### ISSUE TITLE
With --onefile extraction can fail with programs already running

### ISSUE THREAD

**Issue by LeonardoRick** [Nuitka/Nuitka#1000]
* Nuitka version
```
$   python -m nuitka --version
0.6.12.3
Python: 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]
Executable: C:\Program Files\Python38\python.exe
OS: Windows
Arch: x86_6
```
Installed via `pip`

Used libraries
```
firebase-admin==4.5.1
python-dateutil==2.8.1
PyNaCl==1.4.0
cffi==1.14.4
TgCrypto==1.2.2
Pyrogram==1.1.13
APScheduler==3.7.0
python-engineio==4.0.0
python-socketio==5.0.4
Rx==3.1.1
```
The file used to work on `0.6.12` and execute perfectly. It still build right, but when I try to execute, the following error happens:

```
$ ./main.exe
Assertion failed: target_file != INVALID_HANDLE_VALUE, file static_src\WindowsOnefile.c, line 374
```

The `main.exe` inside `main.dist` still works normaly, so probably it's a `--oneflie` error

**Comment by kayhayen** [comment]
You didn't provide the command line you are using here. The Python side won't make much of a different, but the onefile and version information options will.

**Comment by LeonardoRick** [comment]
@kayhayen  sorry about that, this was the comment I used:
`python -m nuitka --standalone --onefile --windows-file-version=1.0.0.0 --windows-company-name=tlg-web-bot --plugin-enable=numpy --plugin-enable=pylint-warnings --include-package=urllib3 --include-package-data --mingw64 tlg/main.py --include-data-file=$HOME/AppData/Roaming/Python/Python38/site-packages/grpc/_cython/_credentials/roots.pem=grpc/_cython/_credentials/ --include-data-file=$HOME/AppData/Roaming/Python/Python38/site-packages/iqbotrealtime/tlgdb/local/__init__.py=tlgdb/local/`

**Comment by kayhayen** [comment]
The caching is not currently actually done, instead it overwrite it each time. So only with `--windows-onefile-tempdir` it will not run into attempting to overwrite a running program, which is what I suspect is going on here.

**Comment by kayhayen** [comment]
Not sure what `--include-package-data --mingw64` is doing. That option has an argument, doesn't it. I wonder if it attempts to do that for a --mingw64 package, that will hardly exist.

**Comment by kayhayen** [comment]
Yup, going to add that options check, now I get this:


> ./bin/nuitka-run --stand --debug --include-package-data --mingw64 some.py 
> FATAL: Error, --include-package-data needs module pattern as an argument

**Comment by kayhayen** [comment]
You probably meant  `--include-package-data=*` didn't you.

**Comment by kayhayen** [comment]
The actual usage of pre-existing files for quicker execution will be implemented, but it's unclear when. Until then the temporary mode must be recommended unfortunately.

**Comment by LeonardoRick** [comment]
Hi @kayhayen. I really tried to understand your messages but I think I'm out of context. I just discovered that the problem to not occur all the times. Sometimes the build finishes and the program runs normally.

You talked somethning about `--windows-onefile-tempdir`. What's the difference abou this and `--onefile`?

About `--include-package-data` I was really thinking aobut adding all data packages needed, so I think `--include-package-data=*` is  the proper command, right? What's weird is that it works sometimes even when I'm passing `--include-package-data` so I guess it's being ignored and maybe I don't need this command.

**Comment by LeonardoRick** [comment]
@kayhayen I searched more about what you talked and now I think I got whats happening. it really  looks like attempting to overwrite a running program and thats a problem because I'm running variuous instances of the same `.exe`. Any ideia on when it will be implemented? I'm here to help with anything I can do. For now, I'm going to try the `windows-oneflie-tempdir` and see how it goes

**Comment by LeonardoRick** [comment]
@kayhayen where this temporary folder is created during execution when`windows-onefile-tempdir` is used?

**Comment by kayhayen** [comment]
@LeonardoRick in the temporary directory of course, notice that next release of Nuitka is adding a feature to specify the location with `--windows-onefile-tempdir-spec`

**Comment by LeonardoRick** [comment]
@kayhayen thats weird, it looks to me that it's building like a plain `--standalone` inside `.dist`. I guess I'll not be able to use a o single file version while `--onefile` give us this error

**Comment by kayhayen** [comment]
The handling of onefile cached and onefile temp modes is now supposed to be perfect in this regard. Locking binaries is also very much avoided.
