### ISSUE TITLE
Eventlet plugin was broken

### ISSUE THREAD

**Issue by SimonNejmann** [Nuitka/Nuitka#1001]
When using `python3 -m nuitka --standalone --plugin-enable=eventlet runserver.py`, I get this error:

> Traceback (most recent call last):
>  ...
>   File "/home/pi/sneCode/gv-nano-standalone/GV-Nano/env/lib/python3.7/site-packages/nuitka/plugins/standard/DataFileCollectorPlugin.py", line 296, in considerDataFiles
>     func, subdir, folders_only = self.known_data_folders[module_name]
> ValueError: not enough values to unpack (expected 3, got 2)

Looking at the code in DataFileCollectorPlugin.py, it seems that there is a problem when eventlet is used. I can see in the git history that `known_data_folders` was changed for eventlet from:
`"eventlet": (_getPackageFiles, ("dns",), False),  # copy other package source`
to
`"eventlet": (_getPackageFiles, "dns"),  # copy other package source`

But this change causes the above error in `considerDataFiles`:
>        if module_name in self.known_data_folders:
>            func, subdir, folders_only = self.known_data_folders[module_name]

I tried to "fix" it in my own copy by just adding the `, False` back to the eventlet entry in `known_data_folders`. But this fails because `_getPackageFiles` was changed to work with the new entry. Adding `False` back makes the function treat it as another package name, which fails when `pkgutil.find_loader` calls `.startswith('.')` on the bool.

With the quick fix failing, I have reached the end of my python/nuitka knowledge, and I hope that somebody else can solve this issue.

**Comment by kayhayen** [comment]
Thanks for the report. Can you share a minimal reproducer, so I don't loose time with that?

**Comment by SimonNejmann** [comment]
Sure. Example program:

```
from flask import Flask, render_template
from flask_socketio import SocketIO

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)

@app.route('/')
def hello_world():
    return 'Hello, World!'
    
if __name__ == '__main__':
    socketio.run(app)
```

I ran it in a fresh virtual environment, pip installed eventlet, Flask, flask_socketio, and nuitka.
`pip freeze` lists this:
```
bidict==0.21.2
click==7.1.2
dnspython==1.16.0
eventlet==0.30.1
Flask==1.1.2
Flask-SocketIO==5.0.1
greenlet==1.0.0
itsdangerous==1.1.0
Jinja2==2.11.3
MarkupSafe==1.1.1
Nuitka==0.6.12.3
python-engineio==4.0.0
python-socketio==5.0.4
six==1.15.0
Werkzeug==1.0.1
```

**Comment by kayhayen** [comment]
@SimonNejmann are you saying that Flask or Flask-SocketIO will behave different when eventlet or greenlet are installed? For me, when I install these only, they are not pulled in.

**Comment by SimonNejmann** [comment]
Yes, from https://flask-socketio.readthedocs.io/en/latest/

> The extension automatically detects which asynchronous framework to use based on what is installed. Preference is given to eventlet, followed by gevent.

As far as I can see the bug should happen as long as `considerDataFiles` in `DataFileCollectorPlugin.py` is run with eventlet as one of the modules it is looking for, this is just the way I know of how to get it to happen.

**Comment by SimonNejmann** [comment]
I just tried again on my raspberry:
```
mkdir test
cd test/
python3 -m venv env
source env/bin/activate
pip install flask
pip install flask_socketio
pip install eventlet
pip install nuitka
nano example.py (copy in the example program)
python3 -m nuitka --standalone --plugin-enable=eventlet example.py
```
Ends with:
```
...
Nuitka-Scons:INFO: Compiled 236 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 236
Traceback (most recent call last):
  File "/home/pi/sneCode/test/env/lib/python3.7/site-packages/nuitka/__main__.py", line 209, in <module>
    main()
  File "/home/pi/sneCode/test/env/lib/python3.7/site-packages/nuitka/__main__.py", line 195, in main
    MainControl.main()
  File "/home/pi/sneCode/test/env/lib/python3.7/site-packages/nuitka/MainControl.py", line 753, in main
    copyDataFiles(dist_dir=dist_dir)
  File "/home/pi/sneCode/test/env/lib/python3.7/site-packages/nuitka/freezer/Standalone.py", line 1632, in copyDataFiles
    for plugin, included_datafile in Plugins.considerDataFiles(module):
  File "/home/pi/sneCode/test/env/lib/python3.7/site-packages/nuitka/plugins/Plugins.py", line 309, in considerDataFiles
    for value in plugin.considerDataFiles(module):
  File "/home/pi/sneCode/test/env/lib/python3.7/site-packages/nuitka/plugins/standard/DataFileCollectorPlugin.py", line 296, in considerDataFiles
    func, subdir, folders_only = self.known_data_folders[module_name]
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by kayhayen** [comment]
@SimonNejmann I managed to reproduce it, the approach there taken is highly dubious, copying Python files, I am changing this ti implicit dependencies, however it seems there are things missing for Cryptodome which is then used through `dnssec`, so these need to be added too.
.

**Comment by kayhayen** [comment]
There is also an eventlet plugin that is just a workaround for including `dns` as a source code, something which isn't really supported anyway, to prevent it from being compiled. I am going to remove that too.

**Comment by kayhayen** [comment]
This got sorted out, interestingly the file scan it does needed to be kept for now, otherwise the patching of greenlet failed, but there was a bug where paths get normalized by the used function, and on Windows that changes package names, so there it wasn't working even after fixing the bug.

I removed folders_only all around, but I intend to move things to the eventlet plugin and check if it's not better to just have implicit dependencies instead, maybe demoted to source code after compilation, rather than working with file copies. There are dependencies of the "dns" after all that get hidden this way.

But the regression is gone, and might be part of a hotfix, not sure now.

**Comment by kayhayen** [comment]
I managed to get rid of the file copying, the dns package is now also properly scanned using `pkgutils.walk_package` rather than file system scanning, and it's included as bytecode rather than as sourcecode, and if the "dns" package is used, the Cryptodome packages used by it are also included, as it's going through the stand method, where Nuitka compiles these packages, and then demotes it to bytecode for the final package.

That is going to make this so much more compatible, it hurts and at the same time gets rid of fragile code there. I will also make the plugin automatic, i.e. it will be enabled by default, as there is no harm in having the same decisions for acceleration mode too, esp. the implicit dependencies.

**Comment by kayhayen** [comment]
ok, the improved version is on factory, that's much cleaner code, effectively removing the code that failed us there.

**Comment by kayhayen** [comment]
Part of the last pre-release.

**Comment by SimonNejmann** [comment]
I just compiled my full project with the development version of Nuitka. It did have one small burp* during the compilation, but it does not seem eventlet related, the compilation continued, and the resulting binary seems to work fine. So I would agree that this issue is fixed.

* The burp was in some tqdm thing (the new progress bar?):
`tqdm/_monitor.py", line 49, in get_instances - RuntimeError: Set changed size during iteration`
I can post the full error in a new issue if you want to, but it was spotted on a dev build (0.6.13rc5) so perhaps the code is too fluid for it to help.

**Comment by kayhayen** [comment]
Part of the 0.6.13 release.
