### ISSUE TITLE
ignore unused code

### ISSUE THREAD

**Issue by Ben-Faessler** [Nuitka/Nuitka#1002]
Hello.
At the moment Nuitka just takes the Python files, optimizes something, converts them to C and compiles them afterwards.
The problem is that Nuitka just converts the whole file. So **unused** variables, functions, classes and so on are simply compiled with.  Is it possible to do this so that Nuitka compiles **only** the **required** code parts?

**Comment by kayhayen** [comment]
There have been attempts to detect what modules are used while running the program. 

Detected required code parts is rather hard. Nuitka currently doesn't do module level optimization yet, but once it does that, this might be achieved, but probably never perfectly, as it takes a whole program optimization to know what is used. There are e.g. programs that will import `__main__` and use things from there. Any other module may still import your module and use what you consider unused on a module level.

However, I have plans to take PGO to a level where from example runs type information is taken, and unused things might be included in the module, but only as bytecode. This will be a while though, as we are still busy trying to get C types in code generation to be more than what they currently are.

Closing, as questions are once answered. The prong of action will be taken independently.
