### ISSUE TITLE
"init_fs_encoding: failed to get the Python codec of the filesystem encoding"

### ISSUE THREAD

**Issue by Alpengreis** [Nuitka/Nuitka#1003]
python -m nuitka --version

0.6.12.3
Python: 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]
Executable: C:\Program Files\Python39\python.exe
OS: Windows
Arch: x86_64

Installed with pip, tested with and without venv ...

I receive always - since I upgraded to Python 3.9.2 (probably) - the following error:

Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
Traceback (most recent call last):
  File "email\encoders.py", line 15, in <module>
  File "asyncio\constants.py", line 1, in <module>
  File "encodings\punycode.py", line 6, in <module>
  File "asyncio\selector_events.py", line 9, in <module>
  File "asyncio\staggered.py", line 5, in <module>
  File "base64.py", line 9, in <module>
  File "poplib.py", line 18, in <module>
ModuleNotFoundError: No module named 'socket'

I still relatively new to all this, please consider :-)

Can you help me?

**Comment by kayhayen** [comment]
Python 3.9.2 is working for me just fine. You were supposed to specify a minimal reproducer and options you were using.

**Comment by Alpengreis** [comment]
Ok, but this with minimal reproducer is a problem (yet). With some "easy" code, it works too here. I will test some things and can hopefully reproduce it then with some lines, which I could post here.

**Comment by kayhayen** [comment]
Ok, in that case make a new issue please.
