### ISSUE TITLE
Question: How to include whole folders in the distribution

### ISSUE THREAD

**Issue by betopicapiedra** [Nuitka/Nuitka#1005]
_Hi, I am trying to include folders that my program uses but, I have found that they can only be added manually.
Is there any way to add them during compilation?
I tried to use this but it didn't work for me
-------------------------------------------------- ------------------------------------------------
nuitka --standalone --plugin-enable = qt-plugins --windows-icon-from-ico = favicon.ico --windows-disable-console --include-data-file = img / *. svg = interface / * .ui * .py = constants / *. py player.py_

**Comment by Pro100rus32** [comment]
Example:

`--include-data-file=E:\Test1\Test2\icons\*=icons\`


Attach all files from a folder to a folder.

**Comment by kayhayen** [comment]
What @Pro100rus32 said is spot on, thanks.

**Comment by betopicapiedra** [comment]
**_Sorry if I ask again. I have already been testing and it still gives me an error ... I attach a photo of my project so that you have a clearer idea of the folders that I have to include_**
------------------------------------------------------------------------------------------
![Captura de pantalla (3)](https://user-images.githubusercontent.com/5233084/109399220-23f62d00-7907-11eb-8568-fa6e84b38b04.png)
