### ISSUE TITLE
Create a build one run anywhere binary!

### ISSUE THREAD

**Issue by brendanator** [Nuitka/Nuitka#1006]
This is a way out there idea but it would be amazing to use https://github.com/jart/cosmopolitan to build a single executable that would run on all platforms. 

I realise this would require a multiplatform version of the python library so it probably impossible right now. However, this is just a cool project that I wanted to draw your attention to it.

**Comment by kayhayen** [comment]
Once there is a CPython that runs like that, making a Nuitka version of it might be possible. But as you stated, for now it's not possible.
