### ISSUE TITLE
[WIN10+MSYS2mingw64+PyGObject] ImportError: cannot import name '_gi' from 'gi'

### ISSUE THREAD

**Issue by maurocsound** [Nuitka/Nuitka#1011]
## Description of the issue
I'm on Windows 10 64bit. 
I would like to compile a python program (which uses GTK, so PyGObject package) into an exe. 
I correctly installed MSYS2 and updated the "MSYS2 MINGW 64-bit" environment as per instructions.

I installed nuitka with the following command:
```shell
$ pacman -S mingw-w64-x86_64-python-nuitka
```

Then I ran, in the dir where I have my python script named 'p.py'):
```shell
$ python -m nuitka --standalone --mingw64 p.py
```

It seems to go all right... There are no errors from the nuitka script. Now I have 2 dir: p.build and p.dist. I go into the p.dist subdir and when I try to run the generated exe I have the following error and the script doesn't run:

```shell
$ ./p.exe
Traceback (most recent call last):
  File "C:\msys64\home\Mauro\prova\P7B09~1.DIS\p.py", line 1, in <module>
  File "C:\msys64\home\Mauro\prova\P7B09~1.DIS\gi/__init__.py", line 40, in <module gi>
ImportError: cannot import name '_gi' from 'gi' (C:\msys64\home\Mauro\prova\P7B09~1.DIS\gi/__init__.py)

```

This is the content of the p.py script I tried to compile:
```
# p.py:
import gi

print("Hello!")
```

## Context information (for bug reports)
```
$ python -m nuitka --version
0.6.12.3
Python: 3.8.8 (default, Feb 20 2021, 07:16:03)  [GCC 10.2.0 64 bit (AMD64)]
Executable: C:/msys64/mingw64/bin/python.exe
OS: Windows
Arch: x86_64
```

**Comment by maurocsound** [comment]
P.S.: I installed the pygobject package as per instructions from the official [docs](https://pygobject.readthedocs.io/en/latest/getting_started.html#windows-getting-started):

`
pacman -S mingw-w64-x86_64-gtk3 mingw-w64-x86_64-python3 mingw-w64-x86_64-python3-gobject
`

**Comment by kayhayen** [comment]
Wow, really, this can only be pip installed on Windows, and then only with msys2, can you find out, what happens to this code:

```
        elif full_name == "gi._gi":
            gtk_dll_path = locateDLL("gtk-3")

            if gtk_dll_path is not None:
                dist_dll_path = os.path.join(dist_dir, os.path.basename(gtk_dll_path))
                shutil.copy(gtk_dll_path, dist_dll_path)

                return ((gtk_dll_path, dist_dll_path, None),)
```

It's in the implicit imports plugin and maybe, this PyGTK is now GTK4 based, and it's simply not finding the DLL now. Could be as simple as fixing the DLL name. Do you even enter that code?

Yours,
Kay

**Comment by maurocsound** [comment]
Sorry, I don't understand... Where is it that piece of code? Nuitka sources? 
Anyway PyGObject currently is GTK3 based. And Python+GTK3 (so, with PyGObject) works fine on my Windows system if I use the standard python interpreter (in the msys2-mingw64 environment) to run the script. But when trying to compile the script with Nuitka, even a script with just a simple "import gi" makes the generated exe stop with an error. 

P.S.: GTK in python uses many DLLs:

_gi-cpython-38.dll
libgtk-3-0.dll
libgdk-3-0.dll
libgobject-2.0-0.dll
libgirepository-1.0-1.dll
libgio-2.0-0.dll
...and many others...

so I don't know if that extract of code you posted does the things right...

**Comment by maurocsound** [comment]
I don't know if this can help you but on my Win10 system if I write this in a python shell (within msys2-mingw64 environment with pygobject package correctly installed):

```
>>> import ctypes.util
>>> ctypes.util.find_library("gtk-3")
```

I get nothing.

But if I do this:

```
>>> ctypes.util.find_library("libgtk-3-0")
'C:\\msys64\\mingw64\\bin/libgtk-3-0.dll'
```

...I get the right DLL.

**Comment by kayhayen** [comment]
Find it in the Nuitka code, and replace it and see how that goes. Report if it works, because if it, we could just make an if ... is None ... locate the other kind of trick. Not sure if it can ever be OK to not find that DLL. Chances are Nuitka will find the other DLLs as being used by that one, which is precisely why manual copying is not supported and not likely to work, at not work well at least.

**Comment by maurocsound** [comment]
Hi, I tried to replace this (in the file that on my system is located in 'C:\msys64\mingw64\lib\python3.8\site-packages\nuitka\plugins\standard\ImplicitImports.py'):

```
elif full_name == "gi._gi":
            gtk_dll_path = locateDLL("gtk-3")
```

with this:

```
elif full_name == "gi._gi":
            gtk_dll_path = locateDLL("libgtk-3-0")
```

but after compiling with nuitka the result is the same:

`ImportError: cannot import name '_gi' from 'gi'`

Then I checked the gi folder inside the created p.dist dir and I found this file:

`_gi-cpython-38.pyd`

I renamed it in "_gi.pyd" and now the error is different:

`ModuleNotFoundError: No module named 'gi._error'`

So I added in the ImplicitImports.py this (at line 268):

```
        elif full_name == "gi":
            yield "gi._error"
```

and now the p.exe runs!

But I should do more tests (the test script is too simple), and I don't understand why the file created by nuitka in the 'gi' subfolder is '_gi-cpython-38.pyd' rather than '_gi.pyd'.

**Comment by maurocsound** [comment]
Ok, now I tried with the following script (basically it creates a Gtk window and shows it):

```
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

window = Gtk.Window(title="Hello World")
window.show()
window.connect("destroy", Gtk.main_quit)
Gtk.main()
```

after renaming the file gi/_gi-cpython-38.pyd to gi/_gi.pyd, running the exe gives the following error:

`ValueError: Namespace Gtk not available`

**Comment by kayhayen** [comment]
@maurocsound why did you remove the traceback information in your last message, as I can't run it, I would like to know which import does it.

On the renaming, what bites us there, is that some people pretend DLLs are extension modules, and then they hard code their idea about the names. It might be that `gi._gi` is that kind of fake. If this was loaded as an extension module, it would work either way. 

Nuitka puts entension modules under the version specific names for a while now, but arguably, for standalone inclusion, that may not be a good idea due to that kind of issue. I am going to change that now, also adding the DLL search fallback.

**Comment by kayhayen** [comment]
As for the implicit dependency, there already is this:

```
        elif full_name == "gi._gi":
            yield "gi._error"
```

Can you check, why this code branch is no taken:

```
        elif full_name == "gi._gi":
            yield "gi._error"
```

It ought to go into that already, otherwise the `locateDLL` I would expect to not happen as it's branching on the same module name.

**Comment by maurocsound** [comment]
> @maurocsound why did you remove the traceback information in your last message, as I can't run it, I would like to know which import does it.

Sorry, here is the traceback:

```
$ ./p.exe
Traceback (most recent call last):
  File "C:\msys64\home\Mauro\prova\P7B09~1.DIS\p.py", line 2, in <module>
  File "C:\msys64\home\Mauro\prova\P7B09~1.DIS\gi/__init__.py", line 126, in require_version
ValueError: Namespace Gtk not available
```

**Comment by maurocsound** [comment]
I tried to add a `print(full_name)` for debugging purposes in the `considerExtraDlls` method inside the ImplicitImports.py file, and after that nuitka gives these dll names related to gi when I try to build the exe with it:

gi
gi._constants
gi._error
**gi._gi-cpython-38**
gi._propertyhelper
gi._signalhelper
gi.docstring
gi.importer
gi.module
gi.overrides
gi.repository
gi.types

As you can see, there is no gi._gi in the above list (but there is a `gi._gi-cpython-38`), so this branch will never run:

```
        ...
        elif full_name == "gi._gi":
            gtk_dll_path = locateDLL("libgtk-3-0")
        ...
```

**Comment by maurocsound** [comment]
P.S.: I tried to replace gi._gi with gi._gi-cpython-38 in the above piece of code, and now the libgtk-3-0.dll is included in the p.dist dir, but running the exe gives always the same error of "Namespace Gtk not available".

**Comment by flozz** [comment]
@maurocsound for the `Namespace Gtk not available` error, you can fix it by providing the path to the typelib files through an environment variable:

    export GI_TYPELIB_PATH="/c/gtk-build/gtk/x64/release/lib/girepository-1.0"

(you must change the path, mine is for gvsbuild)

**Comment by zegervdv** [comment]
I've noticed this is also the case on linux.
I was running an strace on a nuitka build and saw the typelib files are still loaded from the system installation.

When exporting the env variable, most are loaded correctly.

Could this env variable be set automatically to the right directory? Based on the location of the binary I assume?

**Comment by kayhayen** [comment]
That environment variable is king indeed, we need a plugin to provide it as pre-load code, there is precence to that in other plugins, so actually this could be done by others too. Also the files must be included as data files I guess, or as a data directory even. And the question is to know which one, typically ghi will have code with a function to call, otherwise we need to mimic it, but if you have code to run with an import of it, there is also precedence of that. I would love to see this fixed, gi is naturally important.

**Comment by zegervdv** [comment]
I assume it could be something similar to https://github.com/Nuitka/Nuitka/blob/6441e0c5e3442987a3e7640cca07200dd930f30a/nuitka/plugins/standard/TkinterPlugin.py#L98?

If so, I will try to prepare a PR later this week.

**Comment by kayhayen** [comment]
Yes, that's the same kind of thing @zegervdv , and then question is, are these data files or DLLs. The later need to be provided in a different way. You need to find `known_data_dirs` in the `nuitka/plugins/standard/DataFileCollectorPlugin.py` in case its merely data files. I am one day going to make these things a yaml config, but for now, you can just add it there. If it's DLLs you should go with this for ease:

```
    def getExtraDlls(self, module):
        if module.getFullName() == "glfw":
            dll_filename = self._getDLLFilename()

            yield makeDllEntryPoint(
                source_path=dll_filename,
                dest_path=os.path.join("glfw", os.path.basename(dll_filename)),
                package_name="glfw.library",
            )
```

Currently plugins do data files and DLLs in `considerExtraDlls` of their plugin, but that's a lot of code that is redudent, and this is much nicer, and you can work using `getFileList` from `nuitka.utils.FileOperations`  to list a folder with filtering, recursively, to yield those DLL entry points. One day the `considerExtraDlls` is supposed to go away.

**Comment by kayhayen** [comment]
This is part of the 0.6.18 release.
