### ISSUE TITLE
cannot import 'uic' from 'PyQt5'

### ISSUE THREAD

**Issue by wsnow99** [Nuitka/Nuitka#1014]
python 3.7.9  nuitka 0.6.12 in anaconda by pip, Windows 10 64 bit
I try to package a PyQt5 script, everything was going well, But in the end there was a ImportError:

```
Traceback (most recent call last):
  File "E:\exe\o\QtUi.dist\QtUi.py", line 12, in <module>
  File "E:\exe\o\QtUi.dist\pyqtgraph\__init__.py" , line 13, in <module>
    from .Qt import QtGui, mkQApp
  File "E:\exe\o\QtUi.dist\pyqtgraph\Qt.py", line 191, in <module>
    from PyQt5 importb QtGui, QtCore, QtWidgets, uic
ImportError: cannot import 'uic' from 'PyQt5' (E:\exe\o\QtUi.dist\PyQt5\__init__.py)
```

I'm not sure how to solve it

**Comment by Ja7adR** [comment]
I think in pyqt5 v 5.15.x `uic` removed.

**Comment by kayhayen** [comment]
Thanks @Ja7adR seems to be yet another case of a script that wouldn't run with Python being reported as a Nuitka error.
