### ISSUE TITLE
pyside2 compilation

### ISSUE THREAD

**Issue by crostow** [Nuitka/Nuitka#1015]
I have a project that consists of 3 folders and 2 .py files in the root of the project.

How would the instruction be so that it will take all the files and include them.

I have tried with this

nuitka3 --standalone --plugin-enable = qt-plugins --windows-disable-console Setup.py

It does not mark any error but when I want to run the application nothing happens.

**Comment by Ja7adR** [comment]
use `--plugin-enable=qt-plugins --include-qt-plugins=sensible,styles` and remove `--windows-disable-console`

after compile open executable file and see console error.

**Comment by kayhayen** [comment]
The PySide2 is not currently supported really, and ignored by the qt-plugins plugin though. However, support is being added for a future release in #1009 so there is hope, but not right now that code is cooking, and not even on factory branch yet.

In unrelated news, there is now options to force stdout and stderr to files in the develop version, so in principle, the disabling of the console doesn't have to be hiding errors anymore @Ja7adR
