### ISSUE TITLE
PyQT5 Compilation opens with empty window

### ISSUE THREAD

**Issue by jiri-otoupal** [Nuitka/Nuitka#1019]
Iam trying to compile hello world Qt Qml app so far I had tried nuitka version 0.6.5,0.6.7,0.6.8,Current stable and current dev version, but so far every version has the same issue.

In all the versions window opens empty without nothing in it.
Iam compiling on RHEL7 or Ubuntu 18.04

Source trying to compile:

main.py
```


import sys
import PyQt5.QtQuick

from PyQt5.QtCore import QUrl
from PyQt5.QtGui import QGuiApplication
from PyQt5.QtQml import QQmlApplicationEngine


if __name__ == "__main__":
    app = QGuiApplication(sys.argv)
    engine = QQmlApplicationEngine()
    context = engine.rootContext()
    engine.load(QUrl("main.qml"))
    if not engine.rootObjects():
        sys.exit(-1)
    sys.exit(app.exec_())
```
main.qml
```

import QtQuick 2.13
import QtQuick.Dialogs 1.0
import QtQuick.Window 2.13
import QtQuick.Controls 2.15
import QtQuick.Layouts 1.11
import QtGraphicalEffects 1.0
import QtQuick.Timeline 1.0



Window {
    id: window
    width: 800
    height: 480
    visible: true
    color: "#0c226f"
    property int installProgress: 0
    title: qsTr("Hello World")
    maximumHeight: height
    maximumWidth: width

    minimumHeight: height
    minimumWidth: width
}
```

My nuitka flags:

`python3.9 -m nuitka main.py --show-progress --remove-output --linux-onefile-icon=sprits/icon.ico --plugin-enable=qt-plugins --include-qt-plugins=all --include-module=pycrosskit --include-module=clipboard --follow-imports --python-flag=nosite --experimental=use_pefile --experimental=use_pefile_recurse --enable-plugin=dill-compat --plugin-enable=pylint-warnings --onefile --standalone`

If i run the generated executable it launches a empty window with anything in it.
[Here](https://gofile.io/d/FfxYDE) is the test case with environment.

**Comment by kayhayen** [comment]
Your experimental flags are noise only and have no effect anymore. Do not use --show-progress as it diables the cool new progress bars. That's for debugging lack of progress only these days.

But what makes you think the output should not be empty? It was for me when I ran with with Python 3.8 on Windows just now. It's a blue Winedows with correct title, and what else would there have to be?

I think your example is somehow maybe too minimal.

**Comment by jiri-otoupal** [comment]
If your window opened as a blue window with white text its working. But problem is that my compiled version on Ubuntu 18.04 opens with gray pattern and there is nothing.
