### ISSUE TITLE
PySide2 Signal sender() method not working

### ISSUE THREAD

**Issue by RESP3CT88** [Nuitka/Nuitka#1020]
Nuitka version 0.6.12rc3
Python: 3.8.5 (default, Jul 28 2020, 12:59:40) 
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64

In both PySide2/PyQt you are supposed to be able to call a method called "sender()" on the method that is receiving the signal. See below example. Works fine when running in python. But I get this error below when running it after being compiled by Nuitka . No errors in the compilation.

```
Traceback (most recent call last):
  File "/tmp/.mount_test.bYmBkiz/test.py", line 24, in buttonClicked
AttributeError: 'NoneType' object has no attribute 'text'
```

```
import sys
from PySide2.QtWidgets import QApplication, QMainWindow, QPushButton

class Example(QMainWindow):

    def __init__(self):
         super().__init__()
         self.initUI()

    def initUI(self):
        btn1 = QPushButton('Button 1', self)
        btn1.move(30, 50)
        btn1.clicked.connect(self.buttonClicked)
        self.setGeometry(300, 300, 300, 150)
        self.setWindowTitle('Window')
        self.show()

    def buttonClicked(self):
        sender = self.sender()
        self.statusBar().showMessage(sender.text() + ' changed')

if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = Example()
    sys.exit(app.exec_())

```

**Comment by kayhayen** [comment]
You have excluded information on how you compile the program, this was I cannot tell if you used the new PySide2 plugin that is currently still on factory, but PySide2 is only supported freshly: https://nuitka.net/doc/factory.html and #1009
