### ISSUE TITLE
PySide2 Extra arguments for Slots are not ignored from Signals

### ISSUE THREAD

**Issue by RESP3CT88** [Nuitka/Nuitka#1022]
0.6.13rc6 *Factory branch*
Python: 3.8.5 (default, Jul 28 2020, 12:59:40) 
OS: Linux

Just a minor thing, seems that slots are not ignoring extra arguments from signals unlike how it actually works in Qt.

> The signature of a signal must match the signature of the receiving slot. (In fact a slot may have a shorter signature than the signal it receives because it can ignore extra arguments.) 
https://doc.qt.io/qt-5/signalsandslots.html

I noticed this when I was using the QProcess "finished" signal, which results in an error about receiving too many arguments.
`TypeError: finished() takes 1 positional argument but 2 were given`

Sample Code to Produce Error
```
import sys
from PySide2.QtWidgets import QApplication
from PySide2.QtCore import Slot, Signal, QProcess, QObject


class Main(QObject):

    def __init__(self):
        QObject.__init__(self)

    def finished(self):
        print('process has finished')
        sys.exit()

    def ping(self):
        self.proc = QProcess(self)
        self.proc.finished.connect(self.finished)
        self.proc.readyReadStandardOutput.connect(self.ping_read)
        self.proc.start('ping', ['8.8.8.8', '-c', '4'])

    def ping_read(self):
        # proc = self.sender()
        data = self.proc.readAllStandardOutput()
        print(data)


if __name__ == "__main__":
    app = QApplication([])

    main = Main()
    main.ping()

    sys.exit(app.exec_())
```

Compilation:
```
ubuntu@ubuntu:~/Test2/main$ sudo python3 -m nuitka --enable-plugin=pyside2 main.py
Nuitka:INFO: Starting Python compilation.
Nuitka:INFO: Completed Python level compilation and optimization.                                           
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.                                
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Compiled 12 C files using ccache.                                                        
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'disabled': 1
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 10
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 1
Nuitka:INFO: Keeping build directory 'main.build'.
Nuitka:INFO: Successfully created 'main.bin'.

```

Output:
```
ubuntu@ubuntu:~/$ sudo ./main.bin
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=115 time=16.8 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=115 time=16.6 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=115 time=12.1 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=115 time=12.9 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 12.125/14.613/16.837/2.124 ms
TypeError: finished() takes 1 positional argument but 2 were given
```

**Comment by kayhayen** [comment]
Hi there,

> Just a minor thing, seems that slots in Nuitka don't ignore extra arguments from signals unlike how it actually works in Qt.

That may well have a point. The wrappers we create do accept star arguments, so there is no way for Qt to know not to pass them. I will enhance that, thanks for your report, that seems like an incompatibility to be fixed.

**Comment by RESP3CT88** [comment]
Awesome! Thanks for all your work on this amazing project.

**Comment by kayhayen** [comment]
Part of the 0.6.13 release.

**Comment by bersbersbers** [comment]
Hi, I am facing the same issue in a similar context. Since there is no commit assigned to this issue, may I ask how you solved this? A hint at the code may be completely sufficient. Thanks!

**Comment by kayhayen** [comment]
Check this out https://nuitka.net/pages/pyside2.html

**Comment by bersbersbers** [comment]
Understood, thanks! If your changes applied only to PySide2 and not PySide6, or if they were made on the PySide side (and not within nuitka), it is rather unlikely they will help me with my problem. fyi, https://stackoverflow.com/q/76596620

**Comment by kayhayen** [comment]
I made them to PySide6 and PySide2 both. I do not know what your problem is, and I won't read an external site to figure out, make a new report please.
