### ISSUE TITLE
[MacOS] Compilation error with --plugin-enable tk-inter

### ISSUE THREAD

**Issue by xvolte** [Nuitka/Nuitka#1024]
**The issue :** 

When compiling a program on MacOsX with --plugin-enable=tkinter, I am getting the following error:
`FATAL: tk-inter: Could not find Tcl. Aborting standalone generation.`

From my understanding, I'm not even sure if the latest version of Tkinter needs any TCL libs as I understand that the TCL is now embedded within Tkinter since python 3.7.2+

`if you are using a Python from any current python.org Python installer for macOS (3.9.0+, 3.8.0+, or 3.7.2+), no further action is needed to use IDLE or tkinter. A built-in version of Tcl/Tk 8.6 will be used.`
see here:
https://www.python.org/download/mac/tcltk/

**The same code source works fine with Nuitka on the following OS : Windows10, Ubuntu, CentOS**. Only MacOs version of Nuitka is not working.

Thanks in advance for your help. (and an enormous thank you for creating Nuitka !)

* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

> xvolte@xvolte-MacBook %   python3.9 -m nuitka --version
> 0.6.12.4
> Python: 3.9.1 (v3.9.1:1e5d33e9b9, Dec  7 2020, 12:10:52) 
> Executable: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9
> OS: Darwin
> Arch: x86_64

* How did you install Nuitka and Python
python 3.9 from via official MacOs pkg (python-3.9.1-macosx10.9.pkg), Nuitka via pip3.9
no virtual env.

* Many times when you get an error from Nuitka, your setup may be special
no issue with an hello world. the issue comes from Nuitka with Tkinter not finding TCL. it work fine if running the py file directly.

* The specific PyPI names and versions

> xvolte@xvolte-MacBook % python3.9 -m pip freeze
> certifi==2020.12.5
> cx-Freeze==6.5.3
> importlib-metadata==3.4.0
> libpff-python==20161119
> lxml==4.6.2
> Nuitka==0.6.12.4
> psutil==5.8.0
> pycryptodome==3.10.1
> PyPDF2==1.26.0
> regex==2020.11.13
> zipp==3.4.0

**Comment by kayhayen** [comment]
Do you have a reference for the embedding part? I cannot confirm it on any Python install I have.

Also consider https://nuitka.net/pages/commercial.html because at this time, I won't give priority to macOS issues like this one otherwise, and you might be a commercial user.

**Comment by xvolte** [comment]
Hello,

Hello again, the only reference I have, I already posted it, the official python.org website : 
https://www.python.org/download/mac/tcltk/
**it looks like a MacOS specificity...**

I can also confirm that running the code directly with python3.9 does work on my MacOS machine without having installed anything else.
I also noticed that Nuitka compiles without error if I do not put --plugin-enable=tk-inter, but then I get a full black Tk() window instead of what I would have normally (several labels and entries and two buttons)

Good to know for the commercial part, I didn't know - I'm developing a python script with a GUI but I'm not selling the tool to anyone.
what would consider me as "commercial" user ?

thanks in advance,

**Comment by xvolte** [comment]
also, maybe this can help ?
Looks like cxFreeze are having the same issues...

https://github.com/marcelotduarte/cx_Freeze/issues/849

**Comment by xvolte** [comment]
following this "work around" fixed the problem, so maybe it is a python issue after all ?

https://github.com/marcelotduarte/cx_Freeze/issues/849#issuecomment-765114137

`Found a work around for python3.9 on mac Big Sur. Borrow tcl and tk 8.6.11 from python 3.10 0a3 as follows:

install python3.10 0a3
don't bother trying cx_freeze under this early 3.10, it, and many other libraries (like regex), don't work yet in this early 3.10 pre-release
cd into /Library/Frameworks/Python.framework/Versions/3.9/lib
mv tcl8.6 tcl8.6.distributed
mv tk8.6 tk8.6.distributed
cp -r /Library/Frameworks/Python.framework/Versions/3.10/lib/tcl8.6 .
cp -r /Library/Frameworks/Python.framework/Versions/3.10/lib/tk8.6 .
cd /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload
mv _tkinter.cpython-39-darwin.so _tkinter.cpython-39-darwin.so.distributed
cp /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/lib-dynload/_tkinter.cpython-310-darwin.so _tkinter.cpython-39-darwin.so
This seems to make tkinter operable again under cx_freeze (no more black window)`

I then compiled **without** --plugin-enable=tk-inter and it works like a charm, with Nuitka.

so it is not an official fix, but it does work.

**Comment by kayhayen** [comment]
There are environment variables in the plugin that you can specify, look them up in the Nuitka code of the tk-inter plugin, then you can spare yourself the copying.

However, why would your code work with CPython 3.9 without these? Does it? I am often getting reports about broken CPython installations that are phrased to be Nuitka issues, but the original program doesn't run. This looks like a case of that, or maybe a missed optimization, because CPython can pick up something from the system there. However, that's not going to run well as as standalone version, but going back to older OSes is usually not advisable anyway, you compile on the oldest OS.

You are a commercial user if you are willing to pay to get something solved rather than to wait for an eventual solution and if you are not, OK. I am putting this note where I won't bother unlesss I get paid to do something immediately.

Yours,
Kay
