### ISSUE TITLE
Include whole directory structure in standalone

### ISSUE THREAD

**Issue by matt-hu** [Nuitka/Nuitka#1025]
I am writing a game in pygame that I would like to package using Nuitka. However, it requires large amounts of images stored in a directory structure that need to be copied to the build output. There is the main images folder, which then has several subdirectories containing images (and sometimes more subdirectories within the subdirectory). Is there an easy way to accomplish this? I know you can use `--include-data-file`, however it would take a long time to go through and add each subdirectory...

**Comment by kayhayen** [comment]
Did you read the documentation of that option, and try the obvious? Not saying it works, but there is an easy attempt right there using patterns. That might work like `--include-data-file=yourdir/*:yourdir/`. Not sure what the underlying code does with directories matching, but give it a try please. I agree that another option for directories would be nicer to read or maybe what's working.

**Comment by matt-hu** [comment]
I did try that, but I ran into a couple of problems, the first one being patterns didn't work in zsh. However, they worked in bash, so not sure what was going on there...
Secondly, when I used the pattern it copied the files in the directory, but when it reached a subdirectory it failed, complaining that it was a directory, not a file.
One pattern that did work was `yourdir/**/*`. This copied all of the files, but didn't preserve the directory structure, so the program was unable to find what it needed.
Hope this helps, sorry I didn't give these details in the first comment...

**Comment by kayhayen** [comment]
Using quotes is really required, your shell should never see those patterns, Nuitka will not like the result. 

Thanks for doing the research. I will make an enhancement one I find the time, that adds the new option. Even if it were possible with current means, it would still be ugly and unlike to be discovered.

Yours,
Kay

**Comment by matt-hu** [comment]
@kayhayen Thanks very much! I really like what I have seen so far, so for now I will just zip up the standalone to distribute...
Looking forward to being able to use onefile though!

**Comment by kayhayen** [comment]
This is on the factory branch right now. https://nuitka.net/doc/factory.html and will be in the next release.

**Comment by matt-hu** [comment]
Thanks!

**Comment by kayhayen** [comment]
Part of the 0.6.14 release.
