### ISSUE TITLE
Error :no such option: --recurse-all

### ISSUE THREAD

**Issue by gauthierbuttez** [Nuitka/Nuitka#1027]
Hi,

This is my environment:
nuitka 0.6.12.4
Python: 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
Executable: C:\Users\Nino\AppData\Local\Programs\Python\Python37\python.exe
OS: Windows
Arch: x86_64

I just updated Nuitka today. I wanted to compile my python code with the usual command:
`python -m nuitka --standalone --mingw64 --include-module=psutil --plugin-enable=pylint-warnings --enable-plugin=numpy --enable-plugin=qt-plugins --show-progress --show-scons --follow-imports --recurse-all --windows-icon=favicon.ico MyScript.py`

And I get this error message:
`__main__.py: error: no such option: --recurse-all`

So I removed this option to give a try and I get this time this error message:
`__main__.py: error: ambiguous option: --windows-icon (--windows-icon-from-exe, --windows-icon-from-ico?)`

Can you help me to fix these issues please?

**Comment by kayhayen** [comment]
@gauthierbuttez The recurse options are now --follow style options, check help output, these were the names in the older versions as well. And for the icon option, the `--windows-icon-from-ico` matches the old icon option.

**Comment by gauthierbuttez** [comment]
Thank you for your help.
