### ISSUE TITLE
Can Nuitka create extension modules that works with more Python versions. 

### ISSUE THREAD

**Issue by gec84** [Nuitka/Nuitka#1028]
I wonder if there is a way to create a pyd file that will work with other versions of python (not only the version with which it was created)?
I created the pyd with python version 3.9 but then I couldn't use it with other versions like 3.8 or 3.6.

**Comment by kayhayen** [comment]
The created extension modules fit only precisely for the Python version they are created for nothing else. If you want to support multiple Python version, you need compile with each version. 

It will (for Python3) produce filenames ignored by all other versions, so you could put them in the same place alongside. The Python2 filename will be bad in this regard as it will load with Python3's but not be recognize as an extension module, including the Python version in the extension module filename is new in Python3.
