### ISSUE TITLE
multiprocess and dill cannot transfer objects in main script, giving KeyError: '__main__'

### ISSUE THREAD

**Issue by sla-te** [Nuitka/Nuitka#1030]
**Problematic package: https://github.com/uqfoundation/multiprocess**
_Description:_ `multiprocess` is a fork of multiprocessing which uses dill instead of pickle for sharing objects between processes which causes significant improvements when it comes to sharing or passing objeccts to processes. In my case the application requires it becasue we share a lot of complex objects between our processes, and it simply is not workable with the regular multiprocessing implementation.

After compiling and starting the excecutable via CMD, we get:
```
Traceback (most recent call last):
  File "C:\Users\chwba\PYCHAR~1\NUITKA~3\APP~1.DIS\app.py", line 21, in <module __parents_main__>
  File "C:\Users\chwba\PYCHAR~1\NUITKA~3\APP~1.DIS\multiprocessing\spawn.py", line 74, in freeze_support
  File "C:\Users\chwba\PYCHAR~1\NUITKA~3\APP~1.DIS\multiprocessing\spawn.py", line 116, in spawn_main
  File "C:\Users\chwba\PYCHAR~1\NUITKA~3\APP~1.DIS\multiprocessing\spawn.py", line 126, in _main
  File "C:\Users\chwba\PYCHAR~1\NUITKA~3\APP~1.DIS\__init__.py-postLoad", line 29, in _create_compiled_function3
KeyError: '__main__'
```
Compiled executable: https://nextcloud.mnwd.in/s/t4xHomW8GBQKwY9
Compilation log: https://nextcloud.mnwd.in/s/rZKNoYPLTn8qb6E

**Compiled with:**
```
python -m nuitka --follow-imports^
                 --show-progress^
                 --show-scons^
                 --warn-unusual-code^
                 --assume-yes-for-downloads^
                 --warn-unusual-code^
                 --plugin-enable=pylint-warnings^
                 --plugin-enable=multiprocessing^
                 --plugin-enable=dill-compat^
                 --standalone^
                 --msvc=14.2^
                 app.py > compile.log
```
(Tested with clang and msvc=14.2, with and without multiprocessing plugin/dill-compat)

**Code snippet to reproduce:**
```
from time import sleep
from multiprocess import Process, freeze_support

def do_work():
	print("working..")
	sleep(3)

def main():
	p = Process(target=do_work)
	p.start()

if __name__ == "__main__":
	freeze_support()
	main()
```

**Used requirements:**
```
multiprocess
```

**Nuitka**
```
0.6.13
Python: 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]
Executable: C:\Users\chwba\PycharmProjects\nuitka_mp_pickling_error\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
```
(Installed via `python -m pip install nuitka`)

**Comment by kayhayen** [comment]
The dill plugin of Nuitka might exist only because of this package you are using there. It may also have been another one, but they are all similar I guess. Can you try if it works moved outside of `__main__` as that is a special case with multiprocessing, which would only have `__parents_main__` (spelling). For normal modules it ought to work, does it?

**Comment by chwba** [comment]
Its not possible to call freeze_support outside of `__main__`, as described in the official documentation of multiprocessing (https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support), which also applies for `multiprocess` multiprocess.

**Comment by kayhayen** [comment]
@chwba then you have that and only that on main and call `somewhere_else.main()` from another file.

**Comment by chwba** [comment]
Sorry, but im not sure I understand..... I have to create a separate file to call my main?

**Comment by kayhayen** [comment]
I am saying that dill might work everywhere but in the main script.

There is something fishy about `__main__` as a module, it's not really one, so things have to take special action to work there, and the bug in Nuitka is only that. Still worth fixing, but you got a workaround clearly. Few people put their code in the main script, indeed it's often generated and only doing roughly what yours is doing now.

And the error would relate to the dill support only. I think it may be as easy as mapping `__main__` to `__parents_main__` or whatever it is in forks and vice versa. Very ugly, but true. I probably need to revisit this, it's also ugly in poluting every module code, even if not being active as a plugging. With a workaround like that though, it's not an immediate priority.

**Comment by chwba** [comment]
Should probably leave a note about this in the docs as the official documentation of multiprocessing will be misleading for anyone running into this one.

**Comment by KevinRodriguez777** [comment]
This works as expected nowadays
