### ISSUE TITLE
Can multiple executables share a distribution folder?

### ISSUE THREAD

**Issue by kuiber** [Nuitka/Nuitka#1034]
Is it possible to create multiple binaries from a single project and have them share the same dist directory? I've managed to create multiple binaries, but they are all in separate folders, making the distribution require a lot of disk space.

My project is structured like this:

```
.
├── exec
│   ├── exe_1.py
│   ├── exe_2.py
│   ├── exe_3.py
│   ├── exe_4.py
│   └── exe_5.py
├── lib
│   ├── lib_1.py
│   ├── lib_2.py
│   └── lib_3.py
├── __main__.py
└── requirements.txt
```

I'd like to make a distributable where I have 6 executables in the final product - all the files in the `exec` directory and the `__main__.py` file. The `lib` directory is full of code that is imported by the rest of the project, and the `requirements.txt` file has a list of packages that the program needs.

I've managed to run it with the following command args

`python -m nuitka --show-progress --show-scons --standalone sample_project/__main__.py `

which successfully creates a `__main__.dist` directory but I can only ever get 1 binary. When I run it against a new file, it creates a new binary in a different folder.

Is there any way to have the binaries that are created use the same .dist directory? Or maybe a different way of packaging with nuitka that I'm not thinking about?

Thanks

**Comment by kayhayen** [comment]
The sharing of the distribution folder is not yet implemented, but there is a mid term plan to do that. Closing this, as that's what we do with questions.
