### ISSUE TITLE
Problem with pkg_resources and openapi_spec_validator

### ISSUE THREAD

**Issue by ed0001tt** [Nuitka/Nuitka#1036]
**optimization change implemented in Nuitka 0.6.13**

> possibly related to:
> \nuitka\importing\IgnoreListing.py

**problem description**
python package "openapi_spec_validator" requires pkg_resources but not imported

> \openapi_spec_validator\schemas.py
> line 4: from pkg_resources import resource_filename

link: https://pypi.org/project/openapi-spec-validator/

**Comment by kayhayen** [comment]
Minimal example is always needed.

**Comment by ed0001tt** [comment]
Sample python code <test.py>
> from pkg_resources import resource_filename
> path = '/resources/schemas/v{0}/schema.json'.format('2.0')
> path_resource = resource_filename('openapi_spec_validator', path)
> print('path_resource : {}'.format(path_resource))

run python code:
> python -m test
> path_resource : /home/.../site-packages/openapi_spec_validator/resources/schemas/v2.0/schema.json

run command on version Nuitka 0.6.13:
> python -m nuitka --include-package-data=openapi_spec_validator --include-package-data=jsonschema --show-modules --show-modules-output=nuitka-modules.txt --standalone test.py

more <nuitka-modules.txt>
> ...
> Nuitka-Inclusion:INFO: Included uncompiled module 'pkg_resources'.
> Nuitka-Inclusion:INFO: Included uncompiled module 'pkg_resources.extern'.
> Nuitka-Inclusion:INFO: Included uncompiled module 'pkg_resources.extern.appdirs'.
> Nuitka-Inclusion:INFO: Included uncompiled module 'pkg_resources.extern.packaging'.
> ...

./test
> ...@LenovoT490-2:~/debug-nuitka-package-versions/test.dist$ ./test
> Traceback (most recent call last):
>   File "/home/.../debug-nuitka-package-versions/test.dist/test.py", line 1, in <module>
>   File "/home/.../debug-nuitka-package-versions/test.dist/pkg_resources/__init__.py", line 75, in <module>
>   File "/home/.../debug-nuitka-package-versions/test.dist/pkg_resources/extern/packaging/__init__.py", line 6, in <module>
>   File "/home/.../debug-nuitka-package-versions/test.dist/pkg_resources/extern/__init__.py", line 58, in create_module
>   File "/home/.../debug-nuitka-package-versions/test.dist/pkg_resources/extern/__init__.py", line 54, in load_module
> ImportError: The 'packaging.__about__' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.

Suspected problem:
> /pkg_resources/_vendor/packaging/* not imported by Nuitka

Another attempt on Nuitka 0.6.12.4 with the same command yields <nuitka-modules.txt>:
> ...
> Nuitka-Inclusion:INFO: Included uncompiled module 'pkg_resources'.
> Nuitka-Inclusion:INFO: Included uncompiled module 'pkg_resources._vendor'.
> Nuitka-Inclusion:INFO: Included uncompiled module 'pkg_resources._vendor.appdirs'.
> Nuitka-Inclusion:INFO: Included uncompiled module 'pkg_resources._vendor.packaging'.
> Nuitka-Inclusion:INFO: Included uncompiled module 'pkg_resources._vendor.packaging.__about__'.
> Nuitka-Inclusion:INFO: Included uncompiled module 'pkg_resources._vendor.packaging._compat'.
> Nuitka-Inclusion:INFO: Included uncompiled module 'pkg_resources._vendor.packaging._structures'.
> Nuitka-Inclusion:INFO: Included uncompiled module 'pkg_resources._vendor.packaging._typing'.
> Nuitka-Inclusion:INFO: Included uncompiled module 'pkg_resources._vendor.packaging.markers'.
> Nuitka-Inclusion:INFO: Included uncompiled module 'pkg_resources._vendor.packaging.requirements'.
> Nuitka-Inclusion:INFO: Included uncompiled module 'pkg_resources._vendor.packaging.specifiers'.
> Nuitka-Inclusion:INFO: Included uncompiled module 'pkg_resources._vendor.packaging.utils'.
> Nuitka-Inclusion:INFO: Included uncompiled module 'pkg_resources._vendor.packaging.version'.
> Nuitka-Inclusion:INFO: Included uncompiled module 'pkg_resources._vendor.pyparsing'.
> Nuitka-Inclusion:INFO: Included uncompiled module 'pkg_resources.extern'.

./test
> path_resource : /home/.../site-packages/openapi_spec_validator/resources/schemas/v2.0/schema.json

**Comment by kayhayen** [comment]
Not immediately providing a test case, means I can come back to it arbitrarily later. Just like in this case. With the pkg-resources plugin, the require is detected and resolved at compile time. I added the data files on factory branch, so your example works perfectly and out of the box without using any datafile options.

https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
Part of the current pre-release and will be part of the next stable release 0.6.18

**Comment by kayhayen** [comment]
This is part of the 0.6.18 release.
