### ISSUE TITLE
Error with tqdm during compilation (.... size changed during iteration)

### ISSUE THREAD

**Issue by chwba** [Nuitka/Nuitka#1040]
**.... size changed during iteration**
```
  File "C:\Users\Administrator\Documents\COMPILATION\source_app\venv\lib\site-packages\nuitka\build\inline_copy\tqdm\tqdm\_monitor.py", line 49, in get_instances
self.update(data)
                             File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.9.2\lib\_weakrefset.py", line 51, in __init__
    rn self.__class__(self)
  File "C:\Users\Administrator\Documents\COMPILATION\source_app\venv\lib\site-packages\nuitka\build\inline_copy\tqdm\tqdm\_monitor.py", line 69, in run
     (more hidden) ...                                                    File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.9.2\lib\_weakrefset.py", line 93, in copy




  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.9.2\lib\_weakrefset.py", line 120, in update
```
Sadly the error was printed in stdout, so i couldnt fully capture it..
I suggest using https://github.com/willmcgugan/rich, I have had problems with tqdm before as well.

**Comment by kayhayen** [comment]
This is indeed annoying, and I think you are the second one to see it, very ugly. Was this a crash or a warning given, I think the later, right?

After a bit of research upstream, I found this, supposedly it's fixed by an update:

https://github.com/tqdm/tqdm/issues/481

I will update the inline copy of tqdm at the next opportunity.

**Comment by kayhayen** [comment]
And yes, a crash from a warning, pretty rough.

**Comment by kayhayen** [comment]
I have updated the inline copy of tqdm to the latest version, where they claim there is no error. As for the suggestion, I am not in a position to do evaluate it. It looks nice surely, but I would ne a PR that replaces it, as I cannot spend the time to do that right now, just to analyse if it's better than tdqm. If you are up for that, please indicate so. 

As an improvement or alternative, it would definitely be welcome.

**Comment by kayhayen** [comment]
Accidental close, the fix is on factory.

**Comment by kayhayen** [comment]
This is part of the current pre-release.

**Comment by kayhayen** [comment]
Accidentally close again, damn. :)

**Comment by chwba** [comment]
Id really suggest to use rich over tqdm it does not cause such issues

**Comment by kayhayen** [comment]
@chwba I agree on the looks, but I don't have the time to do it, and I don't know its API. Checkout `nuitka/Progress.py` (on develop branch) where it's used. I am willing to have both usable, I actually would love to have it. But as I said, I cannot afford to spend the time right now. What tqdm has going for it, is their claim that they do not cost CPU.

Esp. if it support PyCharm's terminal and other crappy terminals better, it is probably totally worth it. But today I will be looking at an optimization that might make compilation on the frontend side of Nuitka way faster. But if you have the knowledge of their API, that's probably only a small task for you.

**Comment by chwba** [comment]
The API is very similar to exactly the same. - It does support PyCharms terminal but one has to check `Emulate terminal in output console` for it to work. As I use it - Here is a snippet that works inside a class:

```python
from concurrent.futures.thread import ThreadPoolExecutor
from time import sleep

from rich.progress import Progress, TextColumn, BarColumn, TimeRemainingColumn


class TestBar:
	def __init__(self):
		self.task = None
		self.progress = Progress(
			TextColumn("[bold blue]{task.fields[desc]}", justify="left"),
			BarColumn(bar_width=100),
			"[progress.percentage]{task.percentage:>3.1f}%",
			"•",
			"[progress.percentage]{task.completed:1d}",
			"/",
			"[progress.percentage]{task.total:1d}",
			"•",
			TimeRemainingColumn(),
		)

	def run(self):
		with self.progress:
			self.task = self.progress.add_task("Do Work", desc="[green]Do all the work", total=10)

			tpe = ThreadPoolExecutor(max_workers=500)
			for i in range(10):
				f = tpe.submit(self.do_work, i)
				sleep(0.01)
				f.add_done_callback(self.thread_callback)
			tpe.shutdown(wait=True)

		print("Work finished")

	def do_work(self, i):
		sleep(i)
		print(f"[{i}] working...")

	def thread_callback(self, thread):
		self.progress.update(self.task, advance=1)


if __name__ == "__main__":
	bar = TestBar()
	bar.run()
```
https://nextcloud.mnwd.in/s/ExPDnpKFDTrQSdD

**Comment by kayhayen** [comment]
Part of the 0.6.14 release.
