### ISSUE TITLE
libuuid not found in Nuitka on Alpine

### ISSUE THREAD

**Issue by anki-code** [Nuitka/Nuitka#1046]
Hi! 

Minimal example to repeat the issue in docker:

```python
docker run --rm -it python:3.9-alpine sh

apk add libuuid
ls /lib/libuuid*
# /lib/libuuid.so.1      /lib/libuuid.so.1.3.0

pip install nuitka
# Successfully installed nuitka-0.6.13.1

python
from nuitka.utils.SharedLibraries import locateDLL
locateDLL("uuid")
# None                     # Expected: libuuid

from ctypes.util import find_library
find_library("uuid")
# None                     # Expected: libuuid
```

I have this [fix](https://github.com/anki-code/xonsh-portable-binary/blob/3ec06162ff75bd5d78ff17b1c0da74e0acb7dc73/xonsh-portable-musl-alpine.Dockerfile#L35-L39):

```python
#
# Fix Nuitka 0.6.10 + Python 3.6 + Alpine issue when libuuid is installed via `apk add libuuid`
# but `ctypes.util.find_library('uuid')` returns None instead of right path.
#
RUN sed -i 's|locateDLL("uuid")|"/lib/libuuid.so.1.3.0"|g' /usr/local/lib/python3.6/site-packages/nuitka/plugins/standard/ImplicitImports.py
```

Thanks!

**Comment by kayhayen** [comment]
That's right, for Alpine there is special code to find libraries.

**Comment by kayhayen** [comment]
What does `ctypes.util.find_library("uuid")` give you?

**Comment by anki-code** [comment]
> What does ctypes.util.find_library("uuid") give you?

None.

**Comment by kayhayen** [comment]
That one is supposed to resolve the name to a soname, which then is searched with this code:

```
    if isAlpineLinux():
        return localDLLFromFilesystem(
            name  = dll_name,
            paths = ["/lib","/usr/lib","/usr/local/lib"]
        )
```

So your task is to figure out, why it doesn't work, and if there are alternative names to `ctypes.util.find_library` that would work, maybe it wants to `.1` although I strongly believe that is precisely part of its task.

**Comment by anki-code** [comment]
> Is there a tool this find_library uses on your OS, and that is not installed or something?

@kayhayen You're right!
1. The `find_library` functions uses `ld` util that not preinstalled in Alpine. The `build-base` package has it.
2. The `libuuid` library creates `/lib/libuuid.so.1` and `/lib/libuuid.so.1.3.0` and `find_library` can't find it by suffix reasons. So we need to create a symlink.

The solution is:

```python
docker run --rm -it python:3.9-alpine sh

apk add libuuid build-base
cd /lib &&  ln -s libuuid.so.1 libuuid.so
python -c 'from ctypes.util import find_library; print(find_library("uuid"))'
# libuuid.so.1
```

**Comment by anki-code** [comment]
Reported to python issue tracker - https://bugs.python.org/issue43642

**Comment by kayhayen** [comment]
Seems to be an Alpine or Pyton bug, therefore put to invalid, unless you know how to add something to Nuitka to detect this more automatically.
