### ISSUE TITLE
Syntax error installing in Python 2.7

### ISSUE THREAD

**Issue by fcojavmc** [Nuitka/Nuitka#1050]
> python -m nuitka --version
0.6.13.1
Python: 2.7.12 (default, Jul 01 2016, 15:34:22) [GCC]
Executable: /usr/bin/python
OS: Linux
Arch: x86_64

Error message:

Processing Nuitka-0.6.13.1-py2.7.egg
creating /usr/lib/python2.7/site-packages/Nuitka-0.6.13.1-py2.7.egg
Extracting Nuitka-0.6.13.1-py2.7.egg to /usr/lib/python2.7/site-packages
  File "/usr/lib/python2.7/site-packages/Nuitka-0.6.13.1-py2.7.egg/nuitka/build/inline_copy/tqdm/tqdm/asyncio.py", line 38
    async def __anext__(self):
            ^
SyntaxError: invalid syntax

  File "/usr/lib/python2.7/site-packages/Nuitka-0.6.13.1-py2.7.egg/nuitka/build/inline_copy/tqdm/tqdm/rich.py", line 46
    f"{completed/unit:,.{precision}f}/{total/unit:,.{precision}f} {suffix}",
                                                                          ^
SyntaxError: invalid syntax

Adding Nuitka 0.6.13.1 to easy-install.pth file

**Comment by kayhayen** [comment]
Are you saying that happens when exactly?

**Comment by fcojavmc** [comment]
Hello. Installing with: python setup.py install

**Comment by kayhayen** [comment]
Ok, this is solved on the factory branch, where I just removed the files, they are unused anyway. I believe it doesn't prevent installation, or does it?

**Comment by kayhayen** [comment]
Part of the 0.6.14 release.
