### ISSUE TITLE
tkinter plug-in for appJar on python3.8

### ISSUE THREAD

**Issue by thothloki** [Nuitka/Nuitka#1052]
I am trying to make a stand-alone app and used the —include ti-kinter command but it doesn’t seem to work with the appJar module. Is this a simple fix or am I screwed?

sorry about the lack of error data. Am on mobile and nowhere near my computer right now. Just wondering if all I have to do is add “appJar” to the plug-in to fix it.

**Comment by kayhayen** [comment]
Please retry when you are able to fill out the issue template, so I have any way of knowing anything.
