### ISSUE TITLE
FATAL: Error, no 'Python.h' debug headers can be found at '['/usr/include/python3.6dm']', dependency not satisfied!

### ISSUE THREAD

**Issue by mdarby85** [Nuitka/Nuitka#1060]
I am attempting to use Nuitka to build an executable obfuscated with pyarmor that I can also debug with something like GDB. While trying to build a basic example I encountered the following error:

```
$ python3 -m nuitka --python-debug --unstripped --follow-imports main.py
Nuitka:INFO: Starting Python compilation.
Nuitka:INFO: Completed Python level compilation and optimization.                                                                                                                                                  
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.                                                                                                                                       
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
FATAL: Error, no 'Python.h' debug headers can be found at '['/usr/include/python3.6dm']', dependency not satisfied!
```
'Python.h' exists in the /usr/include/python3.6dm/ directory.
Searching online for this exact error returns no results and I can't seem to find anything in the issues reported here either.

I believe I'm using the correct command line syntax to build such an executable but if I'm using Nuitka incorrectly or it doesn't fit my use case, then I would appreciate someone correcting me.

Additional info:

OS: CentOS 7

```
$ python3 -m nuitka --version
0.6.13.2
Python: 3.6.8 (default, Nov 16 2020, 16:55:22) 
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
```

**Comment by kayhayen** [comment]
For debugging with gdb, you may also want to add `--debug` as it keeps debug information. Can you check the code in `Backend.scons` that outputs the error, it would have to be wrong very wrong then.

**Comment by mdarby85** [comment]
I'm gonna go ahead and close this. Today, for no reason I can find, the error doesn't appear anymore. I can't reproduce the error so it must have been some fluke in CentOS on my end.

The code in `Backend.scons` that throws that error doesn't seem to have anything wrong in it that I can see either.
