### ISSUE TITLE
Mingw64 compiling simple test script fails wiith "FATAL: Error, cannot find 'python38.lib' file"

### ISSUE THREAD

**Issue by astromehazu** [Nuitka/Nuitka#1061]
Hello,

I tried to compile test python script using Nuitka in MINGW64 shell of MSYS2 installation (version 20210228) on Windows 8.1
Python script:

```python
#!/usr/bin/env python
print('Works.')
```

at the MINGW64 prompt 

`/usr/bin/env python` gives:

> Python 3.8.9 (default, Apr  3 2021, 09:30:04)  [GCC 10.2.0 64 bit (AMD64)] on win32

When I try to compile script by

`python3 -m nuitka --mingw64 --standalone --show-scons test.py`

I get:

> Nuitka:INFO: Starting Python compilation.
> Nuitka:INFO: Completed Python level compilation and optimization.
> Nuitka:INFO: Generating source code for C backend compiler.
> Nuitka:INFO: Running data composer tool for optimal constant value handling.
> Nuitka:INFO: Running C level backend compilation via Scons.
> Scons command: C:/msys64/mingw64/bin/python3.exe -W ignore C:/msys64/mingw64/lib/python3.8/SITE-P~1/nuitka/build/INLINE~1/bin/scons.py -f C:/msys64/mingw64/lib/python3.8/SITE-P~1/nuitka/build/BACKEN~1.SCO --jobs 1 --warn=no-deprecated --no-site-dir --debug=explain,stacktrace result_name=C:/msys64/home/admin/TEST~1.DIS/test source_dir=. debug_mode=false python_debug=false unstripped_mode=false module_mode=false full_compat=false experimental= trace_mode=false python_version=3.8 target_arch=x86_64 python_prefix=C:/msys64/mingw64 nuitka_src=C:/msys64/mingw64/lib/python3.8/SITE-P~1/nuitka/build module_count=489 result_exe=C:/msys64/home/admin/TEST~1.DIS/test.exe standalone_mode=true frozen_modules=165 noelf_mode=true show_scons=true mingw_mode=true
> scons: Reading SConscript files ...
> Nuitka-Scons:INFO: CC 'C:\\msys64\\mingw64\\bin/gcc.exe' version check gives (10, 2, 0)
> Nuitka-Scons:INFO: Initial CC: 'gcc'
> Nuitka-Scons:INFO: Initial CCVERSION: (10, 2, 0)
> Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
> Nuitka-Scons:INFO: Modes for this compiler are: {'gcc_mode': True, 'clang_mode': False, 'clangcl_mode': False, 'mingw_mode': True, 'msvc_mode': False}
> Nuitka-Scons:INFO: Using C11 mode: True
> Scons: Compiler used C:\msys64\mingw64\bin/gcc.exe
> FATAL: Error, cannot find 'python38.lib' file.

In deed there is no such file and it is not included in any MSYS2 packages. What can i do to obtain that file and where should it be placed? 
Sorry for the text striketrough, it is not present in the original result.

**Comment by roiderats** [comment]
> > FATAL: Error, cannot find 'python38.lib' file.
> In deed there is no such file and it is not included in any MSYS2 packages. What can i do to obtain that file and where should it be placed?

Same issue for me, freshly installed MinGW today.  I see python3.lib(173088 bytes) and python39.lib(361556 bytes) in C:\Users\myname\AppData\Local\Programs\Python\Python39\libs\ which is where Windows-native Python 3.9.2 installed itsself by default. So, I'll try to install Windows-native 3.8, get the file and populate random places of mingw-filesystem with it

**Comment by kayhayen** [comment]
I don't think this applies anymore, I have since got MinGW and POSIX both to work in standalone mode at least. Accelerated mode for some reason don't work, because preserving the python environment somehow fails, but this shouldn't happen anymore.
