### ISSUE TITLE
Fastapi and uvicorn build failed and mutiple workers failed

### ISSUE THREAD

**Issue by Leezj9671** [Nuitka/Nuitka#1063]
Use the demo like this [#618](https://github.com/Nuitka/Nuitka/issues/618#issuecomment-815625137)

`fapi_test.py` is like below:

`pip install fastapi uvicorn nuitka`

```python
from fastapi import FastAPI
import uvicorn

app = FastAPI()


@app.get("/")
async def read_root():
    return {"Hello": "World"}


@app.get("/items/{item_id}")
async def read_item(item_id: int, q: str = None):
    return {"item_id": item_id, "q": q}

if __name__ == "__main__":
    uvicorn.run("fapi_test:app", host="127.0.0.1", port=5000, log_level="info")
```

Nuitka build using `python -m nuitka --standalone fapi_test.py`

Then I ran `./fapi_test.dist/fapi_test`, and I got `ERROR:    Error loading ASGI app. Could not import module "fapi_test".` error.

Another error is when I set the workers greater than 1 like below:
```python
    uvicorn.run("fapi_test:app", host="127.0.0.1", port=5000, log_level="info", workers=2)
```

The built exe can run, but raise another error and web service failed:

```
INFO:     Uvicorn running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:     Started parent process [99052]
/home/leezj/amztools/fapi_test.dist/multiprocessing/semaphore_tracker.py:55: UserWarning: semaphore_tracker: process died unexpectedly, relaunching.  Some semaphores might leak.
```

Enviroments:
- Python 3.7.10 in Miniconda
- FastAPI Uvicorn Nuitka all the newest version 
- Ubuntu 18.04

**Comment by kayhayen** [comment]
For multiprocessing, isn't it needed to call `freeze_support`. That might be the second issue you are reporting. Obviously it would be nice, if the multiprocessing plugin told about this, so far it's relatively shy about speaking of anything outside of the main module.

Try adding this to your main module code:

```
from multiprocessing import freeze_support

if __name__ == "__main__":
    freeze_support()
```

I guess, for multiprocessing, we ought to patch it either way. Also in a way that it will reject to work when it's used, but the workarounds were not compiled in. Let me know if the second thing helps.

**Comment by Leezj9671** [comment]
> For multiprocessing, isn't it needed to call `freeze_support`. That might be the second issue you are reporting. Obviously it would be nice, if the multiprocessing plugin told about this, so far it's relatively shy about speaking of anything outside of the main module.
> 
> Try adding this to your main module code:
> 
> ```
> from multiprocessing import freeze_support
> 
> if __name__ == "__main__":
>     freeze_support()
> ```
> 
> I guess, for multiprocessing, we ought to patch it either way. Also in a way that it will reject to work when it's used, but the workarounds were not compiled in. Let me know if the second thing helps.

Nope, add `freeze_support` not working and got same error.

**Comment by kayhayen** [comment]
The first issue, if I am not mistaken is that when you have a file Python file as a main program `filename.py`, it's loaded as `__main__` and executed with that `__name__` and then you can also import it as `filename`, duplicating the code, that time run as `__name__` being `filename`. In both instances `__file__` is the same btw.

In my mind, that's a bug of Python that you are using here, that Nuitka emulates when it sees an explicit import. You can add that to the code or use `--include-module` to workaround that. A potential plugin for this tech, could recognize that the `uvicorn.run` argument will be imported and do that for you. But that would rely on parsing the string, etc. and I guess, I much would prefer to do something else, e.g. to patch the `run` method to give a nicer error message after compilation.

Regarding multiprocessing, yeah, that is Windows only, but you are not using that, so that ought to work. Maybe you just need to fix the first issue and I was wrongly assuming the second part was with a workaround for the first used.

**Comment by Leezj9671** [comment]
> The first issue, if I am not mistaken is that when you have a file Python file as a main program `filename.py`, it's loaded as `__main__` and executed with that `__name__` and then you can also import it as `filename`, duplicating the code, that time run as `__name__` being `filename`. In both instances `__file__` is the same btw.
> 
> In my mind, that's a bug of Python that you are using here, that Nuitka emulates when it sees an explicit import. You can add that to the code or use `--include-module` to workaround that. A potential plugin for this tech, could recognize that the `uvicorn.run` argument will be imported and do that for you. But that would rely on parsing the string, etc. and I guess, I much would prefer to do something else, e.g. to patch the `run` method to give a nicer error message after compilation.
> 
> Regarding multiprocessing, yeah, that is Windows only, but you are not using that, so that ought to work. Maybe you just need to fix the first issue and I was wrongly assuming the second part was with a workaround for the first used.

Thank you very much for your sincere answer. I fixed first issue by `--include-module filename`,  but second issue is help needed. An example is like this:

```python
from multiprocessing import freeze_support

from fastapi import FastAPI
import uvicorn

app = FastAPI()
freeze_support()


@app.get("/")
async def read_root():
    return {"Hello": "World"}


if __name__ == "__main__":
    uvicorn.run("fapi_test:app", host="127.0.0.1", port=5000, log_level="info", workers=2)
```

**Comment by Leezj9671** [comment]
btw, `freeze_support` seems effected on Windows, but I'm running this code on Ubuntu.

**Comment by kayhayen** [comment]
Ok, I will look into that and get back to you, but maybe only after 0.6.14 release this weekend, but I am assuming there is something with multiprocessing going on still, but you are right, that is not it, it is supposed to work on Windows. Maybe it's how the command line is handled with `unvcorn`.

**Comment by chuxuan2333** [comment]
I had the same error :  ERROR:    Error loading ASGI app. Could not import module "main".  
Then I had added --include-module=main , but the error also existed, help need!

this's my nuitka command line options with Nuitka '0.6.16.2' and Python '3.6' on ubuntu 18.04:
python3 -m nuitka  --standalone --nofollow-imports --include-module=main --follow-import-to=core,apis,models,schema,utils --remove-output --output-dir=out  main.py

**Comment by chuxuan2333** [comment]
And the main function code:
`if __name__ == '__main__':
    freeze_support()
    uvicorn.run(app="main:app", host='0.0.0.0', port=settings.PORT, reload=settings.RELOAD)`

**Comment by chuxuan2333** [comment]
And the main function code：
`if __name__ == '__main__':
        freeze_support()
        uvicorn.run(app="main:app", host='0.0.0.0', port=settings.PORT, reload=settings.RELOAD)`

**Comment by KevinRodriguez777** [comment]
this works nowadays if you use the format 
```py
if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=5000, log_level="info", workers=8)
``` 
of course workers is optional.

```py
uvicorn.run("fapi_test:app" ...
```
 still doesn't work but for now the above workaround is good.

**Comment by kayhayen** [comment]
So, I am getting now:

> Nuitka: Launching 'MiniUnicorn.dist\MiniUnicorn.exe'.
> ERROR:    Error loading XX ASGI app. Nuitka: Could not import module "MiniUnicorn" use "--include-module=MiniUnicorn" option during compilation.

And if I follow that advice from non deployment config, it just works

```
- module-name: 'uvicorn.importer' # checksum: e2733864
  anti-bloat:
    - description: 'better error message for string imports'
      replacements_plain:
        'Could not import module "{module_str}"': 'Nuitka: Could not import module "{module_str}" use "--include-module={module_str}" option during compilation'
      when: 'not deployment'
```

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
Part of the 2.1.3 hotfix release I just made.
