### ISSUE TITLE
Qt eventFilters only work when "all" Qt plugins are selected

### ISSUE THREAD

**Issue by hirios** [Nuitka/Nuitka#1064]
I'm trying to change the background of a program using eventFilter(). The background change should take place after hovering the mouse over the buttons. But after compiling with Nuitka, this function does not work. I wrote a small example and added a video so that if you want you can reproduce the error. 

Exemple link: https://drive.google.com/file/d/1e9SUbP0nnDTJ6H2_wA_8-l9PGAC1WbhY/view?usp=sharing

Those were the arguments that I used on Windows:
```nuitka --mingw64 --onefile   --plugin-enable=pylint-warnings --plugin-enable=qt-plugins --include-data-file=images\*=images\ --windows-onefile-tempdir main.py```

https://doc.qt.io/archives/qtforpython-5.12/PySide2/QtCore/QObject.html#PySide2.QtCore.PySide2.QtCore.QObject.installEventFilter

https://srinikom.github.io/pyside-docs/PySide/QtCore/QObject.html#PySide.QtCore.PySide.QtCore.QObject.installEventFilter

**Comment by hirios** [comment]
My config:
Windows 10 21H1 (Build 19043) 
Python 3.8.8
Nuitka==0.6.13.2
PyQt5==5.15.4
PyQt5-Qt5==5.15.2
PyQt5-sip==12.8.1

**Comment by kayhayen** [comment]
I can confirm this is not working, and it's not even working with the private PySide2 compile that has my PySide 6.1 changes contained.

**Comment by kayhayen** [comment]
Ah, with "all" qt plugins, it's working for me with my private PySide2 compile. Maybe also will for your PyQt5. I will have to investigate, which missing plugin causes this, and if it shouldn't be part of the "sensible" default.

**Comment by kayhayen** [comment]
As an aside, Nuitka commercial 0.6.14 will be able to include the Qt images inside the standalone binary already, fully protected.

The normal version has a `--include-data-dir=images=images` that includes the whole folder as of 0.6.14 that you can use if you are not commercial, and it's a bit simpler.

And I don't quite get, why you needed to replace the slashes in the path. Not having a working URL that is relative to `__file__` is a bug, as you require execution inside the dist folder, or inside the python file folder, which is unfriendly.

And of course, once released, PySide6.1 will also work.

**Comment by kayhayen** [comment]
With `--include-qt-plugins=sensible,styles` it works for me. I am adding that for 0.6.14 release to be included in sensible, as without it no hover events are generated.

**Comment by hirios** [comment]
> With `--include-qt-plugins=sensible,styles` it works for me. I am adding that for 0.6.14 release to be included in sensible, as without it no hover events are generated.


This worked very well for me! Thank you so much for the quick return

**Comment by hirios** [comment]
I'm looking forward to version 0.6.14. 
Will ```--include-data-dir=``` work recursively? this is something that might be good to implement in future versions of Nuitka

**Comment by hirios** [comment]
> And I don't quite get, why you needed to replace the slashes in the path. Not having a working URL that is relative to `__file__` is a bug, as you require execution inside the dist folder, or inside the python file folder, which is unfriendly.

Apparently the ```setStyleSheet``` method only accepts this bar ```/``` 

But I'm not sure, maybe I'm using it the wrong way

**Comment by hirios** [comment]
Again I thank the Nuitka project and its quick return, I think I can finish the issue now.
