### ISSUE TITLE
[PyQt5] Same thread id with QThread (multi-thread does not work)

### ISSUE THREAD

**Issue by Hintay** [Nuitka/Nuitka#1065]
I use `QThread` to perform intensive tasks. Each `QThread` creates a new thread after its starts and has a different thread ID to the main thread. The different threads do not block each other. However, after compiled with Nuitka, I found that all the `QThread` were running in the main thread and that the intensive tasks of one thread would block the other threads. This also led to deadlocks on signals connected with `BlockingQueuedConnection`.

I wrote a small example to test:

```python
import sys
from PyQt5.QtCore import QObject, QThread, QCoreApplication, pyqtSlot


class ThreadObject(QObject):
    @pyqtSlot()
    def init(self):
        print("Object current thread id:", int(QThread.currentThreadId()))


if __name__ == "__main__":
    app = QCoreApplication(sys.argv)
    print("Main current thread id:", int(QThread.currentThreadId()))

    thread_object = ThreadObject()
    thread = QThread(app)
    thread.started.connect(thread_object.init)
    thread_object.moveToThread(thread)

    @pyqtSlot()
    def quit_thread():
        thread.terminate()
        thread.wait(50)
        app.quit()

    thread.started.connect(quit_thread)
    thread.start()

    app.exec()

```

In the case of running source code with Python, the IDs of the threads are different.

```
> python qthread_test.py     
Main current thread id: 3032
Object current thread id: 28092
```

Use the following command with Nuitka:

```shell
nuitka --mingw64 --follow-imports --plugin-enable=pylint-warnings qthread_test.py
```

And run, the thread IDs are the same, which means that all the code is running in the same thread.

```
> qthread_test.exe
Main current thread id: 33660
Object current thread id: 33660
```

Environments:

- Python 3.8.8 x86_64 in Miniconda
- PyQt5 5.15.4
- Nuitka 0.6.13.3 and 0.6.14rc5
- Windows 10 20H2

**Comment by kayhayen** [comment]
I have tried a similar example with PySide2, and it's the same, even with the workarounds applied that 0.6.13 added. However, the patched PySide2 for Nuitka commercial users works fine.

As for PyQt5, please contact Riverbank and ask them to support Nuitka compiled functions. I have done the change such that it will be in PySide 6.1 once released. Consider https://nuitka.net/pages/pyside2.html

I will introduce public domain C files that Riverbank could use to add support in case they are interested. I would appreciate if they contacted me. Given that I now have Qt upstream support for Nuitka, even if unreleased for months to come, I am probably not going to do this right away unless they are interested.

**Comment by kayhayen** [comment]
If somebody were to pay me to do these changes, I would make them of course, therefore the funding wanted tag.

**Comment by kayhayen** [comment]
For funding would appy for PyQt6, I don't think that PyQt5 will get changes anymore, but I really recommend going PySide6 which is well supported by me and Qt company *both*.
