### ISSUE TITLE
 pure virtual method 'QIconEngine.paint()' not implemented.

### ISSUE THREAD

**Issue by zqbxx** [Nuitka/Nuitka#1066]
env:
1. win7 32bit, python 3.7.9 , nuitka 0.6.14rc5
2. win10 64bit python 3.9.0, nuitka 0.6.14rc5

requirements:
`PySide2`
`QtAwesome`

**code:**
icon.py
```
import os

from PySide2.QtCore import QSize
from PySide2.QtWidgets import QApplication
os.environ['QT_API'] = 'PySide2'
import qtawesome as qta


if __name__ == '__main__':

    app = QApplication()
    t1 = qta.icon('ei.file-new')
    p1 = t1.pixmap((QSize(32, 32)))
    app.exit()
```
**find `qtawesome` dir in `site-packages`, copy it to your working dir and delete all .py files and pycache**

**compile:**
open git bash
```
python -m nuitka --mingw64 --show-progress --standalone --plugin-enable=pyside2 ./icon.py
cp -R -u ./qtawesome ./icon.dist
```
**run:**
```
 ./icon.exe
Traceback (most recent call last):
  File "E:\dist\test\icon.dist\icon.py", line 14, in <module>
NotImplementedError: pure virtual method 'QIconEngine.paint()' not implemented.

```

**Comment by kayhayen** [comment]
What does end up in the awesome folder, only the icon or anything else? Also, you may want to consider `--include-package-data` which I intended for this procedure.

**Comment by zqbxx** [comment]
> 
> 
> What does end up in the awesome folder, only the icon or anything else? Also, you may want to consider `--include-package-data` which I intended for this procedure.

*.ttf and *.json

`--include-package-data=qtawesome` works

**Comment by zqbxx** [comment]
qtawesome extend `QIconEngine`(`CharIconEngine` in iconic_font.py). i have tried to aovid use `CharIconEngine`, overwirte `qtawesome.iconic_font.IconicFont#_icon_by_painter`

```
    def _icon_by_painter(self, painter, options):
        size = QSize(width, height)
        pm = QPixmap(size)
        pm.fill(Qt.transparent)
        painter.paint(self, QPainter(pm), QRect(QPoint(0, 0), size), PySide2.QtGui.QIcon.Mode.Normal,
                      PySide2.QtGui.QIcon.State.Off, options)
        return QIcon(pm)
```

but it still has some problems, the code is not work correct, `color_active` has no effect.
`qta.icon('ei.unlock', color=icon_color['color'], color_active=icon_color['active'])`

`QIconEngine` is  necessary here
https://doc.qt.io/qt-5/qiconengine.html#details
https://doc.qt.io/qt-5/qicon.html#pixmap

**Comment by kayhayen** [comment]
Ok, I think I might be able to expand the free work arounds for that abstract class as well.

**Comment by vmtest888** [comment]
I have this error too, is there a solution?

**Comment by kayhayen** [comment]
Yes, it is this: https://nuitka.net/pages/pyside2.html

I don't think I will personally invest time into PySide2 anymore outside of Nuitka commercial, and even there it just works for everyting, and needs no attention. Spending my time to do that and workarounds as well has no point. If you look at the plugin and extend the workaround for the base class in question, be my guest with a PR.
