### ISSUE TITLE
jsonschema metadata error

### ISSUE THREAD

**Issue by solanu** [Nuitka/Nuitka#1068]
python -m nuitka --version

```
0.6.5
Python: 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 14 2019, 23:09:19) [MSC v.1916 32 bit(Intel)]
Executable: C:\Users\IEUser\AppData\Local\Programs\Python\Python37-32\python.exe

OS: Windows
Arch: x86
```

* How did you install Nuitka and Python

`pip`

  python -m pip freeze

```
aiofiles==0.6.0
aiohttp==3.7.4.post0
aiomysql==0.0.21
aioodbc==0.3.3
aiopg==1.2.1
aiosqlite==0.17.0
alabaster==0.7.12
altgraph==0.16.1
appdirs==1.4.4
async-timeout==3.0.1
asyncio==3.4.3
attrs==20.3.0
auto-py-to-exe==2.6.5
Babel==2.9.0
bottle==0.12.17
bottle-websocket==0.2.9
certifi==2019.9.11
cffi==1.13.2
chardet==3.0.4
colorama==0.4.1
commonmark==0.9.1
Cython==0.29.23
distlib==0.3.1
docutils==0.17
Eel==0.10.4
filelock==3.0.12
future==0.18.2
gevent==1.4.0
gevent-websocket==0.10.1
greenlet==0.4.15
idna==2.8
imagesize==1.2.0
importlib-metadata==3.10.1
influxdb==5.2.3
iso8601==0.1.14
isort==4.3.21
Jinja2==2.11.3
jsonschema==3.2.0
lazy-object-proxy==1.4.3
MarkupSafe==1.1.1
mccabe==0.6.1
multidict==5.1.0
nose==1.3.7
Nuitka==0.6.5
numpy==1.17.3
outcome==1.1.0
packaging==20.9
paho-mqtt==1.5.1
pandas==0.25.2
pefile==2019.4.18
pluggy==0.13.1
psycopg2-binary==2.8.6
ptvsd==4.3.2
PuLP==1.6.10
py==1.10.0
pycparser==2.19
Pygments==2.8.1
PyInstaller==3.5
pylint==2.4.3
pymodbus==2.5.1
pyModbusTCP==0.1.10
PyMySQL==0.9.3
pyodbc==4.0.30
pyparsing==2.4.2
Pyro4==4.77
pyrsistent==0.17.3
pyserial==3.5
pyserial-asyncio==0.5
python-dateutil==2.8.0
pytz==2019.3
pywin32==225
pywin32-ctypes==0.2.0
recommonmark==0.7.1
Represent==1.6.0.post0
requests==2.22.0
rinoh-typeface-dejavuserif==0.1.3
rinoh-typeface-texgyrecursor==0.1.1
rinoh-typeface-texgyreheros==0.1.1
rinoh-typeface-texgyrepagella==0.1.1
rinohtype==0.5.2
serpent==1.28
six==1.15.0
slugify==0.0.1
snowballstemmer==2.1.0
Sphinx==3.5.4
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
SQLAlchemy==1.4.7
sqlalchemy-aio==0.16.0
SQLAlchemy-Utils==0.37.0
stringify==0.1.1
toml==0.10.2
tox==3.23.0
typed-ast==1.4.0
typing-extensions==3.7.4.3
urllib3==1.25.6
virtualenv==20.4.3
websockets==8.1
whichcraft==0.6.1
wrapt==1.11.2
xlrd==2.0.1
yarl==1.6.3
zipp==3.4.1
```

I am using [jsonschema ](https://pypi.org/project/jsonschema/) pip module. This module needs some json files that install in C:\Users\IEUser\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\jsonschema\schemas

Nuitka standalone (follow imports) compilations ends with no error and I get compilation directory (`main.dist`).
However, I get an error when I run `main.dist/main.exe` beacuse it does not found json files from jsonschema module.

If I copy `jsonschema\schemas` directory to `main.dist` directory, `main.exe` found json files but there is still another poblema: I get a `no package metadata was found for jsconschema` error.

**Comment by kayhayen** [comment]
Does't the --include-package-data option work for it here?

Regarding the metadata not found, for ``pkg_resources`` there is now a plugin, and I think it ought to be possible to expand it in a way that it works for metadata and its backport as well, I will look into that. But basically so far, that is not yet implemented and in terms of reporting it's a duplicate in that sense. Btw, strange how there is a typo in the error message quoted for the package name?

**Comment by solanu** [comment]
@kayhayen sorry for the typo, It was my own typo, I did not copy/pasted but I wrote from my memory with my hands ;-)

I get `no such option: --include-package-data` error when I use `--include-package-data` option.

How can I tracking new metadata feautre?

Thank you very much

**Comment by kayhayen** [comment]
You are using an impressively old version of Nuitka there.

**Comment by kayhayen** [comment]
I just pushed to factory branch improvements for this, the data files for jsonschema are now copied automatically. Also the pkg-resources plugin will recognize the metadata version code and compile time resolve when enabled.

https://nuitka.net/doc/factory.html

**Comment by solanu** [comment]
> I just pushed to factory branch improvements for this, the data files for jsonschema are now copied automatically. Also the pkg-resources plugin will recognize the metadata version code and compile time resolve when enabled.
> 
> https://nuitka.net/doc/factory.html

It works with `factory` branch and `--include-package-data=jsonschema --plugin-enable=pkg-resources` options.

Thank you very muc, @kayhayen 

It will be merge in `master` branch in the future, right?

**Comment by kayhayen** [comment]
@solanu the package data option ought to be unnecessary, and only duplicate some hard coding in Nuitka, it's on develop now and will be in 0.6.15 release, but not as a hotfix, because I did structural changes. But develop is pretty stable too usually. We keep the issue open until it's released as stable, so people find this until then.

**Comment by kayhayen** [comment]
Part of 0.6.15 release.

**Comment by solanu** [comment]
> Part of 0.6.15 release.

Thank you very much!
