### ISSUE TITLE
PySide2 QThread Unsupported?

### ISSUE THREAD

**Issue by kdrkdrkdr** [Nuitka/Nuitka#1071]
Hello. I'm PySide2 user..

I want to compile with this command line, 

python -m nuitka --mingw64 --plugin-enable=qt-plugins --include-qt-plugins=all .\myfile.py

but, my code is using QThread class.. it can access def __init__(self), but, can't access run(start), and stop method..

how can i do?

**Comment by kayhayen** [comment]
Use the pyside2 plugin, not the pyqt5 plugin and latest Nuitka version.
