### ISSUE TITLE
AppImageKit

### ISSUE THREAD

**Issue by Ben-Faessler** [Nuitka/Nuitka#1074]
Can you take care of the following problem, please?
[Problem](https://github.com/AppImage/AppImageKit/issues/1128)

**Comment by kayhayen** [comment]
I have pushed a fix to https://nuitka.net/doc/factory.html let me know if it works, then I can include it in the next hotfix.

**Comment by Ben-Faessler** [comment]
Thanks, it works.

**Comment by kayhayen** [comment]
This is already part of the stable release as a hotfix.
