### ISSUE TITLE
Compiling for older MacOS version

### ISSUE THREAD

**Issue by Leseratte10** [Nuitka/Nuitka#1075]
I'm using Nuitka 0.6.9.4 with Python 3.8 on a MacOS 10.15 Github Runner. I know that that Nuitka version is old, but I'm asking a general question not reporting a particular bug so hopefully that's not a problem. Also, I read through the changelog and it doesn't look like anything changed regarding this.

I'm installing Python using `brew install python3` and nuitka using `pip install nuitka=0.6.9.4`. 

I'm running nuitka with this command:
`python -m nuitka main.py --follow-imports --standalone --jobs=1 --recurse-all --plugin-enable=tk-inter`

The resulting Binary works just fine on a Mac with Catalina (10.15), but it does not run on older MacOS versions. I tried setting `CCFLAGS: "-mmacosx-version-min=10.10"` but that didn't help either. I don't have an older Mac to test this with, but the person who tested my program says that "the minimum version for this is 10.15 Catalina so it doesn't run on my 10.13 Mac". 

Given that A) I do not own a Mac myself so all compiling must happen through a Mac Github Actions CI Runner (or through cross-compiling when/if #43 gets fixed in the future), and B) Github does not provide MacOS runners older than 10.15 Catalina, is there any way I can use nuitka to build a binary that'll run on older MacOS versions?

For Linux I'm solving this issue by using an Ubuntu 20.04 image on the Github CI Runner, but then running Nuitka in an Ubuntu 16.04 Docker container on said runner to be able to support Ubuntu 16.04 and newer. However, it doesn't seem possible to do something similar with MacOS. 

Am I missing something, or is this just not possible with Nuitka?

**Comment by kayhayen** [comment]
For Windows, using latest works. For Linux, we must compile on the newest one due to new glibc refusing to run on newer systems, but I will be looking into creating container images myself to work around that.

From what I have seen so far, older Xcode and older SDKs must be installed, and it's possible. I have not yet done it, but eventually I will figure it out. But it is in the realms of using proper toolchain and options, and nothing that Nuitka itself does.

**Comment by kayhayen** [comment]
The release 0.6.18 added support for this, compiling should actually work on any macOS version and still be able to target what the Python version is created for. Also notice that application bundles are supported now.
