### ISSUE TITLE
ModuleNotFoundError while include-module is used

### ISSUE THREAD

**Issue by korneel69** [Nuitka/Nuitka#1084]
C:\WINDOWS\system32>nuitka --onefile --windows-onefile-tempdir --enable-plugin=multiprocessing --follow-imports **--include-module=gevent._gevent_c_hub_local** --enable-plugin=gevent C:\Users\K\Downloads\dddd\BottyThotty.py

Output
...
...
Nuitka-Plugins:INFO: gevent: Greenlet tree tracking switched off
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
**Nuitka:WARNING: Did not follow import to unused 'gevent._gevent_c_hub_local', consider include options.**
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl).
Nuitka-Scons:INFO: Compiled 145 C files using clcache with 0 cache hits and 145 cache misses.
Nuitka-Postprocessing:INFO: Creating single file from dist folder, this may take a while.
Nuitka:INFO: Running bootstrap binary compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl).
Nuitka-Scons:INFO: Compiled 1 C files using clcache with 0 cache hits and 1 cache misses.
Nuitka:INFO: Keeping onefile build directory 'BottyThotty.onefile-build'.
Nuitka:INFO: Keeping dist folder 'BottyThotty.dist' for inspection, no need to use it.
Nuitka:INFO: Keeping build directory 'BottyThotty.build'.
Nuitka:INFO: Successfully created 'BottyThotty.exe'.

When running:
  File "C:\Users\K\BOTTYT~1.DIS\BottyThotty.py", line 9, in <module>
  File "C:\Users\K\BOTTYT~1.DIS\gevent\__init__.py", line 86, in <module>
  File "C:\Users\K\BOTTYT~1.DIS\gevent\_hub_local.py", line 101, in <module>
  File "C:\Users\K\BOTTYT~1.DIS\gevent\_util.py", line 148, in import_c_accel
  File "importlib.py", line 127, in import_module
**ModuleNotFoundError: No module named 'gevent._gevent_c_hub_local'**

Include-module=gevent does not solve it either

Any and all ideas on how this might be resolved are appreciated!

Thanks in advance.

**Comment by kayhayen** [comment]
You didn't fill out the issue template at all, and your outputs seem to not match the input, or rather strange bugs exist. I don't really appreciate guessing information.
