### ISSUE TITLE
Drastic performance issue (Binaries execution slower than Python!)

### ISSUE THREAD

**Issue by ABD-Z** [Nuitka/Nuitka#1087]
0.6.14.4
Python: 3.5.3 (default, Nov 18 2020, 21:09:16)
OS: Linux
Arch: x86_64
Installed via Pip in a virtualenv.

Hallo,
I am using nuitka as everybody here in order to transpile python script into binaries file and thus expect to be a bit faster than in Python. It is, normally, but I am facing right now a big issue.
I developped a server containing three threads (threading module from Python) : 
-one for recieving messages from client via a socket and answer him
-one for sending in real time events to the client.
-and one, the main thread containing the two above. It controlls in a try catch, if the flag of the receiver thread is set to True (means that it received an empty string) and thus restart the server, or catch a Keyboard exception and shutdown everything.

I used this command to generate the distribution :
python -m nuitka --standalone --show-progress main.py
My program use many natif Python modules such as socket, threading, ElementTree, etc.. and use also Redis module  (https://pypi.org/project/redis/)
And what is really strange is that the binary program is slowed down!
It takes an incredible amount of time to do for loops.
For example, this little piece of code is a bottleneck : 
```
            for device in data.db2.lrange("historique",0,-1):
                if data.db2.exists(device) == 0:
                    data.db2.lrem("historique",0,device)
```
db2 is a Redis databe ; lrem return components from list in given range here 0 to -1.
This piece of code is executed in a blink in Python.
And as far as I know, I dont think the problem is from Redis because I already transpiled monothread program using Redis commands without any performance issues.

So the question, why the binaries are slow? Does nuitka supports multi threading? What are the things to avoid while programming in Python in order to have the most optimized binary compilation?
Best Regards

**Comment by kayhayen** [comment]
Using develop and 3.9 may help some, because the threading integration improved a lot there.

**Comment by kayhayen** [comment]
Would it be possible for you to provide an example database for reference from somewhere, so I can reproduce this?

**Comment by kayhayen** [comment]
@ABD-Z Thank you so much, looking forward to the test case.

**Comment by ABD-Z** [comment]
Files for testing are ready!
[nuitkatest_ABD-Z.zip](https://github.com/Nuitka/Nuitka/files/6466561/nuitkatest_ABD-Z.zip)

The zip contains 4 files : 
-data.py consists of const and other datas gatherd in this file. debug function is used, to disable it just change the boolean inside the function to false.
-client.py is there to simulate client, what it receives and send has no importance. It has to be connected to the server
-server.py contains all the threads, it contains the bottleneck for loops inside the Sender thread.
-db_fllier.py is a utility to fill the database. Just enter random stuff as the key that will be stored in the DB and in a list called historic. The default time defined in data.py is 60 seconds, thus the key will expire and the Sender will iterate over historic to check if the elements in historic exists in the DB or else it will remove it. As the db is filled (up to less than 25 elements) the process begins to slow down in Sender loops.

Hope that it would help to improve Nuitka

**Comment by ABD-Z** [comment]
Forgot also to say that Redis should be installed on the computer : https://redis.io/topics/quickstart
And then install redis module for Python : pip install redis

**Comment by kayhayen** [comment]
It would be nice, if someone packaged this as a test case, testing support for redis would be nice.

**Comment by ABD-Z** [comment]
How to do it? I'm curious to know.

**Comment by kayhayen** [comment]
Not sure, closing for lack of feedback, the original issue seems resolved and if you need help to provide it as a test case, that's how far we can get, as I cannot help you do that.
