### ISSUE TITLE
Keras module not found

### ISSUE THREAD

**Issue by marcus1337** [Nuitka/Nuitka#1089]
I am trying to use Nuitka to compile a neural network using Keras. On the line that makes use of "Sequential()" I get this error AFTER compiling it to C code: "ModuleNotFoundError: No module named 'tensorflow.python.keras.engine.base_layer_v1"

It would be cool if Nuitka also could work with Keras. (https://keras.io/)

**Comment by kayhayen** [comment]
This is a very bad report, so I ignored it, but Tensorflow works on factory for me now with at least Windows.

**Comment by kayhayen** [comment]
https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
If you still have issues, create a new issue and fill out the template, otherwise it's pointless to me.
