### ISSUE TITLE
The tzdata files are not included

### ISSUE THREAD

**Issue by LarsK1** [Nuitka/Nuitka#1096]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

```
0.6.14.7
Python: 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
Executable: C:\Program Files\Python39\python.exe
OS: Windows
Arch: x86_64
```

* How did you install Nuitka and Python

  pip, virtualenc

* Also supply a [Short, Self Contained, Correct, Example](http://sscce.org/)

  `
import exchangelib`

When importing exchangelib Nuitka correctly imports tzdata, but the required data files are not included. With `--include-package=tzdata --include-package-data=tzdata` everything works fine. Is there an possibility to auto-include these files, as it is done with Qt?

**Comment by LarsK1** [comment]
Seems pretty similar to #1094

**Comment by kayhayen** [comment]
Woah, I confused this with another issue. This seems related, maybe the files moved or something.

**Comment by kayhayen** [comment]
I managed to reproduce this, but not on Linux strangely, only on Windows.

**Comment by kayhayen** [comment]
This is fixed on the factory branch https://nuitka.net/doc/factory.html

What I don't quite like is that it include `__init__.py` files but for compatibility, that is probably needed, however the cache files are ugly, but we don't have a filtering copy that would remove this kind of file reliably, so that is not the issue here.

**Comment by kayhayen** [comment]
Thanks for the PR, it's on factory too now (had a SyntaxError though, there is a reason PRs shouldn't be done to factory, no CI is run for PRs against it), that should solve this. This is the right way to do it, rather than doing the include options, making PRs if they are generally necessary.

**Comment by kayhayen** [comment]
Part of 0.6.15 release.
