### ISSUE TITLE
Windows: Updating resources can fail with no good information given

### ISSUE THREAD

**Issue by ActonMartin** [Nuitka/Nuitka#1098]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

0.6.14.4
Python: 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
Executable: D:\Projects\BottleDetect\venv\Scripts\python.exe
OS: Windows
Arch: x86_64

* How did you install Nuitka and Python
In a virtualenv(Pycharm) and use pip install 

* Also supply a [Short, Self Contained, Correct, Example](http://sscce.org/)

this is my command :

nuitka --mingw64 --standalone --show-memory --show-progress --plugin-enable=qt-plugins,torch --follow-import-to=functionCode,ui,NET,utool --nofollow-imports --windows-icon-from-ico=D:\Projects\BottleDetect\kk.ico --output-dir=softwarelo2 main.py

When I want to add a icon ,it shows like:
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 34
Nuitka-Postprocessing:INFO: Adding 8 icon(s) from icon file 'D:\\Projects\\BottleDetect\\kk.ico'.
FATAL: Failed to update resources, the result is unusable.

**Comment by kayhayen** [comment]
Hello,

did you not get other warnings as well? It is supposed to warn you a couple of times, and inform you about the likily reason. Are you really badly into cutting out information, or is this a bug that it fails to retry.

Yours,
Kay

**Comment by ActonMartin** [comment]
there just two red lines:
1:Nuitka-Options:WARNING: Following no imports is unlikely to work for standalone mode and should not be specified.

2:Nuitka-Postprocessing:WARNING: Succeeded with resource update in attempt 4.

**Comment by ActonMartin** [comment]
and now I just use same code line:
just change the output folder and delete the ico. It failed.


Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Backend C:   3%|█████▍                                                                                                                                                                                 |
Backend C:  29%|█████████████████████████████████████████████████████▌
Backend C:  32%|██████████████████████████████████████████████████████████▉
Backend C:  59%|███████████████████████████████████████████████████████████████████████████████████████████████
Backend C:  82%|███████████████████████████████████████████████████████████████████████████████████████████████
Nuitka-Scons:INFO: Compiled 34 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 34
FATAL: Failed to update resources, the result is unusable.

**Comment by kayhayen** [comment]
I have pushed a debugging improvement to the factory branch, please report the error number of the new warning:

https://nuitka.net/doc/factory.html

**Comment by ActonMartin** [comment]
I uninstall original branch and install factory branch,  make sure have the correct branch.
Then I use code line to run nuitka, first I havn't seen any others red line except two red lines I have mentioned above. Then I see the help have --debug. I add it, this time just show one information,
like :
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 32
Nuitka-Postprocessing:INFO: Adding 8 icon(s) from icon file 'ICON/logo.ico'.

And I found a folder named cache in 'C:\Users\martin\AppData\Local\Nuitka\Nuitka\Cache\ccache', then I delete all of them in the ccache. Run again, also show the cache miss 32,.Then I run it again, this time not stuck at cache miss. 

show some information like:
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 32
then command line could countinue run,.finally I see my exe with ico. 

I don't know why it happen, just like need compile tow times.Maybe my experience could support some clews.

**Comment by Ben-Faessler** [comment]
Cache miss occurs when the c file has not yet been compiled.  The next time it is run, the files are already compiled, so a cache hit occurs.

**Comment by kayhayen** [comment]
The cache hit changes the timing, this is a race. 

I don't know why exactly you are not seeing the message, but it tells you to disable your virus checker for the build folder. The created binary is modified by Nuitka, but it cannot be done while the virus checker has it open. Since you are not very good at reading, I am assuming a mistake of yours in using factory somehow, but it should now always give this message for each retry.

You can look at `nuitka/utils/WindowsResources.py` and look for yourself if there is some kind of bug preventing the message from being displayed, but I cannot explain why you wouldn't have it. Maybe retry updating too. The change is now also on the develop branch.

**Comment by kayhayen** [comment]
Part of 0.6.15 release.
