### ISSUE TITLE
PyQt5 5.15.4 OSX segmentation fault

### ISSUE THREAD

**Issue by quadhead** [Nuitka/Nuitka#1103]
Hi,

using nuitka compiled binaries in OSX works fine with PyQt5 5.15.2, but using PyQt5 5.15.4 will always lead to a segmentation fault:

```
OS Version:            macOS 11.3 (20E232)

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000008
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [38152]

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.apple.CoreFoundation      	0x00007fff207d02be _CFGetNonObjCTypeID + 10
1   com.apple.CoreFoundation      	0x00007fff206ab974 CFBundleCopyBundleURL + 14
2   QtCore                        	0x000000010f090470 QLibraryInfo::location(QLibraryInfo::LibraryLocation) + 1328
3   QtCore                        	0x000000010f0906cd QLibraryInfo::location(QLibraryInfo::LibraryLocation) + 1933
4   QtCore                        	0x000000010f276494 QCoreApplication::libraryPathsLocked() + 1524
5   QtCore                        	0x000000010f276a02 QCoreApplication::setLibraryPaths(QStringList const&) + 66
6   QtCore.so                     	0x000000010ee90c3e meth_QCoreApplication_setLibraryPaths(_object*, _object*) + 78
7   xxx      			          	0x000000010dec8038 CALL_FUNCTION_WITH_SINGLE_ARG + 1480
8   xxx 				         	0x000000010deb722d modulecode_PyQt5$QtCore$$45$postLoad + 3117
...
```

I guess this has something to do with PyQt5 5.15.4 using Qt libs 5.15.2, because there are no Qt libs 5.15.4.
Installing PyQt5 5.15.4 will always install PyQt5-Qt5 5.15.2.
So it might be because version numbers are not equal although it is compatible.

Example code:
```
import sys
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *

if __name__ == '__main__':
    app = QApplication(sys.argv)
    ui = QMainWindow()
    ui.show()
    app.exit(app.exec())
```

Versions:
```
nuitka 0.6.14.7, installed via pip in virtualenv
Python: 3.9.2
OS: Darwin
Arch: x86_64

PyQt5==5.15.4
PyQt5-Qt5==5.15.2
```

Command line:
`python3 -m nuitka --plugin-enable=qt-plugins --include-qt-plugins=sensible,styles --clang --standalone main.py
`

My feeling is that nuitka is not really used on OSX a lot. I always see Windows examples only, which is a shame because Python and Qt are about cross platform. 
Thank you for your great work on nuitka though, it's really cool!

**Comment by kayhayen** [comment]
Thanks. I actually made PySide wheels for macOS, but they currently are 10.4 or higher only, although I will probably do 10.3 too eventually. I do not think that mixing versions for the bindings and Qt is going to work at all. Does it work with pure Python? Why do it at all.

For the commercial support of PySide go here: https://nuitka.net/pages/pyside2.html

When building on macOS, it seems you should do it on the old systems. After some patch level there is a know issue with loading Qt without there being some files, that doesn't exist on the previous patch level.

As far as macOS goes, I have added proper support some time ago, with more to come. Hopefully during the coming months I will also add onefile support, icons, etc. for the OS too. I now have access to machines and develop for it as well, but right now e.g. getting PySide 6.1 to work is a higher priority.

**Comment by kayhayen** [comment]
I actually believe this is not about mixed versions, but wrong build host OS, or are you saying you built on 10.3?

**Comment by kayhayen** [comment]
For the record, this affects PySide too, and probably is a general standalone issue with frameworks, introduced in a macOS update.

**Comment by quadhead** [comment]
Thanks for your answer.

Correct, I am on mac OS 11.3 and mixing these versions works with Windows nuitka deployment. And it works perfectly with pure Python on mac and windows.
I don't have a choice, because I have PyQt commercial, which is only available as 5.15.4. 
Everyone on mac using PyQt 5.15.4 (be it commercial or not) will have this problem when deploying with nuitka I guess.

My second choice could be to upgrade everything and try PyQt 6.1 with nuitka. What are the odds in your opinion that this could be successful? ;)

**Comment by kayhayen** [comment]
Using PySide 6.1 is generally your best bet, as it has upstream support for Nuitka. However, there is a bug open #1097 that I however erase. Interestingly the PySide2 is not affected by that, but that's my commercial offering only. I will try to address that issue. For PyQt there are open incompatibilites with Nuitka to the point, that I will potentially consider it unsupported in the future unless Riverbank works with me to resolve them.

But I believe it's a new macOS standalone issue you are facing, and the way out would be to build your program on 10.13 and use that. It's the lowest supported OS for Qt, and should then work on everything else.

Windows allows to build on the latest no issue. Linux and macOS are way more sensitive, and generally need you to build on older. I will research for ways to make that not true with macOS. For Linux plans are for using containers of old Linux on new Linux. For macOS something similar needs to be done, but I am not  there yet. But using old macOS will work to deploy on new macOS, that I expect to be the case.

**Comment by quadhead** [comment]
Thank you. Honestly this is quite frustrating.
I will not go and get an old Mac with High Sierra just to try this. There is docker-osx, but not for versions that old.

My options are now:
Migrate to PySide6 and hope that you will make it work some day.
Migrate to PySide2 and give you the money just to compile this outdated 5.15.2 version.
Leave my backend code in Python and make it a dynamic lib and build the complete frontend from scratch in a different technology (e.g. Flutter).

Neither option really makes me happy.

**Comment by kayhayen** [comment]
The macOS support has improved significantly, since then PyQt5 has worked for as good as it can. Of course PySide6 and maybe PyQt6 if it gets fixes are still recommended.
