### ISSUE TITLE
importlib.metadata.PackageNotFoundError: jsonschema

### ISSUE THREAD

**Issue by mesca** [Nuitka/Nuitka#1108]
(Maybe related to #1068, closed yesterday)

When running a small script compiled in standalone mode, I get:

```
Traceback (most recent call last):
  File "[...]/test.dist/jsonschema_test.py", line 1, in <module>
  File "[...]/test.dist/jsonschema/__init__.py", line 34, in <module jsonschema>
  File "[...]/test.dist/importlib/metadata.py", line 551, in version
  File "[...]/test.dist/importlib/metadata.py", line 524, in distribution
  File "[...]/test.dist/importlib/metadata.py", line 187, in from_name
importlib.metadata.PackageNotFoundError: jsonschema
```

Python installed with anaconda in dedicated environment.

``$ python -m nuitka --version``

```
0.6.15
Python: 3.9.5 (default, May 18 2021, 12:31:01)
Executable: /Users/mesca/anaconda3/envs/nuitka/bin/python
OS: Darwin
Arch: x86_64
```

I have the same issue when using the develop branch (v0.6.16rc1).

``$ python -m pip freeze | grep jsonschema``

```
jsonschema==3.2.0
```

Minimal example:

```
from jsonschema import validate

if __name__ == "__main__":
    schema = {
        "type" : "object",
        "properties" : {
            "foobar" : {"type" : "number"}
        }
    }
    validate(instance={"foobar": 42}, schema=schema)
```

Nuitka output:

```
Nuitka-Options:INFO: Used command line options: --standalone --plugin-enable=pkg-resources test.py
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.16rc1' on Python '3.9' commercial None.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'tkinter' added '_tkinter'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'socket' added '_socket'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: clang (clang).
Nuitka-Scons:INFO: Compiled 56 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'disabled': 1
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 55
Nuitka-Plugins:INFO: data-files: Included data dir 'jsonschema/schemas' with 4 files due to package data for 'jsonschema'.
Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3/Grammar3.9.5.final.0.pickle' due to package data for 'lib2to3.pgen2'.
Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3/PatternGrammar3.9.5.final.0.pickle' due to package data for 'lib2to3.pgen2'.
Nuitka:INFO: Keeping build directory 'test.build'.
Nuitka:INFO: Successfully created 'test.dist/test'.
```

**Comment by kayhayen** [comment]
Please use `--enable-plugin=pkg-resources` and it ought to work. Let me know if that is not the case.

**Comment by kayhayen** [comment]
The plugin should be activated by default. I am starting to think there is no downside to that, but it's relatively hard to discover the plugin with the many names and mechanisms to cover.

**Comment by kayhayen** [comment]
Also, did you not get a warning about the plugin not being used if you didn't use it? With the foreseen change, making it active by default, that becomes irrelevant, but I am curious about this, maybe some mechanism for that warning isn't working as expected.

**Comment by mesca** [comment]
> Please use `--enable-plugin=pkg-resources` and it ought to work. Let me know if that is not the case.

I _did_ use the `pkg-resources` plugin, as can be seen in the Nuitka output:
```
Nuitka-Options:INFO: Used command line options: --standalone --plugin-enable=pkg-resources test.py
```

Datafiles are included (thanks to the `pkg-resources` plugin), but the metadata error happens for another reason. When compiled in standalone mode, the package is not discoverable by `importlib.metadata`. The error is triggered by [this line](https://github.com/Julian/jsonschema/blob/bda42e3cc541aa416df3e35d58d48750f91c47de/jsonschema/__init__.py#L39).

You can reproduce the issue with the minimal example I provided above.

 The simple fix is to replace the dynamic call to `version()` by a hardcoded value at compile time (see #1109).

**Comment by kayhayen** [comment]
@mesca my apologies for not noticing, can you checkout why it's not matching there? There is code precisely to do that hardcoded value replacement in that plugin.

**Comment by mesca** [comment]
Yes, I am looking into it right now. I think I have a clue. I have a short meeting and will come back to you.

**Comment by mesca** [comment]
OK, I've fixed the issue in `pkg-resources`.

**Comment by kayhayen** [comment]
Fixed on github develop, but there will be a hotfix for this soon.

**Comment by kayhayen** [comment]
Already releases as part of a hotfix.
