### ISSUE TITLE
How to include data files in non-standalone app

### ISSUE THREAD

**Issue by stolpa4** [Nuitka/Nuitka#1116]
I have a pretty large python application with multiple sub-packages, etc. And I want to create a binary from it. Not a standalone binary, but the one that is intended to be used in the same python environment with all the dependencies installed on the Docker container.

The use-case is as simple as I want to protect my python code, but let anyone use my library as-is.

With your beautiful tool, I can make it, however, there is one major concern. My application has data files, and those, as far as I understand, can be included in a binary only in the standalone/onefile mode.

So my question is: Is it possible to somehow include the data files I have, so I can use the compiled binary as intended?

One possible solution will be to restore the whole project structure and stick to --file-reference-choice=original. But I want to use --file-reference-choice=frozen and not expose any structure to an end-user. Are there other possibilities to resolve the issue?

**Comment by kayhayen** [comment]
The Nuitka commercial offering has data hiding and a plugin to include data files inside the binary. It isn't yet advertised here, but will be when get around to updating it: https://nuitka.net/pages/commercial.html
