### ISSUE TITLE
about using NuitKa  to tensorflow1.14  ，error TypeError: startswith first arg must be str or a tuple of str, not NoneType

### ISSUE THREAD

**Issue by zhanghongyong123456** [Nuitka/Nuitka#1118]
![002](https://user-images.githubusercontent.com/48466610/120802673-4be3d500-c575-11eb-94fd-08a2b15cb83c.png)
I using win10 python3.6.7 tensorflow 1.14.0

**Comment by zhanghongyong123456** [comment]
The first mistake is
![007](https://user-images.githubusercontent.com/48466610/120804360-22c44400-c577-11eb-8e82-d8675eef97d0.png)
![006](https://user-images.githubusercontent.com/48466610/120804376-26f06180-c577-11eb-9b16-a6248a7b74ca.png)

，and i Modify the source code，and  get the second error above after compiling

**Comment by zhanghongyong123456** [comment]
elements = module_name.split(".")   Changed to    elements = module_name.getTopLevelPackageName()

**Comment by kayhayen** [comment]
Yes, that plugin has not been updated for that API change. A fix is on factory: https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
Part of 0.6.15.3 hotfix release.

**Comment by YuJie-Tian** [comment]
@kayhayen Hello, I have the same problem.
I using win10 python=3.7.3 tensorflow=1.14.0.
And i tried NuitKa=0.6.15/0.6.15.3/0.6.16/0.6.17rc2.
Do you know the reason for the error?
Look forward to your reply! Thank u!

![1](https://user-images.githubusercontent.com/68223422/127830809-e3db70db-ac7d-4de6-bb9d-3b6a33ffc740.png)

**Comment by YuJie-Tian** [comment]
It's runing！
1.  #1118
I changed the version of Python and TensorFlow,
**Python=3.6.5 TensorFlow=1.8.0.**

2. #190 
**delete ‘--plugin-enable=numpy‘**, it seems to be in conflict with CV2.
