### ISSUE TITLE
Enable '-o FILENAME' argument in --onefile mode

### ISSUE THREAD

**Issue by bearsh** [Nuitka/Nuitka#1119]
Nuitka v0.6.14.7 errors when using `-o FILENAME` in `--onefile` mode. It would be nice to be able to specify the output filename.

**Comment by kayhayen** [comment]
You are right, that seems overly harsh.

**Comment by kayhayen** [comment]
Done, https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
This is part of the current pre-release.

**Comment by LdwgWffnschmdt** [comment]
Your changes (https://github.com/Nuitka/Nuitka/commit/14396da531d70c494680e27a7dc0ce8bc77b91ed) actually break specifying the output filename if you are not in onefile mode.

**Comment by kayhayen** [comment]
Thanks for reporting @LdwgWffnschmdt this is now on factory, and I shall soon update develop to unbreak this. I also noticed that the binary name used inside the onfile was not affected, but now it's using the basename of the name given with "-o" too, and therefore handles onefile entirely separately. I don't think this needs a rebase, the `-o` option is not used in testing at all.

**Comment by kayhayen** [comment]
Part of the 0.6.16 release.
