### ISSUE TITLE
Is the module "baron" used in Nuitka?

### ISSUE THREAD

**Issue by suliuzh** [Nuitka/Nuitka#1123]
Hi,
There seems to be no code in the source code that uses the module "baron". But in “/requirements-devel.txt”, "baron == 0.9" is still listed.

The following commit removes " from baron.parser import ParsingError" in "nuitka/tools/quality/autoformat/Autoformat.py ".
[Minor update](https://github.com/Nuitka/Nuitka/commit/b698adae2ef3072874bc3694ae4df08175f1b19e)

So is baron a unused dependency?

**Comment by kayhayen** [comment]
Redbaron uses baron, but it didn't expose the exception. When we started using `black` for formatting, only one task has remained is to update comments for pylint. They used to be arbitrary order, which is bad for searching them, and redbaron is used to sort them and to enforce their value names to be standardized.

We could rewrite this code to not use it, but I kind of like redbaron, and should it or something like it, become more mature, it could be a nice tool for source level patches to be done with Nuitka. Any pointers are welcome here.
