### ISSUE TITLE
Error: No module named 'numpy.core._multiarray_umath', when calling compiled module with numpy imported

### ISSUE THREAD

**Issue by rtchiew** [Nuitka/Nuitka#1127]
Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

```
python -m nuitka --version
0.6.15.3
Python: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
OS: Windows
Arch: x86_64
```

numpy version: 1.19.5

How did you install Nuitka and Python
`python -m pip install nuitka`

Code:
```
import numpy as np
def gen_text(seed_text):
    return str('HelloWorld')

```
Cli:
`python -m nuitka --module --follow-imports word_pred_min.py`

Compiled successfully into word_pred_min.pyd. But on calling the module, returned error:

```
Traceback (most recent call last):
  File "D:\Repos\PythonTest\numpy\core\__init__.py", line 22, in <module numpy.core>
  File "D:\Repos\PythonTest\numpy\core\multiarray.py", line 12, in <module numpy.core.multiarray>
  File "D:\Repos\PythonTest\numpy\core\overrides.py", line 7, in <module numpy.core.overrides>
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "word_pred_api.py", line 1, in <module>
    import word_pred_min
  File "D:\Repos\PythonTest\word_pred_min.py", line 1, in <module word_pred_min>
    import numpy as np
  File "D:\Repos\PythonTest\numpy\__init__.py", line 140, in <module numpy>
  File "D:\Repos\PythonTest\numpy\core\__init__.py", line 48, in <module numpy.core>
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "D:\Python38\python.exe"
  * The NumPy version is: "1.19.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

```

**Comment by kayhayen** [comment]
I bet you failed to consider reading the warning Nuitka has output durding compilation.

**Comment by rtchiew** [comment]
Other than a warning about enabling plugin pkg-resources, there are no other warnings. 
`python -m nuitka --module --follow-imports --plugin-enable=pkg-resources word_pred_min.py`

The compiled pyd resulted in the same error when called.

**Comment by kayhayen** [comment]
Sorry for my oversight, but you are not using standalone mode at all.

**Comment by kayhayen** [comment]
In accelerated mode, mixing compiled and uncompiled codes is not working very well. For numpy you are doing that, and this causes it to fail. You must not follow imports to numpy or the support for loading modules into compiled modules must be entirely complete, which it is not.

**Comment by ryancinsight** [comment]
I just want to piggyback on this and say if you create a numpy folder where you run your script and copy structure of wheel folder but only keeping the pyd files then this will run. only issue I've had is with scipy that has a _highs folder in optimize that nuitka thinks is a module instead. Is there a one folder option for --module flag, I also noticed numpy plugin is disabled for module creation on windows at least even when specified.

**Comment by kayhayen** [comment]
Closing it as a duplicate, there are no numpy problems when you do standalone. For acceleration it will not work, that needs not be here open.
