### ISSUE TITLE
PySide6.1.0  error(Reason: image not found, macos10.14.6) 

### ISSUE THREAD

**Issue by malizheng** [Nuitka/Nuitka#1128]
- Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)
0.6.15.3
Python: 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) 
Executable: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3
OS: Darwin
Arch: x86_64

- How did you install Nuitka and Python

pip3 install Nuitka

- I wroten this code (with pyside6 6.1.0):

`
import sys

from PySide6 import QtCore, QtGui, QtWidgets

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    print("123")
`

`sudo nuitka3 --standalone --show-progress --show-memory --plugin-enable=pyside6 --output-dir=open_quk quk.py`

- The following error was encountered:

Traceback (most recent call last):
  File "/Users/lizh/Desktop/daima/open_quk/quk.dist/quk.py", line 2, in <module>
ImportError: dlopen(/Users/lizh/Desktop/daima/open_quk/quk.dist/PySide6/QtCore.so, 2): Library not loaded: @rpath/QtQml.framework/Versions/A/QtQml
  Referenced from: /Users/lizh/Desktop/daima/open_quk/quk.dist/libpyside6.abi3.6.1.dylib
  Reason: image not found

logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by kayhayen** [comment]
You are confusing me here.

**Comment by kayhayen** [comment]
Yes, it might be a duplicate, if you want to help, in `nuitka.freezer.Standalone` there is probably not much to do, to make it handle `@rpath/` better. Otherwise you will have to wait. And then make sure to use 6.1.1 which is already released and has an important fix for Nuitka.

**Comment by malizheng** [comment]
Thank you, I'll follow your lead and try to find out.

**Comment by kayhayen** [comment]
Hoping for a PR there :)

**Comment by malizheng** [comment]
I looked at the code today and found that @rpath may have been called in .so, which is why nuitka can't detect it. I would like to ask if it is possible to specify @rpath as @executable_path when the program is running.

**Comment by kayhayen** [comment]
Are you saying it's not in `otool` output and cannot be changed? Because if it's not things will be very ugly for us.

**Comment by malizheng** [comment]
Thank you for your reply. I solved the above problem through the install_name_tool function.

**Comment by kayhayen** [comment]
Well, yes, and Nuitka does that in said code, but somehow fails in this instance, that's what I asked you to debug and correct.

**Comment by kayhayen** [comment]
This should be resolved for a long time already, PySide6 on macOS works like a charm.
