### ISSUE TITLE
Question: How to include copyright information in compilation

### ISSUE THREAD

**Issue by GentleVincent** [Nuitka/Nuitka#1129]
Hello, I like nuitka, thank you for it.
Is there a way to compile copyright information to .exe file on wondows system just like complie product name by using parameter --windows-product-name?

**Comment by kayhayen** [comment]
The option `--copyright` has been added a while ago. Currently has only effect on Windows, but other platforms will follow.

**Comment by kayhayen** [comment]
There is also a license report in newer Nuitka, that can be used to describe what licenses your binary is subject to.
