### ISSUE TITLE
Nuikta executable raising ModuleNotFoundError: No module named '_curses' #1113

### ISSUE THREAD

**Issue by Justaus3r** [Nuitka/Nuitka#1132]
Re-addressing issue [1113](https://github.com/Nuitka/Nuitka/issues/1113),
as i didn't got response on my last question and my question wasn't clearly explained(i apologize for the duplicate,i can close the previous issue if you want).

Python version(not a python specific problem):
```
$ python --version
Python 3.8.3
```

Nuitka version:
```
$ python -m nuitka --version                                                    
0.6.15                                                                          
Python: 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (A
MD64)]                                                                          
Executable: C:\Users\Administrator\AppData\Local\Programs\Python\Python38\python
.exe                                                                            
OS: Windows                                                                     
Arch: x86_64                                             
```

command used to compile the script:
```
python -m nuitka  --plugin-enable=tk-inter --standalone Anfu.py
```
How to reproduce the problem:
- First install [windows-curses](https://pypi.org/project/windows-curses/) ,[rich](https://pypi.org/project/rich/) ,[cryptography](https://pypi.org/project/cryptography/).
- Download the zip from [here](https://github.com/Justaus3r/Anfu/archive/refs/tags/0.1.3.zip).
- Build the script ,when you run the executable it just show the following error and terminates:
```
$ Anfu.exe
Traceback (most recent call last):
  File "C:\Users\ADMINI~1\Desktop\PROGRA~1\Anfu\ANFU~1.DIS\Anfu.py", line 26, in <module>
  File "C:\Users\ADMINI~1\Desktop\PROGRA~1\Anfu\ANFU~1.DIS\curses\__init__.py", line 13, in <module>
ModuleNotFoundError: No module named '_curses'
```

**Comment by kayhayen** [comment]
That's not how things work with me.
