### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified.

### ISSUE THREAD

**Issue by dmz73vu** [Nuitka/Nuitka#1134]
Fresh python and nuitka install.
python -m nuitka --version
0.6.15.3
Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
Executable: C:\Apps\Python\Python39\python.exe
OS: Windows
Arch: x86_64
Following steps in "Create a folder for the Python code" from github I get the error from the title:
python -m nuitka --mingw64 hello.py
Nuitka-Options:INFO: Used command line options: --mingw64 hello.py
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.15.3' on Python '3.9' commercial None.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Mismatch between Python binary ('C:\\Apps\\Python\\Python39\\python.exe' -> 'pei-x86-64') and C compiler ('C:\\Apps\\TDM-GCC-64\\bin\\gcc.exe' -> 'pei-i386') arches, ignored!
Nuitka-Scons:INFO: Backend C compiler: C:\Users\cu\AppData\Local\Nuitka\Nuitka\gcc\x86_64\10.2.0-11.0.0-8.0.0-r5\mingw64\bin\gcc.exe (gcc.exe).
Nuitka-Scons:INFO: Compiled 11 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 11
Traceback (most recent call last):
  File "C:\Apps\Python\Python39\lib\site-packages\nuitka\__main__.py", line 187, in <module>
    main()
  File "C:\Apps\Python\Python39\lib\site-packages\nuitka\__main__.py", line 173, in main
    MainControl.main()
  File "C:\Apps\Python\Python39\lib\site-packages\nuitka\MainControl.py", line 728, in main
    executePostProcessing()
  File "C:\Apps\Python\Python39\lib\site-packages\nuitka\PostProcessing.py", line 321, in executePostProcessing
    addResourceToFile(
  File "C:\Apps\Python\Python39\lib\site-packages\nuitka\utils\WindowsResources.py", line 263, in addResourceToFile
    update_handle = _openFileWindowsResources(target_filename)
  File "C:\Apps\Python\Python39\lib\site-packages\nuitka\utils\WindowsResources.py", line 170, in _openFileWindowsResources
    raise ctypes.WinError()
FileNotFoundError: [WinError 2] The system cannot find the file specified.

When stepping through code in debugger, the error seems to be caused due to parameter "filename" in line "update_handle = BeginUpdateResource(filename, False)" not having the full path but instead it is just the target file (hello.exe). If I manually change "filename" to full path ('D:\\Dev\\Python\\projects\\helloworld\\hello.exe' in my case) then process completes without error.

**Comment by kayhayen** [comment]
Ok, this has been observed before, and even fixed by @Maxwell175 but I refused it on the grounds of it not possibly being required, as we don't change the directory, and the file exists under that path. However, this is sufficient evidence now, I will change it for the next release.

**Comment by kayhayen** [comment]
It was never not merged, I was wrong there, I trusted @Maxwell175 and therefore this is part of 0.6.16 automatically which is now released.
