### ISSUE TITLE
Add support to pygsheets

### ISSUE THREAD

**Issue by scherzocrk** [Nuitka/Nuitka#1135]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

```
  0.6.15.3
  Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
  Executable: path\to\project\.venv\Scripts\python.exe
  OS: Windows
  Arch: x86_64
```

* How did you install Nuitka and Python

  `poetry add nuitka`

* The specific PyPI names and versions

```
[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.25.1"
PyYAML = "^5.4.1"
pygsheets = "^2.0.5"
pandas = "^1.2.4"
loguru = "^0.5.3"
APScheduler = "^3.7.0"
pytz = "^2021.1"

[tool.poetry.dev-dependencies]
black = "^21.6b0"
Nuitka = "^0.6.15"
```

In order for pygsheets packages to work, I had to use --include-data-dir="path/to/project/.venv/Lib/site-packages/pygsheets/data"="pygsheets/data" while compiling using --standalone option. There are two json files in this folder that need to be copied. Not sure if you want to support this package for other users.

**Comment by kayhayen** [comment]
I could not reproduce it with a mere import, would you have an example code for it?
