### ISSUE TITLE
[PyQt5] TypeError: 'compiled_method' object is not connected

### ISSUE THREAD

**Issue by Hintay** [Nuitka/Nuitka#1137]
Hello,
I'm having the same issues with #833, this will only occur when disconnecting the signal if specific a slot.

I have written a minimal reproducer:
```python
import sys
from PyQt5.QtCore import QObject, QCoreApplication, pyqtSignal, pyqtSlot, QTimer


class TestObject(QObject):
    test_signal = pyqtSignal()

    def __init__(self, parent=None):
        super().__init__(parent)
        self.parent = parent
        self.test_signal.connect(self.test_slot)
        self.timer = QTimer()

    @pyqtSlot()
    def test_slot(self):
        print("This is a test slot.")
        self.timer.singleShot(100, self.on_timeout)

    @pyqtSlot()
    def on_timeout(self):
        print("Disconnect signal.")
        self.test_signal.disconnect(self.test_slot)
        self.parent.quit()


if __name__ == "__main__":
    app = QCoreApplication(sys.argv)
    test_object = TestObject(app)
    test_object.test_signal.emit()
    app.exec()
```

Use the following command with Nuitka:
```shell
nuitka --mingw64 --follow-imports --plugin-enable=pylint-warnings qtsignal_test.py
```
There will be a TypeError after running it.
```
> signal_test.exe
This is a test slot.
Disconnect signal.
Traceback (most recent call last):
  File "qtsignal_test.py", line 22, in on_timeout
    self.test_signal.disconnect(self.test_slot)
TypeError: 'compiled_method' object is not connected
```
Environments:
- Python 3.8.8 x86_64 in Miniconda
- PyQt5 5.15.4
- Nuitka 0.6.15.3
- Windows 10 20H2

**Comment by kayhayen** [comment]
Unfortunately PyQt5 seems to not be working well. I recommend using PySide2, esp. with the patches avaiable in the Nuitka commercial offering, or PySide 6.1.2 once it's available, which will be fully correct out of the box.

https://nuitka.net/pages/pyside2.html

Yours,
Kay

**Comment by kayhayen** [comment]
I have also reached out to Riverbank just now. I will probably add warnings to Nuitka when you use PyQt5 about the many problems this will have and recommend to switch to PySide unless that address those bugs or make it that it makes sense for me to do it.

**Comment by Hintay** [comment]
Thanks for your help! Unfortunately PySide 2 does not have qmlRegisterSingletonType and qmlRegisterUncreatableType ([link](https://bugreports.qt.io/browse/PYSIDE-574)). And in the meantime my project uses QSerialPort, which was removed in Qt 6.0 and [reintroduced in Qt 6.2](https://wiki.qt.io/New_Features_in_Qt_6.2). So I have to use PyQt 5.12 until Qt 6.2 is released then I can switch to PySide.

**Comment by kayhayen** [comment]
This is not ideal. I have been in contact with Riverbank about PyQt. Not sure what will come out of it though. I would be very surprised if it was a fixed 5.x release though.

**Comment by arthurchen1906** [comment]
it seems signal.disconnect() will work, but with some slot parameter in won't.

if it's one signal & one slot connection, just set the disconnect parameter void.

**Comment by KevinRodriguez777** [comment]
this works nowadays as long as `--enable-plugin=pyqt5` is active.

**Comment by arthurchen1906** [comment]
来信已收到！我会及时处理。

**Comment by kayhayen** [comment]
The Chinese email auto-responders are really bad sources of wasted time.
