### ISSUE TITLE
Notify users of missing libraries before the end of compilation

### ISSUE THREAD

**Issue by tebulo0** [Nuitka/Nuitka#1138]
If compiling with --standalone the user gets a notification at the end of compilation that chrpath needed to be installed. 
It would be nice if the user could get a small error popup at the beginning of compilation with all the missing libraries and possibly a command suggestion:

sudo apt install gcc g++ ccache chrpath

**Comment by kayhayen** [comment]
It depends on on the system if `chrpath` is needed. Many systems and many compilations don't need it, and clearly not all modes need it. So only once the standalone compilation actually reaches the part where it encounters a wrong rpath, it will do that, and on Debian in particular, with system packages, it will not. 

That said, the Nuitka Debian packages recommend `chrpath` and require `ccache`.

In a PyPI world, it seems to depend on the packages used.

Yours,
Kay
