### ISSUE TITLE
Nuitka+fastapi+uvicorn=«multiprocessing/resource_tracker.py:96: UserWarning: resource_tracker: process died unexpectedly, relaunching»

### ISSUE THREAD

**Issue by belonesox** [Nuitka/Nuitka#1139]
Consider following minimal sample project used FastAPI with uvicorn, based on pipenv for fast reproduceability.
https://github.com/belonesox/fastapi-unicorn-nuitka-troubles

* Checkout it.
* ``test1.py`` demo service with 1 worker
* ``test2.py``  demo run service with 2 workers
* ``sh reproduce-me.sh`` — compile both of them

* ``pure_python_ok.sh`` — successfully run using raw python (both 1worker and 2worker versions).
```
INFO:     Uvicorn running on http://0.0.0.0:8040 (Press CTRL+C to quit)
INFO:     Started parent process [1138946]
INFO:     Started server process [1138961]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Started server process [1138962]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
```
To check that service is working, just open http://localhost:8040/docs

* ``compiled_1worker_ok.sh`` — run compiled nuitka version with 1 worker, OK
``
INFO:     Started server process [1139332]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8040 (Press CTRL+C to quit)
``
* ``compiled_2worker_bad.sh`` — run compiled nuitka version with 2 worker, failed with
``
test2.dist/multiprocessing/resource_tracker.py:96: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.
``

**Comment by kayhayen** [comment]
Really good report, I will look at it, I like your usage of pipenv to make sure we have same versions.

**Comment by belonesox** [comment]
Just tested on 
```
nuitka = "0.6.17"
python_version = "3.9"
```

The problem still persists. :(

**Comment by belonesox** [comment]
Just tested on

```
nuitka = "0.6.19.7"
python_version = "3.9"
```

The problem still persists. :(

**Comment by hishamyousry** [comment]
I am facing the same issue on Nuitka 0.7.7 and Python 3.8. Is there any planned fix or a workaround for this issue?

**Comment by belonesox** [comment]
My workaround - to use `hypercorn`. (mostly compatible with uvicorn).

**Comment by kayhayen** [comment]
This just worked for me with 2 workers. Probably a multiprocessing improvement fixed that some time ago.

**Comment by belonesox** [comment]
Confirm that. Works for me on 
```
Fedora           34 
Nuitka            0.8.2
uvicorn           0.17.6
```  
even with 100 workers.

**Comment by melonamin** [comment]
Hi @kayhayen,
 
I'm having a similar issue, here is the relevant part of the environment

```
python 3.10.9
nuitka   1.4.8
uvicorn 0.20.0
```

Some of the routes in FastAPI fail with one of these two errors:

* `/.../multiprocessing/resource_tracker.py:104: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.
fish: Job 1, 'build/cli.dist/binary -unv a…' terminated by signal SIGBUS (Misaligned address error)`
* `/.../multiprocessing/resource_tracker.py:104: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.
fish: Job 1, 'build/cli.dist/binary -unv a…' terminated by signal SIGSEGV (Address boundary error)`

Most of the routes works, I can't find why the failing APIs fail. 

Is there a way to produce a more detailed error to help with debugging? `--trace-execution` is practically unusable for my purposes.

**Comment by kayhayen** [comment]
@melonamin Posting below closed issues is a surefire way to get ignored. I am not going to guess without a fresh issue template, what kinds of mistakes and setup you have made.
