### ISSUE TITLE
«--recompile-c-only» looks not working as expected

### ISSUE THREAD

**Issue by belonesox** [Nuitka/Nuitka#1146]
Consider sample repo (with pipenv)
    https://github.com/belonesox/nuitka-and-recompile-case

There are 
* trivial python file  ``test.py``
* ``compile-full.sh`` — regular compile script to standalone
* ``recompile.sh`` — compile script with ``--recompile-c-only`` that I thought, only recompile C files generated by compile-full.sh. 

According help, …
```
    --recompile-c-only  This is not incremental compilation, but for Nuitka
                        development only. Takes existing files and simply
                        compile them as C again. Allows compiling edited C
                        files for quick debugging changes to the generated
                        source, e.g. to see if code is passed by, values
                        output, etc, Defaults to off.
```
… I expected that it only call scons  command to compile generated C files, but it still 
run all marathon with "PASS 1…2…", "Optimizing module", etc.

I am not sure, that it is bug, because I see 
```
Depends on compiling Python source to determine which files it should look at.
```

But if not, we needed another option like  ``--really-recompile-c-only-orly``  to only recompile C sources. (for example, I am trying to experiment with memory consumption of gcc compilation, without generating C sources) 

Or may be just generate file "build.me" in ".build" folder, with 
scons command and setted all environment staff that it need, like "NUITKA_PACKAGE_DIR", etc.

Any solutions appreciated!

**Comment by kayhayen** [comment]
Your expectation is wrong. It's for Nuitka development only. Nuitka still compiles the Python code to find out things that are not persisted on the build folder. And I don't care about a C recompile.
