### ISSUE TITLE
PySimpleGUI is not supported

### ISSUE THREAD

**Issue by monkeycc** [Nuitka/Nuitka#1147]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

0.6.15
Python: 3.6.13 |Anaconda, Inc.| (default, Mar 16 2021, 11:37:27) [MSC v.1916 64 bit (AMD64)]
Executable: D:\anaconda3\envs\dabao\python.exe
OS: Windows
Arch: x86_64

* How did you install Nuitka and Python

anaconda

* The specific PyPI names and versions

numpy                  1.19.3

* Also supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
* 
`import PySimpleGUI as sg`

`nuitka --mingw64 --standalone --show-memory --show-progress --plugin-enable=tk-inter --nofollow-imports --output-dir=software PySimpleGUI22.py`

ModuleNotFoundError: No module named 'PySimpleGUI'

**Comment by kayhayen** [comment]
This is not the current release. And congratulations on your combinations of options. You might want to consider help outputs and warnings.
