### ISSUE TITLE
An error occurred when I used OneFile

### ISSUE THREAD

**Issue by bulingda** [Nuitka/Nuitka#1148]
An error occurred when I used '--oneFile'.
![image](https://user-images.githubusercontent.com/55130106/124229352-0bf61a80-db40-11eb-81e1-4b675f02f9f7.png)
May I ask how to solve this problem? Thank you very much for your answer.

**Comment by kayhayen** [comment]
Done

**Comment by bulingda** [comment]
> Done

Did I not describe it in enough detail? Why did you turn off my question?
