### ISSUE TITLE
Why Nuitka requires MinGW64 installation and rejects MinGW32

### ISSUE THREAD

**Issue by Whirlpool-Programmer** [Nuitka/Nuitka#1149]
I already have gcc installed along with MinGW w32.
and it is also in the path!

but nuitka just starts downloading `winlibs-i686-posix-dwarf-gcc-10.2.0-llvm-11.0.0-mingw-w64-8.0.0-r5.zip` which is almost 390mb!
do it require MinGW w64 only?

**Comment by kayhayen** [comment]
MinGW is not MinGW64, and it's unrelated to the number of bits. From what I recall, the compatibility on MinGW with Windows is really bad for most programs. Therefore it's unsupported.
