### ISSUE TITLE
When running Nuitka from a batch script, all instructions after are ignored

### ISSUE THREAD

**Issue by TheQuinbox** [Nuitka/Nuitka#1152]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

0.6.12.2                                                                                                                
Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]                                    
Executable: C:\Users\tygil\AppData\Local\Programs\Python\Python37\python.exe                                            
OS: Windows                                                                                                             
Arch: x86_64                                                                                                            

* How did you install Nuitka and Python

Downloaded python from the website, and Nuitka through Pip.

* Also supply a [Short, Self Contained, Correct, Example](http://sscce.org/)

Put this inside a bat file, named really anything of your choice, and try to run it.

```batch
@echo off
nuitka  --standalone --python-flag=no_site --windows-disable-console --remove-output test.py
pause
echo This is a test
pause
```

After running, you'll notice that Nuitka runs, but once it does, it forcefully kills the batch file, doesn't let the instructions continue.

**Comment by kayhayen** [comment]
That's a very old release. How did you verify it's actually killed it?

**Comment by TheQuinbox** [comment]
Is it? This is the version that installed with PIP by default on a fairly new Py installation. I confirmed that it exited because none of the other instructions in the batchfile got ran after Nuitka

**Comment by kayhayen** [comment]
I was wrong with the version, can't read.

Depending on the example size, it may just keep compiling for a long time. Check out the user manual and what it says about the anti-bloat plugin. Make sure read this: https://nuitka.net/doc/user-manual.html#dependency-creep-in-standalone

If you are really daring, use https://nuitka.net/doc/factory.html where the plugin learned to also remove numpy.distutils and numpy.testing, and _pytest for many popular things.

This is what I am working with: (add it to your test.py) and develop releases of Nuitka e.g. avoid having both PySide2 and PyQt5 included, etc. if you enable the respective plugin for one.

```
# nuitka-project: --noinclude-custom-mode=numpy._pytesttester:error
# nuitka-project: --noinclude-custom-mode=numpy.testing:error
# nuitka-project: --noinclude-custom-mode=numpy.distutils:error
# nuitka-project: --noinclude-custom-mode=scipy._lib._testutils:error
# nuitka-project: --noinclude-custom-mode=matplotlib:nofollow
# nuitka-project: --noinclude-custom-mode=pandas.util.testing:error
# nuitka-project: --noinclude-custom-mode=pandas.testing:error
# nuitka-project: --noinclude-custom-mode=pandas.util._tester:error
# nuitka-project: --noinclude-custom-mode=jinja2.tests:error
```

Generally scalability can be an issue. But other than that, maybe some sort of out of memory killer from Windows could kill not only the task, but its shell, I never knew however than Windows has that. But nothing in Nuitka can kill the terrminal really. So I am thinking you may be confused. I agree, it's typically me, see version. :)

**Comment by kamgha** [comment]
Try `python.exe -m nuitka --standalone ...`, I can not reproduce this.

What Windows version are you using?
Can you try a newer CPython 3.7 version than 3.7.0?
Did you try this on a different machine as well?

> maybe some sort of out of memory killer from Windows

Windows should inform the user about low memory, I've never seen it silently terminate processes.

**Comment by kayhayen** [comment]
To my knowledge, Nuitka never kills any process outside of its test suite for onefile on Windows. It's just incapable of that. I am putting this to invalid and closed, but will reopen with evidence provided.

**Comment by kayhayen** [comment]
As an aside, 3.7.0 is the worst CPython release I have ever seen. Update it no matter what you do, it's full of memory leaks. That's not going to help using Nuitka.
