### ISSUE TITLE
OpenCV

### ISSUE THREAD

**Issue by maxekb** [Nuitka/Nuitka#1155]
Hello 
0.6.16.2
Python: 3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Users\Max\Anaconda\python.exe
OS: Windows
Arch: x86_64

I try use opencv & compile it.
my opencv version 4.2
a nuitka used version 4.3
![Screenshot_60](https://user-images.githubusercontent.com/4647338/125514118-08e863a6-7a75-458b-8406-4fc8796624a7.jpg)

cv 4.2 & 3.4 have different syntax.
what's best way to compile programm ?

**Comment by kayhayen** [comment]
Read the user manual, there is a way there that makes sure you are using the correct Python. Using one for Nuitka and one for Python is most likely what is going on here.

**Comment by maxekb** [comment]
Sorry, thank  you
real problem in locked .pyd library.
