### ISSUE TITLE
How to use C/C++ to link .so file?

### ISSUE THREAD

**Issue by thread-liu** [Nuitka/Nuitka#1156]
## version

- Nuitka == 0.6.16.2
- Python == 3.8.10

## Description

In Ubuntu 20.04, I used Nuitka to generate a Python file as a .so file. Can I call the.so file directly using C/C++?

```python
# main.py
def print_hi():
    print("hello,  world")
```

use cmd `nuitka --module --output-dir=out main.py` to generate libmain.so

```c
// test.c
#include <stdio.h>
#include <dlfcn.h>
int main(void)
{
        int i;
    libfunc func;
    void *handler;
    
    handler = dlopen("./libmain.so",RTLD_LAZY);
    if (handler == NULL)
    {
        printf("dlopen error!\n");
        return -1;
    }
    
    func = dlsym(handler, "print_hi");
    dlclose(handler);

    return 0;
}
```

use cmd `gcc -o test test.c -ldl`    

run test:

./test

Open Error: ./libmain.so: undefined symbol: PyExc_SystemError.

Thanks for your help!

**Comment by kayhayen** [comment]
Check the questions tag. That is not how it works, you need to embedd Python to use an extension module.

**Comment by thread-liu** [comment]
> Check the questions tag. That is not how it works, you need to embedd Python to use an extension module.

I add `libpython3.8.so ` file,  it also not work:  `Dlsym Error:./libmain.so: undefined symbol: print_hi`

**Comment by kayhayen** [comment]
Embedding Python is not linking libpython: https://docs.python.org/3/extending/embedding.html

**Comment by liukangcc** [comment]
> Embedding Python is not linking libpython: https://docs.python.org/3/extending/embedding.html

Thanks for your help!
