### ISSUE TITLE
Error while running binary: h5py.h5.H5PYConfig' has no attribute '__reduce_cython__ 

### ISSUE THREAD

**Issue by kaoh** [Nuitka/Nuitka#1168]
I get the following error:

>...
  File "/tmp/.mount_rasa.bnnIZLM/h5py/version.py", line 17, in <module h5py.version>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "h5py/h5.pyx", line 41, in init h5py.h5
AttributeError: type object 'h5py.h5.H5PYConfig' has no attribute '__reduce_cython__'

During the build I get this warning, but I don't know how to fix this:

> Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libz-a147dcb0.so.1.2.3'.
/home/widerstand/Projekte/nuitka_issue/venv/lib/python3.8/site-packages/h5py/.libs/././libz-a147dcb0.so.1.2.3 used by:
   rasa.dist/h5py/_conv.so
different from
/home/widerstand/Projekte/nuitka_issue/venv/lib/python3.8/site-packages/psycopg2/../psycopg2_binary.libs/libz-a147dcb0.so.1.2.3 used by
   rasa.dist/psycopg2/_psycopg.so

* Please check out if the develop version of Nuitka works better for you.

Not tested. Found no pip package.

* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

  > python -m nuitka --version

> 0.6.16.2
Python: 3.8.10 (default, Jun  2 2021, 10:49:15) 
Executable: /home/kaoh/projects/test_nlu/venv/bin/python
OS: Linux
Arch: x86_64

* How did you install Nuitka and Python

I used pip in a virtualenv

* The specific PyPI names and versions

I guess these are the main packages:

>numpy==1.18.5
rasa==2.6.2
spacy==3.0.6
tensorflow==2.3.2

* Also supply a [Short, Self Contained, Correct, Example](http://sscce.org/)

[This project](https://github.com/kaoh/nuitka_issue) demonstrates the issue.

**Comment by kayhayen** [comment]
The "short" part for the example falls a bit short, but it's easy. I did some h5py work, and now I want to see how this fares, seems to work for me with factory version. I just got `rasa -h` to work, let me know if something else might be missing.

**Comment by kaoh** [comment]
No sure, what the last comment implies, does the provided example work for you? For me not.

**Comment by kayhayen** [comment]
With this version, it should: https://nuitka.net/doc/factory.html it's also soon going to part of develop branch.

**Comment by kaoh** [comment]
Now, I got it. there is a factory version, I was not aware of. I will try it. Thanks.

**Comment by kayhayen** [comment]
The change is in fact also on develop right now and will be part of the next release. I am even closing the issue, but I would like you to repoen it if that `rasa` binary can be made to demonstrate a problem, I will keep the test case around for a while, but the originally reported issue should be solved.
