### ISSUE TITLE
Question: Is there a way to achieve pythonw behavior?

### ISSUE THREAD

**Issue by aarmn** [Nuitka/Nuitka#1180]
There is no way for making a Nuitka made executable run without a console pop-up, like when a python file is saved with ".pyw" behavior.

I scanned all switches once and searched all over google

I don't flag it rn, cause it may be my mistake, as I'm newbie in this project, if this feature is not out there, this shall be flagged as "enhancement"

**Comment by kayhayen** [comment]
Yes, there is an option, checkout  `--windows-disable-console`
