### ISSUE TITLE
optimizing comtypes.gen.* is slow

### ISSUE THREAD

**Issue by niki-sp** [Nuitka/Nuitka#1181]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

nuitka 0.6.17rc3
Python: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
OS: Windows
Arch: x86_64

* How did you install Nuitka and Python
installed from source - Git Commit: 97cec3f4f4b4

* The specific PyPI names and versions
comtypes   1.1.7

* Example
```
# just_comtypes.py
import comtypes
import comtypes.gen.MSHTML
```
* Nuitka options used
python3 -m nuitka --standalone --mingw --show-progress --nofollow-import-to numpy just_comtypes.py

[gen.zip](https://github.com/Nuitka/Nuitka/files/6967990/gen.zip)
generated comtypes wrappers for test

**Comment by KevinRodriguez777** [comment]
this most likely isn't revelant nowadays.
