### ISSUE TITLE
after build completely copy exe file to other competeur，error occurred

### ISSUE THREAD

**Issue by GaoTianTian96** [Nuitka/Nuitka#1182]
Thanks to the author!
To be able to provide such a great method

0.6.16.3
Python: 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
Executable: D:\Users\admin\anaconda3\python.exe
OS: Windows
Arch: x86_64

 
nuitka --standalone --mingw64 --show-memory --show-progress --nofollow-imports  --follow-import-to=need  --windows-icon-from-ico=ivision.ico    --output-dir=Release  eval.py 
 
build able normal runing on host computer，it is best way， but copy to other pc，error as follows

**ModuleNotFoundError: No module named 'need.backbone'**
backbone within need file

**Comment by kayhayen** [comment]
Read the help on options used. Your combination should be warned about and doesn't work.
