### ISSUE TITLE
Unable to package WinRT library

### ISSUE THREAD

**Issue by nemwiz** [Nuitka/Nuitka#1184]
Hello,

I'm trying to package my application which uses Windows runtime API (also known as WinRT) and there is an official Python wrapper provided by Microsoft. More info is available [here ](https://docs.microsoft.com/en-us/uwp/api/) and [here](https://github.com/microsoft/xlang/blob/master/src/package/pywinrt/projection/readme.md).

However this library is not packaged correctly because when I run my distributable I get an `AttributeError` and if you look into the winrt library under `winrt.windows.devices.__init__.py` on line 5 lies the root cause and 'Windows.Service' somehow don't get packaged in the final output.

Here is a repo with minimal reproduction of the issue https://github.com/nemwiz/winrt-nuitka-build

How do I include this library? I'm a bit stuck.
Also I couldn't find examples on how to include external libraries e.g. `.pyd` files. I just want my executable to find the needed libraries even if I have to copy/paste them from somewhere.
 
Thanks

**Comment by nemwiz** [comment]
After some trial and error I managed to find the issue.
WinRT ships a binary `_winrt.pyd` and when the library initializes they try to load it with the following code.

```
loader = importlib.machinery.ExtensionFileLoader(module_name, _winrt.__file__)
```

The key part here is `_winrt.__file__` and after Nuitka compilation this throws an error 
`'winrt._winrt' has no attribute '__file__'`

I saw the option `--file-reference-choice` and I've tried both `runtime `and `original `values, but same error appeared.

Is this a bug in Nuitka or the library uses some non standard way of importing binaries? Any guidance on this would be welcome.

At the moment I've found 2 workarounds and I don't like any of them. :)
1. Edit the library source code and replace `__file__` with a correct path to the binary
2. Exclude the library with `--nofollow-import-to=winrt` and copy/paste the `winrt` library from `venv` into the `dist` folder

**Comment by kayhayen** [comment]
Closing for lack of feedback.

**Comment by flozz** [comment]
Hello,

I have the exact same issue with [Bleak WinRT](https://github.com/dlech/bleak-winrt/) (Python 3.9 and Python 3.10 on Windows 10).

The [`__init__.py`](https://github.com/dlech/bleak-winrt/blob/main/pywinrt/bleak_winrt/__init__.py) file generated by WinRT looks like this:

```python
# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.0.0-alpha.6

from . import _winrt

def _import_ns_module(ns):
    import importlib.machinery
    import importlib.util

    try:
        module_name = "_bleak_winrt_" + ns.replace('.', '_')

        loader = importlib.machinery.ExtensionFileLoader(module_name, _winrt.__file__)
        spec = importlib.util.spec_from_loader(module_name, loader)
        module = importlib.util.module_from_spec(spec)
        loader.exec_module(module)
        return module
    except Exception:
        return None
```
as @nemwiz said, ` _winrt` has no `__file__` attribute.

I currently resolved my issue by patching the `__init__.py` file like this:

```python
# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.0.0-alpha.6

from . import _winrt

import os
_winrt.__file__ = os.path.join(os.path.dirname(__file__), "_winrt.pyd")

def _import_ns_module(ns):
    import importlib.machinery
    import importlib.util

    try:
        module_name = "_bleak_winrt_" + ns.replace('.', '_')

        loader = importlib.machinery.ExtensionFileLoader(module_name, _winrt.__file__)
        spec = importlib.util.spec_from_loader(module_name, loader)
        module = importlib.util.module_from_spec(spec)
        loader.exec_module(module)
        return module
    except Exception:
        return None
```

I hope this additional information can help. :)

**Comment by kayhayen** [comment]
@flozz it does, can you however create a new issue, where I would have a reproducer even. Nuitka should be setting `__file__` since last release, but I have zero information and context in order to reproduce this.
