### ISSUE TITLE
Object += tuple/list inplace add operation is not compatible (broken with numpy.array)

### ISSUE THREAD

**Issue by niki-sp** [Nuitka/Nuitka#1187]
Nuitka '0.6.17rc3' on Python '3.8' with mingw
numpy      1.20.3

test code:
```
from numpy import array

def test():
    line = (2, 3)
    line = array(line, 'd')
    line += (1, 2)
    print(line)

test()
```
**expected output:**
[3. 5.]
**real output:**
  File "npadd.py", line 6, in test
    line += (1, 2)
TypeError: Concatenation operation is not implemented for NumPy arrays, use np.concatenate() instead. Please do not rely on this error; it may not be given on all Python implementations.

**Comment by kayhayen** [comment]
Part of the latest hotfix.
