### ISSUE TITLE
Nuitka --onefile not working in Windows

### ISSUE THREAD

**Issue by RESP3CT88** [Nuitka/Nuitka#1188]
Python 3.9.6
Nuitka version 0.6.15.1

Program code (test.py):
`print("Detecting system...");`

Nuitka compilation command:
`python -m nuitka --mingw64 --onefile --windows-onefile-tempdir-spec=%TEMP%\\onefile_%PID%_%TIME% test.py`

Nuitka log:

> Nuitka-Options:INFO: Used command line options: --mingw64 --onefile --windows-onefile-tempdir-spec=C:\Users\Aaron\AppData\Local\Temp\\onefile_%PID%_16:49:26.33 test.py
> Nuitka:INFO: Starting Python compilation with Nuitka '0.6.15.1' on Python '3.9' commercial None.
> Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'tkinter' added '_tkinter'.
> Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'socket' added '_socket'.
> Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.
>                                                                                                                        Nuitka:INFO: Completed Python level compilation and optimization.
> Nuitka:INFO: Generating source code for C backend compiler.
>                                                                                                                        Nuitka:INFO: Running data composer tool for optimal constant value handling.
> Nuitka:INFO: Running C level backend compilation via Scons.
> Nuitka-Scons:INFO: Backend C compiler: C:\Users\Aaron\AppData\Local\Nuitka\Nuitka\gcc\x86_64\10.2.0-11.0.0-8.0.0-r5\mingw64\bin\gcc.exe (gcc.exe).
> Nuitka-Scons:INFO: Compiled 11 C files using ccache.
> Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 9
> Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 2
> Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3\\Grammar3.9.6.final.0.pickle' due to package data for 'lib2to3.pgen2'.
> Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3\\PatternGrammar3.9.6.final.0.pickle' due to package data for 'lib2to3.pgen2'.
> Nuitka-Postprocessing:INFO: Creating single file from dist folder, this may take a while.
> Nuitka:INFO: Running bootstrap binary compilation via Scons.
> Nuitka-Scons:INFO: Backend C compiler: C:\Users\Aaron\AppData\Local\Nuitka\Nuitka\gcc\x86_64\10.2.0-11.0.0-8.0.0-r5\mingw64\bin\gcc.exe (gcc.exe).
> Nuitka-Scons:INFO: Compiled 1 C files using ccache.
> Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 1
> Nuitka:INFO: Keeping onefile build directory 'test.onefile-build'.
> Nuitka:INFO: Keeping dist folder 'test.dist' for inspection, no need to use it.
> Nuitka:INFO: Keeping build directory 'test.build'.
> Nuitka:INFO: Successfully created 'test.exe'.

Executing test.exe returns error:
`Assertion failed: target_file != INVALID_HANDLE_VALUE, file static_src\WindowsOnefile.c, line 373`

**Comment by kayhayen** [comment]
The report is not nearly against the latest version, this was probably fixed already.
