### ISSUE TITLE
exception with python -OO and numpy

### ISSUE THREAD

**Issue by niki-sp** [Nuitka/Nuitka#1189]
Nuitka '0.6.17rc3' on Python '3.8' with mingw
numpy 1.20.3

test code:
```
"""
python -OO numpy
"""
assert __doc__ is None, 'python -OO ' + __file__
import numpy
print(numpy.__doc__)

# nuitka-project: --standalone
# nuitka-project: --python-flag=no_warnings,no_asserts,nosite,no_docstrings
# nuitka-project-if: {OS} == "Windows":
#  nuitka-project: --mingw
# nuitka-project: --plugin-enable=anti-bloat
# nuitka-project: --plugin-enable=numpy
```
**expected output**
None
**real output**
  File "...\numpy\core\overrides.py", line 192, in decorator
TypeError: add_docstring() argument 2 must be str, not None

**Comment by kayhayen** [comment]
This is a duplicate, I don't know what is going on there. When I trace the code, it all looks as if it must be working, but it is not. Maybe one day, anti-bloat gets a change to let go of this attempts to care for docstrings of functions copied around.

**Comment by niki-sp** [comment]
the problem can be fixed with **anti-bloat.yaml**
```
numpy.core.overrides:
  description:
    "fix numpy for python -OO"
  replacements:
    "add_docstring(implementation, dispatcher.__doc__)" : "'''add_docstring(implementation, dispatcher.__doc__ or '')'''"
```

**Comment by kayhayen** [comment]
This is now part of the current pre-release. The anti-bloat plugin will become default one day, then this will be automatically solved.

**Comment by kayhayen** [comment]
Accidental close.

**Comment by kayhayen** [comment]
This is part of the 0.6.17 release.
