### ISSUE TITLE
LGPL compliance

### ISSUE THREAD

**Issue by math-artist** [Nuitka/Nuitka#1191]
Doing a search, just to find out that I am the only person that raised that concern publicly 2 years ago, but is there a way to ensure LGPL compliance with Nuitka (I am of course referring to creating standalones with the great hinted-compilation utility)?

The problem is not the cost of commercial licenses (best example is Qt), but there are cases where libraries are under LGPL without a commercial alternative, and to be compliant, some code need to be excluded from the executable.

I found an interesting article explaining their workflow to solve this with pyinstaller: https://velovix.github.io/post/lgpl-gpl-license-compliance-with-pyinstaller/

It seems that Nuitka is already keeping the C/C++ dependencies outside the executable, but what if Python code is under LGPL? How to ensure LGPL compliance? 

My current problem is that I am using OpenCascade for reading CAD files and nothing else. It is the only library available in Python that does it well. That's 1 % of my application, but it still needs to be done. I can't figure out how to use pythonocc-core under LGPL with Nuitka, because it will inevitably end up in the .exe.

Any hint on how to do it?

**Comment by kamgha** [comment]
> because it will inevitably end up in the .exe.

You can use `--nofollow-import-to=` to exclude certain modules. You would then ship the not-included Python module alongside your executable (in source form `.py` or byte compiled `.pyc`), or you can compile it with `--module` separately and ship that resulting binary `.pyd`/`.dll`/`.so` with your main executable.

**Comment by kayhayen** [comment]
Nuitka origanisation has no lawyers. I am not a lawyer. Please ask the FSF these questions, as they are the authors of the license. 

I believe the LGPL is intended to allow inclusion of unchanged code into a binary for as long as the LGPL source of that code is made available. But obviously I might be wrong, since you guessed it, I am not a lawyer.

That said @kamgha answered it pretty much perfectly. You can have them entirely separate as an extension module of its own, which of course can then be swapped out.

Yours,
Kay

**Comment by math-artist** [comment]
@kayhayen This was not a legal question, but a technical one. LGPL compliance requires the user to have the ability to switch to a different version of the library. This means that not changing the code and providing the sources is one thing, but the user needs a method to swap the library version with another one. Hence, it requires either to have the LGPL libraries external to the executable, or provide a procedure and everything required to compile with another version (which is not possible with closed-source projects.)

I will try what @kamgha suggested. That seems pretty straightforward.
