### ISSUE TITLE
Jinja2 is missing MarkupSafe

### ISSUE THREAD

**Issue by kamgha** [Nuitka/Nuitka#1192]
Nuitka 0.6.17rc3 (from source)
CPython 3.7.6 on Windows 7 SP1 64bit

Updating from Nuitka 0.6.15rc5, compilation worked before.

The CPython installation is "fresh" from their website, no additional modules nor pip have been installed.

Running Nuitka with `..\path\to\python -m nuitka --plugin-enable=pylint-warnings --standalone --prefer-source-code --follow-stdlib --lto --python-flag=no_site,no_randomization,no_warnings,no_asserts,no_docstrings --disable-dll-dependency-cache --windows-disable-console ..\path\to\myproject.py`

A simple "Hello World"-script does work. A rather complex project does exhibit the following error during compilation:

```
Nuitka:INFO: Generating source code for C backend compiler.
FATAL: Error, expected inline copy of 'jinja2' is in 'D:\\p3d\\Nuitka\\nuitka\\b
uild\\inline_copy\\jinja2' there, error was: ModuleNotFoundError("No module name
d 'markupsafe'").
```

Adding `markupsafe` to `Nuitka\nuitka\build\inline_copy\jinja2` leads to the following error 

```
Nuitka:INFO: Generating source code for C backend compiler.
Traceback (most recent call last):
  File "D:\p3d\Nuitka\nuitka\__main__.py", line 187, in <module>
    main()
  File "D:\p3d\Nuitka\nuitka\__main__.py", line 173, in main
    MainControl.main()
  File "D:\p3d\Nuitka\nuitka\MainControl.py", line 718, in main
    result, options = compileTree()
  File "D:\p3d\Nuitka\nuitka\MainControl.py", line 594, in compileTree
    makeSourceDirectory()
  File "D:\p3d\Nuitka\nuitka\MainControl.py", line 381, in makeSourceDirectory
    ) = CodeGeneration.generateHelpersCode()
  File "D:\p3d\Nuitka\nuitka\codegen\CodeGeneration.py", line 480, in generateHe
lpersCode
    calls_body_code = getCallsCode()
  File "D:\p3d\Nuitka\nuitka\codegen\CallCodes.py", line 669, in getCallsCode
    result.append(getQuickCallCode(args_count=quick_call_used))
  File "D:\p3d\Nuitka\nuitka\codegen\CallCodes.py", line 651, in getQuickCallCod
e
    template = getTemplate("nuitka.codegen", "CodeTemplateCallsPositional.j2")
  File "D:\p3d\Nuitka\nuitka\utils\Jinja2.py", line 69, in getTemplate
    return getEnvironment(module_name).get_template(template_name)
  File "D:\p3d\Nuitka\nuitka\utils\Jinja2.py", line 47, in getEnvironment
    loader=jinja2.PackageLoader(module_name, "templates"),
  File "D:\p3d\Nuitka\nuitka\build\inline_copy\jinja2\jinja2\loaders.py", line 2
22, in __init__
    from pkg_resources import DefaultProvider, ResourceManager, \
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by kayhayen** [comment]
From what I know, markupsafe has a C extension, and cannot be included as an inline copy, am I wrong about that? But seeing that pkg_resources would also have to be included, that's not tenable.

So that's expected to happen, you need to install the requirements now, at least Jinja2. Nuitka has not needed that for ages, but it's over now. Nuitka has been using static code generation with Jinja2 only, but now it's switching to it for normal code generation too, right now it's adding call variants that the static code misses only, but I expect more templates to switch from Python string formatting to Jinja2 templates.

I have yet to merge them with setup.py, since versioning and OS checks do not work on old pip, that's something that will need a bit of care. For Nuitka, maybe a split between the Python that runs Nuitka and the Python it looks at, is coming, in which case, we are removing these needs, and e.g. a 3.9 will run Nuitka while it's compiling 2.7 code, but that's in the distant future. Then of course, Nuitka wouldn't have to live inside the target namespace anymore and not import from there. But I am not seeing this happen this year.

**Comment by kayhayen** [comment]
That said, I think I will want to work on the `setup.py` and some form of handling of the Jinja2 import error, that is more expressive, or suggestive of what to do.

**Comment by kamgha** [comment]
> From what I know, markupsafe has a C extension, and cannot be included as an inline copy, am I wrong about that?

That C module is optional for acceleration. In case of it not being present, it will fall back to _native.py (see tail of markupsafe/__init__.py).

So I installed pip via `python -m ensurepip` and Jinja2 via `python -m pip install Jinja2` (following message is from Jinja2==2.11.3) and I get this error:

```
Nuitka:INFO: Generating source code for C backend compiler.
Traceback (most recent call last):
  File "D:\p3d\Nuitka\nuitka\__main__.py", line 187, in <module>
    main()
  File "D:\p3d\Nuitka\nuitka\__main__.py", line 173, in main
    MainControl.main()
  File "D:\p3d\Nuitka\nuitka\MainControl.py", line 718, in main
    result, options = compileTree()
  File "D:\p3d\Nuitka\nuitka\MainControl.py", line 594, in compileTree
    makeSourceDirectory()
  File "D:\p3d\Nuitka\nuitka\MainControl.py", line 381, in makeSourceDirectory
    ) = CodeGeneration.generateHelpersCode()
  File "D:\p3d\Nuitka\nuitka\codegen\CodeGeneration.py", line 480, in generateHe
lpersCode
    calls_body_code = getCallsCode()
  File "D:\p3d\Nuitka\nuitka\codegen\CallCodes.py", line 669, in getCallsCode
    result.append(getQuickCallCode(args_count=quick_call_used))
  File "D:\p3d\Nuitka\nuitka\codegen\CallCodes.py", line 651, in getQuickCallCod
e
    template = getTemplate("nuitka.codegen", "CodeTemplateCallsPositional.j2")
  File "D:\p3d\Nuitka\nuitka\utils\Jinja2.py", line 69, in getTemplate
    return getEnvironment(module_name).get_template(template_name)
  File "D:\p3d\Nuitka\nuitka\build\inline_copy\jinja2\jinja2\environment.py", li
ne 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "D:\p3d\Nuitka\nuitka\build\inline_copy\jinja2\jinja2\environment.py", li
ne 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "D:\p3d\Nuitka\nuitka\build\inline_copy\jinja2\jinja2\loaders.py", line 1
13, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "D:\p3d\Nuitka\nuitka\build\inline_copy\jinja2\jinja2\loaders.py", line 2
35, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: CodeTemplateCallsPositional.j2
```

**Comment by kayhayen** [comment]
How did you install Nuitka though?

**Comment by kamgha** [comment]
> How did you install Nuitka though?

1. Downloaded Nuitka 0.6.17rc3.tar.bz2 from https://nuitka.net/pages/download.html
2. Extracted it
3. cd into the directory
4. Invoking Python via relative path, e. g. `..\python\python.exe -m nuitka --standalone ..\project\myproject.py`

I did not touch setup.py, this has worked before up to this point so far.

**Comment by kayhayen** [comment]
and it should, as these are sdist created by setup.py and, I think it might be not listing them as datafiles in setup.py, once there is a new pre-release I will let you know, I am tagging this as factory to not forget, but there are no archives for it.

**Comment by kamgha** [comment]
> the new pre-release ought to be good now. Let me know if that holds true

Yes, thanks, it works now.

> you need to install the requirements now, at least Jinja2. Nuitka has not needed that for ages, but it's over now.

Isn't Jinja2, except some of its dependencies, shipped with Nuitka?

So, to avoid `pip`, I've put the `markupsafe`-module from [MarkupSafe](https://pypi.org/project/MarkupSafe/) into `Nuitka/nuitka/build/inline_copy/jinja2/` and the `pkg_resources`-module from [setuptools](https://pypi.org/project/setuptools/) into `Nuitka/`, so that Python can find it. As written earlier, the C-module  of MarkupSafe is not needed as of now, since it'll fall back to its native implementation.

Would it make sense to add these two modules to `inline_copy` as well, or what is the point of that directory since it already includes some dependencies?

**Comment by kayhayen** [comment]
How big is pkg_resources anyway? I am starting to change my mind. But the lack of extension module, could it mean that it is really slow in that case?

**Comment by kayhayen** [comment]
Maybe can you make a PR with this, I would consider merging it. I have had problems with other day, with the yaml version requireed by Nuitka conflicting with one that a user package wants. And I think it's been a good thing that when Nuitka is asking to be installed into an environment, it will not possibly conflict.

**Comment by kayhayen** [comment]
I have added markupsafe 1.1.1 as an inline copy, and it seemed to work without pkg_resources, and now I am checking if all the Python versions will be happy with it, I guess, I am reverting my decision here, and will make it still possible to use nuitka without installing dependencies at all.

**Comment by kayhayen** [comment]
I have pushed markupsafe to factory, so this is something we will be able to forget once it's part of a pre-release. Naturally, an installed markupsafe will be faster, but so far it's barely using Jinja2 for code generation, so it doesn't really matter all that much.

**Comment by kayhayen** [comment]
I have created virtualenv on all Python versions, and pkg_resources was always there. So it's kind of correct to assume that I guess, but your report suggested it's missing. Can you detail more clearly what your Python setup is there.

**Comment by kamgha** [comment]
> but your report suggested it's missing. Can you detail more clearly what your Python setup is there.

This is my configuration, pip is an optional component and when not selected, the installation will not include its dependency `setuptools` which includes `pkg_resources`:

![py376woPip](https://user-images.githubusercontent.com/7195621/142743258-cdf047c1-98c1-4562-9755-08dacac24419.png)

**Comment by kayhayen** [comment]
Ah, OK, that's explains it, but is uncommon, isn't it, Python cannot do anything really unless you install something from pip. But I guess, it's working now.

**Comment by kayhayen** [comment]
I have just encountered the missing pkg_resources myself, in a fresh MSYS2 install, and I am also seeing it happen when I do reflected test again for some versions, so I am adding pkg_resources to the package now, hoping to resolve this.

**Comment by kayhayen** [comment]
Part of the 0.6.19 release I just made.
