### ISSUE TITLE
Add multiprocessing process spawn mode on Linux, add multiprocessing.manager support on macOS

### ISSUE THREAD

**Issue by dgander** [Nuitka/Nuitka#1194]
- Nuitka Version: 0.6.16.4 and "Develop" as of 27/08/21. 
- OS: Ubuntu 20.04 64 Bit
- Python: 3.9.4
- Installation:  via pip in a virtualenv, from python compiled from source 

I'm trying to compile an application which makes use of multiprocessing in spawn mode.
A minimal example such as the following doesn't work ("Hello" is never printed):

```
import multiprocessing as mp

def f(name):
    print("hello", name)

if __name__ == "__main__":
    ctx = mp.get_context("spawn")
    p = ctx.Process(target=f, args=("test",))
    p.start()
    p.join()
```

Built with:
```
python3 -m nuitka\
  --quiet\
  --onefile\
  --assume-yes-for-downloads\
  --output-dir=output\
  src/test.py
```

The documentation from the multiprocessing module, implies that this may not work with Nuitka though:

> https://docs.python.org/3/library/multiprocessing.html
> Warning The 'spawn' and 'forkserver' start methods cannot currently be used with “frozen” executables (i.e., binaries produced by packages like PyInstaller and cx_Freeze) on Unix.
> The 'fork' start method does work.

It would be great even to get just a confirmation that this isn't supposed to work rather than wondering if it's a bug.

Purely for my own curiousity, any pointers towards what is stopping it from working or making this difficult to support would be interesting too!

**Comment by kayhayen** [comment]
The multiprocessing plugin makes it work on Windows. It's hard coding things in 2 places for win32, you would have to lift that.

But the question is why, this is an inferior mode of operation, is it not? Using threads on Linux will be much faster.

Yours,
Kay

**Comment by dgander** [comment]
Thanks - that's helpful just knowing that.

Having two parts of the program being more isolated compared to using forking or using threading is beneficial for this particular application.

**Comment by kayhayen** [comment]
yup, so it's doable, seems this might apply for you: https://nuitka.net/pages/commercial.html I guess I can make it work in one day, get in touch via the form if you are interested.

**Comment by kayhayen** [comment]
I have come across issues with `multiprocessing.manager` on macOS, where it seems that this is also used, therefore I have undertaken the effort to implement this, and it's currently on factory. The multiprocessing plugin is no longer limited to Windows, but still has to be activating with `--enable-plugin=multiprocessing` to add the support. Linux works without it normally, but the plugin makes the example code work.

Code is current on factory, https://nuitka.net/doc/factory.html and needs to be tested before it can be included in a release, but the matter is urgent as it affects commercial macOS users.

**Comment by kayhayen** [comment]
Yes, this was also what was missing for macOS to work. It seems it uses shared memory for `multiprocessing.manager` on Linux, but not on macOS, making it need the resource tracker process, which is also what keeps back spawn mode.

**Comment by kayhayen** [comment]
This is part of the 0.6.18 release.
