### ISSUE TITLE
I tried to use Nuitka with mutilprocessing application, but when i'm done packing, I clicked exe and there was a bug

### ISSUE THREAD

**Issue by Mr-Clutch-China** [Nuitka/Nuitka#1200]
I apologize for this intrusion, but this problem bother me for along time. In this case, I've already packed, but clicking on exe didn't worked, then many of the same processes reappear (as I can see in task Manager), they almost overwhelmed my memory. I would like to ask, what are the reasons for this situation, and of course in pyCharm , it worked well. Thanks!!!

**Comment by kayhayen** [comment]
No issue template filled out.
