### ISSUE TITLE
PyCode_New and PyCode_NewWithPosOnlyArgs are going away in CPython 3.11

### ISSUE THREAD

**Issue by da-woods** [Nuitka/Nuitka#1203]
See https://bugs.python.org/issue45122

Posting here as advance notice because you look to use this API to generate tracebacks (similar to Cython and MyPyc).

The alternative options at the moment appear to be the internal `_PyCode_New` or `PyCode_NewEmpty` followed by `code.replace()`

**Comment by vstinner** [comment]
> The alternative options at the moment appear to be the internal _PyCode_New 

Hum, it's not a good idea to rely on the private C API.

PyCode_NewEmpty() is public ;-)

**Comment by kayhayen** [comment]
Nuitka is not very shy with private CPython APIs, that I can tell you. But so far, 3.10 is not yet fully supported, so this is in the far future. Thanks for pointing it out, having a myriad of things to provide is ugly indeed.

**Comment by kayhayen** [comment]
I don't think I noticed this, unfortunately to me this was just noise. Rather than remove it, Python 3.11 added a new argument.
