### ISSUE TITLE
PyTorch import compiles but does not execute

### ISSUE THREAD

**Issue by gkalman1** [Nuitka/Nuitka#1208]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)
0.6.16.4
Python: 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Users\gkalm\Anaconda3\python.exe
OS: Windows
Arch: x86_64

* How did you install Nuitka and Python
python install with Anaconda
(base) pip install of Nuitka for Python 3.7 downloaded from website

* The specific PyPI names and versions
torch==1.9.0
torchvision==0.10.0

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)
--- simple.py ---
    print("test: at A1")
    import torch
    print("test: at A2")
    
    def talk(message):
        return "Talk " + message
    
    def main():
        print(talk("Hello World"))
    
    if __name__ == "__main__":
        main()

---
I was not able to compile a longer script that uses easyOCR. I spent about a week now trying to get it to work by adding and subtracting parts. I am now at the conclusion that it is PyTorch import that is causing an issue. So, I reduced it down to the script above where I see the same behavior. I am not very knowledgeable of nuitka (first time trying to use it). Nonetheless, it seems to me that I am following what I am supposed to be doing.

When I compile with (I tried a number of different option combinations with similar results):
python -m nuitka --standalone --plugin-enable=numpy --plugin-enable=torch --plugin-enable=pylint-warnings --plugin-enable=pyqt5 --follow-imports --mingw64 simple.py

I get no errors or warnings during compilation (which takes about an hour on my laptop). However, when I try to execute simple.exe from the command line, it will print "test: at A1", but then pause and return the command line as if it is done with the execution. There are no errors that it outputs.

When I compile without the --standalone or --onefile option (e.g., python -m nuitka --mingw64 simple.py), the compilation takes a few seconds and produces an executable that executes fully and correctly. However, I want this for a distribution to a user that does not have Python, nor knows how to install it.

I have been hoping that I was just doing something wrong that is simple and stupid (that is why I spent so long trying different things). However, I am starting to think that it may not be something that I am doing. 

Any help? Thank you.

**Comment by kayhayen** [comment]
I am sorry, but PyTorch is currently not well covered it seems. I will come to this in the future only.

**Comment by kayhayen** [comment]
Latest Torch is supposed to work with the plugin activated on 0.8.1

**Comment by beuaaa** [comment]
Hello @gkalman1,

Do you manage to compile with Nuitka your project using easyocr ?
I can't do it and I would need some feedback.

**Comment by kayhayen** [comment]
@beuaaa please open a new issue, then we can look into it
