### ISSUE TITLE
compiling with gcc from conda env

### ISSUE THREAD

**Issue by bago13** [Nuitka/Nuitka#1212]
Hello, 

First of thank you for your amazing work with nuitka, can't wait to the the next improvements !

I've had a small issue trying to compile from a conda environnement with nuita.
the name of my compiler installed with  conda is  x86_64-conda-linux-gnu-cc 

In nuitka/build/Backend.scons :

**I had to change this (line 1075) :** 
```python
# Tell compiler to create a shared library or program.
if module_mode:
    if "gcc" in the_cc_name or "g++" in the_cc_name:
        env.Append(CCFLAGS=["-shared"])
    elif clang_mode:
        pass
    elif msvc_mode:
        env.Append(CCFLAGS=["/LD"])  # Create a DLL.
    else:
        assert False, the_cc_name
```

**to that :**
```python
# Tell compiler to create a shared library or program.
if module_mode:
    if any(val in the_cc_name for val in ("gcc", "g++", "gnu-cc")):
        env.Append(CCFLAGS=["-shared"])
    elif clang_mode:
        pass
    elif msvc_mode:
        env.Append(CCFLAGS=["/LD"])  # Create a DLL.
    else:
        assert False, the_cc_name
```

By the way, running the compilation with clang (installed from conda) worked straight away.

**Comment by kayhayen** [comment]
Nuitka already has this:

```
def isGccName(cc_name):
    return "gcc" in cc_name or "g++" in cc_name or "gnu-cc" in cc_name
```

Seems this is a place it's not yet used.

**Comment by kayhayen** [comment]
I have fixed this on factory branch: https://nuitka.net/doc/factory.html

**Comment by bago13** [comment]
Great! thank you.

**Comment by kayhayen** [comment]
Does the `--libstatic-python` option work for you there? It ought to, and with `--lto=yes` it might make big difference. Not using CondaCC, but gcc will cause errors though, but for you it ought to work. Do we think that in case of Anaconda, to change the search order to gnu-cc might make it possible it's found instead?

**Comment by bago13** [comment]
First of all, I must say I know close to nothing about compilation...  
I've installed nuitka factory and tryed these options.  
I activated option `lto=yes` 
libstatic-python option doesn't exists, did you meant `--static-libpython=yes` ?  
- with `--static-libpython=yes` or  `--static-libpython=auto` I got this message : 
`FATAL: Error, static libpython is not found or not supported for this Python installation.` 
I tryed `conda install libpython` but it found no match.
- with `--static-libpython=no` it compiled without raising any error.

**Comment by kayhayen** [comment]
Ok, just wanted to know, thanks, sorry for the misspelling from top of my head. So LTO actually works in that mode, which means I can autoactivate it, but the static libpython might live in a place where it's not found. If you wanted to help you can have a look at current factory, now `lto=auto` which is the default, should be properly activated in your environment. And also, if you could look at  `_getSystemStaticLibPythonPath()` in `nuitka/utils/StaticLibraries.py` you could help make it work when that libpython is available, and you only need to tell me which code path there could work, there one some for Debian, maybe they will work with some tweaks.

**Comment by bago13** [comment]
With the latest factory here is what i got :
```shell
Nuitka-Options:INFO: Used command line options: --module Post/script_bago.py --output-dir=Post --nofollow-imports --show-scons --static-libpython=yes --lto=auto
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.17rc8' on Python '2.7' commercial None.

Nuitka-Options:WARNING: In module mode, providing --static-libpython has no effect, it's not used.
```

for the _getSystemStaticLibPythonPath issue, here is what worked for me (in StaticLibraries line 118) :
```python
    else:
        candidate = os.path.join(
            sys_prefix, "lib", "libpython" + python_abi_version + ".a",
            sys_prefix, "lib", "libpython" + python_abi_version + ".so",
        )
```
I added .so extension

**Comment by kayhayen** [comment]
Well, yes, that mode is for programs only, extension modules do not link against `libpython`. you need to find a static link library, the .so you can link against, but Nuitka does that for programs anyway, if it's not static, these are not static link libraries. Look for a file from the conda libpython package that ends with something else, most likely `.a`.

**Comment by bago13** [comment]
Ok I found something that seems to work for my conda env : 
```python
    else:
        candidate = os.path.join(
            sys_prefix, "lib", "libpython" + python_abi_version + ".a",
            sys_prefix, "lib", "python" + python_abi_version, "config", "libpython" + python_abi_version + ".a",
        )
```
After modifying this the compilation didn't raise any error with  `--static-libpython=yes` and `--lto=auto`

**Comment by bago13** [comment]
And I watched in windows the path would be the same.

**Comment by bago13** [comment]
On windows 64 the path would be just like line 90 :
`os.path.join(sys_prefix, "libs", "python" + python_abi_version.replace(".", "") + ".lib",)`

**Comment by kayhayen** [comment]
What compiler are you using with Conda on Windows there? Nuitka required gcc 8 or higher, and CondaCC was stalled at 5.x when I last checked, did they update it finally?

**Comment by bago13** [comment]
When i run nuitka from windows without any argument about the compiler, it chooses MSVC (which is outside of anaconda environnement).

**Comment by kayhayen** [comment]
Ah, now that I am thinking of it, on Windows the Python DLL has to be a DLL or else things won't work with anything from PyPI and any extension module, which is why we created https://github.com/Nuitka/Nuitka-Python which is a fully statically linked Python, but still under development.

**Comment by kayhayen** [comment]
So on Windows LTO is done with MSVC, but static libpython will only be there for Nuitka-Python.

**Comment by bago13** [comment]
Ok good to know

**Comment by kayhayen** [comment]
This is part of the 0.6.17 release.
