### ISSUE TITLE
Issue when compiling on Linux Debian 10

### ISSUE THREAD

**Issue by FeelsBadMan1** [Nuitka/Nuitka#1215]
New Version of my Issue:
* Not solved in any opend issue or on Stackoverflow.

* Developerversion did cause the same issue.

I tried both installation methods. currently im running version 0.6.16.4 installed using pip.

* Linux Debian 10

  > Version: 0.6.16.4

* i installed python using apt install python3 and installed nuitka using pip3 install nuitkar

==========================================================

Old Version of my Issue:
Hello, i compiled the pythonfile joiner.py with no issue on Windows using all options listed below. then i switched to a LinuxServer and tried running the same command suing the same options again: 
```
python3 -m nuitka --standalone --plugin-enable=multiprocessing --follow-imports --show-modules --show-scons --show-progress --onefile --show-modules --assume-yes-for-downloads --mingw64 --include-package-data selenium --run joiner.py
```
This caused following issue: ```__main__.py: error: no such option: --mingw64```

I then thought that the --mingw64 option might nly be valid for Windows Systems so i removed that option. Compared to WIndows the compilation was kinda fast and the .bin file got created but because of the --run option it directly ran the script and the script threw a error "no module named PyAuthGG" even after i installed it the issue still happend. I wanted to include all inputed modules into the .bin file so i not need to install anything after the compilation was done. Hopefully someone here could help me by doing so.

**Comment by kayhayen** [comment]
You didn't fill out the issue template at all. And I agree, having an error from `--mingw64` is not nice, going to change that to a proper error exit.

**Comment by FeelsBadMan1** [comment]
> You didn't fill out the issue template at all. And I agree, having an error from `--mingw64` is not nice, going to change that to a proper error exit.

Okay. Well i edited my issue a bit now. Maybe this helps!

**Comment by kayhayen** [comment]
An actual minimal reproducer would be needed too.

**Comment by FeelsBadMan1** [comment]
I compiled a pythonfile (.py) on WIndows with no single issue so far. I used --mingw64 argument as this was told me to do on different Websites. At the end the command i used to compile on WIndows was following:
```
python3 -m nuitka --standalone --plugin-enable=multiprocessing --follow-imports --show-modules --show-scons --show-progress --onefile --show-modules --assume-yes-for-downloads --mingw64 --include-package-data selenium --run joiner.py
```
After running this a .exe file got created, i uploaded the file to virustotal to see if any antivirus detect it as Malware because when i used pyarmor & pyinstaller a lot antivirus detected the converted .exe even if it just where a print statement the compiled file using nukita did not show any detection.
However later i wanted to offer the executable for different operatingsystems such as linux or apple systems.
I then tried to convert it to linux debian 10 first. The result was a .deb File with a size of 8MB if i remember correctly.
After the compilation was done (This was kinda fast compared to WIndows (I think because imports where not included))
I noticed that after running the script different Python Tracebacks where raised one example is following but im sure this also would happen with other modules: ```no module named PyAuthGG```
After installing the Module it not solved the issue at all. I thought all packages would be included into the .deb file as it was on WIndows but i was wrong. A sulution for this would be great!

**Comment by kayhayen** [comment]
If you care about anti-virus, Nuitka-commercial is for you as well, it should be even better for that: https://nuitka.net/pages/commercial.html

Without a reproducer, how do you think this can be solved? If you cannot do that, then you have to wait for this to be closed by other means, or become a commercial subscriber, in which case you can make private reports potentially, if it is not too involved for me to work on.

**Comment by FeelsBadMan1** [comment]
I am a single person that want to make some pythonscripts obfuscated and Plublic without the code being able to be reverseable I dont think paying 250€ will solve my issue. Im in education (student) and my earnings are depending on what my parents earn. means i only get 50€ a month so the commercial version is also too expencive for only 1 year for my uses. However the issue im facing is what i wrote above. currently i cant include the full Traceback as im not at home  and cant reproduce by including more code that nuitka outputs and so on. If this is needed i will send it when im at home, if so please let me know.

**Comment by kayhayen** [comment]
I think I made it clear, that a reproduction needs to be possible. How you are thinking that it can be done from command line options you found on the internet is surprising to me, so yes, provide a minimal reproducer, or this will be closed as invalid as this is not actionable.

**Comment by FeelsBadMan1** [comment]
I thought the free version would obfuscate the pythoncode too after converting it to C. Everything worked fine on Windows so i thought it works fine on Linux too. However i have some friends working with me together as developers to create such tool. I might need to ask them or my parents if they want to spend some money that i then give them back or use the free version until i earned enough money. I read the link that describe what is different on the commercial version and im kinda intressted and would by it now if i just had the money... Im not a native speaker (im from Germany) and im not quite sure what exactly you mean by "reproduce"

**Comment by kayhayen** [comment]
I am sorry, I cannot help you then.

**Comment by kayhayen** [comment]
The described UI change is part of the current release 0.6.17.
