### ISSUE TITLE
Conversion of dateutil.relativedelta into a proper *.pyd file

### ISSUE THREAD

**Issue by User68325794** [Nuitka/Nuitka#1216]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)
0.6.16.4
Python: 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
Executable: C:\Program Files\Python\python.exe
OS: Windows
Arch: x86_64

* How did you install Nuitka and Python
Python: offical intallation from https://www.python.org/
Nuitka: pip

* The specific PyPI names and versions
python-dateutil==2.8.2

* The problem

I am real newby with Nuitka and a novice (less than a year of experience) with Python. I want to create a set of application.exe + module.pyd.

I have several modules, but one is causing a particular problem -- dateutil.relativedelta

In my application.py file I use:

```
import sys

sys.path.append("./DLL/") # this is where my *.pyd files are located

from dateutil.relativedelta import relativedelta
```

However, there is no such file as dateutil.relativedelta.py. There are separate dateutil.py and relativedelta.py files which I convert into dateutil.pyd and relativedelta.pyd as follows:

  python -m nuitka --module "c:\Program Files\Python\Lib\datetime.py"
  
  python -m nuitka --module "c:\Program Files\Python\Lib\site-packages\dateutil\relativedelta.py"

When I compile my application.exe (with --nofollow-imports opion) and launch it, I receve a message that dateutil.relativedelta is not present in the /DLL/ folder, which is true because I can only supply dateutil.pyd and relativedelta.pyd. When it comes to other modules, like PySimpleGUI, such problem is not present.

I have exhausted all options I could think of. Please help.

**Comment by kayhayen** [comment]
There are instructions for how to compile a package rather than a module in the user manual, try to follow them. This is not really a good question as it is. Extension modules do not contain DLLs. Should they need to be provided, you have to do it yourself, in which case a distutils project in setup.py should be created that works with Python to make a wheel, and then use `bdist_nuitka` instead.
