### ISSUE TITLE
pyqtgraph importlib ModuleNotFoundError issue 

### ISSUE THREAD

**Issue by arktrin** [Nuitka/Nuitka#1223]
... _or maybe it is just an importlib issue_ 

Trying to compile minimalistic pyqtgraph(PyQt5) application (```pyqtgraph_minimal.py```):
```python
from pyqtgraph import plot, exec

win = plot()
win.setWindowTitle('pyqtgraph example')

if __name__ == '__main__':
    exec()
```
with 
```bash
python3 -m nuitka --plugin-enable=numpy --plugin-enable=pyqt5 --onefile pyqtgraph_minimal.py
```
in clean virtualenv, having latest packages available through pip, ```pip3 list``` output:
```
Package    Version
---------- --------
Nuitka     0.6.17.1
numpy      1.21.2
pip        21.2.4
PyQt5      5.15.4
PyQt5-Qt5  5.15.2
PyQt5-sip  12.9.0
pyqtgraph  0.12.2
setuptools 58.1.0
wheel      0.37.0
```
but getting (maybe import) error after application start:
```
Traceback (most recent call last):
  File "/tmp/.mount_pyqtgrYCHjBB/pyqtgraph_minimal.py", line 7, in <module>
    from pyqtgraph import plot, exec
  File "/tmp/.mount_pyqtgrYCHjBB/pyqtgraph/__init__.py", line 205, in <module pyqtgraph>
  File "/tmp/.mount_pyqtgrYCHjBB/pyqtgraph/graphicsItems/GraphicsLayout.py", line 5, in <module pyqtgraph.graphicsItems.GraphicsLayout>
  File "/tmp/.mount_pyqtgrYCHjBB/pyqtgraph/graphicsItems/ViewBox/__init__.py", line 1, in <module pyqtgraph.graphicsItems.ViewBox>
  File "/tmp/.mount_pyqtgrYCHjBB/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 1742, in <module pyqtgraph.graphicsItems.ViewBox.ViewBox>
  File "/tmp/.mount_pyqtgrYCHjBB/pyqtgraph/graphicsItems/ViewBox/ViewBoxMenu.py", line 7, in <module pyqtgraph.graphicsItems.ViewBox.ViewBoxMenu>
  File "importlib.py", line 127, in import_module
ModuleNotFoundError: No module named 'pyqtgraph.graphicsItems.ViewBox.axisCtrlTemplate_pyqt5'
```
build log:
```
Nuitka-Options:INFO: Used command line options: --plugin-enable=numpy --plugin-enable=pyqt5 --onefile pyqtgraph_minimal.py
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.17.1' on Python '3.8' commercial None.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'tkinter' added '_tkinter'.                                       
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'numpy.core' added 'numpy.core._dtype_ctypes,numpy.core._multiarray_tests'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pkg_resources.extern' added 'pkg_resources._vendor.packaging,pkg_resources._vendor.pyparsing,pkg_resources._vendor.appdirs'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pkg_resources._vendor.packaging' added 'pkg_resources._vendor.packaging.version,pkg_resources._vendor.packaging.specifiers,pkg_resources._vendor.packaging.requirements'.                                 
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'numpy' added 'numpy.compat,numpy.lib,numpy.linalg,numpy.fft,numpy.polynomial,numpy.random,numpy.random._bounded_integers,numpy.random._common,numpy.random._generator,numpy.random._mt19937,numpy.random._pcg64,numpy.random._philox,numpy.random._sfc64,numpy.random.bit_generator,numpy.random.mtrand,numpy.ctypeslib,numpy.ma,numpy.matrixlib'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'numpy.random.mtrand' added 'numpy,numpy.random.bit_generator,numpy.typing'.                                                                                                                               
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'numpy.random.bit_generator' added 'abc,threading,numpy,numpy.typing'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'numpy.random._sfc64' added 'numpy,numpy.random.bit_generator,numpy.typing'.                                                                                                                               
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'numpy.random._philox' added 'numpy,numpy.random.bit_generator,numpy.typing'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'numpy.random._pcg64' added 'numpy.random.bit_generator,numpy.typing'.                                                                                                                                     
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'numpy.random._mt19937' added 'numpy,numpy.random.bit_generator,numpy.typing'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'numpy.random._generator' added 'numpy,numpy.typing'.             
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'numpy.random' added 'numpy.random._bounded_integers,numpy.random._common,numpy.random._generator,numpy.random._mt19937,numpy.random._pcg64,numpy.random._philox,numpy.random._sfc64,numpy.random.bit_generator,numpy.random.mtrand'.                                                                                                               
Nuitka-Plugins:INFO: pyqt5: Injecting post-module load code for module 'PyQt5.QtCore':
Nuitka-Plugins:INFO: pyqt5:     Setting Qt library path to distribution folder. We need to avoid loading target                          
Nuitka-Plugins:INFO: pyqt5:     system Qt plug-ins, which may be from another Qt version.                                                
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'PyQt5.QtTest' added 'PyQt5.sip,PyQt5.QtWidgets,PyQt5.QtCore,datetime'.
Nuitka-Plugins:INFO: pyqt5: Implicit dependencies of module 'PyQt5.QtTest' added 'PyQt5.QtCore,PyQt5.QtGui,PyQt5.QtWidgets'.             
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'PyQt5.QtSvg' added 'PyQt5.sip,PyQt5.QtWidgets,PyQt5.QtGui,PyQt5.QtCore,datetime'.                                                                                                                         
Nuitka-Plugins:INFO: pyqt5: Implicit dependencies of module 'PyQt5.QtSvg' added 'PyQt5.QtCore,PyQt5.QtGui,PyQt5.QtWidgets'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'PyQt5.QtWidgets' added 'PyQt5.sip,PyQt5.QtGui,PyQt5.QtCore,datetime'.
Nuitka-Plugins:INFO: pyqt5: Implicit dependencies of module 'PyQt5.QtWidgets' added 'PyQt5.QtGui'.                                       
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'PyQt5.QtGui' added 'PyQt5.sip,PyQt5.QtCore,datetime,PyQt5.QtWidgets'.                                                                                                                                     
Nuitka-Plugins:INFO: pyqt5: Implicit dependencies of module 'PyQt5.QtGui' added 'PyQt5.QtCore'.                                          
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'PyQt5.QtCore' added 'PyQt5.sip,datetime,PyQt5.QtWidgets'.
Nuitka-Plugins:INFO: pyqt5: Implicit dependencies of module 'PyQt5.QtCore' added 'PyQt5.sip'.                                            
Nuitka:INFO: Completed Python level compilation and optimization.                                                                        
Nuitka:INFO: Generating source code for C backend compiler.                                                                              
Nuitka:INFO: Running data composer tool for optimal constant value handling.                                                             
Nuitka:INFO: Running C level backend compilation via Scons.                                                                              
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Compiled 266 C files using ccache.                                                                                    
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 264                                                            
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 2
Nuitka-Plugins:INFO: pyqt5: Copying Qt plug-ins 'iconengines,imageformats,mediaservice,platforms,platformthemes,printsupport,xcbglintegrations' to 'pyqtgraph_minimal.dist/PyQt5/qt-plugins'.
Nuitka-Postprocessing:INFO: Creating single file from dist folder, this may take a while.
Nuitka-Postprocessing:INFO: Completed onefile creation.
Nuitka:INFO: Keeping dist folder 'pyqtgraph_minimal.dist' for inspection, no need to use it.
Nuitka:INFO: Keeping build directory 'pyqtgraph_minimal.build'.
Nuitka:INFO: Successfully created 'pyqtgraph_minimal.bin'.
```
found (maybe) similar issue related to importlib: [#1175](https://github.com/Nuitka/Nuitka/issues/1175)

**Comment by kayhayen** [comment]
The support for PyQt5 exists, but unsure how good it is. Recommendation is PySide2 of Nuitka commercial or PySide6, and there these are used e.g. for pyside6:

# nuitka-project: --plugin-enable=pyside6
# nuitka-project: --plugin-enable=numpy
# nuitka-project: --nofollow-import-to=PyQt5
# nuitka-project: --nofollow-import-to=PyQt6
# nuitka-project: --nofollow-import-to=PySide2
# nuitka-project: --enable-plugin=anti-bloat
# nuitka-project: --include-module=pyqtgraph.canvas.CanvasTemplate_pyside6
# nuitka-project: --include-module=pyqtgraph.canvas.TransformGuiTemplate_pyside6
# nuitka-project: --include-module=pyqtgraph.console.template_pyside6
# nuitka-project: --include-module=pyqtgraph.examples.exampleLoaderTemplate_pyside6
# nuitka-project: --include-module=pyqtgraph.examples.VideoTemplate_pyside6
# nuitka-project: --include-module=pyqtgraph.flowchart.FlowchartCtrlTemplate_pyside6
# nuitka-project: --include-module=pyqtgraph.flowchart.FlowchartTemplate_pyside6
# nuitka-project: --include-module=pyqtgraph.graphicsItems.ViewBox.axisCtrlTemplate_pyside6
# nuitka-project: --include-module=pyqtgraph.graphicsItems.PlotItem.plotConfigTemplate_pyside6
# nuitka-project: --include-module=pyqtgraph.GraphicsScene.exportDialogTemplate_pyside6
# nuitka-project: --include-module=pyqtgraph.imageview.ImageViewTemplate_pyside6

These dynamic imports will be resolved by the Qt plugins in the future, it's actually on my TODO list for next release as there are important users of this.

**Comment by arktrin** [comment]
> Recommendation is PySide2 of Nuitka commercial or PySide6 ...
PySide2 do not work for me either. After numerous tests  PyQt5 vs PySide2 - I've concluded that PyQt5 works better for me.   Will try PySide6. Does Nuitka support PySide6 is better than PySide2  ?

**Comment by arktrin** [comment]
I have tried PySide2 again with all those ```--include-module=pyqtgraph.xxxxxxx_pyside2``` staff. Now I've got ZeroDivisionError:
```
Traceback (most recent call last):
  File "/tmp/.mount_pyqtgrT7UEZK/pyqtgraph_min.py", line 3, in <module>
    win = plot()
  File "/tmp/.mount_pyqtgrT7UEZK/pyqtgraph/__init__.py", line 415, in plot
  File "/tmp/.mount_pyqtgrT7UEZK/pyqtgraph/widgets/PlotWidget.py", line 56, in __init__
  File "/tmp/.mount_pyqtgrT7UEZK/pyqtgraph/graphicsItems/PlotItem/PlotItem.py", line 122, in __init__
  File "/tmp/.mount_pyqtgrT7UEZK/pyqtgraph/graphicsItems/ButtonItem.py", line 19, in __init__
ZeroDivisionError: float division by zero
```

**Comment by arktrin** [comment]
Found [same ZeroDivisionError in ButtonItem.py problem](https://github.com/pyqtgraph/pyqtgraph/issues/1934) in pyqtgraph list of issues. Among of the comments you can find that this was [pyinstaller case](https://github.com/pyqtgraph/pyqtgraph/issues/1811).

**Comment by kayhayen** [comment]
Seeems there might be data files needed. Nuitka has options to include package data that should address it, but it would be nice to have a list of files to include. But the bare import didn't need the file. Are we still talking of the example giving initially? Probably a default window icon, if I read the links correctly.

**Comment by arktrin** [comment]
> Are we still talking of the example giving initially? 
Yeah, same initial minimalistic pyqtgraph example.

**Comment by arktrin** [comment]
I managed to workaround the problem by including ```s = float(width) / self.pixmap.width(); self.setScale(s)``` in the exception as it was pointed above. But this is not a pyqtgraph bug.

**Comment by kayhayen** [comment]
I believe with the data files in the right place, it would work. It should be the same if that image was deleted from the Python installation. Unfortunately some upstreams default to non-exceptions when they cannto find files, but produce objects that will e.g. have an image size of zero. That's making life harder here. That said, I will include it in my pyqtplot work that should happen for next release.

**Comment by kayhayen** [comment]
I have made changes, such that `QT_LIB.lower()` as used by the code is now replaced with the value in source code by the Qt plugins, however `importlib.import_module` will need to be optimized as well for this to have a benefit, which will be the next step, and it's useful anyway, as a lot of code is using that function too. With the change it now ought to be compile time resolvable, but it will take a bit of code from our side to emulate it also for the cases where it doesn't resolve.

**Comment by TangoBravoMike** [comment]
I encounter the same problem at runtime with a Python app using PySide6 and PyQtGraph.  Both of those packages are the latest available on PiPy.
PySide6 version 6.2.0
PyQtGraph version 0.12.2
Nuitka version 0.6.17.2

Thanks!
Rich (TangoBravoMike)
[ModuleNotFoundError.txt](https://github.com/Nuitka/Nuitka/files/7314711/ModuleNotFoundError.txt)

**Comment by kayhayen** [comment]
Some of the imports are now statically resolved at compile time, but not all. More work will be needed, but I am not sure I get to that as it will require invasive changes to how global variables are optimized in modules.

**Comment by arktrin** [comment]
I know it doesn't matter now ... but just in case.  I've tried the latest Nuitka from the factory branch and it gives me the same ZeroDivisionError as I got earlier.

**Comment by kayhayen** [comment]
@arktrin that is just a lack of certain data files. From what I recall a lack of an image gives an image of size 0, and then it's doing math with that. Adding the data files will get around this. I am focusing on having these imports done automatically, then it will be fine, but I invite you to look at this: https://github.com/Nuitka/Nuitka/blob/factory/nuitka/plugins/standard/data-files.yml

If you provide the section for the required stuff it will be great. The not found errors can be worked around with a lot of --include-module arguments. I think I listed them before in nuitka-project syntax that you just need to copy to your main script. With that it should be workable. But my focus clearly is the out of the box experience to work, and that even automatically.

**Comment by kayhayen** [comment]
And may I say, this time *without* adding them to Nuitka, but enhancing its compile time analysis to the point, where it figures the code out.

**Comment by arktrin** [comment]
Sorry to bother you. Earlier you asked for testing so I thought it might help you or someone else.
Thanks a lot for you work !

**Comment by kayhayen** [comment]
Not bothered at all. Actually I am hoping you make a PR with a change of that file once it hits develop, will you? :)

**Comment by arktrin** [comment]
I've tried to figure out how Nuitka works but it is kind of a whole unknown field for me. But I'm glad you think I can do something useful for the project :)

**Comment by arktrin** [comment]
So, in order to make it work someone should translate PyInstaller's hook:
```
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

....
	     datas = collect_data_files("pyqtgraph",
                           includes=["**/*.ui", "**/*.png", "**/*.svg"]),
             hiddenimports = collect_submodules(
                       "pyqtgraph", filter=lambda name: "Template" in name),

...
```
into Nuitka's data-files.yml ?

**Comment by kayhayen** [comment]
The last part, Nuitka will not need and therefore be automatically better as it only picks up used stuff. The first part yes, that would be needed, although I would appreciate it to be minimal. Alternatively you can use --include-package-data=pyqtgraph which just scans for non code stuff, and does the same. I don't know how well it works in the case though.

I try to include only a minimal subset of files by default, not just everything.

Yours,
Kay

**Comment by kayhayen** [comment]
Current Nuitka develop needs no import help anymore, so that is fantastic news.

**Comment by arktrin** [comment]
> Current Nuitka develop needs no import help anymore

Does it mean I don't need all those _--include-module_ anymore ?
```
# nuitka-project: --include-module=pyqtgraph.canvas.CanvasTemplate_pyside6
# nuitka-project: --include-module=pyqtgraph.canvas.TransformGuiTemplate_pyside6
...
```

**Comment by kayhayen** [comment]
Yes, that is what it is about. Nuitka now resolves the code that computes this at compile time and only includes them if they are necessary. And switching bindings is of course easy then too.

**Comment by kayhayen** [comment]
This is part of the 0.6.18 release.

**Comment by arktrin** [comment]
But I'm still getting ZeroDivisionError with my pyqtgraph_minimal.py using `python3 -m nuitka --plugin-enable=numpy --plugin-enable=pyside6 --nofollow-import-to=PyQt5 --nofollow-import-to=PyQt6 --nofollow-import-to=PySide2 --enable-plugin=anti-bloat --onefile pyqtgraph_minimal.py` to compile it.

**Comment by kayhayen** [comment]
The datafiles are to be included manually. That is possible with standard options.

**Comment by arktrin** [comment]
Oh yeah, forgot about `--include-package-data=pyqtgraph`, my bad. 

Huge thanks for all the work you are doing !!
