### ISSUE TITLE
Support other freezers hooks or coordonate with them?

### ISSUE THREAD

**Issue by gdementen** [Nuitka/Nuitka#1228]
All Python "freezers" (namely py2exe, cx_Freeze, PyInstaller and Nuikta) need to handle the same problem: manually specify implicit dependencies for some packages, and they all provide some "hooks" to deal with that. 

Following the issue tracker or changelog of several of them I see that a significant deal of issues on those projects concern those hooks maintenance. Wouldn't it make sense to either piggyback on other packages hooks or standardize on some common hook format to avoid duplication of work?

**Comment by kayhayen** [comment]
My way forward is to make more things yaml config based, when it comes to implicit dependencies and data files. I was at one point open to supporting pyinstaller hooks, but the proposal was never implemented and never will I assume. My way forward is to make anti-bloat as cool shit as possible, while also allowing users and upstreams to contribute to it with very little learning curve. So far it's been a success, anti-bloat works apparently like that. And generally, if I can look at how it*s done by the others, that*s like 98% of the work done anyway.
