### ISSUE TITLE
Nuitka Executable Compiled with --standalone --onefile does not work in windows 7 ?

### ISSUE THREAD

**Issue by PremKumarMishra** [Nuitka/Nuitka#1229]
Hi , I like Nutika Compiler Because its better than Other Compilers .
But I am facing issues with standalone onefile executables in  windows 7 ultimate service pack 1.
**Note : I compiled program in a win 10 pc**
When i run the program it crashes immediately without any error .I also didnt disable console.
my program basically just prints hello world
Thanks in Advance

**Comment by kayhayen** [comment]
You need to compile on Windows 7, then it will run on Windows 10 as well, but not the other way around.
