### ISSUE TITLE
Compile crash with "from sys import version" 

### ISSUE THREAD

**Issue by Maimunaki** [Nuitka/Nuitka#1230]
Hi. I receive an error when I run the program. 

python -m nuitka --mingw64 --onefile --windows-company-name=RunDown --include-package=discum --include-package=colorama --include-package=requests --include-package=webbrowser --include-package=os --include-package=ctypes --include-package=re --include-package=random --include-package=string --include-package=json --include-package=subprocess --include-package=datetime --include-package=hashlib --include-package=getpass --include-package=stdiomask --include-package=selenium --include-package=urllib --windows-product-version=1.0 --plugin-enable=tk-inter RunDown1.4.py

Or

python -m nuitka --mingw64 --onefile --windows-company-name=RunDown --include-package=discum --windows-product-version=1.0 --plugin-enable=tk-inter RunDown1.4.py    

I get the error

    assert hasattr(self.module, self.import_name), self
AttributeError: 'ExpressionImportModuleHard' object has no attribute 'import_name'

Here are my imports 

import colorama
import requests, webbrowser, time, os, discum, ctypes, re, random, string, json, subprocess, datetime, hashlib, getpass, stdiomask
from requests import exceptions
from datetime import datetime
from requests.api import post
from time import daylight, sleep
from colorama import Fore, Style, Back
from json import loads, dumps
from discord_webhook import DiscordWebhook
from selenium import webdriver
import selenium

try:
    os.system("pip install urllib3==1.25.8")
except:
    pass

Could someone please help me?

**Comment by kayhayen** [comment]
Thanks for the report, there is a fix for this on factory, coming to a hotfix later: https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
Part of 0.6.17.2 hotfix release.
