### ISSUE TITLE
Nuitka Commerical renewal

### ISSUE THREAD

**Issue by FeelsBadMan1** [Nuitka/Nuitka#1231]
Hello, Im intressted in the commercial version and i did read the description if this Version to be able to understand, what the differences are. I still have a unaswerd Question where i try to find a Answer for before completing the Payment. Maybe more Questions appear in the feature but for now this is my only Question:

On the Website under the Pricing Headline you wrote and i quote "Currently 250 EUR (or 300 USD), valid for one year, renewal same price."
Now im not quite sure, if that means it automatically renewal or if Customers need to manually pay the full price after 1 year again.
I would love to hear back soon,

- FeelsBadMan

**Comment by kayhayen** [comment]
Renewal is not automatic, I will make offers after one year, likely at a discount, to avoid people not renewing just because they don't need it yet. You can continue using the old version indefinitely, but new Nuitka releases will probably at some point stop working with them.

Yours,
Kay
