### ISSUE TITLE
ImportError for modules using swig bindings

### ISSUE THREAD

**Issue by kongsgard** [Nuitka/Nuitka#1232]
This is a follow-up issue to #1226. With the latest factory release I'm able to successfully compile ifcopenshell, but I'm still not able to run the resulting executable.

* Nuitka version, full Python version and Platform
 
```
0.6.18rc2
Commercial: None
Python: 3.8.12 | packaged by conda-forge | (default, Sep 29 2021, 19:20:16) [MSC v.1916 64 bit (AMD64)]
Executable: C:\tools\miniconda3\envs\processor\python.exe
OS: Windows
Arch: x86_64
```

* How did you install Nuitka and Python

  `pip install -U "https://github.com/Nuitka/Nuitka/archive/factory.zip"`

* The specific PyPI names and versions

  Only ifcopenshell-python is relevant:
  `conda install -c conda-forge ifcopenshell==v0.6.0`

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

  The error occurs when trying to run a compiled script with the following import statement:
`import ifcopenshell`

* Provide in your issue the Nuitka options used

```
--onefile --remove-output --prefer-source-code --assume-yes-for-downloads --enable-plugin=anti-bloat --noinclude-setuptools-mode=nofollow --noinclude-pytest-mode=nofollow --plugin-enable=pylint-warnings --plugin-enable=pkg-resources --plugin-enable=numpy --windows-onefile-tempdir
```

* Note if this is a regression

  This does not seem to work in any versions of Nuitka.
  
* Relevant part of the command line output:

```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\ONCD6B~1\ifcopenshell\ifcopenshell_wrapper.py", line 14, in swig_import_helper
  File "importlib.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ifcopenshell._ifcopenshell_wrapper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\ONCD6B~1\ifcopenshell\__init__.py", line 43, in <module ifcopenshell>
  File "C:\Users\user\AppData\Local\Temp\ONCD6B~1\ifcopenshell\ifcopenshell_wrapper.py", line 17, in <module ifcopenshell.ifcopenshell_wrapper>
  File "C:\Users\user\AppData\Local\Temp\ONCD6B~1\ifcopenshell\ifcopenshell_wrapper.py", line 16, in swig_import_helper
  File "importlib.py", line 127, in import_module
ModuleNotFoundError: No module named '_ifcopenshell_wrapper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\ONCD6B~1\ifcopenshell\__init__.py", line 51, in <module ifcopenshell>
ImportError: IfcOpenShell not built for 'windows\64bit\python3.8'
```

  I also tested with Python 3.9.7, but the same error message is displayed.

**Comment by kayhayen** [comment]
This is a very typical pattern of swig. If I am not mistaken, you can work around it with `--include-module=_ifcopenshell_wrapper` and there is a need to add this as an implicit dependency inside of Nuitka, then this will work out of the box. I will try and see if this pattern "x.py:swig_import_helper" -> "_x" can be done by Nuitka through source analysis or some sorts. That way we get to do this not per every swig module, which I think is what is happening now.

**Comment by kayhayen** [comment]
Ah, there is this code in there: 

```
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_ifcopenshell_wrapper')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_ifcopenshell_wrapper')
    _ifcopenshell_wrapper = swig_import_helper()
    del swig_import_helper
```

Let's ignore 2.6 here, which actually would need some help, or some form of source code based lookup. But the first `importlib.import_module` call is what should be statically optimized. This is missing a few operations on strings, that are not yet optimized, unless I am mistaken, but with `mname` being compile time optimized, it would be working. For #1223 the `importlib.import_module` optimization is something to add anyway, and this just needs string attributes to be optimized, which is on the roadmap for next release, but with dictionary `items`, `iteritems`, but that will be done so general, that optimization of these on constants should all happen at compile time.

So, no special pleading needed there. For 2.6, a more file based approach will be needed, but that's going to be delayed due to lack of importance right now, but swig automatically working for those as well will be nice as well, and also only takes a bit of work, and anti-bloat might be used there. Naturally static optimization working its way will be preferred, but there we have a pattern like this:

```
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ifcopenshell_wrapper', [dirname(__file__)])
        except ImportError:
            import _ifcopenshell_wrapper
            return _ifcopenshell_wrapper
        try:
            _mod = imp.load_module('_ifcopenshell_wrapper', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _ifcopenshell_wrapper = swig_import_helper()
    del swig_import_helper
```

That's much harder to statically optimize with good feelings, but could be handled by a some sort of search and replace with a pattern, such that it becomes an `__import__` call that is also statically optimizable.

**Comment by kayhayen** [comment]
So, now  that module variables are properly traced, and first cases of fully compile time detected paths are done, I am turning to this, and it seem to me, we only need 2 methods of strings to be compile time computed. namely `rpartition` and `join`. So this is what will be done next in this domain, now that all dict methods have been implemented. This should make the solution of this issue automatic as well.

**Comment by kayhayen** [comment]
I was definitely looking at this with a PyPI package, but now I forgot which one to use, should be `ifcopenshell-hypeifc` I guess, because that has the version you reported from Anaconda.

**Comment by kayhayen** [comment]
The `rpartition` and `join` are implemented, but I think I overlooked the `strip` usage, so I will have to add that first before being able to hope for sucess here.

**Comment by kayhayen** [comment]
This works after some generic optimization enhancements, Nuitka should now handle this and similar SWIG bindings for 2.7 or higher: https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
This is now on develop and will be part of 0.6.18 which will be released soon.

**Comment by kayhayen** [comment]
This is part of the 0.6.18 release.
