### ISSUE TITLE
Could not find pytransform.dll

### ISSUE THREAD

**Issue by FeelsBadMan1** [Nuitka/Nuitka#1234]
Python Verison: 3.9.6
Nuitka Version: Latest Release
Imported Modules Version: Latest Versions on all modules (upgraded & updated before compiling)
Modules in use:
```
selenium
sys
os
requests
colorama
numpy
concurrent.features
& a few more i cant look up now
```

Syntax i used to compile the code with all arguments below:
```
nuitka --warn-unusual-code --follow-imports --show-progress --assume-yes-for-downloads --standalone --plugin-enable=multiprocessing --show-modules --show-progress --mingw64 --onefile --include-package-data selenium --nofollow-import-to=importlib --no-pyi-file --experimental=use_pefile --experimental=use_pefile_recurse joiner.py
```

The final .exe file is suprisingly kinda big (75MB) and when users try to run the file they get issues similar to this:
```
Could not find "C:\Users\ADMINI~1\AppData\Local\Temp\ON4C87~1\pytransform\platforms\windows\x86_64\_pytransform.dll"
```
I looked for the dictonary but not found it so i created it, added the pytransform folder but its still the same issue....
Hopefully someone here is able to help me there

Reproduce:
Python script im using (not edited):
```
print("this is to reproduce the behavor with nuitka by FeelBadMan")

# command that convert the code to C and then convert it to a .exe file:
# nuitka --warn-unusual-code --follow-imports --show-progress --assume-yes-for-downloads --standalone --plugin-enable=multiprocessing --show-modules --show-progress --mingw64 --onefile --include-package-data selenium --nofollow-import-to=importlib --no-pyi-file --experimental=use_pefile --experimental=use_pefile_recurse reproduce.py
```
After its convertd using nuitka it works fine but because i dont own the commercial version now i tried to teporarly obfuscate it using pyarmor and then compile it using nuitka. at the point hwre i have the required money i defently buy the commerical version but after using following command to obfuscate the script:
```
pyarmor obfuscate --no-cross-protection --restrict 0 reproduce.py
```
The compiling it using nuitka this issue happens:
```
Could not find "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~2\pytransform\platforms\windows\x86_64\_pytransform.dll"
```
Running the obfuscated .py file without compiled using nuitka works fine. on obfuscating it using pyarmor the folder pytransform with the files __init__.py and _pytransform.dll got created within the same dictonary.

I understand it when you dont want to provide support with pyarmor but this would be nice as i want to repease my tool soon and already have some users that are intressted in buying. after i made some sales, earned enough money from it i will spend this earned money on nuitka commercial. Using pyarmor is jus a temp solution at the moment.

**Comment by kayhayen** [comment]
Without a minimal reproducer, this kind of issue makes no sense.

**Comment by FeelsBadMan1** [comment]
> Without a minimal reproducer, this kind of issue makes no sense.

oh okay. well i now reproduced it. hopefully that helps with finding a solution.

**Comment by kayhayen** [comment]
A minimal reproducer is code that I can compile and see the issue for myself.

**Comment by FeelsBadMan1** [comment]
> A minimal reproducer is code that I can compile and see the issue for myself.

Oh okay. I add this when i am at home.
