### ISSUE TITLE
--onefile-windows-splash-screen-image, fatal error: OnefileSplashScreen.cpp: No such file or directory.

### ISSUE THREAD

**Issue by ozippo** [Nuitka/Nuitka#1236]
--onefile-windows-splash-screen-image, has something wrong. when I use this option, nuikta will show me fatal error: OnefileSplashScreen.cpp: No such file or directory.

just test code:

def test():
    print("test------")
    

if __name__ == "__main__":
    print("Delaying startup by 10s...")
    # Use this code to signal the splash screen removal.
    if "NUITKA_ONEFILE_PARENT" in os.environ:
        splash_filename = os.path.join(
            tempfile.gettempdir(),
            "onefile_%d_splash_feedback.tmp" % int(os.environ["NUITKA_ONEFILE_PARENT"]),
        )

        if os.path.exists(splash_filename):
            os.unlink(splash_filename)

    print("Done... splash should be gone.")
    test()

* Nuitka version:*  full Python version and Platform (Windows, OSX, Linux ...)
>nuitka --version
0.6.17.2
Commercial: None
Python: 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
Executable: C:\Program Files\Python39\python.exe
OS: Windows
Arch: x86_64

 

* How did you install Nuitka and Python
  Install Nuitka use pip,  not in a virtualenv ,
  

* The specific PyPI names and versions
  > python -m pip freeze
altgraph==0.17
astroid==2.5.2
autopep8==1.5.7
beautifulsoup4==4.9.3
bs4==0.0.1
certifi==2020.12.5
chardet==4.0.0
click==7.1.2
colorama==0.4.4
docxtpl==0.11.4
et-xmlfile==1.0.1
future==0.18.2
idna==2.10
isort==5.8.0
Jinja2==2.11.3
lazy-object-proxy==1.6.0
lxml==4.6.3
MarkupSafe==1.1.1
mccabe==0.6.1
Nuitka==0.6.17.2
openpyxl==3.0.7
pefile==2019.4.18
pycodestyle==2.7.0
pyinstall==0.1.4
pyinstaller==4.3
pyinstaller-hooks-contrib==2021.1
pylint==2.7.4
PyQt5==5.15.4
pyqt5-plugins==5.15.4.2.2
PyQt5-Qt5==5.15.2
PyQt5-sip==12.9.0
pyqt5-tools==5.15.4.3.2
python-docx==0.8.10
python-dotenv==0.19.0
pywin32==300
pywin32-ctypes==0.2.0
qt5-applications==5.15.2.2.2
qt5-tools==5.15.2.1.2
requests==2.25.1
rope==0.19.0
six==1.15.0
soupsieve==2.2.1
toml==0.10.2
urllib3==1.26.4
WMI==1.5.1
wrapt==1.12.1
xlrd==2.0.1
xlwt==1.3.0
zstandard==0.15.2

* Many times when you get an error from Nuitka, your setup may be special

  Then even a `print("hello world")` program will not work, please try that and report
  that instead.

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

  That demonstrates the issue i.e a small piece of code which reproduces
  the issue and can be run with out any other (or as few as possible)
  external dependencies. Issues without this may get rejected without much
  consideration.

* Provide in your issue the Nuitka options used
nuitka  --mingw64 ^
        --onefile ^
        --onefile-windows-splash-screen-image=zs.png ^
        --output-dir=Nuitka ^
        splash.py

**Comment by ratbo99** [comment]
i have the same issue. a splash.png is in the directory of the python script, but when i try to convert it with nuitka i got the same error...

static_src\OnefileBootstrap.c:607:10: fatal error: OnefileSplashScreen.cpp: No such file or directory
  607 | #include "OnefileSplashScreen.cpp"

can anybody help? did i something wrong? without a splash screen everything works fine.

**Comment by ratbo99** [comment]
thanks for the answer. i will try it. in the meantime i made the splash in python directly....

**Comment by ozippo** [comment]
Thanks for the answer.
I try the factory, but it still dont work：

In file included from static_src\OnefileBootstrap.c:607:
C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\build\static_src/OnefileSplashScreen.cpp: In function 'getBitmapFromImageStream':
C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\build\static_src/OnefileSplashScreen.cpp:73:9: warning: implicit declaration of function '__uuidof'; did you mean '__muldc3'? [-Wimplicit-function-declaration]
     if (FAILED(CoCreateInstance(CLSID_WICPngDecoder, NULL, CLSCTX_INPROC_SERVER, __uuidof(ipDecoder),
         ^~~~~~
         __muldc3
C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\build\static_src/OnefileSplashScreen.cpp:73:9: error: incompatible type for argument 1 of 'CoCreateInstance'
In file included from C:/Program Files/mingw64/x86_64-w64-mingw32/include/objbase.h:14,
                 from C:/Program Files/mingw64/x86_64-w64-mingw32/include/ole2.h:17,
                 from C:/Program Files/mingw64/x86_64-w64-mingw32/include/wtypes.h:12,
                 from C:/Program Files/mingw64/x86_64-w64-mingw32/include/winscard.h:10,
                 from C:/Program Files/mingw64/x86_64-w64-mingw32/include/windows.h:97,
                 from C:/Program Files/mingw64/x86_64-w64-mingw32/include/rpc.h:16,
                 from C:/Program Files/mingw64/x86_64-w64-mingw32/include/wtypesbase.h:7,
                 from C:/Program Files/mingw64/x86_64-w64-mingw32/include/Shlobj.h:9,
                 from static_src\OnefileBootstrap.c:45:
C:/Program Files/mingw64/x86_64-w64-mingw32/include/combaseapi.h:256:38: note: expected 'const IID * const' {aka 'const struct _GUID * const'} but argument is of type 'GUID' {aka 'const struct _GUID'}
 WINOLEAPI CoCreateInstance (REFCLSID rclsid, LPUNKNOWN pUnkOuter, DWORD dwClsContext, REFIID riid, LPVOID *ppv);
                             ~~~~~~~~~^~~~~~
In file included from static_src\OnefileBootstrap.c:607:
C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\build\static_src/OnefileSplashScreen.cpp:73:9: warning: passing argument 4 of 'CoCreateInstance' makes pointer from integer without a cast [-Wint-conversion]
     if (FAILED(CoCreateInstance(CLSID_WICPngDecoder, NULL, CLSCTX_INPROC_SERVER, __uuidof(ipDecoder),
         ^~~~~~
In file included from C:/Program Files/mingw64/x86_64-w64-mingw32/include/objbase.h:14,
                 from C:/Program Files/mingw64/x86_64-w64-mingw32/include/ole2.h:17,
                 from C:/Program Files/mingw64/x86_64-w64-mingw32/include/wtypes.h:12,
                 from C:/Program Files/mingw64/x86_64-w64-mingw32/include/winscard.h:10,
                 from C:/Program Files/mingw64/x86_64-w64-mingw32/include/windows.h:97,
                 from C:/Program Files/mingw64/x86_64-w64-mingw32/include/rpc.h:16,
                 from C:/Program Files/mingw64/x86_64-w64-mingw32/include/wtypesbase.h:7,
                 from C:/Program Files/mingw64/x86_64-w64-mingw32/include/Shlobj.h:9,
                 from static_src\OnefileBootstrap.c:45:
C:/Program Files/mingw64/x86_64-w64-mingw32/include/combaseapi.h:256:94: note: expected 'const IID * const' {aka 'const struct _GUID * const'} but argument is of type 'int'
 WINOLEAPI CoCreateInstance (REFCLSID rclsid, LPUNKNOWN pUnkOuter, DWORD dwClsContext, REFIID riid, LPVOID *ppv);
                                                                                       ~~~~~~~^~~~
In file included from static_src\OnefileBootstrap.c:607:
C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\build\static_src/OnefileSplashScreen.cpp:77:9: error: 'IWICBitmapDecoder' {aka 'struct IWICBitmapDecoder'} has no member named 'Initialize'
     if (FAILED(ipDecoder->Initialize(image_stream, WICDecodeMetadataCacheOnLoad))) {
         ^~~~~~
C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\build\static_src/OnefileSplashScreen.cpp:81:9: error: 'IWICBitmapDecoder' {aka 'struct IWICBitmapDecoder'} has no member named 'GetFrameCount'
     if (FAILED(ipDecoder->GetFrameCount(&frame_count)) || frame_count != 1) {
         ^~~~~~
C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\build\static_src/OnefileSplashScreen.cpp:85:9: error: 'IWICBitmapDecoder' {aka 'struct IWICBitmapDecoder'} has no member named 'GetFrame'
     if (FAILED(ipDecoder->GetFrame(0, &ipFrame))) {
         ^~~~~~
C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\build\static_src/OnefileSplashScreen.cpp:92:28: error: incompatible type for argument 1 of 'WICConvertBitmapSource'
     WICConvertBitmapSource(GUID_WICPixelFormat32bppPBGRA, ipFrame, &ipBitmap);
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\build\static_src/OnefileSplashScreen.cpp:26,
                 from static_src\OnefileBootstrap.c:607:
C:/Program Files/mingw64/x86_64-w64-mingw32/include/wincodec.h:6440:61: note: expected 'REFWICPixelFormatGUID' {aka 'const struct _GUID * const'} but argument is of type 'GUID' {aka 'const struct _GUID'}
 HRESULT WINAPI WICConvertBitmapSource(REFWICPixelFormatGUID dstFormat, IWICBitmapSource *pISrc, IWICBitmapSource **ppIDst);
                                       ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
In file included from static_src\OnefileBootstrap.c:607:
C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\build\static_src/OnefileSplashScreen.cpp:92:59: warning: passing argument 2 of 'WICConvertBitmapSource' from incompatible pointer type [-Wincompatible-pointer-types]
     WICConvertBitmapSource(GUID_WICPixelFormat32bppPBGRA, ipFrame, &ipBitmap);
                                                           ^~~~~~~
In file included from C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\build\static_src/OnefileSplashScreen.cpp:26,
                 from static_src\OnefileBootstrap.c:607:
C:/Program Files/mingw64/x86_64-w64-mingw32/include/wincodec.h:6440:90: note: expected 'IWICBitmapSource *' {aka 'struct IWICBitmapSource *'} but argument is of type 'IWICBitmapFrameDecode *' {aka 'struct IWICBitmapFrameDecode *'}
 HRESULT WINAPI WICConvertBitmapSource(REFWICPixelFormatGUID dstFormat, IWICBitmapSource *pISrc, IWICBitmapSource **ppIDst);
                                                                        ~~~~~~~~~~~~~~~~~~^~~~~
In file included from static_src\OnefileBootstrap.c:607:
C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\build\static_src/OnefileSplashScreen.cpp:94:12: error: 'IWICBitmapFrameDecode' {aka 'struct IWICBitmapFrameDecode'} has no member named 'Release'
     ipFrame->Release();
            ^~
C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\build\static_src/OnefileSplashScreen.cpp:95:14: error: 'IWICBitmapDecoder' {aka 'struct IWICBitmapDecoder'} has no member named 'Release'
     ipDecoder->Release();
              ^~
C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\build\static_src/OnefileSplashScreen.cpp: In function 'CreateHBITMAP':
C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\build\static_src/OnefileSplashScreen.cpp:104:9: error: 'IWICBitmapSource' {aka 'struct IWICBitmapSource'} has no member named 'GetSize'
     if (FAILED(ipBitmap->GetSize(&width, &height)) || width == 0 || height == 0) {
         ^~~~~~
C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\build\static_src/OnefileSplashScreen.cpp:129:9: error: 'IWICBitmapSource' {aka 'struct IWICBitmapSource'} has no member named 'CopyPixels'
     if (FAILED(ipBitmap->CopyPixels(NULL, stride, size, (BYTE *)(image_data)))) {
         ^~~~~~
C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\build\static_src/OnefileSplashScreen.cpp: In function 'initSplashScreen':
C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\build\static_src/OnefileSplashScreen.cpp:196:17: error: 'IStream' {aka 'struct IStream'} has no member named 'Release'
     image_stream->Release();
                 ^~
C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\build\static_src/OnefileSplashScreen.cpp:201:17: error: 'IWICBitmapSource' {aka 'struct IWICBitmapSource'} has no member named 'Release'
     image_source->Release();
                 ^~
                                                                                                                                                           scons: *** [static_src\OnefileBootstrap.o] Error 1██| 1/1
FATAL: Error, onefile bootstrap binary build failed.

**Comment by kayhayen** [comment]
It's quite possible, it at this time only works with MSVC. The feature is still very experimental.

The whole reason for doing the splash screen in Nuitka is such that if you application is slow to load, you do not have to do anything to change that. Unpacking of Nuitka onefile is very fast, and wouldn't warrant it by default. I am not sure, if I can fight thesee warnings, maybe somebody with more knowledge of MinGW64 can help us here. The "has no member" variety seems bad to me.

**Comment by kayhayen** [comment]
The file has been added as part of the latest hotfix, still seeking help, but not in this issue anymore.
