### ISSUE TITLE
Cannot find requirements for ray  

### ISSUE THREAD

**Issue by hadichko** [Nuitka/Nuitka#1238]
Hi, 
I have a Python project in which I use the ray package for multi-threading. See the warning messages I get during build:
Nuitka-Plugins:WARNING: pkg-resources: Cannot find requirement 'pickle5' for 'ray', expect potential run time problem.
Nuitka-Plugins:WARNING: pkg-resources: Cannot find requirement 'pyarrow' for 'ray.data.impl.util', expect potential run time problem.
As if the warnings were not enough, in the end I got an error message which is not related to ray:
  File "/usr/lib/python3.8/distutils/dir_util.py", line 126, in copy_tree
    raise DistutilsFileError(
distutils.errors.DistutilsFileError: cannot copy tree '/usr/lib/python3/dist-packages/pytz/zoneinfo': not a directory

Any idea how to solve this?

**Comment by kayhayen** [comment]
It's a real pity you didn't fill out the issue template.

**Comment by kayhayen** [comment]
Closing out for lack of feedback.
