### ISSUE TITLE
How to manually include DLL from Python package (e.g. FFmpeg in OpenCV)

### ISSUE THREAD

**Issue by JamesOldfield** [Nuitka/Nuitka#1240]
I am using Python 3.8.11 (through Anaconda) on Windows, with packages (installed with pip, not conda):

    Nuitka==0.6.17.2
    numpy==1.21.1
    opencv-python==4.5.3.56

I am using `--plugin-enable=numpy --plugin-enable=anti-bloat` to enable use of `numpy`, which is a dependancy of OpenCV for Python.

`opencv-python` includes a build of FFmpeg as a dll. The exact file name depends on the version of FFmpeg, which in turn depends on the version of `opencv-python`; in this version particular it is:

    <conda-env>\Lib\site-packages\cv2\opencv_videoio_ffmpeg453_64.dll

It isn't found by the dependency walker. But this is to be expected because it's loaded dynamically only when needed, with a graceful failure (e.g. `VideoWriter` will throw a Python exception). This is done as part of satisfying the LGPL requirements of FFmpeg.

This is more a question than a bug report: what command line option (if any) could I use to include this file?
* I considered (and tried!) `--include-plugin-files=` but it seems to be for Python files to be compiled
* I considered `--include-data-file=` but it takes a file system path, not a path relative to the Python environment
* I considered `--include-package-data=` but it specifically says it excludes DLLs.

For now I am using `--include-data-file=%CONDA_PREFIX%\Lib\site-packages\cv2\opencv_videoio_ffmpeg453_64.dll=opencv_videoio_ffmpeg453_64.dll` and it works (e.g. I can use `VideoWriter`) but it's a bit fragile as it assumes that I'm using Anaconda and Windows (although that is likely to usually be true for me) and the specific FFmpeg number will change as OpenCV version changes.

(Off topic: Many thanks for all your hard work on Nuitka :smile:)

**Comment by JamesOldfield** [comment]
# Dynamic loading from C++

> Maybe when the importlib.import_module static optimization is working, and it seems it does for simple cases, we can attempt to also detect DLL loads from the Python code, maybe this is done with ctypes, it it?

The DLL is not loaded from the Python code at all - it's done dynamically from the C++ code. Here's the code that declares the use of the FFMPEG loader:

    #define DECLARE_DYNAMIC_BACKEND(cap, name, mode) \
    { \
        cap, (BackendMode)(mode), 1000, name, createPluginBackendFactory(cap, name) \
    },
    /* ... */
    DECLARE_DYNAMIC_BACKEND(CAP_FFMPEG, "FFMPEG", MODE_CAPTURE_BY_FILENAME | MODE_WRITER)

And if you chase `createPluginBackendFactory` back (through `class PluginBackendFactory `, which uses `class PluginBackend`, which uses `DynamicLib::libraryLoad`, which calls `libraryLoad_`), you end up at [`modules/core/include/opencv2/core/utils/plugin_loader.private.hpp` line 73](https://github.com/opencv/opencv/blob/830cb5cad7898589fd303292729c02cbf639b8c6/modules/core/include/opencv2/core/utils/plugin_loader.private.hpp#L73):

    static inline
    LibHandle_t libraryLoad_(const FileSystemPath_t& filename)
    {
    #if defined(_WIN32)
    # ifdef WINRT
        return LoadPackagedLibrary(filename.c_str(), 0);
    # else
        return LoadLibraryW(filename.c_str());
    #endif
    #elif defined(__linux__) || defined(__APPLE__) || defined(__OpenBSD__) || defined(__FreeBSD__) || defined(__HAIKU__) || defined(__GLIBC__)
        void* handle = dlopen(filename.c_str(), RTLD_NOW);
        CV_LOG_IF_DEBUG(NULL, !handle, "dlopen() error: " << dlerror());
        return handle;
    #endif
    }

You can see the use of `LoadLibraryW` (or `dlopen` on Linux) is genuinely loading the library at runtime.

# Minimal reproducing case

Here is a minimal reproducing case (let's call it `foo.py`):

    import cv2
    print("* * * * Imported")
    writer = cv2.VideoWriter("output.avi", cv2.VideoWriter_fourcc(*"XVID"), 25, (640, 480))
    print("* * * * Is open:", writer.isOpened())

If you run the script directly (after installing the XVID codec if you don't already have it) you will see:

    * * * * Imported
    * * * * Is open: True

But if you build it with Nuitka:

    python -m nuitka --mingw64 --standalone --plugin-enable=numpy --plugin-enable=anti-bloat foo.py

then running the resulting distribution gives you:

    * * * * Imported
    [ERROR:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-q3d_8t8e\opencv\modules\videoio\src\cap.cpp (589) cv::VideoWriter::open VIDEOIO(CV_IMAGES): raised OpenCV exception:
    
    OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-q3d_8t8e\opencv\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): output.avi in function 'cv::icvExtractPattern'
    
    * * * * Is open: False

On the other hand, if you make the above suggestion (or appropriate variation for your Python installation and OpenCV/FFmpeg version), the resulting build will work:

    python -m nuitka --mingw64 --standalone --plugin-enable=numpy --plugin-enable=anti-bloat ^
        --include-data-file=%CONDA_PREFIX%\Lib\site-packages\cv2\opencv_videoio_ffmpeg453_64.dll=opencv_videoio_ffmpeg453_64.dll ^
        foo.py

**Comment by kayhayen** [comment]
Seems I would need some sort of input files, do I?

**Comment by kayhayen** [comment]
This is the next one right after static optimization for `importlib.import_module` is complete, which itself will take some time. Feel free to remind me when I make a release that claims to do it, but only then.

**Comment by kayhayen** [comment]
The said work is complete and will be in 0.6.18, so this is next on the agenda.

**Comment by kayhayen** [comment]
There are issues with #1366 that will first have to resolved. The DLL integration can now be done through a config file in Nuitka, but the package itself will need some serious work first.

**Comment by kayhayen** [comment]
So VideoWriter is know to work with new enough cv2, and DLLs can be specified via user Yaml configuration files, although of course, they should be added in a PR to the shared configuration file included in Nuitka for general packages.

**Comment by mokurin000** [comment]
Is this possible without a yaml configuration file? I mean an argument to not exclude DLLs from data resources

**Comment by kayhayen** [comment]
No, not possible.
