### ISSUE TITLE
Temporary files under the temp directory cannot be automatically purged

### ISSUE THREAD

**Issue by ozippo** [Nuitka/Nuitka#1245]
When use the --onefile parameter to generate an exe file, the exe file works. However, temporary files(like: onefile_8764_132790263013919660) under the temp directory cannot be automatically purged after the exe file is closed.

nuitka --version
0.6.17.2
Python: 3.9.1 (tags/v3.9.1:1e5d33e, Dec 7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
OS: Windows
Arch: x86_64

**Comment by kayhayen** [comment]
That said, checking the code, I noticed that on Windows it only does the deletion when a console control handler was called, which might not be the case if the console is disabled, which is certainly a possibility. I am adding an explicit cleanup call for when the program exits as well. Not sure why it works for me actually, maybe there is a race condition. On factory that should no longer be the case:

https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
Then likely this is likely fixing things for you, let me know if factory works for you better, as it should.
