### ISSUE TITLE
pyside6:QQmlApplicationEngine failed to load component

### ISSUE THREAD

**Issue by hu76589** [Nuitka/Nuitka#1248]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

 0.6.17.3
Commercial: None
Python: 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
Executable: D:\app\python391\python.exe
OS: Windows
Arch: x86_64

* How did you install Nuitka and Python

  pip install nuitka 

* The specific PyPI names and versions

 PySide6==6.2.0

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

main.py:
import sys

from PySide6.QtGui import QGuiApplication
from PySide6.QtQml import QQmlApplicationEngine

if __name__ == "__main__":
    app = QGuiApplication(sys.argv)
    engine = QQmlApplicationEngine()
    engine.load("./main.qml")
    if not engine.rootObjects():
        sys.exit(-1)
    sys.exit(app.exec())

main.qml:
import QtQuick 2.12
import QtQuick.Controls 2.12
import QtQuick.Controls.Material 2.12

ApplicationWindow {
    id: window
    width: 450
    height: 150
    visible: true
    title: qsTr("test")
    Material.theme: Material.Dark
    Material.accent: Material.Red

    Rectangle {
        width: 50
        height: 50
        border.color: "#ff0000"
        anchors.centerIn: parent

        Text {
            id: red1
            text: qsTr("test")
            font.bold: true
            font.pointSize: 12
            anchors.centerIn: parent
        }
    }
}

* Provide in your issue the Nuitka options used

 nuitka --mingw64 --standalone --show-progress --show-memory --plugin-enable=pyside6 --output-dir=out main.py

when run "main.exe",the error is:

QQmlApplicationEngine failed to load component
file:///D:/py/test/out/main.dist/main.qml:3:1: module "QtQuick.Controls.Material" is not installed
file:///D:/py/test/out/main.dist/main.qml:2:1: module "QtQuick.Controls" is not installed
file:///D:/py/test/out/main.dist/main.qml:1:1: module "QtQuick" is not installed
file:///D:/py/test/out/main.dist/main.qml:3:1: module "QtQuick.Controls.Material" is not installed
file:///D:/py/test/out/main.dist/main.qml:2:1: module "QtQuick.Controls" is not installed
file:///D:/py/test/out/main.dist/main.qml:1:1: module "QtQuick" is not installed
file:///D:/py/test/out/main.dist/main.qml:3:1: module "QtQuick.Controls.Material" is not installed
file:///D:/py/test/out/main.dist/main.qml:2:1: module "QtQuick.Controls" is not installed
file:///D:/py/test/out/main.dist/main.qml:1:1: module "QtQuick" is not installed

**Comment by kayhayen** [comment]
Closing this now, as the original issue was solved long ago of course.
