### ISSUE TITLE
PySide6 QSQLITE driver not loaded

### ISSUE THREAD

**Issue by PMtr** [Nuitka/Nuitka#1254]
Hello,

After some hours of searching without a real success, I'm posting my issue here.

I get the following error when launching the resulting .exe from Nuitka compilation

QSqlDatabase: QSQLITE driver not loaded
QSqlDatabase: available drivers:

I suppose it's a problem to link or to embed qsqlite.dll, but I don't know how to proceed to make it.

See below for conf. details.

Thanks for your support.

Pascal.

  > python -m nuitka --version
0.6.17.4
Commercial: None
Python: 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 14:02:34) [MSC v.1928 64 bit (AMD64)]
Executable: C:\Users\E511794\eric_env\Scripts\python.exe
OS: Windows 10
Arch: x86_64

* How did you install Nuitka and Python

 pip for nuitka, python from python.org/downloads

  > python -m pip freeze
altgraph==0.17
asttokens==2.0.5
cffi==1.15.0
chardet==4.0.0
click==7.1.2
cryptography==35.0.0
cx-Freeze==6.6
cx-Logging==3.0
docutils==0.17
EditorConfig==0.12.3
eric-ide==21.9
Flask==2.0.1
Flask-Cors==3.0.10
future==0.18.2
importlib-metadata==4.0.0
itsdangerous==2.0.1
Jinja2==3.0.1
lxml==4.6.3
Mako==1.1.4
Markdown==3.3.4
MarkupSafe==2.0.1
MouseInfo==0.1.3
Nuitka==0.6.17.4
pefile==2019.4.18
Pillow==8.2.0
PyAutoGUI==0.9.53
pycparser==2.20
PyGetWindow==0.0.9
Pygments==2.10.0
pyinstaller==4.3
pyinstaller-hooks-contrib==2021.1
PyMsgBox==1.0.9
pynput==1.7.3
pyodbc==4.0.30
PyPDF4==1.27.0
pyperclip==1.8.2
PyQt5==5.15.1
pyqt5-plugins==5.15.2.2.1.0
PyQt5-sip==12.8.1
pyqt5-tools==5.15.2.3.0.2
PyQt5Designer==5.14.1
PyQtChart==5.15.1
PyQtWebEngine==5.15.1
PyRect==0.1.4
PyScreeze==0.1.28
PySide2==5.15.2
PySide6==6.2.0
python-dotenv==0.17.0
pythonnet==2.5.2
pytweening==1.0.4
pywin32==300
pywin32-ctypes==0.2.0
PyYAML==5.4.1
QScintilla==2.12.0
qt5-applications==5.15.2.2.1
qt5-tools==5.15.2.1.0.1
reportlab==3.5.67
Send2Trash==1.8.0
shiboken2==5.15.2
shiboken6==6.2.0
SimpleParse==2.2.2
six==1.16.0
toml==0.10.2
vb2py==0.2.2
Werkzeug==2.0.1
xlwt==1.3.0
zipp==3.4.1
zstandard==0.16.0

* Many times when you get an error from Nuitka, your setup may be special

 hello world runs well

* Provide in your issue the Nuitka options used

  python -m nuitka --onefile --windows-icon-from-ico=MyProg.ico --plugin-enable=pyside6 MyProg.py

**Comment by kwiechen** [comment]
putting the sqldrivers folder to _main.dist\PySide6\qt-plugins solves this minor problem

**Comment by kayhayen** [comment]
After enabling the plugin, you just do --help and read what it says. Then it can do stuff automatically. Manual copying is not supported and not working well.
