### ISSUE TITLE
Unable to import win32print with standalone

### ISSUE THREAD

**Issue by JakeKyle** [Nuitka/Nuitka#1256]
Hi

Many thanks for a great compiler and for any help with this.

Nuitka is able to compile a program which contains:
``import win32print``
 to standalone but when I run it I get this error:
```
Traceback (most recent call last):
  File "C:\Users\Jake\PYCHAR~1\TESTWI~1\TEST_W~1.DIS\test_win32print.py", line 1, in <module>
ImportError: LoadLibraryExW 'C:\Users\Jake\PYCHAR~1\TESTWI~1\TEST_W~1.DIS\win32print.pyd' failed: The specified module could not be found.
```

This despite `` win32print.pyd`` being present in the ``.dis`` folder

It seems similar to #1185 to me.

**Versions etc.:**
Nuitka: 0.6.18rc5
Python: 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
OS: Windows
Arch: x86_64

**How installed:**
Python installed from exe downloaded from web
Nuitka Develop version installed via pip:
``pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"``
Not using virtualenv
Earlier Nuitka versions, eg. 0.6.17.3, also failed in the same way

**PyPI names and versions:**
Nuitka==0.6.18rc5
pywin32==302

**Replicable Example:**
test_win32print.py
```
import win32print
print("hello world")
```
Works fine without the import

**Nuitka options**
``nuitka test_win32print.py --standalone``
I have tried various options like:
``--include-module=win32print``
or
``--include-module=pywin32``
but to no avail.

**Results**
Build successful:

```
Nuitka-Options:INFO: Used command line options: test_win32print.py --standalone
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.18rc5' on Python '3.9' commercial None.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'tkinter' added '_tkinter'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'socket' added '_socket'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.
                                                                                                                                               Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
                                                                                                                                               Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl).
Nuitka-Scons:INFO: Compiled 12 C files using clcache with 12 cache hits and 0 cache misses.
Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3\Grammar3.9.7.final.0.pickle' due to package data for 'lib2to3.pgen2'.
Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3\PatternGrammar3.9.7.final.0.pickle' due to package data for 'lib2to3.pgen2'.
Nuitka:INFO: Keeping build directory 'test_win32print.build'.
Nuitka:INFO: Successfully created 'test_win32print.dist\\test_win32print.exe'.
```

**Comment by kayhayen** [comment]
This is fixed on the factory branch: https://nuitka.net/doc/factory.html

**Comment by JakeKyle** [comment]
Many thanks. It works for me using the factory branch.

**Comment by kayhayen** [comment]
Part of 0.6.17.6 hotfix release.
