### ISSUE TITLE
Solution for PyGame_gui asset inclusion?

### ISSUE THREAD

**Issue by Zageron** [Nuitka/Nuitka#1257]
https://github.com/MyreMylar/pygame_gui/issues/214

Is there a known plugin or solution for building in the default assets or data of a library? I have found the commands for various include dir and include by pattern but documentation isn't clear enough and I haven't found any meaningful examples online.

**Comment by kayhayen** [comment]
Lack of feedback, if you cannot provide information, I am going to close this as invalid.

**Comment by Zageron** [comment]
Apologies for the massive delay, the pygame_gui module has data files included within it. As far as I can tell the manual component you linked, which I had attempted to use before, only relates to files the user of nuitka is supplying.
What I am looking for is a way to include the files from pygame_gui.

**Comment by kayhayen** [comment]
There is an option to include package data, you might try that.

**Comment by kayhayen** [comment]
Any success with that @Zageron ?

**Comment by dails08** [comment]
I did find success with it.  I used the option --include-package-data=pygame_gui and it included the necessary data files.  It'll say so in the end of the compilation process.

**Comment by kayhayen** [comment]
I am closing this one as invalid, please open new issue with proper information including a minimal reproducer provided.
