### ISSUE TITLE
Apple Python standalone is linking against specific macOS and cannot be used for standalone

### ISSUE THREAD

**Issue by mwspitzer** [Nuitka/Nuitka#1260]
Likely not a bug, but something I'm doing wrong, but I haven't been able to find any answers.

> python -m nuitka --version
0.6.16.3
Python: 3.8.12 (default, Sep  1 2021, 07:26:09)
OS: Darwin
Arch: x86_64

* How did you install Nuitka and Python

pip

> python -m pip freeze
aniso8601==9.0.1
attrs==21.2.0
certifi==2021.5.30
cffi==1.14.6
charset-normalizer==2.0.5
click==8.0.1
cryptography==3.3.1
cycler==0.10.0
defusedxml==0.6.0
flake8==3.9.2
Flask==1.1.2
Flask-Cors==3.0.8
Flask-Login==0.4.1
flask-restplus==0.13.0
gevent==21.1.2
greenlet==1.1.1
idna==3.2
itsdangerous==2.0.1
Jinja2==3.0.1
jsonschema==3.2.0
kiwisolver==1.3.2
lxml==4.6.3
Mako==1.1.5
Markdown==3.3.4
MarkupSafe==2.0.1
matplotlib==3.1.2
mccabe==0.6.1
nested-lookup==0.2.19
Nuitka==0.6.16.3
numpy==1.20.0
passlib==1.7.2
pdoc3==0.9.2
Pillow==8.3.2
pycodestyle==2.7.0
pycparser==2.20
pyflakes==2.3.1
pyOpenSSL==20.0.1
pyparsing==2.4.7
pyrsistent==0.18.0
python-dateutil==2.8.1
python-docx==0.8.10
pytz==2021.1
regex==2020.6.8
requests==2.26.0
six==1.16.0
urllib3==1.26.6
Werkzeug==2.0.1
zope.event==4.5.0
zope.interface==5.4.0
zstandard==0.15.2

* Provide in your issue the Nuitka options used
# Nuitka compilation options.
#
# nuitka-project: --quiet
# nuitka-project: --standalone
# nuitka-project: --onefile
# nuitka-project: --follow-imports
# nuitka-project: --python-flag=no_site
# nuitka-project: --assume-yes-for-downloads
#
# nuitka-project: --plugin-enable=gevent
# nuitka-project: --plugin-enable=implicit-imports
# nuitka-project: --plugin-enable=numpy
# nuitka-project: --plugin-enable=pylint-warnings
# nuitka-project: --plugin-enable=pkg-resources
#
# ### Copy app directories
# nuitka-project: --include-data-dir=bp/ui/static=static
# nuitka-project: --include-data-dir=bp/ui/templates=templates
# nuitka-project: --include-data-dir=dict=dict
# nuitka-project: --include-data-dir=certs=certs

* Problem
When building on mac, I'm doing the following:

Using python3.8 installed via MacPorts, I create a virtualenv and enable it.
Build using `python3 -m nuitka bp.py` (have also used absolute path to venv python to ensure the right binary is used.
The build gives no errors and runs fine, but others are not able to. For some reason, some of the libraries are being linked outside of the project. They see
`dyld: Library not loaded: /opt/local/lib/libintl.8.dylib
Referenced from: /provate/var/folders/../Python
Reason: image not found`

Once running on my machine, I can go into the temp file to look at the Python file there and see the following:

`/private/var/folders/zj/pq2rg2756tg1hvr4v38b59640000gn/T/onefile_46073_/
> otool -L ./Python
./Python:
        /opt/local/Library/Frameworks/Python.framework/Versions/3.8/Python (compatibility version 3.8.0, current version 3.8.0)
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1675.129.0)
        /opt/local/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.5.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)`

How can I get this to not link to /opt/local? Anybody who tries to run it without ports/homebrew is unable to. The same code builds and runs fine in Windows and Linux.

Thank you
-mS

**Comment by mwspitzer** [comment]
In case someone else finds this, the above didn't fix it. --macos-create-app-bundle was accepted with the latest version, but didn't fix the links. Building the virtualenv with Python 3.8 installed from homebrew vs the macports install fixed it, even without the app bundle. Not sure what the difference is, but the homebrew install plays nicer.

Thank you

**Comment by kayhayen** [comment]
I have made changes for 0.6.18 that reject the Apple Python, which should be detected. I am keeping this closed due to lack of relevance.
