### ISSUE TITLE
compile and build successful, but when I run the exe file, met an error.  

### ISSUE THREAD

**Issue by dream811** [Nuitka/Nuitka#1262]
1. Nuitka version, full Python version and Platform

0.6.17.5
Commercial: None
Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
Executable: D:\CaptchaSolver\venv\Scripts\python.exe
OS: Windows
Arch: x86_64

2. Installation method

I used the virtual environment and the command is ‘python -m pip install nuitka’

I used the nuitka command
python -m nuitka --mingw64 --onefile --windows-company-name=dragon --windows-product-version=1.0
 --plugin-enable=tk-inter --standalone Solver.py
Compiled successfully, but when I run this exe file,
I met an error.

Traceback (most recent call last):
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~3\Solver.py", line 110, in <module>
    solve_captcha(0)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~3\Solver.py", line 79, in solve_captcha
    key = r.recognize_google(audio)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~3\speech_recognition\__init__.py", line 826, in recognize_google
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~3\speech_recognition\__init__.py", line 452, in get_flac_data
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~3\subprocess.py", line 951, in __init__
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~3\subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

How to import these files manually.
Thanks.

**Comment by kayhayen** [comment]
This definitely needs an example program, don't you think?

**Comment by dream811** [comment]
path_to_mp3 = os.path.normpath(os.path.join(os.getcwd(), "sample.mp3"))
    path_to_wav = os.path.normpath(os.path.join(os.getcwd(), "sample.wav"))
    urllib.request.urlretrieve(src, path_to_mp3)

    # load downloaded mp3 audio file as .wav
    try:
        # sound = pydub.AudioSegment.from_wav('sample.wav')
        # sound.export('sample.wav', format="wav")
        # sample_audio = sr.AudioFile()
        sound = pydub.AudioSegment.from_mp3(path_to_mp3)
        sound.export(path_to_wav, format="wav")
        sample_audio = sr.AudioFile(path_to_wav)
    except Exception:
        sys.exit(
            "[ERR] Please run program as administrator or download ffmpeg manually, "
            "https://blog.gregzaal.com/how-to-install-ffmpeg-on-windows/"
        )

    # translate audio to text with google voice recognition
    r = sr.Recognizer()
    with sample_audio as source:
        audio = r.record(source)
    key = r.recognize_google(audio)
    # key = r.recognize_bing(audio, "", "en-US")
    print(f"[INFO] Recaptcha Passcode: {key}")

**Comment by kayhayen** [comment]
I need a self contained example, I do not want to have to fill in any gaps.

**Comment by kayhayen** [comment]
Closing for lack of feedback
