### ISSUE TITLE
Some extension modules do not have proper __package__ in standalone mode, causing errors in new Matplotlib

### ISSUE THREAD

**Issue by codifryed** [Nuitka/Nuitka#1263]
Hi there, 
This issue happens with PySide6 and MatPlotLib 3.5.0.rc1 - the version of matplotlib that supports PySide6 & PyQt6. I know it's not the current stable version, but should be released soon and at the very least you'll have a heads up for when it is. I can compile without error, but when running the compiled binary, it gives this error:
```
Traceback (most recent call last):
  File "/home/theguy/projects/test_nuitka/plot.dist/plot.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/home/theguy/projects/test_nuitka/plot.dist/matplotlib/backends/backend_qtagg.py", line 12, in <module matplotlib.backends.backend_qtagg>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/home/theguy/projects/test_nuitka/plot.dist/matplotlib/backends/backend_qt.py", line 28, in <module matplotlib.backends.backend_qt>
  File "/home/theguy/projects/test_nuitka/plot.dist/matplotlib/backends/backend_qt.py", line 29, in <dictcontraction>
  File "/home/theguy/projects/test_nuitka/plot.dist/matplotlib/backends/qt_compat.py", line 153, in _enum
KeyError: None
```
I see that MatPlotLib has changed how their QT backend setup works a bit with the support for PySide6: https://github.com/matplotlib/matplotlib/pull/19255 

The KeyError reported comes from this line:
`sys.modules[QtCore.__package__]`

**My setup:**
0.6.18rc6  (Also tested against 0.6.17.5)
Commercial: None
Python: 3.9.5 (default, May 11 2021, 08:20:37) 
Executable: /home/theguy/.cache/pypoetry/virtualenvs/test-nuitka-Z7Y54p4h-py3.9/bin/python
OS: Linux
Arch: x86_64

**VirtualEnv managed with:**
Poetry 

**Specific versions used:**
matplotlib-3.5.0rc1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl
numpy-1.21.3-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
PySide6-6.2.1-6.2.1-cp36.cp37.cp38.cp39.cp310-abi3-manylinux1_x86_64.whl
shiboken6-6.2.1-6.2.1-cp36.cp37.cp38.cp39.cp310-abi3-manylinux1_x86_64.whl

**Hello World example for reproduction:**
`plot.py`
```
import sys

from PySide6.QtCore import Qt
from PySide6.QtWidgets import (QApplication, QLabel, QVBoxLayout, QWidget)
from matplotlib.backends.backend_qtagg import FigureCanvasQTAgg
from matplotlib.figure import Figure


class MplCanvas(FigureCanvasQTAgg):

    def __init__(self, parent=None, width=5, height=4, dpi=100):
        fig = Figure(figsize=(width, height), dpi=dpi)
        self.axes = fig.add_subplot(111)
        super(MplCanvas, self).__init__(fig)


class MyWidget(QWidget):
    def __init__(self):
        QWidget.__init__(self)

        self.text = QLabel("Hello World")
        self.text.setAlignment(Qt.AlignCenter)

        sc = MplCanvas(self, width=5, height=4, dpi=100)
        sc.axes.plot([0, 1, 2, 3, 4], [10, 1, 20, 3, 40])

        self.layout = QVBoxLayout()
        self.layout.addWidget(self.text)
        self.layout.addWidget(sc)
        self.setLayout(self.layout)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    widget = MyWidget()
    widget.resize(800, 600)
    widget.show()
    sys.exit(app.exec())
```

**Nuitka options:**

python -m nuitka --follow-imports --standalone --plugin-enable=numpy --plugin-enable=pyside6 plot.py

**Comment by kayhayen** [comment]
Ok, thanks for the report, this should be very fixable with your information provided.

**Comment by forallsunday** [comment]
I have the same issue.

**Comment by kayhayen** [comment]
It seems it's a final release now, so I am trying it out now.

**Comment by kayhayen** [comment]
I am applying anti-bloat plugin, this is my configuration:

```
# nuitka-project: --standalone
# nuitka-project: --plugin-enable=numpy
# nuitka-project: --plugin-enable=pyside6
# nuitka-project: --plugin-enable=anti-bloat
```

It seems include both Qt and Web backends of Matplotlib is costly. It seems to include e.g. Tornado for no good reason. For the Qt plugins, we now have this on develop already:

```
Nuitka-Plugins:INFO: pyside6: Unwanted import of 'PyQt6' that conflicts with 'PySide6' encountered, preventing
its use. As a result an "ImportError" might be given at run time. Uninstall it for full compatible
behaviour with the uncompiled code to debug it.
Nuitka-Plugins:INFO: pyside6: Unwanted import of 'PyQt5' that conflicts with 'PySide6' encountered, preventing
its use. As a result an "ImportError" might be given at run time. Uninstall it for full compatible
behaviour with the uncompiled code to debug it.
Nuitka-Plugins:INFO: pyside6: Unwanted import of 'PySide2' that conflicts with 'PySide6' encountered, preventing
its use. As a result an "ImportError" might be given at run time. Uninstall it for full compatible
behaviour with the uncompiled code to debug it.
```

But I guess, one day we need similar for web backends. For now, it would make sense for matplotlib's different backends to not both be used, but I might be off there. Could evacuate the matplotlib porting of numpy plugin to a dedicated one and add something that disallows both to be imported and make people pick.

**Comment by kayhayen** [comment]
The example has an issue with current PySide or matplotlib final, I cannot tell. It doesn't run. However, I debugged it and it seems that `PySide6.QtCore.__package__` is None with Nuitka and `PySide6` is the correct value.

**Comment by kayhayen** [comment]
It seems there is something specific going on, consider this:

```
import PySide6.QtCore
print(PySide6.QtCore.__package__)

import lxml.etree
print(lxml.etree.__package__)
```

For PySide6 it's wrong, for lxml it's correct. Might have to do with the initialisation method used.

**Comment by kayhayen** [comment]
It's hard to tell, I made a review of the code path, it's the old single phase module load used on Python3.5 or higher, and there is nothing wrong there. However, I am implementing a workaround for this. Just checking if `__package__` was set by the extension module, and if not, we update it to correct value, that should be harmless.

**Comment by codifryed** [comment]
Hi @kayhayen, thanks for looking into this. I too noticed the bloat that comes with matplotlib, especially that web backend. 
It's a bit of a strange bug but glad to hear that a workaround may get that module set correctly. :+1:

**Comment by kayhayen** [comment]
Should be good on factory: https://nuitka.net/doc/factory.html

Strangness is Python eco system normality, default, you name it.

**Comment by forallsunday** [comment]
works fine. thanks a lot.

**Comment by codifryed** [comment]
indeed :D 
Also tested on factory with a non-trivial application. Works. :+1:  Thanks again.

**Comment by kayhayen** [comment]
This is now on develop and will be part of 0.6.18 which will be release soon.

**Comment by kayhayen** [comment]
This is part of the 0.6.18 release.
