### ISSUE TITLE
How to Compile Django App using Nuitka

### ISSUE THREAD

**Issue by nerseswolf** [Nuitka/Nuitka#1265]
Hi, 

I'm trying to compile a Django project with nuitka. Does anyone have a solution how I can do this?

Thank you in advance!

**Comment by sorix6** [comment]
Hi, it’s been a really long time since I got this working so I do not remember what I did. But I believe it requires manage.py to be excluded from obfuscation. I was going to comment on the old issue but they closed it. Sorry I cannot help more.

**Comment by kayhayen** [comment]
wow, no issue template at all, I am going to delete this right away, please do not create issues like this.
