### ISSUE TITLE
How to Compile Django App using Nuitka

### ISSUE THREAD

**Issue by nerseswolf** [Nuitka/Nuitka#1266]
Hi,

I would like to compile a Django application with Nuitka. Unfortunately, I get an error message and don't get it completed successfully. Can you please tell me what I'm doing wrong?

* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

  > python -m nuitka --version
  0.6.17.5
  Commercial: None
  Python: 3.9.7 (default, Oct 13 2021, 06:45:31) 
  Executable: /Users/[user]/Desktop/django_project/venv/bin/python
  OS: Darwin
  Arch: x86_64

* How did you install Python and Nuitka

   installed python with: 
    macOS 64-bit Intel installer ( https://www.python.org/downloads/macos/ )

    installed Nuitka with:
   $ pip install Nuitka

* The specific PyPI names and versions

  > python -m pip freeze
  asgiref==3.4.1
  Django==3.2.9
  Nuitka==0.6.17.5
  pytz==2021.3
  sqlparse==0.4.2

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

  Created simple Django project with:
  $ django-admin startproject mysite

  and for verifying the project, run :
  > python manage.py runserver

  I'm trying to build this project with nuitka as follows:
  > python -m nuitka --module --python-flag=-OO  manage.py

But I get many errors like:

.... 
include/python3.9/Python.h:25:                                                                      
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk/usr/include/stdio.h:64:                                                    
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk/usr/include/_stdio.h:75:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk/usr/include/sys/_types/_va_list.h:31:                                      
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk/usr/include/machine/types.h:37:2: error: architecture not supported
#error architecture not supported                                                                   
 ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]                                 
20 errors generated.                                                                                
scons: *** [__constants.os] Error 1

**Comment by kayhayen** [comment]
Using the iPhoneSDK seems wrong. It seems you would be omitting something there.

**Comment by nerseswolf** [comment]
Thank you for your quick response. I'm not running it from Xcode. On the contrary, I use the normal MacOS terminal. 

When I do the same on Ubuntu:

> python -m nuitka --version
0.6.17.5
Commercial: None
Python: 3.8.0 (default, Feb 25 2021, 22:10:10) 
Executable: /var/www/django_project/venv/bin/python
OS: Linux
Arch: x86_64

I get a compiled file like:

> manage.cpython-38-x86_64-linux-gnu.so

I'm renaming it:

> mv 'manage.cpython-39-darwin.so' manage.so     


And running:

> ./manage.so runserver


which also occurs to an error:

> zsh: permission denied: ./manage.so

**Comment by kayhayen** [comment]
I was interested in the macOS issue too. Can you provide the macOS output with `--show-scons` please.

The module mode is not appropiate for execution. Extension modules can be loaded into Python, but not executed by the OS.

**Comment by nerseswolf** [comment]
Is it generally correct to use the manage.py file to build the django project with nuitka?

Here my MacOS output by running from terminal:

> python -m nuitka --module --show-scons --python-flag=-OO manage.py

Nuitka-Options:INFO: Used command line options: --module --show-scons --python-flag=-OO manage.py
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.17.5' on Python '3.9' commercial None.
Nuitka:INFO: Completed Python level compilation and optimization.               
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.    
Nuitka:INFO: Running C level backend compilation via Scons.
Scons command: /Users/nerseswolf/Desktop/django_project/venv/bin/python -W ignore /Users/nerseswolf/Desktop/django_project/venv/lib/python3.9/site-packages/nuitka/build/inline_copy/bin/scons.py -f /Users/nerseswolf/Desktop/django_project/venv/lib/python3.9/site-packages/nuitka/build/Backend.scons --jobs 4 --warn=no-deprecated --no-site-dir --debug=stacktrace result_name=/Users/nerseswolf/Desktop/django_project/mysite/manage source_dir=. nuitka_python=false debug_mode=false python_debug=false unstripped_mode=false module_mode=true full_compat=false experimental= trace_mode=false python_version=3.9 target_arch=x86_64 python_prefix=/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9 nuitka_src=/Users/nerseswolf/Desktop/django_project/venv/lib/python3.9/site-packages/nuitka/build module_count=2 python_sysflag_optimize=true module_suffix=.cpython-39-darwin.so clang_mode=true show_scons=true
scons: Reading SConscript files ...
Nuitka-Scons:INFO: CC '/usr/bin/gcc' version check gives (13, 0, 0)
Nuitka-Scons:INFO: Initial CC: 'gcc'
Nuitka-Scons:INFO: Initial CCVERSION: (13, 0, 0)
Nuitka-Scons:INFO: Backend C compiler: clang (clang).
Nuitka-Scons:INFO: Modes for this compiler are: {'gcc_mode': True, 'clang_mode': True, 'clangcl_mode': False, 'mingw_mode': False, 'msvc_mode': False}
Nuitka-Scons:INFO: Using C11 mode: True
Scons: Compiler used /usr/bin/clang 
Nuitka-Scons:INFO: LTO mode auto was resolved to mode: 'no' (not known to be supported).
Nuitka-Scons:INFO: Using resource mode: 'incbin' (default).
Nuitka-Scons:INFO: Told to run compilation on 4 CPUs.
Nuitka-Scons:INFO: Checking if ccache is at '/usr/local/opt/ccache' guessed path.
Nuitka-Scons:INFO: Found ccache '/Users/nerseswolf/Library/Application Support/Nuitka/ccache/v4.2.1/ccache' to cache C compilation result.
Nuitka-Scons:INFO: Providing real CC path '/usr/bin/clang' via PATH extension.
Nuitka-Scons:INFO: Launching Scons target: ['/Users/nerseswolf/Desktop/django_project/mysite/manage.cpython-39-darwin.so']
                                                                               scons: done reading SConscript files.                                      | 0/10
scons: Building targets ...
"/Users/nerseswolf/Library/Application Support/Nuitka/ccache/v4.2.1/ccache" "/usr/bin/clang" -o __constants.os -c -std=c11 -fvisibility=hidden -fwrapv -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -pipe -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_MODULE -I/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/include/python3.9 -I. -I/Users/nerseswolf/Desktop/django_project/venv/lib/python3.9/site-packages/nuitka/build/include -I/Users/nerseswolf/Desktop/django_project/venv/lib/python3.9/site-packages/nuitka/build/static_src __constants.c
"/Users/nerseswolf/Library/Application Support/Nuitka/ccache/v4.2.1/ccache" "/usr/bin/clang" -o __constants_data.os -c -std=c11 -fvisibility=hidden -fwrapv -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -pipe -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_MODULE -I/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/include/python3.9 -I. -I/Users/nerseswolf/Desktop/django_project/venv/lib/python3.9/site-packages/nuitka/build/include -I/Users/nerseswolf/Desktop/django_project/venv/lib/python3.9/site-packages/nuitka/build/static_src __constants_data.c
"/Users/nerseswolf/Library/Application Support/Nuitka/ccache/v4.2.1/ccache" "/usr/bin/clang" -o __helpers.os -c -std=c11 -fvisibility=hidden -fwrapv -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -pipe -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_MODULE -I/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/include/python3.9 -I. -I/Users/nerseswolf/Desktop/django_project/venv/lib/python3.9/site-packages/nuitka/build/include -I/Users/nerseswolf/Desktop/django_project/venv/lib/python3.9/site-packages/nuitka/build/static_src __helpers.c
"/Users/nerseswolf/Library/Application Support/Nuitka/ccache/v4.2.1/ccache" "/usr/bin/clang" -o __loader.os -c -std=c11 -fvisibility=hidden -fwrapv -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -pipe -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_MODULE -I/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/include/python3.9 -I. -I/Users/nerseswolf/Desktop/django_project/venv/lib/python3.9/site-packages/nuitka/build/include -I/Users/nerseswolf/Desktop/django_project/venv/lib/python3.9/site-packages/nuitka/build/static_src __loader.c
                                                                               "/Users/nerseswolf/Library/Application Support/Nuitka/ccache/v4.2.1/ccache" "/usr/bin/clang" -o module.manage.os -c -std=c11 -fvisibility=hidden -fwrapv -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -pipe -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_MODULE -I/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/include/python3.9 -I. -I/Users/nerseswolf/Desktop/django_project/venv/lib/python3.9/site-packages/nuitka/build/include -I/Users/nerseswolf/Desktop/django_project/venv/lib/python3.9/site-packages/nuitka/build/static_src module.manage.c
"/Users/nerseswolf/Library/Application Support/Nuitka/ccache/v4.2.1/ccache" "/usr/bin/clang" -o static_src/CompiledCellType.os -c -std=c11 -fvisibility=hidden -fwrapv -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -pipe -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_MODULE -I/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/include/python3.9 -I. -I/Users/nerseswolf/Desktop/django_project/venv/lib/python3.9/site-packages/nuitka/build/include -I/Users/nerseswolf/Desktop/django_project/venv/lib/python3.9/site-packages/nuitka/build/static_src static_src/CompiledCellType.c
In file included from __constants_data.c:9:
In file included from /Users/nerseswolf/Desktop/django_project/venv/lib/python3.9/site-packages/nuitka/build/include/nuitka/incbin.h:37:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include/limits.h:21:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk/usr/include/limits.h:63:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk/usr/include/sys/cdefs.h:825:2: error: Unsupported architecture
#error Unsupported architecture
 ^                                                                              
In file included from __constants_data.c:9:
In file included from /Users/nerseswolf/Desktop/django_project/venv/lib/python3.9/site-packages/nuitka/build/include/nuitka/incbin.h:37:                        
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include/limits.h:21:                  
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk/usr/include/limits.h:64:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk/usr/include/machine/limits.h:11:2: error: architecture not supported
#error architecture not supported
 ^                                                                              
2 errors generated.
"/Users/nerseswolf/Library/Application Support/Nuitka/ccache/v4.2.1/ccache" "/usr/bin/clang" -o static_src/CompiledFunctionType.os -c -std=c11 -fvisibility=hidden -fwrapv -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -pipe -fPIC -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_MODULE -I/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/include/python3.9 -I. -I/Users/nerseswolf/Desktop/django_project/venv/lib/python3.9/site-packages/nuitka/build/include -I/Users/nerseswolf/Desktop/django_project/venv/lib/python3.9/site-packages/nuitka/build/static_src static_src/CompiledFunctionType.c
scons: *** [__constants_data.os] Error 1                                        
scons: internal stack trace:
  File "/Users/nerseswolf/Desktop/django_project/venv/lib/python3.9/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Job.py", line 258, in run
    task.execute()
  File "/Users/nerseswolf/Desktop/django_project/venv/lib/python3.9/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Script/Main.py", line 206, in execute
    SCons.Taskmaster.OutOfDateTask.execute(self)
  File "/Users/nerseswolf/Desktop/django_project/venv/lib/python3.9/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Taskmaster.py", line 255, in execute
    self.targets[0].build()
  File "/Users/nerseswolf/Desktop/django_project/venv/lib/python3.9/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Node/__init__.py", line 766, in build
    self.get_executor()(self, **kw)
  File "/Users/nerseswolf/Desktop/django_project/venv/lib/python3.9/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Executor.py", line 397, in __call__
    return _do_execute_map[self._do_execute](self, target, kw)
  File "/Users/nerseswolf/Desktop/django_project/venv/lib/python3.9/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Executor.py", line 131, in execute_action_list
    raise status    # TODO pylint E0702: raising int not allowed
                                                                               scons: building terminated because of errors.

**Comment by kayhayen** [comment]
You are using Homebrew on macOS, but only CPython and Anaconda would be supported at this time. I have never seen a setup where it does that, but it's not working that way. I can only imagine what's going wrong there, but at this time that's not supported.

So lets turn to Ubuntu. Yes, compiling `manage.py` might work. But in module mode, it's not, it has to become a binary, remove that option. I will need a minimal example though to care about this issue.

**Comment by nerseswolf** [comment]
Yes, I'm using Homebrew on my MacOS.

Now on Ubuntu:

> python -m nuitka --python-flag=-OO manage.py

Nuitka-Options:INFO: Used command line options: --python-flag=-OO manage.py
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.17.5' on Python '3.8' commercial None.
Nuitka-Inclusion:WARNING: Not following import to 'django.core.management' (/var/www/django_project/venv/lib/python3.8/site-packages/django/core/management), please specify --nofollow-imports (do not follow any imports), --follow-imports (follow all generally), --nofollow-import-to=django.core.management (do not follow it), --follow-import-to=django.core.management (follow import it) to change.
Nuitka:INFO: Completed Python level compilation and optimization.                                                                                           
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.                                                                                
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:WARNING: You are not using ccache.                                                                                                            
Nuitka:INFO: Keeping build directory 'manage.build'.
Nuitka:INFO: Successfully created 'manage.bin'.

Then I'm running the created 'manage.bin' file for verifying the build:

> ./manage.bin runserver

  File "./manage.bin", line 1
    ELF1 
    ^
SyntaxError: invalid syntax


To reproduce my small example of the Django project activate a new venv with python 3.8 and run:

> pip install Nuitka==0.6.17.5 Django==3.2.9
> mkdir django_project && cd django_project
> django-admin startproject mysite
> cd mysite

and for verifying the project, run :

> python manage.py runserver

**Comment by kayhayen** [comment]
It seems it's trying to re-execute itself. Can you identfy where and why that happens in Django?

**Comment by nerseswolf** [comment]
ah thank you, I have to deactivate the auto-reloader with --noreload. 

> ./manage.bin runserver --noreload

**Comment by kayhayen** [comment]
you want to use `--standalone` of course, or `--follow-imports` at least, if you want to run only on the same machine. Is there a programtic way to disable autoreload?

**Comment by nerseswolf** [comment]
Even with this my Django project is not recognized and shows this error:

> Error` ModuleNotFoundError: No module named 'django.core.management.commands'

In addition, I also used `--include-plugin-directory` , which didn't get me any further.

To disable autoreload, I only know the command way `--noreload`

**Comment by kayhayen** [comment]
It's a pity, that would be important for a potential Django plugin to do I guess.

I wonder why people resource to plugin directory to include modules when there is `--include-module` in help output. Try that one with names you module names you get errors for and use the later only, for well, files from actual plugin directories, which Django might not have any.

**Comment by kayhayen** [comment]
Closing for lack of feedback. If anyone were to create a new issue with a more complete report, that would be great.
