### ISSUE TITLE
How to pass options to 'python setup.py bdist_nuitka'?

### ISSUE THREAD

**Issue by jitbasemartin** [Nuitka/Nuitka#1272]
How can we pass option to Nuitka when use `python setup.py bdist_nuitka` ?

Current behavior:

```sh
$ python setup.py bdist_nuitka --clang                                              
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --clang not recognized
```

I think `user_options` are missing in: https://github.com/Nuitka/Nuitka/blob/56fc8feefb276499b6d2b9d0a19db1af9ceaf91c/nuitka/distutils/DistutilCommands.py#L253

**Comment by kayhayen** [comment]
I see, beware these are options used in a test, not good ones:

```
    command_options={ 'nuitka' :
        {'--show-scons': True,
         '--show-progress': None,
         '--file-reference-choice':'original',
        }
    },
```

You seem to imply that there is a way for the distutils hook to expose these kinds of things. For the first two kinds of options, I don't have an issue, the later probably should not be like that, people should really put options in there.

Also notice you have project options as a cop out, any compilation of Nuitka will find those normally, but you would have to find the right spot where to put them with this mode of operation, as the entry points are not it, the top level package should do, you can put. 

I guess we should either automate it using the option passing, from Nuitka option parsing. But for some things, I don't see the benefit really to allow them being passed on the command line, e.g. icons etc should not be passed to a setup.py call, but on the inside.

With this information, you can use it. I will write up some new section for use cases, that explains how to use it. My kudos on finding it at all.

The whole `bdist_nuitka` is not well represented in the User Manual. I found this buried. Can you provide

**Comment by kayhayen** [comment]
For my memory, I will post a link here that tells how to do it. Of course a PR that does this would be extremely welcome.

https://jichu4n.com/posts/how-to-add-custom-build-steps-and-commands-to-setuppy/

**Comment by kayhayen** [comment]
This is not going to happen anymore, because `setuptools is so obsolete, and I am not seeing that the `pyproject.toml` allows for it either, so why bother when nobody else did.
