### ISSUE TITLE
Failed to package Kivy/KivyMD into a standalone executable

### ISSUE THREAD

**Issue by Jx-Fong** [Nuitka/Nuitka#1273]
Anyone successfully package a non-tkinter or non-pyqt PyGUI? Here attached the minimum reproducible code for kivy and kivymd and I had failed to compiled a executable exe file for Windows/Linux/Mac for 2 weeks...

# Install Kivy/KivyMD
pip install kivy
or
pip install kivymd

# My code to call a Kivy Button
'''
from kivy.lang import Builder
from kivymd.app import MDApp
from kivy.core.window import Window

Window.size = (360,640)

kv="""
MDRaisedButton:
    text: "Button"
    pos_hint: {"center_x":0.5,"center_y":0.5}
"""
class kivy(MDApp):
    def build(self):
        return Builder.load_string(kv)

kivy().run()

'''

# The nuitka code that I used for compiling this script is as follows:
nuitka --standalone --mingw64 --output-dir=o KivyMD.py

I wonder is this because of lack of plugin? Since by default tkinter has a tk-inter plugin and vice versa for pyqt.

**Comment by kayhayen** [comment]
Kivy has worked in the past. Also wx works.

**Comment by kayhayen** [comment]
Also, there is no wx plugin. Plugins are typically only needed for bad software. Good software is supported without it. That said, it might become necessary, i will see. I assume platforms will make differences.

**Comment by Jx-Fong** [comment]
Thank you for replying. 

Hmm... Does Kivy/KivyMD + nuitka works on your end? Are you using Windows, Linux or Mac? 

KivyMD is so pretty with material design theme and far more visual appealing than pyqt in my opinion. Do you think it is possible to request for a plugin for kivy and kivymd from Nuitka team to package kivy/kivymd app into an executable just like tkinter and pyqt?

**Comment by kayhayen** [comment]
I wasn*t saying it did. But just as an aside, I do not expect it to use anything but Qt. I am adding a couple of implicit imports and datafiles, noting options of Nuitka couldn't do. I will let you know once it works out of the box.

It's unreasonable to assume it needs a plugin. And likely on Windows, the `pyside2` will be needed, but I didn*t get there yet, maybe it really does its own GUI, but I doubt it does anything but layout.

**Comment by kayhayen** [comment]
I think you will have to get a kivy plugin indeed, there is code in kivy.image that scans for several factory, including config on what modules to load, and we will have to finalize that list at compile time. Luckily that should be easy. Hidden dependencies and data files are on factory branch, but unusable before we have that.

**Comment by Jx-Fong** [comment]
If that is the case, may I know how can I get the kivy plugin?

**Comment by kayhayen** [comment]
I am developing it right now, it's on the factory branch, i.e. here: https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
It seems it needs more work, I will let you know, once it covers enough to get your example to work.

**Comment by Jx-Fong** [comment]
Noted, thank you very much for your help.

**Comment by kayhayen** [comment]
The work I did so far is on develop, however I hit a wall when some imported module refused to run without me finding out yet, what it's lacking. I will continue this for the next release cycle.

**Comment by kayhayen** [comment]
The current release contains partial support only, but I will finish this soon, it was added to the roadmap.

**Comment by kayhayen** [comment]
The support for kivy and kivymd is currently on develop, works out of the box due to always enabled kivy plugin. However, on Windows, it warned me about all of PyQt, PySide bindings installed. I do not yet have a plugin that is `noqt`, but I believe it should not be needed, it worked fine when I didn't enable those plugins. Also the numpy plugin was not needed for me.

This one was a lot more complex than expected, but due to commercial backing it finally got done. Thanks.

**Comment by Jx-Fong** [comment]
Finally some good news 💯  I will try it out after the next release. Thank you very much for your help!

**Comment by kayhayen** [comment]
You are welcome, I keep issues open until it's in the stable release, therefore re-opening.

**Comment by kayhayen** [comment]
Part of the 0.6.19 release I just made.
