### ISSUE TITLE
UnicodeDecodeError with python 3

### ISSUE THREAD

**Issue by bago13** [Nuitka/Nuitka#1284]
Hello I'm facing an issue with python 3.6 installed from anaconda on windows.

I'm using --module option for every module of my project.

Here is the message I get :

```
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\PY3\lib\tokenize.py", line 390, in find_cookie
    line_string = line.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\PY3\lib\tokenize.py", line 454, in open
    encoding, lines = detect_encoding(buffer.readline)
  File "C:\ProgramData\Miniconda3\envs\PY3\lib\tokenize.py", line 431, in detect_encoding
    encoding = find_cookie(first)
  File "C:\ProgramData\Miniconda3\envs\PY3\lib\tokenize.py", line 395, in find_cookie
    raise SyntaxError(msg)
SyntaxError: invalid or missing encoding declaration for 'C:\\ProgramData\\Miniconda3\\envs\\PY3\\Scripts\\nuitka3.exe'
```
To be more complete :
- This issue happens when I'm running my setup.py from pycharm, it works well when I run it from powershell (I found this walkaround but it might happen to someone else)
- I'm using nuitka 0.6.17 (but i also tried with  0.6.16 and  0.6.15)
- All my files are encoding in utf-8
- I've ran the whole compilation with python2 without any issue.

**Comment by kayhayen** [comment]
That's not enough information, what's clear is that something finds it necessary to parse the Nuitka executable, which ought to never happen, very likely not nearly a bug of Nuitka. I guess you truncated the call stack, did you? Always a bad idea.

**Comment by kayhayen** [comment]
No feedback yet, I will need more information.

**Comment by bago13** [comment]
Hi, I just found some time to make more tests. I found out that this issue only happens in pycharm in debug mode. When I run my setup.py in normal mode everything works perfectly.

Maybe it's not that important.

**Comment by kayhayen** [comment]
I definitely can't work on it without more information though, but I am glad it's working.
