### ISSUE TITLE
distutils deprecation

### ISSUE THREAD

**Issue by nschloe** [Nuitka/Nuitka#1288]
Nuitka still uses `distutils` in its own code. This should probably be removed at some point.
```
python3.10 -c "import distutils"
```
```
<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
````

**Comment by kayhayen** [comment]
Well, deprecation warnings are disabled in Nuitka, e.g. we use `optparse` which is deprecated since 3.2, and we support Python 2.6 still, so we are not too hot with it.

That said, `distutils` used in only one spot, and that is:

```
def copyTree(source_path, dest_path):
    """Copy whole directory tree, preserving attributes.

    Args:
        source_path: where to copy from
        dest_path: where to copy to, may already exist

    Notes:
        This must be used over `shutil.copytree` which has troubles
        with existing directories.
    """

    from distutils.dir_util import copy_tree

    return copy_tree(source_path, dest_path)
```

I am open to replacement code, esp. as it's not using the same tricks as `copyFileWithPermissions` for filesystems that will give errors in attempts to set ACL, which we do not need. So there would even be an immediate benefit. Long term, we are probably going to need a function that scans a directory, and then lets plugins mess with file contents, and the place files individually, maybe in a filesystem, maybe somewhere else, so this will become unused anyway. 

Tests use it for no good reason (the comment doesn't apply) to copy python files, and otherwise old plugins, which will be changed to data files, and data files, because it's bad. So maybe we will stop having it anyway.

**Comment by nschloe** [comment]
> That said, distutils used in only one spot,

Seems more than one:
```
git grep distutils nuitka/
```
```
nuitka/PythonFlavors.py:            from distutils.dir_util import _multiarch
nuitka/__main__.py:        # only lead to trouble, having e.g. a "distutils" in sys.path that comes
nuitka/__main__.py:        # from "nuitka.distutils".
nuitka/build/inline_copy/lib/scons-2.3.2/SCons/Defaults.py:from distutils.msvccompiler.
nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Defaults.py:from distutils.msvccompiler.
nuitka/build/inline_copy/lib/scons-4.3.0/SCons/Defaults.py:from distutils.msvccompiler.
nuitka/distutils/DistutilCommands.py:""" Nuitka distutils integration.
nuitka/distutils/DistutilCommands.py:import distutils.command.build  # pylint: disable=I0021,import-error,no-name-in-module
nuitka/distutils/DistutilCommands.py:import distutils.command.install  # pylint: disable=I0021,import-error,no-name-in-module
nuitka/distutils/DistutilCommands.py:# Class name enforced by distutils, must match the command name.
nuitka/distutils/DistutilCommands.py:# Required by distutils, used as command name, pylint: disable=invalid-name
nuitka/distutils/DistutilCommands.py:class build(distutils.command.build.build):
nuitka/distutils/DistutilCommands.py:        distutils.command.build.build.run(self)
nuitka/distutils/DistutilCommands.py:# Required by distutils, used as command name, pylint: disable=invalid-name
nuitka/distutils/DistutilCommands.py:class install(distutils.command.install.install):
nuitka/distutils/DistutilCommands.py:        distutils.command.install.install.finalize_options(self)
nuitka/distutils/DistutilCommands.py:# Required by distutils, used as command name, pylint: disable=invalid-name
nuitka/freezer/Standalone.py:            "distutils",
nuitka/freezer/Standalone.py:        if import_path == "distutils.command":
nuitka/freezer/Standalone.py:        if import_path in ("lib2to3", "json", "distutils"):
nuitka/importing/IgnoreListing.py:        # test_distutils.py
nuitka/importing/IgnoreListing.py:        "distutils.tests",
nuitka/importing/IgnoreListing.py:        "distutils.mwerkscompiler",
nuitka/importing/IgnoreListing.py:        "distutils.emxccompiler",
nuitka/plugins/standard/ImplicitImports.py:        "distutils",  # Not performance relevant.
nuitka/plugins/standard/ImplicitImports.py:        "numpy.distutils",  # Largely unused, and a lot of modules.
nuitka/plugins/standard/ImplicitImports.py:        "numpy.f2py",  # Mostly unused, only numpy.distutils import it.
nuitka/plugins/standard/anti-bloat.yml:  description: "disable distutils hacks"
nuitka/plugins/standard/anti-bloat.yml:  description: "remove numpy.distutils references"
nuitka/plugins/standard/anti-bloat.yml:    - "import numpy.distutils.misc_util"
nuitka/plugins/standard/anti-bloat.yml:    "from numpy.distutils.misc_util import get_shared_lib_extension": ""
nuitka/plugins/standard/anti-bloat.yml:    "get_shared_lib_extension()": "repr(numpy.distutils.misc_util.get_shared_lib_extension())"
nuitka/plugins/standard/anti-bloat.yml:    "get_shared_lib_extension(is_python_ext=True)": "repr(numpy.distutils.misc_util.get_shared_lib_extension(is_python_ext=True))"
nuitka/utils/FileOperations.py:        from distutils.dir_util import copy_tree
```

`numpy.distutils` is also of concern: https://github.com/scikit-learn/scikit-learn/issues/21499.

**Comment by nschloe** [comment]
As for `numpy.distutils`, here's a blog post on how scipy moves to [Meson](https://mesonbuild.com/):

https://labs.quansight.org/blog/2021/07/moving-scipy-to-meson/

**Comment by kayhayen** [comment]
Everything you greped there is code handling usage of `distutils` by e.g. `numpy`. The `numpy.distutils` inclusion causes a lot of other imports, that is why `anti-bloat` removes it when enabled, no issue. 

Like I said, the `nuitka_bdist` is for `setuptools`. I call it `distutils`. I do not recall seening any Python project not using that for a long time. 

Debian package origin is detected by them patching `distutils` to contain stuff it normally does not and so on. 

Standard library inclusion excludes `distutils.tests` for being pointless, and so on. 

I am confident all the other places are not "usage" of Nuitka. With your PR it's 3.12 ready. I only wish I was done with 3.10 :)

**Comment by kayhayen** [comment]
This is part of the 0.6.18 release.

**Comment by kayhayen** [comment]
So, 3.12 needs a change in `setup.py` where it monkey patches `distutils.utils` for the bytecode generation to become optional, which will make this hopefully complete, we shall see.
