### ISSUE TITLE
How to access code attributes like __version__ in Nuitka project options?

### ISSUE THREAD

**Issue by codeofdusk** [Nuitka/Nuitka#1294]
When using [Nuitka Options in the code](https://nuitka.net/doc/user-manual.html#nuitka-options-in-the-code), I'd like Nuitka to be able to look up option values from programmatically-specified attributes. For instance, to look up the program version from a module-level `__version__` attribute.

**Comment by kayhayen** [comment]
You can use `__import__("module_name").__version__` for this, just like any other code.

**Comment by codeofdusk** [comment]
Thanks for letting me know, but I couldn't find this documented anywhere...

**Comment by kayhayen** [comment]
@codeofdusk the questions section is for picking up on these, I will try and add this to the User Manual as an example of course too.
