### ISSUE TITLE
libcrypto-1_1-x64.dll and libssl-1_1-x64.dll should also be copied to the dist dir on 64bit Windows

### ISSUE THREAD

**Issue by redstoneleo** [Nuitka/Nuitka#1295]
libcrypto-1_1-x64.dll and libssl-1_1-x64.dll should also be copied to the dist dir on 64bit Windows.
Tested with Python  3.8，win7 64bit, latest Nuitka

**Comment by kayhayen** [comment]
Not filling out the issue template is no good.
