### ISSUE TITLE
ImportError: cannot import name 'suppress_known_deprecation' from 'setuptools.build_meta' 

### ISSUE THREAD

**Issue by nschloe** [Nuitka/Nuitka#1303]
When building with Nuitka, I'm getting
```
  File .tox/.package/lib/python3.7/site-packages/nuitka/distutils/Build.py", line 20, in <module>
    from setuptools.build_meta import _BuildMetaBackend, suppress_known_deprecation
ImportError: cannot import name 'suppress_known_deprecation' from 'setuptools.build_meta' 
```
This function was included only in [setuptools 59](https://github.com/pypa/setuptools/releases/tag/v59.0.0). You should probably bump the requirement.

**Comment by kayhayen** [comment]
Are you attempting to build a wheel as described in the User Manual?

**Comment by kayhayen** [comment]
I see, I am wrapping whatever setuptools provides as its `setuptools.build_meta`, and I was tricked by the too new code, which then gives a warning about setuptools being obsolete while still using it. Nuitka does not depend on setuptools itself, I wonder if just updating it in the docs, to ask for  `>= 59` would be enough, but I think I am going to change the code such that it allows for that function to not exist.

**Comment by kayhayen** [comment]
I have made a change on factory branch, but I will need to test it, unfortunately that's manual right now. Ought to work now. Nuitka itself has no requirement on setuptools as it's supposed to work with very old software, it expresses no opinions on what you should use. Of course that means, my code there needs to support each iteration of setuptools.

**Comment by kayhayen** [comment]
Part of the 0.6.18.2 release.
