### ISSUE TITLE
Non-standard syntax for `command_options` in setup.py

### ISSUE THREAD

**Issue by ra-kete** [Nuitka/Nuitka#1304]
The Nuitka user documentation says that Nuitka options should be specified in the setup.py as follows:
```python
# For setup.py
setup(
   ...,
   command_options={
      'nuitka': {
         # boolean option, e.g. if you cared for C commands
         '--show-scons': True,
         # options with values, e.g. enable a plugin of Nuitka
         '--enable-plugin': 'anti-bloat',
      }
   },
)
```

However, this is apparently not the syntax setuptools intends. The documentation on this is admittedly pretty sparse, this is the best I could find from the setuptools project itself:
-  https://github.com/pypa/setuptools/blob/main/setuptools/_distutils/dist.py#L185-L190

... and from the Sphinx documentation:
- https://www.sphinx-doc.org/en/master/usage/advanced/setuptools.html#using-setuptools-integration

Based on this, the Nuitka example above should actually look like this:
```python
# For setup.py
setup(
   ...,
   command_options={
      'nuitka': {
         # boolean option, e.g. if you cared for C commands
         '--show-scons': ('setup.py', True),
         # options with values, e.g. enable a plugin of Nuitka
         '--enable-plugin': ('setup.py', 'anti-bloat'),
      }
   },
)
```

(The `--` at the beginning of command names could also be removed, but I don't think that matters much.)

### Why is this an issue?

Nuitka doesn't work with the `(source, value)` syntax, it fails complaining about invalid options. That means we have to use the Nuitka-syntax, if we want to set options. That however, breaks whenever setuptools tries to parse these options themselves.

As an example, [setuptools-rust](https://github.com/PyO3/setuptools-rust) calls the method `Distribution.get_cmdline_options`, which makes the build crash with an error like:

```
      File ".../setuptools_rust/setuptools_ext.py", line 129, in run
        options = self.distribution.get_cmdline_options().get("bdist_wheel", {})
      File ".../setuptools/dist.py", line 1070, in get_cmdline_options
        for opt, (src, val) in opts.items():
    TypeError: cannot unpack non-iterable bool object
```

**Comment by kayhayen** [comment]
Thanks for your report, this looks like very valueable information.

**Comment by kayhayen** [comment]
What's crazy is that if you check the source code, it is also only used for tracing which is normally not enabled, and for raising an exception. I could make the code now accept a tuple, and if it's one, insist on it being "setup.py" maybe, and ignore it otherwise.

**Comment by kayhayen** [comment]
But honstly, what is setuptools-rust buisness to look into `nuitka` options anyway?

**Comment by ra-kete** [comment]
It doesn't care about the "nuitka" options, only "bdist_wheel": https://github.com/PyO3/setuptools-rust/blob/main/setuptools_rust/setuptools_ext.py#L129. But to do so it invokes `Distribution.get_cmdline_options`, which iterates over all options.

**Comment by kayhayen** [comment]
Regarding your options comment, there is actually code like this on out setuptools hook:

```
option = "--" + option.lstrip("-")
```

So it would be added, that's not a documented feature though, and I think it's a bad idea. There is some value to being able to search these and find the matching command line options.

Oh, and we accept lists, e.g. for plugins, so tuples were allowed, as are lists, or any iterable, since you cannot repeat options, tuples are actually allowed.

**Comment by kayhayen** [comment]
Going to add code like this then:

```
                    if type(value) is tuple and len(value) == 2 and value[0] == "setup.py":
                        value = value[1]
```

**Comment by kayhayen** [comment]
So now this is going to read like this:

```
   # For setup.py
   setup(
      ...,
      command_options={
         'nuitka': {
            # boolean option, e.g. if you cared for C commands
            '--show-scons': ("setup.py", True),
            # options with values, e.g. enable a plugin of Nuitka
            '--enable-plugin': ("setup.py", 'anti-bloat'),
            # options without value, e.g. enforce using Clang
            '--clang': ("setup.py", None),
            # options with several values, e.g. avoiding including modules
            '--nofollow-import-to' : ("setup.py", ["*.tests", ".distutils"]),
         }
      },
   )
```

**Comment by kayhayen** [comment]
This is hotfix material, can you confirm this does it for you:

https://nuitka.net/doc/factory.html

**Comment by ra-kete** [comment]
I tried it: Using `bool`s to specify flags that take no value doesn't work anymore now. With these options:
```
    command_options={
        "nuitka": {
            "lto": ("setup.py", True),
            "no-pyi-file": ("setup.py", True),
        },
    },
```
I get:
```
Usage: __main__.py [--module] [--run] [options] main_module.py

__main__.py: error: option --lto: invalid choice: '--no-pyi-file' (choose from 'yes', 'no', 'auto')
```

**Comment by kayhayen** [comment]
Well, the `--lto` option was changed accordingly, maybe 2 releases ago.

**Comment by kayhayen** [comment]
It's now is a `choice` and you are getting the next argument value as an option. What this ultimately does is to build one string on the command line, and that's it, and the second option name therefore becomes to value name for `--lto`.

**Comment by ra-kete** [comment]
Ah, that makes sense. I guess my Nuitka version was not updated before then.

After changing the lto option, it works nicely for me :)

**Comment by kayhayen** [comment]
Part of 0.6.18.2 hotfix that was just released.
