### ISSUE TITLE
zstd debug info

### ISSUE THREAD

**Issue by alchem1ster** [Nuitka/Nuitka#1310]
```0.6.18.2
Commercial: None
Python: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
Flavor: Unknown
Executable: O:\Python38\python.exe
OS: Windows
Arch: x86_64
MinGW64: gcc-11.2.0-llvm-12.0.1-mingw-w64-9.0.0-r1
```
The ZSTD library seems to adds debug info to the output binary PE file
Compiled via `nuitka --onefile .\app.py --lto=yes`
<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/28135995/145633171-e8117ab1-4cd7-46a8-85e1-0aa19ea1c04a.png)

</details>

Any ways to stripping out??

**Comment by kayhayen** [comment]
Oh, that's bad, maybe unstripped mode is broken with gcc.

**Comment by kayhayen** [comment]
Yes, MinGW64 has it happening, MSVC does not, which is good as commercial users are on the later. I think LTO might be automatic, I didn't have to use it. I thought it might be related to that, but it is not.

**Comment by kayhayen** [comment]
Ah, seems zstd has traces that want to use `__FILE__` in case of an error, and MSVC doesn't put the full path there, or maybe not do that at all, not sure yet. I am going to get rid of these in a hotfix.

**Comment by kayhayen** [comment]
The fix is on factory, but it's less stable than even normal, I will however make a hotfix later this weekend: https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
Part of the current hotfix.
