### ISSUE TITLE
run exe file exit silently without error message on window10 py3.9.9

### ISSUE THREAD

**Issue by zhusihan-python** [Nuitka/Nuitka#1313]
hi, when i run the output main.exe, the console show up for a few seconds and exit without any output error or meeage.

im using Nuitka 0.6.18.2 at first, get this error with opencv
`ImportError: OpenCV loader: missing configuration file: ['config.py']. Check OpenCV installation.`
so i upgrade my nuitka to 0.6.19rc4 according to this issue
https://github.com/Nuitka/Nuitka/issues/1275
`pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"
`
here is my current environment info:
F:\nuitka\NeatSvtScan>python -m nuitka --version
```
0.6.19rc4
Commercial: None
Python: 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: D:\softwares\py39\python.exe
OS: Windows
Arch: x86_64
```
python library i used in my program:
```
PyQt5 == 5.15.4
PyQtWebEngine == 5.15.5
libscrc == 1.7.1
opencv-python == 4.5.4.58
numpy == 1.21.4
pyvips == 2.1.15
pyserial == 3.5
```
my gcc version
```
F:\nuitka\NeatSvtScan>gcc --version
gcc (x86_64-win32-sjlj-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
i notice that nuitka download a newer one for me and use that to compile
```
Nuitka-Scons:INFO: Too old gcc 'C:\\mingw64\\bin\\gcc.exe' ((8, 1, 0) < (11, 2)) ignored!
Nuitka-Scons:INFO: Backend C compiler: C:\Users\4\AppData\Local\Nuitka\Nuitka\gcc\x86_64\11.2.0-12.0.1-9.0.0-r1\mingw64\bin\gcc.exe (gcc.exe).
```
my comile command:
`python -m nuitka --mingw64 --show-memory --show-progress --follow-imports --enable-plugin=numpy --enable-plugin=pyqt5 --windows-icon-from-ico=F:\nuitka\favicon.ico main.py`

when i run the output main.exe, the console show up for a few seconds and exit without any output error or meeage. i copy the output exe file to other directory and execute it, also the same result.

i add the out put redirct command with  --windows-force-stdout-spec
`python -m nuitka --mingw64 --show-memory --show-progress --follow-imports --enable-plugin=numpy --enable-plugin=pyqt5 --windows-icon-from-ico=F:\nuitka\favicon.ico --windows-force-stdout-spec=F:\logs\stdout.log --windows-force-stderr-spec=F:\logs\stderr.log main.py
`
also the same problem, the console and the stdout.log are both empty.
i got this warning when compiling, i dont know if they are relevant, and why got this warning as i do specified plugin arguments by --enable-plugin
```
Nuitka-Plugins:WARNING: numpy: Not relevant with this OS, or Nuitka arguments given, not activated.
Nuitka-Plugins:WARNING: pyqt5: Not relevant with this OS, or Nuitka arguments given, not activated.
```
i wonder if there are any way to get the debug info, why it collapse. any help would be appreciate

**Comment by zhusihan-python** [comment]
now it has output, its the self define library import error, it cant import even if the program dir is added to system path. so it didn't go to main function. but i still have a question that if i compile the whole program to C by --follow-imports,  why do i need to import python lib while run the exe file.

**Comment by kayhayen** [comment]
It seems you want to use standalone mode, check out the user manual. The binary you create ought to run on the same machine, but mostly only there, and often only if started through a cmd file also generated.

**Comment by zhusihan-python** [comment]
> 
hello kayhayen
i tried standalone before yet not working. this time i add --onefile param
total compile command is 
`python -m nuitka --standalone --onefile --mingw64 --show-memory --show-progress --follow-imports --enable-plugin=numpy --enable-plugin=pyqt5 --windows-icon-from-ico=F:\nuitka\favicon.ico --windows-force-stdout-spec=F:\logs\stdout.log --windows-force-stderr-spec=F:\logs\stderr.log --output-dir=output index.py`
it gens a single index.exe file. run it still didn't import module correctly
here is my import code
```
import sys
import os
root_dir = os.path.dirname(__file__)
print(root_dir)
sys.path.insert(0, root_dir)
print("sys path:", sys.path)
try:
    from PyQt5 import QtCore, QtGui, QtWidgets
    from PyQt5.QtCore import Qt, pyqtSignal
    print("import pyqt finished")
    from utils.qutil import qtutils
    from UI.MainWindowV4 import MainScreen
    from UI.router import Route
    print("import UI finished")
    from slide.time_label import TimeLabel
    from slide.status_label import StatusLabelWidget
    from mcu.port_driver import device, check_thread
    print("all import finished")
except Exception as e:
    print(e)
    import traceback
    traceback.print_exc()
```
the log show that it import pyqt5 no problem, after that when it import utils didn't work well
```
C:\Users\4\AppData\Local\Temp\ON0DDC~1
sys path: ['C:\\Users\\4\\AppData\\Local\\Temp\\ON0DDC~1', 'F:\\nuitka\\NeatSvtScan\\output', 'C:\\Users\\4\\AppData\\Local\\Temp\\ON0DDC~1']
import pyqt finished
```
in the index.build dir i can see all files in utils are transfered to c code
```
2021/12/14  18:53            24,994 module.utils.c
2021/12/14  18:53            28,842 module.utils.common.c
2021/12/14  18:53            49,662 module.utils.common.common.c
2021/12/14  18:53               786 module.utils.common.common.const
2021/12/14  18:54            15,421 module.utils.common.common.o
2021/12/14  18:53               501 module.utils.common.const
2021/12/14  18:53            74,437 module.utils.common.logger.c
2021/12/14  18:53             1,479 module.utils.common.logger.const
2021/12/14  18:54            21,132 module.utils.common.logger.o
2021/12/14  18:53           172,455 module.utils.common.lru_cache.c
2021/12/14  18:53             1,748 module.utils.common.lru_cache.const
2021/12/14  18:54            47,726 module.utils.common.lru_cache.o
2021/12/14  18:53           156,933 module.utils.common.multi_thread.c
2021/12/14  18:53             2,494 module.utils.common.multi_thread.const
2021/12/14  18:54            40,893 module.utils.common.multi_thread.o
2021/12/14  18:54             9,042 module.utils.common.o
2021/12/14  18:53               401 module.utils.const
2021/12/14  18:53            29,038 module.utils.im_process.c
2021/12/14  18:53               517 module.utils.im_process.const
2021/12/14  18:53           178,713 module.utils.im_process.cv_helper.c
2021/12/14  18:53             2,434 module.utils.im_process.cv_helper.const
2021/12/14  18:54            53,263 module.utils.im_process.cv_helper.o
2021/12/14  18:53           226,503 module.utils.im_process.detect_issue.c
2021/12/14  18:53             2,520 module.utils.im_process.detect_issue.const
2021/12/14  18:54            94,498 module.utils.im_process.detect_issue.o
2021/12/14  18:53            97,642 module.utils.im_process.gen_tile.c
2021/12/14  18:53             1,449 module.utils.im_process.gen_tile.const
2021/12/14  18:54            33,946 module.utils.im_process.gen_tile.o
2021/12/14  18:53           234,771 module.utils.im_process.img_combine.c
2021/12/14  18:53             1,547 module.utils.im_process.img_combine.const
2021/12/14  18:54            63,400 module.utils.im_process.img_combine.o
2021/12/14  18:54             9,058 module.utils.im_process.o
2021/12/14  18:54             8,360 module.utils.o
2021/12/14  18:53            28,793 module.utils.qutil.c
2021/12/14  18:53               497 module.utils.qutil.const
```
is the python interpreter still need when running the one file exe file. should i set the python path
