### ISSUE TITLE
Can't create a standalone, no python dll.

### ISSUE THREAD

**Issue by math-artist** [Nuitka/Nuitka#1315]
```
0.6.18.2
Commercial: None
Python: 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 15:37:01) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\jeans\miniconda3\envs\fresh\python.exe
OS: Windows
Arch: x86_64
```
I used to compile with Nuitka with hinted compilation before. I am now trying to compile without it on 0.6.18.2.

This seems like an easy to solve issue but I can't figure it out. I get a "success" compile and an executable. When I try to run it, I get an error message stating "python37.dll not found"  (in french, so it's something similar).  If I add the .dll in the same folder, I get rid of the error, but nothing happens, there is no message in the console.

Also, only an exec and a bat file are created. No folder or dll is created or moved to the destination, which surprises me because with hinted compilation I end up with hundreds of files and folders.

I am using these arguments:

```
    "--standalone",
    "--mingw64",
    "--follow-imports",
    "--assume-yes-for-downloads",
    "--warn-implicit-exceptions",
    "--warn-unusual-code",
    "--windows-icon-from-ico=logo.ico",
    "--static-libpython=no",
```
in a .py file for my own sanity and calling nuitka directly from the file, similar to how nuitka-hints was doing it:

```
import sys
from nuitka.__main__ import main
...
do some stuff, options
...
sys.argv = my_opts
main()
```

Also, it seems to always fail at a first attempt, then succeed. That's the only warning I get:

```
Nuitka-Postprocessing:WARNING: 
Failed to add resources to file 'C:\\Users\\jeansDev\\project\\DIST\\cor.exe' in attempt 1 with error code 22.
Disable Anti-Virus, e.g. Windows Defender for build folders. Retrying after a second of delay.
Nuitka-Postprocessing:WARNING: Succeeded with resource update in attempt 2.
```

Edit: I was getting that same error on the latest dev version, then rolledback to stable 0.6.18.2. before submitting this issue.

**Comment by math-artist** [comment]
Quite similar to this:  #1313 

> It seems you want to use standalone mode, check out the user manual. The binary you create ought to run on the same machine, but mostly only there, and often only if started through a cmd file also generated.

@kayhayen I need clarification on this. I seem to be trying to do the exact same thing.

Pasted from the User Manual:

> Moving binaries to other machines
> The created binaries can be made executable independent of the Python installation, with --standalone and --onefile options.

I also caught a post from you stating that hinted-compilation is not maintained anymore and that you consider it obsolete with the new anti-bloat plugin.

That, and the manual explanation led to me think that I can get the same result with --standalone and distribute my application.  

Are you saying that it is not possible to distribute my application anymore with the latest versions of Nuitka?

**Comment by math-artist** [comment]
I might also be worth noting that `--standalone` is not creating a program.dist folder for me, only a program.build.  

> If you want to be able to copy it to another machine, use --standalone and copy the created program.dist directory and execute the program.exe (Windows) or program (other platforms) put inside.

**Comment by math-artist** [comment]
I changed the order of the arguments and I now have expected warnings for plugin detection, which means that my argument 
`--standalone` was being ignored when at the first position, which I understand now:

```
    if "NUITKA_BINARY_NAME" in os.environ:
        sys.argv[0] = os.environ["NUITKA_BINARY_NAME"]
```
Conclusion: reserve 1st spot for this when calling Nuitka from a python file.

**Comment by kayhayen** [comment]
Are you aware of `nuitka-project:` style options. I am not sure what your wrapper is aiming at achieving, but I am trying to make these things unnecessary. The `sys.argv[0]` is always the program. And Nuitka wants to re-execute, in case certain conditions are not met, you better avoid that trouble by running it as a process.
