### ISSUE TITLE
Scipy can't import _ufuncs

### ISSUE THREAD

**Issue by math-artist** [Nuitka/Nuitka#1318]
```
0.6.18.2
Commercial: None
Python: 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 15:37:01) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\jeans\miniconda3\envs\fresh\python.exe
OS: Windows 10
Arch: x86_64

Scipy Version: 1.7.1
```
Even with this line during compile
`Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'scipy.special' added 'scipy.special._ufuncs_cxx'.
`

I get this at runtime:
```
  File "C:\Users\jeans\project\scipy\interpolate\__init__.py", line 166, in <module scipy.interpolate>
  File "C:\Users\jeans\project\scipy\interpolate\interpolate.py", line 11, in <module scipy.interpolate.interpolate>
  File "C:\Users\jeans\project\scipy\special\__init__.py", line 643, in <module scipy.special>
ImportError
```

This is the faulty line 643 in \scipy\special\__init__.py
`from . import _ufuncs`

Which has not changed in 2 years.

The file `_ufuncs.pyd` has been properly copied by Nuitka to the Scipy/special folder in the distribution.

I can't figure out this one and need some help please.

**Comment by math-artist** [comment]
I just wanted to mention that I already use --standalone, so the workaround from the issue in October won't work here.

**Comment by math-artist** [comment]
Same issue confirmed with Scipy 1.6.3

**Comment by math-artist** [comment]
Working by downgrading to 1.3.1

By the way, I think that I had this issue almost 2 years ago, which is the reason why my last successful compile was with that same version of Scipy. It was still Windows and Anaconda, but it was on a Windows 7 machine.

**Comment by kayhayen** [comment]
@math-artist what is the reproducer there, I think I have compiled scipy repeatedly with success, i guess it's only an import?

**Comment by math-artist** [comment]
On my side it's just importing interpolate like that:

`from scipy import interpolate`

which calls the Scipy.Special init method, and fail at the line:

```
from . import _ufuncs
from ._ufuncs import *
```

My working version of Scipy (1.3.1) does not have the first line `from . import _ufuncs` but has the second line, and the pyd file is different.Versions of _ufuncs pyd that failed for me also have a similar size of 777 kb while 1.3.1 is about 1 mb, so this could be caused by code in the pyd file?

**Comment by kayhayen** [comment]
Ok, I have done a lot of work for the anti-bloat plugin and scipy, and never encountered that one, but I added that import to it, lets see, I should reproduce it now I guess.

**Comment by kayhayen** [comment]
Works for me just fine on Linux, no surprise there. Can you confirm you are using the numpy plugin indeed?

**Comment by kayhayen** [comment]
Reminder to self, I should not waste time on issues without a command line included.

**Comment by math-artist** [comment]
I will try to provide an example to reproduce later.

**Comment by kayhayen** [comment]
@math-artist you will be welcome, please then open a new issue and fill out the template accurately
