### ISSUE TITLE
virtualenvwrapper-win, Py2.7, ImportError: No module named ntpath

### ISSUE THREAD

**Issue by foobar3000** [Nuitka/Nuitka#1320]
When running nuitka, I get `ImportError: No module named ntpath` although it is in the standard library.

Python: 2.7.18
Windows 8.1
venv created using virtualenvwrapper-win

Steps to reproduce:

```
Z:\legacy_stuff (feature/db-migration -> origin)
(legacy_stuff_2_64) λ where nuitka
C:\Users\f3k\Envs\legacy_stuff_2_64\Scripts\nuitka.bat

Z:\legacy_stuff (feature/db-migration -> origin)
(legacy_stuff_2_64) λ nuitka --standalone legacy_stuffController.py --output-dir=U:\Logistik --remove-output

Traceback (most recent call last):
  File "C:\Users\f3k\Envs\legacy_stuff_2_64\lib\site-packages\nuitka\__main__.py", line 29, in <module>
    import os
  File "C:\Users\f3k\Envs\legacy_stuff_2_64\lib\os.py", line 63, in <module>
    import ntpath as path
ImportError: No module named ntpath

Z:\legacy_stuff (feature/db-migration -> origin)
(legacy_stuff_2_64) λ python
Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.executable
'C:\\Users\\f3k\\Envs\\legacy_stuff_2_64\\Scripts\\python.exe'
>>> import ntpath as path
>>> exit()

(legacy_stuff_2_64) λ pip freeze
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
certifi==2021.10.8
chardet==4.0.0
cx-Oracle==7.3.0
gevent==1.2.0
greenlet==1.1.2
idna==2.10
Nuitka==0.6.18.4
pywin32==228
requests==2.25.1
shortuuid==0.5.0
urllib3==1.26.7
win-unc==0.6.1
```

**Comment by kayhayen** [comment]
I would blame `virtualenvwrapper-bin`. It seems when Nuitka re-executes something it does in `site.py`  is getting lost. Use a standard approach for now, I will check out what this does and add support for it, but for now I doubt it has anything to do with your other points.

**Comment by kayhayen** [comment]
I tried `virtualenvwrapper-bin` and it worked. I do not have `python` in `%PATH%`, so I had to add it for those scripts to work, and then nuitka.bat worked after installing (albeit develop version, but I don't think it matters much), and I even checked with `-S` which is how Nuitka relaunches. Being able to import `os` but not `ntpath` is strange and I cannot explain it. Did you use any special options to create that venv then?

**Comment by foobar3000** [comment]
I think, you are right, it seems to be a virtualenvwrapper issue. Installing and running nuitka without venv works fine.
Nothing special creating the venv: `mkvirtualenv -p c:/Python27/python.exe VENV_NAME` (although mkvirtualenv is added to %PAHT%)

**Comment by kayhayen** [comment]
That was not enough to reproduce the issue though, my attempt at creating it just allowed "install" from Nuitka source to work, not sure how well that environment deals with pip wheel installs, but it shouldn't make much of a difference.

**Comment by kayhayen** [comment]
I will need more information to reproduce it. I do not buy that it's about Windows 8, however, maybe you are having a situation where the batch files would need to set or not set something, can you show the "nuitka3.bat" it installed for you?

**Comment by foobar3000** [comment]
Hi Kay, let's close the issue for now. We both got other things to do, as messing around with outdated Py2 and some bugs which not really related to nuitka :)

As my whole setting varies:
- Win7 or 8
- Python installed manually using installer MSI from python.org or via pyenv-win
- Different versions Py2/3
- %PATH% set or not.

There is just one thing I've always installed: virtualenvwrapper-win and the error comes up. As totally new venv's looking weird, there is just `os` and `site`, probably that's why:
```
C:\Users\f3k\Envs\foo2\Lib
λ dir
 Volume in Laufwerk C: hat keine Bezeichnung.
 Volumeseriennummer: AC8A-29DC

 Verzeichnis von C:\Users\f3k\Envs\foo2\Lib

18.12.2021  20:16    <DIR>          .
18.12.2021  20:16    <DIR>          ..
18.12.2021  20:08            26.652 os.py
18.12.2021  20:08    <DIR>          site-packages
18.12.2021  20:08             7.129 site.py
               2 Datei(en),         33.781 Bytes
               3 Verzeichnis(se), 28.012.380.160 Bytes frei
```

Thanks for your effort and great work on Nuitka.

**Comment by kayhayen** [comment]
This is definitely how much freshly created one in env looks site. You might have user configuration that affects virtualenvwrapper-win there or something, mine are complete.

**Comment by brherger** [comment]
For what it's worth I just ran into this same issue using `tox`, `nuikta==0.7.7`, and `python==2.7.18`.

It looks like nuitka hits the `reExecuteNuitka` call in `__main__.py` and adjusts the `sys.path` such that when `import os` runs the second time it fails.

`print(sys.path)` at the top of `__main__.py`... 

first time...
```
['', 'C:\\WINDOWS\\SYSTEM32\\python27.zip', 'C:\\Python27.64\\DLLs', 'C:\\Python27.64\\lib', 'C:\\Python27.64\\lib\\plat-win', 'C:\\Python27.64\\lib\\lib-tk', 'C:\\Users\\x\\foo\\.tox\\py27\\Scripts', 'C:\\Users\\x\\foo\\.tox\\py27', 'C:\\Users\\x\\foo\\.tox\\py27\\lib\\site-packages']
```

second time (reExecuteNuitka)...
```
['C:\\Users\\x\\foo\\.tox\\py27\\lib\\site-packages\\nuitka', 'C:\\WINDOWS\\SYSTEM32\\python27.zip', 'C:\\Users\\x\\foo\\.tox\\py27\\DLLs', 'C:\\Users\\x\\foo\\.tox\\py27\\lib', 'C:\\Users\\x\\foo\\.tox\\py27\\lib\\plat-win', 'C:\\Users\\x\\foo\\.tox\\py27\\lib\\lib-tk', 'C:\\Users\\x\\foo\\.tox\\py27\\Scripts']
```

```
Traceback (most recent call last):
  File "C:\Users\x\foo\.tox\py27\lib\site-packages\nuitka\__main__.py", line 28, in <module>
    import os
  File "C:\Users\x\foo\.tox\py27\lib\os.py", line 63, in <module>
    import ntpath as path
ImportError: No module named ntpath
```

tox.ini
```
[tox]
minversion = 2.4.1
envlist = dist
skipsdist = True

[testenv]
basepython = python2.7
envdir = {toxworkdir}/py27
passenv = HOME

[testenv:nuitka]
deps =
    nuitka
    zstandard
whitelist_externals =
    where
commands =
    python -c "import os; import ntpath"
    python -c "import sys; print(sys.path)"
    nuitka --version
```

**Comment by kayhayen** [comment]
@brherger your definition of same issue is likely off, the symptom can be caused by many things. Can you report it as a new one with full information, looks very interesting to me, but the issue template asks a bit more details
