### ISSUE TITLE
Mingw64: undefined reference to `_PyObjectDict_SetItem'

### ISSUE THREAD

**Issue by zegervdv** [Nuitka/Nuitka#1322]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

  > python -m nuitka --version
``` 
0.6.19rc5
Commercial: None
Python: 3.9.7 (default, Nov 21 2021, 22:02:56)  [GCC 11.2.0 64 bit (AMD64)]
Flavor: MSYS2 MinGW
Executable: C:/msys64/mingw64/bin/python3.exe
OS: Windows
Arch: x86_64
```

* How did you install Nuitka and Python

pip installed from git repo (`pip install /path/to/nuitka`) on develop branch

* The specific PyPI names and versions

no other packages involved

* Many times when you get an error from Nuitka, your setup may be special

triggers on hello.py example:
``` python
def talk(message):
    return "Talk " + message


def main():
    print(talk("Hello World"))


if __name__ == "__main__":
    main()
```

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

Trying to build the above hello.py example on msys2 fails to link:
```
$ python3 -m nuitka --standalone --static-libpython=yes --mingw hello.py
Nuitka-Options:INFO: Used command line options: --standalone --static-libpython=yes --mingw hello.py
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.19rc5' on Python '3.9' commercial None.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'tkinter' added '_tkinter'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'socket' added '_socket'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'curses' added '_curses'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./static_src/CompiledFunctionType.o:CompiledFunctionType.c:(.text+0x39c23): undefined reference to `_PyObjectDict_SetItem'
collect2.exe: error: ld returned 1 exit status
Backend C:   0%|          | 11/?scons: *** [C:/msys64/home/user/HELLO~1.DIS/hello.exe] Error 1
```

* Provide in your issue the Nuitka options used

  `--standalone --static-libpython=yes --mingw`

* Note if this is a regression

 yes, but not sure from what version
 
 Is this a missing function/symbol in the msys python libs? Or are we missing an LDFLAG?

**Comment by kayhayen** [comment]
Nuitka is using an unofficial symbol, and gets away with doing it, on most platforms, actually all but Windows, the code that controls this is as follows:

```
if static_libpython and not (env.anaconda_python and win_target):
    env.Append(CPPDEFINES=["_NUITKA_USE_UNEXPOSED_API"])
```

I think Nuitka-Python wants this enabled. I CPython never gets there. And Anaconda has a pseudo library that is unusable, not sure of MSYS2, is that real static linking therre? I was adding msys2 as a flag, but I guess, on Windows, things are not exported to static link libraries unless explicitely asked by the source, and Python source does not do that.

**Comment by kayhayen** [comment]
I pushed a change to factory that should solve this. The specific part can be in hotfix in principle, but I don't think that's necessary.

**Comment by zegervdv** [comment]
I just tested with the factory branch and it works. Thanks for the quick fix!
I can wait for an official release, no hurry :)

**Comment by kayhayen** [comment]
MSYS2 is more under construction still, but I am getting 3.10 working, and so there will be a quick release anyway. The change is hotfix scope, i.e. no risk no conflict should happen, just a more general way of not doing it for Anaconda, but I think MSYS2 needs other changes only on develop maybe.

**Comment by kayhayen** [comment]
Ultimately I chose to avoid the risk, this will be on develop soon, it's building right now.

**Comment by kayhayen** [comment]
Oh, I was wrong, it's already in the hotfix release.
