### ISSUE TITLE
Infinite Looping on "mustNotHaveValue"

### ISSUE THREAD

**Issue by belonesox** [Nuitka/Nuitka#1324]
Let's consider sample program and nuitka call for compilation:
https://github.com/belonesox/nuitka-looping-mustNotHaveValue

* pipenv-based ``setup-demo.bat`` 
* on ``demo_cycling.bat`` we got infinite loop
```
File "C:\ta-buildroot\python-x86-3.7.9\lib\site-packages\nuitka\optimizations\ValueTraces.py", line 560, in mustNotHaveValue
    if not previous.mustNotHaveValue():
  File "C:\ta-buildroot\python-x86-3.7.9\lib\site-packages\nuitka\optimizations\ValueTraces.py", line 383, in mustNotHaveValue
    return self.previous.mustNotHaveValue()
  File "C:\ta-buildroot\python-x86-3.7.9\lib\site-packages\nuitka\optimizations\ValueTraces.py", line 560, in mustNotHaveValue
    if not previous.mustNotHaveValue():
  File "C:\ta-buildroot\python-x86-3.7.9\lib\site-packages\nuitka\optimizations\ValueTraces.py", line 383, in mustNotHaveValue
    return self.previous.mustNotHaveValue()
  File "C:\ta-buildroot\python-x86-3.7.9\lib\site-packages\nuitka\optimizations\ValueTraces.py", line 560, in mustNotHaveValue
    if not previous.mustNotHaveValue():
  File "C:\ta-buildroot\python-x86-3.7.9\lib\site-packages\nuitka\optimizations\ValueTraces.py", line 383, in mustNotHaveValue
    return self.previous.mustNotHaveValue()
  File "C:\ta-buildroot\python-x86-3.7.9\lib\site-packages\nuitka\optimizations\ValueTraces.py", line 560, in mustNotHaveValue
    if not previous.mustNotHaveValue():
  File "C:\ta-buildroot\python-x86-3.7.9\lib\site-packages\nuitka\optimizations\ValueTraces.py", line 383, in mustNotHaveValue
    return self.previous.mustNotHaveValue()
  File "C:\ta-buildroot\python-x86-3.7.9\lib\site-packages\nuitka\optimizations\ValueTraces.py", line 560, in mustNotHaveValue
    if not previous.mustNotHaveValue():
``` 

![image](https://user-images.githubusercontent.com/1609739/146686564-ec4ca994-408b-4f73-8953-c1ba2c35fbd3.png)

I reproduce it on Windows with ``python-x86-3.7.9`` and ``nuitka = "0.6.18.3"``, but I will try it on Linux and other versions of Nuitka.
Also I will try to simplify testcase

**Comment by kayhayen** [comment]
What do you mean with infinite looping, endlessly slow or actual recursion error from Python?

**Comment by kayhayen** [comment]
Can you try the factory version, I recently discovered that many merges are done that are not necessary, and will no longer be done, these would lead to merges of merges potentially as well, so that version would definitely perform better.

**Comment by belonesox** [comment]
> What do you mean with infinite looping, endlessly slow or actual recursion error from Python?

«endlessly slow»

Then I interrupt process (on debugging or Ctrl-C), I get such stack and variables (something wrong about "sklearn")

**Comment by belonesox** [comment]
> Can you try the factory version,

Yes, I will try all this. I also will try it on different versions of python and on Linux (may be something wrong with my 3.7.9, even on pipenv, I should check on clear box).

**Comment by belonesox** [comment]
With factory branch 
(demo https://github.com/belonesox/nuitka-looping-mustNotHaveValue/tree/07a26e53c4819c9dcbcd77a8f8252bef5f7526e6 )

I got crash
```
Nuitka:INFO: Total memory usage before generating C code: 653.21 MB (684941312 bytes):
Problem with <Node 'EXPRESSION_BUILTIN_ANONYMOUS_REF' with {'builtin_name': 'version_info'}> at c:\users\stas\.virtualenvs\nuitka-looping-mustnothavevalue-dc8w5ryp\src\nuitka\nuitka\constants\Serialization.py:119
Problem with <Node 'STATEMENT_ASSIGNMENT_SUBSCRIPT'> at c:\users\stas\.virtualenvs\nuitka-looping-mustnothavevalue-dc8w5ryp\src\nuitka\nuitka\constants\Serialization.py:119
Problem with <Node 'STATEMENT_TRY' with {'aborting': True}> at c:\users\stas\.virtualenvs\nuitka-looping-mustnothavevalue-dc8w5ryp\src\nuitka\nuitka\constants\Serialization.py:102
Nuitka:WARNING: Problem creating function code 'nuitka$constants$Serialization$$$function__8___init__'.
Traceback (most recent call last):
  File "c:\users\stas\.virtualenvs\nuitka-looping-mustnothavevalue-dc8w5ryp\src\nuitka\nuitka\__main__.py", line 137, in <module>
    main()
  File "c:\users\stas\.virtualenvs\nuitka-looping-mustnothavevalue-dc8w5ryp\src\nuitka\nuitka\__main__.py", line 123, in main
    MainControl.main()
  File "c:\users\stas\.virtualenvs\nuitka-looping-mustnothavevalue-dc8w5ryp\src\nuitka\nuitka\MainControl.py", line 915, in main
    result, options = compileTree()
  File "c:\users\stas\.virtualenvs\nuitka-looping-mustnothavevalue-dc8w5ryp\src\nuitka\nuitka\MainControl.py", line 784, in compileTree
```
[build.log](https://github.com/Nuitka/Nuitka/files/7741647/build.log)

**Comment by belonesox** [comment]
Same "factory crash" on linux
https://github.com/belonesox/nuitka-looping-mustNotHaveValue/tree/6336ea80ea9b96a757592d7547d63139fe66edb9 
```
setup-demo.sh
demo_cycling.sh
```
↓↓↓
[build.log](https://github.com/Nuitka/Nuitka/files/7741749/build.log)

**Comment by belonesox** [comment]
About «infinite looping», on windows/python 3.8.10, demo  → https://github.com/belonesox/nuitka-looping-mustNotHaveValue/tree/windows-python-3.8.10

* On 0.6.16.4 — no looping, OK
* On >=0.6.17.1 — looping exists.

**Comment by kayhayen** [comment]
So, this doesn't affect current stable version then?

**Comment by belonesox** [comment]
It Affects!
0.6.18.3 >= version >=0.6.17.0 — looping exists.

Including «0.6.18.3» (current stable?!) and «0.6.17.0», but not including «0.6.16.4»

**Comment by kayhayen** [comment]
It seems your factory crash is on compiling Nuitka code?!. Does your code import `nuitka` somehow?

**Comment by kayhayen** [comment]
also, from looking at the command, you really want the anti-bloat plugin, and maybe you want to add a rule to the command line that makes it error out on importing `nuitka`` so you can tell where it is coming from.

**Comment by belonesox** [comment]
> It seems your factory crash is on compiling Nuitka code?!. Does your code import `nuitka` somehow?

Please, look
* https://github.com/belonesox/nuitka-looping-mustNotHaveValue/tree/windows-python-3.8.10 — reproduce on Windows
* https://github.com/belonesox/nuitka-looping-mustNotHaveValue/tree/linux-python-3.9.7 — reproduce on Linux

There is no nuitka imports in «test.py»
I did not call anti-bloat plugin in ``demo-cycling``

**Comment by kayhayen** [comment]
The new compilation report feature would be handy, I checked you log, and I am seeing this:

```
:INFO: Optimizing module 'setup', 184 more modules to go after that.
:INFO: Doing module local optimizations for 'setup'.
:INFO: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements,trusted_module_variables,var_usage
:INFO: Not finished with the module due to following change kinds: loop_analysis,new_builtin,new_builtin_ref,new_constant,new_expression,new_statements,var_usage
:INFO: Not finished with the module due to following change kinds: loop_analysis,new_expression,new_statements
:INFO: Not finished with the module due to following change kinds: loop_analysis
:INFO: Not finished with the module due to following change kinds: loop_analysis
:INFO: No changed, but retrying one more time.
:INFO: Finished with the module.
:INFO: Optimizing module 'nuitka.PythonFlavors', 184 more modules to go after that.
```

So it seems something is causing an import of `setup` which ends up being the one from Nuitka, probably being in your current directory. Your scripts are full of absolute paths, I don't think I will see, what you saw there easily. Maybe it's shadowing something. Nuitka has started to use Nuitka code in its `setup.py`, which is why you have that. You probably also have issues stable from that. With the anti-bloat plugin, you could find the module that imports `setup`.

Also the compilation report feature should come in handy, it lists the imports of a module, but not in detail yet, but I can change that. And it would have showed the same, namely setup importing Nuitka, and then what imports setup, we cannot know.

Since factory has the crash fixed, you might actually get that report. However, compilation needs to finish for it to exists, which is why anti-bloat command line options are probably best to find it.

**Comment by belonesox** [comment]
> I have no idea what makes you import nuitka there, that seems rather grave. I have not yet attempted reproduction though, but I am hoping that nothing in Nuitka makes Nuitka go into itself there.

Please, try to reproduce, using my link above.
Since first comment, I do a lot of minimizing, and now there are nothing about "nuitka.PythonFlavors" or "anti-bloat" in logs.
[build.log](https://github.com/Nuitka/Nuitka/files/7757265/build.log)

**Comment by kayhayen** [comment]
This is during code generation, that one has never so far had any such issues. You interrupted it, are you saying it takes very long time? Anyway, I am trying to reproduce it now, discovering that the anti-bloat plugin has not seen `sklearn.utils._testing` before, which is an indication that I at least have not compiled this part of `sklearn`, or not this version.

**Comment by belonesox** [comment]
> You interrupted it, are you saying it takes very long time? 

More that 12 hours, sometimes I run it all night without ending.

**Comment by kayhayen** [comment]
It finished for me in definitely less than one hour, I am using `--enable-plugin=anti-bloat --noinclude-default-mode=error`, I think you never got my anti-bloat references, but it reduces the compilation by a lot. It took me max 30 minutes, I didn't check closely.

I am suspecting you are reaching a low memory situation which can make things slow. Still with anti-bloat, 2k modules are compiled, which is borderline, but there is a lot that anti-bloat doesn't do yet.

I have had to find and fix a regression in the generated C code for a string operation, therefore I don't know if it runs at all, but I think it ought to. But with these large compilations I am waiting for more anti-bloat work to happen over time.

**Comment by belonesox** [comment]
Your proposed option `` --noinclude-default-mode=error`` does the magic:
* with it my test case finished OK
* without it, this test case hanged.

I never use the option, but now I see that if  my code includes for example
```
from setuptools import setup as old_setup
```

it failed with 
```
Nuitka-Progress:INFO: Doing module local optimizations for 'numpy.distutils.core'.
Problem with statement at C:\Users\stas\.virtualenvs\nuitka-looping-mustNotHaveValue-MGvTvGQE\lib\site-packages\numpy\distutils\core.py:6:
->     from setuptools import setup as old_setup

Problem with statement at C:\Users\stas\.virtualenvs\nuitka-looping-mustNotHaveValue-MGvTvGQE\lib\site-packages\numpy\distutils\core.py:4:
-> if 'setuptools' in sys.modules:

FATAL: Error, forbidden import 'setuptools' encountered.
```

**Comment by kayhayen** [comment]
I think you should outlaw `numpy.distutils.core` already. I think in anti-bloat I have made a couple of packages avoid that. That is a distutils clone, that basically explodes dependencies all around. Can you use the custom mode to track this down?

**Comment by belonesox** [comment]
I have tried 
``
--enable-plugin=anti-bloat --noinclude-default-mode=error --noinclude-custom-mode=setuptools:nofollow
``
it leads to this looping.

I tried to track who "is called setuptools" (I thought that «--graph» option suits this, but, obviously, it does not work for that, see  #1341).

I think  there should be some debug print, like
```
def onModuleOptimizationStep(module):
    # Update the graph if active.
    print("onModuleOptimizationStep", module)
```
to track down what module leeds to «FATAL: Error, forbidden import 'XXXXXX' encountered.»

I tracked down to some subpackages of  «scipy.special» (my project really needed it), 
have tried a lot of magic like "--include-package=XXX" + "--nofollow-import-to=XXX"
and …  still have «infinite looping» even with «--enable-plugin=anti-bloat --noinclude-default-mode=error »

```
python.exe -m pipenv run python -m nuitka  --show-scons --windows-disable-console --standalone --show-progress --plugin-enable=numpy  --enable-plugin=anti-bloat --noinclude-default-mode=error --include-package=scipy.special --include-module=scipy.special.cython_special --nofollow-import-to=scipy.special --include-module=skimage.feature._orb_descriptor_positions --include-module=scipy.spatial.transform._rotation_groups  --follow-imports --include-module=scipy.spatial.transform._rotation_groups test.py >build.log 2>&1
```
↓↓↓↓
[build.log](https://github.com/Nuitka/Nuitka/files/7776055/build.log)

( https://github.com/belonesox/nuitka-looping-mustNotHaveValue/tree/windows-python-3.8.10 )

What else should I try?

**Comment by kayhayen** [comment]
I would also say that the memory usage reported, 367MB is not too bad given the 2k modules.

I will add traces, such that it reports the module you interrupted code generation on. It should be interesting to see if there is one that is particularily bad.

**Comment by kayhayen** [comment]
Please retry with current factory branch and see if it is the same module all the time for you. Then of course let us know which one it is. :)

**Comment by belonesox** [comment]
about current factory brach… It takes a lot of time to work with my project with "--noinclude-default-mode=error --enable-plugin=anti-bloat"
(because of "--nofollow-import-to=scipy.special" I have to catch all needed modules manually, after long cycles of build-run-"no-module found"). Then, back, trying to minimize a problem case… 

Now I have a demo

https://github.com/belonesox/nuitka-looping-mustNotHaveValue/tree/windows-python-3.7.9

* trivial python file 
```
https://github.com/belonesox/nuitka-looping-mustNotHaveValue/blob/windows-python-3.7.9/test.py
```

* build  https://github.com/belonesox/nuitka-looping-mustNotHaveValue/blob/windows-python-3.7.9/build-wtf-with-sf-error.bat
(mind «--include-module=scipy.special.sf_error» in the options) without problems 
[build-log.zip](https://github.com/Nuitka/Nuitka/files/7787730/build-log.zip)


* but "ModuleNotFoundError: No module named 'scipy.special.sf_error'" when we run (providing all needed DLLS)
```
Traceback (most recent call last):
  File "C:\projects\nuitka\3.79\NUITKA~1\TEST~1.DIS\test.py", line 3, in <module>
  File "C:\projects\nuitka\3.79\NUITKA~1\TEST~1.DIS\sklearn\__init__.py", line 82, in <module sklearn>
  File "C:\projects\nuitka\3.79\NUITKA~1\TEST~1.DIS\sklearn\base.py", line 17, in <module sklearn.base>
  File "C:\projects\nuitka\3.79\NUITKA~1\TEST~1.DIS\sklearn\utils\__init__.py", line 28, in <module sklearn.utils>
  File "C:\projects\nuitka\3.79\NUITKA~1\TEST~1.DIS\sklearn\utils\fixes.py", line 20, in <module sklearn.utils.fixes>
  File "C:\projects\nuitka\3.79\NUITKA~1\TEST~1.DIS\scipy\stats\__init__.py", line 441, in <module scipy.stats>
  File "C:\projects\nuitka\3.79\NUITKA~1\TEST~1.DIS\scipy\stats\stats.py", line 37, in <module scipy.stats.stats>
  File "C:\projects\nuitka\3.79\NUITKA~1\TEST~1.DIS\scipy\spatial\__init__.py", line 102, in <module scipy.spatial>
  File "C:\projects\nuitka\3.79\NUITKA~1\TEST~1.DIS\scipy\spatial\_geometric_slerp.py", line 8, in <module scipy.spatial._geometric_slerp>
  File "C:\projects\nuitka\3.79\NUITKA~1\TEST~1.DIS\scipy\spatial\distance.py", line 124, in <module scipy.spatial.distance>
  File "C:\projects\nuitka\3.79\NUITKA~1\TEST~1.DIS\scipy\special\__init__.py", line 641, in <module scipy.special>
ModuleNotFoundError: No module named 'scipy.special.sf_error'
```

**Comment by kayhayen** [comment]
It seems that sklearn needs a treatment like numpy for libraries, since I mostly use Linux, I never encountered this, should be easy to add. Otherwise, are you saying you are getting 'scipy.special.sf_error' after using `--nofollow-import-to=scipy.special` ?

I was wondering, if Nuitka should not start to treat these `ModuleNotFoundError` that escape the main program as an unhandled exception. I could include code that tells you WHY this is not not inlcuded. I will admit that the workflow you are using there is tedious.

Do yourself a favor and start using "nuitka-project" options in a file, it becomes way more readable. It took me 3 attempts to check if it's there. With project options they are in the Python file and easier to read and enable/disable. If you don't mind a small wait, let this case untouched, and I will try and make it output a nice error, and make your copy of MSVC libraries unnecessary, ok?

**Comment by belonesox** [comment]
>It seems that sklearn needs a treatment like numpy for libraries, since I mostly use Linux, I never encountered this, should >be easy to add. 

May be I should provide publicly available VPS with windows, that you can use to reproduce such bugs? Should it help?

>Otherwise, are you saying you are getting 'scipy.special.sf_error' after using --nofollow-import-to=scipy.special ?

Roger that.
My nuitka options: https://github.com/belonesox/nuitka-looping-mustNotHaveValue/blob/windows-python-3.7.9/build-wtf-with-sf-error.bat
As far as I know «--nofollow-import-to=XXX» + «--include-module=XXX.yyy» is the only option for me.

>Do yourself a favor and start using "nuitka-project" options in a file, it becomes way more readable.

In my workflow, all these options are generated from some YAML files, so I missed that option, I will learn it and use it for demo bugs.

**Comment by kayhayen** [comment]
Ah ok, I didn't see if you have both, too hard too read this shit.

**Comment by belonesox** [comment]
Just tested on 
```
   nuitka = "0.6.19.7"
   python_version = "3.9"
```
on windows and linux, there is no "infinite looping" anymore. 
So the bug can be closed.

Some other issues I will investigate and report by separately.

**Comment by kayhayen** [comment]
Good, you didn't notice that 0.7 is out since today. :)
