### ISSUE TITLE
Killed signal terminated program lto1

### ISSUE THREAD

**Issue by jhawgs** [Nuitka/Nuitka#1326]
# Basic Info
* Nuitka version

  > $ python -m nuitka --version
0.6.18.4
Commercial: None
Python: 3.9.2 (default, Feb 28 2021, 17:03:44) 
Flavor: Debian Python
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
Distribution: Debian "11

    (note: this is in the latest Ubuntu docker container run on macOS)

* Installed with pip

* Full package list

  > $ python -m pip freeze
altair==4.1.0
argon2-cffi==21.1.0
astor==0.8.1
async-generator==1.10
attrs==21.2.0
backcall==0.2.0
base58==2.1.0
bleach==4.1.0
blinker==1.4
cachetools==4.2.4
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.7
click==7.1.2
colorama==0.4.4
configparser==5.0.2
crayons==0.4.0
cryptography==35.0.0
cycler==0.11.0
debugpy==1.5.1
decorator==5.1.0
defusedxml==0.7.1
EasyProcess==0.3
entrypoints==0.3
Flask==2.0.2
gitdb==4.0.9
GitPython==3.1.24
h11==0.12.0
idna==3.3
ipykernel==6.4.2
ipython==7.29.0
ipython-genutils==0.2.0
ipywidgets==7.6.5
itsdangerous==2.0.1
jedi==0.18.0
Jinja2==3.0.2
jsonschema==4.1.2
jupyter-client==7.0.6
jupyter-core==4.9.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.2
kiwisolver==1.3.2
MarkupSafe==2.0.1
matplotlib==3.4.3
matplotlib-inline==0.1.3
mistune==0.8.4
nbclient==0.5.4
nbconvert==6.2.0
nbformat==5.1.3
nest-asyncio==1.5.1
notebook==6.4.5
Nuitka==0.6.18.4
numpy==1.21.3
outcome==1.1.0
packaging==21.2
pandas==1.3.4
pandocfilters==1.5.0
parse==1.19.0
parso==0.8.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.4.0
prometheus-client==0.12.0
prompt-toolkit==3.0.21
protobuf==3.19.1
ptyprocess==0.7.0
pyarrow==6.0.0
pycparser==2.20
pydeck==0.7.1
Pygments==2.10.0
pyOpenSSL==21.0.0
pyparsing==2.4.7
pyrsistent==0.18.0
python-dateutil==2.8.2
python-stopwatch==1.0.1
pytz==2021.3
pytz-deprecation-shim==0.1.0.post0
PyVirtualDisplay==2.2
pyzmq==22.3.0
requests==2.26.0
selenium==4.0.0b4
selenium-stealth==1.0.6
Send2Trash==1.8.0
six==1.16.0
smmap==5.0.0
sniffio==1.2.0
sortedcontainers==2.4.0
streamlit==1.1.0
termcolor==1.1.0
terminado==0.12.1
testpath==0.5.0
toml==0.10.2
toolz==0.11.1
tornado==6.1
tqdm==4.62.3
traitlets==5.1.1
trio==0.19.0
trio-websocket==0.9.2
typing-extensions==3.10.0.2
tzdata==2021.5
tzlocal==4.1
undetected-chromedriver==3.0.3
urllib3==1.26.7
validators==0.18.2
watchdog==2.1.6
wcwidth==0.2.5
webdriver-manager==3.5.1
webencodings==0.5.1
websockets==10.0
Werkzeug==2.0.2
wget==3.2
widgetsnbextension==3.5.2
wsproto==1.0.0
xvfbwrapper==0.2.9
youtube-transcript-api==0.4.1

* Simple hello world compiles and runs

* Command used (with options)

  > $ python3 -m nuitka ntest.py --warn-unusual-code --standalone --plugin-enable=numpy --plugin-enable=pylint-warnings --include-package-data selenium --assume-yes-for-downloads --show-progress --verbose --warn-implicit-exceptions --show-scons

*  Not sure whether the issue is a regression from an older version of Nuitka. The program, however, compiles fine and runs when compiled on macOS. I am trying to compile in the latest Ubuntu docker container for distribution.

# Reproduction and Detail
As I stated earlier, this project compiles and runs on macOS but not when brought to the Linux container, which is particularly puzzling to me. I have not been able to reproduce the error without compiling the full project, which is quite large.

The full output is almost 500,000 lines, so I won't provide it right now, but I am happy to later if it would be helpful. I will walk through the relevant parts of the output here.

I run the command shown above: `python3 -m nuitka ntest.py --warn-unusual-code --standalone --plugin-enable=numpy --plugin-enable=pylint-warnings --include-package-data selenium --assume-yes-for-downloads --show-progress --verbose --warn-implicit-exceptions --show-scons`.

This makes it through the entire process in the Linux container until Nuitka tries to compile the final binary at `ntest.dist/ntest` with the following command: `gcc -o /s/ntest.dist/ntest -fuse-linker-plugin -flto=2 -fpartial-inlining -freorder-functions -O2 -O2 -z noexecstack -s -Wl,-R,'$ORIGIN' -Wl,--disable-new-dtags -Wl,-b -Wl,binary -Wl,./__constants.bin -Wl,-b -Wl,elf64-x86-64 -Wl,-defsym -Wl,constant_bin_data=_binary_____constants_bin_start @"./@link_input.txt" -L/usr/lib -ldl -lm -lpython3.9`. Nuitka only says `Killed` then terminates with error code `1`.

To get more information about the error straight from gcc, I ran the problematic compilation manually as shown below:
```
$ gcc -o /s/ntest.dist/ntest -fuse-linker-plugin -flto=2 -fpartial-inlining -freorder-functions -O2 -O2 -z noexecstack -s -Wl,-R,'$ORIGIN' -Wl,--disable-new-dtags -Wl,-b -Wl,binary -Wl,./__constants.bin -Wl,-b -Wl,elf64-x86-64 -Wl,-defsym -Wl,constant_bin_data=_binary_____constants_bin_start @"./@link_input.txt" -L/usr/lib -ldl -lm -lpython3.9
gcc: fatal error: Killed signal terminated program lto1
compilation terminated.
lto-wrapper: fatal error: gcc returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
```

I have thoroughly googled these errors, and the messages seem to be very general. I also searched through Nuitka discussions and issues, and found nothing about these issues.

In the mean time, I plan on continuing to search for a solution, and I will update this post with new developments. Until then, I hope your expertise might at least shed some more light on the issue. Thanks for your help in advance.

**Comment by kayhayen** [comment]
This is an out of memory problem of your C compiler. Check out https://nuitka.net/doc/user-manual.html#memory-issues-and-compiler-bugs
