### ISSUE TITLE
nuitka missing implicit dependencies for bottle. again

### ISSUE THREAD

**Issue by ratabomb** [Nuitka/Nuitka#1327]
compiling a program with eel results in this error when starting exe:
![image](https://user-images.githubusercontent.com/75296588/146727132-1a47a443-fec7-436f-b878-6d3b72967d26.png)
the same error was in my previous issue #1225 (https://github.com/Nuitka/Nuitka/issues/1225#issuecomment-950391789), but in factory it worked well. then i changed my pc and downloaded stable release, and it broke again. :(

python version: Python 3.9.7
nuitka version: 0.6.18, 0.6.18.1, 0.6.18.4 (tested these versions and they are resulting the same error)
eel version: 0.14.0 (latest)
pip freeze: https://pastebin.com/LHcLTX3q

**Comment by kayhayen** [comment]
You are correct, I am reoping the old isssue though, there was a typo made in a later cleanup it seems.
