### ISSUE TITLE
[Question] Build via nuitka using pyenv on linux, but from a non-standard temp location giving libpython-static error when the shared objects are present.

### ISSUE THREAD

**Issue by MostHated** [Nuitka/Nuitka#1328]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

python -m nuitka --version (though, the build script in question simply performs a pip install nuitka at the time of running, so the version would be whatever that happens to be at the time)
0.6.18.3
Commercial: None
Python: 3.9.9 (main, Nov 21 2021, 14:06:38)
Flavor: pyenv
Executable: /home/mosthated/.pyenv/versions/3.9.9/bin/python
OS: Linux
Arch: x86_64
Distribution: Pop "21.10"

* How did you install Nuitka and Python

Hello, I am attempting to build using nuitka using pyenv on linux, but from a non-standard location (making a build script that temp installs everything in the current location). I have all of the pyenv env variables set that would need to be, and I have the python shared object files present in the python lib folder from installing with the `"--enable-shared"` flag set (`libpython3.9.so`, `libpython3.9.so.1.0`, `libpython3.so`), but when attempting to run, I always get "FATAL: Error, usable static libpython is not found for this Python installation. You might be missing required '-dev' packages. Disable with `--static-libpython=no`" if you don't want to install it.". 

I am fairly sure I have all of the necessary packages I would need from apt, such as python3.9-dev, libpython3.9-dev, etc, etc. I must be missing something else? Is there some additional environmental var for nuitka that is needed that I might be unaware of?

I also made sure the lib and bin folders were on $PATH, and out of "might as well, nothing else seems to be working" I also tried setting things such as:
```sh
export LD_LIBRARY_PATH="${PYENV}/versions/${PYENVRELEASE}/lib"
export LDFLAGS="-Wl,--rpath=${PYENV}/versions/${PYENVRELEASE}/lib"
```

Those were only recent, though, and didn't seem to offer any sort of change, be it positive or negative.

I am getting this same behavior on Windows, when attempting to build using the same setup. The build script was originally python and so on Windows, I rewrote it in Powershell, just in case it had something to do with trying to use a minimal shell env, thinking python was part of the problem trying to get the variables I was setting into the subprocess shell, but there was no change in the end result. I thought perhaps it was an issue with Windows, so on Linux I rewrote the build script in just bash, but again, same end result, unfortunately.

It actually builds just fine if I go and set `--static-libpython=no`, but I am hoping to not have to do that. Any insight would be greatly appreciated.

**Comment by kayhayen** [comment]
You should not  use `--enable-shared`, Nuitka produces better binaries if you do not. The pyenv support is not really finished yet, but there are changes coming, that will tell Anaconda, pyenv and potentially others what to do in more detail.

**Comment by kayhayen** [comment]
You should not  use `--enable-shared`, Nuitka produces better binaries if you do not. The pyenv support is not really finished yet, but there are changes coming, that will tell Anaconda, pyenv and potentially others what to do in more detail.

**Comment by kayhayen** [comment]
In an unrelated note, I have finally added specific messages per Python flavor, you are welcome to tell me if https://nuitka.net/doc/factory.html works better for you.

**Comment by MostHated** [comment]
Ok, nice, I will give it a try as soon as I get a chance this afternoon.
