### ISSUE TITLE
Question: Can I disable interactive Mode (--assume-no-for-downloads?)

### ISSUE THREAD

**Issue by levesquejf** [Nuitka/Nuitka#1335]
I try to add Nuitka to a new CI/CD pipeline. I can not use `--assume-yes-for-downloads` because of permission issues so I get stuck at the ccache download prompt:

```
No installer needed, cached, one time question.

Proceed and download? [Yes]/No
```

Would it be possible to add a `--assume-no-for-downloads` option?

It's running on macOS.

**Comment by kayhayen** [comment]
There are two obvious solutions, first is to to not have stdin, `</dev/null`, the other is to make it `yes no`, which will output as many "no" responses as you want, not sure if macOS has that.

I will admit this is not obvious, should add something to help output.

**Comment by levesquejf** [comment]
`< /dev/null` is working fine, thanks @kayhayen!
