### ISSUE TITLE
GPG Signing Key expired 2021-12-17

### ISSUE THREAD

**Issue by kevsgithub** [Nuitka/Nuitka#1336]
Failed to fetch http://nuitka.net/deb/stable/bionic/dists/bionic/InRelease  The following signatures were invalid: EXPKEYSIG 1BFC33752912B99C Kay Hayen <kay.hayen@gmail.com>

Hi, 
Your Debian/Ubuntu Signing Key has expired.
Thanks :+1:

**Comment by kayhayen** [comment]
I have a new one, just need to figure out where to put it again

**Comment by kayhayen** [comment]
Ok, I got the signature extended, I think `reprepro` copies it, not sure now, if maybe it expired in the mean time, I was noticing it when preparing a hotfix.

**Comment by kayhayen** [comment]
It seems, bionic was built on 16.12, i.e. when the key was still valid, so this will be fixed on rebuild. I will trigger one to see if it helps.

**Comment by kayhayen** [comment]
The key changed from the rebuild, so I assume all it takes is a hotfix to come. I will trigger a rebuild the stable debian packages manually though, as it might not happen so soon.

**Comment by kevsgithub** [comment]
HI, still shows as expired.

wget -O - http://nuitka.net/deb/archive.key.gpg | gpg

**Comment by kayhayen** [comment]
I saw it, I wonder why it's used, isn't the directories below there independent repos?

**Comment by kayhayen** [comment]
I get it, the website uses it in the instructions. I forgot. I updated it to what it ought to be, my relevant CI server is in maintenance, but website should soon point out proper per distribution keys

**Comment by kayhayen** [comment]
Now reads `wget -O - http://nuitka.net/deb/stable/$CODENAME/dists/$CODENAME/Release.gpg | apt-key add -`

**Comment by kevsgithub** [comment]
it may be me, or things haven't updated yet. (Website still has old instructions).

`wget -O - http://nuitka.net/deb/stable/bionic/dists/bionic/Release.gpg | apt-key add -
--2021-12-22 19:46:01--  http://nuitka.net/deb/stable/bionic/dists/bionic/Release.gpg
Resolving nuitka.net (nuitka.net)... 116.202.30.188, 64:ff9b::74ca:1ebc
Connecting to nuitka.net (nuitka.net)|116.202.30.188|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://nuitka.net/deb/stable/bionic/dists/bionic/Release.gpg [following]
--2021-12-22 19:46:02--  https://nuitka.net/deb/stable/bionic/dists/bionic/Release.gpg
Connecting to nuitka.net (nuitka.net)|116.202.30.188|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 833
Saving to: ‘STDOUT’

-                                                           100%[==========================================================================================================================================>]     833  --.-KB/s    in 0s      

2021-12-22 19:46:04 (23.3 MB/s) - written to stdout [833/833]

gpg: no valid OpenPGP data found.`

`wget -O - http://nuitka.net/deb/stable/bionic/dists/bionic/Release.gpg | gpg
--2021-12-22 19:46:38--  http://nuitka.net/deb/stable/bionic/dists/bionic/Release.gpg
Resolving nuitka.net (nuitka.net)... 116.202.30.188, 64:ff9b::74ca:1ebc
Connecting to nuitka.net (nuitka.net)|116.202.30.188|:80... gpg: WARNING: no command supplied.  Trying to guess what you mean ...
connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://nuitka.net/deb/stable/bionic/dists/bionic/Release.gpg [following]
--2021-12-22 19:46:41--  https://nuitka.net/deb/stable/bionic/dists/bionic/Release.gpg
Connecting to nuitka.net (nuitka.net)|116.202.30.188|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 833
Saving to: ‘STDOUT’

-                                                           100%[==========================================================================================================================================>]     833  --.-KB/s    in 0s      

2021-12-22 19:46:43 (30.8 MB/s) - written to stdout [833/833]

Detached signature.`

Detached signature is weird. Previously it would list expirery etc.

**Comment by kayhayen** [comment]
So, I reverted to old instructions, and placed the key there. I think I know now why it's not automated, I never found out how ansible executes a local command and outputs it remotely, at least I now made a comment so next time I know how to update it, should work now?

**Comment by kevsgithub** [comment]
Just so that you are aware, your sub key is still expired. I don't believe this will cause any problems, but I've held off importing your key in case you wanted to fix this.
Signing and Cert Key looks good.
Encryption sub key still expired.

wget -O - http://nuitka.net/deb/archive.key.gpg | gpg
pub   rsa4096 2013-11-10 [SC] [expires: 2023-12-18]
      D96ADCA1377F1CEB6B5103F11BFC33752912B99C
uid           Kay Hayen <kay.hayen@gmail.com>
sub   rsa4096 2013-11-10 [E] [expired: 2021-12-17]

**Comment by kayhayen** [comment]
Nah, it works, that is what matters. Interestingly last time I managed to update it, but I don't think the subkey is used, or maybe no more, because it is expired, but gpg has no good interface and I don't care enough now.

**Comment by kayhayen** [comment]
I think what I do need however, is a kind of automatic test that checks periodically if the packages still install. It's a shame to not have that tested.
