### ISSUE TITLE
How to get web3/eth-hash to see pysha3 or pycryptodome?

### ISSUE THREAD

**Issue by ratabomb** [Nuitka/Nuitka#1337]
trying to use eth-hash:
```
..................................
File "C:\Users\Vista\AppData\Local\Temp\ON1417~1\eth_hash\main.py", line 41, in __call__
  File "C:\Users\Vista\AppData\Local\Temp\ON1417~1\eth_hash\main.py", line 26, in _hasher_first_run
  File "C:\Users\Vista\AppData\Local\Temp\ON1417~1\eth_hash\backends\auto.py", line 24, in keccak256
  File "C:\Users\Vista\AppData\Local\Temp\ON1417~1\eth_hash\backends\auto.py", line 17, in _initialize
  File "C:\Users\Vista\AppData\Local\Temp\ON1417~1\eth_hash\utils.py", line 19, in auto_choose_backend
  File "C:\Users\Vista\AppData\Local\Temp\ON1417~1\eth_hash\utils.py", line 73, in choose_available_backend
ImportError: None of these hashing backends are installed: ['pycryptodome', 'pysha3'].
Install with `pip install eth-hash[pycryptodome]`. 
```
pip freeze contains these libraries:
pycryptodome==3.11.0
pysha3==1.0.2

nuitka version: 
```
0.6.18.5
Commercial: None
Python: 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\Vista\AppData\Local\Programs\Python\Python39\python.exe
OS: Windows
Arch: x86_64
```

i told you about this issue #1225 , but you deleted these comments because it was not necessary with main issue, but problem is still exists.

**Comment by kayhayen** [comment]
You need Nuitka-commercial for this, it has a plugin that solves the backend issues.

**Comment by kayhayen** [comment]
Leaving this open, as this is one of the many cases, where Nuitka commercial is not documented to do this, and Nuitka gives no warning that it should be used instead.

**Comment by ratabomb** [comment]
i still can't get what to do with it to fix it. am i required to buy a nuitka commercial just to use one library?

**Comment by kayhayen** [comment]
@ratabomb yes, exactly, this is under the assumption that you are using it for commercial software, which seems very unlikely. So I am seeking compensation for my time spent on things that do Visa payments, Bitcoin, etc.

**Comment by ratabomb** [comment]
> @ratabomb yes, exactly, this is under the assumption that you are using it for commercial software, which seems very likely. So I am seeking compensation for my time spent on things that do Visa payments, Bitcoin, etc.

answer me on email

**Comment by kayhayen** [comment]
This is now documented at https://nuitka.net/doc/commercial/commercial-only-packages.html
