### ISSUE TITLE
Python 2 gcc MatplotlibUsing.py triggers -Werror=unused-but-set-variable

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#1338]
Occurring on v0.6.18.5 openSUSE 15.2 builds , on gcc only, and likely Python 2 only.  (clang without debug passed; clang with debug ongoing..)

* The specific PyPI names and versions

python2-matplotlib-2.2.5-lp152.2.3.1

* Provide in your issue the Nuitka options used

This had `--debug` enabled.

* Note if this is a regression

Not sure as https://github.com/Nuitka/Nuitka/issues/1298 prevented testing in earlier versions.

```
[ 1695s] Consider output of standalone mode compiled program: MatplotlibUsing.py
[ 1695s] Comparing output of 'MatplotlibUsing.py' using '/usr/bin/python2' with flags silent, expect_success, --standalone, remove_output, cpython_cache, timing, ignore_warnings ...
[ 2092s] --- /usr/bin/python2 (stdout)
[ 2092s] +++ nuitka (stdout)
[ 2092s] 
[ 2092s] @@ -1,2 +1 @@
[ 2092s] 
[ 2092s] -OK.
[ 2092s]  
[ 2092s] --- /usr/bin/python2 (stderr)
[ 2092s] +++ nuitka (stderr)
[ 2092s] 
[ 2092s] @@ -1 +1,7 @@
[ 2092s] 
[ 2092s] +module.pyparsing.c: In function 'impl_pyparsing$$$function__90_parseString':
[ 2092s] +module.pyparsing.c:53841:17: error: variable 'tmp_try_except_1__unhandled_indicator' set but not used [-Werror=unused-but-set-variable]
[ 2092s] +     nuitka_bool tmp_try_except_1__unhandled_indicator = NUITKA_BOOL_UNASSIGNED;
[ 2092s] +                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 2092s] +cc1: all warnings being treated as errors
[ 2092s] +scons: *** [module.pyparsing.o] Error 1
[ 2092s]  
[ 2092s] Updating CPython cache by force due to non-matching comparison results.
[ 2092s] --- /usr/bin/python2 (stdout)
[ 2092s] +++ nuitka (stdout)
[ 2092s] 
[ 2092s] @@ -1,2 +1 @@
[ 2092s] 
[ 2092s] -OK.
[ 2092s]  
[ 2092s] --- /usr/bin/python2 (stderr)
[ 2092s] +++ nuitka (stderr)
[ 2092s] 
[ 2092s] @@ -1 +1,7 @@
[ 2092s] 
[ 2092s] +module.pyparsing.c: In function 'impl_pyparsing$$$function__90_parseString':
[ 2092s] +module.pyparsing.c:53841:17: error: variable 'tmp_try_except_1__unhandled_indicator' set but not used [-Werror=unused-but-set-variable]
[ 2092s] +     nuitka_bool tmp_try_except_1__unhandled_indicator = NUITKA_BOOL_UNASSIGNED;
[ 2092s] +                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 2092s] +cc1: all warnings being treated as errors
[ 2092s] +scons: *** [module.pyparsing.o] Error 1
[ 2092s]  
[ 2092s] Exit codes 0 (CPython) != 1 (Nuitka)
```

**Comment by kayhayen** [comment]
Oh, that's an interesting report. I will look into it. The module name is one that I believe is fequently compiled, it would be more interesting to know the pyparsing version, but since we are talking Python2, it's pretty likely just the latest one working for it, right?

**Comment by kayhayen** [comment]
btw, if you have like a set of things, e.g. a podman usable file to spin up somelike like a VM to reproduce openSUSE things, I would be super cool with that too.

**Comment by kayhayen** [comment]
ok, and I managed to reproduce it on stable version, but not on develop. I will try and bisect things, and see if the fix is something I should backport.

**Comment by kayhayen** [comment]
in the 0.6.19 release cycle, optimization for merges, loop variables, escaping and all got much better, so I think I know that this is something I had in fact triggered myself in other code, sometimes unused variables were not forward propagated because of being used in merges, and that is no longer relevant, which is why the new version won't have it. I thinking it won't be backportable at all. But there will be a new release this week anyway, probably within days even.

**Comment by kayhayen** [comment]
Somehow git biset is letting me down in new ways, I cannot git biset from master to develop branch, because they have no common base, and when I did it from 0.6.18 tag to develop, it gave up and listed a whole range of commits, because a merge base was bad. Now that's strange, never had that before. Maybe some rebase of mine has gone wrong, or git improved somehow to find out that I am doing bisects the wrong way. Anyway, I think this is something to be considered solved with next release. No way can I backport new optimization, as they uncover too many other wrong things as well, some of which got hotfixed already, but there will be regressions from that.

**Comment by jayvdb** [comment]
> btw, if you have like a set of things, e.g. a podman usable file to spin up somelike like a VM to reproduce openSUSE things, I would be super cool with that too.

best strategy is to use a suse vm, install `osc`, then `osc co devel:languages:python/python-Nuitka`, then use `osc build` which builds in the VM. https://build.opensuse.org/package/show/devel:languages:python/python-Nuitka 

Not sure about podman, but maybe there is tooling to support converting builds to podman, which is also supported by obs-build (https://github.com/openSUSE/obs-build#image-formats).

> ok, and I managed to reproduce it on stable version, but not on develop ..

> Somehow git biset is letting me down in new ways, I cannot git biset from master to develop branch ..

I'll do a build of develop to see if that fixes it.

**Comment by kayhayen** [comment]
@jayvdb I am actually sure of that it is fixed there, problem with these kinds of things is that any optimization can reveal others that are missing... these are going to crop up, and usually are valuable to recognize missed opportunities

**Comment by jayvdb** [comment]
I am also getting this on Python 3 when I enable `--debug` on gcc builds.  I havent been trying `--debug` on gcc for a while, so dont know if this is a recent problem.

```
[ 2291s] Consider output of standalone mode compiled program: FlaskUsing.py
[ 2291s] Comparing output of 'FlaskUsing.py' using '/usr/bin/python3.6' with flags silent, expect_success, --standalone, remove_output, cpython_cache, timing, ignore_warnings ...
[ 2930s] --- /usr/bin/python3.6 (stderr)
[ 2930s] +++ nuitka (stderr)
[ 2930s] 
[ 2930s] @@ -1 +1,7 @@
[ 2930s] 
[ 2930s] +module.pyparsing.core.c: In function â€˜impl_pyparsing$core$$$function__36_parse_stringâ€™:
[ 2930s] +module.pyparsing.core.c:25491:17: error: variable â€˜tmp_try_except_1__unhandled_indicatorâ€™ set but not used [-Werror=unused-but-set-variable]
[ 2930s] +25491 |     nuitka_bool tmp_try_except_1__unhandled_indicator = NUITKA_BOOL_UNASSIGNED;
[ 2930s] +      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 2930s] +cc1: all warnings being treated as errors
[ 2930s] +scons: *** [module.pyparsing.core.o] Error 1
[ 2930s]  
[ 2930s] Updating CPython cache by force due to non-matching comparison results.
[ 2930s] --- /usr/bin/python3.6 (stderr)
[ 2930s] +++ nuitka (stderr)
[ 2930s] 
[ 2930s] @@ -1 +1,7 @@
[ 2930s] 
[ 2930s] +module.pyparsing.core.c: In function â€˜impl_pyparsing$core$$$function__36_parse_stringâ€™:
[ 2930s] +module.pyparsing.core.c:25491:17: error: variable â€˜tmp_try_except_1__unhandled_indicatorâ€™ set but not used [-Werror=unused-but-set-variable]
[ 2930s] +25491 |     nuitka_bool tmp_try_except_1__unhandled_indicator = NUITKA_BOOL_UNASSIGNED;
[ 2930s] +      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 2930s] +cc1: all warnings being treated as errors
[ 2930s] +scons: *** [module.pyparsing.core.o] Error 1
```

**Comment by kayhayen** [comment]
It very likely is recent, the next release doesn't have it as far as I can tell. The compiler is telling us, me, here that it can do an optimization that is indicative of one not being done by Nuitka, in principle for every optimization added to Nuitka, it can reveal the missing of another one... so these are going to come up. Not a huge problem per se.

**Comment by kayhayen** [comment]
Part of the 0.6.19 release I just made.
