### ISSUE TITLE
Opensuse failure in PandasUsing on Python 3.8 & .9

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#1340]
`Nuitka-Plugins:WARNING: Use '--enable-plugin=gi' for: Missing gi support.` is something I have seen before with https://github.com/Nuitka/Nuitka/issues/1298 , but now it is unexpectedly occurring with PandasUsing.py in v0.6.18.5.

On 0.6.18.0 it was passing.

However the current Python 3.6 builds are still passing.

```
[  371s] Nuitka:INFO: Overall execution of './tests/optimizations/run_all.py search' took 5.19 seconds
[  371s] Running the standalone tests with options '' with 'python3.9':
...
[ 3083s] Comparing output of 'PandasUsing.py' using '/usr/bin/python3.9' with flags silent, expect_success, --standalone, remove_output, cpython_cache, timing, plugin_enable:numpy, plugin_disable:pylint-warnings, plugin_disable:pyqt5, plugin_disable:pyside2, plugin_disable:pyside6 ...
[ 4686s] --- /usr/bin/python3.9 (stderr)
[ 4686s] +++ nuitka (stderr)
[ 4686s] 
[ 4686s] @@ -1 +1,2 @@
[ 4686s] 
[ 4686s] +Nuitka-Plugins:WARNING: Use '--enable-plugin=gi' for: Missing gi support.
[ 4686s]  
[ 4686s] Updating CPython cache by force due to non-matching comparison results.
[ 4686s] --- /usr/bin/python3.9 (stderr)
[ 4686s] +++ nuitka (stderr)
[ 4686s] 
[ 4686s] @@ -1 +1,2 @@
[ 4686s] 
[ 4686s] +Nuitka-Plugins:WARNING: Use '--enable-plugin=gi' for: Missing gi support.
[ 4686s]  
[ 4686s] Error, results differed (stderr).
[ 4686s] Listing of dist folder 'PandasUsing.dist':
```

**Comment by kayhayen** [comment]
I have the goal to have plugins on by default. Much rather would I have "gi" plugin do its thing, and inform the user that the copying of the typelib files can be disabled, the plugin is harmless otherwise.

**Comment by kayhayen** [comment]
On factory it's now always on, and that should of course solve this issue.

**Comment by kayhayen** [comment]
This now part of the current pre-release and will be part of 0.6.19 which should arrive shortly.

**Comment by kayhayen** [comment]
Part of the 0.6.19 release I just made.
