### ISSUE TITLE
'PythonShlibModule' object has no attribute 'asGraph' — probably "--graph" broken

### ISSUE THREAD

**Issue by belonesox** [Nuitka/Nuitka#1341]
Same setup as #1324, for example https://github.com/belonesox/nuitka-looping-mustNotHaveValue/tree/windows-python-3.8.10

Running demo with "--graph" got 
```
'PythonShlibModule' object has no attribute 'asGraph'
```

![image](https://user-images.githubusercontent.com/1609739/147376626-21c72244-c44b-44b2-a8e0-fe587a1f53db.png)

Obviously, I can see that last module is 
```
class 'nuitka.nodes.ModuleNodes.PythonShlibModule'
```
that  descendants of PythonModuleBase
```
class PythonShlibModule(PythonModuleBase):
    kind = "PYTHON_SHLIB_MODULE"

    __slots__ = ("used_modules",)

```

but ``asGraph`` is method only for ``CompiledPythonModule`` another descendants of ``PythonModuleBase``.
(I just check factory branch  — same situation).

----
Actually, current functionality of "--graph" is not OK: (and probably, it should be another RFE, but let start discussing here)
* ``pygraphviz`` is very fat module, because of SWIG-dependencies of graphviz. 
  * PITA install it on Windows (see https://pygraphviz.github.io/documentation/stable/install.html#windows, and actually — even worse because of 32/64 problems, need put graphviz bins into PATH, impossibility to automatically install into pipenv, etc)
  * Actually, real SVG/PNG file does not needed (if we need it for docs, we also need interface to specify Graphviz "styles"), so pure "*.dot" file, or even dependency part (… "aa" -> "bb" …  ) of dot file will be better. If someone needed SVG/PDF/PNG, she can easily add appropriate pipeline.
     * May be python workflow drawing libs (PyVis, etc) will be even better for exploring large DAGs. (direct acyclic graphs)
* Dumping appropiate "dot/node deps" file should be continuous, because any exception like 
```
FATAL: Error, forbidden import 'XXXX' encountered.
```   
leaves us without graph and not any glue, what the heck and where this XXXX  module imported.

**Comment by kayhayen** [comment]
So far it's been used only on single modules, when I analysed the optimization behaviour, and not a lot actually. It will draw value traces made, this can easily become impossible to render for larger programs. I admit the help output there is not making it clear that this is for debugging. It is in the debug group though.

The graphs you might be looking for will be made out of the compilation report, that I added recently (not sure yet, but I think it's on develop), but they lack information still. 

What you are saying there about the dot file is very interesting. I have no idea how to style them, would you be willing to help there? I would implement like a dependency analysis graph (that is what you call DAG?) output in dot, you would help to make it pretty and usable? I would love e.g. to have links to the original source in there.

**Comment by kayhayen** [comment]
Also, with a XML report file, we would be better at making all kinds of reports after the compilation when we need it.

**Comment by kayhayen** [comment]
I think I fixed the crash given, but it's not really considered a bug, so I am just closing this.
