### ISSUE TITLE
[Question] Following is more like a Question than a actual issue

### ISSUE THREAD

**Issue by FuckingToasters** [Nuitka/Nuitka#1345]
Hello, I was wondering if there is a way to compile for different operating systems at once (if im on windows, then probably compile for debian, ubuntu, arch systems or apple too.

**Comment by kayhayen** [comment]
With Nuitka commercial you can build on a container Linux that runs on basically everything. Cross compilation is not supported there, there is an issue for it though. In theory it's just work, but I am not sure if it will ever be done.
