### ISSUE TITLE
qtpy/PySide6 standalone missing ui files, icons and Qt sqldriver

### ISSUE THREAD

**Issue by kwiechen** [Nuitka/Nuitka#1351]
Hello,

I have compiled a qtpy/PySide6 program using 

nuitka --standalone --plugin-enable=pyside6 --follow-imports

0.6.18.6
Commercial: None
Python: 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\kai\WPy64-31001\python-3.10.0.amd64\python.exe
OS: Windows
Arch: x86_64

Everything works fine after manually adding the ui files, icons and the sqldrivers to the _main.dist and PySide6 dirs. 

Is it possible include the missing files directly?

Best regards,

Kai

**Comment by kayhayen** [comment]
Yes, you want to include the plugins. Use help and checkout the options of the Qt binding plugin. You can specify which plugins to include. The default is sensible, i.e. things most programs need. But all would be too much.

**Comment by kwiechen** [comment]
thank you - this helps for the missing qtsql drivers. But is it possible to bundle the ui designer files to generate the GUI dynamically, icons and other ressource files? I am currently using pyinstaller to do exactly this. But binary startup is much faster using nuitka ...
