### ISSUE TITLE
Error, usable static libpython is not found for this Python installation. You might be missing required '-dev' packages. Disable with --static-libpython=no" if you don't want to install it.

### ISSUE THREAD

**Issue by monkeycc** [Nuitka/Nuitka#1353]
Nuitka-0.6.18.6
WIN11
python 3. 7

`python -m nuitka --standalone    --show-progress  --windows-disable-console  --plugin-enable=tk-inter   --nofollow-imports  --output-dir=OUT  hello.py
`
FATAL: Error, usable static libpython is not found for this Python installation. You might be missing required '-dev' packages. Disable with --static-libpython=no" if you don't want to install it.

**Comment by monkeycc** [comment]
`conda install -c anaconda libpython`

Problem solving

**Comment by kayhayen** [comment]
Had you tried develop, you might have found this easier. But then again, you don't fill out issue templates either, so you didn't read that.
