### ISSUE TITLE
W: An error occurred during the signature verification.

### ISSUE THREAD

**Issue by kpirnie** [Nuitka/Nuitka#1354]
* Ubuntu 20.04 LTS Server
* Attempting apt update
* Got message: W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://nuitka.net/deb/stable/focal focal InRelease: The following signatures were invalid: EXPKEYSIG 1BFC33752912B99C Kay Hayen <kay.hayen@gmail.com>

**Comment by kayhayen** [comment]
Not sure how to communicate this, the download page has a new key. At some point, I will add a keyring package, but I didn't take the time yet.
