### ISSUE TITLE
Use as the one-file Python Interpreter

### ISSUE THREAD

**Issue by ClericPy** [Nuitka/Nuitka#1358]
I was looking for the `portable` Python Interpreter many years, then I found a way to use nuitka like this.

1. init the `runner.py` like below
2. python3.9 -m nuitka --onefile --standalone --windows-onefile-tempdir-spec=._cache_%PID% --enable-plugin=tk-inter runner.py
3. runner.exe code.py

```python
import sys
from pathlib import Path
from runpy import run_module, run_path

try:
    args = sys.argv
    if len(args) > 1:
        arg1 = args[1]
        if Path(arg1).is_file():
            sys.argv = args[1:]
            run_path(arg1, run_name='__main__')
        elif arg1 == '-m':
            sys.argv = args[2:]
            run_module(args[2], run_name='__main__')
    else:
        import code
        code.interact()
except BaseException:
    import traceback
    traceback.print_exc(file=sys.stderr)
    # waiting for cleaning the cache folder

```

After searching the nuitka issues but no solutions yet.

Could you show me a better usage like that? What I needed is only the portable Interpreter and run Python code with `zipimport` to distribute my Apps.

Thanks for the Awesome nuitka.

**Comment by kayhayen** [comment]
I don't quite get, what the issue is supposed to be here?

**Comment by ClericPy** [comment]
Sorry, could `nuitka` give a better way to use as the one-file interpreter? If not, I will close this issue...
