### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_start_my_server)

### ISSUE THREAD

**Issue by its-jd** [Nuitka/Nuitka#1362]
Hello,

I am generating an extension module from the python module. Nuitka generates .pyd file without any error.
However, when I try to import generated extension module it gives me following error:

`>>> import start_my_server
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit_start_my_server)
`

Is there anything that I need to specify in __init__.py ?

**Comment by kayhayen** [comment]
No issue template, no fun.
