### ISSUE TITLE
Nuitka onefile keep error even just print

### ISSUE THREAD

**Issue by utzlol** [Nuitka/Nuitka#1363]
I have problem with Nuitka installed by pip in my system (Windows 7 32bit). The --onefile file always got error (program.exe has stopped working) even just print something and I don't know how to get the error message with that. I really concerned with this because --standalone file is normal. Also, I got working single executable program when compiling without any attribute that I can't include any file inside it.

**Comment by kayhayen** [comment]
No issue template no fun.
