### ISSUE TITLE
File-Path arguments with Wildcards are crashing the program

### ISSUE THREAD

**Issue by Linuxfabrik** [Nuitka/Nuitka#1364]
For the error this sample script is used:
```python3
print('hello')
```
invoked with python and a sample path like `python hello.py "C:\"` and `python hello.py "C:\*"` it prints hello

when compiled with 
```
python -m nuitka --mingw64 --follow-imports --output-dir C:\nuitka-compile-temp --remove-output --standalone hello.py
```
and then execute the .exe the result is the following:

`hello.exe "C:\"` prints hello and `hello.exe "C:\*"` crashes the program with the `%errorlevel%` variable set to `-1073741819`.

interesting is that `"C:\c*"` succeeds if there is only one file to match and with multiple files that are matching this regex, the program fails again.

* Nuitka version

```
python -m nuitka --version
0.6.18.6
Commercial: None
Python: 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\Administrator\AppData\Local\Programs\Python\Python39\python.exe
OS: Windows
Arch: x86_64
```

* How did you install Nuitka and Python

Python through the official installer and Nuitka per 'python -m pip nuitka'

```
python -m pip freeze

Nuitka==0.6.18.6
psutil==5.8.0
```

**Comment by kayhayen** [comment]
I wonder what shell you are using for this, is it `cmd.exe` ?

The error level on Windows is frequently garbage when certain kinds of crashes happen, not sure how to improve on that.

**Comment by kayhayen** [comment]
I could not reproduce this with the develop version of Nuitka, nor on the stable version. I recently changed how command line arguments are passed and used in Nuitka on Windows however, switching from `main` to `wmain`. My primary motivation was to get rid of useless uses of `GetCommandLineW` in code parts of Nuitka, and instead just use the original one.

I managed to reproduce it with stable version of Nuitka, but with both MinGW64 and MSVC. They both use the MSVC runtime though, so it could be a common bug there. Obviously some unicode to ansi conversion must be done to matched filenames, and while I do not have any unicode in "C:\" I do have symlinks there. However, also "*" crashes it for me in my git checkout that has only harmless stuff going on.

As I am about to release 0.6.19 you were a bit unlucky with this one. 

I wouldn't say I understand why this is an issue. The expansion of file paths must be done by a program itself. It might be that the Python run time does this unknown to me, it might be MSVC runtime. Probably the conversion done there was bad on Windows, but it never cared about file patterns. I will check quickly that patterns do in fact work at all now.

**Comment by kayhayen** [comment]
Ok, there is an interesting difference, with MSVC the pattern ends up in `sys.argv` and with pure Python it does too. With MinGW64 it expanded before the program sees it, more like Linux does things.

**Comment by kayhayen** [comment]
Ok, I was maybe wrong about MSVC having the issue too, it does not. So now we know, the MinGW64 had an issue with expanding the arguments, which it is in fact not really supposed to do (I wonder how to disable that, it might make the program incompatible with Python), but the switch to unicode probably fixed that bug accidentally.

**Comment by kayhayen** [comment]
Part of the 0.6.19 release I just made.
