### ISSUE TITLE
Nuitka For QtQuick Bug!

### ISSUE THREAD

**Issue by ITSweets** [Nuitka/Nuitka#1365]
Hello, I am using Nuitka to package the QtQuick program, there is no problem, but Nuitka copy a few .dll files less, which makes the program unable to run, and must be copied manually. Why doesn't Nuitka automatically copy over? [Qt5QmlWorkerScript.dll, Qt5QuickControls2.dll, Qt5QuickTemplates2.dll]

**Comment by kayhayen** [comment]
No issue template, no fun.
