### ISSUE TITLE
Missing configuration file | OpenCV

### ISSUE THREAD

**Issue by Pro100rus32** [Nuitka/Nuitka#1366]
_last factory Nuitka, win11, python 3.9.9 and 3.10.1_
_OpenCV: 3.4.17.61_

**command:**
`python -m nuitka --windows-uac-admin --mingw64 --enable-plugin=anti-bloat --lto=no --onefile --plugin-enable=numpy "D:\Test.py"`

**Code:**
`import cv2`

**Test.exe**
```
Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Temp\ON6B4C~1\Test.py", line 1, in <module>
  File "C:\Users\test\AppData\Local\Temp\ON6B4C~1\cv2\__init__.py", line 118, in <module cv2>
  File "C:\Users\test\AppData\Local\Temp\ON6B4C~1\cv2\__init__.py", line 66, in bootstrap
  File "C:\Users\test\AppData\Local\Temp\ON6B4C~1\cv2\__init__.py", line 64, in load_first_config
ImportError: OpenCV loader: missing configuration file: ['config.py']. Check OpenCV installation.
```

_I tried add:_
`--include-data-file=D:/TEST/Lib/site-packages/cv2/config.py=cv2 --include-data-file=D:/TEST/Lib/site-packages/cv2/config-3.py=cv2`

**test.exe**
```
  File "C:\Users\test\AppData\Local\Temp\ONA816~1\Test.py", line 1, in <module>
    import cv2
  File "C:\Users\test\AppData\Local\Temp\ONA816~1\cv2\__init__.py", line 118, in <module cv2>
  File "C:\Users\test\AppData\Local\Temp\ONA816~1\cv2\__init__.py", line 106, in bootstrap
  File "C:\Users\test\AppData\Local\Temp\ONA816~1\cv2\__init__.py", line 118, in <module cv2>
  File "C:\Users\test\AppData\Local\Temp\ONA816~1\cv2\__init__.py", line 31, in bootstrap
ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.
```

**Comment by kayhayen** [comment]
This seems to be a duplicate, I recall this for sure.

**Comment by Pro100rus32** [comment]
> This seems to be a duplicate, I recall this for sure.

This problem has been closed. But at the moment I'm still seeing it #1275

**Comment by kayhayen** [comment]
Ah, the PR added this:

```
opencv-python:
  patterns:
    - "config*.py"
```

But that's not the package name, which is what was needed. I never checked it, but the `-` ought to have been suspicous.

**Comment by kayhayen** [comment]
Guess my hope that a yaml file gets more contributions didn't result in anything useful there. Not only does the change not work, when I correct it, it contains relative garbage (nothing adapted or included), and I am getting the error you report anyway. Not sure if it's better on any other platform, I used Windows like you did.

**Comment by kayhayen** [comment]
Looking at the code, indeed recursion is happening like it says, and it's playing interesting games, e.g. this kind of thing within the cv2 package.

```
    py_module = sys.modules.pop("cv2")
    native_module = importlib.import_module("cv2.cv2")
    sys.modules["cv2"] = py_module
```

There is no hope for an easy fix here. It has absolutely insane loading tricks, and very obviously the authors of the code never heard of namespace packages or anything how to iterate packages, etc. as it's all file system based. This would need some serious plugin work to find out, what they want to achieve, and then to achieve it. I don't see myself venturing there without serious funding.

**Comment by kayhayen** [comment]
Just checked, cv2 is also not working on Linux.

**Comment by dmwyatt** [comment]
> Looking at the code, indeed recursion is happening like it says, and it's playing interesting games, e.g. this kind of thing within the cv2 package.
> 
> ```
>     py_module = sys.modules.pop("cv2")
>     native_module = importlib.import_module("cv2.cv2")
>     sys.modules["cv2"] = py_module
> ```
> 
> There is no hope for an easy fix here. It has absolutely insane loading tricks, and very obviously the authors of the code never heard of namespace packages or anything how to iterate packages, etc. as it's all file system based. This would need some serious plugin work to find out, what they want to achieve, and then to achieve it. I don't see myself venturing there without serious funding.

Just idle wondering if maybe the effort might be better spent in improving cv2.  Not that I'm expecting anything out of anyone here, but if it'd be a one-off plugin for Nuitka it might be better to improve cv2 for everyone. (I haven't investigated the source of this problem)

Maybe someone might raise an issue about this with the OpenCV people?

**Comment by fneitzel** [comment]
I replaced
```
    py_module = sys.modules.pop("cv2")
    native_module = importlib.import_module("cv2")
    sys.modules["cv2"] = py_module
```
with:
```python
def __bootstrap__():
   global __bootstrap__, __loader__, __file__
   import sys, pkg_resources, imp
   __file__ = pkg_resources.resource_filename(__name__,'cv2.cpython-310-x86_64-linux-gnu.so')
   print(__file__)
   __loader__ = None; del __bootstrap__, __loader__
   return imp.load_dynamic(__name__,__file__)

def bootstrap():
   [...]
   native_module = __bootstrap__()
```
Then I just needed to move the shared lib to the dist folder and it worked

**Comment by kayhayen** [comment]
@fneitzel thanks for sharing this with me.... if that's working for real, we owe you :-)

**Comment by junbaibai0719** [comment]
> I replaced
> 
> ```
>     py_module = sys.modules.pop("cv2")
>     native_module = importlib.import_module("cv2")
>     sys.modules["cv2"] = py_module
> ```
> 
> with:
> 
> ```python
> def __bootstrap__():
>    global __bootstrap__, __loader__, __file__
>    import sys, pkg_resources, imp
>    __file__ = pkg_resources.resource_filename(__name__,'cv2.cpython-310-x86_64-linux-gnu.so')
>    print(__file__)
>    __loader__ = None; del __bootstrap__, __loader__
>    return imp.load_dynamic(__name__,__file__)
> 
> def bootstrap():
>    [...]
>    py_module = sys.modules.pop("cv2")
>    native_module = __bootstrap__()
>    sys.modules["cv2"] = py_module
> ```
> 
> Then I just needed to move the shared lib to the dist folder and it worked

In Windows, 
```python
def __bootstrap__():
   global __bootstrap__, __loader__, __file__
   import sys, pkg_resources, imp
   print(__name__)
   __loader__ = None; del __bootstrap__, __loader__
   return imp.load_dynamic(__name__,"cv2.pyd")

**Comment by kayhayen** [comment]
It's a shame I didn't get to this yet, but for 0.8 there will be anti-bloat configuration to handle it this way, too busy hunting a corruption bug of current release.

**Comment by kayhayen** [comment]
Actually, no copying is necessary, the `cv2/cv2.so` is already the right kind of file.

**Comment by kayhayen** [comment]
So, only `imp.load_dynamic` works for me. Also I had to solve the `config.py` issue. It seems it is evaluated via exec in a local context, so we just copy the file as source into there with anti-bloat config.

**Comment by kayhayen** [comment]
So, this was done for 0.8, unfortunately only with 0.9 the newest OpenCV will be working, since they changed things again, so I am moving the milestone, but reported versions ought to work already, I think, but for good measure use develop.

**Comment by kayhayen** [comment]
Part of the 0.9 release that I just made.

**Comment by austin-InDro** [comment]
This error is still occuring in V1.1.6 and at least opencv_python versions 4.6, 3.4.17, or 4.5.5.64.
[fneitzel](https://github.com/fneitzel) change to __init__.py did not work for me on Linux x86_64. Same error occured.

**Comment by kayhayen** [comment]
@austin-InDro posting below closed issues is a sure fire way to get ignored, please open a new issue
