### ISSUE TITLE
MinGW64 does wild card expansion for command line arguments of created binaries

### ISSUE THREAD

**Issue by Linuxfabrik** [Nuitka/Nuitka#1370]
Assume you have a directory
* containing two files `test1` and `test2`
* plus a simple Python script compiled with Nuitka 0.6.19, offering a `--filename` parameter, which expects a regex search term, for example `test*`

If you call `myscript.exe --filename "test*"`, you get `myscript.exe error: unrecognized arguments: test2`, so the Windows cmd shell is doing wildcard expansion now, passing `--filename test1 test2` to the script, which of course fails.

Do you know how to prevent this behaviour? We would expect that `test*` is passed to the Python script's `--filename` parameter.

```
0.6.19
Commercial: None
Python: 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\Administrator\AppData\Local\Programs\Python\Python39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

**Comment by kayhayen** [comment]
Generally `--filename=*test*` style of options will be more robust against expansion.

I assume you still have MinGW64 doing it, cmd.EXE doesnot do it to my knowledge, but e.g. bash.exe will, i do not know what powershell does. But argument parsing generally respects quotes, i.e. "test*" is going to work for all shells. If you want to be compatible with python.exe for these matters, it seems you have to use MSVC for the C compiler. I didn't find a way to turn off the argument expansion of MinGW64.

**Comment by kayhayen** [comment]
Actually, clang may also work, I am trying it out, but it has regressed on Windows.

**Comment by kayhayen** [comment]
Nope, Clang on Windows does it too.

**Comment by Linuxfabrik** [comment]
As we do not have MSVC, we are using MinGW64, yes...

**Comment by Linuxfabrik** [comment]
And also yes, `myscript.exe --filename=test*` in cmd.exe works. Unfortunately the parameters are built dynamically by a 3rd party software, which creates ` --filename test*` using spaces.

**Comment by kayhayen** [comment]
I reported the bug to winlibs, lets see what they have to say about it, maybe it can be overridden in some way.

**Comment by kayhayen** [comment]
So, on factory there is a fix for this. Turns out, we can disable it at link time by overriding a variable. With that, it now gives me `*.py` rather than expanded files in `sys.argv` as it should. 

Of course, provided I don't use Git bash which does it even before the program starts. ;-)

**Comment by kayhayen** [comment]
This will become part of the next hotifx.

**Comment by Linuxfabrik** [comment]
Awesome, thank you! :-)

**Comment by kayhayen** [comment]
Part of the latest hotfix release.
