### ISSUE TITLE
How to pronounce Nuitka?

### ISSUE THREAD

**Issue by la-vie-est-belle** [Nuitka/Nuitka#1374]
Can the official give me the  International Phonetic Alphabet of Nuitka please? 

Thanks.

**Comment by kayhayen** [comment]
The best I have come up with is `knewtka` so far. I will research some more, the final `a` sound is not quite right that way.

**Comment by kayhayen** [comment]
I was using this, is there some place where I can change the phonetics and hear it?

**Comment by kayhayen** [comment]
Ok, the `a` sound is the `ɐ`. Not sure if the site pronounced the other stuff correctly, you do not hear the `k` sound. So `knewtkɐ` makes sense to me, but how to replay this somewhere I didn't find.

**Comment by kayhayen** [comment]
Basically `newt` in English and even more `knew` cover the first part, and this `ɐ` sound connected with a `k` catch it best. I think the site wanted to give me an error, so `nu`  is the phonectics for the first part, and then I got `nutkɐ` as a result. This is terribly hard for me. I am hoping you can give me pointers for how to do this.

**Comment by la-vie-est-belle** [comment]
I thought it was pronounced [nuːtkɑː], as nuit is like suit [suːt]. But yes, newka[njuːtka:] is actually sounded better.

Ka takes some time to decide. It can be [kɑ:] or [kə].

**Comment by la-vie-est-belle** [comment]
I thought it was pronounced [nuːtkɑː], as nuit is like suit [suːt]. But yes, newka[njuːtka:] actually sounds better.

Ka takes some time to decide. It can be [kɑ:] or [kə].

**Comment by kayhayen** [comment]
So, inded `nju` as to be right. I just checked `fusion` and that's the sound of the `u` as modified by the `i`. I lack examples of `ka` words in English right now.

**Comment by la-vie-est-belle** [comment]
How about kart?

**Comment by la-vie-est-belle** [comment]
Or vodka.  LOL. :)

**Comment by kayhayen** [comment]
That's very fitting actually :)

**Comment by kayhayen** [comment]
So, that cuts it, `nju:kə` is where we landed. I need to read up what the colon does.

**Comment by la-vie-est-belle** [comment]
t in Nuitka doesn't make the sound right?

The colon in u: means it needs to be read a little bit longer in time. It's a long vowel. :)

**Comment by kayhayen** [comment]
We lost the `t` sound on the way, and I think the colon is not warranted, same as in `newt`, there is  no `nu:t` there I think. So I am for `njutkə` then, assuming the `t` is just the regular one.

**Comment by la-vie-est-belle** [comment]
I like it. 🥇 

Have a good day. :)
