### ISSUE TITLE
Compiler / Linker Error using Nuitka 

### ISSUE THREAD

**Issue by tschloesser** [Nuitka/Nuitka#1376]
Using Nuitka version 0.6.20rc1 im running into a error at the start of „Backend C“ - I believe this is because of MacOS security, is it not?

BTW: Im running the compiler under MacOS 11.6.2, and the issue is coming up in both Python 2.7 and Python3.

-------
ld: cannot link directly with dylib/framework, your binary is not an allowed client of /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.tbd for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)  

Can you provide some help on this as well ;-)

Kind regards

Thorsten

**Comment by kayhayen** [comment]
No issue template means I have no information or chance to reproduce.

**Comment by tschloesser** [comment]
Dear Kay,

I posted the error I received in the shell - what kind of information do you need to help me with this issue?

I 100% nbelive it is MacOS related, but I am nut shure how to change the security settings in this case?

Kind regards

Throsten


===========================
Thorsten Schlößer
***@***.***

**Comment by kayhayen** [comment]
The kind of information the issue template requests and that help me to know why it's different for you.

**Comment by tschloesser** [comment]
Dear Kay,

today I run the same procedure again, only with Python3, and I did not run into any error anymore!

So maybe my reported issue was related to the fact I was using Python 2.7 or because of something else related to my MacBook.

But maybe I can ask you one question: 
As a result running Nuitka I found two folders with the name of my python code and the extentions build and dist
The dist directory is containing a lot or library (.so) files and the binary. 
BTW: I run this command -  python3 -m nuitka --follow-imports --standalone getNMASpwd.py

Can you please tell me, what I have to „distribute“ to run the binary on a rmote host, and if there are nay other requrenments?

===========================
Thorsten Schlößer
***@***.***

**Comment by kayhayen** [comment]
Hello Thorsten,

I really need the outputs to know what is going on. When you say Python 2.7, there is a myriad of things this could mean. If you followed the commands I am asking in the issue template, I would know more and could actually reproduce things. But macOS 11.6 and Python2 alone mean nothing to me. There is plenty of users who have exactly that in right form.

Also please consider reading the User Manual. It answers these questions, and if it does not, you can make it clear what it doesn't say. Maybe you will also discover the section where it says which Python versions are supported while there.

Yours,
Kay
