### ISSUE TITLE
Problems getting jwt.algorithms to work on Linux armhf

### ISSUE THREAD

**Issue by levesquejf** [Nuitka/Nuitka#1377]
Using Nuitka `0.6.19.1`, Python `3.8`, I have the following ImportError on Linux armv7l. Using the same code and Nuitka version, I don't have the issue on x86_64 or aarch64 (armv8).

```
Traceback (most recent call last):
  File "/opt/app/main.dist/main.py", line 2, in <module>
ImportError: cannot import name 'RSAAlgorithm' from 'jwt.algorithms' (/opt/app/main.dist/jwt/algorithms.py)
```

The code is:

```
import jwt
from jwt.algorithms import RSAAlgorithm
from jwt.api_jws import _jws_global_obj


if "RS256" in _jws_global_obj._algorithms:
    jwt.unregister_algorithm("RS256")
jwt.register_algorithm("RS256", RSAAlgorithm(RSAAlgorithm.SHA256))

print("It's working,")
```

Easy to reproduce using Docker (see https://github.com/levesquejf/nuitka-jwt-algorithms-not-imported) on a Linux x86_64 machine. The second script is configured for cross-compilation. It is slow but it's normal.

`./run-nuitka.sh` is building on x86_64 and it's working
`./run-nuitka-armv7l.sh` is building on armv7l and it's failing

**Comment by kayhayen** [comment]
This works on my native armv7l just fine. The cross compiling setup is not supported as you know. Get in touch privately if you are willing to provide funding for me researching why it's happening, otherwise I can't really look at this.

**Comment by kayhayen** [comment]
So, this is on `raspberrypi3-python:3.8.3-stretch-build` which is relatively old, but well-supported by Nuitka. I am trying to reproduce it without docker, but since I fail to understand the dockerfile, I am running them with podman now.

What puzzles me is the `cross-build-start` RUN for which I don't see the file anywhere.

**Comment by kayhayen** [comment]
I have to assume it's contained in the images, and as such is something that these images provide, would that be correct?

**Comment by levesquejf** [comment]
@kayhayen Take a look at this: https://www.balena.io/docs/reference/base-images/base-images/#building-arm-containers-on-x86-machines.

**Comment by kayhayen** [comment]
Just to keep this on my mind: One approach, we could use, is to cross-compile a Python in there, and then convince pip to install wheels into there. Alternatively, we could use qemu/kvm to install a debian. I have used qemu images of various arches of stretch in the past to test Nuitka. But that approach was not aging well. I recall bootstraping ARM machines with qemu in the past too.

We only need the files from in there, so even if that's slow to create, it would be fine. What I think we need is some sort of "remote" access, where Nuitka scans remote Python code, and would use the ".so" and do its ldd lookups.

**Comment by kayhayen** [comment]
Judging by the speed of the installation however, and it's installing armhf packages, I might be on the wrong track, and this image is being actually executed in emulation already, in which case, this wouldn't be about cross compiling all that much.

**Comment by kayhayen** [comment]
Still catching up on my ignorance, but I found this for the cross scripts: https://www.balena.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/

**Comment by kayhayen** [comment]
That's pretty neat technology I have to say, but it's making life a bit harder for debug logins, but I guess I only have to remove the "end" of that cross scripts.

**Comment by kayhayen** [comment]
Ok, I think I found a problem with your code:

```
STEP 10: RUN pipenv run python main.py 
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from jwt.algorithms import RSAAlgorithm
ImportError: cannot import name 'RSAAlgorithm' from 'jwt.algorithms' (/root/.local/share/virtualenvs/app-ueEJiAOq/lib/python3.8/site-packages/jwt/algorithms.py)
```

It's not actually a difference, pure Python does not work! Nuitka will not be able to change that.

Now the question is, does `armhf` on Debian stretch have the support for this? It may not use wheels for each platform, esp. not the unusual ones, I think `armhf` is a dead end that Debian once had, but generally fell out of favor. I was doing my test on `armv7l` and regarding `i386`, that's also fallen out of favor. They may no longer support those with binary wheels which make it easy to use.

So I think you may either find an older version that still had those wheels, but seeing you use want to use 3.8 that is not going to happen. 

Or you need to compile the wheels more properly from source with their development header packages dependencies installed. I am having the build of the `pipenv` cached, not sure if it would output what's missing. I also couldn't immediately find their CI config with how they build their wheels.

I hope this helps!

**Comment by levesquejf** [comment]
Of course, I don't expect Nuitka to work if native Python is not... Let me take a closer look on that code and if it's really needed and I will get back to you. Thanks for your help today.

**Comment by kayhayen** [comment]
You will be very welcome.
