### ISSUE TITLE
Nuitka uses old version of python files

### ISSUE THREAD

**Issue by aipatr** [Nuitka/Nuitka#1379]
Dear all,
could you tell me how to clean the cache of Nuitka?
I installed Nuitka in my CI system but it somehow caches the python files. I want to clean the cache and use everytime the new files.
I don´t care if this makes the process slower.

Thank you in advance!

**Comment by kayhayen** [comment]
One if not the most glaring missing features is actually using of a caching for the python things, but once I do, I surely will add an option for it. Or are you saying you have evidence of it using old files? Then I would love to have a reproducer.

**Comment by kayhayen** [comment]
Lack of feedback
