### ISSUE TITLE
ModuleNotFoundError: No module named 'mpl_toolkits.mplot3d'

### ISSUE THREAD

**Issue by tangjl73** [Nuitka/Nuitka#1384]
nuitka0.6.19
matplotlib 3.5.1
using follow command:
nuitka --mingw64 --standalone --show-progress --show-memory --nofollow-imports --plugin-enable=tensorflow --plugin-enable=qt-plugins --include-qt-plugins=sensible,styles --follow-import-to=mainUI --follow-import-to=other --windows-icon-from-ico=app.ico --output-dir=out_app app.py
ImportError: cannot import name '_api' from 'matplotlib' (...\matplotlib\__init__.py)
then copy matplotlib and mpl_toolkits to exe path ,get follow error:
File ".....\matplotlib\projections\__init__.py", line 4, in <module>
from mpl_toolkits.mplot3d import Axes3D
ModuleNotFoundError: No module named 'mpl_toolkits.mplot3d'

why?please help, thanks!

**Comment by kayhayen** [comment]
You do not read warnings, do you? This is exactly as expected.
