### ISSUE TITLE
Option "--windows-onefile-tempdir-spec=." doesn't work.

### ISSUE THREAD

**Issue by la-vie-est-belle** [Nuitka/Nuitka#1388]
Hi,

I tried to use command  `--windows-onefile-tempdir-spec` to change directory where the temp folder generates.

So I used `nuitka --onefile  --windows-onefile-tempdir-spec=. hello.py` to make the temp folder generate in the same directory as that of hello.exe.

But after I run hello.exe, I got `Error, failed to open '.\hello.exe' for writing.` Did I use the command wrong?

Here is the version info:
```
0.6.19.1
Commercial: None
Python: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
Flavor: Unknown
Executable: E:\python\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

hello.py is very simple:
`print('Hello World')`

Thanks.

**Comment by kayhayen** [comment]
The running `hello.exe` is locked by Windows while it is running, causing this kind of error. I will add something that prevents it from being used. You might use  `.\temp` with more success. I will keep this open despite me thinking it's invalid, such that a check should be added to catch this. 

Did you intend for the onefile to overwrite itself with the unpacked result? Arguably, that could become a feature.

**Comment by la-vie-est-belle** [comment]
`You might use .\temp with more success.` This works, thanks a lot. I must add the folder name in the specified path.

Normally, I would not use this command `--windows-onefile-tempdir-spec`. Just want to learn Nuitka well, and provide some good help. I think Nuitka is promising. :)

**Comment by kayhayen** [comment]
Allow me to keep this open, until I managed to have the options' parser catch this. There should not be such an easy way to shoot yourself in the feet.

**Comment by la-vie-est-belle** [comment]
What if I use command `nuitka --onefile --windows-onefile-tempdir-spec=. hello.py`, the temp folder will generate in the current directory, and the folder name will be `onefile_%PID%_%TIME%` by default?

And if I use  `--windows-onefile-tempdir-spec=./hi`, the temp folder will generate in under the`hi`folder with the default name.

This should solve `Error, failed to open '.\hello.exe' for writing.`. :)

**Comment by la-vie-est-belle** [comment]
What if I use command `nuitka --onefile --windows-onefile-tempdir-spec=. hello.py`, the temp folder will generate in the current directory, and the folder name will be `onefile_%PID%_%TIME%` by default?

And if I use  `--windows-onefile-tempdir-spec=./hi`, the temp folder will generate in under the`hi`folder with the default name.

In short, the unpacked result is **a folder not files**. This should solve `Error, failed to open '.\hello.exe' for writing.`. :)

**Comment by kayhayen** [comment]
Actually, I think you should not care about the temp file folder as much as you did, and if you do, reading the docs will be very vital. And even using `hi` will have lots of drawbacks, like locked files from still running program. I think I will outright outlaw `.` and its `os.path.normpath` brothers. And then I will add a warning, if it doesn't contain `%%` style references.

If your concern is to be able to find files placed near the unpacked executable, then make sure to read the user manual section on this topic, there is `__file__` and there is `sys.argv[0]` pointing to either one.

Right now, the only valid users of this option would be ones, where the firewall warns about a program over and over, without an ability to accept it forever, since with unique paths, they do not get recognized.

**Comment by la-vie-est-belle** [comment]
Got it, thanks!

**Comment by kayhayen** [comment]
So, I pushed to factory a change with a lot of checks, this is the gist of it:

```
        if os.path.normpath(options.onefile_tempdir_spec) == ".":
            Tracing.options_logger.sysexit(
                """\
Error, using '.' as a value for '--onefile-tempdir-spec' is not supported,
you cannot unpack the onefile payload into the same directory as the binary,
as that would overwrite it and cause locking issues as well."""
            )

        if options.onefile_tempdir_spec.count("%") % 2 != 0:
            Tracing.options_logger.warning(
                """Unmatched '%' is suspicious for '--onefile-tempdir-spec' and may
not do what you want it to do: '%s'"""
                % options.onefile_tempdir_spec
            )

        if options.onefile_tempdir_spec.count("%") == 0:
            Tracing.options_logger.warning(
                """Not using any variables for '--onefile-tempdir-spec' should only be
done if your program absolutely needs to be in the same path always: '%s'"""
                % options.onefile_tempdir_spec
            )

        if os.path.isabs(options.onefile_tempdir_spec):
            Tracing.options_logger.warning(
                """Using an absolute path should be avoided unless you are targeting a
very well known environment: '%s'"""
                % options.onefile_tempdir_spec
            )
        elif relpath(options.onefile_tempdir_spec):
            Tracing.options_logger.warning(
                """Using an relative path above the executable should be avoided unless you are targeting a
very well known environment: '%s'"""
                % options.onefile_tempdir_spec
            )
```

Also comments on mismatched `%` which can be typos, and then absolute paths, and paths that are relative, but point to outside of things. This is hopefully sufficient to catch most errors.

**Comment by kayhayen** [comment]
I put this here, in case somebody wants to try it out, but it's not changing anything really: https://nuitka.net/doc/factory.html

I did consider this for hotfix, but then again, it's not that important, hopefully.

**Comment by kayhayen** [comment]
This is on develop now. I am closing this early for lack of general relevance.

**Comment by kayhayen** [comment]
This is part of the 0.7 release now.

**Comment by la-vie-est-belle** [comment]
awesome :)
