### ISSUE TITLE
"Library not loaded" error with PySide6 application on macOS

### ISSUE THREAD

**Issue by zoell** [Nuitka/Nuitka#1389]
As discussed in   #1195  opening a new bug:
When running a Python script which uses PySide6 on macOS (Monterey 12.1), I get the following error:

```
File "/Users/myuser/Dev/test/test.dist/test.py", line 2, in <module>
ImportError: dlopen(/Users/myuser/Dev/test/test.dist/PySide6/QtWidgets.so, 0x0002): Library not loaded: @rpath/QtQml.framework/Versions/A/QtQml
Referenced from: /Users/myuser/Dev/test/test.dist/libpyside6.abi3.6.2.dylib
Reason: tried: '/Users/myuser/Dev/test/test.dist/Qt/lib/QtQml.framework/Versions/A/QtQml' (no such file), '$ORIGIN/QtQml.framework/Versions/A/QtQml' (no such file), '/Users/myuser/Dev/test/test.dist/PySide6/Qt/lib/QtQml.framework/Versions/A/QtQml' (no such file), '$ORIGIN/../QtQml.framework/Versions/A/QtQml' (no such file), '/Users/myuser/Dev/test/test.dist/PySide6/Qt/lib/QtQml.framework/Versions/A/QtQml' (no such file), '$ORIGIN/../QtQml.framework/Versions/A/QtQml' (no such file), '$ORIGIN/QtQml.framework/Versions/A/QtQml' (no such file), '$ORIGIN/QtQml.framework/Versions/A/QtQml' (no such file), '/Library/Frameworks/QtQml.framework/Versions/A/QtQml' (no such file), '/System/Library/Frameworks/QtQml.framework/Versions/A/QtQml' (no such file)Library not loaded: @rpath/QtDBus.framework/Versions/A/QtDBus
```

* Nuitka version, full Python version, flavor, OS, etc. as output by this
  command (it does more than you think, and we are adding more all the time):

  > python -m nuitka --version
0.6.19.3
Commercial: None
Python: 3.9.10 (v3.9.10:f2f3f53782, Jan 13 2022, 17:02:14) 
Flavor: Unknown
Executable: /Users/myuser/Dev/test/venv/bin/python
OS: Darwin
Arch: x86_64

* How did you install Nuitka and Python
Installed from PyCharm.

* The specific PyPI names and versions
  > python -m pip freeze
altgraph==0.17.2
certifi==2021.10.8
charset-normalizer==2.0.10
click==8.0.3
Flask==2.0.1
idna==3.3
itsdangerous==2.0.1
Jinja2==3.0.1
macholib==1.15.2
MarkupSafe==2.0.1
Nuitka==0.6.19.3
pyinstaller==4.8
pyinstaller-hooks-contrib==2021.5
PySide6==6.2.2.1
requests==2.26.0
shiboken6==6.2.2.1
simple-settings==1.0.0
urllib3==1.26.8
Werkzeug==2.0.2
zstandard==0.15.2

* Also supply a Short, Self Contained, Correct, Example

```
if (__name__ == '__main__'):
    from PySide6.QtWidgets import QApplication
    from PySide6.QtWidgets import QGraphicsScene, QGraphicsView
    a = QApplication()
    s = QGraphicsScene()

    v = QGraphicsView(s)
    v.show()
    a.exec()
```

* Provide in your issue the Nuitka options used
`python3 -m nuitka --standalone --plugin-enable=pyside6 test.py`

**Comment by kayhayen** [comment]
For me, a simpler program fails like this on 10.15. It seems something is using an `rpath` that is not understood.

`FATAL: Error, call to 'otool' failed: ['/usr/bin/otool', '-L', '@rpath/QtCore.framework/Versions/A/QtCore'] -> b"error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: @rpath/QtCore.framework/Versions/A/QtCore (No such file or directory)\n".`

There is code there, which attempts to resolve these, but obvious failing at all.

**Comment by kayhayen** [comment]
I think this is an error, because I recently switched the API to call it, previously the error might have been unnoticed.

**Comment by kayhayen** [comment]
The dependency mechanism of macOS has since been wastly improved and PySide6 is known to work.
