### ISSUE TITLE
Packaging PySide6 with Nuitka - import QtNetwork causes issues - qt.network.ssl: No functional TLS backend was found

### ISSUE THREAD

**Issue by valvador92** [Nuitka/Nuitka#1390]
> Nuitka version
0.6.19.4
Commercial: None
Python: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\tools\miniconda3\envs\smartblur_env\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

* How did you install Nuitka and Python
pip install Nuitka in a conda env

* The specific PyPI names and versions
conda.exe install pybind11 libsodium ninja libopencv nomkl numpy=1.21.4 pyopengl pywin32 openssl -y

  > python -m pip freeze
Nuitka==0.6.19.4
numpy @ file:///D:/bld/numpy_1636145505783/work
pybind11 @ file:///D:/bld/pybind11-split_1641689025977/work
pybind11-global @ file:///D:/bld/pybind11-split_1641689025977/work
PyOpenGL==3.1.5
PySide6==6.2.2.1
pywin32==303
shiboken6==6.2.2.1

* Provide in your issue the Nuitka options used

nuitka --standalone --plugin-enable=pyside6 --plugin-enable=numpy --plugin-enable=anti-bloat --output-dir Packaging_video_test --static-libpython=no video_test.py

The problem is with packaging my app with Nuitka. It creates the executable but when I launch the executable I got those errors, and the part of the app related to QtNetwork is not working:

  > qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No TLS backend is available
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed

I didn't have those errors before including QtNetwork. I suspect an issue with OpenSSL but I don't know how to solve it.
If I run my app from the terminal:` python video_test.py`, everything works fine.
I have `openssl=1.1.1l=h8ffe710_0`

Thanks for your help!

**Comment by valvador92** [comment]
Hey!
Thanks for the answer. What are the name of the OpenSSL DLLs? I haven't gound them.
Here you can the the video_test.exe: https://www.swisstransfer.com/d/0a9800db-4fe0-4993-aa70-b6f5842710b3 

Do you want also the source code?

**Comment by kayhayen** [comment]
I actually only want source code and minimal ideally. The internet is not a place to download and run binaries from for me. Even if it were useful which it is not in this case

**Comment by valvador92** [comment]
ok, but the problem comes from the .exe. Running from terminal works fine. Here is the source code. I tried to reduce the code.

`from PySide6 import QtWidgets, QtCore, QtWebEngineWidgets, QtNetwork

import sys


class ConnectivityChecker(QtCore.QObject):
    statusChanged = QtCore.Signal(bool)

    def __init__(self, url, *, timeout=4000, parent=None):
        super().__init__(parent)
        self._status = False
        self._url = url

        self._timeout = timeout
        self.manager = QtNetwork.QNetworkAccessManager()
        self._timer = QtCore.QTimer(singleShot=True, interval=self._timeout, timeout=self.verifyUrlConnectionStatus)

    def start(self):
        QtCore.QTimer.singleShot(0, self._checkConnection)

    def stop(self):
        if self._timer.isActive():
            self._timer.stop()

    @QtCore.Property(bool, notify=statusChanged)
    def status(self):
        return self._status

    @QtCore.Slot(bool)
    def _updateStatus(self, status):
        if self._status != status:
            self._status = status
            self.statusChanged.emit(self.status)

    def _checkConnection(self):
        url = QtCore.QUrl(self._url)
        req = QtNetwork.QNetworkRequest(url)
        self._reply = self.manager.get(req)
        self._reply.finished.connect(self.verifyUrlConnectionStatus)
        self._timer.start()

    @QtCore.Slot()
    def verifyUrlConnectionStatus(self):
        if self._timer.isActive():
            self._timer.stop()
            if self._reply.error() == QtNetwork.QNetworkReply.NoError:
                v = self._reply.attribute(QtNetwork.QNetworkRequest.HttpStatusCodeAttribute)
                if 200 <= v < 300:
                    self._updateStatus(True)
                else:
                    self._updateStatus(False)
            else:
                self._updateStatus(False)
        else:
            self._reply.finished.disconnect(self.verifyUrlConnectionStatus)
            self._reply.abort()
            self._updateStatus(False)
        QtCore.QTimer.singleShot(5000, self._checkConnection)
        self._reply.deleteLater()


class HelpVideoReplayWidget(QtWidgets.QFrame):
    """
    Youtube video player
    """

    def __init__(self, url, iframe_settings, parent=None):
        QtWidgets.QFrame.__init__(self, parent)

        self._url = url
        self._iframe_settings = iframe_settings
        self._htmlPage = (
            """<html>
                    <head>
                        <title>A Sample Page</title>
                    </head>
                    <body style="line-height: 100px; background:black; color:white; text-align:center; font-family: 'Segoe UI'">
                        <h2>"""
            + self.tr("Unable to access YouTube video")
            + """</h2></body></html>"""
        )
        self._youtubePage = (
            """<html>
                <body style="margin: 0px">
                    <iframe id="player" type="text/html" """
            + self._iframe_settings
            + self._url
            + """></iframe></body></html>"""
        )
        self._isUrlPlayable = False
        self.connectivity_manager = ConnectivityChecker("https://www.youtube.com/embed/YdZd7LolWm0")
        self.connectivity_manager.statusChanged.connect(self.onUrlConnectionStatusChanged)
        self.connectivity_manager.start()

        self.hbox_video_placeholder = QtWidgets.QHBoxLayout()
        self.hbox_video_placeholder.setContentsMargins(0, 0, 0, 0)
        self._isVideoLoaded = False
        self._webBrowser = QtWebEngineWidgets.QWebEngineView()
        self.loadVideo()
        self.hbox_video_placeholder.addWidget(self._webBrowser)
        self.setLayout(self.hbox_video_placeholder)

    def loadVideo(self):
        """
        Load iframe page
        """
        if not self._isVideoLoaded:
            self._isVideoLoaded = True
            if self._isUrlPlayable:
                self._webBrowser.setHtml(self._youtubePage)
            else:
                self._webBrowser.setHtml(self._htmlPage)

        else:
            self._reloadVideo()

    def _reloadVideo(self):
        """
        Force load iframe page (ask loading when it is already loaded)
        """
        self.unloadVideo()
        self.loadVideo()

    def unloadVideo(self):
        """
        Unload iframe page to stop play video if any
        """
        if self._isVideoLoaded:
            self._isVideoLoaded = False
            self._webBrowser.setUrl("")
            self.connectivity_manager.stop()

    @QtCore.Slot(bool)
    def onUrlConnectionStatusChanged(self, status):
        if status:
            self._isUrlPlayable = True
        else:
            self._isUrlPlayable = False
        self.loadVideo()


class MainWindow(QtWidgets.QMainWindow):
    def __init__(self, *args, **kwargs):
        super(MainWindow, self).__init__(*args, **kwargs)

        self.browser = HelpVideoReplayWidget(
            "https://www.youtube.com/embed/YdZd7LolWm0",
            """width="557" height="315" frameborder="0" style="background-color: #181818" src=""",
        )

        self.setCentralWidget(self.browser)

        self.show()


app = QtWidgets.QApplication(sys.argv)
window = MainWindow()

app.exec_()`

**Comment by valvador92** [comment]
here is my conda env: @kayhayen 

name: smartblur_env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2020.10.14=0
  - jpeg=9b=vc14h4d7706e_1
  - libblas=3.9.0=5_hd5c7e75_netlib
  - libcblas=3.9.0=5_hd5c7e75_netlib
  - liblapack=3.9.0=5_hd5c7e75_netlib
  - libopencv=4.0.1=hbb9e17c_0
  - libpng=1.6.37=h2a8f88b_0
  - libsodium=1.0.18=h62dcd97_0
  - libtiff=4.1.0=h56a325e_1
  - lz4-c=1.9.2=hf4a77e7_3
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - msys2-conda-epoch=20160418=1
  - ninja=1.10.2=h2d74725_1
  - nomkl=1.0=h5ca1d4c_0
  - numpy=1.21.4=py39h6635163_0
  - openssl=1.1.1l=h8ffe710_0
  - pip=21.3.1=pyhd8ed1ab_0
  - pybind11=2.9.0=py39h2e07f2f_0
  - pybind11-global=2.9.0=py39h2e07f2f_0
  - pyopengl=3.1.5=py_0
  - python=3.9.7=h6244533_1
  - python_abi=3.9=2_cp39
  - pywin32=303=py39hb82d6ee_0
  - setuptools=60.5.0=py39hcbf5309_0
  - sqlite=3.37.0=h8ffe710_0
  - tzdata=2020b=h7b6447c_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_3
  - wheel=0.35.1=py_0
  - xz=5.2.5=h62dcd97_0
  - zlib=1.2.11=vc14h1cdd9ab_1
  - zstd=1.4.4=ha9fde0e_3
  - pip:
    - nuitka==0.6.19.4
    - pyside6==6.2.2.1
    - shiboken6==6.2.2.1

**Comment by valvador92** [comment]
Command I used to create the .exe

`nuitka --standalone --plugin-enable=pyside6 --plugin-enable=anti-bloat --output-dir Packaging_video_test --static-libpython=no video_test.py`

**Comment by valvador92** [comment]
`libcrypto-1_1-x64.dll` and `libssl-1_1-x64.dll` are packaged in the dist folder. Are other DLLs needed? @kayhayen 

Thanks for your help!

**Comment by kayhayen** [comment]
I will get to this with time, unless you are a commercial subscriber, I am not that much in the business of workarounds though. https://nuitka.net/doc/commercial.html but I expect to get to this next week.

**Comment by valvador92** [comment]
@kayhayen Hey! Thank you very much for your help. Let me know once you start working on it. I am working for a Start-up. I will share with them the commercial subscriber link.

We moved from Pyinstaller to Nuitka 2 months to package our apps. This issue is blocking the release, unfortunately.

**Comment by kayhayen** [comment]
@valvador92 that’s great, once they bought priority or full package, I can promise a timely fix, but to be honest, this is otherwise not happening immediately due to well, priorities.

**Comment by valvador92** [comment]
@kayhayen I understand. However, I created a minimal script that demontrates the issue:

```
import sys
from PySide6 import QtCore, QtNetwork, QtWidgets


class CheckConnectivity(QtCore.QObject):
    def __init__(self, *args, **kwargs):
        QtCore.QObject.__init__(self, *args, **kwargs)
        url = QtCore.QUrl("https://www.google.com/")
        req = QtNetwork.QNetworkRequest(url)
        self.net_manager = QtNetwork.QNetworkAccessManager()
        self.res = self.net_manager.get(req)
        self.res.finished.connect(self.processRes)
        self.msg = QtWidgets.QMessageBox()

    @QtCore.Slot()
    def processRes(self):
        if self.res.bytesAvailable():
            self.msg.information(None, "Info", "You are connected to the Internet.")
        self.res.deleteLater()


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    ic = CheckConnectivity()
    sys.exit(app.exec())
```
Nuitka command:
nuitka --standalone --plugin-enable=pyside6 --output-dir Packaging_check_connectivity check_connectivity.py

The problem is this QtNetwork. I am getting same error than with the other example when packaging. And It works fine when running from terminal..

```
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No TLS backend is available
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No TLS backend is available
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No TLS backend is available
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No TLS backend is available
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
```

**Comment by kayhayen** [comment]
Yes, minimal is great. I am pretty sure this about Anaconda, and figuring out their differences there will take some time.

**Comment by junbaibai0719** [comment]
Copy PySide6/plugins/tls。

**Comment by kayhayen** [comment]
Yes, seems to be a case of not using `--include-qt-plugins` with required values. Since this never got a reproducer, I don't see any value in this issue anymore.
