### ISSUE TITLE
Undefined reference to SQLite

### ISSUE THREAD

**Issue by anki-code** [Nuitka/Nuitka#1392]
Hello!
I'm trying to build statically linked standalone app with Nuitka.  [The full set of commands is here](https://github.com/anki-code/xonsh-portable-binary/blob/main/drafts/xonsh-portable-musl-alpine-Python-3.9-make.Dockerfile).

To compile statically linked Python I'm using [python-cmake-buildsystem](https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/issues/309) and as result I have `libpython3.9.a` file with `sqlite` on board.

Then I try to build using Nuitka:
```bash
export LDFLAGS "-static -l:libpython3.9.a"
nuitka3 --python-flag=no_site --python-flag=no_warnings --standalone --follow-imports xonsh/xonsh
```
And as result I've got an errors:
```python

...

Nuitka-Scons:INFO: Running gcc -o module.xonsh.ply.ply.yacc.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-declarations -fno-var-tracking -Wno-misleading-indentation -fcompare-debug-second -O3 -I/usr/include -D__NUITKA_NO_ASSERT__ -D_NUITKA_STANDALONE -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=164 -D_NUITKA_EXE -I/usr/local/include/python3.9 -I. -I/usr/local/lib/python3.9/site-packages/nuitka/build/include -I/usr/local/lib/python3.9/site-packages/nuitka/build/static_src module.xonsh.ply.ply.yacc.c took 66.11 seconds

/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../lib/libpython3.9.a(connection.c.o): in function `pysqlite_connection_dealloc':
/python/Python-3.9.10/Modules/_sqlite/connection.c:258: undefined reference to `sqlite3_close_v2'

/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../lib/libpython3.9.a(connection.c.o): in function `_pysqlite_set_result':
/python/Python-3.9.10/Modules/_sqlite/connection.c:533: undefined reference to `sqlite3_result_text'

/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /python/Python-3.9.10/Modules/_sqlite/connection.c:521: undefined reference to `sqlite3_result_double'

/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /python/Python-3.9.10/Modules/_sqlite/connection.c:519: undefined reference to `sqlite3_result_int64'

...

/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../lib/libpython3.9.a(util.c.o):/python/Python-3.9.10/Modules/_sqlite/util.c:90: more undefined references to `sqlite3_errmsg' follow
collect2: error: ld returned 1 exit status
scons: *** [/xonsh/xonsh.dist/xonsh] Error 1
```

As you can see the errors are around sqlite.

Could you please give an advice what I'm doing wrong? [The full set of commands is here](https://github.com/anki-code/xonsh-portable-binary/blob/main/drafts/xonsh-portable-musl-alpine-Python-3.9-make.Dockerfile). Thanks!

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by kayhayen** [comment]
Static Python is coming with Nuitka-Python eventually. Unfortunately, I cannot support corner configs like this outside of https://nuitka.net/doc/commercial.html esp. not for people who cannot fill out an issue template.

**Comment by anki-code** [comment]
Can I pay for solving this issue without year subscription?

**Comment by kayhayen** [comment]
Stupid question, free, but I am suspecting you are requiring static linking, but SQLite doesn't have a static link library installed.

**Comment by anki-code** [comment]
> but SQLite doesn't have a static link library installed.

To build static Python I installed `sqlite-dev` and `sqlite-static` packages with `/usr/lib/libsqlite3.a ` and `/usr/include/libsqlite3.h` and [the static Python do `import sqlite3` successfully](https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/issues/309#issuecomment-1019247410).

Then I tried to set LDFLAGS for Nuitka with or without static SQLite:

```bash
export LDFLAGS "-static -l:libpython3.9.a"
# or
# export LDFLAGS "-static -l:libpython3.9.a -l:libsqlite3.a"
nuitka3 --python-flag=no_site --python-flag=no_warnings --standalone --follow-imports xonsh/xonsh
```

And I got many `undefined reference to `sqlite3_******` errors. My thought that I missed some additional flags for right references i.e. may be I should set CCFLAGS with including `libsqlite3.h` file (I already tried this with no result).

**Comment by kayhayen** [comment]
What does `python-config --libs` and the likes have to say?

**Comment by kayhayen** [comment]
What does `python-config --libs` and the likes have to say?

**Comment by anki-code** [comment]
If you mean the Python that was used to run Nuitka then nothing special I think:
```
python-config
Usage: /usr/local/bin/python-config --prefix|--exec-prefix|--includes|--libs|--cflags|--ldflags|--extension-suffix|--help|--abiflags|--configdir|--embed

python-config --prefix
/usr/local

python-config --exec-prefix
/usr/local

python-config --includes
-I/usr/local/include/python3.9 -I/usr/local/include/python3.9

python-config --libs
 -ldl  -lm -lm 

python-config --cflags
-I/usr/local/include/python3.9 -I/usr/local/include/python3.9  -Wno-unused-result -Wsign-compare  -DNDEBUG -g -fwrapv -O3 -Wall

python-config --ldflags
 -L/usr/local/lib  -ldl  -lm -lm 

python-config --extension-suffix
.cpython-39-x86_64-linux-gnu.so

python-config --abiflags


python-config --configdir
/usr/local/lib/python3.9/config-3.9-x86_64-linux-gnu

python-config --embed

```

**Comment by kayhayen** [comment]
I can only recommend you to avoid your static linking flag and instead change (if at all necessary) Nuitka such that --static-libpython=yes works properly. Nuitka is not using `-static` there. Maybe that helps. Your config is either broken for embedding Python, or not though.

**Comment by anki-code** [comment]
No success.
```bash
mkdir /tmp/bld
cd /tmp/bld
echo "import sqlite3; print('ok')" > ttt.py
nuitka3 --static-libpython=yes --standalone ttt.py

# Test on the same system
./ttt.dist/ttt
# ok

# Test static binary of clean Ubuntu with docker
docker run -it --rm -v $PWD:/data ubuntu /data/ttt.dist/ttt
# /data/ttt.dist/ttt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /data/ttt.dist/ttt)

```

**Comment by kayhayen** [comment]
Your container might be an older Linux. You have to compile on the oldest Linux you want to support. The glibc is not included in the dist folder, because it's tried to kernel versions. If you think you can compile on brand new Linux and execute on old Linux, well you are dreaming. Instead you compile e.g. in a CentOS 7 container and be good, or even CentOS 6, depending on how ancient you want to become.

But the good news is that your build works. However, I thought you were using musl C library, which is this suddenly using glibc.

And I honestly don't know, but maybe musl doesn't prevent backporting, but I would think it much rather does, since it's supposed to be light, so it won't have all kernels supported, or would it.

**Comment by anki-code** [comment]
If I try to build using the older Linux and run on the fresh Linux I get the error `ImportError: /tmp/bld/_sqlite3.so: cannot open shared object file`:

```bash
docker run -it --rm ubuntu:16.04

apt update
apt install patchelf python3 python3-pip gcc make 
pip3 install nuitka

mkdir /tmp/bld
cd /tmp/bld
echo "import sqlite3; print('ok')" > ttt.py


nuitka3 --static-libpython=yes --standalone ttt.py

./ttt.dist/ttt 
# ok
```
Copy to the fresh linux on the host and run:
```bash
docker cp CID:/tmp/bld/ttt.dist/ttt .
./ttt
#Traceback (most recent call last):
#  File "/tmp/bld/ttt.py", line 1, in <module>
#    import sqlite3; print('ok')
#  File "/tmp/bld/sqlite3/__init__.py", line 23, in <module>
#  File "/tmp/bld/sqlite3/dbapi2.py", line 27, in <module>
#ImportError: /tmp/bld/_sqlite3.so: cannot open shared object file: No such file or directory
```

**Comment by kayhayen** [comment]
Try a `ldd /tmp/bld/_sqlite3.so` on new Linux, and tell me what it says.

**Comment by anki-code** [comment]
There is no `/tmp/bld/_sqlite3.so` on the new Linux because this path is from the old Linux in docker.

**Comment by kayhayen** [comment]
Ah, now I see what you did, the .dist folder needs to be transferred as a whole, or a onefile binary, copying the binary out of the dist folder is not giving you standalone.

**Comment by anki-code** [comment]
Got it! This is working:
```python
docker run -it --rm --cap-add SYS_ADMIN --device /dev/fuse --security-opt apparmor:unconfined --cap-add MKNOD ubuntu:18.04

apt update && apt install patchelf python3 python3-pip gcc make zlib1g-dev git fuse
pip3 install nuitka

mkdir /xonsh
cd xonsh
git clone -n https://github.com/xonsh/xonsh && cd xonsh && git checkout 7168b26
nuitka3 --static-libpython=yes --standalone --onefile xonsh
./xonsh.bin
```

**Comment by kayhayen** [comment]
You can use``--onefile-tempdir` to make it use the bootstrap. Just needs python-zstandard to be compressed.

Is there old Alpine containers?

**Comment by kayhayen** [comment]
Yes,. you cannot see it, but it still is there.

**Comment by anki-code** [comment]
Can you give a bit more details please.

**Comment by anki-code** [comment]
As I see this option available for Windows. But I'm building for Linux.

https://github.com/Nuitka/Nuitka/blob/7b4c3f8f1a16ed62eb7d7b067d0a004bc409bfa2/nuitka/OptionParsing.py#L1110-L1129

**Comment by kayhayen** [comment]
Jumping to conclusions? Linux is the only platform it currently has an an effect on.

**Comment by anki-code** [comment]
Ah, I understand. Yes, it works!
```python
echo 'import sqlite3; print(1)' > /tmp/tst.py
nuitka3 --static-libpython=yes --standalone --onefile --onefile-tempdir /tmp/tst.py
./tst.bin
# 1
```
