### ISSUE TITLE
Ubuntu 14.04 needs corrections to be supported

### ISSUE THREAD

**Issue by sanluku** [Nuitka/Nuitka#1393]
OS: ubuntu14.04
python: 3.7
Nuitka: 0.6.19.4

The last output below:
Nuitka:INFO: Completed Python level compilation and optimization.                                                                               
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Total memory usage before generating C code: 68.36 MB (71684096 bytes):
Nuitka:INFO: Total memory usage before running scons: 82.96 MB (86994944 bytes):                                                                
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Compiled 50 C files using ccache.                                                                                            
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 50
Nuitka-Plugins:INFO: pyqt5: Including Qt plugins 'egldeviceintegrations,iconengines,imageformats,mediaservice,platforms,platformthemes,printsupport,wayland-decoration-client,wayland-graphics-integration-client,wayland-shell-integration,xcbglintegrations' below 'PyQt5/qt-plugins'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/nuitka/__main__.py", line 137, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/nuitka/__main__.py", line 123, in main
    MainControl.main()
  File "/usr/local/lib/python3.7/site-packages/nuitka/MainControl.py", line 955, in main
    addIncludedEntryPoints(Plugins.considerExtraDlls(dist_dir, module))
  File "/usr/local/lib/python3.7/site-packages/nuitka/plugins/Plugins.py", line 419, in considerExtraDlls
    for extra_dll in plugin.considerExtraDlls(dist_dir, module):
  File "/usr/local/lib/python3.7/site-packages/nuitka/plugins/PluginBase.py", line 392, in considerExtraDlls
    for included_entry_point in self.getExtraDlls(module):
  File "/usr/local/lib/python3.7/site-packages/nuitka/plugins/standard/ImplicitImports.py", line 1212, in getExtraDlls
    uuid_dll_path = self.locateDLL("uuid")
  File "/usr/local/lib/python3.7/site-packages/nuitka/plugins/PluginBase.py", line 353, in locateDLL
    return locateDLL(dll_name)
  File "/usr/local/lib/python3.7/site-packages/nuitka/utils/SharedLibraries.py", line 103, in locateDLL
    assert b" (" in left, line
AssertionError: b'\t (libc6,x86-64) => /home/suhaihui/MakeSoft/Main/Build/MainApp/'

My package command:
root@ubuntu:/home/suhaihui/testNuitka# python -m nuitka --standalone --show-progress --plugin-enable=qt-plugins --include-package=PyQt5 --follow-imports hello2.py

Did i do anything wrong?
Waiting for your reply.

**Comment by kayhayen** [comment]
I think CentOS 7/Fedora 19 are working. It seems the `ldd` output produces unexpected output on Ubuntu 14.04, which would need investigation. I think it once worked, and surely I can add it back to that state, but outside of commercial support  https://nuitka.net/doc/commercial.html I don't think I can spend the time.

**Comment by kayhayen** [comment]
This works with my `python3.10 bin/run-inside-nuitka-container --container=Ubuntu1404 --command="python3 bin/nuitka tests/standalone/CtypesUsing.py"` based test perfectly fine, so this is either obsolete or was never valid. Also has had no reproducer.
