### ISSUE TITLE
--onefile updating static files without rebooting

### ISSUE THREAD

**Issue by Svinaug** [Nuitka/Nuitka#1394]
I create an exe with the following command:

`python -m nuitka --mingw64 --standalone --onefile 'app.py'`

The program uses the settings file "config.txt". In the program code itself, the settings file is accessed along the following path:

`with open("config.txt" ....`

If I manually change the "config.txt" file, then the program launched through this exe will not see these changes until the exe is reloaded. How can I make the program see the changes without rebooting when I change it manually? I know that when I run the exe, the files are unpacked to the temp directory, but I did not find this configuration file "config.txt" there - how then does the program access it from the code?

**Comment by kayhayen** [comment]
There are options for including data files in the binary. If you don't use them, the file will not be there. Also in the user manual, there is a section about how to access file near the onefile binary (in case it should not be included and modifiable) and files near the temporary files.
