### ISSUE TITLE
Compile source in unicode paths could fail on Windows

### ISSUE THREAD

**Issue by abcdesteve** [Nuitka/Nuitka#1399]
An error occurred while merging into a single file.
I close every window and app(include windows defender) to make sure nothing is using the file,however,it stll does work
I also try run as admin,but still fail
here are the error:
                Traceback (most recent call last):
                  File "C:\Program Files\Python39\lib\site-packages\nuitka\__main__.py", line 137, in <module>
                    main()
                  File "C:\Program Files\Python39\lib\site-packages\nuitka\__main__.py", line 123, in main
                    MainControl.main()
                  File "C:\Program Files\Python39\lib\site-packages\nuitka\MainControl.py", line 968, in main
                    packDistFolderToOnefile(dist_dir, binary_filename)
                  File "C:\Program Files\Python39\lib\site-packages\nuitka\freezer\Onefile.py", line 72, in packDistFolderToOnefile
                    packDistFolderToOnefileBootstrap(onefile_output_filename, dist_dir)
                  File "C:\Program Files\Python39\lib\site-packages\nuitka\freezer\Onefile.py", line 359, in packDistFolderToOnefileBootstrap
                    with open(onefile_output_filename, "ab") as output_file:
                PermissionError: [Errno 13] Permission denied: 'D:\\Users\\abcdesteve\\Desktop\\temp\\out\\main.exe'

another thing is that I found nuitka doesn't support Chinese path,I wonder whether it will support in the future

here is my system information
Python 3.9.9
windows 10.0.22000
Nuitka   0.6.19.4
use pip to install

**Comment by kayhayen** [comment]
Actually it is supposed to support arbitrary paths, but this may always regress unfortunately, but I am not currently aware of any issues there. Can you show what happens when you try to use it?

The Windows Defender would be my main suspect still. I am not sure if you can close it. Make sure to add a folder exclusion to it, that should be more reliable. Also please try develop, the code changed a lot there with onefile packing and how it's done.

**Comment by abcdesteve** [comment]
> Actually it is supposed to support arbitrary paths, but this may always regress unfortunately, but I am not currently aware of any issues there. Can you show what happens when you try to use it?
> 
> The Windows Defender would be my main suspect still. I am not sure if you can close it. Make sure to add a folder exclusion to it, that should be more reliable. Also please try develop, the code changed a lot there with onefile packing and how it's done.

Here I try to use Chinese path
D:\Users\abcdesteve\Desktop\神龙\神龙翻译\神龙翻译v1.7
The path is changed by the program and it couldn't find the file

\abcdesteve\desktop\绁為緳\绁為緳缈昏瘧\绁為緳缈昏瘧v1.7\out\main.build\__constants.h: No such file or directory
scons: *** [__helpers.obj] d:\users\abcdesteve\desktop\绁為緳\绁為緳缈昏瘧\绁為緳缈昏瘧v1.7\out\main.build\__constants.h: No such file or directory
scons: *** [module.PySide6-preLoad.obj] d:\users\abcdesteve\desktop\绁為緳\绁為緳缈昏瘧\绁為緳缈昏瘧v1.7\out\main.build\__constants.h: No such file or directory
scons: *** [module.charset_normalizer.assets.obj] d:\users\abcdesteve\desktop\绁為緳\绁為緳缈昏瘧\绁為緳缈昏瘧v1.7\out\main.build\__constants.h: No such file or directory
scons: *** [module.charset_normalizer.api.obj] d:\users\abcdesteve\desktop\绁為緳\绁為緳缈昏瘧\绁為緳缈昏瘧v1.7\out\main.build\__constants.h: No such file or directory
scons: *** [module.charset_normalizer.cd.obj] d:\users\abcdesteve\desktop\绁為緳\绁為緳缈昏瘧\绁為緳缈昏瘧v1.7\out\main.build\__constants.h: No such file or directory
scons: *** [module.charset_normalizer.obj] d:\users\abcdesteve\desktop\绁為緳\绁為緳缈昏瘧\绁為緳缈昏瘧v1.7\out\main.build\__constants.h: No such file or directory
scons: *** [module.charset_normalizer.md.obj] d:\users\abcdesteve\desktop\绁為緳\绁為緳缈昏瘧\绁為緳缈昏瘧v1.7\out\main.build\__constants.h: No such file or directory
scons: *** [module.PySide6.obj] d:\users\abcdesteve\desktop\绁為緳\绁為緳缈昏瘧\绁為緳缈昏瘧v1.7\out\main.build\__constants.h: No such file or directory
scons: *** [module.PySide6.QtCore-postLoad.obj] d:\users\abcdesteve\desktop\绁為緳\绁為緳缈昏瘧\绁為緳缈昏瘧v1.7\out\main.build\__constants.h: No such file or directory
scons: *** [module.charset_normalizer.constant.obj] d:\users\abcdesteve\desktop\绁為緳\绁為緳缈昏瘧\绁為緳缈昏瘧v1.7\out\main.build\__constants.h: No such file or directory
scons: *** [module.charset_normalizer.legacy.obj] d:\users\abcdesteve\desktop\绁為緳\绁為緳缈昏瘧\绁為緳缈昏瘧v1.7\out\main.build\__constants.h: No such file or directory
scons: *** [module.charset_normalizer.models.obj] d:\users\abcdesteve\desktop\绁為緳\绁為緳缈昏瘧\绁為緳缈昏瘧v1.7\out\main.build\__constants.h: No such file or directory
scons: *** [module.certifi.core.obj] d:\users\abcdesteve\desktop\绁為緳\绁為緳缈昏瘧\绁為緳缈昏瘧v1.7\out\main.build\__constants.h: No such file or directory
scons: *** [module.__main__.obj] d:\users\abcdesteve\desktop\绁為緳\绁為緳缈昏瘧\绁為緳缈昏瘧v1.7\out\main.build\__constants.h: No such file or directory
scons: *** [module.certifi.obj] d:\users\abcdesteve\desktop\绁為緳\绁為緳缈昏瘧\绁為緳缈昏瘧v1.7\out\main.build\__constants.h: No such file or directory

**Comment by abcdesteve** [comment]
> Actually it is supposed to support arbitrary paths, but this may always regress unfortunately, but I am not currently aware of any issues there. Can you show what happens when you try to use it?
> 
> The Windows Defender would be my main suspect still. I am not sure if you can close it. Make sure to add a folder exclusion to it, that should be more reliable. Also please try develop, the code changed a lot there with onefile packing and how it's done.

Also could you give me a link to tell me which develop to install?

**Comment by Maxwell175** [comment]
> Also could you give me a link to tell me which develop to install?

You can find instruction on installing develop using pip here:
https://nuitka.net/doc/download.html#pypi

**Comment by kayhayen** [comment]
That looks like MinGW64 not being good at this Chines path. however Nuitka passes an "external" path, which is a short 8.3 filesystem path, maybe this has regressed somehow, but it saves scons and gcc from seeing these filenames. I will try with your path. I think NTFS should still do that for you, unless you somehow managed to disable that. Lets see how I fare with it.

**Comment by kayhayen** [comment]
MSVC is what I used now, and I had to fix an encoding bug for the report Nuitka writes inside Scons, but then I indeed get this one:

```
scons: *** [__constants.obj] c:\users\kayha\test\??????????v1.7\mini.build\__constants.h: Invalid argument
scons: *** [__helpers.obj] c:\users\kayha\test\??????????v1.7\mini.build\__constants.h: Invalid argument
scons: *** [module.__main__.obj] c:\users\kayha\test\??????????v1.7\mini.build\__constants.h: Invalid argument
```

**Comment by kayhayen** [comment]
So, Nuitka did it for Python2, where Scons has had issues, checking if the path in `unicode` is different from ANSI on Windows, and sort of minimizing it. But it seems that the current directory, being your path, doesn't work with MSVC (and probably MinGW64 neither, I think you used it). It seems fixed. I have had issues with caching of `clcache`, and similarly expect them from `ccache`, they repeated the error from cache. For that, find Nuitka in your local Windows Appdata and just remove it all once you have the fix.

I will need to do more tests.

**Comment by kayhayen** [comment]
Ok, seems clcache is a victim of MSVC which apparently will not use the short paths in its compiler output that clcache requested:

>Note: including file: C:\Users\kayha\test\??????????v1.7\Mini.build\__helpers.h

This is leading to an exception when trying to open these kinds of files for reading. So using `--disable-ccache` works around that, as might be using MinGW64 with `--mingw64`.

The `clcache` wants to know what files were read in order to checksum them. MSVC must be doing some sort of escaping out of the short path. I checked and there is just no way it would have that current directory to be anything but that.

**Comment by kayhayen** [comment]
Yes indeed, `ccache` needs my fix, but then it works well with MinGW64 in that directory, but for MSVC there may not be a fix possible. There is no way to tell MSVC to not use an encoding that cannot output these names, unless you change the locale of MSVC to match it (maybe), but that is a bad idea, it will cause other issues.

**Comment by abcdesteve** [comment]
> Actually it is supposed to support arbitrary paths, but this may always regress unfortunately, but I am not currently aware of any issues there. Can you show what happens when you try to use it?
> 
> The Windows Defender would be my main suspect still. I am not sure if you can close it. Make sure to add a folder exclusion to it, that should be more reliable. Also please try develop, the code changed a lot there with onefile packing and how it's done.

I try the develop version,and it works quite well. And I found nothing wrong with one-file mode so far.
I am pretty surprised that nuitka even support webengine. (pyinstaller doesn't support it)
However,Chinese path still doesn't work as you tested.
Hope that the problem will be fixed soon. 
: )

**Comment by kayhayen** [comment]
One workaround for the Chinese build path might be to use `--output-dir` to outside it. However, I am assuming this to be your Windows username, and as such it will be inconvenient, and then potentially Nuitka install is going to be affected still as MSVC will report about files used there.

The bizarre thing is that MSVC insist on breaking out of the short path names and displays full names. The internet is full of people having issues like you encountered here with MSVC.

What I want to do is to at least have some sort of detection of the issue. I was also considering a workaround, where a few missing characters would be compensated for. The other is a design change of how clcache works (which we kind of maintain now ourselves), and make it more similar to clcache, where you ask it to dump the code after pre-procesor and then just checksum that. Right now it makes MSVC output the filenames, and then checksums them. And as I noticed, the clcache in Nuitka is not taking advantage of this being almost the same file set for all compilations. Want to research how feasible that is first.

**Comment by kayhayen** [comment]
So, I pushed changes to factory that solve it all of MSVC and MinGW64, ccache and clcache. For clcache turns out there is a mode that we didn't use, where it will look at the generated pre-processor output of the compiler rather than trying to scan for used source files itself. With that, it's working flawless. It's currenlty on https://nuitka.net/doc/factory.html but I expect to include it in the next hotfix release later this week.

**Comment by kayhayen** [comment]
This is part of 0.6.19.5 hotfix release.
