### ISSUE TITLE
PySide2 combo issues

### ISSUE THREAD

**Issue by gerryavr** [Nuitka/Nuitka#1402]
#The combo box functions not working properly after compiled with nuitka 
#self.combo.currentTextChanged.connect( self.comboChanged)  # - not working with nuitka
#self.combo.currentIndexChanged().connect( self.comboChanged) # - not working with nuitka

from PySide2 import QtGui
from PySide2 import QtWidgets
from PySide2.QtWidgets import QApplication, QDialog, QComboBox, QVBoxLayout, QLabel
import sys

class Window(QDialog):
    def __init__(self):
        super().__init__()

        self.title = "PySide2 Combo Box"
        self.top = 200
        self.left = 500
        self.width = 300
        self.height = 100
        self.InitWindow()

    def InitWindow(self):
        #self.setWindowIcon( QtGui.QIcon( "icon.png" ) )
        self.setWindowTitle( self.title )
        self.setGeometry( self.left, self.top, self.width, self.height )
        vbox = QVBoxLayout()

        self.combo = QComboBox()
        self.combo.addItem("Python")
        self.combo.addItem("Java")
        self.combo.addItem("C++")
        self.combo.addItem("C#")
        self.combo.addItem("Ruby")

        self.combo.currentTextChanged.connect( self.comboChanged)
        self.combo.setStyle(QtWidgets.QStyleFactory.create("fusion"))

        self.label = QLabel()
        self.label.setFont( QtGui.QFont("Sanserif",15))
        self.label.setStyleSheet('color:red')

        vbox.addWidget(self.combo)
        vbox.addWidget(self.label)
        self.setLayout(vbox)
        self.show()

    def comboChanged(self):
        text = self.combo.currentText()
        self.label.setText( "You Have Selected : " + text )

if __name__ == '__main__':
    app = QApplication( sys.argv )
    window = Window()
    window.show()
    sys.exit(app.exec_())

**Comment by kayhayen** [comment]
PySide support in Nuitka is only supposed to be good with this: https://nuitka.net/pages/pyside2.html if you require to use PySide2, you need to subscribe to Nuitka commercial: https://nuitka.net/doc/commercial.html

**Comment by gerryavr** [comment]
hi,
how can I know that my application will fully support and work by the commercial nuitka version after I buy the commercial license?

**Comment by kayhayen** [comment]
Short answer is: After you buy, you can know. So far, I have had zero complaints about those wheels. That is what I know, but I might be lying, so who knows.
