### ISSUE TITLE
Does nuitka really support Chinese?

### ISSUE THREAD

**Issue by 29benteng** [Nuitka/Nuitka#1403]
Hi, I met the same problem, and it is not solved.

nuitka --mingw64 --show-progress --standalone --output-dir=Output ADB_Main.py

python 3.6 64bit
nuitka 0.6.19.4
os:Windows 7
Arch:x86_64

I use nuitka to package the python script into an exe program. After running the program, the Chinese prompt information in the python script is displayed as a garbled state on the cmd command line.

Does nuitka support Chinese?

Like this:
(Display in python)
【初始化】本函数文件是团圆饭ADB操作助手，正在运行中...
【初始化】下方是您连接的设备列表，请确认列表中已经有您的设备...
List of devices attached

【初始化】如果未找到您的设备，请连接好ADB后重新运行...
【输入】请输入屏幕宽度（像素）：

 ↓ (after Compiled)

(Display in the exe)
銆愬垵濮嬪寲銆戞湰鍑芥暟鏂囦欢鏄洟鍦嗛キADB鎿嶄綔鍔╂墜锛屾鍦ㄨ繍琛屼腑...
銆愬垵濮嬪寲銆戜笅鏂规槸鎮ㄨ繛鎺ョ殑璁惧鍒楄〃锛岃纭鍒楄〃涓凡缁忔湁鎮ㄧ殑璁惧...
List of devices attached

銆愬垵濮嬪寲銆戝鏋滄湭鎵惧埌鎮ㄧ殑璁惧锛岃杩炴帴濂紸DB鍚庨噸鏂拌繍琛?..
銆愯緭鍏ャ€戣杈撳叆灞忓箷瀹藉害锛堝儚绱狅級锛

Obviously,  the coding utf-8 and gb2312 are mistaken...(Although I added a _#coding=utf-8_ at the beginning of the .py file)

**Comment by kayhayen** [comment]
The output encoding for some Python versions are wrong on Windows. Use e.g. 3.7 or higher and this should be good.

This code shows the workaround Nuitka is making:

```
// Workaround older Python not handling stream setup on redirected files properly.
#if PYTHON_VERSION >= 0x340 && PYTHON_VERSION < 0x380
    {
        char const *encoding = NULL;

        if (SYSFLAG_UTF8) {
            encoding = "utf-8";
        } else {
            encoding = getenv("PYTHONIOENCODING");
            if (encoding == NULL) {
                encoding = "utf-8";
            }
        }

        Py_SetStandardStreamEncoding(encoding, NULL);
    }
#endif
```

If you output to a file in another way that print, you ought to see that your source code is properly parsed.

**Comment by kayhayen** [comment]
And the real "why" is that it takes a ton of code for these Python versions to access the locales and codecs registry of Python and match them up, therefore I will probably not implement it. You can however try to set `PYTHONIOENCODING` on the outside with what you know to be correct. That*s as good as it gets outside of commercial funding for me to work on it.

**Comment by 29benteng** [comment]
Thank you for helping me, I'll try it on another OS and higher version of python. Maybe that works!
Nuitka is a really great tool, I love it and I hope it will continue developing forever! 

Besides, I would also like to extend my sincere wishes to you on the occasion of our Chinese Spring Festival. Have a great day! 
  :-)
