### ISSUE TITLE
Nuitka installation script not working properly on Ubuntu

### ISSUE THREAD

**Issue by hashuser** [Nuitka/Nuitka#1404]
**Problem**: When I tried to install Nuitka on Ubuntu using the official [script](https://nuitka.net/doc/download.html#debian-ubuntu-mint), it failed. I spent some time and figured out why. There are several reasons. @kayhayen 

**ENVIRONMENT**
Ubuntu 20.04.3 LTS

**1# The script has some issues**
```shell
CODENAME=`egrep 'UBUNTU_CODENAME|VERSION_CODENAME' /etc/os-release | cut -d= -f2`
```
Both ```UBUNTU_CODENAME``` and ```VERSION_CODENAME``` will return the same **CODENAME**. Consequetly, ```$CODENAME``` would equal to ```focal\nfocal``` in Ubuntu Focal. Therefore, if you run ```apt-get update``` you will get an error below.
 ```
E: Malformed entry 1 in list file /etc/apt/sources.list.d/nuitka.list (Suite)
```
My solution to this problem is just simply delete ```UBUNTU_CODENAME```. This can eliminate not only duplicated **CODENAME** but also nasty ```\n```. According to my test, it works quite well (at least in Ubuntu Focal)

**My Fix**:
```shell
CODENAME=`egrep 'VERSION_CODENAME' /etc/os-release | cut -d= -f2`
if [ -z "$CODENAME" ]
then
   CODENAME=`lsb_release -c -s`
fi
wget -O - https://nuitka.net/deb/archive.key.gpg | apt-key add -
echo >/etc/apt/sources.list.d/nuitka.list "deb https://nuitka.net/deb/stable/$CODENAME $CODENAME main"
apt-get update
apt-get install nuitka
```
**Before Fix**:

![屏幕截图 2022-02-01 203946](https://user-images.githubusercontent.com/60065064/151973910-79c587df-db71-4d74-b1a1-01fd34f07d85.png)

![屏幕截图 2022-02-01 203901](https://user-images.githubusercontent.com/60065064/151974702-35c9756c-1b0b-489f-bb20-580c87d9abe0.png)

**After Fix**:

![屏幕截图 2022-02-01 204323](https://user-images.githubusercontent.com/60065064/151976101-9964e6db-ba17-4e80-bf09-7fe05a452c2c.png)

**2# CA Certs has some issues**
Since Ubuntu Focal is a Linux distribution, CA Certs are not frequently updated. Let's Encrypt recently changed it's issuance chain, and only those platforms that trust ISRG Root X1 will validate Let’s Encrypt certificates. Unfortunatly, as nuitka.net uses Let's Encrypt, users need manually update CA. ```apt-get install ca-certificates``` is required, otherwise you will get the error below.
```
Certificate varification failed: The certificate is NOT trusted. The certificate chain uses expired certificate. Could not handshake: Error in the certificate verification.
```
Therefore, I suggest we should add ```apt-get install ca-certificates``` in the script, and it will eliminate this problem by automatically updating CA to the latest version.

**My Fix**:
```shell
CODENAME=`egrep 'VERSION_CODENAME' /etc/os-release | cut -d= -f2`
if [ -z "$CODENAME" ]
then
   CODENAME=`lsb_release -c -s`
fi
wget -O - https://nuitka.net/deb/archive.key.gpg | apt-key add -
echo >/etc/apt/sources.list.d/nuitka.list "deb https://nuitka.net/deb/stable/$CODENAME $CODENAME main"
apt-get install ca-certificates
apt-get update
apt-get install nuitka
```

**Before Fix**:

![屏幕截图 2022-02-01 204125](https://user-images.githubusercontent.com/60065064/151980431-c37b4d3b-caa6-4617-8992-9d49fe3fd721.png)

**Comment by kayhayen** [comment]
Very interesting, I think the `|` is there, because this was once working for both Debian and Ubuntu and they each specified only one. Not sure if all Ubuntu specify `UBUNTU_CODENAME`, so I would change it to test first for one, then the other. I am not seeing a new line added, but a space. The case of having both, I will solve by using `sort` which makes the Ubuntu line definitely first, and then `head -1` and then cut should be working on a single line.

```
CODENAME=`egrep 'UBUNTU_CODENAME|VERSION_CODENAME' /etc/os-release | sort | head -1 | cut -d= -f2`
````

I assume you can confirm this works for you, I tested it with an input file with both values, and single match as well, where it still works on my Debian bullseye.

For the root certificate issue, I was totally unaware of these things. I am adding the installation command as you say.

**Comment by hashuser** [comment]
@kayhayen Thank you very much! I've tested the new official installation script, and it works pretty well on my Ubuntu.

**Comment by kayhayen** [comment]
Great, thank you for taking the time to report.

**Comment by Petros626** [comment]
hey @hashuser,

i followed all the steps on thehomepage of nuitka with the corrections as you mentioned, but it still says:

nuitka command not found.

**Comment by kayhayen** [comment]
The main binary is not called `nuitka` but `nuitka3` or `nuitka2` and if you read the user manual, you will see it's not the recommended way to use Nuitka to run these.

**Comment by kayhayen** [comment]
And Linux power user tip, use the `TAB` key. :-)
