### ISSUE TITLE
Bug inspecting frames in closures

### ISSUE THREAD

**Issue by fernandoenzo** [Nuitka/Nuitka#1409]
> 0.6.19.6
> Commercial: None
> Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
> Flavor: Debian Python
> Executable: /usr/bin/python3
> OS: Linux
> Arch: x86_64
> Distribution: Debian 11

Hello,
I just detected a bug that has been driving me crazy for hours. When I inspect `f_locals` in a closure context, the dict is empty if the module is compiled with Nuitka. However, it's filled when running normally with Python.

Here's a very simple example code:
```python
import inspect

def External():
    def func():
        return None

    class Inner:

        def __init__(self):
            print(inspect.currentframe().f_locals)
            print(inspect.currentframe().f_back.f_locals)
            print(inspect.currentframe().f_back.f_back.f_locals)
    
    return Inner()

External()
```

Output when run with Python:

```
{'self': <__main__.External.<locals>.Inner object at 0x7f08bb951dd8>}
{'func': <function External.<locals>.func at 0x7f08bb88eae8>, 'Inner': <class '__main__.External.<locals>.Inner'>}
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x7f08bb9f2f28>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>,
'__file__': 'hola.py', '__cached__': None, 'inspect': <module 'inspect' from '/usr/lib/python3.9/inspect.py'>, 'External': <function External at 0x7f08bba701e0>} 
```

Output when compiled with option `--standalone`:

```
{}
{}
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class 'nuitka_module_loader'>, '__spec__': None, '__compiled__': __nuitka_version__(major=0, minor=6, micro=19, releaselevel='release', standalone=True, onefile=False), '__builtins__': <module 'builtins' (built-in)>, '__file__': '/home/fernando/foo.dist/foo.py', '__cached__': None, '__annotations__': {}, 'inspect': <module 'inspect' from '/home/fernando/foo.dist/inspect.py'>, 'External': <compiled_function External at 0x7fc85f1fdde0>}
```

**Comment by kayhayen** [comment]
Yes, that is not supported. One day it might be, it has nothing to do with standalone at all. 

Frames for functions are populated when an exception occurs, but until then live on the local stack. One day, the frame object might become the primary storage for local variables, and then it would be possible to produce `f_locals` whenever asked, but it's not a good idea to use it anyway. You can use `locals()` in the current context, that will work.

In your example, Nuitka might one day also optimize the class away, so how is the frame stack supposed to match your expectations then?

Yours,
Kay

Yours,
Kay

**Comment by fernandoenzo** [comment]
Thank you so much for your reply and explanation.
