### ISSUE TITLE
FATAL: Error, call to 'patchelf' failed (PySide6 + QML)

### ISSUE THREAD

**Issue by arkadiim** [Nuitka/Nuitka#1410]
* Nuitka version, full Python version, flavor, OS, etc. as output by this
  command (it does more than you think, and we are adding more all the time):
  >0.6.19.6
Commercial: None
Python: 3.10.1 (main, Jan  4 2022, 05:20:14) [GCC 9.3.0]
Flavor: Unknown
Executable: /home/am/prm/python/nuitka-issue/.venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu 20.04.3

* How did you install Nuitka and Python
  > pip install nuitka

* The specific PyPI names and versions
  > Nuitka==0.6.19.6
PySide6==6.2.3
shiboken6==6.2.3

* This is the basic hello world of QML from two files main.py and main.qml.
Build command fails with a **fatal error** when calling patchelf

```python
# main.py
from PySide6.QtGui import QGuiApplication
from PySide6.QtQml import QQmlApplicationEngine


if __name__ == '__main__':
    app = QGuiApplication()
    engine = QQmlApplicationEngine()
    engine.load('main.qml')
    app.exec()
```
```qml
// main.qml
import QtQuick
import QtQuick.Window


Window {
    visible: true

    Rectangle {
        width: 200
        height: 200

        Text {
            text: "Hello World"
        }
    }
}
```

Build command and output
```bash
 python -m nuitka --standalone --plugin-enable=pyside6 --include-qt-plugins=qml main.py
```
>(.venv) am@lp:nuitka-issue$ python -m nuitka --standalone --plugin-enable=pyside6 --include-qt-plugins=qml main.py
Nuitka-Options:INFO: Used command line options: --standalone --plugin-enable=pyside6 --include-qt-plugins=qml main.py
Nuitka-Options:INFO: Detected static libpython to exist, consider '--static-libpython=yes' for better performance, but errors may happen.
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.19.6' on Python '3.10' commercial None.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'PySide6.QtQml' added 'shiboken6,shiboken6.Shiboken,os,enum,PySide6.QtCore,PySide6.QtNetwork'.                         
Nuitka-Plugins:INFO: pyside6: Injecting post-module load code for module 'PySide6.QtCore':                                                                                                    
Nuitka-Plugins:INFO: pyside6:     Setting Qt library path to distribution folder. We need to avoid loading target                                                                             
Nuitka-Plugins:INFO: pyside6:     system Qt plugins, which may be from another Qt version.                                                                                                    
Nuitka-Plugins:INFO: pyside6: Implicit dependencies of module 'PySide6.QtQml' added 'PySide6.QtCore,PySide6.QtNetwork,PySide6.QtQuick'.                                                       
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'PySide6.QtQuick' added 'shiboken6,shiboken6.Shiboken,enum,PySide6.QtCore,PySide6.QtGui,PySide6.QtOpenGL,PySide6.QtQml'.
Nuitka-Plugins:INFO: pyside6: Implicit dependencies of module 'PySide6.QtQuick' added 'PySide6.QtCore,PySide6.QtNetwork,PySide6.QtGui,PySide6.QtQml'.                                         
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'PySide6.QtOpenGL' added 'shiboken6,shiboken6.Shiboken,enum,PySide6.QtCore,PySide6.QtGui'.                             
Nuitka-Plugins:INFO: pyside6: Implicit dependencies of module 'PySide6.QtOpenGL' added 'PySide6.QtCore,PySide6.QtGui,PySide6.QtWidgets'.                                                      
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'PySide6.QtWidgets' added 'shiboken6,shiboken6.Shiboken,enum,PySide6.QtCore,PySide6.QtGui'.                            
Nuitka-Plugins:INFO: pyside6: Implicit dependencies of module 'PySide6.QtWidgets' added 'PySide6.QtGui'.                                                                                      
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'PySide6.QtNetwork' added 'shiboken6,shiboken6.Shiboken,enum,PySide6.QtCore'.                                          
Nuitka-Plugins:INFO: pyside6: Implicit dependencies of module 'PySide6.QtNetwork' added 'PySide6.QtCore'.                                                                                     
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'PySide6.QtCore' added 'shiboken6,shiboken6.Shiboken,os,enum'.                                                         
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'PySide6.QtGui' added 'shiboken6,shiboken6.Shiboken,os,enum,PySide6.QtCore'.                                           
Nuitka-Plugins:INFO: pyside6: Implicit dependencies of module 'PySide6.QtGui' added 'PySide6.QtCore'.                                                                                         
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'socket' added '_socket'.                                                                                              
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'curses' added '_curses'.                                                                                              
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.                                                                                              
Nuitka:INFO: Completed Python level compilation and optimization.                                                                                                                             
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.                                                                                                                  
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Slow C compilation detected, used 60s so far, this might indicate scalability problems.                                                                                    
Nuitka-Scons:INFO: Running gcc -o /home/am/prm/python/nuitka-issue/main.dist/main -z noexecstack -export-dynamic -s -Wl,-R,'$ORIGIN' -Wl,--disable-new-dtags @"./@link_input.txt -L/opt/Python-3.10.1/lib -ldl -lm -lpython3.10 -ldl -lpthread -lutil -lrt -lm took 77.05 seconds
Nuitka-Scons:WARNING: You are not using ccache.                                                                                                                                               
Nuitka-Plugins:INFO: pyside6: Including Qt plugins 'qml' below 'PySide6/qt-plugins'.
FATAL: Error, call to 'patchelf' failed: ['/usr/bin/patchelf', '--set-rpath', '$ORIGIN/../../../../..', 'main.dist/PySide6/qml/Qt/labs/animation/labsanimationplugin.debug'] -> b"patchelf: patchelf.cc:1023: void setSubstr(std::string&, unsigned int, const string&): Assertion `pos + t.size() <= s.size()' failed.".

**Comment by kayhayen** [comment]
You might want to research what is wrong with `patchelf` from Ubuntu here. I wonder if it's a length issue, or if it's something to do with that `.debug` file not being real.

**Comment by kayhayen** [comment]
That said, you don't want to build standalone on the newest system on Linux, but the oldest you want to support. The resulting binary is going to run on 20.04 or higher, maybe not what you want.

**Comment by arkadiim** [comment]
Probably related to https://github.com/NixOS/patchelf/issues/207.
I updated the patchelf version (0.10 -> 0.14.3) and the error is gone. Thanks!

**Comment by kayhayen** [comment]
Yup, I would be closing this as invalid, because it's not a Nuitka bug really. But there are two things:

a) Nuitka needs to make you aware that standalone on Linux built on the system you build on, will have limits.
b) We can definitely just give both `chrpath` and `patchelf` a go. Nuitka has had `chrpath` usage before, and
could easily just restore that and try both, one working will be good enough.

**Comment by kayhayen** [comment]
I am choosing to give up on the `chrpath` fallback after reading its man page again. It's just not going to work as reliable as I want, while having test coverage is made harder.

**Comment by nrbnlulu** [comment]
Having this issue on 
```console
1.2.6
Commercial: None
Python: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Flavor: Debian Python
Executable: /home/nir/.cache/pypoetry/virtualenvs/tzv5hob-ui-5N8t_BVY-py3.10/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.1
```
deps:
```console
attrs              22.1.0 Classes Without Boilerplate
packaging          22.0   Core utilities for Python packages
pyside6            6.4.1  Python bindings for the Qt cross-platform application and UI framework
pyside6-addons     6.4.1  Python bindings for the Qt cross-platform application and UI framework (Addons)
pyside6-essentials 6.4.1  Python bindings for the Qt cross-platform application and UI framework (Essentials)
qtpy               2.3.0  Provides an abstraction layer on top of the various Qt bindings (PyQt5/6 and PySide2/6).
shiboken6          6.4.1  Python/C++ bindings helper module

```

**Comment by kayhayen** [comment]
@nrbnlulu posting below closed issues is a sure-fire way to get ignored, please open a new issue
