### ISSUE TITLE
symfit package runtime error with fit.py module

### ISSUE THREAD

**Issue by grondeau** [Nuitka/Nuitka#1411]
This issue relates to a run-time error raised in the symfit package "fit.py" routine.  Here is the traceback:

Traceback (most recent call last):
  File "C:\Users\Gary\PYfun\SYMFIT~1\SYMFIT~1.DIS\symfitexample.py", line 38, in <module>
  File "C:\Users\Gary\PYfun\SYMFIT~1\SYMFIT~1.DIS\symfit\core\support.py", line 427, in wrapped_func
  File "C:\Users\Gary\PYfun\SYMFIT~1\SYMFIT~1.DIS\symfit\core\fit.py", line 394, in __init__
  File "C:\Users\Gary\PYfun\SYMFIT~1\SYMFIT~1.DIS\symfit\core\support.py", line 427, in wrapped_func
  File "C:\Users\Gary\PYfun\SYMFIT~1\SYMFIT~1.DIS\symfit\core\fit.py", line 91, in __init__
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Unfortunately, even a small demo program requires an extensive compilation to reveal the bug.  For a demo program, I just used the example given with the symfit documentation for a fourier series fit. The code can be found here:

https://symfit.readthedocs.io/en/stable/examples/ex_fourier_series.html

from symfit import parameters, variables, sin, cos, Fit
import numpy as np
import matplotlib.pyplot as plt

def fourier_series(x, f, n=0):
    """
    Returns a symbolic fourier series of order `n`.

    :param n: Order of the fourier series.
    :param x: Independent variable
    :param f: Frequency of the fourier series
    """
    # Make the parameter objects for all the terms
    a0, *cos_a = parameters(','.join(['a{}'.format(i) for i in range(0, n + 1)]))
    sin_b = parameters(','.join(['b{}'.format(i) for i in range(1, n + 1)]))
    # Construct the series
    series = a0 + sum(ai * cos(i * f * x) + bi * sin(i * f * x)
                     for i, (ai, bi) in enumerate(zip(cos_a, sin_b), start=1))
    return series

x, y = variables('x, y')
w, = parameters('w')
model_dict = {y: fourier_series(x, f=w, n=3)}
print(model_dict)

# Make step function data
xdata = np.linspace(-np.pi, np.pi)
ydata = np.zeros_like(xdata)
ydata[xdata > 0] = 1
# Define a Fit object for this model and data
fit = Fit(model_dict, x=xdata, y=ydata)
fit_result = fit.execute()
print(fit_result)

# Plot the result
plt.plot(xdata, ydata)
plt.plot(xdata, fit.model(x=xdata, **fit_result.params).y, ls=':')
plt.xlabel('x')
plt.ylabel('y')
plt.show()

My python and nuitka version:

(myenv) C:\Users\Gary\PYfun\Symfitexample\symfitexample.dist>python -m nuitka --version
0.6.19.4
Commercial: None
Python: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\Gary\anaconda3\envs\myenv\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

Most of the packages I use were loaded through the anconcda channel.  The symfit package was loaded through conda-forge.

The command I used to start the nuitka compile:

python -m nuitka symfitexample.py --static-libpython=no --standalone --enable-plugin=numpy --enable-plugin=pyqt5 

On my modest laptop development system this short script took a good fraction of the day to build and resulted in  2.5GB .build folder and a 1.2GB .dist folder.   

I get very nearly identical errors in my application as are generated with this example.

**Comment by kayhayen** [comment]
This is working these days.
