### ISSUE TITLE
Some loaded extension modules have no __file__ value, causing e.g. runtime issue with WinRT packages (bleak / bleak_winrt)

### ISSUE THREAD

**Issue by flozz** [Nuitka/Nuitka#1413]
Hello,

I have an issue when running a WinRT-dependent application built with Nuitka. This issue was already reported as #1184 but was closed for inactivity.

## Environment

* I installed Python 3.9 using the official Windows 64bit installer from python.org.
* Nuitka was installed using `pip` in a virtualenv.

Versions:

    (__env__) C:\Users\vm0\Desktop\issue-nuitka>python -m nuitka --version
    0.6.19.6
    Commercial: None
    Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
    Flavor: Unknown
    Executable: C:\Users\vm0\Desktop\issue-nuitka\__env__\Scripts\python.exe
    OS: Windows
    Arch: x86_64
    WindowsRelease: 10

I also tried on another Windows 10 machine + Python 3.10 but I do not have access to it right now. :)

## Step to reproduce

Here is a minimal example to reproduce.

`requirements.txt`:

    bleak==0.14.2
    bleak-winrt==1.1.1
    Nuitka==0.6.19.6

`test.py`:

```python
#!/usr/bin/env python3

import bleak
```

`make.bat`:

```bat
nuitka ^
    --follow-imports ^
    --assume-yes-for-downloads ^
    --standalone ^
    test.py
```

* install dependencies (in a venv): `pip install -r requirements.txt`
* build the test: `.\make.bat`
* run the test: `.\test.dist\test.exe`

Output:

```
(__env__) C:\Users\vm0\Desktop\issue-nuitka>test.dist\test.exe
Traceback (most recent call last):
  File "C:\Users\vm0\Desktop\ISSUE-~1\TEST~1.DIS\test.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\vm0\Desktop\ISSUE-~1\TEST~1.DIS\bleak\__init__.py", line 78, in <module bleak>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\vm0\Desktop\ISSUE-~1\TEST~1.DIS\bleak\backends\winrt\scanner.py", line 7, in <module bleak.backends.winrt.scanner>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\vm0\Desktop\ISSUE-~1\TEST~1.DIS\bleak_winrt\windows\devices\bluetooth\__init__.py", line 177, in <module bleak_winrt.windows.devices.bluetooth>
AttributeError: 'NoneType' object has no attribute 'BluetoothAdapter'
```

## Workaround

To workaround the issue, I patched the `.\__env__\Lib\site-packages\bleak_winrt\__init__.py` file from:

```python
# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.0.0-alpha.6

from . import _winrt

def _import_ns_module(ns):
    import importlib.machinery
    import importlib.util

    try:
        module_name = "_bleak_winrt_" + ns.replace('.', '_')

        loader = importlib.machinery.ExtensionFileLoader(module_name, _winrt.__file__)
        spec = importlib.util.spec_from_loader(module_name, loader)
        module = importlib.util.module_from_spec(spec)
        loader.exec_module(module)
        return module
    except Exception:
        return None
```
to:

```python
# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.0.0-alpha.6

from . import _winrt

import os
_winrt.__file__ = os.path.join(os.path.dirname(__file__), "_winrt.pyd")

def _import_ns_module(ns):
    import importlib.machinery
    import importlib.util

    try:
        module_name = "_bleak_winrt_" + ns.replace('.', '_')

        loader = importlib.machinery.ExtensionFileLoader(module_name, _winrt.__file__)
        spec = importlib.util.spec_from_loader(module_name, loader)
        module = importlib.util.module_from_spec(spec)
        loader.exec_module(module)
        return module
    except Exception:
        return None
```

The issue was caused by the missing `__file__` attribute on the `_winrt` object.

----

Do not hesitate if you need more info or if you want I test things... :)

**Comment by kayhayen** [comment]
Ok, that's great, it seems I can work off that. It runs no issue on my system. I am wondering, of course, why `_winrt` has no `__file__` object in the first place, Nuitka definitely should do that, and I am pretty sure I fixed even issues, where it was not present during load, so how would that be missing. But I am going to find out. :)

**Comment by kayhayen** [comment]
As an aside, I would like to thank you for attempting to track this down yourself.

**Comment by kayhayen** [comment]
In case there are other things with WinRT, e.g. DLLs and other modules as implicit dependencies, let me know. It looks as if the dynamic load from the module referenced might be causing issues with hidden imports.

**Comment by davidleon** [comment]
cefpython3 also has problems with missing __file__. currently the build fails at File "helpers.pyx", line 60, in cefpython_py38.GetModuleDirectory. the code in cefpython3 is path = os.path.dirname(os.path.realpath(__file__)).

**Comment by kayhayen** [comment]
This has long been released and should be working well. Posting below unrelated issues is a surefire way to get ignored @davidleon
