### ISSUE TITLE
Path prefix support for two-steps build (code generation & compilation)

### ISSUE THREAD

**Issue by tristanidoux** [Nuitka/Nuitka#1417]
Hello, would it be possible to have more intel regarding the way the import path (for an imported module) is handled & where is it stored between the code generation & the code compilation ?

I know this isn't supported at the moment (#43) but using the steps below, I made it work & the question is not really about cross-compilation but mainly about getting more intel regarding the paths handling  for import.

To summarize, I'm currently cross-compiling for ARM in a **Buildroot** with those 2 steps:
- **Code generation**: Using Qemu (with `--generate-c-only` option)
  ```bash
	--generate-c-only \
	--show-progress \
	--show-scons \
	--show-modules
  ```
- **Compilation**: Using my host toolchains, with Scons etc. from my dev PC (I don't compile directly on my board with Qemu as I don't have compilers available in my board packages).

**Environment**
- Nuitka 0.6.12.3
- Python 3.9
- Static build of Qemu (though I would like to change that as mentionned above)
- Not using `--standalone` or `--onefile` & **NOT** following imports (I juste transpile my own code & compile it)

**What works ?**
- When using Chroot & a static build of Qemu, I only generate the code as if I was executing those steps on the board. I then compile the code generated with my cross-compilation toolchain. Those two steps works flawlessly & whenever I deploy the binary on my board, it works without issues

However, I would like to remove the root permissions dependency & the static build of Qemu. 
When I did, it generated the code & compiled without any issues. However, when I deploy on my board now, I now get:
```sh
Traceback (most recent call last):
  File "/home/XXX/arm-board/home/default/app/__main__.py", line 8, in <module>
ModuleNotFoundError: No module named 'pyroute2'
```
I figured it's because of this **prefix**: `/home/XXX/arm-board/`, which is a path only present on my dev PC (where I generate the code & cross compile & not on my board). 

So the goal would still be to do those 2 steps but maybe with an extra step to handle the Python packages import paths.
I could also do a patch & submit it to handle path prefix.
Hence my question. 

At the moment, I can't seem to find much related to path my output directory when I stop at the code generation, maybe:
- the `executable` or `prefix` in the `__constants.c` file ?

I may be totally mistaken in the way I want to handle things though.
Thanks for your time & the awesome project !

**Comment by kayhayen** [comment]
I am sorry, I do not want to spend time on this kind of thing, I hope you understand. If you want to contact me via Nuitka commercial and get me funding to work on this on a per day basis, be my guest, but otherwise there is too many other more important things undo, including steps of my own long term plan for solving this.
