### ISSUE TITLE
Nuitka has no performance optimizations for my python project.

### ISSUE THREAD

**Issue by sanluku** [Nuitka/Nuitka#1418]
python version: 3.7
nuitka version: 0.6.16

python -m nuitka --standalone --warn-implicit-exceptions --show-progress --show-memory --enable-plugin=pyside2 --plugin-enable=multiprocessing --nofollow-imports --follow-import-to=SourceCode --nofollow-import-to=pyqt5,cv2,opencv_python,numpy,yaml,sqlalchemy,pil,psutils,imutils,importlib_metadata,imgviz --output-dir=disttmp ./MainApp.py

cp -r numpy numpy.libs cv2 opencv_python.libs sqlalchemy importlib_metadata zipp.py typing_extensions.py psutil imgviz PIL Pillow.libs yaml matplotlib packaging pyparsing.py cycler.py dateutil kiwisolver.cpython-37m-x86_64-linux-gnu.so termcolor.py PyQt5 imutils six.py mpl_toolkits serial  ./MainApp.dist/

I use the above two instructions to pack, and it's run normal。
I also use pyinstaller for packaging。
I don't see any performance optimizations between the two。
Did i do anything wrong?

**Comment by kayhayen** [comment]
Thanks for the feedback. Next time consider using the issue template and latest Nuitka version.
