### ISSUE TITLE
Error message on Gitlab CI

### ISSUE THREAD

**Issue by cls** [Nuitka/Nuitka#1423]
I'm looking at having Nuitka run as part of a CI pipeline. On our Windows runner we had an error:

> Nuitka-Scons:INFO: Backend C compiler: cl (cl 14.1).
> FATAL: Error, the Windows SDK must be installed in Visual Studio.

The Windows SDK is however installed. At first I wondered if it might be using the wrong compiler, but after exploring that to no avail I dug through the Nuitka source code and discovered that it checks for an environment variable `WindowsSDKVersion`, which was simply not set in our CI environment.

I feel it would be clearer if the error message mentioned that it was checking for `WindowsSDKVersion`, since it isn't mentioned anywhere, and it shouldn't be necessary to dig through source code to discover a missing environment variable. Perhaps something like:

> FATAL: Error, the Windows SDK must be installed in Visual Studio. (Missing environment variable WindowsSDKVersion.)

I'd be happy to submit a pull request, but I didn't want to presume the preferred error phrasing for your project.

Nuitka version:

> 0.6.19.7
> Commercial: None
> Python: 3.7
> Flavor: Unknown
> Executable: C:\\gitlab-ci\\...\\venv\\Scripts\\python.exe
> OS: Windows
> Arch: x86_64
> WindowsRelease: 10

**Comment by kayhayen** [comment]
No environment variables are necessary to use MSVC, it normally finds it via registry. You can also use a prompt, if you are competent to pick the right one, that works. On CI systems, that may not be enough.

The MSVC version number is suspiciously low. It's probably an unsupported form of MSVC called Build Tools, or something like that, what you have there. If you can make it work, all the power to you, but it's not supported should it be that. It's not even supported in the sense that it is detected and rejected, which could be added indeed.

On Github actions, there is `- uses: ilammy/msvc-dev-cmd@v1` which does setup the MSVC environment. Maybe there is something similar for Gitlab. If you find something, let me know. Maybe it doesn't have MSVC installed, does it?

**Comment by kayhayen** [comment]
I tried an installed Build Tools 2022 on my machine, in an attempt to identify it, but from description and generally, it seems to not  make a difference, finds the Windows SDK, and generally just seems to be the same. Just works, even for both arches. So, not sure what happens when Visual Studio 2022 is not installed, and I am not going to try, but I imagine it may or may not find the Windows SDK automatically in that case.

**Comment by cls** [comment]
The MSVC path found by CMake (which is called by GitLab CI, and in turn calls Nuitka) is:

    C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe

This seems to imply that the proper MSVC version is 14.16.27023 — that's why I wondered if it was using the wrong compiler. I came to the assumption that Nuitka cited 14.1 because that was the first version number for Visual Studio 2017, but if it isn't expected then I can try to look into the discrepancy.

For reference, the issue was completely resolved by the following patch to my CMake setup:

     add_custom_command(
         ...
         COMMAND
    +        ${CMAKE_COMMAND} -E env "WindowsSDKVersion=${CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION}"
             ${VENV_PYTHON_EXECUTABLE} -m nuitka
             ...
     )

On the CI runner in question this sets the environment variable to `10.0.17763.0`.

**Comment by kayhayen** [comment]
The version number is I think the one, that `cl.exe` itself outputs, 14.1 is 2017, 14.2 is 2019, 14.3 is 2022. 

The compiler you are using there is definitely not recommended, but Nuitka tends to work with MSVC from 2008 too, but that can break occasionally.

I tend to think it's a problem of you using Cmake and that setting up an MSVC environment that is incomplete for other build tools, like Scons with it using the official MSVC variable.  But Nuitka and Scons takes configuration provided from the outside serious, and therefore fails under Cmake. 

I don't see the point of using Cmake with Nuitka in the first place, so I don't really care and I can't really believe there is no real MSVC on the Gitlab runners, but my Google fu was not sufficient to find a list of what's on the Windows instances.
