### ISSUE TITLE
Error, cannot only include 'IncludedData*' objects in plugins.

### ISSUE THREAD

**Issue by mcfreis** [Nuitka/Nuitka#1425]
I running "Nuitka:INFO: Starting Python compilation with Nuitka '0.6.19.7' on Python '3.7' commercial None."

and have the following problem with a user pluging which only collects dlls (getExtraDlls) and xsd/xml files (considerDataFiles) from the module directory.

```
Nuitka-Plugins:INFO: data-files: Included data file 'certifi\cacert.pem' due to package data for 'certifi'.
Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3\Grammar3.7.7.final.0.pickle' due to package data for 'lib2to3.pgen2'.
Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3\PatternGrammar3.7.7.final.0.pickle' due to package data for 'lib2to3.pgen2'.
Nuitka-Plugins:INFO: data-files: Included data dir 'pytz\\zoneinfo' with 600 files due to: package data directory for 'pytz'.
Nuitka-Plugins:INFO: libseti: Include data file: SetiAnswerProtocol.xsd
FATAL: libseti: Error, cannot only include 'IncludedData*' objects in plugins.
make: *** [Makefile.mingw:84: compile_py] Error 1
```

What do I have to change in my plugin?

Thank you

**Comment by kayhayen** [comment]
Background is that Nuitka wants to control the file copy and know what should be done, so other plugins can work better with you, e.g. the ones in https://nuitka.net/doc/commercial/protect-data-files.html

**Comment by mcfreis** [comment]
Thank you for the quick response, that solved my issue.
