### ISSUE TITLE
Vosk shared object isn't being included

### ISSUE THREAD

**Issue by angelogladding** [Nuitka/Nuitka#1431]
0.6.19.7
Commercial: None
Python: 3.9.1 (default, Jul  5 2021, 18:51:21) 
Flavor: Unknown
Executable: ~/.cache/pypoetry/virtualenvs/understory-R12ax4gL-py3.9/bin/python
OS: Linux
Arch: x86_64
Distribution: Debian 11

I'm using poetry with `vosk=0.3.32`. I'm having success with Nuitka otherwise so my setup should be sane.

```python
# nuitka-project: --onefile
# nuitka-project: --include-package=vosk
# nuitka-project: --include-package-data=vosk

from vosk import Model, KaldiRecognizer

model = Model("model")
rec = KaldiRecognizer(model, 8000)

rec.FinalResult()
```

```pytb
Traceback (most recent call last):
  File ".../test_vosk.dist/test_vosk.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File ".../test_vosk.dist/vosk/__init__.py", line 21, in <module vosk>
  File ".../test_vosk.dist/vosk/__init__.py", line 15, in open_dll
OSError: cannot load library '.../test_vosk.dist/vosk/libvosk.so': .../test_vosk.dist/vosk/libvosk.so: cannot open shared object file: No such file or directory
```

There's a `vosk/libvosk.so` in my virtual environment's site-packages dir. There is *no* `vosk` dir in my `test_vosk.dist/`

Here's how the Vosk project is setting up FFI: https://github.com/alphacep/vosk-api/tree/master/python

**Comment by kayhayen** [comment]
Your reproducer is unfortunately missing an example model folder, I am assuming. The DLL error is visible before though, so no harm there. But next time please make sure it's more minimal or more complete (runs with Python as given).

**Comment by kayhayen** [comment]
The DLL loading code is relatively benign:

```
def open_dll():
    dlldir = os.path.abspath(os.path.dirname(__file__))
    if sys.platform == 'win32':
        # We want to load dependencies too
        os.environ["PATH"] = dlldir + os.pathsep + os.environ['PATH']
        if hasattr(os, 'add_dll_directory'):
            os.add_dll_directory(dlldir)
        return _ffi.dlopen(os.path.join(dlldir, "libvosk.dll"))
    elif sys.platform == 'linux':
        return _ffi.dlopen(os.path.join(dlldir, "libvosk.so"))
    elif sys.platform == 'darwin':
        return _ffi.dlopen(os.path.join(dlldir, "libvosk.dyld"))
    else:
        raise TypeError("Unsupported platform")
```

I am assuming it's only one configuration entry in the (new) `dll-files.yml` away.

**Comment by kayhayen** [comment]
This case is another strange one, because here a static DLL name prefix is expected, on Windows, normally a `lib` prefix would not be there, not sure if that is `ffi` default, but so far first time I see this. Will have to add a bit of a new feature there in the config handler to make this easy.

**Comment by kayhayen** [comment]
This is part of the 0.7 release now.
