### ISSUE TITLE
PySimpleGui init.tcl problems in onefile mode

### ISSUE THREAD

**Issue by GiovanniK** [Nuitka/Nuitka#1433]
Hi, I'm having a lot of trouble letting my simple app work in onefile mode.

My app works with PySimpleGui and I've been using Pyinstaller's onefile mode to distribute it. This solution however is very slow, which is why I'm trying to switch to Nuitka.

The problem is that in the --onefile mode of Nuitka, I get TCL/TK problems, like this:
`_tkinter.TclError: Can't find a usable init.tcl in the following directories:
    C:/Users/MYUSER/AppData/Local/Temp/lib/tcl8.6 C:/Users/MYUSER/AppData/Local/Temp/lib/tcl8.6 C:/Users/MYUSER/AppData/Local/lib/tcl8.6 C:/Users/MYUSER/AppData/Local/Temp/library C:/Users/MYUSER/AppData/Local/library C:/Users/MYUSER/AppData/Local/tcl8.6.9/library C:/Users/MYUSER/AppData/tcl8.6.9/library`

I think the problem is that it looks one folder too high... it looks directly in the Temp folder for the lib folder, instead of the app folder.

The build command is `py -m nuitka --onefile --output-dir=software --include-data-dir=./tcl8.6=tcl8.6 --include-data-dir=./tk8.6=tk8.6 --include-package-data selenium app.py`

Another problem is the tk-inter plugin, when I try to enable it, it gives me this error:
`TypeError: __init__() missing 2 required positional arguments: 'tcl_library_dir' and 'tk_library_dir'`
The build command is `py -m nuitka --onefile --enable-plugin tk-inter --output-dir=software --include-data-dir=./tcl8.6=tcl8.6 --include-data-dir=./tk8.6=tk8.6 --include-package-data selenium app.py`

When I use the standalone mode, I can make it work with this:
` py -m nuitka --standalone --output-dir=software --include-data-dir=./tcl8.6=tcl8.6 --include-data-dir=./tk8.6=tk8.6 --include-package-data selenium app.py`

I do have to manually copy the tcl8.6 and tk8.6 folders to the path above..
So it looks like this basically:
software/Lib/tcl8.6
software/Lib/tk8.6
software/app.dist/app.exe

This is not my preferred way.
The software will be used on a shared terminal server where I do not have any admin access for, I want to distribute it quickly using only one .exe file.

What I also found was create-exe.py from here:
https://github.com/Nuitka/Nuitka/issues/137#issuecomment-438098457

This however still does not solve the problem. That does not work for --onefile mode either.

Does anyone have a solution for this?
Currently I simply cannot use Nuitka for my app due to this problem.

**Comment by kayhayen** [comment]
While you provided a lot of information, the one from the issue template would be very much needed. I am not aware of the tkinter plugin being broken, but it could well be. Copying the files yourself may work should you happen to get it right, but I don't care about that, esp. as you did not, and that is what the plugin is for.

**Comment by kayhayen** [comment]
Please retry opening a new issue with information as requested in the issue template. Many of your statements are not reproducible by me, and I don't even know what version of Nuitka you are using.
