### ISSUE TITLE
 PySimpleGui init.tcl problems in onefile mode

### ISSUE THREAD

**Issue by GiovanniK** [Nuitka/Nuitka#1434]
* Nuitka version, full Python version, flavor, OS, etc. as output by this
  command (it does more than you think, and we are adding more all the time):

   > 0.6.19.7
Commercial: None
Python: 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Dev\Python\FunctionalOwner\venv\scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 1

* How did you install Nuitka and Python
   > Installed in a venv, using pip.

* The specific PyPI names and versions
   > PySimpleGUI==4.57.0
Nuitka==0.6.19.7

* Many times when you get an error from Nuitka, your setup may be special
   > The application definitely works, converting it to PySide6 using the plugin works well also.
   Issue is definitely with Tkinter/PySimpleGUI and Nuitka. Works correctly with Pyinstaller.

* Nuitka build commands that are NOT working
   > py -m nuitka --onefile --output-dir=software --include-data-dir=./tcl8.6=tcl8.6 --include-data-dir=./tk8.6=tk8.6 --include-package-data selenium app.py
 py -m nuitka --onefile --enable-plugin tk-inter --output-dir=software --include-data-dir=./tcl8.6=tcl8.6 --include-data-dir=./tk8.6=tk8.6 --include-package-data selenium app.py

* Nuitka build commands that ARE WORKING
   > py -m nuitka --standalone --output-dir=software --include-data-dir=./tcl8.6=tcl8.6 --include-data-dir=./tk8.6=tk8.6 --include-package-data selenium app.py

   > I do have to manually copy the tcl8.6 and tk8.6 folders to the path above..
So it looks like this basically, this is the only way to get it working for me:
software/Lib/tcl8.6
software/Lib/tk8.6
software/app.dist/app.exe

### The issue itself

My app works with PySimpleGui and I've been using Pyinstaller's onefile mode to distribute it. This solution however is very slow, which is why I'm trying to switch to Nuitka.
The problem is that in the --onefile mode of Nuitka, I get TCL/TK problems, like this:
   > _tkinter.TclError: Can't find a usable init.tcl in the following directories: C:/Users/MYUSER/AppData/Local/Temp/lib/tcl8.6 C:/Users/MYUSER/AppData/Local/Temp/lib/tcl8.6 C:/Users/MYUSER/AppData/Local/lib/tcl8.6 C:/Users/MYUSER/AppData/Local/Temp/library C:/Users/MYUSER/AppData/Local/library C:/Users/MYUSER/AppData/Local/tcl8.6.9/library C:/Users/MYUSER/AppData/tcl8.6.9/library

I think the problem is that it looks one folder too high... it looks directly in the Temp folder for the lib folder, instead of the app folder.
When I use the standalone mode, I can make it work. But still I have to manually move the TCL/TK folders on level up of the app.exe.

When using the tk-inter plugin, it gives me the following error:
   > TypeError: __init__() missing 2 required positional arguments: 'tcl_library_dir' and 'tk_library_dir'

I've tried this using a different venv and without a venv, the plugins seems to break with whatever I do.
The pyside6 plugin does work fine.

What I also found was create-exe.py from here:
https://github.com/Nuitka/Nuitka/issues/137#issuecomment-438098457

This however still does not solve the problem. That does not work for --onefile mode either.

### See the other issue too for more information
This duplicate of #1433

**Comment by GiovanniK** [comment]
@kayhayen I can provide source code in private too if required, since you could not reproduce it - there's nothing special in there.

**Comment by kayhayen** [comment]
The command line parser for plugins is not working with `--enable-plugin tk-inter` which also disallowed with the 0.7 release I just made, and on `develop` for a long time. It is now required to specify arguments with the `=` sign. The argument parser of Python allows both things there, but it can lead to mistakes of all kinds easily. And the code that tries to detect activated plugins on the command line never handled this.

I am assuming it's working when you use that even for the now old release.

**Comment by GiovanniK** [comment]
I feel kind of stupid that the solution was so simple, this works instantly.
I wasn't alterted because not all arguments required it, so haven't thought about doing it that way.

Thanks a lot! The app starts much, much faster with Nuitka.

**Comment by kayhayen** [comment]
Good to hear, feel free to spam social networks with it.
