### ISSUE TITLE
Tensorflow 2 import crashes during standalone execution

### ISSUE THREAD

**Issue by emre84** [Nuitka/Nuitka#1435]
-  Nuitka version, full Python version, flavor, OS, etc. as output by this
command (it does more than you think, and we are adding more all the time):
MACOS Monterey
Python:3.7.3
Nuitka '0.6.19.4'

- How did you install Nuitka and Python
pip

- The specific PyPI names and versions
tensorflow==2.8

- Provide in your issue the Nuitka options used
sudo python3.7 -m nuitka --standalone --enable-plugin=tensorflow tensorflow.py

- Note if this is a regression
Not tried

- Description:
Tensorflow 2 import crashes during standalone app execution. 

- Content of  tensorflow.py:
import tensorflow as tf
print(tf.__version__)

- Error Message:
2022-02-20 20:52:30.882225: E tensorflow/core/common_runtime/session_factory.cc:48] Two session factories are being registered underGRPC_SESSION
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/descriptor_database.cc:118] File already exists in database: tensorflow/python/framework/cpp_shape_inference.proto
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/descriptor.cc:1379] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
libc++abi: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):

**Comment by kayhayen** [comment]
This one looks ugly, probably it's about data files, the error seems to complain about duplicates, however. The plugin does what it wants to do, which however, these days, probably would be better to do with the anti-bloat engine. Not sure if it needs the numpy plugin, it surely warns about it.

**Comment by kayhayen** [comment]
The anti-bloat really hates this one deeply, with `pytest`and `IPython` being included, I guess, first line of action is to get those warnings resolved:

> Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'pytest' encountered.
> Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython' encountered. 

They are going to make this too slow to compile actually.

**Comment by f1nzo** [comment]
was this error:
```
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.display_functions' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython' encountered.
```
ever resolved? I'm having big problems with it and don't know what is causing this error

**Comment by emre84** [comment]
Hi @f1nzo, Unfortunately I could not get any response yet.

**Comment by kayhayen** [comment]
It's not an error, it's a warning, including `IPython` is really not a good idea as it in turn includes just about every syntax highlighting framework, and everything you can image, making it slow.

When I tackled this issue though, I made the respective Pandas modules stop doing it through anti-bloat, just so the compilation drops by a few thousand modules.

I got Tensorflow to work on at least Windows now, not sure how it affects this error. Can you retry? I will try it out on macOS later.

**Comment by emre84** [comment]
Hi Kay,

Thanks a lot for your investigations. Just let me know when you try macOS out so I can test it on Mac. Unfortunately I do not have windows PC.

Good luck.

**Comment by emre84** [comment]
Hi Kay, I re-tested it on Mac. If you require, I am getting following error:

Command:
sudo python3.7 -m nuitka --standalone  --enable-plugin=anti-bloat --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow --enable-plugin=tensorflow --python-flag=no_site  --include-data-file=/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/inference_graph/detect.tflite=inference_graph/ --include-data-file=/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/training/labelmap.pbtxt=training/  test2.py

Response:
FATAL: Error, failed to resolve DLL path @rpath/libshiboken2.abi3.5.15.dylib (for /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PySide2/QtCore.abi3.so), please report the bug.

then I copied my libshiboken2.abi3.5.1 file into /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PySide2 and re-executed

then I got following error:
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'QtCore'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore used by:  
Nuitka-Inclusion:WARNING: test2.dist/PyQt5/QtCore.so    test2.dist/PyQt5/QtGui.so    test2.dist/PyQt5/QtSvg.so    test2.dist/PyQt5/QtWidgets.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PySide2/Qt/lib/QtCore.framework/Versions/5/QtCore used by    test2.dist/PySide2/QtCore.so
Nuitka-Inclusion:WARNING: test2.dist/PySide2/QtGui.so    test2.dist/PySide2/QtPrintSupport.so    test2.dist/PySide2/QtSvg.so    test2.dist/PySide2/QtWidgets.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'QtGui'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyQt5/Qt/lib/QtGui.framework/Versions/5/QtGui used by:
Nuitka-Inclusion:WARNING: test2.dist/PyQt5/QtGui.so    test2.dist/PyQt5/QtSvg.so    test2.dist/PyQt5/QtWidgets.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PySide2/Qt/lib/QtGui.framework/Versions/5/QtGui used by    test2.dist/PySide2/QtGui.so
Nuitka-Inclusion:WARNING: test2.dist/PySide2/QtPrintSupport.so    test2.dist/PySide2/QtSvg.so    test2.dist/PySide2/QtWidgets.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'QtSvg'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyQt5/Qt/lib/QtSvg.framework/Versions/5/QtSvg used by:
Nuitka-Inclusion:WARNING: test2.dist/PyQt5/QtSvg.so different from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PySide2/Qt/lib/QtSvg.framework/Versions/5/QtSvg used by
Nuitka-Inclusion:WARNING: test2.dist/PySide2/QtSvg.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'QtWidgets'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyQt5/Qt/lib/QtWidgets.framework/Versions/5/QtWidgets
Nuitka-Inclusion:WARNING: used by:    test2.dist/PyQt5/QtSvg.so    test2.dist/PyQt5/QtWidgets.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PySide2/Qt/lib/QtWidgets.framework/Versions/5/QtWidgets used by
Nuitka-Inclusion:WARNING: test2.dist/PySide2/QtPrintSupport.so    test2.dist/PySide2/QtSvg.so    test2.dist/PySide2/QtWidgets.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libgfortran.3.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libgfortran.3.dylib
Nuitka-Inclusion:WARNING: used by:    test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/integrate/../.dylibs/libgfortran.3.dylib used by    test2.dist/scipy/integrate/_dop.so
Nuitka-Inclusion:WARNING: test2.dist/scipy/integrate/_odepack.so    test2.dist/scipy/integrate/_quadpack.so    test2.dist/scipy/integrate/lsoda.so    test2.dist/scipy/integrate/vode.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libgfortran.3.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libgfortran.3.dylib
Nuitka-Inclusion:WARNING: used by:    test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/interpolate/../.dylibs/libgfortran.3.dylib used by    test2.dist/scipy/interpolate/_bspl.so
Nuitka-Inclusion:WARNING: test2.dist/scipy/interpolate/_fitpack.so    test2.dist/scipy/interpolate/dfitpack.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libgfortran.3.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libgfortran.3.dylib
Nuitka-Inclusion:WARNING: used by:    test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/linalg/../.dylibs/libgfortran.3.dylib used by    test2.dist/scipy/linalg/_fblas.so
Nuitka-Inclusion:WARNING: test2.dist/scipy/linalg/_flapack.so    test2.dist/scipy/linalg/_flinalg.so    test2.dist/scipy/linalg/cython_blas.so    test2.dist/scipy/linalg/cython_lapack.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libgfortran.3.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libgfortran.3.dylib
Nuitka-Inclusion:WARNING: used by:    test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/optimize/../.dylibs/libgfortran.3.dylib used by    test2.dist/scipy/optimize/_cobyla.so
Nuitka-Inclusion:WARNING: test2.dist/scipy/optimize/_lbfgsb.so    test2.dist/scipy/optimize/_minpack.so    test2.dist/scipy/optimize/_nnls.so    test2.dist/scipy/optimize/_slsqp.so
Nuitka-Inclusion:WARNING: test2.dist/scipy/optimize/minpack2.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libgfortran.3.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libgfortran.3.dylib
Nuitka-Inclusion:WARNING: used by:    test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/optimize/_trlib/../../.dylibs/libgfortran.3.dylib used by
Nuitka-Inclusion:WARNING: test2.dist/scipy/optimize/_trlib/_trlib.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libgfortran.3.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libgfortran.3.dylib
Nuitka-Inclusion:WARNING: used by:    test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/sparse/linalg/dsolve/../../../.dylibs/libgfortran.3.dylib used by
Nuitka-Inclusion:WARNING: test2.dist/scipy/sparse/linalg/dsolve/_superlu.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libgfortran.3.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libgfortran.3.dylib
Nuitka-Inclusion:WARNING: used by:    test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/sparse/linalg/eigen/arpack/../../../../.dylibs/libgfortran.3.dylib used by
Nuitka-Inclusion:WARNING: test2.dist/scipy/sparse/linalg/eigen/arpack/_arpack.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libgfortran.3.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libgfortran.3.dylib
Nuitka-Inclusion:WARNING: used by:    test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/sparse/linalg/isolve/../../../.dylibs/libgfortran.3.dylib used by
Nuitka-Inclusion:WARNING: test2.dist/scipy/sparse/linalg/isolve/_iterative.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libgfortran.3.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libgfortran.3.dylib
Nuitka-Inclusion:WARNING: used by:    test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/spatial/../.dylibs/libgfortran.3.dylib used by    test2.dist/scipy/spatial/qhull.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libgfortran.3.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libgfortran.3.dylib
Nuitka-Inclusion:WARNING: used by:    test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/special/../.dylibs/libgfortran.3.dylib used by    test2.dist/scipy/special/_ellip_harm_2.so
Nuitka-Inclusion:WARNING: test2.dist/scipy/special/_ufuncs.so    test2.dist/scipy/special/cython_special.so    test2.dist/scipy/special/specfun.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libgfortran.3.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libgfortran.3.dylib
Nuitka-Inclusion:WARNING: used by:    test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/stats/../.dylibs/libgfortran.3.dylib used by    test2.dist/scipy/stats/mvn.so
Nuitka-Inclusion:WARNING: test2.dist/scipy/stats/statlib.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libquadmath.0.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libquadmath.0.dylib
Nuitka-Inclusion:WARNING: used by:    test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/integrate/../.dylibs/libquadmath.0.dylib used by    test2.dist/scipy/integrate/_dop.so
Nuitka-Inclusion:WARNING: test2.dist/scipy/integrate/_odepack.so    test2.dist/scipy/integrate/_quadpack.so    test2.dist/scipy/integrate/lsoda.so    test2.dist/scipy/integrate/vode.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libquadmath.0.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libquadmath.0.dylib
Nuitka-Inclusion:WARNING: used by:    test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/interpolate/../.dylibs/libquadmath.0.dylib used by    test2.dist/scipy/interpolate/_bspl.so
Nuitka-Inclusion:WARNING: test2.dist/scipy/interpolate/_fitpack.so    test2.dist/scipy/interpolate/dfitpack.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libquadmath.0.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libquadmath.0.dylib
Nuitka-Inclusion:WARNING: used by:    test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/linalg/../.dylibs/libquadmath.0.dylib used by    test2.dist/scipy/linalg/_fblas.so
Nuitka-Inclusion:WARNING: test2.dist/scipy/linalg/_flapack.so    test2.dist/scipy/linalg/_flinalg.so    test2.dist/scipy/linalg/cython_blas.so    test2.dist/scipy/linalg/cython_lapack.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libquadmath.0.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libquadmath.0.dylib
Nuitka-Inclusion:WARNING: used by:    test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/optimize/../.dylibs/libquadmath.0.dylib used by    test2.dist/scipy/optimize/_cobyla.so
Nuitka-Inclusion:WARNING: test2.dist/scipy/optimize/_lbfgsb.so    test2.dist/scipy/optimize/_minpack.so    test2.dist/scipy/optimize/_nnls.so    test2.dist/scipy/optimize/_slsqp.so
Nuitka-Inclusion:WARNING: test2.dist/scipy/optimize/minpack2.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libquadmath.0.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libquadmath.0.dylib
Nuitka-Inclusion:WARNING: used by:    test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/optimize/_trlib/../../.dylibs/libquadmath.0.dylib used by
Nuitka-Inclusion:WARNING: test2.dist/scipy/optimize/_trlib/_trlib.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libquadmath.0.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libquadmath.0.dylib
Nuitka-Inclusion:WARNING: used by:    test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/sparse/linalg/dsolve/../../../.dylibs/libquadmath.0.dylib used by
Nuitka-Inclusion:WARNING: test2.dist/scipy/sparse/linalg/dsolve/_superlu.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libquadmath.0.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libquadmath.0.dylib
Nuitka-Inclusion:WARNING: used by:    test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/sparse/linalg/eigen/arpack/../../../../.dylibs/libquadmath.0.dylib used by
Nuitka-Inclusion:WARNING: test2.dist/scipy/sparse/linalg/eigen/arpack/_arpack.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libquadmath.0.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libquadmath.0.dylib
Nuitka-Inclusion:WARNING: used by:    test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/sparse/linalg/isolve/../../../.dylibs/libquadmath.0.dylib used by
Nuitka-Inclusion:WARNING: test2.dist/scipy/sparse/linalg/isolve/_iterative.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libquadmath.0.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libquadmath.0.dylib
Nuitka-Inclusion:WARNING: used by:    test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/spatial/../.dylibs/libquadmath.0.dylib used by    test2.dist/scipy/spatial/qhull.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libquadmath.0.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libquadmath.0.dylib
Nuitka-Inclusion:WARNING: used by:    test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/special/../.dylibs/libquadmath.0.dylib used by    test2.dist/scipy/special/_ellip_harm_2.so
Nuitka-Inclusion:WARNING: test2.dist/scipy/special/_ufuncs.so    test2.dist/scipy/special/cython_special.so    test2.dist/scipy/special/specfun.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libquadmath.0.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libquadmath.0.dylib
Nuitka-Inclusion:WARNING: used by:    test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/stats/../.dylibs/libquadmath.0.dylib used by    test2.dist/scipy/stats/mvn.so
Nuitka-Inclusion:WARNING: test2.dist/scipy/stats/statlib.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libgcc_s.1.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libgcc_s.1.dylib used by:
Nuitka-Inclusion:WARNING: test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/integrate/../.dylibs/libgcc_s.1.dylib used by    test2.dist/scipy/integrate/_dop.so
Nuitka-Inclusion:WARNING: test2.dist/scipy/integrate/_odepack.so    test2.dist/scipy/integrate/_quadpack.so    test2.dist/scipy/integrate/lsoda.so    test2.dist/scipy/integrate/vode.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libgcc_s.1.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libgcc_s.1.dylib used by:
Nuitka-Inclusion:WARNING: test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/interpolate/../.dylibs/libgcc_s.1.dylib used by    test2.dist/scipy/interpolate/_bspl.so
Nuitka-Inclusion:WARNING: test2.dist/scipy/interpolate/_fitpack.so    test2.dist/scipy/interpolate/dfitpack.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libgcc_s.1.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libgcc_s.1.dylib used by:
Nuitka-Inclusion:WARNING: test2.dist/numpy/core/_multiarray_umath.so different from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/linalg/../.dylibs/libgcc_s.1.dylib
Nuitka-Inclusion:WARNING: used by    test2.dist/scipy/linalg/_fblas.so    test2.dist/scipy/linalg/_flapack.so    test2.dist/scipy/linalg/_flinalg.so    test2.dist/scipy/linalg/cython_blas.so
Nuitka-Inclusion:WARNING: test2.dist/scipy/linalg/cython_lapack.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libgcc_s.1.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libgcc_s.1.dylib used by:
Nuitka-Inclusion:WARNING: test2.dist/numpy/core/_multiarray_umath.so different from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/optimize/../.dylibs/libgcc_s.1.dylib
Nuitka-Inclusion:WARNING: used by    test2.dist/scipy/optimize/_cobyla.so    test2.dist/scipy/optimize/_lbfgsb.so    test2.dist/scipy/optimize/_minpack.so    test2.dist/scipy/optimize/_nnls.so
Nuitka-Inclusion:WARNING: test2.dist/scipy/optimize/_slsqp.so    test2.dist/scipy/optimize/minpack2.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libgcc_s.1.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libgcc_s.1.dylib used by:
Nuitka-Inclusion:WARNING: test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/optimize/_trlib/../../.dylibs/libgcc_s.1.dylib used by
Nuitka-Inclusion:WARNING: test2.dist/scipy/optimize/_trlib/_trlib.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libgcc_s.1.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libgcc_s.1.dylib used by:
Nuitka-Inclusion:WARNING: test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/sparse/linalg/dsolve/../../../.dylibs/libgcc_s.1.dylib used by
Nuitka-Inclusion:WARNING: test2.dist/scipy/sparse/linalg/dsolve/_superlu.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libgcc_s.1.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libgcc_s.1.dylib used by:
Nuitka-Inclusion:WARNING: test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/sparse/linalg/eigen/arpack/../../../../.dylibs/libgcc_s.1.dylib used by
Nuitka-Inclusion:WARNING: test2.dist/scipy/sparse/linalg/eigen/arpack/_arpack.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libgcc_s.1.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libgcc_s.1.dylib used by:
Nuitka-Inclusion:WARNING: test2.dist/numpy/core/_multiarray_umath.so different from
Nuitka-Inclusion:WARNING: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/sparse/linalg/isolve/../../../.dylibs/libgcc_s.1.dylib used by
Nuitka-Inclusion:WARNING: test2.dist/scipy/sparse/linalg/isolve/_iterative.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libgcc_s.1.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libgcc_s.1.dylib used by:
Nuitka-Inclusion:WARNING: test2.dist/numpy/core/_multiarray_umath.so different from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/spatial/../.dylibs/libgcc_s.1.dylib
Nuitka-Inclusion:WARNING: used by    test2.dist/scipy/spatial/qhull.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libgcc_s.1.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libgcc_s.1.dylib used by:
Nuitka-Inclusion:WARNING: test2.dist/numpy/core/_multiarray_umath.so different from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/special/../.dylibs/libgcc_s.1.dylib
Nuitka-Inclusion:WARNING: used by    test2.dist/scipy/special/_ellip_harm_2.so    test2.dist/scipy/special/_ufuncs.so    test2.dist/scipy/special/cython_special.so    test2.dist/scipy/special/specfun.so
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libgcc_s.1.dylib'. /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/../.dylibs/libgcc_s.1.dylib used by:
Nuitka-Inclusion:WARNING: test2.dist/numpy/core/_multiarray_umath.so different from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/stats/../.dylibs/libgcc_s.1.dylib
Nuitka-Inclusion:WARNING: used by    test2.dist/scipy/stats/mvn.so    test2.dist/scipy/stats/statlib.so
FATAL: Error, problem with dependency scan of 'test2.dist/PySide2/QtCore.so' with '@rpath/QtCore.framework/Versions/5/QtCore' please report the bug.  

Thanks a lot in advance.

**Comment by kayhayen** [comment]
@emre84 posting below other issues is a sure fire way to get ignored, raise new issues for new issues.

**Comment by kayhayen** [comment]
This is now on develop and will be in 0.8 release.

**Comment by emre84** [comment]
Hi Kay,

Thank you very much for the response. But unfortunately I am getting following error. Do you have idea what I have to do? I would be appreciated for a response.

**Environment:**
MACOS Monterey
Python:3.7.3
Nuitka 'Nuitka-0.8rc7' (downloaded 2 days ago)

**How did you install Nuitka and Python**
pip

**The specific PyPI names and versions**
tensorflow==2.8

**Provide in your issue the Nuitka options used**
sudo python3.7 -m nuitka ---standalone  --enable-plugin=anti-bloat --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow --enable-plugin=tensorflow --python-flag=no_site test.py

**Content of test.py:**
import tensorflow as tf
print(tf.version)

**Error during nuitka standalone compilation:**
_**FATAL: Error, failed to resolve DLL path bazel-out/darwin-opt/bin/tensorflow/compiler/tf2tensorrt/lib_pywrap_py_utils_ccsharedlib.so (for /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/compiler/tf2tensorrt/_pywrap_py_utils.so), please report the bug.**_

Note: I have also tried with following command(--include-data-file tf2tensorrt/*.so included, which has lib_pywrap_py_utils_ccsharedlib.so file inside) , unfortunately I am still getting the same error:

**_sudo python3.7 -m nuitka ---standalone  --enable-plugin=anti-bloat --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow --enable-plugin=tensorflow --python-flag=no_site --include-data-file=/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/compiler/tf2tensorrt/*.so=tensorflow/compiler/tf2tensorrt/ test.py_**

**Comment by kayhayen** [comment]
Part of 0.8 release that I just made.
