### ISSUE TITLE
Qml build error on windows (shutil.SameFileError)

### ISSUE THREAD

**Issue by uralbash** [Nuitka/Nuitka#1438]
> python -m nuitka --version

(.env_win64) Z:\foo>python -m nuitka --version
0.7
Commercial: None
Python: 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: Z:\foo\.env_win64\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

Error appears only in versions more than 0.6.17.7
Each time when assembling pyside6 + qml project a SameFileError occurs:

```
Nuitka-Plugins:INFO: pyside6: Including Qt plugins 'generic,iconengines,imageformats,platforminputcontexts,platforms,qml,styles,tls,virtualkeyboard' below 'PySide6\qt-plugins'.
Traceback (most recent call last):
  File "Z:\foo\.env_win64\lib\site-packages\nuitka\__main__.py", line 137, in <module>
    main()
  File "Z:\foo\.env_win64\lib\site-packages\nuitka\__main__.py", line 123, in main
    MainControl.main()
  File "Z:\foo\.env_win64\lib\site-packages\nuitka\MainControl.py", line 961, in main
    addIncludedEntryPoints(Plugins.considerExtraDlls(dist_dir, module))
  File "Z:\foo\.env_win64\lib\site-packages\nuitka\plugins\Plugins.py", line 481, in considerExtraDlls
    copyFile(extra_dll.source_path, extra_dll.dest_path)
  File "Z:\foo\.env_win64\lib\site-packages\nuitka\utils\FileOperations.py", line 638, in copyFile
    shutil.copyfile(source_path, dest_path)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 244, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: 'Z:\\foo\\.env_win64\\lib\\site-packages\\PySide6\\plugins\\generic\\qtuiotouchplugin.dll' and 'build\\nuitka.build.project\\win64\\foo\\main.dist\\PySide6\\qt-plugins\\generic\\qtuiotouchplugin.dll' are the same file
```

**Comment by kayhayen** [comment]
That's not been seen otherwise so far. I wonder what kind of Python or PySide6 installation that is. How did you create the virtualenv what is the version of virtualenv, are you ussing any special options? There might be some that cause symlinks to be used these days.

**Comment by uralbash** [comment]
I use mounted disk to a virtual machine through Shard Folder on VBox.  And virtual environment is created on shared disk Z. When I try to build with version 0.6.17.7, it works normally and build is successfull. If I install a newer version, the compilation gives an error. When I create virtually environment on disk C build is ok again.

**Comment by kayhayen** [comment]
I was wondering how to virtualenv of Python was created actually. I don't think it plays a role where it's from. I don't consider VirtualBox shared mount to be at fault, unless there is some bad symlinking going on, and symlinks would be copied, but point to the same thing, something bizarre like that.

**Comment by kayhayen** [comment]
Closing for lack of feedback.
