### ISSUE TITLE
Windows: Failure to detect arch of MSVC for ARM64 

### ISSUE THREAD

**Issue by re1von** [Nuitka/Nuitka#1439]
Problem:
With any compilation using nuitka I get an error related to the Scons compiler.

> python -m nuitka --version

0.8rc1
Commercial: None
Python: 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: c:\python\python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

Content test.py:
```python
print('test')
```

Compilation command:
`C:\Python\Python310\python.exe -m nuitka --nofollow-imports test.py`

Output:
```shell
Nuitka-Options:INFO: Used command line options: --nofollow-imports test.py
Nuitka:INFO: Starting Python compilation with Nuitka '0.8rc1' on Python '3.10' commercial None.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
AssertionError: (b'\xa8\xe1\xaf\xae\xab\xec\xa7\xae\xa2\xa0\xad\xa8\xa5: cl [ \xaf\xa0\xe0\xa0\xac\xa5\xe2\xe0... ] \xa8\xac\xef_\xe4\xa0\xa9\xab\xa0... [ /link \xaf\xa0\xe0\xa0\xac\xa5\xe2\xe0_\xaa\xae\xac\xaf\xae\xad\xae\xa2\xaa\x
a8... ]\r\n', b'\x8e\xaf\xe2\xa8\xac\xa8\xa7\xa8\xe0\xe3\xee\xe9\xa8\xa9 \xaa\xae\xac\xaf\xa8\xab\xef\xe2\xae\xe0 Microsoft (R) C/C++ \xa2\xa5\xe0\xe1\xa8\xa8 19.29.30140 \xa4\xab\xef ARM64\r\n(C) \x8a\xae\xe0\xaf\xae\xe0\xa0\xe6\xa
8\xef \x8c\xa0\xa9\xaa\xe0\xae\xe1\xae\xe4\xe2 (Microsoft Corporation).  \x82\xe1\xa5 \xaf\xe0\xa0\xa2\xa0 \xa7\xa0\xe9\xa8\xe9\xa5\xad\xeb.\r\n\r\n'):
  File "C:\Python\PYTHON~1\lib\SITE-P~1\nuitka\build\BACKEN~1.SCO", line 369:
    env = checkWindowsCompilerFound(
  File "C:\Python\Python310\lib\site-packages\nuitka\build\SconsCompilerSettings.py", line 215:
    decision, linker_arch, compiler_arch = decideArchMismatch(
  File "C:\Python\Python310\lib\site-packages\nuitka\build\SconsUtils.py", line 591:
    compiler_arch = getCompilerArch(
  File "C:\Python\Python310\lib\site-packages\nuitka\build\SconsUtils.py", line 582:
    assert False, (stdout, stderr)
```
As far as I understand from the source code `SconsUtils.py`, the problem is due to the fact that the compiler for some reason cannot determine my architecture.
```python
# The MSVC will output on error, while clang outputs in stdout and they
# use different names for arches.
if b"x64" in stderr or b"x86_64" in stdout:
    _compiler_arch[compiler_path] = "pei-x86-64"
elif b"x86" in stderr or b"i686" in stdout:
    _compiler_arch[compiler_path] = "pei-i386"
else:
    assert False, (stdout, stderr)
```

I'm not sure, but I'm inclined to believe that the problem occurred after updating Microsoft Visual Studio. I made the decision to completely reinstall VS, but it did not bring the appropriate results.

I also found something similar in this [comment](https://github.com/Nuitka/Nuitka/issues/1414#issuecomment-1042811464), but my AssertionError output contains something different.

**Comment by kayhayen** [comment]
Yes, the output of `cl.exe` is the only way to know the architecture there. It seems you are using MSVC for cross compiling to ARM64 Windows there? Also I cannot recognize what the garbage is in your output. Do you happen to have a very unknown locale installed?

Are you using a command prompt of MSVC before you start Nuitka there? Your Windows says it is `x86_64`.

**Comment by kayhayen** [comment]
Also, I am updating to 17.1 for MSVC, let's see if that causes something for me too.

**Comment by kayhayen** [comment]
Nothing happened for me. I also installed ARM64 build tools, which is the only thing I found in there, but I don't know how to activate them at all. The autodetection of Scons works just fine for me: https://nuitka.net/doc/factory.html

I enhanced the code to identify the ARM64 target for MSVC there. This way it would not crash but tell you about not matching Python and MSVC. If you really want to target ARM64, you need to run Python under ARM64 as well. And there will things to enhance to support that architecture, I think a couple of places are only considering one or the other to be true, 32 or 64 Intel.

**Comment by re1von** [comment]
> It seems you are using MSVC for cross compiling to ARM64 Windows there? Also I cannot recognize what the garbage is in your output. Do you happen to have a very unknown locale installed?
> 
> Are you using a command prompt of MSVC before you start Nuitka there? Your Windows says it is `x86_64`.

Yes, I use MSVC for cross-compilation. I have all versions of MSVC installed, i.e. x64/x86 and ARM64. I also can't process my output in any way, and this was one of the reasons why I decided to write here.
I don't quite understand what is meant by the phrase:
> very unknown locale

To run nuitka, I use the PyCharm command line, I get the same result using CMD.
I would like to compile using nuitka using x64, not ARM64, but I do not know how to tell nuitka about this, because I have all versions of MSVC, and now, as far as I understand, she wants to use the version for ARM64.

**Comment by kayhayen** [comment]
The cross compilation is not supported at this time. I might relax it at some point, but it's not there.

And native ARM64 on Windows would need serious commercial backing for me to want to support it. I don't even I would even have the device, nor the Python interpreter, as CPython doesn't support that itself, and it seems it's only partially working for many packages. 

Compiling with Nuitka is not going to make x86_64 Python work on ARM64 if that is what you are looking for.

I am now confused if ARM64 is what you want to target, or what Nuitka targets from auto-detection of Scons against your will.

**Comment by kayhayen** [comment]
Can this come from your PyCharm setup, does it happen when you launch a new cmd.exe and just compile from there?

**Comment by re1von** [comment]
> Can this come from your PyCharm setup, does it happen when you launch a new cmd.exe and just compile from there?

This happened absolutely everywhere, wherever I started compiling: in CMD, PyCharm or the VS developer command line. (Outside of any PyCharm project)

Thank you very much for help.
The problem, we can say, disappeared by itself after the change of Visual Studio 16 2019 to 17 2022. I still haven't fully understood the source of the problem, but perhaps it was some kind of conflict of the bit depth of the MSVC versions in the most recent VS 16.


> Also, I am updating to 17.1 for MSVC, let's see if that causes something for me too.

And also, perhaps you misunderstood me a little, this phenomenon began to be observed after the VS 16 2019 update to a newer version VS 16. VS 17 has nothing to do with it.

**Comment by kayhayen** [comment]
This seems to be a Scons issue in some way, because Scons picks the latest one. If the latest one is an Intel one, fine.  Like I said, my ARM64 version in 2022 is not used. Maybe for 2019 it was some kind of bug in MSVC and Scons, that is outside my scope though. At least the compiler/Python mismatch is now properly reported, and this part is in 0.7.1 hotfix release, because it is not invasive and risk-free, but that will be it I guess. Using 2022 is what users that are not subscribers of https://nuitka.net/doc/commercial.html are asked to have anyway.

**Comment by kayhayen** [comment]
Just a note, I have added this detection, and in 1.5 release of Nuitka it will be. CPython 3.11 supports ARM architecture, so it makes sense.
