### ISSUE TITLE
pyside6 --standalone exe run ERROR

### ISSUE THREAD

**Issue by cyz1cyz** [Nuitka/Nuitka#1448]
First. I'm sorry that I didn't provide enough information at the issue before.

When I use nuitka to build a simple pyside6 program ( Such as this url: https://doc.qt.io/qtforpython/examples/example_webenginequick__nanobrowser.html)  with --standalone ( Command is "python -m nuitka --standalone --enable-plugin=pyside6 main.py")and run exe，it will say an ERROR：

Problem importing shibokensupport:
ModuleNotFoundError: No module named 'argparse'
Traceback (most recent call last):
File "signature_bootstrap.py", line 98, in ensure_shibokensupport
File "signature_bootstrap.py", line 112, in bootstrap
File "signature_bootstrap.py", line 167, in exec_module
File "shibokensupport/signature/loader.py", line 146, in
File "signature_bootstrap.py", line 167, in exec_module
File "shibokensupport/signature/lib/pyi_generator.py", line 48, in
ModuleNotFoundError: No module named 'argparse'
sys.path:
C:\Users\anuser\PycharmProjects\pythonProject\main.dist
C:\Users\anuser\PYCHAR1\PYTHON1\MAIN~1.DIS

It look like need argparse，but if I don‘t use --standalone，it can run well.

OS: win11 home Simplified Chinese 22000.527
python: 3.9.9, venv
pip: 21.1.2
msvc:143, from VS2022(17.1)
pyside6: 6.2.3
nuitka:0.7.1, pip

"python -m nuitka --version" shows:
0.7.1
Commercial: None
Python: 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\anuser\PycharmProjects\pythonProject\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

"pip freeze" shows:
Nuitka==0.7.1
PySide6==6.2.3
shiboken6==6.2.3

**Comment by kayhayen** [comment]
This is fixed in 0.7.2 hotfix release. 

We unexpectedly found a C extension module here that insists on loading `argparse` as a hidden dependency, this was a regression. In 0.7 for savings of included bytecode, many modules are no longer considered standard library. This of course has a risk for this kind of regressions. But `argparse`, seriously how can a library use that in C code.

**Comment by zqbxx** [comment]
thanks, solved
