### ISSUE TITLE
Creating Excel module: compiler is out of heap space in pass 2

### ISSUE THREAD

**Issue by epawtows** [Nuitka/Nuitka#1453]
C:\ProgramData\Anaconda3\Scripts>python -m nuitka --version
0.7.3
Commercial: None
Python: 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\ProgramData\Anaconda3\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

Anaconda --version
anaconda Command line client (version 1.7.2)

Installed Nuitka with pip
Installed Anaconda with downloaded installer

No virtual environments used.

Versions:

C:\ProgramData\Anaconda3\Scripts>python -m pip freeze
anaconda-client==1.7.2
anaconda-navigator==1.9.12
conda==4.8.4
conda-build==3.18.11
conda-package-handling==1.7.0
conda-verify==3.4.2
Nuitka==0.7.3
packaging==20.4
pkginfo==1.5.0.1
pyinstaller==4.8
pywin32==227
pywin32-ctypes==0.2.0

I am attempting to compile the gen_py wrapper for Microsoft Excel, as found in C:\ProgramData\Anaconda3\Lib\site-packages\win32com\gen_py
I always get errors for running out of heap space in pass 2. I have attempted to use the --low-memory options, and with lto=no and lto-yes, as indicated in the user manual.  The result is always the same. I have not been able to compile this module previously except under Python 2.7

Command line argument:

C:\ProgramData\Anaconda3\Scripts>nuitka.bat --module --low-memory C:\Temp2\Nuitka_compiles\00020813-0000-0000-C000-000000000046x0x1x8.py

The error result:

Nuitka-Options:INFO: Used command line options: --module --low-memory --jobs=1 --lto=no C:\Temp2\Nuitka_compiles\00020813-0000-0000-C000-000000000046x0x1x8.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main module. Check options and make sure that is intended.
Nuitka:INFO: Starting Python compilation with Nuitka '0.7.3' on Python '3.7' commercial None.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl 14.2).
Unexpected output from this command:
<clcache> /Fomodule.00020813-0000-0000-C000-000000000046x0x1x8.obj /c "module.00020813-0000-0000-C000-000000000046x0x1x8.cpp" /TP /nologo /Ox /GF /Gy /EHsc /J /Gd /bigobj /LD /D__NUITKA_NO_ASSERT__ /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=0 /D_NUITKA_MODULE /IC:\ProgramData\Anaconda3\include /I. /IC:\PROGRA~3\ANACON~1\lib\SITE-P~1\nuitka\build\include /IC:\PROGRA~3\ANACON~1\lib\SITE-P~1\nuitka\build\static_src
C:\ProgramData\Anaconda3\Scripts\00020813-0000-0000-C000-000000000046x0x1x8.build\module.00020813-0000-0000-C000-000000000046x0x1x8.cpp(1207551) : fatal error C1002: compiler is out of heap space in pass 2
Backend C:  44%|¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦                                                      | 4/9scons: *** [module.00020813-0000-0000-C000-000000000046x0x1x8.obj] Error 1

**Comment by kayhayen** [comment]
I think these are really large, generated modules, the report is a duplicate about that. Checking, I find we did it for `comtypes.gen` and this may be another instance of arbitrarily big generated files. Adding it for that package too then.

Can you explain, how the module is normally used, do you explicitly have to import it in your program, or is this something hidden behind some magic?
