### ISSUE TITLE
Support for PyQt6 application

### ISSUE THREAD

**Issue by redstoneleo** [Nuitka/Nuitka#1455]
Nuitka was installed via pip
```
PS C:\Users\Oscar\Documents\EngkuDict> python -m nuitka --version
0.7.3
Commercial: None
Python: 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\Oscar\AppData\Local\Programs\Python\Python39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
PS C:\Users\Oscar\Documents\EngkuDict>
```

Used command :
`python -m nuitka --standalone --mingw64 --remove-output --enable-plugin=qt-plugins --include-qt-plugins=sensible,styles   PyQt_test.py --show-progress`

Source code for  file `PyQt_test.py`:
```
from PyQt6.QtCore import *
from PyQt6.QtCore import pyqtSlot as Slot
from PyQt6.QtCore import pyqtSignal as Signal
from PyQt6.QtGui import *
from PyQt6.QtWidgets import *
from PyQt6.QtWebEngineWidgets import *
from PyQt6.QtWebEngineCore import *
import sys


class WebEngineView(QMainWindow):  #

    def __init__(self, parent=None):
        super().__init__(parent)


if __name__ == "__main__":

    app = QApplication(sys.argv)
    webEngineView = WebEngineView()
    webEngineView.show()
    sys.exit(app.exec())

```

ERROR:
`FATAL: pyqt5: Error, it seems 'PyQt5' is not installed.`

**Comment by hashuser** [comment]
You can use ```--plugin-enable=pyqt6``` or ```--plugin-enable=pyside6```

**Comment by kayhayen** [comment]
I guess, the old name `qt-plugins` which is now `pyqt5` is also confusing to some. Maybe instead of many ones, there could be a single one which accepts as an argument, which binding version to allow, but that's going to very ugly for the code to all merge.

**Comment by kayhayen** [comment]
I think, I am removing `qt-plugins` rename handling, people coming from older tutorials will not know what this does, and people doing the tutorial maintenance will not know to update it. With 0.8 this is a goner.

**Comment by kayhayen** [comment]
Part of develop to remove the alias.
