### ISSUE TITLE
[QUESTION] Possible to convert a python program to a .dll for DLL Injection?

### ISSUE THREAD

**Issue by msr8** [Nuitka/Nuitka#1456]
Long story short, for an **ethical hacking assignment**, I need to imbed a python program inside another executable (this isn't the exact question but this is the solution that I have thought of). I can use msfvenom for DLL injection, but I need to create the malicious .dll file. So is it possible to convert some malicious python code into a .dll file using nuitka?

**Comment by kayhayen** [comment]
Yes, but I don't support this for free. Consider using https://nuitka.net/doc/commercial.html to buy my time.
