### ISSUE TITLE
How to include pyarmor in nuitka

### ISSUE THREAD

**Issue by SadLandscape** [Nuitka/Nuitka#1457]
Let's say we have 2 files: 
mainfile.py
```
from modulefile import x
x()
```
modulefile.py
```
def x():
    print("Working!")
```
how can I obfuscate these two files and include it in nuitka as a onefile executable?

I tried it once but it told things like name '__pyarmor__' is not defined or no module named modulefile

**Comment by kayhayen** [comment]
Using PyArmor is not useful with Nuitka, as it does not contain bytecode, and compare to Nuitka commercial https://nuitka.net/doc/commercial.html it is even an ridiculously inferior solution to begin with.
