### ISSUE TITLE
Spanish accents and character codes wrongly displayed on printing to console on Windows

### ISSUE THREAD

**Issue by pihglez** [Nuitka/Nuitka#1459]
**python -m nuitka --version**
0.7.3
Commercial: None
Python: 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
Flavor: Unknown
Executable: R:\20201002 - Promoción en Tacoronte\PDF\zPrepMontaje\monta\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

**Installed Nuitka using pip after setting a virtualenv**

**PyPI names and versions**
Nuitka==0.7.3
PyPDF2==1.26.0

**Code example and results**
> print("Hernández")
Result after Nuitka compilation:
> Hern├índez
What would be the result:
> Hernández

**Nuitka options**
python -m nuitka --standalone --onefile seccionamontaje.py

**Comment by kayhayen** [comment]
This is a Windows specific bug limited to older Python versions. Upgrade to 3.8 at least.
