### ISSUE TITLE
Nuitka doesn't support pkg_resources.get_distribution

### ISSUE THREAD

**Issue by kayhayen** [Nuitka/Nuitka#146]
Sometimes code will check installed package versions with require or use the version information of installed packages for outputs. For standalone packages that does not work:

`__version__ = pkg_resources.get_distribution('requests').version`

However, by teaching pkg_resources about our meta path based importer, we could convince it
to provide the information even when egg data, etc. has been lost.

The source of the information is easy to get:

```
env = pkg_resources.Environment()
env.scan()
print(env._distmap)
```

This produces a dictionary with the information to use to produce  `Distribution` objects at run time.

This apparently mostly does the job, but is bare of robustness:

```
def get_importer(path_item):
    return sys.meta_path[0]

def my_finder(a,b,c):
    yield pkg_resources.Distribution(project_name = "requests", version = "5")

pkg_resources.register_finder(type(sys.meta_path[0]), my_finder)
pkg_resources.get_importer = get_importer

__version__ = pkg_resources.get_distribution('requests').version

```

This code could become a post-load for `pkg_resources` to monkey patch it for finding resources hidden in the meta path based loader. Our meta path based loader should not be assumed to be only one (it is not for Python3 anyway), but directly accessed. 

Also maybe it could read the distribution data from disk, to avoid caching issues, and it's nicer
to read that way probably too.

**Comment by kayhayen** [comment]
With 0.6.1 release, I want to work on this for the next release.

**Comment by kiranmantri** [comment]
Hi @kayhayen,
Do you know what is the status of this issue?

Thanks

**Comment by oz123** [comment]
I have had similar issues in the past with `pyinstaller`. When running a program packages with pyinstaller one can detect if the environment is `frozen` with [run time information](https://pyinstaller.readthedocs.io/en/v3.3.1/runtime-information.html#run-time-information). Maybe a similar approach can be implemented in nuitka? 
Can you expand on how to detect during run time whether an application is inside a binary packaged by nuitka?

**Comment by kayhayen** [comment]
There is a plugin in Nuitka that detects these kinds of version stuff, and resolves them now at compile time to the correct value, avoiding any runtime code, which makes this a solved issue.

**Comment by oz123** [comment]
@kayhayen maybe you can link to the plugin?

**Comment by kayhayen** [comment]
It's automatically enabled.
