### ISSUE TITLE
Include-module does not work

### ISSUE THREAD

**Issue by dagginio** [Nuitka/Nuitka#1463]
Hello,

I just found nuitka and up to know I like it. However, I found one issue with the --include-module/package option. My compiled code complains about missing "pydoc" module. So I added with --include-module option. I also tried package and package-data, it does not work. 

During compilation it says: WARNING: Did not follow import to unused 'pydoc', consider include options.

I found this bug report, which seems to be similar, but it does not help me.
https://github.com/Nuitka/Nuitka/issues/1112

I am on windows11 with python 3.9.9 and nuitka 0.73 installed by pip

Thanks for your help.
Daniel

**Comment by kayhayen** [comment]
No issue template, no use.
