### ISSUE TITLE
Wheel build issue with cibuildwheel

### ISSUE THREAD

**Issue by nschloe** [Nuitka/Nuitka#1464]
When building Nuitka projects with [cibuildwheel](https://github.com/pypa/cibuildwheel), e.g., [this toy project](https://github.com/nschloe/myfoobar), .so-library files accumulate in the wheels, i.e., the wheel for Python 3.10 contains .so-files for all versions 3.7-3.10. I brought this up to the cibuildwheel devs [here](https://github.com/pypa/cibuildwheel/discussions/1048). The suggestion is that Nuitka probably doesn't handle caching correctly. Quoting:

> Going to guess nuitka doesn't handle caching correctly and is collecting the outputs cached by initial runs. It should cache based on Python version, os, etc - everything that goes into a wheel.
>
> To fix it you could add a pre-build step that deletes the cache, though you'd need to figure out where they are caching the outputs.

**Comment by kayhayen** [comment]
Have you attempted deleting the Nuitka cache then, and as such evidence that it is actually true?

**Comment by nschloe** [comment]
Yup, I'm now clearing the `build/` directory before each build. That works correctly.

**Comment by kayhayen** [comment]
Well, the `build` directory is not a cache of Nuitka, but something from `setuptools`. All Nuitka does, is to go over the python files and replace them with the extension module, and then let other code do its thing. Maybe it is supposed to clean up that directory, in the end, but if it is, that never happens for me for any other build. 

So maybe it is supposed to clear it at the beginning, but I feel very innocent, because Nuitka only overloads code that works on it being populated. 

You can check `nuitka/distutils/DistutilCommands.py` to only remove the Python files, and place the extension module, and otherwise to wrap all commands and the nuitka build backend just uses `bdist_nuitka` rather than `bdist_wheel` and otherwise is also the same.

There are options to clear temporary stages after build to setuptools, these are probably not used with the toml based configuration.

**Comment by kayhayen** [comment]
I checked, by going into `tests/distutils/example_pyproject_1` and running `python3.8 -m build` and `python3.7 -m build` and there was no such issue as you describe. From your toy project, same thing. So total waste of my time, except that I think I got the idea how to specify options with toml and pyproject then.

**Comment by nschloe** [comment]
You're missing `--wheel`. Exact steps to reproduce:
- Clone the MWE repo
- `python3.9 -m build --wheel`
- `python3.8 -m build --wheel`
- unzip `dist/myfoobar-0.0.1-cp39-cp39-linux_x86_64.whl` to find both `.so` files

**Comment by kayhayen** [comment]
Well, why would I use `--wheel`, it was making wheels by default. 

Citing help output is very confusing:

    By default, a source distribution (sdist) is built from {srcdir}
    and a binary distribution (wheel) is built from the sdist.
    This is recommended as it will ensure the sdist can be used
    to build wheels.

    Pass -s/--sdist and/or -w/--wheel to build a specific distribution.
    If you do this, the default behavior will be disabled, and all
    artifacts will be built from {srcdir} (even if you combine
    -w/--wheel with -s/--sdist, the wheel will be built from {srcdir}).

**Comment by kayhayen** [comment]
Maybe it's picking up the build folder therefore, while is below there, definitely none of Nuitka's business though, definitely something about how the tool is used. You probably can demonstrate the bug without Nuitka and version specific extension modules built too.

**Comment by nschloe** [comment]
I tried to demonstrate it with setuptools packages with C++ extensions, but I don't see this behavior there.

I don't want to push too hard on this since I have found a workaround for me (removing the build/ folder). If there are more problems with this in the future, we can come back to it.

**Comment by kayhayen** [comment]
While I believe you, I think it's still something outside of Nuitka's control. Working off a source directory with an extension module, is your choice there, and there is a wheel. The code of Nuitka is not tasked to judge what else there is in the build folder, e.g. there could be rust built stuff there, as seen in other issues.

Not sure if you used the `pyproject.toml` there, did you? If you shared that, I could compare it. I can reproduce it, but I have no idea, why in one case cleaning would occur, while not in the other.

**Comment by nschloe** [comment]
Alright, thanks for looking further into it.

**Comment by kayhayen** [comment]
Let me know when you updated it. I have no clue how to build an extension module with `pyproject.toml`, hoping on you here.
