### ISSUE TITLE
Nuitka UPX plugin can't handle NotCompressibleException

### ISSUE THREAD

**Issue by hashuser** [Nuitka/Nuitka#1466]
Nuitka can't handle ```NotCompressibleException```
When UPX detect low compresion ratio, it may throw ```NotCompressibleException```
![157877697-dd3bcfc9-b397-48fe-9667-8dfd260899f6](https://user-images.githubusercontent.com/60065064/157879013-ab5c4f8c-826c-42d9-8361-2a28865d85bd.png)
```
Nuitka-Plugins:INFO: upx: Uncached file, compressing 'api-ms-win-crt-runtime-l1-1-0.dll' may take a while.
upx: C:\Users\home\Desktop\Python\1\Yashmak.dist\api-ms-win-crt-runtime-l1-1-0.dll: NotCompressibleException
Traceback (most recent call last):
  File "C:\Users\Home\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\__main__.py", line 137, in <module>
    main()
  File "C:\Users\Home\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\__main__.py", line 123, in main
    MainControl.main()
  File "C:\Users\Home\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\MainControl.py", line 963, in main
    copyDllsUsed(
  File "C:\Users\Home\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\freezer\Standalone.py", line 1433, in copyDllsUsed
    Plugins.onCopiedDLLs(dist_dir=dist_dir, used_dlls=used_dlls)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\plugins\Plugins.py", line 415, in onCopiedDLLs
    plugin.onCopiedDLL(
  File "C:\Users\Home\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\plugins\standard\UpxPlugin.py", line 122, in onCopiedDLL
    self._compressFile(filename=dll_filename, use_cache=not self.upx_nocache)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\plugins\standard\UpxPlugin.py", line 102, in _compressFile
    check_call(
  File "C:\Users\Home\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\utils\Execution.py", line 141, in check_call
    subprocess.check_call(*popenargs, **kwargs)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Home\\Desktop\\Python\\upx.exe', '-q', '--no-progress', 'C:\\Users\\home\\Desktop\\Python\\1\\Yashmak.dist\\api-ms-win-crt-runtime-l1-1-0.dll']' returned non-zero exit status 1.
```

**Comment by hashuser** [comment]
![image](https://user-images.githubusercontent.com/60065064/157871961-daa157fe-9df1-4f83-8f53-4712b25daf8b.png)

![image](https://user-images.githubusercontent.com/60065064/157872010-4a41eddd-6b4c-4b6a-a101-a37a7ca87e6b.png)

![image](https://user-images.githubusercontent.com/60065064/157872077-fdcb38c2-be7c-40d5-92f4-29ecd36c367c.png)

![image](https://user-images.githubusercontent.com/60065064/157872138-9ce44d69-e96c-49e2-b325-82df229729e7.png)

![image](https://user-images.githubusercontent.com/60065064/157872190-89df4351-85e4-406f-a76a-3f46d6304640.png)

![image](https://user-images.githubusercontent.com/60065064/157872235-87e4a80f-e1b9-4e0e-8f90-fbddf48cc0d6.png)

![image](https://user-images.githubusercontent.com/60065064/157872303-677eea30-c481-4bc0-8ecd-d59afa2866d6.png)

![image](https://user-images.githubusercontent.com/60065064/157872359-05a8516e-d12d-4584-bfb1-e49cf7900ada.png)

![image](https://user-images.githubusercontent.com/60065064/157872412-2a72d8ad-6d19-4f6b-aedc-f31a7b90dbcf.png)

![image](https://user-images.githubusercontent.com/60065064/157872568-8b04d4e7-4b41-4546-9a36-5b19456aaae1.png)

![image](https://user-images.githubusercontent.com/60065064/157872626-d43c7309-fd18-439a-b114-6455b892fbfc.png)

![image](https://user-images.githubusercontent.com/60065064/157872683-5c855639-5cb6-4327-9dd5-aaab4cba6b5f.png)

![image](https://user-images.githubusercontent.com/60065064/157872747-fc0e2450-a1a9-4dc7-bdc7-510fbdd7a9a1.png)

![image](https://user-images.githubusercontent.com/60065064/157872974-c5f643c7-166e-496f-ba91-0af807a73509.png)

![image](https://user-images.githubusercontent.com/60065064/157873037-7c42eacd-01e4-425b-9e72-6746e453f751.png)

![image](https://user-images.githubusercontent.com/60065064/157873109-ecfa512d-e892-4692-a8ec-8e120170b49b.png)

![image](https://user-images.githubusercontent.com/60065064/157873258-562bf8ce-d6f8-4c24-b190-b58e123d2319.png)

![image](https://user-images.githubusercontent.com/60065064/157873328-b84ca88b-c788-4238-af69-2223d4c65179.png)

![image](https://user-images.githubusercontent.com/60065064/157873373-8ed7f317-1295-43ab-9ad0-df8f77e8d3f6.png)

![image](https://user-images.githubusercontent.com/60065064/157873431-dd1f6bd1-4ac4-431e-80e7-2564858d1499.png)

![image](https://user-images.githubusercontent.com/60065064/157873492-b8be6074-dac5-445a-8a31-c2097ac04d84.png)

![image](https://user-images.githubusercontent.com/60065064/157873551-c5e02060-7d96-4982-ac6a-b058a28d7b28.png)

![image](https://user-images.githubusercontent.com/60065064/157873609-8c6d6318-918a-4eda-b3d7-13ec5d7479fb.png)

![image](https://user-images.githubusercontent.com/60065064/157873669-5e0712c0-3de6-4a2e-af21-63e49bcad2cc.png)

![image](https://user-images.githubusercontent.com/60065064/157873739-0176ba81-f8f8-4656-aaac-2bc0391391e0.png)

![image](https://user-images.githubusercontent.com/60065064/157873896-454da4b8-3e0b-4545-ba0d-4c05f14d95bf.png)

![image](https://user-images.githubusercontent.com/60065064/157873942-f4d5f437-a00a-43c7-8e16-c666fc0cc95b.png)

![image](https://user-images.githubusercontent.com/60065064/157874035-8eaf4ed3-2d29-4bc2-9562-7357a53e30af.png)

![image](https://user-images.githubusercontent.com/60065064/157874077-7dc4e175-eba8-4272-b5ce-3d50f98996d9.png)

![image](https://user-images.githubusercontent.com/60065064/157874123-3b7bdcdf-0d89-4a39-9e9e-1847dfda046f.png)

![image](https://user-images.githubusercontent.com/60065064/157874188-a9c2ee4e-78a7-42b2-8a27-632b9f695d1f.png)

![image](https://user-images.githubusercontent.com/60065064/157874243-03576f7e-581d-4c23-a103-c7c5492dfb23.png)

![image](https://user-images.githubusercontent.com/60065064/157874288-ddafb510-6239-43c2-91cb-ae380b787ecc.png)

![image](https://user-images.githubusercontent.com/60065064/157874538-cb898671-6166-4d83-a88c-e3b05aedef09.png)

![image](https://user-images.githubusercontent.com/60065064/157874745-75961aab-0dc0-4fe8-b7a5-1b2b944e9d64.png)

![image](https://user-images.githubusercontent.com/60065064/157874935-15e3dff5-6fa3-4931-a4d5-fab28b648d7c.png)

![image](https://user-images.githubusercontent.com/60065064/157875150-28d3d4d4-eef8-44f5-9d07-8bdfc8692a0e.png)

![image](https://user-images.githubusercontent.com/60065064/157875328-ff65003d-363f-4898-aa61-9358169aa5e9.png)

**Comment by kayhayen** [comment]
Somebody didn't read the part for screenshots, though. Strange that I didn't have this yet, but I take it can happen.

**Comment by kayhayen** [comment]
I updated factory to have this as well. It won't be part of a hotfix release though, since I made an interface change to a widely used helper function for it to be easy.

**Comment by hashuser** [comment]
> Somebody didn't read the part for screenshots, though. Strange that I didn't have this yet, but I take it can happen.

Sorry, my bad. I've hide that comment.

**Comment by kayhayen** [comment]
This has been on develop branch for a while, but was never marked with factory it seems.

**Comment by kayhayen** [comment]
Part of 0.8 release that I just made.
