### ISSUE TITLE
tomli: File must be opened in binary mode

### ISSUE THREAD

**Issue by nschloe** [Nuitka/Nuitka#1467]
When building a project in the factory branch, I'm getting
```
TypeError: File must be opened in binary mode, e.g. use `open('foo.toml', 'rb')`
```
This is from
```python
                try:
                    from tomli import load as toml_load
                except ModuleNotFoundError:
                    from toml import load as toml_load

                with open(toml_filename) as toml_file:
                    toml_options = toml_load(toml_file)
```
in `nuitka/distutils/DistutilCommands.py`, specifically the `tomli` branch.

**Comment by kayhayen** [comment]
Was that on Windows, because I didn't have it.

**Comment by kayhayen** [comment]
I added it, since it's factory, no tracking of the issue is needed.

**Comment by nschloe** [comment]
This is on Linux, but happens on any operating system. Default tomli behavior: https://github.com/hukkin/tomli#parse-a-toml-file.

**Comment by kayhayen** [comment]
Like I said with the wrong account, I was using a Python3 with tomli installed to test this too, but apparently I didn't notice that it was using the wrong Nuitka install there, which then didn't even have the code. This stuff is really annoying to test for development. Anyway, seems it is working for you now, is it?

**Comment by nschloe** [comment]
It only works when deinstalling tomli. This is still a bug.

**Comment by kayhayen** [comment]
With current factory code?

**Comment by kayhayen** [comment]
Note, you need to specify the update options, or else you might be using an older version of factory easily. Using git is best, but probably integrates badly with pyproject dependencies.

**Comment by kayhayen** [comment]
So, I got this in my experiments, not sure what is going on. The `toml` package wants a string:

> TypeError: Expecting something like a string

and `tomli` I couldn't get to care.

**Comment by kayhayen** [comment]
So, the original code should be working, this was 3.9 on Linux. Now what I will say is that the code in `build` should be leading, and it is using this:

            with open(spec_file, 'rb') as f:
                spec = toml_loads(f.read().decode())

But Nuitka is using `load` rather than `loads` and then names it `loads`. Must be an error I made.

**Comment by kayhayen** [comment]
I changed to `loads` and it should now work then, although my tests didn't produce your error, using the same code as `build` was the intention.
