### ISSUE TITLE
Cannot use shelve without manual import of dbm.dumb

### ISSUE THREAD

**Issue by notiflux** [Nuitka/Nuitka#1474]
> python -m nuitka --version
```
0.7.5
Commercial: None
Python: 3.8.12 (heads/master:bd5e0bb, Aug 31 2021, 10:21:45) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\<user>\AppData\Local\Programs\Python\Python38\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

Nuitka was installed using pip.
Python was installed using the binary installer.

```
import shelve

pConfig = shelve.open("config")
pConfig.close()
```

Compiling the above code example with the following options:
```
python -m nuitka --standalone --follow-imports test.py
```

yields the following output when executing the binary:
```
Traceback (most recent call last):
  File "C:\Users\<user>\nuitkaTest\test.py", line 3, in <module>
  File "C:\Users\<user>\nuitkaTest\shelve.py", line 243, in open
  File "C:\Users\<user>\nuitkaTest\shelve.py", line 226, in __init__
ModuleNotFoundError: No module named 'dbm'
```
Using the current develop version of nuitka (0.8rc6) yields the same error.

If I add `import dbm` in front of `import shelve`, I get an error saying it couldn't find any implementation of dbm (neither dbm.gnu, nor dbm.ndbm, nor dbm.dumb)
If I add `import dbm.dumb` it works fine.

Nuitka version 0.6.19.7 worked perfectly fine.

**Comment by kayhayen** [comment]
Yes, `dbm` is no longer included, as are some other parts of the standard library. I am going to add the dependency, then it will work again. In the meantime, `--include-module=dbm` ought to also work.

**Comment by notiflux** [comment]
I saw that you included dbm in version 0.7.7 again, but it does not automatically include an implementation of it. On Windows, that leads to this error:
```
Traceback (most recent call last):
  File "C:\Dev\TEST~1.DIS\test.py", line 3, in <module>
  File "C:\Dev\TEST~1.DIS\shelve.py", line 243, in open
  File "C:\Dev\TEST~1.DIS\shelve.py", line 227, in _init_
  File "C:\Dev\TEST~1.DIS\dbm\_init_.py", line 75, in open
ImportError: no dbm clone found; tried ['dbm.gnu', 'dbm.ndbm', 'dbm.dumb']
```

adding `--include-module=dbm` yields the same output. Adding `--include-module=dbm.dumb` however, works.

**Comment by kayhayen** [comment]
My bad, I probably checked only on Linux, usually that makes no difference. Also I forgot to ask you to test this, bad. :-)

**Comment by kayhayen** [comment]
So, on Windows, the `dbm.dumb` is the only one working, while on Linux `dbm.ndbm` is visible as a dependency and working probably. I guess, we need to put `dbm.dumb` there.

Please check out this https://nuitka.net/doc/factory.html works on Windows too. And maybe better for Linux because it needs no system libraries that are optional.

**Comment by kayhayen** [comment]
I intend to release 0.8 very soon, probably Friday, so I am pushing this away from 0.7, you can though manually edit the file in Nuitka if you want to have it working with 0.7 now, but factory is my stabilizing attempt, once it's on develop it's practically release quality.

**Comment by notiflux** [comment]
yes, current factory version works perfectly. thank you

**Comment by kayhayen** [comment]
This is now on develop and will be in 0.8 release.

**Comment by kayhayen** [comment]
Part of 0.8 release that I just made.
