### ISSUE TITLE
pkg_resources.DistributionNotFound when using betterproto

### ISSUE THREAD

**Issue by 124C41p** [Nuitka/Nuitka#1476]
After compiling any project which imports `betterproto` in standalone mode, the resulting executable crashes with error

> pkg_resources.DistributionNotFound: The 'betterproto' distribution was not found and is required by the application

This error is caused by the line

> `__version__ = get_distribution("betterproto").version`

inside the betterproto module. It can be avoided by monkey patching `pkg_resources.get_distribution`.
This seemed to be a known issue in general, and should have been fixed in #146. Apparently the fix missed some situation special to betterproto. Can you please revisit #146?

### Affected version
Nuitka 0.7.5 (latest release currently)

### How to reproduce the bug
You can reproduce the bug under Windows 10 with Python3.7 or Python3.10 in the following way:

Install the requirements (pip freeze output)
> betterproto==2.0.0b4
> grpclib==0.4.2
> h2==4.1.0
> hpack==4.0.0
> hyperframe==6.0.1
> multidict==6.0.2
> Nuitka==0.7.5
> python-dateutil==2.8.2
> six==1.16.0

Create `main.py` with the following content
> `import betterproto`

Compile it with nuitka
> python -m nuitka --standalone .\main.py

Run executable
> .\main.dist\main.exe

**Comment by kayhayen** [comment]
It's on the roadmap to replace current source based hacks with actual hard import tracing, until then, this form of call will not work.

**Comment by kayhayen** [comment]
This `distribution.version` stuff is actually a bit harder, as it requires us to assign a shape for the distribution call, where we then pretend to know attribute values of it, need to think if this should be generated code maybe. Other `pkg_resources` nodes like `resource_data` felt like it could be.

**Comment by kayhayen** [comment]
This will make it straight to 2.0.2 too, once released, hopefully soon.
