### ISSUE TITLE
setup.py to setup.cfg

### ISSUE THREAD

**Issue by avlap** [Nuitka/Nuitka#1480]
I tried to build a test project with Nuitka and setuptools. I do get a error:
$ hello
Traceback (most recent call last):
  File "/home/archie/.local/bin/hello", line 5, in <module>
    from lib.hello import hello_world
ModuleNotFoundError: No module named 'lib.hello'

It probably doesn't follow the module imports?

Here is the testing project:

https://github.com/avlap/setuptools_testing/tree/nuitka

In the manual there is only a example of a setup.py for such a use case:
https://nuitka.net/doc/user-manual.html#use-case-5-setuptools-wheels

Can someone give me pointers on how to make this work with a setup.cfg file?

**Comment by kayhayen** [comment]
Please retry with a filled out issue template.
