### ISSUE TITLE
No module named X when using nuitka with setuptools / wheels (setup.cfg vs setup.py)

### ISSUE THREAD

**Issue by avlap** [Nuitka/Nuitka#1481]
$ python -m nuitka --version
0.7.5
Commercial: None
Python: 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
Flavor: Unknown
Executable: /usr/bin/python
OS: Linux
Arch: x86_64
Distribution: Arch None

- How did you install Nuitka and Python
Arch repositories, no venv

pyproject.toml:
[build-system]
requires = ["setuptools>=42", "wheel", "nuitka"]
build-backend = "nuitka.distutils.Build"

setup.cfg:
[metadata]
name = hello
version = 0.0.1
author = Example Author
description = A small example package
long_description = file: README.md
long_description_content_type = text/markdown
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: Linux

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.10
#install_requires =

[options.packages.find]
where = src

[options.entry_points]
console_scripts =
        hello = lib.hello:hello_world

ISSUE:

I tried to build a test project with Nuitka and setuptools. I do get a error:
$ hello
Traceback (most recent call last):
File "/home/archie/.local/bin/hello", line 5, in
from lib.hello import hello_world
ModuleNotFoundError: No module named 'lib.hello'

It probably doesn't follow the module imports?

$ ls .local/bin/
hello

$ ls .local/lib/python3.10/site-packages/
build                                  jedi                   psutil                  _yaml
build-0.7.0.dist-info                  jedi-0.18.1.dist-info  psutil-5.9.0.dist-info  yaml
hello-0.0.1.dist-info                  LICENCE                PyYAML-5.4.1.dist-info
hello.cpython-310-x86_64-linux-gnu.so  parso                  xdg
hello.pyi                              parso-0.8.3.dist-info  xdg-5.1.1.dist-info

Here is the testing project:

https://github.com/avlap/setuptools_testing/tree/nuitka

In the manual there is only a example of a setup.py for such a use case:
https://nuitka.net/doc/user-manual.html#use-case-5-setuptools-wheels

Can someone give me pointers on how to make this work with a setup.cfg file?

**Comment by kayhayen** [comment]
The thing it is ignoring, not aware of is this:

```
[options.packages.find]
where = src
```

Not of the current test cases have that.

Also, not sure what this is supposed to be

```
[options]
package_dir =
    = src
packages = find:
```

None of the test cases have a `package_dir` assignment, either.

Maybe it means the same. Since Nuitka never handles `find:` but I think only sees package names, it may be necessary that you repeat yourself there or not, will have to test that too.

So it just won't find that. I wonder if this is something akin to a `PYTHONPATH`, and if Nuitka would have to amend the existing one, or override it. This would of course be easy to add, once the information is found.

If you moved `lib` to top level, and remove those, it would work. Should be an easy fix to Nuitka, likely even hotfix material to solve this, but needs a bit of research on what to do.

**Comment by kayhayen** [comment]
This is working now: https://nuitka.net/doc/factory.html

Let me know if that's working for you, I think I can include it in the next hotfix, even.

**Comment by avlap** [comment]
> The thing it is ignoring, not aware of is this:
> 
> ```
> [options.packages.find]
> where = src
>

 ```
"packages is a list of all Python [import packages](https://packaging.python.org/en/latest/glossary/#term-Import-Package) 

that should be included in the [distribution package](https://packaging.python.org/en/latest/glossary/#term-Distribution-Package). 
Instead of listing each package manually, we can use the find: directive to automatically discover all packages and 
subpackages and options.packages.find to specify the package_dir to use. In this case,
 the list of packages will be example_package as that’s the only package present"


https://packaging.python.org/en/latest/tutorials/packaging-projects/

> 
> Not of the current test cases have that.
> 
> Also, not sure what this is supposed to be
> 
> ```
> [options]
> package_dir =
>     = src
> packages = find:
> ```

"package_dir is a mapping of package names and directories. An empty package name represents the “root package” —
the directory in the project that contains all Python source files for the package — so in this case the src directory is 
designated the root package."


https://packaging.python.org/en/latest/tutorials/packaging-projects/
> 
> None of the test cases have a `package_dir` assignment, either.
> 
> Maybe it means the same. Since Nuitka never handles `find:` but I think only sees package names, it may be necessary that you repeat yourself there or not, will have to test that too.
> 
> So it just won't find that. I wonder if this is something akin to a `PYTHONPATH`, and if Nuitka would have to amend the existing one, or override it. This would of course be easy to add, once the information is found.
> 
> If you moved `lib` to top level, and remove those, it would work. Should be an easy fix to Nuitka, likely even hotfix material to solve this, but needs a bit of research on what to do.


Thanks will do some testing.
I'm fairly new to python and so to packaging, but they move away from setup.py, 
at least for the configuring part.

Some resources:
https://packaging.python.org/en/latest/tutorials/packaging-projects/
https://setuptools.pypa.io/en/latest/userguide/declarative_config.html
https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html

**Comment by kayhayen** [comment]
It's part of the current hotfix, I am assuming it fixes that. I am not dealing with the dictionary nature of things there, just accepting the root change, which is in the examples, and basically I doubt it matters, and I didn't want to create a test case. Can deal with package_dir as an actual dictionary when real users have that.

**Comment by avlap** [comment]
Hm could be me, but I can't get this to work.

$ python -m nuitka --version
0.8rc6
Commercial: None
Python: 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
Flavor: Unknown
Executable: /usr/bin/python
OS: Linux
Arch: x86_64
Distribution: Arch None


$ hello
Traceback (most recent call last):
  File "/home/archie/.local/bin/hello", line 5, in <module>
    from hello import hello_world
ImportError: cannot import name 'hello_world' from 'hello' (/home/archie/.local/lib/python3.10/site-packages/hello.cpython-310-x86_64-linux-gnu.so)



https://github.com/avlap/setuptools_testing/tree/nuitka_factory

**Comment by kayhayen** [comment]
Yes, could be you, impossible to tell from what you provided, raise a new issue and make sure you use the Nuitka you cite in the build actually.

**Comment by avlap** [comment]
Got it working, thx.

**Comment by avlap** [comment]
"If you moved lib to top level, and remove those, it would work. Should be an easy fix to Nuitka, likely even hotfix material to solve this, but needs a bit of research on what to do."

It looks indeed, that it's not working when having a separate lib folder.

I think the whole idea of the new setup.cfg / pyproject.toml mechanism, is that you can keep the same setup (folder tree / module setup), and use different build tools for it. This also would be a ideal scenario for Nuitka I can imagine. It makes it easy for people to switch to Nuitka, having the same setup. I'm a bit surprised that it doesn't seems to work that way at the moment.

Now it seems I've to make one step up in the folder tree to get it build with: python -m nuitka --follow-imports program.py

If I'm right, I think that needs a fix.
