### ISSUE TITLE
How can I save and modify the C source generated?

### ISSUE THREAD

**Issue by c5ace** [Nuitka/Nuitka#1482]
I just installed nuitka '0.7.6' on Gentoo Linux and want to converting about 5000 lines of python source to C source.  No Windows or MinGW. Only gcc.  

I can't find instructions to do this.  

The resulting C source is to be modified, debugged and optimized for speed with assembler for my own hardware and to be integrated into existing C source.  The existing Python 2 code is very slow and insecure.  

Command line examples will be appreciated.

Thank you in advance.

**Comment by kayhayen** [comment]
Nuitka is not a converter, and we do not support this use case outside https://nuitka.net/doc/commercial.html where the time would have to be paid for.
