### ISSUE TITLE
OSError: [Errno 7] Argument list too long: 'ldd'

### ISSUE THREAD

**Issue by MyraBaba** [Nuitka/Nuitka#1485]
I have python code includes numpy torch mxnet opencv.

after few hours compiling it gives 👍 
OSError: [Errno 7] Argument list too long: 'ldd'

is there any solution for this argument limit ? 

runned :   python -m nuitka --onefile --enable-plugin=numpy --enable-plugin=torch video.py
latest nuitka 0.7.6
ubuntu 18 & 20

**Comment by kayhayen** [comment]
Hm, `ldd` is called elsewhere too. I think I should really stop even reading incomplete reports, e.g. ones without a traceback where one should be.

**Comment by MyraBaba** [comment]
@kayhayen 

is that helpfull

python -m nuitka --onefile --enable-plugin=numpy --enable-plugin=torch video.py
Nuitka-Options:INFO: Used command line options: --onefile --enable-plugin=numpy --enable-plugin=torch video.py
Nuitka:INFO: Starting Python compilation with Nuitka '0.7.6' on Python '3.6' commercial None.
Nuitka-Plugins:INFO: anti-bloat: Handling module 'scipy._lib._testutils' with full replacement : remove numpy testing framework.  
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'scipy._lib' added 'scipy._lib.messagestream'.             
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'scipy.sparse.csgraph' added 'scipy.sparse.csgraph._validation'.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':                                
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.                                     
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':                               
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.                                 
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'scipy.linalg' added 'scipy.linalg.cython_blas,scipy.linalg.cython_lapack'.
Nuitka-Plugins:INFO: anti-bloat: Handling module 'numpy._pytesttester' with full replacement : remove numpy testing framework.    
Nuitka-Plugins:INFO: anti-bloat: Handling module 'numpy.core.overrides' with 1 change(s) for: workaround numpy issues with compiled code.
Nuitka-Plugins:INFO: anti-bloat: Handling module 'pydoc' with 1 change(s) for: remove module ability to display GUI with tkinter and topics data.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'numpy.core' added 'numpy.core._dtype_ctypes,numpy.core._multiarray_tests'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pkg_resources.extern' added 'pkg_resources._vendor.packaging,pkg_resources._vendor.pyparsing,pkg_resources._vendor.appdirs'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pkg_resources._vendor.packaging' added 'pkg_resources._vendor.packaging.version,pkg_resources._vendor.packaging.specifiers,pkg_resources._vendor.packaging.requirements'.
Nuitka-Plugins:INFO: anti-bloat: Updated module 'scipy.integrate._quadrature' function '_copy_func'.                              
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'scipy.spatial' added 'scipy.spatial.transform,scipy.spatial.transform._rotation_groups'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'scipy.spatial.transform' added 'scipy.spatial.transform._rotation_groups'.
Nuitka-Plugins:INFO: anti-bloat: Handling module 'matplotlib' with 1 change(s) for: remove setuptools and pytest testing framework reference.
Nuitka-Plugins:INFO: anti-bloat: Updated module 'matplotlib' function '_init_tests'.                                              
Nuitka-Plugins:INFO: anti-bloat: Updated module 'matplotlib' function 'test'.                                                     
Nuitka-Plugins:INFO: anti-bloat: Updated module 'matplotlib.pyplot' function 'install_repl_displayhook'.                          
Nuitka-Plugins:INFO: anti-bloat: Updated module 'matplotlib.pyplot' function 'uninstall_repl_displayhook'.                        
Nuitka-Plugins:INFO: anti-bloat: Updated module 'matplotlib.backend_bases' function '_fix_ipython_backend2gui'.                   
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'matplotlib.backends.backend_webagg' added 'matplotlib.backends.backend_webagg_core'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'matplotlib.backends.backend_webagg_core' added 'matplotlib.backends.backend_webagg'.
Nuitka-Plugins:INFO: anti-bloat: Handling module 'PIL.ImageShow' with 1 change(s) for: remove IPython reference.                  
Nuitka-Plugins:INFO: anti-bloat: Handling module 'cffi.ffiplatform' with 1 change(s) for: disable distutils hacks.                
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pycparser.c_parser' added 'pycparser.yacctab,pycparser.lextab'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'matplotlib.backends' added 'matplotlib.backends._backend_agg,matplotlib.backends._tkagg,matplotlib.backends.backend_tkagg,matplotlib.backends.backend_agg'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'matplotlib' added 'matplotlib.backend_managers,matplotlib.backend_bases,mpl_toolkits'.
Nuitka-Plugins:INFO: anti-bloat: Handling module 'certifi.core' with 1 change(s) for: avoid using importlib.resources without need.
Nuitka-Plugins:INFO: anti-bloat: Handling module 'numpy.testing' with full replacement : remove numpy testing framework.          
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'scipy.stats._stats' added 'scipy.special.cython_special'. 
Nuitka-Plugins:INFO: anti-bloat: Handling module 'pandas' with 2 change(s) for: remove pandas testing framework.                  
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pandas.core.window' added 'pandas._libs.window'.          
Nuitka-Plugins:INFO: anti-bloat: Updated module 'pandas._testing' function 'external_error_raised'.                               
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pandas._libs' added 'pandas._libs.tslibs.np_datetime,pandas._libs.tslibs.nattype,pandas._libs.tslibs.base'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'sklearn.preprocessing' added 'sklearn.preprocessing._csr_polynomial_expansion'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'sklearn.cluster' added 'sklearn.cluster._dbscan_inner,sklearn.cluster._k_means_elkan'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'sklearn.manifold' added 'sklearn.manifold._barnes_hut_tsne,sklearn.manifold._utils'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'scipy.special' added 'scipy.special._ufuncs_cxx'.         
Nuitka-Plugins:INFO: anti-bloat: Handling module 'sklearn.utils._testing' with 1 change(s) for: remove pytest testing framework.  
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'sklearn.utils' added 'sklearn.utils.arrayfuncs,sklearn.utils.graph_shortest_path,sklearn.utils.murmurhash,sklearn.utils.sparsefuncs_fast,sklearn.utils._cython_blas,sklearn.utils._logistic_sigmoid,sklearn.utils._random'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'cryptography' added '_cffi_backend'.                      
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'urllib3' added 'urllib3._collections,urllib3.connection,urllib3.connectionpool,urllib3.contrib,urllib3.contrib.appengine,urllib3.exceptions,urllib3.fields,urllib3.filepost,urllib3.packages,urllib3.packages.six,urllib3.packages.ssl_match_hostname,urllib3.poolmanager,urllib3.request,urllib3.response,urllib3.util,urllib3.util.connection,urllib3.util.queue,urllib3.util.request,urllib3.util.response,urllib3.util.retry,urllib3.util.ssl_,urllib3.util.timeout,urllib3.util.url,urllib3.util.wait,urllib.error,urllib.parse,urllib.request,http.client,urllib.response'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'skimage.measure' added 'skimage.measure._ccomp,skimage.measure._find_contours_cy,skimage.measure._marching_cubes_classic_cy,skimage.measure._marching_cubes_lewiner_cy,skimage.measure._moments_cy,skimage.measure._pnpoly'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'skimage._shared' added 'skimage._shared.geometry,skimage._shared.interpolation,skimage._shared.transform'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'skimage.transform' added 'skimage.transform._hough_transform,skimage.transform._radon_transform,skimage.transform._warps_cy'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'skimage.feature' added 'skimage.feature.brief_cy,skimage.feature.censure_cy,skimage.feature.corner_cy,skimage.feature.orb_cy,skimage.feature._orb_descriptor_positions,skimage.feature._cascade,skimage.feature._haar,skimage.feature._hessian_det_appx,skimage.feature._hoghistogram,skimage.feature._texture'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'skimage.feature.orb_cy' added 'skimage.feature._orb_descriptor_positions'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'skimage.draw' added 'skimage.draw._draw'.                 
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'skimage.morphology' added 'skimage.morphology._convex_hull,skimage.morphology._extrema_cy,skimage.morphology._flood_fill_cy,skimage.morphology._greyreconstruct,skimage.morphology._max_tree,skimage.morphology._skeletonize_3d_cy,skimage.morphology._skeletonize_cy'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'skimage.segmentation' added 'skimage.segmentation._felzenszwalb_cy,skimage.segmentation._quickshift_cy,skimage.segmentation._slic'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'skimage.filters.rank' added 'skimage.filters.rank.bilateral_cy,skimage.filters.rank.core_cy,skimage.filters.rank.generic_cy,skimage.filters.rank.percentile_cy'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'skimage.restoration' added 'skimage.restoration._denoise_cy,skimage.restoration._nl_means_denoising,skimage.restoration._unwrap_1d,skimage.restoration._unwrap_2d,skimage.restoration._unwrap_3d'.
Nuitka-Plugins:INFO: anti-bloat: Handling module 'pywt._pytesttester' with full replacement : remove pywt testing framework.      
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pywt' added 'pywt._extensions,pywt._extensions._cwt,pywt._extensions._dwt,pywt._extensions._pywt,pywt._extensions._swt'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pywt._extensions' added 'pywt._extensions._cwt,pywt._extensions._dwt,pywt._extensions._pywt,pywt._extensions._swt'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'skimage.io' added 'skimage.io._plugins,skimage.io._plugins._colormixer,skimage.io._plugins._histograms,skimage.io._plugins.fits_plugin,skimage.io._plugins.gdal_plugin,skimage.io._plugins.gtk_plugin,skimage.io._plugins.imageio_plugin,skimage.io._plugins.imread_plugin,skimage.io._plugins.matplotlib_plugin,skimage.io._plugins.pil_plugin,skimage.io._plugins.qt_plugin,skimage.io._plugins.simpleitk_plugin,skimage.io._plugins.tifffile_plugin,skimage.io._plugins.util'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'imageio' added 'PIL.BlpImagePlugin,PIL.BmpImagePlugin,PIL.BufrStubImagePlugin,PIL.CurImagePlugin,PIL.DcxImagePlugin,PIL.DdsImagePlugin,PIL.EpsImagePlugin,PIL.FitsStubImagePlugin,PIL.FliImagePlugin,PIL.FpxImagePlugin,PIL.FtexImagePlugin,PIL.GbrImagePlugin,PIL.GifImagePlugin,PIL.GribStubImagePlugin,PIL.Hdf5StubImagePlugin,PIL.IcnsImagePlugin,PIL.IcoImagePlugin,PIL.ImImagePlugin,PIL.ImtImagePlugin,PIL.IptcImagePlugin,PIL.Jpeg2KImagePlugin,PIL.JpegImagePlugin,PIL.McIdasImagePlugin,PIL.MicImagePlugin,PIL.MpegImagePlugin,PIL.MpoImagePlugin,PIL.MspImagePlugin,PIL.PalmImagePlugin,PIL.PcdImagePlugin,PIL.PcxImagePlugin,PIL.PdfImagePlugin,PIL.PixarImagePlugin,PIL.PngImagePlugin,PIL.PpmImagePlugin,PIL.PsdImagePlugin,PIL.SgiImagePlugin,PIL.SpiderImagePlugin,PIL.SunImagePlugin,PIL.TgaImagePlugin,PIL.TiffImagePlugin,PIL.WebPImagePlugin,PIL.WmfImagePlugin,PIL.XbmImagePlugin,PIL.XpmImagePlugin,PIL.XVThumbImagePlugin'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'PIL._imagingtk' added 'PIL._tkinter_finder'.              
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'skimage.io._plugins' added 'skimage.io._plugins._colormixer,skimage.io._plugins._histograms,skimage.io._plugins.fits_plugin,skimage.io._plugins.gdal_plugin,skimage.io._plugins.gtk_plugin,skimage.io._plugins.imageio_plugin,skimage.io._plugins.imread_plugin,skimage.io._plugins.matplotlib_plugin,skimage.io._plugins.pil_plugin,skimage.io._plugins.qt_plugin,skimage.io._plugins.simpleitk_plugin,skimage.io._plugins.tifffile_plugin,skimage.io._plugins.util'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'numpy.random' added 'numpy.random._bounded_integers,numpy.random._common,numpy.random._generator,numpy.random._mt19937,numpy.random._pcg64,numpy.random._philox,numpy.random._sfc64,numpy.random.bit_generator,numpy.random.mtrand'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'cv2' added 'numpy,numpy.compat,numpy.lib,numpy.linalg,numpy.fft,numpy.polynomial,numpy.random,numpy.random._bounded_integers,numpy.random._common,numpy.random._generator,numpy.random._mt19937,numpy.random._pcg64,numpy.random._philox,numpy.random._sfc64,numpy.random.bit_generator,numpy.random.mtrand,numpy.ctypeslib,numpy.ma,numpy.matrixlib,numpy.core,numpy.core._dtype_ctypes,numpy.core._multiarray_tests'.
Nuitka-Plugins:INFO: anti-bloat: Handling module 'numpy.ctypeslib' with 3 change(s) for: remove numpy.distutils references.       
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'numpy' added 'numpy.compat,numpy.lib,numpy.linalg,numpy.fft,numpy.polynomial,numpy.random,numpy.random._bounded_integers,numpy.random._common,numpy.random._generator,numpy.random._mt19937,numpy.random._pcg64,numpy.random._philox,numpy.random._sfc64,numpy.random.bit_generator,numpy.random.mtrand,numpy.ctypeslib,numpy.ma,numpy.matrixlib'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'urllib.request' added 'http.client'.                      
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'shelve' added 'dbm'.                                      
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pathlib' added 'ntpath,posixpath'.                        
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.                                  
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module '_asyncio' added 'asyncio'.                                
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'locale' added '_bootlocale'.                              
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'encodings' added 'encodings.idna,encodings.base64_codec,encodings.hex_codec,encodings.rot_13'.
Nuitka:INFO: Completed Python level compilation and optimization.                                                                 
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.                                                      
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program (no progress information available).                                                   
Nuitka-Scons:INFO: Running /usr/bin/gcc -o /2_biyotek/video.dist/video -fuse-linker-plugin -flto=16 -fpartial-inlining -freorder-functions -O2 -z noexecstack -Xlinker -export-dynamic -rdynamic -s -Wl,-R,'$ORIGIN' -Wl,--disable-new-dtags -Wl,-b -Wl,binary -Wl,./__constants.bin -Wl,-b -Wl,elf64-x86-64 -Wl,-defsym -Wl,constant_bin_data=_binary_____constants_bin_start @"./@link_input.txt -L/usr/lib -ldl -lm /usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m-pic.a -lz -lm -lutil -lpthread -lexpat took 818.19 seconds
Nuitka-Scons:INFO: Compiled 2865 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 2865
Nuitka-Plugins:INFO: torch: Copying files from 'torch' installation:
Nuitka-Plugins:INFO: torch: Copied 1619 files.
Detecting used DLLs:  25%|███████████████▍                                             | 72/284, video.dist/numpy/random/mtrand.soTraceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nuitka/__main__.py", line 137, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/nuitka/__main__.py", line 123, in main
    MainControl.main()
  File "/usr/local/lib/python3.6/dist-packages/nuitka/MainControl.py", line 966, in main
    standalone_entry_points=getStandaloneEntryPoints(),
  File "/usr/local/lib/python3.6/dist-packages/nuitka/freezer/Standalone.py", line 1375, in copyDllsUsed
    and Options.getWindowsDependencyTool() != "depends.exe",
  File "/usr/local/lib/python3.6/dist-packages/nuitka/freezer/Standalone.py", line 1149, in _detectUsedDLLs
    standalone_entry_point.package_name,
  File "/usr/local/lib/python3.6/dist-packages/nuitka/utils/ThreadedExecutor.py", line 45, in submit
    self.results.append(function(*args))
  File "/usr/local/lib/python3.6/dist-packages/nuitka/freezer/Standalone.py", line 1110, in addDLLInfo
    update_cache=update_cache,
  File "/usr/local/lib/python3.6/dist-packages/nuitka/freezer/Standalone.py", line 1063, in _detectBinaryDLLs
    original_dir=os.path.dirname(original_filename),
  File "/usr/local/lib/python3.6/dist-packages/nuitka/freezer/Standalone.py", line 646, in _detectBinaryPathDLLsPosix
    stdout, stderr, _exit_code = executeProcess(command=("ldd", dll_filename))
  File "/usr/local/lib/python3.6/dist-packages/nuitka/utils/Execution.py", line 362, in executeProcess
    cwd=getExternalUsePath(os.getcwd()) if external_cwd else None,
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: 'ldd'

**Comment by yanboma** [comment]
> I have python code includes numpy torch mxnet opencv.
> 
> after few hours compiling it gives 👍 OSError: [Errno 7] Argument list too long: 'ldd'
> 
> is there any solution for this argument limit ?
> 
> runned : python -m nuitka --onefile --enable-plugin=numpy --enable-plugin=torch video.py latest nuitka 0.7.6 ubuntu 18 & 20

fix it？

**Comment by kayhayen** [comment]
I have made a change such that the directories considered for a package are no longer all sub directories, but only those with filenames matching to DLLs. That ought to avoid the issue even if I never saw it myself. In some cases, e.g. Qt there are a lot of sub-directories for QML and plugins, so this can be the problem there.

**Comment by kayhayen** [comment]
This is now on the develop branch and will be part of the 0.8 release.

**Comment by MyraBaba** [comment]
I will test dev branch today and let you know.

Best

**Comment by MyraBaba** [comment]
Hi @kayhayen 

dev version succesfully compiled one the big code. Its working. 

Is there any way to point the compiled app required libraries ? It is looking it own folder . LD_LIBRARY_PATH adding is not affected. 

Best

**Comment by kayhayen** [comment]
@MyraBaba I don't think I get the question. It's own folder is where it puts things. When something is missing, Nuitka needs to be taught to include it, raise new issues for things that are found missing.

**Comment by MyraBaba** [comment]
@kayhayen  

I want to seperate executable and the all other required libs path for linux . How can I say to onefile executable to look this folder for libs?

**Comment by MyraBaba** [comment]
@kayhayen 

succesfully compiled binaru gives opencv and numpy related errors:

ImportError: libopenblasp-r0-09e95953.3.13.so: cannot open shared object file: No such file or directory 
and some opencvlibs.

**Comment by kayhayen** [comment]
Don't use Debian system Python installation, but a virtualenv with PyPI packages, because Debian apparently is giving it all to make it hard to move it to other systems.

**Comment by kayhayen** [comment]
Part of 0.8 release that I just made.

**Comment by MyraBaba** [comment]
@kayhayen 
Thanks . Will feedback after tested

Best
