### ISSUE TITLE
[Help] Is it possible to compile together with files?

### ISSUE THREAD

**Issue by LanzTokisaki** [Nuitka/Nuitka#1487]
So I am new to nuitka and wanted to compile my code

Im just going to write a basic example that relates to my code

```
from PIL import Image

file = "test.png"
img = Image.open(file)
img.show()
```

Is it possible to compile the code together with "test.png"? I want it to be literally 1 file when compiled all together with the files needed.

**Comment by kayhayen** [comment]
There is onefile mode, where you can include data files. Refer to the user manual, also on how to use `sys.argv[0]` and `__file__` to locate them. That uses a temporary folder to run stuff. With Nuitka commercial, the files can be embedded directly. See https://nuitka.net/doc/commercial.html and https://nuitka.net/doc/commercial/protect-data-files.html for more information.
