### ISSUE TITLE
nuitka doesn't include python.runtime.dll (pythonnet/clr)

### ISSUE THREAD

**Issue by PMtr** [Nuitka/Nuitka#1489]
pyhon 39
nuitka 0.7.3 & 0.8rc7
pythonnet 2.5.2
Windows 10 v20h2
Compiler Mingw64

Hello,

command line used : `python -m nuitka myprog.py --onefile --enable-plugin=pyside6`

Something which has a resemblance with #"Nuitka doesn't work with pywebview" #412
due to use of clr module, there is a need of python.runtime.dll whihc is not found, error when launching the exe file:
 System.IO.FileNotFoundException: Impossible to load the file or assembly ```
'file:///C:\Users\E511794\AppData\Local\Temp\onefile_123656_132925112483670235\Python.Runtime.dll' or one of its dependancies. The specified file was not found.
at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at clrModule.PyInit_clr()

Is there a way to include this dll into final result to make it run?
I browse nuitka doc, I saw a dll-files plugin without finding an usage which match with my question.
I must admit that I'm not an experimented programmer and I can have miss something.

Thanks.
```

**Comment by kayhayen** [comment]
Without a reproducer, there is not a lot to do.

**Comment by azidennn** [comment]
I am experiencing this issue, too. To reproduce, create a file named test.py containing:

`import clr`

Then run `python -m nuitka test.py --standalone` (or `--onefile`). This results in the error initially described.

You can copy Python.Runtime.dll into the resulting standalone directory as a workaround. Or you can use --include-data-file for either mode. But this ideally would be included automatically if pythonnet is used in the target script.

**Comment by PMtr** [comment]
Hi,

I wonder if I didn't try the solutions you proposed without any success (put it in the directory or -include-data-file), to be sure I will try again.
Anyway great thanks for your contribution, help and reply.

Regards.
De : azidennn ***@***.***>
Envoyé : samedi 23 avril 2022 05:43
À : Nuitka/Nuitka ***@***.***>
Cc : Marchand, Pascal ***@***.***>; Author ***@***.***>
Objet : [External] Re: [Nuitka/Nuitka] nuitka doesn't include python.runtime.dll (pythonnet/clr) (Issue #1489)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

I am experiencing this issue, too. To reproduce, create a file named test.py containing:

import clr

Then run python -m nuitka test.py --standalone (or --onefile). This results in the error initially described.

You can copy Python.Runtime.dll into the resulting standalone directory as a workaround. Or you can use --include-data-file for either mode. But this ideally would be included automatically if pythonnet is used in the target script.

-

**Comment by kayhayen** [comment]
I still cannot install this with Python3.9 which the original report states though, but only 3.8 and yes, pywebview got that DLL dependency, but maybe that was short sighted, and it's actually another module that should get it attributed.

**Comment by kayhayen** [comment]
Indeed, the `pywebview` got this `clr` dependency added, for the wrong module name. Moving the code to outside the plugin will just make it work.

**Comment by kayhayen** [comment]
This is currently on the factory branch.

**Comment by kayhayen** [comment]
Part of the 0.8 release I just made.
