### ISSUE TITLE
PyCryptodome missing .pyd's

### ISSUE THREAD

**Issue by Nshout** [Nuitka/Nuitka#1494]
I am trying to create a module (.pyd) with Nuitka using: `py -m nuitka --module protect.py --include-package=Crypto`. As the module I made uses PyCryptodome (tested with PyCryptodomex as well) it fails to import the .pyd files that PyCryptodome needs. I think such a issue has been reported before, but I am unsure since it wasn't about modules.

OS: Windows 11 x64
Python: 3.10.3 x64
Nuitka: 0.7.6

**Comment by Aikkko** [comment]
+++
I have problems with it too

**Comment by kayhayen** [comment]
I would nee a minimal reproducer though.

**Comment by C-Peck** [comment]
Decrypt.py
```
from Cryptodome.Cipher import AES

def get_text():
    key = b'Q\xd5\xe0\xae\xb5a\xc7\xee\x91{\xeb\x1fB2l%\xba\xd26\x89\xf54\xde3\x18x\x1aF\xde\x8f\xe7\xc3'
    encrypted_data = b'f\x19CP5J6N>\x7f\xcb3\x93\x05!\xdav\x8b'
    iv = b'\x12\x17\xa0\xeb\xbdb\xe2\x1c\xb5\xf1\x14\x17\xb5um\xe5'
    cipher = AES.new(key, AES.MODE_CFB,iv = iv)
    return cipher.decrypt(encrypted_data)
```
Compiled with `python -m nuitka --module decrypt.py  --include-package=Cryptodome`

main.py with decrypt.cp310-win_amd64.pyd in the same directory
```
from decrypt import get_text

if __name__ == "__main__":
    print(get_text().decode())
```

**Comment by kayhayen** [comment]
Ah my bad, I didn't notice none of you are using standalone mode. You are supposed to create wheels from your modules that contain all your dependencies, other extension modules are not included into the created extension module, but you can put them into a wheel if you want, however it would be a bad idea.

You either want to do standalone mode, or create wheel of your software, then you can use Nuitka to compile during the wheel creation the Python code.
