### ISSUE TITLE
Standalone mode debug info

### ISSUE THREAD

**Issue by alchem1ster** [Nuitka/Nuitka#1496]
```0.7.6
Commercial: None
Python: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
Flavor: Unknown
Executable: O:\Python38\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
MinGW64: gcc-11.2.0-mingw-w64-9.0.0-r5
```
Some libs (dbm, email, http) seems to adds debug info to the output binary PE file
Compiled via both `nuitka --mingw64 --standalone .\main.py` and `nuitka --mingw64 --onefile .\main.py`, but onefile PE version does not contain such information.
<details>
<summary>findstr "O:\Python38" main.exe</summary>

O:\Python38\lib\dbm\__init__.pyr
O:\Python38\lib\dbm\ndbm.py
O:\Python38\lib\email\__init__.pyr
O:\Python38\lib\email\_encoded_words.py
O:\Python38\lib\email\_header_value_parser.py
O:\Python38\lib\email\_parseaddr.pyr
O:\Python38\lib\email\_policybase.py
O:\Python38\lib\email\base64mime.pyr
O:\Python38\lib\email\charset.pyr
O:\Python38\lib\email\contentmanager.py
O:\Python38\lib\email\encoders.py
O:\Python38\lib\email\errors.pyr
O:\Python38\lib\email\feedparser.py
O:\Python38\lib\email\generator.py
O:\Python38\lib\email\header.py
O:\Python38\lib\email\headerregistry.py
O:\Python38\lib\email\iterators.pyr
O:\Python38\lib\email\message.py
O:\Python38\lib\email\parser.py
O:\Python38\lib\email\policy.pyr
O:\Python38\lib\email\quoprimime.py
O:\Python38\lib\email\utils.py
O:\Python38\lib\http\__init__.pyr
O:\Python38\lib\http\client.py

</details>

**Comment by kayhayen** [comment]
This might happen if they come from the byte code demotion cache, in which case the original filename is used, that is a regression of 0.7 then I fear.

**Comment by kayhayen** [comment]
Recompiling the byte code is probably a stupid idea, for now I will change it to use the same kind of filename, the original one is even wrong.

**Comment by kayhayen** [comment]
Caching is not so much the issue, happens even if disabled, demoted byte code does use the original filename in its `__file__` value, which is not only not compatible, but also leaking information. I will shortly put up something on factory branch that does this better, preparing a hotfix release for this. Might be an old issue though.

**Comment by kayhayen** [comment]
Release as 0.7.7
