### ISSUE TITLE
AssertionError: assert encoding is not None

### ISSUE THREAD

**Issue by ygbingo** [Nuitka/Nuitka#1499]
### Nuitka version, full Python version, flavor, OS, etc. as output by this
  command (it does more than you think, and we are adding more all the time):

  > python -m nuitka --version
```
0.7.6
Commercial: None
Python: 3.8.12 (default, Oct 12 2021, 13:49:34)
Flavor: Anaconda Python
Executable: /root/miniconda3/envs/py38/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 20.04.1
```

### How did you install Nuitka and Python

  I used ```pip install nuitka``` installed Nuitka.

- I'm sure I install nuitka succeed
- I use nuitka on Windows10 by wsl.

### What error did I get?
I had a sanic server codes. And I used this command to generate *.bin file: ```python3 -m nuitka --follow-imports --plugin-enable=pylint-warnings -o ./server.bin --remove-output --show-scons --static-libpython=no cx_api_server/server.py```

Then, I got this error:
```
...
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pkg_resources._vendor.packaging' added 'pkg_resources._vendor.packaging.version,pkg_resources._vendor.packaging.specifiers,pkg_resources._vendor.packaging.requirements'.
PASS 1:  97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉    | 579/597, sanic.response
...
...
...
Problem with statement at /root/miniconda3/envs/py38/lib/python3.8/site-packages/sanic/response.py:37:
-> class BaseHTTPResponse:
Nuitka:INFO: Interrupted while working on '<Node 'COMPILED_PYTHON_MODULE' with {'filename': '/root/miniconda3/envs/py38/lib/python3.8/site-packages/sanic/response.py', 'module_name': <ModuleName sanic.response>, 'code_flags': ''}>'.
PASS 1:  97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉    | 579/597, sanic.response
...
...
 File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/nuitka/specs/BuiltinParameterSpecs.py", line 679, in extractBuiltinArgs
    result = builtin_class(*args_list, source_ref=node.getSourceReference())
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/nuitka/nodes/AttributeNodesGenerated.py", line 604, in wrapExpressionStrOperationEncode
    return ExpressionStrOperationEncode3(
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/nuitka/nodes/StrNodes.py", line 1404, in __init__
    assert encoding is not None
AssertionError

**Comment by ygbingo** [comment]
### Versions info:
- Python 3.8.12
- Sanic 21.6.2; Routing 0.7.0
- Nuitka 0.7.6
  - Commercial: None
  - Python: 3.8.12 (default, Oct 12 2021, 13:49:34)
  - Flavor: Anaconda Python
  - Executable: /root/miniconda3/envs/py38/bin/python
  - OS: Linux
  - Arch: x86_64
  - Distribution: Ubuntu (based on Debian) 20.04.1

**Comment by gdementen** [comment]
Disclaimer: I am not the author of Nuitka, but if I was, I do not think I could do anything with your bug report.

Please provide the shortest possible code which works under cpython but exhibits the error you see when compiled with Nuitka.

>  Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)
> 
>   That demonstrates the issue i.e a small piece of code which reproduces
>   the issue and can be run with out any other (or as few as possible)
>   external dependencies. Issues without this may get rejected without much
>   consideration.

**Comment by kayhayen** [comment]
From the crashing package, I managed to extra a reproducer like this:

```
def f():
    return "{value}".encode(errors="surrogateescape")
```

Basically what happens is that `str.encode` has two default values and accepts keyword arguments. That is unique for `str` at least, not sure if `dict` methods allow this. So the `utf-8` default value for encoding is missing on at least Python3. Not sure how I want to have these cases, should it silently add it, or require dedicated nodes for them, which in term of course, could well be only wrappers or derived classes.

**Comment by kayhayen** [comment]
The Python2 form for `unicode` ought to share the issue.

**Comment by kayhayen** [comment]
We do not yet generate nodes for the Python2 type though, I pushed a fix to factory.

**Comment by kayhayen** [comment]
https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
This is now on develop and will be in 0.8 release. I actually found another similar bug for `str.split` and `str.rsplit` when enhancing the test to cover terminal keyword arguments.

**Comment by kayhayen** [comment]
Part of 0.8 release that I just made.

**Comment by kayhayen** [comment]
Part of 0.8 release that I just made.
