### ISSUE TITLE
Question: Is it possible to use setup.py with nuitka to compile standalone exe or onefile exe?

### ISSUE THREAD

**Issue by herokrat** [Nuitka/Nuitka#1500]
* Nuitka version, full Python version, flavor, OS, etc. as output by this
  command (it does more than you think, and we are adding more all the time):
0.7.6
Commercial: None
Python: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\herma\PycharmProjects\pythonProject1\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

* I install Nuitka with pip and virtualenv.

* The specific PyPI names and versions
Nuitka==0.7.6
zstandard==0.17.0

Question:  My project is simple Tkinter GUI and i want to use setup.py to build it for Windows. But i can`t do that.

My project structure:
-src (folder)
--smaple (folder)
--- __init__.py (empty)
--- __main__.py (entry point of program)
--- clock.py (class that used in main)

Example №1:

My setup.py:

setup(
    name='AML',
    package_dir={"": "src"},
    packages=find_packages(where="src"),
    python_requires=">=3.10, <4",
    platforms='Windows',
    install_requires=[],
    entry_points={
        "console_scripts": [
            "sample=sample:main",
        ],
    },

    command_options={'nuitka': {'--standalone': ('setup.py', None), ('--enable-plugin': ('setup.py', 'tk-inter')}} 
)

I run python -m setup.py bdist_nuitka and got these outputs.

Nuitka-Options:INFO: Used command line options: --module --enable-plugin=pylint-warnings --enable-plugin=tk-inter --output-dir=C:\Users\herma\PycharmProjects\pythonProject1\build\lib --nofollow-import-to=*.tests --remove-output --incl
ude-package=sample --standalone C:\Users\herma\PycharmProjects\pythonProject1\build\lib\sample

 "FATAL: Error, conflicting options, cannot make standalone module, only executable."

And so i don`t get how to do it right.

Example №2
I removed option --standalone from setup.py and in the end a got.

Nuitka-Options:INFO: Used command line options: --module --enable-plugin=pylint-warnings --enable-plugin=tk-inter --output-dir=C:\Users\herma\PycharmProjects\pythonProject1\build\lib --nofollow-import-to=*.tests --remove-output --incl
ude-package=sample C:\Users\herma\PycharmProjects\pythonProject1\build\lib\sample
Nuitka:INFO: Starting Python compilation with Nuitka '0.7.6' on Python '3.10' commercial None.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl 14.3).
Nuitka-Scons:INFO: Backend linking program (no progress information available).
Nuitka-Scons:INFO: Compiled 11 C files using clcache with 8 cache hits and 3 cache misses.
Nuitka:INFO: Removing build directory 'C:\\Users\\herma\\PycharmProjects\\pythonProject1\\build\\lib\\sample.build'.
Nuitka:INFO: Successfully created 'C:\\Users\\herma\\PycharmProjects\\pythonProject1\\build\\lib\\sample.cp310-win_amd64.pyd'.
Nuitka-Wheel:INFO: Finished compilation of 'sample'.
running install
running install_lib
creating build\bdist.win-amd64
creating build\bdist.win-amd64\wheel
creating build\bdist.win-amd64\wheel\sample
running install_egg_info
running egg_info
creating src\AML.egg-info
writing manifest file 'src\AML.egg-info\SOURCES.txt'
writing manifest file 'src\AML.egg-info\SOURCES.txt'
Copying src\AML.egg-info to build\bdist.win-amd64\wheel\.\AML-0.0.0.1-py3.10.egg-info
C:\Users\herma\PycharmProjects\pythonProject1\venv\lib\site-packages\wheel\bdist_wheel.py:80: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
  if get_flag('Py_DEBUG',
C:\Users\herma\PycharmProjects\pythonProject1\venv\Scripts\python.exe: Error while finding module specification for 'setup.py' (ModuleNotFoundError: __path__ attribute not found on 'setup' while trying to find
 'setup.py'). Try using 'setup' instead of 'setup.py' as the module name.

**Comment by kayhayen** [comment]
Wheels are designed to live in a Python installation, standalone makes no sense there. I am considering to use `distutils` configuration to build a wheel, to be used to not build a wheel, but right now, that's not there yet. Obviously you would e.g. have a working wheel binary distribution setup, and might want to go without.

The error, you got, may come from this bit:

``` ('--enable-plugin': ('setup.py', 'tk-inter')}}  ```

Nuitka wants to load `setup.py` as a plugin

Now the user manual uses this:

```            '--enable-plugin': ("setup.py", "pyside2"),

I wonder if that name we put there, is being imported by `distutils` or something there. Nuitka compilation worked fine, and then something finds out that "setup.py" is not importable, why? I was under the impression for that name to not matter, and maybe that is wrong.

**Comment by kayhayen** [comment]
This has been dealt with in other issues.
