### ISSUE TITLE
Nuitka + Pyarmor Not Compiling

### ISSUE THREAD

**Issue by f1nzo** [Nuitka/Nuitka#1503]
I'm a new coder so I'm sorry if this is a dumb question/problem but I looked everywhere and have not been able to find a solution.

I have obfuscated a .py file with this command:
`pyarmor obfuscate --output output_folder __main__.py`
I successfully get a folder called output_folder with the content being:

- __main__.py
- pytransform
- pytransform > __init__.py
- pytransform > _pytransform.dll

I now run the following nuitka command to pack it all into one exe file:
`py -m nuitka --onefile --mingw64 --standalone --enable-plugin=numpy --output-dir=output_dir testfile`

**Comment by ralienpp** [comment]
And what's the error message? In what way does it not work? Give us the details, otherwise we cannot help.

**Comment by f1nzo** [comment]
When I run the .exe file I get: 
`Traceback (most recent call last):
  File "C:\Users\finwi\AppData\Local\Temp\ON5739~1\__main__.py", line 1, in <module>
ModuleNotFoundError: No module named 'pytransform'`
I think this means it is not packaging the pytransform folder in the executable but idk how to fix it :(.

**Comment by ralienpp** [comment]
It is possible that the way the obfuscator works makes it non-obvious that the file is imported, so Nuitka isn't aware of this dependency. Try to explicitly add `import pytransform` to the obfuscated file, to clearly signalize Nuitka that this library is needed.

**Comment by kayhayen** [comment]
Of course, pyarmor is not recommended to be used with Nuitka, but Nuitka commercial instead. https://nuitka.net/doc/commercial.html#protection-vs-reverse-engineering

Doing said import, is probably enough to make it sort of work, but honestly very pointless. The byte code protection may be all good and dandy, but it's far better to not have bytecode in the first place and use Nuitka commercial data protection features.

If you are on Windows, watch out for Nuitka Deluxe which integrates VM technology and should become public as a product later this or next month.

**Comment by thecowmilk** [comment]
pyarmor is not recommended to be compiled with any compiler. They have their own which is a `pyinstaller` mix. I have opened an issue at their end they still haven't give a solution.
