### ISSUE TITLE
`pygame`: Nuitka didn't include `libvorbisfile-3.dll` while packing

### ISSUE THREAD

**Issue by wszqkzqk** [Nuitka/Nuitka#1510]
`nuitka 0.7.7` installed by `pip`

```shell
0.7.7
Commercial: None
Python: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\17265\AppData\Local\Programs\Python\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```
To play an `.ogg` in `pygame.mixer.music`, the one-file `.exe` need to include `libvorbisfile-3.dll`, but nuitka didn't pack it.

**Comment by kayhayen** [comment]
Can you provide a small example of it maybe, this would be easy to add, but I'd like to see it for myself.

**Comment by wszqkzqk** [comment]
> Can you provide a small example of it maybe, this would be easy to add, but I'd like to see it for myself.

OK, but this example's README is in Chinese.
[pypvz](https://github.com/wszqkzqk/pypvz)

**Comment by wszqkzqk** [comment]
Maybe it's difficult for Nuitka to find the correct codec format of media files and add the related `.dll` files?

**Comment by kayhayen** [comment]
I want to one day have plugins detect it from the data files. So if you were having a `.ogg` data file would trigger DLL dependencies as a condition, and not if you were not. Many GUI libraries share similar issues. It's an optimization yes, but with the yaml file and recent plugin changes (they get to see actually included data files) it's now easy, maybe I take a stab at it, but allow for a bit of time here.

**Comment by kayhayen** [comment]
The whole project is not acceptable as an example, unless I have known to work easy instructions on how to compile, esp. if it's a foreign language to me.

**Comment by kayhayen** [comment]
Closing for lack of feedback.
