### ISSUE TITLE
How to run codesign for an app compiled by Nuitka on macOS?

### ISSUE THREAD

**Issue by kbrowser** [Nuitka/Nuitka#1511]
> Nuitka version 0.7.7 (Commercial: None), Python version 3.10, macOS Monterey on Apple M1

This is the first time I ask a question about Nuitka. I hope it is exact to post it in the issues section.

Nuitka is a great compiler, so I can relase my app's versions for Windows, Linux and macOS. It works like a charm.

However, on macOS, because of its Gatekeeper mechanism, I have to run codesign after Nuitka compiles an .app (compiled with --standalone --macos-create-app-bundle), but codesign never signed the app successfully.

If I just run "codesign -s 'the name of Developer ID Application cert' a.app", the error will say the app is already signed, but running "codesign -v" will fail and say missing a cert.

If I run "codesign -f --deep -s 'the name of Developer ID Application cert' a.app", after waiting a while, the error will be "bundle format unrecognized, invalid, or unsuitable". 

The UI module that my app is tkinter, and the only third-party module that my app uses is Pillow.

It is not a bug of Nuitka. May I ask anyone who has experience for using Nuitka on macOS, how can you successfully run codesign for signing an app compiled by Nuitka? I feel grateful if you can give me advice.

Thanks for reading!

**Comment by kayhayen** [comment]
Nuitka does the `codesign` itself, and on develop it added the ability to specify the certificate to use, and even entitlements, before it was only ad-hoc signature.

I agree, shouldn't be a bug of Nuitka. If you encounter any issues with Nuitka failing to sign, however there are sometimes workarounds needed. With PySide2 e.g. it automatically makes you use `--onefile` as that cannot be signed. Also something added for 0.8

**Comment by kbrowser** [comment]
Thanks for your reply! I am very glad to hear the future version will add the feature of specifying a certificate on macOS. If the option is just like "--macos-certificate=", it will be perfect.

**Comment by kayhayen** [comment]
You can checkout the develop packages no problem and see for yourself.

**Comment by kbrowser** [comment]
Thanks a lot! You mean the development version of Nuitka? Generally I install Nuitka through pip, so I don't know how to install the development version. I may wait for the future release.

**Comment by kayhayen** [comment]
One day I will figure out, how Nuitka-develop can be uploaded to PyPI as well without conflicting with Nuitka, but I didn't spend the time yet, how to identify develop versions to it.

**Comment by logileifs** [comment]
> One day I will figure out, how Nuitka-develop can be uploaded to PyPI as well without conflicting with Nuitka, but I didn't spend the time yet, how to identify develop versions to it.

Just append the version with `.dev0` and upload to pypi, it will not be installed unless you specify nuitka==x.y.z.dev0. Further explanation: https://peps.python.org/pep-0440/#developmental-releases

**Comment by kayhayen** [comment]
@logileifs thanks, I will try to add it once i find the time.

**Comment by kbrowser** [comment]
Today I tried Nuitka 0.8rc9. It can work without "--enable-plugin=tk-inter", but will not include tkinter's folders. With "--enable-plugin=tk-inter", the codesign step will terminate with an error "...bundle format unrecognized, invalid, or unsuitable\nIn subcomponent: ..../a.app/Contents/MacOS/tcl/opt0.4".

After searching, I find the page "https://github.com/pyinstaller/pyinstaller/wiki/Recipe-OSX-Code-Signing-Qt" gives some important information, "The root cause if that folders containing a dot in their name is not allowed in the Contents/MacOS folder."

"opt0.4" is a folder, so maybe this is why codesign is not successful with "--enable-plugin=tk-inter". Is it possible to fix it by Nuitka?

Thanks!

**Comment by kayhayen** [comment]
Yes, you need to add `--onefile`. For `PySide2` it is also required. What I take from that is that maybe it would make sense to discover this automatically.

I guess something similar to this for tk might make sense too:

```
# For PySide2, we need to use even --onefile when application bundle
PySide2:
  standalone_macos_bundle_mode: onefile
  disable_console: recommend
```

**Comment by kayhayen** [comment]
The config for the TkInter variants for Python2/Python3 is on factory branch now.

**Comment by kbrowser** [comment]
Hello!

Generally I use the options "--standalone --macos-disable-console --enable-plugin=tk-inter --macos-create-app-bundle --macos-app-icon=logo.icns" on macOS.

Just now I tested the options adding "--onefile". The app can be signed, but there are some problems: 1. The app lacks an icon though logo.icns has been set. 2. Every time the app starts very very slowly. 3. Some of its features related to permissions can't work now but there is no notice window.

I also tested the options with "--onefile" but without "--macos-create-app-bundle". It created a .bin file, but the file can't run.

I believe the options without "--onefile" should be perfect if the problem related to tcl/opt0.4 can be fixed.

**Comment by kayhayen** [comment]
Are you saying the entitlements given to the binary to not get granted to the forked off binary? That's pretty bad.

How many "." folders are there, any chance you can come up with a patch to TCL such that it doesn't use that name, but say `opt0_4`, because Nuitka could apply that then.

**Comment by kayhayen** [comment]
Also, is there a way to keep entitlements when forking a binary on macOS?

**Comment by kbrowser** [comment]
I think it is the problem of entitlements.

After compiling without the option "--onefile",  when I click the .app file (it has the logo I set), its interface will appear instantly, and a notice window will ask for entitlements to read a default folder.

After compling with the option "--onefile", when I click the .app file (its icon is blank whatever I set an icon), its blank icon will jump for a long time, and later its interface appears. There is no notice window for asking entitlements, but it can't finish reading the default folder.

By the way, the option "--onefile" also has some problems on other systems. On Linux, sometimes the file can't run, and there is an error which says it can't find AppImage.

Sorry, I don't know how to make a patch to TCL, and I can't find a way to keep entitlements for a forked off binary. Since a folder containing a dot in its name is not allowed in the Contents/MacOS folder, perhaps Nuitka can recognize if a path is a folder, and then rename the "." of its name to "_", and replaces the path in compiled code. Even there are more folders including ".", the problem can be solved.

**Comment by kayhayen** [comment]
The icon being absent is something I never noticed, but the Qt programs I used, probably use Qt to set the icon at run time, but if that is true, it's even uglier, but it kind of makes sense.

As far as filenames go, of course can be done, but not sure what the impact on TCL will be. I am about to add options to inhibit data files, then we can use it and see if it's a needed file anyway. You can test that of course yourself by renaming it in your Python installation now.

**Comment by kayhayen** [comment]
I think it downloads `AppImage` when it needs that on Linux. You can use `--onefile-tempdir` on Linux to use the same code as on macOS. Once the caching, i.e. the tempdir is possible to be a static one that is reused, I will drop AppImage.

**Comment by kayhayen** [comment]
The config suggest was added for develop and will be in 0.8 release as well.

**Comment by kbrowser** [comment]
There are two folders "http1.0" and "opt0.4" which should be renamed in the folder "tcl" of an app.

In the folder "/Library/Frameworks/Python.framework/Versions/3.10/lib/tcl8.6/" on macOS, I renamed "http1.0" to "http1_0" and renamed "opt0.4" to "opt0_4". They are copied to the folder of an app during Nuitka compiles the app. Now without "--onefile" but with "--enable-plugin=tk-inter --macos-create-app-bundle" the app can be successfully signed with a developer cert.

But the notarization of the app failed. The error shows "The executable does not have the hardened runtime enabled." Can Nuitka enable the hardened runtime during compiling the app?

**Comment by kbrowser** [comment]
I found a perfect solution to solve all of the issues.

Now I use codesign to sign my app with hardened runtime (add "--options runtime").

And about the folder which includes a dot, don't directly sign the folder, but enter the folder and sign the files of the folder. It is just like running "cd" firstly and "codesign" secondly.

**Comment by kayhayen** [comment]
For individual signing, you need to figure out the dependencies, which is why Nuitka uses `--deep`. I am not sure about data files for apps, if they have an issue if they have a dot in the folder name.

What you say is confusing me. With `--onefile` the signing never sees the dot files, so you don't sign them, they live in a temp folder. And the `--options runtime` is not saying anything about entitlements. Are you saying, that will allow a `--onefile --macsos-create-app-bundle` application to be signed and execute the child process with entitlements inherited?

It seems from the manage like an omission to not have it on, as it gives protection that people might want.

**Comment by kbrowser** [comment]
Hardened runtime is needed for the notarization of an app for macOS. So I use the codesign command with "--options runtime" for resigning the app. The entire codesign command I use is:

codesign --deep --options runtime --timestamp --force --verify --verbose --sign "Developer ID Application:..." a.app

It seems that the resigning command will make the app lose entitlements ("--macos-app-protected-resource=..." set by Nuitka).

I don't add "--onefile" when using Nuitka, because now I use PySide6 and it needs dynamic libraries.

I have another question. If you don't add "--macos-app-protected-resource=..." when using Nuitka to compile an app that needs to access "~/Pictures" folder, will the first run of your app cause a dialog that shows a message "quit unexpectedly" but the app actually works normally and does not crash?

**Comment by kayhayen** [comment]
I added `--options runtime` to the signing that Nuitka does. You should look at `nuitka.utils.Signing` and either copy what it does, or add to it, you are missing an option for entitlements to work.

WIth PySide6 the `--onefile` alone won't give you a GUI application, so bundle is needed, and `--onefile` would be wasteful, not sure if it's not even working in that mode, but it would be a new topic, to disallow it.

Your last question I don't get. 

Get factory version from here, it has the fix for runtime: https://nuitka.net/doc/factory.html

**Comment by kbrowser** [comment]
I have tried the factory version, and the notarization was successful after signing by Nuitka. Thanks!

By the way, where can I find the page about nuitka.utils.Signing?

**Comment by kayhayen** [comment]
It's a module of nuitka code.

**Comment by kayhayen** [comment]
This is not working for Github Actions though:

```
+dyld: Library not loaded: @executable_path/libpython3.8.dylib
+  Referenced from: /Users/runner/work/Nuitka/Nuitka/tests/standalone/CtypesUsing.dist/CtypesUsing
+  Reason: no suitable image found.  Did find:
+	/Users/runner/work/Nuitka/Nuitka/tests/standalone/CtypesUsing.dist/libpython3.8.dylib: code signature in (/Users/runner/work/Nuitka/Nuitka/tests/standalone/CtypesUsing.dist/libpython3.8.dylib) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)
+	/Users/runner/work/Nuitka/Nuitka/tests/standalone/CtypesUsing.dist/libpython3.8.dylib: code signature in (/Users/runner/work/Nuitka/Nuitka/tests/standalone/CtypesUsing.dist/libpython3.8.dylib) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)
+	/Users/runner/work/Nuitka/Nuitka/tests/standalone/CtypesUsing.dist/libpython3.8.dylib: stat() failed with errno=1
+	file system relative paths not allowed in hardened programs
```

Not sure what it tries to say with the last line. This is probably Homebrew Python. What am I doing in an issue, where you didn't even bother to post `--version` output of Nuitka, I don't know, so I cannot tell what you are using.

**Comment by kayhayen** [comment]
It doesn't work on CPython Official for me with neither 2.7 nor 3.8 and I assume nothing will. I am guessing, that it may be the lack of identity, but adding one and setting signed app name, etc. didn't change it one bit.

**Comment by kayhayen** [comment]
Ok, reading manpage of `codesign`, it says something that means this, that because my certificate used for signing is not from Apple, it will not work to load the files. It works for you probably because of your certificate, so this is probably something that will have to be a different option, unless I learn how to detect a certificate is from Apple. For now I am disabling it again, as it breaks CI.

**Comment by kbrowser** [comment]
I always use the latest version (now it is 3.10.4) of Python which is downloaded from its official site. It is a big pain to release an app for macOS, because there are too many restrictions and problems.

On macOS, every day the first compiling of Nuitka will fail, and the second compiling can be successful. But since the second compiling can be successful, I think that it might be the bug of macOS or Xcode tool used by Nuitka.

My app uses ImageMagick. It is a command line program. It is not easy to install ImageMagick on macOS, except a user is willing to install Homebrew or MacPorts. I can't require a user to install a third-party programe, especially Homebrew or MacPorts will install a lot of dependencies which are not used by ImageMagick. And many macOS users are not familiar with a console. I then made a small package of ImageMagick through MacPorts, and signed all files using my Developer ID certificate. This is the experience I mentioned about signing a command-line program.

By default, Apple require all programs to use certificates (Developer ID Application for .app, and Developer ID Installer for .pkg) issued by Apple instead of third-party companies, and all apps must add hardened runtime and be notarized. I am familiar with command line, but I can't require a user to disable the security feature of macOS for installing a third-party app. Therefore, I follow all restrictions of Apple.

**Comment by kayhayen** [comment]
You may have out of memory issues, check low memory in user manual, a killed job might have more luck once it enters the cache.

My beef is that I will need to become an Apple Developer and pay their fees, just to test this. I will want to wait until one of those with an NDA or no need for me, and a certificate will let me do this for them. Right now, https://nuitka.net/doc/commercial.html doesn't really cover or promise signing yet, but obviously it's getting there. I am just not happy with maintaining code that I cannot test myself right now.

But obviously, most people do this themselves, and it's not important right now. Once the 0.8 settles, I might ask for a customer to let me experiment with it, such that it will be acceptable to them.

**Comment by kayhayen** [comment]
So, this is about this part of the code, that I had to comment out:

```
        # TODO: This appears to be useful, but apparently doesn't work for all flavors of Python.
        # "--options=runtime",
```

I think we might be able to do it with CPython, and maybe Anaconda only, but testing will be needed. Do you have a suggestion for the option name to use on this. For now, I guess, I am making it experimental, such that `--experimental=macos-sign-runtime` will enable it and close this convoluted issue for now. Maybe I can ask for helo with that in place.

**Comment by kayhayen** [comment]
This is now on develop branch and will be in 1.1 release soon.

**Comment by kayhayen** [comment]
This is part of the stable release 1.1 that I just made.

**Comment by kbrowser** [comment]
> So, this is about this part of the code, that I had to comment out:
> 
> ```
>         # TODO: This appears to be useful, but apparently doesn't work for all flavors of Python.
>         # "--options=runtime",
> ```
> 
> I think we might be able to do it with CPython, and maybe Anaconda only, but testing will be needed. Do you have a suggestion for the option name to use on this. For now, I guess, I am making it experimental, such that `--experimental=macos-sign-runtime` will enable it and close this convoluted issue for now. Maybe I can ask for helo with that in place.

Sorry for very late reply! I have not been here for a very long time. Sorry that I have abandoned the development of my app for macOS. Thanks for your great efforts! Happy New Year!
