### ISSUE TITLE
 Module 'pywintypes' isn't in frozen sys.path

### ISSUE THREAD

**Issue by mohammed-workfellow** [Nuitka/Nuitka#1514]
* Nuitka version, full Python version, flavor, OS, etc. as output by this
  command (it does more than you think, and we are adding more all the time):

  > python -m nuitka --version
```
 3.10.4  poetry run python -m nuitka --version
0.7.7
Commercial: None
Python: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]   
Flavor: Unknown
Executable: C:\task_miner\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

* How did you install Nuitka and Python

Python is from python.org downloads. Nuitka running inside a .venv managed by poetry.

* The specific PyPI names and versions

  `pywin32` , `uiautomation` .

  > python -m pip freeze

```[tool.poetry.dependencies]
python = "3.10"
comtypes-fork = "^1.1.10"
keyboard = "0.13.5"
psutil = "5.7.2"
requests = "2.26.0"
uiautomation = "2.0.16"
pydantic = "^1.9.0"
mouse = "^0.7.1"
rule-engine = "^3.3.1"
eliot = "^1.14.0"
pywin32 = "^303"
xmltodict = "^0.12.0"
falcon = "^3.1.0"
Jinja2 = "^3.1.1"
Nuitka = "^0.7.7"
build = "^0.7.0"


[tool.poetry.dev-dependencies]
ipdb = "^0.13.9"
yapf = "^0.32.0"
freezegun = "^1.1.0"
pytest = "6.2.5"
pyperclip = "1.8.2"
pykafka = "^2.8.0"
eliot-tree = "^21.0.0"
poetry2setup = "^1.0.0"
build = "^0.7.0"
```

In the same activated environment, test sample seems to work while actual application code doesn't

```
import psutil
import pywintypes
import uiautomation
import win32gui
import win32process


def main_process_name():
    active_window_handle = win32gui.GetForegroundWindow()
    active_window_pid = win32process.GetWindowThreadProcessId(active_window_handle)[-1]
    if active_window_pid < 0:
        return None
    try:
        return psutil.Process(active_window_pid).name()
    except psutil.NoSuchProcess:
        return None


def get_window_geometry():
    try:
        active_window_handle = win32gui.GetForegroundWindow()
        left_x, top_y, right_x, bottom_y = win32gui.GetWindowRect(active_window_handle)
        window_width, window_height = right_x - left_x, bottom_y - top_y
        return left_x, top_y, window_width, window_height
    except pywintypes.error:
        # Default to zero-size window at origin
        return 0, 0, 0, 0


def get_url_chromium():
    with uiautomation.UIAutomationInitializerInThread():
        control = uiautomation.GetFocusedControl()
        control_list = []
        while control:
            control_list.insert(0, control)
            control = control.GetParentControl()
            
        control = control_list[0 if len(control_list) == 1 else 1]
            
        address_control = uiautomation.FindControl(control, lambda c, d: 
                                                    isinstance(c, uiautomation.EditControl))
        if address_control:

            return address_control.GetValuePattern().Value


if __name__== '__main__':
    print(main_process_name())
    print(get_window_geometry())
    print(get_url_chromium())
```

In the actual application with same imports, compiled with Nuitka:

```
import uiautomation
  File "C:\private_path\.venv\lib\site-packages\win32\lib\pywintypes.py", line 129, in <module pywintypes>
    __import_pywin32_system_module__("pywintypes", globals())
  File "C:\private_path\.venv\lib\site-packages\win32\lib\pywintypes.py", line 44, in __import_pywin32_system_module__
    raise ImportError(
ImportError: Module 'pywintypes' isn't in frozen sys.path ['C:\\private_path', 'c:\\users\\MOHAMM~1\\appdata\\local\\programs\\python\\PYTHON~1\\python310.zip', 'C:\\Users\\MohammedSalman\\AppData\\Local\\Programs\\Python\\Python310\\DLLs', 'C:\\Users\\MohammedSalman\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\private_path\\.venv', 'C:\\private_path\\.venv\\lib\\site-packages', 'C:\\private_path\\.venv\\lib\\site-packages\\win32', 'C:\\private_path\\.venv\\lib\\site-packages\\win32\\lib', 'C:\\private_path\\.venv\\lib\\site-packages\\Pythonwin']
```

* Provide in your issue the Nuitka options used

```poetry python -m nuitka .\main.py --follow-imports```

I also went through https://github.com/Nuitka/Nuitka/issues/296 . I tried the user plugin as well as the script provided by https://github.com/JorjMcKie with some retrofitting. The DLLs seem to be copied fine, still not found when executing.

Also from other issues, I am able to build a wheel and execute that in a new environment just fine. This means:

1. Nuitka is able to package pywintypes: See my running example code above.
2. My application code runs as wheel: Both compiled with Poetry and with setup tools.
3. My application doesn't work when compiled with `nuitka` due to ImportError, despite (1) and (2).

**Comment by mohammed-workfellow** [comment]
Also from other issues, I am able to build a wheel and execute that in a new environment just fine. This means:
1. Nuitka is able to package pywintypes: See my running example code above.
2. My application code runs as wheel: Both compiled with Poetry and with setup tools.
3. My application doesn't work when compiled due to ImportError, despite (1) and (2).

**Comment by kayhayen** [comment]
It seems you are not using standalone mode, is that on purpose?

**Comment by mohammed-workfellow** [comment]
@kayhayen I tried with `poetry run python -m nuitka .\private_path\main.py --follow-imports --standalone` . When running the compiled file, a new error is showing:
```
 File "pydantic\dataclasses.py", line 3, in init pydantic.dataclasses
  File "pydantic\class_validators.py", line 8, in init pydantic.class_validators
  File "pydantic\errors.py", line 5, in init pydantic.errors
  File "pydantic\typing.py", line 25, in init pydantic.typing
ModuleNotFoundError: No module named 'typing_extensions'
```

I found an issue ticket in Pydantic with similar problem,[ the commentator says that python 3.7 solved the issue.](https://github.com/samuelcolvin/pydantic/issues/3054#issuecomment-1013956847)

**Comment by kayhayen** [comment]
Make sure to try develop, maybe it's a fix that's already there.

**Comment by kayhayen** [comment]
I believe this is fixed with the current develop version of Nuitka.

**Comment by kayhayen** [comment]
Part of the 0.8 release I just made.
