### ISSUE TITLE
ModuleNotFoundError: No module named 'pylibcheck'

### ISSUE THREAD

**Issue by jdghreiongbergm** [Nuitka/Nuitka#1516]
I'm getting an error when trying to compile with these options:
--follow-imports
--standalone
--onefile
--windows-icon-from-ico=myico.png

The error is:
ModuleNotFoundError: No module named 'pylibcheck'

I have the package installed and I don't understand what to do.

Log:
C:\Users\BLURRED\Desktop\Testing\test\Obfuscated\other\bin>main
Traceback (most recent call last):
  File "C:\Users\BLURRED\AppData\Local\Temp\ON0F70~1\main.py", line 1352, in <module>
  File "<string>", line 1, in <module>
  File "C:\Users\BLURRED\Desktop\Testing\test\Obfuscated\other\bin\imports.py", line 359, in <module>
    exec(__import__("\x62\x61\x73\x65\x36\x34").b64decode(I.encode("\x75\x74\x66\x2d\x38")).decode("\x75\x74\x66\x2d\x38"))
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pylibcheck'

Versions:
0.7.6
Commercial: None
Python: 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Python\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

How I installed:
pip install nuitka

**Comment by ygbingo** [comment]
I'm not the assigner. But can you see 'pylibcheck' when you tap ```pip list```? Maybe in anothor conda env?

**Comment by kayhayen** [comment]
You have created a hidden dependency that Nuitka cannot see. You will need to make it include modules it cannot see imported through `--include-module` or `--include-package` options, otherwise, well, they won't be there in the standalone compilation.
