### ISSUE TITLE
Plugin option "--upx-binary" does not properly handle path to executable

### ISSUE THREAD

**Issue by Maxwell175** [Nuitka/Nuitka#1517]
If you want to post a problem/bug, to help us understand and resolve your issue
please check that you have provided at least the information below, and discard
up to here:

* Nuitka version, full Python version, flavor, OS, etc. as output by this
  command (it does more than you think, and we are adding more all the time):

  > python -m nuitka --version

* How did you install Nuitka and Python

  Did you use pip, anaconda, deb, rpm, from source, git clone, then install into
  a virtualenv or not, this is very important usually.

pip

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

  That demonstrates the issue i.e a small piece of code which reproduces
  the issue and can be run with out any other (or as few as possible)
  external dependencies. Issues without this may get rejected without much
  consideration.

When using the upx plugin and passing in the full path to the UPX binary, I get the error message `Nuitka-Plugins:WARNING: upx: No UPX binary found, please use '--upx-binary' option to specify it.`. When I instead put only the path up to, but not including the upx.exe, it works as expected.

test.py:
```
print("Hello World")
```

Fails:
`python.exe -m nuitka --standalone --plugin-enable=upx --upx-binary=C:\src\upx-3.96-win64\upx.exe test.py`

Works:
`python.exe -m nuitka --standalone --plugin-enable=upx --upx-binary=C:\src\upx-3.96-win64 test.py`

**Comment by kayhayen** [comment]
It's using `self.upx_binary = getExecutablePath("upx", upx_path)` and we could make the last one handle the case, where a file was provided rather than a directory as `extra_path`.

**Comment by kayhayen** [comment]
This is now on develop and will be in 0.8 release.

**Comment by kayhayen** [comment]
Part of 0.8 release that I just made.
