### ISSUE TITLE
use cv2  error , "cv2" binary extensions

### ISSUE THREAD

**Issue by txlcx** [Nuitka/Nuitka#1518]
get ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation. 

by use  python -m nuitka  --standalone --show-progress --nofollow-imports --plugin-enable=torch,numpy --follow-import-to=newCV2,numpy,cv2 --output-dir=out_nuitka test_image/train.py

**Comment by kayhayen** [comment]
No issue template no fun.
