### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ygbingo** [Nuitka/Nuitka#1519]
Before submitting an Issue, please review the [Issue Guidelines](https://github.com/kayhayen/Nuitka/blob/develop/CONTRIBUTING.md#submitting-an-issue).

* I nuitka my program successfully. But when I run my ```cxp_assist.bin``` file, the mistake is sign up like that:
```
  File "./cxp_assist.bin", line 1
    ELF
    ^
SyntaxError: invalid syntax

```

* Env version
  > python -m nuitka --version
```
0.7.6
Commercial: None
Python: 3.8.12 (default, Oct 12 2021, 13:49:34)
Flavor: Anaconda Python
Executable: /root/miniconda3/envs/py38/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 20.04.1
```

* How did you install Nuitka and Python
- I use ``` pip install nuitka==0.7.6 ``` to install nuitka package.

* Many times when you get an error from Nuitka, your setup may be special
 Actually, I have succeed in other programs. And just this program show that bug.

* So, do I need use some encode command when use nuitka?

**Comment by kayhayen** [comment]
No reproducer, no fun.
