### ISSUE TITLE
Question: How to use pyinstaller hooks in Nuitka?

### ISSUE THREAD

**Issue by rosatheagraham** [Nuitka/Nuitka#1523]
Some part of my programme required to add a hook to work properly. It exists as a examplehook.py file in my project directory.

As you know the pyinstaller has this --additional-hooks-dir= option to add hooks while compiling. 

It works like:

`pyinstaller --additional-hooks-dir=. myscript.py` (in this example the directory path is given as ".")

My question is: _Does Nuitka have any option to indicate hooks?_

**Comment by rosatheagraham** [comment]
Thanks. I can definitely add an example.
This repository below, has the basic skeleton of my programme.
[https://github.com/rosatheagraham/script](https://github.com/rosatheagraham/script)
It consists of 2 folders and 2 python files, listed below:
```
/static/
/templates/
hook-cefpython3.py
script.py
```
The script.py file is my main. Therefore, It could be tested by `python script.py` command.

The usual way I use to pack this programme with pyinstaller is, with the command below:
`pyinstaller --onefile --noconsole --add-data "templates;templates" --add-data "static;static" --additional-hooks-dir=. script.py`
As you can see while packing with pyinstaller, I add the option `--additional-hooks-dir` which points to main directory with `"=."` and  this option looks for some additional files in the directory, so called hooks or hook files, to add the programme in order to run at some point. In my case this file is : `hook-cefpython3.py`

That way it converts to a successfully running exe. Without adding  `hook-cefpython3.py` with `--additional-hooks-dir=.` option my exe does not start properly. My `script.py` needs it because of a function called **"cef"** , which is connected to some module. My `script.py` is very short. You can immediately see it, if you open it with an editor.

You may ask why I am trying to compile my programme with nuitka, as it already could be done with pyinstaller. Well, because in further coding, I have some conflict troubles with the pyinstaller created exe. Therefore I would like to use some other tool.

Thanks for reading.

**Comment by kayhayen** [comment]
I am not familiar with pyinstaller.

Nuitka has Yaml files, like e.g. `dll-files.yml`, `data-files.yml`, `implicit-dependencies.yml` and others, that you can contribute to. you might want to do that, or write a user plugin that achieves the effects you want there. The goal with Nuitka is however, to not have to write code for these things.

PyInstaller hooks are not working with Nuitka. At this time, these Yaml files of Nuitka are not well documented, I have to admit, this may change with volunteers.

The other approach is to report what happens wrong with Nuitka in a minimal example, in which case it will be easy to add the information usually, but that's nothing I can promise to happen in a timely fashion.

**Comment by kayhayen** [comment]
I consider this an answered question. Please make a PR with the changes or a new report detailing how the package in question doesn't work.

**Comment by rosatheagraham** [comment]
Hello, Of course I should have opened a parenthesis and report what directly the nuitka command results in case we try to run in the current programme

In case the current folder consists of those:
```
/static/
/templates/
hook-cefpython3.py
script.py
```

With the command:
`python -m nuitka script.py --standalone --plugin-enable=multiprocessing --follow-imports --show-modules --show-scons --show-progress --include-data-dir=./templates=./templates --include-data-dir=./static=./static --mingw64`

The error resulting after running the created exe file is:
`[0413/015803.222:ERROR:icu_util.cc(133)] Invalid file descriptor to ICU data received.`

_This trial of me was trivial, because hook-cefpython3.py has lines related to pyinstaller which is irrelevant to our case with running nuitka._

Therefore we **exclude** hook-cefpython3.py and In case the current folder consists of those:
```
/static/
/templates/
script.py
```

With the command:
`python -m nuitka script.py --standalone --plugin-enable=multiprocessing --follow-imports --show-modules --show-scons --show-progress --include-data-dir=./templates=./templates --include-data-dir=./static=./static --mingw64`

The error resulting after running the created exe file is:
`[0413/042851.483:ERROR:icu_util.cc(133)] Invalid file descriptor to ICU data received.`

After some investigation, I have found out the pyinstaller has it's own way to add their own pyinstaller hooks. From there, and the change of the question title, I can say that there might be needed to have a new feature to include a pyinstaller hook in a nuitka compilation, which is not really what I expect to be from nuitka developers. Well if anyone could do this they can. But pyinstaller is a different product, therefore thank you very much indeed.

Finally, I will be seeking for other ways to use my programme without compiling with any tool. If there is anything that I should do with nuitka, please tell me. Otherwise, I wish you all the best.
