### ISSUE TITLE
macOS: Can't automatically find tcl and tk for python installed via MacPorts

### ISSUE THREAD

**Issue by briankendall** [Nuitka/Nuitka#1524]
Trying to build a script using `--enable-plugin=tk-inter` will fail if python was installed using MacPorts. Setting `TCL_LIBRARY` and `TK_LIBRARY` to `/opt/local/lib/tcl8.6` and `/opt/local/lib/tk8.6` respectively fixes it, and I'm submitting a bug report as suggested by the error message that nuitka printed.

Probably best to also add `/opt/local/lib/tcl8.5` and `/opt/local/lib/tk8.5` to the candidate paths as well.

**Comment by kayhayen** [comment]
What made you think that MacPorts is supported at all?

Anyway, closing for lack of issue template.

**Comment by PgLoLo** [comment]
Same issue, please fix

**Comment by kayhayen** [comment]
If there was a valid report, we could fix it, but me too doesn't cut it either. Please open a new issue with a proper report.
