### ISSUE TITLE
--static-libpython can't find libpython despite being in PATH

### ISSUE THREAD

**Issue by Torxed** [Nuitka/Nuitka#1525]
More of a question of usage than a bug:

* Version information
  ```
  Nuitka Develop 0.8rc8 (and master 0.7.7)
  Commercial: None
  Python: 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]
  Flavor: Unknown
  Executable: /usr/bin/python
  OS: Linux
  Arch: x86_64
  Distribution: Arch None (Arch Linux 2022-04-13)
  ```

* How did you install Nuitka and Python

  `pip` for `develop`, and `pacman -S nuitka` for `master`.

* The specific PyPI names and versions

  I'm not using any libraries.

* Many times when you get an error from Nuitka, your setup may be special

  My limited understanding tells me that Nuitka is trying to locate `Python.h` files.
  And the location of those I get using `pkg-config --cflags python3`.
  And i pre-pend `PATH` with `/usr/include/python3.10`.
  Full PATH: `/usr/include/python3.10:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
  Maybe this is helpful:
  ```
  $ sudo find / -iname '*python.h*' 2>/dev/null
  /usr/share/doc/fontforge/scripting/python.html
  /usr/share/doc/cmake/html/module/FindPython.html
  /usr/share/doc/libxslt-1.1.35/html/python.html
  /usr/share/gtk-doc/html/harfbuzz/integration-python.html
  /usr/share/pycharm/plugins/python-ce/helpers/pydev/pydevd_attach_to_process/common/python.h
  /usr/include/python3.10/Python.h
  /opt/python-dbg/include/python3.10d/Python.h
  ```

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

  ```python
  print("a")
  ```

* Provide in your issue the Nuitka options used

  ```
  $ nuitka3 --linux-onefile-compression=xz --disable-ccache --static-libpython=yes --lto=yes --generate-c-only --disable-bytecode-cache --no-pyi-file --nofollow-imports --standalone test.py
  ```

This is not a high priority issue, I'm simply just a fan of the project and was tinkering and trying to generate the smallest possible build of python code, later I wished to link it/initiate it with other C applications. I might have contradicting flags, or misunderstood the flags. Stumbled upon this and couldn't sort it myself. Closest (but not really helpful/relevant) issue was #1353. Tried `develop` from https://nuitka.net/doc/download.html.

**Comment by kayhayen** [comment]
It is not supported to generate C code and compile it later. The option is intended for testing purposes only. The help output says: `Do not think you can use this directly.`

The `Python.h` is located by code that uses the ABI flags if any. I assume you fail to call scons correctly, since with the command you gave, you cannot get an error from compilation.

**Comment by kayhayen** [comment]
Also the other options lead to important warnings of Nuitka, read those too.

**Comment by Torxed** [comment]
> Also the other options lead to important warnings of Nuitka, read those too.

I see. It spit out some ~600 lines of error messages not being able to find `Py_Threading` and what not, so I must have missed that hint/error.
