### ISSUE TITLE
is there any "onefile" succes in the docker container ? 

### ISSUE THREAD

**Issue by MyraBaba** [Nuitka/Nuitka#1527]
Due to Fuse and docker paltform I couldnt succeed to create onefile nuitka output. 

Is there any other way ? auto extracting to a specific tmp and then execute bin ?

**Comment by kayhayen** [comment]
With Nuitka commercial, there is a script that handles it all automatically. But basically `--onefile-tempdir` needs to given in addition to `--onefile`. We are contemplating on giving up `AppImage` anyway. I am not aware how fuse can work inside a docker container.

**Comment by MyraBaba** [comment]
You can take a look gexe bexe on linux. You could have similar way to package all 

Best

**Comment by MyraBaba** [comment]
gzexe for correction
