### ISSUE TITLE
Issue with /usr/bin/ld: cannot find -lz

### ISSUE THREAD

**Issue by jfesperet** [Nuitka/Nuitka#1529]
> python -m nuitka --version
 python -m nuitka --version
0.7.7
Commercial: None
Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
Flavor: Debian Python
Executable: /usr/bin/python
OS: Linux
Arch: x86_64
Distribution: Debian 10

> Installation of NUITKA with PIP

> When I use NUITKA : python -m nuitka --standalone hello.py
jfe@inttbx01:~/dev$ python -m nuitka --standalone hello.py
Nuitka-Options:INFO: Used command line options: --standalone hello.py
Nuitka:INFO: Starting Python compilation with Nuitka '0.7.7' on Python '3.7' commercial None.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'urllib.request' added 'http.client'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'shelve' added 'dbm'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pathlib' added 'ntpath,posixpath'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module '_asyncio' added 'asyncio'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'locale' added '_bootlocale'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'encodings' added 'encodings.idna,encodings.base64_codec,encodings.hex_codec,encodings.rot_13'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program (no progress information available).
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
scons: *** [/home/jfe/dev/hello.dist/hello] Error 1

**Comment by kayhayen** [comment]
You need to install the respective development packages, if you don't install via Debian package. In this case `libz-dev` might do the trick. Arguably, we could handle these kinds of errors with outputting dependencies.

**Comment by jfesperet** [comment]
Perfect, thank you.
