### ISSUE TITLE
Debug feature: List c-source files

### ISSUE THREAD

**Issue by brupelo** [Nuitka/Nuitka#153]
Consider this:

**MainControl.py**

    def makeSourceDirectory(main_module):
        ...

        module_filenames = pickSourceFilenames(
            source_dir = source_dir,
            modules    = ModuleRegistry.getDoneModules()
        )

        if Options.options.show_source_fies:
            from distutils.util import strtobool

            def userYesNoQuery(question):
                print(question, end="")
                while True:
                    try:
                        return strtobool(input().lower().strip())
                    except ValueError:
                        print("Please respond with 'y' or 'n'.\n")

            print("Compiling:")
            for module in ModuleRegistry.getDoneModules():
                if module.isCompiledPythonModule():
                    print("  {}".format(module_filenames[module]))

            if not userYesNoQuery("Proceed (y/n)? "):
                sys.exit(0)

**OptionsParsing.py**

    debug_group.add_option(
        "--show-source-files",
        action  = "store_true",
        dest    = "show_source_fies",
        default = False,
        help    = """\
    Provide a summary of source files before compilation happens
    """
    )

I've made a fast test how long would take to that code display the numpy c source files and the execution was painfully slow, few minutes.

Can you think of a much faster way (the order of ms/few_seconds, ie: [0s-10s]) that warn the user about which c source files will be generated/compiled?

**Comment by kayhayen** [comment]
Why should the user care which C source files are generated?

The final scope is only known at the end of optimization, because an import statement may or may not be present, so I fail to see how this is better than ``--generate-c-only option`` and an ``ls`` command.

Anyway, I fail to see the motivation here. I discussed on the mailing list that a report of the compilation will be added, and it probably will have to be created incrementally, but it definitely is not my priority right now. I will add it eventually because it should be used in helping me decide if some test cases are doing stupid stuff, e.g. compiling "wheel" in the reflected compilation test.

**Comment by brupelo** [comment]
> Why should the user care which C source files are generated?

I totally agree with you here... remember I'm the guy who already insisted zillion times about UIs providing the minimal feature set that cover important users use-cases, no more, no less. In fact, end-users will only care about 2 things, speed (runtime & build) & correctness. They just want stuff working out of the box and many of them won't try twice if they don't see any benefit on the first attempts, sad but true :)

Anyway, let me clarify a little bit here, this issue is some sort of addon on top of #136 , reason why I opened this new one was mainly to self-answer one of the few questions I've written there... I just didn't want to make longer #136.

That said, you can observe I've written "Debug feature" as a title and then you can also see in one of those throw-away example snippets I've used `debug_group`... so this was intended to be a feature for "advanced/expert" nuitka users :)

Rationale behind this is related - as explained in the other thread - to the fact that building meaty packages is a quite expensive operation in many cases, so if we advanced users knew very soon (a range of [0s-10s] would be ideal) which type of content will be generated/compiled/added into the final extension module  that'd be awesome and it would help us to know whether the options we passed to nuitka are the correct ones or not. 

Unfortunately, I don't see how an incremental logging would help here... You mean adding some logging to the `writeSource` function itself, right? Tbh, to me is the same whether I see printed c files along 400s multiple times rather than all of them after 400s. Probably I'll have to wait 400s mostly of the times :/

Anyway, please consider the whole explained context from the other issue #136 so you have a wider perspective why I'm asking/interested on this one.

Right now I've got some scripts that compiles ~200 packages living in a `requirements.txt`... And many packages will be built ok out of the box decently fast, which it's quite awesome... but in many other cases, huge packages like numpy, pandas, matplotlib, pyopengl, sympy, custom frameworks... well, I'd like to have a finer grain control so I'll know exactly which content to ship or not before deploying anything. When I say finer control I mean, if my project will just use a little % of a huge meaty package I just want to include that little % of the package. As it's not the same spending 900s/1000s rather than <100s :)

Hope it makes more sense now and you can understand a little bit better the "motivation" behind this. Feel free to close this issue though so we can continue the discussion on the other thread or leave this one open, whatever works better for you, your choice.

And just for the record, it's of course low-prio stuff... I was just interested to know from you if this was achievable easily or not. 

But the fact you've already stated this won't be easy to achieve (till optimization stage has ended) makes me think that having a report in the range of 0s-10s will be quite challenging/difficult/impossible to achieve :(

In any case, let me ask you, don't you think end-users & advanced should understand perfectly which type of content will be included on their final extension modules? I mean, it's like if I was going to build projects like {chromium, qt, blender, cmake, ...} from scratch and I didn't know exactly how to configure them nor knowing which stuff to discard on the compilation, that's just crazy :/

**Comment by kayhayen** [comment]
As suggested I am closing this, largely due to my failure to understand. I need to catch up with your comments, but the time to generated the C code should actually be fairly minimal in comparison to reading and optimizing them, so I don't see the point yet.

What I also do not like is to talk about file names at all. In my mind, the split per module is arbitrary and subject to change, and has nothing to do with modules. I hope to inline modules to their users eventually, would that mean they are not included?

Moving --show-inclusion or what it is named up might be an option, but like I said, need to catch up if I can ever make it.
