### ISSUE TITLE
Nuitka compiled binary miscalculates formula containing Modulo

### ISSUE THREAD

**Issue by kamgha** [Nuitka/Nuitka#1530]
Nuitka 0.8rc9 (from source)
CPython 3.7.13 on Windows 7 SP1
GCC+MinGW64: 11.2.0 with MinGW64 master from early April 2022
also tested MSVC 2015U3

Given is the following reproducer:

`python -m nuitka --standalone --disable-ccache ..\test.py`
```
def reduceAngle(deg):

    return ((deg + 180.) % 360.) - 180.


for i in range(-1000,1001):
    print(str(i) + ": " + str(reduceAngle(i)))
```

Running the code in CPython 3.7.13 gives an expected output. Values returned shall be in the range [-180..180), which means v >= -180 up to v < 180.
[test-CPython.txt](https://github.com/Nuitka/Nuitka/files/8492369/test-CPython.txt)

The output after compiled with Nuitka gives back different values when the input is negative and lower than a certain threshold. It is outside the expected range (seems to be between -539 and 179 in this example).
[test-Nuitka.txt](https://github.com/Nuitka/Nuitka/files/8492370/test-Nuitka.txt)

**Comment by Maxwell175** [comment]
Interesting. Can confirm that the output of that script is different on CPython vs Nuitka.

```
0.7.6
Commercial: None
Python: 3.8.10 (default, Nov 26 2021, 20:14:08) 
Flavor: Debian Python
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Ubuntu) 5.24
```

**Comment by kayhayen** [comment]
Wow, thanks for the report, that is the worst kind of bug.

**Comment by kayhayen** [comment]
This uses `BINARY_OPERATION_MOD_OBJECT_OBJECT_FLOAT` as it knows the right hand side statically, which then seeks to specialize, with float check and `float % float` code, but I suspect now that the handling of sign is somehow wrong.

**Comment by kayhayen** [comment]
This is fixed on factory, it seems positive module of negative values were wrong. I made a mistake when I created the Jinja2 template for the modulo and `divmod` code, confusing left and right argument in a check, and CPython test suite apparently didn't find it, nor did I. Thanks for the report.

**Comment by kamgha** [comment]
Looks good now, thanks.

**Comment by kayhayen** [comment]
This is now on develop and will be in 0.8 release.

**Comment by kayhayen** [comment]
Part of 0.8 release that I just made.
