### ISSUE TITLE
Example code Argument list too long 'ldd' ERROR

### ISSUE THREAD

**Issue by MyraBaba** [Nuitka/Nuitka#1533]
This a reproducable example of  

```

import configparser
import pickle
import sqlite3
import torch
import datetime
import numpy as np
import os
import cv2
import socket
import mxnet as mx

cv2.waitKey(2)
print(torch.name)
x = np.array(0)
cc = mx.gpu()
o = os.path
v = socket.AddressInfo
```

whenyou try to compile with : 

python3 -m nuitka --onefie

above code gives Argument list is too long 'ldd' error

Is there any one can compile above code with onefile / nuitka ? 

I assume what ever ldd is doing should be divided and doing partially to solve

Best

**Comment by Maxwell175** [comment]
@MyraBaba It seems like you missed the part of the issue template about providing the output of the `python -m nuitka --version`.

**Comment by MyraBaba** [comment]
@Maxwell175 
python -m nuitka --version
0.7.6
Commercial: None
Python: 3.8.5 (default, Jul 28 2020, 12:59:40) 
Flavor: Debian Python
Executable: /home/2080/.local/share/virtualenvs/.venv/vvv/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 20.04.1

**Comment by kayhayen** [comment]
I am assuming the torch plugin was not used, that will normally disable compilation for a lot of modules, which I kind of hate for it to do, but maybe that's why it does it.

**Comment by kayhayen** [comment]
Closing for lack of feedback. The issue ought to be solved on current develop version, there was a better reporting duplicate.
