### ISSUE TITLE
How to make EXE work with embedded python environment in subdirectory

### ISSUE THREAD

**Issue by lon91ong** [Nuitka/Nuitka#1540]
I compile `main.py` with the following parameters: `nuitka --mingw64 --nofollow-imports --full-compat --plugin-enable=upx --windows-disable-console --output-dir=out main.py`
The main.exe can be used with the embedded python environment in the directory structure shown below.
![directory structure](https://user-images.githubusercontent.com/16462258/165291663-8d8e3724-ac72-40d4-a06f-95fc09417b98.png)
I want to organize the directory structure as shown below.
![sub python dir](https://user-images.githubusercontent.com/16462258/165292812-f36dd06a-c65f-49d6-9cb7-5b731eb00efd.png)

Please let me know if there is a possible way to do this. Thanks a lot!

**Comment by kayhayen** [comment]
It is not possible, the embedded Python is incomplete and not supported.

**Comment by lon91ong** [comment]
@kayhayen The main.exe works well in the directory structure shown below.
![directory structure](https://user-images.githubusercontent.com/16462258/165413718-41589caa-35b6-425e-a1a0-eb4e0f622b32.png)

**Comment by lon91ong** [comment]
> It is not possible, the embedded Python is incomplete and not supported.

@kayhayen I use the full Python environment with Nuitka to compile, and then package the EXE file with embedded Python for distribution.
