### ISSUE TITLE
Question: Can I switch .exe architecture while compiling a python code?

### ISSUE THREAD

**Issue by thecowmilk** [Nuitka/Nuitka#1542]
It would be cool if I can build an `.exe` with `32bit` architecture when I have a `x86-64` architecture or vice versa rather than installing an OS for that architecture.

**Comment by kiseki999** [comment]
If you are using 64-bit Windows, you can also generate a 32-bit `.exe`. You just need to run Nuitka using the 32-bit version of Python.

**Comment by kayhayen** [comment]
The only thing I would add is that on macOS with universal Python binaries, it can be done, there is an option to pick `arm64` or `x86_64`, and even universal there.

**Comment by thecowmilk** [comment]
@kayhayen apologise for reopening but since I have the time I want to ask smth, can this also be done in Windows? It'd be very great if we could have this one on other platforms than MacOSm

**Comment by kayhayen** [comment]
@thecowmilk the reason this is done on macOS is that for efficiency we need to be able to strip architectures from what is often compiled as dual arch binary Python and libraries on PyPI.

Nuitka used to have `--python-arch` and `--python-version` make it switch the Python binary, but I decided to let go of this and the version switching, these were only restarting Nuitka with the specified Python interpreter, that also had to be installed and found, and this e.g. won't work well at all with virtualenv and friends, so it was more of a trap when it picked wrongly.

So never happening again, that's for sure in my mind. Maybe one day when cross compiling is solved, it might be revived as part of that. But even then you will need the target Python somewhere.
