### ISSUE TITLE
scikit-learn .libs directory error

### ISSUE THREAD

**Issue by interseba5** [Nuitka/Nuitka#1544]
The execution of the code listed below result in this error:
```
Traceback (most recent call last):
File "D:\_DEV\BRANCH\C-LINK~1.0_L\C-2BEA~1\MAIN~1.DIS\main.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\_DEV\BRANCH\C-LINK~1.0_L\C-2BEA~1\MAIN~1.DIS\plotter.py", line 5, in <module plotter>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\_DEV\BRANCH\C-LINK~1.0_L\C-2BEA~1\MAIN~1.DIS\sklearn\__init__.py", line 80, in <module sklearn>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\_DEV\BRANCH\C-LINK~1.0_L\C-2BEA~1\MAIN~1.DIS\sklearn\_distributor_init.py", line 23, in <module sklearn._distributor_init>
  File "D:\_DEV\BRANCH\C-LINK~1.0_L\C-2BEA~1\MAIN~1.DIS\ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'D:\_DEV\BRANCH\C-LINK~1.0_L\C-2BEA~1\MAIN~1.DIS\sklearn\.libs\vcomp140.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

The error message refer to a missing dll named `vcomp140.dll` but the entire `sklearn\.lib` directory is missing from the dist directory.
I have tried to add manually the .libs directory from `C:\Python39\Lib\site-packages\sklearn\.libs` in `main.dist\sklearn` but when i run main.exe again it does not print nothing in stdout and the program exits immediatly .

0.7.7
Commercial: None
Python: 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Python39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

I installed from https://www.python.org/downloads/

I use pip and i dont use any virtual enviroment.
Pip version:
pip 22.0.4 from c:\python39\lib\site-packages\pip (python 3.9)

Some pip package version:
numpy==1.22.3
pandas==1.4.1
scikit-learn==1.0.2
scipy==1.8.0
xgboost==1.6.0
imbalanced-learn==0.9.0

* Short code example
```Python
from operator import index
import pandas as pd
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier,AdaBoostClassifier
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split as sklearn_train_test_split,GroupShuffleSplit
from imblearn.over_sampling  import RandomOverSampler, SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.combine import SMOTETomek, SMOTEENN
from collections import Counter
from imblearn.ensemble import BalancedRandomForestClassifier
from numpy import zeros
from xgboost import XGBClassifier

print("Hello world")
```

*  Nuitka options used

python -m nuitka --enable-plugin=numpy --standalone main.py

**EDIT**
After i copy the .libs directory in the dist path and try to debug the EXE with Visual Studio, i obtain this exception: `Exception thrown at 0x00007FF76265EA03 in main.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.`

**Comment by kayhayen** [comment]
When I tried this on Linux, I found a missing implicit dependency, adding that. The report is a bit cloudy, since it uses more imports than described as causing the bug, I removed all `imblearn`  and try to focus on `sklearn` here. I think Linux might not have a `.libs` issue, but it will be nice to see that working first, since it's so much easier for debugging.

**Comment by interseba5** [comment]
Im using nuitka because i'm trying to demonstrate to my manager that we can use this in our company, so we are not commercial user but we are planning to become

**Comment by kayhayen** [comment]
This is fixed in the current 0.8 release.

**Comment by interseba5** [comment]
I have tried to recompile this with nuitka 0.8.3 but again i obtain this while debugging with visual studio:
`'main.exe' (Win32): Loaded 'D:\main.dist\scipy\stats\_boost\beta_ufunc.pyd'. Module was built without symbols.
'main.exe' (Win32): Loaded 'D:\main.dist\scipy\stats\_boost\binom_ufunc.pyd'. Module was built without symbols.
'main.exe' (Win32): Loaded 'D:\main.dist\scipy\stats\_boost\nbinom_ufunc.pyd'. Module was built without symbols.
'main.exe' (Win32): Loaded 'D:\main.dist\scipy\stats\_boost\hypergeom_ufunc.pyd'. Module was built without symbols.
'main.exe' (Win32): Loaded 'D:\main.dist\scipy\stats\_biasedurn.pyd'. Module was built without symbols.
Exception thrown at 0x00007FF62BF16E73 in main.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.`

**Comment by kayhayen** [comment]
@interseba5 posting below closed issues is a surefire way of getting ignored, this time I am pointing out the duplicate #1565
