### ISSUE TITLE
Python3: Cannot use keyword arguments in "str.split()"

### ISSUE THREAD

**Issue by djgood** [Nuitka/Nuitka#1545]
Thanks for creating such a useful tool! Upgraded my version of Nuitka today and ran into this bug.

* Nuitka version:

`python -m nuitka --version`

```
0.7.6
Commercial: None
Python: 3.8.9 (default, Oct 26 2021, 07:25:54)
Flavor: Apple Python
Executable: /<path>/venv/bin/python
OS: Darwin
Arch: x86_64
```

* Nuitka was installed via pip: `pip install nuitka==0.7.6`

Minimal example `test_program.py` to reproduce this:
```
print(__name__.split('.', maxsplit=1)[0])
```

* Compiling with `python -m nuitka test_program.py` and running the resulting .bin file results in the following exception:
```
  File "/<path>/test_program.py", line 2, in <module>
    print(__name__.split('.', maxsplit=1)[0])
TypeError: str.split() takes no keyword arguments
```

* This is a regression, I have it last working in 0.6.17.7, I have tried the develop version and the issue still persists.

I suspect this might be coming from the string optimizations added in versions after 0.6.17.7. I was looking through the documentation and was hoping to find a way to disable these to see if that was indeed the issue, but I couldn't find anything. If there's anything I can set to work around this issue for now, that would be appreciated! :)

Edit:

The obvious workaround here is to call `.split()` with `maxsplit` positionally rather than using the keyword. Unfortunately, this is in a library I'm using which I don't want to have to patch. Since calling this with a keyword argument is supported in Python 3, it would be nice if it was also supported when compiling with Nuitka.

**Comment by kayhayen** [comment]
Thanks for your report, this should be easy to fix.

**Comment by kayhayen** [comment]
The keyword allowance was added in Python3, which probably is why I didn't see it, and why most code doesn't yet use it.

**Comment by kayhayen** [comment]
I pushed a fix to factory, and enhanced the generated test to cover this, so these things are harder to go unnoticed.

**Comment by kayhayen** [comment]
https://nuitka.net/doc/factory.html

**Comment by djgood** [comment]
Thanks for the speedy response and glad to hear it was an easy fix :) Can confirm I am no longer getting this error in factory.

**Comment by kayhayen** [comment]
This is now on the develop branch.

**Comment by kayhayen** [comment]
Part of 0.8 release that I just made.
