### ISSUE TITLE
How does one include a binary that is generated from python from an included package?

### ISSUE THREAD

**Issue by zackees** [Nuitka/Nuitka#1546]
# Nuitka How does one include an internal binary that is generated from python from an included package?

I couldn't find the solution is searches or documentation (with a light skim) so I'm going to push this question here in hopes that others that come to this issue will find it through a search engine.

In many python projects the api is in the form of a command line program. For example `garc` it is used like this:

```
python -m pip install garc
garc --help
```

However, if i build a Nuitka project the program will error that `garc` cannot be found. Other projects like `static_ffmpeg` or `ytclip` would suffer the same fate.

It might be that this feature is already supported but that I need to include some magic. Or maybe this isn't supported at all and needs to be implemented via a custom plugin. Regardless it would be great to know what the issue is because running installed commands is a large subset of the python app ecosystem.

## python -m nuitka --version

0.7.7
Commercial: None
Python: 3.10.4 (v3.10.4:9d38120e33, Mar 23 2022, 17:29:05) [Clang 13.0.0 (clang-1300.0.29.30)]
Flavor: Unknown
Executable: /Users/niteris/Programming/rss2gab/venv/bin/python
OS: Darwin

## How did you install Nuitka and Python

pip

## The specific PyPI names and versions
astroid==2.11.3
attrs==21.4.0
auto-selenium==1.0.1
beautifulsoup4==4.11.1
black==22.3.0
certifi==2021.10.8
charset-normalizer==2.0.12
click==8.1.3
dill==0.3.4
distlib==0.3.4
download==0.3.5
feedparser==6.0.8
filelock==3.6.0
flake8==4.0.1
gabposter==1.2.0
garc==2.1
idna==3.3
iniconfig==1.1.1
isort==5.10.1
Jinja2==3.1.2
lazy-object-proxy==1.7.1
MarkupSafe==2.1.1
mccabe==0.6.1
msedge-selenium-tools==3.141.4
mypy==0.950
mypy-extensions==0.4.3
Nuitka==0.7.7
packaging==21.3
pathspec==0.9.0
platformdirs==2.5.2
pluggy==1.0.0
py==1.11.0
pycodestyle==2.8.0
pyflakes==2.4.0
pyjpgclipboard==1.0.1
pylint==2.13.7
pyparsing==3.0.8
pytest==7.1.2
python-dateutil==2.8.2
requests==2.27.1
rss2gab @ file:///Users/niteris/Programming/rss2gab
selenium==3.141.0
sgmllib3k==1.0.0
six==1.16.0
soupsieve==2.3.2.post1
toml==0.10.2
tomli==2.0.1
tox==3.25.0
tqdm==4.64.0
typing_extensions==4.2.0
urllib3==1.26.9
virtualenv==20.14.1
wrapt==1.14.0
zstandard==0.17.0

## Many times when you get an error from Nuitka, your setup may be special

No errors while compile. Final binary doesn't run.

## Code snippet

```
import os.system('garc --help')
```

The program will fail

## Provide in your issue the Nuitka options used

    "python -m nuitka",
    "--follow-imports",
    "--standalone",
    "--include-package=garc",
    "--include-package-data=selenium,rss2gab,garc",
    f"--output-dir={APP_BUILD_DIR}",
    APP_SRC,
    "--onefile",
    "-o",
    f"{APP_BUILD_DIR}/{APP_NAME}",

**Comment by kayhayen** [comment]
This is not currently supported, and will need `sharedist` or `multidist` from the roadmap. Basically a binary with multiple entry points is what it does: https://nuitka.net/doc/roadmap.html

It is expected to happen during the summer.

**Comment by zackees** [comment]
Great, thanks for the quick answer.

Btw, if you want a great demo of your library in action please check out:

https://github.com/zackees/open-webdriver

It builds flawlessly in mac/linux/win

Just want to say what a great product this is and I hope people discover it more. It really satisfies the use case of delivering a compiled binary to a client. If you ever are able to get a wasm version compiled (probably libpython is the blocker) then you have the potential to create an entire mini container system for python.

**Comment by johnosbb** [comment]
I have a solution that currently uses pyinstaller. It uses spellchecker which I add to the pyinstaller spec file with something like:

python -m PyInstaller --add-binary="spellchecker/resources/en.json.gz;spellchecker/resources" main.py

It seems from the comments above that this is not supported. Is this still the case? IS there another may of facilitating the need to add these resource files?

**Comment by kayhayen** [comment]
So "multidist" is now a thing since 1.4 release, so multiple `--main` and you can run it through different names. Check out the user manual for how that is best done. At this time the doc is not perfect, but it will hopefully become better.

Also the Yaml Package configuration can have files defined as DLLs to be "binary", in which case they do get DLL treatment and also have the executable bit set. The docs are also sparse on this. 

Not sure when I get to make a post about an included binary example, so far no PyPI package needed it, or it wasn't used there, but maybe the Qt plugins will migrate to it.

And lastly, plugins are capable of yield objects that describe executables just like DLLs to include. Just check the Qt plugins for how it's done with webengine.

**Comment by kayhayen** [comment]
I forgot to give the pointer: https://nuitka.net/doc/nuitka-package-config.html#where-else-to-look

If these are PyPI packages, PRs that put it to use are very welcome.
