### ISSUE TITLE
Nuitka returns error: FATAL: Error, unknown plug-in 'librosa' referenced.

### ISSUE THREAD

**Issue by JorisSneagle** [Nuitka/Nuitka#1548]
I am trying to compile my python program with Nuitka but it returns the error: FATAL: Error, unknown plug-in 'librosa' referenced. when run with the following command:
`
python -m nuitka --standalone --enable-plugin=tk-inter --enable-plugin=numpy --enable-plugin=librosa --enable-plugin=matplotlib program.py`

my system information is as follow:
`
0.7.7
Commercial: None
Python: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\joris\AppData\Local\Programs\Python\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10`

nuitka was installed via pip

the ` python -m pip freeze` command returns the following (shortened to the ones used in the project):
`librosa==0.9.1
matplotlib==3.5.1
numpy==1.21.5`

the unshortened list is as follows:
`altgraph==0.17.2
appdirs==1.4.4
audioread==2.1.9
auto-py-to-exe==2.19.0
bottle==0.12.19
bottle-websocket==0.2.9
cachetools==5.0.0
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.12
cx-Freeze==6.10
cx-Logging==3.0
cycler==0.11.0
Cython==0.29.28
decorator==5.1.1
Eel==0.12.4
fonttools==4.31.2
future==0.18.2
gevent==21.12.0
gevent-websocket==0.10.1
greenlet==1.1.2
idna==3.3
joblib==1.1.0
kiwisolver==1.4.2
librosa==0.9.1
llvmlite==0.38.0
matplotlib==3.5.1
Nuitka==0.7.7
numba==0.55.1
numpy==1.21.5
packaging==21.3
pefile==2021.9.3
Pillow==9.1.0
pooch==1.6.0
py2exe==0.11.1.0
pycparser==2.21
pyinstaller==5.0.1
pyinstaller-hooks-contrib==2022.4
pyparsing==3.0.7
python-dateutil==2.8.2
pywin32-ctypes==0.2.0
requests==2.27.1
resampy==0.2.2
scikit-learn==1.0.2
scipy==1.8.0
six==1.16.0
SoundFile==0.10.3.post1
threadpoolctl==3.1.0
urllib3==1.26.9
whichcraft==0.6.1
zope.event==4.5.0
zope.interface==5.4.0
zstandard==0.17.0`

A hello world program compiles but the resulting exe file crashes after 1s without error in command prompt when run

**Comment by kayhayen** [comment]
Well, the issue template has a point, but well, Nuitka has a no `librosa` plugin. It seems you are confused. Curious what made you use that.

**Comment by JorisSneagle** [comment]
I thought Nuitka was supposed to be able to compile any program written in python regardless of what libraries it uses. I need librosa for my script because it needs to read an audio file and then fourier transform it. 

Also I am still very much a beginner so it is possible i got something mixed up.

**Comment by Fire-Cube** [comment]
The plugins are only for special modules that don't work without plugins.  However, most modules work without plugins.  Just try it without.  If it doesn't work, you can report the error message.

**Comment by kayhayen** [comment]
If you find something to not work, you do not invent a plugin name, you make a minimal reproducer and report the issue, and then the supposed state will be achieved from that report.
