### ISSUE TITLE
Debian: standalone and onefile not correctly copying required libs and files for end product

### ISSUE THREAD

**Issue by MyraBaba** [Nuitka/Nuitka#1549]
Version:

> nuitka3 --version
> 0.8rc9
> Commercial: None
> Python: 3.6.9 (default, Dec  8 2021, 21:08:43)
> Flavor: Debian Python
> Executable: /usr/bin/python3
> OS: Linux
> Arch: x86_64
> Distribution: Ubuntu (based on Debian) 18.04.6

Sample Code:

```
from __future__ import division
import setproctitle
import argparse
import logging
from pathlib import Path


logging.basicConfig(filename="_11_log.txt",
                                                        filemode='a',
                                                        format='%(asctime)s,%(msecs)d %(name)s %(levelname)s %(message)s',
                                                        datefmt='%H:%M:%S',
                                                        level=logging.INFO)

logger = logging.getLogger()

from signal import signal, SIGINT
from sys import exit
import sys , os
import configparser
import pickle
import sqlite3
import torch
import numpy as np
import os
import cv2
import socket

xx  = np.empty(shape=[0, 1024], dtype=np.float32)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
img = cv2.imread("test.jpg")`

```
nuitka .

> python3 -m nuitka --plugin-enable=numpy   --plugin-enable=torch --standalone  compileTest.py

binary compileTest succesfully created.

When I run It complains for torc related libs cant be found.  what I see the troch libs in the : torch/lib   in the dist folder of the binary. 

I copied all torch libs fromthere to the binary folder . 

run again and now :   

> compileTest.dist# ./compileTest
Traceback (most recent call last):
  File "/concrete_prohavelsan/compileTest.dist/numpy/core/__init__.py", line 22, in <module numpy.core>
  File "/concrete_prohavelsan/compileTest.dist/numpy/core/multiarray.py", line 12, in <module numpy.core.multiarray>
  File "/concrete_prohavelsan/compileTest.dist/numpy/core/overrides.py", line 7, in <module numpy.core.overrides>
ImportError: libopenblasp-r0-09e95953.3.13.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/concrete_prohavelsan/compileTest.dist/compileTest.py", line 22, in <module>
  File "/concrete_prohavelsan/compileTest.dist/torch/__init__.py", line 605, in <module torch>
  File "/concrete_prohavelsan/compileTest.dist/torch/cuda/__init__.py", line 607, in <module torch.cuda>
  File "/concrete_prohavelsan/compileTest.dist/torch/cuda/amp/__init__.py", line 1, in <module torch.cuda.amp>
  File "/concrete_prohavelsan/compileTest.dist/torch/cuda/amp/autocast_mode.py", line 6, in <module torch.cuda.amp.autocast_mode>
  File "/concrete_prohavelsan/compileTest.dist/numpy/__init__.py", line 140, in <module numpy>
  File "/concrete_prohavelsan/compileTest.dist/numpy/core/__init__.py", line 48, in <module numpy.core>
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.6 from "/concrete_prohavelsan/compileTest.dist/python3"
  * The NumPy version is: "1.19.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libopenblasp-r0-09e95953.3.13.so: cannot open shared object file: No such file or directory

I copied from /usr/local/lib/python3.6/dist-packages/numpy.libs/libopenblasp-r0-09e95953.3.13.so to compile.dist/ folder 

so program continuously complaining   libs for torch, numpy , torch and opencv...

How we can properly compile and run the standalone version of the program ?

Best

**Comment by kayhayen** [comment]
The Debian system packages are not very portable. Actually a lot of effort is being done by Debian to make sure that packages are properly distributed in the FHS. The plugins work for standalone with PyPI packages, but for Debian, it has been attempted, but it's probably a lost cause.

The non-working nature of Debian system should cause an error for using standalone builds that points this out. I am waiting for warnings/errors to be able to point to generic explaining pages.

**Comment by kayhayen** [comment]
The warning is there in 0.9 now, even though the link it points to doesn't yet exist, still closing this one.
