### ISSUE TITLE
ModuleNotFoundError: No module named 'http.cookiejar'

### ISSUE THREAD

**Issue by byehack** [Nuitka/Nuitka#1551]
## t.py:
```python
while 1: exec(input('> '))
```

### v0.8rc9:
```
~~~>C:\Python37x86\python -m nuitka --standalone --mingw64 t.py

Nuitka-Options:INFO: Used command line options: --standalone --mingw64 t.py
Nuitka:INFO: Starting Python compilation with Nuitka '0.8rc9' on Python '3.7' commercial None.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'wsgiref.simple_server' added 'http.server'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'urllib.request' added 'http.client'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'socket' added '_socket'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'shelve' added 'dbm.dumb'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pathlib' added 'ntpath,posixpath'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module '_asyncio' added 'asyncio'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'locale' added '_bootlocale'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'encodings' added 'encodings.idna,encodings.base64_codec,encodings.hex_codec,encodings.rot_13'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program (no progress information available).
Nuitka-Scons:INFO: Compiled 20 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 8
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 1
Nuitka:INFO: Keeping build directory 't.build'.
Nuitka:INFO: Successfully created 't.dist\\t.exe'.

~~~>t.dist\t.exe
> import http.server
> import http.cookiejar
Traceback (most recent call last):
  File "C:\Users\Tester\Desktop\ttr\y\TBDD7~1.DIS\t.py", line 25, in <module>
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'http.cookiejar'
```
### v0.6.19.7:
```
~~~>python -m nuitka --standalone --mingw64 t.py
Nuitka-Options:INFO: Used command line options: --standalone --mingw64 t.py
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.19.7' on Python '3.7' commercial None.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'tkinter' added '_tkinter'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'socket' added '_socket'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'locale' added '_bootlocale'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Compiled 11 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 10
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 1
Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3\Grammar3.7.9.final.0.pickle' due to package data for 'lib2to3.pgen2'.
Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3\PatternGrammar3.7.9.final.0.pickle' due to package data for 'lib2to3.pgen2'.
Nuitka:INFO: Keeping build directory 't.build'.
Nuitka:INFO: Successfully created 't.dist\\t.exe'.

~~~>t.dist\t.exe
> import http.server
> import http.cookiejar
> 
```
Here is reports for full comparison:

[0.6.19.7.xml.zip](https://github.com/Nuitka/Nuitka/files/8599828/0.6.19.7.xml.zip)

[0.8rc9.xml.zip](https://github.com/Nuitka/Nuitka/files/8599833/0.8rc9.xml.zip)

**Comment by byehack** [comment]
here is reports for full comparison:

[0.6.19.7.xml.zip](https://github.com/Nuitka/Nuitka/files/8599828/0.6.19.7.xml.zip)

[0.8rc9.xml.zip](https://github.com/Nuitka/Nuitka/files/8599833/0.8rc9.xml.zip)

**Comment by Maxwell175** [comment]
There is no way for nuitka to figure out what packages you want to include since your code doesn't have any references to them. Check the --help output for options to manually specify what packages to include. Perhaps `--include-package=http`.

**Comment by byehack** [comment]
@Maxwell175 
Nuitka already imported `urllib.request` which depends on `http.cookiejar`.
I compared it with PyInstaller.

**Comment by ralienpp** [comment]
My current workaround for this problem is to add `import http.cookiejar  # noqa` to the file Nuitka compiles, to explicitly tell it that I want it to be imported. The "noqa" comment is needed if you have any tools like flake8 or pylint that will complain about unused imports.

**Comment by kayhayen** [comment]
Given time, all of `stdlib` might not be included. Initially, only packages like `http` are excluded, but the list is constantly growing.

That said, there is no option that would ignore it, and include all of stdlib, which might be what people can want, to e.g. delivery a Python interactive prompt like that. I accept that usecase, but I don't care. But probably a `--include-stdlib` for standalone mode might be useful to some people. Or just one?

**Comment by kayhayen** [comment]
@byehack your commit is confusing me, are you saying `http.cookiejar` is a hidden dependency of `http.client`  ?

**Comment by kayhayen** [comment]
You are probably confused by `wsgiref` still being included, which is something I am just changing, which will also allow to remove the dependency on `http.client` it has. I have not removed it on factory yet, but I probably will.

With modules from stdlib, it compiles them for dependency analysis, unless they are included just because, which made `wsgiref` not work until adding its dependency or moving it out.

**Comment by byehack** [comment]
> My current workaround for this problem is to add `import http.cookiejar # noqa` to the file Nuitka compiles, to explicitly tell it that I want it to be imported. The "noqa" comment is needed if you have any tools like flake8 or pylint that will complain about unused imports.

@ralienpp 
True, Actually I already used this solution in my code after upgraded to version 0.8rc9.
but i'm looking for another solution to solve this problem without changing in my code. At least command line option to hidden-import module.

> I accept that usecase, but I don't care. But probably a `--include-stdlib` for standalone mode might be useful to some people. Or just one?

@kayhayen 
I tested with `--include-stdlib` but still it doesn't include `http.cookiejar`.


> @byehack your commit is confusing me, are you saying `http.cookiejar` is a hidden dependency of `http.client` ?

Yes. exactly.

**Comment by byehack** [comment]
> You are probably confused by `wsgiref` still being included, which is something I am just changing, which will also allow to remove the dependency on `http.client` it has. I have not removed it on factory yet, but I probably will.
> 
> With modules from stdlib, it compiles them for dependency analysis, unless they are included just because, which made `wsgiref` not work until adding its dependency or moving it out.

True. it should not include stdlib modules (that are not imported in header of other stdlib modules) until they actually used from our script.
but some stdlibs like `urllib.request` depends `http.cookiejar`.
I agree `urllib.request` doesn't import `http.cookiejar` in header of source, but in `HTTPCookieProcessor` which is important class for me importing `http.cookiejar`

![image](https://user-images.githubusercontent.com/26390254/166303024-c482583b-fbde-430d-beca-7df6897ac9b7.png)

if anyway or option to implement its behavior like v0.6.19 i'll be happy.

**Comment by kayhayen** [comment]
I see, that's indeed a hidden dependency when `urllib` is not treated like that, but I fear, I cannot do that now. So my solution will have to be to remove `http` from the non-automatic inclusion list. I cannot dare expanding it to `urllib` just yet, there will be so many things that depend on that in turn.

**Comment by kayhayen** [comment]
I have added the dependency to `urllib.requests` where it belongs, confused myself there. https://nuitka.net/doc/factory.html

**Comment by byehack** [comment]
I installed [Factory](https://github.com/Nuitka/Nuitka/tree/a05708cacac554eef5a2f21faaac4cb47191277d) and compared with develop version.
![image](https://user-images.githubusercontent.com/26390254/166541958-e6f4714b-2c05-44cd-8aeb-461b6d2082df.png)

i know `wsgiref` package excluded by https://github.com/Nuitka/Nuitka/commit/543193571fb3f780ce36aca4fb1574e0c9eb1fcb.
but why `http.server` is also excluded?

**Comment by kayhayen** [comment]
This is now on the develop branch.

**Comment by kayhayen** [comment]
Part of 0.8 release that I just made.
