### ISSUE TITLE
Nuitka-Scons:INFO: Backend linking program (no progress information available). Never done

### ISSUE THREAD

**Issue by SysKeyyy** [Nuitka/Nuitka#1553]
This part is what i'm stuck on, all the time 
![image](https://user-images.githubusercontent.com/68533095/166197627-15c720c2-b954-41f2-800f-d67e64436626.png)
I have wated multiple hours never getting past it just with a hell world script, iv'e turned of my AV and looked for solutions but haven't found any. I litterally don't know what to do '

EDIT: When it's done i get this error
![image](https://user-images.githubusercontent.com/68533095/166206925-2ced580f-56c0-4634-8ccf-60d89d5eeb60.png)
OSError: [WinError 193] %1 is not a valid Win32-program

**Comment by kayhayen** [comment]
Screenshots are not reports

**Comment by kayhayen** [comment]
let alone not filled out issue templates
