### ISSUE TITLE
0xc0000005 Access Violation when including scipy.signal

### ISSUE THREAD

**Issue by pepassaco** [Nuitka/Nuitka#1554]
# The problem

After executing the .exe, a terminal window opens and auto-closes after a couple of seconds without outputing anything. 

Debugging with VisualStudio 2019 I can get to see that the program is outputing a ```0xc0000005 Access Violation``` error.

I was working with a bigger program and, after a lot of time debugging, I got to the conclussion that the line which is causing said error is the one where I import scipy.signal. In order to verify this, I created the following simple program, which Nuitka is not able to conver properly to an executable. 

# Nuitka version

OS: Windows 11
```
python -m nuitka --version
0.7.7
Commercial: None
Python: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\quita\AppData\Local\Programs\Python\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

I also tried a venv with Python 3.9 and got the same result.

# Installation

I installed Nuitka from pip and Python from the Microsoft Store. 

# My program

It cannot get simpler

```
from scipy.signal import butter, lfilter
print("Hello, world!")
pause = input(":)")
```

The program works fine when removing the import.

# My packages

```
python -m pip freeze
assimp==4.1.4
cachetools==5.0.0
certifi==2021.10.8
charset-normalizer==2.0.12
cmake==3.22.4
configparser==5.2.0
cssselect2==0.6.0
cycler==0.11.0
Cython==0.29.28
distlib==0.3.4
docopt==0.6.2
easygui==0.98.3
et-xmlfile==1.1.0
filelock==3.6.0
fonttools==4.33.3
future==0.18.2
idna==3.3
imageio==2.18.0
keyboard==0.13.5
kiwisolver==1.4.2
liccheck==0.6.5
lxml==4.8.0
matplotlib==3.5.1
Nuitka==0.7.7
numpy==1.22.3
numpy-quaternion==2022.4.2
openpyxl==3.0.9
packaging==21.3
Panda3D==1.10.11
pandas==1.4.2
pefile==2021.9.3
Pillow==9.1.0
pipreqs==0.4.11
platformdirs==2.5.2
py2exe==0.11.1.0
pygame==2.1.2
pyparsing==3.0.8
PyPDF2==1.27.9
python-dateutil==2.8.2
python-obfuscator==0.0.2
pytz==2022.1
Quaternion==3.5.2.post4
regex==2022.4.24
reportlab==3.6.9
requests==2.27.1
scipy==1.8.0
semantic-version==2.9.0
six==1.16.0
svglib==1.2.1
tinycss2==1.1.1
toml==0.10.2
urllib3==1.26.9
virtualenv==20.14.1
webencodings==0.5.1
xlrd==2.0.1
yarg==0.1.9
zstandard==0.17.0
```

# My Nuitka command

```
python -m nuitka --standalone --enable-plugin=numpy --windows-icon-from-ico=icon.png .\main.py
```

I also tried without the icon argument, with the ```--onefile``` option and whith the options for saving errors and stdout to files with no luck.

I do not obtain any warning nor error during its execution, only info messages.

**Comment by interseba5** [comment]
Same exception as my [issue](https://github.com/Nuitka/Nuitka/issues/1544)

**Comment by kayhayen** [comment]
@interseba5 you are correct, I will look into this once I can

**Comment by pepassaco** [comment]
Thank you for taking a look at this. If you were able to suggest any quick fix or workaround for the moment, I'd be interested in trying it out! :)

**Comment by kayhayen** [comment]
This has worked just fine for me on Linux, but with older scipy, might be new one only.

**Comment by kayhayen** [comment]
Works fine on Windows too, seems bogus report as it is.

**Comment by kayhayen** [comment]
Seems I oversaw the duplicate nature, this has been fixed through the other issue of course and was not invalid, but duplicate.
