### ISSUE TITLE
AppImage: add option to specify application name

### ISSUE THREAD

**Issue by bearsh** [Nuitka/Nuitka#1557]
Right now the application name is taken from the binary name:
https://github.com/Nuitka/Nuitka/blob/6d868e6d6c371f46ce627f8b774ad3db3d14cab3/nuitka/freezer/Onefile.py#L154-L164

an option to specify a more human readable application name (which makes the marketing department happy) would be nice as `binary_basename` tend to be a technical name.

**Comment by bearsh** [comment]
instead of a name option, maybe a more generic solution regarding .dektop files can used which would also solve #1130

**Comment by kayhayen** [comment]
That's correct, I am working to universalize the product information that is currenly Windows only, and then will work to produce Desktop files for Linux with it. I would welcome a PR that makes use of the `getWindowsCompanyName` there even now, but for now I have to defer it from my side until the automatic updating and code signing hits Linux too.

**Comment by kayhayen** [comment]
For Linux we do not generate desktop files anymore, and we may well add that, but AppImagine does not exist anymore, therefore I am closing this.
