### ISSUE TITLE
Anaconda static libpython is no more compatible, error: "libpython3.9.a: error adding symbols: File format not recognized"

### ISSUE THREAD

**Issue by r00t1900** [Nuitka/Nuitka#1559]
Nuitka version:
```
0.7.7
Commercial: None
Python: 3.9.7 (default, Sep 16 2021, 13:09:58) 
Flavor: Anaconda Python
Executable: /home/tac/miniconda3/envs/normal/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 18.04.6
```
target `a.py`:
```python
print("hello world!")
```

nuitka command:
```bash
nuitka a.py
```
error output:
```
Nuitka-Options:INFO: Used command line options: a.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure that is intended.
Nuitka:INFO: Starting Python compilation with Nuitka '0.7.7' on Python '3.9' commercial None.
Nuitka:INFO: Completed Python level compilation and optimization.               
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.    
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program (no progress information available). 
/usr/bin/ld: /home/tac/miniconda3/envs/normal/lib/libpython3.9.a(abstract.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /home/tac/miniconda3/envs/normal/lib/libpython3.9.a(abstract.o): unable to initialize decompress status for section .debug_info
/home/tac/miniconda3/envs/normal/lib/libpython3.9.a: error adding symbols: File format not recognized
collect2: error: ld returned 1 exit status
```
> I've install libpython-static via command `conda install -c conda-forge libpython-static`

## question

Which part lead to this problem? I know adding an argument can skip this `libpython` part. But what if I want this feature enabled?

**Comment by kayhayen** [comment]
That's pretty bad. I wasn't aware, maybe Anaconda gcc is so old now the debug format is not supported anymore by winlibs gcc, in which case we would have to give up on it. I wonder if --mscc=latest would have to work there.

**Comment by kayhayen** [comment]
I am disabling static libpython for Windows Anaconda, it's basically unmaintained. Their gcc is stuck at 5.3.0 and will apparently never update, which is why we use winlibs. The static libpython is only providing DLL bindings, and it's unclear how much this helps anyway, maybe it did, but we no longer need to care it seems.

**Comment by r00t1900** [comment]
However, I got "please enable libpython if you are running under anaconda" under ubuntu, not windows. I've declared it in my nuitka version output. Why is that?

**Comment by kayhayen** [comment]
Ah, my bad, I misread that. I think this is a very similar issue likely. Try to use CondaCC, i.e. the gcc you can install through conda install, it would seem this could be the reverse situation, Ubuntu gcc being to old, and CondaCC producing too new one. Thanks for pointing out my oversight here. The symptom of mismatch is of course not limited to Windows.

On Linux, you actually want to use `libpython` for all reasons, performance, protection, distribution size, that is why the warning is very real.

I am assuming, that some sort of gcc version check needs to be added for Anaconda Python on Linux. Maybe `--condacc` should become an option and be required with too old gcc. I forgot how to install CondaCC though. Nuitka needs only the C compiler of it. I will have access to an Ubuntu 18.04 later this week, and will check things out there. There used to be a time when CondaCC was used on Windows, but like I said, no more. 

With LTO there is also something going on. If I am not mistaken CondaCC and system gcc are easily incompatible. Therefore the LTO linking is not enabled by default with Anaconda.

I would be grateful if you figured out what to conda install to get CondaCC installed. I think it is not the default, it wasn't on Windows at least.

**Comment by r00t1900** [comment]
That's very nice of you too, being so patient on this details. I would reply to it ASAP once I figure it out :)

**Comment by yzhuan** [comment]
> 

try `conna install gcc` and build it.

**Comment by kayhayen** [comment]
Part of the 0.9 release that I just made.

**Comment by Jackiexiao** [comment]
hi, so how to solve this problem, I have update nuitka to 0.9 but encounter same issue, should I install CondaCC ? @kayhayen

**Comment by kayhayen** [comment]
@Jackiexiao are you sure you have the same problem?

**Comment by Jackiexiao** [comment]
```
Nuitka-Scons:INFO: Backend linking program with 108 modules (no progress information available).
/usr/bin/ld: /data1/jackie/anaconda3/envs/frontend2.0/lib/libpython3.8.a(abstract.o): unable to initialize decompress status for section .debug_info
/data1/jackie/anaconda3/envs/frontend2.0/lib/libpython3.8.a: error adding symbols: File format not recognized
collect2: error: ld returned 1 exit status
scons: *** [/data1/jackie/zhuiyi/tts/frontend2.0/temp/temp.dist/temp] Error 1
Makefile:2: recipe for target 'compile' failed
make: *** [compile] Error 1
(frontend2.0) ➜  temp git:(v2.0) ✗ python3 -m nuitka --version
0.9
Commercial: None
Python: 3.8.12 (default, Oct 12 2021, 13:49:34)
Flavor: Anaconda Python
Executable: /data1/jackie/anaconda3/envs/frontend2.0/bin/python3
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 18.04.6
```

**Comment by kayhayen** [comment]
You are using a too old gcc, that is why. Nuitka doesn't pick up CondaCC unless it's installed. This apparently got closed, because of the unrelated Windows issue, where it shouldn*t be used at all.

**Comment by kayhayen** [comment]
The information I had been seeking, was that CondaCC is named `gcc_linux-64` on Linux. If you install that, maybe the issue already goes away. For me that set `CC` to point to a supported gcc, but as some people like to use it without an environment activately, also added automatic preference when Anaconda is running.

As an aside, with Anaconda-Python you can use any Linux you like, going to very old sysems is only needed if you use a self compiled Python or a Debian Python.

Now I need to check if we can enable LTO by default in this configuration, and make a similar change for macOS.

**Comment by Jackiexiao** [comment]
yep, the easiest way to upgrade gcc in anaconda is 
```
conda install gcc_linux-64
```
the installed gcc is named  `x86_64-conda-linux-gnu-gcc`, check gcc version using
```
x86_64-conda-linux-gnu-gcc --version
```

**Comment by kayhayen** [comment]
It's not necessarily an upgrade, but it's kind of making sure, it matches the `libpython` which is what this is mainly about.

So LTO is now enabled on macOS in any case, seems to work with all flavors with no issue, but with Anaconda it should give a nice performance boost.

The CondaCC on macOS is older than the one I have on not too new macOS, so that makes no sense, unless the same issue surfaces, but I think Clang is generally not breaking compatibilit for its bytecode as often as gcc.

So with that, I consider this one solved, just needs to hit releases now.

**Comment by kayhayen** [comment]
This is part of 1.0 release.

**Comment by r00t1900** [comment]
Such a bravo new.

**Comment by pyotyr** [comment]
For me this has worked sofar: 
conda install -c conda-forge libpython-static

**Comment by kayhayen** [comment]
I have added a dependency to the Anaconda package, that should make that need go away.

**Comment by xuzhuang1996** [comment]
> yep, the easiest way to upgrade gcc in anaconda is
> 
> ```
> conda install gcc_linux-64
> ```
> 
> the installed gcc is named `x86_64-conda-linux-gnu-gcc`, check gcc version using
> 
> ```
> x86_64-conda-linux-gnu-gcc --version
> ```

it works for me

**Comment by kayhayen** [comment]
What does --version output for you with these?
