### ISSUE TITLE
cannot load native module 'Crypto.Util._galois' when I run the .exe

### ISSUE THREAD

**Issue by devlenni** [Nuitka/Nuitka#1560]
Hello, if I want to start the .exe I get this error: cannot load native module 'Crypto.Util._galois'.
I also tried to install the Crypto package in the venv folder and more things. The only file which could have something todo with the _galois is called _galois.cp39-win_amd64.pyd file which is located in /site-packages/Crypto/Util.

**Comment by kayhayen** [comment]
No issue template, no fun.
