### ISSUE TITLE
Enhancement: generate a build project that is reusable

### ISSUE THREAD

**Issue by davidleon** [Nuitka/Nuitka#1561]
build project should allow static library linking. 3rd party libraries can be precompiled to a .a file or a .lib file. and the build project allows user to restart the building process of some weird access denied issues during compiling c source on windows(random failure of access, and if restart nuitka, the command 95% runs without problem, it's not likely a nuitka bug) without having to wait nuitka to rescan all the source files.

**Comment by kayhayen** [comment]
The access denied is actually a problem with `clcache` handling and improved on develop. Creating the project such that it can be statically executed without Nuitka, is making the support of all people who will fail to understand when they need to rebuild. Not interested really.
