### ISSUE TITLE
Compile seems to not include tkdnd package needed for tkinterdnd2

### ISSUE THREAD

**Issue by Izamii** [Nuitka/Nuitka#1562]
Nutika version: 

> 0.7.7
Commercial: None
Python: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\Steven\AppData\Local\Programs\Python\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

> nuitka and tkinterdnd2 were installed through pip install, on pip 22.1.

Target  ```Test.py```:

```python
from tkinterdnd2 import *

ws = TkinterDnD.Tk()

ws.mainloop()
```

Commands used: 
```
   python -m nuitka --follow-imports --standalone --enable-plugin=tk-inter Test.py
   python -m nuitka --follow-imports --onefile --enable-plugin=tk-inter Test.py
```

Compiling seems to work fine but when the .exe is opened it produces the following error:
```
Traceback (most recent call last):
  File "C:\Users\Steven\AppData\Local\Temp\ONEFIL~1\tkinterdnd2\TkinterDnD.py", line 53, in _require
_tkinter.TclError: can't find package tkdnd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Steven\AppData\Local\Temp\ONEFIL~1\Test.py", line 4, in <module>
    ws = TkinterDnD.Tk()
  File "C:\Users\Steven\AppData\Local\Temp\ONEFIL~1\tkinterdnd2\TkinterDnD.py", line 285, in __init__
  File "C:\Users\Steven\AppData\Local\Temp\ONEFIL~1\tkinterdnd2\TkinterDnD.py", line 55, in _require
RuntimeError: Unable to load tkdnd library.
```
This issue only happens when --standalone or --onefile is used, running a compile without them works completely fine and starts the .exe as intended.

I'm not quite sure why this error occurs, any insights on it would be welcome.

**Comment by kayhayen** [comment]
Accelerated mode loads installed modules, so anything not compiled will still be found.

**Comment by kayhayen** [comment]
This is on the factory branch.

I made several changes. First off, I made a change to anti-bloat configuration that in case of missing tkinter plugin will give a runtime error message that is more informative. More of these changes will come for plugins that need to be decided by the user.

Then, plugins now can provide package data, in this case, the path of the data needed is OS dependent, but this allows the tk-inter plugin to add package data for tkinterdnd2, but to also filter it for the OS directory. This ability should come in handy, e.g. when we enhance command line `--include-package-data` to allow for patterns of what should be included.

And then the DLL needed per platform is also added. This is still a bit manual, one day we should have an easy way to include DLLs of the current platform from the package listing.

With this, it works though, and tk-inter support has become nicer too.

**Comment by kayhayen** [comment]
Check it out from here: https://nuitka.net/doc/factory.html

**Comment by Izamii** [comment]
Hello Kay, thank you for the quick response and fix for the issue, I've tested around with it for a little bit and it seems to work wonderfully so far!

**Comment by kayhayen** [comment]
Part of the current pre-release on develop branch.

**Comment by kayhayen** [comment]
Part of 0.8 release that I just made.
