### ISSUE TITLE
[Question] Are there any goals to improve caching

### ISSUE THREAD

**Issue by WhoAteDaCake** [Nuitka/Nuitka#1569]
Hi, I'm sorry if this is not the best place to task, I was wondering if there was any plans to improve caching during the builds?

I've recently attempted to build one of my web services with nuitka and it took around 45mins, which I'm not too bothered about, but when trying to re-compile it, it didn't have any speed up at all.

I've seen that ccache is used, but does it do any work during the first pass?

Thanks so much for all your work!

**Comment by kayhayen** [comment]
When people help with implementing caching, it will be sooner, the goal exists.
