### ISSUE TITLE
Would it be possible to use the clang in MSYS2 or MinGW to compile?

### ISSUE THREAD

**Issue by wszqkzqk** [Nuitka/Nuitka#1572]
When I add `--mingw` it just calls gcc and when I add `--clang` it calls cl-clang, can it call clang in MSYS2 or MinGW to compile?

**Comment by kayhayen** [comment]
The solution is ridiculous, I admit, use both, i.e. `--ming --clang`. The compiler options shall one day be reformed, but that day has not yet come.

I found that current winlibs doesn't support LTO (yet), so I didn't care much about exposing it.

**Comment by wszqkzqk** [comment]
> The solution is ridiculous, I admit, use both, i.e. `--ming --clang`. The compiler options shall one day be reformed, but that day has not yet come.
> 
> I found that current winlibs doesn't support LTO (yet), so I didn't care much about exposing it.

OK, Thank you so much!

**Comment by wszqkzqk** [comment]
> The solution is ridiculous, I admit, use both, i.e. `--ming --clang`. The compiler options shall one day be reformed, but that day has not yet come.
> 
> I found that current winlibs doesn't support LTO (yet), so I didn't care much about exposing it.

```powershell
AssertionError: (b'', b'clang: error: no input files\r\n'):
  File "C:\Users\17265\AppData\Local\Programs\Python\PYTHON~1\lib\SITE-P~1\nuitka\build\BACKEN~1.SCO", line 377:
    env = checkWindowsCompilerFound(
  File "C:\Users\17265\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\build\SconsCompilerSettings.py", line 215:
    decision, linker_arch, compiler_arch = decideArchMismatch(
  File "C:\Users\17265\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\build\SconsUtils.py", line 599:
    compiler_arch = getCompilerArch(
  File "C:\Users\17265\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\build\SconsUtils.py", line 590:
    assert False, (stdout, stderr)
```

It seems that Nuitka treated `clang` under `mingw` as `cl` mode, and failed with this mistake

Version INFO:
```
0.8
Commercial: None
Python: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\17265\AppData\Local\Programs\Python\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

**Comment by kayhayen** [comment]
Well, maybe it regressed after I lost interest. I will check it out once I update winlibs, which is actually something I promised to do for 0.8.1, but not sure if I can cover clang there. I would definitely want to retry for LTO.

**Comment by kayhayen** [comment]
This just worked for me, no problem. Maybe it's not clear to you, that you cannot use --clang and use your own Clang on Windows, that's not going to work. It will work with the one from MinGW64 or MSVC only (Clang component). Using a Clang install on Windows is not supported, as it needs help with the Windows SDK.
