### ISSUE TITLE
Install/Upgrade to Nuitka 8.0/8.1 fails - zip_safe missing

### ISSUE THREAD

**Issue by David-Worboys** [Nuitka/Nuitka#1573]
- Attempted to upgrade to latest Nuitka and I got the  following error.  
- Deleted Nutika and attempted to reinstall and got the same error.

- Other python libraries do not have this issue

**OS: Debian 11 bullseye**
**Python 3.10.4**

pip install -U Nuitka==0.8.1
Collecting Nuitka==0.8.1
  Using cached Nuitka-0.8.1.tar.gz (3.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      /home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'zip_safe'
        warnings.warn(msg)
      /home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'entry_points'
        warnings.warn(msg)
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
      
      error: invalid command 'egg_info'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by David-Worboys** [comment]
Whoops forgot this bit:

 python -m pip freeze
appdirs==1.4.4
astroid==2.11.5
black==22.3.0
boto3-stubs==1.23.5
botocore-stubs==1.26.5
BTrees==4.10.0
certifi==2022.5.18.1
cffi==1.15.0
charset-normalizer==2.0.12
click==8.1.3
colorama==0.4.4
commonmark==0.9.1
ConfigUpdater==3.1
crypto==1.4.1
dill==0.3.5.1
dlib==19.24.99
fs==2.4.16
idna==3.3
isort==5.10.1
Jinja2==3.1.2
lazy-object-proxy==1.7.1
MarkupSafe==2.1.1
mccabe==0.7.0
memray==1.1.0
mypy==0.950
mypy-boto3-ec2==1.23.0.post1
mypy-boto3-s3==1.23.0.post1
mypy-extensions==0.4.3
Naked==0.1.31
netifaces==0.11.0
numpy==1.22.4
pathspec==0.9.0
pathvalidate==2.5.0
perfmetrics==3.2.0.post0
persistent==4.9.0
platformdirs==2.5.2
psutil==5.9.1
pycparser==2.21
pycryptodome==3.14.1
Pygments==2.12.0
pylint==2.13.9
PySide6==6.3.0
PySide6-Addons==6.3.0
PySide6-Essentials==6.3.0
pysqlite3==0.4.7
python-dateutil==2.8.2
pytz==2022.1
PyYAML==6.0
RelStorage==3.4.5
requests==2.27.1
rich==12.4.2
shellescape==3.8.1
shiboken6==6.3.0
simplejson==3.17.6
six==1.16.0
toml==0.10.2
tomli==2.0.1
transaction==3.0.1
types-backports==0.1.3
types-python-dateutil==2.8.16
types-pytz==2021.3.8
types-setuptools==57.4.15
types-simplejson==3.17.6
types-six==1.16.15
typing_extensions==4.2.0
urllib3==1.26.9
wrapt==1.14.1
xmltodict==0.13.0
zc.lockfile==2.0
ZConfig==3.6.0
ZODB==5.7.0
zodbpickle==2.3
zope.dottedname==4.3
zope.interface==5.4.0

**Comment by kayhayen** [comment]
Seems something funny has been done with `setuptools` to not have these option `entry_points` anymore. I don't think you will be able to install any version of Nuitka with it now?

**Comment by kayhayen** [comment]
The setuptools version is hidden from freeze output unfortunately, Please provide this commands output

`python -c "import setuptools; print(setuptools.__version__)"`

**Comment by David-Worboys** [comment]
Hi Kay, as requested:

 python -c "import setuptools; print(setuptools.__version__)"
62.3.2

I will try and install an earlier Nuitka version and let you know

**Comment by David-Worboys** [comment]
And I cannot install Nuitka 7 either - which I have previously done so...so setuptools is broke I guess

**Comment by kayhayen** [comment]
In which way did you create the virtualenv there?

**Comment by kayhayen** [comment]
I don't know why the venv bit is not part of the original report.

```
 A  hayen@anna: ~/test$ python3 -m venv install_test
 A  hayen@anna: ~/test$ cd install_test
 A  hayen@anna: ~/test/install_test$ ls -l
total 20
drwxr-xr-x 2 hayen hayen 4096 May 25 16:03 bin
drwxr-xr-x 2 hayen hayen 4096 May 25 16:03 include
drwxr-xr-x 3 hayen hayen 4096 May 25 16:03 lib
lrwxrwxrwx 1 hayen hayen    3 May 25 16:03 lib64 -> lib
-rw-r--r-- 1 hayen hayen   69 May 25 16:03 pyvenv.cfg
drwxr-xr-x 3 hayen hayen 4096 May 25 16:03 share
 A  hayen@anna: ~/test/install_test$ . bin/activate
(install_test)  A  hayen@anna: ~/test/install_test$ python -m pip install nuitka
Collecting nuitka
  Downloading Nuitka-0.8.1.tar.gz (3.8 MB)
     |████████████████████████████████| 3.8 MB 5.3 MB/s 
Using legacy 'setup.py install' for nuitka, since package 'wheel' is not installed.
Installing collected packages: nuitka
    Running setup.py install for nuitka ... done
Successfully installed nuitka-0.8.1
(install_test)  A  hayen@anna: ~/test/install_test$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

It's working just fine for me. So question becomes if anything you did install before in that venv changed setuptools for the worse.

**Comment by David-Worboys** [comment]
Sorry about the venv bit Kay - kind of the background of life and I forget about it as it just works.

I downgraded setuptools to 62.3.0 and Nuitka install worked! 
I upgraded to seetuptools 62.3.2 and Nuitka install failed

So I have a work around but something has changed with setuptools

**Comment by David-Worboys** [comment]
And I just tried installing geonames and same behavior:

setuptools 62.3.0 works
setuptools 62.3.2 fails

The finger is really pointing at a setuptools change being root cause

**Comment by kayhayen** [comment]
It seems that `setuptools-62.3.2` works fine for me. Maybe a strange case of corruption on your side.

**Comment by David-Worboys** [comment]
Definitely an odd one...I will put this on the shelf until the next python release and then I will make a new venv and see if it works....

**Comment by David-Worboys** [comment]
Just to close this off..I rebuilt my dev environment and the problem went away.
