### ISSUE TITLE
Process exits immediately

### ISSUE THREAD

**Issue by kroese** [Nuitka/Nuitka#1574]
**Nuitka 0.8.1 on Win11 (Python: 3.10.4)**

When I compile my script using: 

`python -m nuitka --onefile --enable-plugin=numpy .\script.py`

It finishes without any errors, but when I run the resulting .exe it says:

`[process exited with code 3221225477 (0xc0000005)]`

How can I track down why this .exe doesn't work?

**Comment by kayhayen** [comment]
No issue template no fun
