### ISSUE TITLE
Can I use nuitka to compile python code to a C++ library?

### ISSUE THREAD

**Issue by ItsCubeTime** [Nuitka/Nuitka#1575]
Hi, Im making a plugin for Unreal Engine and find that the API it provides is a little insufficient for my needs, rather than go dig in C++ libraries I figured it would be easier to write the additional OS inoperability code in Python and expose that to my C++ code, looking for the most development friendly approach to now achieve this (performance is not super crucial, but still matters to the extend that I want to be able to make at least 30 calls or so per second).

Can nuitka help me with this? Ideally I would like to be able to call individual Python functions from C++ code and get return values _without_ the dependency on a Python interpreter being installed on the system using it.

**Comment by kayhayen** [comment]
This has been addressed elsewhere, basically you need to embed Python. Once you have that working, Nuitka can compile your Python code. It doesn't do that for you yet.
