### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 192: illegal multibyte sequence

### ISSUE THREAD

**Issue by JiaPai12138** [Nuitka/Nuitka#1576]
* Version
0.8.1
Commercial: None
Python: 3.9.12 [MSC v.1929 64 bit (AMD64)]
OS: Windows
Arch: x86_64
WindowsRelease: 10

* How did you install Nuitka and Python
Install Python from https://www.python.org/
Install Nuitka using pip install Nuitka -U
Update from version 0.7.7 to 0.8.x
Not installed in virtualenv

* The specific PyPI names and versions
pip 22.1

* Problem: Errors in packing using command
python -m nuitka --mingw64 --module --warn-implicit-exceptions --show-progress --remove-output --warn-implicit-exceptions sample.py

Nuitka-Scons:INFO: Backend linking program (no progress information available).
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\nuitka\__main__.py", line 137, in <module>
    main()
  File "D:\Python39\lib\site-packages\nuitka\__main__.py", line 123, in main
    MainControl.main()
  File "D:\Python39\lib\site-packages\nuitka\MainControl.py", line 942, in main
    result, options = compileTree()
  File "D:\Python39\lib\site-packages\nuitka\MainControl.py", line 858, in compileTree
    result, options = runSconsBackend(quiet=not Options.isShowScons())
  File "D:\Python39\lib\site-packages\nuitka\MainControl.py", line 696, in runSconsBackend
    SconsInterface.runScons(
  File "D:\Python39\lib\site-packages\nuitka\build\SconsInterface.py", line 284, in runScons
    checkCachingSuccess(source_dir or options["source_dir"])
  File "D:\Python39\lib\site-packages\nuitka\build\SconsCaching.py", line 335, in checkCachingSuccess
    ccache_logfile = getSconsReportValue(source_dir=source_dir, key="CCACHE_LOGFILE")
  File "D:\Python39\lib\site-packages\nuitka\build\SconsUtils.py", line 338, in getSconsReportValue
    return readSconsReport(source_dir).get(key)
  File "D:\Python39\lib\site-packages\nuitka\build\SconsUtils.py", line 324, in readSconsReport
    for line in getFileContentByLine(os.path.join(source_dir, "scons-report.txt")):
  File "D:\Python39\lib\site-packages\nuitka\utils\FileOperations.py", line 531, in getFileContentByLine
    return getFileContents(filename, mode, encoding=encoding).splitlines()
  File "D:\Python39\lib\site-packages\nuitka\utils\FileOperations.py", line 549, in getFileContents
    return f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 192: illegal multibyte sequence

* Sample code to pack
`import time
def get_time():
print(time.time())
`

* Note if this is a regression
Everything worked fine before Nuitka version 0.8.0

* Consider getting commercial support
About to

**Comment by JiaPai12138** [comment]
python -m pip freeze
absl-py==1.0.0
ahk==0.13.0
altgraph==0.17.2
appdirs==1.4.4
asgiref==3.4.1
astunparse==1.6.3
async-generator==1.10
async-timeout==4.0.2
atomicwrites==1.4.0
attrs==21.2.0
auto-py-to-exe==2.18.2
Automat==20.2.0
backports.shutil-get-terminal-size==1.0.0
bcrypt==3.2.0
bezier==2021.2.12
blinker==1.4
boto3==1.20.26
botocore==1.23.26
bottle==0.12.19
bottle-websocket==0.2.9
Brotli==1.0.9
bsdiff4==1.2.1
cachetools==5.0.0
Cerberus==1.3.4
certifi==2022.5.18.1
cffi==1.15.0
chardet==4.0.0
charset-normalizer==2.0.12
click==7.1.2
cocos2d==0.6.9
colorama==0.4.4
commonmark==0.9.1
comtypes==1.1.11
configparser==5.2.0
constantly==15.1.0
cryptography==37.0.2
cssselect==1.1.0
cupy-cuda102==10.4.0
cupy-cuda114==10.4.0
cx-Freeze==6.10
cx-Logging==3.0
cycler==0.11.0
Cython==0.29.30
Deprecated==1.2.13
dsdev-utils==1.3.0
ed25519==1.5
Eel==0.12.4
fastrlock==0.8
filelock==3.6.0
Flask==2.0.3
flatbuffers==2.0
fonttools==4.28.5
freetype-py==2.2.0
future==0.18.2
gast==0.4.0
gevent==21.12.0
gevent-websocket==0.10.1
glfw==2.5.0
google-auth==2.6.2
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
GPUtil==1.4.0
greenlet==1.1.2
grpcio==1.43.0
h11==0.12.0
h2==4.1.0
h5py==3.6.0
hpack==4.0.0
hyperframe==6.0.1
hyperlink==21.0.0
idna==3.3
imgui==1.4.1
imgviz==1.5.0
importlib-metadata==4.10.0
incremental==21.3.0
iniconfig==1.1.1
injector==0.19.0
Interface==2.11.1
itemadapter==0.4.0
itemloaders==1.0.4
itsdangerous==2.1.2
Jinja2==3.1.1
jmespath==0.10.0
joblib==1.1.0
jsonschema==4.4.0
kaitaistruct==0.9
keras==2.8.0
Keras-Preprocessing==1.1.2
kiwisolver==1.4.2
koila==0.1.1
labelImg==1.8.6
labelme==5.0.1
ldap3==2.9.1
libclang==12.0.0
lief==0.11.5
llvmlite==0.38.1
loguru==0.6.0
lxml==4.8.0
Mako==1.1.6
Markdown==3.3.6
MarkupSafe==2.0.1
matplotlib==3.2.2
mitmdump==1.1.2
more-itertools==8.12.0
MouseInfo==0.1.3
mpmath==1.2.1
msgpack==1.0.3
mss==6.1.0
natsort==8.1.0
netron==5.7.1
ntplib==0.4.0
Nuitka==0.8.1
numba==0.55.1
numpy==1.21.6
nvidia-ml-py==11.515.0
oauthlib==3.2.0
onnx==1.10.2
onnx-simplifier==0.3.8
onnxconverter-common==1.9.0
onnxmltools==1.10.0
onnxoptimizer==0.2.6
onnxruntime-directml==1.10.0
opencv==4.5.5
opencv-python==4.5.5.64
opt-einsum==3.3.0
ordered-set==4.1.0
outcome==1.1.0
packaging==21.3
pandas==1.4.0
paramiko==2.9.1
parsel==1.6.0
passlib==1.7.4
pbr==5.8.0
pefile==2021.9.3
Pillow==9.1.1
platformdirs==2.5.0
play-mp3==0.0.1
playsound==1.3.0
pluggy==1.0.0
priority==2.0.0
Protego==0.1.16
protobuf==3.18.1
psutil==5.9.1
publicsuffix2==2.20191221
py==1.11.0
pyadl==0.1
pyarmor==7.4.3
pyarmor-webui==1.3.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
PyAutoGUI==0.9.53
pybind11==2.9.2
pycocotools==2.0.4
pycparser==2.21
pycryptodome==3.14.1
pycuda==2021.1
PyDispatcher==2.0.5
pydivert==2.1.0
pydub==0.25.1
pygame==2.1.2
PyGetWindow==0.0.9
pyglet==1.5.21
Pygments==2.11.2
pyinstaller==5.1
pyinstaller-hooks-contrib==2022.5
PyMsgBox==1.0.9
PyNaCl==1.4.0
pynput==1.7.6
pynvml==11.4.1
pyobfuscate==0.3
PyOpenGL==3.1.6
pyOpenSSL==22.0.0
pyparsing==3.0.8
pyperclip==1.8.2
PyQt5==5.15.4
pyqt5-plugins==5.15.4.2.2
PyQt5-Qt5==5.15.2
PyQt5-sip==12.9.0
pyqt5-tools==5.15.4.3.2
PyQt6==6.3.0
PyQt6-Qt6==6.3.0
PyQt6-sip==13.3.1
PyRect==0.1.4
pyrsistent==0.18.1
PyScreeze==0.1.28
PySDL2==0.9.9
pyserial==3.5
PySocks==1.7.1
pytest==7.0.1
python-dateutil==2.8.2
python-dotenv==0.19.2
python-vlc==3.0.12118
PythonForWindows==0.6.5
pytools==2022.1.3
pytweening==1.0.4
pytz==2021.3
PyUpdater==4.0
PyUpdater-S3-Plugin==4.1.2
PyUpdater-SCP-Plugin==4.0.3
pyvirtualcam==0.9.1
pywin32==304
pywin32-ctypes==0.2.0
PyYAML==6.0
qt5-applications==5.15.2.2.2
qt5-tools==5.15.2.1.2
QtPy==2.1.0
queuelib==1.6.2
ray==1.11.0
redis==4.2.2
reprint==0.6.0
requests==2.27.1
requests-file==1.5.1
requests-oauthlib==1.3.1
rich==12.2.0
rsa==4.8
ruamel.yaml==0.17.16
ruamel.yaml.clib==0.2.6
s3transfer==0.5.0
scikit-learn==1.0.2
scipy==1.7.3
scp==0.14.2
Scrapy==2.6.1
seaborn==0.11.2
selenium==4.1.2
service-identity==21.1.0
setproctitle==1.2.2
setuptools-scm==6.4.2
simple-pid==1.0.1
six==1.16.0
skl2onnx==1.10.4
smartPID==1.0
sniffio==1.2.0
sortedcontainers==2.4.0
sounddevice==0.4.3
spark-parser==1.8.9
stevedore==3.5.0
sympy==1.9
tabulate==0.8.9
tensorboard==2.8.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorflow-estimator==2.7.0
tensorflow-gpu==2.8.0
tensorflow-io-gcs-filesystem==0.23.1
termcolor==1.1.0
tf-estimator-nightly==2.8.0.dev2021122109
thop==0.0.31.post2005241907
threadpoolctl==3.1.0
tinyaes==1.0.3
tldextract==3.2.0
toml==0.10.2
tomli==2.0.0
torch==1.10.2+cu113
torch2trt==0.3.0
torchaudio==0.10.2+cu113
torchvision==0.11.3+cu113
tornado==6.1
tqdm==4.64.0
trio==0.20.0
trio-websocket==0.9.2
trtpy==1.2.6
Twisted==22.4.0
twisted-iocpsupport==1.0.2
typing_extensions==4.2.0
uncompyle6==3.8.0
urllib3==1.26.9
urwid==2.1.2
vboxapi==1.0
w3lib==1.22.0
Werkzeug==2.0.2
whichcraft==0.6.1
win32-setctime==1.1.0
winput==1.4.0
WMI==1.5.1
wrapt==1.13.3
wres==1.0.3
wsproto==1.1.0
wxPython==4.1.1
xdis==6.0.3
zipp==3.8.0
zope.event==4.5.0
zope.interface==5.4.0
zope.schema==6.2.0
zstandard==0.15.2

**Comment by kayhayen** [comment]
What is the `gbk` codec, I don't know, but this is an extension of a previous bug, where the Scons report could not be written due to encoding issues, which I never reproduced. I can make the fix based on this information though.

**Comment by kayhayen** [comment]
This is fixed on the factory branch https://nuitka.net/doc/factory.html

**Comment by JiaPai12138** [comment]
Thanks, that works

**Comment by kayhayen** [comment]
Part of 0.8.2 release.
