### ISSUE TITLE
Adding Documentation Notice for Spawn Incompatibility

### ISSUE THREAD

**Issue by hishamyousry** [Nuitka/Nuitka#1581]
I have a Python script that uses multiprocessing to spawn processes. When I used Nuitka to create a binary with it (using --onefile) I was getting this error message: 

`/tmp/.mount_vsiSima4Iye5/multiprocessing/resource_tracker.py:96: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.`

After investigating for a couple of days, I finally found this warning in the [multiprocessing documentation](https://docs.python.org/3/library/multiprocessing.html):

> Warning The 'spawn' and 'forkserver' start methods cannot currently be used with “frozen” executables (i.e., binaries produced by packages like PyInstaller and cx_Freeze) on Unix. The 'fork' start method does work.

After replacing "spawn" with "fork", everything works fine.

It seems that this is a limitation from the multiprocessing library itself, but I am suggesting adding a note of it in the "Typical Problems" section documentation to save users some debugging time.

Info about my environment:
Python 3.8.2
OS: RedHat 7.6
Nuitka Versions that produced this issue: 0.7.7, 0.8, 0.9rc1

If this is however not a known limitation and is not expected to occur, please let me know so that I can give you more information about the issue that I have seen.

**Comment by kayhayen** [comment]
Not so sure of that though, of tests it work fine. You failed to give a reproducer, assuming you used it wrongly somehow without revealing sufficient information.

This works perfectly:

```
import multiprocessing as mp
import os


def f(name):
    print("hello", name)


if __name__ == "__main__":
    ctx = mp.get_context("spawn")
    p = ctx.Process(target=f, args=("test",))
    p.start()
    p.join()
```

Nuitka is more compatible than the other tools mentioned.

**Comment by hishamyousry** [comment]
Ok well if this is expected to work, then I will provide more information so that you can reproduce the issue.

In fact, you can use the same code that you provided to reproduce it. The issue mainly comes when you add the binary path to your PATH environment variable so that you can use it directly in the shell.

Steps to reproduce:
1. Create a --onefile executable of the provided code.
2. Open another shell at a different location
3. Add /path/to/Binary to your PATH environment variable:
     on csh: setenv PATH /path/to/binary:$PATH
     on bash export PATH=/path/to/binary:$PATH
4. Call the binary directly by its name
Here you would expect to see the "hello test" message. In fact, no output is shown. If you run the binary using its absolute or relative path it will run correctly, and if you replace "spawn" with "fork" it will also work correctly. The only case that doesn't work is if you call the binary from the PATH variable directly.

**Comment by kayhayen** [comment]
Can you try with `--onefile-tempdir`, I suspect this might be going away if you did.

**Comment by hishamyousry** [comment]
The issue persists after adding this option.

By the way, what does this option do? I can't find it when using "nuikta --help"?

**Comment by kayhayen** [comment]
The way onefile works on Linux is different from other OSes, but it is going away once cached execution becomes a thing. It has caused issues in the past too.

So it seems that somewhere there should be an absolute path should be used, but is not.
