### ISSUE TITLE
How to decompile .exe

### ISSUE THREAD

**Issue by PandoricGalaxy** [Nuitka/Nuitka#1582]
I had convertied a .py file to .exe using nuitka.
However i forgot what code was in it and i really need to know it!
Is there a way to decompile the .exe back to .py?

**Comment by kayhayen** [comment]
No, unfortunately not. If you didn't use Nuitka commercial, you may find some of the data in the binary file, with commercial even that would be hard.

**Comment by kkava** [comment]
Good. I'm glad it isn't easy to decompile, that's one of the features I was looking for. I've just donated to the project - thank you.

**Comment by PandoricGalaxy** [comment]
> Good. I'm glad it isn't easy to decompile, that's one of the features I was looking for. I've just donated to the project - thank you.

I did find a program claiming to decompile it and show code but don't remember where since I didnt need it that time
