### ISSUE TITLE
Failed to include-data-dir for onefile on Windows

### ISSUE THREAD

**Issue by 12Tall** [Nuitka/Nuitka#1583]
When I was trying to compile app.py to standalone, Nuitka will copy `./static` folder to `app.dist/static2` sutomatically, and the output exe file works great. But after `--onefile` option added, the onefile version `app.exe` cannot find the `./stactic2` folder, and no `static2` folder was copied to the `app.exe` directory. Is there any way to solve this problem, or I have to copy the static folder along with the onefile `app.exe` manually?

* Provide in your issue the Nuitka options used
  > py -3.8 -m nuitka  ./app.py --standalone --onefile --output-dir=out --plugin-enable=pywebview --include-data-dir=static=static2

* Nuitka version  
  > python -m nuitka --version 
  > 0.8.2
  > Commercial: None
  > Python: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
  > Flavor: Unknown
  > Executable: C:\Program Files\Python38\python.exe
  > OS: Windows
  > Arch: x86_64
  > WindowsRelease: 10

* How did you install Nuitka and Python

  > pip and exe installer

* The specific PyPI names and versions

  > python -m pip freeze
  > Nuitka==0.8.2                            
  > proxy-tools==0.1.0
  > pycparser==2.21
  > pythonnet==2.5.2
  > pywebview==3.6.3

![image](https://user-images.githubusercontent.com/29416757/170718489-599c82d9-2c5b-421f-a039-67086e909950.png)

![image](https://user-images.githubusercontent.com/29416757/170718653-77bfd3f4-f8af-4dca-b7bd-de2fe42be377.png)

**Comment by kayhayen** [comment]
Yes, it is described in the user manual how this addressed. https://nuitka.net/doc/user-manual.html#onefile-finding-files
