### ISSUE TITLE
The visualization window generated on macOS becomes very fuzzy. 

### ISSUE THREAD

**Issue by malizheng** [Nuitka/Nuitka#1585]
The visualization window generated on macOS becomes very fuzzy, and how to solve it? 
```
0.8.2
Commercial: None
Python: 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) 
Flavor: CPython Official
Executable: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3
OS: Darwin
```

* How did you install Nuitka and Python
pip3 install Nuitka==0.8.2

<img width="202" alt="1b7a3640-fa4a-4340-b8ff-8566d571ffd2" src="https://user-images.githubusercontent.com/14052596/170813539-b7846711-9d6a-42ea-9ae2-08fae39dfcdf.png">

**Comment by kayhayen** [comment]
No reproducer, no fun.

**Comment by malizheng** [comment]
`# _*_ coding:utf-8 _*_
import sys
from PySide6 import QtGui
from PySide6 import QtWidgets
from PySide6.QtWidgets import *
import os


class TableWidget(QWidget):

    def __init__(self,*args, **kwargs):
        super(TableWidget, self).__init__(*args, **kwargs)
        self.edit_cell=False
        self.rows=0
        self.__init_ui()

    def __init_ui(self):
        self.table = QTableWidget(1,2) 
        self.table.setHorizontalHeaderLabels(('test1','test2'))
        self.table.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.__layout = QVBoxLayout()
        self.__layout.addWidget(self.table)
        self.setLayout(self.__layout)
        self.table.setItem(0, 0, QTableWidgetItem("test3")) 
        self.table.setItem(0, 1, QTableWidgetItem("test4")) 
        control_layout = QHBoxLayout()
        self.nameText = QLineEdit()
        self.nameText.setPlaceholderText("QLineEdit") 
        control_layout.addStretch(1)
        control_layout.addWidget(self.nameText)
        self.__layout.addLayout(control_layout)


class TestWindow(QMainWindow):
    def __init__(self):
        super(TestWindow,self).__init__()
        self.__init_ui()

    def __init_ui(self):
        self.resize(300, 300)
        self.setWindowTitle("Table title")
        self.table_widget = TableWidget()
        self.setCentralWidget(self.table_widget)

if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = TestWindow()
    window.show()
    sys.exit(app.exec())`

<img width="299" alt="20220528-165748@2x" src="https://user-images.githubusercontent.com/14052596/170818516-9b1f83f7-b0f1-4bca-8b1f-4924edd3095f.png">

Windows became very fuzzy and QLineEdit also failed to enter.

**Comment by kayhayen** [comment]
Actually, I assume Nuitka was giving you the warning,  I assume to do that. On macOS, console applications do not have high resolution. Maybe the warning message for disabling console must be improved.
