### ISSUE TITLE
Windows: Clang from MingW-w64(MSYS2) failed

### ISSUE THREAD

**Issue by wszqkzqk** [Nuitka/Nuitka#1588]
Version info:
``` powershell
0.8.3
Commercial: None
Python: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\17265\AppData\Local\Programs\Python\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```
Command:
`nuitka --mingw64 --clang --standalone --onefile --show-progress --show-memory --output-dir=out F:\testandbuild\pyfiles\computeTestPy.py`

Error output:
```
AssertionError: (b'', b'clang: error: no input files\r\n'):
  File "C:\Users\17265\AppData\Local\Programs\Python\PYTHON~1\lib\SITE-P~1\nuitka\build\BACKEN~1.SCO", line 377:
    env = checkWindowsCompilerFound(
  File "C:\Users\17265\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\build\SconsCompilerSettings.py", line 215:
    decision, linker_arch, compiler_arch = decideArchMismatch(
  File "C:\Users\17265\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\build\SconsUtils.py", line 598:
    compiler_arch = getCompilerArch(
  File "C:\Users\17265\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\build\SconsUtils.py", line 589:
    assert False, (stdout, stderr)
```

The statement `File "C:\Users\17265\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\build\SconsUtils.py", line 589: assert False, (stdout, stderr)` will only execute with `msvc_mode`, but my compile flag is `--mingw64`, that might be the problem.

And the command to get the architecture of clang from mingw-w64 is `X:/xxxPath/clang.exe -v` or `X:/xxxPath/clang.exe --version`, but the output `AssertionError: (b'', b'clang: error: no input files\r\n'):` showed it might just run `X:/xxxPath/clang.exe` and failed.

**Comment by kayhayen** [comment]
So, in my case, it searches `clang` and doesn't find it, in your case, it does. You may have a Clang.exe in your `PATH`, where mine is fed later by defaulting to downloaded gcc, then doing

```
            if clang_mode:
                env["CC"] = os.path.join(os.path.dirname(compiler_path), "clang.exe")
```

That is why I never see it. Question is of course, if using `clang` from `PATH` is a good idea. I do not want to rule it out, and might try downloading LLVM later.

**Comment by kayhayen** [comment]
I was not getting C compile time errors with the LLVM that I happened to have, and used for testing now (making a few more touch ups), but it didn't support some linker options.

I am absolutely not sure the MSYS2 clang will work if not used by the MSYS2 python. In that case, it's supposed to use their gcc and clang I think, and that is what is supported. Using it from the outside, which it seems like, judging by your flavor not being recognized, I am not sure if it can work, but you can give it a try, may just as well.

**Comment by wszqkzqk** [comment]
> There are two forms of clang in there, are there not? One I think is more geared towards "mingw" like build, and one more towards "posix" like build. The first one probably could work indeed.

Yes, actually I only tested the “mingw” one(from ucrt64. mingw64, and clang64 repo ), and the “posix” one is not recommended to be used to build local applications.

**Comment by kayhayen** [comment]
And then it fails with LTO in precisely the same way as winlibs, claiming that "LLVM IR bitcode" is an unknown object format.

**Comment by wszqkzqk** [comment]
> The original LLVM fails many linker options that appear important, e.g. stack size, but maybe are just different, then needs different link libraries, and then fails to find `SetDllDirectory` which is strange, but I found that is useless code anyway, so that could be removed, then it ran fine.

There are [3 x64 environments in MSYS2 for naitive x64 application building](https://www.msys2.org/docs/environments/). GCC in ucrt64 and mingw64 can pass the check process while GCC in clang64 fials(can not correctly detect the arch of compiler), and all Clang compilers can't pass the check process. All above compilers work well as long as skip the compile check process by editing Nuitka's code.

**Comment by kayhayen** [comment]
I have enhanced it on factory branch though: https://nuitka.net/doc/factory.html

It wasn't considering clang, gcc, and msvc, now it will. I could clang from PATH, but it seems it wasn't going to work for LLVM download, didn't try MSYS2 yet, but I recall clang worked from within MSYS2, but I might be wrong or outdated, ought to do it now though.

**Comment by kayhayen** [comment]
Part of the current pre-release.
