### ISSUE TITLE
Add possibility to run Nuitka from Python code

### ISSUE THREAD

**Issue by sebastian-szurlej** [Nuitka/Nuitka#1592]
Right now one can run Nuitka throught the terminal using nuitka command and with specified flags. I think it would be great to have the possibility to run it from the Python script like we can do in PyInstaller:
[https://pyinstaller.org/en/stable/usage.html#running-pyinstaller-from-python-code](url)

    import PyInstaller.__main__
    
    PyInstaller.__main__.run([
        'my_script.py',
        '--onefile',
        '--windowed'
    ])

Or maybe it is possible, but I am not aware of. And this is, of course, rather enhancement than issue.

**Comment by psydox** [comment]
In our company, I wrote a simple python script to run the Nuitka build process which I named "build_nuitka.py".  The script I wrote handles the versioning (using CalVer) automatically and copies all required files in the distribution directory.  Before this script, a batch file is used to automate the Nuitka build process, but it is not as flexible as the Python build script version.  I run the build process just by running the build script: python build_nuitka.py

It's probably not the one you are looking for but it may help you a bit, so here is the script I wrote:

`########################################################################################
# PACKAGES / MODULES                                                                   #
########################################################################################

import os
import subprocess
import shutil
from datetime import datetime

########################################################################################
# SETTINGS                                                                             #
########################################################################################

# APP INFORMATION (EDITABLE)
APP_NAME            = "APP_NAME_HERE"
APP_ICON            = f"./res/icon/{APP_NAME}.ico"
OUTPUT_DIRECTORY    = "./build/nuitka"

# PRODUCT INFORMATION (EDITABLE)
PRODUCT_NAME        = "PRODUCT NAME HERE"
PRODUCT_VERSION     = "1.0"

# COMPANY INFORMATION (EDITABLE)
COMPANY_NAME        = "COMPANY NAME INC."

########################################################################################
# STOP! DO NOT EDIT BELOW THIS LINE! ONLY EDIT IF NEEDED TO!                           #
########################################################################################

if __name__ == "__main__":

    # Automatically Generate Application Version
    APP_VERSION = datetime.today().strftime('%Y.%m.%d')

    # Automatically Generate Application Build
    APP_BUILD   = datetime.today().strftime('%H%M') 

    # Compiled Folder Name
    FOLDER_NAME = f"{APP_NAME} v{APP_VERSION} (Build {APP_BUILD})"

    # Compose the Command.
    # Note: Do not remove the " " before the the parameters.
    BUILD_COMMAND  =       f"python -m nuitka "
    BUILD_COMMAND += " " + f"--standalone"
    BUILD_COMMAND += " " + f"--follow-imports"
    BUILD_COMMAND += " " + f"--run"
    BUILD_COMMAND += " " + f"--debugger"
    BUILD_COMMAND += " " + f"--python-flag=no_site"
    BUILD_COMMAND += " " + f"--warn-implicit-exceptions"
    BUILD_COMMAND += " " + f"--warn-unusual-code"
    BUILD_COMMAND += " " + f"--assume-yes-for-downloads"
    BUILD_COMMAND += " " + f"--include-package=win32"
    BUILD_COMMAND += " " + f"--enable-plugin=numpy"
    BUILD_COMMAND += " " + f"--output-dir=\"{OUTPUT_DIRECTORY}\""
    BUILD_COMMAND += " " + f"--remove-output"
    # BUILD_COMMAND += " " + f"--jobs=4"
    BUILD_COMMAND += " " + f"--windows-icon-from-ico=\"{APP_ICON}\""
    BUILD_COMMAND += " " + f"--windows-company-name=\"{COMPANY_NAME}\""
    BUILD_COMMAND += " " + f"--windows-product-name=\"{PRODUCT_NAME}\""
    BUILD_COMMAND += " " + f"--windows-file-version=\"{APP_VERSION}.{APP_BUILD}\""
    BUILD_COMMAND += " " + f"--windows-product-version=\"{PRODUCT_VERSION}\""
    BUILD_COMMAND += " " + f"--windows-file-description=\"{APP_NAME}\""
    BUILD_COMMAND += " " + f"app.py"

    os.system('cls')

    print("================================================================================")
    print(f"Building: {FOLDER_NAME}")
    print("================================================================================")
    print()

    __is_success = False

    try:

        print("----------------------------------------")
        print(f"COMPILING/LINKING STARTED...")
        print("----------------------------------------")

        # Call Nuitka
        subprocess.call(BUILD_COMMAND)

        # Check If Executable is present.
        if os.path.exists(f"{OUTPUT_DIRECTORY}/app.dist/app.exe"):

            print()

            print("----------------------------------------")
            print(f"COMPILING/LINKING... DONE!")
            print("----------------------------------------")

            print()

            print("----------------------------------------")
            print(f"COPYING REQUIRED RESOURCES...")
            print("----------------------------------------")

            # Copy Required Resources

            print(f"• Copying [app.ini] file to [{OUTPUT_DIRECTORY}/app.dist/app.ini]...")
            shutil.copyfile("app.ini", f"{OUTPUT_DIRECTORY}/app.dist/app.ini")

            print(f"• Copying [development.key] file to [{OUTPUT_DIRECTORY}/app.dist/development.key]...")
            shutil.copyfile("development.key", f"{OUTPUT_DIRECTORY}/app.dist/development.key")

            print(f"• Copying [res] folder to [{OUTPUT_DIRECTORY}/app.dist/res]...")
            shutil.copytree("res", f"{OUTPUT_DIRECTORY}/app.dist/res")

            print("----------------------------------------")
            print(f"COPYING REQUIRED RESOURCES... DONE!")
            print("----------------------------------------")

            print()

            print("----------------------------------------")
            print(f"RENAMING REQUIRED FILES/FOLDERS...")
            print("----------------------------------------")

            # Rename Application
            print(f"• Renaming file [{OUTPUT_DIRECTORY}/app.dist/app.exe] to [{OUTPUT_DIRECTORY}/app.dist/{APP_NAME}.exe]...")
            os.rename(f"{OUTPUT_DIRECTORY}/app.dist/app.exe", f"{OUTPUT_DIRECTORY}/app.dist/{APP_NAME}.exe")

            # Rename Folder
            print(f"• Renaming folder [{OUTPUT_DIRECTORY}/app.dist] to [{OUTPUT_DIRECTORY}/{FOLDER_NAME}]...")
            os.rename(f"{OUTPUT_DIRECTORY}/app.dist", f"{OUTPUT_DIRECTORY}/{FOLDER_NAME}")

            print("----------------------------------------")
            print(f"RENAMING REQUIRED FILES/FOLDERS... DONE!")
            print("----------------------------------------")

            __is_success = True

        else:

            print()
            print("----------------------------------------")
            print(f"COMPILING/LINKING... ERROR! UNABLE TO FIND [{OUTPUT_DIRECTORY}/app.dist/app.exe]... ABORTING!")
            print("----------------------------------------")
            print()

            __is_success = False

    except Exception as e:

        __is_success = False


    if __is_success:
        print("\n================================================================================")
        print(f"Building: {FOLDER_NAME} is Completed Successfully!")
        print("================================================================================\n")

    else:
        print("\n================================================================================")
        print(f"Building: {FOLDER_NAME} Failed!")
        print("================================================================================\n")        `

**Comment by kayhayen** [comment]
There is Nuitka project options, where you can execute code to determine things at compile time. That ought to eliminate most use cases of this.

Nuitka likes to re-execute itself during compilation, to get rid of the effects, e.g. of the `site` module. That kind of `run` would never return, therefore. It wants to have a pristine environment, after assuming the difference of what is sees is caused by `site` module and preserved.

Your example doesn't illustrate, which `subprocess.check_call[sys.executable, "-m", "nuitka", "--onefile", "myscript.py"])` should be so much inferior. I would like to hear from you there, I don't see much of a point.
