### ISSUE TITLE
Windows : Forced outputs do not have proper encoding, causing for Chinese output "UnicodeEncodeError"

### ISSUE THREAD

**Issue by zhusihan-python** [Nuitka/Nuitka#1596]
full err log
```
Traceback (most recent call last):
  File "F:\print_chinese.dist\print_chinese.py", line 3, in <module>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 3-7: ordinal not in range(128)
```
my nutika version: at frist i use 0.6.19rc7, then i tried 0.7.7, 0.8.3, and factory version 0.9rc4, both of them has the same error as above
python -m nuitka --version
```
0.8.3
Commercial: None
Python: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: D:\softwares\py39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```
build script
`nuitka --standalone --mingw64 --windows-disable-console --windows-force-stdout-spec=F:\print_chinese.log --windows-force-stderr-spec=F:\print_chinese_err.log print_chinese.py
`

example code:
```
l = [('扫描时间：2022年06月02日 11:42\n操作员：user1', None, 1)]
print(l)
```
this error only shown in standlone mode and console disabled by --windows-disable-console , it works well while console is opened, setting PYTHONIOENCODING as this [issue](https://github.com/Nuitka/Nuitka/issues/1255) said didn't work for me, i guess it has been set in python 3.9 already

**Comment by kayhayen** [comment]
We open these files without specifying an encoding, which is definitely a weakness, that will cause this. Can you try if setting `utf8_mode` when executing compilation fixes the issue for you. The workaround you are talking about is deemed unnecessary with 3.9 or higher, since there the needed encoding is available during program startup.

**Comment by kayhayen** [comment]
When we disable the console, the `sys.stdout` and friends become empty. There is no access to the encoding, that it would have, my first idea was to copy the encoding value simply, but that is not an option.

Strangely, default encoding of the created file is `cp1252` on my Windows, while `sys.stdout` has `utf-8`. That is without the UTF-8 mode.

**Comment by kayhayen** [comment]
With 3.5 the standard out encoding was `mbcs`. Afterwards it was `utf-8`. So it feels safe to do it for all Python3 I guess.

**Comment by kayhayen** [comment]
Fixed on factory branch. https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
Part of the current pre-release.

**Comment by kayhayen** [comment]
Part of the 0.9 release that I just made.
