### ISSUE TITLE
Standalone fails with AttributeError: module 'distutils.command.install' has no attribute '_load_schemes'

### ISSUE THREAD

**Issue by kloon15** [Nuitka/Nuitka#1598]
I cannot create standalone builds, it always fails with the same error:

> AttributeError: module 'distutils.command.install' has no attribute '_load_schemes'

See attached file for full log [nuitka.log](https://github.com/Nuitka/Nuitka/files/8844603/nuitka.log).

* Nuitka version, full Python version, flavor, OS, etc. as output by this
  command (it does more than you think, and we are adding more all the time):

  > 0.8.3
  > Commercial: None
  > Python: 3.10.4 (main, Mar 24 2022, 13:07:27) [GCC 11.2.0]
  > Flavor: Debian Python
  > Executable: /home/kloon/Projects/pyPandas/venv/bin/python3
  > OS: Linux
  > Arch: x86_64
  > Distribution: Kali (based on Debian) 2022.2

* How did you install Nuitka and Python

  > apt-get install python3-dev and pip install nuitka (in a venv)

* The specific PyPI names and versions

  > altgraph==0.17.2
  > asttokens==2.0.5
  > backcall==0.2.0
  > decorator==5.1.1
  > et-xmlfile==1.1.0
  > executing==0.8.3
  > ipython==8.4.0
  > jedi==0.18.1
  > matplotlib-inline==0.1.3
  > Nuitka==0.8.3
  > numpy==1.22.4
  > openpyxl==3.0.10
  > ordered-set==4.1.0
  > pandas==1.4.2
  > parso==0.8.3
  > pexpect==4.8.0
  > pickleshare==0.7.5
  > prompt-toolkit==3.0.29
  > ptyprocess==0.7.0
  > pure-eval==0.2.2
  > pyarmor==7.4.3
  > Pygments==2.12.0
  > pyinstaller==5.1
  > pyinstaller-hooks-contrib==2022.6
  > python-dateutil==2.8.2
  > pytz==2022.1
  > six==1.16.0
  > stack-data==0.2.0
  > traitlets==5.2.2.post1
  > wcwidth==0.2.5

* Many times when you get an error from Nuitka, your setup may be special

  > I can compile code and run perfectly with --follow-imports but not with --standalone.

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

  > It always fails regardless of code.

* Provide in your issue the Nuitka options used

  > nuitka3 --standalone main.py

* Note if this is a regression

  > No idea.

**Comment by kloon15** [comment]
pip freeze is missing the basic python packages:
pip                       22.1.2
setuptools                62.3.2
wheel                     0.37.1

**Comment by kayhayen** [comment]
I am going to add warnings about building standalone from Debian installations, mostly because they are often not designed to be portable, enforcing hard code paths, that only Debian has. So, what you produce there is not very portable, but still might be what you want.

Make sure to create a virtualenv, and compile in there, then the issue will go away likely. The PyPI packages are designed to be portable.

That said, I will make a change that doesn't include `_distutils_system_mod` automatically unless it's used, and it seems broken anyway.

**Comment by kayhayen** [comment]
The warning is now on develop and will be released as part of 0.9

**Comment by kayhayen** [comment]
The web page that it points to, doesn't exist yet though.

**Comment by kayhayen** [comment]
Part of the 0.9 release that I just made.
