### ISSUE TITLE
Enhancement: Detect very long link phase and suggest "--lto=no" from "--lto=auto" being slow

### ISSUE THREAD

**Issue by gdementen** [Nuitka/Nuitka#1604]
I was coping with link times of more than an hour until I used --lto=no which made the link step near instantaneous (with very little performance difference).

The problem is that I only read about --lto=no by accident (by reading another issue), so it would be great if Nuitka had suggested it to me.

**Comment by kayhayen** [comment]
Much like slow compilation warning, this could indeed be done. I must admit, I am myself annoyed by the lack of progress information too. Maybe after 5 minutes, with `--lto=auto` you get it like the other performance warnings for C modules.

**Comment by kayhayen** [comment]
This is now on the factory branch. It should only trigger for compilations below 500 modules, where auto resolves to "yes", and then still being slow. This is now acceptable to share the timer, because I recently bumped the slow compile warning up to 5 minutes for a module.

**Comment by kayhayen** [comment]
Part of the current pre-release and will be in 1.7, closing this early for lack of general relevance.

**Comment by kayhayen** [comment]
Part of the 1.7 release I just made now.
