### ISSUE TITLE
macOS 打包app后没有提示权限问题

### ISSUE THREAD

**Issue by superCong** [Nuitka/Nuitka#1605]
<key>NSCameraUsageDescription</key>
    <string>An application in app requests access to the device's camera.</string>
    <key>NSMicrophoneUsageDescription</key>
    <string>An application in app requests access to the device's microphone.</string>
    <key>NSLocationUsageDescription</key>
    <string>An application in app requests access to the user's location information.</string>
    <key>NSDesktopFolderUsageDescription</key>
    <string>An application in app requests access to the user's Desktop folder.</string>
    <key>NSDocumentsFolderUsageDescription</key>
    <string>An application in app requests access to the user's Documents folder.</string>
    <key>NSDownloadsFolderUsageDescription</key>
    <string>An application in app requests access to the user's Downloads folder.</string>
    <key>NSNetworkVolumesUsageDescription</key>
    <string>An application in app requests access to files on a network volume.</string>
    <key>NSRemovableVolumesUsageDescription</key>
    <string>An application in app requests access to files on a removable volume.</string>
    <key>NSBluetoothAlwaysUsageDescription</key>
    <string>An application in app requests access to Bluetooth.</string>

以上是各种权限的代码，以下是添加的位置
xxx/venv/lib/python3.10/site-packages/nuitka/utils/MacOSApp.py
修改代码后软件打包出来就可以有权限。
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/21659767/172889623-580b861e-35f3-46a0-a8ec-e0654d4c97f6.png">

**Comment by kayhayen** [comment]
No issue template no fun
