### ISSUE TITLE
Breaks Pillow webp support

### ISSUE THREAD

**Issue by nyx191** [Nuitka/Nuitka#1607]
Installed Nuitka via pip3, Pillow via apt from debian repos.
```
$ nuitka3 --version
0.8.4
Commercial: None
Python: 3.10.5 (main, Jun  8 2022, 09:26:22) [GCC 11.3.0]
Flavor: Debian Python
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
Distribution: Debian sid
```
Pillow v9.1.1.
My wish is to make Pillow code faster and produce single python-independent binary. AppImage is ok for me.
Consider following example:
```
#!/usr/bin/env python3

from PIL import Image

def main():
    Image.open("in.jpg").save("out.webp")

if __name__ == "__main__":
    main()
```
Compiling with nuitka and executing:
```
$ CCFLAGS='-march=native' nuitka3 --quiet --onefile --follow-stdlib --follow-imports --remove-output --enable-plugin=numpy --enable-plugin=pyqt5 -j3 webp.py
```
produces binary `webp.bin`
```
$ ./webp.bin
Traceback (most recent call last):
  File "/tmp/.mount_webp.bzy6UMM/webp.py", line 10, in <module>
    main()
  File "/tmp/.mount_webp.bzy6UMM/webp.py", line 7, in main
    Image.open("in.jpg").save("out.webp")
  File "/tmp/.mount_webp.bzy6UMM/PIL/Image.py", line 2280, in save
ValueError: unknown file extension: .webp
```
So no WebP support, unfortunate.
Replacing `out.webp` with e.g. `out.png` leads to working program, but I need WebP for my specific purpose.
**UPD0:**
Simplified command:
`$ nuitka3 --onefile --full-compat --remove-output --enable-plugin=numpy --enable-plugin=pyqt5 webp.py` doesn't work either.

**Comment by nyx191** [comment]
According to
https://github.com/Nuitka/Nuitka/issues/1598#issuecomment-1148413778
I guess that debian packages are bad for building standalone Nuitka executables and I should use only pip packages.

**Comment by nyx191** [comment]
> Did you try that and did the problem persinst?

Yes, please look at https://github.com/Nuitka/Nuitka/issues/1607#issuecomment-1156171991
I tried with 100% PyPI (nuitka, pillow, all their dependencies) in Arch Linux, the problem with WebP persists.

**Comment by kayhayen** [comment]
Ah, your update annotation was confusing me there, I get it now. Thanks.

**Comment by kayhayen** [comment]
My first suspect was a missing PIL plugin, but `PIL.WebPImagePlugin` is in the implicit imports, not sure what's going on there.

**Comment by kayhayen** [comment]
Ah, it's wrongly (?) assigned to `imageio` which you are not using.

**Comment by nyx191** [comment]
> Ah, it's wrongly (?) assigned to `imageio` which you are not using.

AFAIK, `pillow` project is independent from `imageio`, but `imageio` requires `pillow`. WebP support is also `pillow` thing.

**Comment by kayhayen** [comment]
Yes, it's changed to that, somebody added a sloppy implicit dependency there, changing it made things just work. These plugins of Pillow are just some of imageio plugins indeed, and it does a proper `PIL.Image` import that should always have had those.

**Comment by kayhayen** [comment]
Part of the of current pre-release, and will be part of 0.9 release.

**Comment by nyx191** [comment]
Can confirm that 0.9rc7 works against full PIL program

**Comment by kayhayen** [comment]
Part of the 0.9 release that I just made.
