### ISSUE TITLE
Plotly import issue with standalone executable

### ISSUE THREAD

**Issue by parksj10** [Nuitka/Nuitka#1609]
```bash
Commercial: None
Python: 3.9.6 (default, Aug 18 2021, 15:44:49) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\tools\miniconda3\envs\np_test\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

`pip install nuitka` into a conda virtualenv

```bash
------------ -----------
certifi      2022.5.18.1
Nuitka       0.8.4
orderedset   2.0.3
pip          21.2.4
plotly       5.8.2
setuptools   61.2.0
tenacity     8.0.1
wheel        0.37.1
wincertstore 0.2
```

hello world works properly

**SSCCE**
```python
import plotly.graph_objects as go
fig = go.Figure(
    data=[go.Bar(y=[2, 1, 3])],
    layout_title_text="A Figure Displayed with fig.show()"
)
fig.show()
```

**Nuitka Options**

`python -m nuitka --standalone --warn-implicit-exceptions --output-dir=.\nuitka .\test.py`

**Error**
```bash
>./nuitka/nuitka/test.dist/test.exe                                         
Traceback (most recent call last):
  File "C:\Users\Josh\Code\nuitka\nuitka\TEST~1.DIS\test.py", line 2, in <module>  File "C:\Users\Josh\Code\nuitka\nuitka\TEST~1.DIS\plotly\graph_objects\__init__.py", line 299, in __getattr__
  File "C:\Users\Josh\Code\nuitka\nuitka\TEST~1.DIS\_plotly_utils\importers.py",
line 37, in __getattr__
  File "C:\Users\Josh\Code\nuitka\nuitka\TEST~1.DIS\plotly\graph_objs\__init__.py", line 299, in __getattr__
  File "C:\Users\Josh\Code\nuitka\nuitka\TEST~1.DIS\_plotly_utils\importers.py",
line 36, in __getattr__
  File "importlib.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'plotly.graph_objs._figure'
```

NOTE:

when I force module inclusion via command line option:

`--include-module=plotly.graph_objs`

it fails at the next module that is imported via `_find_and_load_unlocked`:

```bash
>/nuitka/nuitka/test.dist/test.exe                                     
Traceback (most recent call last):
  File "C:\Users\Josh\Code\nuitka\nuitka\TEST~1.DIS\test.py", line 3, in <module>  File "C:\Users\Josh\Code\nuitka\nuitka\TEST~1.DIS\plotly\graph_objs\_bar.py", line 3210, in __init__
  File "C:\Users\Josh\Code\nuitka\nuitka\TEST~1.DIS\plotly\basedatatypes.py", line 4847, in __setitem__
  File "C:\Users\Josh\Code\nuitka\nuitka\TEST~1.DIS\plotly\basedatatypes.py", line 4329, in _get_validator
  File "C:\Users\Josh\Code\nuitka\nuitka\TEST~1.DIS\plotly\validator_cache.py", line 29, in get_validator
  File "importlib.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'plotly.validators.bar'
```

**Comment by kayhayen** [comment]
This looks like a missing dependency. I will use your example, and try to add them.

**Comment by kayhayen** [comment]
I am first doing `anti-bloat` work on the usual suspects, Pandas has already improved a lot, and but I found that plotly pulls in ipython, which is pretty bad for bloat, so that's being removed now, so we hopefully end up with a lighter compilation here.

**Comment by kayhayen** [comment]
So, the hidden dependencies are due to a lazy-loading of modules, that they added for 3.7 or higher, using `__getattr__` to hide it, rather than statically just importing everything. These things unfortunately always mean, we cannot tell ahead of time which ones to include, and which ones not. For now I will use the branch for 3.7 with newer Python too, as effectively that is what we have to do. Only PGO will let us determine actually used modules later on.

**Comment by kayhayen** [comment]
Same thing for validators, adding a full package dependency for all `plotly.validators` modules to be there.

**Comment by kayhayen** [comment]
When I add these validators all, it flat out breaks all records, with 4.5k+ modules and still climbing. The trace for the implicit dependencies modules of the validators is huge itself, not sure what to do here. I wonder if there is a way for Nuitka to predict the used one, as it's completely unreasonable.

**Comment by kayhayen** [comment]
It ended up being 4895 modules, which is way too much memory consumption. It pulls in Tornado, and other things, that are probably all highly optional dependencies normally. I will need to check out, if this is a few of them, that cause a lot of them, but for that, ideally we would have a dependency tree in the compilation report, otherwise it's going to be a too tedious process.

**Comment by parksj10** [comment]
> So, the hidden dependencies are due to a lazy-loading of modules, that they added for 3.7 or higher, using `__getattr__` to hide it, rather than statically just importing everything. These things unfortunately always mean, we cannot tell ahead of time which ones to include, and which ones not. For now I will use the branch for 3.7 with newer Python too, as effectively that is what we have to do. Only PGO will let us determine actually used modules later on.

I tried running this with `PGO`, but it errored out for me. 



> It ended up being 4895 modules, which is way too much memory consumption. It pulls in Tornado, and other things, that are probably all highly optional dependencies normally. I will need to check out, if this is a few of them, that cause a lot of them, but for that, ideally we would have a dependency tree in the compilation report, otherwise it's going to be a too tedious process.

Does `nuitka` output a compilation report? I tried forcibly including the entire `plotly` package and I ended up with more than 10k modules, but it did eventually compile (haven’t tested functionality yet).

I agree as it stands it’s way too much for both memory and compile time

**Comment by kayhayen** [comment]
Yes, the `--report` outputs an XML file, that lists all included modules and data files. Going to add more and more over time, it's intended for testing at first, e.g. making sure what's included for data files or not, but it should become a reference for checking out things. The implicit import traces, are e.g. something to get rid of entirely. Instead, I would like to have a "used by" for each module, that gives a reason. But it's not yet something to point users to and not have them disappointed. There is naturally much information missing.

I have done some anti-bloat work. The validators show what's possible with new Nuitka, it is like 100s of modules per second for those, so maybe it's not as bad. It included `setuptools_scm` for me still, and right now I am fighting `tornado` from `tenacity` which is a popular retrying framework.

I just saw it jump from 600 to 3600 by adding the validators, but it's flashing through them without adding much modules if any, so probably it's not too bad, these are all small ones. Sometime we have single modules that takes longer than these combined.

The 10k is not an option, definitely, and the inclusion of a whole package will pull in way to many dependencies. Maybe the validators themselves, but I can see how as a user, you don't want to minimize at all, but maximizing the runs. I have this on the side across a few days, and then solve one tiny bit, start it again, and revisit when I have the time.

For me it's also kind of fun. But also, sometimes I get ideas, how to better avoid those. As e.g. for tenacity, I am removing the tornado import, with a toggle to disable that. Maybe a tornado plugin could provide that. But I think, in some of these instances, what would be needed, is a sort of optional lazy import, which is what many times code does for IPython, e.g. where it checks if it's in `sys.modules` and if it is, would use it. 

With the right kind of mechanism, the toggles should be avoidable. Of course, if all upstream Python used a standard approach, that would also be sweet, but I made the plan to add it to Nuitka and use it, to have fully transparent replacements for these, where plugins don't matter.

Also, I am using the `no-qt` plugin, as it avoids many imports as well. The `PySide6` pulls in and insists on some bad modules in `shiboken6` and that is hard to avoid. A `no-web` plugin that inhibits, tornado, flask, and what not, and ones that allow only the specific one, would probably also help a lot.

But I think I am finishing on Plotly such that it will be way more OK soon.

**Comment by kayhayen** [comment]
Meh, there is a similar thing going on with templates, adding those, I am down to 4263 when including them. Lets see if it cuts that. Compilation is slow, but not super slow. Changes are on develop and factory right now, but there might be coming more.

**Comment by kayhayen** [comment]
I didn't finish this in time for 0.9, but chances are one of the hotfixes will have it. I was having an issue that suggested the matching of module names in the Yaml config must have a problem, or something strange.

**Comment by kayhayen** [comment]
I actually forgot to tell, but I am pretty sure at least 1.0 is having this already and will be released shortly.
