### ISSUE TITLE
Support for PEP 604 – Allow writing union types as X | Y

### ISSUE THREAD

**Issue by haptiq-sondre** [Nuitka/Nuitka#1611]
* Nuitka version, full Python version, flavor, OS, etc. as output by this
  command (it does more than you think, and we are adding more all the time):

  > python -m nuitka --version

```
0.8.4
Commercial: 1.0.0
Python: 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\my-app-uZqywXsA-py3.10\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

* How did you install Nuitka and Python

  pip in a poetry environment

* The specific PyPI names and versions

  No relevant packages.

* Many times when you get an error from Nuitka, your setup may be special

  There is no issue if I use e.g. `Optional[str]` instead of `str | None` union types.

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

  Use of any function which uses union types as specified by [PEP 604](https://peps.python.org/pep-0604/).

* Provide in your issue the Nuitka options used

  ```
  nuitka --onefile --prefer-source-code --assume-yes-for-downloads --enable-plugin=anti-bloat --noinclude-setuptools-mode=nofollow --noinclude-pytest-mode=nofollow --plugin-enable=multiprocessing --plugin-enable=numpy --plugin-enable=pkg-resources --plugin-enable=pylint-warnings --msvc=latest --enable-plugin=data-hiding --windows-onefile-tempdir --windows-icon-from-ico=D:\a\my-app\my-app\my_app\resources\favicon.ico --windows-company-name=MyApp --windows-product-name=My App (C) 2020-2022 MyCompany --windows-file-description=My App 2022.5.0 (09d086e) --windows-file-version=2022.5.0.0 --windows-product-version=2022.5.0.0 D:\a\my-app\my-app\my_app\MyApp.py
  ```

* Note if this is a regression

  No.

* Consider getting commercial support

  Yes, we have Nuitka Commercial and Priority.

**Comment by kayhayen** [comment]
I believe they are working, can you provide an example of something not working, please?

**Comment by haptiq-sondre** [comment]
Ah, sorry. On closer inspection it seems like it has to do with forward referencing.
An executable is created by Nuitka, but when I run it I get `TypeError: unsupported operand type(s) for |: 'str' and 'NoneType'`.

Example with pydantic:
```
from pydantic import BaseModel, Field

class A(BaseModel):
    x: "B" | None = Field(None, hidden=True)
    
class B(BaseModel)
    y: int = 0
```

Changing `"B" | None` to `"Optional["B"]"` removes the error. Alternatively, forward referencing like this should be avoided.

**Comment by kayhayen** [comment]
I think Nuitka statically optimizes `"B" | None` according to normal rules, since `B` is not a type, but a string:

```
>>> "B" | None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'str' and 'NoneType'
```

**Comment by kayhayen** [comment]
```
>>> x = ast.parse("X: 'B' | None") 
>>> ast.dump(x)
"Module(body=[AnnAssign(target=Name(id='X', ctx=Store()), annotation=BinOp(left=Constant(value='B'), op=BitOr(), right=Constant(value=None)), simple=1)], type_ignores=[])"
```

Right now, the annotation is build with the same parsing code that standard code does. Thankfully CPython a way to introduce new inconsistency, such that, we will have to specify a context here, that enforces different parsing during it. And esp. these forward declarations from strings are a specialty there. So now I don't know if `|` needs to be treated differently, or if strings need to be considered types.

**Comment by kayhayen** [comment]
Ok, I wasted my time, your example doesn't work in CPython either, please make a new report with a real incompatibilty when you find one.

```
python3.10 MiniPydanticAnnotation.py
Traceback (most recent call last):
  File "C:\Users\kayha\repos\Py2C\MiniPydanticAnnotation.py", line 3, in <module>
    class A(BaseModel):
  File "C:\Users\kayha\repos\Py2C\MiniPydanticAnnotation.py", line 4, in A
    x: "B" | None = Field(None, hidden=True)
TypeError: unsupported operand type(s) for |: 'str' and 'NoneType'
```
