### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Akselmo** [Nuitka/Nuitka#1614]
Full context: https://github.com/Akselmo/ESOLinuxAddonManager/issues/21

Built my app with Nuitka into appimage, it fails to find the SSL certificate on other machines that the appimage is built on. The appimage was built on Fedora 36, so any F36 distro runs it, but if the SSL cert is in different place it doesnt work.

Any help/fixes for this?

```
File "/tmp/.mount_ESOLinhiD7PY/urllib/request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
```

Using Nuitka 0.8.4 to build singlefile app.

**Comment by Akselmo** [comment]
Update, something i noticed

The certification location is not dynamic: when compiled with nuitka it gets the cert location and its always the one used by the build machine.

**Comment by Akselmo** [comment]
This was an user error.. Oops.

I had forgotten to add `--include-package="certifi" ` to my build script.

**Comment by kayhayen** [comment]
Without the issue template there is nothing I can, normally the package should be included automatically, but you failed to make a proper report, you are welcome to retry with filled out issue template, but as such, this is useless.
