### ISSUE TITLE
FATAL: implicit-imports: Error, illegal value for 'standalone_macos_bundle_mode' for 'wx' entry.

### ISSUE THREAD

**Issue by noeru-desu** [Nuitka/Nuitka#1620]
```
0.9rc7
Commercial: None
Python: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\YZH\AppData\Local\Programs\Python\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```
I compiled this code:
```
import wx
```
with command: 
```
nuitka --onefile --macos-disable-console --macos-create-app-bundle test.py
```
output content:
```
Nuitka-Options:INFO: Used command line options: --onefile --macos-disable-console --macos-create-app-bundle E:\test.py
Nuitka:INFO: Starting Python compilation with Nuitka '0.9rc7' on Python '3.10' commercial grade 'not installed'.
FATAL: implicit-imports: Error, illegal value for 'standalone_macos_bundle_mode' for 'wx' entry.
```
I checked the source code and found that in `nuitka/plugins/standard/standard.nuitka-package.config.yml`, line 1315, `standalone_macos_bundle_mode` is set to `"true"`. I solved the problem after changing it to `standalone_macos_bundle_mode: True`

**Comment by paddy-r** [comment]
I confirm I am having the same issue Python 3.9, wxpython version 4.1.1).

**Comment by kayhayen** [comment]
No, you do not @paddy-r you probably just used 0.9.0 and not 0.9.1 which wasn't on PyPI yet.

**Comment by paddy-r** [comment]
Thanks @kayhayen, I upgraded to 0.9.2 and my code now compiles successfully.
