### ISSUE TITLE
Tensorflow 2 import crashes during nuitka compilation( failed to resolve DLL _pywrap_py_utils.so)

### ISSUE THREAD

**Issue by emre84** [Nuitka/Nuitka#1621]
Environment:
MACOS Monterey
Python:3.7.3
Nuitka 'Nuitka-0.8rc7' (downloaded 2 days ago)

How did you install Nuitka and Python
pip

The specific PyPI names and versions
tensorflow==2.8

Provide in your issue the Nuitka options used
sudo python3.7 -m nuitka ---standalone --enable-plugin=anti-bloat --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow --enable-plugin=tensorflow --python-flag=no_site test.py

Content of test.py:
import tensorflow as tf
print(tf.version)

Error during nuitka standalone compilation:
FATAL: Error, failed to resolve DLL path bazel-out/darwin-opt/bin/tensorflow/compiler/tf2tensorrt/lib_pywrap_py_utils_ccsharedlib.so (for /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/compiler/tf2tensorrt/_pywrap_py_utils.so), please report the bug.

Note: I have also tried with following command(--include-data-file tf2tensorrt/*.so included, which has lib_pywrap_py_utils_ccsharedlib.so file inside) , unfortunately I am still getting the same error:

sudo python3.7 -m nuitka ---standalone --enable-plugin=anti-bloat --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow --enable-plugin=tensorflow --python-flag=no_site --include-data-file=/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/compiler/tf2tensorrt/*.so=tensorflow/compiler/tf2tensorrt/ test.py

**Comment by kayhayen** [comment]
DLLs are not data files, so no wonder it has no effect on Nuitka DLL resolution.

This might be due to a duplicate DLL warning, but you failed to provide the version output of Nuitka, so I don't know what Python this really is. Please retry with proper information filled out. Otherwise I am assuming duplicate.

**Comment by emre84** [comment]
Hi Kay,


Sorry. Here is my output:
https://www.dropbox.com/s/ftdior8mq875htt/temp?dl=0

**Comment by kayhayen** [comment]
I would be more interested in what `--version` of nuitka says about your system.

**Comment by emre84** [comment]
emres-Air:object_detection emre$ sudo python3.7 -m nuitka --version
0.8rc7
Commercial: None
Python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
Flavor: Unknown
Executable: /usr/local/bin/python3.7
OS: Darwin
Arch: x86_64

**Comment by kayhayen** [comment]
The `nuitka --version` output is not the output of the run, which only shows that you don't read things, or else the anti-bloat warnings would have given you a pause.

**Comment by emre84** [comment]
Hi Kay, do i have to open a new issue with the same content and title or will you reactivate current issue? Do you need any other output from me? I guess "sudo python3.7 -m nuitka --version" was enough, am I right?

Thanks a lot for your supports.
