### ISSUE TITLE
Questiom: How to change output filename when building module with Nuitka?

### ISSUE THREAD

**Issue by MagicBeanJack** [Nuitka/Nuitka#1624]
Previously I used Python 3.6 and Nuitka 0.6.7 to build a Nuitka module, the output filename is **test_module.pyd** then I upgraded to Python 3.9 and Nuitka 0.9, and the output filename is now t**est_module.cp39-win32.pyd.** I want to remove **.cp39-win32** in the filename. I read through Nuitka --help, but I can't find the command to modify it. Here is the command I used to build Nuitka module
`python -m nuitka --module test_module.py --mingw64 --no-pyi-file --remove-output`
Any help is appreciated

**Comment by Cjw9000-py** [comment]
just rename it with `rename test_module.*.pyd test_module.pyd` but be sure not to change test_module because then your module cannot be loaded anymore.

**Comment by kayhayen** [comment]
There is `-o` but it might not be used, I got to try it out, and consider fixing it.

```
FATAL: Error, may only specify output filename for acceleration and onefile mode,
but not for module mode where filenames are mandatory, and not for
standalone where there is a sane default used inside the dist folder.
```

Well, that is true, however the change you want to make would be legal, but misleading, as one can not recognize the version supported anymore.

**Comment by kayhayen** [comment]
I would accept a PR, that changes the check such that it will let pass values in module mode, that have the suffix. However, @Cjw9000-py is absolutely right. You can just rename it afterwards too.
