### ISSUE TITLE
MSYS2: Python path configuration error

### ISSUE THREAD

**Issue by wszqkzqk** [Nuitka/Nuitka#1626]
Python in MSYS2 doesn't work without `standalone` mode

My command:
```cmd
nuitka3 --mingw64 --follow-imports --output-dir=~\Downloads\out computeTestPy.py"
```
When I ran `computeTestPy.exe`, it showed:
```python
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = 'C:\Program Files\PerkinElmerInformatics\ChemOffice2021\ChemScript\Lib'
  program name = 'python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 0
  sys._base_executable = 'C:/Users/17444/Downloads/out/computeTestPy.exe'
  sys.base_prefix = 'D:/a/msys64/mingw64'
  sys.base_exec_prefix = 'D:/a/msys64/mingw64'
  sys.platlibdir = 'lib'
  sys.executable = 'C:/Users/17444/Downloads/out/computeTestPy.exe'
  sys.prefix = 'D:/a/msys64/mingw64'
  sys.exec_prefix = 'D:/a/msys64/mingw64'
  sys.path = [
    'C:\\Program Files\\PerkinElmerInformatics\\ChemOffice2021\\ChemScript\\Lib',
    'D:/a/msys64/mingw64/lib/python310.zip',
    'D:/a/msys64/mingw64/lib/python3.10',
    'D:/a/msys64/mingw64/lib/lib-dynload',
    '',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00001e48 (most recent call first):
  <no Python frame>
```
When I ran `computeTestPy.cmd`, it showed:
```python
Python path configuration:
  PYTHONHOME = 'c:/msys64/mingw64/bin'
  PYTHONPATH = 'C:\Program Files\PerkinElmerInformatics\ChemOffice2021\ChemScript\Lib'
  program name = 'python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 0
  sys._base_executable = 'C:/Users/17444/Downloads/out/computeTestPy.exe'
  sys.base_prefix = 'c:/msys64/mingw64/bin'
  sys.base_exec_prefix = 'C:/msys64/mingw64/bin'
  sys.platlibdir = 'lib'
  sys.executable = 'C:/Users/17444/Downloads/out/computeTestPy.exe'
  sys.prefix = 'c:/msys64/mingw64/bin'
  sys.exec_prefix = 'C:/msys64/mingw64/bin'
  sys.path = [
    'C:\\Program Files\\PerkinElmerInformatics\\ChemOffice2021\\ChemScript\\Lib',
    'C:/msys64/mingw64/bin/lib/python310.zip',
    'c:/msys64/mingw64/bin/lib/python3.10',
    'C:/msys64/mingw64/bin/lib/python3.10/lib-dynload',
    '',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00000ce0 (most recent call first):
  <no Python frame>
```
`C:\Program Files\PerkinElmerInformatics\ChemOffice2021\ChemScript\Lib` is not the correct python path. Actually it's just a tool library about chemistry. And the order of this item in environment variable `Path` is behind the order of the binary file of MSYS2. Maybe Nuitka choosed the Python path incorrectly?

**Comment by kayhayen** [comment]
The CMD file creation, I am not sure it is needed.

**Comment by kayhayen** [comment]
It at least has wrong contents, because it's geared to Win32 Python installation, but not MSYS2. But executing the executable gives an error, but without the `bin` part for Python home. Probably still wrong.

**Comment by kayhayen** [comment]
So, the DLL directory of the running Python DLL is determined, and that is used for `PYTHONHOME`. That is not as general as it should be, now using the Python `sys.prefix`, but that is not helping a lot, but it's more correct I guess.

**Comment by kayhayen** [comment]
Btw, does msys2 have the ordered set packages that Nuitka likes?

**Comment by kayhayen** [comment]
Actually, it does help, was testing the wrong thing. It is now on factory: https://nuitka.net/doc/factory.html

**Comment by wszqkzqk** [comment]
> Btw, does msys2 have the ordered set packages that Nuitka likes?

Yes, [mingw-w64-python-ordered-set](https://packages.msys2.org/base/mingw-w64-python-ordered-set)

**Comment by wszqkzqk** [comment]
> Actually, it does help, was testing the wrong thing. It is now on factory: https://nuitka.net/doc/factory.html

I've [made a PR](https://github.com/msys2/MINGW-packages/pull/11939) for MSYS2 to add python-zstandard and python-ordered to Nuitka's optional dependencies.

**Comment by kayhayen** [comment]
Thanks for that PR, should help a lot for compile time performance, and yes, onefile needs a bit of love too.

**Comment by kayhayen** [comment]
Part of the 0.9.1 hotfix I just released.
