### ISSUE TITLE
Nuitka packed application raise UnicodeEncodeError when add `--windows-disable-console`

### ISSUE THREAD

**Issue by r00t1900** [Nuitka/Nuitka#1633]
## version details
> python -m nuitka --version
```
0.7.7
Commercial: None
Python: 3.8.13(default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\<username>\miniconda3\envs\chaos\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 7
```
> windows version
```
OS: Windows 10
Arch: x86_64
```
## error details
When compile python project using parameters `--windows-disable-console` and `--onefile`, it just appear for a while then crash. Because there is no console output so I redirect the logging into a file and found this error:
```
UnicodeEncodeError: `ascii` can not encode bytes `...`...
```

## analysis

Before I request this issue, I've search in previous issues(e.g. https://github.com/Nuitka/Nuitka/issues/1596,https://github.com/Nuitka/Nuitka/issues/1378,) with keyword `ascii` and I found many others have same or similar problems about encoding error when enabling `--windows-disable-console`, but I did not know what is the exactly solution for current nuitka version.

Actually, I use python library `loguru` for loggng and therefore it may also call the python internal `print()` function. However, `print()` or logging is a common requirement for development so obviously I can not delete all of them. So is there any alternative steps to specific the python encoding into `utf-8` instead of `ascii` to have this problem solved? Maybe there are already a newer version have this problem fixed but I would like to fix it in this version :)

Thanks for reading.

**Comment by kayhayen** [comment]
This is old Nuitka, this has been fixed long since.

**Comment by r00t1900** [comment]
Apparently I upgraded nuitka to 0.9.0 and it solved, although it requires a newer mingw and import a ccache component.

**Comment by kayhayen** [comment]
Not sure why you say "although", it downloads them for you anyway.

**Comment by r00t1900** [comment]
> Not sure why you say "although", it downloads them for you anyway.

yeah nuitka is friendly to user and can downloads automatically, I just want to point out the dependencies between 0.7.7 and 0.9.0, never mind :)
