### ISSUE TITLE
FATAL: Error, failed to resolve DLL path @rpath/QtCore.framework/Versions/5/QtCore in MacOS (12.3.1 M1 chip) + qt5 with --standalone

### ISSUE THREAD

**Issue by statfs** [Nuitka/Nuitka#1635]
This is the error message:

    FATAL: Error, failed to resolve DLL path @rpath/QtCore.framework/Versions/5/QtCore (for /Users/x/miniconda3/envs/py37/lib/python3.7/site-packages/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore), please report the bug.

* Nuitka version, full Python version, flavor, OS, etc. 

  > python -m nuitka --version
0.8.4
Commercial: None
Python: 3.7.0 (default, Jun 28 2018, 07:39:16)
Flavor: Anaconda Python
Executable: /Users/x/miniconda3/envs/py37/bin/python
OS: Darwin
Arch: x86_64

* How did you install Nuitka and Python
  > conda create -n py37
conda install python==3.7 (because python3.8 cannot install pyqt5)
pip install nuitka

* The specific PyPI names and versions

   > python -m pip freeze
certifi @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_83242e7e-f82d-4a71-8ef2-9d71d212d249gu_wxmeq/croots/recipe/certifi_1655968827803/work/certifi
click==7.1.2
imantics==0.1.12
lxml==4.8.0
Nuitka==0.8.4
numpy==1.20.3
opencv-python==4.5.5.64
ordered-set==4.1.0
PyQt5==5.15.4
pyqt5-plugins==5.15.4.2.2
PyQt5-Qt5==5.15.2
PyQt5-sip==12.11.0
PySide2==5.15.2.1
qimage2ndarray==1.9.0
qt5-applications==5.15.2.2.2
qt5-tools==5.15.2.1.2
shiboken2==5.15.2.1
SimpleITK==2.0.2
xmljson==0.2.1

* Many times when you get an error from Nuitka, your setup may be special

  Then even a `print("hello world")` program will not work, please try that and report
  that instead.

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

```
import sys
from PyQt5 import QtGui
from PyQt5.QtCore import Qt, QRect, QRectF, pyqtSlot, QEvent
from PyQt5.QtCore import QTimer, Qt, QRectF, QRect
from PyQt5.QtCore import QPoint, Qt, QPointF
from PyQt5.QtWidgets import QWidget, QApplication, QPushButton, QVBoxLayout, QHBoxLayout, QLabel, QShortcut, QGroupBox, QCheckBox, QComboBox
from PyQt5.QtGui import QColor, QFont, QBrush, QPen, QPainter, QPolygon, QPainterPath, QPainterPathStroker
from PyQt5.QtGui import QKeySequence
from PyQt5.QtGui import QIcon, QPixmap, QImage
from PyQt5.QtCore import pyqtSignal, QObject
from PyQt5.QtWidgets import (
    QApplication,
    QGridLayout,
    QHBoxLayout,
    QVBoxLayout,
    QPushButton,
    QWidget,
    QLabel,
    QListWidget,
    QLineEdit,
    QTextEdit,
    QSlider,
)
class Window(QWidget):
    pass
if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = Window()
    window.show()
    sys.exit(app.exec_())
```
* Provide in your issue the Nuitka options used

> python -m nuitka qt.py --enable-plugin=pyqt5 --verbose --standalone
  Ideally use the project feature, so options and example code go alone

* Note if this is a regression: don't know

**Comment by statfs** [comment]
Yes. The same error accur to me even if I am using the 1.0rc2
> 1.0rc2
Commercial: None
Python: 3.7.0 (default, Jun 28 2018, 07:39:16)
Flavor: Anaconda Python
Executable: /Users/x/miniconda3/envs/py37/bin/python
OS: Darwin
Arch: x86_64

**Comment by kayhayen** [comment]
I used your code with 3.9 from Anaconda no problem just now. But from past experience, it may well not be the Anaconda PyQt5 that I used, but what I have from PyPI.

**Comment by kayhayen** [comment]
Also worked with 3.7.5 (I wouldn't use the zero version), and installed Qt from Anaconda, and confirms it works for me, even in that configuration, and actually the Qt is used from Anaconda, so I think there is some information missing here. I basically only created a new environment, install python==3.7.5 and pyqt, and that was it.

**Comment by statfs** [comment]
Hi, Kay Hayen, I reproduced your success by "conda install pyqt", which is different with mine. I used to install pyqt by "pip install pyqt5", this is the problem.

**Comment by kayhayen** [comment]
I see, I recall that one working before though, but I can give it a shot as well.

**Comment by kayhayen** [comment]
Ok, that does it indeed. I don't care much about PyQt5, since I believe PySide2/6 work so much better with Nuitka, but this might be real issue with the dependency scanner.

**Comment by kayhayen** [comment]
Ok, and even if I include parent folders, the lib folder is not added, well because according to filename matches, it's not a DLL, not ending in `.dylib` suffix.

**Comment by kayhayen** [comment]
Adding recognition of framework folders, helped the resolution, but then both with Anaconda and Python3.9 (I couldn't install it for 3.10, probably not supported), it both segfaults and I cannot debug it on my M1 machine, because `x86_64` is used, and `lldb` apparently is also useless there, very bad. Going to bisect it now, it must have regressed at some point it was working, I feel pretty sure of that.

**Comment by kayhayen** [comment]
So, of course it worked before, and still will when you specifiy `--standalone --macos-create-app-bundle --enable-plugin=pyqt5 --onefile`. For PySide2, we got this:

```
- module-name: "PySide2"
  implicit-imports:
    standalone_macos_bundle_mode: "onefile"
    disable_console: "recommend"
```

That is making sure my PySide2 users, have a working version, and apparently PyQt5 needs it too. It seems for PyQt5 the Anaconda packaging is superior and avoids the crap of it having to be in a framework at runtime, likely Anaconda main Python binary is not a framework.

@Fire-Cube I am adding information for this, we need to not forget to deal with this at merge time.
