### ISSUE TITLE
Running tests against compiled code

### ISSUE THREAD

**Issue by jamesstidard** [Nuitka/Nuitka#164]
I was wondering how people are going about testing their application binaries after they have been nuitked.

I have a application with a bunch of pytests that sit along side the project and was thinking to build a second binary which includes those and somehow running them once compiled.

The main idea is to try and catch any missed dynamic imports or asset files that need to be explicitly included in the build command sent to Nuitka.

Has anyone done something similar or have any ideas about how to go about this?

Thanks

**Comment by kayhayen** [comment]
Currently the best I can do is to point you to tests/test-runners where py.test and nose are attempted to be used. I think the later might not work, but I recall somehow nose2 ought to.

Basically what you do is to make an extension module out of your code, and run the test code using it. If your test code lives in the package namespace, the environment variable trick from that test-runner allows you to smuggle your uncompiled test code into the compiled package for import, and then it works just fine.

This should really be documented. Be my guest and update the README.rst with a pull request if you manage to find out from my pointers here.

**Comment by jamesstidard** [comment]
I was able to run my unit tests against my application as a compiled module, and they passed. Though, then compiling with the `--standalone` flag, the application does not work and fails a `pandas` import.

I was thinking of using this method of testing as a step in a CI release flow. But it this might produce a false positive and lead to a broken release.

I'm not really familiar with this kinda process, so forgive me if I'm talking crap. Would it make sense to build a standalone version of the application from the perspective of the test runner (e.g. pytest) - seeing as the tests import the application themselves. That might lead to the testing version being more representative to the final build?

**Comment by robbmcleod** [comment]
I run into similar issues with making wheels via `python setup.py bdist_nuitka`. The directory structure is intact, the Python package has the `test_*` modules, but `py.test` doesn't appear to find them via traversing the `__file__` attributes. How hard would it be to hack the `bdist_nuitka` tool to optionally not compile modules that start with `test_*`?

**Comment by kayhayen** [comment]
@Do you *want* to include the test files into the wheel at all?

I think for tests to be discovered by `py.test`, they need to be found in the file system, and them not being compiled is perfectly fine.

Right now we do not offer a way to include files in uncompiled form as `.py` files for the wheel, but mechanism, but it definitely ought to be not that hard to hack `bdist_nuitka.py`, around here:

https://github.com/Nuitka/Nuitka/blob/c9edd33bdfa61bf0476aeeb2ed2b40cf97d11fb5/nuitka/distutils/bdist_nuitka.py#L117

But what would be missing, in case you want the tests to part of the wheel (currently the ones recognized are not included I think), is the part where the `.py` files are deleted, to preserve the files, not matching the patterns.

And in an ideal world, the patterns would be provided from the outside and come from your `setup` call with those being maybe default arguments. But I am not really good at the distutils mechanism for options. But surely, nothing of this is hard.

**Comment by robbmcleod** [comment]
I'm ok with including the `test_YYY.py` files in the wheel. Based on what you say, I would have to do some set operations on `python_files` to stop this unlink:

    for fn in python_files:
            os.unlink(fn)

I'm travelling for work next week and then on vacation, but I can take a look at it when I get back. `distutils` is always a pain but there are ways to pass it additional command-line arguments.

**Comment by kayhayen** [comment]
Plus, I am near sure, there is already parameters passed.

The main pain point is the pattern matching done by Nuitka is based on module names, and you are going to have file names right there to preserve. But I think it might be possible to ask for every filename the function that tells you its full module name, and then to use the matching functions, shouldn't be too hard that way.

I am going to push API updates later this weekend to the functions, but I am e.g. talking about `matchesModuleNameToPatterns` and `getModuleNameAndKindFromFilename` which should be used. These return tuples, but are directly what and all you need.

**Comment by kayhayen** [comment]
There is now a `setuptools` integration, that should make this easy. Just produce a wheel without tests, and install it and run your tests. By default, wheel production currently excluded all '`*.tests` packages from compilation.
