### ISSUE TITLE
Nuitka built application can not find resources file under `onefile` mode both in linux and windows, and crash under `windows 7 x64` operating system

### ISSUE THREAD

**Issue by r00t1900** [Nuitka/Nuitka#1640]
## version
- nuitka: 0.9.0
- python: 3.8
- os: ubuntu/windows

## problem
I found this issue when I compile pyqt5 application with `--onefie` parameter. In either windows or linux, it appears that the single binary application raise `no such a file or directory: <resources path>` error. So I need to manually copy all necessary resources file defined in nuitka command(by parameters `--include-data-file` and `--include-data-dir`) so the `--onefile` is not a really one file.

## expected
- point out my problems on nuitka command that cause this issue
- discuss  and form a solution I can compile application in a real `onefile` mode with all defined and required resources added so that I can distribute application with a single `.bin` or `.exe` file :)

> by the way, with nuitka=0.9.0, python=3.8 and os=windows 7 x64,  binary executable compiled with `--onefile` will crash and can not use, while `--standalone` works well in windows 7 and both `--onefile` and `--standalone` works well in windows 10 or later. I would also like to figure out why is that.

**Comment by r00t1900** [comment]
> Regarding Windows 7, please make that a separate issue. I do have users on Windows 7, but it might have regressed.
> 
> I am not sure I understand this one, onefile can be used on Qt programs no issue. You didn't fill out the issue template, so I guess, you want me to guess what you did?

properly I did not describe it very well~The point is in windows 7, the `--onefile` compiled binary executable file will crash, while `--standalone` won't. That happen in windows 7, but in windows 10 both `--onefile` and `--standalone` works fine.

Uh, about the sample, should be a copy of code or binary executable?

**Comment by kayhayen** [comment]
I never use binaries provided to me, so only source code, scripts, and instructions please.

**Comment by r00t1900** [comment]
> I never use binaries provided to me, so only source code, scripts, and instructions please.

- [ui-demo-1.zip](https://github.com/Nuitka/Nuitka/files/9018067/ui-demo-1.zip)

I've share a demo project to you, you can find instruction in `README.md`.

Thanks~

**Comment by kayhayen** [comment]
I guess you didn't consider using options to include your data file in the compilation. There is a section in the user manual about that and onefile, one how to find it. You code is overly optimistic about the current directory it seems.

**Comment by kayhayen** [comment]
It means you need to read the resources I pointed out.
