### ISSUE TITLE
Sklearn GridSearchCV not working

### ISSUE THREAD

**Issue by interseba5** [Nuitka/Nuitka#1641]
* Nuitka version, full Python version, flavor, OS, etc. as output by this
  command (it does more than you think, and we are adding more all the time):

  > python -m nuitka --version
0.9
Commercial: None
Python: 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Python39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

* How did you install Nuitka and Python

Installed using pip

* The specific PyPI names and versions
pip 22.0.4 from c:\python39\lib\site-packages\pip (python 3.9)

  > python -m pip freeze
scipy==1.8.0
xgboost==1.6.0
scikit-learn==1.0.2

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

```python
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.datasets import load_iris

X, y = load_iris(return_X_y=True, as_frame=True)
clf = XGBClassifier()
learning_rate = [0.05, 0.1, 0.2]
max_depth = [4, 6, 8, 10]
n_estimators = [100, 200, 300]
sample_rate = [0.7, 0.8, 0.9]
colsample_bytree = [0.2, 0.5, 0.7, 0.9, 1.0]
grid = {'n_estimators': n_estimators,
        'learning_rate': learning_rate,
        'max_depth': max_depth,
        'colsample_bytree': colsample_bytree,
        'subsample': sample_rate}
clf_tuned = GridSearchCV(estimator=clf, param_grid=grid,verbose=verbose, n_jobs=-1)
clf_tuned.fit(X,y)
```

* Provide in your issue the Nuitka options used

python -m nuitka --enable-plugin=numpy --enable-plugin=tk-inter --nofollow-import-to=IPython,dask,tensorflow --mingw64 --standalone main.py

**Explanation**
When i try to use GridSearchCv of sklearn i obtain this error:
```
Fitting 5 folds for each of 540 candidates, totalling 2700 fits
08:57:41.673 [i] T[0x5120] - main.<module __parents_main__>: Command given: D:\main.dist\main.exe --multiprocessing-fork 4524
08:57:41.673 [i] T[0x3550] - main.<module __parents_main__>: Command given: D:\main.dist\main.exe --multiprocessing-fork 4348
08:57:41.673 [i] T[0x2dd0] - main.<module __parents_main__>: Command given: D:\main.dist\main.exe --multiprocessing-fork 4652
usage: pm [-h] {train,deploy} ...
pm: error: argument command: invalid choice: '4652' (choose from 'train', 'deploy')
08:57:41.688 [i] T[0xe84] - main.<module __parents_main__>: Command given: D:\main.dist\main.exe --multiprocessing-fork 4588
08:57:41.688 [i] T[0x3820] - main.<module __parents_main__>: Command given: D:\main.dist\main.exe --multiprocessing-fork 4556
08:57:41.688 [i] T[0x6754] - main.<module __parents_main__>: Command given: D:\main.dist\main.exe --multiprocessing-fork 4352
usage: pm [-h] {train,deploy} ...
pm: error: argument command: invalid choice: '4348' (choose from 'train', 'deploy')
usage: pm [-h] {train,deploy} ...
pm: error: argument command: invalid choice: '4524' (choose from 'train', 'deploy')
usage: pm [-h] {train,deploy} ...
pm: error: argument command: invalid choice: '4588' (choose from 'train', 'deploy')
usage: pm [-h] {train,deploy} ...
08:57:42.673 [e] T[0x6634] - main.<module>: [Errno 22] Invalid argument
08:57:42.688 [e] T[0x6634] - main.<module>: Traceback (most recent call last):
  File "D:\MAIN~1.DIS\joblib\parallel.py", line 935, in retrieve
  File "D:\MAIN~1.DIS\joblib\_parallel_backends.py", line 542, in wrap_future_result
  File "D:\MAIN~1.DIS\concurrent\futures\_base.py", line 445, in result
  File "D:\MAIN~1.DIS\concurrent\futures\_base.py", line 390, in __get_result
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.
```
This means that when GridSearchCv try to spawn the parallels thread it tries to execute again main.exe (that is the compiled main.py) whit the additional option  --multiprocessing-fork. This is wrong given the fact that you dont have to execute the main.exe but you have to execute the GridSearchCv code.
The `pm: error: argument command: invalid choice: '4348' (choose from 'train', 'deploy')` is given because in my code during the initialization phase I parse some arguments from the command line and obviously the pid of a process isn't a valid argument.

Doing some further investigation i found out that the correct command that GridSearchCv use is: 
```
C:\Python39\python.exe -c from joblib.externals.loky.backend.popen_loky_win32 import main; main() --multiprocessing-fork 4676
```
Instead, the compiled exe when trying to spawn a new process it gives this command:
```
D:\main.dist\main.exe --multiprocessing-fork 4588
```

**Comment by kayhayen** [comment]
The multiprocessing module is supported by Nuitka in general, but this way of doing it is not yet supported. Not sure what the purpose of that is.

**Comment by kayhayen** [comment]
If somebody were to figure out, where this happens in the code, maybe joblib, that would be nice.

**Comment by KevinRodriguez777** [comment]
this particular issue has gone away in lastest version of nuitka, however a different one came up, i'll make a  new issue for that and closing this one

**Comment by kayhayen** [comment]
Yeah, Nuitka-Watch is covering this even.
