### ISSUE TITLE
Using variables assigned from immutable constants that are not bool, get corrupted by boolean checks

### ISSUE THREAD

**Issue by statfs** [Nuitka/Nuitka#1642]
This problem is the compatibility with SimpleITK, It seems that Nuitka will change the code inside simpleITK ?
python -m nuitka --version
> 0.9
Commercial: None
Python: 3.7.0 (default, Jun 28 2018, 07:39:16)
Flavor: Anaconda Python
Executable: /Users/guo/opt/miniconda3/envs/py3/bin/python
OS: Darwin
Arch: x86_64

The error from the generated binary is:
> Traceback (most recent call last):
  File "/var/folders/gd/_q348dc554n0ppb3twdjl3m80000gp/T//onefile_99562_1656493322_414341/sitk.py", line 1, in <module>
    import SimpleITK as sitk
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/var/folders/gd/_q348dc554n0ppb3twdjl3m80000gp/T//onefile_99562_1656493322_414341/SimpleITK/__init__.py", line 21, in <module SimpleITK>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/var/folders/gd/_q348dc554n0ppb3twdjl3m80000gp/T//onefile_99562_1656493322_414341/SimpleITK/_version.py", line 54, in <module SimpleITK._version>
  File "/var/folders/gd/_q348dc554n0ppb3twdjl3m80000gp/T//onefile_99562_1656493322_414341/SimpleITK/_version.py", line 35, in _get_pep386version
TypeError: can only concatenate str (not "bool") to str

And if I rewrite the "sitk_patch" and "sitk_tweak", the new binary could run normally. 

There is a original "_version.py" in simpleitk
    
    def _get_pep386version():
        """Uses configured CMake version variable to construct a pep 386 compliant version string."""

        sitk_major = "2"
        sitk_minor = "1"
        sitk_patch = "1"
        sitk_tweak = "2"
        sitk_rc = ""
        sitk_post = ""
        sitk_dev = ""
        sitk_hash = "5627c"

        version = sitk_major + "." + sitk_minor

        if sitk_patch:
            version += "." + sitk_patch
            if sitk_tweak:
                version += "." + sitk_tweak

        if sitk_rc:
            version += sitk_rc

        if sitk_post:
            version += ".post" + sitk_post
        elif sitk_dev:
            version += ".dev" + sitk_dev

        # Local Version Identifier
        if sitk_hash and "ON" not in ['1', 'ON']:
            version += "+g" + sitk_hash

        return version

    __version__ = _get_pep386version()

And I have to add a dirty statement now:

     if sitk_patch:
       # dirty start
        if type(sitk_patch) is  bool:
            sitk_patch = "1"
       # dirty end
        version += "." + sitk_patch
        if sitk_tweak:
            version += "." + sitk_tweak

**Comment by kayhayen** [comment]
It does not "change" the code, it compiles it wrongly, thanks for the example, I reproduce it.

**Comment by kayhayen** [comment]
Amazing grace, that seems impossible. The first 2 optimization it does are these:

> Nuitka-Optimization:INFO: Mini.py:6 : new_constant : Predicted compile time constant truth value.
> Nuitka-Optimization:INFO: Mini.py:16 : new_raise : Replaced operator 'Add' with <ShapeTypeStr str STR> <ShapeTypeBool bool OBJECT> arguments that cannot work.

I am very confused how that happens. I managed to get down to this:

```
def f():
    sitk_patch = "1"
    version = "2"

    if sitk_patch:
        version += "." + sitk_patch

    return version

print(f())
```

**Comment by kayhayen** [comment]
Ok, now I know, this is mistake done in an optimization added for 0.9, the boolean evaluation of a variable is now forwarded to the assign node source, which then chooses to replace itself with the boolean value, in its current parent, corrupting the original assignment. Very bad, but managable. I had a similar issue with calls through variables corrupting the tree, but here it seems to not cause a crash.

**Comment by kayhayen** [comment]
So, on factory there is a fix for this. Once it passes my CI, there will be a rebase of `main` and a hotfix with it.

**Comment by kayhayen** [comment]
Part of the 0.9.2 hotfix release I just made.
