### ISSUE TITLE
Dynamically imported modules' script fails with AttributeError: 'NoneType' object has no attribute 'load_module'

### ISSUE THREAD

**Issue by Crowfunder** [Nuitka/Nuitka#1646]
**Issue description**

When compiled with Nuitka, \_\_init__.py of locally imported module fails with error:
```
Traceback (most recent call last):
  File "C:\Testdir\MAIN~1.DIS\main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Testdir\MAIN~1.DIS\modules\__init__.py", line 12, in <module modules>
AttributeError: 'NoneType' object has no attribute 'load_module'
```
Otherwise everything works

**Nuitka version, full Python version, flavor, OS, etc:**

```
0.9
Commercial: None
Python: 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

**How did you install Nuitka and Python**

pip both on global installation and venv

**Short, Self Contained, Correct, Example**

Project structure:
main.py
modules/\_\_init__.py
modules/script.py

Contents of main.py do not matter, it just uses `import modules`
For example:
```py
import modules

print('List modules below: ')
for module in modules.__modules__:
    print(module)
```
Contents of script.py do not matter as well.
Contents of \_\_init__.py :
```py
import pkgutil

__modules__ = {}
for loader, module_name, is_pkg in pkgutil.walk_packages(__path__):
    _module = loader.find_module(module_name).load_module(module_name)
    __modules__[module_name] = _module
    globals()[module_name] = _module
```

**Nuitka options used**
```
python -m nuitka --include-plugin-directory=modules --standalone main.py
```

 **Compilation log**
```
Nuitka-Options:INFO: Used command line options: --include-plugin-directory=modules --standalone main.py
Nuitka:INFO: Starting Python compilation with Nuitka '0.9' on Python '3.10' commercial grade 'not installed'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'urllib.request' added 'http.client,http.cookiejar'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'socket' added '_socket'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'shelve' added 'dbm.dumb'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pathlib' added 'ntpath,posixpath'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'importlib.metadata' added 'email'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'concurrent.futures.process' added 'multiprocessing,multiprocessing.connection'.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module '_asyncio' added 'asyncio'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'quopri' added 'py_compile'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'encodings' added 'encodings.idna,encodings.base64_codec,encodings.hex_codec,encodings.rot_13'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 15 modules (no progress information available).
Nuitka-Scons:INFO: Compiled 30 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 15
Nuitka:INFO: Keeping build directory 'main.build'.
Nuitka:INFO: Successfully created 'main.dist\\main.exe'.
```

**Note**
If used with `--nofollow-import-to=modules` and without `--include-plugin-directory=modules`, and uncompiled `modules` folder gets placed in main.dist, everything works as intended.

**Note 2**
If used without `--include-plugin-directory=modules` the error does not occur, however the `script.py` does not get imported.
For example, if main.py also contains line:
`modules.script.start()`
And script.py contains:
```py
def start():
   print('Module start invoked')
```
Instead the executable returns error:
`AttributeError: module 'modules' has no attribute 'script'`

**Comment by kayhayen** [comment]
You can do `--include-package=modules` and they will all be importable afterwards, as if you had added the directory to `sys.path`. After that, you can use `pkgutil.iter_packages` to find them, or maybe even `pkgutil.walk_packages`. Maybe I never tried that.

Including them as a plugin folder strips it of the package name, which is mainly why it wasn't working for you.

**Comment by kayhayen** [comment]
For loading plugins provided by a user, check out this: https://nuitka.net/doc/user-manual.html#manual-python-file-loading

**Comment by Crowfunder** [comment]
Just wanted to note that despite using the option, `pkgutil.walk_packages` did not work, however `pkgutil.iter_packages` did the job, thanks! 👍🏻

**Comment by Crowfunder** [comment]
For anyone who stumbles upon the same issue, here's a rewritten `__init__.py` that works with Nuitka and gives *almost* the same result. The only difference is that the original version imports the module object as i.e ` <module 'start' `, where the rewritten one returns `<module 'modules.start'`.

```py
import pkgutil

__modules__ = {}
for module_class in pkgutil.iter_modules(__path__):
    
    module_name = module_class.name
    module_object = pkgutil.resolve_name('modules.' + module_name)
    __modules__[module_name] = module_object
    globals()[module_name] = module_object
```

**Comment by kayhayen** [comment]
Yes, there needs to be something to anchor your search on. I think it is possible to iterate over all modules as well, but you wouldn't be able to tell where they came from, depending on your compilation mode, the `__file__` will now be relative to the binary, and as such useless.

The `pkgutil.resolve_name` is news to me. I guess it needs support from Nuitka too to recognize some otherwise hidden imports. Nuitka is aware of `importlib.import_module` at this time. Not sure if we ever get to a point, where the for loop would be evaluated, but should it be, I guess then it could statically know at compile time which ones these are, but right now you need to help it there.
