### ISSUE TITLE
Cannot reuse already awaited compiled_coroutine

### ISSUE THREAD

**Issue by levesquejf** [Nuitka/Nuitka#165]
Using 0.6.0.1, I just had the following exception: `RuntimeError: cannot reuse already awaited compiled_coroutine`. This is very similar with [Bug #404](http://bugs.nuitka.net/issue404) except it says `compiled_coroutine`instead of `coroutine`.

As for Bug #404, the exception has been raised when another exception was raised (probably some kind of connection issue within aiohttp due to a network connection issue). I don't have much details at this point but since it was fixed in 0.5.32 and never happened since my upgrade to 0.6.0.1, it might be easy to fix. If not, I will try to get more details to reproduce.

**Comment by kayhayen** [comment]
The symptom looks similar, but is actually different. The same fix wouldn't apply.

Definitely need a reproducer, otherwise I cannot know if this is not correct behavior, i.e. if not CPython would have done the same.

**Comment by kayhayen** [comment]
Lack of feedback. Please re-open with reproducer that fails for Nuitka, works for CPython.

**Comment by henrytom1703** [comment]
I have a same this issues. Please reopen this bugs.
Error: cannot reuse already awaited compiled coroutine

**Comment by kayhayen** [comment]
As it is only a symptom it will be another issue. Open a new one with reproducer.

**Comment by levesquejf** [comment]
I am still not able to reproduce but the issue is still there with Python 3.6.8 and Nuitka 0.6.2. As soon as I have a reproducer, I will open a new issue.

**Comment by Eierkopp** [comment]
The following code triggers it for me:

    #!/usr/bin/python3

    import asyncio
    import traceback

    async def test():
        try:
            await loop.create_connection(None, "no-such-host", 11111)
        except Exception:
            traceback.print_exc()

    loop = asyncio.get_event_loop()

    loop.run_until_complete(test())

Environment is

    % nuitka3 --version
    0.6.3.1
    Python: 3.7.3 (default, Apr  3 2019, 05:39:12) 
    Executable: /usr/bin/python3
    OS: Linux
    Arch: x86_64

Best regards,

Martin

**Comment by levesquejf** [comment]
Hi @Eierkopp. Looks more like #213. Your compiled code fails on 3.7.3 but works on 3.6.8. If you have code that fails on 3.6.8, it would be great for this issue.

**Comment by levesquejf** [comment]
@kayhayen I have a reproducer for this bug (affecting both 3.6 and 3.7). Can you please reopen this issue? Also, any idea of a timeline to take a look at it? Thanks!

Reproducer: https://github.com/levesquejf/nuitka-asyncio-bug-issue165

**Comment by kayhayen** [comment]
I hope to take a look later today. This seems very reproducible now.

**Comment by levesquejf** [comment]
@kayhayen Here is simpler example using aiodns: https://github.com/levesquejf/nuitka-asyncio-bug-issue165-aiodns

**Comment by levesquejf** [comment]
@kayhayen Another example with asyncio.Event: https://github.com/levesquejf/asyncio_task_already_awaited_bug-issue165-event

**Comment by levesquejf** [comment]
@kayhayen Another example with aiohttp. It is affecting 3.6.8 and it fails even with the latest factory release: https://github.com/levesquejf/asyncio_task_already_awaited_bug-aiohttp2.

**Comment by levesquejf** [comment]
Fixed with 0.6.5 (see #213). Closing issue.
