### ISSUE TITLE
Using virtualenv inside created binaries is unsupported (was distutils.errors.DistutilsModuleError: invalid command 'build')

### ISSUE THREAD

**Issue by ofek** [Nuitka/Nuitka#1652]
```dockerfile
FROM python:3.9

RUN apt update && apt install -y python3 python3-pip build-essential patchelf

RUN pip3 install --upgrade virtualenv
RUN python3 -m virtualenv "$HOME/venv"
ENV PATH "$HOME/venv/bin:$PATH"

RUN git clone --branch factory https://github.com/Nuitka/Nuitka
RUN pip install ./Nuitka
RUN pip install zstandard orderedset

RUN git clone https://github.com/pypa/hatch
WORKDIR /hatch

# install dependencies
RUN pip install . && pip uninstall -y hatch

RUN python -m nuitka --standalone --onefile --onefile-tempdir src/hatch
```

Then:

```
docker build -t hatch-nuitka
docker run --rm hatch-nuitka ./hatch.bin env create
```

```
  File "/tmp/onefile_1_1656857527_764891/virtualenv/discovery/py_info.py", line 90, in __init__
  File "/tmp/onefile_1_1656857527_764891/virtualenv/discovery/py_info.py", line 165, in _distutils_install
  File "/tmp/onefile_1_1656857527_764891/distutils/command/install.py", line 367, in finalize_options
  File "/tmp/onefile_1_1656857527_764891/distutils/cmd.py", line 286, in set_undefined_options
  File "/tmp/onefile_1_1656857527_764891/distutils/dist.py", line 857, in get_command_obj
  File "/tmp/onefile_1_1656857527_764891/distutils/dist.py", line 843, in get_command_class
distutils.errors.DistutilsModuleError: invalid command 'build'
```

Code: https://github.com/pypa/virtualenv/blob/20.15.1/src/virtualenv/discovery/py_info.py#L165

**Comment by ofek** [comment]
Hmm, I see some never-solved issues:

- https://github.com/pyca/cryptography/issues/1323
- https://github.com/xattr/xattr/issues/49

**Comment by ofek** [comment]
Oh 😢  it's dynamically importing https://github.com/python/cpython/tree/3.10/Lib/distutils/command

https://github.com/python/cpython/blob/3.10/Lib/distutils/dist.py#L823-L829

**Comment by ofek** [comment]
Might be impossible to get virtualenv bundled https://github.com/pyinstaller/pyinstaller/issues/6928#issuecomment-1173127202

**Comment by kayhayen** [comment]
I am not sure, I have a chance to understand what this is about. Do you want to bundle Python distutils into a onefile binary and use it to create Python distributions. That would be useless and unsupported.

**Comment by ofek** [comment]
I want to bundle virtualenv (which uses distutils sometimes for now) and use it to create Python virtual environments from the bundled Python

**Comment by ofek** [comment]
@gaborbernat how does that work, do you just copy the executable and modify PYTHONPATH to point to original stdlib?

**Comment by kayhayen** [comment]
Nuitka does not bundle a full Python installation, so there is no way it can create one. If you want to include a Python, you can pretend it's data files, and run it, but I don't see the point of doing that with Nuitka.
