### ISSUE TITLE
0.9.3: FATAL: Error, error exit from AppImage because fuse kernel module was not loaded.

### ISSUE THREAD

**Issue by black-snow** [Nuitka/Nuitka#1654]
Similar or same issue as https://github.com/Nuitka/Nuitka/issues/1622

> uitka:INFO: Downloading 'https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage'.
FATAL: Error, error exit from AppImage because fuse kernel module was not loaded.

with:

```docker
FROM python:3.10.5-bullseye@sha256:850b7f7626e5ca9822cc9ac36ce1f712930d8c87eb31b5937dba4037fe204034

WORKDIR /usr/src/xxx

COPY . .

RUN : \
    && python -m pip install --upgrade pip \
    && python -m pip install pdm \
    && apt update && apt dist-upgrade -y && apt install -y patchelf fuse gcc \
    && python -m pdm sync \
    && :
```

and `pdm` runs:

```shell
python -m nuitka main.py --standalone --onefile -oxxx --assume-yes-for-downloads --linux-onefile-icon=icon.png
```

Worked fine on 0.8.2 (now 0.9.3). Tried bullseye slim before and swapped it for the full-blown one hoping this would fix things. Also had to provide `--linux-onefile` with a custom icon - apparently there's no default icon in the recent python image(?).

```
0.9.3
Commercial: None
Python: 3.10.5 (main, Jun 23 2022, 10:42:52) [GCC 10.2.1 20210110]
Flavor: Unknown
Executable: /usr/local/bin/python
OS: Linux
Arch: x86_64
Distribution: Debian 11
```
via WSL2 on Win10.

@kayhayen btw, looking forward to 1.0.0. And congrats on the latest improvements!

Will try again with the 1.x RC

**Comment by black-snow** [comment]
Works fine with 1.0rc4 - closing this.

**Comment by kayhayen** [comment]
Yes, with 1.0 no longer using AppImage, but our own bootstrap.
