### ISSUE TITLE
Question: How to package additional binary into onefile

### ISSUE THREAD

**Issue by statfs** [Nuitka/Nuitka#1656]
I have to call one executable binary and one dynamic library in my python script, and I put them into a dir named "data/resources/",
calling by "subprocess.Popen([binary_name])" and "ctypes.cdll.LoadLibrary(lib_name)" using relative path.

It seems all right without packaging, either on Mac or on Windows, until I use this command to build a package:
> python -m nuitka --mingw64 --standalone --show-progress --show-memory --enable-plugin=pyqt5 --onefile  --enable-plugin=numpy --show-scons --lto=no  --include-data-dir=data/resources=data/resources --windows-icon-from-ico=data/resources/logo.ico entry.py
> OR
> python -m nuitka --standalone --show-progress --show-memory --enable-plugin=pyqt5 --onefile  --enable-plugin=numpy --show-scons   --include-data-dir=data/resources=data/resources --macos-app-icon=data/resources/logo.ico entry.py

I can find the binary files in in entry.dist, but the new package cannot. unless I put them in the current work directory( but I hope to package them all into one file).

**Comment by statfs** [comment]
Just for example: 

I have a wrapper.py and a dir(data/res/gcc, data/res/gcc.exe inside). 
- data/res/gcc is copied from /usr/bin/gcc in mac
- data/res/gcc.exe is copied from C:\mingw64\bin\gcc.exe in windows.

I want to distribute a binary use one source code like:
- one wrapper.bin file only for mac.
- one wrapper.exe file only for windows.

this is the code of wrapper.py
```
import platform
import subprocess

def wrapper():
    try:
        current = platform.system().lower()
        if current == "darwin":
            binary = "./data/res/gcc"
        elif current == "windows":
            binary = './data/res/gcc.exe'
        process = subprocess.Popen([binary,"-v"],
                                   stdout=subprocess.PIPE,
                                   stderr=subprocess.PIPE)
        stdout, stderr = process.communicate()
        print(stderr)
        print(stdout)
    except Exception as e:
        print(str(e))

if __name__ == "__main__":
    wrapper()

```

if is it possible for --onefile?

**Comment by statfs** [comment]
I am trying to use PyInstaller to see if there is similar problem or not. 
The pyinstaller provide a switch "--add-binary" to support the binary file packaging. 
I generated one binary file using a modified version of wrapper.py, which also works with nuitka.


```
import platform
import subprocess
import sys
import os
import stat

def resource_path(relative_path):
    base_path = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
    return os.path.join(base_path, relative_path)

def make_executable(path):
    st = os.stat(path)
    os.chmod(path, st.st_mode | stat.S_IEXEC)

def wrapper():
    try:
        current = platform.system().lower()
        if current == "darwin":
            binary = "ls-rename"
        elif current == "windows":
            binary = './data/res/gcc.exe'
        import os
        binary = resource_path(binary)
        if os.path.exists(binary):
            print("exist: ", binary)
            make_executable(binary)
        else:
            print("no exist: ", binary)
        process = subprocess.Popen([binary,"-v"],
                                   stdout=subprocess.PIPE,
                                   stderr=subprocess.PIPE)
        stdout, stderr = process.communicate()
        print(stderr)
        print(stdout)
    except Exception as e:
        print(str(e))

if __name__ == "__main__":
    wrapper()
```

**Comment by statfs** [comment]
Thank you, kayhayen.
It seems that my code works for now on windows. 
Just for reference who may occur to this.

**Comment by kayhayen** [comment]
The change to onefile is on factory, and will be in 1.1, so that is off the table at that point. I will not make it a hotfix I believe. User options for adding DLLs and executables, are going to be Yaml driven. Right now, the `dlls` section of Yaml does not preserve the `x` bit though, need to add that too.

**Comment by kayhayen** [comment]
Basically, watch out for when we document the Yaml file with examples, adding DLLs and executables with be in the examples.

**Comment by kayhayen** [comment]
The Yaml format now supports binaries, and binaries get an x bit, and the change is on develop right now.

**Comment by kayhayen** [comment]
This is part of the stable release 1.1 that I just made.

**Comment by kayhayen** [comment]
This makes it ever so more urgent, that we get the Yaml file format documented.

**Comment by deajan** [comment]
Sorry to piggyback the thread, but the title "how to package additional binary into onefile" is exactly the question I wanted to ask.
I'm building a onefile executable, that contains another executable it will call via subprocess.
I'm adding the executable with `--include-data-file` option as of today, but this doesn't retain executability.
So far this technique works for Windows, but will fail with a permission error on Linux.
Is there any way to bundle executable files into a onefile build ? Something like `--include-exe-file` perhaps ?

**Comment by kayhayen** [comment]
Like I said, only Yaml files will allow it at this time. Currently, there is only one example in standard

```
- module-name: 'cefpython3'
  data-files:
    dirs:
      - 'locales'
    patterns:
      - '*.bin'
      - '*.pak'
      - '*.dat'

  dlls:
    - from_filenames:
        prefixes:
          - 'subprocess'
        executable: 'yes'
      when: 'win32'
    - from_filenames:
        prefixes:
          - ''
      when: 'win32'
```

That is probably very similar. The `executable` bit is not even in the docs yet, going to add it now.

**Comment by kayhayen** [comment]
@deajan Yes, done at the right moment, it will work as well. Ever since the executable flag got added, this is ultimately how it is determined. I am not sure it preserves the x-bit on data files though, or that it should do it. Also, on Win32 there is no x-bit, I am kind of surprised to see it used in that config I cited with Win32. It probably will make sense most on non-Win32.
