### ISSUE TITLE
Nuitka only works on Windows 7 only with Python flavors that actually support Windows 7, Anaconda is not one of them

### ISSUE THREAD

**Issue by r00t1900** [Nuitka/Nuitka#1658]
## About issue

This is an already reported issue but not solved: 
- https://github.com/Nuitka/Nuitka/issues/1640#
- I've not try the develop version

## Nuitka version

  > python -m nuitka --version

```bash
0.9
Commercial: None
Python: 3.8.13 (default, Mar 28 2022, 06:59:08) ]MSVC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\<username>\miniconda3\envs\<env-name>\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 7
```

## Installation reproducing
- Python:
  - Download [miniconda3](https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/Miniconda3-py38_4.10.3-Windows-x86_64.exe) from anaconda mirror site and then install as normal.
  - create python eivironment with `conda create -n <env-name> python=3.8`

- Nuitka: 
  - Download source code archive [Nuitka-0.9.0.tar.gz](https://github.com/Nuitka/Nuitka/archive/refs/tags/0.9.tar.gz) from PyPi or github repository
  - `pip install Nuitka-0.9.0.tar.gz`

## The specific PyPI names and versions

- pyqt5~=5.15.2
- qtawesome
- loguru

> Actually, even with no extra dependencies and compile the hello world project, this problem will still happen. So I think that it is not a package problem or a resource file problem.

## Nuitka command options

```
cd src
nuitka --output-dir=../build --plugin-enable=pyqt5 --windows-icon-from-ico=res/icon/main.ico --include-data-dir=res=res --include-data-file=config.json=config.json --include-package-data=qtawesome --onefile --windows-disable-console main.py
```
## Code example

- here [ui-demo-1.zip](https://github.com/Nuitka/Nuitka/files/9050605/ui-demo-1.zip)

## Problem description

With the steps shown above and after reading user manual, I still get `App Crashed` under Windows 7. As your replies in previous issue, I check the "include data file for `--onefile`" related options again and make sure that I've add them but I still got error. What strange is the `--standalone` works well for Windows 7 and both `--onefile` and `--standalone` work well for Windows 10.

Would you mind trying to build my code in windows 7 to have a deep look? 

**Sincerely grateful!**

**Comment by kayhayen** [comment]
Nuitka can only support, what the specific Python supports, and yours does not support Windows 7 according to their docs. Using Nuitka won't change that.
