### ISSUE TITLE
Windows use qt-material theme invalid

### ISSUE THREAD

**Issue by yilongmd** [Nuitka/Nuitka#1666]
`python main.py`
![图片](https://user-images.githubusercontent.com/6745227/178070674-e447b6d1-bee5-46d2-ac3f-d66d33f77345.png)

`nuitka --standalone --windows-disable-console --windows-icon-from-ico=logo.ico --enable-plugin=pyside6  --onefile  main.py`

Run main.exe:
![图片](https://user-images.githubusercontent.com/6745227/178071057-b6a1252a-fee3-4510-900f-d056d61e5d8b.png)

Code:
`from PySide6.QtWidgets import QApplication, QMainWindow
from PySide6.QtUiTools import QUiLoader
from qt_material import apply_stylesheet

########################################################################
class ShowUI(QMainWindow):
    # ----------------------------------------------------------------------
    def __init__(self):
        """"""
        super().__init__()
        self.main = QUiLoader().load('window.ui', self)

if __name__ == '__main__':
    app = QApplication()

    apply_stylesheet(app, theme='dark_teal.xml')

    frame = ShowUI()
    frame.main.show()

    app.exec_()`

**Comment by kayhayen** [comment]
Where is `dark_teal.xml` supposed to come from?

**Comment by yilongmd** [comment]
![image](https://user-images.githubusercontent.com/6745227/178105663-26dc3bc7-1e73-40e1-a9d5-212916c75963.png)
![image](https://user-images.githubusercontent.com/6745227/178105694-90a2cd8c-faa9-4956-9a3a-a189fc722318.png)

dark_teal.xml in pip install site-packages

**Comment by yilongmd** [comment]
> Where is `dark_teal.xml` supposed to come from?
![image](https://user-images.githubusercontent.com/6745227/178105846-e6e0c87b-0280-4564-8a4b-6d82a1b59902.png)
![image](https://user-images.githubusercontent.com/6745227/178105859-de0ea5ff-a316-45a3-9022-fc8d044b9c82.png)


dark_teal.xml in pip install site-packages
`pip install qt-material `

**Comment by yilongmd** [comment]
> 

Need other commands to be included in the program?

**Comment by kayhayen** [comment]
I don't get what your screenshots are supposed to tell me. I guess I wanted a file path. So are you saying it's part of a PyPI package called `qt-material`. Did you try `--include-package-data="qt_material"` which would include the files. What I don't get is how the program you posted, finds it though.

**Comment by kayhayen** [comment]
I guess there might be something in `window.ui` that you didn't post?

**Comment by yilongmd** [comment]
--include-package-data="qt_material"  Then it's ok

**Comment by yilongmd** [comment]
theme:
`pip install qt-material`
it's part of a PyPI package called qt-material

**Comment by kayhayen** [comment]
Ok, can you have a look at this file and make a PR with a change that automates that? Checkout this and nearby: https://github.com/Nuitka/Nuitka/blob/7a4999a3e7c90342f70f6a1cf92790113ae4afda/nuitka/plugins/standard/standard.nuitka-package.config.yml#L84

**Comment by Kndy666** [comment]
@yilongmd If you cancel the argument `--windows-disable-console` you will find the error comes from the the external file isn't existed.The error is like this `WARNING:root:YourDirectory\qt_material\themes\dark_teal.xml not exist!`
Just try to copy the files from the `\site-packages\qt_material` manually to the output folder and address this issue.

**Comment by kayhayen** [comment]
@Kndy666 For copying the data files, Nuitka options shall be used, like the one I already indicated, or others. Simply copying will limit the applicability to other use cases. What's really needed here, is the Yaml configuration for it to happen automatically.

**Comment by Kndy666** [comment]
Yes, I didn't consider the applicability and just simply copied the files.Use the nuitka options will be better to address it.

**Comment by kayhayen** [comment]
But really the best solution is for somebody to create PR that describes the data directory of the packages and then everybody just immediately has it out of the box.

What's also something to take out of this is, that for unhandled exceptions, in no console mode, we should display something in a dialog. Nuitka is encouraging to disable the console, and in some cases, it's even required (on macOS mostly), but still, it would be more helpful for this kind of problem to see that error.

**Comment by yilongmd** [comment]
@kayhayen Through configuration, the author has helped me solve the problem

**Comment by yilongmd** [comment]
@Kndy666 Through configuration, the author has helped me solve the problem

**Comment by yilongmd** [comment]
@kayhayen 
I don't know how to create PR, can you please give me a tutorial

**Comment by yilongmd** [comment]
Do you want to manually modify this file after creation and then submit PR?
`Nuitka/nuitka/plugins/standard/standard.nuitka-package.config.yml`

**Comment by kayhayen** [comment]
I am pretty sure, Github has better tutorials than I could ever make on how to create a PR. Start with cloning the git repo, then read `CONTRIBUTING.md` there. However I fear, this is not geared towards this use case at all yet. I will try and add something that makes it easier for this kind of contribution.

However, yes, that file needs to have information added about the data directory or files of that package.

Please try it, and report your problems while doing it. Then I know what the docs should contains. :)

**Comment by kayhayen** [comment]
This will make it straight to 2.0.2 too, once released, hopefully soon.
