### ISSUE TITLE
RuntimeError: super(): arg[0] deleted

### ISSUE THREAD

**Issue by jamesstidard** [Nuitka/Nuitka#167]
Hi,

I've ran across `RuntimeError` when using Nuitka with `pyyaml==3.13` on one of it's [calls to `super()`](https://github.com/yaml/pyyaml/blob/release/3.13/lib3/yaml/constructor.py#L204).

The full error message I get is a `RuntimeError: super(): arg[0] deleted` which I guess has something to do with it its reference to self when calling its parent.

### enviroment
I'm running this in a docker container so nuitka is being ran on what should appear to it as the system python. My base image is the python:3.7 one. Nuitka and PyYAML were installed by pipenv with the `--system` flag within the container. Which should be equivalent to a regular pip install to the system interpreter.

### version
I've tried this on both the release 0.6.2 as well as the develop branch.

0.6.1rc4
Python: 3.7.0 (default, Sep  5 2018, 03:25:31) 
Executable: /usr/local/bin/python
OS: Linux
Arch: x86_64

### example
```python
# main.py
import yaml
from io import StringIO


some_yaml = StringIO("""\
men: [John Smith, Bill Jones]
women:
  - Mary Smith
  - Susan Williams
""")


if __name__ == "__main__":
    print(yaml.load(some_yaml))
```

```sh
$ python -m nuitka main.py --standalone
```

```sh
$ ./main.dist/main
Traceback (most recent call last):
  File ".../main.dist/main.py", line 14, in <module>
  File ".../main.dist/yaml/__init__.py", line 72, in load
  File ".../main.dist/yaml/constructor.py", line 37, in get_single_data
  File ".../main.dist/yaml/constructor.py", line 46, in construct_document
  File ".../main.dist/yaml/constructor.py", line 398, in construct_yaml_map
  File ".../main.dist/yaml/constructor.py", line 204, in construct_mapping
RuntimeError: super(): arg[0] deleted
```

Let me know if there are any more details I can provide.

**Comment by kayhayen** [comment]
This could be a side effect of a recent change that impacts built-in resolution if a star import is present. It would make it possible for super() to be used the Python implementation which depends on things that are not true for compiled functions. Normally "super" would be resolved to the compiled replacement.

Only a suspect, I will check it and try to release a fix over the weekend.

**Comment by kayhayen** [comment]
I saw your link just now: it has `from .error import *` and my star import code is then disabling optimization for all built-in names, but that's too harsh, a few like super, locals, globals, probably should still be trusted.

Yours,
Kay

**Comment by jamesstidard** [comment]
@kayhayen ah right. I'd like to be able to make a pull request for this, but I'm still pretty ignorant to the code base. Will try to read through your developer documentation & the code on the weekend.

Thanks.

**Comment by kayhayen** [comment]
@jamesstidard You are welcome, this one would probably been a bit hard to find, basically there was already a list of names that are to still be converted to built-in references even in the face of start imports, but super wasn't on the list yet.

```
--- a/nuitka/nodes/VariableRefNodes.py
+++ b/nuitka/nodes/VariableRefNodes.py

-_hard_names = ("dir", "eval", "exec", "execfile", "locals", "vars")
+_hard_names = ("dir", "eval", "exec", "execfile", "locals", "vars", "super")

``` 

That is where from mere variable references of global names, things are converted potentially to built-in variables in case of module variables not set. Star imports make this unreliable for as long as we do not analyse the __all__ of the imported module. Coming eventually for sure, but not there right now.

So that is fixed on factory now and should make it into the next pre-release, probably coming over the weekend: 

You can try it out if you like to: http://nuitka.net/doc/factory.html

Yours,
Kay

**Comment by kayhayen** [comment]
Just released.

**Comment by jamesstidard** [comment]
@kayhayen gave this a shot this morning with 0.6.3 and it works. Appreciate the fix, thank you.

**Comment by kayhayen** [comment]
I totally can see how nobody is ever going to get numbers like 0.6.0.3 right. :)

Yours,
Kay

**Comment by jamesstidard** [comment]
Ah, that's just me being lazy and think I've remembered right. Bad with dates as well, so I'd still probably get the `year.month.day.build` format wrong as well :).
