### ISSUE TITLE
Question:lto1.exe: out of memory allocating 65536 bytes

### ISSUE THREAD

**Issue by camelot2013** [Nuitka/Nuitka#1670]
I build my program by Nuitka. The compilation process is normal, but the last LD process is wrong
**WORKS:** 
Win10 (64bit)
Python 3.7.3
Nuitka 0.9.4
pyside6 6.2.2.1

**FAILS:**
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 983 modules (no progress information available).

lto1.exe: out of memory allocating 65536 bytes
lto-wrapper.exe: fatal error: C:\mingw64\bin\gcc.exe returned 1 exit status
compilation terminated.
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: error: lto-wrapper failed
collect2.exe: error: ld returned 1 exit status

**Comment by kayhayen** [comment]
Read the user manual on low memory, and report with issue template next time.
