### ISSUE TITLE
Compiler crash for "str.format" usage that does use result (seen in package shodan)

### ISSUE THREAD

**Issue by xqdoo00o** [Nuitka/Nuitka#1672]
1.0rc6
Commercial: None
Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
Flavor: Debian Python
Executable: /root/cc/bin/python
OS: Linux
Arch: x86_64
Distribution: Debian 11

I use shodan for some test. and I installed it by
`pip install shodan`

When I type in the command `python3 -m nuitka --standalone sd.py`
then cause AssertionError
Here is the Traceback
```
Nuitka:INFO: Generating source code for C backend compiler.
C Source Generation: 54.5%|█████████████▋           | 42/77, shodan.helpers  Problem with <Node 'STATEMENT_EXPRESSION_ONLY' with {'expression': 'EXPRESSION_STR_OPERATION_FORMAT'}> at /root/cc/lib/python3.9/site-packages/shodan/helpers.py:167
Problem with <Node 'STATEMENT_CONDITIONAL'> at /root/cc/lib/python3.9/site-packages/shodan/helpers.py:166
Problem with <Node 'STATEMENT_TRY' with {'aborting': True}> at /root/cc/lib/python3.9/site-packages/shodan/helpers.py:145
Nuitka:WARNING: Problem creating function code 'shodan$helpers$$$function__8_humanize_bytes'.
```
Thanks!

Update:  Just try this simply test.py with `python3 -m nuitka test.py`
```
def humanize_bytes(byte_count, precision=1):
    if byte_count == 1:
        return '1 byte'
    if byte_count < 1024:
        '{0:0.{1}f} {2}'.format(byte_count, 0, 'bytes')

    suffixes = ['KB', 'MB', 'GB', 'TB', 'PB']
    multiple = 1024.0  # .0 to force float on python 2
    for suffix in suffixes:
        byte_count /= multiple
        if byte_count < multiple:
            return '{0:0.{1}f} {2}'.format(byte_count, precision, suffix)
    return '{0:0.{1}f} {2}'.format(byte_count, precision, suffix)
```

**Comment by kayhayen** [comment]
That is indeed correct, and interestingly happening with the stable version too, I was kind of assuming this to be a regression of develop, as we touched the C types usage a lot there.

**Comment by kayhayen** [comment]
The following upstream code is rather unusual:

```
    if byte_count < 1024:
        '{0:0.{1}f} {2}'.format(byte_count, 0, 'bytes')
```

The result of format is not used, you might want to tell them about it. That however explains, why we have escaped noticing the bug so far. In this case, a built-in `str.format` is used without the proper object to result type conversion, which then runs into attempting to release a void value.

**Comment by kayhayen** [comment]
This is fixed on factory branch: https://nuitka.net/doc/factory.html

I need to contemlate making another hotfix, unfortunately I just did one earlier today.

**Comment by xqdoo00o** [comment]
Thanks!

**Comment by kayhayen** [comment]
This is part of 1.0 release.

**Comment by kayhayen** [comment]
Actually was already in 0.9.6 as well.
