### ISSUE TITLE
Nuitka can't run on Android termux 

### ISSUE THREAD

**Issue by Linux-aarch** [Nuitka/Nuitka#1673]
I have ```Android termux``` and I already install **nuitka**.
I already check nuitka version **python -m nuitka --version**
```
python -m nuitka --version                           ─╯
Nuitka:WARNING: Cannot detect Linux distribution, this may
Nuitka:WARNING: prevent optimization.
1.0rc7
Commercial: None
Python: 3.10.5 (main, Jun  7 2022, 03:52:12) [Clang 12.0.8 (https://android.googlesource.com/toolchain/llvm-project c935d99d7
Flavor: Unknown
Executable: /data/data/com.termux/files/home/venv/venv/bin/python
OS: Linux
Arch: aarch64
Distribution: Unknown None
```
But my question is that why nuitka can't compile my python file
When I compile a **python projects** using **nuitka**

```
python -m nuitka drop.py                             ─╯
Nuitka:WARNING: Cannot detect Linux distribution, this may
Nuitka:WARNING: prevent optimization.
Nuitka-Options:INFO: Used command line options: drop.py
Nuitka-Options:WARNING: You did not specify to follow or
Nuitka-Options:WARNING: include anything but main program.
Nuitka-Options:WARNING: Check options and make sure that is
Nuitka-Options:WARNING: intended.
Nuitka:WARNING: Using very slow fallback for ordered sets,
Nuitka:WARNING: please install 'ordered-set' PyPI package
Nuitka:WARNING: for best Python compile time performance.
Nuitka:INFO: Starting Python compilation with Nuitka '1.0rc7' on Python '3.10' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:WARNING: Cannot detect Linux distribution, this may
Nuitka:WARNING: prevent optimization.
Nuitka:INFO: Running C compilation via Scons.
Nuitka:WARNING: Cannot detect Linux distribution, this may
Nuitka:WARNING: prevent optimization.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
clang-14: error: unknown argument: '-fpartial-inlining'
clang-14: error: unknown argument: '-ftrack-macro-expansion=0'
clang-14: error: unknown argument: '-fcompare-debug-second'
clang-14: error: unknown argument: '-fpartial-inlining'
clang-14: error: unknown argument: '-ftrack-macro-expansion=0'
clang-14: error: unknown argument: '-fcompare-debug-second'
clang-14: error: unknown argument: '-fpartial-inlining'
clang-14: error: unknown argument: '-ftrack-macro-expansion=0'
clang-14: error: unknown argument: '-fcompare-debug-second'
clang-14: error: unknown argument: '-fpartial-inlining'
clang-14: error: unknown argument: '-ftrack-macro-expansion=0'
clang-14: error: unknown argument: '-fcompare-debug-second'
clang-14: error: unknown argument: '-fpartial-inlining'
clang-14: error: unknown argument: '-ftrack-macro-expansion=0'
clang-14: error: unknown argument: '-fcompare-debug-second'
clang-14: error: unknown argument: '-fpartial-inlining'
clang-14: error: unknown argument: '-ftrack-macro-expansion=0'
clang-14: error: unknown argument: '-fcompare-debug-second'
clang-14: error: unknown argument: '-fpartial-inlining'
clang-14: error: unknown argument: '-ftrack-macro-expansion=0'
clang-14: error: unknown argument: '-fcompare-debug-second'
Backend C: 70.0%|█████████████████▌       | 7/10scons: *** [__constants.o] Error 1
scons: *** [__constants_data.o] Error 1
scons: *** [__helpers.o] Error 1
scons: *** [__loader.o] Error 1
scons: *** [module.__main__.o] Error 1
scons: *** [static_src/MainProgram.o] Error 1
scons: *** [static_src/CompiledCellType.o] Error 1
clang-14: error: unknown argument: '-fpartial-inlining'
clang-14: error: unknown argument: '-ftrack-macro-expansion=0'
clang-14: error: unknown argument: '-fcompare-debug-second'
Backend C: 80.0%|████████████████████     | 8/10scons: *** [static_src/CompiledFunctionType.o] Error 1
```
Why this error and why can't compile on my Android termux. Please guide me.

**Comment by Maxwell175** [comment]
I've looked into this briefly in the past and you can get as far as a built binary by following these steps:

```
pkg install python patchelf binutils
pip install ordered-set Nuitka
python -m nuitka --clang --standalone hello.py
```

However, since android does not support RPATH, you get the following error when running the binary:

```
WARNING: linker: Warning: "/data/data/com.termux/files/home/hello.dist/hello" unused DT entry: DT_RPATH (type 0xf arg 0x13d7) (ignoring)
CANNOT LINK EXECUTABLE "./hello.dist/hello": library "libpython3.10.so.1.0" not found: needed by main executable
```

I've worked on similar fixes for another project in the past, which can be found here:
https://github.com/panda3d/panda3d/blob/16304388699f30cf97316997242e46e5ccfdbc8e/makepanda/makepackage.py#L843

Obviously that's a totally different project but the basic commands are going to be similar if someone wants to make it work in Nuitka. I'm not sure if supporting Termux is a priority for Nuitka (unless you're a commercial customer), but at the end of the day the better way to compile for android in general is using the NDK to cross compile, which is not supported by Nuitka currently.

**Comment by Linux-aarch** [comment]
I done install successfully **nuitka**. But after compile **nuitka** can't run **so** file.
I have this 👇
```
ls                                                   ─╯ _asyncio.so         _elementtree.so      _struct.so        _bisect.so          _hashlib.so          _uuid.so          _blake2.so          _heapq.so            _zoneinfo.so      _bz2.so             _json.so             array.so          _codecs_cn.so       _lzma.so             audioop.so        _codecs_hk.so       _multibytecodec.so   binascii.so       _codecs_iso2022.so  _multiprocessing.so  drop              _codecs_jp.so       _opcode.so           fcntl.so          _codecs_kr.so       _pickle.so           grp.so            _codecs_tw.so       _posixshmem.so       ha                _contextvars.so     _posixsubprocess.so  math.so           _crypt.so           _queue.so            mmap.so           _csv.so             _random.so           pyexpat.so        _ctypes.so          _sha512.so           select.so         _datetime.so        _socket.so           termios.so        _dbm.so             _ssl.so              unicodedata.so    _decimal.so         _statistics.so       zlib.so
```
I have this issues problem and **nuitka cython** can't run. 👇
```
./drop                                               ─╯ WARNING: linker: Warning: "/data/data/com.termux/files/home/test/drop.dist/drop" unused DT entry: DT_RPATH (type 0xf arg 0x13d7) (ignoring)                                      CANNOT LINK EXECUTABLE "./drop": library "libpython3.10.so.1.0" not found
```

**Comment by kayhayen** [comment]
Step one would be to make sure, the Android Linux is properly identified, such that it becomes possible to identify the platform. 

Step two, probably something general, a gcc that is really a clang, is something we could recognize, or tie a default to clang for this platform. I prefer the former of course, since it will be universal.

Step three is probably to adapt the way DLL dependencies are detected, that seems not to work.

I won't do these, but I welcome anybody taking a stab at it.

**Comment by Linux-aarch** [comment]
> I've looked into this briefly in the past and you can get as far as a built binary by following these steps:
> 
> ```
> pkg install python patchelf binutils
> pip install ordered-set Nuitka
> python -m nuitka --clang --standalone hello.py
> ```
> 
> However, since android does not support RPATH, you get the following error when running the binary:
> 
> ```
> WARNING: linker: Warning: "/data/data/com.termux/files/home/hello.dist/hello" unused DT entry: DT_RPATH (type 0xf arg 0x13d7) (ignoring)
> CANNOT LINK EXECUTABLE "./hello.dist/hello": library "libpython3.10.so.1.0" not found: needed by main executable
> ```
> 
> I've worked on similar fixes for another project in the past, which can be found here: https://github.com/panda3d/panda3d/blob/16304388699f30cf97316997242e46e5ccfdbc8e/makepanda/makepackage.py#L843
> 
> Obviously that's a totally different project but the basic commands are going to be similar if someone wants to make it work in Nuitka. I'm not sure if supporting Termux is a priority for Nuitka (unless you're a commercial customer), but at the end of the day the better way to compile for android in general is using the NDK to cross compile, which is not supported by Nuitka currently.
Step one would be to make sure, the Android Linux is properly identified, such that it becomes possible to identify the platform.

Step two, probably something general, a gcc that is really a clang, is something we could recognize, or tie a default to clang for this platform. I prefer the former of course, since it will be universal.

Step three is probably to adapt the way DLL dependencies are detected, that seems not to work.

I won't do these, but I welcome anybody taking a stab at it.


> I've looked into this briefly in the past and you can get as far as a built binary by following these steps:
> 
> ```
> pkg install python patchelf binutils
> pip install ordered-set Nuitka
> python -m nuitka --clang --standalone hello.py
> ```
> 
> However, since android does not support RPATH, you get the following error when running the binary:
> 
> ```
> WARNING: linker: Warning: "/data/data/com.termux/files/home/hello.dist/hello" unused DT entry: DT_RPATH (type 0xf arg 0x13d7) (ignoring)
> CANNOT LINK EXECUTABLE "./hello.dist/hello": library "libpython3.10.so.1.0" not found: needed by main executable
> ```
> 
> I've worked on similar fixes for another project in the past, which can be found here: https://github.com/panda3d/panda3d/blob/16304388699f30cf97316997242e46e5ccfdbc8e/makepanda/makepackage.py#L843
> 
> Obviously that's a totally different project but the basic commands are going to be similar if someone wants to make it work in Nuitka. I'm not sure if supporting Termux is a priority for Nuitka (unless you're a commercial customer), but at the end of the day the better way to compile for android in general is using the NDK to cross compile, which is not supported by Nuitka currently.


Step one would be to make sure, the Android Linux is properly identified, such that it becomes possible to identify the platform.

Step two, probably something general, a gcc that is really a clang, is something we could recognize, or tie a default to clang for this platform. I prefer the former of course, since it will be universal.

Step three is probably to adapt the way DLL dependencies are detected, that seems not to work.

I won't do these, but I welcome anybody taking a stab at it.

**Comment by Linux-aarch** [comment]
> Step one would be to make sure, the Android Linux is properly identified, such that it becomes possible to identify the platform.
> 
> Step two, probably something general, a gcc that is really a clang, is something we could recognize, or tie a default to clang for this platform. I prefer the former of course, since it will be universal.
> 
> Step three is probably to adapt the way DLL dependencies are detected, that seems not to work.
> 
> I won't do these, but I welcome anybody taking a stab at it.

Dear sir,
You mean that the **nuitka** can't support on Android termux. Right?

**Comment by Linux-aarch** [comment]
> I've looked into this briefly in the past and you can get as far as a built binary by following these steps:
> 
> ```
> pkg install python patchelf binutils
> pip install ordered-set Nuitka
> python -m nuitka --clang --standalone hello.py
> ```
> 
> However, since android does not support RPATH, you get the following error when running the binary:
> 
> ```
> WARNING: linker: Warning: "/data/data/com.termux/files/home/hello.dist/hello" unused DT entry: DT_RPATH (type 0xf arg 0x13d7) (ignoring)
> CANNOT LINK EXECUTABLE "./hello.dist/hello": library "libpython3.10.so.1.0" not found: needed by main executable
> ```
> 
> I've worked on similar fixes for another project in the past, which can be found here: https://github.com/panda3d/panda3d/blob/16304388699f30cf97316997242e46e5ccfdbc8e/makepanda/makepackage.py#L843
> 
> Obviously that's a totally different project but the basic commands are going to be similar if someone wants to make it work in Nuitka. I'm not sure if supporting Termux is a priority for Nuitka (unless you're a commercial customer), but at the end of the day the better way to compile for android in general is using the NDK to cross compile, which is not supported by Nuitka currently.

Dear sir,

When I run **py -m nuitka --clang --standalone test.py** on termux. Here is my problem that why **nuitka*" can't compile a python script. This is simple **Hello world" python file. Check error 👇

![Screenshot_20220717-134150.png](https://user-images.githubusercontent.com/47935105/179391028-efb88115-ffb1-4ce8-9226-c706f0caa93c.png)

After that the **test** file can't run after **nuitka compile** ```./test```

![Screenshot_20220717-134123.png](https://user-images.githubusercontent.com/47935105/179391064-434a305c-192a-4082-847b-3ae5f7492a93.png)

Why nuitka cython can't run after clang compile. Please solve me . **Thanks in advance**

**Comment by Maxwell175** [comment]
As KayHayen said, Nuitka does not support Android currently. Kay outlined the 3 general things that need to be done to add support if someone would like to put in the time to do it.

**Comment by kayhayen** [comment]
Please don't post screenshots or repeated information @Linux-aarch actually it seems you cannot contribute to the solution any further.

**Comment by kayhayen** [comment]
It seems Termux is working nowadays just fine.

**Comment by LinuxUserGD** [comment]
> However, since android does not support RPATH, you get the following error when running the binary:
> 
> ```
> WARNING: linker: Warning: "/data/data/com.termux/files/home/hello.dist/hello" unused DT entry: DT_RPATH (type 0xf arg 0x13d7) (ignoring)
> CANNOT LINK EXECUTABLE "./hello.dist/hello": library "libpython3.10.so.1.0" not found: needed by main executable
> ```
> 

I still get this error on Android (Bliss OS x86_64) when running any binary compiled with Nuitka (Python 3.10.8 / 2.7.18)

**Comment by kayhayen** [comment]
@LinuxUserGD can you make a new report with more details, right now I am not sure I have everything needed. I do not even know if this happens at compile time or run time.
