### ISSUE TITLE
dolphindb issue

### ISSUE THREAD

**Issue by ljzecg** [Nuitka/Nuitka#1676]
I'm having trouble with the package `dolphindb`, which depends on numpy, pandas, pytz etc..

```
import dolphindb as ddb

if __name__ == '__main__':
    s = ddb.session()
    print(s)
```

Using this script:
`python -m nuitka .\main.py --standalone --enable-plugin=numpy`

Executing the main.exe:
`ModuleNotFoundError: No module named 'dolphindbcpp'`

After coping the `dolphindbcpp.cp37-win_amd64.pyd` to the `main.dist` directory:
`ImportError: DLL load failed:`

However, when using this script:
`python -m nuitka .\main.py --standalone --enable-plugin=numpy --nofollow-import-to=dolphindb`

After coping all the dependency (numpy, pandas, dateutil, six.py ...)to the main.dist dir, it works.

I also tried the `--include-package-data`
What is the right scripts for some packages like it?

**Comment by kayhayen** [comment]
Copying manualy is unsupported. You failed fill out the issue template, which is very annoying as it means I have to guess stuff, and I don't like to.

**Comment by ljzecg** [comment]
> Copying manualy is unsupported. You failed fill out the issue template, which is very annoying as it means I have to guess stuff, and I don't like to.

I am sorry, this is my first time to try out the issue section in one project, but what do you mean by filling out the issue template?
I have posted the example code, which is quite simple. As well as the nuitka scripts.

I tried `--include-package-data=dolphindb` but it still does not work.

Is there any chance that DO NOT compile packages that dolphindb but use python.dll to directly execute them by copying the entire folder manually.

**Comment by kayhayen** [comment]
Create a new issue and read the issue template, then provide all information. Simple.
