### ISSUE TITLE
Suggestion import

### ISSUE THREAD

**Issue by arist0v** [Nuitka/Nuitka#1679]
I didn't find any easy way to import  nuitka into a python script, my use case is the following:

build.py script:

- pytest: if succes
- nuitka build
- etc.. 

i was hoping to find a way like:

`import nuitka

builder = nuitka
builder.standalone = True
builder.enable-plugin(['numpy],)
builder.build()
`

or anything else like that would be nice, so i could just import nuitka and setup a builder and call a build to be able to use it in a .py script use for ci/cd

**Comment by kayhayen** [comment]
Just call it with subprocess. Nuitka depends on fully controlling the environment it runs it, it will not work without restarting itself into a clean one.

**Comment by arist0v** [comment]
> Just call it with subprocess. Nuitka depends on fully controlling the environment it runs it, it will not work without restarting itself into a clean one.

This is what i ended up to do, but was still hoping a better way to do it but it's fine if it's not possible

**Comment by kayhayen** [comment]
Well, we could make a module to call the executable, but why? Take note that options to Nuitka are best passed as project options, this will allow you to put the options into the source code, refer to user manual for that. If you find you need code to build the Nuitka options, maybe there is something wrong with its options or your approach. :)

**Comment by arist0v** [comment]
@kayhayen thank you for your quick response, i can do it perfectly by calling a subprocess, the only point i have to do is to point the python executable to the executable in the .venv folder for my build process, so maybe a way to specify a build virtual env could be a nice addition then

**Comment by arist0v** [comment]
thank you i'll take a look at it!
