### ISSUE TITLE
No installation instructions for Linux Mint

### ISSUE THREAD

**Issue by ralienpp** [Nuitka/Nuitka#168]
Here are the steps I am following:

```
CODENAME=`lsb_release -c -s`
wget -O - http://nuitka.net/deb/archive.key.gpg | apt-key add -
echo >/etc/apt/sources.list.d/nuitka.list "deb http://nuitka.net/deb/stable/$CODENAME $CODENAME main"
apt-get update
apt-get install nuitka
```

The output of `lsb_release -c -s` is `tara`, so the contents of the apt source file looks like `deb http://nuitka.net/deb/stable/tara tara main`. This leads to `apt` being unable to update the repositories, yielding the following error: `E: The repository 'http://nuitka.net/deb/stable/tara tara Release' does not have a Release file.
`

Changing that line to `deb http://nuitka.net/deb/stable/xenial xenial main` resolves the problem.

**Comment by kayhayen** [comment]
Probably nipicking, but the instructions claim to work for Debian and Ubuntu only.

From what I know, every Mint version is secretly one of those really. Is there a command that can tell the code name mapping, then I would update the instructions to use it.

The way repos work a symlink on the server is not enough.

**Comment by ralienpp** [comment]
You're right. Perhaps, at a minimum, this could be a simple remark in the documentation, hinting the reader about the solution. This was a bit puzzling for me, and I spent quite some time exploring various false trails.

However, there is an easy way to get the matching Ubuntu name: `grep "UBUNTU_CODENAME" /etc/os-release`, this will output something like this: `UBUNTU_CODENAME=bionic`.

A command to get just the `bionic` part would be `grep "UBUNTU_CODENAME" /etc/os-release  | awk -F= '{ print $NF}'`

**Comment by kayhayen** [comment]
@ralienpp that's nice, although using `awk` feels too embarrassing, I think `cut -f2 -d=` should be preferred. I am going to update the website with instructions that I would ask you to test out, even if I am now closing this issue, just comment here anyway.

This should work to have joint instructions for all of Debian, Ubuntu and Mint.

**Comment by kayhayen** [comment]
Thanks, I pushed it, the next web site update will be fixed.
