### ISSUE TITLE
implicit-imports unnecessory package

### ISSUE THREAD

**Issue by xqdoo00o** [Nuitka/Nuitka#1686]
1.0rc8
Commercial: None
Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
Flavor: Debian Python
Executable: /root/a/bin/python
OS: Linux
Arch: x86_64
Distribution: Debian 11

I just tried helloworld.py
`print("Hello world")`
with command `python3 -m nuitka --onefile helloworld.py`

then the console outputs lots of implicit-imports
`Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'urllib.request' added 'http.client,http.cookiejar'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'shelve' added 'dbm.dumb'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pathlib' added 'ntpath,posixpath'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'importlib.metadata' added 'email'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'concurrent.futures.process' added 'multiprocessing,multiprocessing.connection'.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module '_asyncio' added 'asyncio'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'quopri' added 'py_compile'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'encodings' added 'encodings.idna,encodings.base64_codec,encodings.hex_codec,encodings.rot_13'.`

Is that necessory for just helloworld.py?
the imports causing a big binary size of 19MB for helloworld.

**Comment by kayhayen** [comment]
If you want you can help reducing it. But things are really very interdependent there, removing stuff, and a lot of big ones have, has caused breakage already.
