### ISSUE TITLE
Bug: Support of `match-case`

### ISSUE THREAD

**Issue by wszqkzqk** [Nuitka/Nuitka#1688]
`match-case` was added to python since python 3.10, but it seems that nuitka didn't recognize it.

When I use `match-case`, the compile process is blocked and there is no output even after an extremely long time, but when I replace the code with `if` implementation, the compile process succeed.

[One simple example](https://github.com/wszqkzqk/pypvz/commit/9fa2521396f1407f64483f46089cbcf80633d98a#diff-37b082726122e11da2f7ae49919a4f698c6b2294d77180fe55ba483f79a0a0af)

```pwsh
> nuitka --version
0.9.6
Commercial: None
Python: 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\17265\AppData\Local\Programs\Python\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

**Comment by kayhayen** [comment]
I will gladly fix it, given a minimal example, copying the simple example code just compiled fine, so I don't know what you are talking about. Maybe I failed to use GitHub, but I don't know that. Or maybe I forgot that there are improvements only on develop branch, and you didn't try that.

**Comment by wszqkzqk** [comment]
This is the log of compiling my little example and it was blocked.
[The simple example](https://github.com/wszqkzqk/pypvz/commit/9fa2521396f1407f64483f46089cbcf80633d98a#diff-37b082726122e11da2f7ae49919a4f698c6b2294d77180fe55ba483f79a0a0af)
```pwsh
Nuitka-Options:INFO: Used command line options: --mingw64 --standalone --onefile --show-progress --output-dir=D:\17265\Documents\GitHub\pypvz\release --windows-icon-from-ico=D:\17265\Documents\GitHub\pypvz\pypvz.ico --include-data-dir=D:\17265\Documents\GitHub\pypvz\resources=resources --include-data-file=C:\Users\17265\AppData\Local\Programs\Python\Python310\Lib\site-packages\pygame\libogg-0.dll=libogg-0.dll --include-data-file=C:\Users\17265\AppData\Local\Programs\Python\Python310\Lib\site-packages\pygame\libopus-0.dll=libopus-0.dll --include-data-file=C:\Users\17265\AppData\Local\Programs\Python\Python310\Lib\site-packages\pygame\libopusfile-0.dll=libopusfile-0.dll --include-data-file=C:\Users\17265\AppData\Local\Programs\Python\Python310\Lib\site-packages\pygame\libvorbisfile-3.dll=libvorbisfile-3.dll --include-data-file=C:\Users\17265\AppData\Local\Programs\Python\Python310\Lib\site-packages\pygame\libvorbis-0.dll=libvorbis-0.dll --lto=yes --windows-product-name=pypvz --windows-company-name=null --windows-file-description=pypvz --windows-disable-console --windows-product-version=0.7.34.0 D:\17265\Documents\GitHub\pypvz\main.py
Nuitka:INFO: Starting Python compilation with Nuitka '0.9.6' on Python '3.10' commercial grade 'not installed'.
Nuitka-Progress:INFO: PASS 1:
Nuitka-Progress:INFO: Optimizing module '__main__', 0 more modules to go after that.
Nuitka-Progress:INFO: Doing module local optimizations for '__main__'.
Nuitka-Progress:INFO: Not changed, but retrying one more time.
Nuitka-Progress:INFO: Not finished with the module due to following change kinds: new_expression
Nuitka-Progress:INFO: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements
Nuitka-Progress:INFO: Not changed, but retrying one more time.
Nuitka-Progress:INFO: Finished with the module.
Nuitka-Progress:INFO: Optimizing module 'source.state.level', 396 more modules to go after that.
Nuitka-Progress:INFO: Doing module local optimizations for 'source.state.level'.
PASS 1: 0.3%|                         | 1/398, source.state.level
```
I've cleaned the ccache but it doesn't help. And it works when I replaced `match-case` with `if` implementation.

But this minimal example can pass the compile process without replacement.
```python
match 1:
    case 1:
        print("Hello, world!")
```

I am not sure what caused this issue now...

**Comment by kayhayen** [comment]
So you don't have a reproducer, right? I think you may have jumped to conclusions. Revert your commit and see if it does not work then and I can have a look, but I doubt it has any substance right now. The code you linked worked no issue for me.

**Comment by wszqkzqk** [comment]
> So you don't have a reproducer, right? I think you may have jumped to conclusions. Revert your commit and see if it does not work then and I can have a look, but I doubt it has any substance right now. The code you linked worked no issue for me.

I've reverted but it still didn't work.

**Comment by wszqkzqk** [comment]
Let me test on other devices then...

**Comment by wszqkzqk** [comment]
> Let me test on other devices then...

It seems that [the github workflow](https://github.com/wszqkzqk/pypvz/runs/7431372083?check_suite_focus=true) is also blocked by the same step.

**Comment by kayhayen** [comment]
If you provide me with a link to a plain file that causes the symptom, that would be great.

**Comment by kayhayen** [comment]
Also please try develop, there was a severe scalability bug, maybe your code triggered it too

**Comment by wszqkzqk** [comment]
> If you provide me with a link to a plain file that causes the symptom, that would be great.

OK, [***this is the file***](https://github.com/wszqkzqk/pypvz/blob/master/source/state/level.py), but it's just a personal project for fun and the code may not be easy to understand with comment code in my mother languiage, I'll try to translate some of them if necessary...

**Comment by wszqkzqk** [comment]
> Also please try develop, there was a severe scalability bug, maybe your code triggered it too

OK, I'll test it on GitHub Workflow with a brand new environment
