### ISSUE TITLE
I have used the command "python -m nuitka --onefile --follow-imports TPP.py".  but i got error like this picture i have also used this command administrator cmd already

### ISSUE THREAD

**Issue by MRX0077** [Nuitka/Nuitka#1689]
![Screenshot 2022-07-20 195038](https://user-images.githubusercontent.com/101811344/179987383-ea7f8a79-f4ef-49e1-b83b-4d274cd6a5bd.png)

**Comment by kayhayen** [comment]
No issue template, no fun.
