### ISSUE TITLE
Unexpected behavior with --windows-disable-console.

### ISSUE THREAD

**Issue by Rajjco** [Nuitka/Nuitka#1692]
My code runs fine in Pycharm IDE but after Compiling it with Nuitka it behaves differently and doesn't work as intended.

If I enable the console window It runs properly but not with --windows-disable-console.

Here is the command:
`nuitka --standalone --follow-imports --enable-plugin=tk-inter  --windows-icon-from-ico=Resources\logo.png --windows-disable-console main.py`

Link to source code:
https://github.com/Rajjco/Simple-Youtube-Downloader-GUI/blob/main/main.py

**Comment by kayhayen** [comment]
You failed to provide the issue template information sadly.

**Comment by kayhayen** [comment]
Also not true
