### ISSUE TITLE
This is not a bug, but a question that puzzles me

### ISSUE THREAD

**Issue by CeivenLean** [Nuitka/Nuitka#1694]
I have used nuitka for two years. I have not encountered any packaging problems that I cannot solve. Thank you for your efforts. Today when I packed it on virtual machine win7, the output text on the terminal was completely scrambled (for example, "请输入文件" to be output, and after nuitka packed, the terminal displayed "杈撳叆鏂囦欢".
"), I tried every kind of encoding and couldn't solve it, but when I thought about pyinstaller and tried it, it turned out to be OK. So that's what I was confused about. The same program runs correctly with the python command before packaging, but there's a problem with nuitka and pyinstaller doesn't. But I used nuitka to package programs with Chinese before, but that's on a win10 notebook I ordered, and it's OK. I can't find the reason for this problem on my virtual machine win7

**Comment by kayhayen** [comment]
There is a workaround for a chicken and egg problem when initializing output on Python3 up to 3.7

```
// Workaround older Python not handling stream setup on redirected files properly.
#if PYTHON_VERSION >= 0x340 && PYTHON_VERSION < 0x380
    {
        char const *encoding = NULL;

        if (SYSFLAG_UTF8) {
            encoding = "utf-8";
        } else {
            encoding = getenv("PYTHONIOENCODING");
            if (encoding == NULL) {
                encoding = "utf-8";
            }
        }

        Py_SetStandardStreamEncoding(encoding, NULL);
    }
#endif
```

It will default to "UTF8" which is not going to work on Chinese systems. However, I think Python3.9 works on Windows 7 still, does it not, at least 3.8 will, and not have the issue. It would require bigger changes to Nuitka to make up for this.

**Comment by CeivenLean** [comment]
Thank you. I know this is a problem with the old os and the old python. utf8 had not been defaulted at that time,
