### ISSUE TITLE
Enhancement: Make Windows SDK not installed for a MSVC fallback to MinGW64 if allowed

### ISSUE THREAD

**Issue by kayhayen** [Nuitka/Nuitka#1698]
Right now, when on Windows, the MSVC found doesn't have a Windows SDK installed as well, an error `FATAL: Error, the Windows SDK must be installed in visual studio` is given. This should rather be a reason to fallback to MinGW64 though, as some users have these installed, without even knowing that. Only when a user insist with `--msvc=latest`  a fallback shall not be done, but this error.

This requires moving `_detectWindowsSDK` into ``checkWindowsCompilerFound`.

**Comment by kayhayen** [comment]
This is an enhancement that may end up being too risky for 1.0 and be pushed to 1.1

**Comment by fleimgruber** [comment]
I was seeing this today when coming back to Nuitka after a break to see whether old issues still reproduce.

IIRC, the last time I used Nuitka in 2021, it actually installed the MinGW64 toolchain by itself as is mentioned in the docs under https://github.com/Nuitka/Nuitka#requirements. Was it because back then I did not have the Visual Studio compiler (cl) installed and it falled back to MinGW64 because of that? And now as it finds the VS compiler, it tries to use it but then finds Windows SDK uninstalled?

**Comment by fleimgruber** [comment]
If so, is there a way to tell Nuitka to not use the Windows C compiler but automatically download and use the MinGW64 compiler regardless?

**Comment by fleimgruber** [comment]
Also, did you consider to have a "look-ahead" to compile phase where the error "FATAL: Error, the Windows SDK must be installed in Visual Studio." would be given to the user prior to analyzing the Python code and generating the C sources? What happens now is that code analysis and code generation takes a few minutes in some cases and the time is wasted when later the compiler toolchain is found lacking some components / has some other issues.

**Comment by kayhayen** [comment]
Yes, that option already exists. I do not consider look aheead though, as it increases the complexity for little gain. The fallback will just make it work, and insisting on MSVC, while not having the supported one installed, is nothing I am concerned with how much time they waste.

**Comment by fleimgruber** [comment]
I see, thanks for your thoughts on this.

> Yes, that option already exists.

Would you mind giving me a shove, I was not able to find it in the user manual.

**Comment by fleimgruber** [comment]
And sorry for hijacking the issue.

**Comment by fleimgruber** [comment]
> Would you mind giving me a shove, I was not able to find it in the user manual.

Sorry for the noise, found it in the `nuitka --help` as `--mingw64`.

**Comment by kayhayen** [comment]
If somebody encounters this and wants to help thst would be great. For now I lack the time to do it myself.

**Comment by kayhayen** [comment]
I have implemented this, and it will soon hit factory branch, going to be part of 1.6. After changes, it turns out, this should actually be really simply. It's just like arch mismatch for MSVC now. I am closing it early due to lack of general relevance.
