### ISSUE TITLE
No support for PySide2 in standalone mode

### ISSUE THREAD

**Issue by aoloe** [Nuitka/Nuitka#170]
Before submitting an Issue, please review the [Issue Guidelines](https://github.com/kayhayen/Nuitka/blob/master/CONTRIBUTING.md#submitting-an-issue).

* could not find a match in this tracker for "QtGui"
* Successfully installed Nuitka-0.6.1rc5 through pip in a venv
 
```
nuitka3 --version
0.6.1rc5
Python: 3.6.6 (default, Jun 27 2018, 14:44:17)
Executable: /home/ale/src-tmp/python-tutorial-qt/venv/bin/python3
OS: Linux
Arch: x86_64
```

the python code

```py
from PySide2.QtWidgets import QApplication, QLabel

app = QApplication([])
label = QLabel('Hello World')
label.show()
app.exec_()
```

compiled with

```sh
python -m nuitka --recurse-all --standalone hello-world.py
```

zipped the resulting `hello-world.dist` and copied it on a different computer.

unzipped and:

```sh
$ ./hello-world
Traceback (most recent call last):
  File "/home/ale/t/hello-world.dist/hello-world.py", line 1 <module>
ImportError: could not import module 'PySide2.QtGui'
```

if i run

```sh
$ python -m nuitka --recurse-all hello-world.py
```
i can correctly run the resulting `hello-world.bin` on the same machine, even if i'm not in the virtual environment.

i can provide the zip file, if it is useful for you...

**Comment by kayhayen** [comment]
There is a plugin in Nuitka that deals with implicit imports and handles these for PyQt5 and PySide already.

Recently I noticed that PyQt5 provides so called ".pyi "files, which (with upcoming fixes that I have yet to push to factory and pre-release this weekend) which seem to provide all the hidden dependencies.

Can we try and convince PySide2 makers, which is apparently the Qt project now to provide these, so we don't have to hard code them in Nuitka (and in everything else on the planet that attempts to package it)?

Otherwise, feel free to search "PySide" in Nuitka and extend it for PySide2 too as well, and very likely things will work. The "plugins" code will need to be adapted to recognize it either way.

**Comment by kayhayen** [comment]
If you are willing to make a PR for Nuitka, I can help you get this done, it's not rocket science, but for the implicit imports, I would very much prefer to talk to PySide2 makers for them to provide files with these hidden imports in them.

As PySide2 seems unfinished, I am not going to care all that much about it, esp. as I had bad experience with getting PySide patches merged in the past. Could well be that PySide2 still hard codes uncompiled function type checks like PySide did.

**Comment by ManPython** [comment]
I made simple example on win7 x64 with --standalone with Pyside2 
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] 

python -m nuitka --recurse-all --standalone main.py
scons: *** [main.build\module.__main__.o] AttributeError : 'EnvironmentError' object has no attribute 'strerror'

In case that without --standalone main.exe is prepared with success pn p36
python -m nuitka --recurse-all  main.py

I little confused coz in p36 my .exe need python36.dll next to .exe and not including this.

**Comment by kayhayen** [comment]
When scons aborts with an error, things are incomplete and will not work therefore. Actually there should be no exe in the dist folder if I am not mistaken, @ManPython.

The error looks familiar, and in fact Nuitka inline copy of scons has a fix for it:
https://github.com/SCons/scons/issues/3094

Not sure if I applied it to the newer one for 3.0.1 as well.

Yours,
Kay

**Comment by girstenbrei** [comment]
Hi there!
I have the same problem as @aoloe (I think). I can reproduce the failure (Windows 10, Nuitka 0.6.0.6 via pip, PySide2 5.11.2, Python 3.7.1). But I explicitely use something from the QtGui module (QPixmap) and that seems to solve the import issue. This leaves me with the following error: 
```
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```
Thought maybe I get lucky, copying the qt-plugins folder (containing a platforms-folder) into the PySide2 folder (giving me `.\xyz.dist\PySide2\qt-plugins\platforms`, but thats not enough apparently.

I may be able to provide you with a PR, don't know much about Nuitka unfortunately, neither about PySide2, but adapting nuitka/plugins/standard/PySidePyQtPlugin.py, I may be able to do that. Just wanted to ask if someone knew the error from above, what it means and if there are any gotyas for adapting the plugin?

PS: @kayhayen (and all other contributors) really really really awesome work! Appart from other advantages I think Nuitka completes the python eco system: why would I use pyinstaller/cx_freeze/aso. when I can get all the advantages of a compiled piece of software? I think it's great!

**Comment by taimurrabuske** [comment]
Hello. I submitted a pull request.
https://github.com/Nuitka/Nuitka/pull/205
https://github.com/taimurrabuske/Nuitka/commit/34fd2262edbc56b0698333320a35e5ea2ed93e73

I managed to make it work with a simple hello-world PySide2 example.

import sys
from PySide2.QtWidgets import QApplication, QLabel

app = QApplication(sys.argv)
#label = QLabel("Hello World!")
label = QLabel("<font color=red size=40>Hello World!</font>")
label.show()
app.exec_()

**Comment by kayhayen** [comment]
When https://bugreports.qt.io/browse/PYSIDE-1523 is included PySide will be good with Nuitka. There is experimental support for PySide2 right now, but it has a few bugs. Closing this as a duplicate.
