### ISSUE TITLE
No module named 'dateutil.easter' not built

### ISSUE THREAD

**Issue by oondrash** [Nuitka/Nuitka#1700]
### python3 -m nuitka --version
Python: 3.6.8 (default, May  8 2021, 09:11:34)
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64

Nuitka was installed with pip on my machine.

### python3 -m pip freeze
amqp==5.1.1
attrs==21.4.0
backports.zoneinfo==0.2.1
cached-property==1.5.2
configobj==5.0.6
dbus-python==1.2.4
decorator==4.2.1
Deprecated==1.2.13
gpg==1.13.1
html5lib==0.999999999
importlib-metadata==4.8.3
importlib-resources==5.4.0
iniconfig==1.1.1
isc==2.0
kombu==5.1.0
libcomps==0.1.16
librabbitmq==2.0.0
lxml==4.2.3
MarkupSafe==0.23
nftables==0.1
Nuitka==0.6.12.2
numpy==1.19.1
ordered-set==4.0.2
packaging==21.3
pandas==1.1.0
patsy==0.5.2
perf==0.1
pexpect==4.3.1
pluggy==1.0.0
ply==3.9
psutil==5.4.3
ptyprocess==0.5.2
py==1.11.0
pyasn1==0.3.7
pycairo==1.16.3
pydbus==0.6.0
pygobject==3.28.3
pyparsing==3.0.9
pytest==7.0.1
python-dateutil==2.8.2
python-linux-procfs==0.6.3
pytz==2022.1
pytz-deprecation-shim==0.1.0.post0
pyudev==0.21.0
PyYAML==3.12
rpm==4.14.3
schedutils==0.6
scipy==1.5.4
selinux==2.9
sepolicy==1.1
setools==4.3.0
setroubleshoot==1.1
six==1.11.0
slip==0.6.4
slip.dbus==0.6.4
sos==4.1
SSSDConfig==2.5.1
statsmodels==0.12.2
syspurpose==1.28.17
systemd-python==234
tomli==1.2.3
typing-extensions==4.1.1
tzdata==2022.1
tzlocal==4.2
urllib3==1.26.10
vine==5.0.0
WALinuxAgent==2.2.49.2
webencodings==0.5.1
wincertstore==0.2
wrapt==1.14.1
zipp==3.6.0
 
### main.py
import pandas
print('Hello world')

### python3 get-hints.py main.py
Process run will timeout in 5 minutes
Hello world
Call cleaning has removed 528 items.

### python3 nuitka-hints.py main.py
NUITKA v(0, 6, 12, 2) on Python 3.6.8 (linux) is compiling 'main.py' with these options:
 --standalone
 --nofollow-imports
 --hinted-json-file=main-36-linux-64.json

Nuitka-Options:WARNING: Recursing none is unlikely to work for standalone mode and should not be specified.
Nuitka-Plugins:INFO: hinted-mods: 'hinted-mods' is adding the following options:
Nuitka-Plugins:INFO: hinted-mods: Enabling Nuitka plugin 'numpy' as needed.
Nuitka-Plugins:INFO: hinted-mods: --recurse-to=zlib and 416 more modules
Nuitka:INFO: Starting Python compilation.
Nuitka-Plugins:INFO: hinted-mods: drop site
Nuitka-Plugins:INFO: hinted-mods: drop pytest
Nuitka-Plugins:INFO: hinted-mods: drop numpy.distutils (in numpy)
Nuitka-Plugins:INFO: hinted-mods: drop unittest
Nuitka-Plugins:INFO: hinted-mods: drop numpy.testing._private.noseclasses (in numpy.testing._private)
Nuitka-Plugins:INFO: hinted-mods: drop scipy (plugin 'numpy')
Nuitka-Plugins:INFO: hinted-mods: drop doctest
Nuitka-Plugins:INFO: hinted-mods: drop numpy.testing._private.parameterized (in numpy.testing._private)
Nuitka-Plugins:INFO: hinted-mods: drop _collections_abc
Nuitka-Plugins:INFO: hinted-mods: drop array
Nuitka-Plugins:INFO: hinted-mods: drop psutil
Nuitka-Plugins:INFO: hinted-mods: drop numpy.dual (in numpy)
Nuitka-Plugins:INFO: hinted-mods: drop numpy.distutils.misc_util (in numpy.distutils)
Nuitka-Plugins:INFO: hinted-mods: drop _decimal
Nuitka-Plugins:INFO: hinted-mods: drop _pydecimal
Nuitka-Plugins:INFO: hinted-mods: drop numpy.ma.mrecords (in numpy.ma)
Nuitka-Plugins:INFO: hinted-mods: drop urllib.request (in urllib)
Nuitka-Plugins:INFO: hinted-mods: drop urllib.error (in urllib)
Nuitka-Plugins:INFO: hinted-mods: drop pydoc
Nuitka-Plugins:INFO: hinted-mods: drop pandas.io.formats.latex (in pandas.io.formats)
Nuitka-Plugins:INFO: hinted-mods: drop pandas.io.formats.html (in pandas.io.formats)
Nuitka-Plugins:INFO: hinted-mods: drop pandas.core.computation.expressions (in pandas.core.computation)
Nuitka-Plugins:INFO: hinted-mods: drop pandas.util.testing (in pandas.util)
Nuitka-Plugins:INFO: hinted-mods: drop pandas.io.formats.style (in pandas.io.formats)
Nuitka-Plugins:INFO: hinted-mods: drop pandas.core.apply (in pandas.core)
Nuitka-Plugins:INFO: hinted-mods: drop pandas.core.computation.check (in pandas.core.computation)
Nuitka-Plugins:INFO: hinted-mods: drop pandas.core.arrays._arrow_utils (in pandas.core.arrays)
Nuitka-Plugins:INFO: hinted-mods: drop pandas.core.resample (in pandas.core)
Nuitka-Plugins:INFO: hinted-mods: drop pandas.plotting._matplotlib (in pandas.plotting)
Nuitka-Plugins:INFO: hinted-mods: drop pandas.io.formats.csvs (in pandas.io.formats)
Nuitka-Plugins:INFO: hinted-mods: drop pandas.io.clipboard (in pandas.io)
Nuitka-Plugins:INFO: hinted-mods: drop sqlite3
Nuitka-Plugins:INFO: hinted-mods: drop dateutil.tz.win (in dateutil.tz)
Nuitka-Plugins:INFO: hinted-mods: drop dateutil.rrule (in dateutil)
Nuitka-Plugins:INFO: hinted-mods: drop dateutil.zoneinfo (in dateutil)
Nuitka-Plugins:INFO: hinted-mods: drop http.client (in http)
Nuitka-Plugins:INFO: hinted-mods: drop pandas.io.sas.sas_xport (in pandas.io.sas)
Nuitka-Plugins:INFO: hinted-mods: drop pandas.io.sas.sas7bdat (in pandas.io.sas)
Nuitka-Plugins:INFO: hinted-mods: drop lxml.html (in lxml)
Nuitka-Plugins:INFO: hinted-mods: drop lxml.etree (in lxml)
Nuitka-Plugins:INFO: hinted-mods: drop optparse
Nuitka-Plugins:INFO: hinted-mods: drop pandas.core.arrays.sparse.scipy_sparse (in pandas.core.arrays.sparse)
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:WARNING: Not recursing to unused '__future__'.
Nuitka:WARNING: Not recursing to unused '_compat_pickle'.
Nuitka:WARNING: Not recursing to unused '_compression'.
Nuitka:WARNING: Not recursing to unused '_weakrefset'.
Nuitka:WARNING: Not recursing to unused 'argparse'.
Nuitka:WARNING: Not recursing to unused 'base64'.
Nuitka:WARNING: Not recursing to unused 'ctypes._endian'.
Nuitka:WARNING: Not recursing to unused 'dis'.
Nuitka:WARNING: Not recursing to unused 'encodings'.
Nuitka:WARNING: Not recursing to unused 'enum'.
Nuitka:WARNING: Not recursing to unused 'fnmatch'.
Nuitka:WARNING: Not recursing to unused 'genericpath'.
Nuitka:WARNING: Not recursing to unused 'gettext'.
Nuitka:WARNING: Not recursing to unused 'hashlib'.
Nuitka:WARNING: Not recursing to unused 'heapq'.
Nuitka:WARNING: Not recursing to unused 'hmac'.
Nuitka:WARNING: Not recursing to unused 'importlib._bootstrap'.
Nuitka:WARNING: Not recursing to unused 'importlib._bootstrap_external'.
Nuitka:WARNING: Not recursing to unused 'json.decoder'.
Nuitka:WARNING: Not recursing to unused 'json.encoder'.
Nuitka:WARNING: Not recursing to unused 'linecache'.
Nuitka:WARNING: Not recursing to unused 'logging'.
Nuitka:WARNING: Not recursing to unused 'ntpath'.
Nuitka:WARNING: Not recursing to unused 'opcode'.
Nuitka:WARNING: Not recursing to unused 'os'.
Nuitka:WARNING: Not recursing to unused 'random'.
Nuitka:WARNING: Not recursing to unused 'selectors'.
Nuitka:WARNING: Not recursing to unused 'signal'.
Nuitka:WARNING: Not recursing to unused 'stat'.
Nuitka:WARNING: Not recursing to unused 'types'.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Compiled 312 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'disabled': 1
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 311
Nuitka-Plugins:INFO: hinted-mods: Compiled 'main.py' in 8.3 minutes.
Nuitka:INFO: Keeping build directory 'main.build'.
Nuitka:INFO: Successfully created 'main.dist/main'.

### 
./main.dist/main
Traceback (most recent call last):
  File "/tmp/services/microservice-skp/main.dist/pandas/__init__.py", line 30, in <module pandas>
  File "/tmp/services/microservice-skp/main.dist/pandas/_libs/__init__.py", line 13, in <module pandas._libs>
  File "pandas/_libs/hashtable.pxd", line 8, in init pandas._libs.interval
  File "pandas/_libs/missing.pxd", line 11, in init pandas._libs.hashtable
  File "pandas/_libs/tslibs/nattype.pxd", line 9, in init pandas._libs.missing
  File "/tmp/services/microservice-skp/main.dist/pandas/_libs/tslibs/__init__.py", line 30, in <module pandas._libs.tslibs>
  File "pandas/_libs/tslibs/conversion.pyx", line 33, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/offsets.pxd", line 7, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 17, in init pandas._libs.tslibs.offsets
ModuleNotFoundError: No module named 'dateutil.easter'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/services/microservice-skp/main.dist/main.py", line 1, in <module>
  File "/tmp/services/microservice-skp/main.dist/pandas/__init__.py", line 38, in <module pandas>
ImportError: C extension: No module named 'dateutil.easter' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.

**Comment by kayhayen** [comment]
This version of Nuitka is not supported, and hinted compilation also no more. Just use modern Nuitka, which thanks to anti-bloat produces acceptable results for pandas.
