### ISSUE TITLE
Poetry compat: HelloWorld does not print on stdout

### ISSUE THREAD

**Issue by fleimgruber** [Nuitka/Nuitka#1701]
```
> poetry run python -m nuitka --version

0.9.6
Commercial: None
Python: 3.9.12 (tags/v3.9.12:b28265d, Mar 23 2022, 23:52:46) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\LeimgruberF\dev\nuitka-poetry\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

Installed Python via pyenv-win and Nuitka via Poetry (`poetry add --dev nuitka`). Poetry manages a virtual environment and runs all `poetry run ...` commands in that environment.

Ran Nuitka on the HelloWorld example from the user manual:

```
> poetry run python -m nuitka .\hello.py --mingw64

Nuitka-Options:INFO: Used command line options: .\hello.py --mingw64
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure that is intended.
Nuitka:INFO: Starting Python compilation with Nuitka '0.9.6' on Python '3.9' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 9 files (no progress information available).
Nuitka-Scons:INFO: Compiled 36 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 9
Nuitka:INFO: Keeping build directory 'hello.build'.
Nuitka:INFO: Successfully created 'hello.exe'.
```

But then a `.\hello.exe` returns with an exit code -10737415150 and without printing anything on STDOUT. Any ideas on how to debug this further? I am at a loss.

**Comment by kayhayen** [comment]
If you want to transfer to another machine, you need to use standalone mode, otherwise it's expected to not work. If you create it accelerated inside a virtualenv, you need to run it in there too. For some Python installations, where the DLL is not accessible, a CMD file is created that provides the environment. Potentially it needs to for virtualenv persistence of `PYTHONPATH` etc. but for you there, `poetry run hello.exe` would be needed.

**Comment by kayhayen** [comment]
Ah, the `.cmd` file if it is already created, should always be the one to use, but in that case, it would have appeared in the log file you gave, but I didn't see it there. Did you yourself create one?

**Comment by fleimgruber** [comment]
> Did you yourself create one?

No, not by hand nor explicitly.

> it would have appeared in the log file you gave, but I didn't see it there

Maybe I copied an outdated / wrong log section, my bad in that case. But I just tested again and with

```
> poetry run python -m nuitka .\hello.py --mingw64
```

the `hello.cmd` is created, but not mentioned in the log.

**Comment by kayhayen** [comment]
So, I added the trace to the output on factory branch. It's an important enhancement, but largely unrelated to anything in the issue specifics, therefore I am closing it. I do believe on Linux, the virtualenv environment still needs preservation, but this is about Windows, where it's expected to be worked around already be the "uninstalled" Python mechanism.
