### ISSUE TITLE
Question: Regarding VTK compilation behaviour

### ISSUE THREAD

**Issue by jkissi** [Nuitka/Nuitka#1703]
Hello!
I am compiling a program in standalone mode. when running the program after compilation, I get an error regarding vtk:

`ModuleNotFoundError: No module named 'vtk.util'`

It's odd, because I have tried specifically to get nuitka to add those directories with the import flags:
`--include-package=vtkmodules.util` or 
`--include-module=vtkmodules.util`

and the console output indicates that it can find these directories but the final .dist/ folder never contains vtk files from this directory. It contains files in the main folder but not from the subfolders. 
Before I submit a full report, I just wanted to make sure that vtk is supported, or rather, that there isn't some specific reason
why vtk itself doesn't work regarding nuitka compilation..? Or am I missing something obvious? 

Thanks
j

**Comment by kayhayen** [comment]
No issue template no fun.

**Comment by jkissi** [comment]
haha, thats fair. I will formulate things in a better way and come back. 
Thanks.
