### ISSUE TITLE
ptyhon39.dll was not found on path

### ISSUE THREAD

**Issue by godclowntools** [Nuitka/Nuitka#1707]
Hi.
I obfuscate and compiled the python script with **Nuitka**. And is running good in my machine but when I test it in my virtual box with windows a pop up show python39.dll was not found.

So basically my problem is.
1.) First as Nuitka creates project.build folder and I don't want to share with someone . I just want to share the exe file with someone. Is there any way to do it.
2) Second as the error shows python is not found and Is it necessary to install python on running machine. If not then how ?

Thank you

**Comment by Maxwell175** [comment]
You should check out the user manual on information on how to properly use Nuitka for working between different computers: https://nuitka.net/doc/user-manual.html#use-case-4-program-distribution

**Comment by kayhayen** [comment]
No issue template no fun, probably didn't even use proper mode.
