### ISSUE TITLE
Syntax command_options setuptools for nuitka

### ISSUE THREAD

**Issue by Hraesvelg** [Nuitka/Nuitka#1708]
Hi,

Sorry for the issue if she is not justify but i didn't see documentation or sample for this case...
my problem is related to [#1304](https://github.com/Nuitka/Nuitka/issues/1304 )

below my code to use nuitka

`
setup(
....
command_options={
        'nuitka': {
            "standalone": True,
            "onefile": True,
            "disable-console": True,
            "windows-icon-from-ico": "favicon.png",
            "enable-plugin": "pyside6",
        }
    },
...
`

ok so now if i try to launch the build, for last argument nuitka take the first package in my project ...
but i would like to precise the argument : the name of application (app.py)

Nuitka-Options:INFO: Used command line options: --module --enable-plugin=pylint-warnings --output-dir=C:\Users\Hraesvelg\Projects\test_project\build\lib --nofollow-import-to=*.tests --remove-output --include-package=controllers --standalone --onefile --disable-console --windows-icon-from-ico=favicon.png --enable-plugin=pyside6 **C:\Users\Hraesvelg\Projects\test_project\build\lib\controllers**

->

Nuitka-Options:INFO: Used command line options: --module --enable-plugin=pylint-warnings --output-dir=C:\Users\Hraesvelg\Projects\test_project\build\lib --nofollow-import-to=*.tests --remove-output --include-package=controllers --standalone --onefile --disable-console --windows-icon-from-ico=favicon.png --enable-plugin=pyside6 **C:\Users\Hraesvelg\Projects\test_project\build\lib\app.py**

Thanks !

**Comment by kayhayen** [comment]
That is not supported at this time. Nuitka lets the wheel intallation creates runners that import the package. It will be coming once multidist is implemented, which it is not, checkout roadmap.
