### ISSUE TITLE
M1 Mac| Nuitka 1.0 : FATAL: Error, problem with dependency scan

### ISSUE THREAD

**Issue by Josh596** [Nuitka/Nuitka#1709]
* Full Error
```
Nuitka-Plugins:INFO: numpy: Found 3 files DLLs from numpy installation.
FATAL: Error, problem with dependency scan of '/Users/luki/miniforge3/envs/main39/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so' with '@loader_path/../.dylibs/libopenblas64_.0.dylib' please report the bug.
```

  > python -m nuitka --version
```
1.0
Commercial: None
Python: 3.9.1 | packaged by conda-forge | (default, Jan 26 2021, 01:30:54) 
Flavor: Anaconda Python
Executable: /Users/luki/miniforge3/envs/main39/bin/python
OS: Darwin
Arch: arm64
```

* How did you install Nuitka and Python

I installed nuitka using `pip install Nuitka`.
Python from Anaconda

  > python -m pip freeze
```
Nuitka==1.0
numpy==1.21.6
opencv-python==4.5.3.56
Pillow==9.1.1
PySide6==6.3.0
```

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

> test.py
```

import sys
import numpy as np
import cv2
from PIL import Image
from PySide6.QtCore import Qt
from PySide6.QtWidgets import QApplication, QLabel, QWidget

def main():
    app = QApplication(sys.argv)
    window = QWidget()
    window.setWindowTitle("Simple")
    window.setGeometry(300, 300, 300, 300)
    label = QLabel(window)
    label.setText("Hello World!")
    label.setGeometry(0, 0, 300, 300)
    label.setAlignment(Qt.AlignCenter)
    window.show()

    im = Image.new(mode="RGB", size=(200, 200))
    im_array = np.array(im)
    return app.exec()




if __name__ == "__main__":
    sys.exit(main())

```

* Provide in your issue the Nuitka options used
```
python3 -m nuitka --standalone --macos-app-icon=icons/icon.icns --macos-create-app-bundle --disable-ccache --include-package=objc --follow-imports  --enable-plugin=pyside6 --enable-plugin=numpy --assume-yes-for-download --run test.py
```

  

I get the error, even if I use python without conda

**Comment by kayhayen** [comment]
When you say `use python`, do you mean CPython download or uncompiled?!

**Comment by Josh596** [comment]
> When you say `use python`, do you mean CPython download or uncompiled?!

Sorry. I mean Cpython download

**Comment by kayhayen** [comment]
Ok, I will look into it. I am pretty sure I did numpy with Anacoda before, but the error basically means that some DLL directory is missing still there. I think that `numpy` plugin would copy these DLLs, but they are not found during the scan, although I believe, that `.dylibs` ought to be discovered when searching for DLL directories, or that `loader_path` is applied to narrowly.

**Comment by kayhayen** [comment]
Can you provide the output of https://nuitka.net/doc/factory.html with your Anaconda setup.

**Comment by kayhayen** [comment]
I added the resolved path as a trace, and I normalized paths produced there, which however ought to not affect `os.path.exists` but who knows for sure. This should allow us to tell. For bonus points, can you figure out, where the mistake is. From the looks of it, that is where the file ought to live, although of course I can imagine that Anaconda deviates there, and puts these libs in another place.

**Comment by Josh596** [comment]
Using the factory branch and installing as specified in https://nuitka.net/doc/factory.html. 

I tested with:

> > test.py
> 
> ```
> 
> import sys
> import numpy as np
> import cv2
> from PIL import Image
> from PySide6.QtCore import Qt
> from PySide6.QtWidgets import QApplication, QLabel, QWidget
> 
> def main():
>     app = QApplication(sys.argv)
>     window = QWidget()
>     window.setWindowTitle("Simple")
>     window.setGeometry(300, 300, 300, 300)
>     label = QLabel(window)
>     label.setText("Hello World!")
>     label.setGeometry(0, 0, 300, 300)
>     label.setAlignment(Qt.AlignCenter)
>     window.show()
> 
>     im = Image.new(mode="RGB", size=(200, 200))
>     im_array = np.array(im)
>     return app.exec()
> 
> 
> 
> 
> if __name__ == "__main__":
>     sys.exit(main())
> ```
> 
> * Provide in your issue the Nuitka options used
> 
> ```
> python3 -m nuitka --standalone --macos-app-icon=icons/icon.icns --macos-create-app-bundle --disable-ccache --include-package=objc --follow-imports  --enable-plugin=pyside6 --enable-plugin=numpy --assume-yes-for-download --run test.py
> ```

and I get another error, it seems to have moved past numpy, and now affects PySide6.

Here is the error:
```
Nuitka-Plugins:INFO: numpy: Found 3 files DLLs from numpy installation.
FATAL: Error, failed to find path @rpath/libshiboken6.abi3.6.2.dylib (resolved DLL to /Users/luki/miniforge3/envs/main39/lib/python3.9/site-packages/PySide6/libshiboken6.abi3.6.2.dylib) for /Users/luki/miniforge3/envs/main39/lib/python3.9/site-packages/PySide6/libpyside6.abi3.6.2.dylib, please report the bug.
```

**Comment by Josh596** [comment]
> I added the resolved path as a trace, and I normalized paths produced there, which however ought to not affect `os.path.exists` but who knows for sure. This should allow us to tell. For bonus points, can you figure out, where the mistake is. From the looks of it, that is where the file ought to live, although of course I can imagine that Anaconda deviates there, and puts these libs in another place.

How do I figure out where the mistake is ?

**Comment by Josh596** [comment]
I did some digging. I believe the `libshiboken6.abi3.6.2.dylib` should be resolved to `/Users/luki/miniforge3/envs/main39/lib/python3.9/site-packages/shiboken/libshiboken6.abi3.6.2.dylib`.

It should be resolved to the shiboken package.

**Comment by kayhayen** [comment]
That makes more sense, there is code like this here:

```
    def getModuleSpecificDllPaths(self, module_name):
        if module_name.hasNamespace("PySide6"):
            yield self.locateModule("shiboken6")
```

These are used for `@rpath` I think, but somehow they are not active, although you have the plugin active.  It might not get forwarded. I will be able to look at it tomorrow, but I strongly suspect, that the `package_name` of a using DLL is not attributed to a used DLL, but should be. Based on that, I might have a fix for it already.

I did a bit of `normpath` changes that ought to not make the numpy issue go away, but then again it looked like it never ought to have existed in the first place, since the paths looked good. But I am taking it. I believe some places compare paths to be identical maybe. Need to check too if that is happening.

**Comment by kayhayen** [comment]
The current factory branch state ought to be working for this better now. Used DLLs by an extension module, didn't get the package name passed on (anymore), and as such in this unusual situation, didn't benefit from the code. The only reason it exists PySide, which does strange things with libshiboken there, and maybe only on macOS.

**Comment by kayhayen** [comment]
This works fine on factory now and is going to be part of 1.0.1, closing now with release being immanent anyway.
