### ISSUE TITLE
Code compiled in one computer doesn't work in a similar computer (with same OS and architecture).

### ISSUE THREAD

**Issue by joaopfg** [Nuitka/Nuitka#1712]
When trying to use code compiled in one computer in another computer, I am having the error: 

`ImportError: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found `

The two computers give the same output to `uname -a` command and to `dpkg-architecture -q DEB_BUILD_ARCH` but the hardware is not the same.

Am I missing something ? Is the compiled code also dependent on deeper details about hardware ?

I can give some additional detail about the hardware of both computers if needed.

**Comment by kayhayen** [comment]
No issue template no fun

**Comment by joaopfg** [comment]
@kayhayen It was more like a general question. 

Is the code produced by Nuitka totally determined by the OS and architecture or is it dependent on deeper hardware details ? Seems to be the later in my tests. I just wanted a confirmation from your side to be sure I'm not doing something wrong and that I'm not spending resources on a non-existent problem.

**Comment by kayhayen** [comment]
Read manuals to be sure.
