### ISSUE TITLE
Python3.10: Pattern matching does not work correctly with conditions on matched sequence elements

### ISSUE THREAD

**Issue by DemonicSavage** [Nuitka/Nuitka#1713]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

```
1.0
Commercial: None
Python: 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0]
Flavor: Unknown
Executable: /home/twilight/.cache/pypoetry/virtualenvs/tagger-fLqvqAez-py3.10/bin/python
OS: Linux
Arch: x86_64
Distribution: Arch None
```

* How did you install Nuitka and Python

`poetry add nuitka`

* The specific PyPI names and versions

No external dependencies

* Many times when you get an error from Nuitka, your setup may be special

Everything else seems fine?

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

```python
def repl(command):

    match command.split():
        case [("add" | "rm") as action, *person]:
            print("add")

        case ["print"]:
            print("print")

repl("print")
```
This prints "add" instead of "print".

* Provide in your issue the Nuitka options used

Defaults.

* Note if this is a regression

Not that I know of.

* Consider getting commercial support

Not right now

**Comment by kayhayen** [comment]
That's a pretty nasty one, wrong execution is always the worst.

**Comment by kayhayen** [comment]
The fix for this is on the factory branch and will be in 1.0.2 likely https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
I reduced the case further and found a missing thing, I am currently looking at executing the `test_patma` from the suite, so there might be more fixes coming.

**Comment by kayhayen** [comment]
A few more enhancements are on develop, one key thing is missing, namely mixing positional and keyword arguments in matching, and one wrong execution is still being done, that I am still looking into.

**Comment by kayhayen** [comment]
This is part of the stable release 1.1 that I just made.
