### ISSUE TITLE
Questions about tensorrt packaging

### ISSUE THREAD

**Issue by Trytoz** [Nuitka/Nuitka#1714]
My English is not very good, so this article comes from translation software.
I am using python 3.8
Nuitka Version: 0.9.6
I found part of the problem in packaging a project about onnx to tensorrt conversion in yolov5.
The packager has correctly identified tensorrt and the related code, and has copied the dll files related to cuda as well as cudnn and trt, but I noticed some exceptions, it seems to not detect or determine that the nvinfer_builder_resource.dll (supported by tensorrt) is not needed, I'm not sure about the file is required for tensorrt or not. I'm also not sure if it's a vulnerability. So here's the feedback.

**Comment by kayhayen** [comment]
I will need a minimal reproducer. You are not supposed to have to copy any DLLs by yourself, make sure to use Nuitka 1.0 or higher, which has gotten more compatible. Also make sure to provide `python -m nuitka --version` output, so I can know the environment, and `python -m pip freeze` output for the relevant package versions used in the reproducer. Ideally start with a single issue. Once I have a reproducer, I can normally fix it easily, but I cannot work of abstract information like the one you provided.

**Comment by Trytoz** [comment]
这是来自QQ邮箱的自动回复邮件。邮件我已收到。

**Comment by Trytoz** [comment]
我使用的是cuda 11.3，
cudnn-windows-x86_64-8.4.1.50_cuda11.6-archive
As you say, I also think I don't need to make additional copies of the dll, but in practice it's really missing。

I'm still using version 0.96, I'll update to version 1.0 later and try again。



# ----------
Here are my python packages
> (cuda11) C:\Users\root>python -m pip freeze
> arc4==0.2.0
> certifi @ file:///C:/Windows/TEMP/abs_e9b7158a-aa56-4a5b-87b6-c00d295b01fanefpc8_o/croots/recipe/certifi_1655968940823/work/certifi
> cffi==1.15.1
> charset-normalizer==2.1.0
> colorama==0.4.5
> coloredlogs==15.0.1
> comtypes==1.1.11
> cryptography==37.0.4
> cycler==0.11.0
> d3dshot==0.1.5
> flatbuffers==2.0
> fonttools==4.34.4
> humanfriendly==10.0
> idna==3.3
> kiwisolver==1.4.4
> matplotlib==3.5.2
> mpmath==1.2.1
> mss==6.1.0
> Nuitka==0.9.6
> numpy==1.20.0
> onnx==1.12.0
> onnxruntime==1.12.0
> onnxruntime-gpu==1.12.0
> opencv-contrib-python==4.6.0.66
> opencv-python==4.1.2.30
> packaging==21.3
> pandas==1.4.3
> Pillow==7.1.2
> pipdeptree==2.2.1
> piptree==0.1.4
> protobuf==3.20.1
> pycparser==2.21
> pynput==1.7.6
> pyparsing==3.0.9
> pyreadline3==3.4.1
> python-dateutil==2.8.2
> pytz==2022.1
> pywin32==304
> PyYAML==6.0
> requests==2.28.1
> scipy==1.8.1
> seaborn==0.11.2
> six==1.16.0
> sympy==1.10.1
> tensorrt @ file:///K:/NNNNNNNNNN/pytrtwhl/tensorrt-8.4.1.5-cp38-none-win_amd64.whl
> torch==1.12.0+cu113
> torchaudio==0.12.0+cu113
> torchvision==0.13.0+cu113
> tqdm==4.64.0
> typing_extensions==4.3.0
> urllib3==1.26.11
> wincertstore==0.2
> 

This is part of my sample code, my code is more complex, I am not sure if the location needs the dll。
# ----
```
import tensorrt as trt
import os

EXPLICIT_BATCH = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
TRT_LOGGER = trt.Logger()


def get_engine(onnx_file_path, engine_file_path=""):
    """Attempts to load a serialized engine if available, otherwise builds a new TensorRT engine and saves it."""

    def build_engine():
        """Takes an ONNX file and creates a TensorRT engine to run inference with"""
        with trt.Builder(TRT_LOGGER) as builder, builder.create_network(
            EXPLICIT_BATCH
        ) as network, builder.create_builder_config() as config, trt.OnnxParser(
            network, TRT_LOGGER
        ) as parser, trt.Runtime(
            TRT_LOGGER
        ) as runtime:
            config.max_workspace_size = 1 << 32  # 4GB
            builder.max_batch_size = 1
            # Parse model file
            if not os.path.exists(onnx_file_path):
                print(
                    "ONNX file {} not found, please run yolov3_to_onnx.py first to generate it.".format(onnx_file_path)
                )
                exit(0)
            print("Loading ONNX file from path {}...".format(onnx_file_path))
            with open(onnx_file_path, "rb") as model:
                print("Beginning ONNX file parsing")
                if not parser.parse(model.read()):
                    print("ERROR: Failed to parse the ONNX file.")
                    for error in range(parser.num_errors):
                        print(parser.get_error(error))
                    return None

            # # The actual yolov3.onnx is generated with batch size 64. Reshape input to batch size 1
            # network.get_input(0).shape = [1, 3, 608, 608]

            print("Completed parsing of ONNX file")
            print("Building an engine from file {}; this may take a while...".format(onnx_file_path))
            plan = builder.build_serialized_network(network, config)
            engine = runtime.deserialize_cuda_engine(plan)
            print("Completed creating Engine")
            with open(engine_file_path, "wb") as f:
                f.write(plan)
            return engine

    if os.path.exists(engine_file_path):
        # If a serialized engine exists, use it instead of building an engine.
        print("Reading engine from file {}".format(engine_file_path))
        with open(engine_file_path, "rb") as f, trt.Runtime(TRT_LOGGER) as runtime:
            return runtime.deserialize_cuda_engine(f.read())
    else:
        return build_engine()


def main():
    """Create a TensorRT engine for ONNX-based YOLOv3-608 and run inference."""

    # Try to load a previously generated YOLOv3-608 network graph in ONNX format:
    onnx_file_path = "apex_288_epo600.onnx"
    engine_file_path = "model.engine"

    get_engine(onnx_file_path, engine_file_path)


if __name__ == "__main__":
    main()
```

**Comment by kayhayen** [comment]
I like to first fix the first issue, trying to avoid it may or may not work correctly, and actually is not supported, because often DLLs need special treatment to be able to run elsewhere. I will check it out, once I find the time. If you want to have this fast, consider becoming a Nuitka commercial subscriber or having the priority package: https://nuitka.net/doc/commercial.html#pricing

But I think I should get to this given some time anyway.

**Comment by kayhayen** [comment]
Well, no, this is from a special PyPI index, I think I might not want to go there unless this is funded.

**Comment by Trytoz** [comment]
> 嗯，不，这是来自一个特殊的 PyPI 索引，我想我可能不想去那里，除非有资金支持。

I may have a problem with the translation of this English paragraph on my side, I don't understand this paragraph very well, do I need to do anything about this?

**Comment by Trytoz** [comment]
According to my side, after executing the package and running it on other systems that lack environment, it prompts that nvinfer_builder_resource.dll is missing, but it only needs to be copied from the compiled system, which is not a serious bug as of now, after all, it only needs to be copied manually.

**Comment by kayhayen** [comment]
Well, to be clear, I was considering to do this as part of my unpaid work on Nuitka, but now I will only do it if you become a commercial subscriber before. I will have to spend time and/or money to get that package installed it seems, so I think it will be something a commercial user wants and will pay me to do it by being a subscriber. if not, no problem, there is plenty other things to do.

**Comment by Trytoz** [comment]
okey

**Comment by KRRT7** [comment]
fixed and merged previously.
