### ISSUE TITLE
--standalone --plugin-enable=qt-plugins not working with python34

### ISSUE THREAD

**Issue by ManPython** [Nuitka/Nuitka#172]
After comand
python -m nuitka --recurse-all --standalone --plugin-enable=qt-plugins main.py
the main.exe want platforms\
..in case that in main.dist\PyQt5\qt-plugins\  exist this
If I copy the platforms\ next to main.exe then working ok

*  Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

0.6.0.3
Python: 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 bit (AMD64)]
Executable: E:\Python34\python.exe
OS: Windows w7sp1 x64 
Arch: x86_64

*  How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
   what is a virtualenv ...), this is very important usually.
PIP

In relation with experiments on https://github.com/Nuitka/Nuitka/issues/170#issuecomment-429647120
..not need any python34.dll

**Comment by kayhayen** [comment]
The platform plugins are included by default on Windows or so I am thinking: 

https://github.com/Nuitka/Nuitka/blob/e649cef06adda4a9b2470349100ac9f73de0ffd0/nuitka/plugins/standard/PySidePyQtPlugin.py#L145

Can you check what's going on there for you, and maybe it just lives in another spot than what the code is thinking. This should be easy to debug for you.

**Comment by kayhayen** [comment]
Closed for lack of feedback.

**Comment by develooper1994** [comment]
I know it has closed but I am still facing with same problem. Whenever I use standalone, qt-plugin and pyqt5 nuitka throws me asserterror

**Comment by kayhayen** [comment]
@develooper1994 being closed is for lack of feedback when I requested input. I invite you to fill out the issue template here or in another new issue. I just tend to not keep around issues that leave me guessing.
