### ISSUE TITLE
LTO error when compiling source due to version mismatch 

### ISSUE THREAD

**Issue by wxguy** [Nuitka/Nuitka#1727]
Trying to build my Python application which uses [wrf-python](https://wrf-python.readthedocs.io/en/latest/installation.html) which inturn relies on numpy, xarray, netcdf and cartopy modules extensively. 

Installed all libraries using Miniconda. Here is the version of nuitka version I am using:

```
$ python -m nuitka --version                                                         
1.0.1
Commercial: None
Python: 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0]
Flavor: Anaconda Python
Executable: /home/sundar/miniconda3/envs/wrfplot/bin/python
OS: Linux
Arch: x86_64
Distribution: Arch (based on arch) None
```

My issue here is that the compilation of modules by GCC is successful but `lto` optimization fails each time with the following error (only last few lines are printed):

```
Nuitka-Scons:INFO: Backend linking program with 1212 files (no progress information available).
/home/sundar/miniconda3/envs/wrfplot/bin/x86_64-conda-linux-gnu-cc -o /media/sundar/Datas/myprojects/wrf_plot/dist_lin/wrfplot.dist/wrfplot -fuse-linker-plugin -flto=8 -fpartial-inlining -freorder-functions -O2 -s -z noexecstack -export-dynamic -Wl,-R,'$ORIGIN' -Wl,--disable-new-dtags -Wl,-b -Wl,binary -Wl,./__constants.bin -Wl,-b -Wl,elf64-x86-64 -Wl,-defsym -Wl,constant_bin_data=_binary_____constants_bin_start -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/sundar/miniconda3/envs/wrfplot/lib -Wl,-rpath-link,/home/sundar/miniconda3/envs/wrfplot/lib -L/home/sundar/miniconda3/envs/wrfplot/lib @"./@link_input.txt" -L/home/sundar/miniconda3/envs/wrfplot/lib -ldl -lm /home/sundar/miniconda3/envs/wrfplot/lib/libpython3.10.a -ldl -lpthread -lutil -lrt -lm
lto1: fatal error: bytecode stream in file '/home/sundar/miniconda3/envs/wrfplot/lib/libpython3.10.a' generated with LTO version 6.2 instead of the expected 8.1
compilation terminated.
lto-wrapper: fatal error: /home/sundar/miniconda3/envs/wrfplot/bin/x86_64-conda-linux-gnu-cc returned 1 exit status
compilation terminated.
/home/sundar/miniconda3/envs/wrfplot/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
scons: *** [/media/sundar/Datas/myprojects/wrf_plot/dist_lin/wrfplot.dist/wrfplot] Error 1
scons: internal stack trace:
  File "/home/sundar/miniconda3/envs/wrfplot/lib/python3.10/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Job.py", line 258, in run
    task.execute()
  File "/home/sundar/miniconda3/envs/wrfplot/lib/python3.10/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Script/Main.py", line 206, in execute
    SCons.Taskmaster.OutOfDateTask.execute(self)
  File "/home/sundar/miniconda3/envs/wrfplot/lib/python3.10/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Taskmaster.py", line 255, in execute
    self.targets[0].build()
  File "/home/sundar/miniconda3/envs/wrfplot/lib/python3.10/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Node/__init__.py", line 766, in build
    self.get_executor()(self, **kw)
  File "/home/sundar/miniconda3/envs/wrfplot/lib/python3.10/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Executor.py", line 397, in __call__
    return _do_execute_map[self._do_execute](self, target, kw)
  File "/home/sundar/miniconda3/envs/wrfplot/lib/python3.10/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Executor.py", line 131, in execute_action_list
    raise status    # TODO pylint E0702: raising int not allowed
scons: building terminated because of errors.
```

I initially thought that it is related to GCC version used for compilation. However, the issue persist even when I downgrade the GCC version using conda. I have also tried on Ubuntu 18.04 in a virtual machine and the resultant issue was same.

The nuitks command I used for compiling the code was:

```
$ python -m nuitka --assume-yes-for-downloads --follow-imports --standalone --python-flag=-OO --output-dir=dist_win --plugin-enable=numpy --show-scons --show-modules --include-module=netCDF4.utils --include-package-data=pyproj --follow-import-to=pyproj --follow-import-to=shapely --include-package=shapely --include-package-data=shapely --include-data-dir=wrfplot/data=data /media/Data/myprojects/wrf_plot/wrfplot/wrfplot.py
```

After disabling `lto` option with`--lto=no`, I am getting the following AssertionError error:

```
Traceback (most recent call last):
  File "/home/sundar/miniconda3/envs/wrfplot/lib/python3.10/site-packages/nuitka/__main__.py", line 138, in <module>
    main()
  File "/home/sundar/miniconda3/envs/wrfplot/lib/python3.10/site-packages/nuitka/__main__.py", line 124, in main
    MainControl.main()
  File "/home/sundar/miniconda3/envs/wrfplot/lib/python3.10/site-packages/nuitka/MainControl.py", line 962, in main
    addIncludedEntryPoints(Plugins.considerExtraDlls(module))
  File "/home/sundar/miniconda3/envs/wrfplot/lib/python3.10/site-packages/nuitka/plugins/Plugins.py", line 475, in considerExtraDlls
    for extra_dll in plugin.getExtraDlls(module):
  File "/home/sundar/miniconda3/envs/wrfplot/lib/python3.10/site-packages/nuitka/plugins/standard/DllFilesPlugin.py", line 159, in getExtraDlls
    for dll_entry_point in self._handleDllConfig(
  File "/home/sundar/miniconda3/envs/wrfplot/lib/python3.10/site-packages/nuitka/plugins/standard/DllFilesPlugin.py", line 120, in _handleDllConfig
    for result in self._handleDllConfigByCode(
  File "/home/sundar/miniconda3/envs/wrfplot/lib/python3.10/site-packages/nuitka/plugins/standard/DllFilesPlugin.py", line 103, in _handleDllConfigByCode
    yield self.makeDllEntryPoint(
  File "/home/sundar/miniconda3/envs/wrfplot/lib/python3.10/site-packages/nuitka/plugins/PluginBase.py", line 434, in makeDllEntryPoint
    return makeDllEntryPoint(
  File "/home/sundar/miniconda3/envs/wrfplot/lib/python3.10/site-packages/nuitka/freezer/IncludedEntryPoints.py", line 98, in makeDllEntryPoint
    return _makeDllOrExeEntryPoint(
  File "/home/sundar/miniconda3/envs/wrfplot/lib/python3.10/site-packages/nuitka/freezer/IncludedEntryPoints.py", line 66, in _makeDllOrExeEntryPoint
    assert isRelativePath(dest_path), dest_path
AssertionError: ../../libgeos_c.so
```

**Comment by kayhayen** [comment]
Hm, it is using the Conda C compiler, precisely to avoid mismatches between libpython and gcc. In your case, it is using the Conda C from outside the env, for an env, that has a newer Python than baseline Anaconda, and probably was compiled using a newer package.

This should help, from the changelog:

```
-  Anaconda: Use ``CondaCC`` from environment variables for Linux and
   macOS, in case it is installed. This can be done with e.g. ``conda
   install gcc-linux-64`` on Linux or ``conda install clang_osx-64`` on
   macOS.
```

Installing inside the Conda environment the matching gcc is supposed to help. Also it seems you encounter an issue with DLLs by code from out Yaml configuration, that is indeed a bug, that will be there irregardless of LTO or not.

**Comment by kayhayen** [comment]
The `shapely.geos` (please provide minimal reproducers, esp. in case of crashes, here I could guess it, but I shouldn't have to) seems to detect an Anaconda environment, and then use a different path, and also is being very platform specific about target paths. It may only work well with PyPI right now, but I can add configuration for anaconda I guess. Anaconda is unusual there, because it makes a DLL reference to the outside world.

**Comment by wxguy** [comment]
> 

Both the errors I have received with and without `--lto` option are after installing `gcc-linux-64` using conda. I also used your recommendation to use `CondaCC` from an environment variable. However, the same issus persist.

The minimum reproducable code is taken from official [wrf-python](https://wrf-python.readthedocs.io/en/latest/plot.html) website:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from netCDF4 import Dataset
import matplotlib.pyplot as plt
from matplotlib.cm import get_cmap
import cartopy.crs as crs
from cartopy.feature import NaturalEarthFeature
from wrf import (to_np, getvar, smooth2d, get_cartopy, cartopy_xlim, cartopy_ylim, latlon_coords)

ncfile = Dataset("../../../wrfout_d01_2016-03-30_00_00_00")
slp = getvar(ncfile, "slp")
smooth_slp = smooth2d(slp, 3, cenweight=4)
lats, lons = latlon_coords(slp)
cart_proj = get_cartopy(slp)
fig = plt.figure(figsize=(12,6))
ax = plt.axes(projection=cart_proj)
states = NaturalEarthFeature(category="cultural", scale="50m", facecolor="none", name="admin_1_states_provinces_shp")
ax.add_feature(states, linewidth=.5, edgecolor="black")
ax.coastlines('50m', linewidth=0.8)
plt.contour(to_np(lons), to_np(lats), to_np(smooth_slp), 10, colors="black", transform=crs.PlateCarree())
plt.contourf(to_np(lons), to_np(lats), to_np(smooth_slp), 10, transform=crs.PlateCarree(), cmap=get_cmap("jet"))
plt.colorbar(ax=ax, shrink=.98)
ax.set_xlim(cartopy_xlim(smooth_slp))
ax.set_ylim(cartopy_ylim(smooth_slp))
ax.gridlines(color="black", linestyle="dotted")
plt.title("Sea Level Pressure (hPa)")
plt.show()
```

With the above minimal code also, I get the same error.

**Comment by kayhayen** [comment]
I see, must be using shapely. I did some work on making Shapely work with Anaconda, on Windows there an issue with it not finding the DLL afterwards, due to some Anaconda specifics, for Linux I will have a look later too.

**Comment by wxguy** [comment]
> I see, must be using shapely. I did some work on making Shapely work with Anaconda, on Windows there an issue with it not finding the DLL afterwards, due to some Anaconda specifics, for Linux I will have a look later too.

Just a head up that nuitka was unable to copy required libgeos dll files to proper location. However, it never crashed at that point of time (nuitka 0.8.x) series. After copying dll files manually to shapely directory worked.

**Comment by kayhayen** [comment]
Well yes, Anaconda is made to be portable, but also attempts to do de-duplication, and some software even checks for Anaconda environment variables, so e.g. shapely will not run even if compiled without Anaconda, if these variables are set, very ugly, but fixable.

That means, for DLLs it likely needs extra love for some packages that will otherwise already work, after we supported PyPI versions, shapely works for a long time with standard Python.

**Comment by wxguy** [comment]
In my opinion, if copying ***.so** or ***.dll** files manually to a standalone directory solves the problem, then nuitka should not crash. This copy-pasting stuff can be done after the compilation process is completed. I may be technically wrong but thought that it would be a good idea.

**Comment by kayhayen** [comment]
I appreciate your input, but I don't share the idea that I get to support why some manual copying does not work. For Anaconda specifically it seems shapely code will not allow it.

Anyway, for Windows and Linux this works for CPython and Anaconda now, with some source codes to shapely. I didn't have the time to check macOS yet, due to other issues.

The LTO bug reported, I didn't have the time yet, but I want to get to it for  the next hotfix.

**Comment by wxguy** [comment]
I was closely monitoring the development code base for these `LTO` and `shapely` bugs. Gone through the code base here `https://github.com/Nuitka/Nuitka/commit/9aeefcafe7201478ba698e3dcc8a1f40334fbf1a` and here `https://github.com/Nuitka/Nuitka/blob/develop/nuitka/plugins/standard/DllFilesPlugin.py` which indicates the shapely bug is fixed.

Therefore, installed the development version of nuitka with the following command:

```
pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"
```

Here are the details of the installed version:
```
 python -m nuitka --version                                                                      
1.1rc5
Commercial: None
Python: 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:04:59) [GCC 10.3.0]
Flavor: Anaconda Python
Executable: /home/sundar/miniconda3/envs/wrfplot/bin/python
OS: Linux
Arch: x86_64
Distribution: Arch (based on arch) None
```
Command used again for trying to get executable is:

```
$ python -m nuitka --assume-yes-for-downloads --follow-imports --standalone --python-flag=-OO --output-dir=./build/linux --plugin-enable=numpy --show-scons --show-modules --include-module=netCDF4.utils --include-package-data=pyproj --follow-import-to=pyproj --follow-import-to=shapely --include-package=shapely --include-package-data=shapely --include-data-dir=wrfplot/data=data ./wrfplot/wrfplot.py
```

This time I received a different error as indicated below:

```
Nuitka-Plugins:INFO: data-files: Included data file 'xarray/static/html/icons-svg-inline.html' due to package data directory 'static' for 'xarray'.
Nuitka-Plugins:INFO: dll-files: Found 1 file DLLs from shapely.geos installation.
FATAL: Error: Found a dependency with a relative path. Was a dependency copied to dist early? linux-vdso.so.1
```

This is just an update regarding ongoing development work on fixing these bugs. I hope it helps in identifying the issues at your end.

**Comment by kayhayen** [comment]
That is indeed another kind of bug, that is supposed to be fixed. It is because of a change in glibc that is only a couple of days old.

**Comment by kayhayen** [comment]
The shapely parts are indeed on develop now, however, I didn't get to the version mismatch part of Anaconda, that I regard critical for new user experience. Also for shapely, I will need to test with macOS before I am happy with this one.

**Comment by wxguy** [comment]
I returned to report that I made it work by downgrading the nuitka version to `0.8.4`. Here are some other details which may be of help to you:-

```
$ python -m nuitka --version
0.8.4
Commercial: None
Python: 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:04:59) [GCC 10.3.0]
Flavor: Anaconda Python
Executable: /home/sundar/miniconda3/envs/wrfplot/bin/python
OS: Linux
Arch: x86_64
Distribution: Arch (based on arch) None
```

The version info is the same for the Windows version of nuitka as well.

Options used to build the application are:

```
--assume-yes-for-downloads
--follow-imports
--standalone
--python-flag=-OO
--output-dir=build/linux
--plugin-enable=numpy
--show-scons
--show-modules
--include-module=netCDF4.utils
--include-package-data=pyproj
--follow-import-to=pyproj
--follow-import-to=shapely
--include-package=shapely
--include-package-data=shapely
--include-data-dir=wrfplot/data=data
--include-data-dir=$CONDA_PREFIX/share/proj=pyproj/proj 
--include-data-file=$CONDA_PREFIX/lib/libgeos*so.*=shapely/.libs/
--noinclude-default-mode=nofollow
wrfplot/wrfplot.py
```

When I used the above options, it did not complain about `AssertionError`. Neither complained about a version mismatch regarding `LTO`. It is also important to note that I have not installed `gcc` from conda.

The program has successfully compiled both on `Linux` and `Windows`.

I have noticed that after compilation is completed, the `libgeos*` libraries are copied to the root of the standalone directory. I have to overcome this issue by including `--include-data-file=$CONDA_PREFIX/lib/libgeos*so.*=shapely/.libs/` on Linux and `--include-data-file=$CONDA_PREFIX\Library\bin\geos*.dll=shapely\DLLs\` under Windows. Otherwise, the program will complain about missing library. I don't think this is an issue of nuitka. Maybe shapely is searching for these libraries somewhere else.

I hope it helps you further narrow down the issue for fixing the bug.

**Comment by kayhayen** [comment]
I just reproduced the Anaconda issue, in my root environment after installing `gcc_linux-64` it gives this:

```
lto1: fatal error: bytecode stream in file '/home/hayen/anaconda3/lib/libpython3.9.a' generated with LTO version 6.2 instead of the expected 8.1
```

It seems that is not the correct gcc package to use then. For me it was with Python3.9 which I think is default in that Anaconda that I have there. The 6.2 is pointing to a much older gcc than the 9.3 there, not sure if that is good to go old. Maybe it's a sign of this being something that ought to be unused.

**Comment by kayhayen** [comment]
I am not sure why, but Anaconda chooses to compile the static Python with an anienct gcc, so we will have to disable the LTO rather than to enable. Now I am very confused, because I was thinking I got it to work in that way before.

**Comment by kayhayen** [comment]
Maybe this is somehow conda-forge vs. non conda-forge stuff? I am trying to add dependencies to the Anaconda package, maybe i will help.

**Comment by kayhayen** [comment]
This is part of the stable release 1.1 that I just made, the Anaconda package does not yet depend on things there, but LTO got disabled.
