### ISSUE TITLE
Tix doesn't get added to the dist folder when using --enable-plugin=tk-inter

### ISSUE THREAD

**Issue by DimoDimchev** [Nuitka/Nuitka#1728]
Version info:
```
1.1rc2
Commercial: None
Python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Program Files\Python37\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

Tix is an extension to tkinter which needs no additional installation(it ships with tkinter as part of the standard Python library). There are many widgets used in tkinter applications that rely on tix.

Currently if you use the `--enable-plugin=tk-inter` argument tix doesn't get added to the dist folder and therefore applications that rely on it won't work.

The current workaround I've found is to copy and paste the directory from your local Python installation over to the dist folder IF you're using `--standalone`. I've also tried using `--include-data-dir=<tix location>=tix<version>` but for some reason that spits out this error when trying to run the executable: `_tkinter.tclError: value for -data missing`

**Comment by kayhayen** [comment]
Thanks for the report, this folder also contains a DLL, which Nuitka will not want to copy as a data file anyway, where data file options copy DLLs, I consider that to be a bug, and on develop at least, I recently fixed it for some cases. I wonder if importing `tix` is enough, you didn't provide an example.

**Comment by kayhayen** [comment]
I really need an example, the mere import doesn't trigger any visible issue and just works.

**Comment by kayhayen** [comment]
Closing for lack of feedback.
