### ISSUE TITLE
'blis' module not found when using spaCy

### ISSUE THREAD

**Issue by kjrussell** [Nuitka/Nuitka#1732]
I'm attempting to use the spacy library, however upon import in a standalone build I receive the following error:

```
D:\Projects\Example\Build\main.dist> ./main.exe
Traceback (most recent call last):
  File "D:\Projects\Example\Build\main.dist\main.py", line 1, in <module>
  File "D:\Projects\Example\Build\main.dist\spacy\__init__.py", line 6, in <module spacy>
  File "D:\Projects\Example\Build\main.dist\spacy\errors.py", line 2, in <module spacy.errors>
  File "D:\Projects\Example\Build\main.dist\spacy\compat.py", line 38, in <module spacy.compat>
  File "D:\Projects\Example\Build\main.dist\thinc\api.py", line 2, in <module thinc.api>
  File "D:\Projects\Example\Build\main.dist\thinc\initializers.py", line 4, in <module thinc.initializers>
  File "D:\Projects\Example\Build\main.dist\thinc\backends\__init__.py", line 7, in <module thinc.backends>
  File "D:\Projects\Example\Build\main.dist\thinc\backends\ops.py", line 15, in <module thinc.backends.ops>
  File "thinc\backends\cblas.pyx", line 1, in init thinc.backends.cblas
ModuleNotFoundError: No module named 'blis'
```

looking around in the issues for the problematic packages, the closest I could find is #994, I don't believe these are even remotely the same problem, however the packages were present in some of their output. I don't know if that means that this should work and I'm using the packaging options incorrectly or if these libraries are just unsupported at the moment.

Either way I appreciate your time in advance, and thank you for maintaining Nuitka it's a wonderful project. Template info is included below.

#####################################Begin Template##############################################

* `python -m nuitka --version` output:
1.0.3
Commercial: None
Python: 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: D:\Projects\Example\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

* How did you install Nuitka and Python:
Nuitka was installed via Pip
Python was installed via the recommended windows installer from the python website

* The specific PyPI names and versions:
blis==0.7.8
catalogue==2.0.8
certifi==2022.6.15       
charset-normalizer==2.1.0
click==8.1.3
colorama==0.4.5
cymem==2.0.6
idna==3.3
Jinja2==3.1.2
langcodes==3.3.0
MarkupSafe==2.1.1        
murmurhash==1.0.7        
Nuitka==1.0.3
numpy==1.23.1
orderedset==2.0.3        
packaging==21.3
pathy==0.6.2
preshed==3.0.6
pydantic==1.9.2
pyparsing==3.0.9
requests==2.28.1
smart-open==5.2.1        
spacy==3.4.1
spacy-legacy==3.0.9
spacy-loggers==1.0.3
srsly==2.4.4
thinc==8.1.0
tqdm==4.64.0
typer==0.4.2
typing_extensions==4.3.0
urllib3==1.26.11
wasabi==0.10.1

* Many times when you get an error from Nuitka, your setup may be special:
the example below compiles and runs without the spacy import

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)
```
import spacy

def main():

    print("hello world")

    return

if __name__ == '__main__':
    main()
```

* Provide in your issue the Nuitka options used:
```
python -m nuitka --standalone --enable-plugin=numpy --output-dir=./Build main.py
```

**Comment by arcontechnologies** [comment]
I'm facing the same issue and I managed to include 'blis' in` --include-package=win32com,spacy,fr_core_news_sm,thinc,blis`, I'm now ending with another module not found "thinc.backends.linalg". this is non ending story. Nuitka is suitable for simple projects but when it comes to real world projects it turns to a complete mess.

**Comment by kayhayen** [comment]
@arcontechnologies thanks for the generalization, always helpful thing to do

**Comment by arthurchen1906** [comment]
the same error occurred with module 'blis'

**Comment by kayhayen** [comment]
The dependency for thinc was added as part of the 1.1.1 hotfix release I just made. Not sure if this fixes spacy already, please open new issues if not.

**Comment by arthurchen1906** [comment]
来信已收到！我会及时处理。
