### ISSUE TITLE
pyzbar app throws FileNotFoundError after compilation

### ISSUE THREAD

**Issue by DolarJoe** [Nuitka/Nuitka#1736]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.
```
1.0.3
Commercial: None
Python: 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```
* How did you install Nuitka and Python
```
pip install Nuitka
```

* The specific PyPI names and versions
```
pyzbar==0.1.9
```
* Many times when you get an error from Nuitka, your setup may be special

Nuitka compiled files will run fine if they don't include `pyzbar`

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

```
from pyzbar import pyzbar
from PIL import Image

for i in pyzbar.decode(Image.open("qr_result_text.png")):
    print(i.data.decode('utf-8'))

```
PIL is not the problem here, same issue happens when `Image.open()` is replaced by OpenCV `cv2.imread()`
 
qr_result_text.png is attached, contains string "qr result text"

* Provide in your issue the Nuitka options used

```
python.exe -m nuitka --standalone test.py
```
* Note if this is a regression

Don't know

* Expected behaviour

Compiled .exe works the same as when running the script through python

* Current behaviour

Throws this error when i try to run the compiled .exe
```
FileNotFoundError: Could not find module 'libiconv.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

Source code and example qr image
---
[pyzbar.zip](https://github.com/Nuitka/Nuitka/files/9363024/pyzbar.zip)

**Comment by kayhayen** [comment]
Thanks for the excellent report, I can work of that.

My initial suspect, is that this might work as user yaml (check help output):

```
- module-name: "pyzbar"
  dlls:
    - from_filenames:
        prefixes:
          - "libiconv"
          - "libzbar"
```

Right now I am preparing a travel, so I don't have the time, but if you confirm, I can make it part of 1.0.5 (1.0.4 had an important fix btw) hotfix.

**Comment by DolarJoe** [comment]
The recommended yaml indeed fixed the issue, thank you.

**Comment by kayhayen** [comment]
This should be part of the current hotfix release already.
