### ISSUE TITLE
Incorrect __file__ value for compiled namespace package's sub-package

### ISSUE THREAD

**Issue by bryandeng** [Nuitka/Nuitka#1738]
* Nuitka version, full Python version, flavor, OS, etc.

  ```
  1.0.4
  Commercial: None
  Python: 3.8.10 (default, Jun 22 2022, 20:18:18) 
  Flavor: Debian Python
  Executable: /usr/bin/python3
  OS: Linux
  Arch: x86_64
  Distribution: Ubuntu (based on Debian) 20.04.4
  ```

* How did you install Nuitka and Python

  Nuitka: installed automatically during a `pyproject.toml` based build.
  Python: system Python.

* The specific PyPI names and versions

  ```
  build==0.8.0
  setuptools==65.0.2
  toml==0.10.2
  ```

* Many times when you get an error from Nuitka, your setup may be special

  Install the built wheel from the example below, then the `__file__` value of the namespace package's sub-package contains one additional level of the namespace.

  ```
  Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
  [GCC 9.4.0] on linux
  Type "help", "copyright", "credits" or "license" for more information.
  >>> import a.b
  >>> a.b.__file__
  '/usr/local/lib/python3.8/dist-packages/a/b/__init__.py'
  >>> from a.b import c
  >>> c.__file__
  '/usr/local/lib/python3.8/dist-packages/a/a/b/c/__init__.py'
  ```
  which should be

  ```
  '/usr/local/lib/python3.8/dist-packages/a/b/c/__init__.py'
  ```

  instead.

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

  Construct a minimal Python project as the following, these `__init__.py` are empty files.

  ```
  nuitka-issue/
  ├── a
  │   └── b
  │       ├── c
  │       │   └── __init__.py
  │       └── __init__.py
  └── pyproject.toml
  ```

  The contents of `pyproject.toml` are

  ```
  [build-system]
  requires = [
      "nuitka",
      "setuptools>=45",
      "toml",
      "wheel",
  ]
  build-backend = "nuitka.distutils.Build"
  
  [project]
  name = "a.b"
  version = "0.0.1"
  
  [tool.setuptools.packages.find]
  include = ["a.b*"]
  ```

  Then build the `wheel` by the following command

  > python3 -m build
 
* Provide in your issue the Nuitka options used

  controlled by the `pyproject.toml` file in the example above.

**Comment by joaopfg** [comment]
I have noticed the same bug. For now,my work around is to remove the additional level by hand whenever I use `__file__`.

**Comment by kayhayen** [comment]
Since with wheels, file reference mode ought to be `runtime` the re-formulation and the `ExpressionModuleAttributeFileRef` seem out of the question. I think the code that builds the package, wants to identify a top level package, and may not be friendly with there only being a sub-package to compile. I wonder what Nuitka gets asked to compile here. It may just be that the output is not where it is expected, and that adds the level. I shall look into it.

**Comment by njacquemin1993** [comment]
I noticed the same bug, what is the status of this issue?

**Comment by kayhayen** [comment]
I don't think I ever got the command line of Nuitka that I asked for, which should be present in the wheel build.

**Comment by bryandeng** [comment]
```
Nuitka-Wheel:INFO: Building: 'a.b' with command '['/tmp/build-env-l8xyb6zz/bin/python', '-m', 'nuitka', '--module', '--enable-plugin=pylint-warnings', '--output-dir=/tmp/build-via-sdist-n3f9j7e3/a.b-0.0.1/build/lib/a', '--nofollow-import-to=*.tests', '--remove-output', '--include-package=a.b', '/tmp/build-via-sdist-n3f9j7e3/a.b-0.0.1/build/lib/a/b']'
```

@kayhayen If you need the entire building log, I can post it below.

**Comment by kayhayen** [comment]
So, `a.b.__file__` is actually correct., the the `__file__` values of the contained namespace should be runtime adopted, to one level deeper, and it is, no idea where the `a/` part is coming from. I will need to check that out.

**Comment by kayhayen** [comment]
So, indeed this takes the DLL directory as a base, which works filne for the top name, but the included ones. it seems have the "a" name in themselves. Which is not surprising, since we asked to include "a.b" and not "b".

So for that wheel build, Nuitka should recognize that it's about a namespace package (no code in a), and include `--include-paacke=b` from there. Might need a PYTHONPATH addition to find it.

I am not sure I can make this before 1.5 release, but it will be hotfixable I think.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
I added a test case, and I made it work. Honestly, now I am a bit confused, how it managed to find `b.c`, but I guess, since `b` as a main module is added, that is of course not an issue at all, so effectively all I had to do was to strip the `a`  part.

**Comment by njacquemin1993** [comment]
I tested the factory version, and I confirm it fixes the issue. Thanks!

**Comment by kayhayen** [comment]
This is now on develop and will be part of the 1.5 release shortly.

**Comment by kayhayen** [comment]
This is part of the stable release 1.5 that I just made.
