### ISSUE TITLE
"NameError: name '__annotations__' is not defined" in case of annotations for local variables

### ISSUE THREAD

**Issue by k-sok** [Nuitka/Nuitka#174]
```
$ pip3 install nuitka
$ python -m nuitka --version
0.6.0.3 
Python: 3.6.6 (default, Sep 12 2018, 18:26:19) 
Executable: /usr/bin/python
OS: Linux
Arch: x86_64
```
(same behavior with 0.6.1rc4)

I get `name '__annotations__' is not defined` exceptions for local variables with type annotations. Unfortunately, I was not able to reproduce the behavior with a small example -  annotations for local variables seem to work there. However, in my larger example the reported exception origin is definitely the line containing the local variable definition and after removing the annotations the larger example works.

Sorry for this less meaningful explanation but possibly there are some known issues with annotations for local variables and you know the conditions under which they occur. If not, I'll try to stepwise reduce  the large example in order to pin down the cause.

**Comment by kayhayen** [comment]
No, I am not aware of any problem right there.  If you can provide a reproducer, that will be good.

**Comment by k-sok** [comment]
I got it. It's about annotations in generators: 

```
$ printf "def gen():\n   x: int = 1\n   yield 1\nnext(gen())" > test.py
$ python -m nuitka --module test.py
$ python -c "import test"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/playground/test.py", line 4, in <module test>
    next(gen())
  File "/home/playground/test.py", line 2, in gen
    x: int = 1
NameError: name '__annotations__' is not defined
```

However, this works fine:

```
$ printf "def gen():\n   x = 1\n   yield 1\nnext(gen())" > test.py
$ python -m nuitka --module test.py
$ python -c "import test"
$ 
```

**Comment by kayhayen** [comment]
uh, this only happens on module mode, not in program mode, which is a total surprise to me.

**Comment by kayhayen** [comment]
So it's using the module level `__annotations__` and for compatibility, in Nuitka there is code like this which prevents this from being noticed in small test programs:
```
    if is_module and is_main and python_version >= 360:
        provider.markAsNeedsAnnotationsDictionary()
```

That explains why this as bug could also be hidden, if you had module level annotations in the same module.

**Comment by kayhayen** [comment]
Although, the hiding will only be done with 3.7, the 3.6 was better at not allowing to confuse the two.

**Comment by kayhayen** [comment]
The issue is that in tree building, function bodies and everything else are being distinguished, but it really should be modules/classes and everything else, where they are basically ignored, except acting as a forward declaration that such a local should exist maximally.

Needless to say, when undetected, this was very wasteful to do, as assigning a subscript to the global will have been slow and more code generated.

I believe not a lot of people use annotations in generators yet, which is maybe why this wasn't seen so far. 

Anyway, a fix is on factory, but should be seen through my CI to be sure it has no other consequences.

I am preparing a 0.6.1 for "as soon as possible" so I might skip on the potential hotfix this could be, unless I find out reasons for it to not happen within the next couple of days.

**Comment by kayhayen** [comment]
Ah and thanks for tracking this down to the nice reproducer, I bet this wasn't easy. :)

**Comment by k-sok** [comment]
> I believe not a lot of people use annotations in generators yet, which is maybe why this wasn't seen so far.

Well, I'm using the annotations approximately in the same manner as I was using C++'s const keyword: everywhere, where it's not forbidden (admittedly not that strict :))

> Ah and thanks for tracking this down to the nice reproducer, I bet this wasn't easy. :)

You're welcome. It took a couple of hours but the good thing was that I had only to remove code, never bring back removed parts

**Comment by kayhayen** [comment]
Part of the 0.6.0.5 hotfix I just made.

**Comment by k-sok** [comment]
Thank you very much!
