### ISSUE TITLE
Nuitka doesn't go along with the Onnxruntime. Numpy plugin is enabled.

### ISSUE THREAD

**Issue by remort** [Nuitka/Nuitka#1740]
Hello. I'm trying to build an aiohttp microservice with onnx (and thus witn numpy) into a standalone app. I do it for the first time.
I do it inside `python:3.10.6-slim-bullseye` container.

`python -m nuitka --version`:

```
1.0.4
Commercial: None
Python: 3.10.6 (main, Aug  3 2022, 10:24:07) [GCC 10.2.1 20210110]
Flavor: Unknown
Executable: /usr/local/bin/python
OS: Linux
Arch: x86_64
Distribution: Debian 11
```

`python -m pip freeze`

```
aiochclient==2.1.0
aiohttp==3.8.1
aiosignal==1.2.0
alembic==1.8.1
async-timeout==4.0.2
attrs==22.1.0
certifi==2022.6.15
charset-normalizer==2.1.0
click==8.1.3
cloudpickle==2.1.0
coloredlogs==15.0.1
databricks-cli==0.17.2
docker==5.0.3
entrypoints==0.4
Flask==2.2.2
flatbuffers==2.0
frozenlist==1.3.1
gitdb==4.0.9
GitPython==3.1.27
greenlet==1.1.2
gunicorn==20.1.0
humanfriendly==10.0
idna==3.3
importlib-metadata==4.12.0
itsdangerous==2.1.2
Jinja2==3.1.2
Mako==1.2.1
MarkupSafe==2.1.1
mlflow==1.28.0
mpmath==1.2.1
multidict==6.0.2
Nuitka==1.0.4
numpy==1.23.2
oauthlib==3.2.0
onnx==1.12.0
onnxruntime==1.12.1
packaging==21.3
pandas==1.4.3
prometheus-client==0.14.1
prometheus-flask-exporter==0.20.3
protobuf==3.20.1
PyJWT==2.4.0
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2022.2.1
PyYAML==6.0
querystring-parser==1.2.4
requests==2.28.1
scipy==1.9.0
six==1.16.0
smmap==5.0.0
SQLAlchemy==1.4.40
sqlparse==0.4.2
sympy==1.10.1
tabulate==0.8.10
typing_extensions==4.3.0
Unidecode==1.3.4
urllib3==1.26.11
uvloop==0.16.0
wait-for-it==2.1.1
websocket-client==1.3.3
Werkzeug==2.2.2
yarl==1.8.1
zipp==3.8.1
```

I run Nuitka like this: `python3 -m nuitka --include-package=app --onefile --follow-imports --standalone --include-data-file=/onnxruntime-linux-x64-1.12.1/lib/libonnxruntime.so=./ --enable-plugin=numpy --follow-import-to=numpy app/run.py`

providing an onnx .so file for it fron this archive which has the same version with onnx installed from pypi:
`https://github.com/microsoft/onnxruntime/releases/download/v1.12.1/onnxruntime-linux-x64-1.12.1.tgz`

Compile of my succedes, but when I run it, I get the following error:
```
ModuleNotFoundError: No module named 'numpy'
ImportError: numpy.core.multiarray failed to import
```

**Comment by remort** [comment]
Seems to be a problem with compiling `onnxruntime` library but not `numpy`. A minimal research is represented here: https://github.com/Nuitka/Nuitka/issues/738#issuecomment-1222054414

**Comment by Ibax1** [comment]
Hello. Any progress/update on this issue?

**Comment by kayhayen** [comment]
Yes, supposed to work.
