### ISSUE TITLE
How to make pymssql and cx_oracle into onefile?

### ISSUE THREAD

**Issue by laferce** [Nuitka/Nuitka#1741]
I use sqlalchemy to connect to databases with drivers of pymysql, pymssql and cx_oracle. They go well in program.py.
When I pack it into onefile program.exe, pymysql goes well but the other two raise the same Exception:
```
Traceback (most recent call last):
  File "C:\Users\my\AppData\Local\Temp\ONEFIL~1\test.py", line 7, in <module>
    c=sqlalchemy.create_engine('mssql+pymssql://sa:1@192.168.200.128:1433/msdb')
  File "<string>", line 2, in create_engine
  File "C:\Users\my\AppData\Local\Temp\ONEFIL~1\sqlalchemy\util\deprecations.py", line 309, in warned
  File "C:\Users\my\AppData\Local\Temp\ONEFIL~1\sqlalchemy\engine\create.py", line 522, in create_engine
  File "C:\Users\my\AppData\Local\Temp\ONEFIL~1\sqlalchemy\engine\url.py", line 655, in _get_entrypoint
  File "C:\Users\my\AppData\Local\Temp\ONEFIL~1\sqlalchemy\util\langhelpers.py", line 343, in load
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:mssql.pymssql
```
or
`sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:oracle.cx_oracle`
The code likes this:
```
import cx_Oracle,pymssql,pymysql,sqlalchemy
from pymssql import _mssql
from sqlalchemy.sql import default_comparator
# MySQL:
c=sqlalchemy.create_engine('mysql+pymysql://root:root@192.168.200.128:3306/mysql')
print(c.execute('select * from user').fetchone())
# SQL Server:
c=sqlalchemy.create_engine('mssql+pymssql://sa:1@192.168.200.128:1433/msdb')
print(c.execute('select * from msdb.dbo.sysutility_mi_smo_properties_to_collect_internal').fetchone())
# Oracle
c=sqlalchemy.create_engine('oracle+cx_oracle://sys:1@192.168.200.128:1521/xe?mode=sysdba')
print(c.execute('select * from ICOL$').fetchone())
```
The command is:
`nuitka --onefile --remove-output program.py`
I have tried the args like `--follow-imports`, `--include-package=pymssql`, `--follow-import-to=pymssql` and so on but nothing changed.
How can I fix this problem? Thank you.

**Comment by subtle99** [comment]
same issue

**Comment by kayhayen** [comment]
I was thinking, I would need actual database installations, but it seems the creation of the engines doesn't require it. So I stripped the example original provided of these, and I can go with that.

**Comment by kayhayen** [comment]
My bad, I didn't put a milestone or help wanted on this one, so it fell through the cracks. It seems it's only missing a few implicit dependencies, that I am adding now. For sqlalchemy, people have made Yaml configuration changes for Nuitka according to https://nuitka.net/doc/nuitka-package-config.html in the past already, but if I don't even tag it as help wanted, that's not happening for this issue.

**Comment by kayhayen** [comment]
With a minor change this works now:

```
import sqlalchemy

# MySQL:
c = sqlalchemy.create_engine("mysql+pymysql://root:root@192.168.200.128:3306/mysql")
# print(c.execute('select * from user').fetchone())
# SQL Server:
c = sqlalchemy.create_engine("mssql+pymssql://sa:1@192.168.200.128:1433/msdb")
# print(c.execute('select * from msdb.dbo.sysutility_mi_smo_properties_to_collect_internal').fetchone())
# Oracle
c = sqlalchemy.create_engine(
    "oracle+cx_oracle://sys:1@192.168.200.128:1521/xe?mode=sysdba"
)
```

Of course the respective bindings need to be installed, but then are picked up automatically. Not sure if at runtime anything is happening at all. I cannot test that easily, so please report if there is anything with factory still.

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.
