### ISSUE TITLE
Provide a way to include license files in AppImage

### ISSUE THREAD

**Issue by gvegidy** [Nuitka/Nuitka#1747]
When running for example `python3 -m nuitka --standalone --onefile diag.py` it builds a AppImage that contains the compiled python packages and some necessary .so files from the system, for example `libpython3.10.so.1.0` and `libssl.so.1.1`.

Many python packages and system libraries are released under a Open Source license that requires binary distributions of the code to contain the full license text.

For example the python license contains (shortened by me):
```
[...] provided, however, that PSF's License Agreement and PSF's notice of copyright,
[...] are retained
```
and the openssl license contains:
```
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
```
and the Apache license nuitka itself comes with:
```
a. You must give any other recipients of the Work or Derivative Works a copy of this License; and
```

So while I'm not a lawyer and don't know if any of these clauses have been tested in court, I read them all like the license texts should be included in the AppImage itself or distributed together with it.

Nuitka should provide a way to comply with these licenses without too much hassle for the developer.

It could work like this:
1. nuitka outputs the source filenames with full path of all python modules it compiles
2. nuitka outputs the .so libraries with full path of all shared libs it includes
3. the package manager is queried for these files and the related packages are found out
4. in most current Linux distributions each package comes with a license file in for example `/usr/share/licenses/`
5. the license files are included in a subdir within the AppImage
6. the developer adds a short code snippet that allows to browse the included licenses when a special commandline option is given

Unfortunately I don't know of an easy and distribution-independent way to find a license file to some source file.

So I think to get this at least going, nuitka should as first step get an option to output a list of all source files (points 1. and 2. above).

When using the `--show-modules-output` option you already get parts of it. But this output seems to be more directed at human readers debugging dependency problems and is not suitable to pipe into a script that does the distribution dependent license file lookup. 

So maybe the code for `--show-modules-output` could be adapted to create a new option, for example called `--show-source-files`
The file written out by it could then look like this:
```
/usr/lib/python3.10/abc.py
/usr/lib/python3.10/ast.py
/usr/lib/python3.10/codecs.py
/usr/lib/python3.10/collections/__init__.py
[...]
/usr/lib/libpython3.10.so.1.0
/usr/lib/libssl.so.1.1

```
You could then use this and a distribution dependent script to get the necessary license files.

---

```
  > python -m nuitka --version
0.8.4
Commercial: None
Python: 3.10.5 (main, Aug  1 2022, 07:53:20) [GCC 12.1.0]
Flavor: Unknown
Executable: /usr/bin/python
OS: Linux
Arch: x86_64
Distribution: Sysrescue (based on arch) 9.04
```

* How did you install Nuitka and Python
Arch Linux package nuitka 0.8.4-1 installed via pacman

**Comment by MultiDragon** [comment]
does `--include-data-files` not do what you want?

**Comment by gvegidy** [comment]
My main problem right now is figuring out for which source files I have to add the licenses.

Finding all used source files should be done fully automatic and not by hand, because new dependencies with new licenses could be added without the developer doing anything, just because a package you actively import now requires some other package in a new version.

As far as I understand, `--include-data-files` would include the files, but I have to know in advance which files. So it could for example be used in a second run of nuitka, when I figured out all necessary license files in a first run.

**Comment by kayhayen** [comment]
Nuitka is not using AppImage anymore. I am not a lawyer either, but if the PyPI packages do not contain a license file, then your binary probably doesn't have to do it either.

Data files can be added to the Yaml configuration, where this an issue. I am pretty sure the PSF copyright notice is only for source code and not binaries, but I could be wrong there too.

**Comment by kayhayen** [comment]
I am putting this as invalid, as data files can be easily added to the Yaml configuration already, so there is no problem with that.

**Comment by kayhayen** [comment]
Nuitka has a compilation report with `--report` which contains what is included, and I think with the original source. If a file must be included, I welcome PRs that do that. In some instances, Nuitka already does it.

**Comment by gvegidy** [comment]
Thanks for the pointer to `--report`.

It contains the source files for included shared libraries like this:
```
<included_dll name="libssl.so.1.1" dest_path="libssl.so.1.1" source_path="/usr/lib/libssl.so.1.1" package="/usr/lib/libssl.so.1.1" ignored="no" />
<included_extension name="_lzma.so" dest_path="_lzma.so" source_path="/usr/lib/python3.10/lib-dynload/_lzma.cpython-310-x86_64-linux-gnu.so" package="/usr/lib/python3.10/lib-dynload/_lzma.cpytho
n-310-x86_64-linux-gnu.so" ignored="no" />
```

But it is missing source information for python modules (`UncompiledPythonModule` and `CompiledPythonModule`) used:
```
  <module name="http.client" kind="UncompiledPythonModule" reason="Instructed by user to follow all modules, including non-automatic standard library modules." />
<module name="dialog" kind="CompiledPythonModule" reason="Instructed by user to follow to all non-standard library modules." />
```

I would appreciate it if you could add the source files for these to the report file. Thanks.

**Comment by kayhayen** [comment]
I might do it if the request was related to this: https://nuitka.net/doc/commercial.html

Currently the report is a feature that is not complete, and I spotted a bug in your output, but I don't think I have the time right now to do this. You can write a Nuitka plugin, they also get this information. I don't see this as a priority right now.

**Comment by gvegidy** [comment]
Without a comprehensive list of sources it is very hard to find out which source files and licenses are actually used and have to be dealt with. Without complying with all the license conditions of all used modules and shared libraries, you are not allowed to distribute the resulting binary. 

For me using Nuitka becomes moot when I am not allowed to distribute the resulting binary. So I rate this as something like a showstopper.
