### ISSUE TITLE
nuitka.net uses an unsupported protocol.

### ISSUE THREAD

**Issue by hashuser** [Nuitka/Nuitka#1748]
<img width="1280" alt="Screenshot 2022-08-23 072016" src="https://user-images.githubusercontent.com/60065064/186085441-3b177a2e-c12f-4e43-b7a4-10a1821b8b80.png">

**Comment by kayhayen** [comment]
Had to disable cloudfare, which unfortunately is going to make the site slow, not sure what the issue is there, but it works for now.
