### ISSUE TITLE
Nuitka in azure devops pipeline

### ISSUE THREAD

**Issue by melanieStryder** [Nuitka/Nuitka#1749]
Hey

I am using python 3.9.12 and nutika 0.7.6. I am trying to automate the creation of exe using build azure devops pipeline which was done manually in my local machine. The command works perfectly in my local machine but when running through the pipeline, the generated exe is small in size(29mb instead of 70mb) and exiting without an error on running in the local command prompt. All the dependency files and folders are already provided in the command.

The only discrepancy I could find is the mistmatch of acrhes but in the command I have used --mingw64, --assume-yes-for-downloads, --onefile &  --windows-disable-console.  --plugin-enable=tk-inter $(System.DefaultWorkingDirectory)\myFile.py used for python file.  All the required folder and files are present in the azure repository.

I am installing nuitka using pip in the pipeline.

![image](https://user-images.githubusercontent.com/111873346/186149243-3f246f76-0e98-4a43-a84c-6d17eef4d56c.png)

**Comment by kayhayen** [comment]
No issue template no fun, and very old Nuitka too.
