### ISSUE TITLE
Numpy.bool_ object is not iterable

### ISSUE THREAD

**Issue by ebranlard** [Nuitka/Nuitka#175]
I'm running into a problem compiling a script using numpy, on windows 10. I tried with python 2.7, 3.6 and 3.7. 
I'm using the following compilation command:
``` bash
python -m nuitka --follow-imports --include-plugin-directory --include-plugin-files --show-progress test.py
```
with the following content for the file `test.py`:
``` python
import numpy as np
x = np.linspace(0,1,5)
a = np.isclose(0.5,x)
```
(This python script works on my machine when called from python)
The compilation works but the created .exe file outputs the following error:
``` bash
  File "XXXXtest.py", line 3, in <module>
    a=np.isclose(0.5,x)
  File "C:\Bin\Python36\lib\site-packages\numpy\core\numeric.py", line 2365, in isclose
    if all(xfin) and all(yfin):
TypeError: 'numpy.bool_' object is not iterable
```

I hope you can reproduce and maybe point out where this error comes from. I created this example because I actually failed to compile a small script that uses matplotlib. Matplotlib relies on numpy and the exe generated by nuitka would crash with the error: `TypeError: 'numpy.bool_' object is not iterable`, similar to the one mentioned above for the canonical "numpy" case.  
Thank you for your help.

Note: I use Visual Studio 2017 tools v15.0. I have used nuitka successfully on other scripts.

**Comment by kayhayen** [comment]
This issue seems to be one already solved, although I believe at the time I assumed it only affects develop. You failed to fill out the issue template (why do people skip it?), so I am left to guessing what you have used exactly.

**Comment by kayhayen** [comment]
Misclick

**Comment by kayhayen** [comment]
Your test program works for me at least on develop code.

**Comment by kayhayen** [comment]
Definitely makes me reconsider my plans, as this one is an important one. I was going to have more performance stuff before 0.6.1 release, but I will try to stabilize as soon as possible, then release in the light of this.

**Comment by kayhayen** [comment]
I am still delaying the release for bugfixing. I will close this issue however now, being in develop is kind of good enough.

**Comment by opaka** [comment]
I have the same bug after nuitka compilation is it going to be solved soon ?

**Comment by kayhayen** [comment]
@opaka it is
