### ISSUE TITLE
`--onefile` requires xpm icon file on Linux although it is not used anymore

### ISSUE THREAD

**Issue by gvegidy** [Nuitka/Nuitka#1750]
When running nuitka on Linux with the `--onefile` option, it looks for a python xpm icon file. If it is not found it errors out like this:
```
# nuitka3 --standalone --onefile diag.py 
Nuitka-Options:INFO: Used command line options: --standalone --onefile diag.py
FATAL: Error, none of the default icons '/usr/share/pixmaps/python3.10.xpm, /usr/share/pixmaps/python3.xpm, /usr/share/pixmaps/python.xpm' exist, making '--linux-onefile-icon' required.
```
When looking at a created onefile binary, it looks like the icon file is not included anymore, probably since AppImage isn't used anymore. 

Not all Linux distributions include a easily usable python xpm icon file. For example I could not find one packaged in Arch Linux and had to copy one from another system. So requiring the xpm icon creates usage issues there.

Please check if my observation that the xpm file isn't used anymore is correct. If yes, please consider removing the check for it.

---
  > python -m nuitka --version
```
1.0.5
Commercial: None
Python: 3.10.6 (main, Aug  3 2022, 17:39:45) [GCC 12.1.1 20220730]
Flavor: Unknown
Executable: /usr/bin/python
OS: Linux
Arch: x86_64
Distribution: Sysrescue (based on arch) 9.04
```
* How did you install Nuitka and Python
Arch Linux packages python-3.10.6-1 and nuitka-1.0.5-1 installed through pacman.
No virtualenv used.

**Comment by kayhayen** [comment]
That is true, the idea is of course that we can produce a desktop file one day on Linux. However, that is not going to happen all that soon, and even then, an icon would not be mandatory.

**Comment by kayhayen** [comment]
I have remove the check on the factory branch, https://nuitka.net/doc/factory.html

**Comment by gvegidy** [comment]
I have tested your patch and it is looking good to me.

Thanks for the quick fix!

**Comment by kayhayen** [comment]
Keeping issue open until they solved in stable release.

**Comment by kayhayen** [comment]
Part of 1.0.6 hotfix release.
