### ISSUE TITLE
Can't using external module after packing

### ISSUE THREAD

**Issue by ChuanRayChou** [Nuitka/Nuitka#1752]
I want to using external python script after packing like below.

packing command ::

```
nuitka --mingw64 --standalone --output-dir=out  packing.py
```
packing.exe
module 
  |-- function.py

but it show error ModuleNotFoundError: No module named 'function'

```
> .\gui_wx.exe
Traceback (most recent call last):
ModuleNotFoundError: No module named 'module .function'
```
  > python -m nuitka --version

```
1.0.4
Commercial: None
Python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\eraycho\Anaconda3\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

* How did you install Nuitka and Python

windows 10 , python 3.9.12 with Anaconda3, Nuitka install by [conda](https://anaconda.org/conda-forge/nuitka)
No virtualenv used.

**Comment by kayhayen** [comment]
Without a reproducer, this is useless.

**Comment by ChuanRayChou** [comment]
What do I need to provide?
all script ?? or just packing.exe and function.py ???

**Comment by kayhayen** [comment]
Mixing compiled packages with source code files is not working, only extension modules do at this time. Nuitka does not include a soure file loader in its package loader for your package. This is actually a duplicate that affects acceleration mode too, where that is more of an issue, that partially compiled stuff does not work.

If you were to not compile the package at all, things would have a chance. You can ask Nuitka to `--nofollow-import-to` on its name.

**Comment by kayhayen** [comment]
Being able to put source code into a distribution is not really supported, and also you were unclear if you put it into a dist folder, your layout omitted the dist level.

**Comment by ChuanRayChou** [comment]
> Being able to put source code into a distribution is not really supported, and also you were unclear if you put it into a dist folder, your layout omitted the dist level.

first thank's your reply, yes I have put the pm_event.function into dist, but still not work.

**Comment by kayhayen** [comment]
If you provide the resulting file from `--report` that would be useful.

**Comment by ChuanRayChou** [comment]
I have try packing with `--report=report` many times, but could not find any output. did you have any idle ??

**Comment by kayhayen** [comment]
never hesitate to read help output and let me know what is unclear there.

**Comment by ChuanRayChou** [comment]
Yes! I have read the help already packing command as below, then still have nothing.

`nuitka --mingw64 --standalone --output-dir=out --nofollow-import-to=module --report=with_no_inport  main.py`

output ::
```
Nuitka:INFO: Keeping dist folder 'out\\main.dist' for inspection, no need to use it.
Nuitka:INFO: Keeping build directory 'out\\main.build'.
Nuitka:INFO: Successfully created 'out\\main.exe'.
Nuitka:INFO: Compilation report in file 'with_no_inport'.
```

**Comment by kayhayen** [comment]
I am sorry, I cannot help you then.
