### ISSUE TITLE
Multiprocessing library running very slowly

### ISSUE THREAD

**Issue by my1e5** [Nuitka/Nuitka#1753]
I have a performance related problem when using the `multiprocessing` library. Here is a MWE that creates a `Pool` of workers and measures the time this takes. 

```python
# main.py
from multiprocessing import Pool
from time import perf_counter

def main():
    while True:
        processes = int(input("Enter number of processes: "))
        t1 = perf_counter()
        with Pool(processes=processes):
            pass
        t2 = perf_counter()
        print(f"Time taken: {t2-t1}")

if __name__ == "__main__":
    main()
```
Running this script with my python interpreter I get the following sort of performance:
```
$ python main.py
Enter number of processes: 1
Time taken: 0.06969530001515523
Enter number of processes: 6
Time taken: 0.13465180003549904
Enter number of processes: 12
Time taken: 0.3786882000276819
```
When I create an executable with Nuitka using `python -m nuitka --clang --standalone main.py` and run the resulting .exe I get:
```
$ ./main.exe
Enter number of processes: 1
Time taken: 1.668638400034979
Enter number of processes: 6
Time taken: 9.8353400999913
Enter number of processes: 12
Time taken: 19.345703400031198
```
As you can see, the time taken to spawn the pool of workers is considerably slower. Is this expected behaviour? For context, in the project I'm working on I am using the `scipy.optimize` library with parallel computing enabled. And I traced the slow execution time to the use of the `multiprocessing` library. 

* Version/Platform: Python 3.10 (installed from python.org) , Nuitka 1.0.5 (installed via pip), Windows 10
```
$ python -m nuitka --version
1.0.5
Commercial: None
Python: 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\Username\AppData\Local\Programs\Python\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

**Comment by kayhayen** [comment]
I testing this myself, and fail to reproduce it. At the time I wondered, if your reproducer is lacking the imports, not sure now, but I think I never believed this one. With onefile it would have been the case until relatively recently, like 1.5.x or so.

I got this numbers from Nuitka:

```
Enter number of processes: 1
Time taken: 0.028629800013732165
Enter number of processes: 6
Time taken: 0.03226959996391088
Enter number of processes: 12
Time taken: 0.07118139998055995
```

Compare to CPython

```
Enter number of processes: 1
Time taken: 0.03625340003054589
Enter number of processes: 6
Time taken: 0.03780900000128895
Enter number of processes: 12
Time taken: 0.06947769998805597
```

Differences would appear to be noise. Seems we either improved startup since, but I would consider this solved now.
