### ISSUE TITLE
Linux: Linker error about Py symbols missing for dynamic modules when using clang and static libpython

### ISSUE THREAD

**Issue by vinayinvicible** [Nuitka/Nuitka#1759]
When dynamic modules (math, fcntl, etc...) are used in the script, the binary generated using onefile, clang and static-libpython does not work as expected.

* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version
1.0.5
Commercial: None
Python: 3.7.3 (default, Aug 27 2022, 03:08:47) 
Flavor: pyenv
Executable: /home/vinay/code/testing/compile/.venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 20.04.4

  If you are not providing the full output. The issue cannot be solved and will
  be considered `invalid`. It does more than you think, and we are adding more
  all the time. We do not want to left guessing or trying things out to
  reproduce your issue.

* How did you install Nuitka and Python

  > Installed Python using pyenv.
Installed Nuitka via pip.

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

```python
# asd.py
import fcntl
print("Hello World!")
```

* Provide in your issue the Nuitka options used

  > python -m nuitka asd.py --clang --onefile --static-libpython=yes
Nuitka-Options:INFO: Used command line options: asd.py --clang --onefile --static-libpython=yes --prefer-source-code
Nuitka:INFO: Starting Python compilation with Nuitka '1.0.6' on Python '3.7' commercial grade 'not installed'.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka:INFO: Completed Python level compilation and optimization.                        
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.       
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: clang (clang).
Nuitka-Scons:INFO: Backend linking program with 13 files (no progress information available).
Nuitka-Scons:INFO: Compiled 13 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 12
Nuitka-Postprocessing:INFO: Creating single file from dist folder, this may take a while.
Nuitka-Onefile:INFO: Running bootstrap binary compilation via Scons.
Nuitka-Scons:INFO: Onefile C compiler: clang (clang).
Nuitka-Scons:INFO: Onefile linking program with 1 files (no progress information available).
Nuitka-Scons:INFO: Compiled 1 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 1
Nuitka-Onefile:INFO: Keeping onefile build directory 'asd.onefile-build'.
Nuitka-Onefile:INFO: Using compression for onefile payload.
Nuitka-Onefile:INFO: Onefile payload compression ratio (27.12%) size 38114835 to 10335659.
Nuitka:INFO: Keeping dist folder 'asd.dist' for inspection, no need to use it.
Nuitka:INFO: Keeping build directory 'asd.build'.
Nuitka:INFO: Successfully created 'asd.bin'.

Generated binary raises exception

  > ./asd.bin

Traceback (most recent call last):
  File "/tmp/onefile_52525_1661548149_47879/asd.py", line 2, in <module>
    import fcntl
ImportError: /tmp/onefile_52525_1661548149_47879/fcntl.so: undefined symbol: PyExc_ValueError

**Comment by kayhayen** [comment]
Not sure if pyenv is to blame here, or if using clang is. I would need `--show-scons` output from you, to know what branches are taken.

**Comment by vinayinvicible** [comment]
Fixed in https://github.com/Nuitka/Nuitka/pull/1760

**Comment by kayhayen** [comment]
yes, good job, thanks for helping yourself there!
