### ISSUE TITLE
Commerical Nuitka

### ISSUE THREAD

**Issue by FuckingToasters** [Nuitka/Nuitka#1763]
I looked at the commerical website, which showcase the features and the pricing.
It seems that the normal commerical version without commercial extra support cost 250€/year.
This is a bit expencive for just 1 year if you look at free obfuscators like pyarmor (which are probably not as good as nuitka)

I'm unsure if you pay access for 1 year and after that year has passed you lose access or if you technically buy lifetime access but new versions & support stops after that 1 year.

Would be nice if anyone can answer the question stated above as soon as possible!

Regards,
FuckingToasters.

**Comment by kayhayen** [comment]
You loose access to the updates after one year, e.g. a Python 3.11 support wouldn't be there. Nuitka is not a code obfuscucator, but a compiler, so the comparison to pyarmor is moot. Hiding your code is different from not shipping your code.

If 250/yr is expensive, you probably need to consider if you have anything of value to protect.
