### ISSUE TITLE
ModuleNotFoundError for Pandas Private Module

### ISSUE THREAD

**Issue by newTypeGeek** [Nuitka/Nuitka#1765]
I try to use Nuitka to compile this script. The compilation is successful and a `.bin` file is generated. But upon execution, it raises `ModuleNotFoundError: No module named 'pandas._config.localization`
```python
import time

import pandas as pd

SLEEP_SEC = 5

while True:
    now = pd.Timestamp.utcnow()
    print(f"{now=}")

    print(f"Sleep for {SLEEP_SEC} seconds")
    time.sleep(SLEEP_SEC)
```

 ## Nuitka version
I tried the latest stable release (`1.0.6`) before, but the same error occurs. So, I switch to the latest pre-release version `1.1rc7`
  > python -m nuitka --version

  ```
  1.1rc7
  Commercial: None
  Python: 3.9.12 (main, Jun  1 2022, 06:36:29) 
  Flavor: Anaconda Python
  Executable: /opt/miniconda3/envs/secure-python/bin/python
  OS: Darwin
  Arch: x86_64
  ```

## Installation of Python and Nuitka and Python packages
  ```
   conda create -n nuitka-tutorial python=3.9 -y
   conda activate nuitka-tutorial
   pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"
   pip install numpy==1.23.2
   pip install pandas==1.4.3
  ```

## The specific PyPI names and versions

  > python -m pip freeze
  ```
  anyio==3.6.1
  certifi @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_83242e7e-f82d-4a71-8ef2-9d71d212d249gu_wxmeq/croots/recipe/certifi_1655968827803/work/certifi
  charset-normalizer==2.1.1
  h11==0.12.0
  httpcore==0.15.0
  idna==3.3
  Nuitka @ https://github.com/Nuitka/Nuitka/archive/develop.zip
  numpy==1.23.2
  pandas==1.4.3
  python-dateutil==2.8.2
  pytz==2022.2.1
  rfc3986==1.5.0
  six==1.16.0
  sniffio==1.2.0
  typing_extensions==4.3.0
  urllib3==1.26.12
   ```

**Comment by kayhayen** [comment]
Maybe the error is Anaconda specific, or maybe new Pandas, seems pretty innocent pandas usage, I believe the version was working in other OSes so far, probably them (Anaconda) moving code to shared places again.

**Comment by kayhayen** [comment]
I verified it works on macOS as expected, now trying with Anaconda.

**Comment by MalcolmMielle** [comment]
I have the same error on linux when using venv and no anaconda.

**Comment by kjczarne** [comment]
Just run into the same issue on x86_64 Ubuntu 22.04, Python 3.8.15, Nuitka 1.2.3.
I am not using conda, this is running under plain `virtualenv` in my case.
Is there a way we can force Nuitka to discover protected modules?

**Comment by kayhayen** [comment]
The original report seems to not be using standalone mode, which I have to infer from the `.bin` suffix, however it's unclear what was included, and what was not, making this a very bad report. And the me toos, while providing some information didn't add to it. Nuitka is not good at partially compiling modules in accelerated mode, like pandas and then to have some extension modules mixed in. Can you confirm of deny using --standalone mode here?

**Comment by kjczarne** [comment]
Thanks for the response! I was not using the `--standalone` flag. With the `--standalone` flag, pandas seems to work.

**Comment by kayhayen** [comment]
The accelerated mode using mixed code still needs to be enhanced, but I didn't find the time for the issue yet. Most people affected are using the wrong mode anyway.
