### ISSUE TITLE
Library not loaded: '@rpath/libpython3.10.dylib'

### ISSUE THREAD

**Issue by ElbartoLennyy** [Nuitka/Nuitka#1771]
I installed miniconda via homebrew and then created a virtual environment. I installed it via pip nuitka and orderset and tried to build the hello test file from the example on the website. I used nuitka bevor on windows, were I had no problem. I am running it now on an M1 Pro Macbook. 
I´ve tried the stable release and the development version. 

> python -m nuitka --standalone hello.py                                          (tester) 

Building it works fine without errors. 

```
Nuitka-Options:INFO: Used command line options: --standalone hello.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.1rc8' on Python '3.10' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.                        
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: clang (clang).
Nuitka-Scons:INFO: Backend linking program with 10 files (no progress information available).
Nuitka-Scons:WARNING: You are not using ccache.
Nuitka:INFO: Keeping build directory 'hello.build'.                             
Nuitka:INFO: Created binary that runs on macOS 11.1 (arm64) or higher.
Nuitka:INFO: Successfully created 'hello.dist/hello'
```

Running then the output file results in this error.  The file libpython3.10.dylib which cannot be found is in the directory. Building it in normal mode (not onefile or standalone) works just fine. 

>hello.dist/hello 
```
dyld[10503]: Library not loaded: '@rpath/libpython3.10.dylib'
  Referenced from: '/Users/alex/dev/env-tester/hello.dist/hello'
  Reason: tried: '$ORIGIN/libpython3.10.dylib' (no such file), '$ORIGIN/libpython3.10.dylib' (no such file), '/usr/local/lib/libpython3.10.dylib' (no such file), '/usr/lib/libpython3.10.dylib' (no such file)
fish: Job 1, './hello' terminated by signal SIGABRT (Abort)
```

  > python -m nuitka --version
```
1.1rc8
Commercial: None
Python: 3.10.4 (main, Mar 31 2022, 03:37:37) [Clang 12.0.0 ]
Flavor: Anaconda Python
Executable: /opt/homebrew/Caskroom/miniconda/base/envs/tester/bin/python
OS: Darwin
Arch: arm64
```

> pip list 
```
Package     Version
----------- ---------
certifi     2022.6.15
Nuitka      1.1rc8
ordered-set 4.1.0
pip         22.1.2
setuptools  63.4.1
wheel       0.37.1
```

Thanks a lot for the help.

**Comment by ElbartoLennyy** [comment]
With the factory version it works for me. Thansk for the quick fix for now!

**Comment by kayhayen** [comment]
This is part of develop version now.

**Comment by roniemartinez** [comment]
Hope the fix will be released soon. I got the same error when building an app bundle in Github Actions and then trying to install it to my desktop.

```
dyld[52300]: Library not loaded: '/Users/runner/hostedtoolcache/Python/3.10.6/x64/lib/libpython3.10.dylib'
  Referenced from: '/Applications/MyApp.app/Contents/MacOS/MyApp'
  Reason: tried: '/Users/runner/hostedtoolcache/Python/3.10.6/x64/lib/libpython3.10.dylib' (no such file), '/usr/local/lib/libpython3.10.dylib' (no such file), '/usr/lib/libpython3.10.dylib' (no such file)
[1]    52300 abort      /Applications/MyApp.app/Contents/MacOS/MyApp
```

- Building it from my machine works fine (to be expected because it can find it).
- Another observation is that `libpython3.10.dylib` is not included in the package contents but all other `dylib` files are there

**Comment by kayhayen** [comment]
Well, Nuitka runs its test on 3.10 just fine on Github Actions for all I know @roniemartinez this issue is for Anaconda mixed configuration. It may not be building in build mode, but so far I have not witnessed a big difference there.

**Comment by roniemartinez** [comment]
Thanks for your reply @kayhayen 

For me, error only happens if I run the app built from Github Actions (`macos-latest`) in my local machine. I downloaded this build using `actions/upload-artifact@v3`.

I've tried some configuration and was able to include `libpython3.10.dylib` in the resulting bundle. However, I get the same error when running the built app.

You can find my builds here:
- PR: https://github.com/roniemartinez/nuitka-build/actions/runs/3031630183
- Built artifacts/installer: https://github.com/roniemartinez/nuitka-build/actions/runs/3031630183

Error (same as before):
```
/Applications/myapp.app/Contents/MacOS/myapp ; exit;
dyld[60478]: Library not loaded: '/Users/runner/hostedtoolcache/Python/3.10.6/x64/lib/libpython3.10.dylib'
  Referenced from: '/Applications/myapp.app/Contents/MacOS/myapp'
  Reason: tried: '/Users/runner/hostedtoolcache/Python/3.10.6/x64/lib/libpython3.10.dylib' (no such file), '/usr/local/lib/libpython3.10.dylib' (no such file), '/usr/lib/libpython3.10.dylib' (no such file)
[1]    60478 abort      /Applications/myapp.app/Contents/MacOS/myapp
```

Bundle contents:
```
$ ls /Applications/myapp.app/Contents/MacOS | grep dylib
libcrypto.1.1.dylib
libgdbm.6.dylib
libgdbm_compat.4.dylib
libintl.8.dylib
liblzma.5.dylib
libpyside6.abi3.6.3.dylib
libpython3.10.dylib
libshiboken6.abi3.6.3.dylib
libssl.1.1.dylib
```

It looks like it is still linked to system's `libpython3.10.dylib` instead of the included file.

**Comment by kayhayen** [comment]
Ah, that's bad, it definitely shouldn't let system references remain undetected. But I believe `otool` usage on macOS is kind of broken, which is probably why this happens. Now GitHub actions is not a Python that is proclaimed as supported, so do not expect this to be a priority, esp. not posted below an unrelated issue that will be closed soon.

**Comment by roniemartinez** [comment]
> esp. not posted below an unrelated issue that will be closed soon.

Thanks. I created a separate ticket: https://github.com/Nuitka/Nuitka/issues/1784

**Comment by kayhayen** [comment]
This is part of the stable release 1.1 that I just made.
