### ISSUE TITLE
RunTimeError with Jupyter QtConsole when showing an image with pyplot

### ISSUE THREAD

**Issue by pyt2** [Nuitka/Nuitka#1773]
matplotlib.pyplot.Imshow in jupyter qtconsole generates a RunTimeError with nuitka.
The Issue is reproduced with official python 3.7.4, 3.8.6, 3.10.5
The issue is reproduced with visual studio 2017 (14.13) and gcc (11.3.0-14.0.3-10.0.0-msvcrt-r3)
The issue is reproduced with matplotlib 3.2.2 and 3.5.3.
The bug is reproduced with PyQt5 or PySide6.
The bug is reproduced with nuitka 1.0.0 or 1.0.5
under windows 10 64bit

Jupyter QtConsole when the RunTimeError issue occurs :

Jupyter QtConsole 5.3.1
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.34.0 -- An enhanced Interactive Python. Type '?' for help.
pyplot.imshow(image, cmap='gray')
Out[1]: <matplotlib.image.AxesImage at 0x1efa9da1fc8>---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~\x64\SIMPLECASE\IPython\core\formatters.py in __call__(self, obj)

~\x64\SIMPLECASE\matplotlib\figure.py in _repr_html_(self)

RuntimeError: Must not call matplotlib.figure._repr_html_

￼

The attached file requirement.txt list the minimal list of modules required to reproduce the issue.

The bug disappears when the 6 following code lines of file figure.py of matplotlib are commented :
    def _repr_html_(self):
        # We can't use "isinstance" here, because then we'd end up importing
        # webagg unconditionally.
        if 'WebAgg' in type(self.canvas).__name__:
            from matplotlib.backends import backend_webagg
            return backend_webagg.ipython_inline_display(self)

The most simple testcase to reproduce the bug :

# -*- coding: utf-8 -*-
import sys
from qtpy import QtWidgets
from qtpy.QtWidgets import QMainWindow, QApplication
from qtconsole.rich_jupyter_widget import RichJupyterWidget
from qtconsole.inprocess import QtInProcessKernelManager

def make_jupyter_widget_with_kernel():
    """Start a kernel, connect to it, and create a RichJupyterWidget to use it
    """
    kernel_manager = QtInProcessKernelManager()
    kernel_manager.start_kernel(show_banner=False)
    kernel_manager.kernel.gui = 'qt'
    kernel_manager.kernel.shell.enable_matplotlib(gui='inline')
    kernel_client = kernel_manager.client()
    kernel_client.start_channels()
    jupyter_widget = RichJupyterWidget()
    jupyter_widget.kernel_manager = kernel_manager
    jupyter_widget.kernel_client = kernel_client
    return jupyter_widget

app = QApplication(sys.argv)
win = QtWidgets.QMainWindow()
win.resize(800,800)
console = make_jupyter_widget_with_kernel()
win.setCentralWidget(console)
win.show()
win.setWindowTitle('console ipython')
console.kernel_manager.kernel.shell.ex("import numpy as np")
console.kernel_manager.kernel.shell.ex("import matplotlib.pyplot as pyplot")
console.kernel_manager.kernel.shell.ex("image=np.arange(500*500).reshape((500, 500)).astype(np.uint32)")
console.kernel_manager.kernel.shell.ex("pyplot.imshow(image, cmap='gray')")
sys.exit(app.exec_())

Command line for compilation under windows :
python.exe -m nuitka --mingw64 ^
--force-dll-dependency-cache-update --standalone --output-dir=x64\SIMPLECASE --show-progress --enable-console ^
--enable-plugin=numpy ^
--noinclude-pytest-mode=nofollow ^
--noinclude-setuptools-mode=nofollow ^
--include-module=distutils.version ^
--include-module=zmq.utils.garbage ^
--include-module=pygments.lexers._mapping ^
--include-module=pygments.lexers.css ^
--include-module=pygments.lexers.html ^
--include-module=pygments.lexers.javascript ^
--include-module=pygments.lexers.jvm ^
--include-module=pygments.lexers.markup ^
--include-module=pygments.lexers.perl ^
--include-module=pygments.lexers.python ^
--include-module=pygments.lexers.ruby ^
--include-module=pygments.lexers.shell ^
--include-package=pygments.styles ^
--include-package=pygments.formatters ^
--include-package-data=jedi ^
--include-package-data=parso ^
--noinclude-IPython-mode=allow ^
--include-qt-plugins=sensible,styles ^
--plugin-enable=pyside6 ^
--nofollow-import-to=PyQt5 ^
--nofollow-import-to=PyQt6 ^
--nofollow-import-to=PySide2 ^
simpleqtconsole.py

[requirement.txt](https://github.com/Nuitka/Nuitka/files/9454397/requirement.txt)

**Comment by kayhayen** [comment]
The config for that is 
```
- module-name: 'matplotlib.figure'
  anti-bloat:
    - description: 'remove IPython reference'
      change_function:
        '_repr_html_': 'un-callable'
      when: 'not use_ipython'
```

and you use that `allow` mode. This might have been not yet conditional at the time, I recall adding some of these at some point. You do not list what version you used, which ought to make this report valid, but I believe it was true at the time.
