### ISSUE TITLE
ModuleNotFoundError: No module named 'math' (Nuitka '1.0.6' on Python '3.10')

### ISSUE THREAD

**Issue by kpopovic** [Nuitka/Nuitka#1776]
Hello,

from Nuitka [(User Manual)](https://nuitka.net/doc/user-manual.html) I have used a sample just to give it a try.
The problem is that I get an error ModuleNotFoundError: No module named 'math'. 
I don't know why Nuitka has issues with builtin random or math modules.

`nuitka --standalone hello.py --run`

(venv) [root@cent01 ldif-mixer]# python -m nuitka --standalone hello.py --run
Nuitka-Options:INFO: Used command line options: --standalone hello.py --run
Nuitka-Options:INFO: Detected static libpython to exist, consider '--static-libpython=yes' for better performance, but errors may happen.
Nuitka:INFO: Starting Python compilation with Nuitka '1.0.6' on Python '3.10' commercial grade 'not installed'.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 13 files (no progress information available).
Nuitka-Scons:WARNING: You are not using ccache.
Nuitka:INFO: Keeping build directory 'hello.build'.
Nuitka:INFO: Successfully created 'hello.dist/hello'.
Nuitka:INFO: Launching 'hello.dist/hello'
Traceback (most recent call last):
  File "/usr/local/netzwert/ldif-mixer/hello.dist/hello.py", line 11, in <module>
  File "/usr/local/netzwert/ldif-mixer/hello.dist/random.py", line 49, in <module>
ModuleNotFoundError: No module named 'math'

**hello.py**

```
import random

def talk(message):
    return "Talk " + message

def main():
    print(talk("Hello World"))

if __name__ == "__main__":
    main()

```

Best Regards,
Kresimir

**Comment by kayhayen** [comment]
Congratulations on reading the user manual, it would be have been sweet if you read the issue template and provided the output of `nuitka --version` as well.

**Comment by kpopovic** [comment]
> nuitka --version

python -m nuitka --version
1.0.6
Commercial: None
Python: 3.10.5 (main, Sep  5 2022, 15:45:28) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
Flavor: Unknown
Executable: /usr/local/netzwert/Python-3.10.5/venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Centos (based on Fedora) 8

_Note: python 3.10.5 is compiled from source without errors._

**Comment by kayhayen** [comment]
I think I also need the output with `--show-scons` to see what code path is taken.

**Comment by kpopovic** [comment]
> I think I also need the output with `--show-scons` to see what code path is taken.

I was playing with Nuitka arguments for several hours and managed it to work (on other py sample file, different than hello.py):

_note: as third-party dependency I use bonsai [(Bonsai LDAP)](https://pypi.org/project/bonsai/)_

requirements.txt
```
bonsai==1.5.0
Nuitka==1.0.6
ordered-set==4.1.0
zstandard==0.18.0
```

`python -m nuitka --standalone --show-modules --show-modules-output=ldif-mixer.trace --include-module=math,bonsai._bonsai,select,_contextvars --follow-stdlib --show-scons ldif-mixer.py --run`

The main question: why at least `math` module is not supported out-of-box ?

-show-modules-output: [ldif-mixer.zip](https://github.com/Nuitka/Nuitka/files/9495901/ldif-mixer.zip)

**Comment by kayhayen** [comment]
The --follow-stdlib option is not a good idea to use, but also not what you gave initially. The scons output, I didn't find it in the log provided, which indeed is minimal. Lets stick to hello world for now and find it there.

**Comment by kayhayen** [comment]
That is very helpful. I believe your `libpython3.10` might be miscompiled. At leaast I am using `--enable-shared` or older systems, albeit all Debian, and have it working. It can be avoided by using `--static-libpython=yes` in which case it may still not work, and of course will even be better for performance.

**Comment by kayhayen** [comment]
Closing for lack of feedback
