### ISSUE TITLE
nuitka not finding a C compiler

### ISSUE THREAD

**Issue by rra88** [Nuitka/Nuitka#1778]
**Nuitka version, full Python version, flavor, OS, etc.:** 

- 1.0.6
- Commercial: None
- Python: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:30:19) [MSC v.1929 64 bit (AMD64)]
- Flavor: Anaconda Python
- Executable: C:\Users\erjan\Anaconda3\envs\recoder_project_environment\python.exe
- OS: Windows
- Arch: x86_64
- WindowsRelease: 10

**How did you install Nuitka and Python**
Python through Anaconda, nuitka through pip (I believe I did not get the latest version using conda)

**Did you use pip, anaconda, deb, rpm, from source, git clone, then install into
  a virtualenv or not, this is very important usually and one thing, the above
  command does not tell us (yet).**
I ran nuitka from the developer prompt of VS Code, in an environment created for the specific python project I wanted to create an executable for.

**Many times when you get an error from Nuitka, your setup may be special**
I'm not sure whether the setup is special. I can run my app successfully from VS code.

**Provide in your issue the Nuitka options used**
python.exe -O -m nuitka --plugin-enable=pylint-warnings --enable-plugin=numpy --enable-plugin=pyside6 --enable-plugin=tk-inter --windows-icon-from-ico=pathToMyIcon.png --onefile myPythonFile.py 

**Description**
After running the above command, nuitka displayed the error message 
> FATAL: Error, the Windows SDK must be installed in Visual Studio.

I have Visual Studio 17, 19 and 22 installed. Using Visual Studio Installer I can see that for the VS 2017 installation, C++ for Desktop Development is included, with Windows SDK version 10.0.16299 and VC++ 2017 v.141. The VS 2022 installation also has the C++ for Desktop Development included, with Windows SDK 10.0.19041.0 and MSVC v.143.

Running `cl` from the terminal in VS Code (on the same environment as above: C:\Users\erjan\Anaconda3\envs\recoder_project_environment) the following information is printed: 
> Microsoft (R) C/C++ Optimizing Compiler Version 19.13.26131.1 for x64

Following a suggestion (not to my issue) to use a different compiler (clang instead of cl - https://stackoverflow.com/questions/71396733/nuitka-compilation-error-when-building-on-windows) the error message was different: 
> FATAL: Visual Studio has no Clang component found at 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\Llvm\x64\bin'

Am I really missing an acceptable compiler, or is nuitka just not finding it?

**Comment by kayhayen** [comment]
The developer prompt should only be used by people who know what they are doing. For mere mortals, a standard prompt is recommened. Then Nuitka (Scons) will find the right one to use for you.

**Comment by rra88** [comment]
Thanks for the quick feedback. Unfortunately running the command from Command Prompt led to the same error.
The last three messages in print-out the prompt being:

> Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl 14.3).
FATAL: Error, the Windows SDK must be installed in Visual Studio.

**Comment by kayhayen** [comment]
Ok, I know the docs suck at this, largely because it's an ever-changing topic on MS side. Would you mind sharing a screenshot of the installed packages of your 2022 installation, so I can compare it.

**Comment by rra88** [comment]
Microsoft Visual Studio Professional 2022
Version 17.1.6
VisualStudio.17.Release/17.1.6+32421.90
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

Visual C++ 2022   00483-10803-44387-AA118
Microsoft Visual C++ 2022

ASP.NET and Web Tools 2019   17.1.363.30963
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   17.1.363.30963
Azure App Service Tools v3.0.0

C# Tools   4.1.0-5.22165.10+e555772db77ca828b02b4bd547c318387f11d01f
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.21344.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   6.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Python - Django support   17.0.21344.1
Provides templates and integration for the Django web framework.

Python - Profiling support   17.0.21344.1
Profiling support for Python projects.

Python with Pylance   17.0.21344.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   17.0.1229.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.1.0-5.22165.10+e555772db77ca828b02b4bd547c318387f11d01f
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.21610.4+07b5673e4f2fa7630e78abe37f16b372353a7242
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

**Comment by kayhayen** [comment]
In that list, there is no Windows SDK? I also wonder who you got that list in ascii form, is there a command to query it? I think I once saw a command to install components, there must be something to automatically suggest installaling missing components like this.

**Comment by kayhayen** [comment]
Like this: https://docs.microsoft.com/de-de/visualstudio/install/command-line-parameter-examples?view=vs-2022

**Comment by kayhayen** [comment]
I wonder if this also works for the community edition, that many people, including me, can use.

**Comment by kayhayen** [comment]
Dreaming of a world, where I can enhance the error message to say execute this, and it will work.

**Comment by rra88** [comment]
> In that list, there is no Windows SDK? I also wonder who you got that list in ascii form, is there a command to query it? I think I once saw a command to install components, there must be something to automatically suggest installaling missing components like this.

I simply opened VS22, then used Help -> About Microsoft Visual Studio -> Copy Info. Below is a screenshot from the Visual Studio Installer, on the right hand side it gives me the impression Windows SDK should be installed.
![VS22_installationDetails](https://user-images.githubusercontent.com/101706204/189284460-69d1f838-31fa-4a7d-9208-9c3e5a51dbfe.PNG)

**Comment by kayhayen** [comment]
You only have more workloads, on my laptop here, I *only* have Desktop, and Clang as an individual component installed (the later should not be necessary at all).

Sorry for my screenshot being German, but I think it shows that you only have more stuff.

![VS-Install](https://user-images.githubusercontent.com/4226920/189287440-a2378c45-466d-41b2-b7f6-c49af00fd66a.PNG)

**Comment by kayhayen** [comment]
I am thinking, Desktop development with C++ should be sufficient for sure. I can try out if adding Python or .NET is what breaks things for me too.

**Comment by rra88** [comment]
It'd be great if you could check that!

**Comment by kayhayen** [comment]
I just tried developer prompts, they work for me as it currently is. I tried adding more components, and it worked. If you can, you might want to debug the code that leads to the error message, maybe Scons somehow can be fooled. I am not sure you are the only one, but I don't know what to do without being able to reproduce this.

**Comment by rra88** [comment]
Alright, thanks for trying that. I'll play around a bit and report back if I find a solution.

**Comment by rra88** [comment]
I had several Visual Studio installations: 2017, 2019 and 2022. Windows SDK was installed on the 2022 version, but not on the 2017 version (not sure about the 2019 one). It seems Nuitka was looking for a C compiler in the 2017 installation, and giving up when it could not be found. After upgrading the 2017 installation with Visual Studio Installer -- a change that added Windows SDK -- my Nuitka command worked. Since then I have uninstalled 2017 and 2019, and it still works (using the Windows SDK from the 2022 installation). I leave the issue labeling and closing to you guys as I'm not sure whether this should be marked invalid or not.

**Comment by kayhayen** [comment]
Nothing really actionable here. I recently improved developer prompt support again, this should be good in 1.5 now
