### ISSUE TITLE
QtGui import DLL load failed

### ISSUE THREAD

**Issue by amrosallam2011** [Nuitka/Nuitka#178]
from PyQt5 import QtGui
Traceback (most recent call last):
  File "<pyshell#76>", line 1, in <module>
    from PyQt5 import QtGui
ImportError: DLL load failed: The specified procedure could not be found.

can any one help me plz to fix this error

**Comment by kayhayen** [comment]
Sometimes I really wonder why I have an issue template. Just so you can erase it?
