### ISSUE TITLE
Library not loaded: '/Users/runner/hostedtoolcache/Python/3.10.6/x64/lib/libpython3.10.dylib'

### ISSUE THREAD

**Issue by roniemartinez** [Nuitka/Nuitka#1784]
Thanks for your reply @kayhayen 

For me, error only happens if I run the app built from Github Actions (`macos-latest`) in my local machine. I downloaded this build using `actions/upload-artifact@v3`.

I've tried some configuration and was able to include `libpython3.10.dylib` in the resulting bundle. However, I get the same error when running the built app.

You can find my builds here:
- PR: https://github.com/roniemartinez/nuitka-build/pull/1
- Built artifacts/installer: https://github.com/roniemartinez/nuitka-build/actions/runs/3031630183

Error (same as before):
```
/Applications/myapp.app/Contents/MacOS/myapp ; exit;
dyld[60478]: Library not loaded: '/Users/runner/hostedtoolcache/Python/3.10.6/x64/lib/libpython3.10.dylib'
  Referenced from: '/Applications/myapp.app/Contents/MacOS/myapp'
  Reason: tried: '/Users/runner/hostedtoolcache/Python/3.10.6/x64/lib/libpython3.10.dylib' (no such file), '/usr/local/lib/libpython3.10.dylib' (no such file), '/usr/lib/libpython3.10.dylib' (no such file)
[1]    60478 abort      /Applications/myapp.app/Contents/MacOS/myapp
```

Bundle contents:
```
$ ls /Applications/myapp.app/Contents/MacOS | grep dylib
libcrypto.1.1.dylib
libgdbm.6.dylib
libgdbm_compat.4.dylib
libintl.8.dylib
liblzma.5.dylib
libpyside6.abi3.6.3.dylib
libpython3.10.dylib
libshiboken6.abi3.6.3.dylib
libssl.1.1.dylib
```

It looks like it is still linked to system's `libpython3.10.dylib` instead of the included file.

_Originally posted by @roniemartinez in https://github.com/Nuitka/Nuitka/issues/1771#issuecomment-1242945559_

**Comment by kayhayen** [comment]
As an aside, how portable are github action Python installations anyway? They might be compiled towards only macos-latest, meaning the binaries are not backportable.

**Comment by kayhayen** [comment]
Says Nuitka:

> Nuitka:INFO: Created binary that runs on macOS 10.15 (x86_64) or higher.

Not too bad, CPython does 10.9, not sure about Anaconda.

**Comment by kayhayen** [comment]
So, this has been fixed in a hotfix release, turns out CPython was broken too after my dependency scanner rewrite. The main Python DLL was not updated.
