### ISSUE TITLE
Nuitka Issue for Unix Amazon Ec2 instance

### ISSUE THREAD

**Issue by arpankhetani** [Nuitka/Nuitka#1785]
I have a client who has a Centos Redhat system. I tried to obfuscate and create a bin onefile using nuitka where my python program includes basic pandas and flask code. Unfortunately I am facing below issue - I noticed issue does not come when ubuntu is used , but  centos / amazon ec2 instances uses maximum of glibc26.

module.pandas.plotting._core.c: In function 'impl_pandas$plotting$_core$$$function__19__load_backend':
module.pandas.plotting._core.c:10738:34: warning: implicit declaration of function 'IMPORT_HARD_IMPORTLIB__METADATA'; did you mean 'IMPORT_HARD_IMPORTLIB_METADATA'? [-Wimplicit-function-declaration]
         tmp_import_name_from_1 = IMPORT_HARD_IMPORTLIB__METADATA();
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                  IMPORT_HARD_IMPORTLIB_METADATA
module.pandas.plotting._core.c:10738:32: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
         tmp_import_name_from_1 = IMPORT_HARD_IMPORTLIB__METADATA();
                                ^
Nuitka-Scons:INFO: Backend linking program with 392 modules (no progress information available).
./module.pandas.plotting._core.o: In function `impl_pandas$plotting$_core$$$function__19__load_backend':
module.pandas.plotting._core.c:(.text+0x117dd): undefined reference to `IMPORT_HARD_IMPORTLIB__METADATA'
collect2: error: ld returned 1 exit status

Can you advise its Nuitka issue or glibc issue. Unfortunately ec2 instances / centos comes with glibc26 version. Also numpy import works correctly , but it fails for Pandas / Flask version. I am making use of Python3.8

**Comment by kayhayen** [comment]
No issue template, no fun.
