### ISSUE TITLE
Azure SDK slow compilation

### ISSUE THREAD

**Issue by ilya-brykau** [Nuitka/Nuitka#1791]
Python: 3.9
Nuitka: 1.0.6
OS: Windows 10/Windows Server 2019
Problematic packages: 
azure-identity = 1.10.0
azure-mgmt-compute = 27.2.0
azure-mgmt-network = 21.0.1

What nuitka parameters are used?
--standalone 
--remove-output 
--plugin-enable=pylint-warnings
--include-package=log
--lto=no
--enable-plugin=anti-bloat
--msvc=14.1

Whats the issue?
Import of the specific azure api version causes slow compilation (UP to 2 hours and more)

Code sample:
```
from typing import Optional

from azure.core.exceptions import ResourceNotFoundError
from azure.core.polling import LROPoller
from azure.identity import DefaultAzureCredential
from azure.mgmt.network import NetworkManagementClient
from azure.mgmt.network.v2022_01_01.models import (
    AddressSpace,
    IPConfiguration,
    NetworkInterface,
    NetworkSecurityGroup,
    PublicIPAddress,
    PublicIPAddressSku,
    Subnet,
    VirtualNetwork,
    PublicIPAddressSkuName,
    IPAllocationMethod,
    IPVersion,
)


class AzureNetworkClient:
    def __init__(self, subscription_id: str):
        credential: DefaultAzureCredential = DefaultAzureCredential()
        self._client: NetworkManagementClient = NetworkManagementClient(
            credential,
            subscription_id,
            api_version='2022-01-01',
        )

    def get_virtual_network_by_name(
            self,
            resource_group: str,
            vnet_name: str,
    ) -> Optional[VirtualNetwork]:
        try:
            virtual_network: VirtualNetwork = self._client.virtual_networks.get(
                resource_group_name=resource_group,
                virtual_network_name=vnet_name,
            )
            return virtual_network
        except ResourceNotFoundError:
            return None

    def get_subnet_by_name(
            self,
            resource_group: str,
            vnet_name: str,
            subnet_name: str
    ) -> Optional[Subnet]:
        try:
            subnet: Subnet = self._client.subnets.get(
                resource_group_name=resource_group,
                virtual_network_name=vnet_name,
                subnet_name=subnet_name,
            )
            return subnet
        except ResourceNotFoundError:
            return None

    def get_public_ip_by_name(
            self,
            resource_group: str,
            public_ip_name: str,
    ) -> Optional[PublicIPAddress]:
        try:
            public_ip: PublicIPAddress = self._client.public_ip_addresses.get(
                resource_group_name=resource_group,
                public_ip_address_name=public_ip_name,
            )
            return public_ip
        except ResourceNotFoundError:
            return None

    def get_network_interface_by_name(
            self,
            resource_group: str,
            network_interface_name: str,
    ) -> Optional[NetworkInterface]:
        try:
            network_interface: NetworkInterface = self._client.network_interfaces.get(
                resource_group_name=resource_group,
                network_interface_name=network_interface_name,
            )
            return network_interface
        except ResourceNotFoundError:
            return None

    def create_virtual_network(
            self,
            resource_group: str,
            location: str,
            vnet_name: str,
    ) -> VirtualNetwork:
        vnet: Optional[VirtualNetwork] = self.get_virtual_network_by_name(
            resource_group=resource_group,
            vnet_name=vnet_name
        )
        if vnet:
            return vnet

        poller: LROPoller[VirtualNetwork] = self._client.virtual_networks.begin_create_or_update(
            resource_group,
            vnet_name,
            VirtualNetwork(
                location=location,
                address_space=AddressSpace(
                    address_prefixes=['10.0.0.0/16'],
                ),
            ),
        )

        return poller.result()

    def create_subnet(
            self,
            resource_group: str,
            vnet_name: str,
            subnet_name: str,
    ) -> Subnet:
        subnet: Optional[Subnet] = self.get_subnet_by_name(
            resource_group=resource_group,
            vnet_name=vnet_name,
            subnet_name=subnet_name,
        )
        if subnet:
            return subnet

        poller: LROPoller[Subnet] = self._client.subnets.begin_create_or_update(
            resource_group,
            vnet_name,
            subnet_name,
            Subnet(
                address_prefix='10.0.0.0/24',
            ),
        )
        return poller.result()

    def create_public_ip(
            self,
            resource_group: str,
            location: str,
            ip_name: str,
    ) -> PublicIPAddress:
        poller: LROPoller[PublicIPAddress] = self._client.public_ip_addresses.begin_create_or_update(
            resource_group,
            ip_name,
            PublicIPAddress(
                location=location,
                sku=PublicIPAddressSku(
                    name=PublicIPAddressSkuName.STANDARD,
                ),
                public_ip_allocation_method=IPAllocationMethod.STATIC,
                public_ip_address_version=IPVersion.I_PV4,
            ),
        )

        return poller.result()

    def create_network_security_group(
            self,
            resource_group: str,
            location: str,
            nsg_name: str,
    ) -> NetworkSecurityGroup:
        poller: LROPoller[NetworkSecurityGroup] = self._client.network_security_groups.begin_create_or_update(
            resource_group,
            nsg_name,
            NetworkSecurityGroup(
                location=location,
            )
        )

        return poller.result()

    def create_network_interface(
            self,
            resource_group: str,
            location: str,
            ip_config_name: str,
            network_interface_name: str,
            subnet_id: str,
            public_ip_address_id: str,
            nsg_id: str,
    ) -> NetworkInterface:
        poller: LROPoller[NetworkInterface] = self._client.network_interfaces.begin_create_or_update(
            resource_group,
            network_interface_name,
            NetworkInterface(
                location=location,
                ip_configurations=[
                    IPConfiguration(
                        name=ip_config_name,
                        subnet=Subnet(
                            id=subnet_id,
                        ),
                        public_ip_address=PublicIPAddress(
                            id=public_ip_address_id,
                        ),
                    ),
                ],
                network_security_group=NetworkSecurityGroup(
                    id=nsg_id,
                )
            ),
        )

        return poller.result()
```

Why the issue might appear? 
Azure api contains cross-version operations/models and it requires additional imports.

How i tried to solve the issue?
Remove unnecessary imports
--nofollow-import-to
Enable/Disable lto
Enable anti-bloat

**Comment by kayhayen** [comment]
It seems e.g. azure.mgmt.network.v2019_07_01.operations._operations is almost 70k lines of code, pretty hefty one. I might look into it if there is commercial backing: https://nuitka.net/doc/commercial.html

Otherwise I am afraid, this won't have the priority at this time.

**Comment by kayhayen** [comment]
I have added code to not compile the `azure.mgmt.network` packages, but to include them as bytecode, attempting to compile this killed my very powerful CI machine, so no chance this is for lack of resources.

Not sure if this will make it acceptable. Caching should be allowed of course to take benefit, a first compilation will still be slow on the Python level, but appeared doable. But I cannot run this due to risk of interfering with 1.1 release and early hotfixes now.

**Comment by ilya-brykau** [comment]
Hi Kayhayen, Thanks for the response. Is it possible that mgmt.compute has the same issue as network package?
Here is a code sample:
`import math
from typing import Iterable, List, Optional, Tuple

from azure.core.exceptions import ResourceNotFoundError
from azure.core.polling import LROPoller
from azure.identity import DefaultAzureCredential
from azure.mgmt.compute import ComputeManagementClient
from azure.mgmt.compute.v2017_12_01.models import OperationStatusResponse
from azure.mgmt.compute.v2021_04_01.models import (
    CreationData,
    DataDisk,
    Disk,
    DiskCreateOption,
    DiskCreateOptionTypes,
    DiskSku,
    DiskStorageAccountTypes,
    HardwareProfile,
    HyperVGeneration,
    ManagedDiskParameters,
    NetworkInterfaceReference,
    NetworkProfile,
    OperatingSystemTypes,
    OSDisk,
    StorageProfile,
    VirtualMachine,
    VirtualMachineSizeTypes, GrantAccessData, AccessLevel, AccessUri,
)

from dtjson import DiskItem, DiskConfiguration, VmComputeMetadata


class AzureComputeClient:
    def __init__(self, subscription_id: str):
        credential: DefaultAzureCredential = DefaultAzureCredential()
        self._client: ComputeManagementClient = ComputeManagementClient(
            credential,
            subscription_id,
            api_version='2021-04-01',
        )

    def get_vm_by_name(
            self,
            resource_group: str,
            vm_name: str,
    ) -> VirtualMachine:
        azure_vm: VirtualMachine = self._client.virtual_machines.get(
            resource_group_name=resource_group,
            vm_name=vm_name,
        )
        return azure_vm

    def get_managed_disk_by_name(
            self,
            resource_group: str,
            disk_name: str,
    ) -> Optional[Disk]:
        try:
            azure_disk: Disk = self._client.disks.get(
                resource_group_name=resource_group,
                disk_name=disk_name,
            )
            return azure_disk
        except ResourceNotFoundError:
            return None

    def list_managed_disks_by_resource_group(
            self,
            resource_group: str,
            prefix: Optional[str] = None,
    ) -> List[Disk]:
        azure_disks: Iterable[Disk] = self._client.disks.list_by_resource_group(
            resource_group_name=resource_group,
        )
        if not prefix:
            return list(azure_disks)

        return [disk for disk in azure_disks if disk.name.startswith(prefix)]  # type: ignore

    def create_managed_disk(
            self,
            resource_group: str,
            disk_name: str,
            location: str,
            zones: Optional[List[str]],
            config: DiskItem,
            disk_type: DiskStorageAccountTypes,
    ) -> Disk:
        poller: LROPoller[Disk] = self._client.disks.begin_create_or_update(
            resource_group,
            disk_name,
            Disk(
                location=location,
                zones=zones,
                disk_size_gb=math.ceil(config.disk_info.disk_size / (1024 ** 3)),
                os_type=OperatingSystemTypes.WINDOWS,
                hyper_v_generation=HyperVGeneration.V2,
                creation_data=CreationData(
                    create_option=DiskCreateOption.EMPTY,
                ),
                sku=DiskSku(
                    name=disk_type,
                ),
            ),
        )

        return poller.result()

    def copy_managed_disk(
            self,
            resource_group: str,
            disk_name: str,
            location: str,
            source_uri: AccessUri,
    ) -> Disk:
        poller: LROPoller[Disk] = self._client.disks.begin_create_or_update(
            resource_group,
            disk_name,
            Disk(
                location=location,
                creation_data=CreationData(
                    create_option=DiskCreateOption.IMPORT_ENUM,
                    source_uri=source_uri.access_sas,
                ),
            ),
        )

        return poller.result()

    def grant_disk_access(
            self,
            resource_group: str,
            disk_name: str,
    ) -> AccessUri:
        poller: LROPoller[AccessUri] = self._client.disks.begin_grant_access(
            resource_group,
            disk_name,
            GrantAccessData(
                access=AccessLevel.READ,
                duration_in_seconds=3600,
            )
        )

        return poller.result()

    def delete_managed_disk(
            self,
            resource_group: str,
            disk_name: str,
    ) -> None:
        poller: LROPoller[OperationStatusResponse] = self._client.disks.begin_delete(
            resource_group,
            disk_name,
        )

        poller.result()

    def move_managed_disk(
            self,
            source_resource_group: str,
            source_disk_name: str,
            source_disk_id: str,
            target_resource_group: str,
            target_disk_name: str,
            target_location: str,
    ) -> Disk:
        source_uri = self.grant_disk_access(
            source_resource_group,
            source_disk_name
        )
        copied_disk: Disk = self.copy_managed_disk(
            resource_group=target_resource_group,
            disk_name=target_disk_name,
            location=target_location,
            source_uri=source_uri,
        )
        self.delete_managed_disk(
            resource_group=source_resource_group,
            disk_name=source_disk_name,
        )

        return copied_disk

    @staticmethod
    def get_data_disks(
            created_disks: List[Disk],
    ) -> List[DataDisk]:
        lun_start = 1

        return [
            DataDisk(
                lun=int(lun_start := lun_start + 1),
                create_option=DiskCreateOptionTypes.ATTACH,
                name=managed_disk.name,
                managed_disk=ManagedDiskParameters(
                    id=managed_disk.id
                )
            ) for managed_disk in created_disks
        ]

    def create_and_attach_managed_disks_to_vm(
            self,
            resource_group: str,
            vm_name: str,
            disks_config: DiskConfiguration,
            name_prefix: str,
            os_disk_type: DiskStorageAccountTypes,
    ) -> Tuple[List[DataDisk], List[Disk]]:
        azure_vm: VirtualMachine = self.get_vm_by_name(resource_group, vm_name)
        location: str = azure_vm.location
        zones: Optional[List[str]] = azure_vm.zones
        os_disk_index: int = 0
        created_disks: List[Disk] = [
            self.create_managed_disk(
                resource_group=resource_group,
                disk_name=name_prefix + str(index),
                location=location,
                zones=zones,
                config=config,
                disk_type=os_disk_type if index == os_disk_index else DiskStorageAccountTypes.STANDARD_LRS,
            )
            for index, config in enumerate(disks_config.disk_array, os_disk_index)
        ]

        disks_to_attach: List[DataDisk] = self.get_data_disks(created_disks)

        azure_vm.storage_profile.data_disks.extend(disks_to_attach)  # type: ignore

        async_update: LROPoller[VirtualMachine] = self._client.virtual_machines.begin_create_or_update(
            resource_group,
            azure_vm.name,
            azure_vm,
        )
        async_update.wait()

        return disks_to_attach, created_disks

    def unattach_managed_disks_from_vm(
            self,
            resource_group: str,
            vm_name: str,
            disk_lun_ids: Optional[List[int]],
    ) -> None:
        if not disk_lun_ids:
            return

        azure_vm: VirtualMachine = self.get_vm_by_name(resource_group, vm_name)
        azure_vm.storage_profile.data_disks = [  # type: ignore
            data_disk for data_disk in azure_vm.storage_profile.data_disks  # type: ignore
            if data_disk.lun not in disk_lun_ids
        ]

        async_update: LROPoller[VirtualMachine] = self._client.virtual_machines.begin_create_or_update(
            resource_group,
            azure_vm.name,
            azure_vm,
        )
        async_update.wait()

    def replace_disks_if_different_region_or_rg(
            self,
            resource_group: str,
            location: str,
            os_disk: Disk,
            data_disks: List[Disk],
            agent_metadata: VmComputeMetadata,
    ) -> Tuple[Disk, List[Disk]]:
        is_same_region_and_rg: bool = bool(
            resource_group == agent_metadata.resource_group and
            location == agent_metadata.location
        )
        if is_same_region_and_rg:
            return os_disk, data_disks

        os_disk = self.move_managed_disk(
            source_resource_group=agent_metadata.resource_group,
            source_disk_name=os_disk.name,  # type: ignore
            source_disk_id=os_disk.id,  # type: ignore
            target_resource_group=resource_group,
            target_disk_name=os_disk.name,  # type: ignore
            target_location=location,
        )
        data_disks = [
            self.move_managed_disk(
                source_resource_group=agent_metadata.resource_group,
                source_disk_name=disk.name,  # type: ignore
                source_disk_id=disk.id,  # type: ignore
                target_resource_group=resource_group,
                target_disk_name=disk.name,  # type: ignore
                target_location=location,
            ) for disk in data_disks
        ]

        return os_disk, data_disks

    def create_vm(
            self,
            resource_group: str,
            location: str,
            vm_name: str,
            network_interface_id: str,
            os_disk: Disk,
            data_disks: List[Disk],
            agent_metadata: VmComputeMetadata,
            vm_size: VirtualMachineSizeTypes,
    ) -> VirtualMachine:
        os_disk, data_disks = self.replace_disks_if_different_region_or_rg(
            resource_group=resource_group,
            location=location,
            os_disk=os_disk,
            data_disks=data_disks,
            agent_metadata=agent_metadata,
        )
        data_disk_ids: List[str] = [
            disk.id for disk in data_disks  # type: ignore
        ]

        lun_start: int = 0
        poller: LROPoller[VirtualMachine] = self._client.virtual_machines.begin_create_or_update(
            resource_group,
            vm_name,
            VirtualMachine(
                location=location,
                hardware_profile=HardwareProfile(
                    vm_size=vm_size,
                ),
                network_profile=NetworkProfile(
                    network_interfaces=[
                        NetworkInterfaceReference(
                            id=network_interface_id,
                        ),
                    ],
                ),
                storage_profile=StorageProfile(
                    os_disk=OSDisk(
                        os_type=OperatingSystemTypes.WINDOWS,
                        create_option=DiskCreateOptionTypes.ATTACH,
                        managed_disk=ManagedDiskParameters(
                            id=os_disk.id,
                        )
                    ),
                    data_disks=[
                        DataDisk(
                            lun=int(lun_start := lun_start + 1),
                            create_option=DiskCreateOptionTypes.ATTACH,
                            managed_disk=ManagedDiskParameters(
                                id=disk_id
                            )
                        ) for disk_id in data_disk_ids
                    ],
                ),
            ),
        )

        return poller.result()
`

**Comment by kayhayen** [comment]
From the looks of it very likely, indeed.

**Comment by ilya-brykau** [comment]
> From the looks of it very likely, indeed.

So should we expect excluding azure packages from compilation? Or adding a parameter to add packages as a bytecode?

**Comment by kayhayen** [comment]
There is currently no such option, this is hardcoded in Nuitka. We are planning to add this to the package configuration Yaml file, but that has not happened yet.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working. 

If you retry and report, I can easily add more stuff, we can work that way.

**Comment by ilya-brykau** [comment]
> Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html
> 
> Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.
> 
> If you retry and report, I can easily add more stuff, we can work that way.

Thanks for the improvement. kayhayen. It gave a performance boost during compilation. But optimization step is still slow. Is it possible to make it faster somehow?

**Comment by kayhayen** [comment]
The Python compilation of these modules should only happen once, and then the analysis result is cached, and bytecode directly created.

**Comment by ilya-brykau** [comment]
> The Python compilation of these modules should only happen once, and then the analysis result is cached, and bytecode directly created.

is this results cached using ccache?

**Comment by kayhayen** [comment]
I believe the changes are in current stable through hotfixes, but not entirely sure, but due to the nature of the bug, let me close this, nothing happening there anymore.
