### ISSUE TITLE
Windows "Company Name" parameter with Chinese characters causes "onefile linking illegal byte sequence" error

### ISSUE THREAD

**Issue by IneededAnAccountToDoStuff** [Nuitka/Nuitka#1794]
First time submitting an error, hope I'm doing this right. I've replaced certain file names with █ to remove personal info.

A while back, I was recompiling a program I had made, but Nuitka raised an error:
(I'll put the full error text later)

  Nuitka-Scons:INFO: Onefile linking program with 1 files (no progress information available).
  In file included from static_src\OnefileBootstrap.c:97:
  C:\Users\████\AppData\Local\Programs\Python\PYTHON~1\lib\SITE- 
  P~1\nuitka\build\static_src/HelpersSafeStrings.c: In function 'expandTemplatePathW':
  C:\Users\FUNSIN~1\AppData\Local\Programs\Python\PYTHON~1\lib\SITE- 
  P~1\nuitka\build\static_src/HelpersSafeStrings.c:182:71: error: converting to execution 
  character set: Illegal byte sequence
    182 |                     appendWStringSafeW(target, L"" NUITKA_COMPANY_NAME, buffer_size);
        |                                                                       ^

  scons: *** [static_src\OnefileBootstrap.o] Error 1
  FATAL: Error, onefile bootstrap binary build failed.

After a lot of trial and error, I traced down the issue to the "Company Name" Parameter.

That seems to be the only parameter that impacts the error.
The issue appears when the "Company Name" Parameter is set to a set of Chinese characters I use.

The "Company Name" Parameter means that it is onefile, and the text I use, 公司, is a joke meaning "Program".

The thing is, previous versions of Nuitka worked with this "Company Name".

The command I ran was:
    nuitka --output-dir=.\ExecutableOutputFolder --remove-output --standalone --onefile --assume-yes-for-downloads --windows-product-version=1 --windows-product-name="Placeholder" --windows-company-name="公司" --windows-file-description="Placeholder" --onefile-tempdir-spec="%TEMP%\onefile_████_test_%PID%" "D:\████\Executables\test.py"

I'm using pip to install, pip listing "Nuitka     1.0.7"

Python version is 3.10.0, CPython, Windows 8.1. The command returned:

1.0.7
Commercial: None
Python: 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\████\AppData\Local\Programs\Python\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 8.1

All the programs I've tried have worked flawlessly, unless I set the Company Name Parameter to  my custom string, then it fails.

Full output of the command:

Nuitka-Options:INFO: Used command line options: --output-dir=.\ExecutableOutputFolder --remove-output --standalone --onefile --assume-yes-for-downloads --windows-product-version=1 --windows-p
roduct-name=Placeholder --windows-company-name=公司 --windows-file-description=Placeholder --onefile-tempdir-spec=C:\Users\FUNSIN~1\AppData\Local\Temp\onefile_MC_COMP_test_%PID% D:\matthew\Ac
tive\Executables\test.py
Nuitka-Options:WARNING: Using an absolute path should be avoided unless you are targeting a very well known environment: anchor with e.g. %TEMP%, %CACHE_DIR% is recommended:
Nuitka-Options:WARNING: 'C:\Users\FUNSIN~1\AppData\Local\Temp\onefile_MC_COMP_test_%PID%'
Nuitka:WARNING: Using very slow fallback for ordered sets, please install 'ordered-set' PyPI package for best Python compile time performance.
Nuitka:INFO: Starting Python compilation with Nuitka '1.0.7' on Python '3.10' commercial grade 'not installed'.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka:INFO: Completed Python level compilation and optimization. 443/444, abc
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.5, test
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 13 files (no progress information available).
Nuitka-Scons:INFO: Compiled 27 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 13
Nuitka-Postprocessing:INFO: Creating single file from dist folder, this may take a while.-1_1.dll
Nuitka-Onefile:INFO: Running bootstrap binary compilation via Scons.
Nuitka-Onefile:WARNING: Onefile mode cannot compress without 'zstandard' module installed.
Nuitka-Scons:INFO: Onefile C compiler: gcc (gcc).
Nuitka-Scons:INFO: Onefile linking program with 1 files (no progress information available).
In file included from static_src\OnefileBootstrap.c:97:
C:\Users\FUNSIN~1\AppData\Local\Programs\Python\PYTHON~1\lib\SITE-P~1\nuitka\build\static_src/HelpersSafeStrings.c: In function 'expandTemplatePathW':
C:\Users\FUNSIN~1\AppData\Local\Programs\Python\PYTHON~1\lib\SITE-P~1\nuitka\build\static_src/HelpersSafeStrings.c:182:71: error: converting to execution character set: Illegal byte sequence
  182 |                     appendWStringSafeW(target, L"" NUITKA_COMPANY_NAME, buffer_size);
      |                                                                       ^

scons: *** [static_src\OnefileBootstrap.o] Error 1
FATAL: Error, onefile bootstrap binary build failed.

Hope this helps.

**Comment by kayhayen** [comment]
The bad thing is, onefile does not even use this value in your case. It is for onefile intended to allow usage below below `%CACHE_DIR%` or `%HOME%` and the like. The Windows supports UTF-16 for filenames in the APIs. I think it must be a bug, that assignment of `NUITKA_COMPANY_NAME` literal didn't raise an encoding error.

**Comment by kayhayen** [comment]
```
 File "C:\Users\kayha\repos\Py2C\nuitka\build\SconsUtils.py", line 523:
    f.write("#define %s %s\n" % (key, makeCLiteral(value)))
  File "C:\Python39_64\lib\encodings\cp1252.py", line 19:
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
```

So, happens for me. I guess, using the OS provided encoding for the file is wrong. The compiler will not use that encoding usually, but UTF8 instead.

**Comment by kayhayen** [comment]
Yes, forcing to UTF-8 preserves your company name properly. I believe only Windows should be affected. Thanks for reporting.

Also make sure to consider https://nuitka.net/doc/commercial.html if you are a commerical user.

**Comment by kayhayen** [comment]
This is now on develop branch and will be in 1.1 release soon.

**Comment by kayhayen** [comment]
This is part of the stable release 1.1 that I just made.
