### ISSUE TITLE
Qt Plugin does not find msvcp140.dll in site-packages\pyside6\ 

### ISSUE THREAD

**Issue by bearsh** [Nuitka/Nuitka#1795]
I want to build a standalone and/or onefile of my project.
Qt Plugin tries to find `msvcp140.dll` in `site-packages\pyside6\`  which does not exist there but it exists in `site-packages\shiboken6`.
I was able to build it before (different PySide6 version) but also in a different project with the same PySide6 version.

- Error message:
```
Nuitka-Plugins:INFO: pyside6: Including Qt plugins 'iconengines,imageformats,platforms,styles' below 'PySide6\qt-plugins'.
FATAL: Error, attempting to include file 'c:\users\martin\virtua~1\flex-p~1\lib\site-p~1\pyside6\msvcp140.dll' that does not exist.
```

- OS: Windows 10
- Nuitka version:

```
1.0.7
Commercial: None
Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\Martin\.virtualenvs\flex-prodtool-WiHASTzN\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```
- Installed by: pip
- Package versions:

```
altgraph==0.17.2
click==8.1.3
click-option-group==0.5.3
colorama==0.4.5
ecdsa==0.18.0
future==0.18.2
greenlet==1.1.3
hidapi==0.12.0.post2
intelhex==2.3.0
mypy==0.971
mypy-extensions==0.4.3
Nuitka==1.0.7
pefile==2022.5.30
psycopg2-binary==2.9.3
pyaes==1.6.1
PySide6==6.3.2
PySide6-Addons==6.3.2
PySide6-Essentials==6.3.2
python-box==6.0.2
pywin32==304
pywin32-ctypes==0.2.0
shiboken6==6.3.2
six==1.16.0
SQLAlchemy==1.4.40
tomli==2.0.1
typing_extensions==4.3.0
zstandard==0.18.0
```

**Comment by kayhayen** [comment]
This is caching bug, fixed on 1.1 already for which a release is coming very soon.

**Comment by kayhayen** [comment]
Workaround by forcing an update of the dependency cache with `--force-dll-dependency-cache-update`

**Comment by bearsh** [comment]
thanks @kayhayen for the fast response, very appreciate. the workaround worked!

**Comment by kayhayen** [comment]
This is part of the stable release 1.1 that I just made.
