### ISSUE TITLE
TypeError: descriptor 'format' for 'str' objects doesn't apply to a 'builtin_function_or_method' object

### ISSUE THREAD

**Issue by grgi** [Nuitka/Nuitka#1796]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

```
1.0.7
Commercial: None
Python: 3.10.7 (main, Sep  8 2022, 14:34:29) [GCC 12.2.0]
Flavor: Debian Python
Executable: /tmp/importlib_metadata/bin/python
OS: Linux
Arch: x86_64
Distribution: Debian sid
```

* How did you install Nuitka and Python

Via `pip` from PyPI in a dedicated `venv`. 

* The specific PyPI names and versions
```
Nuitka==1.0.7
ordered-set==4.1.0
```

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

`format_failure.py`:
```
func = "{foo}".format
print(func(foo="Foo"))
```

Running this simple file should yield just `Foo` but compiled it throws an TypeError:
```
Traceback (most recent call last):
  File "/tmp/format_failure/src/format_failure.py", line 2, in <module>
    print(func(foo="Foo"))
TypeError: descriptor 'format' for 'str' objects doesn't apply to a 'builtin_function_or_method' object
```

* Provide in your issue the Nuitka options used

`python -m nuitka format_failure.py`

* Note if this is a regression

Yes, with Nuitka < 0.9 it works without a problem, e.g. 0.8.4

**Comment by kayhayen** [comment]
There is a bug, these methods are indeed methods, but `.format` is being called as unbound method there, clearly a false optimization happening.

**Comment by kayhayen** [comment]
Ok, I found the commit that does it, was in 0.9 release, and I am going to try and rebase my fix onto it, once proven. Right now it's on factory and might trigger a new hotfix release for 1.0 just now, even with 1.1 around the corner.

**Comment by kayhayen** [comment]
Part of the 1.0.8 release, done through a rebase back to 0.9 development, so bisect is intact.
