### ISSUE TITLE
`--unstriped` option is spelled incorrectly

### ISSUE THREAD

**Issue by saltedcoffii** [Nuitka/Nuitka#1799]
Nuitka provides an option called `--unstriped` that makes nuitka not strip the binary. The correct spelling is `--unstripped`. unstriped means "something that is not striped/something that does not have stripes"

**Comment by kayhayen** [comment]
Interesting, I have this in the changelog:

```
-  There is now a ``--unstripped`` (since renamed to ``--unstriped``)
   option that just keeps the debug information in the file, but doesn't
   keep the assertions.
```

I need to check what triggered me there, to do the change. Undoing it will of course be easy.

**Comment by kayhayen** [comment]
Ok, this `unstripped` is reported by cspell as an unknown word, wrongly, which made me default to assume I had made a mistake there.

**Comment by kayhayen** [comment]
Thanks for the report, this is coming to factory soon and will be in 1.1 release. I need to keep the old option as an alias, because valgrind based test runner is using it with versions that won't have that change. I am closing this one already for lack of general relevance.

**Comment by kayhayen** [comment]
This is part of the stable release 1.1 that I just made.
