### ISSUE TITLE
 package folders and subfolders get TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by EWilsen** [Nuitka/Nuitka#1801]
nuitka --version
0.7.7
Commercial: None
Python: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
Flavor: Unknown
Executable: D:\software\python\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

Hi, i want to package all my .py files and folders, folders and subfolders, my directory structure like :

│  setup.py
├─dep
│  │  data.py
│  ├─test_print
│  │  │  print_test.py
├─model
│  │  model.py
│  │ 
│  ├─first
│  │  │  first.py
│  │  │  
│  │  ├─sec
│  │  │  │  sec.py

i use command like:
`nuitka --standalone --show-memory --show-progress --nofollow-imports --follow-import-to=dep,model --output-dir=out steup.py`

but when  i run setup.exe i  get error:
![image](https://user-images.githubusercontent.com/30451190/191159649-5d7a4fd5-448b-45e0-89e1-3f3ceb3cdf0b.png)

what can i do, thx~

**Comment by EWilsen** [comment]
i try to upgrade my nuitka to 1.0.7, packaging time from 2min increase to 30min, problem still not solved

**Comment by EWilsen** [comment]
fixed, subfolder need an empty __init__.py file.

**Comment by kayhayen** [comment]
This is just garbage combination: `--standalone --nofollow-imports`, whatever you are doing there, you are on  your own.

**Comment by EWilsen** [comment]
> This is just garbage combination: `--standalone --nofollow-imports`, whatever you are doing there, you are on your own.

In my case, i just need to encrypt my code，the code has many dependencies of imports , 
The fastest package plan is to use this combination `--standalone --nofollow-imports`  and move original imports .py to dist folders，why is it garbage ?

**Comment by kayhayen** [comment]
Because you do not compile your code, but ship Python code, there is no sense in calling that encryption.

**Comment by EWilsen** [comment]
i know what you mean，but thanks a lot

**Comment by lchunleo** [comment]
> fixed, subfolder need an empty **init**.py file.

hi, i face the same error when i performed my execution of the compiled program in linux. Can i check does it meant all the subfolders need to have empty init.py file? is there a way of avoiding this as i have many subfolders and their nested folders?
