### ISSUE TITLE
TypeError: sequence item 0: expected str instance, NoneType found

### ISSUE THREAD

**Issue by wangzhuanxing123** [Nuitka/Nuitka#1802]
When I run the exe generated by Nuitka, this error occurs. No solution can be found online. Is this a bug?
lib_dir = os.path.sep.join([site.USER_SITE, 'paddle', 'libs'])
TypeError: sequence item 0: expected str instance, NoneType found
![111](https://user-images.githubusercontent.com/32756085/191398351-dd8c2af2-fd2e-4e62-bdec-994b4a74fe8a.jpg)

**Comment by kayhayen** [comment]
No issue template no fun.
