### ISSUE TITLE
Question: Compiled file detected as Trojan:Win32/Sabsik.TE.A!ml  by Windows Defender

### ISSUE THREAD

**Issue by ANTONIOPSD** [Nuitka/Nuitka#1804]
It started being detected today.

I used the next modules:

import os
from pathlib import Path 
from PIL import Image
import sys
import msvcrt as m
import time

The script is used to resize all image files inside of a specific folder.

This is the command I use to compile the script:

nuitka --onefile --standalone Resize.py

I installed zstandard for compression as indicated in the Nuitka logs.

Of course this is a false positive because I created the script, and I compiled it a month ago, but I guess some poeple with have problems with it in a commercial enviroment.

**Comment by MultiDragon** [comment]
Onefile has issues on certain machines. I think nuitka-commercial is able to resolve some of the issues with av software

**Comment by kayhayen** [comment]
We have customers deploying to thousands of machines with no AV issues using this https://nuitka.net/doc/commercial.html but it's easy to make mistakes, you will need the information contained there to do it right and naturally I am not supporting the free Nuitka on this topic.
