### ISSUE TITLE
"comctl32.dll that does not exist" on Windows11  22H2 (22621.598)

### ISSUE THREAD

**Issue by funchan24** [Nuitka/Nuitka#1808]
These days, I upgraded my system to Windows11  22H2 (22621.598), All my nuitka packagers failed, They worked well on the previous system.

environment:
system: Windows11  22H2 (22621.598) 64bit
python: 3.7.6 32bit
nuitka: 1.0.7
package-option: nuitka --standalone --output-dir=output\ShareFile --remove-output --windows-disable-console --windows-icon-from-ico=res\main_256.ico --plugin-enable=tk-inter core\main.py

error message:
`FATAL: Error, attempting to include file 'c:\windows\winsxs\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22610.1_none_6df091a6808ed515\comctl32.dll' that does not exist.`

**Comment by kayhayen** [comment]
This is fixed on develop already, which will soon be release as 1.1 and has been reported elsewhere too.
