### ISSUE TITLE
Issue using "pint" library with nuitka - possible issue with __new__ lookups

### ISSUE THREAD

**Issue by DerekK88** [Nuitka/Nuitka#1810]
Hi nuitka developers!

I just started using `nuitka` and I'm reallly excited to use this tool to compile and distribute a project of mine I've been working on.  Has anyone had issues using nuitka (1.0.7) with the `pint` python package for units?  I have tried on both a Mac and Windows11 OS, but am running into the following error message on both OS cases, at runtime, after a successful compilation:
```
Traceback (most recent call last):
  File "C:\Users\derek\Documents\tests\nuitka\test.py", line 5, in <module>
    i = ureg.Quantity(np.random.rand(1000), "A")
  File "C:\Users\derek\miniconda3\envs\analysis\lib\site-packages\pint\quantity.py", line 272, in __new__
    inst = SharedRegistryObject().__new__(cls)
  File "C:\Users\derek\miniconda3\envs\analysis\lib\site-packages\pint\util.py", line 815, in __new__
    inst = object.__new__(cls)
TypeError: object.__new__(X): X is not a type object (SharedRegistryObject)
```

The offending line in pint seems to be [here](https://github.com/hgrecco/pint/blob/208d36a5bb051465296dad846296bb19628e2307/pint/util.py#L815)

Here is a simple minimum working example (MWE), `test.py` that should reproduce the issue, if numpy and pint are installed (`pip install pint`):

``` python
import pint
import numpy as np
ureg = pint.UnitRegistry()

i = ureg.Quantity(np.random.rand(1000), "A")
r = ureg.Quantity(np.random.rand(1000), "ohm")
print((i*r).to("mV"))
input("<pause, press enter to continue>")
```

Thanks in advance for any help! :)

**Comment by kayhayen** [comment]
Thanks, I have a feeling, this must be somehow about numpy objects being different. When I tried similar code, it outright refused to make `.__new__` being used as a callable.

**Comment by kayhayen** [comment]
I reproduced this, but so far I only added missing data files, and did some anti-bloat work against `dask` usage, to make the compilation way more scalable. I am not finished with this, as I discovered a missing optimization that would avoid having to remove dask with anti-bloat engine, which I want to do first.

**Comment by kayhayen** [comment]
Said data files and dependencies are on develop, but potentially incomplete, this is delayed to 1.3 release likely.

**Comment by kayhayen** [comment]
The underlying error, `TypeError: object.__new__(X): X is not a type object (SharedRegistryObject)` also has not been solved yet.

**Comment by kayhayen** [comment]
The parts that were done are on develop, but the error persists, so the issue remains open, we might attempt to include it in a hotfix, but from what I remember, I was not able to figure out, what exactly was going wrong there.

**Comment by kayhayen** [comment]
I did not make it for 1.4 release, but I still plan to look into this once 3.11 support for Nuitka is solved.

**Comment by androo-L** [comment]
I've also come across this bug, but without using numpy - just pint with a normal python int or float, eg:  

test_pint.py:

```python
import pint

ureg = pint.UnitRegistry(autoconvert_offset_to_baseunit=True)

print( 1 * ureg.V )
```

gives the following when run:

```
Traceback (most recent call last):
  File "X:\DataBase scripts\modules\test_pint.py", line 7, in <module>
    print( 1.0 * ureg.V )
  File "X:\DataBase scripts\modules\.venv\lib\site-packages\pint\facets\plain\unit.py", line 145, in __mul__
    return self._REGISTRY.Quantity(other, self._units)
  File "X:\DataBase scripts\modules\.venv\lib\site-packages\pint\facets\plain\quantity.py", line 221, in __new__
    inst = SharedRegistryObject().__new__(cls)
  File "X:\DataBase scripts\modules\.venv\lib\site-packages\pint\util.py", line 815, in __new__
    inst = object.__new__(cls)
TypeError: object.__new__(X): X is not a type object (SharedRegistryObject)
```

I can't see what is going wrong though.

**Comment by androo-L** [comment]
Sorry, I should note that the traceback is from when the `1` was `1.0`.

**Comment by kayhayen** [comment]
So, 3.11 is done, and I am going to look at this kind of issue. To me a reduced test case is very helpful @androo-L as that is taking a lot of things out of the loop.

**Comment by kayhayen** [comment]
So, this is getting wrong code executed:

`inst = SharedRegistryObject().__new__(cls)` where it seems, that the really simple `SharedRegistryObject` class with just a plan standard `__new__` is getting called with the wrong arguments. This should be a `classmethod` automatically, and in general those are known to work with Nuitka, but maybe some part of the calling code in `CALL_METHOD_WITH_SINGLE_ARG` is just wrong. 

What ends up happening, is that rather than passing `cls` as first argument, the instance of the argument, is passed, as if it was a normal method. This is of course a bug.

**Comment by kayhayen** [comment]
I managed to drill it down to this:

```
class SharedRegistryObject:
    def __new__(cls, *args, **kwargs):
        if cls is not SharedRegistryObject:
            print("SharedRegistryObject.__new__ enter", cls, args, kwargs)

        inst = object.__new__(cls)
        return inst


inst = SharedRegistryObject().__new__(object)
```

The metaclass is called twice, once for the `SharedRegistryObject()` and once for the manual `__new__` call as a function. Adding a `@classmethod` to `__new__` makes it work. This is supposedly done automatically during the tree building phase of Nuitka, adding e.g. also things for other methods. But apparently, something doesn't add up there.

**Comment by kayhayen** [comment]
So, somehow for Python3, this was no longer done. It appears, the core class creation no longer needs it, but  that doesn't mean, that a manual code like above, wouldn't expect them to be still treated like it. Also they are `staticmethod`. It's also fine to make them class methods, according to the Python2 code, which explains why it was working, and that is respected too by the code, i.e. not changed then.

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
So, sadly, my CI hates it. It breaks `test_enum´ of CPython, which doesn't like `__new__` to be a staticmethod. That is probably why it was removed for Python3 in the first place. I will need to revert it, and instead make a anti-bloat engine replacement, or something like that, that does it for just this case, maybe adding it as a new feature, adding decorators could potentially solve a bunch of things in the future.

**Comment by kayhayen** [comment]
So, factory got the more target fix, that changes only `pint` to become supported. This will be in 1.6.1 once it's released.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.6.2 that I just made.
