### ISSUE TITLE
windows7 PyQt5.QtWebEngineWidgets ImportError

### ISSUE THREAD

**Issue by baa-god** [Nuitka/Nuitka#1817]
```python
# main.py
import PyQt5.QtWebEngineWidgets
```

Windows10 run:
```shell
nuitka `
--clang `
--standalone `
--show-memory `
--show-progress `
--enable-plugin=pyqt5 `
--enable-plugin=pylint-warnings main.py
```

I have installed the necessary libraries required by `PyQtWebEngine`:

```shell
PyQt5             5.15.7
PyQt5-Qt5         5.15.2
PyQt5-sip         12.11.0
PyQt5-stubs       5.15.6.0
PyQtWebEngine     5.15.6
PyQtWebEngine-Qt5 5.15.2
```

Executing `main.exe` on Windows 10 works without any problems, but on Windows 7 it gives an error:

```python
Traceback <most recent call last>:
   File "D:\kfsys\main.py", line 1, in <mobule>
ImportError
```

After comparison, I found that there is a static library called `dbghelp.dll` in the packaged directory. If it is deleted, `main.exe` will be executed successfully on Windows7.

Is the error caused by an extra `dbghelp.dll`? or something else? Can this be fixed?

**Comment by seydss** [comment]
https://groups.io/ics/7195806/234609498425746857/feed.ics

**Comment by kayhayen** [comment]
I cannot support Windows 7 outside of https://nuitka.net/doc/commercial.html
