### ISSUE TITLE
Nuitka Assumes "~/Library/Application Support/Nuitka" is writable

### ISSUE THREAD

**Issue by carles-protopixel** [Nuitka/Nuitka#1819]
If Nuitka can't find a ccache installation, it will download one.

When used in OSX, it will download it into `~/Library/Application Support/Nuitka`. In our case, this is a problem because our CI environment will not allow creating anything inside `~/Library`.

For `getCacheDir()` this can be overridden by using `NUITKA_CACHE_DIR` env variable. However, no such thing exists for `getAppDir()`.

`getCachedDownload(...)` will just consume `getAppDir()`:

https://github.com/Nuitka/Nuitka/blob/e12789463dd4da1c279d515c8345258936ea0fb9/nuitka/utils/Download.py#L45

It would be very useful for us to have an environment variable to set this directory. For the time being, we have to disable ccache.

**Comment by kayhayen** [comment]
What CI type is that?

**Comment by kayhayen** [comment]
Looking at `getAppDir` this is the only usage of it, and I kind of wonder, why downloads should go there, rather than in the cache directory. And since I do not intend to add user level Nuitka configuration (anybody ever saw gcc user configuration?), this method can probably be removed.

It's of course a big ugly, that this breaks all previous download caching, but I guess, such is life.

**Comment by carles-protopixel** [comment]
Thanks! For reference, we are running the build under bazel, which uses `sandbox-exec` in OSX, so the build is not affected by user configuration stuff.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working. 

I am closing this for lack of general relevance early.

**Comment by kayhayen** [comment]
This is currently on develop branch.

**Comment by kayhayen** [comment]
Part of the 1.2 release that was made a while ago.
