### ISSUE TITLE
importing uproot package with standalone

### ISSUE THREAD

**Issue by ty-borg** [Nuitka/Nuitka#1825]
•	Nuitka version, full Python version, flavor, OS, etc. as output by this command.
```
python -m nuitka –version
1.0.7
Commercial: None
Python: 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\path\to\env\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

•	How did you install Nuitka and Python
Python installed via anaconda.  Virtual environment setup and command “python -m pip install <package>” used for installing packages. 

•	The specific PyPI names and versions
`uproot==4.3.5`

•	Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)
`import uproot`

•	Provide in your issue the Nuitka options used
`python -m nuitka  --follow-imports --enable-plugin=numpy --standalone  test.py`

Explanation:
I am trying to make a single file executable with Nuitka and am running into problems with the uproot package.  I’ve been able to successfully make an executable with the code when not including the portions that import uproot, but it fails when including that package.  I usually put input(“some text”) statements around the code example and it never makes it to the input(“some text”) statement after the import statement.
A couple comments from playing around with the uproot source code trying to track down the issue.  Uproot has several dependencies, of which only numpy is a hard requirement.  One of the dependencies isn’t available on windows (xrootd) and the portions of the uproot source code containing code related to that package seem to be causing issues (if I comment out said code, the executable will make it further into the source code but crash again when hitting another piece of code related to that package or perhaps code related to the other optional dependencies).
Uproot works perfectly fine on windows when using it in a script, so I’m wondering if there is a way to get it to work when using Nuitka as well.

**Comment by kayhayen** [comment]
You are not using the latest stable release, not the previous last hotfix.

**Comment by ty-borg** [comment]
Sorry about that.  I've updated to 1.1.2 and retried with no success.

I also re-installed uproot to avoid any changes I made and to get the original warnings that come up:

```
Nuitka-Inclusion:WARNING: Cannot find distribution 'XRootD' at                                                         
Nuitka-Inclusion:WARNING: 'C:\env\lib\site-packages\uproot\extras.py:135', expect potential run time   
Nuitka-Inclusion:WARNING: problem, unless this unused code.                                        
Nuitka-Inclusion:WARNING: Cannot find distribution 'pyxrootd' at        
Nuitka-Inclusion:WARNING: 'C:env\lib\site-packages\uproot\extras.py:139', expect potential run time   
Nuitka-Inclusion:WARNING: problem, unless this unused code.
```

**Comment by kayhayen** [comment]
@ty-borg interesting, what do you expect from me now?

**Comment by kayhayen** [comment]
Closing for lack of feedback.
