### ISSUE TITLE
Windows: DLL's not found in WinSxS system folder

### ISSUE THREAD

**Issue by rayjharvey** [Nuitka/Nuitka#1828]
1.1.2
Commercial: None
Python: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

Nuitka will say it cannot find a .dll in WinSxS folder when compiling.

Most current example:

FATAL: Error, attempting to include file 
c:\windows\winsxs\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22000.1_none_271a8fad6a2d1b1e\comctl32.dll' (Used by '_tkinter.pyd') that does not exist.
'c:\windows\winsxs\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.22000.978_none_ce87762a12f7f3ba\gdiplus.dll' (Used by 'win32ui.pyd') that does not exist.

Version 5.82.22000.1 is an older version that Windows automatically removes. However, it retains four other versions of the file.

The workaround being used is to boot into a PE environment and go into "God Mode" and manually create the directory then copy the .dll from one of the other directories.

This works until the next Windows Update cycle that updates core systems such as .NET runtimes or Features and the system removes the folder again.

**Comment by kayhayen** [comment]
But does your Python 3.10 tkinter work when it is bound by SxS in that way? You did not provide an example, so I have to guess stuff which I do not like.

**Comment by rayjharvey** [comment]
Not to be funny, you want an example of what? Yes, tkinter works fine when ran unfrozen or even from one of the other frozen methods without modifying the SxS folder. It's very well tested, in use for a year. The mature tkinter PySimpleGUI is used if that is what you want an example of.  But what part of the code do you need to see? The imports? How is a window created? I know you don't want the whole source, but I'd have no idea what to show you since the code runs and compiles without issue otherwise. Perhaps when it happens again, take an example off the pysimeplegui website and attempt to compile it to see if the same thing happens (which I would think so since nothing fancy is done) and give that to you to duplicate? Which I'd be happy to do. Again, not to be funny, I'd have to guess myself at internal Nuitka DLL errors as I have no idea how that works.

**Comment by kayhayen** [comment]
You are not funny, no worry. I need an example program to see things for myself. If you cannot provide it, no problem, one day somebody will. Thanks for your tipps.

**Comment by kayhayen** [comment]
After a collaborator encountered a similar issue, this has been narrowed down to being 2 issues.

First, the caching of dependencies didn't detect SxS changes. Second, including SxS is probably wrong anyway, no PyPI package will ever use it for real.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
The is part of the current stable release. Not including SxS anymore, is on 1.2 and will be in the release, but the issue was not  about it, therefore closing now.
