### ISSUE TITLE
"Windows SDK must be installed" but it's already installed

### ISSUE THREAD

**Issue by ripdechains** [Nuitka/Nuitka#1831]
1.1.2
Commercial: None
Python: 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
Flavor: Unknown
OS: Windows
Arch: x86_64
WindowsRelease: 10 (Really it's 11)
-------------------------------------
I have installed Nuitka via pip (` python -m pip install nuitka` )
I have installed "orderedset" PyPI package.
I'm trying to obtain a standalone executable from a script in this way:  `python -m nuitka myscript.py --onefile`

I get this error at the end: `FATAL: Error, the Windows SDK must be installed in Visual Studio.`
I have bot VS2012 and VS2015 insatlled and SDK for Windows 11.
I have also try to install Clang for Visual Studio then repeat command with `--clang` flag but I receive this error: `FATAL: Visual Studio has no Clang component found at 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\x86_amd64\cl.ex\Llvm\x64\bin'.`

Now I'm trying to completely uninstall all Visual Studio versions and reinstall the last Visual Studio.
Do you have another tips for solve this issue? 
Thank you in advance and good work

**Comment by ripdechains** [comment]
Solved installing Visual Studio 2022 and installing MinGW64 via MSYS2 . Standalone executable has been generated with 0 errors

**Comment by kayhayen** [comment]
Just for the record, external installations of SDKs do not count, they must be installed inside the Visual Studio version itself and appear to be private to it. Same for clang, which I believe was not available for old Visual Studio. I guess the error message could be nicer there, but not following the user manual is never going to work smooth anyway.
