### ISSUE TITLE
Import error in numpy.testing assert_ function when using statsmodels.tsa.api VAR module

### ISSUE THREAD

**Issue by Pasmikh** [Nuitka/Nuitka#1834]
Nuitka version 1.1.2
Commercial: None
Python: 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\ProgramData\Miniconda3\envs\ml_oil_windows\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

* I installed python with conda and nuitka with conda-forge in virtual environment.
print('Hello world') compilation works correctly.

* Python file that produces error (SSCCE):
`from statsmodels.tsa.api import VAR`
statsmodels library version 0.13.2
numpy version 1.23.3

* Nuitka options used
`python -m nuitka --standalone --plugin-enable=numpy --lto=no main.py`

* When I launch exe file, I get following output:
`Traceback (most recent call last):
  File "C:\Users\Pavel\Test\TEST~1.DIS\test.py", line 1, in <module>
  File "C:\Users\Pavel\Test\TEST~1.DIS\statsmodels\tsa\__init__.py", line 1, in <module statsmodels.tsa>
  File "C:\Users\Pavel\Test\TEST~1.DIS\statsmodels\tools\__init__.py", line 2, in <module statsmodels.tools>
  File "C:\Users\Pavel\Test\TEST~1.DIS\statsmodels\tools\_testing.py", line 17, in <module statsmodels.tools._testing>
ImportError: cannot import name 'assert_' from 'numpy.testing' (C:\Users\Pavel\Test\TEST~1.DIS\numpy\testing\__init__.py`

**Comment by kayhayen** [comment]
Thanks for the report, that is a serious problem with anti-bloat replacement of `numpy.testing`.

**Comment by kayhayen** [comment]
This has been fixed and released as part of the 1.1.6 hotfix release.
