### ISSUE TITLE
Error, failed to detect gcc version of backend compiler 'gcc'.

### ISSUE THREAD

**Issue by Yoko11111111** [Nuitka/Nuitka#1835]
Hello, i have an problem to compile with nuitka.

I am using the command:
python -m nuitka --windows-icon-from-ico=ico.ico --onefile --windows-company-name=Zuna --windows-product-version=1.0 --plugin-enable=tk-inter main.py

Im getting the error: FATAL: Error, failed to detect gcc version of backend compiler 'gcc'.
libwinpthread-1.dll wasnt found.

Any Solutions or help please?

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun.
