### ISSUE TITLE
Newer shapely version does not properly load DLLs

### ISSUE THREAD

**Issue by sebastian-szurlej** [Nuitka/Nuitka#1837]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

1.1.3
Commercial: None
Python: 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: D:\dev\venvs\nuitka-test\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

* How did you install Nuitka and Python

pip install Nuitka

* The specific PyPI names and versions

anyio==3.5.0
asgiref==3.5.0
click==8.1.3
pydantic==1.9.0
python-dotenv==0.20.0
PyYAML==6.0
Shapely==1.8.4
sniffio==1.2.0
sse-starlette==1.1.6
starlette==0.17.1
typing_extensions==4.2.0
uvicorn==0.17.6
watchgod==0.8.2
websockets==10.3

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

```
from shapely.geometry import Point, Polygon, LineString
from shapely.strtree import STRtree

if __name__ == '__main__':
    print(Point)
    print(Polygon)
    print(LineString)
    print(STRtree)
```

* Provide in your issue the Nuitka options used

nuitka --standalone main.py

I am getting the error below:

Traceback (most recent call last):
  File "D:\dev\repos\nuitka-shapely\main.dist\main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\dev\repos\nuitka-shapely\main.dist\shapely\__init__.py", line 29, in <module shapely>
  File "D:\dev\repos\nuitka-shapely\main.dist\shapely\__init__.py", line 14, in _delvewheel_init_patch_0_0_23
  File "D:\dev\repos\nuitka-shapely\main.dist\os.py", line 1111, in add_dll_directory
FileNotFoundError: [WinError 2] Nie można odnaleźć określonego pliku: 'D:\\dev\\repos\\nuitka-shapely\\main.dist\\Shapely.libs'

It seems that since version 1.8.1 of shapely, they have changed how the wheels are build:
https://github.com/shapely/shapely/issues/1326#issuecomment-1048507697
above may be helpful somehow I think.

**Comment by kayhayen** [comment]
This is using `_delvewheel_init_patch_0_0_23()` something, which the zmq plugin already handles.

```
    def onModuleSourceCode(self, module_name, source_code):
        if module_name == "zmq" and Options.isStandaloneMode():
            # TODO: Make the anti-bloat engine to this.

            if "_delvewheel_init_patch" in source_code:
                match = re.search(
                    r"(def _delvewheel_init_patch_(.*?)\(\):\n.*?_delvewheel_init_patch_\2\(\))",
                    source_code,
                    re.S,
                )

                delvewheel_version = match.group(2).replace("_", ".")

                self.info(
                    "Detected usage of 'delvewheel' version %r." % delvewheel_version
                )

                code = match.group(1)

                code = code.replace("os.add_dll_directory", "add_dll_directory")
                code = code.replace("sys.version_info[:2] >= (3, 8)", "True")

                # Fake the __file__ to the proper value.
                exec_globals = {
                    "__file__": self.locateModule(module_name) + "\\__init__.py",
                    "add_dll_directory": self._add_dll_directory,
                }

                # We believe this should be the easiest, pylint: disable=exec-used
                exec(code, exec_globals)

    def getExtraDlls(self, module):
        # TODO: DLL directory from code like this, is not yet a thing.
        if module.getFullName() == "zmq" and self.dll_directory is not None:
            for dll_filename in getFileList(self.dll_directory):
                yield self.makeDllEntryPoint(
                    source_path=dll_filename,
                    dest_path=os.path.join(
                        "pyzmq.libs", os.path.basename(dll_filename)
                    ),
                    package_name="zmq",
                    reason="needed as a workaround for old 'zmq'",
                )

```

Originally, when I wrote that code, I believed this could be general purpose. I have no encountered anything else using it in a long time, though. We could make it general and separate plugin trying to deal with this on a general level. I am just not sure how to handle old and Anaconda shapely alongside this.

Extending the Yaml to cover it, would also be cool, but programming in Yaml is probably not where we should go. But we might want to have a way to tell the yaml part, to not fire, though a tag, set by the plugin matching. That would require plugins to have an extra slot, whereby looking at the code, they can act. In this case, `shapely` and `shapely.goes` however are both competing for the DLLs to be provided. But the `dlls` section of `shapely.geos` probably safely.

What I do not really want to do is to become dependent on `shapely.__version__` or anything like that, since that may work not well, however we may have to finally implement this, unless I come up with a way of making it unnecessary. But we may have reached the end of the road for it.

So probably, generalized `pyzmq` plugin plus version dependent disable of the `shapely` DLL related changes, is the way to go, this may have to be 1.2 material, but I can also imagine this being a hofix.

**Comment by kayhayen** [comment]
So, I managed to generalize the zmq plugin, need to check now, if it still works for zmq. Also added support for checking the version, but I need to find the precise version to check against, but I guess I will trust you there.

```
- module-name: 'shapely.geos'
  dlls:
    # PyPI has it contained.
    - by_code:
        setup_code: 'import shapely.geos'
        filename_code: 'shapely.geos._lgeos._name'
      when: 'not anaconda and not win32 and version("shapely") < (1,8,1)'
    # Anaconda or Win32 are forced to specific path.
    - by_code:
        setup_code: 'import shapely.geos, os'
        filename_code: 'shapely.geos._lgeos._name'
      dest_path: 'shapely'
      when: 'anaconda or win32 and version("shapely") < (1,8,1)'
```

**Comment by kayhayen** [comment]
Says now: 

> Nuitka-Plugins:INFO: pyzmq: Detected usage of 'delvewheel' version '0.0.23' in module 'shapely'.

I am keeping the plugin name as pyzmq for now, although in theory, it should automatically cover all delvewheel using packages now. I hope these are getting more.

**Comment by kayhayen** [comment]
In terms of deployment, I mean to put it 1.1.4 hotfix out first, and include this in 1.1.5 only.

**Comment by sebastian-szurlej** [comment]
Thanks Kay!

Regarding the exact version, I believe it is 1.8.1 - it is also indicated within pyinstaller hooks for shapely:

https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-shapely.py

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.1.5 that I just made.
