### ISSUE TITLE
Fail to load packages from within pyqt

### ISSUE THREAD

**Issue by djh208** [Nuitka/Nuitka#1840]
I am getting an import error when generating a standalone package using PyQT:
ImportError: LoadLibraryExW 'C:\Users\***\Test\PyQt5\QtCore.pyd' failed: The specified procedure could not be found.

This appears to be similar to issue #453
https://github.com/Nuitka/Nuitka/issues/453

However, that appears to have been addressed. I tried reverting to Nuitka 0.6.5 and PyQT 5.12.3 but that did not fix this issue.

The develop version of Nuitka has the same issue.

* Nuitka version:

1.1.3
Commercial: None
Python: 3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\*****\Anaconda3\envs\py37-nmr_pyqt5upd\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

* How did you install Nuitka and Python

I installed Nuitka using pip. My python installation is run through Anaconda. I use the Spyder IDE but installs were done using a python command window started from Anaconda.

* The specific PyPI names and versions

I think the relevant outputs from freeze are:
Nuitka==1.1.3
PyQt5==5.12.3
PyQt5-Qt5==5.15.2
PyQt5-sip==4.19.19
pyqtgraph @ file:///tmp/build/80754af9/pyqtgraph_1594064840332/work
PyQtWebEngine==5.12.1
QtAwesome @ file:///tmp/build/80754af9/qtawesome_1615991616277/work
qtconsole @ file:///tmp/build/80754af9/qtconsole_1616775094278/work
QtPy==1.9.0

 * Many times when you get an error from Nuitka, your setup may be special

I can confirm that I can run a simple "Hello World" script, and I can compile that into a standalone package that works perfectly.

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

This example script fails on the second line when it tries to import QtCore:

print('Hello World')
from PyQt5 import QtCore
print('I ran!')

* Provide in your issue the Nuitka options used

I compile the script using:
python -m nuitka testpyqt.py --standalone --enable-plugin=pyqt5

**Comment by kayhayen** [comment]
I am treating this as an issue to make it more clear in the PyQt5 plugin at least, if not in the PyQt6 plugin as well, that it is recommened to use PySide instead. With Anaconda, it seems clear it might not be working at all, although it might be nice to get at least PyQt6 to work if they have that, but first we ought to learn how well that works at all.

**Comment by djh208** [comment]
Thanks for the clarification, I had not realised that. I will try switching to PySide for now.

**Comment by kayhayen** [comment]
I checked on Anaconda, in preparation to adding a warning, finding that conda installed PyQt5 did not really work at all, mostly because of static paths from the build machine given as responses. I now believe your test case that you did not provide is not what it should be.

I added a warning for the factory branch, and a workaround to these unusable paths.

**Comment by kayhayen** [comment]
I am closing this now. I checked one known problem, namely Qt threading with PyQt6, and it works. I will probably not recommend against it, but there should be more issues around.

**Comment by kayhayen** [comment]
Using pip with Anaconda Python is not Anaconda from mine or their perspective. Anyway, PyQt5 from conda packages would now work, might come in handy if there are ever PyQt6 packages, which there are not. Maybe they don't see the benefit either with PySide6 being there.

**Comment by djh208** [comment]
@gdementen Thanks for that suggestion.  Though, I have my code working with PySide now, which is probably the optimal solution as it sounds like that is going to be better supported. 
@kayhayen Thanks again for a very prompt responses. You've developed a fantastic package.

**Comment by kayhayen** [comment]
But I was crazy enough to add PyQt5 conda package support to Nuitka, so no workaround like that is necessary anymore.

**Comment by kayhayen** [comment]
Part of the 1.2 release that was made a while ago.
