### ISSUE TITLE
cannot import name 'check_ansix923_padding' from 'cryptography.hazmat.bindings._rust' (unknown location) 

### ISSUE THREAD

**Issue by emre84** [Nuitka/Nuitka#1841]
**Environment:**
MACOS Monterey
Python:3.7.3
Nuitka 'Nuitka-1.2rc4'

**How did you install Nuitka and Python**
pip

**Provide in your issue the Nuitka options used**
sudo python3.7 -m nuitka --run --standalone --enable-plugin=numpy,pyside2 --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow --python-flag=no_site main.py

**Error during nuitka standalone compilation:**
Traceback (most recent call last):
"/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/main.dist/managers/file_encryption_manager.py", line 27, in <module managers.file_encryption_manager>
  File "/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/main.dist/cryptography/fernet.py", line 14, in <module cryptography.fernet>
  File "/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/main.dist/cryptography/hazmat/primitives/padding.py", line 11, in <module cryptography.hazmat.primitives.padding>
ImportError: cannot import name 'check_ansix923_padding' from 'cryptography.hazmat.bindings._rust' (unknown location)

**Failed Code Line:**
from cryptography.fernet import Fernet

**My nuitka --version output:**
emres-Air:inference emre$ sudo python3.7 -m nuitka --version
1.2rc4
Commercial: None
Python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
Flavor: Unknown
Executable: /usr/local/bin/python3.7
OS: Darwin
Arch: x86_64

**PS: With the reason that current Nutika version 1.1.3 is not compilable on my MacOS(issue:#1833) I could just test my code with Factory (Nuitka-1.2rc4) branch.**
Thanks a lot in advance.

**Comment by kayhayen** [comment]
Not sure what causes this, but my attempts with CPython and Anaconda just worked, and on 3.7 Anaconda, it fails to run with python itself. Installing `python==3.7.5` and `cryptography` yieled unusable module.

**Comment by emre84** [comment]
Hi Kay, sorry I could not get what you require. needs_example means that you need example from me?
So I have to send the exact py script, which causes compilation error. Right?

PS:Actually I have already written down above:
**Failed Code Line:**
from cryptography.fernet import Fernet

**Comment by kayhayen** [comment]
I have failed to reproduce it though. It might be due to you using an older version. Like I said Anaconda env based on 3.7 didn't allow me to create a usable environment. In Anaconda there are environment files. If you figure out how to create one and give it to me, I might be able to reproduce. But this just gave me outright an error trying that import with the conda packages mentioned. All on macOS.

**Comment by emre84** [comment]
Hallo Kay,

I installed Anaconda navigator and created a python environment with python 3.7.13 version and cryptography version 38.0.1( the latest version ) but I could not reproduce either.

But If you use standard Python:3.7.3 on MacOS and with cryptography version 38.0.1 (the latest version ). It is reproducible.

Repro Steps:
1-Create a file like test.py with following line
from cryptography.fernet import Fernet
2-pip install cryptography==38.0.1
2- then compile this file with following common:
sudo python3.7 -m nuitka --run --standalone --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow --python-flag=no_site test.py

Is it not possible to try it to reproduce with standard python as I did on your own MacOS. 

I would be appreciated for a response. Thanks a lot in advance.

**Comment by kayhayen** [comment]
I cannot reproduce, so something is missing from this report, and so far you are not succeeding at making it clear what it is. I am not going to downgrade my CPython 3.7 to your version, wasted too much time on nothing reproducible here already, and that seems desparate, but maybe you upgrade your CPython to 3.7.9 and see if that helps.

**Comment by kayhayen** [comment]
I thought about this, I can offer this. In your minimal CPython 3.7 setup, can you send me a `--report=compilation-report.log` so I can look at it. We can switch this to email, I believe you have my address. Then I am going to enhance that reporting feature, until I iron out, what the difference is. This should be viewed as a chance to enhance the tools for reporting to a level where I can do this from said report.

**Comment by emre84** [comment]
Hallo Kay,

Thanks for the offer. I sent you my log report(From nuitka version 1.2rc4) per Email.

**Comment by emre84** [comment]
Hi Kay, I installed 3.7.9 CPython as you recommended, and compilation worked fine with 1.2rc7 nuitka version. Then I downgraded back to my old python version 3.7.3 and compiled with the same nuitka version, it worked either. So I do not know what the reason is, but everything works fine now.

Thanks for your supports. You can close the issue.

Summary:
So cryptography works fine with following versions:
 
emres-Air:main.dist emre$ python3.7 -m nuitka --version
1.2rc7
Commercial: None
Python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
Flavor: CPython Official
Executable: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7
OS: Darwin
Arch: x86_64

**Comment by kayhayen** [comment]
Ok, lets give up on this then, since the environment you have likely got lost, and this must be a corner case, that will show itself in another place maybe later with more clarity.
