### ISSUE TITLE
Compilation takes forever when module contains Sqlalchemy ORM Model classes

### ISSUE THREAD

**Issue by m-ar13f** [Nuitka/Nuitka#1846]
Nuitka compilation run fast but it tooks forever when compile module containing sqlalchemy model class. I've tried nuitka from 1.0.4 version and last version 1.1.5 and the issue perisist.
Nuitka version 1.1.5 run on python 3.10 arch linux.

Options used:
Nuitka-Options:INFO: Used command line options: --module ./path/to/package/__main__.py --include-package=package.module --nofollow-imports --remove-output --lto=no --no-pyi-file --output-dir=src/package

Example code :
```
from dataclasses import dataclass
from dataclasses import field
import datetime
from decimal import Decimal
from sqlalchemy import ForeignKey
from sqlalchemy import MetaData
from sqlalchemy import Table
from sqlalchemy.orm import registry
from sqlalchemy.schema import DefaultClause
from sqlalchemy import Boolean, Column, DateTime, Integer, String, Text, text
from sqlalchemy.dialects import postgresql as sql_dialects

mapper_registry = registry()

@dataclass
class Categories:
    id: str = field(init=False)
    name: str = None
   
metadata_obj = MetaData(schema="some_schema")

categories = Table(
    'categories',
    metadata_obj,
    Column('id',sql_dialects.UUID(),primary_key=True,nullable=False,),
    Column('name',sql_dialects.VARCHAR(length=255),nullable=True,),   
)

mapper_registry.map_imperatively(Categories, categories)`
```

The above code will take forever when compiling with nuitka. For now i just exclude the package when running compilation.
I guess the sqlalchemy Table object was the culprit.

**Comment by kayhayen** [comment]
Note: In module mode, you are not really supposed to include third party code anyway. It's unlikely to work or have any meaningful distribution value.

**Comment by kayhayen** [comment]
For accelerated, and probably standalone mode, I guess the same holds true. This is however probably a scalability bug that occurs with many classes in the same file with Nuitka. I will see if this one makes it easier to attack.

**Comment by m-ar13f** [comment]
> Note: In module mode, you are not really supposed to include third party code anyway. It's unlikely to work or have any meaningful distribution value.

Yes,  what I wanted to do was to compile application main module in some package and all the subpackages in it and then distribute it to python wheel including required files to run the app. It's actually whole app not a package library. 
It seems to work though, I've tried and run the compiled module. It's like package compilation maybe. I go through this direction bcoz I couldn't figure out nuitka with setup tools,  time contraint, may be I need more research though.

**Comment by kayhayen** [comment]
Without a wheel, modules do not allow to include data files unless you are using Nuitka commercial, which can embedd data files for use in the Python code. But if it works for you, all power to you, just saying it is not the intended solution. Glad if it works. 

https://nuitka.net/doc/commercial/protect-data-files.html

Maybe one day somebody will make a tutorial on how to achieve it with pyproject.toml as well, but I believe it's not straightforward to include stuff for many other modules there, but dependencies would have to work for you.

**Comment by m-ar13f** [comment]
> Without a wheel, modules do not allow to include data files unless you are using Nuitka commercial, which can embedd data files for use in the Python code. But if it works for you, all power to you, just saying it is not the intended solution. Glad if it works.
> 
> https://nuitka.net/doc/commercial/protect-data-files.html
> 
> Maybe one day somebody will make a tutorial on how to achieve it with pyproject.toml as well, but I believe it's not straightforward to include stuff for many other modules there, but dependencies would have to work for you.

yes, I didn't include the data files in compilation bcoz I knew it wasnt possible in non commercial version. That's why the data files remain untouched. I just included them in python wheel distribution together with single compiled file. My purpose is just to see how fast the application is in compiled mode.  It's flask application actually. So the wheel distribution only contains one compiled main module with the depedency package in it, and the rest of it are data files. I just playing around and it works.

**Comment by kayhayen** [comment]
In the 1.4 release, a lot of scalability work has been done, this should now be somewhat better.

**Comment by m-ar13f** [comment]
Awesome, I'm impressed how fast nutika progressing. Gonna try it. 

Thank you sir.
