### ISSUE TITLE
Error: no such option: --windows-onefile-tempdir-spec=

### ISSUE THREAD

**Issue by BTCapsule** [Nuitka/Nuitka#1849]
I am trying to use --windows-onefile-tempdir-spec=.\temp as suggested in issue #1388, but I get an error:

__main__.py: error: no such option: --windows-onefile-tempdir-spec=

I am using Python 3.9 (64-bit) in Microsoft Visual Studio 2017.

**Comment by kayhayen** [comment]
Feel free to read the help output. I will add an entry to the changelog too, so it could found that way too.

**Comment by kayhayen** [comment]
Seems, this was done for 1.1 and deployed inside the 1.0.8 hotfix as well. Added this here:

```
+-  UI: Removed ``--windows-onefile-tempdir-spec`` alias of
+   ``--onefile-tempdir-spec`` option, it is no longer Windows specif
ic.
+
```

This was probably not intended to be done in a hotfix, but such is life.
