### ISSUE TITLE
webpage: update link to the Arch Linux AUR package

### ISSUE THREAD

**Issue by xyproto** [Nuitka/Nuitka#185]
Hi,

This is hopefully an acceptable place to report the following issue:

On the [Nuitka download webpage](https://nuitka.net/pages/download.html) there is a dead link to https://aur.archlinux.org/packages.php?ID=55267.

The correct/updated link is: https://aur.archlinux.org/packages/nuitka-git/

There is also no need to mention the name of the AUR maintainer of the unofficial Nuitka package, since AUR packages may change hands relatively often (unless you want to follow the AUR package somehow, and update the name with regular intervals).

Cheers!

**Comment by kayhayen** [comment]
Thanks Alexander for the report. I updated the download page with the new link.
