### ISSUE TITLE
OSError [WinError 127] pyzmq.libs not found?

### ISSUE THREAD

**Issue by jekoie** [Nuitka/Nuitka#1854]
```console
C:\Users\jett>python  -m nuitka --version
1.1.6
Commercial: None
Python: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:34:34) [MSC v.1928 32 bit (Intel)]
Flavor: Unknown
Executable: C:\Users\jett\AppData\Local\Programs\Python\Python38-32\python.exe
OS: Windows
Arch: x86
WindowsRelease: 10


C:\Users\jett>pip show pyzmq
Name: pyzmq
Version: 24.0.1
Summary: Python bindings for 0MQ
Home-page: https://pyzmq.readthedocs.org
Author: Brian E. Granger, Min Ragan-Kelley
Author-email: zeromq-dev@lists.zeromq.org
License: LGPL+BSD
Location: c:\users\jett\appdata\local\programs\python\python38-32\lib\site-packages
Requires:
Required-by: zmq
```

**compile cmd**
`nuitka --noinclude-IPython-mode=nofollow --plugin-enable=pyqt5 --windows-icon-from-ico=./design/res/logo.ico --show-progress --lto=yes  --output-dir=dist --no-pyi-file --remove-output --show-modules --include-package=websockets,uvicorn,certifi,requests  --show-modules-output=./dist/module.txt --nofollow-import-to=PIL,lib2to3,matplotlib,tornado,tkinter --standalone FWTMES.py`

I try to compile my app, it contains `PyQt5, pyzmq, fastAPI` important packages, I successfuly compile my app.
And it run well on win10 system, but when I copy it  to my workmate win7 system. I run as follow error?

![image](https://user-images.githubusercontent.com/6836400/197663144-fa3c9f7d-93be-4528-8985-d6b122148f4e.png)

**Comment by kayhayen** [comment]
Does the `pyzmq.libs` folder exist, and what does it contain?

**Comment by kayhayen** [comment]
Can you try with Nuitka develop branch. I recently noticed with a Windows 11 update, that we incliude SxS DLLs, which the OS provides, not only for no good reason, but maybe as a bad idea for backward compatibility. If such a DLL came from Windows 10 there, if would be hindering. Also if you produce the `--report=compilation-report.xml` output, I can tell from there, if a DLL is included that might have this issue.

**Comment by jekoie** [comment]
I am use macbook pro M1, and install win11 on virtual machhine,The error is fixed when my friend update his win7 system.
Bellow is my compile log, hope can help you.Thanks.
[compilation-report.xml.txt](https://github.com/Nuitka/Nuitka/files/9892604/compilation-report.xml.txt)

**Comment by kayhayen** [comment]
The recommended way to support Windows 7 or even Windows XP is to compile on that system. If done correctly, it's known to be backward portable. Since all DLLs are from your Python 3.8 installation, it's your task to make sure they support the systems you want it to.  For Windows 10, e.g. there are also versions that are not supported by some software. I don't know PyQt5 requirements.

**Comment by jspzyhl** [comment]
Uninstall Python3.8 and reinstall Python3.7, compile your app with python3.7 and nuitka, the output exe can be executed on windows 7.
