### ISSUE TITLE
nuitka crashes if python package has text in the version

### ISSUE THREAD

**Issue by mz3-andrey** [Nuitka/Nuitka#1857]
System: 
1.1.6
Commercial: None
Python: 3.8.13 (default, Aug  9 2022, 11:20:38) 
Flavor: Unknown
Executable: /some/path/to/venv/python3.8
OS: Linux
Arch: i686
Distribution: Debian 7
nuitka was installed through pip

`pip freeze`:

Events==0.4
Nuitka==1.1.6
ordered-set==4.1.0
Shapely==1.8.5.post1
zstandard==0.18.0

When running nuitka --standalone I get a traceback that ends in
`ValueError: invalid literal for int() with base 10: 'post1'`
The traceback mentioned module versions so I checked `pip freeze` and found the culprit

Fixed the issue by getting another version of Shapely.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by h8n71r5t** [comment]
Can we start posting Nuitka bugs related to Python 3.11 or it isn't allowed yet?

**Comment by mz3-andrey** [comment]
Works on factory, thanks!

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.1.7 that I just made.
