### ISSUE TITLE
Nuitka 1.1.6 with OpenCV 4.6.0 Recursion issue

### ISSUE THREAD

**Issue by austin-InDro** [Nuitka/Nuitka#1859]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

```
python -m nuitka --version

1.1.6
Commercial: None
Python: 3.9.12 (main, Apr  5 2022, 06:56:58) 
Flavor: Anaconda Python
Executable: /home/austin/miniconda3/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.1
```
* Issue has been mentioned in
#1366 

* How did you install Nuitka and Python

pip

* The specific PyPI names and versions

`opencv-python`
```
import cv2
cv2.__version__
'4.6.0'
```

* Many times when you get an error from Nuitka, your setup may be special

The full code:
`import cv2` (Named opencv_tester.py)

Command: `python3 -m nuitka --follow-imports --static-libpython=no opencv_tester.py`
Also the command
Command: `python3 -m nuitka --include-data-file=/home/austin/miniconda3/lib/python3.9/site-packages/cv2/config.py  --follow-imports --static-libpython=no opencv_tester.py`

* Provide in your issue the Nuitka options used

1. --follow-imports
2. --include-data-file
3. --static-libpython=no

* Error during `./opencv_tester.py`
```
['/home/austin/Documents/tmp/ws/src/opencv_test', '/home/austin/miniconda3/lib/python3.9/site-packages/cv2', '/home/austin/Documents/tmp/ws/install/velodyne_msgs/lib/python3.10/site-packages', '/home/austin/Documents/tmp/ws/install/swift_pgm2/lib/python3.10/site-packages', '/home/austin/Documents/tmp/ws/install/phidgets_msgs/lib/python3.10/site-packages', '/home/austin/Documents/tmp/ws/install/optical_capture/lib/python3.10/site-packages', '/home/austin/Documents/tmp/ws/install/interfaces/lib/python3.10/site-packages', '/home/austin/Documents/tmp/ws/install/geojson_msgs/lib/python3.10/site-packages', '/home/austin/Documents/tmp/ws/install/commander/lib/python3.10/site-packages', '/home/austin/Documents/tmp/ws/install/breadcrumbs_msgs/lib/python3.10/site-packages', '/home/austin/Documents/tmp/ws/install/api_interfaces/lib/python3.10/site-packages', '/opt/ros/humble/lib/python3.10/site-packages', '/opt/ros/humble/local/lib/python3.10/dist-packages', '/home/austin/miniconda3/lib/python39.zip', '/home/austin/miniconda3/lib/python3.9', '/home/austin/miniconda3/lib/python3.9/lib-dynload', '/home/austin/miniconda3/lib/python3.9/site-packages']
Traceback (most recent call last):
  File "/home/austin/Documents/tmp/ws/src/opencv_test/opencv_tester.py", line 2, in <module>
    import cv2 as cv
  File "/home/austin/miniconda3/lib/python3.9/site-packages/cv2/__init__.py", line 181, in <module cv2>
    bootstrap()
  File "/home/austin/miniconda3/lib/python3.9/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/home/austin/miniconda3/lib/python3.9/site-packages/cv2/__init__.py", line 181, in <module cv2>
    bootstrap()
  File "/home/austin/miniconda3/lib/python3.9/site-packages/cv2/__init__.py", line 76, in bootstrap
    raise ImportError('ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.')
ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.

```

**Comment by kayhayen** [comment]
It may only work in standalone mode, mixes compilation is known to work badly. This also should be some sort of `options` hint in the yaml file, that some things will not work to be included in accelerated mode.

**Comment by austin-InDro** [comment]
Thanks for the quick reply @kayhayen, which yaml file are you talking about?

**Comment by kayhayen** [comment]
In https://github.com/Nuitka/Nuitka/blob/develop/nuitka/plugins/standard/standard.nuitka-package.config.yml we have a bunch of configuration for missing DLLs, code changes, etc. and also warnings to be given for options that are missing. You not using standalone should be warned against for packages like cv2, which do require things of Nuitka that are currently not implemented (loading bytecode and source from disk into compiled packages).

**Comment by austin-InDro** [comment]
Thanks @kayhayen, I may not be able to come back to this for a few weeks. Please feel free to close the issue in you'd like.

**Comment by kayhayen** [comment]
Closing for lack of feedback.
