### ISSUE TITLE
importlib.metadata.PackageNotFoundError when using pydantic-argparse

### ISSUE THREAD

**Issue by carles-protopixel** [Nuitka/Nuitka#1861]
Hello,
I am encountering a variation of #1793, which seemed to be solved in `1.1` . Importing `pydantic_argparse` will fail with `importlib.metadata.PackageNotFoundError: pydantic-argparse`.

* Nuitka version, full Python version, flavor, OS, etc. as output by _this_ command.

  > python -m nuitka --version

```
1.1.6
Commercial: None
Python: 3.9.13 (main, Oct 19 2022, 16:06:06)
Flavor: Unknown
Executable: /tmp/env/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 18.04.5
```

* How did you install Nuitka and Python

I am using `pyenv` to install Python 3.9.13. I am using `venv` to create a clean environment.

* The specific PyPI names and versions

  > python -m pip freeze

```
Nuitka==1.1.6
pydantic==1.10.2
pydantic-argparse==0.6.0
typing_extensions==4.4.0
```

* Example

```
# file: program.py
import pydantic_argparse

print("hello")
```

After compilation, the execution stops with this error:

```
Traceback (most recent call last):
  File "/tmp/program.dist/program.py", line 1, in <module>
  File "/tmp/program.dist/pydantic_argparse/__init__.py", line 12, in <module pydantic_argparse>
  File "/tmp/program.dist/pydantic_argparse/__version__.py", line 18, in <module pydantic_argparse.__version__>
  File "/tmp/program.dist/importlib/metadata.py", line 559, in metadata
  File "/tmp/program.dist/importlib/metadata.py", line 196, in from_name
importlib.metadata.PackageNotFoundError: pydantic_argparse
```

[The line that triggers this](https://github.com/SupImDos/pydantic-argparse/blob/v0.6.0/pydantic_argparse/__version__.py#L18) inside `pydantic_argparse` is:

```
__title__: str = metadata.metadata(__package__)["name"]
```

* Provide in your issue the Nuitka options used

```
python -m nuitka --standalone --follow-imports program.py
```

* Note if this is a regression

This does not seem to be a regression, the bug is present in 0.9, 1.0.8, 1.1.5 and 1.1.6

**Comment by carles-protopixel** [comment]
I edited the description as it was referring to a similar issue (#1745), but not the one I was thinking of (#1793).

**Comment by kayhayen** [comment]
i don't get what could be causing this. Code looks very innocent and should be covered, as a hard import with compile time resolution.

**Comment by kayhayen** [comment]
So, there is a mismatch between the distribution name, and the package name. Nuitka correctly conserves the distribution object, but in order create find things like a runtime path of it, it searches for the name inside the embedded modules, and `pydantic-argparse` is not one of them, but somehow it was resolved to that.

I need to figure out where that is happening, and if a trivial `-` -> `_` replacement will generally work, or if there is another thing to persist, namely the package name to use for internal lookup.

**Comment by kayhayen** [comment]
Actually, we were using the metadata name, and just need to keep track of the original name and use that instead, then it works.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
This is hotfix material, but there might be no 1.1.8,since 1.2 is right around the corner.

**Comment by carles-protopixel** [comment]
Thanks for the amazingly quick fix! I confirm that this is working using factory branch.

**Comment by kayhayen** [comment]
Part of the current 1.1.8 hotfix release that I just made.
