### ISSUE TITLE
Nutika wrongly raises exceptions for bytes() and bytearray() with keyword arguments

### ISSUE THREAD

**Issue by bazbar** [Nuitka/Nuitka#187]
*  Nuitka 0.6.0.5, Python 3.7.0 and Platform Windows
   python -m nuitka --version

*  How did you install Nuitka and Python 
   Nuitka via pip, Python via exe from python.org.  No virtualenv

*  `bytes ("some string", encoding="UTF8")` should be equivalent to 
`"some string".encode(encoding="UTF8")`, but isn't.  

The former results in a warning:

> Nuitka:WARNING:<module:line>: Will always raise exception: "TypeError(bytes() takes no keyword arguments)

and seems to cause an exception as well.

Thanks for the fantastic Nuitka!

**Comment by kayhayen** [comment]
I think some built-ins lost there support for keyword arguments at some point, and this was added to nuitka to comply with it:

```
if python_version < 370:
    builtin_float_spec = BuiltinParameterSpec("float", ('x',), 1)
else:
    builtin_float_spec = BuiltinParameterSpecNoKeywords("float", ('x',), 1)
```

However, nothing like it has been done for `bytes`, it was always based on `bytearray` which seems also affected and not using the proper base class, `BuiltinParameterSpecNoKeywords` all the time.

I will change it and throw it at my buildbots, and make it part of a 0.6.0.7 release, the 0.6.0.6 is just out.

Yours,
Kay

**Comment by kayhayen** [comment]
Ah the nasty ness, the first argument cannot be a keyword argument, second and third can be, much like a `def bytes("string, *, encoding, errors"): ...` definition is supposed to work, but that never got implemented so far.

Currently for simulation of builtin calls, Nuitka uses keyword argument call style for all arguments with `**kw` or `*arglist` style, and has no support for that. However, I recall there is at least one of these for `ImportError` with Python3, which would need that too.

So this may not be quick at all it seems.

Yours,
Kay

**Comment by kayhayen** [comment]
Meh, confused keyword only with positional only, so this is easy and seems to work. Much like what's necessary for `int`  before Python 3.7 was the case:

```
if python_version < 370:
    builtin_int_spec = BuiltinParameterSpec("int", ('x', "base"), 2)
else:
    builtin_int_spec = BuiltinParameterSpecPosArgs("int", ('x', "base"), 2, 1)
```

So this is actually very easy indeed.

Yours,
Kay

**Comment by kayhayen** [comment]
The code currently is on the factory branch and will be part of the net hotfix release.

**Comment by bazbar** [comment]
Cool! Very fast bug squashing.  First time I've come across anything not working with Nuitka.

I guess I'll have the honour of closing this, then :-)
