### ISSUE TITLE
Issue 1814 fix is only on factory branch

### ISSUE THREAD

**Issue by interseba5** [Nuitka/Nuitka#1870]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version

1.1.7
Commercial: None
Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Python39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

* How did you install Nuitka and Python

Installed using pip

* The specific PyPI names and versions

pip 22.0.4 from c:\python39\lib\site-packages\pip (python 3.9)

```
python -m pip freeze
llvmlite==0.39.1
shap==0.41.0
```

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)
```Python
import shap
print('hello world')
```

* Provide in your issue the Nuitka options used

python -m nuitka --enable-plugin=numpy --nofollow-import-to=IPython,dask,tensorflow,keras,matplotlib --standalone main.py

### Explanation
A month ago i have report this [issue ](https://github.com/Nuitka/Nuitka/issues/1814)about a missing dll for the llvmlite package. This was fixed in the factory branch, i tested it and worked. Today i have updated to nuitka 1.1.7 main version and i have noticed that the fix wasnt there. 
In fact:
nuitka/plugins/standard/standard.nuitka-package.config.yml in factory branch
```yaml
...
- module-name: 'llvmlite.binding.ffi'
  dlls:
    - from_filenames:
        prefixes:
          - 'llvmlite'
          - 'libllvmlite'
 ...
```
And in nuitka/plugins/standard/standard.nuitka-package.config.yml in main branch there aren't those lines of code

**Comment by kayhayen** [comment]
I do not quite accept this kind of report really, it's in develop too FWIW.
