### ISSUE TITLE
Pin to taskbar does not work as expected when compyling with --onefile option

### ISSUE THREAD

**Issue by spalbird** [Nuitka/Nuitka#1875]
> pip list | grep -i nuitka
Nuitka 1.1.8

**Pin to taskbar does not work as expected when compyling with --onefile option**

    After quitting the program the pinned link is not accessible anymore.
    => The reason is the .exe is copied into a temporary folder and started from there.

_Linking the .exe by dragging to the taskbar does not work either, an command windows opens with error messages._

I am beginning to evaluate Nuitka and my experiences are from compiling an Tkinter About widget on Windows 10 and Python 3.10.

=> For a solution, I suggest to look at pyinstaller which also uses a temporary folder for --onefile compiles where pin to taskbar works as expected.

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun.
