### ISSUE TITLE
Bytecode caching is not reusable due to different hash result for the same package

### ISSUE THREAD

**Issue by ilya-brykau** [Nuitka/Nuitka#1877]
Hi, i tried to use bytecode caching for azure modules and reuse the cache on different machines. But it results in nuitka not reuseing the cache as getModuleImportableFilesHash() produces a different hash value. Even though Windows, python version, nuitka version and dependencies are the same

Nuitka version, full Python version, flavor, OS, etc. as output by this
command.

`python -m nuitka --version`

```
1.1.5
Commercial: None
Python: 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\draas-recovery-agent\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

The specific PyPI names and versions
```
 astroid==2.8.6
attrs==21.2.0
azure-common==1.1.28
azure-core==1.24.2
azure-identity==1.10.0
azure-mgmt-compute==29.0.0
azure-mgmt-core==1.3.2
azure-mgmt-network==21.0.1
azure-sdk-trim @ git+https://github.com/clumio-code/azure-sdk-trim@530c5ca20d42e027b5d29bb244ea26701fd2ecdb
bottle==0.12.19
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.8
colorama==0.4.5
conan==1.44.0
coverage==6.5.0
cryptography==36.0.1
dataclasses-json==0.5.6
distro==1.6.0
fasteners==0.16.3
flake8==4.0.1
humanize==4.3.0
idna==3.3
inflection==0.5.1
iniconfig==1.1.1
isodate==0.6.1
isort==5.10.1
Jinja2==3.0.3
lazy-object-proxy==1.6.0
MarkupSafe==2.0.1
marshmallow==3.14.1
marshmallow-enum==1.5.1
mccabe==0.6.1
msal==1.18.0
msal-extensions==1.0.0
msrest==0.7.1
mypy==0.971
mypy-extensions==0.4.3
node-semver==0.6.1
Nuitka==1.1.5
oauthlib==3.2.0
orderedset==2.0.3
packaging==21.3
parameterized==0.8.1
patch-ng==1.17.4
platformdirs==2.4.0
pluggy==1.0.0
pluginbase==1.0.1
portalocker==2.5.1
psutil==5.8.0
py==1.11.0
py-zabbix==1.1.7
pycodestyle==2.8.0
pycparser==2.21
pyflakes==2.4.0
Pygments==2.10.0
PyJWT==1.7.1
pylint==2.11.1
pyOpenSSL==21.0.0
pyparsing==3.0.6
pytest==6.2.5
pytest-cov==3.0.0
pytest-random-order==1.0.4
python-dateutil==2.8.2
python-json-logger==2.0.2
PyYAML==5.4.1
requests==2.26.0
requests-oauthlib==1.3.1
responses==0.16.0
six==1.16.0
teamcity-messages==1.29
toml==0.10.2
tomli==1.2.2
tqdm==4.62.3
types-cryptography==3.3.14
types-enum34==1.1.3
types-ipaddress==1.0.3
types-pyOpenSSL==21.0.3
types-requests==2.26.1
typing-inspect==0.7.1
typing_extensions==4.0.1
urllib3==1.26.7
wrapt==1.13.3
```
Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)
Checked hash produces for azure.mgmt.compute module and compared it during runs. The result was different. My assumption is that getPackageSearchPath(None) affects the hash result

Provide in your issue the Nuitka options used
`--standalone --remove-output --nofollow-import-to=azure.mgmt.compute.v2015_06_15 --nofollow-import-to=azure.mgmt.compute.v2016_03_30 --nofollow-import-to=azure.mgmt.compute.v2016_04_30_preview --nofollow-import-to=azure.mgmt.compute.v2017_03_30 --nofollow-import-to=azure.mgmt.compute.v2017_09_01 --nofollow-import-to=azure.mgmt.compute.v2018_04_01 --nofollow-import-to=azure.mgmt.compute.v2018_06_01 --nofollow-import-to=azure.mgmt.compute.v2018_09_30 --nofollow-import-to=azure.mgmt.compute.v2018_10_01 --nofollow-import-to=azure.mgmt.compute.v2019_03_01 --nofollow-import-to=azure.mgmt.compute.v2019_04_01 --nofollow-import-to=azure.mgmt.compute.v2019_07_01 --nofollow-import-to=azure.mgmt.compute.v2019_11_01 --nofollow-import-to=azure.mgmt.compute.v2019_12_01 --nofollow-import-to=azure.mgmt.compute.v2020_05_01 --nofollow-import-to=azure.mgmt.compute.v2020_06_01 --nofollow-import-to=azure.mgmt.compute.v2020_06_30 --nofollow-import-to=azure.mgmt.compute.v2020_09_30 --nofollow-import-to=azure.mgmt.compute.v2020_10_01_preview --nofollow-import-to=azure.mgmt.compute.v2020_12_01 --nofollow-import-to=azure.mgmt.compute.v2021_03_01 --nofollow-import-to=azure.mgmt.compute.v2021_08_01 --nofollow-import-to=azure.mgmt.compute.v2021_10_01 --nofollow-import-to=azure.mgmt.compute.v2021_11_01 --nofollow-import-to=azure.mgmt.compute.v2021_12_01 --nofollow-import-to=azure.mgmt.compute.v2022_01_03 --nofollow-import-to=azure.mgmt.compute.v2022_03_02 --nofollow-import-to=azure.mgmt.network.v2015_06_15 --nofollow-import-to=azure.mgmt.network.v2016_09_01 --nofollow-import-to=azure.mgmt.network.v2016_12_01 --nofollow-import-to=azure.mgmt.network.v2017_03_01 --nofollow-import-to=azure.mgmt.network.v2017_06_01 --nofollow-import-to=azure.mgmt.network.v2017_10_01 --nofollow-import-to=azure.mgmt.network.v2018_01_01 --nofollow-import-to=azure.mgmt.network.v2018_02_01 --nofollow-import-to=azure.mgmt.network.v2018_04_01 --nofollow-import-to=azure.mgmt.network.v2018_06_01 --nofollow-import-to=azure.mgmt.network.v2018_07_01 --nofollow-import-to=azure.mgmt.network.v2018_08_01 --nofollow-import-to=azure.mgmt.network.v2018_10_01 --nofollow-import-to=azure.mgmt.network.v2018_11_01 --nofollow-import-to=azure.mgmt.network.v2018_12_01 --nofollow-import-to=azure.mgmt.network.v2019_04_01 --nofollow-import-to=azure.mgmt.network.v2019_06_01 --nofollow-import-to=azure.mgmt.network.v2019_08_01 --nofollow-import-to=azure.mgmt.network.v2019_09_01 --nofollow-import-to=azure.mgmt.network.v2019_11_01 --nofollow-import-to=azure.mgmt.network.v2019_12_01 --nofollow-import-to=azure.mgmt.network.v2020_03_01 --nofollow-import-to=azure.mgmt.network.v2020_05_01 --nofollow-import-to=azure.mgmt.network.v2020_07_01 --nofollow-import-to=azure.mgmt.network.v2020_08_01 --nofollow-import-to=azure.mgmt.network.v2020_11_01 --nofollow-import-to=azure.mgmt.network.v2021_02_01 --include-package=log --enable-plugin=pylint-warnings --enable-plugin=anti-bloat --noinclude-pytest-mode=nofollow --lto=no --msvc=latest --output-dir=C:\draas-recovery-agent\.temp\compile C:\draas-recovery-agent\src\unified_entry.py`

**Comment by kayhayen** [comment]
The follow options also take patterns, which it seems you may benefit from. Also, what are the imports of azure that I should use to benefit from? Also can you retry using the 1.2 version?

**Comment by ilya-brykau** [comment]
@kayhayen Here is an example of working imports
Compute imports available: 
`from azure.mgmt.compute.v2017_12_01.models import OperationStatusResponse
from azure.mgmt.compute.v2021_04_01.models import (
    BootDiagnostics,
    CreationData,
    DataDisk,
    DiagnosticsProfile,
    Disk,
    DiskCreateOption,
    DiskCreateOptionTypes,
    DiskSku,
    DiskStorageAccountTypes,
    HardwareProfile,
    HyperVGeneration,
    InstanceViewStatus, ManagedDiskParameters,
    NetworkInterfaceReference,
    NetworkProfile,
    OperatingSystemTypes,
    OSDisk,
    StorageProfile,
    VirtualMachine,
    VirtualMachineInstanceView, VirtualMachineSizeTypes,
)`
Network imports available:
`from azure.mgmt.network.v2022_01_01.models import (
    AddressSpace,
    IPConfiguration,
    NetworkInterface,
    NetworkSecurityGroup,
    PublicIPAddress,
    PublicIPAddressSku,
    SecurityRule,
    SecurityRuleAccess,
    SecurityRuleDirection,
    SecurityRuleProtocol,
    Subnet,
    VirtualNetwork,
    PublicIPAddressSkuName,
    IPAllocationMethod,
    IPVersion,
)`

**Comment by kayhayen** [comment]
Right now it doesn't work when filenames change. From `sys.path` they often come absolute. What should be done is to instead get the list of importable module names. However, that too is kind of explosive and regressive when something like a current directory or a large repository enters the game, since any directory is a package, etc. and ideally this would instead be based on modules actually attempted to be imported by a module considered for caching. So if a module only imports `os` and fails to import say `importlib_metadata` and that would still be the case, what gives. We would just have to retry those.

Since we do have the list of imports done, and its actually used as part of the caching too, we may just try those again and make the result or non-result part of the hash value. This will also increase the hit rate of the thing tremendously.

I am not sure when, but there should be a live stream late november again. This could be something we do there. It would be a very nice subject.

**Comment by ilya-brykau** [comment]
@kayhayen Any updates on this issue?

**Comment by kayhayen** [comment]
There have been no streams yet, but maybe later this month.

**Comment by kayhayen** [comment]
The import findings are now stored in the cache, and filenames are produced by locating the cached module names, and cache is discarded if the same things cannot be found. The cache is now based on the source code, configuration used, and the module name. So this is already solved by PRs of @Fire-Cube and me.
