### ISSUE TITLE
Huge Filesizes

### ISSUE THREAD

**Issue by ohitstom** [Nuitka/Nuitka#1881]
Versions:
```
1.1.6
Commercial: None
Python: 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: D:\Users\tomfi\AppData\Local\Programs\Python\Python39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```
* Output-
None as it compiled successfully.

* How did you install Nuitka and Python-
I installed nuitka over pip and python using their executable.

* The specific PyPI names and versions-
`numpy: 1.22.2`

* Provide in your issue the Nuitka options used-
`nuitka --onefile --include-plugin-directory=modules --enable-plugin=numpy main.py`

* Dependencies:
```
aiohttp==3.8.3
msal==1.20.0
pandas==1.5.1
pandas_stubs==1.2.0.53
pyperclip==1.8.2
requests==2.28.1
```

* Screenshots-
1 - Code size
![image](https://user-images.githubusercontent.com/22730962/201214345-7aeb46a0-394c-4fb1-8c2f-b6ab78302e97.png)
2 - executable size.
![image](https://user-images.githubusercontent.com/22730962/201214240-4a317af0-46c6-4c80-9efc-42f102de03f2.png)

**Comment by kayhayen** [comment]
So, you expect the compiled binary to be smaller than the code? And to magically shrink the numpy DLLs out of existance? I am not sure I am getting the issue here, you have of course also failed to provide a minimal example as well, so I consider this as invalid.
