### ISSUE TITLE
Cannot run app with folium - branca package can't be imported

### ISSUE THREAD

**Issue by apwebber** [Nuitka/Nuitka#1882]
I get the following error when running a nuitka-compiled PySide6 app with Folium, displaying in a QWebEngineView:

```
Traceback (most recent call last):
  File "C:\Users\XXX\ONEDRI~1\DOCUME~1\python\MYPACK~1\SCANNE~1\GQR~1.DIS\GQr.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\XXX\ONEDRI~1\DOCUME~1\python\MYPACK~1\SCANNE~1\GQR~1.DIS\downloader\__init__.py", line 3, in <module downloader>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\XXX\ONEDRI~1\DOCUME~1\python\MYPACK~1\SCANNE~1\GQR~1.DIS\branca\__init__.py", line 1, in <module branca>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\XXX\ONEDRI~1\DOCUME~1\python\MYPACK~1\SCANNE~1\GQR~1.DIS\branca\colormap.py", line 15, in <module branca.colormap>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\XXX\ONEDRI~1\DOCUME~1\python\MYPACK~1\SCANNE~1\GQR~1.DIS\branca\element.py", line 23, in <module branca.element>
  File "C:\Users\XXX\ONEDRI~1\DOCUME~1\python\MYPACK~1\SCANNE~1\GQR~1.DIS\jinja2\loaders.py", line 323, in __init__
ValueError: The 'branca' package was not installed in a way that PackageLoader understands.
```

Removing Folium from the application allows it to run. Branca is a Folium dependency.

* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

1.2 (also tested with stable release)
Commercial: None
Python: 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\alex.webber\Envs\scanner-env\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

* How did you install Nuitka and Python

pip install nuitka into venv

* The specific PyPI names and versions

autoflake==1.7.7
branca==0.5.0
CacheControl==0.12.11
cachetools==5.2.0
certifi==2022.6.15
cffi==1.15.1
charset-normalizer==2.1.1
colorama==0.4.5
configparser-crypt==0.6.2
cryptidy==1.1.0
cryptography==37.0.4
Deprecated==1.2.13
et-xmlfile==1.1.0
firebase-admin==5.3.0
folium==0.12.1.post1
google-api-core==2.8.2
google-api-python-client==2.58.0
google-auth==2.11.0
google-auth-httplib2==0.1.0
google-cloud-core==2.3.2
google-cloud-firestore==2.6.1
google-cloud-storage==2.5.0
google-crc32c==1.3.0
google-resumable-media==2.3.3
googleapis-common-protos==1.56.4
greenlet==1.1.3
grpcio==1.47.0
grpcio-status==1.47.0
httplib2==0.20.4
idna==3.3
Jinja2==3.1.2
jwcrypto==1.3.1
MarkupSafe==2.1.1
msgpack==1.0.4
Nuitka @ https://github.com/Nuitka/Nuitka/archive/develop.zip (also tried with the current stable version)
numpy==1.23.2
oauth2client==4.1.3
openpyxl==3.0.10
ordered-set==4.1.0
orderedset==2.0.3
pandas==1.4.3
Pillow==9.2.0
proto-plus==1.22.1
protobuf==4.21.5
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pycryptodome==3.15.0
pycryptodomex==3.15.0
pyflakes==2.5.0
pyodbc==4.0.34
pyparsing==3.0.9
PySide6==6.4.0.1
PySide6-Addons==6.4.0.1
PySide6-Essentials==6.4.0.1
python-dateutil==2.8.2
pytz==2022.2.1
pywin32==304
qrcode==7.3.1
reportlab==3.6.11
requests==2.28.1
rsa==4.9
shiboken6==6.4.0.1
sigfig==1.3.2
six==1.16.0
sortedcontainers==2.4.0
SQLAlchemy==1.4.40
sqlalchemy-access==1.1.3
tomli==2.0.1
uritemplate==4.1.1
urllib3==1.26.12
wrapt==1.14.1

* Many times when you get an error from Nuitka, your setup may be special

No issue running and compiling without Folium

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

```
import io
import sys

import folium
from PySide6 import QtWidgets
from PySide6.QtWebEngineWidgets import QWebEngineView


class MainWindow(QtWidgets.QMainWindow):

    
    def __init__(self, *args, **kwargs):
        super(MainWindow, self).__init__(*args, **kwargs)
        
        self.resize(600, 500)
        
        self.browser = QWebEngineView()
        self.setCentralWidget(self.browser)
        
        self.create_map()
        
    def create_map(self):
        """Create a map of the world and display in browser"""
        
        world_map= folium.Map(tiles="cartodbpositron")
        
        data = io.BytesIO()
        world_map.save(data, close_file=False)
        self.browser.setHtml(data.getvalue().decode())
        
def main():
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())
    
    
if __name__ == '__main__':
    main()
```

* Provide in your issue the Nuitka options used

```
nuitka folium_test.py --show-progress --standalone --plugin-enable=pyside6^
 --windows-product-name="test"^
 --windows-company-name="test"^
 --windows-product-version=0.0.1^
 --windows-file-description="test"^
 --report=compilation-report.xml
```

**Comment by kayhayen** [comment]
This rings a bell, I feel I had this before, and for that, I think `pkg_resources` is now registering the meta path based loader of Nuitka, however this has either regressed or Jinja2 has changed yet again. Likely it is because of Anaconda Python though, and CPython would work. I will have to check it out.

**Comment by kayhayen** [comment]
Trying with CPython, it's complaining about missing data files, I am adding configuration for branca, to also include the templates, I guess, that's all missing here. The Jinja2 error for missing template may just be misleading. These people who convert file not found errors to something they believe might be the case... looks like this should be solvable in a hotfix.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by apwebber** [comment]
Thanks @kayhayen, tested working!

**Comment by kayhayen** [comment]
This is already part of the current hotfixes.
