### ISSUE TITLE
RISC-V baremetal standalone binary not really statically linked

### ISSUE THREAD

**Issue by gnodipac886** [Nuitka/Nuitka#1885]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

1.2
Commercial: None
Python: 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]
Flavor: Debian Python
Executable: /usr/bin/python3
OS: Linux
Arch: riscv64
Distribution: Ubuntu (based on Debian) 22.04.1

* How did you install Nuitka and Python

`pip3 install nuitka`
no venv

* The specific PyPI names and versions

no packages, literally `print("Hello World!")`

* Many times when you get an error from Nuitka, your setup may be special

very special, print hello world doesn't work yet

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

`print("Hello World!")`

* Provide in your issue the Nuitka options used

I've tried both --standalone and --onefile

***the issue***:
- Environment: qemu riscv-64 VM running ubuntu 22.04
- Target Python File: `print("Hello World!")`
- Goal: Get a statically linked binary file able to run on RISC-V CPU without linux
- Current Status: When I simulate the binary using spike ([risc-v isa simulator](https://github.com/riscv-software-src/riscv-isa-sim)) the output suggests the the resulting binary file is not a proper elf file, and suggests that its not statically linked. When I vim the executable there's ELF in the beginning of the file.

My Nuitka command line to compile, these are run in the QEMU VM and are successful:
`python3 -m nuitka --onefile test.py` and
`python3 -m nuitka --standalone test.py`

Here's the output to `spike test`
`spike: ../fesvr/elfloader.cc:36: std::map<std::__cxx11::basic_string<char>, long unsigned int> load_elf(const char*, memif_t*, reg_t*): Assertion 'IS_ELF_EXEC(*eh64)' failed.`

`bbl loader;
not a statically linked ELF program`

Any thoughts?
Thanks in advance :)

**Comment by kayhayen** [comment]
If you want static linking, i.e. no DLLs, make sure to use Nuitka Python and Nuitka in conjunction. Check out the Discord Server as linked on the main site for a channel dedicated to it.
