### ISSUE TITLE
can you explain about certifi in folder.dist

### ISSUE THREAD

**Issue by hossain93** [Nuitka/Nuitka#1888]
hi every body
I search in the internet and I cant find a explain for certifi .
because I want delete it and I don't know when I delete it my exe file work correct or not.
excuse me for this question
thanks for good your module

**Comment by kayhayen** [comment]
It contains a data file needed, I believe a SSL certificate. Only with Nuitka commercial and its file embedding you could have it included in your binary.

In Pythin if you talk to a website with any package really and want to use SSL or may use SSL, it will crash without the file.

https://nuitka.net/doc/commercial/protect-data-files.html
