### ISSUE TITLE
no exe generate after using option --standalone

### ISSUE THREAD

**Issue by woshichuanqilz** [Nuitka/Nuitka#189]
Here is the output. Without the standalone option, I can get the exe file. 
With standalone, after execuate the command `@C:\Python36\python.exe -m nuitka --standalone --windows-icon=ico_dnf.ico login_gui.py` no exe file generated. Why is this?  

> @C:\Python36\python.exe -m nuitka --standalone --windows-icon=ico_dnf.ico login_gui.py
Nuitka:WARNING:Use '--plugin-enable=multiprocessing' for: Multiprocessing workarounds for compiled code on Windows.
Nuitka:WARNING:login_gui.py:18: Cannot find 'Tkinter' as absolute import.
Nuitka:WARNING:login_gui.py:23: Cannot find 'ttk' as absolute import.
Nuitka:WARNING:C:\Python36\lib\site-packages\numpy\testing\_private\pytesttester.py:125: Cannot find 'pytest' in package 'numpy.testing._private' as absolute import (tried pytest).
Nuitka:WARNING:C:\Python36\lib\site-packages\setuptools\command\egg_info.py:20: Cannot find 'setuptools.extern.six.moves' in package 'setuptools.command' as absolute import (tried setuptools.extern.six.moves).
Nuitka:WARNING:C:\Python36\lib\site-packages\setuptools\command\egg_info.py:20: Cannot find 'setuptools.extern.six' in package 'setuptools.command' as absolute import (tried setuptools.extern.six).
Nuitka:WARNING:C:\Python36\lib\site-packages\setuptools\namespaces.py:5: Cannot find 'setuptools.extern.six.moves' in package 'setuptools' as absolute import (tried setuptools.extern.six.moves).
Nuitka:WARNING:C:\Python36\lib\site-packages\setuptools\namespaces.py:5: Cannot find 'setuptools.extern.six' in package 'setuptools' as absolute import (tried setuptools.extern.six).
Nuitka:WARNING:C:\Python36\lib\site-packages\numpy\f2py\diagnose.py:51: Cannot find 'numpy_distutils' in package 'numpy.f2py' as absolute import (tried numpy_distutils).
Nuitka:WARNING:C:\Python36\lib\site-packages\numpy\f2py\diagnose.py:91: Cannot find 'numpy_distutils.command.build_flib' in package 'numpy.f2py' as absolute import (tried numpy_distutils.command.build_flib).
Nuitka:WARNING:C:\Python36\lib\site-packages\numpy\f2py\diagnose.py:91: Cannot find 'numpy_distutils.command' in package 'numpy.f2py' as absolute import (tried numpy_distutils.command).
Nuitka:WARNING:C:\Python36\lib\site-packages\numpy\f2py\diagnose.py:113: Cannot find 'numpy_distutils.fcompiler' in package 'numpy.f2py' as absolute import (tried numpy_distutils.fcompiler).
Nuitka:WARNING:C:\Python36\lib\site-packages\numpy\f2py\diagnose.py:136: Cannot find 'numpy_distutils.command.cpuinfo' in package 'numpy.f2py' as absolute import (tried numpy_distutils.command.cpuinfo).
Nuitka:WARNING:C:\Python36\lib\site-packages\numpy\f2py\diagnose.py:142: Cannot find 'numpy_distutils.cpuinfo' in package 'numpy.f2py' as absolute import (tried numpy_distutils.cpuinfo).
Nuitka:WARNING:C:\Python36\lib\site-packages\numpy\distutils\system_info.py:133: Cannot find 'ConfigParser' in package 'numpy.distutils' as absolute import (tried ConfigParser).
Nuitka:WARNING:C:\Python36\lib\site-packages\numpy\distutils\system_info.py:2115: Cannot find 'Numeric' in package 'numpy.distutils' as absolute import (tried Numeric).
Nuitka:WARNING:C:\Python36\lib\site-packages\numpy\distutils\system_info.py:2120: Cannot find 'numarray' in package 'numpy.distutils' as absolute import (tried numarray).
Nuitka:WARNING:C:\Python36\lib\site-packages\numpy\f2py\__version__.py:6: Cannot find '__svn_version__' in package 'numpy.f2py' as absolute import (tried __svn_version__).
Nuitka:WARNING:C:\Python36\lib\site-packages\setuptools\config.py:10: Cannot find 'setuptools.extern.packaging.version' in package 'setuptools' as absolute import (tried setuptools.extern.packaging.version).
Nuitka:WARNING:C:\Python36\lib\site-packages\setuptools\config.py:10: Cannot find 'setuptools.extern.packaging' in package 'setuptools' as absolute import (tried setuptools.extern.packaging).
Nuitka:WARNING:C:\Python36\lib\site-packages\setuptools\wheel.py:12: Cannot find 'setuptools.extern.packaging.utils' in package 'setuptools' as absolute import (tried setuptools.extern.packaging.utils).
Nuitka:WARNING:C:\Python36\lib\site-packages\setuptools\pep425tags.py:152: Cannot find '_manylinux' in package 'setuptools' as absolute import (tried _manylinux).
Nuitka:WARNING:C:\Python36\lib\site-packages\setuptools\ssl_support.py:45: Cannot find 'backports.ssl_match_hostname' in package 'setuptools' as absolute import (tried backports.ssl_match_hostname).
Nuitka:WARNING:C:\Python36\lib\site-packages\setuptools\ssl_support.py:45: Cannot find 'backports' in package 'setuptools' as absolute import (tried backports).
Nuitka:WARNING:C:\Python36\lib\site-packages\setuptools\sandbox.py:18: Cannot find 'org.python.modules.posix.PosixModule' in package 'setuptools' as absolute import (tried org.python.modules.posix.PosixModule).
Nuitka:WARNING:C:\Python36\lib\site-packages\setuptools\sandbox.py:18: Cannot find 'org.python.modules.posix' in package 'setuptools' as absolute import (tried org.python.modules.posix).
Nuitka:WARNING:C:\Python36\lib\site-packages\setuptools\sandbox.py:18: Cannot find 'org.python.modules' in package 'setuptools' as absolute import (tried org.python.modules).
Nuitka:WARNING:C:\Python36\lib\site-packages\setuptools\sandbox.py:18: Cannot find 'org.python' in package 'setuptools' as absolute import (tried org.python).
Nuitka:WARNING:C:\Python36\lib\site-packages\setuptools\sandbox.py:18: Cannot find 'org' in package 'setuptools' as absolute import (tried org).
Nuitka:WARNING:C:\Python36\lib\site-packages\numpy\testing\_private\nosetester.py:246: Cannot find 'scipy' in package 'numpy.testing._private' as absolute import (tried scipy).
Nuitka:WARNING:C:\Python36\lib\site-packages\numpy\testing\_private\nosetester.py:294: Cannot find 'nose.plugins.builtin' in package 'numpy.testing._private' as absolute import (tried nose.plugins.builtin).
Nuitka:WARNING:C:\Python36\lib\site-packages\numpy\testing\_private\nosetester.py:294: Cannot find 'nose.plugins' in package 'numpy.testing._private' as absolute import (tried nose.plugins).
Nuitka:WARNING:C:\Python36\lib\site-packages\numpy\testing\_private\nosetester.py:294: Cannot find 'nose' in package 'numpy.testing._private' as absolute import (tried nose).
Nuitka:WARNING:C:\Python36\lib\site-packages\numpy\testing\_private\noseclasses.py:17: Cannot find 'nose.plugins.errorclass' in package 'numpy.testing._private' as absolute import (tried nose.plugins.errorclass).
Nuitka:WARNING:C:\Python36\lib\site-packages\numpy\testing\_private\noseclasses.py:18: Cannot find 'nose.plugins.base' in package 'numpy.testing._private' as absolute import (tried nose.plugins.base).
Nuitka:WARNING:C:\Python36\lib\site-packages\numpy\testing\_private\noseclasses.py:19: Cannot find 'nose.util' in package 'numpy.testing._private' as absolute import (tried nose.util).
Nuitka:WARNING:C:\Python36\lib\site-packages\numpy\lib\npyio.py:32: Cannot find 'future_builtins' in package 'numpy.lib' as absolute import (tried future_builtins).
Nuitka:WARNING:C:\Python36\lib\site-packages\numpy\lib\_datasource.py:375: Cannot find 'urlparse' in package 'numpy.lib' as absolute import (tried urlparse).
Nuitka:WARNING:C:\Python36\lib\site-packages\numpy\lib\_datasource.py:398: Cannot find 'urllib2' in package 'numpy.lib' as absolute import (tried urllib2).
Nuitka:WARNING:C:\Python36\lib\site-packages\numpy\core\__init__.py:95: Cannot find 'copy_reg' in package 'numpy.core' as absolute import (tried copy_reg).
Nuitka:WARNING:C:\Python36\lib\site-packages\pyautogui\_pyautogui_x11.py:7: Cannot find 'Xlib.display' in package 'pyautogui' as absolute import (tried Xlib.display).
Nuitka:WARNING:C:\Python36\lib\site-packages\pyautogui\_pyautogui_x11.py:7: Cannot find 'Xlib' in package 'pyautogui' as absolute import (tried Xlib).
Nuitka:WARNING:C:\Python36\lib\site-packages\pyautogui\_pyautogui_x11.py:9: Cannot find 'Xlib.ext.xtest' in package 'pyautogui' as absolute import (tried Xlib.ext.xtest).
Nuitka:WARNING:C:\Python36\lib\site-packages\pyautogui\_pyautogui_x11.py:9: Cannot find 'Xlib.ext' in package 'pyautogui' as absolute import (tried Xlib.ext).
Nuitka:WARNING:C:\Python36\lib\site-packages\pyautogui\_pyautogui_x11.py:10: Cannot find 'Xlib.XK' in package 'pyautogui' as absolute import (tried Xlib.XK).
Nuitka:WARNING:C:\Python36\lib\site-packages\pyautogui\_pyautogui_osx.py:5: Cannot find 'Quartz' in package 'pyautogui' as absolute import (tried Quartz).
Nuitka:WARNING:C:\Python36\lib\site-packages\pyautogui\_pyautogui_osx.py:8: Cannot find 'AppKit' in package 'pyautogui' as absolute import (tried AppKit).
Nuitka:WARNING:C:\Python36\lib\site-packages\PIL\Image.py:136: Cannot find 'cffi' in package 'PIL' as absolute import (tried cffi).
Nuitka:WARNING:C:\Python36\lib\site-packages\PIL\Image.py:146: Cannot find 'pathlib2' in package 'PIL' as absolute import (tried pathlib2).
Nuitka:WARNING:C:\Python36\lib\site-packages\PIL\ImageQt.py:34: Cannot find 'PyQt5.QtGui' in package 'PIL' as absolute import (tried PyQt5.QtGui).
Nuitka:WARNING:C:\Python36\lib\site-packages\PIL\ImageQt.py:34: Cannot find 'PyQt5' in package 'PIL' as absolute import (tried PyQt5).
Nuitka:WARNING:C:\Python36\lib\site-packages\PIL\ImageQt.py:35: Cannot find 'PyQt5.QtCore' in package 'PIL' as absolute import (tried PyQt5.QtCore).
Nuitka:WARNING:C:\Python36\lib\site-packages\PIL\ImageQt.py:37: Cannot find 'PyQt4.QtGui' in package 'PIL' as absolute import (tried PyQt4.QtGui).
Nuitka:WARNING:C:\Python36\lib\site-packages\PIL\ImageQt.py:37: Cannot find 'PyQt4' in package 'PIL' as absolute import (tried PyQt4).
Nuitka:WARNING:C:\Python36\lib\site-packages\PIL\ImageQt.py:38: Cannot find 'PyQt4.QtCore' in package 'PIL' as absolute import (tried PyQt4.QtCore).
Nuitka:WARNING:C:\Python36\lib\site-packages\PIL\ImageQt.py:40: Cannot find 'PySide.QtGui' in package 'PIL' as absolute import (tried PySide.QtGui).
Nuitka:WARNING:C:\Python36\lib\site-packages\PIL\ImageQt.py:40: Cannot find 'PySide' in package 'PIL' as absolute import (tried PySide).
Nuitka:WARNING:C:\Python36\lib\site-packages\PIL\ImageQt.py:41: Cannot find 'PySide.QtCore' in package 'PIL' as absolute import (tried PySide.QtCore).
Nuitka:WARNING:C:\Python36\lib\site-packages\pymsgbox\__init__.py:49: Cannot find 'Tkinter' in package 'pymsgbox' as absolute import (tried Tkinter).
Nuitka:WARNING:C:\Python36\lib\site-packages\setuptools\dist.py:31: Cannot find 'setuptools.extern.packaging.specifiers' in package 'setuptools' as absolute import (tried setuptools.extern.packaging.specifiers).
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Python36\lib\site-packages\PIL\Image.py:418' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Python36\lib\site-packages\numpy\core\__init__.py:82' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Python36\lib\site-packages\numpy\lib\function_base.py:3917' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Python36\lib\site-packages\numpy\lib\utils.py:373' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Python36\lib\site-packages\numpy\lib\utils.py:868' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Python36\lib\site-packages\numpy\lib\utils.py:926' may require use of '--include-plugin-directory' or '--include-plugin-files'.

**Comment by kayhayen** [comment]
Can you provide the version outputs, this looks like older Nuitka somehow to me, otherwise I cannot see what would be the issue. It's not you overlooking that it creates a `.dist` folder with the binary contained, right?

**Comment by kayhayen** [comment]
There is a `login_gui.exe` right there. I agree the folder is crouded and #66 or #16 would solve that.

**Comment by woshichuanqilz** [comment]
@kayhayen  Thank you, the exe file without "--standalone" option generated under the root option, which make me forgot to search in the dist folder.
