### ISSUE TITLE
Segfault with custom `argparse` types

### ISSUE THREAD

**Issue by 0x446** [Nuitka/Nuitka#1892]
### System information
|Key|Value|
|---|---|
| Nuitka version  | 1.2.1 |
| Commercial | None |
| Python | 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] |
| Flavor | Unknown |
| Executable | C:\\...\venv\Scripts\python.exe |
| OS | Windows |
| Arch | x86_64 |
| WindowsRelease | 10 (Build: 2009.19044) |

### How did you install Nuitka and Python?
```shell
python -m venv venv
source ./venv/Scripts/activate
pip install nuitka ordered-set
deactivate
```

### The specific PyPI names and versions
```ini
Nuitka==1.2.1
ordered-set==4.1.0
```

### Reproducible application
[nuitka-argparse-segfault.zip](https://github.com/Nuitka/Nuitka/files/10033277/nuitka-argparse-segfault.zip)
Outputs of the application (all of them were ran in a Git Bash window; Git for Windows v2.38.1) :
```shell
# ./venv/Scripts/python.exe App.py -d "2022-01-01"
    Got arguments: Namespace(date=datetime.datetime(2022, 1, 1, 0, 0))
# ./venv/Scripts/python.exe App.py -d "2022-01-01 .. 2022-01-31"
    Got arguments: Namespace(date=(datetime.datetime(2022, 1, 1, 0, 0), datetime.datetime(2022, 1, 31, 0, 0)))
    
# App.exe -d "2022-01-01"
    Got arguments: Namespace(date=datetime.datetime(2022, 1, 1, 0, 0))
# App.exe -d "2022-01-01 .. 2022-01-31"
    Segmentation fault
```

### Nuitka build command
```shell
python -m nuitka \
  --mingw64 \
  --standalone \
  --warn-implicit-exceptions \
  --warn-unusual-code \
  --prefer-source-code \
  --follow-stdlib \
  --remove-output \
  --disable-bytecode-cache \
  --disable-ccache \
  --disable-dll-dependency-cache \
  --show-scons \
  --show-progress \
  --python-flag='-O' \
  --enable-plugin=anti-bloat \
  --enable-plugin=multiprocessing \
  --noinclude-pytest-mode=nofollow \
  --noinclude-setuptools-mode=nofollow \
  --output-dir='C:\nuitka-compile' \
  --windows-company-name='Nuitka' \
  --windows-product-name='App' \
  --windows-product-version='1.0.0' \
  --windows-file-description='App :: Description.' \
  App.py
```

### Possible regression?
I'm unsure about that as I never wrote that logic for another Nuitka version.

**Comment by kayhayen** [comment]
I managed to reproduce this on Linux just now, feels totally crazy.

**Comment by kayhayen** [comment]
So, this here:

```
        try:
            date: datetime = datetime.fromisoformat(data)
            return date
        except ValueError:
            pass
```

must be exposing a bug, maybe even a regression, the returning code later is convinced, that `date` must have a value, where in fact it must not have a value.

**Comment by kayhayen** [comment]
With returning code, I am refering to code that comes after this snippet.

**Comment by kayhayen** [comment]
Reduced it to this then, and of course it needed not be `datetime`, could be anything that raises.

```
from datetime import datetime

def f(data):
    try:
        date: datetime = datetime.fromisoformat(data)
        return date
    except ValueError:
        pass

f("a")
```

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working. 

This is very likely to lead to a hotfix 1.2.2, with a rebase once this is proven stable.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.2.2 that I just made.
