### ISSUE TITLE
why my program have conflict with screen recorder

### ISSUE THREAD

**Issue by hossain93** [Nuitka/Nuitka#1895]
Hi every body. when I run my exe file and also I want record from my screen but my exe file not work any way. I test three screen recorder and all of them have same result.
my module in my program are .

`import requests
import json
import hmac
import hashlib
import base64
from urllib.parse import urlencode
import time
import uuid
import datetime
import threading
from websocket import create_connection
import chime
import os
import sys
import socket
import base64
from Crypto.Cipher import AES
from Crypto.Hash import SHA256
from Crypto import Random`
I compile my code with:
`nuitka --standalone --assume-yes-for-downloads --remove-output --disable-dll-dependency-cache --plugin-enable=pylint-warnings --plugin-enable=numpy --plugin-enable=pkg-resources python_file.py`

when I test my program(exe) without screen recorder it work good and not have any problem. I test two way:
first run exe file then screen recorder and also first run screen recorder then run exe file . this two way don't solve my problem

I install nuitka with `pip3 install nuitka`
python --version : python 3.10.5

python -m nuitka --version :
1.2
Commercial: None
Python: 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\hossain\AppData\Local\Programs\Python\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

**Comment by kayhayen** [comment]
So you want me to guess which import does what and come up with my own program that demonstrates the failure? Please provide a minimal program that demonstrates the issue, or else I doubt that there is anything actionable.

**Comment by hossain93** [comment]
> So you want me to guess which import does what and come up with my own program that demonstrates the failure? Please provide a minimal program that demonstrates the issue, or else I doubt that there is anything actionable.

       ` x=1
        while x==1:
            time.sleep(0.05)
            while 1:
                time.sleep(0.05)
                try:
                    sp= json.load(open("entry_trader.json"))
                    break
                except Exception as error:
                    pass
            if (type(sp['stop_trail'])==int) and (type(sp['stopPrice_sl'])==int):
                if (sp['stop_trail']>0) or (sp['stopPrice_sl']>0):
                    while 1:
                        time.sleep(0.05)
                        try:
                            json.dump({"status":1}, open('get_ok.json','w'))
                            break
                        except Exception as error:
                            pass
                    self.sl_tp=sp
            for i in [*self.alive_positions]:
                self.detail_accuonts[i]['last_time']=str(datetime.datetime.utcnow())

            self.touched_sl=[*{key:value for key,value in self.alive_positions.items() if value['stopPrice_sl']>=self.price}]
            self.touched_st=[*{key:value for key,value in self.alive_positions.items() if value['stop_trail']<=self.price}]

            if (len(self.touched_sl)>0) or (self.sl_tp['stopPrice_sl']>0):
                
                self.touched_sl=[*self.alive_positions]
                print('touch sl')`

I have problem with this section of my code.
when I change value entry_trader and save my program get that value with json.load 
then it arrive to line `print('touch sl')` it can't show any thing< my mean is that don't work `print` and my exe locked and do not any work.

I test another program like below and my exe don't have any conflict with screen recorder

``

**Comment by kayhayen** [comment]
So, seriously, screenshots of code? I will report back when I am finishing typing it up.

**Comment by kayhayen** [comment]
You may want to try 1.2.2, I believe it has a regression fix that may affect the code you posted.
