### ISSUE TITLE
Can the packaged dependency directory be customized?

### ISSUE THREAD

**Issue by Nisekoi5** [Nuitka/Nuitka#1896]
hello ,I had a small problem with using it. My code imported a large number of pip libraries that didn't need to be repackaged, so I used '--nofollow-import-to' to get rid of them
I then copied them from the 'site-packages' directory into the application directory, and they worked just fine.
It's just that there are hundreds of files/folders in the program directory
Can I put them in a new folder and the application reads the dependencies from that folder? I'm going to assume his name is lib
I used 'sys.path.apped("./lib")' to add the directory to the search directory, but it still resulted in an error if an absolute import statement such as' from xxx import xxx 'was encountered

Is there a better way?  

This is a folder minimum example
```
├─lib # Move the dependency of the root directory here
│   ├─aiohttp
│   ├─.........
│   └─Other dependencies
└─main.exe
```
In addition, I created a repository
https://github.com/Nisekoi5/nuitka-Import-problem
The out folder is the compiled product of the command I used,
`nuitka --mingw64 --standalone --show-progress --show-memory --nofollow-import-to=requests --output-dir=out3.9_request run.py`
Running './out/run.exe 'directly should result in ModuleNotFoundError
At this point, if the http module that causes the error 'from http.cookies import Morsel' import statement is moved from the lib folder to the root directory, it will work fine

I use the pip installation
```
1.1.8
Commercial: None
Python: 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\N\AppData\Local\Programs\Python\Python39\python.exe     
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

**Comment by kayhayen** [comment]
Actually, manual copying of files for standalone is not supported at all, even where it happens to work, I have intentions to change Nuitka in ways that will disallow failed imports at compile time to work at runtime.  At that point, any advice for what you are doing will be invalid.

I will definitely not run executables provided to me outside of Nuitka commercial, I only care about source code.
