### ISSUE TITLE
QtMultimedia is not currently supported on this platform or compiler.

### ISSUE THREAD

**Issue by zqbxx** [Nuitka/Nuitka#1897]
```
python -m nuitka --version
1.1.7
Commercial: None
Python: 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: F:\python\venv\editor\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

```
pip list | findstr PySide                                                            
PySide6               6.4.0.1
PySide6-Addons        6.4.0.1
PySide6-Essentials    6.4.0.1
```

main.py
```
from PySide6.QtWidgets import QApplication
from PySide6.QtMultimedia import QMediaDevices
import sys


app = QApplication(sys.argv)
cameraList = QMediaDevices.videoInputs()
for i, cameraDevice in enumerate(cameraList):
    text = "Local  %d: %s" % (i, cameraDevice.description())
    print(text)
sys.exit(app.exec())
```

compile
`
nuitka --show-progress --standalone --follow-imports --enable-plugin=pyside6 main.py
`

run
```
main.exe
could not load multimedia backend ""
QtMultimedia is not currently supported on this platform or compiler.
```
msys2/MINGW-packages#9736 is a similar issue, but i don't know how to use it
PyInstaller has similar problem with pyqt6 https://stackoverflow.com/questions/74415173/qtmultimedia-is-not-currently-supported-on-this-platform-or-compiler-pyinstalle

**Comment by zqbxx** [comment]
msvc has same problem

`nuitka --show-progress --standalone --follow-imports --msvc=14.3 --enable-plugin=pyside6 main.py`

remove compiler installed by nuitka, and use lastes mingw `llvm-mingw-20220906-msvcrt-x86_64` has same problem

`nuitka --show-progress --standalone --follow-imports --mingw64 --enable-plugin=pyside6 main.py`

**Comment by kayhayen** [comment]
Did you consider selecting the Qt plugins to include? I am assuming, these do not fall into the default sensible subset picked, try all with --include-qt-plugins and then narrow down.

**Comment by zqbxx** [comment]
> Did you consider selecting the Qt plugins to include? I am assuming, these do not fall into the default sensible subset picked, try all with --include-qt-plugins and then narrow down.

I can not find document about `include-qt-plugins` in  `nuitka --help `. 

So I guess the option should be `--include-qt-plugins=multimedia`. 

But it still has problem.

```
main.exe
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

**Comment by zqbxx** [comment]
> > Did you consider selecting the Qt plugins to include? I am assuming, these do not fall into the default sensible subset picked, try all with --include-qt-plugins and then narrow down.
> 
> I can not find document about `include-qt-plugins` in `nuitka --help `.
> 
> So I guess the option should be `--include-qt-plugins=multimedia`.
> 
> But it still has problem.
> 
> ```
> main.exe
> qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> ```

DLL files missing. 

Set variable QT_QPA_PLATFORM_PLUGIN_PATH before running the program can avoid this problem

```
set QT_QPA_PLATFORM_PLUGIN_PATH=F:\python\venv\editor\Lib\site-packages\PySide6\plugins\platforms
main.exe
Local  0: USB Camera
Local  1: USB2.0 Camera
```
https://answers.ros.org/question/354707/qtqpaplugin-could-not-find-the-qt-platform-plugin-windows-in/

**Comment by kayhayen** [comment]
You need to read the documentation more carefully. Including only the multimedia plugin doesn't cut it, it won't even launch any Qt without the platform plugin.

**Comment by zqbxx** [comment]
> 
upgrade to nuitka 1.2.2

`pip install -U Nuitka`

`nuitka --help | findstr include-qt-plugins` output nothing

[Here](https://nuitka.net/doc/user-manual.html#nuitka-options-in-the-code) is the document mentioned `include-qt-plugins`, but no information about how to use this option

Is there any document about this option? I can't find that.

**Comment by kayhayen** [comment]
The help output is all there is. You basically have to know what it is, or use `all` which of course will become big.

**Comment by kayhayen** [comment]
Did you have a chance to try it?

**Comment by kayhayen** [comment]
Closing for lack of feedback.

**Comment by Sun-ZhenXing** [comment]
> The value `sensible,multimedia` might be more what you want.

```yml
PySide6: 6.5.3
Nuitka:  1.8.4
```

@kayhayen 
That worked for me, thanks. Can you list which plugins are available in the documentation for ready access?

**Comment by kayhayen** [comment]
@Sun-ZhenXing yes, the plugin has an option for it, enable it and do --help to see it.

**Comment by LonelyChineseBoy** [comment]
> > The value `sensible,multimedia` might be more what you want.价值 `sensible,multimedia` 可能更符合您的要求。
> 
> ```yaml
> PySide6: 6.5.3
> Nuitka:  1.8.4
> ```
> 
> @kayhayen That worked for me, thanks. Can you list which plugins are available in the documentation for ready access?这对我有用，谢谢。您能否在文档中列出哪些插件可供随时访问？

How did you solve it and which command did you use? @Sun-ZhenXing

**Comment by LonelyChineseBoy** [comment]
In my project, the packaging command added -- include qt plugins=multimedia  successfully
