### ISSUE TITLE
Pandas PyArrow to_parquet access violation error

### ISSUE THREAD

**Issue by interseba5** [Nuitka/Nuitka#1898]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version

1.2
Commercial: None
Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Python39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

* How did you install Nuitka and Python

Installed using pip

* The specific PyPI names and versions

pip 22.0.4 from c:\python39\lib\site-packages\pip (python 3.9)
 ```
pyarrow==10.0.0
pandas==1.5.0
 ```

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

 ```Python
from pandas import read_csv
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/housing.csv'
dataframe = read_csv(url)
dataframe.to_parquet('ts.pq')
 ```

* Provide in your issue the Nuitka options used

python -m nuitka --enable-plugin=numpy --nofollow-import-to=IPython,dask,tensorflow,keras,matplotlib --standalone --output-dir=.\bin\Debug main.py 

### Explanation
When i try to run the compiled script, it closes immediatly without any output. I have tried to debug the .exe with visual studio and i have obtained this output:
```
...
'main.exe' (Win32): loading of 'F:\bin\Debug\main.dist\parquet.dll' completed. Module compiled without symbol.
'main.exe' (Win32): loading of 'F:\bin\Debug\main.dist\_uuid.pyd' completed. 
'main.exe' (Win32): loading of 'F:\bin\Debug\main.dist\_queue.pyd' completed. 
'main.exe' (Win32): loading of 'F:\bin\Debug\main.dist\pyarrow\_hdfsio.pyd' completed. Module compiled without symbol..
'main.exe' (Win32): loading of 'F:\bin\Debug\main.dist\pandas\_libs\ops.pyd' completed. Module compiled without symbol.
'main.exe' (Win32): loading of 'F:\bin\Debug\main.dist\numexpr\interpreter.pyd' completed. Module compiled without symbol.
'main.exe' (Win32): loading of 'C:\Windows\System32\kernel.appcore.dll' completed. 
'main.exe' (Win32): loading of 'F:\bin\Debug\main.dist\pyarrow\_compute.pyd' completed. Module compiled without symbol.
Exception thrown at 0x00007FF8C3686455 (python39.dll) in main.exe: 0xC0000005: access violation reading path 0xFFFFFFFFFFFFFFFF.
```

**Comment by kayhayen** [comment]
This should be missing DLLs, it seems pyarrow has some.

**Comment by kayhayen** [comment]
Actually, this copies code that #1565 has a workaround for. It seems that not only seaborn, but also pyarray copies that code. It is a MSVC compiler bug for the Nuitka generated code. I fixed it on factory branch, but it still segfaulted, this time in pandas plotting. I will have to check out why that is now. Maybe a similar thing there too.

**Comment by interseba5** [comment]
MinGW64 should work because i remeber that also for #1565 and a related issue that i had opened (#1544) i had temporary solved it by compiling with MinGW64.

**Comment by kayhayen** [comment]
The good thing of course would be that maybe it highlights, where MSVC is being stretched too far and goes wrong, such that code generation could be changed to not do it.

**Comment by kayhayen** [comment]
I was checking and SciPy 1.8.1 works still, I was not sure if recent optimization improvements would re-expose the issue of MSVC here, but apparently that is not the case.

**Comment by kayhayen** [comment]
python3.9 bin/nuitka --list-package-dlls=pyarrow
Nuitka-Tools:INFO: Checking package directory 'C:\Python39\lib\site-packages\pyarrow' .. 
C:\Python39\lib\site-packages\pyarrow
  arrow.dll
  arrow_dataset.dll
  arrow_flight.dll
  arrow_python.dll
  arrow_python_flight.dll
  arrow_substrait.dll
  msvcp140.dll
  parquet.dll

**Comment by kayhayen** [comment]
I didn't have any issue with a test compilation, so this is all good I assume.
