### ISSUE TITLE
using nuitka for compiling to different architecture

### ISSUE THREAD

**Issue by janluak** [Nuitka/Nuitka#1899]
Hey,

this is less a bug than a help request:

I am trying to compile a python program including the python interpreter for using this program on a different architecture (embedded).
With using `--follow-imports` and `--standalone` I was able to compile my code within one container (having python installed) and executing it on another bare container just by copying the `dist` directory.
So far so nice and thanks for the nuitka 👍

The hard part is to understand how to configure gcc.
I know its possible to use different gcc on a machine for compiling for different architectures. I just can't figure out if this is available with nuitka...

Anybody an idea?
Thanks everyone!

**Comment by kayhayen** [comment]
Nuitka doesn't support cross compilation at this time.
