### ISSUE TITLE
Expose explicit interfaces of module externally

### ISSUE THREAD

**Issue by pyrito** [Nuitka/Nuitka#1900]
Hi @kayhayen, 

Firstly, thank you for the great work with Nuitka - this project has blossomed into something very useful for the community. We appreciate your hard work and contributions!

I have been using Nuitka for a project and was wondering if there was a way to only expose certain modules to users externally. For example say I had the following repo structure:

```
moduleX/
    - classA.py
    - classB.py
    - classC.py
    - classD.py
```
Let's say that I compile `moduleX` by doing something like this: `python -m nuitka --module moduleX --include-package=moduleX`. The shared object as is would allow me to import `classA`, `classB`, etc. What if I wanted to only expose things from `classA` and `classB` and nothing else while still compiling the other files in the module so that other things would work internally. Would this be possible? 

Thanks so much!

**Comment by kayhayen** [comment]
There is information in https://nuitka.net/doc/commercial.html on how to do this to some extent, but not perfectly. It will add the ability to isolate your module totally in the future, but that does not exist yet this time.
