### ISSUE TITLE
A problem about load dll im my own code

### ISSUE THREAD

**Issue by Soikie** [Nuitka/Nuitka#1901]
When i load dll im my code ,it occurs follow error . I know the dll lacks dependencies ,but the denpendencies are too many . How can i make the nuitka add the dll when compiling?

error
`Traceback (most recent call last):
File "PyInstaller\loader\pyimod03_ctypes.py", line 53, in init
File "ctypes_init_.py", line 382, in init
FileNotFoundError: Could not find module 'D:\python_trt\yolov5.dll' (or one of its dependencies). Try using the full path with constructor syntax.`

code

`from ctypes import *
import cv2
import os
import numpy as np
import numpy.ctypeslib as npct

class Detector():
    def __init__(self,model_path,dll_path):
        self.yolov5 = CDLL(dll_path,winmode = 0)
        self.yolov5.Detect.argtypes = [c_void_p,c_int,c_int,POINTER(c_ubyte),npct.ndpointer(dtype = np.float32, ndim = 2, shape = (50, 6), flags="C_CONTIGUOUS")]
        self.yolov5.Init.restype = c_void_p
        self.yolov5.Init.argtypes = [c_void_p]
        self.yolov5.cuda_free.argtypes = [c_void_p]
        self.c_point = self.yolov5.Init(model_path)

    def predict(self,img):
        rows, cols = img.shape[0], img.shape[1]
        res_arr = np.zeros((50,6),dtype=np.float32)
        self.yolov5.Detect(self.c_point,c_int(rows), c_int(cols), img.ctypes.data_as(POINTER(c_ubyte)),res_arr)
        self.bbox_array = res_arr[~(res_arr==0).all(1)]
        return self.bbox_array

    def free(self):
        self.yolov5.cuda_free(self.c_point)

def visualize(img,bbox_array):
    for temp in bbox_array:
        bbox = [temp[0],temp[1],temp[2],temp[3]]  #xywh
        clas = int(temp[4])
        score = temp[5]
        cv2.rectangle(img,(int(temp[0]),int(temp[1])),(int(temp[0]+temp[2]),int(temp[1]+temp[3])), (105, 237, 249), 2)
        img = cv2.putText(img, "class:"+str(clas)+" "+str(round(score,2)), (int(temp[0]),int(temp[1])-5), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (105, 237, 249), 1)
    return img

app_root = os.path.dirname(__file__)
model_path = os.path.join(app_root, "yolov5s.engine").encode("utf8")
dll_path = os.path.join(app_root, "yolov5.dll")
print(dll_path,model_path)
os.add_dll_directory(dll_path)
det = Detector(model_path=model_path, dll_path=dll_path)  # b'' is needed
img = cv2.imread("./images/bus.jpg")
result = det.predict(img)
img = visualize(img,result)
cv2.imshow("img",img)
cv2.waitKey(0)
det.free()
cv2.destroyAllWindows()`

**Comment by kayhayen** [comment]
For all DLLs you need to check out the user yaml that can be provided. So  far it is not documented, but we are going to add documentation soon. For now you can look at the existing yaml files in Nuitka. I am closing this however, due to incomplete information.
