### ISSUE TITLE
support last version pytorch

### ISSUE THREAD

**Issue by krolaper** [Nuitka/Nuitka#1902]
https://github.com/Nuitka/Nuitka/issues/1891

@[kayhayen] Actually kind of all are supported, but every PyPI release can invalidate that information. Right now we do not have automatic regression testing of all of PyPI, but we hope to get there.

@[kayhayen] This is part of the hotfix release 1.2.2 that I just made.

Updated, but did not help. Still the same error:
Nuitka-Plugins:WARNING: torch: This plugin has been deprecated, do not enable it anymore.
version of pytorch 1.3.0 as said cannot be installed, it is not in official source. only from version 1.11.0

**Comment by kayhayen** [comment]
That 1.3.0 was probably a typo of 1.13.0
