### ISSUE TITLE
Unsupported 16-bit application on Windows10

### ISSUE THREAD

**Issue by ripdechains** [Nuitka/Nuitka#1905]
![immagine](https://user-images.githubusercontent.com/97162786/203482127-53e1c9e2-89c8-4185-8f12-67d06ee0a700.png)
archive image (identical to the error message on my machine)

After using the Nuitka-generated executables for a few months without any problems, on the same machine, I now get this incompatibility error when running them. If until a few days ago they worked without problems, what could be the problem?

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun.
