### ISSUE TITLE
Dask dataframe incompatibility 

### ISSUE THREAD

**Issue by RJHughes** [Nuitka/Nuitka#1906]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version
1.2.2
Commercial: None
Python: 3.8.10 (default, Jun 22 2022, 20:18:18)
Flavor: Debian Python
Executable: /home/user/venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 20.04.5

* How did you install Nuitka and Python
> python -m venv venv
> source venv/bin/activate
> pip install nuitka 
> pip install pandas 
> pip install dask

* The specific PyPI names and versions
> pip freeze | grep dask
dask==2022.7.1
> pip freeze | grep pandas
pandas==1.4.1

* Short program (test.py)

```
import dask.dataframe as dd
import pandas as pd

df = pd.DataFrame([[1,2,3,4]],columns=["a","b","c","d"])
dask_df = dd.from_pandas(df, 4)

print(df)
print(dask_df)
```

* Provide in your issue the Nuitka options used
> python -m nuitka --standalone --plugin-enable=numpy --prefer-source-code  test.py
> cd test.dist
> ./test

```
Traceback (most recent call last):
  File "/home/user/test.dist/dask/dataframe/__init__.py", line 4, in <module dask.dataframe>
  File "/home/user/test.dist/dask/dataframe/backends.py", line 20, in <module dask.dataframe.backends>
  File "/home/user/test.dist/dask/dataframe/core.py", line 35, in <module dask.dataframe.core>
  File "/home/user/test.dist/dask/dataframe/methods.py", line 22, in <module dask.dataframe.methods>
  File "/home/user/test.dist/dask/dataframe/utils.py", line 23, in <module dask.dataframe.utils>
ImportError: cannot import name 'tm' from 'dask.dataframe._compat' (/home/user/test.dist/dask/dataframe/_compat.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/test.dist/test.py", line 1, in <module>
  File "/home/user/test.dist/dask/dataframe/__init__.py", line 64, in <module dask.dataframe>
ImportError: Dask dataframe requirements are not installed.

Please either conda or pip install as follows:

  conda install dask                     # either conda install
  python -m pip install "dask[dataframe]" --upgrade  # or python -m pip install

```

# Description
Hi there, I'm trying to compile a project that uses dask dataframes for multiprocessing. I've been unable to do so because of the above issue which I can re-produce with a small example. I saw an earlier post that suggested to use `prefer-source-code` for dask. I have tried a few iterations on this nuitka call but all seem to hit the same issue. I haven't tried exhaustive permutations on the commands as the compile time is already quite large (~1 hour). Any advice on how to reduce this (I read that we might be bringing too much unneeded functionality of pandas into the fold) as well as a possible solution for the above issue would be much appreciated.

**Comment by KevinRodriguez777** [comment]
This works correctly on latest Nuitka

**Comment by nnc6** [comment]
I have the same issue. 
Versions:
dask 2024.2.1
pandas 2.0.1
nuitka 2.1
I do not use dask in the script, it's called because of swifter and sqlite3 libraries I'm using. i checked in the path (C:\Users\user\filename.dist\dask\dataframe) and _compat.py is actually there...

**Comment by KevinRodriguez777** [comment]
> I have the same issue. Versions: dask 2024.2.1 pandas 2.0.1 nuitka 2.1 I do not use dask in the script, it's called because of swifter and sqlite3 libraries I'm using. i checked in the path (C:\Users\user\filename.dist\dask\dataframe) and _compat.py is actually there...

open a new issue and follow the issues readme instructions.
