### ISSUE TITLE
NSUserNotificationCenter cannot be initialized 

### ISSUE THREAD

**Issue by emre84** [Nuitka/Nuitka#1907]
**Environment:**
python3.7 -m nuitka --version
Nuitka-Options:INFO: Used command line options: --version
1.3rc3
Commercial: None
Python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21)
Flavor: CPython Official
Executable: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7
OS: Darwin
Arch: x86_64
scons: warning: Calling missing SConscript without error is deprecated.
Transition by adding must_exist=0 to SConscript calls.
Missing SConscript '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nuitka/build/CCompilerVersion.scons'
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nuitka/build/inline_copy/bin/scons.py", line 44, in 
**NOTE:**
Somehow I got an error for "python3.7 -m nuitka --version" command, as you see above. But my comment is not related with this warning

**How did you install Nuitka and Python**
pip

**The specific PyPI names and versions**
pyobjc==9.0

**Provide in your issue the Nuitka options used**
sudo python3.7 -m nuitka --run --standalone --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow --python-flag=no_site test.py

**Content of test.py:**
```
#code sends macOS alerts
import os
import time
from Foundation import NSUserNotification
from Foundation import NSUserNotificationCenter
_title = "title"
message = "message"
notification = NSUserNotification.alloc().init()
notification.setTitle(title)
notification.setInformativeText(message)
center = NSUserNotificationCenter.defaultUserNotificationCenter()
center.deliverNotification(notification)
time.sleep(2)
```

**Error during executable run:**
Traceback (most recent call last):
File "/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/tests/test5.dist/test5.py", line 16, in 
AttributeError: 'NoneType' object has no attribute 'deliverNotification_'

**Note:**
Is bug fix(1590) not related with Foundation-NSUserNotification and Foundation-NSUserNotificationCenter libraries? I thought that https://github.com/Nuitka/Nuitka/issues/1590 would fix my problem.

Thanks a lot in advance.

**Comment by kayhayen** [comment]
Does this need an entitlement, and can you try app bundle mode, I am suspecting there might be issues with that. For all I know, pyobjc has passed the developers test suite with stable Nuitka, but there may still be usability traps.

**Comment by kayhayen** [comment]
No feedback on my question?

**Comment by emre84** [comment]
Hi Kay, 

As you said before I did not want to comment any status before I finish all my tests.

So:
your suggestion was right with bundle mode:

Following basic code works fine with following nuitka command:

**Nuikta Command:**
date > log.txt;sudo python3.7 -m nuitka --run --standalone --enable-plugin=numpy,pyside2  --noinclude-pytest-mode=nofollow   --noinclude-setuptools-mode=nofollow  --macos-create-app-bundle --macos-app-icon=/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/icons/license_lock_photo.png --python-flag=no_site test.py; date >> log.txt

**Content of test.py:**
#code sends macOS alerts
import os
import time
from Foundation import NSUserNotification
from Foundation import NSUserNotificationCenter
_title = "title"
message = "message"
notification = NSUserNotification.alloc().init()
notification.setTitle(title)
notification.setInformativeText(message)
center = NSUserNotificationCenter.defaultUserNotificationCenter()
center.deliverNotification(notification)
time.sleep(2)

But if I use similar nuitka command with my whole code, I got some problems. I will investigate and let you know.

If you want you can close this issue.

Thanks a lot.

**Comment by emre84** [comment]
Hi Kay,

My tests are completed. My Problem is that I am using PySide in my App. So if I compile my code(with Pyside import) with " --macos-create-app-bundle" mode, It cannot compile since I got following error.

FATAL: options-nanny: Error, package 'PySide2' requires '--onefile' to be used on top of '--macos-create-app-bundle' or else it cannot work.

But If I use "--onefile" and "--macos-create-app-bundle" together, it does not work.

My command:
python3.7 -m nuitka --run --standalone --enable-plugin=numpy,pyside2  --noinclude-pytest-mode=nofollow  --noinclude-setuptools-mode=nofollow --python-flag=no_site --macos-app-icon=/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/icons/license_lock_photo.png **--onefile --macos-create-app-bundle** test.py

Then I get again "AttributeError: 'NoneType' object has no attribute 'deliverNotification_'" error.

Could you please recommend me a command to be able to use PySide with NSUserNotificationCenter? Or is it not possible at the moment with the reason that PySide does not support  --macos-create-app-bundle?

**Comment by kayhayen** [comment]
As you are not a commercial subscriber, you won't have the PySide2 version that is fully compatible with Nuitka, see here: https://nuitka.net/pages/pyside2.html

You will either need to subscribe or update to PySide6.

**Comment by kayhayen** [comment]
At least we learned that indeed, bundle mode is required for your example code to work. I am adding that.
