### ISSUE TITLE
Nuitka compile .exe not sending the email

### ISSUE THREAD

**Issue by Ogujiuba-Henry** [Nuitka/Nuitka#1909]
I recently compiled a keylogger script using nuitka, but the .exe file created does not send the email file after code is executed. The code works normally when run from terminal. Is there any fix for this?

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun.
