### ISSUE TITLE
The "multidispatcher" does not work with compiled classes, NotImplementedError: Could not find signature for __init__: <str>

### ISSUE THREAD

**Issue by Bingdom** [Nuitka/Nuitka#1910]
Hi, it looks like the multipledispatch library is not working for me

### python -m nuitka --version

```
1.2.2
Commercial: None
Python: 3.10.8 (main, Nov 24 2022, 13:21:08) [GCC 10.2.1 20210110]
Flavor: Unknown
Executable: /usr/local/bin/python3.10
OS: Linux
Arch: x86_64
Distribution: Debian 11
```

Output of errror:

```
Traceback (most recent call last):
  File "/home/user/dispatch.dist/dispatch.py", line 14, in <module>
  File "/home/user/dispatch.dist/multipledispatch/dispatcher.py", line 433, in __call__
NotImplementedError: Could not find signature for __init__: <str>
```

### How did you install Nuitka and Python

I used the following command to install nuitka:
```
python3.10 -m pip install nuitka
```

I downloaded and compiled python myself. Not using pyenv.
I have a very barebones debian setup.

### Version of multipledispatch I'm using
```
multipledispatch==0.6.0
```

### Reproducible code
Confirmed working in python as expected

```py
# nuitka-project: --standalone
from multipledispatch import dispatch

class TestClass:
	@dispatch(str)
	def __init__(self, id: str):
		self.id = id
	
	@dispatch(str, int)
	def __init__(self, id: str, count: int):
		self.id = id
		self.count = count


ins1 = TestClass("abc")
ins2 = TestClass("xyz", 4)

print(ins1.id)
print(ins2.id, ins2.count)
```

**Comment by kayhayen** [comment]
Bonus points for using project options, the project happens in accelerated mode too. it just "hates" compiled methods it seems.

**Comment by kayhayen** [comment]
The critical code is this one, the prints are added by me:

```
    def _(func):
        name = func.__name__
        print(name, func, ismethod(func))

        if ismethod(func):

            dispatcher = inspect.currentframe().f_back.f_locals.get(
                name,
                MethodDispatcher(name),
            )

            print(inspect.currentframe().f_back.f_locals, inspect.currentframe().f_back.f_code.co_name)
        else:
            if name not in namespace:
                namespace[name] = Dispatcher(name)
            dispatcher = namespace[name]

        dispatcher.add(types, func)
        return dispatcher
    return _
```

The code relies on `f_locals` which for functions and classes is only filled in case of an exception and it being attached to a traceback in Nuitka. Output differs:

```
# Python:
__init__ <function TestClass.__init__ at 0x000001E8BCCFE050> True
{'__module__': '__main__', '__qualname__': 'TestClass'} TestClass
__init__ <function TestClass.__init__ at 0x000001E8BCCFE0E0> True
{'__module__': '__main__', '__qualname__': 'TestClass', '__init__': <dispatched __init__>} TestClass
```

vs. 

```
# Nuitka:
__init__ <compiled_function TestClass.__init__ at 0x000001ECFCED2E30> True
{'__module__': '__main__'} TestClass
__init__ <compiled_function TestClass.__init__ at 0x000001ECFCED2B60> True
{'__module__': '__main__'} TestClass
```

I believe Nuitka is delaying the assignment into the locals variable dictionary until the "return" to the metaclass usage, where it has to be updated for sure. But it seems to exist, and I am not sure if it is just not assigned to the frame yet.

So, what is happening, is that `multidispatcher` tries to find pre-existing assignments of functions in the dictionary, and work with that. For `enum` and friends, I am pretty sure, we are not delaying assignments in all cases, but recognize if the class dictionary might be something with side effects. The decorator from `multidispatch` is kind of similar in that.

**Comment by kayhayen** [comment]
So, the frame gets created after the mapping that the class uses, already exists, and actually in this instance, the storage could simply be put there. Instead it creates immediately for every class frame, one that contains `__module__` with the module name, as it ought to be, despite on the outside having it put into the dictionary too.

It seems, this is a missing optimization, to create class frames with a passed and pre-existing `f_locals` (or in case of it being cached), assigning it to there after creating it.

This might actually be relatively easy then, even if of course tedious.

**Comment by kayhayen** [comment]
So, I got this to work, lets see how much CI likes this. It touches code that I changed for 3.11 already, so I am not going to make it a hotfix.

**Comment by kayhayen** [comment]
I have resisted the temptation to do the "once vs. full cached" frame optimization, that I feel like it ough to be done too, looking at the code. Right now, the class frame continues to exist even after a class is executed, which of course only makes sense inside loops or functions that can get called multiple times. That is memory and code wasting. For module frames, we already don't do it that way. Classes were so far not really considered, only generators/coroutines/asyncgen have their own thing. 

There might be some scalability on the C level to be gained by removing this unnecessary bloat code. For performance the caching is irrelevant, but memory usage is slightly too high (a frame object is not huge), and code complexity is also high, but for that to be benefitted from, we also shouldn't cache (actually pre-create) their code objects at module load time.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
This is part of the latest pre-release  I just made.

**Comment by kayhayen** [comment]
This is part of the stable release 1.3 that I just made.
