### ISSUE TITLE
Windows: SciPy 1.9.2 or higher is not working

### ISSUE THREAD

**Issue by newuserforstudy** [Nuitka/Nuitka#1912]
1. python -m nuitka --version
'''
1.2.3
Commercial: None
Python: 3.9.0 (default, Nov 15 2020, 08:30:55) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: D:\xxx\Anaconda\envs\paddle\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
'''

2. my project structure

pythonDemo
     —data_dir
     —python_package1
           —__init__.py
           —do_something.py
     —python_package2
          —__init__.py
          —main.py

3. my problem:
Nuitka-Plugins:INFO: delvewheel: Detected usage of 'delvewheel' version '1.1.0' in module 'scipy'.
PASS 1: 60.0%|███████████████          | 772/1286, pandas.core.nanopsTraceback (most recent call last):

  File "D:\sdh\SoftwareInstallLocation\Anaconda\envs\paddle\lib\site-packages\nuitka\plugins\standard\DelvewheelPlugin.py", line 103, in onModuleSourceCode
    assert self.dll_directory is not None, module_name
AssertionError: scipy

**Comment by kayhayen** [comment]
This is going to be part of 1.2.4 hotfix release that I am about to make. Right now it's on the factory branch.

**Comment by MosBas** [comment]
Scipy 1.10 was recently released, and seem to suffer from the same issue.

**Comment by kayhayen** [comment]
@MosBas posting below closed issues is a sure fire way to get ignored.
