### ISSUE TITLE
missing link flag in OSX

### ISSUE THREAD

**Issue by chaosct** [Nuitka/Nuitka#192]
*  Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

On OSX 10.12.6 , stock python (I also have an official python install, with same results)

```
Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
```

   python -m nuitka --version

```
0.6.0.6
Python: 2.7.10 (default, Feb  7 2017, 00:08:15)
Executable: /Users/protopixel/Documents/proto_light_simulator2/.env/bin/python
OS: Darwin
Arch: x86_64
```

*  How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
   what is a virtualenv ...), this is very important usually.

I have nuitka installed in a virtualenv

*  If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
   that demonstrates the issue i.e a small piece of code which reproduces
   the issue and can be run with out any other (or as few as possible)
   external dependencies.

```
$ cat t.py
def f():
    print 'hello'
```

So running this leaves me with lots of linking errors:

```
$ nuitka --module t.py
Undefined symbols for architecture x86_64:
  "_PyArg_ParseTuple", referenced from:
      _Nuitka_Method_reduce_ex in CompiledMethodType.os
  "_PyArg_ParseTupleAndKeywords", referenced from:
      __path_unfreezer_get_data in MetaPathBasedLoader.os
      __path_unfreezer_find_module in MetaPathBasedLoader.os
      __path_unfreezer_load_module in MetaPathBasedLoader.os
      __path_unfreezer_is_package in MetaPathBasedLoader.os
  "_PyArg_UnpackTuple", referenced from:
      _Nuitka_Method_tp_new in CompiledMethodType.os
      _Nuitka_Generator_throw in CompiledGeneratorType
...
```

However, if I supply an extra linking flag for libpython:

```
$ LDFLAGS=-lpython2.7 nuitka --module t.py
````

This works

*  If this is a regression (used to work in an earlier version of Nuitka),
   please note what you know about that.

It worked before, not sure if the problem is because I updated or changed something...

**Comment by kayhayen** [comment]
This is a change I did for everything but Windows, to not link against Python, because it's not needed, and some Python versions don't even have the shared library to do that.

Your Python is it a pyenv possibly?

**Comment by kayhayen** [comment]
Sorry, didn't see you writing "stock python", so that's definitely an issue for all normal module compilation there.

**Comment by chaosct** [comment]
Is it safe in the meantime to link against libpython2.7 like I did?

**Comment by kayhayen** [comment]
Yes, it is what the fix will achieve. Not sure it can be in a hotfix though, doing more changes.

**Comment by kayhayen** [comment]
The fix for it has been on the factory branch, but I got ill and forgot to describe it here.

**Comment by kayhayen** [comment]
This is now on develop branch and will be in next release, closing therefore.
