### ISSUE TITLE
Nuitka and *forge and Numba

### ISSUE THREAD

**Issue by falseywinchnet** [Nuitka/Nuitka#1925]
This is not a bug report. I was asked to submit a ticket with the details on how to replicate an effort to build a simple python program,
which should be a typical use case for nuitka but seems to fail at this time. This may be due to multiple factors, including the environment used. However, the environmental issues were resolved manually without great effort,  but may be suited to patching as the convenience of the "mini" conda dedicated environments is not slight for development and packaging purposes.
At last, we come to a more serious challenge, and this is the challenge- nuitka may often be used to compile packages depending on librosa, which is considered to have among the best STFT implementation among many other convenient audio handling features.
However, recent versions of librosa, for performance, depend on numba, which is a LLVM producing tool with limited interoperable capability with regards to nuitka.

The desired program, which I attempted to compile is: [](https://raw.githubusercontent.com/falseywinchnet/streamcleaner/master/demo_fileIO.py)
This is a single file program that imports:
import os
import numpy

from time import sleep
from time import time as time
from librosa import stft, istft
from scipy.io import wavfile
from tkinter import Tk
from tkinter.filedialog import askopenfilename

The desired environment is chosen to allow for the latest stable packages and python version, in a convenient format with zero conflict, zero frustration configuration and usage.

To replicate my environment and steps:

Firstly obtain either the mambaforge or miniforge binary for your platform and architecture and install it.
These can be obtained from [](https://github.com/conda-forge/miniforge)
This will quickly set up a single conda virtual environment with python 3.10 in your user folder where everything is accessible,
and provide a shortcut to open a pre-configured terminal environment which is sanitary.

Also git is required to install nuitka.

Opening this environment from the shortcut, using "conda install" and "pip install", only the minimum essential packages are required:
conda install scipy, numpy, librosa, tk. pip install "nuitka @ git+https://github.com/Nuitka/Nuitka".
The respective components and their dependencies are quickly added to the environment.

Nuitka 1.3rc5 is the installed version.

I then run  "nuitka --standalone --enable-plugin=tk-inter  demo_fileIO.py"

(base) C:\Users\admin\Desktop> nuitka --standalone --enable-plugin=tk-inter  demo_fileIO.py
Nuitka-Options:INFO: Used command line options: --standalone --enable-plugin=tk-inter demo_fileIO.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.3rc5' on Python '3.10' commercial grade 'not installed'.
Nuitka-Plugins:INFO: tk-inter: Injecting pre-module load code for module 'tkinter':
Nuitka-Plugins:INFO: tk-inter:     Need to make sure we set environment variables for TCL.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka-Plugins:INFO: pkg-resources: Injecting post-module load code for module 'pkg_resources':
Nuitka-Plugins:INFO: pkg-resources:     Registering Nuitka loader with "pkg_resources".

Note that due to librosa, the entirety of numba, which is a different llvm optimizing package, has to be included.
However, librosa also brings in sklearn and matplotlib. These libraries are not required and should be optimized out-
librosa is only used for their excellent stft and istft functions, nothing more.'

In this run, pass 1 completes considering 2100 files.  However, it crashes with an error:

FATAL: tk-inter: Could not find Tcl, you might need to set 'TCL_LIBRARY' and if that works, report a bug.

The error does not indicate that what nuitka is looking for is init.tcl.

set TCL_LIBRARY=C:\Users\admin\mambaforge\Library\lib\tcl8.6

After doing this, pass 1 completes, and pass two runs. However, pass two does not complete.
It then complains about TK, which must also be set.

set TK_LIBRARY=C:\Users\admin\mambaforge\Library\lib\tk8.6

Nothing else is changed, but passes 1 and 2 must still re-run. Perhaps nuitka should check "touch" of file update last time
to determine if it is necessary to re-run passes.

After providing this information nuitka is able to prune files somewhat, only including 1,440 files in the compile stage.

Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).

Nuitka-Scons:INFO: Backend linking program with 1440 files (no progress information available).
Nuitka-Scons:INFO: Running 'C:\\Users\\admin\\AppData\\Local\\Nuitka\\Nuitka\\Cache\\downloads\\gcc\\x86_64\\11.3.0-14.0.3-10.0.0-msvcrt-r3\\mingw64\\bin\\gcc.exe -o "C:\\Users\\admin\\Desktop\\DEMO_F~1.DIS\\demo_fileIO.exe" -fuse-linker-plugin -flto=8 -fpartial-inlining -freorder-functions -Wl,--exclude-all-symbols -Wl,--out-implib,.\\import.lib -municode -O3 -s -Wl,--enable-auto-import -Wl,--stack,9863168 -static-libgcc @".\\@link_input.txt" -LC:\\Users\\admin\\mambaforge\\libs -lm -lpython310' took 3684.48 seconds
Nuitka-Scons:INFO: Compiled 5757 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 1440
Nuitka-Postprocessing:WARNING: Failed to add resources to file 'demo_fileIO.dist\\demo_fileIO.exe' in attempt 1 with
Nuitka-Postprocessing:WARNING: error code 22.
Disable Anti-Virus, e.g. Windows Defender for build folders. Retrying
Nuitka-Postprocessing:WARNING: after a second of delay.
Nuitka-Postprocessing:WARNING: Succeeded with add resources to file 'demo_fileIO.dist\\demo_fileIO.exe' in attempt 2.
Nuitka-Plugins:INFO: data-files: Included data file 'certifi\cacert.pem' due to package data for 'certifi'.
Nuitka-Plugins:INFO: matplotlib: Included 182 data files due to package data for 'matplotlib.
Nuitka-Plugins:INFO: matplotlib: Included data file 'matplotlib\mpl-data\matplotlibrc' due to updated matplotlib config file with backend to use.
Nuitka-Plugins:INFO: tk-inter: Included 87 data files due to Tk copy needed for standalone Tcl.
Nuitka-Plugins:INFO: tk-inter: Included 836 data files due to Tcl needed for tkinter usage.
Nuitka-Plugins:INFO: dll-files: Found 1 file DLLs from llvmlite.binding.ffi installation.
Nuitka-Plugins:INFO: dll-files: Found 32 files DLLs from scipy installation.
Nuitka:INFO: Keeping build directory 'demo_fileIO.build'.
Nuitka:INFO: Successfully created 'demo_fileIO.dist\demo_fileIO.exe'.

At this point the build succeeds.

Furthermore, while previous builds included extra dlls more than were needed, the latest nuitka succeeds in leaving them out.
After including mkl_intel_thread.2.dll. manually,  and following the error messages, on two more missing imports, a number of secondary imports that were missed were manually included and the program finally can produce the dialogue to select a file.

I then attempted to process a file with the program. This failed, and further diagnostic will require debugging and consideration to this interoperability. The program is also 200mb despite the original source being 280 lines.

Traceback (most recent call last):
  File "C:\Users\admin\Desktop\DEMO_F~1.DIS\demo_fileIO.py", line 275, in <module>
  File "C:\Users\admin\Desktop\DEMO_F~1.DIS\demo_fileIO.py", line 250, in process_data
  File "C:\Users\admin\Desktop\DEMO_F~1.DIS\demo_fileIO.py", line 231, in denoise
  File "C:\Users\admin\Desktop\DEMO_F~1.DIS\librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\admin\Desktop\DEMO_F~1.DIS\librosa\core\spectrum.py", line 416, in istft
    __overlap_add(y[..., frame * hop_length :], ytmp, hop_length)
  File "C:\Users\admin\Desktop\DEMO_F~1.DIS\numba\core\dispatcher.py", line 487, in _compile_for_args
    raise e
  File "C:\Users\admin\Desktop\DEMO_F~1.DIS\numba\core\dispatcher.py", line 420, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "C:\Users\admin\Desktop\DEMO_F~1.DIS\numba\core\dispatcher.py", line 965, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Users\admin\Desktop\DEMO_F~1.DIS\numba\core\dispatcher.py", line 125, in compile
    status, retval = self._compile_cached(args, return_type)
  File "C:\Users\admin\Desktop\DEMO_F~1.DIS\numba\core\dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "C:\Users\admin\Desktop\DEMO_F~1.DIS\numba\core\dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "C:\Users\admin\Desktop\DEMO_F~1.DIS\numba\core\compiler.py", line 716, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\admin\Desktop\DEMO_F~1.DIS\numba\core\compiler.py", line 448, in compile_extra
    ExtractByteCode().run_pass(self.state)
  File "C:\Users\admin\Desktop\DEMO_F~1.DIS\numba\core\untyped_passes.py", line 64, in run_pass
    bc = bytecode.ByteCode(func_id)
  File "C:\Users\admin\Desktop\DEMO_F~1.DIS\numba\core\bytecode.py", line 214, in __init__
    self._compute_lineno(table, code)
  File "C:\Users\admin\Desktop\DEMO_F~1.DIS\numba\core\bytecode.py", line 236, in _compute_lineno
    known = table[_FIXED_OFFSET].lineno
KeyError: 2

**Comment by falseywinchnet** [comment]
https://github.com/falseywinchnet/streamcleaner/blob/master/demo_fileIO.py
this is the program I attempted to compile, for some reason the link wouldn't inline in the original post

**Comment by kayhayen** [comment]
As you say, not a report, so I won't treat it like one. The Anaconda is now correctly handling tkinter. Not sure what else you have to report, feel free to file actual reports for other things.
