### ISSUE TITLE
Clang compling error

### ISSUE THREAD

**Issue by shenjackyuanjie** [Nuitka/Nuitka#1926]
![image](https://user-images.githubusercontent.com/54507071/206374300-285d2f3a-be1c-4117-a67e-5ca92a5ee474.png)
![image](https://user-images.githubusercontent.com/54507071/206374637-57ab496b-4f57-4be2-9661-4ff4d07759c8.png)

for `print('Hello World')`
![image](https://user-images.githubusercontent.com/54507071/206379012-e6609405-dae4-4519-bc0b-156a550237ce.png)

![image](https://user-images.githubusercontent.com/54507071/206379273-01ae86d2-02fe-4bc0-9a9d-718a55752bae.png)

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun.

**Comment by shenjackyuanjie** [comment]
sorry, and I will open anther issue
