### ISSUE TITLE
Numpy:Error, call to 'codesign' failed

### ISSUE THREAD

**Issue by emre84** [Nuitka/Nuitka#1928]
**Environment:**
emres-MacBook-Air:tests emre$ python3.7 -m nuitka --version
Nuitka-Options:INFO: Used command line options: --version
1.3rc6
Commercial: None
Python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
Flavor: CPython Official
Executable: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7
OS: Darwin
Arch: x86_64
Version C compiler: /usr/bin/clang (clang).

**How did you install Nuitka and Python**
pip

**nuitka command:**
python3.7 -m nuitka --run --standalone --enable-plugin=numpy,pyside6  --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow --python-flag=no_site --include-data-dir=/Users/models=models --include-data-dir=/Users/icons=icons --macos-app-icon=/Users/icons/license_lock_photo.png --macos-create-app-bundle --macos-disable-console --macos-app-protected-resource="NSCameraUsageDescription:xxx" --macos-app-protected-resource="NSPhotoLibraryUsageDescription:xxx" --macos-app-mode=ui-element test_copy.py;

**Content of test_copy.py:**
```
import numpy as np
a = np.arange(15).reshape(3, 5)
```

**error:**
Nuitka-Plugins:WARNING: numpy: This plugin has been deprecated, do not enable it anymore.
Nuitka:INFO: Starting Python compilation with Nuitka '1.3rc6' on Python '3.7' commercial grade 'not installed'.
Nuitka-Plugins:INFO: pyside6: Injecting post-module load code for module 'PySide6.QtCore':
Nuitka-Plugins:INFO: pyside6:     Setting Qt library path to distribution folder. We need to avoid loading target
Nuitka-Plugins:INFO: pyside6:     system Qt plugins, which may be from another Qt version.
Nuitka:INFO: Completed Python level compilation and optimization.               
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.                 
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: clang (clang).
Nuitka-Scons:INFO: Backend linking program with 141 files (no progress information available).
Nuitka-Scons:INFO: Running /usr/bin/clang -o /Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/tests/test_copy.app/Contents/MacOS/test_copy -flto --target=x86_64-apple-macos10.9 -O3 -Wno-deprecated-declarations -headerpad_max_install_names -Wl,-sectcreate,constants,constants,./__constants.bin @"./@link_input.txt -L/Library/Frameworks/Python.framework/Versions/3.7/lib -lm -lpython3.7m took 260.74 seconds
Nuitka-Scons:INFO: Compiled 141 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 110
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 31
Nuitka-Postprocessing:INFO: File '/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/icons/license_lock_photo.png' is not in macOS icon format, converting to it.
Nuitka-Options:INFO: Included data file 'models/.DS_Store' due to specified data dir '/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/models' on command line.
Nuitka-Options:INFO: Included data file 'models/classes' due to specified data dir '/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/models' on command line.
Nuitka-Options:INFO: Included data file 'models/classifier_lite.onnx' due to specified data dir '/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/models' on command line.
Nuitka-Options:INFO: Included data file 'models/classifier_model.onnx' due to specified data dir '/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/models' on command line.
Nuitka-Options:INFO: Included data file 'models/detector_v2_default_checkpoint.onnx' due to specified data dir '/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/models' on command line.
Nuitka-Options:INFO: Included 52 data files due to specified data dir '/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/icons' on command line.
Nuitka-Plugins:INFO: pyside6: Including Qt plugins 'iconengines,imageformats,platforms,styles' below 'PySide6/qt-plugins'.
Nuitka-Plugins:INFO: dll-files: Found 4 files DLLs from numpy installation.
Nuitka-Plugins:INFO: dll-files: Found 7 files DLLs from numpy.core installation.
FATAL: Error, call to 'codesign' failed: ['/usr/bin/codesign', '-s', '-', '--force', '--deep', '--preserve-metadata=entitlements', 'test_copy.app/Contents/MacOS/test_copy', 'test_copy.app/Contents/MacOS/CoreFoundation/_CoreFoundation.so', 'test_copy.app/Contents/MacOS/CoreFoundation/_inlines.so', 'test_copy.app/Contents/MacOS/Foundation/_Foundation.so', 'test_copy.app/Contents/MacOS/Foundation/_inlines.so', 'test_copy.app/Contents/MacOS/PySide6/QtCore.so', 'test_copy.app/Contents/MacOS/PySide6/QtGui.so', 'test_copy.app/Contents/MacOS/PySide6/QtWidgets.so', 'test_copy.app/Contents/MacOS/_bisect.so', 'test_copy.app/Contents/MacOS/_blake2.so', 'test_copy.app/Contents/MacOS/_bz2.so', 'test_copy.app/Contents/MacOS/_codecs_cn.so', 'test_copy.app/Contents/MacOS/_codecs_hk.so', 'test_copy.app/Contents/MacOS/_codecs_iso2022.so', 'test_copy.app/Contents/MacOS/_codecs_jp.so', 'test_copy.app/Contents/MacOS/_codecs_kr.so', 'test_copy.app/Contents/MacOS/_codecs_tw.so', 'test_copy.app/Contents/MacOS/_contextvars.so', 'test_copy.app/Contents/MacOS/_crypt.so', 'test_copy.app/Contents/MacOS/_csv.so', 'test_copy.app/Contents/MacOS/_ctypes.so', 'test_copy.app/Contents/MacOS/_datetime.so', 'test_copy.app/Contents/MacOS/_dbm.so', 'test_copy.app/Contents/MacOS/_decimal.so', 'test_copy.app/Contents/MacOS/_elementtree.so', 'test_copy.app/Contents/MacOS/_hashlib.so', 'test_copy.app/Contents/MacOS/_heapq.so', 'test_copy.app/Contents/MacOS/_json.so', 'test_copy.app/Contents/MacOS/_lzma.so', 'test_copy.app/Contents/MacOS/_multibytecodec.so', 'test_copy.app/Contents/MacOS/_opcode.so', 'test_copy.app/Contents/MacOS/_pickle.so', 'test_copy.app/Contents/MacOS/_posixsubprocess.so', 'test_copy.app/Contents/MacOS/_queue.so', 'test_copy.app/Contents/MacOS/_random.so', 'test_copy.app/Contents/MacOS/_scproxy.so', 'test_copy.app/Contents/MacOS/_sha3.so', 'test_copy.app/Contents/MacOS/_socket.so', 'test_copy.app/Contents/MacOS/_ssl.so', 'test_copy.app/Contents/MacOS/_struct.so', 'test_copy.app/Contents/MacOS/_uuid.so', 'test_copy.app/Contents/MacOS/audioop.so', 'test_copy.app/Contents/MacOS/binascii.so', 'test_copy.app/Contents/MacOS/fcntl.so', 'test_copy.app/Contents/MacOS/grp.so', 'test_copy.app/Contents/MacOS/math.so', 'test_copy.app/Contents/MacOS/mmap.so', 'test_copy.app/Contents/MacOS/numpy/core/_multiarray_tests.so', 'test_copy.app/Contents/MacOS/numpy/core/_multiarray_umath.so', 'test_copy.app/Contents/MacOS/numpy/fft/_pocketfft_internal.so', 'test_copy.app/Contents/MacOS/numpy/linalg/_umath_linalg.so', 'test_copy.app/Contents/MacOS/numpy/linalg/lapack_lite.so', 'test_copy.app/Contents/MacOS/numpy/random/_bounded_integers.so', 'test_copy.app/Contents/MacOS/numpy/random/_common.so', 'test_copy.app/Contents/MacOS/numpy/random/_generator.so', 'test_copy.app/Contents/MacOS/numpy/random/_mt19937.so', 'test_copy.app/Contents/MacOS/numpy/random/_pcg64.so', 'test_copy.app/Contents/MacOS/numpy/random/_philox.so', 'test_copy.app/Contents/MacOS/numpy/random/_sfc64.so', 'test_copy.app/Contents/MacOS/numpy/random/bit_generator.so', 'test_copy.app/Contents/MacOS/numpy/random/mtrand.so', 'test_copy.app/Contents/MacOS/objc/_objc.so', 'test_copy.app/Contents/MacOS/pyexpat.so', 'test_copy.app/Contents/MacOS/select.so', 'test_copy.app/Contents/MacOS/shiboken6/Shiboken.so', 'test_copy.app/Contents/MacOS/termios.so', 'test_copy.app/Contents/MacOS/unicodedata.so', 'test_copy.app/Contents/MacOS/zlib.so', 'test_copy.app/Contents/MacOS/PySide6/qt-plugins/iconengines/libqsvgicon.dylib', 'test_copy.app/Contents/MacOS/PySide6/qt-plugins/imageformats/libqgif.dylib', 'test_copy.app/Contents/MacOS/PySide6/qt-plugins/imageformats/libqicns.dylib', 'test_copy.app/Contents/MacOS/PySide6/qt-plugins/imageformats/libqico.dylib', 'test_copy.app/Contents/MacOS/PySide6/qt-plugins/imageformats/libqjpeg.dylib', 'test_copy.app/Contents/MacOS/PySide6/qt-plugins/imageformats/libqmacheif.dylib', 'test_copy.app/Contents/MacOS/PySide6/qt-plugins/imageformats/libqmacjp2.dylib', 'test_copy.app/Contents/MacOS/PySide6/qt-plugins/imageformats/libqsvg.dylib', 'test_copy.app/Contents/MacOS/PySide6/qt-plugins/imageformats/libqtga.dylib', 'test_copy.app/Contents/MacOS/PySide6/qt-plugins/imageformats/libqtiff.dylib', 'test_copy.app/Contents/MacOS/PySide6/qt-plugins/imageformats/libqwbmp.dylib', 'test_copy.app/Contents/MacOS/PySide6/qt-plugins/imageformats/libqwebp.dylib', 'test_copy.app/Contents/MacOS/PySide6/qt-plugins/platforms/libqcocoa.dylib', 'test_copy.app/Contents/MacOS/PySide6/qt-plugins/platforms/libqminimal.dylib', 'test_copy.app/Contents/MacOS/PySide6/qt-plugins/platforms/libqoffscreen.dylib', 'test_copy.app/Contents/MacOS/PySide6/qt-plugins/styles/libqmacstyle.dylib', 'test_copy.app/Contents/MacOS/numpy/.dylibs/libgcc_s.1.dylib', 'test_copy.app/Contents/MacOS/numpy/.dylibs/libgfortran.3.dylib', 'test_copy.app/Contents/MacOS/numpy/.dylibs/libopenblas.0.dylib', 'test_copy.app/Contents/MacOS/numpy/.dylibs/libquadmath.0.dylib', 'test_copy.app/Contents/MacOS/numpy/core/_multiarray_tests.cpython-37m-darwin.so', 'test_copy.app/Contents/MacOS/numpy/core/_multiarray_umath.cpython-37m-darwin.so', 'test_copy.app/Contents/MacOS/numpy/core/_operand_flag_tests.cpython-37m-darwin.so', 'test_copy.app/Contents/MacOS/numpy/core/_rational_tests.cpython-37m-darwin.so', 'test_copy.app/Contents/MacOS/numpy/core/_simd.cpython-37m-darwin.so', 'test_copy.app/Contents/MacOS/numpy/core/_struct_ufunc_tests.cpython-37m-darwin.so', 'test_copy.app/Contents/MacOS/numpy/core/_umath_tests.cpython-37m-darwin.so', 'test_copy.app/Contents/MacOS/Python', 'test_copy.app/Contents/MacOS/libpyside6.abi3.6.4.dylib', 'test_copy.app/Contents/MacOS/libshiboken6.abi3.6.4.dylib', 'test_copy.app/Contents/MacOS/QtCore', 'test_copy.app/Contents/MacOS/QtGui', 'test_copy.app/Contents/MacOS/QtDBus', 'test_copy.app/Contents/MacOS/QtWidgets', 'test_copy.app/Contents/MacOS/libssl.1.1.dylib', 'test_copy.app/Contents/MacOS/libcrypto.1.1.dylib', 'test_copy.app/Contents/MacOS/libopenblas.0.dylib', 'test_copy.app/Contents/MacOS/libgfortran.3.dylib', 'test_copy.app/Contents/MacOS/libquadmath.0.dylib', 'test_copy.app/Contents/MacOS/libgcc_s.1.dylib', 'test_copy.app/Contents/MacOS/QtSvg'] -> b'test_copy.app/Contents/MacOS/test_copy: bundle format unrecognized, invalid, or unsuitable\nIn subcomponent: /Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/tests/test_copy.app/Contents/MacOS/numpy/.dylibs'.

Note: I tried to compile with and without numpy enable(--enable-plugin=pyside6 and --enable-plugin=numpy,pyside6). in both cases, I got the error.

Thanks a lot in advance.

**Comment by kayhayen** [comment]
Ah shoot, dots are illegal in these things, we will have to patch up the path used, to not contain that. Luckily anti-bloat can come to our rescue and do it on source level, and then we can change the target paths of the DLLs. I am surprised this hasn't come up in other places yet, numpy is not as rare.

**Comment by kayhayen** [comment]
This was released as a hotfix to 1.3 and is part of 1.4 as well.

**Comment by daviewales** [comment]
@kayhayen, I think I'm getting this for `tcl/tk` with Nuitka version 1.4.3 on macOS 12.

```
test_tkinter.app/Contents/MacOS/test_tkinter: bundle format unrecognized, invalid, or unsuitable
In subcomponent: /Users/runner/work/h2h_data_processor/h2h_data_processor/test_tkinter.app/Contents/MacOS/tcl/opt0.4'
```

<details>

```
python3 -m nuitka --tcl-library-dir=/Library/Frameworks/Python.framework/Versions/3.11/lib/tcl8.6 --tk-library-dir=/Library/Frameworks/Python.framework/Versions/3.11/lib/tk8.6 --macos-create-app-bundle --enable-plugin=tk-inter --follow-imports --assume-yes-for-downloads --standalone test_tkinter.py
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /Users/runner/hostedtoolcache/Python/3.10.9/x64
    PKG_CONFIG_PATH: /Users/runner/hostedtoolcache/Python/3.10.9/x64/lib/pkgconfig
    Python_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.10.9/x64
    Python2_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.10.9/x64
    Python3_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.10.9/x64

Nuitka-Options:INFO: Used command line options: --tcl-library-dir=/Library/Frameworks/Python.framework/Versions/3.11/lib/tcl8.6 --tk-library-dir=/Library/Frameworks/Python.framework/Versions/3.11/lib/tk8.6 --macos-create-app-bundle --enable-plugin=tk-inter --follow-imports --assume-yes-for-downloads --standalone test_tkinter.py
Nuitka:WARNING: Using very slow fallback for ordered sets, please install 'ordered-set' PyPI package for best Python compile time performance.
Nuitka-Options:INFO: Following all imports is the default for standalone mode and need not be specified.
Nuitka:INFO: Starting Python compilation with Nuitka '1.4.3' on Python '3.10' commercial grade 'not installed'.
Nuitka-Plugins:INFO: tk-inter: Injecting pre-module load code for module 'tkinter':
Nuitka-Plugins:INFO: tk-inter:     Need to make sure we set environment variables for TCL.
Nuitka-Plugins:INFO: options-nanny: Note, when using 'tkinter', consider using '--disable-console' option. Otherwise high resolution will not be available and a terminal window will open. However for debugging, terminal output is the easiest way to see informative traceback information.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: clang (clang).
Nuitka:INFO: Downloading 'https://nuitka.net/ccache/v4.2.1/ccache-4.2.1.zip'.
Nuitka:INFO: Extracting to '/Users/runner/Library/Caches/Nuitka/downloads/ccache/v4.2.1/ccache'
Nuitka-Scons:INFO: Backend linking program with 7 files (no progress information available).
Nuitka-Scons:INFO: Compiled 7 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 7
Nuitka-Plugins:INFO: tk-inter: Included 87 data files due to Tk needed for tkinter usage.
Nuitka-Plugins:INFO: tk-inter: Included 222 data files due to Tcl needed for tkinter usage.
FATAL: Error, call to 'codesign' failed: ['/usr/bin/codesign', '-s', '-', '--force', '--deep', '--preserve-metadata=entitlements', 'test_tkinter.app/Contents/MacOS/test_tkinter', 'test_tkinter.app/Contents/MacOS/_bisect.so', 'test_tkinter.app/Contents/MacOS/_blake2.so', 'test_tkinter.app/Contents/MacOS/_bz2.so', 'test_tkinter.app/Contents/MacOS/_codecs_cn.so', 'test_tkinter.app/Contents/MacOS/_codecs_hk.so', 'test_tkinter.app/Contents/MacOS/_codecs_iso2022.so', 'test_tkinter.app/Contents/MacOS/_codecs_jp.so', 'test_tkinter.app/Contents/MacOS/_codecs_kr.so', 'test_tkinter.app/Contents/MacOS/_codecs_tw.so', 'test_tkinter.app/Contents/MacOS/_contextvars.so', 'test_tkinter.app/Contents/MacOS/_crypt.so', 'test_tkinter.app/Contents/MacOS/_csv.so', 'test_tkinter.app/Contents/MacOS/_ctypes.so', 'test_tkinter.app/Contents/MacOS/_datetime.so', 'test_tkinter.app/Contents/MacOS/_dbm.so', 'test_tkinter.app/Contents/MacOS/_decimal.so', 'test_tkinter.app/Contents/MacOS/_elementtree.so', 'test_tkinter.app/Contents/MacOS/_hashlib.so', 'test_tkinter.app/Contents/MacOS/_heapq.so', 'test_tkinter.app/Contents/MacOS/_json.so', 'test_tkinter.app/Contents/MacOS/_lzma.so', 'test_tkinter.app/Contents/MacOS/_multibytecodec.so', 'test_tkinter.app/Contents/MacOS/_opcode.so', 'test_tkinter.app/Contents/MacOS/_pickle.so', 'test_tkinter.app/Contents/MacOS/_posixsubprocess.so', 'test_tkinter.app/Contents/MacOS/_queue.so', 'test_tkinter.app/Contents/MacOS/_random.so', 'test_tkinter.app/Contents/MacOS/_scproxy.so', 'test_tkinter.app/Contents/MacOS/_sha512.so', 'test_tkinter.app/Contents/MacOS/_socket.so', 'test_tkinter.app/Contents/MacOS/_ssl.so', 'test_tkinter.app/Contents/MacOS/_statistics.so', 'test_tkinter.app/Contents/MacOS/_struct.so', 'test_tkinter.app/Contents/MacOS/_tkinter.so', 'test_tkinter.app/Contents/MacOS/_uuid.so', 'test_tkinter.app/Contents/MacOS/array.so', 'test_tkinter.app/Contents/MacOS/audioop.so', 'test_tkinter.app/Contents/MacOS/binascii.so', 'test_tkinter.app/Contents/MacOS/fcntl.so', 'test_tkinter.app/Contents/MacOS/grp.so', 'test_tkinter.app/Contents/MacOS/math.so', 'test_tkinter.app/Contents/MacOS/pyexpat.so', 'test_tkinter.app/Contents/MacOS/select.so', 'test_tkinter.app/Contents/MacOS/termios.so', 'test_tkinter.app/Contents/MacOS/unicodedata.so', 'test_tkinter.app/Contents/MacOS/zlib.so', 'test_tkinter.app/Contents/MacOS/libpython3.10.dylib', 'test_tkinter.app/Contents/MacOS/libintl.8.dylib', 'test_tkinter.app/Contents/MacOS/libgdbm_compat.4.dylib', 'test_tkinter.app/Contents/MacOS/libgdbm.6.dylib', 'test_tkinter.app/Contents/MacOS/libssl.1.1.dylib', 'test_tkinter.app/Contents/MacOS/libcrypto.1.1.dylib', 'test_tkinter.app/Contents/MacOS/liblzma.5.dylib', 'test_tkinter.app/Contents/MacOS/libtcl8.6.dylib', 'test_tkinter.app/Contents/MacOS/libtk8.6.dylib'] -> b'test_tkinter.app/Contents/MacOS/test_tkinter: bundle format unrecognized, invalid, or unsuitable\nIn subcomponent: /Users/runner/work/h2h_data_processor/h2h_data_processor/test_tkinter.app/Contents/MacOS/tcl/opt0.4'.
```

</details>

**Comment by kayhayen** [comment]
@daviewales posting below closed issues is a sure fire way to get ignored unfortunately
