### ISSUE TITLE
Clang compile error

### ISSUE THREAD

**Issue by shenjackyuanjie** [Nuitka/Nuitka#1931]
Clang compile error

```
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: clang (clang).
Nuitka-Scons:INFO: Backend linking program with 59 files (no progress information available).
Unexpected output from this command:
D:\APPS\LLVM\bin\clang.exe -o "D:\githubs\DR\build\nuitka1\DR.dist\DR.exe" -Wl,--exclude-all-symbols -Wl,--out-implib,.\import.lib -municode -Wl,--stack,9863168 @".\@link_input.txt" -LD:\APPS\CPython\Python38\libs -lm -lpython38
LINK : warning LNK4044: 无法识别的选项“/-exclude-all-symbols”；已忽略
LINK : warning LNK4044: 无法识别的选项“/-out-implib”；已忽略
LINK : warning LNK4044: 无法识别的选项“/-stack”；已忽略
LINK : fatal error LNK1181: 无法打开输入文件“.\import.lib”
clang: error: linker command failed with exit code 1181 (use -v to see invocation)
```

# the dev version didn't work well

# > python -m nuitka --version
```
1.2.6
Commercial: None
Python: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
Flavor: Unknown
Executable: D:\APPS\CPython\Python38\python3.8.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

# install by 
> python3.8 -m pip install --upgrade nuitka
(witch install nuitka`1.2.6`)

# for `print("hello world")`

![image](https://user-images.githubusercontent.com/54507071/206379012-e6609405-dae4-4519-bc0b-156a550237ce.png)

The same program has been tested on 1.2.6. result in the same way

**Comment by kayhayen** [comment]
You can use Clang in 2 ways. With `--msvc=latest --clang` you get ClangCL and with `--mingw64 --clang` you get the Clang that is part of the winlibs distribution. You of course then don't put anything LLVM into your `PATH`.

For all I know, the errors you cite above are likely only the beginning. From what I recall, the Clang also lacks a usable Windows SDK modification, and more. I gave up on it therefore. The other two ways deliver usable packages with minimal effort.

Yours,
Kay

**Comment by shenjackyuanjie** [comment]
thanks！
But well, I used to use clang(LLVM 115.0.5) with GCC(12.2.0) on my PC
you can see my [repo's file](https://github.com/shenjackyuanjie/Difficult-Rocket/blob/main/docs/nuitka/20221121_nuitka_performs.md) to check it
I reset my windows recent. then it looks like this
so I'm not sure if this issue is cause by the reason you say

thanksfull
shen

**Comment by shenjackyuanjie** [comment]
btw. you can see in the repo's file
when LTO=yes. nuitka compiler will also raise error from some `.o` file
did I need to start a new issue for it?
