### ISSUE TITLE
Why Nuitka creates temporary file directly under C: driver in Windows

### ISSUE THREAD

**Issue by xunilcyl** [Nuitka/Nuitka#1932]
I installed Nuitka in Conda, and ran the basic command "python -m nuitka hello.py" following the [User Manual](https://nuitka.net/doc/user-manual.html) , there was a temporary file "RCX2B0B.tmp" file created under C:\ . Even though the file was removed in short time, but why not create temporary files in the temporary path of system? Since in many situations, application writes file to C:\  is considered dangerous. 

* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.
  > python -m nuitka --version
0.6.13.2
Python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Users\myuser\Anaconda3\envs\myenv\python.exe
OS: Windows
Arch: x86_64

* How did you install Nuitka and Python
Nuitka installed with anaconda3

**Comment by kayhayen** [comment]
Please use a recent version of nuitka, 1.2.6 should be on conda-forge already.
