### ISSUE TITLE
Executable created on macOS 13 cannot be run on macOS 12

### ISSUE THREAD

**Issue by rafalstapinski** [Nuitka/Nuitka#1937]
Hi - I'm unable to find a reference to this in the Nuitka issues nor documentation, but apologies if I missed it and feel free to point me at it.

When creating an executable on (example) macOS 13 Ventura, I cannot run it on any version below, for example on macOS 12 Monterey - getting:

```You can't use this version of the application ... with this version of macOS. You have macOS 12.5.1. This application requires macOS 13.0 or later.```

Is this an option that can be tweaked within Nuitka? Or does this simply come down to a limitation when compiling anything on macOS?

Appreciate any guidance, thank you.

**Comment by rafalstapinski** [comment]
Ah okay, I see that is the case https://github.com/Nuitka/Nuitka/issues/1103#issuecomment-845460856

> Windows allows to build on the latest no issue. Linux and macOS are way more sensitive, and generally need you to build on older. I will research for ways to make that not true with macOS. For Linux plans are for using containers of old Linux on new Linux. For macOS something similar needs to be done, but I am not there yet. But using old macOS will work to deploy on new macOS, that I expect to be the case.

Believe that answers my question - will leave this issue open for maintainer to close as issue rules state.

**Comment by Maxwell175** [comment]
I have had success building with support for macOS 10.9 on macOS 12. I did use a custom built version of python and I made sure to always have `-mmacosx-version-min=10.9` in `CFLAGS`, `CXXFLAGS` and `LDFLAGS` while building python and my app using Nuitka. It is likely that you will not need to compile python from source and just a version from python.org. Depending on how far back you want to support you might need to go with an Intel-only python if you want to support older than 11 if I recall. In any case it is not recommended to use the version of python that comes with your macOS install.

Please make sure to post the output of `python -m nuitka --version` if you would like further assistance.

**Comment by kayhayen** [comment]
Had you filled out the issue template, there would have been more to say. This is likely because of your Python flavor. This determines where it runs, not the build OS, at least one macOS. Nuitka has gained indepence of build OS for macOS a long time ago. Maybe it regressed with macOS 13, hard to tell without any proper information.

**Comment by kayhayen** [comment]
I would need `python -m nuitka --version` output for sure at least.

**Comment by rafalstapinski** [comment]
```
poetry run python -mnuitka --version                                                          00:25:56
1.2.7
Commercial: None
Python: 3.10.8 (main, Dec  3 2022, 20:49:05) [Clang 14.0.0 (clang-1400.0.29.202)]
Flavor: pyenv
Executable: /Users/rafal/Projects/ansel/.venv/bin/python
OS: Darwin
Arch: arm64
```

**Comment by kayhayen** [comment]
You would have to configure your pyenv to build binaries for older macOS, or build it on old macOS. For what I know, it is not intended for deploying applications. Instead use CPython, which is the one listed as supported in the manual. Using pyenv on older macOS will probably make it work on that or higher, but e.g. CPython allows 10.9 or higher for deployment. And you can build on new macOS, you just have to pick the intel arch during build.
