### ISSUE TITLE
--onefile Unable to carry resource file, application of exe file icon failed，It works normally in dist folder.

### ISSUE THREAD

**Issue by Monster-DP** [Nuitka/Nuitka#1938]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version
1.2.6
Commercial: None
Python: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Flavor: Unknown
Executable: D:\Multifarious\code\pythonProject1\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

 

* How did you install Nuitka and Python

Python is installed through the official website installation package. Nuitka is installed through pycharm. Install to the virtualenv environment.

* The specific PyPI names and versions

  > python -m pip freeze
Nuitka==1.2.6
PySide6==6.4.1
PySide6-Addons==6.4.1
PySide6-Essentials==6.4.1
shiboken6==6.4.1

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

```
 #Window icon
from PySide6 import QtGui
icon = QtGui.QIcon()
icon.addPixmap(QtGui.QPixmap("icon/关机.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
self.setWindowIcon(icon)
```

* Provide in your issue the Nuitka options used

  [Nuitka Options in the code](https://nuitka.net/doc/user-manual.html#nuitka-options-in-the-code)
> nuitka --mingw64 --standalone --windows-disable-console --show-progress --show-memory --output-dir=out --enable-plugin=pyside6 --windows-icon-from-ico='关机.ico' --include-data-dir=./icon=./icon  --onefile windows定时关机工具.py

* Working normally under dist folder, with icon
![image](https://user-images.githubusercontent.com/47738288/207798570-fe58b886-842e-4a5e-a72c-bc0315b9d935.png)
* Generate single file exe without icon
![image](https://user-images.githubusercontent.com/47738288/207798673-9528f2f4-d649-4775-8c9b-10a881ca3382.png)

**Comment by kayhayen** [comment]
You need to read the user manual on how to find files in standalone and onefile mode. The "icon/" style path is not working unless the file is in your current directory, which for onefile it is never, and for standalone only if you launch it through explorer, but e.g. not a changed directory.

**Comment by kayhayen** [comment]
One of the things Qt does, is to not give you a filenotfound error. Instead it will just not load things, obscuring your mistake.

**Comment by Monster-DP** [comment]
> 您需要阅读用户手册，了解如何在独立和单一文件模式下查找文件。"icon/" 样式路径不起作用，除非该文件位于您的当前目录中，对于 onefile 它永远不会，并且仅当您通过资源管理器启动它时才用于独立，但例如不是更改目录。
Okay, thank you for your answer
