### ISSUE TITLE
--follow-imports in module mode is not working as described in the documentation

### ISSUE THREAD

**Issue by OverDriveGain** [Nuitka/Nuitka#1943]
**Python, nuitka, and OS info**
1.2.6
Commercial: None
Python: 3.8.10 (default, Nov 14 2022, 12:59:47)
Flavor: Debian Python

**Installed via**
sudo apt-get install python3
pip3 install nuitka

**Issue description**
Module mode doesn't support --follow-imports, but in the  [documentation](https://nuitka.net/doc/user-manual.html) under Use Case 2 - Extension Module Compilation it states in the notes that --follow-imports is supported.

**Code example**
python3 -m nuitka --module logger.py --follow-imports

**Output**
FATAL: In module mode you must follow modules more selectively, and e.g. should not include standard library or all foreign modules or else it will fail to work. You can selectively add them with '--follow-import-to=name' though.

**Comment by kayhayen** [comment]
Thanks for your report, I have updated the section to no longer do it. It was always dumb to do that, as these kinds of modules are going to be extremely incompatible with everything else. Also added a bit of other information that related to selective exclusion of tests, and for data file embedding.

**Comment by kayhayen** [comment]
The release of 1.3 is immanent, I am closing this thefore now.
