### ISSUE TITLE
[Question] Multi-threading compiled binary?

### ISSUE THREAD

**Issue by anzhi0708** [Nuitka/Nuitka#1949]
Hi a random n00b here.

I was wondering if compiled binary executable supports multi-threading since Nuitka translates Python code to C++ code first (if that's what happened there). So I imported `threading` module and did a little bit of experiment but seemed like it was still single-threaded. Any help? :3

**Comment by kayhayen** [comment]
The Python GIL is not removed by Nuitka. You can use `multiprocessing` which will do the trick.
