### ISSUE TITLE
Using nuitka to package project with multiple modules

### ISSUE THREAD

**Issue by xennygrimmato** [Nuitka/Nuitka#195]
My python project consists of multiple python modules, some of them are nested - that is, one python module might contain another module and so on.

1. Do I need to create a binary for each top-level python module separately? Would nuitka take care of the nested modules by itself or do I need to specify some option?
2. Is there a way for nuitka to identify all existing modules in the project and generate binaries for each module on its own, instead of me manually specifying each module?

**Comment by kayhayen** [comment]
With nested modules you are referring to "package". While Nuitka currently has no explicit package mode, it's easy to make one which contains it. Check out the user manual which explains the precise command for that.

The mid term vision of Nuitka is to go through distutils. Nuitka comes with a `bdist_nuitka` target that some people are using already. In `setup.py` you specify the input as you normally would to build a wheel and then Nuitka does create a wheel, but one that necessarily architecture dependent. I cannot point you to documentation there, but there are examples in `tests/distutils` but obviously that is incomplete work, as it may not work will all cases yet.

If you happen to have a distutils integration already, try it out, and report bugs, or better, try and improve the distutils code of Nuitka yourself if you can.

I am closing this as I do with questions. Feel free to ask a followup on this question or a new one for another topic.
