### ISSUE TITLE
Set copyright notice to onefile exe

### ISSUE THREAD

**Issue by interseba5** [Nuitka/Nuitka#1951]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version

1.2.7
Commercial: None
Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Python39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

* How did you install Nuitka and Python

Installed using pip

* The specific PyPI names and versions

pip 22.0.4 from c:\python39\lib\site-packages\pip (python 3.9)

## Question 
Hi,
I wanted to ask if is it possibile to add a copyright notice to the onefile compiled exe. I have seen that you can set the company name, product and file version, but i have not found any options to set the copyright notice.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
I have added --copyright and --trademarks while at it, to set these strings.

**Comment by interseba5** [comment]
I have tried and it worked. Thank you very much for the quick fix and your awesome work!!

**Comment by kayhayen** [comment]
Spread the word if you can, or consider Nuitka commercial, with this being probably something that indicates that kind of usage.  https://nuitka.net/doc/commercial.html

**Comment by kayhayen** [comment]
This is part of the stable release 1.3 that I just made.
