### ISSUE TITLE
nuitka.exe missing in conda env Scripts folder

### ISSUE THREAD

**Issue by bago13** [Nuitka/Nuitka#1954]
Hello
I'm using a python conda environnement.

I was using python 3.6 and I recently switched to a python 3.8 and installed last nuitka stable version.
I no longer can find nuitka.exe in my env Scripts directory.

Only .bat can be found.
But nuitka utils fonction keeps searching for .exe file on windows :
`from nuitka.utils.Execution import getExecutablePath`

I can no longer use this function in my setup.py.

Best Regards,

Hugo.

**Comment by kayhayen** [comment]
I am not sure I can understand this at all.

**Comment by bago13** [comment]
Ok, 
here is the content of my miniconda\envs\PY38\Scripts :
![image](https://user-images.githubusercontent.com/74469417/209162786-f68a0b77-8bdf-4fb8-b9a8-991c4edd3c07.png)

and here is the content of my miniconda\envs\PY36\Scripts :
![image](https://user-images.githubusercontent.com/74469417/209162982-bf5dddd0-27a7-4362-b269-7a5daad84de3.png)

On windows, getExecutablePath is searching for .exe file not .bat file.
As a result with my last python env it can't find any executable nuitka file.

**Comment by kayhayen** [comment]
I think you may have jumped to conclusions rather than sharing actual information. These executables are not used by Nuitka in any way, and have been removed a long time ago. Are you comparing different versions of Nuitka here?

**Comment by bago13** [comment]
Maybe I haven't been clear.

I said in my first message that i also moved to the last version of nuitka (previously i used nuitka V0.6.17).

The only issue here is that `getExecutablePath` doesn't work on windows for the last versions of nuitka.

I use it to find nuitka executable to compile my modules in the setup.py of my project.

I found my way out by making my own function, but i thought that it might be useful for someone else to get it fixed.

here is the function i used instead of getExecutablePath:

```python
import sys
try:
    from pathlib import Path
except ImportError:
    from pathlib2 import Path

ON_WINDOWS = sys.platform.startswith('win')

def get_nuitka_executable_from_env_folder():
    entensions_to_test = (".exe", "3.exe", ".bat") if ON_WINDOWS else ("", "3")
    bindir = 'Scripts' if ON_WINDOWS else 'bin'
    path = Path(sys.executable).parent
    nuitka_binary_tmp = path / 'nuitka'
    if nuitka_binary_tmp.exists():
        return nuitka_binary_tmp

    if path.name != bindir:
        path = path / bindir

    if not path.exists():
        raise ValueError("Cannot find scripts/bin directory? %s" % path)

    nuitka_binary = str(path / 'nuitka')
    for extension_tmp in entensions_to_test:
        nuitka_binary_tmp = Path(nuitka_binary + extension_tmp)
        if nuitka_binary_tmp.exists():
            return nuitka_binary_tmp
    return None
```

**Comment by kayhayen** [comment]
You should read the user manual, the recommended way of invoking Nuitka does not use batch or exe files, but goes through "python -m", you had solved a problem that never needed to be solved.
