### ISSUE TITLE
on ubuntu 22 "/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found"

### ISSUE THREAD

**Issue by djkcyl** [Nuitka/Nuitka#1958]
I built the binary using github action, but it doesn't work on ubuntu 22, but it works fine on windows

my workflows https://github.com/djkcyl/BBot-Graia/blob/web/.github/workflows/prerelease.yml
```
python -m nuitka --onefile --standalone --show-progress --assume-yes-for-downloads --output-dir=nuitka --windows-icon-from-ico=tv.png --user-package-configuration-file=nuitka.yml main.py
```
```
root@ubuntu:~/test# ./bbot-1.2.0.beta.1ddce6c-ubuntu-nuitka 
./bbot-1.2.0.beta.1ddce6c-ubuntu-nuitka: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./bbot-1.2.0.beta.1ddce6c-ubuntu-nuitka)
./bbot-1.2.0.beta.1ddce6c-ubuntu-nuitka: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./bbot-1.2.0.beta.1ddce6c-ubuntu-nuitka)
```

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun.
