### ISSUE TITLE
Ubuntu doesn't work :  /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./main.bin)

### ISSUE THREAD

**Issue by djkcyl** [Nuitka/Nuitka#1959]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

Github Action
```
1.3.2
Commercial: None
Python: 3.9.16 (main, Dec  8 2022, 11:01:53) 
Flavor: Unknown
Executable: /opt/hostedtoolcache/Python/3.9.16/x64/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.1
Version C compiler: /usr/bin/gcc (gcc).
```

* How did you install Nuitka and Python

  `pip install nuitka zstandard orderedset`

* The specific PyPI names and versions

```
Nuitka==1.3.2
orderedset==2.0.3
zstandard==0.19.0
```

* Provide in your issue the Nuitka options used

```
python -m nuitka --onefile --standalone --assume-yes-for-downloads --output-dir=nuitka main.py
```

I downloaded the binary from the release and tested it on my own ubuntu host and it doesn't work
https://github.com/djkcyl/actiontest/releases/tag/test1

```
root@ubuntu:~/test# ./main.bin 
./main.bin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./main.bin)
./main.bin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./main.bin)
```

**Comment by kayhayen** [comment]
You might want to read the user manual about how to make Linux standalone binaries that are backwards portable.
