### ISSUE TITLE
Standalone build needs to be done on oldest system to be used

### ISSUE THREAD

**Issue by mosajjal** [Nuitka/Nuitka#196]
*  Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

0.6.1rc8 (installed via pip)
Python: 3.7.1 (default, Oct 22 2018, 10:41:28)
OS: Linux
Arch: x86_64

I've built a binary with --standalone but when I ship it to a Debian installation with Python3.6, I get this error:

```./userange: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/libpython3.7m.so.1.0)```

this means the libc.so library is not included, right? That would pose a problem for non-libc systems as well (Alpine, for example). What would be the best way to solve this?

**Comment by kayhayen** [comment]
You cannot use standalone on Linux to backport from new glibc to older systems, only the other way around. Mostly because glibc is often kernel specific and will not work.

Yours,
Kay

**Comment by mosajjal** [comment]
How about using something like `musl` similar to what Rust/Go is doing? Musl [allows](https://rust-lang-nursery.github.io/edition-guide/rust-2018/platform-and-target-support/musl-support-for-fully-static-binaries.html) to build a fully statically linked binary to be used anywhere. Python in Alpine is built based on `musl` so there must be a way to link all this together.. I'll take a look at it myself to see if it's possible in any way.

**Comment by kayhayen** [comment]
@mosajjal of course you can try that too, may also work. With the removal of fibers from Nuitka, I think it got less demanding on glibc there and ought to work now. 

I was also wondering how AnaConda builds, with its Python running everywhere without installation, it may also be a good base to use. Maybe their glibc linking is done liberal enough to not require anything current.
