### ISSUE TITLE
Nuitka times out of 4h to compile 

### ISSUE THREAD

**Issue by ilya-brykau** [Nuitka/Nuitka#1960]
Hi, Nuitka stucks during compilation and the build time goes out of 4h (1.5h) before the update.  Compilation stumbles on azure.mgmt.network.v2022_01_01.models._models_py3 even though it is one of few modules left. 1.5 works well enough

An example can be found in a previous issue: [https://github.com/Nuitka/Nuitka/issues/1791](url)

Nuitka version, full Python version, flavor, OS, etc. as output by this
command: python -m nuitka --version
1.3.2
Commercial: None
Python: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\ilya.brykau\AppData\Local\Programs\Python\Python39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe (cl 14.1).

<details open>

  <summary>Packages installed</summary>

  astroid==2.8.6 ; python_version >= "3.9" and python_version < "4.0"
atomicwrites==1.4.0 ; python_version >= "3.9" and python_version < "4.0" and sys_platform == "win32"
attrs==21.2.0 ; python_version >= "3.9" and python_version < "4.0"
azure-common==1.1.28 ; python_version >= "3.9" and python_version < "4.0"
azure-core==1.24.2 ; python_version >= "3.9" and python_version < "4.0"
azure-identity==1.10.0 ; python_version >= "3.9" and python_version < "4.0"
azure-mgmt-compute==29.0.0 ; python_version >= "3.9" and python_version < "4.0"
azure-mgmt-core==1.3.2 ; python_version >= "3.9" and python_version < "4.0"
azure-mgmt-network==21.0.1 ; python_version >= "3.9" and python_version < "4.0"
azure-mgmt-resource==21.2.1 ; python_version >= "3.9" and python_version < "4.0"
bottle==0.12.19 ; python_version >= "3.9" and python_version < "4.0"
certifi==2021.10.8 ; python_version >= "3.9" and python_version < "4.0"
cffi==1.15.0 ; python_version >= "3.9" and python_version < "4.0"
charset-normalizer==2.0.8 ; python_version >= "3.9" and python_version < "4.0"
colorama==0.4.4 ; python_version >= "3.9" and python_version < "4.0"
conan==1.54.0 ; python_version >= "3.9" and python_version < "4.0"
coverage[toml]==6.5.0 ; python_version >= "3.9" and python_version < "4.0"
cryptography==36.0.1 ; python_version >= "3.9" and python_version < "4.0"
dataclasses-json==0.5.6 ; python_version >= "3.9" and python_version < "4.0"
distro==1.6.0 ; python_version >= "3.9" and python_version < "4.0" and sys_platform == "linux" or python_version >= "3.9" and python_version < "4.0" and sys_platform == "linux2"
fasteners==0.16.3 ; python_version >= "3.9" and python_version < "4.0"
flake8==4.0.1 ; python_version >= "3.9" and python_version < "4.0"
idna==3.3 ; python_version >= "3.9" and python_version < "4.0"
inflection==0.5.1 ; python_version >= "3.9" and python_version < "4.0"
iniconfig==1.1.1 ; python_version >= "3.9" and python_version < "4.0"
isodate==0.6.1 ; python_version >= "3.9" and python_version < "4.0"
isort==5.10.1 ; python_version >= "3.9" and python_version < "4.0"
jinja2==3.0.3 ; python_version >= "3.9" and python_version < "4.0"
lazy-object-proxy==1.6.0 ; python_version >= "3.9" and python_version < "4.0"
markupsafe==2.0.1 ; python_version >= "3.9" and python_version < "4.0"
marshmallow-enum==1.5.1 ; python_version >= "3.9" and python_version < "4.0"
marshmallow==3.14.1 ; python_version >= "3.9" and python_version < "4.0"
mccabe==0.6.1 ; python_version >= "3.9" and python_version < "4.0"
msal-extensions==1.0.0 ; python_version >= "3.9" and python_version < "4.0"
msal==1.18.0 ; python_version >= "3.9" and python_version < "4.0"
msrest==0.7.1 ; python_version >= "3.9" and python_version < "4.0"
mypy-extensions==0.4.3 ; python_version >= "3.9" and python_version < "4.0"
mypy==0.971 ; python_version >= "3.9" and python_version < "4.0"
node-semver==0.6.1 ; python_version >= "3.9" and python_version < "4.0"
nuitka==1.1.5 ; python_version >= "3.9" and python_version < "4.0"
oauthlib==3.2.2 ; python_version >= "3.9" and python_version < "4.0"
orderedset==2.0.3 ; python_version >= "3.9" and python_version < "4.0"
packaging==21.3 ; python_version >= "3.9" and python_version < "4.0"
parameterized==0.8.1 ; python_version >= "3.9" and python_version < "4.0"
patch-ng==1.17.4 ; python_version >= "3.9" and python_version < "4.0"
platformdirs==2.4.0 ; python_version >= "3.9" and python_version < "4.0"
pluggy==1.0.0 ; python_version >= "3.9" and python_version < "4.0"
pluginbase==1.0.1 ; python_version >= "3.9" and python_version < "4.0"
portalocker==2.5.1 ; python_version >= "3.9" and python_version < "4.0"
psutil==5.8.0 ; python_version >= "3.9" and python_version < "4.0"
py-zabbix==1.1.7 ; python_version >= "3.9" and python_version < "4.0"
py==1.11.0 ; python_version >= "3.9" and python_version < "4.0"
pycodestyle==2.8.0 ; python_version >= "3.9" and python_version < "4.0"
pycparser==2.21 ; python_version >= "3.9" and python_version < "4.0"
pyflakes==2.4.0 ; python_version >= "3.9" and python_version < "4.0"
pygments==2.10.0 ; python_version >= "3.9" and python_version < "4.0"
pyjwt==2.6.0 ; python_version >= "3.9" and python_version < "4.0"
pyjwt[crypto]==2.6.0 ; python_version >= "3.9" and python_version < "4.0"
pylint==2.11.1 ; python_version >= "3.9" and python_version < "4.0"
pyopenssl==21.0.0 ; python_version >= "3.9" and python_version < "4.0"
pyparsing==3.0.6 ; python_version >= "3.9" and python_version < "4.0"
pytest-cov==3.0.0 ; python_version >= "3.9" and python_version < "4.0"
pytest-random-order==1.0.4 ; python_version >= "3.9" and python_version < "4.0"
pytest==6.2.5 ; python_version >= "3.9" and python_version < "4.0"
python-dateutil==2.8.2 ; python_version >= "3.9" and python_version < "4.0"
python-json-logger==2.0.2 ; python_version >= "3.9" and python_version < "4.0"
pywin32==302 ; python_version >= "3.9" and python_version < "4.0" and sys_platform == "win32" or python_version >= "3.9" and platform_system == "Windows" and python_version < "4.0"
pyyaml==5.4.1 ; python_version >= "3.9" and python_version < "4.0"
requests-oauthlib==1.3.1 ; python_version >= "3.9" and python_version < "4.0"
requests==2.26.0 ; python_version >= "3.9" and python_version < "4.0"
responses==0.16.0 ; python_version >= "3.9" and python_version < "4.0"
setuptools==65.5.1 ; python_version >= "3.9" and python_version < "4.0"
six==1.16.0 ; python_version >= "3.9" and python_version < "4.0"
teamcity-messages==1.29 ; python_version >= "3.9" and python_version < "4.0"
toml==0.10.2 ; python_version >= "3.9" and python_version < "4.0"
tomli==1.2.2 ; python_version >= "3.9" and python_full_version <= "3.11.0a6"
tqdm==4.62.3 ; python_version >= "3.9" and python_version < "4.0"
types-cryptography==3.3.14 ; python_version >= "3.9" and python_version < "4.0"
types-enum34==1.1.3 ; python_version >= "3.9" and python_version < "4.0"
types-ipaddress==1.0.3 ; python_version >= "3.9" and python_version < "4.0"
types-pyopenssl==21.0.3 ; python_version >= "3.9" and python_version < "4.0"
types-requests==2.26.1 ; python_version >= "3.9" and python_version < "4.0"
typing-extensions==4.0.1 ; python_version >= "3.9" and python_version < "4.0"
typing-inspect==0.7.1 ; python_version >= "3.9" and python_version < "4.0"
urllib3==1.26.7 ; python_version >= "3.9" and python_version < "4"
wmi==1.5.1 ; python_version >= "3.9" and python_version < "4.0" and sys_platform == "win32"
wrapt==1.13.3 ; python_version >= "3.9" and python_version < "4.0"
</details>

<details open>
  <summary>Provide in your issue the Nuitka options used</summary>
  `Nuitka-Options:INFO: Used command line options: --standalone --remove-output --nofollow-import-to=azure.mgmt.compute.aio --nofollow-import-to=azure.mgmt.compute.v2015_06_15 --nofollow-import-to=azure.mgmt.compute.v2016_03_30 --nofollow-import-to=azure.mgmt.compute.v2016_04_30_preview --nofollow-import-to=azure.mgmt.compute.v2017_03_30 --nofollow-import-to=azure.mgmt.compute.v2017_09_01 --nofollow-import-to=azure.mgmt.compute.v2017_12_01 --nofollow-import-to=azure.mgmt.compute.v2018_04_01 --nofollow-import-to=azure.mgmt.compute.v2018_06_01 --nofollow-import-to=azure.mgmt.compute.v2018_09_30 --nofollow-import-to=azure.mgmt.compute.v2018_10_01 --nofollow-import-to=azure.mgmt.compute.v2019_03_01 --nofollow-import-to=azure.mgmt.compute.v2019_04_01 --nofollow-import-to=azure.mgmt.compute.v2019_07_01 --nofollow-import-to=azure.mgmt.compute.v2019_11_01 --nofollow-import-to=azure.mgmt.compute.v2019_12_01 --nofollow-import-to=azure.mgmt.compute.v2020_05_01 --nofollow-import-to=azure.mgmt.compute.v2020_06_01 --nofollow-import-to=azure.mgmt.compute.v2020_06_30 --nofollow-import-to=azure.mgmt.compute.v2020_09_30 --nofollow-import-to=azure.mgmt.compute.v2020_10_01_preview --nofollow-import-to=azure.mgmt.compute.v2020_12_01 --nofollow-import-to=azure.mgmt.compute.v2021_03_01 --nofollow-import-to=azure.mgmt.compute.v2021_04_01 --nofollow-import-to=azure.mgmt.compute.v2021_08_01 --nofollow-import-to=azure.mgmt.compute.v2021_10_01 --nofollow-import-to=azure.mgmt.compute.v2021_11_01 --nofollow-import-to=azure.mgmt.compute.v2021_12_01 --nofollow-import-to=azure.mgmt.compute.v2022_01_03 --nofollow-import-to=azure.mgmt.compute.v2022_03_01 --nofollow-import-to=azure.mgmt.compute.v2022_03_02 --nofollow-import-to=azure.mgmt.compute.__pycache__ --nofollow-import-to=azure.mgmt.network.aio --nofollow-import-to=azure.mgmt.network.v2015_06_15 --nofollow-import-to=azure.mgmt.network.v2016_09_01 --nofollow-import-to=azure.mgmt.network.v2016_12_01 --nofollow-import-to=azure.mgmt.network.v2017_03_01 --nofollow-import-to=azure.mgmt.network.v2017_06_01 --nofollow-import-to=azure.mgmt.network.v2017_10_01 --nofollow-import-to=azure.mgmt.network.v2018_01_01 --nofollow-import-to=azure.mgmt.network.v2018_02_01 --nofollow-import-to=azure.mgmt.network.v2018_04_01 --nofollow-import-to=azure.mgmt.network.v2018_06_01 --nofollow-import-to=azure.mgmt.network.v2018_07_01 --nofollow-import-to=azure.mgmt.network.v2018_08_01 --nofollow-import-to=azure.mgmt.network.v2018_10_01 --nofollow-import-to=azure.mgmt.network.v2018_11_01 --nofollow-import-to=azure.mgmt.network.v2018_12_01 --nofollow-import-to=azure.mgmt.network.v2019_04_01 --nofollow-import-to=azure.mgmt.network.v2019_06_01 --nofollow-import-to=azure.mgmt.network.v2019_08_01 --nofollow-import-to=azure.mgmt.network.v2019_09_01 --nofollow-import-to=azure.mgmt.network.v2019_11_01 --nofollow-import-to=azure.mgmt.network.v2019_12_01 --nofollow-import-to=azure.mgmt.network.v2020_03_01 --nofollow-import-to=azure.mgmt.network.v2020_05_01 --nofollow-import-to=azure.mgmt.network.v2020_06_01 --nofollow-import-to=azure.mgmt.network.v2020_07_01 --nofollow-import-to=azure.mgmt.network.v2020_08_01 --nofollow-import-to=azure.mgmt.network.v2020_11_01 --nofollow-import-to=azure.mgmt.network.v2021_02_01 --nofollow-import-to=azure.mgmt.network.__pycache__ --nofollow-import-to=azure.mgmt.resource.changes.aio --nofollow-import-to=azure.mgmt.resource.changes.__pycache__ --nofollow-import-to=azure.mgmt.resource.deploymentscripts.aio --nofollow-import-to=azure.mgmt.resource.deploymentscripts.v2019_10_01_preview --nofollow-import-to=azure.mgmt.resource.deploymentscripts.__pycache__ --nofollow-import-to=azure.mgmt.resource.features.aio --nofollow-import-to=azure.mgmt.resource.features.v2015_12_01 --nofollow-import-to=azure.mgmt.resource.features.__pycache__ --nofollow-import-to=azure.mgmt.resource.links.aio --nofollow-import-to=azure.mgmt.resource.links.__pycache__ --nofollow-import-to=azure.mgmt.resource.locks.aio --nofollow-import-to=azure.mgmt.resource.locks.v2015_01_01 --nofollow-import-to=azure.mgmt.resource.locks.__pycache__ --nofollow-import-to=azure.mgmt.resource.managedapplications.aio --nofollow-import-to=azure.mgmt.resource.managedapplications.__pycache__ --nofollow-import-to=azure.mgmt.resource.privatelinks.aio --nofollow-import-to=azure.mgmt.resource.privatelinks.__pycache__ --nofollow-import-to=azure.mgmt.resource.resources.aio --nofollow-import-to=azure.mgmt.resource.resources.v2016_02_01 --nofollow-import-to=azure.mgmt.resource.resources.v2016_09_01 --nofollow-import-to=azure.mgmt.resource.resources.v2017_05_10 --nofollow-import-to=azure.mgmt.resource.resources.v2018_02_01 --nofollow-import-to=azure.mgmt.resource.resources.v2018_05_01 --nofollow-import-to=azure.mgmt.resource.resources.v2019_03_01 --nofollow-import-to=azure.mgmt.resource.resources.v2019_05_01 --nofollow-import-to=azure.mgmt.resource.resources.v2019_05_10 --nofollow-import-to=azure.mgmt.resource.resources.v2019_07_01 --nofollow-import-to=azure.mgmt.resource.resources.v2019_08_01 --nofollow-import-to=azure.mgmt.resource.resources.v2019_10_01 --nofollow-import-to=azure.mgmt.resource.resources.v2020_06_01 --nofollow-import-to=azure.mgmt.resource.resources.v2020_10_01 --nofollow-import-to=azure.mgmt.resource.resources.v2021_01_01 --nofollow-import-to=azure.mgmt.resource.resources.__pycache__ --nofollow-import-to=azure.mgmt.resource.subscriptions.aio --nofollow-import-to=azure.mgmt.resource.subscriptions.v2016_06_01 --nofollow-import-to=azure.mgmt.resource.subscriptions.v2018_06_01 --nofollow-import-to=azure.mgmt.resource.subscriptions.v2019_06_01 --nofollow-import-to=azure.mgmt.resource.subscriptions.__pycache__ --nofollow-import-to=azure.mgmt.resource.templatespecs.aio --nofollow-import-to=azure.mgmt.resource.templatespecs.v2019_06_01_preview --nofollow-import-to=azure.mgmt.resource.templatespecs.v2021_03_01_preview --nofollow-import-to=azure.mgmt.resource.templatespecs.v2021_05_01 --nofollow-import-to=azure.mgmt.resource.templatespecs.__pycache__ --include-package=log --enable-plugin=pylint-warnings --enable-plugin=anti-bloat --noinclude-pytest-mode=nofollow --lto=no --msvc=latest --output-dir=Y:\draas-recovery-agent\.temp\compile Y:\draas-recovery-agent\src\unified_entry.py`
</details>

**Comment by kayhayen** [comment]
Does it give any indication what it is working on so long with `--show-progress` I think that should output the current module more clearly.

**Comment by ilya-brykau** [comment]
I think it no longer reproduces. So we can close the ticket. But i would like to raise the slow azure packages compilation topic one more time. As we kind of stuck with it. The cache is not reusable, packages compilation doesn't become faster after a new release. Can we discuss what can we do about it?
I can provide a build log with --show-progress and timing so you can take a look of what can be improved here

**Comment by kayhayen** [comment]
The version change breaks caching of the modules, so it has to be recompiled once. Next attempts would have less work.
