### ISSUE TITLE
Add the ability to indicate Dependency Walker path

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [Nuitka/Nuitka#1962]
Currently we cannot specify own location for Dependency Walker. This is determined by:
https://github.com/Nuitka/Nuitka/blob/1dc7275d42820715304fe848bb786b813686bd13/nuitka/freezer/DependsExe.py#L42

It would be nice if this tool could be obtain from the `Path` variable and/or has some separate variable (same as we have for `ccache`):
https://github.com/Nuitka/Nuitka/blob/4d54b1fba3274724980686e02a933661a8659268/nuitka/build/SconsCaching.py#L83

**Comment by kayhayen** [comment]
Since the tool has no had updates for ages, why would you?

**Comment by ArkadiuszMichalski** [comment]
I want to download this tool once and put it in some permanent folder. Then, thanks to the `Path` or dedicated variable, I can indicate them dynamically. Sometimes I have to clear Nuitka's cache folders, and this causes this tool have to be downloaded again and again.

All the logic to do this exist because the `ccache` solution works similarly. The current solution is a bit confusing, because I thought that if I add both tools to `Path` then Nuitka will look for them there.  Unfortunately, this only happens for `ccache`, for `depends` I still get asking to download.

**Comment by kayhayen** [comment]
With 1.3 there are new dedicated options for clear or disable the cache in Nuitka, check these out. For `ccache` this to allow using your own binary, that may or may not be better. Check these options out, you can not clear the downloads cache, but clear other caches.

**Comment by ArkadiuszMichalski** [comment]
But it still causes me to download this tool unnecessarily:
- when I have fresh project folder
- when I have more projects then each download this tool

When I have this tool already downloaded on my own folder, I see no reason why it should be downloaded again unnecessarily (waste time and resources). But if setting own location for this tool is a problem then there's no point to changing this.

**Comment by kayhayen** [comment]
The Nuitka cache folder for downloads is user wide, not per project. So I am not copying what you say.
