### ISSUE TITLE
Question:Is there any easy method for Apple code signing in Nuitka?

### ISSUE THREAD

**Issue by emre84** [Nuitka/Nuitka#1963]
I am trying to codesign my nuitka application via codesign tool manually so I am just wondering if if there is an easy way to do it via Nuitka.

I searched all following sources: "nuitka --help, Nuitka Chat and Nuitka User guide"

What I found is just the following parameters:
--macos-signed-app-name, macos-sign-identity and macos-sign-notarization, but as I understand they are not calling explicitly codesign tool and sign my application. Am I right? They just add some variables into info.plist. So I have to code sign my tool anyway my own. I know it is not a complicated process but it is a little bit effortful to add all libraries, photos, file etc. in app folder into codesign file. 

Thanks a lot in advance.

**Comment by emre84** [comment]
Ohh I just saw that there is an _CodeSignature folder in my app. is my app already signed automatically? :D

**Comment by kayhayen** [comment]
Signing is in fact automatic and mandatory with some macOS and hardware combinations.
