### ISSUE TITLE
Some extension modules change "__file__" during the extension module loading process to "None"

### ISSUE THREAD

**Issue by thesct22** [Nuitka/Nuitka#1964]
## Nuitka version

```
1.4rc3
Commercial: None
Python: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Program Files\Python38\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\HostX64\x64\cl.exe (cl 14.2).
```

## Packages

```
cefpython3==66.1
cffi==1.15.1     
clr-loader==0.2.4
Nuitka==1.4rc3
orderedset==2.0.3
proxy-tools==0.1.0
pycparser==2.21
pythonnet==3.0.1
pywebview==3.7.2
```

```
pip install pywebview[cef]
```

## Code

```python
import webview

webview.create_window(
    "test webview", "127.0.0.1", text_select=True, min_size=(1200, 800)
)

webview.start(gui="cef")
```

## Error

> Works fine when using python webview_test.py. Opens a small empty webview window as expected. Throws following error when using webview_test.exe.

```
[CEF Python] ExceptHook: catched exception, will shutdown CEF

Traceback (most recent call last):
  File "C:\SOULTI~1\test\WEBVIE~1.DIS\webview\platforms\cef.py", line 53, in _set_dpi_mode
AttributeError: module 'sys' has no attribute '_MEIPASS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\SOULTI~1\test\WEBVIE~1.DIS\webview_test.py", line 7, in <module>
  File "C:\SOULTI~1\test\WEBVIE~1.DIS\webview\__init__.py", line 140, in start
  File "C:\SOULTI~1\test\WEBVIE~1.DIS\webview\platforms\winforms.py", line 512, in create_window
  File "C:\SOULTI~1\test\WEBVIE~1.DIS\webview\platforms\cef.py", line 210, in init
  File "C:\SOULTI~1\test\WEBVIE~1.DIS\webview\platforms\cef.py", line 55, in _set_dpi_mode
  File "C:\SOULTI~1\test\WEBVIE~1.DIS\ntpath.py", line 223, in dirname
  File "C:\SOULTI~1\test\WEBVIE~1.DIS\ntpath.py", line 185, in split
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by kayhayen** [comment]
This might also be a chance to migrate the pywebview plugin to Yaml package configuration usage, which might be possible now, while testing this.

**Comment by kayhayen** [comment]
I am totally failing to get pywebview to work. I previously had a working installtion, which was using to develop the plugin, and now I migrated the DLLs and data-files parts, however, I cannot update it due to MSVC 2022 giving me compile errors, and running your example complained about pythonet not being installed and then a System.NullReferenceException in the respective code.

That is very annoying stuff.

**Comment by kayhayen** [comment]
The closest code I could find for it is this, apparently my 3.8 has it, despite failing to upgrade:

**Comment by kayhayen** [comment]
That couldn't possibly have it, but it's from pywebview 3.5 which is what I looked previously (but not cef backend).

**Comment by kayhayen** [comment]
Using your requirements, I actually manage to install things, but I am getting this:

> RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'

**Comment by thesct22** [comment]
> I am totally failing to get pywebview to work. I previously had a working installtion, which was using to develop the plugin, and now I migrated the DLLs and data-files parts, however, I cannot update it due to MSVC 2022 giving me compile errors, and running your example complained about pythonet not being installed and then a System.NullReferenceException in the respective code.
> 
> That is very annoying stuff.

Got pythonnet error when `pip install pywebview`. Tried `pip install pywebview[cef]` and this error was not shown.

**Comment by thesct22** [comment]
> Using your requirements, I actually manage to install things, but I am getting this:
> 
> > RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'

This might help:

https://github.com/Nuitka/Nuitka/issues/1924#issuecomment-1341807874

**Comment by kayhayen** [comment]
It has issues finding stuff when launched through a symlink, which is my default setup. It went away then. I first retried the test case I had, and noticed also that "arm64" support was added for DLLs, so I enhanced that, but of course we exclude DLLs, but chromiumedge needed help, and now it's working nicely there too. Now on to your example.

**Comment by kayhayen** [comment]
There is a bug here (in this poor code, this would swallow CTRL.C and what not):    

```
    try:
        subprocess_path = os.path.join(sys._MEIPASS, 'subprocess.exe')
    except:
        subprocess_path = os.path.join(os.path.dirname(cef.__file__), 'subprocess.exe')

```

It seems that `cef.__file__` is None, which indicates a problem with the extension loader and its compatibility. I was thinking it is pretty good, but apparently not yet perfectly. There have been issues with `__file__` before and fixed, but there are a bunch of code paths in the module loading, and I need to checkout which one this is.

**Comment by thesct22** [comment]
Unrelated to this issue but, 
I had an issue with `Path(__file__).parent.absolute()` as it shows "C:\Examp~1\xyz\MAI~1.DIS\somefile.py" and not "C:\Example\xyz\main.dist\somefile.py" this causes not file not found errors in some stuff I was working with.

```python
dir = Path(__file__).parent.absolute()
dir_split = dir.parts
matches = (index for index, dir_name in enumerate(dir_split) if dir_name.endswith(".dist"))
```

Solved by using

```python
filepath = os.path.abspath(sys.argv[0])
dir = os.path.dirname(filepath)
dir = Path(dir)
dir_split = dir.parts
```

**Comment by kayhayen** [comment]
So, tracing the load, Nuitka checks the `__file__` two times. One time, during phase 1 it's not set, and Nuitka puts the correct value there, which then the extension module changes to `None` during phase 2, which Nuitka lets pass, because it only updates non-existant `__file__` values, in case the extension modules things itself, but not expecting `None` to be put there.

**Comment by kayhayen** [comment]
With that fixed, it seems better, and now fails to launch, it seems that cefpython3 must be missing at least `subprocess.exe` , which hopefully is it, but the yaml package configuration plugin doesn't yet handle exe files the way I want it to, needs fixes too I guess.

**Comment by kayhayen** [comment]
No such issues, just that I tricked myself with the yaml parser of `yes` vs `"yes"` which is ugly problem.

**Comment by kayhayen** [comment]
@thesct22 you might want to read the user manual on finding files, the path you see is a so called "short path" and works just fine.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by thesct22** [comment]
Works now.

**Comment by kayhayen** [comment]
Part of the 1.3.4 release I just made.
