### ISSUE TITLE
Standalone: Somebody needs to add data file configuration for mnemonic package

### ISSUE THREAD

**Issue by minutogit** [Nuitka/Nuitka#1966]
Reproduceable bug with nuitka1.3.2

**Systeminfo:**
Python: 3.10.6     Commercial: None     Flavor: Debian Python     OS: Linux   Arch: x86_64
Distribution: Linuxmint (based on Ubuntu) 21     Version C compiler: /usr/bin/gcc (gcc).

**create following file test_mnemonic.py with content:**
```
from mnemonic import mnemonic
mnemo = mnemonic.Mnemonic('english')
print(mnemo.generate(strength=128))
```

**Compiling command with nutika:**  nuitka3 --onefile test_mnemonic.py

**When you run the compiled binary, the following error is displayed:**

```
  Traceback (most recent call last):
  File "/tmp/onefile_1535060_1672166917_812699/test_mnemonic.py", line 2, in <module>
    mnemo = mnemonic.Mnemonic('english')
  File "/tmp/onefile_1535060_1672166917_812699/mnemonic/mnemonic.py", line 71, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/onefile_1535060_1672166917_812699/mnemonic/wordlist/english.txt'
```

**Comment by kayhayen** [comment]
Consider https://nuitka.net/doc/nuitka-package-config.html#data-files and making a PR out of it.

**Comment by kayhayen** [comment]
It seems like nobody is acting on this, which is a pity. Consider the tools used in https://nuitka.net/posts/nuitka-package-config-kickoff.html which should help a lot more than the docs, which however have also improved since.

**Comment by kayhayen** [comment]
Thanks for working on it, very much appreciated.
