### ISSUE TITLE
Question: How to solve "FATAL: Error, Visual Studio required for using ClangCL on Windows" ?

### ISSUE THREAD

**Issue by DaliaMokhtar** [Nuitka/Nuitka#1968]
while trying to use Nuitka on anaconda prompt to obfuscate python script **pass.py**
(would like to use clang compiler not gcc)
after typing below cmd:

`python -m nuitka --clang --follow-imports pass.py`
it shows this error message:

`FATAL: Error, Visual Studio required for using ClangCL on Windows.`
However I've installed Microsoft visual studio community 2022 edition with C++ and python packages
where is the problem?

using anaconda python 3.9.13
using anaconda Nuitka 0.6.16
OS: windows 11

**Comment by kayhayen** [comment]
You need to install the Clang components as well. 

Your Nuitka is ancient btw, and conda-forge has newer ones for a long time already, that will be working much better.

**Comment by DaliaMokhtar** [comment]
it solved by below steps:<br>
1)installed individual components from visual studio installer:<br>

[![enter image description here][1]][1]
<br>
2)added to path system variable: clang.exe, clang++.exe and clang-cl.exe paths, in my system they are in:

      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\bin
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\bin
      C:\Users\Dalia\anaconda3\pkgs\clang-14.0.6-h44fa016_0\Library\bin\


  [1]: https://i.stack.imgur.com/a1TSA.png
