### ISSUE TITLE
[Termux] WARNING: unused DT entry: DT_RPATH

### ISSUE THREAD

**Issue by anzhi0708** [Nuitka/Nuitka#1971]
Hi, I'm not sure if it's a Termux issue or Android problem, both my 32-bit & 64-bit ARM Android phone complains about `unused DT entry (ignoring)`. The compiled binary runs smoothly tho. 

Anyway I don't think this is a Nuitka issue but any ideas pls? :3

**Comment by LinuxUserGD** [comment]
Related issue: https://github.com/Nuitka/Nuitka/issues/1673#issuecomment-1186302390

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun.
