### ISSUE TITLE
No Clang component for MSVC found

### ISSUE THREAD

**Issue by DaliaMokhtar** [Nuitka/Nuitka#1977]
I'm using anaconda Nuitka packages to obfuscate my python script PASS.py
I've done below steps:

1. installed Microsoft visual studio community edition 2022 with python development and Desktop development with C++

2. installed individual components:
![Screenshot 2023-01-03 141629](https://user-images.githubusercontent.com/45294101/210361059-c2416451-06a0-424c-8c8c-941e17a9923f.png)
![Screenshot 2023-01-03 141652](https://user-images.githubusercontent.com/45294101/210361070-f3ad3a94-08e5-4905-b95e-8ce3d765ffb9.png)

3. I have also installed microsoft_build_tools_2015_update_3_x86_x64 and visual_2015_redistributable_update_3_x86

4. added to path system variable: clang.exe, clang++.exe and clang-cl.exe, in my system there are in:

    C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\bin
    C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\bin
    C:\Users\Dalia\anaconda3\pkgs\clang-14.0.6-h44fa016_0\Library\bin\

on anaconda prompt, I run below command

`python -m nuitka --clang --follow-imports PASS.py`

it shows below message:
```
 Nuitka-Options:INFO: Used command line options: --clang --follow-imports PASS.py
    Nuitka:INFO: Starting Python compilation with Nuitka '0.6.16' on Python '3.9' commercial None.
    Nuitka:INFO: Completed Python level compilation and optimization.
    Nuitka:INFO: Generating source code for C backend compiler.
    Nuitka:INFO: Running data composer tool for optimal constant value handling.
    Nuitka:INFO: Running C level backend compilation via Scons.
    TypeError: not all arguments converted during string formatting:
      File "C:\Users\Dalia\ANACON~1\lib\SITE-P~1\nuitka\build\Backend.scons", line 334:
        addClangClPathFromMSVC(env=env, target_arch=target_arch)
      File "C:\Users\Dalia\anaconda3\lib\site-packages\nuitka\build\SconsUtils.py", line 315:
        scons_details_logger.info("No Clang component for MSVC found." % clang_dir)
```
Nuitka version: 0.6.16
python version: 3.9
OS: windows 11

**Comment by Maxwell175** [comment]
Please try again with a newer version of Nuitka. You have a version that is well over a year old.

**Comment by kayhayen** [comment]
I wonder why Anaconda does not give them the newer versions of the package that I maintain.

**Comment by DaliaMokhtar** [comment]
it's solved by writing command without "--clang":
`python -m nuitka --follow-imports PASS.py`
