### ISSUE TITLE
Conflicting DLLs when using PyQt5 + ZeroMQ

### ISSUE THREAD

**Issue by TechnicalPirate** [Nuitka/Nuitka#198]
**System Info**
0.6.0.6
Python: 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)]
Executable: C:\Users\user\.virtualenvs\Nuitka_Test_moXy6b\Scripts\python.exe
OS: Windows
Arch: x86

**Nuitka Installation Method** - Pip

**Venv** - Yes created via `pipenv` 

**Regression?** No - first time using Nuitka

**Reproduction** - Attempt to compile with both `pyzmq` and `PyQt5` as imports

**Command Used** - `python -m nuitka --follow-imports --recurse-all --plugin-enable=qt-plugins --python-flag=nosite --force-dll-dependency-cache-update --standalone NuitkaTest/start_app.py --output-dir=nuitka_build`   ( and a couple of variations while testing, but same behavior consistently ) 

**Conflicting DLLs** - `concrt140.dll` `msvcp140.dll`

**Error Sample** - `Error, conflicting DLLs for 'concrt140.dll'.
c:\users\joe.deuchar\.virtualenvs\kat-hub-tng-g-moxy6b\lib\site-packages\pyqt5\qt\bin\concrt140.dll used by:
   **snip - basically all Qt .pyds**
different from
c:\users\joe.deuchar\.virtualenvs\kat-hub-tng-g-moxy6b\lib\site-packages\zmq\concrt140.dll used by
   n_build\start_hub.dist\zmq\libzmq.pyd`

**Dependencies / PipFreeze**
certifi==2018.10.15
chardet==3.0.4
idna==2.7
influxdb==5.0.0
katagentapi==0.0.1
katapi==2.0.0rc0
katlog==0.0.1
lxml==4.2.5
Nuitka==0.6.0.6
pathlib==1.0.1
PyGithub==1.35
PyJWT==1.5.3
PyQt5==5.7.1
python-dateutil==2.7.5
pytz==2018.7
pyzmq==17.1.2
requests==2.20.1
sip==4.19.8
six==1.11.0
splunk-handler==2.0.8
urllib3==1.24.1

**Comment by kayhayen** [comment]
These ones are rejected from pip for me:

```
katagentapi==0.0.1
katapi==2.0.0rc0
katlog==0.0.1
```

I am assuming they don't matter. I am missing a main program from you, so I assume you mean `import PyQt5; import pyzmq` as the test case.

**Comment by kayhayen** [comment]
I am totally unsure how Nuitka can possibly decide which of those DLL to use. It should be impossible to load both, and which one is loaded should depend on which imports and uses of the module occur first, so that is nothing to be able to predict.

The one DLL is higher version than the other, so that might be a criterion to go with, in making that decision.

So far this error message has mostly only served to find errors in the selection process. Normally when this has occurred, Nuitka had two copies of a DLL for bad reasons. This is the first time it happens where it is not at fault, but rather the situation is normal.

I am tempted now, to make the PyQt plugin which is responsible for injecting these, handle a decision, where its own DLLs loose more often and stir the decision to pick the newest version of the DLL. Then the impact will be limited, and bugs should they still exist, can be revealed. On the other hand, they have become rare, and it's probably not worth it anymore.

**Comment by TechnicalPirate** [comment]
Hey!

Thanks for the responses, you're correct the missing packages are in house
stuff that's not on pypi.

I'm currently away from the office where I have my work machine and will be
back on the 2nd,I'll aim to make a minimal reproduction for you then!

Hope you're having a good festive season and wishing you a happy new year
:-)

~Joe

**Comment by kayhayen** [comment]
Thanks, I managed to reproduce the issue anyway, and implemented the detection of DLL version working for at least Python3, and based on that, give a warning and proceed:

```
Nuitka:WARNING:Ignoring conflicting DLLs for 'msvcp140.dll' and using newest file version.
Nuitka:WARNING:Ignoring conflicting DLLs for 'concrt140.dll' and using newest file version.
```


However,  this reveals another issue:

```
$ ./Mini.dist/Mini.exe
Traceback (most recent call last):
  File "C:\Users\kayha\test\issue198\Mini.dist\Mini.py", line 2, in <module>
  File "C:\Users\kayha\test\issue198\Mini.dist\zmq\__init__.py", line 47, in <module zmq>
  File "C:\Users\kayha\test\issue198\Mini.dist\zmq\backend\__init__.py", line 40, in <module zmq.backend>
  File "C:\Users\kayha\test\issue198\Mini.dist\zmq\utils\sixcerpt.py", line 34, in reraise
  File "C:\Users\kayha\test\issue198\Mini.dist\zmq\backend\__init__.py", line 27, in <module zmq.backend>
  File "C:\Users\kayha\test\issue198\Mini.dist\zmq\backend\select.py", line 27, in select_backend
ImportError: No module named 'zmq.backend.cython'
```

It seems zmq plays some "plugin" tricks, that need to be dealt with too. But the DLL collision issue seems resolved. I will look into this zmq next though, hoping however it reproduces on Linux.

Yours,
Kay

**Comment by kayhayen** [comment]
So there is now code on the factory branch which makes the DLL decision and something that makes sure the standard cython backend for zmq is available. Not sure what zmq is doing with it though, I would be grateful for a minimal test that exercises zmq so I can cover more than `import zmq` to work.

Yours,
Kay

**Comment by kayhayen** [comment]
This is now on develop and soon in a release, closing the issue therefore.
