### ISSUE TITLE
Missing dependencies for "transformers" module

### ISSUE THREAD

**Issue by StyriamMZ** [Nuitka/Nuitka#1980]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

> $ python -m nuitka --version
> 1.3.5
> Commercial: None
> Python: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
> Flavor: Unknown
> Executable: E:\PythonProjects\GPT3_Assistant\\.env\Scripts\python.exe
> OS: Windows
> Arch: x86_64
> WindowsRelease: 7
> Version C compiler: D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\cl.exe (cl 14.2).

* How did you install Nuitka and Python

  Nuitka installed via pip in venv. ordered-sets and dependency walker installed.

* The specific PyPI names and versions

> $ python -m pip freeze               
> altgraph==0.17.3                     
> certifi==2022.12.7                   
> charset-normalizer==2.1.1            
> colorama==0.4.6                      
> et-xmlfile==1.1.0                    
> filelock==3.9.0                      
> future==0.18.2                       
> huggingface-hub==0.11.1              
> idna==3.4                            
> Nuitka==1.4rc6                       
> numpy==1.24.1                        
> openai==0.25.0                       
> openpyxl==3.0.10                     
> ordered-set==4.1.0                   
> packaging==22.0                      
> pandas==1.5.2                        
> pandas-stubs==1.5.2.221213           
> pefile==2022.5.30                    
> pygubu==0.28                         
> pyinstaller==5.7.0                   
> pyinstaller-hooks-contrib==2022.14   
> python-dateutil==2.8.2               
> pytz==2022.7                         
> pywin32-ctypes==0.2.0                
> PyYAML==6.0                          
> regex==2022.10.31                    
> requests==2.28.1                     
> six==1.16.0                          
> tokenizers==0.13.2                   
> tqdm==4.64.1                         
> transformers==4.25.1                 
> types-pytz==2022.7.0.0               
> typing_extensions==4.4.0             
> urllib3==1.26.13                     

* Many times when you get an error from Nuitka, your setup may be special

  Project compiles and starts successfully without huggingface transformers.

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

```
#!/usr/bin/python3
# nuitka-project: --include-package=tqdm
# nuitka-project: --include-package=regex
# nuitka-project: --include-package=requests
# nuitka-project: --include-package=packaging
# nuitka-project: --include-package=filelock
# nuitka-project: --include-package=numpy
# nuitka-project: --include-package=tokenizers

from transformers import GPT2TokenizerFast

if __name__ == "__main__":
    print('hello')
```

* Provide in your issue the Nuitka options used

```
Project settings:
# nuitka-project: --include-data-files={MAIN_DIRECTORY}/editor.ui=editor.ui
# nuitka-project: --enable-plugin=tk-inter
# nuitka-project: --include-package=pygubu
# nuitka-project: --include-package=tqdm
# nuitka-project: --include-package=regex
# nuitka-project: --include-package=requests
# nuitka-project: --include-package=packaging
# nuitka-project: --include-package=filelock
# nuitka-project: --include-package=numpy
# nuitka-project: --include-package=tokenizers
```

In my venv terminal:
> python -m nuitka --follow-imports --show-progress --show-modules --standalone __init__.py

At first, before adding all --include-package but pygubu I ended up with an error:
> importlib.metadata.PackageNotFoundError: No package metadata was found for tqdm

I got the same error in pyinstaller, so ended up adding one more package after each failed compilation (or freezing? whatever the correct name is).
pyinstaller works 10x faster so it was more feasible to test it step by step than in Nuitka. At this moment I don't know better way to find hidden imports.

The point is, pyinstaller works with this configuration but the program made with Nuitka returned:
Traceback (most recent call last):

```
Traceback (most recent call last):
  File "E:\PYTHON~1\GPT3_A~1\__INIT~1.DIS\__init__.py", line 31, in <module>
  File "E:\PYTHON~1\GPT3_A~1\__INIT~1.DIS\transformers\__init__.py", line 30, in <module transformers>
  File "E:\PYTHON~1\GPT3_A~1\__INIT~1.DIS\transformers\dependency_versions_check.py", line 17, in <module transformers.dependency_versions_check>
  File "E:\PYTHON~1\GPT3_A~1\__INIT~1.DIS\transformers\utils\__init__.py", line 59, in <module transformers.utils>
  File "E:\PYTHON~1\GPT3_A~1\__INIT~1.DIS\transformers\utils\hub.py", line 32, in <module transformers.utils.hub>
  File "E:\PYTHON~1\GPT3_A~1\__INIT~1.DIS\huggingface_hub\__init__.py", line 254, in __getattr__
  File "importlib.py", line 126, in import_module
ModuleNotFoundError: No module named 'huggingface_hub.hf_api'
```

**Comment by kayhayen** [comment]
This good report has escaped my attention so far.

One quick note about your usage of `--include-package=numpy` and others. These should have to be unnecessary, and I am not sure why you would want to include e.g. `numpy.random._examples.cython.setup` or `numpy.typing.tests.test_typing` which makes no sense to me. Actually it's beyond reason. 

With other tools that may be what you do, but I invite you to join the Yaml improvement club: https://nuitka.net/posts/nuitka-package-config-kickoff.html

Not sure now if you just felt like that would be a migration, or if you actually encountered issues that lead to your set of options.

Right now I am doing a bit of anti-bloat work for tokenizer, but of course that will hit a wall. Howeve, huggingface I actually care about. I wonder why that one didn't get an include though. :)

**Comment by kayhayen** [comment]
I managed to reproduce it without the package includes you have.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.5.4 that I just made.

**Comment by ryango** [comment]
I see `Traceback (most recent call last):
  File "E:\PYTHON~1\GPT3_A~1\__INIT~1.DIS\__init__.py", line 31, in <module>
  File "E:\PYTHON~1\GPT3_A~1\__INIT~1.DIS\transformers\__init__.py", line 30, in <module transformers>
  File "E:\PYTHON~1\GPT3_A~1\__INIT~1.DIS\transformers\dependency_versions_check.py", line 17, in <module transformers.dependency_versions_check>
  File "E:\PYTHON~1\GPT3_A~1\__INIT~1.DIS\transformers\utils\__init__.py", line 59, in <module transformers.utils>
  File "E:\PYTHON~1\GPT3_A~1\__INIT~1.DIS\transformers\utils\hub.py", line 32, in <module transformers.utils.hub>
  File "E:\PYTHON~1\GPT3_A~1\__INIT~1.DIS\huggingface_hub\__init__.py", line 254, in __getattr__
  File "importlib.py", line 126, in import_module
ModuleNotFoundError: No module named 'huggingface_hub.hf_api'`

on 1.5.4. Any tips?

**Comment by kayhayen** [comment]
@ryango Posting below closed issues is a surefire way to get ignored. I am not going to guess without a fresh issue template, what kinds of mistakes and setup you have made.
