### ISSUE TITLE
Built-in `ellipsis` object is used instead of custom `Ellipsis` class

### ISSUE THREAD

**Issue by Aksem** [Nuitka/Nuitka#1981]
**Problem:** if class `Ellipsis` is defined, built-in `ellipsis` object is used instead.

Minimal example to get idea:
```python
from dataclasses import dataclass


@dataclass
class Ellipsis:
    ...


print(Ellipsis.__name__) # AttributeError: 'ellipsis' object has no attribute '__name__'
```

In CPython it works well. And it would be not so big problem if only my code didn't work, but I found this problem when I tried to compile app with [libcst](https://github.com/Instagram/LibCST) package([Ellipsis class](https://github.com/Instagram/LibCST/blob/main/libcst/matchers/_return_types.py#L246)  and [its usage](https://github.com/Instagram/LibCST/blob/main/libcst/matchers/_visitors.py#L58)).

Repository with minimal example to reproduce the issue: https://github.com/Aksem/nuitka_load_module_regression. It also includes configured CI to compile the program with Nuitka 1.3.5 and factory.

**Nuitka version:** 1.3.5+ (tested 1.3.5, factory)
**Environment:** Python 3.10.9 installed via pyenv, Nuitka installed via poetry. All OS: Linux/Ubuntu, macOS, Windows.
**Nuitka version output:**

1.3.5
Commercial: None
Python: 3.10.9 (main, Dec  7 2022, 08:15:20) [GCC 9.4.0]
Flavor: Unknown
Executable: /home/runner/.cache/pypoetry/virtualenvs/nuitka-compile-ellipsis-bug-GEwdtZaC-py3.10/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 20.04.5
Version C compiler: /usr/bin/gcc (gcc).

**Nuitka parameters:** --standalone --follow-imports([reference in example](https://github.com/Aksem/nuitka_load_module_regression/blob/main/.github/workflows/ci.yml#L94)).

**Execution logs**(last lines):
```
Execute: nuitka_compile_ellipsis_bug/main.py:5 <Node 
'STATEMENT_RELEASE_VARIABLE_LOCAL' with {'variable_name': '__class__', 'owner': 
'__main__$$$class__1_Ellipsis'}>
Execute: nuitka_compile_ellipsis_bug/main.py:5 <Node 
'STATEMENT_RETURN_RETURNED_VALUE'>
Execute: nuitka_compile_ellipsis_bug/main.py:5 <Node 
'STATEMENT_RELEASE_VARIABLE_TEMP' with {'variable_name': 
'class_creation_1__class_decl_dict', 'owner': '__main__'}>
Execute: nuitka_compile_ellipsis_bug/main.py:5 <Node 
'STATEMENT_RELEASE_VARIABLE_TEMP' with {'variable_name': 
'class_creation_1__metaclass', 'owner': '__main__'}>
Execute: nuitka_compile_ellipsis_bug/main.py:5 <Node 
'STATEMENT_RELEASE_VARIABLE_TEMP' with {'variable_name': 
'class_creation_1__prepared', 'owner': '__main__'}>
Execute: nuitka_compile_ellipsis_bug/main.py:10 <Node 
'STATEMENT_RAISE_EXCEPTION_IMPLICIT'>
main(): Exited from __main__.
Traceback (most recent call last):
  File 
"/home/runner/work/nuitka_compile_ellipsis_bug/nuitka_compile_ellipsis_bug/main.
dist/main.py", line 10, in <module>
AttributeError: 'ellipsis' object has no attribute '__name__'
```

**Comment by kayhayen** [comment]
For some reason, I put "Ellipsis" on the level of "True" and "False" with respect to being allowed to override. Obviously not a good idea, esp. given how rarely it is used in that form anyway.

```
class Ellipsis:
    ...

print(Ellipsis)
```

Already shows the difference.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by Aksem** [comment]
Just tested in example repo, it works! Thanks for the fix!

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.3.6 that I just made.
