### ISSUE TITLE
exe can't be opened with no hint

### ISSUE THREAD

**Issue by monchin** [Nuitka/Nuitka#1982]
Hello, this issue is actually not a bug. 

I used pyside6 and nuitka to finish a little gui program, with `--standalone` to make it usable even on windows 10 computers without python. It worked well on my computer and several computers of my colleagues. But on one computer, it just couldn't be opened, and there was no any hint. When double clicked, there was no reaction, and when in CMD typed `.\main.exe` and `enter`, there was still no reaction. 

I'm sure the program is definitly correct, and I guess maybe that something is missing on that computer so the program couldn't be opened, but I don't know what it is because there was no hint. Is there any way to make me know the reason why it couldn't be opened on that computer? Any suggestions would be appreciated. Thank you!

All the computers are win10.

**Comment by kayhayen** [comment]
Feel free to read the user manual of Nuitka.

**Comment by monchin** [comment]
> Feel free to read the user manual of Nuitka.
@kayhayen 
I'm sorry, but it seems the user manual doesn't tell me what files lacked would result to a no-reaction open in some computer. I have used `--standalone` and it worked well in most computers without python, except that one computer, but I don't know the reason. So I would like to know if anyone has met this situation before and if there is any solutions.
