### ISSUE TITLE
Error installing depends.exe on Windows

### ISSUE THREAD

**Issue by dcsoft4** [Nuitka/Nuitka#1984]
The first time using Nuitka after installation resulted in failure to install `depends.exe`:

    Detecting used DLLs: 0.0%|                         | 0/37, mainscratch.exeNuitka will make use of Dependency Walker 
    (https://dependencywalker.com) tool
    to analyze the dependencies of Python extension modules.
    
    Is it OK to download and put it in 'C:\Users\David\AppData\Local\Nuitka\Nuitka\Cache\downloads\depends\x86_64'.
    
    No installer needed, cached, one time question.
    
    Proceed and download? [Yes]/No
    yes
    Nuitka:INFO: Downloading 'https://dependencywalker.com/depends22_x64.zip'.
    Nuitka:INFO: Extracting to 'C:\Users\David\AppData\Local\Nuitka\Nuitka\Cache\downloads\depends\x86_64\depends.exe'
    Nuitka:INFO: Problem with the downloaded zip file, deleting it.
    FATAL: Error, need 'depends.exe' as extracted from 'https://dependencywalker.com/depends22_x64.zip'.

Cause:  The issue is `https://` does not work.  You must use `http://dependencywalker.com/depends22_x64.zip` as their SSL cert is not valid.

Workaround:  Manually download the file and install to the indicated Nuitka Cache folder.

Reproduced configuration:

> python -m nuitka --version

    1.3.6
    Commercial: None
    Python: 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
    Flavor: CPython Official
    Executable: C:\Program Files\Python39\python.exe
    OS: Windows
    Arch: x86_64
    WindowsRelease: 10
    Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\cl.exe (cl 14.3).

* How did you install Nuitka and Python

    pip install Nuitka

> python -m pip freeze

    certifi==2021.5.30
    charset-normalizer==2.0.6
    idna==3.2
    Nuitka==1.3.6
    orderedset==2.0.3
    PySide6==6.4.0.1
    PySide6-Addons==6.4.0.1
    PySide6-Essentials==6.4.0.1
    python-dateutil==2.8.2
    pywin32==301
    requests==2.26.0
    shiboken6==6.4.0.1
    six==1.16.0
    urllib3==1.26.7
    zstandard==0.16.0

* Provide in your issue the Nuitka options used

    python -m nuitka --follow-imports --enable-plugin=pyside6 mainscratch.py

**Comment by kayhayen** [comment]
You mean like the code does:

```
            try:
                urlretrieve(url, download_path)
            except Exception as e:  # Any kind of error, pylint: disable=broad-except
                try:
                    urlretrieve(url.replace("https://", "http://"), download_path)
                except Exception:  # Any kind of error, pylint: disable=broad-except
                    Tracing.general.sysexit(
                        "Failed to download '%s' due to '%s'. Contents should manually be copied to '%s'."
                        % (url, e, download_path)
                    )
```

**Comment by kayhayen** [comment]
Your statement about the certificate being invalid is probably an inference from being unable to download with your Python either way, not true at all.

**Comment by dcsoft4** [comment]
Sorry, it seems the problem is related to the MalwareBytes anti-virus I am using.
