### ISSUE TITLE
api-ms-win-core-path-l1-1-0.dll missing

### ISSUE THREAD

**Issue by Jalkhov** [Nuitka/Nuitka#1986]
* **Nuitka version**
	1.3.3                                                                                   
	Commercial: None                                                                        
	Python: 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:01:48) [MSC v.1929 32 bit (Intel)]
	Flavor: CPython Official                                                                
	Executable: C:\Users\master\envs\aotsystem-QAhCQOwZ\Scripts\python.exe  
	OS: Windows                                                                             
	Arch: x86                                                                               
	WindowsRelease: 10

* **How did you install Nuitka and Python**
  I have used PIP, i am working in a Pipenv virtual enviroment

* Nuitka full command
 `pipenv run python -m nuitka aotsystem.py --standalone --include-data-dir=src=src --windows-icon-from-ico=logo.ico`

 Before I would like to give some details of my case that I think are important. My system architecture is x64, but the virtual environment where I am is x32 due to customer requirements (the target OS is Windows 7). I continue, the compilation of nuitka is done satirfactorily, and the executable behaves perfectly in my own computer, but when I try to run it in a virtual machine with Windows 7 x32 Bits I get a warning where it says that the `api-ms-win-core-path-l1-1-0.dll` is missing.

 I do not intend to compare but I just want to point out that in PyInstaller there is an option to search for the dlls needed for the executable to work and adds them automatically, I wanted to know if there was something similar in Nuitka, or what is recommended to fix this situation. I note that the virtual environment has drivers and everything is up to date.

**Comment by kayhayen** [comment]
There is https://nuitka.net/doc/user-manual.html#windows-standalone-program-redistribution which I think currently suggests that these API DLLs are included and might be removed, where they are never included. It's hard to find systems without a runtime, freshly setup VMs are among them, but installing any amount of software these will be there already, and so they are not included.

Nuitka includes DLLs by default of course.
