### ISSUE TITLE
joblib bug: ImportError: cannot import name 'make_memmap'

### ISSUE THREAD

**Issue by mingwugmail** [Nuitka/Nuitka#199]
*  python -m nuitka --version
0.6.0.6
Python: 2.7.12 (default, Nov 19 2016, 06:48:10) 
OS: Linux
Arch: x86_64

*  How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
   what is a virtualenv ...), this is very important usually.

pip in virtualenv

```
$ cat joblib_bug.py 
# python -m nuitka --follow-imports joblib_bug.py

from joblib import Parallel, delayed
from math import sqrt

def p():
  l = Parallel(n_jobs=1)(delayed(sqrt)(i**2) for i in range(10))
  print(l)

if __name__ == '__main__':
  p()
```

```
$ python --version
Python 2.7.12

$ python joblib_bug.py
[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]
```

compiled with: 
python -m nuitka --follow-imports joblib_bug.py
then

```
$ ./joblib_bug.bin 
Traceback (most recent call last):
  File "/home/.../joblib_bug.py", line 3, in <module>
    from joblib import Parallel, delayed
  File "/home/.../mypy/local/lib/python2.7/site-packages/joblib/__init__.py", line 121, in <module joblib>
    from .memory import Memory, MemorizedResult
  File "/home/.../mypy/local/lib/python2.7/site-packages/joblib/memory.py", line 37, in <module joblib.memory>
    from . import numpy_pickle
  File "/home/.../mypy/local/lib/python2.7/site-packages/joblib/numpy_pickle.py", line 29, in <module joblib.numpy_pickle>
    from .backports import make_memmap
ImportError: cannot import name 'make_memmap'

```

**Comment by kayhayen** [comment]
I need to look at joblib, and how it achieves its parallel stuff. The imports themselves are innocent, and joblib didn't yet start to use anything though, at this point.

**Comment by kayhayen** [comment]
Trying to reproduce, this worked for me, probably dependent on joblib specific version. I was using the one in Debian. I will retry with pip installing latest later today.

**Comment by kayhayen** [comment]
So on Debian Testing, where I tried next, it gives me this:
```
    from ._store_backends import StoreBackendBase, FileSystemStoreBackend
  File "/usr/lib/python2.7/dist-packages/joblib/_store_backends.py", line 16, in <module joblib._store_backends>
    from .backports import concurrency_safe_rename
ImportError: cannot import name 'concurrency_safe_rename'
```

I will try and find out what this can be, maybe threaded imports, for which the Python 3.4 protection with `__initializing__` is not effective, on the other hand this wasn't yet threading at all.

**Comment by kayhayen** [comment]
So this is related to .pth files. These are used to create namespace packages, e.g. "backports" in my home directory on the Buster machine. And the check for the ".pth" namespace was ignoring the package part, and therefore mistaking that "backports" as "joblib.backports".

I guess this kind of collision is rare enough to not have been observed so far. I will soon release a fix to the factory branch and include it in the next release.

**Comment by kayhayen** [comment]
This is now on develop and soon in a release, closing the issue therefore.
