### ISSUE TITLE
Check for zstandard before compilation when using --onefile

### ISSUE THREAD

**Issue by Duckle29** [Nuitka/Nuitka#1996]
Hi there, and thanks for an amazing bit of software :)

I'm packaging a small app that uses pandas, and as such compilation takes a while.  
Because of this it'd be nice if Nuitka checked for optional dependencies as the first thing, like it does with `oredered-set`

A quick warning with `"Won't be able to compress onefile executable as zstandard dependency isn't installed"` or similar would be nice :)

```
python -m nuitka --version
1.3.7
Commercial: None
Python: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\mjep\AppData\Local\pypoetry\Cache\virtualenvs\mtf-criticals-lMkUpbCG-py3.10\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\cl.exe (cl 14.3).
```

### How did you install Nuitka and Python
Installed into app venv via py poetry

### Options

using --standalone and --onefile

**Comment by kayhayen** [comment]
You are more than welcome to create the PR that implements it.

**Comment by Duckle29** [comment]
Seems solved and merged here https://github.com/Nuitka/Nuitka/pull/2004 Thanks :)

**Comment by Duckle29** [comment]
Woops, no closing. forgot

**Comment by kayhayen** [comment]
Indeed, and 1.4 was released with it, but this was never tracked through develop.
