### ISSUE TITLE
Question:is it possible use nuitka for Android apps?

### ISSUE THREAD

**Issue by emre84** [Nuitka/Nuitka#2001]
is it possible use nuitka for Android apps? Only documentation What I found is following:
https://github.com/Nuitka/Nuitka/issues/1163

**Comment by kayhayen** [comment]
It is indeed possible, but not every Python is going to work. It seems #1948 makes the other issues obsolete. Either Termux improved or Nuitka did, but there wasn't really anything missing, just that the Linux detection was complaining about an unknown OS.
