### ISSUE TITLE
Problem with compiling mplcairo backend for matplotlib

### ISSUE THREAD

**Issue by sevostyanov97** [Nuitka/Nuitka#2005]
I'm trying to use Nuitka to compile my GTK3-based project with matplotlib. It works fine if I use [the builtin backend GTK3Agg](https://matplotlib.org/stable/users/explain/backends.html#the-builtin-backends), but I'm going to use [mplcairo backend](https://github.com/matplotlib/mplcairo).

I created a minimal reproducible example:

```python
import mplcairo
```

and tried to compile it with the following command:

```
python -m nuitka --standalone example.py
```

On executing the compiled program `__PROJECT_PATH___/example.dist/example`, the following error appeared:

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load`
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pydoc'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "__PROJECT_PATH___/example.dist/example.py", line 1, in <module>
  File "__PROJECT_PATH___/example.dist/mplcairo/__init__.py", line 27, in <module mplcairo>
ImportError: initialization failed
Fatal Python error: PyThreadState_Get: the function must be called with the GIL held, but the GIL is released (the current Python thread state is NULL)
Python runtime state: finalizing (tstate=0x00000000068f51d0)

Aborted (core dumped)
```

List of my Python packages inside a venv `python -m pip list`:
```
Package         Version
--------------- -------
contourpy       1.0.7
cycler          0.11.0
fonttools       4.38.0
kiwisolver      1.4.4
matplotlib      3.6.3
mplcairo        0.5
Nuitka          1.3.8
numpy           1.24.1
ordered-set     4.1.0
packaging       23.0
Pillow          9.4.0
pip             22.3.1
pycairo         1.23.0
pyparsing       3.0.9
python-dateutil 2.8.2
setuptools      59.6.0
six             1.16.0
```
The command I used to install the packages: `python -m pip install mplcairo nuitka ordered-set`

Nuitka, Python and GCC version `python -m nuitka --version`:
```
1.3.8
Commercial: None
Python: 3.10.9 (main, Dec  7 2022, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]
Flavor: Fedora Python
Executable: __PROJECT_PATH___/venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Fedora 36
Version C compiler: /usr/lib64/ccache/gcc (gcc).
```
I also tried to compile it with Clang `clang --version`:
```
clang version 14.0.5 (Fedora 14.0.5-2.fc36)
Target: x86_64-redhat-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
using the command
```
python -m nuitka --standalone --clang example.py
```
but it gave a simple `Aborted (core dumped)` error.

My questions are:
- Is it possible to compile the mplcairo backend with Nuitka?
- If so, how?

**Comment by kayhayen** [comment]
The `pydoc` is not included automatically by Nuitka and seems to be a hidden dependency of some sorts. You may already have success with `--include-module=pydoc`. There have been C extension that use it, this appears to be another one. I will check it out now.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
As an aside, using latest Fedora is not going to produce very portable Linux binaries. This is not yet as present in the docs as it should be. Basically you need to build on the oldest system, unfortunately. Nuitka commercial has a container base build that does build on CentOS 7 for this reason.
