### ISSUE TITLE
Android Termux: library "libpython3.10.so.1.0" not found: needed by main executable

### ISSUE THREAD

**Issue by LinuxUserGD** [Nuitka/Nuitka#2008]
* Nuitka version, full Python version, flavor, OS, etc.
Bliss OS x86_64, python3.10 (Termux)
```bash
python3.10 -m nuitka --version
Nuitka:WARNING: Cannot detect Linux distribution, this may prevent optimization.
1.4rc10
Commercial: None
Python: 3.10.8 (main, Jan 16 2023, 15:47:20) [Clang 15.0.7 ]
Flavor: Unknown
Executable: /data/data/com.termux/files/usr/bin/python3.10
OS: Linux
Arch: x86_64
Distribution: Unknown None
Version C compiler: /data/data/com.termux/files/usr/bin/gcc (gcc).
Nuitka:WARNING: Cannot detect Linux distribution, this may prevent optimization.
```
* How did you install Nuitka and Python

Using modified termux build script to build python3.10
https://github.com/termux/termux-packages/blob/master/packages/python/build.sh

Alternatively installing python2.7 with `pkg install python2` produces same error.

* The specific PyPI names and version
```bash
python3.10 -m pip freeze
black==22.12.0
click==8.1.3
-e git+https://github.com/LinuxUserGD/gdscript-transpiler-bin@3670c405e56b86fe12fb80b88e46ef43df54895a#egg=gds
mypy-extensions==0.4.3
Nuitka @ git+https://github.com/Nuitka/Nuitka.git@3318a2e1f95b2193f404cce887602b759995e788
ordered-set==4.1.0
pathspec==0.10.3
platformdirs==2.6.2
six==1.16.0
tomli==2.0.1
x-python @ git+https://github.com/rocky/x-python.git@5e8a0b2a21075bb819b71e21fdbe9378b6ba1219
xdis @ git+https://github.com/rocky/python-xdis.git@1f71a88af57d2b9fe5ae9dc1eec70b4cfcd2593e
zstandard==0.19.0
```

Example:

`echo "print('output')" > output.py`
```bash
python3.10 -m nuitka --clang output.py
Nuitka-Options:INFO: Used command line options: --clang output.py
Nuitka:WARNING: Cannot detect Linux distribution, this may prevent optimization.
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure that is intended.
Nuitka:INFO: Starting Python compilation with Nuitka '1.4rc10' on Python '3.10' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: clang (clang).
Nuitka:WARNING: Cannot detect Linux distribution, this may prevent optimization.
Nuitka-Scons:INFO: Backend linking program with 7 files (no progress information available).
Nuitka-Scons:INFO: Compiled 49 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 6
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'local_storage_miss': 6
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'local_storage_read_miss': 12
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'local_storage_write': 12
Nuitka:INFO: Keeping build directory 'output.build'.
Nuitka:INFO: Successfully created 'output.bin'.
```
```bash
./output.bin
WARNING: linker: Warning: "/data/data/com.termux/files/home/output.bin" unused DT entry: DT_RPATH (type 0xf arg 0x13d8) (ignoring)
CANNOT LINK EXECUTABLE "./output.bin": library "libpython3.10.so.1.0" not found: needed by main executable
```
Workaround:
```bash
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libpython3.10.so.1.0 ./output.bin
WARNING: linker: Warning: "/data/data/com.termux/files/home/output.bin" unused DT entry: DT_RPATH (type 0xf arg 0x13d8) (ignoring)
output
```

**Comment by kayhayen** [comment]
Well, in standalone mode, it would copy the DLLs needed, but without it, of course not. On Linux, in accelerated mode, the RTPATH is used to allow finding the original Python DLL, but if Android doesn't support that (and I think LD_LIBRARY_PATH should be better to use), you can do that yes.

This is called "uninstalled" Python in Nuitka, and usually is affecting Windows and CPython or Anaconda only. But I can of course copy the Python DLL near the ".bin" for Android as well. Note however, that it still unlikely to work independently of an termux install.

**Comment by kayhayen** [comment]
Closing for lack of feedback.

**Comment by LinuxUserGD** [comment]
> Well, in standalone mode, it would copy the DLLs needed, but without it, of course not. On Linux, in accelerated mode, the RTPATH is used to allow finding the original Python DLL, but if Android doesn't support that (and I think LD_LIBRARY_PATH should be better to use), you can do that yes.
> 
> This is called "uninstalled" Python in Nuitka, and usually is affecting Windows and CPython or Anaconda only. But I can of course copy the Python DLL near the ".bin" for Android as well. Note however, that it still unlikely to work independently of an termux install.

In standalone mode, LD_PRELOAD would be a possible workaround too but breaks with `--onefile`.

It seems Android only supports `DT_RUNPATH` according to https://github.com/termux/termux-packages/issues/2071#issuecomment-364566718 which might be possible if Nuitka uses `patchelf --shrink-rpath`.

**Comment by kayhayen** [comment]
The onefile bootstrap could set environment variables, that should be easy to add. The `patchelf` usage seems fair game though, I will look into adding it.

**Comment by kayhayen** [comment]
I added the use for Android. I was able to see it being effective on my Linux, but it's limited to Android based Linux for now.

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by LinuxUserGD** [comment]
Thanks for the fix!
I can confirm that it works on both python2.7 and python3.10 with Termux on aarch64 Android after setting the environment variable with `export ANDROID_ARGUMENT=1` (for python2.7 the `sys.version` output is cut), and for python3.11 it works by default and the distribution/flavor is detected as `Android` automatically.

**Comment by kayhayen** [comment]
Can you explain what it means for `sys.version` to be cut? And what it with `ANDROID_ARGUMENT`, I think something lead to me believe, that was always set with Termux?

**Comment by LinuxUserGD** [comment]
> What is `sys.version` for 2.7 there and 3.10?
```bash
~ $ python2.7 -c "import sys; print(sys.version)"
2.7.18 (default, Apr  9 2022, 12:24:03)
[GCC Android (7714059, based on r416183c1) Clang 12.0.8 (https://android.google
~ $ python3.10 -c "import sys; print(sys.version)"
3.10.8 (main, Dec 31 2022, 15:00:22) [Clang 15.0.6 ]
~ $ python3.11 -c "import sys; print(sys.version)"
3.11.1 (main, Dec  7 2022, 05:56:18) [Clang 14.0.6 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0
```
python2.7 and python3.11 are official termux binaries, python3.10 is compiled from older termux repository commit.
> And what it with ANDROID_ARGUMENT, I think something lead to me believe, that was always set with Termux?

For termux 0.116 I get the following environment
```bash
~ $ python3.11 -c "from os import environ; print(environ)"
environ({'SHELL': '/data/data/com.termux/files/usr/bin/bash', 'COLORTERM': 'truecolor', 'HISTCONTROL': 'ignoreboth', 'PREFIX': '/data/data/com.termux/files/usr', 'JAVA_HOME': '/data/data/com.termux/files/usr/opt/openjdk', 'TERMUX_IS_DEBUGGABLE_BUILD': '0', 'TERMUX_MAIN_PACKAGE_FORMAT': 'debian', 'PWD': '/data/data/com.termux/files/home', 'TERMUX_VERSION': '0.118.0', 'EXTERNAL_STORAGE': '/sdcard', 'LD_PRELOAD': '/data/data/com.termux/files/usr/lib/libtermux-exec.so', 'HOME': '/data/data/com.termux/files/home', 'LANG': 'en_US.UTF-8', 'TERMUX_APK_RELEASE': 'F_DROID', 'DEX2OATBOOTCLASSPATH': '/apex/com.android.art/javalib/core-oj.jar:/apex/com.android.art/javalib/core-libart.jar:/apex/com.android.art/javalib/core-icu4j.jar:/apex/com.android.art/javalib/okhttp.jar:/apex/com.android.art/javalib/bouncycastle.jar:/apex/com.android.art/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/framework-atb-backward-compatibility.jar', 'TMPDIR': '/data/data/com.termux/files/usr/tmp', 'ANDROID_DATA': '/data', 'TERM': 'xterm-256color', 'ANDROID_I18N_ROOT': '/apex/com.android.i18n', 'SHLVL': '1', 'ANDROID_ROOT': '/system', 'BOOTCLASSPATH': '/apex/com.android.art/javalib/core-oj.jar:/apex/com.android.art/javalib/core-libart.jar:/apex/com.android.art/javalib/core-icu4j.jar:/apex/com.android.art/javalib/okhttp.jar:/apex/com.android.art/javalib/bouncycastle.jar:/apex/com.android.art/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/framework-atb-backward-compatibility.jar:/apex/com.android.conscrypt/javalib/conscrypt.jar:/apex/com.android.media/javalib/updatable-media.jar:/apex/com.android.mediaprovider/javalib/framework-mediaprovider.jar:/apex/com.android.os.statsd/javalib/framework-statsd.jar:/apex/com.android.permission/javalib/framework-permission.jar:/apex/com.android.sdkext/javalib/framework-sdkextensions.jar:/apex/com.android.wifi/javalib/framework-wifi.jar:/apex/com.android.tethering/javalib/framework-tethering.jar', 'ANDROID_TZDATA_ROOT': '/apex/com.android.tzdata', 'TERMUX_APP_PID': '9635', 'PATH': '/data/data/com.termux/files/usr/bin', 'ANDROID_ART_ROOT': '/apex/com.android.art', '_': '/data/data/com.termux/files/usr/bin/python3.11'})
~ $
```
so there is `ANDROID_ROOT` / `TERMUX_VERSION` set (also `uname -o` command returns "Android")

**Comment by kayhayen** [comment]
I now believe I must have seen ghosts and `ANDROID_ARGUMENT` is a typo or something. Not calling `uname -o` currently, preferring files, and then `lsb_release`, and in between that check for android based is done with variables, now with `return "ANDROID_ROOT" in os.environ or "android.googlesource.com" in sys.version` in the coming hotfix. I was not aware that only 3.11 had Google origin in its version output.

With that it's probably good. Let me just close it then, from 1.5.2 on, it will be working out of the box unchanged I guess. Nice to see 3.11 working on Android too. Would you be able to make some sort of PR that kind of gives people a howto, for installing termux and compiling with Python like current user manual has for Windows already?
