### ISSUE TITLE
Nuitka PluginBase support (or any another plugin system?)

### ISSUE THREAD

**Issue by katant** [Nuitka/Nuitka#201]
PluginBase (https://github.com/mitsuhiko/pluginbase) helps to make plugins without changing the code by simply downloading the plugin.
Without recompiling in Nuitka this will not work.

I have seen that Nuitka has a system of modules, but how to load them without recompiling the main program (if possible)?

**Comment by kayhayen** [comment]
Importing uncompiled python code is supposed to work just as it normally would from compiled code to uncompiled and from uncompiled to compiled code. They are on equal footing.

If you have a concrete issue, feel free to open it, but for now I will assume and treat this as the question if that is supposed to work. Yes it is.
