### ISSUE TITLE
OPENCV Error

### ISSUE THREAD

**Issue by iminsideyou** [Nuitka/Nuitka#2010]
ERROR:
```

FATAL: anti-bloat: Error, cannot evaluate code 'textwrap.indent(pkgutil.get_data('cv2', 'config.py').decode('utf8'), '    ') + textwrap.indent(pkgutil.get_data('cv2', 'config-3.py').decode('utf8'), '    ')' in 'import textwrap
import pkgutil
from nuitka.utils.Importing import getSharedLibrarySuffix' due to: [Errno 2] No such file or directory: 'C:\tools/miniconda3/envs/gpu/Lib/site-packages/cv2\python-3.8\config.py'
```

* Nuitka:INFO: Starting Python compilation with Nuitka '1.3.8' on Python '3.8' commercial grade 'not installed'. Windows 10
* python -m nuitka --follow-imports --enable-plugin=tk-inter --onefile C:\myopencvscript\opencvtestscript.py

  > 1.3.8
Commercial: None
Python: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\tools\miniconda3\envs\gpu\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\cl.exe (cl 14.3).

* PIP

  Did you use pip, anaconda, deb, rpm, from source, git clone, then install into
  a virtualenv or not, this is very important usually and one thing, the above
  command does not tell us (yet).

* The specific PyPI names and versions
opencv

I have already reinstalled my opencv build several times. Everything with opencv works but the compilation via nuittka. No version seems to work to compile as I have tried a bunch of different nuitka versions.

**Comment by kayhayen** [comment]
The error output seems rather strange, did you fail to copy it correctly, maybe?

**Comment by kayhayen** [comment]
Also it remains unclear to me what you mean when you say "your opencv build".

**Comment by iminsideyou** [comment]
What do you mean when you say Copy. I built opencv with cuda support (Visual Studio, Anaconda, CMake, Cuda)

**Comment by iminsideyou** [comment]
I know for a fact 'C:\tools/miniconda3/envs/gpu/Lib/site-packages/cv2\python-3.8\config.py' the config.py is actually in
C:\tools/miniconda3/envs/gpu/Lib/site-packages/cv2\config.py

not sure if that is really this issue not sure why that would be an issue

**Comment by kayhayen** [comment]
Nuitka is using `pkgutil.get_data` and it seems to resolve to funny paths for you, not sure why. However it also seems only the `config-3.py` does not exist. So far I think Anaconda and PyPI packages work, your self-built package may be different with the config Python files it expects. Can you try creating an empty one where it has this now?

**Comment by iminsideyou** [comment]
OK it is compiling. Will update you on if it worked or not

**Comment by iminsideyou** [comment]
bezier was in my python file for some reason. Removed and I am now at the backend c compiler portion

**Comment by iminsideyou** [comment]
[https://cdn.discordapp.com/attachments/1037954367984246815/1068182146042318878/cv2error.PNG](url)

**Comment by iminsideyou** [comment]
ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.

But I know this build is correct

**Comment by kayhayen** [comment]
It might fail to check the cv2 version though, it 4.7 needs changes, that I wouldn't know yet. Nuitka has version dependent handling of their import tricks, maybe it broke. The delvewheel stuff is strange, what kind of scipy is that, the one from Anaconda, or self built as well?

**Comment by kayhayen** [comment]
So, 4.7 from PyPI has just worked fine for me, no changes there.

**Comment by iminsideyou** [comment]
scipy is from Anaconda.
opencv version is 4.5.1 - any other version is not supported for my gpu env build
oddly enough PyInstaller --onefile works and I can run the executable it creates with no issues.

**Comment by kayhayen** [comment]
This is in Nuitka though:

```
  options:
    checks:
      - description: 'OpenCV2 is best supported with 4.6 or later'
        support_info: 'warning'
        when: 'version("opencv-python") < (4,6)'
```

But I don't think it affects that initial load, that should work with 4.5, but your error seemed to have an issue with this:

```
        # Before OpenCV 4.6
        'native_module = importlib.import_module("cv2.cv2")': '"import imp; native_module = imp.load_dynamic(\"cv2\", os.path.join(os.path.dirname(__file__), \"cv2%s\"))" % getSharedLibrarySuffix(False)'
```

That replacement is using `getSharedLibrarySuffix` which you had in your error output, however it ought to work, but maybe it got broken at some point, the whole thing is here:

```
  anti-bloat:
    - description: 'workaround for colliding native module import'
      context:
        - 'import textwrap'
        - 'import pkgutil'
        - 'from nuitka.utils.Importing import getSharedLibrarySuffix'
      replacements_plain:
        ? "load_first_config([\n"
        : 'if False: (['
      replacements:
        "load_first_config(['config.py'], True)": "textwrap.indent(pkgutil.get_data('cv2', 'config.py').decode('utf8'), '    ') + textwrap.indent(pkgutil.get_data('cv2', 'config-3.py').decode('utf8'), '    ')"
        # Before OpenCV 4.6
        'native_module = importlib.import_module("cv2.cv2")': '"import imp; native_module = imp.load_dynamic(\"cv2\", os.path.join(os.path.dirname(__file__), \"cv2%s\"))" % getSharedLibrarySuffix(False)'
        # After OpenCV 4.6
        'native_module = importlib.import_module("cv2")': '"import imp; native_module = imp.load_dynamic(\"cv2\", os.path.join(os.path.dirname(__file__), \"cv2%s\"))" % getSharedLibrarySuffix(False)'
      when: 'standalone'
```

**Comment by kayhayen** [comment]
The scipy from Anaconda works fine for me, I have no idea what would be going one there. Can you look at `nuitka\plugins\standard\DelvewheelPlugin.py` for the code that leads up to there, what it is effectively evaluating, and how that cannot call the function to register the DLL.

**Comment by iminsideyou** [comment]
Hmmm. So I looked up the initial error and saw a Chinese post about the issue. They went into \cv2 and copy pasted and renamed into the cv2\python-3.8\ folder. I needed to do that for config.py and config-3.py and it then compiled. Unfortunately I then run into this error when trying to run the .exe.

error:

import pyautogui
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Stream\AppData\Local\Temp\ONEFIL~1\pyautogui__init.py", line 183, in <module pyautogui>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Stream\AppData\Local\Temp\ONEFIL~1\pyscreeze__init.py", line 45, in <module pyscreeze>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Stream\AppData\Local\Temp\ONEFIL~1\cv2__init.py", line 113, in <module cv2>
  File "C:\Users\Stream\AppData\Local\Temp\ONEFIL~1\cv2__init.py", line 37, in bootstrap
UnboundLocalError: local variable 'os' referenced before assignment

**Comment by kayhayen** [comment]
Lets not do too many manipulations, rather help me reproduce the issue. Messing with the cv2 installation is not what we should do, rather we should understand where the things we see are coming from. I am not too interested in making one user have a procedure that works, but rather to generally work. I hope you understand.

So I am assuming that when building manually, you get a folder structure, that contains even more tricks. The `pkgutil.get_data` seems capable of dealing with it. And also the `config-3.py` may not exist. I will have to check out what is there in PyPI forms of cv2. Can you provide the `__init__.py` of your cv2 installation. I think I need to see if your bootstrap code is changed from PyPI package.

Does it not have this:

````
    load_first_config(['config.py'], True)
    load_first_config([
        'config-{}.{}.py'.format(sys.version_info[0], sys.version_info[1]),
        'config-{}.py'.format(sys.version_info[0])
    ], True)
```

And maybe this means you do not have a `python-3.py` but maybe you have a `python-3.8.py` instead. I think it means that one of the files is expected, `True` there means required. On PyPI, the wheel is for all Python versions, on your build, it's probably specific to the 3.8, therefore we would solve the first issue.

Just as a side note. Solving the first issue is the path to success. Working around it without understanding it, is the path to wasted time and dubious results. 

From this, I think I can conclude how to improve the Nuitka configuration for cv2 there. However, I would also love to see your `python-3.8.py` then, and what it does. Maybe it's responsible for the version specific folder, and this might require an import hack for Nuitka to be configured.

**Comment by kayhayen** [comment]
I really need your input here.

**Comment by kayhayen** [comment]
Closing for lack of feedback and deleting too, to avoid people stumbling over non-helpful issue.
