### ISSUE TITLE
Possibility of partly compiling a project.

### ISSUE THREAD

**Issue by thesct22** [Nuitka/Nuitka#2019]
Are there any existing ways/ future plans to implement a way to partly obfuscate a project.

If there are modules that are open-source you could possibly keep them as such and then compile and create executable only for the the modules and files you wish to be hidden from the user. Is this possible as of now, or is it possible to implement this on nuitka. It can potentially save a lot of compilation time and helps developers who is using nuitka for the sole purpose of masking the source code and is not bothered about keeping the open-sourced modules as such.

**Comment by kayhayen** [comment]
Including things as bytecode is already possible today. The anti-bloat plugin allows `--noinclude-custom-module=module_name:bytecode` in which case it is included as bytecode. Not sure how well it works with namespaces, this has not been a priority.
