### ISSUE TITLE
Build complains about existing source files when built in docker repeatedly

### ISSUE THREAD

**Issue by ilya-brykau** [Nuitka/Nuitka#2024]
Platform: Windows Server 2016 amd64 Docker

Assertion error occurred during Nuitka:INFO: Generating source code for C backend compiler.
Nuitka '1.4' on Python '3.9' commercial grade 'not installed'.

Command-line parameters:
`Nuitka-Options:INFO: Used command line options: --standalone --remove-output --nofollow-import-to=azure.mgmt.compute.aio --nofollow-import-to=azure.mgmt.compute.v2015_06_15 --nofollow-import-to=azure.mgmt.compute.v2016_03_30 --nofollow-import-to=azure.mgmt.compute.v2016_04_30_preview --nofollow-import-to=azure.mgmt.compute.v2017_03_30 --nofollow-import-to=azure.mgmt.compute.v2017_09_01 --nofollow-import-to=azure.mgmt.compute.v2017_12_01 --nofollow-import-to=azure.mgmt.compute.v2018_04_01 --nofollow-import-to=azure.mgmt.compute.v2018_06_01 --nofollow-import-to=azure.mgmt.compute.v2018_09_30 --nofollow-import-to=azure.mgmt.compute.v2018_10_01 --nofollow-import-to=azure.mgmt.compute.v2019_03_01 --nofollow-import-to=azure.mgmt.compute.v2019_04_01 --nofollow-import-to=azure.mgmt.compute.v2019_07_01 --nofollow-import-to=azure.mgmt.compute.v2019_11_01 --nofollow-import-to=azure.mgmt.compute.v2019_12_01 --nofollow-import-to=azure.mgmt.compute.v2020_05_01 --nofollow-import-to=azure.mgmt.compute.v2020_06_01 --nofollow-import-to=azure.mgmt.compute.v2020_06_30 --nofollow-import-to=azure.mgmt.compute.v2020_09_30 --nofollow-import-to=azure.mgmt.compute.v2020_10_01_preview --nofollow-import-to=azure.mgmt.compute.v2020_12_01 --nofollow-import-to=azure.mgmt.compute.v2021_03_01 --nofollow-import-to=azure.mgmt.compute.v2021_04_01 --nofollow-import-to=azure.mgmt.compute.v2021_08_01 --nofollow-import-to=azure.mgmt.compute.v2021_10_01 --nofollow-import-to=azure.mgmt.compute.v2021_11_01 --nofollow-import-to=azure.mgmt.compute.v2021_12_01 --nofollow-import-to=azure.mgmt.compute.v2022_01_03 --nofollow-import-to=azure.mgmt.compute.v2022_03_01 --nofollow-import-to=azure.mgmt.compute.v2022_03_02 --nofollow-import-to=azure.mgmt.compute.v2022_04_04 --nofollow-import-to=azure.mgmt.compute.v2022_08_01 --nofollow-import-to=azure.mgmt.network.aio --nofollow-import-to=azure.mgmt.network.v2015_06_15 --nofollow-import-to=azure.mgmt.network.v2016_09_01 --nofollow-import-to=azure.mgmt.network.v2016_12_01 --nofollow-import-to=azure.mgmt.network.v2017_03_01 --nofollow-import-to=azure.mgmt.network.v2017_06_01 --nofollow-import-to=azure.mgmt.network.v2017_10_01 --nofollow-import-to=azure.mgmt.network.v2018_01_01 --nofollow-import-to=azure.mgmt.network.v2018_02_01 --nofollow-import-to=azure.mgmt.network.v2018_04_01 --nofollow-import-to=azure.mgmt.network.v2018_06_01 --nofollow-import-to=azure.mgmt.network.v2018_07_01 --nofollow-import-to=azure.mgmt.network.v2018_08_01 --nofollow-import-to=azure.mgmt.network.v2018_10_01 --nofollow-import-to=azure.mgmt.network.v2018_11_01 --nofollow-import-to=azure.mgmt.network.v2018_12_01 --nofollow-import-to=azure.mgmt.network.v2019_04_01 --nofollow-import-to=azure.mgmt.network.v2019_06_01 --nofollow-import-to=azure.mgmt.network.v2019_08_01 --nofollow-import-to=azure.mgmt.network.v2019_09_01 --nofollow-import-to=azure.mgmt.network.v2019_11_01 --nofollow-import-to=azure.mgmt.network.v2019_12_01 --nofollow-import-to=azure.mgmt.network.v2020_03_01 --nofollow-import-to=azure.mgmt.network.v2020_05_01 --nofollow-import-to=azure.mgmt.network.v2020_06_01 --nofollow-import-to=azure.mgmt.network.v2020_07_01 --nofollow-import-to=azure.mgmt.network.v2020_08_01 --nofollow-import-to=azure.mgmt.network.v2020_11_01 --nofollow-import-to=azure.mgmt.network.v2021_02_01 --nofollow-import-to=azure.mgmt.storage.aio --nofollow-import-to=azure.mgmt.storage.v2015_06_15 --nofollow-import-to=azure.mgmt.storage.v2016_01_01 --nofollow-import-to=azure.mgmt.storage.v2016_12_01 --nofollow-import-to=azure.mgmt.storage.v2017_06_01 --nofollow-import-to=azure.mgmt.storage.v2017_10_01 --nofollow-import-to=azure.mgmt.storage.v2018_03_01_preview --nofollow-import-to=azure.mgmt.storage.v2018_07_01 --nofollow-import-to=azure.mgmt.storage.v2018_11_01 --nofollow-import-to=azure.mgmt.storage.v2019_04_01 --nofollow-import-to=azure.mgmt.storage.v2019_06_01 --nofollow-import-to=azure.mgmt.storage.v2020_08_01_preview --nofollow-import-to=azure.mgmt.storage.v2021_01_01 --nofollow-import-to=azure.mgmt.storage.v2021_02_01 --nofollow-import-to=azure.mgmt.storage.v2021_04_01 --nofollow-import-to=azure.mgmt.storage.v2021_06_01 --nofollow-import-to=azure.mgmt.storage.v2021_08_01 --nofollow-import-to=azure.mgmt.storage.v2021_09_01 --nofollow-import-to=azure.mgmt.storage.v2022_05_01 --nofollow-import-to=azure.mgmt.resource.changes.aio --nofollow-import-to=azure.mgmt.resource.deploymentscripts.aio --nofollow-import-to=azure.mgmt.resource.deploymentscripts.v2019_10_01_preview --nofollow-import-to=azure.mgmt.resource.features.aio --nofollow-import-to=azure.mgmt.resource.features.v2015_12_01 --nofollow-import-to=azure.mgmt.resource.links.aio --nofollow-import-to=azure.mgmt.resource.locks.aio --nofollow-import-to=azure.mgmt.resource.locks.v2015_01_01 --nofollow-import-to=azure.mgmt.resource.managedapplications.aio --nofollow-import-to=azure.mgmt.resource.privatelinks.aio --nofollow-import-to=azure.mgmt.resource.resources.aio --nofollow-import-to=azure.mgmt.resource.resources.v2016_02_01 --nofollow-import-to=azure.mgmt.resource.resources.v2016_09_01 --nofollow-import-to=azure.mgmt.resource.resources.v2017_05_10 --nofollow-import-to=azure.mgmt.resource.resources.v2018_02_01 --nofollow-import-to=azure.mgmt.resource.resources.v2018_05_01 --nofollow-import-to=azure.mgmt.resource.resources.v2019_03_01 --nofollow-import-to=azure.mgmt.resource.resources.v2019_05_01 --nofollow-import-to=azure.mgmt.resource.resources.v2019_05_10 --nofollow-import-to=azure.mgmt.resource.resources.v2019_07_01 --nofollow-import-to=azure.mgmt.resource.resources.v2019_08_01 --nofollow-import-to=azure.mgmt.resource.resources.v2019_10_01 --nofollow-import-to=azure.mgmt.resource.resources.v2020_06_01 --nofollow-import-to=azure.mgmt.resource.resources.v2020_10_01 --nofollow-import-to=azure.mgmt.resource.resources.v2021_01_01 --nofollow-import-to=azure.mgmt.resource.resources.v2021_04_01 --nofollow-import-to=azure.mgmt.resource.subscriptions.aio --nofollow-import-to=azure.mgmt.resource.subscriptions.v2016_06_01 --nofollow-import-to=azure.mgmt.resource.subscriptions.v2018_06_01 --nofollow-import-to=azure.mgmt.resource.subscriptions.v2019_06_01 --nofollow-import-to=azure.mgmt.resource.templatespecs.aio --nofollow-import-to=azure.mgmt.resource.templatespecs.v2019_06_01_preview --nofollow-import-to=azure.mgmt.resource.templatespecs.v2021_03_01_preview --nofollow-import-to=azure.mgmt.resource.templatespecs.v2021_05_01 --nofollow-import-to=azure.mgmt.resource.policy.aio --nofollow-import-to=azure.mgmt.resource.policy.v2015_10_01_preview --nofollow-import-to=azure.mgmt.resource.policy.v2016_04_01 --nofollow-import-to=azure.mgmt.resource.policy.v2016_12_01 --nofollow-import-to=azure.mgmt.resource.policy.v2017_06_01_preview --nofollow-import-to=azure.mgmt.resource.policy.v2018_03_01 --nofollow-import-to=azure.mgmt.resource.policy.v2018_05_01 --nofollow-import-to=azure.mgmt.resource.policy.v2019_01_01 --nofollow-import-to=azure.mgmt.resource.policy.v2019_06_01 --nofollow-import-to=azure.mgmt.resource.policy.v2019_09_01 --nofollow-import-to=azure.mgmt.resource.policy.v2020_09_01 --include-package=log --enable-plugin=anti-bloat --noinclude-pytest-mode=nofollow --lto=no --msvc=latest --assume-yes-for-downloads --output-dir=c:\data\.temp\compile c:\data\src\unified_entry.py`

requirements used:
`atomicwrites==1.4.0 ; python_version >= "3.9" and python_version < "4.0" and sys_platform == "win32"
attrs==21.2.0 ; python_version >= "3.9" and python_version < "4.0"
azure-common==1.1.28 ; python_version >= "3.9" and python_version < "4.0"
azure-core==1.26.2 ; python_version >= "3.9" and python_version < "4.0"
azure-identity==1.12.0 ; python_version >= "3.9" and python_version < "4.0"
azure-mgmt-compute==29.1.0 ; python_version >= "3.9" and python_version < "4.0"
azure-mgmt-core==1.3.2 ; python_version >= "3.9" and python_version < "4.0"
azure-mgmt-network==22.2.0 ; python_version >= "3.9" and python_version < "4.0"
azure-mgmt-resource==22.0.0 ; python_version >= "3.9" and python_version < "4.0"
azure-mgmt-storage==21.0.0 ; python_version >= "3.9" and python_version < "4.0"
black==22.12.0 ; python_version >= "3.9" and python_version < "4.0"
bottle==0.12.19 ; python_version >= "3.9" and python_version < "4.0"
certifi==2021.10.8 ; python_version >= "3.9" and python_version < "4.0"
cffi==1.15.0 ; python_version >= "3.9" and python_version < "4.0"
charset-normalizer==2.0.8 ; python_version >= "3.9" and python_version < "4.0"
click==8.1.3 ; python_version >= "3.9" and python_version < "4.0"
colorama==0.4.6 ; python_version >= "3.9" and python_version < "4.0"
conan==1.54.0 ; python_version >= "3.9" and python_version < "4.0"
coverage[toml]==6.5.0 ; python_version >= "3.9" and python_version < "4.0"
cryptography==36.0.1 ; python_version >= "3.9" and python_version < "4.0"
dataclasses-json==0.5.6 ; python_version >= "3.9" and python_version < "4.0"
distro==1.6.0 ; python_version >= "3.9" and python_version < "4.0" and sys_platform == "linux" or python_version >= "3.9" and python_version < "4.0" and sys_platform == "linux2"
fasteners==0.16.3 ; python_version >= "3.9" and python_version < "4.0"
idna==3.3 ; python_version >= "3.9" and python_version < "4.0"
inflection==0.5.1 ; python_version >= "3.9" and python_version < "4.0"
iniconfig==1.1.1 ; python_version >= "3.9" and python_version < "4.0"
isodate==0.6.1 ; python_version >= "3.9" and python_version < "4.0"
jinja2==3.0.3 ; python_version >= "3.9" and python_version < "4.0"
markupsafe==2.0.1 ; python_version >= "3.9" and python_version < "4.0"
marshmallow-enum==1.5.1 ; python_version >= "3.9" and python_version < "4.0"
marshmallow==3.14.1 ; python_version >= "3.9" and python_version < "4.0"
msal-extensions==1.0.0 ; python_version >= "3.9" and python_version < "4.0"
msal==1.18.0 ; python_version >= "3.9" and python_version < "4.0"
msrest==0.7.1 ; python_version >= "3.9" and python_version < "4.0"
mypy-extensions==0.4.3 ; python_version >= "3.9" and python_version < "4.0"
mypy==0.991 ; python_version >= "3.9" and python_version < "4.0"
node-semver==0.6.1 ; python_version >= "3.9" and python_version < "4.0"
nuitka==1.4 ; python_version >= "3.9" and python_version < "4.0" and sys_platform == "win32" or python_version >= "3.9" and python_version < "4.0" and sys_platform == "darwin"
oauthlib==3.2.2 ; python_version >= "3.9" and python_version < "4.0"
orderedset==2.0.3 ; python_version >= "3.9" and python_version < "4.0" and sys_platform == "win32" or python_version >= "3.9" and python_version < "4.0" and sys_platform == "darwin"
packaging==21.3 ; python_version >= "3.9" and python_version < "4.0"
parameterized==0.8.1 ; python_version >= "3.9" and python_version < "4.0"
patch-ng==1.17.4 ; python_version >= "3.9" and python_version < "4.0"
pathspec==0.10.3 ; python_version >= "3.9" and python_version < "4.0"
platformdirs==2.4.0 ; python_version >= "3.9" and python_version < "4.0"
pluggy==1.0.0 ; python_version >= "3.9" and python_version < "4.0"
pluginbase==1.0.1 ; python_version >= "3.9" and python_version < "4.0"
portalocker==2.5.1 ; python_version >= "3.9" and python_version < "4.0"
psutil==5.9.4 ; python_version >= "3.9" and python_version < "4.0"
py-zabbix==1.1.7 ; python_version >= "3.9" and python_version < "4.0"
py==1.11.0 ; python_version >= "3.9" and python_version < "4.0"
pycparser==2.21 ; python_version >= "3.9" and python_version < "4.0"
pygments==2.10.0 ; python_version >= "3.9" and python_version < "4.0"
pyjwt==2.6.0 ; python_version >= "3.9" and python_version < "4.0"
pyjwt[crypto]==2.6.0 ; python_version >= "3.9" and python_version < "4.0"
pyopenssl==21.0.0 ; python_version >= "3.9" and python_version < "4.0"
pyparsing==3.0.6 ; python_version >= "3.9" and python_version < "4.0"
pytest-cov==3.0.0 ; python_version >= "3.9" and python_version < "4.0"
pytest-random-order==1.0.4 ; python_version >= "3.9" and python_version < "4.0"
pytest==6.2.5 ; python_version >= "3.9" and python_version < "4.0"
python-dateutil==2.8.2 ; python_version >= "3.9" and python_version < "4.0"
python-json-logger==2.0.2 ; python_version >= "3.9" and python_version < "4.0"
pywin32==302 ; python_version >= "3.9" and python_version < "4.0" and sys_platform == "win32" or python_version >= "3.9" and platform_system == "Windows" and python_version < "4.0"
pyyaml==5.4.1 ; python_version >= "3.9" and python_version < "4.0"
requests-oauthlib==1.3.1 ; python_version >= "3.9" and python_version < "4.0"
requests==2.26.0 ; python_version >= "3.9" and python_version < "4.0"
responses==0.16.0 ; python_version >= "3.9" and python_version < "4.0"
ruff==0.0.237 ; python_version >= "3.9" and python_version < "4.0"
six==1.16.0 ; python_version >= "3.9" and python_version < "4.0"
teamcity-messages==1.32 ; python_version >= "3.9" and python_version < "4.0"
toml==0.10.2 ; python_version >= "3.9" and python_version < "4.0"
tomli==1.2.2 ; python_version >= "3.9" and python_full_version < "3.11.0a7"
tqdm==4.62.3 ; python_version >= "3.9" and python_version < "4.0"
types-cryptography==3.3.14 ; python_version >= "3.9" and python_version < "4.0"
types-enum34==1.1.3 ; python_version >= "3.9" and python_version < "4.0"
types-ipaddress==1.0.3 ; python_version >= "3.9" and python_version < "4.0"
types-pyopenssl==21.0.3 ; python_version >= "3.9" and python_version < "4.0"
types-requests==2.26.1 ; python_version >= "3.9" and python_version < "4.0"
typing-extensions==4.0.1 ; python_version >= "3.9" and python_version < "4.0"
typing-inspect==0.7.1 ; python_version >= "3.9" and python_version < "4.0"
urllib3==1.26.7 ; python_version >= "3.9" and python_version < "4"
wmi==1.5.1 ; python_version >= "3.9" and python_version < "4.0" and sys_platform == "win32"
`
Traceback:
`Traceback (most recent call last):
    File "C:\data\.venv_docker_windows\lib\site-packages\nuitka\__main__.py", line 151, in <module>
      main()
    File "C:\data\.venv_docker_windows\lib\site-packages\nuitka\__main__.py", line 137, in main
      MainControl.main()
    File "C:\data\.venv_docker_windows\lib\site-packages\nuitka\MainControl.py", line 951, in main
      result, options = compileTree()
    File "C:\data\.venv_docker_windows\lib\site-packages\nuitka\MainControl.py", line 830, in compileTree
      makeSourceDirectory()
    File "C:\data\.venv_docker_windows\lib\site-packages\nuitka\MainControl.py", line 461, in makeSourceDirectory
      writeSourceCode(
    File "C:\data\.venv_docker_windows\lib\site-packages\nuitka\tree\SourceHandling.py", line 280, in writeSourceCode
      assert not os.path.isfile(filename), filename
  AssertionError: c:\data\.temp\compile\unified_entry.build\__helpers.h`

**Comment by kayhayen** [comment]
Probably a failure to delete a mounted directory of a duplicate usage of the same folder, something like that. I don't think there is anything to do about this from Nuitka side, is there?

**Comment by ilya-brykau** [comment]
The build is running on CI every day and that's the first time I see this after an update. Docker is always clean and no folders compilation folders present there before build

**Comment by kayhayen** [comment]
What of these folders are mounted and visible on the outside though?

**Comment by ilya-brykau** [comment]
Everything including the sourcecode. The actual flow is the following:
1. Build is triggered
2. New EC2 instance with Windows onboard is created
3. Folder with sourcecode is downloaded
4. Docker instance is created with the whole folder mapped
5. Nuitka is running inside docker

**Comment by kayhayen** [comment]
I have had issues with podman before, and I recall seeing at least another instance, or where file accesses went wrong on these mounted folders. The can be locks, etc. that keep files alive, has happened before. In the Linux/Unix world, NFS was also famous for it.

Put the build folder to the inside of it. I do not think for Nuitka there is a good way to detect the situation of a network backed folder being used. I do not think these shortcomings of OS/Docker can be worked around by Nuitka at all. If you have any idea how, please share it.

**Comment by ilya-brykau** [comment]
We might retry in this case. Increased build time is better then failed build

**Comment by kayhayen** [comment]
I am not sure I get what you are referring to there with increased build time.

**Comment by ilya-brykau** [comment]
Im talking about added retries in case we failed to write something to the filesystem. Retries number, sleep time etc is This is something worth thinking about. Adding retries might add some overhead to the build but it will more likely prevent falling in case of inability to write to disk. What you use right now is an optimistic locking but it is actually possible to wait for the lock release.

**Comment by kayhayen** [comment]
It is not a locking, Nuitka expects that for a given build folder, nothing else is creating files there. You probably have overlapping builds or something like that.

**Comment by ilya-brykau** [comment]
One build agent is dedicated to one build and is killed afterwards. Only one build is running on it. So its not overlapping. Bur we can close the issue if you think its not important

**Comment by kayhayen** [comment]
I did not find any actionable information, yes
