### ISSUE TITLE
Rename data-files directory while including it

### ISSUE THREAD

**Issue by nick-0** [Nuitka/Nuitka#2027]
Are there any utilities to change the name of a standalone directory?
I am currently using the config.yaml method:

`  data-files:
     dirs:
        - 'pluginfo'
    dest_path: '.'
`

This does put the directory into my dist, but I need to rename the directory from 'pluginfo' to 'usd'.
Are there any utilities for this?
Thanks,
Nick

**Comment by kayhayen** [comment]
This is only doable via the command line at this time. The form that works with file names can do it. 

The expectation is that package data does not change names inside the distribution, we never needed that therefore with any package so far.
