### ISSUE TITLE
When compiling with Nuitka I need to add it in Azure folder.

### ISSUE THREAD

**Issue by ZaferKilic** [Nuitka/Nuitka#2028]
Hi, I need to add the Azure folder when compiling with Nuitka. At first, when my application opened, I made it add itself, but I could not get a result. What should I do?

The Nuitka Command I'm Using -->  python -m nuitka --mingw64 --windows-icon-from-ico=C:\Users\tcool\OneDrive\Masaüstü\AliceInc\Medya\1-DİJİTAL\ALİCE.ico --onefile --windows-company-name=AliceInc --windows-product-version=1.0 --plugin-enable=tk-inter Alice.py

![Ekran_goruntusu_2023-01-30_000842](https://user-images.githubusercontent.com/87082513/215557375-6881c33c-f416-44e6-bb4b-000a748fc2c2.png)

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.
