### ISSUE TITLE
dll copy of onnxruntime (gpu)

### ISSUE THREAD

**Issue by csvt32745** [Nuitka/Nuitka#2029]
Nuitka environment
 ```
1.5rc2
Commercial: None
Python: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\AlanHuang\AppData\Local\Programs\Python\Python38\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual 
Studio\2022\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe (cl 14.3).
```
Package
```
onnxruntime-gpu==1.13.1 
numpy==1.23.5
```
Minimal reproduce: `t.py`.
`model.onnx` is any onnx model file (example: [https://github.com/microsoft/onnxruntime/blob/main/samples/python/training/orttrainer/mnist/mnist_original.onnx](https://github.com/microsoft/onnxruntime/blob/main/samples/python/training/orttrainer/mnist/mnist_original.onnx)).
```python
import numpy as np
import onnxruntime as ort

if __name__ == "__main__":
    print(ort.get_device())
    model = ort.InferenceSession(r'..\model.onnx', providers=['CUDAExecutionProvider'])
```

Nuitka command (Successfully compiled)
```
nuitka --standalone --show-progress t.py
```

Runtime Error: Seems like dlls in `onnxruntime\capi` are missed.
```
2023-01-31 14:52:46.3477728 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1641 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.
GPU
2023-01-31 14:52:46.4810044 [E:onnxruntime:Default, provider_bridge_ort.cc:1266 onnxruntime::TryGetProviderInfo_CUDA] 
D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1018 onnxruntime::ProviderSharedLibrary::Ensure 
[ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load 
"D:\SGD\film_onnx\nuitka_test\t.dist\onnxruntime\capi\onnxruntime_providers_shared.dll"

Traceback (most recent call last):
  File "D:\SGD\film_onnx\nuitka_test\t.dist\t.py", line 6, in <module>
  File "D:\SGD\film_onnx\nuitka_test\t.dist\onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "D:\SGD\film_onnx\nuitka_test\t.dist\onnxruntime\capi\onnxruntime_inference_collection.py", line 395, in _create_inference_session
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:574 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. 
Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page 
(https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements), 
make sure they're in the PATH, and that your GPU is supported.
```

After manually copying `...\Python38\Lib\site-packages\onnxruntime\capi\*.dll` into `t.dist\onnxruntime\capi`,
the error messege disappeared and the exectuable (full program) works on another machine.

**Comment by kayhayen** [comment]
If you are available to do a PR, this can be fixed by adding to the yaml configuration, described here: [https://nuitka.net/doc/nuitka-package-config.html](https://nuitka.net/doc/nuitka-package-config.html)

And here is more of a walk through style post: [https://nuitka.net/posts/nuitka-package-config-kickoff.html](https://nuitka.net/posts/nuitka-package-config-kickoff.html)

Here is a similar PR for another package: [#1993](https://github.com/Nuitka/Nuitka/pull/1993)

**Comment by kayhayen** [comment]
So this got released as part of 1.4.1 already, but using 1.4.3 is recommended.

**Comment by fashni** [comment]
i don't know why but the latest version (1.7.9) does not include the all the dlls, only onnxruntime_providers_shared.dll

**Comment by fashni** [comment]
it seems like this commit 7968b7895a074b2bfa5ccd21fdc5f40e4fd0205c was undoing some of the intended purpose of #2030, which is to include all dlls, not only the dll for CPU.

**Comment by kayhayen** [comment]
@fashni you are right, that looks wrong, and has escaped my attention, I will correct that with a new hotfix.
