### ISSUE TITLE
Total output size for standalone w/ and w/o onefile

### ISSUE THREAD

**Issue by RyanHope** [Nuitka/Nuitka#2031]
I am building a project that uses pyside6, numpy and scipy. The resulting build contains 3 copies of libopenblas and the total output folder size is almost 200mb. In onefile mode, the binary is 35mb.  Why is there such a difference between these two options?

**Comment by kayhayen** [comment]
The onefile uses compression. Identical files are naturally a perfect fit for it. Can you provide a minimal reproducer that exercises all 3 users of the blas library, so I can try and deduplicate it.

**Comment by RyanHope** [comment]
Ok so 7z compression of the non-one-file build does bring the final size down to about the one-file build size. I was using rar before and it was still ~2x bigger so thought the onefile was doing some special voodoo. I went to make the minimal example and noticed that neither my minimal or main project is producing 3 blas libs now, only 2. IDK what I changed. I will revisit this later possibly.

**Comment by kayhayen** [comment]
Having 2 is still one too much possibly.

**Comment by RyanHope** [comment]
Well here is my current minimal example...

```
import numpy as np
import scipy.ndimage


def main():
    x = np.random.random_sample(10000).reshape(100, 100)
    y = scipy.ndimage.gaussian_filter(x, 0.99)
    print(y)


if __name__ == "__main__":
    main()
```

**Comment by kayhayen** [comment]
It probably has more to do with your environment, make a separate and new report, then I will have all the information.
