### ISSUE TITLE
Windows: Output filename without exe suffix gives "scons failed to create the expected file"

### ISSUE THREAD

**Issue by WhosMyName** [Nuitka/Nuitka#2034]
I'm using the latest version of the action and scons can't create the binary file after compiliation.
The platform is Windows.  
Nuitka 1.3.8
Here's the run of the [CI/CD Pipeline](https://github.com/WhosMyName/RealBandcampMusicDiscovery/actions/runs/4053185236/jobs/6973502459#step:5:253).

Am I doing something wrong/incorrectly?
How can I help SCons create the file?
Should I check back with the people from SCons?

Thanks in advance ❤️

**Comment by WhosMyName** [comment]
Okay that a good to know info.
I checked through the repo and I think that's already handled [correct me if I'm wrong].
From [OutputDirectories.py](https://github.com/Nuitka/Nuitka/blob/1.3.8/nuitka/OutputDirectories.py#L128)
```python
        elif isWin32OrPosixWindows():
            result += ".exe"
```

**Comment by kayhayen** [comment]
Check one branch higher, that is the one your configuration triggers. I will have something for that soon.

**Comment by kayhayen** [comment]
I am getting this, so it's actually disallowed by Nuitka:

> FATAL: Error, may only specify output filename for acceleration and onefile mode,
> but not for module mode where filenames are mandatory, and not for
> standalone where there is a sane default used inside the dist folder.

That was changed for 1.4 I think, but arguably that is a bit close minded, esp. as a recently discovered that the default picked on Linux/macOS can collide with package directory names, and was changed to containing a `.bin` suffix.

**Comment by kayhayen** [comment]
Not my favorite bit of the code, lets see if that will be doable for a hotfix.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by WhosMyName** [comment]
@kayhayen thanks for the quick fix ❤️ 
I updated my fork of the action with
`pip install -U "https://github.com/Nuitka/Nuitka/archive/factory.zip" -r "$github_action_path\requirements.txt"`
and ran it through the pipeline.
> It just works!  

It's wonderful, most gracious thanks.

**Comment by kayhayen** [comment]
I am going to add support for branch names later this week likely, then that kind of action should no longer be necessary, and you would be on the 1.4.2 that I published in the mean time maybe.

**Comment by kayhayen** [comment]
Will be part of the 1.4.3 hotfix when it comes.

**Comment by kayhayen** [comment]
This was release as part of the 1.4.3 hotfix I just made.
