### ISSUE TITLE
Wrong result provided by compiled code with tensorflow session run under some situation

### ISSUE THREAD

**Issue by wrchen-voxel** [Nuitka/Nuitka#2037]
I compiled some python code(see attachment) which contains tensorflow tf.py_func and numpy  using nuitka, 
found that when using **nuitka>=0.6.19**(including nuitka==1.x), 
this code result is different with the one run using original python code, 
but nuitka==0.6.18.x (maybe **nuika<=0.6.18.6**) compiled one could return the correct result.

I suspect that maybe tensorflow `session.run` with graph contains `tf.py_func` with `numpy` might trigger this under some situation,
 but I'm not sure which part of the code triggered this difference,  
and this might related with the  nuitka changes 
(https://github.com/Nuitka/Nuitka/compare/0.6.18.6...0.6.19)

  > python -m nuitka --version
 ```
    0.6.19
    Commercial: None
    Python: 3.6.9 (default, Nov 25 2022, 14:10:45) 
    Flavor: Debian Python
    Executable: /usr/local/vcw/thorax/venv/bin/python
    OS: Linux
    Arch: x86_64
    Distribution: Ubuntu 18.0
```
  > nuitka compile command:

```python -m nuitka --show-progress --nofollow-imports --remove-output -o single_check single_check.py```

  > Package Version:
```
tensorflow-gpu       1.14.0
numpy                1.19.5
```

Here is the compressed code file:
[nuitka_test.tar.gz](https://github.com/Nuitka/Nuitka/files/10566143/nuitka_test.tar.gz)

**Comment by kayhayen** [comment]
I am not sure what you expect from `--nofollow-imports`, so this is using the uncompiled tensorflow, which then fails to work, as does the standard 2.8 tensorflow. The old tensorflow 1 is not currently supported. I am sure there is an issue somewhere that expresses already that I would want to have substantial funding in order to make tensorflow 1 work.
