### ISSUE TITLE
Standalone fails to handle apsw, needs to support `package_name/__init__.so` for output

### ISSUE THREAD

**Issue by rogerbinns** [Nuitka/Nuitka#2039]
In standalone or onefile mode nuitka allows [apsw](https://github.com/rogerbinns/apsw) to be imported, but the module contents are empty.

This was originally reported at https://github.com/rogerbinns/apsw/issues/399

````console 
$ python3 -m pip install --user apsw
$ python3 -m pip install --user -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"
$ cat foo.py
import apsw

def main():
    print(dir(apsw)[:15))
    print(apsw.sqlitelibversion())

if __name__ == '__main__':
    main()
$ python3 foo.py
['AbortError', 'AuthError', 'Backup', 'BindingsError', 'Blob', 'BusyError', 'CantOpenError', 'Connection', 'ConnectionClosedError', 'ConnectionNotClosedError', 'ConstraintError', 'CorruptError', 'Cursor', 'CursorClosedError', 'EmptyError']
3.40.1
$ python3 -m nuitka foo.py 
Nuitka-Options:INFO: Used command line options: foo.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure that is intended.
Nuitka:WARNING: Using very slow fallback for ordered sets, please install 'ordered-set' PyPI package for best Python compile time performance.
Nuitka:INFO: Starting Python compilation with Nuitka '1.5rc3' on Python '3.10' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 6 files (no progress information available).
Nuitka-Scons:INFO: Compiled 19 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 12
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'called_for_link': 1
Nuitka:INFO: Keeping build directory 'foo.build'.
Nuitka:INFO: Successfully created 'foo.bin'.
$ ./foo.bin
['AbortError', 'AuthError', 'Backup', 'BindingsError', 'Blob', 'BusyError', 'CantOpenError', 'Connection', 'ConnectionClosedError', 'ConnectionNotClosedError', 'ConstraintError', 'CorruptError', 'Cursor', 'CursorClosedError', 'EmptyError']
3.40.1
$ python3 -m nuitka --standalone foo.py 
Nuitka-Options:INFO: Used command line options: --standalone foo.py
Nuitka:WARNING: Using very slow fallback for ordered sets, please install 'ordered-set' PyPI package for best Python compile time performance.
Nuitka:INFO: Starting Python compilation with Nuitka '1.5rc3' on Python '3.10' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.                       
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 8 files (no progress information available).
Nuitka-Scons:INFO: Compiled 25 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 12
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 1
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'called_for_link': 1
Nuitka:INFO: Keeping build directory 'foo.build'.                              
Nuitka:INFO: Successfully created 'foo.dist/foo.bin'.
$ foo.dist/foo.bin 
['__builtins__', '__compiled__', '__doc__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
Traceback (most recent call last):
  File "/space/t/foo.dist/foo.py", line 8, in <module>
  File "/space/t/foo.dist/foo.py", line 5, in main
AttributeError: module 'apsw' has no attribute 'sqlitelibversion'
$ python3 -m nuitka --onefile foo.py 
Nuitka-Options:INFO: Used command line options: --onefile foo.py
Nuitka:WARNING: Using very slow fallback for ordered sets, please install 'ordered-set' PyPI package for best Python compile time performance.
Nuitka:INFO: Starting Python compilation with Nuitka '1.5rc3' on Python '3.10' commercial grade 'not installed'.
Nuitka-Onefile:WARNING: Onefile mode cannot compress without 'zstandard' module installed.
Nuitka:INFO: Completed Python level compilation and optimization.                       
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 8 files (no progress information available).
Nuitka-Scons:INFO: Compiled 30 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 9
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 1
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'called_for_link': 1
Nuitka-Postprocessing:INFO: Creating single file from dist folder, this may take a while.
Nuitka-Onefile:INFO: Running bootstrap binary compilation via Scons.
Nuitka-Onefile:WARNING: Onefile mode cannot compress without 'zstandard' module installed.
Nuitka-Scons:INFO: Onefile C compiler: gcc (gcc).
Nuitka-Scons:INFO: Onefile linking program with 1 files (no progress information available).
Nuitka-Scons:INFO: Compiled 4 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 2
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'called_for_link': 1
Nuitka-Onefile:INFO: Keeping onefile build directory 'foo.onefile-build'.
Nuitka:INFO: Keeping dist folder 'foo.dist' for inspection, no need to use it.
Nuitka:INFO: Keeping build directory 'foo.build'.
Nuitka:INFO: Successfully created 'foo.bin'.
$ ./foo.bin
['__builtins__', '__compiled__', '__doc__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
Traceback (most recent call last):
  File "/tmp/onefile_3538309_1675438024_993920/foo.py", line 8, in <module>
    main()
  File "/tmp/onefile_3538309_1675438024_993920/foo.py", line 5, in main
    print(apsw.sqlitelibversion())
AttributeError: module 'apsw' has no attribute 'sqlitelibversion'
````

**Comment by kayhayen** [comment]
Am I seriously to guess to OS here, because the issue template cannot be filled, missing requested --version output?

**Comment by rogerbinns** [comment]
I reproduced on Ubuntu 22.10, the original poster on Windows.

**Comment by kayhayen** [comment]
From the looks of it, this is purely a single extension module. I took note of a `py.typed` data file, that is a kind of type that should never be included and started polluting packages, at least I am seeing it second time now. But no DLLs. I checked on Linux. Maybe it has a dependency on stdlib, but no error checking like high quality code has.

**Comment by rogerbinns** [comment]
Can you help me understand your comment?  ````py.typed```` is present because PEP 561 says it should be because there is a ````__init__.pyi```` with type stubs.  The DLL is ````__init__.so/.pyd````

What do you mean by "it has a dependency on stdlib"?

What error checking should be present in which code?

**Comment by kayhayen** [comment]
Oh my goodness, looking at the C code, the extension overloads `__getattr__` like all the cool kids now, to deliver attributes of `apsw` from `apsw.shell` because why not.

**Comment by rogerbinns** [comment]
The reason ````__getattr__```` is overloaded was because ````Shell```` used to be part of the main C code and got moved out separately.  That ensured existing user code was not broken by the move.

In any event that isn't exercised by the example code.  Note how the module is empty in standalone or onefile mode.

**Comment by kayhayen** [comment]
I thought it was delegating more stuff, but it still adds a hidden dependency I guess:

```
static PyObject *
apsw_getattr(PyObject *module, PyObject *name)
{
  PyObject *shellmodule = NULL, *res = NULL;
  const char *cname = PyUnicode_AsUTF8(name);

  if (strcmp(cname, "Shell") && strcmp(cname, "main"))
    return PyErr_Format(PyExc_AttributeError, "Unknown apsw attribute %R", name);

  shellmodule = PyImport_ImportModule("apsw.shell");
  if (shellmodule)
    res = PyObject_GetAttrString(shellmodule, cname);
  Py_XDECREF(shellmodule);
  return res;
}
```

**Comment by kayhayen** [comment]
I used `--python-flag=-v` and found no imports that it attempts at all. It seems the module should only ever remain empty if `init_exceptions` fails. But then it also returns NULL, which should come up in Nuitka, need to make sure that is not combined with an exception check, maybe none is set.

**Comment by rogerbinns** [comment]
I don't think it matters if nuitka doesn't pick it ````__getattr__``.  The developer can just use ````apsw.shell.Shell```` (new name) instead of ````apsw.Shell``` (old name).  The module being empty is however a problem.

**Comment by kayhayen** [comment]
Yes, I understand that is unrelated, although a problem for some uses by itself.

But I don't know why that happens at all. I would have to debug the C code of the extension, to find the non-obvious bug. I have added "import sqlite3" because that will make sure `libsqlite3.so` is inside the dist, just in case. I included all the modules, there are no data files. Something is tripping it up there, but Nuitka loaded it and calls the entry point, and there is really not a lot to be incompatible at that point. The dir is immediately empty, and yes, I would expect the methods there to be at a minimum, after `m = apswmodule = PyModule_Create(&apswmoduledef);` is executed.

**Comment by kayhayen** [comment]
Unfortunately I do not think I can afford the time to debug this outside of Nuitka commercial, somebody else needs to build this and single step/trace the extension module C code, if you want me to do it, get priority or full package here https://nuitka.net/doc/commercial.html#pricing

**Comment by kayhayen** [comment]
Typical reasons why extension modules do not work

a) Nuitka doesn't include all of stdlib by default. Module code attempts import, and handles lack of module more or less clearly. Does not apply here.

b) Nuitka does't include data files by default. The lack of files can cause extension modules or their DLLs to misbehave in strange ways. Does not apply here. The "indicator file" is worthless at run-time and in fact --include-package-data=apsw ought to not include that one. I made a mental note to improve that. Standalone deployments do not need those files for sure.

c) Nuitka doesn't include DLLs by default. The lack of DLLs can cause inability to import, run properly, whatever on any later date. Does not apply here.

So what applies here? I am honestly curious myself. And now that I checked more closely, maybe I oversaw something, because the module returned a rich `PyObject_Dir()`, so that is something to look at.

**Comment by rogerbinns** [comment]
I did debug more.  I added a printf to the beginning of ````PyInit_apsw````.  The print did happen in nuitka regular mode. 
 In standalone/onefile mode the printf is not called at all.

My guess would be that nuitka was expecting ````__init__.py````  (ie Python source) when ````__init__.so```` is actually a shared library.  It is somewhat unconventional but does work with CPython and PyPy.  The sample code will work fine if every file in the apsw module is deleted except the ````__init__.so````.  I also tested this scenario.

APSW is built by default including SQLite code directly into the shared library - there is no external dependency.

**Comment by rogerbinns** [comment]
That certainly seems to be the case.  If you grab the ````__init__.so````, put it alongside the test file named ````apsw.so```` and get rid of the rest of apsw, then nuitka works perfectly in standalone and onefile mode.

**Comment by kayhayen** [comment]
Ah, yes, when listing the DLLs I saw it, but I considered it a bug of the DLL listing, that is indeed not going to work for Nuitka's loader generally. This is something to support then I guess. The traced one with values, is from the sqlite3 import that I added, in case it#s the DLLs, so that confused me.

**Comment by kayhayen** [comment]
So, the module we see without workarounds is a namespace module of Nuitka, these are empty and populated from the package being a directory.

**Comment by kayhayen** [comment]
So, this is indeed an incompatibility of Nuitka, I guess. CPython accepts this I understand, and so should Nuitka of course then, and I guess, CPython will not accept anything below a `apsw.so` though, since it will not check its `__path__` likely. Ok, I can definitely work from there, but it will take a bit of time.

**Comment by kayhayen** [comment]
@rogerbinns thanks for helping with this one, I can take it from here, but it is touching the importing machinery of Nuitka, which is always a complicated task

**Comment by rogerbinns** [comment]
Thanks for looking into it - I don't envy you touching anything to do with Python importing!

I [have documented](https://github.com/rogerbinns/apsw/issues/399#issuecomment-1416179581) a workaround for the original poster so they should be able to keep going with nuitka.

**Comment by kayhayen** [comment]
I think, an `__init__.so` is supposed to work with Python, and it definitely also would have to be added to Nuitka to, to detect this kind of directory as a package,  although I not a 100% sure. We might look into this in one of the streams, such that we can become compatible with seeing it, and producing it potentially.

**Comment by abdelouahabb** [comment]
Any update ?

**Comment by kayhayen** [comment]
No, but streaming has restarting, but even within that, it may not be a priority to do this.

**Comment by KRRT7** [comment]
this actually was fixed on an earlier version of nuitka.
