### ISSUE TITLE
nuitka 1.4.3 does not support --include-resource=icon.png:icon.png?

### ISSUE THREAD

**Issue by pendave** [Nuitka/Nuitka#2041]
As I find nuitka 1.4.3 does not support `--include-resource=icon.png:icon.png` Then the icon displayed in the upper right corner of my PyQt5 window is the default gray icon, and the icon of the program displayed on the taskbar is also the gray icon, how can I change it to my own icon?

![image](https://user-images.githubusercontent.com/1331881/216817849-40a9f488-c97c-45bf-8506-0869ba6be95a.png)

I asked ChatGTP how to handle with this issue, but I have no idea yet.

It says:
1. If the --include-resource option is not supported in nuitka version 1.4.3, then you can change the window's icon by
Set the icon manually in code: You can use Qt's QtGui.QIcon class to read the icon file and set it as the window's icon. The code example is as follows.

`from PyQt5.QtGui import QIcon
app = QApplication(sys.argv)
app.setWindowIcon(QIcon('icon.png'))
window = QMainWindow()
window.show()
sys.exit(app.exec_())
`

2. Package icon files and executable files together: You can use a packaging tool, such as pyinstaller, to package icon files and executable files together. Please refer to pyinstaller's documentation for details.

Yes, in nuitka version 1.4.3, there is no method provided to package external resources (such as images) directly. Therefore, this version does not automatically package external files and you need to place them in the correct location at runtime in order for your application to use them properly.

:(

**Comment by kayhayen** [comment]
This report is garbage, you can include data files no problem.

**Comment by pendave** [comment]
> This report is garbage, you can include data files no problem.

Thanks, I prefer an answer for my request. Any tutorial or manual to include data files such as the icon.png? Please help!

**Comment by Maxwell175** [comment]
https://nuitka.net/doc/user-manual.html#use-case-4-program-distribution
