### ISSUE TITLE
Output not being placed in --output-dir

### ISSUE THREAD

**Issue by Thermohaliate** [Nuitka/Nuitka#2044]
* Nuitka version, full Python version, flavor, OS, etc.

Nuitka: 1.4.3
Commercial: None
Python: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: D:\Data\Python\Cache\virtualenvs\testing-aD9iks_E-py3.10\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc)

* How did you install Nuitka and Python

poetry add nuitka@latest

* The specific PyPI names and versions

adal==1.2.7
astroid==2.13.2
asttokens==2.2.1
backcall==0.2.0
black==22.12.0
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==2.1.1
click==8.1.3
colorama==0.4.6
comm==0.1.2
cryptography==39.0.0
debugpy==1.6.5
decorator==5.1.1
dill==0.3.6
entrypoints==0.4
executing==1.2.0
idna==3.4
ipykernel==6.20.1
ipython==8.8.0
isort==5.11.4
jedi==0.18.2
jupyter_client==7.4.8
jupyter_core==5.1.3
lazy-object-proxy==1.9.0
matplotlib-inline==0.1.6
mccabe==0.7.0
mypy-extensions==0.4.3
nest-asyncio==1.5.6
Nuitka==1.4.3
office365-rest-client==2.2.0
ordered-set==4.1.0
packaging==23.0
parso==0.8.3
pathspec==0.10.3
pickleshare==0.7.5
platformdirs==2.6.2
prompt-toolkit==3.0.36
psutil==5.9.4
pure-eval==0.2.2
pycparser==2.21
Pygments==2.14.0
PyJWT==2.6.0
pylint==2.15.10
python-dateutil==2.8.2
pywin32==305
pyzmq==25.0.0
requests==2.28.1
six==1.16.0
stack-data==0.6.2
tomli==2.0.1
tomlkit==0.11.6
tornado==6.2
traitlets==5.8.1
typing_extensions==4.4.0
urllib3==1.26.14
wcwidth==0.2.5
wrapt==1.14.1
zstandard==0.19.0

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

```python
# main.py

print("Hello World")
```

* Provide in your issue the Nuitka options used

`nuitka main.py --output-dir=bin --output-filename="Hello World.exe" --onefile --remove-output`

* Explanation

When compiling with the above command, the `.exe` ends up in the root directory instead of in the "bin" folder. Before I made this short example, I was trying this on my main project and can say that `Nuitka` also doesn't copy anything specified with `--include-data-dir` and `--include-data-files` to the specified output directory.

**Comment by kayhayen** [comment]
It happens that #1878 has just been fixed and is slated for 1.4.4 release that I am about to make. I am closing this as a duplicate.
