### ISSUE TITLE
"TypeError: joinpath() takes at most 1 argument" with jsonschema 4.17.1+ and --follow-imports

### ISSUE THREAD

**Issue by hermannch** [Nuitka/Nuitka#2046]
### intro

Hi,

compiled executables raises `TypeError: joinpath() takes at most 1 argument (2 given)` on `jsonschema.validate()` if built with `nuitka --follow-imports ...`
Omitting `--follow-imports` doesn't have this error.

Since https://github.com/python-jsonschema/jsonschema/commit/4f8f346cc475439715833ac6bd6e5c5e3dc21ee3#diff-d38128373c229147d38e1c4707cdecd7e510c14eef80565374fe9a69627e4676R107

likely related: https://github.com/Nuitka/Nuitka/issues/1274

### info

* Affected nuitka versions: `1.1.8`, `1.4.3` , `develop`, `factory` (as of 2023-02-08, a.k.a. `1.5rc5`)
* How did you install Nuitka and Python: python3.10 is from ubuntu22.04. nuitka is from pip/github (see sscce below)
* this is a regression: *no*

### SSCCE

```sh
#!/bin/sh
set -eux


# `nuitka --follow-imports ...` breaks jsonschema 4.17.1
# jsonschema added a call to Path.joinpath(), commit: 4f8f346cc475439715833ac6bd6e5c5e3dc21ee3
# https://github.com/python-jsonschema/jsonschema/commit/4f8f346cc475439715833ac6bd6e5c5e3dc21ee3#diff-d38128373c229147d38e1c4707cdecd7e510c14eef80565374fe9a69627e4676R107


cat << WRITE_REQUIREMENTS > requirements.txt
jsonschema==4.17.1
# affected as well: Nuitka==1.1.8
# affected as well: Nuitka==1.4.3
https://github.com/Nuitka/Nuitka/archive/factory.zip
WRITE_REQUIREMENTS

rm -rf venv
python3 -m venv venv
. ./venv/bin/activate

pip install -r requirements.txt

rm -rf mwe.py
cat << MWE > ./mwe.py
#!/usr/bin/env python3


# seems to work
from pathlib import Path
p = Path("foo")
x = p.joinpath("bar", "baz")
print(x)

# raises: TypeError: joinpath() takes at most 1 argument (2 given)
import jsonschema
jsonschema.validate([2, 4], {"maxItems": 2})
print("valid")
MWE

rm -rf mwe.build mwe.bin
python3 -m nuitka --version
python3 -m nuitka \
	--follow-imports \
	mwe.py

python3 mwe.py #works
./mwe.bin
# + ./mwe.bin
# Traceback (most recent call last):
#   File "./nuitka-joinpath-bug/mwe.py", line 15, in <module>
#     jsonschema.validate([2, 4], {"maxItems": 2})
#   File "./nuitka-joinpath-bug/venv/lib/python3.10/site-packages/jsonschema/validators.py", line 1116, in validate
#     cls.check_schema(schema)
#   File "./nuitka-joinpath-bug/venv/lib/python3.10/site-packages/jsonschema/validators.py", line 226, in check_schema
#     validator = Validator(
#   File "<attrs generated init jsonschema.validators.create.<locals>.Validator>", line 5, in __init__
#   File "./nuitka-joinpath-bug/venv/lib/python3.10/site-packages/jsonschema/validators.py", line 216, in __attrs_post_init__
#     self.resolver = RefResolver.from_schema(
#   File "./nuitka-joinpath-bug/venv/lib/python3.10/site-packages/jsonschema/validators.py", line 771, in from_schema
#     return cls(base_uri=id_of(schema), referrer=schema, *args, **kwargs)  # noqa: B026, E501
#   File "./nuitka-joinpath-bug/venv/lib/python3.10/site-packages/jsonschema/validators.py", line 744, in __init__
#     self.store = _utils.URIDict(_store_schema_list())
#   File "./nuitka-joinpath-bug/venv/lib/python3.10/site-packages/jsonschema/validators.py", line 107, in _store_schema_list
#     for version in package.joinpath("schemas", "vocabularies").iterdir():
# TypeError: joinpath() takes at most 1 argument (2 given)
```

**Comment by kayhayen** [comment]
Thanks, I was not aware that `joinpath` is supposed to accept multiple arguments, although naturally it might make sense that way.

**Comment by hermannch** [comment]
yeah, https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.joinpath says its signature is
```
PurePath.joinpath(*other)
```

**Comment by hermannch** [comment]
if you throw some hints at me , i ca try to come up with a fix

**Comment by kayhayen** [comment]
The implementation of `joinpath` is in this C function: https://github.com/Nuitka/Nuitka/blob/08a273cd1f7f44872ce0b663e9b85eff1039e6df/nuitka/build/static_src/MetaPathBasedLoaderResourceReaderFiles.c#L226

**Comment by kayhayen** [comment]
For complexity, it also is used as `__truediv__` which is actually a joinpath with a single argument. Are you familiar enough with the C extension APIs there?

**Comment by kayhayen** [comment]
So it seems that `joinpath` is indeed `varargs` and has no argument names. Currently, it accepts `child`. Not sure where that came from, but this is I think from the ABC:

```
//    @abc.abstractmethod
//    def joinpath(self, child):
//        """
//        Return Traversable child in self
//        """
//
```

And Nuitka implements that.

**Comment by kayhayen** [comment]
I checked the Python 3.11 source and it's a mix of functions that do `child` and `*children` as arguments. I think I may not have seen the crash with Python 3.9, but only 3.10, maybe some generic machinery got changed so you can expect it at least from some, and does not get resolved in Python core. 

Interestingly, I was not able to find the abstract base class, not sure where I took this from originally. I thought I saw an ABC somewhere with the methods, but whatever it is, it's not like Python itself takes it more serious than it has to.

But being C code, what we can do, is to check for keyword arguments, so calling with `child = ` will still work, although I doubt that is done in actual code, it will still be compatible, and if no keyword arguments are given, well and then treat all arguments as a tuple, not limiting to one.

So in an absurd sense, Nuitka complies with both calling signatures. I will have this shortly I think, just takes a loop and then it will work.

**Comment by kayhayen** [comment]
And for `iterdir` being used not on the top level, now I get an `NotImplementedError` from Nuitka. I was lazy and never saw this one before. What is strange how this works with 3.9 then, which it does. I guess, something there exposes us more clearly.

**Comment by kayhayen** [comment]
As a first step, I added now optimization of `os.listdir` that we will need to use for `iterdir` to work, the implementation got to be based around that. Need to check why `iterdir` with empty argument got implemented as a package name based thing. I believe `jsonschema` is actually after directories. Since with Nuitka package directories are only created as necessary, probably this needs to be compiled with `os.listdir`.

**Comment by kayhayen** [comment]
I do not find any trace in the issue tracker or anywhere else, not even a test file, that uses the `iterdir` interface at all. Checking my private repo, I found that I did it roughly at the same time as I added the files stuff, also for `jsonschema` and I think, `iterdir` is also not really going to work, even if called with empty string value. So we got to add more tests and get those to work I suppose.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.4.5 that I just made.

**Comment by hermannch** [comment]
thank you for the quick fix.

it would be tremendously helpful if you could add references to issues to your commit messages, like so
`Fixes: https://github.com/Nuitka/Nuitka/issues/2046`
This will enable other people to follow along much easier

**Comment by kayhayen** [comment]
Yes, I could be so much more helpful if I spent my time to save the time of others. I wish people realized that it should be the other way around.
