### ISSUE TITLE
output executable missing part of original script name

### ISSUE THREAD

**Issue by SirDank** [Nuitka/Nuitka#2050]
> python -m nuitka --version

Commercial: None
Python: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Program Files\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\cl.exe (cl 14.3).

install method: pip
virtualenv: no

  > python -m pip freeze

certifi==2022.12.7
Nuitka==1.4.5
ordered-set==4.1.0
zstandard==0.19.0

  > Nuitka options used

Nuitka-Options:INFO: Used command line options: --standalone --clang --warn-unusual-code --assume-yes-for-downloads --show-anti-bloat-changes --plugin-enable=pylint-warnings --enable-plugin=anti-bloat --noinclude-setuptools-mode=nofollow --noinclude-pytest-mode=nofollow --noinclude-unittest-mode=nofollow --noinclude-IPython-mode=nofollow --include-package-data=grapheme --windows-company-name="Dankware Inc." --windows-product-name=dank.tool --windows-file-version=69.69.69.69 --windows-product-version=69.69.69.69 --windows-file-description=dank.tool --windows-uac-admin --windows-icon-from-ico=d:dankware.ico --include-package=urllib3 --include-package-data=certifi --include-data-file=d:start.mp3=./ --include-data-file=d:stop.mp3=./ --include-data-file=d:dankware.wav=./ --include-data-file=d:dankware.ico=./ --windows-force-stderr-spec=dank.tool_errors.txt dank.tool.py

  > Console Output Snippet:

Nuitka:INFO: Keeping build directory 'dank.tool.build'.
Nuitka:INFO: Successfully created 'dank.tool.dist\dank.exe'.

  > Error:

The final executable is saved as "dank.exe" instead of "dank.tool.exe"

**Comment by kayhayen** [comment]
This has to have something to do with the `.` in the executable name.

**Comment by kayhayen** [comment]
You can work around for now with `--output-filename=dank-tool` I suppose. Also I noticed you are not setting the icon of the executable. Generally your command line looks old. I assume this is a regression you are reporting?

**Comment by SirDank** [comment]
The options have "--windows-icon-from-ico=d:dankware.ico" and yeah it is regression.

**Comment by kayhayen** [comment]
Yup, it's too many options definitely. :)

**Comment by kayhayen** [comment]
Happens in plain accelerated mode too. Then I guess I will try and git bisect it.

**Comment by SirDank** [comment]
could you check one other thing, im not sure if it has been fixed already but i had an issue a while ago with dragging and dropping files onto the console window, the error being the file path would not appear ( it used to appear before so im guessing its regression again )

**Comment by kayhayen** [comment]
> could you check one other thing, im not sure if it has been fixed already but i had an issue a while ago with dragging and dropping files onto the console window, the error being the file path would not appear ( it used to appear before so im guessing its regression again )

I do not like to mix issues. If you have a reproducible issue, I invite you to create another issue.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.
