### ISSUE TITLE
Feature request: install with extras

### ISSUE THREAD

**Issue by bersbersbers** [Nuitka/Nuitka#2053]
After `pip install nuitka`, during runtime, Nuitka asks to also install `ordered-set` (for performance, I guess) and `zstandard` (this is even required, I think).

I wonder if it might make sense to be able to install these soft-dependencies with pip, e.g., using extras such that `pip install nuitka[orderedsets,onefile]` installs both dependencies. Otherwise, projects depending on `nuitka` will have to separately document and maintain these dependencies.

**Comment by kayhayen** [comment]
Can you make a PR with  this change, I am not familiar with it, but totally open to it. The problem with these is that they would have to be versioned, as e.g. `orderedset` fails to build without MSVC installed, and `zstandard` is not available everywhere. Please help me here.

**Comment by bersbersbers** [comment]
Sure! See #2058, considering that this is more of a technical demo at this point. Feel free to adapt especially the naming.

**Comment by kayhayen** [comment]
Yes, I commented there already. Super useful indeed. Thanks for the proposal and demo code.

**Comment by bersbersbers** [comment]
Works great on `develop` already, thanks!

**Comment by bersbersbers** [comment]
Or so I though. Even though `zstandard` is installed, it is not found:

> Nuitka-Onefile:WARNING: Onefile mode cannot compress without 'zstandard' module installed.

Not sure if this is an issue with installation or rather Python 3.11 or Windows, both of which I have been trying for the first time with Nuitka:

```
(project_dev) C:\code\project>python -m pip show nuitka && python -m pip install zstandard && echo. > empty.py && python -m nuitka empty.py --onefile
Name: Nuitka
Version: 1.5rc9
Summary: Python compiler with full language support and CPython compatibility
Home-page: https://nuitka.net
Author: Kay Hayen
Author-email: Kay.Hayen@gmail.com
License: Apache License, Version 2.0
Location: C:\Users\bers\.pyenv-win-venv\envs\project_dev\Lib\site-packages
Requires: ordered-set, zstandard
Required-by:
Requirement already satisfied: zstandard in c:\users\bers\.pyenv-win-venv\envs\project_dev\lib\site-packages (0.19.0)
Nuitka-Options:INFO: Used command line options: empty.py --onefile
Nuitka:WARNING: The Python version '3.11' is not officially supported by Nuitka '1.5rc9', but an upcoming release will change that. In the mean time use Python version '3.10' instead or newer
Nuitka:WARNING: Nuitka.
Nuitka:INFO: Starting Python compilation with Nuitka '1.5rc9' on Python '3.11' commercial grade 'not installed'.
Nuitka-Onefile:WARNING: Onefile mode cannot compress without 'zstandard' module installed.
```

**Comment by bersbersbers** [comment]
Hm, same thing on Linux:
```
...
Successfully built Nuitka
Installing collected packages: zstandard, ordered-set, Nuitka
Successfully installed Nuitka-1.5rc9 ordered-set-4.1.0 zstandard-0.19.0

(project_dev) bers@hostname:/mnt/c/Code/project$ python -m nuitka project/project.py --quiet --onefile --static-libpython=no --enable-plugin=pyside6 --include-module=pytest --include-module=_pytest --include-module=unittest --nofollow-import-to=setuptools --nofollow-import-to=tkinter --linux-icon=project/icon/favicon.ico
Nuitka:WARNING: The Python version '3.11' is not officially supported by Nuitka '1.5rc9', but an upcoming release will change that. In the mean time use Python version '3.10' instead or newer
Nuitka:WARNING: Nuitka.
Nuitka-Onefile:WARNING: Onefile mode cannot compress without 'zstandard' module installed.
Nuitka-Onefile:WARNING: Onefile mode cannot compress without 'zstandard' module installed.

(project_dev) bers@hostname:/mnt/c/Code/project$ python -m pip show zstandard
Name: zstandard
Version: 0.19.0
Summary: Zstandard bindings for Python
Home-page: https://github.com/indygreg/python-zstandard
Author: Gregory Szorc
Author-email: gregory.szorc@gmail.com
License: BSD
Location: /home/bers/.pyenv/versions/project_dev/lib/python3.11/site-packages
Requires:
Required-by: Nuitka
```

**Comment by kayhayen** [comment]
Very strange. On Windows the standalone does not work at all for me now. Version 0.15 or higher ought to be good. I will trry and update, but also since 3.11 is not supported, who whos if it even considers it. Since it is partial now, that would be a mistake though.

**Comment by kayhayen** [comment]
On thing I noticed, that for `orderedset` on Windows will only install when MSVC is available, and that's e.g. not going to be the case for many, so I am removing that. But I had dropped that down to older than 3.7 which on Windows, nobody should use, since there are the locale problems before 3.8 anyway. I need to try and pip install this myself. Locally it works fine for me.

**Comment by kayhayen** [comment]
For 3.10 just now didn't happen for me.

**Comment by kayhayen** [comment]
Yes, but with 3.11 it does. I guess, when finding compressor Pythons, it is not considered, despite being the running one. That has to be a bug. For me it does this:

> Nuitka-Onefile:INFO: Using external Python '/usr/bin/python3.8' to compress the payload.

But it should not have looked elsewhere.

**Comment by kayhayen** [comment]
Well, arguably it's a bit rought to say, that the current one is generically good for everything, in the case of scons, it may happen that we want to update our inline copy first. But for zstandard it is now considering partially supported Python versions by Nuitka to automatically be usable, so for 3.12 one day this will be automatic.

**Comment by kayhayen** [comment]
I am closing this one, since its main purpose has been achieved.
