### ISSUE TITLE
`AttributeError: 'NoneType' object has no attribute 'getAsString'` with `--include-module=pytest`

### ISSUE THREAD

**Issue by bersbersbers** [Nuitka/Nuitka#2054]
```
$ python -m nuitka --version
1.4.6
Commercial: None
Python: 3.10.10 (main, Feb 12 2023, 13:26:48) [GCC 11.3.0]
Flavor: pyenv
Executable: /home/bers/.pyenv/versions/project/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.1
Version C compiler: /usr/bin/gcc (gcc).
```

```
$ touch empty.py; python -m nuitka empty.py --static-libpython=no --include-module=pytest
Nuitka-Options:INFO: Used command line options: empty.py --static-libpython=no --include-module=pytest
Nuitka:INFO: Starting Python compilation with Nuitka '1.4' on Python '3.10' commercial grade 'not installed'.
Traceback (most recent call last):
  File "/home/bers/.pyenv/versions/project/lib/python3.10/site-packages/nuitka/__main__.py", line 151, in <module>
    main()
  File "/home/bers/.pyenv/versions/project/lib/python3.10/site-packages/nuitka/__main__.py", line 137, in main
    MainControl.main()
  File "/home/bers/.pyenv/versions/project/lib/python3.10/site-packages/nuitka/MainControl.py", line 942, in main
    main_module = _createMainModule()
  File "/home/bers/.pyenv/versions/project/lib/python3.10/site-packages/nuitka/MainControl.py", line 232, in _createMainModule
    Recursion.checkPluginSinglePath(
  File "/home/bers/.pyenv/versions/project/lib/python3.10/site-packages/nuitka/importing/Recursion.py", line 302, in checkPluginSinglePath
    module = recurseTo(
  File "/home/bers/.pyenv/versions/project/lib/python3.10/site-packages/nuitka/importing/Recursion.py", line 75, in recurseTo
    Plugins.onModuleRecursion(
  File "/home/bers/.pyenv/versions/project/lib/python3.10/site-packages/nuitka/plugins/Plugins.py", line 936, in onModuleRecursion
    plugin.onModuleRecursion(
  File "/home/bers/.pyenv/versions/project/lib/python3.10/site-packages/nuitka/plugins/standard/AntiBloatPlugin.py", line 461, in onModuleRecursion
    % (handled_module_name, source_ref.getAsString()),
AttributeError: 'NoneType' object has no attribute 'getAsString'
```

**Comment by kayhayen** [comment]
I hope you are only including all of `pytest` for demonstration purposes. Not a good idea generally, but definitely a valid bug.

**Comment by kayhayen** [comment]
Obviously, the warning is moot when the user asked to do it. Asking you to change the mode to `allow` would be a strange idea there.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by bersbersbers** [comment]
Thanks, factory is working.

I'll briefly explain why I am doing this: I am currently experimenting with several Python "one-file packagers". I tried `pyinstaller` first, and was able to include all tests in my first test executables which was great to ensure that all functionality would still be working after deployment (and I did find a few notable bugs that way, so I would in fact recommend doing that). So naturally, I tried the same thing with Nuitka. Test discovery is not working yet, and maybe it never will so this whole exercise is moot, but compilation finishes fine now and I am prepared to invest a bit more time to see if I can get things running, due to the benefits observed before.

Note that in standalone mode, including `pytest` makes my executable grow from 71 MB (mainly due to numpy, matplotlib, PySide6, I assume) to 73 MB, so I don't care too much about the overhead. Are there other reasons why I should not include `pytest` at all?

**Comment by kayhayen** [comment]
Actually for tests, there is stuff in Nuitka, but it requires you to compile a package and test that. Checkout `tests/test-runners` and for as long as we do not have isolation, importing the tests might work for discovery there. Nuitka makes it hard to include them though, plugin might decide `bytecode` for them, but e.g. `sourcecode` will not work. This is an underdeveloped area, and from my checks, pytest was really bad at making the scanning run from within a binary.

With multidist however, a dedicated binary name could probably be added that will run the tests.

You can probably `--nofollow-import-to=PySide6` or enable the `no-qt` plugin and the like, to trim it, asssuming it's not a hard dependency.

**Comment by kayhayen** [comment]
What I also mean to say, I am not against making this work well with onefile mode.

**Comment by bersbersbers** [comment]
> You can probably `--nofollow-import-to=PySide6` or enable the `no-qt` plugin and the like, to trim it, asssuming it's not a hard dependency.

Well, it's a GUI application, so `PySide6` is a very hard dependency.

> What I also mean to say, I am not against making this work well with onefile mode.

Thanks. I will try for a bit and share updates if I think they're useful :)

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.4.7 that I just made.
