### ISSUE TITLE
How to exclude all Python / pip modules

### ISSUE THREAD

**Issue by leelx78** [Nuitka/Nuitka#2055]
Hi, I have Nuitka 1.4.4. installed via pip on Debian 9 and all works open Python 3.9.4.

I have all my own Python source repo in /source/** which only exists on the development machine and all my Python modules depend on those (e.g. modules in /source/shared/*). I need to distribute code on deployment machines which do not have the /source folder but would have all third-party pip modules already installed.

So, the task is to protect and deploy MY code (e.g. everything on /source) and not to care for any other standard modules, which can be installed via pip separately.

What's the best way to do this? If I build as standalone it takes forever and compiles everything unnecessarily. If I manually include every single one of my python files it works but it's a mess. If I manually exclude every pip module it should work (haven't tested yet) but also a mess.

There must be a better way to tell Nuitka to not follow any import outside /source? I couldn't figure that out from the docs sorry

Please let me know thanks!

**Comment by kayhayen** [comment]
You build a wheel with your software, then enable distutils integration of Nuitka. It is described in the user manual.

**Comment by kayhayen** [comment]
For standalone mode, you could write a plugin that decides `bytecode` for all code that is not yours. It is dubious however if that is going to produce usable results due to errors with mixing code from nuitka's loader and extension modules, which is many modules.

**Comment by leelx78** [comment]
Thanks Kay,

`You build a wheel with your software, then enable distutils integration of Nuitka. It is described in the user manual.`
I went through he manual and it's not clear to me how to do it sorry..


it would be idea if we could write something like --noinclude-pip, that would be very useful since in most cases we use nuitka to protect our own code while all that is from pip is already public. 

--nofollow-import-to="<folder>" would also be great!

Otherwise I can try to make a script to exclude every module in pip list but that seems a hack?

**Comment by kayhayen** [comment]
Building wheels is not a skill I can teach, sorry. But the Python website has all the information. If you have that, making a deployable program that is compiled with just your code is trivial.

I told you that a Nuitka plugin is the way to go. I will admit these are not too well documented, but they can do anything you want, including what you asked for.

**Comment by kayhayen** [comment]
Searching the word "wheel" in that manual finds this: https://nuitka.net/doc/user-manual.html#use-case-5-setuptools-wheels
