### ISSUE TITLE
--include-data-dir=d:\path\to\folder=folder does not include python scripts and sub folders

### ISSUE THREAD

**Issue by SirDank** [Nuitka/Nuitka#2056]
> python -m nuitka --version

1.4.7
Commercial: None
Python: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Program Files\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\cl.exe (cl 14.3).

install method: pip
virtualenv: no

  > python -m pip freeze

certifi==2022.12.7
Nuitka==1.4.7
ordered-set==4.1.0
zstandard==0.19.0

  > Nuitka options used

Nuitka-Options:INFO: Used command line options: --standalone --clang --warn-unusual-code --assume-yes-for-downloads --show-anti-bloat-changes --plugin-enable=pylint-warnings --enable-plugin=anti-bloat --noinclude-setuptools-mode=nofollow --noinclude-pytest-mode=nofollow --noinclude-unittest-mode=nofollow --noinclude-IPython-mode=nofollow --include-package-data=grapheme --windows-company-name="Dankware Inc." --windows-product-name=dank.fusion-fall --windows-file-version=69.69.69.69 --windows-product-version=69.69.69.69 --windows-file-description=dank.fusion-fall --windows-uac-admin --windows-icon-from-ico=d:\dankware.ico --include-package=urllib3 --include-package-data=certifi --include-data-file=d:\ffextract.py=./ --include-data-dir=d:\unitypack=unitypack --include-data-file=d:\dankware.wav=./ --include-data-file=d:\dankware.ico=./ --windows-force-stderr-spec=dank.fusion-fall_errors.txt dank.fusion-fall.py

  > list of files and folders to be included:
  
  ['asset.py', 'assetbundle.py', 'classes.json', 'engine', 'enums.py', 'environment.py', 'export.py', 'modding.py', 'object.py', 'resources.py', 'strings.dat', 'structs.dat', 'type.py', 'utils.py', '__init__.py']

  > List of files included:
  
  ['classes.json', 'strings.dat', 'structs.dat']
  
  > List of files/folders it has missed including:

files: ['asset.py', 'assetbundle.py', 'enums.py', 'environment.py', 'export.py', 'modding.py', 'object.py', 'resources.py', 'type.py', 'utils.py', '__init__.py']

folder: ['engine']

  > note:
  
  --include-package-data seems to be working correctly

**Comment by kayhayen** [comment]
No data file option is supposed to include Python code. The all exclude files known to be code.

Code can be include with other include options though. Look for --include-module  e.g. and Nuitka supports iteration over packages with standard functions as describeb in the user manual, if this is some sort of plugin mechanism.
