### ISSUE TITLE
unable to drag and drop files onto the terminal window to paste path

### ISSUE THREAD

**Issue by SirDank** [Nuitka/Nuitka#2057]
> python -m nuitka --version

1.4.7
Commercial: None
Python: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Program Files\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\cl.exe (cl 14.3).

install method: pip
virtualenv: no

  > python -m pip freeze

certifi==2022.12.7
Nuitka==1.4.7
ordered-set==4.1.0
zstandard==0.19.0

  > Nuitka options used

Nuitka-Options:INFO: Used command line options: --standalone --clang --warn-unusual-code --assume-yes-for-downloads --show-anti-bloat-changes --plugin-enable=pylint-warnings --enable-plugin=anti-bloat --noinclude-setuptools-mode=nofollow --noinclude-pytest-mode=nofollow --noinclude-unittest-mode=nofollow --noinclude-IPython-mode=nofollow --include-package-data=grapheme --windows-company-name="Dankware Inc." --windows-product-name=dank.fusion-fall --windows-file-version=69.69.69.69 --windows-product-version=69.69.69.69 --windows-file-description=dank.fusion-fall --windows-uac-admin --windows-icon-from-ico=d:\dankware.ico --include-package=urllib3 --include-package-data=certifi --include-data-file=d:\ffextract.py=./ --include-data-dir=d:\unitypack=unitypack --include-data-file=d:\dankware.wav=./ --include-data-file=d:\dankware.ico=./ --windows-force-stderr-spec=dank.fusion-fall_errors.txt dank.fusion-fall.py

  > sample script
  
  ```py
  path_to_file = input("\n  > Drag and Drop your file here: ")
  print(path_to_file)
  ```
  
  > note:
  
  This used to work on an older version of nuitka

**Comment by kayhayen** [comment]
This is a feature of the terminal, and I just tested it, works fine with Visual Code and cmd.exe both. There is probably hardly a way for Nuitka to stop it from working.

**Comment by SirDank** [comment]
There were older builds of nuitka with which this feature worked though

**Comment by kayhayen** [comment]
There is no version of Nuitka with which it doess not work.

**Comment by SirDank** [comment]
Wait are you sure about that? I can send you an executable in which it does work

**Comment by kayhayen** [comment]
I am sure of that, yes. And I do not execute things sent to me. You probably didn't try your reproducer yourself?
