### ISSUE TITLE
Unsigned binaries give "ASP: Security policy would not allow process" in macOS arm binaries

### ISSUE THREAD

**Issue by vicalloy** [Nuitka/Nuitka#2066]
1. I use thid command to build `python -m nuitka --follow-imports --clang mario_main.py`, the build is success. 
1. I get output `[1]    82285 killed  ./mario_main.bin` when run the program, and find`kernel ASP: Security policy would not allow process: 78734, .../mario_main.bin` in console.
1. `python -m nuitka --standalone --follow-imports --clang mario_main.py` is fine.

* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
```
1.4.7
Commercial: None
Python: 3.10.8 (main, Oct 21 2022, 22:22:30) [Clang 14.0.0 (clang-1400.0.29.202)]
Flavor: Homebrew Python
Executable: /Users/huxm/.poetry_env/mario-sNRpVPNR-py3.10/bin/python
OS: macOS 13.1 (22C65)
Arch: arm64
Version C compiler: /usr/bin/clang (clang).
```
* How did you install Nuitka and Python
poetry

**Comment by kayhayen** [comment]
Note that homebrew is not a good choice for making portable Python binaries. From my experience they do not go back to older OSes.

I have never tried to run accelerated Python compilations on other machines. That is also nothing supposed to be supported. People do use that with Docker containers where they bring their own environment, and have things under control. 

Signing is done for app bundles only, and I think I know that unsigned binaries do not run on arm64 with newer macOS anymore. So I think Apple doesn't allow this anymore, but it would also depend on the Homebrew installation to match relatively well. Not sure if that is what you intended there. But feel free to sign the binary manually with codesign, and maybe if this is really a commercial need, if you become a priority subscriber, I can also add something that will sign it and not be standalone, but it surely is nothing I consider at this point.

**Comment by kayhayen** [comment]
Closing for lack of feedback.
