### ISSUE TITLE
decompiling

### ISSUE THREAD

**Issue by aidgamesa** [Nuitka/Nuitka#2067]
How to decompile?

**Comment by kayhayen** [comment]
Not possible

**Comment by kayhayen** [comment]
Unlike other tools, Nuitka does not include the Python bytecode of compiled code, but rather generates C code which then is translated to machine code. You can therefore decompile it just as much as you can decompile C code. For protecting contained data Nuitka commercial has more options to protect data, embedd data files protected, and even tracebacks: https://nuitka.net/doc/commercial.html
