### ISSUE TITLE
Windows and custom MinGW64 gives "Error: ld.exe: cannot find ltrans0.ltrans.o: No such file or directory"

### ISSUE THREAD

**Issue by Rimush** [Nuitka/Nuitka#2069]
> C:\work\test\2>python -m nuitka --windows-disable-console --follow-imports main.py
> Nuitka-Options:INFO: Used command line options: --windows-disable-console --follow-imports main.py
> Nuitka:INFO: Starting Python compilation with Nuitka '1.4.7' on Python '3.10' commercial grade 'not installed'.
> Nuitka:INFO: Completed Python level compilation and optimization.
> Nuitka:INFO: Generating source code for C backend compiler.
> Nuitka:INFO: Running data composer tool for optimal constant value handling.
> Nuitka:INFO: Running C compilation via Scons.
> Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
> Nuitka-Scons:INFO: Backend linking program with 6 files (no progress information available).
> c:/work/tools/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\Rimush\AppData\Local\Temp\ccKTJTgg.ltrans0.ltrans.o: No such file or directory
> c:/work/tools/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\Rimush\AppData\Local\Temp\ccKTJTgg.ltrans1.ltrans.o: No such file or directory
> c:/work/tools/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\Rimush\AppData\Local\Temp\ccKTJTgg.ltrans2.ltrans.o: No such file or directory
> c:/work/tools/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\Rimush\AppData\Local\Temp\ccKTJTgg.ltrans3.ltrans.o: No such file or directory
> collect2.exe: error: ld returned 1 exit status
> 
> scons: *** [C:\work\test\2\main.exe] Error 1

I checked the folder "C:\Users\Rimush\AppData\Local\Temp\" while Nuitka is running. There are no files "ccKTJTgg.ltrans0.ltrans.o, ccKTJTgg.ltrans1.ltrans.o, ccKTJTgg.ltrans2.ltrans.o, ccKTJTgg.ltrans3.ltrans.o", but there are files "ccKTJTgg.ltrans0.o, ccKTJTgg.ltrans1.o, ccKTJTgg.ltrans2.o, ccKTJTgg.ltrans3.o"

Nuitka version: 1.4.7
Commercial: None
Python: 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Python\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\work\tools\mingw64\bin\gcc.exe (gcc).

**Comment by kayhayen** [comment]
Use the MinGW of Nuitka, it works with LTO. I do not debug random MinGW64 versions.

**Comment by Rimush** [comment]
The same problem when Nutika downloads mingw64

> C:\work\test\2>python -m nuitka --windows-disable-console --follow-imports main.py
> Nuitka-Options:INFO: Used command line options: --windows-disable-console --follow-imports main.py
> Nuitka:INFO: Starting Python compilation with Nuitka '1.4.7' on Python '3.10' commercial grade 'not installed'.
> Nuitka:INFO: Completed Python level compilation and optimization.
> Nuitka:INFO: Generating source code for C backend compiler.
> Nuitka:INFO: Running data composer tool for optimal constant value handling.
> Nuitka:INFO: Running C compilation via Scons.
> Nuitka will use gcc from MinGW64 of winlibs to compile on Windows.
> 
> Is it OK to download and put it in 'C:\Users\Rimush\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3'.
> 
> No installer needed, cached, one time question.
> 
> Proceed and download? [Yes]/No
> y
> Nuitka:INFO: Downloading 'https://github.com/brechtsanders/winlibs_mingw/releases/download/11.3.0-14.0.3-10.0.0-msvcrt-r3/winlibs-x86_64-posix-seh-gcc-11.3.0-llvm-14.0.3-mingw-w64msvcrt-10.0.0-r3.zip'.
> Nuitka:INFO: Extracting to 'C:\Users\Rimush\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe'
> Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
> Nuitka-Scons:INFO: Backend linking program with 6 files (no progress information available).
> c:/users/rimush/appdata/local/nuitka/nuitka/cache/downloads/gcc/x86_64/11.3.0-14.0.3-10.0.0-msvcrt-r3/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\Rimush\AppData\Local\Temp\ccqPpvbh.ltrans0.ltrans.o: No such file or directory
> c:/users/rimush/appdata/local/nuitka/nuitka/cache/downloads/gcc/x86_64/11.3.0-14.0.3-10.0.0-msvcrt-r3/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\Rimush\AppData\Local\Temp\ccqPpvbh.ltrans1.ltrans.o: No such file or directory
> c:/users/rimush/appdata/local/nuitka/nuitka/cache/downloads/gcc/x86_64/11.3.0-14.0.3-10.0.0-msvcrt-r3/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\Rimush\AppData\Local\Temp\ccqPpvbh.ltrans2.ltrans.o: No such file or directory
> c:/users/rimush/appdata/local/nuitka/nuitka/cache/downloads/gcc/x86_64/11.3.0-14.0.3-10.0.0-msvcrt-r3/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\Rimush\AppData\Local\Temp\ccqPpvbh.ltrans3.ltrans.o: No such file or directory
> collect2.exe: error: ld returned 1 exit status
> 
> scons: *** [C:\work\test\2\main.exe] Error 1

**Comment by kayhayen** [comment]
That's pretty bad indeed. I did try updating to winlibs MinGW 12.2 and I recall, once before I had similar reports, and the hope was that they go away with a newer version. Obviously not. Because we are affected by this then: https://sourceware.org/bugzilla/show_bug.cgi?id=30079

**Comment by kamgha** [comment]
> I do not debug random MinGW64 versions.
> I did try updating to winlibs MinGW 12.2 and I recall, once before I had similar reports, and the hope was that they go away with a newer version. Obviously not. 

Building GCC 12.2 + MinGW-w64 against Binutils 2.39 works for me, but brings up the issue mentioned above (or similar) with Binutils 2.40.

**Comment by kayhayen** [comment]
It seems winlibs needs a release and a new build based on that to to be updated, which we are waiting for. Do you know the easiest way to get the binutils version when I have a foreign gcc installation @kamgha ? Also, setting `MAKE` to its prefixed name is a change that for gcc 12 is really useful. I have been waiting to update to 12 with MAKE, so we get parallel LTO linking, which will be huge for compile times.

At this point it seems however unlikely it will come in time for 1.5 release of Nuitka which is immanent.

**Comment by kamgha** [comment]
> the easiest way to get the binutils version when I have a foreign gcc installation

I guess `ld -v` is what you are looking for.

> It seems winlibs needs a release and a new build based on that to to be updated [...]
> At this point it seems however unlikely it will come in time for 1.5 release of Nuitka which is immanent.

There is GCC 12.2 with Binutils 2.39 from "winlibs" here https://github.com/brechtsanders/winlibs_mingw/releases/tag/12.2.0-15.0.6-10.0.0-ucrt-r3 . It may work already.

**Comment by Rimush** [comment]
Unfortunately now I can not check anything, because I had to reinstall Windows. Now there are no problems with Nuitka and it was not possible to find the cause.

**Comment by kayhayen** [comment]
@kamgha I do not use the "urct" versions yet, since I am not yet sure what the implications are for runtime availability. But I tried 12.2.0 with MSVC and it failed to work. 

@Rimush that's good news for you, then I guess I invite you to unsubscribe the bug. Unfortunately, I feel like somebody else will report it again at some point. I will use this to trace when to update MinGW to 12.

**Comment by kayhayen** [comment]
@kamgha mine is indeed 2.38 there, so yes, switching might be an idea, but actually I would prefer to first change gcc version, and then change runtime, or make it an option first.

**Comment by kamgha** [comment]
> I do not use the "urct" versions yet

Right, I prefer MSVCRT as well. At the end of this page is a comparison: https://www.msys2.org/docs/environments/

> I am not yet sure what the implications are for runtime availability.

UCRT would drop Windows 7 RTM. Requirement will be Windows 7 SP1/8/8.1 and this update on top of it: https://support.microsoft.com/en-us/topic/update-for-universal-c-runtime-in-windows-c0514201-7fe6-95a3-b0a5-287930f3560c . It's included in Windows 10 onwards.

> and then change runtime, or make it an option first.

Perhaps this decision can be made upon how CPython is linked against, to avoid pulling in new dependencies.

"winlibs" provides this: https://github.com/brechtsanders/winlibs_mingw/releases/tag/12.2.0-15.0.6-10.0.0-msvcrt-r3 . I just tested this with Nuitka and it works here (GCC 12.2.0 + Binutils 2.39 / MSVCRT).

**Comment by kayhayen** [comment]
I see, since UCRT will be mixing runtime with extension modules of Python necessarily, we may trigger too many issues then or need both, so that is not an option, or is it. At some point I will try it out. Maybe UCRT has some sort of compatibility layer there?

**Comment by kayhayen** [comment]
Not going to happen for even 1.7, delaying it to 1.8

**Comment by kamgha** [comment]
> winlibs needs a release and a new build based on that to to be updated, which we are waiting for. 

winlibs has now a suitable build available: https://github.com/brechtsanders/winlibs_mingw/releases/tag/13.2.0-16.0.6-11.0.1-msvcrt-r1

```
GCC 13.2.0
MinGW-w64 11.0.1 (linked with msvcrt)
GNU Binutils 2.41
```

i686:
https://github.com/brechtsanders/winlibs_mingw/releases/download/13.2.0-16.0.6-11.0.1-msvcrt-r1/winlibs-i686-posix-dwarf-gcc-13.2.0-mingw-w64msvcrt-11.0.1-r1.zip

x86_64:
https://github.com/brechtsanders/winlibs_mingw/releases/download/13.2.0-16.0.6-11.0.1-msvcrt-r1/winlibs-x86_64-posix-seh-gcc-13.2.0-mingw-w64msvcrt-11.0.1-r1.zip

**Comment by kayhayen** [comment]
Ok, I will try and update it for 1.9 like one of the first things.

**Comment by kayhayen** [comment]
So, current factory has this, seems good. Should also make LTO faster with Nuitka there.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
The update to gcc 13 is on develop, however it seems LTO and 32 bits are currently at least giving stray error messages, that I have no explanation for, and might lead to me to disabling it for that setup.

**Comment by kayhayen** [comment]
Part of the 1.9 release I just made.
