### ISSUE TITLE
No data files in directory

### ISSUE THREAD

**Issue by TheHellTower** [Nuitka/Nuitka#2073]
Before submitting an Issue, please review the [Issue Guidelines](https://github.com/Nuitka/Nuitka/blob/develop/CONTRIBUTING.md#submitting-an-issue). (this got removed ?)

  > python -m nuitka --version:
```
1.4.7
Commercial: None
Python: 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Program Files\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).
```

* How did you install Nuitka and Python
Using `py -m pip install nuitka` and I installed `zstandard` and `ordered-set` and for Python I fully installed it with the installer by checking for all users checkbox without any virtualenv.

* The specific PyPI names and versions
- pygame 2.1.3
- authgg 0.9
- numpy 1.24.2
- selenium-wire 5.1.0
- colorama 0.4.6
- psutil 5.9.4

It is not related to a error in building but it doesn't find some folders I point out:
Example to point out this data folder: `%temp%\random\pycryptography39` I do: `--include-data-dir="*fullPath*\random\pycryptography39=pycryptography39"` 
But I get:
```
Nuitka-Options:WARNING: No data files in directory
Nuitka-Options:WARNING: '*fullPath*\random\pycryptography39.'
```
 

* Provide in your issue the Nuitka options used

**All options are working except when I want to include a data dir**

Command: `py -m nuitka --standalone --onefile --output-dir="helper.executable" --include-data-file="*fullPath*\random\pycryptography39=pycryptography39" --include-package=selenium --include-package=seleniumwire "*fullPath*\random\helper.py"`

**Comment by TheHellTower** [comment]
Note: I seen it was working in the `0.8.3` of nuitka but not in the last version

**Comment by kayhayen** [comment]
The data files options of Nuitka do not include code anymore. Use the yaml configuration as described here: https://nuitka.net/doc/nuitka-package-config.html

**Comment by novakdwy** [comment]
glad to see you use ares ;)

>
