### ISSUE TITLE
What to do when my program has a virus false report?

### ISSUE THREAD

**Issue by dlsofree** [Nuitka/Nuitka#2081]
1.4.8
Commercial: None
Python: 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\nguye\AppData\Local\Programs\Python\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).
I just built the helloworld program and it also reported 13 viruses, before using 1.2.7 there were 0 viruses, where is the reason for it?
![image](https://user-images.githubusercontent.com/126412418/221426966-6e1169ae-2215-4018-8a5d-130f2d9c0004.png)

**Comment by kayhayen** [comment]
In Nuitka commercial there is a bunch of hints for how to use Nuitka properly, such that this doesn't happen. I do not really believe that it's dependent on the Nuitka version. Unfortunately for Nuitka, it is being used by malware authors just as much as by legit people, maybe more. The used algorithms may lump you in there. I feel I will add a section under "problems" in the User Manual about this. If you want and need 0 detections, I recommend becoming a subscriber.

I so far do not feel like advertising with this, but I think I need to start doing it. It's a major point.

https://nuitka.net/doc/commercial.html

**Comment by kayhayen** [comment]
You would know how to avoid it from happening, yes, that's mainly a question of knowledge. I added the section to the User Manual, and I think I will have to add a section about this to the commercial page I pointed you to as well. 

Obviously, however, I cannot guarantee that e.g. an actual malware will not be reported.

**Comment by kayhayen** [comment]
I have added the pointer to the User Manual and took note to add the section for the page, which will be a focus next month anyway.

**Comment by chiron853** [comment]
pay to make it fud? worst thing ever so this new version of nuitka or zstandard caused this thing to happen time to install old versions and see again

**Comment by dlsofree** [comment]
> 

using nuitka 1.2.7

**Comment by chiron853** [comment]
installed old version of nuitka disabled ccache and zstandard and i also tried hello print and now i got 25 detections?????

**Comment by kayhayen** [comment]
Guys, I do not need you to report the state of non-working things, so please stop it. I made it clear that naive approaches are not going to achieve your goal.
