### ISSUE TITLE
MSYS2: Nuitka --onefile build failed to start on Windows

### ISSUE THREAD

**Issue by caricardo** [Nuitka/Nuitka#2084]
```console
$ python -m nuitka --version
1.4.8
Commercial: None
Python: 3.10.8 (main, Oct 15 2022, 19:00:40)  [GCC 12.2.0 64 bit (AMD64)]
Flavor: MSYS2 MinGW
Executable: C:/msys64/mingw64/bin/python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:/msys64/mingw64/bin/gcc.exe (gcc).
```

main_gi.py:
```python
import gi
gi.require_version("Gtk", "4.0")
from gi.repository import Gtk

if __name__ == "__main__":
	print(f"GTK version: {Gtk.MAJOR_VERSION}.{Gtk.MINOR_VERSION}.{Gtk.MICRO_VERSION}")
```

main_numpy.py:
```python
import numpy

if __name__ == "__main__":
	print(f"{numpy.__version__}")
```

Nuitka compilation commands:
```console
$ python -m nuitka --onefile --low-memory ./main_numpy.py
$ python -m nuitka --onefile ./main_gi.py
$ python -m nuitka --mingw64 --onefile --onefile-tempdir-spec=%TEMP%\\onefile_%PID%_%TIME% ./main_gi.py
```

It still build right, but when I try to execute, the following error happens:
```console
$ ./main_numpy.exe
Error, failed to open 'C:\msys64\tmp\/onefile_6540_133220462827603521\numpy/core/_multiarray_tests.pyd' for writing.

$ ./main_gi.exe
Error, failed to open 'C:\msys64\tmp\/onefile_13336_133220462952782886\gi/_gi.pyd' for writing.
```

Also using cmd as administrator:
```cmd
C:\msys64\home\user\nuitka_err>main_gi.exe
Error, failed to open 'C:\Users\user\AppData\Local\Temp\/onefile_8404_133220685428551434\gi/_gi.pyd' for writing.

C:\msys64\home\user\nuitka_err>main_numpy.exe
Error, failed to open 'C:\Users\user\AppData\Local\Temp\/onefile_10640_133220685499872646\numpy/core/_multiarray_tests.pyd' for writing.
```

The main*.exe inside main*.dist still works normaly, so probably it's a --onefile error.
```console
$ python ./main_numpy.py
1.24.2

$ python ./main_gi.py
GTK version: 4.8.2

$ ./main_numpy.dist/main_numpy.exe
1.24.2

$ ./main_gi.dist/main_gi.exe
GTK version: 4.8.2
```

Module folders in the dir with unpacked temporary files not exist.
```console
$ diff -qr ./main_gi.dist /tmp/onefile_13336_133220462952782886
Only in ./main_gi.dist: gi
Only in ./main_gi.dist: girepository

$ diff -qr ./main_numpy.dist /tmp/onefile_8276_133220695812006992
Only in ./main_numpy.dist: numpy
```

Maybe it's trying to store file before creating a folder?

**Comment by kayhayen** [comment]
It seems suspicious that the slashes are not the correct ones. I am assuming this is a MSYS2 MinGW specific issue.

**Comment by kayhayen** [comment]
This could would be vulnerable I guess to nested directories:

```
    while (*w) {
        if (*w == FILENAME_SEP_CHAR) {
            *w = 0;

            createDirectory(dir_path);

            *w = FILENAME_SEP_CHAR;
        }

        w++;
    }
```

With Win32 defined, I am assuming that checks for `\` precisely and nothing else, which is fair, because we control how the archive filenames are stored.

**Comment by kayhayen** [comment]
Maybe it was using a different Python for onefile compression, that has a different setting. It would say that in your compilation at some point I think. But if e.g. the Posix Python was found, this one would create the `/`.

The solution is probably to pass the platform slash value to the external compressor Python as well. Also the compressor Python actually used is probably something to put into the compilation report, so I could tell it from that and know, but I have a strong suspect that you must be somewhat special there.

**Comment by caricardo** [comment]
The error was caused by MSYS2 subsystem([issue 1591](https://github.com/msys2/MSYS2-packages/issues/1591)  and [issue 2638](https://github.com/conan-io/conan/issues/2638)).
Fixed with https://github.com/msys2/MSYS2-packages/issues/1591#issuecomment-573336696
```console
$ MSYSTEM= python -m nuitka --onefile --low-memory ./main_numpy.py
$ ./main_numpy.exe
1.24.2
```

Thanks for your support. Maybe user should be warned if environment variable "MSYSTEM" is set(on MSYS2 MinGW64) and make Nuitka clear it while building?

**Comment by kayhayen** [comment]
Ah, I see, I think though, that my hypothetical issue, namely switching between different variants, also merrited a solution, so the code added for that will make it just work.

```
                # Might be changing from POSIX to Win32 Python on Windows.
                if win_path_sep:
                    filename_relative = filename_relative.replace("/", "\\")
                else:
                    filename_relative = filename_relative.replace("\\", "/")
```

This should make it work even with the bug you mentioned.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by caricardo** [comment]
I installed factory branch, but nothing changed:
```console
$ git clone --branch factory https://github.com/Nuitka/Nuitka.git
$ pip install -e ./Nuitka/
$ python -m nuitka --version
1.5rc12
Commercial: None
Python: 3.10.10 (main, Feb 10 2023, 19:20:41)  [GCC 12.2.0 64 bit (AMD64)]
Flavor: MSYS2 MinGW
Executable: C:/msys64/mingw64/bin/python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:/msys64/mingw64/bin/gcc.exe (gcc).

$ python -m nuitka --onefile --low-memory ./main_gi.py
Nuitka-Options:INFO: Used command line options: --onefile --low-memory ./main_gi.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.5rc12' on Python '3.10' commercial grade 'not installed'.
...

$ ./main_gi.exe
Error, failed to open 'C:\msys64\tmp\/onefile_14168_133222574992245016\gi/_gi.pyd' for writing.

$ MSYSTEM= python -m nuitka --onefile --low-memory ./main_gi.py
Nuitka-Options:INFO: Used command line options: --onefile --low-memory ./main_gi.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.5rc12' on Python '3.10' commercial grade 'not installed'.
...

$ ./main_gi.exe
GTK version: 4.8.3
```

**Comment by kayhayen** [comment]
Are you saying there is a MinGW Python where `os.path.sep == "\\"` is not True?

**Comment by kayhayen** [comment]
That is insanity, esp. since I frequently encounter programs that do not allow `/` but of course, I can change the criterion to `isWin32OrPosixWindows`. I would be thinking the whole point of the MinGW variant is to be Win32, and not POSIX, but who am I, what invariant will not be broken by people wiser than me?

**Comment by caricardo** [comment]
> Are you saying there is a MinGW Python where `os.path.sep == "\\"` is not True?

Yes, behavior described in [issue 1591](https://github.com/msys2/MSYS2-packages/issues/1591).
Python from "mingw-w64-x86_64-python" makes choice of path separator based on "MSYSTEM" environment variable(https://github.com/msys2/MSYS2-packages/issues/1591#issuecomment-573362848).
```console
$ pacman -R python && pacman -S mingw-w64-x86_64-python
$ echo $MSYSTEM
MINGW64

$ python
Python 3.10.10 (main, Feb 10 2023, 19:20:41)  [GCC 12.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.path.sep
'/'
>>> exit()

$ MSYSTEM= python
Python 3.10.10 (main, Feb 10 2023, 19:20:41)  [GCC 12.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.path.sep
'\\'
>>>
```

**Comment by kayhayen** [comment]
I updated factory with just checking if it's on Windows. Should work now.

**Comment by kayhayen** [comment]
This is part of the 1.5.3 release.
