### ISSUE TITLE
Support bundling Python files as data files / source code

### ISSUE THREAD

**Issue by tbabej** [Nuitka/Nuitka#2088]
The newest releases of Nuitka (1.4 and above) do not allow bundling files with `*.py` extension via `--include-data-dir` option. While this is a niche use case, there are legitimate cases where one might want to do so (instead of compiling the file). In my case I am bundling a plugin for an external tool, which also happens to be Python-based.

Invoking nuitka in the following manner will produce a helpful warning showcasing that the directory did not bundle anything:
```
$ python3.10 -m nuitka --include-data-dir=ansible-runner-callback-dir=ansible_runner/display_callback/callback '--noinclude-data-files=*.pyc' pqrs/cli.py
[...]
Nuitka-Options:WARNING: No data files in directory 'ansible-runner-callback-dir.'
```

where the referenced directory in fact contains two Python files:
```
$ ls ansible-runner-callback-dir
__init__.py
awx_display.py
```

This differs from behaviour of Nuitka below 1.4 (i.e. Nuitka 1.3.8 will happily include a data dir with `*.py` files). 

Specs below:
> 1.4.8
> Commercial: None
> Python: 3.10.9 (main, Dec 20 2022, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]
> Flavor: Fedora Python
> Executable: /home/tbabej/.cache/pypoetry/virtualenvs/pqrs-wpOT8-yL-py3.10/bin/python
> OS: Linux
> Arch: x86_64
> Distribution: Fedora 37
> Version C compiler: /usr/bin/gcc (gcc).

**Comment by bersbersbers** [comment]
Interesting. I use that exact functionality successfully in the newest release candidate, see https://github.com/Nuitka/Nuitka/issues/2086. While that issue has a different focus, bundling `include-data-file=test_bug.py=./` works fine, and I seem to remember that `include-data-file=*.py=./` worked the same way. Maybe try the latest rc using
```
pip install git+https://github.com/Nuitka/Nuitka
```

**Comment by kayhayen** [comment]
I think, that for including code, data files options are the wrong thing. I do consider these workarounds bugs. Often you might want to have them compiled, and only where that is not the case, it should be done. We should add a new option for that.

Almost as if I was Tesla I removed a feature before adding support for the new one. This was mostly aimed at not including extension modules or DLLs with data file options.

I would welcome a suggestion how to specify Python files for source code inclusions. Like `--include-source-code-files=source_dir/*=target_dir` and `--include-package-source=some.name`. But this will be subject to problems. Right now Nuitka cannot load source files in all cases. And we might want to do bytecode rather than source code too.

So far I have not had much commercial interest in providing stuff as source code. And I am not too keen of having an added complexity in the mixing of source and extension modules, and compile code, and what's working there and what is not.

**Comment by kayhayen** [comment]
If you write a Nuitka plugin, it can do whatever the heck it wants to do btw, so technically it will be possible. You just overload it and have to do the file locating and scanning for source yourself. The data file helpers are all supposed to disallow it.

**Comment by kayhayen** [comment]
Nuitkas has users of varying skill level. Giving them "responsibility" is for the majority to set them up for failure. Therefore a simple solution doesn't cut it in my mind. Nuitka should simply just work. Having 3 sets of options, one related to DLLs, one related to source code, and to data files is the better long term plan in my mind.

I e.g. plan that standalone will soon by default refuse to import anything it didn't know of at the time of compilation.

Simple solutions make things too hard in my mind.

**Comment by hanshantong** [comment]
> I think, that for including code, data files options are the wrong thing. I do consider these workarounds bugs. Often you might want to have them compiled, and only where that is not the case, it should be done. We should add a new option for that.
> 
> Almost as if I was Tesla I removed a feature before adding support for the new one. This was mostly aimed at not including extension modules or DLLs with data file options.
> 
> I would welcome a suggestion how to specify Python files for source code inclusions. Like `--include-source-code-files=source_dir/*=target_dir` and `--include-package-source=some.name`. But this will be subject to problems. Right now Nuitka cannot load source files in all cases. And we might want to do bytecode rather than source code too.
> 
> So far I have not had much commercial interest in providing stuff as source code. And I am not too keen of having an added complexity in the mixing of source and extension modules, and compile code, and what's working there and what is not.

How does nuitka copy multiple types of data files using the argument '--include-data-files' if the data files are in different source directories?

**Comment by kayhayen** [comment]
You can specify the argument any amount of time you want @hanshantong and limit by file type for each indidivual usage. Just beware, that it may not obey the `*.py` if given right now.

**Comment by hanshantong** [comment]
> You can specify the argument any amount of time you want @hanshantong and limit by file type for each indidivual usage. Just beware, that it may not obey the `*.py` if given right now.

Got it, thanks, kayhayen. I run "python -m nuitka --version" just now, then an AttributeError was shot:
```python
1.6rc4
Commercial: None
Python: 3.8.16 (default, Jan 17 2023, 22:25:28) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Anaconda3\envs\package6.4.2\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
AttributeError: 'tuple' object has no attribute 'append':
  File "C:\ANACON~1\envs\my_env_name\lib\site-packages\nuitka\build\CCompilerVersion.scons", line 253:
    reportCCompiler(env, "Version", my_print)
  File "C:\Anaconda3\envs\my_env_name\lib\site-packages\nuitka\build\SconsCompilerSettings.py", line 880:
    % (context, getReportPath(env.the_compiler), cc_output)
  File "C:\Anaconda3\envs\my_env_name\lib\site-packages\nuitka\utils\FileOperations.py", line 1016:
    prefixes.append(

```

**Comment by kayhayen** [comment]
@hanshantong that version problem is indeed fixed on factory now

**Comment by kayhayen** [comment]
If the suffix is specified as `*.py` it does it for a while already. See e.g. this Yaml configuration of ours:

```
- module-name: 'pysnmp.smi'
  data-files:
    patterns:
      - 'mibs/**/*.py'
```

It has to be very precise about that, docs should eventually maybe point that out, but I believe it should be absolutely the exception, and Nuitka should support including code as python source files and reading them at run time itself properly, for all things to work. Mixing code bugs still apply, so this will only work for code that is not inside a compiled package at all, i.e. where there is a `__init__.py` in compiled form too.

**Comment by Rayterex** [comment]
I have similar issue. I wrap inside executable two directories that contain python scripts for Blender and python scripts for Autodesk Maya using ```--include-data-dir``` but non of those python files are inside executable when I use never versions of Nuitka. Did You figure out what is the best workaround?

**Comment by KevinRodriguez777** [comment]
> I have similar issue. I wrap inside executable two directories that contain python scripts for Blender and python scripts for Autodesk Maya using `--include-data-dir` but non of those python files are inside executable when I use never versions of Nuitka. Did You figure out what is the best workaround?

Hello, can you please open a new issue with your own minimal working example so that we can take a look? thank you.
