### ISSUE TITLE
nuitka is detected as PUA.Python.Nuitka/Trojan.Nuitka.Script.24 in virustotal even if py file is fud

### ISSUE THREAD

**Issue by chiron853** [Nuitka/Nuitka#2093]
i used nuitka 1.4.8 including 1.2.7 but i got 12 detections in virustotal on every version of nuitka other modules for nuitka are ccache 4.7.4  zstandard 1.5.4 and i used py -m nuitka --onefile --windows-icon-from-ico=  main.py command with python 3.10.10

**Comment by kayhayen** [comment]
This is a duplicate, if you do things correctly, it will work. The information how to do it, is behind the Nuitka commercial paywall though. If you want, you can get in touch with virus vendors and have them explain to you what your options are as well.

**Comment by chiron853** [comment]
but i didnt use no console command so how does it get more detections than pyinstaller
