### ISSUE TITLE
Cannot compile `(lambda: None)()` due to `'impl___main__$$$function__1_lambda': identifier not found`

### ISSUE THREAD

**Issue by bersbersbers** [Nuitka/Nuitka#2094]
```
>nuitka --version
1.5rc12
Commercial: None
Python: 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]  
Flavor: Unknown
Executable: C:\Users\bers\.pyenv-win-venv\envs\project_3.11\Scripts\python.exe       
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\cl.exe (cl 14.3).

>more bug2.py
(lambda: None)()

>nuitka --quiet bug2.py 
Nuitka:WARNING: The Python version '3.11' is not officially supported by Nuitka '1.5rc12',Nuitka:WARNING: but an upcoming release will change that. In the mean time use Python     
Nuitka:WARNING: version '3.10' instead or newer Nuitka.
Nuitka-Options:WARNING: You did not specify to follow or include anything but main        
Nuitka-Options:WARNING: program. Check options and make sure that is intended.
Unexpected output from this command:
<clcache> /Fomodule.__main__.obj /c "module.__main__.cpp" /TP /nologo /GL /Ox /GF /Gy /EHsc /J /Gd /bigobj /MT /D__NUITKA_NO_ASSERT__ /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=0 /D_NUITKA_EXE /IC:\Users\bers\.pyenv\pyenv-win\versions\3.11.2\include /I. /IC:\Users\bers\PYENV-~1\envs\PROJEC~1.11\Lib\SITE-P~1\nuitka\build\include /IC:\Users\bers\PYENV-~1\envs\PROJEC~1.11\Lib\SITE-P~1\nuitka\build\static_src
module.__main__.cpp(519): error C3861: 'impl___main__$$$function__1_lambda': identifier not found
scons: *** [module.__main__.obj] Error 2

```

**Comment by bersbersbers** [comment]
(Note that `python -c "(lambda: None)()"` is perfectly valid.)

**Comment by kayhayen** [comment]
You are correct. This is probably due to verbose output `Replaced call to created function body '<lambda>' with direct function call. ` but somehow it is no longer inlined as it should be.

**Comment by kayhayen** [comment]
Ah, well, that of is not really why, but of course would have hidden the bug too.

What is really going on, is that at some point, code generation started to optimize for constant return functions, to not have any code. Of course in case of direct call, there still needs to be something that gives the value. These functions should have to be inlined with absolute certainty. I think we do not inline anymore, because we had trouble with handling all cases where e.g. keyword arguments can be used to reorder, etc. and this therefore has not been addressed yet, in a way that it was enabled.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
The inlining of functions calls is actually something not too far off and might be a worthwhile goal for a coming release.

**Comment by bersbersbers** [comment]
Thanks, factory works :)

**Comment by kayhayen** [comment]
I have a suspect how you encountered the bug from the other issue.

**Comment by bersbersbers** [comment]
Yes, I encountered this while debugging #2086. I would ever *intend* to write `(lambda: None)()`, I hope :)

**Comment by kayhayen** [comment]
It could also come from say `os.path.sep == "/"` compile time optimization, but it's equally useless. And it could come from function inlining of Nuitka, but as discussed, this is unfortunately disabled, but I think I decided to give it a try at re-enabling it, by giving `return` only functions of low complexity a shot. With the recent children node generation, I feel like getting the cost of said `return` statements somewhat accurately, should be doable in an efficient way even. Surely going to make at least experimental code for that.

It would be bug hiding for the above case, and also I had this "infinite" speed up years ago, and it's a shame it got lost. The calls indeed cannot all the resolved, but those which are, can of course be inlined. My fix can be removed again, once we can inline all constant only returning functions, and once we properly track if a function is inlined and called both. That is I think a technical debt we have there in function generation, that right now it's either direct call or through function object, but never both.

For complex helper calls, classes, etc. face the same issue. They are shared between all uses. Some when inlined will be optimized away entirely for some forms of argument, and even allow better optimization in this case. That's really the next scalability stuff.

**Comment by kayhayen** [comment]
This is part of the stable release 1.5 that I just made.
