### ISSUE TITLE
Compile `torch` library to .so

### ISSUE THREAD

**Issue by Osbornnnnn** [Nuitka/Nuitka#2095]
How i can compile pytorch to .so library for using in C/Go

**Comment by kayhayen** [comment]
Nuitka commercial plans to, but does not yet support compilation to DLLs. I do not intend to make this supported. Nuitka and Python code can both be used by embedding a Python interpreter that executes extension modules or source code loaded into it.

Get the embedding of standard Python to work, then can if you want, compile the Python code into an extension module for importing.

If you use standalone mode, you might be able to embedd the Go or C code into it with whatever techniues you choose as well.

**Comment by kayhayen** [comment]
The DLL support I am talking about is a convience feature mostly, when said DLL takes on the hard work of embedding.
