### ISSUE TITLE
ModuleNotFoundError: No module named 'treelib'

### ISSUE THREAD

**Issue by hanshantong** [Nuitka/Nuitka#2098]
1. the version of treelib I used: 1.6.1

2. the nuikta's information is listed below:
1.1
Commercial: None
Python: 3.8.16 (default, Jan 17 2023, 22:25:28) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Anaconda3\envs\package6.4.2\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

3. the version of python:
4.

**Comment by kayhayen** [comment]
@hanshantong please follow the instructions and use latest Nuitka and provide a minimal example code the next time you report.
