### ISSUE TITLE
Problem starting a file in ubuntu 20.04

### ISSUE THREAD

**Issue by ptfu0** [Nuitka/Nuitka#2102]
Hello? Why in ubuntu 20.04 in nautilus (standard file manager) can not run a bin file, displays a list of programs through which to open the file (chmod +x of course on the file is executed). From the terminal this file runs without problems. On ubuntu 22.04 there is no such problem. Who knows how to solve the problem? 
python3 -m nuitka --version
1.4.8
Commercial: None
Python: 3.8.10 (default, Nov 14 2022, 12:59:47) 
Flavor: Debian Python
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 20.04.5
Version C compiler: /usr/bin/gcc (gcc).

**Comment by kayhayen** [comment]
This is out of scope for Nuitka, please ask Ubuntu. Generally we should have a feature to create desktop files, then this won't be important at all, but we don't have that at this time. Contributions for a desktop file generator would be very welcome.
