### ISSUE TITLE
Nuitka and xonsh

### ISSUE THREAD

**Issue by anki-code** [Nuitka/Nuitka#2105]
Hello @kayhayen !
I've read your post about leaving the old work! Congratulations!

I just want to let you know that I'm personally interested in using Nuitka for compilation [xonsh](https://xon.sh/) binaries.

If you will have some time to review the xonsh code and have a write the draft of steps that could be increase xonsh performance (speed) by compilation with Nuitka I will invest into development this.

I'm not the xonsh founder I'm just inspired by xonsh and I see the potential in Nuitka to make xonsh faster.

My first try to make simple xonsh binary with Nuitka was here - [xonsh-binary](https://github.com/anki-code/xonsh-binary/blob/617d29bb41da42cf80d3eefcc97beeaecc9fa9ac/xonsh-python-glibc-binary.Dockerfile).

Thanks!

**Comment by kayhayen** [comment]
Feel free to read the docs and make issue reports if things are not working as expected.
