### ISSUE TITLE
--onefile app icon is not working

### ISSUE THREAD

**Issue by jaskaur18** [Nuitka/Nuitka#2107]
I was trying to build for Mac with onefile option but icon --macos-app-icon doesn't show on the build. it works perfectly without --onefile option  but when I put --onefile it shows black no icon and doesn't include any resources in .app file

tried with the latest stable version and factory also same issue

<img width="118" alt="image" src="https://user-images.githubusercontent.com/51957556/224795957-2c0df026-43f2-4695-a2b4-16ec966cdafc.png">

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.
