### ISSUE TITLE
Make it more clear that Nuitka is written in Python itself

### ISSUE THREAD

**Issue by pfalcon** [Nuitka/Nuitka#211]
I know about Nuitka for at least 3 years. One of these wonderful Xmas days I woke up with a thought "How I'm tired of all those stupid Python compilers written in awful languages! We need cute Python compilers written in Python! (And less bloated than PyPy.)"

3 days later, SUDDENLY, Nuitka is written in Python. I don't know why I thought Nuitka is written in C/C++. Possible reasons:

1. Because I'm stupid?
2. Because majority of software in this world is written in C/C++?
3. Because CPython is written in C?
4. Because Nuitka generates C?
5. Your choice?

Can you please help stupid people like me? http://nuitka.net/pages/overview.html should start with "Nuitka is a Python compiler written in Python." Actually, I'd suggest to never mention "Python compiler" and always "Python compiler written in Python". When you hear "Python compiler", you imagine C, `#ifdef WINDOWS`, piles and piles of low-level code, awfulness and ugliness. When you hear "Python compiler written in Python", you imagine almost zero cost of starting up, immediate hackability, ease of introspection and experimentation - all hopefully trickling into possibility to contribute back.

**Comment by pfalcon** [comment]
Oh, and project description here on github of "Nuitka as from http://nuitka.net" doesn't help to catch people's attention.

**Comment by kayhayen** [comment]
As a first measure, I updated i along the lines of the TL/DR of the http://nuitka.net/pages/overview.html page. Also for the website link, there is a field for that already.

I guess, this is from when I was lazily just proving a clone of what I thought of ought to mainly reside on Nuitka home page. However, issue tracking and code is here now, even factory branch is always in sync, so that has no place anymore.

**Comment by kayhayen** [comment]
Also what is done, is compiling the web site from different sources. One would be e.g. the `README.txt` and `Developer_Manual.rst` from Nuitka repo itself.

**Comment by kayhayen** [comment]
Also to answer your question. You are not stupid. I am just limited in my abilities of expression. And the solution is to make it easier for others to join me in that endeavor.

**Comment by kayhayen** [comment]
For reference, I attempted a Wiki for Nuitka a while ago, that one was a catastrophic failure. Nobody cares about that.

**Comment by kayhayen** [comment]
@pfalcon That is very motivating issue, very constructive of you to share your realization with me.

**Comment by kayhayen** [comment]
So as a first step I removed the use of `nuitka-factory` and `nuitka-master` submodules from the "nikola-site" repo of mine, using `curl` to download the needed files on demand only.

Getting rid of these submodules means that the repo will be easier to work with. Having submodules is not good, as they are tedious to update outside of scripting, and esp. factory commits tends to become unreachable.

Next step ought to be to separate the "blog" and the informational web site part even visually, with a proper landing page in the index that cites the blog posts by title or something, but gives more of landing page feel, so then `nuitka.net/blog` could become what the current landing page is. And then to maybe move the private parts of my blog out of there, into a space maintained separately. The landing page ought to offer pages for typical audiences, like the ones I listed above.

Also currently "output" is a git repo with a submodule. I might want to truncate that one, but I sure do like to see actual changes there, so mistakes can be explained.

**Comment by kayhayen** [comment]
Ok, I am closing it, and will track my making available `nuitka-website` repo separately.

**Comment by pfalcon** [comment]
@kayhayen: Sorry to bother again, but maybe you can consider adding tags to the project here on github. At least please consider adding "python-compiler", it's a lonely place now: https://github.com/topics/python-compiler

**Comment by kayhayen** [comment]
Hello Paul,

after a couple of failed attempts, I finally found where to do it. Can you
check which ones you feel are missing or wrong?

Thanks,
Kay

Am Mi., 9. Jan. 2019 um 00:06 Uhr schrieb Paul Sokolovsky <
notifications@github.com>:

**Comment by pfalcon** [comment]
@kayhayen: Looks great, thanks for response and doing it! Having "nuitka" tag is useful - hope it'll be getting more entries over time!
