### ISSUE TITLE
Nuitka:WARNING: The Python version '3.11' is not officially supported by Nuitka '1.5.1'

### ISSUE THREAD

**Issue by pauljurczak** [Nuitka/Nuitka#2110]
This warning appears when building with Nuitka 1.5.1:
```
Nuitka:WARNING: The Python version '3.11' is not officially supported by Nuitka '1.5.1'
```
contrary to listing on PyPI, which shows Python 3.11 support.

**Comment by kayhayen** [comment]
It's in the middle of things. I call it experimental support. I will change the wording to reflect that to "only experimentally supported".

**Comment by kayhayen** [comment]
This will go to the hotfix 1.5.2, in 1.6 the message will likely be gone. I am closing this early for lack of general relevance.
