### ISSUE TITLE
ImportError: `libpyside6.abi3.so.6.4`: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by bersbersbers** [Nuitka/Nuitka#2114]
`bug2.py`
```python
# python -m pip install nuitka PySide6-Essentials
# python -m nuitka bug2.py
# bug2.dist/bug2.bin

# nuitka-project: --quiet
# nuitka-project: --standalone
# nuitka-project: --static-libpython=no
# nuitka-project: --enable-plugin=pyside6

from PySide6.QtCore import QCoreApplication

application = QCoreApplication()
print("Done.")
```

Output:
> ImportError: libpyside6.abi3.so.6.4: cannot open shared object file: No such file or directory

**Comment by bersbersbers** [comment]
Similarly, my executables have stopped working on Windows, so I doubt this is a system configuration error. Executables terminate without error message, which I why I went for Linux to grab more meaningful outputs.

**Comment by bersbersbers** [comment]
I can repro this with v1.5.1 but not v1.5 from PyPI. Looking at https://github.com/Nuitka/Nuitka/compare/1.5...1.5.1, is it https://github.com/Nuitka/Nuitka/commit/a899b82df3dfa28ca0835961aa5bce6298ff40f5?

**Comment by bersbersbers** [comment]
Interestingly, the two binaries (working and non-working ones) have exactly the same size:
```
-rwxrwxrwx 1 bers bers 8533600 Mar 15 16:57 bug2.dist/bug2.bin*
-rwxrwxrwx 1 bers bers 8533600 Mar 15 17:00 bug2.dist/bug2.bin*
```

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
