### ISSUE TITLE
MessageBox problems

### ISSUE THREAD

**Issue by Monday-Leo** [Nuitka/Nuitka#2117]
My code are as follows:

`win32api.MessageBox(0, "Hello", "test",win32con.MB_OK)`

I use win10 to pack as exe. My command is:

`nuitka --standalone --show-memory  --show-progress --output-dir=o --onefile  test.py`

It works on my computer. But when I send it to window 2012server, it doesn't work. MessageBox donesn't appear!
How to solve it?
![1)4OIRQ_E%NK)I({V@ WEST](https://user-images.githubusercontent.com/53975909/225538286-14b7f6e3-d126-41d6-b5da-2c071ddbbbaf.png)

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
