### ISSUE TITLE
SystemError: null argument to internal routine

### ISSUE THREAD

**Issue by MomentQYC** [Nuitka/Nuitka#2118]
Environment and pypi package versions
```shell
1.5.1
Commercial: None
Python: 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Program Files\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).
pygame 2.3.0 (SDL 2.24.2, Python 3.10.5)
```

When I compile a program with PyInstaller and Nuitka's default options, it runs perfectly fine.But when I use the `--onefile` and/or `--standalone` options, it gives me `SystemError: null argument to internal routine` error at runtime.
This is the code that is causing the problem.

```python
import os
os.environ["PYGAME_HIDE_SUPPORT_PROMPT"]=""
import sys
import pygame
import time
import ctypes

pygame.init()
info = pygame.display.Info()
window_size = (info.current_w, info.current_h)
screen = pygame.display.set_mode((0,0), pygame.FULLSCREEN, pygame.NOFRAME, pygame.SWSURFACE)
pygame.display.set_caption("")

hwnd = pygame.display.get_wm_info()["window"]
ctypes.windll.user32.SetForegroundWindow(hwnd)
ctypes.windll.user32.SetWindowPos(hwnd, -1, 0, 0, 0, 0, 0x0003)
ctypes.windll.user32.SetWindowLongW(hwnd, -20, ctypes.windll.user32.GetWindowLongW(hwnd, -20) | 0x80)

font = pygame.font.SysFont('SimHei', 50)

color = (255, 255, 255)
alpha = 0

text_list = ["Text 1", "Text 2", "Text 3", "Text 4"]
current_text_index = 0

fade_in_time = 1
fade_out_time = 1
show_time = 5
start_time = time.time()
clock = pygame.time.Clock()
FPS = 60
game_running = True
num = 0

while True:
    if  text_list[current_text_index] == text_list[(len(text_list)-1)]:
        num += 1
        if num == FPS*(show_time-fade_in_time-fade_out_time):
            game_running = False
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pass

    current_time = time.time()
    elapsed_time = current_time - start_time

    if elapsed_time >= show_time:
        current_text_index += 1
        if current_text_index >= len(text_list):
            current_text_index = 0
        start_time = time.time()

    if elapsed_time < fade_in_time:
        alpha = int(255 * (elapsed_time / fade_in_time))
    elif elapsed_time > (show_time - fade_out_time) and game_running == True:
        alpha = int(255 * ((show_time - elapsed_time) / fade_out_time))
    else:
        alpha = 255

    screen.fill((0, 0, 0))

    text_surface = font.render(text_list[current_text_index], True, color)
    text_surface.set_alpha(alpha)
    screen.blit(text_surface, ((window_size[0]-text_surface.get_width())/2, (window_size[1]-text_surface.get_height())/2))

    if game_running:
        pygame.display.flip()

        clock.tick_busy_loop(FPS)
    else:
        if event.type == pygame.KEYDOWN:
            break
pygame.quit()
sys.exit()
```

It seems that whenever there are two options mentioned above, this error appears and then crashes.

**Comment by kayhayen** [comment]
This is an embarrassing 1.5 regression. It seems related to your `PATH` value most likely having non-ASCII values.

I added a backup/restore for `PATH` during Python init, to make sure it doesn't pick up stuff from there, but when `os.environ` was going to be repaired (it picks up false value then), it crashes. None of your code is even close to running there. It seems Python3.10 and Windows are affected.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by MomentQYC** [comment]
> Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

Thank you very much, so far running without any problems!

**Comment by siben168** [comment]
I have the same issue after upgraded to 1.5.1, I've tried factory version with no luck to install this version corrected, is it possible to  down grade to stable version to get things work anyway?

**Comment by kayhayen** [comment]
The 1.4.8 doesn't have this issue. I am hoping that 1.5.3 will be out soon and not have it either.

**Comment by kayhayen** [comment]
The hotfix 1.5.3 should soon hit PyPI and solved this.
