### ISSUE TITLE
Can I run Nuitka from outside of the virtualenv to compile code inside the virtualenv?

### ISSUE THREAD

**Issue by burnhardo** [Nuitka/Nuitka#2119]
Hi there,

what is the correct way or is there a better way to include the virtualenv like i does.

To include my virtualenv i extend PYTHONPATH with the site-packages path from my virtualenv directory on runtime. Is there a better way or a automatic way that nuitka recognize it? My nuitka Installation is outside this virtualenv i must say.

thanks and great work with nuitka! Thanks for that.

**Comment by kayhayen** [comment]
Nuitka really wants to run inside the environment it is compiling for. It does not have to be pip installed in there, only activate the environment and use a git clone if you want to have it outside, with that virtualenv Python. All other configurations are not supported.

For minimal effect on the virtualenv, `python setup.py develop` just creates a kind of link in the virtualenv that allows you to edit and change Nuitka and have it immediately be visible without installing again. That of course means you have a local copy of Nuitka.
