### ISSUE TITLE
module "QtQuick.Controls" plugin "qtquickcontrols2plugin" not found with --standalone

### ISSUE THREAD

**Issue by JaegerStephan** [Nuitka/Nuitka#2122]
* Please check whether the bug was already reported or fixed.

A similar issue was already reported few years ago [#76](https://github.com/Nuitka/Nuitka/issues/76)

* Please check out if the develop version of Nuitka works better for you.

Already tried to run the master and the factory version since I've already mentioned some issues in #2113 

* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version

<pre>
1.6rc3
Commercial: None
Python: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:14:58) [MSC v.1929 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\jaegeste\Desktop\nuitka-conda-example\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).
</pre>

it is the same issue for nuitka version 1.5.1 on windows and under Linux (Fedora) (Nuitka version 1.5.3)

* How did you install Nuitka and Python

pip in venv

* The specific PyPI names and versions

  > python -m pip freeze

<pre>
Nuitka @ https://github.com/Nuitka/Nuitka/archive/factory.zip
ordered-set==4.1.0       
PySide6==6.4.2
PySide6-Addons==6.4.2    
PySide6-Essentials==6.4.2
shiboken6==6.4.2
zstandard==0.20.0
</pre>

* Many times when you get an error from Nuitka, your setup may be special

For testing I tried to run [this Qt QML example](https://doc.qt.io/qtforpython-6/examples/example_qml__textproperties.html).
I made just one slight adaption. I added a resources.qrc containing the main.qml which I converted to a resources.py which again can be imported in the main.py to resolve dependencies. 

* Also supply a Short, Self Contained, Correct, Example

see above

* Provide in your issue the Nuitka options used

<pre>
nuitka --standalone --enable-plugin=pyside6 main.py
</pre>

it works fine with `--follow-imports` instead of `--standalone` but I need to have a standalone version.

The error message is:

<pre>
main.qml:7:1: module "QtQuick.Templates" plugin "qtquicktemplates2plugin" not found
</pre>

**Comment by kayhayen** [comment]
You need to enable to Qt `qml` plugin manually.

**Comment by JaegerStephan** [comment]
Thank you for that hint but adding `--enable-plugin=qml` is not available as I checked afterwards by 
`nuitka --plugin-list` which outputs

<pre>
                 The following plugins are available in Nuitka
--------------------------------------------------------------------------------
 anti-bloat        Patch stupid imports out of widely used library modules source codes.
 data-files        
 delvewheel        Required for support of delvewheel using packages in standalone mode
 dill-compat       
 dll-files
 enum-compat       
 eventlet          Support for including 'eventlet' dependencies and its need for 'dns' package monkey patching
 gevent            Required by the gevent package
 gi                Support for GI typelib dependency
 glfw              Required for OpenGL and glfw in standalone mode
 implicit-imports  
 kivy              Required by kivy package
 matplotlib        Required for matplotlib module
 multiprocessing   Required by Python's multiprocessing module
 no-qt             Disable all Qt bindings for standalone mode.
 numpy             Deprecated, was once required by the numpy package
 options-nanny     
 pbr-compat        
 pkg-resources     Workarounds for 'pkg_resources'.
 pmw-freezer       Required by the Pmw package
 pylint-warnings   Support PyLint / PyDev linting source markers
 pyqt5             Required by the PyQt5 package.
 pyqt6             Required by the PyQt6 package for standalone mode.
 pyside2           Required by the PySide2 package.
 pyside6           Required by the PySide6 package for standalone mode.
 pywebview         Required by the webview package (pywebview on PyPI)
 tensorflow        Deprecated, was once required by the tensorflow package
 tk-inter          Required by Python's Tk modules
 torch             Deprecated, was once required by the torch package
 trio              Required for Trio package
 upx               Compress created binaries with UPX automatically
</pre>

So how can I consider qml plugin?
I can not find any answer. I crawled the web (especially the documentation and the repository and issuesalready for hours.

**Comment by kayhayen** [comment]
The Qt plugins have an include option for Qt plugins. Impossible to talk about plugins for plugins. This is sort of a duplicate, because "qml" could be derived from used imports mayhaps, but that is not implemented.

**Comment by JaegerStephan** [comment]
Ok...after searching in the source code I could handle it. Just one careful hint: maybe some documentation regarding qml could be improved since even the `--include-qt-plugins` argument is not listed by `nuitka --help`.
The issue can be closed.

**Comment by kayhayen** [comment]
It is listed though, but of course only when the plugin is enabled. For QML specifically though, we should not have to let the user help us there, but that is forever undone so far.
