### ISSUE TITLE
nuitka-run.bat missing closing quotation mark

### ISSUE THREAD

**Issue by DiegoBaldassarMilleuno** [Nuitka/Nuitka#2125]
```
1.5.3
Commercial: None
Python: 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\diego.baldassar\Tools\Python3.11\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX64\x64\cl.exe (cl 14.3).
```

Installed with pip, no other packages involved.

> PS C:\Users\diego.baldassar> nuitka-run --help
""C:\Users\diego.baldassar\Tools\Python3.11\Scripts\nuitka.bat --run --help" is not recognized as an internal or external command, operable program or batch file.

Simply, the batch file should contain:

> "%~dp0nuitka.bat" --run %*

instead of:

> "%~dp0nuitka.bat --run %*

This fixes the issue.

**Comment by kayhayen** [comment]
Thanks for your report, this must have been forever broken, thanks for reporting. I will put it in the 1.5.4 hotfix that should come soon.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.5.4 that I just made.
