### ISSUE TITLE
is it hanging or I need to wait.

### ISSUE THREAD

**Issue by bitcoin4cashqc** [Nuitka/Nuitka#2127]
i rented an  EC2 instance to do this. Clean ubuntu 20, python3.10, latest nuitka from apt get.

Is it normal it hand on telethon?

![Screenshot_20230320_111902_Chrome](https://user-images.githubusercontent.com/17071641/226405444-82260826-d375-4a0b-9c69-639255bf0d81.jpg)

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
