### ISSUE TITLE
FATAL: delvewheel: Plugin issue while working on 'module 'scipy''. Please report the bug with the above traceback included.

### ISSUE THREAD

**Issue by cuish0920** [Nuitka/Nuitka#2128]
![image](https://user-images.githubusercontent.com/32830720/226537163-386ac5ca-aabc-44fd-b25c-f1ca858563e3.png)

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
