### ISSUE TITLE
Incompatibility between src-layout and namespace package since v1.5

### ISSUE THREAD

**Issue by bryandeng** [Nuitka/Nuitka#2130]
Consider the following minimal project of src-layout, these `__init__.py` are empty files.

```
project
├── pyproject.toml
└── src
    └── a
        └── b
            ├── c
            │   └── __init__.py
            └── __init__.py
```

The contents of `pyproject.toml` are

```
[build-system]
requires = [
    "nuitka",
    "setuptools>=45",
    "toml",
    "wheel",
]
build-backend = "nuitka.distutils.Build"

[project]
name = "a.b"
version = "0.0.1"

[tool.setuptools.packages.find]
where = ["src"]
include = ["a.b*"]
```

Then build a wheel with `pyproject-build` command and install it using `pip`.

If `nuitka <1.5`, compilation and importing work as expected.

```
Nuitka-Wheel:INFO: Building: 'a.b' with command '['/tmp/build-env-3_ky99ta/bin/python', '-m', 'nuitka', '--module', '--enable-plugin=pylint-warnings', '--output-dir=/tmp/build-via-sdist-9nablh05/a.b-0.0.1/build/lib/a', '--nofollow-import-to=*.tests', '--remove-output', '--include-package=a.b', '/tmp/build-via-sdist-9nablh05/a.b-0.0.1/build/lib/a/b']'
```
```
Python 3.8.16 (default, Mar  5 2023, 12:11:33) 
[GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from a.b import c
>>> 
```

But since v1.5, importing stops working.

```
Nuitka-Wheel:INFO: Building: 'a.b' with command '['/tmp/build-env-_v7xrbg4/bin/python', '-m', 'nuitka', '--module', '--enable-plugin=pylint-warnings', '--output-dir=/tmp/build-via-sdist-iespbkti/a.b-0.0.1/build/lib/a', '--nofollow-import-to=*.tests', '--remove-output', '--include-package=b', '/tmp/build-via-sdist-iespbkti/a.b-0.0.1/build/lib/a/b']'
```
```
Python 3.8.16 (default, Mar  5 2023, 12:11:33) 
[GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from a.b import c
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'c' from partially initialized module 'a.b' (most likely due to a circular import) (/opt/python/cp38-cp38/lib/python3.8/site-packages/a/b.cpython-38-x86_64-linux-gnu.so)
>>> 
```

**Comment by kayhayen** [comment]
Can you try and formulate a pull request that adds it to `tests/distutils`. I thought I have a test case there, that does something like this, and I do not recognize the difference from it.

**Comment by bryandeng** [comment]
Is the existing test case called `nested_namespaces`?

I think the only difference is src-layout vs plain-layout.
And I just confirmed that my minimal project works well if using plain-layout, that is to say without a `src` folder.

**Comment by kayhayen** [comment]
For `setup.py` we cover this, the example for poetry is not working, because poetry doesn't let us play, but it would it, so I guess, this kind of also explains #2126 happening. 

Of course removing the prefix is only a workaround and far from acceptable. I need to figure out, how to know it.

The code that works for setupstools normally is this one:

```
        old_dir = os.getcwd()
        os.chdir(build_lib)

        if self.distribution.package_dir and "" in self.distribution.package_dir:
            main_package_dir = self.distribution.package_dir.get("")
        else:
            main_package_dir = os.path.abspath(old_dir)

        # Search in the build directory preferably.
        addMainScriptDirectory(main_package_dir)
```

For this to work, I guess `self.distribution.package_dir` may have been provided as absolute path, but maybe now it's relative or something like that. Bonus points if you figure it out. I guess, an `os.path.join` to `old_dir` might be all it takes.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.5.4 that I just made.
