### ISSUE TITLE
Behavior change when pyproject.toml and setup.py co-exist since v1.5

### ISSUE THREAD

**Issue by bryandeng** [Nuitka/Nuitka#2131]
## Background
`pyproject.toml` and `setup.py` co-exist in my project. They are used in two different stages.
1. `setup.py` is used by `scikit-build` to build a PyTorch C++ extension, which will be packaged into the wheel later.
2. `nuitka` and `setuptools` are configured through `pyproject.toml` to do compilation of the Python part and packaging.

## Problem
Since v1.5, `nuitka` starts reading `setup.py` which were ignored by previous versions of `nuitka`.

###
I can delete it anyway, before my stage 2. But I think it's better to report this behavior change to know if it's by design or not.
Maybe some change in package discovery mechanism results in that `setup.py` is scanned as a normal `.py` file?
My project uses the src-layout.

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
