### ISSUE TITLE
" ModuleNotFoundError: No module named 'UFONet' "

### ISSUE THREAD

**Issue by RpR-DeeJay** [Nuitka/Nuitka#2135]
i do apologise if this has been brought up before but it didnt appear to show up when i searched. this may not even be an issue and i just dont understand how im supposed to do this stuff in which case some help would be much appreciated. 

Using kali linux installed on my windows 10 PC.
Already ran the "setup.py" file several times with no errors.
i ran the "ufonet" file and it threw the following error:

{
`┌──(deejay㉿DESKTOP-AND59K2)-[~/ufonet]
└─$ ufonet
Traceback (most recent call last):
  File "/usr/local/bin/ufonet", line 33, in <module>
    sys.exit(load_entry_point('ufonet==1.8', 'gui_scripts', 'ufonet')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/ufonet", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'UFONet'`
}

i have no idea what is going on.

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
