### ISSUE TITLE
Where ist the .pdb file

### ISSUE THREAD

**Issue by mrduszek** [Nuitka/Nuitka#2139]
I've created an .exe file from a .py with Nuitka. For further proccess I need the .pdb file but it was not created. How can I create the .pdb file with Nuitka?

**Comment by kayhayen** [comment]
Nuitka only creates those in `--debug` mode. Notice however, you do not want to deploy the binary coming out of that. I am curious what further processing is done with that PDB file.

**Comment by mrduszek** [comment]
I did run nuikta with --debug but still there is no .pdb file. I want to protect the source code of a python script from reverse eng. The purpose of the .pdb file is to run it together with the executable (compiled with nuitka) through an obfuscator like pyarmor or vmprotect.
