### ISSUE TITLE
I can’t set the path to settings.ini and in the result the exe file does not see it outside of main.dist

### ISSUE THREAD

**Issue by Kuromi-Chan** [Nuitka/Nuitka#2140]
I can’t set the path to settings.ini and in the result the exe file does not see it outside of main.dist.
I get an error when starting like: configparser.NoSextionErorr.
How to set the path?

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
