### ISSUE TITLE
Multiprocessing spawn didn't cope well with relative path launch and directory change

### ISSUE THREAD

**Issue by JiaPai12138** [Nuitka/Nuitka#2141]
**I am not sure if it can be reproduced**
$ python -m nuitka --version
```
1.5.4
Commercial: None
Python: 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: D:\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: D:\IDE\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\cl.exe (cl 14.3).
```
Installed python from official website, added to PATH
Nuitka Installed by "pip install nuitka -U"

Error:
```
2023/03/29, 00:08:23    [WinError 2] The system cannot find the file specified
File "<frozen main1>", line 379, in main
File "<frozen main1>", line 380, in main
File "<string>", line 1, in <module>
File "<frozen test1>", line 1965, in main
File "<frozen test1>", line 1965, in main
File "E:\PJ2024_copy\multiprocessing\process.py", line 121, in start
File "E:\PJ2024_copy\multiprocessing\context.py", line 224, in _Popen
File "E:\PJ2024_copy\multiprocessing\context.py", line 336, in _Popen
File "E:\PJ2024_copy\multiprocessing\popen_spawn_win32.py", line 73, in __init__
```

## Simplified code for testing
main1.py
```
import os
from ctypes import byref, c_int, windll
from importlib import import_module
from multiprocessing import freeze_support
from pathlib import Path
from sys import executable

import win32gui


# main method
def main():
    if not windll.shell32.IsUserAnAdmin() or not __debug__:
        windll.shell32.ShellExecuteW(None, 'runas', executable, __file__, None, 1)
        exit(0)

    # 设置工作目录
    working = str(Path(__file__).parent.absolute())
    # os.path.dirname(os.path.abspath(__file__))
    os.chdir(working)

    windll.kernel32.SetConsoleMode(windll.kernel32.GetStdHandle(-10), 128)
    windll.ntdll.NtSetTimerResolution(5000, True, byref(c_int()))
    win32gui.GetDoubleClickTime = lambda: 0

    tester = import_module('folder'+'.'+'test1')
    main_run = tester.main
    eval('main_run()')


# main entry
if __name__ == '__main__':
    freeze_support()
    main()
```

test1.py:
```
import multiprocessing as mp


def process1(arr: mp.Array):
    from time import sleep

    arr[0] += 1

    while True:
        print('Processing 1 running')
        sleep(3)


def process2(arr: mp.Array):
    from time import sleep

    arr[0] += 1

    while True:
        print('Processing 2 running')
        sleep(3)


def process3(arr: mp.Array):
    from time import sleep

    arr[0] += 1

    while True:
        print('Processing 3 running')
        sleep(3)


def main():
    from time import sleep
    array_one = mp.Array('d', [0.0]*64)

    p1 = mp.Process(target=process1, args=(array_one,))
    p1.name = 'process_one'
    p1.daemon = True

    p2 = mp.Process(target=process2, args=(array_one,))
    p2.name = 'process_two'
    p2.daemon = True

    p3 = mp.Process(target=process3, args=(array_one,))
    p3.name = 'process_two'
    p3.daemon = True

    p1.start()
    p2.start()
    p3.start()

    while array_one[0] < 2:
        sleep(1)

    while True:
        print('Main process running')
        sleep(1)


if __name__ == '__main__':
    from time import sleep
    print('Here means nothing but annoying')
    while True:
        sleep(1)
```

Files structure:
```
.
├── folder
│   └── test1.py
└── main1.py
```

Nuitka command:
```
python -m nuitka --mingw64 --module --show-progress --warn-implicit-exceptions --remove-output --nofollow-imports test1.py

python -m nuitka --mingw64 --standalone --show-progress --show-memory --show-modules --enable-plugin=no-qt --windows-uac-admin --output-dir=main1 --remove-output main1.py
```
The attached file shows the result of packing
[final.zip](https://github.com/Nuitka/Nuitka/files/11102412/final.zip)

Now, if you double click main1.exe, it works fine
But if you open an administrator cmd window, cd to this folder and type "main1.exe" then enter, it will show error message like the following:
```
$ main1.exe
Traceback (most recent call last):
  File "E:\final\main1.py", line 34, in <module>
  File "E:\final\main1.py", line 28, in main
  File "<string>", line 1, in <module>
  File "E:\final\folder\test1.py", line 50, in main
  File "E:\final\multiprocessing\process.py", line 121, in start
  File "E:\final\multiprocessing\context.py", line 224, in _Popen
  File "E:\final\multiprocessing\context.py", line 336, in _Popen
  File "E:\final\multiprocessing\popen_spawn_win32.py", line 73, in __init__
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

This error might also appear on Win11 with double click

**Comment by kayhayen** [comment]
Nuitka has ways to do this better:

```
    if not windll.shell32.IsUserAnAdmin() or not __debug__:
        windll.shell32.ShellExecuteW(None, 'runas', executable, __file__, None, 1)
        exit(0)
```

I do not believe it comes close to being correct for working with multiprocessing. There are options to make a program run with privilege, I would assume they work. The above might be loosing information, and or not work correctly.

**Comment by kayhayen** [comment]
Ah, you are using `--windows-uac-admin` but I guess `not __debug__` is still firing.

**Comment by kayhayen** [comment]
I have yet to confirm the given example myself. Yesterday I was turned off by it never terminating. I will change the code so that it will not do that anymore. Not even CTRL-C worked. Maybe that is what one of your calls does. I will get back to it though and check it. I am assuming now that daemon mode is the issue.

**Comment by kayhayen** [comment]
Ok, the `os.chdir`, which is of course to be allowed, can cause it to fail. It is trying to execute a relative path, and relative to the start directory, probably as given by the shell.

It seems the daemon mode need not be specified, at least in my case, these run on, even after the main process exits. The race nature could be explained by the main thread exiting after two processes started working. I think what they are trying to do, it to launch a replacement to synchronize the data maybe, but we don't really have to care about the details.

Just need to figure out, where `multiprocessing` is getting the old path from, `sys.argv[0]` or `sys.executable` or whatever, and an argument has to be made that if it's the later, that value would have to be made absolute during startup.

**Comment by kayhayen** [comment]
So, the `sys.executable` is properly absolute normally, however, the `multiprocessing` plugin derives it from `sys.argv[0]` which may not be absolute. It is often not absolute when launched from the Windows terminal in standalone mode, I am suspecting, onefile wouldn't have the issue, using absolute paths. I am also assuming double click on Windows gives programs an absolute `sys.argv[0]` but not entirely sure of that.

I am somewhat confused why I think I saw it without standalone mode too, since the directory change you are making, there ought to not have any influence, basically being the same directory, but it appears I couldn't repeat that and maybe had used standalone at that time.

Anyway, making `sys.argv[0]` absolute at the time of import will make it harder to trigger, but not impossible. I wonder, if it is not just wrong to use all of `sys.argv[0]` and instead to relatively correct it from the startup `sys.executable` value, which should be absolute already, just the wrong name, having `python` in there rather than the `something.exe`.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
We are keeping issues open until it's released. This will likely appear in 1.5.5 release.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.5.5 that I just made.
