### ISSUE TITLE
--onefile-tempdir-spec="%CACHE_DIR% doesn't work correctly on unix systems

### ISSUE THREAD

**Issue by Gagi2k** [Nuitka/Nuitka#2143]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

 ```
 python -m nuitka --version
1.6rc5
Commercial: None
Python: 3.11.2 (main, Feb 12 2023, 00:48:52) [GCC 12.2.0]
Flavor: Debian Python
Executable: /home/gagi/work/venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Debian sid
Version C compiler: /usr/bin/gcc (gcc).
```

* How did you install Nuitka and Python

Installed into a venv.
```pip3 install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip" ordered-set zstandard patchelf```

* The specific PyPI names and versions

```antlr4-python3-runtime==4.12.0
click==8.1.3
coloredlogs==15.0.1
humanfriendly==10.0
Jinja2==3.1.2
MarkupSafe==2.1.2
Nuitka @ https://github.com/Nuitka/Nuitka/archive/develop.zip
ordered-set==4.1.0
patchelf==0.17.2.1
path==16.6.0
path.py==12.5.0
PyYAML==6.0
qface==2.0.8
six==1.16.0
watchdog==3.0.0
zstandard==0.20.0
```

* Many times when you get an error from Nuitka, your setup may be special

The application itself works fine!

* Also supply a Short, Self Contained, Correct, Example

I can try to replicate the error with a smaller hello world program, but haven't done that yet.

* Provide in your issue the Nuitka options used

The relevant ones are:

```--onefile --standalone --onefile-tempdir-spec=%CACHE_DIR%/%COMPANY%/%PRODUCT%/%VERSION% -company-name="My\ Company" --product-name=myproduct --product-version=1.2.3```

* Note if this is a regression

It's the first time i'm using nuitka, but i guess it's a regression as the documentation explains to use %CACHE_DIR% to write into the users cache directory. On linux that should be `$HOME/.cache`

* Description

I'm trying to create a onefile standalone binary using the following options:

```--onefile --standalone --onefile-tempdir-spec=%CACHE_DIR%/%COMPANY%/%PRODUCT%/%VERSION% ```

while the application itself works fine, the tempdir for storing all modules doesn't work correctly and always creates a folder named HOME in the current run directory. It looks like a $ or some escaping is missing.

I was able to see this behavior on macos intel and arm as well as on linux (debian, ubuntu). I tried multiple python versions (3.11, 3.8) and also multiple nutika versions (1.5.4 and dev). Everything is installed into a venv using pip.

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."

**Comment by Gagi2k** [comment]
give me a minute i will add the template.

**Comment by kayhayen** [comment]
I can confirm, this is indeed not working properly. On non-Windows, this is internally using `%HOME%` but forgot to put the quotes, and this has not been reported yet. I will have a fix shortly.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.5.5 that I just made.

**Comment by Gagi2k** [comment]
Just tested it with 1.5.5 and i can confirm that this is fixed now, thx a lot!
