### ISSUE TITLE
module.natsort.utils.c error 'inf' undeclared (first use in this function) did you mean 'sinf'

### ISSUE THREAD

**Issue by guerie74** [Nuitka/Nuitka#2144]
Using the first time nuitka, having some trouble when using module natsort. 

* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

1.5.4
Commercial: None
Python: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:00:38) [MSC v.1934 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\Me\AppData\Local\miniconda3\envs\ercp310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).

* How did you install Nuitka and Python
Miniconda3-latest-Windows-x86_64.exe

conda create -n ercp310 python=3.10
conda config --add channels conda-forge
conda config --set channel_priority strict
conda install asammdf
conda install nuitka
conda install watchdog

(ercp310) PS C:\UserData\ERC\hw> conda info

     active environment : ercp310
    active env location : C:\Users\Me\AppData\Local\miniconda3\envs\ercp310
            shell level : 4
       user config file : C:\Users\Me\.condarc
 populated config files : C:\Users\Me\.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=11.7=0
                          __win=0=0
       base environment : C:\Users\Me\AppData\Local\miniconda3  (writable)
      conda av data dir : C:\Users\Me\AppData\Local\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Me\AppData\Local\miniconda3\pkgs
                          C:\Users\Me\.conda\pkgs
                          C:\Users\Me\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Me\AppData\Local\miniconda3\envs
                          C:\Users\Me\.conda\envs
                          C:\Users\Me\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.3.1 requests/2.28.1 CPython/3.10.9 Windows/10 Windows/10.0.19045
          administrator : False
             netrc file : None
           offline mode : False

* The specific PyPI names and versions

asammdf @ file:///D:/bld/asammdf_1679985267954/work
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1671632566681/work
boltons @ file:///home/conda/feedstock_root/build_artifacts/boltons_1677499911949/work
brotlipy @ file:///D:/bld/brotlipy_1666764804378/work
canmatrix @ file:///home/conda/feedstock_root/build_artifacts/canmatrix_1675754198644/work
cchardet @ file:///D:/bld/cchardet_1666947750730/work
certifi==2022.12.7
cffi @ file:///D:/bld/cffi_1671179506518/work
chardet @ file:///D:/bld/chardet_1669990505384/work
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1661170624537/work
click @ file:///D:/bld/click_1666798499870/work
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1666700638685/work
conda==23.3.1
conda-package-handling @ file:///home/conda/feedstock_root/build_artifacts/conda-package-handling_1669907009957/work
conda-tree @ file:///home/conda/feedstock_root/build_artifacts/conda-tree_1679661879592/work
conda_package_streaming @ file:///home/conda/feedstock_root/build_artifacts/conda-package-streaming_1669733752472/work
contourpy @ file:///D:/bld/contourpy_1673633923174/work
cryptography @ file:///D:/bld/cryptography-split_1679811386218/work
cycler @ file:///home/conda/feedstock_root/build_artifacts/cycler_1635519461629/work
fonttools @ file:///D:/bld/fonttools_1680021368967/work
future @ file:///home/conda/feedstock_root/build_artifacts/future_1673596611778/work
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1663625384323/work
isal @ file:///D:/bld/python-isal_1667123805363/work
jsonpatch @ file:///home/conda/feedstock_root/build_artifacts/jsonpatch_1632759296524/work
jsonpointer==2.0
kiwisolver @ file:///D:/bld/kiwisolver_1666805768319/work
lxml @ file:///D:/bld/lxml_1671013694264/work
lz4 @ file:///D:/bld/lz4_1675806827501/work
matplotlib @ file:///D:/bld/matplotlib-suite_1678135731316/work
menuinst @ file:///D:/bld/menuinst_1666839998718/work
munkres==1.1.4
natsort @ file:///home/conda/feedstock_root/build_artifacts/natsort_1677763448882/work
networkx @ file:///home/conda/feedstock_root/build_artifacts/networkx_1673151334029/work
Nuitka @ file:///D:/bld/nuitka_1679835381921/work
numexpr @ file:///D:/bld/numexpr_1666816800466/work
numpy @ file:///D:/bld/numpy_1675642725500/work
ordered-set @ file:///home/conda/feedstock_root/build_artifacts/ordered-set_1643221357603/work
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1673482170163/work
pandas @ file:///D:/bld/pandas_1680107795707/work
Pillow @ file:///D:/bld/pillow_1678273669417/work
pluggy @ file:///home/conda/feedstock_root/build_artifacts/pluggy_1667232663820/work
pycosat @ file:///D:/bld/pycosat_1666836675990/work
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1680037383858/work
pyparsing @ file:///home/conda/feedstock_root/build_artifacts/pyparsing_1652235407899/work
PySocks @ file:///D:/bld/pysocks_1661604991356/work
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1680088766131/work
PyYAML @ file:///D:/bld/pyyaml_1666772550103/work
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1673863902341/work
ruamel.yaml @ file:///D:/bld/ruamel.yaml_1678273308128/work
ruamel.yaml.clib @ file:///D:/bld/ruamel.yaml.clib_1670412994006/work
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
toolz @ file:///home/conda/feedstock_root/build_artifacts/toolz_1657485559105/work
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1677948868469/work
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1678559861143/work
unicodedata2 @ file:///D:/bld/unicodedata2_1667239969015/work
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1678635778344/work
watchdog @ file:///D:/bld/watchdog_1679333145497/work
win-inet-pton @ file:///D:/bld/win_inet_pton_1667051142467/work
xlrd @ file:///home/conda/feedstock_root/build_artifacts/xlrd_1610224409810/work
XlsxWriter @ file:///home/conda/feedstock_root/build_artifacts/xlsxwriter_1678748950623/work
xlwt==1.3.0
zstandard==0.19.0

* Many times when you get an error from Nuitka, your setup may be special

hallo world without natsort is working

(ercp310) PS C:\UserData\ERC\hw> nuitka  --follow-imports --clean-cache=ccache --standalone --onefile  h.py
Nuitka-Options:INFO: Used command line options: --follow-imports --clean-cache=ccache --standalone --onefile h.py
Nuitka-Cache:INFO: Cleaning cache 'ccache' directory 'C:\Users\Me\AppData\Local\Nuitka\Nuitka\Cache\ccache'.
Nuitka-Cache:INFO: Done.
Nuitka-Options:INFO: Following all imports is the default for onefile mode and need not be specified.
Nuitka:INFO: Starting Python compilation with Nuitka '1.5.4' on Python '3.10' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 6 files (no progress information available).
Nuitka-Scons:INFO: Compiled 23 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 6
Nuitka-Postprocessing:INFO: Creating single file from dist folder, this may take a while.
Nuitka-Onefile:INFO: Running bootstrap binary compilation via Scons.
Nuitka-Scons:INFO: Onefile C compiler: gcc (gcc).
Nuitka-Scons:INFO: Onefile linking program with 1 files (no progress information available).
Nuitka-Scons:INFO: Compiled 4 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 1
Nuitka-Onefile:INFO: Keeping onefile build directory 'h.onefile-build'.
Nuitka-Onefile:INFO: Using compression for onefile payload.
Nuitka-Onefile:INFO: Onefile payload compression ratio (29.09%) size 22079834 to 6422720.
Nuitka:INFO: Keeping dist folder 'h.dist' for inspection, no need to use it.
Nuitka:INFO: Keeping build directory 'h.build'.
Nuitka:INFO: Successfully created 'h.exe'.
(ercp310) PS C:\UserData\ERC\hw> .\h.exe
Talk Hello World

* Also supply a Short, Self Contained, Correct, Example

```
import natsort as ns

def talk(message):
    return "Talk " + message

def main():
    print(talk("Hello World"))

    a = ['num5.10', 'num-3', 'num5.3', 'num2']
    ns.natsorted(a, alg=ns.REAL) == ns.natsorted(a, alg=ns.ns.REAL)

if __name__ == "__main__":
    main()

```
* Provide in your issue the Nuitka options used

(ercp310) PS C:\UserData\ERC\hw> nuitka  --follow-imports --clean-cache=ccache --standalone --onefile  hw.py
Nuitka-Options:INFO: Used command line options: --follow-imports --clean-cache=ccache --standalone --onefile hw.py
Nuitka-Cache:INFO: Cleaning cache 'ccache' directory 'C:\Users\Me\AppData\Local\Nuitka\Nuitka\Cache\ccache'.
Nuitka-Cache:INFO: Done.
Nuitka-Options:INFO: Following all imports is the default for onefile mode and need not be specified.
Nuitka:INFO: Starting Python compilation with Nuitka '1.5.4' on Python '3.10' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
module.natsort.utils.c: In function 'impl_natsort$utils$$$function__18_parse_number_or_none_factory':
module.natsort.utils.c:4854:36: error: 'inf' undeclared (first use in this function); did you mean 'sinf'?
 4854 |             tmp_cmp_expr_right_1 = inf;
      |                                    ^~~
      |                                    sinf

Backend C: 93.8%|███████████████████████▍ | 15/16scons: *** [module.natsort.utils.o] Error 1
Nuitka-Scons:INFO: Backend linking program with 16 files (no progress information available).

* Avoid unnecessary options

same with: nuitka  --follow-imports --clean-cache=ccache --standalone  hw.py
same with: nuitka  --follow-imports --clean-cache=ccache  hw.py

* Note if this is a regression

first time using nuitka

**Comment by kayhayen** [comment]
Thanks for the report, that's a rare find of issue. Apparently this is trying to use a C float value for `inf` and that is not how these are written in C. Should be super easy to fix.

**Comment by kayhayen** [comment]
I reduced it to this code:

```
def f(alg):
    nan_replace = float("+inf") if alg else float("-inf")
    return nan_replace == float("+inf")
```

This is a so far rare case, where the comparison code, actually uses the internal C type "CFLOAT" for C `double`. It doesn't yet use that for `nan_replace` storage, but that wouldn't really change much as for the bug. But since that has object storage, those float calls end up producing a `PyObject *` of these `inf` values, but for the comparison we do optimize it, and call then `RICH_COMPARE_EQ_CBOOL_FLOAT_CFLOAT` with the right side, being `inf`.

I suspect that `nan` might have similar issues, and maybe even -0, not sure of that. The code to generate the C literal there, just takes the Python value too directly.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by guerie74** [comment]
Perfect! Looks pretty good :), the small sample from above is now compiling without complains! I can confirm that the fix on factory branch is working, I just tested it in an new conda environment:

(ercp310nfix) PS C:\UserData\ERC\hw> python -m nuitka --version
1.6rc5
Commercial: None
Python: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:00:38) [MSC v.1934 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\Me\AppData\Local\miniconda3\envs\ercp310nfix\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).
(ercp310nfix) PS C:\UserData\ERC\hw> nuitka  --follow-imports --clean-cache=ccache --standalone --onefile  hw.py
Nuitka-Options:INFO: Used command line options: --follow-imports --clean-cache=ccache --standalone --onefile hw.py
Nuitka-Cache:INFO: Cleaning cache 'ccache' directory 'C:\Users\Me\AppData\Local\Nuitka\Nuitka\Cache\ccache'.
Nuitka-Cache:INFO: Done.
Nuitka-Options:INFO: Following all imports is the default for onefile mode and need not be specified.
Nuitka:INFO: Starting Python compilation with Nuitka '1.6rc5' on Python '3.10' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 16 files (no progress information available).
Nuitka-Scons:INFO: Compiled 64 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 16
Nuitka-Postprocessing:INFO: Creating single file from dist folder, this may take a while.
Nuitka-Onefile:INFO: Running bootstrap binary compilation via Scons.
Nuitka-Scons:INFO: Onefile C compiler: gcc (gcc).
Nuitka-Scons:INFO: Onefile linking program with 1 files (no progress information available).
Nuitka-Scons:INFO: Compiled 4 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 1
Nuitka-Onefile:INFO: Keeping onefile build directory 'hw.onefile-build'.
Nuitka-Onefile:INFO: Using compression for onefile payload.
Nuitka-Onefile:INFO: Onefile payload compression ratio (28.93%) size 22516572 to 6514798.
Nuitka:INFO: Keeping dist folder 'hw.dist' for inspection, no need to use it.
Nuitka:INFO: Keeping build directory 'hw.build'.
Nuitka:INFO: Successfully created 'hw.exe'.

THX!

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.5.5 that I just made.

**Comment by twstagg** [comment]
Wow. Thanks guys! Came here to report this. 1.5.5 release fixes it for me!
