### ISSUE TITLE
Anaconda on macOS gives during C compilation "undeclared function 'getsectdata'"

### ISSUE THREAD

**Issue by willm10034** [Nuitka/Nuitka#2146]
I'm getting the error:
undeclared function 'getsectdata'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

This is on a M2 Pro Mac mini w/Ventura

**$ python -m nuitka --version**           
1.5.4
Commercial: None
Python: 3.9.16 (main, Mar  8 2023, 04:29:24) 
Flavor: Anaconda Python
Executable: /Users/will/anaconda3/envs/py39/bin/python
OS: Darwin
Arch: arm64
Version C compiler: /usr/bin/clang (clang).

**Python File:**

def Hello():
    print('Hello world!')

if __name__ == '__main__':
    Hello()

**Output of python -m Nuitka --show-scons test.py:**

Nuitka-Options:INFO: Used command line options: --show-scons test.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure that is
Nuitka-Options:WARNING: intended.
Nuitka:INFO: Starting Python compilation with Nuitka '1.5.4' on Python '3.9' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Scons command: /Users/will/anaconda3/envs/py39/bin/python -W ignore /Users/will/anaconda3/envs/py39/lib/python3.9/site-packages/nuitka/build/inline_copy/bin/scons.py -f /Users/will/anaconda3/envs/py39/lib/python3.9/site-packages/nuitka/build/Backend.scons --jobs 12 --warn=no-deprecated --no-site-dir --debug=stacktrace result_name=/Users/will/Dropbox/Will/PycharmProjects/factoring/test source_dir=. nuitka_python=false debug_mode=false python_debug=false module_mode=false full_compat=false experimental= trace_mode=false python_version=3.9 nuitka_src=/Users/will/anaconda3/envs/py39/lib/python3.9/site-packages/nuitka/build module_count=1 result_exe=/Users/will/Dropbox/Will/PycharmProjects/factoring/test.bin python_prefix=/Users/will/anaconda3/envs/py39 clang_mode=true show_scons=true noelf_mode=true anaconda_python=true macos_min_version=11.1 macos_target_arch=arm64 target_arch=arm64
scons: Reading SConscript files ...
Nuitka-Scons:INFO: CC '/usr/bin/gcc' version check gives (14, 0, 3)
Nuitka-Scons:INFO: Initial CC: 'gcc'
Nuitka-Scons:INFO: Initial CCVERSION: (14, 0, 3)
Scons: Compiler used /usr/bin/clang 
Nuitka-Scons:INFO: Backend C compiler: clang (clang).
Nuitka-Scons:INFO: LTO mode auto was resolved to mode: 'yes' (known to be supported (macOS clang)).
Nuitka-Scons:INFO: Using C11 mode: True
Nuitka-Scons:INFO: Using resource mode: 'mac_section' (default for macOS).
Nuitka-Scons:INFO: Told to run compilation on 12 CPUs.
Nuitka-Scons:INFO: Found ccache '/opt/homebrew/bin/ccache' to cache C compilation result.
Nuitka-Scons:INFO: Providing real CC path '/usr/bin/clang' via PATH extension.
Nuitka-Scons:INFO: Launching Scons target: ['/Users/will/Dropbox/Will/PycharmProjects/factoring/test.bin']
scons: done reading SConscript files.
scons: Building targets ...
"/opt/homebrew/bin/ccache" "/usr/bin/clang" -o __constants.o -c -flto -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden --target=arm64-apple-macos11.1 -O3 -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_MACOS_SECTION -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/Users/will/anaconda3/envs/py39/include/python3.9 -I. -I/Users/will/anaconda3/envs/py39/lib/python3.9/site-packages/nuitka/build/include -I/Users/will/anaconda3/envs/py39/lib/python3.9/site-packages/nuitka/build/static_src __constants.c
"/opt/homebrew/bin/ccache" "/usr/bin/clang" -o __helpers.o -c -flto -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden --target=arm64-apple-macos11.1 -O3 -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_MACOS_SECTION -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/Users/will/anaconda3/envs/py39/include/python3.9 -I. -I/Users/will/anaconda3/envs/py39/lib/python3.9/site-packages/nuitka/build/include -I/Users/will/anaconda3/envs/py39/lib/python3.9/site-packages/nuitka/build/static_src __helpers.c
"/opt/homebrew/bin/ccache" "/usr/bin/clang" -o __loader.o -c -flto -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden --target=arm64-apple-macos11.1 -O3 -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_MACOS_SECTION -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/Users/will/anaconda3/envs/py39/include/python3.9 -I. -I/Users/will/anaconda3/envs/py39/lib/python3.9/site-packages/nuitka/build/include -I/Users/will/anaconda3/envs/py39/lib/python3.9/site-packages/nuitka/build/static_src __loader.c
"/opt/homebrew/bin/ccache" "/usr/bin/clang" -o module.__main__.o -c -flto -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden --target=arm64-apple-macos11.1 -O3 -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_MACOS_SECTION -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/Users/will/anaconda3/envs/py39/include/python3.9 -I. -I/Users/will/anaconda3/envs/py39/lib/python3.9/site-packages/nuitka/build/include -I/Users/will/anaconda3/envs/py39/lib/python3.9/site-packages/nuitka/build/static_src module.__main__.c
"/opt/homebrew/bin/ccache" "/usr/bin/clang" -o static_src/MainProgram.o -c -flto -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden --target=arm64-apple-macos11.1 -O3 -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_MACOS_SECTION -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/Users/will/anaconda3/envs/py39/include/python3.9 -I. -I/Users/will/anaconda3/envs/py39/lib/python3.9/site-packages/nuitka/build/include -I/Users/will/anaconda3/envs/py39/lib/python3.9/site-packages/nuitka/build/static_src static_src/MainProgram.c
"/opt/homebrew/bin/ccache" "/usr/bin/clang" -o static_src/CompiledFunctionType.o -c -flto -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden --target=arm64-apple-macos11.1 -O3 -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_MACOS_SECTION -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/Users/will/anaconda3/envs/py39/include/python3.9 -I. -I/Users/will/anaconda3/envs/py39/lib/python3.9/site-packages/nuitka/build/include -I/Users/will/anaconda3/envs/py39/lib/python3.9/site-packages/nuitka/build/static_src static_src/CompiledFunctionType.c
In file included from static_src/CompiledFunctionType.c:2673:
In file included from /Users/will/anaconda3/envs/py39/lib/python3.9/site-packages/nuitka/build/static_src/CompiledCodeHelpers.c:2108:
/Users/will/anaconda3/envs/py39/lib/python3.9/site-packages/nuitka/build/static_src/HelpersConstantsBlob.c:1199:12: error: call to undeclared function 'getsectdata'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    return getsectdata("constants", "constants", &size) + (uintptr_t)header;
           ^
1 error generated.
Nuitka-Scons:INFO: Backend linking program with 6 files (no progress information available).
scons: *** [static_src/CompiledFunctionType.o] Error 1
scons: internal stack trace:
  File "/Users/will/anaconda3/envs/py39/lib/python3.9/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Job.py", line 258, in run
    task.execute()
  File "/Users/will/anaconda3/envs/py39/lib/python3.9/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Script/Main.py", line 206, in execute
    SCons.Taskmaster.OutOfDateTask.execute(self)
  File "/Users/will/anaconda3/envs/py39/lib/python3.9/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Taskmaster.py", line 255, in execute
    self.targets[0].build()
  File "/Users/will/anaconda3/envs/py39/lib/python3.9/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Node/__init__.py", line 766, in build
    self.get_executor()(self, **kw)
  File "/Users/will/anaconda3/envs/py39/lib/python3.9/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Executor.py", line 397, in __call__
    return _do_execute_map[self._do_execute](self, target, kw)
  File "/Users/will/anaconda3/envs/py39/lib/python3.9/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Executor.py", line 131, in execute_action_list
    raise status    # TODO pylint E0702: raising int not allowed
scons: building terminated because of errors.

**Comment by kayhayen** [comment]
Thanks for your report, it seems Anaconda on macOS is regressed. On my M2 it doesn't do that, it seems you are not using any CondaCC. I noticed, it will call with any signature. So it's as if it's undefined for me too. When I include the header from the manpage it will crash for me, although it seems to match. If I declare only the function as used, it will also crash for me. Very strange. 

Looking at the header and the function, it says it's deprecated, and using `getsectiondata` didn't crash even with the header. I think that should solve the issue.

As an aside, I am not sure of the effect of `-m Nuitka` over `-m nuitka`, hopefully it doesn't load the main package as `Nuitka` because I think that could cause trouble. I need to check that out occassionally, took note of that.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by willm10034** [comment]
Successfully installed Nuitka-1.6rc5 ordered-set-4.1.0 zstandard-0.20.0

Same error using the factory version.
Nuitka:INFO: Starting Python compilation with Nuitka '1.6rc5' on Python '3.9' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: /usr/bin/clang (clang).
In file included from static_src/CompiledFunctionType.c:2673:
In file included from /Users/will/anaconda3/envs/py39/lib/python3.9/site-packages/nuitka/build/static_src/CompiledCodeHelpers.c:2108:
/Users/will/anaconda3/envs/py39/lib/python3.9/site-packages/nuitka/build/static_src/HelpersConstantsBlob.c:1202:12: error: call to undeclared function 'getsectdata'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    return getsectdata("constants", "constants", &size) + (uintptr_t)header;
           ^                                   
1 error generated.                             
Nuitka-Scons:INFO: Backend linking program with 6 files (no progress information available).
scons: *** [static_src/CompiledFunctionType.o] Error 1

**Comment by kayhayen** [comment]
That puts the "success" part into question, that is the old code.

**Comment by amiyapatanaik** [comment]
I got the same error on a project which was building fine but stopped working after I upgraded my Mac M1 to Ventura 

`Nuitka-Scons:INFO: Backend C compiler: clang (clang).
In file included from static_src/CompiledFunctionType.c:2673:
In file included from /Users/amiya/opt/anaconda3/envs/neurobitpsg/lib/python3.8/site-packages/nuitka/build/static_src/CompiledCodeHelpers.c:2108:
/Users/amiya/opt/anaconda3/envs/neurobitpsg/lib/python3.8/site-packages/nuitka/build/static_src/HelpersConstantsBlob.c:1207:29: error: call to undeclared function 'getsectdatafromheader_64'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    unsigned char *result = getsectdatafromheader_64(header, "constants", "constants", &size) + (uintptr_t)header;
                            ^                   
1 error generated.                              `

**Comment by kayhayen** [comment]
@amiyapatanaik that too should be solved by the factory branch

**Comment by kayhayen** [comment]
It seems I forgot to push, sorry my bad.

**Comment by amiyapatanaik** [comment]
Yes, that resolves the issue. Thank you. When can I expect it pushed to the stable branch?

**Comment by willm10034** [comment]
Yes, it's fixed, thank you.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.5.5 that I just made.
