### ISSUE TITLE
Question: Compiling for all of Windows, Linux, and MacOS when you do not have access to all

### ISSUE THREAD

**Issue by tksoftw** [Nuitka/Nuitka#2149]
Hello,

I've been using Nukita to compile my Python code and it's been working great. However, I'm not sure how to compile my code for my friend, who runs MacOS. I'm running Nukita on Windows myself and I was wondering if it's possible to compile my code for both Windows and MacOS.

Any help would be greatly appreciated. Thank you!

**Comment by kayhayen** [comment]
This is a duplicate, cross compilation is not supported. However, GitHub can compile for you, check out: https://github.com/Nuitka/Nuitka-Action which will build for you.
