### ISSUE TITLE
transformers can't find PyTorch

### ISSUE THREAD

**Issue by biw** [Nuitka/Nuitka#2151]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.
```
1.6rc6
Commercial: None
Python: 3.9.16 (main, Dec  7 2022, 10:06:04)
Flavor: Homebrew Python
Executable: /Users/ben/Library/Caches/pypoetry/virtualenvs/nuitka-test-MHSt2B15-py3.9/bin/python
OS: Darwin
Arch: arm64
Version C compiler: /usr/bin/clang (clang).
```

* How did you install Nuitka and Python

using python from Conda, poetry to manage the install, installed Nuitka via poetry

`pyproject.toml`:
```
[tool.poetry]
name = "nuitka-test"
version = "0.1.0"
description = ""
authors = ["Ben Williams <email@email.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
nuitka = { git = "https://github.com/Nuitka/Nuitka.git", branch = "factory" }
transformers = "4.27.4"
torch = "1.13.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

* The specific PyPI names and versions

```
certifi==2022.12.7
charset-normalizer==3.1.0
filelock==3.11.0
huggingface-hub==0.13.4
idna==3.4
Jinja2==3.1.2
MarkupSafe==2.1.2
mpmath==1.3.0
networkx==3.1
Nuitka @ git+https://github.com/Nuitka/Nuitka.git@d37e6294dfba8038dfff01a2a3059e01e5cbb155
numpy==1.24.2
ordered-set==4.1.0
packaging==23.0
Pillow==9.5.0
PyYAML==6.0
regex==2023.3.23
requests==2.28.2
sympy==1.11.1
tokenizers==0.13.3
torch==1.13.1
torchvision==0.15.1
tqdm==4.65.0
transformers==4.27.4
typing_extensions==4.5.0
urllib3==1.26.15
zstandard==0.20.0
```

(Also tried with `torch===2.0.0` and got the same errors)

`poetry.lock` (too long for the issue): https://gist.github.com/biw/f34c8c0513aac9805c8c785b72b38b15

* Many times when you get an error from Nuitka, your setup may be special

✅ Confirmed that Nuitka works with simple `print` example.

* Also supply a Short, Self Contained, Correct, Example

The following is a short example showing that highlights the issue:

```py
import transformers
import torch
print('hello world')
print(transformers.__version__, torch.__version__)
```

* Provide in your issue the Nuitka options used

```
poetry run python -m nuitka --standalone  ./hello.py
```

After running the `.bin`, I get the following message:
```
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
```
which is odd given that I get the version number of `transformers` and `torch` on line 4. I might be missing some flags, but after debugging a few hours wasn't sure. This causes `transformers` to fail when actually calling the library

**Comment by kayhayen** [comment]
The code doing the version check is likely not compile time optimized. Need to check it out, and likely just remove it. I think when I added support for `transformers` I saw it, but then it was also true, i.e. was given by Python as well.

**Comment by kayhayen** [comment]
If you want to help, you can find the source code file, ideally as an upstream source code link, where they give the error message, so we can consider what kind of anti-bloat Yaml we are going to use there.

**Comment by kayhayen** [comment]
This is now tracked in #2193 which was created later, and has priority.
