### ISSUE TITLE
Linux standalone: should not include "libnssutil3.so" from the OS

### ISSUE THREAD

**Issue by twstagg** [Nuitka/Nuitka#2154]
See title. I'm experiencing an issue with --onefile compiled builds on Linux with a particular lib. Removing it allows the program to launch. However, I'm unclear on how to do this once the binary has been compressed into a single file.

I do not see documentation regarding an interface to do this. I am asking as I have received a report in my project for the latest build on Linux. Specifically, I was able to resolve the issue by providing a non-onefile build that had `libnssutil3.so`

A link to the report I received: https://github.com/oceancabbage/RimSort/issues/59

To clarify - I would like to be able to completely skip over packing `libnssutil3.so` from my builds on Linux

```
~$ python3 -m nuitka --version
1.5.5
Commercial: None
Python: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Flavor: Debian Python
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.2
Version C compiler: /usr/bin/gcc (gcc).
```

Nuitka installed via `pip`,

**Comment by kayhayen** [comment]
Maybe the file names of the libc changed, we already ignore `libnssutils3.so` among many others. And yes, there is an option to not include DLLs, check help output. However of course, that ought to be unnecessary.

As an aside, building on latest Linux is not recommended for many reasons, not the least being that the Python library is not going to like oder systems a lot. In Nuitka commercial I have a tool to build inside an old container so it works on old systems too: https://nuitka.net/doc/commercial.html which does this automatically. But basically you ought to build on CentOS 7 or very old Debian, but for later I am not entirely sure how good it is I fear not as portable.

That said, I am adding the DLL to the list of automatically excluded things.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by twstagg** [comment]
@kayhayen 

> Maybe the file names of the libc changed, we already ignore `libnssutils3.so` among many others. And yes, there is an option to not include DLLs, check help output. However of course, that ought to be unnecessary.
> 
> As an aside, building on latest Linux is not recommended for many reasons, not the least being that the Python library is not going to like oder systems a lot. In Nuitka commercial I have a tool to build inside an old container so it works on old systems too: https://nuitka.net/doc/commercial.html which does this automatically. But basically you ought to build on CentOS 7 or very old Debian, but for later I am not entirely sure how good it is I fear not as portable.
> 
> That said, I am adding the DLL to the list of automatically excluded things.

Thanks for the info! I will consider that in the future. For now, I am building against older versions of glibc - which takes care of the issue you begin to describe here. When I get things working perfectly, I have seen some cool docker containers for PyInstaller that gave me some ideas for my own ecosystem as well.

Could you please elaborate on the option(s) "to not include DLLs, check help output" just for my future reference?

> Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html
> 
> Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

I will try out factory and let you know if that resolves my issue as well after my attempt!

**Comment by twstagg** [comment]
@kayhayen 

```
$ python3 -m nuitka --version
1.6rc6
Commercial: None
Python: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Flavor: Debian Python
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.2
AttributeError: module 'ctypes' has no attribute 'windll':
  File "/home/Steelbox.local/tstagg/.local/lib/python3.10/site-packages/nuitka/build/CCompilerVersion.scons", line 253:
    reportCCompiler(env, "Version", my_print)
  File "/home/Steelbox.local/tstagg/.local/lib/python3.10/site-packages/nuitka/build/SconsCompilerSettings.py", line 880:
    % (context, getReportPath(env.the_compiler), cc_output)
  File "/home/Steelbox.local/tstagg/.local/lib/python3.10/site-packages/nuitka/utils/FileOperations.py", line 1090:
    _report_path_cache[key] = _getReportPath(filename, prefixes)
  File "/home/Steelbox.local/tstagg/.local/lib/python3.10/site-packages/nuitka/utils/FileOperations.py", line 1127:
    filename = getWindowsLongPathName(filename)
  File "/home/Steelbox.local/tstagg/.local/lib/python3.10/site-packages/nuitka/utils/FileOperations.py", line 1014:
    GetLongPathNameW = ctypes.windll.kernel32.GetLongPathNameW
```

Unrelated, but I get this after reinstalling with factory on Ubuntu 22.04 this morning - let me know if you would like me to put in a separate issue

**Comment by kayhayen** [comment]
Yeah, that is life with factory, for a Windows issue, I didn't limit the code added to Windows, but should be better now.

**Comment by kayhayen** [comment]
Self built Python done with care will also work, that's great. I do not consider myself an interactive manual.

As for the bug, it must be old, I didn't find any Ubuntu version that had the name "libnssutils3.so" for a DLL. I need to check on CentOS 7 still.

**Comment by kayhayen** [comment]
Even on CentOS7 that "new" name was used, so I kind of assume it was a typo all along. Strange how this went unnoticed for so long, but I guess, we shall be glad you found it and reported it.

**Comment by twstagg** [comment]
@kayhayen 

My issue is resolved with those changes on factory branch. Thanks!

Could you please elaborate on the option(s) "to not include DLLs, check help output" just for my future reference?

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.5.6 that I just made.
