### ISSUE TITLE
Onefile mode broken on hotfix/1.5.6

### ISSUE THREAD

**Issue by R-YaTian** [Nuitka/Nuitka#2158]
Nuitka version: 1.5.6
Commercial: None
Python: 3.8.16 (default, Dec 20 2022, 23:03:33) [MSC v.1900 32 bit (Intel)]
Flavor: CPython Official
OS: Windows
Arch: x86
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\Hostx86\x86\cl.exe (cl 14.3).

The specific PyPI names and versions:
Nuitka @ file:///D:/downloads/Nuitka-hotfix-1.5.6.zip
ordered-set==4.1.0
zstandard==0.20.0

Provide in your issue the Nuitka options used:
nuitka -standalone --msvc=14.3 --enable-plugin=tk-inter --nofollow-import-to=dbm --nofollow-import-to=distutils --nofollow-import-to=py_compile --nofollow-import-to=argparse --onefile test.py

*Onefile mode works fine on hotfix1.5.5 before...

**Comment by kayhayen** [comment]
Seems devoid of useful information.
