### ISSUE TITLE
"unexpected keyword argument" error compiling PyQtGraph application

### ISSUE THREAD

**Issue by ntjess** [Nuitka/Nuitka#2162]
<details>
<summary>Output of <code>pip freeze</code></summary>

```
certifi @ file:///C:/b/abs_85o_6fm0se/croot/certifi_1671487778835/work/certifi
click==8.1.3
colorama==0.4.6
darkdetect==0.7.1
Nuitka==1.5.5
numpy==1.24.2
ordered-set==4.1.0
packaging==23.0
pyqtdarktheme==2.1.0
pyqtgraph @ git+https://github.com/pyqtgraph/pyqtgraph@7642e18e1d1ff569b1ef6db844c09280fc5fcddf
PySide6==6.5.0
PySide6-Addons==6.5.0
PySide6-Essentials==6.5.0
qtextras==0.6.7
QtPy==2.3.1
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.7
shiboken6==6.5.0
wincertstore==0.2
zstandard==0.20.0
```

</details>

<details>
<summary>Output of <code>python -m nuitka --version</code></summary>

```
1.5.5
Commercial: None
Python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\ntjess\miniconda3\envs\py39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX64\x64\cl.exe (cl 14.3).
```

</details>

MWE file `main.py`:
```python
import pyqtgraph as pg
from pyqtgraph.parametertree import Parameter, ParameterTree

pg.mkQApp()
tree = ParameterTree()

params = [
    {'name': 'param1', 'type': 'int', 'value': 10},
    {'name': 'param2', 'type': 'float', 'value': 1.0},
    {'name': 'param3', 'type': 'bool', 'value': True},
    {'name': 'param4', 'type': 'list', 'values': ['a', 'b', 'c'], 'value': 'a'},
]

p = Parameter.create(name='params', type='group', children=params)
tree.setParameters(p, showTop=False)

tree.show()
pg.exec()
```

After compiling with `python -m nuitka main.py  --enable-plugin=pyside6 --standalone`

and running with `main.dist/main.exe`:
```
Traceback (most recent call last):
  File "C:\Users\ntjess\Desktop\git\TEST-N~1\MAIN~1.DIS\main.py", line 15, in <module>
  File "C:\Users\ntjess\Desktop\git\TEST-N~1\MAIN~1.DIS\pyqtgraph\parametertree\ParameterTree.py", line 50, in setParameters
  File "C:\Users\ntjess\Desktop\git\TEST-N~1\MAIN~1.DIS\pyqtgraph\parametertree\ParameterTree.py", line 80, in addParameters
  File "C:\Users\ntjess\Desktop\git\TEST-N~1\MAIN~1.DIS\pyqtgraph\parametertree\ParameterTree.py", line 67, in addParameters
  File "C:\Users\ntjess\Desktop\git\TEST-N~1\MAIN~1.DIS\pyqtgraph\parametertree\Parameter.py", line 571, in makeTreeItem
  File "C:\Users\ntjess\Desktop\git\TEST-N~1\MAIN~1.DIS\pyqtgraph\parametertree\parameterTypes\basetypes.py", line 62, in __init__
TypeError: _missing_interp() got an unexpected keyword argument 'force'
```

Note that the example has no issues compiling without standalone (`python -m nuitka main.py`) and instead running `.\main.cmd`:
![image](https://user-images.githubusercontent.com/23620506/231103451-8477a1da-01ad-481b-8568-e1733c17c265.png)

Is there something I can fix on my end?

_Originally posted by @ntjess in https://github.com/Nuitka/Nuitka/issues/1532#issuecomment-1502912511_

**Comment by kayhayen** [comment]
I managed to reproduce it. Somehow for a type, a default implementation is used. There has to be some sort of unpopulated registry, that I need to find I guess.

**Comment by kayhayen** [comment]
```
        def _missing_interp(v):
            # Assume raw interpretation
            return v
            # Or:
            # raise TypeError(f'No interpreter found for type {typ}')
```

This not supporting `force` might be an upstream problem, but in the uncompiled, this never triggered, so there is some sort of incompatibility going on.

**Comment by kayhayen** [comment]
What's crazy, is that if I change that function to raise the `TypeError`, the compilation result just works. I need to repeat that, but that should be impossible, but maybe something handles that `TypeError`.

**Comment by kayhayen** [comment]
This is killing me.

How can `_missing_interp` as given by the qualname be used, when it lives like this:

```
    def _interpretValue(self, v):
        typ = self.opts['type']

        def _missing_interp(v):
            # Assume raw interpretation
            return v
            # Or:
            # raise TypeError(f'No interpreter found for type {typ}')

        assert hasattr(builtins, typ)
        interpreter = getattr(builtins, typ, _missing_interp)
        print("V", typ, interpreter, v)
        return interpreter(v)
```

Literally the only way is if there is corruption with compiled function objects of some sorts. This appears to be yet another symptom of a corruption. However, yet again, it's behaving the same on both Windows and Linux. That is entirely unlikely for a corruption. However, I lack any other explanation. I am disabling the freelist. Also, something of note is that with using `typ` the function is having a closure variable and as such might have different malloc behaviour. If this holds true, it's a very ugly issue.

**Comment by kayhayen** [comment]
So, I narrowed this down a lot. I added a bunch of checks and made a bunch of disables for optimazation work and more checks generally. But turns out, that his call releases the compiled method in question, the one found later used in unusable state. Did that by checking release functions for their names.

> self.widget.sigChanged.disconnect(self.widgetValueChanged)

Here, this is a PySide6 widget, which disconnects a slot and after that, `self.widgetValueChanged` is released, but still stored in `self`. With a free list, the memory can be used again, and then the effect is different code being called, which explains the error seen when attempting to call it, namely the argument error.

The call code is also innocent, I disabled all call optimization too, making the most generic call form and things still happen like that. Now first course of action in to update PySide6 and see if we can reproduce it outside of pyqtgraph. The fix probably has to be in PySide6. Unfortunately PySide 6.5.0 is equally affected. I was still using a 6.4 before.

**Comment by kayhayen** [comment]
So, I isolate this:

```
""" Reference counting tests.

These contain functions that do PySide6 specific things, where we have a suspect
that references may be lost or corrupted. Executing them repeatedly and
checking the reference count is how they are used.
"""

# While we use that for comparison code, no need to compile that.
# nuitka-project: --nofollow-import-to=nuitka

# nuitka-project: --enable-plugin=pyside6

import os
import sys

import sys
from PySide6.QtWidgets import QApplication, QPushButton

app = QApplication()
button = QPushButton("Call function")

from nuitka.tools.testing.Common import executeReferenceChecked

x = 17

def function():
    pass

class C:
    def meth(self):
        pass

def qtTestFunction1():
    button.clicked.connect(function)
    button.clicked.disconnect(function)

def qtTestFunction2():
    c = C()

    button.clicked.connect(c.meth)
    # button.clicked.disconnect(c.meth)

####################################

# These need stderr to be wrapped.
tests_stderr = ()

# Disabled tests
tests_skipped = {}

result = executeReferenceChecked(
    prefix="qtTestFunction",
    names=globals(),
    tests_skipped=tests_skipped,
    tests_stderr=tests_stderr,
)

sys.exit(0 if result else 1)
```

**Comment by kayhayen** [comment]
Commenting out the `disconnect` actually makes no difference. The automatic disconnect releases the function owned by the given method object illegally. Only if the object lives, repeated connects are not an issue. I think we need to check PySide6 code in that area.

**Comment by kayhayen** [comment]
So, as a workaround, you can do this.

```
def myconnect(self, func):
    if hasattr(func, "im_func"):
        if hasattr(func.im_func, "__compiled__"):
            myconnect._protected = getattr(myconnect, "_protected", set())
            myconnect._protected.add(func)

    return orig_connect(self, func)

import PySide6.QtCore
orig_connect = PySide6.QtCore.SignalInstance.connect
PySide6.QtCore.SignalInstance.connect = myconnect
```

Then it's no more crashing, but leaking a reference to the compiled method and as a consequence the object assiociated. The real fix has to be in PySide6, but we have this now, and even integrate it into the PySide6 plugin.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.5.7 that I just made.

**Comment by kayhayen** [comment]
The plugin for PySide6 now does this automatically, and just like that, it runs smoothly.

The corruption happens when disconnecting slots or releasing objects with slots connected. The workaround will prevent that from happening. The disconnect is still done, but the method is kept in memory, causing a small memory leak. For now that works.
