### ISSUE TITLE
FATAL: Error, the Windows SDK must be installed in Visual Studio.

### ISSUE THREAD

**Issue by kennyhml** [Nuitka/Nuitka#2166]
Hey, so ive seen this issue like twice here, unfortunately reading through neither of them fixed it for me.

When I run py -m nuitka --version I get the following:
```
1.5.4
Commercial: None
Python: 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\Admin\AppData\Local\Programs\Python\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe (cl 14.0).
```

I installed basically all windows SDKS inside Visual Studio, its still telling me that theyre missing.
I installed nuitka via pip, python is standart cpython and installed via the official website.
I do use a venv to execute the command

I use a fair amount of packages in my project, but I dont think thta would be the problem as it compiles alright with the standart compiler, but I would like to use clang

I execute `py -m nuitka main.py --onefile --plugin-enable=pyside6 --nofollow-import-to=tkinter --windows-uac-admin --clang`

As you can see, ive tried basically every install:
![sdks](https://user-images.githubusercontent.com/106347478/231624560-2d505668-8cbd-4277-901d-5945bcea9b31.png)

**Comment by kennyhml** [comment]
Update: I tried to update nuitka to the most recent version, exact same issue.

**Comment by kayhayen** [comment]
So your version output shows you are using the community version, and your screenshot is for build tools.

**Comment by kennyhml** [comment]
@kayhayen could you clarify? And I apologize for sending the build tools, the normal tab basically looks the same though, all SDKs installed 
![sdks](https://user-images.githubusercontent.com/106347478/231683055-fdf3e83f-b58d-4905-91d2-140f901c0123.png)

> So your version output shows you are using the community version.

Indeed I am, but the projects description states:
> Visual Studio 2022 or higher on Windows, older versions will work but only supported for commercial users. 
> (the community editions work just fine)

So why is the community version not going to work?

Thank you very much for your time!

**Comment by kayhayen** [comment]
It is working fine. I notice a (2) in your screenshot title. Does that mean you have two of them installed? You might have previously bee using stuff that auto-installs things. I once tried to make Nuitka auto-install MSVC to its private parts with the correct components, but failed to do unfortunately. I think I saw these numbers in that case. You may want to configure the correct one.

**Comment by kennyhml** [comment]
Oh yea, that (2) is weird! I'll see what I can find about that.

**Comment by kayhayen** [comment]
Yes, you can waste my time.
