### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by sante85** [Nuitka/Nuitka#2167]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version

version
1.5.6
Commercial: None
Python: 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
Flavor: Unknown
Executable: c:\Python38\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64\cl.exe (cl 14.2).

  If you are not providing the full output. The issue cannot be solved and will
  be considered `invalid`. It does more than you think, and we are adding more
  all the time. We do not want to left guessing or trying things out to
  reproduce your issue.

* How did you install Nuitka and Python
I have use pip

* The specific PyPI names and versions

pip --version
pip 20.2.1 from c:\python38\lib\site-packages\pip (python 3.8)

* Also supply a Short, Self Contained, Correct, Example
inverter.py

```
import argparse
import json
import logging
import os

from version import VERSION_INVERTER

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--version", action='store_true'
    )
    args = parser.parse_args()

    if args.version:
        print(VERSION_INVERTER)
        return

```
version.py
-----------------------------------------
```
import requests

VERSION_INVERTER = "1.0.0"
```
requirements.txt
----------------------------
requests==2.28.2

* Provide in your issue the Nuitka options used

 python -m nuitka --follow-imports --standalone --onefile --run src/inverter/inverter.py

**Comment by kayhayen** [comment]
How sure are you that you have requests installed, i.e. that it works without compilation?

**Comment by kayhayen** [comment]
I of course didn't manage to reproduce.

**Comment by sante85** [comment]
If i execute with python code run right.
Requests package is installed by pip

Il gio 13 apr 2023, 10:04 Kay Hayen ***@***.***> ha scritto:

**Comment by kayhayen** [comment]
Please provide the output of `--report`.

**Comment by sante85** [comment]
I attach report file
[report.zip](https://github.com/Nuitka/Nuitka/files/11231576/report.zip)

**Comment by sante85** [comment]
in my project folder, i have venv folder "C:\Users\Desktop\PycharmProjects\pythonProject\venv\Lib\site-packages".
I set any parameter to nuikta to right search deps?

**Comment by kayhayen** [comment]
So this is from your report:

```
  <module name="src.utils.utils" kind="CompiledPythonModule" reason="Instructed by user to follow to all non-standard library modules.">
    <module_usages>
      <module_usage name="base64" finding="absolute" line="1" />
      <module_usage name="json" finding="absolute" line="2" />
      <module_usage name="logging" finding="absolute" line="3" />
      <module_usage name="os" finding="absolute" line="4" />
      <module_usage name="src.utils.requests" finding="not-found" line="6" />
```

So, this begs the question, what kind of import is done there. It seems that's the one giving you an error on line 6. It being noz found is puzzling and would be in line with requests not being installed. 

I think you may be very confused as to what Python your app runs with and which one you compile with. Your compilation was not done with the venv active. I think, I cannot help you there, you need to figure out what Python you can use to run Nuitka with. I invite you to ask PyCharm support, if they make it easy for you to not know it, they probably also should make it easy to run software within it.

**Comment by sante85** [comment]
> So this is from your report:
> 
> ```
>   <module name="src.utils.utils" kind="CompiledPythonModule" reason="Instructed by user to follow to all non-standard library modules.">
>     <module_usages>
>       <module_usage name="base64" finding="absolute" line="1" />
>       <module_usage name="json" finding="absolute" line="2" />
>       <module_usage name="logging" finding="absolute" line="3" />
>       <module_usage name="os" finding="absolute" line="4" />
>       <module_usage name="src.utils.requests" finding="not-found" line="6" />
> ```
> 
> So, this begs the question, what kind of import is done there. It seems that's the one giving you an error on line 6. It being noz found is puzzling and would be in line with requests not being installed.
> 
> I think you may be very confused as to what Python your app runs with and which one you compile with. Your compilation was not done with the venv active. I think, I cannot help you there, you need to figure out what Python you can use to run Nuitka with. I invite you to ask PyCharm support, if they make it easy for you to not know it, they probably also should make it easy to run software within it.

i have tryed to compile with Docker file. this is output report and Dockerfile. If i run file, throw "segmentation error".
I install all deps with PyPi. 
All deps are finded
[Dockerfile.release.txt](https://github.com/Nuitka/Nuitka/files/11232518/Dockerfile.release.txt)
[report.zip](https://github.com/Nuitka/Nuitka/files/11232850/report.zip)
