### ISSUE TITLE
cannot read feather file with pandas2.0/pyarrow11.0

### ISSUE THREAD

**Issue by gdementen** [Nuitka/Nuitka#2169]
* Please check whether the bug was already reported or fixed.

Not that I am aware of.

* Please check out if the develop version of Nuitka works better for you.

I haven't checked (yet) as AFAIK there isn't anything related to this problem in develop compared to 1.5.6

* Nuitka version, full Python version, flavor, OS, etc.

1.5.6
Commercial: None
Python: 3.10.10 | packaged by Anaconda, Inc. | (main, Mar 21 2023, 18:39:17) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: [...]\envs\nuitka_read_feather\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

* How did you install Nuitka and Python

conda create -n nuitka_read_feather python=3.10
conda activate nuitka_read_feather
pip install pandas pyarrow nuitka

* The specific PyPI names and versions
Nuitka==1.5.6
pandas==2.0.0
pyarrow==11.0.0

* Many times when you get an error from Nuitka, your setup may be special

Hello world works :)

* Also supply a Short, Self Contained, Correct, Example

```python
# nuitka-project: --standalone
# nuitka-project: --lto=no
import pandas as pd

print(pd.read_feather('test.feather'))
```

Test file created using the following (uncompiled) script:
```python
import pandas as pd
df = pd.DataFrame({'a': [1, 2], 'b': [3, 4]})
df.to_feather('test.feather')
```

When using Python, the result is:
```
> python nuitka_read_feather.py
   a  b
0  1  3
1  2  4
```

When using Nuitka, the result is:
```python
> nuitka_read_feather.exe
Traceback (most recent call last):
  File "[...]\NUITKA~1.DIS\nuitka_read_feather.py", line 5, in <module>
  File "[...]\NUITKA~1.DIS\pandas\io\feather_format.py", line 148, in read_feather
  File "[...]\NUITKA~1.DIS\pyarrow\feather.py", line 226, in read_feather
  File "pyarrow\array.pxi", line 830, in pyarrow.lib._PandasConvertible.to_pandas
  File "pyarrow\table.pxi", line 3990, in pyarrow.lib.Table._to_pandas
  File "[...]\NUITKA~1.DIS\pyarrow\pandas_compat.py", line 810, in table_to_blockmanager
  File "[...]\NUITKA~1.DIS\pyarrow\pandas_compat.py", line 968, in _reconstruct_index
  File "pyarrow\pandas-shim.pxi", line 126, in pyarrow.lib._PandasAPIShim.pd.__get__
  File "pyarrow\pandas-shim.pxi", line 100, in pyarrow.lib._PandasAPIShim._check_import
  File "pyarrow\pandas-shim.pxi", line 56, in pyarrow.lib._PandasAPIShim._import_pandas
```

* Note if this is a regression

This is a "regression" in the sense that reading feather files with Pandas used to work, but I assume this is a new implicit dependency in pyarrow (or maybe pandas) instead of a regression in Nuitka.

I will try to fix it when I get some time.

**Comment by gdementen** [comment]
I confirm this is not a regression in Nuitka as it works using:
```
nuitka                    1.5.6
pandas                    1.4.2
pyarrow                   8.0.0
python                    3.9.12
```

**Comment by kayhayen** [comment]
Yes, clearly something for Nuitka-watch to find in the future. Latest pandas being broken is kind of critical for Nuitka, because so many people use it.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by gdementen** [comment]
The provided test case works indeed. Thanks for the quick reaction!

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.5.7 that I just made.
