### ISSUE TITLE
[Question]  After built with Nuitka, how to execute "python.exe demo.py config.cfg"

### ISSUE THREAD

**Issue by caoxiaosheng** [Nuitka/Nuitka#2170]
Hello, i have a question

After built with Nuitka, python.exe and envs are frozen.
If i want to run "python.exe demo.py config.cfg" with subprocess and  use the frozen envs,  what can i du
```
subprocess.Popen('python.exe demo.py config.cfg')
```

Thanks

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
