### ISSUE TITLE
Splash Screen doesn't work

### ISSUE THREAD

**Issue by ThatOneShortGuy** [Nuitka/Nuitka#2177]
When using the [below command](#nuitka-options-used) to compile the below code on the new 1.5.6 version, the splash screen does not appear. I compiled the same thing on 1.4 and it worked like a charm. The `Splash.png` file is in the same directory as the [`tmp.py`](#code-used) file.

# Nuitka version
1.5.6
Commercial: None
Python: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Program Files\Python39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX64\x64\cl.exe (cl 14.3).

Nuitka installed with pip v23.1

# Code Used
### **tmp.py**
Similar to the directions in the [README.rst](https://github.com/Nuitka/Nuitka#readme).
```python
import os
import tempfile
import time

time.sleep(5)

if "NUITKA_ONEFILE_PARENT" in os.environ:
    splash_filename = os.path.join(
        tempfile.gettempdir(),
        "onefile_%d_splash_feedback.tmp" % int(os.environ["NUITKA_ONEFILE_PARENT"]),
    )

    if os.path.exists(splash_filename):
        os.unlink(splash_filename)

print("Hello World")
```

# Nuitka options used
python -m nuitka --onefile --onefile-windows-splash-screen-image="Splash.png" tmp.py

# Issues
Compiles without any issues.
When you run the `tmp.exe` produced, no splash screen appears.

**Comment by kayhayen** [comment]
Ah, this is a recent regression. When switching the onefile payload to be accesses as a resource, my favorite number was used for the resource ID, which was already used for the splash screen.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.5.7 that I just made.
