### ISSUE TITLE
Nuitka dosen't work

### ISSUE THREAD

**Issue by salahW3b** [Nuitka/Nuitka#2180]
Hello my error : 
C:\Users\kader>pip install nuitka
Requirement already satisfied: nuitka in c:\users\kader\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (1.5.6)
Requirement already satisfied: ordered-set>=4.1.0 in c:\users\kader\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from nuitka) (4.1.0)
Requirement already satisfied: zstandard>=0.15 in c:\users\kader\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from nuitka) (0.21.0)

C:\Users\kader>nuitka
'nuitka' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

C:\Users\kader>python -m nuitka --version
FATAL: Error, the Python from Windows store is not supported, check the User Manual of Nuitka .
Help me please

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
