### ISSUE TITLE
Nuitka fails to find libz on on Ubuntu 18.04

### ISSUE THREAD

**Issue by KishoreAD** [Nuitka/Nuitka#2181]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version
1.5.6
Commercial: None
Python: 3.8.13 (default, Apr 19 2022, 00:53:22) 
Flavor: Debian Python
Executable: /home/kishore/oapp/qualitycontrol/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 18.04.6
Version C compiler: /usr/bin/gcc (gcc).

* How did you install Nuitka and Python
  Installed Nuitka using pip on both windows and ubuntu.
  Python in windows has been installed using installer and in ubuntu using Deadsnakes PPA.

* Also supply a Short, Self Contained, Correct, Example
  I have tried to build the following piece of code using the command "python -m nuitka --onefile hello.py"
  def run():
    print("Hello")

  if __name__ == "__main__":
    run()
    
This has worked successfully in windows and I was able to get a hello.bin which was properly working. But, When I tried to build it on Ubuntu, I am facing the issue with following error:
Nuitka-Options:INFO: Used command line options: --onefile hello.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.5.6' on Python '3.8' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.                       
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 7 files (no progress information available).
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
scons: *** [/home/kishore/Desktop/nuitka/hello.dist/hello.bin] Error 1

* Provide in your issue the Nuitka options used
  --onefile

**Comment by kayhayen** [comment]
This should have worked before. It appears that you are missing a debian package with the zlib library. However, strange that it is not installed when Python is using it. I will have to check out a minimal environment there.

**Comment by kayhayen** [comment]
That is what I was thinking. Maybe somehow a directory necessary is not in the linker path for some reason, like I said, when Python runs, it probably loaded it no issue, so it's just a matter of providing the right directory to `LIBPATH` in Scons. I think some `dpkg -L zlib1g` or `dpkg -l zlib1g` output might shed a light on where the file is.

**Comment by KishoreAD** [comment]
Below is the response of the command:

(qualitycontrol) kishore@ubuntu:~/Desktop/nuitka$ dpkg -l zlib1g 
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                          Version                     Architecture                Description
+++-=============================================-===========================-===========================-===============================================================================================
ii  zlib1g:amd64                                  1:1.2.11.dfsg-0ubuntu2.2    amd64                       compression library - runtime

**Comment by kayhayen** [comment]
With upper case `-L` it will show the files contained.

**Comment by KishoreAD** [comment]
Please find the below info using dpkg -L zlib1g  
/.
/lib
/lib/x86_64-linux-gnu
/lib/x86_64-linux-gnu/libz.so.1.2.11
/usr
/usr/share
/usr/share/doc
/usr/share/doc/zlib1g
/usr/share/doc/zlib1g/changelog.Debian.gz
/usr/share/doc/zlib1g/copyright
/lib/x86_64-linux-gnu/libz.so.1

**Comment by kayhayen** [comment]
Then I believe `LDFLAGS="-L /lib/x86_64-linux-gnu"` ought to make it work.

**Comment by KishoreAD** [comment]
This command hasn't helped too.
(qualitycontrol) kishore@ubuntu:~/Desktop/nuitka$ LDFLAGS="-L /lib/x86_64-linux-gnu"
(qualitycontrol) kishore@ubuntu:~/Desktop/nuitka$ python -m nuitka --onefile hello.py 
Nuitka-Options:INFO: Used command line options: --onefile hello.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.5.6' on Python '3.8' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.                       
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 7 files (no progress information available).
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
scons: *** [/home/kishore/Desktop/nuitka/hello.dist/hello.bin] Error 1
(qualitycontrol) kishore@ubuntu:~/Desktop/nuitka$ dpkg -L zlib1g 
/.
/lib
/lib/x86_64-linux-gnu
/lib/x86_64-linux-gnu/libz.so.1.2.11
/usr
/usr/share
/usr/share/doc
/usr/share/doc/zlib1g
/usr/share/doc/zlib1g/changelog.Debian.gz
/usr/share/doc/zlib1g/copyright
/lib/x86_64-linux-gnu/libz.so.1

**Comment by kayhayen** [comment]
You don't know how to set environment variables unfortunately, you may have to export it, or put it in front of the command to affect that command only. Read your shell docs if that doesn't make sense to you.

**Comment by KishoreAD** [comment]
Yeah, My bad. It was a mistake. Build was successful once I installed zlib1g-dev too. Previously, I have just installed zlib1g.
Thank you for your help and I guess this need to be documented.

**Comment by kayhayen** [comment]
Yes, much like `Python.h` missing is noticed, these things are ideally reported too. I not quite get what the dev package contributes, but maybe that is because it's static or so on Debian Python. I recall there is or was code to scan for static link libraries, probably should do more names there.

**Comment by JRudransh** [comment]
Hello @kayhayen I am a python developer and I would like to contribute to this project

**Comment by kayhayen** [comment]
@JRudransh I suggest you check out the Discord specifically, and generally the `CONTRIBUTING.md` in the repo.

**Comment by kayhayen** [comment]
I saw it happen with a Container that I created recently for `Ubuntu1804.containerfile` which I will either provide for free or commercially in the future, not yet decided. Anyway, no need to keep it open anymore. I am putting it to 2.0 where the Linux container build solution for general use is maybe appearing, maybe later, but I am not tracking it here, but in roadmap I guess.

**Comment by KlimchevKonstantin** [comment]
`sudo apt install zlib1g-dev`

**Comment by filipopo** [comment]
> `sudo apt install zlib1g-dev`

Hey... I have this same issue, on Debian 12 though, zlib1g-dev is definitely in the image but nuitka didn't bundle it which I found out after I tried to run my binary on a distroless docker image and I had to copy it over, otherwise it works...

```
ARG OS_VERSION=12
FROM debian:${OS_VERSION}-slim AS build
ENV DEBIAN_FRONTEND=noninteractive

COPY updater.py .

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
      ccache \
      gcc \
      make \
      patchelf \
      pipx \
      python3-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    pipx run nuitka \
      --assume-yes-for-downloads \
      --python-flag=-OO \
      --standalone \
      --output-filename=updater-linux-amd64 \
      updater.py

FROM gcr.io/distroless/cc-debian${OS_VERSION}:latest
WORKDIR /opt/updater

COPY --from=build /lib/x86_64-linux-gnu/libz.so.1 /lib/x86_64-linux-gnu/

COPY --from=build updater.dist/* .

CMD ["./updater-linux-amd64"]
```

**Comment by kayhayen** [comment]
Nuitka doesn't copy system DLLs by default for packages, and definitely not these LSB ones.
