### ISSUE TITLE
Are there any known limitation when running a python script that got compiled with Nuitka using posix_spawn from inside a C++ script? 

### ISSUE THREAD

**Issue by loaiali** [Nuitka/Nuitka#2182]
I'm trying to launch a python script that got compiled using Nuitka3 by launching it from inside a C++ file using posix_spawn, but I keep seeing defunct ( zombified) processes, This behavior is quite new to me, previously I've launched this python script from a cmd and didn't encounter any issues

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
