### ISSUE TITLE
Support for `importlib.resources.files` to include the package files are read from is needed or else `ModuleNotFoundError` occurs.

### ISSUE THREAD

**Issue by robclewley** [Nuitka/Nuitka#2183]
```
1.6rc7
Commercial: None
Python: 3.10.8 (main, Apr 17 2023, 20:57:13) [Clang 14.0.0 (clang-1400.0.29.202)]
Flavor: pyenv
Executable: ~/.pyenv/versions/3.10.8/Library/Frameworks/Python.framework/Versions/3.10/bin/python
OS: Darwin
Arch: x86_64
Version C compiler: /usr/bin/clang (clang).
```

I'm using a pyenv build based on `env PYTHON_CONFIGURE_OPTS="--enable-framework --enable-static" pyenv install 3.10.8`

Initially installed nuitka from pip (v.1.5.6), but now directly from git source with `python setup.py install` in my pyenv, which was freshly made yesterday.

 - Hello world trivial script builds and runs fine using similar arguments to Nuitka as my problem case.
 - Hello world with 2 imports (both unused) `pygame` and `pygame_gui` -- import builds and runs fine.

 - Minimum script to reproduce my error

```
import pygame
import pygame_gui

from pygame_gui import UIManager, PackageResource

pygame.font.init()
pygame.freetype.init()
pygame.display.set_mode((800, 600), pygame.SRCALPHA)

ui_manager = UIManager((800, 600),
                            PackageResource(package='data.themes',
                                            resource='theme_2.json'))

print("hello world")
```

Command / options used and error output when running:

```
> python -m nuitka  --standalone --include-package-data=pygame_gui.data --static-libpython=no hw2.py

Nuitka-Options:INFO: Used command line options: --standalone --include-package-data=pygame_gui.data --static-libpython=no hw2.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.6rc7' on Python '3.10' commercial grade 'not installed'.
Nuitka-Plugins:INFO: pkg-resources: Injecting post-module load code for module 'pkg_resources':
Nuitka-Plugins:INFO: pkg-resources:     Registering Nuitka loader with "pkg_resources".
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: clang (clang).
Nuitka-Scons:INFO: Scons: Inherited CPPFLAGS='-I/usr/local/opt/sqlite3/include' variable.
Nuitka-Scons:INFO: Scons: Inherited LDFLAGS='-L/usr/local/opt/readline/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/sqlite3/lib' variable.
Nuitka-Scons:INFO: Backend linking program with 258 files (no progress information available).
Nuitka-Scons:INFO: Compiled 258 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 258
Nuitka-Options:INFO: Included 21 data files due to package 'pygame_gui.data' package data.
Nuitka:INFO: Keeping build directory 'hw2.build'.
Nuitka:INFO: Created binary that runs on macOS 12.6 (x86_64) or higher.
Nuitka:INFO: Successfully created 'hw2.dist/hw2.bin'.
```

I need to include the `--static-libpython=no` option otherwise nuitka complains that "Automatic detection of static libpython failed. Nuitka on pyenv should not use '--enable-shared'. Disable with '--static-libpython=no' if you don't want to install it." and I can't avoid standalone because of the data files to include.

```
> ./hw2.dist/hw2.bin
pygame 2.3.0 (SDL 2.24.2, Python 3.10.8)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
File "~/hw2.dist/hw2.py", line 10, in <module>
File "~/hw2.dist/pygame_gui/ui_manager.py", line 69, in __init__
File "~/hw2.dist/pygame_gui/core/ui_appearance_theme.py", line 79, in __init__
File "~/hw2.dist/pygame_gui/core/ui_appearance_theme.py", line 90, in _load_default_theme_file
File "~/hw2.dist/pygame_gui/core/ui_appearance_theme.py", line 650, in load_theme
SystemError: More keyword list entries (5) than format specifiers (4)
```

There are no format specifiers in the pygame_gui code at that line, and the script runs fine natively. I found a similar issue that was fixed in 2019 here: https://github.com/Nuitka/Nuitka/issues/461

These are all the dependencies for the game I'm building in this environment, although my minimally reproduced example of a problem doesn't depend on 99% of these (just `pygame-ce` and `pygame_gui` and any of their dependencies).

```
> python -m pip freeze
altgraph==0.17.3
arrow==1.2.3
asciitree==0.3.3
blis==0.7.9
cachetools==5.3.0
catalogue==2.0.8
certifi==2022.12.7
charset-normalizer==3.1.0
click==8.1.3
confection==0.0.4
contourpy==1.0.7
cycler==0.11.0
cymem==2.0.7
cytoolz==0.12.1
dicttoxml==1.7.16
exceptiongroup==1.1.1
Flask==2.2.3
Flask-Jsonpify==1.5.0
floret==0.10.2
fonttools==4.39.3
fuzzywuzzy==0.18.0
hashids==1.3.1
idna==3.4
imageio==2.27.0
iniconfig==2.0.0
itsdangerous==2.1.2
jellyfish==0.11.2
Jinja2==3.1.2
joblib==1.2.0
kiwisolver==1.4.4
langcodes==3.3.0
lazy_loader==0.2
macholib==1.16.2
MarkupSafe==2.1.2
matplotlib==3.7.1
murmurhash==1.0.9
netifaces==0.11.0
networkx==3.1
noise==1.2.2
Nuitka==1.6rc7
numpy==1.24.2
opensimplex==0.4.4
ordered-set==4.1.0
orjson==3.8.10
packaging==23.1
pandas==2.0.0
pathy==0.10.1
patsy==0.5.3
Pillow==9.5.0
pluggy==1.0.0
preshed==3.0.8
py-sim-game-engine @ file:///~/gaming/public_engine/py-sim-game-engine
pycryptodome==3.17
pydantic==1.10.7
pygame==2.3.0
pygame-ce==2.2.1
pygame-gui==0.6.8
pyinstaller==5.10.1
pyinstaller-hooks-contrib==2023.2
pyparsing==3.0.9
pyphen==0.14.0
pytest==7.3.1
python-dateutil==2.8.2
python-i18n==0.3.9
pytz==2023.3
PyWavelets==1.4.1
PyYAML==6.0
requests==2.28.2
scikit-image==0.20.0
scikit-learn==1.2.2
scipy==1.10.1
shapely==2.0.1
simplejson==3.19.1
simplerandom==0.13.5
six==1.16.0
smart-open==6.3.0
spacy==3.5.2
spacy-legacy==3.0.12
spacy-loggers==1.0.4
srsly==2.4.6
statsmodels==0.13.5
tabulate==0.9.0
textacy==0.13.0
thinc==8.1.9
threadpoolctl==3.1.0
tifffile==2023.4.12
tinyaes==1.0.4
tomli==2.0.1
toolz==0.12.0
tqdm==4.65.0
typer==0.7.0
typing_extensions==4.5.0
tzdata==2023.3
ujson==5.7.0
urllib3==1.26.15
wasabi==1.1.1
Werkzeug==2.2.3
Whoosh==2.7.4
zstandard==0.21.0
```

**Comment by robclewley** [comment]
FWIW - i checked with recent versions of nuitka from 1.1.8 and each subsequent major sub-version 1.2-1.5. Everything I tested prior to 1.5 builds but fails at runtime with:

```
Traceback (most recent call last):
  File "~/hw2.dist/hw2.py", line 10, in <module>
  File "~/hw2.dist/pygame_gui/ui_manager.py", line 69, in __init__
  File "~/hw2.dist/pygame_gui/core/ui_appearance_theme.py", line 62, in __init__
  File "~/hw2.dist/pygame_gui/core/ui_font_dictionary.py", line 127, in __init__
  File "~/hw2.dist/pygame_gui/core/ui_font_dictionary.py", line 155, in _load_default_font
  File "~/hw2.dist/pygame_gui/core/utility.py", line 400, in load
TypeError: unsupported operand type(s) for /: 'nuitka_resource_reader_files' and 'str'
```

**Comment by kayhayen** [comment]
The support for pygame should be pretty good. The Nuitka-Python community for our static no DLL binary builds is pretty heavy user of that, but this `pygame_gui` which has the issue.

In your example I think it might be missing data files. It won't run with Python for me.

**Comment by robclewley** [comment]
> It won't run with Python for me.

I see that I didn't specify that the test would need the `pygame_gui_examples/data` files on your local machine to test, I apologize. You would need the contents of this folder from where the python script resides: https://github.com/MyreMylar/pygame_gui_examples/tree/master/data

In any case, there are no missing data files from the `pygame_gui` package in the build. In fact, I separated out the relevant lines referenced in the `SystemError` in the `pygame_gui` code (L650 of `pygame_gui/core/ui_appearance_theme.py`), had it print out the full path to the files it was about to try to load, and re-ran the build. The build works, as before, and prints out the path `~/pygame_gui_examples/hw2.dist/pygame_gui/data/default_theme.json` (edited out my irrelevant home path) which I can confirm is a file that is indeed copied in to precisely that location inside the package. That is a core pygame_gui package data file, not one from the local folder anyway, so the absent local files are a red herring. Again, sorry for causing confusion there.

For your future reference, a full nuitka command that I verified correctly pulls in both the pygame_gui package data files _and_ local data files on my machine is

```
python -m nuitka  --standalone --include-package-data=pygame_gui.data --include-data-dir=data=./data --static-libpython=no hw2.py
```

Thanks for taking a look at this.

**Comment by robclewley** [comment]
I spent some time talking to the pygame_gui author and working on deriving a truly minimal demonstration of the bug based on what's happening inside pygame_gui where this was failing.

It appears that two simple conditions are necessary.

1) To import the package from site_packages (not local to script) that has a desired data file, even if you don't use anything from the import. (This condition is _not_ met if you import any other package instead.)
2) To use the `errors='strict'` option in the file open.

Here's my `test.py` file.

```
from importlib.resources import files
import test_package

fpp = "test_package"
fpr = "test_file.txt"

package_file = files(fpp) / fpr
print(package_file)

# this fails, but only if you `import test_package`
# (this is basically the exact line the SystemError indicates from pygame_gui example I first posted)
#open_file = package_file.open('r', encoding='utf-8', errors='strict')

# this fails, but only if you `import test_package`
#open_file = package_file.open('r', errors='strict')

# this always succeeds
#open_file = package_file.open('r', encoding='utf-8')

# this always succeeds
open_file = package_file.open('r')

print(open_file.read())
```

and you'll need a test package installed in site packages. Mine is literally just:

```
test_package:
  - __init__.py (empty)
  - test_file.txt
```

where the text file just contains any string.

I ran the command  `python -m nuitka  --standalone --include-package-data=test_package --static-libpython=no test.py`

Failing output when executing the bin:
```> test.dist/test.bin
~/test.dist/test_package/test_file.txt
Traceback (most recent call last):
  File "~/test.dist/test.py", line 17, in <module>
SystemError: More keyword list entries (5) than format specifiers (4)
```

Here's the nuitka build output for a failing case:
```
Nuitka-Options:INFO: Used command line options: --standalone --include-package-data=test_package --static-libpython=no test.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.5.6' on Python '3.10' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: clang (clang).
Nuitka-Scons:INFO: Scons: Inherited CPPFLAGS='-I/usr/local/opt/sqlite3/include' variable.
Nuitka-Scons:INFO: Scons: Inherited LDFLAGS='-L/usr/local/opt/readline/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/sqlite3/lib' variable.
Nuitka-Scons:INFO: Backend linking program with 7 files (no progress information available).
Nuitka-Scons:INFO: Compiled 7 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 7
Nuitka-Options:INFO: Included data file 'test_package/test_file.txt' due to package 'test_package' package data.
Nuitka:INFO: Keeping build directory 'test.build'.
Nuitka:INFO: Created binary that runs on macOS 12.6 (x86_64) or higher.
Nuitka:INFO: Successfully created 'test.dist/test.bin'.
```

and slightly different for a passing case:
```
Nuitka-Options:INFO: Used command line options: --standalone --include-package-data=test_package --static-libpython=no test.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.5.6' on Python '3.10' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: clang (clang).
Nuitka-Scons:INFO: Scons: Inherited CPPFLAGS='-I/usr/local/opt/sqlite3/include' variable.
Nuitka-Scons:INFO: Scons: Inherited LDFLAGS='-L/usr/local/opt/readline/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/sqlite3/lib' variable.
Nuitka-Scons:INFO: Backend linking program with 7 files (no progress information available).
Nuitka-Scons:INFO: Compiled 7 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 6
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 1
Nuitka-Options:INFO: Included data file 'test_package/test_file.txt' due to package 'test_package' package data.
Nuitka:INFO: Keeping build directory 'test.build'.
Nuitka:INFO: Created binary that runs on macOS 12.6 (x86_64) or higher.
Nuitka:INFO: Successfully created 'test.dist/test.bin'.
```

although the cache hits and misses seem to vary a little on different runs.

**Comment by robclewley** [comment]
I found some more helpful info for something I expect is closely related.  The following `test.py` script fails on a data file referenced using a dot in a sub-dir, depending on whether I `import test_package`. Minor adjustment to the test package test package I introduced in the previous message:

```
test_package:
  - __init__.py (empty)
  - test_file.txt (irrelevant for this test)
  - data/
      - test_file2.txt
```

Presence of an empty `__init__.py` inside `test_package/data` makes no difference to the outcome.

```
from importlib.resources import files, as_file
# fails only if this import is present
import test_package

# note the `.data` (doesn't fail on pulling in files from `test_package` directory)
f_pack = files("test_package.data")
pr = f_pack / 'test_file2.txt'

print(pr)

with pr.open('r', encoding='utf-8') as fp:
    fp.read()

print("hello world")
```

using `python -m nuitka --standalone --include-package-data=test_package --static-libpython=no  test.py` or fails the same with the variant option `--include-package-data=test_package.data` .

Nuitka output:
```
Nuitka-Options:INFO: Used command line options: --standalone --plugin-enable=pylint-warnings --include-package-data=test_package --static-libpython=no test.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.5.6' on Python '3.10' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: clang (clang).
Nuitka-Scons:INFO: Scons: Inherited CPPFLAGS='-I/usr/local/opt/sqlite3/include' variable.
Nuitka-Scons:INFO: Scons: Inherited LDFLAGS='-L/usr/local/opt/readline/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/sqlite3/lib' variable.
Nuitka-Scons:INFO: Backend linking program with 7 files (no progress information available).
Nuitka-Scons:INFO: Compiled 7 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 7
Nuitka-Options:INFO: Included data file 'test_package/.DS_Store' due to package 'test_package' package data.
Nuitka-Options:INFO: Included data file 'test_package/test_file.txt' due to package 'test_package' package data.
Nuitka-Options:INFO: Included data file 'test_package/data/test_file2.txt' due to package 'test_package' package data.
Nuitka:INFO: Keeping build directory 'test.build'.
Nuitka:INFO: Created binary that runs on macOS 12.6 (x86_64) or higher.
Nuitka:INFO: Successfully created 'test.dist/test.bin'.
```

The error is

```
Traceback (most recent call last):
  File "~/test.dist/test.py", line 4, in <module>
  File "~/test.dist/importlib/_common.py", line 22, in files
  File "~test.dist/importlib/_common.py", line 66, in get_package
  File "~/test.dist/importlib/_common.py", line 57, in resolve
  File "importlib.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'test_package.data'
```

**Comment by kayhayen** [comment]
I am not sure, why `test_package.data`should be included as a package. Right now, nothing is importing it. In a sense, the package should probably be considered "imported" by the `files("test_package.data")` and other calls. Right now, this doesn't trigger what is called recursion. More often than not, packages are using their own data files. Calling the directory `data` a package on the Python level is un-optimal in some way, but surely legit in Python3 for a while now. 

I am not even sure `--include-package=test_package.data` would work, but it should be the workaround. Please try it and let me know if it laughs in your face, saying does not exist. Namespace packages do work however, so it ought to be good. If that is an issue, the `__init__.py` will make it work. 

Adding recursion to the metadata resource nodes ought to be simple actually, and is of course very warranted. It will be a matter of how to do it cleanly. I am hoping to smuggle this in soon. Right now I am in lock down for 3.11 support and 1.6 release, but it could likely become a hotfix of 1.6 too.

**Comment by kayhayen** [comment]
So, I quickly checked and `files` is currently not a dedicated node in Nuitka. Unlike e.g. `read_text` and what not. It could of course be added, but that is probably much less hotfix-ish and might mean, I need to add that before 1.6 release just to be able to add this as a place to add the dependency. Using `read_text` or `read_binary` would be better, and I might go for those first. If this is supposed to be generic, well, then of course, `files` is required. But just to note the workaround with Nuitkas as it is now.

**Comment by robclewley** [comment]
Thanks, the workaround works great.

**Comment by kayhayen** [comment]
But of course, I really want no workarounds to be necessary with Nuitka. In the future version, it won't be once I find the time and risk tolerance to improve this.

**Comment by kayhayen** [comment]
So, I have been implementing this, I will add the factory tag to it right now, but it may only appear there during the day, since I am working on Debian package building improvements, and the branch state is messy now. But it will be in 1.7, and this works now:

```
# nuitka-project: --standalone
# nuitka-project: --noinclude-default-mode=error

import importlib.resources

print("importlib.resources.files gives value", importlib.resources.files("jsonschema"))
```

This contributes a module usage of the compile time recognized call, and also makes that call hard now, but still resolved at runtime. But with `jsonschema` included, and the fact that it does have automatic data files in our package config, this just works.

I do not want to make the detection of this with lack of included data files yet, just wanted to get rid of a common and confusing error source. The lack of data files, ought still be obvious somehow.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working. But beware it may not yet be actually there immediately yet.

**Comment by kayhayen** [comment]
Part of the current pre-release and will be part of 1.7 release.

**Comment by kayhayen** [comment]
Part of the 1.7 release I just made.
