### ISSUE TITLE
Nuitka to be improved a lot for file size !

### ISSUE THREAD

**Issue by gaamaaresosa** [Nuitka/Nuitka#2186]
Today I explored Nuitka for more than 8 hours by taking simple 50 lines of test code.
With just 2 standard libs: 1) import sys, 2) import os

A) 
With simple standard build the output is **7MB** size binary
`
sudo python3 -m nuitka NuitkaTest.py
`

B)
With --onefile option  the size is **25MB** (35 Mins build time)
`
sudo python3 -m nuitka --onefile NuitkaTest.py
`

That too the --onefile build showing
**"Bus error"**
Which I got it fixed from PyInstller last week with 5.10.1
https://github.com/pyinstaller/pyinstaller/issues/7566

C) 
When I examined the output exe, I see that was not pure machine code native binary.
Still using Python at runtime. May be still that using bytecode ?

My requirement was making 100% machine code on native binary for security.
But I am upset.
Please some one correct me if I did something wrong.

D) 
Finally I build same NuitkaTest.py file with Cython.
True 100% machine code on native binary.
Output binary file size is **203KB** only

**HOW DID I TEST THE OUTPUT:**
On the source code I wrote a line
print(sys.executable)
`sudo python3 NuitkaTest.py`
Result = /usr/bin/python3
That means its using Python intrepreter to execuite the code.

**After compling the code with Nuitka and run the binary:**
`sudo ./NuitkaTest`
Result = /usr/bin/python3
That means its still using Python intrepreter to execuite the binary.

**Same  NuitkaTest.py build with cython and run the binary:**
`sudo ./NuitkaTest`
Result = /usr/bin/NuitkaTest
That means good bye to Python and execuiting the binary via direct CPU.
This is what I wanted.

**But still Nuitka compiling and bundling is very easy.**

NOTE: 
I was so happy seeing  Nuitka automatically adding imports and making *.c files 
Then using CGG to compile.
But what is wrong with Nuitka to make huge output size ?
I don't why Numpy and other bundles automatically added by Nuitka for my simple 50 lines source code.

Same sequence I was doing with Cython too.
And Cython + CGG made tiny output file.

**Comment by kayhayen** [comment]
I don't see sufficient information either.

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
