### ISSUE TITLE
nuitka exe build from av library, building success but got  No module named 'av.buffer'

### ISSUE THREAD

**Issue by AnhTalent** [Nuitka/Nuitka#2191]
I'm writing a code to transfer a file using the aiortc module.
aiortc imports av package for video or audio streaming.
I successfully made the code and in the python virtual environment, the code transfer the datastream without any issue.

But once I built the exe using nuitka,  I got the following error from running the exe console:
...
File "av\audio\frame.pyx", line 1, in init av.audio.frame
  File "av\frame.pyx", line 1, in init av.frame
ModuleNotFoundError: No module named 'av.buffer'
...

my environment is :
nuitka : 1.5.6
aiortc : 1.5.0
av : 9.2.0

I hope an urgent help for this issue.

Best,

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
