### ISSUE TITLE
Nuitka build for av package, executable returns av modules not found error

### ISSUE THREAD

**Issue by AnhTalent** [Nuitka/Nuitka#2192]
The compiled the attached sample code, running the generated executable throws the following error:
Traceback (most recent call last):
  File "C:\Users\hotdog\Desktop\Last_trying\a.dist\a.py", line 1, in <module>
  File "C:\Users\hotdog\Desktop\Last_trying\a.dist\av\__init__.py", line 59, in <module av>
  File "C:\Users\hotdog\Desktop\Last_trying\a.dist\av\audio\__init__.py", line 1, in <module av.audio>
  File "av\audio\frame.pyx", line 1, in init av.audio.frame
ModuleNotFoundError: No module named 'av.frame'

Running the original python script file has no error, but when I run the exe file built by nuitka it outputs the error on av package modules.
________________________________________
**Nuitka version (installed via pip 23.1)**
1.5.6
Commercial: None
Python: 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\hotdog\Desktop\Last_trying\vp\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\cl.exe (cl 14.1).
Relevant python modules
av==9.2.0
ordered-set==4.1.0
zstandard==0.21.0
________________________________________
**Code Used**
av_usage.py
import av
print(av.buffer)
________________________________________
**Nuitka options used**
nuitka --standalone ./av_usage.py

**Comment by kayhayen** [comment]
Thanks, much better.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by AnhTalent** [comment]
I tested and could build the av package successfully with the factory version.

Thanks!

**Comment by dryarullin** [comment]
@kayhayen nuitka --version
1.5.7
Commercial: None
Python: 3.11.0 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:21) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: D:\Soft\Miniconda3\envs\pyqt_new\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\bin\HostX64\x64\cl.exe (cl 14.3).

**Comment by kayhayen** [comment]
Yes, you are correct. I meant to include it in the hotfix, but somehow didn't happen. So this will be in 1.6 and is on develop now only, but I am hoping to make 1.6 happen anyway. There won't be more hotfixes of 1.5 now unless something critical happens.

**Comment by kayhayen** [comment]
This is part of the stable release 1.6 that I just made.
