### ISSUE TITLE
``FATAL: Error, 'depends.exe' failed to produce expected output.`` using tobix/pywine Docker container

### ISSUE THREAD

**Issue by 0ctopirate** [Nuitka/Nuitka#2194]
Using simplest possible hello world program, ``print('Hello World!')``, fails using ``wine python -m nuitka --standalone test.py`` with ``FATAL: Error, 'depends.exe' failed to produce expected output.``. Without the standalone option it works fine and the output binary prints correctly, but of course no dependencies are included.

I am currently using the ``tobix/pywine`` container (run with ``docker run --rm -it --entrypoint /bin/sh tobix/pywine``).

Trying to execute depends.exe manually with ``/opt/wineprefix/drive_c/users/root/AppData/Local/Nuitka/Nuitka/Cache/downloads/depends/x86_64/depends.exe`` results in no output with an exit code of ``53``. Not sure what that means but wine is definitely set as the interpreter so the problem isn't that it's being run without wine.

* Nuitka version, full Python version, flavor, OS, etc.
```
# wine python -m nuitka --version
1.5.6
Commercial: None
Python: 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).
```

* How did you install Nuitka and Python

Python installer is wget and run in wine, details in the dockerfile (https://github.com/webcomics/pywine/blob/main/Dockerfile). Nuitka installed with ``wine pip install nuitka``.

I understand this may not be a supported usecase but I'm not seeing any immediately obvious reason it shouldn't work...

**Comment by kayhayen** [comment]
If you cannot get `depends.exe` to work, you are lost. My suspect would be that wine libraries are not all proper PE files, and wouldn't run on Windows anyway. Things could probably be hacked in such a fashion to circumvent that issue, but I do not care enough to even try.

**Comment by kayhayen** [comment]
Not sure if the 32 and 64 bit versions can do everything the other version can. I didn't expect them to be able to look at 64 bit binaries, but if that's wrong, we could detect wine probably somehow and special case that indeed.
