### ISSUE TITLE
scipy not work in pyd when called by C++

### ISSUE THREAD

**Issue by mosyang** [Nuitka/Nuitka#2195]
Nuitka 1.5.6 with pip
Scipy 1.9.1 with pip
Python 3.9.13 with Miniforge3_4.13.0-1
Platform: Windows Server 2019
C++14 Standard
nuitka compile to mymodule.pyd:  python -m nuitka --output-dir=out --module mymodule.py
```python
import scipy
def myfunction():
    print(123)
``` 
How to load pyd
```c++
    Py_Initialize();
    PyObject* pmodule = PyImport_ImportModule("mymodule");
    PyObject* pfunction = PyObject_GetAttrString(pmodule, "myfunction");
    Py_Finalize();
``` 

Description:
     When I compiled mymodule.py to mymodule.cp39-win_amd64.pyd, I can use python to load pyd call myfunction() perfectly.  However in C++, I used the above code to call myfunction, I got exception.
```c++
Exception thrown at 0x00007FFD46536806 (python39.dll) in mymodule.exe: 0xC0000005: Access violation reading location 0x0000000000000008.
``` 
When C++ load pyd(contains scipy import), it throws exception like the above.
If I removed: import scipy from the mymodule.py then compile again, C++ can load pyd and work well.  
It seems that scipy does not work in pyd when pyd is called in C++ environment.   In this case, numpy and opencv are good.

**Comment by kayhayen** [comment]
Your information is only a subset of the information the commands listed in the issue template output. Sadly.

Nuitka does a lot to be able to run extension modules happily, just like Python. If you code and environment fits that, I do not have time or inclination to debug. Feel free to bisect how much of Nuitka main program you need to make your code work too.
