### ISSUE TITLE
Tensorflow: FATAL: Error, failed to find path bazel-out/darwin_arm64-opt/bin/tensorflow/core/platform/lib_cpu_feature_guard.so_ccsharedlib.so

### ISSUE THREAD

**Issue by Josh596** [Nuitka/Nuitka#2197]
`python -m nuitka --version`
```
1.6rc7
Commercial: None
Python: 3.8.10 (v3.8.10:3d8993a744, May  3 2021, 09:09:08) 
Flavor: CPython Official
Executable: /Users/Josh/Desktop/Work-Stuff/Tools/.venv/bin/python
OS: Darwin
Arch: arm64
Version C compiler: /usr/bin/clang (clang).
```
*Full output*
```
Nuitka-Options:INFO: Used command line options: --standalone --disable-console --company-name=DesignGecko --product-name=Tools --product-version=1.9.1 --file-description=Tools --macos-app-version=1.9.1 --include-data-files=image_operations/enhance/upscale/*.pb=image_operations/enhance/upscale/ --include-data-files=image_operations/bgremove/u2net.pth=image_operations/bgremove/ --nofollow-import-to=torchaudio --macos-app-mode=gui --macos-app-name=Tools --macos-app-icon=icons/toolsicon.ico --macos-create-app-bundle --enable-plugin=pyside6 --nofollow-import-to=tkinter --assume-yes-for-download --run Tools.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.6rc7' on Python '3.8' commercial grade 'not installed'.
Nuitka-Plugins:INFO: pyside6: Injecting post-module load code for module 'PySide6.QtCore':
Nuitka-Plugins:INFO: pyside6:     Setting Qt library path to distribution folder. We need to avoid loading target
Nuitka-Plugins:INFO: pyside6:     system Qt plugins, which may be from another Qt version.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka-Plugins:INFO: pkg-resources: Injecting post-module load code for module 'pkg_resources':
Nuitka-Plugins:INFO: pkg-resources:     Registering Nuitka loader with "pkg_resources".
Nuitka-Plugins:INFO: implicit-imports: Injecting pre-module load code for module 'torch.jit._state':
Nuitka-Plugins:INFO: implicit-imports:     According to Yaml configuration.
Nuitka:INFO: Completed Python level compilation and optimization.               
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.    
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: clang (clang).
Nuitka-Scons:INFO: Backend linking program with 4289 files (no progress information available).
Nuitka-Scons:INFO: Compiled 4289 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 4287
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 2
Nuitka-Postprocessing:INFO: File 'icons/toolsicon.ico' is not in macOS icon format, converting to it.
Nuitka-Options:INFO: Included data file 'image_operations/enhance/upscale/EDSR_x3.pb' due to specified data file 'image_operations/enhance/upscale/*.pb=image_operations/enhance/upscale/' on command line.
Nuitka-Options:INFO: Included data file 'image_operations/enhance/upscale/EDSR_x4.pb' due to specified data file 'image_operations/enhance/upscale/*.pb=image_operations/enhance/upscale/' on command line.
Nuitka-Options:INFO: Included data file 'image_operations/enhance/upscale/ESPCN_x2.pb' due to specified data file 'image_operations/enhance/upscale/*.pb=image_operations/enhance/upscale/' on command line.
Nuitka-Options:INFO: Included data file 'image_operations/enhance/upscale/FSRCNN_x3.pb' due to specified data file 'image_operations/enhance/upscale/*.pb=image_operations/enhance/upscale/' on command line.
Nuitka-Options:INFO: Included data file 'image_operations/enhance/upscale/FSRCNN_x4.pb' due to specified data file 'image_operations/enhance/upscale/*.pb=image_operations/enhance/upscale/' on command line.
Nuitka-Options:INFO: Included data file 'image_operations/enhance/upscale/LapSRN_x8.pb' due to specified data file 'image_operations/enhance/upscale/*.pb=image_operations/enhance/upscale/' on command line.
Nuitka-Options:INFO: Included data file 'image_operations/bgremove/u2net.pth' due to specified data file 'image_operations/bgremove/u2net.pth=image_operations/bgremove/' on command line.
Nuitka-Plugins:INFO: data-files: Included data file 'Crypto/Util/.keep_dir.txt' due to empty dir needed for 'Crypto.Util._raw_api'.
Nuitka-Plugins:INFO: data-files: Included data file 'certifi/cacert.pem' due to package data for 'certifi'.
Nuitka-Plugins:INFO: matplotlib: Included 182 data files due to package data for 'matplotlib.
Nuitka-Plugins:INFO: matplotlib: Included data file 'matplotlib/mpl-data/matplotlibrc' due to updated matplotlib config file with backend to use.
Nuitka-Plugins:INFO: data-files: Included data file 'skimage/io/_plugins/fits_plugin.ini' due to package data for 'skimage'.
Nuitka-Plugins:INFO: data-files: Included 30 data files due to package data directory 'data' for 'skimage'.
Nuitka-Plugins:INFO: data-files: Included data file 'skimage/feature/orb_descriptor_positions.txt' due to package data for 'skimage.feature._orb_descriptor_positions'.
Nuitka-Plugins:INFO: data-files: Included data file 'torch/bin/protoc' due to package data directory 'bin' for 'torch'.
Nuitka-Plugins:INFO: data-files: Included data file 'torch/bin/protoc-3.13.0.0' due to package data directory 'bin' for 'torch'.
Nuitka-Plugins:INFO: data-files: Included data file 'torch/bin/torch_shm_manager' due to package data directory 'bin' for 'torch'.
Nuitka-Plugins:INFO: data-files: Included 7884 data files due to package data directory 'include' for 'torch'.
Nuitka-Plugins:INFO: pyside6: Including Qt plugins 'iconengines,imageformats,platforms,styles,tls' below 'PySide6/qt-plugins'.
Nuitka-Plugins:INFO: dll-files: Found 1 file DLLs from tensorflow installation.
Nuitka-Plugins:INFO: dll-files: Found 1 file DLLs from tensorflow.lite.experimental.microfrontend.python.ops.audio_microfrontend_op installation.
Nuitka-Plugins:INFO: dll-files: Found 6 files DLLs from torch installation.
FATAL: Error, failed to find path bazel-out/darwin_arm64-opt/bin/tensorflow/core/platform/lib_cpu_feature_guard.so_ccsharedlib.so (resolved DLL to bazel-out/darwin_arm64-opt/bin/tensorflow/core/platform/lib_cpu_feature_guard.so_ccsharedlib.so) for /Users/Josh/Desktop/Work-Stuff/Tools/.venv/lib/python3.8/site-packages/tensorflow/core/platform/_cpu_feature_guard.so, please report the bug.
```
* How did you install Nuitka and Python
Installed using pip into a virtualenv

* The specific PyPI names and versions
  > python -m pip freeze
I only displayed the libraries I believe are important
```
grpcio==1.49.1
h5py==3.7.0
idna==3.4
imageio==2.22.1
importlib-metadata==5.0.0
keras==2.9.0
keras-nightly==2.11.0.dev2022100307
Keras-Preprocessing==1.1.2
Nuitka @ https://github.com/Nuitka/Nuitka/archive/develop.zip
numba==0.56.2
numpy==1.23.3
oauthlib==3.2.1
opencv-contrib-python==4.6.0.66
opencv-python==4.6.0.66
PyScreeze==0.1.28
PySide6==6.5.0
PySide6-Addons==6.5.0
PySide6-Essentials==6.5.0
python-dateutil==2.8.2
requests==2.28.1
requests-oauthlib==1.3.1
rsa==4.9
scikit-image==0.19.3
scipy==1.9.1
shiboken6==6.5.0
tensorboard==2.9.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow-estimator==2.9.0
tensorflow-macos==2.9.2
tensorflow-metal==0.5.1
termcolor==2.0.1
torch==1.12.1
torchaudio==0.12.1
torchvision==0.13.1
```

* Also supply a Short, Self Contained, Correct, Example
```
import tensorflow._api.v2.compat.v1 as tf
from tensorflow.python.platform import gfile

print(tf.version)
```

* Provide in your issue the Nuitka options used
```
script_name="Tools.py"
product_name="Tools"
product_version="1.9.1"
company_name="ToolsTest"

python -m nuitka \
--standalone \
--disable-console \
--company-name="$company_name" \
--product-name="$product_name" \
--product-version="$product_version" \
--file-description="$product_name" \
--macos-app-version="$product_version" \
--include-data-files=image_operations/enhance/upscale/*.pb=image_operations/enhance/upscale/ \
--include-data-files=image_operations/bgremove/u2net.pth=image_operations/bgremove/ \
--nofollow-import-to=torchaudio \
--macos-app-mode=gui \
--macos-app-name=Tools \
--macos-app-icon=icons/toolsicon.ico \
--macos-create-app-bundle \
--enable-plugin=pyside6 \
--nofollow-import-to=tkinter \
--assume-yes-for-download \
--run \
"$script_name"
```

**Comment by kayhayen** [comment]
Is this a self-compiled version of Torch, what is bazel doing for you there. Either way it appears to be a bug of the DLL scanner of macOS. The filename `lib_cpu_feature_guard.so_ccsharedlib.so` looks kind of suspicous to me. Also can you confirm or deny that the file actually exists? I somehow get the vibes that it might be that the DLL scan there kind of prefers to have a `.dylib`. Can you provide the listing of the `lib` folder in the `torch` package there.

**Comment by Josh596** [comment]
1. It's not a self-compiled version of Torch
2. I initially believed it was an issue with tensorflow.
3. Yes, the file `lib_cpu_feature_guard.so_ccsharedlib.so` exists in site-packages/tensorflow/core/platform
4. And the file `_cpu_feature_guard.so` also exists in site-packages/tensorflow/core/platform
5. Listings of the lib folder in torch package
```
libc10.dylib
libshm.dylib
libtorch_cpu.dylib
libtorch_global_deps.dylib
libtorch_python.dylib
libtorch.dylib
```

**Comment by kayhayen** [comment]
Ok, I will look into that, absolutely looks like there is no reason. I am suspecting the `.so` suffix is an issue here. This is not torch2, so I would expect it to work, but alas not the case.

**Comment by Josh596** [comment]
I was wondering if purchasing a Nuitka commercial package could potentially speed up the fix. If so, which package would be the best fit for my needs? Thank you.

**Comment by kayhayen** [comment]
The priority package is designed for that. With the full package, you get a discount on the commercial package by combining them, which is recommended for any substatial use of Nuitka by a company.

https://nuitka.net/doc/commercial.html#pricing

And yes, priority would change everything of course.

**Comment by kayhayen** [comment]
So, I started to look into this. I noticed that this is not the newest version, but there is no hope that updating will make things break less. I however, do not find `tensorflow-macos==2.9.2` due to arch issues. It appears I wasn't using arm64 with my installation. So I believe this is somehow about the arches now. My 3.8.9 appears to not be a universal build, I will correct that, and then I should be able to see this as well.

**Comment by Josh596** [comment]
I tried what you suggested and upgraded tensorflow-macos and tensorflow-metal to the latest versions (`tensorflow-macos==2.11.0`). The error I was getting before is no longer happening. However, I'm still getting a FATAL: Error saying that it couldn't find the path ... about another package(`protobuf`, and its dependency `google`) related to tensorflow. Is it best to open a new issue or continue discussing this here?

**Comment by kayhayen** [comment]
I think it's a problem of mixed arch installation of packages, that I would still need to nail down. If you report the new error here as well, that would be good. I didn't immediately succeed in reproducing that one. Nuitka is apparently somehow too strict with arches. Can you try limiting the arch to arm64 or x86_64 with `--macos-target-arch`, that should change things.

**Comment by kayhayen** [comment]
@Josh596 just to be clear, porting to latest versions is not required, and not even recommended. Typcially newer versions are only more broken with Nuitka, because e.g. the latest versions needs a fix, and that was not yet done. That is why I said "there is no hope". However, it could have been that PyPI packages were built more robust, but apparently not, or maybe they are, but other packages like the one mentioned, still have the same issue. Since Nuitka means to be compatible, we need to find and fix it, if only to give a better error message.

**Comment by kayhayen** [comment]
When I am trying that requirements list lith M1, I get

> ERROR: Could not find a version that satisfies the requirement tensorflow-macos==2.9.2 (from versions: none)
> ERROR: No matching distribution found for tensorflow-macos==2.9.2

I am trying with x86_64 now, but can you try setting up a new arm64 venv, because these requirements are uninstallable for me.

**Comment by kayhayen** [comment]
Hm, my bad, I forgot, I think that I am on a x86_64 CPython there, which I knew I would have to update.

**Comment by kayhayen** [comment]
And it seems, that changing versions in an existing virtualenv is not at all working with any level of tensorflow involvement, but I got the example to run at least.

**Comment by kayhayen** [comment]
I managed to reproduce it. It seems torchaudio links again DLLs from torch, which is of course nothing too illegal. We have ways to allow that, but my first attempts didn't immedaitely work, but I will get that surely.

**Comment by kayhayen** [comment]
So, I found the issue with torchaudio there, and this DLL now works, but it then runs into another one:

> FATAL: Error, failed to find path @rpath/libavdevice.58.dylib (resolved DLL to /Users/hayen/test/tf_issue/lib/python3.8/site-packages/torchaudio/libavdevice.58.dylib) for /Users/hayen/test/tf_issue/lib/python3.8/site-packages/torchaudio/_torchaudio_ffmpeg.so from torchaudio, please report the bug.

And this one refers to a file that just doesn't exist. The is very similar to what we recently did for PySide6 which also contains components that do not work. We added an interface that would cause `_torchaudio_ffmpeg.so` to be ignored, since it could not possibly load. Right now this one is attached to a concrete plugin, but the DLL plugin could do it from Yaml configuration, and then this will be easy to add, we do not currently need a plugin for anything tensorflow and torch anymore, and I would like to keep it that way of course.

**Comment by kayhayen** [comment]
So, I did the reactoring, and added config for the missing DLL to be acceptable, however next up we have this here:

> FATAL: Error, failed to find path bazel-out/darwin_arm64-opt/bin/tensorflow/core/platform/lib_cpu_feature_guard.so_ccsharedlib.so (resolved DLL to bazel-out/darwin_arm64-opt/bin/tensorflow/core/platform/lib_cpu_feature_guard.so_ccsharedlib.so) for /Users/hayen/test/tf_issue/lib/python3.8/site-packages/tensorflow/core/platform/_cpu_feature_guard.so from 'tensorflow', please report the bug.

I have seen this plenty of times, the bazel-out has lead me to believe, I am seeing private builds of PyPI packages. Now this DLL does exist. It is in `lib/python3.8/site-packages/tensorflow/core/platform/lib_cpu_feature_guard.so_ccsharedlib.so` and now I am very confused as to what this tells us. It is just in the same directory, not using `@loader_path` or `@rpath`.

I need to read some docs for macOS DLL resolution now, maybe that is a fallback being used, then we would of course have to support that. Not sure though, if `@rpath` would be the default or `@loader_path`, both could be true. Or maybe it doesn't work at all. The name rings a bell, it also may be Win32 specific from my memory, there was at least code that treats it differently there.

**Comment by kayhayen** [comment]
Ah, the pre-loading of said DLL is done on non-Win32 using ctypes, so this is definitely being used by tensorflow, and that bazel-out crap is just poor packaging of theirs.

**Comment by kayhayen** [comment]
So, macOS loads the DLL, but not the DLL that was not found. I moved the DLL that I located via ´find` away, and tensorflow still works and loads correctly. Our current mechanism may therefore be wrong in not including the using DLL, e.g. with `torchaudio` as DLLs can be loaded. Maybe the compatibility version allows that, not sure:

> bazel-out/darwin_arm64-opt/bin/tensorflow/core/platform/lib_cpu_feature_guard.so_ccsharedlib.so (compatibility version 0.0.0, current version 0.0.0)

I would be interesting, what that DLL could be for. Asking upstream tensorflow would be interesting. For now, I think paths that are relative paths and not found, we should ignore them. At the same time, relative paths should probably try and resolve like this `resolved_path = os.path.join(binary_filename, path)` rather than just using `path`. For absolute paths that changes nothing, for relative paths it would, but I am not sure, that is legal anyway, so I am not doing that now.

**Comment by kayhayen** [comment]
Ok, and with this, at least the specific version set you provided works. I will try and update to the other set given, and "latest" well now.

**Comment by Josh596** [comment]
Tested with the factory branch, and it works perfectly.

**Comment by kayhayen** [comment]
This is part of the stable release 1.6 that I just made.
