### ISSUE TITLE
Onefile not run, but --run run right

### ISSUE THREAD

**Issue by sante85** [Nuitka/Nuitka#2198]
Good morning,

I have tested your snipped code in two configurations:

## Configurations
```
python3.9 -m nuitka --follow-imports --report=report.xml --unstripped --onefile --standalone test/snippet.py

python3.9 -m nuitka --report=report.xml --follow-imports --trace-execution --debug --run --unstripped --debugger  test/snippet.py
```

Second run right, first throw a segmentation fault.
Docker image used to build and test is: 
```
FROM debian:stable-slim
```

## Nuikta version
```
1.5.7
Commercial: None
Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
Flavor: Debian Python
Executable: /usr/bin/python3.9
OS: Linux
Arch: x86_64
Distribution: Debian 11
Version C compiler: /usr/bin/gcc (gcc).
```
-----------------------------------------------------
## Source code
```
def talk(message):
    return "Talk " + message


def main():
    print(talk("Hello World"))


if __name__ == "__main__":
    main()
```
I attach code and report.

Best regards
[report.zip](https://github.com/Nuitka/Nuitka/files/11335527/report.zip)
[snippet.zip](https://github.com/Nuitka/Nuitka/files/11335536/snippet.zip)

**Comment by kayhayen** [comment]
I guess, the obvious question is, where do you expect binaries created on Debian 11 to run? Am I getting that right, that you are saying inside the Debian 11 image itself, onefile segfaults? 

Literally my whole CI for Linux runs on Debian 11, and onefile is tested there. My suspect now, is that you are encountering a bug in the onefile bootstrap for Linux, maybe mishandling the absence or non-writable nature, or whatever of the default temporary spec path. Like the "slim" image doing something to `/tmp` that is unusual.

That of course would be a very interesting find. It may also actually be new. I am currently moving my CI infrastructure to Docker based builds. So I will be eventually able to do that myself, but can run the debugger with --onefile as well? Your second variant uses only accelleration mode, but debug switches. Merge the two :)

**Comment by sante85** [comment]
ok, i can do something. Or am I waiting for 1.6?

Thank you

**Comment by kayhayen** [comment]
Well, yes, combine `--onefile --debugger --run` and post the result. You didn't enable debugging in the mode that is crashing, but in the one that is not.

**Comment by sante85** [comment]
this is result of test --onefile --debugger --run
'''
--report=report.xml --follow-imports --trace-execution --debug --run --unstripped --company-name=Terainnovation --product-name=smart-battery-ota --product-version=1.0.0 --onefile --debugger test/snippet.py
''''

Execute: test/snippet.py:5 <Node 'STATEMENTS_FRAME_FUNCTION' with {'co_name': 'main', 'co_kind': 'Function', 'co_varnames': '', 'co_freevars': '', 'co_argcount': 0, 'co_posonlyargcount': 0, 'co_kwonlyargcount': 0, 'co_has_starlist': False, 'co_has_stardict': False, 'co_filename': 'snippet.py', 'co_lineno': 5, 'co_new_locals': True, 'co_is_optimized': True, 'code_flags': ''}>
Execute: test/snippet.py:6 <Node 'STATEMENT_EXPRESSION_ONLY' with {'expression': 'EXPRESSION_CALL_NO_KEYWORDS'}>
Execute: test/snippet.py:1 <Node 'STATEMENTS_FRAME_FUNCTION' with {'co_name': 'talk', 'co_kind': 'Function', 'co_varnames': 'message', 'co_freevars': '', 'co_argcount': 1, 'co_posonlyargcount': 0, 'co_kwonlyargcount': 0, 'co_has_starlist': False, 'co_has_stardict': False, 'co_filename': 'snippet.py', 'co_lineno': 1, 'co_new_locals': True, 'co_is_optimized': True, 'code_flags': ''}>
Execute: test/snippet.py:2 <Node 'STATEMENT_RETURN'>
Talk Hello World
Execute: test/snippet.py:5 <Node 'STATEMENT_RETURN_NONE'>
main(): Exited from __main__.
main(): Calling Py_Exit.
Waiting for child to exit.

Child is exited.

ONEFILE: Exiting.
[Inferior 1 (process 499) exited normally]
No stack.

**Comment by kayhayen** [comment]
Now that's not good, working with `--debug` indicates some really bad things usually. Since you have it with hello world, that's all the more baffling. I wonder how to tell which binary segfaults.

Can you compile with *only* these options:

`--onefile --experimental=show-startup-time`

and then provide the output.

Btw, your output has `--trace-execution` on. Just removing that may also make it appear in debug mode, that tracing changes a lot and is not needed really. 

I do not need reports anymore, they don't reveal anything anymore. Right now, I want to learn which binary does the segfauft, the bootstrap or Python (unlikely) and why debug mode can make it work.

**Comment by sante85** [comment]
ok, i will try with only --onefile --experimental=show-startup-time ?

**Comment by kayhayen** [comment]
Yes, that will also output traces that will allow us to tell which program segfaults exactly and roughly where.

**Comment by sante85** [comment]
with options suggested, this is output
```
 --report=report.xml --follow-imports --onefile --experimental=show-startup-time test/snippet.py
```

```
root@facfbc7dcd03:/# snippet
ONEFILE: Entered main().
ONEFILE: Unpacking payload.
ONEFILE: Determining payload start position.
ONEFILE: Checking header for compression.
ONEFILE: Entering decompression.
ONEFILE: Finishing decompression, cleanup payload.
ONEFILE: Preparing forking of slave process.
main(): Entered.
main(): Prepare standalone environment.
main(): Calling Nuitka_Py_Initialize to initialize interpreter.
Nuitka_Py_Initialize(): Calling Py_InitializeFromConfig.
main(): Calling createGlobalConstants().
main(): Returned createGlobalConstants().
main(): Calling createMainModuleConstants().
main(): Returned createMainModuleConstants().
main(): Calling __main__.
Talk Hello World
main(): Exited from __main__.
main(): Calling Py_Exit.
ONEFILE: Exiting.
```

**Comment by kayhayen** [comment]
And if you remove the experimental flag, it does it then segfault?

**Comment by sante85** [comment]
With only  --follow-imports --onefile run right, 
but if i using: --follow-imports  --onefile --standalone raise segfault
standalone option is need to create an auto runnable file.

is right or wrong this approach?

**Comment by kayhayen** [comment]
What's strange is that `--follow-imports` is implied by `--standalone` and that in turn is implied by `--onefile`. So what you are seeing could also mean sporadically. If stack memory is used, that can happen.

Code to show what I mean.

```
    # Onefile implies standalone build.
    if options.is_onefile:
        options.is_standalone = True

```
Also you should see that output:

```
    if options.follow_all is True and standalone_mode:
        Tracing.options_logger.info(
            "Following all imports is the default for %s mode and need not be specified."
            % standalone_mode
        )
```

And follow all imports is done anyway:

```
def shallFollowAllImports():
    """:returns: bool derived from ``--follow-imports``"""
    return options.is_standalone or options.follow_all is True
```

I guess, you can prove me wrong by finding a relevant difference in the compilation reports of the crashing and non-crashing one. Either way, I will try it myself too now.

**Comment by kayhayen** [comment]
My own experiments with debian-slim didn't reveal anything. I didn't have compression, no idea if that makes a difference, I think you have a docker file that I should use rather than default debian.

**Comment by sante85** [comment]
I will try to debian default and test if run right. can you update later.

Il giorno ven 28 apr 2023 alle ore 14:59 Kay Hayen ***@***.***>
ha scritto:

**Comment by kayhayen** [comment]
I think you are severely wasting my time. The report does not at all match what we are talking about and having traces for. I was not expecting a docker file so I could build the container like you have one, but there is none. I understand you not wanting to share your source code. Please understand that my investment of time ends here, and I feel way too late. 

If you get the sense that I am angry, that's only about myself to not respect the boundaries I defined for myself.
