### ISSUE TITLE
Question: MinGW-64, sjlj or seh

### ISSUE THREAD

**Issue by Azza-NZ** [Nuitka/Nuitka#220]
When you download the MinGW-64 archive instead of the installer I selected POSIX and Dwarf as per instructions but then you get a 3rd option of **sjlj** or **seh**. What one is recommended/needed?

**Comment by kayhayen** [comment]
I guess they just made it more confusing, I do really know which one is the one I had used last time, but I think it was this, and it has no such option:

https://mingw-w64.org/doku.php/download/mingw-builds

**Comment by Azza-NZ** [comment]
Yeah that links to the source forge page I used I was curious for people want to just extract the files rather than use the web installer. I used the **seh** archive and it worked, the majority of the downloads were **seh**.

**Comment by Azza-NZ** [comment]
That's the same SourceForge account I used it gives options if you don't want to use the web installer.

https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/

**Comment by kayhayen** [comment]
Well, generally please use the web installer. 

The exception model won't matter at all, as we do C, and that is for C++ and the like only. I would define `sjlj`, but you could do me the favor and see with hello world program, which one is smaller, then we go with that in the docs and I will try to add a more direct link like this, although I think these are very much in flux.

**Comment by kayhayen** [comment]
I looked at the stats, and it seems `seh` is what people pick way more often.

**Comment by kayhayen** [comment]
I added something to the user manual about this, closing it.
