### ISSUE TITLE
It seems 'PySide6' is not installed or broken

### ISSUE THREAD

**Issue by hunter-xue** [Nuitka/Nuitka#2205]
I have installed PySide6, but got not installed error. 
![image](https://user-images.githubusercontent.com/4905312/235291662-9b3bb287-e3db-4508-9f7f-d862bf741cd8.png)

**Comment by kayhayen** [comment]
That doesn't make it a valid plugin name though, there is however a pyside6 plugin.

**Comment by hunter-xue** [comment]
I upload the wrong screenshot, please this one: 

![image](https://user-images.githubusercontent.com/4905312/235292168-b205577c-d51a-4af1-9faf-a817ce655c51.png)

**Comment by kayhayen** [comment]
You also didn't read the issue template, right? I really dislike screenshots, and emailing me privately for extra wasting my time is totally unacceptable.
