### ISSUE TITLE
`GLIBC_2.33' not found 

### ISSUE THREAD

**Issue by v3ss0n** [Nuitka/Nuitka#2210]
using 1.5.7 , i had compile on latest arch linux , it works fine between latest OSs , but  woon't run on older ubuntu.
Is there way to include old versions?

**Comment by kayhayen** [comment]
Yes, build on older Linux. The Python from newest Linux will never run on older systems.

**Comment by v3ss0n** [comment]
i see , thanks. Is there anyway  to switch compailer, like CLang to statically build it?

**Comment by kayhayen** [comment]
The glibc is encoding kernel interfaces. Statically linking it is not going to work well at all. Nuitka commercial has a podman based container, that I eventually plan on making more public. It's geared to people who don't know how to use containers, copies your code and requirements in there, compiles an optimized Python and installs a relatively modern gcc, then works well. But so far I do not even advertise that. Maybe by the time next person reads this, I added that or made it public: https://nuitka.net/doc/commercial.html but it's in there. :)

**Comment by v3ss0n** [comment]
currently its hard to distribute , so i will just build a dockerfile -that would be used for building the binary.
