### ISSUE TITLE
File doesn`t work after renaming

### ISSUE THREAD

**Issue by deldroid** [Nuitka/Nuitka#2214]
when I build my file, it works fine, but if I rename it, it doesn't start anymore.

build command: python -m nuitka --standalone --onefile --follow-imports --show-modules --show-memory --show-progress --show-scons --mingw64 --remove-output --nofollow-import-to=email,mailbox,mailcap,ftplib,smtpd,html,http,xml,xmlrcp 

mingw:
This is the winlibs 64-bit standalone build of:
- GCC 12.2.0
- GDB 13.1
- LLVM/Clang/LLD/LLDB 16.0.0
- MinGW-w64 10.0.0 (linked with ucrt)
- GNU Binutils 2.40
- GNU Make 4.4.1
- PExports 0.47
- dos2unix 7.4.4
- Yasm 1.3.0
- NASM 2.16.01
- JWasm 2.12pre
- ccache version 4.8
- CMake 3.26.3
- ninja 1.11.1
- doxygen 1.9.6

This build was compiled with GCC 12.2.0 and packaged on 2023-04-05.

error:
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Temp\onefile_2748_133270073629202299\work.py", line 701, in <module>
  File "C:\Users\Admin\AppData\Local\Temp\onefile_2748_133270073629202299\multiprocessing\process.py", line 121, in start
  File "C:\Users\Admin\AppData\Local\Temp\onefile_2748_133270073629202299\multiprocessing\context.py", line 224, in _Popen
  File "C:\Users\Admin\AppData\Local\Temp\onefile_2748_133270073629202299\multiprocessing\context.py", line 336, in _Popen
  File "C:\Users\Admin\AppData\Local\Temp\onefile_2748_133270073629202299\multiprocessing\popen_spawn_win32.py", line 73, in init
FileNotFoundError: [WinError 2] The system cannot find the file specified

code:
import sys
import random
import os
import win32event
import time
import ctypes
import time
import socket
import psutil
from zipfile import ZipFile
import json
import multiprocessing
import threading
from subprocess import check_output, CalledProcessError, STDOUT
import wmi
import re
from io import BytesIO, StringIO
import filedate

...

def conn():
    while True:
        try:
            addr = ''
            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
                s.connect((addr, 1024))
        except Exception as e:
            time.sleep(15)
            pass

if __name__ == '__main__':
    p = multiprocessing.Process(target=conn)
    p.start()

error occurs on the line multiprocessing.Process(target=conn)

I hope the information provided is enough
versions of all libraries are the latest
without multiprocessing or changing name my program works good, but i need it

**Comment by kayhayen** [comment]
You need to change the filename with `--output-filename`. Also, UCRT was in question if it can be used with Python, the last time I considered it, may just be wrong, use the one Nuitka downloads instead. But there is no Nuitka version, so I cannot even know why it would be suspectible. I assume last hotfix wouldn't have noticed a manual rename, but now I cannot tell.
