### ISSUE TITLE
Can Nuitka support pyqtlet2?

### ISSUE THREAD

**Issue by mcondarelli** [Nuitka/Nuitka#2216]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.
```
mcon@Spoke:~/nuitka$ ( . venv/bin/activate ; python -m nuitka --version )
1.5.7
Commercial: None
Python: 3.9.2 (default, Feb 28 2021, 17:03:44) 
Flavor: Debian Python
Executable: /home/mcon/nuitka/venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Debian 11
Version C compiler: /usr/bin/gcc (gcc).
```
* How did you install Nuitka and Python
```
sudo apt install python3
python3 -m venv venv
venv/bin/pip install -U pip wheel pyqtlet2[pyqt5] nuitka
```
* The specific PyPI names and versions
```
mcon@Spoke:~/nuitka$ ( . venv/bin/activate ; python -m pip freeze )
Nuitka==1.5.7
ordered-set==4.1.0
packaging==23.1
pkg_resources==0.0.0
PyQt5==5.15.9
PyQt5-Qt5==5.15.2
PyQt5-sip==12.12.1
pyqtlet2==0.9.3
PyQtWebEngine==5.15.6
PyQtWebEngine-Qt5==5.15.2
QtPy==2.3.1
zstandard==0.21.0
```
* Many times when you get an error from Nuitka, your setup may be special
   Basic `nuitka` usage OK.

* Also supply a Short, Self Contained, Correct, Example
   Basic example, lifted directly from [pyqlet2 site](https://github.com/JaWeilBaum/pyqtlet2) follows:
```python3
import os
import sys
from PyQt5.QtWidgets import QApplication, QVBoxLayout, QWidget
from pyqtlet2 import L, MapWidget


class MapWindow(QWidget):
    def __init__(self):
        # Setting up the widgets and layout
        super().__init__()
        self.mapWidget = MapWidget()
        self.layout = QVBoxLayout()
        self.layout.addWidget(self.mapWidget)
        self.setLayout(self.layout)

        # Working with the maps with pyqtlet
        self.map = L.map(self.mapWidget)
        self.map.setView([12.97, 77.59], 10)
        L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png').addTo(self.map)
        self.marker = L.marker([12.934056, 77.610029])
        self.marker.bindPopup('Maps are a treasure.')
        self.map.addLayer(self.marker)
        self.show()


if __name__ == '__main__':
    app = QApplication(sys.argv)
    widget = MapWindow()
    sys.exit(app.exec_())

```
* Provide in your issue the Nuitka options used
   To test I use the following bash script:
```shell
#!/bin/bash
set -x
set -e

python3 -m venv venv
venv/bin/pip install -U pip wheel pyqtlet2[pyqt5] nuitka
venv/bin/python test.py
( . venv/bin/activate ; nuitka3 --standalone --enable-plugin=pyqt5 test.py )
( cd test.dist ; ./test.bin )
```

* Avoid unnecessary options
   Ok

* Note if this is a regression
   No previous usage

* Consider getting commercial support
   Not an option ATM, it may be considered if confirmed `nuitka` can actually work in this specific Use Case.

* Problem description:
   * `pyqtlet2` is a thin wrapper around [Leaflet](https://leafletjs.com/index.html) JavaScript package.
   * JavaScript is executed using PyQt5 PyQtWebEngine
   * JavaScript (complete, frozen, Leaflet clone) and self-contained HTML page including it are part of `pyqtlet2` (in the `web` subdir).
   * Apparently all this part (residing in `venv/lib/python3.9/site-packages/pyqtlet2/web`) is not copied over by `nuitka` so resulting program fails because it doesn't find the "page" to load.
   * After we solve this issue there will be problem to be sure page loading finds its `script`s (and then I'll have to make sure everything else works in my program, which is "a bit more complex", but this is another issue, of course).
   * My current problem is to understand if `nuitka` can support `pyqtlet2`.
   * I tried switching to PyQt6/PySide6 but problem is the same (and I would have problems with porting my program, especially with PySide).

* IMPORTANT NOTE:
   Depending on actual Linux-distribution/lib-version/python combination it may be necessary to add `QTWEBENGINE_CHROMIUM_FLAGS=--disable-seccomp-filter-sandbox` to overcome changes in security settings leading to a hang (due to fact "load_page" never terminates so program is stuck in a "secondary main loop").

Any comment welcome.
TiA!

**Comment by kayhayen** [comment]
Sure, this appear to be just data files, which Nuitka will gladly handle.

If you are available to do a PR, this can be fixed by adding to the yaml configuration, described here: [https://nuitka.net/doc/nuitka-package-config.html](https://nuitka.net/doc/nuitka-package-config.html)

And here is more of a walk through style post: [https://nuitka.net/posts/nuitka-package-config-kickoff.html](https://nuitka.net/posts/nuitka-package-config-kickoff.html)

Here are a example PRs for other packages:

[#2030](https://github.com/Nuitka/Nuitka/pull/2030) 
[#1993](https://github.com/Nuitka/Nuitka/pull/1993)

**Comment by mcondarelli** [comment]
THANKS
It proved far easier than anticipated.
The patch is trivial:
```patch
diff --git a/nuitka/plugins/standard/standard.nuitka-package.config.yml b/nuitka/plugins/standard/standard.nuitka-package.config.yml
index 2f6b1cddd..fb4fdd06e 100644
--- a/nuitka/plugins/standard/standard.nuitka-package.config.yml
+++ b/nuitka/plugins/standard/standard.nuitka-package.config.yml
@@ -2149,6 +2149,11 @@
       - 'colors'
       - 'icons'
 
+- module-name: 'pyqtlet2'
+  data-files:
+    dirs:
+      - 'web'
+
 - module-name: 'pyreadstat._readstat_parser'
   implicit-imports:
     - depends:
```
Is this enough or should I prepare a proper PR?
