### ISSUE TITLE
ModuleNotFoundError: No module named 'passlib.handlers.phpass'

### ISSUE THREAD

**Issue by steeljardas** [Nuitka/Nuitka#2220]
Error:
`Traceback (most recent call last):
  File "C:\Users\STEELH~1\Desktop\pthon\CALLOF~1\BOT2~1.DIS\bot2.py", line 26, in <module>
  File "C:\Users\STEELH~1\Desktop\pthon\CALLOF~1\BOT2~1.DIS\passlib\registry.py", line 43, in __getattr__
  File "C:\Users\STEELH~1\Desktop\pthon\CALLOF~1\BOT2~1.DIS\passlib\registry.py", line 352, in get_crypt_handler
ModuleNotFoundError: No module named 'passlib.handlers.phpass'`

This was how I ran nuitka:
py -m nuitka --standalone bot2.py --enable-plugin=tk-inter

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
