### ISSUE TITLE
ModuleNotFoundError: No module named 'passlib.handlers.phpass'

### ISSUE THREAD

**Issue by steeljardas** [Nuitka/Nuitka#2222]
Error:
`Traceback (most recent call last): File "C:\Users\STEELH~1\Desktop\pthon\CALLOF~1\BOT2~1.DIS\bot2.py", line 26, in <module> File "C:\Users\STEELH~1\Desktop\pthon\CALLOF~1\BOT2~1.DIS\passlib\registry.py", line 43, in __getattr__ File "C:\Users\STEELH~1\Desktop\pthon\CALLOF~1\BOT2~1.DIS\passlib\registry.py", line 352, in get_crypt_handler ModuleNotFoundError: No module named 'passlib.handlers.phpass'`

This was how I ran nuitka:
>py -m nuitka --standalone bot2.py --enable-plugin=tk-inter

python -m nuitka --version
>1.5.7
Commercial: None
Python: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Python\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).

How did you install Nuitka and Python
> Pip, no virtualenv. Python I don't recall since its been years but I just downloaded it from the python website and installed it normally as far as I remember

Alll modules I'm importing
```
from pyautogui import *
import pyautogui
import time
import keyboard
import numpy as np
import random
import win32api, win32con, win32gui
from PIL import Image, ImageGrab
from pytesseract import *
import tkinter as tk
from tkinter import ttk, Toplevel, StringVar
from tkinter.scrolledtext import ScrolledText
import tkinter.messagebox as tm
from tkinter.ttk import *
import cv2
from functools import partial
from threading import Timer, Thread
import sys
import asyncio
from pynput.mouse import Button, Controller
from pywinauto import Desktop
import numpy
import imageio
import ctypes
from passlib.hash import phpass
import mysql
import mysql.connector
from tkinter import *
import webbrowser
from tinydb import TinyDB, Query
```

I also tried doing the compiling "hello world" and see if any error pops up but no errors.

**Comment by kayhayen** [comment]
The more interesting case would be a minimal reproducer of the issue you are reporting.

**Comment by steeljardas** [comment]
> The more interesting case would be a minimal reproducer of the issue you are reporting.

I'm not too sure what you mean. My program is quite large, all I really did was install Nuitka with pip, read all the different options and try compiling said program with the following command:
> 
py -m nuitka --standalone bot2.py --enable-plugin=tk-inter

And when trying to run the executable that's the error that pops up (Module not found)

**Comment by kayhayen** [comment]
If that's your contribution, that's fair enough, but it renders the report useless.
