### ISSUE TITLE
Nuitka is removing docstrings when --python-flag=-O is used. It should only remove them with --python-flag=-OO.

### ISSUE THREAD

**Issue by jcrmatos** [Nuitka/Nuitka#223]
Hello,

Nuitka is removing docstrings when --python-flag=-O is used.
It should only remove them with --python-flag=-OO.

```
(.venv) C:\Users\JMatos\OneDrive\Python\uniclave>python -m nuitka --version
0.6.0.6
Python: 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 32 bit (Int
el)]
Executable: C:\Users\JMatos\OneDrive\Python\uniclave\.venv\Scripts\python.exe
OS: Windows
Arch: x86
```

Thanks,

JM

**Comment by kayhayen** [comment]
Oops, I had no clue this even ecists, but this is obviously easy to fix, going to add support for -OO

**Comment by jcrmatos** [comment]
Hello,

Ok, thanks.
Check my other issue #222 because it is related to --python-flag.
This way you do both in one go. :)

Thanks,

JM

**Comment by kayhayen** [comment]
Releases as 0.6.1.1
