### ISSUE TITLE
Add Nuitka support for the pysnmp library

### ISSUE THREAD

**Issue by joeverve** [Nuitka/Nuitka#2233]
# Add support for pysnmp library

## Environment as reported by `python -m nuitka --version`
> 1.5.7
Commercial: None
Python: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\jhomp\code\nuitka_issues\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).

### Python
Python is CPython downloaded directly from python.org
A new 'venv' python virtual environment was created for this test using `python -m venv .venv`

### Nuitka
Nuitka was installed via pip in the virtual environment `pip install nuitka`

## PyPI names and versions
As reported by `python -m pip freeze`:
anyio==3.6.2
aonvif==1.0.0rc6
attrs==23.1.0
certifi==2023.5.7
charset-normalizer==3.1.0
h11==0.14.0
httpcore==0.17.0
httpx==0.24.0
idna==3.4
isodate==0.6.1
lxml==4.9.2
Nuitka==1.5.7
ordered-set==4.1.0
platformdirs==3.5.1
ply==3.11
pyasn1==0.5.0
pycryptodomex==3.17
pysmi==0.3.4
pysnmp==4.4.12
python-snap7==1.3
pytz==2023.3
requests==2.30.0
requests-file==1.5.1
requests-toolbelt==1.0.0
six==1.16.0
sniffio==1.3.0
urllib3==2.0.2
zeep==4.2.1
zstandard==0.21.0

## Special Considerations - Many times when you get an error from Nuitka, your setup may be special
A new virtual environment was created for testing Nuitka issues in their simplest form to prevent other code from complicating matters.   The virtual environment used for testing pysnmp was also used for testing the `aonvif` and `python-snap7` libraries as well, so there are more python packages installed in the pip freeze output above than are strictly required for a pysnmp test.

## Short, Self Contained, Correct, Example
The following short example reliably reproduces the issue observed and can be used as a simple test.  

Observed Error:
> pysnmp.smi.error.MibNotFoundError: No module __SNMP-FRAMEWORK-MIB loaded at <pysnmp.smi.builder.MibBuilder object at 0x0000020089BE05B0
 
```py
from pysnmp.hlapi import SnmpEngine


def reproduce_issue():
    engine: SnmpEngine = SnmpEngine()
    print('If you see this message, Nuitka resolved the reported issue with pysnmp!')


reproduce_issue()

```

## Nuitka Options Used

Compiler cmd line: `python -m nuitka --output-dir=.\build --output-filename=pysnmp_test.exe --standalone --user-package-configuration-file=issues.nuitka-package.config.yml --report=compilation-report.xml pysnmp_issue.py`

The `issues.nuitka-package.config.yml` file contained the following pysnmp configuration:

```
- module-name: 'pysnmp.smi.builder'
  data-files:
     patterns:
       - 'mibs/**/*.py'
```

**Comment by kayhayen** [comment]
I don't think your Yaml config has a good chance of working, Python files are not data files, and therefore will not match. Let me see what I can come up with.

**Comment by kayhayen** [comment]
```
 N  hayen@Neyah: python bin/nuitka --list-package-data=pysnmp
Nuitka-Tools:INFO: Checking package directory '/home/hayen/.local/lib/python3.10/site-packages/pysnmp' .. 
/home/hayen/.local/lib/python3.10/site-packages/pysnmp
 N  hayen@Neyah: ~/repos/Py2C$ python bin/nuitka --list-package-dll=pysnmp
Nuitka-Tools:INFO: Checking package directory '/home/hayen/.local/lib/python3.10/site-packages/pysnmp' .. 
Nuitka-Tools:INFO: Found 0 DLLs.
```

So this doesn't seem to be about inclusion of DLLs or data-files, there are none apparently.

**Comment by kayhayen** [comment]
Seems I was wrong about the yaml data files configuration though, it doesn't filter code away, although I think it really should, so your config actually copies stuff indeed. This might also be a mismatch of the default ignores suffixes, I will have to check that. For what it's worth I made `--include-package-data=pysnmp.smi:**/*.py` do the equivalent of your Yaml configuration. It no longer ignores the suffix specified in the data file option if any. Just all other code types.

**Comment by kayhayen** [comment]
So, seems that it was failing to include the package, adding those to the implicit dependencies made it work. 

The protection level is very weak, but I assume will work with Nuitka commercial file embedding or should be be easy to change in that way. However, it would of course be best, if we could use the code in compiled form, but that is too much effort, and I do not contemplate this right now without funding. Probably needs a day of my time paid.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by joeverve** [comment]
I have tested this change on  all of my pysnmp use cases and can confirm this change does fix the reported issue in my tests.

**Comment by kayhayen** [comment]
Not sure how to track potential protection improvements that I would want money for. I guess closed and funding_wanted will be a thing until then.

**Comment by kayhayen** [comment]
Chaging the files will allow the user to execute arbitrary code in your program. Depending on the nature of protection you seek, that might be very valuable or not.

I am of course not withholding the improvement and it's part of factory right now and will be in 1.6 for sure. It's just that for people like you, a false illusion of security could be generated. So there is kind of another issue, where the .py files should come from protected  data files of Nuitka commercial, which would be simple, or compiled as well and used like that, in the first place, which probably just requires some of my time.

As you can imagine the world where somebody sees their software hacked unexpectedly easily, and I do not earn a bit of money, is bad for both sides. I feel the responsibility to share that knowledge. Of course, very hard to do for all projects, to know if they are valnerable or not, but here I know for sure.

**Comment by kayhayen** [comment]
This is part of the stable release 1.6 that I just made.
