### ISSUE TITLE
multiprocessing fails to spawn a process when running a manually renamed exe

### ISSUE THREAD

**Issue by sebdelsol** [Nuitka/Nuitka#2234]
### Environment:
- Nuitka: 1.5.8
- Python: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
- Flavor: CPython Official
- Executable: .\venv\scripts\python.exe
- OS: Windows
- Arch: x86_64
- WindowsRelease: 10

### Installation:
- pip, venv

### Dependencies:
- None

### Sample:
```python3
# bug.py

# uncomment the hack below to make it work
# if "__compiled__" in globals():  # nuitka ?
#     import os

#     if "NUITKA_ONEFILE_PARENT" in os.environ:  # onefile ?
#         import sys

#         # force the built exe name on sys.argv[0]
#         # so multiprocessing spawn the exe even if it has been renamed
#         BUILT_EXE = "bug.exe"
#         sys.argv[0] = os.path.join(os.path.dirname(sys.argv[0]), BUILT_EXE)


def do_something():
    print("I've done something")


if __name__ == "__main__":
    import multiprocessing

    process = multiprocessing.Process(target=do_something)
    process.start()
    process.join()
```
### Command:
```console
.\venv\scripts\activate
python -m nuitka --onefile bug.py
ren bug.exe bug_.exe
bug_
```

### Error:
```console
Traceback (most recent call last):
  File "%TEMP%\ONEFIL~1\bug.py", line 24, in <module>
  File "%TEMP%\ONEFIL~1\multiprocessing\process.py", line 121, in start
  File "%TEMP%\ONEFIL~1\multiprocessing\context.py", line 224, in _Popen
  File "%TEMP%\ONEFIL~1\multiprocessing\context.py", line 336, in _Popen
  File "%TEMP%\ONEFIL~1\multiprocessing\popen_spawn_win32.py", line 73, in __init__
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

### Nuitka log:
```console
Nuitka-Options:INFO: Used command line options: --onefile bug.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.5.8' on Python '3.10' commercial grade 'not installed'.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka:INFO: Completed Python level compilation and optimization.  
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl 14.3).
Nuitka-Scons:INFO: Backend linking program with 9 files (no progress information available).
Nuitka-Scons:INFO: Compiled 9 C files using clcache with 9 cache hits and 0 cache misses.
Nuitka-Postprocessing:INFO: Creating single file from dist folder, this may take a while.
Nuitka-Onefile:INFO: Running bootstrap binary compilation via Scons.
Nuitka-Scons:INFO: Onefile C compiler: cl (cl 14.3).
Nuitka-Scons:INFO: Onefile linking program with 1 files (no progress information available).
Nuitka-Scons:INFO: Compiled 1 C files using clcache with 1 cache hits and 0 cache misses.
Nuitka-Onefile:INFO: Using compression for onefile payload.
Nuitka-Onefile:INFO: Onefile payload compression ratio (32.59%) size 16537460 to 5390278.
Nuitka-Onefile:INFO: Keeping onefile build directory 'bug.onefile-build'.
Nuitka:INFO: Keeping dist folder 'bug.dist' for inspection, no need to use it.
Nuitka:INFO: Keeping build directory 'bug.build'.
Nuitka:INFO: Successfully created 'bug.exe'.
```

**Comment by kayhayen** [comment]
Two points of improvement. The`__compiled__` indicates the onefile and/or standalone modes pretty well, going to the environment variable is likely to break instead. Check the attributes of the value. Also, renaming the output should be down with `--output-filename`.  I have observed that people who do not find `python-flag=-m` and most often doing these rename manually.

The name of the onefile executable should indeed not have to match though and `sys.argv[0]` should be unused to find the running binary.  I think it's being used to correct `sys.executable` for `mulitprocessing` like this `os.path.join(os.path.dirname(sys.executable), os.path.basename(argv0))` and that is hurting us here. 

Maybe the `__nuitka_binary_dir` needs a companion, but I really hate to pollute the builtins space any further. Much rather would want to put this into `__compiled__` with the drawback being that it requires for the module to be compiled, a `__nuitka__` module could host that more clearly, but adding modules comes with a penalty too.

**Comment by kayhayen** [comment]
So, I think I am going with adding a `__nuitka_binary_exe` for standalone mode to use. It's easy enough and I got it to work with Windows quickly, need of course to cover a lot of cases there, and I think the recent symlink work might have a few uncovered cases, now that I change code in this area.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by sebdelsol** [comment]
Thank you indeed for the very fast fix. 
It works like a charm with the sample I provided (and another project) thanks to your fix on the development version.

For the record I stumbled upon this bug by having a person downloading twice a Nuitka standalone exe by mistake and trying to run the automatically renamed one : it didn't work and I was quite dumbfounded.

**Comment by kayhayen** [comment]
This is part of the stable release 1.6 that I just made.
