### ISSUE TITLE
 ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation

### ISSUE THREAD

**Issue by feckpown** [Nuitka/Nuitka#2236]
The binary output from

`python -m nuitka --follow-imports run.py`

seems to fail with the issue:

```
_raise ImportError('ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.')
ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation_
```

I tried with a good handful of different OpenCV versions, 4.5.5.64, the newest 4.7.0.72, and others, but always get the same error.

Using Python 3.9.7 in a conda environment  

It seems this is a common issue people are experiencing, is there any chance it'll be fixed at some point?

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
