### ISSUE TITLE
Platform.mac_ver doesn't work on MacOS

### ISSUE THREAD

**Issue by enaix** [Nuitka/Nuitka#2237]
Calling platform.mac_ver returns nothing on MacOS Ventura (Macbook Air M2)

Non-compiled:
```
>>> import platform
>>> platform.mac_ver()
('13.3.1', ('', '', ''), 'arm64')
```

Compiled:
> main.py
```
# nuitka-project: --standalone
# nuitka-project: --macos-create-app-bundle
import platform
platform.mac_ver()
```

```
$ python3 -m nuitka --standalone --macos-create-app-bundle ./main.py
$ ./main
('', ('', '', ''), '')
```

It breaks darkdetect package that throws
```
File "/Users/flynn/src/smartwheel-core/src/main.app/Contents/MacOS/darkdetect/__init__.py", line 14, in macos_supported_version
ValueError: invalid literal for int() with base 10: ''
```

> python -m nuitka --version

```
1.5.8
Commercial: None
Python: 3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)]
Flavor: CPython Official
Executable: /Users/flynn/src/smartwheel-core/venv2/bin/python
OS: Darwin
Arch: arm64
Version C compiler: /usr/bin/clang (clang).
```

Python was installed from python.org into a virtualenv, nuitka is installed through pip. Darkdetect version is darkdetect==0.7.1

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by enaix** [comment]
Thanks for the quick reply! It's working as expected

**Comment by kayhayen** [comment]
This is part of the stable release 1.6 that I just made.
