### ISSUE TITLE
can not generate standalone pyside2

### ISSUE THREAD

**Issue by laoshaw** [Nuitka/Nuitka#224]
nuitka3 --standalone test.py

```
import sys
from PySide2.QtWidgets import QApplication, QMessageBox

app = QApplication(sys.argv)

msg_box = QMessageBox()
msg_box.setText("Hello World")
msg_box.show()

sys.exit(msg_box.exec_())
```

Error:

```
File "/home/rx67ds/.local/lib/python3.6/site-packages/nuitka/__main__.py", line 180, in <module>
    main()
  File "/home/rx67ds/.local/lib/python3.6/site-packages/nuitka/__main__.py", line 174, in main
    MainControl.main()
  File "/home/rx67ds/.local/lib/python3.6/site-packages/nuitka/MainControl.py", line 796, in main
    filename = filename
  File "/home/rx67ds/.local/lib/python3.6/site-packages/nuitka/MainControl.py", line 152, in createNodeTree
    Optimization.optimize(main_module.getOutputFilename())
  File "/home/rx67ds/.local/lib/python3.6/site-packages/nuitka/optimizations/Optimization.py", line 533, in optimize
    makeOptimizationPass(initial_pass = True)
  File "/home/rx67ds/.local/lib/python3.6/site-packages/nuitka/optimizations/Optimization.py", line 446, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "/home/rx67ds/.local/lib/python3.6/site-packages/nuitka/optimizations/Optimization.py", line 170, in optimizeModule
    optimizeShlibModule(module)
  File "/home/rx67ds/.local/lib/python3.6/site-packages/nuitka/optimizations/Optimization.py", line 164, in optimizeShlibModule
    signal_change = signalChange
  File "/home/rx67ds/.local/lib/python3.6/site-packages/nuitka/plugins/Plugins.py", line 84, in considerImplicitImports
    plugin.considerImplicitImports(module, signal_change)
  File "/home/rx67ds/.local/lib/python3.6/site-packages/nuitka/plugins/PluginBase.py", line 89, in considerImplicitImports
    for full_name in self.getImplicitImports(module):
  File "/home/rx67ds/.local/lib/python3.6/site-packages/nuitka/plugins/standard/ImplicitImports.py", line 74, in getImplicitImports
    for used_module in module.getUsedModules():
  File "/home/rx67ds/.local/lib/python3.6/site-packages/nuitka/nodes/ModuleNodes.py", line 869, in getUsedModules
    self._readPyPIFile()
  File "/home/rx67ds/.local/lib/python3.6/site-packages/nuitka/nodes/ModuleNodes.py", line 848, in _readPyPIFile
    assert imported.endswith(')')
AssertionError
```

I tried to change: from PySide2.QtWidgets import QApplication, QMessageBox
to:
```
PySide2.QtWidgets import QApplication
PySide2.QtWidgets import QMessageBox
```

same error reported

**Comment by kayhayen** [comment]
Seems PySide2 has a ``.pyi`` file that Nuitka fails to parse correctly.

Can you find out what file it was working on there and send it my way?

**Comment by laoshaw** [comment]
how can I find that? yes pyside2 has lots of *.pyi files, but I don't know the steps to find out which one is related. Tried "python3 -m trace --trackcalls helloworld.py"  etc and it did not help

here is the full list of pyi files for pyside2:

```
./QtMultimedia.pyi
./QtWebSockets.pyi
./QtPositioning.pyi
./QtOpenGL.pyi
./QtWebEngineCore.pyi
./QtHelp.pyi
./QtLocation.pyi
./QtTextToSpeech.pyi
./QtWebEngine.pyi
./QtConcurrent.pyi
./QtWebChannel.pyi
./QtSensors.pyi
./QtWidgets.pyi
./QtUiTools.pyi
./Qt3DCore.pyi
./QtDataVisualization.pyi
./QtX11Extras.pyi
./QtQuick.pyi
./Qt3DAnimation.pyi
./Qt3DLogic.pyi
./QtWebEngineWidgets.pyi
./QtNetwork.pyi
./QtQml.pyi
./QtPrintSupport.pyi
./QtMultimediaWidgets.pyi
./QtScxml.pyi
./QtSql.pyi
./Qt3DInput.pyi
./Qt3DExtras.pyi
./QtGui.pyi
./QtSvg.pyi
./QtCharts.pyi
./Qt3DRender.pyi
./QtXmlPatterns.pyi
./QtTest.pyi
./QtCore.pyi
./QtQuickWidgets.pyi
./QtXml.pyi
```

**Comment by kayhayen** [comment]
I would hack the Nuitka source on your traceback to output the filename via print. For a future release, I am going to add a "Problem parsing..." message, but right now we don't have it.

**Comment by freethebee** [comment]
I ran into the same issue and put a print statement to show the filename on the AssertionError. It turns out many of the PySide2 pyi files contain an import statement like the one below.  
```
# Module PySide2.QtWidgets
import shiboken2 as Shiboken
from PySide2.support.signature import typing
from PySide2.support.signature.mapping import (
    Virtual, Missing, Invalid, Default, Instance)
```
Some example files are:
```
C:\Users\Name\Anaconda3\lib\site-packages\PySide2\QtWidgets.pyi
C:\Users\Name\Anaconda3\lib\site-packages\PySide2\QtCore.pyi
C:\Users\Name\Anaconda3\lib\site-packages\PySide2\QtGui.pyi
```

**Comment by kayhayen** [comment]
PySide2 is and remains unsupported, because upstream is not cooperative for patches.

**Comment by johndoe46** [comment]
> PySide2 is and remains unsupported, because upstream is not cooperative for patches.

Is this still the case ? What a pity, nuitka would be so useful for this use case (distributing python/qt apps).

**Comment by kayhayen** [comment]
It unfortunately is, @johndoe46 

Unlike PyQt, they refused our patches, and now there is little inclination to rectify this from our side it seems. But I guess, you can just use PyQt5 and be good.

**Comment by johndoe46** [comment]
At the time I couldn't choose between the various QT bindings. I took PySide2 because I thought the Nokia support would be beneficial... I'm not so sure about it anymore. I may use an abstraction layer such as qtpy in the future.

**Comment by johndoe46** [comment]
I did try PtQt5 but got an import error on a module while executing the binary nuitka generated (even though I don't use directly this module): "ModuleNotFoundError: No module named 'PyQt5.QtWebChannel'". I'm not sure what's going on, I will probably not use nuitka for desktop apps packaging (I had success with it for CLI apps though).

**Comment by JorjMcKie** [comment]
@johndoe46 - what was your compile command? There are a few options available for the Qt plugin, which might help to play with.
To include *all* Qt code you might use ``--enable-plugin=qt-plugins=all``.

**Comment by johndoe46** [comment]
@JorjMcKie Thank you for your help. I tried this:

`python -m nuitka --plugin-enable=qt-plugins=all --plugin-enable=numpy --standalone src/main.py`

The binary fails on this line:

`from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEngineProfile`

QWebEngine* classes are provided by PyQt but as a separate package called PyQtWebEngine (I don't know why). Maybe there is something to change in Nuitka about this ?

**Comment by JorjMcKie** [comment]
> QWebEngine* classes are provided by PyQt but as a separate package called PyQtWebEngine (I don't know why). Maybe there is something to change in Nuitka about this ?

Ah, thanks for this hint. Maybe I can right try a skeleton script consisting of just your import statements then and see if there is a simple way to trigger the missing implicit import (which I'm sure will be the solution).
Could you provide me these - I imagine: handful of - import statements?

Your experiment has shown a different failure, so we should be approaching the hotspot.

**Comment by JorjMcKie** [comment]
Just tried your single import statement with hinted compilation:
```python
from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEngineProfile

print(
    "successful:",
    "from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEngineProfile",
)
```
This is the compile step and execution log:
```
D:\Jorj\Desktop\Develop\nuitka>python nuitka-hints.py qtweb-test.py
NUITKA is compiling 'qtweb-test.py' with these options:
 --standalone
 --remove-output
 --recurse-none

Nuitka:INFO:User plugin 'hinted-mods.py' is being loaded.
Nuitka:INFO:'hinted-mods.py' is adding the following options:
Nuitka:INFO:--enable-plugin=qt-plugins=sensible
Nuitka:INFO:--recurse-to for 4 imported modules.
Nuitka:INFO:
Nuitka:INFO:drop types
Nuitka:INFO:drop site
Nuitka:INFO:Injecting plug-in based pre load code for module 'PyQt5':
Nuitka:INFO:    Adding dist folder to 'PATH' environment variable.
Nuitka:INFO:drop sip
Nuitka:INFO:Injecting plug-in based post load code for module 'PyQt5.QtCore':
Nuitka:INFO:    Setting Qt library path to distribution folder. Need to avoid loading target
Nuitka:INFO:    system Qt plug-ins, which may be from another Qt version.
Nuitka:INFO:drop PyQt5.QtSvg (in PyQt5)
Nuitka:WARNING:Not recursing to unused 'enum'.
Nuitka:INFO:Copying Qt plug-ins 'iconengines,imageformats,mediaservice,platforms,printsupport' to 'qtweb-test.dist\PyQt5\qt-plugins'.
Nuitka:INFO:Copying OpenSSL DLLs to 'qtweb-test.dist'
Nuitka:INFO:Compile time 125 seconds.

D:\Jorj\Desktop\Develop\nuitka>cd qtweb-test.dist

D:\Jorj\Desktop\Develop\nuitka\qtweb-test.dist>qtweb-test
successful: from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEngineProfile

D:\Jorj\Desktop\Develop\nuitka>cd qtweb-test.dist

D:\Jorj\Desktop\Develop\nuitka\qtweb-test.dist>qtweb-test
successful: from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEngineProfile

D:\Jorj\Desktop\Develop\nuitka\qtweb-test.dist>
```

These are my relevant config data. Just installed PyQtWebEngine, which required me to upgrade PyQt as a whole.

```
D:\Harald\Desktop>python -m nuitka --version
0.6.6rc7
Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Users\Jorj\AppData\Local\Programs\Python\Python37\python.exe
OS: Windows
Arch: x86_64

D:\Jorj\Desktop>python -m pip show pyqt5
Name: PyQt5
Version: 5.13.1
Summary: Python bindings for the Qt cross platform UI and application toolkit
Home-page: https://www.riverbankcomputing.com/software/pyqt/
Author: Riverbank Computing Limited
Author-email: info@riverbankcomputing.com
License: GPL v3
Location: c:\users\jorj\appdata\local\programs\python\python37\lib\site-packages
Requires: PyQt5-sip
Required-by: spyder, PyQtWebEngine

D:\Jorj\Desktop>
```

**Comment by johndoe46** [comment]
I didn't know about nuitka-hints.py. Tryning this now...

**Comment by JorjMcKie** [comment]
ok, but you also should be fine with the conventional compile command
```
python -m nutika --standalone --enable-plugin=qt-plugins=sensible ...
```
except maybe compile time and dist foldersize.
