### ISSUE TITLE
Getting error with nuitka,Python path configuration

### ISSUE THREAD

**Issue by Awuku-kelvin** [Nuitka/Nuitka#2241]
I got this error;

Python path configuration:
  PYTHONHOME = 'C:\Users\deadsec\AppData\Local\Temp\ONEFIL~1'
  PYTHONPATH = (not set)
  program name = 'C:\Users\deadsec\AppData\Local\Programs\Python\Python311\python.exe'
  isolated = 0
  environment = 1
  user site = 1
  safe_path = 0
  import site = 1
  is in build tree = 0
  stdlib dir = 'C:\Users\deadsec\AppData\Local\Temp\ONEFIL~1\Lib'
  sys._base_executable = 'C:\\Users\\deadsec\\AppData\\Local\\Programs\\Python\\Python311\\python.exe'
  sys.base_prefix = 'C:\\Users\\deadsec\\AppData\\Local\\Temp\\ONEFIL~1'
  sys.base_exec_prefix = 'C:\\Users\\deadsec\\AppData\\Local\\Temp\\ONEFIL~1'
  sys.platlibdir = 'DLLs'
  sys.executable = 'C:\\Users\\deadsec\\AppData\\Local\\Programs\\Python\\Python311\\python.exe'
  sys.prefix = 'C:\\Users\\deadsec\\AppData\\Local\\Temp\\ONEFIL~1'
  sys.exec_prefix = 'C:\\Users\\deadsec\\AppData\\Local\\Temp\\ONEFIL~1'
  sys.path = [
    'C:\\Users\\deadsec\\AppData\\Local\\Programs\\Python\\Python311\\python311.zip',
    'C:\\Users\\deadsec\\AppData\\Local\\Temp\\ONEFIL~1\\Lib',
    'C:\\Users\\deadsec\\AppData\\Local\\Temp\\ONEFIL~1\\DLLs',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000075d0 (most recent call first):
  <no Python frame>

its a script i created to convert other files to exe using pyinstaller, but i always get this error when ever i execute the file
tool made with customtkinter

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
