### ISSUE TITLE
Building nuitka binary file without compiling any external dependencies

### ISSUE THREAD

**Issue by ai22m020** [Nuitka/Nuitka#2245]
Citation "_There is plenty of documentation in the user manual about modes, standalone and distutils integration. This is not for helping people who struggle with reading. Should something be missing in the docs, then raise an issue._"

_Originally posted by @kayhayen in https://github.com/Nuitka/Nuitka/issues/575#issuecomment-1171510494_

Seems pretty harsh, as I don't seem to find any clear documentation on this either. I want to create a binary/executable file for my python application --> which means I want the --standalone mode. At the same time I do not want to include any compiled external dependencies, neither into the binary file, nor into the ".dist" and ".build" folder. All the dependencies will be provided by me, and I only want to include my source python files into the build. How do I do this with bdist_utils or distutils? I do not have any driven wheels in my project, and this is the only reference I've found to bdist_utils and distutils in the doc.

**Comment by kayhayen** [comment]
That mode is supported at this time. Probably that explains the lack of information how to do it.

**Comment by ai22m020** [comment]
Don't you mean it is NOT supported? Thanks for the reply.

**Comment by kayhayen** [comment]
@ai22m020 yes indeed. these boolean values are so easy to confuse, two is way too much values for anything :-)
