### ISSUE TITLE
`nuitka --help` is incomplete

### ISSUE THREAD

**Issue by bersbersbers** [Nuitka/Nuitka#2249]
Not reported, not sure if regression

```
1.6rc10
Commercial: None
Python: 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\bers\.pyenv-win-venv\envs\project_3.11\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).
```

- Python from python.org
- pip install https://github.com/Nuitka/Nuitka/archive/refs/heads/develop.zip
- `nuitka --help`

Output stops reproducibly at
```
the whole directory. All files are copied, if you want
                        to exclude files you need to remove them beforehand,
                        or use '--noinclude-data-files' option to remove them.
                        Default empty.
    --noinclude-data-file
(project_3.11) C:\Code\project>
```

**Comment by kayhayen** [comment]
What. Don't tell me years of despising users for not reading the help were unfounded.

I didn't immediately reproduce it on my systems, but I didn't use the installation method you used, and maybe it's a shortcoming of the script file.

**Comment by kayhayen** [comment]
Nah, I cannot reproduce it. Not sure, if you use something else than `virtualenv` that can cause different scripts to be created, and that could cause it, because for Nuitka we create batch files of our own making. I also updated to 3.11.3 to see if that regresses it, but I don't see why that would make a difference, but it broke my existing 3.11 installation, removing the python.exe, repairing it now.... well, maybe not so much a Nuitka bug very likely.

**Comment by kayhayen** [comment]
Nah, I think this one is a broken Python. Being interrupted, there looks like a crash of Python itself. Didn't happen for me, and not on other OSes. Just reinstall your Python, just like I had to do now due to the failure of the upgrade option.

**Comment by bersbersbers** [comment]
I can still reproduce it, so here's a few additional observations:

- `nuitka --help`:
```
                        or use '--noinclude-data-files' option to remove them.
                        Default empty.
    --noinclude-data-file
```

- `nuitka`:
```
                        or use '--noinclude-data-files' option to remove them.
                        Default empty.
    --noinclude-data-fileFATAL: 
Error, need filename argument with python module or main program.
```
(prints help even though `--help` is not part of the command line)

- Same things happen with `python -m nuitka` and `python -m nuitka --help`, so I don't think virtualenv scripts are involved here (but I may be wrong).

- In the debugger, the output looks complete and the process ends in `Options.parseArgs()` of `main()` via a `SystemExit` exception. Here's a stack trace:

```
04:
'  File "c:\\Users\\bers\\.vscode\\extensions\\ms-python.python-2023.8.0\\pythonFiles\\lib\\python\\debugpy\\_vendored\\pydevd\\_pydevd_bundle\\pydevd_runpy.py", line 124, in _run_code\n    exec(code, run_globals)\n'
05:
'  File "C:\\Users\\bers\\.pyenv-win-venv\\envs\\project_3.11\\Lib\\site-packages\\nuitka\\__main__.py", line 151, in <module>\n    main()\n'
06:
'  File "C:\\Users\\bers\\.pyenv-win-venv\\envs\\project_3.11\\Lib\\site-packages\\nuitka\\__main__.py", line 105, in main\n    Options.parseArgs()\n'
07:
'  File "C:\\Users\\bers\\.pyenv-win-venv\\envs\\project_3.11\\Lib\\site-packages\\nuitka\\Options.py", line 268, in parseArgs\n    is_nuitka_run, options, positional_args, extra_args = parseOptions(\n                                                          ^^^^^^^^^^^^^\n'
08:
'  File "C:\\Users\\bers\\.pyenv-win-venv\\envs\\project_3.11\\Lib\\site-packages\\nuitka\\OptionParsing.py", line 1838, in parseOptions\n    options, positional_args = parser.parse_args()\n                               ^^^^^^^^^^^^^^^^^^^\n'
09:
'  File "C:\\Users\\bers\\.pyenv\\pyenv-win\\versions\\3.11.3\\Lib\\optparse.py", line 1387, in parse_args\n    stop = self._process_args(largs, rargs, values)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
10:
'  File "C:\\Users\\bers\\.pyenv\\pyenv-win\\versions\\3.11.3\\Lib\\optparse.py", line 1427, in _process_args\n    self._process_long_opt(rargs, values)\n'
11:
'  File "C:\\Users\\bers\\.pyenv-win-venv\\envs\\project_3.11\\Lib\\site-packages\\nuitka\\utils\\CommandLineOptions.py", line 51, in _process_long_opt\n    return OptionParser._process_long_opt(self, rargs, values)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
12:
'  File "C:\\Users\\bers\\.pyenv\\pyenv-win\\versions\\3.11.3\\Lib\\optparse.py", line 1501, in _process_long_opt\n    option.process(opt, value, values, self)\n'
13:
'  File "C:\\Users\\bers\\.pyenv\\pyenv-win\\versions\\3.11.3\\Lib\\optparse.py", line 784, in process\n    return self.take_action(\n           ^^^^^^^^^^^^^^^^^\n'
14:
'  File "C:\\Users\\bers\\.pyenv\\pyenv-win\\versions\\3.11.3\\Lib\\optparse.py", line 808, in take_action\n    parser.exit()\n'
15:
'  File "C:\\Users\\bers\\.pyenv\\pyenv-win\\versions\\3.11.3\\Lib\\optparse.py", line 1559, in exit\n    sys.exit(status)\n'
```

- I tried adding `sleep`s and `flush`s before this exit call, without effect. But using print debugging, I can see that these lines are executed.

- I noticed I am using VS Code, and tried nuitka inside Windows Command prompt. It was gone! Also, redirecting the output to a file, it looks complete, even `type`ing it afterwards works.

- I wondered if this is a bug within `optparse` (which by the way is deprecated since Python 3.2), the VS Code terminal, or an interaction between the two. I checked `optparse`'s `print_help` function and noticed it prints all the help at once: `file.write(self.format_help())`. Nuitka's help is 38KB, which is quite a bit.

- I can reproduce this problem easily:
```
import sys

text = "".join([f"{i:04d} \n" for i in range(5000)])
sys.stdout.write(text)
```

This prints only lines up to 1249 for me.

I will report this to VS Code.

**Comment by bersbersbers** [comment]
That's another crazy one, if interested, follow https://github.com/microsoft/vscode-python/issues/21312 (which is a palindrome!)

**Comment by kayhayen** [comment]
I have done my trials in Visual Code too, albeit in bash there, and CMD outside of it. I have to commend you for getting to the ground of this. These shell tricks of Visual Code are naturally vulnerable to not being side effect free. I think I didn't try powershell in there, because my old Linux guy head will never make it to that in a thousand years unfortunately, even being on Windows all the time now.

But I guess, that solves it then. The help of Nuitka being big is not considered a bug. :-)

**Comment by bersbersbers** [comment]
fyi, `PYTHONUNBUFFERED` seems to cause this, see https://github.com/microsoft/vscode-python/issues/21312#issuecomment-1657230040
