### ISSUE TITLE
Anti reverse engineering

### ISSUE THREAD

**Issue by qfetu2xtqe** [Nuitka/Nuitka#2252]
Hi, can I use c, c++ source code protectors like "VMProtect" or "The Enigma Protector" as a protective layer that wraps the .exe file generated by Nuitka to increase security ?

**Comment by kayhayen** [comment]
For Python we have this: https://nuitka.net/doc/bundles.html

Such tools are of course useful. With Themida, interaction from within Python can control the VMs, so it can be way better for simple and powerful usages.
