### ISSUE TITLE
Missing support for Crypto.PublicKey ECC

### ISSUE THREAD

**Issue by gdworkman** [Nuitka/Nuitka#2256]
It appears that there are missing implicit dependencies for Crypto.PublicKey.ECC. The issue is present in Nuitka v1.1.5, as well as a 1.6 develop version (both installed with pip).

Using test code in test.py:

```python3
from Crypto.PublicKey import ECC
```

Compiling with options:

`python3 -m nuitka --standalone test.py`

Yields the following when running the compiled code:

```
Traceback (most recent call last):
  File "/vagrant/nuitka_bug/test.dist/test.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/vagrant/nuitka_bug/test.dist/Crypto/PublicKey/ECC.py", line 90, in <module Crypto.PublicKey.ECC>
  File "/vagrant/nuitka_bug/test.dist/Crypto/Util/_raw_api.py", line 309, in load_pycryptodome_raw_lib
OSError: Cannot load native module 'Crypto.PublicKey._ed25519': Not found '_ed25519.cpython-39-x86_64-linux-gnu.so', Not found '_ed25519.abi3.so', Not found '_ed25519.so'
```

Other info:

```
$ python3 -m nuitka --version

1.6
Commercial: None
Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
Flavor: Debian Python
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
Distribution: Debian 11
Version C compiler: /usr/bin/gcc (gcc).
```

```
$ pip3 freeze | grep crypto

asn1crypto==1.5.1
cryptography==38.0.4
oscrypto==1.3.0
pycryptodome==3.15.0
```

```
$ ls  test.dist/Crypto/PublicKey/ | grep so

_ec_ws.so

$ ls ~/.local/lib/python3.9/site-packages/Crypto/PublicKey/ | grep so

_ec_ws.abi3.so
_ed25519.abi3.so
_ed448.abi3.so
_x25519.abi3.so
```

**Comment by kayhayen** [comment]
There is always some methods being added to Crypto, or some packages that use them as a first, so this is unfortunately a constant thing, but usually very simple to add, however for the `pycryptodome` and `pycrytodomex` we still have python code to do them, and not the Yaml code, which means our docs to not apply. We one day need to make shared config between modules possible.

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.6.2 that I just made.
