### ISSUE TITLE
Is there any way to get the original python code from the stack captured by windbg?

### ISSUE THREAD

**Issue by xunilcyl** [Nuitka/Nuitka#2259]
As from my print log, My program is stuck on multiprocessing.Proces.start(), I use Windbg capture the stack trace, how can I translate it back to python stacktrace? Thanks!

More info: My program has a custom thread class, in its run() method will create 31 multiprocessing.Process instances and start them to do heavy task. There are two custom thread objects run at the same time(that is to say, maybe 62 processes will be created). 
 Most of time, it works fine. But occasionally after  37 processes started(), the thread stuck at calling the start() method of rest process instance and never return.  The 37 started processes completed their work, but never finished(can be seen in the task manager).

**_This is the stack captured by WinDbg._**
0:029> ~35kb
 RetAddr               : Args to Child                                                           : Call Site
00 00007ffd`75e35136     : 00000000`00000a6a 00000000`00000000 00000000`00000000 00000000`00000002 : ntdll!NtWriteFile+0x14
01 00007ffd`759b88b2     : 00008e49`9d6de067 00000000`0f4dc060 00000000`001b98dc 00000000`4fe6c634 : KERNELBASE!WriteFile+0x76
02 00007ffd`759b7d42     : 00000000`0f4dc060 00007ffd`759b3496 00000000`00000000 00000000`00000001 : ucrtbase!write_binary_nolock+0x52
03 00007ffd`759b7c2f     : 00000000`ffffffff 00000000`00000000 00000000`00000016 00007ffd`759b3496 : ucrtbase!_write_nolock+0xb2
04 00007ffd`22bed0ac     : 00000000`00000016 00000000`7a2fe4e0 00000000`00007fff 00007ffd`22b4b3d1 : ucrtbase!_write+0x8f
05 00007ffd`22bed007     : 00000000`00000000 00000000`0f4dc060 00000000`050c6180 00000000`3b41df40 : python39!PyErr_Occurred+0x20c
06 00007ffd`22becfac     : 00007ffd`22e9c140 00007ffd`22adf397 00000000`05057270 35420ab9`12b76941 : python39!PyErr_Occurred+0x167
07 00007ffd`22b48115     : 00000000`7a2fe4e0 00000000`00000002 00000000`00000000 00000000`4fe6c890 : python39!PyErr_Occurred+0x10c
08 00007ffd`22bbb388     : 00000000`00000000 00000000`7a2fe4e0 00000000`00000002 00000000`050c6180 : python39!PyObject_SetAttr+0x575
09 00007ffd`22b22771     : 00000000`40c6fbf0 00000000`050c6180 00000000`40c6fbf0 00000000`001b98dc : python39!PyObject_VectorcallMethod+0x88
0a 00007ffd`22b22f2c     : 00000000`40c6fbf0 00000000`00000000 00000000`4fe6c970 00007ffd`780b5ba1 : python39!PyErr_CheckSignals+0x181
0b 00007ffd`22b22ccc     : 00000000`00000000 00000000`0f4dc060 00000000`40c6fbf0 00000000`0f4dc040 : python39!PyMemoryView_FromMemory+0x348
0c 00007ffd`22ad7284     : 00000000`7a2fe4e0 00000000`40c6fbf0 00000000`794d1770 00007ffd`780b47b1 : python39!PyMemoryView_FromMemory+0xe8
0d 00007ffd`22b4699e     : 00000000`0f4dc060 00000000`00000001 00000000`3caff0e0 00007ffd`22b06cde : python39!PyType_GenericAlloc+0x1714
0e 00007ffd`22b46963     : 00000000`3caff0e0 00000000`794d1770 00000000`3f165100 00007ffd`22be1d2f : python39!PyObject_Size+0x9a
0f 00007ffd`22ac1986     : 00000000`3f165100 00000000`001b98dc 00000000`001b98dc 00000000`00000005 : python39!PyObject_Size+0x5f
10 00007ffd`22af814a     : 00000000`3f165100 00000000`3f165100 00000000`00000000 00000000`00000002 : python39!PyObject_IsAbstract+0x84a
11 00007ffd`22af8025     : 00000000`3f165100 00000000`00000002 00000000`0a70be30 00000000`0a70be30 : python39!PyAccu_Init+0x2f6
12 00007ffd`22ac1e1d     : 00000000`0f4dc040 00007ffd`22e8e050 00000000`00000000 00000000`3f165100 : python39!PyAccu_Init+0x1d1
13 00007ffd`22ac0dc7     : 00000000`00000000 00000000`3f165100 00000000`4fe6cc30 00000000`00000000 : python39!PyObject_IsAbstract+0xce1
14 00007ffd`22be3288     : 00000000`3c88a640 00000000`3c88a673 00000000`3c88a628 00000000`00000075 : python39!PyTuple_Size+0x7eb
15 00007ffd`22ac1e40     : 00000000`0503407d 00000000`3c88a640 00007ffd`22e8f8b0 00004a92`2bc86098 : python39!Py_MakePendingCalls+0x1048
16 00007ffd`22ac08d9     : 00000000`00000000 00000000`3f165100 00000000`4fe6cd49 00000000`05034040 : python39!PyObject_IsAbstract+0xd04
17 00007ffd`22ac1dce     : 00000000`033c18e0 00000000`1abd79b0 00000000`033c18e0 00000000`3f165152 : python39!PyTuple_Size+0x2fd
18 00007ffd`22ac0dc7     : 00000000`3caff270 00000000`3f165100 00000000`4fe6ce40 00000000`00000000 : python39!PyObject_IsAbstract+0xc92
19 00007ffd`22be3288     : 00000000`3c0ea580 00000000`3c0ea573 00000000`3c0ea528 00000000`00000075 : python39!PyTuple_Size+0x7eb
1a 00007ffd`22ac1e40     : 00000000`0000007d 00000000`3c0ea580 00007ffd`22e8f8b0 00000000`3c1bbc00 : python39!Py_MakePendingCalls+0x1048
1b 00007ffd`22ac1a18     : 00000000`00000000 00000000`3c93e118 00000000`3f165100 00000000`1abd7d60 : python39!PyObject_IsAbstract+0xd04
1c 00007ffd`22ac1253     : 00000000`3f165100 00000000`4fe6cf50 00000000`00000000 00000000`00000000 : python39!PyObject_IsAbstract+0x8dc
1d 00007ffd`22ac1c7f     : 00000000`3c93e100 00007ffd`22acc048 00000000`3cbf1030 00004a92`2bc86328 : python39!PyObject_IsAbstract+0x117
1e 00007ffd`22ac08d9     : 00000000`00000000 00000000`3f165100 00000000`4fe6d029 00000000`05034040 : python39!PyObject_IsAbstract+0xb43
1f 00007ffd`22ac1dce     : 00000000`3cbf10e0 00000000`1abd7d60 00000000`3cbf10e0 00000000`3f165152 : python39!PyTuple_Size+0x2fd
20 00007ffd`22ac1a18     : 00000000`3caffdb0 00000000`50533860 00000000`3f165100 00000000`00000000 : python39!PyObject_IsAbstract+0xc92
21 00007ffd`22ac12b3     : 00000000`3f165100 00000000`4fe6d130 00000000`00000001 00000000`0000000a : python39!PyObject_IsAbstract+0x8dc
22 00007ffd`22ac1c7f     : 00000000`50533840 00000000`05442670 00000000`00000030 00000000`1ea12828 : python39!PyObject_IsAbstract+0x177
23 00007ffd`22ac0dc7     : 00000000`00000000 00000000`3f165100 00000000`4fe6d1f0 00000000`00000000 : python39!PyObject_IsAbstract+0xb43
24 00007ffd`22be3288     : 00000000`3ebe4500 00000000`3ebe4573 00000000`3ebe4528 00000000`00000075 : python39!PyTuple_Size+0x7eb
25 00007ffd`22ac1e40     : 00000000`0503407d 00000000`3ebe4500 00007ffd`22e8f8b0 00004a92`2bc87ed8 : python39!Py_MakePendingCalls+0x1048
26 00007ffd`22ac08d9     : 00000000`00000000 00000000`3f165100 00000000`4fe6d309 00000000`05034040 : python39!PyObject_IsAbstract+0xd04
27 00007ffd`22ac1dce     : 00000000`50078160 00000000`017dc020 00000000`50078160 00000000`3f165152 : python39!PyTuple_Size+0x2fd
28 00007ffd`22b7890d     : 00000000`3caff590 00000000`3f165100 00000000`00000000 00000000`ffffffff : python39!PyObject_IsAbstract+0xc92
29 00007ffd`22be1c17     : 00000000`3f16512e 00000000`3f165100 00000000`00000480 00007ffd`22e99cd8 : python39!PyBytes_Resize+0x1d1
2a 00007ffd`22b48115     : 00000000`7a2fe4e0 00000000`3f6ebdc0 00000000`3f6ebdc0 00000000`017e2ec0 : python39!PyObject_GenericGetDict+0x397
2b 00007ffd`22ad7dd4     : 80000000`00000002 00000000`7a2fe4e0 00000000`3f6ebdc8 00000000`4fe6d670 : python39!PyObject_SetAttr+0x575
2c 00007ffd`22ae0b73     : 00000000`00000001 00000000`4fe6d670 00000000`4fe6d678 117b2a41`2003d326 : python39!Py_NewReference+0x2c4
2d 00007ffd`22ada5b6     : 00000000`3f6ebc40 00007ffd`22b2a76d 00000000`3f6ebda8 00000000`ffffffff : python39!PyEval_EvalFrameDefault+0x693
2e 00007ffd`22ad843c     : 00000000`00000002 dc4855ff`970ff353 00000000`00000003 00000000`00000000 : python39!PyFunction_Vectorcall+0x946
2f 00007ffd`22ae0d9b     : 00000000`00000000 00000000`4fe6d9e0 00000000`4fe6d9e8 e24178b0`9689ccf4 : python39!Py_NewReference+0x92c
30 00007ffd`22ad9de4     : 00007ffd`22e99cd8 00007ffd`22cebbc8 00000000`0a612ec0 00000000`4fe6dba0 : python39!PyEval_EvalFrameDefault+0x8bb
31 00007ffd`22b2a702     : 00000000`05081a80 00000000`00000000 00000000`05081a80 00000000`00000005 : python39!PyFunction_Vectorcall+0x174
32 00007ffd`22ad84e2     : 00000000`00000000 00000000`7a2fe4e0 00000000`00000000 00000000`3f6e7940 : python39!PyObject_CallObject+0x1e6
33 00007ffd`22ae0972     : 00000000`7a2fe4e0 00000000`4fe6de58 00000000`7a2fe4e0 00000000`076aae00 : python39!Py_NewReference+0x9d2
34 00007ffd`22ad8056     : 00000000`00000001 80000000`00000001 00000000`07912230 00000000`00000000 : python39!PyEval_EvalFrameDefault+0x492
35 00007ffd`22ae0d9b     : 00000000`00000000 00000000`05081a80 00000000`4fe6e0e8 00000037`771e45d6 : python39!Py_NewReference+0x546
36 00007ffd`22ad8056     : 00000000`49b2f020 00000000`7a2fe4e0 00000000`47d08740 00000000`7b26fcb8 : python39!PyEval_EvalFrameDefault+0x8bb
37 00007ffd`22ae0d9b     : 00000000`053a1128 00000000`05081a80 00000000`00000005 00000000`05081a80 : python39!Py_NewReference+0x546
38 00007ffd`22ad9de4     : 00000000`00000000 00000000`053a2368 00000000`057b2140 00000000`4fe6e5c0 : python39!PyEval_EvalFrameDefault+0x8bb
39 00007ffd`22ad699b     : 00000000`05081a80 00000000`057c1430 00000000`05081a80 00000000`4fe6e660 : python39!PyFunction_Vectorcall+0x174
3a 00007ffd`22b2afcc     : 00007ffd`22ad6d30 00000000`00000001 00000000`3cbe0130 00000000`05065bd0 : python39!PyType_GenericAlloc+0xe2b
3b 00000000`0a4291c0     : 00000000`38f93220 00000000`3ca9f900 00000000`4fe6e7b0 00000000`00000000 : python39!PyVectorcall_Call+0x5c
3c 00000000`0a42fefc     : 00000000`3ed80420 00000000`3ca9f900 00000000`4a6b8b18 00007ffd`22acb28c : framework!PyInit_framework+0x1f7870
3d 00000000`0a4323d7     : 00000000`017dc020 00000000`50078160 00007ffd`22e99cd8 00000000`0c3a4df0 : framework!PyInit_framework+0x1fe5ac
3e 00000000`0a1914da     : 00000000`50078160 00000000`01aaa4f0 00000000`3dd2b3c0 00000000`3ca9f900 : framework!PyInit_framework+0x200a87
3f 00000000`0a122d39     : 00000000`1ea12d60 00000000`1ea01cb0 00000000`3d9cb200 00000000`00000000 : framework+0x714da
40 00000000`0a184b0e     : 00000000`3c88ac80 00000000`3c88ac80 00000000`500518f0 00000000`00000000 : framework+0x2d39
41 00000000`0a43103a     : 00000000`49ad5c88 00000000`1b721f80 00000000`1ea12c70 00000000`1ea05970 : framework+0x64b0e
42 00000000`0a180a9e     : 00000000`1ea124f0 00000000`497f5050 00000000`40d25f40 00000000`00000000 : framework!PyInit_framework+0x1ff6ea
43 00000000`0a43103a     : 00000000`49ad5c88 00000000`0a41061e 00000000`1ea12a90 00000000`05074b30 : framework+0x60a9e
44 00000000`0a1b0bd6     : 00000000`00000000 00000000`3f165570 00000000`00000000 00000000`00000000 : framework!PyInit_framework+0x1ff6ea
45 00000000`0a43103a     : 00000000`472cd408 00000000`3ef01730 00000000`1ea556d0 00000000`1e9f78f0 : framework+0x90bd6
46 00000000`0a1d8c19     : 00000000`3f6d5100 00000000`114e2440 00000000`3ef01730 00000000`3b6aca60 : framework!PyInit_framework+0x1ff6ea
47 00000000`0a4300e2     : 00000000`3dc06340 00000000`00000000 00000000`05a733d0 00007ffd`22b97484 : framework+0xb8c19
48 00000000`0a4323d7     : 00000000`500ac880 00000000`1b720080 00000000`1d6a91a0 00000000`00000000 : framework!PyInit_framework+0x1fe792
49 00000000`0a35373b     : 00000000`00000000 00000000`40c969e0 00000000`00000000 00000000`00000000 : framework!PyInit_framework+0x200a87
4a 00000000`0a4126a2     : 00000000`1ea57d60 00000000`0a4125c0 00000000`01b26610 00000000`05591b40 : framework!PyInit_framework+0x121deb
4b 00000000`0a412c64     : 00000000`7a2fe4e0 00000000`491c3ba8 00000000`00000001 00000000`00000000 : framework!PyInit_framework+0x1e0d52
4c 00007ffd`22ad7dd4     : 00000000`4fe6f7c8 00000000`1c891590 00000000`05074b30 00000000`1c8915a8 : framework!PyInit_framework+0x1e1314
4d 00007ffd`22ae0b73     : 00000000`00000001 00000000`4fe6f860 00000000`4fe6f868 3f3d2f8d`00000000 : python39!Py_NewReference+0x2c4
4e 00007ffd`22ad8056     : 00000000`1616da80 00007ffd`69126a50 00000000`491c3a30 00000000`00000001 : python39!PyEval_EvalFrameDefault+0x693
4f 00007ffd`22ae0b73     : 00000000`00000000 00000000`05081a80 00000000`00000000 00007ffd`78090000 : python39!Py_NewReference+0x546
50 00007ffd`22ad9de4     : 00000000`00000000 00000000`00000000 00000000`0558d640 00000000`00000000 : python39!PyEval_EvalFrameDefault+0x693
51 00007ffd`22ad699b     : 00000000`05081a80 00000000`055ad160 00000000`05081a80 00000000`00000000 : python39!PyFunction_Vectorcall+0x174
52 00007ffd`22b2afcc     : 00000000`7a2fe4e0 00007ffd`22b7b45b 00007ffd`22ecc858 00000000`00000001 : python39!PyType_GenericAlloc+0xe2b
53 00007ffd`22b2adcf     : 00000000`7a2fe4e0 00000000`3c1d4a00 00000000`00000000 00007ffd`780b47b1 : python39!PyVectorcall_Call+0x5c
54 00007ffd`22b6610e     : 00000000`3ef65c30 00000000`00000000 00000000`00000001 00000000`7a2fe4e0 : python39!PyObject_Call+0x4f
55 00007ffd`22b6608a     : 00000000`79ae78a0 00007ffd`22b6609c 00000000`00000000 00000000`00000000 : python39!Py_InitializeFromConfig+0x39e
56 00007ffd`759c1bb2     : 00000000`7b2cac30 00000000`00000000 00000000`00000000 00000000`00000000 : python39!Py_InitializeFromConfig+0x31a
57 00007ffd`77cf7614     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ucrtbase!thread_start<unsigned int (__cdecl*)(void *),1>+0x42
58 00007ffd`780e26a1     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : KERNEL32!BaseThreadInitThunk+0x14
59 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21

  > python -m nuitka --version
0.6.13.2
Python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Users\test\Anaconda3\envs\myenv\python.exe
OS: Windows
Arch: x86_64

* How did you install Nuitka and Python
anaconda.

**Comment by kayhayen** [comment]
Please use a recent version of Nuitka.
