### ISSUE TITLE
The --recurse-to option is not working when python version 3.10.11 is installed

### ISSUE THREAD

**Issue by abhigpt548** [Nuitka/Nuitka#2268]
I am trying to build one image using the nuitka build image of Nuitka release verison 1.6 (i.e. Nuitka-1.6.tar.bz2), but when i am trying to use the --recurse-to option inside the container created from nuitka image then i am getting below error:
"**nuitka: error: no such option: --recurse-to**"
![image](https://github.com/Nuitka/Nuitka/assets/52811688/52e5bf36-227b-44b9-bc55-1d3542a9264b)

The python version installed is : 3.10.11
In the Nuitka documentatioin from the fowlloing url : **"https://github.com/Nuitka/Nuitka/blob/develop/.github/ISSUE_TEMPLATE.md"** , says that instead of --recurse-* we can use --follow-* but same type of error is displaying with the follow as well refer below screenshots for Nuitka Documantion as well as the error displaying when we use **follow** instead of **recurse**:
![image](https://github.com/Nuitka/Nuitka/assets/52811688/7c2b1c96-7abe-4c47-b8c0-f4167895c703)
![image](https://github.com/Nuitka/Nuitka/assets/52811688/ee5790be-0efe-4f45-abe1-730c0f36986f)

Can anyone please help me with this , or is it a bug?

**Comment by kayhayen** [comment]
Please read the docs, help output specifically.
