### ISSUE TITLE
Support running as Windows service

### ISSUE THREAD

**Issue by deajan** [Nuitka/Nuitka#227]
Hello,

I'm having a hard time trying to write a Windows service that works once compiled with Nuitka.
The standard way of creating a Python service works with win32serviceutil, but relies on an executable (pythonservice.exe) to load python code.
Once compiled, my code cannot be loaded by pthonservice.exe anymore since it doesn't expect to load executables, but plain python code.

From what I have read, a Windows executable needs to have a SvcMain function that is called from the Windows service manager, as in https://docs.microsoft.com/fr-fr/windows/desktop/Services/svc-cpp

I know this is a (very) long shot, but....
Do you know any way to write python code that will create such a function once compiled with Nuitka?

Best regards.

**Comment by kayhayen** [comment]
I think that this has been achieved with Nuitka already, and I don't think it had to be that way, instead I was looking at what `py2exe` did at the time and walked away with the idea it would be relatively straight forward.

You can compile an extension module from all your code, and call into that, `pythonservice.exe` ought to be able to load those. Can you explore that direction? Obviously that is not standalone, or not something that standalone supports yet.

Right now I am to busy with other things, but I will revive what I had found about this checking my emails from some time ago.

**Comment by kayhayen** [comment]
Have a brief look at the service example source code you linked to, it doesn't appear to be rocket science though, and something we can add to `MainProgram.c` conditionally so it works with standalone mode binaries, which will always be simpler.

I would love Nuitka to be compatible with `py2exe` and how it specifies things in distutils, just steal the responsibility for executing/packaging from it.

**Comment by deajan** [comment]
I'd love to be able to use native Python windows services too, without using any service wrapper like srvany (non supported) or nssm (seen as virus by some antivirus software).
Anyway, my C knowledge == 0 here, so as much as I would love to see that feature, I am not able to help more than doing loads of tests.

**Comment by kayhayen** [comment]
I am taking this one @deajan 

As for setup.py config, there appears to be not all that much:

http://www.py2exe.org/index.cgi/py2exeAndWindowsServices

My goal will be to make a hello world service work with `py2exe` and then to hack distutils much like we do already for wheels, to optionally steal responsibility from `py2exe` dealing with the service definition. Then using your linked code, fill in the values, and include it in the binary.

That should produce a different kind of binary with the service command line.

**Comment by deajan** [comment]
@kayhayen I know your time is valuable, but did you get any time to look into this ?

**Comment by kayhayen** [comment]
Not yet @deajan but I did remember it last week as a promise I didn't yet keep. But I will make I sure I get to it. I am currently all caught up in the pefile/depends.exe final merge, and this will then be my next non-optimization task, OK ? (I tend to make one like these and one like that in parallel, mostly so when I get fed up with one type of work, I have another one where it works smoother) :-)

**Comment by deajan** [comment]
@kayhayen Sorry to bug you again, but it would help me so much being able to run nuitka compiled programs as windows services... I'd sponsor this personnaly if needed :)
Any chance you'll have a look someday ? Best regards.

**Comment by kayhayen** [comment]
So, I looked at the example, and I think, we need new abilities for a plugin, so this can work.

1. Plugins need to be allow to provide arbitrary C files to be included in the final result. That is normally
a no-go, as Nuitka is not intended to be friendly to inclusion of C++ codes. People frequently want to call their libraries this way, and that is not going to work.
2. Similarly, linking against Advapi32 library needs to be enabled by such a plugin, to be able to use the DLL to register the service.
3. With this, we can inject the service code. The ``install`` command for normal execution, is something we ought to be able to intercept, so injecting code very early in `main()` to be allowed to handle arguments would be sweet. The multiprocessing code already has its hardcoded hooks there. It would be sweet to make that re-usable.
4. It's unclear, when your `__main__` code should be run, and how stopping the service should interact it, do we throw a SystemExit exception much like `KeyboardInterupt` into it and allow some cleanup, is it a separate process, or a thread. I assume in `SvcInit` we get to wait for the stop in a thread, and can launch `__main__` in another. It may well be cleaner, to let the process go as a separate process from there, because that has less implications on Python thread handling, monitoring exit, Python signal handling, etc. In this case, we could also be talking of a wrapper binary, but I don't think we need to go there.

Extending the plugin API in this way. I am tagging @JorjMcKie as he should keep an eye, on what I do with the plugin API there.

That sounds like a plan, where no step is really hard, lets see it. For naming, how about `windows-service`  for the plugin.

**Comment by JorjMcKie** [comment]
Interesting stuff! I need a bit of time to better understand what this all is about.
Will do my best to support ...

**Comment by kayhayen** [comment]
This is basically about making the command line handling of the program intercept stuff, and add a way to install it as a Windows service. I am still researching some things. I am adding the infrastructure for the plugin right now.

I got side tracked by looking at the layout of C files in the build folder. I want plugins to have their own namespace in terms of a dedicated folder, for C files they create. Noticed how and why `ccache` usage is so broken, and fixed it. See gitter community chat. But that's the next thing I am doing. I added link libraries for now.

**Comment by kayhayen** [comment]
So adding link libraries, adding code files, is on factory branch now, didn't test it yet, I guess, this leaves the command line stuff out in the open, but I am going to try that out next. Should it work, I guess, command line handling needs to become something collectively composed by plugins in the dynamic part instead of `MainProgram.c` which is static now.

My understanding right now, is that in `main()` the code has to register service entry points. The `SrvMain` is not exposed by the executable directly, or is it? I will have check this with an actual compilation.

**Comment by kayhayen** [comment]
I got the code to actually do what it promised. Plugin code filenames are now namespaced actually included in the compilation, and the extra code feature actually usable.

Also, the example from Microsoft was using ANSI filenames, with which I have very bad experience on Python2 at least, with unicode paths, so I migrated it all to unicode paths, which should make it more robust.

Now the command line handling issue is most pressing. I am a bit at loss, how the "install" actually works, I guess the installer calls it with install at the end, and then it makes itself known, and then only gets called? I am a little without knowledge on that side of things. I guess, I will play around a bit, and maybe later understand.

@deajan how do you install the service right now, is there an InstallShield that does it or what?

**Comment by deajan** [comment]
There are multiple ways to install a service, the easiest being the use of windows service utilities themselves.

`
sc create "myPythonService" binpath= "c:\myapp\my_servicex.exe" type= share start= auto
`

Please note that the spaces after equal signs are mandatory.
You can then use sc to query the service, start or stop it.

**Comment by kayhayen** [comment]
I am trying to debug this by executing a program, which creates a file, but I cannot find the output of it, which is weird. Maybe it cannot write where it runs?

**Comment by kayhayen** [comment]
I am not observing any arguments being given. I need to revisit the code that checks for `ìnstalled` as an argument, but chances are I am confused. I was expecting to be called with that.

**Comment by kayhayen** [comment]
```
    // If command-line parameter is "install", install the service.
    // Otherwise, the service is probably being started by the SCM.
```

So this confused me, the service seems to handle self-installation. Not sure if we care about that immediately. But for that, we need to hook the command line parsing. But I guess, the plugin should after command line handling, and before `__main__` starts, do its thing to respond to the Windows service, which my `Garbage.dist\Garbage.exe` right now doesn't do. Surely we will then want to have parameters for the installation, e.g. name.

**Comment by kayhayen** [comment]
Ok, seems the service name is a mandatory argument. I wonder if we could default it to the binary name, perhaps. I hard coded it, et voila, started and stopped the service, so I think the folklore is under control.

Next up is creating the thread, that will be used to run the Python code. And if that works, we won. :-)

**Comment by kayhayen** [comment]
So, I managed to see the Python code running in the service. I am terminating the thread now, when you ask to stop the service, without question, I guess throwing a sort of SystemExit exception or even KeyboardInterrupt would be good. Any proposals?

Also, the Python code exited, and the service was still considered running. I need to convert its exit code back to STOPPED and somehow a failure report. I guess, tracebacks from main module should lead to something logged.

I am stopping there for now. I will do a few cleanups over the coming day, then put it out for experimentation of yours @deajan as it's still very ugly. We are going to have a chat, once I complete the remaining minor tweaks, for now I think getting 0.6.7 out is more important, as this will need some fiddling as well, but I think I got a good idea. Unsure about the testing side.

I did not extend the plugin framework to do arbitrary command line handling, or alternative main entry points, this is way too specific, and too much effort probably.

As for the `install` command line, that ought to work, I will test it next time around.

**Comment by kayhayen** [comment]
Also, currently I only tried with MSVC and Python 2.7, and I think the later is unlikely to be any difference or issue except for command line parsing, always unsure about MinGW64, that may also reveal a few things. The Microsoft example code is not geared for portability, that much is clear. I cleaned up most of it, but there is likely more.

**Comment by deajan** [comment]
I'll get a bit time next week to play with the service implementation.
I use to compile on MinGW so that will be tested.

As for the thread notifiying the main program about exiting, I think a KeyboardInterrupt is just great, since there's no way such a service could have a console anyway.

The only thing that bugs me is the service name, which should be "pretty".
I mean as a sysadmin I am more scared when I see a service like "mnpstds" instead of "My Nice Python Service That Does Stuff".

If you have some kind of quick howto, I'll be happy to try.

**Comment by kayhayen** [comment]
I think I will ready everything this weekend, the actual windows service plugin is not yet out in the open, but mostly for no good reason right now. I will publish it soon. I was adding command line handling for plugins that makes sense and am caught in the action, like changing all plugins over to the new optparse style, just so I didn't have to add a stupid manual option again.

Yours,
Kay

**Comment by jasonbrown-helios** [comment]
Hi @kayhayen I am so happy that I have come across this thread as we are currently having lots of issues with Pyinstaller built windows service exe's and various client Antivirus quarantining the service. Nuitka seems to be working in our dev environment on our non "windows service" exe's so getting it to successfully compiling windows services will be great.  Happy to assist with any testing etc and also happy to make a financial contribution to help get it across the line.

**Comment by kayhayen** [comment]
@jasonbrown-helios can you in touch with me via private email, this is certainly an option

**Comment by deajan** [comment]
@kayhayen Please also give me the instructions so I can play with the service ;)

**Comment by Ben-Faessler** [comment]
@kayhayen do you plan to release this great feature in the near future? It's been a year since your last comment...

**Comment by kayhayen** [comment]
Thanks to @jasonbrown-helios and @deajan this has been sponsored and is part of the Nuitka commercial offering at https://nuitka.net/pages/commercial.html
