### ISSUE TITLE
"subprocess.CalledProcessError" when executing on github action

### ISSUE THREAD

**Issue by djkcyl** [Nuitka/Nuitka#2271]
github action ubuntu host
python 3.10

**err log:**
https://github.com/djkcyl/BBot-Graia/actions/runs/5165382643/jobs/9309878508

**command:**
```
pdm add nuitka zstandard ordered-set
pdm run python -m nuitka --onefile --standalone --show-progress --assume-yes-for-downloads --output-dir=nuitka --windows-icon-from-ico=tv.ico --user-package-configuration-file=nuitka-lite.yml main.py
```

**Comment by kayhayen** [comment]
The relevant bit is this:

```
    return count, struct.pack("h", count) + result.getvalue()
struct.error: short format requires (-0x7fff - 1) <= number <= 0x7fff
```

So one module has a too large amount of constant data. We don't get to know which one unfortunately, I will try and add an error that points out the trouble maker. Also using signed value for the size might be a stupid idea anyway.

**Comment by kayhayen** [comment]
Thanks for your report, this is giving enhanced output  on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
Is there going to be something coming forth here?

**Comment by kayhayen** [comment]
This is now on the develop branch.

**Comment by kayhayen** [comment]
Closing for lack of feedback.

**Comment by kayhayen** [comment]
The change made for analysing this better is now in 1.7 release.
