### ISSUE TITLE
ModuleNotFoundError: No module named 'socket'

### ISSUE THREAD

**Issue by Juniorsnet** [Nuitka/Nuitka#2274]
Nuitka do not import package "socket and "queue" when use python loggin module.

I use nuitka throug wine has windows environment.

`wine python -m nuitka --version`

```
1.6.1
Commercial: None
Python: 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\users\gsus\AppData\Local\Programs\Python\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).
```
* How did you install Nuitka and Python

`wine python -m pip install -U nuitka`

* The specific PyPI names and versions

> wine python -m pip freeze

```
altgraph==0.17.3
intelhex==2.3.0
Nuitka==1.6.1
ordered-set==4.1.0
pefile==2023.2.7
psycopg-binary==3.1.8
pyinstaller==5.9.0
pyinstaller-hooks-contrib==2023.1
pyserial==3.5
PySide6==6.4.2
PySide6-Addons==6.4.2
PySide6-Essentials==6.4.2
pywin32-ctypes==0.2.0
shiboken6==6.4.2
tinyaes==1.0.4
zstandard==0.21.0
```
* Also supply a Short, Self Contained, Correct, Example

```
import logging, logging.handlers

def main():
    logging.basicConfig(format='%(asctime)s | %(levelname)s | %(message)s',
                        level=logging.INFO,
                        handlers=(logging.FileHandler("example.log"),
                                  logging.StreamHandler())
                        );
    logging.info('Start of program')
    print(factorial(5))
    logging.info('End of program')

def factorial(n):
    logging.info('Start of factorial(%s)'  % (n))
    total = 1
    for i in range(n + 1):
        total *= i
        logging.info('i is ' + str(i) + ', total is ' + str(total))
    logging.info('End of factorial(%s)'  % (n))
    return total

if(__name__=="__main__"):
    main();
```

* Provide in your issue the Nuitka options used

 wine python -m nuitka --follow-imports --standalone TestLoggin.py

However if I add options --include-package=socket --include-package=queue the binary file works perfect.

**Comment by kayhayen** [comment]
That is due to the attempt to reduce the minimal size of programs. I guess, logging is very common, and would have to work, and it does.

**Comment by kayhayen** [comment]
Adding `logging` will potentially hurt with some extension modules using it without indicating that, but we got to go that route eventually. I am not adding back manual dependencies there.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.6.2 that I just made.
