### ISSUE TITLE
How to use a VS2017-windowsXP (v141_xp)?

### ISSUE THREAD

**Issue by HIllya51** [Nuitka/Nuitka#2281]
How to use a VS2017-windowsXP (v141_xp)?

**Comment by HIllya51** [comment]
sorry, I found it.

**Comment by HIllya51** [comment]
I used "--msvc=list", but there are only 14.3 and 14.1.
But I want to use "141_xp" rather than "141"
![批注 2023-06-11 070925](https://github.com/Nuitka/Nuitka/assets/101191390/15188ffe-297a-4395-8da8-d5ff7ad0f2e4)
![批注 2023-06-11 070912](https://github.com/Nuitka/Nuitka/assets/101191390/556e95ca-d141-4222-8fba-3b3b23205a75)

**Comment by HIllya51** [comment]
I have tested "--msvc=14.1" can only use the normal v141 rather than v141_xp, the built program can't run on windows xp.

**Comment by kayhayen** [comment]
Nuitka commercial is offering support for Windows XP targeting users, but I cannot do it here. 

https://nuitka.net/doc/commercial.html
