### ISSUE TITLE
Standalone compilation of project using tsfresh fails due to inclusion of Numba

### ISSUE THREAD

**Issue by anates** [Nuitka/Nuitka#2288]
Hei,
I'm trying to compile a project containing tsfresh/numba, but compilation fails (as detailed below). Is there a way to actually compile such a project using nuitka, or is that (currently) not possible?
Thanks!

* Please check whether the bug was already reported or fixed.

Not as far as I can see

* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version

```
1.7rc1
Commercial: None
Python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: ~\env\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\cl.exe (cl 14.3).
```

* How did you install Nuitka and Python

Installed python via conda, then created a separate venv. Afterwards, I installed nuitka using pip within the environment

* The specific PyPI names and versions

  > python -m pip freeze

```
absl-py==1.4.0
aiofiles==22.1.0
aiosqlite==0.19.0
anyio==3.6.2
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
astroid==2.15.5
asttokens==2.2.1
attrs==23.1.0
Babel==2.12.1
backcall==0.2.0
beautifulsoup4==4.12.2
black==23.3.0
bleach==6.0.0
cachetools==5.3.0
certifi==2023.5.7
cffi==1.15.1
charset-normalizer==3.1.0
click==8.1.3
cloudpickle==2.2.1
colorama==0.4.6
coloredlogs==15.0.1
comm==0.1.3
contourpy==1.0.7
cycler==0.11.0
dask==2023.5.0
debugpy==1.6.7
decorator==5.1.1
defusedxml==0.7.1
dill==0.3.6
distributed==2023.5.0
docutils==0.20.1
exceptiongroup==1.1.1
executing==1.2.0
fastjsonschema==2.17.1
flatbuffers==23.5.9
fonttools==4.39.4
fqdn==1.5.1
fsspec==2023.5.0
gitdb==4.0.10
GitPython==3.1.31
google-auth==2.19.0
google-auth-oauthlib==1.0.0
grpcio==1.54.2
h5py==3.8.0
humanfriendly==10.0
idna==3.4
importchecker==2.0
importlib-metadata==6.6.0
iniconfig==2.0.0
interchange==2021.0.4
ipykernel==6.23.1
ipython==8.13.2
ipython-genutils==0.2.0
ipywidgets==8.0.6
isoduration==20.11.0
isort==5.12.0
jedi==0.18.2
Jinja2==3.1.2
joblib==1.2.0
json5==0.9.14
jsonpointer==2.3
jsonschema==4.17.3
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.6.3
jupyter-ydoc==0.2.4
jupyter_client==8.2.0
jupyter_core==5.3.0
jupyter_server==2.6.0
jupyter_server_fileid==0.9.0
jupyter_server_terminals==0.4.4
jupyter_server_ydoc==0.8.0
jupyterlab==3.6.3
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.7
jupyterlab_server==2.22.1
kiwisolver==1.4.4
lazy-object-proxy==1.9.0
llvmlite==0.39.1
locket==1.0.0
Markdown==3.4.3
MarkupSafe==2.1.2
matplotlib==3.6.0
matplotlib-inline==0.1.6
mccabe==0.7.0
mistune==2.0.5
monotonic==1.6
mpmath==1.3.0
msgpack==1.0.5
mypy==1.3.0
mypy-extensions==1.0.0
nbclassic==1.0.0
nbclient==0.8.0
nbconvert==7.4.0
nbformat==5.8.0
nest-asyncio==1.5.6
nodejs==0.1.1
notebook==6.5.4
notebook_shim==0.2.3
npTDMS==1.6.2
Nuitka @ https://github.com/Nuitka/Nuitka/archive/factory.zip
numba==0.56.4
numpy==1.23.5
oauthlib==3.2.2
onnx==1.14.0
onnxconverter-common==1.13.0
onnxmltools==1.11.2
onnxruntime==1.15.0
optional-django==0.1.0
ordered-set==4.1.0
orderedset==2.0.3
overrides==7.3.1
packaging==23.1
pandarallel==1.6.5
pandas==1.5.3
pandocfilters==1.5.0
pansi==2020.7.3
parso==0.8.3
partd==1.4.0
pathspec==0.11.1
patsy==0.5.3
pickleshare==0.7.5
Pillow==9.5.0
platformdirs==3.5.1
pluggy==1.0.0
prometheus-client==0.17.0
prompt-toolkit==3.0.38
protobuf==3.20.3
psutil==5.9.5
pure-eval==0.2.2
py2neo==2021.2.3
pyarrow==9.0.0
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
pyflakes==2.5.0
Pygments==2.15.1
pylint==2.17.4
pyoxidizer==0.22.0
pyparsing==3.0.9
pyreadline3==3.4.1
pyrsistent==0.19.3
PySide6==6.3.2
PySide6-Addons==6.3.2
PySide6-Essentials==6.3.2
PySimpleGUI==4.60.5
pytest==7.3.1
python-dateutil==2.8.2
python-json-logger==2.0.7
pytz==2023.3
PyWavelets==1.4.1
pywin32==306
pywinpty==2.0.10
PyYAML==6.0
pyzmq==25.0.2
qtconsole==5.4.3
QtPy==2.3.1
requests==2.31.0
requests-oauthlib==1.3.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rsa==4.9
scikit-learn==1.2.2
scipy==1.10.1
seaborn==0.12.2
Send2Trash==1.8.2
shap==0.41.0
shiboken6==6.3.2
six==1.16.0
skl2onnx==1.14.1
slicer==0.0.7
smmap==5.0.0
snakeviz==2.2.0
sniffio==1.3.0
sortedcontainers==2.4.0
soupsieve==2.4.1
stack-data==0.6.2
statistics==1.0.3.5
statsmodels==0.14.0
stumpy==1.11.1
sympy==1.12
tblib==1.7.0
tensorboard==2.13.0
tensorboard-data-server==0.7.0
terminado==0.17.1
threadpoolctl==3.1.0
tikzplotlib==0.10.1
tinycss2==1.2.1
tomli==2.0.1
tomlkit==0.11.8
toolz==0.12.0
torch==1.12.1+cu116
torchaudio==0.12.1+cu116
torcheck==1.0.1
torchvision==0.13.1+cu116
tornado==6.3.2
tqdm==4.65.0
traitlets==5.9.0
tsfresh==0.20.0
typing_extensions==4.6.2
uri-template==1.2.0
urllib3==1.26.16
wcwidth==0.2.6
webcolors==1.13
webencodings==0.5.1
websocket-client==1.5.2
Werkzeug==2.3.4
widgetsnbextension==4.0.7
wrapt==1.15.0
xgboost==1.7.5
y-py==0.5.9
ypy-websocket==0.8.2
zict==3.0.0
zipp==3.15.0
zstandard==0.21.0
```

* Also supply a Short, Self Contained, Correct, Example

MWE: 
```
"""_summary_
"""
import sys
import os

from PySide6 import QtGui
from PySide6.QtWidgets import QApplication
import tsfresh

if __name__ == "__main__":
    print("Hello World!")
```

* Provide in your issue the Nuitka options used

This problem was tested using two different commands:

`nuitka --standalone --enable-plugin=pyside6 --report=compilation-report.xml main.py`

Compilation worked, execution failed with
[with_integrated_numba_output.log](https://github.com/Nuitka/Nuitka/files/11755273/with_integrated_numba_output.log)

When compiling instead using 
`nuitka --standalone --enable-plugin=pyside6 --noinclude-numba-mode=nofollow --report=compilation-report.xml main.py`

execution fails with 
[no_integrated_numba_output.log](https://github.com/Nuitka/Nuitka/files/11755283/no_integrated_numba_output.log)

* Note if this is a regression

Not sure if it has worked before.

**Comment by kayhayen** [comment]
Ah, the report would have been valuable. But JIT compilation of numba is not going to fly yet, because we have no good way of making source code available for it, yet, and still compile code, and we do not have support for including some modules as python files, for it to see.

However, on develop I recently made a new trick, for PyQt5 actually, which has a `@pyqtslot` decorator, such that the functions with that, do get compiled to bytecode. I also forsaw that the source code would be available in the future for these. So one day, maybe things like numba JIT may become usable, but of course, we want to make it obsolete really, but that's not happening in its entirety ever, if at all.

But I cannot tell how long it is to have that.

That being said, we also remove useless numba uses from packages, here `stumpy` seems to be to blame. I can give it a quick shot, but as an example, the import is not really telling me much, if the result would be very usable.

**Comment by kayhayen** [comment]
Minor correct, in accelerated mode, it's probably just fine maybe.

**Comment by kayhayen** [comment]
So, it's using `distributed` and by proxy `dask`, which is usually not what you want, doing some anti-bloat work to reduce the compilation of `tsfresh`, but I have a suspect, that it's really stumpy. I am getting numpy usage from pandas there, so that's probably the reason, but we shall see.

**Comment by kayhayen** [comment]
This is really drawing circles, `statsmodel.sandbox` as a namespace for otherwise useful things, pulls in pytest, removing that like we do for a bunch of numpy/scipy already, and `pandas.core.groupby.groupby` pulls in `numba` which we apparently didn't see so far, but easily removable as well. Not sure if we end up in a usable place, but at least it seems some things are getting more robust against numba usage, not even needing the nofollow approach, which would work for `pandas` most likely.

**Comment by kayhayen** [comment]
So, I have done quite a bit of anti-bloat, for patsy, statsmodels, etc. but it seems `stumpy` is using a distribution location from `pkg_resources` and we may not yet support that, or I don't get why it would be `None` preventing it from doing something stupid with files. I might want to first add that I guess.

**Comment by kayhayen** [comment]
So, that `pkg_resources` fix is coming to the hotfix, but so far only `stumpy` needs it, but for avoiding the `numba` package it's a lost cause, no way that is going to happen.

On the upside for this issue, tsfresh uses it in one function only, and then only with some condition. Can you try current factory branch and confirm it helps some.

There is plenty of anti-bloat work in there, I believe for tsfresh it may have been complete, I forgot, this is not a priority issue at all. Need some interactivity here. But statsmodels and patsy, even numpy and pandas got more work against using `pytest`, `numba`, and `unittest` which should be generally a good idea.

**Comment by anates** [comment]
Hei,
I recompiled both my py-file above and my full code using 1.7rc4, thanks! However, now I encountered the following two issues:

- Running the small py-file listed above works, but I do not get any console output (even though I print "Hello World")
- Running my full program results in an error, hinting to a wrong pointer (Command on address 0xxxxxx pointed to memory in 0xFFFFFFFFFFFFFxxx. Could not read from this address")

What are the next steps I could to to assist with debugging?

**Comment by kayhayen** [comment]
Actually I think I also saw some kind of crash on Windows at least, but sporadically, and it went away with `--debug` so I turned to the known corruption bug, that is fixed now too, but it doesn't appear to be that. I might try compiling on Linux, where debugging will be potentially more revealing.

**Comment by kayhayen** [comment]
Part of the 1.7 release I just made.
