### ISSUE TITLE
GSOC 2019: Make sure top 50 PyPI packages are supported

### ISSUE THREAD

**Issue by kayhayen** [Nuitka/Nuitka#229]
Nuitka works with most software. The aim of this project is to make sure it's true for the top 50 packages on PyPI, by compiling and using their example codes.

In a first stage, you would identify and report the issues to the bug tracker, in a second stage develop tools that help to narrow down issues, e.g. what extension module fails to load precisely, even with a segfault happening, and put them to use and try to fix a few of the simpler issues.

Setting up these as automated tests would be the ultimate goal, so we can follow these top 50 packages with Nuitka over time and make sure they continue to work.

In the past it has happened e.g. that Jinja2 was breaking for Python3.7, and it would be cool to discover this immediately.

Skills: Python programming, pip installation, Linux and/or Windows installs of Python, one is good, both would be great.

**Comment by aditya-hari** [comment]
Hey. 
 
This is something  that sounds really interesting to me and I'd love to be able to contribute to this. 
But I am completely new to Open source as a whole and have no idea how to even begin. I don't expect to be able to do something significant enough to qualify for GSoC or whatever but I'd love for this to be my first foray into open source and to gain experience.  
 
Since this and #230 both are labelled as easy in terms of difficulty, I think I should start here. 
 
But I don't know what "Linux and/or Windows installs of Python" means in terms of skills and I don't know how to begin.  
 
Could you please guide me to some resources or tell me how I should go about finding my bearings? I am competent with Python and consider myself to be a quick learner, I am sure I will be able to get up to speed soon.

**Comment by kayhayen** [comment]
Welcome @aditya-hari and I agree this is not yet detailed enough. Actually today I was going to flesh this further out with pointers.

As for the skill, more of an asset. We would prefer you did this on those platforms, doing it on macOS would e.g. be too difficult for us to help you with. We do not care if you use Windows or Linux, however in my experience the later works better for the debugging that will be needed, i.e. in case of a crash of standalone compiled software.

As for more pointers, they are coming later today, or so I hope.

**Comment by kayhayen** [comment]
So, first of all, we need to define what we mean by top 50 PyPI packages. For Python downloading the packages via `pip` is very widespread. So the first task would be to look at the top 100 and identify 50 packages that are even relevant to Nuitka. 

Of course `pip` itself, leading the list, we will skip that, nobody needs that compiled or uses it as a library in their software. But urllib3 is top 2, and very important piece of software that people rely on, so breaking it in Nuitka compilation would be bad.

What the student would be expected to do, is to go and read its documentation in search for a tutorial, small examples, that make it work. Distill a minimal test out of that and add it to the existing pool of tests in `tests/standalone` say as `tests/standalone/Urllib3Using.py` and get it to work in standalone mode, using the Nuitka argument `--standalone`.

Then, if possible and easy, the tests should be made to work. For `py.test` and `nose2` there is a good chance to get them working against a compiled package. For that you would be using the Nuitka argument `--package`, throw in magic environment variables if necessary, if the tests live below the package name space, say `urllib3.tests` and then run the tests. Looking at the test results, which hopefully pass and fail equally well (never assume a released software passes all the tests when not compiled in your environment or any), you then try to identify the issue, or report it as a Nuitka issue, or sometimes as an issue of the software we are testing.

When those work, we should try and turn this into a re-usable test as well, so we can apply them in an automated fashion.

Then on to next package on the list. The main benefit to the student will be to get to know the 50 most important software packages of Python on at least a cursory level. Something the mentors won't even do. And that will teach you a lot and the mentors too. And it will prevent people using Nuitka from encountering things that our testing will then find before Nuitka releases.

**Comment by kayhayen** [comment]
A good example of a test for a standalone usage is this one:

https://github.com/Nuitka/Nuitka/blob/cb0e0beb72041adeab1065306d5413a6bd868611/tests/standalone/PyQt5Using.py#L29

Here PyQt is used to create an application and signal a slot, which as a compiled function could be problematic. And in fact it was, until we reported to upstream with a potential patch to their source. The later would be fantastic if you manage, but not required.

**Comment by aditya-hari** [comment]
I hate to ask but I would really appreciate it a great deal if you could guide me through it. I am willing to learn and devote as much time as necessary.

**Comment by aditya-hari** [comment]
So I'm definitely showing my inexperience here, but how do I start? Apologize for the constant banal questions, just really want to help

**Comment by kayhayen** [comment]
You would start by making a minimal `urllib3` using program, compile it with nuitka, and run it standalone. You would then integrate it into the test suites mentioned above. Then, optionally try to package urllib3 as a compiled package, and run its tests against that. Then next package.

**Comment by kayhayen** [comment]
And obviously, `urllib3` documentation is most definitely going to contain a tutorial example, some prime use case, of what people usually use it. In that case, it probably is going to be downloading files via http and/or https protocols.

**Comment by PrajwalM2212** [comment]
@kayhayen I am interested in this project and the oppurtunity it gives to know top 50 packages.

**Comment by aditya-hari** [comment]
Alright, I'll get right to that

**Comment by sannanansari** [comment]
> And obviously, `urllib3` documentation is most definitely going to contain a tutorial example, some prime use case, of what people usually use it. In that case, it probably is going to be downloading files via http and/or https protocols.

Hi @kayhayen I am Mohammed Sanan currently pursing my third year in B.tech. I am interested in this project. I can learning more than 50 libraries from this gsoc project.
Documentation helps. But error are occuring 
![screenshot 69](https://user-images.githubusercontent.com/30230441/52296431-5b9e7f00-29a4-11e9-9df2-37598991cc63.png)
After all fixing this error is occuring.

**Comment by kayhayen** [comment]
@sannanansari make sure to use the right kind of MinGW64, the one linked. This error is typical of using MinGW. The user manual has links to what is working.

**Comment by sannanansari** [comment]
Ok. I will get right their.

**Comment by sannanansari** [comment]
> You would start by making a minimal `urllib3` using program, compile it with nuitka, and run it standalone. You would then integrate it into the test suites mentioned above. Then, optionally try to package urllib3 as a compiled package, and run its tests against that. Then next package.

@kayhayen I have gone through this step. Nuitka compiler is compiling urllib3 code and generating.exe file also but --standalone is give an warning and not generating .exe file.
![screenshot 72](https://user-images.githubusercontent.com/30230441/52357540-54d34300-2a5c-11e9-9710-313b18afe5fe.png)
Explain about this part? How can I fix this error?

**Comment by kamgha** [comment]
@sannanansari It means that `six.py` is using the __import__ statement in line 82: https://github.com/urllib3/urllib3/blob/master/src/urllib3/packages/six.py#L82 .  You'll have to find out what `name` is this case can be and pass it in via `--include-plugin-files` or `--include-plugin-directory` to your Nuitka compile statement.

**Comment by sannanansari** [comment]
Sorry for uploading incomplete but no output shown after that
![screenshot 75](https://user-images.githubusercontent.com/30230441/52417950-fe750b80-2b12-11e9-8c37-54be6c60d2d0.png)
As you mention about finding python module it is builtins module. But it is giving an error when I am including --include-plugin-files.
please ignore line from "trackback".

**Comment by kamgha** [comment]
@sannanansari I think this is drifting off-topic. I've just compiled the example script from https://urllib3.readthedocs.io/en/latest/ with `python -m nuitka --standalone test.py` and it compiles fine and generates the executable. The warning is just a warning, it may cause trouble during runtime. `builtins` is part of Python, I doubt that you'd need it here, and it is not a directory.

**Comment by kayhayen** [comment]
Just to give the necessary background @sannanansari beyond what @kamgha said.

The `six` module is a popular Python2/Python3 compatibility layer, that often is included in the package itself, therefore living in the urllib3 namespace here. It does abstract some of the moved imports of Python3, and uses `__import__` to execute its import. 

Nuitka has a hard time to see through tricks like this, which is why it gives a warning, as an indication to the user, that something might go astray here. But it definitely doesn't have to be the case.

Sometimes programs, libraries have folders that they scan and load on the fly, e.g. plugins. These are also done via `__import__` and in that case, Nuitka wants you to tell about such directories.

This is one of the usability quirks. I think Nuitka ought to be changed to not warn about "*.six" modules doing `__import__` as these are all going to be harmless if they are six code. Plugins can suppress warnings, and such a check could easily be added. However, this wouldn't be on your plate with this issue. 

You most often will see this warning and be able to ignore it. And where that is not the case, an `ImportError` will occur at runtime in standalone mode, and will be best explained by looking at this kind of warning.

I hope it clarifies things a bit. It is kind of expected that you won't know these yet. This idea will also expose you to this kind of usability issues of Nuitka naturally, but they are easy to learn.

**Comment by sannanansari** [comment]
Ok.
I want you to see this two things.
![screenshot 78](https://user-images.githubusercontent.com/30230441/52456818-b2f74780-2b7c-11e9-919c-25f3a4d6826f.png)
In first part `C:\Users\Ansari\Anaconda3\python -m nuitka  testing.py`. It is giving me a warning but an executable is created and it is running.
But on second part `>C:\Users\Ansari\Anaconda3\python -m nuitka --standalone testing.py`. It is giving warning but no executable is created.

Being new I am not able to get concept of plugin. But as you say plugin suppressed warning here main problem is that it is not creating executable. Warning is coming in first part also but executable is created. I'm not understanding that.

**Comment by kamgha** [comment]
@sannanansari Please give us the output of `dir /S` after you have run Nuitka with `--standalone`.

**Comment by sannanansari** [comment]
![screenshot 82](https://user-images.githubusercontent.com/30230441/52517619-b5809c80-2c63-11e9-9fb0-2685eb90ebbb.png)
This Screenshot is of `C:\Users\Ansari\Anaconda3\python -m nuitka testing.py` but after seeing into directory I have seen new folder. In first testing.build and executable is created but testing.dist in not.

![screenshot 81](https://user-images.githubusercontent.com/30230441/52517636-0beddb00-2c64-11e9-9191-c55e4c3f3e90.png)
`C:\Users\Ansari\Anaconda3\python -m nuitka --standalone testing.py` here testing.build and testing.dist is created not executable.

sorry for that I was only concentrating on executable file.

**Comment by sannanansari** [comment]
Why standalone is important? When I can directly use Nuikta. Which is providing executable.

**Comment by JorjMcKie** [comment]
@sannanansari  - the executable produced in non-standalone mode only works in presence of a (**fully!**) compatible Python installation.
A stanalone compile can be deployed to any compatible **operating system** - with or without a Python installation.

**Comment by JorjMcKie** [comment]
@sannanansari - when I say "a standalone can be deployed ...", then this means that the ``dist`` folder containing the executable is the deployable item: copy it to any compatible OS, and you will find the exe file in it usable.

Please also refer to the discussion around "One-File" distribution in this context (#230):
There is a request to transform the ``dist`` folder to a (big) exe-file that can be used directly to execute the original compiled script within it on the deployed-to system.
This request can be viewed as solved since a few days - for platforms Windows and Linux (thanks to @akshai9899), still missing Mac OSX for this.

**Comment by sannanansari** [comment]
I have not seen it sorry for that. It is working. So what should I do next?

**Comment by sannanansari** [comment]
I can email any mentor directly if you all don't mind.

**Comment by LilJohny** [comment]
@kayhayen Can I do this for GSOC?

**Comment by kayhayen** [comment]
@LilJohny @sannanansari sure please send in the small questionaire I put in the other GSoC questions thread.

**Comment by Pihu1998** [comment]
Hi @kayhayen I am Pranamika and I am interested in this project. But please can you explain me that what did you mean by identifying 50 packages that are even relevant to Nuitka.

**Comment by kayhayen** [comment]
@Pihu1998 There are download counters on PyPI, and sites which aggregate the information. I think I gave a link previously, but I don't find it right now. But a Google search is all that it takes.

**Comment by Pihu1998** [comment]
@kayhayen  Thank you for the clarification. I will surely search it out.

**Comment by Pihu1998** [comment]
@kayhayen I have gone through the above mentioned steps but received the following error:
![Screenshot (10)](https://user-images.githubusercontent.com/47104271/54365122-46e49380-4694-11e9-9e31-a96673cdac20.png)
I am not able to figure it out. I am new to Open Sourece, maybe I just have't been able to figure out how to use Nuitka. Please help.

**Comment by kayhayen** [comment]
@Pihu1998 need to install Nuitka first

**Comment by Pihu1998** [comment]
@kayhayen Nuitka is already installed.

**Comment by sannanansari** [comment]
@kayhayen I am trying to move forward and try to run more_itertools library from python. But it was giving me error `No module name more_itertools`. What should I do next? My aim is to install more_itertools in Nuitka to understand  it better.

**Comment by kayhayen** [comment]
@sannanansari Nuitka can *only* compile something that is already executable in your normal Python environment. Into that environment, you then apply Nuitka. So first of all, you would have to install what you want to compile, get it to run *uncompiled*, and only *then* you should compile it.

**Comment by sannanansari** [comment]
Can you can suggest what to do now or any bugs?

**Comment by kayhayen** [comment]
@sannanansari Look at the issues tagged GSoC or help_wanted and try to solve them.

**Comment by tab1tha** [comment]
@kayhayen  
Greetings My name is Tambe Tabitha Achere and I program in Python.I'm completely new to opensource and  I want to contribute to Nuitka in order to sharpen my python skills.
I already have a dual  boot of UBUNTU 16.04LTS and Windows 10( with Python 3 and pip installled already). I am really interested in this issue. Please is are there specific guidelines on how a proposal to Nuitka should look like?
Or any prerequisites before I can apply to GSOC under Nuitka?

**Comment by kayhayen** [comment]
Just the normal Google requirements and Guidelines apply, @tab1tha you just start and try to come with a framework of doing e.g. this issue, and detail that in your application.

**Comment by annubv** [comment]
Hello! I am Anubhav, a student of Software Engineering and I want to apply for GSOC 2019 under Nuitka. I went through the documentation and successfully compiled the hello world program.
I am familiar with open source, git, github and I primarily code in Python and have used some of the famous modules like PyQT5 (Check my repos for more).
What can I do to assure you that I can be helpful for this program?
Hope I'm not late!
![Screenshot (97)](https://user-images.githubusercontent.com/16976919/54625008-73355100-4a94-11e9-9b2f-65fb236cb955.png)

**Comment by kayhayen** [comment]
@annubv please check out the thread about other GSoC questions and find the information there.

**Comment by annubv** [comment]
Hey! I tried to compile the cryptography module code with Nuitka although, it was successful but it's taking way too long (more than 5 minutes for me) to do so. What is the reason behind this?
I successfully compiled the urllib3 code without any issues though.
Below is the source code of file t1.py
```
from cryptography.fernet import Fernet
key = Fernet.generate_key()
f = Fernet(key)
token = f.encrypt(b"A really secret message. Not for prying eyes.")
print(token)
print(f.decrypt(token))
```
The command :
```
python -m nuitka --standalone --mingw64 --follow-import-to=cryptography.fernet t1.py
```

**Comment by JorjMcKie** [comment]
Hi,
let me step in with an answer: 5 minutes is nothing!
But seriously:
On Windows, a DLL dependency analyzer (dependency walker) is automatically started, which detects all shared libraries required. This takes the most time ... at least for the first compiles. Analysis results are stored in a cache, which is consulted in subsequent compiles. As this cache enriches, compiles become shorter, because only DLLs yet unknown to the cache need be searched for.
Currently, there is a much faster package available as an "experimental" feature (meanwhile it no longer is truly experimental).
Add ``--experimental=use_pefile`` to your command line, to see the difference.

**Comment by tab1tha** [comment]
the issue description says the first task would be to look at the top 100 and identify 50 packages that are even relevant to Nuitka.Is there any criteria to check?

**Comment by kayhayen** [comment]
This may come as a shock. But the top 50 packages are best identified by looking at the top 100 list that I linked and using the first 50. :-)

**Comment by Pihu1998** [comment]
Hi @kayhayen 
I was running the pytest for the package Six. But I am not able to understand how to use the argument **--package**
> For that you would be using the Nuitka argument --package, throw in magic environment variables if necessary, if the tests live below the package name space, say urllib3.tests and then run the tests

And I didn't understand the above part. Could you please explain or provide some pointers if possible?

**Comment by tommyli3318** [comment]
> @kayhayen Nuitka is already installed from the link provided in the documentation.

If you want to use Nuitka from cmd, you need to install it in command line with pip: "pip3 install nuitka" for python3

**Comment by Pihu1998** [comment]
@tommyli3318 Thankyou so much for the response :-). I somehow figured out the problem and fixed it.
But now the problem is that I was trying to run the py.test for the package Six. But I am not able to figure out how to use the argument --package. 
> For that you would be using the Nuitka argument --package, throw in magic environment variables if necessary, if the tests live below the package name space, say urllib3.tests and then run the tests

And didn't understand the above part.

**Comment by kayhayen** [comment]
Ok, this is actually important @Pihu1998 look here:

https://github.com/Nuitka/Nuitka/blob/69183f6567befd62bc1d768dd070fb99475b8cb4/tests/test-runners/run_all.py#L120

This is the test runner that checks that py.test is usable. And the example software, uses `package` as a name for the package, and then the runner sets `NUITKA_PACKAGE_package` to indicate to the compiled package that its `__path__` should also contain that directory.

**Comment by kayhayen** [comment]
This is the magic I was talking about. That way uncompiled tests can be run inside a package name space, if they so require (they may not!), and still import the compiled package and use it.

**Comment by Pihu1998** [comment]
@kayhayen Thankyou for the elaboration :-)

**Comment by kayhayen** [comment]
I am setting up a machine once provided with it from @deajan company, and it will run it on a regular basis.
