### ISSUE TITLE
22 Detected viruses in simple soft

### ISSUE THREAD

**Issue by samsunysoft** [Nuitka/Nuitka#2290]
https://www.virustotal.com/gui/file/4b171b2ec8bc03a7e6765ccb95d75384856b119385dddac5ff89e8f8643061bd

python 3.11
code:
![image](https://github.com/Nuitka/Nuitka/assets/135343382/7e73589a-6c2b-4f07-8bfd-514e06b3063a)

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
