### ISSUE TITLE
ModuleNotFoundError: No module named 'nuitka.containers.oset'

### ISSUE THREAD

**Issue by EvgeniyaBelovodchenko** [Nuitka/Nuitka#2296]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

1.6.4
Commercial: None
Python: 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: ~\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe (cl 14.2).

* How did you install Nuitka and Python

I installed nuitka using pip within the environment

* The specific PyPI names and versions

altgraph==0.17.3
bottle==0.12.25
bottle-websocket==0.2.9
cffi==1.15.1
cx-Logging==3.1.0
deprecation==2.1.0
Eel==0.16.0
future==0.18.3
gevent==22.10.2
gevent-websocket==0.10.1
greenlet==2.0.2
lief==0.13.2
Nuitka==1.6.4
numpy==1.24.3
ordered-set==4.1.0
packaging==23.1
pandas==2.0.2
pefile==2023.2.7
psutil==5.9.3
pycparser==2.21
pygost @ file:///./extensions/pygost.tar
pyinstaller==5.12.0
pyinstaller-hooks-contrib==2023.3
pyparsing==3.1.0
PyQt5==5.15.9
PyQt5-Qt5==5.15.2
PyQt5-sip==12.12.1
python-dateutil==2.8.2
pytz==2023.3
pywin32-ctypes==0.2.1
six==1.16.0
tzdata==2023.3
whichcraft==0.6.1
zope.event==4.6
zope.interface==6.0
zstandard==0.21.0

* Also supply a Short, Self Contained, Correct, Example
Using documentaion about [hinted_compilation](https://github.com/Nuitka/NUITKA-Utilities/tree/master/hinted-compilation)
command: python nuitka-hints.py yourscript.py

In result, ModuleNotFoundError for:
from nuitka.containers.oset import OrderedSet
from nuitka.containers.odict import OrderedDict
And ImportError: cannot import name 'lateActivatePlugin' from 'nuitka.plugins.Plugins' for:
from nuitka.plugins.Plugins import lateActivatePlugin

**Comment by kayhayen** [comment]
The script you are using is not supported anymore. Use plain Nuitka, which has become pretty good itself at avoid bloat.
