### ISSUE TITLE
Is it possible to at least do not re-generate C source for unmodified modules?

### ISSUE THREAD

**Issue by TsXor** [Nuitka/Nuitka#2297]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version

  ```
  1.7rc5
  Commercial: None
  Python: 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
  Flavor: CPython Official
  Executable: D:\Python39\python.exe
  OS: Windows
  Arch: x86_64
  WindowsRelease: 10
  Version C compiler: D:\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\cl.exe (cl 14.3).
  ```

* How did you install Nuitka and Python

  install develop package into global python environment

* The specific PyPI names and versions

  ```
  Nuitka @ file:///E:/Users/23Xor/Downloads/Nuitka-develop.zip#sha256=b4e22737371eefd3d93338852e235502904d8fc9dd3992537b4e
  ```

* Many times when you get an error from Nuitka, your setup may be special

  No error.

* Also supply a Short, Self Contained, Correct, Example

  Every compilation is an example.

* Provide in your issue the Nuitka options used

  ```
  --standalone
  ```

Nuitka is now re-generating C source for module that is not modified since last build. Is it possible to add a check?

**Comment by kayhayen** [comment]
I am eargerly waiting for the help needed to implement the caching. At this time, I did not manage to implement the necessary persistence feature required.
