### ISSUE TITLE
Issue: ModuleNotFoundError: No module named 'pandas._config.localization' with Nuitka compilation

### ISSUE THREAD

**Issue by ellouzatim** [Nuitka/Nuitka#2302]
### Issue: ModuleNotFoundError: No module named 'pandas._config.localization' with Nuitka compilation

I am facing an issue while compiling my Python script using Nuitka. After successful compilation using the command `python3.11 -m nuitka --follow-imports --standalone main.py`, I encounter a `ModuleNotFoundError: No module named 'pandas._config.localization'` error when trying to execute the compiled program. I expected the compiled program to execute successfully without any import errors. It seems that I am facing the same problem on Windows, and I haven't tested it on Ubuntu yet.

#### Environment
- Python version: 3.11.3 (main, Apr 7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)]
- Nuitka version: 1.6.5
- Operating System: Darwin
- Compiler: Clang

#### Installed Packages
`python3.11 -m pip freeze`
```plaintext
altgraph==0.17.3
attrs==23.1.0
contourpy==1.0.7
altgraph==0.17.3
attrs==23.1.0
contourpy==1.0.7
cx-Freeze==6.15.2
cycler==0.11.0
docx==0.2.4
et-xmlfile==1.1.0
feret==1.3.1
fonttools==4.39.4
imageio==2.31.0
jsonschema==4.17.3
kiwisolver==1.4.4
lazy_loader==0.2
lxml==4.9.2
macholib==1.16.2
matplotlib==3.7.1
networkx==3.1
Nuitka==1.6.5
numpy==1.24.3
opencv-python==4.7.0.72
openpyxl==3.1.2
ordered-set==4.1.0
packaging==23.1
pandas==2.0.2
pdf2image==1.16.3
Pillow==9.5.0
pyinstaller==5.11.0
pyinstaller-hooks-contrib==2023.3
pyparsing==3.0.9
pyproject-toml==0.0.10
pyrsistent==0.19.3
python-dateutil==2.8.2
python-docx==0.8.11
pytz==2023.3
PyWavelets==1.4.1
reportlab==4.0.4
scikit-image==0.21.0
scipy==1.10.1
six==1.16.0
sv-ttk==2.4.5
tifffile==2023.4.12
toml==0.10.2
tzdata==2023.3
zstandard==0.21.0
```

**Comment by kayhayen** [comment]
This is lacking a reproducer script. You clearly didn't really the issue template.
