### ISSUE TITLE
ELF load command alignment not page-aligned

### ISSUE THREAD

**Issue by yang7776** [Nuitka/Nuitka#2303]
centos:7 arm
python3.8.12

run cmd:
`python3 -m nuitka --lto=yes --follow-imports --output-filename=server --onefile server.py`

After the compilation of nuitka is completed, an error is reported during execution：
`error while loading shared libraries: libpython3.8.so.1.0: ELF load command alignment not page-aligned`

I think there is this in the main.dist directory:

```
[root@2810c1e55398 server]# ls main.dist/ | grep libpython3.8.so.1.0
libpython3.8.so.1.0
```

But when I remove the parameter 'onefile', the program will run normally。

Please help me with what I should do, thank you～

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
