### ISSUE TITLE
Program exit without opening when using PySide6

### ISSUE THREAD

**Issue by abcdesteve** [Nuitka/Nuitka#2307]
# versions
```
python 3.10 miniconda
Nuitka                     1.6.6
PySide6                    6.4.3
```
# behavior
At first I found that nuitka won't work when using Slot in PySide6 below 6.5.0
But the lib that I depend on require pyside6<6.5.0
After removing @Slot from my code,no error was raised by nuitka
However, when I try to run the program, I can only see a task was launched in the taskmanager but no pyside window was show,and it will exit in a few secends.
All the icons I use was using the format given in your help page `os.path.join(os.path.dirname(__file__),'icons','logo.svg')`

Work neither in onefile mode or using the whole dir

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
