### ISSUE TITLE
ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db

### ISSUE THREAD

**Issue by xuehaiming** [Nuitka/Nuitka#2310]
My Nutika version 1.6.6
More details shows below:
Commercial: None
Python: 3.10.11 (main, Apr 20 2023, 19:02:41) [GCC 11.2.0]
Flavor: Anaconda Python
Executable: /home/summit/anaconda3/envs/vicenv/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 20.04.6
Version C compiler: /usr/lib/ccache/gcc (gcc).

I am using GDAL  in my Project, I use Nuitka to package using standalone mode, 
`python -m nuitka --standalone --show-progress --show-memory --follow-imports --output-dir=out_gdal --remove-output --main=pack.py`
when I  execute the binary with command "./pack.bin" , errors occurs

> ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db
> ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db

The GDAL  Version is 3.4.1, and I am install it with conda install gdal=3.4.1

Now I find why this happened，because the package folder does not contains share/proj directory witch is show in the conda virtual 
 vicenv folder, and the bash commad has no PROJ_LIB var set, when I copy the proj folder to the dist folder, and use the command below before I execute the project binary witch built by Nuika, It is OK,
`export PROJ_LIB=/home/summit/Poly_PY/out_gdal/pack.dist/proj`

When I am using Pyinstaller to build my project, the dist folder contains share/proj already, and I am not need to set the PROJ_LIB eviroment, but it runs ok, So, Can I package programs with share folder witch is in anaconda env using Nuitka and  include set enviroment (export PROJ_LIB=...) in the packing results?

**Comment by kayhayen** [comment]
Without a reproducer, there is nothing to do here.

As for the data files, these are easy to add.

If you are available to do a PR, this can be fixed by adding to the yaml configuration, described here: [https://nuitka.net/doc/nuitka-package-config.html](https://nuitka.net/doc/nuitka-package-config.html)

And here is more of a walk through style post: [https://nuitka.net/posts/nuitka-package-config-kickoff.html](https://nuitka.net/posts/nuitka-package-config-kickoff.html)

Here are a example PRs for other packages:

[#2030](https://github.com/Nuitka/Nuitka/pull/2030) 
[#1993](https://github.com/Nuitka/Nuitka/pull/1993)

**Comment by xuehaiming** [comment]
> Without a reproducer, there is nothing to do here.
> 
> As for the data files, these are easy to add.
> 
> If you are available to do a PR, this can be fixed by adding to the yaml configuration, described here: https://nuitka.net/doc/nuitka-package-config.html
> 
> And here is more of a walk through style post: https://nuitka.net/posts/nuitka-package-config-kickoff.html
> 
> Here are a example PRs for other packages:
> 
> [#2030](https://github.com/Nuitka/Nuitka/pull/2030) [#1993](https://github.com/Nuitka/Nuitka/pull/1993)

This is my code used for package testing, and the nuitka cmd is 

> python -m nuitka --standalone --show-progress --show-memory --follow-imports --output-dir=out_gdal --remove-output --main=pack.py


```
from osgeo import gdal
from osgeo import ogr, osr
import os
import uuid
import shutil
import tempfile

class GDALInverseDistanceWeighting:
    def __init__(self, xyzs, extent, resolution, nodata=None, epsg=4490):
        self.extent = extent
        self.xyzs = xyzs
        self.resolution = resolution
        self.nodata = nodata
        self.srs = "EPSG:%d"%(epsg)
        self.epsg = epsg


    def execute(self, n_points=12, search_dis=0.0, min_ptnums=0, power=2):
        try:
            tmp_dir = os.path.join(tempfile.gettempdir(), "geodata_%s"%(uuid.uuid4().hex[:10]))
            if not os.path.exists(tmp_dir):
                os.makedirs(tmp_dir)
            lyr_name = "point_layer"
            mem_drv = ogr.GetDriverByName('ESRI Shapefile')
            mem_ds = mem_drv.CreateDataSource(tmp_dir)
            if mem_ds.GetLayerByName(lyr_name)!=None:
                mem_ds.DeleteLayer(lyr_name)
            mem_srs = osr.SpatialReference()
            mem_srs.ImportFromEPSG(self.epsg)
            mem_layer = mem_ds.CreateLayer(lyr_name, srs=mem_srs, geom_type=ogr.wkbPoint)

            field_def = ogr.FieldDefn('z', ogr.OFTReal)
            mem_layer.CreateField(field_def)

            for point in self.xyzs:
                feature = ogr.Feature(mem_layer.GetLayerDefn())
                point_geom = ogr.Geometry(ogr.wkbPoint)
                point_geom.AddPoint(point[0], point[1])
                feature.SetGeometry(point_geom)
                feature.SetField('z', point[2])
                if point[2] is None:
                    continue
                mem_layer.CreateFeature(feature)
                # feature = None
            mem_layer.SyncToDisk()

            x_min, y_min, x_max, y_max = self.extent

            xsize = int(round((x_max - x_min) / self.resolution))
            ysize = int(round((y_max - y_min) / self.resolution))

            # 更新x_max,y_max为resolution整数倍
            x_max = x_min + self.resolution * xsize
            y_max = y_min + self.resolution * ysize
            
            # 定义输出栅格数据的参数
            out_file = os.path.join(tmp_dir, "interp.tif")

            # 定义反距离权重插值的参数
            if search_dis==0:
                search_dis = 3
            algorithm = 'invdist:power={0}:radius={1}:max_points={2}:min_points={3}:nodata=0:max_points_per_quadrant={4}'.format(power, search_dis, n_points, min_ptnums, n_points)
            # algorithm = 'invdist:power={0}:radius={1}:max_points={2}:min_points={3}:max_points_per_quadrant={4}'.format(power, search_dis, n_points, min_ptnums,n_points)
            # algorithm = 'invdist:power=2.0:radius1=0:radius2=0:angle=0.0:max_points=12:min_points=3:nodata=0'
            # 执行反距离权重插值
            input_ds = os.path.join(tmp_dir, "%s.shp"%(lyr_name))
            gdal.Grid(out_file, input_ds, zfield="z", algorithm=algorithm, outputSRS=self.srs,
                    outputBounds=[x_min, y_max, x_max, y_min], width=xsize, height=ysize)
            # 读取栅格数据
            dataset = gdal.Open(out_file)
            band = dataset.GetRasterBand(1)
            # 读取的得到的数据顺序为从左上到右下(↘)
            data = band.ReadAsArray()
            # 移除临时文件
            mem_ds = None
            shutil.rmtree(tmp_dir)
            # mem_ds.DeleteLayer(lyr_name)
            # os.remove(out_file)
            # os.removedirs(tmp_dir)
            return data
        except Exception as e:
            raise e

extent = [100.0, 30, 120, 40]
xyzs = [[110,32,5],[111,32,6],[115,32,15],[118,32,0],
        [110,33,5],[111,34,26],[115,34,0],[118,34,20],
        [110,35,15],[111,35,6],[115,35,15],[117,35,0],
        [110,38,35],[111,38,16],[115,38,15],[117,38,30]
        ]
idst = GDALInverseDistanceWeighting(xyzs, extent, 0.5)
data = idst.execute()
print(data[1].tolist())

```

**Comment by kayhayen** [comment]
Amazing grace, gdal works in no form from PyPI, neither on Windows nor Linux, on Windows Anaconda your version or latest version, with 3.11 or 3.10 all don't work. What a nightmare, downloading Anaconda for Linux now, which I haven't used in a while I guess.

**Comment by kayhayen** [comment]
The example provided now compiles flawlessly on factory. It revealed a bug that is maybe unrelated, but yet important. I didn't see the proj message. I believe it might be missing data files. If you make a new report with more concrete example, I can probably fix that as well.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.7.3 that I just made.
