### ISSUE TITLE
Segmentation Fault with jsonschema@4.18.0

### ISSUE THREAD

**Issue by almightychang** [Nuitka/Nuitka#2314]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

```bash
1.7.1
Commercial: 2.2.0
Python: 3.10.7 (main, May 29 2023, 13:51:48) [GCC 12.2.0]
Flavor: Debian Python
Executable: /home/almightychang/Workspace/issue_nuitka/.venv/bin/python3
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.10
Version C compiler: /usr/bin/gcc (gcc).
```

* How did you install Nuitka and Python

Use python3 venv module to create virtual environment.
Then, installed nuitka 1.7.1 with pip.

* The specific PyPI names and versions

```bash
attrs==23.1.0
jsonschema==4.18.0
jsonschema-specifications==2023.6.1
Nuitka @ git+https://github.com/Nuitka/Nuitka-commercial.git/@67181e37dde098f2e3be32bf6c356e4bacaad419
ordered-set==4.1.0
referencing==0.29.1
rpds-py==0.8.8
zstandard==0.21.0
```

* Many times when you get an error from Nuitka, your setup may be special
* Also supply a Short, Self Contained, Correct, Example

Simple example codes with jsonschema@4.18.0 reproduces the error.

```python
from jsonschema import ValidationError, validate

if __name__ == '__main__':
    schema = {
        "type": "object",
        "properties": {
            "price": {
                "type": "number"
            },
            "name": {
                "type": "string"
            },
        },
    }

    validate(instance={"name": "Eggs", "price": 34.99}, schema=schema)
    try:
        validate(
            instance={
                "name": "Eggs",
                "price": "Invalid"
            },
            schema=schema,
        )
    except ValidationError as e:
        print(e.message)
        print(e.absolute_path)
        print(e.absolute_schema_path)
```

* Provide in your issue the Nuitka options used

```bash
python3 -m nuitka example.py --show-modules --standalone --output-dir=build
```

* Result
Segmentation fault happens when running the output binary. I think there is some compatibility issues around rust bindings in jsonschema's dependencies.

```bash
$ ./build/example.dist/example.bin 
[1]    3079998 segmentation fault (core dumped)  ./build/example.dist/example.bin
```

**Comment by kayhayen** [comment]
I managed to reproduce this. I did not before I took your exact requirements, so this is probably something about new (?) versions too.

**Comment by kayhayen** [comment]
So, this is a bug of the files implementation of Nuitka, it does a `OS_LISTDIR` but ignores the error there. When I add that, it gives me this:

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/hayen/repos/Py2C/Mini.dist/jsonschema_specifications/schemas
```

I do not recall seeing this package before, they probably factored out the data files, and this is now the first time, this implementation of modern API of Nuitka is hit with a missing data file. Not as a critique, but jsonschema people are very much always on the forefront of using newer APIs. I will add your code to Nuitka-Watch as well once I fixed this.

With `--include-package-data=jsonschema_specifications` it will not crash. I will be make a hotfix release with the actual fix of the underlying issue, and Yaml configuration that just does what's needed shortly.

**Comment by kayhayen** [comment]
I have published it on staging branch, but current factory (and by proxy staging) may be regressive at this point, so I cannot recommend it for your deployment.

**Comment by kayhayen** [comment]
Part of the 1.7.2 release.
