### ISSUE TITLE
Compiling C generated files from Nuitka into WASM

### ISSUE THREAD

**Issue by guibvieira** [Nuitka/Nuitka#2321]
I raised an initial stackoverflow in: https://stackoverflow.com/questions/76655779/compiling-nuitka-c-generated-code-into-wasm
in case anyone wants to consult the issue in more detail. 

* Nuitka version, full Python version, flavor, OS, etc. : *

 system: Apple M1 Pro 2021
OS: macOS 13.1 

```
1.7.1
Commercial: None
Python: 3.10.0 (default, Aug 10 2022, 10:39:02) [Clang 13.0.0 (clang-1300.0.27.3)]
Flavor: pyenv
Executable: /Users/***/dev/wasm-test/nuitka-exp/venv/bin/python
OS: Darwin
Arch: arm64
Version C compiler: /usr/bin/gcc (gcc).
```

* How did you install Nuitka and Python

 I installed nuitka via pip in a virtualenv

* The specific PyPI names and versions

Package     Version
----------- -------
Nuitka      1.7.1
ordered-set 4.1.0
pip         23.1.2
setuptools  67.8.0
wheel       0.40.0
zstandard   0.21.0

* Many times when you get an error from Nuitka, your setup may be special

 * Provide in your issue the Nuitka options used

`python -m nuitka --standalone --output-dir=output HelloWorld.py`

* Also supply a Short, Self Contained, Correct, Example

I started with a small Hello World file: 

```
def talk(message):
    return "Talk " + message


def main():
    print(talk("Hello World"))


if __name__ == "__main__":
    main()
```

I wanted to try compiling python to C and from C to WASM. 

To do this, I ran

`python -m nuitka --standalone --output-dir=output HelloWorld.py`

which produces two folder in output, HelloWorld.build and HelloWorld.dist. 
No issues with the binary, but then when I try to use EMCC to compile the c files into wasm files. I'm getting several errors: 

- 'nuitka/prelude.h' file not found
```
module.__main__.c:19:10: fatal error: 'nuitka/prelude.h' file not found
   19 | #include "nuitka/prelude.h"
emcc: error: '/Users/gui/dev/wasm-test/emscripten/emsdk/upstream/bin/clang -target wasm32-unknown-emscripten -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -DEMSCRIPTEN -Werror=implicit-function-declaration --sysroot=/Users/gui/dev/wasm-test/emscripten/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat module.__main__.c -c -o /var/folders/vd/s7y9nsh17j58nlkxbx68vhmw0000gn/T/emscripten_temp_e9g16g7c/module.__main___0.o' failed (returned 1)
```

then after showing it where nuitka can find that file, i.e. : `venv/lib/python3.10/site-packages/nuitka/build/include` within my virtualenv, I am faced with subsequent errors: 

```
In file included from module.__main__.c:19:
/Users/gui/dev/wasm-test/nuitka-exp/venv/lib/python3.10/site-packages/nuitka/build/include/nuitka/prelude.h:34:10: fatal error: 'patchlevel.h' file not found
   34 | #include "patchlevel.h"
      |          ^~~~~~~~~~~~~~
1 error generated.
emcc: error: '/Users/gui/dev/wasm-test/emscripten/emsdk/upstream/bin/clang -target wasm32-unknown-emscripten -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -DEMSCRIPTEN -Werror=implicit-function-declaration --sysroot=/Users/gui/dev/wasm-test/emscripten/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -I/Users/gui/dev/wasm-test/nuitka-exp/venv/lib/python3.10/site-packages/nuitka/build/include module.__main__.c -c -o /var/folders/vd/s7y9nsh17j58nlkxbx68vhmw0000gn/T/emscripten_temp_bn_sl3md/module.__main___0.o' failed (returned 1)
```

Again, had to show the emcc where it could find the patchlevel.h file within nuitka package using `-I` option on emcc. 
`emcc ..... -I/Users/gui/.pyenv/versions/3.10.0/include/python3.10`

Then after showing him where to find my patchlevel.h which was contained within my python installation from pyenv (v3.10.0) I finally got the final error:

```
In file included from module.__main__.c:19:
In file included from /Users/gui/dev/wasm-test/nuitka-exp/venv/lib/python3.10/site-packages/nuitka/build/include/nuitka/prelude.h:58:
In file included from /Users/gui/.pyenv/versions/3.10.0/include/python3.10/Python.h:63:
/Users/gui/.pyenv/versions/3.10.0/include/python3.10/pyport.h:746:2: error: "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
  746 | #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
      |  ^
1 error generated.
```

This last error  suggests that there is a mismatch between the expected and actual size of the long data type on your platform. This can happen if there is a discrepancy between the architecture of your system and the architecture that Python or its libraries were compiled for. For example, if you are using a 64-bit version of Python on a 32-bit system, or vice versa.
I checked that :
- Machine architecture is 64bit by doing `uname -m`
- Python 3.10.0 for 64-bit machines
- `emcc -v`:
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.42 (6ede0b8fc1c979bb206148804bfb48b472ccc3da)
clang version 17.0.0 (https://github.com/llvm/llvm-project f3b64887de61020c09404bfee97b2fadd30df10a)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/gui/dev/wasm-test/emscripten/emsdk/upstream/bin
```

I have tried to produce a simple hello world in c, and compiling that with emcc and there was no issues but when attempting to compile any of the c files found within the HelloWorld.build folder I get the errors I described. I know I am getting an error when using emcc, however I think this due to the way that Nuitka compiles its files and was wondering if I could any help in understanding why it seems so difficult to compile the C files produces by Nuitka. Is it possible that there is an issue with the way Nuitka generated the C code? 

I am new to C, so any help here would be appreciated. 

Thanks in advance and happy to provide any additional information.

**Comment by kayhayen** [comment]
The Nuitka generated code should only be compiled with Scons. It will not work otherwise, and I do at this time have no interest, to make the C folder buildable manually, not even with gcc.

Try again by using `emcc` as `CC`environment variable. And then you probably get to add support for that compiler to our Scons config, I think `isGccName` will need modification, and maybe Scons too.

> I am new to C, so any help here would be appreciated.

I am not deep into wasm, but did you compile Python with wasm as well? Nuitka will not work without libpython ultimately. I thnk you dreamed up an idea here and may not know what you are doing.

**Comment by guibvieira** [comment]
Thank you for your quick reply @kayhayen ! I am indeed not experienced in what I am doing, but I have been tasked with exploring the possibility of compiling Nuitka generated C code into WASM using emcc. I am attempting to do this with a very simple example to see if it is possible. If it doesn’t work, that’s fine, but I would like to see this experiment through to the end.

My plan was to use wasm-ld from LLVM to link the WASM files for both libpython (using the pre-built version from Pyodide) and my Nuitka generated code. This should produce a combined WASM file that includes both my code and the Python runtime.

I have attempted to change the CC environment variable in the SCons configuration to use emcc as the C compiler, and I have also modified the isGccName function to recognize emcc as a valid GCC name. 

```
def isGccName(cc_name):
    return (
        "gcc" in cc_name
        or "g++" in cc_name
        or "gnu-cc" in cc_name
        or "gnu-gcc" in cc_name
        or 'emcc' in cc_name
    )
```
However, I am now getting fatal errors during the Nuitka compilation due to not finding stdio.h. It’s likely that the SCons build script is not correctly passing the include paths to the C compiler now that I’ve made these modifications.

If you could provide any further help on how to modify the SCons configuration to correctly use emcc as the C compiler, I would be very grateful. I understand that this may not be in Nuitka’s or your interest, so I thank you for your time.

**Comment by kayhayen** [comment]
Closing for lack of feedback.
