### ISSUE TITLE
Nuitka's DllFilesPlugin cannot get system libraries outside python's «site-packages» 

### ISSUE THREAD

**Issue by belonesox** [Nuitka/Nuitka#2328]
Nuitka's DllFilesPlugin cannot get system libraries outside python's «site-packages».
Let's consider sample demo with «Shapely» and «geos».

[nuitka-shapely-geos-system-libs.zip](https://github.com/Nuitka/Nuitka/files/12027733/nuitka-shapely-geos-system-libs.zip)

* `00-setup-demo.sh` — setup pipenv with standard Shapely, what bring own `*geos.so*` in `Shapely.libs`
* `01-standard-build-ok.sh`   — Nuitka builds OK
* `02-install-systel-geos.sh` — Installing system GEOS libraries (shell file for RPM/Fedora/Centos, for Ubuntu/Debian please install same packages with apt-get)
* `03-reinstall-shapely-based-on-system-libs.sh` — Reinstalling «Shapely with Geos» on same version that used system geos libs.
* `04-shapely-based-on-system-works-ok.sh`  — all works OK, `shapely.geos._lgeos._name` get `libgeos_c.so.1` that usually shoud be found on system `/usr/lib64`
* `05-nuitka-build-failed.sh` — failed with 

```
Traceback (most recent call last):
  File "/proj/bugs/nuitkas/nuitka-shapely-geos-system-libs/.venv/lib64/python3.10/site-packages/nuitka/plugins/Plugins.py", line 81, in withPluginP
roblemReporting
    yield
  File "/proj/bugs/nuitkas/nuitka-shapely-geos-system-libs/.venv/lib64/python3.10/site-packages/nuitka/plugins/Plugins.py", line 641, in considerEx
traDlls
    for entry_point in _iterateExtraBinaries(
  File "/proj/bugs/nuitkas/nuitka-shapely-geos-system-libs/.venv/lib64/python3.10/site-packages/nuitka/plugins/Plugins.py", line 631, in _iterateEx
traBinaries
    for v in _iterateExtraBinaries(plugin, val):
  File "/proj/bugs/nuitkas/nuitka-shapely-geos-system-libs/.venv/lib64/python3.10/site-packages/nuitka/plugins/Plugins.py", line 630, in _iterateEx
traBinaries
    for val in value:
  File "/proj/bugs/nuitkas/nuitka-shapely-geos-system-libs/.venv/lib64/python3.10/site-packages/nuitka/plugins/standard/DllFilesPlugin.py", line 15
0, in _handleDllConfigByCodeResult
    yield self.makeDllEntryPoint(
  File "/proj/bugs/nuitkas/nuitka-shapely-geos-system-libs/.venv/lib64/python3.10/site-packages/nuitka/plugins/PluginBase.py", line 566, in makeDll
EntryPoint
    return makeDllEntryPoint(
  File "/proj/bugs/nuitkas/nuitka-shapely-geos-system-libs/.venv/lib64/python3.10/site-packages/nuitka/freezer/IncludedEntryPoints.py", line 121, i
n makeDllEntryPoint
    return _makeDllOrExeEntryPoint(
  File "/proj/bugs/nuitkas/nuitka-shapely-geos-system-libs/.venv/lib64/python3.10/site-packages/nuitka/freezer/IncludedEntryPoints.py", line 88, in
 _makeDllOrExeEntryPoint
    assert isRelativePath(dest_path), dest_path
AssertionError: ../../../../libgeos_c.so.1
FATAL: dll-files: Plugin issue while working on 'module 'shapely.geos''. Please report the bug with the above traceback included.
```

Possible non-hacking workaround, like put symlinks to `/usr/lib64` inside 'site-packages', and somehow redefine package heuristics like that … 

```yaml
- module-name: 'shapely.geos'
  dlls:
    # PyPI has it contained, but not for Windows.
    - by_code:
        setup_code: 'import shapely.geos'
        filename_code: '" /proj/bugs/nuitkas/nuitka-shapely-geos-system-libs/.venv/lib64/python3.10/site-packages/system-libs-64/" + shapely.geos._lgeos._name'
      when: 'not is_conda_package("shapely") and not win32 and version("shapely") < (2,0)'
    # Anaconda or Win32 are forced to specific path.
```
… not working because of https://github.com/Nuitka/Nuitka/issues/2325 

IMHO, if Nuitka get pure filename (without path) for a so/dll lib from config

```python
        setup_codes = dll_config.get("setup_code")
        filename_code = dll_config.get("filename_code")

        filename = self.queryRuntimeInformationMultiple(
            "%s_%s" % (full_name.asString().replace(".", "_"), count),
            setup_codes=setup_codes,
            values=(("filename", filename_code),),
        ).filename
```
it should find corresponding system lib in PATH/LD_LIBRARY_PATH.

**Comment by kayhayen** [comment]
This is intended for packages, which had an attribute with the filename, that is hard to replicate otherwise. 

The guessing of `dest_path` will not work for your case, so you need to provide it. I will enhance the code to detect that the relative path approach is failing.

This bit of the code is causing your trouble:

```
        if dest_path is None:
            module_filename = self.locateModule(full_name)

            if os.path.isdir(module_filename):
                dest_path = full_name.asPath()
            else:
                dest_path = os.path.join(full_name.asPath(), "..")

            dest_path = os.path.join(
                dest_path,
                os.path.relpath(filename, os.path.dirname(module_filename)),
            )
        else:
            dest_path = os.path.join(
                dest_path,
                os.path.basename(filename),
            )
```

Of course packages frequently provide absolute paths, so being absolute is not the issue and it's not about being outside of site-package, but being outside of the package directory. So far only the delvewheel plugin is encountering that as its default packaging place, but everything else so far is sane.

I could attempt and assume the package directory for dest_path, if it points outside of the dist folder otherwise. Sometimes it is one level of for things in subpackage, but it feels wrong to be guessing there.

Locating DLLs is a hard problem. Using system DLLs is not a good default, when there is `os.add_dll_directory` and what not. Also one reason, why this option does not exist.

That said, what's wrong with this

```
  dlls:
    # PyPI has it contained, but not for Windows.
    - by_code:
        setup_code: 'import shapely.geos'
        filename_code: 'shapely.geos._lgeos._name'
      when: 'not is_conda_package("shapely") and not win32 and version("shapely") < (2,0)'
    # Anaconda or Win32 are forced to specific path.
    - by_code:
        setup_code: 'import shapely.geos'
        filename_code: 'shapely.geos._lgeos._name'
      dest_path: 'shapely'
      when: 'version("shapely") < (2,0) and (is_conda_package("shapely") or win32 and version("shapely") < (1,8,1))'
```

Is that `shapely.geos._lgeos._name` becomes system DLL in your case?

**Comment by kayhayen** [comment]
I just noticed, the "PyPI" branch does not provide dest_path, whereas the Anaconda branch does. and I am noticing, for that latest, it should use delvewheel on Windows at least. System library on non-Windows seems not covered at all then.

**Comment by belonesox** [comment]
> Locating DLLs is a hard problem. Using system DLLs is not a good default, when there is `os.add_dll_directory` and what not. Also one reason, why this option does not exist.
> Is that `shapely.geos._lgeos._name` becomes system DLL in your case?

Yes, from one point,   if `filename_code` returned just filename, will be good to use same heuristics, as most python code does («works like pure python code») that is to use something like universal and crossplatform as `ctypes.util.find_library`  (like most python libraries use for finding system libraries).

But it is not good for reproduceability of build and tracking library dependecies («what is source for some DLL in nuitka build?»).

For example, inside `shapely.geos` it used `ctypes.util.find_library` to load 'geos_c' and found first available
(in my case libgeos_c.so.1 from geos311-3.11.0-1.f36.x86_64
```
172881 newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=187807, ...}, AT_EMPTY_PATH) = 0
172881 openat(AT_FDCWD, "/usr/geos311/lib64/libgeos_c.so.1", O_RDONLY|O_CLOEXEC) = 3
```

after removing geos311 it found the lib in `geos38-3.8.1-2.f36.x86_64`
```
182486 openat(AT_FDCWD, "/usr/geos38/lib64/libgeos_c.so.1", O_RDONLY|O_CLOEXEC) = 3
182486 newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=250064, ...}, AT_EMPTY_PATH) = 0
```
after removing geos38 it found the lib in `geos39`

```
186250 openat(AT_FDCWD, "/usr/geos39/lib64/libgeos_c.so.1", O_RDONLY|O_CLOEXEC) = 3
```
after removing geos39 it found the lib in `/lib64/libgeos_c.so.1` from `geos-3.10.2-4.fc36.x86_64`
```
187832 openat(AT_FDCWD, "/lib64/libgeos_c.so.1", O_RDONLY|O_CLOEXEC) = 3
187832 newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=272848, ...}, AT_EMPTY_PATH) = 0
187832 openat(AT_FDCWD, "/lib64/libgeos.so.3.10.2", O_RDONLY|O_CLOEXEC) = 3
```

I think, will be better:
* somehow provide Nuitka paths where to find such libraries.
* add a feature to track the source path for all copied and renamed libraries to some file.

**Comment by belonesox** [comment]
BTW, provided archive with sample  (with the binary wheel without libgeos) good to reproduce the example? What tag «needs_example» ask for?

**Comment by kayhayen** [comment]
You may confirm that providing `dest_path` solves the issue, which is what I believe to be the case from looking at the code. The PyPI and Anaconda configs don't both do it, but then again they are also only for old versions.

**Comment by kayhayen** [comment]
Any feedback on this one?

**Comment by belonesox** [comment]
> You may confirm that providing dest_path solves the issue

On pypi branch `shapely.geos._lgeos._name` return lib without path.  Should I hack `Shapely` to check it «providing dest_path solves the issue»?

For my own purposes, now I use very dirty workaround:
* Creating a folder like `xx/syslibs`
* Create symlink for all libs in /usr/lib64/* to  `xx/syslibs/*.so`
* For each reinstalled python wheel package  rebuilded with system libraries, I create a symlink folder '[package].libs' like 
```
 bchlib.libs -> …/tmp/syslibs
 numpy.libs -> …/tmp/syslibs
 scikit_image.libs -> …/tmp/syslibs
```

Very ugly, but looks working for now.

**Comment by kayhayen** [comment]
What do you mean PyPI branch, with the PyPI package, I was thinking it's a full filename, isn't it. But I think only old shapely was using it, maybe newer one only has a name. But how does your version of shapely, the self-compiled one, locate the original DLLs, is there some path baked into it, or how? What is `load_dll` in `shapely.geos` looking like?

**Comment by kayhayen** [comment]
Closing for lack of feedback.
