### ISSUE TITLE
Nuitka MacOS CI

### ISSUE THREAD

**Issue by kayhayen** [Nuitka/Nuitka#233]
Project description: Nuitka has currently no CI for MacOS, which means it can be broken in any release.

Your task would be to enhance the Travis configuration to introduce that the tests are run on MacOS too. Ideally you would also manage to get Anaconda on that platform used, but that is not expected.

Your mentors will not be able to help with MacOS specifics. Nuitka is known to work on the platform, but Travis might expose differences that need some addressing.

**Comment by kayhayen** [comment]
I think I am retracting this idea, for lack of interest. It still needs implementation, but we are not going to be able to mentor this well, and there was no interest.

**Comment by kayhayen** [comment]
@JorjMcKie If I understood you correctly, this would be really easy for you?

**Comment by JorjMcKie** [comment]
Another day with internet at snail speed, so please forgive sending mails.
I’ll take my wheel generator and adapt it ...

Von meinem iPhone gesendet

Am 18.05.2019 um 06:13 schrieb Kay Hayen <notifications@github.com<mailto:notifications@github.com>>:


@JorjMcKie<https://github.com/JorjMcKie> If I understood you correctly, this would be really easy for you?

**Comment by kayhayen** [comment]
@JorjMcKie thanks for helping, with this one, your config proved to be the key, it's now working on Travis
