### ISSUE TITLE
Dependencies from "pefile", open issues

### ISSUE THREAD

**Issue by kayhayen** [Nuitka/Nuitka#234]
After merging, I discovered the following things (this is a collection issue)

* The pefile is always imported on Windows. I made it more optional on factory branch, soon to become the next pre-release. We don't want to force people to install pefile just yet.

* The warning for files not found was specific for pefile branch and very good. I moved it up to all platforms benefit from testing the file existing and properly warning (turned info to warning) about it.

* For testing I first set out with Python2.7 which gets a warning for the MSVC runtime DLL. This one is found via SxS (Side by Side) manifests. Nuitka carefully copies those over into created binaries, and depends.exe finds them. Not sure if pefile deals with them. They are generally not useful in Python extension modules, and I recently even added code to remove them, because it makes things fail, and SxS is not to be used, except maybe with MSVC runtime DLL.

This made me think though, and I expect that this MSVC runtime DLL will be the *only* DLL with that issue, and live on a very strange path. Probably with Windows 10 it is safe to ignore too, then this is not an issue at all. Otherwise, for standalone mode, we ought to *not* copy the manifest and put the DLL alongside. That will improve things only.

So far things look very good @deajan, ignoring that C runtime DLL of Python 2.7 is roughly the only real issue. Locating if from the running CPython would be trivial I hope, there is already code that locations Python27.dll that way.

* The list of ignored DLLs for pefile and dependency walker is different now. Probably need to find a
  way to consolidate that. Not sure how to achieve that.

**Comment by kayhayen** [comment]
Ah, one more thing, I really felt the desire to move Win32 stuff out of Standalone.py, so it's not all that big, but that can be done anytime we settled on the code, not during changes.

**Comment by kayhayen** [comment]
Due to lack of time I didn't yet do much comparisons.

One thing I also changed @deajan is that I made the cache directory for "pefile" different name than the one for "depends.exe", so I don't have to force update all the time to switch providing implementation of cache content.

**Comment by deajan** [comment]
The DLL lists are different since my list includes two more DLLs I found to be part of MSVC redistribuable, that should not come with a standalone executable.
I think it's safe to merge the two lists by now, including both exclusions I added.

As for the cache, it's indeed a very good idea to make different cache files for both versions :)

I honestly wouldn't move the Win32 stuff out of Standalone.py, since it really was helpful reading the code for Linux in order to see what could be done for Windows, and having all that more or less same logic in the same place makes sense to me... 

I've read your cleanup commit and it seems great btw.

Just ping me if you need some tests.

**Comment by kayhayen** [comment]
So, I created a binary called `dll_report` (going to be on factory soon) and it shows disappointing results., very much so.

Turns out, merely using `pefile` will not be good enough.  I think we will not have the last 2 of these items:

http://www.dependencywalker.com/help/html/dependency_types.htm

> Implicit Dependency (also known as a load-time dependency or sometimes incorrectly referred to as static dependency): Module A is implicitly linked with a LIB file for Module B at compile/link time, and Module A's source code actually calls one or more functions in Module B. Module B is a load time dependency of Module A and will be loaded into memory regardless if Module A actually makes a call to Module B at run-time. Module B will be listed in Module A's import table.
> 
> Delay-load Dependency: Module A is delay-load linked with a LIB file for Module B at compile/link time, and Module A's source code actually calls one or more functions in Module B. Module B is a dynamic dependency and will only be loaded if Module A actually makes a call to Module B at run-time. Module B will be listed in Module A's delay-load import table.
> 
> Forward Dependency: Module A is linked with a LIB file for Module B at compile/link time, and Module A's source code actually calls one or more functions in Module B. One of the functions called in Module B is actually a forwarded function call to Module C. Module B and Module C are both dependencies of Module A, but only Module B will be listed in Module A's import table.

I don't even know how this would be done, and we end up re-implementing the dependency walker code.

**Comment by kayhayen** [comment]
Example output:

```
$ PYTHONPATH=`pwd` /c/Python27_32/python nuitka/tools/general/dll_report/__main__.py /c/Python27_32/DLLs/tk85.dll
 Filename: C:/Python27_32/DLLs/tk85.dll
Version Information: (8L, 5L, 2L, 15L)
DLLs directly dependended (pefile): {'DLLs': [u'KERNEL32.dll', u'USER32.dll', u'GDI32.dll', u'MSVCR90.dll', u'COMDLG32.dll', u'SHELL32.dll', u'ole32.dll', u'OLEAUT32.dll', u'COMCTL32.dll', u'ADVAPI32.dll', u'IMM32.dll'], 'AMD64': False}
DLLs recursively dependended (pefile):
   c:\windows\system32\advapi32.dll
   c:\windows\system32\bcryptprimitives.dll
   c:\windows\system32\combase.dll
   c:\windows\system32\comctl32.dll
   c:\windows\system32\comdlg32.dll
   c:\windows\system32\cryptbase.dll
   c:\windows\system32\gdi32.dll
   c:\windows\system32\imm32.dll
   c:\windows\system32\kernel32.dll
   c:\windows\system32\kernelbase.dll
   c:\windows\system32\msvcp_win.dll
   c:\windows\system32\msvcrt.dll
   c:\windows\system32\ntdll.dll
   c:\windows\system32\ole32.dll
   c:\windows\system32\oleaut32.dll
   c:\windows\system32\rpcrt4.dll
   c:\windows\system32\sechost.dll
   c:\windows\system32\shell32.dll
   c:\windows\system32\shlwapi.dll
   c:\windows\system32\sspicli.dll
   c:\windows\system32\user32.dll
   c:\windows\system32\win32u.dll
Total: 22
DLLs recursively dependended (depends.exe):
   c:\windows\system32\aepic.dll
   c:\windows\system32\bcp47mrm.dll
   c:\windows\system32\cldapi.dll
   c:\windows\system32\contactactivation.dll
   c:\windows\system32\coremessaging.dll
   c:\windows\system32\coreuicomponents.dll
   c:\windows\system32\cryptnet.dll
   c:\windows\system32\cryptngc.dll
   c:\windows\system32\crypttpmeksvc.dll
   c:\windows\system32\d3d12.dll
   c:\windows\system32\d3dscache.dll
   c:\windows\system32\dbgcore.dll
   c:\windows\system32\dbgeng.dll
   c:\windows\system32\dbgmodel.dll
   c:\windows\system32\dsclient.dll
   c:\windows\system32\dsreg.dll
   c:\windows\system32\dxilconv.dll
   c:\windows\system32\edpauditapi.dll
   c:\windows\system32\edputil.dll
   c:\windows\system32\efswrt.dll
   c:\windows\system32\fwbase.dll
   c:\windows\system32\fwpolicyiomgr.dll
   c:\windows\system32\hid.dll
   c:\windows\system32\ieapfltr.dll
   c:\windows\system32\mi.dll
   c:\windows\system32\miutils.dll
   c:\windows\system32\msiso.dll
   c:\windows\system32\msvcp110_win.dll
   c:\windows\system32\msvcp_win.dll
   c:\windows\system32\msvcrt.dll
   c:\windows\system32\policymanager.dll
   c:\windows\system32\rmclient.dll
   c:\windows\system32\srpapi.dll
   c:\windows\system32\textinputframework.dll
   c:\windows\system32\tokenbinding.dll
   c:\windows\system32\tpmcoreprovisioning.dll
   c:\windows\system32\userdatatypehelperutil.dll
   c:\windows\system32\webauthn.dll
   c:\windows\system32\wer.dll
   c:\windows\system32\win32u.dll
   c:\windows\system32\windowsperformancerecordercontrol.dll
   c:\windows\system32\wpcwebfilter.dll
   c:\windows\system32\wuceffects.dll
Total: 43

```

**Comment by kayhayen** [comment]
Notice, that pefile only outputs white listed DLLs (I removed them from being ignored directly in hopes of these other DLLs becoming visible, they do not). So pefile actually gives 0 files to copy, which may even be a correct value.

The ones from dependency walker, may not come from the Python installer, and therefore could also deserve to be white listed. However the point is not that. The point is that we cannot detect many kinds of used DLLs. Or are we claiming these to be irrelevant?

**Comment by kayhayen** [comment]
Given that I always do unprivileged installs of Python, loading anything from the system directory will be wrong (in my case), so I will try and achieve that it doesn't happen for me.

**Comment by kayhayen** [comment]
We could maybe dream up a mode, where Dependency Walker does not even look into system directories, because honestly, the days where PyQt had a Windows installer, that would do things there, are over, and the Python DLL, we can find it by other means. Maybe then it will even be fast? Because there is an incredible amount of output related to those.

**Comment by kayhayen** [comment]
I just noticed, why pywin32 needed special help to be added to the scanned directories, for pefile, we are not considering PATH environment, where this lives on my system. This is SysPath for dependency walker, which we should replace by a filtered one, since this includes C:\Windows\System32 on my installation, and maybe even always.

**Comment by JorjMcKie** [comment]
I am **very** much in favor of doing exactly this.
For anyone using a non-canonic installation method, there could be a special pefile usage option, eg. provided via an optional parameter.

**Comment by kayhayen** [comment]
Ok, with this change, the output is easy to oversee:

```
[   ] c:\python27_32\dlls\TK85.DLL
     [ ? ] KERNEL32.DLL
     [ ? ] USER32.DLL
     [ ? ] GDI32.DLL
     [   ] c:\windows\winsxs\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9518_none_508db366bcbd18c4\MSVCR90.DLL
          [ ? ] KERNEL32.DLL
     [ ? ] COMDLG32.DLL
     [ ? ] SHELL32.DLL
     [ ? ] OLE32.DLL
     [ ? ] OLEAUT32.DLL
     [   ] c:\windows\winsxs\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.17763.475_none_589319ff78a9185b\COMCTL32.DLL
          [ ? ] NTDLL.DLL
          [ ? ] ADVAPI32.DLL
          [ ? ] GDI32.DLL
          [ ? ] KERNEL32.DLL
          [ ? ] USER32.DLL
     [ ? ] ADVAPI32.DLL
     [ ? ] IMM32.DLL

```

So, I am definitely doing to implement this. Then we will still have the benefits of delay load dependencies being supported, without the trouble of scanning parts of the system, where we feel nothing should be used.

**Comment by JorjMcKie** [comment]
I also believe we may need a plugin for fully supporting pywin32. There are cases where some of its components are being imported in some hidden way.

**Comment by kayhayen** [comment]
I didn't make timings, but I swear, it's faster now than pefile module.

Remains to be seen, if this also makes the duplicate work being done in the PyQt5 case more bearable. Lets not forget, for most things, it's one time.

**Comment by kayhayen** [comment]
@JorjMcKie Did you see this one:

```
            # Hack for PyWin32. TODO: Move this "__path__" extensions to be
            # plug-in decisions.
            if package_name == "win32com":
                yield os.path.join(element, "win32comext"), True
```

I did this years ago, it's a strange package.

**Comment by JorjMcKie** [comment]
yes, exactly.

**Comment by JorjMcKie** [comment]
For full OPC support, a plugin is definitely needed to include one of the missing DLL `pythonvomXY.dll` or `pywintypesXY.dll` - forgot which one of the two. Both are located in `...\pywin32_system32`. For some rreason, implicit import didn't help in this case and I had to use the `considerExtraDlls` method.

**Comment by kayhayen** [comment]
@JorjMcKie For what it feels now, it seems I will improve dependency walker using code, and hopefully make it more usable as a result, then check out new performance. My try now with a `PyQt4.QtNetwork.pyd` from Anaconda2 was lightning fast without caching.

Hopefully it's all good then, and it leaves us with caching as a remaining issue. One thing that is annoying is that installing a virtualenv in a temporary path, requires a new scan, of what is going to give similar results. One could create from the concatened names of all DLLs in the folders, a salt for the cache key, which in theory could be nice. Then just check the MD5 sums and we are good. Something like that.

**Comment by kayhayen** [comment]
@JorjMcKie Regarding DLLs, they are never implicit imports, that is only Python modules. One exception are the DLLs using by cffi, they are named like `.pyd` files, and can be found that way, without being actually modules. Nasty. But these are more implicit DLLs, aren't they.

**Comment by kayhayen** [comment]
Ok, so this is not all wasted, it made me realize, how the white list is the wrong tool to solve the issue. :-) The whole system directory should be white listed.

Now that I see, do I have to feel ashamed of my wrong doing all those years. :)

**Comment by kayhayen** [comment]
Hm, I will definitely keep pefile, it does one thing very well, the output of one DLL is something to cache very well. Doing a checksum over the DLL, we could find its dependencies whatever directory it lives in.

**Comment by kayhayen** [comment]
But for now, I am going to evaluate the change done to dependency walker path, and make the two share the code for the scan directories more fully. Then we have immediate benefit already, and then worry about caching down the road.

**Comment by kayhayen** [comment]
So, I got this mostly sorted out, or so I feel:

This as a teaser:

> Nuitka:INFO:Running depends.exe for Functions.dist\Functions.exe took 0.10 seconds
> Nuitka:INFO:Running depends.exe for Functions.dist\_bsddb.pyd took 0.08 seconds
> Nuitka:INFO:Running depends.exe for Functions.dist\_ctypes.pyd took 0.07 seconds
> Nuitka:INFO:Running depends.exe for Functions.dist\_elementtree.pyd took 0.07 seconds
> Nuitka:INFO:Running depends.exe for Functions.dist\_hashlib.pyd took 0.07 seconds
> Nuitka:INFO:Running depends.exe for Functions.dist\_msi.pyd took 0.07 seconds
> Nuitka:INFO:Running depends.exe for Functions.dist\_multiprocessing.pyd took 0.07 seconds
> Nuitka:INFO:Running depends.exe for Functions.dist\_socket.pyd took 0.07 seconds
> Nuitka:INFO:Running depends.exe for Functions.dist\_sqlite3.pyd took 0.08 seconds
> Nuitka:INFO:Running depends.exe for Functions.dist\_ssl.pyd took 0.08 seconds
> Nuitka:INFO:Running depends.exe for Functions.dist\_tkinter.pyd took 0.10 seconds
> Nuitka:INFO:Running depends.exe for Functions.dist\bz2.pyd took 0.07 seconds
> Nuitka:INFO:Running depends.exe for Functions.dist\pyexpat.pyd took 0.07 seconds
> Nuitka:INFO:Running depends.exe for Functions.dist\select.pyd took 0.07 seconds
> Nuitka:INFO:Running depends.exe for Functions.dist\unicodedata.pyd took 0.08 seconds

This is not using concurrent.futures, which I disabled, because at least on my Python 2.7, it will not obey the "first exception" rule, and a thread that raises an exception will cause endless hangs. I also had dead locks due to this. Really bad.

Arguably caching my not be necessary at all anymore.

**Comment by kayhayen** [comment]
For pefile, these are the figures:

> Nuitka:INFO:Finding dependencies for Functions.dist\Functions.exe took 3.60 seconds
> Nuitka:INFO:Finding dependencies for Functions.dist\_bsddb.pyd took 1.40 seconds
> Nuitka:INFO:Finding dependencies for Functions.dist\_ctypes.pyd took 0.32 seconds
> Nuitka:INFO:Finding dependencies for Functions.dist\_elementtree.pyd took 0.30 seconds
> Nuitka:INFO:Finding dependencies for Functions.dist\_hashlib.pyd took 1.67 seconds
> Nuitka:INFO:Finding dependencies for Functions.dist\_msi.pyd took 0.12 seconds
> Nuitka:INFO:Finding dependencies for Functions.dist\_multiprocessing.pyd took 0.15 seconds
> Nuitka:INFO:Finding dependencies for Functions.dist\_socket.pyd took 0.16 seconds
> Nuitka:INFO:Finding dependencies for Functions.dist\_sqlite3.pyd took 0.85 seconds
> Nuitka:INFO:Finding dependencies for Functions.dist\_ssl.pyd took 2.27 seconds
> Nuitka:INFO:Finding dependencies for Functions.dist\_tkinter.pyd took 3.69 seconds
> Nuitka:INFO:Finding dependencies for Functions.dist\bz2.pyd took 0.13 seconds
> Nuitka:INFO:Finding dependencies for Functions.dist\pyexpat.pyd took 0.36 seconds
> Nuitka:INFO:Finding dependencies for Functions.dist\select.pyd took 0.06 seconds
> Nuitka:INFO:Finding dependencies for Functions.dist\unicodedata.pyd took 0.34 seconds

Obviously that means we should compile `pefile` with Nuitka. :)

Still nothing in comparison. I think I saw 70s happening before.

Not using the forking thing may be very wise, because on Windows it will clone the full Python process, and potentially a lot of memory along with it. Will it not? Right now I don't see the point of it, and will leave it disabled, as debugging is easier that way.

Once this makes it through my internal CI, I will push it to factory. Then I need to resume comparative testing for DLLs. But maybe we first get feedback on how good it works as a result.

Yours,
Kay

**Comment by kayhayen** [comment]
I mean, the reduced file set, does it even run on other machines. Hard to test for me.

**Comment by deajan** [comment]
Sorry, being late for the dependency party.
Can test things if necessary. Indeed, depends is now REALLY quick.
But, the files "api-ms-win*" are back in the distribution.
Eg:
```
api-ms-win-core-console-l1-1-0.dll
api-ms-win-core-datetime-l1-1-0.dll
api-ms-win-core-debug-l1-1-0.dll
api-ms-win-core-errorhandling-l1-1-0.dll
api-ms-win-core-file-l1-1-0.dll
api-ms-win-core-file-l1-2-0.dll
api-ms-win-core-file-l2-1-0.dll
api-ms-win-core-handle-l1-1-0.dll
api-ms-win-core-heap-l1-1-0.dll
api-ms-win-core-interlocked-l1-1-0.dll
api-ms-win-core-libraryloader-l1-1-0.dll
api-ms-win-core-localization-l1-2-0.dll
api-ms-win-core-memory-l1-1-0.dll
api-ms-win-core-namedpipe-l1-1-0.dll
api-ms-win-core-processenvironment-l1-1-0.dll
api-ms-win-core-processthreads-l1-1-0.dll
api-ms-win-core-processthreads-l1-1-1.dll
api-ms-win-core-profile-l1-1-0.dll
api-ms-win-core-rtlsupport-l1-1-0.dll
api-ms-win-core-string-l1-1-0.dll
api-ms-win-core-synch-l1-1-0.dll
api-ms-win-core-synch-l1-2-0.dll
api-ms-win-core-sysinfo-l1-1-0.dll
api-ms-win-core-timezone-l1-1-0.dll
api-ms-win-core-util-l1-1-0.dll
api-ms-win-crt-conio-l1-1-0.dll
api-ms-win-crt-convert-l1-1-0.dll
api-ms-win-crt-environment-l1-1-0.dll
api-ms-win-crt-filesystem-l1-1-0.dll
api-ms-win-crt-heap-l1-1-0.dll
api-ms-win-crt-locale-l1-1-0.dll
api-ms-win-crt-math-l1-1-0.dll
api-ms-win-crt-multibyte-l1-1-0.dll
api-ms-win-crt-process-l1-1-0.dll
api-ms-win-crt-runtime-l1-1-0.dll
api-ms-win-crt-stdio-l1-1-0.dll
api-ms-win-crt-string-l1-1-0.dll
api-ms-win-crt-time-l1-1-0.dll
api-ms-win-crt-utility-l1-1-0.dll
```

**Comment by kayhayen** [comment]
Is this still relevant? The api DLLs still being present without a need?

**Comment by kayhayen** [comment]
This is resolved.
