### ISSUE TITLE
Is it possible to compile all modules in site-package with --module mode?

### ISSUE THREAD

**Issue by 32h3basfl2** [Nuitka/Nuitka#2342]
My question:
Is it possible to add an option `--follow-dependencies` on `--module` mode?

My situation and use case:
I need to call Python function from C++ program, and the built C++ program need to be run on client's machine without python. The Python function include site-package such as `transformers`. I already understand I need embedded Python to deal with it. However, embedded environment with no site-package (you don't want them neither due to the size). Nuitka can already compile a package into a single .pyd, so theoretically we can compile all site-package into one .pyd (or several .pyd also fine)? 

My attempted:
1. I have tried to compile a python module with `--module` and result with a `my_func.pyd`. However, import the module will need site-package such as `torch` included in either embedded environment or client's machine.
1. `--module` never work with `follow-imports`. It may make sense to exclude Python built-in library, but this result need to manually `follow-import-to`/`--include-package` one by one, since some site-package also relies on another site-package (e.g.: `transformers` need `torch`), where the dependencies are not included automatically.
1. (This is just idea and may not even feasible to work.) I tried build with --standalone, and put everything with my separated built module .pyd in my embedded Python and see if the import can find the dependencies. However, most packages can never be found by that Python, since the built environment do not contain folder `transformers`, but the compiled `program.exe` know where to import it.

Current workaround:
The best I can think of is using the YAML file to configure all dependencies required by a site package, but not yet to get successful.

**Comment by kayhayen** [comment]
From my experience, you need a kind of bootstrap to even embedd Python, some modules are technical. Nuitka does tricks to embedd them still, you will have to replicate those. From then on, Nuitka can provide all modules, yes, but for that to be done, if would have be imported first.

I believe --include-package could work, but where are extension modules, you would have to carry them along manually yourself, since they are currently not embedded, although Nuitka commercial is likely to gain the ability to embedd DLLs and extension modules this summer on Linux, I cannot promise on that being workable for everything: https://nuitka.net/doc/commercial.html

The case for Nuitka to produce a standalone DLL that embedds Python for you, and then runs sort of standalone inside a C++ application, that doesn't see Python ever, is often presented, but never funded so far. Somebody probably would have to pay for 2 weeks of my time there.

**Comment by 32h3basfl2** [comment]
Thanks for the reply. May I confirmed that the embedded DLL and standalone extension module will be on commercial? (since this is not mentioned in commercial feature, it will be hard to propose funding from my firm)

However, AFAIK, embed Python completely inside C++ is only feasible on Unix-like now(?) Because the [official document](https://docs.python.org/extending/embedding.html) never mention how to do it on Windows. Most of our customers are on Windows system. If Nuitka can pack a Python library to standalone DLL for C++ usage, it will be an easier reason to propose the funding.

For now, simple site-package without complicated dependencies (e.g.: numpy) can easily work. For complicated one, the best can be done now is build `--standalone` once and record all the path it traced, and build --module later using `include-package/module` for all of traced package/module, then pull out all the required dll and data file to the embedded python.

**Comment by kayhayen** [comment]
It's not implemented yet, so it can hardly be part of the advertising. For what I know, `py2exe` once did embedded DLL loading on Windows, but I decided against it back then. I am not sure of the veracity of that though, and the Python DLL on Windows is really a big problem.

Nuitka and Nuitka-Python achieve things on Windows: https://github.com/Nuitka/Nuitka-Python

The trick there is that DLLs and extension modules are not used, but e.g. numpy can become a built-in to python.exe after `pip install numpy`, this is so cool, I am always baffled about it.

Nuitka Themida does similar things on Windows as well: https://nuitka.net/doc/bundles.html and they even defeat the Python DLL on Windows, which other tools of the kind do not allow. This uses DLLs and extension modules, but in an invisible fashion to the user. Probably also does re-implement the DLL loader.

Now, integrating this into a DLL, that's all hard. I think Nuitka-Python on Windows has the potential to become a DLL the easiest way. It's probably tough in terms of making packages work. But I know that huge Panda3D game stacks are deployed with Nuitka-Python on our typical 3 platforms, Windows, Linux and macOS. But if a package is not currently supported, then of course, things can quickly become not-workable quickly.

When Nuitka is ran with Nuitka-Python, it solves the stdlib and Python files compilation for all code. The result is a binary without dependencies. Making a DLL instead, maybe not that hard. But I think all of that would require a bunch of funding for me to work on it. And lets face it, you are probably not having it.
