### ISSUE TITLE
Nuitka .exe instantly closes on other PC

### ISSUE THREAD

**Issue by JorgTV** [Nuitka/Nuitka#2348]
The other PC has the same Python Conda version, the same packages installed in conda (nuitka, too obviously) but after openíng it on another pc that is not mine the file instantly closes again. My PC has windows 11, the other PC has windows 10. No error message is showing whatsoever, it's just instantly closing without warning.

Nutika version:

> Name: Nuitka
> Version: 1.7.5
> Summary: Python compiler with full language support and CPython compatibility
> Home-page: https://nuitka.net
> Author: Kay Hayen
> Author-email: Kay.Hayen@gmail.com
> License: Apache License, Version 2.0
> Location: C:\Users\Anwender\Downloads\anaconda\Lib\site-packages
> Requires: ordered-set, zstandard
> Required-by:

Imports:

> import cv2
> import numpy as np
> import torch
> from mss import mss
> import io
> import configparser
> import mouse
> import math
> import winsound
> import win32api

Errors or warnings:

> Python path configuration:
>   PYTHONHOME = 'C:\Users\Anwender\Downloads\anaconda'
>   PYTHONPATH = (not set)
>   program name = 'C:\Users\pidco\Downloads\John_Pidcock_V1\John_Pidcock_V1\john_pidcock.exe'
>   isolated = 0
>   environment = 1
>   user site = 1
>   safe_path = 0
>   import site = 0
>   is in build tree = 0
>   stdlib dir = 'C:\Users\Anwender\Downloads\anaconda\Lib'
>   sys._base_executable = 'C:\Users\pidco\Downloads\John_Pidcock_V1\John_Pidcock_V1\john_pidcock.exe'
>   sys.base_prefix = 'C:\Users\Anwender\Downloads\anaconda'
>   sys.base_exec_prefix = 'C:\Users\Anwender\Downloads\anaconda'
>   sys.platlibdir = 'DLLs'
>   sys.executable = 'C:\Users\pidco\Downloads\John_Pidcock_V1\John_Pidcock_V1\john_pidcock.exe'
>   sys.prefix = 'C:\Users\Anwender\Downloads\anaconda'
>   sys.exec_prefix = 'C:\Users\Anwender\Downloads\anaconda'
>   sys.path = [
>     'C:\Users\pidco\anaconda3\python311.zip',
>     'C:\Users\Anwender\Downloads\anaconda\DLLs',
>     'C:\Users\Anwender\Downloads\anaconda\Lib',
>     'C:\Users\pidco\Downloads\John_Pidcock_V1\John_Pidcock_V1',
>   ]
> Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
> Python runtime state: core initialized
> ModuleNotFoundError: No module named 'encodings'
> 
> Current thread 0x00007f84 (most recent call first):
>   <no Python frame>

**Comment by SirDank** [comment]
try using the following flag `--windows-force-stderr-spec=errors.txt`
it will generate an error.txt file and any error should be visible there!

**Comment by JorgTV** [comment]
> try using the following flag `--windows-force-stderr-spec=errors.txt` it will generate an errors.txt file and any error should be visible there!

Thanks! Updated it.

**Comment by kayhayen** [comment]
For running on another machine, --standalone must be used, or you need to be knowing really well what you are doing. But since you failed to even fill out the issue template no way.
