### ISSUE TITLE
Can not use moultiprocess module with Nuitka

### ISSUE THREAD

**Issue by CookingANut** [Nuitka/Nuitka#2350]
**VERSION:**
1.5.4
Commercial: None
Python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Program Files\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\bin\HostX64\x64\cl.exe (cl 14.3).

**COMMAND LINE:**
Nuitka-Options:INFO: Used command line options: 
--onefile
 --standalone 
--remove-output 
--follow-imports 
--output-filename=LgTreeGen 
--output-dir="C:\Desktop\proj\src\py\DataMonitor" 
 LgTreeGen.py

**ISSUE:**
if I dont use multiprocess module, after nuitka compiling, all thing went well.
But if I use mutiprocess, it just stuck at command window, nothing happened ....(no any error, just stuck in command window)
I have tried below:
- removing one file argument, no help
- add multiprocess.freeze_support() after if __name__== "__main__", no help
- def LgTreeGenerator().run() as a function and move __name__ == "__main__" to another py file and call this function, no help 

Does there have some trick way that I can use multiprocess module with Nuitka?

**CODES DEMO:**
...
import multiprocessing as mp
...
class LgTreeGenerator:
    def __init__(self):
        print("Initializing Generator")
        conf = configparser.ConfigParser()
        conf.read(f"{CWD}{SEP}configuration.ini",encoding="utf-8")
        self.search_path_list =  [i[1] for i in conf.items('SEARCH_PATH')]
        self.export_path = conf["EXPORT_PATH"]['export_path']

    def run(self):
        pool = mp.Pool(processes=len(self.search_path_list))
        pool.map(self.tree_gen, self.search_path_list)

    def tree_gen(self, search_path):
        # I have some print in this function, but command window show nothing)
        ...

if __name__ == "__main__":
    mp.freeze_support()
    LgTreeGenerator().run()

**Comment by kayhayen** [comment]
Please use the most recent stable version, this is quite a few bug fixes behind.

**Comment by CookingANut** [comment]
> 

thanks man, 1.7.6 works
