### ISSUE TITLE
When there are imports of  numpy and pandas, how to make build speed faster on Windows platform?

### ISSUE THREAD

**Issue by rushwing** [Nuitka/Nuitka#2351]
**Problem:** 
Due to project requirements, we need to import pandas and numpy in our code. 
But under --standalone mode, it would compile the whole package instead of the actual needed modules. The compile takes about 15 to 20 minutes for one microservice (Windows Laptop i7 3GHz, 32GB memory), and our projects has up to 4 microservices, so it takes about more than one hour to compile the whole project.
But the same microservice on Mac OS (Macbook M1 Pro) takes only 5 minutes even for a clean cache build.

**The build command used for Mac:**
```
python3.10 -m nuitka --output-dir=dist/ \
    --include-package=main \
    --include-module=xxx.xxx.xxx.columbus.columbus_app.serv_reg.generated \
    --standalone main.py
```

**The output of Mac build:**
```
[BUILD] Cleaning build cache with Nuitka ...
Nuitka-Options:INFO: Used command line options: --clean-cache=all
Nuitka-Cache:INFO: Cleaning cache 'ccache' directory '/Users/danielwong/Library/Caches/Nuitka/ccache'.
Nuitka-Cache:INFO: Done.
Nuitka-Cache:INFO: Cleaning cache 'bytecode' directory '/Users/danielwong/Library/Caches/Nuitka/module-cache'.
Nuitka-Cache:INFO: Done.
[BUILD] Generating standalone executable using Nuitka ...
Nuitka-Options:INFO: Used command line options: --output-dir=dist/ --include-package=main --include-module=arvr.projects.manufacturing.columbus.columbus_app.serv_reg.generated --standalone main.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.6.3' on Python '3.10' commercial grade 'not installed'.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':                                          
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka-Plugins:INFO: pkg-resources: Injecting post-module load code for module 'pkg_resources':                                            
Nuitka-Plugins:INFO: pkg-resources:     Registering Nuitka loader with "pkg_resources".
Nuitka:INFO: Completed Python level compilation and optimization.                                                                              
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.                                                                                
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: clang (clang).
Nuitka-Scons:INFO: Scons: Inherited CPPFLAGS='-I/opt/homebrew/opt/openssl@3/include' variable.
Nuitka-Scons:INFO: Scons: Inherited LDFLAGS='-L/opt/homebrew/opt/openssl@3/lib' variable.
Nuitka-Scons:INFO: Backend linking program with 491 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 491 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 491
Nuitka-Plugins:INFO: data-files: Included data file 'pandas/io/formats/templates/html.tpl' due to package data directory 'templates' for 'pandas.io.formats'.
Nuitka-Plugins:INFO: data-files: Included data file 'pandas/io/formats/templates/html_style.tpl' due to package data directory 'templates' for 'pandas.io.formats'.
Nuitka-Plugins:INFO: data-files: Included data file 'pandas/io/formats/templates/html_table.tpl' due to package data directory 'templates' for 'pandas.io.formats'.
Nuitka-Plugins:INFO: data-files: Included data file 'pandas/io/formats/templates/latex.tpl' due to package data directory 'templates' for 'pandas.io.formats'.
Nuitka-Plugins:INFO: data-files: Included data file 'pandas/io/formats/templates/latex_longtable.tpl' due to package data directory 'templates' for 'pandas.io.formats'.
Nuitka-Plugins:INFO: data-files: Included data file 'pandas/io/formats/templates/latex_table.tpl' due to package data directory 'templates' for 'pandas.io.formats'.
Nuitka-Plugins:INFO: data-files: Included data file 'pandas/io/formats/templates/string.tpl' due to package data directory 'templates' for 'pandas.io.formats'.
Nuitka-Plugins:INFO: data-files: Included 602 data files due to package data directory 'zoneinfo' for 'pytz'.
Nuitka:INFO: Keeping build directory 'dist/main.build'.                                           
Nuitka:INFO: Created binary that runs on macOS 13.0 (arm64) or higher.
Nuitka:INFO: Successfully created 'dist/main.dist/main.bin'.
[CLEANUP] Build successfully.
```

**The build command used for Windows:**
I tried the same command of Mac, no build performance improved, so I tried the following:
```
python -m nuitka --mingw64
                    --show-memory --show-progress
                    --output-dir=dist/
                    --enable-plugin=anti-bloat
                    --nofollow-import-to=unittest
                    --include-plugin-directory=generated
                    --standalone main.py
```

**The output of Windows build:**
See attachment.
[win_nuitka_build.txt](https://github.com/Nuitka/Nuitka/files/12146625/win_nuitka_build.txt)

**Nuitka version, full Python version, flavor, OS, etc. as output by this
command.**

1.6.3
Commercial: None
Python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\danielwong\xxx\xxx\xxx\columbus\columbus_app\build\columbus_app_venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\cl.exe (cl 14.3).

**How did you install Nuitka and Python**

I installed Python in a virtualenv, and install Nuitka with python3.10 -m pip install -r pip_requirements.txt

**Solution I tried:**
I tried to use: "--nofollow-import-to=unittest,numpy,pandas"
The compiling time was significantly improved. But when I copied the site-packages from virtualenv to the target exe folder, it continuously report modules not found error:
some modules like bz2, six, which seemed the built-in modules of Python which couldn't be installed from pip install.
Is there any way to resolve this? I think these packages are the dependencies of pandas.
I need to do auto-deploy to the target machine which might not have the internet access, so we cannot do online "pip install", and we'd better not do it through offline "pip install" with whl files.

**Comment by kayhayen** [comment]
You should always use newest Nuitka, it usually becomes more scalable with every release for a while now, although breakthroughs are not to be expected.

You can use multidist to produce only one binary with multiple behaviours. And you produce wheels with only your code and install it into a Python installation.
