### ISSUE TITLE
Exception group throwing exception

### ISSUE THREAD

**Issue by LuisCarlos-104171** [Nuitka/Nuitka#2355]
I tried compiling python code using nuitka and python 3.11, but I am facing this error that states that an exception occurred when compiling exception group.

> nuitka3 --standalone src/main.py
```
module.exceptiongroup._catch.c: In function 'impl_exceptiongroup$_catch$$$function__4_handle_exception':
module.exceptiongroup._catch.c:633:45: error: 'PyBaseexceptiongroup_Type' undeclared (first use in this function); did you mean 'PyBaseExceptionGroupObject'?
  633 |         tmp_isinstance_cls_1 = (PyObject *)&PyBaseexceptiongroup_Type;
      |                                             ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                             PyBaseExceptionGroupObject
module.exceptiongroup._catch.c: In function 'impl_exceptiongroup$_catch$$$function__5_catch':
module.exceptiongroup._catch.c:2883:49: error: 'PyBaseexceptiongroup_Type' undeclared (first use in this function); did you mean 'PyBaseExceptionGroupObject'?
 2883 |         tmp_issubclass_classes_3 = (PyObject *)&PyBaseexceptiongroup_Type;
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 PyBaseExceptionGroupObject
```

This is the python and nuitka version as well the GCC version.
Python was installed via a virtualenv, if needed I can also send the requirements.txt file.
> nuitka3 --version
```
Commercial: None
Python: 3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201]
Flavor: Unknown
Executable: /home/lukas/Documents/SNA/scraper/venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Endeavouros (based on arch) None
Version C compiler: /usr/bin/gcc (gcc).
```

Tried with both Nuika release and the development version, same issue on both.

**Comment by kayhayen** [comment]
I think you cut out the most intereting bit of the --version output and there is no reproducer.

**Comment by LuisCarlos-104171** [comment]
I don't think so but I will double check the version, also the main packages in use are aiopika, scikit and selenium, but as soon as I can I will try and track down the exact problem.

**Comment by LuisCarlos-104171** [comment]
Confirmed it does indeed work, is there an ETA for it to come to a release?

**Comment by kayhayen** [comment]
Yes, when it's ready.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.7.7 that I just made.
