### ISSUE TITLE
Add PEP 660 support?

### ISSUE THREAD

**Issue by shkey** [Nuitka/Nuitka#2356]
Recently when I was trying to use `pdm` to manage the packaging and build process of our company's project, I encountered an issue when using `nuitka.distutils.Build` as the compile and build backend. After I changed the `build-backend` in `pyproject.toml` to `nuitka.distutils.Build`, when I tried to use `pdm install` to install all the dependencies of the current project and install the current project itself in editable mode into the virtual environment, then used `pdm list` to check the installed dependencies, I found the dependencies were not properly installed in the virtual environment. The package names were shown as `UNKNOWN`(should be pdm-demo), which caused import errors in the code. Here is a simple example:

```bash
❯ pdm --version
PDM, version 2.8.0
❯ mkdir pdm-demo
❯ cd pdm-demo
❯ pdm init
❯ cat pyproject.toml
[project]
    authors         = [{ name = "shkey", email = "shkey325@gmail.com" }]
    dependencies    = []
    description     = ""
    dynamic         = ["version"]
    license         = { text = "MIT" }
    name            = "pdm-demo"
    readme          = "README.md"
    requires-python = ">=3.11"

[build-system]
    build-backend = "nuitka.distutils.Build"
    requires      = ["nuitka", "setuptools", "toml", "versioningit", "wheel"]
❯ pdm install -vv
......
All packages are synced to date, nothing to do.
Installing the project as an editable package...
pdm.termui: Preparing isolated env for PEP 517 build...
pdm.termui: Reusing shared build env: /var/folders/v6/sz7x176j2l10hdr9_j3d_d440000gn/T/pdm-build-env-zbhcceff-shared
pdm.termui: Running PEP 517 backend to build a wheel for <Link file:///Users/shkey/Downloads/pdm-demo (from None)>
pdm.termui: The build backend doesn't support PEP 660, falling back to setuptools-pep660
pdm.termui: Reusing shared build env: /var/folders/v6/sz7x176j2l10hdr9_j3d_d440000gn/T/pdm-build-env-wklmp4eq-shared
  ✔ Install pdm-demo 0.0.0 successful

🎉 All complete!
❯ pdm list
╭─────────┬─────────┬────────────────────────────────────╮
│ name    │ version │ location                           │
├─────────┼─────────┼────────────────────────────────────┤
│ UNKNOWN │ 0.0.0   │ -e /Users/shkey/Downloads/pdm-demo │
╰─────────┴─────────┴────────────────────────────────────╯
❯ pdm run python3
Python 3.11.4 (main, Jul  6 2023, 10:52:18) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pdm_demo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pdm_demo'
>>>
```

So can we add PEP 660 support for `nuitka.distutils.Build`?

**Comment by kayhayen** [comment]
How does it recognize that it doesn't support that? Since it's a thin wrapper around `build`, I would assume we inherit what it takes, is this somehow hardcoded? This feels like something, that maybe `pdm` controls. Can you ask the pdm project what it takes there for them to recognize the build-backend as such?

The code is this:

```
# reusing private "build" package code, pylint: disable=protected-access
class NuitkaBuildMetaBackend(setuptools.build_meta._BuildMetaBackend):
    def build_wheel(
        self, wheel_directory, config_settings=None, metadata_directory=None
    ):
        os.environ["NUITKA_TOML_FILE"] = os.path.join(os.getcwd(), "pyproject.toml")

        with suppress_known_deprecation():
            return self._build_with_temp_dir(
                ["bdist_nuitka"], ".whl", wheel_directory, config_settings
            )


_BACKEND = NuitkaBuildMetaBackend()

get_requires_for_build_wheel = _BACKEND.get_requires_for_build_wheel
get_requires_for_build_sdist = _BACKEND.get_requires_for_build_sdist
prepare_metadata_for_build_wheel = _BACKEND.prepare_metadata_for_build_wheel
build_wheel = _BACKEND.build_wheel
build_sdist = _BACKEND.build_sdist
```

If there is another target needed, etc. I would need to know, but I do not really have the expertise that `pdm` probably has.

**Comment by shkey** [comment]
When I looked at the debug messages printed by `pdm install`, I roughly located the cause of the problem. After checking the current code in <https://github.com/Nuitka/Nuitka/blob/develop/nuitka/distutils/Build.py>, I found that the current `Nuitka` build backend does not implement the `build_editable`, `get_requires_for_build_editable` and `prepare_metadata_for_build_editable` hook functions added in [PEP 660](https://peps.python.org/pep-0660/). This caused `pdm` to be unable to correctly install in editable mode when using it as the build backend. 
After comparing with the code implementation in <https://github.com/pypa/setuptools/blob/main/setuptools/build_meta.py>, I made some modifications to the existing `nuitka.distutils.Build` code, and solved this problem by adding just a few lines of code. If possible, I can submit a PR to merge this modification into the `Nuitka` main branch. I believe this modification will also benefit other users.

**Comment by kayhayen** [comment]
Yes, please do that. I would make it part of a hotfix for sure.

**Comment by shkey** [comment]
I submitted a PR #2357 , please review it. @kayhayen

**Comment by shkey** [comment]
> It's good, I will merge it for 1.7.8 to come relatively soon.

Okay, thanks for your work, by the way when is 1.7.8 roughly expected to be released, the work I’m doing right now may be more reliant on this PR to solve the problem.

**Comment by kayhayen** [comment]
I expect to release it when it's ready of course, not sooner and not much later.

**Comment by kayhayen** [comment]
So I made the hotfix 1.7.8 now with this contained, but can I ask you to also checkout factory branch? I made the discussed cleanup, and it would super cool if you could verify, that I am not breaking it for you with 1.8 which should be also right around the corner.

**Comment by shkey** [comment]
This seems to be a bit of a problem, I get the following error when I switch to the factory branch for validation:

```bash
pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines of the build output:
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/var/folders/5r/mg9342cn1hngkyy5f6zbw8fw0000gn/T/pdm-build-env-vaysimzv-shared/lib/python3.11/site-packages/nuitka/distutils/Build.py", line 56, in <module>
    LEGACY_EDITABLE = setuptools.build_meta.getattr("LEGACY_EDITABLE")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'setuptools.build_meta' has no attribute 'getattr'
```

So should we use Python’s built-in getattr method to get the value of `LEGACY_EDITABLE`, like this: ﻿`LEGACY_EDITABLE = getattr(setuptools.build_meta, "LEGACY_EDITABLE")`, I’ve tested it this way the modification is It works fine.

**Comment by shkey** [comment]
LGTM👍
