### ISSUE TITLE
Question: Is there a nuitka feature to be able to decrease .app file size (almost 3GB)?

### ISSUE THREAD

**Issue by emre84** [Nuitka/Nuitka#2359]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version
1.8rc5
Commercial: None
Python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
Flavor: CPython Official
Executable: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7
OS: Darwin
Arch: x86_64
Version C compiler: /usr/bin/clang (clang).

* How did you install Nuitka and Python
git clone

  > python -m pip freeze
tensorflow==2.11.0

* Provide in your issue the Nuitka options used

sudo python3.7 -m nuitka --run --standalone --enable-plugin=pyside6  --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow --python-flag=no_site --include-data-dir=/models=models --include-data-dir=/icons=icons --macos-app-icon=/license_lock_photo.png --macos-create-app-bundle --macos-disable-console --macos-app-protected-resource="NSCameraUsageDescription:xxx." --macos-app-protected-resource="NSPhotoLibraryUsageDescription:xxx." --macos-app-mode=ui-element main.py

Description: 
The size of my main.app file is reached to 2.84 GB. The biggest files and folders are the tensorflow and _pywrap_tensorflow_internal.so files in my app. they are together 1.3 GB. 
Is there any method to reduce the app size?

Thanks a lot in advance.

**Comment by kayhayen** [comment]
When you install tensorflow, how small is that? Nuitka is not going to be able to magically compress it. You can help and join our anti-bloat efforts, as described here: https://nuitka.net/blog/tag/package_config.html

Make a --report file and check it, then identify things you do not believe to be necessary, and come up with anti-bloat patches that avoid unnecessary dependencies.
