### ISSUE TITLE
Due due ctypes, comtypes is included, causing an unused numpy DLL set to be included

### ISSUE THREAD

**Issue by tdRPA** [Nuitka/Nuitka#2360]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version

 ```
1.7.7
Commercial: None
Python: 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\Administrator\AppData\Local\Programs\Python\Python38\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 2012ServerR2
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).

```

* How did you install Nuitka and Python

`  pip3 install nuitka`
-----------

the problem is: unused numpy lib is included.
source file test.py:
`from infi.systray import SysTrayIcon

if __name__ == '__main__':
    pass`

buid cmd:
`nuitka --onefile --show-memory --show-progress --output-dir=dist .\test.py`

all files attached 

but this did 
not happed with version 1.4.2 , just happed after I uninstalled 1.4.2 and installed 1.7.7

[a.txt](https://github.com/Nuitka/Nuitka/files/12211330/a.txt)
[build.bat.txt](https://github.com/Nuitka/Nuitka/files/12211333/build.bat.txt)
[test.py.txt](https://github.com/Nuitka/Nuitka/files/12211334/test.py.txt)

**Comment by kayhayen** [comment]
I run ran this successfully: `python3.10 bin/nuitka-run --stand --noinclude-custom-mode=numpy:error Mini.py` and I suggest you use that option and report what it says, no numpy was pulled in for me there. With --report you should be able to see it as well, but the option I used would just error out.

**Comment by tdRPA** [comment]
邮件已收到，通常我在1～2天内回复。如有急事，请直接电话联系 ----我的微信 haijun-data

**Comment by tdRPA** [comment]
[Nuitka_report.zip](https://github.com/Nuitka/Nuitka/files/12248784/Nuitka_report.zip)
here are the build data

**Comment by kayhayen** [comment]
The 1.7 version find that "comtypes.safearray" is using it. I do not have it installed, it seems something you have installed, and that maybe is an optional dependency. If you remove it, that will immediately help.

I found this code in `ctypes` which Nuitka now analyses for dependencies:

```
if _os.name == "nt": # COM stuff
    def DllGetClassObject(rclsid, riid, ppv):
        try:
            ccom = __import__("comtypes.server.inprocserver", globals(), locals(), ['*'])
        except ImportError:
            return -2147221231 # CLASS_E_CLASSNOTAVAILABLE
        else:
            return ccom.DllGetClassObject(rclsid, riid, ppv)

    def DllCanUnloadNow():
        try:
            ccom = __import__("comtypes.server.inprocserver", globals(), locals(), ['*'])
        except ImportError:
            return 0 # S_OK
        return ccom.DllCanUnloadNow()
```

So, your Python has this which in turn depends on numpy, which in turn pulls in all these things. There is a new feature on develop, that will allow us to express that we do not want to see these imports as a sufficient reason to include.

Thanks for bringing this to attention, seems potentially big. You can maybe research yourself and tell what pulled in comtypes for you, but pip is not really good at that, or is it? Maybe if you attempt uninstall it will tell what that will break. I will have a fix for that shortly. This kind of yaml ought to work with develop branch as user yaml, for stable the data of `no-auto-follow` is different though.

```
- module-name: 'ctypes'
  anti-bloat:
    - description: 'remove comtypes dependency'
      no-auto-follow:
        'comtypes': 'ignore'
```

**Comment by kayhayen** [comment]
Should work, I was getting not-found before the pip install, and now

```
      <module_usage name="comtypes.server.inprocserver" finding="absolute" line="535" />
      <module_usage name="comtypes.server.inprocserver" finding="absolute" line="543" />
```

But comtypes is not installed, so effectively, Nuitka will be potentially incompatible at run time therefore, but I believe this kind of code only makes sense in programs that use it elsewhere already.

**Comment by tdRPA** [comment]
Acturally I do not understand what you are talking about. I am just using Nuikta to do build and do not know it well. So I am here just report this issue. Just checked both 1.4.2 and 1.7.7 are using the same version of cometype comtypes==1.1.14.

The problem is: why Numpy lib is not included with 1.4.2 but 1.7.7

**Comment by kayhayen** [comment]
I am not sure at this time, I might include this in a hotfix to come, but the syntax change makes me want to delay this to 1.8, still to decide.

**Comment by kayhayen** [comment]
I invite you to monitor the differences in compilation with Nuitka and reports going forward. This kind of report of yours, recognize a change for the worse here, is very valuable and cherished. If you notice another thing like that, great.

**Comment by kayhayen** [comment]
Part of the 1.8 release I just made.

**Comment by tdRPA** [comment]
邮件已收到，通常我在1～2天内回复。如有急事，请直接电话联系 ----我的微信 haijun-data
