### ISSUE TITLE
Generating a static binary

### ISSUE THREAD

**Issue by pedrrcorr** [Nuitka/Nuitka#2365]
Hello,

I want to build a static binary file with all dependencies including libc and ld. When I use --onefile flag, the result is a dynamic linked binary.
My objective is to build a static binary including libc and all other dependencies. 

 I am using nuitka version:
 ```
root@ubuntu:~/secup-uptane/start_servers.build#  python -m nuitka --version
1.7.5
Commercial: None
Python: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Flavor: Debian Python
Executable: /usr/bin/python
OS: Linux
Arch: aarch64
Distribution: Ubuntu (based on Debian) 22.04.2
Version C compiler: /usr/bin/gcc (gcc).
```
I used pip to install nuitka.

The command that i am using is:

> python -m nuitka --onefile filename.py

**Comment by kayhayen** [comment]
You need to use a Python that allows it. Debian Python is not one of them. You will have to compile it yourself in this way or use Nuitka-Python which does this for you: https://github.com/Nuitka/Nuitka-Python

**Comment by actionless** [comment]
which flags should i use to point Nuitka to that local python build,   `--python-for-scons=PATH` and `--static-libpython=yes` ?
