### ISSUE TITLE
Python 3.10: Pattern Matching a sequence doesn't work correctly

### ISSUE THREAD

**Issue by mishamsk** [Nuitka/Nuitka#2368]
See below the minimal reproducible sample that shows the code snippet, expected and actual output.

From what I see it looks like Nuitka doesn't handle sequence patterns properly for some reason, defaulting to the first alternative  (empty sequence) no matter the length of the sequence.

* Please check whether the bug was already reported or fixed.

#1713 seems like a more sophisticated example of this same error. So if it was indeed fixed it may be a regression

* Please check out if the develop version of Nuitka works better for you.

Same error on  Nuitka-1.8rc8 (develop branch as of writing).

* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version

```sh
1.7.1
Commercial: 2.2.0
Python: 3.10.10 (main, Feb 23 2023, 10:42:46) [Clang 14.0.0 (clang-1400.0.29.202)]
Flavor: Unknown
Executable: /Users/path/to/nuitka_tests/.venv/bin/python
OS: Darwin
Arch: arm64
Version C compiler: /opt/homebrew/opt/ccache/libexec/clang (clang).
```

* How did you install Nuitka and Python

pip install (from a local checkout)

* The specific PyPI names and versions

  > python -m pip freeze

```sh
Nuitka @ file:///[redacted]/third-party-repos/nuitka-commercial
ordered-set==4.1.0
zstandard==0.21.0
```

* Many times when you get an error from Nuitka, your setup may be special

Vanilla test python env

* Also supply a Short, Self Contained, Correct, Example

```python
def f(some_l):
    match some_l:
        case []:
            return "Empty list"
        case [v]:
            return f"One element list {v}"
        case _:
            return "More than one element list"


print(f([]))
print(f([1]))
print(f([1, 2]))

# python match_err_minimal.py
# prints:
# Empty list
# One element list 1
# More than one element list

# ./match_err_minimal.dist/match_err_minimal.bin
# prints:
# Empty list
# Empty list
# Empty list
```

* Provide in your issue the Nuitka options used

```sh
python -m nuitka --standalone match_err_minimal.py
```

* Consider getting commercial support

We are on commercial

**Comment by kayhayen** [comment]
Thanks for your support, I will deal with this as soon as possible, this appears to be a terrible bug.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html and I also put it on the staging branch in Nuitka commercial.

Feedback if this is working is very welcome.

**Comment by kayhayen** [comment]
Once my CI is conviced this is not a regression I will put it out as a hotfix release. What happened with matching empty sequences, it was not doing the length check, only if an element was named, that optimization was not permissable as we see. Removing that in our match sequence re-formulation fixes the issue. Generally it seems pretty obvious and non-risky change.

**Comment by mishamsk** [comment]
@kayhayen awesome, thanks a lot. I may give it a try in factory, or you may end tip releasing it quicker

**Comment by kayhayen** [comment]
The staging branch is also available to you, but I will release now indeed. The staging is updated less frequently, but mostly always if a commercial user has an issue fixed. I try to have staging less breaking, so it's more like a "develop" version of Nuitka which could still be used, but probably will be not the conservative choice.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.7.9 that I just made.

**Comment by mishamsk** [comment]
@kayhayen thanks. also can confirm on my side + we've upgraded to 1.7.9 commercial the core project as well
