### ISSUE TITLE
Nuitka fails to run with the error AttributeError: 'FileFinder' object has no attribute 'find_module'

### ISSUE THREAD

**Issue by NotADinosaur** [Nuitka/Nuitka#2369]
Before submitting an Issue, please review the [Issue Guidelines](https://github.com/Nuitka/Nuitka/blob/develop/CONTRIBUTING.md#submitting-an-issue).  
✔

* Please check whether the bug was already reported or fixed.

I checked and couldn't find another issue that is the same as this one
* Please check out if the develop version of Nuitka works better for you.

The issue occurs on 1.7.7, 1.7.8, and 1.8rc8.

* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version

```
C:\Users\myname>python -m nuitka --version
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\nuitka\__main__.py", line 155, in <module>
    main()
  File "C:\Program Files\Python311\Lib\site-packages\nuitka\__main__.py", line 109, in main
    Options.parseArgs()
  File "C:\Program Files\Python311\Lib\site-packages\nuitka\Options.py", line 277, in parseArgs
    is_nuitka_run, options, positional_args, extra_args = parseOptions(
                                                          ^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\nuitka\OptionParsing.py", line 1868, in parseOptions
    _considerPluginOptions(logger)
  File "C:\Program Files\Python311\Lib\site-packages\nuitka\OptionParsing.py", line 1647, in _considerPluginOptions
    addStandardPluginCommandLineOptions(parser=parser)
  File "C:\Program Files\Python311\Lib\site-packages\nuitka\plugins\Plugins.py", line 1519, in addStandardPluginCommandLineOptions
    loadPlugins()
  File "C:\Program Files\Python311\Lib\site-packages\nuitka\plugins\Plugins.py", line 1515, in loadPlugins
    loadStandardPluginClasses()
  File "C:\Program Files\Python311\Lib\site-packages\nuitka\plugins\Plugins.py", line 382, in loadStandardPluginClasses
    _loadPluginClassesFromPackage(nuitka.plugins.standard)
  File "C:\Program Files\Python311\Lib\site-packages\nuitka\plugins\Plugins.py", line 298, in _loadPluginClassesFromPackage
    module_loader = item.module_finder.find_module(item.name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FileFinder' object has no attribute 'find_module'
```

* How did you install Nuitka and Python

I installed nuitka via `python -m pip install nuitka`

* Many times when you get an error from Nuitka, your setup may be special

  When even a `print("hello world")` program will not work, please try that and
  report that error instead. We do not need a report that says "Tensorflow does
  not work" when nothing actually works for you. You ought to also read the User
  Manual and check that your setup is actually supported already.

Attempting to run `python -m nuitka hello.py`  (where hello.py contains the code `print("hello!"`) as in the user manual's exapmle produces the exact same error as `python -m nuitka --version`. I am fairly sure that my setup (windows 10, python 3.11.4, visual studio 2022 build tools) is supported.

**Comment by kayhayen** [comment]
I update my 3.11 to the same hotfix level as yours, just to see it. Nuitka calls effectively `pkgutil.iter_modules("[nuitka/plugins/standard"]) and for me that indeed gives this

```
>>> list(pkgutil.iter_modules(["nuitka/plugins/standard"]))[0].module_finder.find_module
<bound method _find_module_shim of FileFinder('C:\\Users\\kayha\\repos\\Py2C\\nuitka/plugins/standard')> 
```

I assume for you it would not work?

**Comment by kayhayen** [comment]
I think a Python3.12 might behave like that. Considering this comment we have work to do here:

```
    _warnings.warn("find_module() is deprecated and "
                   "slated for removal in Python 3.12; use find_spec() instead",
                   DeprecationWarning)
```

**Comment by NotADinosaur** [comment]
Strange, I’m fairly sure I was not using 3.12 as I don’t use beta versions of things if I can help it but reinstalling python has fixed the issue, thanks.

**Comment by kayhayen** [comment]
I have not found another reason why it could be happening, and of course these things happen. Now if `nuitka --version` would have worked at all, it would have been able to tell us that... which in the future it will. But nevermind, recognizing that 3.12 has those changes needed was pretty helpful still.

**Comment by n-bes** [comment]
Reproduced with version 1.6.5, passed with version 2.3
