### ISSUE TITLE
Alpine Linux / armhf problems, and fixes

### ISSUE THREAD

**Issue by puresilk** [Nuitka/Nuitka#237]
Hi, 
I have added some patches to make nuitka work on Alpine Linux armhf for --standalone mode.
I've written a blogpost about it, explaing the problems and my patches, which is here:
[https://pi3g.com/2019/01/31/using-nuitka-compiler-for-python3-on-alpine-linux-armhf-musl/](https://pi3g.com/2019/01/31/using-nuitka-compiler-for-python3-on-alpine-linux-armhf-musl/)

I'm attaching the patched files. Hope this helps! 
Max

[nuitka_patches.zip](https://github.com/Nuitka/Nuitka/files/2818485/nuitka_patches.zip)

**Comment by puresilk** [comment]
Hi Kay,

glad you find it useful :-), yes - comment on this issue and I will try the next pre-release. I tried to keep my patch generic, so it would work on non armhf systems too, but have not tested it.

Max

**Comment by kayhayen** [comment]
Please try this out, http://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
I have done your patches slightly different. I think `ldd` means that nothing needs to be done, just like with `not found`. Also the scan of the file system is named differently and I attempted a cached function to determine if it is Alpine, that hopefully works.

**Comment by kayhayen** [comment]
But I am optimistic this should work. If not, let me know, so we can tweak it further.

**Comment by puresilk** [comment]
Hi Kay,
I've tested to build with the factory version today - no errors, and the executable works. Seems to be OK!

All the libraries are there as I would expect them to be:

![image](https://user-images.githubusercontent.com/4606111/52163706-3f6dba00-26e6-11e9-8e2e-839cf0069fe3.png)

I will need to package it and test it on an environment without the python3-dev package being installed - might take me some time, as I have to work on another urgent project. Will report back here how it works.

Thank you for accepting the patch suggestion, in the name of all Alpine users!

Max

**Comment by jeritiana** [comment]
Hello guys,

I stumbled upon these errors too and I tested on Docker-based Alpine Linux x86_64: it works well on the develop branch now (V0.6.2rc5 - bc22aa8).

Test information, if needed:

* In a container created from the official Docker `alpine:3.9` image, I installed Build base, Python 2.7.15-r3 and other dependencies: `nuitka --standalone --python-flag=no_site --python-flag=no_warnings --show-progress prog.py` succeeds.
  `prog.py` imports various modules, such as Cryptography, Paramiko and stuff
* And then, with the same image, in another container, without the dependencies: `/prog.dist/prog` works well.

Thank you, waiting for the official release now!

Jeritiana

**Comment by puresilk** [comment]
Hi,

**from my side I can also report now that it seems to work! :-)**
I'm deploying on Alpine without Python, armhf / Raspberry Pi as target. Tested with both ARMv6 and ARMv7 Pi's.
 
Hint to packagers: libpython will still need to be installed into /usr/lib/.. by your package, otherwise the package will automatically depend on python and pull it during installation. If you install libpython, the package will probably conflict with python (as both provide the libpython).  For me currently this is not an issue, as I deploy without python. 

Max

**Comment by puresilk** [comment]
I am therefore closing the issue - hope this is OK with you, Kay?

**Comment by j8r** [comment]
On my side I still got this issue:
```py
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/nuitka/__main__.py", line 184, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/nuitka/__main__.py", line 177, in main
    MainControl.main()
  File "/usr/lib/python3.6/site-packages/nuitka/MainControl.py", line 781, in main
    Plugins.considerExtraDlls(dist_dir, module)
  File "/usr/lib/python3.6/site-packages/nuitka/plugins/Plugins.py", line 110, in considerExtraDlls
    for extra_dll in plugin.considerExtraDlls(dist_dir, module):
  File "/usr/lib/python3.6/site-packages/nuitka/plugins/standard/ImplicitImports.py", line 476, in considerExtraDlls
    uuid_dll_path = locateDLL("uuid")
  File "/usr/lib/python3.6/site-packages/nuitka/utils/SharedLibraries.py", line 45, in locateDLL
    if os.path.sep in dll_name:
TypeError: argument of type 'NoneType' is not iterable
```

Step to reproduce with Docker:
```sh
docker run --rm alpine sh -c '
  apk add --update musl-dev gcc python3-dev py3-pip
  pip3 install nuitka==0.6.2
  echo "print(\"Hi\")" > a.py
  nuitka3 --show-progress --standalone a.py
'
```

**Comment by anki-code** [comment]
Hello @kayhayen ! Thank you for nuitka!
Could you please advice what is the best way to use Nuitka to make standalone binary with portable musl?
Here is the example:
```
docker run --rm -it alpine sh
apk add --update musl-dev gcc python3-dev py3-pip chrpath git
pip install -U "https://github.com/Nuitka/Nuitka/archive/factory.zip"
git clone https://github.com/xxh/xxh
cd xxh
nuitka3 --python-flag=no_site --python-flag=no_warnings --show-progress --standalone --follow-imports xxh
```
After it I have `xxh.dist` with `ldd xxh`
```
        /lib/ld-musl-x86_64.so.1 (0x7f58f86fb000)
        libpython3.8.so.1.0 => ./libpython3.8.so.1.0 (0x7f58f7a96000)
        libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f58f86fb000)
```
Then I move it to Ubuntu and I've got `ldd xxh`:
```
        linux-vdso.so.1 (0x00007ffeeedd9000)
        libpython3.8.so.1.0 => /home/pc/xxh/xxh/xxh.dist/./libpython3.8.so.1.0 (0x00007efd2813c000)
        libc.musl-x86_64.so.1 => not found
        libc.musl-x86_64.so.1 => not found
```
When I copy `libc.musl-x86_64.so.1` from Alpine to `xxh.dist` I've got `ldd xxh` *on Ubuntu*:
```
        linux-vdso.so.1 (0x00007ffce37ac000)
        libpython3.8.so.1.0 => /home/pc/xxh/xxh/xxh.dist/./libpython3.8.so.1.0 (0x00007fbbf0df5000)
        libc.musl-x86_64.so.1 => /home/pc/xxh/xxh/xxh.dist/./libc.musl-x86_64.so.1 (0x00007fbbf0d5f000)
```
Looks good, but not working:
```
ubuntu$ ./xxh
bash: ./xxh: No such file or directory
```
And only if I copy `musl` to `/lib` on Ubuntu I have success:
```
$ sudo cp libc.musl-x86_64.so.1 /lib/ld-musl-x86_64.so.1
$ ./xxh -V
0.6.0
```
1. Please advice what I can do to make musl portable with the app?
2. Is there a way to statically compile musl inside the app?

Many thanks to your work!
