### ISSUE TITLE
Q: FATAL: Automatic detection of static libpython failed. but I'm not using conda, so which package should I install via `pip`?

### ISSUE THREAD

**Issue by joortcom** [Nuitka/Nuitka#2373]
I got this error message:

```
FATAL: Automatic detection of static libpython failed. Nuitka on Anaconda needs package for static libpython installed. Execute 'conda install libpython-static'.
```

but I'm not using conda, so which package should I install via `pip`?

Thanks.

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
