### ISSUE TITLE
Tokenizer requires the SentencePiece library but it was not found in yo_sentencepiece_objects.py", line 93, in __init__ur environment. Checkout the instructions on the           

### ISSUE THREAD

**Issue by ArEnSc** [Nuitka/Nuitka#2378]
When using:
nuitka 1.7.9
transformers==4.29.2
This works perfectly fine, it is able to find the sentence piece library and tokenizer and tokenize.

When using 
nuitka 1.7.9
transformers==4.31.0

LlamaTokenizer requires the SentencePiece library but it was not found in yo_sentencepiece_objects.py", line 93, in __init__ur environment. Checkout the instructions on the                            t_utils.py", line 1027, in requires_backends
installation page of its repo: https://github.com/google/sentencepiece#installation and follow the ones                                                 ur environment. Checkout the instructions on the
that match your environment. Please note that you may need to restart your rllation and follow the onesuntime after installation.      

Here is an example 

```python
from transformers import LlamaTokenizer

import logging

logging.basicConfig(
    format="%(asctime)s %(levelname)s [%(name)s] %(message)s", level=logging.INFO, datefmt="%Y-%m-%d %H:%M:%S"
)

vocab_file = r"C:\Users\Tensor\Desktop\TestSentencePieceHF\Pygmalion-7b\tokenizer.model"
tokenizer_file = r"C:\Users\Tensor\Desktop\TestSentencePieceHF\Pygmalion-7b\tokenizer.json"

tokenizer = LlamaTokenizer(vocab_file=vocab_file,tokenizer_file=tokenizer_file,use_fast=True)

examples = [
    tokenizer(
        "auto-gptq is an easy-to-use model quantization library with user-friendly apis, based on GPTQ algorithm."
    )
]
print(tokenizer("auto_gptq is", return_tensors="pt"))
```

This is the model files to be loaded
C:\Users\Tensor\Desktop\TestSentencePiece\Pygmalion-7b-4bit-GPTQ-Safetensors
https://drive.google.com/file/d/10ZD89g7BVpjbmnkrzIEirxvNzoLwdxOX/view?usp=sharing

**Comment by ArEnSc** [comment]
[report.txt](https://github.com/Nuitka/Nuitka/files/12304726/report.txt)
This is the report

**Comment by ArEnSc** [comment]
@kayhayen for visibility thanks!

**Comment by kayhayen** [comment]
@ArEnSc I am fallen a bit behind on this one, because the new CI machine arrived, and I would like to do the VM for testing these kinds of things there, please allow for a bit more time

**Comment by ArEnSc** [comment]
> @ArEnSc I am fallen a bit behind on this one, because the new CI machine arrived, and I would like to do the VM for testing these kinds of things there, please allow for a bit more time

Absolutely! just surfacing these things so it doesn't get lost :) thank you again!

**Comment by Quicksticks-oss** [comment]
I get the same thing!

**Comment by kayhayen** [comment]
Torch models are absolutely unsafe for me to use. I will run this in a sandboxed environment, because this a commercially backed report. I want to get away from having VMs for this, but use `run-inside-nuitka-container` in a safer way.

**Comment by kayhayen** [comment]
So, I finally managed to setup a safe container environment, to do these things. I reproduced it with it, and I feel it's one of these bug hiding messages that package makers do, so the pityful enduser must never know what the problem is, if it's not the stated one.

**Comment by kayhayen** [comment]
So, transformers has a bunch of meta data dependencies we do not yet list, so `--include-distribution-metadata` can likely solve this, but I am doing two things for this. First, in case of missing metadata, it's going to give an error that suggests the options. And second, I am going to add a bunch of these from the source, but it's likely a moving target, but I don't want code to extract these.

**Comment by KayembaLuwaga** [comment]
Use:
```
!pip install transformers[sentencepiece]
!pip install sentencepiece
```

Make sure to restart your runtime before running again

**Comment by kayhayen** [comment]
I am retrying this after the many changes done for 2.0 there is good changes this now works better.

**Comment by KevinRodriguez777** [comment]
can you retry this?
i simply get 
```
Traceback (most recent call last):
  File "C:\Users\Divine\Desktop\PyDis\MAIN~1.DIS\main.py", line 1, in <module>
ModuleNotFoundError: No module named 'transformers'
```

**Comment by kayhayen** [comment]
@KevinRodriguez777 that would be the one you get when transformers is not installed

**Comment by kayhayen** [comment]
I actually expect this issue to work, but I am waiting for my Azure power VM to run these sort of things, should be happening this week or so I hope.

**Comment by KevinRodriguez777** [comment]
> @KevinRodriguez777 that would be the one you get when transformers is not installed

```
❯ pip list
Package            Version
------------------ ----------
certifi            2024.2.2
charset-normalizer 3.3.2
colorama           0.4.6
filelock           3.13.1
fsspec             2024.3.1
huggingface-hub    0.21.4
idna               3.6
Jinja2             3.1.3
MarkupSafe         2.1.5
mpmath             1.3.0
networkx           3.2.1
Nuitka             2.1.3
numpy              1.26.4
ordered-set        4.1.0
packaging          24.0
pip                24.0
protobuf           5.26.0
PyYAML             6.0.1
regex              2023.12.25
requests           2.31.0
safetensors        0.4.2
sentencepiece      0.2.0
setuptools         69.2.0
sympy              1.12
tokenizers         0.15.2
torch              2.2.1
tqdm               4.66.2
transformers       4.39.1
typing_extensions  4.10.0
urllib3            2.2.1
zstandard          0.22.0
```

it is installed of course, let me try it again from scratch, maybe an enviroment issue.

**Comment by KevinRodriguez777** [comment]
it turned out to be an enviroment issue, anyways, this works nowadays on the latest version.

**Comment by kayhayen** [comment]
Pretty sure that happened for 2.1
