### ISSUE TITLE
Can nuitka build package with script arguments?

### ISSUE THREAD

**Issue by lytofd** [Nuitka/Nuitka#2379]
l could use command below to build my package.

```
python -m nuitka --nofollow-imports sub_dir/entrypoint.py  --include-plugin-files=subdir/* --output-filename=./binary_run_file 
```

entrypoint.py use argparse to parse arguments, so l could run binary file as below

```
./binary_run_file --argument1=1  --argument2=2
```

But l do not want other know my arguments,   so , could l integrate arguments into nuitka build progress? such as :
```
./binary_run_file
```
Thanks.

**Comment by kayhayen** [comment]
You can set `sys.argv` the way you like it in your Python code. Nuitka will not behave different from standard Python with respect to command line arguments, but if you want only the compiled version to do that, check out the user manual for how to determine if your code is compiled or not.
