### ISSUE TITLE
multiprocessing failed

### ISSUE THREAD

**Issue by zhaohe36** [Nuitka/Nuitka#2381]
![QQ截图20230811140212](https://github.com/Nuitka/Nuitka/assets/28671938/253ec9b5-ff2c-4547-93b8-edb6b01d1a39)
![QQ截图20230811140358](https://github.com/Nuitka/Nuitka/assets/28671938/2ad71478-c841-4a32-829a-e5a693c52608)

**Comment by zhaohe36** [comment]
![QQ截图20230811140653](https://github.com/Nuitka/Nuitka/assets/28671938/efd909ee-a588-41b8-af7d-ca2fa80f7117)

**Comment by zhaohe36** [comment]
cant find the attribute

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
