### ISSUE TITLE
Add support for pyx files

### ISSUE THREAD

**Issue by gjmhmm8** [Nuitka/Nuitka#2390]
I would like to request a feature that allows nuitka to compile pyx files directly. pyx files are Cython source files that can contain Python code and Cython extension code, such as C types, variables, functions, classes, etc. defined with cdef or cpdef¹. Currently, nuitka can compile Cython generated extension modules, but it requires some options and parameters to be specified³. It would be more convenient and efficient if nuitka could handle pyx files without the need to convert them to C or Python files first.

I expect nuitka to be able to compile pyx files with a simple command, such as:

```bash
nuitka --standalone testmodel.pyx
```

This should generate an executable file or an extension module from the pyx file, without any errors or warnings. The compiled code should have the same functionality and performance as the original pyx code.

When I try to compile a pyx file with nuitka, I get the following error:

nuitka --module testmodel.pyx
Nuitka-Options:INFO: Used command line options: --module testmodel.pyx
Nuitka-Options:WARNING: You did not specify to follow or include anything but main module. Check options and make sure
Nuitka-Options:WARNING: that is intended.
Nuitka:INFO: Starting Python compilation with Nuitka '1.7.9' on Python '3.9' commercial grade 'not installed'.
testmodel
Traceback (most recent call last):
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\__main__.py", line 155, in <module>
    main()
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\__main__.py", line 141, in main
    MainControl.main()
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\MainControl.py", line 1109, in main
    _main()
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\MainControl.py", line 969, in _main
    main_module = _createMainModule()
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\MainControl.py", line 159, in _createMainModule
    main_module = buildMainModuleTree(
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\tree\Building.py", line 1138, in buildMainModuleTree
    module, _added = buildModule(
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\tree\Building.py", line 1241, in buildModule
    ) = Importing.decideModuleSourceRef(
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\importing\Importing.py", line 802, in decideModuleSourceRef
    assert type(module_name) is ModuleName, module_name
AssertionError: testmodel

- Nuitka version: 1.7.9
- Python version: 3.9
- Platform: Windows 11

**Comment by kayhayen** [comment]
Nuitka is Python compatible, not Cython compatible, since that is not Python language. If it is indeed Python code, rename it to `.py` and make sure it's executable with Python.

That said, the error given in unacceptable indeed, seems like that code path is not really tested.

**Comment by kayhayen** [comment]
It seems, it is not trigger by filename, but by content, I would need to file in question I guess.

**Comment by kayhayen** [comment]
```
python3.10 bin/nuitka --module Mini.pyx
Nuitka-Options:INFO: Used command line options: --module Mini.pyx
Nuitka-Options:WARNING: You did not specify to follow or include anything but main module. Check options and  
Nuitka-Options:WARNING: make sure that is intended.
Nuitka:INFO: Starting Python compilation with Nuitka '1.8rc' on Python '3.10' commercial grade '2.2.3'.
FATAL: Error, filename 'Mini.pyx' suffix does not appear to be Python module code.
```

So that is better behaved. In non module-module, Nuitka has no opinion of the filename, but in module mode, it needs to derive the name of the module from the filename, and without knowing the suffix, that's not happening.

**Comment by kayhayen** [comment]
As for becoming the tool to build standalone with Cython transparently, we lack the resources to do that. I am sure if can be done with being like setuptools to Cython, but I honestly don't care enough to consider it a valid use case. Nuitka has nothing to contribute there and cannot do its commercial IP protection magic either, so there is not a business case for that as well.
