### ISSUE TITLE
compile with mmcv and model, but  `no moulde named mmcv._ext` appears

### ISSUE THREAD

**Issue by Calsia** [Nuitka/Nuitka#2391]
<img width="562" alt="image" src="https://github.com/Nuitka/Nuitka/assets/13194457/2ca82671-7b77-491a-ab2a-22b3c4343199">

I would like to package a mmdetection project to exe. but when I run the exe, the `no moulde named mmcv._ext` appears.

I have tried with python of version 38-310, nuitka of version (1.7.9, 0.6.8.4, factory), 
my command is 'nuitka --standalone(also tested --onefile) --mingw64 --show-progress --output-dir=exe mesh_ortho_main.py'.
however, all results turn to the same error. 

I guess, maybe the pkg of nuitka Cann't match the third ext*pyd?, but I don't know whether it's right, and how to fix it? 
I also guess `-user-package-configuration-file` may be useful? but I don't know what is this param really meaning, and how the `yaml` looks like?

any response  is helpful ,thanks you overmuch.

**Comment by Calsia** [comment]
by the way, the version of my torch is 1.10(1.12), mmcv ==1.7.1

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
