### ISSUE TITLE
Cannot read resource files using stdlib's `importlib.resources.files()` using `--standalone` mode

### ISSUE THREAD

**Issue by jhbuhrman** [Nuitka/Nuitka#2393]
### Versions
```
> python -m nuitka --version
1.7.10
Commercial: None
Python: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: D:\workspace\projects\nuitka-problem\.venv310\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\Hostx64\x64\cl.exe (cl 14.3).
```
### Installation info
```
> where python
D:\dev\Python310\python.exe
....
```
#### Virtual environment
Created with
```
python -m venv .venv310
```
Activated with
```
> .venv310\Scripts\activate
> where python
D:\workspace\projects\nuitka-problem\.venv310\Scripts\python.exe
D:\dev\Python310\python.exe
...
```
#### Installed packages
```
> python -m pip install -U pip
...
> python -m pip install Nuitka
...
> python -m pip freeze
Nuitka==1.7.10
ordered-set==4.1.0
zstandard==0.21.0
```
#### `> type implib_resources_problem\main.py`
```python
import some_package.handle_resources

def main():
    some_package.handle_resources.doit()

if __name__ == "__main__":
    main()
```
#### `> type implib_resources_problem\some_package\__init__.py`
```python
```
#### `> type implib_resources_problem\some_package\handle_resources.py`
```python
import importlib.resources


some_resources = importlib.resources.files("some_package.some_resources")

def doit():
    for number, some_resource in enumerate(some_resources.iterdir(), start=1):
        print(f"resource #{number} ({some_resource!r}):")
        print(some_resource.open("r").read())
```
#### `> type implib_resources_problem\some_package\some_resources\file_A.txt`
```
Some resource file A
```
#### `> type implib_resources_problem\some_package\some_resources\file_B.txt`
```
Some resource file B
```
### Output using plain Python
```
> cd implib_resources_problem
> python -m main
resource #1 (WindowsPath('D:/workspace/projects/nuitka-problem/implib_resources_problem/some_package/some_resources/file_A.txt')):
Some resource file A

resource #2 (WindowsPath('D:/workspace/projects/nuitka-problem/implib_resources_problem/some_package/some_resources/file_B.txt')):
Some resource file B

```
### Nuitka build command
```
> python -m nuitka --standalone --include-package-data=some_package main.py
Nuitka-Options:INFO: Used command line options: --standalone --include-package-data=some_package main.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.7.10' on Python '3.10' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl 14.3).
Nuitka-Scons:INFO: Backend linking program with 9 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 9 C files using clcache with 9 cache hits and 0 cache misses.
Nuitka-Options:INFO: Included data file 'some_package\some_resources\file_A.txt' due to package 'some_package' package data.
Nuitka-Options:INFO: Included data file 'some_package\some_resources\file_B.txt' due to package 'some_package' package data.
Nuitka:INFO: Keeping build directory 'main.build'.
Nuitka:INFO: Successfully created 'main.dist\main.exe'.
```
### Actual output using Nuitka-built version
```
> main.dist\main.exe
resource #1 (<nuitka_resource_reader_files for package 'some_package.some_resources' file '\\file_A.txt'>):
Traceback (most recent call last):
  File "D:\workspace\projects\nuitka-problem\implib_resources_problem\main.dist\main.py", line 9, in <module>
  File "D:\workspace\projects\nuitka-problem\implib_resources_problem\main.dist\main.py", line 5, in main
  File "D:\workspace\projects\nuitka-problem\implib_resources_problem\main.dist\some_package\handle_resources.py", line 9, in doit
FileNotFoundError: [Errno 2] No such file or directory: '\\file_A.txt'
```
#### Additional info:
```
> dir /B D:\workspace\projects\nuitka-problem\implib_resources_problem\main.dist\some_package\some_resources
file_A.txt
file_B.txt
```
For your convenience, the listed source (and resource) files are also provided in attached zip.

[implib_resources_problem.zip](https://github.com/Nuitka/Nuitka/files/12369319/implib_resources_problem.zip)

**Comment by kayhayen** [comment]
Recently I added support for `importlib_resources` that is currently on develop (but only since shortly), and it appears this has also fixed the issue, not sure how, but I think I saw similar things there. I believe `chromadb` was excercising more of the API of Nuitka's reader, and I even had an implementation error in one function, so maybe that's why it's better now.

**Comment by kayhayen** [comment]
Thanks for the excellent report, I was not aware of the scope of my changes there. The 1.8 is due for release in the coming days anyway, this seems important.

**Comment by jhbuhrman** [comment]
> Thanks for the excellent report, I was not aware of the scope of my changes there. The 1.8 is due for release in the coming days anyway, this seems important.

You're welcome! 😄 

Actually the example is a stripped down version of what the _Pyphen_ package is doing. There is another problem with _Pyphen_, for which I have created an issue on their repo (https://github.com/Kozea/Pyphen/issues/54). I will backreference this issue from there...

**Comment by kayhayen** [comment]
If you have any such reproducer, share it with me, no problem. Not being compatible enough is foremost Nuitka's problem and should be solved in it.

**Comment by jhbuhrman** [comment]
Sure, I can do that.

Is it sufficient to provide the set of source files only in a Zip file (and not displaying all the files separately), saves me some work? For the rest I will of course provide the Version, Installation Info, Installed packages, etc. as I did for this very issue.

**Comment by kayhayen** [comment]
I cannot execute foreign code of any reasable size for free. I have been attacked a bunch of time already, and therefore the cost of this, would have to be covered by a subscription of Nuitka already. A minimal example is really required therefore.

**Comment by jhbuhrman** [comment]
A small misunderstanding here, I guess. The example will be as small as this one, but instead of displaying the contents of each file, I would like to provide the 4 files or so in a `.zip`. Is that OK`?

**Comment by kayhayen** [comment]
That will earn you the `excellent_report` tag. I guess I need to make it clear in the template that this kind of zip is in fact very welcome, some people even create small github repos for their reports, even better, but definitely not required. You are welcome. :-)

**Comment by jhbuhrman** [comment]
I've created https://github.com/Nuitka/Nuitka/issues/2400.

**Comment by kayhayen** [comment]
Thanks for pointing these out, probably very significant amounts of packages indirectly affected. Will be good in 1.8 now.

**Comment by kayhayen** [comment]
Part of the 1.8 release I just made.
