### ISSUE TITLE
compiled program remains open in taskmanager after closing.

### ISSUE THREAD

**Issue by jdauthre** [Nuitka/Nuitka#2395]
Nuika version 0.6.17.7
Python: 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
OS: Windows
Arch: x86_64

python -m   nuitka    --include-data-file=werks9.ico=werks9.ico --include-data-file=recording.ico=recording.ico   --standalone --windows-icon-from-ico=werks9.ico  --windows-disable-console --windows-file-description=IPTVPlyer --plugin-enable=multiprocessing  --windows-company-name=VideoWerks --windows-file-version=1.1.0.0 streamerbackend.py

after compiling using standalone mode  all works well but on closing the app  it remains open in task manager under Background Processes, so with multiple openings they just multiply. Also possibly related, if I compile using --onefile  I get an error the .ico files are not found and the temp file in AppData  is not deleted. As far as I can see there is nothing in the code that I haven't used in previous apps, except I have imported the GUI from a separate py file.
Thanks in Advance

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
