### ISSUE TITLE
Feature: A similar -y option for download tools & dependency

### ISSUE THREAD

**Issue by LorenEteval** [Nuitka/Nuitka#2396]
Hi! Just wondering if it's possible for nuitka to add a similar `-y, --yes` option that it just downloads the required tools & dependency(for example, dependency walkers, specific version of gcc, etc.) whenever it needs, just like kind of `sudo apt install -y ...` . It will then be possible to add nuitka build as part of a CI step in various projects which requires full automacy. Thank you.

**Comment by kamgha** [comment]
This already exists: Try `--assume-yes-for-downloads`
https://github.com/Nuitka/Nuitka/blob/f21165c74f81296da61cf4bfa268213a9f5f1c17/nuitka/OptionParsing.py#L510-L519

**Comment by LorenEteval** [comment]
It works, thanks! I'll close this issue.

**Comment by kayhayen** [comment]
@kamgha thanks for being around
