### ISSUE TITLE
Need to add package configuration for opencc package

### ISSUE THREAD

**Issue by AlphaLiu** [Nuitka/Nuitka#2403]
Hi,

In Nuitka 1.7.10, I used the `--include-data-dir` flag to copy the OpenCC directory to the dist directory. However, it only copied a portion of the files and directories, not the entire OpenCC directory. I tested this with other versions of Nuitka, including 1.8.0rc10, which had the same issue as 1.7.10. However, Nuitka 1.3.7 was able to copy the entire OpenCC folder to the dist directory, which is what I expected.

* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.
  > python -m nuitka --version                                                                                                          
1.7.10
Commercial: None
Python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: I:\MySync\Temp\my-projects\nuitka_test\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\cl.exe (cl 14.3).

* Provide in your issue the Nuitka options used
```sh
python -m nuitka --standalone --include-data-dir=.venv\\Lib\\site-packages\\opencc=opencc --output-dir=./build my_test.py
```

There was one line log different from 1.7.10/1.8.0rc10 to 1.3.7

1.7.10 / 1.8.0rc10
```
Nuitka-Options:INFO: Included 55 data files due to specified data dir '.venv\Lib\site-packages\opencc' on command line.
```

1.3.7
```
Nuitka-Options:INFO: Included 60 data files due to specified data dir '.venv\Lib\site-packages\opencc' on command line
```

Here is the structure of my OpenCC folder. As you can see, the `bin` directory was not copied to the `dist` directory in versions 1.7.10 and 1.8.0rc10.

opencc in site-packages
```
.VENV\LIB\SITE-PACKAGES\OPENCC
├─clib
│  ├─bin
│  ├─include
│  │  └─opencc
│  └─share
│      └─opencc
└─__pycache__
```

opencc in build-dist by nuitka 1.7.10/1.8.0rc10
```
BUILDV2\MY_TEST.DIST\OPENCC
└─clib
    ├─include
    │  └─opencc
    └─share
        └─opencc
```

opencc in build-dist by nuitka 1.3.7
```
BUILDV3\MY_TEST.DIST\OPENCC
├─clib
│  ├─bin
│  ├─include
│  │  └─opencc
│  └─share
│      └─opencc
└─__pycache__
```

Thank you for helping.

**Comment by kayhayen** [comment]
Nuitka ignores code in data files options by default since a few releases. The `__pycache__` folder is e.g. ignored entirely, which is good. The data files for opencc do not contain a `bin` folder for me when I look at them with `python3.10 -m nuitka --list-package-data=opencc`  because that file there is a DLL.

The solution would be to add a data directory config and a DLL config both for the module.

If you are available to do a PR, this can be fixed by adding to the yaml configuration, described here: [https://nuitka.net/doc/nuitka-package-config.html](https://nuitka.net/doc/nuitka-package-config.html)

And here is more of a walk through style post: [https://nuitka.net/posts/nuitka-package-config-kickoff.html](https://nuitka.net/posts/nuitka-package-config-kickoff.html)

Here are a example PRs for other packages:

[#2030](https://github.com/Nuitka/Nuitka/pull/2030) 
[#1993](https://github.com/Nuitka/Nuitka/pull/1993)

**Comment by kayhayen** [comment]
Including DLLs is currently only supported via Yaml. DLLs are not data files and have to be specified separately.

**Comment by AlphaLiu** [comment]
Thank you! I will have a try.

**Comment by AlphaLiu** [comment]
It works, the yaml file:
```yml
- module-name: 'opencc'
  data-files:
    dirs:
      - 'clib/share/opencc'
    patterns:
      - '*.json'
      - '*.ocd2'

  dlls:
    - from_filenames:
        relative_path: 'clib/bin'
        prefixes:
          - 'opencc'
      when: 'win32'
```

**Comment by kayhayen** [comment]
I am getting this one, which is a programming mistake of theirs:

```
Exception ignored in: <compiled_function OpenCC.__del__ at 0x000001A46897D7B0>
Traceback (most recent call last):
  File "C:\Users\kayha\repos\Py2C\MINIOP~1.DIS\opencc\__init__.py", line 99, in __del__
AttributeError: 'NoneType' object has no attribute 'opencc_close'
```

They are using a global variable while objects are deleted during shutdown, but I am not sure, if Nuitka should ignore those silently during shutdown at least.

**Comment by kayhayen** [comment]
I checked Linux and it works, macOS doesn't seem to work at all, at least not with "pip install opencc" alone, I am guessing they do not support that OS, or so they, I think it installed a 0.2 and they probably only later added their non-support or something like that.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
Part of the 1.8 release I just made. Thanks for producing the config, very helpful.
