### ISSUE TITLE
More detailed documentation on compiling packages?

### ISSUE THREAD

**Issue by randomwalker42** [Nuitka/Nuitka#2406]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

```
1.7.10
Commercial: None
Python: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Flavor: Debian Python
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.2
Version C compiler: /usr/bin/gcc (gcc).
```

* How did you install Nuitka and Python

I used google colab as test enviroments, nuitka was installed with pip `!pip install nuitka` without a virtualenv.

* Also supply a Short, Self Contained, Correct, Example

I need to distribute a python library that I maintained for others to use, and I want to use Nuitka to compile this package in order to get some degree of encryption (I do not want others to see the source code).  So I created an example module to test. This module is very simple structure as follows:

```
mymodule
└── funcs
    ├── __init__.py
    └── load.py
```

with load.py as 

```
def print_consts():
    print(1, 2, 3)
```

I followed Use Case 3 - Package compilation, and succeesfully executed the following commands:

`!python -m nuitka --debug --module mymodule --include-package=mymodule`, which outputs:

```
Nuitka-Options:INFO: Used command line options: --debug --module mymodule --include-package=mymodule
Nuitka:INFO: Starting Python compilation with Nuitka '1.7.10' on Python '3.10' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 8 files (no progress information available for this stage).
Nuitka-Scons:WARNING: You are not using ccache, re-compilation of identical code will be slower than necessary. Use your OS package manager to install it.
Nuitka:INFO: Keeping build directory 'mymodule.build'.
Nuitka:INFO: Successfully created 'mymodule.cpython-310-x86_64-linux-gnu.so'.
```

I renamed the so files as `!mv mymodule.cpython-310-x86_64-linux-gnu.so mymodule_new.so` and then failed to import it:

```
ImportError                               Traceback (most recent call last)
[<ipython-input-14-11b9f18f8646>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import mymodule_new

ImportError: dynamic module does not define module export function (PyInit_mymodule_new)
```

It seems that some extra steps need to be done, but I can not find more details in the official documents. It would be great if anyone could provide more guidelines on this. 

BTW, is it recommended to use Nuitka for my purpose (encrypting python source code)? I'm expecting one could import the .so file just as one would normally import the python module, or maybe I misunderstand how Nuitka works?

**Comment by kayhayen** [comment]
Renaming the module is not expected to work at all, rendering it invalid. Python enforces module name and filename of extension odules to align.

Module mode exposes your Python API, but of course not the source code. In Nuitka commercial we have some advice if this is what you need to do, to protect it somehwat from low skill attacks.

**Comment by kayhayen** [comment]
I will agree that the user manual can state it better though, I am adding these. I bet my lazy self not clarifying what happens if names are the same, drove you to rename it. You need to move to another folder and have it in sys.path before the source or instead of it.

```
.. important::

   The filename of the produced extension module must not be changed as
   Python insists on a module name derived function as an entry point,
   in this case ``PyInit_some_module`` and renaming the file will not
   change that. Match the filename of the source code what the binary
   name should be.

.. note::

   If both the extension module and the source code of it are in the
   same directory, the extension module is loaded. Changes to the source
   code only have effect once you recompile.
```
