### ISSUE TITLE
libopenblas.dll not getting included when SciPy is version 1.11.2

### ISSUE THREAD

**Issue by SebastianWeis** [Nuitka/Nuitka#2411]
After updating SciPy to version 1.11.2 i get the following message when trying to call functions from the scipy.linalg package:

```
Traceback (most recent call last):
  File "C:\_dev\ERROR~1.DIS\error.py", line 1, in <module>
  File "C:\_dev\ERROR~1.DIS\scipy\__init__.py", line 202, in __getattr__
  File "importlib.py", line 126, in import_module
  File "C:\_dev\ERROR~1.DIS\scipy\linalg\__init__.py", line 206, in <module scipy.linalg>
  File "C:\_dev\ERROR~1.DIS\scipy\linalg\_misc.py", line 3, in <module scipy.linalg._misc>
  File "C:\_dev\ERROR~1.DIS\scipy\linalg\blas.py", line 213, in <module scipy.linalg.blas>
ImportError: LoadLibraryExW 'C:\_dev\ERROR~1.DIS\scipy\linalg\_fblas.pyd' failed: The specified module could not be found.
```
The cause seems to be, that `scipy.libs/libopenblas_v0.3.20-571-g3dec11c6-gcc_10_3_0-c2315440d6b6cef5037bad648efc8c59.dll` is missing from the output directory. Nuitka includes this when the SciPy version is 1.11.1, manually adding this file also resolves this error

**Nuitka version, full Python version, flavor, OS, etc.**

```
1.7.10
Commercial: None
Python: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\sebastian.weis\AppData\Local\pypoetry\Cache\virtualenvs\spinfit-server-8_mJBifK-py3.11\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).
```

**How did you install Nuitka and Python**

 Via Poetry in a venv

**The specific PyPI names and versions**

```
Nuitka==1.7.10
numexpr==2.8.5
numpy==1.25.2
scipy==1.11.2
```

**Example Code that causes the error**

```python
from scipy import linalg as la

print(la.get_blas_funcs('gemv'))
```

**Used Nuitka options**

```
python -m nuitka --standalone --assume-yes-for-downloads --python-flag=no_docstrings error.py
```

I have not tested other Nuitka versions, however Nuitka 1.7.7-1.7.10 were all working with SciPy 1.11.1

**Comment by kayhayen** [comment]
I think you meant to say it's work with 1.11.1 in your last comment. Disabling docstrings is not a guarantuee to work with all packages and their updates, but this is about a DLL, so it won't matter.

**Comment by kayhayen** [comment]
Ok, they checked their patch function from containing `_delvewheel_init_patch` to just `_delvewheel_patch` which is well, a change that I bet was urgently needed.

**Comment by kayhayen** [comment]
Just as an side, comparing the 2 compilation reports would also reveal that delvewheel plugin would have losts its influece on the compilation.

**Comment by SebastianWeis** [comment]
> I think you meant to say it's work with 1.11.1 in your last comment. Disabling docstrings is not a guarantuee to work with all packages and their updates, but this is about a DLL, so it won't matter.

Yes, thats what i meant, sorry. Fixed the typo. Thanks for the advice about disabling docstrings, thats something i have to keep in mind then

**Comment by SebastianWeis** [comment]
Can confirm that this is fixed on the factory branch, thanks for the quick help!

**Comment by kayhayen** [comment]
Part of the 1.8 release I just made.
