### ISSUE TITLE
openvino onefile error on windows

### ISSUE THREAD

**Issue by Monday-Leo** [Nuitka/Nuitka#2412]
I'm trying to package an openvino program into an exe with nuitka. My nuitka version is 1.5.7 python 3.7. My command is like this:
`nuitka --standalone --show-memory  --show-progress --output-dir=o --onefile openvino_infer.py`
I read the issue #1699 and i run successfully through moving the plugins.xml and dlls to the dist folder. But when i run the onefile exe, it cannot find the plugins.xml even though i have put it in the same folder. How to solve the error?
![$M4Q {VX21E)RB~ C}D6W`4](https://github.com/Nuitka/Nuitka/assets/53975909/0f71021a-db2a-4704-85d2-5808096a559f)
![LM2%S3W8RQB8AKUYOBSF)IO](https://github.com/Nuitka/Nuitka/assets/53975909/8b1ca237-3d3f-405d-9d37-ac3c08b6d627)

**Comment by Monday-Leo** [comment]
I set the plugins.xml path in python code. The exe can load the xml, but still miss the openvino_onnx_frontend.dll which is needed. It doesn't work when i put the dll in the onefile folder. How to let the onefile exe load the openvino_onnx_frontend.dll?

**Comment by Monday-Leo** [comment]
I suppose that the openvino.dll and openvino_onnx_frontend.dll must be in the same path. The problem is nuitka only judge openvino.dll as dependence and ingore the openvino_onnx_frontend.dll. In distribution, I can move the dll by hand. However, in onefile, the exe only pack openvino.dll which leads to error. Are there any solutions to contain the openvino_onnx_frontend.dll in onefile?

**Comment by AlphaLiu** [comment]
I think you could refer the solution of #2403

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
