### ISSUE TITLE
Crashing when using too old transformers package

### ISSUE THREAD

**Issue by yggdrasil75** [Nuitka/Nuitka#2417]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.
1.7.10
Commercial: None
Python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\Yggdrasil75\AppData\Local\Programs\Python\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\cl.exe (cl 14.3).

* How did you install Nuitka and Python
pip

  > python -m pip freeze
GitPython
Pillow
accelerate
basicsr
blendmodes
clean-fid
einops
gfpgan
gradio==3.32.0
inflection
jsonmerge
kornia
lark
numpy
omegaconf
open-clip-torch
piexif
psutil
pytorch_lightning
realesrgan
requests
resize-right
safetensors
scikit-image>=0.19
timm
tomesd
torch
torchdiffeq
torchsde
transformers==4.25.1
<details>
<summary>extra log output</summary>
* Provide in your issue the Nuitka options used

F:\creations\images\tool\nuitkabuildtest>nuitka --follow-imports --include-package=transformers launch.py
Nuitka-Options:INFO: Used command line options: --follow-imports --include-package=transformers launch.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.7.10' on Python '3.10' commercial grade 'not installed'.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka-Plugins:WARNING: options-nanny: Using module ('attr' version 22.2.0) with no full support: 'attrs' is not
Nuitka-Plugins:WARNING: fully supported before version 23.1.0
Nuitka-Plugins:INFO: pkg-resources: Injecting post-module load code for module 'pkg_resources':
Nuitka-Plugins:INFO: pkg-resources:     Registering Nuitka loader with "pkg_resources".
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'setuptools' (intending to avoid 'setuptools') in 'torch.utils.cpp_extension' (at                            rs.community
Nuitka-Plugins:WARNING: 'C:\Users\Yggdrasil75\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py:8') encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'setuptools' (intending to avoid 'setuptools') in 'torch.utils.cpp_extension' (at
Nuitka-Plugins:WARNING: 'C:\Users\Yggdrasil75\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py:24') encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/unwanted-module.html
Nuitka-Inclusion:WARNING: Cannot follow import to module 'aenum._py2' because of 'SyntaxError'.
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'IPython' (intending to avoid 'IPython') in 'gradio.utils' (at 'C:\Users\Yggdrasil75\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py:246') encountered.
Nuitka-Plugins:WARNING: It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'IPython' (intending to avoid 'IPython') in 'altair._magics' (at 'C:\Users\Yggdrasil75\AppData\Local\Programs\Python\Python310\lib\site-packages\altair\_magics.py:10')
Nuitka-Plugins:WARNING: encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'IPython' (intending to avoid 'IPython') in 'altair._magics' (at 'C:\Users\Yggdrasil75\AppData\Local\Programs\Python\Python310\lib\site-packages\altair\_magics.py:10')
Nuitka-Plugins:WARNING: encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'IPython' (intending to avoid 'IPython') in 'altair.utils.core' (at 'C:\Users\Yggdrasil75\AppData\Local\Programs\Python\Python310\lib\site-packages\altair\utils\core.py:632')
Nuitka-Plugins:WARNING: encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'IPython' (intending to avoid 'IPython') in 'ipykernel.zmqshell' (at 'C:\Users\Yggdrasil75\AppData\Local\Programs\Python\Python310\lib\site-packages\ipykernel\zmqshell.py:22')
Nuitka-Plugins:WARNING: encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'IPython' (intending to avoid 'IPython') in 'ipykernel.eventloops' (at 'C:\Users\Yggdrasil75\AppData\Local\Programs\Python\Python310\lib\site-packages\ipykernel\eventloops.py:75')Nuitka-Plugins:WARNING: encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'IPython' (intending to avoid 'IPython') in 'ipykernel.eventloops' (at
Nuitka-Plugins:WARNING: 'C:\Users\Yggdrasil75\AppData\Local\Programs\Python\Python310\lib\site-packages\ipykernel\eventloops.py:540') encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/unwanted-module.html
Nuitka-Inclusion:INFO: Cannot find distribution 'oneccl_bind_pt' at 'C:\Users\Yggdrasil75\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\utils\imports.py:72', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'megatron-lm' at 'C:\Users\Yggdrasil75\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\utils\imports.py:111', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'intel_extension_for_pytorch' at 'C:\Users\Yggdrasil75\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\utils\imports.py:185', expect potential run time problem, unless this is unused code.
</details>

PASS 1: 88.7%|██████████████████████▏  | 10198/11502, transformers.tools            Traceback (most recent call last):
  File "C:\Users\Yggdrasil75\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\plugins\Plugins.py", line 81, in withPluginProblemReporting
    yield
  File "C:\Users\Yggdrasil75\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\plugins\Plugins.py", line 533, in considerImplicitImports
    cls._considerImplicitImports(plugin=plugin, module=module)
  File "C:\Users\Yggdrasil75\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\plugins\Plugins.py", line 424, in _considerImplicitImports
    for full_name in iterateModuleNames(plugin.getImplicitImports(module)):
  File "C:\Users\Yggdrasil75\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\plugins\Plugins.py", line 401, in iterateModuleNames
    for v in value:
  File "C:\Users\Yggdrasil75\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\plugins\standard\TransformersPlugin.py", line 246, in getImplicitImports
    for sub_module_name in self.queryRuntimeInformationSingle(
  File "C:\Users\Yggdrasil75\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\plugins\PluginBase.py", line 1078, in queryRuntimeInformationSingle
    ).key
AttributeError: 'NoneType' object has no attribute 'key'
FATAL: transformers: Plugin issue while working on 'module 'transformers.tools''. Please report the bug with the above traceback included.

**Comment by kayhayen** [comment]
No reproducer though.

**Comment by kayhayen** [comment]
I suspect this is old transformers not having the data prepared, I will add a error for old transformers, which we don't support, without commercial backing I cannot see myself supporting older versions of transformers at this point.

**Comment by yggdrasil75** [comment]
alright, will try with newer transformers forced.

**Comment by kayhayen** [comment]
Still want to add those warnings at least.
