### ISSUE TITLE
how to build a pyd to target many python versions

### ISSUE THREAD

**Issue by urna** [Nuitka/Nuitka#2420]
hi guys,

I just wanna know how to build a pyd to target many python versions, let's say 3.5 3.6 3.7......3.11.

Just install all python versions and build them one by one, or there's some "Cloud Service" to do so?

**Comment by kayhayen** [comment]
You could use Nuitka Action with GitHub Actions, https://github.com/Nuitka/Nuitka-Action in a matrix configuration over the Python versions. I guess it would be interesting to add an example for that to the action docs. If you come up with something, please share it.

**Comment by urna** [comment]
邮件已收到，通常我在1～2天内回复。如有急事，请直接电话联系 ----我的微信 haijun-data

**Comment by kayhayen** [comment]
@urna please get your auto responder under control, it's very annoying

**Comment by urna** [comment]
Thanks a lot! First knew this and let me just take try!

**Comment by urna** [comment]
Finally, installed many python versions and by switch to one by one by changing path env var to get it done
