### ISSUE TITLE
QSQLITE driver not loaded with PySide6 application

### ISSUE THREAD

**Issue by ben-hearn-sb** [Nuitka/Nuitka#2424]
Hello,

After compiling my application it runs into an exception where the QSQLITE database cannot be opened due to the QSQLITE database driver not being available voa PySide6.

I have tried to compile the app in standalone, onefile and without any of the options and still no luck. Also the --include-qt-plugins option I have tried with a few variations, qsqlite, qsqlite3, qtsql and still nothing. 

_Note: Using --help does not give me any pointers on what to input in this command._

Can you advise how to get nuitka to find and include the necessary libs?

Exact error below:
```
QSqlDatabase: QSQLITE driver not loaded
QSqlDatabase: available drivers: 
```

**- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.**

```
1.7.10
Commercial: None
Python: 3.9.17 (main, Jul  5 2023, 16:17:03) 
Flavor: Anaconda Python
Executable: /Users/benhearn/miniconda3/envs/traxmanager_dev_venv/bin/python
OS: Darwin
Arch: x86_64
```

**How did you install Nuitka and python?**

```
Installed python via miniconda and set up a virtual env using conda
Installed Nuitka via pip
```

**- The specific PyPI names and versions**

```
certifi==2023.7.22
cffi==1.15.1
chardet==4.0.0
charset-normalizer==3.2.0
Cython==3.0.0
ftfy==6.0.3
idna==3.4
joblib==1.3.1
lxml==4.6.5
mutagen==1.45.1
Nuitka==1.7.10
numpy==1.25.2
ordered-set==4.1.0
packaging==23.1
Pillow==10.0.0
pycparser==2.21
pyside6==6.5.2
python-vlc==3.0.16120
pyuca==1.2
QtPy==2.3.1
requests==2.31.0
scikit-learn==0.24.1
scipy==1.11.1
shiboken6==6.5.2
SoundFile==0.10.3.post1
sparse-dot-topn==0.2.9
threadpoolctl==3.2.0
timeloop==1.0.2
urllib3==2.0.4
wcwidth==0.2.6
winshell==0.6
zstandard==0.21.0
```

**- Also supply a Short, Self Contained, Correct, Example**

```
from PySide6 import QtWidgets
from PySide6.QtSql import QSqlDatabase
import sys

def main():
    app = QtWidgets.QApplication(sys.argv)
    db = QSqlDatabase.addDatabase("QSQLITE")
    if not db.open():
        raise Exception('Cannot open database')

if __name__ == "__main__":
    main()
```

**- Provide in your issue the Nuitka options used**

`Nuitka-Options:INFO: Used command line options: ./test_db.py --standalone --remove-output --enable-plugin=pyside6 --include-qt-plugins=sensible --include-qt-plugins=qsqlite --plugin-enable=pylint-warnings --output-dir=./tests/test_nuitka_builds -o testdb.app`

**NOTE: I have tried various options for --include-qt-plugins such as qsqlite3, qtsql and none seem to work.**

**Comment by kayhayen** [comment]
This is obsolete information, in 1.8 which is the current release this was changed and `sensible` is now added to with this option, and there is a new option to subtract instead. The 1.8 is out for a few days already.
