### ISSUE TITLE
FATAL: Error, call to 'otool' failed

### ISSUE THREAD

**Issue by lidney-clarke** [Nuitka/Nuitka#2425]
Any suggestions?

FATAL: Error, call to 'otool' failed: ['/usr/bin/otool', '-l', '/Library/Frameworks/Python.framework/Versions/3.11/bin/python3'] -> b'xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun\n'.

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
