### ISSUE TITLE
ABOUT [sentence_transformers]

### ISSUE THREAD

**Issue by aylitat** [Nuitka/Nuitka#2427]
I package a programe with langchain embeddings plugin, named : **sentence_transformer**
and I try to use ' --nofollow-import-to=langchain ' to package it.
all runs well , but when the programe use this module.
it debug :
`Could not import sentence_transformers python package. Please install it with `pip install sentence_`
I use this module to make a vectorstore.
I had put the module folder in the programe folder, but it still dosenot work.
It improted like this:
`from langchain.embeddings.sentence_transformer import SentenceTransformerEmbeddings`
sentence_transformer file ↓
`"""HuggingFace sentence_transformer embedding models."""
from langchain.embeddings.huggingface import HuggingFaceEmbeddings

SentenceTransformerEmbeddings = HuggingFaceEmbeddings`

the class code:
`class HuggingFaceEmbeddings(BaseModel, Embeddings):
    """HuggingFace sentence_transformers embedding models.

    To use, you should have the ``sentence_transformers`` python package installed.

    Example:
        .. code-block:: python

            from langchain.embeddings import HuggingFaceEmbeddings

            model_name = "sentence-transformers/all-mpnet-base-v2"
            model_kwargs = {'device': 'cpu'}
            encode_kwargs = {'normalize_embeddings': False}
            hf = HuggingFaceEmbeddings(
                model_name=model_name,
                model_kwargs=model_kwargs,
                encode_kwargs=encode_kwargs
            )
    """

    client: Any  #: :meta private:
    model_name: str = DEFAULT_MODEL_NAME
    """Model name to use."""
    cache_folder: Optional[str] = None
    """Path to store models. 
    Can be also set by SENTENCE_TRANSFORMERS_HOME environment variable."""
    model_kwargs: Dict[str, Any] = Field(default_factory=dict)
    """Key word arguments to pass to the model."""
    encode_kwargs: Dict[str, Any] = Field(default_factory=dict)
    """Key word arguments to pass when calling the `encode` method of the model."""
    multi_process: bool = False
    """Run encode() on multiple GPUs."""

    def __init__(self, **kwargs: Any):
        """Initialize the sentence_transformer."""
        super().__init__(**kwargs)
        try:
            import langchain.sentence_transformers as sentence_transformers

        except ImportError as exc:
            raise ImportError(
                "Could not import sentence_transformers python package. "
                "Please install it with `pip install sentence_transformers`."
            ) from exc
..........`

**Comment by kayhayen** [comment]
There are issues for huggingface_hub and sentence transformers both. #2375 and #2378 are maybe the issues, they are both on the list of to be fixed real soon now, follow those.
