### ISSUE TITLE
Nuitka 1.8 not working with google's vision api

### ISSUE THREAD

**Issue by LeonG68** [Nuitka/Nuitka#2428]
> Python and Nuitka Version

`
$ python -m nuitka --version
1.8
Commercial: None
Python: 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\Leon\AppData\Local\Programs\Python\Python39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\cl.exe (cl 14.3).
`

I'm using google's vision api and am running into this error after packaging the file.

`
Exception ignored in: 'grpc._cython.cygrpc.ssl_roots_override_callback’ E0905 20:53:40.462000000 45048 src/core/lib/security/security_connector/ssl_utils.cc:593] assertion failed: pem_root_certs != nullptr
`

I fixed it in the .dist folder by follow instructions from this page: https://github.com/googleapis/google-cloud-python/issues/5774

And placing the credentials folder and root.pem from: 

`
Python39\site-packages\grpc\_cython\_credentials\roots.pem
`

to: 

`
server.dist\grpc\_cython
`

However, I want to turn it into a `--onefile` instead of `--standalone`. How do I fix this? Is there a way to go from .dist to standalone after fixing .dist?

I can only send you the reproducible on discord because it contains my api keys.

**Comment by LeonG68** [comment]
Tested with 1.8 and 1.8rc9. Neither worked.

**Comment by LeonG68** [comment]
Fixed it! Added 

`
--include-module=grpc --include-package=grpc   --include-package-data=grpc
`

**Comment by kayhayen** [comment]
Maybe I can find a reproducer from the gprc site. Including data files is a common problem, but knowing that it really is needed, and doesn't come from certifi helps. The other things look like hidden dependencies that we need to figure out as well.

**Comment by kayhayen** [comment]
So, checking a hello world, it didn't need it. However, I guess that is mostly because it didn't really do anything, not a lot of data files there:

```
python3.10 ~/repos/Py2C/bin/nuitka --list-package-data=grpc
Nuitka-Tools:INFO: Checking package directory 'C:\Python310_64\lib\site-packages\grpc' ..
C:\Python310_64\lib\site-packages\grpc
C:\Python310_64\lib\site-packages\grpc\_cython\_credentials\roots.pem
Nuitka-Tools:INFO: Found 1 data files.
```

Going to add package configuration for that in 1.8.1

**Comment by kayhayen** [comment]
Also with your reproducers I came across this as an actual needed file.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.8.1 that I just made. But it might be that you need staging to have all fixes done for you.
