### ISSUE TITLE
Mac .App not opening directly, but does when running from terminal

### ISSUE THREAD

**Issue by LeaEdwards** [Nuitka/Nuitka#2429]
Hi! 

Hoping you can help.

When I create the .app on OSX, the main .app does not do anything... (It bounces for a few seconds then closes) however, if in terminal I do: main.app/Contents/MacOS/main

Then it works fine...

Something I missed?

Thanks!

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
