### ISSUE TITLE
Enhancement: Add support to PEP 540 -- Add a new UTF-8 Mode

### ISSUE THREAD

**Issue by jcrmatos** [Nuitka/Nuitka#243]
Consider adding support to PEP 540 -- Add a new UTF-8 Mode.
https://www.python.org/dev/peps/pep-0540/

**Comment by jcrmatos** [comment]
How do I pass the -X utf8 python flag to nuitka?
I know python's -O and -OO can be used in nuitka with --python-flag=-O or --python-flag=-OO but I tried --python-fag=-X utf8 and --python-flag=-Xutf8 and both don't work.

**Comment by jcrmatos** [comment]
I'm testing with the command
python -m nuitka --run test.py

**Comment by kayhayen** [comment]
Use `python -X utf8 -m nuitka --run test.py`  or set `PYTHONUTF8` environment variable.

**Comment by jcrmatos** [comment]
ok, thanks.
