### ISSUE TITLE
include-module not working as it was

### ISSUE THREAD

**Issue by bullghost** [Nuitka/Nuitka#2431]
nevermind i found the issue, its was the path , 
let say the project folder name "testproject"
so inside the testproject folder i call nuitka

and inside get_post_data.py
from src.html_parse import html_tag

when i build with version 0.7.1 it was fine, it will found the html_parse module
but with 1.8 will not found. so i need to remove the src. to getting work

------------------------------------------
hi i came from version 0.7.1 
since last year using python 3.9

now today i try using latest version 1.8 with python 3.11
> nuitka3 --show-progress --static-libpython=yes --include-package=utils --include-module=src.html_parse --output-dir=bin src/get_post_data.py 

ModuleNotFoundError: No module named 'custom_lib'

the os is same, processor is same amd ryzen and x86_64

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
