### ISSUE TITLE
time.strptime in Python 3.11 depends on module "calendar"

### ISSUE THREAD

**Issue by TsXor** [Nuitka/Nuitka#2432]
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version

```
1.8
Commercial: None
Python: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: D:\Python\3.11\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: D:\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\cl.exe (cl 14.3).
```

- How did you install Nuitka and Python

```
pip install nuitka
```

- The specific PyPI names and versions

  > python -m pip freeze

```
Nuitka==1.8
```

Look at this simple example:
```python
import time
TIME_TEMPLATE = '%Y-%m-%d_%H-%M-%S'
timestr = time.strftime(TIME_TEMPLATE, time.localtime())
time = time.strptime(timestr, TIME_TEMPLATE)
```

It crashes after standalone compilation:
```
Traceback (most recent call last):
  File "E:\Users\23Xor\home\TEST~1.DIS\test.py", line 4, in <module>
  File "E:\Users\23Xor\home\TEST~1.DIS\_strptime.py", line 15, in <module>
ModuleNotFoundError: No module named 'calendar'
```

`--include-module=calendar` can fix it.

Yes, `time` is builtin and its dependencies cannot be inspected. However, I think we should do something to let standard things run normally.

**Comment by kayhayen** [comment]
Agreed. The `calendar` is only the list of things rarely imported by extension modules, however, `time` of course means it absolutely is.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.8.1 that I just made.
