### ISSUE TITLE
centos8 ./Modules/_ssl.c:5427: undefined reference to `RAND_status'

### ISSUE THREAD

**Issue by yanboma** [Nuitka/Nuitka#2436]
[]# python -m nuitka --version
1.8.1
Commercial: None
Python: 3.9.15 (main, Sep 12 2023, 10:41:56) 
Flavor: Unknown
Executable: /usr/bin/python
OS: Linux
Arch: x86_64
Distribution: Tencentos (based on Fedora) 3.2
Version C compiler: /usr/bin/gcc (gcc).

python -m nuitka --standalone --nofollow-imports --show-memory --show-progress --follow-stdlib --static-libpython=yes --enable-plugin=anti-bloat ---enable-plugin=multiprocessing --verbose-output=nuitka_compile.txt main.py

Nuitka-Scons:INFO: Backend linking program with 1266 files (no progress information available for this stage).
/usr/bin/ld: /usr/local/python39/lib/libpython3.9.a(_ssl.o): in function `_ssl_RAND_status_impl':
/mnt/Python-3.9.15/./Modules/_ssl.c:5427: undefined reference to `RAND_status'
/usr/bin/ld: /usr/local/python39/lib/libpython3.9.a(_ssl.o): in function `_ssl_RAND_add_impl':
/mnt/Python-3.9.15/./Modules/_ssl.c:5331: undefined reference to `RAND_add'
/usr/bin/ld: /usr/local/python39/lib/libpython3.9.a(_ssl.o): in function `memory_bio_dealloc':
/mnt/Python-3.9.15/./Modules/_ssl.c:4937: undefined reference to `BIO_free'
/usr/bin/ld: /usr/local/python39/lib/libpython3.9.a(_ssl.o): in function `PySSLSession_get_timeout':
/mnt/Python-3.9.15/./Modules/_ssl.c:5217: undefined reference to `SSL_SESSION_get_timeout'
/usr/bin/ld: /usr/local/python39/lib/libpython3.9.a(_ssl.o): in function `PySSLSession_get_time':
/mnt/Python-3.9.15/./Modules/_ssl.c:5208: undefined reference to `SSL_SESSION_get_time'
/usr/bin/ld: /usr/local/python39/lib/libpython3.9.a(_ssl.o): in function `PySSLSession_get_ticket_lifetime_hint':
/mnt/Python-3.9.15/./Modules/_ssl.c:5226: undefined reference to `SSL_SESSION_get_ticket_lifetime_hint'
/usr/bin/ld: /usr/local/python39/lib/libpython3.9.a(_ssl.o): in function `PySSLSession_get_session_id':
/mnt/Python-3.9.15/./Modules/_ssl.c:5238: undefined reference to `SSL_SESSION_get_id'
/usr/bin/ld: /usr/local/python39/lib/libpython3.9.a(_ssl.o): in function `_ssl_MemoryBIO_impl':
/mnt/Python-3.9.15/./Modules/_ssl.c:4910: undefined reference to `BIO_s_mem'
/usr/bin/ld: /mnt/Python-3.9.15/./Modules/_ssl.c:4910: undefined reference to `BIO_new'
/usr/bin/ld: /mnt/Python-3.9.15/./Modules/_ssl.c:4919: undefined reference to `BIO_set_flags'
/usr/bin/ld: /mnt/Python-3.9.15/./Modules/_ssl.c:4920: undefined reference to `BIO_ctrl'
/usr/bin/ld: /mnt/Python-3.9.15/./Modules/_ssl.c:4925: undefined reference to `BIO_free'
/usr/bin/ld: /usr/local/python39/lib/libpython3.9.a(_ssl.o): in function `memory_bio_get_eof':
/mnt/Python-3.9.15/./Modules/_ssl.c:4953: undefined reference to `BIO_ctrl_pending'
/usr/bin/ld: /usr/local/python39/lib/libpython3.9.a(_ssl.o): in function `memory_bio_get_pending':
/mnt/Python-3.9.15/./Modules/_ssl.c:4944: undefined reference to `BIO_ctrl_pending'
/usr/bin/ld: /usr/local/python39/lib/libpython3.9.a(_ssl.o): in function `_ssl_session_dup':
/mnt/Python-3.9.15/./Modules/_ssl.c:2857: undefined reference to `i2d_SSL_SESSION'
/usr/bin/ld: /mnt/Python-3.9.15/./Modules/_ssl.c:2867: undefined reference to `i2d_SSL_SESSION'
/usr/bin/ld: /mnt/Python-3.9.15/./Modules/_ssl.c:2872: undefined reference to `d2i_SSL_SESSION'
/usr/bin/ld: /usr/local/python39/lib/libpython3.9.a(_ssl.o): in function `get_maximum_version':
/mnt/Python-3.9.15/./Modules/_ssl.c:3720: undefined reference to `SSL_CTX_ctrl'
/usr/bin/ld: /usr/local/python39/lib/libpython3.9.a(_ssl.o): in function `get_minimum_version':
/mnt/Python-3.9.15/./Modules/_ssl.c:3704: undefined reference to `SSL_CTX_ctrl'
/usr/bin/ld: /usr/local/python39/lib/libpython3.9.a(_ssl.o): in function `set_host_flags':
/mnt/Python-3.9.15/./Modules/_ssl.c:3811: undefined reference to `SSL_CTX_get0_param'
/usr/bin/ld: /mnt/Python-3.9.15/./Modules/_ssl.c:3813: undefined reference to `X509_VERIFY_PARAM_set_hostflags'
/usr/bin/ld: /usr/local/python39/lib/libpython3.9.a(_ssl.o): in function `get_verify_flags':
/mnt/Python-3.9.15/./Modules/_ssl.c:3602: undefined reference to `SSL_CTX_get0_param'

**Comment by yanboma** [comment]
# ldconfig -v|grep ssl
ldconfig: Can't stat /libx32: No such file or directory
ldconfig: Path `/usr/lib' given more than once
ldconfig: Path `/usr/lib64' given more than once
ldconfig: Can't stat /usr/libx32: No such file or directory
        libevent_openssl-2.1.so.6 -> libevent_openssl-2.1.so.6.0.2
        libssl3.so -> libssl3.so
        libxmlrpc_openssl.so.1 -> libxmlrpc_openssl.so.1.51
        libssl.so.1.1 -> libssl.so.10

**Comment by kayhayen** [comment]
Is it working without --static-libpython ?

Also these seem to suggest you do not read warnings: --standalone --nofollow-imports --follow-stdlib
