### ISSUE TITLE
[question] Add data files *after* the executable was built

### ISSUE THREAD

**Issue by henzef** [Nuitka/Nuitka#2437]
Hi,
first of all thanks for this awesome tool :)

My usecase involves generating multiple very similar Windows executables with --onefile (only a configuration file that I currently add with --include-data-file is different) and the build process takes a lot of time, because I need to call Nuitka once for each configuration file.
Is it somehow already possible to add files to a prebuilt executable, so I could just call Nuitka once to build a base-executable and append the config file as a second step?
If not, could you point me to relevant documentation, so I can try to write such a tool myself?

Regards

**Comment by kayhayen** [comment]
Did you checkout the multidist feature? https://nuitka.net/doc/user-manual.html#use-case-6-multidist

I think it has a kind of wrong name, because it's actually orthogonal to the mode used, and works with onefile as well.

**Comment by henzef** [comment]
I took a different approach that fixed it for me: Append a zip file to the end of the executable and extract it within the application:

    def extract_appended_exe_payload() -> None:
        # Only do something if we have been compiled by Nuitka
        if "__compiled__" not in globals() or not sys.argv[0].endswith(".exe"):
            return

        with open(sys.argv[0], "rb") as f:
            # The length of the zip file is stored in the last 8 bytes of the exe file
            f.seek(-8, os.SEEK_END)
            zip_size = int.from_bytes(f.read(8), byteorder="little", signed=False)

            # The zip file itself comes before that and is appended to the exe
            f.seek(-8 - zip_size, os.SEEK_CUR)
            zip_content = f.read(zip_size)

            with ZipFile(BytesIO(zip_content)) as zipfile:
                zipfile.extractall(path=base_path)

The exe modification simply works as follows:

    def append_zip_file(exe_file_name: str, output_file_name: str, *data_file_names: str) -> None:
        zip_buffer = BytesIO()
    
        with ZipFile(zip_buffer, 'w') as zipfile:
            for data_filename in data_file_names:
                zipfile.write(data_filename)
    
        with open(exe_file_name, 'rb') as exe_file, open(output_file_name, 'wb') as output_file:
            output_file.write(exe_file.read())
            zip_content = zip_buffer.getvalue()
            output_file.write(zip_content)
            output_file.write(len(zip_content).to_bytes(length=8, byteorder="little", signed=False))
