### ISSUE TITLE
Using multiprocessing always causes AttributeError: Can't get attribute. 

### ISSUE THREAD

**Issue by teemo25** [Nuitka/Nuitka#2439]
Versions and modules:
```
pip 23.2.1 from C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip (python 3.11)
```
```
1.8.1
Commercial: None
Python: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\Admin\AppData\Local\Programs\Python\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\Hostx64\x64\cl.exe (cl 14.3).
```
```
dill==0.3.7
multiprocess==0.70.15
Nuitka==1.8.1
zstandard==0.21.0
```

Code:
```
import multiprocessing
import time

def main():
    while True:
        print("Testing")
        time.sleep(0.5)

if __name__ == "__main__":
    p = multiprocessing.Process(target=main)
    p.start()
```

Options used:
`python -m nuitka processtest.py`
Output while compiling:
```
Nuitka-Options:INFO: Used command line options: processtest.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure that is intended.   
Nuitka:INFO: Starting Python compilation with Nuitka '1.8.1' on Python '3.11' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl 14.3).
Nuitka-Scons:INFO: Compiled 9 C files using clcache with 3 cache hits and 6 cache misses.
Nuitka:INFO: Keeping build directory 'processtest.build'.
Nuitka:INFO: Successfully created 'processtest.exe'.
Nuitka:INFO: Execute it by launching 'processtest.cmd', the batch file needs to set environment.
```

Error: 
```
Traceback (most recent call last):
  File "C:\Users\Admin\Documents\PYTHON\nutika\processtest.py", line 36, in <module __parents_main__>
  File "C:\Users\Admin\Documents\PYTHON\nutika\processtest.py", line 35, in __nuitka_freeze_support
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 130, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'main' on <module '__main__' (built-in)>
```

Tried with developer branch, 1.8 and 1.8.1 version of nuitka. 

Ive also tried with the `multiprocess` module as well as importing the functions from another file, only importing the functions worked. Im sure that it should work without importing the functions because I used nuitka like 2 days ago with multiprocessing with no issues. Ive since then reinstalled windows but Ive installed everything the exact same way again. Im still on the same exact version of Windows 10 as well.

**Comment by kayhayen** [comment]
The problem exists with only the `__main__` names, moved to another module, it already works better. I kind of suspect, that is because the forked multiprocessing does not populate `sys.modules["__main__"]` with `__parents_main__` which is the copy if the code they run rather than `__main__`.

Every other use of multiprocessing just works. So this probably just needs a tweak of some sorts. Adding to the automatic `__nuitka_freeze_support` that is injected this line worked for me just now.

```
sys.modules["__main__"] = sys.modules["__parents_main__"]
```

So, your test case is rather special there, but I think I have encountered this before maybe, but didn't quite get to it.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working. 

This will also be in 1.8.2 once it's out.

**Comment by nickger** [comment]
Yep, that one works (and 1.6). Thx.

**Comment by kayhayen** [comment]
This is part of the 1.8.2 hotfix I made just now.

**Comment by w0nzy** [comment]
Hello I make new project but when i import multiprocessing module its give this error how can i fix this 
some error strings 
 File "C:\Users\bla\AppData\Local\Temp\ON45A7~1\wallpaper_payload.py", line 71, in <module __parents_main__>
  File "C:\Users\bla\AppData\Local\Temp\ON45A7~1\wallpaper_payload.py", line 70, in __nuitka_freeze_support
  File "C:\Users\bla\AppData\Local\Temp\ON45A7~1\multiprocessing\spawn.py", line 120, in spawn_main
  File "C:\Users\bla\AppData\Local\Temp\ON45A7~1\multiprocessing\spawn.py", line 130, in _main
AttributeError: Can't get attribute 'WallPaperChanger' on <module '__main__' (built-in)>

**Comment by w0nzy** [comment]
Yeah I was have old version of nuitka 1.8.1 and its was giving this error and removed old nuitka i installed new version fixed. now its working without any error thanks
