### ISSUE TITLE
SIGSEGV (Address boundary error) on py3.11 using sqlglot

### ISSUE THREAD

**Issue by mishamsk** [Nuitka/Nuitka#2445]
The following code works in python 3.11.5 and 3.10.13:

```python
from sqlglot import transpile

print(transpile("SELECT * FROM foo", write="spark", pretty=True, identity=True)) # prints ['SELECT\n  *\nFROM foo']
```

It also works when compiled by Nuitka on python 3.10, at least starting with version 1.7.1.

However, on python 3.11.5, running compiled version results in:
```sh
> python -m nuitka --standalone sqlglot_test.py 
Nuitka-Options:INFO: Used command line options: --standalone sqlglot_test.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.9rc2' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:INFO: anti-bloat: Not including '_json' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka-Plugins:INFO: anti-bloat: Not including '_bisect' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.                        
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: clang (clang).
Nuitka-Scons:INFO: Backend linking program with 64 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 64 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 1
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 63
Nuitka:INFO: Keeping build directory 'sqlglot_test.build'.                     
Nuitka:INFO: Created binary that runs on macOS 13.4 (arm64) or higher.
Nuitka:INFO: Successfully created 'sqlglot_test.dist/sqlglot_test.bin'.

> sqlglot_test.dist/sqlglot_test.bin 
fish: Job 1, 'sqlglot_test.dist/sqlglot_test.…' terminated by signal SIGSEGV (Address boundary error)
```

Nuitka versions tried:

* 1.7.9 commercial
* 1.8.1 commercial
* develop

The issue is with this [sqlglot](https://github.com/tobymao/sqlglot)

- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

I believe we've experienced the same issue on Windows build, but I haven't tested the minimal example of Windows. See below.

For most recent commercial I tried:
```sh
1.8.1
Commercial: 2.2.3
Python: 3.11.5 (main, Aug 29 2023, 09:28:47) [Clang 14.0.3 (clang-1403.0.22.14.1)]
Flavor: Unknown
Executable: redacted/nuitka_tests/.venv/bin/python
OS: Darwin
Arch: arm64
Version C compiler: /opt/homebrew/opt/ccache/libexec/clang (clang).
```

For development version
```sh
1.9rc2
Commercial: None
Python: 3.11.5 (main, Aug 29 2023, 09:28:47) [Clang 14.0.3 (clang-1403.0.22.14.1)]
Flavor: Unknown
Executable: redacted/nuitka_tests/.venv/bin/python
OS: Darwin
Arch: arm64
Version C compiler: /opt/homebrew/opt/ccache/libexec/clang (clang).
AttributeError: 'SConsEnvironment' object has no attribute 'nuitka_src':
  File "redacted/nuitka_tests/.venv/lib/python3.11/site-packages/nuitka/build/CCompilerVersion.scons", line 253:
    setupCCompiler(
  File "redacted/nuitka_tests/.venv/lib/python3.11/site-packages/nuitka/build/SconsCompilerSettings.py", line 792:
    os.path.join(env.nuitka_src, "inline_copy", "zlib"),
```

- How did you install Nuitka and Python

Used pip

- The specific PyPI names and versions

```sh
Nuitka @ git+redacted
ordered-set==4.1.0
sqlglot==18.5.0
zstandard==0.21.0
```

P.S. noticed that sqlglot compilation generally takes enormous amount of time. The minimal example compiles 4-5min on my M1 Pro MacBook with cache installed. Most of the time it hangs on PASS 1 and 2 for `sqlglot.expressions` module.

**Comment by kayhayen** [comment]
Ah, version seems to have regressed, need to check this out, and this issue has priority, this is hopefully something simple.

**Comment by kayhayen** [comment]
The scalability of `sqlglot.expressions` will improve once class re-formulation becomes better, which is bound to happen. I am seeing it too. I will need to reproduce this, then maybe add a workaround for it specifically to not be compiled, so this can be fast as well.  With `python -m nuitka --edit=sqlglot.expressions` you can see for yourself, it's not a small file, but I think the many classes cause bad scalability by influencing each other.

**Comment by kayhayen** [comment]
I found the issue and fixed it on the factory (public) and staging (commercial) branches. Expect this to arrive as part of a 1.8.2 hotfix release in the next days, my CI is supposed to become happy with it first of course.

**Comment by mishamsk** [comment]
@kayhayen awesome, thanks a lot for being so quick!

**Comment by kayhayen** [comment]
This is part of the 1.8.2 hotfix I made on both commercial and standard version just now.

**Comment by mishamsk** [comment]
@kayhayen great, thanks. will try and report back if we get any new issues related to this.
