### ISSUE TITLE
FAQ using Nuitka in commercial products

### ISSUE THREAD

**Issue by brupelo** [Nuitka/Nuitka#245]
**INTRODUCTION**
--------

Hello, how you doing? I hope you guys are alright.

It's been a while since posted here although I tend to keep an eye once or twice a week to see how one of my favourites projects becomes better and better... I must to say you guys did a hell of amazing job in the last months, respect about that. Even I can see the number of contributors have increased sustantially, that's just amazing news! Please keep it going ;-D

That said, I'm opening this thread cos I was having some questions about the potential usage of nuitka on commercial products and since I'm not a lawyer I usually find it pretty hard to understand all the intricacies about software licenses. Hopefully you'll be able to clarify some of my questions:

**QUESTION**
-----

1) Today I've seen this [thread](https://lists.debian.org/debian-legal/2012/01/msg00012.html) from 2012 on debian lists and it seems to me (haven't read it completely) at that time Kay was trying to decide whether to go with GPL or Apache2.0... it seems he finally picked up Apache2.0. Has ever GPL been included in the repo?

My poor git skills have lead me to assume there hasn't, ie:

![showcase](https://dl.dropboxusercontent.com/s/c645akpgp3osu4a/SourceTree_2019-02-05_20-06-14.png)

2) I see there are 2 possible use-cases when you use nuitka on a potential commercial app:

    * 2.a) You decide to create your own commercial python compiler on top of Nuitka source code (derivative product)
    * 2.b) You use Nuitka to "protect" the source code of your commercial python application 

You just need to consider Apache2.0 license in case 2.a, right?

3) When you're forking a repo and creating a commercial product out of a particular branch, do you need to comform the license from that particular commit... or do you need to comform the license from that particular commit as well as the licenses from all the child commits (assuming the license has changed over time)?

4) In the homepage you can see in the contributors section says:

> Thanks go to these individuals for their much valued contributions to Nuitka. Contributors have the license to use Nuitka for their own code even if Closed Source.

I guess this is referring to use-case 2.a, right?

**NUITKA "ALTERNATIVES"**
----------

Got another questions but I'll try to keep the thread short... that said, just to clarify I'm not interested at all to create my own python compiler as I think Nuitka should (and will) be THE python compiler :D . Truth is, the other available alternatives out there are simply not good enough if you compare them to nuitka, here's a little compilation:

 - [bbFreeze](https://pypi.org/project/bbfreeze/)
 - [py2exe](https://github.com/goatpig/py2exe)
 - [pyInstaller](https://github.com/pyinstaller/pyinstaller)
 - [cx_freeze](https://pypi.org/project/cx_Freeze/)
 - [py2app](https://bitbucket.org/ronaldoussoren/py2app)
 - [shedskin](https://github.com/shedskin/shedskin)
 - [py14](https://github.com/lukasmartinelli/py14) <== This was promising
 - [py2c](https://github.com/pradyun/Py2C)
 - [cython](https://cython.org/)
 - [pybee](https://pybee.org/) <== Serious nuitka alternative

I'm sure there are more but just adding the ones that comes from the top of my head.

In any case, it'd be really interesting to provide a proper FAQ about this legal stuff... while I'm not interested on 2.a) I could potentially being interested in the future to use nuitka on 2.b) use-case 
if I ever decide to commercialize some of my python apps.

Other people who're also interested on this, please feel free to add your own questions so maybe we'll end up with a nice FAQ similar to the [pyinstaller one](https://github.com/pyinstaller/pyinstaller/wiki/FAQ)

Thanks in advance! ;)

Yours,
Bruno

**Comment by kayhayen** [comment]
I am not a lawyer, therefore cannot give you legal advice. The following is therefore only my assumption:

Using Nuitka to compile and distribute code of any license is definitely OK. The GPL information you reference is outdated.

Basing a product off Nuitka is definitely OK as well. The copyright notices in the source code are protected by the license and must never be removed. The source code wouldn't have to be distributed though.

Fun fact about project name:

```
# pwd
/home/hayen/repos/Py2C
```

I didn't know such a project exist, but the name was obvious. I call my private garbage checkout still that, while Nuitka is reserved for publicly visible stuff.

**Comment by brupelo** [comment]
Kay! First of all, thanks for your fast answer, so basically the legal terms are pretty similar to the Pyinstaller ones, as in:

    License
    Can I use Nuitka for my commercial, closed-source, Python application?
    Yes.

    If I use Nuitka for my commercial Python application, will I have to distribute my source code as well?
    Absolutely not. You can ship the executables created with Nuitka with whatever license you want.

    If I use Nuitka for my commercial Python application, will I have to advertise/mention/display that Nuitka is being used, for instance by quoting its copyright line?
    Absolutely not. But we will love you if you do.

    I need to modify Nuitka for my own needs. Can I do that?
    Of course, Nuitka is free software. This falls under the terms of the Apache2.0 license: you can modify Nuitka as you wish, but if you distribute your modifications (so-called derived work), you will have to do that under the Apache2.0 license. In short, you can't change the license of Nuitka.

...

> # pwd
> /home/hayen/repos/Py2C
> 

Lol, it's funny how we coders think the same "creative" way... If I went to create my own python to c compiler that would be exactly the name I'd also pick up :D ... In fact, you'll see projects of mine called "py{put_generic_boring_name_here}" all around :)

Btw, about the projects I've listed... the one I was more curious about was [https://github.com/lukasmartinelli/py14](https://github.com/lukasmartinelli/py14), any thought about that approach? Do you think at certain point that approach would be limiting?

Also, I'm curious, why did you close this thread so fast?

Yours,
B

**Comment by brupelo** [comment]
Even if I'm not a lawyer, I do really like the method used by SourceTree (which is closed source app):

![showcase](https://dl.dropboxusercontent.com/s/n69lshwz7qq6voy/SourceTree_2019-02-05_22-50-03.png)

![showcase](https://dl.dropboxusercontent.com/s/z7ti6hntv3lf39p/SourceTree_2019-02-05_22-51-52.png)

In there you can see how the app enumerates all 3rd party stuff as as well as their respective licenses. So I guess if my commercial closed-source app provided such a dialog listing nuitka + all pypi packages used that would be more than enough, wouldn't? (just guessing)
