### ISSUE TITLE
Question: Nuitka compiled application boot time, how does Nuitka boot apps?

### ISSUE THREAD

**Issue by ben-hearn-sb** [Nuitka/Nuitka#2450]
Hello!

After I finally managed to get Nuitka to compile my application I noticed that it is intensely slow to open the application onefile OR standalone file (inside the dist).

The application is quite extensive and will be released as commercial software in the near future, Nuitka is part of our investigation to find the right package system.

However, when I try to boot the application I notice that the start time is incredibly slow (slower than PyInstaller), I am curious what Nuitka is doing when the code is executed?

I need to run some profiling on the start process regardless of package system used but an average 55 second boot time is quite extensive.

Please let me know,

// Ben

- Nuitka version, full Python version, flavor, OS, etc. as output by this exact command.

```
1.8.1
Commercial: None
Python: 3.9.17 (main, Jul  5 2023, 16:17:03) 
Flavor: Anaconda Python
Executable: /Users/benhearn/miniconda3/envs/traxmanager_dev_venv/bin/python
OS: Darwin
Arch: x86_64
Version C compiler: /usr/bin/clang (clang).
```

How did you install Nuitka and python?

Installed python via miniconda and set up a virtual env using conda
Installed Nuitka via pip

- The specific PyPI names and versions

```
certifi==2023.7.22
cffi==1.15.1
chardet==4.0.0
charset-normalizer==3.2.0
Cython==3.0.0
ftfy==6.0.3
idna==3.4
joblib==1.3.1
lxml==4.6.5
mutagen==1.45.1
Nuitka==1.7.10
numpy==1.25.2
ordered-set==4.1.0
packaging==23.1
Pillow==10.0.0
pycparser==2.21
pyside6==6.5.2
python-vlc==3.0.16120
pyuca==1.2
QtPy==2.3.1
requests==2.31.0
scikit-learn==0.24.1
scipy==1.11.1
shiboken6==6.5.2
SoundFile==0.10.3.post1
sparse-dot-topn==0.2.9
threadpoolctl==3.2.0
timeloop==1.0.2
urllib3==2.0.4
wcwidth==0.2.6
winshell==0.6
zstandard==0.21.0
```

- Provide in your issue the Nuitka options used

```
nuitka_command = [
    "python", "-m", "nuitka",
    entry_point,
    "--onefile",
    "--remove-output",
    "--enable-plugin=pyside6",
    "--include-qt-plugins=sensible",
    "--include-qt-plugins=sqldrivers",
    "--plugin-enable=pylint-warnings",
    f"--output-dir={output}",
    f"--include-data-dir={data_dir}",
    "-o",
    app_name
]
```

**Comment by kayhayen** [comment]
Try develop, we enhanced startup time a lot for 1.9, by orders of magnitude in cases.
