### ISSUE TITLE
No module named 'av.video.codeccontext'

### ISSUE THREAD

**Issue by vutung1671997** [Nuitka/Nuitka#2456]
My build code:

nuitka3 --standalone \
        --include-data-dir=onvif_lib/wsdl=wsdl \
        --plugin-enable=pyside6 \
        --plugin-enable=glfw \
        --include-qt-plugins=sensible,multimedia \
        --macos-app-icon=src/assets/images/icon_128.png \
        --macos-app-name="VMS" \
        --macos-app-version="1.0" \
        VMS.py

My version nuitka and pyav:
Nuitka: 1.8.1
pyav: 10.0.0

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."

**Comment by laggykiller** [comment]
@vutung1671997 had the same issue. Seems like you have to compile using:
```
python -m nuitka --standalone --follow-imports --include-package=av --include-module=av.audio.codeccontext --include-module=av.video.codeccontext test.py
```

I think this is cumbersome, so I opened a proper issue here: https://github.com/Nuitka/Nuitka/issues/2467
