### ISSUE TITLE
How to run exe using external python environment

### ISSUE THREAD

**Issue by cainiaoshidai** [Nuitka/Nuitka#2457]
- Nuitka version：1.8.2 , full Python version ： 3.9.0,  OS： windows

I compiled successfully using the following command.
`nuitka --show-memory --show-progress --nofollow-imports --output-dir=out --follow-import-to=need deeppc.py`
So, I get to files, one is exe and one is cmd. 
Please tell me how to use a relative path so that the exe can find the python environment instead of the current absolute path.

Example:
C:\Users\win10>D:\python_env\out\deeppc2.exe
Python path configuration:
  PYTHONHOME = 'D:\python_env\Python\envs\gvmls-py3'
  PYTHONPATH = (not set)
  program name = 'D:\python_env\out\deeppc2.exe'
  isolated = 0
  environment = 1
  user site = 1
  import site = 0
  sys._base_executable = 'D:\\python_env\\out\\deeppc2.exe'
  sys.base_prefix = 'D:\\python_env\\Python\\envs\\gvmls-py3'
  sys.base_exec_prefix = 'D:\\python_env\\Python\\envs\\gvmls-py3'
  sys.platlibdir = 'lib'
  sys.executable = 'D:\\python_env\\out\\deeppc2.exe'
  sys.prefix = 'D:\\python_env\\Python\\envs\\gvmls-py3'
  sys.exec_prefix = 'D:\\python_env\\Python\\envs\\gvmls-py3'
  sys.path = [
    'D:\\Anaconda3\\python39.zip',
    'D:\\python_env\\Python\\envs\\gvmls-py3\\DLLs',
    'D:\\python_env\\Python\\envs\\gvmls-py3\\lib',
    'D:\\python_env\\out',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00005ecc (most recent call first):
<no Python frame>

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
