### ISSUE TITLE
failed to find path @rpath/libc++.1.dylib

### ISSUE THREAD

**Issue by czkoko** [Nuitka/Nuitka#2458]
OS: MacOS 14 (M1)
Compiler: clang (xcode 15)
Python: 3.9 (no virtual env)
nuitka: 1.8.2

When I used the --standalone parameter to package, the following error occurred after the main program had been compiled:
```
Nuitka-Plugins:INFO: data-files: Included data file 'certifi/cacert.pem' due to package data for 'certifi'.
Nuitka-Plugins:INFO: data-files: Included data file 'torch/bin/protoc' due to package data directory 'bin' for 'torch'.
Nuitka-Plugins:INFO: data-files: Included data file 'torch/bin/protoc-3.13.0.0' due to package data directory 'bin' for 'torch'.
Nuitka-Plugins:INFO: data-files: Included data file 'torch/bin/torch_shm_manager' due to package data directory 'bin' for 'torch'.
Nuitka-Plugins:INFO: data-files: Included 8336 data files due to package data directory 'include' for 'torch'.
Nuitka-Plugins:INFO: dll-files: Found 6 files DLLs from torch installation.
FATAL: Error, failed to find path @rpath/libc++.1.dylib (resolved DLL to /Users/koko/Library/Python/3.9/lib/python/site-packages/coremltools/_deps/kmeans1d/libc++.1.dylib) for /Users/koko/Library/Python/3.9/lib/python/site-packages/coremltools/_deps/kmeans1d/_core.cpython-39-darwin.so from 'coremltools._deps.kmeans1d', please report the bug.
```

Coremltools is the core package I need. I didn't find the libc++.1.dylib file, and I ran the compiled program and got an error that couldn't import math.so.

No --standalone parameter works normally after compilation.

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
