### ISSUE TITLE
Request for assistance！

### ISSUE THREAD

**Issue by 17Reset** [Nuitka/Nuitka#2459]
I would like to ask if my program is a PyQt6 program and depends on a lot of large libraries such as transformers, Pytorch, numpy, and so on. Should I exclude the compilation of these libraries with --nofollow-import-to- when I package my project with Nuitka? After exclusion, do I need to manually copy the above libraries inside python\Lib\site-packages? Is there any parameter that can exclude the compilation and automatically include these libraries in the packaged project? If these libraries are not excluded, compiling to exe will consume a lot of time.

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
