### ISSUE TITLE
Question : Embedding dependencies like numpy in a compiled package

### ISSUE THREAD

**Issue by half1red** [Nuitka/Nuitka#2460]
Hello,

More a question than an issue, as I believe that what I am trying may be borderline.
I hope that I will be clear, as I am not as fluent as I'd like in english.

I am trying to build and provide a package with all dependencies embedded. My objectives are:
- to get a full control on all the dependencies and sub-dependencies. This is requested as per our quality assurance. I know that I can manage the versions requested for my dependencies, but it seems complicated for the sub-dependencies.
- to be able to provide a single file or folder to the colleagues who will use the package as a toolbox with everything in it.

I tried two small examples, and only one works. I take a folder named for example "pack" and I put a single __init__.py file in it.
- In the first example I write only `import tqdm`
- In the second example I write only `import numpy`

when I import pack (from pack.cp311-win_amd64.pyd in a separate folder), it works fine for the example with tqdm, and I can use pack.tqdm. It doesn't work with numpy :

```
C:\Users\USER\Documents\DTIMLT\code\test2>py -3.11
Python 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pack
Traceback (most recent call last):
  File "C:\Users\USER\Documents\DTIMLT\code\test2\numpy\__init__.py", line 144, in <module numpy>
  File "C:\Users\USER\Documents\DTIMLT\code\test2\numpy\__config__.py", line 4, in <module numpy.__config__>
  File "C:\Users\USER\Documents\DTIMLT\code\test2\numpy\core\__init__.py", line 24, in <module numpy.core>
  File "C:\Users\USER\Documents\DTIMLT\code\test2\numpy\core\multiarray.py", line 10, in <module numpy.core.multiarray>
  File "C:\Users\USER\Documents\DTIMLT\code\test2\numpy\core\overrides.py", line 8, in <module numpy.core.overrides>
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\USER\Documents\DTIMLT\code\test2\pack\__init__.py", line 1, in <module pack>
  File "C:\Users\USER\Documents\DTIMLT\code\test2\numpy\__init__.py", line 149, in <module numpy>
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
>>>
```

I am aware of issue #1792 and the conclusion stating "Python extension modules cannot include other extension modules. Including "numpy" is not what should you do, instead you should depend on it. Instead build a wheel and include whatever you want in that." But I am not sure that it was ok to dig up an one year old question.

Is it possible to compile a wheel and dependencies with complex package dependencies like numpy ?

The information asked in the issue template:

- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

>python -m nuitka --version
1.8.2
Commercial: None
Python: 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\USER\Documents\DTIMLT\code\test\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc). 

- How did you install Nuitka and Python
Python from official website, then python -m venv venv, then install all lib from pip

>pip freeze  (partial)
Nuitka==1.8.2
numpy==1.26.0
tqdm==4.66.1

Thank you very much for any answer you will be able to provide.

**Comment by kayhayen** [comment]
From what I understand, wheels can declare dependencies, yes. This not not your wheel support. Nuitka makes sure to compile what is included in your wheel. If a wheel that the compiled package is in and that depends on numpy, that will load just fine. The usual packaging guides will help you. Nuitka supports all wheel creation methods listed in the User Manual.

**Comment by half1red** [comment]
Ok, thank you for your answer and your time. I'll check that lead.
