### ISSUE TITLE
import matplotlib library cannot be compiled by Nuitka

### ISSUE THREAD

**Issue by emre84** [Nuitka/Nuitka#2463]
**The used environment:**

python -m nuitka --version
1.9rc3
Commercial: None
Python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\HP\AppData\Local\Programs\Python\Python37\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64\cl.exe (cl 14.3).

python -m pip list
Package                         Version
------------------------------- ---------
absl-py                         1.4.0
adb                             1.3.0
addict                          2.4.0
aiohttp                         3.8.4
aiosignal                       1.3.1
anyio                           3.6.2
argon2-cffi                     21.3.0
argon2-cffi-bindings            21.2.0
arrow                           1.2.3
asb                             0.3
astor                           0.8.1
astunparse                      1.6.3
async-timeout                   4.0.2
asynctest                       0.13.0
attrs                           22.2.0
backcall                        0.2.0
beautifulsoup4                  4.11.2
bleach                          6.0.0
cachetools                      5.3.0
certifi                         2019.9.11
cffi                            1.15.1
charset-normalizer              3.0.1
colorama                        0.4.6
coloredlogs                     15.0.1
contextlib2                     21.6.0
cryptography                    39.0.0
cycler                          0.11.0
Cython                          0.29.33
debugpy                         1.6.6
decorator                       5.1.1
defusedxml                      0.7.1
depthai                         2.20.2.0
dnspython                       2.3.0
docutils                        0.19
entrypoints                     0.4
fastjsonschema                  2.16.2
flatbuffers                     23.3.3
fonttools                       4.38.0
frozenlist                      1.3.3
gast                            0.2.2
google-auth                     2.16.1
google-auth-oauthlib            0.4.6
google-pasta                    0.2.0
grpcio                          1.51.3
h5py                            2.10.0
humanfriendly                   10.0
idna                            3.4
imageio                         2.25.0
importlib-metadata              6.0.0
importlib-resources             5.12.0
imutils                         0.5.4
install                         1.3.5
ipykernel                       6.16.2
ipython                         7.34.0
ipython-genutils                0.2.0
ipywidgets                      8.0.4
jaraco.classes                  3.2.3
jedi                            0.18.2
Jinja2                          3.1.2
jsonschema                      4.17.3
jstyleson                       0.0.2
jupyter                         1.0.0
jupyter_client                  7.4.9
jupyter-console                 6.6.1
jupyter_core                    4.12.0
jupyter-server                  1.23.6
jupyterlab-pygments             0.2.2
jupyterlab-widgets              3.0.5
keras                           2.11.0
Keras-Preprocessing             1.1.2
keyring                         23.13.1
Kivy                            2.1.0
kivy-deps.angle                 0.3.3
kivy-deps.glew                  0.3.1
kivy-deps.sdl2                  0.4.5
Kivy-Garden                     0.1.5
kiwisolver                      1.4.4
libclang                        15.0.6.1
libusb1                         3.0.0
lite                            0.1.5
lxml                            4.9.2
Markdown                        3.4.1
markdown-it-py                  2.2.0
MarkupSafe                      2.1.2
matplotlib                      3.5.3
matplotlib-inline               0.1.6
mdurl                           0.1.2
mistune                         2.0.5
more-itertools                  9.0.0
mpmath                          1.2.1
multidict                       6.0.4
nbclassic                       0.5.2
nbclient                        0.7.2
nbconvert                       7.2.9
nbformat                        5.7.3
nest-asyncio                    1.5.6
networkx                        2.6.3
notebook                        6.5.2
notebook_shim                   0.2.2
NudeNet                         2.0.9
Nuitka                          1.9rc3
numpy                           1.17.4
oauthlib                        3.2.2
onnx                            1.13.1
onnxruntime                     1.13.1
opencv-contrib-python           4.7.0.72
opencv-python                   4.6.0.66
opencv-python-headless          4.7.0.68
openvino                        2022.3.0
openvino-dev                    2022.3.0
openvino-telemetry              2022.3.0
opt-einsum                      3.3.0
ordered-set                     4.1.0
packaging                       23.0
pandas                          1.3.5
pandocfilters                   1.5.0
parso                           0.8.3
pickleshare                     0.7.5
Pillow                          9.4.0
pip                             23.2.1
pkginfo                         1.9.6
pkgutil_resolve_name            1.3.10
plyer                           2.1.0
progressbar2                    4.2.0
prometheus-client               0.16.0
prompt-toolkit                  3.0.37
protobuf                        3.19.6
protos                          0.1.0
psutil                          5.9.4
py3dns                          4.0.0
pyasn1                          0.4.8
pyasn1-modules                  0.2.8
pycparser                       2.21
pydload                         1.0.9
pygame                          2.1.2
Pygments                        2.14.0
PyJWT                           2.6.0
pyparsing                       3.0.9
pypiwin32                       223
pyreadline                      2.1
pyrsistent                      0.19.3
PySide6                         6.5.0
PySide6-Addons                  6.5.0
PySide6-Essentials              6.5.0
python-certifi-win32            1.6.1
python-dateutil                 2.8.2
python-utils                    3.4.5
python-version                  0.0.2
pytz                            2022.7.1
pyvirtualcam                    0.10.2
PyWavelets                      1.3.0
pywin32                         305
pywin32-ctypes                  0.2.0
pywinpty                        2.0.10
PyYAML                          6.0
pyzmq                           25.0.0
qtconsole                       5.4.0
QtPy                            2.3.0
readme-renderer                 37.3
requests                        2.28.2
requests-oauthlib               1.3.1
requests-toolbelt               0.10.1
rfc3986                         2.0.0
rich                            13.3.1
rsa                             4.9
scikit-image                    0.19.3
scipy                           1.7.3
Send2Trash                      1.8.0
setuptools                      67.4.0
setuptools-scm                  7.1.0
shiboken6                       6.5.0
six                             1.16.0
sniffio                         1.3.0
soupsieve                       2.4
sympy                           1.10.1
tensorboard                     2.11.2
tensorboard-data-server         0.6.1
tensorboard-plugin-wit          1.8.1
tensorflow                      2.11.0
tensorflow-estimator            2.11.0
tensorflow-intel                2.11.0
tensorflow-io-gcs-filesystem    0.30.0
tensorflow-object-detection-api 0.1.1
termcolor                       2.2.0
terminado                       0.17.1
texttable                       1.6.7
tf2onnx                         1.14.0
tflite                          2.10.0
tflite-runtime                  2.5.0
tflite2onnx                     0.4.1
tifffile                        2021.11.2
tinycss2                        1.2.1
tinydb                          4.7.1
tomli                           2.0.1
tornado                         6.2
tqdm                            4.65.0
traitlets                       5.9.0
turboactivate                   4.4.4.1
twilio                          7.16.2
twine                           4.0.2
Twisted                         16.2.0
twisted-iocpsupport             1.0.2
typing_extensions               4.4.0
urllib3                         1.26.14
validate-email                  1.3
wcwidth                         0.2.6
webencodings                    0.5.1
websocket-client                1.5.1
Werkzeug                        2.2.3
wheel                           0.38.4
widgetsnbextension              4.0.5
win10toast                      0.9
wrapt                           1.14.1
yarl                            1.9.2
zipp                            3.14.0
zope.interface                  6.0
zstandard                       0.20.0

**Nuitka Installation:**
`py -m pip install Nuitka-develop.zip`

**Nuitka Command:**
>`py -m nuitka --run --standalone --enable-plugin=pyside6  --follow-imports main.py`

**The code sample:**
import matplotlib; matplotlib.use('Agg')
import matplotlib.pyplot as plt  
```

**Error message:**
PASS 1: 0.0%|                         | 0/1, __main__Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\__main__.py", line 155, in <module>
    main()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\__main__.py", line 141, in main
    MainControl.main()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\MainControl.py", line 1091, in main
    _main()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\MainControl.py", line 951, in _main
    main_module = _createMainModule()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\MainControl.py", line 258, in _createMainModule
    optimizeModules(main_module.getOutputFilename())
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\optimizations\Optimization.py", line 344, in optimizeModules
    finished = makeOptimizationPass()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\optimizations\Optimization.py", line 300, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\optimizations\Optimization.py", line 176, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\optimizations\Optimization.py", line 136, in optimizeCompiledPythonModule
    considerUsedModules(module=module, pass_count=pass_count)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\importing\Recursion.py", line 469, in considerUsedModules
    using_module_name=module.module_name,
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\importing\Recursion.py", line 91, in recurseTo
    reason=reason,
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\importing\Recursion.py", line 57, in _recurseTo
    ImportCache.addImportedModule(module)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\importing\ImportCache.py", line 47, in addImportedModule
    Plugins.onModuleDiscovered(imported_module)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\plugins\Plugins.py", line 878, in onModuleDiscovered
    description=plugin.createPreModuleLoadCode(module)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\plugins\standard\MatplotlibPlugin.py", line 180, in createPreModuleLoadCode
    and self._getMatplotlibInfo().needs_matplotlibdata_env
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\plugins\standard\MatplotlibPlugin.py", line 82, in _getMatplotlibInfo
    ("matplotlibrc_filename", "matplotlib_fname()"),
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\plugins\PluginBase.py", line 1054, in queryRuntimeInformationMultiple
    feedback = check_output([sys.executable, "-c", cmd])
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\utils\Execution.py", line 141, in check_output
    raise NuitkaCalledProcessError(exit_code, cmd, output=output, stderr=stderr)
nuitka.utils.Execution.NuitkaCalledProcessError: Command '['C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python37\\python.exe', '-c', '\\\nfrom __future__ import print_function\nfrom __future__ import absolute_import\n\ntry:\n   \n   from matplotlib import matplotlib_fname, get_backend, __version__\n   try:\n       from matplotlib import get_data_path\n   except ImportError:\n       from matplotlib import _get_data_path as get_data_path\n   from inspect import getsource\nexcept ImportError:\n    import sys\n    sys.exit(38)\nprint(repr(matplotlib_fname()))\nprint("-" * 27)\nprint(repr(get_backend()))\nprint("-" * 27)\nprint(repr(get_data_path()))\nprint("-" * 27)\nprint(repr(__version__))\nprint("-" * 27)\nprint(repr(\'MATPLOTLIBDATA\' in getsource(get_data_path) or \'MATPLOTLIBRC\' in getsource(get_data_path)))\nprint("-" * 27)\n']' returned non-zero exit status 1. Output was b"'C:\\\\Users\\\\HP\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python37\\\\lib\\\\site-packages\\\\matplotlib\\\\mpl-data\\\\matplotlibrc'\r\n---------------------------". Error was b'Traceback (most recent call last):\r\n  File "<string>", line 18, in <module>\r\n  File "C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\matplotlib\\__init__.py", line 1172, in get_backend\r\n    return rcParams[\'backend\']\r\n  File "C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\matplotlib\\__init__.py", line 674, in __getitem__\r\n    plt.switch_backend(rcsetup._auto_backend_sentinel)\r\n  File "C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\matplotlib\\pyplot.py", line 262, in switch_backend\r\n    switch_backend(candidate)\r\n  File "C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\matplotlib\\pyplot.py", line 282, in switch_backend\r\n    class backend_mod(matplotlib.backend_bases._Backend):\r\n  File "C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\matplotlib\\pyplot.py", line 283, in backend_mod\r\n    locals().update(vars(importlib.import_module(backend_name)))\r\n  File "C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python37\\lib\\importlib\\__init__.py", line 127, in import_module\r\n    return _bootstrap._gcd_import(name[level:], package, level)\r\n  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import\r\n  File "<frozen importlib._bootstrap>", line 983, in _find_and_load\r\n  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked\r\n  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked\r\n  File "<frozen importlib._bootstrap_external>", line 728, in exec_module\r\n  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\r\n  File "C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\matplotlib\\backends\\backend_qtagg.py", line 12, in <module>\r\n    from .backend_qt import (\r\n  File "C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\matplotlib\\backends\\backend_qt.py", line 76, in <module>\r\n    for mod, key in [\r\n  File "C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\matplotlib\\backends\\backend_qt.py", line 76, in <listcomp>\r\n    for mod, key in [\r\nTypeError: int() argument must be a string, a bytes-like object or a number, not \'KeyboardModifier\''.

Note: I could not find an attachemtn option to attach my 'nuitka-crash-report.xml'. file.

**Comment by kayhayen** [comment]
So, matplotlib and PySide6 in these versions are incompatible.

In this code:

```
from __future__ import print_function
from __future__ import absolute_import

try:

   from matplotlib import matplotlib_fname, get_backend, __version__
   try:
       from matplotlib import get_data_path
   except ImportError:
       from matplotlib import _get_data_path as get_data_path
   from inspect import getsource
except ImportError:
    import sys
    sys.exit(38)
print(repr(matplotlib_fname()))
print("-" * 27)
print(repr(get_backend()))
print("-" * 27)
print(repr(get_data_path()))
print("-" * 27)
print(repr(__version__))
print("-" * 27)
print(repr('MATPLOTLIBDATA' in getsource(get_data_path) or 'MATPLOTLIBRC' in getsource(get_data_path)))
print("-" * 27)
```

it crashes on the `get_backend` call, due to PySide not matching the matplotlib backend expectations. Since it doesn't do it with an `ImportError` that bubbles up, and Nuitka cannot tell what backend is used. Your usage of `use` is not recognized by Nuitka, and a problem by itself, you should instead do it like that:

> https://matplotlib.org/stable/users/explain/figure/backends.html#selecting-a-backend

Setting `MPLBACKEND=Agg` worked for me to execute above code.

**Comment by kayhayen** [comment]
So, I am adding an error catch for that kind of mistake, and will make it error exit like this:

```
FATAL: matplotlib: Error, failed to detect matplotlib backend. Please set 'MPLBACKEND' during compilation.
```

This is given if the query fails.

And now the matplotlib plugin also hints you in the right direction, because it will give you an information if the default or configured plugin works, that it is indeed the one used, so you can know the need to switch it. That should make the matplotlib experience a little more smooth. Esp. as it seems that the default backend is not working the best anymore, and people switch to Agg ones manually a lot now.

**Comment by kayhayen** [comment]
So, it now says: 

> Nuitka-Plugins:INFO: matplotlib: Using as per 'MPLBACKEND' environment variable backend 'agg'.

That is due to me setting it to `Agg` but apparently that's not the real name, which shows that works. The compile time inspection code then inherits that environment and resolves it correctly, and the plugin will override any other `MPLBACKEND` value given from runtime environment variables.

**Comment by emre84** [comment]
Hi Kay,

Thanks a lot for your fast response as always. 

But am I missing any point? I modified my code as you recommended:
```
import matplotlib; matplotlib.use(MPLBACKEND='Agg')
import matplotlib.pyplot as plt
```
And I executed following command:
`
py -m nuitka --run --standalone --enable-plugin=pyside6  --follow-imports main.py`

But unfortunately I am still getting following error. Do I have to update my nuitka with development branch again?:

  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\__main__.py", line 155, in <module>
    main()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\__main__.py", line 141, in main
    MainControl.main()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\MainControl.py", line 1091, in main
    _main()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\MainControl.py", line 951, in _main
    main_module = _createMainModule()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\MainControl.py", line 258, in _createMainModule
    optimizeModules(main_module.getOutputFilename())
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\optimizations\Optimization.py", line 344, in optimizeModules
    finished = makeOptimizationPass()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\optimizations\Optimization.py", line 300, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\optimizations\Optimization.py", line 176, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\optimizations\Optimization.py", line 136, in optimizeCompiledPythonModule
    considerUsedModules(module=module, pass_count=pass_count)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\importing\Recursion.py", line 469, in considerUsedModules
    using_module_name=module.module_name,
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\importing\Recursion.py", line 91, in recurseTo
    reason=reason,
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\importing\Recursion.py", line 57, in _recurseTo
    ImportCache.addImportedModule(module)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\importing\ImportCache.py", line 47, in addImportedModule
    Plugins.onModuleDiscovered(imported_module)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\plugins\Plugins.py", line 878, in onModuleDiscovered
    description=plugin.createPreModuleLoadCode(module)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\plugins\standard\MatplotlibPlugin.py", line 180, in createPreModuleLoadCode
    and self._getMatplotlibInfo().needs_matplotlibdata_env
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\plugins\standard\MatplotlibPlugin.py", line 82, in _getMatplotlibInfo
    ("matplotlibrc_filename", "matplotlib_fname()"),
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\plugins\PluginBase.py", line 1054, in queryRuntimeInformationMultiple
    feedback = check_output([sys.executable, "-c", cmd])
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\utils\Execution.py", line 141, in check_output
    raise NuitkaCalledProcessError(exit_code, cmd, output=output, stderr=stderr)
nuitka.utils.Execution.NuitkaCalledProcessError: Command '['C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python37\\python.exe', '-c', '\\\nfrom __future__ import print_function\nfrom __future__ import absolute_import\n\ntry:\n   \n   from matplotlib import matplotlib_fname, get_backend, __version__\n   try:\n       from matplotlib import get_data_path\n   except ImportError:\n       from matplotlib import _get_data_path as get_data_path\n   from inspect import getsource\nexcept ImportError:\n    import sys\n    sys.exit(38)\nprint(repr(matplotlib_fname()))\nprint("-" * 27)\nprint(repr(get_backend()))\nprint("-" * 27)\nprint(repr(get_data_path()))\nprint("-" * 27)\nprint(repr(__version__))\nprint("-" * 27)\nprint(repr(\'MATPLOTLIBDATA\' in getsource(get_data_path) or \'MATPLOTLIBRC\' in getsource(get_data_path)))\nprint("-" * 27)\n']' returned non-zero exit status 1. Output was b"'C:\\\\Users\\\\HP\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python37\\\\lib\\\\site-packages\\\\matplotlib\\\\mpl-data\\\\matplotlibrc'\r\n---------------------------". Error was b'Traceback (most recent call last):\r\n  File "<string>", line 18, in <module>\r\n  File "C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\matplotlib\\__init__.py", line 1172, in get_backend\r\n    return rcParams[\'backend\']\r\n  File "C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\matplotlib\\__init__.py", line 674, in __getitem__\r\n    plt.switch_backend(rcsetup._auto_backend_sentinel)\r\n  File "C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\matplotlib\\pyplot.py", line 262, in switch_backend\r\n    switch_backend(candidate)\r\n  File "C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\matplotlib\\pyplot.py", line 282, in switch_backend\r\n    class backend_mod(matplotlib.backend_bases._Backend):\r\n  File "C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\matplotlib\\pyplot.py", line 283, in backend_mod\r\n    locals().update(vars(importlib.import_module(backend_name)))\r\n  File "C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python37\\lib\\importlib\\__init__.py", line 127, in import_module\r\n    return _bootstrap._gcd_import(name[level:], package, level)\r\n  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import\r\n  File "<frozen importlib._bootstrap>", line 983, in _find_and_load\r\n  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked\r\n  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked\r\n  File "<frozen importlib._bootstrap_external>", line 728, in exec_module\r\n  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\r\n  File "C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\matplotlib\\backends\\backend_qtagg.py", line 12, in <module>\r\n    from .backend_qt import (\r\n  File "C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\matplotlib\\backends\\backend_qt.py", line 76, in <module>\r\n    for mod, key in [\r\n  File "C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\matplotlib\\backends\\backend_qt.py", line 76, in <listcomp>\r\n    for mod, key in [\r\nTypeError: int() argument must be a string, a bytes-like object or a number, not \'KeyboardModifier\''.

**Comment by kayhayen** [comment]
No, you didn't get what I was saying. Newer Nuitka on factory might have instructed you better, and it's now on develop and will be in 1.9

**Comment by kayhayen** [comment]
Accidental close, keeping it open until release as usual.

**Comment by emre84** [comment]
Hi Kay,

Unfortunately I am still getting error. 

 **I have already installed development code today:**
`py -m nuitka --version`
1.9rc4
Commercial: None
Python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\HP\AppData\Local\Programs\Python\Python37\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64\cl.exe (cl 14.3).

**with following command:**
`py -m pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"`
WARNING: Ignoring invalid distribution -pencv-python (c:\users\hp\appdata\local\programs\python\python37\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\hp\appdata\local\programs\python\python37\lib\site-packages)
Collecting https://github.com/Nuitka/Nuitka/archive/develop.zip
  Using cached https://github.com/Nuitka/Nuitka/archive/develop.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: ordered-set>=4.1.0 in c:\users\hp\appdata\local\programs\python\python37\lib\site-packages (from Nuitka==1.9rc4) (4.1.0)
Requirement already satisfied: zstandard>=0.15 in c:\users\hp\appdata\local\programs\python\python37\lib\site-packages (from Nuitka==1.9rc4) (0.20.0)
WARNING: Ignoring invalid distribution -pencv-python (c:\users\hp\appdata\local\programs\python\python37\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\hp\appdata\local\programs\python\python37\lib\site-packages)

**My code:**
`import matplotlib; matplotlib.use(MPLBACKEND='Agg')`

**My nuitka command:**
`py -m nuitka --run --standalone --enable-plugin=pyside6  --follow-imports test_temp.py`

**My Error :message:**
Nuitka-Options:INFO: Used command line options: --run --standalone --enable-plugin=pyside6 --follow-imports test_temp.py
Nuitka-Options:INFO: Following all imports is the default for standalone mode and need not be specified.
Nuitka:WARNING: On Windows, support for input/output on the console Windows, does not work on non-UTF8 systems, unless
Nuitka:WARNING: Python 3.8 or higher is used but this is 3.7, so please consider upgrading, or disabling the console
Nuitka:WARNING: window for deployment.
Nuitka:WARNING:     Complex topic! More information can be found at
Nuitka:WARNING: https://nuitka.net/info/old-python-windows-console.html
Nuitka:INFO: Starting Python compilation with Nuitka '1.9rc4' on Python '3.7' commercial grade 'not installed'.
FATAL: matplotlib: Error, failed to detect matplotlib backend. Please set 'MPLBACKEND' during compilation.
Nuitka-Reports:INFO: Compilation report written to file 'nuitka-crash-report.xml'.
Nuitka-Reports:INFO: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug report.

**PS:**
If I remove "MPLBACKEND=" from add method(matplotlib.use('Agg')`, and compile, I still get the same error message as above.

Thanks a lot in advance.

**Comment by kayhayen** [comment]
It's interesting, why don't you get this:

> FATAL: matplotlib: Error, failed to detect matplotlib backend. Please set 'MPLBACKEND' during compilation.

Seems the message is unclear, or you do not read it.

**Comment by emre84** [comment]
Hi Kay, sure i have already read the error message. Therefore  i set „ MPLBACKEND“ in my use function.

Import matplotlib; matplotlib.use(MPLBACKEND='Agg')

Maybe there is a misunderstanding. If there is a nuitka paramter as „ MPLBACKEND“ für compilation command, then i will try that this evening.

thanks a lot in advance.

**Comment by kayhayen** [comment]
I have updated factory, it will give you a more clear error now.

**Comment by emre84** [comment]
Hi Kay,

I was getting still the same error this evening after pulling factory, but I guess the problem is that you forgot the error message commented out in nuitka/tracking.py file:
```
"""\
Error, failed to detect matplotlib backend. Please set 'MPLBACKEND' \
environment variable during compilation.""",
                    mnemonic="""\
https://matplotlib.org/stable/users/installing/environment_variables_faq.html#envvar-MPLBACKEND""",
```

Ok I will check https://matplotlib.org/stable/users/installing/environment_variables_faq.html website.

```
py -m nuitka --version
1.9rc4
Commercial: None
Python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\HP\AppData\Local\Programs\Python\Python37\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64\cl.exe (cl 14.3).
```

Thanks a lot.

**Comment by emre84** [comment]
Thanks Kay, I got the error message.

**Comment by kayhayen** [comment]
Part of the 1.9 release I just made.
