### ISSUE TITLE
Nuitka leaves unresolved symbol references when they can be easily resolved

### ISSUE THREAD

**Issue by yurivict** [Nuitka/Nuitka#2464]
In the below example Nuitka passes the "PROBLEM" line in the Cls2.mmm() body that calls the object that is not callable.
This later causes the run-time error.

In this case it is very easy to determine that Cls2.mmm is not callable, and to trigger a compile-time error at this line.

module1.py:
```
class Cls1():
    @property
    def p1():
        return Cls1.m1(self.m)
    def m1(x):
        if x == 1:
            return "x"
```

module2.py:
```
class Cls2():
    def mmm():
        return Cls1().p1() # PROBLEM!!! the uncaught mistake here: Cls1.p1 returns a string or None - both not callable!
```

**Comment by kayhayen** [comment]
This is currently not in the scope of Nuitka, monkey patching, meta classes, etc. all spoil what `Cls1` is going to be at any given moment. You are welcome to join the effort to optimize classes more statically be contibuting.

The focus however is never going to make incorrect code detected at compiled time, but correct code to be faster at run time I fear.

**Comment by yurivict** [comment]
> monkey patching, meta classes, etc. all spoil what Cls1 is going to be at any given moment. 

Our classes don't change over time.
This should help in optimizing situations like this.

**Comment by kayhayen** [comment]
Yes, thanks for pointing this out. Code enhancements of Nuitka would be the ideal followup.

**Comment by yurivict** [comment]
I am just reporting issues based on my experience with using Nuitka in the project @ $JOB.

In the project like I work on all code is static. Nuitka should have an option like "assume-classes-are-unmutable".
And in such case if, for example, some class doesn't have some requested symbol - this should be a hard error, not just an item to try to resolve at the runtime.

Otherwise I am not involved with anything Python-related and can't submit patches.
