### ISSUE TITLE
Error with extension modules in cryptography package when compiling in --module mode

### ISSUE THREAD

**Issue by gustavocmv** [Nuitka/Nuitka#2466]
# Environment Details

## Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.
> python -m nuitka --version
```
1.8.3
Commercial: None
Python: 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0]
Flavor: Anaconda Python
Executable: /home/gustavo/miniconda3/envs/compile/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.3
Version C compiler: /usr/bin/gcc (gcc).
```
## How did you install Nuitka and Python
1. I am using `conda 23.7.4`.
2. I created a new env with `conda create -n 'compile' 'python~=3.11'`, resulting in `Python 3.11.5`.
3. I followed up by installing Nuitka through pip with `pip install nuitka`, resulting in `nuitka 1.8.3` (as above).

## The specific PyPI names and versions
> python -m pip freeze
```
cffi==1.16.0
cryptography==41.0.4
Nuitka==1.8.3
ordered-set==4.1.0
pycparser==2.21
zstandard==0.21.0
```

# MWE
1. Create a file called `mymodule.py` with the following content:
```py
from cryptography import x509
print(x509)
```
2. Check it works properly. Run:
> python -c 'import mymodule'

It should print the following:
```
<module 'cryptography.x509' from '.../miniconda3/envs/compile/lib/python3.11/site-packages/cryptography/x509/__init__.py'>
```

3. Compile `mymodule.py` as with Nuitka:
  > python -m nuitka --module --include-package=cryptography mymodule.py

This will output the following:
```
Nuitka-Options:INFO: Used command line options: --module --include-package=cryptography mymodule.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.8.3' on Python '3.11' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.                                  
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.                                    
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 78 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 77 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 77
Nuitka:INFO: Keeping build directory 'mymodule.build'.
Nuitka:INFO: Successfully created 'mymodule.cpython-311-x86_64-linux-gnu.so'.
```
And will generate two output files: `mymodule.cpython-311-x86_64-linux-gnu.so` and `mymodule.pyi`.

4. Try to run the Nuitka compiled module. Move the output files to another directory (lets call it `binaries`) and run in that directory:
> python -c 'import mymodule'

This will output the following:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../binaries/mymodule.py", line 1, in <module mymodule>
    from cryptography import x509
    
  File ".../binaries/cryptography/x509/__init__.py", line 7, in <module cryptography.x509>
  File ".../binaries/cryptography/x509/certificate_transparency.py", line 11, in <module cryptography.x509.certificate_transparency>
ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._rust'
```
# Extra Info.
The `cryptography` package uses Rust bindings for this module. I guess the error is related to Nuitka not including the file `.../miniconda3/envs/compile/lib/python3.11/site-packages/cryptography/hazmat/bindings/_rust.abi3.so` in the output file `mymodule.cpython-311-x86_64-linux-gnu.so`.

**Comment by kayhayen** [comment]
When compiling to a module or a package, you should not include other packages, certainly not ones that use extension modules, that will just not work.

**Comment by gustavocmv** [comment]
@kayhayen thanks for the clarification.

To make sure I understood it, the proper way to do it would be to compile `mymodule.py` as a module without `--include-package=cryptography` and then just make sure to have `cryptography` in the python environment which will eventually import the compiled version of `mymodule`?

Thanks!

**Comment by kayhayen** [comment]
Yes, building a wheel will be your best choice. Create one first (but not with poetry as that doesn't work yet) without Nuitka and enable it as described in the User Manual. Wheels are also a standard for deployment wheels with data files, etc.
