### ISSUE TITLE
Missing dependencies for pyav need to be added

### ISSUE THREAD

**Issue by laggykiller** [Nuitka/Nuitka#2467]
test.py
```
import av

av_container = av.open("0.mp4")
print(av_container)
```

requirements.txt
```
av==10.0.0
nuitka==1.8.3
```

Also copy in any mp4 video named `0.mp4` into the `test.dist` directory after compiling. Here is a small 15KB `0.mp4` you may use for testing: https://github.com/Nuitka/Nuitka/assets/61652821/0bca7043-90b3-4795-9c0d-354dd17a48b7

Running without compililng: No problem
```
<av.InputContainer '0.mp4'>
```

Compiling 1 (Not work):
```
python -m nuitka --standalone --follow-imports test.py
```

Result 1 (Fail):
```
Traceback (most recent call last):
  File "D:\DOWNLO~1\IMAGEI~1\TEST~1.DIS\test.py", line 1, in <module>
  File "D:\DOWNLO~1\IMAGEI~1\TEST~1.DIS\av\__init__.py", line 36, in <module av>
  File "av\logging.pyx", line 40, in init av.logging
ModuleNotFoundError: No module named 'logging'
```

Compiling 2 (Not work):
```
python -m nuitka --standalone --follow-import --include-package=av test.py
```

Result 2 (Fail):
```
raceback (most recent call last):
  File "D:\DOWNLO~1\IMAGEI~1\TEST~1.DIS\test.py", line 3, in <module>
  File "av\container\core.pyx", line 401, in av.container.core.open
  File "av\container\input.pyx", line 80, in av.container.input.InputContainer.__cinit__
  File "av\codec\context.pyx", line 30, in av.codec.context.wrap_codec_context
ModuleNotFoundError: No module named 'av.video.codeccontext'
```

Compiling 3 (Works):
```
python -m nuitka --standalone --follow-imports --include-package=av --include-module=av.audio.codeccontext --include-module=av.video.codeccontext test.py
```

Result 3 (Success):
```
<av.InputContainer '0.mp4'>
```

Alternatively, modify `test.py` to:
```
import av
from av.audio import codeccontext
from av.video import codeccontext

av_container = av.open("0.mp4")
print(av_container)
```

Compiling 4 (Works):
```
python -m nuitka --standalone --follow-imports --include-package=av test.py
```

Result 4 (Success):
```
<av.InputContainer '0.mp4'>
```

Note that adding the following `nuitka.config.yaml` does not work:

```
- module-name: 'av'
  implicit-imports:
    - depends:
      - 'av.logging'
      - 'av.audio.codeccontext'
      - 'av.video.codeccontext'
```

Compiling 5 (Not work)
```
python -m nuitka --standalone --follow-imports --user-package-configuration-file=nuitka.config.yaml test.py
```

Result 5 (Fail)
```
Traceback (most recent call last):
  File "D:\DOWNLO~1\PYAV-T~1\TEST~1.DIS\test.py", line 1, in <module>
  File "D:\DOWNLO~1\PYAV-T~1\TEST~1.DIS\av\__init__.py", line 36, in <module av>
  File "av\logging.pyx", line 40, in init av.logging
ModuleNotFoundError: No module named 'logging'
```

As you can see, it is quite cumbersome to properly bundle pyav. Is there any simpler way to properly bundle pyav? Seems like there is no easy way to include compiled modules (pxd files) with Nuitka? I think Nuitka should make it easier for us to bundle pyav.

Note that I have read https://github.com/Nuitka/Nuitka/issues/2456 and that issue got closed due to not following issue template.

Also not sure if this got asked many times, but may I ask why not include all submodules of packages specified by `--include-package`? I understand that importing only submodules that the user imported can greatly reduce distribution size, but I think at the very least there should be a command line flag that allow importing all submodules of a package, and one would expect that `--include-package` has such behavior.

Another problem is files in `av.libs` are duplicated in the root directory of the distribution directory (e.g. libx265), resulting in bloat. This occurs in both builds that work and don't work. Remove those duplicate dlls in root directory does not affect functionality of av package.

- Nuitka version, full Python version, flavor, OS, etc.

  > python -m nuitka --version

```
1.8.3
Commercial: None
Python: 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
Flavor: CPython Official
Executable: D:\Downloads\imageio-nuitka-test\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\Hostx64\x64\cl.exe (cl 14.3).
```

- How did you install Nuitka and Python

Python from python.org, exe installer

Nuitka from pip

- The specific PyPI names and versions

  > python -m pip freeze

```
av==10.0.0
Nuitka==1.8.3
ordered-set==4.1.0
zstandard==0.21.0
```

**Comment by kayhayen** [comment]
You can thank the Cython usage of that package for hidden dependencies.

The `av.logging` is using stdlib `logging` but we don't see that. I believe your config is good, but probably just needs to point to `logging` for `av.logging` module.

**Comment by kayhayen** [comment]
I did some previous work of `av` apparently and it almost worked. At some point we stopped including `logging` by default as it pulls in a bunch of other stuff, so this now has to be told, and the codec stuff itself is new. I am going to add your example to Nuitka-Watch I think, since this package is really very vulnerable due to its Cython usage.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
btw, thanks for taking the time to make a proper report, esp. with example AVI. I do not get how the asset file works. Is that somehow a github attachment link?

**Comment by laggykiller** [comment]
Thanks for your hard work! I just drag and dropped the video file into the text box in issue reporting, and it get uploaded like magic

**Comment by laggykiller** [comment]
Tested with factory version just now, can confirm that pyav dependencies are added without additional flags.

---

btw I also did some testing with imageio==2.31.5
```
import imageio.v3

t = imageio.v3.imopen('0.mp4', plugin='pyav', io_mode='r')
```

Compiling with `python -m nuitka --standalone --follow-imports --include-package=av test.py`

Running compiled version fails with:

```
Traceback (most recent call last):
  File "/Users/mcchau/Downloads/av-test/test.app/Contents/MacOS/test.py", line 8, in <module>
  File "/Users/mcchau/Downloads/av-test/test.app/Contents/MacOS/imageio/core/imopen.py", line 156, in imopen
ImportError: The `pyav` plugin is not installed. Use `pip install imageio[pyav]` to install it.
```

While it is total expected that I have to add `--include-package=av`, I have to add `--include-package=imageio` to make the compiled version work.

Is this a feature or bug to ignore `imageio.plugins`? It only contains python codes for binding to pyav, pillow and other library. I think adding and ignoring `imageio.plugins` are both sensible options. If it is a bug, please tell me so that I can open a new issue.

**Comment by kayhayen** [comment]
Please make new issues separately, I do not track or act on stray comments for efficiency reasons.

**Comment by laggykiller** [comment]
Sure, opened in https://github.com/Nuitka/Nuitka/issues/2472

**Comment by laggykiller** [comment]
It seems like files in `av.libs` are still duplicated in the root directory of the distribution directory (e.g. libx265), resulting in bloat. Removing those duplicate dlls in root directory does not affect functionality of av package:

```
for i in os.listdir('sticker-convert.dist/av.libs'):
    file_path = os.path.join('sticker-convert.dist', i)
    if os.path.isfile(file_path):
        os.remove(file_path)
```

**Comment by kayhayen** [comment]
There is no DLL config for `av`, maybe the delvewheel plugin is in action. It does put DLLs below the `site-packages` folder, but probably then they are not deduplicated when extension modules, potentially even from other packages use them. Does it happen with the given example already?

**Comment by kayhayen** [comment]
This code actually should catch that, but it is guarded by a check for same dest path, so it won't do it.

```
            # Check that if a DLL has the same name, if it's identical, then it's easy, we just
            # want to remember, therefore we convert to an ignored type.
            if haveSameFileContents(
                entry_point.source_path, standalone_entry_point.source_path
            ):
                entry_point = _makeIgnoredEntryPoint(entry_point)
                break
```

**Comment by kayhayen** [comment]
Checking the compilation report, for source  path, on Windows, the report path at least is short, which shouldn't be, I think this needs to be avoided. We hand paths to dependency walker in short form, since it's really bad with encoding, but we revert back to long paths, at least sometimes.

**Comment by kayhayen** [comment]
Ok, with this added, it becomes apparent, that the source paths are identical, which kind of is not handled, but duplication is allowed:

```
        if areSamePaths(entry_point.dest_path, standalone_entry_point.dest_path):
            if areSamePaths(
                entry_point.source_path, standalone_entry_point.source_path
            ):
                return
```

So, question becomes, what to do if we have DLLs added in 2 forms. Very likely one is going to be top level and the other is not. For delvewheel, the directory is largely a cleanup, but I think I saw cases where that wasn't true, and the folder name was kind of expected.

**Comment by kayhayen** [comment]
```
grep compilation-report.xml -e libxml2-2-d596991493c6defab3e6bd0ef87481ec
  <included_dll name="libxml2-2-d596991493c6defab3e6bd0ef87481ec.dll" dest_path="av.libs\libxml2-2-d596991493c6defab3e6bd0ef87481ec.dll" 
      source_path="${sys.prefix}\lib\site-packages\av.libs\libxml2-2-d596991493c6defab3e6bd0ef87481ec.dll"#
      package="av" ignored="no" reason="needed by 'av'" />
  <included_dll name="libxml2-2-d596991493c6defab3e6bd0ef87481ec.dll" dest_path="libxml2-2-d596991493c6defab3e6bd0ef87481ec.dll" 
      source_path="${sys.prefix}\lib\site-packages\av.libs\libxml2-2-d596991493c6defab3e6bd0ef87481ec.dll" 
      package="av" ignored="no" reason="Used by 'av.libs\avdevice-59-29229d167f4aaf2f3cdc4f830a69ecac.dll'" />
````

**Comment by kayhayen** [comment]
So, the used by DLL doesn't inherit the dest path, which is caused by this bit of code:

```
            # TODO: If used by a DLL from the same folder, put it there,
            # otherwise top level, but for now this is limited to the case where
            # it is required that way only, because it broke other things.
            if standalone_entry_point.package_name == "openvino" and areInSamePaths(
                standalone_entry_point.source_path, used_dll
            ):
                dest_path = os.path.normpath(
                    os.path.join(
                        os.path.dirname(standalone_entry_point.dest_path),
                        os.path.basename(used_dll),
                    )
                )
            else:
                dest_path = os.path.basename(used_dll)
```

So `openvino` was insisting on the top level stuff, but doing it generally caused DLLs to not be found, I think in case of them used by other packages. It seems `av`  is purposefully avoiding to use other DLLs by making them unique, which is bad, but we can add it to that list. That TODO might be impossible to solve.

**Comment by kayhayen** [comment]
On factory and in 1.8.4 the duplication will not be done anymore, at least not for `av`, but I guess we should add something that informs us of it, and maybe even a symlink style de-duplication step. However, if for inside DLLs, relative paths are used, symlinks might break some platforms, so I am hesitant for now to go there.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.8.4 that I just made.
