### ISSUE TITLE
Support for rlottlie-python needs DLLs added (was: DLLs found by `--list-package-dlls` but not included unless specified)

### ISSUE THREAD

**Issue by laggykiller** [Nuitka/Nuitka#2468]
I discovered this while trying to bundle in a simple ctypes library I wrote: https://github.com/laggykiller/rlottie-python

It requires `rlottie.dll` to work, which is included inside the package.

test.py
```
from rlottie_python.rlottie_wrapper import LottieAnimation

test = LottieAnimation()
print(test)
```

requirements.txt
```
Nuitka==1.8.3
ordered-set==4.1.0
Pillow==10.0.1
rlottie-python==1.1.9
zstandard==0.21.0
```

Running without compiling (Success):
```
<rlottie_python.rlottie_wrapper.LottieAnimation object at 0x00000130B3F57A90>
```

Compiling 1 (Not work):
```
nuitka --standalone --follow-imports --report=report.xml test.py
```

Running 1 (Fails):
```
Traceback (most recent call last):
  File "D:\DOWNLO~1\RLOTTI~1\TEST~1.DIS\test.py", line 3, in <module>
  File "D:\DOWNLO~1\RLOTTI~1\TEST~1.DIS\rlottie_python\rlottie_wrapper.py", line 53, in __init__
  File "D:\DOWNLO~1\RLOTTI~1\TEST~1.DIS\rlottie_python\rlottie_wrapper.py", line 84, in _load_lib
  File "D:\DOWNLO~1\RLOTTI~1\TEST~1.DIS\ctypes\__init__.py", line 376, in __init__
FileNotFoundError: Could not find module 'rlottie.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

Note that running `nuitka --list-package-dlls=rlottie_python` does detect the dll:
```
Nuitka-Tools:INFO: Checking package directory 'D:\Downloads\rlottie-test\venv\Lib\site-packages\rlottie_python' .. 
D:\Downloads\rlottie-test\venv\Lib\site-packages\rlottie_python
  rlottie.dll
Nuitka-Tools:INFO: Found 1 DLLs.
```

To make it work, I have to add `rlottie_python.config.yml`:
```
- module-name: 'rlottie_python'
  dlls:
    - from_filenames:
        prefixes:
          - 'rlottie*'
          - 'librlottie*'
```

Compiling 2 (Success):
```
nuitka --standalone --follow-imports --report=report.xml --user-package-configuration-file=rlottie_python.config.yml test.py
```

Running 2 (Success):
```
<rlottie_python.rlottie_wrapper.LottieAnimation object at 0x00000130B3F57A90>
```

I don't understand why I have to explicitly specify what dll to include using `rlottie_python.config.yml`, even if nuitka detected that dll. Is this a feature or a bug?

If it is a feature to prevent nuitka fail to compile when it encounters some special dll, I think it is a bad feature, as not including the dll has a greater chance of causing failure than including the dll. I would suggest including all dll unless there is an entry for a module in `standard.nuitka-package.config.yml`, in which case follow the instructions in the yml for determining which dll to include.

If it is a feature to reduce bloat, I also think that is a bad feature, as bloated executable is better than a not working executable.

If it is a bug, please look into this, thanks!

- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version

```
1.8.3
Commercial: None
Python: 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
Flavor: CPython Official
Executable: D:\Downloads\imageio-nuitka-test\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\Hostx64\x64\cl.exe (cl 14.3).
```

- How did you install Nuitka and Python

Python from python.org, exe installer

Nuitka from pip

- The specific PyPI names and versions

  > python -m pip freeze

```
Nuitka==1.8.3
ordered-set==4.1.0
Pillow==10.0.1
rlottie-python==1.1.9
zstandard==0.21.0
```

**Comment by kayhayen** [comment]
It's a feature. The tool to scan for DLLs makes it easy to discover required DLLs. Including all DLLs by default would be extremely over the edge for some packages and cause unnecessary bloat. 

Interestingly you have not understood what a prefix is. It's not necessary to do the `*` as that's implied.

**Comment by kayhayen** [comment]
I am adding this, should work for you:

```
- module-name: 'rlottie_python.rlottie_wrapper'
  dlls:
    # TODO: The "lib" difference out to be handled automatically.
    - from_filenames:
        prefixes:
          - 'rlottie'
      when: 'win32'
    - from_filenames:
        prefixes:
          - 'librlottie'
      when: 'not win32'
```

The difference in the prefix for DLLs on Windows vs. non-Windows and in general should be handled more gracefully, make with an optional "lib*" applied in all cases.

**Comment by kayhayen** [comment]
I now remember, why that's not as easy, at least on Linux, extension modules and DLLs are harder to distinguish and might match exactly. When listing the package DLLs we check against that, namely if something is not really a DLL, but an extension module, in which case we skip it, on other platforms we have no such detection, and sometimes DLLs are masked by filename as modules, for supposedly easier packaging or locating them at runtime via find_spec and the like.

But given a proper implementation of `getDllExportedSymbols`  for all platforms, we could in theory discover DLLs of a package reliably and inform the user about it, etc. but that's a bunch of effort, necessary for Windows and macOS both, that I wasn't willing to do myself yet, but be my guest if you care sufficiently, which you may not.

Right now this prevents us from doing using `isExtensionModule` for real.

```
            if exported_symbols is None:
                return None

            return (
                "%s%s" % ("init" if str is bytes else "PyInit_", module_name.asString())
                in exported_symbols
            )

```

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by laggykiller** [comment]
Nice work! But would it be nice if there is an option that allow user specify which package to include all dll? If the user want to try their luck to include all dll in package and make it work, just let them shoot their own foot?

**Comment by kayhayen** [comment]
Right now there is no portable way of telling what a DLL is as I tried to explain. Once there is, warnings and options like that can be done, yes.

**Comment by laggykiller** [comment]
I get what you mean now. Extension modules could be detected by [pkgutil.walk_packages](https://docs.python.org/3/library/pkgutil.html#pkgutil.walk_packages), right? If we get a list of library files under the packge root, then subtract those discovered by `pkgutil.walk_packages`, would we be left with a list of DLL that we can safely assume that is not extension modules and just a plain old DLL?

**Comment by laggykiller** [comment]
Here is a code snippet:
```python
from pkgutil import walk_packages
import importlib
import os

LIB_EXT = ('.dylib', '.so', '.dll', '.pyx', '.pyd')

def get_non_extension_lib(pkg):
    return [i for i in get_all_lib(pkg) if i not in get_extension_lib(pkg)]

def get_extension_lib(pkg):
    pkg_mod = importlib.import_module(pkg)
    libs = []
    for i in walk_packages(pkg_mod.__path__, pkg_mod.__name__ + '.'):
        if i.ispkg == True:
            continue
        
        lib_path = importlib.import_module(i.name).__file__
        if os.path.splitext(lib_path)[1] in LIB_EXT:
            libs.append(lib_path)

    return libs


def get_all_lib(pkg):
    pkg_mod = importlib.import_module(pkg)
    libs = []
    for dirpath, dirnames, filenames in os.walk(os.path.dirname(pkg_mod.__file__)):
        if '__pycache__' in dirpath:
            continue
        for f in filenames:
            if os.path.splitext(f)[1] in LIB_EXT:
                lib_path = os.path.join(dirpath, f)
                libs.append(lib_path)
    
    return libs

# print(get_all_lib('av'))
# print(get_extension_lib('av'))
print(get_non_extension_lib('av'))
```

**Comment by kayhayen** [comment]
No, these things all work on only filenames, and as such are useless. I am seeking to recognize DLLs that masked as extension modules by wrong filenames on Windows/macOS, and to decide extension module vs. normal DLL for filenames that do not allow to distinuish it. `librlottie.so` on Linux can be a DLL or an extension module, and you have to check it on the inside. And same for `something.pyd`, it might be a DLL only, and not an extension module at all. The only thing you can say is that "x.dll" or x.dylib" is never going to be an extension module, but that's then only a partial answer, which always comes at a price.

The only way to tell is to look at the exported symbols of the DLL (extension modules are DLLs with specific exported name), and then you know it. Listing the exported symbols of a Windows DLL and a macOS DLL is what is needed, then we can enhance the function that lists the DLLs of a package to not be unreliable.

Python doesn't care if it returns non-extension modules from your walk, they will just not import, and that's your problem for attempting it.

**Comment by laggykiller** [comment]
Sorry, I don't get it, is there any example where pkgutil.walk_packages report a dll that is actually not an importable extension module?

**Comment by kayhayen** [comment]
I see and I was not aware of that. I was falsely assuming it would leave it to the user to try the import. It also means we cannot use it or do you think that attempting to, and actually going to import all modules and DLLs during compile time is a good idea? I do not waste much of any thought on entertaining that if an offline solution is available.

Nuitka's version of this, as you can see in its code, doesn't do any importing, and still decides it, albeit only on Linux. And actually, we are not supposed to care if it's importable during compile time, or raises an exception. Code often provides environment that makes them usable at runtime in the first place.

**Comment by laggykiller** [comment]
On second thought, yes you are right. My solution won't be feasible during cross-compiling, which is something I am dealing with right now and will open another issue shortly... Back to the drawing board

**Comment by laggykiller** [comment]
How about this? It uses [lief](https://github.com/lief-project/LIEF) to check if it is python library without importing.

According to https://docs.python.org/3/faq/windows.html#is-a-pyd-file-the-same-as-a-dll:

> If you have a DLL named foo.pyd, then it must have a function PyInit_foo(). You can then write Python “import foo”, and Python will search for foo.pyd (as well as foo.py, foo.pyc) and if it finds it, will attempt to call PyInit_foo() to initialize it.

If there is `PyInit_*` function in a library file, then it must be a python extension module.

```
import os
import site
import lief

LIB_EXT = ('.dylib', '.so', '.dll', '.pyd')

def is_py_module(lib_path):
    lib = lief.parse(lib_path)
    for i in lib.exported_functions:
        if 'PyInit_' in i.name:
            return True
        
    return False

def get_pkg_root(pkg):
    for site_package_dir in site.getsitepackages():
        if pkg in os.listdir(site_package_dir):
            pkg_root = os.path.join(site_package_dir, pkg)
            return pkg_root
    
    return None

def get_non_extension_lib(pkg):
    extension_libs = get_extension_lib(pkg)
    all_libs = get_all_lib(pkg)
    return [i for i in all_libs if i not in extension_libs]

def get_extension_lib(pkg):
    pkg_root = get_pkg_root(pkg)
    libs = []
    for dirpath, dirnames, filenames in os.walk(pkg_root):
        if '__pycache__' in dirpath:
            continue
        for f in filenames:
            if os.path.splitext(f)[1] in LIB_EXT:
                lib_path = os.path.join(dirpath, f)
                is_py_module(lib_path)

    return libs

def get_all_lib(pkg):
    pkg_root = get_pkg_root(pkg)
    libs = []
    for dirpath, dirnames, filenames in os.walk(pkg_root):
        if '__pycache__' in dirpath:
            continue
        for f in filenames:
            if os.path.splitext(f)[1] in LIB_EXT:
                lib_path = os.path.join(dirpath, f)
                libs.append(lib_path)
    
    return libs

# print(get_all_lib('av'))
# print(get_extension_lib('av'))
print(get_non_extension_lib('av'))
```

This should work even for cross-compiling situation!

**Comment by kayhayen** [comment]
So, `dumpbin` is MSVC and can be used. It has output like this

```
C:\Users\kayha\repos\Py2C>dumpbin -exports Mini2.cp310-win_amd64.pyd
Microsoft (R) COFF/PE Dumper Version 14.34.31937.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file Mini2.cp310-win_amd64.pyd

File Type: DLL

  Section contains the following exports for Mini2.cp310-win_amd64.pyd

    00000000 characteristics
    FFFFFFFF time date stamp
        0.00 version
           1 ordinal base
           1 number of functions
           1 number of names

    ordinal hint RVA      name

          1    0 000023A0 PyInit_Mini2

  Summary

        6000 .data
        3000 .pdata
       11000 .rdata
        1000 .reloc
        1000 .rsrc
       30000 .text
        1000 _RDATA

```

That should be easy enough to parse as well. The bad thing is that for MinGW64, the `nm.exe` says there were no symbols. So that would make us require MSVC, which is kind of a no-go.

**Comment by laggykiller** [comment]
but would it fail if it is analyzing libraries during cross-compiling? Just now I have done a small experiment, while nm on x86_64 macOS is able to find symbols in arm64 macOS library, it fails to find symbols from linux library. But yeah, using tools like nm would be fast.

**Comment by kayhayen** [comment]
So, `objdump` does this for MinGW64, does a bunch of output with `-p` and among that this

```
[Ordinal/Name Pointer] Table
        [   0] PyInit_Mini2
```

Actually deciding which one to use on Windows, could be hard. We go to the compiler decision inside Scons relatively late. We could of course do what we do for `--version` output of Nuitka and call that, but that's so slow to do it multiple times, I wonder if we can maybe have a cache of the MSVC detection anyway, my CI and myself surely would appreciate even a drop of seconds there anyway.

**Comment by kayhayen** [comment]
For cross compilation, I would expect a cross compiler tool chain to be present. I think objdump and the like have support for multiple platforms builtin, and the cross compilers of MSVC also should not be shocked to see the other format, so I am good with that.

**Comment by kayhayen** [comment]
I will close this once 1.8.4 is out and resume discussion in #2470 about the new feature.

**Comment by laggykiller** [comment]
Tested factory version just now, can confirm that librlottie is included without my own `rlottie_python.config.yml`

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.8.4 that I just made.
