### ISSUE TITLE
Missing GDK DLL(s) for windows standalone build with msys2

### ISSUE THREAD

**Issue by hacklschorsch** [Nuitka/Nuitka#2471]
I am trying to package [gtimelog](https://github.com/gtimelog/gtimelog), a Python + GTK application, for Windows.
I got it running fine using [msys2](https://www.msys2.org/docs/python/), but it doesn't run standalone - it seems nuitka cannot find all relevant DLLs.

----

- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

> python -m nuitka --version

```
$ python -m nuitka --version
1.8
Commercial: None
Python: 3.11.5 (main, Sep 28 2023, 19:43:22)  [GCC 13.2.0 64 bit (AMD64)]
Flavor: MSYS2 MinGW
Executable: C:/msys64/mingw64/bin/python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:/msys64/mingw64/bin/gcc.exe (gcc).
```

- How did you install Nuitka and Python

1. I installed msys2 using their installer on Windows 11 pro and following [the msys2 guidelines](https://www.msys2.org/#installation) and [this micro howto to make sure GTK worked](https://stackoverflow.com/questions/33862049/python-cannot-install-pygobject/54795222#54795222).  I used the default paths (`C:\msys64\`).
2. In the msys2-provided mintty terminal emulator & default shell I cloned [gtimelog](https://github.com/gtimelog/gtimelog) into my $HOME
3. To make it run, I had to install a few libraries, most of which I found in the [pygobject docs](https://pygobject.readthedocs.io/en/latest/devguide/dev_environ.html#windows-dep):
```
pacman -S --needed --noconfirm base-devel mingw-w64-x86_64-toolchain git \
   mingw-w64-x86_64-python3 mingw-w64-x86_64-python3-cairo \
   mingw-w64-x86_64-gobject-introspection mingw-w64-x86_64-libffi
```
Additionally - not sure if all of these are required, but I think these are the ones I got (hope I am not missing anything):

```
pacman -S msys2-runtime-devel
pacman -S mingw-w64-x86_64-python-cairo
pacman -S mingw-w64-x86_64-libsecret
pacman -S mingw-w64-x86_64-libsoup
pacman -S mingw-w64-x86_64-python-nuitka
```
4. To get gtimelog to run:
In the cloned repository directory I ran `make run` to create .mo and GSettings schema files.
After this, I could run gtimelog by issueing: `python gtimelog`

5. Then, by reading docs and trial and error, I got nuitka to build this into a standalone. Again, in the repo clone directory:
```PYTHONPATH=src python -m nuitka --standalone --follow-imports --onefile --include-package-data=gtimelog --show-anti-bloat-changes --show-modules gtimelog```
This results in a 9.4 MB `gtimelog.exe`, which works when started in the msys2 shell or outside of the shell with the generated `gtimelog.cmd` which sets some paths:
```
set PATH=c:/msys64/mingw64/bin;%PATH%
set PYTHONHOME=C:/msys64/mingw64
"%~dp0.\gtimelog.exe" %*
```
The generated `gtimelog.exe` however doesn't run when I start it without these paths set.

- The specific PyPI names and versions

  > python -m pip freeze

```
$ python -m pip freeze
C:/msys64/mingw64/bin/python.exe: No module named pip
```

Here's a gist of the output of `pacman -Q --info` instead: https://gist.github.com/hacklschorsch/f649d8e8a398906bdc218d98d3aafb25

Here's the error I am getting:

```
C:\msys64\home\Flo\gtimelog>.\gtimelog.exe

** (process:32464): WARNING **: 16:11:42.781: Failed to load shared library 'libgdk-3-0.dll' referenced by the typelib: 'libgdk-3-0.dll': The specified module could not be found.
Traceback (most recent call last):
  File "C:\Users\Flo\AppData\Local\Temp\ONEFIL~1\gtimelog", line 13, in <module>
    from gtimelog.main import main  # noqa: E402

  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Flo\AppData\Local\Temp\ONEFIL~1\gtimelog/main.py", line 72, in <module gtimelog.main>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 676, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 573, in module_from_spec
  File "C:\Users\Flo\AppData\Local\Temp\ONEFIL~1\gi/importer.py", line 147, in create_module
  File "C:\Users\Flo\AppData\Local\Temp\ONEFIL~1\gi/overrides/__init__.py", line 118, in load_overrides
  File "importlib.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Flo\AppData\Local\Temp\ONEFIL~1\gi/overrides/Gdk.py", line 91, in <module gi.overrides.Gdk>
  File "C:\Users\Flo\AppData\Local\Temp\ONEFIL~1\gi/overrides/__init__.py", line 195, in override
AssertionError
```

**Comment by kayhayen** [comment]
I already have an example, that I think also covered Cairo usage. This should work from git top level (image file), but I think it says I do not have gtk or gdk, what package would that be? I would like to start out by assertion that what worked so far is working, before maybe finding a difference.

```
import cairo
import gi
from gi.repository import Gdk, Gtk

gi.require_version("Gtk", "3.0")
gi.require_version("Gdk", "3.0")
Gtk.init()

image = cairo.ImageSurface.create_from_png("doc/images/Nuitka-Logo-Symbol.png")
region = Gdk.cairo_region_create_from_surface(image)

print("All OK")
```

**Comment by hacklschorsch** [comment]
I think your reproducer is correct.

----

In a clone of the current Nuitka develop branch, this is what I get:

`$ python reproducer.py`
```
C:/msys64/home/Flo/nuitka-gdk-dll-reproducer/Nuitka/reproducer.py:3: PyGIWarning: Gdk was imported without specifying a version first. Use gi.require_version('Gdk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gdk, Gtk
C:/msys64/home/Flo/nuitka-gdk-dll-reproducer/Nuitka/reproducer.py:3: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gdk, Gtk
All OK
```

Compiling:

`$ python -m nuitka --standalone --follow-imports --onefile reproducer.py`
```
Nuitka-Options:INFO: Used command line options: --standalone --follow-imports --onefile reproducer.py
Nuitka-Options:INFO: Following all imports is the default for onefile mode and need not be specified.
Nuitka:INFO: Starting Python compilation with Nuitka '1.9rc4' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:INFO: anti-bloat: Not including '_bisect' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka-Plugins:INFO: anti-bloat: Not including '_json' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 27 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 27 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 27
Nuitka-Plugins:INFO: gi: Included 37 data files due to typelib files for gi modules.
Nuitka-Postprocessing:INFO: Creating single file from dist folder, this may take a while.
Nuitka-Onefile:INFO: Running bootstrap binary compilation via Scons.
Nuitka-Scons:INFO: Onefile C compiler: gcc (gcc).
Nuitka-Scons:INFO: Onefile linking program with 1 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 1 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 1
Nuitka-Onefile:INFO: Using compression for onefile payload.
Nuitka-Onefile:INFO: Onefile payload compression ratio (30.49%) size 39041642 to 11905569.
Nuitka-Onefile:INFO: Keeping onefile build directory 'reproducer.onefile-build'.
Nuitka:INFO: Keeping dist folder 'reproducer.dist' for inspection, no need to use it.
Nuitka:INFO: Keeping build directory 'reproducer.build'.
Nuitka:INFO: Successfully created 'reproducer.exe'.
```

Similar to my problem, the compiled .exe works from within the msys interactive shell: 

`$ ./reproducer.exe`
```
C:\msys64\tmp\ONEFIL~1\reproducer.py:3: PyGIWarning: Gdk was imported without specifying a version first. Use gi.require_version('Gdk', '3.0') before import to ensure that the right version gets loaded.
C:\msys64\tmp\ONEFIL~1\reproducer.py:3: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
All OK
```

And as expected, the same behavior as I had in a cmd w/o the necessary environment PATHs set:

`.\reproducer.exe`
```
** (process:38716): WARNING **: 09:44:50.086: Failed to load shared library 'libgdk-3-0.dll' referenced by the typelib: 'libgdk-3-0.dll': The specified module could not be found.
Traceback (most recent call last):
  File "C:\Users\Flo\AppData\Local\Temp\ONEFIL~1\reproducer.py", line 3, in <module>
    from gi.repository import Gdk, Gtk

  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 676, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 573, in module_from_spec
  File "C:\Users\Flo\AppData\Local\Temp\ONEFIL~1\gi/importer.py", line 147, in create_module
  File "C:\Users\Flo\AppData\Local\Temp\ONEFIL~1\gi/overrides/__init__.py", line 118, in load_overrides
  File "importlib.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Flo\AppData\Local\Temp\ONEFIL~1\gi/overrides/Gdk.py", line 91, in <module gi.overrides.Gdk>
  File "C:\Users\Flo\AppData\Local\Temp\ONEFIL~1\gi/overrides/__init__.py", line 195, in override
AssertionError
```

**Comment by hacklschorsch** [comment]
> This should work from git top level (image file), but I think it says I do not have gtk or gdk, what package would that be?

Sorry, seems I don't have my notes together after all :/

`$ history | grep 'g[dt]k'`
```
pacman -S mingw-w64-x86_64-gtk3 mingw-w64-x86_64-python-gobject
```

**Comment by kayhayen** [comment]
So, my original example runs just fine for me after updating all of MSYS2 and using factory Nuitka, so this must be new in some way, and sure enough, the GDK DLL mentioned is not included.

**Comment by kayhayen** [comment]
it seems my example is too much cairo leaning maybe, the GTK DLL is also not included (anymore). It seems they changed the DLLs to have a `lib` prefix not seen before. I wonder if find it again will make the GDK DLL be included as a dependency, so we are not having a GDK DLL issue here, but a GTK DLL issue that shows as a GDK DLL issue first, and yes indeed, that seems to be the case, so that's probably your issue.

**Comment by hacklschorsch** [comment]
Thanks @kayhayen!  Please mention if there's anything I can do to help.

**Comment by kayhayen** [comment]
Thanks for your report @hacklschorsch , this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by hacklschorsch** [comment]
Running the current `factory` (05306821d) yields a working standalone executable of the reproducer for me.

Gtimelog exhibits a new problem as well, so that's progress :)

Thank you!

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.8.4 that I just made. However, the further changes of your PR will be in 1.9 only and are on develop right now.
