### ISSUE TITLE
tensorflow import crashes with No module named 'tensorflow.python.data.ops.shuffle_op error

### ISSUE THREAD

**Issue by emre84** [Nuitka/Nuitka#2473]
**The used environment:**

`python3.8 -m nuitka --version`
1.9rc4
Commercial: None
Python: 3.8.10 (v3.8.10:3d8993a744, May  3 2021, 08:55:58) 
Flavor: CPython Official
Executable: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8
OS: Darwin
Arch: x86_64
Version C compiler: /usr/bin/clang (clang).

`python3.8 -m pip list`
Package                         Version
------------------------------- ------------
absl-py                         2.0.0
aiohttp                         3.8.5
aiohttp-retry                   2.8.3
aiosignal                       1.3.1
anyio                           4.0.0
appdirs                         1.4.4
appnope                         0.1.3
appscript                       1.2.2
argon2-cffi                     23.1.0
argon2-cffi-bindings            21.2.0
arrow                           1.2.3
asttokens                       2.4.0
astunparse                      1.6.3
async-lru                       2.0.4
async-timeout                   4.0.3
attrs                           23.1.0
Babel                           2.12.1
backcall                        0.2.0
beautifulsoup4                  4.12.2
bleach                          6.0.0
buildozer                       1.2.0
cachetools                      5.3.1
certifi                         2023.7.22
cffi                            1.15.1
charset-normalizer              3.2.0
coloredlogs                     15.0.1
comm                            0.1.4
contextlib2                     21.6.0
contourpy                       1.1.1
cryptography                    41.0.4
cycler                          0.11.0
Cython                          3.0.2
debugpy                         1.8.0
decorator                       5.1.1
defusedxml                      0.7.1
distlib                         0.3.1
dnspython                       2.4.2
docutils                        0.20.1
exceptiongroup                  1.1.3
executing                       1.2.0
fastjsonschema                  2.18.0
filelock                        3.0.12
flatbuffers                     23.5.26
fonttools                       4.42.1
fqdn                            1.5.1
frozenlist                      1.4.0
gast                            0.4.0
google-auth                     2.23.1
google-auth-oauthlib            1.0.0
google-pasta                    0.2.0
grpcio                          1.58.0
h5py                            3.9.0
humanfriendly                   10.0
idna                            3.4
imageio                         2.31.4
importlib-metadata              6.8.0
importlib-resources             6.1.0
imutils                         0.5.4
ipykernel                       6.25.2
ipython                         8.12.2
ipython-genutils                0.2.0
ipywidgets                      8.1.1
isoduration                     20.11.0
jaraco.classes                  3.3.0
jedi                            0.19.0
Jinja2                          3.1.2
json5                           0.9.14
jsonpointer                     2.4
jsonschema                      4.19.1
jsonschema-specifications       2023.7.1
jupyter                         1.0.0
jupyter_client                  8.3.1
jupyter-console                 6.6.3
jupyter_core                    5.3.2
jupyter-events                  0.7.0
jupyter-lsp                     2.2.0
jupyter_server                  2.7.3
jupyter_server_terminals        0.4.4
jupyterlab                      4.0.6
jupyterlab-pygments             0.2.2
jupyterlab_server               2.25.0
jupyterlab-widgets              3.0.9
keras                           2.13.1
keyring                         24.2.0
kiwisolver                      1.4.5
lazy_loader                     0.3
libclang                        16.0.6
lxml                            4.9.3
Markdown                        3.4.4
markdown-it-py                  3.0.0
MarkupSafe                      2.1.3
matplotlib                      3.7.3
matplotlib-inline               0.1.6
mdurl                           0.1.2
mistune                         3.0.1
more-itertools                  10.1.0
mpmath                          1.3.0
multidict                       6.0.4
nbclient                        0.8.0
nbconvert                       7.8.0
nbformat                        5.9.2
nest-asyncio                    1.5.8
networkx                        3.1
nh3                             0.2.14
notebook                        7.0.4
notebook_shim                   0.2.3
Nuitka                          1.9rc4
numpy                           1.24.3
oauthlib                        3.2.2
onnxruntime                     1.15.0
opencv-python                   4.8.0.76
opt-einsum                      3.3.0
ordered-set                     4.1.0
overrides                       7.4.0
packaging                       23.1
pandocfilters                   1.5.0
parso                           0.8.3
pexpect                         4.8.0
pickleshare                     0.7.5
Pillow                          9.5.0
pip                             23.2.1
pkginfo                         1.9.6
pkgutil_resolve_name            1.3.10
platformdirs                    3.10.0
progressbar2                    4.2.0
prometheus-client               0.17.1
prompt-toolkit                  3.0.39
protobuf                        3.20.3
psutil                          5.9.5
ptyprocess                      0.7.0
pure-eval                       0.2.2
pyasn1                          0.5.0
pyasn1-modules                  0.3.0
pycparser                       2.21
pydload                         1.0.9
pygame                          2.5.2
Pygments                        2.16.1
PyJWT                           2.8.0
pyobjc-core                     10.0
pyobjc-framework-Cocoa          10.0
pyobjc-framework-Quartz         10.0
pyparsing                       3.1.1
PySide6                         6.5.2
PySide6-Addons                  6.5.2
PySide6-Essentials              6.5.2
python-dateutil                 2.8.2
python-json-logger              2.0.7
python-utils                    3.8.1
pytz                            2023.3.post1
PyWavelets                      1.4.1
PyYAML                          6.0.1
pyzmq                           25.1.1
qtconsole                       5.4.4
QtPy                            2.4.0
readme-renderer                 42.0
referencing                     0.30.2
requests                        2.31.0
requests-oauthlib               1.3.1
requests-toolbelt               1.0.0
rfc3339-validator               0.1.4
rfc3986                         2.0.0
rfc3986-validator               0.1.1
rich                            13.5.3
rpds-py                         0.10.3
rsa                             4.9
scikit-image                    0.21.0
scipy                           1.10.1
Send2Trash                      1.8.2
setuptools                      56.0.0
sh                              1.14.1
shiboken6                       6.5.2
six                             1.16.0
sniffio                         1.3.0
soupsieve                       2.5
stack-data                      0.6.2
sympy                           1.12
tensorboard                     2.13.0
tensorboard-data-server         0.7.1
tensorflow                      2.13.1
tensorflow-estimator            2.13.0
tensorflow-io-gcs-filesystem    0.34.0
tensorflow-object-detection-api 0.1.1
termcolor                       2.3.0
terminado                       0.17.1
tifffile                        2023.7.10
tinycss2                        1.2.1
tomli                           2.0.1
tornado                         6.3.3
traitlets                       5.10.1
turboactivate                   4.4.4.1
twilio                          8.9.0
twine                           4.0.2
typing_extensions               4.5.0
uri-template                    1.3.0
urllib3                         2.0.5
validate-email                  1.3
virtualenv                      20.4.3
wcwidth                         0.2.6
webcolors                       1.13
webencodings                    0.5.1
websocket-client                1.6.3
Werkzeug                        2.3.7
wheel                           0.41.2
widgetsnbextension              4.0.9
wrapt                           1.15.0
yarl                            1.9.2
zipp                            3.17.0
zstandard                       0.21.0
Nuitka Installation:
py -m pip install Nuitka-develop.zip

**Nuitka Command:**

`python3.8 -m nuitka --run --standalone --enable-plugin=pyside6  --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow --python-flag=no_site --macos-app-icon=/Users/license_lock_photo.png --macos-create-app-bundle --macos-disable-console test_temp.py`

**The code sample:**
```
from tensorflow.lite.python.interpreter import Interpreter
print("hallo")
```

**Error Message:**
Nuitka-Plugins:INFO: dll-files: Found 1 file DLLs from tensorflow.lite.experimental.microfrontend.python.ops.audio_microfrontend_op installation.
Nuitka:INFO: Keeping build directory 'test_temp.build'.                         
Nuitka:INFO: Created binary that runs on macOS 10.9 (x86_64) or higher.
Nuitka:INFO: Successfully created 'test_temp.app/Contents/MacOS/test_temp'.
Nuitka:INFO: Launching 'test_temp.app/Contents/MacOS/test_temp'
2023-10-02 22:41:05.561240: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/Users/emre/Documents/Tensorflow1_py_test/models/research/object_detection/object_detection/tests/test_temp.app/Contents/MacOS/test_temp.py", line 1, in <module>
  File "/Users/emre/Documents/Tensorflow1_py_test/models/research/object_detection/object_detection/tests/test_temp.app/Contents/MacOS/tensorflow/__init__.py", line 38, in <module tensorflow>
  File "/Users/emre/Documents/Tensorflow1_py_test/models/research/object_detection/object_detection/tests/test_temp.app/Contents/MacOS/tensorflow/python/__init__.py", line 42, in <module tensorflow.python>
  File "/Users/emre/Documents/Tensorflow1_py_test/models/research/object_detection/object_detection/tests/test_temp.app/Contents/MacOS/tensorflow/python/data/__init__.py", line 21, in <module tensorflow.python.data>
  File "/Users/emre/Documents/Tensorflow1_py_test/models/research/object_detection/object_detection/tests/test_temp.app/Contents/MacOS/tensorflow/python/data/experimental/__init__.py", line 97, in <module tensorflow.python.data.experimental>
  File "/Users/emre/Documents/Tensorflow1_py_test/models/research/object_detection/object_detection/tests/test_temp.app/Contents/MacOS/tensorflow/python/data/experimental/service/__init__.py", line 419, in <module tensorflow.python.data.experimental.service>
  File "/Users/emre/Documents/Tensorflow1_py_test/models/research/object_detection/object_detection/tests/test_temp.app/Contents/MacOS/tensorflow/python/data/experimental/ops/data_service_ops.py", line 25, in <module tensorflow.python.data.experimental.ops.data_service_ops>
  File "/Users/emre/Documents/Tensorflow1_py_test/models/research/object_detection/object_detection/tests/test_temp.app/Contents/MacOS/tensorflow/python/data/ops/dataset_ops.py", line 4774, in <module tensorflow.python.data.ops.dataset_ops>
  File "/Users/emre/Documents/Tensorflow1_py_test/models/research/object_detection/object_detection/tests/test_temp.app/Contents/MacOS/tensorflow/python/util/lazy_loader.py", line 58, in __getattr__
  File "/Users/emre/Documents/Tensorflow1_py_test/models/research/object_detection/object_detection/tests/test_temp.app/Contents/MacOS/tensorflow/python/util/lazy_loader.py", line 41, in _load
  File "importlib.py", line 127, in import_module
ModuleNotFoundError: No module named 'tensorflow.python.data.ops.shuffle_op'

**Comment by emre84** [comment]
One more comment: Compilation works fine with python3.7. Just Python3.8 and python3.10 give  tensorflow.python.data.ops.shuffle_op error .


python3.7 -m nuitka --version
1.9rc5
Commercial: None
Python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
Flavor: CPython Official
Executable: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7
OS: Darwin
Arch: x86_64
Version C compiler: /usr/bin/clang (clang).

**Comment by kayhayen** [comment]
It pains me to see that people define a lazy loader for a module and then access it in the same module to load it immediately, but hiding that. I also had a hidden dependency on `ml_dtypes` somewhere that I added, checking if that's all now.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by emre84** [comment]
Thanks Kay, it is fixed.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.8.5 that I just made, not sure if it's enough fixes or develop is really needed, but this specific error is fixed that way.
