### ISSUE TITLE
Issue: %TEMP% does not work when used in --force-stdout-spec

### ISSUE THREAD

**Issue by LorenEteval** [Nuitka/Nuitka#2478]
This is a duplicate of issue #2477 . Sorry I opened the same because the previous is locked and I cannot comment in there.

---

Consider a minimal reproducible example named example.py using PySide6

```python
from PySide6 import QtCore
from PySide6.QtWidgets import QApplication, QMainWindow


app = QApplication()

window = QMainWindow()
window.show()

app.exec()
```

When packed using

```
python -m nuitka --standalone --plugin-enable=pyside6 --disable-console --force-stdout-spec=%TEMP%\_Enable_Stdout example.py --output-dir=nuitka
```

The application works and window shows up. However, if I copy the nuitka output dir to my VM (with different Username), the application cannot start. No window shows up.

(Edit: _Enable_Stdout file found in local machine TEMP, but not VM)

Instead packed using

```
python -m nuitka --standalone --plugin-enable=pyside6 --disable-console --force-stdout-spec=_Enable_Stdout example.py --output-dir=nuitka
```

The application works on my local machine and my VM.

(Edit: _Enable_Stdout file found in local machine and VM program dir)

My local machine environment (Windows 11 22H2):

```
> nuitka --version
1.8.3
Commercial: None
Python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\bin\Hostx64\x64\cl.exe (cl 14.3).
My VM: Windows 10 22H2
```

---

Different test result:

I have a different VM that runs Windows 10 21H2 that has the same Username as my local machine. Performed the same steps above and the result is runnable on both machines. `_Enable_Stdout` file found in local machine and VM TEMP dir.

**Comment by kayhayen** [comment]
Yeah, sorry I forgot I locked it. Also unable to undo comments marked. I somehow was probably too tired to realize this was the proper issue then.

Your problem is that you do not understand that %TEMP% in your command line is expanded by the shell already, and before Nuitka sees it. You need to *quote* these kinds of things.

**Comment by kayhayen** [comment]
Also, you do not show your output, I think there is a warning against absolute paths, but I am not sure now.
