### ISSUE TITLE
GSOC 2019: Use this issue for other GSoC questions

### ISSUE THREAD

**Issue by kayhayen** [Nuitka/Nuitka#248]
First of all: Welcome to Nuitka!

So this issue is intended for all questions of general nature. Introduce yourself here, ask about the process, or about available tools.

This is absolutely open to all kinds of questions related to the GSoC, esp. if you are interested in creating your own idea too. Do not hesitate to ask, as long as you can live with us not answering immediately around the clock. :)

**Comment by bksahu** [comment]
Hello, @kayhayen :smile:  I am Batakrishna Sahu from India. I am an undergrad in computer science. And it's really nice to work with you.

What are your requirements to qualify as a GSoC student? Where can one post the proposed draft for feedbacks?

**Comment by kayhayen** [comment]
@bksahu I do not have a fixed set of requirements, so only what Google wants of you. I would like make sure of course that you qualify for that, but since this is the first time I am doing this, I don't think I have anything beyond that. What I would like to do is to have some sort of video chat before we apply, which is what I meant to offer during the course of the GSoC.

I must say, I was very positively impressed with you just going ahead and trying out. In my mind, that makes you very interesting. During a talk, I expect we can both commit and go ahead together.

**Comment by kayhayen** [comment]
So this week I am relatively busy with 2 of my sons, the older ones having their birthdays, and me preparing that. But my idea is for students that want to apply and that I mentor, we will have a teleconference which mainly aims at getting to know each other, and then maybe weekly ones preparing the application and talking code and designs, or showing you stuff.

My main focus will be to prepare things e.g. with developer manual updates, and then specific help for you. 

So @bksahu if you want, please propose a date and time range with a time zone name :) or so for next week. I am mostly flexible and assume we live in vastly different time zones, but I am active day and night, so I won't mind. :-)

**Comment by bksahu** [comment]
@kayhayen How about I email you directly my contact details?

**Comment by kayhayen** [comment]
@bksahu yes of course, please do that. I was writing this here, only for the part where I say how I think the application part goes for Nuitka. Not to actually schedule our meeting.

**Comment by ritwik12** [comment]
@kayhayen Hi, just few questions. does Nuitka have some specific tasks or projects needed to be done under GSoC 2019 or will it work by contributing normally to this repo?

**Comment by Nimishkhurana** [comment]
Hello @bksahu . I am Nimish Khurana. I am an undergrad pursuing B.E. in Computer Science. I have have strong experience working with Python and basic C++. I would like to do GSoC 2019 under Nuitka. I have also left a comment on Benchmarks issue. Please help me get started to contribute.

**Comment by ritwik12** [comment]
Hey @Nimishkhurana , you have tagged wrong person. @bksahu is just another contributor like you. @kayhayen is the one to be mentioned.

**Comment by girijamanoj** [comment]
Hello @kayhayen 😃, This is Girija Manoj from India I am an undergrad in Computer Science, an Opensource enthusiast, and a Competitive Problem Solver. My expertise is Python and very comfortable with C++ too. I would like to contribute to Nuitka to the best of my ability. I already started exploring the wonderful codebase of Nuitka from the past few days.
           I have a suggestion for the betterment and faster development of our Nuitka, I feel it will be better if we have a platform(like Gitter or IRC) through which we can communicate more effectively than here So that the contributions will pace up. 😃 It will be better if we could start a new thread or chat room on either of the mentioned platforms(It was just my suggestion 😄). Thank you.

**Comment by Nimishkhurana** [comment]
> Hey @Nimishkhurana , you have tagged wrong person. @bksahu is just another contributor like you. @kayhayen is the one to be mentioned.

Oh it was my bad.I have edited my comment. Thanks

**Comment by kayhayen** [comment]
Hello there,

I realize I am falling a bit behind in reactions, sorry about that. As I wrote in this thread, this week is very tense for me due to the birthdays of two of my sons. Today I will also be busy due to it. I will be able to respond to the (many) GSoC requests over the course of the next week. This week I have fallen behind, wanting to get the contributions that are already in 0.6.2 out, which it now is, but that was roughly my spare time budget available for Nuitka.

Next week I will go over all students and answer questions, and make a list, where to direct you to.

If you have C knowledge, there will be another idea added, that should lead you to being able to add and optimize C helper functions. That would be great for me. It seems amazingly many have the skills to do that. 

Ultimately I think I will have a video chat with each of you where I think there is a matching idea, and where we can have a look together.

I hope that is fair for you. Next week and beyond you own me until I catched up. :-)

**Comment by ajitesh-30** [comment]
Hello @kayhayen I am a Computer Science Undergraduate from India . I have got knowledge of both Python and C/C++ . I have read almost every document about Nutika. I would love contributing to Nutika .

**Comment by omarahmed1111** [comment]
hello @kayhayen i am omar ahmed a computer engineering undergrad from Egypt , i have a strong experience in competitive programming and a very good knowledge in c/c++ and python , i will join gsoc 2019 and would like to contribute in Nuitka , i am interested in (Nuitka support for PyPI top 50) project and hope to be more value for this organization , thank you :smiley: 
i have a question that interest me where does name Nuitka come from or what does it mean ? :smile: :smile:

**Comment by omarahmed1111** [comment]
hello @kayhayen , i am a computer engineering undergrad from Egypt , i would like to contribute to nuitka , i cant find a way in the documentation to build it from source on ubuntu linux so is there a way to build it on linux from source ?

**Comment by bksahu** [comment]
Hello. @omarahmed1111 You can build docs on your local machine. You have to first install doxygen and then execute `doxygen doc/Doxyfile`

This will make a `html` folder inside which you can find `index.htm` which you can browse for the docs.

**Comment by kayhayen** [comment]
@omarahmed1111 I think there is a chapter in User Manual now, http://nuitka.net/doc/user-manual.html#installation

But it's shockingly simple, just a standard `setup.py` usage.

**Comment by kayhayen** [comment]
So the way this is going to work, is that I will go over the contacts from students that I had and make sure to reply with a request to fill out mini survey, that basically is just about contact details and Python and C knowledge. Send this to my private email only: kay.hayen@gmail.com

Full Name:
Country:
Student at Org URL:
Email:
Github name:
Twitter handle (optional):
Skype handle (Hangouts would be even better):
Ideas Interested in (we can checkout together):
Python Knowledge (Python2, Python3):
C Knowledge (Basic, Intermediate, Expert, not required for all ideas!):
Anything else you want to point out:

I will search for comments made by you so far on my own, and emails received, and deal with them.

I will store this information and share it with the other GSoC mentors in a private Google Doc for the duration of the application process.

**Comment by kayhayen** [comment]
As for Gitter chat, IRC and other things @girijamanoj , so far I am happy with Github. The advantage is that this is searchable, archived, and one single point of interaction. For now I would like to go with this.

**Comment by kayhayen** [comment]
My goal is to have a video chat with every serious applicant, but I am not entirely sure how long it will be for me to make that happen. Also please understand that we cannot take everybody. You definitely wouldn't want us to have to split our time between too many people, then we can't assist and teach you the way this is supposed to be.

My heart is already bleeding in the prospect that I will have to turn down totally viable offers. Please know that the decision is naturally going to be hard. Don't become angry with me.

**Comment by omarahmed1111** [comment]
hello  @kayhayen i really run into a lot a lot of problems to setup the environment of nuitka on ubuntu 16.04 so that i can excute setup.py and to use nuitka after that as mentioned in the user manual so could i write how to setup the ubuntu environment for nuitka in the user manual documentation will this be helpful or not , i don't know as i am a beginner and don't know if it will help anyone to not run into errors like me or not :smile:

**Comment by riya-17** [comment]
Hey @kayhayen, I am Riya, I would like to Contribute to Nuitika for GSOC 2019. Please help me to start with the issues and getting familiar with the code.

**Comment by LilJohny** [comment]
@kayhayen  Can I use first 50 libs from this list https://pythonwheels.com/  for #229 ?

**Comment by kayhayen** [comment]
@LilJohny That would be perfectly fine too. I think there anyway has to be a big overlap between top 50 PyPI packages and top 50 wheels used, right?

**Comment by sannanansari** [comment]
@kayhayen Yes their is a big overlap [Top 50 pypi packages](https://stackoverflow.com/a/47375786). Now I think our tasks is find next top 50 packages.

**Comment by tab1tha** [comment]
please help.I am trying to run this nuitka on a program called HelloWorld.py on UBuntu 16.04LTS. I have gcc installed not MINGW.I tried modifying the command in the user manual containing MINGW so that gcc is used instead.It gives me this result https://pastebin.com/k8Js29wD .please how do I write the command correctly to run nuitka on a .py program in ubuntu 16.04LTS?

**Comment by bksahu** [comment]
@tab1tha You don't need to install MINGW for Ubuntu 16. Try `python3 -m nuitka --standalone HelloWorld.py`

**Comment by tab1tha** [comment]
python3 -m nuitka --standalone HelloWorld.py runs for 1 minute and does not produce any result

**Comment by bksahu** [comment]
> python3 -m nuitka --standalone HelloWorld.py runs for 1 minute and does not produce any result

@tab1tha It will create two directories: `HelloWorld.bin/` and `HelloWorld.dist/`. You can see the output by executing the executable in the `HelloWorld.dist/` directory. Try `./HelloWorld.dist/HelloWorld`.

**Comment by Nimishkhurana** [comment]
@tab1tha To also run the script in same command use `--run` option.

**Comment by tab1tha** [comment]
> > python3 -m nuitka --standalone HelloWorld.py runs for 1 minute and does not produce any result
> 
> @tab1tha It will create two directories: `HelloWorld.bin/` and `HelloWorld.dist/`. You can see the output by executing the executable in the `HelloWorld.dist/` directory. Try `./HelloWorld.dist/HelloWorld`.

it worked.Thanks

**Comment by tommyli3318** [comment]
@kayhayen Hello! CS major here from the United States. I just discovered Nuitka and gsoc today and this project seems very interesting to me. However, it looks like I'm late to the party. Have you guys already filled up all the positions? Is it too late to go through the application process now?
Thank you!

**Comment by tab1tha** [comment]
hello @tommyli3318 ,the positions have not been assigned yet.Feel free to choose a  GSOC project you want to work on and prepare a proposal for it (deadline for submission to the GSOC website is the 9th of April 2019).Also,go through the User Manual (http://nuitka.net/doc/user-manual.html) and the Developer manual (http://nuitka.net/doc/developer-manual.html) of Nuitka ;They'll help get you 'up to speed'. If you are in doubt ,feel free to drop a question here.

**Comment by kayhayen** [comment]
@tommyli3318 it's not too late until 9th of April, but we expect a substantial PR in the field you want to apply for, but you can always start now and aim for 2020 unless it's your last year of studies. And it may be worth to get a feel of things either way.

One relatively easy issue, if you have C knowledge can be #283 where we have high interest and not as much progress so far.

Also, if you are a systems expert, you can do #230 and start maybe with issues in the field We do not have much progress their either way, and @JorjMcKie is a really experienced mentor you would have there.

**Comment by Nimishkhurana** [comment]
@kayhayen can we have video call now to discuss queries regarding benchmarks project.

**Comment by sannanansari** [comment]
Hey @kayhayen, I hope your day is going good. I want to discuss more about GSOC 2019: Make sure top 50 PyPI packages are supported #229.
As I understand their is 3 stages in project. 1.Find issues and reporting to bug tracker 2. Developing tools to minimized the issues(Fixing issues) 3. Setting up automated tests. As far as Jinja 2 concern I am learning it.
Hiw can I approach this 3 stages?

**Comment by kayhayen** [comment]
Just a quick reminder, there is less than one week left for the applications. Make sure to make it for the deadline. Submit your applications to me for review if you want and work PRs as these will be required to be accepted.

**Comment by tab1tha** [comment]
> Just a quick reminder, there is less than one week left for the applications. Make sure to make it for the deadline. Submit your applications to me for review if you want and work PRs as these will be required to be accepted.

Thanks for the reminder.I uploaded my proposal moments ago. I look forward to your suggestions.

**Comment by Pihu1998** [comment]
> Just a quick reminder, there is less than one week left for the applications. Make sure to make it for the deadline. Submit your applications to me for review if you want and work PRs as these will be required to be accepted.
Should I submit it to your private email or anywhere else?

**Comment by tab1tha** [comment]
> @kayhayen
> 
> > Just a quick reminder, there is less than one week left for the applications. Make sure to make it for the deadline. Submit your applications to me for review if you want and work PRs as these will be required to be accepted.
> 
> Should I submit it to your private email or anywhere else for review?

@Pihu1998 upload your proposal on the GSOC website by searching for Python Software organisation and clicking ''Upload proposal'': the site will provide instructions on how to proceed. Remember to specify that you are applying for Nuitka.
Cheers

**Comment by Pihu1998** [comment]
@tab1tha  Thank you so much for the response :-).  Actually I wanted to know whether it needs to be first reviewed by @kayhayen  before submitting it to the GSOC website.

**Comment by tab1tha** [comment]
> @tab1tha Thank you so much for the response :-). Actually I wanted to know whether it needs to be first reviewed by @kayhayen before submitting it to the GSOC website. 

When you upload the draft (Google docs link) on the site, and confirm that it can be shared with the organisation, you can then notify him here (by using @mention).

**Comment by Pihu1998** [comment]
@tab1tha  Okay. Thank you so much:-)

**Comment by kayhayen** [comment]
You can directly submit on the website, it will be a Google docs link there anyway and it's centrally on our radar, plus easier to dispatch for us mentors internally.

**Comment by Pihu1998** [comment]
@kayhayen I uploaded my proposal. I am looking forward for your suggestions.

**Comment by sannanansari** [comment]
@kayhayen I also uploaded my proposal and looking forward for your suggestions.

**Comment by kayhayen** [comment]
Today is the 8th, on 9th your proposal has to achieve "final" status. Whatever is in "draft" status will be rejected. I understand you can still make changes after submitting as "final", so there is no harm in you putting it to "final", right now.

Also thanks a lot for the many good submissions. It's been fun working with you. Now comes a hard time, where by the constraints of reality, we are forced to live with good ideas loosing our to better ideas. I want to thank you for understanding.

**Comment by kayhayen** [comment]
So, it's closed now. We are reading your submissions. Please do not bother to ask us about acceptance, we are reviewing only towards PSF and Google, and they will assign the slots, and announce the result on May 6th and *we are not allowed* to say anything before, and definitely won't,

That said, it will definitely help your cause to continue to be active and show yours skills. In some cases, we would like to take on students, but need to see more from you, to be comfortable in recommending it.

**Comment by goggle** [comment]
I think we can close this, since GSOC 2019 is over.
Will Nuitka be part of GSOC 2020?
