### ISSUE TITLE
nuitka compiles Django code successfuly but give SyntaxError: source code cannot contain null bytes

### ISSUE THREAD

**Issue by Aledangelo** [Nuitka/Nuitka#2482]
**python version**: 3.11.4
**nuitka version**:  1.8.3
**Flavor**: Fedora Python
**OS**: Linux 
**installation method**: pip

The application is compiled correctly and most Django commands work correctly, except for `runserver` command. It is the main commando, is purpose is to run Django application, but when I launch it this output is produced:

```
$ ./manage.bin runserver
  File "/home/lv/Simulator/./manage.bin", line 1
    ELF
SyntaxError: source code cannot contain null bytes
```

I have searched in all my files but I'm not able to find null bytes.

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."

**Comment by Aledangelo** [comment]
Keep calm buddy. Don't get mad
