### ISSUE TITLE
Crash after name collision between `--include-data-file` and `--output-filename`

### ISSUE THREAD

**Issue by bersbersbers** [Nuitka/Nuitka#2483]
It seems the path of a data file "inside" an app, and the name of the executable itself, can collide during compilation. I see what is going on (both are temporarily placed in the same folder), and it is not too difficult to work around (build to a different name of the executable, then rename), but it feels unnecessary, and the error message does not give a good idea what may be going wrong.

```xml
<exception exception_type="FileExistsError" exception_value="[Errno 17] File exists: 'dist-nuitka/empty.dist/project'">
Traceback (most recent call last):
  File "/home/bers/.pyenv/versions/3.11.6/lib/python3.11/site-packages/nuitka/MainControl.py", line 1104, in main
    _main()
  File "/home/bers/.pyenv/versions/3.11.6/lib/python3.11/site-packages/nuitka/MainControl.py", line 986, in _main
    copyDataFiles()
  File "/home/bers/.pyenv/versions/3.11.6/lib/python3.11/site-packages/nuitka/freezer/IncludedDataFiles.py", line 574, in copyDataFiles
    _handleDataFile(
  File "/home/bers/.pyenv/versions/3.11.6/lib/python3.11/site-packages/nuitka/freezer/IncludedDataFiles.py", line 537, in _handleDataFile
    makePath(os.path.dirname(dest_path))
  File "/home/bers/.pyenv/versions/3.11.6/lib/python3.11/site-packages/nuitka/utils/FileOperations.py", line 193, in makePath
    os.makedirs(path)
  File "&lt;frozen os&gt;", line 225, in makedirs
FileExistsError: [Errno 17] File exists: 'dist-nuitka/empty.dist/project'
</exception>
```

- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

1.8.4
Commercial: None
Python: 3.11.6 (main, Oct  6 2023, 21:02:08) [GCC 12.3.0]    
Flavor: pyenv
Executable: /home/bers/.pyenv/versions/3.11.6/bin/python3
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 23.04
Version C compiler: /usr/bin/gcc (gcc).

- How did you install Nuitka and Python

Windows 10, WSL, Ubuntu 23.04, `pyenv install 3.11.6`, `pip install nuitka==1.8.4`

- Provide in your issue the Nuitka options used

`python -m nuitka --onefile --static-libpython=no --include-data-file=empty.py=project/ --output-dir=dist-nuitka --output-filename=project empty.py`

- Note if this is a regression

It seems like it is not - I see the same thing in 1.5.0 and 1.6.0.

**Comment by bersbersbers** [comment]
Considering that I would like my result to be `dist-nutika/project`, and I do not care what the executable is named inside `empty.dist`, maybe a solution is to build the executable under `dist-nutika/project/nutika.temp.executable` and then move it to `dist-nutika/project` when done.

**Comment by kayhayen** [comment]
But how is `project` supposed to be a directory and a file at the same time? That is just not going to work. Data files are copied before the DLL files are copied, and as a result, those filenames are not known. The executable filename will be not known, but reversing the order, the "standalone entry point" files (EXE+PYDs+DLLs) will be known, and can be checked for.

**Comment by kayhayen** [comment]
I changed `copyDataFiles` to be done after DLL discovery, and then to check if the paths conflict with what's given.

So now this does the following:

> FATAL: Error, data file to be placed in distribution as 'project' conflicts with executable 'project'.

For lack of general relevance, I am closing this early.

**Comment by bersbersbers** [comment]
> But how is `project` supposed to be a directory and a file at the same time?

It is not supposed to be that *at the same time*, at least to my understanding. I think the confusion stems from the fact that in onefile mode, `nuitka` uses the same file name for the internal executable and the onefile executable (which is not necessary).

My call above asks to have `--output-filename=project` - it does not care what the name of the internal executable is. Yet at the time of the error above, `dist-nuitka/empty.dist/project` is the name of the internal executable which leads to collisions with the directory. But nothing is forcing `nuitka` to use the same name for the internal executable as for the outer (onefile) executable.

Note that this is working fine:

```
# NB: --output-filename=project.bin
python -m nuitka --onefile --static-libpython=no --include-data-file=empty.py=project/ --output-dir=dist-nuitka --output-filename=project.bin empty.py

# rename the external executable
mv dist-nuitka/project.bin dist-nuitka/project
```

Now the `project` binary unpacks the internal `project.bin` binary next to the `project` directory. But the calles above look like an unnecessary workaround from a user's (= compiler's) perspective. Maybe in onefile mode, `nuitka` should let the user choose the name of the internal executable independent from the name of the "output" executable. Just an idea.

Either way, the new error message is definitely helpful, thanks for that.

**Comment by kayhayen** [comment]
I only considered standalone here. You are correct, using the same name would not be necessary. In fact the bootstrap generically detects what the main binary is by virtual of it being the first file in the archive. The influence on `__file__` would be there, but `sys.argv[0]` is the onefile anyway. Adding a choice for the name inside the onefile is I fear, very confusing to the reader, but definitely possible.

If you want to PR it, please be my guest:

```
def getResultFullpath(onefile):
    """Get the final output binary result full path."""

    result = getResultBasePath(onefile=onefile)

    if Options.shallMakeModule():
        result += getSharedLibrarySuffix(preferred=True)
    else:
        output_filename = Options.getOutputFilename()

        if Options.isOnefileMode() and output_filename is not None:
            if onefile:
                result = Options.getOutputPath(output_filename)
            else:
                result = os.path.join(
                    getStandaloneDirectoryPath(),
                    os.path.basename(output_filename),
                )
        elif Options.isStandaloneMode() and output_filename is not None:
            result = os.path.join(
                getStandaloneDirectoryPath(),
                os.path.basename(output_filename),
            )
        elif output_filename is not None:
            result = output_filename
        elif not isWin32OrPosixWindows() and not Options.shallCreateAppBundle():
            result += ".bin"

        if isWin32OrPosixWindows() and not hasFilenameExtension(result, ".exe"):
            result += ".exe"

    return result
```

It would have to be an option, but I don't know how to name it. What we could do, is that for dist folder name, in case of onefile, we already append ".bin", because in that case, it's very unlikely to cause collisions, and it's also why on Windows it never happens, so maybe that's a lot less complex and as effective.

**Comment by kayhayen** [comment]
Ok, adding this ought to work

```
        if not isWin32OrPosixWindows() and Options.isOnefileMode() and not onefile:
            result += ".bin"
```

**Comment by kayhayen** [comment]
So, with this, the check still covers DLLs and extension module file conflicts, which is good to have either way, even if they are a lot less likely.

**Comment by bersbersbers** [comment]
I tried factory and it is working fine for me, thanks!

And if you do choose to create a `project.bin` data folder, the error message is very helpful now, too:

> FATAL: Error, data file to be placed in distribution as 'project.bin' conflicts with executable 'project.bin'.

**Comment by kayhayen** [comment]
Part of the current pre-release.

**Comment by kayhayen** [comment]
Part of the 2.2 release I just made.
