### ISSUE TITLE
Input argument -m does not work for compiled code

### ISSUE THREAD

**Issue by MatCat776** [Nuitka/Nuitka#2484]
# Nuitka Version
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.
[user]# python -m nuitka --version
/usr/bin/python: No module named nuitka
[user]# python3 -m nuitka --version
1.8.4
Commercial: None
Python: 3.9.10 (main, Oct  5 2023, 20:13:25)
Flavor: Unknown
Executable: /usr/local/bin/python3
OS: Linux
Arch: x86_64
Distribution: Centos (based on Fedora) 7
Nuitka-Scons:INFO: The provided gcc is too old, switching to its g++ instead.
Version C compiler: /usr/bin/g++ (g++).

- How did you install Nuitka and Python
pip3 install nuitka 
pip3 install patchelf
Installed from source from wget https://www.python.org/

  Did you use pip (for Nuitka only), anaconda (no), deb (no), rpm (no), from source (for python only), git clone (no), then install into a virtualenv (no) 

- The specific PyPI names and versions

[user]#  python -m pip freeze
Nuitka==1.8.4
ordered-set==4.1.0
patchelf==0.17.2.1
zstandard==0.21.0

# Example
- Also supply a Short, Self Contained, Correct, Example

Paste the following into hello.py:
***** start of hello.py ****
import argparse

parser = argparse.ArgumentParser(
    description='A tool for processing data'
)

parser.add_argument(
    '-l',
    '--lname',
    default = None,
    type = str,
    help = 'This option accepts a string'
)

parser.add_argument(
    '-m',
    '--mname',
    default = None,
    type = str,
    help = 'This option accepts a string'
)

parser.add_argument(
    '-n',
    '--nname',
    default = None,
    type = str,
    help = 'This option accepts a string'
)

parser.add_argument(
    '-o',
    '--oname',
    default = 'default_foo',
    type = str,
    help = 'This option accepts a string'
)

parser.add_argument(
    '-p',
    '--pname',
    action="store_true",
    help="Flag to set to true."
)

def talk(message):
    return "Talk " + message

def main():
    print(talk("Hello World"))
    args = parser.parse_args()
    print(args)

**** end of hello.py ****

Uncompiled code works as expected:
[user]# python3 hello.py -l fooL -m fooM -n fooN -o fooO -p
Talk Hello World
Namespace(lname='fooL', mname='fooM', nname='fooN', oname='fooO', pname=True)

Compile code:
python3 -m nuitka hello.py

The -m flag does not work with compiled code:

[user]# ./hello.dist/hello.bin -l fooL -m fooM -n fooN -o fooO -p
Error, the program tried to call itself with '-m' argument. Disable with '--no-deployment-flag=self-execution'.

The suggested flag doesn't help:
[user]# ./hello.dist/hello.bin -l fooL -m fooM -n fooN -o fooO -p --no-deployment-flag=self-execution
Error, the program tried to call itself with '-m' argument. Disable with '--no-deployment-flag=self-execution'.

I'm probably using the flag wrong, but I don't see any documentation on how to use it.
I am aware of this manual, but I suspect there is additional documentation I can't find:
https://nuitka.github.io/Nuitka-website/doc/user-manual.html

If -m is replaced with --mname, it works. Note that -l, -n, -o and -p work fine.
[user]# ./hello.dist/hello.bin -l fooL --mname fooM -n fooN -o fooO -p
Talk Hello World
Namespace(lname='fooL', mname='fooM', nname='fooN', oname='fooO', pname=True)

# Regression
- Note if this is a regression

It is possible this is a regression since Aug 2, 2023. But it is also possible I ran my test differently. I can do more testing next week, if that would be helpful.

**Comment by kayhayen** [comment]
The deployment flags are not actually documented at this time. Nuitka attempts to catch cases where a fork bomb might have been compiled and is about to take down the whole system. If you know that it's not true, you can disable that check as suggested.

Right now it's only in the changelog:

```
-  UI: Added new ``--deployment`` and ``--no-deployment-flag`` that
   disables certain debugging helpers.

   Right now, we use this to control a hook that prevents execution of
   itself with ``-c`` which is used by e.g. ``joblib`` and that
   potentially can turns Nuitka created programs into a fork bombs, when
   they use ``sys.executable -c ...``. This can be disabled with
   ``--no-deployment-flag=self-execution`` or ``--deployment``.

   The plan is to expand this to cover ``FileNotFoundError`` and similar
   exception exits pointing to compilation issues with helpful more
   annotations.
```

**Comment by kayhayen** [comment]
Interestingly `python -mpip --help` works for pip. The fork bombs seen so far have not used that, so I would like to stay away from getting broader at this point, but `-m ...` is used e.g. by loky, and potentially other processes to spawn `sys.executable` with the intent of running other code, which Nuitka does only allow if specifically coded for.

**Comment by MatCat776** [comment]
Does the --no-deployment-flag=self-execution flag get used at time of compilation (option 1) or at runtime (option 2)?

1. python3 -m nuitka hello.py --no-deployment-flag=self-execution
2. ./hello.dist/hello.bin -l fooL -m fooM -n fooN -o fooO -p --no-deployment-flag=self-execution

What input arguments are not allowed without the no-deployment-flag?

**Comment by MatCat776** [comment]
This is probably OBE, but in case anyone wants to run my example, here it is with tabs:
```
import argparse

parser = argparse.ArgumentParser(
    description='A tool for processing data'
)

parser.add_argument(
    '-l',
    '--lname',
    default = None,
    type = str,
    help = 'This option accepts a string'
)

parser.add_argument(
    '-m',
    '--mname',
    default = None,
    type = str,
    help = 'This option accepts a string'
)

parser.add_argument(
    '-n',
    '--nname',
    default = None,
    type = str,
    help = 'This option accepts a string'
)

parser.add_argument(
    '-o',
    '--oname',
    default = 'default_foo',
    type = str,
    help = 'This option accepts a string'
)

parser.add_argument(
    '-p',
    '--pname',
    action="store_true",
    help="Flag to set to true."
)

def talk(message):
    return "Talk " + message

def main():
    print(talk("Hello World"))
    args = parser.parse_args()
    print(args)

if __name__ == "__main__":
    main()
```

**Comment by kayhayen** [comment]
These are valid questions indeed. It's at compile time of course. I won't be getting to documenting this for a while though.

**Comment by kayhayen** [comment]
So, the user manual did actually get updated, and this is currently on the factory branch.

**Comment by kayhayen** [comment]
Let me know if you get it from there.

**Comment by MatCat776** [comment]
Thanks for the update. The flag --no-deployment-flag=self-execution is working for us.

**Comment by kayhayen** [comment]
So, the change is now on develop and will be part of 1.9 release.

**Comment by kayhayen** [comment]
Part of the 1.9 release I just made.
