### ISSUE TITLE
在MacOS下为Pyqt6打包，运行xxx.app直接crash

### ISSUE THREAD

**Issue by Henxun** [Nuitka/Nuitka#2488]
在macos m1使用nuitka打包pyqt6，运行xxx.app程序crash
使用的命令：nuitka --standalone --macos-create-app-bundle --nofollow-imports --enable-plugin=pyqt6 --output-dir=o main.py
错误代码在from PyQt6.QtWidgets import *
开启--debugger得到以下一些信息
thread #1, queue= 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS(code=1, address=0x8)

* frame #0: 0x00000001869bd204 CoreFundation`_CFGetNonObjCTypeID + 92
....

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
