### ISSUE TITLE
No module named 'pydantic.root_model'

### ISSUE THREAD

**Issue by emcek** [Nuitka/Nuitka#2490]
With python file:
```python
from pydantic import RootModel

class RM(RootModel):
    pass

print(RM())
```
Runing Nuitka:
```
python -m nuitka --onefile test2.py
Nuitka-Options:INFO: Used command line options: --onefile test2.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.8.4' on Python '3.10' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.                             
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.                             
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl 14.3).
Nuitka-Scons:INFO: Backend linking program with 68 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 68 C files using clcache with 31 cache hits and 37 cache misses.
Nuitka-Postprocessing:INFO: Creating single file from dist folder, this may take a while.   
Nuitka-Onefile:INFO: Running bootstrap binary compilation via Scons.
Nuitka-Scons:INFO: Onefile C compiler: cl (cl 14.3).
Nuitka-Scons:INFO: Onefile linking program with 1 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 1 C files using clcache with 1 cache hits and 0 cache misses.
Nuitka-Onefile:INFO: Using compression for onefile payload.
Nuitka-Onefile:INFO: Onefile payload compression ratio (29.71%) size 26120664 to 7760739. 
Nuitka-Onefile:INFO: Keeping onefile build directory 'test2.onefile-build'.
Nuitka:INFO: Keeping dist folder 'test2.dist' for inspection, no need to use it.
Nuitka:INFO: Keeping build directory 'test2.build'.
Nuitka:INFO: Successfully created 'test2.exe'.
```
Got error:
```
PS C:\Users\PLMIPLI1\Projects\nuitka_test> .\test2.exe                        
Traceback (most recent call last):
  File "C:\Users\PLMIPLI1\AppData\Local\Temp\ONEFIL~1\test2.py", line 1, in <module>
    from pydantic import RootModel
  File "C:\Users\PLMIPLI1\AppData\Local\Temp\ONEFIL~1\pydantic\__init__.py", line 224, in __getattr__
  File "importlib.py", line 126, in import_module
ModuleNotFoundError: No module named 'pydantic.root_model'
```

python -m nuitka --version
```
1.8.4
Commercial: None
Python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\PLMIPLI1\Projects\venvs\nuitka_test_310\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.37.32822\bin\Hostx64\x64\cl.exe (cl 14.3).
```

python -m pip freeze
```
annotated-types==0.6.0
Nuitka==1.8.4
ordered-set==4.1.0
pydantic==2.4.2
pydantic_core==2.10.1
typing_extensions==4.8.0
zstandard==0.21.0
```

**Comment by kayhayen** [comment]
Newer `pydanctic` has added `__getitem__` lazy loading that prevents Nuitka from seeing the dependencies. Use an older version, I am not sure which, that doesn't have this. I will probably add it for 1.9 release though.

**Comment by emcek** [comment]
Got it. I think this behavior was added in since 2.0.0. Can I force Nuitka to include `pydantic` or any dependencies to be added anyway?

**Comment by krunaldodiya** [comment]
Is there any way to import module dynamically ? not while compiling but while running ?

for example, let's compile very simple binary:-

` main.py `

```
import importlib


def main():
    module_file = importlib.import_module("strategy")
    class_name = getattr(module_file, "Strategy")
    class_object = class_name()
    class_object.run()


if __name__ == "main":
    main()
```

Let's compile now:
```
python -m nuitka main.py -o trader --follow-imports
```

when running `trader` inside `project` directory, it works!

` directory structure `

- project
   - strategy.py

` strategy.py `

```
class Strategy:
   def run(self):
        print("running")
```

but when I install external pip package:-

` pip install some_package `

```
from some_package import some_class

class Strategy:
   def run(self):
        print("running")
```

it throws `module not found` Error for `some_package`

Please let me know if there is any way to import user defined pip packages, because while compiling binary it is not defined which package will user install and use. So I can not use ` nuitka --import-module=some_package `

**Comment by emcek** [comment]
@krunaldodiya If I understand you correctly. You don't know in advanced what user can import (here in `strategy` module)? I think there is no way, dynamically load module if you do not know which one at compiling time. I'm using in my project `importlib` to load some module during runtime, but I know exactly which one I can expected to be loaded during compile time.

**Comment by kayhayen** [comment]
Nuitka supports a bunch of lazy loaders already. I was aware that pydantic now has one, but I couldn't produce it so far, I should have enough information now.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
Part of the 1.9 release I just made.
