### ISSUE TITLE
Question about option to exclude of Python 2 files

### ISSUE THREAD

**Issue by M-Startc** [Nuitka/Nuitka#2493]
I have ttp module (https://github.com/dmulyalin/ttp) in my project and I use `--include-package=ttp ` to include it.
There is [load_python_exec_py2.py](https://github.com/dmulyalin/ttp/blob/master/ttp/utils/load_python_exec_py2.py)  file intended to Python 2 with  line like `exec compile(text_data, '<string>', 'exec') ` , so Nuitka gives error related to SyntaxError.
So the question.
Is there the way to exclude files that are intended to work in Python 2

**Comment by kayhayen** [comment]
Yes, there is, just let me know how help and User Manual fail to answer this.
