### ISSUE TITLE
torch.jit is disabled in standalone mode unnecessarily

### ISSUE THREAD

**Issue by remleduff** [Nuitka/Nuitka#2500]
- Nuitka version

> 1.8.4
Commercial: None
Python: 3.8.10 (default, May 26 2023, 14:05:08) 
Flavor: Debian Python
Executable: /opt/deepsig/.venv/bin/python3
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 20.04.6
Version C compiler: /usr/bin/gcc (gcc).

- How did you install Nuitka and Python

> pip install nuitka

- The specific PyPI names and versions

I've tested with torch versions 1.11.0a0+gitbc2c6ed and 2.1.0
  
 This is related to issue https://github.com/Nuitka/Nuitka/issues/2189
 
 However, kohler made a slight mistake in his example program without realiizing it. His example uses torch.jit.script which requires the source code of the model be present during JIT'ing. However, we only use torch.jit.trace which works without the source code present.
 
 This used to work fine for us using nuitka 0.9.5 in both standalone and normal compilation. But on newer versions of nuitka, it continues to work ok in normal compilation and fails in standalone mode.
 
 I've narrowed this down to this commit (https://github.com/Nuitka/Nuitka/commit/551db20e9c77d37a60ed7c39889054b373bfe055) which added support for the "timm" module. I believe this commit was slightly over-zealous and resulted in disabling torch jit entirely in standalone mode.
 
 I've manually edited the config file disabling the rule that sets the PYTORCH_JIT environment variable to 0, and our code functions normally once again.
 
 Test program (this is similar to the sample code kohler sent before, but uses torch.jit.trace rather than torch.jit.script)
 
 ```
import torch
import io

class MyModule(torch.nn.Module):
    def forward(self, x):
        return x + 10

m = torch.jit.trace(MyModule(), torch.Tensor([1,2,3]))
print(m)

# Save to io.BytesIO buffer
buffer = io.BytesIO()
torch.jit.save(m, buffer)

print("Done")

 ```

**Comment by kayhayen** [comment]
I should then apparently only set the variable if the script module is included, or maybe not at all. From what I recall, `timm` uses the script module without good reasons, I need to check.

**Comment by kayhayen** [comment]
So, I managed to relegate said environment variable trick to during `timm` import only, such that it should not affect all code, but `timm` was really hard to get to work there properly.

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
I don't think this can be really in the hotfix, since it seems a bunch of things would be needed to make `timm` and `torch` work both, so this is going to be 1.9 material.

**Comment by remleduff** [comment]
I just confirmed that adding --module-parameter=torch-disable-jit=no to the factory build works for me.

Is it normal to see:
```
Nuitka-Plugins:WARNING: options-nanny: Module has parameter: Torch JIT is disabled by default, make a choice explicit with '--module-parameter=torch-disable-jit=yes|no'
```

even though I had that on the command line?

**Comment by kayhayen** [comment]
No, that is unexpected, I need to check that out.

**Comment by kayhayen** [comment]
The message should be better now.

**Comment by kayhayen** [comment]
This is now on the develop and the commercial staging branch and part of the latest pre-release, will be part of the 2.0 release that will eventually follow.

**Comment by kayhayen** [comment]
This is part of the stable release 2.0 that I just made.
