### ISSUE TITLE
FATAL: Error, call to 'otool' failed

### ISSUE THREAD

**Issue by xuqiang-idotools** [Nuitka/Nuitka#2501]
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

1.8.4
Commercial: None
Python: 3.10.13 (main, Sep 11 2023, 08:39:02) [Clang 14.0.6 ]
Flavor: Anaconda Python
Executable: /Users/louis/anaconda3/envs/cutkit/bin/python
OS: Darwin
Arch: x86_64
Version C compiler: /usr/local/opt/llvm/bin/clang (clang).

- How did you install Nuitka and Python

  Anaconda.

- The specific PyPI names and versions

anyio==3.7.1
astor==0.8.1
attrdict==2.0.1
Babel==2.12.1
bce-python-sdk==0.8.87
beautifulsoup4==4.12.2
blinker==1.6.2
cachetools==5.3.1
certifi==2023.7.22
charset-normalizer==3.2.0
click==8.1.6
colorama==0.4.6
contourpy==1.1.0
cssselect==1.2.0
cssutils==2.7.1
cycler==0.11.0
Cython==3.0.0
decorator==4.4.2
et-xmlfile==1.1.0
exceptiongroup==1.1.2
fire==0.5.0
Flask==2.3.2
flask-babel==3.1.0
fonttools==4.42.0
future==0.18.3
h11==0.14.0
httpcore==0.17.3
httpx==0.24.1
idna==3.4
imageio==2.31.1
imageio-ffmpeg==0.4.9
imgaug==0.4.0
itsdangerous==2.1.2
Jinja2==3.1.2
kiwisolver==1.4.4
lazy_loader==0.3
Levenshtein==0.21.1
lmdb==1.4.1
lxml==4.9.2
MarkupSafe==2.1.3
matplotlib==3.7.2
moviepy==1.0.3
networkx==3.1
Nuitka==1.8.4
numpy==1.25.2
opencv-contrib-python==4.6.0.66
opencv-python==4.6.0.66
openpyxl==3.1.2
opt-einsum==3.3.0
ordered-set==4.1.0
packaging==23.1
paddle-bfloat==0.1.7
paddleocr==2.7.0.2
paddlepaddle==2.5.1
pandas==2.0.3
pdf2docx==0.5.6
Pillow==10.0.0
premailer==3.10.0
prettytable==3.9.0
proglog==0.1.10
protobuf==3.20.2
psutil==5.9.5
pyclipper==1.3.0.post4
pycryptodome==3.18.0
PyMuPDF==1.20.2
pyparsing==3.0.9
PySide6==6.5.2
PySide6-Addons==6.5.2
PySide6-Essentials==6.5.2
python-dateutil==2.8.2
python-docx==0.8.11
python-Levenshtein==0.21.1
pytz==2023.3
PyWavelets==1.4.1
rapidfuzz==3.2.0
rarfile==4.0
requests==2.31.0
scikit-image==0.21.0
scipy==1.11.1
shapely==2.0.1
shiboken6==6.5.2
six==1.16.0
sniffio==1.3.0
soupsieve==2.4.1
termcolor==2.3.0
thefuzz==0.19.0
tifffile==2023.7.18
tqdm==4.66.1
tzdata==2023.3
urllib3==2.0.4
visualdl==2.5.3
wcwidth==0.2.8
Werkzeug==2.3.6
zstandard==0.21.0

- Many times when you get an error from Nuitka, your setup may be special

  Always.

- Provide in your issue the Nuitka options used

FATAL: Error, call to 'otool' failed: ['/usr/bin/otool', '-L', '/Users/louis/anaconda3/envs/cutkit/lib/python3.10/site-packages/paddle/libs'] -> b"error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't map file: /Users/louis/anaconda3/envs/cutkit/lib/python3.10/site-packages/paddle/libs (Invalid argument)\n".

**Comment by kayhayen** [comment]
This has no reproducer unfortunately.

**Comment by xuqiang-idotools** [comment]
# demo project:
https://github.com/oliverfei/videocr-PaddleOCR.git

#example code or example.py:

from videocr import save_subtitles_to_file

if __name__ == '__main__':
    save_subtitles_to_file('example_cropped.mp4', 'example.srt', lang='ch', time_start='7:10', time_end='7:34',
     sim_threshold=80, conf_threshold=75, use_fullframe=True,
     brightness_threshold=210, similar_image_threshold=1000, frames_to_skip=1)

**Comment by kayhayen** [comment]
I wasn't quite able to get that to run with anything from PyPI, so I assume these are conda packages. Nuitka does have detection of where a package is from in its compilation report with `--report` but I guess, for reporting, we kind of need something that outputs what pip freeze does, but with that information added. Right now I am to guess what kind of Anaconda config I would need to run this.

**Comment by xuqiang-idotools** [comment]
The report has be uploaded, thanks!
[report.xml.zip](https://github.com/Nuitka/Nuitka/files/13053704/report.xml.zip)

**Comment by xuqiang-idotools** [comment]
I think the issue caused by "otool -L" a directory, but not a file in macos.
The directory is "site-packages/paddle/libs" in which incuding some .dylib files.

**Comment by ideogram** [comment]
I experience the same problem, on a Mac M1. Nuitka worked before. Problem started after upgrading mac to Sonomo, so maybe Mac dropped a library or something?

**Comment by ideogram** [comment]
Installing XCODE fixes 1 problem,  but then a new problem occurs:

```
In file included from static_src/CompiledFunctionType.c:2785:
In file included from /Users/my_user_name/Code/my_little_project/venv/lib/python3.9/site-packages/nuitka/build/static_src/CompiledCodeHelpers.c:2097:
/Users/my_user_name/Code/my_little_project/venv/lib/python3.9/site-packages/nuitka/build/static_src/HelpersConstantsBlob.c:1183:29: error: call to undeclared function 'getsectdatafromheader_64'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    unsigned char *result = getsectdatafromheader_64(header, "constants", "constants", &size) + (uintptr_t)header;
                            ^                  
1 error generated.
```

**Comment by kayhayen** [comment]
@ideogram please don't hijack unrelated issues, and don't expect Nuitka 1.2.2 to work as well as 1.8.4 you are wasting my time

**Comment by kayhayen** [comment]
@xuqiang-idotools I noticed that it's a directory too, and it's probably some form of incompatiblity of Nuitka's dependency scan that doesn't support that, or just some garbage left by random build tools, that it's supposed to ignore. That has happened too in the past, since a directory dependency is very strange, unless of course it would be a framework.

**Comment by kayhayen** [comment]
I was probably not clear, but the report didn't yet contain the feature to provide the installer tool name, now it will say `pip` or `conda` in the distribution names on factory which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

With a new report, I should be able to get the tool to reproduce an environment from a report to support conda, and then reproduce the issue almost exactly as you see it hopefully.

**Comment by kayhayen** [comment]
The change is now on develop, and I would need a new report made with it.

**Comment by xuqiang-idotools** [comment]
This problem was temporarily circumvented by the following modifications:

**Comment by kayhayen** [comment]
I need a reproducer though, and for that it seems, I need the new report. Just let me know if you are able to provide it.

**Comment by kayhayen** [comment]
Closing for lack of feedback
