### ISSUE TITLE
['compiled_method' object is not connected] Error Whenever QT disconnect is Called

### ISSUE THREAD

**Issue by tedwgit** [Nuitka/Nuitka#2503]
I found TypeError: "'compiled_method' object is not connected" would always happen during running the generated exe file whenever a QT disconnect is called and executed, while compile process works normally and the executable file could be generated successfully.  Seems like some false assertions are added here in nuitka for these cases.

This error exists both in my own code and some 3rd party QT based libraries where disconnect is called (like some functions of pyqtgraph).

There are 2 similar issues found: #1137, #2492. From #2492, I can see patch for disconnect assertion issue is already updated in factory branch: https://nuitka.net/doc/factory.html  But this error still exists after version 1.9rc5 is installed (previous version is 1.8.4).

I wrote a tiny program just to reproduce this issue, and below is the info.

- python -m nuitka --version
1.9rc5 (also tried 1.8.4)
Commercial: None
Python: 3.9.15 (main, Nov 24 2022, 14:39:17) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\ProgramData\Miniconda3\envs\isp64\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe (cl 14.2).

- Install
Version 1.8.4: pip install nuitka
Version 1.9rc5: python -m pip install -U --force-reinstall "https://github.com/Nuitka/Nuitka/archive/factory.zip"

- Compile cmd
python -m nuitka --standalone --plugin-enable=pyqt6 --output-dir=out disconnect_test.py

- Error log:
d:\Src\DisconnectTest\out\disconnect_test.dist>disconnect_test.exe
Traceback (most recent call last):
  File "D:\Src\DISCON~1\out\DISCON~1.DIS\disconnect_test.py", line 18, in test_event2
TypeError: 'compiled_method' object is not connected

- disconnect_test.py
```
from PyQt6.QtWidgets import QDialog, QApplication
from PyQt6 import uic
from pathlib import Path
import sys

class DisconnectTest(QDialog):
    def __init__(self):
        super().__init__()
        self.ui = uic.loadUi((Path(__file__).parent / "disconnect_test.ui"), self)
        self.button1.clicked.connect(self.test_event1)
        self.button2.clicked.connect(self.test_event2)

    def test_event1(self):
        pass

    def test_event2(self):
        self.button1.clicked.disconnect(self.test_event1)
                      
if __name__ == '__main__':
    app = QApplication(sys.argv)
    w = DisconnectTest()
    w.show()
    sys.exit(app.exec())
```

- disconnect_test.ui
```
<?xml version="1.0" encoding="UTF-8"?>
<ui version="4.0">
 <class>Dialog</class>
 <widget class="QDialog" name="Dialog">
  <property name="geometry">
   <rect>
    <x>0</x>
    <y>0</y>
    <width>400</width>
    <height>300</height>
   </rect>
  </property>
  <property name="windowTitle">
   <string>Test</string>
  </property>
  <widget class="QPushButton" name="button1">
   <property name="geometry">
    <rect>
     <x>100</x>
     <y>120</y>
     <width>75</width>
     <height>23</height>
    </rect>
   </property>
   <property name="text">
    <string>button1</string>
   </property>
  </widget>
  <widget class="QPushButton" name="button2">
   <property name="geometry">
    <rect>
     <x>190</x>
     <y>120</y>
     <width>75</width>
     <height>23</height>
    </rect>
   </property>
   <property name="text">
    <string>button2</string>
   </property>
  </widget>
 </widget>
 <resources/>
 <connections/>
</ui>
```

**Comment by bersbersbers** [comment]
I think it would be essential to report the version of PySide6 you are using. E.g., #2086 occured only in PySide6<6.5.0, and #2492 occured only with >=6.5.2. In addition, 6.5.3 had a connect/disconnect problem in 6.5.3 which is apparently fixed in 6.6.0 (https://bugreports.qt.io/projects/PYSIDE/issues/PYSIDE-2487).

**Comment by tedwgit** [comment]
> I think it would be essential to report the version of PySide6 you are using. E.g., #2086 occured only in PySide6<6.5.0, and #2492 occured only with >=6.5.2. In addition, 6.5.3 had a connect/disconnect problem in 6.5.3 which is apparently fixed in 6.6.0 (https://bugreports.qt.io/projects/PYSIDE/issues/PYSIDE-2487).

What I used in this tiny example is PyQT 6.4.0 instead of PySide6. I know PySide6 is suggested by nuitka due to better support and that's what I prefer in my own projects, but in many cases we may need to compile other guys' projects or modules where PyQT is imported, thus is it possible to add this “disconnect assertion” fix for PyQT as well

**Comment by kayhayen** [comment]
@tedwgit it would be possible, but I think I cannot justify doing it outside of commercial support, or you need to ask your riverbank support, because I am sure you have a license that allows distribution, don't you.

**Comment by kayhayen** [comment]
Closing for lack of feedback
