### ISSUE TITLE
nicegui application runs but no expected window

### ISSUE THREAD

**Issue by retsyo** [Nuitka/Nuitka#2504]
the following simple [nicegui](https://github.com/zauberzeug/nicegui) code can be compiled into a standalone `exe` distribution by using 
```
python.exe -m nuitka --mingw64 --standalone  --report=report.xml  --show-progress --show-memory --debug --output-dir=simple simple.py 
```
the problem is the `simple.exe` > 50MB

so I try to decrease the `exe` file size by 
```
python.exe -m nuitka --mingw64 --standalone --report=report.xml --show-progress --show-memory --debug --nofollow-import-to=asyncio,cffi,websockets,pygments,yaml,email,random,click,multiprocessing,uvicorn,ssl,idna,concurrent,http,xmlrpc,urllib,wsproto,h11,ctypes,colorama,psutil,xml,importlib,gevent,engineio,nicegui,re, --plugin-no-detection --output-dir=simple simple.py
```
now the `exe` is 6MB. 

I run the `exe` and copy missed pacakge by hand for many times. Finnally, the `exe` does not say
```
ModuleNotFoundError: No module named 'SOMETHING'
```
and print `hello` as expected

however, no window appears 

So what is the problem? And how to fix it? Thanks
 

```python
print("hello")

from nicegui import ui
from nicegui import events, ui

ui.label('Hello NiceGUI!')
ui.button('BUTTON', on_click=lambda: ui.notify('button was pressed'))

ui.run(native=True, reload=False)
```

**Comment by Maxwell175** [comment]
I'm not quite sure what you expected to happen. Nuitka does not support you going around Nuitka and copying random stuff in. I'd suggest going back to the command that worked and remove the debug option. From there just disable modules you actually don't use.

**Comment by retsyo** [comment]
no, nothing changes into good even remove the debug option.

As I have stated before, the code should launch a window

**Comment by Maxwell175** [comment]
Did you read what I said about copying? Copying files into the output manually is not supported

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."

**Comment by kayhayen** [comment]
Hard to resist, but don't use `--debug` and complain about file sizes.
