### ISSUE TITLE
`curl_cffi` required `_cffi_backend` and more

### ISSUE THREAD

**Issue by shenjackyuanjie** [Nuitka/Nuitka#2505]
### example program:
```python
from curl_cffi import requests

res = requests.get('http://httpbin.org/get')
print(res.text)
```

### compile command:
```powershell
python -m nuitka --lto=no --clang --msvc=latest --standalone --show-progress --remove-output --assume-yes-for-download --enable-console --output-dir=V:\githubs\luogu\curl_cffi\build --main=main.py
```

### output:
```
❯ .\build\main.dist\main.exe
Traceback (most recent call last):
  File "V:\githubs\luogu\CURL_C~1\build\MAIN~1.DIS\main.py", line 1, in <module>
  File "V:\githubs\luogu\CURL_C~1\build\MAIN~1.DIS\curl_cffi\__init__.py", line 41, in <module curl_cffi>
ModuleNotFoundError: No module named '_cffi_backend'
```

## some tricky fix (still with warnings)

Add 
```yaml
- module-name: 'curl_cffi'
  implicit-imports:
    - depends:
        - '_cffi_backend'
```
After `nuitka/plugins/standard/standard.nuitka-package.config.yml`

### compiler command

> as the same

### output
```
❯ .\build\main.dist\main.exe
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip, deflate, br",
    "Host": "httpbin.org",
    "X-Amzn-Trace-Id": "Root=1-65314792-3f26f6b444e3ecf402736330"
  },
  "origin": "xxxxxxxxxxxxxxx",
  "url": "http://httpbin.org/get"
}

Exception ignored in: <compiled_function Curl.__del__ at 0x000001F8CE489B70>
Traceback (most recent call last):
  File "V:\githubs\luogu\CURL_C~1\build\MAIN~1.DIS\curl_cffi\curl.py", line 101, in __del__
  File "V:\githubs\luogu\CURL_C~1\build\MAIN~1.DIS\curl_cffi\curl.py", line 318, in close
AttributeError: 'NoneType' object has no attribute 'release'
```

## env

```
❯ python -m nuitka --version --clang --msvc=latest
1.8.4
Commercial: None
Python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: V:\githubs\luogu\curl_cffi\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Nuitka-Scons:INFO: MSVC version resolved to 14.3.
Version C compiler: V:\apps\LLVM\bin\clang-cl.exe (clang-cl).
```

```
cffi==1.16.0
curl-cffi==0.5.9
lib-not-dr==0.1.7
Nuitka==1.8.4
ordered-set==4.1.0
pycparser==2.21
zstandard==0.21.0
```

**Comment by kayhayen** [comment]
Thanks for providing the initial yaml config, I will will look at the remaining error glady. 

From my experience, this kind of error may be also upstream, and it seems that only Nuitka outputs this kind of warning during interpreter shutdown and may not even disable it with the `no_warnings` python flag, which would be the minimum I think.

**Comment by kayhayen** [comment]
So, I added a print, and pure Python closes it with `ffi` as imported not being `None` yet, so something about interpreter shutdown and or module release is being incompatible. Python sets global values to None during shutdown, intended causing objects like `ffi` to be released. I wonder if this is a sign of it running too late, most probably `res` destructor holds and releases a reference to a Curl object there, and that is somehow run sooner.

This may just be random, but I never see it in Python, but always with Nuitka.

**Comment by kayhayen** [comment]
So, Nuitka calls `Py_Exit` which is not what the Python interpreter does anymore for at least a while now. I didn't figure out where, but I am kind of assuming that during finalization compiled modules are treated differently. Maybe the loader nowadays gets to decide things, or are just discrimates against non-source/bytecode modules, need to research that in `Py_FinalizeEx` which is where it happens currently.

**Comment by kayhayen** [comment]
Ok, from the looks of it, what must be going on is that the compiled module has an extra reference for some reason, which ends up blocking the easy release, and pushing it to a second phase, where the `None` setting is done. 

```
import sys
print(sys.getrefcount(sys.modules["curl_cffi"]))
```

With Python this prints 2, which means the only reference is actually in `sys.modules` whereas with Nuitka it is 3, which means one reference to the module is leaked and as a result, clearing `sys.modules` will not release it. I need to make a minimal test to see if this happens for any module, or if it takes e.g. compiled functions.

**Comment by kayhayen** [comment]
So, I think i found that, Nuitka might be leaking a reference during import but it seems that didn't help. I also covered the ffi object itself, and the _wrapper extension module, not seeing any reference count differences anymore, so I was thinking maybe the site module non being loaded is making a difference, checking that now.

**Comment by shenjackyuanjie** [comment]
![be64ad5d87ac3833bb5df2a83d5cadc](https://github.com/Nuitka/Nuitka/assets/54507071/8d6a0aa5-8166-4bd3-bfc7-d761d4d64702)

by the way
curl_cffi also have a `cert.pem` data resource file
nuitka need to include it and put it in the `curl_cffi` folder

**Comment by shenjackyuanjie** [comment]
![image](https://github.com/Nuitka/Nuitka/assets/54507071/74c74e2e-e073-4769-8a89-86c2e024ee75)

the `cacert.pem` file is located in here

**Comment by kayhayen** [comment]
I got distracted by a debug mode warning, that is apparently poping up for httplib2 which I saw when compiling this in standalone mode with site mode enabled, just to see if that changes things somehow. I don't think it did change it, but I wanted to do that extra optimization first and it's pretty invasive.

**Comment by kayhayen** [comment]
Seems the reference is badly needed, since classes do not take a reference to the containing module, not do methods, so this has had to be reverted, but it wasn't that anyway. It might be required to build Python to check out how the cleanup of the modules is actually ordered. From the looks of it, shouldn't happen. From tracing, always happens, and is not a matter of silence. With the reference counts adjusted, it would have seemed that they should have been treated the same, but they were not. Maybe a whole new shutdown implementation will be needed ultimately to allow for compiled modules to be stopped in the same way as not compiled ones.

**Comment by T-256** [comment]
FWIW I scheduled few PRs to merge in curl-cffi, that I think all of issue mentioned here would be solved.
You can see final chain of PRs at [no-include](https://github.com/T-256/curl_cffi/tree/no-include) branch.

**Comment by shenjackyuanjie** [comment]
@T-256  glad to hear that!
I'll test that after the pr is merged

**Comment by kayhayen** [comment]
@T-256 seems like a good job

I am adding the data file `cacert.pem` and will close this, the module shutdown behavior not being compatible is not best tracked by keeping this issue open I believe.
