### ISSUE TITLE
Question: Visual Studio Build Tools or Visual Studio

### ISSUE THREAD

**Issue by dineshbvadhia** [Nuitka/Nuitka#2512]
Hello. I have the latest Visual Studio Build Tools (17.7.5) installed on Windows 11 but Nuitka doesn't find it and instead uses cl 14.3.

I don't use Visual Studio. 

How can I make Nuitka use the VS 2022 C++ which is in the Build Tools? Thanks

**Comment by Maxwell175** [comment]
14.3 is the platform tools version, which is separate from the build tools versions.

Version 14.3 is the correct version that goes with Build Tools 2022. Microsoft made their versioning very confusing here.
