### ISSUE TITLE
nuitka 1.8.4 compile tkinter with matplotlib error as :  FATAL: matplotlib: Conflict between user and plugin decision for module 'E:\work...\matplotlib\backends\backend_tkagg.py'.

### ISSUE THREAD

**Issue by avcenter** [Nuitka/Nuitka#2519]
python -m nuitka --version
```
1.8.4
Commercial: None
Python: 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: E:\workspace\PycharmProjects\Py310venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: D:\Programs\mingw64\bin\gcc.exe (gcc).
```
pip list
```
Package         Version 
--------------- ------- 
contourpy       1.1.1
cycler          0.12.1
fonttools       4.43.1
kiwisolver      1.4.5
matplotlib      3.8.0
Nuitka          1.8.4
numpy           1.26.1
ordered-set     4.1.0
packaging       23.2
Pillow          10.1.0
pip             21.1.2
pyparsing       3.1.1
python-dateutil 2.8.2
setuptools      57.0.0
six             1.16.0
wheel           0.36.2
zstandard       0.21.0
```
Error occurs when use:
`python -m nuitka   --standalone   --mingw64 --enable-plugin=tk-inter --noinclude-unittest-mode=allow  --nofollow-import-to=*.tests    --nofollow-import-to=*.distutils   --nofollow-import-to=PIL,numpy,matplotlib      --output-dir=out another_tkinter_matplot.py`
FATAL: matplotlib: Conflict between user and plugin decision for module 'E:\workspace\PycharmProjects\Py310venv\lib\site-packages\matplotlib\backends\backend_tkagg.py'.
Nuitka-Reports:INFO: Compilation report written to file 'nuitka-crash-report.xml'.
Nuitka-Reports:INFO: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug report.

No error occurs  but compile long time when use:
`python -m nuitka   --standalone   --mingw64 --enable-plugin=tk-inter --noinclude-unittest-mode=allow  --nofollow-import-to=*.tests    --nofollow-import-to=*.distutils   --nofollow-import-to=PIL,numpy      --output-dir=out another_tkinter_matplot.py`

After a long time(more than15 minutes on my notebook that bought more than 5 years ago but this notebook nuitka other program are very fast with --nofollow-import-to=PIL,numpy,matplotlib   ),the another_tkinter_matplot.exe will be created,and  it runs well after some modules was copied.
if I can use  --nofollow-import-to=PIL,numpy,matplotlib , I think some minutes can be minus.But now  Nuitka Reports:FATAL: matplotlib: Conflict between user and plugin decision for module 'E:\workspace\PycharmProjects\Py310venv\lib\site-packages\matplotlib\backends\backend_tkagg.py'.
Have any idea process it?
Thanks very much.

Nuitka 0.6.9.6 can be used,and compiled very well and *.exe runs well.

code is here:
`

import tkinter as tk
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from matplotlib.figure import Figure

# 创建 tkinter 窗口
root = tk.Tk()
root.title("Matplotlib in Tkinter")

# 创建 matplotlib 图形
fig = Figure(figsize=(5, 4), dpi=100)
ax = fig.add_subplot(111)
ax.plot([0, 1, 2, 3, 4], [1, 4, 2, 3, 5])

# 将 matplotlib 图形嵌入到 tkinter 窗口中
canvas = FigureCanvasTkAgg(fig, master=root)
canvas.draw()
canvas.get_tk_widget().pack(side=tk.TOP, fill=tk.BOTH, expand=1)

# 运行 tkinter 窗口
tk.mainloop()

`

**Comment by kayhayen** [comment]
It should not output the filename, but the module name. It means to say that you and the plugin disagree on `matplotlib`, and this code triggers it:

```
        # some special handling for matplotlib:
        # depending on whether 'tk-inter' resp. 'qt-plugins' are enabled,
        # their matplotlib backends are included.
        if hasActivePlugin("tk-inter"):
            if module_name in (
                "matplotlib.backends.backend_tk",
                "matplotlib.backends.backend_tkagg",
                "matplotlib.backend.tkagg",
            ):
                return True, "Needed for tkinter matplotlib backend"
```

I agree, that this causing a hard dependency on matplotlib seems wrong. For you as an immediate workaround, the matplotlib plugin should be disabled with `--disable-plugin=matplotlib`, and I need to add checks to it, if it's even allowed for inclusion. So this is a mistake of making it active by default.

I don't get the example code you gave though, does it not import matplotlib, so I am not getting what you are doing there.

**Comment by kayhayen** [comment]
So, it seems where an import `matplotlib.backend.tkagg` is asked for permission, from code like `from matplotlib.backend.tkagg import ...` the decision is triggered and doesn't consider if `matplotlib` or `matplotlib.backend` are permitted. In fact, it probably should used the decision for the parent package or ask that first, or something like that. This is a weakness for the `from` imports, that I feel like I saw before with anti-bloat work.

**Comment by kayhayen** [comment]
So, this code deals with the rejection of a sub-package still attempting the parents:

```
            # When sub-package module import is rejected for whatever reason,
            # still this implies an attempt of the parent, because nothing else
            # will do it otherwise, it of course may also be rejected, but if it
            # is not, otherwise it will be missing.
            #
            # A common case of this happening are extension modules in
            # accelerated mode, for standalone this will of course be rare.
            if decision is False:
```

However, we never get to the part where the decision is `False` because we do not check the full path first. I think we can change `decideRecursion` to first check containing package decisions, and then to apply them to sub-packages if `False`. This will make heavy use of the decision cache, and avoid this issue in its tracks.

**Comment by kayhayen** [comment]
So, adding that it first checks the parent imports upwards, and exits with a negative decision from there, this works with the reproducer I created. Not sure how much of a hotfix this can be. I kind of want to see if Nuitka-Watch changes things from having that with the examples we monitor for changes, so I might just try it.

**Comment by kayhayen** [comment]
Part of the 1.9 release I just made.
