### ISSUE TITLE
most user-built modules dont work on UNC path

### ISSUE THREAD

**Issue by ItsbaileyX3525** [Nuitka/Nuitka#2526]
When using external modules or some built-in modules like turtle fail to load when using UNC paths returning this error:

Traceback (most recent call last):
  File "\\?\UNC\shares-01\studentdocs$\username\Documents\python\Other\built apps\Among us\main.dist\main.py", line 1, in <module>
  File "\\?\UNC\shares-01\studentdocs$\username\Documents\python\Other\built apps\Among us\main.dist\turtle.py", line 107, in <module>
  File "\\?\UNC\shares-01\studentdocs$\username\Documents\python\Other\built apps\Among us\main.dist\tkinter\__init__.py", line 38, in <module>
ImportError: LoadLibraryExW '\\?\UNC\shares-01\studentdocs$\username\Documents\python\Other\built apps\Among us\main.dist\_tkinter.pyd' failed: The parameter is incorrect.

this was using the turtle application using a test file found online, works fine when ran normally (not compiled)

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."

**Comment by ItsbaileyX3525** [comment]
My bad, I was in a rush is all, I will fill it out properly soon

**Comment by kayhayen** [comment]
Create a new issue then please.
