### ISSUE TITLE
Selenium4:  init() got an unexpected keyword argument 'service'

### ISSUE THREAD

**Issue by blippercop** [Nuitka/Nuitka#2528]
I've migrated from selenium 3 to selenium 4 (https://www.selenium.dev/documentation/webdriver/troubleshooting/upgrade_to_selenium_4/#executable_path-has-been-deprecated-please-pass-in-a-service-object) and noticed that the compiled version is not working anymore.
So i've reduced the code to this:

````
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
import os

def get_chromedriver_path():
    chromedriver_path = f'./chromedriver_for_{os.uname().sysname}'
    chromedriver_path = os.path.abspath(chromedriver_path)
    return chromedriver_path

if __name__ == '__main__':
    options = Options()
    options.add_argument("start-maximized")
    webdriver_service = Service(executable_path=f'{get_chromedriver_path()}')
    driver = webdriver.Chrome(options=options,service=webdriver_service)
    url = "https://google.com"
    driver.get(url)

`````
the code runs on the system fine.
compile it with: python3 -m nuitka main.py --standalone --remove-output --show-progress --include-package=urllib3 --follow-imports
 (+ copy package selenium to main.dist)
but executing the binary gives:   File "/python/bin/main.dist/main.py", line 24, in <module>
TypeError: __init__() got an unexpected keyword argument 'service'

#  python3 -m nuitka --version
1.8.5
Commercial: None
Python: 3.9.2 (default, Feb 28 2021, 17:03:44) 
Flavor: Debian Python
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
Distribution: Debian 11
Version C compiler: /usr/bin/gcc (gcc).

- How did you install Nuitka and Python

 I dont remember but I think it was with pip:
 pip list
Package             Version
------------------- ---------
async-generator     1.10
attrs               21.4.0
beautifulsoup4      4.9.3
certifi             2023.7.22
cffi                1.15.1
charset-normalizer  3.2.0
cryptography        41.0.4
dbus-python         1.2.16
decorator           5.0.9
distro-info         1.0
docx                0.2.4
et-xmlfile          1.1.0
future              0.18.3
glpi-api            0.4.0
gssapi              1.6.14
h11                 0.13.0
idna                3.4
jxmlease            1.0.3
ldap3               2.9.1
lxml                4.8.0
ntlm-auth           1.5.0
Nuitka              1.8.5
openpyxl            3.0.7
ordered-set         4.1.0
outcome             1.2.0
Pillow              9.1.0
pip                 23.3.1
pyasn1              0.5.0
pycparser           2.21
PyGObject           3.38.0
pyOpenSSL           22.0.0
pypsrp              0.5.0
pysmb               1.2.7
PySocks             1.7.1
pyspnego            0.1.6
python-apt          2.2.1
python-docx         0.8.11
requests            2.31.0
requests-ntlm       1.1.0
selenium            3.141.0
setuptools          52.0.0
simplejson          3.17.6
six                 1.16.0
sniffio             1.2.0
sortedcontainers    2.4.0
soupsieve           2.2.1
trio                0.21.0
trio-websocket      0.9.2
unattended-upgrades 0.1
urllib3             2.0.4
wheel               0.34.2
wsproto             1.1.0
zstandard           0.22.0

  > python -m pip freeze
# python3 -m pip freeze
async-generator==1.10
attrs==21.4.0
beautifulsoup4==4.9.3
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
cryptography==41.0.4
dbus-python==1.2.16
decorator==5.0.9
distro-info==1.0
docx==0.2.4
et-xmlfile==1.1.0
future==0.18.3
glpi-api==0.4.0
gssapi==1.6.14
h11==0.13.0
idna==3.4
jxmlease==1.0.3
ldap3==2.9.1
lxml==4.8.0
ntlm-auth==1.5.0
Nuitka==1.8.5
openpyxl==3.0.7
ordered-set==4.1.0
outcome==1.2.0
Pillow==9.1.0
pyasn1==0.5.0
pycparser==2.21
PyGObject==3.38.0
pyOpenSSL==22.0.0
pypsrp==0.5.0
pysmb==1.2.7
PySocks==1.7.1
pyspnego==0.1.6
python-apt==2.2.1
python-docx==0.8.11
requests==2.31.0
requests-ntlm==1.1.0
selenium==3.141.0
simplejson==3.17.6
six==1.16.0
sniffio==1.2.0
sortedcontainers==2.4.0
soupsieve==2.2.1
trio==0.21.0
trio-websocket==0.9.2
unattended-upgrades==0.1
urllib3==2.0.4
wsproto==1.1.0
zstandard==0.22.0

I couln't find any other posts about it so I am guessing it's my fault, but maybe someone can quickly confirm that the code above works for them.

**Comment by kayhayen** [comment]
Was the original example working with Python at all?

**Comment by kayhayen** [comment]
Ok, I will check it out, but of course at a low priority, that shouldn't be.

**Comment by kayhayen** [comment]
The example is not usable, since it references a chrome driver in the current directory, that I won't have, so lets ignore it for now.
