### ISSUE TITLE
a reopen of #1599 Nuitka failed to detect DLLs that come from PATH elements with non-unicode characters

### ISSUE THREAD

**Issue by shenjackyuanjie** [Nuitka/Nuitka#2530]
#1599
as the same as #1599
the same problem is still exists in newer version
and non-unicode characters is a situation in chinese/japanese/ otherlanguage developers

my suggest is to change the encoding to `utf-8`

**Comment by shenjackyuanjie** [comment]
<img width="1075" alt="323eb8be201ee8678e0676be9a45ff6" src="https://github.com/Nuitka/Nuitka/assets/54507071/44062aff-680f-45ec-aa24-fc90cebc1706">

**Comment by kayhayen** [comment]
Screenshots are not usable to me, I cannot tell what filename it is, despite having added that information. Please translate the issue template more carefully. There is a reason why screenshots are not allowed.

**Comment by shenjackyuanjie** [comment]
sorry for the screenshots
a simple example `D:/这是一个中文路径` this is a Chinese path

**Comment by kayhayen** [comment]
I was more interested in the path in your actual example, in order to tell where it's coming from.

**Comment by shenjackyuanjie** [comment]
sorry for the example, the original author can't give the path of his issue
but I recreate the situation on my side
give me a little bit of time to summaries it

**Comment by shenjackyuanjie** [comment]
here is the path value and the compile command
and the file in the Chinese path folder, I just use the output folder to make sure depend.exe will find the dll he need inside it, and put the Chinese path at the first one in PATH
http://shenjack.top:5504/upload/ape-gecko-rabbit

here is the crash info
http://shenjack.top:5504/upload/emu-swan-parrot

**Comment by kayhayen** [comment]
Closing for lack of feedback.
