### ISSUE TITLE
File "importlib.py", line 127, in import_module ImportError: DLL load failed while importing _ext: 找不到指定的程序。

### ISSUE THREAD

**Issue by Zgq2021** [Nuitka/Nuitka#2531]
> python -m nuitka --version
![image](https://github.com/Nuitka/Nuitka/assets/115549926/15c52ee8-cce6-4c8d-9080-1f8535495482)

- How did you install Nuitka and Python
I install Nuitka by python -m pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"

> python -m pip freeze
![image](https://github.com/Nuitka/Nuitka/assets/115549926/65e8ada3-b4fb-40f3-8eda-3dede097ce04)

- Provide in your issue the Nuitka options used
`nuitka --standalone --mingw64 --show-progress --show-memory --enable-plugin=numpy --output-dir=out Test.py`

My approach is to first build an empty package in a pure Python environment, and then copy the dependent package into dist.
I would like to provide you with a brief example and attachment, but since the mmcv package itself relies heavily on it, it is difficult to provide attachments. Therefore, I will only provide a brief example and output after resolving the dependency issue. I hope this is useful

- Description
- Example Code
```
import importlib
importlib.import_module("mmcv._ext")
```
- With This Error
```
File "importlib.py", line 127, in import_module
ImportError: DLL load failed while importing _ext: 找不到指定的程序。
```
- mmcv._ext refers to this module
![image](https://github.com/Nuitka/Nuitka/assets/115549926/1695ec17-dfc7-4780-911e-dcba3edeb4a6)
![7f3c40f5286c760cd421e7ed991235f](https://github.com/Nuitka/Nuitka/assets/115549926/f814c9ba-699b-49e1-b9e1-6f6128b61f4c)

- This is the installation method of mmcv
```
pip install -U openmim
mim install mmcv-full
```
https://github.com/open-mmlab/mmcv

**Comment by kayhayen** [comment]
> My approach is to first build an empty package in a pure Python environment, and then copy the dependent package into dist.

This approach is unsupported. I do not care what kinds of errors you encounter executing it.
