### ISSUE TITLE
Require json file at runtime as well

### ISSUE THREAD

**Issue by Devanshudd** [Nuitka/Nuitka#2532]
I have folder structure in which i have Json files, txt files and py files. When i compile with nuitka and make executable file . When i give that executable file to some other system or other person , easily he/she can run that executable in their system but right now it is not possible for me. It asks Json to be present in same folder where I generate after executable file. Error msg is pls use nuitka commercial version. I'm in doubt is it possible with nuitka commercial version or not? Pls help me if anyone is going thorugh this kind of folder structure.

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
