### ISSUE TITLE
Is there any way to import module dynamically ? not while compiling but while running ?

### ISSUE THREAD

**Issue by krunaldodiya** [Nuitka/Nuitka#2534]
Is there any way to import module dynamically ? not while compiling but while running ?

for example, let's compile very simple binary:-

` main.py `

```
import importlib


def main():
    module_file = importlib.import_module("strategy")
    class_name = getattr(module_file, "Strategy")
    class_object = class_name()
    class_object.run()


if __name__ == "__main__":
    main()
```

Let's compile now:
```
python -m nuitka main.py -o trader --follow-imports
```

when running `trader` inside `project` directory, it works!

` directory structure `

- project
   - strategy.py

` strategy.py `

```
class Strategy:
   def run(self):
        print("running")
```

but when I install external pip package:-

` pip install some_package `

```
from some_package import some_class

class Strategy:
   def run(self):
        print("running")
```

it throws `module not found` Error for `some_package`

Please let me know if there is any way to import user defined pip packages, because while compiling binary it is not defined which package will user install and use. So I can not use ` python -m nuitka main.py -o trader --follow-imports
 --include-module=some_package `

_Originally posted by @krunaldodiya in https://github.com/Nuitka/Nuitka/issues/2490#issuecomment-1801174260_

**Comment by kayhayen** [comment]
Yes, feel free to read the help output and user manual of Nuitka.
