### ISSUE TITLE
Simple project with PyTables raises runtime error

### ISSUE THREAD

**Issue by mathiasscroccaro** [Nuitka/Nuitka#2535]
## My setup
```
$ uname -a
Linux mathias-pc 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```
python version: 3.8.16
pipienv version:  2022.7.4
nuitka version: 1.8.5

## The script that I'm trying to compile
```
from tables import *

class Particle(IsDescription):
    name      = StringCol(16)
    idnumber  = Int64Col()
    ADCcount  = UInt16Col()
    TDCcount  = UInt8Col()
    grid_i    = Int32Col()
    grid_j    = Int32Col()
    pressure  = Float32Col()
    energy    = Float64Col()

h5file = open_file("tutorial1.h5", mode="w", title="Test file")
group = h5file.create_group("/", 'detector', 'Detector information')
table = h5file.create_table(group, 'readout', Particle, "Readout example")
```
## The command arguments that I'm using

```
python -m nuitka --include-package-data=tables --include-package-data=ctypes --include-package=tables --standalone test_nuitka.py
```

## The error that it's raising

```
Traceback (most recent call last):
  File "/home/mathias/devgrid/projects/nuitka/test_nuitka.dist/tables/__init__.py", line 26, in <module tables>
  File "/home/mathias/devgrid/projects/nuitka/test_nuitka.dist/ctypes/__init__.py", line 451, in LoadLibrary
  File "/home/mathias/devgrid/projects/nuitka/test_nuitka.dist/ctypes/__init__.py", line 373, in __init__
OSError: libblosc2.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mathias/devgrid/projects/nuitka/test_nuitka.dist/test_nuitka.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/mathias/devgrid/projects/nuitka/test_nuitka.dist/tables/__init__.py", line 28, in <module tables>
  File "/home/mathias/devgrid/projects/nuitka/test_nuitka.dist/ctypes/__init__.py", line 451, in LoadLibrary
  File "/home/mathias/devgrid/projects/nuitka/test_nuitka.dist/ctypes/__init__.py", line 373, in __init__
OSError: /home/mathias/devgrid/projects/nuitka/test_nuitka.dist/tables/libblosc2.so: cannot open shared object file: No such file or directory
```

**Comment by kayhayen** [comment]
This should be simple.

If you are available to do a PR, this can be fixed by adding to the yaml configuration, described here: [https://nuitka.net/doc/nuitka-package-config.html](https://nuitka.net/doc/nuitka-package-config.html)

And here is more of a walk through style post: [https://nuitka.net/posts/nuitka-package-config-kickoff.html](https://nuitka.net/posts/nuitka-package-config-kickoff.html)

Here are a example PRs for other packages:

[#2030](https://github.com/Nuitka/Nuitka/pull/2030) 
[#1993](https://github.com/Nuitka/Nuitka/pull/1993)

**Comment by KevinRodriguez777** [comment]
Good morning Kay, tried my hand at this issue, didn't manage to get too far, once it finds once of the needed dlls, and run the example, tables forkbombs itself, nuitka doesn't detect it.
```yaml
- module-name: "tables"
  anti-bloat:
    - description: "remove tables.tests usage"
      replacements_plain:
        "from .tests import print_versions, test": ""
  dlls:
    - from_filenames:
        prefixes:
          - "libblosc2"
        suffixes:
          - "pyd"
          - "dll"
      when: "win32"
```

**Comment by KevinRodriguez777** [comment]
The MRE given by @mathiasscroccaro and the example provided by PyTables at [Pytables Cookbook](https://www.pytables.org/cookbook/py2exe_howto.html), both work on, and when combined with Nuitka, outputs a working executable when using a conda env.

**Comment by kayhayen** [comment]
For fork bombs, we can use `--experimental=debug-self-forking` and I have a trick in Nuitka-Watch, that prevents fork bombs from having any actual success in their bombing. I will quote it here:

```
import os, sys

if "NUITKA_LAUNCH_TOKEN" not in os.environ:
    sys.exit("Error, need launch token or else fork bomb suspected.")
else:
    del os.environ["NUITKA_LAUNCH_TOKEN"]
```

Actually Nuitka is trying to get ahold of them without the deployment option already, finding "-c" and "-m" options, otherwise I would suggest it adds that now. With the environment variable trick, the fork immediately terminates. I think I am adding a new section to the User Manual even, or typical problems at least, where this is added.

**Comment by kayhayen** [comment]
Closing for lack of feedback.

**Comment by jtc42** [comment]
I'm facing all these issues myself now. I've modified the package config as described by [KRRT7](https://github.com/KRRT7) (happy to submit a PR for this change), and that solves the missing library issue but I'm facing the same fork-bomb problem now.

Adding the `NUITKA_LAUNCH_TOKEN` code doesn't seem to prevent the bomb though, and I'm at a bit of a loss as to what I can try next. 

Any advice would be fantastic, thanks.

**Comment by KRRT7** [comment]
> I'm facing all these issues myself now. I've modified the package config as described by [KRRT7](https://github.com/KRRT7) (happy to submit a PR for this change), and that solves the missing library issue but I'm facing the same fork-bomb problem now.
> 
> ~Adding the `NUITKA_LAUNCH_TOKEN` code doesn't seem to prevent the bomb though, and I'm at a bit of a loss as to what I can try next.~ **EDIT:** Fork-bomb protection works. I'm now trying to identify which part specifically causes the fork bomb so I can add that to the package config and submit a PR including the library _and_ fork-bomb protection.
> 
> **To anyone who might come across this prior to a PR being submitted and accepted:**
> 
> You need to make two changes.
> 
> * Replace `tables` in `standard.nuitka-package.config`
> 
> Since Nuitka does not (yet) support package config merging, you need to replace the `tables` entry in the standard config with
> 
> ```yaml
> - module-name: 'tables' # checksum: 590cadeb
>   anti-bloat:
>     - description: 'remove tables.tests usage'
>       replacements_plain:
>         'from .tests import print_versions, test': ''
>   dlls:
>     - from_filenames:
>         prefixes:
>           - "libblosc2"
>         suffixes:
>           - "pyd"
>           - "dll"
>       when: "win32"
> ```
> 
> * Add `cpuinfo` package config
> 
> Either modify the standard config, or add a user config, containing
> 
> ```yaml
> - module-name: 'cpuinfo.cpuinfo'
>   anti-bloat:
>     - description: 'workaround for forking itself'
>       replacements_plain:
>         "getattr(sys, 'frozen', False)": 'True'
>         'getattr(sys, "frozen", False)': 'True'
>         'CAN_CALL_CPUID_IN_SUBPROCESS = True': 'CAN_CALL_CPUID_IN_SUBPROCESS = False'
>       when: 'win32'
> ```
> 
> This prevents `cpuinfo` from forking the process when compiled with Nuitka by forcing the condition that checks for PyInstaller specifically to always be True, and setting a global that's _also_ required to disable process forking in `cpuinfo`.

thanks for this, is there a reason
```yaml
        "getattr(sys, 'frozen', False)": 'True'
``` is replaced twice?

**Comment by jtc42** [comment]
> > I'm facing all these issues myself now. I've modified the package config as described by [KRRT7](https://github.com/KRRT7) (happy to submit a PR for this change), and that solves the missing library issue but I'm facing the same fork-bomb problem now.
> > ~Adding the `NUITKA_LAUNCH_TOKEN` code doesn't seem to prevent the bomb though, and I'm at a bit of a loss as to what I can try next.~ **EDIT:** Fork-bomb protection works. I'm now trying to identify which part specifically causes the fork bomb so I can add that to the package config and submit a PR including the library _and_ fork-bomb protection.
> > **To anyone who might come across this prior to a PR being submitted and accepted:**
> > You need to make two changes.
> > 
> > * Replace `tables` in `standard.nuitka-package.config`
> > 
> > Since Nuitka does not (yet) support package config merging, you need to replace the `tables` entry in the standard config with
> > ```yaml
> > - module-name: 'tables' # checksum: 590cadeb
> >   anti-bloat:
> >     - description: 'remove tables.tests usage'
> >       replacements_plain:
> >         'from .tests import print_versions, test': ''
> >   dlls:
> >     - from_filenames:
> >         prefixes:
> >           - "libblosc2"
> >         suffixes:
> >           - "pyd"
> >           - "dll"
> >       when: "win32"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * Add `cpuinfo` package config
> > 
> > Either modify the standard config, or add a user config, containing
> > ```yaml
> > - module-name: 'cpuinfo.cpuinfo'
> >   anti-bloat:
> >     - description: 'workaround for forking itself'
> >       replacements_plain:
> >         "getattr(sys, 'frozen', False)": 'True'
> >         'getattr(sys, "frozen", False)': 'True'
> >         'CAN_CALL_CPUID_IN_SUBPROCESS = True': 'CAN_CALL_CPUID_IN_SUBPROCESS = False'
> >       when: 'win32'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This prevents `cpuinfo` from forking the process when compiled with Nuitka by forcing the condition that checks for PyInstaller specifically to always be True, and setting a global that's _also_ required to disable process forking in `cpuinfo`.
> 
> thanks for this, is there a reason
> 
> ```yaml
>         "getattr(sys, 'frozen', False)": 'True'
> ```
> 
> is replaced twice?

I’ll be honest, I checked https://github.com/Nuitka/Nuitka/blob/b0600a3f805b0f2c2194c2735df599d7b9dbdd36/nuitka/plugins/standard/standard.nuitka-package.config.yml#L1829 for a reference implementation, saw you’d done it there, and was so desperate to get this working that I copied it just to improve my chances 😂. Happy to change for a PR.

**Comment by kayhayen** [comment]
I don't mind the duplication, and Nuitka ought to learn, to force certain attributes on a per-module per-package basis, so we don't use source modification there anymore and are more robust.

**Comment by kayhayen** [comment]
I am closing this, as the 2.3.8 hotfix is going to get this right now, directly from the PR.
