### ISSUE TITLE
Question: How to pass options only when compiling a specific module?

### ISSUE THREAD

**Issue by toto-man** [Nuitka/Nuitka#2537]
python -m nuitka --version: 
```
1.8.4
Commercial: None
Python: 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\toto\Desktop\test\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\Hostx64\x64\cl.exe (cl 14.3).
```

python -m pip freeze:
```
anyio==4.0.0
certifi==2023.7.22
charset-normalizer==3.3.0
colorama==0.4.6
crayons==0.4.0
debugpy==1.8.0
h11==0.14.0
httpcore==0.18.0
httpx==0.25.0
idna==3.4
imageio==2.31.5
memory-profiler==0.61.0
Nuitka==1.8.4
numpy==1.26.0
objgraph==3.6.0
ordered-set==4.1.0
piexif==1.1.3
Pillow==10.0.1
pycryptodome==3.19.0
PySide6==6.5.3
PySide6-Addons==6.5.3
PySide6-Essentials==6.5.3
pywin32==306
shiboken6==6.5.3
sniffio==1.3.0
tqdm==4.66.1
urllib3==2.0.6
zstandard==0.21.0
```

I am using a custom-built clang-cl.exe when compiling with Nuitka.

 I wanted to pass custom options to this compiler, and upon checking the user manual, I found out that I can pass options using the CCFLAGS environment variable. 

I set it up and it worked well when I compiled in standalone mode. After further investigation, I found that the options I set were passed to all the compilers that were executed.

Here is my question: Is there a way to pass arbitrary options to the compiler only when compiling a specific module?

**Comment by kayhayen** [comment]
no, there is no such thing, Scons apparently could do it, see https://stackoverflow.com/questions/2013622/scons-overriding-build-options-for-one-file

However, it would take a volunteer to add something like different environments in the scons files for different kinds of files, and even different modules, which will make things overly complicated without having a good use case. You didn't quite detail what yours would be. So far I am good with passing defines to all C modules no problem.
