### ISSUE TITLE
Error running executable that include autoit

### ISSUE THREAD

**Issue by plaasses** [Nuitka/Nuitka#2539]
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  1.7.5
Commercial: None
Python: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\USER\PycharmProjects\USER\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).

I have a python script that uses module "autoit"

When using --onefile and --standalone, i get this error:

 "autoit.py", line 26, in <module autoit.autoit> OSError: Cannot load AutoItX from path: C:\Users\USER\AppData\Local\Temp\ONEFIL~1\autoit\lib\AutoItX_x64.dll
 
 When not using --onefile or --standalone, there is no error 
 
 commands used  - results the same : 
 nuitka --onefile --enable-plugin=tk-inter --enable-plugin=pyqt6 --disable-console aio_main.py
 nuitka --standalone --enable-plugin=tk-inter --enable-plugin=pyqt6 --disable-console aio_main.py

**Comment by plaasses** [comment]
Example code :

(windowName = Any window name that is open)

import autoit as au3
import sys


windowName = "5565-EMS NEW"
print(au3.win_get_handle(windowName))

**Comment by plaasses** [comment]
![image](https://github.com/Nuitka/Nuitka/assets/84514977/299143c9-596f-4db9-8ca7-c1ccef2b61c0)

Sorry for the screenshot - CMD window closes before i can copy

**Comment by kayhayen** [comment]
You can launch a CMD to execute the program, and you should be using stable Nuitka.

If you are available to do a PR, this can be fixed by adding to the yaml configuration, described here: [https://nuitka.net/doc/nuitka-package-config.html](https://nuitka.net/doc/nuitka-package-config.html)

And here is more of a walk through style post: [https://nuitka.net/posts/nuitka-package-config-kickoff.html](https://nuitka.net/posts/nuitka-package-config-kickoff.html)

Here are a example PRs for other packages:

[#2030](https://github.com/Nuitka/Nuitka/pull/2030) 
[#1993](https://github.com/Nuitka/Nuitka/pull/1993)

**Comment by plaasses** [comment]
Thank you so much , i go study links :)

**Comment by plaasses** [comment]
`- module-name: 'autoit'
  dlls:
    - from_filenames:
        relative_path: 'lib'
        prefixes:
          - 'AutoIt'
        when: 'win32'`
        
   Added to yaml configuration , works perfectly now

**Comment by kayhayen** [comment]
Thanks a lot, confirming it works, will be on factory soon.

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by plaasses** [comment]
Tested factory , it is working as well :)

Thank you

**Comment by kayhayen** [comment]
Part of the 1.9 release I just made.
