### ISSUE TITLE
Windows 10 not executing created .exe file

### ISSUE THREAD

**Issue by MrJiggsaw** [Nuitka/Nuitka#254]
Before submitting an Issue, please review the [Issue Guidelines](https://github.com/kayhayen/Nuitka/blob/master/CONTRIBUTING.md#submitting-an-issue).

* Please check whether the bug was already reported or fixed.

* Please check out if the develop version of Nuitka works better for you.

  Download source, packages [from here](http://nuitka.net/pages/download.html)
  where you will also find instructions how to do it via PyPI.

If you want to post a problem/bug, to help us understand and resolve your issue
please check that you have provided at least the information below, and discard
up to here:

*  Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

   python -m nuitka --version

*  How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
   what is a virtualenv ...), this is very important usually.

*  If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
   that demonstrates the issue i.e a small piece of code which reproduces
   the issue and can be run with out any other (or as few as possible)
   external dependencies.

*  If this is a regression (used to work in an earlier version of Nuitka),
   please note what you know about that.

**Comment by MrJiggsaw** [comment]
I have recently started with Nuitka and I am having an issue on running executable file which shows an undesirable error .It successfully creates .dist folder and .build with no error or warnings.But when I tried to run the executable file inside .dist folder I have an error

![error_nuitka](https://user-images.githubusercontent.com/26304423/52577674-9ee76a80-2e48-11e9-8405-3b3451487885.JPG)

**Comment by MrJiggsaw** [comment]
Any help related to this will be appreciated

**Comment by kayhayen** [comment]
No help is possible due to total absence of any information requested in the issue template.

**Comment by MrJiggsaw** [comment]
![first](https://user-images.githubusercontent.com/26304423/52580497-81b59a80-2e4e-11e9-8d76-3225742303e4.JPG)
![second](https://user-images.githubusercontent.com/26304423/52580498-81b59a80-2e4e-11e9-857e-48c4e96b464c.JPG)
![third](https://user-images.githubusercontent.com/26304423/52580503-8417f480-2e4e-11e9-8c83-42bd2e887124.JPG)





I hope so this is enough.I am a noob . Any guide will also be appreciated

**Comment by JorjMcKie** [comment]
As @kayhayen said: Python and Nuitka version are missing.
Get them via `python -m nuitka --version`.
How did you install Nuitka?
Then, your program is **Trial1.exe**, which seems to execute (however not doing anything).
Can you share the trial1.py script?

**Comment by kayhayen** [comment]
@JorjMcKie I closed the issue due to total lack of filling out the issue template and "noob" doesn't mean you cannot try. I am not patient enough for this. I did however see that there is `pefile` used, so that might be interesting, a pity we were not getting information here.

**Comment by JorjMcKie** [comment]
@kayhayen - ok, just thought one step of more help would help ... and yes: what he did send might have been an interesting case.

**Comment by MrJiggsaw** [comment]
Ok I understood the python version I am using is 3.6.5 and the nuitka is 0.6.1.1 
I just installed it by pip install Nuitka .It installed just fine 

Then I was going through user manual  where I found Windows standalone execution of file and I just pasted the given code 
It finely created .dist and .build file 

Then I tried to execute the Trial file inside it ,but it gave me some address error .I thought it might be a gcc issue so I reinstalled it and again ran the Nuitka code but still the same issue

**Comment by kayhayen** [comment]
I am doing the 0.6.2 like tomorrow. The `pefile` code is not even present in that version, so it definitely has nothing to do with that.

BTW: I meant to make `nuitka --version` output the compiler and its version. But what good is it when people can't be bothered to execute it for their reports. 

Whatever you mean with `gcc` may well not be the right one @MrJiggsaw that is at least my assumption for now.

**Comment by MrJiggsaw** [comment]
nuitka --version
0.6.1.1                                                                                                                                                               Python: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]                                                                                  Executable: C:\Python\python.exe                                                                                                                                      OS: Windows                                                                                                                                                           Arch: x86_64  



I tried even without pefile but still gives the same error:
python -m nuitka --standalone Trial1.py

Still the same error

What do you expect me to do??

**Comment by JorjMcKie** [comment]
@MrJiggsaw please send me the `Trial1.py` script, I am willing to try it on my machine. I am using VS 2017  C++ compiler.
Have you checked which compiler you are using? There are limitations as to which ones are [supported](https://github.com/Nuitka/Nuitka#requirements) ...,

**Comment by MrJiggsaw** [comment]
Trial1 Script : 
import math
print(math.sqrt(9))
++++++++++++++++++++++++++++
Using minGW  compiler

**Comment by kayhayen** [comment]
Use MinGW64 as desribed in the user manual.

**Comment by MrJiggsaw** [comment]
mingw-w64
Tried this, it fails 

What else I am expected to try??

**Comment by JorjMcKie** [comment]
I made `Trial1.py` with these instructions

```python
import math
print(math.sqrt(9))
```

Compiled via this command, incl. test log:

```
D:\Jorj\Desktop\Develop\Nuitka>python -m nuitka --standalone --mingw64 
--disable-dll-dependency-cache --experimental=use_pefile trial1.py

D:\Jorj\Desktop\Develop\Nuitka>cd trial1.dist

D:\Jorj\Desktop\Develop\Nuitka\trial1.dist>trial1
3.0

D:\Jorj\Desktop\Develop\Nuitka\trial1.dist>
```

I have the compiler at `C:\mingw64` which I downloaded from Sourceforge as a ZIP (`x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z`) and **unzipped / copied** its resp. folder to `C:\`). This is the resulting version:
```
C:\mingw64\bin>gcc -dumpversion
8.1.0

C:\mingw64\bin>
```

In my environment variables I have:
`CC` = `C:\Mingw64\bin\gcc.exe`
and the following 2 entries in the `PATH` variable: `...;C:\MinGW64;C:\MinGW64\bin;`

I am using `Microsoft Windows [Version 10.0.17134.590]` 64bit, and

```
D:\Jorj\Desktop>python -m nuitka --version
0.6.2rc4
Python: 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Users\Jorj\AppData\Local\Programs\Python\Python37\python.exe
OS: Windows
Arch: x86_64

D:\Jorj\Desktop>
```

Wrapping up:
I cannot tell how you do that, but you **must** be using the wrong compiler.

**Comment by MrJiggsaw** [comment]
@JorjMcKie I tried it again with your compiled code ,but it gives me the same issue ,I dont know why??
My gcc version is updated.Like it compiles c programs efficiently and executes it perfectly but fails when I try it with Nutika

![gcc_snippet](https://user-images.githubusercontent.com/26304423/52860209-cd20bf00-3154-11e9-9b5b-0c0dd262313f.JPG)

**Comment by MrJiggsaw** [comment]
Can anyone help me with this??What mistake am I making?

**Comment by JorjMcKie** [comment]
@MrJiggsaw - without actually looking at your machine, there is no telling what may be wrong.

My best guess: there is a mixture between 32bit and 64bit components happening at some point. The exception message you are getting looks like that at least.

My advice: 
* Mimik everything I did as documented above - every single bit of my setup - Windows **environment variables**, mingw64 download file and setup, etc. Install the same Python version as I did (3.7.2 64bit).
* Make sure you get the bitness right of each and every single component!
* Then repeat the compile in exactly the way I did it.
* Make a **complete** directory list of the dist folder and include it here. Do **not** send a screen print, but a text file
* I will then compare the sizes of my and your binaries
* Buy me a beer (not a coffee)

**Comment by MrJiggsaw** [comment]
Ok I'll try this one more time and if it worked ,beer is confirmed

**Comment by kayhayen** [comment]
Maybe you are a victim of #225 not being solved. You definitely have to make the correct choices, both 32 bits or both 64 bits, or else it shouldn't compile. But something @deajan reports there makes me thing, this configuration that used to error out, may not compile, but not work or so.

**Comment by MrJiggsaw** [comment]
I tried like everything about executing with the mingw link given .It gives me another error ,So I tried installing it manually using mingw64 bit given but it gives me the same error .The (mingw)link given in the user manual gives me the following error: 

This was the first popup given .I selected the following

![first](https://user-images.githubusercontent.com/26304423/53284984-2dc98080-3781-11e9-8e5d-41a4e413dd39.JPG)

And then it gives me the error:

![second](https://user-images.githubusercontent.com/26304423/53284990-3fab2380-3781-11e9-94da-a94ae8987976.JPG)

I then downloaded from the following link:
https://sourceforge.net/projects/mingw-w64/

Then it completes successfully but while executing fails

**Comment by kayhayen** [comment]
The screenshots look all wrong to me. Could be standard MinGW if my memory serves well.

Maybe you want to try and follow my Anaconda setup as described in the user manual. You use that Python, which contains a lot, and can simply install a MinGW64 via it, and have it work. Currently the easiest setup of all. There is no way for you to get the arches wrong which is our current suspect. :)

Otherwise, this will have to wait until I find the time to make sure wrong MinGWs are detected more reliably.

Yours,
Kay

**Comment by kayhayen** [comment]
http://nuitka.net/doc/user-manual.html#id7

Forgot to send the link.

**Comment by MrJiggsaw** [comment]
What about this link it serves for mingw64:
https://sourceforge.net/projects/mingw-w64/

**Comment by amanpreets01** [comment]
Ok Thank you so much for the time >
I have figured it out and its working now.
