### ISSUE TITLE
App compiling and working fine using PyInstaller but not with Nuitka

### ISSUE THREAD

**Issue by krunaldodiya** [Nuitka/Nuitka#2544]
Hi There,

I am very new to Nuitka, I had a closed issue: https://github.com/Nuitka/Nuitka/issues/2534 after that I read docs and I was success in compiling the app.

```
./build.sh
```

### PyInstaller Output
```
INFO:     Will watch for changes in these directories: ['/mnt/WorkSpace/Code/hello']
INFO:     Uvicorn running on http://0.0.0.0:5555 (Press CTRL+C to quit)
INFO:     Started reloader process [41671] using StatReload
INFO:     Started server process [41678]
INFO:     Waiting for application startup.
hello
INFO:     Application startup complete.
```

### Nuitka Output
```
INFO:     Will watch for changes in these directories: ['/mnt/WorkSpace/Code/hello']
INFO:     Uvicorn running on http://0.0.0.0:5555 (Press CTRL+C to quit)
INFO:     Started reloader process [41671] using StatReload
```

App stuck at `INFO:     Started reloader process [41671] using StatReload`

I am adding a github repository url: https://github.com/krunaldodiya/hello

When i compile same app with PyInstaller, It works but wih Nuitka, Its is compiling successfully but application is not running, Can you take a look and help me out.

Sorry if it was too noob, any help would be appreciated.

Thanks

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
