### ISSUE TITLE
Scan Reports

### ISSUE THREAD

**Issue by StellarSeeker** [Nuitka/Nuitka#2547]
Hello Kay Hayen,

I was developing an application with PySide6 and noticed an interesting situation. When I converted the .py file to an executable (using GCC), 20 antivirus companies flagged the resulting .exe file as malware. However, when I compiled the same .py file with Mingw64, only 5 antivirus companies detected it as malware. Additionally, the reports indicate that the application communicates with specific IP addresses.

First scan (flagged by 20 antivirus companies): Report link
https://www.virustotal.com/gui/file/83cf527fa8e01292f874e175e3f6f8582e3fa2d894bafa47b93689764aa722c8/behavior

Second scan (compiled with Mingw64, flagged by 5 antivirus companies): Report link
https://www.virustotal.com/gui/file/71899b4903e5fd935507d830370d7dd5d102bf22f446289d5df8bd01914a2182/behavior

What could be the reason for this?

I understand there are commercial solutions, Due to my financial situation, I cannot afford the commercial version.. Is there any way, even if limited, to address this issue?

I apologize if I am mistaken. Thank you in advance.

**Comment by kayhayen** [comment]
See the User Manual about AV problems, I cannot work for free on AV and create a free Python compiler.

**Comment by StellarSeeker** [comment]
Alright, thank you Kay Hayen.
