### ISSUE TITLE
Gradio UI is not responsive after being packaged with Nuitka

### ISSUE THREAD

**Issue by es617** [Nuitka/Nuitka#2548]
Background: see here https://github.com/Nuitka/Nuitka/issues/2540

```
1.9rc7
Commercial: None
Python: 3.11.5 (main, Sep 11 2023, 08:31:25) [Clang 14.0.6 ]
Flavor: Anaconda Python
Executable: /Users/first_lastname/Projects/gradio_test/myenv/bin/python
OS: Darwin
Arch: arm64
Version C compiler: /usr/bin/clang (clang 14.0.3).
```

When running Nuitka 1.9rc7 from factory, I am able to package and run the example code below, but once I open the Gradio UI on the browser, the UI is not responsive. Upon inspecting the developer console on the browser, I see some JavaScript exceptions.

```
import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")

if __name__ == "__main__":
    demo.launch(show_api=False)
```

To debug (again assume nuitka 1.9rc7 from factory)
```
nuitka --static-libpython=no  --follow-imports --include-data-dir=./gradio_test/data=data --noinclude-setuptools-mode=nofollow --standalone --macos-create-app-bundle --clang gradio_test/main2.py
```

```
 ./main2.app/Contents/MacOS/main2
```

Open the browser and follow `http://127.0.0.1:7860`

In Chrome, go to View->Developer->Developer Tools
Select Console, reload the page, and try to press any button in the UI.
This is what I see
<img width="552" alt="image" src="https://github.com/Nuitka/Nuitka/assets/64611135/60937839-2fee-449e-a9a0-f1ad85cb2aa1">

I am not super familiar with how Gradio works under the hood, but there is a JavaScript portion of the framework used to build the frontend. When installing gradio from source, the first step is to build the frontend (scripts/build_frontend.sh - which ultimately calls `pnpm build`).  I suspect Nuitka is not including some of the frontend files in the package. 

One additional thing I noticed (this might be an unrelated issue), when loading the page, I see an error for a POST request. Upon inspecting the payload of that request, the payload has an empty "version" field. This field is not empty if launching the unpackaged script.

<img width="352" alt="image" src="https://github.com/Nuitka/Nuitka/assets/64611135/065a4ec8-5d9f-41e3-a212-f411e1a8b583">

**Comment by es617** [comment]
update here - I got it to work by adding the flag `--import-data-package=gradio`

this added the following files, and now the simple seem to be working fine

<img width="262" alt="image" src="https://github.com/Nuitka/Nuitka/assets/64611135/44a41428-13cd-4c84-8cff-c9d931b7ef60">

**Comment by kayhayen** [comment]
I guess, I only stumbled over "templates" during its startup, but seems `_frontend_code` surely is at least essential, and the version might be coming from package.json, just a hunch, need to check that. This is going to be 1.9 hotfix material though, since I largely want to get that out of the door ASAP now.

**Comment by es617** [comment]
sounds good, thanks for looking into it. I can manually include the package data until then. Thanks!

**Comment by kayhayen** [comment]
I added it on the factory branch and it will be part of 1.9 release, which got delayed enough to finish this on the side with your input.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
Part of the 1.9 release I just made.
