### ISSUE TITLE
trouble compiling with --include-distribution-metadata=pandas and without --include-distribution-metadata=pandas

### ISSUE THREAD

**Issue by ArEnSc** [Nuitka/Nuitka#2549]
I think there is a bit of a regression on factory, we discussed that it might be more complex in discord.
I was gonna write a ticket but it was mentioned not to that in the github issue template.

- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.
1.9rc7 factory branch e7eaea90ae40248a11c1c3bd1f04337d892639c3
Commercial: None
Python: 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\Tensor\Desktop\jsonformertest\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

Installed via Pip3 cloned repo on factory branch.
# download from here https://huggingface.co/TheBloke/OpenHermes-2-Mistral-7B-AWQ 
# git clone the repo then when cloned use git 
# lfs pull to get the model.

```python
from awq import AutoAWQForCausalLM
from transformers import AutoTokenizer, TextStreamer
## loop over numbers from 1 to 10

def main():
    quant_path = r"C:\Users\Tensor\Desktop\jsonformertest\OpenHermes-2-Mistral-7B-AWQ" 
    quant_file = r"model.safetensors"

    # Load model
    model = AutoAWQForCausalLM.from_quantized(quant_path, quant_file, fuse_layers=True)
    tokenizer = AutoTokenizer.from_pretrained(quant_path, trust_remote_code=True)
    streamer = TextStreamer(tokenizer, skip_special_tokens=True)

    # Convert prompt to tokens
    prompt_template = """\
    A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions.

    USER: {prompt}
    ASSISTANT:"""

    tokens = tokenizer(
        prompt_template.format(prompt="How are you today?"), 
        return_tensors='pt'
    ).input_ids.cuda()

    # Generate output
    generation_output = model.generate(
        tokens, 
        streamer=streamer,
        max_new_tokens=512
    )

main() When run should output just text.
```

The issue is when using this build command

python -m nuitka --standalone --include-package=huggingface_hub.repocard,huggingface_hub.hf_file_system,sentencepiece,transformers.models.falcon.configuration_falcon,transformers.models.musicgen.configuration_musicgen,transformers.models.mpt.configuration_mpt,transformers.models.deprecated.open_llama.configuration_open_llama,safetensors --include-distribution-metadata=sentencepiece,safetensors --include-distribution-metadata=accelerate --include-distribution-metadata=datasets --include-distribution-metadata=peft --include-distribution-metadata=jinja2 --include-distribution-metadata=openai --include-distribution-metadata=psutil  --include-distribution-metadata=torchaudio 
--include-distribution-metadata=torchvision --include-distribution-metadata=torch --include-distribution-metadata=pandas --report=report --plugin-enable=anti-bloat --noinclude-unittest-mode=allow main.py
When I run the main.exe it tells me to:
--include-distribution-metadata=pandas

When I compile it without that flag
FATAL: Error, including metadata for distribution 'pandas' without including related package 'pandas.libs'
The build exits

It's a catch 22 thanks!

**Comment by kayhayen** [comment]
So, what's going on there, is that `pandas` and `pandas.libs` are provided by the distribution `pandas`, however, during its discovery of what these packages are, it finds both, and then picks only one.

**Comment by kayhayen** [comment]
And then it insists, that should be part of your program, but it is not. This happens with any `import pandas` and then `--include-stribution-metadata=pandas`, of course were `pandas.libs` included, that would be fine. We should make sure that we do consider nested names there.

**Comment by kayhayen** [comment]
Hm, actually top_level.txt of pandas claims it contains `pandas.libs` only as that's the only line there, clearly a packaging bug I guess.

**Comment by ArEnSc** [comment]
@kayhayen Thanks hopefully you are doing well these days!
