### ISSUE TITLE
PySide2 slot cannot be found by qml after compile with nuitka.

### ISSUE THREAD

**Issue by MarkCL** [Nuitka/Nuitka#255]
Nuitka: 0.6.1.1
PySide2: 5.12.1
Python: 3.7.2
MacOS 10.14.3

Used PySide2 to load a qml file as UI. Click the Button on the UI will get an error message(TypeError: Property 'test_function' of object Manager(0x7fe888d10a10) is not a function). Before building through Nuitka (with --recurse-all), everything works fine(print string "OK" when the button clicked).

Example:

TestQmlPySide2.py

    import sys
    from PySide2.QtGui import QGuiApplication
    from PySide2.QtQml import QQmlApplicationEngine
    from PySide2.QtCore import QObject, Slot
    
    
    class Manager(QObject):
        def __init__(self, parent=None):
            QObject.__init__(self, parent)
    
        @Slot()
        def test_function(self):
            print("OK")
    
    
    if __name__ == '__main__':
        app = QGuiApplication(sys.argv)
        manager = Manager()
        engine = QQmlApplicationEngine()
        engine.rootContext().setContextProperty("Manager", manager)
        engine.load('TestQmlPySide2.qml')
        if not engine.rootObjects():
            sys.exit(-1)
        sys.exit(app.exec_())

TestQmlPySide2.qml

    import QtQuick 2.12
    import QtQuick.Window 2.12
    import QtQuick.Controls 1.4
    import QtCharts 2.3

    Window {
        title: qsTr("Test")
        width: 640
        height: 480
        visible: true
        Button {
            text: qsTr("Click Me")
            onClicked: Manager.test_function()
        }
    }

**Comment by kayhayen** [comment]
This is a duplicate/complement of #170 as suspected, callbacks do not work with PySide2, it will need patches.

Anybody willing to look into this, volunteer here.

**Comment by kayhayen** [comment]
For standalone there would be #205 but it has no point until this one is resolved. I think it stalled precisely because compiled functions are ignored by PySide2.

**Comment by kayhayen** [comment]
The commercial PySide2 wheels solve this, as does using PySide6 which officially supports nuitka: https://nuitka.net/pages/pyside2.html
