### ISSUE TITLE
Question: Will asynchronous threads be changed to synchronous execution?

### ISSUE THREAD

**Issue by YaoJusheng** [Nuitka/Nuitka#2553]
python3 -m nuitka --version:
```text
1.8.6
Commercial: None
Python: 3.8.10 (default, May 26 2023, 14:05:08) 
Flavor: Debian Python
Executable: /home/.venv/protest/bin/python3
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 20.04.6
Version C compiler: /usr/bin/gcc (gcc).
```

I use code similar to the following in flask:
```python3
def async_thread(f):

    @wraps(f)
    def wrapper(*args, **kwargs):
        t = Thread(target=f, args=args, kwargs=kwargs)
        t.start()

    return wrapper
```
I  want to change the synchronous method to asynchronous execution through the decorator.

However, after compiling with nuitka, when I ran it, I found that the asynchronous mode had been changed back to synchronization.

```shell
python3 -m nuitka --show-progress --quiet --disable-ccache --module app --include-package=app --nofollow-imports --remove-output --no-pyi-file --clang
```
Does nuitka not support using asynchronous threads in this way? Or are there any special parameter options that I missed?

At the same time, I found that `flask_mail` could not send emails in the compiled execution program. What was the reason for this?

**Comment by kayhayen** [comment]
It seems you first and foremost missed that reports need a minimal reproducer, not just a code sample.

**Comment by YaoJusheng** [comment]
> It seems you first and foremost missed that reports need a minimal reproducer, not just a code sample.

Ok. Here is a simple example:

```python3

import os
import time
from functools import wraps
from threading import Thread

from flask import Flask
from flask_mail import Mail, Message
from flask_restx import Resource, Api
from dotenv import load_dotenv

load_dotenv(".env", override=False)


class Config:
    MAIL_SERVER = os.environ.get("MAIL_SERVER")
    MAIL_PORT = os.environ.get("MAIL_PORT")
    MAIL_USE_TLS = os.environ.get("MAIL_USE_TLS")
    MAIL_USERNAME = os.environ.get("MAIL_USERNAME")
    MAIL_PASSWORD = os.environ.get("MAIL_PASSWORD")
    MAIL_DEFAULT_SENDER = os.environ.get("MAIL_DEFAULT_SENDER")


app = Flask(__name__)
app.config.from_object(Config)
mail = Mail(app)
api = Api(
    app,
    doc='/doc',
    version='0.0.1',
    titles="Flask Test Demo",
)


def async_thread(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        t = Thread(target=f, args=args, kwargs=kwargs)
        t.start()

    return wrapper


@async_thread
def do_something():
    print("To do...")
    time.sleep(10)
    print("Done.")


@async_thread
def send_simple(to_email):
    print("Start to send email...")
    with app.app_context():
        msg = Message(
            "Hello",
            sender=app.config["MAIL_DEFAULT_SENDER"],
            recipients=[to_email]
        )
        msg.body = "testing"
        msg.html = "<b>testing</b>"
        mail.send(msg)
    print("Send over.")


@api.route('/hello')
class HelloWorld(Resource):
    def get(self):
        # something to do
        do_something()
        return {'hello': 'world'}


@api.route('/email/<string:email>')
class SendSimple(Resource):
    def post(self, email):
        send_simple(email)
        return {"result": f"email has been sent to {email}"}


if __name__ == '__main__':
    app.run(debug=True, port=5000)
```

The dependency packages are as follows:
```text
Flask==2.3.2
flask-restx==1.1.0
Flask-Mail==0.9.1
python-dotenv==0.14.0
nuitka==1.8.6
```

Nuitka used as follows:
```shell
python3 -m nuitka --show-progress --quiet --disable-ccache --module app.py --nofollow-imports --remove-output --no-pyi-file --clang
```

he app runs as follows:
```shell
uwsgi --http :9090 --thunder-lock --module app:app
```

Go to `http://127.0.0.1:9090/doc` for testing.

After doing the above, I found problems with asynchronous threads and sending emails.

**Comment by kayhayen** [comment]
Which way of finding problems will make the problem visible?

**Comment by YaoJusheng** [comment]
> Which way of finding problems will make the problem visible?

When I tested these two interfaces, I found that the thread seemed to be suspended. 
The thread did not exit after 10 seconds, and the previous one would not end until the second same request.

The interface for sending mail does not actually perform sending.

I describe it this way, is it acceptable?

**Comment by kayhayen** [comment]
I am having a hard time to get data files to work here. I kind of have high doubts that you know what you were doing, since you must have copied files manually, and who knows how well. I am adding these, but `flask_restx` is having strange ideas about where it wants to find them it seems, not the typical package or I am being dumb.

**Comment by kayhayen** [comment]
I have updated factory, but I never came close to observing what you claim, which is also very likely wrong anyway. I believe you were jumping to conclusions. I added the data files and both APIs seem to work fine in quick succession, which is I guess sufficient evidence of threads being used. Not sending email properly is possible, but in pure Python your program was giving a bunch of errors, to me, so I will just ignore it now.

**Comment by kayhayen** [comment]
I will track this issue until 1.9 release which should be soon, and then likely delete it, since it seems very invalid in all claims made.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by YaoJusheng** [comment]
> I have updated factory, but I never came close to observing what you claim, which is also very likely wrong anyway. I believe you were jumping to conclusions. I added the data files and both APIs seem to work fine in quick succession, which is I guess sufficient evidence of threads being used. Not sending email properly is possible, but in pure Python your program was giving a bunch of errors, to me, so I will just ignore it now.

Maybe you should check the information printed on the console after calling the two APIs, and you may have new insights.

As for getting a bunch of errors in pure python? I did not find that the python version in my environment is 3.8.10.

**Comment by YaoJusheng** [comment]
> Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html
> 
> Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

Thank you for your reply, but I tried it, and the final performance of the factory branch does not seem to have changed. Of course, my previous conclusion may not be so accurate, it is just a guess. The title is indeed inappropriate, but the problem does exist. Pass It can be seen from the console output that 'Done' is not printed after 10 seconds. There is indeed a problem with the performance of the asynchronous thread. This is actually the main problem at present.

Thanks again for your quick reply, I'll try other solutions as well.

**Comment by KevinRodriguez777** [comment]
keep in mind your thread is a not actually asynchronous, it's still synchronous but it's added to a thread, that being said, i work a lot with concurrent proxified requests, threaded *and* actual asynchronous requests, i have never observed nuitka change the behavior of how they're executed, i'm with kay on this, this isn't something that's happening on the nuitka side.

**Comment by KevinRodriguez777** [comment]
> > keep in mind your thread is a not actually asynchronous, it's still synchronous but it's added to a thread, that being said, i work a lot with concurrent proxified requests, threaded _and_ actual asynchronous requests, i have never observed nuitka change the behavior of how they're executed, i'm with kay on this, this isn't something that's happening on the nuitka side.
> 
> That's right. It's not really asynchronous, it's just formal. But before and after compilation, judging from the execution results, there seems to be a problem with the newly opened thread after compilation, and this is exactly the problem that needs to be solved.

can you make an MRE that doesn't involve any of the flask overhead?

**Comment by kayhayen** [comment]
I honestly cannot play around with a web GUI to find potential issues. It was interesting to learn of `flask_restx` it's pretty neat, I have used postman before I think, years ago as an external solution. But anything that involves me guessing what the expected outcome is clearly is a nogo. I didn't have errors in my console output that did not already appear with Python. I think it hates mail not being setup. 

This adds to this not being minimal, since it obviously depends on your setup. I am not here to debug that. And your claimed issue, I feel like I may have heard of it before if true.

**Comment by YaoJusheng** [comment]
> > > keep in mind your thread is a not actually asynchronous, it's still synchronous but it's added to a thread, that being said, i work a lot with concurrent proxified requests, threaded _and_ actual asynchronous requests, i have never observed nuitka change the behavior of how they're executed, i'm with kay on this, this isn't something that's happening on the nuitka side.
> > 
> > 
> > That's right. It's not really asynchronous, it's just formal. But before and after compilation, judging from the execution results, there seems to be a problem with the newly opened thread after compilation, and this is exactly the problem that needs to be solved.
> 
> can you make an MRE that doesn't involve any of the flask overhead?

I plan to use nuitka to compile the flask application. Therefore, I cannot bypass flask. 
However, I tested and found that if it is compiled into an executable binary file alone, there does not seem to be this problem. I am trying to combine it with click.

As for the problems with module compilation, I will find time to remove flask and test it separately.

**Comment by kayhayen** [comment]
The data file things are part of the 1.9 release I just made.
