### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv._ext'

### ISSUE THREAD

**Issue by Zgq2021** [Nuitka/Nuitka#2555]
> python -m nuitka --version
![image](https://github.com/Nuitka/Nuitka/assets/115549926/20529907-525f-4fb6-a38c-57b1ce7cf76f)

- How did you install Nuitka and Python
I install Nuitka by python -m pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"

> python -m pip freeze
Due to the need for many front-end packages, I am unable to take a screenshot for you. Here is the installation process of the front-end package
```
pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113
pip install -U openmim
mim install mmcv-full
mim install mmdet==2.28
```

- Provide in your issue the Nuitka options used
`nuitka --standalone --mingw64 --show-progress --show-memory --noinclude-unittest-mode=allow --output-dir=out Test.py`

I would like to provide you with a brief example and attachment, but since the mmcv package itself relies heavily on it, it is difficult to provide attachments. Therefore, I will only provide a brief example and output after resolving the dependency issue. I hope this is useful

- Description
- Example Code
```
import importlib
importlib.import_module("mmcv._ext")
```
- With This Error
![image](https://github.com/Nuitka/Nuitka/assets/115549926/431191c7-196d-47f3-a066-cfa232c92614)

https://github.com/open-mmlab/mmcv

**Comment by kayhayen** [comment]
Please learn copy and paste of text from consoles.
