### ISSUE TITLE
Build python script as a dynamic library

### ISSUE THREAD

**Issue by TNtube** [Nuitka/Nuitka#2560]
Hello,

I'm very interested on using Nuitka as a part of a personnal project that bridge between python and C++.

But for performance purposes, I was wondering if Nuitka provide any tools to build dynamic library (.dll, .so, ....). I wasn't able to find any documentation about it.

Is it even possible ?
And if so, how could I call python functions inside my C++ project ?

Thanks.

**Comment by kayhayen** [comment]
It is possible, but I do not support achieving this currently outside of Nuitka commercial higher tiers.
