### ISSUE TITLE
Flask with Templates 

### ISSUE THREAD

**Issue by TheShoes** [Nuitka/Nuitka#2561]
Hello, 

First of thank you for Nuitka.  It is working great. Well except i cant figure one thing out. 

I am using Nuitka to wrap my flask app up.  When I do this the flask api points are open and it works great.  The only issue is i dont have my html in and am using separate files for that.  

What I would like to do is have my html and take advantage of the flask render templates.  This way the html can be inside the app itself.   
Everything works as expected when i run the flask app with python.  HTML works perfectly. 
When I try to package it i get :

TemplateNotFound.   
jinja2.exceptions.TemplateNotFound: index.html

Is there a command that I am missing when creating a build?

Thank you

**Comment by Maxwell175** [comment]
You haven't filled out the issue template. But please try checking out the section on working with data files on the manual.

**Comment by TheShoes** [comment]
yeah you are correct... I was just about to jump on to answer this.  
what i needed to do was just include the folders in my command line to create the build.  
 --include-data-dir=templates=templates --include-data-dir=static=static 
 Thank you very much for your help
