### ISSUE TITLE
[errorno 2] No such file or directory

### ISSUE THREAD

**Issue by li-jun-fei** [Nuitka/Nuitka#2564]
a onefile exe package build by nuitka, while executing on the windows 10, error raised: no such file or directory: [some of my ***.py scripts file] 

here is my build command:
python -m nuitka vSphereCollector.py --company-name='company' --product-name='vSphere health Checker' --product-version=1.0 --windows-icon-from-ico=static/image/check.png  --include-data-dir=static=static  --include-data-dir=templates=templates --onefile --output-dir=vSphereCollector.dist --include-module=paramiko --include-module=pyVmomi --include-module=pyVim --include-module=vsanmgmtObjects --include-module=vsanapiutils   --include-module=packaging  --include-module=defusedxml    --run
![56bc3c83bfbdb66f415ee7266aa780f](https://github.com/Nuitka/Nuitka/assets/25841343/75983328-a76f-4c79-8781-2fd1e7e07d3a)

**Comment by li-jun-fei** [comment]
installed visual studio community 2022 with componnets:
msvc v143 (latest)
llvm(clang-vl) tools msbuild uspport
Windows c++ clang build(16.0.5)
Windows 10 sdk

**Comment by li-jun-fei** [comment]
I use importlib.util to dynamic  loads some script module, Is this the cause that nuitka does not include this scripts?
But after I used switch --include-module to include these script module explicitly, It‘s still has the same  issue

**Comment by kayhayen** [comment]
Actual screenshots even @Maxwell175 :-)
