### ISSUE TITLE
Cannot connect to slots that start on __

### ISSUE THREAD

**Issue by enaix** [Nuitka/Nuitka#2567]
Attemting to connect to a slot which starts on double dash causes an error (see example)

`self.test.connect(self.__test)`

`AttributeError: 'Caller' object has no attribute '_Caller__test'`

The issue is present in both develop and 1.9 versions. Took a while to find the cause of the bug haha

  > python -m nuitka --version
1.9
Commercial: None
Python: 3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)]
Flavor: CPython Official
Executable: /Users/flynn/src/smartwheel-core/venv2/bin/python
OS: Darwin
Arch: arm64
Version C compiler: /opt/homebrew/opt/llvm/bin/clang (clang 16.0.6).

- How did you install Nuitka and Python

Installed via pip in separate virtualenv. Python flavor is official cpython (from python website).

<details>
<summary>The specific PyPI names and versions</summary>

alabaster==0.7.13
astroid==3.0.1
Babel==2.12.1
certifi==2023.5.7
charset-normalizer==3.1.0
contourpy==1.0.7
cycler==0.11.0
darkdetect==0.7.1
dill==0.3.7
docutils==0.20.1
fonttools==4.39.4
idna==3.4
imagesize==1.4.1
isort==5.12.0
Jinja2==3.1.2
kiwisolver==1.4.4
MarkupSafe==2.1.3
matplotlib==3.7.1
mccabe==0.7.0
Nuitka==1.9
numpy==1.24.3
ordered-set==4.1.0
packaging==23.1
Pillow==9.5.0
platformdirs==4.0.0
py-midi==2.0.1
Pygments==2.15.1
pylint==3.0.2
pynput==1.7.6
pyobjc-core==9.1.1
pyobjc-framework-ApplicationServices==9.1.1
pyobjc-framework-Cocoa==9.1.1
pyobjc-framework-Quartz==9.1.1
pyparsing==3.0.9
PyQt6==6.5.0
PyQt6-Qt6==6.5.0
PyQt6-sip==13.5.1
pyqtdarktheme==2.1.0
pyserial==3.5
python-dateutil==2.8.2
python-rtmidi==1.4.9
requests==2.31.0
six==1.16.0
smartwheel-core @ file:///Users/flynn/src/smartwheel-core
snowballstemmer==2.2.0
Sphinx==7.0.1
sphinxcontrib-applehelp==1.0.4
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
swcolorpicker==1.4.3
tomli==2.0.1
tomlkit==0.12.3
tqdm==4.66.1
typing_extensions==4.8.0
urllib3==2.0.3
zstandard==0.21.0

</details>

## Example

```
from PyQt6.QtCore import pyqtSignal, pyqtSlot
from PyQt6.QtWidgets import QWidget, QApplication, QMainWindow

# nuitka-project: --enable-plugin=pyqt6


class Caller(QWidget):
    test = pyqtSignal()

    def __init__(self, parent=None):
        super(Caller, self).__init__(parent)
        self.test.connect(self.__test)
        self.test.emit()

    @pyqtSlot()
    def __test(self):
        print("test")


class Window(QMainWindow):
    def __init__(self):
        super().__init__()
        self.caller = Caller(self)
        

if __name__ == "__main__":
    app = QApplication([])
    win = Window()
    win.show()
    app.exec()

```

**Comment by kayhayen** [comment]
What strikes me is that the method name is a private function name, I believe that should play a role here.

**Comment by kayhayen** [comment]
So, for `@pyqtslot` Nuitka applies a workaround, to make it behave better with PyQt5. I am not even sure it's needed with PyQt6, but what it does is to compile the decorated function as bytecode, and that then fails to know that it is inside a class, and doesn't apply private name resolution.

There is no good solution to this at all, and probably there are potentially also more issues generated by this. I need to research if there is any way of telling `compile` built-in any of this.

**Comment by enaix** [comment]
So, for now it is better to make the slots public. I hope that others will find this issue in case of a similar problem

**Comment by kayhayen** [comment]
I have a workaround for it that makes it work for the specific example, but generally this workaround is kind of fragile until we solve it properly.

**Comment by kayhayen** [comment]
In #2415 I will try and devise a more general solution, that does not use bytecode for the function, but only for an wrapping of the entry point, hiding the compiled function that then exists again.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
The specific example works now with 1.9.1 but e.g. using private attributes inside of methods decorated as slots, will still be broken. Follow that in the other issue I mentioned.
