### ISSUE TITLE
Cannot set CC to directory path, but must use filename instead.

### ISSUE THREAD

**Issue by anderspersson** [Nuitka/Nuitka#257]
**nuitka version:**	 0.6.1.1
**Python version:**	Python: 3.7.2 MSC v.1916 64 bit (AMD64)
**Executable**: C:\dev_tools\Python37\python.exe
**OS**: Windows
**Arch**: x86_64
**All installed using** PIP
**Compiler** MingGW64 installed att  c:\mingw64
**version** g++.exe (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
**Compiler path** = c:\mingw64\bin

**Enviroment set/used**
CC=c:\mingw64
NUITKA_CLCACHE_BINARY=C:\dev_tools\Python37\Scripts\clcache.exe

**Python program i try to build**
----------hello.py------------------------
```
def talk(message):
    return "Talk " + message

def main():
    print( talk("This is a test message"))

if __name__ == "__main__":
    main()
```
----------------------------------------------

**Build command:**
	python -m nuitka --standalone --remove-output --mingw64 --show-progress --experimental=use_pefile --python-arch=x86_64  --show-scons .\hello.py 

**Also tested** 
	python -m nuitka --standalone hello.py

**Error:**
scons: Told to run compilation on 4 CPUs.
scons: Found clcache 'C:\dev_tools\Python37\Scripts\clcache.exe' to cache object files for 'C:\MinGW64'.
Scons: Launching target: ['hello.dist\\hello.exe']
scons: done reading SConscript files.
scons: Building targets ...
scons: building `hello.build\module.__main__.o' because it doesn't exist
g++ -o hello.build\module.__main__.o -c /EHsc /J /Gd /Ox /MT -D_NUITKA_EXPERIMENTAL_USE_PEFILE -D_NUITKA_STANDALONE -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_RESOURCE -D_NUITKA_FROZEN=168 -D_NUITKA_MODULE_COUNT=448 -D_NUITKA_EXE -IC:\dev_tools\Python37\include -IC:\dev_tools\Python37\PC -Ihello.build -IC:\dev_tools\Python37\lib\site-packages\nuitka\build\include -IC:\dev_tools\Python37\lib\site-packages\nuitka\build\static_src hello.build\module.__main__.cpp
scons: building `hello.build\__constants.o' **because it doesn't exist**
g++ -o hello.build\__constants.o -c /EHsc /J /Gd /Ox /MT -D_NUITKA_EXPERIMENTAL_USE_PEFILE -D_NUITKA_STANDALONE -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_RESOURCE -D_NUITKA_FROZEN=168 -D_NUITKA_MODULE_COUNT=448 -D_NUITKA_EXE -IC:\dev_tools\Python37\include -IC:\dev_tools\Python37\PC -Ihello.build -IC:\dev_tools\Python37\lib\site-packages\nuitka\build\include -IC:\dev_tools\Python37\lib\site-packages\nuitka\build\static_src hello.build\__constants.cpp
scons: building `hello.build\__frozen.o' **because it doesn't exist**
g++ -o hello.build\__frozen.o -c /EHsc /J /Gd /Ox /MT -D_NUITKA_EXPERIMENTAL_USE_PEFILE -D_NUITKA_STANDALONE -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_RESOURCE -D_NUITKA_FROZEN=168 -D_NUITKA_MODULE_COUNT=448 -D_NUITKA_EXE -IC:\dev_tools\Python37\include -IC:\dev_tools\Python37\PC -Ihello.build -IC:\dev_tools\Python37\lib\site-packages\nuitka\build\include -IC:\dev_tools\Python37\lib\site-packages\nuitka\build\static_src hello.build\__frozen.cpp
scons: building `hello.build\__helpers.o' **because it doesn't exist**
g++ -o hello.build\__helpers.o -c /EHsc /J /Gd /Ox /MT -D_NUITKA_EXPERIMENTAL_USE_PEFILE -D_NUITKA_STANDALONE -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_RESOURCE -D_NUITKA_FROZEN=168 -D_NUITKA_MODULE_COUNT=448 -D_NUITKA_EXE -IC:\dev_tools\Python37\include -IC:\dev_tools\Python37\PC -Ihello.build -IC:\dev_tools\Python37\lib\site-packages\nuitka\build\include -IC:\dev_tools\Python37\lib\site-packages\nuitka\build\static_src hello.build\__helpers.cpp
g++: error: /EHsc: No such file or directory
g++: error: /J: No such file or directory
g++: error: /Gd: No such file or directory
g++: error: /Ox: No such file or directory
g++: error: /MT: No such file or directory
g++: error: /EHsc: No such file or directory
g++: error: /J: No such file or directory
g++: error: /Gd: No such file or directory
g++: error: /Ox: No such file or directory
g++: error: /MT: No such file or directory
g++: error: /EHsc: No such file or directory
g++: error: /J: No such file or directory
g++: error: /Gd: No such file or directory

**Comment by kayhayen** [comment]
A couple of comments to make: The `clcache` is for MSVC only and should have no impact.

The CC variable must point to a gcc.exe, not a directory.

The messsage you refer to is absolutely normal Scons output. The object file does't exist, which is why Scons will build it (not in cache).

The g++ which should not be used is called with MSVC options. Not sure why, but that definitely should not happen I guess. I will check if it is due to you using a directory, or due to you using the environment variable. Anyway, this should definitely error out much saner. I will try and add respective checks.

**Comment by anderspersson** [comment]
The error was that CC was set to CC=c:\mingw64
not CC=c:\mingw64\bin\gcc.exe
/A
 
I have now documented how to set up a working environment in Windows 10 using mingw64
I can write it down I en step-step guide if it would help other Windows user?

**Comment by kayhayen** [comment]
@anderspersson such a guide would be very welcome, what format would you use? We are using ReST for the user manual, and I will hopefully soon make available a nuitka-web repository where we should probably have this, that is Nikola and ReST then too. Depending on the format you prefer, it will be easy to convert though.

I once had a Wiki going, but it was dying all along until spammers abused it, so I gave up on that. Not sure if we want to use the GH Wiki maybe. Do you?

**Comment by kayhayen** [comment]
As for the issue, I added checks against providing a directory path, these are now caught and reported as an error for both `CC` and `CXX` (which nobody should use, but well, similar code). I am closing it because I will release today anyway, and it's not something anybody would find anyway.

**Comment by anderspersson** [comment]
Great, i will do a draft and we can talk about format later, i will be text only, and easy to format to any system later.
Where do i send it?

**Comment by kayhayen** [comment]
@anderspersson if you want to, a pull request with changes to the `README.rst` would be most welcome.

I was considering that to be sort of a starting point for a Tutorial. First step always has to be "I am stupid, just get me going quickly" point, where you do this, and then run the software to play with it, without knowing all the details, but a few things being demonstrated.

Anyway, if you want something easier, private email is fine, but I like pull requests. :-)

**Comment by anderspersson** [comment]
Pull request is fine for me, /A
