### ISSUE TITLE
Tkinter standalone test doesn't use TCL

### ISSUE THREAD

**Issue by kayhayen** [Nuitka/Nuitka#258]
The test of Tkinter for standalone mode is far too weak. It has always passed despite #137 and that was probably the root cause of this not being detected earlier.

However, I lack all the knowledge to make a tkinter test that is headless. For PyQt5 and other things, we tend to have it, but often the headless nature makes things difficult. In my Buildbot tests, there should be no Windows popping up (I use my main desktop for it, and my own account).

So we need to enhance the test to cover this. I am hoping @JorjMcKie can help us out here.

That way his glorious plugin which I am going to release later today will be tested, and cannot break as easily in the future as it otherwise could.

**Comment by kayhayen** [comment]
I have assigned this to you @JorjMcKie which I hope is OK for you, let me know if I ought to wait for you to take it. :) It would be very nice to have a PR that adds something that will make it fail when executed without your plugin and pass with it. The test runner will use your plugin for that test automatically btw.

I am speaking of this one:

https://github.com/Nuitka/Nuitka/blob/bc22aa833c22e2f5f55304ec47b57c71c6adf16d/tests/standalone/TkInterUsing.py#L27

As you can see, very impressive test coverage. I hope I can rely on you to expand this is a bit. If it's hard (headless for a GUI framework) then OK, we can also try and make me shout out about this on Twitter.

**Comment by JorjMcKie** [comment]
@kayhayen - sure, I will take it on.

**Comment by JorjMcKie** [comment]
submitted the PR

**Comment by JorjMcKie** [comment]
Given the design of the Tkinter plugin, I could also have checked the existence of the respective `os.environ` value(s), i.e. without even importing tkinter - just doing a `assert os.environ.get("TCL_LIBRARY", None)`.
But then ... who knows what may happen to the plugin one day?

**Comment by kayhayen** [comment]
Thanks a lot. I also forgot that when I enabled the plugin.

With your changes, Linux was now properly failing, I have a fix for that on my factory, adding system TCL/Tk installation to the whilelisted files that are allowed to be used. I am about to push as soon as Travis liked it for real. Closing this and thanks a lot.

To me this is mostly about having a test that will break when I make re-factorings to the plugins, and then will only learn much later about it breaking.

Also thanks for the speedy reaction. Made my day. :)

**Comment by JorjMcKie** [comment]
any time again - I assure you.
As I mentioned: I am a retired man having plenty of time

**Comment by kayhayen** [comment]
@JorjMcKie so if you are OK with that, I would define kind of well defined work packages for you and assign you to it and try to grow you into all the things. Right now I would start out with the Plugin API now that we have http://nuitka.net/apidoc generated with Doxygen. 

But to be honest, I don't even know what sort of annotations it expects there. Since you sort of figured out the plugin API in parts at least, I thought it would be good if you looked at the methods in those base classes, and documented them, so @deajan and everybody have an easier time creating plugins.

This would get a bug stone off my chest. Otherwise, I think one area where I am clueless, and you may not be, is Windows and performance measurements like I do with Valgrind. Running things many times to make the error small is taking too long. Is there a way to get at CPU tick counters accounted for the process, or something. That is another research topic.

Another area would be the replacing of `mt.exe` and `rc.exe` usages in Nuitka with `ctypes` and Win32 API calls. There is an issue about multi size icons that would need that. And obviously that would make Nuitka a lot less dependent on proper Windows API tools.

Next week, I will be able to settle down a bit again and define these well. For the Plugin API there is no real well defined task, and you can start with that if you want to immediately. The others, I should probably create an issue and include all I know about this. That is always a good idea anyway.

And then, if you don't mind, I would try and get you into optimization on the Python side of things step by step too. There is plenty of relatively isolated and well definable tasks that I would love to see you take on. This will definitely be fun.

**Comment by JorjMcKie** [comment]
Sounds great to me. I am fine with all of that, but start with Plugin API as you suggest.

During my professional career I have always loved optimization stuff, so I am looking forward to that, too.

**Comment by kayhayen** [comment]
Preparing to leave into offline world right now, but my mind wanted to something that is there, let me call it "exception control flow optimization".

You know, `try: import ... except ImportError import python3_module` how cool would it be to be able to optimize those statically. That will make a real difference, but I am no where even close to continuing that one, but there is already some infrastructure for that. Ok, don't hold me to it, but I will definitely aim at writing up that one. Feels perfect. API is definitely a headline task. But that would be big too.

**Comment by JorjMcKie** [comment]
"Aha - of course!" was my rection to your last comment. Compilation always also implies making decisons (Python version, platform, OS), which could be used to remove now unnecessary code ...

**Comment by JorjMcKie** [comment]
Want to focus on plugin API now. Installed doxygen and read through the manual.
Please point me to where the source of the http://nuitka.net/apidoc live.

**Comment by JorjMcKie** [comment]
Please ignore my previous post. Figured out how it works.
Finished about 80% to 90% of the plugin API docu in the plugin source code and doxygen is nicely generating it.
Next step will be to adjust the Developer Manual accordingly.
There are a few methods of PluginBase I have no idea about what they do or I am uncertain about the correct description:

```python
def _createTriggerLoadedModule(module, trigger_name, code)
    """ ??? """

def onModuleEncounter(self, module_filename, module_name, module_package, module_kind)
    """ ??? """

def decideRecursion(module_filename, module_name, module_package, module_kind)
    """ Return bool as to whether we should recurse into it.
        What is module_kind?"""

def recurseTo(module_package, module_filename, module_kind, reason, signal_change)
    """Recurse into this ... meaning of module_kind, reason, signal_change?"""

def removeDllDependencies(self, dll_filename, dll_filenames)
    """ ??? """
```

**Comment by JorjMcKie** [comment]
I am also planning to provide a dummy user plugin as a practical guide ...

**Comment by JorjMcKie** [comment]
Here are more questions which arose from writing a user plugin as a separate python module:

1. Coding ``--user-plugin=file.py`` in the command line treats `file.py` like a normal plugin. The ``plugin_name`` is ignored - except its ``bool()`` must be ``True``. Correct?
2. Consequently, there is no way to specify warnings if not used, correct?
3. There is no way to specify options for this type of plugin - correct?

**Comment by JorjMcKie** [comment]
@kayhayen - my status:

# Plugin API Documentation
Finished documenting `PluginBase.py`, `NumpyPlugin.py`, `TkinterPlugin.py`, which includes testing doxygen results of that.
**Important finding:** in order to get nice/meaningful doxygen output,
    1. option `OPTIMIZE_OUTPUT_JAVA   = YES` **must be set!**
    2. for documentation of Nuitka Python classes and methods, a different approach must be used. Instead of

```python
def foo(a, b):
    """ comment ..."""
```
the following is required:

```python
## Function foo does blah, blah
# @param a is blah
# @param b is also blah
# @returns ...
def foo(a, b):
```
IAW, these objects must be **prefixed** with comments like this. Any trouble here? pylint issue?

# User Plugin Example and Plugin Option Documentation
Created a simple plugin for demo purposes. This should find its place in the developer manual. SHould I just update that as part of my soon docu PR?

Created a documentation / How-To for plugin option usage. Also put in developer manual?

# Missing Support of User Plugin Options
Tested a few things around that and found an easy way to include this feature. It is basically this:
* user plugins provided as `--user-plugin=script.py` can use a syntax similar to standard plugins: `--user-plugin=script.py=a,b,c`
* only minor changes are required to support this:
    - user plugins **must** set `plugin_name = __file__`
    - `Options.py`, method `getPluginOptions` must search for the plugin_name in concatenation `options.plugins_enabled + options.user_plugins`
    - `Plugins.py` must strip off the options tail from the filename when eating the user plugins

Any comments?

**Comment by kayhayen** [comment]
@JorjMcKie Changing the strings from doc strings is a bit of work, but I think not an issue, looks good to me in terms of result, actually brilliant.

**Comment by kayhayen** [comment]
I am OK with your PR updating doc strings and manuals all over the place, @JorjMcKie and feel free to move this discussion to a PR as soon as you are ready for it. You can also just push branches without yet making the request, I see those too. But a PR is nice for making comments directly along code.

The user plugin arguments look good to me. It's the same then, but I assume needs code changes from you to work.

The `__file__` naming of plugins is something we could do via its meta class. I think there is a `__module__` attribute that the user plugin base class could use, via `__file__` or maybe even `__name__`.

Not having a warning for an unused user plugin is because it is active by default, no detectors, right? That is probably OK. I wonder if passive plugins should indicate that, but lets not over engineer it in the end. The user plugins should be a nice precursor and easy to turn into a PR for Nuitka.

**Comment by kayhayen** [comment]
As for `module_kind`, I think it indicates if it's an extension module (`.so`/`.pyd`), if it is included as bytecode (`.pyc`/frozen inside product) or as a compiled module (inside product).

I need to look at the functions you mentioned for a proper response, I think I will manage later today.
