### ISSUE TITLE
exception：pandas read_csv codec

### ISSUE THREAD

**Issue by zjb6975017** [Nuitka/Nuitka#2583]
error:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 3: invalid continuation byte

version:
nuitka1.8.6
python 3.7.9
pandas 1.3.5

compile cmd：
python -m nuitka --mingw64 --standalone --follow-stdlib --nofollow-import-to=pandas,numpy --show-progress --show-memory  --output-dir=o2  .\main.py

i make sure that the file is utf-8,and it's run ok before use nuitka

**Comment by zjb6975017** [comment]
the code is very simple:
import pandas as pd
pd.read_csv('xxx.csv')

**Comment by kayhayen** [comment]
I like the `area` annotation, there are however commands for what you are asked for in the issue template. Using `--nofollow-import-to=pandas,numpy` is not some form of "make pandas work better", it is a "make it not work" option.

**Comment by zjb6975017** [comment]
I used this option` --nofollow-import-to=pandas,numpy` because these two packages are too large. I called them by adding the path of the package in sys. path


> I like the `area` annotation, there are however commands for what you are asked for in the issue template. Using `--nofollow-import-to=pandas,numpy` is not some form of "make pandas work better", it is a "make it not work" option.

**Comment by KevinRodriguez777** [comment]
> I used this option` --nofollow-import-to=pandas,numpy` because these two packages are too large. 
you're importing them though, so it needs them to run properly
> I called them by adding the path of the package in sys. path。i guess that this problem is not related to this option.
what does this mean? does that mean that the code you showed isn't the actual code that's being compiled by nuitka?

**Comment by zjb6975017** [comment]
> > I used this option` --nofollow-import-to=pandas,numpy` because these two packages are too large.
> 
> you're importing them though, so it needs them to run properly
> 
> > I called them by adding the path of the package in sys. path。i guess that this problem is not related to this option.
> 
> what does this mean? does that mean that the code you showed isn't the actual code that's being compiled by nuitka?

Because I couldn't find the built-in library on my own after compiling to exe, I wrote the Python package path into the system in the code

I only compiled the calling code during compilation, but I did not compile the pandas/numpy packages themselves
