### ISSUE TITLE
Long Path on Windows: FileNotFoundError

### ISSUE THREAD

**Issue by dmmoeu** [Nuitka/Nuitka#2584]
Seems like Nuitka can't write long path files on Windows. Even if long path is enabled on the machine.

- Please check whether the bug was already reported or fixed.

Didn't find any long path related issues

- Please check out if the develop version of Nuitka works better for you.

Same error with Nuitka '2.0rc3' on Python '3.11'

- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version

```
1.8.2
Commercial: 2.2.5
Python: 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
Flavor: CPython Official
Executable: path\to\Local\Programs\Python\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64\cl.exe (cl 14.3).
```

- How did you install Nuitka and Python

pip install git

- The specific PyPI names and versions

  > python -m pip freeze

```
Nuitka @ nuitka-commercial
ordered-set==4.1.0
zstandard==0.22.0
```

- Many times when you get an error from Nuitka, your setup may be special

- Also supply a Short, Self Contained, Correct, Example

```
from pathlib import Path

# > 260 ?
p = Path.cwd() / "veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeery" / "looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong" / "paaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaath"

# this is working
# p = Path.cwd() / "short" / "path"

print(len(str(p)))
p.mkdir(parents=True, exist_ok=True)
print(Path.exists(p))

# python .\test_long_path.py
# outputs
# 294
# True

# .\test_long_path.dist\test_long_path.exe
# outputs
# 294
# Traceback (most recent call last):
#   File "<cwd>\TEST_L~1.DIS\pathlib.py", line 1116, in mkdir
# FileNotFoundError: [WinError 3] The system cannot find the path specified: '<cwd>\\veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeery\\looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong\\paaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaath'

# During handling of the above exception, another exception occurred:

# Traceback (most recent call last):
#   File "<cwd>\TEST_L~1.DIS\test_long_path.py", line 10, in <module>
#   File "<cwd>\TEST_L~1.DIS\pathlib.py", line 1121, in mkdir
#   File "<cwd>\TEST_L~1.DIS\pathlib.py", line 1116, in mkdir
# FileNotFoundError: [WinError 3] The system cannot find the path specified: '<cwd>\\veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeery\\looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong\\paaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaath'
```

- Provide in your issue the Nuitka options used

`python -m nuitka --standalone .\test_long_path.py`

- Consider getting commercial support

We are on commercial

**Comment by kayhayen** [comment]
So, enabling it can be done with saving this reg file:

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem]
"LongPathsEnabled"=dword:00000001
```

After which, Python can do it, and Nuitka cannot. Needless to say, since the setting is not default, no application ought to rely on it, but that's besides the point. It's standard `mkdir` of Python library that fails here, so it absolutely has to be about the program and Python.exe having a difference.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory and staging branches, which are development versions under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working. 

Also this is slated for 1.9.4 hotfix release that I expect to do within a couple of days as well.

**Comment by kayhayen** [comment]
Part of the 1.9.4 hotfix release.
