### ISSUE TITLE
skimage/sklearn regression on 1.9.1 -> 1.9.2

### ISSUE THREAD

**Issue by danielj-genesis** [Nuitka/Nuitka#2586]
1.9.2
Commercial: None
Python: 3.8.10 (default, Nov 27 2023, 14:56:03) 
Flavor: Unknown
Executable: /home/administrator/Documents/test_nuitka/albu/env/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.2
Version C compiler: /usr/bin/gcc (gcc 11).

Python3.8.10 built from source, created a venv

```
python -m pip freeze:
albumentations==1.1.0
imageio==2.33.0
joblib==1.3.2
lazy-loader==0.3
networkx==3.1
Nuitka==1.9.2
numpy==1.24.4
opencv-python-headless==4.8.1.78
ordered-set==4.1.0
packaging==23.2
Pillow==10.1.0
PyWavelets==1.4.1
PyYAML==6.0.1
qudida==0.0.4
scikit-image==0.21.0
scikit-learn==1.3.2
scipy==1.10.1
threadpoolctl==3.2.0
tifffile==2023.7.10
typing-extensions==4.8.0
zstandard==0.22.0

```

This breaks on Nuitka 1.9.2 with an immediate segmentation fault when trying to import albumentations:
```
import albumentations

print('hello')

```
`python -m nuitka --standalone test.py`

On Nuitka 1.9.1 this works fine

I found this trying to compile my project and got the same immediate segfault so I narrowed it down to albumentations after placing some logs but I'm not sure if something else is affected after the import too.

The app is okay on 1.9.1 so I'll use that for now.

**Comment by kayhayen** [comment]
That's kind of surprising to hear, but possible still, maybe the `dict.get` fix is somehow an issue, but otherwise I don't see what would be, if I manage to reproduce it, git bisect will tell us though.

**Comment by kayhayen** [comment]
For what it's worth, I reproduced it with my current development version, now checking with `--debugger`, also doing some anti-bloat work that will avoid dask and ipython in there, for smaller compile, but it's always annoying to search for bugs in large compiles. With the C traceback, maybe it becomes obvious if it's related to the change I mentioned.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by danielj-genesis** [comment]
I tested the app again on factory and it's working well now :+1:

**Comment by kayhayen** [comment]
Part of the 1.9.3 release I just made.
