### ISSUE TITLE
matplotlib error: ImportError: DLL load failed while importing _tkinter

### ISSUE THREAD

**Issue by Snopylz** [Nuitka/Nuitka#2588]
1.0.6
Commercial: None
Python: 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Program Files\Python39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

python installed from .exe, dont use virtual environment
pip install nuitka==1.0.6

altgraph==0.17.4
cycler==0.12.1
fonttools==4.45.1
importlib-metadata==6.8.0
kiwisolver==1.4.5
matplotlib @ file:///C:/Users/msj/Downloads/matplotlib-3.5.2-cp39-cp39-win_amd64.whl
Nuitka==1.0.6
numpy @ file:///C:/Users/msj/Downloads/numpy-1.22.4%2Bvanilla-cp39-cp39-win_amd64.whl
packaging==23.2
pefile==2023.2.7
Pillow==10.1.0
pyinstaller-hooks-contrib==2023.10
pyparsing==3.1.1
python-dateutil==2.8.2
pywin32-ctypes==0.2.2
six==1.16.0
zipp==3.17.0

**Code:**
import numpy as np
import matplotlib as mpl

import matplotlib.pyplot as plt

mpl.rcParams['xtick.labelsize'] = 24
mpl.rcParams['ytick.labelsize'] = 24
np.random.seed(42)
x = np.linspace(0, 5, 100)
y = 2*np.sin(x) + 0.3*x**2
y_data = y + np.random.normal(scale=0.3, size=100)
plt.figure('data')
plt.plot(x, y_data, '.')
plt.figure('model')
plt.plot(x, y)
plt.figure('data & model')
plt.plot(x, y, 'k', lw=3)
plt.scatter(x, y_data)
plt.savefig('result.png')
plt.show()

nuitka --standalone --mingw64 --show-progress --show-memory --nofollow-import-to=numpy,matplotlib --enable-plugin=numpy,matplotlib,tk-inter  --output-dir=o test.py

**Question:**
When i move **tkinter folder** from `C:\Program Files\Python39\Lib\tkinter` to `test_matplotlib\o\test.dist`, I got the error **ImportError: DLL load failed while importing _tkinter:**
I tried to move `Python39\DLLs\_tkinter.pyd` to `test_matplotlib\o\test.dist` but still error,
how can i solve this problem?

**error message:**
```
Traceback (most recent call last):
  File "C:\Users\msj\Desktop\TEST_M~1\o\TEST~2.DIS\test.py", line 8, in <module>
  File "C:\Users\msj\Desktop\test_matplotlib\o\test.dist-t\matplotlib\pyplot.py", line 2498, in <module>
    switch_backend(rcParams["backend"])
  File "C:\Users\msj\Desktop\test_matplotlib\o\test.dist-t\matplotlib\pyplot.py", line 277, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File "C:\Users\msj\Desktop\test_matplotlib\o\test.dist-t\matplotlib\pyplot.py", line 278, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "importlib.py", line 127, in import_module
  File "C:\Users\msj\Desktop\test_matplotlib\o\test.dist-t\matplotlib\backends\backend_tkagg.py", line 1, in <module>
    from . import _backend_tk
  File "C:\Users\msj\Desktop\test_matplotlib\o\test.dist-t\matplotlib\backends\_backend_tk.py", line 7, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'
```

**Comment by kayhayen** [comment]
Please use recent Nuitka, it's much better these days.
