### ISSUE TITLE
Runtime error when importing torch: `ImportError: libcupti.so.12: ELF load command address/offset not properly aligned`

### ISSUE THREAD

**Issue by doradsoft** [Nuitka/Nuitka#2592]
When importing torch compilation is successful but a runtime error apeaars:

> ./main.bin
> Traceback (most recent call last):
>   File "/tmp/nuitka-cache/onefile_103377_1701887391_29443/main.py", line 1, in <module>
>     import torch
> 
>   File "/tmp/nuitka-cache/onefile_103377_1701887391_29443/torch/[\_\_init\_\_.py](https://github.com/pytorch/pytorch/blob/v2.1.1/torch/__init__.py)", line 235, in <module torch>
> ImportError: libcupti.so.12: ELF load command address/offset not properly aligned

I guess there are some environment specific related causes, so please guide me what to attach on top of the template, thanks.

- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

`python -m nuitka --version`
> 2.0rc3
> Commercial: 2.3.2
> Python: 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0]
> Flavor: Anaconda Python
> Executable: <...>/anaconda3/bin/python
> OS: Linux
> Arch: x86_64
> Distribution: Centos (based on Fedora) 7
> Version C compiler: <...>/bin/gcc (gcc 9.2.0).

- How did you install Nuitka and Python

pip install Nuitka-commercial-staging.zip
no virtualenv.

- The specific PyPI names and versions

`pip list --format=freeze`

> accelerate==0.20.3
> aiobotocore==2.5.0
> aiofiles==22.1.0
> aiohttp==3.8.5
> aioitertools==0.7.1
> aiosignal==1.2.0
> aiosqlite==0.18.0
> alabaster==0.7.12
> anaconda-anon-usage==0.4.2
> anaconda-catalogs==0.2.0
> anaconda-client==1.12.1
> anaconda-cloud-auth==0.1.3
> anaconda-navigator==2.5.0
> anaconda-project==0.11.1
> anyio==3.5.0
> appdirs==1.4.4
> argon2-cffi==21.3.0
> argon2-cffi-bindings==21.2.0
> arrow==1.2.3
> astroid==2.14.2
> astropy==5.1
> asttokens==2.0.5
> async-timeout==4.0.2
> atomicwrites==1.4.0
> attrs==22.1.0
> Automat==20.2.0
> autopep8==1.6.0
> Babel==2.11.0
> backcall==0.2.0
> backoff==2.2.1
> backports.functools-lru-cache==1.6.4
> backports.tempfile==1.0
> backports.weakref==1.0.post1
> bcrypt==3.2.0
> beautifulsoup4==4.12.2
> binaryornot==0.4.4
> bitsandbytes==0.41.2.post2
> black==0.0
> bleach==4.1.0
> bokeh==3.2.1
> boltons==23.0.0
> botocore==1.29.76
> Bottleneck==1.3.5
> brotlipy==0.7.0
> certifi==2023.11.17
> cffi==1.15.1
> chardet==4.0.0
> charset-normalizer==3.3.2
> click==8.1.7
> cloudpickle==2.2.1
> clyent==1.2.2
> colorama==0.4.6
> colorcet==3.0.1
> comm==0.1.2
> conda==23.7.4
> conda-build==3.26.1
> conda-content-trust==0.2.0
> conda_index==0.3.0
> conda-libmamba-solver==23.7.0
> conda-pack==0.6.0
> conda-package-handling==2.2.0
> conda_package_streaming==0.9.0
> conda-repo-cli==1.0.75
> conda-token==0.4.0
> conda-verify==3.4.2
> constantly==15.1.0
> contourpy==1.0.5
> cookiecutter==1.7.3
> cryptography==41.0.3
> cssselect==1.1.0
> cycler==0.11.0
> cytoolz==0.12.0
> daal4py==2023.1.1
> dask==2023.6.0
> datasets==2.14.7
> datashader==0.15.2
> datashape==0.5.4
> debugpy==1.6.7
> decorator==5.1.1
> defusedxml==0.7.1
> Deprecated==1.2.14
> diff-match-patch==20200713
> dill==0.3.6
> distributed==2023.6.0
> docstring-to-markdown==0.11
> docutils==0.18.1
> einops==0.6.1
> entrypoints==0.4
> et-xmlfile==1.1.0
> executing==0.8.3
> fastjsonschema==2.16.2
> filelock==3.13.1
> flake8==6.0.0
> Flask==2.2.2
> fonttools==4.25.0
> frozenlist==1.3.3
> fsspec==2023.10.0
> future==0.18.3
> gensim==4.3.0
> glob2==0.7
> gmpy2==2.1.2
> googleapis-common-protos==1.61.0
> greenlet==2.0.1
> grpc-interceptor==0.15.4
> grpcio==1.59.3
> grpcio-reflection==1.59.3
> grpcio-status==1.59.3
> grpcio-tools==1.51.1
> h5py==3.9.0
> HeapDict==1.0.1
> hf_transfer==0.1.4
> holoviews==1.17.1
> huggingface-hub==0.16.4
> hvplot==0.8.4
> hyperlink==21.0.0
> idna==3.4
> imagecodecs==2023.1.23
> imageio==2.31.1
> imagesize==1.4.1
> imbalanced-learn==0.10.1
> importlib-metadata==6.0.0
> incremental==21.3.0
> inflection==0.5.1
> iniconfig==1.1.1
> intake==0.6.8
> intervaltree==3.1.0
> ipykernel==6.25.0
> ipython==8.15.0
> ipython-genutils==0.2.0
> ipywidgets==8.0.4
> isort==5.9.3
> itemadapter==0.3.0
> itemloaders==1.0.4
> itsdangerous==2.0.1
> jaraco.classes==3.2.1
> jedi==0.18.1
> jeepney==0.7.1
> jellyfish==1.0.1
> Jinja2==3.1.2
> jinja2-time==0.2.0
> jmespath==0.10.0
> joblib==1.2.0
> json5==0.9.6
> jsonpatch==1.32
> jsonpointer==2.1
> jsonschema==4.17.3
> jupyter==1.0.0
> jupyter_client==7.4.9
> jupyter-console==6.6.3
> jupyter_core==5.3.0
> jupyter-events==0.6.3
> jupyter-server==1.23.4
> jupyter_server_fileid==0.9.0
> jupyter_server_ydoc==0.8.0
> jupyter-ydoc==0.2.4
> jupyterlab==3.6.3
> jupyterlab-pygments==0.1.2
> jupyterlab_server==2.22.0
> jupyterlab-widgets==3.0.5
> kaleido==0.2.1
> keyring==23.13.1
> kiwisolver==1.4.4
> lazy_loader==0.2
> lazy-object-proxy==1.6.0
> libarchive-c==2.9
> libmambapy==1.5.1
> linkify-it-py==2.0.0
> llvmlite==0.40.0
> lmdb==1.4.1
> locket==1.0.0
> loguru==0.6.0
> lxml==4.9.3
> lz4==4.3.2
> Markdown==3.4.1
> markdown-it-py==2.2.0
> MarkupSafe==2.1.1
> matplotlib==3.7.2
> matplotlib-inline==0.1.6
> mccabe==0.7.0
> mdit-py-plugins==0.3.0
> mdurl==0.1.0
> mistune==0.8.4
> mkl-fft==1.3.8
> mkl-random==1.2.4
> mkl-service==2.4.0
> more-itertools==8.12.0
> mpmath==1.3.0
> msgpack==1.0.3
> multidict==6.0.2
> multipledispatch==0.6.0
> multiprocess==0.70.14
> munkres==1.1.4
> mypy-extensions==1.0.0
> mypy-protobuf==3.4.0
> navigator-updater==0.4.0
> nbclassic==0.5.5
> nbclient==0.5.13
> nbconvert==6.5.4
> nbformat==5.9.2
> nest-asyncio==1.5.6
> networkx==3.1
> nltk==3.8.1
> notebook==6.5.4
> notebook_shim==0.2.2
> Nuitka==2.0rc3
> numba==0.57.1
> numexpr==2.8.4
> numpy==1.26.2
> numpydoc==1.5.0
> nvidia-cublas-cu12==12.1.3.1
> nvidia-cuda-cupti-cu12==12.1.105
> nvidia-cuda-nvrtc-cu12==12.1.105
> nvidia-cuda-runtime-cu12==12.1.105
> nvidia-cudnn-cu12==8.9.2.26
> nvidia-cufft-cu12==11.0.2.54
> nvidia-curand-cu12==10.3.2.106
> nvidia-cusolver-cu12==11.4.5.107
> nvidia-cusparse-cu12==12.1.0.106
> nvidia-nccl-cu12==2.18.1
> nvidia-nvjitlink-cu12==12.3.101
> nvidia-nvtx-cu12==12.1.105
> openpyxl==3.0.10
> opentelemetry-api==1.21.0
> opentelemetry-exporter-otlp==1.21.0
> opentelemetry-exporter-otlp-proto-common==1.21.0
> opentelemetry-exporter-otlp-proto-grpc==1.21.0
> opentelemetry-exporter-otlp-proto-http==1.21.0
> opentelemetry-instrumentation==0.42b0
> opentelemetry-instrumentation-grpc==0.42b0
> opentelemetry-proto==1.21.0
> opentelemetry-sdk==1.21.0
> opentelemetry-semantic-conventions==0.42b0
> ordered-set==4.1.0
> packaging==23.2
> pandas==2.0.3
> pandocfilters==1.5.0
> panel==1.2.3
> param==1.13.0
> parsel==1.6.0
> parso==0.8.3
> partd==1.4.0
> pathlib==1.0.1
> pathspec==0.10.3
> patsy==0.5.3
> peft==0.4.0
> pep8==1.7.1
> pexpect==4.8.0
> pickleshare==0.7.5
> Pillow==10.1.0
> pip==23.3.1
> pkce==1.0.3
> pkginfo==1.9.6
> platformdirs==3.10.0
> plotly==5.9.0
> pluggy==1.0.0
> ply==3.11
> poyo==0.5.0
> prometheus-client==0.14.1
> prompt-toolkit==3.0.36
> Protego==0.1.16
> protobuf==4.25.1
> psutil==5.9.0
> ptyprocess==0.7.0
> pure-eval==0.2.2
> py-cpuinfo==8.0.0
> pyarrow==11.0.0
> pyarrow-hotfix==0.6
> pyasn1==0.4.8
> pyasn1-modules==0.2.8
> pycodestyle==2.10.0
> pycosat==0.6.4
> pycparser==2.21
> pyct==0.5.0
> pycurl==7.45.2
> pydantic==1.10.8
> PyDispatcher==2.0.5
> pydocstyle==6.3.0
> pyerfa==2.0.0
> pyflakes==3.0.1
> Pygments==2.15.1
> PyJWT==2.4.0
> pylint==2.16.2
> pylint-venv==2.3.0
> pyls-spyder==0.4.0
> pyodbc==4.0.34
> pyOpenSSL==23.2.0
> pyparsing==3.0.9
> PyQt5-sip==12.11.0
> pyrsistent==0.18.0
> PySocks==1.7.1
> pytest==7.4.0
> python-dateutil==2.8.2
> python-dotenv==0.21.0
> python-json-logger==2.0.7
> python-lsp-black==1.2.1
> python-lsp-jsonrpc==1.0.0
> python-lsp-server==1.7.2
> python-slugify==5.0.2
> python-snappy==0.6.1
> pytoolconfig==1.2.5
> pytz==2023.3.post1
> pyviz-comms==2.3.0
> PyWavelets==1.4.1
> pyxdg==0.27
> PyYAML==6.0.1
> pyzmq==23.2.0
> QDarkStyle==3.0.2
> qstylizer==0.2.2
> QtAwesome==1.2.2
> qtconsole==5.4.2
> QtPy==2.2.0
> queuelib==1.5.0
> regex==2023.10.3
> requests==2.31.0
> requests-file==1.5.1
> requests-toolbelt==1.0.0
> responses==0.13.3
> rfc3339-validator==0.1.4
> rfc3986-validator==0.1.1
> rope==1.7.0
> Rtree==1.0.1
> ruamel.yaml==0.17.21
> ruamel-yaml-conda==0.17.21
> s3fs==2023.4.0
> safetensors==0.3.3
> scikit-image==0.20.0
> scikit-learn==1.3.0
> scikit-learn-intelex==20230426.111612
> scipy==1.11.4
> Scrapy==2.8.0
> seaborn==0.12.2
> SecretStorage==3.3.1
> Send2Trash==1.8.0
> sentencepiece==0.1.99
> service-identity==18.1.0
> setuptools==69.0.2
> sip==6.6.2
> six==1.16.0
> smart-open==5.2.1
> sniffio==1.2.0
> snowballstemmer==2.2.0
> sortedcontainers==2.4.0
> soupsieve==2.4
> Sphinx==5.0.2
> sphinxcontrib-applehelp==1.0.2
> sphinxcontrib-devhelp==1.0.2
> sphinxcontrib-htmlhelp==2.0.0
> sphinxcontrib-jsmath==1.0.1
> sphinxcontrib-qthelp==1.0.3
> sphinxcontrib-serializinghtml==1.1.5
> spyder==5.4.3
> spyder-kernels==2.4.4
> SQLAlchemy==1.4.39
> stack-data==0.2.0
> statsmodels==0.14.0
> sympy==1.11.1
> tables==3.8.0
> tabulate==0.8.10
> TBB==0.2
> tblib==1.7.0
> tenacity==8.2.2
> terminado==0.17.1
> text-generation-server==1.2.0
> text-unidecode==1.3
> textdistance==4.2.1
> texttable==1.7.0
> threadpoolctl==2.2.0
> three-merge==0.1.1
> tifffile==2023.4.12
> tinycss2==1.2.1
> tldextract==3.2.0
> tokenizers==0.13.3
> toml==0.10.2
> tomlkit==0.11.1
> toolz==0.12.0
> torch==2.1.1
> tornado==6.3.2
> tqdm==4.66.1
> traitlets==5.7.1
> transformers==4.33.3
> triton==2.1.0
> Twisted==22.10.0
> typer==0.6.1
> types-protobuf==4.24.0.4
> typing_extensions==4.8.0
> tzdata==2023.3
> uc-micro-py==1.0.1
> ujson==5.4.0
> Unidecode==1.2.0
> urllib3==1.26.18
> w3lib==1.21.0
> watchdog==2.1.6
> wcwidth==0.2.5
> webencodings==0.5.1
> websocket-client==0.58.0
> Werkzeug==2.2.3
> whatthepatch==1.0.2
> wheel==0.38.4
> widgetsnbextension==4.0.5
> wrapt==1.16.0
> wurlitzer==3.0.2
> xarray==2023.6.0
> xxhash==3.4.1
> xyzservices==2022.9.0
> y-py==0.5.9
> yapf==0.31.0
> yarl==1.8.1
> ypy-websocket==0.8.2
> zict==2.2.0
> zipp==3.11.0
> zope.interface==5.4.0
> zstandard==0.19.0

- Short, Self Contained, Correct, Example

```python
import torch
print(torch.zeros)
```

- Nuitka options used

python -m nuitka --main=main.py --standalone --onefile --static-libpython=no --onefile-tempdir-spec="%TEMP%/nuitka-cache/onefile_%PID%_%TIME%" --noinclude-unittest-mode=allow --clang

**Comment by doradsoft** [comment]
> What OS do you run on, CentOS 7 too?

Yes, it's throwing runtime error on the same machine.

**Comment by kayhayen** [comment]
Would you have the compilation report for upload, or the snippet that indicates why it's included (or if not)?

**Comment by doradsoft** [comment]
> Would you have the compilation report for upload

Delivered in private.

**Comment by kayhayen** [comment]
So, the one line that is relevant is this right here:

> <included_dll name="libcupti.so.12" dest_path="libcupti.so.12" source_path="${sys.prefix}/lib/python3.11/site-packages/nvidia/cuda_cupti/lib/libcupti.so.12" package="torch" ignored="no" reason="Used by 'torch/_C.so'"/>

So, it seems this is indeed included by Nuitka, and then after modifying it with `patchelf` for use with standalone fails to load. This being CentOS 7 of course means it is not the newest patchelf. Can you give the output of `patchelf --version` ? And also, can you compare the source file and the one in the dist folder for size discrepancies?

**Comment by doradsoft** [comment]
`patchelf --version`

> patchelf 0.18.0

**Comment by doradsoft** [comment]
Well after you pointed it out,
Maybe https://github.com/NixOS/patchelf/issues/492 is the case?
Downgrading to [0.17.2](https://github.com/NixOS/patchelf/releases/tag/0.17.2) and letting you know.

**Comment by kayhayen** [comment]
I need to check what my commercial containers and CentOS containers in general use, but I guess/hope it's not that version.

**Comment by doradsoft** [comment]
I confirm it doesn't reproduce with patchelf [0.17.2](https://github.com/NixOS/patchelf/releases/tag/0.17.2)
thanks for helping on this one

**Comment by kayhayen** [comment]
For Nuitka is probably means that we should error check the patchelf version. I am also kind of annoyed by the fact that the tools versions used are not recorded in the compilation report. But the problem side is solved I guess.

**Comment by kayhayen** [comment]
Finally took the time, for this to be checked, now patchelf 0.18.0 precisely is rejected at compilation start. This will be in the 2.3 release and is coming to the factory branch. I am closing this early.
