### ISSUE TITLE
PyQt 6 - does not see included files

### ISSUE THREAD

**Issue by NeuralAIM** [Nuitka/Nuitka#2597]
- Nuitka version:
```
C:\Windows\System32>python -m nuitka --version
1.9.3
Commercial: None
Python: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Program Files\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10 (win 11!)
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0).
```

**example.py:**
```
import sys
from PyQt6.QtWidgets import QApplication, QLabel
from PyQt6.QtGui import QPixmap

def main():
    app = QApplication(sys.argv)
    label = QLabel("Hello")
    #add svg icon
    label.setPixmap(QPixmap("files/exit.svg"))

    label.adjustSize()
    label.show()
    sys.exit(app.exec())

if __name__ == "__main__":
    main()
```

commands:
1: `nuitka --onefile --enable-plugins=pyqt6 --include-data-dir="files=files" example.py`
2: `nuitka --standalone --enable-plugins=pyqt6 --include-data-dir="files=files" example.py`

Behavior in the collection mode `--standalone` is expected, which is not to say about `--onefile`:

![image](https://github.com/Nuitka/Nuitka/assets/75082388/72ca7aee-c872-4699-8aff-41f22e6740e8)

I know what can be done like this:
`label.setPixmap(QPixmap(os.path.normpath(os.path.dirname(__file__)) + "/files/exit.svg"))`

But this is very difficult to do when you have a large application built in Qt Designer, where files are used both in QSS (it's not working with qss) and in the code.

**Comment by kayhayen** [comment]
The file embedding of Nuitka commercial solves this very nicely for PySide6 with no changes to the program needed. However, the original code not being portable, i.e. not working if you launch the program from another directory, was always a problem of the code, you just normally don't feel it.
