### ISSUE TITLE
How can I change C compiler options, e.g. workaround default -fcf-protection option in the GCC compiler?

### ISSUE THREAD

**Issue by parkilwoo** [Nuitka/Nuitka#2603]
### Version
- 2.0rc5
- Commercial: None
- Python: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
- Flavor: Debian Python
- Executable: /usr/bin/python
- OS: Linux
- Arch: x86_64
- Distribution: Ubuntu (based on Debian) 22.04.2
- Version C compiler: /usr/bin/gcc (gcc 11).

hello. I am using a .so file with Nuitka. I am using Thales solution for licensing the .so file, but I am not able to use Thales solution because the -fcf-protection option in GCC compiler is set to full, which is the default. Currently, I am using the SconsCompilerSettings.py file as a workaround and using the sed command to temporarily put in that part.
Is there a better way?

`sed -i 's/# Support for gcc and clang, restricting visibility as much as possible./env.Append(CCFLAGS=["-fcf-protection=none"])/' /usr/local/lib/python${PYTHON_VERSION}/dist-packages/nuitka/build/SconsCompilerSettings.py`

**Comment by kayhayen** [comment]
https://nuitka.net/doc/user-manual.html#providing-extra-options-to-nuitka-c-compilation

**Comment by kayhayen** [comment]
I saw your PR, very good. I welcome making these features directly accessible.
