### ISSUE TITLE
Not able to import tensorflow

### ISSUE THREAD

**Issue by siewwentong** [Nuitka/Nuitka#2610]
Description of issue:
I have a python script that only has one line:
```
import tensorflow as tf
```
and I tried to compile this script using the following command:
```
python3 -m nuitka --standalone import_tensorflow.py
```
The compilation works fine, but when I run the generated bin file, I get the following error:
```
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/descriptor_database.cc:642] File already exists in database: tensorflow/python/framework/cpp_shape_inference.proto
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/descriptor.cc:1986] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
Aborted
```

I have also tried a few different flags as listed below, but all of them will end up with the same error when the bin file is ran
```
python3 -m nuitka --follow-imports --standalone import_tensorflow.py
python3 -m nuitka --include-module=tensorflow --standalone import_tensorflow.py
python3 -m nuitka --include-module=tensorflow  --include-module=google.protobuf --standalone import_tensorflow.py
python3 -m nuitka  --enable-plugin=tensorflow --standalone import_tensorflow.py
```
- I have used nuika for more complicated projects and scripts, and they work perfectly fine. Then I realized whenever there's tensorflow involved, I would get this error, which prompted me to test with a very simple script that only imports tensorflow.
- Running "python3 -c 'import tensorflow as tf' " does not return any errors.
- I also tried different tensorflow and protobuf versions, but the same error persists.

Really appreciate any help / guidance to solve this issue, many thanks!

Additional infos:
Output of "python -m nuitka --version":
```
1.9.3
Commercial: None
Python: 3.8.10 (default, May 26 2023, 14:05:08) 
Flavor: Debian Python
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 20.04.6
Version C compiler: /usr/bin/gcc (gcc 7).
```

Nuitka and other python packages are all installed via pip install

The specific PyPI names and versions:
- tensorflow: 2.13.1
- protobuf: 3.20.3

**Comment by kayhayen** [comment]
That's very strange, I believe tensorflow works. It might be absolutely necessary to have your pip freeze, and the compilation report as given by `--report=compilation-report.xml` in order to reproduce. I might also be wrong of course, but I am pretty sure it must be some specifics going on.

**Comment by siewwentong** [comment]
[pypi_packages.txt](https://github.com/Nuitka/Nuitka/files/13684196/pypi_packages.txt)
[compilation-report.txt](https://github.com/Nuitka/Nuitka/files/13684201/compilation-report.txt)

These are the files requested, stored as text files :)

**Comment by siewwentong** [comment]
> [pypi_packages.txt](https://github.com/Nuitka/Nuitka/files/13684196/pypi_packages.txt) [compilation-report.txt](https://github.com/Nuitka/Nuitka/files/13684201/compilation-report.txt)
> 
> These are the files requested, stored as text files :)


@kayhayen Are there any more information that I need to provide?

**Comment by kayhayen** [comment]
When the issue template is not immediately filled out, an issue falls into a second track, where I look at the tags when I find the time, and check it then. No more immediate reaction then, esp. when I know that there is something more involved necessary, in this case undusting my tool for installing venv from reports after the many 1.9 improvements in this field.
