### ISSUE TITLE
Nuitka doesn't handle using Python from compiled source checkout and cannot tell the location of Python.h

### ISSUE THREAD

**Issue by flozz** [Nuitka/Nuitka#2611]
Hello,

I am working on porting an application to macOS and for some reasons I had to build my own Python version (from a release tag of the official CPython Git repository). When I tried to compile my app, I had the following error:

```
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: clang (clang 15.0.0).
FATAL: Error, no 'Python.h' development headers can be found at '['/usr/local/include/python3.11', '/usr/local/develop/headers/python3.11']', dependency not satisfied!
```

I was able to fix my issue and to successfully build my app by editing the [`nuitka/build/Backends.scons`](https://github.com/Nuitka/Nuitka/blob/develop/nuitka/build/Backend.scons#L598-L606) file to add the path of the `Include/` folder of my compiled CPython.

* Is it possible/worthwhile to add a way to tel Nuitka where the `Python.h` file is located?
* What is the best way to achieve this? (CLI option? dedicated env var? parsing "common" env vars like CPATH/CCPATH/CFLAGS/...?)

I can work on a PR to implement whatever solution you think is the best to achieve this (if you think this feature is valuable for Nuitka).

## Nuitka / OS version

```
1.9.4
Commercial: None
Python: 3.11.7 (tags/v3.11.7:fa7a6f2303, Dec 14 2023, 15:44:57) [Clang 15.0.0 (clang-1500.1.0.2.5)]
Flavor: Unknown
Executable: /Users/fabien/myproject/build/__env__/bin/python
OS: Darwin
Arch: arm64
Version C compiler: /usr/bin/clang (clang 15.0.0).
```

## Steps to reproduce

I first installed XCode, HomeBrew and the following packages with `brew`:

```
brew install pkg-config openssl@3.0 xz gdbm tcl-tk
```

Then I built Python:

```bash
PATH="/opt/homebrew/bin/:$PATH"

cd ~/myproject/
mkdir -p build/

git clone https://github.com/python/cpython.git build/cpython.git
cd build/cpython.git
git checkout v3.11.7

GDBM_CFLAGS="-I$(brew --prefix gdbm)/include"
GDBM_LIBS="-L$(brew --prefix gdbm)/lib -lgdbm"
./configure \
    --with-openssl="$(brew --prefix openssl@3.0)"
make -j4

cd -
```

Then I made a virtualenv and installed Nuitka (and dependencies for my app):

```bash
build/cpython.git/python.exe -m venv build/__env__/
source build/__env__/bin/activate
pip install nuitka==1.9.4
pip install -e .
```

And finally I built my app:

```bash
export CPPFLAGS="-I$PWD/build/cpython.git/Include -I$PWD/build/cpython.git"
export LDFLAGS="-L$PWD/build/cpython.git"
python -m nuitka \
    --follow-imports \
    --include-package=PIL \
    --include-package-data=myapp \
    --enable-plugin=tk-inter \
    --tcl-library-dir="$(brew --prefix tcl-tk)" \
    --tk-library-dir="$(brew --prefix tcl-tk)" \
    --standalone \
    --onefile \
    --macos-create-app-bundle \
    --macos-signed-app-name=fr.foo.bar.myapp \
    --macos-app-name=MyAPP \
    --macos-app-version="$(python setup.py --version)" \
    --jobs=4 \
    --disable-cache=all \
    macbuild/myapp-darwin.py
```

----

EDIT: I edited the Nuitka/OS version... I ran the command from the wrong venv the first time ^^'

**Comment by kayhayen** [comment]
So, you are running self compiled Python, but not on Windows, which is where I think I did stuff to make that work in the past. If you did a `make install` the expected layout would be found. I agree however that it ought to be unnecessary. Can you provide the output of `--show-scons` such that I can see what it detects as the python prefix?

**Comment by flozz** [comment]
> Can you provide the output of --show-scons such that I can see what it detects as the python prefix?

Yes sure!

```
python -m nuitka --show-scons macbuild/myapp-darwin.py
```
```
Nuitka-Options:INFO: Used command line options: --show-scons macbuild/myapp-darwin.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program.
Nuitka-Options:WARNING: Check options and make sure that is intended.
Nuitka:INFO: Starting Python compilation with Nuitka '1.9.4' on Python '3.11' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Scons command: /Users/fabien/myproject/build/__env__/bin/python -W ignore /Users/fabien/myproject/build/__env__/lib/python3.11/site-packages/nuitka/build/inline_copy/bin/scons.py -f /Users/fabien/myproject/build/__env__/lib/python3.11/site-packages/nuitka/build/Backend.scons --jobs 8 --warn=no-deprecated --no-site-dir --debug=stacktrace result_name=/Users/fabien/myproject/myapp-darwin source_dir=. nuitka_python=false debug_mode=false python_debug=false module_mode=false full_compat=false experimental= trace_mode=false file_reference_mode=original module_count=1 result_exe=/Users/fabien/myproject/myapp-darwin.bin nuitka_src=/Users/fabien/myproject/build/__env__/lib/python3.11/site-packages/nuitka/build python_version=3.11 python_prefix=/usr/local no_deployment= clang_mode=true show_scons=true noelf_mode=true macos_min_version=14.1 macos_target_arch=arm64 target_arch=arm64
scons: Reading SConscript files ...
Nuitka-Scons:INFO: CC '/usr/bin/gcc' version check gives (15, 0, 0)
Nuitka-Scons:INFO: Initial CC: 'gcc'
Nuitka-Scons:INFO: Initial CCVERSION: (15, 0, 0)
Scons: Compiler used /usr/bin/clang 
Nuitka-Scons:INFO: CC '/usr/bin/clang' version check gives (15, 0, 0)
Nuitka-Scons:INFO: Backend C compiler: clang (clang 15.0.0).
Nuitka-Scons:INFO: LTO mode auto was resolved to mode: 'yes' (known to be supported (macOS clang)).
Nuitka-Scons:INFO: Using C11 mode: True
Nuitka-Scons:INFO: Using resource mode: 'mac_section' (default for macOS).
Nuitka-Scons:INFO: Told to run compilation on 8 CPUs.
Nuitka-Scons:INFO: Checking if ccache is at '/usr/local/bin/ccache' guessed path.
Nuitka-Scons:INFO: Checking if ccache is at '/Users/fabien/myproject/build/__env__/bin/ccache' guessed path.
Nuitka-Scons:INFO: Checking if ccache is at '/usr/local/opt/ccache' guessed path.
Nuitka-Scons:INFO: Checking if ccache is at '/opt/homebrew/bin/ccache' guessed path.
Nuitka will make use of ccache to speed up repeated compilation.
[...]
```

**Comment by flozz** [comment]
> So, you are running self compiled Python, but not on Windows, which is where I think I did stuff to make that work in the past.

Yes that's right.

> If you did a make install the expected layout would be found. I agree however that it ought to be unnecessary.

I do not wanted to do a `make install` to not "pollute" the machine. I ultimately want to turn this Mac into a CI build server so many projects may be built on it with different Python versions. :)

**Comment by kayhayen** [comment]
I agree with not wanting to install, Python can run from built tree. It may be the best tested configuration due to all their developers doing it. ;-)

> python_prefix=/usr/local

That is wrong, is it not? That is the prefix it *would* use if installed. I need to check what I did for self compiled Windows Python now, but I believe there is no such thing as a compiled in prefix there, and this was maybe only about the DLL.

**Comment by kayhayen** [comment]
So, the fix would be a correct result from this function:

```
def getSystemPrefixPath():
    """Return real sys.prefix as an absolute path breaking out of virtualenv.

    Note:

        For Nuitka, it often is OK to break out of the virtualenv, and use the
        original install. Mind you, this is not about executing anything, this is
        about building, and finding the headers to compile against that Python, we
        do not care about any site packages, and so on.

    Returns:
        str - path to system prefix
    """

It lives in `nuitka.PythonVersions`.

btw, I am confused by you referencing `python.exe`, but if you manage to find the real `sys.executable` in that case, and a `PCBuild` directory along side it, then you can safely assume source code. I am tempted to want to have this detected as a Python flavor btw, so --version output of Nuitka will say "compiled Python from source" or something, for bonus points.

So the task would be to recognize that the `sys.prefix` value is not the one to use, but check `sys.executable` as well. I think you can compare `sys.executable` and check if it's where you would expect it to be. Applying realpath to resolve symlinks. So if prefix is `/usr/local/` and the real sys executable is not where it should be, then check for source code with "PCBuild" and you are good to go with that prefix. The C header will then we found in scons.

**Comment by kayhayen** [comment]
Give it a shot to PR that please. :-)

**Comment by flozz** [comment]
> btw, I am confused by you referencing `python.exe`

I am confused too... I do not know why I have the .exe suffix on a macOS build ^^'

> So the task would be to recognize that the `sys.prefix` value is not the one to use, but check `sys.executable` as well. I think you can compare `sys.executable` and check if it's where you would expect it to be. Applying realpath to resolve symlinks. So if prefix is `/usr/local/` and the real sys executable is not where it should be, then check for source code with "PCBuild" and you are good to go with that prefix. The C header will then we found in scons.

Here is what I get:

```python
>>> import nuitka.PythonVersions
>>> nuitka.PythonVersions.getSystemPrefixPath()
'/usr/local'

>>> import sys
>>> sys.prefix
'/Users/fabien/myproject/build/__env__'
>>> sys.executable
'/Users/fabien/myproject/build/__env__/bin/python'

>>> import os 
>>> os.path.realpath(sys.executable)
'/Users/fabien/myproject/build/cpython.git/python.exe'
```

```bash
$ ls /Users/fabien/myproject/build/cpython.git
Doc			PCbuild			configure
Grammar			Parser			configure.ac
Include			Programs		install-sh
LICENSE			Python			libpython3.11.a
Lib			README.rst		platform
Mac			Tools			pybuilddir.txt
Makefile		_bootstrap_python	pyconfig.h
Makefile.pre		aclocal.m4		pyconfig.h.in
Makefile.pre.in		build			python-config
Misc			config.guess		python-config.py
Modules			config.log		python.exe
Objects			config.status		python.exe-gdb.py
PC			config.sub		setup.py
```

It looks like the right location as the `Python.h` file lives in the `Include` folder next to the executable :)

**Comment by kayhayen** [comment]
Don't look at the `Python.h` file. Correct the output of `getSystemPrefixPath` and it will be the first step and yeah, your outputs suggest you can fix it to return `'/Users/fabien/myproject/build/cpython.git` and it would work. The algorithm outlined in my previous not will work. For Linux, the `nuitka/build/Backend.scons` should not just try 

```
            os.path.join(
                python_prefix_external, "include", "python" + python_abi_version
            ),
```

but also 

```
            # CPython source code checkout
            os.path.join(
                python_prefix_external, "Include", 
            ),
```

as a candidate for the header file path.

**Comment by kayhayen** [comment]
Thanks a lot for working on this, very helpful indeed.

**Comment by kayhayen** [comment]
Adding the flavor detection:

```
~/test/live-python/Python-3.11.4$ ./python ~/repos/Nuitka/bin/nuitka --version
2.0rc6
Commercial: None
Python: 3.11.4 (main, Dec 27 2023, 11:07:06) [GCC 11.4.0]
Flavor: Self Compiled
Executable: /home/hayen/test/live-python/Python-3.11.4/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.3
```

**Comment by kayhayen** [comment]
Changed it to `Self Compiled Uninstalled`, since it's not so much about compiling yourself.

**Comment by kayhayen** [comment]
For me on Linux at least, this is needed:

```
/home/hayen/test/live-python/Python-3.11.4/Include/Python.h:12:10: fatal error: pyconfig.h: No such file or directory
   12 | #include "pyconfig.h"     
```

Seems the root directory should be added too, which is where that file lives for me.

**Comment by kayhayen** [comment]
It seems accelerated mode is lacking a workable `sys.path` entirely, since linked in are unusable paths, but standalone works for me on Linux now, but setting PYTHONPATH is sufficient, so i suspect using a virtualenv will work. And it does, not sure how do that, for ApplePython we error out, and probably should do that for the config without a virtualenv too, so I am just adding that, and not going to bother with make it work without install at all.

**Comment by flozz** [comment]
Hello,

I can help if you need to test things on macOS (I am inexperienced with that OS, but I am learning how it works to be able to port an app).

Anyway, thank you for all your work on Nuitka!

**Comment by kayhayen** [comment]
I was sort of expecting that you do macOS on your side, yes. I would expect it to work, since your PR only got amended by a little to cover things I found needed on Linux, but macOS should work. I am keeping it open until 2.0 release, and actually kind of still plan to make a uninstalled Windows build, just to see if it works as well.

**Comment by flozz** [comment]
I tested with Nuitka `factory`, my app was successfully compiled and everything is working fine (macOS 14.1.2, Python 3.11.7) :)

**Comment by kayhayen** [comment]
It seems I am not going to Windows yet, at least not until I need it, so I consider this done now.

**Comment by kayhayen** [comment]
This is part of the stable release 2.0 that I just made.
