### ISSUE TITLE
The  code with multiprocessing library running very slowly

### ISSUE THREAD

**Issue by xueliang** [Nuitka/Nuitka#2616]
The multiprocessing library is service_streamer [service_streamer](https://github.com/ShannonAI/service-streamer/tree/master), which is a middleware for web service of machine learning applications runing on multi-gpu/multi-processing. However, if the code is compiled with nuitka, the binary runs very slowly.

Following is a miniproject with service_streamer:

```
import logging
from typing import List
from service_streamer import ManagedModel,Streamer

from flask import Flask, request, jsonify
from gevent import monkey; monkey.patch_all()
from gevent.pywsgi import WSGIServer


logging.basicConfig(level=logging.ERROR)

import time
class TestModel(object):
    def __init__(self):
        return

    def predict(self, batch: List[str]) -> List[str]:
        batch_inputs = []
        masked_indexes = []
        batch_outputs = []
        for text in batch:
            batch_outputs.append(0)
            time.sleep(0.5)
        return batch_outputs


class ManagedTestModel(ManagedModel):

    def init_model(self):
        self.model = TestModel()

    def predict(self, batch):
        return self.model.predict(batch)
		
		

app = Flask(__name__)
model = None
streamer = None
@app.route("/stream", methods=["POST"])
def stream_predict():
    inputs = ['a','b']
    outputs = streamer.predict(inputs)
    return jsonify(outputs)


if __name__ == "__main__":
    streamer = Streamer(ManagedTestModel, batch_size=1, max_latency=0.001, worker_num=4, cuda_devices=(0, ))
    model = TestModel()
    WSGIServer(("0.0.0.0", 5006), app).serve_forever()
```

It could be tested by requests as follows:

```
import requests

url = "http://127.0.0.1:5006/stream"

import time
start = time.time()
for i in range(10):
    response = requests.post(url)
end = time.time()
print(end - start)
```

If running it with python in my machine, the output could be:
> 6.071689605712891

But if compiled with 

>  python -m nuitka --show-progress --show-memory --standalone    --output-dir=build/Linux-64 --static-libpython=no  ./testStreamer.py

and run the binary as the server, the output of testing code becomes:
> 24.576040267944336

BTW, the version of nuitka is:

> 1.9
> Commercial: None
> Python: 3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0]
> Flavor: Anaconda Python
> Executable: /home/lc/miniconda3/envs/ocronnx/bin/python
> OS: Linux
> Arch: x86_64
> Distribution: Ubuntu (based on Debian) 20.04.6
> Version C compiler: /usr/bin/gcc (gcc 9).

I guess there is something about multi-processing, but I can not figure it out very clearly.

**Comment by KevinRodriguez777** [comment]
i'm noticing the same results compiled vs uncompiled, i guess it got fixed along the way
