### ISSUE TITLE
Не могу скомпилировать Kivy

### ISSUE THREAD

**Issue by RyzhikSS** [Nuitka/Nuitka#2617]
Nuitka   1.9.5 python 3.11

D:\VelikoBot>nuitka --include-plugin-files=dependencies.py --onefile --standalone --output-dir=build main.py
Nuitka-Options:INFO: Used command line options: --include-plugin-files=dependencies.py --onefile --standalone --output-dir=build main.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.9.5' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:INFO: options-nanny: Using module 'trio._core._ki' (version 0.22.0) with incomplete support: Disabled careful handling of KeyboardInterrupt in 'trio'
PASS 1: 90.0%|██████████████████████▌  | 459/510, kivy.core.window            Traceback (most recent call last):
  File "C:\Users\Рыжик\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\plugins\Plugins.py", line 82, in withPluginProblemReporting
    yield
  File "C:\Users\Рыжик\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\plugins\Plugins.py", line 534, in considerImplicitImports
    cls._considerImplicitImports(plugin=plugin, module=module)
  File "C:\Users\Рыжик\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\plugins\Plugins.py", line 426, in _considerImplicitImports
    for full_name in iterateModuleNames(plugin.getImplicitImports(module)):
  File "C:\Users\Рыжик\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\plugins\Plugins.py", line 403, in iterateModuleNames
    for v in value:
  File "C:\Users\Рыжик\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\plugins\standard\KivyPlugin.py", line 90, in getImplicitImports
    for _, module_name, _ in self._getKivyInformation().window_impl:
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Рыжик\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\plugins\standard\KivyPlugin.py", line 62, in _getKivyInformation
    info = self.queryRuntimeInformationMultiple(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Рыжик\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\plugins\PluginBase.py", line 1102, in queryRuntimeInformationMultiple
    feedback = feedback.decode("utf8")
               ^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 258: invalid continuation byte
FATAL: kivy: Plugin issue while working on 'module 'kivy.core.window''. Please report the bug with the above traceback included.
Nuitka-Reports:INFO: Compilation report written to file 'nuitka-crash-report.xml'.
Nuitka-Reports:INFO: Compilation crash report written to file 'nuitka-crash-report.xml'.

**Comment by RyzhikSS** [comment]
Установил Nuitka из вашей ссылки. Предыдущая проблема исправилась. Но возникла новая проблема

D:\VelikoBot>nuitka --onefile --standalone --windows-disable-console --output-dir=build main.py
Nuitka-Options: Used command line options: --onefile --standalone --windows-disable-console --output-dir=build main.py
Nuitka: Starting Python compilation with Nuitka '2.0rc6' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:options-nanny: Using module 'trio._core._ki' (version 0.22.0) with incomplete support: Disabled careful handling of KeyboardInterrupt in 'trio'
Nuitka-Plugins:anti-bloat: Not including 'PIL.ImageQt' automatically in order to avoid bloat, but this may cause: PIL will not be able to create Qt image objects.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: gcc (gcc 13.2.0).
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Illegal byte sequence

                                                scons: *** [__constants.o] Error 3
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Illegal byte sequence

Backend C: 0.7%|▏                        | 2/301scons: *** [__helpers.o] Error 3
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Illegal byte sequence

                                                scons: *** [__loader.o] Error 3
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Illegal byte sequence

Backend C: 1.3%|▎                        | 4/301scons: *** [module.PIL.BlpImagePlugin.o] Error 3
Nuitka-Reports: Compilation report written to file 'nuitka-crash-report.xml'.
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'.

**Comment by kayhayen** [comment]
The gcc seems to have problems with the filenames of yours here too. It does actually avoid things, by switching to "short paths" during compilation, because gcc on Windows doesn't handle a lot of things, or maybe it was ccache, but this looks like it's not happening. I wonder if short Cyrillic paths are not covered.

Can you provide the output of the compilation of "hello world" with --show-scons so I can see what it's using there. I suspect, that maybe `Рыжик` is short and not converted to a short path, but it would confirm that by seeing the value of python_prefix passed to Scons.

**Comment by RyzhikSS** [comment]
Исправил учётную запись на имя без кириллицы. Всё заработало. Спасибо
