### ISSUE TITLE
--include-data-dir doesn't work

### ISSUE THREAD

**Issue by Qubbby** [Nuitka/Nuitka#2626]
Dear sir：
    Something strange appeared when I used --include-data-dir arguments.
As readme.md said：
    To copy a whole folder with all files, you can use --include-data-dir=/path/to/images=images which will copy all files including a potential subdirectory structure. You cannot filter here, i.e. if you want only a partial copy, remove the files beforehand.

When I used --include-data-dir=libs=libs，Nuitka always gives me a WARNING（Nuitka-Options WARNING: No data files in directory）.I do am sure there is a subfolder in libs folder.

I would appreciate a lot if you could help me.

Thank you for reading！

**Comment by KevinRodriguez777** [comment]
what sort of data files are you trying to include?

**Comment by Qubbby** [comment]
.dll files.
I could accomplish it by a lot of  '--include-data-files=' one by one such as '--include-data-files=libs/mysql/*.dll=libs/mysql/' (It is really a little inconvenient.

Thank you for your reply^ ^

**Comment by Qubbby** [comment]
> what sort of data files are you trying to include?

.dll files.
I could accomplish it by a lot of '--include-data-files=' one by one such as '--include-data-files=libs/mysql/*.dll=libs/mysql/' (It is really a little inconvenient.

Thank you for your reply^ ^

**Comment by KevinRodriguez777** [comment]
DLLs are not data files.
please take a look at https://nuitka.net/doc/nuitka-package-config.html

**Comment by Qubbby** [comment]
> DLLs are not data files.
> 
> please take a look at https://nuitka.net/doc/nuitka-package-config.html

Thank you!!!
I am a newbie coder and really confused after getting no result by asking ChatGPT.
Again,thank you very much for your help
Have a nice day^^

**Comment by KevinRodriguez777** [comment]
No problem, if you still need help please send a Minimal Reproducible Example so that we can add it to nuitka.
