### ISSUE TITLE
function co_name changed

### ISSUE THREAD

**Issue by AIgiraffe** [Nuitka/Nuitka#2627]
when i use nuitka with torch.12 + python38+nuikta0.6.8.4, i decorated a function with torch.fx.wrap，the f_code.co_name of function is  "\<module>" in the local Python environment, but it changed in exe， the changed f_code.co_name like "\<module excise.tmp.test>".how can i keep the f_code.co_name as "\<module> in exe?,thanks

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
