### ISSUE TITLE
Pandas link error

### ISSUE THREAD

**Issue by shenjackyuanjie** [Nuitka/Nuitka#2631]
```
Nuitka-Scons:INFO: Backend C compiler: clang-cl (clang-cl).
Nuitka-Scons:INFO: Backend linking program with 504 files (no progress information available for this stage).
lld-link: error: undefined symbol: modulecode_pandas$core$arrays$sparse$accessor
>>> referenced by __loader.obj:(meta_path_loader_entries)
```
```
fuzzywuzzy==0.18.0
lib-not-dr==0.3.12
Nuitka==1.9.5
numpy==1.26.2
ordered-set==4.1.0
pandas==1.5.3
Pillow==10.1.0
python-dateutil==2.8.2
pytz==2023.3.post1
pywin32==306
six==1.16.0
tomli==2.0.1
tzdata==2023.3
zstandard==0.22.0
```
(pandas 2.1.4 behave the same)
```
V:\githubs\nuitka-test\pandas-pack\env\Scripts\python.exe -m nuitka --main=main.py --standalone --msvc=latest --clang --windows-icon-from-ico=./images/bs.ico --output-dir=./build --disable-console --enable-plugin=tk-inter --debug
Working Dir:  V:\githubs\nuitka-test\pandas-pack
Nuitka-Options:INFO: Used command line options: --main=main.py --standalone --msvc=latest --clang --windows-icon-from-ico=./images/bs.ico --output-dir=./build --disable-console --enable-plugin=tk-inter --debug
```

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
