### ISSUE TITLE
--clang --mingw64 cause issue

### ISSUE THREAD

**Issue by shenjackyuanjie** [Nuitka/Nuitka#2634]
```
2.0rc7
Commercial: None
Python: 3.8.18+ (heads/3.8:7f59c4c1d4, Aug 26 2023, 00:20:02) [MSC v.1900 64 bit (AMD64)]
Flavor: CPython Official
Executable: D:\APPS\CPython\Python38\python3.8.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: V:\apps\LLVM\bin\clang.exe (clang 17.0.6).
```
test program
```python
print('hello world')
```
build with standalone
```bash

❯ python3.8 -m nuitka --clang --mingw64 --main=main.py --standalone
Nuitka-Options: Used command line options: --clang --mingw64 --main=main.py --standalone
Nuitka: Starting Python compilation with Nuitka '2.0rc7' on Python '3.8' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: clang (clang 17.0.6).
static_src\MainProgram.c:145:5: error: call to undeclared function 'SetDllDirectoryW'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  145 |     SetDllDirectoryW(getBinaryDirectoryWideChars(true));
      |     ^
static_src\MainProgram.c:145:5: note: did you mean 'AddDllDirectory'?
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um\libloaderapi.h:454:1: note: 'AddDllDirectory' declared here
  454 | AddDllDirectory(
      | ^
1 error generated.

Backend C: 16.7%|████▏                    | 1/6scons: *** [static_src\MainProgram.o] Error 1
Nuitka-Scons: Backend linking program with 6 files (no progress information available for this stage).
Nuitka-Reports: Compilation report written to file 'nuitka-crash-report.xml'.
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'.
```
build without standalone
```
❯ python3.8 -m nuitka --clang --mingw64 --main=main.py
Nuitka-Options: Used command line options: --clang --mingw64 --main=main.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure that is intended.
Nuitka: Starting Python compilation with Nuitka '2.0rc7' on Python '3.8' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: clang (clang 17.0.6).
Nuitka-Scons: Backend linking program with 6 files (no progress information available for this stage).
Unexpected output from this command:
"V:\apps\LLVM\bin\clang.exe" -o "V:\githubs\NUITKA~1\basic\main.exe" -Wl,--exclude-all-symbols -Wl,--out-implib,.\import.lib -municode -Wl,--stack,9863168 @".\@link_input.txt" -LD:\APPS\CPython\Python38\libs -lm -lpython38
LINK : warning LNK4044: 无法识别的选项“/-exclude-all-symbols”；已忽略
LINK : warning LNK4044: 无法识别的选项“/-out-implib”；已忽略
LINK : warning LNK4044: 无法识别的选项“/-stack”；已忽略
LINK : fatal error LNK1181: 无法打开输入文件“.\import.lib”
clang: error: linker command failed with exit code 1181 (use -v to see invocation)

scons: *** [V:\githubs\NUITKA~1\basic\main.exe] Error 1181
Nuitka-Reports: Compilation report written to file 'nuitka-crash-report.xml'.
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'.
```

**Comment by kayhayen** [comment]
The use of `SetDllDirectoryW` not working means you do not have a Windows SDK in the way it is expected. It seems to be present, but it probably lacks some defines. What I do not see, is that you probably have LLVM in your PATH, which is not supported. It might be missing some defines.

You would have to look into the Windows SDK and the Clang you are using, where the incompatibility lies. For what I know, GCC comes with a modified Windows SDK that works, and if you use the downloaded MinGW64, that should work. 

The bug here is that your LLVM from `%PATH%` is even used. It probably would have to be replaced with the path to the clang.exe inside of the MinGW64 that Nuitka does use, but it's also very unfriendly to do that, since it stops people from trying it, if they want to. But I guess, they they have to set `CC` environment.

**Comment by shenjackyuanjie** [comment]
let me have a try with downloaded mingw64

**Comment by kayhayen** [comment]
I have changed the handling of "--clang" to force searched C compiler to "clang" to not apply on Windows in MinGW64 mode anymore. Also, if --clang is given and a compiler was detected that is not a clang binary, it rejects it now, so environment provided gcc will be dropped, etc.

That should resolve your issue.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
If you wanted to force LLVM clang.exe, you would have to set the environment variable CC to its path and then use --clang, that would allow to continue attempting to make it work. I have very little interest in debugging its interactions with the Windows SDK though, or become limited to what works with it, or how well. C compilers on Windows are notoriously bad for compatibility with the platform features, that is why many other GCC forms are not allowed and it may be the same for Clang, without winlibs patches it might be garbage.
