### ISSUE TITLE
How do I apply traceback-encryption to a module?

### ISSUE THREAD

**Issue by parkilwoo** [Nuitka/Nuitka#2637]
- OS: ubuntu 22.04
- Python: 3.8

hello. I'm currently using the commercial version of Nuitka. The traceback-encryption plugin works fine in the .py file, but when I add the --module option, I get the following error and can't apply it. Is it still not possible to use traceback-encryption plugin in module?

![Screenshot from 2024-01-03 16-44-55](https://github.com/Nuitka/Nuitka/assets/56834479/16c6af57-2e77-4094-8d79-124cce92d0af)

**Comment by kayhayen** [comment]
Yes, module mode cannot encrypt tracebacks yet. We have no control over the running Python unfortunately.
