### ISSUE TITLE
Error in use --include-package-data selenium

### ISSUE THREAD

**Issue by Radomur** [Nuitka/Nuitka#2638]
I'm having trouble running the program after compilation - "Message: Unable to obtain driver for chrome using Selenium Manager.;"
I read in the thread (https://github.com/Nuitka/Nuitka/issues/456#issuecomment-826575917) that  the parameter "--include-package-data selenium" can help me.

```
nuitka --follow-imports --standalone --enable-plugin=tk-inter --include-package-data selenium  tkint.py --run 
```
I have an error writing:
"**Usage: main.py [--module] [--run] [options] main_module.py
main.py: error: The '--include-package-data' option requires an argument with '--include-package-data='.**"

Python 3.11.7
Windows 10 64 bit
pip install nuitka

`attrs==23.2.0
beautifulsoup4==4.12.2
certifi==2023.11.17
cffi==1.16.0
charset-normalizer==3.3.2
h11==0.14.0
idna==3.6
mysql-connector==2.2.9
mysql-connector-python==8.2.0
Nuitka==1.9.6
ordered-set==4.1.0
outcome==1.3.0.post0
packaging==23.2
protobuf==4.21.12
pycparser==2.21
PySocks==1.7.1
python-dotenv==1.0.0
requests==2.31.0
selenium==4.16.0
selenium-stealth==1.0.6
sniffio==1.3.0
sortedcontainers==2.4.0
soupsieve==2.5
trio==0.23.2
trio-websocket==0.11.1
urllib3==2.1.0
webdriver-manager==4.0.1
wsproto==1.2.0
zstandard==0.22.0`

**Comment by kayhayen** [comment]
You better read and try to understand what the error message is trying to tell you though. Nuitka no longer accepts options in the format you gave, for ages now.
