### ISSUE TITLE
Nuitka stuck on transformers.utils.dummy_pt_objects file

### ISSUE THREAD

**Issue by WhozKunal** [Nuitka/Nuitka#2639]
I am trying to make a py file to exe which is has ml model i am using nuitka but the nuitka stuck 97% on that file transformers.utils.dummy_pt_objects   and its around 8 hour still stuck on that not going .

Please help if anything you have

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."

**Comment by WhozKunal** [comment]
ok thanks for the details i am creating a new report
