### ISSUE TITLE
High CPU Usage and Compilation Stalling on 'dummy_pt_objects.py' from Transformers Library

### ISSUE THREAD

**Issue by WhozKunal** [Nuitka/Nuitka#2640]
I am encountering an issue during the Nuitka compilation process where the CPU usage drops to 0%, causing the compilation to appear stuck. This behavior occurs specifically when the process encounters the file "dummy_pt_objects.py" from the transformers library. The CPU usage remains high until it reaches this file, at which point it drops to 0%. I have tried updating Nuitka and the Transformers library to their latest versions, but the problem persists. Additionally, I've excluded the problematic file using the .nuitka_include workaround, but it did not resolve the issue. The issue is reproducible on both Windows and Linux environments. I am using Nuitka version 1.9.6 and Python version 3.10.11 Any insights or suggestions on how to troubleshoot and resolve this issue would be greatly appreciated.

**Comment by kayhayen** [comment]
Keep deleting the issue template, and I will block you.
