### ISSUE TITLE
File name case sensitivity issues in the Windows system

### ISSUE THREAD

**Issue by lidanqing123** [Nuitka/Nuitka#2646]
I developing on Windows. This error may be due to the fact that I have set up my Windows system's environment.

```
fsutil file setCaseSensitiveInfo path enable
```
This is because when using Git, I often run into file or directory name case conflicts.

I'd suggest that nuitka could change os.path.normcase to os.path.normpath

_Originally posted by @lidanqing123 in https://github.com/Nuitka/Nuitka/issues/2645#issuecomment-1882203187_

**Comment by lidanqing123** [comment]
![图片](https://github.com/Nuitka/Nuitka/assets/21281783/a104be8e-dc10-4c17-96b8-baebbfad5101)

**Comment by lidanqing123** [comment]
https://learn.microsoft.com/en-us/windows/wsl/case-sensitivity

**Comment by kayhayen** [comment]
I removed one use of it the other day, where it checks for `.ico` suffix, simply because it is code duplication with `hasFileExtension` but I guess, that one does it too.

**Comment by kayhayen** [comment]
Using `os.path.normpath` does not allow for case insensitive approaches, so Python doesn't support it. I only tried with 3.10, but that what matters. So it seems we need our own function. The below code illustrates the main use of it. A new function that takes your setting into account is definitely doable, lets see if we find something existing.

```
def areSamePaths(path1, path2):
    """Decide if two paths the same.

    Args:
        path1: First path
        path2: Second path

    Returns:
        Boolean value indicating if the two paths point to the
        same path.

    Notes:

        Case differences ignored on platforms where that is the
        norm, and with it normalized, and turned absolute paths, and
        even short paths, it then becomes a mere string compare after that.
    """

    path1 = os.path.abspath(os.path.normpath(path1))
    path2 = os.path.abspath(os.path.normpath(path2))

    if os.path.exists(path1) and os.path.exists(path2):
        path1 = getExternalUsePath(path1)
        path2 = getExternalUsePath(path2)

    path1 = os.path.normcase(path1)
    path2 = os.path.normcase(path2)

    return path1 == path2
```

**Comment by kayhayen** [comment]
I have replaced uses of assignments from `os.path.normcase` that then can cause these filenames to be wrong, there were a few more things like that, and the code could be done better in all cases by using APIs that compare without modifying.

Generally it cannot be avoided. Comparisons cannot be made real, i.e. it's virtually impossible to detect if a folder has this attribute set in Python. The C API for that is very ugly, and even then, it's very unclear when it must be done or not, e.g. when searching for a module, when it's filename based and wrong in Python or not.

But I believe it might work better for you now.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
These changes are now on develop, let me know if it works for you now.

**Comment by kayhayen** [comment]
This is part of the stable release 2.0 that I just made.
