### ISSUE TITLE
Geopandas import error.

### ISSUE THREAD

**Issue by RybarskiDominik** [Nuitka/Nuitka#2647]
I have errors when i use "import geopandas as gpd"
When I remove the geopandas import, the program works normally.

`C:\Obszar roboczy\GML-2021-Kompilator\GML.dist>"C:\Obszar roboczy\GML-2021-Kompilator\GML.dist\GML.exe"
Traceback (most recent call last):
  File "C:\OBSZAR~1\GML-20~1\GML~1.DIS\GML.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\OBSZAR~1\GML-20~1\GML~1.DIS\geopandas\__init__.py", line 17, in <module geopandas>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\OBSZAR~1\GML-20~1\GML~1.DIS\geopandas\datasets\__init__.py", line 8, in <module geopandas.datasets>
StopIteration`

  > python -m nuitka --version
1.9.7
Commercial: None
Python: 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Program Files\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe (cl 14.3).

- How did you install Nuitka and Python:
pip install Nuitka

  > python -m pip freeze:
`altgraph==0.17.4
attrs==23.2.0
certifi==2023.11.17
click==8.1.7
click-plugins==1.1.1
cligj==0.7.2
colorama==0.4.6
cx-Freeze==6.15.12
cx-Logging==3.1.0
et-xmlfile==1.1.0
fiona==1.9.5
geopandas==0.14.2
lief==0.13.2
Nuitka==1.9.7
numpy==1.26.3
openpyxl==3.1.2
ordered-set==4.1.0
packaging==23.2
pandas==2.1.4
pefile==2023.2.7
pyinstaller==6.3.0
pyinstaller-hooks-contrib==2023.12
pyproj==3.6.1
PySide6==6.6.1
PySide6-Addons==6.6.1
PySide6-Essentials==6.6.1
python-dateutil==2.8.2
pytz==2023.3.post1
pywin32-ctypes==0.2.2
shapely==2.0.2
shiboken6==6.6.1
six==1.16.0
tzdata==2023.4
zstandard==0.22.0`

- Many times when you get an error from Nuitka, your setup may be special
when turn on program, always

My import module:
```
from PySide6.QtWidgets import (QApplication, QGraphicsLineItem, QMainWindow, QGraphicsItem, QFileDialog, QCheckBox,
    QTableWidget,QGraphicsEllipseItem, QTableWidgetItem, QLineEdit, QApplication, QMainWindow, QGraphicsView, QGraphicsScene, QGraphicsPolygonItem,
    QGraphicsTextItem, QToolBar)
from PySide6.QtGui import QFont, QPolygonF, QPolygonF, QPainter, QFont, QColor, QTransform, QBrush, QPen, QIcon, QPainterPath
from shapely.geometry import Polygon, MultiPolygon, Point, MultiLineString, LineString
from PySide6.QtSvg import QSvgRenderer
from PySide6.QtSvgWidgets import QGraphicsSvgItem
from PySide6.QtCore import Qt, QPointF, QPoint, QRectF
from PySide6 import QtCore, QtWidgets, QtGui
#from shapely.ops import unary_union
from os.path import exists
import geopandas as gpd
import xml.dom.minidom
import pandas as pd
import webbrowser
import openpyxl
import sqlite3
import logging
import random
import shutil
import time
import math
import sys
import re
import os```

- Avoid unnecessary options
i use:
python -m nuitka --standalone GML.py --enable-plugin=pyside6

**Comment by kayhayen** [comment]
@RybarskiDominik I think this might just be package data, try with `--include-package-data=geopandas.datasets` and let us know, in which case it just needs to be added to the yaml config.

**Comment by RybarskiDominik** [comment]
Everything works fine after include package geopandas.datasets.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
This is part of the stable release 2.0 that I just made.
