### ISSUE TITLE
Add necessary Info.plist keys to support Qt permission API with PySide6 application packaged as app bundle in macOS

### ISSUE THREAD

**Issue by shyamnathp** [Nuitka/Nuitka#2650]
**_This is not a bugreport, but rather a feature request._** 

Qt introduced a [permission API](https://www.qt.io/blog/permission-apis-in-qt-6.5) for macOS in its 6.5 release to allow the application to check and request certain permissions like bluetooth, camera, calender etc. This does not work with PySide6 on macOS because the permission API works by checking the Info.plist of the app bundle for the relevant properties eg: NSCameraUsageDescription for camera. When running a python PySide6 script (i.e. python /path/to/pyside_script.py) the app bundle is the Python interpreter itself and its Info.plist file does not contain these required properties. Because of macOS security model, it is also not possible to modify and use a custom Info.plist file at runtime. Therefore, the only way the Qt permission API works with macOS is by adapting the Info.plist when packaging the PySide6 application. In the case of Nuitka, this means packaging a PySide6 application with the option _--macos-create-app-bundle_.

Since at PySide6 we recommend Nuitka as the tool for deploying PySide6 application, we thought it best to file a feature request here. From my understanding, the issue can be fixed by tweaking this file [https://github.com/Nuitka/Nuitka/blob/develop/nuitka/utils/MacOSApp.py](https://github.com/Nuitka/Nuitka/blob/develop/nuitka/utils/MacOSApp.py) after checking if one of the permission classes exists in the Python code of the project. Ideally, I think this should look something like, but i might be completely wrong:

```
if (QCameraPermission in Nuitka Node Tree):
    infos["NSCameraUsageDescription"] = "Allow camera usage"
```

Another option would be to pass a custom Info.plist file as a Nuitka cli argument. If the option is passed, then use the custom Info.plist for the application. Otherwise use the Info.plist file generated by Nuitka.

A third option would be to add additional linker options to compiled Nuitka binary to embed a custom Info.plist into the text segment of the binary. With this approach it will probably ignore the Info.plist file in the app bundle. I am not sure if this is even required since option 1 seems like the correct approach.

I am more than happy to create a PR with some guidance across the Nuitka code base. Also, I would love to know your inputs and suggestions on this and if this could be a possible feature to be added to Nuitka. Thanks.

**Comment by kayhayen** [comment]
Did you consider using `--macos-app-protected-resource` which I think does that. There is a section `MacOS Entitlements` in the User Manual too, which shows how to get microphone access.

**Comment by shyamnathp** [comment]
Thank you so much. That looks exactly like what i need. Let me check it out.

**Comment by kayhayen** [comment]
The naming is probably too technical for somebody to discover it. Also, one day the final build page needs to point to OS specific features not used.
