### ISSUE TITLE
olefile  LookupError: unknown encoding: UTF-16LE

### ISSUE THREAD

**Issue by abyss-zues** [Nuitka/Nuitka#2654]
I packaged a module using Nuitka, which uses msofcrypto tool. When I called this module using another program, the program encountered an error
The error message is as follows
![image](https://github.com/Nuitka/Nuitka/assets/110171545/b5952b72-f8fc-496f-a071-fda4dadb2c76)
When I use debugging mode to check for errors,run ''.decode('UTF-16LE', errors) does not result in any errors,But when running 'utf16_str.decode('UTF-16LE', errors)' again, it still reports an error。
When an error occurs, the content of the variable is shown in the following figure
![image](https://github.com/Nuitka/Nuitka/assets/110171545/8b70ab5c-11c1-4ddc-a63e-0ef106e7be3e)
I'm sorry, this is my first time submitting a question, and because I'm not good at English, I used a translator to complete these sentences。

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
