### ISSUE TITLE
Can't import numpy. numpy: This plugin has been deprecated

### ISSUE THREAD

**Issue by lattellie** [Nuitka/Nuitka#2657]
**- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.**

2.0rc10
Commercial: None
Python: 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\Latte\anaconda3\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\cl.exe (cl 14.3).

**- How did you install Nuitka and Python**

standalone installer for Python and git for Nuitka.

**- The specific PyPI names and versions**

Nuitka @ https://github.com/Nuitka/Nuitka/archive/factory.zip#sha256=752129914aa458fa8da7f3097f06066ff3ef81668c9c72e9c9d7e185b22f2f74
numpy==1.26.2
numpydoc @ file:///C:/Windows/TEMP/abs_30799058-86dd-4401-b621-d172137a4d87_ra3twm7/croots/recipe/numpydoc_1657529873713/work
opencv-contrib-python==4.8.0.74
opencv-python==4.8.1.78

**- Also supply a Short, Self Contained, Correct, Example**

When I have import numpy on top of my .py file, the exe simply opens and closes. so I tested it with this:

    def main():
        b = 'no'
        while b.lower() != 'yes':
            b = input("do you want to start program? [yes/no]")
        try:
            import numpy as np
        except:
            print("cannot import np")
        try:
            import cv2
        except:
            print("cannot import cv2")
        try:
            img = cv2.imread("output-imgs/captured4.jpg")
            cv2.imshow("video stream", img)
            cv2.waitKey()
        except:
            print("cannot find image")
        b = 'no'
        while b.lower() != 'yes':
            b = input("do you want to end program? [yes/no]")
    
    if __name__ == "__main__":
        main()

and here's the output I got after running the exe file:

      do you want to start program? [yes/no]yes
      cannot import np
      OpenCV bindings requires "numpy" package.
      Install it via command:
          pip install numpy
      cannot import cv2
      cannot find image

**- Provide in your issue the Nuitka options used**
python -m nuitka --standalone test.py

**- Note if this is a regression**
No.

Thanks in advance!

**Comment by KevinRodriguez777** [comment]
Hello, can you please include the full traceback you get when you run the executable? along with the compilation report from a compilation report from `--report`? thank you.

**Comment by lattellie** [comment]
Here's the traceback I got when executing `python -m nuitka --standalone imshow.py --report=compilation-report.xml`

    Nuitka-Options: Used command line options: --standalone imshow.py
    Nuitka-Options: --report=compilation-report.xml
    Nuitka: Starting Python compilation with Nuitka '2.0rc10' on Python '3.9' commercial
    Nuitka: grade 'not installed'.
    Nuitka-Plugins:delvewheel: Detected usage of 'delvewheel' version '1.5.1' in module
    Nuitka-Plugins:delvewheel: 'numpy'.
    Nuitka: Completed Python level compilation and optimization.                     
    Nuitka: Generating source code for C backend compiler.
    Nuitka: Running data composer tool for optimal constant value handling.                 
    Nuitka: Running C compilation via Scons.
    Nuitka-Scons: Backend C compiler: cl (cl 14.3).
    Nuitka-Scons: Backend linking program with 120 files (no progress information available
    Nuitka-Scons: for this stage).
    Nuitka-Scons: Compiled 120 C files using clcache with 120 cache hits and 0 cache misses.
    Nuitka-Plugins:dll-files: Found 1 file DLLs from cv2 installation.
    Nuitka: Keeping build directory 'imshow.build'.                                         
    Nuitka: Successfully created 'imshow.dist\imshow.exe'.
    Nuitka-Reports: Compilation report written to file 'compilation-report.xml'.

and here's the compilation report I got.
[compilation-report.md](https://github.com/Nuitka/Nuitka/files/14013542/compilation-report.md)

Thanks for the speedy response!

**Comment by kayhayen** [comment]
You might want to read up on what a traceback is. We actually were looking for the exception information that your test program suppresses with a `except: pass` as otherwise we cannot have a clue what's going on.

**Comment by KevinRodriguez777** [comment]
```
import numpy as np
import cv2


def main():

    img = cv2.imread("flier.jpg")
    cv2.imshow("video stream", img)
    cv2.waitKey()


if __name__ == "__main__":
    main()
```
compiles and runs fine on latest nuitka.

**Comment by KevinRodriguez777** [comment]
I'm using cpython already, let me try via ananconda / conda.

**Comment by KevinRodriguez777** [comment]
i guess someone else is just going to have to try it with conda, it's refusing to work on my system for whatever reason.

**Comment by kayhayen** [comment]
Nah, waiting for feedback a couple more days, then if nothing is forthcoming, that's the close as invalid for "lack of feedback". It's the users responsibility to provide the answer to my question, and when then nothing happens, e.g. the user lost interest, or doesn't read email, closing and deleting even can be best options so other users with the same issue, which would have to be frequent, can raise it again. And if it's very special, that user would have to say it. I should start taking notes for the triage team rationales.

**Comment by kayhayen** [comment]
And one more thing, if you feel like you are out of there, unassign yourself. Not assigned issues is something I will be searching at occasions, for as long as it's assigned to you, I would see this, and hesitate to take action, and I bet others too, unassigned means free for taking, right.

**Comment by kayhayen** [comment]
Closing for lack of feedback.
