### ISSUE TITLE
olefile UTF-16LE decode error

### ISSUE THREAD

**Issue by abyss-zues** [Nuitka/Nuitka#2660]
Nuitka Version 1.9.7
Commercial: None
Python: 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\Abyss\AppData\Local\pypoetry\Cache\virtualenvs\workspace-hUud8Oj8-py3.11\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe (cl 14.3).

Python installation using the official exe installation package
Nuitka using Poetry

Virtual Environment Information：
beautifulsoup4==4.12.3
black==23.12.1
Brotli==1.1.0
certifi==2023.11.17
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
cryptography==42.0.0
darkdetect==0.8.0
et-xmlfile==1.1.0
ezdxf==1.1.4
fonttools==4.47.2
idna==3.6
inflate64==1.0.0
lxml==5.1.0
msoffcrypto-tool==5.3.1
multivolumefile==0.2.3
mypy-extensions==1.0.0
Nuitka==1.9.7
numpy==1.26.3
olefile==0.47
openpyxl==3.1.2
ordered-set==4.1.0
packaging==23.2
pathspec==0.12.1
pillow==10.2.0
platformdirs==4.1.0
psutil==5.9.8
py7zr==0.20.8
pybcj==1.0.2
pycparser==2.21
pycryptodomex==3.20.0
pyparsing==3.1.1
pyppmd==1.1.0
PySide6==6.4.2
PySide6-Addons==6.4.2
PySide6-Essentials==6.4.2
PySide6-Fluent-Widgets==1.4.6
PySideSix-Frameless-Window==0.3.6
pywin32==306
pyzstd==0.15.9
requests==2.31.0
shiboken6==6.4.2
soupsieve==2.5
texttable==1.7.0
typing_extensions==4.9.0
urllib3==2.1.0
zstandard==0.22.0

Nuitka commands：nuitka --module --output-dir=out --mingw64 --include-package=Tools --remove-output --no-pyi-file --include-package=bs4 Tools

Error Details
`Traceback (most recent call last):
  File "E:\Projects\Workspace\Plug\Tools\0.2.1\Tools\SAP\SAPCard.py", line 133, in on_PushButton_clicked
  File "E:\Projects\Workspace\Plug\Tools\0.2.1\Tools\SAP\SAPCard.py", line 56, in check_pwd
  File "E:\Projects\Workspace\Plug\Tools\0.2.1\Tools\ToolsClass.py", line 72, in get_pwd
  File "C:\Users\Abyss\AppData\Local\pypoetry\Cache\virtualenvs\workspace-hUud8Oj8-py3.11\Lib\site-packages\msoffcrypto\__init__.py", line 45, in OfficeFile
    ole = olefile.OleFileIO(file)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Abyss\AppData\Local\pypoetry\Cache\virtualenvs\workspace-hUud8Oj8-py3.11\Lib\site-packages\olefile\olefile.py", line 1128, in __init__
    self.open(filename, write_mode=write_mode)
  File "C:\Users\Abyss\AppData\Local\pypoetry\Cache\virtualenvs\workspace-hUud8Oj8-py3.11\Lib\site-packages\olefile\olefile.py", line 1416, in open
    self.loaddirectory(self.first_dir_sector)
  File "C:\Users\Abyss\AppData\Local\pypoetry\Cache\virtualenvs\workspace-hUud8Oj8-py3.11\Lib\site-packages\olefile\olefile.py", line 1802, in loaddirectory
    root_entry = self._load_direntry(0)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Abyss\AppData\Local\pypoetry\Cache\virtualenvs\workspace-hUud8Oj8-py3.11\Lib\site-packages\olefile\olefile.py", line 1834, in _load_direntry
    self.direntries[sid] = OleDirectoryEntry(entry, sid, self)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Abyss\AppData\Local\pypoetry\Cache\virtualenvs\workspace-hUud8Oj8-py3.11\Lib\site-packages\olefile\olefile.py", line 819, in __init__
    self.name = ole_file._decode_utf16_str(self.name_utf16)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Abyss\AppData\Local\pypoetry\Cache\virtualenvs\workspace-hUud8Oj8-py3.11\Lib\site-packages\olefile\olefile.py", line 1185, in _decode_utf16_str
    unicode_str = utf16_str.decode('UTF-16LE', errors)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
LookupError: unknown encoding: UTF-16LE
`
I apologize for not being able to provide the minimal code, as I am unable to reproduce it in the minimal code at this time.
I use Nuitka to package private Python packages into .pyd files with Python references.
I have tested this problem from version 1.7.9 to 1.9.7, but not other versions.
This problem occurs with Mingw64, Clang, and MVSC compilers.
I can't seem to use utf-16le decode in the exception in debug mode.

This problem has been bothering me for a long time, please help me to find out where the problem is, thank you very much!

**Comment by kayhayen** [comment]
You are not indicating while Python you are running in, what do you mean with "debug" mode?

**Comment by abyss-zues** [comment]
Debug mode in pycharm

**Comment by kayhayen** [comment]
Does it happen outside of debug mode of PyCharm?

**Comment by abyss-zues** [comment]
Yes, it happens in other environments. But when the module is run as source or packaged as a separate EXE file, it works fine. The module is required to be imported by another Python software (A), which is equivalent to a launcher or plugin manager, and the problem occurs whether A is run as source code or after compilation with Nuitka. It can be observed that the module does not contain an olefile, it uses the olefile package from the virtual environment, which can also be located using Debug mode. I'm guessing that something in the module after packaging is causing the Codecs to be corrupted.

I'm really sorry that I can't reproduce the problem using minimal code and can't give you the source code.

I admire your dedication and appreciate your help!

**Comment by KevinRodriguez777** [comment]
can you please figure out a minimal working example we can reproduce? without one it's near impossible to help.

**Comment by abyss-zues** [comment]
Sorry for the wait, I finally made the latest code that can be recovered, here to correct, the module after repeated import will appear the above problem.Attached is the source code, you just need to use nuitka to compile the 'Demo' package into a module (nuitka commands are also attached) and then run DemoMain.py.
demo.xlsx is a blank encrypted Excel file.
[ErrorDemo.zip](https://github.com/Nuitka/Nuitka/files/14105899/ErrorDemo.zip)

**Comment by KevinRodriguez777** [comment]
Doesn't seem like a straightfoward MRE, but let me give it a go.

**Comment by abyss-zues** [comment]
Excuse me, did you find out what the problem is?

**Comment by KevinRodriguez777** [comment]
@kayhayen this will need your expertise, i *think* this is an issue with nuitkas `--module` mode, please confirm.

**Comment by kayhayen** [comment]
> sys.meta_path.clear()

**Comment by kayhayen** [comment]
I don't think many imports will work after that, this is a faulty code for just about anything. Nuitka's loaders, as well as Python ones are removed, thus e.g. encodings may or may not be loadable anymore at that point.
