### ISSUE TITLE
The icon for .exe is Ok, but when the exe is running, the default icon.

### ISSUE THREAD

**Issue by dim22-star** [Nuitka/Nuitka#2663]
Windows 10 and Windows Server 2022
Python 3.9
Nuitka 1.9.7

python -m nuitka --onefile --disable-console --windows-icon-from-ico=main-ico.png main.py

I also tried using main.ico
I used different icon sizes (from 16 to 256).
an exe file with an icon, but in the program itself (top left) and in the taskbar, the default icon is used.
![Безымянный](https://github.com/Nuitka/Nuitka/assets/90024771/fa80eed1-2d92-443c-b727-cb69dcf89c21)

![Безымянный](https://github.com/Nuitka/Nuitka/assets/90024771/b43c7660-89ee-4ecb-a52b-95ca2cbf8311)

**Comment by kayhayen** [comment]
The option doesn't magically make Qt or whatever pick up the icon for use in its Windows. You have to still load it manually there too.

**Comment by dim22-star** [comment]
Hmm. Six months ago there was no such problem, the icon changed everywhere.I use Pywebview.

**Comment by kayhayen** [comment]
Please open a new issue, describing the regression if any. You didn't even come close to a issue description, so I am treating it as a question.
