### ISSUE TITLE
Does Nuitka compile itself?

### ISSUE THREAD

**Issue by abyss-zues** [Nuitka/Nuitka#2665]
Does Nuitka compile itself? Using '--onefile', '--module' or '--standalone' mode? How should I compile it?

**Comment by LinuxUserGD** [comment]
See https://github.com/Nuitka/Nuitka/issues/1746#issuecomment-1223816524

**Comment by kayhayen** [comment]
@LinuxUserGD Let me now if you want to become part of Nuitka/nuitka-issue-handling team, so you can manage issues that you feel comfortable with yourself fully
