### ISSUE TITLE
Cannot pack Python files using --include-data-dir in newer version of Nuitka

### ISSUE THREAD

**Issue by Rayterex** [Nuitka/Nuitka#2666]
I pack Blender Python scripts and Maya Python scripts inside executable built with Nuitka. However never versions of Nuitka don't allow packing of Python files.

Minimal example:

**(1) Create two empty python files:**
```
test_nuitka_data_dir/dependency_1.py
test_nuitka_data_dir/dependency_2.py
```

**(2) test_nuitka.py** - This test outputs dependency python files in ```test_output_dir```
```
import shutil, sys, os

def find_in_path(dir_name):

    path_out = False
    for path in sys.path:
        if os.path.isdir(os.path.join(path, dir_name)):
            path_out = os.path.join(path, dir_name)
    return path_out

shutil.copytree(find_in_path('test_nuitka_data_dir'), 'test_output_dir')
print('Test works!')
```

**(3) build_test_nuitka.py**
```
import subprocess

include_data_dir = 'test_nuitka_data_dir'
main_python_file_path = 'test_nuitka.py'

args = ['nuitka', 
        '--msvc=latest',
        '--standalone',
        '--onefile',
        '--follow-imports',
        '--include-data-dir=%s=%s' % (include_data_dir, include_data_dir),
        '--remove-output',
        main_python_file_path]
        
subprocess.call(args, shell = True)
```

When I try to run ```build_test_nuitka.py``` with Nuitka ```1.9.7``` I get this waning:
```
Nuitka-Options:WARNING: No data files in directory 'test_nuitka_data_dir.'
```

test_nuitka.exe crashes since ```find_in_path``` finds nothing. However if I build this test using old version of Nuitka ```0.9.6``` everything works just fine. ```test_nuitka_data_dir``` is created with ```dependency_1.py``` and ```dependency_2.py``` files

Does Nuitka no longer treat python files as data files? #2088

**Comment by Rayterex** [comment]
Thanks! Makes sense.

If anyone is interested in this topic in the future. The only workaround I've found is to list directories that contain ```.py``` files recursively and add them one by one using ```'--include-data-files=<subdirectory_path>/*.py=<subdirectory_path>/'```. Since I am shipping my executable with my custom python core libraries and 3rd python libraries that are not contained in Maya or Blender, like NumPy, Scipy, OpenCV, PySide, this includes tens of thousands of these flags: ```--include-data-files```, but it is what it is. Second option, that I haven't implemented yet, would be to zip all the python files and unzip them when the .exe is launched

**Comment by kayhayen** [comment]
You are very much on your own there, but well without your right to get that to work.
