### ISSUE TITLE
How to import libmagic by python libraries?

### ISSUE THREAD

**Issue by nachocodexx** [Nuitka/Nuitka#2672]
I have an error when I try to package my program, one of the libraries that the executable programm needs is the libmagic.  The executable works in my laptop, but when I try to execute it in a friend's laptop, it shows the following error: 

ImportError: failed to find libmagic.  Check your installation. 

I try to include python-magic-bin to include the library but that not work, there is another option to makes libmagic work in a Nuitka executable. 

I try to use the following command to generate the executable: 

 python -m nuitka --standalone --include-package=python-magic-bin --include-data-files=./magic_dlls/*=./ --windows-icon-from-ico=.\assets\mictlan_logo_dark.ico .\watcher.py

But i get the following error: 
FATAL: Error, failed to locate package 'python-magic-bin' you asked to include.

- Nuitka version
python -m nuitka --version shows the below info:
1.9.7
Commercial: None
Python: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\cl.exe (cl 14.3).

- How did you install Nuitka and Python -> Using pip
- Many times when you get an error from Nuitka, your setup may be special
This error persist over and over again in my friend's laptop.

/

**Comment by kayhayen** [comment]
The --include-package takes not distribution names, but package names. Read up on the difference.

Not having a reproducer I cannot really do anything to resolve it in some sort of way. Please provide one, or we will have to close it.

**Comment by nachocodexx** [comment]
Thanks for your quick response, I assign to --include-package flag the name of the python-magic-bin library that it suppose to install libmagic for windows which is my target OS for running my program.  But when I try to run my program on windows it crashed and show the error message :

ImportError: failed to find libmagic.  Check your installation

But in my code I import magic library. 

The interesting here is that in my PC the program works. 


I need help to figure out how to install libmagic using python libraries or maybe if someone has solved before. 

Give a couple of hour to try to create a minimal example to reproduce the error. 

Thanks.

**Comment by KevinRodriguez777** [comment]
@nachocodexx can you please tell us precisely how you installed libmagic and a minimal reproducer of the code.

**Comment by nachocodexx** [comment]
Sorry  for taking to long to reply, I made the decision to remove that dependency from my client and send it to the server, it was easier.

Sorry for the inconvenience, I will close this issue.
