### ISSUE TITLE
Question: Does --onefile produced dist folder equal what --standalone produces?

### ISSUE THREAD

**Issue by bersbersbers** [Nuitka/Nuitka#2676]
I am running nuitka with `--standalone` and `--onefile`, separately. I just discovered that the `--onefile` output folder has a `project.dist` folder that seems to include the same files as the `--standalone` one, so I wonder if I can get away with just calling `--onefile` (saving half the CI compilation time) and grabbing both distributions from here. All files in the two folders seem be identical, with the exception of `project.exe` (which has the same byte size, but different content).

Maybe this is worth documenting, too.

**Comment by kayhayen** [comment]
The standalone distribution is compiled differently when used with `--onefile`. For example `__compiled__.containing_dir` will be different and even crash and a bunch of plugins, e.g. code signing, UPX, PySide6, and others will behave differently, so all sorts of paper cuts can happen.

That said, the .dist folder is created for easier debugging, and sort of expected to often work. But guaranteeing that is a different beast.

**Comment by bersbersbers** [comment]
Thanks, that helps a lot!
