### ISSUE TITLE
CompiledCellType.c:240:1: error: invalid conversion

### ISSUE THREAD

**Issue by sullivan50909** [Nuitka/Nuitka#2678]
My problem exists in Nuitka version 2.0, but not in version 1.9.7. My code has not changed significantly in the last 6 months and always built fine with Nuitka.
 
- Non-working Nuitka version
2.0
Commercial: None
Python: 3.9.10 (main, Jan 15 2024, 17:20:02)
Flavor: Unknown
Executable: /usr/local/bin/python3
OS: Linux
Arch: x86_64
Distribution: Centos (based on Fedora) 7
Nuitka-Scons: The provided gcc is too old, switching to its g++ instead.

- Working Nuitka version
1.9.7 and earlier

- How did you install Nuitka and Python
pip3 install --user nuitka 
(same for working and non-working)

- The specific PyPI names and versions

I don't think this issue relates to any additional packages. 

- Also supply a Short, Self Contained, Correct, Example

When I try to compile my code, I get the following error:
In file included from static_src/CompiledFunctionType.cpp:3080:0:
/root/.local/lib/python3.9/site-packages/nuitka/build/static_src/CompiledCellType.c:240:1: error: invalid conversion from ‘void*’ to ‘PyAsyncMethods*’ [-fpermissive]

I'm out of time to come up with a simplified example tonight. If this is not enough information for you to reproduce the issue, let me know and I'll come up with something tomorrow.
 

- Provide in your issue the Nuitka options used

 time python3 -m nuitka --standalone --python-flag=no_docstrings --include-module=distutils.util --include-package=core --include-module=pyproj._compat --include-data-files=/config/*=config/ myFunction.py

- Note if this is a regression
Yes.

The problem is caused by:
https://github.com/Nuitka/Nuitka/commit/710069862346b7aa5f019c9cd6d105a05af708e1

If I put back the if statement at line 201 of CompiledCellType.c, my code starts working.

#if PYTHON_VERSION < 0x300
    (cmpfunc)Nuitka_Cell_tp_compare, // tp_compare
#else
    0,                          // tp_reserved
#endif

**Comment by kayhayen** [comment]
You are using the C++ fallback due to too old gcc, which has this issue. Use a more recent gcc either way. I have prepared a fix for MSVC 14.2 which is also using C++ for a similar problem, but now I am sort of confused, why it didn't happen there. In theory, factory branch is supposed to work with this.

**Comment by sullivan50909** [comment]
I just tried the factory branch and it passed my simplified test. Thanks.
I can't update gcc right now, but I'm working on doing that soon.

**Comment by kayhayen** [comment]
This is part of the hotfix release 2.0.1 that I just made.
