### ISSUE TITLE
error on importing GPytorch

### ISSUE THREAD

**Issue by ooodragon94** [Nuitka/Nuitka#2683]
OSError: Can't get source for <compiled_function _jit_linear_cg_updates at 0x00000245E766E400>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available.

I'm currently using nuitka to build my engine.
Seems like it fails on importing GPytorch.
This is my guess but I think it is very likely, since it seems like others are having the same problem while using pyinstaller.

https://github.com/pyinstaller/pyinstaller/issues/7647

any idea on solving this problem in nuitka?

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
