### ISSUE TITLE
Nuitka 2.0 stuck  when build vedo, seem go into an infinite loop

### ISSUE THREAD

**Issue by zincers** [Nuitka/Nuitka#2684]
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version
    > 2.0
    > Commercial: None
    > Python: 3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)]
    > Flavor: Anaconda Python
    > Executable: D:\Software\miniconda3\envs\BladeDesigner\python.exe
    > OS: Windows
    > Arch: x86_64
    > WindowsRelease: 10

- How did you install Nuitka and Python

  conda virtualenv, pip install nuitka

- The specific PyPI names and versions

  > python -m pip freeze
    > colorcet==3.0.1
    > contourpy==1.2.0
    > cycler==0.12.1
    > Deprecated==1.2.14
    > et-xmlfile==1.1.0
    > fonttools==4.47.2
    > geomdl==5.3.1
    > kiwisolver==1.4.5
    > markdown-it-py==3.0.0
    > matplotlib==3.6.3
    > mdurl==0.1.2
    > more-itertools==10.2.0
    > Nuitka==2.0
    > numpy==1.26.3
    > openpyxl==3.1.2
    > ordered-set==4.1.0
    > packaging==23.2
    > pandas==2.2.0
    > param==2.0.2
    > pillow==10.2.0
    > psutil==5.9.8
    > pyct==0.5.0
    > Pygments==2.17.2
    > pyparsing==3.1.1
    > PySide6==6.6.1
    > PySide6-Addons==6.6.1
    > PySide6-Essentials==6.6.1
    > python-dateutil==2.8.2
    > pytz==2023.4
    > pywin32==306
    > PyYAML==6.0.1
    > QtPy==2.4.1
    > rich==13.7.0
    > ruamel.yaml==0.18.5
    > ruamel.yaml.clib==0.2.8
    > scipy==1.12.0
    > shapely==2.0.2
    > shiboken6==6.6.1
    > six==1.16.0
    > triangle==20230923
    > trimesh==4.1.0
    > tzdata==2023.4
    > vedo==2023.5.0
    > vtk==9.3.0
    > wrapt==1.16.0
    > xlrd==2.0.1
    > XlsxWriter==3.1.9
    > zstandard==0.22.0

- Also supply a Short, Self Contained, Correct, Example

[https://github.com/marcomusy/vedo/blob/master/examples/basic/buildmesh.py](https://github.com/marcomusy/vedo/blob/master/examples/basic/buildmesh.py)

```
"""Manually build a mesh from points and faces"""
from vedo import Mesh, show

# Define the vertices and faces that make up the mesh
verts = [(50,50,50), (70,40,50), (50,40,80), (80,70,50)]
cells = [(0,1,2), (2,1,3), (1,0,3)] # cells same as faces

# Build the polygonal Mesh object from the vertices and faces
mesh = Mesh([verts, cells])

# Set the backcolor of the mesh to violet
# and show edges with a linewidth of 2
mesh.backcolor('violet').linecolor('tomato').linewidth(2)

# Create labels for all vertices in the mesh showing their ID
labs = mesh.labels2d('pointid')

# Print the points and faces of the mesh as numpy arrays
print('vertices:', mesh.vertices)
print('faces   :', mesh.cells)

# Show the mesh, vertex labels, and docstring
show(mesh, labs, __doc__, viewup='z', axes=1).close()
```

- Provide in your issue the Nuitka options used

`python -m nuitka --msvc=14.3 --standalone .\tests\buildmesh.py`

- Note if this is a regression

  it used to work in version 1.9.7.

--------
Nuitka Stuck here
> Nuitka-Plugins:delvewheel: Detected usage of 'delvewheel' version '1.5.2' in module 'numpy'.
> Nuitka-Plugins:delvewheel: Detected usage of 'delvewheel' version '1.5.1' in module 'vtkmodules'.
> PASS 1: 96.1%|████████████████████████ | 473/492, vedo.addons

When  activate `--verbose` option, stuck here 

> Nuitka-Optimization: D:\Software\miniconda3\envs\BladeDesigner\Lib\site-packages\vedo\addons.py:3929 : new_statements : Reduced scope of tried block. Trailing statements at D:\Software\miniconda3\envs\BladeDesigner\Lib\site-packages\vedo\addons.py:3929/<Node 'STATEMENT_RELEASE_VARIABLE_TEMP' with {'variable_name': 'tuple_unpack_49__source_iter', 'owner': 'vedo$addons$$$function__86_Axes'}>,D:\Software\miniconda3\envs\BladeDesigner\Lib\site-packages\vedo\addons.py:3929/<Node 'STATEMENT_ASSIGNMENT_VARIABLE_FROM_TEMP_VARIABLE' with {'variable_name': 'lt0', 'is_temp': False, 'var_type': 'object', 'owner': 'vedo$addons$$$function__86_Axes'}>,D:\Software\miniconda3\envs\BladeDesigner\Lib\site-packages\vedo\addons.py:3929/<Node 'STATEMENT_DEL_VARIABLE_TOLERANT' with {'variable_name': 'tuple_unpack_49__element_1', 'is_temp': True, 'var_type': 'object', 'owner': 'vedo$addons$$$function__86_Axes'}>,D:\Software\miniconda3\envs\BladeDesigner\Lib\site-packages\vedo\addons.py:3929/<Node 'STATEMENT_ASSIGNMENT_VARIABLE_FROM_TEMP_VARIABLE' with {'variable_name': 'lt1', 'is_temp': False, 'var_type': 'object', 'owner': 'vedo$addons$$$function__86_Axes'}>,D:\Software\miniconda3\envs\BladeDesigner\Lib\site-packages\vedo\addons.py:3929/<Node 'STATEMENT_DEL_VARIABLE_TOLERANT' with {'variable_name': 'tuple_unpack_49__element_2', 'is_temp': True, 'var_type': 'object', 'owner': 'vedo$addons$$$function__86_Axes'}>.
> Nuitka-Optimization: D:\Software\miniconda3\envs\BladeDesigner\Lib\site-packages\vedo\addons.py:3929 : new_statements : Uninitialized temp variable 'tuple_unpack_49__element_1' is not released.
> Nuitka-Optimization: D:\Software\miniconda3\envs\BladeDesigner\Lib\site-packages\vedo\addons.py:3929 : new_statements : Uninitialized temp variable 'tuple_unpack_49__element_2' is not released.

**Comment by kayhayen** [comment]
With stuck you mean, like no output anymore, that's indeed very not good.

**Comment by kayhayen** [comment]
It's reproducible if I attempt to only compile the `vedo.addons` backing file with `--module`. It seems stuck on this line:

>    acts = titles + lines + labels + grids + framelines

And apparently it's endless looping trying to get the type shape of `lines` which is not a particularly hard variable. It's assigned from `[]` and then appended a few times, but then seems to get stuck in that lookup.

**Comment by kayhayen** [comment]
This code was added at some point:

```
                if trace1.isEscapeTrace() and trace1.previous is trace2:
                    version = versions[0]
                elif trace2 is trace1.isEscapeTrace() and trace2.previous is trace1:
                    version = versions[1]
                else:
                    version = self.addVariableMergeMultipleTrace(
                        variable=variable,
                        traces=(
                            trace1,
                            trace2,
                        ),
                    )

```

The intention was to avoid merge traces of traces that may or may not be escaped, and replace them with the escaped trace only. However, the second branch has a typo `trace2 is` that made it ineffective in those cases. Recent changes make escape traces actually consider their previous trace, before it was essentially giving unknown type shape. At that point, this became way more than a waste of memory, it became a scalability issue, where the ever deeper nesting of those traces could render code to become slower and slower to optimize the more escapes (usually unknown code can run) are seen.

The result of this will be two fold. Some codes will use a lot less value traces now, which would always have been a good idea, and this now compiles in somewhat acceptable time, albeit not too fast.

**Comment by zincers** [comment]
> Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html
> 
> Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

Thanks for your comment, factory branch works for me.

**Comment by kayhayen** [comment]
This is part of the hotfix release 2.0.1 that I just made.
