### ISSUE TITLE
Question about packaging with globally installed Nuitka in a virtual environment

### ISSUE THREAD

**Issue by mogoyu** [Nuitka/Nuitka#2686]
- Nuitka version 2.0

  > python  --version  3.8.18

I installed Nuitka on my system (globally), then I created a new project with pycharm in a virtual environment, and I installed all the libraries or packages I need in the virtual environment, and it executes correctly, and then I executed the Nuitka commands in the virtual environment on the command line in pycharm: nuitka --clang -- standalone --show-progress --show-memory --onefile --enable-plugin=pyside2 --windows-icon-from-ico=. standalone --show-progress --show-memory --onefile --enable-plugin=pyside2 --windows-icon-from-ico=... /logo.ico --output-dir=out main.py
will result in unpacked libraries and packages for the virtual environment. However, if I install Nuitka in the virtual environment and execute the same package command again in the virtual environment, the software will be packaged correctly. Is it possible to package the libraries and packages in the virtual environment correctly using the global Nuitka without installing Nuitka in the virtual environment? If so, what do I need to do?

**Comment by kayhayen** [comment]
Nuitka wants to run inside the virtual environment. Nuitka does not need to be installed. 

So if you do `python-from-virtualenv Nuitka.git/bin/nuitka` it will load Nuitka from there and it is never installed and always matches exactly what you do in git, update, edit, branch switch, etc.

Alternatively `python-from-virtualenv setup.py develop` injects a small pth file, with the same effect, and you can then use `python-from-virtualenv -m nuitka` as if it was installed, but it's not.
