### ISSUE TITLE
C compiler cannot compile C file generated from large Python file

### ISSUE THREAD

**Issue by Were-Logan-0110** [Nuitka/Nuitka#2687]
## Nutika --version
```sql
2.0
Commercial: None
Python: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
Flavor: CPython Official
Executable: E:\fbvenv\build\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
(gcc 13.2.0).

(Inside venv)
```
## COMMAND
```sql
./Scripts/nuitka --disable-console --standalone --lto=no --enable-plugin=pyqt5 main.py
```
### so i have a python file that is Qt compiled ui of 12K lines (582K characters) when nuitka gets stuck when it tries to compile its (C|Headers) generated code so in first it got stuck at *99,9%* and when i terminated c1.exe from task manger it said that it failed to compile it and also its object file was empty (0KB) so i tried again but to only compile it with the following command
```sql
nuitka --mingw FacebookGui.py --lto=no --enable-plugin=pyqt5
```
## **Output**
```sql
Nuitka-Options: Used command line options: --mingw FacebookGui.py --lto=no --enable-plugin=pyqt5
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure
Nuitka-Options:WARNING: that is intended.
Nuitka-Plugins:WARNING: pyqt5: Not relevant with this OS, or Nuitka arguments given, not activated.
Nuitka: Starting Python compilation with Nuitka '2.0' on Python '3.11' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: gcc (gcc 13.2.0).
Backend C: 83.3%|████████████████████▊    | 5/6
```

# Any idea how can i fix this?

# [Scons output](https://pastebin.com/Ni3C1mqU)

**Comment by Were-Logan-0110** [comment]
### Also there is a solution to my case is using the `loadUi` function from Qt instead and if u care about not sharing the ui file u can encrypt it with a hardcoded key lets say
```py
from cryptography.fernet import Fernet
key = b'zyX8lG9R_t74kPsRqH6OKfI8YbyKRFGiLt94Kpj5pPA='
cipherSuite = Fernet(key)
inputFilePath = "Gui.ui"
outputFilePath = "_AnStrangeName.dll"
with open(inputFilePath, 'rb') as inputFile:
    data = inputFile.read()
encryptedData = cipherSuite.encrypt(data)
with open(outputFilePath, 'wb') as outputFile:
    outputFile.write(encryptedData)
```
then you can decrypt it on startup
```py
        cSuite = Fernet(b'zyX8lG9R_t74kPsRqH6OKfI8YbyKRFGiLt94Kpj5pPA=')
        with open(appMainDir/"_AnStrangeName.dll", 'rb') as encFile:
            encData = encFile.read()
        decryptedData = cSuite.decrypt(encData)
        decryptedDataStr = decryptedData.decode('utf-8')
        uiFile = StringIO(decryptedDataStr)
        loadUi(uiFile,self)
```
## Here comes an issue if u were doing something like `self.ui = Ui_MainWindow()` as that will result into a not found attributes so u can proxify the __getattr__ dunder method to repalce self.ui with self as the following
```py
class Window(ResizeableWindow, QModernFramelessWindow):
    """_summary_

    Args:
        QMainWindow (_type_): _description_
    """
    def __getattr__(self, name):
        if name == "ui":
            return self
        else:
            return super().__getattr__(name)
    def __hasattr__(self, name):
        if name == 'ui':
            return True
        return super().__hasattr__(name)
```

# NOTE This doesnot solve nuitka problem obviously

**Comment by shenjackyuanjie** [comment]
there is one possible solution
use `--clang --msvc=latest` not `--mingw64`
is this case, it may just need a "bit" longer wait (like about 10~20 min?), so switch your compiler to msvc+clang(clang-cl) will make it faster
this is just a suggestion, and you need to install both msvc and clang to try it

**Comment by kayhayen** [comment]
Without a reproducer there is nothing I can do. Yes, you can find a better C compiler. Probably random scalability work of Nuitka may eventually make it work. Since this is a commercial project of a non-subscriber to Nuitka commercial I invite you to become one, then you can report the problematic Python file privately to me.

**Comment by kayhayen** [comment]
Closing for lack of feedback

**Comment by Were-Logan-0110** [comment]
> Closing for lack of feedback

I already have my answer thank you so much
