### ISSUE TITLE
Light build

### ISSUE THREAD

**Issue by fantomas-code** [Nuitka/Nuitka#2689]
## How do I compile only what I am going to use in my software? I ask because when I compile my program, many things are included that my program does not even occupy.

**Comment by KevinRodriguez777** [comment]
Use a virtual environment for maximum isolation, if those extra dependencies are still being pulled in, then that means a module or third party library you use needs those dependencies implicitly and as such nuitka will pull them because they’re needed.

**Comment by fantomas-code** [comment]
For example, my application uses these modules and still compiles more modules


import sys
from PySide6.QtUiTools import QUiLoader
from PySide6.QtWidgets import QApplication
from PySide6.QtCore import QFile, QIODevice, Qt


from PySide6.QtWidgets import QMainWindow, QApplication, QMenu, QPushButton
from PySide6.QtCore import QTimer, Qt, QSize
from PySide6.QtGui import QAction, QCursor, QIcon

import ctypes

from src.reloj import Ui_Reloj

from locale import LC_ALL, setlocale
from time import strftime
from shutil import copy
from os import path, getenv, remove
from getpass import getuser
import webbrowser

**Comment by KevinRodriguez777** [comment]
https://code.qt.io/cgit/pyside/pyside-setup.git/tree/requirements.txt
these are pyside6 requirements, so naturally nuitka will pull those dependencies, and then the sub dependencies of those dependencies and so on and so forth.
Pyside6 is a large program and a such it will probably need a lot of things to be compiled.

**Comment by fantomas-code** [comment]
So is it normal that my program weighs so much?

**Comment by KevinRodriguez777** [comment]
With pyside + numpy as dependencies, yes.

**Comment by fantomas-code** [comment]
Thank you at least you clarified my doubt

**Comment by KevinRodriguez777** [comment]
No problem
