### ISSUE TITLE
How do I import modules from a SO file generated by nuitka?

### ISSUE THREAD

**Issue by Vigrond** [Nuitka/Nuitka#269]
I am interested in "Use Case 3".  I am very new to nuitka's concepts, bare with me.

I am trying to use nuitka to "obfuscate" some django sub packages ("apps")

My question is, can I reuse the shared object file generated by nuitka in python?

I have the following (basic example):
```
/api
/api/urls.py
```
```

python3 -m nuitka --module api --include-package=api
python3
>>> import api  (works)
>>> from api import urls
ImportError: cannot import name 'urls'
```

I am also aware of the note in the documentation that says:  

> The recursion into the package directory needs to be provided manually, otherwise the package is empty.

However this is at odds with the --help command:

```
--include-package=PACKAGE
                        Include a whole package. Give as a Python namespace,
                        e.g. ``some_package.sub_package`` and Nuitka will then
                        find it and include it and all the modules found below
                        that disk location in the binary or extension module
                        it creates, and make it available for import by the
                        code.
```

Using `--follow-import-to=api` appears to make no difference

Perhaps I am going about this all wrong, or can be gently reguided.

Thank you for your work.

**Comment by JorjMcKie** [comment]
have you tried `dir(api)` - what does it contain?
I assume, the source version does have `urls`?

I have done the same successfully with e.g. `PySimpleGUI`

**Comment by kayhayen** [comment]
@JorjMcKie Once we asked a question that we want to see a response to, feel free to put it to `needs_example` tag.

The documentation your cite is not wrong, you indeed need to specify the package as the top level module and then say you want to include it. I think you have failed to say @Vigrond what you actually observe to happen, and what the problem would be.

**Comment by Vigrond** [comment]
> have you tried `dir(api)` - what does it contain?

```
>>> import api
>>> dir(api)
['__builtins__', '__cached__', '__compiled__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
>>> api.__path__
['/code/nuitka/api', '/notexist']
>>> api.__file__
'/code/nuitka/api.so'
```
 

> I think you have failed to say @Vigrond what you actually observe to happen, and what the problem would be.

I am making the assumption that submodules will be available after `import api`, so that they may be accessible with `api.urls` for example.  In my api.build directory, it does exist:
```
module.ats.api.urls.c
module.ats.api.urls.os
```
What I am observing is that they appear to not be accessible.  It feels like a very basic problem however I am failing to understand why.  I may be not understanding how SO files work.

In Python you can do something like `from api import urls`.  The `__init__.py` file in the api directory can be empty (no imports) and it still knows how to find `urls`  Perhaps that is why I am unable to access `api.urls` even though it is compiled in `api.build` ?

> The documentation your cite is not wrong, you indeed need to specify the package as the top level module and then say you want to include it.

This interpretation makes sense.  I had read it to mean that you may need to do the recursion yourself.. i.e... `--follow-import-to=api.urls` or something like that.

**Comment by kayhayen** [comment]
@Vigrond This might be a basic Python misunderstanding, but Python does not automatically import submodules.

```
import module
module.module_variable # works
module.sub_module # will not work
```

You have to actually trigger the import for this to work. Only an `import module.sub_module` or with Python3 I think, `from module import sub_module` will work.

If I am getting something wrong, please try and make the minimal reproducer that illustrates what is working with standard Python and not with compiled code.

**Comment by kayhayen** [comment]
Lack of feedback.
