### ISSUE TITLE
Standalone doesn't enforce the files, only `--onefile` currently has no ability to update the contained files

### ISSUE THREAD

**Issue by Mephiiistopheles** [Nuitka/Nuitka#2692]
Standalone doesn't enforce the files, only `--onefile` currently has no ability to update the contained files, but turning it into an archive format is something that is being worked on, but not at highest priority, but it is expected to come into exististance later this year.

_Originally posted by @kayhayen in https://github.com/Nuitka/Nuitka/issues/2691#issuecomment-1927614566_
 

Thank you very much for the above response to the referenced issue.

Just to clarify, if I compile my package with --standalone and --enable-plugin=pyside6, a particularly enthusiastic user who created their own modified version of PySide6 could just directly swap it in by replacing the provided PySide6 subdirectory with their own?

I only ask as the previous exchanges about this seemed to talk about needing to use --no-follow-imports and bundling things separately. This confused me because it looks like PySide wouldn't be statically linked in --standalone mode and therefore be freely swappable by default.

**Comment by kayhayen** [comment]
I never claimed that copying files manually is in any way supported. What a user will be able to do, is to build PySide6 themselves in a matching version, and then they can replace the DLLs if they exist.
