### ISSUE TITLE
Missing `libglib-2.0.so.0` and/or `libpython3.11.so.1.0` when running on non-Python system

### ISSUE THREAD

**Issue by bersbersbers** [Nuitka/Nuitka#2693]
I will update this issue with more of the requested information, <s>but since I have an idea already what's going wrong, maybe that much information isn't even required</s> (not true any more: I am using system Python, so I guess nuitka should include system DLLs - right?). I am building with `nuitka` on some internal GitLab CI running Docker containers. I use the `python:3.11` container for compilation and a non-Python container for testing. Testing fails with error messages such as

> Exception ignored in: 'PySide6-postLoad'
Traceback (most recent call last):
  File "/project/project-v0.1.2/PySide6-postLoad.py", line 21, in <module PySide6-postLoad>
ImportError: libglib-2.0.so.0: cannot open shared object file: No such file or directory

(`standalone`) or 

> ./project-v0.1.2.bin: error while loading shared libraries: libpython3.11.so.1.0: cannot open shared object file: No such file or directory

(`onefile`).

```
$ python -m nuitka --version
2.0.1
Commercial: None
Python: 3.11.7 (main, Feb  1 2024, 05:02:20) [GCC 12.2.0]
Flavor: Unknown
Executable: /usr/local/bin/python
OS: Linux
Arch: x86_64
Distribution: Debian 12
Version C compiler: /usr/bin/gcc (gcc 12).
```

- How did you install Nuitka and Python

`Pulling docker image python:3.11 ...` and `pip install nuitka==2.0.1 PySide6-Essentials=6.6.1`

- Also supply a Short, Self Contained, Correct, Example

This is not easy. I compile on one container and run on another (both Debian-based).

- Provide in your issue the Nuitka options used

`python nuitka.py --standalone/--onefile` with `nuitka.py` like this:

```python
# nuitka-project: --static-libpython=no
# nuitka-project: --enable-plugin=pyside6
# nuitka-project: --nofollow-import-to=tkinter
# nuitka-project: --noinclude-default-mode=error

# nuitka-project: --include-module=pydicom.encoders.gdcm
# nuitka-project: --include-module=pydicom.encoders.pylibjpeg

# nuitka-project-if: {OS} == "Linux":
#   nuitka-project: --output-filename=project.bin
#   nuitka-project: --linux-icon=project/icon/favicon.ico
#   nuitka-project: --noinclude-pytest-mode=allow
#   nuitka-project: --noinclude-unittest-mode=allow
#   nuitka-project: --include-package=_pytest
#   nuitka-project: --include-package=pytestqt
#   nuitka-project: --include-module=PySide6.QtTest
#   nuitka-project: --include-module=pytest_order.plugin
#   nuitka-project: --include-module=project.test_project
#   nuitka-project: --include-data-file=pyproject.toml=./
#   nuitka-project: --include-data-file=conftest.py=./
#   nuitka-project: --include-data-file=project=project/=**/test_*.py
#   nuitka-project: --include-data-dir=example=example
#   nuitka-project: --include-data-dir=test=test
#   nuitka-project: --nofollow-import-to=doctest
#   nuitka-project: --no-deployment-flag=self-execution

# nuitka-project: --assume-yes-for-downloads

# nuitka-project-if: "CI" in os.environ:
#   nuitka-project: --show-progress
#   nuitka-project: --show-memory
#   nuitka-project: --show-scons
#   nuitka-project: --show-modules

```

**Comment by kayhayen** [comment]
There seems to be no code associated with this, the container you are using seems to have an unsupported flavor of Python, I don't think I want or can add support for every containerized Python there is.

For PyPI packages, system DLLs are not included. The glib one seems to be a requirement of the PyPI package of PySide6, programs won't run without a minimal set of dependencies installed.

**Comment by bersbersbers** [comment]
> the container you are using seems to have an unsupported flavor of Python, I don't think I want or can add support for every containerized Python there is

That's surprising - I seem to be using the [`python` "Docker Official Image"s](https://hub.docker.com/_/python). So I had expected if _any_ Docker images would be supported, it must at least be those ones.

If you agree that this Docker image should be supported, I might come up with a small Dockerfile that recreates the problem.

**Comment by kayhayen** [comment]
Much like manylinux images, for which I recently did add some support, what happens with those images is that they are necessarily suitable for all uses and differ in stupid ways. In that case recently, the link libraries needed for embedding Python were just not present, unless you unpack them first.

For creating standalone software, Debian bookwork is like the worst choice to make, for running it, probably yes, but then why use standalone mode, if you run inside an image that already has it all.

The glib issue is one of the target system though. If I am not mistaken, that's not a DLL that you are allowed to bring along and expect to work well with the OS you are bringing it to, it has to come from there.

Building on latest Linux is not recommended for many reasons, not the least being that the Python library compiled for new OS is not going to like older systems a lot. In Nuitka commercial I have a tool to build inside an old container so it works on old systems too: https://nuitka.net/doc/commercial.html which does this automatically. But basically you ought to build on CentOS 7 or very old Debian, but for later I am not entirely sure how good it is I fear not as portable. I don't know when, but eventually `run-inside-nuitka-container` should grow into a solution that allows you to use CentOS 8 for compilation transparently.

**Comment by kayhayen** [comment]
With Debian, you do not have to install recommended packages, which is default, and that will likely make it a lot smaller. Read the docs of apt on that.

Integrating with a Linux desktop, for Qt requires that desktop to be present. If there is no glib, X11 client, wayland libs, that kind of thing, that's kind of hard to do. Bringing those desktop libraries along yourself, you can try it, but your chances of it working are going to vary. Linux standalone is kind of weak, yes, I agree. That's probably why desktops use other OSes usually. You can use flatpaks and what not to deploy your software, but I don't care.

Also popularity of a docker container means nothing to me, if the purpose doesn't align with requirements and purposes of Nuitka. It obviously has one user too few as otherwise that user would contribute the necessary changes to make it work. I am not that user at this time.
