### ISSUE TITLE
Missing OpenGL DLLs on Windows

### ISSUE THREAD

**Issue by BoboTiG** [Nuitka/Nuitka#270]
*  Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)
```shell
c:\> python.exe -m nuitka --version
0.6.2
Python: 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 12:45:02) [MSC v.1900 32 bit (Intel)]
Executable: c:\python36-32\python.exe
OS: Windows
Arch: x86
```

*  How did you install Nuitka and Python?

Installed Python from the official website.

```shell
c:\> python.exe -m pip install nuitka==0.6.2
```

*  If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/).

File **test.py**:
```python
import sys

from PyQt5.QtCore import QUrl
from PyQt5.QtQuick import QQuickView
from PyQt5.QtWidgets import QApplication


app = QApplication([])

view = QQuickView()
view.setResizeMode(QQuickView.SizeRootObjectToView)

engine = view.engine()
engine.quit.connect(app.quit)
context = engine.rootContext()
context.setContextProperty("Value", "Tic!")

view.setSource(QUrl("Main.qml"))
view.show()
sys.exit(app.exec_())
```

File **Main.qml**:
```qml
import QtQuick 2.10
import QtQuick.Controls 2.3
import QtQuick.Layouts 1.3


Rectangle {
    visible: true
    width: 360
    height: 360

    MouseArea {
        anchors.fill: parent
        onClicked: {
            if (textid.text == Value) {
                textid.text = "Tac!";
            } else {
                textid.text = Value;
            }
        }
    }

    Text {
        id: textid
        text: qsTr(Value)
        font.pixelSize: 20
        anchors.centerIn: parent
    }
}
```
Compilation command:
```batch
set options=--standalone --recurse-all
set options=%options% --plugin-enable=qt-plugins=imageformats,qml
set options=%options% --windows-disable-console --assume-yes-for-downloads
set options=%options% --experimental=use_pefile --experimental=use_pefile_recurse --experimental=use_pefile_fullrecurse
python.exe -m nuitka %options% nxdrive
```

* What is ther error?

When building a Qt + QML app, on Windows, the final executable will need additionnal OpenGL DDLs to work. We've done that patch on PyInstaller:  https://github.com/pyinstaller/pyinstaller/blob/1844d69f5aa1d64d3feca912ed1698664a3faf3e/PyInstaller/hooks/hook-PyQt5.py#L39 and https://github.com/pyinstaller/pyinstaller/blob/1844d69f5aa1d64d3feca912ed1698664a3faf3e/PyInstaller/utils/hooks/qt.py#L282-L284.

Those DDLs are not required whith basic Qt apps as far as I can tell.

When manually copying those files into `test.dist` folder, all works fine:
```
c:\python36-32\lib\site-packages\pyqt5\qt\bin\libEGL.dll
c:\python36-32\lib\site-packages\pyqt5\qt\bin\libGLESv2.dll
c:\python36-32\lib\site-packages\pyqt5\qt\bin\d3dcompiler_XX.dll
c:\python36-32\lib\site-packages\pyqt5\qt\bin\opengl32sw.dll
```

**Comment by bearsh** [comment]
@kayhayen using Nuitka v0.6.18.6 with the pyside6 plugin, the file `opengl32sw.dll` is missing (again) in the distribution folder. using something like `--include-data-file=PATH_TO_VENV\Lib\site-packages\PySide6\opengl32sw.dll=.` workarounds the problem.

**Comment by kayhayen** [comment]
The filename you are mentioning there @bearsh was never included. I need to check, but myself PySide6 has other DLL names there to use, current code only considers these: ("libeay32.dll", "ssleay32.dll") and works for PySide2 for me right now.

**Comment by kayhayen** [comment]
Well, that said, the OpenGL libraries are also not found for PySide2, strange. Need to check more.

**Comment by kayhayen** [comment]
Ouch, I looked at SSL names rather than OpenGL.

**Comment by kayhayen** [comment]
Not sure if this ever worked for PySide2 or PySide6 on Windows, I doubt it did. I don't think I have an example that needs it though, but I modified the code and now SSL and OpenGL libraries are found and included. Are you saying it is a regression @bearsh ?

**Comment by kayhayen** [comment]
I should not tolerate reuse of old issues, I think. Anyway, this is it: https://nuitka.net/doc/factory.html going to be part of 0.6.19 which I expect to release soon.

**Comment by bearsh** [comment]
> Are you saying it is a regression @bearsh ?
I don't know as I never had a project depending on webengine before...

anyway, thanks for your fast action!

**Comment by kayhayen** [comment]
Part of the 0.6.19 release I just made.
