### ISSUE TITLE
PySide signal connection doesn't accept keyword argument "slot"

### ISSUE THREAD

**Issue by ForgedCore8** [Nuitka/Nuitka#2704]
- Nuitka version, full Python version, flavor, OS, etc.

2.0.1
Commercial: None
Python: 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\Jake\Downloads\Doki-Doki-Mod-Installer-main\Doki-Doki-Mod-Installer-main\ddmi\scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0).

- How did you install Nuitka and Python

Nuitka installed via pip
Python installed from python.org installer

- pypi version
pip 23.2.1 from C:\Users\Jake\Downloads\Doki-Doki-Mod-Installer-main\Doki-Doki-Mod-Installer-main\ddmi\Lib\site-packages\pip (python 3.11)

PySide6==6.6.1
PySide6-Addons==6.6.1
PySide6-Essentials==6.6.1
shiboken6==6.6.1

[https://github.com/forgedcore8/doki-doki-mod-installer](https://github.com/forgedcore8/doki-doki-mod-installer)

```nuitka --enable-plugin=pyside6 --follow-imports --include-data-dir=./assets=./assets  ddmi.py```

Running the executable yeilds it to not open and immediately end itself. There is no errors that occur.

**Comment by KevinRodriguez777** [comment]
Hi kay, i asked the user over at PyDis to open an issue, when i try to reproduce it myself using factory
`nuitka --remove-output --standalone --run --enable-plugin=pyside6 ddmi.py`

```
Traceback (most recent call last):
  File "C:\Users\Divine\Desktop\PyDis\DDMI~1.DIS\ddmi.py", line 389, in <module>
  File "C:\Users\Divine\Desktop\PyDis\DDMI~1.DIS\ddmi.py", line 42, in __init__
  File "C:\Users\Divine\Desktop\PyDis\DDMI~1.DIS\ddmi.py", line 151, in init_ui
TypeError: patched_connect() got an unexpected keyword argument 'slot'
```
we get this, i think i remember reading that it had been fixed previously, regression maybe?

**Comment by KevinRodriguez777** [comment]
this might've been an premature issue, when i checked what `.connect()` takes
i see this
```py
(method) def connect(
    slot: object,
    type: ConnectionType = ...
) -> Connection
```
so i assumed it was right, and well, i think it should be?
however, once we change the code to 

        self.zip_browse_button.clicked.connect(lambda: self.browse_path(self.zip_entry, False))

        self.game_path_browse_button.clicked.connect(lambda: self.browse_path(self.game_path_entry, True))

        self.auto_button.clicked.connect(lambda: self.auto_toggle())

        self.newdir_checkbox.stateChanged.connect(lambda state: utils.check_changed(state, self))

        self.mod_path_browse_button.clicked.connect(lambda: self.browse_path(self.mod_path_entry, True))

        self.process_button.clicked.connect(lambda: self.on_button_click())

        self.delete_button.clicked.connect(lambda: utils.delete_ddlc(self.game_path_entry.text(), self))
 without the explicit `slot=` argument, it compiles fine.

**Comment by kayhayen** [comment]
The signature of that C backed functions is hard to get by, I went with `receiver` for the argument name. But the evidence there seems to suggest that is indeed to be named `slot` which would make sense. I will try my test cases with explicit keyword arguments and uncompiled, to see if there is version differences, PySide2/PySide6 and within PySide6 itself.

**Comment by kayhayen** [comment]
I was getting this, when I tried it on Windows with 6.6.1 and 6.6.0 uncompiled now:

> TypeError: disconnect() takes no keyword arguments

But I think it takes a `receiver` argument. A recent fix was that it's optional, meaning to disconnect all receivers. 

For connect, I am getting this:

> TypeError: SignalInstance() missing required argument 'slot' (pos 1)

So, the name `receiver` is wrong I guess, not sure where I have it from now.

**Comment by kayhayen** [comment]
Even old PySide6 had that name, I tried 6.3.2 right now, just to see if they changed it.

**Comment by kayhayen** [comment]
Even PySide2 needs that (for which we have almost the same code in place)

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
Part of the 2.0.3 hotfix that I just made.
