### ISSUE TITLE
KeyError: 'NUITKA_PYTHONPATH_AST'

### ISSUE THREAD

**Issue by Redysz** [Nuitka/Nuitka#2705]
When trying to use nuitka I'm getting this error:

```
(venv) C:\git\project>python -m nuitka SystemTest\Tools\gui\gui.py
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\git\project\venv\Lib\site-packages\nuitka\__main__.py", line 172, in <module>
    main()
  File "C:\git\project\venv\Lib\site-packages\nuitka\__main__.py", line 59, in main
    sys.path = [os.environ["NUITKA_PYTHONPATH_AST"]]
                ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'NUITKA_PYTHONPATH_AST'
```
It is happening on normal nuitka version and on development one. Currently installed 2.0.1. Can't use `python -m nuitka --version` (the same error occurs)
```
Windows: 10 64bit
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
```
nuitka installed just with `pip install nuitka`

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."

**Comment by Redysz** [comment]
@kayhayen I can't follow the template what I've written "Can't use python -m nuitka --version (the same error occurs)"

**Comment by kayhayen** [comment]
I understand that much, however I do not know anything about the Python or OS used, except what I guess, which is not enough at all. Even the Nuitka version is to be guessed, not accepting that, esp. as I would have to learn what is special about your setup.

**Comment by Redysz** [comment]
@kayhayen
> I do not know anything about the Python or OS

I've written:
```
Windows: 10 64bit
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
```

> Even the Nuitka version is to be guessed
I've written:
> Currently installed 2.0.1.

Can you tell me why you have to guess the Python, OS or Nuitka version when I have given everything?
This is exactly what template says to attach:
> Nuitka version, full Python version, flavor, OS

**Comment by kayhayen** [comment]
Because there are many flavors of Python, to you 3.11 might be the version, to Nuitka it is not like that. The `--version` command recognized them, but lacking that, I need to know what you installed there, and virtualenv it is, etc. but if you are not familiar with these things, I will wait for somebody who is to report the issue, if it's happening to anybody else anyway.
