### ISSUE TITLE
ModuleNotFoundError: No module named 'zaber_motion_bindings_windows'

### ISSUE THREAD

**Issue by 01baftb** [Nuitka/Nuitka#2712]
I get the following error after running my application that was compiled using Nuitka.  The issue is related to when I import [zaber_motion ](https://pypi.org/project/zaber-motion/) module. 

```
Traceback (most recent call last):
  File "C:\Users\abcd\build\ZABER_~1.DIS\zaber_import_issue.py", line 1, in <module>
  File "C:\Users\abcd\build\ZABER_~1.DIS\zaber_motion\__init__.py", line 6, in <module zaber_motion>
  File "C:\Users\abcd\build\ZABER_~1.DIS\zaber_motion\library.py", line 4, in <module zaber_motion.library>
  File "C:\Users\abcd\build\ZABER_~1.DIS\zaber_motion\call.py", line 12, in <module zaber_motion.call>
  File "C:\Users\abcd\build\ZABER_~1.DIS\zaber_motion\bindings.py", line 39, in <module zaber_motion.bindings>
  File "C:\Users\abcd\build\ZABER_~1.DIS\zaber_motion\bindings.py", line 30, in _load_library
  File "importlib.py", line 126, in import_module
ModuleNotFoundError: No module named 'zaber_motion_bindings_windows'
```

Sample code: 
```python 
from zaber_motion.ascii import Connection
print("Loading...")
connection = Connection.open_serial_port(port_name='COM4')
print("Done...")
```

Compiling command: 
```powershell
python -m nuitka --standalone --output-dir=build .\main.py
```

**Comment by kayhayen** [comment]
@KevinRodriguez777 never work on it, without knowing the `--version` output. Can you provide that @01baftb ?

**Comment by 01baftb** [comment]
> @KevinRodriguez777 never work on it, without knowing the `--version` output. Can you provide that @01baftb ?

Sorry forgot to mention the version. 

```
zaber-motion                  4.7.0
zaber-motion-bindings-windows 4.7.0
```

```
PS C:\Users\abcd\some_example_path_a> python -m nuitka --version                                                                              
1.9.3
Commercial: None
Python: 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\temp_python_venv\some_example_path_b\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

**Comment by KevinRodriguez777** [comment]
> > @KevinRodriguez777 never work on it, without knowing the `--version` output. Can you provide that @01baftb ?
> 
> Sorry forgot to mention the version.
> 
> ```
> zaber-motion                  4.7.0
> zaber-motion-bindings-windows 4.7.0
> ```
> 
> ```
> PS C:\Users\abcd\some_example_path_a> python -m nuitka --version                                                                              
> 1.9.3
> Commercial: None
> Python: 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]
> Flavor: CPython Official
> Executable: C:\temp_python_venv\some_example_path_b\Scripts\python.exe
> OS: Windows
> Arch: x86_64
> WindowsRelease: 10
> ```
Thanks for the report, this will be fixed in the next release of nuitka.

**Comment by 01baftb** [comment]
Thank you. Is there a temporary method to address this issue using the .yaml file as you suggested in a previous issue https://github.com/Nuitka/Nuitka/issues/2598#issuecomment-1846725297 I reported?

**Comment by KevinRodriguez777** [comment]
> Thank you. Is there a temporary method to address this issue using the .yaml file as you suggested in a previous issue [#2598 (comment)](https://github.com/Nuitka/Nuitka/issues/2598#issuecomment-1846725297) I reported?

absolutely, here's the yaml
```yaml
- module-name: "zaber_motion"
  implicit-imports:
    - depends:
        - "zaber_motion_bindings_windows"

- module-name: "zaber_motion_bindings_windows"
  dlls:
    - from_filenames:
        prefixes:
          - "zaber-motion-lib"```

**Comment by kayhayen** [comment]
@KevinRodriguez777 is that yaml all it takes, I would put it up for 2.0.3 inclusion then, it looks though as if it there might be a "when: win32" warranted.

And just generally speaking, for triage team rationale, once you see a report against non-latest Nuitka, 1.9 here, always ask for a retest with the current stable release by the reporting user first. Always there is a chance that new Nuitka solved whatever caused an import to be implicit dependency. And second, at least I found this myself to be useful. It's good to see a response from a reporter, more than once what happens is that working on an issue, and encountering clarification needs, it turns out that the reporter is not following up, making the report impossible to work on, and then it wasted my time. So a kind of initial roundtrip with a quick confirmation like "yup, 2.0.2 is the same" is a sign of life that is valuable in itself even if unlikely to be happening otherwise. But e.g. coming 2.1 I wouldn't be as sure anymore, if that wouldn't catch more stuff than 2.0 now.

**Comment by 01baftb** [comment]
> > Thank you. Is there a temporary method to address this issue using the .yaml file as you suggested in a previous issue [#2598 (comment)](https://github.com/Nuitka/Nuitka/issues/2598#issuecomment-1846725297) I reported?
> 
> absolutely, here's the yaml
> 
> ```yaml
> - module-name: "zaber_motion"
>   implicit-imports:
>     - depends:
>         - "zaber_motion_bindings_windows"
> 
> - module-name: "zaber_motion_bindings_windows"
>   dlls:
>     - from_filenames:
>         prefixes:
>           - "zaber-motion-lib"```
> ```

The build config yaml file resolved the issue for Nuitka v1.9.3.  I upgraded to Nuitka v2.0.2 and the compiled .exe file had the same reported issue if I did NOT use the build config yaml file. However, if I used the build config yaml file on v2.0.2 then the issue is resolved.

**Comment by kayhayen** [comment]
Thanks for reporting @01baftb , I am going to add it for 2.0.3 with a "win32" limitation on those bindings.

**Comment by kayhayen** [comment]
I added linux and macos myself @KevinRodriguez777 as they are extremely similar, that was easy after you figured it out, credited the commit to you.

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
This is part of the 2.0.3 release I just made.

**Comment by 01baftb** [comment]
@kayhayen @KevinRodriguez777 Sorry to reopen the issue. I upgraded the [zaber_motion ](https://pypi.org/project/zaber-motion/ )module from 4.7.0 to 5.1.2 and now I am running into errors again. I used the build config yaml file that was previously mentioned. 

```
Traceback (most recent call last):
  File "C:\Users\abcd\build\zaber_motion\__init__.py", line 6, in <module zaber_motion>
  File "C:\Users\abcd\build\zaber_motion\library.py", line 4, in <module zaber_motion.library>
  File "C:\Users\abcd\build\zaber_motion\call.py", line 12, in <module zaber_motion.call>
  File "C:\Users\abcd\build\zaber_motion\bindings.py", line 39, in <module zaber_motion.bindings>
  File "C:\Users\abcd\build\zaber_motion\bindings.py", line 35, in _load_library
ImportError: Could not find library zaber-motion-lib-windows-amd64.dll in bindings. Please contact Zaber support.
```

**Comment by 01baftb** [comment]
An update to my previous comment. I was able to resolve the issue by using the build config yaml file with the contents below. However, I am unsure if this is the appropriate approach. Please confirm. 

```yaml
- module-name: "zaber_motion"
  implicit-imports:
    - depends:
        - "bindings"

- module-name: "bindings"
  dlls:
    - from_filenames:
        prefixes:
          - "zaber-motion-lib"
```

**Comment by kayhayen** [comment]
The correct approach is to use stable Nuitka and make a new report.

**Comment by kayhayen** [comment]
So @KevinRodriguez777 informed me that they indeed at a top level module names `bindings` in a minor release. I was using 5.1.1 last week when doing the hotfix, and 5.1.2 is this. For a proper solution of that new issue you will be creating please, a version check of `zaber_motion` should be added, and hopefully the recognize that you cannot just put that kind of package name up one day.
