### ISSUE TITLE
Beginner's question: How to accelerate repeated standalone packaging and compilation

### ISSUE THREAD

**Issue by monkeycc** [Nuitka/Nuitka#2717]
`python -m nuitka    --standalone  --show-progress --plugin-enable=tk-inter  --include-data-dir=config=config  main.py`

Every time it needs to be recompiled
A long time

Sometimes the code is modified
But every time it takes a very long time to recompile
Is there any command that can accelerate
I want to replace main.exe

**Comment by kayhayen** [comment]
Unfortunately no.
