### ISSUE TITLE
How to just convert my code to exe?

### ISSUE THREAD

**Issue by liuzhongshu** [Nuitka/Nuitka#2719]
My code has many 3rd dependencies, the dependencies are very large (numpy,scipy,pytorch,tk...), so I just want to convert my code to exe, then execute on client machine using there virtual Python environment. then I can distribute a small zip to client machine.

How to do that, thanks.

**Comment by KevinRodriguez777** [comment]
have you looked at the documentation? https://nuitka.net/doc/user-manual.html

**Comment by liuzhongshu** [comment]
yes, for example, i have a.py and b.py (a.py use b.py)
If I use  nuitka a.py, then I get a.exe that still need b.py to run.
if I use nuitka --follow-imports a.py, then I get a lot of unwanted 3rd packages in final a.exe.
if I use nuitka --module a.py, I get a compiled pyd file, not exe.

maybe i missed something.

**Comment by KevinRodriguez777** [comment]
the documentation states:
```The created binaries can be made executable independent of the Python installation, with --standalone and --onefile options.```
this is what you're missing.

**Comment by liuzhongshu** [comment]
but I don't want an independent exe, it will be very large, because I use many 3rd packages.  I just need an exe include only a.py + b.py (that's my code), so can distribute a very small file to client machine, the client machine has already install a python environment.

**Comment by kayhayen** [comment]
@liuzhongshu Use this https://nuitka.net/doc/user-manual.html#use-case-5-setuptools-wheels mode, you create a wheel of your Python code, that can be installed into a Python, then use Nuitka to create compiled ones of it, they install with `pip` just fine and contain a runner and your code as a package compiled.

**Comment by liuzhongshu** [comment]
I find --include-module is more suitable for my case, any way, thanks very much

**Comment by kayhayen** [comment]
The only way of creating portable binaries is when using `--module` or `--standalone`, including modules into an accelerated executable and then running it elsewhere will sometimes appear to work, but is in no way considered supported. Good luck.
