### ISSUE TITLE
Action does not support nuitka-project comments in source

### ISSUE THREAD

**Issue by linuxdaemon** [Nuitka/Nuitka#2722]
This seems to be a regression from 0.6 -> 1.x as the cli format was changed.

In Nuitka, it seems the pre-parsing of cli args is only looking for positional file names and the --main= argument, not --script-name=:

https://github.com/Nuitka/Nuitka/blob/7265989dffad17c2d3c4c71308ce097025306606/nuitka/OptionParsing.py#L2023-L2051

The action used to pass the value of the `script-name` field as a positional argument until v1.0 when it switched to passing it via the github actions env var. It looks like the `nuitka-project` comment parsing is also done before github action cli args are loaded, so renaming the key in the json may not work without reordering the parsing.

For replication, here is the current commit with my actions config: https://github.com/TotallyNotRobots/describealign/tree/3696d33b3790754521f029e128f9cba1c6049378

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by linuxdaemon** [comment]
This worked perfectly in my case, didn't need to change anything except setting the version to `factory`. Thanks!

**Comment by kayhayen** [comment]
This is part of the hotfix release 2.0.4 that I just made.
