### ISSUE TITLE
Feature Request - Docker utilities to build cross platform

### ISSUE THREAD

**Issue by zackees** [Nuitka/Nuitka#2723]
This is a feature request.

I was able to get a dockerfile defined that allows me to compile an app from the command line from linux/windows/mac to linux.

I've wrapped this up a python package:
github.com/zackees/python-compile

And it works like this:
```bash
python-compile --os debian --input demo_http_server.py --requirements requirements.txt
```

It would be awesome if other platforms could be supported as well. I have a work in progress for the windows dockerfile that uses linux with a cross compiler toolchain. But I'm giving up on that for now.

In theory it's possible to build windows and macos from any system that supports docker.

**Comment by kayhayen** [comment]
This already exists, sort of, check out `run-nuitka-inside-container`. It's not overly documented, and the container files are not really there, but I intend to rebase the commercial container offering that is part of Nuitka commercial on top of it, that's then CentOS7 and Python3.11, and make a free one based on CentOS8 available too. But right now, compiling inside of a container is easy, defaults to podman, but I occasionally also used docker with it.

**Comment by zackees** [comment]
Where is `run-nuitka-inside-container` located? I grepped for it in the repo but didn't find any matches.

> So, with a bit of work from your side, it already is there

Work I've already done, or work that I should contribute?

**Comment by kayhayen** [comment]
There is `bin/run-inside-nuitka-container` though, spelling mixed up.

For container files it can only use this:

```
./nuitka/tools/podman/containers/CI.containerfile
./nuitka/tools/podman/containers/Python-Minor-Versions.containerfile
```

I have this in my private repo, unpublished, not sure how good it is:

```
ARG CENTOS_VERSION
FROM centos:8
ENV container docker
USER root

RUN cd /etc/yum.repos.d/ && sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
RUN dnf install -y epel-release \
    && dnf repolist \
    && dnf install -y gcc strace patchelf ccache gdb make python3-devel python3-zstandard python3-ordered-set \
    && dnf clean -y all

VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/sbin/init"]
```

I think I have used that to test CentOS 8 with Nuitka, but for good compilation, you need to wrap commands with e.g. `scl enable devtoolset-9` or something. Depending on how good you are at containers, you will be able to run from your checkout inside a container and get the output no problem.

But to make it all smooth, i really need to merge this and my commercial container stuff, which is sort of smooth, but not flexible at all, with this very flexible thing, but that will take time. But the tool has the capability. 

I got a bunch of container files privately, not sure how to manage that.

```
CI.containerfile           Fedora32.containerfile.in        ManyLinux2014_x86_64.containerfile
CentOS7.containerfile      Fedora33.containerfile.in        MuslLinux.containerfile
CentOS8.containerfile      Fedora34.containerfile.in        Python-Minor-Versions.containerfile
Debian.containerfile       Fedora35.containerfile.in        Ubuntu1604.containerfile
Fedora.containerfile       Fedora36.containerfile.in        Ubuntu1804.containerfile
Fedora30.containerfile.in  Fedora37.containerfile.in        Windows-isolated.containerfile
Fedora31.containerfile.in  Linux-isolated.containerfile.in
```

I definitely want some of those for testing native Pythons, one is for CI usage, and others are for debugging, or just running code and pip installs in a secure fashion, with no network, isolated, etc.


I guess, you either help yourself or wait until I get around to finishing it.

**Comment by zackees** [comment]
Looks like your work in progress is missing the mingw64 toolchain:

```
RUN dnf -y install \
    bison \
    cmake \
    findutils \
    wine \
    python3-pip \
    flex \
    git \
    make \
    mingw64-boost \
    mingw64-gcc \
    mingw64-gcc-c++ \
    mingw64-libxml2 \
    mingw64-qt5-qtbase-devel \
    mingw64-qt5-qtsvg \
    mingw64-qt5-qttools-tools \
    procps-ng \
    ragel \
  && dnf clean all
  ```

**Comment by zackees** [comment]
That was the instructions I was following for a cross compiler toolchain from this [link](https://www.reddit.com/r/learnpython/comments/w1basa/comment/jg9ckvn/?utm_source=share&utm_medium=web2x&context=3). It may not be necessary.

The part that I'm getting stuck on is the following and I was wondering if you know the answer to this:

```
RUN curl https://github.com/zackees/python3.10/raw/main/win/python-3.10.10-amd64.exe -o python_installer.exe

RUN wine python_installer.exe  <--- this does not work
```

**Comment by zackees** [comment]
Never mind I switched to one of the python 3.11 downloads and it works fine.

**Comment by kayhayen** [comment]
Cross compilation is not supported with Nuitka, your instructions must be arbitrarily bad, forgive me for not reading or supporting them. I am sure wine can be made to work, but I would use the downloaded MinGW64 of Nuitka there. But I am not your "how to install python in wine" support, the CPython or wine project may do that. I am sure about the ability of Nuitka wine to produce standalone binaries. I might get interested in supporting that one day, but that day hasn't come yet.

Maybe you want to be using Nuitka-Action on GitHub instead, that's an easier way to compile for all 3 platforms without having them.

That said, I understood cross platform in this context to mean building for Linux on Windows on macOS hosts, not the other way around. So in that sense, what I am doing is not interesting to you. What I want to make is the ability to compile for Linux on CentOS 8 while using Fedora 50 or Windows 12. 

For Windows as a target, I do not care as much. If somebody were to contribute enough to Nuitka to make wine work one day, I would take it. It's not really cross platform in my book. But I am also not sure how well their DLLs work on actual Windows, and what kind of C runtime will make things work there.

**Comment by kayhayen** [comment]
Not sure what to do with this issue then, the docker/podman side of things, I will want to work on, but the wine part is actually entire unrelated to that, and maybe should be a separate issue, and probably already is.

**Comment by kayhayen** [comment]
Yeah, since I track the container stuff as part of my commercial roadmap anyway, let me close this issue and point you to what was being said there: https://github.com/Nuitka/Nuitka/issues/43#issuecomment-395030271 as that still stands.
