### ISSUE TITLE
Cross-target build on Mac OS x86_64 for arm64 failed with 'assert finding != "not-found"'

### ISSUE THREAD

**Issue by ioctl-user** [Nuitka/Nuitka#2724]
I am running Mac OS 13 x86_64, python 3.11 installed via brew, Nuitka installed via pip3.11

> python3 -m nuitka --version

```
2.0.3
Commercial: None
Python: 3.11.7 (main, Dec  4 2023, 18:10:11) [Clang 15.0.0 (clang-1500.1.0.2.5)]
Flavor: Homebrew Python
Executable: /usr/local/Cellar/python@3.11/3.11.7_1/bin/python3.11
OS: Darwin
Arch: x86_64
Version C compiler: /usr/bin/clang (clang 15.0.0).

```
 
> cat 1.py
```
print("Hello")
```

> python3 -m nuitka --macos-target-arch=arm64 --standalone --follow-imports 1.py
```
Nuitka-Options: Used command line options: --macos-target-arch=arm64
Nuitka-Options: --standalone --follow-imports 1.py
Nuitka-Options: Following all imports is the default for standalone mode and
Nuitka-Options: need not be specified.
Nuitka: Starting Python compilation with Nuitka '2.0.3' on Python '3.11'
Nuitka: commercial grade 'not installed'.
Nuitka-Reports: Compilation report written to file 'nuitka-crash-report.xml'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/nuitka/__main__.py", line 175, in <module>
    main()
  File "/usr/local/lib/python3.11/site-packages/nuitka/__main__.py", line 161, in main
    MainControl.main()
  File "/usr/local/lib/python3.11/site-packages/nuitka/MainControl.py", line 1131, in main
    _main()
  File "/usr/local/lib/python3.11/site-packages/nuitka/MainControl.py", line 980, in _main
    main_module = _createMainModule()
                  ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nuitka/MainControl.py", line 156, in _createMainModule
    main_module = buildMainModuleTree(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nuitka/tree/Building.py", line 1222, in buildMainModuleTree
    module.setStandardLibraryModules(
  File "/usr/local/lib/python3.11/site-packages/nuitka/nodes/ModuleNodes.py", line 957, in setStandardLibraryModules
    assert finding != "not-found"
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError
Nuitka-Reports: Compilation crash report written to file
Nuitka-Reports: 'nuitka-crash-report.xml'. Please include it in your bug report.
```

Cannot paste good formatted crash report, so will attach it as txt file.
[nuitka-crash-report.txt](https://github.com/Nuitka/Nuitka/files/14378155/nuitka-crash-report.txt)

**Comment by kayhayen** [comment]
This might be related to this being cross target. Where Nuitka detects the modules to locate and include for technical needs, it does expect them to be locatable, but apparently they are not.

I changed factory to tell us the trouble maker.

Thanks for your report, this enhanced for debugging on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

The report is not useful at that stage. The assertion now will contain a module name. We might be able to conclude from that.

You might be misguided to think that a non-universal build of Python can be made to target another arch. The way these options work, is that a universal Python build like the one from CPython can strip itself down to only the given arch. Nuitka has no way of making your x86_64 Python binary parts run on arm64 by itself.

**Comment by ioctl-user** [comment]
Tried the same with the factory version:

```
Nuitka-Options: Used command line options: --macos-target-arch=arm64
Nuitka-Options: --standalone 1.py
Nuitka: Starting Python compilation with Nuitka '2.1rc4' on Python '3.11'
Nuitka: commercial grade 'not installed'.
Traceback (most recent call last):
  File "/Users/build/Library/Python/3.11/lib/python/site-packages/nuitka/__main__.py", line 175, in <module>
    main()
  File "/Users/build/Library/Python/3.11/lib/python/site-packages/nuitka/__main__.py", line 161, in main
    MainControl.main()
  File "/Users/build/Library/Python/3.11/lib/python/site-packages/nuitka/MainControl.py", line 1141, in main
    _main()
  File "/Users/build/Library/Python/3.11/lib/python/site-packages/nuitka/MainControl.py", line 984, in _main
    main_module = _createMainModule()
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/build/Library/Python/3.11/lib/python/site-packages/nuitka/MainControl.py", line 160, in _createMainModule
    main_module = buildMainModuleTree(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/Users/build/Library/Python/3.11/lib/python/site-packages/nuitka/tree/Building.py", line 1222, in buildMainModuleTree
    module.setStandardLibraryModules(
  File "/Users/build/Library/Python/3.11/lib/python/site-packages/nuitka/nodes/ModuleNodes.py", line 965, in setStandardLibraryModules
    assert finding != "not-found", early_module_name
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError: _codecs_cn
Nuitka-Reports: Compilation crash report written to file
Nuitka-Reports: 'nuitka-crash-report.xml'. Please include it in your bug report.
```

Seems, the only word `_codecs_cn` is added.

Could you give advice and/or update program output with link to the guide how to prepare cross-target environment for the MacOS? I've tried using compile.py script from this [issue](https://github.com/Nuitka/Nuitka/issues/2469) but didn't succeed.

**Comment by kayhayen** [comment]
I think, when locating extension modules, Nuitka checks the architecture.

In your case, maybe this doesn't work out:

```
    if (
        found_candidate.module_type == "C_EXTENSION"
        and isMacOS()
        and not hasUniversalOrMatchingMacOSArchitecture(found_candidate.full_path)
    ):
        # Not usable for target architecture.
        raise ImportError
```

You either need an arm64 Python to run this, and a Universal build of Python. If you only have a x86_64 machine, download CPython, but I think, what this means, is that your configuration is unsupported. Nuitka cannot really cross compile, esp. not as it at the end of the day, it's going to need arm64 binaries, and you don't have them there.

I guess, what I can do is to error out on this sooner. I am not sure though, how to detect universal vs. non-universal Python binaries.

**Comment by kayhayen** [comment]
These forms of unsupported cross platform builds are now detected. Only universal Python versions are allowed to do it, they can running any arch produce a build for the other version, and it now errors out properly in your configuration.

**Comment by kayhayen** [comment]
This is part of the current pre-release, closing it for lack of general relevance, this is only a better error message for an unsupported configuration after all.

**Comment by ioctl-user** [comment]
Sorry, for writing to the closed issue.

With the factory version and without universal2 python binaries I have the following message:

```
FATAL: Cannot cross compile from non-universal macOS binaries.
```

Looks a little-bit confusing on the outside. May I suggest this one:

```
FATAL: Cannot cross compile using non-universal python binaries for MacOS. Please install universal python package.
```

**Comment by kayhayen** [comment]
I am keeping them unlocked for precisely this sort of comment for you to make. Thanks for actually trying it out even though you personally stood very little to gain from it. I am taking this on. I think I will also add a bit of how to get it.

**Comment by kayhayen** [comment]
```
                Tracing.options_logger.sysexit(
                    """\
Cannot cross compile to other arch, using non-universal python binaries \
for macOS. Please install the "universal" python package as offered on \
the Python download page."""
                )
```

**Comment by kayhayen** [comment]
Part of the 2.2 release I just made.
