### ISSUE TITLE
`use_last_error` Keyword giving TypeError for CDLL call

### ISSUE THREAD

**Issue by WyattBreitner** [Nuitka/Nuitka#2729]
- `python3 -m nuitka --version`:
```
2.0.5
Commercial: None
Python: 3.11.8 (main, Feb  7 2024, 00:00:00) [GCC 13.2.1 20231205 (Red Hat 13.2.1-6)]
Flavor: Fedora Python
Executable: /home/wyatt/Documents/NuitkaTest/.venv/bin/python3
OS: Linux
Arch: x86_64
Distribution: Fedora 39
Version C compiler: /usr/lib64/ccache/gcc (gcc 13).
```
- Nuitka is installed in a venv using pip
- Reproducible Example:
```
from ctypes import CDLL as _cdll

lib = _cdll("/usr/lib64/libc.so.6", use_errno=True, use_last_error=True)
``` 
- `python3 -m nuitka main.py --standalone`
- `./main.dist/main.bin`
```
Traceback (most recent call last):
  File "/home/wyatt/Documents/NuitkaTest/main.dist/main.py", line 3, in <module>
TypeError: 'use_last_error' is an invalid keyword argument for ctypes.CDLL()
```
This error does not happen if main.py is run without being compiled

**Comment by kayhayen** [comment]
Ok, need to figure out when that got added, we optimize CDLL calls in hope to one day statically optimize them into knowing that DLLs get loaded manually by the Python code.

**Comment by kayhayen** [comment]
It seems, `use_last_error` was already present in Python 2.6, so this is like a long standing oversight.

**Comment by kayhayen** [comment]
It seems the core of the fix is this:

-        "use_lasterror",
+        "use_last_error",

That argument name has had a typo in it, so trivial fix, just that it exists twice, once for pre-3.8 and post-3.8 due to `winmode` being added.

**Comment by kayhayen** [comment]
This is part of the 2.1.1 hotfix release I made
