### ISSUE TITLE
Solved. Windows, local directory and system package confusion.

### ISSUE THREAD

**Issue by ioctl-user** [Nuitka/Nuitka#2734]
Nuitka is running on the Windows 10 in VirtualBox.
Python installed from the official site, nuitka installed via pip.

> python -m nuitka --version
```
2.0.5
Commercial: None
Python: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Program Files\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0).
```

I have two files:
> cat main.py
```
from lib.locale.bar import bar

bar()
```

> cat lib\locale\bar.py
```
def bar():
        print("Hi")
```

Build command:
```
python.exe -m nuitka --standalone --report=report.txt --onefile .\main.py
```

When running with python "Hi" is printed, when running built version for MacOS and Linux, it's printed also. But windows built version gives an error.

> .\main.exe
```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\OND049~1\main.py", line 1, in <module>
    from lib.locale.bar import bar

ModuleNotFoundError: No module named 'lib.locale.bar'; 'lib.locale' is not a package
```

Report file is attached.
[report.txt](https://github.com/Nuitka/Nuitka/files/14448387/report.txt)

Seems, the problem in the "locale" directory name. Looks like Nuitka confuses it with some system module.

However, python interpreter doesn't gives this error. So, it may be Nuitka problem.

**Comment by KevinRodriguez777** [comment]
this isn't a nuitka thing but more of a python problem, you'll need an empty init file within locale, next to bar.py

**Comment by ioctl-user** [comment]
This fixes the issue.

Thanks for additional explanation!
