### ISSUE TITLE
Nuitka Multidist option not working

### ISSUE THREAD

**Issue by cpythonist** [Nuitka/Nuitka#2737]
I'm writing a Python program with six scripts, three of which need to be compiled into separate executable files.
`main.py`, `updater.py` and `installer.py` need to be compiled to three individual executable files in the same directory.
All six scripts lie in the main branch.

```
E:
|-----prog
      |-----base.py
      |-----globalNamespace.py
      |-----installer.py
      |-----printStrings.py
      |-----second4.py
      |-----settings.dat
      |-----updater.py
```

I saw the documentation and saw option for `Multidist` with the `--main` option. I did the command like this:

`python -m nuitka --standalone --follow-imports --mingw64 --warn-unusual-code --windows-icon-from-ico=icon.ico --company-name="SomeCompany" --product-name="aName" --file-version=1.0.0.0 --product-version=4.0 --file-description="aDescription" --copyright="Apache-2.0" --include-data-files=settings.dat=. --main=main.py --main=updater.py --main=installer.py`

But this produces only one executable `main.exe` in `main.dist`. And when I try to run it, it gives the following traceback is obtained:
```
Traceback (most recent call last):
  File "E:\prog\main.dist\main.py", line 90, in <module multidist-1-main>
  File "E:\prog\main.dist\subprocess.py", line 1026, in __init__
  File "E:\prog\main.dist\subprocess.py", line 1538, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
Line 90 is where I have run `updater.py` from `main.py`.
I have used `subprocess.Popen()` to call `updater.py` from `main.py` AND `updater.py` calls `installer.py` using the same function.

I tried different approaches like to maybe to import the files hoping Nuitka would compile them too, but with no success.
No help is available on the Internet for this (every question asks about compiling to a single file).

Nuitka details:
```
1.9.2
Commercial: None
Python: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\<user>\AppData\Local\Programs\Python\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10 (Actually 11)
Nuitka-Scons:INFO: For Python version 3.11 MSVC 14.3 or later is required, not 14.2 which is too old.
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0).
```

**Comment by kayhayen** [comment]
Your report is against a relatively old version and you didn't provide the code necessary, but it indeed seems unnecessary. Launching compiled files is not foreseen like that. You need to copy/symlink/rename it to `installer.exe` and it will execute that. There is no transparent recognition where the main arguments live relative to each other.

At this time, the links, batch files, etc. to do it, the code that decides what to run, works like this:

```
    source_code = renderTemplateFromString(
        r"""
import sys, re, os
main_basename = re.sub(r'(.pyw?|\.exe|\.bin)?$', '', os.path.normcase(os.path.basename(sys.argv[0])))
{% for main_module_name, main_basename in zip(main_module_names, main_basenames) %}
if main_basename == "{{main_basename}}":
    __import__("{{main_module_name.asString()}}")
    sys.exit(0)
{% endfor %}

sys.exit("Error, failed to detect what to do for filename derived name '%s'." % main_basename)
""",
        main_module_names=main_module_names,
        main_basenames=main_basenames,
        zip=zip,
    )
```

With competent usage of subprocess, you can achieve that `sys.argv[0]` is under your control when calling subprocess. For Windows, we really didn't decide yet what kind of invocation will be best, as symlinks cannot be put into any kind of archives on Windows really, but if you read the user manual, that would have been known to you, that you are on your own there. There are issues seeking for help with making this more of a ready made solution that has several options to choose from for launcher creation, but not at this time, and it's not me going to create this (now).
