### ISSUE TITLE
exec import problem

### ISSUE THREAD

**Issue by JustRedTTG** [Nuitka/Nuitka#2743]
- How did you install Nuitka and Python

> nuitka github action
> it's python 3.11

- Also supply a Short, Self Contained, Correct, Example

> Should work and import correctly within exec environment

- Provide in your issue the Nuitka options used

> `standalone`

The error
`
C:\Users\Lenovo\Nextcloud\Downloads\rpg demo standalone>main.exe
Traceback (most recent call last):
File "C:\Users\Lenovo\NEXTCL~1\DOWNLO~1\RPGDEM~1\engine\protected_extension_loader.py", line 49, in load
File "<string>", line 5, in <module>
ModuleNotFoundError: No module named 'engine.npcs.enemies' 
`

I'm not sure if it's a pathing error or not, but my onefile also has a error trying to find it's files

**Comment by KevinRodriguez777** [comment]
>It's Also supply a Short, Self Contained, Correct, Example

this means you need to include an minimal reprucible example of the error. without one, impossible to help.

**Comment by JustRedTTG** [comment]
> > It's Also supply a Short, Self Contained, Correct, Example
> 
> this means you need to include an minimal reprucible example of the error. without one, impossible to help.

have second.py file for testing
have main.py file
exec("import second", locals(), globals())

**Comment by KevinRodriguez777** [comment]
that doesn't track with
`engine\protected_extension_loader`
`ModuleNotFoundError: No module named 'engine.npcs.enemies'`

if you can't provide an accurate reproducible example

>   That demonstrates the issue i.e a small piece of code which reproduces the issue and can be run
>   with out any other (or as few as possible) external dependencies. Issues without this may will
>   likely be rejected without much consideration. Often this can be as simple as importing a package,
>   if this is a packaging issue, try that first.

without one we can't, and might not even be willing to help

**Comment by KevinRodriguez777** [comment]
the code you provided does not even include an import to engine, which is what's causing the issue. open a new issue and this time read the issues guidelines.

**Comment by JustRedTTG** [comment]
> the code you provided does not even include an import to engine, which is what's causing the issue. open a new issue and this time read the issues guidelines.

engine is a __init__ module folder with sub items, relative import should work within exec too

**Comment by KevinRodriguez777** [comment]
the example you provided *works* when compiled with Nuitka.

**Comment by JustRedTTG** [comment]
> the example you provided *works* when compiled with Nuitka.

I'll provide an example where it breaks tmr
