### ISSUE TITLE
error while compiling selenium chromedriver or something?? check it on picture

### ISSUE THREAD

**Issue by BAYU-SPAMMING** [Nuitka/Nuitka#2747]
### Python: 3.9.8 (tags/v3.9.8:bb3fdcf, Nov  5 2021, 20:48:33) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\PC\AppData\Local\Programs\Python\Python39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

_**This is an error when I want to compile using nuitka and use the selenium chromedriver module in python.**_

THE ERROR : 
![Screenshot 2024-03-06 175758](https://github.com/Nuitka/Nuitka/assets/69312755/bb8df77e-5ac8-41f1-b97c-229cd88db233)

I've used such as :
**nuitka --standalone --include-package-data=selenium Main.py**

**but he still raises an error 
any solution?
#want to ask :)**

**Comment by BAYU-SPAMMING** [comment]
@kayhayen any solution??

**Comment by Diegocndd** [comment]
same bug in https://github.com/Nuitka/Nuitka/issues/2746

**Comment by KevinRodriguez777** [comment]
this is a duplicate #2746, please follow that issue instead.

**Comment by BAYU-SPAMMING** [comment]
> same bug in #2746

is there any solution??
