### ISSUE TITLE
Mac zig build using “Apple” in target

### ISSUE THREAD

**Issue by jimkring** [Nuitka/Nuitka#2756]
I've gotten `zig cc` working pretty well on x86 linux.  So, I set up a matrix to test on Windows and MacOS.  Here is an error on a `macos-latest` github runner:
https://github.com/jimkring/nuitka-zig-cc/actions/runs/8197801740/job/22420319448#step:5:89
`error: unable to parse target query 'x86_64-apple-macos11.7': UnknownOperatingSystem`

I believe the target should be just 'x86_64-macos11.7‘ without the ‘apple’

There is a macOS build with gcc on that worked fine. Just the macos build with zig cc failed: https://github.com/jimkring/nuitka-zig-cc/actions/runs/8199925407

**Comment by kayhayen** [comment]
I changed that on factory, and will even put it out for the hotfix. I am closing this one early for lack of general relevance.

**Comment by kayhayen** [comment]
This is part of the 2.1.1 hotfix release I made
