### ISSUE TITLE
Bootstrap triggers virus total on signed executable

### ISSUE THREAD

**Issue by JustRedTTG** [Nuitka/Nuitka#2757]
I have a signed executable made with nuitka and I uploaded it to virus total, the bootstrap seems to get detected. Can the bootstrap be compiled manually or something

nuitka from pip
version info:
```
2.0.4
Commercial: None
Python: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] 
Flavor: CPython Official
Executable: C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\ProgramData\mingw64\mingw64\bin\gcc.exe (gcc 13.2.0).
```

![image](https://github.com/Nuitka/Nuitka/assets/46073266/dca831d5-954d-4859-9776-018af031f6a2)

https://www.virustotal.com/gui/file/6eb1d49c8a9d0196e6f4810a63c09b8ef65e56b83aca7d571eb5566d15850634

I've also contacted the anti-virus provider for false positive

**Comment by kayhayen** [comment]
One is pretty good, but as described in the docs, the steps necessary to reduce it further are available for Nuitka commercial subscribers only.
