### ISSUE TITLE
Long Type integration and Unicode Type Integration to support Python 3.12

### ISSUE THREAD

**Issue by quaesitor-scientiam** [Nuitka/Nuitka#2760]
Co-authored-by: Richard Wheeler <richard_wheeler@rjew.info>

* Python 3.12 support

3.12 has this now:

```
typedef struct _PyLongValue {
    uintptr_t lv_tag; /* Number of digits, sign and flags */
    digit ob_digit[1];
} _PyLongValue;

struct _longobject {
    PyObject_HEAD
    _PyLongValue long_value;
};
```
Used to be defined as::

```
struct _longobject {
    PyObject_VAR_HEAD
    digit ob_digit[1];
};

```
-------------

Generic object type for a variable size container

         PyObject_VAR_HEAD vs PyObject_HEAD

So, if PyObject *a is actually a PyLongObject *a then you know that you can use Py_SIZE to get the amount of digits.

For 3.12, they gave up on that, and now lv_tag encodes not only amount of digits, and sign, but also some "flags".

And we got e.g. Jinja2 template code like this, an excerpt

```
    if (Py_REFCNT({{operand1}}) == 1) {
        digit const *b_digits = {{ right.getLongValueDigitsPointerExpression("operand2") }};
        Py_ssize_t b_digit_count = {{ right.getLongValueDigitCountExpression("operand2") }};

        bool a_negative = {{ left.getLongValueIsNegativeTestExpression("operand1") }};
        bool b_negative = {{ right.getLongValueIsNegativeTestExpression("operand2") }};

        if (a_negative) {
            if (b_negative) {
                {# Reversed operands order means sign inversion. #}
                {{ operand1 }} = _Nuitka_LongSubInplaceDigits({{ operand1 }}, b_digits, b_digit_count, -1);
            } else {
                {{ operand1 }} = _Nuitka_LongAddInplaceDigits({{ operand1 }}, b_digits, b_digit_count);
                Py_SET_SIZE({{ operand1 }}, -Py_ABS(Py_SIZE({{ operand1 }})));
            }
        } else {
            if (b_negative) {
                {{ operand1 }} = _Nuitka_LongAddInplaceDigits({{ operand1 }}, b_digits, b_digit_count);
            } else {
                {{ operand1 }} = _Nuitka_LongSubInplaceDigits({{ operand1 }}, b_digits, b_digit_count, 1);
            }
        }

        {{ goto_exit(props, "exit_result_ok") }}
    }
```

There is already Jinja2 context that has getLongValueIsNegativeTestExpression and that needs to be now code now different from 3.11 and 3.12

The call to Py_SET_SIZE({{ operand1 }}, -Py_ABS(Py_SIZE({{ operand1 }}))); is assuming, that Py_SIZE is in charge, and that now would need that sort of modification.

Like adding a method.

They got implementations for Python long, for C long, and so on

```
    @staticmethod
    def getLongValueIsNegativeTestExpression(operand):
        return "Py_SIZE(%s_long_object) < 0" % operand
```

This is for know `PyLongObject *`  used in code generation. For 3.12, we need to produce something that is either Py_SIZE or whatever is new there.

For C longs, there is this:

```
    @staticmethod
    def getLongValueIsNegativeTestExpression(operand):
        return "%s_is_negative" % operand
```

And for single digit numbers, i.e. longs small enough to not be forced into 2 digits

```
    @staticmethod
    def getLongValueIsNegativeTestExpression(operand):
        return "%s < 0" % operand
```

These kinds of methods now need to be touched, to not use Py_SIZE directly, maybe add one for `Py_SET_SIZE` and getting the digit count, with `Py_ABS(Py_SIZE())`.

That's a bunch of refactoring of code, where if you do it properly, you start to use 3.11 correct code still, but there is a `#ifdef PYTHON_VERSION < 0x3c0` or so that guards it to be different to the C compiler.

Code like this is generated:

```
static PyObject *COMPARE_EQ_OBJECT_LONG_LONG(PyObject *operand1, PyObject *operand2) {
    CHECK_OBJECT(operand1);
    assert(PyLong_CheckExact(operand1));
    CHECK_OBJECT(operand2);
    assert(PyLong_CheckExact(operand2));

    PyLongObject *operand1_long_object = (PyLongObject *)operand1;

    PyLongObject *operand2_long_object = (PyLongObject *)operand2;

    bool r;

    if (operand1_long_object == operand2_long_object) {
        r = true;
    } else if (Py_SIZE(operand1_long_object) != Py_SIZE(operand2_long_object)) {
        r = false;
    } else {
        Py_ssize_t i = Py_ABS(Py_SIZE(operand1_long_object));
        r = true;

        while (--i >= 0) {
            if (operand1_long_object->ob_digit[i] != operand2_long_object->ob_digit[i]) {
                r = false;
                break;
            }
        }
    }

    // Convert to target type.
    PyObject *result = BOOL_FROM(r);
    Py_INCREF(result);
    return result;
}
```

Modify those helpers, add maybe some, the Jinja will produce code that won't use Py_ABS anymore, but maybe a newly added `_Nuitka_GetDigitCount` instead, that for 3.11 is one thing, and for 3.12 something else.

This sort of code also comes from it

```
/* Code referring to "LONG" corresponds to Python2 'long', Python3 'int' and "LONG" to Python2 'long', Python3 'int'. */
static PyObject *_BINARY_OPERATION_ADD_OBJECT_LONG_LONG(PyObject *operand1, PyObject *operand2) {
    CHECK_OBJECT(operand1);
    assert(PyLong_CheckExact(operand1));
    CHECK_OBJECT(operand2);
    assert(PyLong_CheckExact(operand2));

    PyObject *result;

    // Not every code path will make use of all possible results.
#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable : 4101)
#endif
    NUITKA_MAY_BE_UNUSED PyObject *obj_result;
    NUITKA_MAY_BE_UNUSED long clong_result;
#ifdef _MSC_VER
#pragma warning(pop)
#endif

    PyLongObject *operand1_long_object = (PyLongObject *)operand1;

    PyLongObject *operand2_long_object = (PyLongObject *)operand2;

    if (Py_ABS(Py_SIZE(operand1_long_object)) <= 1 && Py_ABS(Py_SIZE(operand2_long_object)) <= 1) {
        long r = MEDIUM_VALUE(operand1_long_object) + MEDIUM_VALUE(operand2_long_object);

        clong_result = r;
        goto exit_result_ok_clong;
    }

    {
        PyLongObject *z;

        digit const *a_digits = operand1_long_object->ob_digit;
        Py_ssize_t a_digit_count = Py_ABS(Py_SIZE(operand1_long_object));
        bool a_negative = Py_SIZE(operand1_long_object) < 0;
        digit const *b_digits = operand2_long_object->ob_digit;
        Py_ssize_t b_digit_count = Py_ABS(Py_SIZE(operand2_long_object));
        bool b_negative = Py_SIZE(operand2_long_object) < 0;

        if (a_negative) {
            if (b_negative) {
                z = _Nuitka_LongAddDigits(a_digits, a_digit_count, b_digits, b_digit_count);
                Py_SET_SIZE(z, -(Py_SIZE(z)));
            } else {
                z = _Nuitka_LongSubDigits(b_digits, b_digit_count, a_digits, a_digit_count);
            }
        } else {
            if (b_negative) {
                z = _Nuitka_LongSubDigits(a_digits, a_digit_count, b_digits, b_digit_count);
            } else {
                z = _Nuitka_LongAddDigits(a_digits, a_digit_count, b_digits, b_digit_count);
            }
        }

        obj_result = (PyObject *)z;
        goto exit_result_object;
    }

exit_result_object:
    if (unlikely(obj_result == NULL)) {
        goto exit_result_exception;
    }
    result = obj_result;
    goto exit_result_ok;

exit_result_ok_clong:
    result = Nuitka_LongFromCLong(clong_result);
    goto exit_result_ok;

exit_result_ok:
    return result;

exit_result_exception:
    return NULL;
}
```

You don't have to run it with 3.12 to do that, and it won't work well until e.g. strings are also solved.

- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version

(py3.11)PS S:\repo\Nuitka> python -m nuitka --version
2.2rc1
Commercial: None
Python: 3.11.8 | packaged by Anaconda, Inc. | (main, Feb 26 2024, 21:34:05) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: S:\Tools\Anaconda\envs\py3.11\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\bin\Hostx64\x64\cl.exe (cl 14.3).

- How did you install Nuitka and Python

Anaconda

**Comment by kayhayen** [comment]
I think "negation" of longs needs to be its own helper function, surely it works differently. This is 3.11 code

```
static PyObject *
long_neg(PyLongObject *v)
{
    PyLongObject *z;
    if (IS_MEDIUM_VALUE(v))
        return _PyLong_FromSTwoDigits(-medium_value(v));
    z = (PyLongObject *)_PyLong_Copy(v);
    if (z != NULL)
        Py_SET_SIZE(z, -(Py_SIZE(v)));
    return (PyObject *)z;
}
```

As you can see, they used to the negation (of an object, they are shortcutting for small numbers) with Py_SIZE negation, playing a dirty trick anymore. If you check out the same in 3.12, you can get a good idea of how it's now.

```
static PyObject *
long_neg(PyLongObject *v)
{
    PyLongObject *z;
    if (_PyLong_IsCompact(v))
        return _PyLong_FromSTwoDigits(-medium_value(v));
    z = (PyLongObject *)_PyLong_Copy(v);
    if (z != NULL)
        _PyLong_FlipSign(z);
    return (PyObject *)z;
}
```

So, I guess, you would have to add a `_NuitkaLong_FlipSign` with the code of 3.11 and 3.12 behind #if

**Comment by kayhayen** [comment]
```
#if PYTHON_VERSION < 0x3c
#define _NuitkaLong_FlipSign(x) Py_SET_SIZE(x, -(Py_SIZE(x)));
#else
#define _NuitkaLong_FlipSign _PyLong_FlipSign
#endif
```

This should be it. Find all the places that do this, and call the new "function" from there. If done correctly, you see no change for Python3.11, and for Python3.12 one C compile error will be gone. The proper spot could be `nuitka/build/include/nuitka/helper/ints.h` although maybe I forgot and there is a better one.

Then rinse and repeat. For everything done there, we have a Python longobject code that we need to make portable across versions essentially.

**Comment by kayhayen** [comment]
The `0x3c0` is 3.12

**Comment by kayhayen** [comment]
I did this and it's currently on factory branch.

**Comment by quaesitor-scientiam** [comment]
Bummer, sorry didn't know you were going to move this fast on this issue.  Thanks anyway
