### ISSUE TITLE
Python3.11, Nuitka, OpenCV and GStreamer

### ISSUE THREAD

**Issue by cceresa-ivm** [Nuitka/Nuitka#2762]
> python -m nuitka --version
2.1.1
Commercial: None
Python: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\ClaireCERESA\PycharmProjects\gstreamer_project\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\Hostx64\x64\cl.exe (cl 14.3).

I installed nuitka in my virtual environment (based on Python3.11) using pip.

> python -m pip freeze
Nuitka==2.1.1
numpy==1.26.4
ordered-set==4.1.0
PySide6==6.6.2
PySide6_Addons==6.6.2
PySide6_Essentials==6.6.2
shiboken6==6.6.2
zstandard==0.22.0

I need to use openCV with GStreamer. So I follow this tutorial to compile it : 
https://galaktyk.medium.com/how-to-build-opencv-with-gstreamer-b11668fa09c

The package opencv is therefore installed directly in my Python 3.11 (used to create the virtual environment)

When I do : "python -m nuitka main.py", everything works.

But I need a onefile executable. So I use : "python -m nuitka --onefile main.py"

And I have an error :
_FATAL: anti-bloat: Error, failed to evaluate expression "textwrap.indent(pkgutil.get_data('cv2', 'config.py').decode('utf8'), '    ') + textwrap.indent(pkgutil.get_data('cv2', 'config-3.py').decode('utf8'), '    ')" in this context,
 exception was 'DLL load failed while importing cv2: Le module spécifié est introuvable.'.
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'._

**What do I have to do to compile my project in a onefile executable with the opencv I compiled and the dll for GStreamer ?**

**Comment by cceresa-ivm** [comment]
If needed, the nuitka-crash-report is :

"<?xml version='1.0' encoding='utf8'?>
<nuitka-compilation-report nuitka_version="2.1.1" nuitka_commercial_version="not installed" completion="error exit message (1)" exit_message="anti-bloat: Error, failed to evaluate expression &quot;textwrap.indent(pkgutil.get_data('cv2', 'config.py').decode('utf8'), '    ') + textwrap.indent(pkgutil.get_data('cv2', 'config-3.py').decode('utf8'), '    ')&quot; in this context, exception was 'DLL load failed while importing cv2: Le module spécifié est introuvable.'.">
  <module name="__main__" kind="PythonMainModule" usage="root_module" reason="Root module" source_path="${cwd}\main.py">
    <module_usages>
      <module_usage name="PySide6.QtCore" finding="absolute" line="1" />
      <module_usage name="PySide6.QtWidgets" finding="absolute" line="2" />
      <module_usage name="PySide6" finding="absolute" line="3" />
      <module_usage name="PySide6.QtGui" finding="relative" line="3" />
      <module_usage name="sys" finding="absolute" line="4" />
      <module_usage name="os" finding="absolute" line="5" />
      <module_usage name="_collections_abc" finding="absolute" line="1" />
      <module_usage name="abc" finding="absolute" line="1" />
      <module_usage name="ast" finding="absolute" line="1" />
      <module_usage name="codecs" finding="absolute" line="1" />
      <module_usage name="collections" finding="absolute" line="1" />
      <module_usage name="collections.abc" finding="absolute" line="1" />
      <module_usage name="contextlib" finding="absolute" line="1" />
      <module_usage name="copyreg" finding="absolute" line="1" />
      <module_usage name="dis" finding="absolute" line="1" />
      <module_usage name="encodings" finding="absolute" line="1" />
      <module_usage name="encodings.aliases" finding="absolute" line="1" />
      <module_usage name="encodings.ascii" finding="absolute" line="1" />
      <module_usage name="encodings.big5" finding="absolute" line="1" />
      <module_usage name="encodings.big5hkscs" finding="absolute" line="1" />
      <module_usage name="encodings.charmap" finding="absolute" line="1" />
      <module_usage name="encodings.cp037" finding="absolute" line="1" />
      <module_usage name="encodings.cp1006" finding="absolute" line="1" />
      <module_usage name="encodings.cp1026" finding="absolute" line="1" />
      <module_usage name="encodings.cp1125" finding="absolute" line="1" />
      <module_usage name="encodings.cp1140" finding="absolute" line="1" />
      <module_usage name="encodings.cp1250" finding="absolute" line="1" />
      <module_usage name="encodings.cp1251" finding="absolute" line="1" />
      <module_usage name="encodings.cp1252" finding="absolute" line="1" />
      <module_usage name="encodings.cp1253" finding="absolute" line="1" />
      <module_usage name="encodings.cp1254" finding="absolute" line="1" />
      <module_usage name="encodings.cp1255" finding="absolute" line="1" />
      <module_usage name="encodings.cp1256" finding="absolute" line="1" />
      <module_usage name="encodings.cp1257" finding="absolute" line="1" />
      <module_usage name="encodings.cp1258" finding="absolute" line="1" />
      <module_usage name="encodings.cp273" finding="absolute" line="1" />
      <module_usage name="encodings.cp424" finding="absolute" line="1" />
      <module_usage name="encodings.cp437" finding="absolute" line="1" />
      <module_usage name="encodings.cp500" finding="absolute" line="1" />
      <module_usage name="encodings.cp720" finding="absolute" line="1" />
      <module_usage name="encodings.cp737" finding="absolute" line="1" />
      <module_usage name="encodings.cp775" finding="absolute" line="1" />
      <module_usage name="encodings.cp850" finding="absolute" line="1" />
      <module_usage name="encodings.cp852" finding="absolute" line="1" />
      <module_usage name="encodings.cp855" finding="absolute" line="1" />
      <module_usage name="encodings.cp856" finding="absolute" line="1" />
      <module_usage name="encodings.cp857" finding="absolute" line="1" />
      <module_usage name="encodings.cp858" finding="absolute" line="1" />
      <module_usage name="encodings.cp860" finding="absolute" line="1" />
      <module_usage name="encodings.cp861" finding="absolute" line="1" />
      <module_usage name="encodings.cp862" finding="absolute" line="1" />
      <module_usage name="encodings.cp863" finding="absolute" line="1" />
      <module_usage name="encodings.cp864" finding="absolute" line="1" />
      <module_usage name="encodings.cp865" finding="absolute" line="1" />
      <module_usage name="encodings.cp866" finding="absolute" line="1" />
      <module_usage name="encodings.cp869" finding="absolute" line="1" />
      <module_usage name="encodings.cp874" finding="absolute" line="1" />
      <module_usage name="encodings.cp875" finding="absolute" line="1" />
      <module_usage name="encodings.cp932" finding="absolute" line="1" />
      <module_usage name="encodings.cp949" finding="absolute" line="1" />
      <module_usage name="encodings.cp950" finding="absolute" line="1" />
      <module_usage name="encodings.euc_jis_2004" finding="absolute" line="1" />
      <module_usage name="encodings.euc_jisx0213" finding="absolute" line="1" />
      <module_usage name="encodings.euc_jp" finding="absolute" line="1" />
      <module_usage name="encodings.euc_kr" finding="absolute" line="1" />
      <module_usage name="encodings.gb18030" finding="absolute" line="1" />
      <module_usage name="encodings.gb2312" finding="absolute" line="1" />
      <module_usage name="encodings.gbk" finding="absolute" line="1" />
      <module_usage name="encodings.hp_roman8" finding="absolute" line="1" />
      <module_usage name="encodings.hz" finding="absolute" line="1" />
      <module_usage name="encodings.iso2022_jp" finding="absolute" line="1" />
      <module_usage name="encodings.iso2022_jp_1" finding="absolute" line="1" />
      <module_usage name="encodings.iso2022_jp_2" finding="absolute" line="1" />
      <module_usage name="encodings.iso2022_jp_2004" finding="absolute" line="1" />
      <module_usage name="encodings.iso2022_jp_3" finding="absolute" line="1" />
      <module_usage name="encodings.iso2022_jp_ext" finding="absolute" line="1" />
      <module_usage name="encodings.iso2022_kr" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_1" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_10" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_11" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_13" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_14" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_15" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_16" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_2" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_3" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_4" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_5" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_6" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_7" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_8" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_9" finding="absolute" line="1" />
      <module_usage name="encodings.johab" finding="absolute" line="1" />
      <module_usage name="encodings.koi8_r" finding="absolute" line="1" />
      <module_usage name="encodings.koi8_t" finding="absolute" line="1" />
      <module_usage name="encodings.koi8_u" finding="absolute" line="1" />
      <module_usage name="encodings.kz1048" finding="absolute" line="1" />
      <module_usage name="encodings.latin_1" finding="absolute" line="1" />
      <module_usage name="encodings.mac_arabic" finding="absolute" line="1" />
      <module_usage name="encodings.mac_croatian" finding="absolute" line="1" />
      <module_usage name="encodings.mac_cyrillic" finding="absolute" line="1" />
      <module_usage name="encodings.mac_farsi" finding="absolute" line="1" />
      <module_usage name="encodings.mac_greek" finding="absolute" line="1" />
      <module_usage name="encodings.mac_iceland" finding="absolute" line="1" />
      <module_usage name="encodings.mac_latin2" finding="absolute" line="1" />
      <module_usage name="encodings.mac_roman" finding="absolute" line="1" />
      <module_usage name="encodings.mac_romanian" finding="absolute" line="1" />
      <module_usage name="encodings.mac_turkish" finding="absolute" line="1" />
      <module_usage name="encodings.mbcs" finding="absolute" line="1" />
      <module_usage name="encodings.oem" finding="absolute" line="1" />
      <module_usage name="encodings.palmos" finding="absolute" line="1" />
      <module_usage name="encodings.ptcp154" finding="absolute" line="1" />
      <module_usage name="encodings.punycode" finding="absolute" line="1" />
      <module_usage name="encodings.quopri_codec" finding="absolute" line="1" />
      <module_usage name="encodings.raw_unicode_escape" finding="absolute" line="1" />
      <module_usage name="encodings.shift_jis" finding="absolute" line="1" />
      <module_usage name="encodings.shift_jis_2004" finding="absolute" line="1" />
      <module_usage name="encodings.shift_jisx0213" finding="absolute" line="1" />
      <module_usage name="encodings.tis_620" finding="absolute" line="1" />
      <module_usage name="encodings.undefined" finding="absolute" line="1" />
      <module_usage name="encodings.unicode_escape" finding="absolute" line="1" />
      <module_usage name="encodings.utf_16" finding="absolute" line="1" />
      <module_usage name="encodings.utf_16_be" finding="absolute" line="1" />
      <module_usage name="encodings.utf_16_le" finding="absolute" line="1" />
      <module_usage name="encodings.utf_32" finding="absolute" line="1" />
      <module_usage name="encodings.utf_32_be" finding="absolute" line="1" />
      <module_usage name="encodings.utf_32_le" finding="absolute" line="1" />
      <module_usage name="encodings.utf_7" finding="absolute" line="1" />
      <module_usage name="encodings.utf_8" finding="absolute" line="1" />
      <module_usage name="encodings.utf_8_sig" finding="absolute" line="1" />
      <module_usage name="encodings.uu_codec" finding="absolute" line="1" />
      <module_usage name="encodings.zlib_codec" finding="absolute" line="1" />
      <module_usage name="enum" finding="absolute" line="1" />
      <module_usage name="functools" finding="absolute" line="1" />
      <module_usage name="genericpath" finding="absolute" line="1" />
      <module_usage name="importlib" finding="absolute" line="1" />
      <module_usage name="importlib._bootstrap" finding="absolute" line="1" />
      <module_usage name="importlib._bootstrap_external" finding="absolute" line="1" />
      <module_usage name="importlib.machinery" finding="absolute" line="1" />
      <module_usage name="inspect" finding="absolute" line="1" />
      <module_usage name="io" finding="absolute" line="1" />
      <module_usage name="keyword" finding="absolute" line="1" />
      <module_usage name="linecache" finding="absolute" line="1" />
      <module_usage name="locale" finding="absolute" line="1" />
      <module_usage name="ntpath" finding="absolute" line="1" />
      <module_usage name="opcode" finding="absolute" line="1" />
      <module_usage name="operator" finding="absolute" line="1" />
      <module_usage name="os" finding="absolute" line="1" />
      <module_usage name="quopri" finding="absolute" line="1" />
      <module_usage name="re" finding="absolute" line="1" />
      <module_usage name="re._casefix" finding="absolute" line="1" />
      <module_usage name="re._compiler" finding="absolute" line="1" />
      <module_usage name="re._constants" finding="absolute" line="1" />
      <module_usage name="re._parser" finding="absolute" line="1" />
      <module_usage name="reprlib" finding="absolute" line="1" />
      <module_usage name="stat" finding="absolute" line="1" />
      <module_usage name="token" finding="absolute" line="1" />
      <module_usage name="tokenize" finding="absolute" line="1" />
      <module_usage name="types" finding="absolute" line="1" />
      <module_usage name="warnings" finding="absolute" line="1" />
      <module_usage name="zipimport" finding="absolute" line="1" />
      <module_usage name="__future__" finding="absolute" line="1" />
      <module_usage name="__hello__" finding="absolute" line="1" />
      <module_usage name="__phello__" finding="absolute" line="1" />
      <module_usage name="__phello__.ham" finding="absolute" line="1" />
      <module_usage name="__phello__.ham.eggs" finding="absolute" line="1" />
      <module_usage name="__phello__.spam" finding="absolute" line="1" />
      <module_usage name="_aix_support" finding="absolute" line="1" />
      <module_usage name="_bootsubprocess" finding="absolute" line="1" />
      <module_usage name="_compat_pickle" finding="absolute" line="1" />
      <module_usage name="_compression" finding="absolute" line="1" />
      <module_usage name="_markupbase" finding="absolute" line="1" />
      <module_usage name="_osx_support" finding="absolute" line="1" />
      <module_usage name="_py_abc" finding="absolute" line="1" />
      <module_usage name="_pyio" finding="absolute" line="1" />
      <module_usage name="_sitebuiltins" finding="absolute" line="1" />
      <module_usage name="_strptime" finding="absolute" line="1" />
      <module_usage name="_threading_local" finding="absolute" line="1" />
      <module_usage name="_weakrefset" finding="absolute" line="1" />
      <module_usage name="base64" finding="absolute" line="1" />
      <module_usage name="bisect" finding="absolute" line="1" />
      <module_usage name="calendar" finding="absolute" line="1" />
      <module_usage name="cgi" finding="absolute" line="1" />
      <module_usage name="cgitb" finding="absolute" line="1" />
      <module_usage name="chunk" finding="absolute" line="1" />
      <module_usage name="cmd" finding="absolute" line="1" />
      <module_usage name="code" finding="absolute" line="1" />
      <module_usage name="codeop" finding="absolute" line="1" />
      <module_usage name="colorsys" finding="absolute" line="1" />
      <module_usage name="configparser" finding="absolute" line="1" />
      <module_usage name="contextvars" finding="absolute" line="1" />
      <module_usage name="copy" finding="absolute" line="1" />
      <module_usage name="dataclasses" finding="absolute" line="1" />
      <module_usage name="datetime" finding="absolute" line="1" />
      <module_usage name="difflib" finding="absolute" line="1" />
      <module_usage name="encodings.base64_codec" finding="absolute" line="1" />
      <module_usage name="encodings.bz2_codec" finding="absolute" line="1" />
      <module_usage name="encodings.hex_codec" finding="absolute" line="1" />
      <module_usage name="encodings.idna" finding="absolute" line="1" />
      <module_usage name="encodings.rot_13" finding="absolute" line="1" />
      <module_usage name="filecmp" finding="absolute" line="1" />
      <module_usage name="fileinput" finding="absolute" line="1" />
      <module_usage name="fnmatch" finding="absolute" line="1" />
      <module_usage name="ftplib" finding="absolute" line="1" />
      <module_usage name="getopt" finding="absolute" line="1" />
      <module_usage name="gettext" finding="absolute" line="1" />
      <module_usage name="glob" finding="absolute" line="1" />
      <module_usage name="graphlib" finding="absolute" line="1" />
      <module_usage name="gzip" finding="absolute" line="1" />
      <module_usage name="heapq" finding="absolute" line="1" />
      <module_usage name="html" finding="absolute" line="1" />
      <module_usage name="html.entities" finding="absolute" line="1" />
      <module_usage name="html.parser" finding="absolute" line="1" />
      <module_usage name="imaplib" finding="absolute" line="1" />
      <module_usage name="imghdr" finding="absolute" line="1" />
      <module_usage name="imp" finding="absolute" line="1" />
      <module_usage name="importlib._abc" finding="absolute" line="1" />
      <module_usage name="importlib.abc" finding="absolute" line="1" />
      <module_usage name="importlib.metadata" finding="absolute" line="1" />
      <module_usage name="importlib.metadata._adapters" finding="absolute" line="1" />
      <module_usage name="importlib.metadata._collections" finding="absolute" line="1" />
      <module_usage name="importlib.metadata._functools" finding="absolute" line="1" />
      <module_usage name="importlib.metadata._itertools" finding="absolute" line="1" />
      <module_usage name="importlib.metadata._meta" finding="absolute" line="1" />
      <module_usage name="importlib.metadata._text" finding="absolute" line="1" />
      <module_usage name="importlib.readers" finding="absolute" line="1" />
      <module_usage name="importlib.resources" finding="absolute" line="1" />
      <module_usage name="importlib.resources._adapters" finding="absolute" line="1" />
      <module_usage name="importlib.resources._common" finding="absolute" line="1" />
      <module_usage name="importlib.resources._itertools" finding="absolute" line="1" />
      <module_usage name="importlib.resources._legacy" finding="absolute" line="1" />
      <module_usage name="importlib.resources.abc" finding="absolute" line="1" />
      <module_usage name="importlib.resources.readers" finding="absolute" line="1" />
      <module_usage name="importlib.resources.simple" finding="absolute" line="1" />
      <module_usage name="importlib.simple" finding="absolute" line="1" />
      <module_usage name="importlib.util" finding="absolute" line="1" />
      <module_usage name="ipaddress" finding="absolute" line="1" />
      <module_usage name="json" finding="absolute" line="1" />
      <module_usage name="json.decoder" finding="absolute" line="1" />
      <module_usage name="json.encoder" finding="absolute" line="1" />
      <module_usage name="json.scanner" finding="absolute" line="1" />
      <module_usage name="mailcap" finding="absolute" line="1" />
      <module_usage name="mimetypes" finding="absolute" line="1" />
      <module_usage name="modulefinder" finding="absolute" line="1" />
      <module_usage name="netrc" finding="absolute" line="1" />
      <module_usage name="nturl2path" finding="absolute" line="1" />
      <module_usage name="numbers" finding="absolute" line="1" />
      <module_usage name="pathlib" finding="absolute" line="1" />
      <module_usage name="pickle" finding="absolute" line="1" />
      <module_usage name="pickletools" finding="absolute" line="1" />
      <module_usage name="pipes" finding="absolute" line="1" />
      <module_usage name="pkgutil" finding="absolute" line="1" />
      <module_usage name="platform" finding="absolute" line="1" />
      <module_usage name="poplib" finding="absolute" line="1" />
      <module_usage name="posixpath" finding="absolute" line="1" />
      <module_usage name="pprint" finding="absolute" line="1" />
      <module_usage name="pstats" finding="absolute" line="1" />
      <module_usage name="pyclbr" finding="absolute" line="1" />
      <module_usage name="rlcompleter" finding="absolute" line="1" />
      <module_usage name="sched" finding="absolute" line="1" />
      <module_usage name="shlex" finding="absolute" line="1" />
      <module_usage name="shutil" finding="absolute" line="1" />
      <module_usage name="signal" finding="absolute" line="1" />
      <module_usage name="sndhdr" finding="absolute" line="1" />
      <module_usage name="socketserver" finding="absolute" line="1" />
      <module_usage name="sre_compile" finding="absolute" line="1" />
      <module_usage name="sre_constants" finding="absolute" line="1" />
      <module_usage name="sre_parse" finding="absolute" line="1" />
      <module_usage name="string" finding="absolute" line="1" />
      <module_usage name="stringprep" finding="absolute" line="1" />
      <module_usage name="struct" finding="absolute" line="1" />
      <module_usage name="symtable" finding="absolute" line="1" />
      <module_usage name="sysconfig" finding="absolute" line="1" />
      <module_usage name="tarfile" finding="absolute" line="1" />
      <module_usage name="threading" finding="absolute" line="1" />
      <module_usage name="timeit" finding="absolute" line="1" />
      <module_usage name="tomllib" finding="absolute" line="1" />
      <module_usage name="tomllib._parser" finding="absolute" line="1" />
      <module_usage name="tomllib._re" finding="absolute" line="1" />
      <module_usage name="tomllib._types" finding="absolute" line="1" />
      <module_usage name="trace" finding="absolute" line="1" />
      <module_usage name="traceback" finding="absolute" line="1" />
      <module_usage name="tracemalloc" finding="absolute" line="1" />
      <module_usage name="typing" finding="absolute" line="1" />
      <module_usage name="unicodedata" finding="absolute" line="1" />
      <module_usage name="uu" finding="absolute" line="1" />
      <module_usage name="weakref" finding="absolute" line="1" />
      <module_usage name="webbrowser" finding="absolute" line="1" />
      <module_usage name="xdrlib" finding="absolute" line="1" />
      <module_usage name="zipfile" finding="absolute" line="1" />
    </module_usages>
  </module>
  <performance>
    <memory_usage name="after_launch" value="43380736" />
  </performance>
  <data_composer blob_size="None" />
  <command_line>
    <option value="--onefile" />
    <option value="main.py" />
  </command_line>
  <plugins>
    <plugin name="anti-bloat" user_enabled="no" />
    <plugin name="data-files" user_enabled="no" />
    <plugin name="delvewheel" user_enabled="no" />
    <plugin name="dll-files" user_enabled="no" />
    <plugin name="eventlet" user_enabled="no" />
    <plugin name="gevent" user_enabled="no" />
    <plugin name="gi" user_enabled="no" />
    <plugin name="glfw" user_enabled="no" />
    <plugin name="implicit-imports" user_enabled="no" />
    <plugin name="kivy" user_enabled="no" />
    <plugin name="matplotlib" user_enabled="no" />
    <plugin name="multiprocessing" user_enabled="no" />
    <plugin name="options-nanny" user_enabled="no" />
    <plugin name="pbr-compat" user_enabled="no" />
    <plugin name="pkg-resources" user_enabled="no" />
    <plugin name="pywebview" user_enabled="no" />
    <plugin name="transformers" user_enabled="no" />
  </plugins>
  <distributions />
  <python python_exe="${sys.prefix}\Scripts\python.exe" python_flavor="CPython Official" python_version="3.11.6" os_name="Windows" arch_name="x86_64">
    <search_path>
      <path value="${cwd}" />
      <path value="${sys.real_prefix}\Lib\site-packages\cv2\python-3.11" />
      <path value="${sys.real_prefix}\DLLs" />
      <path value="${sys.real_prefix}\Lib" />
      <path value="${sys.real_prefix}" />
      <path value="${sys.prefix}" />
      <path value="${sys.prefix}\Lib\site-packages" />
      <path value="${sys.real_prefix}\Lib\site-packages" />
    </search_path>
  </python>
  <output run_filename="${cwd}\main.exe" />
</nuitka-compilation-report>"

**Comment by kayhayen** [comment]
The crash report is incomplete. Your cv2 builds seems unhealthy during Nuitka compile time, make it possible to import it for Nuitka.

**Comment by cceresa-ivm** [comment]
[crash_report.txt](https://github.com/Nuitka/Nuitka/files/14589679/crash_report.txt)
 
Sorry, here is the full crash report.

**Comment by kayhayen** [comment]
That looks very unhealthy

```
    <search_path>
      <path value="${cwd}" />
      <path value="${sys.real_prefix}\Lib\site-packages\cv2\python-3.11" />
      <path value="${sys.real_prefix}\DLLs" />
      <path value="${sys.real_prefix}\Lib" />
      <path value="${sys.real_prefix}" />
      <path value="${sys.prefix}" />
      <path value="${sys.prefix}\Lib\site-packages" />
      <path value="${sys.real_prefix}\Lib\site-packages" />
    </search_path>
```

Make a proper installation of cv2, to avoid it. Since `eval` is being used, I have to assume your cv2 is actually broken, the code failing to import it during Nuitka compile time, leaves no other guess. Without a reproducer, I cannot really do confirm that, but I am not going to try random instructions to see if they work.
