### ISSUE TITLE
Compiled binaries with latest 3.6.8 say: No module named 'encodings' 

### ISSUE THREAD

**Issue by Benji81** [Nuitka/Nuitka#277]
Hello,

On nuitka 0.6.2 installed through pip from python3.6.7 install with pyenv I got a executable of **3MB** which works on this machine but not on a target machine :

> Fatal Python error: Py_Initialize: Unable to get the locale encoding
> ModuleNotFoundError: No module named 'encodings'
> 
> Current thread 0x00007f8063bdc740 (most recent call first):
> Aborted (core dumped)

On the same machine, I used to compile the same source for 3 another versions of Python (2.7, 3.4 and 3.5 but installed with apt this time and with also a Nuitka 0.6.2 installed through pip). The resulting binaries are about **250KB** and they work on the target machine.

Compilation line:
`nuitka3 --python-flag=no_site run.py`

A temporary solution would be to install a python3.6.7 manually but I would like to do it with pyenv for my CI.

Thanks,

**Comment by JorjMcKie** [comment]
If you do not use option ``--standalone``, nor ``--module``, then you will create a program that only can run on that machine and with that Python. There is no "target machine".

If I understand your intention right, you must use ``--standalone``.

**Comment by kayhayen** [comment]
If you do not switch OS, and have Python installed in the system in the same way, standalone can be avoided. But that is not advisable, right. I wonder if we could try and make accelerated binaries given nicer errors though, but generally I am assuming user error here, therefore closing.

**Comment by Benji81** [comment]
@JorjMcKie adding the --standalone option raise a:

> scons: *** [invenis_run.build/module.__main__.c] ValueError : unsupported pickle protocol: 4

I used to build several versions (2.7, 3.4, 3.5, 3.6) to ensure it will work on a target machine with at least one of this python version installed. Maybe it fails because when I compile with a pyenv, it suppose the python on the target machine is also a "pyenv" Python.

**Comment by kayhayen** [comment]
Although recently it seems one guy managed to get `pyenv` working, this is very much unsupported. It seems no `pyenv` is like the other. There is also something in the User Manual specifically stating that. 

This one `pyenv` even seems to take issue with Scons. Never saw that kind of error so far.

Make sure to use a scons that works better, either the inline copy (remove scons) or install it, if it's not installed, not sure what scons you are using there.

**Comment by Benji81** [comment]
@kayhayen first thanks for your nice work on this project.
I confirm I use almost the the same OS on both machine (ubuntu but not the same version)
You said "I am assuming user error", do you think the fact I use a pyenv python on the compile machine and a "apt-install" on the target machine is the problem?

**Comment by kayhayen** [comment]
Thanks @Benji81 

So first of all, moving to another machine is not supposed to be done in accelerated mode. Nuitka will hard code knowledge about the current system state, and of course implementation details of the minor version of Python.

Second there is the issue that `pyenv` support for standalone at least is not good.

And third, the error you gave is from Scons, and it's a Python error that has no right to exist, other than using a Python that is incompatible with it, which I didn't encounter other than for major versions. I blame `pyenv` but I might be wrong. This is before moving to another machine, and even before really using standalone mode (just building a binary intended for it).

The combination of this all is a bit much. Unsupported use case, unsupported Python that then has bugs with Scons. Please try out Anaconda and see if that works better for you.

**Comment by kayhayen** [comment]
So I updated my Anaconda on Windows to that latest `3.6.x` and get the error you originally reported on Windows too now. No standalone mode, mere acceleration.

**Comment by kayhayen** [comment]
I am not sure @Benji81 was having this, but it's suspiciously close. If you want, can you try an older Python 3.6.5 in pyenv and see if that works for you, I almost suspect it would.

There seems to be an upstream change that breaks Nuitka in this minor release.

**Comment by kayhayen** [comment]
So it seems the Anaconda created binary with 3.6.8 doesn't have the PYTHONPATH necessary to setup the interpreter.  It normally came from the "Python36.dll" that we copy along side the binary, but that seems to be no more the case. 

But now that I think of it, I have no clue how this could have ever worked, with Anaconda aiming at being movable. Need to check if we preserve enough of `sys.prefix` et all, although I think we can only do that later.

**Comment by kayhayen** [comment]
I still have the change related to this on factory only, this proves to be rather regressive, because setting `Py_SetPath` means we get a lot more responsibility.

**Comment by kayhayen** [comment]
So, I finally figured it out, and seems there is an API that is better than `PYTHONHOME` and works on newer Python versions as well as on Python2, removing the need to mess with environment variables entirely.

It's also already released as 0.6.3 just today.
