### ISSUE TITLE
MacOS shared object dependency scan failure with system library

### ISSUE THREAD

**Issue by vincent-lhomme** [Nuitka/Nuitka#2779]
Hi,

 
The issue seems related to this:  https://github.com/Nuitka/Nuitka/issues/2580

 
Using python 3.11.6, nuitka 1.9.7, macOS 14.2.1
When building the application with nuitka, the dependency scan fails with this message:
`FATAL:     Error, problem with dependency scan of '/Users/<user>/[…]/<plugin>.cpython-311-darwin.so' with '/opt/homebrew/opt/zstd/lib/libzstd.1.dylib' please report the bug.`
Command:
`poetry run python -m nuitka --standalone --macos-create-app-bundle main.py`
This happens when using a python package containing compiled code linking to a system library.
Here is the dependency:
app.py → plugin.cpython-311-darwin.so → libzstd.1.so
Note that the library is available in the system at this location:
/usr/local/lib/libzstd.1.dylib
Also note that other libraries are linked the same way, which don’t trigger the same issue, like liblzma.

I attached a tarball with material to reproduce:
[testcase_issue_nuitka.tar.gz](https://github.com/Nuitka/Nuitka/files/14651305/testcase_issue_nuitka.tar.gz)

Thanks for your support!

**Comment by kayhayen** [comment]
Please use current Nuitka, those things have changed a bunch.
