### ISSUE TITLE
FATAL: Error, file 'main.py' is not found.

### ISSUE THREAD

**Issue by ManPython** [Nuitka/Nuitka#2780]
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version
2.1.2
Nuitka-2.1.2-cp311-cp311-win_amd64.whl size=3291853 sha256=574f57890252819ffe292fdcb4171e2f45cffd1b16d909b986b224e64bae3a32
 
- How did you install Nuitka and Python

pip

 
There is crazy issue for me when using .bat file Winows11 as administrator.
`FATAL: Error, file 'main.py' is not found.`
When no administrator then some dir/files have no access `PermissionError: [WinError 32] `, but main.py is found normally then.
I'm doing simple example. The compiler.bat :

```
E:\Python311-venv\Scripts\python -m nuitka --exe main.py
pause
```
With other parameters -- similar case. Old versions of nuitka did not meet this type issues I think, but I not used nuitka with new update of W11..can be related issue.

**Comment by KevinRodriguez777** [comment]
--exe is not a valid parameter, read the manual

**Comment by ManPython** [comment]
> --exe is not a valid parameter, read the manual
But this is one case exactly where I'm getting correctly working .exe (if copied next to python3.dll)..

**Comment by kayhayen** [comment]
The `--exe` expands to `--execute-with-pythonpath` or so, and has an effect if used with `--run` only @KevinRodriguez777 and arguably, not a good idea to abbreviate that short, and historically, Nuitka might have had `--exe` and I now forgot, but module mode was the default once, maybe. I forgot.

As for Windows permissions, get them right. I am myself unsure now, how `os.path.exists` handles `PermissionError` properly, but I don't think we care much. But if it's false, I guess that's that then.

**Comment by kayhayen** [comment]
Checking out the option, I noticed it's not being used anymore, I will just remove it for 2.2.

We also got a non-warning reader here.

```
    if not shallExecuteImmediately():
        if shallRunInDebugger():
            Tracing.options_logger.warning(
                "The '--debugger' option has no effect outside of '--debug' without '--run' option."
            )

        if not shallClearPythonPathEnvironment():
            Tracing.options_logger.warning(
                "The '--execute-with-pythonpath' option has no effect without '--run' option."
            )

```

I was checking in to see if that was missing, but I guess, I need to default assume Nuitka warns, but people don't care enough to read anything.

**Comment by ManPython** [comment]
Something is wrong here with all.
When adding `--run` then compiled app working in relation to venv. When close after 1st time auto executed by run then 2nd run from .exe icon does not working, must be moved next to python311.dll 

Anyway after compilation I seeing this:
`Nuitka-Scons: Onefile linking program with 1 files (no progress information available for this stage).`
but even something wrong, I see a information:
`The system cannot find the specified path`
`The system cannot find the specified path`
`The system cannot find the specified path`
- but witch path? By this log is not clear around
Then normal..
```
Nuitka-Scons: Compiled 1 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 1
Nuitka-Onefile: Using compression for onefile payload.
Nuitka-Onefile: Onefile payload compression ratio (20.25%) size 98029904 to 19851003.
Nuitka-Onefile: Keeping onefile build directory 'main.onefile-build'.
Nuitka: Keeping dist folder 'main.dist' for inspection, no need to use it.
Nuitka: Keeping build directory 'main.build'.
Nuitka: Successfully created 'main.exe'.
Nuitka: Launching 'main.exe'.
```

Also:
`__main__.py: error: The '--msvc' option requires an argument with '--msvc='.`
then: ` --msvc=MSVC`
`FATAL: For --msvc only values 'latest', 'info', and 'X.Y' values are allowed, but not 'MSVC'.`

**Comment by kayhayen** [comment]
The --run option does things properly, and if you read the output of Nuitka, you would know what to to run. Hint, it's not the .exe file.

I don't get your `--msvc` option comment. The only thing I dislike there is that it calls things `__main__.py` which is sort of defeating the readability of the output with `-m nuitka`.

**Comment by kayhayen** [comment]
I pushed the improved usage string to factory. Please don't confuse closed issues with personally support threads.

**Comment by ManPython** [comment]
>  Please don't confuse closed issues with personally support threads.

I think is W11 issue. I meet this same when tried cythonize manually some examples. But case with `PermissionError: [WinError 32]` blocking something in case old project with previous nuitka with p38 no problem.

The suggestions around `--msvc` must be changed. 

Not have option answer and close for ticket.

**Comment by kayhayen** [comment]
I don't get what you are trying to say. Maybe open a new issue, where you try to explain it without assuming I already understand what you are saying.
