### ISSUE TITLE
FATAL: Error, data files cannot be included in accelerated mode unless using commercial plugins '--embed-*' options. Not done for

### ISSUE THREAD

**Issue by ManPython** [Nuitka/Nuitka#2781]
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version
2.1.2
Nuitka-2.1.2-cp311-cp311-win_amd64.whl size=3291853 sha256=574f57890252819ffe292fdcb4171e2f45cffd1b16d909b986b224e64bae3a32
 
- How did you install Nuitka and Python

pip

```
python -m nuitka --include-data-file=test.gif=test.gif --include-package=cynes main.pyw
Nuitka-Options: Used command line options: --include-data-file=test.gif=test.gif --include-package=cynes main.pyw
Nuitka: Starting Python compilation with Nuitka '2.1.2' on Python '3.11' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: cl (cl 14.3).
Nuitka-Scons: Backend linking program with 8 files (no progress information available for this stage).
Nuitka-Scons: Compiled 8 C files using clcache with 4 cache hits and 4 cache misses.
FATAL: Error, data files cannot be included in accelerated mode unless using commercial plugins '--embed-*' options. Not done for 'test.gif'
```

What is reason for this error? How to operate  '--embed-*' ?

**Comment by KevinRodriguez777** [comment]
are you sure you need an accelerated build? including package data makes me think you want standalone or onefile

**Comment by ManPython** [comment]
It's does not matter what want.. (single .exe app in fact) but issue is about parameter.

**Comment by KevinRodriguez777** [comment]
what you want does matter, the parameter cannot be used with accelerated mode but can be used with standalone / onefile. therefore using parameters not supported with a certain mode will not work.
