### ISSUE TITLE
Python311.dll can't be found

### ISSUE THREAD

**Issue by ManPython** [Nuitka/Nuitka#2782]
Regarding this issue, it's still actuall 
https://github.com/Nuitka/Nuitka/issues/2568#issuecomment-2007842426

- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version
2.1.2
Nuitka-2.1.2-cp311-cp311-win_amd64.whl size=3291853 sha256=574f57890252819ffe292fdcb4171e2f45cffd1b16d909b986b224e64bae3a32
 
- How did you install Nuitka and Python

pip

1. What I meet:

`Main.cmd` have this:
```
@echo off
rem This script was created by Nuitka to execute 'main.exe' with Python DLL being found.
set PATH=E:\SOFTW~1\PYTHON\PYTHON~4;%PATH%
set PYTHONHOME=E:\SOFTWARE\PYTHON\Python311
set NUITKA_PYTHONPATH=E:\Projects\Python;E:\SOFTWARE\PYTHON\Python311\DLLs;E:\SOFTWARE\PYTHON\Python311\Lib;E:\SOFTWARE\PYTHON\Python311;E:\SOFTWARE\PYTHON\Python311-venv;E:\SOFTWARE\PYTHON\Python311-venv\Lib\site-packages;E:\SOFTWARE\PYTHON\Python311-venv\Lib\site-packages\win32;E:\SOFTWARE\PYTHON\Python311-venv\Lib\site-packages\win32\lib;E:\SOFTWARE\PYTHON\Python311-venv\Lib\site-packages\Pythonwin
"%~dp0main.exe" %*
```

a) this looks bad created
`set PATH=E:\SOFTW~1\PYTHON\PYTHON~4;%PATH%`
should be 
`E:\SOFTWARE\PYTHON\Python311-venv\`

b) By this.. I'm not sure about Python311.dll incude to single .exe file
I. Looks like not added. But why?
II. When exe moving to dir Python311 wehre is Python311.dll then working. On Python311-venv\scripts not.

2. Soo..
```
E:\SOFTWARE\Python311-venv\Scripts\python -m nuitka --include-data-file=test.gif=test.gif main.pyw
pause
```
a) Then how to build main.exe with single file/one file including test.gif and Python311.dll other related as required?
b) How to ommit the Main.cmd or it's always required to prepare .exe ?
c) How to add Python311-venv without nuitka in Python311-venv? Coz normally taking all, but note that in .bat I can indicate many other venv as required, but I should not have in each nuitka I think or pip related modules. 

or should be:
`--include-onefile-external-data=test.gif=test.gif` ??

**Comment by ManPython** [comment]
I'm testing `--onefile` without `--mingw64` and.. 
`Error, couldn't launch child ([Error 225] Operation did not complete successfully because the file contains a virus or potentially unwanted software.
)`
Each new `onefile_13680_133553608560118309` is problem for Win Defender. Eg. `Trojan:Win32/Wacatac.B!ml`

Only with `--mingw64` working .exe for me copied next to `E:\SOFTWARE\PYTHON\Python311\`


Eg.
```
E:\Projects\Python>E:\SOFTWARE\Python311-venv\Scripts\python -m nuitka  --onefile --include-onefile-external-data=test.gif=test.gif main.pyw --experimental=--report-refcounts --debug
Nuitka-Options: Used command line options: --onefile --include-onefile-external-data=test.gif=test.gif main.pyw
Nuitka-Options: --experimental=--report-refcounts --debug
Nuitka: Starting Python compilation with Nuitka '2.1.2' on Python '3.11' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka-CodeGen: Missing C helper code variant, used fallback:
Nuitka-CodeGen: E:\SOFTWARE\Python311-venv\Lib\site-packages\numpy\core\einsumfunc.py:568,E:\SOFTWARE\Python311-venv\Lib\site-packages\numpy\polynomial\chebyshev.py:302,E:\SOFTWARE\Python311-venv\Lib\site-packages\numpy\polynomial\chebyshev.py:333,E:\SOFTWARE\Python311-venv\Lib\site-packages\pip\_vendor\rich\cells.py:72,E:\SOFTWARE\Python311-venv\Lib\site-packages\pip\_vendor\rich\text.py:1073
Nuitka-CodeGen: at BINARY_OPERATION_FLOORDIV_OBJECT_LONG_DIGIT
Nuitka-CodeGen: Missing C helper code variant, used fallback:
Nuitka-CodeGen: E:\SOFTWARE\Python311-venv\Lib\site-packages\numpy\core\getlimits.py:197
Nuitka-CodeGen: at BINARY_OPERATION_POW_OBJECT_DIGIT_DIGIT
Nuitka-CodeGen: Missing C helper code variant, used fallback:
Nuitka-CodeGen: E:\SOFTWARE\Python311-venv\Lib\site-packages\numpy\core\records.py:297,E:\SOFTWARE\Python311-venv\Lib\site-packages\numpy\lib\npyio.py:1618,E:\SOFTWARE\Python311-venv\Lib\site-packages\numpy\lib\npyio.py:1623,E:\SOFTWARE\Python311-venv\Lib\site-packages\numpy\lib\npyio.py:2305
Nuitka-CodeGen: at BINARY_OPERATION_MOD_OBJECT_OBJECT_TUPLE
Nuitka-CodeGen: Missing C helper code variant, used fallback:
Nuitka-CodeGen: E:\SOFTWARE\Python311-venv\Lib\site-packages\numpy\lib\arraysetops.py:725
Nuitka-CodeGen: at RICH_COMPARE_GT_NBOOL_FLOAT_LONG
Nuitka-CodeGen: Missing C helper code variant, used fallback:
Nuitka-CodeGen: E:\SOFTWARE\Python311-venv\Lib\site-packages\numpy\lib\npyio.py:2286 at
Nuitka-CodeGen: INPLACE_OPERATION_MOD_OBJECT_TUPLE
Nuitka-CodeGen: Missing C helper code variant, used fallback:
Nuitka-CodeGen: E:\SOFTWARE\Python311-venv\Lib\site-packages\pip\_vendor\urllib3\util\retry.py:368
Nuitka-CodeGen: at BINARY_OPERATION_POW_OBJECT_DIGIT_LONG
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: cl (cl 14.3).
Nuitka-Scons: Backend linking program with 425 files (no progress information available for this stage).
Nuitka-Scons: Compiled 425 C files using clcache with 0 cache hits and 425 cache misses.
Nuitka-Postprocessing: Creating single file from dist folder, this may take a while.
Nuitka-Onefile: Running bootstrap binary compilation via Scons.
Nuitka-Scons: Onefile C compiler: cl (cl 14.3).
Nuitka-Scons: Onefile linking program with 1 files (no progress information available for this stage).
Nuitka-Scons: Compiled 1 C files using clcache with 0 cache hits and 1 cache misses.
Nuitka-Onefile: Using compression for onefile payload.
Nuitka-Onefile: Onefile payload compression ratio (19.77%) size 266660276 to 52717716.
Nuitka-Onefile: Keeping onefile build directory 'main.onefile-build'.
Nuitka: Keeping dist folder 'main.dist' for inspection, no need to use it.
Nuitka: Keeping build directory 'main.build'.
Nuitka: Successfully created 'main.exe'.

 ```
..but no exist .exe
But..  --onefile looks like old "singlefile" from other python tools to compile to .exe as bundling to execute after unpack.
This all doing dissonance around.


Also often problem:
```
__constants.c:21:18: error: 'STRIP_DIRNAME' defined but not used [-Werror=unused-function]
   21 | static PyObject *STRIP_DIRNAME(PyObject *path) {
      |                  ^~~~~~~~~~~~~
cc1.exe: all warnings being treated as errors
```
`\PY7D3C~1\Lib\SITE-P~1\nuitka\build\inline_copy\libbacktrace "__constants.c`

**Comment by KevinRodriguez777** [comment]
yeah it sounds like you need to read the documentation https://nuitka.net/doc/user-manual.html#distribute
AVs detecting compiled executables with nuitka is a known issue.

**Comment by ManPython** [comment]
I just moved from python36, 38 to 311 projects, where nuitka works ok for me. But now I see many problems to reach level like time ago. Then oldest version not give me never some problems around AVs like now.
The basic problem is around .dll and venv as not combined together with .exe 


Comment.. I'm surprised how slow is MSVC 14.39.33519 now than previous versions.

**Comment by KevinRodriguez777** [comment]
venvs are not included in the exe, but modules needed by your programs are. read the manual.
