### ISSUE TITLE
Give option to run nuitka after --version

### ISSUE THREAD

**Issue by ManPython** [Nuitka/Nuitka#2785]
Right now after this command, nuitka can show just version
 `-m nuitka --version --mingw64 --show-progress --show-memory --run --onefile --enable-plugin=numpy main.pyw`
Want suggest to process next commands.

@kayhayen do You remeber my app as Nuitka-GUI? Can't find this on repos around as uttility tools, etc.
Was deleted maybe?

**Comment by kayhayen** [comment]
No tool I know of does that. Also, Nuitka runs special modes when it handles --version, making two invocations is not a problem. If you want to record Nuitka version output, --report is the more powerful way of achieving that, since it covers more information, or should at least. But missing stuff should be added there instead.

**Comment by ManPython** [comment]
> Regarding GUI, do you mean this one?

Not this as juancarlospaco. My GUI was based on QT as new to operate with parameters and profiles (tree widgets).
If not exist will try publish on my own repos. Other way in private files you can check find file "Nuitka-GUI_v3.png" but can be in zip as remember.

There was a output with whole lines from cmd, then not must omit --version from `OptionParsing.py` as all commands and helps docs. App build a config profile from this. I like this to manage many logs, compare, etc. 
Due complications with "ad administrator" and differences result around cmd and WindowsTerminal often, .bat files are problematic on Windows. Also when doing "partial test" for some modules when must prepare other main.py files as version, profile are more comfy to manage than .bat etc. But yaml now also can be good solution but manage execute many of still need some special workflow.

**Comment by kayhayen** [comment]
You might mean this one: https://github.com/Nuitka/NUITKA-Utilities

This is archived, and searches do not find it anymore I think.

**Comment by kayhayen** [comment]
Closing, as I reject your idea of --version only causing output and still compiling.
