### ISSUE TITLE
Error on the output .exe both onefile and dist. 'Cannot import name 'tm' from dask.dataframe._compat'

### ISSUE THREAD

**Issue by nnc6** [Nuitka/Nuitka#2788]
I already installed last version of dask (2024.2.1) and nuitka (2.1.2) but I'm always getting the same output.
After roughly two hours compiling and no error report the output .exe file of my script is always useless. As i click on the exe the cmd is appearing, then something appears and suddendly the windows get closed. After a few try I was able to print the screen, see below.
![error](https://github.com/Nuitka/Nuitka/assets/9645415/eab7a459-0edd-43c1-b380-1255b6400213)
I got that there's some problems with dask dataframe, I check the content of the folder C:\Users\zanepid0\Test_visual.dist\dask and it contains just dask.yaml. I don't use dask in my script, I think some other libraries I use needs it.
Any idea about how to solve? I read in another closed issue that the guy solved just upgrading nutika, but that's not my case....

**Comment by kayhayen** [comment]
In the template, we have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that we do not want to be left guessing. For you it's easy to erase the issue template and expect us to ask you questions only as necessary, but we cannot do that. We would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore we are  likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
