### ISSUE TITLE
decompile a pyd module

### ISSUE THREAD

**Issue by Jzhenli** [Nuitka/Nuitka#2792]
Hi, nuitka is really a good project, I often use it to compile my module package as a .pyd file, but I have a concern if the .pyd file can be decompiled easily by others. Would u help to confirm it?

The command I often used is:     python -m nuitka --module mycodefolder --include-package=mycodefolder 

BTW, I have noticed some closed issues have talked this topic already, but seems there's no clear answers.

**Comment by kayhayen** [comment]
It cannot be decompiled to Python.

**Comment by Siradankullanici** [comment]
You can extract malicious payload but extracting source code little bit diffucult. Here is my project about that but there more advanced one in my anrtivirus: https://github.com/HydraDragonAntivirus/AutoNuitkaDecompiler
