### ISSUE TITLE
FATAL: Error, problem with dependency scan of“darwin.so” with "ibgdal.34.dylib" please report the bug.

### ISSUE THREAD

**Issue by IceSakuraAzure** [Nuitka/Nuitka#2794]
### Nuitka version:
```
2.1.3
Commercial: None
Python: 3.10.14 (main, Mar 21 2024, 11:21:31) [Clang 14.0.6 ]
Flavor: Anaconda Python
Executable: /Users/liqi/miniconda3/envs/myenv/bin/python
OS: Darwin
Arch: arm64
Version C compiler: /usr/bin/clang (clang 15.0.0).
```

I used "nuikta" to package the python script "gdal2tiles.py" from the "GDAL" library.
My operating system is macOS 14.1.2, I installed the gdal library via brew, and then I used miniconda to set up a virtual environment "python@3.10", in which I installed the gdal library and the numpy library. Here is my pip list.
```
Package     Version
----------- -------
GDAL        3.8.4
Nuitka      2.1.3
numpy       1.26.4
ordered-set 4.1.0
pip         23.3.1
setuptools  68.2.2
wheel       0.41.2
zstandard   0.22.0
```
And this is the packing command I executed:
```
nuitka3 --standalone --output-filename=gdal2tiles /Users/liqi/miniconda3/envs/myenv/bin/gdal2tiles.py
```
After I waited about 1 hour for it to execute, the program threw an exception, and here is the full output of the run:
```
(myenv) liqi@liqideMBP gdalpackage % nuitka3 --standalone --output-filename=gdal2tiles /Users/liqi/miniconda3/envs/myenv/bin/gdal2tiles.py
Nuitka-Options: Used command line options: --standalone
Nuitka-Options: --output-filename=gdal2tiles
Nuitka-Options: /Users/liqi/miniconda3/envs/myenv/bin/gdal2tiles.py
Nuitka: Starting Python compilation with Nuitka '2.1.3' on Python '3.10'
Nuitka: commercial grade 'not installed'.
Nuitka-Plugins:anti-bloat: Not including '_bisect' automatically in order to    
Nuitka-Plugins:anti-bloat: avoid bloat, but this may cause: may slow down by
Nuitka-Plugins:anti-bloat: using fallback implementation.
Nuitka-Plugins:anti-bloat: Not including '_json' automatically in order to avoid
Nuitka-Plugins:anti-bloat: bloat, but this may cause: may slow down by using
Nuitka-Plugins:anti-bloat: fallback implementation.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.         
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: clang (clang 15.0.0).
Nuitka-Scons: Backend linking program with 111 files (no progress information
Nuitka-Scons: available for this stage).
Nuitka-Scons: Compiled 111 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache miss': 111
FATAL:     Error, problem with dependency scan of '~/miniconda3/envs/myenv/lib/python3.10/site-packages/osgeo/_gdal.cpython-310-darwin.so' with '/opt/homebrew/opt/gdal/lib/libgdal.34.dylib' please report the bug.
```
He prompted me to report the bug, so I posted this issue.
What should I do about this issue please?

**Comment by kayhayen** [comment]
It seems your environment is mixing Homebrew and Anaconda, that's not very healthy thing to have. Clean that up.

**Comment by IceSakuraAzure** [comment]
> It seems your environment is mixing Homebrew and Anaconda, that's not very healthy thing to have. Clean that up.

I reset my computer and installed only miniconda. After that, I installed "python@3.10"、"gdal"、"numpy" by "conda".Here is my environment.
[ENVIROMMENT.TXT](https://github.com/Nuitka/Nuitka/files/14807046/ENVIROMMENT.TXT)
And Here is my Nuitka Version:
```
2.1.4
Commercial: None
Python: 3.10.14 (main, Mar 21 2024, 11:21:31) [Clang 14.0.6 ]
Flavor: Anaconda Python
Executable: /Users/liqi/miniconda3/bin/python
OS: Darwin
Arch: arm64
Version C compiler: /usr/bin/clang (clang 15.0.0).
```
Then I executed the same command as before.Unfortunately, it still didn't work and the error was very similar to the previous one:
```
(base) liqi@liqideMBP gdal_pack3 % nuitka3 --standalone --output-filename=gdal2tiles /Users/liqi/miniconda3/bin/gdal2tiles.py
Nuitka-Options: Used command line options: --standalone
Nuitka-Options: --output-filename=gdal2tiles
Nuitka-Options: /Users/liqi/miniconda3/bin/gdal2tiles.py
Nuitka: Starting Python compilation with Nuitka '2.1.4' on Python '3.10'
Nuitka: commercial grade 'not installed'.
Nuitka-Plugins:anti-bloat: Not including '_bisect' automatically in order to    
Nuitka-Plugins:anti-bloat: avoid bloat, but this may cause: may slow down by
Nuitka-Plugins:anti-bloat: using fallback implementation.
Nuitka-Plugins:anti-bloat: Not including '_json' automatically in order to avoid
Nuitka-Plugins:anti-bloat: bloat, but this may cause: may slow down by using
Nuitka-Plugins:anti-bloat: fallback implementation.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.         
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: clang (clang 15.0.0).
Nuitka-Scons: Backend linking program with 110 files (no progress information
Nuitka-Scons: available for this stage).
Nuitka-Scons: Compiled 110 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 110
Nuitka-Plugins:WARNING: dll-files: DLL configuration by filename code for
Nuitka-Plugins:WARNING: 'numpy' did not give a result. Either conditions are
Nuitka-Plugins:WARNING: missing, or this version of the module needs treatment
Nuitka-Plugins:WARNING: added.
FATAL:     Error, problem with dependency scan of '~/miniconda3/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so' with '@rpath/libopenblas.0.dylib' please report the bug.
```
I don't know where is "@rpath",so what should I do about this problem?

**Comment by kayhayen** [comment]
That is a technicality of the linker, Nuitka fails to find out, what it is at compile time. Your report is good now, I will check it out.

**Comment by kayhayen** [comment]
In an attempt to bisect it, I didn't find any prior version, that handled this setup and didn't give the same error, so it's just plainly the broken DLL detection for the Conda package here, PyPI is going to work, I will try and figure it out. The `lib` folder being there for use only sometimes seems like an omission that will affect many packages.

**Comment by kayhayen** [comment]
Ah, yes, it is indeed about not being a system package, and then being reduced to DLLs that come from `PYTHONPATH` more or less, but the folders below Anaconda should never be considered system paths, however, they now are, and that's fixable. I am not sure now how told that limitation is, maybe I needed to go back to 1.8 even, I only tried 1.9 in my bisect attempts.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by IceSakuraAzure** [comment]
> Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html
> 
> Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

Thank you for your work, during these weeks I have also tried other options to package this python library, such as using cxFreeze, pyinstaller, and so on. Some of them worked, but the startup time was so long, about 60 seconds, that it was impossible to put it into production use. For now I still think nuitka should be the best solution. Thanks again for your efforts on this issue.

**Comment by kayhayen** [comment]
This is part of the current pre-release and on develop now.

**Comment by kayhayen** [comment]
Part of the 2.2 release I just made.
