### ISSUE TITLE
Standalone: Standard library scan can crash with .git folders present

### ISSUE THREAD

**Issue by OlegXio** [Nuitka/Nuitka#2800]
```
C:\Users\1>python -m nuitka --version
2.1.4
Commercial: None
Python: 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: D:\Program Files\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Nuitka will use gcc from MinGW64 of winlibs to compile on Windows.
```

i write:
`nuitka --clang --disable-console --onefile-windows-splash-screen-image=neural-ss-xio-splash.png  --windows-icon-from-ico=ai.ico  --company-name=XioSoft --product-name=Neural-SS --copyright=license.txt --product-version=1.0.0.8 --follow-imports --output-dir=deploy-nui --onefile  --windows-product-version=1.0.0.8 Neural-SS.py`

but i get an error: 
`Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug
Nuitka-Reports: report.`
[nuitka-crash-report.xml](https://github.com/Nuitka/Nuitka/files/14817349/nuitka-crash-report.xml.txt)

i succesfully compile an "print("hello world")" programm (command `nuitka hello.py`), it's work.

[pip freeze.txt](https://github.com/Nuitka/Nuitka/files/14817353/pip.freeze.txt)

I'm try a `nuitka --follow-imports --output-dir=deploy-nui --onefile Neural-SS.py`, but it didn't work either :(.
However, I tried the same thing without the --onefile option (`nuitka --follow-imports --output-dir=deploy-nui Neural-SS.py`) , and it works!

(code contains a `pygame `and `random` modules)

**Comment by kayhayen** [comment]
It seems you have `.git` folder in your Python installation, and Nuitka is not very tolerant of dot directories.

**Comment by kayhayen** [comment]
Actually, the code tries it, and succeeds for one level only:

```
        # Ignore ".idea", ".git" and similar folders, they are not modules
        dirs = [dirname for dirname in dirs if not dirname.startswith(".")]
```

But for `os.walk` to not look further, it needs to remove it from `dir` and not overwrite it only.

So this will work

```
        # Ignore ".idea", ".git" and similar folders, they are not modules
        dirs[:] = [dirname for dirname in dirs if not dirname.startswith(".")]
```

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
Part of the 2.1.5 hotfix I just made.

**Comment by OlegXio** [comment]
Yes, thanks, the program assembled by nuitka from the factory branch works
