### ISSUE TITLE
RecursiveScriptModule' has no attribute '_construct

### ISSUE THREAD

**Issue by ckc-heu** [Nuitka/Nuitka#2804]
When running the program packaged with Nuitka, it shows 'type object 'RecursiveScriptModule' has no attribute '_construct'.' After debugging, I found that this part model = torch.jit.load(opened_file, map_location=device if jit else "cpu").eval() got stuck.
![捕获](https://github.com/Nuitka/Nuitka/assets/118704102/1b5d9d38-97cd-416f-b0cc-3447887cb27c)

I use nuitka --standalone --show-memory --show-progress --standalone --nofollow-imports --enable-plugin=pyside6 --plugin-enable=torch --windows-icon-from-ic=dj.ico  --remove-output  main.py

My environment is PS D:\py_projects\Hair-GUI\main.dist> python -m nuitka --version
2.1.4
Commercial: None
Python: 3.10.14 | packaged by Anaconda, Inc. | (main, Mar 21 2024, 16:20:14) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: D:\Annaconda3\envs\hairstyle\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Nuitka-Scons:WARNING: Windows SDK must be installed in Visual Studio for it to be usable with Nuitka. Use the Visual Studio installer for
Nuitka-Scons:WARNING: adding it.
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0)

Do you have any suggestions for me?

**Comment by kayhayen** [comment]
Yes, filling out the issue template, and providing a reproducer.
