### ISSUE TITLE
Python 3.12 Support?

### ISSUE THREAD

**Issue by Artucuno** [Nuitka/Nuitka#2806]
Hey there,

Does Nuitka have support for Python 3.12? If not, when do you think it will be added?

Some of the requirements that I have for a project unfortunately require Python 3.12.

Thanks,
Artu

**Comment by Maxwell175** [comment]
Please use GitHub's convenient search function to check if there is an issue open already.

https://github.com/Nuitka/Nuitka/issues?q=is%3Aissue+is%3Aopen+Python+3.12
