### ISSUE TITLE
ModuleNotFoundError: No module named `scipy.special._cdflib` with `SciPy-1.13.0`

### ISSUE THREAD

**Issue by srikanthravipati** [Nuitka/Nuitka#2807]
- `python -m nuitka --version`
 
     2.1.4
     Commercial: None
     Python: 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
     Flavor: CPython Official
     Executable: C:\Users\SrikanthRavipati\AppData\Local\Programs\Python\Python311\python.exe
     OS: Windows
     Arch: x86_64
     WindowsRelease: 10
     Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64\cl.exe  (cl 14.3).

- Installed Nuitka using pip

   `python -m pip install --upgrade nuitka`

- The specific PyPI names and versions, using `python -m pip freeze`

   `numpy==1.26.4`
   `scipy==1.13.0`  

- Example

   `from scipy.stats import median_abs_deviation`

- Provide in your issue the Nuitka options used
   
   `python -m nuitka --standalone .\test_scipy_1.13.py`

- Traceback (most recent call last) -- last two lines:
  ```
   File "scipy\\special\\_ufuncs.pyx", line 1, in init scipy.special._ufuncs
   ModuleNotFoundError: No module named 'scipy.special._cdflib'```

**Comment by seunghoon4176** [comment]
i got the same issue with pyinstaller

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
Part of the 2.1.5 hotfix I just made.

**Comment by srikanthravipati** [comment]
It's working. Thanks for the prompt response!
