### ISSUE TITLE
supoortability of @Slot(name="xxx")

### ISSUE THREAD

**Issue by pHiney** [Nuitka/Nuitka#2808]
- Please check whether the bug was already reported or fixed.
Can't see it

  > python -m nuitka --version
2.0.2
Commercial: None
Python: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\git\PathOfBuilding-Python\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\Hostx64\x64\cl.exe (cl 14.3).

There doesn't appear to be a way to ask questions:

**Does having the name for Slot() help or hinder you ?**
```python
@Slot(name="item_list_delete_item")
```

I've been wondering whether to fill these in to shut pyCharm up, but I am concerned it may not be supported by other things, like Nuitka.
![image](https://github.com/Nuitka/Nuitka/assets/4302241/f29c2a2c-3434-46c0-90ca-7f221f3ecacb)

**Comment by kayhayen** [comment]
It is supported.
