### ISSUE TITLE
Nuitka locating GCC wrong

### ISSUE THREAD

**Issue by xDefyingGravity** [Nuitka/Nuitka#2809]
On MacOS 13.6.6 with Python 3.8.
2.0.6
Commercial: None
Python: 3.8.0 (v3.8.0:fa919fdf25, Oct 14 2019, 10:23:27) 
Flavor: CPython Official
Executable: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8
OS: Darwin
Arch: x86_64

whenever i run nuitka on a file it will give me an error stating that
Permission denied: '/usr/local/opt/gcc'.
I see the error is that nuitka tries to locate the GCC executable but gets a folder instead.

**Comment by KevinRodriguez777** [comment]
can you try latest nuitka? i believe some path improvements were done recently

**Comment by xDefyingGravity** [comment]
I just tried that, but I didn’t notice much improvement in the results. I encountered the same error afterward. One thing I noticed, though, is that when I ran `nuitka —version`, it completed without stopping due to a subprocess error. This provided me with more results:

2.1.5
Commercial: None
Python: 3.8.0 (v3.8.0:fa919fdf25, Oct 14 2019, 10:23:27)
Flavor: CPython Official
Executable: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8
OS: Darwin
Arch: x86_64
Version C compiler: /usr/bin/clang (clang 15.0.0).

**Comment by kayhayen** [comment]
I think `/usr/local/opt/gcc` ought to not exist, but I can take it from there, the path scan function of Nuitka is potentially wrong, but it may also be Scons doing that. This means `/usr/local/opt/` is in PATH for you?

**Comment by xDefyingGravity** [comment]
It seems `/usr/local/opt` got added to my PATH. GCC still works fine (I use it frequently), but Nuitka seems to be picking up something incorrect.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
Closing this early for lack of general relevance.

**Comment by kayhayen** [comment]
I have put this into 2.1.6 release.
