### ISSUE TITLE
SetConsoleCtrlHandler not working with console

### ISSUE THREAD

**Issue by hansalemaos** [Nuitka/Nuitka#2815]
First, I would like to thank you for this awesome library! Keep up the great work. I have a little problem, nothing dramatic, but it would be nice if somebody could help me. 

```SetConsoleCtrlHandler``` works perfectly with the pure Python console (without being compiled with Nuitka) and with the compiled Nuitka version without console. I use it mainly to kill other processes with https://github.com/ElyDotDev/windows-kill the SetConsoleCtrlHandler helps me to not crash my own process. When I compile Nuitka with Tkinter and Console, ```SetConsoleCtrlHandler``` doesn't have any effect. 

Is there any way to fix that? Here is an example:

```py
# Ctrl+C handler 

from ctypes import WINFUNCTYPE, windll
from ctypes.wintypes import BOOL, DWORD
import sys

ctrl_config = sys.modules[__name__]
ctrl_config.function = lambda *args, **kwargs: None

kernel32 = windll.LoadLibrary("kernel32")
PHANDLER_ROUTINE = WINFUNCTYPE(BOOL, DWORD)
SetConsoleCtrlHandler = kernel32.SetConsoleCtrlHandler
SetConsoleCtrlHandler.argtypes = (PHANDLER_ROUTINE, BOOL)
SetConsoleCtrlHandler.restype = BOOL

(
    CTRL_C_EVENT,
    CTRL_BREAK_EVENT,
    CTRL_CLOSE_EVENT,
    CTRL_LOGOFF_EVENT,
    CTRL_SHUTDOWN_EVENT,
) = 0, 1, 2, 3, 4
continue_proc = True


def disable_con_proc():
    print("kill: {}".format(continue_proc))


@PHANDLER_ROUTINE
def console_handler(ctrl_type):
    r"""
    Console Control Handler for Windows

    This module provides functionality for handling console control events in Windows,
    namely CTRL_C_EVENT, CTRL_BREAK_EVENT, CTRL_CLOSE_EVENT, CTRL_LOGOFF_EVENT, CTRL_SHUTDOWN_EVENT

        Args:
            ctrl_type (int): The type of control event.

        Returns:
            bool: True if the event is handled; False otherwise.

        Example:
            To use this module, import it and set your desired function as the console handler:

            >>> from consolectrlhandler import ctrl_config

            Define your custom function to handle console control events:

            >>> def ctrl_handler(ctrl_type):
            ...     print(f"Received control event: {ctrl_type}")

            Assign your custom function as the console handler:

            >>> ctrl_config.function = ctrl_handler

            Then run your main program loop.

            # Complete code
            from consolectrlchandler import ctrl_config
            import time

            def ctrlhandler(ctrl_type):
                print(f"ctrl handler {ctrl_type}")

            ctrl_config.function = ctrlhandler
            while True:
                print("test")
                time.sleep(1)
    """
    if ctrl_type in (
        CTRL_C_EVENT,
        CTRL_BREAK_EVENT,
        CTRL_CLOSE_EVENT,
        CTRL_LOGOFF_EVENT,
        CTRL_SHUTDOWN_EVENT,
    ):
        ctrl_config.function(ctrl_type=ctrl_type)
        return True
    return False


if not SetConsoleCtrlHandler(console_handler, True):
    raise RuntimeError("SetConsoleCtrlHandler failed.")


# to import 

            from consolectrlchandler import ctrl_config
            import time

            def ctrlhandler(ctrl_type):
                print(f"ctrl handler {ctrl_type}")

            ctrl_config.function = ctrlhandler
            while True:
                print("test")
                time.sleep(1)


    test
    test
    ctrl handler 0
    test
    ctrl handler 0
    ctrl handler 0
    ctrl handler 0
    ctrl handler 0
    test
    ctrl handler 0
    test
    test```

**Comment by kayhayen** [comment]
You didn't provide the information from the issue template, nor the options used to compile.

**Comment by hansalemaos** [comment]
I am sorry, I should have read it better. 

**python -m nuitka --version**                                                        

2.1.5
Commercial: None
Python: 3.11.8 | packaged by Anaconda, Inc. | (main, Feb 26 2024, 21:34:05) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\ProgramData\anaconda3\envs\proxifierapp\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe (cl 14.3).

**How did you install Nuitka and Python?**
I installed anaconda and the pip from anaconda. Then I used Anaconda's pip to install Nuitka. I never had any problems using it that way

**command line**
start "" "C:\ProgramData\anaconda3\envs\proxifierapp\python.exe" -m nuitka C:/ProgramData/anaconda3/envs/proxifierapp/multiinstancemanagerstacks.pyw --standalone --assume-yes-for-downloads --output-dir=c:/ctrlctest --onefile --windows-icon-from-ico=C:/Users/hansc/AppData/Local/Temp/tmpxtljzj_n.ico --windows-uac-admin --file-version=1.0.0.6 --onefile-tempdir-spec=%CACHE_DIR%/multiinstancemanagerstacks/1.0.0.6 --enable-plugin=tk-inter --jobs=1 --plugin-enable=multiprocessing --show-progress --show-modules

**Comment by kayhayen** [comment]
Nuitka converts these into `KeyboardInterrupt` by the onefile bootstrap I believe. That may interfere with your code, which is not handling that exception properly maybe. Otherwise, you probably can receive those events in the Python code no problem.

**Comment by kayhayen** [comment]
Yes, onefile bootstrap will convert them to `CTRL_C_EVENT` and send that to the Python process. Python then converts that to KeyboardInterrupt normally. Not responding gets it killed. If it don't want that to happen, set the timeout to a large value, that is `--onefile-child-grace-time`.

I am not entirely sure what you want to achieve though.

**Comment by hansalemaos** [comment]
Thank you very much for your help! I will try that tomorrow! It's just about killing Bluestacks Instances. I build something like an Multiple-Instance-Manager. When I use "taskkill" to kill the instances, they break quite often and can't be started anymore, because the data is corrupt. When there is no console, everything is working fine, but I like the console when I do testing.

**Comment by kayhayen** [comment]
I am assuming, the grace time is not sufficient for your program, but it's a user error like that. In a way, this hard kill happening needs to be better described somewhere, but I don't track this a bug right now.

**Comment by hansalemaos** [comment]
Thank you so much for your help! Like you, I also don't think that it is not a bug. Today I won't be able to check it, but during the week, I will compile it again, and give it a little more grace time. Have a good Sunday!
