### ISSUE TITLE
Are Nuitka compiled files actually binaries ?

### ISSUE THREAD

**Issue by RobertAzovski** [Nuitka/Nuitka#2820]
Please just explain how does compilation works with Nuitka.

I thought binary file is just an array of 0010010101 but it seems like Nuitka just packs separate python files like Pyinstaller does. Like this one shown on ViRusTotal seems like whole my executables are consist of pyd files.
_hashlib.pyd
_ctypes.pyd
libffi-8.dll
libcrypto-1_1.dll
_uuid.pyd

So technically it is not binary at all but some archive of python bytecode files packed together ?

If so. What chances that Source Code of My program can be reverse engineered ??

**Comment by kayhayen** [comment]
The files you see there are DLLs and extension modules used for embedding Python, these are written in C, e.g. the `hashlib` module can use either a built-in module `_hashlib` or an external module. These are not using bytecode, and are just packaged by Nuitka.

Nuitka only compiles Python code to C code and therefore machine code itself. For some parts, it can use bytecode, e.g. the `encodings` are required to be bytecode when initializing the Python DLL, embedded statically or not, but user code is normally never bytecode.
