### ISSUE TITLE
[QUESTION] Executables connect strange IPs

### ISSUE THREAD

**Issue by RobertAzovski** [Nuitka/Nuitka#2822]
`$ python -m nuitka --remove-output --mingw64 --standalone --onefile yy.py` If I use `mingw64` flag I always get this error in logs

```
Nuitka-Scons: Mismatch between Python binary ('C:\sss\aaa\venv\Scripts\python.exe' -> 'pei-x86-64') and C compiler ('C:\MinGW\bin\gcc.exe' -> 'pei-i386') arches, that
Nuitka-Scons: compiler is ignored!
```
I noticed that after that VirusTotal always finds that Executable tries to connect various strange IPs even if it is `Hello World` like program.

I googled the problem and found this thread https://github.com/pyinstaller/pyinstaller/issues/8323 and seems like people notice same with Pyinstaller.

Accoring that discussion I guess when Nuitka fails to use my `minGW` compiler it uses VSCode compiler that sews in various IPs that send various data to Microsoft when an Executable gets runned.

If I don't use `--mingw64` in nuitka command then in same program VT doesn't say that the program connects to any IPs as it should be.

Thus. I have questions:
1. Why Nuitka fails to use my GCC ?
2. If it doesnt use my GCC then what does Nuitka use ?

**Comment by kayhayen** [comment]
You might want to ask VirusTotal or Microsoft about why they connect to IPs. I reckon, it's to verify signature validity or malware catalogs before exiting a binary.

Your observations generally are wrong, I think.

**Comment by kayhayen** [comment]
I am considering the error output to be pretty self explanatory, you seem to think the issue tracker is for asking unrelated or unclear things, I do not.
