### ISSUE TITLE
Using Nuitka to create a shared module?

### ISSUE THREAD

**Issue by aghasemi** [Nuitka/Nuitka#2827]
Hi and sorry if this is answered before/available in documentations. Is it possible to use Nuitka to create a shared module insyead of an executable, with exported functions that can be called by other programs etc.?

Many thanks

**Comment by KRRT7** [comment]
yes, the documentation goes over this. https://nuitka.net/user-documentation/use-cases.html#use-case-2-extension-module-compilation

**Comment by aghasemi** [comment]
Hi. Thanks for the link and sorry for continuing the discussion. Is there a minimal example on how to make it work? It seems in documents the focus is on creating native module for Python itself, whereas I want to call the created native module from another programming language (Java). When I check the exported symbols in the created .so file (using `objdump` in Linux), I only see one with the same name as the module/file name, but nothing for the functions that I created in that module. Is that expected?

**Comment by kayhayen** [comment]
The lack of documentation is founded in the lack of support for the scenario. Nuitka does not create DLLs for you yet, it may in the future, as a couple of customers help themselves and achieve that, but if you don't know how to embed Python yourself, then this is not the project to do it for you, refer to Python documentation for embedding of Python.
