### ISSUE TITLE
No ordinary import error 

### ISSUE THREAD

**Issue by Rakhsan** [Nuitka/Nuitka#2831]
So I checked the docs saw the issues other people were having.
The problem is nuitka is not importing the current directory.

My file structure:
`C:\Users\USER\PycharmProjects\Minecraft
|   main.py
|   settings.py
|   shader_program.py
|   textures.py
|   tnd.py
|   Voxeloid.ico
|   __init__.py
|   
+---assets
|       (Contains assets for the game)
|   
+---compiled
|       (Will contain compiled executables)
|   
+---meshes
|       (Contains mesh data for the game)
|   
+---shaders
|       (Contains shader code)
|   
+---world_objects
|   +---chunk.py
|   |   __init__.py
|   |   
|   \---__pycache__
|           chunk.cpython-39.pyc
|           
\---__pycache__
        settings.cpython-39.pyc
`

Here is command I use:
` nuitka --standalone --include-data-file=Voxeloid.ico=./ --windows-icon-from-ico=Voxeloid.ico --output-dir=C:\Users\USER\PycharmProjects\Minecraft\compiled main.py`

So when I checked why my app was not starting I did this:
`C:\Users\USER\PycharmProjects\Minecraft\compiled\main.dist>main.exe > output.txt 2>&1`

Inside of output.txt looks like this:
`Traceback (most recent call last):
  File "C:\Users\USER\PYCHAR~1\MINECR~1\compiled\MAIN~1.DIS\main.py", line 5, in <module>
  File "C:\Users\USER\PYCHAR~1\MINECR~1\compiled\MAIN~1.DIS\scene.py", line 2, in <module scene>
  File "C:\Users\USER\PYCHAR~1\MINECR~1\compiled\MAIN~1.DIS\world_objects\chunk.py", line 1, in <module world_objects.chunk>
ModuleNotFoundError: No module named 'Minecraft'
pygame-ce 2.4.1 (SDL 2.28.5, Python 3.11.9)
`

Honorable mentions:
`PS C:\Users\USER\PycharmProjects\Minecraft> nuitka --version
2.1.6
Commercial: None
Python: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\USER\PycharmProjects\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\bin\Hostx64\x64\cl.exe (cl 14.3).
PS C:\Users\USER\PycharmProjects\Minecraft> python --version
Python 3.11.9
PS C:\Users\USER\PycharmProjects\Minecraft> systeminfo | findstr /B /C:"OS Name" /B /C:"OS Version" 
OS Name:                   Microsoft Windows 10 Pro                           
OS Version:                10.0.19045 N/A Build 19045
PS C:\Users\USER\PycharmProjects\Minecraft>
`

PLS HELP ME!

**Comment by Rakhsan** [comment]
Also tried: `sys.path.append(r"C:/Users/USER/PycharmProjects/Minecraft")` in main.py but didn't work

**Comment by kayhayen** [comment]
In the template, we have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that we do not want to be left guessing. For you it's easy to erase the issue template and expect us to ask you questions only as necessary, but we cannot do that. We would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore we are  likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."

**Comment by Rakhsan** [comment]
Ok ok I ma close this and create a new one with exceptional standard
