### ISSUE TITLE
F_TRACE

### ISSUE THREAD

**Issue by JustRedTTG** [Nuitka/Nuitka#2835]
```C:\temp\demo>main                                                                                                       Traceback (most recent call last):                                                                                        File "C:\temp\demo\main.pyw", line 165, in <module>                                                                     File "C:\temp\demo\pygameextra\context.py", line 311, in __call__                                                       File "C:\temp\demo\pygameextra\context.py", line 288, in _loop                                                          File "C:\temp\demo\main.pyw", line 129, in loop                                                                         File "C:\temp\demo\engine\SceneContext.py", line 75, in __call__                                                        File "C:\temp\demo\pygameextra\context.py", line 173, in __call__                                                       File "C:\temp\demo\pygameextra\context.py", line 170, in actual                                                         File "C:\temp\demo\pygameextra\display.py", line 150, in wrap                                                           File "C:\temp\demo\pygameextra\mouse.py", line 65, in wrap                                                              File "C:\temp\demo\pygameextra\context.py", line 166, in run                                                            File "C:\temp\demo\pygameextra\context.py", line 92, in _loop                                                           File "C:\temp\demo\engine\SceneContext.py", line 87, in loop                                                            File "C:\temp\demo\universal\game_state.py", line 469, in check_slots                                                   File "C:\temp\demo\universal\game_state.py", line 142, in __enter__                                                   RuntimeError: f_trace is not writable in Nuitka```

**Comment by JustRedTTG** [comment]
nuitka-action latest nuitka, python 3-11 on windows, dist (standalone) AS EXTRA CONTEXT

**Comment by kayhayen** [comment]
In the template, we have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that we do not want to be left guessing. For you it's easy to erase the issue template and expect us to ask you questions only as necessary, but we cannot do that. We would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore we are  likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
