### ISSUE TITLE
Nuitka Multi Thread support

### ISSUE THREAD

**Issue by ABD-Z** [Nuitka/Nuitka#2836]
Hello Mister Kay,

I just want to have clarification about Multi Threading support in Nuitka. 
Three years ago I'v opened an issue (https://github.com/Nuitka/Nuitka/issues/1087) stating that multi threading was slow. You suggested to take developement branch with Python 3.9. So I wanted to know how threading is going with Nuitka nowadays in 2024. Is main branch (the on who is downloa via pip install) supports threading pefectly ? What is the best configuration on a Linux Debian 4.9 (Python version, Nuitka version, etc..)

Besten Regards

**Comment by kayhayen** [comment]
Yes
