### ISSUE TITLE
After using Nuitka to package pyside6 into exe, the drag and drop file function has failed

### ISSUE THREAD

**Issue by zhenzi0322** [Nuitka/Nuitka#2839]
Example:

```python
from PySide6.QtWidgets import QApplication, QMainWindow, QListWidget
from PySide6.QtCore import Qt

class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Drag and Drop Example")
        self.setAcceptDrops(True)

        self.list_widget = QListWidget(self)
        self.setCentralWidget(self.list_widget)
        print(self.acceptDrops())

    def dragEnterEvent(self, event):
        if event.mimeData().hasUrls():
            event.acceptProposedAction()

    def dropEvent(self, event):
        for url in event.mimeData().urls():
            file_path = url.toLocalFile()
            print("Dropped file:", file_path)
            self.list_widget.addItem(file_path)


if __name__ == "__main__":
    app = QApplication([])
    window = MainWindow()
    window.setGeometry(100, 100, 400, 300)
    window.show()
    app.exec()
```

It is possible to drag and drop files normally without packaging. After packaging, I found that I couldn't drag it anymore

**Comment by KRRT7** [comment]
![image](https://github.com/Nuitka/Nuitka/assets/106575910/a24294ab-7346-460b-94ec-c856f59aa51b)
are you using the latest version of nuitka? it works fine for me

**Comment by zhenzi0322** [comment]
nuitka==1.8

**Comment by KRRT7** [comment]
upgrade to the latest Nutika and try again, `python -m pip install --upgrade nuitka`

**Comment by zhenzi0322** [comment]
> upgrade to the latest Nutika and try again, `python -m pip install --upgrade nuitka`

Hello, I have updated to the latest version 2.2.1. If the parameter - windows uac admin is added for packaging, it will result in the inability to drag and upload files.


Draggable commands:
```
nuitka --standalone --onefile --show-progress --plugin-enable=pyside6 --disable-ccache --output-filename="demo" app.py
```

Command that cannot drag and drop file uploads：
```
nuitka --standalone --onefile --show-progress --plugin-enable=pyside6 --windows-uac-admin --disable-ccache --output-filename="demo3" app.py
```

--Isn't the Windows uac admin parameter giving the application administrator privileges? Why does it not support dragging and dropping file uploads?

**Comment by KRRT7** [comment]
> > upgrade to the latest Nutika and try again, `python -m pip install --upgrade nuitka`
> 
> Hello, I have updated to the latest version 2.2.1. If the parameter - windows uac admin is added for packaging, it will result in the inability to drag and upload files.
> 
> Draggable commands:
> 
> ```
> nuitka --standalone --onefile --show-progress --plugin-enable=pyside6 --disable-ccache --output-filename="demo" app.py
> ```
> 
> Command that cannot drag and drop file uploads：
> 
> ```
> nuitka --standalone --onefile --show-progress --plugin-enable=pyside6 --windows-uac-admin --disable-ccache --output-filename="demo3" app.py
> ```
> 
> --Isn't the Windows uac admin parameter giving the application administrator privileges? Why does it not support dragging and dropping file uploads?

![image](https://github.com/Nuitka/Nuitka/assets/106575910/074dffc6-5654-4ec8-858e-cde52399353e)
as you can see, it works with windows-uac-admin as well, check that your AV isn't interfering with your program

**Comment by zhenzi0322** [comment]
If I add the -- windows uac admin parameter to my package, I won't be able to drag and drop files. If I don't add it, I can drag and drop files

**Comment by KRRT7** [comment]
my examples are both with and without the windows uac admin parameter, they both work for me as shown.

**Comment by zhenzi0322** [comment]
ok
