### ISSUE TITLE
[Question] Am I using this flag correctly? (`nofollow-import-to`)

### ISSUE THREAD

**Issue by anzhi0708** [Nuitka/Nuitka#2843]
I wrote a simple `pandas` script just to print a DataFrame to the terminal, 
but because my pip installation included optional `pandas` dependencies like `matplotlib` and `sqlalchemy`, Nuitka compiled them as well. 
As a result, I used `--nofollow-import-to=matplotlib --nofollow-import-to=sqlalchemy` to exclude them, **and the final size of the compiled EXE file was reduced by about 30%.**

However, I have a few questions. 
(1) In the official documentation, the `--nofollow-import-to` flag seems to be followed by a glob expression. 
(2) The lowercase 'sqlalchemy' I used here does not match the library name seen in `pip freeze`, but it seems to have worked anyway?

**Comment by kayhayen** [comment]
1. True, it accepts patterns. I added that to the help output. We do not have a user manual section yet, that explains things about module inclusion, we are going to add it eventually from the help output.

2. Module names and distribution names are different for some packages indeed. Nuitka Options accept one or the other.
