### ISSUE TITLE
Crash with sklearn

### ISSUE THREAD

**Issue by qiangxinglin** [Nuitka/Nuitka#2848]
> python -m nuitka --version
```
2.2.1
Commercial: None
Python: 3.10.14 (main, Mar 20 2024, 14:08:13) [MSC v.1939 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Program Files\Python39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\cl.exe (cl 14.1).
```

- How did you install Nuitka and Python

  venv, then `pip install -U nuitka`

- The specific PyPI names and versions

```
grpc-interceptor==0.15.4
grpcio==1.62.1
imageio==2.34.1
joblib==1.4.2
lazy_loader==0.4
networkx==3.2.1
Nuitka==2.2.1
numpy==1.23.5
opencv-contrib-python==4.9.0.80
opencv-python==4.9.0.80
openvino==2023.3.0
openvino-telemetry==2024.1.0
ordered-set==4.1.0
packaging==24.0
pillow==10.2.0
protobuf==4.25.3
PyWavelets==1.6.0
PyYAML==6.0.1
scikit-image==0.20.0
scikit-learn==1.4.2
scipy==1.9.1
threadpoolctl==3.5.0
tifffile==2024.5.10
zstandard==0.22.0
```

- Many times when you get an error from Nuitka, your setup may be special

  `hello world` work.

- Note if this is a regression

  Yes, `nuitka==1.0.6` works

[nuitka-crash-report.zip](https://github.com/Nuitka/Nuitka/files/15293390/nuitka-crash-report.zip)

**Comment by kayhayen** [comment]
I managed to reproduce this, hard submodule imports of `sklearn` were created without keeping the exception exit annotated that was suspected initially.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment]
This is part of the 2.2.2 hotfix I just made.
