### ISSUE TITLE
Error: problem with dependency scan of '/usr/local/lib/libcrypto.dylib' with '/usr/local/opt/openssl@3/lib/libcrypto.3.dylib' please report the bug

### ISSUE THREAD

**Issue by LorenEteval** [Nuitka/Nuitka#2853]
Error while building PySide6 application using QtNetwork with nuitka on intel macbook.

I've made it to a minimal reproducible example `main.py`:

```python
from PySide6 import QtCore
from PySide6.QtWidgets import *
from PySide6.QtNetwork import *

import functools


def handleFinishedByNetworkReply(networkReply):
    print('finished')


app = QApplication()

manager = QNetworkAccessManager()
reply = manager.get(QNetworkRequest(QtCore.QUrl('http://cp.cloudflare.com/')))
reply.finished.connect(
    functools.partial(
        handleFinishedByNetworkReply,
        reply,
    )
)

window = QMainWindow()
window.show()

app.exec()

```

Nuitka version (installed via `pip install "nuitka==2.2.1"` in a freshly created venv):

```
2.2.1
Commercial: None
Python: 3.11.8 (v3.11.8:db85d51d3e, Feb  6 2024, 18:02:37) [Clang 13.0.0 (clang-1300.0.29.30)]
Flavor: CPython Official
Executable: /.../nuitka-bug-report/.venv/bin/python
OS: Darwin
Arch: x86_64
macOSRelease: 13.6.6
```

Output of `python -m pip freeze`:

```
Nuitka==2.2.1
ordered-set==4.1.0
PySide6-Essentials==6.5.3
shiboken6==6.5.3
zstandard==0.22.0
```

Command to build:

```
python -m nuitka --standalone --plugin-enable=pyside6 --disable-console --macos-create-app-bundle main.py --output-dir=nuitka
```

Nuitka log:

```
Nuitka-Options: Used command line options: --standalone --plugin-enable=pyside6 --disable-console --macos-create-app-bundle main.py --output-dir=nuitka
Nuitka:WARNING: For GUI applications, you ought to specify an icon with '--macos-app-icon'.", otherwise a dock icon may not be present.
Nuitka: Starting Python compilation with Nuitka '2.2.1' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:anti-bloat: Not including '_bisect' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka-Plugins:anti-bloat: Not including 'socket' automatically in order to avoid bloat, but this may cause: can break calls of 'email.utils.make_msgid()'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.              
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: clang (clang 15.0.0).
Nuitka-Scons: Backend linking program with 12 files (no progress information available for this stage).
Nuitka-Scons: Compiled 12 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache miss': 12
Nuitka-Plugins:pyside6: Including Qt plugins 'iconengines,imageformats,platforms,styles,tls' below 'PySide6/qt-plugins'.
Nuitka-Inclusion: Not including forbidden DLL '/.../nuitka-bug-report/.venv/lib/python3.11/site-packages/PySide6/Qt/plugins/imageformats/libqpdf.dylib'.
Nuitka-Inclusion: Not copying forbidden DLL 'nuitka/main.app/Contents/MacOS/PySide6/qt-plugins/imageformats/libqpdf.dylib'.
FATAL:     Error, problem with dependency scan of '/usr/local/lib/libcrypto.dylib' with '/usr/local/opt/openssl@3/lib/libcrypto.3.dylib' please report the bug.
```

I've also tested that this error pops up with `nuitka 1.9`, but not with `nuitka 1.8.6`.

**Comment by kayhayen** [comment]
It seems you have Homebrew in PATH, don't do that. For CPython, Nuitka will pick up system DLLs and believe this one to be necessary.

**Comment by LorenEteval** [comment]
Sorry @kayhayen , but I cannot reproduce this on arm64 macOS (specifically mac mini, having Homebrew on PATH).

I did a quick test based on runners using Github Actions. According to [Github Document](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories), `macos-11`, `macos-12` and `macos-13` are `x86_64`-based of macOS, while `macos-14` is `arm64`-based of macOS. Then just define job steps to run the exact build procedure this issue addressed before on the OS-matrix. The test result is [here](https://github.com/LorenEteval/nuitka-bug-report/actions/runs/9080130077).

As you can see, for jobs on `macos-14`, which have Homebrew in PATH (verified by `Get Homebrew version` step, the same on other OS), but nuitka didn't give any errors. However for jobs on `x86_64`-based macOS, the job succeeded with `nuitka 1.8.6`, but not with `nuitka 1.9` and `nuitka 2.2.1`, and gave the error this issue aimed to report.

Does that mean this is an exception specifically for `x86_64`-based macOS? Should I continue on this issue or reopen another?

**Comment by twstagg** [comment]
@LorenEteval @kayhayen 

This fixed it for me with the Github provided runners, given that you do this before your Nuitka step:
```
      # Remove problematic brew libs if Intel Mac
      - name: Remove problematic brew libs
        run: |
          brew remove --force --ignore-dependencies openssl@3
          brew cleanup openssl@3
        if: runner.os == 'macos' && matrix.arch == 'i386'
```

**Comment by kayhayen** [comment]
With Homebrew, it's "lib" directory has to be added, and for amd64, this is clearly separated from the rest of the OS, but I am not so sure for x86_64, there it was probably very dirty. Since Homebrew is not what is recommended for portable distributions anyway, I don't think I will want to make it work if it's effort to pull hairs between OS and Homebrew DLLs not being clearly sorted. I think CPython should be used rather than Homebrew, since that gives maximum portability. Homebrew typically is not backward portable, CPython and PyPI are better at that, maybe, although I wouldn't swear on it.

**Comment by kayhayen** [comment]
I am tempted to disallow standalone on Homebrew with x86_64, since it's a trap only, but maybe I am all wrong, and the /usr/local/lib is not an OS folder at all, is it?
