### ISSUE TITLE
PySide6: Error when packaging QtQuick application

### ISSUE THREAD

**Issue by shyamnathp** [Nuitka/Nuitka#2854]
I am trying to package a PySide6 QtQuick/QML application with Nuitka and I get the following error

`FATAL: Error, cannot use file '/Users/qt/shyam/pyside-setup/venv_11_0/lib/python3.11/site-packages/PySide6/Qt/qml/QtQuick/Controls/macOS/images/busyindicator-dark.webp' (RIFF (little-endian) data, Web/P image) to build arch 'x86_64' result`

For macOS, the qml plugins include 4 .webp files which should also be bundled along with the application. I believe the error is because Nuitka considers these files to be dlls and not data files. This is also seen in the attached error report obtained by running Nuitka with '--report=nuitka_error.txt'

Command run:

`python -m nuitka /Users/qt/shyam/test_wheels/qml_test/main.py --follow-imports --enable-plugin=pyside6 --verbose --noinclude-qt-translations --static-libpython=no --noinclude-dlls=*/QtQuickEffectMaker/* --standalone --macos-create-app-bundle --include-data-files=/Users/qt/shyam/test_wheels/qml_test/main.qml=./main.qml --macos-app-icon=/Users/qt/shyam/test_wheels/venv_10_9/lib/python3.10/site-packages/PySide6/scripts/deploy_lib/pyside_icon.icns --include-qt-plugins=accessiblebridge,networkaccess,networkinformation,platforminputcontexts,platforms/darwin,qml,qmltooling,scenegraph`

The error goes away when i add "--noinclude-dlls=*.webp" to the above command. Is it possible to consider .webp files as data files so that the files can be bundled together with the application?

Nuitka Version: 
`2.1
Commercial: None
Python: 3.11.0 (v3.11.0:deaf509e8f, Oct 24 2022, 14:43:23) [Clang 13.0.0 (clang-1300.0.29.30)]
Flavor: CPython Official
Executable: /Users/qt/shyam/pyside-setup/venv_11_0/bin/python
OS: Darwin
Arch: x86_64
Version C compiler: /usr/bin/clang (clang 14.0.3).`
[nutika_error.txt](https://github.com/Nuitka/Nuitka/files/15308626/nutika_error.txt)

**Comment by kayhayen** [comment]
The 2.1 version is relatively old and you lack a minimal reproducer.

**Comment by kayhayen** [comment]
I still don't see a reproducer, apparently this about a new PySide6 release, but your low quality report never stated even package versions.

**Comment by kayhayen** [comment]
Ok, fair enough, the compilation report has those versions, but without a reproducer, I do not really care to create one myself.

**Comment by kayhayen** [comment]
But self-built PySide6, I don't know how good it is. In the mean time, I will be looking at supporting the 6.7.0 which gives me a errors with my standard QML test case.

**Comment by kayhayen** [comment]
Nuitka 2.2.3 works fine for me now.
