### ISSUE TITLE
Whether or not there is an interest in adding a packaged configuration file

### ISSUE THREAD

**Issue by Dozingfiretruck** [Nuitka/Nuitka#2857]
Whether or not there is an interest in adding a packaged configuration file?

like pyinstaller .spec file ，Using the command line is cumbersome, the configuration files are more convenient，
pyside6 has pyside6-deploy support .spec file,it is convenient

**Comment by Maxwell175** [comment]
Nuitka already has the ability to read command line options from comments within the Python file that you point it at. See an example here: https://nuitka.net/user-documentation/user-manual.html#splash-screen

Unfortunately there is no separate documentation section for it at this time.

**Comment by kayhayen** [comment]
Currently it's well hidden in https://nuitka.net/user-documentation/tips.html#nuitka-options-in-the-code but I agree, it should be in the user manual, and only pointed out there.

**Comment by Dozingfiretruck** [comment]
It's very easy to use, and it would be great if the documentation was better, haha

**Comment by kayhayen** [comment]
I am doing rewordings of the documentation, and as part of it, I did the tips section today, stripping it down, and moving its previous and enhanced contents to user manual as a new section. Lots of work with proper split still to do.
