### ISSUE TITLE
Invoking wintypes during packaging causes the program to fail to run.

### ISSUE THREAD

**Issue by eamon-cai** [Nuitka/Nuitka#2863]
Nuitka version, full Python version, flavor, OS, etc. as output by this exact command.

        (v5lite) PS D:\Code\Python\v5lite> python -m nuitka --version
        2.2.2                                                                                                                                                                               
        Commercial: None
        Python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
        Flavor: CPython Official
        Executable: C:\Users\Eamon\.virtualenvs\v5lite-wtluHURw\Scripts\python.exe
        OS: Windows
        Arch: x86_64
        WindowsRelease: 10
        Version C compiler: C:\App\ccache\cache\downloads\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0).

How did you install Nuitka and Python
        pipenv install  nuitka

The specific PyPI names and versions
        Nuitka==2.2.2

When I package a module, let's assume the file is named a.py. Inside a.py, I use from ctypes import wintypes. Now, I package it into a.pyd. In another project, let's call it project B, I reference a.pyd. When I package project B, everything goes smoothly, but during runtime, it stops at from ctypes import wintypes, and no error is caught. However, using import wintypes alone does not cause it to stop running.

Before packaging:
import ctypes
import math
from ctypes import wintypes
After packaging:
import ctypes as ctypes # C:\Users\Eamon\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py
import math as math # <module 'math' (built-in)>
import os as os # C:\Users\Eamon\AppData\Local\Programs\Python\Python310\lib\os.py
import ctypes.wintypes as wintypes # C:\Users\Eamon\AppData\Local\Programs\Python\Python310\lib\ctypes\wintypes.py

**Comment by kayhayen** [comment]
The implicit dependencies are in `.pyi` files. Be sure to have them visible. There recently was an issue about hard imports not listed as dependencies, and it got fixed for 2.3, so just use develop.

**Comment by eamon-cai** [comment]
I used the development board Nuitka. When packaging, the generated .pyi file seems to still lack the necessary libraries, such as os. I have to manually supplement them.

**Comment by kayhayen** [comment]
I am not sure you have provided a minimal reproducer, so I can understand what you are trying to do at all. My guess would have to be wrong then, but that's not my fault.
