### ISSUE TITLE
One-file exe work well local side, work not good on network path.

### ISSUE THREAD

**Issue by GelzoneCC** [Nuitka/Nuitka#2864]
I made a tool for web crawler (not use --headless mode) and use nuitka to make it an one-file .exe file with:
`nuitka --lto=no --standalone --plugin-enable=pyqt5 --onefile --include-package-data=selenium --disable-console --output-dir=BIOS --remove-output --windows-icon-from-ico=webcrawler.ico WindowController.py`

After make it an .exe file (without window console), it works fine at local side (e.g. my PC) (work fine means it can display the GUI I created with Pyqt5 and press the button on it to show the browser and do the crawler task). But when I move the .exe from local to the network path (e.g. \\srv\folder\python\crawler.exe) and run, it can jsut show the GUI and unable to do the crawler task (did not show the browser when press the button).

I thought maybe the disable console instruction caused the issue so I tried to remove the `--disable-console` and made .exe again.
After this, it works well both on local side and the network path. Although it can work on network path, it is still annoying there is a window console when users use it. So I want to figure it out why/what will cause this issue? 
*(For some reasons, I prefer run the .exe on the network path.)

I have also tried `nuitka 1.8.6` and `nuitka 2.1.3` but got the same result.

I guess the issue will be relative with `Seleium 4.10.0` and `webdriver-manager 4.0.1` because my previous tool without these 2 packages didn't cause the "window console" issue on the network path. Here is code snippet:

```
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

chrome_service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service = chrome_service)
```

### Main Python Package
Nuitka                       2.2
numpy                      1.25.1
openpyxl                   3.0.10
pandas                      1.5.3
PyQt5                        5.15.9
selenium                   4.10.0
webdriver-manager  4.0.1

### Nuitka
2.2
Commercial: None
Python: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: D:\PyWorkSpace\Python_Project\venv_UITool\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\cl.exe (cl 14.1).

**Comment by kayhayen** [comment]
Can you before reporting a Nuitka issue first make sure the Python program works when used in the same way? Or if that is not possible, reduce the issue to something that is reproducible by me without too much effort. If you can e.g. demonstrate the the forking of some executable on a network path works in Python but not in Nuitka on a network path, that would be a report, but I am not going to go out and figure out what your issue is for you between these things. I guess using a virtualenv on a network and demonstrating that to work might be enough there, provided the drivers are download to in in there too.

**Comment by GelzoneCC** [comment]
Thank for your reply. I will try to make a easy script to test what I have mentioned.
Briefly, 

- the tool with `--disable-console`: 

1. local side: able to open the GUI and do crawler tasks
2. network path: able to open the GUI but unable to do crawler tasks

- the tool without `--disable-console`:

1. Both local side and network path are able to open the GUI and do the crawler tasks

So, based on the scenario, I just thought if the `--disable-console` got conflict with `Selenium 4.10` and `webdriver-manager 4.0.1`.
Anyway, I will use a easy script to test in a few days.

**Comment by kayhayen** [comment]
Don't make promises about what you will do, tell what you done in the next issue you open with the information gathered.
