### ISSUE TITLE
Failed to initialize QMediaPlayer "Not available"

### ISSUE THREAD

**Issue by jinwa7262** [Nuitka/Nuitka#2866]
Works fine before packaging with Nuitka, error after packaging with Nuitka: No QtMultimedia backends found. Only QMediaDevices, QAudioDevice, QSoundEffect, QAudioSink, and QAudioSource are available.
Failed to initialize QMediaPlayer "Not available", causing mp3 files to not play normally
After checking, it is because the two dll files in PySide6\plugins\multimedia\ cannot be found, but I copied the multimedia directory to PySide6\plugins\ and it still doesn't work.
The command I use is: Nuitka --standalone --enable-plugin=pyside6 mainForm.py

Nuitka-Options: Used command line options: --standalone --enable-plugin=pyside6 mainForm.py
Nuitka:WARNING: The Python version '3.12' is only experimentally supported by Nuitka '2.2.2', but an upcoming release will change that. In the mean time use Python version '3.11' instead or newer Nuitka.
Nuitka: Starting Python compilation with Nuitka '2.2.2' on Python '3.12' commercial grade 'not installed'.
Nuitka-Plugins:options-nanny: Note, when using 'PySide6', consider using '--disable-console' option. Otherwise a terminal window will open. However for debugging, terminal output is the easiest way to see
Nuitka-Plugins:options-nanny: informative traceback and error information, so delay this until your program is working and remove once you find it non-working, and use '--enable-console' to make it explicit
Nuitka-Plugins:options-nanny: and not see this message.
Nuitka: Completed Python level compilation and optimization.     
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.      
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: cl (cl 14.3).
Nuitka-Scons: Backend linking program with 104 files (no progress information available for this stage).
Nuitka-Scons: Compiled 104 C files using clcache with 104 cache hits and 0 cache misses.
Nuitka-Plugins:pyside6: Including Qt plugins 'iconengines,imageformats,platforms,styles,tls' below 'PySide6\qt-plugins'.
Nuitka-Plugins:data-files: Included data file 'certifi\cacert.pem' due to package data for 'certifi'.         
Nuitka: Keeping build directory 'mainForm.build'.
Nuitka: Successfully created 'mainForm.dist\mainForm.exe'.

**Comment by kayhayen** [comment]
In the template, we have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that we do not want to be left guessing. For you it's easy to erase the issue template and expect us to ask you questions only as necessary, but we cannot do that. We would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore we are  likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
