### ISSUE TITLE
After encountering threading, the following code will not be executed.

### ISSUE THREAD

**Issue by lrq51678** [Nuitka/Nuitka#2867]
import os
import base64
import json
import os.path
import random
import struct
import threading
import socket
import time
import traceback
import psutil
import paths as p

print('-3-')
threading.Thread(target=self.sendTTS).start()
print('-4-')

Hello, after executing the threading statement, it will not be executed print('-4-'),But it's always executing methods within the thread。
My nuitka version is 2.1.4 ，Python 3.11.5

The nuitka statement is :
nuitka --module --lto=no --mingw64 --show-progress --show-memory --include-module=paths  --output-dir=outputStudioService StudioService.py

**Comment by lrq51678** [comment]
The program did not report any errors and has been hanging there ever since

**Comment by kayhayen** [comment]
Old Nuitka, and no reproducer. 

In the template, we have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that we do not want to be left guessing. For you it's easy to erase the issue template and expect us to ask you questions only as necessary, but we cannot do that. We would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore we are  likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
