### ISSUE TITLE
i want to increase recursion limit

### ISSUE THREAD

**Issue by furjac** [Nuitka/Nuitka#2870]
How to increase recursion limit there is problem like idk where its gettung when i changed the recursion limit in code its working but after compiling to exe using nuitka this happens but pyinstaller spec file import sys and changing the recursion limit working 
help me out

**Comment by kayhayen** [comment]
Nuitka doesn't respect the recursion limit itself, and changing it in `sys` will only affect bytecode, so why do it?

**Comment by furjac** [comment]
i dont know it still occurs the error exist when i use the tempfile module

**Comment by furjac** [comment]
@kayhayen this is my repo i was trying to use on https://github.com/furjac/FG_Torrents

**Comment by furjac** [comment]
![image](https://github.com/Nuitka/Nuitka/assets/81816200/acff61ed-282b-495f-ab49-01cedb83d17f)
see this for example

**Comment by furjac** [comment]
fixed it it was just os.chdir problem
