### ISSUE TITLE
Testing Nuitka '2.3rc5' Python 3.12.3 Windows 10, still doesn't work

### ISSUE THREAD

**Issue by Dnyarri** [Nuitka/Nuitka#2871]
Ok, tried to test newest Nuitka develop,

Nuika develop Nuitka '2.3rc5'
Git commit:
08670ba200ac3059babe1f363e8f6f1d9a5fe66a
New pre-release.
date 18 May 18:51

OS: Windows 10

File to be compiled: may be dowloaded from https://github.com/Dnyarri/PixelArtScaling
more precisely it's Scale2x.py

Now things that work:
py -3.11 --version
Python 3.11.9 

compile command:
py -3.11 D:\Nuitka\bin\nuitka --onefile --onefile-no-compression --prefer-source-code --clean-cache=all --force-dll-dependency-cache-update --output-dir="D:\Temp" --remove-output --enable-plugin=tk-inter --windows-console-mode=disable --windows-icon-from-ico="D:\Ilyich\Python\PixelArtScaling\2x.ico" --include-data-file="D:\Ilyich\Python\PixelArtScaling\2x.ico"="2x.ico" --company-name="AmphiSoft" --product-name="ScaleNx" --file-version=2024.05.17.20 --product-version=2024.05.17.20 --file-description="Scale2x image resizer" --copyright="amphisoft@gmail.com" "D:\Ilyich\Python\PixelArtScaling\Scale2x.py"

result: compile ok, everything works, dialog pops up, I select PNG image to rescale, program works, asks me for the filename to save, saves, exits, new PNG is saved, resized as requested, resolution doubled, no junk introduced, no error message received, everything as I want it to be. Currenly resulting exe may be dowloaded from "Release" section of github repo above by anyone interested in upscaling their pictures with ScaleNx algorithms.

Now things that doesn't work:

same machine, the only Nuitka

py -3.12 --version 
Python 3.12.3

compile command:

in command above changed "py -3.11" to "py -3.12"

Nuitka: Starting Python compilation with Nuitka '2.3rc5' on Python '3.12' commercial grade 'not installed'.
...
Nuitka-Scons: Backend C compiler: gcc (gcc 13.2.0).
...
Nuitka: Successfully created 'D:\Temp\Scale2x.exe'. 

result: compile ok, nothing works. When starting Scale2x.exe thus obtained, nothing happens. Ok, change "--windows-console-mode=disable" to "--windows-console-mode=force". When starting Scale2x.exe thus obtained, empty console appears, then disappears without saying a word.

Now, basically, that all what happens. Or doesn't.

PS: forgot to add, initially it was without " --prefer-source-code", and didn't work as well, I just tried " --prefer-source-code" just in case, but nothing changed. At least nothing visible.

**Comment by kayhayen** [comment]
Without a narrowed down reproducer, this is unfortunately a useless report.

**Comment by Dnyarri** [comment]
I beleived I offered as much info as possible, including link to source .py file. What else can I provide to help?

**Comment by kayhayen** [comment]
You can narrow it down to the failing part. I cannot execute large bodies of foreign code for security reasons and I cannot debug them manually in search of an issue. That would be your task.

**Comment by Dnyarri** [comment]
Ok, since I have no idea how can I "narrow" such a small program like mine, I did nothing but waited. Yesterday I repeated git pull --all --force as always, and now I have commit ebe35680b7dce34d420d381035ac749778b7a9b3 installed. Everything works fine - same bat for compile, same Python 3.12.3, same programs, only thing changed is Nuitka 2.3rc6. Haven't done speed tests yet, but compiled programs do exactly what I want them to do without any problem.

So I cannot provide more detail regarding what exactly did not work previously, but, since it works now, I guess you may close this issue since it's not relevant anymore.

**Comment by kayhayen** [comment]
Yeah, I fixed something that might have affected your code.
