### ISSUE TITLE
The exe file is not copied for the command --include-data-dir

### ISSUE THREAD

**Issue by Dozingfiretruck** [Nuitka/Nuitka#2876]
![image](https://github.com/Nuitka/Nuitka/assets/24759100/a95191ab-47dd-43a1-a85e-ea734f099fbc)
![image](https://github.com/Nuitka/Nuitka/assets/24759100/fca717e9-c781-4657-8b82-88a6e005addf)
only copy bdfconv, the bdfconv.exe is not copied

**Comment by KRRT7** [comment]
you will have to add via a yaml config 
https://nuitka.net/user-documentation/nuitka-package-config.html
for an example on how to do it you can refer to
https://github.com/Nuitka/Nuitka/blob/develop/nuitka/plugins/standard/standard.nuitka-package.config.yml#L4618-L4624

**Comment by kayhayen** [comment]
I added this recently should be a good reference pointer https://nuitka.net/user-documentation/user-manual.html#code-is-not-data-files and let me know if there is something missing.
