### ISSUE TITLE
PkgResourcesPlugin.py not support python3.8??

### ISSUE THREAD

**Issue by Forrest-ly** [Nuitka/Nuitka#2878]
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure that is intended.
Nuitka: Starting Python compilation with Nuitka '2.2.3' on Python '3.8' commercial grade 'not installed'.
Nuitka-Plugins:pkg-resources: Detected easy install entry script, compile time detecting entry point.
Traceback (most recent call last):
  File "/usr/local/lib64/python3.8/site-packages/nuitka/plugins/Plugins.py", line 69, in withPluginProblemReporting
    yield
  File "/usr/local/lib64/python3.8/site-packages/nuitka/plugins/Plugins.py", line 973, in onModuleSourceCode
    new_source_code = plugin.onModuleSourceCode(
  File "/usr/local/lib64/python3.8/site-packages/nuitka/plugins/standard/PkgResourcesPlugin.py", line 93, in onModuleSourceCode
    return self._handleEasyInstallEntryScript(*match.groups())
  File "/usr/local/lib64/python3.8/site-packages/nuitka/plugins/standard/PkgResourcesPlugin.py", line 55, in _handleEasyInstallEntryScript
    module_name = entry_point.module
AttributeError: 'EntryPoint' object has no attribute 'module'

[root@j38d05411 /]# python3 -m nuitka --version
2.2.3
Commercial: None
Python: 3.8.12 (default, Aug 10 2022, 11:16:29)
Flavor: Fedora Python
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
Distribution: Alinux (based on Fedora) 3
Version C compiler: /usr/bin/gcc (gcc 10).

[root@j38d05411 /]# python3 --version
Python 3.8.12

**Comment by kayhayen** [comment]
In the template, we have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that we do not want to be left guessing. For you it's easy to erase the issue template and expect us to ask you questions only as necessary, but we cannot do that. We would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore we are  likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."

**Comment by kayhayen** [comment]
This might be fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by Forrest-ly** [comment]
Sorry for this. The factory branch works fine for me,  thank you !

**Comment by kayhayen** [comment]
Part of the 2.3 release.
