### ISSUE TITLE
Question: How to compile a .pyc file directly (without the source .py)?

### ISSUE THREAD

**Issue by jcrmatos** [Nuitka/Nuitka#288]
Would it be possible to compile a .pyc file directly (without the source .py)?
This would be great for compiling the bytecode modules developed with web2py.

**Comment by kayhayen** [comment]
I don't have the answer, but suppose this works on it:

https://pypi.org/project/uncompyle6/

Please report if that is indeed the case. Then we can consider this as the standard solution to the issue. I am curious my self, but I lack the time during GSoC @jcrmatos

**Comment by jcrmatos** [comment]
uncompyle6 doesn't compile from .pyc. What it tries to do is to decompile a .pyc to a .py.
Unfortunately it doesn't work with my sources, it returns several errors and nevers outputs a .py file.

**Comment by kayhayen** [comment]
The idea was `.pyc` -> `.py` -> `.exe | .pyd | .so` where Nuitka would do the last step. For the first step we apparently don't have a solution yet.
