### ISSUE TITLE
spacy dependencies failure

### ISSUE THREAD

**Issue by kmn1024** [Nuitka/Nuitka#2889]
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

2.2.3
Commercial: 2.5.1
Python: 3.11.9 (main, Apr 19 2024, 16:39:34) [GCC 11.2.0]
Flavor: Anaconda Python
Executable: /home/orangepi/miniconda3/envs/theplatform_ov_prod/bin/python
OS: Linux
Arch: aarch64
Distribution: Ubuntu (based on Debian) 22.04.3
Version C compiler: /usr/bin/gcc (gcc 11).

- How did you install Nuitka and Python

python -m pip install -U --force-reinstall https://XXX@github.com/Nuitka/Nuitka-commercial/archive/main.zip

- The specific PyPI names and versions

...
blis                      0.7.11
Nuitka                    2.2.3
preshed                   3.0.9
spacy                     3.7.4
spacy-legacy              3.0.12
spacy-loggers             1.0.5
thinc                     8.2.3
...

- Also supply a Short, Self Contained, Correct, Example

Simple program `spacy_test.py`:
```
import spacy

nlp = spacy.load("en_core_web_sm", disable=["ner", "parser"])
tokens = list(nlp("This is a very good test."))
print([(token.text, token.pos_) for token in tokens])
```

Expected output:
`[('This', 'DET'), ('is', 'AUX'), ('a', 'DET'), ('very', 'ADV'), ('good', 'ADJ'), ('test', 'NOUN'), ('.', 'PUNCT')]`

Compile command (I came up with this based on other issues filed related to spacy):
`python -m nuitka --follow-imports --standalone --include-package=spacy,en_core_web_sm,thinc,blis,preshed  --include-package-data=spacy,en_core_web_sm  spacy_test.py`

Even with the command above, there were lots of missing dependencies, and I had to do the following:
```
cd spacy_test.dist/
SITE_PKGS_DIR=/home/orangepi/miniconda3/envs/myconda/lib/python3.11/site-packages

cp $SITE_PKGS_DIR/thinc/backends/_custom_kernels.cu thinc/backends/
cp $SITE_PKGS_DIR/thinc/backends/linalg.cpython-311-aarch64-linux-gnu.so thinc/backends/
cp $SITE_PKGS_DIR/spacy/parts_of_speech.cpython-311-aarch64-linux-gnu.so spacy/
cp $SITE_PKGS_DIR/spacy/default_config.cfg spacy/
cp $SITE_PKGS_DIR/spacy/pipeline/transition_parser.cpython-311-aarch64-linux-gnu.so spacy/pipeline/
cp $SITE_PKGS_DIR/spacy/pipeline/_parser_internals/stateclass.cpython-311-aarch64-linux-gnu.so spacy/pipeline/_parser_internals/
cp $SITE_PKGS_DIR/spacy/pipeline/_parser_internals/transition_system.cpython-311-aarch64-linux-gnu.so spacy/pipeline/_parser_internals/
cp $SITE_PKGS_DIR/spacy/pipeline/_parser_internals/_beam_utils.cpython-311-aarch64-linux-gnu.so spacy/pipeline/_parser_internals/
cp $SITE_PKGS_DIR/spacy/pipeline/_parser_internals/arc_eager.cpython-311-aarch64-linux-gnu.so spacy/pipeline/_parser_internals/
cp $SITE_PKGS_DIR/spacy/pipeline/_parser_internals/ner.cpython-311-aarch64-linux-gnu.so spacy/pipeline/_parser_internals/
mkdir -p spacy/cli/templates/
cp $SITE_PKGS_DIR/spacy/cli/templates/quickstart_training_recommendations.yml spacy/cli/templates/
mv en_core_web_sm/en_core_web_sm-3.7.1/* en_core_web_sm/
```

Now, I am still stuck, with this error:
```
Traceback (most recent call last):
  File "/home/orangepi/platform/theplatform/spacy_test.dist/spacy_test.py", line 3, in <module>
  File "/home/orangepi/platform/theplatform/spacy_test.dist/spacy/__init__.py", line 51, in load
  File "/home/orangepi/platform/theplatform/spacy_test.dist/spacy/util.py", line 467, in load_model
  File "/home/orangepi/platform/theplatform/spacy_test.dist/spacy/util.py", line 547, in load_model_from_path
  File "/home/orangepi/platform/theplatform/spacy_test.dist/spacy/language.py", line 2209, in from_disk
  File "/home/orangepi/platform/theplatform/spacy_test.dist/spacy/util.py", line 1390, in from_disk
  File "/home/orangepi/platform/theplatform/spacy_test.dist/spacy/language.py", line 2203, in <lambda>
  File "/home/orangepi/platform/theplatform/spacy_test.dist/spacy/pipeline/lemmatizer.py", line 304, in from_disk
  File "/home/orangepi/platform/theplatform/spacy_test.dist/spacy/pipeline/lemmatizer.py", line 173, in _validate_tables
ValueError: [E912] Failed to initialize lemmatizer. Missing lemmatizer table(s) found for mode 'rule'. Required tables: ['lemma_rules']. Found: [].
```

- Consider getting commercial support

Yes, I am a commercial customer.

**Comment by kayhayen** [comment]
Sorry, I was on a release cruch for 2.3, which is now over, this is most probably data files, I will check it out.

**Comment by kayhayen** [comment]
So we added a bunch of things on develop from a PR that @KRRT7 made, but maybe for a different issue, I will check this out.

**Comment by kayhayen** [comment]
Seems, I kind of forgot to merge said PR, but I was working on it today and we want a better integration with the models you downloaded, to discover them automatically and warn about it with a plugin dedicated to that.

**Comment by kayhayen** [comment]
So on factory, your MRE should compile without any additional options usage but a new plugin parameter from spacy that will be yelled at you.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory and staging (commercial) branches, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment]
This is now on the develop branch and will be in 2.4 release.

**Comment by HydraDragonAntivirus** [comment]
I have similar issue with spacy too but I wonder how he did manage to load en_core_web_sm

**Comment by MartinHlavna** [comment]
@HydraDragonAntivirus I have noticed there is spacy plugin. I am not using default models so I am unable to verify but you may try.

```
Plugin options of 'spacy':
    --spacy-language-model=INCLUDE_LANGUAGE_MODELS
                        Spacy language models to use. Can be specified
                        multiple times. Use 'all' to include all downloaded
                        models.

```

**Comment by HydraDragonAntivirus** [comment]
### 

> @HydraDragonAntivirus I have noticed there is spacy plugin. I am not using default models so I am unable to verify but you may try.
> 
> ```
> Plugin options of 'spacy':
>     --spacy-language-model=INCLUDE_LANGUAGE_MODELS
>                         Spacy language models to use. Can be specified
>                         multiple times. Use 'all' to include all downloaded
>                         models.
> ```
FATAL: Error, unknown plug-in 'spacy' referenced.
I'm on Windows 11 23H2 and Nuitka version is latest (2.3.11)

**Comment by HydraDragonAntivirus** [comment]
Ha now I understand. The pull request is fix this.

**Comment by kayhayen** [comment]
You should use develop branch after PR merges.

**Comment by HydraDragonAntivirus** [comment]
Until that what can we do to include en_core_web_md

**Comment by HydraDragonAntivirus** [comment]
https://www.youtube.com/watch?v=4p44xqH0TZ4 This video is so helpful. Ok let's use this argument until develop version releases it. My arguments:
`python -m nuitka --onefile --windows-icon-from-ico="C:\Users\victim\Documents\HydraDragonAntivirus\assets\HydraDragonAV.png" --windows-uac-admin --include-module=win32file --include-module=win32con --include-module=notifypy --include-module=yara --include-module=watchdog --include-module=joblib --include-package=spacy  --include-module=pefile --include-module=preshed.maps --enable-plugin=pyside6 --include-data-dir="C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages\en_core_web_md\en_core_web_md-3.7.1=en_core_web_md"  antivirus.py`

**Comment by kayhayen** [comment]
This is part of the stable release 2.4 that I just made.
