### ISSUE TITLE
Nuitka incompatibly achieves: "foo() is foo()"

### ISSUE THREAD

**Issue by pmav99** [Nuitka/Nuitka#289]
Both nuitka and Python were installed from the Archlinux repos

```
python -m nuitka --version
0.6.2
Python: 3.7.2 (default, Jan 10 2019, 23:51:51) 
Executable: /usr/bin/python
OS: Linux
Arch: x86_64
```

I was reading [this blog post](https://nullprogram.com/blog/2019/02/24/) and I thought to test `foo() is foo()` with nuitka and it seems that nuitka is (over?)optimising the `f2()` function in the following snippet:

``` python
def f1():
    return (1, 2, 3)

def f2():
    x = 1
    return (x, 2, 3)

assert f1() is f1(), 'WTF'
assert f2() is f2(), 'WTF'   # This one raises in Python 3.7
print("finished")            # Nuitka prints this
```

Realistically speaking this is a contrived edge case but nevertheless, Nuitka does have incompatible behavior.

*  If this is a regression (used to work in an earlier version of Nuitka),
   please note what you know about that.

Not sure, probably not.

**Comment by kayhayen** [comment]
This exhibits a missing optimization. I also had it with Python2.7 which I happend to try first. But f1 and f2 look perfect and identical on the C level, returning a reference to a pre-made tuple. Which ought to mean, there is no way the `is` operation can fail, yet it does.

Seems pretty serious.

**Comment by kayhayen** [comment]
No wait, actually Python2 behavior is un-optimized, and Nuitka's is, and that is correct of course. There is nothing in the language that promises much about `is` identity, so Nuitka is of course absolutely correct in optimizing this.

Also I can confirm that no version of Python fared any better. Obviously nobody will want separate tuples for what is a constant value really, so we are not considering compatibility here as trump. 

I would say that `a == b` always has to allow for `a is b` to be true.
