### ISSUE TITLE
opcua generated sources is too large for C compilers

### ISSUE THREAD

**Issue by stepa00** [Nuitka/Nuitka#2897]
Hello,

I have developed a project but one package does not allow me to compile it using Nuitka. This python package is `opcua`. It is an older no version of `asyncua` and no longer supported. However, I am not yet switching to a newer version based on `asyncio`.

## Similar issue.

https://github.com/Nuitka/Nuitka/issues/1704
I have checked already. The difference is that I am using `opcua=0.98.13` which is older version without `asyncio` features.

## System specs

```terminal
2.2.3
Commercial: None
Python: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\sttte\hmi_build\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64\cl.exe (cl 14.3).
```

## This is `Nuitka` settings.

```terminal
# nuitka-project: --standalone
# nuitka-project: --msvc=latest
# nuitka-project: --lto=no
# nuitka-project: --low-memory

## This is `Nuitka` output.

```terminal
Nuitka-Options: Used command line options: --standalone --msvc=latest --lto=no --low-memory main.py
Nuitka: Starting Python compilation with Nuitka '2.3' on Python '3.10' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.                                                       
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.                                                       
Nuitka: Running C compilation via Scons.
Nuitka-Scons: MSVC version resolved to 14.3.
Nuitka-Scons: Backend C compiler: cl (cl 14.3).
Unexpected output from this command:             
<clcache> /Fomodule.opcua.server.standard_address_space.standard_address_space_part5.obj /c "module.opcua.server.standard_address_space.standard_address_space_part5.c" /nologo /std:c11 /wd5105 /Ox /GF 
/Gy /EHsc /J /Gd /bigobj /MT /D__NUITKA_NO_ASSERT__ /D_NUITKA_STANDALONE /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=152 /D_NUITKA_EXE /D_NUITKA_PLUGIN_MULTIPROCESSING_ENABLED=1 /IC:\Users\sttte\TEST_O~1\VENV~1\Lib\SITE-P~1\nuitka\build\inline_copy\zlib /IC:\Users\sttte\AppData\Local\Programs\Python\PYTHON~2\include /I. /IC:\Users\sttte\BITROB~1\TEST_O~1\VENV~1\Lib\SITE-P~1\nuitka\build\include /IC:\Users\sttte\BITROB~1\TEST_O~1\VENV~1\Lib\SITE-P~1\nuitka\build\static_src /IC:\Users\sttte\TEST_O~1\VENV~1\Lib\SITE-P~1\nuitka\build\inline_copy\libbacktrace
C:\Users\sttte\test_opcua_package\main.build\module.opcua.server.standard_address_space.standard_address_space_part5.c(95) : fatal error C1002: compiler is out of heap space in pass 2      
scons: *** [module.opcua.server.standard_address_space.standard_address_space_part5.obj] Error 1
FATAL: Failed unexpectedly in Scons C backend compilation.
Nuitka:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/scons-backend-failure.html
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'.
```

## Dependencies.

```terminal
lxml==5.2.2
Nuitka==2.3
opcua==0.98.13
ordered-set==4.1.0
python-dateutil==2.9.0.post0
pytz==2024.1
six==1.16.0
zstandard==0.22.0
```

## How install Nuitka and Python.

Nuitka is installed using `pip` into virtualenv. Tested on smaller projects.

Python from official python website 64 bit version.

## Test code

```python
# nuitka-project: --standalone
# nuitka-project: --msvc=latest
# nuitka-project: --lto=no
# nuitka-project: --low-memory

import opcua

print('Hello, world!')
```

## Additional info

I have tried the following thing:

1. `--lto=on/off`;
2. `--jobs`;
3. `--mingw64`;
4. On linux: `--clang`;
5. Building on linux with all above mentioned options;
6. Settings from similar issue mentioned above;
7. Read "heap memory" related solution on Nuitka website: https://nuitka.net/user-documentation/common-issue-solutions.html.

In my original project I have library `asyncua` as well which is building perfectly fine.

All my tries to compile the project end up with the same error:
```
scons: *** [module.opcua.server.standard_address_space.standard_address_space_part5.obj] Error 1
```

**Comment by gdementen** [comment]
To fix this, you probably need to skip compiling (include as bytecode instead). One way to do this is to mimic the changes in the following commit but using opcua instead of asyncua:  https://github.com/Nuitka/Nuitka/commit/fa5c7d2e7ee49d7881c3cff8ca36a7953c842dcc

**Comment by kayhayen** [comment]
These modules are huge and generated from only classes, exhibiting scalability issues for the C compilers. Nuitka is not yet good at generating code that's easier for them to consume, so the solution is to treat it just the same as the other async, as @gdementen suggested. I am adding that factory and the next hotfix 2.3.1 release, once I get to it, internally I already have it.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by stepa00** [comment]
Thank you @kayhayen for such a fast response and @gdementen thank you for the suggestion. I was testing exactly the same 3 lines that @kayhayen added to factory version but on a 2.2.3 stable version of Nuitka. It works for me. 
However, I have not tried factory version.

**Comment by kayhayen** [comment]
Part of the 2.3.1 hotfix release.
