### ISSUE TITLE
Packaging Error with PyOpenGL in Editable Mode

### ISSUE THREAD

**Issue by eamon-cai** [Nuitka/Nuitka#2899]
> python -m nuitka --version

2.3
Commercial: None
Python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\\.virtualenvs\xxx-wtluHURw\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

- Provide in your issue the Nuitka options used

nuitka --standalone --clang --show-progress --output-dir=out .\opengl\test.py

When I install PyOpenGL in **editable mode**, it works and runs correctly before packaging. However, after packaging, it throws errors on specific code, such as `glut.glutInit()`. If I uninstall it and install it in normal mode, it can be packaged and run correctly. I found an issue that previously addressed this problem and it seemed to have been resolved a long time ago. 
#2356
So now I am unsure whether it is a problem with the PyOpenGL project or something else.

**Comment by kayhayen** [comment]
Are you even referring to the same editable as PDM is using there?

**Comment by eamon-cai** [comment]
I have not yet tried using PDM for package management.

Currently, I am using the latest version 3.17 of this project: [https://github.com/mcfletch/pyopengl](url)
I am using the latest versions of pip and pipenv.

When I run the following code:
```
import OpenGL.GLUT as glut
glut.glutInit()
```
It results in an error after packaging.

Additionally, the PyOpenGL_accelerate in the same project cannot be loaded after packaging:

File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
File "src\\arraydatatype.pyx", line 1, in init OpenGL_accelerate.arraydatatype
KeyError: '__reduce_cython__'

**Comment by kayhayen** [comment]
I am not sure what you mean with editable mode still.

**Comment by kayhayen** [comment]
Also I think I don't want to use pre-releases in order to support things. You probably have hidden dependencies there, that I cannot see with PyPI yet, check out the manual and submit a PR with the correct Nuitka package configuration. I this case I suspect module dependencies missing.
