### ISSUE TITLE
Pyqt5 issue: FATAL: pyqt5: Plugin issue while working on 'Plugin initialization failed'

### ISSUE THREAD

**Issue by WaapiGo** [Nuitka/Nuitka#2903]
Hello, 

I have an issue. I guess it might be a dumb one, but I just couldn't figure out why...

**System: Windows 10
IDE: Pycharm 2022.3
Python Version: 3.9.13
Nuitka Version: 2.3
PyQt5 Version: 5.15.10
pyqt5-plugins Version: 5.15.9.2.3
pyqt5-tools Version: 5.15.9.3.3**

When I use commands like this:
**python -m nuitka --standalone --mingw64 --show-progress --show-memory --follow-imports --enable-plugin=pyqt5 --output-dir=output NuitkaTest.py**

it will always shows errors as following: (I tried many different combinations of different versions of Nuitka and Pyqt5, and it always ended up with these errors. As long as I removed "--enable-plugin=pyqt5" from the commands, it will finish packing, however the exe can not run without plugin.)

> PS D:\GitHub\Test> python -m nuitka --standalone --mingw64 --show-progress --show-memory --follow-imports --enable-plugin=pyqt5 --output-dir=output NuitkaTest.py
> Nuitka-Options: Used command line options: --standalone --mingw64 --show-progress --show-memory --follow-imports --enable-plugin=pyqt5 --output-dir=output NuitkaTest.py
> Nuitka-Options: Following all imports is the default for standalone mode and need not be specified.
> Traceback (most recent call last):
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\plugins\Plugins.py", line 69, in withPluginProblemReporting
>     result = NuitkaPluginQtBindingsPluginBase._getQtInformation(self)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\plugins\standard\PySidePyQtPlugin.py", line 261, in _getQtInformation
>     info = self.queryRuntimeInformationMultiple(
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\plugins\PluginBase.py", line 1234, in queryRuntimeInformationMultiple
>     feedback = check_output([sys.executable, "-c", cmd], env=env)
>     result = NuitkaPluginQtBindingsPluginBase._getQtInformation(self)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\plugins\standard\PySidePyQtPlugin.py", line 261, in _getQtInformation
>     info = self.queryRuntimeInformationMultiple(
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\plugins\PluginBase.py", line 1234, in queryRuntimeInformationMultiple
>     feedback = check_output([sys.executable, "-c", cmd], env=env)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\utils\Execution.py", line 130, in check_output
>     raise NuitkaCalledProcessError(exit_code, cmd, output=output, stderr=stderr)
> nuitka.utils.Execution.NuitkaCalledProcessError: Command '['C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\python.exe', '-c', '\\\nfrom __future__ import print_function\nfrom __future__ import absolute_import\
> n\ntry:\n   \n   import os\n   import PyQt5.QtCore\nexcept ImportError:\n    import sys\n    sys.exit(38)\nprint(repr(PyQt5.QtCore.QCoreApplication.libraryPaths()))\nprint("-" * 27)\nprint(repr(os.path.join(os.path.dirname(PyQt5.__f
> ile__), \'plugins\')))\nprint("-" * 27)\nprint(repr(os.path.join(os.path.dirname(PyQt5.__file__), \'..\', \'..\', \'..\', \'Library\', \'plugins\')))\nprint("-" * 27)\nprint(repr(PyQt5.QtCore.PYQT_VERSION_STR))\nprint("-" * 27)\npri
> nt(repr(getattr(PyQt5, \'_nuitka_patch_level\', 0)))\nprint("-" * 27)\nprint(repr(PyQt5.QtCore.QLibraryInfo.location(PyQt5.QtCore.QLibraryInfo.TranslationsPath)))\nprint("-" * 27)\nprint(repr(PyQt5.QtCore.QLibraryInfo.location(PyQt5
> .QtCore.QLibraryInfo.LibraryExecutablesPath)))\nprint("-" * 27)\nprint(repr(PyQt5.QtCore.QLibraryInfo.location(PyQt5.QtCore.QLibraryInfo.DataPath)))\nprint("-" * 27)\n']' returned non-zero exit status 1. Error was b'File "<string>",
>  line 1\r\n    \\\r\n     ^\r\nSyntaxError: unexpected EOF while parsing'.
> FATAL: pyqt5: Plugin issue while working on 'Plugin initialization failed'. Please report the bug with the above traceback included.

-----------------------------------------------------------------------
**Here are my code for testing:**

```
import sys
import logging
import queue
from PyQt5.QtWidgets import QApplication, QWidget, QVBoxLayout, QTextEdit, QPushButton, QLineEdit
from PyQt5.QtCore import QThread, pyqtSignal

class QueueHandler(logging.Handler):
    def __init__(self):
        super().__init__()
        self.queue = queue.Queue()
        self.formatter = logging.Formatter('%(levelname)s: %(message)s')
        self.setFormatter(self.formatter)

    def emit(self, record):
        self.queue.put(record)


amazinglogger = logging.getLogger('whipx_logger')
amazinglogger.setLevel(logging.DEBUG)
amazinghandler = QueueHandler()
amazinglogger.addHandler(amazinghandler)


class LoggerThread(QThread):
    log_signal = pyqtSignal(str)

    def __init__(self, logger):
        super().__init__()
        self.logger = logger

    def run(self):
        while True:
            record = self.logger.handlers[0].queue.get()
            formatted_record = self.logger.handlers[0].format(record)
            self.log_signal.emit(formatted_record)


class MainWindow(QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowTitle('Claude Assistant')
        self.resize(400, 300)

        layout = QVBoxLayout()
        self.text_edit = QTextEdit()
        self.text_edit.setReadOnly(True)
        layout.addWidget(self.text_edit)

        self.lineEdit = QLineEdit()
        layout.addWidget(self.lineEdit)

        self.button = QPushButton('Start Logging')
        self.button.clicked.connect(self.start_logging)
        layout.addWidget(self.button)

        self.setLayout(layout)

        self.logger_thread = LoggerThread(amazinglogger)
        self.logger_thread.log_signal.connect(self.update_text_edit)
        self.logger_thread.start()

    def start_logging(self):
        text = self.lineEdit.text() + " --> yes~~"
        amazinglogger.debug(text)
        amazinglogger.info(text)

    def update_text_edit(self, message):
        self.text_edit.append(message)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())
```
-----------------------------------
Thanks for your help!

**Comment by kayhayen** [comment]
Unfortunately you didn't fill out the issue template, the --version output would be very much needed

**Comment by WaapiGo** [comment]
> Unfortunately you didn't fill out the issue template, the --version output would be very much needed

Sorry, are the following infos that you need?

Flavor: CPython Official
Executable: C:\Users\Administrator\AppData\Local\Programs\Python\Python39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0).

**Comment by kayhayen** [comment]
You failed to properly include the error messages without a bunch of new lines thrown into the mix, I cannot recognize what could be the SyntaxError claimed there. Since you also failed to provide a pip listing, hard to tell what you are using. For me newest PyQt5 works for both 3.9 and 3.10 from PyPI. 

They wouldn't be able to create a `SyntaxError` about EOF that easily though anyway.

I was using 

```
PyQt5==5.15.10
PyQt5-Qt5==5.15.2
PyQt5-sip==12.13.0
```

I am giving up on this one, since you failed to provide information properly in the first place.
