### ISSUE TITLE
Performance question on nuitka code

### ISSUE THREAD

**Issue by flo-vienna** [Nuitka/Nuitka#2905]
What order of magnitude of difference must/can I expect
comparing a nuitka compiled python DLL to a functionally equivalent DLL, which was developed in C/C++ with
Visual Studio (with all the uncertainties attached to the question) ?

**Comment by kayhayen** [comment]
You must not have any expectations of that sort. Right now Nuitka is not giving you C speed, but we hope to get there.

**Comment by flo-vienna** [comment]
Thanks for the answer.
In what kind of magnitude is the different as it still might be acceptable :)
