### ISSUE TITLE
Issues with compiling tsai

### ISSUE THREAD

**Issue by elelelaaa** [Nuitka/Nuitka#2907]
> python -m nuitka --version
2.4rc2
Commercial: None
Python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:51:29) [MSC v.1929 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\user\anaconda3\envs\py39_MP3\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0).

- How did you install Nuitka and Python
conda create -n my_env python=3.9
python -m pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip" 

Hello,
I encountered the following error in a code that uses 'from tsai.inference import load_learner':
```
fastcore\basics.py, line 408, in store_attr
KeyError: 'self'
```

Here is a portion of the store_attr code:
```
def store_attr(names=None, self=None, but='', cast=False, store_args=None, **attrs):
    "Store params named in comma-separated `names` from calling context into attrs in `self`"
    fr = sys._getframe(1)
    args = argnames(fr, True)
    if self: args = ('self', *args)
    else: self = fr.f_locals[args[0]]
```

My code runs without issues in PyCharm, but when compiled with Nuitka, I encounter the error mentioned above. It seems that fr = sys._getframe(1) might not be calling correctly.

In the case of tsai, I have used two methods: pip install tsai and tsai received through git clone https://github.com/timeseriesAI/tsai.git, but the error is the same.

nuitka also produces the same error in versions 1.5.7, 2.4, and 2.4rc.

I would appreciate any assistance you can provide.

**Comment by kayhayen** [comment]
Nuitka doesn't keep a frame with local variables until an exception occurs, that kind of code is not supported yet.
