### ISSUE TITLE
ModuleNotFoundError: No module named 'imp' in python 3.12

### ISSUE THREAD

**Issue by georgezampoukis** [Nuitka/Nuitka#2908]
Hi!

I Know that python 3.12 support isn't finished yet, but I would like to report an issue I found:

I am using this script to freeze my application:

```
nuitka --standalone --output-filename=irai --windows-icon-from-ico=moon/assets/ui/icons/irai.ico --include-data-dir=./moon=moon --windows-console-mode=disable --enable-plugin=pyside6 main.py
```

It works great on python 3.11 but on python 3.12 it produces this error at runtime:

```
ModuleNotFoundError: No module named 'imp'
```

it seems that imp has been deprecated in 3.12 in favour of importlib.

nuitka version: 2.3.1

**Comment by kayhayen** [comment]
It actually works pretty well and no such issue is known.

In the template, we have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that we do not want to be left guessing. For you it's easy to erase the issue template and expect us to ask you questions only as necessary, but we cannot do that. We would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore we are  likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
