### ISSUE TITLE
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: C:\Users\****\myapp\certifi\cacert.pem

### ISSUE THREAD

**Issue by ducchet** [Nuitka/Nuitka#2910]
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

2.3.1
Commercial: None
Python: 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\opec\AppData\Local\Programs\Python\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0).

- How did you install Nuitka and Python

pip install nuitka
pip install --upgrade nuitka

- Also supply a Short, Self Contained, Correct, Example

I just compile it, when I open the exe file it sends requests to telegram and it says that
when i run python myapp.py it works fine
i tried nuitka version 2.3 and it works normally, maybe the latest version is buggy
```
import requests
requests.get("https://api.telegram.org/bot"+ '6855******:AA**********************' +"/sendMessage" + "?chat_id=" + '598214****' + "&text=" + 'hello')
```

- Provide in your issue the Nuitka options used
python -m nuitka --standalone --onefile --follow-imports --windows-icon-from-ico=skid.png --output-dir=dist --output-filename=skid.exe skid.py

**Comment by kayhayen** [comment]
You failed to provide the requests and certify versions, as requested in the issue template, which is why this didn't get attention at the time, and I cannot reproduce any of that anyway.
