### ISSUE TITLE
Assertion failed: !(tmp_assign_source_2 == NULL), file module.ibm_db.c, line 133

### ISSUE THREAD

**Issue by kxmatjob** [Nuitka/Nuitka#2915]
When I run the program db.exe and report an error, the detailed information is as follows. Thanks
env:
windows 7
python 3.6.8
ibm_db 3.1.4
nuitka 1.0.6

cmd:
`python -m nuitka --debug --standalone --lto=no  --report=report.xml --mingw64 --show-progress --show-memory --nofollow-import-to=pymysql,multiprocessing,http,email --enable-plugin=pyside2 --output-dir=out --jobs=4 db.py`

error:
G:\nuitka_test\out\db.dist>db.exe
Assertion failed: !(tmp_assign_source_2 == NULL), file module.ibm_db.c, line 133

code:
` import ibm_db
 class DBUtils():
    def __init__(self):
        super(DBUtils, self).__init__()
        self.dbhandle = 0`
 
 `  # DB2
    def conn_db(self, connParamStr= ""):
        try:
            self.dbhandle = ibm_db.pconnect(connParamStr, "", "")
        except Exception as e:
            print("connection:", ibm_db.conn_errormsg())`

 `if __name__ == '__main__':
    connParamStr = "DATABASE=%s;HOSTNAME=%s;PORT=%s;PROTOCOL=TCPIP;UID=%s;PWD=%s;"\
                    % ('dbtest', '127.0.0.1', '50000', 'user', 'pwd')
    db = DBUtils()
    db.conn_db(connParamStr)
    print(db.dbhandle)`

**Comment by kayhayen** [comment]
Please use a more recent Nuitka.
