### ISSUE TITLE
How to compile absolutely all modules installed?

### ISSUE THREAD

**Issue by xihuyu20000** [Nuitka/Nuitka#2921]
when I use nuitka, I want to compile all packages and modules ,not only from PYTHON_HOME/Lib but also PYTHON_HOME/Lib/site-packages. Yes, all packages and modules  in my PYTHON_HOME. Have any method?

**Comment by kayhayen** [comment]
You could walk the packages with `pkgutil.walk_packages` and generate `--include-module` or even `--include-package` out of them, getting the names from pkgutil. In Nuitka, there is code to scan all of `sys.path` or you could use `locateModules` once you have a package name and do it from a plugin as implicit dependencies for `__main__`. 

But no ready made solutions and you might want to wait for the scalability improvements this summer to be done, this is going to be slow.
