### ISSUE TITLE
Relative path in binary file

### ISSUE THREAD

**Issue by VladVons** [Nuitka/Nuitka#293]
How to use nuitka to compile project with a relative path inside as "./Inc"?

I have a project with dynamic modules loading
```

Module = __import__("Inc/" + aModuleName)
Module.Hello()

```
I compiled it with nuitka

> nuitka --follow-imports project1.py

My sources are located in /home/user1/project1
With a hex editor i see in binary file absolute pathes "/home/user1/project1/....."

When i move binary file to another computer and to another directory it doesnt work, bacause i looks for dynamic loaded files in  /home/user1/project1/Inc

nuitka 0.6.2
python 2.7.13
linux raspberrypi 4.14.98-v7+

**Comment by kayhayen** [comment]
Accelerated mode is not intended for this use of "move to another computer", definitely not for "another directory". Use --standalone for this.

**Comment by VladVons** [comment]
"standalone" option generans a tons of *.so files in roject1.dist directory  
and it still generates absolute path /home/user1/project1

How to compile without absolute pathses?  
nuitka --follow-imports project1.py

**Comment by kayhayen** [comment]
@VladVons no it does not, check the exe inside the dist folder, it is using only relative paths.

**Comment by VladVons** [comment]
hi kayhayen
here is binary files
http://download.oster.com.ua/www/permanent/nuitka/

search string inside "/home/linux/PycharmProjects/py-relay/src"
py-relay.exe (nuitka --follow-imports --standalone py-relay.py)

search many strings inside "/home/linux/PycharmProjects/py-relay/src"
py-relay.bin (nuitka --follow-imports py-relay.py)

Is it possible in future version remove teh absolute path for "not standalone" option?
py-relay.bin (nuitka --follow-imports py-relay.py)

**Comment by VladVons** [comment]
Hi kayhayen

here is binary files
http://download.oster.com.ua/www/permanent/nuitka/


find absolute path string "/home/linux/PycharmProjects/py-relay/src/"

py-relay.exe has one occurance
(nuitka --follow-imports --standalone py-relay.py)

py-relay.bin has many occurance
(nuitka --follow-imports py-relay.py)
i like this type of binary. It small and only one ready to work.
it would be great to see in next versions relative path
