### ISSUE TITLE
May I convert the modules installed using pip to pyd first, then package the converted pyd modules into an exe, and successfully import them in my Python script?

### ISSUE THREAD

**Issue by c469591** [Nuitka/Nuitka#2932]
### Version

windows10
python 3.11
nuitka 2.3.3

### How to install

pip install nuitka
Use python.exe to install Python.

### Explanation

Hello, 
May I convert the modules installed using pip to pyd first, then package the converted pyd modules into an exe, and successfully import them in my Python script?
Because I noticed that the modules inside the exe packaged with Nuitka are converted to pyd files,
I want to compile the modules into pyd files by myself first, and then package them into the exe with data file parameters to reduce the compilation time when using Nuitka each time.
I can currently use.
` --nofollow-import-to=lxml `
Remove certain modules, and then use
` --include-data-files=lxml\=lxml\=**\*.* ^`
Pack the folder of the module into the exe, but I found an issue.
Because there are many py files in the module, which will slow down the startup speed of the exe. I think this issue may also be caused by my use of
` --onefile ^`
However, at present, my needs require me to use this parameter because without it, the size of the folder would be several times larger than that of the individual exe file.

My packaging command is as follows, I will put the following command into a .cmd file for use.
```
nuitka ^
 --nofollow-import-to=lxml ^
 --include-data-files=lxml\=lxml\=**\*.* ^
 --standalone ^
 --show-memory ^
 --show-progress ^
 --output-dir=o ^
 --nofollow-imports ^
 --plugin-enable=numpy ^
 --plugin-enable=multiprocessing ^
 --include-module=win32com ^
 --windows-disable-console ^
 --remove-output ^
 -o lamb_gui ^
 --onefile ^
 gui.py
```

**Comment by kayhayen** [comment]
Manual copying of files into distributions is unsupported.

You can try and compile extension modules out of packages if you want, yes, but Nuitka is not handling data files and the like for you. There is a way to include packages uncompiled, but it doesn't work well yet for mixed situations, so that's not ready, but you can experiment as you see fit, just don't expect any help yet. If you want, you can look at enhancing Nuitka to do things properly.
