### ISSUE TITLE
The program does not run after compilation. Error: ModuleNotFoundError: No module named 'PyQt5'

### ISSUE THREAD

**Issue by Shaymas228** [Nuitka/Nuitka#2938]
When trying to compile a Python file into exe via nuitka using the command: python -m nuitka --windows-disable-console --onefile --windows-icon-from-ico=icon.ico --enable-plugin=pyside6 myprogram.py displays the message: Unwanted import of 'PyQt5' that conflicts with 'PySide6' encountered, preventing its inclusion. As a result an "ImportError" might be given at run time. Uninstall the module it for fully Nuitka-Plugins:pyside6: compatible behavior with the uncompiled code.
After compilation, I try to run the exe file but in the terminal I get the error: ModuleNotFoundError: No module named 'PyQt5'
Although my code does not use PyQt5 at all, but only pyside6. In general, the exe program does not start. Please tell me how to fix this problem?
![Uploading 608Kje7PG7.png…]()

**Comment by kayhayen** [comment]
In the template, we have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that we do not want to be left guessing. For you it's easy to erase the issue template and expect us to ask you questions only as necessary, but we cannot do that. We would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore we are  likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
