### ISSUE TITLE
Error: ModuleNotFoundError: No module named 'PyQt5'. The program does not run after compilation

### ISSUE THREAD

**Issue by Shaymas228** [Nuitka/Nuitka#2942]
- Nuitka` version, full Python version, flavor, OS, etc. as output by this exact command.
2.2
Commercial: None
Python: 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\No Information\AppData\Local\Programs\Python\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0).

- How did you install Nuitka and Python
pip install nuitka
downloaded python installer from official site

- Nuitka command
 `python -m nuitka --windows-disable-console --onefile --windows-icon-from-ico=icon.ico --enable-plugin=pyside6 mamogram.py`

- On the issue
When trying to compile a Python file into exe via nuitka in consle displays the message: 
`Unwanted import of 'PyQt5' that conflicts with 'PySide6' encountered, preventing its inclusion. As a result an "ImportError" might be given at run time. Uninstall the module it for fully Nuitka-Plugins:pyside6: compatible behavior with the uncompiled code.`

After compilation, I try to run the exe file but in the terminal I get the error: 
`ModuleNotFoundError: No module named 'PyQt5'`

Although my code does not use PyQt5 at all, but only pyside6. In general, the exe program does not start. 
I already uninstalled PyQt5 using the command `pip uninstall PyQt5` but it didn't help at all.
Please tell me how can i fix this problem?

**Comment by kayhayen** [comment]
Nuitka can only make programs work that already work, so uninstalling PyQt5 can of course in fact cause that. The PySide6 plugin suppresses PyQt5, because loading two different Qt versions is not possible, at least not 2 Qt5 or 2 Qt6. Not sure if both Qt6 and Qt5 can work. Without a reproducer there is only so much to do. 

Also make sure to use latest Nuitka version and provide a minimal reproducer. In order to figure out where PyQt5 is used, with it installed, use --noinclude-custom-mode=PyQt5:error that should point you to where it's happening.

**Comment by Shaymas228** [comment]
As I understand it, I need to find out where in my code the pyqt5 module is used, using the command `--noinclude-custom-mode=PyQt5:error`. If I understand correctly, the full Nuitka command looks like `python -m nuitka --onefile --windows-icon-from-ico=icon.ico --enable-plugin=pyside6 --noinclude-custom-mode=PyQt5:error mamogram.py`
But after compilation, when I run the EXE file, I don’t receive any information about where PyQt5 is used. Maybe I'm doing something wrong? But I must say that in my code there is no mention of PyQt5 anywhere.

**Comment by kayhayen** [comment]
It should happen at compile time. Not having PyQt5 installed would be an indication of not getting the error.
