### ISSUE TITLE
CPython: There is a problem with detecting imports

### ISSUE THREAD

**Issue by OlegXio** [Nuitka/Nuitka#2944]
I have the same error when building the program as https://github.com/Nuitka/Nuitka/issues/546 (CPython import problems).
However, there is the only difference I found - any program, including the "hello world" program does not work **if use the `--onefile` option**, otherwise everything works fine
Python 3.10
Nuitka 2.4.rc6

crash report xml file is not created

**Comment by KRRT7** [comment]
without a reproducible example it's impossible to help.

**Comment by OlegXio** [comment]
`print('hello world')`.
this code was successfully built and started, but if you specify the --onefile flag, it will not be built successfully. 
Did I understand you correctly? Or did you need a code other than hello world

**Comment by KRRT7** [comment]
this code works for me on both linux and windows, how did you install nuitka? run `nuitka --version` and share the output

**Comment by OlegXio** [comment]
Install nuitka: `python -m pip install -U --force-reinstall "https://github.com/Nuitka/Nuitka/archive/factory.zip"`.

```info
2.4rc6
Commercial: None
Python: 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: D:\Program Files\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\gcc (gcc 13.2.0).
```

**Comment by kayhayen** [comment]
The factory branch is not supported like that, your gcc is not, reports are only valid for develop or main.
