### ISSUE TITLE
cannot scan dependency with @rpath/QtSvg.framework/Versions/A/QtSvg'

### ISSUE THREAD

**Issue by oungsi2000** [Nuitka/Nuitka#2945]
Hello

I'm using venv for my project
when i tried to build a bundle without using venv, always successed to build a bundle without any compileerror, (but got error zsh:abort when i execute the bundle)

starting to use venv, i got fatal error 
FATAL:     Error, problem with dependency scan of '~/Desktop/my-project/.venv/lib/python3.11/site-packages/PySide6/Qt/plugins/iconengines/libqsvgicon.dylib' with '@rpath/QtSvg.framework/Versions/A/QtSvg' please report the bug.

this is my nuitka version, 
------
2.3.9
Commercial: None
Python: 3.11.3 (v3.11.3:f3909b8bc8, Apr  4 2023, 20:12:10) [Clang 13.0.0 (clang-1300.0.29.30)]
Flavor: CPython Official
Executable: /Users/jung-yongjun/Desktop/판매추적기/.venv/bin/python3.11
OS: Darwin
Arch: arm64
macOSRelease: 11.6
Version C compiler: /usr/bin/clang (clang 12.0.5).

and this is the commandline below i used
------
python3.11 -m nuitka --enable-plugin=pyside6 --macos-create-app-bundle app.py

this is a whole log of nuitka
-----
Nuitka-Options: Used command line options: --enable-plugin=pyside6 --macos-create-app-bundle PysideGUI.py
Nuitka:WARNING: For application bundles, you ought to specify an icon with '--macos-app-icon'.", otherwise a dock icon may not be present.
Nuitka: Starting Python compilation with Nuitka '2.3.9' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:options-nanny: Note, when using 'PySide6', consider using '--macos-create-app-bundle' option. Otherwise high resolution will not be
Nuitka-Plugins:options-nanny: available and a terminal window will open. However for debugging, terminal output is the easiest way to see informative
Nuitka-Plugins:options-nanny: traceback and error information, so launch it from there if possible.
Nuitka-Plugins:anti-bloat: Not including '_bisect' automatically in order to avoid bloat, but this may cause: may slow down by using fallback
Nuitka-Plugins:anti-bloat: implementation.
Nuitka-Plugins:anti-bloat: Not including '_json' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.                                 
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: clang (clang 12.0.5).
Nuitka will make use of ccache to speed up repeated compilation.

Is it OK to download and put it in '/Users/jung-yongjun/Library/Caches/Nuitka/downloads/ccache/v4.2.1'.

Fully automatic, cached. Proceed and download? [Yes]/No : n
Nuitka-Scons: Backend linking program with 455 files (no progress information available for this stage).
Nuitka-Scons:WARNING: You are not using ccache, re-compilation of identical code will be slower than necessary. Use your OS package manager to install it.
Nuitka-Plugins:pyside6: Including Qt plugins 'iconengines,imageformats,platforms,styles,tls' below 'PySide6/qt-plugins'.
FATAL:     Error, problem with dependency scan of '~/Desktop/판매추적기/.venv/lib/python3.11/site-packages/PySide6/Qt/plugins/iconengines/libqsvgicon.dylib' with '@rpath/QtSvg.framework/Versions/A/QtSvg' please report the bug.

Thanks

**Comment by kayhayen** [comment]
Something inconsistent about your report, for ARM we do not download ccache, or do we.

Which version of PySide6 is this?

**Comment by oungsi2000** [comment]
my pyside6 version is 6.7.2
i can distribute all source code if you need

**Comment by kayhayen** [comment]
This won't depend much on the source code, more the system side of things, or PySide 6.7.2 contains changes Nuitka is not handling yet, I think 6.7.1 worked, but i will check now.

**Comment by kayhayen** [comment]
Can you try and eliminate the possibility that it's the Chinese path that the virtualenv lives in. So far I never had issues with file paths, but maybe that is what's going on.

**Comment by oungsi2000** [comment]
Sorry for delay.
I changed the all path letters to Latin. It successfully worked ! As you said, the un-Latin letters was the problem 

But When I execute the Bundle, Mainwindow does not appear and immediatly shut down. 

when I run executable file inside of bundle (content/MacOS/exec) different Execption was shown such as:
------
Error in sys.excepthook:
Traceback (most recent call last):
  File "/Users/jung-yongjun/Desktop/myapp/.venv/PysideGUI.app/Contents/MacOS/PysideGUI.py", line 43, in catch_exception
NameError: name 'app' is not defined

Original exception was:
Traceback (most recent call last):
  File "/Users/jung-yongjun/Desktop/myapp/.venv/PysideGUI.app/Contents/MacOS/PysideGUI.py", line 152, in <module>
NameError: name 'QStyledItemDelegate' is not defined
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

this is some part of my code: 

```
from PySide6.QtWidgets import *
from PySide6.QtCore import * 
from PySide6.QtGui import *

~
def catch_exception(exc_type, exc_value, exc_traceback):
    # Keyboard Interrupt를 통한 예외 발생은 무시합니다.
    if issubclass(exc_type, KeyboardInterrupt):
        sys.__excepthook__(exc_type, exc_value, exc_traceback)
        return
    app.setAttribute(Qt.ApplicationAttribute.AA_DontUseNativeDialogs, True)
~

class GraphicDelegate(QStyledItemDelegate):
 ~
class Mainwindow(QMainwindow):
~

if __name__ == "__main__":
    app = QApplication(sys.argv)
    mainWindow = MainWindow()
    mainWindow.show()
    sys.exit(app.exec())
```

Doesn't Nuitka support QStyledItemDelegate from PySide6.QtWidgets ?
Thanks

**Comment by kayhayen** [comment]
It's supposed to support everything. Make a new issue with that and fill out the issue template properly, then I can look into it, but parts of code won't do anything for me.

**Comment by kayhayen** [comment]
I have a suspect, that `LC_ALL` changes might needed, just like the ones I did for the Linux tooling the other day. So far, only `LANG`  was set and maybe for macOS nothing gets set at all yet, I need to check.

**Comment by kayhayen** [comment]
I have generalized the change, so it now should also apply to your macOS and solve the issue, I am very confident it would have to. Let me know if the original path works equally well/bad now, so I can consider this for the next hotfix.

**Comment by kayhayen** [comment]
This is part of the 2.3.10 hotfix release I just made.
