### ISSUE TITLE
Numpy import error (multiarray)

### ISSUE THREAD

**Issue by solanu** [Nuitka/Nuitka#295]
I get the following error when I run `main.exe` after I compile with `python -m nuitka --standalone --mingw64 --follow-imports main.py`:
```
main
Traceback (most recent call last):
  File "C:\Users\IEUser\Desktop\o\main.dist\numpy\core\__init__.py", line 40, in <module numpy.core>
  File "C:\Users\IEUser\Desktop\o\main.dist\numpy\core\multiarray.py", line 12, in <module numpy.core.multiarray>
  File "C:\Users\IEUser\Desktop\o\main.dist\numpy\core\overrides.py", line 6, in <module numpy.core.overrides>
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\IEUser\Desktop\o\main.dist\main.py", line 1, in <module>
  File "C:\Users\IEUser\Desktop\o\main.dist\c\i.py", line 3, in <module c.i>
  File "C:\Users\IEUser\Desktop\o\main.dist\e\e.py", line 6, in <module e.e>
  File "C:\Users\IEUser\Desktop\o\main.dist\e\a.py", line 6, in <module e.a>
  File "C:\Users\IEUser\Desktop\o\main.dist\numpy\__init__.py", line 142, in <module numpy>
  File "C:\Users\IEUser\Desktop\o\main.dist\numpy\core\__init__.py", line 71, in <module numpy.core>
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\Program Files\Python37\python.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was:


```
Nothing after `Original error was:`.

I am using numpy functions in my code such as `numpy.zeros`, `numpy.ones` ,... and so on).

My setup is:
```
Python: 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] (It is installed with Windows installer) [no more versions of python installed]
Nuitka 0.6.2 (it is installed with pip)
MinGW-64 8.1.0 (win32 threads and x86_64 architecture) (It is installed with Windows installer)
Numpy: 1.16.2 (it is installed with pip)
Windows 10 64bits (same problem with Windows 7 64bits) [fresh and clean original installation]
Arch: x86_64
```

I have tried to compile with `python -m nuitka --standalone --mingw64 --follow-imports --include-plugin-directory="C:\Program Files\Python37\Lib\site-packages\numpy\core" main.py` but I always get the same error when I run `main.exe`.

**Comment by JorjMcKie** [comment]
I am a numpy user, too. Let me try to re-generate your situation.
You are obviously not using additional numpy plugin libraries (MKL, OpenBlas, ...) right?

**Comment by solanu** [comment]
> 
> 
> I am a numpy user, too. Let me try to re-generate your situation.
> You are obviously not using additional numpy plugin libraries (MKL, OpenBlas, ...) right?

No numpy plugins

**Comment by JorjMcKie** [comment]
When re-installing numpy, I realized that the 1.16.2 version now comes with `C:\...\site-packages\numpy\.libs\libopenblas.IPBC74C7KURV7CB2PKT5Z5FNR3SIBV4J.gfortran-win_amd64.dll` - an OpenBlas DLL.
So you **must** use `--enable-plugin=numpy-plugin` in your standalone compile.

Not doing this, I am running in the same issue - doing it works fine!

Unfortunate, this numpy message not specifying what was itching ...

**Comment by solanu** [comment]
It works! Thank you

**Comment by apdullahyayik** [comment]
when --enable-plugin=numpy-plugin is used "Error, unknown plug-in 'numpy-plugin' referenced." occurs

**Comment by JorjMcKie** [comment]
sorry, my bad: please use ``--enable-plugin=numpy`` not ``--enable-plugin=numpy-plugin``.

**Comment by JorjMcKie** [comment]
Maybe you find [hinted compilation](https://github.com/Nuitka/NUITKA-Utilities/tree/master/hinted-compilation) useful: it will relieve you from figuring out all the plugins required by your script - plus some other advantages.

**Comment by apdullahyayik** [comment]
> sorry, my bad: please use `--enable-plugin=numpy` not `--enable-plugin=numpy-plugin`.

Unfortunately, same error occurs again 
Error, unknown plug-in 'numpy' referenced.

**Comment by JorjMcKie** [comment]
Did you upgrade your Nuitka anytime lately?

**Comment by JorjMcKie** [comment]
Please show me the output of the following commands:
``python -m nuitka --version``
and
``python -m nuitka --plugin-list``

**Comment by apdullahyayik** [comment]
1st
-------
0.6.1.1
Python 3.7.5rc1
Os: Linux

2nd
-------
A long usage info
and this error message : "Error, need positional argument with python
module or main program"


Thanks for your support

**Comment by JorjMcKie** [comment]
This version is from almost prehistoric times!
Please install the most current version from the development branch, and then you should be successful.
