### ISSUE TITLE
NameError: name 'WinDLL' is not defined, Nuitka 2.3.9 build Scipy 1.14

### ISSUE THREAD

**Issue by zincers** [Nuitka/Nuitka#2954]
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

> python -m nuitka --version

> 2.3.9
> Commercial: None
> Python: 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]
> Flavor: Anaconda Python
> Executable: D:\Software\Miniconda3\envs\TestEnv\python.exe
> OS: Windows
> Arch: x86_64
> WindowsRelease: 11
> Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\bin\Hostx64\x64\cl.exe (cl 14.3).

- How did you install Nuitka and Python

 conda virtualenv, pip install nuitka

- The specific PyPI names and versions

> python -m pip list -v
> 
> Package     Version Location                                              Installer
> ----------- ------- ----------------------------------------------------- ---------
> Nuitka      2.3.9   D:\Software\Miniconda3\envs\TestEnv\Lib\site-packages pip
> numpy       2.0.0   D:\Software\Miniconda3\envs\TestEnv\Lib\site-packages pip
> ordered-set 4.1.0   D:\Software\Miniconda3\envs\TestEnv\Lib\site-packages pip
> pip         24.0    D:\Software\Miniconda3\envs\TestEnv\Lib\site-packages
> scipy       1.14.0  D:\Software\Miniconda3\envs\TestEnv\Lib\site-packages pip
> setuptools  69.5.1  D:\Software\Miniconda3\envs\TestEnv\Lib\site-packages
> wheel       0.43.0  D:\Software\Miniconda3\envs\TestEnv\Lib\site-packages
> zstandard   0.22.0  D:\Software\Miniconda3\envs\TestEnv\Lib\site-packages pip

- Also supply a Short, Self Contained, Correct, Example

Only one line in test.py
```
import scipy
```

- Provide in your issue the Nuitka options used

```
python -m nuitka --msvc=latest --standalone test.py
```

- Note if this is a regression

Python 3.11 + Nuitka 2.1 works. 

---
When running the compiled executable program，an error occurs. The output:
```
(TestEnv) PS E:\path\to\> .\__build__\test.dist\test.exe
Traceback (most recent call last):
  File "E:\path\to\__build__\test.dist\test.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "E:\path\to\__build__\test.dist\scipy\__init__.py", line 76, in <module scipy>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "E:\path\to\__build__\test.dist\scipy\_distributor_init.py", line 25, in <module scipy._distributor_init>
NameError: name 'WinDLL' is not defined
```

**Comment by kayhayen** [comment]
That's kind of suprising, but of course possible, I thought we would already know that.

**Comment by kayhayen** [comment]
I am surprised to see that Scipy actually works with Numpy 2 there. I thought it required a new Scipy as well, but that's not the case, which is good, of course.

**Comment by kayhayen** [comment]
This config is to blame I guess.

```
- module-name: 'scipy._distributor_init' # checksum: 576c57d8
  anti-bloat:
    - description: 'workaround for scipy DLL loading'
      append_plain: |
        import os
        if os.name == "nt":
          import glob
          libs_dir = os.path.join(os.path.dirname(__file__), '..', 'scipy.libs')
          for filename in glob.glob(os.path.join(libs_dir, '*openblas*dll')):
            WinDLL(filename)
      when: 'win32 and version("scipy") >= (1, 9, 2)'
```

I will have to check what we were trying to achieve there, this may have become unnecessary. At which point that happened, I am trying to figure out right now.

**Comment by kayhayen** [comment]
Seems, 1.14 is precisely the one, that removes the code this is supposed to tie into. Therefore the WinDLL import from ctypes is no longer there. And probably it's the newest that added numpy 2 support, which I repaired only recently, so it makes sense we hear of it exactly now. The breakage is Windows only.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by zincers** [comment]
Thanks for helping me resolve this problem, factory branch works for me.

**Comment by kayhayen** [comment]
This is part of the 2.3.10 hotfix release I just made.
