### ISSUE TITLE
Suggestion: Better aproach for getting Path to executable

### ISSUE THREAD

**Issue by diego-comlet** [Nuitka/Nuitka#2957]
According to the [Nuitka User Manual](https://nuitka.net/user-documentation/common-issue-solutions.html#onefile-finding-files), `os.path.dirname(__file__)` should be used to find files *'inside'* the compiled executable in *onefile* mode. But there are multiple uses cases under which, this does not work:

1. First let's start explaining the folder structure for the given examples:
 ```
entry_script.py
code/
    __main__.py
    functions.py
    other_file.py
    ...
```
And let's say entry_script.py > \_\_main\_\_.py > functions.py

> ">" simbolize a call from 'a' to 'b'

2. If `os.path.dirname(__file__)`  is used from within `functions.py` the path returned will be: /path/to/compiled/tmp/folder/code

> Notice how the name of the folder 'code' gets appended at the end.

Sure this has a simple enough fix, in which we just look at the parent of the returned folder, but this would make the implementation of the code rely onto not being moved around inisde the sources.

3. So in this point, you would the reasonable sollution with be to move out from this `__file__`  aproach onto another suggested one `os.path.dirname(sys.argv[0])`  (On this case I am refering to *standalone*) and this for the most part will in fact fix the issue. But then, we stumble upon another use case:
    1. Let's say we want to add the compiled executable to the PATH, which is a pretty common practice.
    2. After adding the executable to the PATH, the variable `sys.argv[0]`  turns out usless given, that the path information for the executable is just no longer then. 

4. And this brings me to a sollution for files either _'inside'_ **onefile**, or  **standalone**:
The following code, takes care of gessing the 'depth' in the folder structure of the current script, so then you can look at the parent directory the exact number of times required, to get the path to the executable.
For this we take a look at `__name__`  and this will return, let's put a series of examples:
      1. For `entry_script.py`, `__get_call_depth()` will return `1`.
      2. For `code.py`, `__get_call_depth()` will return `2`.
      3. For `functions.py`, `__get_call_depth()` will return `2`.
  Those are exactly the amount of times to call parent, for the given `__file__` to get to the executable path.
```python
def __get_call_depth() -> int:
    return len(__name__.split('.'))

path = pathlib.Path(__file__)
for _ in range(__get_call_depth()):
    path = path.parent
return path
```
> For this example, pathlib.Path is used instead of os.path, but the code should pretty much be the same

This is my suggestion :construction_worker:, please correct me if I made any mistakes, and hope this comes handy to someone. Also this makes me wonder, if it would make sense for Nuitka to provide some library as a tool set, to manage this variables more easily.

> _Note: Please keep in mind, that even thou the example given evolves around the 'onefile' mode, this affects all use cases under which this variables get used._

**Comment by kayhayen** [comment]
I am not sure, I am getting you. Of course you can use `pathlib`, pkg_resources.read_text, pkgutil.get_data, and importlib.resources or whatever functions they all work. Some of them work with package names, some of them work with filenames. Only some people associate their data files with packages, but I would recommend doing it, since it makes it easy to work with them in Python code with clean calls.

For the root directory of inside your program, which is apparently what you are looking for, the best thing would be to use `os.path.dirname(sys.modules["__main__").__file__` which is probably something worth adding to the documentation.

Does this address your point?

I find your proposal of this being library code, nice. The typical Python APIs have no distinction of inside/outside of course, but `os.path.dirname(sys.argv[0])` is kind of good enough there, isn't it.

**Comment by diego-comlet** [comment]
Thanks! `sys.modules["__main__"].__file__` fixed my issue. 
Regarding `os.path.dirname(sys.argv[0])`, as previouslly stated it will work as long as you don't run it from another folder calling it from the PATH.

For example, on Windows:
```shell
set PATH=%PATH%;path\to\compiled\binary\
```
Calling **binary.exe** will make `sys.argv[0]` return just 'binary.exe' with absolutely no information about its location.

**Comment by kayhayen** [comment]
I will have to investigate that. There is `__compiled__.contained_dir` to find the outside directory, but I believe the onefile is supposed to produce an absolute path there. If it's not, I would consider that a bug of course.

**Comment by kayhayen** [comment]
You are correct, this is not absolute at all, making it unreliable for use.

`contained_dir` is intended mainly for you avoid having to do different things for macOS apps vs. everything else, where to get outside of the dist dir, you only need a dirname, but for macOS that's not enough to get outside the .app.

**Comment by kayhayen** [comment]
So, I changed it for the Python side of things for standalone and accelerated mode both, but onefile should pass it corrected already, however it just uses `GetCommandLineW` so I guess, I need to replace the first argument in there with a parsed one, but need to figure out, how to do the command line parsing on Windows safely first.

**Comment by kayhayen** [comment]
As an aside, making `__compiled__.containing_dir` absolute was only added relatively recently, and the wrong place to do it for that object only, since it's derived from the sys.argv[0], if that's absolute, it would be automatically good, so I can also correct that one, and containing_dir could easily be wrong it called via PATH indeed.

**Comment by kayhayen** [comment]
Ok, that was easy, `CommandLineToArgvW` exists and can be used to disassemble and later recombine, I guess.

**Comment by kayhayen** [comment]
So, I did it for onefile, standalone, accelerated on all OSes, it's on staging branch right now, I kind of don't dare changing it late in the 2.3 series, but that's got to make things a lot more robust. The unfortunate thing is that it's not fully compatible code for Python, where that's not happening, the path needs manual resolution there and it works only if calling it from the current directory. So I guess, for Python fully compatible code, some sort of PATH resolution needs to be done I guess, where using __file__ was always good, but that's just the way it is I fear. Maybe I change my recommendation over to allow for `compiled.__containing_dir` with file fallback, but I hate non-standard Python changes in user code.

**Comment by kayhayen** [comment]
This is currently on the develop and staging branches and will be part of the 2.4 release.

**Comment by kayhayen** [comment]
This is part of the stable release 2.4 that I just made.

**Comment by Choonholic** [comment]
sys.argv returns incorrect results:

Command: abc.exe argv1 argv2

Nuitka 2.3.11 - sys.argv = ['\path\abc.exe', 'argv1', 'argv2']
Nuitka 2.4 - sys.argv = ['\path\abc.exeargv1', 'argv2']

I had to rollback to 2.3.11... Please check this quickly.
