### ISSUE TITLE
Nuitka does not import necessary pycryptodome library

### ISSUE THREAD

**Issue by Jaydenha09** [Nuitka/Nuitka#2959]
I was trying to compile a program that use pycryptodome, after compiled it, it cant load Crypto.Cipher._pkcs1_decode, later found out nuitka wont copy the library Crypto/Cipher/_pkcs1_decode.pyd, the program works after I copy _pkcs1_decode.pyd manually

- Nuitka version
```
PS C:\Users\jayde> python -m nuitka --version
2.3.10
Commercial: None
Python: 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\jayde\AppData\Local\Programs\Python\Python39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64\cl.exe (cl 14.3).
```

Installed the stable version with pip

Minimal example
```
from Crypto.Cipher import AES, PKCS1_OAEP
from Crypto.PublicKey import RSA
from Crypto.Random import get_random_bytes

aes_key = get_random_bytes(32)
rsa_key = RSA.generate(4096)
aes_cipher = AES.new(aes_key, AES.MODE_EAX)
rsa_cipher = PKCS1_OAEP.new(rsa_key.publickey())

try:
    encrypted_data = aes_cipher.encrypt(b'Test data')
    encrypted_key = rsa_cipher.encrypt(aes_key)
    print('Encryption successful')
except Exception as e:
    print('Encryption failed:', e)
```

Command used

python -m nuitka --standalone test.py

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by Jaydenha09** [comment]
yup its working, thanks

also for people found this issue, want a temporary fix without using factory branch, you can include the below code
```
try:
  import Crypto.Cipher._pkcs1_decode
except:
  pass
```

that module cant be imported directly, so you will have to use try and ignore the exception, just to make nuitka detects it and import it

**Comment by kayhayen** [comment]
Even easier would of course be an  `--include-module` usage, but this is going to be part of a hotfix anyway.

**Comment by kayhayen** [comment]
This is part of the stable release 2.4 that I just made.
