### ISSUE TITLE
Nuitka must not search DLLs from PATH for PyPI packages on Windows

### ISSUE THREAD

**Issue by joseph16388** [Nuitka/Nuitka#2968]
Hello! My project compiled perfectly with pyinstaller, but the exe file was slow to start, so I started trying to compile with Nuitka, but I ran into problems.
 I used nuitka to compile the project error, system information and logs are as follows：

- Nuitka version, 
2.3.10
- full Python version
Python 3.11.5
-  OS
WIN11
- command
nuitka --output-filename=FanTui_SoftWare --standalone  --no-pyi-file --output-dir=D:/AI/ChatGLM2/AI_Novel_FanTui_Pack/nuitka_output  --enable-plugin=pyside6  --module-parameter=torch-disable-jit=no --report=compilation-report.xml  D:/AI/ChatGLM2/AI_Novel_FanTui_Pack/FanTui_SoftWare.py
- report (log)：
[compilation-report.txt](https://github.com/user-attachments/files/16064999/compilation-report.txt)

Please see how to solve, thank you!！

**Comment by kayhayen** [comment]
This is not the first time I see this DLL:

OSError: [Errno 123] getWindowsLongPathName for c:\progra~2\tencent\we~1\dll\ws2_32.dll (文件名、目录名或卷标语法不正确。)

Remove it from your PATH, and I was thinking, we were no longer picking up DLLs from `%PATH%` but maybe we still do.

**Comment by kayhayen** [comment]
What is `tencent` anyway?

**Comment by joseph16388** [comment]
> This is not the first time I see this DLL:
> 
> OSError: [Errno 123] getWindowsLongPathName for c:\progra~2\tencent\����we~1\dll\ws2_32.dll (文件名、目录名或卷标语法不正确。)
> 
> Remove it from your PATH, and I was thinking, we were no longer picking up DLLs from `%PATH%` but maybe we still do.

ok，thanks you.
I did what you asked, Nuitka: Successfully created XXXX.
But when I click on the exe executable, I get an error: **nuitka: Need to use this as an option to compile with '-- included-distribution-metadata =librosa'**, but when I add this option to the command line, I get an error: **FATAL: Error, could not find distribution 'librosa' for which metadata was asked to be included.**
So, how do I fix this?

**Comment by joseph16388** [comment]
> What is `tencent` anyway?

It's the name of an Internet, gaming company

**Comment by kayhayen** [comment]
> > What is `tencent` anyway?
> 
> It's the name of an Internet, gaming company

Ah yes, I am actually familiar with that name now. Thanks. They seem to include DLLs that are only there for Windows.

**Comment by kayhayen** [comment]
For the other thing, please make a new report, I loose track. So what should be done, is that for PyPI packages, system DLLs and thus non-Python PATH elements must not be considered for Windows, this is not in line with what we do for Linux and macOS and why you encounter this.

**Comment by joseph16388** [comment]
> For the other thing, please make a new report, I loose track. So what should be done, is that for PyPI packages, system DLLs and thus non-Python PATH elements must not be considered for Windows, this is not in line with what we do for Linux and macOS and why you encounter this.

Thanks for your reply! The newest report As follows:
[compilation-report.txt](https://github.com/user-attachments/files/16088221/compilation-report.txt)

**Comment by miaopass-future** [comment]
Has this problem been addressed? I'm currently using version 2.4.8, and I still have this problem

**Comment by kayhayen** [comment]
This issue is two faced. First of all, the DLL dependency scan doesn't respect the decision of outside DLLs or not, and second that decision itself might be problematic:

```
            if isStandardLibraryPath(module_filename):
                allow_outside_dependencies = True
            else:
                allow_outside_dependencies = Plugins.decideAllowOutsideDependencies(
                    standalone_entry_point.module_name
                )
```

So for extension modules from standard library, currently on all OSes, it might pull stuff in still. I am addressing the inconsistency of not following the command on Windows first, but I think for standard libraries, it might still do DLL scans, which on Windows can be spoiled by bad deployments easily.

**Comment by kayhayen** [comment]
Ah, what's going on is that Nuitka is first detecting with all `%PATH%` and then discards it later, which is too late, because it fails to resolve

**Comment by kayhayen** [comment]
So, for now, I think we need to handle cases of failure to find a long path from what is a short path. I am not sure how this short path quoted can fail to resolve to a long path, that should not be possible, but maybe I am misunderstanding how the underlying Windows API works, and it's not recursive, and we would get to resolve each path component separately.

**Comment by kayhayen** [comment]
Part of the current pre-release and will be in 2.5 once released.

**Comment by kayhayen** [comment]
Part of the 2.5 release I just made.

**Comment by rrsyycm** [comment]
https://www.wmphp.com/8138.html
解决了tencent问题,删除环境变量后需要注销重启.
