### ISSUE TITLE
Multiple instances of dependency walker sending CPU to 100%

### ISSUE THREAD

**Issue by poke2201** [Nuitka/Nuitka#297]
I'm using nuitaka 0.6.2 and python 3.7.0 on a windows 64 bit machine.

0.6.2
Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
Executable: C:\Python\python.exe
OS: Windows
Arch: x86_64

I downloaded nuitaka from the website, and then installed through pip according to the manual.

I followed the tutorial on the manual, however when I run the executable code:

`python -m nuitka --standalone --mingw64 hello.py`, my cpu usage shoots up to 100% and I see multiple instances of dependency walker on my task manager and it doesn't create a .exe that I can "use".  Here is [a picture of what is happening](https://i.imgur.com/0ljCgGH.png).

I can't tell what is causing this issue, but I know it opens gcc.exe and gets stuck on making the dependency walker.  I tried this with admin permissions on command prompt with the same result.

**Comment by JorjMcKie** [comment]
That per se doesn't look unnormal at first sight.
First the first runs, the dependency walker goes through a lot of stuff, but stores the results of its works for subsequent runs - if you muster the patience to let it finish.

To get acquainted and see results quickly, you can use some options which avoid using the dependency walker, resp. creating the dll cache.

```
python -m nuitka --standalone --mingw64 --experimental=use_pefile --disable-dll-dependency-cache --python-flag=nosite hello.py
```

**Comment by poke2201** [comment]
Okay, that seemed to work, I was able to get the .exe running perfectly.  However, I do want it to work without having to use experimental features.

How long does it usually take for the dependency walker to do its job?  Now that I know it works, should I retry the old code and just let it sit there?

And then for subsequent runs, will it be much faster as it knows where to look?

**Comment by JorjMcKie** [comment]
1. We will make this experimental feature a standard before long
2. You can continue to use ``--disable-dll-dependency-cache``, which will deactivate the dependency walker
3. yes: the dependency walker will save its its results. Only dependencies not investigated will afterwards be researched

**Comment by JorjMcKie** [comment]
I would still recommend using ``pefile``. Why don't you try and use the little "invocation helper" [nuitka-sa.py](https://github.com/Nuitka/NUITKA-Utilities/blob/master/nuitka-sa.py). It embodies all the lengthy parameters in an internal list, which can easily be changed.

**Comment by deajan** [comment]
The "standard" dependency walker will take a lot of time because for every single DLL, it will cross your whole filesystem.
On my Core i7 with an nvme SSD, I had about 30 minutes of depends.exe running all my 8 cores at 100% cpu.
Nevertheless, the experimental dependency walker will not produce "bad" distributions, since it basically does the same job as the standard dependency walker does, just quicker.

**Comment by poke2201** [comment]
Okay thank you for the help!

**Comment by LivePython** [comment]
This is very helpful in my case. Thanks for the update

**Comment by kayhayen** [comment]
All the information here, is now wrong. The performance issue of dependency walker is supposed to be resolved, should now always be fast. The experimental options do not have any effect anymore, and the implementation for pefile has been removed. Using recent Nuitka, the problem should not exist.

**Comment by kayhayen** [comment]
Also no longer searches all file system.

**Comment by kayhayen** [comment]
Do not follow any advice given in this issue, it is obsolete. If you believe  you experience problems with dependency walker CPU, create new issues, there are no solutions here.
