### ISSUE TITLE
Error, cannot find 'python311.lib' file.

### ISSUE THREAD

**Issue by Singhom931** [Nuitka/Nuitka#2977]
Nuitka: Running C compilation via Scons.
Nuitka-Scons:WARNING: Windows SDK must be installed in Visual Studio for it to be usable with Nuitka. Use the Visual Studio installer for adding it.
Nuitka-Scons: Backend C compiler: gcc (gcc 13.2.0).
FATAL: Error, cannot find 'python311.lib' file.
FATAL: Failed unexpectedly in Scons C backend compilation.
Nuitka:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/scons-backend-failure.html
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'.

this is on a simple hello world program so probably issue with my setup but i cant figure out why my enviornment variables are working fine then why cant its find python311.lib

**Comment by kayhayen** [comment]
Read the user manual, you cannot use your own GCC and the MSVC needs to have the right stuff installed in it.

**Comment by ilsong** [comment]
Anyone found solutions? I read the documents and I set ```PYTHONPATH``` environment variable, other python paths to environment variables and copy ```python311.lib``` file to cwd and python path. But still nauitka is showing "cannot find ```python311.lib``` file" message.
