### ISSUE TITLE
Multidist not work without standalone

### ISSUE THREAD

**Issue by seed93** [Nuitka/Nuitka#2981]
When I try to use `--main` option, I failed to run. This is my test.
```
# a.py
print('a')

# b.py
print('b')
```
When I run with `python -m nuitka --main=a.py --main=b.py`, it shows `ModuleNotFoundError: No module named 'multidist-1-a'`.
It only works when I add an option `--standalone`, which is not what I want.

The environment info is below.

2.2.3
Commercial: None
Python: 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0]
Flavor: Debian Python
Executable: /usr/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 20.04.6
Version C compiler: /usr/bin/gcc (gcc 9).

**Comment by kayhayen** [comment]
I think it works if you e.g. followed all imports. Right now, I think it creates fake modules but then doesn't include them automatically and relies on, e.g., `--follow-imports` to be used, but this ought to work with following no imports indeed, but that is should be easy enough to add.

**Comment by seed93** [comment]
> I think it works if you e.g. followed all imports. Right now, I think it creates fake modules but then doesn't include them automatically and relies on, e.g., `--follow-imports` to be used, but this ought to work with following no imports indeed, but that is should be easy enough to add.

It works as expected. But if I have thousands of packages and I don't want to pack them in this executable file, what can I do? It is extreamly slow and larget. I could pack every endpoint parallely currently and this is faster.

**Comment by kayhayen** [comment]
Yes, the fix will be to include those. Nuitka does that a lot in accelerated mode, e.g. including modules needed by plugins, I will add it. This was just an explanation, why we didn't notice this before.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by seed93** [comment]
> Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html
> 
> Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

Thank you so much. I tested with the factory version, and it worked in the original case. However, if I import some package, e.g. `import numpy` in any `.py` files, it will not be found. It will say `ModuleNotFoundError: No module named 'numpy'`

**Comment by kayhayen** [comment]
Please open new issues with reproducers for new issues. I however believe you probably just need to inform yourself of how Nuitka works. While this was a valid issue, your report sounds like user error of what accelerated does or not.

I am closing this issue early for lack of general interest. Accelerated mode multidist with no follows got to be rare.

**Comment by kayhayen** [comment]
This is part of the stable release 2.4 that I just made.
