### ISSUE TITLE
Use multidist in 2.4rc8 version

### ISSUE THREAD

**Issue by seed93** [Nuitka/Nuitka#2986]
When I try to use `--main` option, I failed to run. This is my test.
```
# a.py
import numpy
print('a')

# b.py
print('b')
```
When I run with `python -m nuitka --main=a.py --main=b.py`, it shows `ModuleNotFoundError: No module named 'numpy'`.
It only works when I add an option `--standalone` or `--follow-imports`, which is not what I want because there maybe thoudsands of packages needed to be imported.

The environment info is below.

Name: Nuitka
Version: 2.4rc8
Summary: Python compiler with full language support and CPython compatibility
Home-page: https://nuitka.net
Author: Kay Hayen
Author-email: Kay.Hayen@gmail.com
License: Apache License, Version 2.0
Location: /usr/local/lib/python3.10/dist-packages
Requires: ordered-set, zstandard
Required-by:

**Comment by kayhayen** [comment]
I don't think it is, I am not convinced you have numpy installed for the version of Python you compile with. Please fill out the issue template completely.
