### ISSUE TITLE
undefined symbol: const_str_plain_split

### ISSUE THREAD

**Issue by n-bes** [Nuitka/Nuitka#2989]
Hi. I built my project with environment variables and latest nuitka (2.3.11): 

```shell
CFLAGS="-g -O0"
CCFLAGS="-g -O0"
CXXFLAGS="-g -O0"
CPPFLAGS="-g -O0"

python3 -m nuitka --module --show-scons --include-package=project_name project_name --lto=yes
```

And while running it is failed with:
```
project_name.cpython-312-aarch64-linux-gnu.so: undefined symbol: const_str_plain_split
```

```shell
readelf -Ws --dyn-syms project_name.cpython-312-aarch64-linux-gnu.so

Symbol table '.dynsym' contains 372 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND
     1: 00000000003015c0     0 SECTION LOCAL  DEFAULT    9 .init
....
   217: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND const_str_plain_split
...
```

I found this line, but not found implementation of this object:

https://github.com/Nuitka/Nuitka/blob/61c6ac3a05b6abf406c8c586ba8920905b37b2ad/nuitka/build/include/nuitka/exception_groups.h#L78

It is not reproduced without envs but with --debug flag:
```
python3 -m nuitka --module --show-scons --include-package=project_name project_name --lto=yes --debug --unstripped
```

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment]
These are fed by the constants blob loading and are supposed to be aliased into a global pool by generated code. However, split was not added yet.

**Comment by kayhayen** [comment]
Oh sorry, fixed that up, please try again.

**Comment by n-bes** [comment]
It works

**Comment by kayhayen** [comment]
This is part of the stable release 2.4 that I just made.
