### ISSUE TITLE
Windows standalone build is unable to find libusb_package

### ISSUE THREAD

**Issue by zakx** [Nuitka/Nuitka#2990]
I am building a script that uses [Bumble](https://google.github.io/bumble/index.html) which pulls in `libusb_package`. Running the .exe results in an exception where a path is not found.

```
Traceback (most recent call last):
  File "C:\Users\zakx\Desktop\dist\SERVER~1.DIS\server.py", line 366, in <module>
  File "C:\Users\zakx\Desktop\dist\SERVER~1.DIS\server.py", line 363, in main
  File "C:\Users\zakx\Desktop\dist\SERVER~1.DIS\asyncio\runners.py", line 194, in run
  File "C:\Users\zakx\Desktop\dist\SERVER~1.DIS\asyncio\runners.py", line 118, in run
  File "C:\Users\zakx\Desktop\dist\SERVER~1.DIS\asyncio\base_events.py", line 687, in run_until_complete
  File "C:\Users\zakx\Desktop\dist\SERVER~1.DIS\server.py", line 298, in run_bt
  File "C:\Users\zakx\Desktop\dist\SERVER~1.DIS\bumble\transport\__init__.py", line 214, in open_transport_or_link
  File "C:\Users\zakx\Desktop\dist\SERVER~1.DIS\bumble\transport\__init__.py", line 93, in open_transport
  File "C:\Users\zakx\Desktop\dist\SERVER~1.DIS\bumble\transport\__init__.py", line 165, in _open_transport
  File "C:\Users\zakx\Desktop\dist\SERVER~1.DIS\bumble\transport\usb.py", line 362, in open_usb_transport
  File "C:\Users\zakx\Desktop\dist\SERVER~1.DIS\bumble\transport\usb.py", line 53, in load_libusb
  File "C:\Users\zakx\Desktop\dist\SERVER~1.DIS\libusb_package\__init__.py", line 51, in get_library_path
  File "C:\Users\zakx\Desktop\dist\SERVER~1.DIS\importlib\resources\_legacy.py", line 25, in wrapper
  File "C:\Users\zakx\Desktop\dist\SERVER~1.DIS\importlib\resources\_legacy.py", line 103, in is_resource
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\zakx\\Desktop\\dist\\SERVER~1.DIS\\libusb_package'
```

Thanks for your help.

# Options used

`python -m nuitka --assume-yes-for-downloads --standalone --main=server.py --windows-uac-admin --no-progressbar --show-progress --msvc=14.3 --include-package=libusb_package --include-package-data=libusb_package`

I got the idea for `--include-package=libusb_package --include-package-data=libusb_package` from [here](https://github.com/Nuitka/Nuitka/issues/2598#issuecomment-1846904739), but adding or removing those has no effect on the outcome.

# Versions

```shell
$ python -m nuitka --version
2.3.11
Commercial: None
Python: 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\gitlab-runner\builds\gQNxy-T7h\0\zakx\simulator\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64\cl.exe (cl 14.3).
```

```shell
$ python -m pip list -v
Package           Version  Location                                                                   Installer
----------------- -------- -------------------------------------------------------------------------- ---------
bumble            0.0.195  C:\gitlab-runner\builds\gQNxy-T7h\0\zakx\simulator\.venv\Lib\site-packages pip
libusb-package    1.0.26.1 C:\gitlab-runner\builds\gQNxy-T7h\0\zakx\simulator\.venv\Lib\site-packages pip
libusb1           3.1.0    C:\gitlab-runner\builds\gQNxy-T7h\0\zakx\simulator\.venv\Lib\site-packages pip
Nuitka            2.3.11   C:\gitlab-runner\builds\gQNxy-T7h\0\zakx\simulator\.venv\Lib\site-packages pip
pip               24.0     C:\gitlab-runner\builds\gQNxy-T7h\0\zakx\simulator\.venv\Lib\site-packages pip
pyusb             1.2.1    C:\gitlab-runner\builds\gQNxy-T7h\0\zakx\simulator\.venv\Lib\site-packages pip
```
(shortened to relevant packages)

# How did you install Nuitka and Python

  Using `pip install nuitka` in a Python 3.12 virtualenv on Windows 11

**Comment by KRRT7** [comment]
could you share a minimal reproducible example.

**Comment by zakx** [comment]
I was trying to set up a minimal reproducible example and while I did this built a GitHub Actions pipeline to build the file. For some reason, the GitHub Actions pipeline is actually able to produce a file that works and has libusb properly bundled. My private GitLab CI runner does not manage to do this. I'm now trying to figure out what the relevant difference between those runs could be. For that reason, I have now enabled diffable reports.

Minimal example: https://github.com/zakx/nuitka-issue-2990-example

## Windows execution output difference

### GitLab version
```
PS C:\Users\zakx\Desktop\dist\run_advertiser.dist> .\run_advertiser.exe device1.json usb:0
DEBUG:asyncio:Using proactor: IocpProactor
<<< connecting to HCI...
Traceback (most recent call last):
  File "C:\Users\zakx\Desktop\dist\RUN_AD~1.DIS\run_advertiser.py", line 72, in <module>
  File "C:\Users\zakx\Desktop\dist\RUN_AD~1.DIS\asyncio\runners.py", line 194, in run
  File "C:\Users\zakx\Desktop\dist\RUN_AD~1.DIS\asyncio\runners.py", line 118, in run
  File "C:\Users\zakx\Desktop\dist\RUN_AD~1.DIS\asyncio\base_events.py", line 687, in run_until_complete
  File "C:\Users\zakx\Desktop\dist\RUN_AD~1.DIS\run_advertiser.py", line 51, in main
  File "C:\Users\zakx\Desktop\dist\RUN_AD~1.DIS\bumble\transport\__init__.py", line 214, in open_transport_or_link
  File "C:\Users\zakx\Desktop\dist\RUN_AD~1.DIS\bumble\transport\__init__.py", line 93, in open_transport
  File "C:\Users\zakx\Desktop\dist\RUN_AD~1.DIS\bumble\transport\__init__.py", line 165, in _open_transport
  File "C:\Users\zakx\Desktop\dist\RUN_AD~1.DIS\bumble\transport\usb.py", line 362, in open_usb_transport
  File "C:\Users\zakx\Desktop\dist\RUN_AD~1.DIS\bumble\transport\usb.py", line 53, in load_libusb
  File "C:\Users\zakx\Desktop\dist\RUN_AD~1.DIS\libusb_package\__init__.py", line 51, in get_library_path
  File "C:\Users\zakx\Desktop\dist\RUN_AD~1.DIS\importlib\resources\_legacy.py", line 25, in wrapper
  File "C:\Users\zakx\Desktop\dist\RUN_AD~1.DIS\importlib\resources\_legacy.py", line 103, in is_resource
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\zakx\\Desktop\\dist\\RUN_AD~1.DIS\\libusb_package'
```

### GitHub version
```
PS C:\Users\zakx\Desktop\dist> .\run_advertiser-github.exe device1.json usb:0
DEBUG:asyncio:Using proactor: IocpProactor
<<< connecting to HCI...
DEBUG:bumble.transport.usb:loading libusb library at C:\Users\zakx\AppData\Local\Temp\ONEFIL~1\libusb_package\libusb-1.0.dll
DEBUG:bumble.transport.usb:USB Device: Bus 001 Device 007: ID 2fe3:000b
DEBUG:bumble.transport.usb:selected endpoints: configuration=1, interface=0, setting=0, acl_in=0x82, acl_out=0x01, events_in=0x81,
DEBUG:bumble.transport.usb:current configuration = 1
DEBUG:bumble.transport.usb:starting USB event loop
<<< connected
[…]
```

For some reason the working version is finding a libusb-1.0.dll file, but in a different location than the GitLab version. The GitLab version seems to be looking in the current directory, while the GitHub version is looking in some temporary folder. I suppose Nuitka is taking care of unpacking dependencies there?

## Differences in installation
### GitLab
On my GitLab CI runner, Nuitka 2.3.11 is installed via pip from Pypy. The Runner is on Windows 11. Windows SDK version 10.0.26100.0. The VSCode compiler version is 14.3. Python 3.12.4 has been manually installed. All the relevant pip versions seem to match.

Used command line options: --standalone --report=report.xml --report-diffable --show-scons --assume-yes-for-downloads --output-dir=build --script-name=run_advertiser.py

### GitHub
Nuitka 2.3.11 [is installed](https://github.com/zakx/nuitka-issue-2990-example/blob/main/.github/workflows/build.yml) via the Nuitka Action; that seems to do a git checkout and builds the requested version manually before installing it locally. The runner is on [Windows Server 2022](https://github.com/actions/runner-images/blob/win22/20240707.1/images/windows/Windows2022-Readme.md). The runner's using Windows SDK '10.0.22621.0' which is slightly older. It's also using MSVC 14.3. Python 3.12.4 was installed by an imported action.

Used command line options: --standalone --report=report.xml --report-diffable --show-scons --assume-yes-for-downloads --output-dir=build --script-name=run_advertiser.py

The most important difference between the two is in the build log, right before the end:
`Nuitka-Plugins:dll-files: Found 1 file DLLs from libusb_package installation.`
That is missing from the GitLab run.

## Reports
[reports.zip](https://github.com/user-attachments/files/16152547/reports.zip)

A quick diff shows that the GitHub report has the following line that the other report does not have.

```xml
<   <included_dll name="libusb-1.0.dll" dest_path="libusb_package\libusb-1.0.dll" source_path="${sys.prefix}\Lib\site-packages\libusb_package\libusb-1.0.dll" package="libusb_package" ignored="no" reason="Yaml config of 'libusb_package'" />
```

Any idea why one invocation of this is unable to find the DLL, even though the relevant versions match? Is it possible that the PyPy version of Nuitka is different to the manually built one from the action?

Again, thank you for your time.

**Comment by zakx** [comment]
Thanks for your hints. Stumbling through the code, I have found the --list-package-dlls command line option that effectively calls that function and tried starting by using that.

```shell
$ python -m nuitka --list-package-dlls=libusb_package
Nuitka-Tools: Checking package directory 'C:\gitlab-runner\builds\gQNxy-T7h\0\zakx\simulator\.venv\Lib\site-packages\libusb_package' ..
Nuitka-Tools: Found 0 DLLs.
```

And in fact, there are no DLLs in that folder. I started to wonder how they would come to be in there anyway, and after some detours (Microsoft Defender, Caches, …) found out that libusb-package does not have wheels for Python 3.12 yet. In fact, the project feels a bit abandoned. However, when there's no wheel available, the build process will try to build libusb on the spot, but critically it will fail silently, leaving you with no DLL and no clue at all.

The building process itself requires the "v142 build tools" (part of Visual Studio 2019). While the libusb-package maintainers state that the free community edition is enough to build it, Microsoft has decided that using older versions of Visual Studio now does require an active MSDN subscription. Looking at the libusb repository, they have already fixed that issue and migrated to a new build file that also supports the current v143 build tools. So I have now forked the libusb-package repo, updated the submodule to a more recent version of libusb with that new VS project file and did some superficial changes to the libusb-package setup.py to accomondate the changes in libusb. (I have also opened [a ticket](https://github.com/pyocd/libusb-package/issues/22) with libusb-package, but don't feel to optimistic about it.)

Trying again, using my libusb-package fork, `pip install` will now build a libusb DLL and Nuitka will correctly find it.

The key takeaway is: **If you use libusb-package, double check that installing it actually provides a DLL file. There is no warning or error while installing it even if it does not.**

So I suppose this issue is now invalid and can be closed. Thank you again for your time and help with this.

**Comment by kayhayen** [comment]
I must have misunderstood you, I was assuming you had used 3.12 on both runners. What I guess can of course happen is that the installation fails silently due to missing headers. I still like your report.

However, it becomes clear that people in CI are compiling often enough on systems incapable of running the software in Python, and that's something to keep in mind, to ask them to test it.

**Comment by zakx** [comment]
No, you are correct, I was running the exact same Python version on both runners.

The difference was that the GitHub runner has a correct toolchain installed and was therefore able to build a DLL locally. To confirm this, I have changed the GitHub Action in my example repo, see https://github.com/zakx/nuitka-issue-2990-example/actions/runs/9891858157/job/27323189586#step:4:107.

(Apparently the Enterprise version of VS2022 can build v142 projects; the Community version I am using certainly could not.)
