### ISSUE TITLE
Functions created with `types.FunctionTypes` segfault

### ISSUE THREAD

**Issue by Hedwyn** [Nuitka/Nuitka#2996]
Hello,
Since the code objects for functions are empty when running nuitka-compiled code, functions created using FunctionTypes with existing code objects will segfault on call.
See this minimum example to reproduce the issue:

```python
from types import FunctionType

def echo(msg: str):
    print(msg)

echo("Hello World")


segfaulting_echo = FunctionType(
    code=echo.__code__,
    globals=echo.__globals__,
    name="segfaulting_echo",
)

segfaulting_echo("Hello World")
```
*Note that the code object itself is not created dynamically with compile() or similar,  it is only a reference to an existing code object*.
Tested on:
**Operating System**: Ubuntu 22 / Kernel 5.15.0 x86_64
**Python** : Python 3.11.9
Tested with Nuitka 2.3.11, with --onefile flag. Installed with `pip`. 

When looking at the back trace in gdb, the segfault happens somewhere in _PyEval_EvalFrameDefault when evaluating the generated function, I'm assuming the segfault occurs when trying to access the pointer to the code object which is most likely NULL.

I'm aware that this use case is not supported by Nuitka (that's not what the issue is about), but it would be nice to detect this sort of violation before going to segfault as this was rather hard to spot in a large codebase and might happen to other people as well. Maybe warnings/errors when generating INCREF on code objects in the C-transpiled user code ?

**Comment by krmckmk** [comment]
güzel fonksyon

**Comment by Rooba** [comment]
https://github.com/Nuitka/Nuitka?tab=readme-ov-file#deep-copying-uncompiled-functions Would that not fall under this?

**Comment by kayhayen** [comment]
Nuitka function objects are having bytecode that does nothing. Copying it is not going to give you what you are looking for, but it should not segfault. I believe we create the code objects in a way that they don't do anything, but apparently that is for whatever reason not happening here.

**Comment by kayhayen** [comment]
Ah, we have there `\0\0` which works for checks of Python core, and for Nuitka to detect it, if it was asked to execute it. Making something that raises a `RuntimeError` would probably be even more robust and useful.

**Comment by kayhayen** [comment]
So, I did that, we need to make a template code object, and now it says this:

```
Nuitka: Launching 'Mini.bin'.
Hello World
Traceback (most recent call last):
  File "/home/hayen/repos/Py2C/Mini.py", line 15, in <module>
    segfaulting_echo("Hello World")
    
  File "/home/hayen/repos/Py2C/Mini.py", line -1, in echo
RuntimeError: Compiled function bytecode used
```

**Comment by Hedwyn** [comment]
Hello Kay,
thank you for your reply, I think getting the function to raise a `RuntimeError` sounds like a good solution. I would maybe suggest if I may to link to some nuitka documentation regarding this limitation in the exception body, as it might not be obvious to users that this error comes from nuitka and is not a Python standard error.

**Comment by kayhayen** [comment]
Yes, some refinements might be good, but anything but a segfault is better enough already.

**Comment by kayhayen** [comment]
This is part of the stable release 2.4 that I just made.
