### ISSUE TITLE
Corrupted sys.argv

### ISSUE THREAD

**Issue by mgeeky** [Nuitka/Nuitka#2997]
Hi!

I've noticed that for some reason, `--onefile` artifacts acquire corrupted `sys.argv`.

Here's an example:

```
cmd> program.exe test
```

Returns output:

```
[program args debug] argv[0]: 坠嵬Ȅ
[program args debug] argv[1]: ᤐ嵬Ȅ
[program args debug] argv[2]: test
usage:

Usage: program.exe [options] <outfile>
坠嵬Ȅ: error: unrecognized arguments: test
```

**Notice chinese unicode characters**. Naturally this breaks my program's ability to process arguments.

This excerpt is _anonymized_ and stripped, but generally my program prints out entire `sys.argv` array before passing it over to `argparse`.

Here're the compilation flags:

```
py -3.11 -m nuitka --msvc=latest --include-data-dir="C:\Program\Path\assets\data=assets\data" --follow-imports --include-module=generators.igenerator --include-plugin-directory="C:\Program\Path\generators" --prefer-source-code --include-module=win32api --include-module=ctypes --noinclude-custom-mode=numpy:nofollow --noinclude-custom-mode=numpy.libs:nofollow --noinclude-custom-mode=matplotlib:nofollow --noinclude-custom-mode=cv2:nofollow --noinclude-custom-mode=PIL:nofollow --noinclude-custom-mode=scipy:nofollow --noinclude-custom-mode=PyQt2:nofollow --noinclude-custom-mode=PyQt3:nofollow --noinclude-custom-mode=PyQt4:nofollow --noinclude-custom-mode=PyQt5:nofollow --noinclude-custom-mode=PyQt6:nofollow --noinclude-custom-mode=PyQt7:nofollow --noinclude-custom-mode=PySide2:nofollow --noinclude-custom-mode=PySide3:nofollow --noinclude-custom-mode=PySide4:nofollow --noinclude-custom-mode=PySide5:nofollow --noinclude-custom-mode=PySide6:nofollow --noinclude-custom-mode=PySide7:nofollow --python-flag=no_site --python-flag=no_docstrings --no-deployment-flag=self-execution --onefile-tempdir-spec="{TEMP}/tmp{PID}_{TIME}" --enable-plugin=pylint-warnings --enable-plugin=data-hiding --enable-plugin=anti-debugger --warn-unusual-code --assume-yes-for-downloads --enable-plugin=upx --upx-binary="C:\Program\Path\release\upx.exe" --windows-console-mode=force -o "program.exe" --onefile --output-dir="C:\Program\Path\release\_temp" "program.py"
```

Nuitka version:

```
2.4rc7
Commercial: 2.6.1
Python: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64\cl.exe (cl 14.3).
```

I suspected this might be due to `upx` compression or `anti-debugger` plugin, but crossed out both after trials and errors.

Cheers,
Mariusz.

**Comment by kayhayen** [comment]
Oh, upx surely could do funny things. I assume you are dumping sys.argv right after execution. I am shocked actually I have to admit, but let me see.

**Comment by kayhayen** [comment]
For me it's reproducible with exactly 2 arguments. Man, I feel bad.

**Comment by kayhayen** [comment]
This somehow has to be at fault, and it's also used when constructing the DLL filename to load. So maybe we are onto the big solution here for the issues observed.

```
void appendCharSafeW(wchar_t *target, char c, size_t buffer_size) {
    char buffer_c[2] = {c, 0};
    wchar_t wide_buffer_c[2];

    size_t res = mbstowcs(wide_buffer_c, buffer_c, 2);
    if (res != 1) {
        abort();
    }

    appendWCharSafeW(target, wide_buffer_c[0], buffer_size);
}
```

**Comment by kayhayen** [comment]
If I change this:

```
-            appendCharSafeW(result, ' ', size);
+            appendWCharSafeW(result, L' ', size);
```

in the bootstrap code, the issue becomes no longer reproducible from a 100% hit rate for 2 args. I would almost be certain that mbsctowcs has no issue to convert the ' ' to a L' ' and yes, it doesn't null terminate, meaning the wide buffer is actually too large, but we pick out only that first character that was created, and in no way should it cause this.

**Comment by kayhayen** [comment]
Somehow this may be AV hating my onefile created occasionally and then not. However, I never have had it happen before. On staging, I have enhanced the command line composition code.

I think my mistake was to get the command line, then calculate its length and then copy the command line over. The "malloc" apparently may get memory associated with the command line. It doesn't matter if I do not free the memory with LocalFree, the input point can become invalid at any time it seems, and be used for my command line. I changed this to use a static buffer, so as to avoid the whole complexity, and now it runs reliably, modulo the 255 errors when launching the Python child, that I have not seen so far.

I will try and make sure, this is not related to the command line change, which would be awful, but something that could be worked around of course, e.g. if the filename of the bootstrap was passed by environment, etc. but this is very confusing to me, since I have allow listed my user there for Windows Defender, and it not blocking the bootstrap, but the extracted executable, it's just nothing I ever saw, and now it seems to happen frequently, but it actually could not be Windows Defender if you know what I mean.

**Comment by kayhayen** [comment]
The code in question was never on the main branch, but I was preparing a release with it for 2.4, so this is a great find, that would have caused a lot of wasted time down the road.

**Comment by mgeeky** [comment]
Happy I could help (by taking yet more of your time ¯\_(ツ)_/¯  ). 

Surely there's something funny going with windows command line conversion and I also had this impression this needs to be related to ascii to multi-byte conversion. Thing is, we cannot resign from multi-byte conversion (the C's `L` prefix) as users need to be able to supply their language local parameters like filenames, titles etc. Conversion is required, but chances are command line buffer is not getting properly terminated causing it read out of bounds, maybe?

Nonetheless, currently, in order to remain able to ship my programs had to come up with nasty workaround that sifts through `sys.argv` and unfilters baddies :)

Cheers,
Mariusz.
