### ISSUE TITLE
UTF-8 mode

### ISSUE THREAD

**Issue by BoboTiG** [Nuitka/Nuitka#300]
*  Nuitka version
```shell
0.6.2
Python: 3.6.8 (default, Feb 19 2019, 16:00:46) 
Executable: /home/tiger-222/projects/ven36/bin/python
OS: Linux
Arch: x86_64
```

*  How did you install Nuitka and Python? Via `pip`.

*  SSCCE ([Short, Self Contained, Correct, Example](http://sscce.org/)):
```python
import sys

print("stderr", sys.stderr)
print("stdin", sys.stdin)
print("stdout", sys.stdout)
```

* Outputs

Call 1:
```shell
$ python3 test.py
stderr <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>
stdin <_io.TextIOWrapper name='<stdin>' mode='r' encoding='UTF-8'>
stdout <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
```

Call 2:
```shell
$ ./test.dist/test
stderr <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>
stdin <_io.TextIOWrapper name='<stdin>' mode='r' encoding='UTF-8'>
stdout <_io.TextIOWrapper name='<stdout>' mode='w' encoding='ascii'>
```
Check the last line showing `ascii`.

Call 3:
```shell
$ PYTHONUTF8 ./test.dist/test
stderr <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>
stdin <_io.TextIOWrapper name='<stdin>' mode='r' encoding='UTF-8'>
stdout <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
```
This is OK actually.

* Compilation

I read #243 and tried both commands with the same result:
```shell
$ python3 -m nuitka --standalone test.py
$ python3 -X utf8 -m nuitka --standalone test.py
```

* Questions

1. My needs are to enable the UTF-8 mode when running the compiled version, without asking a user to set the `PYTHONUTF8=1` envar. I was hoping to use the `--python-flag=utf8` option, but it is not (yet?) implemented.
2. If we do not consider the question 1, I think there is a bug somewhere, right? In `Call 3`, `sys.stdout` should use `UTF-8` encoding rather than `ascii` as this is what is in use by default as seen in `Call 1`.

**Comment by kayhayen** [comment]
@BoboTiG Did you try the develop version? I sort of recall that there was an issue that the `utf8_mode` was implemented, but during re-execution it was forgotten. So normally your commands ought to work, but I consider it's probably not yet released due to this being relatively unimportant.

**Comment by BoboTiG** [comment]
Oh you are totally right. The develop version works like a charm!
Thank you and sorry for missing that easy idea :)
