### ISSUE TITLE
 There is a problem with packaging dependency libraries 

### ISSUE THREAD

**Issue by es3344520** [Nuitka/Nuitka#3001]
I've been stuck in this position for at least 60 minutes during the compilation and packaging process, although I know the dependency library may be a bit large, but not that long. Moreover, the yt_dlp library also provides pre-compiled libraries that can be copied directly and cannot be used directly.   This happens all the time, whether it's automatically identifying dependent libraries, manually copying them, or specifying folders 
Want to know how to solve it? Is there a command to copy directly without compiling the yt_dlp library? All packaged into executive files?  thanks a lot 

 
【 Here are the in-process logs 】

mac@Aloveletterfromyou 22 % nuitka3 --standalone --enable-plugin=tk-inter --macos-create-app-bundle --macos-app-icon=mj.jpg Sp.py
Nuitka-Options: Used command line options: --standalone --enable-plugin=tk-inter
Nuitka-Options: --macos-create-app-bundle --macos-app-icon=mj.jpg Sp.py
Nuitka: Starting Python compilation with Nuitka '2.3.11' on Python '3.11'
Nuitka: commercial grade 'not installed'.
Nuitka-Plugins:options-nanny: Note, when using 'tkinter', consider using        
Nuitka-Plugins:options-nanny: '--macos-create-app-bundle' option. Otherwise high
Nuitka-Plugins:options-nanny: resolution will not be available and a terminal
Nuitka-Plugins:options-nanny: window will open. However for debugging, terminal
Nuitka-Plugins:options-nanny: output is the easiest way to see informative
Nuitka-Plugins:options-nanny: traceback and error information, so launch it from
Nuitka-Plugins:options-nanny: there if possible.
PASS 1: 98.2%|████████████████████████▌| 1613/1643, yt_dlp.extractor.lazy_extrac

**Comment by kayhayen** [comment]
We are working on scalability enhancements, this will become faster, for now it is what it is

**Comment by GSTbyMM** [comment]
Is there any improvement on this since it still gets stuck on this?

**Comment by KRRT7** [comment]
> Is there any improvement on this since it still gets stuck on this?

https://github.com/Nuitka/Nuitka/issues/3269
