### ISSUE TITLE
Recommendations of how to compile PEG parser for xonsh project

### ISSUE THREAD

**Issue by anki-code** [Nuitka/Nuitka#3002]
Hello! Thank you for Nuitka!

In the [xonsh project](https://github.com/xonsh/xonsh) we're going to replace old parser to [PEG parser](https://github.com/xonsh/peg-parser) based on [pegen](https://github.com/we-like-parsers/pegen) - is the parser generator used in CPython to produce the parser used by the interpreter.

May be you can give us advice of how to compile it using Nuitka to achieve best performance? It will be very helpful for us.

Thanks!

**Comment by krmckmk** [comment]
iyi öneriler

**Comment by kayhayen** [comment]
@krmckmk please stick to English, and also don't make useless comments

**Comment by kayhayen** [comment]
Sorry, but getting my advice is something we do not have the time for, for Nuitka commercial sponsors that's different of course, but that's not what we are talking about I guess.
