### ISSUE TITLE
After the script is packaged, although it can run to the program interface, it cannot use the program normally. error occurred 

### ISSUE THREAD

**Issue by es3344520** [Nuitka/Nuitka#3006]
[MAC platform] Nuitka uses the latest version, and Python uses 3.11 
 
As the title says: This script works fine when it is run directly locally or packaged with pyinstaller.

After packaging with Nuitka, the following error occurs. Although the program can be opened normally to enter the interface, it cannot be used, and the binary files and dependent libraries that the program depends on are all there.

It is currently speculated that after Nuitka packaging, the program may have a problem in the process of calling the dependent library to perform the task, resulting in the inability to correctly execute the original task. This problem may be that the dependent library cannot be used correctly or cannot be found.

Of course, the above is just my speculation. Please take a look at the specific problem. Thank you very much
 

【This is an error report】 

Command '['/Users/mac/Desktop/11/cs.app/Contents/MacOS/yt', 'ytsearch1:"Lady Gaga - Just Dance"', '--format', 'bestaudio/best', '--extract-audio', '--audio-format', 'flac', '--audio-quality', '0', '--output', '/Users/mac/Desktop/Lady Gaga - Just Dance.%(ext)s', '--quiet', '--no-playlist', '--no-check-certificate', '--prefer-ffmpeg', '--ffmpeg-location', '/Users/mac/Desktop/11/cs.app/Contents/MacOS/ffmpeg']' returned non-zero exit status 255.

**Comment by kayhayen** [comment]
In the template, we have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that we do not want to be left guessing. For you it's easy to erase the issue template and expect us to ask you questions only as necessary, but we cannot do that. We would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore we are  likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
