### ISSUE TITLE
[URGENT] ERROR

### ISSUE THREAD

**Issue by D3vMohab** [Nuitka/Nuitka#3007]
FATAL: Error, failed to locate package 'zeroconf._services' while trying to look up DLL dependencies, that should not happen. Please report the issue.

I installed zeroconf using pip but Nuitka still cant detect it!

**Comment by Maxwell175** [comment]
In order for your issue to be addressed, you need to provide the information requested in the issue template. We need the Nuitka --version output and a minimal code sample that demonstrates the issue.

**Comment by D3vMohab** [comment]
@Maxwell175 I am trying to compile an app with the pymobiledevice3 library, but it fails because it uses the zeroconf library, can you try to compile an app with the pymobiledevice3 library

I am using Nuitka latest version BTW!
