### ISSUE TITLE
Can Nuitka  support pypy?

### ISSUE THREAD

**Issue by 1234shemingjun** [Nuitka/Nuitka#3013]
My interpreter is PyPy3【3.13】
I tried to build my scripts as single package by pyinstaller, but never work
So
Can Nuitka  support pypy? please help~thanks

**Comment by KRRT7** [comment]
nuitka heavily relies on CPython and the way it works, PyPy works differently so it'll most likely never be supported

**Comment by 1234shemingjun** [comment]
So, Is there anyway can build scripts as single package? with PyPy3 interpreter

> nuitka heavily relies on CPython and the way it works, PyPy works differently so it'll most likely never be supported

**Comment by KRRT7** [comment]
> So, Is there anyway can build scripts as single package? with PyPy3 interpreter
> 
> > nuitka heavily relies on CPython and the way it works, PyPy works differently so it'll most likely never be supported

that's outside the scope of Nuitka, you should ask PyPy about it https://pypy.org/contact.html

**Comment by 1234shemingjun** [comment]
thanks

**Comment by 1234shemingjun** [comment]
thanks
