### ISSUE TITLE
Question about --onefile, --noinclude-dlls and excluded libs search.

### ISSUE THREAD

**Issue by ioctl-user** [Nuitka/Nuitka#3014]
Seems the only method meet the requirement of LGPL license of used libs with onefile option is excluding them from the onefile binary with the "--noinclude-dlls=" option.

However, in this case Nuitka doesn't copy them to the build directory. So, user have to find correct library path in filesystem himself, because he need placing it near onefile binary. This action appears very inconvenient.

Is there any recommended method how to get list of needed libraries paths?

If not, may I suggest adding option that just find not included libraries and print paths to them?

**Comment by kayhayen** [comment]
There are plans to make the onefile archive writable in the sense that the user can replace files, which will be good enough for all I know, in that sense this is a duplicate.
