### ISSUE TITLE
sys.argv is broken in nuitka 2.4 in Windows

### ISSUE THREAD

**Issue by Choonholic** [Nuitka/Nuitka#3015]
**Environments:**
* Windows 11
* Python 3.12.4
* Nuitka 2.4

**Issue symptoms:**

`sys.argv` returns incorrect results:

Command: `abc.exe argv1 argv2`

In Nuitka 2.3.11 - `sys.argv = ['\path\abc.exe', 'argv1', 'argv2']`
But in Nuitka 2.4 - `sys.argv = ['\path\abc.exeargv1', 'argv2']`

**Comment by NinjaCheetah** [comment]
Having this issue as well. Seems exclusive to Windows as my command line app is built for macOS, Windows, and Linux and the macOS and Linux builds continue to function as expected.

**Comment by kayhayen** [comment]
Very strange, I was sure, I had this solved, but apparently not at all. I don't know if you used onefile but I think previous reports said that.

**Comment by kayhayen** [comment]
Ah, this is about a missing separator only, I need to check.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment]
Part of the 2.4.1 hotfix I just made.

**Comment by Choonholic** [comment]
@kayhayen, your fix is working. Thanks!

**Comment by kayhayen** [comment]
@carlos-a-g-h posting below closed issues is a sure fire way to get ignored, open a new issue explaining what you see and expect
