### ISSUE TITLE
FATAL: anti-bloat: Error, condition 'standalone' for module 'tensorflow' did not evaluate to boolean result.

### ISSUE THREAD

**Issue by caglarari** [Nuitka/Nuitka#3016]
Hi,
I installed Nuitka on Google Colab & was trying to see if I can create an extension module with Nuitka that uses tensorflow.
I did try different versions of tensorflow & Nuitka development but nothing changed. I always got the following error message

Nuitka: Starting Python compilation with Nuitka '2.4' on Python '3.10' commercial grade 'not installed'.
FATAL: anti-bloat: Error, condition 'standalone' for module 'tensorflow' did not evaluate to boolean result.
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'.

I was wondering if it Is possible to fix this problem?
Thanks

Here is the notebook code
!pip install -U nuitka
!python -m nuitka --version
!python -m nuitka --module tfmod.py

tfmod.py contents

import tensorflow as tf

def printver():
  print("tf version is "+tf.__version__)

Here is the notebook code with outputs
#!pip install tensorflow==2.8.0
!pip install -U nuitka
#!pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"

Collecting nuitka
  Downloading Nuitka-2.4.tar.gz (3.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 8.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting ordered-set>=4.1.0 (from nuitka)
  Downloading ordered_set-4.1.0-py3-none-any.whl (7.6 kB)
Collecting zstandard>=0.15 (from nuitka)
  Downloading zstandard-0.23.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 20.6 MB/s eta 0:00:00
Building wheels for collected packages: nuitka
  Building wheel for nuitka (pyproject.toml) ... done
  Created wheel for nuitka: filename=Nuitka-2.4-cp310-cp310-linux_x86_64.whl size=3358914 sha256=ac42ac94663da522c6108f00d7c8b2b3fbac919ae7d90d564472fd5ec215fdac
  Stored in directory: /root/.cache/pip/wheels/dd/d4/e8/f6ffeb8e089ca3548810b6d76af7f9a6f2a7d30f58def6a73e
Successfully built nuitka
Installing collected packages: zstandard, ordered-set, nuitka
Successfully installed nuitka-2.4 ordered-set-4.1.0 zstandard-0.23.0

!python -m nuitka --version

2.4
Commercial: None
Python: 3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0]
Flavor: Debian Python
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.3
Version C compiler: /usr/bin/gcc (gcc 11).

!python -m nuitka --module tfmod.py

Nuitka-Options: Used command line options: --module tfmod.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main module. Check options and make sure that is intended.
Nuitka: Starting Python compilation with Nuitka '2.4' on Python '3.10' commercial grade 'not installed'.
FATAL: anti-bloat: Error, condition 'standalone' for module 'tensorflow' did not evaluate to boolean result.
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'.

**Comment by kayhayen** [comment]
Changes to make `--list-package-dlls` enforce standalone mode, had the side effect of changing standalone mode to None, which is not a problem, except for this plugin conditions, going to hotfix that.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment]
Part of the 2.4.1 hotfix I just made.

**Comment by caglarari** [comment]
I installed the factory branch & that one works. 

I tried more complicated things like calling tensorflow.experimental.numpy functions from the modules. They all worked. Thanks.
