### ISSUE TITLE
Failure on trailing forward slash on Windows

### ISSUE THREAD

**Issue by bersbersbers** [Nuitka/Nuitka#3020]
On Windows, nuitka 2.4.0/2.4.1 fail (while 2.3.11 works) for

```
echo.>empty.py
echo.>empty.dat
nuitka --standalone empty.py --include-data-file=empty.dat=folder/
```

Output:
```
Nuitka-Options: Used command line options: empty.py --include-data-file=folder/empty.dat=folder/
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure that is intended.
Nuitka: Starting Python compilation with Nuitka '2.4.1' on Python '3.12' commercial grade 'not installed'.
FATAL: Error, cannot add data file with 'folder/empty.dat' path, as 'contains illegal character '/''
```

It would be helpful if the same function call could be used on Windows and Linux.

**Comment by kayhayen** [comment]
I agree, that's not nice. Slashes are usually being converted no problem, the trailing slash is causing an issue, because somewhere a normpath is missing, I will remove that need.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment]
Part of the 2.4.2 hotfix release I just made.

**Comment by bersbersbers** [comment]
Thanks!

**Comment by cfcurtis** [comment]
Hi, sorry to resurrect an old bug, but I'm getting an error with forward slashes in the middle of the path. I'm using the GitHub action, here's the relevant error message:

```bash
Nuitka: Starting Python compilation with Nuitka '2.4.4' on Python '3.8' commercial grade 'not installed'.
FATAL: Error, cannot add data file with 'resources/locale\babel.cfg' path, as 'contains illegal character '/''
```
