### ISSUE TITLE
Quoted arguments including spaces parsed incorrectly on Windows (Nutika 2.4/2.4.1)

### ISSUE THREAD

**Issue by NinjaCheetah** [Nuitka/Nuitka#3021]
**Nuitka Version:**
```
2.4.1
Commercial: None
Python: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\campb\Documents\Code\Python\WiiPy\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64\cl.exe (cl 14.3).
```
Installed normally from PyPI.

**Description:**
On Windows, when you pass arguments in quotes that include spaces, the spaces don't get included as part of the quoted string and the argument gets separated. Seems to be present in both 2.4 and 2.4.1. Also tested on Nuitka 2.4.1 on Linux, and this issue does not occur there. Reverting to Nuitka 2.3.11 on Windows shows that this was working before the 2.4 release.

**Command:** `program.exe arg1 "arg 2"`

**Value of `sys.argv`:**
Nuitka 2.3.11: `['\path\to\program.exe', 'arg1', 'arg 2']`
Nuitka 2.4/2.4.1: `['\path\to\program.exe', 'arg1', 'arg', '2']`

**Comment by kayhayen** [comment]
Thanks for the report, this is actually way more difficult than it should be, seems while Windows can partition arguments with APIs, it cannot re-assemble it easily, but I found code that I can emulate and handles escapes of "\" and quotes correctly too.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment]
This will be in the hotfix 2.4.2 shortly too.

**Comment by kayhayen** [comment]
Part of the 2.4.2 hotfix release I just made.

**Comment by NinjaCheetah** [comment]
Seems to be working as expected in the hotfix!
