### ISSUE TITLE
FATAL: implicit-imports: Plugin issue while working on 'module 'pydantic'

### ISSUE THREAD

**Issue by Cabyy** [Nuitka/Nuitka#3023]
I got a error with the command

python -m nuitka --standalone --show-memory --show-progress --follow-imports --include-plugin-directory=belt_server/startup,belt_server/api main.py

Any one help?
Thanks.

Nuitka-Progress: Optimizing module 'pydantic', 142 more modules to go after that.
Nuitka-Memory: Total memory usage before optimizing module 'pydantic': 748.17 MB (784510976 bytes)
Nuitka-Plugins:WARNING: implicit-imports: Problem locating 'pydantic' for implicit imports of '.main'.
PASS 1: 75.5%|██████████████████▉      | 441/584, pydanticTraceback (most recent call last):
  File "/Users/bytensor/python_env/belt_venv/lib/python3.9/site-packages/nuitka/plugins/Plugins.py", line 69, in withPluginProblemReporting
    yield
  File "/Users/bytensor/python_env/belt_venv/lib/python3.9/site-packages/nuitka/plugins/Plugins.py", line 521, in considerImplicitImports
    cls._considerImplicitImports(plugin=plugin, module=module)
  File "/Users/bytensor/python_env/belt_venv/lib/python3.9/site-packages/nuitka/plugins/Plugins.py", line 424, in _considerImplicitImports
    module_filename = plugin.locateModule(full_name)
  File "/Users/bytensor/python_env/belt_venv/lib/python3.9/site-packages/nuitka/plugins/PluginBase.py", line 729, in locateModule
    _module_name, module_filename, _module_kind, _finding = locateModule(
  File "/Users/bytensor/python_env/belt_venv/lib/python3.9/site-packages/nuitka/importing/Importing.py", line 827, in locateModule
    assert module_package is None or (
AssertionError: <ModuleName ''>
FATAL: implicit-imports: Plugin issue while working on 'module 'pydantic''. Please report the bug with the above traceback included.
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'.

And this is the log file. It's a xml file.
[nuitka-crash-report.txt](https://github.com/user-attachments/files/16358505/nuitka-crash-report.txt)

Nuitka  2.5rc1

**Comment by kayhayen** [comment]
The part where is says `Nuitka-Plugins:WARNING: implicit-imports: Problem locating 'pydantic' for implicit imports of '.main'.` is sort of wrong already. I wonder if it somehow picked the idea of that module name up from your usages of `--include-plugin-directory`. Can you specify a file listing of these?

**Comment by Cabyy** [comment]
Thanks very much.

These are my files:

(base) bytensor@Tongcais-Mac-mini belt_server % ll -R api                                           
total 104
drwxr-xr-x  15 bytensor  staff   480B Jul 24 17:27 .
drwxr-xr-x  14 bytensor  staff   448B Jul 24 17:27 ..
-rw-r--r--   1 bytensor  staff   958B Dec 11  2023 __init__.py
drwxr-xr-x   7 bytensor  staff   224B Jul 24 17:27 admin
drwxr-xr-x  25 bytensor  staff   800B Jul 24 17:27 app
-rw-r--r--   1 bytensor  staff   1.9K Apr 30 10:47 basic.py
-rw-r--r--   1 bytensor  staff   3.3K Dec 11  2023 constraint.py
-rw-r--r--   1 bytensor  staff   3.4K Dec 11  2023 interface.py
-rw-r--r--   1 bytensor  staff   3.3K Dec 11  2023 menu.py
-rw-r--r--   1 bytensor  staff   4.3K Mar  4 14:24 middleware.py
drwxr-xr-x  14 bytensor  staff   448B Jul 24 17:27 response_model
-rw-r--r--   1 bytensor  staff    12K Dec 11  2023 role.py
-rw-r--r--   1 bytensor  staff   4.2K Dec 11  2023 router.py
-rw-r--r--   1 bytensor  staff   1.4K Dec 11  2023 utils.py
drwxr-xr-x   5 bytensor  staff   160B Jul 24 17:27 wechat_official_account

api/admin:
total 40
drwxr-xr-x   7 bytensor  staff   224B Jul 24 17:27 .
drwxr-xr-x  15 bytensor  staff   480B Jul 24 17:27 ..
-rw-r--r--   1 bytensor  staff     0B Dec 11  2023 __init__.py
-rw-r--r--   1 bytensor  staff   598B Mar  4 14:24 app.py
-rw-r--r--   1 bytensor  staff   2.3K Dec 11  2023 auth.py
-rw-r--r--   1 bytensor  staff   3.0K Mar  4 14:24 login.py
-rw-r--r--   1 bytensor  staff   6.1K Dec 11  2023 user.py

api/app:
total 184
drwxr-xr-x  25 bytensor  staff   800B Jul 24 17:27 .
drwxr-xr-x  15 bytensor  staff   480B Jul 24 17:27 ..
-rw-r--r--   1 bytensor  staff     0B Dec 11  2023 __init__.py
-rw-r--r--   1 bytensor  staff   2.2K Apr 30 10:47 app.py
-rw-r--r--   1 bytensor  staff   746B Jan 29 14:21 auth.py
drwxr-xr-x  14 bytensor  staff   448B Jul 24 17:27 customer
-rw-r--r--   1 bytensor  staff   680B Dec 11  2023 evaluation.py
-rw-r--r--   1 bytensor  staff   1.9K Mar  4 14:24 evaluation_breath.py
-rw-r--r--   1 bytensor  staff   3.2K Apr 30 10:47 evaluation_history.py
-rw-r--r--   1 bytensor  staff   1.8K Mar  4 14:24 evaluation_pabd.py
-rw-r--r--   1 bytensor  staff   2.6K Mar  4 14:24 evaluation_pabd_angle.py
-rw-r--r--   1 bytensor  staff   955B Mar  4 14:24 firmware.py
-rw-r--r--   1 bytensor  staff   657B Jan 16  2024 monitor.py
-rw-r--r--   1 bytensor  staff   2.0K Mar  4 14:24 monitor_dynamic_breath.py
-rw-r--r--   1 bytensor  staff   2.0K Mar  4 14:24 monitor_static_trunk.py
-rw-r--r--   1 bytensor  staff   1.7K Dec 11  2023 posture.py
-rw-r--r--   1 bytensor  staff   2.8K Dec 11  2023 report_form.py
-rw-r--r--   1 bytensor  staff   3.0K Apr 30 10:47 train.py
-rw-r--r--   1 bytensor  staff   4.9K Apr 30 10:47 train_plan.py
-rw-r--r--   1 bytensor  staff   3.2K Apr 30 10:47 train_plan_history.py
-rw-r--r--   1 bytensor  staff   665B Apr 30 10:47 train_plan_prompt.py
-rw-r--r--   1 bytensor  staff   2.3K Jan 16  2024 train_pro.py
-rw-r--r--   1 bytensor  staff   5.7K Apr 30 10:47 trainee.py
-rw-r--r--   1 bytensor  staff   1.6K Dec 11  2023 user.py
-rw-r--r--   1 bytensor  staff   3.3K Jul 19 12:34 wechat.py

api/app/customer:
total 96
drwxr-xr-x  14 bytensor  staff   448B Jul 24 17:27 .
drwxr-xr-x  25 bytensor  staff   800B Jul 24 17:27 ..
-rw-r--r--   1 bytensor  staff     0B Mar  4 14:24 __init__.py
-rw-r--r--   1 bytensor  staff   1.7K Mar  4 14:24 app.py
-rw-r--r--   1 bytensor  staff   898B Mar  4 14:24 basic.py
-rw-r--r--   1 bytensor  staff   2.5K Mar  4 14:24 coach.py
-rw-r--r--   1 bytensor  staff   1.3K Mar  4 14:24 faq.py
-rw-r--r--   1 bytensor  staff   690B Mar  4 14:24 feedback.py
-rw-r--r--   1 bytensor  staff   2.9K Mar  4 14:24 login.py
-rw-r--r--   1 bytensor  staff   2.0K Apr 30 10:47 train.py
-rw-r--r--   1 bytensor  staff   5.6K Apr 30 10:47 train_plan.py
-rw-r--r--   1 bytensor  staff   3.3K Apr 30 10:47 train_plan_history.py
-rw-r--r--   1 bytensor  staff   1.6K Mar  4 14:24 user.py
-rw-r--r--   1 bytensor  staff   3.9K Mar  4 14:24 wechat.py

api/response_model:
total 104
drwxr-xr-x  14 bytensor  staff   448B Jul 24 17:27 .
drwxr-xr-x  15 bytensor  staff   480B Jul 24 17:27 ..
-rw-r--r--   1 bytensor  staff     0B Dec 11  2023 __init__.py
drwxr-xr-x   8 bytensor  staff   256B Jul 24 17:27 admin
drwxr-xr-x  23 bytensor  staff   736B Jul 24 17:27 app
-rw-r--r--   1 bytensor  staff   3.8K Apr 30 10:47 basic.py
-rw-r--r--   1 bytensor  staff   3.3K Dec 11  2023 constraint.py
-rw-r--r--   1 bytensor  staff   2.5K Mar  4 14:24 file.py
-rw-r--r--   1 bytensor  staff   4.4K Dec 11  2023 interface.py
-rw-r--r--   1 bytensor  staff   6.3K Dec 11  2023 menu.py
-rw-r--r--   1 bytensor  staff   2.0K Apr 30 10:47 obs.py
-rw-r--r--   1 bytensor  staff    11K Dec 11  2023 role.py
-rw-r--r--   1 bytensor  staff   4.6K Dec 11  2023 router.py
drwxr-xr-x   6 bytensor  staff   192B Jul 24 17:27 wechat_official_account

api/response_model/admin:
total 72
drwxr-xr-x   8 bytensor  staff   256B Jul 24 17:27 .
drwxr-xr-x  14 bytensor  staff   448B Jul 24 17:27 ..
-rw-r--r--   1 bytensor  staff   466B Apr 30 10:47 __init__.py
-rw-r--r--   1 bytensor  staff   1.1K Mar  4 14:24 app.py
-rw-r--r--   1 bytensor  staff   2.6K Apr 30 10:47 auth.py
-rw-r--r--   1 bytensor  staff   1.4K Dec 11  2023 login.py
-rw-r--r--   1 bytensor  staff    14K Apr 30 10:47 user.py
-rw-r--r--   1 bytensor  staff   136B Dec 11  2023 utils.py

api/response_model/app:
total 480
drwxr-xr-x  23 bytensor  staff   736B Jul 24 17:27 .
drwxr-xr-x  14 bytensor  staff   448B Jul 24 17:27 ..
-rw-r--r--   1 bytensor  staff     0B Dec 11  2023 __init__.py
-rw-r--r--   1 bytensor  staff   2.5K Dec 11  2023 app.py
drwxr-xr-x  10 bytensor  staff   320B Jul 24 17:27 customer
-rw-r--r--   1 bytensor  staff   2.2K Apr 30 10:47 evaluation.py
-rw-r--r--   1 bytensor  staff    21K Jul 19 11:39 evaluation_breath.py
-rw-r--r--   1 bytensor  staff    24K Jul 19 11:39 evaluation_history.py
-rw-r--r--   1 bytensor  staff    17K Jul 19 11:39 evaluation_pabd.py
-rw-r--r--   1 bytensor  staff    19K Jul 19 11:39 evaluation_pabd_angle.py
-rw-r--r--   1 bytensor  staff   2.2K Dec 11  2023 firmware.py
-rw-r--r--   1 bytensor  staff   2.2K Jan 16  2024 monitor.py
-rw-r--r--   1 bytensor  staff    16K Jul 19 11:39 monitor_dynamic_breath.py
-rw-r--r--   1 bytensor  staff    15K Jul 19 11:39 monitor_static_trunk.py
-rw-r--r--   1 bytensor  staff   1.9K Dec 11  2023 posture.py
-rw-r--r--   1 bytensor  staff    11K Dec 11  2023 report_form.py
-rw-r--r--   1 bytensor  staff    17K Apr 30 10:47 train.py
-rw-r--r--   1 bytensor  staff    13K Jul 19 11:39 train_plan.py
-rw-r--r--   1 bytensor  staff   6.7K Jul 22 14:51 train_plan_history.py
-rw-r--r--   1 bytensor  staff    17K Jul 19 11:39 train_pro.py
-rw-r--r--   1 bytensor  staff    10K Apr 30 10:47 trainee.py
-rw-r--r--   1 bytensor  staff   2.0K Dec 11  2023 user.py
-rw-r--r--   1 bytensor  staff   3.7K Dec 12  2023 wechat.py

api/response_model/app/customer:
total 80
drwxr-xr-x  10 bytensor  staff   320B Jul 24 17:27 .
drwxr-xr-x  23 bytensor  staff   736B Jul 24 17:27 ..
-rw-r--r--   1 bytensor  staff   3.2K Mar  4 14:24 coach.py
-rw-r--r--   1 bytensor  staff   2.8K Mar  4 14:24 faq.py
-rw-r--r--   1 bytensor  staff   960B Mar  4 14:24 feedback.py
-rw-r--r--   1 bytensor  staff   2.2K Mar  4 14:24 login.py
-rw-r--r--   1 bytensor  staff   4.2K Jul 22 14:54 train_plan.py
-rw-r--r--   1 bytensor  staff   2.4K Jul 22 14:49 train_plan_history.py
-rw-r--r--   1 bytensor  staff   4.8K Mar  4 14:24 user.py
-rw-r--r--   1 bytensor  staff   2.7K Mar  4 14:24 wechat.py

api/response_model/wechat_official_account:
total 32
drwxr-xr-x   6 bytensor  staff   192B Jul 24 17:27 .
drwxr-xr-x  14 bytensor  staff   448B Jul 24 17:27 ..
-rw-r--r--   1 bytensor  staff     0B Dec 11  2023 __init__.py
-rw-r--r--   1 bytensor  staff   2.5K Dec 11  2023 claim_result.py
-rw-r--r--   1 bytensor  staff   7.6K Dec 11  2023 receive_msg.py
-rw-r--r--   1 bytensor  staff   893B Dec 11  2023 xml_support.py

api/wechat_official_account:
total 24
drwxr-xr-x   5 bytensor  staff   160B Jul 24 17:27 .
drwxr-xr-x  15 bytensor  staff   480B Jul 24 17:27 ..
-rw-r--r--   1 bytensor  staff   409B Dec 11  2023 __init__.py
-rw-r--r--   1 bytensor  staff   883B Dec 11  2023 claim_result.py
-rw-r--r--   1 bytensor  staff   1.7K Dec 11  2023 receive_msg.py


(base) bytensor@Tongcais-Mac-mini belt_server % ll -R startup 
total 104
drwxr-xr-x  14 bytensor  staff   448B Jul 24 17:27 .
drwxr-xr-x  14 bytensor  staff   448B Jul 24 17:27 ..
-rw-r--r--   1 bytensor  staff     0B Dec 11  2023 __init__.py
-rw-r--r--   1 bytensor  staff   1.5K Dec 11  2023 api.py
-rw-r--r--   1 bytensor  staff   821B Apr 30 10:47 encrypt.py
-rw-r--r--   1 bytensor  staff   2.4K Dec 11  2023 handlers.py
-rw-r--r--   1 bytensor  staff   4.3K Dec 11  2023 id.py
-rw-r--r--   1 bytensor  staff   1.6K Dec 11  2023 logger.py
-rw-r--r--   1 bytensor  staff   5.1K Jul 19 11:39 main.py
-rw-r--r--   1 bytensor  staff   3.9K Apr 30 10:47 obs.py
drwxr-xr-x   5 bytensor  staff   160B Jul 24 17:27 router
-rw-r--r--   1 bytensor  staff   8.5K Jul 19 11:39 service.py
-rw-r--r--   1 bytensor  staff   334B Dec 11  2023 startup_logger.py
drwxr-xr-x  22 bytensor  staff   704B Jul 24 17:27 storage

startup/router:
total 16
drwxr-xr-x   5 bytensor  staff   160B Jul 24 17:27 .
drwxr-xr-x  14 bytensor  staff   448B Jul 24 17:27 ..
-rw-r--r--   1 bytensor  staff     0B Dec 11  2023 __init__.py
-rw-r--r--   1 bytensor  staff   1.6K Dec 11  2023 main_router.py
-rw-r--r--   1 bytensor  staff   1.1K Dec 11  2023 wechat_official_account_router.py

startup/storage:
total 184
drwxr-xr-x  22 bytensor  staff   704B Jul 24 17:27 .
drwxr-xr-x  14 bytensor  staff   448B Jul 24 17:27 ..
-rw-r--r--   1 bytensor  staff   1.1K Apr 30 10:47 __init__.py
-rw-r--r--   1 bytensor  staff   999B Mar  4 14:24 auth_storage_factory.py
-rw-r--r--   1 bytensor  staff   931B Dec 11  2023 coach_storage_factory.py
-rw-r--r--   1 bytensor  staff   368B Dec 11  2023 counter_storage_factory.py
-rw-r--r--   1 bytensor  staff   1.5K Dec 11  2023 evaluation_storage_factory.py
-rw-r--r--   1 bytensor  staff   339B Mar  4 14:24 faq_storage_factory.py
-rw-r--r--   1 bytensor  staff   404B Mar  4 14:24 feedback_storage_factory.py
-rw-r--r--   1 bytensor  staff   375B Dec 11  2023 file_storage_factory.py
-rw-r--r--   1 bytensor  staff   365B Apr 30 10:47 oss_storage_factory.py
-rw-r--r--   1 bytensor  staff   3.2K Dec 11  2023 rbac_storage_factory.py
-rw-r--r--   1 bytensor  staff   2.1K Apr 30 10:47 result_storage_factory.py
-rw-r--r--   1 bytensor  staff   328B Mar  4 14:24 sms_storage_factory.py
-rw-r--r--   1 bytensor  staff    13K Jul 15 17:44 storage_factory.py
-rw-r--r--   1 bytensor  staff   416B Dec 11  2023 sys_config_storage_factory.py
-rw-r--r--   1 bytensor  staff   1.7K Apr 30 10:47 train_plan_storage_factory.py
-rw-r--r--   1 bytensor  staff   1.3K Apr 30 10:47 trainee_storage_factory.py
-rw-r--r--   1 bytensor  staff   530B Dec 11  2023 user_storage_factory.py
-rw-r--r--   1 bytensor  staff   700B Dec 11  2023 version_storage_factory.py
-rw-r--r--   1 bytensor  staff   359B Jan 16  2024 video_storage_factory.py
-rw-r--r--   1 bytensor  staff   1.1K Dec 11  2023 wechat_resource_storage_factory.py

**Comment by kayhayen** [comment]
I don't see anything there, however, I will try and find out from where `.main` can originate. We check for valid module names normally, and chances are we can move the error earlier, but I will need to make code changes for that, but it won't be long.

**Comment by kayhayen** [comment]
So, first thing, the message has arguments reversed. It should have been:

> Nuitka-Plugins:WARNING: implicit-imports: Problem locating '.main' for implicit imports of 'pydantic'.

So this is probably `pydantic.main` we are talking about. I need to check it, but I believe the PyI parser may output that, but should have resolved it actually, but maybe for extension modules that are packages, it does it wrong.

**Comment by kayhayen** [comment]
Can you provide the version of pydantic you are using?

**Comment by kayhayen** [comment]
I found it in the report, and managed to reproduce it myself, this is for pydantic alone.

**Comment by Cabyy** [comment]
Thank you.
The version of pydantic is 1.9.0

**Comment by Cabyy** [comment]
@sullivan50909 
Thank you.  It worked when I turn back  the version to 2.3.11.

But I got another error:
FATAL: Error, failed to locate package 'pydantic' while trying to look up DLL dependencies, that should not happen. Please report the issue.

And this time not xml file gived.

**Comment by kayhayen** [comment]
Once a new release happen, you can consider the older ones unsupported for anything but my commercial customers. I reproduced and fixed the error, which is the parsing of the Python source as if it was a .pyi file, and there should be a fix somewhere shorty, it didn't make it into 2.4.2 but I have it somewhere, not sure now where it's at this time.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by Cabyy** [comment]
@kayhayen Thank you. I'll try it later.

**Comment by Cabyy** [comment]
Grate! It works well. Thank you.

**Comment by kayhayen** [comment]
Part of the 2.4.4 hotfix I just made
