### ISSUE TITLE
Executable fails to run on other devices due to error with cariocffi

### ISSUE THREAD

**Issue by geekblack22** [Nuitka/Nuitka#3025]
Hi am trying to use Nuitka to create and executable for an application that uses cariosvg, I installed GTK3 runtime installer but when I move the executable to another machine I get this error(I am on windows 11, python 3.10 and nuitka 2.3.11):
`Temp\ONEFIL~1\cairocffi_init_.py", line 57, in dlopen
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo.so.2'
cannot load library 'libcairo.2.dylib': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo.2.dylib'
cannot load library 'libcairo-2.dll': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo-2.dll' `
Here is the command that I ran:
`python -m nuitka --msvc=latest --assume-yes-for-downloads --onefile --onefile-windows-splash-screen-image=.\python\imgs\Logo.png $(MAIN_SCRIPT) --include-module=can.interfaces.pcan  --enable-plugin=pyside6  --include-data-files=env\Lib\site-packages\cairosvg\VERSION=VERSION  --output-dir=dist/ --output-filename=$(EXECUTABLE_NAME).exe`
Here is my pip freeze:
`blatann==0.5.0
Brotli==1.1.0
cairocffi==1.7.1
CairoSVG==2.7.1
can-isotp==1.9
canopen==2.2.0
cffi==1.16.0
contourpy==1.2.1
cryptography==42.0.8
cssselect2==0.7.0
cycler==0.12.1
defusedxml==0.7.1
fastcrc==0.3.0
fonttools==4.53.1
gitdb==4.0.11
GitPython==3.1.27
inflate64==1.0.0
kids.cache==0.0.7
kiwisolver==1.4.5
libsass==0.23.0
lxml==5.2.2
matplotlib==3.7.0
mock==5.1.0
multivolumefile==0.2.3
Nuitka==2.3.11
numpy==1.22.0
ordered-set==4.1.0
packaging==24.1
pandas==2.0.2
pc-ble-driver-py==0.17.0
perlin-noise==1.12
pillow==10.4.0
psutil==6.0.0
py7zr==0.21.0
pybcj==1.0.2
pycparser==2.22
pycryptodomex==3.20.0
pyparsing==3.1.2
pyppmd==1.1.0
pyserial==3.5
PySide6==6.7.2
PySide6_Addons==6.7.2
PySide6_Essentials==6.7.2
python-can==4.3.1
python-dateutil==2.9.0.post0
pytz==2024.1
pywin32==306
pyzstd==0.16.0
QT-PyQt-PySide-Custom-Widgets==1.0.2
QtAwesome==1.3.1
QtPy==2.4.1
qtsass==0.4.0
shiboken6==6.7.2
six==1.16.0
smmap==5.0.1
termcolor==2.4.0
texttable==1.7.0
tinycss2==1.3.0
typing_extensions==4.12.2
tzdata==2024.1
watchdog==4.0.1
webencodings==0.5.1
wrapt==1.16.0
zstandard==0.23.0`

**Comment by kayhayen** [comment]
Being asked on discord to raise an issue, doesn't mean the issue template doesn't apply to you. please retry, this time with the template filled out.
