### ISSUE TITLE
When compiling to an extension module, Python classes inheriting from PySide2 classes can no longer override virtual methods

### ISSUE THREAD

**Issue by briankendall** [Nuitka/Nuitka#303]
- version:    
        `0.6.3rc3`
        `Python: 2.7.10 (default, Aug 17 2018, 19:45:58)`
        `Executable: /usr/bin/python`
        `OS: Darwin`
        `Arch: x86_64`
- checked out Nuitka repo at commit b84034
- installed using setuptools

Here is an example program that demonstrates the problem:

```
from PySide2.QtWidgets import QApplication, QWidget

class MyWindow(QWidget):
    def mousePressEvent(self, event):
        print "Press!"

def run():
    app = QApplication([])
    window = MyWindow()
    window.setFixedSize(300, 200)
    window.show()
    app.exec_()
```
To see it working properly, save that code to a python file (e.g. `test.py`), run python, import it and then execute `run()`:
```
$ python
>>> import test
>>> test.run()
```
A window will open, and if you click the window it will print the text "Press!"

If I convert it to an extension module using Nuitka, i.e. `nuitka --module test.py` and then repeat the same procedure, the window will open but clicking on it will not print "Press!".

What seems to be going wrong is that `mousePressEvent` is not properly overriding the same virtual function on the `QWidget` C++ class when compiled with Nuitka.

As a side note, I'd just like to say that Nuitka is a very impressive project!

**Comment by kayhayen** [comment]
Thanks for the compliment, unfortunately PySide2 is unsupported, see #255 and #224 and there is nobody who is contributing the patches for it to work to the PySide source. Last time we did it, for PySide1, it was not integrated due to PySide2 coming. And recent reports have not gained any priority on their side yet.

Therefore I recommend to use PyQt, which has been a very good citizen and accepted our contributions each time.

**Comment by briankendall** [comment]
Alas I am stuck with PySide2 at the moment due to the restrictions of my project. However I did find a workaround for this issue that I'll post here just in case it helps someone else in the future.

In my particular use case I'm only compiling some of my python modules into extension modules, so I can leave around some regular python or bytecode files. The workaround is to have an uncompiled file that acts as a shim around one of PySide's classes and reimplements any virtual methods. Then my compiled modules import and subclass from that.

Here's an updated version of my above example with the fix:

shim.py:
```
from PySide2.QtWidgets import QWidget

class QWidgetShim(QWidget):
    def mousePressEvent(self, event):
        self._mousePressEvent(event)
```

test.py:
```
from PySide2.QtWidgets import QApplication
from PySide2.QtCore import Signal, SIGNAL
from shim import QWidgetShim

class MyWindow(QWidgetShim):
    doThing = Signal()
    
    def __init__(self, parent=None):
        super(MyWindow, self).__init__(parent)
        self.doThing.connect(self.blah)
    
    def _mousePressEvent(self, event):
        self.doThing.emit()
    
    def blah(self):
        print "Press!"

def run():
    app = QApplication([])
    window = MyWindow()
    window.setFixedSize(300, 200)
    window.show()
    app.exec_()
```
This works correctly if I compile test.py using Nuitka and leave shim.py uncompiled.

**Comment by andrewleech** [comment]
FYI I've just been blocked by the same issue and pinged the matching pyside2 ticket: https://bugreports.qt.io/browse/PYSIDE-829
pyside2 development is very active, perhaps they'll be more interested in fixing the issue there than then original pyside1 issue.

**Comment by andrewleech** [comment]
Hi @kayhayen I've had some feedback from pyside2 / qt 
> Hey Andrew Leech, sadly that old patch doesn't do the trick to solve the issue.
> I tried them in the past, and didn't properly work:
> 
> https://codereview.qt-project.org/c/pyside/pyside-setup/+/230712
> 
> Even now applying the same patch on the newer source code, it doesn't work.

> I'm really ignorant on how nuitka works, but I really don't understand how we can fix this from our side, since for me it's more like 'copying the right things' in the 'proper location'.
> 
> Do you know if someone can provide a more detailed analysis on the issue from the nuitka point of view?

I too don't understand the inner workings enough to provide much input, would you be able to elaborate on the issue at all?
