### ISSUE TITLE
Handle exit signal with --windows-console-mode=attach

### ISSUE THREAD

**Issue by Sash0check** [Nuitka/Nuitka#3034]
```
2.4.3
Commercial: None
Python: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: .venv\Scripts\python.exe
OS: Windows
```

Python installed via python website as standalone
Nuitka installed via pip install nuitka

The specific PyPI names and versions:
None

compile command
```
python -m nuitka --standalone example.py  --windows-console-mode=attach
```

example code:
```python
import os
import signal
import time
from multiprocessing import Process
import win32api


def handle_exit(signal):
    print('KILL', signal)
    with open('output.txt', 'w') as f:
        f.write('KILLL')
    # sys.exit(1)


# signal.signal(signal.CTRL_BREAK_EVENT, handle_exit)
# signal.signal(signal.SIGTERM, handle_exit)
# signal.signal(signal.SIGBREAK, handle_exit)
win32api.SetConsoleCtrlHandler(handle_exit, True)


def start_gui():
    master_pid = os.getppid()
    os.kill(master_pid, signal.CTRL_BREAK_EVENT)


if __name__ == '__main__':
    p = Process(target=start_gui)
    p.start()
    while 1:
        print('example')
        time.sleep(0.1)
```

Error Log
```
Traceback (most recent call last):
  File "F:\Projects\ub\example.dist\example.py", line 16, in <module>
  File "F:\Projects\ub\example.dist\example.py", line 7, in get_hardware_id
  File "F:\Projects\ub\example.dist\subprocess.py", line 421, in check_output
  File "F:\Projects\ub\example.dist\subprocess.py", line 503, in run
  File "F:\Projects\ub\example.dist\subprocess.py", line 837, in __init__
  File "F:\Projects\ub\example.dist\subprocess.py", line 1272, in _get_handles
OSError: [WinError 6] The handle is invalid

```

Question:
I'm trying to handle kill signal. Handler work only if app launched from console. If the application is not launched from the console, then the handler does not work. I tried to use 'os.kill(master_pid, signal.SIGTERM)' or psutil 'send_signal' for kill app. And 'win32api.SetConsoleCtrlHandler' or 'signal.signal(signal.SIGTERM)'. Also tried different singals. How do I achieve the result? Thank you!

**Comment by kayhayen** [comment]
Something in your report doesn't add up. Anyway, Console APIs work only for console applications, refer to MS documentation, generally you might want to use the Python signal module it seems.

**Comment by Sash0check** [comment]
Sorry, log was copied from previous issue (edited). Python singal module was tested too

**Comment by kayhayen** [comment]
I don't know what was tested or how, since you didn't include any information about that. Open a new issue if you have something, but don't expect Win32 Console API to work with GUI applications. Make it work with `pythonw.exe` and if you find something incompatible, then I am interested, not so much in telling you how things work.
