### ISSUE TITLE
[BUG]UnicodeDecodeError on nuitka 2.4

### ISSUE THREAD

**Issue by sena-nana** [Nuitka/Nuitka#3039]
## Summary

After I updated to Nuitka version 2.4, a UnicodeDecodeError error was reported. Whereas the same project was working fine in version 2.3.11. By catching the error code, I got the exception file as main.build/ccache-48748.txt, whose text encoding is GB2312, I think it has something to do with my operating system which is Chinese.

## Output

```
Nuitka-Options: Used command line options:
Nuitka-Options: --standalone
Nuitka-Options: --windows-icon-from-ico=./icon.ico
Nuitka-Options: --onefile --mingw64
Nuitka-Options: --product-name=name
Nuitka-Options: --product-version=0.3.0
Nuitka-Options: --copyright=Sena-nana
Nuitka-Options: --deployment
Nuitka-Options: --nofollow-import-to=nuitka,debugpy
Nuitka-Options: --output-filename=Server.exe
Nuitka-Options: main.py
Nuitka: Starting Python compilation with Nuitka
Nuitka: '2.4.5' on Python '3.12' commercial grade
Nuitka: 'not installed'.
Nuitka: Completed Python level compilation and  
Nuitka: optimization.
Nuitka: Generating source code for C backend     
Nuitka: compiler.
Nuitka: Running data composer tool for optimal
Nuitka: constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: gcc (gcc
Nuitka-Scons: 13.2.0).
Nuitka-Scons: Backend linking program with 232  
Nuitka-Scons: files (no progress information     
Nuitka-Scons: available for this stage).
Traceback (most recent call last):
  File "E:\myproject\.venv\Lib\site-packages\nuitka\__main__.py", line 206, in <module>
    main()
  File "E:\myproject\.venv\Lib\site-packages\nuitka\__main__.py", line 188, in main
    MainControl.main()
  File "E:\myproject\.venv\Lib\site-packages\nuitka\MainControl.py", line 1155, in main
    _main()
  File "E:\myproject\.venv\Lib\site-packages\nuitka\MainControl.py", line 1004, in _main
    result, scons_options = compileTree()        
                            ^^^^^^^^^^^^^        
  File "E:\myproject\.venv\Lib\site-packages\nuitka\MainControl.py", line 919, in compileTree
    result, scons_options = runSconsBackend()    
                            ^^^^^^^^^^^^^^^^^    
  File "E:\myproject\.venv\Lib\site-packages\nuitka\MainControl.py", line 767, in runSconsBackend
    runScons(
  File "E:\myproject\.venv\Lib\site-packages\nuitka\build\SconsInterface.py", line 403, in runScons
    checkCachingSuccess(source_dir or options["source_dir"])
  File "E:\myproject\.venv\Lib\site-packages\nuitka\build\SconsCaching.py", line 336, in checkCachingSuccess
    stats = _getCcacheStatistics(ccache_logfile) 
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "E:\myproject\.venv\Lib\site-packages\nuitka\build\SconsCaching.py", line 282, in _getCcacheStatistics        
    for line in getFileContentByLine(ccache_logfile, encoding="utf8"):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\myproject\.venv\Lib\site-packages\nuitka\utils\FileOperations.py", line 793, in getFileContentByLine      
    return getFileContents(filename, mode, encoding=encoding).splitlines()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\myproject\.venv\Lib\site-packages\nuitka\utils\FileOperations.py", line 811, in getFileContents
    return f.read()
           ^^^^^^^^
  File "C:\Users\user\.rye\py\cpython@3.12.3\Lib\codecs.py", line 707, in read
    return self.reader.read(size)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.rye\py\cpython@3.12.3\Lib\codecs.py", line 507, in read
    newchars, decodedbytes = self.decode(data, self.errors)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 9663: invalid continuation byte
Nuitka-Reports: Compilation crash report written 
Nuitka-Reports: to file
Nuitka-Reports: 'nuitka-crash-report.xml'. Please
Nuitka-Reports: include it in your bug report.
```

## Command

```
nuitka main.py
```

```
# Compilation mode, support OS-specific options
# nuitka-project: --standalone
# nuitka-project: --windows-icon-from-ico=./icon.ico
# nuitka-project: --onefile
# nuitka-project: --mingw64
# nuitka-project: --product-name=name
# nuitka-project: --product-version=0.3.0
# nuitka-project: --copyright=Sena-nana
# nuitka-project: --deployment
# nuitka-project: --nofollow-import-to=nuitka,debugpy
# nuitka-project: --output-filename=Server.exe
```

## System Information

```
>>> nuitka --version                                   
2.4.5
Commercial: None                                 
Python: 3.12.3 (main, Apr 15 2024, 17:48:16) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: E:\myproject\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe (cl 14.3).
```

**Comment by kayhayen** [comment]
So, I had crashes before from users that were using cp950 or so local encoding, and switched to UTF8 blindly, what encoding is that file then, I need to research.

**Comment by kayhayen** [comment]
Can you provide the `ccache.*.txt` from the build folder, so I can see what it is? I made the python live in a Chinese folder, the cache dir in a Chinese folder and used Chinese module names, and I couldn't find anything non-ASCII in the ccache log file on my system. So I need an example from you.

**Comment by sena-nana** [comment]
Of course, I processed the personal information, and I kept the original data for the rest of the content.I don't think it's probably a Chinese path issue though, since my paths are all ascii and only the system uses Chinese encoding.
There are Chinese characters in the file though, so I thought maybe it might be causing the problem? I replaced them with non-private Chinese characters, and hopefully it still retains the original effect.
[ccache-33452.txt](https://github.com/user-attachments/files/16455774/ccache-33452.txt)

**Comment by kayhayen** [comment]
It says `GB18030` by uchardet, but of course, with your manual manipulation, I cannot tell if that's real. That would be your actual system locale maybe, which is probably what is used with the other cases too. As it is kind of a bug to expose the C compiler to any such kind of paths, we can sort of expect it to be ascii encoding actually, except the hostname. I will add something that filters the text contents to remove the hostname information.

**Comment by sena-nana** [comment]
Thanks for your work.

**Comment by byeblack** [comment]
I found that errors similar to the following often occur when compiling on v2.4.5:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 5389912: invalid start byte
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug
Nuitka-Reports: report.

After following up, I found the following problems:
[2024-08-02T09:35:51.422430 13340] Could not acquire C:\Users\xx\AppData\Local\Nuitka\Nuitka\Cache\ccache/1/c/stats.lock: 另一个程序正在使用此文件，进程无法访问。 (32)

And because "另一个程序正在使用此文件，进程无法访问。" is not in English, it causes the above problem.

**Comment by CCKNBC** [comment]
At least in the `2.4.2` version there is no problem, but upgrading to `2.4.5` will result in encoding errors

```
<nuitka-compilation-report nuitka_version="2.4.5" nuitka_commercial_version="not installed" completion="exception">
  <exception exception_type="UnicodeDecodeError" exception_value="'utf-8' codec can't decode byte 0xc1 in position 1160399: invalid start byte">
Traceback (most recent call last):
  File "d:\Projects\Company\Auto-Report\.venv\Lib\site-packages\nuitka\MainControl.py", line 1155, in main
    _main()
  File "d:\Projects\Company\Auto-Report\.venv\Lib\site-packages\nuitka\MainControl.py", line 1004, in _main
    result, scons_options = compileTree()
                            ^^^^^^^^^^^^^
  File "d:\Projects\Company\Auto-Report\.venv\Lib\site-packages\nuitka\MainControl.py", line 919, in compileTree
    result, scons_options = runSconsBackend()
                            ^^^^^^^^^^^^^^^^^
  File "d:\Projects\Company\Auto-Report\.venv\Lib\site-packages\nuitka\MainControl.py", line 767, in runSconsBackend
    runScons(
  File "d:\Projects\Company\Auto-Report\.venv\Lib\site-packages\nuitka\build\SconsInterface.py", line 403, in runScons
    checkCachingSuccess(source_dir or options["source_dir"])
  File "d:\Projects\Company\Auto-Report\.venv\Lib\site-packages\nuitka\build\SconsCaching.py", line 336, in checkCachingSuccess
    stats = _getCcacheStatistics(ccache_logfile)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Projects\Company\Auto-Report\.venv\Lib\site-packages\nuitka\build\SconsCaching.py", line 282, in _getCcacheStatistics
    for line in getFileContentByLine(ccache_logfile, encoding="utf8"):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Projects\Company\Auto-Report\.venv\Lib\site-packages\nuitka\utils\FileOperations.py", line 793, in getFileContentByLine
    return getFileContents(filename, mode, encoding=encoding).splitlines()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Projects\Company\Auto-Report\.venv\Lib\site-packages\nuitka\utils\FileOperations.py", line 811, in getFileContents
    return f.read()
           ^^^^^^^^
  File "D:\Program Files\Python-3.11\Lib\codecs.py", line 707, in read
    return self.reader.read(size)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python-3.11\Lib\codecs.py", line 507, in read
    newchars, decodedbytes = self.decode(data, self.errors)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 1160399: invalid start byte
</exception>
```

**Comment by kayhayen** [comment]
It says `GB18030` by uchardet, but of course, with your manual manipulation, I cannot tell if that's real. That would be your actual system locale maybe, which is probably what is used with the other cases too. As it is kind of a bug to expose the C compiler to any such kind of paths, we can sort of expect it to be ascii encoding actually, except the hostname. I will add something that filters the text contents to remove the hostname information.

**Comment by kayhayen** [comment]
The inability to acquire the lock of @byeblack made me think, that's another path not shortened, and exposing ccache.exe to it, is wrong, since it very likely cannot handle this kind of file path properly. We have seen before that for some Chinese paths, the short path doesn't change to a 8.3 form that is ASCII, and that's an issue that i have no solution for. The code clearly tries it:

```
        # Unless asked to do otherwise, store ccache files in our own directory.
        if "CCACHE_DIR" not in os.environ:
            ccache_dir = getCacheDir("ccache")
            makePath(ccache_dir)
            ccache_dir = getExternalUsePath(ccache_dir)
            setEnvironmentVariable(env, "CCACHE_DIR", ccache_dir)
            env["CCACHE_DIR"] = ccache_dir
```

So, that's something I don't even know how to solve.

**Comment by kayhayen** [comment]
@CCKNBC the fix is currently on factory only, try that please

**Comment by kayhayen** [comment]
@byeblack the code that i cited, can you make sure it is ran during your compilation, and that indeed `ccache_dir` has Chinese characters. If that is what's going on, the use of absolute paths is problematic there, and maybe using `..\..` style paths will work for more things, but it would only be a stop gap, if you have your user name in any folder name of the compilation stage.

**Comment by byeblack** [comment]
> @byeblack the code that i cited, can you make sure it is ran during your compilation, and that indeed `ccache_dir` has Chinese characters. If that is what's going on, the use of absolute paths is problematic there, and maybe using `..\..` style paths will work for more things, but it would only be a stop gap, if you have your user name in any folder name of the compilation stage.

I am sure that all the paths are in English, including the project's dependent packages, the project's path, and my system username. I tried to remove the cache and recompile, but it still has the same problem. This may be because my project has too many dependencies (including pandas, playwright, and slint, etc., with nearly 2,000 C source codes), so there is a file lock problem, and my operating system interface uses Chinese so the error is Chinese, but after writing to cchace-*.txt, it appears as garbled characters (opening the file with UTF-8 encoding is similar to this: Could not acquire C:\Users\xx\AppData\Local\Nuitka\Nuitka\Cache\ccache/1/c/stats.lock: ��һ����������ʹ�ô��ļ��������޷�����ʡ� (32)). This kind of problem may also occur when I compile a project with smaller dependencies. I don't want to revert to 2.4.0-2.4.3 because playwright gets stuck when launching the browser, and 2.3.11 makes playwright work but doesn't compile if the PYI file contains non-English multi-line comments ("""). 😫

**Comment by SakuraMaiii** [comment]
> > @byeblack the code that i cited, can you make sure it is ran during your compilation, and that indeed `ccache_dir` has Chinese characters. If that is what's going on, the use of absolute paths is problematic there, and maybe using `..\..` style paths will work for more things, but it would only be a stop gap, if you have your user name in any folder name of the compilation stage.
> 
> I am sure that all the paths are in English, including the project's dependent packages, the project's path, and my system username. I tried to remove the cache and recompile, but it still has the same problem. This may be because my project has too many dependencies (including pandas, playwright, and slint, etc., with nearly 2,000 C source codes), so there is a file lock problem, and my operating system interface uses Chinese so the error is Chinese, but after writing to cchace-*.txt, it appears as garbled characters (opening the file with UTF-8 encoding is similar to this: Could not acquire C:\Users\xx\AppData\Local\Nuitka\Nuitka\Cache\ccache/1/c/stats.lock: ��һ����������ʹ�ô��ļ��������޷�����ʡ� (32)). This kind of problem may also occur when I compile a project with smaller dependencies. I don't want to revert to 2.4.0-2.4.3 because playwright gets stuck when launching the browser, and 2.3.11 makes playwright work but doesn't compile if the PYI file contains non-English multi-line comments ("""). 😫
> 
> PS. Finally, I compiled my project completely in Windows Sandbox and it ran perfectly, although it still had problems like Could not acquire C:\Users\WDAGUT~1\AppData\Local\Nuitka\Nuitka\Cache\ccache/lock/auto_cleanup.lock: The process cannot access the file because it is being used by another process. (32) , but because it was an English error, there was no problem like "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 1160399: invalid start byte " that could not compile.



hi,I encountered the same problem： _UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 2175177: invalid start byte_.

I made sure all the *py files were UTF-8 and deleted the ccache folder before running it again, but it still doesn't work.have you solved it?

**Comment by byeblack** [comment]
> > > @byeblack the code that i cited, can you make sure it is ran during your compilation, and that indeed `ccache_dir` has Chinese characters. If that is what's going on, the use of absolute paths is problematic there, and maybe using `..\..` style paths will work for more things, but it would only be a stop gap, if you have your user name in any folder name of the compilation stage.
> > 
> > 
> > I am sure that all the paths are in English, including the project's dependent packages, the project's path, and my system username. I tried to remove the cache and recompile, but it still has the same problem. This may be because my project has too many dependencies (including pandas, playwright, and slint, etc., with nearly 2,000 C source codes), so there is a file lock problem, and my operating system interface uses Chinese so the error is Chinese, but after writing to cchace-*.txt, it appears as garbled characters (opening the file with UTF-8 encoding is similar to this: Could not acquire C:\Users\xx\AppData\Local\Nuitka\Nuitka\Cache\ccache/1/c/stats.lock: ��һ����������ʹ�ô��ļ��������޷�����ʡ� (32)). This kind of problem may also occur when I compile a project with smaller dependencies. I don't want to revert to 2.4.0-2.4.3 because playwright gets stuck when launching the browser, and 2.3.11 makes playwright work but doesn't compile if the PYI file contains non-English multi-line comments ("""). 😫
> > PS. Finally, I compiled my project completely in Windows Sandbox and it ran perfectly, although it still had problems like Could not acquire C:\Users\WDAGUT~1\AppData\Local\Nuitka\Nuitka\Cache\ccache/lock/auto_cleanup.lock: The process cannot access the file because it is being used by another process. (32) , but because it was an English error, there was no problem like "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 1160399: invalid start byte " that could not compile.
> 
> hi,I encountered the same problem： _UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 2175177: invalid start byte_.
> 
> I made sure all the *py files were UTF-8 and deleted the ccache folder before running it again, but it still doesn't work.have you solved it?

You need to set the operating system language to English.

**Comment by magicacgn** [comment]
I modified this section to fix the issue

**Comment by magicacgn** [comment]
I modified this section to fix the issue   
C:\Users\magicspace\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\build\SconsCaching.py

for line in getFileContentByLine(ccache_logfile, encoding="utf8"): 
->
for line in getFileContentByLine(ccache_logfile, ): #encoding="utf8"

**Comment by kayhayen** [comment]
So, if ccache does native encoding, I wonder why we had encoding errors before. Nobody should have to change anything about their system btw, since Nuitka is supposed to work on beginner systems without that kind of need.

However, ever since I made that change, to not parse in system encoding, the number of reports have exploded, so I think I will revert it and make sure the next time, somebody reports an encoding issue with it, that it's subjected to more scrutiny.

**Comment by djhj-YR** [comment]
I had used nuitka ( for compiling EXE ) so many times, no error . But today once I upgrade all software packages via pip , afterwards I encountered such issue , too. 
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 246421: invalid start byte...
I checked the relevant xml file : <nuitka-compilation-report nuitka_version="2.5rc3" nuitka_commercial_version="not installed" completion="exception">
  <exception exception_type="UnicodeDecodeError" exception_value="'utf-8' codec can't decode byte 0xc1 in position 183608: invalid start byte">
Traceback (most recent call last):
...
  Since there are some Chinese characters in the Python scripts. I have to use another solution: 
within the Control Panel, navigate to the [Clock and Region] section and click on [Region]. In the [Region] window that appears, locate and select the [Administration] tab. On the [Administration] tab, locate the option labelled "Beta: Use Unicode UTF-8 in worldwide languages" within the "Change system locale" section. Then I must restart computer then compile one-file EXE via nuitka , I made it ! The relevant EXE file works well.
 BTW if I change the following script of Python311\Lib\site-packages\nuitka\build\SconsCaching.py :
 for line in getFileContentByLine(ccache_logfile, encoding="utf8"):
->
for line in getFileContentByLine(ccache_logfile, ): #encoding="utf8"
  Although the nuitka is able to compile one-file EXE , but the EXE is not good, always crashes ( for every time)...
FYI.

**Comment by djhj-YR** [comment]
I also found out a solution to workaround : don't upgrade nuitka from previous version, just uninstall (python -m pip uninstall nuitka ) then delete everything in the nuitka folder (Python311\Lib\site-packages\nuitka) , afterwards I installed fresh new version of nuitka (e.g. # Develop version ; python -m pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip") , then I compiled one-file EXE , it works ! (Even I created one-file unitka  option especially for external tools , under PYCharm, no error found ...)

**Comment by CCKNBC** [comment]
> I had used nuitka ( for compiling EXE ) so many times, no error . But today once I upgrade all software packages via pip , afterwards I encountered such issue , too. UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 246421: invalid start byte... I checked the relevant xml file : Traceback (most recent call last): ... Since there are some Chinese characters in the Python scripts. I have to use another solution: within the Control Panel, navigate to the [Clock and Region] section and click on [Region]. In the [Region] window that appears, locate and select the [Administration] tab. On the [Administration] tab, locate the option labelled "Beta: Use Unicode UTF-8 in worldwide languages" within the "Change system locale" section. Then I must restart computer then compile one-file EXE via nuitka , I made it ! The relevant EXE file works well. BTW if I change the following script of Python311\Lib\site-packages\nuitka\build\SconsCaching.py : for line in getFileContentByLine(ccache_logfile, encoding="utf8"): -> for line in getFileContentByLine(ccache_logfile, ): #encoding="utf8" (no need to enable "Beta: Use Unicode UTF-8 in worldwide languages" option of Windows control panel.) The nuitka was able to compile one-file EXE , but I didn't test such EXE , at least I have another way to fix the issue... FYI.

This does work without changing the system language, it looks as if there is a pull request for a fix, not sure if the factory branch works without these changes, haven't tested it yet, but as the developer said we shouldn't have to go and change the system settings, looking forward to version 2.5 to fix it.

**Comment by kayhayen** [comment]
I am reverting all changes for the next hotfix, and then I think it's different people for whom it's not working. We will need to not just assume we can force it to be ASCII, seems untrue for error messages. And we cannot assume it's UTF8. There error that had been raised before, which looked like system encoding wasn't cutting it, will reappear and then we analyse it. I expect to make the 2.4.6 release later today and then it will be back to as good as it was. Next change will then need more careful consideration. So far using UTF8 was commonly the solution for many things.

**Comment by kayhayen** [comment]
I have since release 2.4.6, please open a new issue for anything that looks the same. The original report making me do it, had the same symptom, and will be back, but I need clean and full reports, ideally with the ccache file provided and sys.filesystemencoding or whatever it is, I will add that to --report outputs for 2.5 also.
