### ISSUE TITLE
ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by tiebanluyu** [Nuitka/Nuitka#3041]
ValueError: list.remove(x): x not in list
the reason of the bug looks tiny
[nuitka-crash-report.zip](https://github.com/user-attachments/files/16480693/nuitka-crash-report.zip)

**Comment by KRRT7** [comment]
The issue template contains the guidance on how to properly support issues. If you ignore it, likely the issue will be closed as invalid. We cannot really make guesses.

fill out the template.
