### ISSUE TITLE
[Question] Does Nuitka support multiprocessing?

### ISSUE THREAD

**Issue by anzhi0708** [Nuitka/Nuitka#3050]
I've been using it for years now, 
thanks for your hard work :3

I don't know if the executable file obtained after compilation will crash when running multiple processes.
Any suggestions? Thanks ^^

**Comment by Dnyarri** [comment]
I used multiprocessing (pool, to be specific) for one of my programs. After compiling with Nuitka it works as expected, i.e. load all CPUs, works twice as fast as its single-process parent, and work a bit faster than Python original (not dramatic but statistically significant).

**Comment by anzhi0708** [comment]
> I used multiprocessing (pool, to be specific) for one of my programs. After compiling with Nuitka it works as expected, i.e. load all CPUs, works twice as fast as its single-process parent, and work a bit faster than Python original (not dramatic but statistically significant).

Thanks for reply ^^
