### ISSUE TITLE
Multicore execution - Do Binaries compiled by Nuitka, run concurrently unlike Phyton?

### ISSUE THREAD

**Issue by volkan-akkus-tr** [Nuitka/Nuitka#3056]
I am searching for a solution to make a large Phyton codebase to run on multiple threads, concurrently. It is not possible, as you already know, due to Python's Global Interpreter Lock (GIL).

Does Nuitka help me with that?
What do you suggest?

Thanks for your time.

**Comment by KRRT7** [comment]
Nuitka does not help with this, however [python 3.13](https://peps.python.org/pep-0703/) is dropping the GIL, and nuitka will be supporting that aspect of python.

**Comment by kayhayen** [comment]
Outside of that, Nuitka only supports Python level solutions like multiprocessing, thread pools, etc. so you first get to solve this yourself, and then Nuitka has that too. With 3.13 no-GIL simple threads will be good enough and no multiprocessing is needed, but that's a bit off in the future for real applications.
