### ISSUE TITLE
Please add Anti injection to the Nutika exe to prevent dlls to be injected into it like pyshell and more

### ISSUE THREAD

**Issue by mosol1** [Nuitka/Nuitka#3057]

**Comment by KRRT7** [comment]
this is  a commercial feature i believe https://nuitka.net/doc/commercial.html, @kayhayen would have to confirm

**Comment by kayhayen** [comment]
Indeed, that's outside of the scope of free Nuitka, and would be in Nuitka VM, currently called Nuitka Themida at the time of this writing: https://nuitka.net/doc/bundles.html
