### ISSUE TITLE
Executable built from Nuitka running in free-threaded python binary results in GIL'ed executable binary

### ISSUE THREAD

**Issue by jimkring** [Nuitka/Nuitka#3061]
Related to #2834 (Python 3.13 support ), I have been doing some testing of the latest Nuikta dev and Python 3.13rc1.

I tried building a stand-alone executable using free-threaded (NOGIL) python in Windows, but it appears that the GIL is enabled in the final executable binary created by Nuitka.

My `main.py` (that I'm building into an EXE) looks like the following:
```python
# main.py
import sys
import sysconfig

gill_enabled = sys._is_gil_enabled()
Py_GIL_DISABLED = sysconfig.get_config_var("Py_GIL_DISABLED")

print(f"sys._is_gil_enabled(): {gill_enabled}")
print(f"sysconfig.get_config_var(\"Py_GIL_DISABLED\"): {Py_GIL_DISABLED}")
```

When I do a build the resulting `main.exe` prints out the following values (indicating that the GIL is enabled):

```
sys._is_gil_enabled(): True
sysconfig.get_config_var("Py_GIL_DISABLED"): 0
```

Note the command used for the build is the following:
```
C:\Python313\python3.13t.exe -m pip install --no-cache-dir -r requirements.txt        
C:\Python313\python3.13t.exe -m nuitka --assume-yes-for-downloads --standalone main.py
```

And, also note that `python3.13t.exe` is the free-threaded python binary and this is installed *along-side* the GIL'ed binary by choosing the `Include_freethreaded=1` option during installation.  This results in `python.exe` and `python3.13t.exe` living side-by-side.  Perhaps nuitka is assuming that the build should be using the GIL'ed python due to naming of the binaries or something?

If you would like to reproduce or look at the logs, I'm doing this in a GH Action:
https://github.com/jimkring/nuitka-nogil-testing/actions/runs/10363080292/job/28686110659

In the build process, I'm also running `main.py` from source before the build, just to prove that the GIL is disabled (as I would expect) in the free-threaded python:
```
Run C:\Python313\python3.13t.exe main.py
  C:\Python313\python3.13t.exe main.py
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
sys._is_gil_enabled(): False
sysconfig.get_config_var("Py_GIL_DISABLED"): 1
```

Again, it's only the built exe that shows the problem:
```
Run .\main.dist\main.exe
  .\main.dist\main.exe
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
sys._is_gil_enabled(): True
sysconfig.get_config_var("Py_GIL_DISABLED"): 0
```

**Comment by kayhayen** [comment]
There was a mistake in Scons, where the wrong link library was using on Windows, and that got fixed. This specific problem is gone, but free threaded itself doesn't work.
