### ISSUE TITLE
Error using on Windows `Nuitka does not work in --standalone or --onefile on Windows without.` needs more explaination

### ISSUE THREAD

**Issue by abhishekbhakat** [Nuitka/Nuitka#3065]
Command used :
```
python -m nuitka `
          --follow-imports `
          --onefile `
          --file-version=0.3.0 `
          --product-version=0.3.0 `
          --lto=yes `
          --noinclude-data-files=plotly/package_data/templates/*.json `
          --noinclude-data-files=plotly/package_data/datasets/*.csv.gz `
          --noinclude-data-files=plotly/package_data/datasets/*.geojson.gz `
          --output-filename=somebinary.exe `
          script.py
```

Was trying it in GitHub workflows. The error message is very weird and looks like an incomplete sentence, perhaps. Without what? `.`? What is the command we are supposed to use? Was not able to find ref to this in docs.

**Comment by kayhayen** [comment]
In the template, we have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that we do not want to be left guessing. For you it's easy to erase the issue template and expect us to ask you questions only as necessary, but we cannot do that. We would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore we are  likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."

**Comment by abhishekbhakat** [comment]
Not all issues created always can be an issue. Some things can be just a discussion. Some projects have [GitHub Discussions](https://docs.github.com/en/discussions), Nuitka doesn't. So even for a simple discussion, the requirement is to fill out the template. Anyways, it's just a thought. 
I'll create another issue following the template.
