### ISSUE TITLE
coremltools package gives fatal error on MacOS

### ISSUE THREAD

**Issue by dryarullin** [Nuitka/Nuitka#3070]
The _coremltools_ library gives a fatal error on MacOS:

`FATAL: Error, failed to find path @rpath/libcoremlpython.dylib (resolved DLL to /env/lib/python3.11/site-packages/coremltools/libcoremlpython.dylib) for/env/lib/python3.11/site-packages/coremltools/libcoremlpython.so from 'coremltools', please report the bug.`

>python -m nuitka --version
```
2.4.5
Commercial: None
Python: 3.11.9 (v3.11.9:de54cf5be3, Apr  2 2024, 07:12:50) [Clang 13.0.0 (clang-1300.0.29.30)]
Flavor: CPython Official
Executable: /envt/bin/python3.11
OS: Darwin
Arch: arm64
macOSRelease: 14.5
Version C compiler: /usr/bin/clang (clang 15.0.0).
```

>Minimal example on MacOS

```
import coremltools as ct
print(ct.version.__version__)
```

>python3 -m pip freeze
```
nuitka==2.4.5
coremltools==7.2
```

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment]
So, this is a case, where a `.dylib` file has a dependency on itself, but is using a `.so` name for that. Added support for that in both directions to happen.

**Comment by dryarullin** [comment]
Thanks!

**Comment by kayhayen** [comment]
Part of the current hotfix release 2.4.9
