### ISSUE TITLE
nuitka cannot find black.cache when packaging black

### ISSUE THREAD

**Issue by daironxuan** [Nuitka/Nuitka#3074]
```python
"""
Created by: xiaoyu
Date: 2024/8/18
File: black_test
"""
import black

print(black.cache.CACHE_DIR)
```

##### nuitka --msvc=latest --standalone --onefile --show-progress --output-dir=builder_release_black --include-package=black --include-package=black.cache --include-package=black.files --include-package=black.mode --include-package=black.output black_test.py

builder_release_black>black_test.exe
Traceback (most recent call last):
  File "C:\Users\Lenvo\AppData\Local\Temp\ONEFIL~1\black_test.py", line 6, in <module>
  File "src\black\__init__.py", line 38, in <module>
ModuleNotFoundError: No module named 'black.cache'; 'black' is not a package

it seems that only black packaging failed

**Comment by kayhayen** [comment]
In the template, we have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that we do not want to be left guessing. For you it's easy to erase the issue template and expect us to ask you questions only as necessary, but we cannot do that. We would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore we are  likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
