### ISSUE TITLE
match-case statement causes segfault

### ISSUE THREAD

**Issue by 124C41p** [Nuitka/Nuitka#3075]
When compiling this snippet

```python3
class Foo:
    x: int
    y: int

foo = Foo()
foo.y = 1

match foo:
    case Foo(x=x):
        print(f"{x=}")
    case Foo(y=y):
        print(f"{y=}")
```

with `nuitka --standalone` on Linux, or with `nuitka --standalone --mingw64` on Windows, the resulting executable immediately crashes due to a segmentation fault.

**Environment**
```
> python -m nuitka --version
2.4.7
Commercial: None
Python: 3.11.9 (main, Apr  2 2024, 08:25:04) [GCC 13.2.0]
Flavor: Unknown
Executable: /home/erik/deleteme/nuitka-debugging/.venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Nixos 24.05
Version C compiler: ~/.nix-profile/bin/gcc (gcc 13.2.0).
```

**How I installed Nuitka and Python**

Nuitka was installed by pip (`pip install nuitka`) into a virtual environment created by `python -m venv`. Under Linux, I used my system's Python. Under Windows, Python was installed by the official Python installer.

**The specific PyPI names and versions**

```
> python -m pip list -v
Package     Version Location                                                                Installer
----------- ------- ----------------------------------------------------------------------- ---------
Nuitka      2.4.7   /home/erik/deleteme/nuitka-debugging/.venv/lib/python3.11/site-packages pip
ordered-set 4.1.0   /home/erik/deleteme/nuitka-debugging/.venv/lib/python3.11/site-packages pip
pip         24.0    /home/erik/deleteme/nuitka-debugging/.venv/lib/python3.11/site-packages pip
setuptools  65.5.0  /home/erik/deleteme/nuitka-debugging/.venv/lib/python3.11/site-packages pip
zstandard   0.23.0  /home/erik/deleteme/nuitka-debugging/.venv/lib/python3.11/site-packages pip
```

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment]
Was attempting to release match args for a class that provided none in case of attribute lookup errors.
