### ISSUE TITLE
Can not compile the code with paddleOCR 

### ISSUE THREAD

**Issue by Endymionasda** [Nuitka/Nuitka#3076]
The test code is very simple.

from paddleocr import PaddleOCR
engine = PaddleOCR(use_angle_cls=True, lang="ch", use_gpu=True)
output = engine.ocr('1.png')

G:\EVEjsq\Scripts\python.exe -m nuitka --standalone --onefile --show-progress --show-scons --output-dir=E:\dabao --windows-console-mode=force E:\EVEG\test\test.py

Tips missing framework_pb2.py module，But even though I manually supplemented the dist folder with this file framework_pb2.py, it still doesn't work and prompts winerror 2.

**Comment by KRRT7** [comment]
can you share the error output?

**Comment by kayhayen** [comment]
@KRRT7 what is the status of this, do we close/delete this for lack of feedback, what about your PR there? I asked if the change that is in there would be good, but got no feedback yet.

**Comment by kayhayen** [comment]
I can just merge what you got there right now then, even if incomplete, it is a better starting position either way
