### ISSUE TITLE
onefile bootstrap binary build failed as it couldn't find C++ compiler

### ISSUE THREAD

**Issue by ad1b003** [Nuitka/Nuitka#3078]
while trying
`python -m nuitka --mingw64 --clang --standalone --onefile --onefile-windows-splash-screen-image=G:\tkinter-projects\mfms\business-analyst.png --enable-plugin=tk-inter --windows-console-mode=disable --windows-icon-from-ico=icon.ico --plugin-enable=upx --upx-binary="G:/tkinter-projects/mfms/FinanceManagementSystem.exe"  FinanceManagementSystem.py`

it throws
```
-enable=upx --upx-binary="G:/tkinter-projects/mfms/FinanceManagementSystem.exe"  FinanceManagementSystem.py;4504406e-f0d7-4f24-8a93-35e0e7617f2dNuitka-Options: Used command line options: --mingw64 --clang --standalone --onefile
Nuitka-Options: --onefile-windows-splash-screen-image=G:\tkinter-projects\mfms\business-analyst.png --enable-plugin=tk-inter
Nuitka-Options: --windows-console-mode=disable --windows-icon-from-ico=icon.ico --plugin-enable=upx
Nuitka-Options: --upx-binary=G:/tkinter-projects/mfms/FinanceManagementSystem.exe FinanceManagementSystem.py
Nuitka-Plugins:anti-bloat: Not including 'PIL.ImageQt' automatically in order to avoid bloat, but this may cause: PIL will not be able to
Nuitka-Plugins:anti-bloat: create Qt image objects.
Nuitka-Plugins:anti-bloat: Not including 'socket' automatically in order to avoid bloat, but this may cause: can break calls of
Nuitka-Plugins:anti-bloat: 'email.utils.make_msgid()'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.                        
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\clang.exeNuitka-Scons: (clang.exe 16.0.6).
Nuitka-Scons: Backend linking program with 107 files (no progress information available for this stage).
Nuitka-Scons: Compiled 107 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 107
Nuitka-Postprocessing: Adding 1 icon(s) from icon file 'icon.ico'.
Nuitka-Plugins:tk-inter: Included 89 data files due to Tk needed for tkinter usage.
Nuitka-Plugins:tk-inter: Included 834 data files due to Tcl needed for tkinter usage.
Nuitka-Postprocessing: Creating single file from dist folder, this may take a while. 
Nuitka-Onefile: Running bootstrap binary compilation via Scons.
Nuitka-Scons: Onefile C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\clang.exeNuitka-Scons: (clang.exe 16.0.6).
Nuitka-Scons: Onefile linking program with 2 files (no progress information available for this stage).
error: invalid argument '-std=c11' not allowed with 'C++'

scons: *** [static_src\OnefileSplashScreen.o] Error 1
FATAL: Error, onefile bootstrap binary build failed.
```

How can I fix it?

**Comment by kayhayen** [comment]
The splash screen only works with MSVC, due to strange differences in the header files, that nobody has rectified yet. So far we never use Clang with C++ code, but only C code, but I guess, that's an error by itself. When compiling I think it catches MinGW64 with an error pragma.

**Comment by kayhayen** [comment]
Checking it out, I didn't see errors with MinGW64 or Clang, but it seems the splash screen itself might be regressed.

**Comment by kayhayen** [comment]
I was stupid, compiling via SSH where I couldn'T see the splash screen, can of course not work. On the upside, I added really a lot of debug traces.

**Comment by kayhayen** [comment]
This will be part of the hotfix 2.4.8 I am about to make and currently is on factory. The Clang error is gone by making it a C specific option what C standard to use (seems GCC is more generous there). And now splash screen works with all 3 compilers including the one you use, there wasn't really anything to do to achieve that, it just worked. I was having errors with MinGW64 before, but it seems their Windows SDK is now compatible. I am closing this one early for lack of general relevance.

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.
