### ISSUE TITLE
"Scalability issue" - macOS Catalina 10.15.7

### ISSUE THREAD

**Issue by siissioe123** [Nuitka/Nuitka#3085]
``` 
2.2.3
Commercial: None
Python: 3.11.9 (main, Aug 20 2024, 09:55:07) [Clang 12.0.0 (clang-1200.0.32.29)]
Flavor: Homebrew Python
Executable: /usr/local/Cellar/python@3.11/3.11.9_1/bin/python3.11
OS: Darwin
Arch: x86_64
macOSRelease: 10.15.7
Version C compiler: /usr/bin/clang (clang 12.0.0).
``` 
(using "`python -m nuitka --version`")

```
CPU: Intel i7-4770S (8) @ 3.10GHz 
GPU: NVIDIA GeForce GT 750M 
Memory: 6680MiB / 16384MiB
```
(from neofetch)

I have made a simple CPU/GPU temps monitor to keep an eye on my hardware temps (usually pretty toasty). When compiling using "python -m nuitka --standalone --macos-create-app-bundle main.py -o osx-cputemp", the compilation starts, but then it gets stuck at 98.3% at this stage:
```
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.                    
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: clang (clang 12.0.0).
Nuitka-Scons: Slow C compilation detected, used 360s so far, scalability problem.
Backend C: 98.3%|████████████████████████▌| 59/60
```

Where I'm told there's a scalability problem, I saw that there's another issue - closed - on github, #[1397](https://github.com/Nuitka/Nuitka/issues/1397), but the problem is a bit different. Whilst I have the same problem (on the Activity Monitor I can see that clang is using 100% of my CPU). I tried restarting my iMac and tried restarting the compilation - still the same.

Thanks

**Comment by siissioe123** [comment]
It did finish compiling, but it took almost an hour...
Is there a way to speed up compilation?

**Comment by KRRT7** [comment]
if you share a minimal reproducible example / fill out the issue template we can attempt to narrow down why it's taking so long.

**Comment by siissioe123** [comment]
Idk, now it takes a normal amount of time. The only thing I did was installing ccache

**Comment by kayhayen** [comment]
Closing for lack of feedback
