### ISSUE TITLE
Slow executable startup time on MacOS

### ISSUE THREAD

**Issue by Moosems** [Nuitka/Nuitka#3088]
MRE:
```python
from time import time

def main():
    st = time()
    print("Wowzers! It started!")
    et = time() - st
    print("Script time: ", et)

if __name__ == "__main__":
    main()
```

Terminal Output:
```
Moosems $ python3 -m nuitka test.py --standalone; time ./test.dist/test.bin
Nuitka-Options: Used command line options: test.py --standalone
Nuitka: Starting Python compilation with Nuitka '2.4.7' on Python '3.12' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: clang (clang 15.0.0).
Nuitka-Scons: Backend linking program with 6 files (no progress information available for this stage).
Nuitka-Scons: Compiled 6 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 6
Nuitka: Keeping build directory 'test.build'.
Nuitka: Created binary that runs on macOS 13.0 (x86_64) or higher.
Nuitka: Successfully created 'test.dist/test.bin'.
Wowzers! It started!
Script time:  0.00015425682067871094
./test.dist/test.bin  0.04s user 0.03s system 5% cpu 1.143 total
Moosems $ time ./test.dist/test.bin
Wowzers! It started!
Script time:  3.695487976074219e-05
./test.dist/test.bin  0.04s user 0.01s system 95% cpu 0.057 total
Moosems $ time python3 test.py
Wowzers! It started!
Script time:  2.574920654296875e-05
python3 test.py  0.04s user 0.02s system 88% cpu 0.059 total
```

- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  2.4.7

- How did you install Nuitka and Python

  pip and python.org

The larger the project, the longer the initial startup time (first time the binary is run) takes. It might be something to consider looking into but I understand if this isn't a priority. I searched the docs but couldn't find anything on this. If you have any ideas on bringing down this initial time, I'm open to suggestions. Without `--standalone` it was still `0.704 total` the first time and averaged about the same afterwards. Maybe this also is a my end thing and, if so, feel free to close this.

**Comment by kayhayen** [comment]
In your example given, I am failing to identify a difference when I try it. The time output makes no sense. You can use `--experimental=show-startup-time` to look into the details. But since you cannot even provide the output of `--version` even though it clearly asked for that, I feel like you are not good at providing information.

**Comment by Moosems** [comment]
@kayhayen Respectfully, there is no lack of information. The line `Nuitka: Starting Python compilation with Nuitka '2.4.7' on Python '3.12' commercial grade 'not installed'.` in the traceback shows both the Nuitka and Python version, the system is evident by the name, the flavor is a python.org install which was also stated, and it is very clear that it takes 1.5 seconds for the executable to run which is crazy given that the script itself only runs for 2.574920654296875e-05 to 0.00015425682067871094 seconds depending on how many times the executable has been run. Nuitka 2.4.10 still has this though the first run now generally takes about 1.15 seconds. Using `--experimental=show-startup-time` gives the following:
```
2024-10-18 05:05:33.317 main(): Entered.
2024-10-18 05:05:33.317 main(): Prepare standalone environment.
2024-10-18 05:05:33.318 main(): Preparing frozen modules.
2024-10-18 05:05:33.318 copyFrozenModulesTo(): Calling _loadBytesCodesBlob.
2024-10-18 05:05:33.318 loadConstantsBlob(): One time init.
2024-10-18 05:05:33.318 loadConstantsBlob(): Found blob, decoding now.
2024-10-18 05:05:33.318 loadConstantsBlob(): CRC32 that blob for correctness.
2024-10-18 05:05:33.335 loadConstantsBlob(): One time init complete.
2024-10-18 05:05:33.335 copyFrozenModulesTo(): Updating frozen module table sizes.
2024-10-18 05:05:33.336 main(): Calling Nuitka_Py_Initialize to initialize interpreter.
2024-10-18 05:05:33.337 Nuitka_Py_Initialize(): Calling Py_InitializeFromConfig.
2024-10-18 05:05:33.348 main(): Calling createGlobalConstants().
2024-10-18 05:05:33.348 main(): Returned createGlobalConstants().
2024-10-18 05:05:33.348 main(): Calling createMainModuleConstants().
2024-10-18 05:05:33.348 main(): Returned createMainModuleConstants().
2024-10-18 05:05:33.369 main(): Calling __main__.
Wowzers! It started!
Script time:  0.00019788742065429688
2024-10-18 05:05:33.370 main(): Exited from __main__.
2024-10-18 05:05:33.370 main(): Calling Py_Exit.
2024-10-18 05:05:33.374 Nuitka_at_exit(): Called by C exit()
./test.dist/test.bin  0.03s user 0.04s system 5% cpu 1.226 total
```

It seems that, as I showed previously, this is not an issue with the script itself running but something about the executable startup time.

**Comment by kayhayen** [comment]
When people say "respectfully", what follows is usually not respectful, and this seems to be no exception. The only respectful answer would be to provide the missing information. So why should I work on this.
