### ISSUE TITLE
Import User-Provided Modules at Runtime

### ISSUE THREAD

**Issue by achempak-polymer** [Nuitka/Nuitka#3090]
In Nuitka, is it possible to import a module at runtime that was unknown at compile-time? For example, say I have the following code:
```python
from SomeDataStructure import SomeDataStructure
def import_custom_implementation() -> SomeAbstractType:
    if os.getenv("USE_CUSTOM_IMPL"):
        from CustomImpl.CustomDataStructure import CustomDataStructure
        return CustomDataStructure
    else:
        return SomeDataStructure

data_structure = import_queue()
```
Is there any way for Nuitka to know at runtime how to do this import: `from CustomImpl.CustomDataStructure import CustomDataStructure`? For example, without using Nuitka, I can modify `PYTHONPATH` and then run the program as so:
```
PYTHONPATH=$PYTHONPATH:/PATH/TO/CUSTOM/PACKAGE python main.py
```
This is running on my system, where `/PATH/TO/CUSTOM/PACKAGE` contains a custom implementation of some data structure that I've provided. When my users use a compiled Nuitka executable version of my program, and they provide their own implementation of the data structure at their own `/PATH/TO/CUSTOM/PACKAGE`, is there any way for the program to find this module?

I've  looked through the `--help` docs and found information about `--include-package` and `--include-module`, but these are for searching specific directories at compile-time. What I want to know is if there is a way to find a user-defined module at a user-defined path (e.g. they will modify `PYTHONPATH`) at runtime. Thank you 😄 

Also, do let me know if this isn't the right place to ask this question. I know it isn't a bug, but I'm new to the Nuitka community and wasn't sure where to post.

**Comment by kayhayen** [comment]
If you don't use the isolation Python flag and standalone (which is not default anyway), you can expand the `sys.path` in any way you see fit and have it expanded. In isolated mode, not found imports will be turned into hard errors eventually, but right now, there is just no way to find anything there, unless extending the `sys.path` yourself.

You may also use this for real plugin handling: https://nuitka.net/user-documentation/common-issue-solutions.html#manual-python-file-loading
