### ISSUE TITLE
Error loading QtWidgets.pyd

### ISSUE THREAD

**Issue by nilprovai** [Nuitka/Nuitka#3102]
Im use Nuitka 2.4 and PySide6 6.7.2
`NS: nuitka demo.py --standalone --onefile --plugin-enable=pyside6` didn't make any difference, you'll still get:
ImportError: LoadLibraryEx 'C:\Users\nil\AppData\Local\Temp\ONEFIL~1\PySide6\QtWidgets.pyd' failed

**Comment by nilprovai** [comment]
runs on Windows 1511

**Comment by KRRT7** [comment]
fill out the issue template please.

**Comment by nilprovai** [comment]
Python Version: 3.12.5
Nuitka Version: 2.4.8
PySide6 Version: 6.7.2
Build Command:
`nuitka demo.py --standalone --onefile --plugin-enable=pyside6`
Build on:
`Windows 11 23H2 (22631.4037)`
Tested on:
`Windows 10 (1511)`
Got error:
`Traceback (most recent call last):
  File "C:\Users\nil\AppData\Local\Temp\ONEFIL~1\demo.py", line 1, in <module>
ImportError: LoadLibraryExW 'C:\Users\nil\AppData\Local\Temp\ONEFIL~1\PySide6\QtWidgets.pyd' failed`



> fill out the issue template please.

**Comment by kayhayen** [comment]
Qt6 doesn't support old Windows 10. They failed to do the first thing, namely to run their program uncompiled and then get us to tell why their wishes don't work out. I almost feel bad for helping them.
