### ISSUE TITLE
The behavior of included file in onefile and standalone mode is suggested to be the same.

### ISSUE THREAD

**Issue by xueliang** [Nuitka/Nuitka#3103]
python -m nuitka --version
2.4.5
Commercial: None
Python: 3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0]
Flavor: Anaconda Python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 20.04.6
Version C compiler: /usr/bin/gcc (gcc 9).

The test code is very simle, just to read the included text file.

```
import os

for line in open("model/a.txt"):
        print(line)
```

a.txt is a simple text file.

```
cat model/a.txt
123
345
456
```

I tried three types of way to include the data into the binary file,

```
python -m nuitka --show-progress --show-memory --standalone  --onefile  --output-dir=build/Linux-64 --static-libpython=no  ./main.py --include-data-files=model/a.txt=model/a.txt

python -m nuitka --show-progress --show-memory --standalone  --onefile  --output-dir=build/Linux-64 --static-libpython=no  ./main.py --include-data-files=model/*=model/

python -m nuitka --show-progress --show-memory --standalone  --onefile  --output-dir=build/Linux-64 --static-libpython=no  ./main.py --include-data-dir=model=model
```
but when running the binary file, an error says:

```
./main.bin
Traceback (most recent call last):
  File "/tmp/onefile_4182505_1725182515_727119/main.py", line 4, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'model/a.txt'
```

I find if removing the onefile option, the binary file by standalone work.
It seems that the data is extracted to "/tmp/onefile_4182505_1725182515_727119", not the current directory. So the problem could be solved by:

```
# Get the directory where the script is running
script_dir = os.path.dirname(os.path.abspath(__file__))
print(script_dir)
# Construct the path to the file in the extracted directory
file_path = os.path.join(script_dir, 'model/a.txt')

# Now you can open the file with the correct path
with open(file_path) as file:
    for line in file:
        print(line)
```

Finally, the behavior of onefile and standalone is suggested to be the same.

**Comment by kayhayen** [comment]
your code is wrong. Check the user manual for how to find files, and as a hint, the current directory is not it
