### ISSUE TITLE
scons: *** [static_src\CompiledFunctionType.obj] Error 2

### ISSUE THREAD

**Issue by lfillaz** [Nuitka/Nuitka#3104]
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure
Nuitka-Options:WARNING: that is intended.
Nuitka: Starting Python compilation with Nuitka '2.5rc5' on Python '3.12' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: cl (cl 14.3).
Unexpected output from this command:
<clcache> /Fo__constants.obj /c "__constants.c" /nologo /GL /std:c11 /wd5105 -O2 /Z7 /FS /EHsc /J /Gd /bigobj /W4 /wd4505 /wd4127 /wd4100 /wd4702 /wd4189 /wd4211 /wd4115 /WX /wd4512 /wd4510 /wd4610 /wd4200 /wd4996 /MT /D_NUITKA_DEBUG_DEBUG_IMMORTAL /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=0 /D_NUITKA_EXE /D_NUITKA_FILE_REFERENCE_ORIGINAL_MODE /IC:\Users\Al-kc\AppData\Local\Programs\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\inline_copy\zlib /IC:\Users\Al-kc\AppData\Local\Programs\Python\PYTHON~1\include /I. /IC:\Users\Al-kc\AppData\Local\Programs\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\include /IC:\Users\Al-kc\AppData\Local\Programs\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\static_src /IC:\Users\Al-kc\AppData\Local\Programs\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\inline_copy\libbacktrace
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\intrin.h(1008): error C2220: the following warning is treated as an error
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\intrin.h(1008): warning C4391: 'char _sat_add_i8(char,char)': incorrect return type for intrinsic function, expected 'unsigned char'
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\intrin.h(1016): warning C4391: 'char _sat_sub_i8(char,char)': incorrect return type for intrinsic function, expected 'unsigned char'
scons: *** [__constants.obj] Error 2
Unexpected output from this command:
<clcache> /Fo__helpers.obj /c "__helpers.c" /nologo /GL /std:c11 /wd5105 -O2 /Z7 /FS /EHsc /J /Gd /bigobj /W4 /wd4505 /wd4127 /wd4100 /wd4702 /wd4189 /wd4211 /wd4115 /WX /wd4512 /wd4510 /wd4610 /wd4200 /wd4996 /MT /D_NUITKA_DEBUG_DEBUG_IMMORTAL /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=0 /D_NUITKA_EXE /D_NUITKA_FILE_REFERENCE_ORIGINAL_MODE /IC:\Users\Al-kc\AppData\Local\Programs\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\inline_copy\zlib /IC:\Users\Al-kc\AppData\Local\Programs\Python\PYTHON~1\include /I. /IC:\Users\Al-kc\AppData\Local\Programs\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\include /IC:\Users\Al-kc\AppData\Local\Programs\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\static_src /IC:\Users\Al-kc\AppData\Local\Programs\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\inline_copy\libbacktrace
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\intrin.h(1008): error C2220: the following warning is treated as an error
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\intrin.h(1008): warning C4391: 'char _sat_add_i8(char,char)': incorrect return type for intrinsic function, expected 'unsigned char'
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\intrin.h(1016): warning C4391: 'char _sat_sub_i8(char,char)': incorrect return type for intrinsic function, expected 'unsigned char'
scons: *** [__helpers.obj] Error 2
Unexpected output from this command:
<clcache> /Fostatic_src\MainProgram.obj /c "static_src\MainProgram.c" /nologo /GL /std:c11 /wd5105 -O2 /Z7 /FS /EHsc /J /Gd /bigobj /W4 /wd4505 /wd4127 /wd4100 /wd4702 /wd4189 /wd4211 /wd4115 /WX /wd4512 /wd4510 /wd4610 /wd4200 /wd4996 /MT /D_NUITKA_DEBUG_DEBUG_IMMORTAL /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=0 /D_NUITKA_EXE /D_NUITKA_FILE_REFERENCE_ORIGINAL_MODE /IC:\Users\Al-kc\AppData\Local\Programs\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\inline_copy\zlib /IC:\Users\Al-kc\AppData\Local\Programs\Python\PYTHON~1\include /I. /IC:\Users\Al-kc\AppData\Local\Programs\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\include /IC:\Users\Al-kc\AppData\Local\Programs\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\static_src /IC:\Users\Al-kc\AppData\Local\Programs\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\inline_copy\libbacktrace
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\intrin.h(1008): error C2220: the following warning is treated as an error
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\intrin.h(1008): warning C4391: 'char _sat_add_i8(char,char)': incorrect return type for intrinsic function, expected 'unsigned char'
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\intrin.h(1016): warning C4391: 'char _sat_sub_i8(char,char)': incorrect return type for intrinsic function, expected 'unsigned char'
scons: *** [static_src\MainProgram.obj] Error 2
Unexpected output from this command:
<clcache> /Fomodule.__main__.obj /c "module.__main__.c" /nologo /GL /std:c11 /wd5105 -O2 /Z7 /FS /EHsc /J /Gd /bigobj /W4 /wd4505 /wd4127 /wd4100 /wd4702 /wd4189 /wd4211 /wd4115 /WX /wd4512 /wd4510 /wd4610 /wd4200 /wd4996 /MT /D_NUITKA_DEBUG_DEBUG_IMMORTAL /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=0 /D_NUITKA_EXE /D_NUITKA_FILE_REFERENCE_ORIGINAL_MODE /IC:\Users\Al-kc\AppData\Local\Programs\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\inline_copy\zlib /IC:\Users\Al-kc\AppData\Local\Programs\Python\PYTHON~1\include /I. /IC:\Users\Al-kc\AppData\Local\Programs\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\include /IC:\Users\Al-kc\AppData\Local\Programs\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\static_src /IC:\Users\Al-kc\AppData\Local\Programs\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\inline_copy\libbacktrace
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\intrin.h(1008): error C2220: the following warning is treated as an error
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\intrin.h(1008): warning C4391: 'char _sat_add_i8(char,char)': incorrect return type for intrinsic function, expected 'unsigned char'
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\intrin.h(1016): warning C4391: 'char _sat_sub_i8(char,char)': incorrect return type for intrinsic function, expected 'unsigned char'
scons: *** [module.__main__.obj] Error 2
Nuitka-Scons: Backend linking program with 6 files (no progress information available for this stage).
Unexpected output from this command:
<clcache> /Fostatic_src\CompiledFunctionType.obj /c "static_src\CompiledFunctionType.c" /nologo /GL /std:c11 /wd5105 -O2 /Z7 /FS /EHsc /J /Gd /bigobj /W4 /wd4505 /wd4127 /wd4100 /wd4702 /wd4189 /wd4211 /wd4115 /WX /wd4512 /wd4510 /wd4610 /wd4200 /wd4996 /MT /D_NUITKA_DEBUG_DEBUG_IMMORTAL /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=0 /D_NUITKA_EXE /D_NUITKA_FILE_REFERENCE_ORIGINAL_MODE /IC:\Users\Al-kc\AppData\Local\Programs\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\inline_copy\zlib /IC:\Users\Al-kc\AppData\Local\Programs\Python\PYTHON~1\include /I. /IC:\Users\Al-kc\AppData\Local\Programs\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\include /IC:\Users\Al-kc\AppData\Local\Programs\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\static_src /IC:\Users\Al-kc\AppData\Local\Programs\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\inline_copy\libbacktrace
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\intrin.h(1008): error C2220: the following warning is treated as an error
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\intrin.h(1008): warning C4391: 'char _sat_add_i8(char,char)': incorrect return type for intrinsic function, expected 'unsigned char'
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\intrin.h(1016): warning C4391: 'char _sat_sub_i8(char,char)': incorrect return type for intrinsic function, expected 'unsigned char'
C:\Users\Al-kc\AppData\Local\Programs\Python\Python312\Lib\site-packages\nuitka\build\static_src\MetaPathBasedLoaderResourceReaderFiles.c(643): warning C4457: declaration of 'op' hides function parameter
C:\Users\Al-kc\AppData\Local\Programs\Python\Python312\Lib\site-packages\nuitka\build\static_src\MetaPathBasedLoaderResourceReaderFiles.c(637): note: see declaration of 'op'
C:\Users\Al-kc\AppData\Local\Programs\Python\Python312\Lib\site-packages\nuitka\build\static_src\MetaPathBasedLoaderResourceReaderFiles.c(649): warning C4457: declaration of 'op' hides function parameter
C:\Users\Al-kc\AppData\Local\Programs\Python\Python312\Lib\site-packages\nuitka\build\static_src\MetaPathBasedLoaderResourceReaderFiles.c(637): note: see declaration of 'op'
scons: *** [static_src\CompiledFunctionType.obj] Error 2
FATAL: Failed unexpectedly in Scons C backend compilation.
Nuitka:WARNING:     Complex topic! More information can be found at
Nuitka:WARNING: https://nuitka.net/info/scons-backend-failure.html
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'.

**Comment by kayhayen** [comment]
In the template, we have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that we do not want to be left guessing. For you it's easy to erase the issue template and expect us to ask you questions only as necessary, but we cannot do that. We would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore we are  likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
