### ISSUE TITLE
MetaPathBasedLoader.c handle leak

### ISSUE THREAD

**Issue by Aruise** [Nuitka/Nuitka#3117]
Static analyzer caught a memory leak

Handle 'handle' opened here: 
https://github.com/Nuitka/Nuitka/blob/551166924fe58dfcdbce3a64dd53e474af876b1a/nuitka/build/static_src/MetaPathBasedLoader.c#L806

Handle leaked here, causing memory leak:
https://github.com/Nuitka/Nuitka/blob/551166924fe58dfcdbce3a64dd53e474af876b1a/nuitka/build/static_src/MetaPathBasedLoader.c#L864

Perhaps adding either 'dlclose(handle);' or exception before 'return NULL;' will fix the memory leak?

**Comment by kayhayen** [comment]
This report makes no sense, these are to remain loaded until program end.
