### ISSUE TITLE
FATAL: anti-bloat: Error, failed to evaluate expression

### ISSUE THREAD

**Issue by ashutoshmishra1014** [Nuitka/Nuitka#3118]
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version
```
2.4.8
Commercial: None
Python: 3.8.19 (default, Mar 20 2024, 19:58:24) 
Flavor: Anaconda Python
Executable: /home/woody/iwal/iwal037h/conda/nuitka/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 20.04.6
Version C compiler: /usr/bin/gcc (gcc 9).
```

- How did you install Nuitka and Python
`pip install nuitka`

My application is based on the below project:
https://github.com/nerfstudio-project/nerfstudio

- Also supply a Short, Self Contained, Correct, Example

`python -m nuitka --follow-imports --include-module=tinycudann_bindings --onefile --standalone --report=compilation-report.xml nerfstudio/scripts/train.py`

- Error
```
FATAL: anti-bloat: Error, failed to evaluate expression '"""_static_compile_ignored_keys = %s\n\ndef get_assignments_with_compile_ignored_comments(module):\n  return _static_compile_ignored_keys[module.__name__]\n""" % repr(get_variable("torch_config_modules"))\n' in this context, exception was 'malformed node or string: <_ast.Call object at 0x7f410139bbb0>'.
Nuitka-Reports: Compilation report written to file 'compilation-report.xml'.
```

Compilation Report:
[compilation-report.txt](https://github.com/user-attachments/files/16977175/compilation-report.txt)

**Comment by ashutoshmishra1014** [comment]
@kayhayen any suggestions?

**Comment by gdementen** [comment]
If you can confirm that that file runs fine under CPython, it seems like a bug in Nuitka or its anti-bloat config. With the information you give, I believe it is possible to reproduce and thus fix the problem but... it would still be much easier (and thus quicker) to fix if you could narrow down that script to a (preferably much) smaller script. I **suppose* this is a problem with the pytorch integration code in Nuitka, so if you could create a torch-only script which reproduces the problem that would be great.

**Comment by ashutoshmishra1014** [comment]
I setup a new environment with nuitka and issues seems to be resolved.

**Comment by thanks9807** [comment]
hi, @ashutoshmishra1014 .
I'm having the same problem as you. Can you tell me how you solved it?
