### ISSUE TITLE
Faild to Compile with PymuPDF - fatal error C1002: compiler is out of heap space in pass 2

### ISSUE THREAD

**Issue by chianjin** [Nuitka/Nuitka#3123]
Nuitka: 2.4.8
Commercial: None
Python: 3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)]
Flavor: CPython Official
Executable: E:\Project\PDFeXpress\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64\cl.exe (cl 14.3).

 Nuitka      2.4.8
 ordered-set 4.1.0
 pillow      10.4.0
 pip         23.2.1
 psutil      6.0.0
 PyMuPDF     1.24.10
 PyMuPDFb    1.24.10
 tkinterdnd2 0.4.2
 zstandard   0.23.0

I use PymuPDF in my project and use Nuitka to compile the application.
It worked well before in several minutes.

When I changed to Python 3.12 and installed the last version of all packages.
Nuitka took too long time to optimize pymupdf and faild to compile the application.

`fatal error C1002: compiler is out of heap space in pass 2`
[nuitka-crash-report.xml.txt](https://github.com/user-attachments/files/17057733/nuitka-crash-report.xml.txt)

**Comment by KERERCVASD** [comment]
maybe this will help
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic

you may need to install the c compiler

**Comment by HydraDragonAntivirus** [comment]
Similar issue happened in 2.5rc5 here is the error `Unexpected output from this command:
<clcache> /Fomodule.sympy.polys.polyquinticconst.obj /c "module.sympy.polys.polyquinticconst.c" /std:c11 /nologo /wd5105 /wd4391 /Ox /GF /Gy /EHsc /J /Gd /bigobj /MT /D__NUITKA_NO_ASSERT__ /D_NUITKA_STANDALONE /D_NUITKA_ONEFILE_MODE /D_NUITKA_ONEFILE_TEMP_BOOL /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=155 /D_NUITKA_EXE /D_NUITKA_PLUGIN_MULTIPROCESSING_ENABLED=1 /IC:\Users\victim\AppData\Local\Programs\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\inline_copy\zlib /IC:\Users\victim\AppData\Local\Programs\Python\PYTHON~1\include /I. /IC:\Users\victim\AppData\Local\Programs\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\include /IC:\Users\victim\AppData\Local\Programs\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\static_src /IC:\Users\victim\AppData\Local\Programs\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\inline_copy\libbacktrace
C:\Users\victim\Documents\oldstuff\antivirus.build\module.sympy.polys.polyquinticconst.c(9520) : fatal error C1002: compiler is out of heap space in pass 2`

**Comment by HydraDragonAntivirus** [comment]
Do this SET CFLAGS=/Zm200 then use your Nuitka command.

**Comment by HydraDragonAntivirus** [comment]
If still didn't work upgrade 200 to 300

**Comment by HydraDragonAntivirus** [comment]
Even if upgrading to 400 doesn't work for me.

**Comment by kayhayen** [comment]
I don't think `/Zm` has any meaningful influence. 

https://nuitka.net/user-documentation/common-issue-solutions.html#memory-issues-and-compiler-bugs
