### ISSUE TITLE
nuitka --standalone exit immediately (Do nothing) if import pendulum

### ISSUE THREAD

**Issue by gaoming714** [Nuitka/Nuitka#3124]
import pendulum 

if I use --standalone, the exe file will not work, (exit immediately)

I read from this issue https://github.com/Nuitka/Nuitka/issues/568
but I don't know how to fix.

**Comment by kayhayen** [comment]
In the template, we have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that we do not want to be left guessing. For you it's easy to erase the issue template and expect us to ask you questions only as necessary, but we cannot do that. We would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore we are  likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
