### ISSUE TITLE
Python flag no_annotations breaks NamedTuple

### ISSUE THREAD

**Issue by jbjd** [Nuitka/Nuitka#3125]
This was reproduced on Windows, details below

Nuitka Version:
```
PS C:\Python\Viewer> python -m nuitka --version
2.4.8
Commercial: None
Python: 3.12.6 (tags/v3.12.6:a4a2d2b, Sep  6 2024, 20:11:23) [MSC v.1940 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\jimde\AppData\Local\Programs\Python\Python312\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64\cl.exe (cl 14.3).
```
Nuitka installed with pip, not virtualenv. Python was installed from Windows installer (64-bit) from python.org

Broken code (example.py):
```
from typing import NamedTuple

class SomeNamedTuple(NamedTuple):
    foo: int
    bar: tuple

named_tuple = SomeNamedTuple(1, ("asfd", 12))

print(named_tuple)
```
Build command: ```python -m nuitka .\example.py --python-flag=no_annotations```
Output: ```TypeError: SomeNamedTuple.__new__() takes 1 positional argument but 3 were given```

Build command: ```python -m nuitka .\example.py```
Output of example.exe: ```SomeNamedTuple(foo=1, bar=('asfd', 12))```

So ```--python-flag=no_annotations``` breaks NamedTuple, but not namedtuple from collections instead of typing

Working code (example.py):
```
from collections import namedtuple

class SomeNamedTuple(namedtuple("SomeNamedTuple", ["foo", "bar"])):
    foo: int
    bar: tuple

named_tuple = SomeNamedTuple(1, ("asfd", 12))

print(named_tuple)
```
Build command" ```python -m nuitka .\example.py --python-flag=no_annotations```
Output of example.exe: ```SomeNamedTuple(foo=1, bar=('asfd', 12))```

I also tried this with ```--mingw64``` and got the same results.

**Comment by kayhayen** [comment]
I am surprised you don't see how removing annotations is supposed to be allowed if code uses them 

We added per module and package configuration to replace the global flag.

Your example works exactly as expected.

**Comment by jbjd** [comment]
That's fair, I just figured it would be nice to have NamedTuple still work with no_annotations. I thought there could be a check during compile to make it work, but I understand leaving it as is.

Thank you
