### ISSUE TITLE
Compile failed after updating to macOS 15 Sequoia

### ISSUE THREAD

**Issue by zhiyiYo** [Nuitka/Nuitka#3127]
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version
2.4.8
Commercial: None
Python: 3.11.7 (main, Dec 15 2023, 12:09:56) [Clang 14.0.6 ]
Flavor: Anaconda Python
Executable: /Users/shokokawaii/miniconda3/envs/fluentclient/bin/python3
OS: Darwin
Arch: arm64
macOSRelease: 15.0
Version C compiler: /usr/bin/clang (clang 15.0.0).

- How did you install Nuitka and Python

   > Download from miniconda and `pip install nuitka`

- The specific PyPI names and versions

   > No packages.

- Also supply a Short, Self Contained, Correct, Example

 Hi, I upgraded macOS to 15 this afternoon, but when I packaged the simplest demo which only contains one line code `print ("Hello world")`, it got an error message:
```sh
Nuitka-Scons: Backend C compiler: clang (clang 15.0.0).
Nuitka-Scons: Backend linking program with 6 files (no progress information available for this stage).
Nuitka-Scons: Compiled 6 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 6
FATAL: Error, call to 'otool' gave warnings: ['/usr/bin/otool', '-arch', 'arm64', '-L', '/Users/shokokawaii/dist/FluentClient/FluentClient.app/Contents/MacOS/test'] -> b"dyld[1708]: symbol '__ZTINSt3__13pmr15memory_resourceE' missing from root that overrides /usr/lib/libc++.1.dylib. Use of that symbol in /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk is being set to 0xBAD4007.\ndyld[1709]: symbol '__ZTINSt3__13pmr15memory_resourceE' missing from root that overrides /usr/lib/libc++.1.dylib. Use of that symbol in /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk is being set to 0xBAD4007.\n".
```
Building command as blow:
```
nuitka --standalone --show-memory --show-progress  --macos-create-app-bundle
--macos-disable-console --macos-app-version=0.7.3 --macos-app-name=FluentClient --output-dir=dist/FluentClient test.py
```

**Comment by zhiyiYo** [comment]
I try to call the otool in shell, but get no error:
```
/usr/bin/otool -arch arm64 -L /Users/shokokawaii/Documents/Python_Study/Fluent-Client/dist/FluentClient/test.app/Contents/MacOS/test
/Users/shokokawaii/Documents/Python_Study/Fluent-Client/dist/FluentClient/test.app/Contents/MacOS/test:
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1351.0.0)
```

**Comment by zhiyiYo** [comment]
For the previously packaged project, I found a temporary solution. Currently, Clang can compile the executable file normally, but there is an issue with the post-processing steps. We can use otool to correct the dynamic library paths referenced by the executable file：
```sh
install_name_tool -change @rpath/libpython3.11.dylib @executable_path/libpython3.11.dylib your_binary_file
```

**Comment by kayhayen** [comment]
This might be Anaconda specific, I am not seeing it with CPython compilation at all.

**Comment by kayhayen** [comment]
This lacks a reproducer and is not a general issue, closing it therefore.

**Comment by kayhayen** [comment]
If anybody ever sees this, please make a more competent report including a reproducer.
