### ISSUE TITLE
Can Nuitka executables file be extracted into shared libraries?

### ISSUE THREAD

**Issue by kietheros** [Nuitka/Nuitka#3135]
Previously, I used Cython to compile my project, where each Python file (module) was compiled into a shared library (.so file). I have just tried using Nuitka, and it works well. Is it possible to extract the executable into shared libraries instead?

My concern is that if each Python file is compiled into a .so file, someone could potentially read the file names to understand the roles of these files and focus on them to find vulnerabilities.

**Comment by kayhayen** [comment]
Just use the standalone mode to compile all files at once into a single binary with only previously existing extension modules being used.

**Comment by kayhayen** [comment]
https://nuitka.net/user-documentation/use-cases.html

**Comment by kietheros** [comment]
@kayhayen I'm using standalone mode, and I see a folder named 'dist' that contains one binary file. I wonder if this binary file is like a self-extracting archive that contains the main app and the shared library files compiled from each Python module then it can be easily extracted easily to see the structure of the project, all module name?

**Comment by kayhayen** [comment]
It is not
