### ISSUE TITLE
Error running standalone onefile executable

### ISSUE THREAD

**Issue by 01baftb** [Nuitka/Nuitka#3137]
I use the following command to build my executable. 

`python -m nuitka --standalone --output-dir=build --enable-plugin=pyside6 --include-data-files=my_README.html=my_README.html --windows-icon-from-ico=res/myicon.ico --onefile .\MyApp.py `

The building works fine. However, when I launch the onefile .exe version of the application, I get a popup dialog with error below.  Then the application's exe file disappears. 

> Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item. 

When I run the non-onefile .exe version of the application, found in the `MyApp.dist\` folder, I do not have any issues. 

System info: 
Windows 11 x64
Python 3.11.9
Nuitka 2.4.8

**Comment by kayhayen** [comment]
In the template, we have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that we do not want to be left guessing. For you it's easy to erase the issue template and expect us to ask you questions only as necessary, but we cannot do that. We would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore we are  likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
