### ISSUE TITLE
Child from subprocess.Popen raises KeyboardInterrupt if indicating --onefile --windows-console-mode=disable

### ISSUE THREAD

**Issue by fjnnng** [Nuitka/Nuitka#3138]
- Outputs from the commands:

```shell
PS C:\Users\untitled\Documents\test> .\venv\Scripts\python.exe -m nuitka --version
2.4.8
Commercial: None
Python: 3.12.6 (tags/v3.12.6:a4a2d2b, Sep  6 2024, 20:11:23) [MSC v.1940 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\untitled\Documents\test\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0).
```

```shell
PS C:\Users\untitled\Documents\test> .\venv\Scripts\python.exe -m pip list -v
Package     Version Location                                                Installer
----------- ------- ------------------------------------------------------- ---------
Nuitka      2.4.8   C:\Users\untitled\Documents\test\venv\Lib\site-packages pip
ordered-set 4.1.0   C:\Users\untitled\Documents\test\venv\Lib\site-packages pip
pip         24.2    C:\Users\untitled\Documents\test\venv\Lib\site-packages pip
zstandard   0.23.0  C:\Users\untitled\Documents\test\venv\Lib\site-packages pip
```

- Nuitka was installed via:
```shell
PS C:\Users\untitled\Documents\test> python -m venv venv
PS C:\Users\untitled\Documents\test> .\venv\Scripts\python.exe -m pip install nuitka
```

- Python was installed via:
Windows installer (64-bit) from https://www.python.org/downloads/windows/

- How to reproduce the issue:

Compile the following code with

```shell
PS C:\Users\untitled\Documents\test> .\venv\Scripts\python.exe -m nuitka --mingw64 --onefile --windows-console-mode=disable test.py
```

```python
import os.path, subprocess, sys, time

if sys.argv[1:]:
    with open("test.log", "w") as f:
        sys.stdout = f
        sys.stderr = f
        count = 1
        while True:
            print(count)
            time.sleep(1)
            count += 1
else:
    subprocess.Popen([os.path.basename(sys.argv[0]), ""])
```

If run with no argument, the executable will execute itself with an argument in another process and exit, and the child with an argument will count every second. But it will not survive too long because of a KeyboardInterrupt. To see this, double-click `test.exe`, and `test.log` will be as the following:

```
INFO:root:1
INFO:root:2
INFO:root:3
INFO:root:4
INFO:root:5
INFO:root:6
INFO:root:7
INFO:root:8
INFO:root:9
INFO:root:10
INFO:root:11
INFO:root:12
INFO:root:13
INFO:root:14
INFO:root:15
INFO:root:16
INFO:root:17
INFO:root:18
INFO:root:19
INFO:root:20
INFO:root:21
INFO:root:22
INFO:root:23
INFO:root:24
INFO:root:25
INFO:root:26
ERROR:root:Traceback (most recent call last):
ERROR:root:  File "C:\Users\untitled\AppData\Local\Temp\ONB0CA~1\test.py", line 40, in <module>
ERROR:root:    while sys.argv[1:] and True:
ERROR:root:KeyboardInterrupt
```

To minimize the code, I let the executable execute itself, but it is not necessary, that is, the first argument in `subprocess.Popen()` is irrelevant. This issue goes away if either removing `--windows-console-mode=disable` or replacing `--onefile` with `--standalone`.

I am not experienced in submitting issues, so if there is anything inappropriate, please let me know. Thank you.

**Comment by kayhayen** [comment]
Your use of `os.basename` and expecting that to run something depends on a couple of things to be true, that would be better done with the actual path used. It appears though, as if it forks for you there, so it's not your issue, but showing a misunderstanding of the respective documentation of Nuitka there. Re-forking the onefile is useless, you ought to prefer `__main__` and I am not sure how good recursive onefile supervision goes. But I think you are having a race here, where the first onefile program exits and as a result a kill is sent to the process group of it, so it's behaving as expected. Spawning only the unpacked executable won't change that.

Read the help output for `--onefile-child-grace-time=GRACE_TIME_MS` to see why it continues to run for some time and how to disabling that killing.

**Comment by kayhayen** [comment]
I don't have a reason to believe the behaviour should depend on disabling the console btw, if it did, that's probably some other bug and maybe a real one of Nuitka, where it fails to launch the onefile without a console, or where the process group is a new one somehow where it should not be.
