### ISSUE TITLE
TypeError: exceptions.AttributeError does not take keyword arguments

### ISSUE THREAD

**Issue by grgi** [Nuitka/Nuitka#3144]
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version
```
2.4.8
Commercial: 2.6.2
Python: 3.11.2 (main, Aug 26 2024, 07:20:54) [GCC 12.2.0]
Flavor: Debian Python
Executable: /tmp/foo/bin/python
OS: Linux
Arch: x86_64
Distribution: Debian 12
Version C compiler: /usr/bin/gcc (gcc 12).
```

- How did you install Nuitka and Python

Python from Debian 12 and Nuitka from Github's `Nuitka-commercial`

- The specific PyPI names and versions

  > python -m pip list -v
```
Package     Version Location                              Installer
----------- ------- ------------------------------------- ---------
Nuitka      2.4.8   /tmp/foo/lib/python3.11/site-packages pip
ordered-set 4.1.0   /tmp/foo/lib/python3.11/site-packages pip
pip         23.0.1  /tmp/foo/lib/python3.11/site-packages pip
setuptools  66.1.1  /tmp/foo/lib/python3.11/site-packages pip
zstandard   0.23.0  /tmp/foo/lib/python3.11/site-packages pip
```

- Also supply a Short, Self Contained, Correct, Example

`foo.py`:
```
AttributeError("foo", name="bar")
```

`python foo.py` does not print anything and terminates normally. However, compiled with Nuitka, I get the following error:
```
Traceback (most recent call last):
  File "/tmp/foo/foo.py", line 1, in <module>
    AttributeError("foo", name="bar")

TypeError: exceptions.AttributeError does not take keyword arguments
```

Note, this is relevant because `numpy` has several instances of `AttributeError` with keyword arguments.

**Comment by kayhayen** [comment]
Interesting, never saw that happen so far.

**Comment by kayhayen** [comment]
So, this is 3.10 or higher, I don't find it in `help(AttributeError)` so it's not documented, which of course is not relevant for being compatible, but explains probably why it's not used a lot.

**Comment by grgi** [comment]
In fact, `NameError` also allows a `name` keyword.

**Comment by kayhayen** [comment]
I managed to add it for my internal CI.

As for docs,

this is from  the help, I would expect it there:

```
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
```

But maybe I am just not good at reading docs and that's correct? It does not accept all keywords though...

**Comment by kayhayen** [comment]
I also noticed `NameError` looking at the source code for what to do there. I would hope it's a lot less relevant though, but that's not the criterion to aim for I guess.

**Comment by grgi** [comment]
This is odd indeed. I found that it seems to accept the keywords listed in the ”Data descriptors” section of `help(AttributeError)` (and correspondingly for `NameError`):
```
 |  Data descriptors defined here:
 |
 |  name
 |      attribute name
 |
 |  obj
 |      object
 ```

**Comment by kayhayen** [comment]
It's probably not meant to be user facing, that is why the docs do not reflect it, you are supposed to catch those things, not create them. That said, nothing stops anybody from doing it. 

I have the fix for `AttributeError` on Python3.10+ done.

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by grgi** [comment]
Many thanks! With Nuitka from the factory branch, it is working.

**Comment by kayhayen** [comment]
Part of the current pre-release and will be in 2.5 once released.

**Comment by kayhayen** [comment]
Part of the 2.5 release I just made.
