### ISSUE TITLE
build error on linux with 3.13 nogil and nuitka@factory

### ISSUE THREAD

**Issue by jimkring** [Nuitka/Nuitka#3146]
build error on linux with 3.13 nogil and nuitka@factory. Here's the CI run: https://github.com/jimkring/nuitka-nogil-testing/actions/runs/11314874383/job/31465356392

This is just a periodic test to see how things are progressing with nuikta support for 3.13 and nogil. I hope this report is helpful to your ongoing work.  I'm not actively using 3.13 yet.

Related to:
- #2834

```
Nuitka-Scons: Backend C compiler: gcc (gcc 13).
In file included from /home/runner/venv-3.13/lib/python3.13t/site-packages/nuitka/build/static_src/CompiledCodeHelpers.c:2072,
                 from static_src/CompiledFunctionType.c:3217:
/home/runner/venv-3.13/lib/python3.13t/site-packages/nuitka/build/static_src/HelpersAttributes.c: In function 'SET_ATTRIBUTE_GENERIC':
/home/runner/venv-3.13/lib/python3.13t/site-packages/nuitka/build/static_src/HelpersAttributes.c:961:51: warning: passing argument 2 of '_PyObjectDict_SetItem' from incompatible pointer type [-Wincompatible-pointer-types]
  961 |             int res = _PyObjectDict_SetItem(type, dict_pointer, attr_name, value);
      |                                                   ^~~~~~~~~~~~
      |                                                   |
      |                                                   PyObject ** {aka struct _object **}
/home/runner/venv-3.13/lib/python3.13t/site-packages/nuitka/build/static_src/HelpersAttributes.c:961:65: warning: passing argument 3 of '_PyObjectDict_SetItem' from incompatible pointer type [-Wincompatible-pointer-types]
  961 |             int res = _PyObjectDict_SetItem(type, dict_pointer, attr_name, value);
      |                                                                 ^~~~~~~~~
      |                                                                 |
      |                                                                 PyObject * {aka struct _object *}
/home/runner/venv-3.13/lib/python3.13t/site-packages/nuitka/build/static_src/HelpersAttributes.c:961:23: error: too few arguments to function '_PyObjectDict_SetItem'
  961 |             int res = _PyObjectDict_SetItem(type, dict_pointer, attr_name, value);
      |                       ^~~~~~~~~~~~~~~~~~~~~
Nuitka-Scons: Backend linking program with 7 files (no progress information available for this stage).
scons: *** [static_src/CompiledFunctionType.o] Error 1
FATAL: Failed unexpectedly in Scons C backend compilation.
Nuitka:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/scons-backend-failure.html
Nuitka-Reports: Compilation report written to file 'report.xml'.
```

**Comment by jimkring** [comment]
Here is the nuitka build report: [nuitka-report-ubuntu-latest.zip](https://github.com/user-attachments/files/17355820/nuitka-report-ubuntu-latest.zip)

**Comment by kayhayen** [comment]
I have seen this one too, it's I think because we trust an API there, that is not exported on non-Linux, but can be used there, but has changed. They added a parameter and I need to checkout, why. I think it has to do with dictionary monitoring.

**Comment by jimkring** [comment]
Hi @kayhayen -- I hope all is well :)

Some updates:

### Nogil builds are working on Nuikta@factory

I just ran [my test project](https://github.com/jimkring/nuitka-nogil-testing/) builds and noticed that we are now successfully building without errors on both linux and windows using 3.13t (nogil) and nuitka@factory.  That's great to see and it appears that in the built execuables, they are correctly reporting gil enabled/disabled status. My test program checks the following and prints it to the console:

```
sys._is_gil_enabled(): False
sysconfig.get_config_var("Py_GIL_DISABLED"): 1
```

That looks just as I would expect, which is great.

### Executables never return after being called

I did notice, however, that on both windows and ubuntu, the executable never returns after it's called from the command line -- instead, the console just hangs indefinitely after the print statements.  You can see this behavior (the timeouts that occurred) in the following github actions run:

https://github.com/jimkring/nuitka-nogil-testing/actions/runs/11693334824

```
Run .\main.dist\main.exe
  .\main.dist\main.exe
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    pythonLocation: C:\hostedtoolcache\windows\Python\3.13.0\x64-freethreaded
    PKG_CONFIG_PATH: C:\hostedtoolcache\windows\Python\3.13.0\x64-freethreaded/lib/pkgconfig
    Python_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.13.0\x64-freethreaded
    Python2_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.13.0\x64-freethreaded
    Python3_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.13.0\x64-freethreaded
sys._is_gil_enabled(): False
sysconfig.get_config_var("Py_GIL_DISABLED"): 1
Error: The action 'Run Built App (Windows)' has timed out after 1 minutes.
```

The code from this exe is pretty trivial and does not even have a main loop:

[main.py](https://github.com/jimkring/nuitka-nogil-testing/blob/main/main.py)
```python
import sys
import sysconfig

gill_enabled = sys._is_gil_enabled()
Py_GIL_DISABLED = sysconfig.get_config_var("Py_GIL_DISABLED")

print(f"sys._is_gil_enabled(): {gill_enabled}")
print(f"sysconfig.get_config_var(\"Py_GIL_DISABLED\"): {Py_GIL_DISABLED}")
```

**Comment by kayhayen** [comment]
I am pretty sure that no-GIL is not close to being usable yet. A bunch of Nuitka code has not been changed to order things correctly, although with these single threaded codes, that cannot be the issue really. I will give it a quick shot, seeing where it hangs.

**Comment by kayhayen** [comment]
I am getting random errors on importing `__future__` in accelerated mode, half of the time, it gives me this:

```
TypeError: NULL object in marshal data for code object
IMPORT_HARD___FUTURE__ : "Unexpected failure of hard import of '__future__'"
```

This is despite the loader doing this:

```
import __future__ # considering responsibility (find_spec)
import __future__ # denied responsibility
# /opt/self-built-pythons/lib/python3.13t/__pycache__/__future__.cpython-313.pyc matches /opt/self-built-pythons/lib/python3.13t/__future__.py
```

I don't get how this can happen, maybe some modules are being loaded concurrently, but that error would have to come from the inside of the standard Python bytecode import mechanism, but it's clearly a race, the other time at program exit, it is crashing in the allocator. We might use that one incompatible there, or maybe mismanage some secret import lock somewhere, I am currently lost on where the race is happening between what.

**Comment by kayhayen** [comment]
This is part of the 2.5 release, lets no track all of No-GIL in one issue, make new ones as you find stuff

**Comment by jimkring** [comment]
@kayhayen fantastic news — good find!

Yes, I’ll open new issues as the come up. 👍
