### ISSUE TITLE
poetry fail to install nuitka

### ISSUE THREAD

**Issue by wudicom520** [Nuitka/Nuitka#3154]
`python3.8        poetry1.8.4`

Using version ^2.4.10 for nuitka

Updating dependencies
Resolving dependencies... (34.1s)

Package operations: 1 install, 0 updates, 0 removals

  - Installing nuitka (2.4.10): Failed

  ChefInstallError

  Failed to install wheel, setuptools>=42.

  Output:
  Updating dependencies
  Resolving dependencies...

  Package operations: 2 installs, 0 updates, 0 removals

    - Installing setuptools (75.1.0)
    - Installing wheel (0.44.0)

    RuntimeError

    Hash for wheel (0.44.0) from archive wheel-0.44.0-py3-none-any.whl not found in known hashes (was: sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855)

    at ~/.local/lib/python3.8/site-packages/poetry/installation/executor.py:812 in _validate_archive_hash
        808│
        809│         archive_hash = f"{hash_type}:{get_file_hash(archive, hash_type)}"
        810│
        811│         if archive_hash not in known_hashes:
      → 812│             raise RuntimeError(
        813│                 f"Hash for {package} from archive {archive.name} not found in"
        814│                 f" known hashes (was: {archive_hash})"
        815│             )
        816│

  Cannot install wheel.

    RuntimeError

    Hash for setuptools (75.1.0) from archive setuptools-75.1.0-py3-none-any.whl not found in known hashes (was: sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855)

    at ~/.local/lib/python3.8/site-packages/poetry/installation/executor.py:812 in _validate_archive_hash
        808│
        809│         archive_hash = f"{hash_type}:{get_file_hash(archive, hash_type)}"
        810│
        811│         if archive_hash not in known_hashes:
      → 812│             raise RuntimeError(
        813│                 f"Hash for {package} from archive {archive.name} not found in"
        814│                 f" known hashes (was: {archive_hash})"
        815│             )
        816│

  Cannot install setuptools.

  Error:

  at ~/.local/lib/python3.8/site-packages/poetry/installation/chef.py:102 in install
       98│             InstalledRepository.load(self._env),
       99│         )
      100│         installer.update(True)
      101│         if installer.run() != 0:
    → 102│             raise ChefInstallError(requirements, io.fetch_output(), io.fetch_error())
      103│
      104│
      105│ class Chef:
      106│     def __init__(

Cannot install build-system.requires for nuitka.

Regardless of which version of Nuitka I install, do I need the latest versions of Setup Tools and Wheel? Is this reasonable

**Comment by kayhayen** [comment]
The setuptools>=42 is really ancient and the first one to support the build system. You have a poetry and or setuptools issue here, this doesn't even touch Nuitka.
