### ISSUE TITLE
Cannot create exe with numba

### ISSUE THREAD

**Issue by iliodium** [Nuitka/Nuitka#3155]
OS: Windows
Arch: x86_64
WindowsRelease: 10
Python: 3.12.6 (tags/v3.12.6:a4a2d2b, Sep  6 2024, 20:11:23) [MSC v.1940 64 bit (AMD64)]
nuitka 2.4.10
numba 0.60.0

I want to build an exe file that uses numba using nuitka

python -m nuitka main.py --jobs=8

first, uncomment the line
 `cc.compile()` 
and comment 
```
import my_module
m = my_module.multi(10, 20)
print(m)
```
launch main.py then undo the changes and run the build

```
import os
from numba.pycc import CC

cc = CC('my_module')
cc.output_dir = os.path.dirname(os.path.realpath(__file__))
cc.output_file = 'my_module.pyd'


@cc.export('multi', 'i4(i4, i4)')
def mult(a, b):
    return a * b


if __name__ == "__main__":
    # cc.compile()
    import my_module

    m = my_module.multi(10, 20)
    print(m)
```

I'm getting an error

`Traceback (most recent call last):
  File "D:\WindSpectrum\WindSpectrum\venv312\Lib\site-packages\numba\pycc\__init__.py", line 7, in <module>
    import setuptools
  File "D:\WindSpectrum\WindSpectrum\venv312\Lib\site-packages\setuptools\__init__.py", line 22, in <module>
    import _distutils_hack.override  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'distutils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WindSpectrum\WindSpectrum\tests\numba\main.py", line 1, in <module>
    from numba.pycc import CC

  File "D:\WindSpectrum\WindSpectrum\venv312\Lib\site-packages\numba\pycc\__init__.py", line 10, in <module>
    raise ImportError(msg)
ImportError: The 'setuptools' package is required at runtime for pycc support.
`

**ModuleNotFoundError: No module named 'distutils'**

Python 3.12 does not come with a stdlib distutils module ([changelog](https://docs.python.org/3/whatsnew/3.12.html)), because distutils was deprecated in 3.10 and removed in 3.12. See [PEP 632 – Deprecate distutils module](https://peps.python.org/pep-0632/).

https://stackoverflow.com/questions/77233855/why-did-i-get-an-error-modulenotfounderror-no-module-named-distutils

what should I do to build the exe ?

**Comment by iliodium** [comment]
should we expect support in 2.5 ?  am a student and I use this wonderful technology to write my graduation paper. graduation in 8 months, can I hope for the support of setuptools?)

**Comment by kayhayen** [comment]
If you help, you can make sure to have your expectations met, otherwise please leave me along with asking for release dates unless you are an actual supporter.
