### ISSUE TITLE
Reproducible output hash

### ISSUE THREAD

**Issue by acitd** [Nuitka/Nuitka#3157]
Every time I create a standalone binary (.exe) with the same source code, it has different hash (sha256).
I want to have every time the same.
I've search for an option but I didn't find something to achieve this.

**Comment by kayhayen** [comment]
You need to use a reproducible tool chain to achieve that. Nuitka itself is not doing anything against it for all I know, in fact I think I did have reproducible binaries at some point, but for lack of input, I am closing this as invalid.

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
