### ISSUE TITLE
Kivy: Missing modules for clipboard support under Linux

### ISSUE THREAD

**Issue by rweiss123** [Nuitka/Nuitka#3158]
- Please check out if the develop version of Nuitka works better for you.
Tried with Nuitka-2.5rc9, same problem

- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.
```
2.4.10
Commercial: None
Python: 3.11.2 (main, Aug 26 2024, 07:20:54) [GCC 12.2.0]
Flavor: Debian Python
Executable: /home/rweiss/work/kivy_clipboard/venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Debian 12
Version C compiler: /usr/bin/gcc (gcc 12).
```

- How did you install Nuitka and Python
Nuitka: pip
Python and pip: apt

  Did you use pip, anaconda, deb, rpm, from source, git clone, then install into a virtualenv or
  not, this is very important usually and one thing, the above command does not tell us (yet).

I installed Python and pip using apt, then I created a venv and all required modules were installed into that venv using pip. 

- The specific PyPI names and versions
```
Package            Version
------------------ ---------
certifi            2024.8.30
charset-normalizer 3.4.0
docutils           0.21.2
idna               3.10
Kivy               2.3.0
Kivy-Garden        0.1.5
Nuitka             2.4.10
ordered-set        4.1.0
pip                23.0.1
Pygments           2.18.0
requests           2.32.3
setuptools         66.1.1
urllib3            2.2.3
zstandard          0.23.0
```

- Also supply a Short, Self Contained, Correct, Example

```
# compiled using venv/bin/python -m nuitka --standalone myapp.py

import kivy
from kivy.app import App
from kivy.uix.button import Button
from kivy.core.clipboard import Clipboard

class MyApp(App):
    def build(self):
        button = Button(text='Click 2 Crash', on_press=self.copy2clip)
        return button
    
    def copy2clip(self, instance):
        Clipboard.copy('Hello World!')

if __name__ == '__main__':
    MyApp().run()
```

- Provide in your issue the Nuitka options used
  [Nuitka Options in the code](https://nuitka.net/doc/user-manual.html#nuitka-options-in-the-code)
The link doesn't bring me to the advertised information.

I can work around the problem by manually including these modules:
kivy.core.clipboard.clipboard_xclip
kivy.core.clipboard.clipboard_xsel
kivy.core.clipboard.clipboard_dbusklipper
kivy.core.clipboard.clipboard_gtk3
kivy.core.clipboard.clipboard_sdl2
kivy.core.clipboard.clipboard_dummy

A workaround like this is not needed for Windows, so I wonder if something is missing for Linux.

An unrelated request:
Could you please consider a more positive text when someone is too dumb to fill out the template?
Something like "Please fill out the template, otherwise we can not work on this issue" would have been totally sufficient, and far more friendlier. Thank you in advance.

Regards,
Reinhard

**Comment by kayhayen** [comment]
You can make a PR to change the issue template to enhance it. I might be blind to some of its shortcomings. I do not make it a form where filling out is forced, but I expect the courtesy of providing necessary information. Way too many people think they know that information won't be needed, or are unwilling to spend even a tiny bit of time. I for my part do not find the text unfriendly, only informative of what's going to have to happen. I cannot count the amount of times, where I have made exceptions only to regret it later on.

**Comment by kayhayen** [comment]
Do we think, `dummy` is really needed, it may just be a fallback. I remember adding stuff for clipboard on macOS because it was complaining there at launch about missing things, Kivy is usually good about that.

**Comment by rweiss123** [comment]
The kivy widget textinput relies on the existence of a clipboard implementation. From kivy/uix/textinput.py:
```
    def _ensure_clipboard(self):
        global Clipboard, CutBuffer
        if not Clipboard:
            from kivy.core.clipboard import Clipboard, CutBuffer
```
There are no further checks when the clipboard comes to being used:
```
    def copy(self, data=''):
        self._ensure_clipboard()
        if data:
            return Clipboard.copy(data)
        ...
```
Function `core_select_lib` (kivy/core/__init__.py, called from kivy/core/clipboard/__init__.py) goes through the list of `_clipboard` and tries to import until the first successful import. Imports can fail through exceptions, e.g. clipboard_gtk3.py:
```
import gi
gi.require_version('Gtk', '3.0')
```
gi.require_version() raises a ValueError exception on version mismatch (https://pygobject.gnome.org/guide/api/api.html).

My conclusion is that if all other clipboard methods fail to import, Kivy will import the clipboard_dummy and widgets will rely on its existence. I can't judge if this will ever happen, but my guess would be that it can happen, otherwise the Kivy developers wouldn't have added the dummy to the clipboard list.

Best regards,
Reinhard

**Comment by kayhayen** [comment]
The Kivy plugin has for Windows and macOS already manual code, I am moving this to standard package configuration and also a few more things from the Kivy plugin, while also adding Linux now.

**Comment by kayhayen** [comment]
Not sure why this was more visible for non-Linux, but I guess, it's complete now. Of course android might be still a thing, but we will cross that bridge later.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by rweiss123** [comment]
Works fine with 2.5rc10. Thank you.

Best regards,
Reinhard

**Comment by kayhayen** [comment]
Part of the 2.5 release I just made.
