### ISSUE TITLE
Nuitka recursion issue when building on mac

### ISSUE THREAD

**Issue by JustRedTTG** [Nuitka/Nuitka#3159]
This is an issue entirely coming from nuitka. 
When on Mac (macos-latest, GitHub actions system) 
With python 3.9 
After building nuitka fails to get the os?

Here are my logs from the end of running nuitka-action with latest nuitka: https://pastebin.com/BcvMm831

**Comment by kayhayen** [comment]
In the template, we have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that we do not want to be left guessing. For you it's easy to erase the issue template and expect us to ask you questions only as necessary, but we cannot do that. We would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore we are  likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."

**Comment by JustRedTTG** [comment]
I didn't get the template.. I'll make a new issue I guess
