### ISSUE TITLE
Can onefile mode make __file__ the same as the exe file's location?

### ISSUE THREAD

**Issue by monchin** [Nuitka/Nuitka#3162]
Hello, I need to use `--onefile` mode to compile my program, but I'm using `__file__` to get the location of my program. My code is like this:
```python
# nuitka-project: --standalone
# nuitka-project: --onefile
# main.py
print("my location:", __file__)
```
When I directly `python main.py`, the output is `my location: C:\Project\test\test_one_file\src\test_one_file\main.py`

Then I use nuitka to compile it: `python -m nuitka main.py --output-dir=build`, it'll get a directory "build/main.dist" with "main.exe" in it, and a onefile-mode "main.exe"
Keeping my commandline location fixed, I first test no-onefile-mode "main.exe" with `.\build\main.dist\main.exe`, the output is `my location: C:\Project\test\TEST_O~1\build\MAIN~1.DIS\main.py`, which is right.
But when I test onefile-mode "main.exe" with `.\build\main.exe`, the output is `my location: C:\Users\c.men\AppData\Local\Temp\ONEFIL~1\main.py`, which is not what I expect.

I know this is because onefile-mode file would unzip itself first and then execute, so I know this is not a bug. But it would be very difficult when it needs some other files with relative location to the program, especially when these files may need to be changed. So I'm wondering is there a good way to handle these situations?

I found that there is a parameter `--include-onefile-external-data`, but I got a failure when tried it. My code is:
```python
# nuitka-project: --standalone
# nuitka-project: --onefile
# nuitka-project: --include-onefile-external-data={MAIN_DIRECTORY}/.env=.env
# main.py
import os
from pathlib import Path
from dotenv import load_dotenv
MAIN_DIR = Path(__file__).parent
if not (MAIN_DIR / '.env').exists():
    print("no .env file")
load_dotenv(MAIN_DIR / '.env')
print("env path", MAIN_DIR / '.env')
print("TEST_EV", os.getenv("TEST_EV"))
```
and with a `.env` file in the same directory:
```
TEST_EV=test
```
With `python -m nuitka main.py`, `build/main.dist/main.exe` behaves what I want, but `build/main.exe` shows
```
no .env file
env path C:\Users\c.men\AppData\Local\Temp\ONEFIL~1\.env
TEST_EV None
```
I may need to change the value of "TEST_EV" in .env, so I can't use `--include-data-files`. If it is proper to use `--include-onefile-external-data` in this situation, could you please give me an example?

**Comment by Choonholic** [comment]
I respectfully **DISAGREE**.

Changing the behavior could be quite risky, as I believe many people, including myself, use `__file__` to get unpacked files' path.

I suggest you using `sys.argv[0]` instead of `__file__`.

**Comment by Choonholic** [comment]
If you should detect using Nuitka or not, please refer to the follow:

```
nuitka_installed = True if COMPILED_KEY in globals() else False
```

**Comment by kayhayen** [comment]
Nuitka makes `sys.argv[0]` and absolute path, and that one should be used. We use the `.py` suffix for `__file__`, because a lot of code is written that expects this to be a Python file, of which the suffix becomes removed, like `[:-3]` to get a basename, or split by dot on non-Windows, etc. and the `__compiled__` value has attributes to help you.

The way it's intended, internal data is near `os.path.dirname(__file__)` and external data near `sys.argv[0]`.

I have to compliment you. From my experience, most people are confused that current directory doesn't work as they are used to, being `__file__` relative is principle very good code. However, for onefile, two values are needed, and this is the solution I have. I am not super happy with it, but that's what I got now as the best.

**Comment by monchin** [comment]
> Nuitka makes `sys.argv[0]` and absolute path, and that one should be used. We use the `.py` suffix for `__file__`, because a lot of code is written that expects this to be a Python file, of which the suffix becomes removed, like `[:-3]` to get a basename, or split by dot on non-Windows, etc. and the `__compiled__` value has attributes to help you.
> 
> The way it's intended, internal data is near `os.path.dirname(__file__)` and external data near `sys.argv[0]`.
> 
> I have to compliment you. From my experience, most people are confused that current directory doesn't work as they are used to, being `__file__` relative is principle very good code. However, for onefile, two values are needed, and this is the solution I have. I am not super happy with it, but that's what I got now as the best.

Thank you @kayhayen , I'll try `sys.argv`. But I still want to know how to use `--include-onefile-external-data`, because I didn't make it clear after reading the help document
```
    --include-onefile-external-data=PATTERN
                        Include the specified data file patterns outside of
                        the onefile binary, rather than on the inside. Makes
                        only sense in case of '--onefile' compilation. First
                        files have to be specified as included somehow, then
                        this refers to target paths. Default empty.
```
Could you please give an example how to use it? Thank you!

**Comment by kayhayen** [comment]
You use --include-data* options on whatever files you need to include. And with this option, you decide if they end up near the unpacked binary or near the created onefile binary. I agree, this need to also use those other options should be made more clear, will add that.

**Comment by kayhayen** [comment]
Examples are really in low supply too, I agree. For every option, there should be one, but who is going to create those?

**Comment by monchin** [comment]
Thank you! I tried `sys.argv` and `__compiled__` and they works perfectly for me, so it seems this option is not need urgently for me now.

**Comment by kayhayen** [comment]
The option is mainly for people like me, who won't write build scripts, but want to do everything on the command line, include the copying of files. Nuitka can of course be very helpful at locating files, esp. in the project options, but using variable for the main script directory as a source, or package data, but that's a style thing, which demos could show. I will add it to the list of things, that I will be asking help with, to create examples.

**Comment by jeffjiang0613** [comment]
> Nuitka makes `sys.argv[0]` and absolute path, and that one should be used. We use the `.py` suffix for `__file__`, because a lot of code is written that expects this to be a Python file, of which the suffix becomes removed, like `[:-3]` to get a basename, or split by dot on non-Windows, etc. and the `__compiled__` value has attributes to help you.
> 
> The way it's intended, internal data is near `os.path.dirname(__file__)` and external data near `sys.argv[0]`.
> 
> I have to compliment you. From my experience, most people are confused that current directory doesn't work as they are used to, being `__file__` relative is principle very good code. However, for onefile, two values are needed, and this is the solution I have. I am not super happy with it, but that's what I got now as the best.

I use nuitka to compile a py source code to a pyd with --module argument, how could I get the full path of this compiled pyd?

**Comment by kayhayen** [comment]
In module mode to get the path where the Python file would be, but the actualy `.pyd/.so` path is not so easy. Nuitka lies in `__file__` because chances are some codes will rely on the `.py` suffix of `__file__` and not `Mini3.cpython-312-x86_64-linux-gnu.so` e.g. which will lead to errors accessing the file.

I am adding a `__compiled__.containing_file` maybe, I need to investigate that, it ought to be very easy, since `__compiled__.containing_dir` which is what most people care for `os.path.dirname(__file__)` for the most cases except app bundles on macOS and standalone mode. However, assuming you want to know where the code lives, it would be quite different, and probably needs another name. I am taking note of that idea, don't hold your breath for it though.
