### ISSUE TITLE
multiprocessing issue in exe file created with Nuitka

### ISSUE THREAD

**Issue by Tom1403** [Nuitka/Nuitka#3163]
Hi everybody.
I have a python program which completes some tasks by defining some processes using the multiprocessing library.
While in Anaconda, the program starts processes and completes the given tasks.
After making the exe file using PyInstaller, also it works as expected.
However, when I make the exe file from my program using Nuitka, it runs around 30 times slower!
These are the libraries my program imports:

main_program.py :
import cv2
import os
import time
import numpy as np
from hashlib import sha3_256
from multiprocessing import Process, Queue
from cryptography.hazmat.primitives.ciphers import Cipher
from cryptography.hazmat.primitives.ciphers.modes import CTR
from cryptography.hazmat.primitives.ciphers.algorithms import AES128

gui.py :
from tkinter import *
from tkinter import ttk
from tkinter import filedialog
from threading import Thread
from PIL import ImageTk, Image
from multiprocessing import freeze_support
import main_program

I am using an Intel Core i9-10900 cpu with 16.0 GB ram.
My installed packages are listed below.

I create the exe file using this command:
nuitka --standalone --enable-plugin=tk-inter gui.py

Thanks

--------------------------

(base) M:\TMP>nuitka --version
2.4.10
Commercial: None
Python: 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\user01\anaconda3\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64\cl.exe (cl 14.3).

(base) M:\TMP>pip list -v
Package                           Version            Installer
--------------------------------- ------------------ --------
aiobotocore                       2.12.3             conda
aiohttp                           3.9.5              conda
aioitertools                      0.7.1              conda
aiosignal                         1.2.0              conda
alabaster                         0.7.16             conda
altair                            5.0.1              conda
anaconda-anon-usage               0.4.4              conda
anaconda-catalogs                 0.2.0              conda
anaconda-client                   1.12.3             conda
anaconda-cloud-auth               0.5.1              conda
anaconda-navigator                2.6.0              conda
anaconda-project                  0.11.1             conda
annotated-types                   0.6.0              conda
anyio                             4.2.0              conda
appdirs                           1.4.4              
archspec                          0.2.3              conda
argon2-cffi                       21.3.0             conda
argon2-cffi-bindings              21.2.0             conda
arrow                             1.2.3              conda
astroid                           2.14.2             conda
astropy                           6.1.0              conda
astropy-iers-data                 0.2024.6.3.0.31.14 conda
asttokens                         2.0.5              conda
async-lru                         2.0.4              conda
atomicwrites                      1.4.0              conda
attrs                             23.1.0             conda
Automat                           20.2.0             conda
autopep8                          2.0.4              conda
Babel                             2.11.0             conda
bcrypt                            3.2.0              conda
beautifulsoup4                    4.12.3             conda
binaryornot                       0.4.4              conda
black                             24.4.2             conda
bleach                            4.1.0              conda
blinker                           1.6.2              conda
bokeh                             3.4.1              conda
boltons                           23.0.0             conda
botocore                          1.34.69            conda
Bottleneck                        1.3.7              conda
Brotli                            1.0.9              conda
cachetools                        5.3.3              conda
certifi                           2024.6.2           conda
cffi                              1.16.0             conda
chardet                           4.0.0              conda
charset-normalizer                2.0.4              conda
click                             8.1.7              conda
cloudpickle                       2.2.1              conda
colorama                          0.4.6              conda
colorcet                          3.1.0              conda
comm                              0.2.1              conda
conda                             24.5.0             conda
conda-build                       24.5.1             conda
conda-content-trust               0.2.0              conda
conda_index                       0.5.0              conda
conda-libmamba-solver             24.1.0             conda
conda-pack                        0.7.1              conda
conda-package-handling            2.3.0              conda
conda_package_streaming           0.10.0             conda
conda-repo-cli                    1.0.88             conda
conda-token                       0.5.0+1.g2209e04   conda
constantly                        23.10.4            conda
contourpy                         1.2.0              conda
cookiecutter                      2.6.0              conda
cryptography                      42.0.5             conda
cssselect                         1.2.0              conda
cycler                            0.11.0             conda
cytoolz                           0.12.2             conda
dask                              2024.5.0           conda
dask-expr                         1.1.0              conda
datashader                        0.16.2             conda
debugpy                           1.6.7              conda
decorator                         5.1.1              conda
defusedxml                        0.7.1              conda
diff-match-patch                  20200713           conda
dill                              0.3.8              conda
distributed                       2024.5.0           conda
distro                            1.9.0              conda
docstring-to-markdown             0.11               conda
docutils                          0.18.1             conda
entrypoints                       0.4                conda
et-xmlfile                        1.1.0              conda
executing                         0.8.3              conda
fastjsonschema                    2.16.2             conda
filelock                          3.13.1             conda
flake8                            7.0.0              conda
Flask                             3.0.3              conda
fonttools                         4.51.0             conda
frozendict                        2.4.2              conda
frozenlist                        1.4.0              conda
fsspec                            2024.3.1           conda
gensim                            4.3.2              conda
gitdb                             4.0.7              conda
GitPython                         3.1.37             conda
greenlet                          3.0.1              conda
h5py                              3.11.0             conda
HeapDict                          1.0.1              conda
holoviews                         1.19.0             conda
hvplot                            0.10.0             conda
hyperlink                         21.0.0             conda
idna                              3.7                conda
imagecodecs                       2023.1.23          conda
imageio                           2.33.1             conda
imagesize                         1.4.1              conda
imbalanced-learn                  0.12.3             conda
importlib-metadata                7.0.1              conda
incremental                       22.10.0            conda
inflection                        0.5.1              conda
iniconfig                         1.1.1              conda
intake                            0.7.0              conda
intervaltree                      3.1.0              conda
ipykernel                         6.28.0             conda
ipython                           8.25.0             conda
ipython-genutils                  0.2.0              conda
ipywidgets                        7.8.1              conda
isort                             5.13.2             conda
itemadapter                       0.3.0              conda
itemloaders                       1.1.0              conda
itsdangerous                      2.2.0              conda
jaraco.classes                    3.2.1              conda
jedi                              0.18.1             conda
jellyfish                         1.0.1              conda
Jinja2                            3.1.4              conda
jmespath                          1.0.1              conda
joblib                            1.4.2              conda
jpeglib                           1.0.1              pip
json5                             0.9.6              conda
jsonpatch                         1.33               conda
jsonpointer                       2.1                
jsonschema                        4.19.2             conda
jsonschema-specifications         2023.7.1           conda
jupyter                           1.0.0              conda
jupyter_client                    8.6.0              conda
jupyter-console                   6.6.3              conda
jupyter_core                      5.7.2              conda
jupyter-events                    0.10.0             conda
jupyter-lsp                       2.2.0              conda
jupyter_server                    2.14.1             conda
jupyter_server_terminals          0.4.4              conda
jupyterlab                        4.0.11             conda
jupyterlab-pygments               0.1.2              conda
jupyterlab_server                 2.25.1             conda
jupyterlab-widgets                1.0.0              conda
keyring                           24.3.1             conda
kiwisolver                        1.4.4              conda
lazy_loader                       0.4                conda
lazy-object-proxy                 1.10.0             conda
lckr_jupyterlab_variableinspector 3.1.0              conda
libarchive-c                      2.9                conda
libmambapy                        1.5.8              conda
linkify-it-py                     2.0.0              conda
llvmlite                          0.42.0             conda
lmdb                              1.4.1              conda
locket                            1.0.0              conda
lxml                              5.2.1              conda
lz4                               4.3.2              conda
Markdown                          3.4.1              conda
markdown-it-py                    2.2.0              conda
MarkupSafe                        2.1.3              conda
matplotlib                        3.8.4              conda
matplotlib-inline                 0.1.6              conda
mccabe                            0.7.0              conda
mdit-py-plugins                   0.3.0              conda
mdurl                             0.1.0              conda
menuinst                          2.1.1              conda
mistune                           2.0.4              conda
mkl-fft                           1.3.8              conda
mkl-random                        1.2.4              conda
mkl-service                       2.4.0              
more-itertools                    10.1.0             conda
mpmath                            1.3.0              conda
msgpack                           1.0.3              conda
multidict                         6.0.4              conda
multipledispatch                  0.6.0              conda
mypy                              1.10.0             conda
mypy-extensions                   1.0.0              conda
navigator-updater                 0.5.1              conda
nbclient                          0.8.0              conda
nbconvert                         7.10.0             conda
nbformat                          5.9.2              conda
nest-asyncio                      1.6.0              conda
networkx                          3.2.1              conda
nltk                              3.8.1              conda
notebook                          7.0.8              conda
notebook_shim                     0.2.3              conda
Nuitka                            2.4.10             pip
numba                             0.59.1             conda
numexpr                           2.8.7              conda
numpy                             1.26.4             conda
numpydoc                          1.7.0              conda
opencv-python                     4.10.0.84          pip
openpyxl                          3.1.2              conda
ordered-set                       4.1.0              pip
overrides                         7.4.0              conda
packaging                         23.2               conda
pandas                            2.2.2              conda
pandocfilters                     1.5.0              conda
panel                             1.4.4              conda
param                             2.1.0              conda
paramiko                          2.8.1              conda
parsel                            1.8.1              conda
parso                             0.8.3              conda
partd                             1.4.1              conda
pathspec                          0.10.3             conda
patsy                             0.5.6              conda
pexpect                           4.8.0              conda
pickleshare                       0.7.5              conda
pillow                            10.3.0             conda
pip                               24.0               
pkce                              1.0.3              conda
pkginfo                           1.10.0             conda
platformdirs                      3.10.0             conda
plotly                            5.22.0             conda
pluggy                            1.0.0              conda
ply                               3.11               conda
prometheus-client                 0.14.1             conda
prompt-toolkit                    3.0.43             conda
Protego                           0.1.16             conda
protobuf                          3.20.3             
psutil                            5.9.0              conda
ptyprocess                        0.7.0              conda
pure-eval                         0.2.2              conda
py-cpuinfo                        9.0.0              conda
pyarrow                           14.0.2             conda
pyasn1                            0.4.8              conda
pyasn1-modules                    0.2.8              
pycodestyle                       2.11.1             conda
pycosat                           0.6.6              conda
pycparser                         2.21               conda
pyct                              0.5.0              conda
pycurl                            7.45.2             
pydantic                          2.5.3              conda
pydantic_core                     2.14.6             conda
pydeck                            0.8.0              conda
PyDispatcher                      2.0.5              conda
pydocstyle                        6.3.0              conda
pyerfa                            2.0.1.4            conda
pyflakes                          3.2.0              conda
Pygments                          2.15.1             conda
PyJWT                             2.8.0              conda
pylint                            2.16.2             conda
pylint-venv                       3.0.3              conda
pyls-spyder                       0.4.0              
PyNaCl                            1.5.0              conda
pyodbc                            5.0.1              conda
pyOpenSSL                         24.0.0             conda
pyparsing                         3.0.9              conda
PyQt5                             5.15.10            conda
PyQt5-sip                         12.13.0            conda
PyQtWebEngine                     5.15.6             conda
PySocks                           1.7.1              conda
pytest                            7.4.4              conda
python-dateutil                   2.9.0.post0        conda
python-docx                       1.1.2              pip
python-dotenv                     0.21.0             conda
python-json-logger                2.0.7              conda
python-lsp-black                  2.0.0              conda
python-lsp-jsonrpc                1.1.2              conda
python-lsp-server                 1.10.0             conda
python-slugify                    5.0.2              conda
python-snappy                     0.6.1              conda
pytoolconfig                      1.2.6              conda
pytz                              2024.1             conda
pyviz_comms                       3.0.2              conda
pywavelets                        1.5.0              conda
pywin32                           305.1              
pywin32-ctypes                    0.2.2              conda
pywinpty                          2.0.10             conda
PyYAML                            6.0.1              conda
pyzmq                             25.1.2             conda
QDarkStyle                        3.2.3              conda
qstylizer                         0.2.2              conda
QtAwesome                         1.2.2              conda
qtconsole                         5.5.1              conda
QtPy                              2.4.1              conda
queuelib                          1.6.2              conda
referencing                       0.30.2             conda
regex                             2023.10.3          conda
requests                          2.32.2             conda
requests-file                     1.5.1              conda
requests-toolbelt                 1.0.0              conda
rfc3339-validator                 0.1.4              conda
rfc3986-validator                 0.1.1              conda
rich                              13.3.5             conda
rope                              1.12.0             conda
rpds-py                           0.10.6             conda
Rtree                             1.0.1              conda
ruamel.yaml                       0.17.21            conda
ruamel-yaml-conda                 0.17.21            conda
s3fs                              2024.3.1           conda
scikit-image                      0.23.2             conda
scikit-learn                      1.4.2              conda
scipy                             1.13.1             conda
Scrapy                            2.11.1             conda
seaborn                           0.13.2             conda
semver                            3.0.2              conda
Send2Trash                        1.8.2              conda
service-identity                  18.1.0             conda
setuptools                        69.5.1             
sip                               6.7.12             conda
six                               1.16.0             conda
smart-open                        5.2.1              conda
smmap                             4.0.0              conda
sniffio                           1.3.0              conda
snowballstemmer                   2.2.0              conda
sortedcontainers                  2.4.0              conda
soupsieve                         2.5                conda
Sphinx                            7.3.7              conda
sphinxcontrib-applehelp           1.0.2              conda
sphinxcontrib-devhelp             1.0.2              conda
sphinxcontrib-htmlhelp            2.0.0              conda
sphinxcontrib-jsmath              1.0.1              conda
sphinxcontrib-qthelp              1.0.3              conda
sphinxcontrib-serializinghtml     1.1.10             conda
spyder                            5.5.1              conda
spyder-kernels                    2.5.0              conda
SQLAlchemy                        2.0.30             conda
stack-data                        0.2.0              conda
statsmodels                       0.14.2             conda
streamlit                         1.32.0             conda
sympy                             1.12               conda
tables                            3.9.2              conda
tabulate                          0.9.0              conda
tblib                             1.7.0              conda
tenacity                          8.2.2              conda
terminado                         0.17.1             conda
text-unidecode                    1.3                conda
textdistance                      4.2.1              conda
threadpoolctl                     2.2.0              conda
three-merge                       0.1.1              conda
tifffile                          2023.4.12          conda
tinycss2                          1.2.1              conda
tldextract                        3.2.0              conda
toml                              0.10.2             conda
tomli                             2.0.1              conda
tomlkit                           0.11.1             conda
toolz                             0.12.0             conda
tornado                           6.4.1              conda
tqdm                              4.66.4             conda
traitlets                         5.14.3             conda
truststore                        0.8.0              conda
Twisted                           23.10.0            conda
twisted-iocpsupport               1.0.2              conda
typing_extensions                 4.11.0             conda
tzdata                            2023.3             conda
uc-micro-py                       1.0.1              conda
ujson                             5.10.0             conda
unicodedata2                      15.1.0             conda
Unidecode                         1.2.0              conda
urllib3                           2.2.2              conda
w3lib                             2.1.2              conda
watchdog                          4.0.1              conda
wcwidth                           0.2.5              conda
webencodings                      0.5.1              conda
websocket-client                  1.8.0              conda
Werkzeug                          3.0.3              conda
whatthepatch                      1.0.2              conda
wheel                             0.43.0             
widgetsnbextension                3.6.6              conda
win-inet-pton                     1.1.0              conda
wrapt                             1.14.1             conda
xarray                            2023.6.0           conda
xlwings                           0.31.4             conda
xyzservices                       2022.9.0           conda
yapf                              0.40.2             conda
yarl                              1.9.3              conda
zict                              3.0.0              conda
zipp                              3.17.0             conda
zope.interface                    5.4.0              conda
zstandard                         0.22.0             conda

**Comment by kayhayen** [comment]
There had been issues with onefile, where it went through the onefile unpacking and was slower as a result. I don't know that multiprocessing is slower with Nuitka. 

This looks like a user error potentially, since your program always does the same thing, so forks behave the same, which on Windows could be fatal. I don't see the program doing much, so I don't even see anything happening at all, how did you measure the supposed slow down, and how sure are you it's not your AV that gives it a pause.

**Comment by kayhayen** [comment]
Closing for lack of feedback
