### ISSUE TITLE
mkl/../libmkl_intel_thread.so.2: undefined symbol: __kmpc_global_thread_num

### ISSUE THREAD

**Issue by ashutoshmishra1014** [Nuitka/Nuitka#3166]
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version
```
2.4.10
Commercial: None
Python: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
Flavor: Anaconda Python
Executable: /home/ashu/conda/uv_project/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 20.04.6
Version C compiler: /usr/bin/gcc (gcc 9).
```

- How did you install Nuitka and Python

My application is based on an internal project, all the dependencies are installed via pip inside a conda environment

- Also supply a Short, Self Contained, Correct, Example
`python -m nuitka --follow-imports --include-data-files=/home/ashu/conda/uv_project/lib/python3.10/site-packages/trimesh/resources/units_to_inches.json=trimesh/resources/units_to_inches.json --include-data-files=/home/home/ashu/checkouts/uv_project/shader/*.*=shader/ --standalone --onefile --report=compilation-report.xml ./training/train.py`

- Error
```
/home/ashu/conda/uv_project/train.bin: symbol lookup error: /scratch/918965.tinygpu/onefile_2853721_1729788876_476030/mkl/../libmkl_intel_thread.so.2: undefined symbol: __kmpc_global_thread_num
```

Please note that I am doing the Nuitka compilation on a cluster node on HPC in case this is relevant for this problem. I have done a similar compilation on a local machine and it worked fine but surprisingly not on an HPC machine. (HPC machine was needed for the GPU access)

**Comment by kayhayen** [comment]
In the template, we have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that we do not want to be left guessing. For you it's easy to erase the issue template and expect us to ask you questions only as necessary, but we cannot do that. We would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore we are  likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."

**Comment by ashutoshmishra1014** [comment]
I have now realised it was not a nuitka bug, hence closing the issue. Will adhere to the issue template more strictly from next time. Thanks anyways.
