### ISSUE TITLE
Compile pywin32 with Nuitka

### ISSUE THREAD

**Issue by BotovodWF** [Nuitka/Nuitka#3171]
Hello, please teach me how to compile files with pywin32 libraries. I have looked at other requests, read the article https://nuitka.net/doc/commercial/windows-service.html on the website, asked ChatGPT, but I didn't find a solution. How to compile the code
```
import win32gui
import win32con
import win32api

def wait_for_notepad():
    While True:
        hwnd = win32gui.FindWindow(None, “Untitled - Notepad”)
        if hwnd:
            win32gui.ShowWindow(hwnd, win32con.SW_NORMAL)
            break

wait_for_notepad()
```
In one executable file? I got only ImportError

```
C:\Projects\Pycharm\AUTOREG_WARFACE>nuitka --version
2.4.11
Commercial: None
Python: 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Python\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64\cl.exe (cl 14.3).

C:\Projects\Pycharm\AUTOREG_WARFACE>python --version
Python 3.9.9

Translated with DeepL.com (free version)
```

Please give me the final team for Nuitka, really please....

**Comment by kayhayen** [comment]
Your example code is not even Python, you need to find a better bot to make issue reports.

**Comment by kayhayen** [comment]
You may want to use a supported flavor of Python, refer to the User Manual what you should use. The "Unknown" Flavor is indicative of something unsupported, pywin32 is working fine with official Python downloads.

**Comment by BotovodWF** [comment]
I apologize, creator of Nuitka, but why isn't it even python? I get this error on startup after compilation
`nuitka --standalone --onefile --include-package=win32gui --include-package=win32gui --include-package=win32con --include-package=win32api tests_pywin32.py`

```
Traceback (most recent call last):
  File “C:\Temp\ONEFIL~1\tests_pywin32.py”, line 1, in <module>
    import win32gui
ImportError
```

How can I solve it?

**Comment by kayhayen** [comment]
Copy the code from the issue into a Python file and try to execute it. Probably your translator did stupid things, I don't know that.

Download Python from here and use that: https://www.python.org/

What you use is not working with Nuitka, and I doubt you are capable of identifying it.

**Comment by BotovodWF** [comment]
Ok, maybe it's not python code, but it compiles from python to exe with pyinstaller, with nuitka, but I get this error when I run the compiled file. Question, how to fix this? win32api (and others) are taken from pywin32 library, how to add all these libraries to the executable for correct compilation in single file mode?

**Comment by BotovodWF** [comment]
```
import win32gui
import win32api

def RUS():
    window_handle = win32gui.GetForegroundWindow()
    result = win32api.SendMessage(window_handle, 0x0050, 0, 0x04190419)
    return result

RUS()
```

It's 100% python code and no compile without error after start exe file
