### ISSUE TITLE
Program crashed without error

### ISSUE THREAD

**Issue by 2cody** [Nuitka/Nuitka#3175]
```
2.4.11
Commercial: None
Python: 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\goven\AppData\Local\Programs\Python\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\cl.exe (cl 14.3).
```
Installed via pip
My problem is that the program compiled by nuitka, crashes at random times, no error, no nothing, just crashes.
Tried to run the exe through cmd to see the last message, but nothing.
Very please help, as I can't solve this problem for a long time.
Tried different compilation parameters, nothing helps.
`python -m nuitka --standalone --onefile core.py --windows-icon-from-ico=bin/icon.ico --enable-plugin=tk-inter --include-package-data=bip_utils --include-package=eth_hash --follow-imports --output-dir=bin --no-deployment-flag=self-execution --deployment`

**Comment by kayhayen** [comment]
Next time try reading and following the issue template.

In the template, we have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that we do not want to be left guessing. For you it's easy to erase the issue template and expect us to ask you questions only as necessary, but we cannot do that. We would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore we are  likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
