### ISSUE TITLE
Conflict with Standard Library Module Causes Nuitka Packaging Errors

### ISSUE THREAD

**Issue by zbouslikhin** [Nuitka/Nuitka#3185]
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version

```
2.4.11
Commercial: None
Python: 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\zaid\AppData\Local\pypoetry\Cache\virtualenvs\test-TSWMVn5n-py3.11\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe (cl 14.3).
```

- How did you install Nuitka and Python

Python installed through pyenv-win
Nuitka installed via poetry add nuitka

- The specific PyPI names and versions

  > python -m pip list -v

```
nuitka      2.4.11 Python compiler with full language support and CPython compatibility
ordered-set 4.1.0  An OrderedSet is a custom MutableSet that remembers its order, so that every
zstandard   0.23.0 Zstandard bindings for Python
```

- Description

After bundling my source code to an executable, I kept getting Exceptions from Python's standard library such as asyncio. Thinking it was due to some other installed library, I omitted one by one, yet the problem persisted.
It turned out the cause of the issue was due to a package called `signal` I had in my code. Renaming the directory from `signal` to `filter_signal` solved the problem.

Here is a tree view of the directory:

└───test
    │   poetry.lock
    │   pyproject.toml
    │
    └───mypackage
        │   to_build.py
        │
        └───signal
                __init__.py

The content of the script to be compiled by Nuitka:

```mypackage/to_build.py
from asyncio import run

async def main_test():
    print("h")


def main():
    run(main_test())


if __name__ == "__main__":
    main()
```

`to_build.py` was compiled using the following command:
` python -m nuitka --deployment --standalone --onefile --msvc=latest --follow-imports .\mypackage\test.py`

And the traceback thrown after running the generated executable:
```
Traceback (most recent call last):
  File "C:\temp\ON411C~1\to_build.py", line 12, in <module>
  File "C:\temp\ON411C~1\to_build.py", line 8, in main
  File "C:\temp\ON411C~1\asyncio\runners.py", line 189, in run
  File "C:\temp\ON411C~1\asyncio\runners.py", line 59, in __enter__
  File "C:\temp\ON411C~1\asyncio\runners.py", line 137, in _lazy_init
  File "C:\temp\ON411C~1\asyncio\events.py", line 805, in new_event_loop
  File "C:\temp\ON411C~1\asyncio\events.py", line 695, in new_event_loop
  File "C:\temp\ON411C~1\asyncio\windows_events.py", line 315, in __init__
  File "C:\temp\ON411C~1\asyncio\proactor_events.py", line 638, in __init__
AttributeError: module 'signal' has no attribute 'set_wakeup_fd'
Exception ignored in: <function BaseEventLoop.__del__ at 0x000002016A6291C0>
Traceback (most recent call last):
  File "C:\temp\ON411C~1\asyncio\base_events.py", line 691, in __del__
  File "C:\temp\ON411C~1\asyncio\proactor_events.py", line 687, in close
AttributeError: module 'signal' has no attribute 'set_wakeup_fd'
```

**Comment by kayhayen** [comment]
I cannot reproduce this one on Linux with neither 3.12 nor 3.11, and 3.11 on Windows too, I also somehow feel I would know it. Your "unknown" flavor is potentially an unsupported form of Python. This works for all Python versions supporting asyncio I would assume. Please detail what Python flavor you are using.

**Comment by KRRT7** [comment]
> I cannot reproduce this one on Linux with neither 3.12 nor 3.11, and 3.11 on Windows too, I also somehow feel I would know it. Your "unknown" flavor is potentially an unsupported form of Python. This works for all Python versions supporting asyncio I would assume. Please detail what Python flavor you are using.

that sounds strange to me, he mentions he used pyenv-win, which is essentially just a CLI wrapper over python.org installers, which it grabs from the https://www.python.org/ftp/python/ and searches for the windows MSI installer of the requested python version

**Comment by zbouslikhin** [comment]
I'm not using a flavored Python. As @KRRT7 explained, pyenv is just a wrapper over the Python Windows MSI installer. 
I tried without using pyenv, but installing Python straight using the MSI installer, the problem persists.

I created a repo as an example to reproduce this:
- https://github.com/zbouslikhin/nuitka-conflict-bug

**Comment by KRRT7** [comment]
> I'm not using a flavored Python. As @KRRT7 explained, pyenv is just a wrapper over the Python Windows MSI installer. I tried without using pyenv, but installing Python straight using the MSI installer, the problem persists.
> 
> I created a repo as an example to reproduce this:
> 
> * https://github.com/zbouslikhin/nuitka-conflict-bug

can you try without the `--follow-imports` flag?

**Comment by zbouslikhin** [comment]
> > I'm not using a flavored Python. As @KRRT7 explained, pyenv is just a wrapper over the Python Windows MSI installer. I tried without using pyenv, but installing Python straight using the MSI installer, the problem persists.
> > I created a repo as an example to reproduce this:
> > 
> > * https://github.com/zbouslikhin/nuitka-conflict-bug
> 
> can you try without the `--follow-imports` flag?

Same result, unfortunately

**Comment by KRRT7** [comment]
> > > I'm not using a flavored Python. As @KRRT7 explained, pyenv is just a wrapper over the Python Windows MSI installer. I tried without using pyenv, but installing Python straight using the MSI installer, the problem persists.
> > > I created a repo as an example to reproduce this:
> > > 
> > > * https://github.com/zbouslikhin/nuitka-conflict-bug
> > 
> > 
> > can you try without the `--follow-imports` flag?
> 
> Same result, unfortunately

I see you're using a venv managed by poetry, can you take poetry out of the loop and use a vanilla venv?

**Comment by zbouslikhin** [comment]
Cleaned up my Python paths, installed Python3.11 using the MSI installer. 
The error is the same.

**Comment by kayhayen** [comment]
But poetry is still being used, right?

**Comment by kayhayen** [comment]
There being a signal path in the path, probably means it's happening with CPython too. I believe standard library has no precedence over current directory, so signal is imported from there, and doesn't have what standard library has.

**Comment by kayhayen** [comment]
```
kayha@Muska MINGW64 ~/test/nuitka-conflict-bug (main)
$ python3.11 mypackage/test.py 
Traceback (most recent call last):
  File "C:\Users\kayha\test\nuitka-conflict-bug\mypackage\test.py", line 12, in <module>
    main()
  File "C:\Users\kayha\test\nuitka-conflict-bug\mypackage\test.py", line 8, in main
    run(main_test())
  File "C:\Python311_64\Lib\asyncio\runners.py", line 189, in run
    with Runner(debug=debug) as runner:
  File "C:\Python311_64\Lib\asyncio\runners.py", line 59, in __enter__
    self._lazy_init()
  File "C:\Python311_64\Lib\asyncio\runners.py", line 137, in _lazy_init
    self._loop = events.new_event_loop()
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311_64\Lib\asyncio\events.py", line 806, in new_event_loop
    return get_event_loop_policy().new_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311_64\Lib\asyncio\events.py", line 695, in new_event_loop
    return self._loop_factory()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311_64\Lib\asyncio\windows_events.py", line 315, in __init__
    super().__init__(proactor)
  File "C:\Python311_64\Lib\asyncio\proactor_events.py", line 642, in __init__
    signal.set_wakeup_fd(self._csock.fileno())
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'signal' has no attribute 'set_wakeup_fd'
sys:1: RuntimeWarning: coroutine 'main_test' was never awaited
Exception ignored in: <function BaseEventLoop.__del__ at 0x00000207F7B74EA0>
Traceback (most recent call last):
  File "C:\Python311_64\Lib\asyncio\base_events.py", line 694, in __del__
  File "C:\Python311_64\Lib\asyncio\proactor_events.py", line 691, in close
AttributeError: module 'signal' has no attribute 'set_wakeup_fd'
```

What a shame to waste our time like that.

**Comment by zbouslikhin** [comment]
> ```
> kayha@Muska MINGW64 ~/test/nuitka-conflict-bug (main)
> $ python3.11 mypackage/test.py 
> Traceback (most recent call last):
>   File "C:\Users\kayha\test\nuitka-conflict-bug\mypackage\test.py", line 12, in <module>
>     main()
>   File "C:\Users\kayha\test\nuitka-conflict-bug\mypackage\test.py", line 8, in main
>     run(main_test())
>   File "C:\Python311_64\Lib\asyncio\runners.py", line 189, in run
>     with Runner(debug=debug) as runner:
>   File "C:\Python311_64\Lib\asyncio\runners.py", line 59, in __enter__
>     self._lazy_init()
>   File "C:\Python311_64\Lib\asyncio\runners.py", line 137, in _lazy_init
>     self._loop = events.new_event_loop()
>                  ^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Python311_64\Lib\asyncio\events.py", line 806, in new_event_loop
>     return get_event_loop_policy().new_event_loop()
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Python311_64\Lib\asyncio\events.py", line 695, in new_event_loop
>     return self._loop_factory()
>            ^^^^^^^^^^^^^^^^^^^^
>   File "C:\Python311_64\Lib\asyncio\windows_events.py", line 315, in __init__
>     super().__init__(proactor)
>   File "C:\Python311_64\Lib\asyncio\proactor_events.py", line 642, in __init__
>     signal.set_wakeup_fd(self._csock.fileno())
>     ^^^^^^^^^^^^^^^^^^^^
> AttributeError: module 'signal' has no attribute 'set_wakeup_fd'
> sys:1: RuntimeWarning: coroutine 'main_test' was never awaited
> Exception ignored in: <function BaseEventLoop.__del__ at 0x00000207F7B74EA0>
> Traceback (most recent call last):
>   File "C:\Python311_64\Lib\asyncio\base_events.py", line 694, in __del__
>   File "C:\Python311_64\Lib\asyncio\proactor_events.py", line 691, in close
> AttributeError: module 'signal' has no attribute 'set_wakeup_fd'
> ```
> 
> What a shame to waste our time like that.

Wasting your time was not the aim.
Thank you for resolving this anyways...

**Comment by zbouslikhin** [comment]
> Yeah, it's OK; shit happens, and I am still unhappy with my handling of it; checking out your code example wasn't that much time, but it really should be clear that you ought to be the first one to do it. You can help me understand how it came to that. Do you, e.g., have a working code base that you always compile in, say, CI, and when it doesn't work, although you suspect it should, you report it as a bug?
> 
> I wonder how to avoid this kind of report. Probably I should ask for evidence that the program works uncompiled more clearly. I don't think the current issue template does even ask for it.

Indeed. The bug report template does not ask for an evidence that the program works uncompiled.
In the same fashion you did, adding a section in the template to confirm that running the code using vanilla Python `python <entry_point>.py`
is perhaps enough to avoid such reports like this one where a package manager is used.

Another option would be adding a disclaimer mentioning that any bug report where a package manager is used, is considered invalid?

**Comment by kayhayen** [comment]
Not really, I was contemplating if the standard library handling differered, assuming in poetry it works. Nuitka needs to recognize the virtualenv and what's standard library and what not, and if it compiles some parts of the stdlib, that could cause the symptom, and so I was seeing it as a poetry specific bug. That kind of is a valid sort of bug to know and something I care about.

**Comment by kayhayen** [comment]
So I updated the issue template and put something at the top explaining it, going to delete this one though later.
