### ISSUE TITLE
Error when using mne library to read array file

### ISSUE THREAD

**Issue by HeHaina** [Nuitka/Nuitka#3191]
Hello,

I am encountering an issue when using the bundling library nuikta with the mne library. Specifically, when I attempt to bundle the ica.plot_sources() function from mne, an error occurs. The error message is: ("self"), and the function does not execute as expected. The program crashes and the process cannot be completed.

I have tried troubleshooting the issue, but the problem persists. I suspect the issue might be related to compatibility between nuikta and mne, or an unhandled exception in the ica.plot_sources() function when bundling.

My steps:
Use nuikta to bundle the mne library.
Call the ica.plot_sources() function.
Observe the error message: ("self").

I expect the ica.plot_sources() function to run successfully without errors. Specifically, I hope that nuikta will handle the ICA-related functions in mne correctly and prevent the ("self") error from occurring.

Below is my configuration（pip install）：
2.5rc13
Commercial: None
Python: 3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:20:11) [MSC v.1938 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: D:\Anaconda3\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: \AppData\Local\Nuitka\Nuitka\Cache\DOWNLO1\gcc\x86_64\14.2.0posix-19.1.1-12.0.0-msvcrt-r2\mingw64\bin\gcc.exe (gcc 14.2.0).

To assist with troubleshooting, I have attached a minimal reproducible example and the relevant data files. I would appreciate it if this issue could be addressed as soon as possible, as it is hindering my work.If the code I provided causes any issues while you're trying to solve the problem, please feel free to contact me.

Thank you for your help and support!

[ICAICA.zip](https://github.com/user-attachments/files/17730425/ICAICA.zip)

**Comment by kayhayen** [comment]
I managed to reproduce this, it's indeed another module that needs handling, and lives below mne.io so it's about reading files I assume.

**Comment by kayhayen** [comment]
Part of the 2.5 release I just made.

**Comment by HeHaina** [comment]
Thanks sir. I would like to confirm that the tool is working perfectly and all functions are operating as expected. Thank you for your hard work and support. I truly appreciate your efforts in ensuring everything runs smoothly.

Best regards,
