### ISSUE TITLE
--include-raw-dir do not copy files

### ISSUE THREAD

**Issue by zak-45** [Nuitka/Nuitka#3196]
Hi, 
For one of my project, I need some external exe file to be part of it. 
Saw the option --include-raw-dir and look promising except that during my test, nothing is copied.

this is the small code I used for test:
```
import os 
import sys 

try:
    dir = os.listdir(os.path.join(os.path.dirname(__file__), "assets"))
    print(dir)
except:
    print('no dir')

    
input('waiting...')
```

when I compile with --include-data-dir, I got mytext.txt file only, which is supposed to happend.
when I compile with --include-raw-dir, I got nothing, which is not supposed to happend.

It look's like this issue could be related: [https://github.com/Nuitka/Nuitka/issues/3116](https://github.com/Nuitka/Nuitka/issues/3116)

All tests done on Win 11 OS, with nuitka 2.4.11 installed using pip install.
Attached, I provided the report files from both compilation process.

This is the output from my tests:

C:\dev\test>dir /d assets
 Le volume dans le lecteur C s’appelle Acer
 Le numéro de série du volume est E863-80DF

 Répertoire de C:\dev\test\assets

[.]          [..]         myprog.exe   mytext.txt
               2 fichier(s)        6 572 038 octets
               2 Rép(s)  163 671 068 672 octets libres

C:\dev\test>**nuitka --standalone --onefile --include-data-dir=assets=assets --report=report_test_data.xml test.py**
Nuitka-Options: Used command line options: --standalone --onefile --include-data-dir=assets=assets --report=report_test_data.xml test.py
Nuitka: Starting Python compilation with Nuitka '2.4.11' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:anti-bloat: Not including 'socket' automatically in order to avoid bloat, but this may cause: can break calls of 'email.utils.make_msgid()'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: cl (cl 14.3).
Nuitka-Scons: Backend linking program with 6 files (no progress information available for this stage).
Nuitka-Scons: Compiled 6 C files using clcache with 6 cache hits and 0 cache misses.
Nuitka-Options: Included data file 'assets\mytext.txt' due to specified data dir 'assets' on command line.
Nuitka-Postprocessing: Creating single file from dist folder, this may take a while.
Nuitka-Onefile: Running bootstrap binary compilation via Scons.
Nuitka-Scons: Onefile C compiler: cl (cl 14.3).
Nuitka-Scons: Onefile linking program with 1 files (no progress information available for this stage).
Nuitka-Scons: Compiled 1 C files using clcache with 1 cache hits and 0 cache misses.
Nuitka-Onefile: Using compression for onefile payload.
Nuitka-Onefile: Onefile payload compression ratio (30.21%) size 19410908 to 5863080.
Nuitka-Onefile: Keeping onefile build directory 'test.onefile-build'.
Nuitka: Keeping dist folder 'test.dist' for inspection, no need to use it.
Nuitka: Keeping build directory 'test.build'.
Nuitka: Successfully created 'test.exe'.
Nuitka-Reports: Compilation report written to file 'report_test_data.xml'.

C:\dev\test>test.exe
['mytext.txt']
waiting...

C:\dev\test>**nuitka --standalone --onefile --include-raw-dir=assets=assets --report=report_test_raw.xml test.py**
Nuitka-Options: Used command line options: --standalone --onefile --include-raw-dir=assets=assets --report=report_test_raw.xml test.py
Nuitka: Starting Python compilation with Nuitka '2.4.11' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:anti-bloat: Not including 'socket' automatically in order to avoid bloat, but this may cause: can break calls of 'email.utils.make_msgid()'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: cl (cl 14.3).
Nuitka-Scons: Backend linking program with 6 files (no progress information available for this stage).
Nuitka-Scons: Compiled 6 C files using clcache with 6 cache hits and 0 cache misses.
Nuitka-Postprocessing: Creating single file from dist folder, this may take a while.
Nuitka-Onefile: Running bootstrap binary compilation via Scons.
Nuitka-Scons: Onefile C compiler: cl (cl 14.3).
Nuitka-Scons: Onefile linking program with 1 files (no progress information available for this stage).
Nuitka-Scons: Compiled 1 C files using clcache with 1 cache hits and 0 cache misses.
Nuitka-Onefile: Using compression for onefile payload.
Nuitka-Onefile: Onefile payload compression ratio (30.21%) size 19410858 to 5863187.
Nuitka-Onefile: Keeping onefile build directory 'test.onefile-build'.
Nuitka: Keeping dist folder 'test.dist' for inspection, no need to use it.
Nuitka: Keeping build directory 'test.build'.
Nuitka: Successfully created 'test.exe'.
Nuitka-Reports: Compilation report written to file 'report_test_raw.xml'.

C:\dev\test>test.exe
no dir
waiting...

C:\dev\test>

thanks.

[report_test_.zip](https://github.com/user-attachments/files/17747726/report_test_.zip)

**Comment by kayhayen** [comment]
I can confirm, the option had no effect.

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by zak-45** [comment]
Thanks, can confirm this work with the factory branch:

this is the result:
C:\dev\test>nuitka --standalone --onefile --include-raw-dir=assets=assets --report=report_test_raw.xml test.py
Nuitka-Options: Used command line options: --standalone --onefile --include-raw-dir=assets=assets --report=report_test_raw.xml test.py
Nuitka: Starting Python compilation with Nuitka '2.5rc14' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:anti-bloat: Not including 'socket' automatically in order to avoid bloat, but this may cause: can break calls of 'email.utils.make_msgid()'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: cl (cl 14.3).
Nuitka-Scons: Backend linking program with 6 files (no progress information available for this stage).
Nuitka-Scons: Compiled 6 C files using clcache with 1 cache hits and 5 cache misses.
Nuitka-Options: Included data file 'assets\myprog.exe' due to specified raw dir 'assets' on command line.
Nuitka-Options: Included data file 'assets\mytext.txt' due to specified raw dir 'assets' on command line.
Nuitka-Postprocessing: Creating single file from dist folder, this may take a while.
Nuitka-Onefile: Running bootstrap binary compilation via Scons.
Nuitka-Scons: Onefile C compiler: cl (cl 14.3).
Nuitka-Scons: Onefile linking program with 1 files (no progress information available for this stage).
Nuitka-Scons: Compiled 1 C files using clcache with 0 cache hits and 1 cache misses.
Nuitka-Onefile: Using compression for onefile payload.
Nuitka-Onefile: Onefile payload compression ratio (22.71%) size 25987592 to 5901813.
Nuitka-Onefile: Keeping onefile build directory 'test.onefile-build'.
Nuitka: Keeping dist folder 'test.dist' for inspection, no need to use it.
Nuitka: Keeping build directory 'test.build'.
Nuitka: Successfully created 'test.exe'.
Nuitka-Reports: Compilation report written to file 'report_test_raw.xml'.

C:\dev\test>test.exe
['myprog.exe', 'mytext.txt']
waiting...
