### ISSUE TITLE
Running single test 

### ISSUE THREAD

**Issue by bksahu** [Nuitka/Nuitka#320]
On executing  `$ ./tests/basics/run_all.py search BuiltinsTest.py` 
I get the following output
```
Using concrete python 2.7.12 on x86_64
Skipping Asserts.py
Skipping Assignments.py
Skipping BigConstants.py
Skipping Branching.py
Skipping BuiltinOverload.py
Skipping BuiltinSuper.py
Comparing output of 'BuiltinsTest.py' using '/usr/bin/python' with flags silent, expect_success, remove_output, recurse_all, original_file, cpython_cache ...
Comparing output of 'ClassMinimal.py' using '/usr/bin/python' with flags silent, expect_success, remove_output, recurse_all, original_file, cpython_cache ...
Comparing output of 'Classes.py' using '/usr/bin/python' with flags silent, expect_success, remove_output, recurse_all, original_file, cpython_cache ...
Comparing output of 'ComparisonChains.py' using '/usr/bin/python' with flags silent, expect_success, remove_output, recurse_all, original_file, cpython_cache ...
...
```

But I want to run the test only for `BuiltinsTest.py`. Is there any other flag to do so?

**Nuitka**: 0.6.3rc4
**Python**: 3.5.2 (default, Nov 12 2018, 13:43:14) 
**Executable**: /usr/bin/python3
**OS**: Linux
**Arch**: x86_64

**Comment by kayhayen** [comment]
Check out `nuitka/tools/testing/SearchModes.py` and their usages. I suggest you implement `only`, which is something I have too wanted before. Basically you would hunt for the first match and stop right after.

**Comment by bksahu** [comment]
Sure. I'm on it.
