### ISSUE TITLE
nuitka-1.6.6 worked successfully on msys64 but now nuitka-2.4.11 (latest) fails

### ISSUE THREAD

**Issue by noeldiviney** [Nuitka/Nuitka#3200]
Hello Kay.
I have been checking out the the history of running nuitka on the msys64 environment Windows 10 Pro Version 22H2 os build 19045.5131.
I would like to present the following results of building a "Hello World" example in a wxPython GUI with nuitka as follows 👎 

Nuitka Version 1.6.6  which also successfully builds and executes the wxPython GUI
The following nuitka-1.6.6.zip has the full details. 
[nuitka-1.6.6.zip](https://github.com/user-attachments/files/17788336/nuitka-1.6.6.zip)

Nuitka Version 1.8.3  which successfully builds and executes the wxPython GUI
The following nuitka-1.8.3.zip has the full details.
[nuitka-1.8.3.zip](https://github.com/user-attachments/files/17788417/nuitka-1.8.3.zip)

Nuitka Version 2.1.6 which also successfully build but fails to execute due failure to import "wx data"
The following nuitka-2.1.6.zip has the full details.
[nuitka-2.1.6.zip](https://github.com/user-attachments/files/17788426/nuitka-2.1.6.zip)

Nuitka Version 2.4.11 which fails to build and creates a "crash-report"
The following nuitka-2.4.11.zip has the full details.
[nuitka-2.4.11.zip](https://github.com/user-attachments/files/17788428/nuitka-2.4.11.zip)

I am available to help resolve this issue.
I am just one of the many thousands of Embedded Systems Developers who are using msys64 as a great Windows
environment and would love to have the protection the nuitka commercial offers.

Cheers Noel Diviney.

**Comment by kayhayen** [comment]
I made more assertions, to address that normpath doesn't work as expected on MSYSt64 MinGW, but as is happens I addressed an old issue the other day and saw a lot of assertions myself for #2628 so that's probably going to do it for you too.

**Comment by kayhayen** [comment]
Part of the 2.5.1 release.
