### ISSUE TITLE
MacOS: Icon does not get set with --onefile

### ISSUE THREAD

**Issue by dynamicsamurai816** [Nuitka/Nuitka#3205]
```
python -m nuitka --version
2.4.11
Commercial: None
Python: 3.9.20 (main, Sep  6 2024, 19:03:56)
Flavor: Homebrew Python
OS: Darwin
Arch: x86_64
macOSRelease: 15.1
Version C compiler: /usr/bin/clang (clang 16.0.0).
```

Nuitka installed with pip

Command:
`python -m nuitka --output-dir=dist --standalone --onefile --macos-create-app-bundle --macos-app-icon=assets/icon/icon.png test.py
`

I'm able to create a onefile on Mac successfully, however there seems to be an issue with setting the `--macos-app-icon`. When I leave `--onefile` out, the icon gets set correctly. If I execute the command **with** `--onefile`, the icon does not get set.

**Comment by kayhayen** [comment]
Don't use onefile and app bundle together, it's supposed to be used as a workaround for specific circumstances, and Nuitka should actively warn about it.

**Comment by kayhayen** [comment]
It's not identical, with onefile the program inside the app contains the DLLs and data files and unpacks them at runtime, not useful for apps, unless illegal filenames occur. The onefile might also pack the icons, of that I am not sure now, but I am not convinced, I feel like I saw icons myself on macOS recently working properly.

**Comment by kayhayen** [comment]
Note to self: I should not respond to issues that do not follow the issue template and have no reproducer.
