### ISSUE TITLE
pluggy plugins are not detected

### ISSUE THREAD

**Issue by saifjarboui** [Nuitka/Nuitka#3206]
Hi all,
I am using pluggy do defines hooks via entry point to my library
seems like nuitka --standalone is not taking into account dist/entry_points.txt
I tried manually to copy the package-dist folder and it worked

**Comment by Kevin-O-Hsu** [comment]
It seems that Nuitka itself does not have the function of embedding data files. You should try virtualbox instead.

**Comment by saifjarboui** [comment]
It can though.. like xml files.. but maybe that needs special configuration and ideally.. supporting the entry points detection for that package when using --include-package option

**Comment by KRRT7** [comment]
> Nuitka itself does not have the function of embedding data files.

on the contrary, we have very good support for that, to the point that it's slowing us down from working on more important things

**Comment by saifjarboui** [comment]
@KRRT7 
[example.zip](https://github.com/user-attachments/files/17816131/example.zip)


extract the folder, then ` pip install` path to `egg_sample_plugin` and `egg_sample`
then try to run the script sample.py
then compile it with 
`python -m nuitka --run --standalone --include-package=egg_sample_plugin path\to\sample.py`

**Comment by kayhayen** [comment]
You want to use `--include-distribution-metadata` which includes the information needed to lookup entry points at run time.

**Comment by kayhayen** [comment]
For third party packages, yaml configuration can be used. Here is an example

```
- module-name: 'opentelemetry.propagate' 
  data-files:
    - include-metadata:
        - 'opentelemetry-api'
```
