### ISSUE TITLE
Regression with exception handling from coroutines (was: Assertion Failure in Nuitka 2.5.1 with Telethon Integration)

### ISSUE THREAD

**Issue by 1Danish-00** [Nuitka/Nuitka#3211]
- **Nuitka Version:**
   ```
   2.5.1
   Commercial: None
   Python: 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]
   Flavor: CPython Official
   Executable: C:\Users\Devs\Desktop\BUILD\Scripts\python.exe
   OS: Windows
   Arch: x86_64
   WindowsRelease: 10
   Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64\cl.exe (cl 14.3).
   ```
   
- **Installation:**
   - **Nuitka**: Installed via pip.
   - **Python**: Installed using the official Windows setup installer.
   
- **PyPI Packages and Versions (venv)**:
   ```
   Package     Version
   ----------- -------
   Nuitka      2.5.1
   ordered-set 4.1.0
   pip         24.0
   pyaes       1.6.1
   pyasn1      0.6.1
   rsa         4.9
   Telethon    1.38.1
   zstandard   0.23.0
   ```

- **Command Used**:
   The following command was used to compile the script:
   ```
   python -m nuitka --msvc=latest --debug --standalone test.py
   ```

- **Code Snippet**:
   The script that produces the error is as follows:
   ```python
   from telethon import TelegramClient

   client = TelegramClient("test", 6, "eb06d4abfb49dc3eeb1aeb98ae0f581e")

   async def main():
       print("Starting client with bot_token...")
       await client.start(bot_token="8173941128:AAHU1XdBGhvXN93aK6TxWpgeQVWSpEhRSqI")

       print("Fetching client details...")
       me = await client.get_me()

       print(me.stringify())

       # sometimes same error comes here on disconnect too
       await client.disconnect()
       await client.log_out()

   client.loop.run_until_complete(main())
   ```

- **Error Message**:
   The error message encountered during runtime is:
   ```
   Starting client with bot_token...
   Assertion failed: HAS_ERROR_OCCURRED(tstate), file C:\Users\Devs\Desktop\BUILD\Lib\site-packages\nuitka\build\static_src\CompiledGeneratorTypeUncompiledIntegration.c, line 1
   ```

- **Additional Context:**
  - The issue began after upgrading to **Nuitka 2.5.1**, with the previous version of Nuitka working fine.
  - The error occurs when running the executable compiled by Nuitka, either during the start-up (`client.start()`) or sometimes during the disconnect operation (`client.disconnect()`).
  - Also The keys and tokens used in this code snippet are default and for demo purpose. You can **use the same** without replacing anything.

**Comment by 1Danish-00** [comment]
> This is a regression made during the 2.5 development, where we abstracted and unified exception handling, and made a mistake, since the code expects to be called with an exception set, but needs to also accept no exception set and return a value for that too.
> 
> Thanks for your report. This is fixed on the factory branch, which is a development version that is under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html
> 
> Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

Yes, its working fine! thank you for the quick fix.

**Comment by kayhayen** [comment]
Part of the 2.5.2 release I just made.
