### ISSUE TITLE
IMPORT_HARD_CTYPES : "Unexpected failure of hard import of 'ctypes'"

### ISSUE THREAD

**Issue by Sandv** [Nuitka/Nuitka#3215]
Thank you for the fantastic package nuitka! However, I am new to this and ran into problems. I am running into this issue with relatively benign code. Compiles with no errors. Runtime error as below. Thank you for any pointers to get this towork!

On runtime:
**IMPORT_HARD_CTYPES : "Unexpected failure of hard import of 'ctypes'"**

only occurs with --onefile
--standalone without onefile works

somewhat similiar to issue #2973 which remains unexplained.

The issue only arises with --onefile
checked with lates stable and the dev nuitka.
python installed from https://www.python.org/downloads/
checked with 3.9 and 3.11, same result

- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.
python -m nuitka --version
2.6rc2
Commercial: None
Python: 3.9.2rc1 (tags/v3.9.2rc1:4064156, Feb 17 2021, 11:25:18) [MSC v.1928 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\veit\source\PhotosepPy\ps\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

- How did you install Nuitka and Python
pip install, virtualenv

- The specific PyPI names and version
  > python -m pip list -v
Package           Version   Location                                             Installer
----------------- --------- ---------------------------------------------------- ---------
coloredlogs       15.0.1    c:\users\veit\source\photoseppy\ps\lib\site-packages pip
flatbuffers       24.3.25   c:\users\veit\source\photoseppy\ps\lib\site-packages pip
humanfriendly     10.0      c:\users\veit\source\photoseppy\ps\lib\site-packages pip
mpmath            1.3.0     c:\users\veit\source\photoseppy\ps\lib\site-packages pip
Nuitka            2.6rc2    c:\users\veit\source\photoseppy\ps\lib\site-packages pip
numpy             2.0.2     c:\users\veit\source\photoseppy\ps\lib\site-packages pip
onnxruntime       1.19.2    c:\users\veit\source\photoseppy\ps\lib\site-packages pip
opencv-python     4.10.0.84 c:\users\veit\source\photoseppy\ps\lib\site-packages pip
ordered-set       4.1.0     c:\users\veit\source\photoseppy\ps\lib\site-packages pip
packaging         24.2      c:\users\veit\source\photoseppy\ps\lib\site-packages pip
pip               20.2.3    c:\users\veit\source\photoseppy\ps\lib\site-packages pip
protobuf          5.28.3    c:\users\veit\source\photoseppy\ps\lib\site-packages pip
pyreadline3       3.5.4     c:\users\veit\source\photoseppy\ps\lib\site-packages pip
setuptools        49.2.1    c:\users\veit\source\photoseppy\ps\lib\site-packages pip
sympy             1.13.3    c:\users\veit\source\photoseppy\ps\lib\site-packages pip
typing-extensions 4.12.2    c:\users\veit\source\photoseppy\ps\lib\site-packages pip
zstandard         0.23.0    c:\users\veit\source\photoseppy\ps\lib\site-packages pip

- compile messages: 
```
(ps) PS C:\Users\veit\source\PhotosepPy> python -m nuitka .\onnxsep4.py
Nuitka-Options: Used command line options: --onefile --standalone --include-data-files=best.onnx=best.onnx .\onnxsep4.py
Nuitka: Starting Python compilation with Nuitka '2.6rc2' on Python '3.9' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: cl (cl 14.3).
Nuitka-Scons: Backend linking program with 155 files (no progress information available for this stage).
Nuitka-Scons: Compiled 155 C files using clcache with 154 cache hits and 1 cache misses.
Nuitka-Plugins:dll-files: Found 1 file DLLs from cv2 installation.
Nuitka-Plugins:dll-files: Found 2 files DLLs from onnxruntime installation.
Nuitka-Options: Included data file 'best.onnx' due to specified data file 'best.onnx=best.onnx' on command line.
Nuitka-Postprocessing: Creating single file from dist folder, this may take a while.
Nuitka-Onefile: Running bootstrap binary compilation via Scons.
Nuitka-Scons: Onefile C compiler: cl (cl 14.3).
Nuitka-Scons: Onefile linking program with 1 files (no progress information available for this stage).
Nuitka-Scons: Compiled 1 C files using clcache with 1 cache hits and 0 cache misses.
Nuitka-Onefile: Using compression for onefile payload.
Nuitka-Onefile: Keeping onefile build directory 'onnxsep4.onefile-build'.
Nuitka: Keeping build directory 'onnxsep4.build'.
Nuitka: Successfully created 'onnxsep4.exe'.
```
- Short Example that produces the issue for me:

```
# nuitka-project: --onefile
# nuitka-project: --standalone
# nuitka-project: --include-data-files=best.onnx=best.onnx

import cv2
import numpy as np
import onnxruntime
import os
import sys

def get_model_path(modelname: str) -> str:
    return os.path.join(sys._MEIPASS, modelname) if getattr(sys, 'frozen', False) else \
           os.path.join(os.path.dirname(os.path.abspath(__file__)), modelname)

def process_image(image_path: str, model_path: str):
    image = cv2.imread(image_path)
    session = onnxruntime.InferenceSession(model_path, providers=['CPUExecutionProvider'])
    
    # Preprocess image
    resized = cv2.resize(image, (640, 640))
    input_tensor = np.expand_dims(resized.transpose(2, 0, 1).astype(np.float32) / 255.0, 0)
    
    # Run inference
    outputs = session.run(None, {'images': input_tensor})
    return outputs[0]

if __name__ == "__main__":
    model_path = get_model_path('best.onnx')
    process_image('test.jpg', model_path)
    print('Processed')
```

**Comment by Sandv** [comment]
Sorry forgot to remove the best.onnx model file include line. Here is the code that causes the issue without any additional files needed.


```
# nuitka-project: --onefile
# nuitka-project: --standalone

import cv2
import numpy as np
import onnxruntime
import os
import sys

def get_model_path(modelname: str) -> str:
    return os.path.join(sys._MEIPASS, modelname) if getattr(sys, 'frozen', False) else \
           os.path.join(os.path.dirname(os.path.abspath(__file__)), modelname)

def process_image(image_path: str, model_path: str):
    image = cv2.imread(image_path)
    session = onnxruntime.InferenceSession(model_path, providers=['CPUExecutionProvider'])
    
    # Preprocess image
    resized = cv2.resize(image, (640, 640))
    input_tensor = np.expand_dims(resized.transpose(2, 0, 1).astype(np.float32) / 255.0, 0)
    
    # Run inference
    outputs = session.run(None, {'images': input_tensor})
    return outputs[0]

if __name__ == "__main__":
    model_path = get_model_path('best.onnx')
    process_image('test.jpg', model_path)
    print('Processed')
```

**Comment by kayhayen** [comment]
The failing to import ctypes would be really strange. Did you encounter it first on the stable version of Nuitka, or maybe only with the developed version?

**Comment by kayhayen** [comment]
There were issues with the argument parsing that onefile does to get the program path argument and replace it with an absolute path in the past. That quoting code was corrected, I think on 2.4 hotfixes already, and as such I don't hope the issue is related. However, given you are using CPython Official flavor, I kind of have to wonder if that's entirely true.

You ought to be unable to compile and run `tests/standalone/CtypesUsing.py` in your environment, and I would suspect, you have a special path, where the temporary directory lives, where your user directory would have to be the special one.

I recently noticed issues with the new member of compiled, `original_argv` which is however not part of this. 

Since 2.5.2 and factory right now fix corruption bugs of 2.5 release, maybe what we see there, could also be strange form of surfacing the issue. I am giving your program a quick reproducing compilation, but I sort of suspect nothing to come up, and it did not.

So either this is a special home directory name of yours, something reports, --version and other things tend to hide away, the one you gave through `executable` (which is more like a bug to be visible like that) is all so innocent, it hurts. So if you want to try factory now, or 2.5.2 once I release it, hope it that's just a symptom of those bugs fixed.

**Comment by kayhayen** [comment]
With 2.5.2 I would hope this is not happening anymore, let me know if does.

**Comment by Sandv** [comment]
Thank you very much for looking into this! It must be something with my Windows setup and as you mentioned specifically with the tempdir. When I specify a temp path with  # nuitka-project: --onefile-tempdir-spec=%HOME%\onefile it works! I will check on future releases. Thank you so much for all your work on this fantastic tool!
