### ISSUE TITLE
sys.argv[0] sends me to the /tmp folder, instead of where the executable is

### ISSUE THREAD

**Issue by ThalliumSulfate** [Nuitka/Nuitka#3218]
I currently have 2 paths in my program:

```
filePath = os.path.realpath(os.path.dirname(__file__))
appPath = os.path.join(os.path.dirname(sys.argv[0]))
```
the filePath is for datafiles compiled into the executable, appPath is for saving and accessing external data(saved character data), 

However currently they both send me to the same location /tmp/onefile

From my understanding this is not supposed to be the case, can i get some assistance?

**Comment by kayhayen** [comment]
In the template, we have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that we do not want to be left guessing. For you it's easy to erase the issue template and expect us to ask you questions only as necessary, but we cannot do that. We would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore we are  likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
