### ISSUE TITLE
Nuitka issue on mac

### ISSUE THREAD

**Issue by isovsisland** [Nuitka/Nuitka#3221]
I had written about an issue compiling with nuitka on mac and found the issue was deleted. Not sure why, since the problem was not resolved. I was going to comment that the exact same code compiles and runs fine on Windows with Nuitka. Please note that I had follwed your instructions for writting up the issue quite closely. To find the issue summarily deleted was dissapointing. Hope you find this additional information about the issue not occuring on Windows useful enough that it is reviewed further.

**Comment by KRRT7** [comment]
we find it disappointing that people don't follow the [issue template](https://github.com/Nuitka/Nuitka/blob/develop/.github/ISSUE_TEMPLATE.md).

**Comment by isovsisland** [comment]
I did follow it and Kay responded not thinking it was a problem ith nuitka. Which is why I was going to add that my script compiled and ran fine on Windows. But finding that my was deleted, was, as I said dissapointing as is your response.

**Comment by kayhayen** [comment]
@isovsisland if you have a genuine issue, take my apologies later, but I think it might be the case that i responded and then later decided to delete it as it has no value for other users.

**Comment by kayhayen** [comment]
This issue will be deleted, because I am not willing to make life harder for myself with invalid issues that contain no information worthwhile to search through.

**Comment by isovsisland** [comment]
I certainly would have provided any information if you would have asked and the expectation was not that something needed to be done now. You realize this was all based on your response from Discord to submit the issue in github. Obviously there is something wrong with nuitka or its configuration on mac since my script compiled and ran fine on Windows. But no matter, there is plenty of other software I can use.

**Comment by kayhayen** [comment]
Being asked to raise an issue on Discord is commonly mistaken as a wafer of the requirement to fill out the issue template. You didn't do that, good on you. But your program contained a simple and common user error, that I pointed out, and that @KRRT7 even thought it would have to begin with.

Anyway, I am blocking you for a while here, since you become slightly toxic, which normally I don't mind, but combined with uselessness, that's too much for me.

**Comment by kayhayen** [comment]
Seems there is no time based blocks, so it's indefinite, sorry, that harsh, I feel like 30 days should be enough, I will unblock you once I go over things, I definitely recall there was such a feature.

**Comment by kayhayen** [comment]
And just in case, anyone wonders why I do this. I have only so much time to spend. I do not want to spend it on things that do not progress Nuitka. If you make a comment designed to make me feel bad, you do damage. People frequently wonder how I can pull of making Nuitka in the first place, and part of it, is that I let go of things, that I would normally be interested in. So don't be surprised if I let go of things I am not interested in. I try to be helpful and respectful, but if you don't read my replies, and make drama out of it, that's it for me, I just don't want to spend time on those things.

It's a shame I am going to delete this statement later. I should put it somewhere.
