### ISSUE TITLE
Probable bug in argument parser

### ISSUE THREAD

**Issue by gdementen** [Nuitka/Nuitka#3223]
https://github.com/Nuitka/Nuitka/blob/82769198cb273c353faf29b3f6f0fd7673625421/nuitka/utils/CommandLineOptions.py#L45

AFAICT, the key was already popped at the previous line, so link will always be None?!

**Comment by kayhayen** [comment]
You are absolutely correct, I did only explore terminal links and apparently then made it such that it no longer works, but I also removed the `link` usage it seems. But it will be better to get that corrected, thanks that's a good catch that would have cost me time I am sure.
