### ISSUE TITLE
Nuitka '2.5.4' supports playwright, how to use it correctly

### ISSUE THREAD

**Issue by xingzheseo** [Nuitka/Nuitka#3225]
D:\python>python -m nuitka --standalone --windows-icon-from-ico=icon.ico 1000years.py
Nuitka-Options: Used command line options: --standalone --windows-icon-from-ico=icon.ico 1000years.py
Nuitka: Starting Python compilation with Nuitka '2.5.4' on Python '3.12' commercial grade 'not installed'.
FATAL: playwright: No browsers included. Use the option '--playwright-include-browser=browser_name' to include one. Use 'all' to include all installed ones.
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'.

code:
browser_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'chrome', 'chrome.exe')

I use a custom browser path. How do I write the package command? I hope you can give me some advice. Thank you.

**Comment by KRRT7** [comment]
how did you download the "custom" browser?

**Comment by xingzheseo** [comment]
Portable

**Comment by KRRT7** [comment]
you will have to be proactive here if you want support for this I'm afraid, how did you download? minimal working script etc etc.

**Comment by Kevin-O-Hsu** [comment]
#3277

**Comment by kayhayen** [comment]
This was always a very unspecific issue, but it's solved.
