### ISSUE TITLE
Lack of full Playwright support (connect_over_cdp)

### ISSUE THREAD

**Issue by europecdc** [Nuitka/Nuitka#3229]
What if I don’t want to connect a browser, but just use a CDP connection? 
The documentation is extremely explicit about the browser.

**Comment by KRRT7** [comment]
I'm fairly sure this is a playwright question, what made you open an issue here?

**Comment by europecdc** [comment]
Nah, this is not a question about Playwright itself, this is a question about the functionality of Nuitka.
When calling --include-package=playwright, I MUST specify the browser path, which is not entirely correct. As I stated above, I can also use a CDP and it doesn't require a browser, so why would I add one and add even more weight?

**Comment by KRRT7** [comment]
fair enough, I didn't know playwright could be used without having a browser installed via playwright itself, I'll add an option for a "browserless"  playwright installation.

**Comment by kayhayen** [comment]
Part of the 2.5.7 release I just made.
