### ISSUE TITLE
macOS: code signing with --macos-signed-app-name isn't working with --onefile

### ISSUE THREAD

**Issue by random-developer** [Nuitka/Nuitka#3239]
% python -m nuitka --version
2.5.4
Commercial: None
Python: 3.11.4 (v3.11.4:d2340ef257, Jun  6 2023, 19:15:51) [Clang 13.0.0 (clang-1300.0.29.30)]
Flavor: CPython Official
Executable: ~/.virtualenvs/Q/bin/python
OS: Darwin
Arch: arm64
macOSRelease: 15.2
Version C compiler: /usr/bin/clang (clang 16.0.0).

Q: How did you install Nuitka and Python?
A: Installed via pip and python.org's installer.

The problem:I'm specifying a signing identifier (--macos-signed-app-name) on the command line, but it isn't being honored on the actual executable, it's only honored on the self extracting front end.

Here is the top of my Nuitka output:
```
Nuitka-Options: Used command line options: --nofollow-import-to=bs4 --nofollow-import-to=jinja2 --nofollow-import-to=numpy --nofollow-import-to=pandas --onefile
Nuitka-Options: --onefile-tempdir-spec={HOME}/.my-cache/my-program --output-dir=build --output-filename=my-program --macos-create-app-bundle
Nuitka-Options: --macos-sign-identity=MyIdentity --macos-signed-app-name=com.me.my-program Daemons/my-program.py
```

Using `code sign -dv build/my-program` to verify, I see I have the expected `Identifier=com.me.my-program`. However, at runtime this front end just extracts the actual contents to ~/.my-cache/my-program/my-program.bin, and the identifier reported on that is merely `my-program`.

As a work-around, is there a way to point Nuitka at a dist directory and have it create the onefile extractor as a separate stage? I could modify my build process to perform the code signing separately if so.

**Comment by random-developer** [comment]
(As a side note here, I would prefer to not use `--macos-create-app-bundle` in this instance - the item being created is a command line tool (and operates as a daemon as well). However, my code needs to pull in Foundation, and Nuitka refuses to pull that in without the app-bundle flag. `FATAL: options-nanny: Error, package 'Foundation' requires '--macos-create-app-bundle' to be used or else it cannot work.`

**Comment by kayhayen** [comment]
We cannot make packages that must be run a inside bundle (Python is one) work outside of bundles. Things are a GUI like PySide6, or use macOS system APIs like Foundation, tend to do that.

The onefile combination is pretty useless and will go away once Nuitka supports creating .dmg files, and without the bundle it is useful, but many packages cannot work, and not use many OS features. I think on macOS, outside of the command line program that doesn't use very many packages like that, not a huge chance to use it. Maybe one day, we make a onefile that unpacks an `.app` folder, but you won't be allowed to run those from temp folders, so yeah, Apple is really a limiting factor I think.

**Comment by kayhayen** [comment]
The thing with `--macos-signed-app-name` is that it is using in the plist file and part of the app bundle so far only, but I now adding on the command line. Let me know if it gives the expected result.

**Comment by kayhayen** [comment]
Thanks for your report. This is fixed on the factory branch, which is a development version that is under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by random-developer** [comment]
Using factory version 2.6rc6, the results appear to be identical: the onefile is properly signed but the executable that gets extracted from it is not.

For diagnostic purposes is there some way to see the actual codesign commands that occurred during my build? I suspect there is only one happening which, if true, would be the problem: there needs to be two: one (probably including the --deep option) after the `.dist` directory is populated, and another against the onefile that gets crated from that `.dist`.

**Comment by kayhayen** [comment]
A typo rendered my change ineffective, but it should now work. There are two signatures, which I confirmed by looking at it using `--onefile-temp-spec=lala` and with `codesign -d -v` on both files. It always uses `--deep` option. Please retry.

**Comment by random-developer** [comment]
Confirmed; both binaries have the same correct signature now. Thank you!

**Comment by kayhayen** [comment]
Part of the 2.5.6 hotfix I just made.
