### ISSUE TITLE
Nuitka fails to compile pymupdf aka fitz

### ISSUE THREAD

**Issue by JustRedTTG** [Nuitka/Nuitka#3243]
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.
```
2.5.6
Commercial: None
Python: 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: F:\Nyden\PPG\moss-desktop\.venv1\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

- How did you install Nuitka and Python

Python is a venv, using `https://github.com/TheWORLD1886/Python-3.10-Portable` but the issue is present regardless of python
Issue is present on 3.9 and 3.10
Nuitka installed through pip and git also fails

- The specific PyPI names and versions
```
Nuitka             2.5.6  pip
PyMuPDF            1.25.0 pip
```

- Many times when you get an error from Nuitka, your setup may be special

`import pymupdf` is enough to trigger the error

- Also supply a Short, Self Contained, Correct, Example

Should compile without issues

- Provide in your issue the Nuitka options used

`--mode=app --report=compilation-report.xml --assume-yes-for-downloads --outpust-dir=build --script-name=test_pymupdf.py`

- Avoid unnecessary options

succeeds with just option `--script-name=test_pymupdf.py` seems to be only broken in app mode
result of running executable, prints pymupdf version correctly
```
> test_pymupdf.exe 
1.25.0
```
`--onefile` fails
`--standalone` fails

- The issue:
nuitka fails to compile `pymupdf.mupdf` **(stuck on PASS 1)**
or it takes about an hour and fails with an error log such as this from nuitka-action running on windows with python 3.9
```
Unexpected output from this command:
<clcache> /Fomodule.pymupdf.mupdf.obj /c "module.pymupdf.mupdf.c" /std:c11 /nologo /wd5105 /wd4391 /Ox /GF /Gy /EHsc /J /Gd /bigobj /MT /D__NUITKA_NO_ASSERT__ /D_NUITKA_STANDALONE /D_NUITKA_ONEFILE_MODE /D_NUITKA_ONEFILE_TEMP_BOOL /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=153 /D_NUITKA_EXE /D_NUITKA_PLUGIN_MULTIPROCESSING_ENABLED=1 /IC:\HOSTED~1\windows\Python\398E0A~1.13\x64\Lib\SITE-P~1\nuitka\build\inline_copy\zlib /IC:\HOSTED~1\windows\Python\398E0A~1.13\x64\include /I. /IC:\HOSTED~1\windows\Python\398E0A~1.13\x64\Lib\SITE-P~1\nuitka\build\include /IC:\HOSTED~1\windows\Python\398E0A~1.13\x64\Lib\SITE-P~1\nuitka\build\static_src /IC:\HOSTED~1\windows\Python\398E0A~1.13\x64\Lib\SITE-P~1\nuitka\build\inline_copy\libbacktrace
D:\a\moss-desktop-action-testing\moss-desktop-action-testing\build\moss.build\module.pymupdf.mupdf.c(1823011) : fatal error C1002: compiler is out of heap space in pass 2

scons: *** [module.pymupdf.mupdf.obj] Error 1
FATAL: Failed unexpectedly in Scons C backend compilation.
```
seems to be a recursive memory-filling error during compilation

I hope this extensive report helps to resolve the issue. If need for anything else do mention me. This issue seems to be very reproducable *at least on windows*

**Comment by kayhayen** [comment]
YYour C compile it out of memory, for now that's not considered an issue of Nuitka really, although scalability work will improve the memory needs in the future.

**Comment by JustRedTTG** [comment]
and what is your solution to this issue? Even using nuitka action I cannot build my app, not to mention it takes an hour and fails, only in `--mode=app` otherwise it builds in seconds without issue, are you sure this is a C compile out of memory issue? Perhaps something else is causing it to trigger an out of memory error

**Comment by kayhayen** [comment]
If you cared to look up with google or on the web site for typical issues, you would find all your options.

**Comment by kayhayen** [comment]
> D:\a\moss-desktop-action-testing\moss-desktop-action-testing\build\moss.build\module.pymupdf.mupdf.c(1823011) : fatal error C1002: compiler is out of heap space in pass 2

That is MSVC talking to you, not necessarily me. It seems that this file is quite big, line 1823011 seems quite heroic. It's probably generated Python code that is too big, but outside of commercial support, I won't care about this right now, as like I said, I am working on scalability generally anyway.

**Comment by JustRedTTG** [comment]
Tested on linux with similar time of an hour long on pass 1
![image](https://github.com/user-attachments/assets/bc35e8b5-80ae-4084-9f9f-763886f54b9d)
Sorry but here is an image from htop

After pass 1 it tries to compile an, I mind you file generated by nuitka

```
/* Generated code for Python module 'pymupdf$mupdf'
 * created by Nuitka version 2.5.6
```

That is over 100MB+ in size, if nuitka is generating these files, then this is an issue with nuitka, am I not mistaken?

**Comment by JustRedTTG** [comment]
I recommend maybe adding pymupdf.mupdf to the list of modules to not include `--nofollow-import-to=pymupdf.mupdf` this seems to fix the issue, weather or not it diminishes some functionality of pymupdf I am not sure, but it seems the module works for what I had used it in my code

**Comment by kayhayen** [comment]
If the input is large, the output is not going to shrink by a lot. That said I accept it's a scalability issue, but I don't trace it here.

**Comment by JustRedTTG** [comment]
I believe this is a regression of #142

**Comment by JustRedTTG** [comment]
here's a full reproduction guide:

install python 3.9 (tested in other versions and OSes too)
`pip install nuitka pymupdf`
have a `test.pdf` and a simple code as such in a file for example named `test_pymupdf.py`: 
```py
import pymupdf

pdf = pymupdf.open('test.pdf', filetype='pdf')

pdf_page = pdf[0]

pdf_page.get_pixmap().writePNG('test.png')
```

try to compile it with nuitka:
`nuitka --mode=app --script-name=test_pymupdf.py`
PASS 1 will take an absurdly long time (hour or so)
Then the compilation of the massive c file for mupdf will usually overload github action memory, on a beefy machine it might compile but probably after a few hours

**Comment by wenkenwan** [comment]
python 3.10.11 nuitka stop at pymupdf.mupdf

**Comment by JustRedTTG** [comment]
I am sharing compilation report, used clang, managed to compile mupdf after a very long while, it does work, but this is absurd

```
  <module name="pymupdf.mupdf" kind="CompiledPythonModule" usage="import fromlist" reason="Instructed by user to follow to all modules." source_path="${sys.prefix}\lib\site-packages\pymupdf\mupdf.py" distribution="PyMuPDF">
    <optimization-time pass="1" time="5328.05" micro_passes="6" max_branch_merge="1521" merged_total="487495" />
    <optimization-time pass="2" time="733.05" micro_passes="1" max_branch_merge="1521" merged_total="72811" />
```
[compilation_report.txt](https://github.com/user-attachments/files/18085352/compilation_report.txt)

**Comment by kayhayen** [comment]
I agree, I would hope that scalability improvements as outlines on the roadmap will just make those condense away though. The max branch merge is large and the total one is huge as well, but this is something that will go away. Other modules like `telethon.tl.types` and some `azure` API packages have this and I am hopeful about them, but I don't trace this here, but on roadmap only.

**Comment by chianjin** [comment]
This question has been bothering me for a while, [https://github.com/Nuitka/Nuitka/issues/3123](https://github.com/Nuitka/Nuitka/issues/3123)
In my case, the working environment is python 3.11 + pymupdf 1.22.5 + nuitka 1.8.5, any newer version will hang on PASS 1 `pymupdf.mupdf`.
Additionally, `--mingw64 --clang` options is recommended. With MSVC, the analysis and compilation is very slow.

**Comment by kayhayen** [comment]
@chianjin if you were to take the time and use git bisect to figure out the commit, that could in fact be very interesting or not, since I think loop variable analysis is probably to blame and indispensable for correctness, but maybe something else comes up

**Comment by JustRedTTG** [comment]
> I just had trouble with fitz (pymupdf) and nuitka last week when compiling at home.
> But I had just packed a standalone at job before heading home and of course work more on a project...
> 
> At work I had both nuitka and PyMuPDF since 2022, and at home a recently grabed updates.
> **Downgrading Nuitka didn't work**
>  _(also, you can really notice HOW SLOW it was after get used to newer version, good job guys)_
>  
>  Drowngraded pymupdf to 1.22.3 and it worked.
>  Reupdated nuitka and kept working
>  
>  So @JustRedTTG just **downgrade pymupdf** and be more diligent if your not paying in behalf this project
> 
While I do not pay for nuitka it is an open source project and I use it to develop other open source projects. 

My contributions is to note any issues I run into while using nuitka and this is one of them since my project requires the lastest version of pymupdf. 

I tried multiple versions and the one that worked with nuitka did not work with my project, either way I remain on the fact that this is an issue. 

But I'm in no rush since I do not pay for nuitka commercial and remain on my open source practices. 

I do donate to projects I like but I am not in the financial state to support nuitka directly as of now. Be mindful of that.

**Comment by kayhayen** [comment]
> (also, you can really notice HOW SLOW it was after get used to newer version, good job guys)

@ylaveq This style of communication is not welcome here, and @JustRedTTG don't feel like you have to justify yourself, this person has no say around here, and if this style repeats, I will make sure we don't hear of it again

**Comment by JustRedTTG** [comment]
> > (also, you can really notice HOW SLOW it was after get used to newer version, good job guys)
> 
> @ylaveq This style of communication is not welcome here, and @JustRedTTG don't feel like you have to justify yourself, this person has no say around here, and if this style repeats, I will make sure we don't hear of it again

I appreciate this understanding and I agree with you.
Keep up the great work!

**Comment by kayhayen** [comment]
Time to justify myself. Recently at PyLatAM 2024, I was able to demonstrate a 13x speedup for some loop examples. As a pre-condition, the tracing code had to get more correct, and I think it made Nuitka slower. That is not a necessity though. The scalability work I am doing right now, among other things, will make loop analysis fast again. The current exception tracing code is causing too much work to be done that ends up never used, making it a pity. The code was always weak in this regard, but gave up so soon, it was fast.

So it's my suspect, a git bisect would find commits that enhanced loop tracing as the cause for slow workings of some modules.

Luckily enough people find ways to waste my time so I didn't get to the scalability work that I mean to do, the sense of entitlement is really strong in some people. I probably should see it as a sign of success that these noisy and non-constructive people show up more often, and it is.

That said, once "Winter of Scalability" is over, there is hope that the Python compilation side of Nuitka will be faster than ever before. :)

**Comment by crazymxm** [comment]
I personally think that the problem is not due to the speed of nuitka compiling C code. The generated module.pymupdf.mupdf.c is extremely large.   Might be some problems in converting the python code to C？ The python code of pymupdf is not big.

**Comment by JustRedTTG** [comment]
> I personally think that the problem is not due to the speed of nuitka compiling C code. The generated module.pymupdf.mupdf.c is extremely large. Might be some problems in converting the python code to C？ The python code of pymupdf is not big.

Yes I agree, I noticed that too, nuitka first takes ages generating this massive C file which can fail and then it also struggles compiling it afterwards due to it's size, which causes double the slow down

**Comment by crazymxm** [comment]
In fact, pymupdf itself does not have much code, and its core function is to call the link library of mupdf. For example, the _mupdf.so file (the screenshot I took through debug is as follows), I don't know why the generated C code is so huge.

<img width="980" alt="image" src="https://github.com/user-attachments/assets/b47ec51d-c1cf-4844-9a00-1aa0eff9ddfd" />

**Comment by kayhayen** [comment]
Do `python -m nuitka --edit=pymupdf.mupdf` and you find a file of 60k lines of Python code, full of classes and functions, playing to the weaknesses of Nuitka, and generating a lot more code than necessary. I didn't find the for loop issue, but many classes is an issue by itself.

The main background is that every Python version has added more to the complexity of how classes are created. Dataclasses, generics, subclass hooks, etc. all add bloat that current ends up in C code a lot of times. Part of my roadmap is to add a mechanism that will work kind of like profile guided optimization, where we will record, that classes do not do much magic in their metaclass selection, and can have more straightforward code generated. That will be the third step on the roadmap there: https://nuitka.net/changelog/roadmap.html#scalability-standard

**Comment by dy0gu** [comment]
Sorry about "reviving" this issue, I know there are a few about PyMuPDF, but downgrading PyMuPDF to an earlier version like @ylaveq said also made it compile on my machine. So @kayhayen, I think it's okay to remove the off-topic mark. To be honest I don't understand why it's marked like that to begin with, I think maybe you misunderstood what he has saying, he was actually complimenting your work by saying he noticed how slow Nuitka **USED** to be when he tried to downgrading it to see if it was a regression on your part, and how it's noticeably much faster on newer versions.

> I just had trouble with fitz (pymupdf) and nuitka last week when compiling at home. But I had just packed a standalone at job before heading home and of course work more on a project...
> 
> At work I had both nuitka and PyMuPDF since 2022, and at home a recently grabed updates. **Downgrading Nuitka didn't work** _(also, you can really notice HOW SLOW it was after get used to newer version, good job guys)_
> 
> Drowngraded pymupdf to 1.22.3 and it worked. Reupdated nuitka and kept working
> 
> So [@JustRedTTG](https://github.com/JustRedTTG) just **downgrade pymupdf** and be more diligent if your not paying in behalf this project

**Comment by kayhayen** [comment]
@dy0gu being off-topic is not a criticism, but just means it's nothing I care to see again, if it's unrelated to the issue at hand, which to me is the scalability side of things, being above or below a treshold of working is not all that interesting to me the next time I get to work on the issue

**Comment by JustRedTTG** [comment]
I'd like to highlight again that this is only broken in **app** mode, but compiling a simple test with pymupdf without **app** mode would result in a working binary in 7 seconds, don't you think that is a little odd @kayhayen ?
