### ISSUE TITLE
Anti virus detection

### ISSUE THREAD

**Issue by thisisdali** [Nuitka/Nuitka#3245]
My files are flagged as a malware even though the code is print(a+b)

**Comment by EnemySYS** [comment]
> My files are flagged as a malware even though the code is print(a+b)

Without a digital signature it is difficult to get around. I've seen a guy who didn't detect anything, but I don't know if it was an obfuscation.

**Comment by thisisdali** [comment]
oh i tried on my friends pc and its working good
