### ISSUE TITLE
程序编译后运行程序崩溃，未编译前程序可正常执行

### ISSUE THREAD

**Issue by wjdy** [Nuitka/Nuitka#3249]
Nuitka: A segmentation fault has occurred. This is highly unusual and can
have multiple reasons. Please check https://nuitka.net/info/segfault.html
for solutions.
QBasicTimer::start: QBasicTimer can only be used with threads started with QThread

使用anaconda   python=3.12 3.10都测试过，同样会闪退，使用python3.8也会闪退，部分功能可以使用

感觉是pyqt的问题，我的源码是从pyqt5修改为pyside6的，未编译前代码可以正常运行，需要注意，这边打包只将自定义软件包打包为exe,相关依赖包并未打包

**Comment by kayhayen** [comment]
In the template, we have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that we do not want to be left guessing. For you it's easy to erase the issue template and expect us to ask you questions only as necessary, but we cannot do that. We would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore we are  likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
