### ISSUE TITLE
bin-file.bin is ignored when using "--include-data-dir=data=data/"

### ISSUE THREAD

**Issue by noeldiviney** [Nuitka/Nuitka#3255]
I am using msys64 environment on Windows 10 to develop "embedded Systems Projects"
Nuitka version is 2.5.6. as follows
$ nuitka --version
2.5.1
Commercial: None
Python: 3.12.7 (main, Nov  3 2024, 19:54:34)  [GCC 14.2.0 64 bit (AMD64)]
Flavor: MSYS2 MinGW
Executable: C:/nuitka-test/msys64/mingw64/bin/python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Nuitka-Scons: Non downloaded winlibs-gcc 'C:/nuitka-test/msys64/mingw64/bin/gcc.exe' is being
Nuitka-Scons: ignored, Nuitka is very dependent on the precise one.
Version C compiler: ~/AppData/Local/Nuitka/Nuitka/Cache/DOWNLO~1/gcc/x86_64/14.2.0posix-19.1.1-12.0.
0-msvcrt-r2/mingw64/bin/gcc.exe (gcc 14.2.0).

My file structure is as follows
/c/nuitka-test
├── data
│   ├── bin-file.bin
│   ├── hex-file.hex
│   └── text-file.txt
├── msys64
│   └── msys64-installation-goes-here
├── nuitka-hello-build-log.txt
├── nuitka-hello.build
├── nuitka-hello.dist
│   ├── data
│   │   ├── hex-file.hex
│   │   └── text-file.txt
│   ├── other files are here
└── nuitka-hello.py

My data to be included as shown above has 3 files, namely, bin-file.bin, hex-file.hex and text-file.txt.
My nuitka-hello.dist/data after the nuitka build  has only 2 files. namely, hex-file.hex, and text-file.txt .
The bin-file.bin is missing.

My nuitka build command is "nuitka --standalone --include-data-dir=data=data/ nuitka-hello.py"

See the following "nuitka-test-build-log.txt" for full details
[nuitka-hello-build-log.txt](https://github.com/user-attachments/files/18091157/nuitka-hello-build-log.txt)

See the following "nuitka-test.zip" for complete example
[nuitka-test.zip](https://github.com/user-attachments/files/18091127/nuitka-test.zip)

Help appreciated.
Noel Diviney

**Comment by kayhayen** [comment]
The documentation has a section on why code is not data, and what file types are considered code. Now arguably, not all `.bin` files are like that. If you want to avoid that, use the raw dir inclusion options instead, or specify an explicit file pattern that matches them with the data files options, although that would have to be with `*.bin` as such is not usable as well with multiple file suffixes, etc.
