### ISSUE TITLE
xgboost no_docstring

### ISSUE THREAD

**Issue by tobyclh** [Nuitka/Nuitka#3258]
Before submitting an Issue, please review the
[Issue Guidelines](https://github.com/Nuitka/Nuitka/blob/develop/CONTRIBUTING.md#submitting-an-issue).

- Please check whether the bug was already reported or fixed.
Already discussed in #2006 and #2007

- Please check whether the issue appears when you run the code with Python, if it does, it's not a
  Nuitka issue.
No

XGBoost checks for docstring with assertion, I do not agree the practice but they are not about to change [that](https://github.com/dmlc/xgboost/issues/8537).

Currently Nuitka handles this by [replacing the line when nodocstring and no assertion are BOTH specified](https://github.com/Nuitka/Nuitka/blob/91679a4d336690a56aab39fbc4810d3643b634be/nuitka/plugins/standard/standard.nuitka-package.config.yml#L8644 ), however, I would like to keep my asserts while removing docstrings.  

It doesn't seem very intuitive to me that you are required to turn off assertion since turning off assertion should resolve the issue without any replacement anyway, I propose that we only require no docstrings

**Comment by kayhayen** [comment]
We can improve this now, doc strings and assertions are now per module/package yaml configuration, but we don't use that feature yet. With that, we could enforce per module the use or non-use of docstrings or assertions. Anti-bloat has settings `annotations`, `doc_strings` and `assertions`.

I haven't yet taken the time to do this, but it's part of the plan to attack some of the slower to compile modules, where we can get away with it, to remove all of them.

As for the configuration you pointed out, it surely can be replaced with one, which just disables assertions generally, or maybe the specific one, if it's needed.

Also you may be totally correct about it. Can you try and create a PR that uses those features. I am not sure I documented them, but basically they take `yes/no/default` where the later is the global Python flag value and could be used to solve this.

**Comment by kayhayen** [comment]
If you are available to do a PR, this can be fixed by adding to the yaml configuration, described here: [https://nuitka.net/doc/nuitka-package-config.html](https://nuitka.net/doc/nuitka-package-config.html)

And here is more of a walk through style post: [https://nuitka.net/posts/nuitka-package-config-kickoff.html](https://nuitka.net/posts/nuitka-package-config-kickoff.html)

Here are a example PRs for other packages:

[#2030](https://github.com/Nuitka/Nuitka/pull/2030) 
[#1993](https://github.com/Nuitka/Nuitka/pull/1993)
