### ISSUE TITLE
Nuitka Optomization Error -Duplicate locals name

### ISSUE THREAD

**Issue by BassamMimoto** [Nuitka/Nuitka#3265]
**Platform Info**
Nuitka Version: 2.4.5 Commercial 
Python Version: 3.10.16
OS: MacOS Core i5. Version 14.4.1

Nuitka Crash Report is Attached.

----------------------------------------------
**Command Used and Output**
Nuitka-Options: Used command line options: --standalone --company-name=MY_COMPANY --product-name=MY_APP --file-version=0.0.1 --product-version=0.0.1 --noinclude-unittest-mode=nofollow --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow --include-module=sklearn.ensemble --include-package=xgboost --include-package=xgboost.core --include-package=xgboost.sklearn --include-package=skops --include-package=skops.io --include-package-data=company_macos --macos-create-app-bundle --macos-signed-app-name=ai.MY.APP..LaunchAgent --macos-sign-identity=XXXXXXXX --macos-sign-notarization --macos-app-mode=ui-element --macos-app-version=0.0.1 --main=my-app.py --main=my-app-dialog.py --static-libpython=no --clang
Nuitka:WARNING: For application bundles, you ought to specify an icon with '--macos-app-icon'.", otherwise a dock icon may not be present.

Nuitka: Starting Python compilation with Nuitka '2.4.5' on Python '3.10' commercial grade '2.6.2'.

Traceback (most recent call last):
  File "/Users/admintest/app/Nuitka-commercial/nuitka/__main__.py", line 206, in <module>
	main()
  File "/Users/admintest/app/Nuitka-commercial/nuitka/__main__.py", line 188, in main
	MainControl.main()
  File "/Users/admintest/Nuitka-commercial/nuitka/MainControl.py", line 1155, in main
	_main()
  File "/Users/admintest/app/Nuitka-commercial/nuitka/MainControl.py", line 995, in _main
	main_module = _createMainModule()
  File "/Users/admintest/app/Nuitka-commercial/nuitka/MainControl.py", line 256, in _createMainModule
	optimizeModules(main_module.getOutputFilename())
  File "/Users/admintest/app/Nuitka-commercial/nuitka/optimizations/Optimization.py", line 332, in optimizeModules
	finished = makeOptimizationPass()
  File "/Users/admintest/app/Nuitka-commercial/nuitka/optimizations/Optimization.py", line 288, in makeOptimizationPass
	changed, micro_passes = optimizeModule(current_module)
  File "/Users/admintest/app/Nuitka-commercial/nuitka/optimizations/Optimization.py", line 166, in optimizeModule
	return optimizeCompiledPythonModule(module)
  File "/Users/admintest/app/Nuitka-commercial/nuitka/optimizations/Optimization.py", line 126, in optimizeCompiledPythonModule
	considerUsedModules(module=module, pass_count=pass_count)
  File "/Users/admintest/app/Nuitka-commercial/nuitka/importing/Recursion.py", line 521, in considerUsedModules
	new_module = recurseTo(
  File "/Users/admintest/app/Nuitka-commercial/nuitka/importing/Recursion.py", line 80, in recurseTo
	module = _recurseTo(
  File "/Users/admintest/app/Nuitka-commercial/nuitka/importing/Recursion.py", line 38, in _recurseTo
	module = Building.buildModule(
  File "/Users/admintest/app/Nuitka-commercial/nuitka/tree/Building.py", line 1434, in buildModule
	module = _createModule(
  File "/Users/admintest/app/Nuitka-commercial/nuitka/tree/Building.py", line 1134, in _createModule
	result = CompiledPythonPackage(
  File "/Users/admintest/app/Nuitka-commercial/nuitka/nodes/ModuleNodes.py", line 712, in __init__
	CompiledPythonModule.__init__(
  File "/Users/admintest/app/Nuitka-commercial/nuitka/nodes/ModuleNodes.py", line 294, in __init__
	self.locals_scope = getLocalsDictHandle(
  File "/Users/admintest/app/Nuitka-commercial/nuitka/nodes/LocalsScopes.py", line 41, in getLocalsDictHandle
	raise NuitkaOptimizationError(
nuitka.Errors.NuitkaOptimizationError:
duplicate locals name
globals_xgboost$dask
module_dict
xgboost.dask
/Users/admintest/miniconda3/envs/venv/lib/python3.10/site-packages/xgboost/dask/__init__.py
xgboost.dask
/Users/admintest/miniconda3/envs/venv/lib/python3.10/site-packages/xgboost/dask.py

The above information should be included in a bug report.
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug repor

----------------------------------------------
**Other Details**

- I am using PIP to install dependencies within Conda environment.
- Python installed via "pyenv" version 3.10.16
- Nuitka, is used as a git rep. Checkout via the 2.4.5 tag

----------------------------------------------
**Python App Dependency List**

# Name                	
[nuitka-crash-report.txt](https://github.com/user-attachments/files/18161782/nuitka-crash-report.txt)
Version               	Build  Channel
_py-xgboost-mutex     	2.0                   	cpu_0	conda-forge
aiofiles              	22.1.0               	pypi_0	pypi
annotated-types       	0.7.0                	pypi_0	pypi
argparse              	1.4.0                	pypi_0	pypi
build                 	1.2.2.post1          	pypi_0	pypi
bzip2                 	1.0.8            	h6c40b1e_6  
ca-certificates       	2024.12.14       	h8857fd0_0	conda-forge
cffi                  	1.17.0               	pypi_0	pypi
chardet               	3.0.4                	pypi_0	pypi
cython                	0.29.37              	pypi_0	pypi
deprecation           	2.1.0                	pypi_0	pypi
filelock              	3.16.1               	pypi_0	pypi
fsspec                	2024.10.0            	pypi_0	pypi
huggingface-hub       	0.27.0               	pypi_0	pypi
idna                  	2.8                  	pypi_0	pypi
invoke                	2.2.0                	pypi_0	pypi
joblib                	1.4.2          	pyhd8ed1ab_1	conda-forge
json-five             	1.1.2                	pypi_0	pypi
libblas               	3.9.0       	25_osx64_openblas	conda-forge
libcblas              	3.9.0       	25_osx64_openblas	conda-forge
libcxx                	19.1.5           	hf95d169_0	conda-forge
libffi                	3.4.4            	hecd8cb5_1  
libgfortran           	5.0.0       	13_2_0_h97931a8_3	conda-forge
libgfortran5          	13.2.0           	h2873a65_3	conda-forge
liblapack             	3.9.0       	25_osx64_openblas	conda-forge
libopenblas           	0.3.28      	openmp_hbf64a52_1	conda-forge
libxgboost            	2.1.3        	cpu_h63c3a07_0	conda-forge
llvm-openmp           	19.1.5           	ha54dae1_0	conda-forge
llvmlite              	0.40.1               	pypi_0	pypi
markdown              	3.7                  	pypi_0	pypi
mimoto-agent          	0.1.0                	pypi_0	pypi
ncurses               	6.4              	hcec6c5f_0  
nuitka                	2.4.5                	pypi_0	pypi
numba                 	0.57.1               	pypi_0	pypi
numpy                 	1.24.3               	pypi_0	pypi
openssl               	3.4.0            	hd471939_0	conda-forge
ordered-set           	4.1.0                	pypi_0	pypi
packaging             	24.2                 	pypi_0	pypi
pip                   	24.3.1               	pypi_0	pypi
psutil                	5.9.8                	pypi_0	pypi
py-xgboost            	2.1.3       	cpu_pyhd3de297_0	conda-forge
pycparser             	2.22                 	pypi_0	pypi
pycryptodomex         	3.21.0               	pypi_0	pypi
pydantic              	2.10.3               	pypi_0	pypi
pydantic-core         	2.27.1               	pypi_0	pypi
pynput                	1.7.7                	pypi_0	pypi
pyobjc-core           	10.3.2               	pypi_0	pypi
pyobjc-framework-applicationservices 10.3.2               	pypi_0	pypi
pyobjc-framework-cocoa	10.3.2               	pypi_0	pypi
pyobjc-framework-coretext 10.3.2               	pypi_0	pypi
pyobjc-framework-quartz   10.3.2               	pypi_0	pypi
pyobjc-framework-webkit   10.3.2               	pypi_0	pypi
pyproject-hooks       	1.2.0                	pypi_0	pypi
python                	3.10.16          	hce00570_1  
python_abi            	3.10                	2_cp310	conda-forge
pytz                  	2022.7.1             	pypi_0	pypi
pyzipper              	0.3.6                	pypi_0	pypi
readline              	8.2              	hca72f7f_0  
regex                 	2024.11.6            	pypi_0	pypi
requests              	2.22.0               	pypi_0	pypi
scikit-learn          	1.2.2                	pypi_0	pypi
scipy                 	1.14.1      	py310hefd78d6_2	conda-forge
setuptools            	69.0.2               	pypi_0	pypi
skops                 	0.10.0               	pypi_0	pypi
sly                   	0.5                  	pypi_0	pypi
sqlite                	3.45.3           	h6c40b1e_0  
stats-model           	0.4.0                	pypi_0	pypi
tabulate              	0.9.0                	pypi_0	pypi
threadpoolctl         	3.5.0          	pyhc1e730c_0	conda-forge
tk                    	8.6.14           	h4d00af3_0  
toml                  	0.10.2               	pypi_0	pypi
tomli                 	2.2.1                	pypi_0	pypi
tqdm                  	4.67.1               	pypi_0	pypi
tzdata                	2024b            	h04d1e81_0  
tzlocal               	5.0.1                	pypi_0	pypi
urllib3               	1.25.11              	pypi_0	pypi
wheel                 	0.40.0               	pypi_0	pypi
xgboost               	1.7.6                	pypi_0	pypi
xz                    	5.4.6            	h6c40b1e_1  
zlib                  	1.2.13           	h4b97444_1  
zstandard             	0.23.0               	pypi_0	pypi

**Comment by kayhayen** [comment]
Can you try with the current main version, just to be sure, I think 2.5.6 might be better.

Anyway, this should not normally happen:

```
xgboost.dask
/Users/admintest/miniconda3/envs/venv/lib/python3.10/site-packages/xgboost/dask/init.py
xgboost.dask
/Users/admintest/miniconda3/envs/venv/lib/python3.10/site-packages/xgboost/dask.py
```

If these files both exist, only one ought to be picked up. The use of `--include-package=xgboost` probably triggers this, and one of the files will not be used by the importing system, which I don't know right now, but I will try and check that out.

**Comment by kayhayen** [comment]
If at all possible, feel free to do away with all `--include-package` and throw the errors at me in the form of reports here or via email as a commercial user. I would need a reproducer of some sorts, I will try and get something out of your report though.

**Comment by kayhayen** [comment]
Part of the 2.5.7 release I just made.

**Comment by BassamMimoto** [comment]
Great! Thank you for the quick response. I will try your suggestions and
part of it I will try to move to the latest Nuitka version.
Will let you know if the issue persisted.

**Comment by BassamMimoto** [comment]
Is it possible to grant me access to the commercial repo? At this time,
David Charboneau is the only one that has such access.

Thank you,
Bassam

**Comment by kayhayen** [comment]
For issues regarding your subscription, get in touch with me privately.

**Comment by arnodunstatter** [comment]
> If at all possible, feel free to do away with all `--include-package` and throw the errors at me in the form of reports here or via email as a commercial user. I would need a reproducer of some sorts, I will try and get something out of your report though.

Hmm, so I was getting a similar error as [alsanie360](https://github.com/alsanie360) when using `python -m nuitka --module temp_dir_containg_distributable_version_of_my_package\my_package --include-package=my_package` but, as per your quoted advice, i removed the last option and ran `python -m nuitka --module temp_dir_containg_distributable_version_of_my_package\my_package` and that seemed to work just fine, which I find confusing since  your [documentation on package-compilation](python -m nuitka --module temp_dir_containg_distributable_version_of_my_package\my_package) explicitly tells us to use the `--include-package=<package_name>` option. That said, from the beginning I found the seemingly redundant specification of `my_package` confusing, and the output from `python -m nuitka --help` in regards to the `--include_package` and `--module` options did not help clarify my confusion.

I really appreciate your package, but I believe your documentation deserves an overhaul.

**Comment by kayhayen** [comment]
@arnodunstatter There is now a --mode=package which just does the right thing, crashes with the command you gave are probably issues still though and should be reported separately. Posting below closed issues is a sure fire way to get ignored.
