### ISSUE TITLE
When I build a program that imports sqlfluff, I get a runtime error.

### ISSUE THREAD

**Issue by natsuki0011** [Nuitka/Nuitka#3266]
I'm trying to create a tool that checks SQL grammar, and although I get the expected results in the Python script, I get a runtime error when I build it.

I think there may be something missing or incorrect in the options I specify when building, so I'd appreciate some advice.
I'm not good at English, so I'm using machine translation. I apologize for my poor English.

The source code, current output results, and information about my development environment are as follows. Please let me know if there is any additional information I should provide.

--SourceCode(SQLcheckTest.py)
'''
Created on 2024/12/17

@author: User01
'''
import sqlfluff

chkstr = "select * from tbl where col1 = 'foo';"
ret = sqlfluff.lint(chkstr, dialect="postgres")
print(ret)

#Run as script
#[{'start_line_no': 1, 'start_line_pos': 1, 'code': 'AM04', 'description': 'Query produces an unknown number of result columns.', 'name': 'ambiguous.column_count', 'warning': False, 'fixes': [], 'start_file_pos': 0, 'end_line_no': 1, 'end_line_pos': 37, 'end_file_pos': 36}, {'start_line_no': 1, 'start_line_pos': 37, 'code': 'LT12', 'description': 'Files must end with a single trailing newline.', 'name': 'layout.end_of_file', 'warning': False, 'fixes': [{'type': 'create_after', 'edit': '\n', 'start_line_no': 1, 'start_line_pos': 38, 'start_file_pos': 37, 'end_line_no': 1, 'end_line_pos': 38, 'end_file_pos': 37}], 'start_file_pos': 36, 'end_line_no': 1, 'end_line_pos': 38, 'end_file_pos': 37}]

--Result
Traceback (most recent call last):
  File "C:\pleiades\2022-12\WORKSP~1\Test\SQLCHE~1.DIS\SQLcheckTest.py", line 9, in <module>
  File "C:\pleiades\2022-12\WORKSP~1\Test\SQLCHE~1.DIS\sqlfluff\api\simple.py", line 87, in lint
  File "C:\pleiades\2022-12\WORKSP~1\Test\SQLCHE~1.DIS\sqlfluff\api\simple.py", line 40, in get_simple_config
  File "C:\pleiades\2022-12\WORKSP~1\Test\SQLCHE~1.DIS\sqlfluff\core\config.py", line 878, in from_root
  File "C:\pleiades\2022-12\WORKSP~1\Test\SQLCHE~1.DIS\sqlfluff\core\config.py", line 801, in __init__
KeyError: 'templater'

--Build command
`nuitka --standalone --follow-imports --mingw64 --include-package-data=sqlfluff SQLcheckTest.py`

--Environment information
>python -m nuitka --version
2.3.2
Commercial: None
Python: 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Program Files\Python312\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0).

>python -m pip list -v
DEPRECATION: Loading egg at c:\program files\python312\lib\site-packages\nuitka-2.2.1-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\program files\python312\lib\site-packages\pyperclip-1.8.2-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
Package                   Version     Location                                                                 Installer
------------------------- ----------- ------------------------------------------------------------------------ ---------
altgraph                  0.17.4      C:\Program Files\Python312\Lib\site-packages                             pip
appdirs                   1.4.4       C:\Users\User01\AppData\Roaming\Python\Python312\site-packages          pip
asgiref                   3.8.1       C:\Users\User01\AppData\Roaming\Python\Python312\site-packages          pip
attrs                     23.2.0      C:\Program Files\Python312\Lib\site-packages                             pip
bcrypt                    4.1.3       C:\Program Files\Python312\Lib\site-packages                             pip
beautifulsoup4            4.12.3      C:\Program Files\Python312\Lib\site-packages                             pip
blinker                   1.8.2       C:\Program Files\Python312\Lib\site-packages                             pip
certifi                   2024.2.2    C:\Program Files\Python312\Lib\site-packages                             pip
cffi                      1.16.0      C:\Program Files\Python312\Lib\site-packages                             pip
chardet                   5.2.0       C:\Users\User01\AppData\Roaming\Python\Python312\site-packages          pip
charset-normalizer        3.3.2       C:\Program Files\Python312\Lib\site-packages                             pip
click                     8.1.7       C:\Program Files\Python312\Lib\site-packages                             pip
colorama                  0.4.6       C:\Program Files\Python312\Lib\site-packages                             pip
cryptography              42.0.7      C:\Program Files\Python312\Lib\site-packages                             pip
customtkinter             5.2.2       C:\Program Files\Python312\Lib\site-packages                             pip
darkdetect                0.8.0       C:\Program Files\Python312\Lib\site-packages                             pip
diff_cover                9.0.0       C:\Users\User01\AppData\Roaming\Python\Python312\site-packages          pip
Django                    5.1.1       C:\Users\User01\AppData\Roaming\Python\Python312\site-packages          pip
et-xmlfile                1.1.0       C:\Program Files\Python312\Lib\site-packages                             pip
Flask                     3.0.3       C:\Program Files\Python312\Lib\site-packages                             pip
h11                       0.14.0      C:\Program Files\Python312\Lib\site-packages                             pip
idna                      3.7         C:\Program Files\Python312\Lib\site-packages                             pip
iniconfig                 2.0.0       C:\Users\User01\AppData\Roaming\Python\Python312\site-packages          pip
itsdangerous              2.2.0       C:\Program Files\Python312\Lib\site-packages                             pip
Jinja2                    3.1.4       C:\Program Files\Python312\Lib\site-packages                             pip
MarkupSafe                2.1.5       C:\Program Files\Python312\Lib\site-packages                             pip
msoffcrypto-tool          5.4.0       C:\Program Files\Python312\Lib\site-packages                             pip
Nuitka                    2.3.2       C:\Users\User01\AppData\Roaming\Python\Python312\site-packages          pip
Nuitka                    2.2.1       c:\program files\python312\lib\site-packages\nuitka-2.2.1-py3.12.egg
numpy                     1.26.4      C:\Users\User01\AppData\Roaming\Python\Python312\site-packages          pip
olefile                   0.47        C:\Program Files\Python312\Lib\site-packages                             pip
openpyxl                  3.1.2       C:\Program Files\Python312\Lib\site-packages                             pip
ordered-set               4.1.0       C:\Program Files\Python312\Lib\site-packages                             pip
outcome                   1.3.0.post0 C:\Program Files\Python312\Lib\site-packages                             pip
packaging                 24.0        C:\Program Files\Python312\Lib\site-packages                             pip
pandas                    2.2.2       C:\Users\User01\AppData\Roaming\Python\Python312\site-packages          pip
paramiko                  3.4.0       C:\Program Files\Python312\Lib\site-packages                             pip
pathspec                  0.12.1      C:\Users\User01\AppData\Roaming\Python\Python312\site-packages          pip
pefile                    2023.2.7    C:\Program Files\Python312\Lib\site-packages                             pip
pillow                    10.3.0      C:\Program Files\Python312\Lib\site-packages                             pip
pip                       24.0        C:\Program Files\Python312\Lib\site-packages                             pip
pipdeptree                2.20.0      C:\Program Files\Python312\Lib\site-packages                             pip
pluggy                    1.5.0       C:\Users\User01\AppData\Roaming\Python\Python312\site-packages          pip
psutil                    5.9.8       C:\Program Files\Python312\Lib\site-packages                             pip
psycopg2-binary           2.9.9       C:\Program Files\Python312\Lib\site-packages                             pip
pycparser                 2.22        C:\Program Files\Python312\Lib\site-packages                             pip
pycryptodome              3.20.0      C:\Program Files\Python312\Lib\site-packages                             pip
Pygments                  2.18.0      C:\Users\User01\AppData\Roaming\Python\Python312\site-packages          pip
pyinstaller               6.6.0       C:\Program Files\Python312\Lib\site-packages                             pip
pyinstaller-hooks-contrib 2024.6      C:\Program Files\Python312\Lib\site-packages                             pip
PyNaCl                    1.5.0       C:\Program Files\Python312\Lib\site-packages                             pip
pyperclip                 1.8.2       c:\program files\python312\lib\site-packages\pyperclip-1.8.2-py3.12.egg
pyperclip                 1.8.2       C:\Program Files\Python312\Lib\site-packages\pyperclip-1.8.2-py3.12.egg/
pyperclip                 1.8.2       c:\program files\python312\lib\site-packages\pyperclip-1.8.2-py3.12.egg
PySocks                   1.7.1       C:\Program Files\Python312\Lib\site-packages                             pip
pytest                    8.2.2       C:\Users\User01\AppData\Roaming\Python\Python312\site-packages          pip
python-dateutil           2.9.0.post0 C:\Users\User01\AppData\Roaming\Python\Python312\site-packages          pip
pytz                      2024.1      C:\Users\User01\AppData\Roaming\Python\Python312\site-packages          pip
pywin32-ctypes            0.2.2       C:\Program Files\Python312\Lib\site-packages                             pip
PyYAML                    6.0.1       C:\Users\User01\AppData\Roaming\Python\Python312\site-packages          pip
regex                     2024.5.15   C:\Users\User01\AppData\Roaming\Python\Python312\site-packages          pip
requests                  2.31.0      C:\Program Files\Python312\Lib\site-packages                             pip
selenium                  4.20.0      C:\Program Files\Python312\Lib\site-packages                             pip
setuptools                69.5.1      C:\Program Files\Python312\Lib\site-packages                             pip
six                       1.16.0      C:\Users\User01\AppData\Roaming\Python\Python312\site-packages          pip
sniffio                   1.3.1       C:\Program Files\Python312\Lib\site-packages                             pip
sortedcontainers          2.4.0       C:\Program Files\Python312\Lib\site-packages                             pip
soupsieve                 2.5         C:\Program Files\Python312\Lib\site-packages                             pip
sqlfluff                  3.0.7       C:\Users\User01\AppData\Roaming\Python\Python312\site-packages          pip
sqlparse                  0.5.1       C:\Users\User01\AppData\Roaming\Python\Python312\site-packages          pip
tblib                     3.0.0       C:\Users\User01\AppData\Roaming\Python\Python312\site-packages          pip
tkinterdnd2               0.3.0       C:\Program Files\Python312\Lib\site-packages                             pip
tqdm                      4.66.4      C:\Users\User01\AppData\Roaming\Python\Python312\site-packages          pip
trio                      0.25.0      C:\Program Files\Python312\Lib\site-packages                             pip
trio-websocket            0.11.1      C:\Program Files\Python312\Lib\site-packages                             pip
typing_extensions         4.11.0      C:\Program Files\Python312\Lib\site-packages                             pip
tzdata                    2024.1      C:\Users\User01\AppData\Roaming\Python\Python312\site-packages          pip
urllib3                   2.2.1       C:\Program Files\Python312\Lib\site-packages                             pip
waitress                  3.0.0       C:\Program Files\Python312\Lib\site-packages                             pip
Werkzeug                  3.0.3       C:\Program Files\Python312\Lib\site-packages                             pip
wsproto                   1.2.0       C:\Program Files\Python312\Lib\site-packages                             pip
zstandard                 0.22.0      C:\Program Files\Python312\Lib\site-packages                             pip

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

**Comment by kayhayen** [comment]
Please use the latest stable release.

**Comment by kayhayen** [comment]
I managed to reproduce the issue with latest stable release. We got `sqlfluff` package configuration in Nuitka, however for some reason, the plugins seem to no longer load and give None values.

**Comment by kayhayen** [comment]
Ah, seems `--include-distribution-metadata=sqlfluff` will be needed, adding that to our package configuration, so it works out of the box again.

**Comment by kayhayen** [comment]
Thanks for your report. This is fixed on the factory branch, which is a development version that is under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment]
Your example is very usable, hence I added it to Nuitka-Watch allowing us to detect this kind of package support regression in the future.

**Comment by natsuki0011** [comment]
Thank you for the advice on the build command.
Thanks to you, I was able to confirm that it works after building.
I will use this option to build from now on.
I'm also interested in the factory branch, so I'll try it out when I have time. I'll only use it to verify operation.

**Comment by kayhayen** [comment]
We keep issues opened until they reach the main version. Also consider "Please do not share plans to do it; only confirm or deny that it is working." the way it's meant.

**Comment by kayhayen** [comment]
Part of the current 2.5.8 hotfix release.
