### ISSUE TITLE
exe built on computer A can't run on computer B due to compatibility issue

### ISSUE THREAD

**Issue by CheroAislinn** [Nuitka/Nuitka#3275]
So the symptom is simple, I compile an exe on computer A and run it on computer B, it would pop up a window saying:

> Unsupported 16-Bit Application
> The program or feature {exe name} cannot start or run due to in compatibility with 64-bit versions of windows.

I tried to compile it on computer B and run on A, still the same. I can confirm both computers are 64-Bit os and x64 processor.

**Comment by Kevin-O-Hsu** [comment]
Can you give us some true examples and details? It's not the way you pull a issue.

**Comment by Choonholic** [comment]
My apps built by nuitka are being downloaded and used by several hundred users daily, yet I have never received a report of this issue before. To investigate the problem, please provide at least the minimum information requested in the issue template, along with a minimal reproducer.

**Comment by kayhayen** [comment]
In the template, we have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that we do not want to be left guessing. For you it's easy to erase the issue template and expect us to ask you questions only as necessary, but we cannot do that. We would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore we are  likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
