### ISSUE TITLE
Python36 and issues for Nuitka-0.6.3

### ISSUE THREAD

**Issue by ManPython** [Nuitka/Nuitka#342]
I made many multiple tests and want provide some issues for Nuitka-0.6.3 with Python36
Hope that can help to improve nuitka.
The python code is just print("Hello!")

1.
python -m nuitka --follow-imports main.pyw

> gcc: fatal error: -fuse-linker-plugin, but liblto_plugin-0.dll not found
> compilation terminated.
> scons: *** [main.exe] Error 1

2. 
python -m nuitka --mingw --recurse-all
--output-dir=build\--mingw--recurse-all main.pyw

> cc1.exe: out of memory allocating 33558527 bytes
> scons: *** [build\--mingw--recurse-all\main.build\CompiledCodeHelpers.o] Error 1

3. 
python -m nuitka --mingw --follow-impor
ts --show-progress --output-dir=build\--mingw--follow-imports main.pyw

> Nuitka:INFO:PASS 1:
> Nuitka:INFO:Initial optimization pass.
> Nuitka:INFO:Optimizing module '__main__', 0 more modules to go after that.
> Nuitka:INFO:Doing module local optimizations for '__main__'.
> Nuitka:INFO:Next global optimization pass.
> Nuitka:INFO:Optimizing module '__main__', 0 more modules to go after that.
> Nuitka:INFO:Doing module local optimizations for '__main__'.
> Nuitka:INFO:PASS 2 ... :
> Nuitka:INFO:Next global optimization pass.
> Nuitka:INFO:Optimizing module '__main__', 0 more modules to go after that.
> Nuitka:INFO:Doing module local optimizations for '__main__'.
> Nuitka:INFO:Total memory usage before running scons: 22.39 MB (23482368 bytes):
> 
> cc1.exe: out of memory allocating 33558527 bytes
> scons: *** [build\--mingw--follow-imports\main.build\MainProgram.o] Error 1

4. python -m nuitka --mingw64 --standalone
 --output-dir=build\--mingw64--standalone main.pyw

> cc1.exe: out of memory allocating 150304 bytes
> mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw6
> 4/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/as.
> exe: out of memory allocating 4064 bytes
> scons: *** [build\--mingw64--standalone\main.build\CompiledCodeHelpers.o] Error

5. 
python -m nuitka --mingw64 --standalone

>  --output-dir=build\--mingw64--standalone main.pyw
> scons: *** [build\--mingw64--standalone\main.build\module.__main__.c] ValueError
>  : unsupported pickle protocol: 4

6.
python -m nuitka --mingw --standalone -
-experimental=use_pefile --output-dir=build\--mingw--standalone--experimental ma
in.pyw

> Exception in thread Thread-4:
> Traceback (most recent call last):
>   File "E:\Python36\lib\threading.py", line 91
> 6, in _bootstrap_inner
>     self.run()
>   File "E:\Python36\lib\threading.py", line 86
> 4, in run
>     self._target(*self._args, **self._kwargs)
>   File "E:\Python36\lib\subprocess.py", line 1
> 083, in _readerthread
>     buffer.append(fh.read())
> MemoryError

7. 
--mingw64--standalone
**- are file .pyd no .dll's like in --mingw--standalone and no .exe**

8. 
--mingw--standalone 
**- there is .exe but must be python36.dll near to .exe**
- not sure.. this is normal? In Python34 not need python34.dll

files that are next to:
    gpsvc.dll
    main.exe
    msvcrt.dll
    nlaapi.dll
    pyexpat.pyd
    python36.dll
    select.pyd
    sensapi.dll
    sqlite3.dll
    sysntfy.dll
    tcl86t.dll
    tk86t.dll
    ucrtbase.dll
    unicodedata.pyd
    vcruntime140.dll
    wer.dll
    werui.dll
    _asyncio.pyd
    _bz2.pyd
    _ctypes.pyd
    _decimal.pyd
    _elementtree.pyd
    _hashlib.pyd
    _lzma.pyd
    _msi.pyd
    _multiprocessing.pyd
    _overlapped.pyd
    _socket.pyd
    _sqlite3.pyd
    _ssl.pyd
    _tkinter.pyd

**Comment by kayhayen** [comment]
That pickle protocol error is actually a real bug, that I have encountered. Scons seems to use a pickle protocol for its cache database in one Python and then the other Python doesn't understand it, and crashes. My attempts at making the filename include the Python major version of scons used have failed so far.

**Comment by kayhayen** [comment]
As for the `Python.DLL`, there is a detection of uninstalled Python and that DLL is only copied alongside the created binary, of course if it doesn't error out before, and if that Python DLL doesn't live in the Windows system directory. So not copying it in acceleration mode can be normal.

**Comment by kayhayen** [comment]
I find this highly suspicious: `gcc: fatal error: -fuse-linker-plugin, but liblto_plugin-0.dll not found` and it makes me doubt your MinGW64 configuration very much.

**Comment by ManPython** [comment]
> 
> 
> As for the `Python.DLL`, there is a detection of uninstalled Python and that DLL is only copied alongside the created binary, of course if it doesn't error out before, and if that Python DLL doesn't live in the Windows system directory. So not copying it in acceleration mode can be normal.
To be clear here. 
Can we ommit `Python36.DLL` or `Python34.DLL` next to .exe  or in `c:\windows\system32\PYTHON34.DLL` ? 
- I trying never to install my pythons after OS re-instalations, etc. just have some "updates" to vars, pathes, etc. but some other apps copying pythons .dll ..so I was not conscious about use these .dll in exe form this source as `c:\windows\system32\PYTHON34.DLL`. Just now discovered by dependecywalker (btw - nuitka want download it in first run but not working by the not actual links probably)
I mind that we can use some --options where are include these .dll's?
https://stackoverflow.com/questions/189549/embedding-dlls-in-a-compiled-executable
You know.. many ppls thinking `standalone` like in old way `py2exe` where was just .exe

**Comment by kayhayen** [comment]
I am assuming same as #343 here. The good thing is it finally convinced me to dive into making sure that compiler and Python arch match, so doubts will be less.
