### ISSUE TITLE
Compiled executable requires escalation until file rename

### ISSUE THREAD

**Issue by nseidle** [Nuitka/Nuitka#346]
*  Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

0.6.2
Python: 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)]
Executable: C:\Users\nathan.seidle\AppData\Local\Programs\Python\Python37-32\python.exe
OS: Windows
Arch: x86

*  How did you install Nuitka and Python

Python - Windows MSI
Nuitka - Installed via pip

First, thanks for creating and supporting Nuitka. It is a very helpful tool for many people!

My issue is really just a head scratcher: After compiling a UART based python script the script fails to run without escalation / elevation to administrator access. I started reducing my script to see what caused the elevation requirement. To my surprise, my test.py/exe temporary file no longer needed elevation. The content is identical. The only difference, I believe, is the copy/paste caused the file permissions to change from the original file (although I do not see any difference via Windows file properties). 

Is there a way to tell what scripts will trigger elevation before compilation? How do the exectuables that Nuitka produces inherit the permissions from the source files?

**Comment by kayhayen** [comment]
They do not inherit permissions. That itself would require elevation of privileges, would it not?

Nuitka doesn't deal with elevation of privileges on Windows. You may have accepted `python.exe` to do stuff, or its DLL, and the compiled binaries can inherit those. Nuitka does `shutil.copyfile` them, but I doubt that preserves that kind of things.

**Comment by nseidle** [comment]
Got it. Thank you!
