### ISSUE TITLE
error after compiling .spec

### ISSUE THREAD

**Issue by nickrh75** [Nuitka/Nuitka#347]
Hi, there, not sure whether I should ask this here, but with pyinstaller I can generate an executable by compiling a .spec file which references a .py file, whereas when I try to do the same with nuitka the .exe generated inside a .spec.dist folder fails to run, and an error related to the .spec file is shown. Is this normal, in the sense that nuitka works only with .py files?

> 0.6.3
> Python: 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:30:55) [MSC v.1500 32 bit (Intel)]
> Executable: C:\Python27\python.exe
> OS: Windows
> Arch: x86

**Comment by kayhayen** [comment]
I have no idea what a spec file is supposed to be. A minimal example is really needed.

**Comment by JorjMcKie** [comment]
Based on my PyInstaller experience, I know what @nickrh75 is referring to. The answer is:

A ``.spec`` file is something specific to PyInstaller. They have invented this text file type for their own purposes - it has no meaning outside that.

So of course Nuitka doesn't understand those files - and neither would any other Python compiler, be it py2exe, cx-freeze or whatever.

**Comment by nickrh75** [comment]
Ok, thanks for the info @JorjMcKie.
