### ISSUE TITLE
How to execute a compiled version of aiohttp script 

### ISSUE THREAD

**Issue by Kalanamith** [Nuitka/Nuitka#355]
I tried to compile and run following script using Nuitka in Ubuntu 18.04 LTS version, Python 3.6.8 and Nuitka 0.5.0.2.8 
All the dependencies were installed 

. The script taken from https://docs.aiohttp.org/en/v3.0.1/
filename :- server.py

```
from aiohttp import web

async def handle(request):
    name = request.match_info.get('name', "Anonymous")
    text = "Hello, " + name
    return web.Response(text=text)

app = web.Application()
app.router.add_get('/', handle)
app.router.add_get('/{name}', handle)

web.run_app(app)

```

I have used the following command  to compile it 
`python -m nuitka --follow-imports --standalone server.py` 

This will create 2 folders and no compile errors were given.

When I tried to run the server file in `server.dist` folder, it threw the following error 

```
ModuleNotFoundError: No moduke named 'aiohttp'

```
aiohttp is installed in current environment.   Is it required to do additional steps?

**Comment by kayhayen** [comment]
The version of Nuitka you are using is really distant from 0.6.3 which is the current release. But it is supposed to work once `python server.py` works, no sooner, and I doubt it does.

There is an archive for Ubuntu on the download page of Nuitka, which has the current stable version, use that instead.

Yours,
Kay

**Comment by Kalanamith** [comment]
I tried with  Nuitka installed on pip and ideally this did not work. After installing Nuitka negatively on  Linux along side with python dependencies worked. In addition to this any relative imports in a project wont work.
