### ISSUE TITLE
Nuitka compiled file only works for My PC

### ISSUE THREAD

**Issue by whatevea** [Nuitka/Nuitka#358]
I compiled my python 3.6 script using nuitka, which works fine in my Pc but in other PC it gives this problem. it is supposed be independent executable file isnt it /? then why i am having such errors.

![image](https://user-images.githubusercontent.com/49833723/56469124-1b07bb00-6455-11e9-90a5-79e933213245.png)

**Comment by kayhayen** [comment]
No issue template, no support.

**Comment by whatevea** [comment]
please help if you can
