### ISSUE TITLE
Big Project Memory is overflow.

### ISSUE THREAD

**Issue by 7369632** [Nuitka/Nuitka#361]
Memory Error.

Memory overflow, Python 32 bits, memory usage exceeding 4GB, has been used / largeaddressaware to remove 2GB of memory restrictions.

nuitka version:0.6.3
command: 
nuitka --follow-imports  --experimental=use_pefile --experimental=use_pefile_recurse --experimental=use_pefile_fullrecurse --include-plugin-directory="D:\n\a" --standalone  --show-memory --show-modules a.py --show-progress --show-scons --output-dir="D:\n\Out"

**Comment by kayhayen** [comment]
Using 32 bits is bound for memory issues, simply use 64 bits.

**Comment by 7369632** [comment]
> Using 32 bits is bound for memory issues, simply use 64 bits.

Thank，But my program is written in 32 bits, and the external DLL is 32 bits.
How do I prevent memory overflow?
