### ISSUE TITLE
Segmentation fault when importing module "sh"

### ISSUE THREAD

**Issue by johndoe46** [Nuitka/Nuitka#365]
Using python module sh (https://github.com/amoffat/sh in version 1.12.14), Nuitka does create an executable but this exe segfaults:

```
(venv) ➜ ✗ cat crashme.py
import sh
print("hello")
(venv) ➜ ✗ python -m nuitka --standalone crashme.py 
(venv) ➜ ✗ ./crashme.dist/crashme 
[1]    19819 segmentation fault (core dumped)  ./crashme.dist/crashme
(venv) ➜  ✗ python -m nuitka --version
0.6.3
Python: 3.7.3 (default, Apr  3 2019, 05:39:12) 
Executable: /home/me/some/folder/venv/bin/python
OS: Linux
Arch: x86_64
```

Python is the stock python37 from Ubuntu 19.04.

**Comment by johndoe46** [comment]
I'm just gonna avoid sh for now but since one of Nuitka's goal is compatibility I thought you might find it interesting.

**Comment by AetherPrior** [comment]
I'm unable to recreate this error in:
```
0.6.6rc3
Python: 3.6.8 (default, Jan 14 2019, 11:02:34) 
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
```
Output:
```
$ python3 -m nuitka --standalone  crashme.py
$ ./crashme.dist/crashme
Hello, World!
```

**Comment by kayhayen** [comment]
Thanks @AetherPrior for checking this out. I think the last release contained a fix for shared library loading, that was definitely there, but hard to observe. It may have fixed this. I am adding needs_example waiting for @johndoe46 to confirm.

**Comment by johndoe46** [comment]
I can't confirm right now (laptop completely dead :'-( ) but I'll set up a VM before monday and I'll get back here.

**Comment by johndoe46** [comment]
Did a quick test with a recent Debian with stock Python. No problem now:

![nuitka sh](https://assets.bontards.com/upload/25/25c659e9a958f57922212a93d1ed52f2c5839be0/nuitka-sh.png)

Whatever didn't worked must have been fixed. Thank you :)

**Comment by kayhayen** [comment]
Thanks for reporting back, closing.
