### ISSUE TITLE
Segmentation Fault on Mac OS X High Sierra

### ISSUE THREAD

**Issue by es1o** [Nuitka/Nuitka#366]
Hello,
I have a problem with nuitka. I get Segmentation Faul after trying run nuitka binary.

*  Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

```
0.6.3
Python: 3.7.3 (default, Mar 27 2019, 09:23:15)
Executable: /Users/esio/work/gamalon/python-compile/venv/bin/python
OS: Darwin
Arch: x86_64
```

*  How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
   what is a virtualenv ...), this is very important usually.
I installed virtualenv `virtualenv venv` and then `pip install nuitka`

*  If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
   that demonstrates the issue i.e a small piece of code which reproduces
   the issue and can be run with out any other (or as few as possible)
   external dependencies.
```
def esio():
    print("Hello World!")

if __name__ == "__main__":
    esio()
```

*  If this is a regression (used to work in an earlier version of Nuitka),
   please note what you know about that.

I don't know. I've never user nuitka before.

* How to reproduce:
1. Write simple code.
2. Compile with nuitka `python3 -m nuitka --standalone hello.py`
3. Run code: `cd hello.dist` `./hello`

I get Segmentation fault:

`[1]    34392 segmentation fault  ./hello`

I tested the same code on Ubuntu and everything works. How to compile and test code on Mac OS X?

**Comment by kayhayen** [comment]
What kind of Python installation is this? Are you using pyenv by chance?

Yours,
Kay

**Comment by idchlife** [comment]
I have same error.
I'm using pipenv (basically package manager and automator for virtualenv). I jump into virtualenv (so all the libraries will be available) and build. After trying to execute I'm getting segmentation fault.
I tried different options, but maybe there is a common pattern for building for mac os?

**Comment by kayhayen** [comment]
I think I would the output with `--debugger`, i.e. a traceback of where the crash is happening. Likely this is a simple regression of some sorts, I do not have a MacOS machine at all.

**Comment by idchlife** [comment]
@kayhayen ok, thank you!

**Comment by kayhayen** [comment]
Seems 3.5 and higher were affected, and PR on develop merged fixed it. Currently on the git branch has that, packages will follow later.
