### ISSUE TITLE
factory openSUSE FlaskUsing.py on Python 2

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#369]
When using [branch factory Nuitka-0.6.3.1556202417, on openSUSE Python 2.7, .spec](https://build.opensuse.org/package/show/home:jayvdb:py-bridge/python-Nuitka-factory)

```
[  558s] Consider output of recursively compiled program: FlaskUsing.py
[  558s] Comparing output of 'FlaskUsing.py' using '/usr/bin/python2' with flags silent, expect_success, standalone, remove_output, ignore_warnings ...
[  828s] --- /usr/bin/python2 (stderr)
[  828s] +++ nuitka (stderr)
[  828s] 
[  828s] @@ -1 +1,2 @@
[  828s] 
[  828s] +Nuitka:INFO:Missing C helper code variant, used fallback: BINARY_OPERATION_ADD_UNICODE_STR
[  828s]  
[  828s] Error, outputs differed.
[  828s] Error exit! 1
[  828s] error: Bad exit status from /var/tmp/rpm-tmp.2D64DA (%check)
```

Not happening on 0.6.3.1 (which I am just starting to play with).

**Comment by kayhayen** [comment]
That's great, I just managed to get the Jinja2 based creation of these helpers in place, adding these variants with not extremely shabby optimization clearly will be easy now.

The 0.6.3.1 diff is minimal, and unrelated. Actually it's a fix only effective on Windows, you can ignore that release for now.

**Comment by jayvdb** [comment]
thx for info re 0.6.3.1 .  I didnt check the diff of that, so I would have wasted a lot of time for no reason.  I'll keep focused on factory branch.

**Comment by kayhayen** [comment]
This one will have to wait a bit. I took the chance and added specialized helpers for all the pairs in the group `int`/`long`/`float` and `unicode`/`str`. It will be a while, until my Buildbots give me enough confidence of that change, and I think I may need to add tests for it.

**Comment by jayvdb** [comment]
Confirming this doesnt occur on Python 3.

**Comment by kayhayen** [comment]
This is in 0.6.4 I think, surely on factory.
