### ISSUE TITLE
run-tests --no-other-python runs CPython2.6 which needs git-core

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#371]
That `--no-other-python` runs CPython 2.6 tests is a bit surprising in itself, but then...

```py
[ 1003s] Using concrete python 2.7.16 on x86_64
[ 1003s] Traceback (most recent call last):
[ 1003s]   File "./tests/CPython26/run_all.py", line 29, in <module>
[ 1003s]     setupCacheHashSalt(".")
[ 1003s]   File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.3.1556225278.5b0db9f5/nuitka/tools/testing/Common.py", line 1255, in setupCacheHashSalt
[ 1003s]     args=git_cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE
[ 1003s]   File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
[ 1003s]     errread, errwrite)
[ 1003s]   File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
[ 1003s]     raise child_exception
[ 1003s] OSError: [Errno 2] No such file or directory
[ 1003s] error: Bad exit status from /var/tmp/rpm-tmp.sWDzW2 (%check)
```

I look under the covers and it is attempting to run `git`.  It would be nice if the exception mentioned what was missing, and better yet recovered and ignored the missing `git` if that is possible.

When I add git

```
[  835s] Run '/usr/bin/python2 ./tests/CPython26/run_all.py search' in '/home/abuild/rpmbuild/BUILD/Nuitka-0.6.3.1556202417.e23ccdbb'.
[  835s] Using concrete python 2.7.16 on x86_64
[  835s] Traceback (most recent call last):
[  835s]   File "./tests/CPython26/run_all.py", line 29, in <module>
[  835s]     setupCacheHashSalt(".")
[  835s]   File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.3.1556202417.e23ccdbb/nuitka/tools/testing/Common.py", line 1272, in setupCacheHashSalt
[  835s]     assert process.returncode == 0, stderr_git
[  835s] AssertionError: fatal: not a git repository (or any of the parent directories): .git
```
I'm going to try `--skip-other-cpython-tests` and hope that gets me passed this.

This wasnt happening with my builds against the released versions.
It is new on my factory builds: https://build.opensuse.org/package/show/home:jayvdb:py-bridge/python-Nuitka-factory

**Comment by kayhayen** [comment]
I see, that's too bad. I am using the git to get a tree value for my testing, where there is always a .git source, but I can see how that might not be the case. Also the other day I was annoyed at a Python package randomly checking with git to detect its version.

I am going to push a fix to factory soon, where when it's not a git checkout, it is scanning the file list and using hash content of that as a stop gap.

**Comment by kayhayen** [comment]
The code is on factory, ought to be better for you now.

**Comment by jayvdb** [comment]
I havent got this part of the test suite working in factory, probably due to https://github.com/Nuitka/Nuitka/issues/375 , but it does appear that this specific problem is resolved.  Much appreciated.
