### ISSUE TITLE
factory openSUSE PasslibUsing.py on Python 2

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#374]
```console
[  938s] Consider output of recursively compiled program: PasslibUsing.py
[  939s] Comparing output of 'PasslibUsing.py' using '/usr/bin/python2' with flags silent, expect_success, standalone, remove_output, ignore_warnings ...
[ 1025s] --- /usr/bin/python2 (stdout)
[ 1025s] +++ nuitka (stdout)
[ 1025s] 
[ 1025s] @@ -1,4 +1 @@
[ 1025s] 
[ 1025s] -hello
[ 1025s] -118
[ 1025s] -bye
[ 1025s]  
[ 1025s] --- /usr/bin/python2 (stderr)
[ 1025s] +++ nuitka (stderr)
[ 1025s] 
[ 1025s] @@ -1 +1,2 @@
[ 1025s] 
[ 1025s] +PasslibUsing: /home/abuild/rpmbuild/BUILD/Nuitka-0.6.3.1556302073.5d14149b/nuitka/build/include/nuitka/helper/dictionaries.h:209: DICT_SET_ITEM: Assertion `Py_REFCNT(value) > 0' failed.
[ 1025s]  
[ 1025s] Exit codes 0 (CPython) != -6 (Nuitka)
```

**Comment by jayvdb** [comment]
This is occurring only on Python 2.  It passes on Python 3.

**Comment by kayhayen** [comment]
Wow, that's a bad one, reference losses are the worst and luckily for some time typically rare, but very important to hunt down. Which version was this one? Factory or stable or both?

**Comment by jayvdb** [comment]
This is done with Nuitka factory, and using the openSUSE standard package for passlib, which is from https://build.opensuse.org/package/show/devel:languages:python/python-passlib and the openSUSE factory has identical version.  All 1.7.1, same as PyPI.  Note it has a patch, to allow testing against libxcrypt, but no change to the source.  Not sure if that is relevant.

**Comment by kayhayen** [comment]
Can you still reproduce this one, because I cannot.

**Comment by jayvdb** [comment]
Seems to be fixed
