### ISSUE TITLE
factory, openSUSE test/test_aepack.py difference due to missing modules on Linux

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#375]
```console
[  842s] Comparing output of 'test/test_aepack.py' using '/usr/bin/python2' with flags silent, remove_output, binary_python_path, recurse_none, original_file, cpython_cache ...
[  848s] --- /usr/bin/python2 (stderr)
[  848s] +++ nuitka (stderr)
[  848s] 
[  848s] @@ -1,7 +1,7 @@
[  848s] 
[  848s]  Traceback (most recent call last):
[  848s]    File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.3.1556302073.5d14149b/tests/CPython27/test/test_aepack.py", line 7, in <module>
[  848s]      aetypes = test_support.import_module('aetypes')
[  848s] -  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.3.1556302073.5d14149b/tests/CPython27/test/test_support.py", line 81, in import_module
[  848s] +  File "/usr/lib64/python2.7/test/support/__init__.py", line 92, in import_module
[  848s]      raise unittest.SkipTest(str(msg))
[  848s]  unittest.case.SkipTest: No module named aetypes
[  848s]  
[  848s] Error, outputs differed.
[  848s] Error exit! 1
[  848s] error: Bad exit status from /var/tmp/rpm-tmp.Ec0vuH (%check)
```

**Comment by kayhayen** [comment]
I strongly believe that absolute vs. relative import should work.

This is because the program compiled lives in `test`, and only that is added to the `PYTHONPATH`, but instead, the current directory is missing for Nuitka, but not for CPython. This should only need a tuning of the test suite runners therefore.

**Comment by kayhayen** [comment]
I am however lacking an explanation, why this is not happening for me. I too don't have the module, but for me, the CPython call stack is more like this (on Windows, but I am sure, Linux will be similar):

```
Comparing output of 'test\test_aepack.py' using 'C:\Python27_32\python.exe' with flags silent, remove_output, binary_python_path, recurse_none, original_file, cpython_cache, expect_success ...
 Traceback (most recent call last):
  File "test\test_aepack.py", line 7, in <module>
    aetypes = test_support.import_module('aetypes')
  File "C:\Users\kayha\repos\Py2C\tests\CPython27\test\test_support.py", line 81, in import_module
    raise unittest.SkipTest(str(msg))
unittest.case.SkipTest: No module named aetypes
```

The current directory, should remain in the PYTHONPATH. Is there potentially something in OBS that disables that?

Yours,
Kay

**Comment by kayhayen** [comment]
Alternatively, something that enables absolute_imports could also be the case, but that is nothing I believe that can be done easily.

**Comment by jayvdb** [comment]
Every step can be seen at https://build.opensuse.org/build/home:jayvdb:py-bridge/openSUSE_Tumbleweed/x86_64/python-Nuitka-factory/_log

Currently being invoked as `/usr/bin/python2 ./tests/run-tests --no-other-python --skip-other-cpython-tests --skip-cpython27-tests --skip-reflection-test` , but the problem occurs when `--skip-cpython27-tests` is removed.

Nothing is fiddling with `PYTHONPATH`, and I doubt OBS does anything relevant.

However there are a long list of patches applied at https://build.opensuse.org/package/show/devel:languages:python:Factory/python which might be relevant.

Any logic which is making assumptions about the path of a stdlib module could be trouble - the logic should use `mod.__file__` to find where the module lives, and maybe use `os.__file__` as the default location of stdlib.

Skimming through the logs of https://build.opensuse.org/build/devel:languages:python:Factory/openSUSE_Tumbleweed/x86_64/python-base/_log and https://build.opensuse.org/build/devel:languages:python:Factory/openSUSE_Tumbleweed/x86_64/python/_log might show something placed where Nuitka or the test runner isnt expecting.

You can branch my OBS project and play with it, e.g. add debugging in `%prep` to investigate, or run extra tests.  `osc service runall` will sync with Nuitka branch `factory`.

**Comment by jayvdb** [comment]
I ran into the same problem with `test_al` and `test_MacOS` , so I assume the same will occur for any platform specific module on Python 2.

**Comment by kayhayen** [comment]
> [  848s] -  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.3.1556302073.5d14149b/tests/CPython27/test/test_support.py", line 81, in import_module
> [  848s] +  File "/usr/lib64/python2.7/test/support/__init__.py", line 92, in import_module

What's striking me now, is that this isn't even the same module. One is "test.test_support" or "test_support" normally, and the other is "test.support", which is how Python3 test suites do it.

I assume this is yet again another backport, that might be unexpected. However, I totally fail to see, how the two could be confused, ever.

I do need to make sure though, that binary_python_path does actually work. This seemed to indicate it may not, or be not as strict in terms of order, e.g. not putting things first when they should.

Yours,
Kay

**Comment by jayvdb** [comment]
It looks like this is solved in v0.6.5.

**Comment by jayvdb** [comment]
AH my mistake.  The problem still exists when I remove `--skip-cpython27-tests`.

```console
[ 1540s] Comparing output of 'test/test_aepack.py' using '/usr/bin/python2' with flags silent, remove_output, binary_python_path, recurse_none, original_file, cpython_cache ...
[ 1549s] --- /usr/bin/python2 (stderr)
[ 1549s] +++ nuitka (stderr)
[ 1549s] 
[ 1549s] @@ -1,7 +1,7 @@
[ 1549s] 
[ 1549s]  Traceback (most recent call last):
[ 1549s]    File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.5.1564222277.69470ccd/tests/CPython27/test/test_aepack.py", line 7, in <module>
[ 1549s]      aetypes = test_support.import_module('aetypes')
[ 1549s] -  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.5.1564222277.69470ccd/tests/CPython27/test/test_support.py", line 81, in import_module
[ 1549s] +  File "/usr/lib64/python2.7/test/support/__init__.py", line 89, in import_module
[ 1549s]      raise unittest.SkipTest(str(msg))
[ 1549s]  unittest.case.SkipTest: No module named aetypes
[ 1549s]  
[ 1549s] Error, outputs differed.
[ 1549s] Error exit! 1
```

**Comment by jayvdb** [comment]
The cause is in the test runners fiddling of sys.path

```console
[  965s] Comparing output of 'test/test_aepack.py' using '/usr/bin/python2' with flags silent, remove_output, binary_python_path, recurse_none, original_file, cpython_cache ...
[  981s] --- /usr/bin/python2 (stderr)
[  981s] +++ nuitka (stderr)
[  981s] 
[  981s] @@ -1,5 +1,5 @@
[  981s] 
[  981s]  Traceback (most recent call last):
[  981s]    File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.5.1568975414.e336d005/tests/CPython27/test/test_aepack.py", line 7, in <module>
[  981s]      import sys;raise RuntimeError(sys.path);aetypes = test_support.import_module('aetypes')
[  852s] -RuntimeError: ['/home/abuild/rpmbuild/BUILD/Nuitka-0.6.5.1568975414.e336d005/tests/CPython27/test', '/home/abuild/rpmbuild/BUILDROOT/python-Nuitka-0.6.5.1568975414.e336d005-27.1.x86_64/usr/lib/python2.7/site-packages', '/home/abuild/rpmbuild/BUILD/Nuitka-0.6.5.1568975414.e336d005/tests/CPython27/test', '/home/abuild/rpmbuild/BUILD/Nuitka-0.6.5.1568975414.e336d005/tests/CPython27', '/usr/lib/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7/site-packages', '/usr/local/lib64/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages', '/usr/lib/python2.7/site-packages']
[  852s] +RuntimeError: ['/var/tmp/27tests/python2.7-debug', '/home/abuild/rpmbuild/BUILDROOT/python-Nuitka-0.6.5.1568975414.e336d005-27.1.x86_64/usr/lib/python2.7/site-packages', '/home/abuild/rpmbuild/BUILD/Nuitka-0.6.5.1568975414.e336d005/tests/CPython27/test', '/home/abuild/rpmbuild/BUILD/Nuitka-0.6.5.1568975414.e336d005', '/usr/lib/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7/site-packages', '/usr/local/lib64/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages', '/usr/lib/python2.7/site-packages']
```

When I run `PYTHONPATH=${PWD}/tests/CPython27/ python2 ./tests/run-tests --no-other-python ...` these tests pass.

**Comment by kayhayen** [comment]
Brilliant line of attack, I should have thought of that.

Thanks, I am going to push a change to factory soon, matching the change I was making in the test suites just now. It will make sure they both have the test suite directory in path.

**Comment by kayhayen** [comment]
This is on develop for a while and awaits release soonish.

**Comment by kayhayen** [comment]
Has been released.
