### ISSUE TITLE
ModuleNotFoundError when using gevent and --standalone

### ISSUE THREAD

**Issue by dmrlawson** [Nuitka/Nuitka#379]
Hi,

I think this is the same issue as http://bugs.nuitka.net/issue420 but that hasn't had a response in six months.

Using this script `nuitka_test.py` as an example:
```python
import gevent.monkey
gevent.monkey.patch_all()

print("Hi!")
```

I create a virtualenv using Python 3.7.3, then:
```bash
(venv) $ pip install nuitka gevent
(venv) $ python -m nuitka nuitka_test.py
(venv) $ ./nuitka_test.bin
Hi!
(venv) $ python -m nuitka --standalone nuitka_test.py
Nuitka:WARNING:Use '--plugin-enable=pylint-warnings' for: Understand PyLint/PyDev annotations for warnings.
Nuitka:WARNING:Unresolved '__import__' call at '/home/davidlawson/.virtualenvs/tmp-2543a007f75e0254/lib/python3.7/site-packages/gevent/_hub_local.py:24' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at '/home/davidlawson/.virtualenvs/tmp-2543a007f75e0254/lib/python3.7/site-packages/gevent/hub.py:63' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at '/home/davidlawson/.virtualenvs/tmp-2543a007f75e0254/lib/python3.7/site-packages/gevent/monkey.py:224' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at '/home/davidlawson/.virtualenvs/tmp-2543a007f75e0254/lib/python3.7/site-packages/gevent/monkey.py:347' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at '/home/davidlawson/.virtualenvs/tmp-2543a007f75e0254/lib/python3.7/site-packages/gevent/monkey.py:349' may require use of '--include-plugin-directory' or '--include-plugin-files'.
(venv) $ ./nuitka_test.dist/nuitka_test 
Traceback (most recent call last):
  File "/home/davidlawson/.virtualenvs/tmp-2543a007f75e0254/nuitka_test.dist/nuitka_test.py", line 1, in <module>
  File "/home/davidlawson/.virtualenvs/tmp-2543a007f75e0254/nuitka_test.dist/gevent/__init__.py", line 87, in <module gevent>
  File "/home/davidlawson/.virtualenvs/tmp-2543a007f75e0254/nuitka_test.dist/gevent/_hub_local.py", line 101, in <module gevent._hub_local>
  File "/home/davidlawson/.virtualenvs/tmp-2543a007f75e0254/nuitka_test.dist/gevent/_util.py", line 105, in import_c_accel
  File "/home/davidlawson/.virtualenvs/tmp-2543a007f75e0254/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'gevent.__hub_local'
```

If I try including the gevent directory like so:
```bash
(venv) $ python -m nuitka --standalone --include-plugin-directory=/home/davidlawson/.virtualenvs/tmp-2543a007f75e0254/lib/python3.7/site-packages/gevent nuitka_test.py
```

I get the same result but not the `Nuitka:WARNING:Unresolved '__import__' ...` warnings.

This was originally with the latest releases of nuitka from PyPi (0.6.3.1) and gevent (1.4.0). I've tried with the development branch of nuitka as well and saw no difference.

**Comment by JorjMcKie** [comment]
I'll look into it.

**Comment by JorjMcKie** [comment]
@dmrlawson - I have a successful compile and run of your example.
Required a carefully specified set of so-called _**implcit imports**_ and an extra plugin (welcome to the club).
Before I now go and integrate these changes for the next Nuitka version:
Do you have a more complex example for me please? Need to make sure things will always work.
Thanks

**Comment by dmrlawson** [comment]
Great, thank you!

I don't have a good example to share at the moment, but this one from the gevent repo should test that it's actually working: https://github.com/gevent/gevent/blob/master/examples/concurrent_download.py

**Comment by 5murfette** [comment]
any update on this? I have the same issue, good timing ...

**Comment by 5murfette** [comment]
Now looking back, my issue seems related, but is a bit different, for example, I am able to reproduce almost the same issue with pure Python3, as I have after compiling with Nuitka on Python2.7:

I did insert one log print into gevent/_util.py @ def import_c_accel ->
`print("cname =", cname)`
before
`mod = importlib.import_module(cname)`

My gevent test app:
`import gevent

from gevent import monkey
if "patch_subprocess" in dir(monkey):  # New gevent
    monkey.patch_all(thread=False, subprocess=False)
`

First, pure Python2.7 run of gevent:
`c:\Python27amd64\python.exe somelib.py
cname = gevent.__hub_local
cname = gevent.__greenlet_primitives
cname = gevent.__waiter
cname = gevent.__hub_primitives
cname = gevent._greenlet
cname = gevent.__ident
cname = gevent.__abstract_linkable
cname = gevent._event
cname = gevent.__semaphore
cname = gevent._queue
Hello from lib too!`

Then, same run on pure Python 3.6.6:
`c:\Python36_64\python.exe somelib.py
cname = gevent.__hub_local
Traceback (most recent call last):
  File "D:\Projects\bundle-test\somelib.py", line 2, in <module>
    import gevent
  File "D:\Projects\bundle-test\gevent\__init__.py", line 87, in <module>
    from gevent._hub_local import get_hub
  File "D:\Projects\bundle-test\gevent\_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "D:\Projects\bundle-test\gevent\_util.py", line 106, in import_c_accel
    mod = importlib.import_module(cname)
  File "C:\Python36_64\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: Module not found`

Now, same file compiled with Nuitka on Python2.7:
`c:\Python27amd64\python.exe -m nuitka --standalone --mingw64 somelib.py --follow-imports`
=>
`somelib.dist\somelib.exe
cname = gevent.__hub_local
Traceback (most recent call last):
  File "d:\Projects\bundle-test\somelib.dist\somelib.py", line 2, in <module>
  File "d:\Projects\bundle-test\somelib.dist\gevent\__init__.py", line 87, in <module gevent>
  File "d:\Projects\bundle-test\somelib.dist\gevent\_hub_local.py", line 101, in <module gevent._hub_local>
  File "d:\Projects\bundle-test\somelib.dist\gevent\_util.py", line 106, in import_c_accel
  File "d:\Projects\bundle-test\somelib.dist\importlib\__init__.py", line 37, in import_module
ImportError: No module named __hub_local`

So I'm not sure what is wrong here, but Nuitka seems to behave more like Python3.6 even though it is running on Python2.7.

**Comment by JorjMcKie** [comment]
I am currently working on this - with partial success so far.

What both of you observe are consequences of "hidden imports" done by gevent. This means, that source code analyzers (eg. compilers like Nuitka) are unable to see what is going to be imported, when an import with a "disguised" name is encountered.
It's even worse when imports happen inside a a compiled (shared) module, because you then don't even know that an import is happening there.

In all those cases, we must (1) find out what is going on, and (2) tell Nuitka to do the import under conditions similar to the application.
PyInstaller and the likes have basically a similar problem. But because the keep the whole application interpreted by the normal Pyhon interpreter, they just need to pack a big enough bundle and feed this into the interpreter.
This is more complex for a true compiler like Nuitka ...

The above is heavily the case with gevent. And even a bit worse, because completely different things are done in different situations, and the sequence (or point in time) of when an import should happen, also plays a big role: you cannot just name all - you must make this situation-dependent as well. And then gevent also overwrites ("monkey patches") standard modules with its own stuff - an additional complication.

This is what I currently trying to understand, so I must ask for your patience ...

**Comment by JorjMcKie** [comment]
Making progress:
Found an additional missing implicit import. Testing changes on Windows now.
Once Linux also works, I will let you know ...

**Comment by JorjMcKie** [comment]
I have finally been successful:
With a combination of the right implicit imports and the new standard plugin `gevent` the above example can be compiled and executed on both, Windows and Linux.

Thse changes are on their way into Nuitka's development branch. Expect respective news in the next few days.

**Comment by dmrlawson** [comment]
I tested your branch and it so far it seems to work perfectly, thank you!

I still see the warnings during compilation but there doesn't seem to be a problem.

**Comment by JorjMcKie** [comment]
glad to hear this!
Your are on Linux, right?
Yes the warnings can be ignored. Some day I'll switch them off. As well as the wordiness in total.

**Comment by dmrlawson** [comment]
Great, thanks for the clarification.

Yes, this is on Linux.

**Comment by kayhayen** [comment]
If you are really desparate in debugging potentially missing DLLs, this can also help:

https://docs.microsoft.com/de-de/sysinternals/downloads/procmon

I was just using it, and seeing what `_ctypes.pyd` is doing to crash my new code.

**Comment by JorjMcKie** [comment]
@dmrlawson - how is your status? Everything green with the latest nuitka version?

**Comment by dmrlawson** [comment]
Using your branch everything worked flawlessly, thank you.
