### ISSUE TITLE
Issue of compiling for pandas

### ISSUE THREAD

**Issue by 7369632** [Nuitka/Nuitka#380]
Python Version:2.7
pandas Version:0.24.2
File:"pandas\core\groupby\grouper.py"
nuitka Version:factory
and master Version is no problem.

Error:
```
grouper.build\module.grouper.cpp(20227): error C2094: 标签“function_exception_e
xit”未定义scons: *** [grouper.build\module.grouper.obj] Error 2
scons: building terminated because of errors.
```

**Comment by kayhayen** [comment]
Thanks for your report, the recent id optimization fix was causing this, fixed now.
