### ISSUE TITLE
Question: Getting runtime errors, e.g. undefined symbol: PyFPE_jbuf

### ISSUE THREAD

**Issue by VladVons** [Nuitka/Nuitka#383]
I compiled project on (Debian 9.9, Python 2.7.13)
nuitka --follow-imports --remove-output Project.py

when i run binary on (Ubuntu 18.04, Python 2.7.15rc1) i get error
undefined symbol: PyFPE_jbuf

i founf this string "PyFPE_jbuf"  in  Debian 9.9 machine
/usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.a
/usr/lib/python2.7/config-x86_64-linux-gnu/python.o
 
What should i additional install to run project on Ubuntu machine?
Or should i generate each time binary for every type of linux?

**Comment by kayhayen** [comment]
When you mean to switch machines, OSes for sure, use --standalone mode. Otherwise the system  libraries will be unable to execute stuff.

Yours,
Kay

**Comment by JJMeric** [comment]
using the --standalone option, my previous Project.bin has not been replaced, the only thins that gets updated are the directories Project.build and Project.dist

**Comment by kayhayen** [comment]
The standalone binary is in the dist folder unless using onefile. Nuitka does not delete files outside of that.
