### ISSUE TITLE
Incorrect definition of the system console encoding in Windows used by cmd.exe

### ISSUE THREAD

**Issue by omgiafs** [Nuitka/Nuitka#386]
Hello.
Trying to compile a simple script (encoding - utf-8), got error `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 41: invalid continuation byte:`:
```
scons: Reading SConscript files ...
SCONS:  Tools= ['mingw']
Scons CC 'gcc' version check:
Scons CC 'gcc' version check gives '5.3.0' from '5.3.0'
Initial CC: gcc
Initial CCVERSION: 5.3.0
Initial CXX: g++
Initial CXXVERSION: None
SCONS:  Picked compiler: gcc
SCONS:  Picked name: gcc
Scons compiler: Using H:\Programs\Miniconda3\Library\mingw-w64\bin\gcc.exe
Scons: Detecting arch with : ['objdump', '-f', 'h:\\Programs\\Miniconda3\\python.exe']
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 41: invalid continuation byte:
  File "H:\Programs\Miniconda3\lib\site-packages\nuitka\build\SingleExe.scons", line 1387:
    if getLinkerArch() != getCompilerArch():
  File "H:\Programs\Miniconda3\lib\site-packages\nuitka\build\SingleExe.scons", line 1363:
    _linker_arch = _getBinaryArch(os.environ["NUITKA_PYTHON_EXE_PATH"])
  File "H:\Programs\Miniconda3\lib\site-packages\nuitka\build\SingleExe.scons", line 1345:
    data = data.decode(sys.stdout.encoding)
```

Some information about environment:
Machine configuration: Windows 10 x64 (**Russian language**).
Python 3.6.7 installed from Miniconda 3, Nuitka DEV installed from Factory (`pip install -U "http://nuitka.net/gitweb/?p=Nuitka.git;a=snapshot;h=refs/heads/factory;sf=tgz"`).

```
h:\Programs\Miniconda3>python -m nuitka --version
0.6.4rc3
Python: 3.6.7 |Anaconda, Inc.| (default, Oct 28 2018, 20:57:12) [MSC v.1915 32 bit (Intel)]
Executable: h:\Programs\Miniconda3\python.exe
OS: Windows
Arch: x86

h:\Programs\Miniconda3>python.exe
Python 3.6.7 |Anaconda, Inc.| (default, Oct 28 2018, 20:57:12) [MSC v.1915 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import locale
>>> print(locale.getpreferredencoding())
cp1251
>>> print(sys.getdefaultencoding())
utf-8
>>> print(sys.stdout.encoding)
utf-8
>>> exit()

h:\Programs\Miniconda3>chcp
Текущая кодовая страница: 866
```

This error is a child of Windows codepage hell.
Python get preferenced encoding `cp1251`, default encoding `utf-8`, stdout encoding `utf-8` a-a-and windows console encoding is `cp866`! Bingo!

So we have an incorrect definition of the system console encoding in Windows used by `cmd.exe`. 
If i change line 1345 of `\lib\site-packages\nuitka\build\SingleExe.scons` from 
`data = data.decode(sys.stdout.encoding)` to
`data = data.decode('cp866')`,
all works perfect, and compilation finishing successfully.

Problem is to detect correct codepage used by `cmd.exe`.

**Comment by kayhayen** [comment]
This only happens with MSVC, which it seems will output without respect to anything, in whatever encoding the compiler language has. I have no idea how to predict the encoding that MSVC will use. The only approach currently would be to uninstall the languages, but I believe this may also be interface language for Visual Studio.

The `sys.stdout.encoding` is a failed attempt indeed, because MSVC will not respect it. I wonder if there is any way to get it from some form of `--version` output. Can you provide a sample of your `cl.exe --version` as a binary file (i.e. redirected to a file), so I have something to check on.

**Comment by omgiafs** [comment]
> Can you provide a sample of your `cl.exe --version` as a binary file (i.e. redirected to a file), so I have something to check on.
Here it is. And yes, this file have OEM866 codepage.
[cl-output.txt](https://github.com/Nuitka/Nuitka/files/3182535/cl-output.txt)

**Comment by alex-pobeditel-2004** [comment]
@omgiafs  
About compilation without VS - I installed mingw64 (it quite small) - after that you can use ` --mingw64` in command line

**Comment by kayhayen** [comment]
Nuitka now downloads the winlibs compiler automatically and uses it. That should solve the issue for you. For decoding outputs, we now have code that attempts many things. Since this is used, never heard of it again:

```
def decodeData(data):
    """Our own decode tries to workaround MSVC misbehavior."""
    try:
        return data.decode(sys.stdout.encoding)
    except UnicodeDecodeError:
        import locale

        try:
            return data.decode(locale.getpreferredencoding())
        except UnicodeDecodeError:
            return data.decode("utf8", "backslashreplace")
```
