### ISSUE TITLE
Compilation works under Virtualenv but not Pipenv

### ISSUE THREAD

**Issue by morefigs** [Nuitka/Nuitka#387]
**Nuitka version** 0.6.3.1

**Windows version** Win 10 Pro 1803

**Python version** Standard install, Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32

**Installation**
Installed via Pipenv.

**Regression** unknown.

**Problem**

I recently upgraded my project's virtual environment from Virtualenv to Pipenv.

Under Virtualenv compilation would work via:

    venv\Scripts\python.exe -m nuitka --standalone --mingw64 --windows-disable-console --plugin-enable=qt-plugins app\app.py

However when I create a Pipenv environment the app runs fine, but compilation fails when called via:

    pipenv run python -m nuitka --standalone --mingw64 --windows-disable-console --plugin-enable=qt-plugins app\app.py

It seems to fail upon copying required DLLs. The error message is:

    Nuitka:INFO:Injecting plug-in based post load code for module 'PyQt5.QtCore':
    Nuitka:INFO:    Setting Qt library path to distribution folder. Need to avoid loading target
    Nuitka:INFO:    system Qt plug-ins, which may be from another Qt version.
    Nuitka:WARNING:Use '--plugin-enable=pylint-warnings' for: Understand PyLint/PyDev annotations for warnings.
    Nuitka:INFO:Copying Qt plug-ins 'iconengines,imageformats,mediaservice,platforms,printsupport' to 'app.dist\PyQt5\qt-plugins'.
    Nuitka:INFO:Copying OpenSSL DLLs to 'app.dist'
    Traceback (most recent call last):
    File "C:\Users\user\.virtualenvs\app-dBcG5naP\lib\site-packages\nuitka\__main__.py", line 184, in <module>
    main()
    File "C:\Users\user\.virtualenvs\app-dBcG5naP\lib\site-packages\nuitka\__main__.py", line 177, in main
    MainControl.main()
    File "C:\Users\user\.virtualenvs\app-dBcG5naP\lib\site-packages\nuitka\MainControl.py", line 774, in main
    standalone_entry_points=standalone_entry_points,
    File "C:\Users\user\.virtualenvs\app-dBcG5naP\lib\site-packages\nuitka\freezer\Standalone.py", line 1513, in copyUsedDLLs
    dll_version1 = getWindowsDLLVersion(dll_filename1)
    File "C:\Users\user\.virtualenvs\app-dBcG5naP\lib\site-packages\nuitka\utils\SharedLibraries.py", line 162, in getWindowsDLLVersion
    codepages = array.array("H", ctypes.string_at(r.value, l.value))
    File "C:\Users\user\AppData\Local\Programs\Python\Python37\Lib\ctypes\__init__.py", line 497, in string_at
    return _string_at(ptr, size)
    OSError: exception: access violation reading 0x00000000AFC253A0
> 
> 
>

**Comment by kayhayen** [comment]
I believe that has nothing to do with pipenv vs. virtualenv, but is a crash that has been reported, and I believe fixed on the develop branch.

I need to figure out, how develop release could be on PyPI, until then please use the git branch.

The crash ought to be rare, but apparently it is not. Let me know if that helps, because if it does not, then maybe there is more to be done in this field.

**Comment by kayhayen** [comment]
Lack of feedback, assuming it's good.
