### ISSUE TITLE
matplotlib: RuntimeError: Could not find the matplotlib data files

### ISSUE THREAD

**Issue by NathanVasquez** [Nuitka/Nuitka#393]
**Versions**

`$ python3 -m nuitka --version`
>0.6.3.1
Python: 3.6.8 (default, Apr 25 2019, 21:02:35) 
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64

`>>> sys.version`
>'3.6.8 (default, Apr 25 2019, 21:02:35) \n[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]'

`$ pip3 show matplotlib`
>Name: matplotlib
Version: 3.0.3
Summary: Python plotting package
Home-page: http://matplotlib.org
Author: John D. Hunter, Michael Droettboom
Author-email: matplotlib-users@python.org
License: PSF
Location: /usr/local/lib64/python3.6/site-packages
Requires: cycler, numpy, kiwisolver, python-dateutil, pyparsing
Required-by: 

**Installation**

`$ yum install python36`
`$ pip3 install Nuitka`
`$ pip3 install matplotlib`

**Issue**

I had a much bigger script but boiled it down to this gem of a one-liner:

`import matplotlib.pyplot as plt`

It compiled, although I did get the following warnings just prior to scons:

`$ python3 -m nuitka --standalone --show-progress --show-scons test_matplotlib.py`
> ...
Nuitka:INFO:Optimizing module '_codecs_hk', 2 more modules to go after that.
Nuitka:INFO:Optimizing module '_codecs_cn', 1 more modules to go after that.
Nuitka:INFO:Optimizing module '_bz2', 0 more modules to go after that.
Nuitka:WARNING:Unresolved '\_\_import\_\_' call at '/usr/local/lib64/python3.6/site-packages/numpy/core/function_base.py:453' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '\_\_import\_\_' call at '/usr/local/lib64/python3.6/site-packages/numpy/lib/utils.py:366' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '\_\_import\_\_' call at '/usr/local/lib64/python3.6/site-packages/numpy/lib/utils.py:865' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '\_\_import\_\_' call at '/usr/local/lib64/python3.6/site-packages/numpy/lib/utils.py:923' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:INFO:Total memory usage before running scons: 775.68 MB (813355008 bytes):
...

Upon trying to run I get:

>Traceback (most recent call last):
  File "/test/test_matplotlib.dist/test_matplotlib.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/test/test_matplotlib.dist/matplotlib/\_\_init\_\_.py", line 1099, in <module matplotlib>
  File "/test/test_matplotlib.dist/matplotlib/\_\_init\_\_.py", line 940, in rc_params
  File "/test/test_matplotlib.dist/matplotlib/\_\_init\_\_.py", line 746, in matplotlib_fname
  File "/test/test_matplotlib.dist/matplotlib/\_\_init\_\_.py", line 744, in gen_candidates
  File "/test/test_matplotlib.dist/matplotlib/\_\_init\_\_.py", line 413, in wrapper
  File "/test/test_matplotlib.dist/matplotlib/\_\_init\_\_.py", line 690, in get_data_path
  File "/test/test_matplotlib.dist/matplotlib/\_\_init\_\_.py", line 684, in _get_data_path
RuntimeError: Could not find the matplotlib data files

**Comment by JorjMcKie** [comment]
I will need to modify the `numpy` plugin somewhat so these data get copied.
No big deal.

**Comment by JTT-JustTheTip** [comment]
Also getting this issue, any ideas on a fix?

**Comment by NathanVasquez** [comment]
As a temporary work around you can do the following:
```
cd /usr
find -name "mpl-data"
# mine shows ./local/lib64/python3.6/site-packages/matplotlib/mpl-data
```
in your python script add the following:
```
os.environ['MATPLOTLIBDATA'] = '/usr/local/lib64/python3.6/site-packages/matplotlib/mpl-data'`
```
Depending on what you're doing with matplotlib, you may have to add some more imports depending on what complains to you at runtime... I had to do the following as well:
```
import matplotlib.backends.backend_tkagg
import matplotlib.backends.backend_svg
```
(You don't have to actually do anything with those imports, they're just there to get nuitka to mark them as a needed import)

A little painful, but *shrugs* either that or wait around until it's fixed :)

**Comment by JorjMcKie** [comment]
Please give me a bit of more time:
The required changes to several plugins are underway.
I will then upload a ZIP file which you can use to (1) temporarily overwrite the `plugins` folder of your Nuitka installation, and (2) it will contain the required updated tools for standalone-compiling `matplotlib`, `cv2` and `tensorflow` scripts.

**Comment by JorjMcKie** [comment]
please also refer to [this](https://github.com/Nuitka/NUITKA-Utilities/issues/10).

**Comment by JorjMcKie** [comment]
@NathanVasquez - what is your current status?
Your issue should be addressed with the current nuitka version, resp. numpy plugin version ...

**Comment by jakams** [comment]
I ran into the same matplotlib data problem.

What version should address the problem?
I tried the current developer version (0.6.4rc6), but got the same result for the proposed minimal example from the first comment here.

**Comment by JorjMcKie** [comment]
@jakams - during compile: was there the message ``Copied 'mpl-data' from 'matplotlib' installation.``?
If **not**, you were not using the correct compile command:
You should use ``python get-hints.py yourscript.py`` **first**. After that do ``python nuitka-hints.py yourscript.py``.

The first step creates a logfile of all imports your script is doing. The second (the actual compile) is using this log to determine the required plugins and any additional plugin options to configure the appropriate compile parameters.

**Comment by jakams** [comment]
I didn't do it this way. I'll try it now.

**Comment by jakams** [comment]
I cant find much info on hinting...
Is there a hinting file missing in your comment: https://github.com/Nuitka/NUITKA-Utilities/issues/10#issuecomment-493712297

I found and used hinting.rar from 4 days ago (https://github.com/Nuitka/Nuitka/issues/364#issuecomment-498027642)

I get the following error:

> D:\test>python get-hints.py test_matplotlib.py
Call cleaning has removed 496 items.

D:\test>python nuitka-hints.py test_matplotlib.py
NUITKA is compiling 'test_matplotlib.py' with these options:
 --standalone
 --remove-output
 --experimental=use_pefile
 --recurse-none
 --disable-dll-dependency-cache

Nuitka:INFO: 'hinted-mods.py' is adding the following options:
Nuitka:INFO: --enable-plugin=numpy=matplotlib
Nuitka:INFO: --enable-plugin=tk-inter
Nuitka:INFO: --recurse-to for 248 imported modules.
Nuitka:INFO:
Nuitka:INFO:User plugin 'hinted-mods.py' loaded.
Nuitka:INFO:Injecting plug-in based pre load code for module 'tkinter':
Nuitka:INFO:    Need to make sure we set environment variables for TCL.
Nuitka:INFO: drop site
Nuitka:INFO: drop IPython
Problem with statement at C:\Users\Jaka\Anaconda3\lib\site-packages\matplotlib\p
yplot.py:122:
->             from IPython.core.pylabtools import backend2gui

Problem with statement at C:\Users\Jaka\Anaconda3\lib\site-packages\matplotlib\p
yplot.py:98:
->         if 'IPython' in sys.modules:

Problem with statement at C:\Users\Jaka\Anaconda3\lib\site-packages\matplotlib\p
yplot.py:97:
->     try:

Problem with statement at C:\Users\Jaka\Anaconda3\lib\site-packages\matplotlib\p
yplot.py:82:
-> def install_repl_displayhook():

Problem with statement at C:\Users\Jaka\Anaconda3\lib\site-packages\matplotlib\p
yplot.py:82:
-> def install_repl_displayhook():

Nuitka:INFO:Interrupted while working on '<Node 'COMPILED_PYTHON_MODULE' with {'
filename': 'C:\\Users\\Jaka\\Anaconda3\\lib\\site-packages\\matplotlib\\pyplot.p
y', 'package': 'matplotlib', 'name': 'pyplot'}>'.
Traceback (most recent call last):
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\__main__.py", line 184, in <module>
    main()
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\__main__.py", line 177, in main
    MainControl.main()
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\MainControl.py", line 746, in main
    main_module = createNodeTree(filename=filename)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\MainControl.py", line 141, in createNodeTree
    Optimization.optimize(main_module.getOutputFilename())
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\optimizations\Optimization.py", line 542, in optimize
    makeOptimizationPass(initial_pass=True)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\optimizations\Optimization.py", line 456, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\optimizations\Optimization.py", line 167, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\optimizations\Optimization.py", line 100, in optimizeCompiledPythonModule
    module.computeModule()
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\nodes\ModuleNodes.py", line 489, in computeModule
    trace_collection=self.trace_collection
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\nodes\StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\nodes\FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\optimizations\TraceCollections.py", line 550, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\nodes\AssignNodes.py", line 267, in computeStatement
    trace_collection.onExpression(self.getAssignSource())
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\optimizations\TraceCollections.py", line 531, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\nodes\ExpressionBases.py", line 980, in computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\optimizations\TraceCollections.py", line 531, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\nodes\FunctionNodes.py", line 830, in computeExpressionRaw
    function_body.computeFunctionRaw(trace_collection)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\nodes\FunctionNodes.py", line 384, in computeFunctionRaw
    self.computeFunction(trace_collection)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\nodes\FunctionNodes.py", line 397, in computeFunction
    trace_collection=trace_collection
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\nodes\StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\optimizations\TraceCollections.py", line 550, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\nodes\TryNodes.py", line 117, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\nodes\StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\nodes\FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\optimizations\TraceCollections.py", line 550, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\nodes\TryNodes.py", line 117, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\nodes\StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\optimizations\TraceCollections.py", line 550, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\nodes\ConditionalNodes.py", line 576, in computeStatement
    branch_yes_collection.computeBranch(branch=yes_branch)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\optimizations\TraceCollections.py", line 730, in computeBranch
    result = branch.computeStatementsSequence(trace_collection=self)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\nodes\StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\optimizations\TraceCollections.py", line 550, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\nodes\AssignNodes.py", line 267, in computeStatement
    trace_collection.onExpression(self.getAssignSource())
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\optimizations\TraceCollections.py", line 531, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\nodes\ExpressionBases.py", line 1050, in computeExpressionRaw
    expression = trace_collection.onExpression(expression=sub_expression)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\optimizations\TraceCollections.py", line 531, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\nodes\ExpressionBases.py", line 999, in computeExpressionRaw
    return self.computeExpression(trace_collection=trace_collection)
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\nodes\ImportNodes.py", line 401, in computeExpression
    trace_collection=trace_collection, module_name=imported_module_name
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\nodes\ImportNodes.py", line 280, in _attemptRecursion
    module_package=module_package,
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\nodes\ImportNodes.py", line 199, in _consider
    module_kind=module_kind,
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\importing\Recursion.py", line 181, in decideRecursion
    module_filename, module_name, module_package, module_kind
  File "C:\Users\Jaka\Anaconda3\lib\site-packages\nuitka-0.6.4rc6-py3.6.egg\nuit
ka\plugins\Plugins.py", line 240, in onModuleEncounter
    module_filename, module_name, module_package, module_kind
  File "hinted-mods.py", line 294, in onModuleEncounter
    import_set = self.ImplicitImports.getImportsByFullname(module_package)
AttributeError: 'NuitkaPluginPopularImplicitImports' object has no attribute 'ge
tImportsByFullname'

**Comment by JorjMcKie** [comment]
Hm, your scripts are correctly configured, but one component in your Nuitka version is incorrect. Don't know why this is so. I recommend you take the plugins directory contained in the following ZIP and copy it over to your installation's Nuitka plugins folder - just to see if this solves your issue.

Independently we will look into what is happening in the Nuitka distribution.
[hinting.zip](https://github.com/Nuitka/Nuitka/files/3263714/hinting.zip)

**Comment by JorjMcKie** [comment]
But as you can see from your (unsuccessful) compile log: the numpy plugin must be used with option matplotlib, and you also need plugin tk-inter.
If you compile your script in the "normal" way mimiking these options, you should be successful ok ...

**Comment by JorjMcKie** [comment]
What the hinting logic does:
* exclude everything except stuff which your script really needs during its execution

**Comment by jakams** [comment]
Overwriting nuitka's plugins seems to have done it.
compiling via hints seems to work, as well as using:
> python -m nuitka --standalone --remove-output --experimental=use_pefile --disable-dll-dependency-cache --enable-plugin=numpy=matplotlib --enable-plugin=tk-inter test_matplotlib.py

which is based on the hints. 

Hints seem very useful :).
I am off to attempt my original compilation...

By the way, maybe this helps someone, so I am posting it...
I did have a bunch of setbacks with compiling the minimal example. One of them was that I tried compiling on a different computer, that had an older matplotlib version (2.2.2).
It successfully compiled using hints, but running it produced:

> ModuleNotFoundError: No module named 'matplotlib.backends.backend_qt5agg'

I found:

> Nuitka:WARNING: Not recursing to unused 'matplotlib.backends.backend_qt5agg'

in the compilation warnings.

This seems to have gotten solved by upgrading matplotlib to the current 3.1.0. version.

**Comment by JorjMcKie** [comment]
Thanks for the feedback.

**Comment by hclivess** [comment]
I think `mpl-data` and all it includes needs to be added to nuitka similarly to this: https://github.com/Nuitka/Nuitka/issues/215

**Comment by JorjMcKie** [comment]
> I think `mpl-data` and all it includes needs to be added to nuitka similarly to this, because manual copying works: #215

The correct (!) version of numpy does that. Either you use hinted compiles or you specify ``--enable-plugin=numpy=matplotlib`` and it should work.
I sadly realized that release 0.0.4 and also the current development version did not pick up the most current plugins. If you want to try them out, copy the directory from this ZIP:
[hinting.zip](https://github.com/Nuitka/Nuitka/files/3285586/hinting.zip)
