### ISSUE TITLE
local import variable not showing up as <class 'module'>

### ISSUE THREAD

**Issue by NathanVasquez** [Nuitka/Nuitka#394]
**Versions**

`$ python3 -m nuitka --version`
>0.6.3.1
Python: 3.6.8 (default, Apr 25 2019, 21:02:35)
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64

`>>> sys.version`
>'3.6.8 (default, Apr 25 2019, 21:02:35) \n[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]'

**Installation**

`$ yum install python36`
`$ pip3 install Nuitka`

**Issue**

I'm trying to use an import idiom that works in python, but doesn't work once compiled. It seems to stem from the wrong type being returned.

Script to reproduce:

```
try:
    import local_import
except ImportError:
    local_import = None

if local_import is not None:
    print("Does not print when compiled")

print(type(local_import))
```
Note: _local\_import.py_ is an empty file in the same directory

Compiled with:

```
$ python3 -m nuitka \
  --standalone \
  --show-progress \
  --nofollow-imports \
  --show-scons \
  --explain-imports \
  test_local_import.py 
```

Actual Output:

><class 'NoneType'>

Expected Output:

>local\_import: Does not print when compiled
<class 'module'>

Looking at the output from --explain-imports, this seems to have found it just fine:

>findModule: Enter to search 'local_import' in package None level 0.
_findModule: Enter to search 'local_import'.
_findModuleInPath: Enter local_import in None
_findModuleInPath: Using search path ['/test/import_test', '/test/import_test', '.', '/usr/lib64/python36.zip', '/usr/lib64/python3.6', '/usr/lib64/python3.6/lib-dynload', '/usr/local/lib64/python3.6/site-packages', '/usr/local/lib/python3.6/site-packages', '/usr/lib64/python3.6/site-packages', '/usr/lib/python3.6/site-packages'] for None
Candidates OrderedSet([('/test/import_test', 1, '/test/import_test/local_import.py'), ('.', 1, './local_import.py')])
_findModuleInPath: _findModuleInPath2 gave /test/import_test/local_import.py
findModule: Found absolute imported module 'local_import' in filename '/test/import_test/local_import.py':

It seems this is a bit of a corner case... All of the following independently work fine:
- Using this idiom with a standard package like `os`
- compiling with `--follow-import-to=local_import`
- compiling without `--nofollow-imports`

**Comment by kayhayen** [comment]
Maybe I am stupid, but when you ask it to not include the module, why should it not raise `ImportError` on them? It becomes None, due to you catching it and setting it that way. And what module value do you expect there, without including it?

**Comment by NathanVasquez** [comment]
Ahhhhh. I was totally misunderstanding what that flag meant. Gotchya.
