### ISSUE TITLE
python-iptables aka iptc hidden import of libxtwrapper.so

### ISSUE THREAD

**Issue by drzraf** [Nuitka/Nuitka#398]
The [whitelist](https://github.com/Nuitka/Nuitka/blob/master/nuitka/plugins/standard/ImplicitImports.py) may need to include the [hidden import](https://github.com/ldx/python-iptables/blob/master/iptc/xtables.py#L828) of a C-library within `iptc.xtables`:
`_lib_xtwrapper, _ = find_library("xtwrapper")`
See also https://github.com/ldx/python-iptables/issues/182

By the way, I failed to pinpoint **which** nuitka command-line `--include-*` argument provides direct access to `locateDLL` and ability to forcefully include this specific object in the resulting executable.

**Comment by kayhayen** [comment]
Although Python extension modules are DLLs, on Windows (and macOS I think) named differently, not every DLL is or not will be found via import mechanisms. This function seems to be about DLLs.


https://github.com/Nuitka/Nuitka/blob/5b0db9f598bb486a0a7210c74eddb7370da75895/nuitka/plugins/standard/ImplicitImports.py#L515

As you can see, this is relatively little used. Often, PyQt5, etc. have dedicated plugins, but if it's only that, put it there and please make a PR.

Yours,
Kay
