### ISSUE TITLE
Nuitka on MacOS with tensorflow 

### ISSUE THREAD

**Issue by vprelovac** [Nuitka/Nuitka#402]
This is not an issue per se, just documenting my experience using Nuitka on MacOS for the first time in case someone else encounters the same issues.

OSX version: 10.14.5
Python version: miniconda - didnt work; brew installed python 3.7.3 worked OK
Nuitka version: latest dev Nuitka-0.6.4rc5

First had the 
`Error, call to 'install_name_tool' to fix Python library path failed.`

problem as referenced in https://github.com/Nuitka/Nuitka/issues/94

**I have solved this by removing miniconda installation of python, and installing python with brew as suggested in the issue.**

Next had the following issue:

```
Scons command: /usr/local/Cellar/python/3.7.3/bin/python3.7 -W ignore /usr/local/lib/python3.7/site-packages/nuitka/build/inline_copy/bin/scons.py -f /usr/local/lib/python3.7/site-packages/nuitka/build/SingleExe.scons --jobs 20 --warn=no-deprecated --no-site-dir --debug=explain name=test_model result_name=test_model source_dir=test_model.build debug_mode=false python_debug=false unstripped_mode=false module_mode=false full_compat=false experimental= trace_mode=false python_version=3.7 target_arch=x86_64 python_prefix=/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7 nuitka_src=/usr/local/lib/python3.7/site-packages/nuitka/build nuitka_cache=/Users/prelovac/Library/Caches/Nuitka module_count=2 result_exe=test_model.bin show_scons=true abiflags=m
scons: Reading SConscript files ...
SCONS:  Tools= ['default']
Scons CC 'gcc' version check:
Scons CC 'gcc' version check gives '4.2.1' from '4.2.1'
Scons CC 'cc' version check:
Scons CC 'cc' version check gives '10.0.1' from 'Apple LLVM version 10.0.1 (clang-1001.0.46.4)'
Scons CC 'g++' version check:
Scons CC 'g++' version check gives '4.2.1' from '4.2.1'
Initial CC: gcc
Initial CCVERSION: 4.2.1
Initial CXX: g++
Initial CXXVERSION: 4.2.1
SCONS:  Picked compiler: clang
SCONS:  Picked name: clang
Scons compiler: Using /usr/bin/clang 
Scons: Using resource mode: code
scons: Told to run compilation on 20 CPUs.
Scons: Launching target: ['test_model.bin']
scons: done reading SConscript files.
scons: Building targets ...
....

scons: building `test_model.bin' because it doesn't exist
clang -o test_model.bin -z noexecstack -Wno-deprecated-declarations @"test_model.build/@sources.tmp" -L/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib -lm -lpython3.7m
ld: unknown option: -z
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [test_model.bin] Error 1
scons: building terminated because of errors.
```

with

```
clang -v
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

ld -v
@(#)PROGRAM:ld  PROJECT:ld64-450.3
BUILD 18:45:16 Apr  4 2019
configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
LTO support using: LLVM version 10.0.1, (clang-1001.0.46.4) (static support for 22, runtime is 22)
TAPI support using: Apple TAPI version 10.0.1 (tapi-1001.0.4.1)

```

Since this was in the last step and the cause was clear (-z noexecstack was not supported by the linker) I manually ran the last command excluding the '-z noexecstack' and it worked.

Did not investigate this further but this seemed unsupported by the linker (man ld | grep execstack returned nothing).

--

All in all I was checking if Nuitka could speed up a tensorflow model running on CPU. Compilation with --folow-imports took about 35 minutes (had to traverse the monster that tensorflow code is) and created a 28MB executable without any problems!

Here are the results:

Python 3.7.3: execution time **1m47s**
Python 3.7.3 + Nuitka: execution time **1m42s**

I did expect to see better results, but I guess tensorflow python libs were already heavily optimized.

**Comment by kayhayen** [comment]
This was a bad issue, no reproducer, wrong advice and is generally obsolete.

The package tensorflow should work now and CPython should be used.
