### ISSUE TITLE
--recompile-c-only should mention it "resumes"/"continues" the process

### ISSUE THREAD

**Issue by drzraf** [Nuitka/Nuitka#405]
I suggest that `--recompile-c-only` be aliased to either `--continue` or `--resume`.
Or that, alternatively, the documentation of  `--recompile-c-only` contains **continue** and/or **resume** since these are likely to be searched for when one experiences an interrupted compilation.

**Comment by kayhayen** [comment]
Hello,

that is not their purpose really, although I agree, that is what they can be used for. Right now it's a development hack, where generated code will not be written, but instead manual modifications will survive.

Need to think of this, you are right, this is very nearly such a feature.

Yours,
Kay

**Comment by kayhayen** [comment]
I think, I am not in favor of this, after some though. Rather I want to get Nuitka to be caching so heavily that this is no longer needed. For developing, the edit and compile feature is very useful. I will make the help more clear, that it's not for end users at all.
