### ISSUE TITLE
Nuitka doesn't work with trio.

### ISSUE THREAD

**Issue by leojay** [Nuitka/Nuitka#410]
I'm using Nuitka 0.6.3.1 and Python 3.6.5 in a venv environment on a linux machine.
I installed Nuitka and trio with command:
```
pip install Nuitka trio
```

trio is an async library.
https://github.com/python-trio/trio

I have a file ```t.py``` like this:
```
import trio

async def main():
  print('hello')

trio.run(main)
```

If I run the script directly, everything is fine.
```
$ python t.py 
hello
```
But if I compile the script with Nuitka, it doesn't run anymore
```
$ python -m nuitka t.py 
Nuitka:WARNING:Not recursing to 'trio' (/home/leojay/test/py3test/lib/python3.6/site-packages/trio), please specify --nofollow-imports (do not warn), --follow-imports (recurse to all), --nofollow-import-to=trio (ignore it), --follow-import-to=trio (recurse to it) to change.
$ ./t.bin
Traceback (most recent call last):
  File "/home/leojay/test/py3test/t.py", line 6, in <module>
    trio.run(main)
  File "/home/leojay/test/py3test/lib/python3.6/site-packages/trio/_core/_run.py", line 1430, in run
    run_impl(runner, async_fn, args)
  File "/home/leojay/test/py3test/lib/python3.6/site-packages/trio/_core/_run.py", line 1579, in run_impl
    runner.task_exited(task, final_outcome)
  File "/home/leojay/test/py3test/lib/python3.6/site-packages/trio/_core/_run.py", line 1064, in task_exited
    raise TrioInternalError
trio.TrioInternalError

```

I expect the script to output ```hello```, instead of throwing an exception.
Can you please take a look at this?
Thanks!

Leo

**Comment by leojay** [comment]
Another problem I encountered is that, when compiling ```t.py```, if I add ```--follow-import-to=trio```, the compiled program crashes with a different error:
```
$ python -m nuitka --follow-import-to=trio t.py 
Nuitka:WARNING:Not recursing to 'async_generator' (/home/leojay/test/py3test/lib/python3.6/site-packages/async_generator), please specify --nofollow-imports (do not warn), --follow-imports (recurse to all), --nofollow-import-to=async_generator (ignore it), --follow-import-to=async_generator (recurse to it) to change.
Nuitka:WARNING:Not recursing to 'idna' (/home/leojay/test/py3test/lib/python3.6/site-packages/idna), please specify --nofollow-imports (do not warn), --follow-imports (recurse to all), --nofollow-import-to=idna (ignore it), --follow-import-to=idna (recurse to it) to change.
Nuitka:WARNING:Not recursing to 'attr' (/home/leojay/test/py3test/lib/python3.6/site-packages/attr), please specify --nofollow-imports (do not warn), --follow-imports (recurse to all), --nofollow-import-to=attr (ignore it), --follow-import-to=attr (recurse to it) to change.
Nuitka:WARNING:Not recursing to 'outcome' (/home/leojay/test/py3test/lib/python3.6/site-packages/outcome), please specify --nofollow-imports (do not warn), --follow-imports (recurse to all), --nofollow-import-to=outcome (ignore it), --follow-import-to=outcome (recurse to it) to change.
Nuitka:WARNING:Not recursing to 'contextvars' (/home/leojay/test/py3test/lib/python3.6/site-packages/contextvars), please specify --nofollow-imports (do not warn), --follow-imports (recurse to all), --nofollow-import-to=contextvars (ignore it), --follow-import-to=contextvars (recurse to it) to change.
Nuitka:WARNING:Not recursing to 'sniffio' (/home/leojay/test/py3test/lib/python3.6/site-packages/sniffio), please specify --nofollow-imports (do not warn), --follow-imports (recurse to all), --nofollow-import-to=sniffio (ignore it), --follow-import-to=sniffio (recurse to it) to change.
Nuitka:WARNING:Not recursing to 'sortedcontainers' (/home/leojay/test/py3test/lib/python3.6/site-packages/sortedcontainers), please specify --nofollow-imports (do not warn), --follow-imports (recurse to all), --nofollow-import-to=sortedcontainers (ignore it), --follow-import-to=sortedcontainers (recurse to it) to change.
$ ./t.bin 
Traceback (most recent call last):
  File "/home/leojay/test/py3test/t.py", line 1, in <module>
    import trio
  File "/home/leojay/test/py3test/lib/python3.6/site-packages/trio/__init__.py", line 18, in <module trio>
    from ._core import (
  File "/home/leojay/test/py3test/lib/python3.6/site-packages/trio/_core/__init__.py", line 29, in <module trio._core>
    from ._run import *
  File "/home/leojay/test/py3test/lib/python3.6/site-packages/trio/_core/_run.py", line 25, in <module trio._core._run>
    from ._entry_queue import EntryQueue, TrioToken
  File "/home/leojay/test/py3test/lib/python3.6/site-packages/trio/_core/_entry_queue.py", line 6, in <module trio._core._entry_queue>
    from .. import _core
ImportError: cannot import name '_core'
```

**Comment by JorjMcKie** [comment]
This probably can be resolved with appropriate implicit imports.

**Comment by kayhayen** [comment]
Not sure, he is not using standalone mode, merely acceleration, in which case it ought to fall back to file system for missing ones, or so I am thinking. For the main problem, there is an async issue that I will be working on these days and it might be causing this one, so I would defer this issue for now.

But maybe it is doing nasty stuff as a module, you might want to give your hinter a try to see if it cheats somehow @JorjMcKie as it is also a powerful debugging tool

**Comment by JorjMcKie** [comment]
It definitely does cheat!
Its imports go crisscross up and down the package levels, and most of the modules start with a single underscore. And all this as a pure Python package ... chapeau!

**Comment by kayhayen** [comment]
Although Nuitka is compatible with that lone, relative imports up and down ought to work fine. :)

**Comment by JorjMcKie** [comment]
you are right - my remarks were indeed irrelevant.

When I set all `trio` components to "bytecode", and also when I make an **extension module** from `trio` the following exception occurs:

```
D:\Jorj\Desktop\Develop\nuitka>trio-test
Traceback (most recent call last):
  File "D:\Jorj\Desktop\Develop\nuitka\trio-test.py", line 8, in <module>
    trio.run(main)
  File "C:\Users\Jorj\AppData\Local\Programs\Python\Python37\lib\site-packages\trio\_core\_run.py", line 1430, in run
    run_impl(runner, async_fn, args)
  File "C:\Users\Jorj\AppData\Local\Programs\Python\Python37\lib\site-packages\trio\_core\_run.py", line 1579, in run_impl
    runner.task_exited(task, final_outcome)
  File "C:\Users\Jorj\AppData\Local\Programs\Python\Python37\lib\site-packages\trio\_core\_run.py", line 1064, in task_exited
    raise TrioInternalError
trio.TrioInternalError

D:\Jorj\Desktop\Develop\nuitka>
```

This indeed points to an async issue as you say.

**Comment by JorjMcKie** [comment]
If you are interested to see the hinter logfile:
[trio-test.log](https://github.com/Nuitka/Nuitka/files/3241221/trio-test.log)
 It is a condensed from of the ``hints.py`` logfile, only show the indentation level, the calls and their results.
Overall this looks harmless

**Comment by JorjMcKie** [comment]
BTW there are lots of ``from .. import  `` statements contained in the product. When I replace them with the actual name, the error mesages `` cannot import _core from `` go away and the exception from my preceeding post appears.
I can't image that this type of import statement imposes a problem to nuitka, right?

**Comment by kayhayen** [comment]
Well, @JorjMcKie I typically feel 2 distinct kind of surprises.

a) How can it be this ever worked.
b) How can this not work.

Many times the two are unjustified and I never resolve that. :)

Can you condense this into a reproducer? In tests/programs I think I have examples of programs doing the kind of thing, but I may have easily missed something with it.

Yours,
Kay

**Comment by JorjMcKie** [comment]
@kayhayen  - as you may deducted from my short CV, I do appreciate considerations in the area of science theory like yours ... ;-)

Talking from my experience however, a situation like this usually hints at unknown aspects or circumstances.

Anyway, I will continue to investigate this and come with a more complete diagnosis.

**Comment by JorjMcKie** [comment]
I re-installed trio in both, my Windows and Linux environment and re-run compile and test.

I am now back at the status of @leojay in both environments.
[trio-test-log.txt](https://github.com/Nuitka/Nuitka/files/3244774/trio-test-log.txt)

@kayhayen  - I believe this ``trio.TrioInternalError`` should first be resolved. Subsequent errors like this inability to find ``_core`` as a component of ``trio``, etc. have a fat chance to just be artefacts created by the initial problem.
At least I was not able to fool nuitka with ``from .. import xxx`` statements in a make-up circumstance.

Is there any place I might look into, or do you want to take this on by yourself?

**Comment by kayhayen** [comment]
Unfortunately I didn't the have time to look into these perfectly reproducible issues. You can give it a go, or wait until we know we are not wasting our time. Obviously that kind of error to find a "_core" is going to be very unrelated to what I am talking about, which `async` iteration interchangeability with pure Python.

**Comment by leojay** [comment]
Hi,

I managed to reproduce the second problem with relatively simple code.
Here is my code structure:
```
$ tree
.
├── a
│   ├── b
│   │   ├── c.py
│   │   └── __init__.py
│   └── __init__.py
└── atest.py
```
Here are the contents of all files:
```
$ cat atest.py 
import a
$ cat a/__init__.py
from .b import *
$ cat a/b/__init__.py 
def hello():
    print('hello from b')

from .c import *
$ cat a/b/c.py 
from .. import b
b.hello()
```

When running the code directly, everything is fine:
```
$ python atest.py 
hello from b
```
But when running the compiled code, it shows an import error:
```
$ python -m nuitka atest.py --follow-import-to=a
$ ./atest.bin 
Traceback (most recent call last):
  File "/home/leo/test/triotest/importtest/atest.py", line 1, in <module>
    import a
  File "/home/leo/test/triotest/importtest/a/__init__.py", line 1, in <module a>
    from .b import *
  File "/home/leo/test/triotest/importtest/a/b/__init__.py", line 4, in <module a.b>
    from .c import *
  File "/home/leo/test/triotest/importtest/a/b/c.py", line 1, in <module a.b.c>
    from .. import b
ImportError: cannot import name 'b' from 'a' (/home/leo/test/triotest/importtest/a/__init__.py)
```

Hope this helps.

Leo

**Comment by kayhayen** [comment]
Thanks, I should be able to take it from there.

**Comment by kayhayen** [comment]
The behavior Nuitka shows is correct for Python 2.7, but not for 3.5 or higher.

**Comment by kayhayen** [comment]
Seems it's a pretty fundamental issue though. The re-formulations seem all correct, however, when the module body is active, it doesn't set `_Py_PackageContext`, which should be `a.b` and would be needed to properly resolve the level 2, when it then attempts `__import__("", fromlist=("b",), level = 2)` but given no context, it probably just errors out.

For extension module loading, this is done, but not for normal compiled modules. I was thinking that the `__package__` of the using module works, and actually I recall that being necessary for imports to find their ways. Checking import Python code now.

**Comment by kayhayen** [comment]
Nah, I just forgot, it's looking at `__package__` from the `globals` argument, which we are giving, which is sort of correct, and that makes it all mysterious. I have checked that `a.b` wasn't set for Python either, so this brings it down to having no explanation why that import is not doing its job.

**Comment by kayhayen** [comment]
So, I found it, the `IMPORT_NAME_OR_MODULE` was getting the wrong module dictionary passed, namely the one it shall attempt to import from, instead of the one that is doing the import. For level 1 that is OK, but not for level 2 imports.

The fix will show up later today on factory and in a 0.6.4 release soon. 

The bug only affects 3.5 or higher as that feature is only there, and only when relative package imports are made that way, not normal name lookups.

I guess the issue got hihacked by us with this potentially unrelated bug, or will this be what it was about, but I will still keep you posted about the progress of that. I don't think a separate issue is needed.

Yours,
Kay

**Comment by JorjMcKie** [comment]
Great - congrats!
I will continue with this issue using that version.

**Comment by leojay** [comment]
Any updates on this? ETA?

**Comment by kayhayen** [comment]
Not sure what the status of Nuitka with latest trio is now. As I said, this got hijacked, and should be more addressable now.

**Comment by leojay** [comment]
I just tried with 
```
Nuitka==0.6.9.3
trio==0.17.0
```
on my Ubuntu 20.04 machine with Python 3.8.5. This time, I could compile the `t.py`, but failed to run the result file:
```
$ python -m nuitka t.py 
Nuitka:WARNING:Not recursing to 'trio' (/home/leo/test/nuitkatest/venv/lib/python3.8/site-packages/trio), please specify --nofollow-imports (do not warn), --follow-imports (recurse to all), --nofollow-import-to=trio (ignore it), --follow-import-to=trio (recurse to it) to change.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:WARNING: You are not using ccache.
$ ./t.bin 
Traceback (most recent call last):
  File "/home/leo/test/nuitkatest/t.py", line 6, in <module>
    trio.run(main)
  File "/home/leo/test/nuitkatest/venv/lib/python3.8/site-packages/trio/_core/_run.py", line 1928, in run
    raise runner.main_task_outcome.error
  File "/home/leo/test/nuitkatest/venv/lib/python3.8/site-packages/trio/_core/_run.py", line 1576, in init
    self.main_task = self.spawn_impl(
  File "/home/leo/test/nuitkatest/venv/lib/python3.8/site-packages/trio/_core/_run.py", line 1455, in spawn_impl
    coro.cr_frame.f_locals.setdefault(LOCALS_KEY_KI_PROTECTION_ENABLED, system_task)
AttributeError: 'NoneType' object has no attribute 'f_locals'

```

**Comment by luozikuan** [comment]
> I just tried with
> 
> ```
> Nuitka==0.6.9.3
> trio==0.17.0
> ```
> 
> on my Ubuntu 20.04 machine with Python 3.8.5. This time, I could compile the `t.py`, but failed to run the result file:
> 
> ```
> $ python -m nuitka t.py 
> Nuitka:WARNING:Not recursing to 'trio' (/home/leo/test/nuitkatest/venv/lib/python3.8/site-packages/trio), please specify --nofollow-imports (do not warn), --follow-imports (recurse to all), --nofollow-import-to=trio (ignore it), --follow-import-to=trio (recurse to it) to change.
> Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
> Nuitka-Scons:WARNING: You are not using ccache.
> $ ./t.bin 
> Traceback (most recent call last):
>   File "/home/leo/test/nuitkatest/t.py", line 6, in <module>
>     trio.run(main)
>   File "/home/leo/test/nuitkatest/venv/lib/python3.8/site-packages/trio/_core/_run.py", line 1928, in run
>     raise runner.main_task_outcome.error
>   File "/home/leo/test/nuitkatest/venv/lib/python3.8/site-packages/trio/_core/_run.py", line 1576, in init
>     self.main_task = self.spawn_impl(
>   File "/home/leo/test/nuitkatest/venv/lib/python3.8/site-packages/trio/_core/_run.py", line 1455, in spawn_impl
>     coro.cr_frame.f_locals.setdefault(LOCALS_KEY_KI_PROTECTION_ENABLED, system_task)
> AttributeError: 'NoneType' object has no attribute 'f_locals'
> ```

Same here, I'm using win10 x64, Nuitka==0.9.6, trio==0.21.0

**Comment by kayhayen** [comment]
If Trio was changed to store it on the `coro` object, rather than its frame, both being equally unique, it could work I think, but I don't have the knowledge nor time to do this.

**Comment by kayhayen** [comment]
We have a plugin that works around for a long time now, so this can be considered solved.
