### ISSUE TITLE
Force particular modules to be frozen, rather than compiled?

### ISSUE THREAD

**Issue by Varriount** [Nuitka/Nuitka#415]
Is there a way to force certain modules to be frozen, rather than compiled?

**Comment by Ben-Faessler** [comment]
I would like to try to help here. How would I have to proceed? Does freezing mean just copying the modules to the dist folder?

**Comment by kayhayen** [comment]
@Ben-Faessler there is demoteCompiledModuleToBytecode for which there is currently a hard coded decision which these are, and this is about adding command line patterns similar to the include or follow variety of options, that change this decision. It's actually relatively trivial, just a bunch of work.

There is a cross benefit with another thing you offered to help with, I will post there too.

**Comment by kayhayen** [comment]
The anti-bloat plugin allows a `bytecode` mode for its custom bloat modes. That can be used. It won't work well in all cases, which is why it's not made very public, but there you go, this is technically implemented.
