### ISSUE TITLE
openSUSE Pmw tests fail

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#420]
Using factory, with https://build.opensuse.org/package/show/devel:languages:python/python-pmw

(I note that the package doesnt have tests, so it could be that it is broken, I will investigate this)

```console
[  898s] Comparing output of 'PmwUsing.py' using '/usr/bin/python3' with flags silent, expect_success, standalone, remove_output, plugin_enable:pmw-freezer ...
[  917s] --- /usr/bin/python3 (stderr)
[  917s] +++ nuitka (stderr)
[  917s] 
[  917s] @@ -1 +1,4 @@
[  917s] 
[  917s] +Traceback (most recent call last):
[  917s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.3.1559901536.b3f9838b/tests/standalone/PmwUsing.dist/PmwUsing.py", line 20, in <module>
[  917s] +ModuleNotFoundError: No module named 'Pmw'
[  917s]  
[  917s] Exit codes 0 (CPython) != 1 (Nuitka)
[  917s] Error, outputs differed.
[  917s] Error exit! 1
```

**Comment by kayhayen** [comment]
@jayvdb did it work for Python2 though?

**Comment by kayhayen** [comment]
This touches the bundling code: https://build.opensuse.org/package/view_file/devel:languages:python/python-pmw/py36.patch?expand=1

**Comment by kayhayen** [comment]
Ok, that is probably it:

> Nuitka:WARNING:Cannot recurse to import module '../../../../usr/local/lib/python3.7/dist-packages/Pmw' (/usr/local/lib/python3.7/dist-packages/Pmw) because of 'SyntaxError'

These kinds of warnings are actually import to report. :)

**Comment by kayhayen** [comment]
I just pushed to factory the solution for this.

**Comment by kayhayen** [comment]
The release 0.6.8 was just made and contains the correction.
