### ISSUE TITLE
Problems decoding compiler output, got UnicodeError in SingleExe.scons

### ISSUE THREAD

**Issue by redstoneleo** [Nuitka/Nuitka#421]
I am working on Win7 32 bit in  simplfied Chinese version , I got UnicodeError in SingleExe.scons on line
`err = err.decode(sys.stdout.encoding)`
if replaced the line with 
`err = err.decode(locale.getpreferredencoding())`
the UnicodeError is gone.

**Comment by kayhayen** [comment]
Can you confirm my suspect that you were using the MSVC compiler?

This is indeed an interesting solution attempt. This has plagued users of Nuitka on Windows with locales and MSVC installed for them for a while. As it doesn't care about terminal encodings. This should be a good attempt.

**Comment by kayhayen** [comment]
I am adding this as an extra ball attempt in case of `UnicodeDecodeError` it will try that, so that is probably going to address the issue for good.

**Comment by redstoneleo** [comment]
I am using gcc compiler, not MSVC compiler.

**Comment by kayhayen** [comment]
Ok, interesting, anyway fix is on factory branch now. 

The instructions on https://nuitka.net/doc/factory.html are not working for pip, but otherwise will do. I shall try and make it not use the removed gitweb interface.

**Comment by kayhayen** [comment]
So this is in 0.6.5rc3, currently develop branch.

**Comment by kayhayen** [comment]
Released as 0.6.5
