### ISSUE TITLE
ImportError with PyQt5 and PySide2 both installed

### ISSUE THREAD

**Issue by redstoneleo** [Nuitka/Nuitka#425]
After freezed my application with
`python -m nuitka --standalone --mingw64 MainWindow.py --remove-output --plugin-enable=qt-plugins --nofollow-import-to=pyside2  --show-modules
`
 Running the executable leads to
```
D:\BaiduYunDownload\programming\Python\django-test\EngkuDict\MainWindow.dist>D:\
BaiduYunDownload\programming\Python\django-test\EngkuDict\MainWindow.dist\MainWi
ndow.exe
Traceback (most recent call last):
  File "D:\BaiduYunDownload\programming\Python\django-test\EngkuDict\MainWindow.
dist\MainWindow.py", line 15, in <module>
  File "D:\BaiduYunDownload\programming\Python\django-test\EngkuDict\MainWindow.
dist\Ui_MainWindow.py", line 9, in <module Ui_MainWindow>
ImportError
```

MainWindow.py, line 15
`from Ui_MainWindow import *`
Ui_MainWindow.py, line 9
`from PyQt5 import QtCore, QtGui, QtWidgets`

**Comment by kayhayen** [comment]
this looks good, unfortunately I have no access to a Windows box, could be that PyQt5 has new hidden dependency, this looks rather innocent.

**Comment by redstoneleo** [comment]
That may be caused by PIL, which have some imports  of PySide2(the official Qt binding for Python )， used in my project which  is based on PyQt5，so I guess Nuitka  get messy confronted with two version of Qt lib versions , this led the exception .

**Comment by kayhayen** [comment]
I don't think that can be it, and I agree with `--nofollow-import-to=pyside2`, notice that PySide and PySide2 are not supported currently.

But you could confirm my theory by downgrading PyQt to say 5.11.3 https://pypi.org/project/PyQt5/#history

Otherwise, I will need to reproduce this anyway, and as I said, looks straight like a missing implicit dependency or DLL need that was added recently.

**Comment by JorjMcKie** [comment]
@redstoneleo - if you want, send me your script pls. and I will try it on my Windows using "hinted compilation".
This will ensure that only those modules are being followed to, which the program actually imports during its execution. This prevents PySide and a lot of other stuff which just happens to be present in the source code gets in the way.

**Comment by redstoneleo** [comment]
My foregoing speculation is not correct . 
I have both PySide2 and PyQt5 installed , and I tested with [PyQt5WithPIL.py](https://gist.github.com/redstoneleo/fd260e89701912bb22b0533224d041fe).
First, I tried standalone executable making command :
`nuitka --standalone --mingw64 --remove-output --plugin-enable=qt-plugins  PyQt5WithPIL.py --show-progress ` 
eval with  `--nofollow-import-to=pyside2`:
`nuitka --standalone --mingw64 --remove-output --plugin-enable=qt-plugins  PyQt5WithPIL.py --show-progress --nofollow-import-to=pyside2`

1. 
I found an odd warning message during the process 
`Nuitka:INFO:    system Qt plug-ins, which may be from another Qt version.`
So it seems Nuitka cannot decide the right Qt plug-ins for PyQt5 once PySide2 installed alongside.
2.
After the process finished , I run the executable form console , got 
```
D:\BaiduYunDownload\programming\Python>PyQt5WithPIL.exe
Traceback (most recent call last):
  File "D:\BaiduYunDownload\programming\Python\PyQt5WithPIL.dist\PyQt5WithPIL.py
", line 6, in <module>
ImportError
```
But if I change the standalone executable making command to:
`nuitka --standalone --mingw64 --remove-output --plugin-enable=qt-plugins  PyQt5WithPIL.py --show-progress --nofollow-import-to=pyside2`
or rename the `PySide2 `directory (in `C:\Users\i\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\PySide2`) to `PySide20`， the final executable runs properly. I think this hint PySide2 prevents PyQt5 related Python script from making standalone executable for Windows  successfully.

3. 
I found the Nuitka generated executable wears old style user interface. For example , it freezed the above `PyQt5WithPIL.py` into  executable with the old look :
![image](https://user-images.githubusercontent.com/5896180/60104130-66ab4d80-9793-11e9-8d39-b45f56482298.png)
but  `python3 PyQt5WithPIL.py` gives the modern look :
![image](https://user-images.githubusercontent.com/5896180/60104068-4bd8d900-9793-11e9-8f2c-f0c2a45b76ee.png)
So how to tweak Nuitka to generate modern look executables?

**Comment by kayhayen** [comment]
There is a pull request that is about including styles for Qt. It got stuck and should be completed #363 that will fix the looks issue.

As for PySide2, that is of course bad. Can it be that PIL imports it.

As PySide2 is severely unsupported, we ought to consider taking measures against including it. I am not immediately sure that `--nofollow-import-to=PySide2` is not needed, it may not be case sensitive, I need to check, but I think it might be.

**Comment by redstoneleo** [comment]
I still got `ImportError` after set `--nofollow-import-to=PySide2`

**Comment by kayhayen** [comment]
The plugin got split in the last release, and I think previously stopped working for PySide, so this is fixed already.
