### ISSUE TITLE
implicit module errors

### ISSUE THREAD

**Issue by codeyman** [Nuitka/Nuitka#438]
This is similar to #416. I can't reopen that issue so creating a new issue.

```
$ python -m nuitka --follow-imports --standalone --follow-stdlib   -j 6 --show-progress test.py
...
Nuitka:INFO:Doing module local optimizations for 'tensorflow.python'.
Error, implicit module 'tensorflow.python.module' expected by 'tensorflow.python' not found.
```

```
(py3env)  (dev *)sridhar@sridhar-dev1:~/devel/ML_WC1/Sain$ python -m nuitka --version
**0.6.4**
Python: 3.6.7 (default, Feb 26 2019, 11:59:03)
Executable: /home/sridhar/devel/py3env/bin/python
OS: Linux
Arch: x86_64
```

```
(py3env)  (dev *)sridhar@sridhar-dev1:~/devel/ML_WC1/Sain$ python -c 'import tensorflow as tf; print(tf.__version__)'
**1.10.1**
```

**Comment by JorjMcKie** [comment]
Tensorflow versions differ greatly in terms of how they are structured internally. So this package is a moving target in terms of Nuitka support. With 1.10.1 you are also using a fairly old version ... According to my information, in version 2.0.0 a complete subpackage (contrib) will be gone.

That said, you **_need_** to use the ``tensorflow`` plugin before you can even hope to do successful standalone compilations. Is there a specific reason why you do not do that?

I have a bunch of changes for the implicit imports module pending to be included. You may want to try them by overwriting the ``plugins`` directory of your Nuitka installation with the one included in the following zip file.
[hinting.zip](https://github.com/Nuitka/Nuitka/files/3317709/hinting.zip)

The ``ImplicitImports.py`` module contained therein declares the majority of the tensorflow imports as optional, which should prevent Nuitka to be as strict as you have observed it,

I also recommend using "hinted compilation" and **not** using ``--folow-stdlib``. "Hinting" reverses the inclusion logic to "include nothing except what is used when your scripts is actually running".

**Comment by JorjMcKie** [comment]
Ah, forgot to mention, that using tensorflow also has implications on yet other plugins needed, the most important being ``numpy``, potentially with some options.
But depending on your script's need there may be yet others like ``sklearn``.
All this is detected by hinted compilation and the compilation appropriately configured.

**Comment by kayhayen** [comment]
Closing for lack of feedback.
