### ISSUE TITLE
PonyORM incompatible with Nuitka

### ISSUE THREAD

**Issue by andrewleech** [Nuitka/Nuitka#44]
I've found a runtime failure when trying to use a module compiled with nuitka which uses PonyORM for managing a sqlite database.
[PonyORM - Python ORM with beautiful query syntax](https://ponyorm.com/)

```
Traceback (most recent call last):
  File "C:\APP\app\resultsdb\__init__.py", line 109, in load
  File "<string>", line 2, in select
  File "C:\APP\app_packages\pony\utils\utils.py", line 58, in cut_traceback
    return func(*args, **kwargs)
  File "C:\APP\app_packages\pony\orm\core.py", line 5160, in select
    return make_query(args, frame_depth=3)
  File "C:\APP\app_packages\pony\orm\core.py", line 5147, in make_query
    tree, external_names, cells = decompile(gen)
  File "C:\APP\app_packages\pony\orm\decompiling.py", line 28, in decompile
    else: throw(TypeError)
  File "C:\APP\app_packages\pony\utils\utils.py", line 98, in throw
    raise exc
TypeError
```

Some initial diagnostics shows that it's really not likely to work, probably ever.... pony does some crazy introspection on the code to be able to use really convenient python syntax to generate sql queries.

Here's a really good description of how it work: https://stackoverflow.com/questions/16115713/how-pony-orm-does-its-tricks

And specifically:
https://github.com/ponyorm/pony/blob/orm/pony/orm/decompiling.py#L17
```
def decompile(x):
    cells = {}
    t = type(x)
    if t is types.CodeType: codeobject = x
    elif t is types.GeneratorType: codeobject = x.gi_frame.f_code
```
In my case, when it's running as a compiled module, "t" above is ` <class 'compiled_generator'>`
Even if I modify pony to accept this as a `types.GeneratorType` the object does not have the `x.gi_frame` attribute. 

I'm not particularly asking for this to be fixed, I've moved away from using PonyORM already (not even using a database anymore, switched to yaml with my `structured_config` module to manage)

I just wanted to document my findings in case others run into the same issue.

**Comment by kayhayen** [comment]
I think "gi_frame" is implemented. It is just delayed for when it is actually created. CPython might create the frame more immediately, whereas Nuitka does it only when it's actually first started. So that would be a difference. They ought to use "gi_code" though, which is faster too. Maybe you want to tell them that, because that is only better.

Also using "isinstance" (which Nuitka patches to accept compiled_generator too or "inspect.isgenerator" would be better, both would work.

The question is of course, what it wants to do with that code object. I think that is where it might have to fail.

**Comment by kayhayen** [comment]
Using the Nuitka plugin API it would be possible to force byte code compilation for modules that use PonyORM functions like "select".

Alternatively, Nuitka could attach bytecode for compiled functions too, bloating the size of binaries a bit, but probably not all that dramatic. Having that plugin controlled, we could combine that two, and it would work.

**Comment by kayhayen** [comment]
So eventually I will do it. If anyone wants to dive into this, very welcome. This looks like something you can easily do on the outskirts of Nuitka, plugin API, and getting bytecode attached to functions, both should be easy. "inspect.getcode()" with "compile" built-in might be good there. Not too difficult, just not on my schedule right now.
