### ISSUE TITLE
Scons: Problem with incompatible libraries (MinGW64, Nuitka, lpython27)

### ISSUE THREAD

**Issue by azinsh1988** [Nuitka/Nuitka#441]
Hello, I installed Nuitka using 
$ pip install Nuitka 
on Windows 10, 64 bit, 
And installed MinGW64 based on Nuitka user manual:
$ gcc --version
gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
$ python -m nuitka --version
0.6.4
Python: 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)]
Executable: C:\Python27\python.exe
OS: Windows
Arch: x86_64
When I'm running hello example by
$ python -m nuitka --recurse-all --follow-imports --mingw64 --show-progress hellooo.py
I'm getting

C:/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:\Users\user\AppData\Local\Nuitka\Nuitka\Cache\win_libs\2.7\3ae2bfd1f3810e1f8e63d12b6640d305/libpython27.a when searching for -lpython27

It gives me the hello.exe file which workes fine, but I'm curious why I'm getting this warning and is it important or can be ignored in bigger projects?

**Comment by kayhayen** [comment]
Woah, that is funny, you know that this library is in fact created specifically for use by the gcc linker, indeed for x86_64. 

Parts of your output however suggest using 32 bits. Can you provide me with the output with `--show-scons` for the hello world example, this would help me recognize what is going on very easily.

Yours,
Kay

**Comment by azinsh1988** [comment]
$ python -m nuitka --recurse-all --follow-imports --mingw64 --show-scons hello.py

Scons command: C:\Python27\python.exe -W ignore C:\Python27\lib\site-packages\nuitka\build\inline_copy\bin\scons.py -f C:\Python27\lib\site-packages\nuitka\build\SingleExe.scons --jobs 4 --warn=no-deprecated --no-site-dir --debug=explain show_scons=true cache_mode=true name=hello python_debug=false unstripped_mode=false full_compat=false module_mode=false module_count=2 result_exe=hello.exe debug_mode=false noelf_mode=true target_arch=x86_64 trace_mode=false result_name=hello nuitka_src=C:\Python27\lib\site-packages\nuitka\build mingw_mode=true nuitka_cache=C:\Users\user\AppData\Local\Nuitka\Nuitka\Cache python_prefix=C:\Python27 source_dir=hello.build experimental= python_version=2.7 arg_encoding=utf8
scons: Reading SConscript files ...
SCONS:  CC='C:\\MinGW64\\mingw64\\bin\\gcc.exe'
SCONS:  Tools= ['mingw']
Scons CC 'gcc' version check:
Scons CC 'gcc' version check gives '8.1.0' from '8.1.0'
Initial CC: gcc
Initial CCVERSION: 8.1.0
Initial CXX: g++
Initial CXXVERSION: None
SCONS:  Picked compiler: C:\MinGW64\mingw64\bin\gcc.exe
SCONS:  Picked name: gcc.exe
Scons compiler: Using C:\MinGW64\mingw64\bin\gcc.exe
Scons CC 'C:\\MinGW64\\mingw64\\bin\\gcc.exe' version check:
Scons CC 'C:\\MinGW64\\mingw64\\bin\\gcc.exe' version check gives '8.1.0' from '8.1.0'
Scons: Detecting arch with : ['objdump', '-f', 'C:\\Python27\\python.exe']
Scons: Detecting arch with : ['objdump', '-f', 'C:\\MinGW64\\mingw64\\bin\\gcc.exe']
Scons: Using resource mode: win_resource
scons: Told to run compilation on 4 CPUs.
scons: Unable to find ccache.exe, consider user manual.
scons: Using scons cache inside build directory.
Scons: Launching target: ['hello.exe']
scons: done reading SConscript files.
scons: Building targets ...
scons: building `hello.build\module.__main__.o' because it doesn't exist
C:\MinGW64\mingw64\bin\gcc.exe -o hello.build\module.__main__.o -c -std=c11 -fwrapv -fpartial-inlining -ffile-prefix-map=hello.build\static_src=C:\Python27\lib\site-packages\nuitka\build\static_src -fno-var-tracking -O3 -pipe -D_WIN32_WINNT=0x0501 -D_NUITKA_SYSFLAG_PY3K_WARNING=0 -D_NUITKA_SYSFLAG_DIVISION_WARNING=0 -D_NUITKA_SYSFLAG_UNICODE=0 -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -DMS_WIN64 -D_NUITKA_CONSTANTS_FROM_RESOURCE -D_NUITKA_FROZEN=0 -D_NUITKA_MODULE_COUNT=2 -D_NUITKA_EXE -IC:\Python27\include -IC:\Python27\PC -Ihello.build -IC:\Python27\lib\site-packages\nuitka\build\include -IC:\Python27\lib\site-packages\nuitka\build\static_src hello.build\module.__main__.c
scons: building `hello.build\__constants.o' because it doesn't exist
C:\MinGW64\mingw64\bin\gcc.exe -o hello.build\__constants.o -c -std=c11 -fwrapv -fpartial-inlining -ffile-prefix-map=hello.build\static_src=C:\Python27\lib\site-packages\nuitka\build\static_src -fno-var-tracking -O3 -pipe -D_WIN32_WINNT=0x0501 -D_NUITKA_SYSFLAG_PY3K_WARNING=0 -D_NUITKA_SYSFLAG_DIVISION_WARNING=0 -D_NUITKA_SYSFLAG_UNICODE=0 -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -DMS_WIN64 -D_NUITKA_CONSTANTS_FROM_RESOURCE -D_NUITKA_FROZEN=0 -D_NUITKA_MODULE_COUNT=2 -D_NUITKA_EXE -IC:\Python27\include -IC:\Python27\PC -Ihello.build -IC:\Python27\lib\site-packages\nuitka\build\include -IC:\Python27\lib\site-packages\nuitka\build\static_src hello.build\__constants.c
scons: building `hello.build\__frozen.o' because it doesn't exist
C:\MinGW64\mingw64\bin\gcc.exe -o hello.build\__frozen.o -c -std=c11 -fwrapv -fpartial-inlining -ffile-prefix-map=hello.build\static_src=C:\Python27\lib\site-packages\nuitka\build\static_src -fno-var-tracking -O3 -pipe -D_WIN32_WINNT=0x0501 -D_NUITKA_SYSFLAG_PY3K_WARNING=0 -D_NUITKA_SYSFLAG_DIVISION_WARNING=0 -D_NUITKA_SYSFLAG_UNICODE=0 -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -DMS_WIN64 -D_NUITKA_CONSTANTS_FROM_RESOURCE -D_NUITKA_FROZEN=0 -D_NUITKA_MODULE_COUNT=2 -D_NUITKA_EXE -IC:\Python27\include -IC:\Python27\PC -Ihello.build -IC:\Python27\lib\site-packages\nuitka\build\include -IC:\Python27\lib\site-packages\nuitka\build\static_src hello.build\__frozen.c
scons: building `hello.build\__helpers.o' because it doesn't exist
C:\MinGW64\mingw64\bin\gcc.exe -o hello.build\__helpers.o -c -std=c11 -fwrapv -fpartial-inlining -ffile-prefix-map=hello.build\static_src=C:\Python27\lib\site-packages\nuitka\build\static_src -fno-var-tracking -O3 -pipe -D_WIN32_WINNT=0x0501 -D_NUITKA_SYSFLAG_PY3K_WARNING=0 -D_NUITKA_SYSFLAG_DIVISION_WARNING=0 -D_NUITKA_SYSFLAG_UNICODE=0 -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -DMS_WIN64 -D_NUITKA_CONSTANTS_FROM_RESOURCE -D_NUITKA_FROZEN=0 -D_NUITKA_MODULE_COUNT=2 -D_NUITKA_EXE -IC:\Python27\include -IC:\Python27\PC -Ihello.build -IC:\Python27\lib\site-packages\nuitka\build\include -IC:\Python27\lib\site-packages\nuitka\build\static_src hello.build\__helpers.c
scons: building `hello.build\MainProgram.o' because it doesn't exist
C:\MinGW64\mingw64\bin\gcc.exe -o hello.build\MainProgram.o -c -std=c11 -fwrapv -fpartial-inlining -ffile-prefix-map=hello.build\static_src=C:\Python27\lib\site-packages\nuitka\build\static_src -fno-var-tracking -O3 -pipe -D_WIN32_WINNT=0x0501 -D_NUITKA_SYSFLAG_PY3K_WARNING=0 -D_NUITKA_SYSFLAG_DIVISION_WARNING=0 -D_NUITKA_SYSFLAG_UNICODE=0 -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -DMS_WIN64 -D_NUITKA_CONSTANTS_FROM_RESOURCE -D_NUITKA_FROZEN=0 -D_NUITKA_MODULE_COUNT=2 -D_NUITKA_EXE -IC:\Python27\include -IC:\Python27\PC -Ihello.build -IC:\Python27\lib\site-packages\nuitka\build\include -IC:\Python27\lib\site-packages\nuitka\build\static_src hello.build\MainProgram.c
scons: building `hello.build\CompiledCellType.o' because it doesn't exist
C:\MinGW64\mingw64\bin\gcc.exe -o hello.build\CompiledCellType.o -c -std=c11 -fwrapv -fpartial-inlining -ffile-prefix-map=hello.build\static_src=C:\Python27\lib\site-packages\nuitka\build\static_src -fno-var-tracking -O3 -pipe -D_WIN32_WINNT=0x0501 -D_NUITKA_SYSFLAG_PY3K_WARNING=0 -D_NUITKA_SYSFLAG_DIVISION_WARNING=0 -D_NUITKA_SYSFLAG_UNICODE=0 -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -DMS_WIN64 -D_NUITKA_CONSTANTS_FROM_RESOURCE -D_NUITKA_FROZEN=0 -D_NUITKA_MODULE_COUNT=2 -D_NUITKA_EXE -IC:\Python27\include -IC:\Python27\PC -Ihello.build -IC:\Python27\lib\site-packages\nuitka\build\include -IC:\Python27\lib\site-packages\nuitka\build\static_src hello.build\CompiledCellType.c
scons: building `hello.build\CompiledFunctionType.o' because it doesn't exist
C:\MinGW64\mingw64\bin\gcc.exe -o hello.build\CompiledFunctionType.o -c -std=c11 -fwrapv -fpartial-inlining -ffile-prefix-map=hello.build\static_src=C:\Python27\lib\site-packages\nuitka\build\static_src -fno-var-tracking -O3 -pipe -D_WIN32_WINNT=0x0501 -D_NUITKA_SYSFLAG_PY3K_WARNING=0 -D_NUITKA_SYSFLAG_DIVISION_WARNING=0 -D_NUITKA_SYSFLAG_UNICODE=0 -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -DMS_WIN64 -D_NUITKA_CONSTANTS_FROM_RESOURCE -D_NUITKA_FROZEN=0 -D_NUITKA_MODULE_COUNT=2 -D_NUITKA_EXE -IC:\Python27\include -IC:\Python27\PC -Ihello.build -IC:\Python27\lib\site-packages\nuitka\build\include -IC:\Python27\lib\site-packages\nuitka\build\static_src hello.build\CompiledFunctionType.c
scons: building `hello.build\CompiledMethodType.o' because it doesn't exist
C:\MinGW64\mingw64\bin\gcc.exe -o hello.build\CompiledMethodType.o -c -std=c11 -fwrapv -fpartial-inlining -ffile-prefix-map=hello.build\static_src=C:\Python27\lib\site-packages\nuitka\build\static_src -fno-var-tracking -O3 -pipe -D_WIN32_WINNT=0x0501 -D_NUITKA_SYSFLAG_PY3K_WARNING=0 -D_NUITKA_SYSFLAG_DIVISION_WARNING=0 -D_NUITKA_SYSFLAG_UNICODE=0 -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -DMS_WIN64 -D_NUITKA_CONSTANTS_FROM_RESOURCE -D_NUITKA_FROZEN=0 -D_NUITKA_MODULE_COUNT=2 -D_NUITKA_EXE -IC:\Python27\include -IC:\Python27\PC -Ihello.build -IC:\Python27\lib\site-packages\nuitka\build\include -IC:\Python27\lib\site-packages\nuitka\build\static_src hello.build\CompiledMethodType.c
scons: building `hello.build\CompiledGeneratorType.o' because it doesn't exist
C:\MinGW64\mingw64\bin\gcc.exe -o hello.build\CompiledGeneratorType.o -c -std=c11 -fwrapv -fpartial-inlining -ffile-prefix-map=hello.build\static_src=C:\Python27\lib\site-packages\nuitka\build\static_src -fno-var-tracking -O3 -pipe -D_WIN32_WINNT=0x0501 -D_NUITKA_SYSFLAG_PY3K_WARNING=0 -D_NUITKA_SYSFLAG_DIVISION_WARNING=0 -D_NUITKA_SYSFLAG_UNICODE=0 -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -DMS_WIN64 -D_NUITKA_CONSTANTS_FROM_RESOURCE -D_NUITKA_FROZEN=0 -D_NUITKA_MODULE_COUNT=2 -D_NUITKA_EXE -IC:\Python27\include -IC:\Python27\PC -Ihello.build -IC:\Python27\lib\site-packages\nuitka\build\include -IC:\Python27\lib\site-packages\nuitka\build\static_src hello.build\CompiledGeneratorType.c
scons: building `hello.build\CompiledFrameType.o' because it doesn't exist
C:\MinGW64\mingw64\bin\gcc.exe -o hello.build\CompiledFrameType.o -c -std=c11 -fwrapv -fpartial-inlining -ffile-prefix-map=hello.build\static_src=C:\Python27\lib\site-packages\nuitka\build\static_src -fno-var-tracking -O3 -pipe -D_WIN32_WINNT=0x0501 -D_NUITKA_SYSFLAG_PY3K_WARNING=0 -D_NUITKA_SYSFLAG_DIVISION_WARNING=0 -D_NUITKA_SYSFLAG_UNICODE=0 -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -DMS_WIN64 -D_NUITKA_CONSTANTS_FROM_RESOURCE -D_NUITKA_FROZEN=0 -D_NUITKA_MODULE_COUNT=2 -D_NUITKA_EXE -IC:\Python27\include -IC:\Python27\PC -Ihello.build -IC:\Python27\lib\site-packages\nuitka\build\include -IC:\Python27\lib\site-packages\nuitka\build\static_src hello.build\CompiledFrameType.c
scons: building `hello.build\CompiledCodeHelpers.o' because it doesn't exist
C:\MinGW64\mingw64\bin\gcc.exe -o hello.build\CompiledCodeHelpers.o -c -std=c11 -fwrapv -fpartial-inlining -ffile-prefix-map=hello.build\static_src=C:\Python27\lib\site-packages\nuitka\build\static_src -fno-var-tracking -O3 -pipe -D_WIN32_WINNT=0x0501 -D_NUITKA_SYSFLAG_PY3K_WARNING=0 -D_NUITKA_SYSFLAG_DIVISION_WARNING=0 -D_NUITKA_SYSFLAG_UNICODE=0 -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -DMS_WIN64 -D_NUITKA_CONSTANTS_FROM_RESOURCE -D_NUITKA_FROZEN=0 -D_NUITKA_MODULE_COUNT=2 -D_NUITKA_EXE -IC:\Python27\include -IC:\Python27\PC -Ihello.build -IC:\Python27\lib\site-packages\nuitka\build\include -IC:\Python27\lib\site-packages\nuitka\build\static_src hello.build\CompiledCodeHelpers.c
scons: building `hello.build\InspectPatcher.o' because it doesn't exist
C:\MinGW64\mingw64\bin\gcc.exe -o hello.build\InspectPatcher.o -c -std=c11 -fwrapv -fpartial-inlining -ffile-prefix-map=hello.build\static_src=C:\Python27\lib\site-packages\nuitka\build\static_src -fno-var-tracking -O3 -pipe -D_WIN32_WINNT=0x0501 -D_NUITKA_SYSFLAG_PY3K_WARNING=0 -D_NUITKA_SYSFLAG_DIVISION_WARNING=0 -D_NUITKA_SYSFLAG_UNICODE=0 -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -DMS_WIN64 -D_NUITKA_CONSTANTS_FROM_RESOURCE -D_NUITKA_FROZEN=0 -D_NUITKA_MODULE_COUNT=2 -D_NUITKA_EXE -IC:\Python27\include -IC:\Python27\PC -Ihello.build -IC:\Python27\lib\site-packages\nuitka\build\include -IC:\Python27\lib\site-packages\nuitka\build\static_src hello.build\InspectPatcher.c
scons: building `hello.build\MetaPathBasedLoader.o' because it doesn't exist
C:\MinGW64\mingw64\bin\gcc.exe -o hello.build\MetaPathBasedLoader.o -c -std=c11 -fwrapv -fpartial-inlining -ffile-prefix-map=hello.build\static_src=C:\Python27\lib\site-packages\nuitka\build\static_src -fno-var-tracking -O3 -pipe -D_WIN32_WINNT=0x0501 -D_NUITKA_SYSFLAG_PY3K_WARNING=0 -D_NUITKA_SYSFLAG_DIVISION_WARNING=0 -D_NUITKA_SYSFLAG_UNICODE=0 -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -DMS_WIN64 -D_NUITKA_CONSTANTS_FROM_RESOURCE -D_NUITKA_FROZEN=0 -D_NUITKA_MODULE_COUNT=2 -D_NUITKA_EXE -IC:\Python27\include -IC:\Python27\PC -Ihello.build -IC:\Python27\lib\site-packages\nuitka\build\include -IC:\Python27\lib\site-packages\nuitka\build\static_src hello.build\MetaPathBasedLoader.c
scons: building `hello.exe' because it doesn't exist
C:\MinGW64\mingw64\bin\gcc.exe -o hello.exe -Wl,--enable-auto-import -s -static-libgcc @"hello.build\@sources.tmp" -LC:\Users\user\AppData\Local\Nuitka\Nuitka\Cache\win_libs\2.7\3ae2bfd1f3810e1f8e63d12b6640d305 -lm -lShlwapi -lpython27
C:/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:\Users\user\AppData\Local\Nuitka\Nuitka\Cache\win_libs\2.7\3ae2bfd1f3810e1f8e63d12b6640d305/libpython27.a when searching for -lpython27
scons: done building targets.

**Comment by kayhayen** [comment]
I have just checked and the path your warning provides, exists for me, it's the only one there, and the `mingw32` path part seems harmless. My gcc 8.1 installation is a bit older, but does similar and will not give the warning. I will try and update my Python 2.7 to see if it has anything changed.

Because if it's right (i.e. does not use the generated link library), then it should not work, but since it does, question becomes how.

**Comment by kayhayen** [comment]
Crap, I cannot confirm the need to produce these libraries at all anymore, not even with Python 2.6 which I did not touch, or Anaconda, which has old gcc 5.3 only, now I think how about just removing it. Not needed with gcc 8.1, not with 7.3, why does it exist.

The commit that added it is from 2014 and titled "Added initial support for MinGW64". Checking timeline, 5.3 was released only later, 2015, probably MinGW64 wasn't yet on that version, hard to tell now. Afterwards it got unnecessary and wasn't noticed until today.

I am going to remove it and ask my Buildbots about it, as they cover a lot more use cases, but I have checked executable and module both.

Yours,
Kay

**Comment by azinsh1988** [comment]
Thanks. I'm going to wait for your answer.

**Comment by kayhayen** [comment]
So this is in 0.6.5rc3, currently develop branch.

**Comment by kayhayen** [comment]
Released as 0.6.5
