### ISSUE TITLE
I cannot get any performance improvement with nuitka(even it is slower than the original version)

### ISSUE THREAD

**Issue by junimnjw** [Nuitka/Nuitka#444]
*  Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

Linux

(AOTTest) junimnjw@neo-local-server:~/PycharmProjects/AOTTest$ python -m nuitka --version
0.6.4
Python: 3.7.3 (default, Mar 27 2019, 22:11:17) 
Executable: /home/junimnjw/anaconda3/envs/AOTTest/bin/python
OS: Linux
Arch: x86_64

I'd like to talk about the performance issue in nuitka. 
I made a simple python program that uses Numpy package and compared the original python program to the converted program (converted by Nuitka). 

The problem is that...
The result showed the AOTed program is much slower than the original one. 
does any body can explain me why the AOTed version of program showed the poor performance?
Is there any factor  I have to consider when I try to do AOT for my python code using Nuitka?

let me show you the result and the used sample program as below. 

1. Original Python Program result. 
/home/junimnjw/anaconda3/envs/AOTTest/bin/python /home/junimnjw/PycharmProjects/AOTTest/main.py
1553096182.8424668
Numpy Elapsed Time:28.90 msec
Total Elapsed Time:7218.78 msec

2. Compiled version with Nuitka. 
(AOTTest) junimnjw@neo-local-server:~/PycharmProjects/AOTTest$ ./main.bin 
1548688969.1353004
Numpy Elapsed Time:28.70 msec
Total Elapsed Time:8897.46 msec
(AOTTest) junimnjw@neo-local-serve

main.py

from my_package.my_module import MyClass
import time
import numpy as np
import random

def main():

    first_part_time = time.process_time()

    instance = MyClass()
    n = 5000000
    first_list = []
    second_list = []
    for i in range(n):
        first_list.append(random.randrange(1, n))
        second_list.append(random.randrange(1, n))

    first_array = np.array(first_list)
    second_array = np.array(second_list)

    second_part_time = time.process_time()

    print(instance.bare_numpy(first_array, second_array))

    last_part_time = time.process_time()

    print("Numpy Elapsed Time:%0.2f msec" % ((last_part_time - second_part_time)*1000))
    print("Total Elapsed Time:%0.2f msec" % ((last_part_time - first_part_time) * 1000))

if __name__ == "__main__":

    main()

**Comment by kayhayen** [comment]
Nuitka does not accelerate NumPy as it is C code.

Startup time for compiled programs might be worse. I do not know, but I often suspect it. Right now we do not investigate that.

Yours,
Kay
