### ISSUE TITLE
Compiled binary - HTTPSConnection Error

### ISSUE THREAD

**Issue by Nihlander** [Nuitka/Nuitka#445]
# Issue
Compiling a Python3 script which utilises http.client.HTTPSConnection() produces an executable binary however, the compilation warning detailed below is output.

The script executes successfully with no errors or warnings via Python3.

### Compile Methods Tested
`sudo python3 -m nuitka --follow-imports --recurse-all --standalone --show-progress ./input_buffer.py`

`sudo python3 -m nuitka --follow-imports --recurse-all --standalone --show-progress ./input_buffer.py`

`sudo python3 -m nuitka --follow-imports --include-plugin-directory=/usr/lib/python3/dist-packages/urllib3 --include-plugin-directory=/usr/lib/python3/dist-packages/chardet --include-plugin-directory=/usr/lib/python3/dist-packages/idna --standalone --show-progress ./input_buffer.py`

Executing the compilation with the `--include-plugin-directory` flags causes the below compilation warning not to be output however, the binary still outputs the python error detailed below.

### Compilation Warning
```
Nuitka:WARNING:Unresolved '__import__' call at '/usr/lib/python3/dist-packages/requests/packages.py:7' may require use of '--include-plugin-directory' or '--include-plugin-files'.
```

### Contents of /usr/lib/python3/dist-packages/requests/packages.py
```
import sys

# This code exists for backwards compatibility reasons.
# I don't like it either. Just look the other way. :)

for package in ('urllib3', 'idna', 'chardet'):
    locals()[package] = __import__(package)
    # This traversal is apparently necessary such that the identities are
    # preserved (requests.packages.urllib3.* is urllib3.*)
    for mod in list(sys.modules):
        if mod == package or mod.startswith(package + '.'):
            sys.modules['requests.packages.' + mod] = sys.modules[mod]

# Kinda cool, though, right?
```

### Binary Execution
The binary file executes and the below error is output.
```
Traceback (most recent call last):
  File "/home/ubuntu/input_buffer.py", line 68, in <module>
  File "/home/ubuntu/input_buffer.py", line 54, in main
  File "/home/ubuntu/input_buffer.py", line 20, in get_api_data
AttributeError: module 'http.client' has no attribute 'HTTPSConnection'
```

### Version Info
Nuitka: 0.6.4
Python: 3.6.8 (default, Jan 14 2019, 11:02:34)
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64

### Installation Method
Ubuntu Stable Repository

**Comment by kayhayen** [comment]
This was lacking a reproducer, which is probably it got ignored. I expect this to work well for a long time already.
