### ISSUE TITLE
scons: *** [MainWindow.build\__constants.o] Error 1

### ISSUE THREAD

**Issue by redstoneleo** [Nuitka/Nuitka#447]
command：
`nuitka --standalone --mingw64 --remove-output --enable-plugin=qt-plugins=sensible,styles  MainWindow.py --show-progress --nofollow-import-to=pyside2 --include-module=PyQt5.QtWebChannel --include-module=PyQt5.QtPrintSupport  --include-module=pytz --include-module=EngkuDict  --include-module=NewWords  --include-module=WordDefinition   --include-module=sqlparse  --debugger`

```
...
Nuitka:INFO:Total memory usage before running scons: 330.74 MB (346804224 bytes)
:
Nuitka:INFO:Missing optimization, used fallback: ('Lt', <class 'nuitka.nodes.sha
pes.BuiltinTypeShapes.ShapeTypeNoneType'>, <class 'nuitka.nodes.shapes.BuiltinTy
peShapes.ShapeTypeBytes'>)
cc1.exe: out of memory allocating 65536 bytes
scons: *** [MainWindow.build\__constants.o] Error 1
```

**Comment by kayhayen** [comment]
Please do not erase the issue template, but fill it.

Do not use --debugger, as it will generate more complex code that is slower.
