### ISSUE TITLE
I wonder about the message :"Nuitka:WARNING:Recursed to package 'my_package' twice."

### ISSUE THREAD

**Issue by junimnjw** [Nuitka/Nuitka#448]
Required Info | 
0.6.4
Python: 3.7.3 (default, Mar 27 2019, 22:11:17) 
Executable: /home/junimnjw/anaconda3/envs/python-neo-facedetection_with_aot/bin/python3.7
OS: Linux
Arch: x86_64

Hello. I am now trying to compile my own python package using Nuitka. 
I just wonder that the bellow warning message indicates something that I did wrong or not. 

Did I typed wrong for compiling my package? Why I am getting below warning message?

(python-neo-facedetection_with_aot) junimnjw@neo-local-server:~/PycharmProjects/python-neo-facedetection_with_aot$ python -m nuitka --module my_package --include-package=my_package
**Nuitka:WARNING:Recursed to package 'my_package' at '/home/junimnjw/PycharmProjects/python-neo-facedetection_with_aot/my_package' twice.**

the project tree is like below. 

![image](https://user-images.githubusercontent.com/35256480/60227519-a294fe80-98ca-11e9-95ff-fd35d7710bc2.png)

**Comment by kayhayen** [comment]
I think this one is actually described in the user manual. 

We compile the filename you give as a module, even if it is a package, giving an empty package. Then you get to force inclusion of a whole module, which makes it see the top level twice, ignoring it, which triggers the warning.

Closing, as this is only a question to be found via tag or google.
