### ISSUE TITLE
I am getting a build error while compiling a package

### ISSUE THREAD

**Issue by junimnjw** [Nuitka/Nuitka#449]
(python-neo-facedetection_with_aot) junimnjw@neo-local-server:~/PycharmProjects/python-neo-facedetection_with_aot$ nuitka --version
0.6.4
Python: 3.7.3 (default, Mar 27 2019, 22:11:17) 
Executable: /home/junimnjw/anaconda3/envs/python-neo-facedetection_with_aot/bin/python3.7
OS: Linux
Arch: x86_64

I am getting a build error while compiling my own package that imports 'numpy'.
I don't get still why it happened. (I am not familiar with Nuitk)
Please help me to figure the issue. 

Error Message:

(python-neo-facedetection_with_aot) junimnjw@neo-local-server:~/PycharmProjects/python-neo-facedetection_with_aot$ python -m nuitka --module my_package --include-package=numpy
Nuitka:WARNING:Unresolved '__import__' call at '/home/junimnjw/anaconda3/envs/python-neo-facedetection_with_aot/lib/python3.7/site-packages/numpy/core/function_base.py:453' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at '/home/junimnjw/anaconda3/envs/python-neo-facedetection_with_aot/lib/python3.7/site-packages/numpy/doc/__init__.py:11' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at '/home/junimnjw/anaconda3/envs/python-neo-facedetection_with_aot/lib/python3.7/site-packages/numpy/lib/utils.py:366' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at '/home/junimnjw/anaconda3/envs/python-neo-facedetection_with_aot/lib/python3.7/site-packages/numpy/lib/utils.py:865' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at '/home/junimnjw/anaconda3/envs/python-neo-facedetection_with_aot/lib/python3.7/site-packages/numpy/lib/utils.py:923' may require use of '--include-plugin-directory' or '--include-plugin-files'.
my_package.build/module.numpy.linalg.tests.test_linalg.c: In function ‘impl_numpy$linalg$tests$test_linalg$$$function_79_test_axis’:
my_package.build/module.numpy.linalg.tests.test_linalg.c:80726:18: internal compiler error: 세그멘테이션 오류
 static PyObject *impl_numpy$linalg$tests$test_linalg$$$function_79_test_axis( struct Nuitka_FunctionObject const *self, PyObject **python_pars )
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
scons: *** [my_package.build/module.numpy.linalg.tests.test_linalg.os] Error 1

**Comment by kayhayen** [comment]
This would be a gcc bug. It seems you are using gcc 7. If you can, get gcc 8.1, and if it persists, you can consider submitting a bug report to them. Also you can try out clang.

Also, out of curiosity, I would like to look at `numpy.linalg.tests.test_linalg.py`, please attach it as a zip file.

I have a strong suspect, that the issue can be worked around though on Nuitka level, therefore I will also put it to bug.

Yours,
Kay

Yours,
Kay

**Comment by kayhayen** [comment]
Lack of feedback
