### ISSUE TITLE
Nuitka can't compile anything using msvc 14.1

### ISSUE THREAD

**Issue by Keithcat1** [Nuitka/Nuitka#451]
Platform: Windows 7 64 bit
Python: 3.7.2
Nuitka: 0.6.5 - Dev
Virtual environment: None
Current compiler: msvc 14.1

Whenever I try to build any code with nuitka, it gives the same error.
Here is output from scons when trying to build.

nuitka --module --show-scons testme.py
Scons command: C:\python37\python.exe -W ignore C:\python37\lib\site-packages\nuitka-0.6.5rc2-py3.7.egg\nuitka\build\inline_copy\bin\scons.py -f C:\python37\lib\site-packages\nuitka-0.6.5rc2-py3.7.egg\nuitka\build\SingleExe.scons --jobs 4 --warn=no-deprecated --no-site-dir --debug=explain name=testme result_name=testme source_dir=testme.build debug_mode=false python_debug=false unstripped_mode=false module_mode=true full_compat=false experimental= trace_mode=false python_version=3.7 target_arch=x86_64 python_prefix=C:\python37 nuitka_src=C:\python37\lib\site-packages\nuitka-0.6.5rc2-py3.7.egg\nuitka\build nuitka_cache=C:\Users\You\AppData\Local\Nuitka\Nuitka\Cache module_count=2 cache_mode=true show_scons=true noelf_mode=true
scons: Reading SConscript files ...
SCONS:  Tools= ['default']

scons: warning: MSVC_USE_SCRIPT set to False, assuming environment set correctly.
File "C:\python37\lib\site-packages\nuitka-0.6.5rc2-py3.7.egg\nuitka\build\SingleExe.scons", line 497, in createEnvironment
Initial CC: cl
Initial CCVERSION: None
Initial CXX: $CC
Initial CXXVERSION: None
SCONS:  Picked compiler: cl
SCONS:  Picked name: cl
Scons compiler: Using C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe (MSVC 14.1)

Scons: Using resource mode: win_resource
scons: Told to run compilation on 4 CPUs.
scons: Unable to find clcache.exe, consider user manual.
scons: Using scons cache inside build directory.
Scons: Launching target: ['testme.pyd']
scons: done reading SConscript files.
scons: Building targets ...
scons: building `testme.build\module.testme.obj' because it doesn't exist
cl /Fotestme.build\module.testme.obj /c testme.build\module.testme.cpp /TP /nologo /EHsc /J /Gd /Ox /LD /D_NUITKA_SYSFLAG_BYTES_WARNING=0 /D_NUITKA_SYSFLAG_NO_SITE=0 /D_NUITKA_SYSFLAG_VERBOSE=0 /D_NUITKA_SYSFLAG_UTF8=0 /D_NUITKA_SYSFLAG_OPTIMIZE=0 /D__NUITKA_NO_ASSERT__ /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=0 /D_NUITKA_MODULE_COUNT=2 /D_NUITKA_MODULE /IC:\python37\include /IC:\python37\PC /Itestme.build /IC:\python37\lib\site-packages\nuitka-0.6.5rc2-py3.7.egg\nuitka\build\include /IC:\python37\lib\site-packages\nuitka-0.6.5rc2-py3.7.egg\nuitka\build\static_src
scons: building `testme.build\__constants.obj' because it doesn't exist
cl /Fotestme.build\__constants.obj /c testme.build\__constants.cpp /TP /nologo /EHsc /J /Gd /Ox /LD /D_NUITKA_SYSFLAG_BYTES_WARNING=0 /D_NUITKA_SYSFLAG_NO_SITE=0 /D_NUITKA_SYSFLAG_VERBOSE=0 /D_NUITKA_SYSFLAG_UTF8=0 /D_NUITKA_SYSFLAG_OPTIMIZE=0 /D__NUITKA_NO_ASSERT__ /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=0 /D_NUITKA_MODULE_COUNT=2 /D_NUITKA_MODULE /IC:\python37\include /IC:\python37\PC /Itestme.build /IC:\python37\lib\site-packages\nuitka-0.6.5rc2-py3.7.egg\nuitka\build\include /IC:\python37\lib\site-packages\nuitka-0.6.5rc2-py3.7.egg\nuitka\build\static_src
scons: building `testme.build\__frozen.obj' because it doesn't exist
cl /Fotestme.build\__frozen.obj /c testme.build\__frozen.cpp /TP /nologo /EHsc /J /Gd /Ox /LD /D_NUITKA_SYSFLAG_BYTES_WARNING=0 /D_NUITKA_SYSFLAG_NO_SITE=0 /D_NUITKA_SYSFLAG_VERBOSE=0 /D_NUITKA_SYSFLAG_UTF8=0 /D_NUITKA_SYSFLAG_OPTIMIZE=0 /D__NUITKA_NO_ASSERT__ /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=0 /D_NUITKA_MODULE_COUNT=2 /D_NUITKA_MODULE /IC:\python37\include /IC:\python37\PC /Itestme.build /IC:\python37\lib\site-packages\nuitka-0.6.5rc2-py3.7.egg\nuitka\build\include /IC:\python37\lib\site-packages\nuitka-0.6.5rc2-py3.7.egg\nuitka\build\static_src
scons: building `testme.build\__helpers.obj' because it doesn't exist
cl /Fotestme.build\__helpers.obj /c testme.build\__helpers.cpp /TP /nologo /EHsc /J /Gd /Ox /LD /D_NUITKA_SYSFLAG_BYTES_WARNING=0 /D_NUITKA_SYSFLAG_NO_SITE=0 /D_NUITKA_SYSFLAG_VERBOSE=0 /D_NUITKA_SYSFLAG_UTF8=0 /D_NUITKA_SYSFLAG_OPTIMIZE=0 /D__NUITKA_NO_ASSERT__ /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=0 /D_NUITKA_MODULE_COUNT=2 /D_NUITKA_MODULE /IC:\python37\include /IC:\python37\PC /Itestme.build /IC:\python37\lib\site-packages\nuitka-0.6.5rc2-py3.7.egg\nuitka\build\include /IC:\python37\lib\site-packages\nuitka-0.6.5rc2-py3.7.egg\nuitka\build\static_src
c:\python37\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directoryc:\python37\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directoryscons: *** [testme.build\__constants.obj] Error 2
scons: *** [testme.build\__frozen.obj] Error 2
c:\python37\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directoryc:\python37\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directoryscons: *** [testme.build\module.testme.obj] Error 2
scons: *** [testme.build\__helpers.obj] Error 2
scons: building terminated because of errors.

It feels like it might not be including files from the windows kits that I also have installed.
Judging by the command line parameters, Cython does this, and it compiles without any problems.
I'd still like to use Nuitka though, but it doesn't work with msvc for me.

**Comment by kayhayen** [comment]
Which environment have you activated when you compile, because I think it would have to be the problem, although normally they work from my experience.

> scons: warning: MSVC_USE_SCRIPT set to False, assuming environment set correctly.

If you don't do it, Scons picks it, and potentially better. The Windows SDK (which would be the one with `io.h` is normally well detected.

Yours,
Kay

**Comment by Keithcat1** [comment]
Hi,
I barely even knew about nuitka environments and I certainly didn't have a default set. SCons probably did that.
Come to think, that scons line, the one about nuitka_use_script_environment being set to false, wasn't there before.
Can you tell me how to set it to windows SDK so it loads io.h and other required files?

**Comment by kayhayen** [comment]
I am surprised to consider an Visual Studio 2017 installation without the SDK. No idea what is going on here.

**Comment by kayhayen** [comment]
The new release has a newer Scons, maybe it works better.

**Comment by kayhayen** [comment]
Using `Initial CC: cl` may well mean, it's compiling with the wrong architecture. That could mean it cannot open resources for it, although that's only a theory.

We are checking arches for MinGW64. Can you show its output too?

Yours,
Kay

**Comment by kayhayen** [comment]
Closing for lack of feedback and hope that new scons does the trick.

**Comment by programjio** [comment]
@kayhayen as reported in another bug thread this is the same issue i am also facing VS2019 used.
More details here if you wish to get the details https://github.com/Nuitka/Nuitka/issues/547

can you detail this what to do so that i can try with that ,i am also getting the same waring
what to set as environment variable please

@kayhayen  Which environment have you activated when you compile, because I think it would have to be the problem, although normally they work from my experience.

scons: warning: MSVC_USE_SCRIPT set to False, assuming environment set correctly.
