### ISSUE TITLE
How to Access Data Files along with Binary

### ISSUE THREAD

**Issue by jss-cmyk** [Nuitka/Nuitka#455]
I compiled a program successfully, but the the program cannot access data files along with it.
like open("./data.bin", "rb")

**Comment by jrnp97** [comment]
Hello, I was that problem when use static files on program to fix it I copy file(s) on specific path inside .exe directory, in your case you must move **data.bin** file to directory where has your *.exe* file, I hope work.

**Comment by kayhayen** [comment]
You should use `os.path.join(os.path.dirname(__file__), "data.bin")` as the filename. Using the `./` makes you dependent on the current directory, not a good idea.

**Comment by kayhayen** [comment]
Also, `pkgutil.get_data(package, resource)` is a good idea, ought to work too.
