### ISSUE TITLE
Console Window on MacOS

### ISSUE THREAD

**Issue by sekkit** [Nuitka/Nuitka#458]
There is a parameter for hiding Windows console.
But how to do it in MacOS?

**Comment by kayhayen** [comment]
So it can be done, but it's not trivial, hoping for a PR as I don't have access to macOS https://stackoverflow.com/questions/23861914/how-to-hide-terminal-window-in-mac-osx

**Comment by kayhayen** [comment]
The macOS has now a bundle mode and an option to disable the console using that.
