### ISSUE TITLE
Question: Possible to directly call C functions in a dynamic library?

### ISSUE THREAD

**Issue by briankendall** [Nuitka/Nuitka#463]
Does Nuitka provide a way for a compiled Python module to directly call a C function in a dynamic library, without having to make use of ctypes or another similar module?

(Apologies if the issue tracker is an inappropriate place to ask such a question.)

**Comment by kayhayen** [comment]
No, it does not. It is however part of the plan to understand `ctypes` well enough to ultimately turn its uses into direct C usage. This is still a bit of, but not impossible to happen.

**Comment by dbsxdbsx** [comment]
@kayhayen Just a similiar question. Is it possible to export function interface from a python module as a binary library, so that I can use the library in other programming language ?

**Comment by kayhayen** [comment]
You can create extension modules, and if you can load these by embedding Python in your language. That can be done according to Python documentation.

The GIL handling is not changed by compilation, your guess is wrong. The way around that is to use multiple processes, but not threads.

**Comment by dbsxdbsx** [comment]
@kayhayen, Does it mean that it is working like a cpython with GIL when running the binary program  wrapped by Nuitka?

**Comment by kayhayen** [comment]
@dbsxdbsx yes
