### ISSUE TITLE
 "can't find gendef.exe" in hello.py tutorial: Installed in conda env, on Win10, using m2w64-gcc

### ISSUE THREAD

**Issue by DanCodigaMWRA** [Nuitka/Nuitka#465]
I am on Windows 10 (x86_64) using Miniconda and python 3.6.7. I would like to install nuitka and the needed C compiler wholly within a conda env, and not have to adjust my path at all, nor have to set an environment variable, etc.

Is this possible? I thought the answer was yes, based on footnote 3 of the documentation at https://nuitka.net/doc/user-manual.html#installation, which states:

"Installation of matching MinGW64 is easiest if you have an Anaconda or Miniconda installation and execute <path_to_Anaconda>\Scripts\conda install m2w64-gcc libpython and then before you run Nuitka do setenv CC=<path_to_Anaconda>\Library\mingw-w64\bin\gcc.exe and then its use will be forced. Nuitka also uses it automatically, if you run it like this <path_to_Anaconda>\python -m nuitka ...."

That last sentence made me hopeful, as it seems to imply that nuitka will find and use the right compiler automatically.

So I created a conda env using a yml file (top priorty channel uses is conda-forge, in case that matters). Included in the new env (among lots of others such as numpy, pandas, matplotlib etc) are nuitka, m2w64-gcc, and libpython.

Then I activated this new conda env, and checked that I had gcc.exe (it is version 5.3.0) and nuitka (version 0.6.4). 

From within the new conda env, I tried to follow the first most basic tutorial case hello.py at https://nuitka.net/doc/user-manual.html#tutorial-setup-and-build-on-windows.

I execute "python hello.py" and it works fine, but when I try "python -m nuitka --mingw64 hello.py" I get the "cannot find gendef.exe" error. 

I can't tell if this means it is not finding the compiler at all, or just not finding gendef.

But I wonder if this means that I must set the CC environment variable and/or adjust my path after all? If so, you may want to adjust the way that footnote is written.

**Comment by DanCodigaMWRA** [comment]
Update. I set the CC environment variable to the correct gcc.exe file (path .../Library/mingw64/bin/gcc.exe) within my envs folder under miniconda files. Still same error, can't find gendef.exe. Seems like the problem of the missing gendef.exe is present even when the C compiler itself is found.

**Comment by DanCodigaMWRA** [comment]
Another update. I see the missing gendef.exe error has come up before: 
https://github.com/Nuitka/Nuitka/issues/35 

Here is the output in my case, when I use --show-scons:

python -m nuitka --standalone --mingw64 --show-scons hello.py

Scons command: C:\Users\Codiga_D\AppData\Local\Continuum\miniconda3\envs\EQ\python.exe -W ignore C:\Users\Codiga_D\AppData\Local\Continuum\miniconda3\envs\EQ\lib\site-packages\nuitka\build\inline_copy\bin\scons.py -f C:\Users\Codiga_D\AppData\Local\Continuum\miniconda3\envs\EQ\lib\site-packages\nuitka\build\SingleExe.scons --jobs 6 --warn=no-deprecated --no-site-dir --debug=explain name=hello result_name=hello.dist\hello source_dir=hello.build debug_mode=false python_debug=false unstripped_mode=false module_mode=false full_compat=false experimental= trace_mode=false python_version=3.6 target_arch=x86_64 python_prefix=C:\Users\Codiga_D\AppData\Local\Continuum\miniconda3\envs\EQ nuitka_src=C:\Users\Codiga_D\AppData\Local\Continuum\miniconda3\envs\EQ\lib\site-packages\nuitka\build nuitka_cache=C:\Users\Codiga_D\AppData\Local\Nuitka\Nuitka\Cache module_count=443 result_exe=hello.dist\hello.exe cache_mode=true standalone_mode=true frozen_modules=170 show_scons=true mingw_mode=true noelf_mode=true
scons: Reading SConscript files ...
SCONS:  CC='C:\\Users\\Codiga_D\\AppData\\Local\\Continuum\\miniconda3\\envs\\EQ\\Library\\mingw-w64\\bin\\gcc.exe'
SCONS:  Tools= ['mingw']
Scons CC 'gcc' version check:
Scons CC 'gcc' version check gives '5.3.0' from '5.3.0'
Initial CC: gcc
Initial CCVERSION: 5.3.0
Initial CXX: g++
Initial CXXVERSION: None
SCONS:  Picked compiler: C:\Users\Codiga_D\AppData\Local\Continuum\miniconda3\envs\EQ\Library\mingw-w64\bin\gcc.exe
SCONS:  Picked name: gcc.exe
Scons compiler: Using C:\Users\Codiga_D\AppData\Local\Continuum\miniconda3\envs\EQ\Library\mingw-w64\bin\gcc.exe
Scons CC 'C:\\Users\\Codiga_D\\AppData\\Local\\Continuum\\miniconda3\\envs\\EQ\\Library\\mingw-w64\\bin\\gcc.exe' version check:
Scons CC 'C:\\Users\\Codiga_D\\AppData\\Local\\Continuum\\miniconda3\\envs\\EQ\\Library\\mingw-w64\\bin\\gcc.exe' version check gives '5.3.0' from '5.3.0'
Scons: Creating Python library defs with: ['C:\\Users\\Codiga_D\\AppData\\Local\\Continuum\\miniconda3\\envs\\EQ\\Library\\mingw-w64\\bin\\gendef', '-', 'c:\\users\\codiga_d\\appdata\\local\\continuum\\miniconda3\\envs\\eq\\python36.dll']
Error, cannot find "gendef.exe" which is required though.

**Comment by kayhayen** [comment]
Please try the develop branch. I think I recently made changes that remove the use of gendef entirely.

**Comment by DanCodigaMWRA** [comment]
Thank you for your quick reply.

Can I install the develop branch within my conda env, using a conda command? 
If so ... can you advise me on what the syntax would be?

If not ... I guess I should wait until your next release-- disappointed because I'm eager to try nuitka, but I am not a dev, (I am looking for a tool that enables me to convert relatively complex python scripts in to executables, but have found major limitations when trying to use pyinstaller and cx_freeze, so nuitka seems like it may be a useful alternative.)

**Comment by kayhayen** [comment]
That should do: `pip install "https://github.com/Nuitka/Nuitka/archive/develop.zip"`

**Comment by DanCodigaMWRA** [comment]
Ok so I got the dev branch installed and it works on the hello.py file which is nice. 
Thank you for your help.
