### ISSUE TITLE
Nuitka segfaults in ld call on aarch64

### ISSUE THREAD

**Issue by itdaniher** [Nuitka/Nuitka#47]
Python3.6.3
Linux 4.4
GCC 7.2.0
Aarch64

trying to compile a simple 'hello world' with:

```pipenv run nuitka --show-scons --verbose print.py```

segfaults as per in a call to ld as per:

https://gist.github.com/itdaniher/6343be4097dd35e78df5df06b3f88c8b

note that my compiler / linker chain is tested-working, built python and the kernel from source.

**Comment by kayhayen** [comment]
Any segfault of "ld" is its own. For all I know, the Debian tool chain works fine with Nuitka.

**Comment by shubjain26** [comment]
Getting the same error, while compiling on Jetson Tx2 (aarch64)

@itdaniher did you find any workaround
```
gcc -o hello.dist/hello.exe -Wl,-R,'$ORIGIN' -Wl,--disable-new-dtags -Wl,-b -Wl,binary -Wl,hello.build/__constants.bin -Wl,-b -Wl,elf64-littleaarch64 -Wl,-defsym -Wl,constant_bin=_binary_hello_build___constants_bin_start hello.build/__frozen.o hello.build/module.__main__.o hello.build/__constants.o hello.build/__helpers.o hello.build/MainProgram.o hello.build/CompiledCellType.o hello.build/CompiledFunctionType.o hello.build/CompiledMethodType.o hello.build/CompiledGeneratorType.o hello.build/CompiledFrameType.o hello.build/CompiledCodeHelpers.o hello.build/InspectPatcher.o hello.build/MetaPathBasedLoader.o hello.build/fibers_gen.o -L/usr/lib -ldl -lpython2.7
collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
compilation terminated.
scons: *** [hello.dist/hello.exe] Error 1
scons: building terminated because of errors.

```

**Comment by kayhayen** [comment]
How about adding more memory, or swap file? Since you are having this on 64 bits, I wouldn't think it's a 2GB limit hit.

**Comment by itdaniher** [comment]
@shubjain26 I did not. I just stopped using Nuitka as I could not get it to behave and @kayhayen just chalked it up to ld.

**Comment by benelgiac** [comment]
Just so you know, even with the latest binutils 2.32 the problem is still there. At no point RAM is exhausted and I have a 16 GB swap file. Very quickly reproducible if you have a TX2.

**Comment by kayhayen** [comment]
@benelgiac You do realize, that a segmentation fault of `ld` when used with Nuitka is not a bug of Nuitka, but of `ld` and your specific binary? There is no way, I will debug `ld` crashes. But if it's reproducible, turn it into a minimal test case of ld and take it to the binutils maintainers.

**Comment by benelgiac** [comment]
Of course I do, I am not blaming anyone or asking you to debug anything but please consider that it's already the third tx2 user reporting the same issue, so probably it's worth understanding what's going on. Even if it has nothing to do with Nuitka, I think it would be useful if we could find a solution on this thread.

Since I cannot, am not able and do not want to even start considering looking into ld, I have tried to overcome the problem by installing **lld**, which should be a drop-in replacement for ld. I have compiled it and installed on TX2 and got an error as well, slightly better than a crash at least:

```
ld: error: unknown -format value: elf64-littleaarch64 (supported formats: elf, default, binary)
collect2: error: ld returned 1 exit status
```
Maybe this tells you something more than it tells me (i.e. lld is not very much a "drop-in" replacement)

Facts:
- ld version 1.30 segments on simple hello world nuitka compilation
- ld version 1.32 segments on simple hello world nuitka compilation
- lld version 9.0.0 gives error on simple hello world nuitka compilation
- I can successfully link other complex projects (i.e. OpenCV) on TX2 using both ld and lld
- I have successfully used the same version of nuitka on tx2 on previous version of TX2 linux (based on ubuntu 16.04 and supposedly with a different version of ld)

If I will be able to spend more time on this, I will try to make it reproducible without nuitka.

**Comment by kayhayen** [comment]
@benelgiac You might want to try and change `SingleExe.scons` so it doesn't use `resource_mode = "linker"` but instead value `code`. I can imagine that it makes it easier for `ld`, or that your `lld` will then work.

Should it be that, coming up with a bug report to the binutils people would be possible.

Yours,
Kay

**Comment by benelgiac** [comment]
Hi @kayhayen I have not yet been able to test your suggestion, but in the meantime I found a workaround. Just **using clang instead of gcc "fixes" the problem**. It must be that the ld/lld bug is triggered only when attempting to link object files generated by gcc. 

I am happy with this at the moment. Thanks for you help!

**Comment by kayhayen** [comment]
I wonder, if we should get into the business of warning about using clang on aarch64, as this may be happening a lot.

Yours,
Kay

**Comment by oddmario** [comment]
> I wonder, if we should get into the business of warning about using clang on aarch64, as this may be happening a lot.
> 
> Yours, Kay

Hello,

It indeed does happen a lot. I tried compiling a Flask application on an aarch64 Oracle Cloud instance and faced the same issue. Installing clang then appending the `--clang` parameter to Nuitka solved the issue.

**Comment by kayhayen** [comment]
Dang, these things are tough to reproduce naturally, but I guess, catching -11 exit code from the C tools on at least Linux, and turning it to stating something that a C compiler bug was encountered, could be a thing.

**Comment by kayhayen** [comment]
If you would be willing to test it @oddmario I could make the change, and you confirm it to work for you, if that's something you would be willing to do for the project.

**Comment by oddmario** [comment]
> If you would be willing to test it @oddmario I could make the change, and you confirm it to work for you, if that's something you would be willing to do for the project.

Sure! I'd love to.

**Comment by kayhayen** [comment]
It is there now: https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
I see, this is `gcc` converting `-11` from its used tool to `1` error exit. So, catching it in C compilation, but not linking, however there it's likely to happen with LTO. So, I am working around that by searching for ` terminated with signal 11` and pretending to have exit code -11 then (unless it's somehow zero, don't want to make things fail that did not).

Please retry with factory. I am of course no sure if this is `stderr` really, worst case it's `stdout` and will still not work. Please retry with current factory code.

**Comment by oddmario** [comment]
> I see, this is `gcc` converting `-11` from its used tool to `1` error exit. So, catching it in C compilation, but not linking, however there it's likely to happen with LTO. So, I am working around that by searching for ` terminated with signal 11` and pretending to have exit code -11 then (unless it's somehow zero, don't want to make things fail that did not).
> 
> Please retry with factory. I am of course no sure if this is `stderr` really, worst case it's `stdout` and will still not work. Please retry with current factory code.

Turns out it's stderr :)

```
Nuitka-Scons:INFO: Backend linking program (no progress information available).

collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
compilation terminated.
Nuitka-Scons:INFO: Running gcc -o /root/test/main.dist/main -fuse-linker-plugin -flto=4 -fpartial-inlining -freorder-functions -O2 -z noexecstack -Xlinker -export-dynamic -rdynamic -s -Wl,-R,'$ORIGIN' -Wl,--disable-new-dtags -Wl,-b -Wl,binary -Wl,./__constants.bin -Wl,-b -Wl,elf64-littleaarch64 -Wl,-defsym -Wl,constant_bin_data=_binary_____constants_bin_start @"./@link_input.txt -L/usr/lib -ldl -lm /usr/lib/python3.8/config-3.8-aarch64-linux-gnu/libpython3.8-pic.a -lz -lm -lutil -lpthread -lexpat took 1030.86 seconds
FATAL: Error, the C compiler 'gcc' crashed with segfault. Consider upgrading it or using --clang option.
scons: *** [/root/test/main.dist/main] Explicit exit, status 1
```

**Comment by kayhayen** [comment]
Thanks for working with me here, this will turn out to be very useless, esp. once `sysexit` gains URL support.

**Comment by kayhayen** [comment]
Part of the 0.7 release.
