### ISSUE TITLE
`PyObject_IsInstance` not working for `FunctionType` checks

### ISSUE THREAD

**Issue by teskje** [Nuitka/Nuitka#471]
When doing an instance check of a Python function compiled with Nuitka against the stdlib class `types.FunctionType`, it should return True. It does in pure Python code, i.e. using `isinstance`. However, it does not when using `PyObject_IsInstance` inside a Python extension module.

My minimal example consists of the extension module (*check.c*) and the Python module that gets compiled with Nuitka (*main.py*).

* **check.c**

```c
#include <Python.h>

static PyObject *check_check(PyObject *self, PyObject *args) {
    PyObject *obj;
    PyArg_ParseTuple(args, "O", &obj);

    PyObject *types = PyImport_ImportModule("types");
    PyObject *FunctionType = PyObject_GetAttrString(types, "FunctionType");
    if (PyObject_IsInstance(obj, FunctionType)) {
        Py_RETURN_TRUE;
    } else {
        Py_RETURN_FALSE;
    }
}

static PyMethodDef check_methods[] = {
    {"check",  check_check, METH_VARARGS, "do check"},
    {NULL, NULL, 0, NULL},
};

static struct PyModuleDef checkmodule = {
    PyModuleDef_HEAD_INIT,
    "check",
    NULL,
    0,
    check_methods,
};

PyMODINIT_FUNC PyInit_check(void) {
    return PyModule_Create(&checkmodule);
}
```

* **main.py**

```python
from check import check

def foo():
    pass

assert check(foo)
```

Compile *check.c* to an extension module, place it in the Python path and run *main.py* with Python 3. The assert passes and no output is generated.

Now compile *main.py* with Nuitka and run the resulting binary:

```
$ python3 -m nuitka --nofollow-imports main.py
$ ./main.bin
Traceback (most recent call last):
  File "/tmp/venv/main.py", line 6, in <module>
    assert check(foo)
AssertionError
```

Clearly the instance check inside the extension module fails.

---

* Nuitka version, full Python version and Platform
  * Nuitka: 0.6.5rc5 (also tested with 0.6.4)
  * Python: 3.6.7 (default, Oct 22 2018, 11:32:17)
  * OS: Linux (Ubuntu 18.04 on WSL)
  * Arch: x86_64

* How did you install Nuitka and Python?

```
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install http://nuitka.net/releases/Nuitka-0.6.5rc5.tar.gz
```

**Comment by ra-kete** [comment]
In case you are wondering: This came up when I tried to use Nuitka on a project that uses [pydantic](https://pydantic-docs.helpmanual.io/), which is compiled with Cython.

**Comment by kayhayen** [comment]
I think there is a way for Nuitka to achieve this, by having `__instancecheck__` in its compiled types, then it will pass the check, but what' next? If people are going to assume it can be casted to a PyFunction object, or that `PyFunction_GET_ARGS` is working, we will have a lot of corruption.

On the Python level, that is not possible, on the C level, there is huge danger. On the other hand, we are not talking about `PyFunction_Check`, so maybe people are not supposed to use it that way anyway.

**Comment by kayhayen** [comment]
A complication is that this `__instancecheck__` has to live in the metaclass of a type, to get called, and that will require introducing it in the first place.

**Comment by kayhayen** [comment]
So, who ever is going to take this on, the code that should be changed lives here:

https://github.com/Nuitka/Nuitka/blob/5eae90fc5d4813341395c8be79410f770c42c41c/nuitka/build/static_src/CompiledFunctionType.c#L573

This is where the `compiled_function` type is readied. It probably is also where the meta class needs to be injected. I saw this link on StackOverflow:

https://stackoverflow.com/questions/52957192/python-extension-in-c-metaclass

It explains how to insert it to a type, and of course, you would have to create it. It should be derived from the "type" meta class and only provide one method of its own. Showing that you get called and with which arguments would be good enough.

**Comment by Nimishkhurana** [comment]
I am working on this @kayhayen

**Comment by Nimishkhurana** [comment]
@kayhayen I found in documentation that `.ob_type` of any custom `type` must be defaultly initialised to `&PyType_Type`;
Documentation: https://docs.python.org/2/c-api/typeobj.html#c.PyObject.ob_type
We are not even doing this. So can it be possible that it is not recognizing the `type` because of this.

**Comment by kayhayen** [comment]
We are using `PyVarObject_HEAD_INIT` with NULL, which as they write under the link, is changed by `PyType_Ready` when that is the value. I guess, puting NULL there, also gave a tiny bit less code.

I therefore think, as part of the example in StackOverflow, you set `->tp_type` manually to your to be created meta class type that inherits from `type`. Doing that just before calling `PyType_Ready` is likely good enough @Nimishkhurana

**Comment by Nimishkhurana** [comment]
> We are using `PyVarObject_HEAD_INIT` with NULL, which as they write under the link, is changed by `PyType_Ready` when that is the value. I guess, puting NULL there, also gave a tiny bit less code.

I guess you mean to say `PyType_Type` inplace of `PyType_Ready`. I am also asking that can't we just assign the value `PyType_Type` inplace of custom metaclass as currently only NULL is there not even `PyType_Type`

**Comment by kayhayen** [comment]
The later would not be a change @Nimishkhurana but what `PyType_Ready(&Nuitka_Function_Type);` already does.

And yes, indeed, it is called and expected to make the type "ready", i.e. usable at run time, and the first snippet of yours looks good to me. You just have to define `MetaType` and make it ready too, before using it.

**Comment by Nimishkhurana** [comment]
Okay understood @kayhayen. Should i make another .h file to define MetaType or define in this file only, what will be the better option? I guess it will involve making a custom Type and adding a custom __new__ function. Am i right ?

**Comment by kayhayen** [comment]
If you don't find it to confusing, you can leave it in the same file. Part of this is also to get an idea, if maybe this is a generic thing, that e.g. `compiled_method` and other types can re-use.

I think, you don't have to change `__new__`, do you? I am not sure with how little you can get away with, but basically you can try and start with a type that defines no slots of its own at all, and just inherits from `type`, well, with the `NULL` you are already doing. Ready that type, and put it as the `ob_type` and look at this:

```
def f(): pass

print(type(f))
print(type(type(f)))
```

Get the later to whatever name you picked, how about `compiled_type`, and you are in. Then use provide methods. Simillar to the `__reduce__` in `Nuitka_Function_methods`, you can one array for yourself and use it as `tp_methods`.

I think most of the time, I don't define `tp_new` and get away with it. And `tp_init` will do with default behavior. Mind you, we don't need to change any of the mechanics, we just want that `__instancecheck__` becomes callable.

**Comment by kayhayen** [comment]
What I honestly don't know check, is if and with what arguments, __instancecheck__ will be called. Just printing them out with `PRINT_ITEM(args); PRINT_NEW_LINE();` will do for us. Then we can come up with the proper response. :)

**Comment by kayhayen** [comment]
Also, how generic it can be will be understood at that point.

**Comment by Nimishkhurana** [comment]
@kayhayen I have made the MetaType but how do i add it to module. I can't find any variable which denotes current module.

**Comment by kayhayen** [comment]
@Nimishkhurana it doesn't have to be in a module, I might be mistaken, but that should not be necessary. For CPython2 types, I just checked on prompt, and apparently `__builtin__` is used, but that is also where it lives as a name, you can just assign it as the `ob_type` and be good. 

Later, when you can see it at run time, you can print its `__module__` and see if that is some sort of default the that happens automatically. But for now it should be ignorable.

**Comment by Nimishkhurana** [comment]
okay @kayhayen. I have used Nuitka quite a long time ago. Now when i run 
`python -m nuitka filename.py` 
It says no module named nuitka in anaconda3/bin/python.

**Comment by kayhayen** [comment]
For development, you git do git checkout, and use `python ./bin/nuitka` or add the git checkout directory in your `PYTHONPATH` variable or execute `python setup.py develop` which will make your checkout work for the Python installation @Nimishkhurana

**Comment by kayhayen** [comment]
Any news here @Nimishkhurana  ?

**Comment by Nimishkhurana** [comment]
I have compiled but getting error that PyObject Type has no attribute ob_type. 
After googling i used this instead `Py_TYPE(&Nuitka_Function_Type) = &MetaType;`. This generates the .bin file but running that file says segmentation fault.

**Comment by kayhayen** [comment]
Maybe it would be best to create a PR with what you got, then I can comment more to the point.

Using Py_TYPE() discards type information indeed, but then again it's declared as `PyTypeObject`, so that is fishy. Got to see your code I guess.

**Comment by Nimishkhurana** [comment]
Ok I will make a PR soon.

**Comment by kayhayen** [comment]
The PR got never finished, and maybe wasn't the best solution. I am attempting a way riskier approach that I originally avoided, and that is to claim that compiled functions have uncompiled functions as a base type. That is of course barely true, and any code to run from the uncompiled function type will cause severe issues. For that type of function I have added massive amounts of assertions to make sure the slots are not the same between them. But attributes and methods may still come through. I will generate tests that demonstrate this to be untrue, before I can make this baseline. However, likely it's just fine.

The option to enable this is `--experimental=function-base` and it's on the factory branch right now: https://nuitka.net/doc/factory.html

**Comment by lermana** [comment]
I just want to note that I was previously getting the following error, which is alleviated when running with your new fix:
```
RuntimeError: no validator found for <class 'compiled_function'>, see `arbitrary_types_allowed` in Config
```

Thank you!

**Comment by kayhayen** [comment]
Part of the current hotfix 0.6.17.7 release, including the experimental flag.

**Comment by kayhayen** [comment]
Opening, because the experimental flag is not the final solution. For the next release 0.6.19 I have harded it, and made sure it works well, but I am not making it the default, however I believe it should be usable. For the next release I am adding a goal to have it as default for the 0.6.20 release.

**Comment by jborman-exos** [comment]
@kayhayen thanks for linking me here from #1359. I read through the comments above, but I just want to clarify what the solution is (if any). Having already tried the latest development branch of Nuitka to no avail, is the fix you mention just adding this flag `--experimental=function-base` or is it something not yet implemented/available in a release candidate of 0.6.19?

**Comment by brendanator** [comment]
This flag `--experimental=function-base` successful compiles Pydantic on mac and linux 🎉

However on Windows I am getting the following exception:

```python
"C:\Users\runneradmin\AppData\Local\Nuitka\Nuitka\gcc\x86_64\11.2.0-12.0.1-9.0.0-r1\mingw64\bin\ccache.exe" "C:\Users\runneradmin\AppData\Local\Nuitka\Nuitka\gcc\x86_64\11.2.0-12.0.1-9.0.0-r1\mingw64\bin\gcc.exe" -o static_src\CompiledGeneratorType.o -c -flto -fuse-linker-plugin -fno-fat-lto-objects -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-declarations -fno-var-tracking -Wno-misleading-indentation -fcompare-debug-second -O3 -D_NUITKA_EXPERIMENTAL_FUNCTION_BASE -D_WIN32_WINNT=0x0501 -D__NUITKA_NO_ASSERT__ -D_NUITKA_STANDALONE -DMS_WIN64 -D_NUITKA_CONSTANTS_FROM_RESOURCE -D_NUITKA_FROZEN=166 -D_NUITKA_EXE -IC:\hostedtoolcache\windows\Python\3.9.9\x64\include -I. -IC:\HOSTED~1\windows\Python\3935B3~1.9\x64\lib\SITE-P~1\nuitka\build\include -IC:\HOSTED~1\windows\Python\3935B3~1.9\x64\lib\SITE-P~1\nuitka\build\static_src static_src\CompiledGeneratorType.c
static_src\CompiledGeneratorType.c:1468:5: error: initializer element is not constant
scons: *** [static_src\CompiledGeneratorType.o] Error 1
scons: internal stack trace:

  File "C:\HOSTED~1\windows\Python\3935B3~1.9\x64\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-4.3.0\SCons\Job.py", line 262, in run
 1468 |     &PyGen_Type, /* tp_base */
    task.execute()
  File "C:\HOSTED~1\windows\Python\3935B3~1.9\x64\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-4.3.0\SCons\Script\Main.py", line 193, in execute
    SCons.Taskmaster.OutOfDateTask.execute(self)
  File "C:\HOSTED~1\windows\Python\3935B3~1.9\x64\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-4.3.0\SCons\Taskmaster.py", line 235, in execute
    self.targets[0].build()
  File "C:\HOSTED~1\windows\Python\3935B3~1.9\x64\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-4.3.0\SCons\Node\__init__.py", line 755, in build
    self.get_executor()(self, **kw)
  File "C:\HOSTED~1\windows\Python\3935B3~1.9\x64\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-4.3.0\SCons\Executor.py", line 384, in __call__
    return _do_execute_map[self._do_execute](self, target, kw)
  File "C:\HOSTED~1\windows\Python\3935B3~1.9\x64\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-4.3.0\SCons\Executor.py", line 120, in execute_action_list
    raise status    # TODO pylint E0702: raising int not allowed

      |     ^

In file included from static_src\CompiledGeneratorType.c:1645:

C:\HOSTED~1\windows\Python\3935B3~1.9\x64\lib\SITE-P~1\nuitka\build\static_src/CompiledCoroutineType.c:1214:5: error: initializer element is not constant

 1214 |     &PyCoro_Type, /* tp_base */

      |     ^

In file included from C:\HOSTED~1\windows\Python\3935B3~1.9\x64\lib\SITE-P~1\nuitka\build\static_src/CompiledCoroutineType.c:1880,

                 from static_src\CompiledGeneratorType.c:1645:

C:\HOSTED~1\windows\Python\3935B3~1.9\x64\lib\SITE-P~1\nuitka\build\static_src/CompiledAsyncgenType.c:1098:5: error: initializer element is not constant

 1098 |     &PyAsyncGen_Type, /* tp_base */

      |     ^

In file included from static_src\CompiledGeneratorType.c:1650:

C:\HOSTED~1\windows\Python\3935B3~1.9\x64\lib\SITE-P~1\nuitka\build\static_src/CompiledFrameType.c:544:5: error: initializer element is not constant

  544 |     &PyFrame_Type, // tp_base

      |     ^

static_src\CompiledFunctionType.c:523:5: error: initializer element is not constant
scons: *** [static_src\CompiledFunctionType.o] Error 1
scons: internal stack trace:

  523 |     &PyFunction_Type, /* tp_base */

      |     ^

In file included from static_src\CompiledFunctionType.c:2722:

C:\HOSTED~1\windows\Python\3935B3~1.9\x64\lib\SITE-P~1\nuitka\build\static_src/CompiledMethodType.c:526:5: error: initializer element is not constant

  File "C:\HOSTED~1\windows\Python\3935B3~1.9\x64\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-4.3.0\SCons\Job.py", line 262, in run
    task.execute()
  526 |     &PyMethod_Type, /* tp_base */
  File "C:\HOSTED~1\windows\Python\3935B3~1.9\x64\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-4.3.0\SCons\Script\Main.py", line 193, in execute

    SCons.Taskmaster.OutOfDateTask.execute(self)
      |     ^
  File "C:\HOSTED~1\windows\Python\3935B3~1.9\x64\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-4.3.0\SCons\Taskmaster.py", line 235, in execute

    self.targets[0].build()
scons: building terminated because of errors.
  File "C:\HOSTED~1\windows\Python\3935B3~1.9\x64\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-4.3.0\SCons\Node\__init__.py", line 755, in build
    self.get_executor()(self, **kw)
  File "C:\HOSTED~1\windows\Python\3935B3~1.9\x64\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-4.3.0\SCons\Executor.py", line 384, in __call__
    return _do_execute_map[self._do_execute](self, target, kw)
  File "C:\HOSTED~1\windows\Python\3935B3~1.9\x64\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-4.3.0\SCons\Executor.py", line 120, in execute_action_list
    raise status    # TODO pylint E0702: raising int not allowed```

**Comment by kayhayen** [comment]
I think that you need to use develop, where it's better. Seems it's not legal C and problematic to use a DLL symbol on Windows.

**Comment by kayhayen** [comment]
With 0.7 this works out of the box and the experimental flag makes no difference anymore.
