### ISSUE TITLE
nuitka compiles code successfuly but give SyntaxError: Non-UTF-8 code starting with '\x9d' in file on running

### ISSUE THREAD

**Issue by anekix** [Nuitka/Nuitka#478]
**python version** 3.7.3
**nuitka version**: 0.6.5
**installation method**: pip

I compiled my flask app as a standalone binary using the command :
`python3 -m nuitka --standalone --follow-imports --recurse-all --show-progress --show-scons run.py`
it compiles successfully everything but on running the binary it give:

```
 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:9090/ (Press CTRL+C to quit)
 * Restarting with stat
  File "/home/backend/app/run.dist/run", line 1
SyntaxError: Non-UTF-8 code starting with '\x9d' in file /home/backend/app/run.dist/run on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

```

i have searched all my files but none have `\x9d` character.

**Comment by kayhayen** [comment]
It seems flask is trying to re-execute the main program. Which normally is a python script, and running it with Python will work, but not in this case.

I am not too familiar with flask, can you give me a minimal example mayhaps? I have no idea what Flask is trying to achieve, and how to avoid it. But if it's a reload of the binary, it should not be due to changed sources normally, as their aint any, maybe it is due to Python flags.

**Comment by kayhayen** [comment]
Any progress on this, I would need an example to examine this.

**Comment by anekix** [comment]
i will update soon( maybe by tomorrow), away from computer for some reasons

**Comment by anekix** [comment]
I tried simple flask app to reproduce the issue but i couldn't find the cause. my flask app is a  large project. i need to pin point what is triggering this error. i will update soon

**Comment by kayhayen** [comment]
Any progress on this @anekix as without a reproducer, I can't analyse this.

**Comment by kayhayen** [comment]
Closing for lack of feedback.

**Comment by ottokrechmer** [comment]
Same problem in Django app, I can give a simple example app. Can you help in this case?

**Comment by StepanU** [comment]
I had the same error.
Fixed by disabling debug mode!

**Comment by rwayan** [comment]
> I had the same error.
> Fixed by disabling debug mode!

It works thx
