### ISSUE TITLE
Enum error for standalone compiling Tensorflow

### ISSUE THREAD

**Issue by xinliclarifai** [Nuitka/Nuitka#481]
Hello, I run into this errors when compiling tensorflow in standalone. I guess it's because not compile Tensorflow or Enum correctly. Do you think it's a bug? Or is there anything I did wrong?
Thanks!

Traceback
```
Traceback (most recent call last):
  File "/home/ubuntu/work/test/test.dist/test.py", line 7, in <module>
  File "/home/ubuntu/work/test/test.dist/tensorflow/python/training/optimizer.py", line 508, in compute_gradients
  File "/home/ubuntu/work/test/test.dist/tensorflow/python/ops/gradients_impl.py", line 662, in gradients
  File "/home/ubuntu/work/test/test.dist/tensorflow/python/ops/gradients_impl.py", line 797, in _GradientsHelper
  File "/home/ubuntu/work/test/test.dist/enum/__init__.py", line 347, in __call__
TypeError: unbound compiled_method __new__() must be called with UnconnectedGradients instance as first argument (got EnumMeta instance instead)
```
This exception is caused in compiled version by wrong enum.Enum processing in tensorflow. 

Running with standalone:
`python -m nuitka --standalone --include-package=setuptools --include-package=mock --include-package=pbr --show-progress --show-scons --show-modules test.py` ( can reproduce the problem )
Only compile with Enum:
`python -m nuitka --standalone --include-package=setuptools --include-package=mock --include-package=pbr --show-progress --show-scons --show-modules python/ops/unconnected_gradients.py` (work well)
Without standalone:
`python -m nuitka test.py` (work well)

Sample Script(test.py):
```
import tensorflow as tf
x = tf.Variable(0.5)
y = x*x

opt = tf.train.MomentumOptimizer(0.8, 0.9)
grads = opt.compute_gradients(y)
print 1
opt = tf.train.AdamOptimizer(1e-4)
grads = opt.compute_gradients(y)
print 2
```

Environment:
```
0.6.4rc3
Python: 2.7.15+ (default, Nov 27 2018, 23:36:35)
Executable: /home/ubuntu/virtualenv/v1/bin/python
OS: Linux
Arch: x86_64
```
Nuitka is installed by `pip install http://nuitka.net/releases/Nuitka-0.6.4rc3.tar.gz`
Tensorflow 1.13.1
In a clean python virtualenv in Ubuntu 14.04

**Comment by kayhayen** [comment]
You are using an outdated version of Nuitka, plus a development version. This has been fixed already.

Yours,
Kay
