### ISSUE TITLE
Exclude namespace when building a package

### ISSUE THREAD

**Issue by raviv** [Nuitka/Nuitka#486]
Hi,

When building a package, is it possible to exclude a namespace?

For example, exclude "mylib.internal" when building "mylib" using
`python -m nuitka --module mylib --include-package=mylib`

Thanks,

**Comment by kayhayen** [comment]
I think this should be working, e.g. `--nofollow-import-to=*.tests`, is it not?

Yours,
Kay

**Comment by raviv** [comment]
Thanks @kayhayen 
Wasn't aware of this option. It's not in the doc.
