### ISSUE TITLE
Seg faults on aarch64

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#489]
```console
[   97s] + /usr/bin/python2 ./tests/run-tests --no-other-python --skip-basic-tests --skip-syntax-tests --skip-other-cpython-tests --skip-cpython27-tests --skip-reflection-test
[   97s] Cannot execute tests with Python 2.6, disabled or not installed.
[   97s] Executing test case called python2.7-debug with CPython python2.7 and extra flags '--debug'.
[   97s] Running the program tests with options '--debug' with python2.7:
[   97s] Run '/usr/bin/python2 ./tests/programs/run_all.py search' in '/home/abuild/rpmbuild/BUILD/Nuitka-0.6.5.1565768581.a1f8026e'.
[   97s] Using concrete python 2.7.16 on aarch64
[   97s] Consider output of recursively compiled program: absolute_import
[   97s] Comparing output of 'absolute_import/AbsoluteImportMain.py' using '/usr/bin/python2' with flags silent, expect_success, remove_output, recurse_all, original_file, two_step_execution ...
[  108s] --- /usr/bin/python2 (stdout)
[  108s] +++ nuitka (stdout)
[  108s] 
[  108s] @@ -1,3 +1 @@
[  108s] 
[  108s] -This is for relative import.
[  108s] -hi
[  108s]  
[  108s] --- /usr/bin/python2 (stderr)
[  108s] +++ nuitka (stderr)
[  108s] 
[  108s] @@ -1 +1,4 @@
[  108s] 
[  108s] +collect2: fatal error: ld terminated with signal 11 [Segmentation fault]
[  108s] +compilation terminated.
[  108s] +scons: *** [AbsoluteImportMain.bin] Error 1
[  108s]  
[  108s] Exit codes 0 (CPython) != 1 (Nuitka)
[  108s] Error, outputs differed.
[  108s] Error exit! 1
[  108s] error: Bad exit status from /var/tmp/rpm-tmp.C6lb0L (%check)
```

On 0.6.5
```console
[   98s] + /usr/bin/python2 ./tests/run-tests --skip-reflection-test --no-other-python
[   98s] Cannot execute tests with Python 2.6, disabled or not installed.
[   98s] Executing test case called python2.7-debug with CPython python2.7 and extra flags '--debug'.
[   98s] Running the basic tests with options '--debug' with python2.7:
[   98s] Run '/usr/bin/python2 ./tests/basics/run_all.py search' in '/home/abuild/rpmbuild/BUILD/Nuitka-0.6.5'.
[   98s] Using concrete python 2.7.16 on aarch64
[   98s] Comparing output of 'Asserts.py' using '/usr/bin/python2' with flags silent, expect_success, remove_output, recurse_all, original_file, cpython_cache ...
[  109s] --- /usr/bin/python2 (stdout)
[  109s] +++ nuitka (stdout)
[  109s] 
[  109s] @@ -1,9 +1 @@
[  109s] 
[  109s] -Function that will assert.
[  109s] -Raised <type 'exceptions.AssertionError'> 
[  109s] -Function that will not assert.
[  109s] -No exception.
[  109s] -Function that will assert with argument.
[  109s] -Raised <type 'exceptions.AssertionError'> argument
[  109s] -Assertion with tuple argument.(3,)
[  109s] -Assertion with plain argument.3
[  109s]  
[  109s] --- /usr/bin/python2 (stderr)
[  109s] +++ nuitka (stderr)
[  109s] 
[  109s] @@ -1 +1,4 @@
[  109s] 
[  109s] +collect2: fatal error: ld terminated with signal 11 [Segmentation fault]
[  109s] +compilation terminated.
[  109s] +scons: *** [/var/tmp/basics/python2.7-debug/Asserts.bin] Error 1
[  109s]  
[  109s] Exit codes 0 (CPython) != 1 (Nuitka)
[  109s] Error, outputs differed.
[  109s] Error exit! 1
[  109s] error: Bad exit status from /var/tmp/rpm-tmp.NBWrZI (%check)
```

**Comment by kayhayen** [comment]
A segfault in `collect2` should be considered its fault. I don't think this is related to memory usage.

I have a suspect that it could be this:

```
if gcc_mode and not noelf_mode and not clang_mode:
    env.Append(LINKFLAGS=["-z", "noexecstack"])
```

Maybe that's less robust, but otherwise I am at loss of course.

Yours,
Kay

**Comment by kayhayen** [comment]
@jayvdb did you have a chance to try out with removing the quoted code?

**Comment by jayvdb** [comment]
No, this one slipped past me, but I'll get to it this weekend.

**Comment by jayvdb** [comment]
I have removed those two lines and the problem persists.

I'll dig into this a bit today.

Also noting the same problem occurs on Python 3.

```console
[   97s] Executing test case called python3.7-nodebug with CPython python3.7 and extra flags ''.
[   97s] Running the program tests with options '' with python3.7:
[   97s] Run '/usr/bin/python3 ./tests/programs/run_all.py search' in '/home/abuild/rpmbuild/BUILD/Nuitka-0.6.5.1568975414.e336d005'.
[   97s] Using concrete python 3.7.3 on aarch64
[   97s] Consider output of recursively compiled program: absolute_import
[   97s] Comparing output of 'absolute_import/AbsoluteImportMain.py' using '/usr/bin/python3' with flags silent, expect_success, plugin_enable:pylint-warnings, remove_output, recurse_all, original_file, two_step_execution ...
[  105s] --- /usr/bin/python3 (stdout)
[  105s] +++ nuitka (stdout)
[  105s] 
[  105s] @@ -1,3 +1 @@
[  105s] 
[  105s] -This is for relative import.
[  105s] -hi
[  105s]  
[  105s] --- /usr/bin/python3 (stderr)
[  105s] +++ nuitka (stderr)
[  105s] 
[  105s] @@ -1 +1,4 @@
[  105s] 
[  105s] +collect2: fatal error: ld terminated with signal 11 [Segmentation fault]
[  105s] +compilation terminated.
[  105s] +scons: *** [AbsoluteImportMain.bin] Error 1
```

**Comment by jayvdb** [comment]
I see this is a repeat of https://github.com/Nuitka/Nuitka/issues/47

**Comment by kayhayen** [comment]
This is of course some form of tool chain issue, with "gcc" crashing during the compilation, and not for a large program. The `noexecstack` looked suspicious to me. Another thing, that could be found guilty is where the constants blob gets directly attached.

if in `SingleExe.scons` you find this code:

```
if win_target:
    resource_mode = "win_resource"
elif gcc_mode and getLinkerArch() is not None:
    resource_mode = "linker"
else:
    resource_mode = "code"
```

and make it so that `resource_mode` becomes code, it will create a C file instead of asking the linker to attach a symbol. Quite possibily, that is a bit unusual of Nuitka to use this feature. Surely gcc must not crash either way, even if Nuitka gets something wrong there (determining linker arch), and you can also check if the provided linker arch is at fault and should be different.

Am I correct in an assessment that no program can be compiled for aarch64 ? 

Yours,
Kay

**Comment by jayvdb** [comment]
I've installed clang and done `sed -i 's/return options.clang/return True/' nuitka/Options.py` , and the basic tests all passed.  I'm running more extensive tests now with clang.

I didnt see a quick way to force use of clang from `run_tests`.

> Am I correct in an assessment that no program can be compiled for aarch64 ?

This arch has a large percentage of the distro built for it, and mostly using gcc -- but it is more finicky.  I've seen quite a few packages exclude it from the build, or exclude it from the check phase.  So I am not treating this as a high priority / blocker for getting Nuitka pushed into the main distro collection.

**Comment by kayhayen** [comment]
There is `NUITKA_EXTRA_OPTIONS` which is supposed to be handled by the test runner, you can specifiy things like `--debug` and `--clang` this way.

For clang the objdump trick is used too, but a different `ld` right? That would explain it not crashing due to more modern software.

BTW: Does openSUSE give a static link library for CPython?

Yours,
Kay

**Comment by jayvdb** [comment]
Forcing `resource_mode = "code"` (`sed -i 's/return _linker_arch/return None/' nuitka/build/SingleExe.scons`) gets gcc working.

And all tests are passing with clang.

**Comment by jayvdb** [comment]
It looked like `NUITKA_EXTRA_OPTIONS` was being overwritten in the test runner, to specify the "sub test directory" iirc.

With clang, I am just using the normal `ld`.

So I think the solution for this is to force `resource_mode = "code"` for this arch if using gcc.  And maybe a note on the README recommending using clang for this arch...?

**Comment by kayhayen** [comment]
I am under the impression though, that it works generally though with say Debian. I am going to try and install a kvm virtual machine of Debian now, where I think I would know if it doesn't work. But I have not really validated the linker arch detection beyond `armhf` yet.

**Comment by kayhayen** [comment]
Not sure if Debian stable even does aarch64, I failed to setup a arm64, mostly due to qmu not having a default machine, which is suspicious. So that fails from my side. Let me close this as a non-Nuitka bug then, as I don't see any cause of action. You ought to report this upstream to binutils I guess, segfault is not the thing to do, even if Nuitka was wrong there.

I see an off chance, that something is wrong with the arch we specify, but without a test platform, that's hard to tell for now.

**Comment by awesomebytes** [comment]
I just wanted to say thanks for the information posted here and in https://github.com/Nuitka/Nuitka/issues/47 
As a fellow arm64 user testing Nuitka (thanks a lot for creating it!) I ran into this issue too. I tried using clang and it worked.
