### ISSUE TITLE
The --lto is not supported on Windows

### ISSUE THREAD

**Issue by golyalpha** [Nuitka/Nuitka#492]
Version output:
```
0.6.5
Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Users\Dell\AppData\Local\pypoetry\Cache\virtualenvs\blender-renderfarm-py3.7\Scripts\python.exe
OS: Windows
Arch: x86_64
```
Win10 Version: 1903

Toolchains installed: MinGW64 & VS2017 Build Tools

Nuitka installed as dev dependency into a poetry-managed venv

Nuitka fails to compile the exe.

Crash output:
```
lto-wrapper.exe: fatal error: CreateProcess: No such file or directory
compilation terminated.
C:/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: error: lto-wrapper failed
collect2.exe: error: ld returned 1 exit status
scons: *** [hello.pyd] Error 1
scons: building terminated because of errors.
```

hello.py
```
print("Yo, it works.")
```

Command to run Nuitka:
```
poetry run python -m nuitka --lto --standalone --recurse-all --python-flag=no_site --show-progress --show-scons hello.py
```

**Comment by kayhayen** [comment]
The `--lto` on Windows might be a particularity unsupported option. All in all, so far I think it only has chances on Linux, because on Windows, they enforce using the DLL.

And maybe MinGW64 doesn't even include that. I will verify, and make the --lto option invisible or ineffective on Windows, although I am not so sure that e.g. clang will not do something useful at least.

Yours,
Kay

**Comment by kayhayen** [comment]
I managed to reproduce with MinGW64 indeed.

**Comment by golyalpha** [comment]
What about MSVC and Clang?

**Comment by golyalpha** [comment]
I'm going to be checking MSVC later (once my current build finishes), but I don't think I have Clang on my system...

**Comment by golyalpha** [comment]
@kayhayen I may have another problem. `--clang` and `--msvc` doesn't seem to be doing anything. Nuitka still uses MinGW64 no matter what switch I use.

Scons output before compilation started (no `--lto`)
```
Scons command: C:\Users\Dell\AppData\Local\pypoetry\Cache\virtualenvs\blender-renderfarm-py3.7\Scripts\python.exe -W ignore C:\Users\Dell\AppData\Local\pypoetry\Cache\virtualenvs\blender-renderfarm-py3.7\lib\site-packages\nuitka\build\inline_copy\bin\scons.py -f C:\Users\Dell\AppData\Local\pypoetry\Cache\virtualenvs\blender-renderfarm-py3.7\lib\site-packages\nuitka\build\SingleExe.scons --jobs 8 --warn=no-deprecated --no-site-dir --debug=explain name=blender_renderfarm result_name=blender_renderfarm.dist\blender_renderfarm source_dir=blender_renderfarm.build debug_mode=false python_debug=false unstripped_mode=false module_mode=false full_compat=false experimental= trace_mode=false python_version=3.7 target_arch=x86_64 python_prefix=c:\users\dell\appdata\local\programs\python\python37 nuitka_src=C:\Users\Dell\AppData\Local\pypoetry\Cache\virtualenvs\blender-renderfarm-py3.7\lib\site-packages\nuitka\build nuitka_cache=C:\Users\Dell\AppData\Local\Nuitka\Nuitka\Cache module_count=447 result_exe=blender_renderfarm.dist\blender_renderfarm.exe cache_mode=true standalone_mode=true frozen_modules=168 show_scons=true noelf_mode=true clang_mode=true python_sysflag_no_site=true
scons: Reading SConscript files ...
SCONS:  CC='C:\\MinGW64\\mingw64\\bin\\gcc.exe '
SCONS:  Tools= ['mingw']
Scons CC 'gcc' version check:
Scons CC 'gcc' version check gives '8.1.0' from '8.1.0'
Initial CC: gcc
Initial CCVERSION: 8.1.0
Initial CXX: g++
Initial CXXVERSION: None
SCONS:  Picked compiler: C:\MinGW64\mingw64\bin\gcc.exe
SCONS:  Picked name: gcc.exe
Scons compiler: Using C:\MinGW64\mingw64\bin\gcc.exe
Scons CC 'C:\\MinGW64\\mingw64\\bin\\gcc.exe ' version check:
Scons CC 'C:\\MinGW64\\mingw64\\bin\\gcc.exe ' version check gives '8.1.0' from '8.1.0'
Scons: Detecting arch with : ['objdump', '-f', 'C:\\Users\\Dell\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\blender-renderfarm-py3.7\\Scripts\\python.exe']
Scons: Detecting arch with : ['objdump', '-f', 'C:\\MinGW64\\mingw64\\bin\\gcc.exe ']
Scons: Using resource mode: win_resource
scons: Told to run compilation on 8 CPUs.
scons: Unable to find ccache.exe, consider user manual.
scons: Using scons cache inside build directory.
Scons: Launching target: ['blender_renderfarm.dist\\blender_renderfarm.exe']
scons: done reading SConscript files.
scons: Building targets ...
```

**Comment by kayhayen** [comment]
There is an issue about clang support. The only thing that half-way worked to far for clang is using it as `clang-cl.exe`. The performance numbers were so disappointing though, that I didn't peruse it further, although eventually we will for sure.

MSVC 2019 is working. The build promprts, I am not so sure about, people seem to pick ones that do not match their Python arch, but the pre-releases have checks for that now. But finding it via registry works always.

I not sure, which command triggered the gcc output, looks good to me. Are you complaing that --clang has no impact, well yes.

Clang is not a full tool chain, but an addon only, i.e. you need to install the other compiler anyway, and once you do that, with MSVC you get an acceleration, but not what MinGW64 gives out of the box. I think I said stuff on #148 about this.

For as long as that is the case, it's uninteresting, however, installing MSVC 2019, I noted it contains an option for clang installation, and that would probably make #148 easier.

**Comment by kayhayen** [comment]
Also CC environment variable always wins, don't set it, if you want options to make the choice.

**Comment by Keithcat1** [comment]
Is this still a problem with the new WinLibs toolchain? I've never sceen this on my computer. Also I found some info on this bug: https://bugs.launchpad.net/gcc-arm-embedded/+bug/1689294

**Comment by kayhayen** [comment]
The --lto is supported on Windows for a while now, and changes what MSVC does, also with ClangCL mode. It will also become the default at some point in the future.
