### ISSUE TITLE
Building modules against the python stable ABI

### ISSUE THREAD

**Issue by andrewleech** [Nuitka/Nuitka#497]
label: enhancement, question

My main use case of Nuitka is turning python packages into binary modules via the setuptools interface, which works great, thanks!

I've recently used the python stable abi ( https://docs.python.org/3/c-api/stable.html ) for a different project and found it surprisingly effecctive.

My assumption is the stable abi is probably going to be too limited for nuitka to be constrained to, however if it was possible to use it would mean that just two binary modules (x86,x64) could be built to support all python 3 versions.

What do you think?

**Comment by kayhayen** [comment]
This is certainly doable, even if only as an option, but extra effort to maintain and test, but I can see how useful it would be.

Potentially it's also a value in making it clear where the hacks are made in Nuitka and to isolate them. This is obviously only for Python3.

**Comment by kayhayen** [comment]
It is however very unlikely to happen, unless funding is provided by a sponsor with substantial money.
