### ISSUE TITLE
Issue with cryptography module

### ISSUE THREAD

**Issue by blakdronzer** [Nuitka/Nuitka#498]
I have been facing this exclusive issue including crpytography component. It have no problem compiling the same but when we run the application - it fails. It gets the following errlr.
Traceback (most recent call last):
  File "E:\Projects\SomeInternalProject\app.py", line 5, in <module>
    from ProcessManager import ProcessManager
  File "E:\Projects\SomeInternalProject\ProcessManager.py", line 6, in <module ProcessManager>
    import globals
  File "E:\Projects\SomeInternalProject\globals.py", line 8, in <module globals>
    from cryptography.fernet import Fernet
  File "E:\Projects\SomeInternalProject\venv\lib\site-packages\cryptography\fernet.py", line 18, in <module cryptography.fernet>
    from cryptography.hazmat.primitives import hashes, padding
  File "E:\Projects\SomeInternalProject\venv\lib\site-packages\cryptography\hazmat\primitives\padding.py", line 13, in <module cryptography.hazmat.primitives.padding>
    from cryptography.hazmat.bindings._padding import lib
ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._padding'

Have tried various options

python -m nuitka --follow-imports --standalone --python-version=3.6 --experimental=use_pefile --experimental=use_pefile_recurse --experimental=use_pefile_fullrecurse --plugin-enable=pylint-warnings  --plugin-enable=numpy --recurse-to=cryptography --recurse-to=cryptography.hazmat --recurse-to=cryptography.hazmat.bindings app.py

and also

 python -m nuitka --follow-imports --experimental=use_pefile --experimental=use_pefile_recurse --experimental=use_pefile_fullrecurse --plugin-enable=pylint-warnings  --plugin-enable=numpy --include-package=cryptography app.py

but every time we try to run the compiled output - we end up with the above issue.
Secondly - will like to mention that the cryptography module that was installed are all compiled to pyd.. and it dose not have source attached. No problem i can get the source code too if required - but this is something i am stuck in. Can someone please help me get out of this issue? PLS??

**Comment by blakdronzer** [comment]
Well just realized i should also mention - the same when i try running inside the console .. i am not getting any error

```
(venv) λ python
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from cryptography.hazmat.bindings._padding import lib
>>>
```

**Comment by JorjMcKie** [comment]
pls provide me with your app source.
I will try and dig thru the problem.

**Comment by milos-korenciak** [comment]
I suggest to close this thread as much more with the same topic was done here: https://github.com/Nuitka/Nuitka/issues/645

**Comment by kayhayen** [comment]
This is indeed a duplicate and works these days.
