### ISSUE TITLE
Calling Nuitka functions from C++

### ISSUE THREAD

**Issue by Samuel-Nathanson** [Nuitka/Nuitka#503]
Hi,

I am working on video enhancement software, and I want to run my Python code from C++.
I ran 
python -m nuitka --module CSR.py to generate a .so file, and I moved it to the directory /usr/local/lib/eye.

I can compile a file with this .so file (run_python.cpp)
g++ -L /usr/local/lib/eye run_python.cpp -o run -lCSR

This compiles and runs. 

However, I want to learn how to call the functions in CSR.py from run_python.cpp. Is there a way to do this?

**Comment by kayhayen** [comment]
Checkout how to embedd Python interpreter in the Python C/API documentation.
