### ISSUE TITLE
Optimization needed for text only programs

### ISSUE THREAD

**Issue by programmingkidx** [Nuitka/Nuitka#504]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

  python -m nuitka --version
0.6.6rc4
Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 12:01:12) 
Executable: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
OS: Darwin
Arch: x86_64

* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.
I unzipped the source code zip file and ran it directly from its folder.

# full python program used
print("Hello world")

When I compile the above program, the output is huge. On Mac OS X the ouput program size is 26.3 MB! This is simply too big a such a simple program. For a comparable C program like this:

#include <stdio.h>

int main(int argc, char *argv)
{
    printf("Hello world\n");
    return 0;
}

the program's size is only 8k. 

To fix this problem I suggest an optimization be added for text only programs that simply translates python's print() functions to C's printf() functions. I think translating python's raw_input() functions to C's gets() function would be a good idea also.

**Comment by JorjMcKie** [comment]
Your argument is based on wrong assumptions:

The comparison **_cannot_** be one with a program written in C.
An acceptable competition might be something like PyInstaller. The PyInstaller size of such a "hello" program is around 7.7 MB. Using Nuitka you will have something like 9.2 MB, both cases applying UPX and Nuitka not even fully cleaned from unnecessary shared libraries (in which case they are pretty much the same size).
So it's at least the same ballpark, while Nuitka output is a full program and will not be interpreted - in contrast to the PyInstaller case.

**Comment by JorjMcKie** [comment]
You also should take into account, that Python scripts even fully compiled as C programs still by their very nature need the Python shared library (``Python37.dll`` in the Windows Python 3.7 case). This guy alone is 3.6 MB in size ...

**Comment by kayhayen** [comment]
Very well said @JorjMcKie 

Nuitka is not a transpiler, i.e. it is not translating Python to C, and it never will be. It therefore uses a Python installation of some sorts, the existing one for acceleration, or an included one for portability.

You might want to look at Shedkin e.g. which translates some Python programs to C++ programs.

Yours,
Kay
