### ISSUE TITLE
Boto3 - Unable to load endpoints JSON

### ISSUE THREAD

**Issue by jpittiglio** [Nuitka/Nuitka#505]
# Issue

Using the boto3 library will ultimately result in a successfully compiled binary, but generates an exception immediately at runtime due to one of two different issues (which appears to depend on whether or not one attempts to use 'client' or 'resource' objects).

## Example 1

```python
#!/usr/bin/python3

import boto3
from botocore.config import Config

aws_region = 'us-east-1'
proxy_addresses = {'http': '1.2.3.4:80', 'https': '1.2.3.4:443'}

b3s = boto3.session.Session()
ec2 = b3s.resource('ec2', region_name=aws_region, config=Config(proxies=proxy_addresses))

instances = ec2.instances.filter(InstanceIds=['i-xxxxxx'])
for i in instances:
    print(i)
```

Slightly sanitized, simple example that most closely matches my use-case.  Running directly as a Python script yields the expected output:
```
ec2.Instance(id='i-xxxxxx')
```

The following command was run within a virtual environment and successfully compiled an executable with no warnings:
```bash
python -m nuitka --standalone --follow-imports --show-progress --show-scons --recurse-all --include-plugin-directory=/home/jp/nuitka-boto3-test/venv/lib/python3.6/site-packages/boto3 test.py
```

Running the produced executable yielded the following error:
```bash
# test.dist/test 
Traceback (most recent call last):
  File "/home/jp/nuitka-boto3-test/test.dist/boto3/session.py", line 340, in resource
  File "/home/jp/nuitka-boto3-test/test.dist/botocore/loaders.py", line 132, in _wrapper
  File "/home/jp/nuitka-boto3-test/test.dist/botocore/loaders.py", line 376, in load_service_model
botocore.exceptions.UnknownServiceError: Unknown service: 'ec2'. Valid service names are: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jp/nuitka-boto3-test/test.dist/test.py", line 10, in <module>
  File "/home/jp/nuitka-boto3-test/test.dist/boto3/session.py", line 346, in resource
boto3.exceptions.ResourceNotExistsError: The 'ec2' resource does not exist.
The available resources are:
   - 
```

## Example 2

```python
#!/usr/bin/python3

import boto3

ec2 = boto3.client('ec2', region_name='us-east-1')
response = ec2.describe_instances()
print(response)
```

Trying an even more simplistic example with the 'client' object yielded similar results - running the above as a Python script yielded the expected output:
```python
{'Reservations': [{'Groups': [], 'Instances': [ ... < snip > ... ], 'ResponseMetadata': {'RequestId': 'xxxxx', 'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'text/xml;charset=UTF-8', 'transfer-encoding': 'chunked', 'vary': 'accept-encoding', 'date': 'Mon, 02 Sep 2019 23:52:56 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}
```

The following command was run within a virtual environment and successfully compiled an executable with no warnings:
```bash
python -m nuitka --standalone --follow-imports --show-progress --show-scons --recurse-all --include-plugin-directory=/home/jp/nuitka-boto3-test/venv/lib/python3.6/site-packages/boto3 test2.py
```

Running the produced executable yielded the following error:
```bash
# test2.dist/test2 
Traceback (most recent call last):
  File "/home/jp/nuitka-boto3-test/test2.dist/test2.py", line 5, in <module>
  File "/home/jp/nuitka-boto3-test/test2.dist/boto3/__init__.py", line 91, in client
  File "/home/jp/nuitka-boto3-test/test2.dist/boto3/session.py", line 258, in client
  File "/home/jp/nuitka-boto3-test/test2.dist/botocore/session.py", line 828, in create_client
  File "/home/jp/nuitka-boto3-test/test2.dist/botocore/session.py", line 695, in _get_internal_component
  File "/home/jp/nuitka-boto3-test/test2.dist/botocore/session.py", line 903, in get_component
  File "/home/jp/nuitka-boto3-test/test2.dist/botocore/session.py", line 155, in create_default_resolver
  File "/home/jp/nuitka-boto3-test/test2.dist/botocore/loaders.py", line 132, in _wrapper
  File "/home/jp/nuitka-boto3-test/test2.dist/botocore/loaders.py", line 424, in load_data
botocore.exceptions.DataNotFoundError: Unable to load data for: endpoints
```

## Version Info
```bash
# python -m nuitka --version
0.6.5
Python: 3.6.8 (default, Apr 25 2019, 21:02:35) 
Executable: /home/jp/venv/bin/python
OS: Linux
Arch: x86_64
```

Installed in virtual environment (virtualenv) on CentOS 7.6.1810 (Core).  Using pip, installed all dependencies for test (boto3, nuitka), which yields the following:
```bash
# pip freeze
boto3==1.9.220
botocore==1.12.220
docutils==0.15.2
jmespath==0.9.4
Nuitka==0.6.5
python-dateutil==2.8.0
s3transfer==0.2.1
six==1.12.0
urllib3==1.25.3
```

# Other References
Please note - I am able to compile other scripts with no issues using other external libraries, including requests with some minor tweaks.  I've not been able to figure out how to make boto3 work though.

I did find reference in #339 regarding tests for boto3 and an indication the `endpoints.json` file wasn't being found, but no clear resolution.  @kayhayen made note it might be possible to modify the dictionary `known_data_files` in `DataFileCollectorPlugin.py`, which I attempted first as:

`"botocore": ((None, "./data/endpoints.json"),),`

Then as:

`"botocore": ((None, "./venv/lib/python3.6/site-packages/botocore/data/endpoints.json"),),`

And finally as:

`"botocore": ((None, "/home/jp/nuitka-boto3-test/venv/lib/python3.6/site-packages/botocore/data/endpoints.json"),),`

As I wasn't entirely clear on the proper usage, but none of them seemed to make any impact.  Additionally, when running nuitka, I also tried adding an additional parameter:

`--include-plugin-directory=/home/jp/nuitka-boto3-test/venv/lib/python3.6/site-packages/botocore`

Thinking it might be necessary, but no luck.

**Comment by JorjMcKie** [comment]
Hi, trying to recreate your issue resulted in the following exception (both cases):
```
...
\botocore\hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "C:\Users\Harald\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "C:\Users\Harald\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\signers.py", line 157, in sign
    auth.add_auth(request)
  File "C:\Users\Harald\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\auth.py", line 357, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```
Am I missing something? My installtion is the following:

```D:\Jorj\Desktop>python -m pip show boto
Name: boto
Version: 2.49.0
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: c:\users\Jorj\appdata\local\programs\python\python37\lib\site-packages
Requires:
Required-by: moto

D:\Jorj\Desktop>python -m pip show boto3
Name: boto3
Version: 1.9.135
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: UNKNOWN
License: Apache License 2.0
Location: c:\users\Jorj\appdata\local\programs\python\python37\lib\site-packages
Requires: s3transfer, botocore, jmespath
Required-by: moto, aws-sam-translator

D:\Jorj\Desktop>python -m pip show botocore
Name: botocore
Version: 1.12.135
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email: UNKNOWN
License: Apache License 2.0
Location: c:\users\Jorj\appdata\local\programs\python\python37\lib\site-packages
Requires: jmespath, docutils, urllib3, python-dateutil
Required-by: s3transfer, moto, boto3, aws-xray-sdk

D:\Jorj\Desktop>
```

Very probably, you are missing the data from folder ``boto3/data`` in the generated ``dist`` standalone folder. To get these copied as part of the compile process, some adjustments are required to one of more Nuitka plugins.
I am trying to see which they are. Maybe even a new separate plugin specifically for boto must be created.

**Comment by jpittiglio** [comment]
Thanks a ton for looking into this @JorjMcKie!

I should have noted my tests were being performed on an EC2 instance hosted within AWS.  Boto3 checks a few locations for credentials, before ultimately calling a local address to retrieve the IAM role assigned to the instance if none are found - I'm using that method.  The alternative is to install the AWS CLI (`yum install awscli`) and run `aws configure` which configures the AWS credentials file.  Ref: https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html

I believe you are right regarding the missing data - however, I don't know if I was modifying the `known_data_files` dictionary correctly, or if I was missing a flag for Nuitka to process my changes correctly.

**Comment by JorjMcKie** [comment]
To make things a bit easier without me having to replicate all of your environment, you may want to try a couple of manual folder copies into your generated ``dist``.

If those then work, I will modify the respective Nuitka plugins.

In your dist folder, you should see subfolder named like the packages used (boto, botocore, boto3). Copy the respective ``.../data`` folder into them and try your compiled script again. Chances are it then works.

Looking again into my Python I saw that boto3 also has tons of data (32 MB) in folder ``.../boto3/data`` and dozens of subfolders thereof.
I am always in favor of saving disk size if I can. But as a non-user of the ``boto*`` packages I have no way of telling use cases apart, which may or may not need some or all of those data. So what I would do as a first cut for modifying the Nuitka plugins, is copying all those data at first sight of the respective boto module during compile ... if that's also ok for you.

**Comment by kayhayen** [comment]
@tommyli3318 has tried to use mock to test boto, but the need for access to cloud instances is a deal breaker, therefore it's not covered by its tests, nor do we have good test cases for standalone. It seems you are going to have to do the testing for us.

**Comment by JorjMcKie** [comment]
@kayhayen - we already have a "boto" entry in the ``DataFileCollectorPlugin.py`` which points to ``(None, "./endpoints.json")`` . Maybe it should instead be named "botocore"? And use ``./data/endpoints.json`` instead?
But as I said: that very ``./data`` folder contains 188 (!) more subfolders - which we probably should also copy, if we want to be sure covering the next similar case ...

**Comment by kayhayen** [comment]
@JorjMcKie I might have done that based on a crash I saw, and the file being present, it was never enough surely.

**Comment by JorjMcKie** [comment]
@kayhayen  - that's fine. 
I have to confess a major knowledge gap:
What would I have to specify in the ``DataFileCollectorPlugin.py`` if I want to copy a complex data file structure, e.g. a folder with many subfolder and files?
Would that be a case for specifying a function to be called instead?

**Comment by jpittiglio** [comment]
@JorjMcKie you are awesome - your suggestions ultimately worked!

I first attempted to copy just the `data` folder and the `endpoints.json` file into the root `test2.dist` directory, as below:

```bash
test2.dist
├── data
│   └── endpoints.json
```

This ultimately gave me the same error as before:
```
botocore.exceptions.DataNotFoundError: Unable to load data for: endpoints
```

However, creating a root `botocore` directory above `data` like so:

```bash
test2.dist
├── botocore
│   └── data
│       └── endpoints.json
```

Yielded a different error:
```
botocore.exceptions.UnknownServiceError: Unknown service: 'ec2'. Valid service names are:
```

Thus, I simply copied botocore in it's entirety (versus just `endpoints.json`) to this location, and I got the expected results!

Interestingly, I attempted the exact same process on the Example 1 above (test.dist) and received the same `UnknownServiceError`.  Copying the entirety of `boto3` to the `test.dist` directory along with `botocore` resolved this issue.  I confess to not understanding boto3 in it's entirety on how it constructs clients vs resources, and so suspect that's the cause here.

The 'copy it all' approach is undeniably a little lazy on my part, but I wanted to test your hypothesis.  Please let me know if there are any additional tests I can run or how I can help contribute back on this, as I already have running EC2 instances I can test against.

**Comment by JorjMcKie** [comment]
Just to make sure I understodd you well:
If the dist folder layout looks like

```
test2.dist
├── botocore
│   └── data
│       └── acm
│       └── acm-pca
│       └── ...
│       └── xray
│       └── _retry.json
│       └── endpoints.json
```

... your script works fine?
I so, I'll write something into a plugin and you are ready to go. If we later find ways to exclude any of the subfolders, we can still do it.

**Comment by kayhayen** [comment]
@JorjMcKie It only deals with files so far, beware it does `if os.path.isfile(source_path):` which will make it skip directories, and then there is the `nuitka.freezer.Standalone.copyDataFiles` which does `shutil.copy2` which might be just fine, if you change that to `os.path.exists`.

**Comment by jpittiglio** [comment]
@JorjMcKie The working version I tested was by copying *all* of botocore and boto3 into the root dist folder - i.e.:

```bash
test2.dist
├── botocore
│   └── args.py
│   └── auth.py
│   └── awsrequest.py
│   └── ...
│   └── data
│       └── acm
│       └── acm-pca
│       └── ...
│       └── xray
│       └── _retry.json
│       └── endpoints.json
...
```

**Comment by JorjMcKie** [comment]
Ok, thanks. Will start working on it then.

**Comment by JorjMcKie** [comment]
I have modified a nuitka plugin contained in here:

[DataFileCollectorPlugin.zip](https://github.com/Nuitka/Nuitka/files/3574964/DataFileCollectorPlugin.zip)

As far as I can check it out on my machine, the complete folder ``botocore/data`` is copied to the ``dist`` folder as you have indicated it above (of course, no ``.py`` files are needed).

If you copy the contained ``DataFileCollectorPlugin.py`` directly over to your nuitka installation folder in Python to replace ``/nuitka/plugins/standard/DataFileCollectorPlugin.py`` you hopefully should be able to arrive at the working result (fingers crossed).
Otherwise - please bear with me - we would need another round ...

Once it works, I would upload that fix so we soon would have it officially available.

@kayhayen - I added another dictionary ``known_data_folders`` for hopefully several similar cases. One case I am instantly thinking of is matplotlib data which are now - regrettfully - handled in the numpy plugin. There are more.
Would appreciate your feedback for how I did it, to achieve a maximum of coding style compliance ... ;-)

**Comment by jpittiglio** [comment]
@JorjMcKie Thanks again.  Took a little while of testing - this whole time I've been getting an `Error, needs 'chrpath' on your system, due to 'RPATH' settings in used shared` during compilation and assumed it was an 'ignorable' error since the build still appeared to succeed.  However, after attaching a debugger, I found `DataFileCollectorPlugin.py` was never actually being called - this apparently happens after this error would occur, which would explain why I couldn't seem to get anything to work when attempting to modify the file myself!  A simple `yum install chrpath` resolved this.

Ultimately, after resolving all that I was able to compile successfully - but was receiving the following error at runtime:

```python
Traceback (most recent call last):
  File "/home/jp/nuitka-boto3-test/test2.dist/urllib3/util/ssl_.py", line 322, in ssl_wrap_socket
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jp/nuitka-boto3-test/test2.dist/botocore/httpsession.py", line 253, in send
  File "/home/jp/nuitka-boto3-test/test2.dist/urllib3/connectionpool.py", line 640, in urlopen
  File "/home/jp/nuitka-boto3-test/test2.dist/urllib3/util/retry.py", line 344, in increment
  File "/home/jp/nuitka-boto3-test/test2.dist/urllib3/packages/six.py", line 686, in reraise
  File "/home/jp/nuitka-boto3-test/test2.dist/urllib3/connectionpool.py", line 600, in urlopen
  File "/home/jp/nuitka-boto3-test/test2.dist/urllib3/connectionpool.py", line 344, in _make_request
  File "/home/jp/nuitka-boto3-test/test2.dist/urllib3/connectionpool.py", line 843, in _validate_conn
  File "/home/jp/nuitka-boto3-test/test2.dist/urllib3/connection.py", line 362, in connect
  File "/home/jp/nuitka-boto3-test/test2.dist/urllib3/util/ssl_.py", line 324, in ssl_wrap_socket
urllib3.exceptions.SSLError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jp/nuitka-boto3-test/test2.dist/test2.py", line 6, in <module>
  File "/home/jp/nuitka-boto3-test/test2.dist/botocore/client.py", line 357, in _api_call
  File "/home/jp/nuitka-boto3-test/test2.dist/botocore/client.py", line 647, in _make_api_call
  File "/home/jp/nuitka-boto3-test/test2.dist/botocore/client.py", line 667, in _make_request
  File "/home/jp/nuitka-boto3-test/test2.dist/botocore/endpoint.py", line 102, in make_request
  File "/home/jp/nuitka-boto3-test/test2.dist/botocore/endpoint.py", line 136, in _send_request
  File "/home/jp/nuitka-boto3-test/test2.dist/botocore/endpoint.py", line 228, in _needs_retry
  File "/home/jp/nuitka-boto3-test/test2.dist/botocore/hooks.py", line 356, in emit
  File "/home/jp/nuitka-boto3-test/test2.dist/botocore/hooks.py", line 228, in emit
  File "/home/jp/nuitka-boto3-test/test2.dist/botocore/hooks.py", line 211, in _emit
  File "/home/jp/nuitka-boto3-test/test2.dist/botocore/retryhandler.py", line 183, in __call__
  File "/home/jp/nuitka-boto3-test/test2.dist/botocore/retryhandler.py", line 250, in __call__
  File "/home/jp/nuitka-boto3-test/test2.dist/botocore/retryhandler.py", line 277, in _should_retry
  File "/home/jp/nuitka-boto3-test/test2.dist/botocore/retryhandler.py", line 316, in __call__
  File "/home/jp/nuitka-boto3-test/test2.dist/botocore/retryhandler.py", line 222, in __call__
  File "/home/jp/nuitka-boto3-test/test2.dist/botocore/retryhandler.py", line 359, in _check_caught_exception
  File "/home/jp/nuitka-boto3-test/test2.dist/botocore/endpoint.py", line 200, in _do_get_response
  File "/home/jp/nuitka-boto3-test/test2.dist/botocore/endpoint.py", line 244, in _send
  File "/home/jp/nuitka-boto3-test/test2.dist/botocore/httpsession.py", line 280, in send
botocore.exceptions.SSLError: SSL validation failed for https://ec2.us-east-1.amazonaws.com/ [Errno 2] No such file or directory
```

On a whim, I decided to simply try copying the full botocore subdirectory into the dist directory and everything worked as expected.  For reference, I used the following to run Nuitka from within my virtual environment:
```bash
python -m nuitka --standalone --follow-imports --show-progress --show-scons --recurse-all --include-plugin-directory=/home/jp/nuitka-boto3-test/venv/lib/python3.6/site-packages/boto3 --include-plugin-directory=/home/jp/nuitka-boto3-test/venv/lib/python3.6/site-packages/botocore test2.py
```

Am I using an incorrect option here?

Lastly I noticed in the new dictionary `known_data_folders` you specify botocore and boto.  Could you also include boto3?  Not sure if it's necessary, but might help prevent future issues as boto3 has replaced the original boto library.

Again, your help is greatly appreciated.

**Comment by JorjMcKie** [comment]
@jpittiglio - made more changes:
* now also copying ``boto3/data`` (can't image why I forgot this in the first place)
* added a handful of implicit imports to better support ``boto3``
* made changes to the numpy plugin - it will no longer copy pure data files (for matplotlib and sklearn), but leave this to the data-files plugin, as it should have from the start

With these changes, the test scripts run on my machine (as long as I do not actually access the internet ...)

This time, I have copied all standard plugins in the attached zip for you to repeat your test once more.
I also uploaded the Nuitka ``jorj`` branch with the same changes, so @kayhayen can use the stuff together with his other changes.

[plugins-standard.zip](https://github.com/Nuitka/Nuitka/files/3579647/plugins-standard.zip)

**Comment by jpittiglio** [comment]
@JorjMcKie Thanks again for your assistance - I'd say this is resolved now.

The initial test failed - identified your branch has a new, additional utils module - `ModuleNames.py` - which was missing.  Got that in place and compilation completed without error.

Received the same error again:
```
botocore.exceptions.SSLError: SSL validation failed for https://ec2.us-east-1.amazonaws.com/ [Errno 2] No such file or directory
```

Fresh eyes help though - I realized this was likely complaining about the availability of the ca-cert PEM.  Many times I've seen the use of the environmental variable `AWS_CA_BUNDLE` which *did* fix the issue when set.  However, I wanted to understand why the script didn't require this.

Ultimately attached a debugger again and found botocore has a local copy it uses by default (probably would have been smarter to just find any *.pem files, but was a fun exercise nonetheless).  It's located at `./botocore/cacert.pem`, which explains why copying the whole directory before worked and just the `data` directory doesn't.

I modified the `known_data_files` dictionary in the `DataFileCollectorPlugin.py` as follows:
```python
known_data_files = {
    # Key is the package name to trigger it
    # Value is a tuple of 2 element tuples, thus trailing commas, where
    # the target path can be specified (None is just default, i.e. the
    # package directory) and the filename relative to the source package
    # directory
    "botocore": ((None, "cacert.pem"),), # Added
    "site": ((None, "orig-prefix.txt"),),
    "nose.core": ((None, "usage.txt"),),
    "scrapy": ((None, "VERSION"),),
    "requests": (("certifi", "../certifi/cacert.pem"),),
    "importlib_resources": ((None, "version.txt"),),
    "moto": (
        (None, "./ec2/resources/instance_types.json"),
        (None, "./ec2/resources/amis.json"),
    ),
}
```

Compilation completed and the new binary worked flawlessly.

**Comment by JorjMcKie** [comment]
@jpittiglio  - that's great! Thanks a lot, we are a team aren't we?
I will integrate your mod in my ``jorj`` branch and push again.
