### ISSUE TITLE
Python Embedding with Nuitka

### ISSUE THREAD

**Issue by Samuel-Nathanson** [Nuitka/Nuitka#507]
Hi, 

I want to use Python.h to call functions from my program (CSR_loadAndInferOneImage.py, which includes fastai, cv2, and torch). 

I have tried compiling with Nuitka using
`nuitka CSR_loadAndInferOneImage.py --recurse-all`
This creates .o and .c files, but I do not know any way to reference these with Python.h. If anyone knows how to do this, please let me know immediately.  

I also tried compiling a standalone version with 
 `nuitka --standalone CSR_loadAndInferOneImage.py --recurse-all`
This creates a .dist and .build folder, which contains .so files, but not all of the ones that I want. When I run this command, fastai is not included with the .so libraries, and the binary file that is creates does not run. Running CSR_loadAndInferOneImage.dist/CSR_loadAndInferOneImage causes this error:
`(autotune-p1) sam@sam-Oryx-Pro:~/Documents/test_python_embedding$ ./CSR_loadAndInferOneImage.dist/CSR_loadAndInferOneImage 
INTEL MKL ERROR: /home/sam/Documents/test_python_embedding/CSR_loadAndInferOneImage.dist/libmkl_intel_thread.so: cannot open shared object file: No such file or directory.
Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.so.`

How can I compile a standalone version of my program with the fastai library included? 

Sam

**Comment by kayhayen** [comment]
Seems a case for the numpy plugin, does it cover this @JorjMcKie ?

**Comment by JorjMcKie** [comment]
@Samuel-Nathanson / @kayhayen  - the numpy plugin must be used of course (``--enable-plugin=numpy``) in standalone mode. As well as any other of the standard plugins - you mentioned ``torch``, definitely this one too. Numpy also requires option specifications if you also use scipy, matplotlib, pandas, ...
Up to at least numpy version 1.17.0, the plugin will copy the required shared libraries and other data to the target ``dist`` folder (for scipy  too, some data files for matplotlib and what not).
If that already solves your issue, Samuel, remains to be seen.
Presumably, your script invokes some other exension module written in C? Or how come you need to access ``Python.h``?
If you however do some Python-based parsing of this file, then it needs to be treated like a data file and be copied like one into the target ``dist`` ...

**Comment by kayhayen** [comment]
As for embedding part, there is only the normal way of embedding a Python interpreter into the program, or compiling the whole program. Nuitka does not give C and Python any other interface than what Python does, i.e. you C code must be an extension module to be called from python, and a program must embedd a Python interpreter and run code in there, that has no access to much anything.

Whatever you are dreaming Nuitka to be for interfacing your code, it's not made for that. First, get your stuff to run in Python, then you can use Nuitka. There is no use case enabled by Nuitka.

As for using standalone mode, @JorjMcKie has outlined the case, but the two things don't mix.

Yours,
Kay
