### ISSUE TITLE
pygobject based app fails to start

### ISSUE THREAD

**Issue by zegervdv** [Nuitka/Nuitka#510]
Compiling an application which uses GTK (via pygobject) fails to start.
It happens both with and without the `--standalone` flag.
Output of the app:
```
Traceback (most recent call last):
  File "/mnt/c/Users/zvandeva/Documents/Projects/app/foo.dist/foo.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/mnt/c/Users/zvandeva/Documents/Projects/app/foo.dist/gi/repository/__init__.py", line 25, in <module gi.repository>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/mnt/c/Users/zvandeva/Documents/Projects/app/foo.dist/gi/importer.py", line 34, in <module gi.importer>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/mnt/c/Users/zvandeva/Documents/Projects/app/foo.dist/gi/overrides/__init__.py", line 16, in <module gi.overrides>
  File "/mnt/c/Users/zvandeva/Documents/Projects/app/foo.dist/pkgutil.py", line 561, in extend_path
  TypeError: Required argument 'is_package' (pos 2) not found  
```

The source (minimal example):
``` python
# cat foo.py
import gi

gi.require_version('Gtk', '3.0')

from gi.repository import Gtk

window = Gtk.Window()
window.show_all()
Gtk.main()  
```

I am using a development version (because I was seeing a problem that was fixed in another issue):
```
0.6.6rc5
Python: 3.6.8 (default, Jan 14 2019, 11:02:34)
Executable: /mnt/c/Users/zvandeva/Documents/Projects/app/.py36/bin/python 
OS: Linux
Arch: x86_64 
```
I'm actually running on WSL, but I don't suppose it makes a difference.

The command I use to build:
```
python -m nuitka --standalone --follow-imports --show-progress --show-scons foo.py
```

**Comment by zegervdv** [comment]
PS I am using the `rc` version to get around #500

**Comment by kubilus1** [comment]
Similar error using pywebview with gtk.  

```
  File "/home/user/Software/proj/proj.dist/gi/overrides/__init__.py", line 15, in <module gi.overrides>
  File "/home/user/Software/proj/proj.dist/pkgutil.py", line 561, in extend_path
TypeError: Required argument 'is_package' (pos 2) not found
```

**Comment by kayhayen** [comment]
The importing side of things is fixed on factory branch now.

However, when creating the Window, it was segfaulting for me. I noticed that a hidden dependency on a DLL was missing, `libgtk-3` which is huge, but it crashes still with segfault on Linux with Python3.5 for me. I have no doubt all Python3 will crash.

Seems a type library of gi is loaded from the system still. Not sure what these are and if they need to be adapted. For some reason, before crashing it attempts to load a DLL that previously loaded already with success (libgtk-3), without PATH, but changing the directory makes it succeed, but still crash. I doubt loading it again is a good idea.

Seems we have deep issues here with Gtk. Can you have a look @JorjMcKie, maybe your hinting helps you identify what causes the re-load of the DLL and/or the crash. Looks like a nice puzzle again.

**Comment by JorjMcKie** [comment]
@kayhayen ok.

**Comment by JorjMcKie** [comment]
Sorry for the delay. Turned out I am unable to install PyGObject on Windows ...
At least the results for Linux / Py3.6.

I am also getting that segmentation fault:

```python
import gi

print("successful:", "import gi")
gi.require_version("Gtk", "3.0")
print("successful:", 'gi.require_version("Gtk", "3.0")')
from gi.repository import Gtk

print("successful:", "from gi.repository import Gtk")
window = Gtk.Window()    # <=== crash occurs here
print("successful:", "window = Gtk.Window()")
window.show_all()
print("successful:", "window.show_all()")
Gtk.main()
print("successful:", "Gtk.main()")
```
Therefore, I don't believe hinted compile will help, because the imports all worked ...
The contents of the attached ZIP are:
* ``gi-test.log`` raw listing of all imports in their original sequence. Contains 2 record types: CALL and RESULT. First item in a record is the import level depth, so each CALL matches exactly the next RESULT  **on the same level**.
* ``gi-test-36-linux-64.json`` the cleaned up raw log for use during hinted compilation
* ``gi-test-compile-run.log`` compilation and test run output.

[gi-test.zip](https://github.com/Nuitka/Nuitka/files/3638545/gi-test.zip)

**Comment by kayhayen** [comment]
@JorjMcKie should have warned you, I had to switch to Linux too.

**Comment by zegervdv** [comment]
If you want to try on Windows you will need to use Msys2. It’s the only platform GTK supports on Windows.
I haven’t tried Nuitka on Msys yet but I can try it out and share my config if that would help.

**Comment by JorjMcKie** [comment]
That definitely would help!
I actually tried that one myself, but got nevertheless stuck – Python wouldn’t start, so the demo script of couldn’t be tried and what not.

**Comment by zegervdv** [comment]
You can find msys2 here (if you don't have it yet) [msys2](https://www.msys2.org/).
Then you need to install some packages (assuming you are using the mingw 64bit terminal):
```
pacman -S git \
                mingw-w64-x86_64-python3 \
                mingw-w64-x86_64-python3-pip \
                mingw-w64-x86_64-gtk3 \
                mingw-w64-x86_64-python3-gobject \
                mingw-w64-x86_64-gcc \
                mingw32/mingw-w64-i686-gcc \
                mingw32/mingw-w64-i686-mesa \
                mingw64/mingw-w64-x86_64-mesa \
                patch
```

I'm currently trying to run nuitka on the develop branch on Msys, but it seems to fail on finding the python header files. There's an issue open for that msys2/MINGW-packages#4868.

I'm going to try a bit further, but it seems there may be something else that needs to be fixed first to get it to work on msys.

**Comment by zegervdv** [comment]
I'm getting this error:
```
Error, no 'Python.h' development headers can be found at 'C:/msys2/mingw64/include', dependency not satisfied!
```
And I can see the `Python.h` file is one level deeper at `C:/msys2/mingw64/include/python3.7m`.
Trying to find a way to add it to the include path.

**Comment by kayhayen** [comment]
The MSYS2 works if you do right kinds of pacman installations, except it changed in the last month, search in User Manual and the issue tracker, worked for me.

**Comment by zegervdv** [comment]
I've been doing some new testing on the latest release (0.6.7) and also have the segfault now.
Looking at the strace logs, I see it is loading a lot of `.typelib` files from the system location:
```
openat(AT_FDCWD, "/usr/lib64/girepository-1.0/GObject-2.0.typelib", O_RDONLY) = 3
```

Shouldn't those have been copied into the `.dist` folder?

**Comment by kayhayen** [comment]
The release 0.6.8 was just made and contains the correction.
