### ISSUE TITLE
Installing compiled packages loose their package directory

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#521]
I have started that project we discussed a long time ago, of building an openSUSE site-packages all compiled with Nuitka

https://build.opensuse.org/project/show/home:jayvdb:Nuitka

I have hacked at rpm macros to get packages mostly building without modifications to the .spec files, but one aspect is going to require some very ugly macro modifications, and maybe it can be handled inside Nuitka, either with a special flag, or even just a patch that I apply.

When installing `packaging` built with Nuitka, the result is `packaging.so` and `packaging.pyi`.

It would be really helpful for RPM packaging if that was `packaging/__init__.so` and `packaging/__init__.pyi` , so that the expected directory still exists and it is only the files under that path which are modified.

I have no idea how difficult that might be.

OTOH, `six` should still be `six.so and `six.pyi` in the top level.

(It would be even more wonderful if it could be `six.pyd`, as it would then match the .specs with `.../name.py*`, but I suspect that wont work on Linux.  Changing the spec to .specs with `.../name.*` is feasible, especially as only a small subset of packages do not use directories.)

**Comment by jayvdb** [comment]
Another good reason to be doing this is that packages with extra data files still need to have a directory, so it is a bit confusing to have a foo.so and foo/

**Comment by jayvdb** [comment]
A good heuristic to add as a 'quick fix' might be that if the package has any uncompiled assets that need to be distributed into a directory, or there is already a directory from existing installed packages, the .so and .pyi should be in that same directory.

That doesnt solve the more complicated cases like zope (https://github.com/Nuitka/Nuitka/issues/524), but it will reduce the size of this problem.

**Comment by jayvdb** [comment]
https://github.com/Nuitka/Nuitka/issues/522#issuecomment-535890361 covers a related case of `cryptography_vectors`, where I needed to copy the data to directory beside the built .so , which introduces potential conflicts for any two packages which have package data in a folder of the same name.

**Comment by kayhayen** [comment]
There is actually a package that requires an `__init__.so` to be created, and Nuitka cannot do it, actually outright refuses to. I am putting this to duplicate, and will come up with the package name in question later.
