### ISSUE TITLE
zope components built with Nuitka are all called zope.so

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#524]
When using `build_with_nuitka` , `zope.exceptions` and `zope.interface` both build a zope.so, which needless to say conflict when installed.  This is a special case of https://github.com/Nuitka/Nuitka/issues/521

Moving them so that zope.exceptions is `zope/exceptions.so`, etc, only partially solves the problem.

https://build.opensuse.org/package/show/home:jayvdb:Nuitka/python-zope.interface
https://build.opensuse.org/package/show/home:jayvdb:Nuitka/python-zope.exceptions

Then when running `zope-testrunner` we encounter

```console
[   94s] + zope-testrunner-3.7 -v --test-path=.
[   95s] Traceback (most recent call last):
[   95s]   File "/usr/bin/zope-testrunner-3.7", line 11, in <module>
[   95s]     load_entry_point('zope.testrunner==5.0', 'console_scripts', 'zope-testrunner')()
[   95s]   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
[   95s]     return get_distribution(dist).load_entry_point(group, name)
[   95s]   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
[   95s]     return ep.load()
[   95s]   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
[   95s]     return self.resolve()
[   95s]   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
[   95s]     module = __import__(self.module_name, fromlist=['__name__'], level=0)
[   95s] ImportError: dynamic module does not define module export function (PyInit_testrunner)
```

**Comment by kayhayen** [comment]
Namespaces like this should be working, checkout `tests/distutils/example_nested_namespaces32` 

From the output of bdist_nuitka:

```
adding 'a/b/pkg.cpython-310-x86_64-linux-gnu.so'
adding 'a/b/pkg.pyi'
```

This was working for a long time already, sadly old issues were not maintained well.
