### ISSUE TITLE
build_with_nuitka breaks Jinja2

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#525]
`build_with_nuitka` uses `"--nofollow-import-to=*.tests"` which breaks Jinja2 which has a `jinja2.tests` for the tests used in the Jinja2 templating language.

(I have a temporary workaround, so no rush on how to solve this)

**Comment by kayhayen** [comment]
You can specify `--follow-import-to=jinja2.tests` for this I believe. Let me know if that is not the case. Maybe it should be documented though.
