### ISSUE TITLE
Nuitka needs to support module execution with `python -m compiled_module`

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#528]
Package `stestr` has lots of test failures, all stemming from this exception. 

```console
[  152s] __________________________ TestReturnCodes.test_list ___________________________
[  152s] NOTE: Incompatible Exception Representation, displaying natively:
[  152s] 
[  152s] testtools.testresult.real._StringException: Empty attachments:
[  152s]   pythonlogging:''
[  152s]   stderr
[  152s]   stdout
[  152s] 
[  152s] Traceback (most recent call last):
[  152s]   File "/home/abuild/rpmbuild/BUILD/stestr-2.5.1/tests/test_return_codes.py", line 213, in test_list
[  152s]     self.assertRunExit('stestr list', 0)
[  152s]   File "/home/abuild/rpmbuild/BUILD/stestr-2.5.1/tests/test_return_codes.py", line 98, in assertRunExit
[  152s]     "Stdout: %s; Stderr: %s" % (out, err))
[  152s]   File "/usr/lib/python3.7/site-packages/testtools/testcase.py", line 411, in assertEqual
[  152s]     self.assertThat(observed, matcher, message)
[  152s]   File "/usr/lib/python3.7/site-packages/testtools/testcase.py", line 498, in assertThat
[  152s]     raise mismatch_error
[  152s] testtools.matchers._impl.MismatchError: 100 != 0: Stdout: b'\n=========================\nFailures during discovery\n=========================\n\n================================================================================\nThe above traceback was encountered during test discovery which imports all the found test modules in the specified test_path.\n'; Stderr: b'Traceback (most recent call last):\n  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main\n    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)\n  File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details\n    code = loader.get_code(mod_name)\nAttributeError: type object \'nuitka_module_loader\' has no attribute \'get_code\'\n'
[  152s] 
[  152s] 
[  152s] _____________________ TestReturnCodes.test_list_from_func ______________________
[  152s] NOTE: Incompatible Exception Representation, displaying natively:
[  152s] 
[  152s] testtools.testresult.real._StringException: Empty attachments:
[  152s]   pythonlogging:''
[  152s]   stderr
[  152s]   stdout
[  152s] 
[  152s] stdout-1: {{{
[  152s] =========================
[  152s] Failures during discovery
[  152s] =========================
[  152s] 
[  152s] ================================================================================
[  152s] The above traceback was encountered during test discovery which imports all the found test modules in the specified test_path.
[  152s] }}}
[  152s] 
[  152s] Traceback (most recent call last):
[  152s]   File "/home/abuild/rpmbuild/BUILD/stestr-2.5.1/tests/test_return_codes.py", line 347, in test_list_from_func
[  152s]     self.assertEqual(0, list_cmd.list_command(stdout=stdout.stream))
[  152s]   File "/home/abuild/rpmbuild/BUILD/stestr-2.5.1/stestr/commands/list.py", line 120, in list_command
[  152s]     cmd.setUp()
[  152s]   File "/home/abuild/rpmbuild/BUILD/stestr-2.5.1/stestr/test_processor.py", line 137, in setUp
[  152s]     self.test_ids = self.list_tests()
[  152s]   File "/home/abuild/rpmbuild/BUILD/stestr-2.5.1/stestr/test_processor.py", line 227, in list_tests
[  152s]     exit(100)
[  152s]   File "/usr/lib/python3.7/_sitebuiltins.py", line 26, in __call__
[  152s]     raise SystemExit(code)
[  152s] SystemExit: 100
[  152s] 
[  152s] 
[  152s] ----------------------------- Captured stderr call -----------------------------
[  152s] Traceback (most recent call last):
[  152s]   File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
[  152s]     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
[  152s]   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
[  152s]     code = loader.get_code(mod_name)
[  152s] AttributeError: type object 'nuitka_module_loader' has no attribute 'get_code'
```

**Comment by jayvdb** [comment]
It looks like https://github.com/Nuitka/Nuitka/issues/523 is related.

```console
[  134s] /usr/lib/python3.7/runpy.py:125: RuntimeWarning: 'testtools.run' found in sys.modules after import of package 'testtools', but prior to execution of 'testtools.run'; this may result in unpredictable behaviour
[  134s]   warn(RuntimeWarning(msg))
[  134s] Traceback (most recent call last):
[  134s]   File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
[  134s]     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
[  134s]   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
[  134s]     code = loader.get_code(mod_name)
[  134s] AttributeError: type object 'nuitka_module_loader' has no attribute 'get_code'
[  134s] error: Bad exit status from /var/tmp/rpm-tmp.MeITyG (%check)
```

**Comment by jayvdb** [comment]
This also breaks `subtest.run` which does not have a bin script. As always, I have a workaround for my own testing needs.

**Comment by antoscha** [comment]
Hello, are there any news on this?  
```
$ python -m my.application
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 157, in _get_module_details
    code = loader.get_code(mod_name)
AttributeError: type object 'nuitka_module_loader' has no attribute 'get_code'
```

**Comment by jayvdb** [comment]
Should we have a dummy `get_code` that returns whatever datatype is expected, but without any real code?

The object in question is at https://github.com/Nuitka/Nuitka/blob/develop/nuitka/build/static_src/MetaPathBasedLoader.c

**Comment by kayhayen** [comment]
I am not sure that it doesn't want to execute some source code there, which of course is going to be hard.

**Comment by kayhayen** [comment]
Yes, I just checked, and it wants to do `exec` on it, so there is really no point in providing something like this, it's only going to be hiding.

So, what are are talking about here, is that apparently you want to run a compiled package, via `python -m`, and I must admit, that is very reasonable. When doing `--run` I am using `-c` and import statements, it never occurred to me, that this ought to work, and this being a regression.

**Comment by terryzhao127** [comment]
Hey, is there any PR working on solving it?

**Comment by kayhayen** [comment]
Not, this is only an idea so far.

**Comment by kayhayen** [comment]
So,  turns out this is impossible. Due to the spec mechanism, it asks the extension module loader of CPython, and never executes anything Nuitka at all. We are treated all the same, so in fact, we would have to do something to patch support into runpy to load these. It does load containing packages, so for a `some_package.some_module` it could indeed be made to work, but honestly that is too little to be worth any effort.

Somebody would have to take it up to CPython and make a change to runpy and the `ExtensionFileLoader` such that it would recognize Nuitka created extension modules and treat those differently. Or we would have to do that ourselves with a site module hack via .pth files, but then it's only going to work where something for that is installed.

As a side note, test code should not be compiled, there is no point for that.

**Comment by kayhayen** [comment]
Lets face it, not going to happen

**Comment by jayvdb** [comment]
> As a side note, test code should not be compiled, there is no point for that.

Test code that lives in the package has to be compiled as part of that package, otherwise it will not work. i.e. test modules living in `package_name/foo/tests/test_foo.py`

**Comment by antoscha** [comment]
I think it should be pointed out in docs.

**Comment by kayhayen** [comment]
@antoscha absolutely correct, I am adding this

Modules: Extension modules are not executable directly
======================================================

A package can be compiled with Nuitka, no problem, but when it comes to
executing it, ``python -m compiled_module`` is not going to work and give the
error ``No code object available for AssertsTest`` because the compiled module
is not source code, and Python will not just load it. The closest would be
``python -c "import compile_module"`` and you might have to call the main
function yourself.

To support this, ``runpy`` would or the ``ExtensionFileLoader`` would need a
change such that we could supply a code object to Python to use.

**Comment by kayhayen** [comment]
And improvements in the wording are welcome

**Comment by jayvdb** [comment]
minor improvement for clarity..?
> To support this, the CPython `runpy` and/or `ExtensionFileLoader` would need improving such that Nuitka could supply a compiled module object for Python to use.

**Comment by kayhayen** [comment]
Taken on board
