### ISSUE TITLE
rpmlint warning "executable-stack"

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#533]
All packages built with Nuitka (at least using clang) cause an rpmlint error:

> scons.i586: W: executable-stack /usr/lib/python3.7/site-packages/SCons.so
> The binary declares the stack as executable.  Executable stack is usually an error as it is only needed if the code contains GCC trampolines or similar constructs which uses code on the stack.  One common source for needlessly executable stack cases are object files built from assembler files which don't define a proper .note.GNU-stack section.

**Comment by kayhayen** [comment]
Nuitka does it for gcc on Linux:

```

if gcc_mode and not noelf_mode and not clang_mode:
    env.Append(LINKFLAGS=["-z", "noexecstack"])

```

I am under the assumption that at least macOS may not like this, or FreeBSD, and there clang_mode works as a guard. However, that may be all wrong. I think clang implies a different linker normally. One that may not even have the issue.

I will try to remove the clang exception on factory branch and see what it does to macOS on Travis. It may however come back quickly.

Yours,
Kay

**Comment by kayhayen** [comment]
So macOS hates it, I disabled it for that case. Need to check the FreeBSD and NetBSD, if their clang does it, likely this ought to be a `linux_mode` thing.

**Comment by kayhayen** [comment]
So this is Nuitka for a while now:

```
if gcc_mode and not noelf_mode and not macosx_target:
    env.Append(LINKFLAGS=["-z", "noexecstack"])
```

I think that solves the issue. I forgot when this was fixed, but can you confirm you hack is no longer necessary @jayvdb
