### ISSUE TITLE
Add mock autospec support

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#535]
https://github.com/Nuitka/Nuitka/issues/522 approaches the problem of Nuikta compatibility from a bottom up approach, starting with the underlying components which are needed to build & test all other components.  The '& test' bit is critical, because otherwise it isnt possible to verify that the Nuitka-generated modules are acceptable.

The most critical failure is in `mock`, especially in its autospec functionality.

The failures look like
```
[  126s] ____________________ SpecSignatureTest.test_signature_class ____________________
[  126s] 
[  126s] self = <tests.testhelpers.SpecSignatureTest testMethod=test_signature_class>
[  126s] 
[  126s]     def test_signature_class(self):
[  126s]         class Foo(object):
[  126s]             def __init__(self, a, b=3): pass
[  126s]     
[  126s] >       mock = create_autospec(Foo)
[  126s] 
[  126s] tests/testhelpers.py:786: 
[  126s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[  126s] /home/abuild/rpmbuild/BUILDROOT/python-mock-3.0.5-11.1.i386/usr/lib/python3.7/site-packages/mock/mock.py:2376: in create_autospec
[  126s]     ???
[  126s] /home/abuild/rpmbuild/BUILDROOT/python-mock-3.0.5-11.1.i386/usr/lib/python3.7/site-packages/mock/mock.py:195: in _check_signature
[  126s]     ???
[  126s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[  126s] 
[  126s] func = <function SpecSignatureTest.test_signature_class.<locals>.Foo.__init__ at 0xb5fc5224>
[  126s] funcopy = <compiled_function _check_signature.<locals>.checksig at 0xb5e1ceac>
[  126s] 
[  126s] >   ???
[  126s] E   TypeError: Nuitka doesn't support __defaults__ size changes
[  126s] 
[  126s] /home/abuild/rpmbuild/BUILDROOT/python-mock-3.0.5-11.1.i386/usr/lib/python3.7/site-packages/mock/mock.py:208: TypeError
```

Given the nature of mock, it is quite likely that this problem will be occurring in test suites and the error shown would be something unrelated.

If it isnt feasible for Nuitka to add support for `__defaults__` size changes, we should look into  maybe some adjustments being made in the mock library to support Nuitka, or a Nuitka helper.

**Comment by kayhayen** [comment]
Getting tests to work is very important, however this will indeed be difficult. The mock tests however may be specific in needing this, or is `create_autospec` something very specific.

**Comment by kayhayen** [comment]
Generally, the tests should not be compiled, only the software under test. I am now not sure if this is separated here. So mock.py should be compiled, but not necessarily the code that excercises it for testing. Of course though, mocking ought to work on compiled functions ideally.

The may be just as we do for other things, monkey patching solutions, that work around this.

**Comment by jayvdb** [comment]
`create_autospec` is a part of the mock functionality, and it is very specific.  It inspects any other class at runtime to create mock objects of that class.  The classes being mocked should be compiled by Nuitka. The tests are not being compiled.  It is the inspection phase which is failing, and I believe it is irrelevant whether mock itself is compiled or not, but I am not 100% certain I ran uncompiled mock on a compiled library.

`graphviz` is one of the libraries which uses mock extensively and was failing as a result.

**Comment by kayhayen** [comment]
I would need an example, to look at this. For making copies of functions, there is now enhanced support, but often the code doing it needs a bit of help to use the `.clone` as documented in Nuitka User Manual.  Can you provide such an example? Most test runners appear to just work with Nuitka, as witnessed by the top 50 PyPI project we once did for GSoC.

**Comment by jayvdb** [comment]
This failure was in the `mock` libraries tests, which are now part of CPython, so if this test passes in Nuitake https://github.com/python/cpython/blob/59e0de4/Lib/test/test_unittest/testmock/testhelpers.py#L789 , this task can be closed.

**Comment by kayhayen** [comment]
I see, and `mock` itself would be hardcore for Nuitka anyway, not your everyday package in terms of what it wants to do with existing functions.
