### ISSUE TITLE
MinGW packages failing when built with Nuitka

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#537]
See note at https://github.com/Nuitka/Nuitka/issues/43#issuecomment-536833426 for how these are being built.

This issue details failures beyond those encountered at https://github.com/Nuitka/Nuitka/issues/522

Build:

- [ ] [pefile](https://build.opensuse.org/package/show/home:jayvdb:wine-python3:py37:packages-Nuitka/python-pefile) - doesnt emit `pefile`
- [ ] [PyYAML](https://build.opensuse.org/package/show/home:jayvdb:wine-python3:py37:packages-Nuitka/python-PyYAML) `fatal error: stdio.h: No such file or directory` also [pycryptodome](https://build.opensuse.org/package/show/home:jayvdb:wine-python3:py37:packages-Nuitka/python-pycryptodome)
- [ ] [redis](https://build.opensuse.org/package/live_build_log/home:jayvdb:wine-python3:py37:packages-Nuitka/python-redis/openSUSE_Tumbleweed/i586) & [maxminddb](https://build.opensuse.org/package/show/home:jayvdb:wine-python3:py37:packages-Nuitka/python-maxminddb) `AttributeError: Can't pickle local object 'BaseTestReader._check_concurrency.<locals>.lookup'`
- [ ] [cmarkgfm](https://build.opensuse.org/package/live_build_log/home:jayvdb:wine-python3:py37:packages-Nuitka/python-cmarkgfm/openSUSE_Tumbleweed/i586) - strange C++ in .c files
- [ ] [Pillow](https://build.opensuse.org/package/show/home:jayvdb:wine-python3:py37:packages-Nuitka/python-Pillow) - no error given?

Test (quite likely these may be due to different dependencies on Windows, missing from .spec files written for Linux only):
- [ ] [waitress](https://build.opensuse.org/package/show/home:jayvdb:wine-python3:py37:packages-Nuitka/python-waitress) `Test failed: <unittest.runner.TextTestResult run=565 errors=63 failures=0>`

Import fails (lots of these; no idea what is going on, yet):
- [ ] [pexpect](https://build.opensuse.org/package/show/home:jayvdb:wine-python3:py37:packages-Nuitka/python-pexpect)
- [ ] [bcrypt](https://build.opensuse.org/package/show/home:jayvdb:wine-python3:py37:packages-Nuitka/python-bcrypt)
- [ ] [CacheControl](https://build.opensuse.org/package/show/home:jayvdb:wine-python3:py37:packages-Nuitka/python-CacheControl)
- [ ] [MarkupSafe](https://build.opensuse.org/package/show/home:jayvdb:wine-python3:py37:packages-Nuitka/python-MarkupSafe)
- [ ] [msgpack](https://build.opensuse.org/package/show/home:jayvdb:wine-python3:py37:packages-Nuitka/python-msgpack)
- [ ] [Werkzeug](https://build.opensuse.org/package/show/home:jayvdb:wine-python3:py37:packages-Nuitka/python-Werkzeug)
- [ ] OpenSSL & [requests-toolbelt](https://build.opensuse.org/package/live_build_log/home:jayvdb:wine-python3:py37:packages-Nuitka/python-requests-toolbelt/openSUSE_Tumbleweed/i586)
- [ ] [itsdangerous](https://build.opensuse.org/package/live_build_log/home:jayvdb:wine-python3:py37:packages-Nuitka/python-itsdangerous/openSUSE_Tumbleweed/i586)

Out of memory:

(mingw32 cc1.exe appears limited to 2Gb of memory)

(possibly also due to extra tracing, and running under wine - it is easy to increase the memory on the workers for each of these)

- [ ] [Pygments](https://build.opensuse.org/package/show/home:jayvdb:wine-python3:py37:packages-Nuitka/python-Pygments)
- [ ] [pyasn1-modules](https://build.opensuse.org/package/show/home:jayvdb:wine-python3:py37:packages-Nuitka/python-pyasn1-modules)
- [ ] [peewee](https://build.opensuse.org/package/show/home:jayvdb:wine-python3:py37:packages-Nuitka/python-peewee)

Missing mingw deps (i.e. not in openSUSE): git, argon2, brotli, cmark, libyaml

Missing Python stdlib deps: mpdecimal, gdbm (not working in cpython cross-compile)

Failing because of Windows:
- [ ] [pytest-asyncio](https://build.opensuse.org/package/show/home:jayvdb:wine-python3:py37:packages-p2/python-pytest-asyncio) - test_subprocess test_subprocess_forbid raise NotImplementedError in stdlib asyncio

**Comment by kayhayen** [comment]
I honestly don't know how to use this, but I suspect it's outdated.
