### ISSUE TITLE
ImportError: cannot import name 'Image' from 'PIL'

### ISSUE THREAD

**Issue by Mikami382** [Nuitka/Nuitka#539]
I'm trying to compile my program, however upon finished running the following command 
`python -m nuitka --follow-imports easyak.py --show-progress --show-scons`

I ran .\EasyAK.exe through Windows Powershell
and received the following error before the program exitted:

`PS D:\Documents\EasyAK_R3> .\easyak.exe Traceback (most recent call last):   File "D:\Documents\EasyAK_R3\easyak.py", line 16, in <module>     from PIL import Image ImportError: cannot import name 'Image' from 'PIL' (C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\__init__.py)`

And these are the only warnings I got:

> Nuitka:INFO:Doing module local optimizations for 'cv2.data'.
Nuitka:INFO:Total memory usage before generating C code: 377.79 MB (396144640 bytes):
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py:432' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\Xlib\XK.py:47' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\Xlib\display.py:120' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\cx_Freeze\hooks.py:437' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\function_base.py:463' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\lib\utils.py:393' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\lib\utils.py:892' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\lib\utils.py:950' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:INFO:Total memory usage before running scons: 387.24 MB (406048768 bytes):

How can I resolve this issue? Please help.

**Comment by JorjMcKie** [comment]
> python -m nuitka --follow-imports easyak.py --show-progress --show-scons

This is not your complete command, right? I assume you are trying to do a standalone compile?

**Comment by JorjMcKie** [comment]
You also did not provide the **complete** required information for issue submission ...

**Comment by Mikami382** [comment]
Sorry, I was falling asleep the time I submitted this. Here are the additional informations:
`0.6.5
Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Users\Elite\AppData\Local\Programs\Python\Python37\python.exe
OS: Windows
Arch: x86_64`

I installed Nuitka via pip (I used the guide from https://nuitka.net/doc/user-manual.html#write-some-code-and-test)

I did not see any error upon executing the Nuitka commands except those warnings. However the error I got was the Module Not Found when I try to open the executable.

I am trying to make a compiled version of my python codes that works for other Windows machines. Did I miss any other commands?

**Comment by JorjMcKie** [comment]
I suggest you try compiling your program using ["hinted compilation"](https://github.com/Nuitka/NUITKA-Utilities/tree/master/hinted-compilation). This consists of two separate steps:

1. Analyze and log the import statements of your script via ``python get-hints.py yourscript.py``. This will create a JSON file with this information.

2. Compile via ``python nuitka-hints.py yourscript.py``. This invokes Nuikta providing it with all required parameters, including activation of any plugins.

This way you need a command line which is a lot shorter and less error prone. Also the compile time is much shorter and the resulting ``dist`` folder is smaller.

**Comment by Mikami382** [comment]
The first command gave me the following JSON file: 
https://puu.sh/EnTs4/04ef477e60.json

And the second one gave me this error:
(venv) D:\Documents\EasyAK_R3>python nuitka-hints.py easyak.py
NUITKA is compiling 'easyak.py' with these options:
 --standalone
 --remove-output
 --recurse-none

Nuitka:INFO:User plugin 'hinted-mods.py' is being loaded.
Nuitka:INFO:'hinted-mods.py' is adding the following options:
Nuitka:INFO:--enable-plugin=numpy
Nuitka:INFO:--enable-plugin=tk-inter
Nuitka:INFO:--enable-plugin=qt-plugins=sensible
Nuitka:INFO:--recurse-to for 228 imported modules.
Nuitka:INFO:
Nuitka:INFO:Injecting plug-in based pre load code for module 'tkinter':
Nuitka:INFO:    Need to make sure we set environment variables for TCL.
Problem with statement at easyak.py:1:
-> import os

Nuitka:INFO:Interrupted while working on '<Node 'PYTHON_MAIN_MODULE' with {'filename': 'easyak.py', 'main_added': False, 'mode': 'compiled'}>'.
Traceback (most recent call last):
  File "D:\Documents\EasyAK_R3\venv\lib\site-packages\nuitka\__main__.py", line 184, in <module>
    main()
  File "D:\Documents\EasyAK_R3\venv\lib\site-packages\nuitka\__main__.py", line 177, in main
    MainControl.main()
  File "D:\Documents\EasyAK_R3\venv\lib\site-packages\nuitka\MainControl.py", line 759, in main
    main_module = createNodeTree(filename=filename)
  File "D:\Documents\EasyAK_R3\venv\lib\site-packages\nuitka\MainControl.py", line 141, in createNodeTree
    Optimization.optimize(main_module.getOutputFilename())
  File "D:\Documents\EasyAK_R3\venv\lib\site-packages\nuitka\optimizations\Optimization.py", line 542, in optimize
    makeOptimizationPass(initial_pass=True)
  File "D:\Documents\EasyAK_R3\venv\lib\site-packages\nuitka\optimizations\Optimization.py", line 456, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "D:\Documents\EasyAK_R3\venv\lib\site-packages\nuitka\optimizations\Optimization.py", line 167, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "D:\Documents\EasyAK_R3\venv\lib\site-packages\nuitka\optimizations\Optimization.py", line 100, in optimizeCompiledPythonModule
    module.computeModule()
  File "D:\Documents\EasyAK_R3\venv\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 514, in computeModule
    trace_collection=self.trace_collection
  File "D:\Documents\EasyAK_R3\venv\lib\site-packages\nuitka\nodes\StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "D:\Documents\EasyAK_R3\venv\lib\site-packages\nuitka\nodes\FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "D:\Documents\EasyAK_R3\venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 549, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "D:\Documents\EasyAK_R3\venv\lib\site-packages\nuitka\nodes\StatementNodes.py", line 226, in computeStatement
    trace_collection.onExpression(expression=self.getExpression())
  File "D:\Documents\EasyAK_R3\venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 530, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "D:\Documents\EasyAK_R3\venv\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1005, in computeExpressionRaw
    return self.computeExpression(trace_collection=trace_collection)
  File "D:\Documents\EasyAK_R3\venv\lib\site-packages\nuitka\nodes\ImportNodes.py", line 401, in computeExpression
    trace_collection=trace_collection, module_name=imported_module_name
  File "D:\Documents\EasyAK_R3\venv\lib\site-packages\nuitka\nodes\ImportNodes.py", line 280, in _attemptRecursion
    module_package=module_package,
  File "D:\Documents\EasyAK_R3\venv\lib\site-packages\nuitka\nodes\ImportNodes.py", line 199, in _consider
    module_kind=module_kind,
  File "D:\Documents\EasyAK_R3\venv\lib\site-packages\nuitka\importing\Recursion.py", line 181, in decideRecursion
    module_filename, module_name, module_package, module_kind
  File "D:\Documents\EasyAK_R3\venv\lib\site-packages\nuitka\plugins\Plugins.py", line 251, in onModuleEncounter
    module_filename, module_name, module_package, module_kind
TypeError: onModuleEncounter() takes 4 positional arguments but 5 were given

**Comment by JorjMcKie** [comment]
You must be using an outdated Nuitka version.
This is mine:
```
nuitka>python -m nuitka --version
0.6.6rc6
Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Users\Jorj\AppData\Local\Programs\Python\Python37\python.exe
OS: Windows
Arch: x86_64
```
Installed from ``factory`` branch.
Also works with the ``develop`` branch which has this version:

```
python -m nuitka --version
0.6.6rc7
Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Users\Jorj\AppData\Local\Programs\Python\Python37\python.exe
OS: Windows
Arch: x86_64
```

**Comment by Mikami382** [comment]
Thank you, it seems to be working properly.
This may be out of topic but could you please answer these questions?

1. How do I add a window icon? Is there an argument for the command line to add an icon?
2. The program executes with a python console, is there a way to not show the console and only GUI?
3. And is there a way that I can reorganize the files such as put all the .pyd/other dlls into another folder  (like a subfolder /lib for example) and only leave the executable at root folder? 
4. Is there a command line to make an installer out of this? (That includes additional files that I need to add (like images folder)
Thus something like this:

```
root/ EasyAK.exe
root/ Lib/PyQT5
root/ Lib/PIL
root/ Lib/qt5qml

(custom files to be included)
root/ Images/image1.jpg
root/ Images/image2.jpg
```

**Comment by JorjMcKie** [comment]
With hinted compilation you can use all the normal invocation parameters of Nuitka. For example:

> How do I add a window icon? Is there an argument for the command line to add an icon?
The program executes with a python console, is there a way to not show the console and only GUI?

``python nuitka-hints.py --windows-icon=ICON_PATH --windows-disable-console yourscript.py``

The only condition is, that ``yourscript.py`` is the last parameter.

> And is there a way that I can reorganize the files such as put all the .pyd/other dlls into another folder (like a subfolder /lib for example) and only leave the executable at root folder?

No, the ``dist`` folder layout needs to be as it is created by Nuitka.

> Is there a command line to make an installer out of this? (That includes additional files that I need to add (like images folder)

You can add your own data files to the ``dist`` folder. This can be done by manual copying after the compile has finished. In this case, you can also decide, to put those data in the ``dist`` root, or a subfolder (e.g. ``images``) of your choice. Of course, ``yourscript.py`` must know how to locate them relative to the directory from where it is invoked.
You can also write a user plugin which does the copy and which is invoked by Nuitka. This would then look like: ``python nuitka-hints.py --user-plugin=data-for-yourscript.py yourscript.py``.

Or - my favorite - convert your data to Python modules, which you can import. In this way data are included by the compilation itself. See the attached example script, which contains a PNG image (the Nuitka logo) defined as a Python variable:
[pil-test.zip](https://github.com/Nuitka/Nuitka/files/3680558/pil-test.zip)
I have a little script which can convert any file into such a Python definition in base64 format - drop a note if you are interested.
There are various scripts in https://github.com/Nuitka/NUITKA-Utilities, which pack the ``dist`` folder in one file for installation purposes: ``exe-maker.py``, ``one-file-maker.py``.

**Comment by JorjMcKie** [comment]
I should add, that you can modify script ``nuitka-hints.py`` to adapt it to your special needs. For example, to alsways disable console windows. Already now it contains logic to do that if your script is named like this: ``yourscript.pyw``.

**Comment by Mikami382** [comment]
I'm having an issue with one-file-maker.py that you mentioned (for Windows).
I was able to execute the file that is in the dist folder that was made by nuitka-hints.py. 
So I assumed there's no problem with the exe itself.

I ran the following command

> python onefile-maker-windows.py

Selected the dist folder, and included the icon I wanted.
This is the output:
`Running command ["C:\Program Files (x86)\NSIS\makensis.exe" /DNAME="easyak.exe" /DSFXOUTPUT="D:\Documents\EasyAK_R3\easyak.exe" /DSOURCEDIR="D:\Documents\EasyAK_R3\easyak.dist.reduced\*" /DSFXEXECUTABLE="easyak.exe" /DDICTSIZE="128" /DICON=D:/Documents/EasyAK_R3/icon.ico /DUAC=user "D:\Documents\EasyAK_R3\easyak.dist.reduced.nsi"]. Please wait, this may take some time.

Command ["C:\Program Files (x86)\NSIS\makensis.exe" /DNAME="easyak.exe" /DSFXOUTPUT="D:\Documents\EasyAK_R3\easyak.exe" /DSOURCEDIR="D:\Documents\EasyAK_R3\easyak.dist.reduced\*" /DSFXEXECUTABLE="easyak.exe" /DDICTSIZE="128" /DICON=D:/Documents/EasyAK_R3/icon.ico /DUAC=user "D:\Documents\EasyAK_R3\easyak.dist.reduced.nsi"] returned with exit code [0]. Command output was:
Command line defined: "NAME=easyak.exe"
Command line defined: "SFXOUTPUT=D:\Documents\EasyAK_R3\easyak.exe"
Command line defined: "SOURCEDIR=D:\Documents\EasyAK_R3\easyak.dist.reduced\*"
Command line defined: "SFXEXECUTABLE=easyak.exe"
Command line defined: "DICTSIZE=128"
Command line defined: "ICON=D:/Documents/EasyAK_R3/icon.ico"
Command line defined: "UAC=user"
Processing config: C:\Program Files (x86)\NSIS\nsisconf.nsh
Processing script file: "D:\Documents\EasyAK_R3\easyak.dist.reduced.nsi" (ACP)

--------------------------------------------------------------------------------
OneFile generation return code: 0`

But I cannot open the executable. No error message or warnings. Did I miss anything?

**Comment by JorjMcKie** [comment]
I tried the script as well, and it worked for me!
With ``one-file-maker`` the program inside (made from ``yourscript.py``) is immediately executed after the ``dist`` folder has been unpacked to some temporary folder,
So maybe you just did not see that something was actually happening?
I just compiled a Qt based script with extension ".pyw", which displays an embedded PNG and wait forever until the display Window is clicked away. Everything worked as it should (no console window, etc.).

My only issue is that I could not unpack the installation exe to a non-temporary directory ...

**Comment by Mikami382** [comment]
Hmmm strange, I really do not see anything even after attempting to open it few times.
It did show loading cursor then normal mouse icon, and nothing is happening after that.

The executable that is exactly in the dist folder works fine though..

**Comment by JorjMcKie** [comment]
Just tried to unzip the installer exe ... this worked as well and is a (less elegant) way to install without executing ...

**Comment by Mikami382** [comment]
Thanks anyways. I'll close this one.
