### ISSUE TITLE
Choose Windows dependency mechanism earlier in standalone mode

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#541]
After doing a full compile, on an VM without a tty, Nuitka bails out in `raw_input` asking if I want to download depends.exe.  Unfortunately, as it isnt a tty, I can not reply.

Also, the isolated VM does not have network access, so the only available choice is to use `pefile`.

Ideally Nuitka detects isatty and network, and chooses `pefile` for me, and issues a warning that it is slower, buggier, whatever.

**Comment by jayvdb** [comment]
Also it seems that `depends.exe` is non-free, so it is not able to be added as a dependency in Wine/msys/MinGW packaging.

However it is available from chocolatey : https://chocolatey.org/packages/dependencywalker , so it could be a dependency of a chocolatey Nuitka package which atm doesnt exist https://chocolatey.org/packages?q=nuitka

**Comment by kayhayen** [comment]
There is an option to allow downloads for a while now, there is no choice anymore. One day we might have to do it, if Windows ARM becomes a real thing, with it never going to support that. The atttempts based on pefile must be considered failed. But Windows ARM will never be a real thing, unless that kind of tool emerges anyway.
