### ISSUE TITLE
Issue with QThread

### ISSUE THREAD

**Issue by Mikami382** [Nuitka/Nuitka#542]
Version
`0.6.6rc6
Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Users\Elite\AppData\Local\Programs\Python\Python37\python.exe
OS: Windows
Arch: x86_64`

I installed Nuitka through PIP.

I found an issue with QThread, I am using PyQT5.
I used nuitka-hints.py to compile my python codes.
The program works fine at the beginning until I start using QThread. 
It seems to be freezing the UI, but the thread continues to run.
UI will be responsive once the thread finishes.
My assumption would be Nuitka not supporting QThread, is this the case?

For additional info, I was able to run the the QThread with cx_freeze/pyinstaller/or through python interpreter without freezing the UI.

What could be wrong?

**Comment by Mikami382** [comment]
Here are the snippets, this what starts the thread:
```
    def createWorkerThread(self):
        self.worker = WorkerObject()
        self.worker_thread = QThread()
        self.worker.queue = {}

        self.worker.KMap = self.dialog.ui.keyMap.keySequence().toString()
        self.worker.KAttack = self.dialog.ui.keyAttack.keySequence().toString()
        self.worker.KInteract = self.dialog.ui.keyInteract.keySequence().toString()
        self.worker.KJournal = self.dialog.ui.keyJournal.keySequence().toString()
        self.worker.KSwap = self.dialog.ui.keySwap.keySequence().toString()
        self.worker.KCard = self.dialog.ui.keyCardDuel.keySequence().toString()

        self.worker.deckStandard = str(self.dialog.ui.deckStandard.currentText())
        self.worker.deck3StarWar = str(self.dialog.ui.deck3StarWar.currentText())

        # Setup the worker object and the worker_thread.
        self.worker.moveToThread(self.worker_thread)
        self.worker_thread.start()
```

And this is the worker
```
class WorkerObject(QObject):
    signalStatus = pyqtSignal(bool)
    signalLog = pyqtSignal(str)
    signalQueue = pyqtSignal(int, int)

    # 0 = idle
    # 1 = processing
    # 2 = done

    def __init__(self, parent=None):
        super(self.__class__, self).__init__(parent)
        self.isRunning = False
        self.KMap = None
        self.KAttack = None
        self.KInteract = None
        self.KJournal = None
        self.KSwap = None
        self.KCard = None

        self.deckStandard = None
        self.deck3StarWar = None

    def stop(self):
        self.isRunning = False

    def log(self, text):
        self.signalLog.emit(str(text))

    @pyqtSlot()
    def startWork(self):

        self.isRunning = True
        self.signalStatus.emit(True)

        sleep(10)

        self.signalStatus.emit(False)
        self.log("Done!")
        return

```

When in sleep state, the UI simply stopped being responsive. This does not happen in the pyhthon intreperter itself or the cx-freeze like I mentioned. What am I missing?

**Comment by JorjMcKie** [comment]
@Mikami382 - can you please give me the (or some) complete script? I would like to check if a different option for using the ``qt-plugins`` would help.
Of course you could also try compiling without hinted compilation while using exactly the same parameters as you saw hinting generated ... **_except:_** instead of ``--enable-plugin=qt-plugins=sensible`` please use ``--enable-plugin=qt-plugins=all``.
It is worth a try ...

Background: Qt comes with a lot of stuff. Option ``sensible`` represents a commonly used subset of it. So far, hinted compilation does not try to analyze the detail usage profile of the script - but it would certainly be possible. And I could replace the ``sensible`` option by something else when encountering things like QThread.

**Comment by Mikami382** [comment]
Yes of course, I attached it in the following post (please understand that I may delete this later)
Pardon my terrible logics/writings, it is my personal project. I am studying python. 

[Scripts.zip](https://github.com/Nuitka/Nuitka/files/3683160/Scripts.zip)

Do let me know if you need anything else!

**Comment by JorjMcKie** [comment]
ok, please allow me some time.
I am busy for the rest of the day (Venezuela time) ...

**Comment by JorjMcKie** [comment]
Started trying your scripts. Was a bit frightened that elevated user access is required to execute it ...

Then I am being asked for a license number?
You are aware of how to correctly detect being compiled by Nuitka:

```python
compiled = globals().get("__compiled__", False)
if compiled:
    print(
        "Running compiled (Nuitka v%i.%i.%i-%s)"
        % (compiled.major, compiled.minor, compiled.micro, compiled.releaselevel)
    )
```

**Comment by Mikami382** [comment]
Yes, it is an auto click program (macro), to be able to click the target program, it requires admin access.
And about the license, you can just add `return 1` on `checkLicense ` before anything..

And thank for you for letting me know about that, I was so focused on making it work on Nuitka first before anything else.. 

Were you able to identify/fix the issue?

**Comment by JorjMcKie** [comment]
Thanks for the infos.
No, I was hesitant re what may happen if I do the wrong things ;-)

**Comment by Mikami382** [comment]
After you get past through the license check, just add any task to Queue Tasks tab and click Start. 
The QThread should start immediately and sleep for 10 seconds (Line 433), this is where it freezes everything completely until the the thread stops.

It is working fine on other compilers (cx-freeze pyinstaller) but not here. The main reason why I really wanted to use Nuitka is because it is (relatively) harder to decompile compared from the others (machine codes).

Please help me get this working x)

**Comment by JorjMcKie** [comment]
Unfortunately, this did not make any difference.
I seem to remember that Qt threading has been some kind of issue here earlier - maybe you should search the issue database for qthread ...
A weird thing with your script:
When the main script ends, that does not end everything it has triggered off: other windows are still showing up, etc.
This of course means, that ``get-hints.py`` never gets to read all the logfiles created by all subprocesses. It will hence create an incomplete consolidated JSON file ... Is there no way to wait in the main task until all subs have finished?

**Comment by Mikami382** [comment]
Could you elaborate what you mean by "other windows are still showing up?" It only has one window GUI as far as I remember..

**Comment by JorjMcKie** [comment]
Trying to catch everything in one screen:
![img1](https://user-images.githubusercontent.com/8290722/66164672-33355600-e601-11e9-85fc-efb74bc0c42e.jpg)

**Comment by Mikami382** [comment]
Ah, that may be because when you dont have admin access, the script makes you to "re-run" the script with admin access, so first script (without admin access) exits and the second "re-run" one opens with UAC popup.

I think the solution for this would be temporarily add `return True` to `is_admin()` function before anything else is executed in that method. So it doesnt have to re-run the script.

**Comment by JorjMcKie** [comment]
Ah correct, that made it.
But the blocking issue is still unresolved ...

**Comment by Mikami382** [comment]
I guess there's no way to use Nuitka with QThread for now..

**Comment by JorjMcKie** [comment]
I'm afraid you are right.

**Comment by egas77** [comment]
There are still problems with QThread right now?

**Comment by kayhayen** [comment]
Last time I discussed with them, they were not aware of any issues. I suggest to re-open a new issue, or to use PySide2 or PySide6 where I know such issues do not exist.

**Comment by stevencnix** [comment]
PyQT5 version 5.15.6 appears to still only run QThreads on the main thread after compiling with Nuitka even if using the qt plugins provided by Nuitka. Is there a timeline on having this issue fixed?

**Comment by kayhayen** [comment]
Like I said, since they are not aware of the issue, I would say never. Your best bet is PySide2 or PySide6: https://nuitka.net/pages/pyside2.html

I doubt there will be updates for PyQt5 though. For PySide2 I solved the issue myself. You can of course do the same for PyQt5 if you are very interested, but since PySide2 is compatible, the cheapest path would be to switch.

**Comment by stevencnix** [comment]
Yeah I switched over my whole project to PySide2 to realize that the version was too new and I couldn't use the PySide2 plugin.  I guess I will give PySide6 a try here soon. It honestly isn't a game ender to use PyInstaller. Nuitka just had more potential for what I need.

**Comment by kayhayen** [comment]
What do you mean, PySide2 being too new? Also, curious, where do you see the potential?

**Comment by kayhayen** [comment]
Yes, I wasn't aware of any update of PySide2 after that, actually I was pretty sure there won't be any. I guess, I need to update the version check then, thanks for your feedback. Seems you want very important things from Nuitka, and I can see only it deliver on that, but what price would you associate with that goals of yours?

**Comment by stevencnix** [comment]
I appreciate you responding and glad I was able to inform you of the PySide2 update.

**Comment by kayhayen** [comment]
Not sure why it wasn't clear enough, but the message is this:

> Nuitka-Plugins:WARNING: pyside2: This PySide2 version only partially supported through workarounds, full support: https://nuitka.net/pages/pyside2.html

It is partially supported. I will update the page however, it is through workarounds applied by the plugin. I spent (too much) time on making some things work with wrapper functions, but that only goes so far. The patches for PySide2 are only in the Nuitka commercial wheels. The page is very unclear about it, also PySide6 is more of a thing now.
