### ISSUE TITLE
Nuitka “\urllib3\util\ssl_.py ssl_wrap_socket FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by programjio** [Nuitka/Nuitka#547]
Python installed version python3.6  C:\python3  
Compiler :C:\MinGW64\mingw64\opt\lib\python2.7
Environment : Windows7 

Issue : python script runs with no errors . Nuitka converted exe fails to run,complete issue details
urllib3\util\ssl_.py ssl_wrap_socket FileNotFoundError

https://stackoverflow.com/questions/58189265/nuitka-urllib3-util-ssl-py-ssl-wrap-socket-filenotfounderror-errno-2-no-su

i found some issues that though my installed python version is python 3.6.x the compiler has the python2.7 in the directory C:\MinGW64\mingw64\opt\lib\python2.7  also this has no urllib3 related files .

how to compile urllib3 to get  urllib3.pyc and urllib3.pyo file . i hope getting this file there would solve the issue.

Or 

Something else is throwing the error in exe.

**Comment by programjio** [comment]
@kayhayen Could you please help with some hint ,i tried with GCC, VC++ visual studio in all i got the same error.
It looks to be a major issue .Any hint.

**Comment by JorjMcKie** [comment]
@programjio - is this a standalone compile?

**Comment by kayhayen** [comment]
@programjio the python inside MinGW64 is not used or supported at this time, if you don't specify it, nothing will make it used, should be totally unrelated to that presence then.

**Comment by programjio** [comment]
@kayhayen thank you for your feedback . python inside MinGW64 is not used or supported at this time does this mean we cannot use it .

Tried with Visual studio 2017 community edition VC\Tools\MSVC\14.23.28105\bin\HostX64\x64\cl.exe (MSVC 14.2) facing the same issue.

More over thought VS 2019 would help resolving this issue now i am struck with the same issue reported here  https://github.com/Nuitka/Nuitka/issues/468.

Giving the details here completely to get  some support .

If this is wrong doing ,share me how i can get working exe .

Nuitka:DEBUG:D:/python/deri_v2_api_building/der_test_api/deribit-api-clients-master_api2/deribit-api-clients-masterAPI_V2/python/testing.py:1 : new_statements : Original parameter variable value param
eter variable 'message' is not released.
Nuitka:DEBUG:D:/python/deri_v2_api_building/der_test_api/deribit-api-clients-master_api2/deribit-api-clients-masterAPI_V2/python/testing.py:1 : new_statements : Removed useless try, all handlers remov
ed.
Scons command: C:\Users\mm\AppData\Local\Programs\Python\Python37\python.exe -W ignore C:\Users\mm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy
\bin\scons.py -f C:\Users\mm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\SingleExe.scons --jobs 1 --warn=no-deprecated --no-site-dir --debug=explain name=testing re
sult_name=D:\python\deri_v2_api_building\der_test_api\deribit-api-clients-master_api2\deribit-api-clients-masterAPI_V2\python\output\testing.dist\testing source_dir=D:\python\deri_v2_api_building\der_
test_api\deribit-api-clients-master_api2\deribit-api-clients-masterAPI_V2\python\output\testing.build debug_mode=false python_debug=false unstripped_mode=false module_mode=false full_compat=false expe
rimental= trace_mode=false python_version=3.7 target_arch=x86_64 python_prefix=C:\Users\mm\AppData\Local\Programs\Python\Python37 nuitka_src=C:\Users\mm\AppData\Local\Programs\Pyth
on\Python37\lib\site-packages\nuitka\build nuitka_cache=C:\Users\mm\AppData\Local\Nuitka\Nuitka\Cache module_count=448 result_exe=D:\python\deri_v2_api_building\der_test_api\deribit-api-clie
nts-master_api2\deribit-api-clients-masterAPI_V2\python\output\testing.dist\testing.exe cache_mode=true standalone_mode=true frozen_modules=168 show_scons=true noelf_mode=true
scons: Reading SConscript files ...
Scons: Tools= ['default']

scons: warning: MSVC_USE_SCRIPT set to False, assuming environment set correctly.
File "C:\Users\mm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\SingleExe.scons", line 506, in createEnvironment
Scons: Initial CC: cl
Scons: Initial CCVERSION: None
Scons: Initial CXX: $CC
Scons: Initial CXXVERSION: None
Scons: Picked compiler: cl
Scons: Picked name: cl
Scons: Using C11 mode: False
Scons: Compiler used C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX64\x64\cl.exe (MSVC 14.2)

Scons: Using resource mode: win_resource
Scons: Told to run compilation on 1 CPUs.
Scons: Unable to find clcache.exe, consider reading user manual.
Scons: Using scons cache inside build directory.
TypeError: write() argument must be str, not bytes:
  File "C:\Users\mm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\SingleExe.scons", line 1806:
    os.path.join(source_dir, "cache-" + target_arch + "-" + python_abi_version)
  File "C:\Users\mm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.1.0\SCons\Script\SConscript.py", line 666:
    env = self.factory()
  File "C:\Users\mm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.1.0\SCons\Script\SConscript.py", line 646:
    default_env = SCons.Defaults.DefaultEnvironment()
  File "C:\Users\mm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.1.0\SCons\Defaults.py", line 88:
    _default_env = SCons.Environment.Environment(*args, **kw)
  File "C:\Users\mm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.1.0\SCons\Environment.py", line 991:
    apply_tools(self, tools, toolpath)
  File "C:\Users\mm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.1.0\SCons\Environment.py", line 107:
    env.Tool(tool)
  File "C:\Users\mm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.1.0\SCons\Environment.py", line 1798:
    tool(self)
  File "C:\Users\mm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.1.0\SCons\Tool\__init__.py", line 306:
    self.generate(env, *args, **kw)
  File "C:\Users\mm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.1.0\SCons\Tool\default.py", line 41:
    SCons.Tool.Tool(t)(env)
  File "C:\Users\mm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.1.0\SCons\Tool\__init__.py", line 306:
    self.generate(env, *args, **kw)
  File "C:\Users\mm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.1.0\SCons\Tool\mslink.py", line 314:
    msvc_setup_env_once(env)
  File "C:\Users\mm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.1.0\SCons\Tool\MSCommon\vc.py", line 654:
    msvc_setup_env(env)
  File "C:\Users\mm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.1.0\SCons\Tool\MSCommon\vc.py", line 773:
    d = msvc_find_valid_batch_script(env,version)
  File "C:\Users\mm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.1.0\SCons\Tool\MSCommon\vc.py", line 721:
    d = script_env(vc_script, args=arg)
  File "C:\Users\mm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.1.0\SCons\Tool\MSCommon\vc.py", line 600:
    stdout = common.get_output(script, args)
  File "C:\Users\mm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.1.0\SCons\Tool\MSCommon\common.py", line 203:
    sys.stderr.write(stderr)
END

Atleast anyone method that will solve my problem and if i get exe that would run smoothly is fine for me .Please support with your expertise.


This is the Build script used to build the exe ,let me know if any changes needed
#####################################################
#               NUITKA BUILD SCRIPT                 #
#####################################################
# Author: Matic Kukovec
# Date: April 2018

import os
import platform


NUITKA = "C:/Users/mm/AppData/Local/Programs/Python/Python37/Scripts/nuitka3-script.py"  # Path where my nuitka3-script.py is
CWD = os.getcwd().replace("\\", "/")
#MSVC = "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build/vcvars64.bat"
MSVC = "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build/vcvars64.bat"
PYTHON_VERSION = "3.7"
PYTHON_EXE_PATH= "C:/Users/mm/AppData/Local/Programs/Python/Python37/python.exe"
NUMBER_OF_CORES_FOR_COMPILATION = 1 # 1 is the safest choice, but you can try more

# Generate command
command = '"{}" amd64 &'.format(MSVC)
command += "{} ".format(PYTHON_EXE_PATH)
command += "{} ".format(NUITKA)
#command += "--python-version={}".format(PYTHON_VERSION)
command += "--output-dir={}/output ".format(CWD)
command += "--verbose "
command += "--jobs={} ".format(NUMBER_OF_CORES_FOR_COMPILATION)
command += "--show-scons "
# command += "--windows-disable-console "
# command += "--icon={}/myicon.ico ".format(CWD)
command += "--standalone "
# command += "--run "
command += "{}/testing.py".format(CWD)
os.system(command)

print("END")

Have i set the path and environment variables that too need help .

Windows 7&10 platform with python 3.7.4 version i tried and 3.6 ,3.8 as well tried nothing give output

**Comment by programjio** [comment]
i have no clue why this is failing to generate the exe now ,switched to VS2019 nothing working need your help .

@kayhayen kayhayen  i am ready to share me source code to you over email as well.

not closed ticket ...

**Comment by programjio** [comment]
@kayhayen @JorjMcKie 
Can you please look into this issue ,i see there are several urllib3 errors that blocks the program execution.
I could not get into a solution and this is pending more than two weeks.
https://nuitka.net/posts/urllib3-wheel-with-nuitka.html

https://github.com/Nuitka/Nuitka/issues/557  (similar issue)

https://github.com/Nuitka/Nuitka/issues/413

**Comment by JorjMcKie** [comment]
@programjio  - I am willing to help, but I would need the script you actually want to get a standalone exe for. If you cannot shre it, I would at least need a stripped-down version which contains all the relevant imports.
I am successfully using the VS 2017 C compiler for all my nuitka scripts. So if I am able to get your script comiled, we can assume, that Nuitka is out of the issue loop.

**Comment by programjio** [comment]
@kayhayen @JorjMcKie Thank you for your feedback .I am ready to share you the full script with you.
This gives me a hope .Share me your email or the way i can connect you . We shall discuss over email and the final result we provide here for the user benefit.

I am trying now the Visual Studio 2019. Can you tell me what option i need to choose in VS2017 installation to be of sure of i am using the same option as you.

**Comment by JorjMcKie** [comment]
> @kayhayen @JorjMcKie Thank you for your feedback .I am ready to share you the full script with you.
> This gives me a hope .Share me your email or the way i can connect you . We shall discuss over email and the final result we provide here for the user benefit.

You can use jorj.x.mckie@outlook.de

> 
> I am trying now the Visual Studio 2019. Can you tell me what option i need to choose in VS2017 installation to be of sure of i am using the same option as you.

I am not using any special option here. Just the normal ``python -m nuitka --standalone ...`` is doing the job. My VS 2017 community edition is also vanilla, and I am using it to compile my non-Nuitka Python extensions mainly. On occasion, I am also using the mingw64 compiler, so I have a few tricks at hand to help nuitka follow the switching ...

**Comment by programjio** [comment]
@JorjMcKie i have sent you an email to the given email id .
If this could solve my build issue and exe crash that will be nice.

**Comment by JorjMcKie** [comment]
@programjio - just sent you a response ...

**Comment by JorjMcKie** [comment]
Based on our off-the-record, I think we can close this now.
For others interested:
The main reason was missing certificates data files for a vanilla urllib3 application.
I will include the update in the ``jorj`` branch ...
