### ISSUE TITLE
TypeError: descriptor 'iter_modules' requires a 'nuitka_module_loader' object but received a 'str'

### ISSUE THREAD

**Issue by glitchassassin** [Nuitka/Nuitka#548]
**Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)**

```
> py -3 -m nuitka --version
0.6.6rc7
Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]
Executable: C:\Python37\python.exe
OS: Windows
Arch: x86
```

**How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.**

Python: Windows executable installer
Nuitka: Cloned git repository, then `pip3 install .` inside the repo

**If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
  that demonstrates the issue i.e a small piece of code which reproduces
  the issue and can be run with out any other (or as few as possible)
  external dependencies.**

The following snippet yields the error:

```
import pkgutil

for module_info in pkgutil.iter_modules():
    print(module_info)
```

Compile with `py -3 -m nuitka .\nuitka_test.py`

When the resulting nuitka_test.exe is run, the following error results:

```
Traceback (most recent call last):
  File "C:\Users\jonwi\Documents\sandbox\nuitka_test.py", line 3, in <module>
    for module_info in pkgutil.iter_modules():
  File "C:\Python37\lib\pkgutil.py", line 130, in iter_modules
    for name, ispkg in iter_importer_modules(i, prefix):
  File "C:\Python37\lib\functools.py", line 840, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Python37\lib\pkgutil.py", line 140, in iter_importer_modules
    return importer.iter_modules(prefix)
TypeError: descriptor 'iter_modules' requires a 'nuitka_module_loader' object but received a 'str'
```

**Context:**

I am attempting to compile an app that uses pyexcel, which relies on lml for lazy-loading plugins. The issue seems to trace back to this snippet. My guess is this may be a collision with the Nuitka implementation of a sys.meta_path hook, but I'm not familiar enough with C to confirm or hazard a guess at a fix.

**Comment by jayvdb** [comment]
I can reproduce this with Nuitka 0.6.11 while testing `sbp` https://github.com/swift-nav/libsbp/blob/master/python/sbp/msg.py#L52

```py
tests/sbp/test_table.py:11: in <module>
    from sbp.msg import SBP
sbp/msg.py:86: in <module>
    parse_jit = try_import_jit()
sbp/msg.py:52: in try_import_jit
    if parse_jit_name in (name for loader, name, ispkg in iter_modules()):
sbp/msg.py:52: in <genexpr>
    if parse_jit_name in (name for loader, name, ispkg in iter_modules()):
/usr/lib/python3.8/pkgutil.py:130: in iter_modules
    for name, ispkg in iter_importer_modules(i, prefix):
/usr/lib/python3.8/functools.py:875: in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
/usr/lib/python3.8/pkgutil.py:140: in iter_importer_modules
    return importer.iter_modules(prefix)
E   TypeError: descriptor 'iter_modules' for 'nuitka_module_loader' objects doesn't apply to a 'str' object
```

**Comment by jayvdb** [comment]
https://github.com/Nuitka/Nuitka/issues/603 is another case of this problem with @pyexcel . ping @chfw & @kayhayen

**Comment by kayhayen** [comment]
This has been working with Nuitka for a while already, was solved in a duplicate report. This one got overlooked until now.
