### ISSUE TITLE
Fatal error C1002: compiler is out of heap space in pass 2

### ISSUE THREAD

**Issue by muhammeteminturgut** [Nuitka/Nuitka#554]
Version:
`C:\Users\MEmin\AppData\Local\Programs\Python\Python35-32>python -m nuitka --version
0.6.5
Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)]
Executable: C:\Users\MEmin\AppData\Local\Programs\Python\Python35-32\python.exe
OS: Windows
Arch: x86`

I installed Nuitka through pip.
Previously i was distributing my program with pyinstaller. 
However, I decided to use nuitka because of pyinstaller has low performance and to prevent decompile codes.
But I always get this error code. what is the problem?

`C:\Users\MEmin\AppData\Local\Programs\Python\Python35-32>python -m nuitka --standalone --plugin-enable=tk-inter --experimental=use_pefile --experimental=use_pefile_recurse --experimental=use_pefile_fullrecurse "C:\Users\MEmin\Desktop\Dictater_1.1.5\Dictater.py"
Nuitka:INFO:Injecting plug-in based pre load code for module 'tkinter':
Nuitka:INFO:    Need to make sure we set environment variables for TCL.
Nuitka:WARNING:Use '--plugin-enable=pylint-warnings' for: Understand PyLint/PyDev annotations for warnings.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\MEmin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\PIL\Image.py:432' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\MEmin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\googleapiclient\http.py:384' may require use of '--include-plugin-directory' or '--include-plugin-files'.
cl /FoDictater.build\module.pyasn1_modules.rfc2459.obj /c "Dictater.build\module.pyasn1_modules.rfc2459.cpp" /TP /nologo /EHsc /J /Gd /Ox /MT /D_NUITKA_EXPERIMENTAL_USE_PEFILE /D_NUITKA_EXPERIMENTAL_USE_PEFILE_RECURSE /D_NUITKA_EXPERIMENTAL_USE_PEFILE_FULLRECURSE /D_NUITKA_STANDALONE /D_NUITKA_SYSFLAG_BYTES_WARNING=0 /D_NUITKA_SYSFLAG_NO_SITE=0 /D_NUITKA_SYSFLAG_VERBOSE=0 /D_NUITKA_SYSFLAG_UTF8=0 /D_NUITKA_SYSFLAG_OPTIMIZE=0 /D__NUITKA_NO_ASSERT__ /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=169 /D_NUITKA_MODULE_COUNT=731 /D_NUITKA_EXE /Iinclude /IPC /IDictater.build /Ilib\site-packages\nuitka\build\include /Ilib\site-packages\nuitka\build\static_src
scons: *** [Dictater.build\module.pyasn1_modules.rfc2459.obj] Error 1
C:\Users\MEmin\AppData\Local\Programs\Python\Python35-32\Dictater.build\module.pyasn1_modules.rfc2459.cpp(1808) : fatal error C1002: compiler is out of heap space in pass 2`

**Comment by kayhayen** [comment]
I looked at the file, and it seemed innocent at first, but made Nuitka use 73 for optimization and up to 100 MB for code generation itself, I think there is something astray there.

**Comment by kayhayen** [comment]
Oh, my Linux gcc is using 3.2G right now on this in a single module compilation, I am totally at loss from looking at the Python why this is. This is not going to fit in the 2GB that 32 bits will use on your system.

Your options are to wait until I figure out the scalability issue here, or to try 64 bits Python and be even more patient, since that file will compile for a long, long time I regret. @muhammeteminturgut

**Comment by kayhayen** [comment]
So, the 130 classes are the only real special thing I can see. The code for those and their bodies is in what we call an outline in Nuikta, which effectively is inlined, giving a huge C function body when the C code is generated.

Also, the Python3 effort to create a class, select the meta class, calling it, checking for errors, is there for every class. This has the advantage that static optimization could be more easily applied, but these are all cases, where it will not be done (yet). Python3 class definitions allow to much things to happen.

**Comment by kayhayen** [comment]
This is delayed until 3.8 is fully supported, which is hopefully not far off. But I believe there is a bunch of scalability work exposed by this file.

**Comment by kayhayen** [comment]
That said, I am going to add these modules of pyasn to the unworthy ones, which will mean they will be included as bytecode. They are only run once and have no compiled code that ever runs again, so going via C is a total waste.

**Comment by muhammeteminturgut** [comment]
> Oh, my Linux gcc is using 3.2G right now on this in a single module compilation, I am totally at loss from looking at the Python why this is. This is not going to fit in the 2GB that 32 bits will use on your system.
> 
> Your options are to wait until I figure out the scalability issue here, or to try 64 bits Python and be even more patient, since that file will compile for a long, long time I regret. @muhammeteminturgut

Can you add  to nuitka `IMAGE_FILE_LARGE_ADDRESS_AWARE` flag for compilation under Windows?
[https://stackoverflow.com/a/18282931/7063350](https://stackoverflow.com/a/18282931/7063350)

**Comment by kayhayen** [comment]
@muhammeteminturgut that would be the C compiler to be compiled with it, since it that is what is being used. I know that MSVC has a cross compiler that could be used, I am not sure if it is. For MinGW64 I don't know.

Using 64 bits for Python and MinGW64 seems the realistic workaround right now. Not sure how much they care about their 32 bit variant in MinGW64, but they would have to use it. Since it's most likely going to slow down things (there is always a price), I doubt they will.

**Comment by kayhayen** [comment]
The `IMAGE_FILE_LARGE_ADDRESS_AWARE` is for binaries created, so this is unrelated, and using 32 bits is bad. There is now documentation on low memory in the User Manual, that suggests some things that might actually help in this situation, but that is about it: https://nuitka.net/doc/user-manual.html#memory-issues-and-compiler-bugs
