### ISSUE TITLE
No module named 'win32api' while using Nuitka-Package compilation

### ISSUE THREAD

**Issue by RahulBadenkal** [Nuitka/Nuitka#555]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

`0.6.5`
`Python: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]`
`Executable: C:\Users\<user>\Desktop\project\venv\Scripts\python.exe`
`OS: Windows`
`Arch: x86_64`

* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.

`Installed python from python.org as a windows executable.`
`Installed nuitka via pip`
`Working in a virtualenv created using PyCharm`

I am trying to create multiple exes all of which depend on a common python package. So I am trying something like this:

<pre>
project/      
      - commonPackage
          - commonPackage.pyd
      - exe1
          - dlls and other files for exe1
      - exe2
          - dlls and other files for exe2
</pre>
The commonPackage dir will contain a single commonPackage.pyd

So I did the following:
(1) For Common package
- Created a new virtual env
- Installed pywin32: `pip install pywin32`
- Compiled Using: `>python -m nuitka --mingw64 --module commonPackage --include-package="commonPackage" --recurse-all`
- Project Structure for package: 
<pre>
-myPackage
    - commonPackage
        - __init__.py
        - excelutils.py
</pre>
- excelutils.py Code:
```python
print('Inside Package')
import time
import win32com.client


def open_word():
    word = win32com.client.DispatchEx("Word.Application")  # Using DispatchEx for an entirely new Word instance
    word.Visible = True
    print('Sleeping.....')
    time.sleep(10)
    print('Woke up')
    word.Quit()
```
(2) For first exe (Created using pyinstaller)
- Created a new virtual env
- installed pyinstaller: `>pip install pyinstaller`
- Compiled Using: `>pyinstaller --clean -D run.py`
- Project Structure :
<pre>
-myexe/
    - run.py
</pre>
- run.py Code:
```python
import sys
import os

if hasattr(sys, 'frozen'):
    basis = sys.executable
    BASEDIR = os.path.dirname(basis)
    print(BASEDIR)
    new_path = os.path.abspath(os.path.join(BASEDIR, '../commonPackage/'))
    sys.path.append(new_path)

from core.excelutils import open_word

print('Hello World')
open_word()
```
(3) Then I copy the above compiled files as below:
<pre>
project/      
      - commonPackage
          - commonPackage.pyd (generated using nuitka, around 3.4 MB)
      - myexe
          - dlls and other files for exe (generated using pyinstaller)
</pre>

(4) Now, executing the exe from command line gives this error:
```
Sys.path
['C:\\Users\\GyRo\\Desktop\\projects2\\python-only\\dist\\nuitka-issue\\myexe\\base_library.zip', 'C:\\Users\\GyRo\\Desktop\\projects2\\python-only\\dist\\nuitka-issue\\myexe', 'C:\\Users\\GyRo\\Desktop\\projects2\\python-only\\dist\\nuitka-issue\\commonPackage']
Inside Package
Traceback (most recent call last):
  File "run.py", line 14, in <module>
  File "C:\Users\GyRo\Desktop\projects2\python-only\dist\nuitka-issue\commonPackage\commonPackage\excelutils.py", line 4, in <module commonPackage.excelutils>
  File "C:\Users\GyRo\Desktop\projects2\python-only\dist\nuitka-issue\commonPackage\win32com\__init__.py", line 5, in <module win32com>
ModuleNotFoundError: No module named 'win32api'
[7068] Failed to execute script run
```

**Comment by RahulBadenkal** [comment]
When I do the same thing but instead of pywin32, use some other package (let's say appdirs `pip install appdirs`) in commonPackage, then the whole set up works. So I think the issue is that pywin32 is not being bundled in somePackage.pyd properly.

**Comment by kayhayen** [comment]
The way you should do this is by packaging a wheel. Once it works with standard setuptools, you just enable using Nuitka and it's supposed to work. This manual method is very error prone and requires for you to know what you are doing: https://nuitka.net/doc/user-manual.html#use-case-5-setuptools-wheels
