### ISSUE TITLE
How do you protect contained strings on the generated executables?

### ISSUE THREAD

**Issue by gggggeorge** [Nuitka/Nuitka#556]
Hello,

**python -m nuitka --version**

```
0.6.6rc5
Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
Executable: C:\Python35\python.exe
OS: Windows
Arch: x86_64
```

----
I've been using Nuitka, and it's working great, but I have a question regarding how strings are encoded in the created *.exe:

1. literal strings
2. functions names, parameters, etc.

I can easily pull up a text editor, and search for (1) and (2), and easily see them embedded in the executable -which I don't know of anyone using Nuitka would probably want (I certainly do not).

Is there a way to pass a compiler flag to have (1) and (2) encoded differently?

I'm using the MinGW64 compiler.

Here is a compiler I might be interested in trying (movfuscator -"The single instruction C compiler"):

https://github.com/Battelle/movfuscator

I tried searching for some documentation to either "switch out" to a different compiler, or to pass flags (when I run **python -m nuitka --standalone ...**) to the compiler or Nuitka, but I didn't see anything that helped me, or at least that I could understand -sorry about that.

Also, the interesting thing is I seem to find the strings in the *.exe, but not in the *.o files...?

----
Any hints or ideas would be most welcome!  :smiley:

Thanks,
George Hynes
10/21/2019 1:32pm ET

**Comment by math-artist** [comment]
+1 for the question regarding literal strings

I am currently learning Nuitka (I have discovered the project 2 weeks ago and I really like it) and I am working on a work-around to obfuscate some code that is not currently compatible with Nuitka (I have a project with the UI based on PySide2).

My current attempt is to use AES encryption on PySide2 dependent modules and Noitka on other modules, including the main script where I need to hide an encryption key.

I read somewhere that with Nuitka executables, like Cython, function names are easy to read, but I am wondering if there is way to make string variables less readily available in the executable.

Thanks

**Comment by Nexuzzzz** [comment]
it would be great if a cli flag could be added to strip certain data, and perhaps a flag to obfuscate data (like PyInstallers ""--key flag)

**Comment by kayhayen** [comment]
There is Nuitka commercial for that: https://nuitka.net/pages/commercial.html
