### ISSUE TITLE
Issue when including Pandas library.

### ISSUE THREAD

**Issue by blakdronzer** [Nuitka/Nuitka#557]
I am currently having trouble taking in Pandas as library for integration :( ... in current project of mine - i am stuck with Pandas. I know many would have got in with solution for the same but here - i am stuck with this error:
```
Traceback (most recent call last):
File "/home/currentuser/Projects/OCRServer/app.dist/app.py", line 5, in <module>
File "<frozen importlib._bootstrap>", line 971, in _find_and_load
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
File "/home/currentuser/Projects/MyProject/app.dist/ProcessManager.py", line 9, in <module ProcessManager>
File "<frozen importlib._bootstrap>", line 971, in _find_and_load
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
File "/home/currentuser/Projects/MyProject/app.dist/ProcessWorker.py", line 16, in <module ProcessWorker>
File "<frozen importlib._bootstrap>", line 971, in _find_and_load
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
File "/home/currentuser/Projects/MyProject/app.dist/pandas/init.py", line 22, in <module pandas>
File "<frozen importlib._bootstrap>", line 971, in _find_and_load
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
File "/home/currentuser/Projects/MyProject/app.dist/pandas/compat/numpy/init.py", line 3, in <module pandas.compat.numpy>
File "<frozen importlib._bootstrap>", line 971, in _find_and_load
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
File "/home/currentuser/Projects/MyProject/app.dist/distutils/init.py", line 12, in <module>
AttributeError: module 'opcode' has no attribute 'file'

```
I tried even with simple program
```
import pandas as pd
print('hello world')

```
... even this simple application failed to get executed. :(

Is there some possible solution out there for ? Else i may have to get rid of the use of Pandas. I know there is a numpy plugin which i enabled while compiling..
`python3.6 -m nuitka --follow-imports --standalone --plugin-enable=pylint-warnings --plugin-enable=numpy --show-progress --show-scons --show-modules app.py`
but unfortunately - it still fails to execute and simply go ahead and print hello world too

**Comment by JorjMcKie** [comment]
Pandas internally imports matplotlib, so you need to tell this to the numpy plugin via an option: ``enable-plugin=numpy=matplotlib``. Similar thing applies if you (also) use scipy. So the numpy invocation can take forms like ``enable-plugin=numpy=matplotlib,scipy``.

I recommend you consider using [hinted compilation](https://github.com/Nuitka/NUITKA-Utilities/tree/master/hinted-compilation) which takes care of pesky stuff like this and automatically generates the required plugin parameters.

**Comment by blakdronzer** [comment]
Hi,
thanx for the update...
i did enable-plugin as instructed - but unfortunately it still didnt work. it still gave in same error

then i tried going on with the hited compilation as suggested... followed the instructions but following is the result i got in - 

```
Nuitka:INFO:User plugin 'hinted-mods.py' is being loaded.
Nuitka:INFO:'hinted-mods.py' is adding the following options:
Nuitka:INFO:--enable-plugin=numpy
Nuitka:INFO:--recurse-to for 410 imported modules.
Nuitka:INFO:
Problem with statement at test.py:1:
-> import pandas as pd

Nuitka:INFO:Interrupted while working on '<Node 'PYTHON_MAIN_MODULE' with {'filename': 'test.py', 'main_added': False, 'mode': 'compiled'}>'.
Traceback (most recent call last):
  File "/ocr-server/test/venv/lib/python3.6/site-packages/nuitka/__main__.py", line 184, in <module>
    main()
  File "/ocr-server/test/venv/lib/python3.6/site-packages/nuitka/__main__.py", line 177, in main
    MainControl.main()
  File "/ocr-server/test/venv/lib/python3.6/site-packages/nuitka/MainControl.py", line 759, in main
    main_module = createNodeTree(filename=filename)
  File "/ocr-server/test/venv/lib/python3.6/site-packages/nuitka/MainControl.py", line 141, in createNodeTree
    Optimization.optimize(main_module.getOutputFilename())
  File "/ocr-server/test/venv/lib/python3.6/site-packages/nuitka/optimizations/Optimization.py", line 542, in optimize
    makeOptimizationPass(initial_pass=True)
  File "/ocr-server/test/venv/lib/python3.6/site-packages/nuitka/optimizations/Optimization.py", line 456, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "/ocr-server/test/venv/lib/python3.6/site-packages/nuitka/optimizations/Optimization.py", line 167, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "/ocr-server/test/venv/lib/python3.6/site-packages/nuitka/optimizations/Optimization.py", line 100, in optimizeCompiledPythonModule
    module.computeModule()
  File "/ocr-server/test/venv/lib/python3.6/site-packages/nuitka/nodes/ModuleNodes.py", line 514, in computeModule
    trace_collection=self.trace_collection
  File "/ocr-server/test/venv/lib/python3.6/site-packages/nuitka/nodes/StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "/ocr-server/test/venv/lib/python3.6/site-packages/nuitka/nodes/FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "/ocr-server/test/venv/lib/python3.6/site-packages/nuitka/optimizations/TraceCollections.py", line 549, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "/ocr-server/test/venv/lib/python3.6/site-packages/nuitka/nodes/StatementNodes.py", line 226, in computeStatement
    trace_collection.onExpression(expression=self.getExpression())
  File "/ocr-server/test/venv/lib/python3.6/site-packages/nuitka/optimizations/TraceCollections.py", line 530, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "/ocr-server/test/venv/lib/python3.6/site-packages/nuitka/nodes/ExpressionBases.py", line 1005, in computeExpressionRaw
    return self.computeExpression(trace_collection=trace_collection)
  File "/ocr-server/test/venv/lib/python3.6/site-packages/nuitka/nodes/ImportNodes.py", line 401, in computeExpression
    trace_collection=trace_collection, module_name=imported_module_name
  File "/ocr-server/test/venv/lib/python3.6/site-packages/nuitka/nodes/ImportNodes.py", line 280, in _attemptRecursion
    module_package=module_package,
  File "/ocr-server/test/venv/lib/python3.6/site-packages/nuitka/nodes/ImportNodes.py", line 199, in _consider
    module_kind=module_kind,
  File "/ocr-server/test/venv/lib/python3.6/site-packages/nuitka/importing/Recursion.py", line 181, in decideRecursion
    module_filename, module_name, module_package, module_kind
  File "/ocr-server/test/venv/lib/python3.6/site-packages/nuitka/plugins/Plugins.py", line 251, in onModuleEncounter
    module_filename, module_name, module_package, module_kind
TypeError: onModuleEncounter() takes 4 positional arguments but 5 were given
```

**Comment by JorjMcKie** [comment]
Hinted compilation requires a nuitka minimum version, because internal APIs have changed at some time. I just successfully re-tested this with 0.6.6.
I am still concerned why ``hinted-mods.py`` did not generate the correct plugin statement. I will post a Linux compile log in my next comment.

**Comment by JorjMcKie** [comment]
The compilation step should start like this (the script just being the import with a print hello):

```
python3.6 nuitka-hints.py pandas2-test.py
NUITKA is compiling 'pandas2-test.py' with these options:
 --standalone
 --remove-output
 --recurse-none

Nuitka:INFO:User plugin 'hinted-mods.py' is being loaded.
Nuitka:INFO:'hinted-mods.py' is adding the following options:
Nuitka:INFO:--enable-plugin=numpy=matplotlib
Nuitka:INFO:--recurse-to for 401 imported modules.
Nuitka:INFO:
Nuitka:INFO:drop site
Nuitka:WARNING:Use '--plugin-enable=pylint-warnings' for: Understand PyLint/PyDev annotations for warnings.
Nuitka:INFO:drop pandas.core.computation.expressions (in pandas.core.computation)
Nuitka:INFO:drop pandas.io.formats.latex (in pandas.io.formats)
Nuitka:INFO:drop pandas.io.formats.html (in pandas.io.formats)
Nuitka:INFO:drop _decimal
Nuitka:INFO:drop _pydecimal
Nuitka:INFO:drop pandas.io.formats.excel (in pandas.io.formats)
Nuitka:INFO:drop pandas.io.formats.csvs (in pandas.io.formats)
Nuitka:INFO:drop pandas.core.resample (in pandas.core)
Nuitka:INFO:drop scipy.signal (plugin 'numpy')
Nuitka:INFO:drop pandas.core.groupby.categorical (in pandas.core.groupby)
Nuitka:INFO:drop numpy.ma.mrecords (in numpy.ma)
Nuitka:INFO:drop IPython
Nuitka:INFO:drop pandas.io.formats.style (in pandas.io.formats)
Nuitka:INFO:drop pandas.core.apply (in pandas.core)
Nuitka:INFO:drop pandas.core.computation.check (in pandas.core.computation)
Nuitka:INFO:drop matplotlib.pyplot (in matplotlib)
Nuitka:INFO:drop matplotlib.axes (in matplotlib)
Nuitka:INFO:drop pandas.plotting._timeseries (in pandas.plotting)
Nuitka:INFO:drop scipy.stats (plugin 'numpy')
Nuitka:INFO:drop scipy (plugin 'numpy')
Nuitka:INFO:drop matplotlib.artist (in matplotlib)
Nuitka:INFO:drop matplotlib.afm (in matplotlib)
Nuitka:INFO:drop matplotlib.style.core (in matplotlib.style)
Nuitka:INFO:drop matplotlib.ft2font (in matplotlib)
Nuitka:INFO:drop matplotlib.backend_tools (in matplotlib)
Nuitka:INFO:drop matplotlib.textpath (in matplotlib)
Nuitka:INFO:drop matplotlib.tight_bbox (in matplotlib)
Nuitka:INFO:drop matplotlib.widgets (in matplotlib)
Nuitka:INFO:drop matplotlib._pylab_helpers (in matplotlib)
Nuitka:INFO:drop PIL
Nuitka:INFO:drop matplotlib.collections (in matplotlib)
Nuitka:INFO:drop matplotlib.texmanager (in matplotlib)
Nuitka:INFO:drop matplotlib.figure (in matplotlib)
Nuitka:INFO:drop matplotlib.hatch (in matplotlib)
Nuitka:INFO:drop numpy.distutils (in numpy)
Nuitka:INFO:drop imp
Nuitka:INFO:drop pydoc
Nuitka:INFO:drop numpy.dual (in numpy)
Nuitka:INFO:drop pdb
Nuitka:INFO:drop uuid
Nuitka:INFO:drop _collections_abc
Nuitka:INFO:drop dateutil.tz.win (in dateutil.tz)
Nuitka:INFO:drop dateutil.zoneinfo (in dateutil)
Nuitka:INFO:drop matplotlib.lines (in matplotlib)
Nuitka:INFO:drop matplotlib.patches (in matplotlib)
Nuitka:INFO:drop matplotlib.table (in matplotlib)
Nuitka:INFO:drop matplotlib.cm (in matplotlib)
Nuitka:INFO:drop pandas.io.clipboard (in pandas.io)
Nuitka:INFO:drop sqlite3
Nuitka:INFO:drop doctest
Nuitka:INFO:drop termios
Nuitka:INFO:drop pandas.io.s3 (in pandas.io)
Nuitka:INFO:drop pandas.io.gcs (in pandas.io)
Nuitka:INFO:drop IPython.core.formatters (in IPython.core)
Nuitka:INFO:drop matplotlib.gridspec (in matplotlib)
Nuitka:INFO:drop scipy.sparse (plugin 'numpy')
Nuitka:INFO:drop scipy.interpolate (plugin 'numpy')
Nuitka:INFO:drop pandas.compat.chainmap_impl (in pandas.compat)
Nuitka:INFO:drop unittest
Nuitka:INFO:drop numpy.testing._private.noseclasses (in numpy.testing._private)
Nuitka:INFO:drop numpy.testing._private.parameterized (in numpy.testing._private)
Nuitka:INFO:drop unittest.case (in unittest)
Nuitka:INFO:drop numpy.distutils.misc_util (in numpy.distutils)
Nuitka:INFO:drop dummy_threading
Nuitka:INFO:drop IPython.core.debugger (in IPython.core)
Nuitka:INFO:drop pandas.io.sas.sas_xport (in pandas.io.sas)
Nuitka:INFO:drop pandas.io.sas.sas7bdat (in pandas.io.sas)
Nuitka:INFO:drop html5lib
Nuitka:INFO:drop optparse

**Comment by JorjMcKie** [comment]
I just refreshed ``hinted-mods.py``. To be sure, please download it again for your next compile.
Only the compile step needs to repeated - not the ``get-hints.py`` step.

**Comment by blakdronzer** [comment]
I did update the code / ran in as prescribed. It unfortunately still gives in same error.

python3.6 -m nuitka --version
0.6.5
Python: 3.6.8 (default, Oct  9 2019, 14:04:01) 
Executable: /project/test/venv/bin/python3.6
OS: Linux
Arch: x86_64

Anything i am doing wrong like? Or something here is different?

**Comment by JorjMcKie** [comment]
Please upgrade nuitka to 0.6.6 - I cannot remember when that call pattern changed, which ``hinted-mods.py`` now is relying on.
I am putting a Nuitka version check in to create more meaningful error situations.

**Comment by blakdronzer** [comment]
Hi,

Can you help me upgrade the same to 0.6.6 ... i tried upgrading using the pip command but could not find the distribution yet.

pip3.6 install nuitka==0.6.6
ERROR: Could not find a version that satisfies the requirement nuitka==0.6.6 (from versions: 0.4.0.linux-x86_64, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.4.1, 0.4.4.2, 0.4.5, 0.4.5.1, 0.4.5.2, 0.4.5.3, 0.4.6, 0.4.6.1, 0.4.6.2, 0.4.7, 0.4.7.1, 0.4.7.2, 0.5.0.1, 0.5.1, 0.5.1.1, 0.5.1.5, 0.5.1.6, 0.5.2, 0.5.2.1, 0.5.3.2, 0.5.3.3, 0.5.3.4, 0.5.3.5, 0.5.4, 0.5.4.1, 0.5.4.2, 0.5.4.3, 0.5.5, 0.5.5.1, 0.5.5.2, 0.5.5.3, 0.5.6.1, 0.5.7, 0.5.7.1, 0.5.8, 0.5.9, 0.5.10, 0.5.10.1, 0.5.10.2, 0.5.11, 0.5.11.1, 0.5.11.2, 0.5.12, 0.5.12.1, 0.5.12.2, 0.5.13, 0.5.13.1, 0.5.13.2, 0.5.13.3, 0.5.13.4, 0.5.13.6, 0.5.13.7, 0.5.13.8, 0.5.14, 0.5.14.1, 0.5.14.2, 0.5.14.3, 0.5.15, 0.5.16, 0.5.16.1, 0.5.19, 0.5.20, 0.5.22, 0.5.23.1, 0.5.24.1, 0.5.24.4, 0.5.25, 0.5.26, 0.5.27, 0.5.28, 0.5.28.1, 0.5.29, 0.5.29.1, 0.5.29.2, 0.5.29.3, 0.5.29.4, 0.5.29.5, 0.5.30, 0.5.31, 0.5.32, 0.5.32.1, 0.5.32.2, 0.5.32.3, 0.5.32.4, 0.5.32.5, 0.5.32.6, 0.5.32.7, 0.5.32.8, 0.5.33, 0.6.0, 0.6.0.1, 0.6.0.2, 0.6.0.3, 0.6.0.4, 0.6.0.5, 0.6.0.6, 0.6.1, 0.6.1.1, 0.6.2, 0.6.3, 0.6.3.1, 0.6.4, 0.6.5)
ERROR: No matching distribution found for nuitka==0.6.6

**Comment by blakdronzer** [comment]
Hi,

Thanx for the update. I did follow the instruction and update the nuitka to 0.6.6 and it went through with the hinted compilation. But once again - it failed in with same result :(
python3.6 -m nuitka --version    
0.6.6rc7
Python: 3.6.8 (default, Oct  9 2019, 14:04:01) 
Executable: /home/amitshah/Projects/test/venv/bin/python3.6
OS: Linux
Arch: x86_64

(venv) developer@ubuntu16-development:~/Projects/test$ python3.6 get-hints.py test.py 
hello world with Pandas
Call cleaning has removed 499 items.
(venv) developer@ubuntu16-development:~/Projects/test$ python3.6 nuitka-hints.py test.py
NUITKA is compiling 'test.py' with these options:
 --standalone
 --remove-output
 --recurse-none
 
Nuitka:INFO:User plugin 'hinted-mods.py' is being loaded.
Nuitka:INFO:'hinted-mods.py' is adding the following options:
Nuitka:INFO:--enable-plugin=numpy
Nuitka:INFO:--recurse-to for 410 imported modules.
Nuitka:INFO:
Nuitka:INFO:drop site
Nuitka:INFO:drop pandas.io.formats.latex (in pandas.io.formats)
Nuitka:INFO:drop pandas.io.formats.html (in pandas.io.formats)
Nuitka:INFO:drop _decimal
Nuitka:INFO:drop _pydecimal
Nuitka:INFO:drop pandas.core.computation.expressions (in pandas.core.computation)
Nuitka:INFO:drop numpy.ma.mrecords (in numpy.ma)
Nuitka:INFO:drop pandas.io.formats.style (in pandas.io.formats)
Nuitka:INFO:drop pandas.core.apply (in pandas.core)
Nuitka:INFO:drop pandas.core.resample (in pandas.core)
Nuitka:INFO:drop pandas.core.groupby.categorical (in pandas.core.groupby)
Nuitka:INFO:drop numpy.distutils (in numpy)
Nuitka:INFO:drop _collections_abc
Nuitka:INFO:drop imp
Nuitka:INFO:drop numpy.dual (in numpy)
Nuitka:INFO:drop pydoc
Nuitka:INFO:drop pandas.core.computation.check (in pandas.core.computation)
Nuitka:INFO:drop pandas.io.s3 (in pandas.io)
Nuitka:INFO:drop pandas.plotting._matplotlib (in pandas.plotting)
Nuitka:INFO:drop pandas.io.formats.excel (in pandas.io.formats)
Nuitka:INFO:drop pandas.io.formats.csvs (in pandas.io.formats)
Nuitka:INFO:drop pandas.io.clipboard (in pandas.io)
Nuitka:INFO:drop sqlite3
Nuitka:INFO:drop dateutil.tz.win (in dateutil.tz)
Nuitka:INFO:drop dateutil.rrule (in dateutil)
Nuitka:INFO:drop dateutil.zoneinfo (in dateutil)
Nuitka:INFO:drop pandas.io.gcs (in pandas.io)
Nuitka:INFO:drop doctest
Nuitka:INFO:drop unittest
Nuitka:INFO:drop numpy.testing._private.noseclasses (in numpy.testing._private)
Nuitka:INFO:drop numpy.testing._private.parameterized (in numpy.testing._private)
Nuitka:INFO:drop unittest.case (in unittest)
Nuitka:INFO:drop numpy.distutils.misc_util (in numpy.distutils)
Nuitka:INFO:drop pandas.io.sas.sas_xport (in pandas.io.sas)
Nuitka:INFO:drop pandas.io.sas.sas7bdat (in pandas.io.sas)
Nuitka:INFO:drop optparse
Nuitka:WARNING:Not recursing to unused '__future__'.
Nuitka:WARNING:Not recursing to unused '_compat_pickle'.
Nuitka:WARNING:Not recursing to unused '_compression'.
Nuitka:WARNING:Not recursing to unused '_weakrefset'.
Nuitka:WARNING:Not recursing to unused 'argparse'.
Nuitka:WARNING:Not recursing to unused 'base64'.
Nuitka:WARNING:Not recursing to unused 'ctypes._endian'.
Nuitka:WARNING:Not recursing to unused 'dis'.
Nuitka:WARNING:Not recursing to unused 'distutils.debug'.
Nuitka:WARNING:Not recursing to unused 'distutils.dep_util'.
Nuitka:WARNING:Not recursing to unused 'distutils.errors'.
Nuitka:WARNING:Not recursing to unused 'distutils.fancy_getopt'.
Nuitka:WARNING:Not recursing to unused 'distutils.spawn'.
Nuitka:WARNING:Not recursing to unused 'distutils.util'.
Nuitka:WARNING:Not recursing to unused 'email'.
Nuitka:WARNING:Not recursing to unused 'email._encoded_words'.
Nuitka:WARNING:Not recursing to unused 'email._parseaddr'.
Nuitka:WARNING:Not recursing to unused 'email._policybase'.
Nuitka:WARNING:Not recursing to unused 'email.charset'.
Nuitka:WARNING:Not recursing to unused 'email.encoders'.
Nuitka:WARNING:Not recursing to unused 'email.errors'.
Nuitka:WARNING:Not recursing to unused 'email.feedparser'.
Nuitka:WARNING:Not recursing to unused 'email.iterators'.
Nuitka:WARNING:Not recursing to unused 'email.utils'.
Nuitka:WARNING:Not recursing to unused 'encodings'.
Nuitka:WARNING:Not recursing to unused 'enum'.
Nuitka:WARNING:Not recursing to unused 'fnmatch'.
Nuitka:WARNING:Not recursing to unused 'genericpath'.
Nuitka:WARNING:Not recursing to unused 'getopt'.
Nuitka:WARNING:Not recursing to unused 'gettext'.
Nuitka:WARNING:Not recursing to unused 'hashlib'.
Nuitka:WARNING:Not recursing to unused 'heapq'.
Nuitka:WARNING:Not recursing to unused 'hmac'.
Nuitka:WARNING:Not recursing to unused 'importlib._bootstrap'.
Nuitka:WARNING:Not recursing to unused 'importlib._bootstrap_external'.
Nuitka:WARNING:Not recursing to unused 'ipaddress'.
Nuitka:WARNING:Not recursing to unused 'json.decoder'.
Nuitka:WARNING:Not recursing to unused 'json.encoder'.
Nuitka:WARNING:Not recursing to unused 'linecache'.
Nuitka:WARNING:Not recursing to unused 'logging'.
Nuitka:WARNING:Not recursing to unused 'ntpath'.
Nuitka:WARNING:Not recursing to unused 'opcode'.
Nuitka:WARNING:Not recursing to unused 'quopri'.
Nuitka:WARNING:Not recursing to unused 'selectors'.
Nuitka:WARNING:Not recursing to unused 'signal'.
Nuitka:WARNING:Not recursing to unused 'socket'.
Nuitka:WARNING:Not recursing to unused 'ssl'.
Nuitka:WARNING:Not recursing to unused 'stat'.
Nuitka:WARNING:Not recursing to unused 'token'.
Nuitka:WARNING:Not recursing to unused 'urllib.response'.
Nuitka:WARNING:Not recursing to unused 'uu'.
Nuitka:INFO:Copied 2 files from 'numpy' installation.
Nuitka:INFO:Compile time 40 minutes.
(venv) developer@ubuntu16-development:~/Projects/test$ cd test.dist/
(venv) developer@ubuntu16-development:~/Projects/test/test.dist$ ./test 
Traceback (most recent call last):
  File "/home/developer/Projects/test/test.dist/test.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/developer/Projects/test/test.dist/pandas/__init__.py", line 22, in <module pandas>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/developer/Projects/test/test.dist/pandas/compat/numpy/__init__.py", line 3, in <module pandas.compat.numpy>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/developer/Projects/test/test.dist/distutils/__init__.py", line 12, in <module>
AttributeError: module 'opcode' has no attribute '__file__'

**Comment by JorjMcKie** [comment]
I am running out of advice a little bit. Let's compare the versions of related packages to eventually find reasons for this different behaviour:

```
D:\Jorj\Desktop>python -m pip show matplotlib
Name: matplotlib
Version: 3.1.1
Summary: Python plotting package
Home-page: https://matplotlib.org
Author: John D. Hunter, Michael Droettboom
Author-email: matplotlib-users@python.org
License: PSF
Location: c:\users\jorj\appdata\local\programs\python\python37\lib\site-packages
Requires: numpy, cycler, python-dateutil, pyparsing, kiwisolver
Required-by:

D:\Jorj\Desktop>python -m pip show pandas
Name: pandas
Version: 0.25.0
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: http://pandas.pydata.org
Author: None
Author-email: None
License: BSD
Location: c:\users\jorj\appdata\local\programs\python\python37\lib\site-packages
Requires: numpy, pytz, python-dateutil
Required-by: statsmodels

D:\Jorj\Desktop>python -m pip show numpy
Name: numpy
Version: 1.17.0
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: c:\users\jorj\appdata\local\programs\python\python37\lib\site-packages
Requires:
Required-by: wxPython, torchvision, tensorflow, tb-nightly, statsmodels, scipy, scikit-learn, PyWavelets, patsy, pandas, opencv-python, matplotlib, Keras-Preprocessing, Keras-Applications, imageio, h5py, cupy-cuda100, chainer

D:\Jorj\Desktop>python -m pip show scipy
Name: scipy
Version: 1.3.1
Summary: SciPy: Scientific Library for Python
Home-page: https://www.scipy.org
Author: None
Author-email: None
License: BSD
Location: c:\users\jorj\appdata\local\programs\python\python37\lib\site-packages
Requires: numpy
Required-by: statsmodels, scikit-learn

D:\Jorj\Desktop>
```

**Comment by blakdronzer** [comment]
Hi, 

Sorry for a delayed response. I was out of commission from work - hospitalized for illness.  Well to be frank - i didnt have matplotlib - but i did install it for the sake of compilation testing. I dont even need scipy - as there aint any need of the same to be working with. Below are the output of the versions of the libraries in use at my end.

(venv) amitshah@ubuntu16-development:~/Projects/test$ python3.6 -m pip show matplotlib
Name: matplotlib
Version: 3.1.1
Summary: Python plotting package
Home-page: https://matplotlib.org
Author: John D. Hunter, Michael Droettboom
Author-email: matplotlib-users@python.org
License: PSF
Location: /home/amitshah/Projects/test/venv/lib/python3.6/site-packages
Requires: numpy, kiwisolver, python-dateutil, cycler, pyparsing
Required-by: 
(venv) amitshah@ubuntu16-development:~/Projects/test$ python3.6 -m pip show pandas           
Name: pandas
Version: 0.25.2
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: http://pandas.pydata.org
Author: None
Author-email: None
License: BSD
Location: /home/amitshah/Projects/test/venv/lib/python3.6/site-packages
Requires: python-dateutil, numpy, pytz
Required-by: 
(venv) amitshah@ubuntu16-development:~/Projects/test$ python3.6 -m pip show numpy
Name: numpy
Version: 1.17.3
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /home/amitshah/Projects/test/venv/lib/python3.6/site-packages
Requires: 
Required-by: pandas, matplotlib

**Comment by blakdronzer** [comment]
Hi,

I even forced the same versions at my end - both numpy and pandas (this were the only ones needed) for the test project. Ran on the hinted compilation and still it gave the following result.

Traceback (most recent call last):
  File "/home/amitshah/Projects/test/test.dist/test.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/amitshah/Projects/test/test.dist/pandas/__init__.py", line 22, in <module pandas>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/amitshah/Projects/test/test.dist/pandas/compat/numpy/__init__.py", line 3, in <module pandas.compat.numpy>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/amitshah/Projects/test/test.dist/distutils/__init__.py", line 12, in <module>
AttributeError: module 'opcode' has no attribute '__file__'

**Comment by JorjMcKie** [comment]
So far I have no explanation.
Your case fails in calling distutils, which is used to determine version numbers of packages.
The failing instruction seems to start with ``from distutils.version import LooseVersion`` in ``/pandas/compat/numpy/__init__.py``.
My version of distutils has no line 12 in ``distutils/__init__.py``. So I think the problem is in that area.
I am sending you a ZIP with
1. a minimal script invoking pandas
2. the JSON file produced by get-hints.py for that script
3. run logs for `get-hints.py`, `nuitka-hints.py` and execution of the binary for the script.

[pandas2-test.zip](https://github.com/Nuitka/Nuitka/files/3803853/pandas2-test.zip)

Maybe you can compare the contents of your JSON with mine.

We could also checkout any differences between our distutils versions:
[distutils.zip](https://github.com/Nuitka/Nuitka/files/3803849/distutils.zip)

**Comment by blakdronzer** [comment]
I should really thank you brother - i too figured that out that the distutils i have had in the python main lib folder - was way different then the one found in the projects venv folder - quite surprising to me too - this have had a single __init__.py with a cfg file .. and the folder have had the same structured set of files that u shared in the zip. This is a strange stuff that happens up .. when creating a virtual environment for a project - the distutils copied / generated is far more different then the one found in the original set of distribution. Wondering why like!! 

But - thanx from the bottom of my heart. This - i believe should be able to help me finish up the task

**Comment by JorjMcKie** [comment]
@blakdronzer - thanks for the nice post!
And best of success!

**Comment by rucciva** [comment]
hi @blakdronzer , i'am facing the same problem as yours. can you share what modification did you do to resolve this?

thanks
