### ISSUE TITLE
How to Compile Django App using Nuitka

### ISSUE THREAD

**Issue by multiversecoder** [Nuitka/Nuitka#560]
Hi, I really appreciate the efforts to create this compiler and I've been successful in compiling a small application based on tornado web framework but, now that I'm developing my main project in django I would like to know how you use nuitka to compile an entire application that uses django, since I can not get a result.
The application uses a Gunicorn server adapter, I would like to know if it is feasible. I'll add it below for more information.

```
import os
import multiprocessing
from django.core.wsgi import get_wsgi_application

from typing import Callable

os.environ['DJANGO_SETTINGS_MODULE'] = 'app.settings' # path to your settings module
    
def workers() -> int:
    return (multiprocessing.cpu_count() * 2) + 1

class GunicornServer:


    def __init__(self, host: str, port: int, **options):
    	self.host = host
    	self.port = port
    	self.options = options


    def run(self, handler: Callable):
        from gunicorn.app.base import Application

        config = {
        	'bind': "%s:%d" % (self.host, int(self.port)),
        	"workers": workers()
    	}
        config.update(self.options)

        class GunicornApplication(Application):
            def init(self, parser, opts, args):
                return config

            def load(self):
                return handler

        GunicornApplication().run()



if __name__ == "__main__":
    GunicornServer("127.0.0.1", 8888).run(get_wsgi_application())
````

Thanks to kayhayen and the whole community

**Comment by sorinaTR** [comment]
@multiversecoder I would really like to know if you've found something helpful about this issue. I find myself in the exact same situation, trying to compile a Django API and would appreciate any idea or suggestion. Thanks

**Comment by sorix6** [comment]
@multiversecoder I would really like to know if you've found something helpful about this issue. I find myself in the exact same situation, trying to compile a Django API and would appreciate any idea or suggestion. Thanks

**Comment by JorjMcKie** [comment]
@sorix6 - can you give me a bare-bones script, preferrably just the imports?
I will see what I can do ...

**Comment by sorix6** [comment]
Hi @JorjMcKie, thanks for getting back to me. 

Unfortunately I cannot provide the source code of the app, but here is the script used for compiling with Nuitka:

```
#!/usr/bin/env python
#
# Code obfuscation using nuitka
# Convert python code to shared object.
#
import os
import pprint


# Project directories to run nuitka on.
# Edit this to include the directories you want.
PROJECT_DIRS = [
    '/app'
]

EXCLUDE_FILES = [
    '__init__.py',
    '__main__.py',
    'setup.py'
]


def main():
    """
    Go through each python file in the given project directories and
    convert python code to shared object using nuitka.
    Remove the original .py file as well.
    """
    py_files_processed = []

    for nuitka_dir in PROJECT_DIRS:
        if nuitka_dir != '/app/tests':
            _recursive(nuitka_dir, py_files_processed)

    # print('Processed the following py files:')
    pprint.pprint(py_files_processed)


def _recursive(folder, py_files_processed):
    """
    """
    for root, directories, files in os.walk(folder):

        if root.startswith('/app/tests'):
            continue

        for directory in directories:
            if directory != 'tests':
                _recursive(directory, py_files_processed)

        for file in files:
            if file.endswith('.py'):
                if file in EXCLUDE_FILES:
                    continue

                file_path = os.path.join(root, file)

                print(f'Processing file: {file_path}')
                py_files_processed.append(file_path)

                # Remove doc-strings from shared object by passing -OO
                # flag.
                cmd = (
                    'python -m nuitka --module --python-flag=-OO '
                    '--remove-output --lto --output-dir={} {}'
                )
                os.system(cmd.format(root, file_path))

                # Remove the original .py file.
                os.remove(file_path)


if __name__ == '__main__':
    main()
```

I used [this](https://varunbpatil.github.io/2019/09/29/nuitka-code-obfuscation.html) as a starting point. The script is run in the Dockerfile at build time.

The file are all compiled to .so files and all seems well, but when I try to use the app, I get a "Segmentation error(core dumped)" error. 

It seems to work fine for a small application, with only one level of modules, but my actual application is a lot more complex and has many external dependencies.

I am using:
- Python 3.6.5
- Nuitka 0.6.3
- Ubuntu 18.04 on my machine
- Docker version 18.09.7

I have gone towards using .so files and not an executable because we have an external Django API that needs to import file from the other application. 

Is compiling the whole API into an executable a solution? We are more interested in obfuscating the application rather than the API, but if having both of them together could also work.

Thank you in advance!

**Comment by nerseswolf** [comment]
I'm also in same situation, trying to compile a Django project with nuitka.  Does anyone have a solution how I can do this?

thank you!

**Comment by kayhayen** [comment]
make a new issue, this one is pretty much failed @nerseswolf
