### ISSUE TITLE
i solve it 

### ISSUE THREAD

**Issue by Glcanepa** [Nuitka/Nuitka#566]
Hello, when i try to use nuitka i have the following error:

C:\g>python -m nuitka --standalone --plugin-enable=numpy --plugin-enable=numpy=scipy snc.py

Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\gian_\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\core\function_base.py:463' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\gian_\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\utils.py:393' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\gian_\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\utils.py:892' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\gian_\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\utils.py:950' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\gian_\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\_lib\_util.py:160' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\gian_\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\optimize\optimize.py:3110' may require use of '--include-plugin-directory' or '--include-plugin-files'.

scons: warning: MSVC_USE_SCRIPT set to False, assuming environment set correctly.
File "C:\Users\gian_\AppData\Local\Programs\Python\Python36\lib\site-packages\nuitka\build\SingleExe.scons", line 508, in createEnvironment
cl /Fosnc.build\__frozen.obj /c "snc.build\__frozen.cpp" /TP /nologo /EHsc /J /Gd /Ox /MT /D_NUITKA_STANDALONE /D_NUITKA_SYSFLAG_BYTES_WARNING=0 /D_NUITKA_SYSFLAG_NO_SITE=0 /D_NUITKA_SYSFLAG_VERBOSE=0 /D_NUITKA_SYSFLAG_UTF8=0 /D_NUITKA_SYSFLAG_OPTIMIZE=0 /D__NUITKA_NO_ASSERT__ /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=170 /D_NUITKA_MODULE_COUNT=977 /D_NUITKA_EXE /IC:\Users\gian_\AppData\Local\Programs\Python\Python36\include /IC:\Users\gian_\AppData\Local\Programs\Python\Python36\PC /Isnc.build /IC:\Users\gian_\AppData\Local\Programs\Python\Python36\lib\site-packages\nuitka\build\include /IC:\Users\gian_\AppData\Local\Programs\Python\Python36\lib\site-packages\nuitka\build\static_src
scons: *** [snc.build\__frozen.obj] Error 2
cl /Fosnc.build\__constants.obj /c "snc.build\__constants.cpp" /TP /nologo /EHsc /J /Gd /Ox /MT /D_NUITKA_STANDALONE /D_NUITKA_SYSFLAG_BYTES_WARNING=0 /D_NUITKA_SYSFLAG_NO_SITE=0 /D_NUITKA_SYSFLAG_VERBOSE=0 /D_NUITKA_SYSFLAG_UTF8=0 /D_NUITKA_SYSFLAG_OPTIMIZE=0 /D__NUITKA_NO_ASSERT__ /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=170 /D_NUITKA_MODULE_COUNT=977 /D_NUITKA_EXE /IC:\Users\gian_\AppData\Local\Programs\Python\Python36\include /IC:\Users\gian_\AppData\Local\Programs\Python\Python36\PC /Isnc.build /IC:\Users\gian_\AppData\Local\Programs\Python\Python36\lib\site-packages\nuitka\build\include /IC:\Users\gian_\AppData\Local\Programs\Python\Python36\lib\site-packages\nuitka\build\static_src
C:\Users\gian_\AppData\Local\Programs\Python\Python36\include\pyconfig.h(59): fatal error C1083: No se puede abrir el archivo incluir: 'io.h': No such file or directorycl /Fosnc.build\__helpers.obj /c "snc.build\__helpers.cpp" /TP /nologo /EHsc /J /Gd /Ox /MT /D_NUITKA_STANDALONE /D_NUITKA_SYSFLAG_BYTES_WARNING=0 /D_NUITKA_SYSFLAG_NO_SITE=0 /D_NUITKA_SYSFLAG_VERBOSE=0 /D_NUITKA_SYSFLAG_UTF8=0 /D_NUITKA_SYSFLAG_OPTIMIZE=0 /D__NUITKA_NO_ASSERT__ /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=170 /D_NUITKA_MODULE_COUNT=977 /D_NUITKA_EXE /IC:\Users\gian_\AppData\Local\Programs\Python\Python36\include /IC:\Users\gian_\AppData\Local\Programs\Python\Python36\PC /Isnc.build /IC:\Users\gian_\AppData\Local\Programs\Python\Python36\lib\site-packages\nuitka\build\include /IC:\Users\gian_\AppData\Local\Programs\Python\Python36\lib\site-packages\nuitka\build\static_src
cl /Fosnc.build\module.__internal__.obj /c "snc.build\module.__internal__.cpp" /TP /nologo /EHsc /J /Gd /Ox /MT /D_NUITKA_STANDALONE /D_NUITKA_SYSFLAG_BYTES_WARNING=0 /D_NUITKA_SYSFLAG_NO_SITE=0 /D_NUITKA_SYSFLAG_VERBOSE=0 /D_NUITKA_SYSFLAG_UTF8=0 /D_NUITKA_SYSFLAG_OPTIMIZE=0 /D__NUITKA_NO_ASSERT__ /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=170 /D_NUITKA_MODULE_COUNT=977 /D_NUITKA_EXE /IC:\Users\gian_\AppData\Local\Programs\Python\Python36\include /IC:\Users\gian_\AppData\Local\Programs\Python\Python36\PC /Isnc.build /IC:\Users\gian_\AppData\Local\Programs\Python\Python36\lib\site-packages\nuitka\build\include /IC:\Users\gian_\AppData\Local\Programs\Python\Python36\lib\site-packages\nuitka\build\static_src
scons: *** [snc.build\__helpers.obj] Error 2
scons: *** [snc.build\module.__internal__.obj] Error 2
scons: *** [snc.build\__constants.obj] Error 2
C:\Users\gian_\AppData\Local\Programs\Python\Python36\include\pyconfig.h(59): fatal error C1083: No se puede abrir el archivo incluir: 'io.h': No such file or directoryC:\Users\gian_\AppData\Local\Programs\Python\Python36\include\pyconfig.h(59): fatal error C1083: No se puede abrir el archivo incluir: 'io.h': No such file or directoryC:\Users\gian_\AppData\Local\Programs\Python\Python36\include\pyconfig.h(59): fatal error C1083: No se puede abrir el archivo incluir: 'io.h': No such file or directory

please help me, thank you

**Comment by kayhayen** [comment]
Ok, solved.
