### ISSUE TITLE
The following signatures were invalid: EXPKEYSIG 1BFC33752912B99C

### ISSUE THREAD

**Issue by tonal** [Nuitka/Nuitka#569]
Add stable repositories to ubuntu 18.04
```
# wget -O - http://nuitka.net/deb/archive.key.gpg | apt-key add -
...
# echo >/etc/apt/sources.list.d/nuitka.list "deb http://nuitka.net/deb/stable/bionic bionic main"
# apt-get update
...
Err:7 https://nuitka.net/deb/stable/bionic bionic InRelease                                                  
  The following signatures were invalid: EXPKEYSIG 1BFC33752912B99C Kay Hayen <kay.hayen@gmail.com>
...
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://nuitka.net/deb/stable/bionic bionic InRelease: The following signatures were invalid: EXPKEYSIG 1BFC33752912B99C Kay Hayen <kay.hayen@gmail.com>
W: Failed to fetch http://nuitka.net/deb/stable/bionic/dists/bionic/InRelease  The following signatures were invalid: EXPKEYSIG 1BFC33752912B99C Kay Hayen <kay.hayen@gmail.com>
```

**Comment by kayhayen** [comment]
I have updated the key for the new release, sorry for the long time this took.

**Comment by niflostancu** [comment]
Hi. Happy new year!
I'm encountering the same issue.
On https://nuitka.net/deb/ , I see the `archive.key.gpg` file was last modified on `2017-11-12 10:57`.

Maybe you recently restored the repo server from backups and the old key reappeared? Or some sort of cache / mirror server issue?
Can you check it please? (I use `apt-get install --allow-unauthenticated nuitka` as workaround, though risky). Thanks.

**Comment by kayhayen** [comment]
Ah, I just noticed that it's global thing, so I was assuming the repo rebuild would contain the key, but it does not. I will update my ansible to do this automatically then, may take a bit though.

**Comment by kayhayen** [comment]
I changed the key, now need to make sure it's actually the one used to create the repo.

**Comment by kayhayen** [comment]
Ok, so the signing key id didn't really change, unsure if the updated will work with new repos, but it ought to be all good after next release now.
