### ISSUE TITLE
Adding parameters such as version,copyright etc. to EXE files

### ISSUE THREAD

**Issue by SeanTolstoyevski** [Nuitka/Nuitka#570]
Hello,

I use Nuitka to distribute my projects as standalone.
However, I was unable to add the values ​​seen in the **Properties / details ** tab of the .exe file that was created.
Copyright, version, file description, Product name...

I use various 3rd party software for this.
I think Uses arduous.
It takes me a long time.

What do Nuitka users do for the situation I'm talking about?
I would like to listen.

I reviewed the NUITKA-Utilities repo and ``nuitka --help`` output.
I couldnt find it.
I may have missed it.

Finally, thanks to Kay Hayen and the nice people for whom I don't know her name for this wonderful project.

**Comment by JorjMcKie** [comment]
Please have a look at https://github.com/Nuitka/NUITKA-Utilities/blob/master/onefile-maker-windows.py.

You should be able to modify the parameters code from line numbers 250 onwards ...

**Comment by SeanTolstoyevski** [comment]
Hi @JorjMcKie ,

The file here is not what I'm talking about.

I'm talking about the parameters of the .exe file.
Isn't NSIS to compress and setup the file?
