### ISSUE TITLE
How to create a single binary without dependencies

### ISSUE THREAD

**Issue by r-clancy** [Nuitka/Nuitka#575]
```
0.6.5
Python: 3.7.4 (default, Aug 13 2019, 20:35:49) 
Executable: /home/ryan/.miniconda/bin/python
OS: Linux
Arch: x86_64
```

Conda environment for Python, Nuitka installed via pip.

I've been looking through the documentation, but I don't quite see the options I am looking for. I have a source tree with a single entry point (`main.py`) and a bunch of other Python modules nested below it. I want to produce a single binary with all of the Python files included, but I **don't** want to include any conda/pip dependencies or the Python interpreter itself.

How can this be done?

**Comment by kayhayen** [comment]
It's called standalone mode, --standalone, that will give you a directory with the dependencies, provided it has no bugs in collecting them.

As for single file, #230 exists, but is unsolved so far.

**Comment by r-clancy** [comment]
@kayhayen What about the no dependencies part? I only want to compile the files within my source tree (without traversing through to pip dependencies or the python interpreter).

Thanks for the information!

**Comment by kayhayen** [comment]
I don't understand that question @r-clancy

**Comment by r-clancy** [comment]
@kayhayen I don't want Nuitka to follow imports that aren't within the same project - if I point to `main.py` I want it to compile all of **my** Python files referenced underneath `main.py` only. Essentially, I want to ship the binary version of my app to a machine with an existing Python environment that has all of the dependencies available (e.g., I ship the binary version of my app with a conda `environment.yml` file).

**Comment by kayhayen** [comment]
Seems you want the default mode, accelerated mode. You create extension modules with it, or binaries and fordid it to follow outside of your namespace. It's best done using distutils and `bdist_nuitka` these days.

**Comment by r-clancy** [comment]
@kayhayen Is there any documentation on this? Specifically the `bdist_nuitka` stuff. Ideally, I'd want a command to compile each file in my package and then I can write something to swap the original `.py` with the `.so` file (or whatever executable extension is produces)

**Comment by r-clancy** [comment]
This seems to do what I want in a `setup.py`:
```
from setuptools import setup, find_packages

setup(
    name='mypackage',
    version='0.0.1',
    packages=find_packages(exclude=[
        'tests'
    ])
)
```

Run `python setup.py bdist_nuitka`

**Comment by r-clancy** [comment]
Scratch that - I only seem to have `.so` files for those in the top-level package.

**Comment by r-clancy** [comment]
@kayhayen Any ideas? Nuitka only seems to produce `.so` files for the top-level package instead of all of the children packages below the top-level.

**Comment by IuliaLungu-synthara** [comment]
Hi, did you ever find a solution for this? I am struggling with the same issue. Thanks!

**Comment by kayhayen** [comment]
There is plenty of documentation in the user manual about modes, standalone and distutils integration. This is not for helping people who struggle with reading. Should something be missing in the docs, then raise an issue.
