### ISSUE TITLE
Runtime error with eventlet and flask/socketio

### ISSUE THREAD

**Issue by tristanidoux** [Nuitka/Nuitka#576]
Hey,

I'm really hyper by your work, this project is awesome !
Here is my setup:

```bash
0.6.5
Python: 3.6.8 (default, Oct  7 2019, 12:59:55)
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64


```

I'm just having a bit of trouble when compiling it. Here is my code below and the log: 

```python
import eventlet
eventlet.monkey_patch()

from flask import Flask
from flask_socketio import SocketIO, send, emit

app = Flask(__name__)
socketio = SocketIO(app)

if __name__ == "__main__":
    socketio.run(app, host='127.0.0.1', port=8000)
```

```bash
$> python3 -m nuitka --standalone app.py
Nuitka:WARNING:Unresolved '__import__' call at '/usr/local/lib/python3.6/dist-packages/eventlet/patcher.py:100' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at '/usr/local/lib/python3.6/dist-packages/eventlet/patcher.py:201' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at '/usr/local/lib/python3.6/dist-packages/eventlet/patcher.py:306' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at '/usr/local/lib/python3.6/dist-packages/flask/cli.py:236' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at '/usr/local/lib/python3.6/dist-packages/flask/helpers.py:749' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at '/usr/local/lib/python3.6/dist-packages/flask/helpers.py:818' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at '/usr/local/lib/python3.6/dist-packages/jinja2/loaders.py:472' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at '/usr/local/lib/python3.6/dist-packages/jinja2/utils.py:142' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at '/usr/local/lib/python3.6/dist-packages/jinja2/utils.py:143' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at '/usr/lib/python3/dist-packages/requests/packages.py:7' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at '/usr/local/lib/python3.6/dist-packages/werkzeug/__init__.py:186' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at '/usr/local/lib/python3.6/dist-packages/werkzeug/__init__.py:191' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at '/usr/local/lib/python3.6/dist-packages/werkzeug/utils.py:547' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at '/usr/local/lib/python3.6/dist-packages/werkzeug/utils.py:555' may require use of '--include-plugin-directory' or '--include-plugin-files'.
```

As you can see, the compilation is successful but when I try to run it, I get the error:
```python
Traceback (most recent call last):
  File "/tmp/nuitka-test/app.dist/app.py", line 4, in <module>
  File "/tmp/nuitka-test/app.dist/eventlet/__init__.py", line 10, in <module eventlet>
  File "/tmp/nuitka-test/app.dist/eventlet/convenience.py", line 4, in <module eventlet.convenience>
  File "/tmp/nuitka-test/app.dist/eventlet/greenpool.py", line 4, in <module eventlet.greenpool>
  File "/tmp/nuitka-test/app.dist/eventlet/queue.py", line 49, in <module eventlet.queue>
  File "/tmp/nuitka-test/app.dist/eventlet/event.py", line 3, in <module eventlet.event>
  File "/tmp/nuitka-test/app.dist/eventlet/hubs/__init__.py", line 19, in <module eventlet.hubs>
  File "/tmp/nuitka-test/app.dist/eventlet/hubs/__init__.py", line 19, in <genexpr>
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

ModuleNotFoundError: No module named 'eventlet.hubs.epolls'
```
I also get the error `Segmentation fault (core dumped)` on another computer with `eventlet==0.24.1`. Eventlet version 0.25.0 changelog indicates that they fixed the eventlet hub where it could use epolls as default hub even when platform does not support it.

When running my app using `python3 -B app`, everything works fine. I would think it has something do nuikta faulting the eventlet hub when compiling ? My computer does support epoll.

If I remove the `eventlet` library, it builds and the error I get when running it is:
```python
Traceback (most recent call last):
  File "/tmp/nuitka-test/app.dist/app.py", line 11, in <module>
  File "/tmp/nuitka-test/app.dist/flask_socketio/__init__.py", line 185, in __init__
  File "/tmp/nuitka-test/app.dist/flask_socketio/__init__.py", line 245, in init_app
  File "/tmp/nuitka-test/app.dist/socketio/server.py", line 108, in __init__
  File "/tmp/nuitka-test/app.dist/engineio/server.py", line 139, in __init__

ValueError: Invalid async_mode specified
```
Which seems very close to a problem that appeared when using `pyinstaller` as you can see [here](https://github.com/miguelgrinberg/python-socketio/issues/35) as seems to be related to the socketio library (something about hidden imports).

Any suggesions to make this work ? Preferably with eventlet as it has better perf :)

Thanks for your time and truly great project !

**Comment by JorjMcKie** [comment]
I started looking into this. One question to start with: What does this animal do? Starting a server and then waiting for something?

Anyway: I have commented out invocation of ``socketio.run(app, host='127.0.0.1', port=8000)`` and then used the [hinted compilation](https://github.com/Nuitka/NUITKA-Utilities/tree/master/hinted-compilation) utilities to compile it.
I am hoping that this skeleton code already does all relevant imports (which hinted compilation logs in a file).
With this I am also getting your message ``No module named 'eventlet.hubs.epolls'``.
So I will further trace any hidden import. This is a fairly safe bet with messages like this one.
Stay tuned.

**Comment by tristanidoux** [comment]
Hey, thanks a lot for looking into this ! I wasn't aware of the **hinted compilation** tool, will definitely keep that in mind !

The skeleton I have written doesn't do anything as I wanted it to be the simplest possible. In theory, there should be routes and events to emit/receive indeed. Let me know if you want a more detailed skeleton.

**Comment by JorjMcKie** [comment]
All I need for hinted compilation ("HC") is a script thats ends by itself, but still does all imports imaginable by the package under investigation.
This is because HC needs to reformat the logfile of all the import - obviously only possible once the script has finished.

**Comment by JorjMcKie** [comment]
I am making progress BTW: my exception has changed 😉
Once I find no more errors I will be submitting new versions of changed Nuitka plugins to you via ZIP file.
With some look it will just be the ``ImplicitImports.py`` plugin, which is located in ``/nuitka/plugins/standard``. Please replace this module there with the version which I will be sending to you and repeat your compile.
After a few back and fro's we should be there ...

**Comment by JorjMcKie** [comment]
CC: @kayhayen 

@tristanidoux - so far so good and ugly:

* **Good:** I compiled and successfully executed the "skeleton" script. Skeleton means: it does all the imports, but else does not do anything useful.
* **Ugly:** ``eventlet`` (or other packages it imports) does  lots of hacking in the internals of Python at startup time. Most prominently it checks which parts of the ``dns`` modules have been imported and replaces those by same-named "green" (non-blocking) variants. In effect this leads to the requirement, that the ``dns`` **sources must be present in the dist folder** - just like data files. And what is more: they will **not be used**, but each occurrence in ``sys.modules`` will subsequently be replaced by some "green" counterpart.

This is at least what I so far have understood from analyzing the packages.

I thoroughly dislike the situation. While there is no problem to handle the ``dns`` package as if it were a bunch of data files, it will lead to Python source in something which should contain **compiled** binary code. The mechanism described above also implies that - at application start - ``.pyc`` files **will be generated in subfolders of the _dist_ folder!**
I am sure that system administrators would hate to install an application with this type of behavior: installation material should be read-only.

I am not clear how to solve this.
A straightforward brute force approach might be to **not copy** the ``*.py`` files, but instead their ``*.pyc`` counterparts - and thus prevent self-modification of the dist folder, **and** Python source being present.
Another possible approach (which I wouldn't know how to do): compile the ``dns`` package into a module (binary extension). It wouldn't be ever executed either, but would share this fate with others.

@kayhayen - any ideas?

**Comment by JorjMcKie** [comment]
@tristanidoux 
Bottom line of my wordy previous post:
With two handful of modifications to the ``ImplicitImport.py`` plugin you could start testing if your stuff is working. The only manual action for you to undertake after a compile, would be copying the ``dns`` package to the dist folder.
Automatic copy of ``dns`` is possible as indicated, but I need a little more time to implement some solution.

Please drop me a note what you would like to do.

**Comment by tristanidoux** [comment]
@JorjMcKie 
Hey ! Thanks so much for your time and the effort ! 
I will gladly try out the fix and will let you known if everything is working according to plan (will probably compile `dns` as a module).
I've sent you a PM and will post feedback as soon as I can.

Thanks :)

**Comment by JorjMcKie** [comment]
@tristanidoux - just sent you another modification for a standard plugin, the data file collector.
With it your should be able to compile eventlet scripts fully automatically in standalone mode.

**Comment by JorjMcKie** [comment]
@tristanidoux - just sent you some more modifications. Hope there will be some progress on your side with them.
