### ISSUE TITLE
Error in checking if Python belongs to a conda environment

### ISSUE THREAD

**Issue by gioboske** [Nuitka/Nuitka#580]
Python and Nuitka version:
```
nuitka: 0.6.5 to 0.6.6rc7 (both master and develop branch)
Python: 3.7.x (conda)
OS: Darwin
Arch: x86_64
```
To check if Python belongs to a conda environment, in general it is checked if "Anaconda" is included in `sys.version` string. From Python version 3.7 This lead to wrong results as explained in the comments of [this](https://stackoverflow.com/a/21282816/2809027) stackoverflow answer.
Instead of:
```
"Anaconda" in sys.version
```
the following should works for all supported Python version:
```
os.path.exists(os.path.join(sys.prefix, 'conda-meta'))
```

**This issue is probably related to #499.**
Maybe fixing it could lead to an easier fix of #499 (in place of PR #579).

I plan to report the outcome of some tests in the next few days.

**Comment by gioboske** [comment]
Definitively related to #95.

**Comment by kayhayen** [comment]
That's great, I was unaware of this. I saw your PR and will merge it. It conflates the static linking stuff, but like I said, that should be possible to decide.

We probably ought to make this detection result in a `conda_mode` towards `SingleExe.scons` code, and then just do static linking for these, but only if the Conda-CC is used. If asked to use any other, we could disable conda_mode, resulting in the performance loss.

My main concern with Conda-CC is that I was having erros with it on Windows, where gcc-5 is probably just a little big too old to not have some flukes. But this is not about Windows at all.

Thanks for your contributions, very much appreciated! I will look into this tomorrow I hope.

**Comment by gioboske** [comment]
Closing the issue, since PR #581 is merged.
Since this issue was limited to conda env check for Python 3.6+, opening a new issue (#595) to address for the new plan to make static linking and using conda-cc mandatory on non-Windows (as outlined by @kayhayen [here](https://github.com/Nuitka/Nuitka/pull/581#issuecomment-569212442) in PR #581).

**Comment by kayhayen** [comment]
The release 0.6.8 was just made and contains the correction.
