### ISSUE TITLE
Trying to bring sympy to the browser using nuitka + emscripten

### ISSUE THREAD

**Issue by dhiahassen** [Nuitka/Nuitka#582]
As the title tells , the aim is to compile and  run sympy on web browser , two monster tools are available for the mission , nuikta and emscripten ( i have done very deep search and tried all alternatives including brython ...but i landed here now , and i put this now as challenge for myself ) 

I have been trying to do this  all day, with no luck, sympy didnt compile from python to c , i tested nuikta with python tornado library and it worked perfectly 

> python -m nuitka --output-dir=tornado --module  --show-memory   --generate-c-only  --include-module=tornado   --recurse-all  C:\Users\USER\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\tornado

gave these files : 
`    module.colorama.ansi.c
    module.colorama.ansitowin32.c
    module.colorama.c
    module.colorama.initialise.c
    module.colorama.win32.c
    module.colorama.winterm.c
    module.tornado.auth.c
    module.tornado.autoreload.c
    module.tornado.c
    module.tornado.concurrent.c
    module.tornado.curl_httpclient.c
    module.tornado.escape.c
    module.tornado.gen.c
    module.tornado.http1connection.c
    module.tornado.httpclient.c
    module.tornado.httpserver.c
    module.tornado.httputil.c
    module.tornado.ioloop.c
    module.tornado.iostream.c
    module.tornado.locale.c
    module.tornado.locks.c
    module.tornado.log.c
    module.tornado.netutil.c
    module.tornado.options.c
    module.tornado.platform.asyncio.c
    module.tornado.platform.auto.c
    module.tornado.platform.c
    module.tornado.platform.caresresolver.c
    module.tornado.platform.interface.c
    module.tornado.platform.posix.c
    module.tornado.platform.twisted.c
    module.tornado.platform.windows.c
    module.tornado.process.c
    module.tornado.queues.c
    module.tornado.routing.c
    module.tornado.simple_httpclient.c
    module.tornado.tcpclient.c
    module.tornado.tcpserver.c
    module.tornado.template.c
    module.tornado.test.asyncio_test.c
    module.tornado.test.auth_test.c
    module.tornado.test.autoreload_test.c
    module.tornado.test.c
    module.tornado.test.concurrent_test.c
    module.tornado.test.curl_httpclient_test.c
    module.tornado.test.escape_test.c
    module.tornado.test.gen_test.c
    module.tornado.test.http1connection_test.c
    module.tornado.test.httpclient_test.c
    module.tornado.test.httpserver_test.c
    module.tornado.test.httputil_test.c
    module.tornado.test.import_test.c
    module.tornado.test.ioloop_test.c
    module.tornado.test.iostream_test.c
    module.tornado.test.locale_test.c
    module.tornado.test.locks_test.c
    module.tornado.test.log_test.c
    module.tornado.test.netutil_test.c
    module.tornado.test.options_test.c
    module.tornado.test.process_test.c
    module.tornado.test.queues_test.c
    module.tornado.test.resolve_test_helper.c
    module.tornado.test.routing_test.c
    module.tornado.test.runtests.c
    module.tornado.test.simple_httpclient_test.c
    module.tornado.test.tcpclient_test.c
    module.tornado.test.tcpserver_test.c
    module.tornado.test.template_test.c
    module.tornado.test.testing_test.c
    module.tornado.test.twisted_test.c
    module.tornado.test.util.c
    module.tornado.test.util_test.c
    module.tornado.test.websocket_test.c
    module.tornado.test.web_test.c
    module.tornado.test.windows_test.c
    module.tornado.test.wsgi_test.c
    module.tornado.testing.c
    module.tornado.util.c
    module.tornado.web.c
    module.tornado.websocket.c
    module.tornado.wsgi.c
    module.tornado._locale_data.c
    module.__internal__.c
    __constants.c
    __frozen.c
    __helpers.c
    __helpers.h`

the exact same command for sympy didn't work , gave the following :

> Nuitka:INFO:Memory usage changed loading module 'sympy': 324.00 KB (331776 bytes)
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nuitka\__main__.py", line 184, in <module>
    main()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nuitka\__main__.py", line 177, in main
    MainControl.main()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nuitka\MainControl.py", line 759, in main
    main_module = createNodeTree(filename=filename)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nuitka\MainControl.py", line 137, in createNodeTree
    plugin_filename=module_filename, module_package=module_package
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nuitka\importing\Recursion.py", line 294, in checkPluginSinglePath
    reason=reason,
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nuitka\importing\Recursion.py", line 166, in recurseTo
    reason=reason,
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nuitka\importing\Recursion.py", line 82, in _recurseTo
    is_shlib=module_kind == "shlib",
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nuitka\tree\Building.py", line 941, in decideModuleTree
    source_ref=source_ref,
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 598, in __init__
    source_ref=source_ref,
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 274, in __init__
    setLocalsDictType(self.module_dict_name, "module_dict")
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nuitka\nodes\LocalsScopes.py", line 31, in setLocalsDictType
    assert locals_dict_name not in locals_dict_handles, locals_dict_name
AssertionError: globals_sympy

There is alot of questions about that AssertError on the web appearing to many people , with no answers , in"AssertionError: globals_sympy" , i wonder why "sympy" appears within the variable name

and this command  : 

> C:\Users\USER\Desktop\dev\HelloWorld>python -m nuitka --output-dir=sympypp --no-pyi-file --include-package=sympy --module --jobs=4 --show-scons --show-memory --show-progress  --generate-c-only --follow-imports  C:\Users\USER\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\sympy

gave the exact same error message

my questions :
1-what is that message 
2-how to get rid of it
3-how can i get a c source code that i can later compile with emscripten and use sympy from javascript with same api names ( if possible that would be great , litterly hundreds of people on the net just want to run sympy on browser, and i would like to do it for my work project so that i won't have to create a python server )

i am using python 3.7 and last version on nuikta , win 64 , 8GB ram 

Thanks alot for the great library , hats down and respect

**Comment by stefnotch** [comment]
Out of curiosity, did you ever manage to get it to work?
