### ISSUE TITLE
PythonOCC project compiled with Nuitka running successfully from my IDE console but not from cmd console

### ISSUE THREAD

**Issue by math-artist** [Nuitka/Nuitka#585]
```
0.6.6rc7
Python: 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
Executable: C:\Users\Mak\Anaconda3\envs\fresh\python.exe
OS: Windows
Arch: x86_64
Nuitka-hints.py and get-hints.py: latest dev version with files from JorjMcKie.
```
Hi,
thanks again for this great project. I really like Nuitka and I continue to use it on new projects.

I compiled a project with Nuitka with an OpenCascade dependency. I was happy to see the executable run successfully from my first attempt. I had to manually copy all the .pyd files from my module folder:

`Anaconda3\envs\fresh\Lib\site-packages\OCC\Core`

to the root of the dist folder. It worked, but only from my IDE console. I suspect that from there it may add environment variables, but I can't really figure out how to fix.

When I remove the OCC pyd files and try to run from the windows cmd console, I get the same error message:
`ModuleNotFoundError: No module named "OCC.Core._GeomAbs"`

But when I copy all the .pyd files to the root of dist, I get the following error from the cmd console at the same module:
```
return _bootstrap._gcd_import(name[level:], package,level) 
ImportError: DLL load failed: The specific module could not be found
```
I have searched in all folders  in my Anaconda environment but I couldn't find any dll for PythonOCC, only a lot of pyd files.

I can share more about my PythonOCC setup, but I am suspecting a beginner's mistake here and thought that you may not need it.

**Comment by math-artist** [comment]
Update: I was able to get a useful traceback while trying to open the executable in a different environment:

```
Traceback (most recent call last):
  File "H:\Dev\REFC\nii.dist\OCC\Core\GeomAbs.py", line 45, in swig_import_helper
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'OCC.Core._GeomAbs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\Dev\REFC\nii.dist\nii.py", line 2, in <module>
  File "H:\Dev\REFC\nii.dist\Nii\__init__.py", line 2, in <module Nii>
  File "H:\Dev\REFC\nii.dist\Nii\NiiMain.py", line 12, in <module Nii.NiiMain>
  File "H:\Dev\REFC\nii.dist\CadModel.py", line 6, in <module CadModel>
  File "H:\Dev\REFC\nii.dist\OCC\Core\GeomAbs.py", line 48, in <module OCC.Core.GeomAbs>
  File "H:\Dev\REFC\nii.dist\OCC\Core\GeomAbs.py", line 47, in swig_import_helper
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\importlib\__init__.py", line 127, in import_module
ImportError: DLL load failed: La procédure spécifiée est introuvable.
```

So, it seems that the executable is trying to use importlib from my Anaconda environment used to compile.

I am also sharing the lines that triggered this:
```
# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

"""
GeomAbs module, see official documentation at
https://www.opencascade.com/doc/occt-7.4.0/refman/html/package_geomabs.html
"""

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _GeomAbs
else:
    import _GeomAbs

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _GeomAbs.SWIG_PyInstanceMethod_New
_swig_new_static_method = _GeomAbs.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr
```

At this point, I am really lost, with no knowledge about swig or any clue how to fix this.

**Comment by math-artist** [comment]
Copying the all dll from `\Library\bin\` to the root of the dist folder solved the problem.
It was probably hidden imports. 

What is your workflow to nail down the required imports?
I feel like I am missing a step and I end up doing a shotgun approach to get things to work.

**Comment by JorjMcKie** [comment]
I think you are right - it should be a hidden import problem. To solve this type of thing, usually some trial-and-error process is required (do some implicit imports, then try again ...) - sometimes this can be tuned by looking up information in analoguous projects, e.g. PyInstaller. Doesn't always do the job, though.

As you are asking for a standard process: Of course you can do this yourself if you want 😉 and modify your Nuitka installation until everything works fine. Those changes can then be integrated into Nuitka itself ...

But I am volunteering to help out once again: If you could give me your script - preferrably just the imports - I will find try and find out the missing pieces.

**Comment by JorjMcKie** [comment]
But more seriously:
I am using this script to help shortcutting the search for potentially required imports.
Given a package name, it will (recursively) look for shared library extensions (*.pyd, *.so, etc.) and output implicit import definitions to sys.stdout.
This output can be copy-pasted to e.g. the ``ImplicitImports.py`` module.
Example:

```python
python scan-dlls.py matplotlib

        elif full_name == "matplotlib":
            yield "matplotlib.ft2font", False
            yield "matplotlib.ttconv", False
            yield "matplotlib._contour", False
            yield "matplotlib._image", False
            yield "matplotlib._path", False
            yield "matplotlib._png", False
            yield "matplotlib._qhull", False
            yield "matplotlib._tri", False

        elif full_name == "matplotlib.backends":
            yield "matplotlib.backends._backend_agg", False
            yield "matplotlib.backends._tkagg", False
```
[scan-dlls.zip](https://github.com/Nuitka/Nuitka/files/3950500/scan-dlls.zip)
