### ISSUE TITLE
Nuitka on sources with Numba use

### ISSUE THREAD

**Issue by jurajmichalak1** [Nuitka/Nuitka#587]
I wanted to create binary file of our project which is deployed directly on customer servers. After short study I chose **nuitka**. My project binary built using nuitka was running until crash on method which is optimized using Numba. Numba compiles python bytecode which is not available in method compiled by Nuitka (what is good).

Is it possible to tell nuitka to keep/store/provide python bytecode of particular methods? So that Numba would be able to access python bytecode of that method?

I understand that nuitka creates C/C++ code directly from python source code and not from its "bytecode". But this would mean interoperability with NUMBA (win-win strategy for both projects).

Other option is to separate such methods into separate source files, and distribute nuitka binary with .pyc files with such numba methods - my goal is to "protect"/hide our python source code.

By the way:
We use anaconda. After I built binary I found out that I need explicit LD_LIBRARY_PATH=/home/user/anaconda/lib in order to execute created binary.

**Comment by kayhayen** [comment]
Regarding the last part, the issue template would really help. If you are on macOS, 0.6.6 should help.

As for the bytecode preservation, not sure how easy it is to include `numba` in standalone mode. Preserving the bytecode is surely something that we could do, even detecting the decorator of numba.

Could you do me the favor and produce a relatively minimal test case of a numba decorated function, maybe even doing something relatively meaningful?

Maybe it's a case for `@nuitka.hints.preserve_bytecode` to be created.

**Comment by jbwintergerst** [comment]
Hi @kayhayen,

I'm running into the same needs than @jurajmichalak1, what's the state of numba support in nuitka ?
Can I be of any help ?

**Comment by jbwintergerst** [comment]
Is it possible to auto include precompiled numba .so files ?

 * when leaving only the .so file, nuitka ignores it => `ImportError`
 * when leaving source .py file with .so file, nuitka uses the .py file despite seeing both files
    * it displays a warning about finding both files
    * tried adding `--no-prefer-source-code` (which should be default) but it still uses the .py file instead of the precompiled .so

Any idea about what's happening here ? :/

**Comment by kayhayen** [comment]
Can you produce a minimal test case for me to see this? I am not using Numba, and don't know about its workings. If it produces a `.so` for the whole module, I am very hopeful it can be put to work. I would even try to distill a test case for standalone mode out of it.

The `--no-prefer-source-code` ought to work correctly, from what I am seeing. But it's not really a good choice, since it's all global and covers more than necessary.

Are you using accelerated or standalone mode @jbwintergerst ?

**Comment by jbwintergerst** [comment]
I'm working on a test case this afternoon

I'm not using standalone nor accelerated. My objective is to compile a package.
Here's the command I'm using (will be in the test case): 
`python -m nuitka --module mymodule --include-package mymodule --no-pyi-file`

**Comment by jbwintergerst** [comment]
Here's a very minimal test case: https://github.com/jbwintergerst/nuitka-numba-compat

**Comment by jbwintergerst** [comment]
It might also be of some help to know that you can add numba's AOT compiler to a setup.py (not very practical since you have to add every file one by one, thus find them in somme way, but it's something):
https://numba.pydata.org/numba-doc/dev/user/pycc.html#distutils-integration

**Comment by jkbgbr** [comment]
Hi @kayhayen, @jbwintergerst,

As there are no follow-up posts, I guess there is not much progress on this matter. Are there any plans for this, is there a way to boost this topic?

**Comment by kayhayen** [comment]
The solution of #650 may or may not solve this, we shall see how this evolves.
