### ISSUE TITLE
TypeError running nuitka-hints.py for hinted-compile

### ISSUE THREAD

**Issue by nanowiz** [Nuitka/Nuitka#592]
I am running the develop version Nuitka v0.6.6rc8 on Python 3.7.3 on a Raspberry Pi 4. I installed Nuitka using ...

sudo python3 -m pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"

I have tried hinted-compile on HelloWorld and it worked fine. But the 2nd step of hinted-compile failed for my program with this error...

> TypeError: getImportsByFullname() takes 2 positional arguments but 3 were given

My program uses matplotlib and tkinter to plot dynamically to a window. I have simplified my program to just plot the time it takes to execute 3 of the key time consuming steps in each loop of the program over time. I created this so I can compare the execution times of the matplotlib routines with and without Nuitka compilation. You can try running the code without Nuitka to see it doing a live plot. You can watch the execution times slowing down as you make the system do other tasks, even just moving the mouse cursor around on my RPi4.

The link below points at my folder in Dropbox. The files of interest are...

 - **Plotloop.py** - the python program code
 - **SD_Plotloop_2019-12-20.txt** - screen dump of messages from the 2 hinted-compile steps

`https://www.dropbox.com/sh/48mpy4s1iv2w3rp/AAChmBXfkv4aQbPPRIaoapW2a?dl=0

**Comment by JorjMcKie** [comment]
please do a fresh download of the relevant hinted compilation scripts

**Comment by nanowiz** [comment]
I did not use scripts to do the compile. I just typed the commands into a terminal window. I haven’t learned how to use scripts. These commands and their outputs are in the SD_ file at my Dropbox link.

**Comment by JorjMcKie** [comment]
Download the scripts hinted-mods.py, nuitka-hints.py and get-hints.py from the hinted compile folder of the utilities folder please

Jorj

________________________________
Von: nanowiz <notifications@github.com>
Gesendet: Saturday, December 21, 2019 12:26:26 PM
An: Nuitka/Nuitka <Nuitka@noreply.github.com>
Cc: Jorj X. McKie <jorj.x.mckie@outlook.de>; Comment <comment@noreply.github.com>
Betreff: Re: [Nuitka/Nuitka] TypeError running nuitka-hints.py for hinted-compile (#592)


I did not use scripts to do the compile. I just typed the commands into a terminal window. I haven’t learned how to use scripts. These commands and their outputs are in the SD_ file at my Dropbox link.

**Comment by nanowiz** [comment]
@JorjMcKie yes I did already, and that was what I used to run the hunted compiles.

**Comment by JorjMcKie** [comment]
Well, something is definitely wrong somewhere in your setup. Cannot tell what and where from my end.
I just successfully compiled plotloop.py on Windows (Nuitka 0.6.6rc8) and Linux (Nuitka 0.6.6rc7) with the same hinted compilation scripts.

Just to get some variables out of the equation, try to do a normal vanilla Nuitka compile then.
Do not forget to enable all required plugins. Looks like you need something like this:

```
python -m nuitka --standalone --enable-plugin=qt-plugins --enable-plugin=numpy=matplotlib --enable-plugin=tk-inter plotloop.py
```

**Comment by nanowiz** [comment]
I did the normal compile using your command line with all the enable-plugin's. It came back with many unresolved warnings and no executable binary. When you did the hinted-compile, did you get an executable binary and did it run OK? Attached is the terminal output of the normal compile. What do you think I should do next?
[SD_NormalCompile_2019-12-22.txt](https://github.com/Nuitka/Nuitka/files/3993070/SD_NormalCompile_2019-12-22.txt)

**Comment by nanowiz** [comment]
@JorjMcKie   I searched for the name pyplot* and found various versions of it installed under the python2.7, python3 and python3.7 folders. Could this be the problem? When I ran the hinted-compile, I started with python3. Not sure if that uses the files in the python3 folder or the python3.7 folder. Attached is the result of searching for pyplot* in the file manager.
![pyplot folders](https://user-images.githubusercontent.com/58935539/71382098-4239fd80-258b-11ea-9922-3f8289861793.png)

**Comment by nanowiz** [comment]
@JorjMcKie  My file system shows that I have matplotlib versions 2.2.4, 3.0.2 and 3.1.2 installed. Perhaps that is the reason I am having problems? Any case I tried to uninstall all of them and reinstall the latest. I ran the following 2 uninstalls and I got these results...
![image](https://user-images.githubusercontent.com/58935539/71434984-d1363b00-269b-11ea-9918-4a85c7e3f73a.png)
![image](https://user-images.githubusercontent.com/58935539/71435051-1ce8e480-269c-11ea-8d12-97a100b649e4.png)
After these 2 uninstalls, searching the file system for matplotlib* shows the following...
![image](https://user-images.githubusercontent.com/58935539/71435152-97b1ff80-269c-11ea-98c0-5a70acc75575.png)
So, I still have matplotlib version 3.0.2 installed in the python3/dist-packages/ folder. But additional steps to uninstall it fails saying that it cannot be found. Listing it using `dpkg --list` doesn't show it either.
What do you think I should do? Should I completely rebuild my system?

**Comment by JorjMcKie** [comment]
Sorry for not coming back to this for a few days.
I have been investigating in the meantime, though.

1. The error around **_missing pyplot_** is very, **_very_** weird: it only happens on Linux - Windows works just fine. It does not have anything to do with your configuration. I am still trying to isolate this problem on my machine. I suspect it is a Nuitka internal error.

2. Your error ``TypeError: getImportsByFullname() takes 2 positional arguments but 3 were given`` however shows that you have a major problem in your installation: it show that the respective Nuitka version is not on a level compatible with the hinted compilation modules. What is wrong in detail - I do not know.

**Comment by JorjMcKie** [comment]
@nanowiz - I've had some success, at least sort of:
Here is a version of your plotloop script which works on my Linux.
The critical change concerns how ``matplotlib.pyplot`` is imported:

```python
import math  # provides math functions
import sys
import time
from datetime import datetime
from tkinter import Tk

import matplotlib

matplotlib.use("TkAgg")  # prevents unneeded imports of matplotlib modules
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from matplotlib import pyplot as plt  # put this at the end after right backend is established
...
```

Apparently this keeps Nuitka from doing wrong things.
Using method ``matplotlib.use("TkAgg")`` directly after importing matplotlib ensures that matplotlib knows early enough which backend (tkinter in your case) you want. There will be no unnecessary imports of other backends.
Please try this one out and let me know how it works.

**Comment by nanowiz** [comment]
@JorjMcKie Thanks for the changes. But I am not able to try it yet as I am in the process of completely rebuilding my system hoping that it will solve the TypeError problem. In the newwly built system, I have not been able to uninstall version 3.0.2 of matplotlib that came pre-installed in Raspbian.  When I try to install with:
`pip install --upgrade matplotlib`
 It fails with permission errors when it trys to uninstall matplotlib 3.0.2. If I add sudo in front of the above command, it skips uninstalling 3.0.2 and installs the new one into a different folder. So I don't know which version python is actually using when I run the program.
Also when I install Nuitka. I used the command you gave me:
`pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"`
This errors out with a permission error at '/usr/local/lib/python3.7/dist-packages/nuitka'
I then tried adding sudo in front of your command. That went fine. But on searching for nuitka, it got installed at /usr/local/lib/python2.7/dist-packages and not under python3.7. Since my program is written for Python3, This will not work.
Any advise on how to solve this issue? Below is the terminal log of running these 2 commands:
```
pi@raspberrypi:~ $ pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/Nuitka/Nuitka/archive/develop.zip
  Downloading https://github.com/Nuitka/Nuitka/archive/develop.zip
     \ 17.9MB 128kB/s
Building wheels for collected packages: Nuitka
  Building wheel for Nuitka (setup.py) ... done
  Created wheel for Nuitka: filename=Nuitka-0.6.7rc1-cp37-none-any.whl size=2109902 sha256=930191aa573fcef6ff533aff575b68a581f6880ea66759e372020e6a61dc4178
  Stored in directory: /tmp/pip-ephem-wheel-cache-vxh55syd/wheels/0c/05/10/5c8eb818478cd708db02ffd33230cc0ae8f293d35a22daaf8d
Successfully built Nuitka
Installing collected packages: Nuitka
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.7/dist-packages/nuitka'
Consider using the `--user` option or check the permissions.

pi@raspberrypi:~ $ sudo pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/Nuitka/Nuitka/archive/develop.zip
  Downloading https://github.com/Nuitka/Nuitka/archive/develop.zip
     / 4.1MB 13.0MB/s
Building wheels for collected packages: Nuitka
  Running setup.py bdist_wheel for Nuitka ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-qI4jzT/wheels/0c/05/10/5c8eb818478cd708db02ffd33230cc0ae8f293d35a22daaf8d
Successfully built Nuitka
Installing collected packages: Nuitka
Successfully installed Nuitka-0.6.7rc1
pi@raspberrypi:~ $ 

```
Below is the result of searching afterwards for nuitka* using the file manager :
![image](https://user-images.githubusercontent.com/58935539/71554266-f72c4a00-29d1-11ea-9112-018fbb594b6f.png)

**Comment by JorjMcKie** [comment]
Well, I'm not acquainted with Raspberry, and I have only limited experience with Linux either.
But I think you should **_always_** use ``python?? -m pip install ...`` to ensure the right pip for the desired Python version ?? is chosen. I **never ever** do a simple ``pip (un)install ...``!

To remove unwanted installations: can you not simply manually delete them from the respective ``dist-packages`` or ``site-packages``? Of course while being under elevated privilegdes! Remove the ``nuitka`` and the ``Nuitka-0.6.7...`` folders as required.

**Comment by nanowiz** [comment]
OK. Adding `python3 -m` installed Nuitka in the right place. I am not familiar with the Raspbian environment and was not sure if it is OK just to delete the 3.0.3 matplotlib package folders. Took the plunge and did it, then installed latest matplotlib with `python3 -m pip install -U matplotlib`. Now everything is working. Hinted compile completed in 51 minutes and the binary works fine. It is interesting however that the compiled version is slightly slower than the interpreted version. You can see it in the plot below. The call to clear() is a hair slower in the compiled version. Top plot is the interpreted version side by side with the compiled version below. Left axis is execution time in seconds for each call into matplotlib. The LT value in the title is the total looptime of the program.
![image](https://user-images.githubusercontent.com/58935539/71561869-51102c80-2a31-11ea-8349-e808382de81c.png)
Thank you so much for the help. Please let me know when you fix this import problem for good.

**Comment by JorjMcKie** [comment]
> Please let me know when you fix this import problem for good.

I will make a few more tests with alternatives.
There is a weird difference between the Linux and Windows versions of matplotlib concerning the standard backend:

* in Windows I am getting this default backend:

```python
Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import matplotlib
>>> matplotlib.get_backend()
'TkAgg'
>>> 
```

* whereas in Linux the same commands deliver this:

```python
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license()" for more information.
>>> import matplotlib
>>> matplotlib.get_backend()
'Qt5Agg'
>>> 
``` 

The ``use("TkAgg")`` method call I was recommending to you changed that to the Windows standard "TkAgg" and then everything worked fine.
So what I will probably do is setting this value as the standard in the plugin.
I will let you know how this turns out.
I think for now we can close this issue, right?

**Comment by nanowiz** [comment]
Yes, I tried that and I get `Qt5Agg` as well.
Yes, we can close this issue now. Thank you.
