### ISSUE TITLE
add --onefile method to one file all .dll and .pyd files.

### ISSUE THREAD

**Issue by byehack** [Nuitka/Nuitka#594]
like pyinstaller

**Comment by JorjMcKie** [comment]
look here https://github.com/Nuitka/NUITKA-Utilities

**Comment by byehack** [comment]
> look here https://github.com/Nuitka/NUITKA-Utilities

which one is appropriate for me?

**Comment by byehack** [comment]
'onefile-maker-windows.py' is using by `nsis` but i don't want this. i want when i execute standalone.exe  it starts in current directory and don't change its cwd to temp. i don't want sfx, i want one-file exe like pyinstaller. can you use pyinstaller --onefile method and add _MEIPASS to sys module?

**Comment by JorjMcKie** [comment]
Pyinstaller does a similar thing as NSIS, namely expand its stuff in a temp folder, execute the main script there, return to the folder where the onefile exe lives and remove the temp folder.
See here:
Script:
```python
# -*- coding: utf-8 -*-
from __future__ import print_function
import os, sys
import tkinter as tk
root = tk.Tk()
width = root.winfo_screenwidth()
height = root.winfo_screenheight()
root.destroy()
del root
print("physical screen: %ix%i" % (width, height))
print("executable:", sys.executable)
print("base_prefix:", sys.base_prefix)
print("base_exec_prefix:", sys.base_exec_prefix)
print("exec_prefix:", sys.exec_prefix)
print("prefix:", sys.prefix)
print("frozen:", hasattr(sys, "frozen"))
print("__file__:", __file__)
print("__name__:", __name__)
if len(sys.path) > 1:
    print("running interpreted")
else:
    print("running frozen")
```

Compile command: ``pyinstaller --onefile --noupx tk-test.py``
Execution log:
```
D:\Jorj\Desktop\Develop\PyInstaller\dist>tk-test
physical screen: 1920x1080
executable: D:\Jorj\Desktop\Develop\PyInstaller\dist\tk-test.exe
base_prefix: D:\Jorj\Temp\_MEI44402
base_exec_prefix: D:\Jorj\Temp\_MEI44402
exec_prefix: D:\Jorj\Temp\_MEI44402
prefix: D:\Jorj\Temp\_MEI44402
frozen: True
__file__: tk-test.py
__name__: __main__
running interpreted

D:\Jorj\Desktop\Develop\PyInstaller\dist>
```

**Comment by byehack** [comment]
no pyinstaller doesn't do this:
![image](https://user-images.githubusercontent.com/26390254/71415621-d7172680-2671-11ea-9872-49c8308e976b.png)
look at the title!
and another problem is virus detect by anti virus with `onefile-maker-windows.py`.
it detected as virus beacuse it uses sfx archive method.

**Comment by byehack** [comment]
> Compile command: `pyinstaller --onefile --noupx tk-test.py`

compile with nuitka and onefile with nsis:
![image](https://user-images.githubusercontent.com/26390254/71415945-86a0c880-2673-11ea-950a-76c91386d79e.png)
it is so differ from pyinstaller. no?

**Comment by byehack** [comment]
please just add this feature that the app just extract the .dll and .pyd in the temp folder, without extract main app.exe in the temp folder.

**Comment by JorjMcKie** [comment]
> please just add this feature that the app just extract the .dll and .pyd in the temp folder, without extract main app.exe in the temp folder.

1. This would need a major change in the way Nuitka builds the dist folder. Not to talk about whether this is possible at all.
2. As far as I am concerned: no - I have no time to do that.
3. Apart from the virus detection sensitivity for the sfx part (which can easily be overcome) there **_is_** no major difference in the behaviour of the two approaches: pyinstaller **_does_** extract into a temp folder - I saw it appearing with my own eyes - then it executes the script **_there_**, then it returns to the folder of the EXE. It does not just put binaries therein, but the complete interpreter too.
4. NSIS generation can easily be adapted to change the behaviour of the generated executable. I currently see no reason to give up the use of that product.

If you see a way to implement a different approach, you are certainly welcome to contribute it!

**Comment by byehack** [comment]
> 1. This would need a major change in the way Nuitka builds the dist folder. Not to talk about whether this is possible at all.

so it is possible!


> 3\. Apart from the virus detection sensitivity for the sfx part (which can easily be overcome)

can u say how?



> 3\. pyinstaller **_does_** extract into a temp folder - I saw it appearing with my own eyes -

yes but not the mainApp.exe! it just extract the libraries and add _MEIPASS to sys.path to use them.


> 3\. It does not just put binaries therein, but the complete interpreter too.

exactly yes it. i think the nuitka do this work, the virus detection problem can be solve.


> If you see a way to implement a different approach, you are certainly welcome to contribute it!


i don't have time like you. for this i asked you: "can you add --onefile method of pyinstaller to nuitka?"

**Comment by JorjMcKie** [comment]
> so it is possible!

On the contrary: major part of the effort would be determining **_if_** this is possible.
But this is a fruitless discussion, because pyinstaller does not do it either:
* pyinstaller's envelopping EXE calls the python interpreter inside the temp folder feeding it with the bytecode of the main script - also residing inside the temp folder like everything else - a mixture of binaries, python bytecodes and a ZIP of the standard library.
* Nuitka's envelopping EXE calls the (same-named) EXE inside the temp folder (no interpreter involved), which also contains all the rest of required things, but no bytecode, no ZIP file, ... only binaries.
