### ISSUE TITLE
No module named 'urllib3.connectionpool' despite 'import urllib3'

### ISSUE THREAD

**Issue by zpin** [Nuitka/Nuitka#604]
Even though `urllib3` is explicitly imported in this 2 line script below it throws the error in the subject when running the compiled program.

**Environment info**
Nuitka develop and also tested versions as far back as 5.33, Python 3.7.6 installed from source, all packages installed using pip. Tested on both Linux and Windows.

**Reproduction steps**
test.py:
```
import urllib3
from requests_toolbelt.adapters.source import SourceAddressAdapter
```
nuitka3 --standalone test.py
```
Nuitka:WARNING:Unresolved '__import__' call at '/usr/local/lib/python3.7/site-packages/requests/packages.py:7' may require use of '--include-plugin-directory' or '--include-plugin-files'. 
```

./test.dist/test
```
Traceback (most recent call last):
  File "/home/user/test/test.dist/test.py", line 1, in <module>
  File "/home/user/test/test.dist/urllib3/__init__.py", line 7, in <module urllib3>
ModuleNotFoundError: No module named 'urllib3.connectionpool'
```

It can be fixed by explicitly adding `urllib3` as a package to include but since there's already an `import urllib3` statement this shouldn't be necessary:
nuitka3 --standalone test.py  --include-package=urllib3

**Comment by JorjMcKie** [comment]
Things like this may nevertheless happen if an "implicit import" necessary.
I am checking this out.

**Comment by JorjMcKie** [comment]
@zpin - confirming:
After changes to the ``ImplicitImports.py`` plugin, your skeleton script does work.
Changes will be published with the next nuitka version. If you have any urgency or would like to do more tests yourself, here is the new version:
[ImplicitImports.zip](https://github.com/Nuitka/Nuitka/files/4045949/ImplicitImports.zip)

**Comment by zpin** [comment]
Great, thank you :) I've tested the new file and it works fine now.

**Comment by themcclure** [comment]
I applied the ImplicImports.py above but I am still getting an error. Mine is slightly different to the one above:
`ModuleNotFoundError: No module named 'urllib3.util.ssl_'`

I am using the latest available via pip: v0.6.8.4

**Comment by Mte90** [comment]
I have the same error with 0.6.11.3.
I am getting this with `pygsheets google-auth-httplib2` those dependences.

**Comment by anAngryAnt** [comment]
^ have same error.
any solution?

**Comment by kayhayen** [comment]
Make new reports.
