### ISSUE TITLE
[NOT A BUG] Improving documentation about standalone

### ISSUE THREAD

**Issue by deajan** [Nuitka/Nuitka#605]
Hello,

I am currently deploying a nuitka built standalone program on a couple of different machines, and noticed that the api-ms-win-crt-*.dll files that come with Nuitka aren't enough depending on the target OS.

Example:
My program asked for api-ms-win-crt-conio-l1-1-0.dll which wasn't present on a vanilla Windows 7 32-bit OS, and which wasn't bundled by nuitka when compiled on Win10 x64.

Indeed, Windows 10 does ucrt.dll, and rehooks all api-ms-win-crt* dll calls to that specific DLL.

I came to the conclusion that in order to get my standalone executable work on all Windows platforms from Win7 to Win10, I had to install Visual C 2015 redistributable first, vc_redistx.86.exe or vc_redist.x64.exe, which has all the necessary updates to use ucrt.dll from WinXP to Win10.

Indeed the version of Visual C (2012/2014/2015) changes depending on the Python version used by Nuitka.
I found that neat table here https://wiki.python.org/moin/WindowsCompilers which I updated with the year 

Visual C++ verison|Year| CPython
-- | --|--
14.X | 2015| 3.5, 3.6, 3.7, 3.8
10.0 | 2010| 3.3, 3.4
9.0 | 2008| 2.6, 2.7, 3.0, 3.1, 3.2

I think it would be nice to state that in the Nuitka documentation somewhere.
Before making a PR, can you confirm my findings ?

Best regards.

**Comment by kayhayen** [comment]
Windows 7 is not really on the list of things intended to be supported, and I wouldn't be too surprised if many Python extension modules were no longer running on it. But if I understand you correctly, this is what it takes, I guess we should have a HowTo document.

One important element of howto on Linux, is to build on the oldest system you intend to support. Going forward is usually possible, going backware, the way programs on Linux e.g. link against DLL requires higher versions of the libc, which then will only work with a certain kernel.

But if this works for Windows 10 to 7, surely we can document it. I just fear that's a moving target. And now that Windows 7 is so deeply EOL it's rather late to start supporting it.

Also notice that Nuitka works with every MSVC with even Python 2.6, and every new enough MinGW 64 for every Python. 

We now ignore everything in the system folder with good success. If we open this up for the ms-api libraries, we need to know really well what we are doing though.

Scary to me, but if it is tested and works, right. But do we maintain it?

**Comment by deajan** [comment]
Well yes, Windows 7 is EOL, but this also applies to Windows 8 and 8.1.

Python already ships with 2 standard VC dlls, vcruntimeXXX.dll and mfcuXXX.dll.
The thing is that vc_redist is already baked into Windows 10 (unless a newer python version will be linked with a newer vc_redist which isn't yet baked in).

It's just giving an advice that installing vc_redist on elder Windows versions will most probably fix some missing dlls that don't ship with a Nuitka standalone program.

There's no maintenace burden to me ;)

As of my understandings, one may compile an executable with any windows version for any windows other windows version (excluding windows 9X ;)), as long as one respects the bitness and ships the right runtime dlls.

**Comment by deajan** [comment]
As for the tests, I'm currently rolling out a Nuitka compiled program on about 2500 computers, which range from Windows 7 to Windows 10, Windows Server 2008 R2 to Windows Server 2019, all in x86 and x64 bits.
I'd like to get rid of Windows 7 in most cases too, but well... industrial computers can't be upgraded sometimes.

My first tests, about 100 machines, went good.
Most machines had already the vc dlls packed by another app, but since I packaged vc_redist into my installer, I didn't find any machine that could not run my program :)

**Comment by kamgha** [comment]
> api-ms-win-crt-conio-l1-1-0.dll which wasn't present on a vanilla Windows 7 32-bit

@deajan Those files will/should be available after updating Windows via "Windows Update" with KB2999226, or install it manually from here: https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows

In the end, it depends on what compiler you use and Windows SDK you build it against. You'll probably be able to avoid this situation by using e. g. MinGW64 and building Python and all dependencies from source with that as well.

You can also make sure on what you need by looking at your executables and DLLs in Dependency Walker.

**Comment by deajan** [comment]
@kamgha That's the whole point of installing VC runtime, which actually contains KB2999226 for every OS from Vista SP2 to Win8.1, rendering the nuitka standalone distribution compiling platform independent.
Btw, I use MinGW64 and do build my dependencies... But Microsoft DLLs aren't built from scratch ;)

**Comment by kayhayen** [comment]
Thinking of it, for now this seems pretty safe, so lets go for it. Your PR is awaited. :)

**Comment by deajan** [comment]
Closing this issue since it has been resolved.
