### ISSUE TITLE
As of 1.4x skipy has changed 'extra-dll' to '.libs'

### ISSUE THREAD

**Issue by paul-spg** [Nuitka/Nuitka#606]
Adding a check for ".libs" after "extra-dll" fails solved the issue, see attachment

https://github.com/Nuitka/Nuitka/blob/93efba8a6a55335beac101f1179f59b19c2f1a03/nuitka/plugins/standard/NumpyPlugin.py#L52

code change in attached txt file.
[NumpyPlugin.py.txt](https://github.com/Nuitka/Nuitka/files/4109409/NumpyPlugin.py.txt)

**Comment by kayhayen** [comment]
This has become obsolete, I must have overlooked it.
