### ISSUE TITLE
Segfault on GTK/Linux

### ISSUE THREAD

**Issue by belonesox** [Nuitka/Nuitka#607]
>  python -m nuitka --version
```
$ python3 -m nuitka --version
0.6.7
Python: 3.7.6 (default, Dec 19 2019, 22:50:01)
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
```

>How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,

pip3 install nuitka

> If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)

https://github.com/belonesox/wtf-gtk-nuitka 
```python
#!/usr/bin/env python3
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

class WTF(Gtk.Window):
    def __init__(self, file_list=None, width=1024, height=768):
        super(WTF, self).__init__()

    def run(self):
        self.show_all()
        Gtk.main()

    def set_key_handler(self, fcn):
        pass

    def quit(self):
        Gtk.main_quit()

if __name__ == "__main__":
    win = WTF()
    win.run()
```

build by
```
python3 -m nuitka --standalone  wtf.py 
```

executable crashed with:
```
(process:30957): Gtk-CRITICAL **: 23:27:38.516: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(process:30957): Gtk-CRITICAL **: 23:27:38.516: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(process:30957): Gtk-CRITICAL **: 23:27:38.516: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed
Segmentation fault (core dumped)
```

**Comment by ntd** [comment]
Same as anthony-tuininga/cx_Freeze/issues/571.

This bug happens when trying to create a GTK widget without X server access. See the [upstream GTK bug](https://gitlab.gnome.org/GNOME/gtk/-/issues/994).

**Comment by belonesox** [comment]
@ntd Thank you!
But I cannot get why working sample GTK/python code stop working after compiling by Nuitka and cx_freeze. "lost X server access?" — why python process have it, but compiled binaries have no access. 
Because I wish to find any workaround without waiting fixing bug in GTK upstream.

**Comment by ntd** [comment]
>  Because I wish to find any workaround without waiting fixing bug in GTK upstream.

This *will never* be fixed because it is not considered a bug. Check the upstream issue for details.

> But I cannot get why working sample GTK/python code stop working after compiling by Nuitka and cx_freeze. "lost X server access?" — why python process have it, but compiled binaries have no access.

No idea: I have no clue of what Nuitka and cx_freeze are. I just run into this very same issue on [my C project](/ntd/adg/commit/bc2c2c90cf0ff7cb02eba5fab8493a6094940354).

Looking for information at that time I also found that a missing `Gtk.init()` call could produce similar results: try to put it before calling `WTF()`.

**Comment by belonesox** [comment]
Bug can be closed, working workaround → add «Gtk.init()» after import.

```
from gi.repository import Gtk
Gtk.init()
```

**Comment by kayhayen** [comment]
Seems this was never a Nuitka issue at all.
