### ISSUE TITLE
Remove PyDoc Comments on Build?

### ISSUE THREAD

**Issue by r-clancy** [Nuitka/Nuitka#608]
I am using Nuitka to provide some source code protection for a package, but it leaves all of the pydoc comments in the compiled `.so` file produced by using `bdist_nuitka`. This leaks information about the implementation that we don't want to share.

Without doing some hack like using an external tool to remove all pydocs comments, compile with Nuitka, and recover the old code to keep the pydoc comments, is there a way to do this? Can this option be added as a option similar to the `Cython.Compiler.Options.docstrings = False` option in Cython?

**Comment by kayhayen** [comment]
This is already implemented. Use `--python-flag=no_docstrings` or directly go `--python-flag=-OO` but that also disables assertions.
