### ISSUE TITLE
Freebsd 11.2-RELEASE LIST_CONCAT too few arguments provided to function-like macro

### ISSUE THREAD

**Issue by jsonpaul** [Nuitka/Nuitka#609]
Platform: FreeBSD  11.2-RELEASE

Version Info:
0.6.8rc1 
Python: 3.7.6 (default, Jan  2 2020, 01:18:33)
Executable: /root/venv3/bin/python
OS: FreeBSD
Arch: amd64

FreeBSD image: https://download.freebsd.org/ftp/releases/ISO-IMAGES/11.2/FreeBSD-11.2-RELEASE-amd64-disc1.iso

I setup a Freebsd 11.2 machine and have python code running on it. I installed nuitka using pkg and found the error below whilst trying to convert my project. After a few tries and trying the --clang flag i decided to try and convert a simple hello world python script and even that failed. I then went on to install nuitka on the machine using the repository but still got the same error. I also tried the same on FreeBSD 11.3-RELEASE and still got the same error. 

It seems as though the definition for the LIST_CONCAT function is being pulled from the system queue.h file rather than the definition in the lists.h header file in python after installing nuitka. I tried to remove the __IF_IDE__ check on the files to include the prelude.h file in nuitka in hopes that it would use the function definition in the lists.h file but that did not help.

I have however successfully used nuitka to convert my project on Debian Linux without any issues. The issue only seems to happen on FreeBSD. Also that gave me hope that my code was not the issue.

Code Example:
`def helloworld():
    print("HELLO WHATS UP WORLD")

if __name__=="__main__":
    helloworld()`

ERROR:
`(venv3) root@:~ # python -m nuitka --module pythontest.py --debug
In file included from static_src/CompiledCodeHelpers.c:2102:
In file included from /root/venv3/lib/python3.7/site-packages/Nuitka-0.6.8rc1-py3.7.egg/nuitka/build/static_src/HelpersOperationBinaryAdd.c:23:
/root/venv3/lib/python3.7/site-packages/Nuitka-0.6.8rc1-py3.7.egg/nuitka/build/static_src/HelpersOperationBinaryAddUtils.c:122:42: error:
      too few arguments provided to function-like macro invocation
    return LIST_CONCAT(operand1, operand2);
                                         ^
/usr/include/sys/queue.h:467:9: note: macro 'LIST_CONCAT' defined here
#define LIST_CONCAT(head1, head2, type, field) do {                           \
        ^
1 error generated.
scons: *** [static_src/CompiledCodeHelpers.os] Error 1`

**Comment by kayhayen** [comment]
My bad for not namespacing these macros of Nuitka. I will make a fixup shortly.

Yours,
Kay

**Comment by kayhayen** [comment]
So this is now on the develop branch and will be part of the 0.6.9 release, which hopefully is not too far off. I wanted to make it part of the hotfix, but then I forgot. :/

**Comment by kayhayen** [comment]
This is the last release 0.6.9 already for a while.
