### ISSUE TITLE
Nuitka terminated  compiling when cannot find implicit module

### ISSUE THREAD

**Issue by redstoneleo** [Nuitka/Nuitka#619]
Nuitka terminated  compiling when cannot find implicit module

```
.....
Nuitka:INFO:Doing module local optimizations for 'PIL.ImageFont'.
Nuitka:INFO:Optimizing module 'PIL._imagingft', 26 more modules to go after that
.
Nuitka:INFO:Optimizing module 'cv2', 25 more modules to go after that.
Error, implicit module 'numpy' expected by 'cv2' not found.
```

**Comment by JorjMcKie** [comment]
> Nuitka terminated compiling when cannot find implicit module

... which is the intended behaviour!
To properly describe your problem, please provide mandatory information for the issue by using the template.
