### ISSUE TITLE
Support for multiline imports in pyi files

### ISSUE THREAD

**Issue by kennroland** [Nuitka/Nuitka#620]
To support Python packages with multiline imports a possible solution is attached. The change is made in function _readPyPIFile in the file /nodes/ModuleNodes.py

[ModuleNodes.zip](https://github.com/Nuitka/Nuitka/files/4185401/ModuleNodes.zip)

**Comment by kayhayen** [comment]
This is now on develop, and going to be part of the next release.

**Comment by kayhayen** [comment]
The release 0.6.8 was just made and contains the correction.
