### ISSUE TITLE
MSYS2 with Anaconda Python: Mismatch between Python and C compiler arches.

### ISSUE THREAD

**Issue by mantielero** [Nuitka/Nuitka#621]
# Environment

Windows 10 64bits

0.6.7
Python: 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
Executable: C:\Users\cxxxxx\AppData\Local\Continuum\anaconda3\python.exe
OS: Windows
Arch: x86_64

Nuitka installed with conda

MSYS2 instead of MINGW64.

# Issue
I am trying nuitka for the first time. When I try to process the web's example, I get:

```
C:>   python -m nuitka --follow-imports hello.py
Error, mismatch between Python ('x86_64') and C compiler ('None') arches.
C:> gcc --version
gcc (Rev2, Built by MSYS2 project) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
C:> gcc -dumpmachine
x86_64-w64-mingw32
```

**Comment by kayhayen** [comment]
The MSYS2 compiler is unsupported with anything but the MSYS2 python. I think the Anaconda libpython won't be usable with it.
