### ISSUE TITLE
Why compiled function of module __code__ return development source file path?

### ISSUE THREAD

**Issue by geekgao** [Nuitka/Nuitka#624]
Nuitka Version: 0.6.7  

> In [3]: some_method
Out[3]: <compiled_function some_method at 0x0000000004DB2862>
>
>In [4]: some_method.__code__
Out[4]: <code object some_method at 0x0000000004DB2862, file "E:\proj\win32\cmn.py", line 10> 

The path **file "E:\proj\win32\cmn.py"**  ,how can i remove or strip it ?

**Comment by kayhayen** [comment]
This is described in the help output. Also the user manual will reveal information to you. You need to pick appriopiate modes to influence these things.
