### ISSUE TITLE
Exception swallowed in awaited coroutine is still bubbled up

### ISSUE THREAD

**Issue by nohack** [Nuitka/Nuitka#626]
1)
When you make a network call to a non existent url using aiohttp in a coroutine assume get(), and you wrap the code inside get() with a try catch so that any network issues are swallowed, the coroutine which awaits on get() is still returning `RuntimeError: cannot reuse already awaited compiled_coroutine get`.

[main.py](https://github.com/infinitedeep/nuitka-aiohttp-bug/blob/master/main.py#L11) -> [magic.py](https://github.com/infinitedeep/nuitka-aiohttp-bug/blob/master/utils/magic.py#L4) -> [network.py](https://github.com/infinitedeep/nuitka-aiohttp-bug/blob/master/utils/network.py#L3)

You expect this [print](https://github.com/infinitedeep/nuitka-aiohttp-bug/blob/master/utils/magic.py#L7) to be logged but it doesn't.

There are similar bugs such as Bug #165 but not exactly like this.

* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

  python -m nuitka --version

  0.6.7
  Python: 3.6.10 (default, Jan  4 2020, 03:22:06) 
  Executable: /usr/local/bin/python
  OS: Linux
  Arch: x86_64

Below is the repo with full explanation

https://github.com/infinitedeep/nuitka-aiohttp-bug

2)
An additional observation: If I remove the proxy magic.py and invoke get() coroutine of network.py from main.py directly, the code works.Below is the repo for this

https://github.com/infinitedeep/nuitka-aiohttp-working

**Comment by kayhayen** [comment]
Sorry, this was actually an excellent bug, but it escaped my attention at the time. It now worked just fine for me, async got a bunch of improvements since, one of which solved your issue.
