### ISSUE TITLE
problem to add requests modules

### ISSUE THREAD

**Issue by BlackRouter** [Nuitka/Nuitka#627]
hi

i have problem to add modules requests with nuitka in windows.

`nuitka main.py --show-progress --recurse-all --standalone`

Warning:

![2020-02-20_232705](https://user-images.githubusercontent.com/15177510/74974068-d1537c80-5439-11ea-94bd-4f1880a3c095.jpg)

**Comment by JorjMcKie** [comment]
You did not use the mandatory form for submitting issues. Several information details are missing.
Also, the included image does not reveal a problem: this compile might have delivered a usable binary ... after all a warning is just a warning.

**Comment by kayhayen** [comment]
@JorjMcKie lets always put `needs_example` tag to these, I periodically go other these and close those without reactions. Or just close immediately if the report is too bad. This warning is scheduled to die btw, dummies don't get it, pros don't need it.

**Comment by BlackRouter** [comment]
@kayhayen nuitka warning for requests

`Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\Javad\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\packages.py:7' may require use of '--include-plugin-directory' or '--include-plugin-files'.`

package.py in requests:

```
import sys

# This code exists for backwards compatibility reasons.
# I don't like it either. Just look the other way. :)

for package in ('urllib3', 'idna', 'chardet'):
    locals()[package] = __import__(package)
    # This traversal is apparently necessary such that the identities are
    # preserved (requests.packages.urllib3.* is urllib3.*)
    for mod in list(sys.modules):
        if mod == package or mod.startswith(package + '.'):
            sys.modules['requests.packages.' + mod] = sys.modules[mod]

# Kinda cool, though, right?
```

**Comment by jokin1999** [comment]
have the same problem and don't know how to resolve it

**Comment by kayhayen** [comment]
If the warning is the problem, the warning is justified, but probably not too important. Anyway, this report is too bad to work with.
