### ISSUE TITLE
Using multiple modules and asyncgen: cannot reuse already awaited compiled_coroutine

### ISSUE THREAD

**Issue by 48000** [Nuitka/Nuitka#629]
Version of Python and Nuitka:

```
$ python -m pip install nuitka
$ python -m nuitka --version
0.6.7
Python: 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Users\nexcvon\.virtualenvs\hello\Scripts\python.exe
OS: Windows
Arch: x86_64
```

Create 3 files, `a.py`, `b.py`, `c.py`.

a.py:
```
import asyncio

async def f():
    await asyncio.sleep(5)
```

b.py:
```
import a

async def g():
    await a.f()
```

c.py:
```
import asyncio
import b

async def f():
    t = asyncio.ensure_future(b.g())
    asyncio.get_running_loop().call_later(1, t.cancel)
    await t

asyncio.get_event_loop().run_until_complete(f())
```

Run commands:
```
> python -m nuitka --module --nofollow-imports a.py
> python -m nuitka --module --nofollow-imports b.py
> python c.py
```

Get error:
```
Traceback (most recent call last):
  File "c.py", line 17, in <module>
    main()
  File "c.py", line 13, in main
    asyncio.get_event_loop().run_until_complete(f())
  File "C:\Users\nexcvon\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 612, in run_until_complete
    return future.result()
  File "c.py", line 9, in f
    await t
  File "b.py", line 6, in g
    await a.f()
RuntimeError: cannot reuse already awaited compiled_coroutine f
```

Same error on WSL / Python 3.6.9 / Nuitka 0.6.7.

**Comment by kayhayen** [comment]
The `libnuitka` is not yet a thing. My suspect, is that the different async implementation of Nuitka present in 2 modules, do not go along well. We need to make sure that we have a re-usable `libnuitka` that only registered compiled types once. Then this use case would work. Until then you have to includ them all in one module.

**Comment by nexcvon** [comment]
Thanks for the reply.

I have found a workaround. Change a.py to:

```
import asyncio

async def _f():
    await asyncio.sleep(5)

def f():
    return asyncio.ensure_future(_f())
```

**Comment by kayhayen** [comment]
The lack of an implementation sharing is still a problem, not sure how to tackle it. Different versions of Nuitka currently need not be compatible with each other, but still would have to recognize their respective compiled times via a shared runtime registry of some sorts. This will of course mostly be needed for module mode, but standalone may of course include modules compiled with Nuitka as well. Their interactivity needs to be there. 

Structurally this is an important issue if we want Nuitka to be used for PyPI packages without problems.

**Comment by KevinRodriguez777** [comment]
This works as expect nowadays
