### ISSUE TITLE
Python3.8: Nested dictionary comprehensions are done wrong

### ISSUE THREAD

**Issue by pokemonchw** [Nuitka/Nuitka#630]
$ python3 -m nuitka --version
0.6.7
Python: 3.8.1 (default, Jan 22 2020, 06:38:00)
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64

The minimum realization:

```
x = {"a":{"b":1},"c":{"d":1}}
y = {n:{z:x[n][z] for z in x[n]} for n in x}
print(y)
```

In cpython, its result is like:

```
{'a': {'b': 1}, 'c': {'d': 1}}
```

But Nuitka is:

```
{'b': {'b': 1}, 'd': {'d': 1}}
```

**Comment by kayhayen** [comment]
Very terrible bug, I am focussing on this with highest priority of course.

**Comment by kayhayen** [comment]
Ok, this appears to be a 3.8 specific bug, with 3.7 it doesn't happen. There changes for dictionary contractions for 3.8, and apparently I messed those up.

Making `x` a function argument, and thus inhibiting compile time optimization didn't help.

**Comment by kayhayen** [comment]
So, using a dictionary contraction side a dictionary contraction is wrong. The code for the updating of a key, value in the built dict was assuming it could use unique temporary variables, which is wrong, and thus corrupts the whole thing.

**Comment by kayhayen** [comment]
This is actually a bug inherited by 3.7 code, where the evaluation order however was more robust against it. The unqiue value temporary variable was done first, and when then the key variable was written during that, it was only later overwritten before being used, so this went unnoticed. 

Effectively, variable usage scopes didn't overlap, but now they do with 3.8 evaluation order.

Before 3.8, evaluation order was `value, dict key`, and now it's `key, value, dict`, where dict is only a reference without side effects, but that was wrong, and Nuitka followed the change, but apparently not in a safe way.

**Comment by kayhayen** [comment]
This is actually a bug inherited by 3.7 code, where the evaluation order however was more robust against it. The unqiue value temporary variable was done first, and when then the key variable was written during that, it was only later overwritten before being used, so this went unnoticed. 

Effectively, variable usage scopes didn't overlap, but now they do with 3.8 evaluation order.

Before 3.8, evaluation order was `value, dict key`, and now it's `key, value, dict`, where dict is only a reference without side effects, but that was wrong, and Nuitka followed the change, but apparently not in a safe way.

**Comment by kayhayen** [comment]
This is part of the current pre-release and will be in 0.6.8

**Comment by kayhayen** [comment]
The release 0.6.8 was just made and contains the correction.
