### ISSUE TITLE
Python3.7: Linker error with Anaconda on Linux

### ISSUE THREAD

**Issue by ajinwu** [Nuitka/Nuitka#632]
nuitka version
```
$ nuitka --version
0.6.7
Python: 3.7.6 (default, Jan  8 2020, 19:59:22) 
Executable: /home/ajin_w/anaconda3/envs/compiler_python/bin/python3.7
OS: Linux
Arch: x86_64
```

my platflam is ubuntu 19.10, not arch

install method: conda install -c conda-forge nuitka

error: I can not compiler the first test example

this is log, I have checked the permissions and can create a file, but I am prompted that the file does not exist
<details>
Nuitka:INFO:PASS 1:
Nuitka:INFO:Initial optimization pass.
Nuitka:INFO:Optimizing module '__main__', 0 more modules to go after that.
Nuitka:INFO:Doing module local optimizations for '__main__'.
Nuitka:INFO:Next global optimization pass.
Nuitka:INFO:Optimizing module '__main__', 0 more modules to go after that.
Nuitka:INFO:Doing module local optimizations for '__main__'.
Nuitka:INFO:PASS 2 ... :
Nuitka:INFO:Next global optimization pass.
Nuitka:INFO:Optimizing module '__main__', 0 more modules to go after that.
Nuitka:INFO:Doing module local optimizations for '__main__'.
Nuitka:INFO:Next global optimization pass.
Nuitka:INFO:Optimizing module '__main__', 0 more modules to go after that.
Nuitka:INFO:Doing module local optimizations for '__main__'.
Nuitka:INFO:Total memory usage before generating C code: 29.66 MB (31100928 bytes):
Nuitka:INFO:Total memory usage before running scons: 29.91 MB (31367168 bytes):
Scons command: /home/username/anaconda3/envs/compiler_python/bin/python -W ignore /home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/inline_copy/bin/scons.py -f /home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/SingleExe.scons --jobs 4 --warn=no-deprecated --no-site-dir --debug=explain name=hello result_name=/home/username/HelloWorld/hello source_dir=. debug_mode=false python_debug=false unstripped_mode=false module_mode=false full_compat=false experimental= trace_mode=false python_version=3.7 target_arch=x86_64 python_prefix=/home/username/anaconda3/envs/compiler_python nuitka_src=/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build nuitka_cache=/home/username/.cache/Nuitka module_count=2 result_exe=/home/username/HelloWorld/hello.bin static_libpython=true uninstalled_python=true show_scons=true abiflags=m
scons: Reading SConscript files ...
Scons: Tools= ['default']
Scons: CC 'gcc' version check:
Scons: CC 'gcc' version check gives '9' from '9'
Scons: Initial CC: gcc
Scons: Initial CCVERSION: 9
Scons: Initial CXX: g++
Scons: Initial CXXVERSION: None
Scons: Picked compiler: gcc
Scons: Picked name: gcc
Scons: Using C11 mode: True
Scons: Compiler used /usr/bin/gcc 
Scons: Detecting arch with : ['objdump', '-f', '/home/username/anaconda3/envs/compiler_python/bin/python']
Scons: Using resource mode: code
Scons: Told to run compilation on 4 CPUs.
Scons: Launching target: ['/home/username/HelloWorld/hello.bin']
scons: done reading SConscript files.
scons: Building targets ...
scons: building `__constants.o' because it doesn't exist
gcc -o __constants.o -c -fvisibility=hidden -std=c11 -fwrapv -ftrack-macro-expansion=0 -fpartial-inlining -fno-lto -fno-var-tracking -O3 -pipe -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/home/username/anaconda3/envs/compiler_python/include/python3.7m -I. -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/include -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/static_src __constants.c
scons: building `__constants_data.o' because it doesn't exist
gcc -o __constants_data.o -c -fvisibility=hidden -std=c11 -fwrapv -ftrack-macro-expansion=0 -fpartial-inlining -fno-lto -fno-var-tracking -O3 -pipe -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/home/username/anaconda3/envs/compiler_python/include/python3.7m -I. -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/include -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/static_src __constants_data.c
scons: building `__helpers.o' because it doesn't exist
gcc -o __helpers.o -c -fvisibility=hidden -std=c11 -fwrapv -ftrack-macro-expansion=0 -fpartial-inlining -fno-lto -fno-var-tracking -O3 -pipe -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/home/username/anaconda3/envs/compiler_python/include/python3.7m -I. -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/include -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/static_src __helpers.c
scons: building `module.__main__.o' because it doesn't exist
gcc -o module.__main__.o -c -fvisibility=hidden -std=c11 -fwrapv -ftrack-macro-expansion=0 -fpartial-inlining -fno-lto -fno-var-tracking -O3 -pipe -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/home/username/anaconda3/envs/compiler_python/include/python3.7m -I. -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/include -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/static_src module.__main__.c
scons: building `static_src/MainProgram.o' because it doesn't exist
gcc -o static_src/MainProgram.o -c -fvisibility=hidden -std=c11 -fwrapv -ftrack-macro-expansion=0 -fpartial-inlining -fno-lto -fno-var-tracking -O3 -pipe -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/home/username/anaconda3/envs/compiler_python/include/python3.7m -I. -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/include -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/static_src static_src/MainProgram.c
scons: building `static_src/CompiledCellType.o' because it doesn't exist
gcc -o static_src/CompiledCellType.o -c -fvisibility=hidden -std=c11 -fwrapv -ftrack-macro-expansion=0 -fpartial-inlining -fno-lto -fno-var-tracking -O3 -pipe -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/home/username/anaconda3/envs/compiler_python/include/python3.7m -I. -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/include -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/static_src static_src/CompiledCellType.c
scons: building `static_src/CompiledFunctionType.o' because it doesn't exist
gcc -o static_src/CompiledFunctionType.o -c -fvisibility=hidden -std=c11 -fwrapv -ftrack-macro-expansion=0 -fpartial-inlining -fno-lto -fno-var-tracking -O3 -pipe -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/home/username/anaconda3/envs/compiler_python/include/python3.7m -I. -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/include -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/static_src static_src/CompiledFunctionType.c
scons: building `static_src/CompiledMethodType.o' because it doesn't exist
gcc -o static_src/CompiledMethodType.o -c -fvisibility=hidden -std=c11 -fwrapv -ftrack-macro-expansion=0 -fpartial-inlining -fno-lto -fno-var-tracking -O3 -pipe -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/home/username/anaconda3/envs/compiler_python/include/python3.7m -I. -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/include -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/static_src static_src/CompiledMethodType.c
scons: building `static_src/CompiledGeneratorType.o' because it doesn't exist
gcc -o static_src/CompiledGeneratorType.o -c -fvisibility=hidden -std=c11 -fwrapv -ftrack-macro-expansion=0 -fpartial-inlining -fno-lto -fno-var-tracking -O3 -pipe -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/home/username/anaconda3/envs/compiler_python/include/python3.7m -I. -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/include -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/static_src static_src/CompiledGeneratorType.c
scons: building `static_src/CompiledCoroutineType.o' because it doesn't exist
gcc -o static_src/CompiledCoroutineType.o -c -fvisibility=hidden -std=c11 -fwrapv -ftrack-macro-expansion=0 -fpartial-inlining -fno-lto -fno-var-tracking -O3 -pipe -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/home/username/anaconda3/envs/compiler_python/include/python3.7m -I. -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/include -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/static_src static_src/CompiledCoroutineType.c
scons: building `static_src/CompiledAsyncgenType.o' because it doesn't exist
gcc -o static_src/CompiledAsyncgenType.o -c -fvisibility=hidden -std=c11 -fwrapv -ftrack-macro-expansion=0 -fpartial-inlining -fno-lto -fno-var-tracking -O3 -pipe -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/home/username/anaconda3/envs/compiler_python/include/python3.7m -I. -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/include -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/static_src static_src/CompiledAsyncgenType.c
scons: building `static_src/CompiledFrameType.o' because it doesn't exist
gcc -o static_src/CompiledFrameType.o -c -fvisibility=hidden -std=c11 -fwrapv -ftrack-macro-expansion=0 -fpartial-inlining -fno-lto -fno-var-tracking -O3 -pipe -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/home/username/anaconda3/envs/compiler_python/include/python3.7m -I. -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/include -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/static_src static_src/CompiledFrameType.c
scons: building `static_src/CompiledCodeHelpers.o' because it doesn't exist
gcc -o static_src/CompiledCodeHelpers.o -c -fvisibility=hidden -std=c11 -fwrapv -ftrack-macro-expansion=0 -fpartial-inlining -fno-lto -fno-var-tracking -O3 -pipe -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/home/username/anaconda3/envs/compiler_python/include/python3.7m -I. -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/include -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/static_src static_src/CompiledCodeHelpers.c
scons: building `static_src/InspectPatcher.o' because it doesn't exist
gcc -o static_src/InspectPatcher.o -c -fvisibility=hidden -std=c11 -fwrapv -ftrack-macro-expansion=0 -fpartial-inlining -fno-lto -fno-var-tracking -O3 -pipe -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/home/username/anaconda3/envs/compiler_python/include/python3.7m -I. -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/include -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/static_src static_src/InspectPatcher.c
scons: building `static_src/MetaPathBasedLoader.o' because it doesn't exist
gcc -o static_src/MetaPathBasedLoader.o -c -fvisibility=hidden -std=c11 -fwrapv -ftrack-macro-expansion=0 -fpartial-inlining -fno-lto -fno-var-tracking -O3 -pipe -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/home/username/anaconda3/envs/compiler_python/include/python3.7m -I. -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/include -I/home/username/anaconda3/envs/compiler_python/lib/python3.7/site-packages/nuitka/build/static_src static_src/MetaPathBasedLoader.c
scons: building `/home/username/HelloWorld/hello.bin' because it doesn't exist
gcc -o /home/username/HelloWorld/hello.bin -fno-lto -z noexecstack -export-dynamic -s -Wl,-R,'/home/username/anaconda3/envs/compiler_python/lib' -Wl,--disable-new-dtags @"./@sources.tmp" -L/home/username/anaconda3/envs/compiler_python/lib -lm /home/username/anaconda3/envs/compiler_python/lib/libpython3.7m.a -ldl -lpthread -lutil -lrt -lm
/usr/bin/ld: /home/username/anaconda3/envs/compiler_python/lib/libpython3.7m.a(main.o): in function `Py_GetArgcArgv':
(.text.unlikely.Py_GetArgcArgv+0x0): multiple definition of `Py_GetArgcArgv'; ./static_src/MainProgram.o:MainProgram.c:(.text+0xc0): first defined here
collect2: error: ld returned 1 exit status
scons: *** [/home/username/HelloWorld/hello.bin] Error 1
scons: building terminated because of errors.

</details>

**Comment by kayhayen** [comment]
Your error is `multiple definition of `Py_GetArgcArgv'` which wasn't seen with Anaconda so far. Apparently the static linking is to blame here, with having a `main.o`that is rather not wanted. It forbids Nuitka to provide these functions.

**Comment by kayhayen** [comment]
The Anaconda suite is not covered by our Github actions, we might want to add it, all other platforms use Anaconda to install the Python version under test, but Linux uses the default of Github actions, which is not Anaconda.

But since we want to recommend Anaconda for its static linking, we better be sure it works and cannot regress. This bug is similar to the one observed with many `pyenv` and other self-compiled variants. It should be a regression of Anaconda to include `main.o`. I am right now installing Anaconda freshly to see if I can reproduce it. 

If I can reproduce it, I am going to add the necessary bits for automatically correcting the `libpython.a` to become usable with Nuitka, so this might actually turn out semi-productive, even if it feels like a waste of time now. For all I know though, Python3.8 has new problems of similar kind with other files.

**Comment by kayhayen** [comment]
Yup, managed to reproduce it. Only Anaconda for Python3 is affected.

**Comment by kayhayen** [comment]
Ok, not using `main.o` doesn't work anymore with 3.7 it seems, due to there being much more code than before, some of which is required. Bad news.

**Comment by kayhayen** [comment]
So there is a simple solution for this, at least with gcc, we can define the symbol as weak. Then it's going to be replaced by another symbol if present. However, that is also going to mean, there is a loss of correctness in these cases. But very few things use `Py_GetArgcArgv` so it's probably not worth the trouble.

**Comment by kayhayen** [comment]
This should work on factory branch now: http://nuitka.net/doc/factory.html

**Comment by lxbrass** [comment]
First of all, **thank you**, this is great project!

Upgrading some code from python 3.6.8 to 3.7.6 produced the same problem. Both python versions built manually, no Anaconda. Linking succeeds with 3.6.8 and fails with 3.7.6 due to duplicated declaration of Py_GetArgcArgv.

Seems to be the same issue.

Will check with the factory branch and report.

**Comment by lxbrass** [comment]
Checked with the factory branch:

Compile/link **succeeds** with nuitka factory branch version 0.6.8rc5, running python 3.7.6 on Linux 

root@Ubuntu64TT:~/projects/product/bin# python3.7 ~/Nuitka-factory/bin/nuitka --version
0.6.8rc5
Python: 3.7.6 (default, Mar  6 2020, 18:53:45) 
Executable: /usr/local/bin/python3.7
OS: Linux
Arch: x86_64

**Comment by kayhayen** [comment]
The release 0.6.8 was just made and contains the correction.
