### ISSUE TITLE
Nuitka 0.6.8rc4 cannot properly load user plugins

### ISSUE THREAD

**Issue by deajan** [Nuitka/Nuitka#633]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

  python -m nuitka --version
```
0.6.8rc4
Python: 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 18 2019, 23:46:00) [MSC v.1916 32 bit (Intel)]
Executable: c:\Python37-32\python.exe
OS: Windows
Arch: x86
```

Installed via pip install -U https://url/to/develop.zip

* If this is a regression (used to work in an earlier version of Nuitka),
  please note what you know about that.

Worked in 0.6.7 ;)

Hello Kay,

I am using @JorjMcKie 's hinted compilation with Nuitka, I stumbled upon a bug which prevents user plugins from loading with latest 0.6.8rc4.

I've updated hinted-mods.py (https://github.com/Nuitka/NUITKA-Utilities/pull/32) according to the changes in nuitka/plugins/Plugins.py where 
`active_plugin_list = []` became `active_plugins = OrderedDict()`.

Nevertheless, it seems that some mods in nuitka/plugins/Plugins.py prevent user plugins from loading.

Here's an output of my test compilation:

```
['C:\\GIT\\MYAPP\\PythonSRC\\hinted-compilation\\nuitka-hints.py', '--standalone', '--recurse-none', '--user-plugin=C:\\GIT\\MYAPP\\PythonSRC\\hinted-compilation\\hinted-mods.py=C:\\GIT\\MYAPP\\PythonSRC\\somesource-37-win32-32.json', '--python-flag=-OO', '--assume-yes-for-downloads', '--output-dir=C:\\GIT\\MYAPP\\SSRC\\Python_BUILD32', 'C:\\GIT\\MYAPP\\PythonSRC\\somesource.py']
NUITKA v0.6.8rc4 on Python 3.7.6 (win32) is compiling 'C:\GIT\MYAPP\PythonSRC\somesource.py' with these options:
 --standalone
 --recurse-none
 --python-flag=-OO
 --assume-yes-for-downloads
 --output-dir=C:\GIT\MYAPP\SSRC\Python_BUILD32

Traceback (most recent call last):
  File "C:\Python37-32\lib\site-packages\nuitka\__main__.py", line 186, in <module>
    main()
  File "C:\Python37-32\lib\site-packages\nuitka\__main__.py", line 138, in main
    activatePlugins()
  File "C:\Python37-32\lib\site-packages\nuitka\plugins\Plugins.py", line 580, in activatePlugins
    loadPlugins()
  File "C:\Python37-32\lib\site-packages\nuitka\plugins\Plugins.py", line 558, in loadPlugins
    loadUserPlugins()
  File "C:\Python37-32\lib\site-packages\nuitka\plugins\Plugins.py", line 523, in loadUserPlugins
    user_plugins[plugin_name] = plugin_class
TypeError: 'OrderedSet' object does not support item assignment
```

I've already tried to fiddle around in nuitka/plugins/Plugins.py by changing `user_pluguns[plugin_name] = plugin_class` to `user_plugins.add(plugin_class)`.

But since the develop branch PluginBase.py file has no `getPluginOptions` function anymore, I ended up being stuck.

**Comment by kayhayen** [comment]
Since I regressed this, I took it on myself to add a plugins test suite and fix this up. Should be working on factory, waiting for CI right now.

**Comment by kayhayen** [comment]
There is a fix for it on factory that appears good, pre-release to follow shortly. I am closing this now, because it was never in a release, and develop will soon be fixed.
