### ISSUE TITLE
Removing non-interface variables from Nuitkas C code

### ISSUE THREAD

**Issue by Make42** [Nuitka/Nuitka#637]
I installed Nuitka via pip into a conda environment on Linux Kubuntu 14.4.

I usually often have a program with different modules, classes etc. which I want to compile with Nuitka and give to other people (e.g. customers) as a module which are not supposed to read my code. Usually this is made difficult, because C to binary compilation removes variable names and only leave addresses. However, to be used in Python as a module Nuitka exposes the variable names and classes etc. to the user. These can be "recovered" by the user using auto-completion, for example in PyCharm, an thus can be used by the user for reverse engineering. I would like Nuitka to not do that, except for the classes/methods/variables etc. that I want to use as the interface.

As an example we could e.g. assume I have the following module

```
import numpy as np
myvar = 24
class MyClass:
  def myfct(x):
    return 42
class MyInterface:
  myprivate_variable = MyClass()
  def dothis(y):
    return myprivate_variable.myfct()
```
and I want only `MyInterface` and  `dothis()` to be usable by the user.

I checked out the C code that Nuitka produces. Is `createModuleCodeObjects` the function that keeps the symbols as plain text? I would like to delete all these plain-text references, except for the ones I would like to use as my interface. How would I accomplish that?

**Comment by kayhayen** [comment]
I think you have no way of realistically achieving this. At some point, I expect to provide methods in the `hints` module, that will allow annotations like you want them, and Nuitka optimization that takes advantage of it, while also enforcing it.

But it's not there yet. Specifically, we are not yet good enough to recognize these kinds of annotations, but if you want to help, you can create a pure Python implementation that would go like this:

`hints.makeModuleVariablesInvisible()`

That would most probably be something that replaces the `sys.modules[__name__]` with an object that overloaded `__getattr__` and gives out nothing, unless informed by other hints.

And then a decorator for the classes `@hints.makeVisible` would tell it to e.g. allow that `sys.modules[__name__]` to hand out that name. Obviously that object would know the real module as an attribute.

For objects and their methods, I believe a similar trick would injecting a `__getattr__` doing checks should be doable.

Depending on your interest, go ahead and implement that, or wait until I do this as part of a commercial offering of Nuitka that allows tighter protection.

**Comment by Make42** [comment]
The solution you propose would just rewrite the Python code in a way, right? Then, if one would be familiar with the principle, couldn't the other person just extract the object that does know all the names and get the names from there?

**Comment by kayhayen** [comment]
This is in the scope of Nuitka commercial and will be implemented there.

**Comment by Make42** [comment]
@kayhayen: Do you have a plan, when this will be available in the commercial plan?
