### ISSUE TITLE
Trying to include external data files using --include-plugin-dir

### ISSUE THREAD

**Issue by RESP3CT88** [Nuitka/Nuitka#641]
I am trying to include a directory ('lib') with my Nuitka standalone. I am using '--include-plugin-dir=lib'. But upon running the executable the program returns errors that the .sed files weren't found. Is my Nuitka command incorrect? How can I include files that are referenced in my Python scripts but not imported directly by Python?

Folder Structure:
```
main.py
lib/
   -- mysedfile.sed
   -- mysedfile2.sed
```

Python Script:
`return shell(['sed', '-nf', 'lib/mysedfile.sed', '/proc/cpuinfo']).split('\n')[0]`

Command:
`python3 -m nuitka --follow-imports --include-plugin-dir=lib --show-progress --standalone main.py`

**Comment by kayhayen** [comment]
No, it will only include python files as compiled modules from that directory. There currently is no such option, you have to manually copy files for now.
