### ISSUE TITLE
[QUESTION] How to enable plugin from user plugin ?

### ISSUE THREAD

**Issue by deajan** [Nuitka/Nuitka#644]
Hello Kay,

Since the new plugin arch in current develop, I am trying to make hinted compilation work again.
So far, in the hinted-mods.py, Jorj activated plugins via

```
from nuitka import Options

options = Options.options
options.plugins_enabled.append("tk-inter")
```

This worked with 0.6.7, but now it indeed puts tk-inter in the options.plugins_enabled list, but using `Options.getPluginsEnabled()` returns an empty list.
I didn't find any hook to enable plugins runtime (ie without using --plugin-enable).
Can you point me to the right direction please ?

Best regards.

**Comment by kayhayen** [comment]
So, the parsing does this, very early in the game:

```
        if arg.startswith(("--enable-plugin=", "--plugin-enable=")):
            addPluginCommandLineOptions(parser=parser, plugin_name=arg[16:])

        if arg.startswith("--user-plugin="):
            addUserPluginCommandLineOptions(parser=parser, filename=arg[14:])
```

This allows the plugin class behind that to add an options group with options. The called function are both small frontend for this function here:
```
def _addPluginCommandLineOptions(parser, plugin_class):
    option_group = OptionGroup(parser, "Plugin %s" % plugin_class.plugin_name)
    plugin_class.addPluginCommandLineOptions(option_group)

    if option_group.option_list:
        parser.add_option_group(option_group)
        plugin_options[plugin_class.plugin_name] = option_group.option_list
```

The dictionary stores the options, and these are later used, to tell the options. Do I reckon correctly, that the parsing is never executed?

In this case, `plugin_options` ought to be a dictionary and filled by `OptionParsing` normally, or by you in the special case of hinted compilation not using a parser at all. 

I can make such a refactoring easily. It seems I broke the decoupling a bit, by remembering the options and forcing them to have values. And you would have to reach in there, and set the option values manually.

**Comment by kayhayen** [comment]
I guess, this should be a release blocking list. I don't want to release with breaking hinted compilation.

**Comment by deajan** [comment]
I am sorry Kay, I have no clue what you're talking about above (I don't understand the Nuitka code well yet).
I just need to enable Nuitka standard plugins from inside the hinted compilation user plugin, which worked with `options.plugins_enabled.append("tk-inter")` before.

I honestly tried to read the code before making this issue, but in the end I'd just ask if you can tell me how I can get that done.

I've fixed most of the hinted compilation for 0.6.8, I think it's the last part that doesn't work.

**Comment by kayhayen** [comment]
So, you need to call `nuitka.plugins.Plugins.activatePlugins()`. This will look into the `options.plugin_enabled` and load things. This is now called after the command line parsing, and you don't do that (yet) I supposed.

When then plugins are created, they can have constructor arguments, which is something very new. You get plugin options that way now. A plugin now is asked prior to creation, and during command line parsing, to provide an options list, from which these values are taken. In your world, I think that is not happening, and instead, I added `nuitka.plugins.Plugins.setPluginOptions` and that will accept a dictionary with the plugin option values, simply as a dict.

Using these 2 functions, your problem should be solved. Can you confirm? The very recent commit on factory is needed for the second function to be present. I would put this on develop, and release, as soon as you got that working and merged.

**Comment by deajan** [comment]
Hello Kay,

I just tried to add activatePlugins() to nuitka-hints.py.
I run into the following issue:

```
C:\GIT\myproject\PythonSRC>c:\Python37-32\python.exe c:\GIT\myproject\PythonSRC\hinted-compilation\nuitka-hints.py local_dev_tests.py
NUITKA v0.6.8rc5 on Python 3.7.6 (win32) is compiling 'local_dev_tests.py' with these options:
 --standalone
 --recurse-none
 --hinted-json-file=local_dev_tests-37-win32-32.json

Nuitka:INFO:'hinted-mods.py' is adding the following options:
Nuitka:INFO:--enable-plugin=multiprocessing
Nuitka:INFO:--recurse-to=types and 23 more modules
Nuitka:INFO:
Traceback (most recent call last):
  File "c:\Python37-32\lib\site-packages\nuitka\__main__.py", line 186, in <module>
    main()
  File "c:\Python37-32\lib\site-packages\nuitka\__main__.py", line 138, in main
    activatePlugins()
  File "c:\Python37-32\lib\site-packages\nuitka\plugins\Plugins.py", line 602, in activatePlugins
    _addActivePlugin(plugin_class, args=True)
  File "c:\Python37-32\lib\site-packages\nuitka\plugins\Plugins.py", line 66, in _addActivePlugin
    plugin_instance = plugin_class(**plugin_args)
  File "c:\GIT\myproject\PythonSRC\hinted-compilation\hinted-mods.py", line 313, in __init__
    activatePlugins()
  File "c:\Python37-32\lib\site-packages\nuitka\plugins\Plugins.py", line 593, in activatePlugins
    _addActivePlugin(plugin_class)
  File "c:\Python37-32\lib\site-packages\nuitka\plugins\Plugins.py", line 59, in _addActivePlugin
    assert plugin_name not in active_plugins.keys(), plugin_name
AssertionError: data-files
```

I used the latest nuitka-hints.py code from Nuitka utilities, where the sole modification I did was adding a call to `activatePlugins()` at the end of the `__init__` function of class `HintedModsPlugin`.

I then tried to compile the following:
```
import multiprocessing

print('Hello multiprocessed world')
```

**Comment by deajan** [comment]
Ahem... anyone ?

**Comment by kayhayen** [comment]
This is still on my mind, sorry for the delay. My main problem is that I have zero experience with using hinted compilation, and believe, I need to try it, otherwise I won't understand. Can you provide me with a branch of yours to try out, and maybe stupid guy level instructions @deajan ?

**Comment by deajan** [comment]
Here are some basic instructions to get it to work.
Let's say you have `test.py` containing the following:

```
import sys
import tkinter as tk
from tkinter import ttk
from tkinter.messagebox import showinfo

def popup_showinfo():
    showinfo("Window", "Hello World!")
    sys.exit()

class Application(ttk.Frame):

    def __init__(self, master):
        ttk.Frame.__init__(self, master)
        self.pack()
        self.button_showinfo = ttk.Button(self, text="Show Info", command=popup_showinfo)
        self.button_showinfo.pack()

root = tk.Tk()

app = Application(root)

root.mainloop()
```

I choose a tk app because it should trigger the Nuitka tk-inter plugin.
Next, get the files from https://github.com/Nuitka/NUITKA-Utilities/tree/master/hinted-compilation

`get-hints.py` analyses all the import calls from the app and writes `local_dev_tests-37-win32-32.json` or `local_dev_tests-37-win32-64.json` depending on your python architecture.
To run the analyzer:
```
get-hints.py test.py
```

Once this is done, we can use `nuitka-hints.py` to compile, which will remove any modules which haven't been called, and activate plugins depending on the modules. In our case, it should activate the tk-inter plugin.

To compile
```
nuitka-hints.py test.py
```

The nuitka-hints.py script basically launches nuitka with `--user-plugin=hinted-mods.py --hinted-json-file=[the file generated by get-hints.py]`

Now `hinted-mods.py` reads the json file, and tries to enable plugins if needed.
In our case, it tries to activate tk-inter plugin in line 247:
`options.plugins_enabled.append("tk-inter")`

I've tried to replace that call with `nuitka.plugins.Plugins.activatePlugins()`, giving the error above.

Is this sufficient ?

**Comment by kayhayen** [comment]
This is next on my list, making a pre-release now, but then I will try to solve this before release as one the last actions.

**Comment by kayhayen** [comment]
So, this didn't crash, but is funny talking:

/c/Python37/python ../NUITKA-Utilities/hinted-compilation/nuitka-hints.py MiniHinted.py
NUITKA v0.6.8rc on Python 3.7.3 (win32) is compiling 'MiniHinted.py' with these options:
 --standalone
 --recurse-none
 --hinted-json-file=MiniHinted-37-win32-64.json

> Nuitka:INFO:'hinted-mods' is adding the following options:
> Nuitka:INFO:--enable-plugin=tk-inter
> Nuitka:INFO:--recurse-to=tkinter.messagebox and 7 more modules
> Nuitka:INFO:
> Nuitka-Plugins:WARNING: Use '--plugin-enable=tk-inter' for: Tkinter needs TCL included.
> Nuitka:INFO:drop types
> Nuitka:INFO:drop site
> Nuitka:WARNING: Not recursing to unused 'enum'.
> Nuitka:WARNING: Not recursing to unused 're'.
> Nuitka:WARNING: Not recursing to unused 'tkinter.commondialog'.
> Nuitka:WARNING: Not recursing to unused 'tkinter.constants'.
> Nuitka:INFO:Compiled 'MiniHinted.py' in 38 seconds.

I guess, it should be criticized, that the hinted compilation uses the logging output, that would make it appear to be Nuitka output. I believe the "drop" output is not from Nuitka, the last one might be, and would indicate that the hinted compilation asks to enter modules, that Nuitka finds not needed, which would be strange.

**Comment by kayhayen** [comment]
Ok, now I realize, it's because it's a plugin, and I am changing it to use plugin level tracing only.

**Comment by kayhayen** [comment]
So, the release fixes this, I think. However plugins in Nuitka do similar checks and fail now. I intend to fix that separately.
