### ISSUE TITLE
WinError 110 when compiling with PythonOCC

### ISSUE THREAD

**Issue by Brently-Mills** [Nuitka/Nuitka#647]
Hello,

Using Nuitka 0.6.7 installed from the .msi installer from the Nuitka web site, with Anaconda 3 Python version 3.6.5 on a windows 10 computer.
I have a project that uses PythonOCC (version 7.4.0). I am able to compile other applications that do not use PythonOCC with Nuitka but if I include PythonOCC I always get the WinError 110. 

Example (please find core_helloworld.py example here https://github.com/tpaviot/pythonocc-demos/blob/master/examples/core_helloworld.py):

C:\Anaconda3\Scripts\nuitka.exe --standalone C:\Temp\nuitka_test\core_helloworld.py --include-package=OCC --plugin-enable=qt-plugins --force-dll-dependency-cache-update --mingw64

Nuitka:INFO:Injecting plug-in based pre load code for module 'PyQt5':
Nuitka:INFO:    Adding dist folder to 'PATH' environment variable.
Nuitka:INFO:Injecting plug-in based post load code for module 'PyQt5.QtCore':
Nuitka:INFO:    Setting Qt library path to distribution folder. Need to avoid loading target
Nuitka:INFO:    system Qt plug-ins, which may be from another Qt version.
Nuitka:WARNING:Use '--plugin-enable=numpy' for: numpy support.
Nuitka:WARNING:Use '--plugin-enable=pylint-warnings' for: Understand PyLint/PyDev annotations for warnings.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\PIL\Image.py:408' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\cffi\verifier.py:151' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\cloudpickle\cloudpickle.py:908' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\cloudpickle\cloudpickle.py:944' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\cloudpickle\cloudpickle.py:1100' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\flask\cli.py:235' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\flask\helpers.py:742' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\flask\helpers.py:811' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\ipykernel\pickleutil.py:223' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\ipython_genutils\importstring.py:31' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\ipython_genutils\importstring.py:39' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\jedi\evaluate\compiled\access.py:150' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\jinja2\loaders.py:472' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\jinja2\utils.py:142' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\jinja2\utils.py:143' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\matplotlib\backend_managers.py:351' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\matplotlib\backends\__init__.py:61' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\numpy\lib\function_base.py:4555' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\numpy\lib\utils.py:373' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\numpy\lib\utils.py:868' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\numpy\lib\utils.py:926' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\py\_vendored_packages\apipkg.py:69' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\pygments\formatters\__init__.py:39' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\pygments\lexers\__init__.py:41' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\pygments\styles\__init__.py:64' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\requests\packages.py:7' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\sphinx\ext\autodoc\importer.py:140' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\sphinx\highlighting.py:76' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\sphinx\registry.py:315' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\sphinx\search\__init__.py:277' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\sphinx\util\__init__.py:254' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\sphinx\util\__init__.py:291' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\sphinx\util\__init__.py:543' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\sphinxcontrib\websupport\core.py:104' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\sqlalchemy\dialects\__init__.py:43' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\sqlalchemy\dialects\mysql\mysqldb.py:167' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\sqlalchemy\sql\type_api.py:569' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\sqlalchemy\testing\engines.py:154' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\tornado\util.py:178' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\tornado\util.py:181' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\traitlets\utils\importstring.py:34' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\traitlets\utils\importstring.py:42' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\werkzeug\__init__.py:116' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\werkzeug\__init__.py:121' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\werkzeug\utils.py:418' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\werkzeug\utils.py:427' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\win32com\client\gencache.py:236' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\win32com\client\gencache.py:627' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\win32com\client\makepy.py:320' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\win_unicode_console\runner.py:128' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\zmq\backend\select.py:26' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\zmq\eventloop\minitornado\util.py:59' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\zmq\eventloop\minitornado\util.py:62' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\lib\site-packages\zmq\utils\jsonapi.py:25' may require use of '--include-plugin-directory' or '--include-plugin-files'.

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\nuitka\__main__.py", line 182, in <module>
    main()
  File "C:\Anaconda3\lib\site-packages\nuitka\__main__.py", line 175, in main
    MainControl.main()
  File "C:\Anaconda3\lib\site-packages\nuitka\MainControl.py", line 758, in main
    executePostProcessing(OutputDirectories.getResultFullpath())
  File "C:\Anaconda3\lib\site-packages\nuitka\PostProcessing.py", line 68, in executePostProcessing
    lang_id=0,
  File "C:\Anaconda3\lib\site-packages\nuitka\utils\WindowsResources.py", line 259, in addResourceToFile
    _closeFileWindowsResources(update_handle)
  File "C:\Anaconda3\lib\site-packages\nuitka\utils\WindowsResources.py", line 165, in _closeFileWindowsResources
    raise ctypes.WinError()
OSError: [WinError 110] The system cannot open the device or file specified.

I did try the latest beta version of Nuitka (0.6.8rc5) but it crashes on --plugin-enable=qt-plugins, so I revered back to 0.6.7.

A little backstory: I recently upgraded our PythonOCC based project from Python 2.7 to Python 3.6.5 as well as the latest version of PythonOCC. In the past I have been successful compiling this project using Nuitka 0.6.5 for Python 2.7.  

Any advice on how to tackle this issue is very much appreciated.

Thank you,
Brent

**Comment by Brently-Mills** [comment]
Update. A resolution could not be found for this issue. I suspect it is isolated to the computers I use at work -- although it is odd that I can still compile the Python 2.7 version of our PythonOCC application with Nuitka v 0.6.5.

If anybody has any insight or ideas as to the cause I would love to here them.
Thank you,
Brent

**Comment by kayhayen** [comment]
These are virus tools blocking the access, Nuitka has gained a retry mechanism, so this now is assumed to be good.
