### ISSUE TITLE
Question: Including data files or non python files in standalone build

### ISSUE THREAD

**Issue by Alex-Mann** [Nuitka/Nuitka#649]
I'm wondering how to include some data files / configuration files in a cli tool that I am building. I saw on the documentation that this likely might not be supported? Maybe someone can provide some clarification.

I'm looking to include a couple CSVs and a few YAML files within the cli tool. What I have tried so far is this command to compile it:
```
python3 -m nuitka --standalone --follow-imports programmer/cli.py --include-plugin-files="programmer/**/*.yaml,programmer/**/*.csv"
```

No errors or warnings during compilation. But when I run I get the following issue:
```
Traceback (most recent call last):
  File "/Users/amann/Work/git/mss_programmer/./cli.dist/importlib/resources.py", line 97, in open_binary
FileNotFoundError: [Errno 2] No such file or directory: '/Users/amann/Work/git/mss_programmer/cli.dist/programmer/configurator/rate.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/amann/Work/git/mss_programmer/./cli.dist/cli.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/amann/Work/git/mss_programmer/./cli.dist/programmer/configurator/configurator.py", line 11, in <module programmer.configurator.configurator>
  File "/Users/amann/Work/git/mss_programmer/./cli.dist/programmer/utils/path_helper.py", line 6, in get_file_path
  File "/Users/amann/Work/git/mss_programmer/./cli.dist/contextlib.py", line 112, in __enter__
  File "/Users/amann/Work/git/mss_programmer/./cli.dist/importlib/resources.py", line 201, in path
  File "/Users/amann/Work/git/mss_programmer/./cli.dist/importlib/resources.py", line 111, in open_binary
FileNotFoundError: 'rate.csv' resource not found in 'programmer.configurator'
```

So clearly the files are not getting bundled in. If someone could provide some guidance that would be great. Thanks.

**Comment by JorjMcKie** [comment]
This type of thing is normally handled by the Nuitka standard plugin ``DataFileCollectorPlugin.py``, which can do this automatically when triggered by the encounter of some module.

1. As long as your module is not covered you can certainly manually copy over the respective files to the ``dist`` folder.
2. You can as well write a Nuitka user plugin for your module, which does exactly this task.
3. Yet another option is turn gears and convert your data to Python files. Which obviously would get you covered automatically.

Maybe a balanced approach is point number 2: once your module approaches maturity, that code can easily be incorporated in the standard plugin.

**Comment by Alex-Mann** [comment]
Can you point me to some resources on the `DataFileCollectorPlugin.py` and then also writing/how user plugins are constructed?

I have thought about the conversion to a python file, but the CSV file is actually used for maintainability/readability, so an additional build step would have to be performed somewhere before compile to convert that CSV into a python file. Then I suppose using an environment variable like `IS_DEV` could default to using the csv/other datafiles, and compiled bins could use the transformed version of the files...

**Comment by JorjMcKie** [comment]
If you look into the source of `DataFileCollectorPlugin.py`, you will see several situations covered when "known" modules are encountered. Like (1) single files, (2) one or more sub folders, (3) generated files are copied to `yourscript.dist`.
From what I see in your error log, your module will fall in category (2).

For the time being, you could write a simple plugin which only does something at the end of successful standalone compilation:

```python
import os
import sys
import shutil
from logging import info

from nuitka.plugins.PluginBase import NuitkaPluginBase


class MyPlugin(NuitkaPluginBase):

    plugin_name = __file__

    def onStandaloneDistributionFinished(self, dist_dir):
        """Will be called at end of successful compilation.
        dist_dir is the folder name 'yourscript.dist'.
        Now copy your data file folders to the right dist
        subfolders using e.g. the shutil module.
        """
        return None

```

If you name this module `myplugin.py`, your command line would look like this:

`python -m nuitka --standalone --user-plugin=myplugin.py myscript.py`

**Comment by kayhayen** [comment]
This is answered it seems.
