### ISSUE TITLE
Some Code can see in RCDATA standalone file  

### ISSUE THREAD

**Issue by BlackRouter** [Nuitka/Nuitka#651]
```
Nuitka Version 0.6.7
Python 3.8.2
Windows
Mingw64
```

I compile a example code with nutika + Mingw compiler after check with [DIE ](http://ntinfo.biz/index.html) tools dump RCData and some python code return :(

i think compiled file can patch on memory and return to python code .

https://imgur.com/I9bUwiv
https://imgur.com/jHejFxd

**Comment by kayhayen** [comment]
I am not sure what you are trying to say. The non-commercial Nuitka will not obfuscucate right now, and e.g. use proper function names and variable names in call stack. That is to be expected and well known.

There is no code there however, except the standard library in bytecode form.
