### ISSUE TITLE
Portable binary with musl

### ISSUE THREAD

**Issue by anki-code** [Nuitka/Nuitka#652]
Hello! Thank you for Nuitka!

Could you please advice what is the best way to make standalone binary with portable musl wich will work portable on Ubuntu and Alpine? I tried and looks like close to success.

Here is the example and additional questions below:

1. I build the [xxh project](https://github.com/xxh/xxh) (it hasn't any complex libs) with Nuitka:
```
docker run --rm -it -v `pwd`:/host alpine sh
apk add --update musl-dev gcc python3-dev py3-pip chrpath git
pip3 install -U "https://github.com/Nuitka/Nuitka/archive/factory.zip"
pip3 install pexpect pyyaml
git clone --depth 1 https://github.com/xxh/xxh
cd xxh
nuitka3 --python-flag=no_site --python-flag=no_warnings \
        --show-progress --standalone --follow-imports xxh
```
2. After it I have `xxh.dist` with `ldd xxh` on Alpine:
```
/lib/ld-musl-x86_64.so.1 (0x7f58f86fb000)
libpython3.8.so.1.0 => ./libpython3.8.so.1.0 (0x7f58f7a96000)
libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f58f86fb000)
```
The app works perfect on Alpine.

3. Then I move it to Ubuntu and I've got `ldd xxh`:
```
linux-vdso.so.1 (0x00007ffeeedd9000)
libpython3.8.so.1.0 => /home/pc/xxh/xxh/xxh.dist/./libpython3.8.so.1.0 (0x00007efd2813c000)
libc.musl-x86_64.so.1 => not found
libc.musl-x86_64.so.1 => not found
```

4. When I copy `libc.musl-x86_64.so.1` from Alpine to `xxh.dist` 
I've got `ldd xxh` **on Ubuntu**:
```
linux-vdso.so.1 (0x00007ffce37ac000)
libpython3.8.so.1.0 => /home/pc/xxh/xxh/xxh.dist/./libpython3.8.so.1.0 (0x00007fbbf0df5000)
libc.musl-x86_64.so.1 => /home/pc/xxh/xxh/xxh.dist/./libc.musl-x86_64.so.1 (0x00007fbbf0d5f000)
```

5. Looks good, but not working:
```
ubuntu$ ./xxh
bash: ./xxh: No such file or directory
```

6. And only if I copy `musl` to `/lib` on Ubuntu I have **success**:
```
$ sudo cp libc.musl-x86_64.so.1 /lib/ld-musl-x86_64.so.1
$ ./xxh -V
0.6.0
```

7. If I open `xxh` binary in vim I see absolute path `/lib/ld-musl-x86_64.so.1` and it looks like the cause why I should copy the musl to system lib directory.

A. Please advice what I can do to make musl portable with the app?
B. Is there a way to statically compile musl inside the app?
C. Is there a way to make one big static binary `xxh` file?

Musl is small and some projects use it instead of libc for creating static standalone apps. It will be great if Nuitka can do the same.

Many thanks to your work!

**Comment by kayhayen** [comment]
The glibc cannot be included, simply because it fails to work with older kernels. We therefore have code that specifically inhibits it.

I am not versed with muslc at all. Does it not have the same issue. Are you saying that there is a portable version of muslc and there is a trick to use it? Nuitka surely could change how to links and statically link that. Just let me know which flags you need to add for that to gcc and ld. You can export `CCFLAGS=` and `LDFLAGS=` and Nuitka will include it for your experimentation.

**Comment by anki-code** [comment]
> Nuitka surely could change how to links and statically link that. Just let me know which flags you need to add for that to gcc and ld. You can export CCFLAGS= and LDFLAGS= and Nuitka will include it for your experimentation.

Hello @romkatv! Could your experience of building [zsh-bin](https://github.com/romkatv/zsh-bin/) with static musl be applied here?

**Comment by romkatv** [comment]
You need to enable static linking. If you are using gcc, try `LDFLAGS=-static`.

**Comment by anki-code** [comment]
Next steps. I've built static python as [described in wiki](https://wiki.python.org/moin/BuildStatically) and got `libpython3.8.a`. Next I tried to static build with `LDFLAGS`:
```
export LDFLAGS="-static -l:libpython3.8.a"
nuitka3 --python-flag=no_site --python-flag=no_warnings --show-progress \
        --standalone --follow-imports xxh
```
After this I've got `xxh.dist` with `ldd xxh`:
```
/lib/ld-musl-x86_64.so.1 (0x7f890d65e000)
```
It's better than before! 

But 
1. When I tried to run `./xxh` I've got:
```
Traceback (most recent call last):
  File "/xxh/xxh.dist/xxh", line 5, in <module>
  File "/xxh/xxh.dist/xxh_xxh/xxh.py", line 1, in <module xxh_xxh.xxh>
  File "/xxh/xxh.dist/yaml/__init__.py", line 8, in <module yaml>
  File "/xxh/xxh.dist/yaml/loader.py", line 8, in <module yaml.loader>
  File "/xxh/xxh.dist/yaml/constructor.py", line 14, in <module yaml.constructor>
  File "/xxh/xxh.dist/datetime.py", line 8, in <module>
ImportError: Dynamic loading not supported
```
2. The musl still not statically linked.

Any thoughts are welcome.

**Comment by anki-code** [comment]
I've edited my previous message. Statically linking was success!

@kayhayen could you please take a look on python traceback and my nuitka arguments?

**Comment by anki-code** [comment]
I've got success! 

```
  File "/xxh/xxh.dist/yaml/constructor.py", line 14, in <module yaml.constructor>
  File "/xxh/xxh.dist/datetime.py", line 8, in <module>
```
This error means that on line 8 in Python standard `datetime.py` file there is an import of module which not included to Python static while building.

To fix this:
1. Find `datetime.py` (`/usr/lib/python3.8/datetime.py` on Alpine) and get the module name from line 8 (it's `math` module)
2. Open `Python3.8.2/Modules/Setup`, search the module and uncomment:
```
math mathmodule.c _math.c
```
3. Rebuild static Python and copy to `/usr/lib`:
```
./configure LDFLAGS="-static" --disable-shared
make LDFLAGS="-static" LINKFORSHARED=" "
cp libpython3.8.a /usr/lib
```
4. Now try to rebuild app with Nuitka:
```
export LDFLAGS="-static -l:libpython3.8.a"
nuitka3 --python-flag=no_site --python-flag=no_warnings --show-progress \
        --standalone --follow-imports xxh
```
5. If you faced with error go to step 1 and repeat until getting all required modules to static Python
6. If you have success you've got the static linked binary of your app which portable on Alpine, Ubuntu, Arch, CentOS (I've tested):
```
alpine# ldd xxh.dist/xxh
/lib/ld-musl-x86_64.so.1 (0x7f890d65e000)
ubuntu# ldd xxh.dist/xxh
statically linked
```
