### ISSUE TITLE
compiling h2o project with Nuitka

### ISSUE THREAD

**Issue by valeita** [Nuitka/Nuitka#654]
Hi,

i open this issue because i have problems to compile an H2O project with Nuitka.
https://www.h2o.ai/
H2O is a framework to do machine learning and artificial intelligence model. It works in a simply mode, after installing H2O in python env, we need to write 2 rows to use it:

```
import h2o
h2o.init(ip="localhost", port=54321, max_mem_size="8G", nthreads=-1)
```

With the second line, a cluster H2O is started, or if already started, it connect to him. The cluster (1 node in local pc) is the central element that permit to prepare data and build models. how? there's a jar file that is used (h2o.jar) that is searched in a python path.

Now, i tried in several ways to build a test project with this 2 lines. Here the code:

```
import h2o

def talk(message):
    return "Talk " + message

def main():
    print( talk("Hello World"))

if __name__ == "__main__":
    h2o.init(ip="localhost", port=54321, max_mem_size="8G", nthreads=-1)
    main()
```

When i finish to compile, and tried to start my executable, the h2o.jar file that is used to start the cluster, is not included. I tried to manually create the folder and moved this file in the path when it's searched, but then the problem is about the H2O version of jar file that mismatch. While the H2O.jar is version 3.28.0.3 (in python env first build), in the compiled project, the version that is registered is 0.0.local.
Someone had experience with this problem?
I tried command line like --include-package=h2o
-- follow-imports
--follow-imports --recurse-all
-- include plugin-directory

Follow now my step that i did, to reproduce the problem:

python version:
Python 3.6.9

I created a virtualenv:
virtualenv -p /usr/bin/python3 nuitka-venv

pip install h2o
pip install pandas
pip install -U nuitka

Now, opening a python shell, this 2 lines works

```
import h2o
h2o.init(ip="localhost", port=54321, max_mem_size="8G", nthreads=-1)
```

but when inserted in hello.py and compiled, something of h2o is not included in the compiled version.
Other info:
python -m nuitka --version
0.6.7
Python 3.6.9
Executable /home/valerio/Scrivania/test/nuitka-venv/bin/python
OS: Linux
Arch: x86_64

My ubuntu is 18.04.4 LTS

any kind of help is appreciated, thanks!

**Comment by kayhayen** [comment]
I think this is a effect of the known issue, that we do not include these version information files that pip puts into the file system. There is an issue where the plan is to collect basically the version information of all, and then to include it readily for query at run time.

Until then, you will have to work around this by modifying said code, filenames, etc.

**Comment by kayhayen** [comment]
The version stuff it seems no longer is an issue, and @KevinRodriguez777 produced a data files config that makes it work out of the box now. I added it with crediting to him.

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
Part of the 2.0.3 hotfix that I just made.
