### ISSUE TITLE
win32service.pyd not found 

### ISSUE THREAD

**Issue by BlackRouter** [Nuitka/Nuitka#657]
**0.6.7
Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)]
Executable: C:\Users\Javad\AppData\Local\Programs\Python\Python38-32\python.exe
OS: Windows
Arch: x86**

after compile via this options: 
```
nuitka main.py --show-progress --recurse-all --standalone --enable-plugin=qt-plugins=sensible,styles --mingw64 --disable-dll-dependency-cache --experimenta
l=use_pefile
```

all things ok and file win32service.pyd included after compile but show error:

> ImportError: LoadLibraryEx failed: The specified module could not be found ( Module pywin32 )

![2020-03-23_173636](https://user-images.githubusercontent.com/15177510/77320028-76a98b00-6d2d-11ea-8722-117c5bc7ff50.jpg)
![2020-03-23_173646](https://user-images.githubusercontent.com/15177510/77320038-7a3d1200-6d2d-11ea-98f6-4addcd8d6769.jpg)

**Comment by kayhayen** [comment]
The pefile dependency walker might not be good enough, please retry with latest stable and not using it.

**Comment by BlackRouter** [comment]
> The pefile dependency walker might not be good enough, please retry with latest stable and not using it.

ok try it and send result

**Comment by kayhayen** [comment]
Closing for lack of feedback.
