### ISSUE TITLE
Compiling exe with nuitka: issue with the copyDataFiles function

### ISSUE THREAD

**Issue by cvpython** [Nuitka/Nuitka#658]
Hello all,

I had some trouble compiling my code with nuitka by means of the command `python.exe nuitka-hints.py script.py`.

The code notably uses gdal, pyqt5 and vtk.

Here is the error raised:

> Nuitka:INFO:Copying Qt plug-ins 'iconengines,imageformats,mediaservice,platforms,printsupport' to 'IHM_SLAM_S.dist\PyQt5\qt-plugins'.
> Nuitka:INFO:Copying OpenSSL DLLs to 'IHM_SLAM_S.dist'
> Nuitka:INFO:Copied 'matplotlib/mpl-data'.
> Nuitka:INFO:Copied 35 files from 'numpy' installation.
> Nuitka:WARNING:No files or folders found for 'osgeo' in subfolder(s) 'data'.
> Traceback (most recent call last):
>   File "D:\Programme\Anaconda3\envs\IHM\lib\site-packages\nuitka\__main__.py", line 182, in <module>
>     main()
>   File "D:\Programme\Anaconda3\envs\IHM\lib\site-packages\nuitka\__main__.py", line 175, in main
>     MainControl.main()
>   File "D:\Programme\Anaconda3\envs\IHM\lib\site-packages\nuitka\MainControl.py", line 782, in main
>     copyDataFiles(dist_dir=dist_dir, data_files=data_files)
>   File "D:\Programme\Anaconda3\envs\IHM\lib\site-packages\nuitka\freezer\Standalone.py", line 1555, in copyDataFiles
>     for source_desc, target_filename in data_files:
> ValueError: not enough values to unpack (expected 2, got 0)

To _hack_ the problem, I had to add the condition `if len(data_files[0]):` before the line 1555 in the file nuitka\freezer\Standalone.py (and to indent all the lines after this condition).
This is clearly not a nice hack but it works for my case.  

Here is the result of `python -m nuitka --version`:

> 0.6.7
> Python: 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:22:21) [MSC v.1916 64 bit (AMD64)]
> Executable: D:\Programme\Anaconda3\envs\IHM\python.exe
> OS: Windows
> Arch: x86_64

Hope it helps nuitka developers.

**Comment by kayhayen** [comment]
This is stable version of the code, I believe develop is already better, which you were recommended to try out.

**Comment by cvpython** [comment]
Thank you @kayhayen for your reply.

I indeed had no problem compiling with the develop branch ... but the exe does not work.
Here is the error:

> Traceback (most recent call last):
>   File "C:\PROGRA~1\ECL_AIR\IHM_SLAM_S_PY3\IHM_SLAM_S.dist\IHM_SLAM_S.py", line 22, in <module>
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "C:\PROGRA~1\ECL_AIR\IHM_SLAM_S_PY3\IHM_SLAM_S.dist\SRC\sDon.py", line 14, in <module SRC.sDon>
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "C:\PROGRA~1\ECL_AIR\IHM_SLAM_S_PY3\IHM_SLAM_S.dist\SRC\sRunClass.py", line 11, in <module SRC.sRunClass>
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "C:\PROGRA~1\ECL_AIR\IHM_SLAM_S_PY3\IHM_SLAM_S.dist\numpy\__init__.py", line 152, in <module numpy>
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "C:\PROGRA~1\ECL_AIR\IHM_SLAM_S_PY3\IHM_SLAM_S.dist\numpy\random\__init__.py", line 181, in <module numpy.random>
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "C:\PROGRA~1\ECL_AIR\IHM_SLAM_S_PY3\IHM_SLAM_S.dist\numpy\random\_pickle.py", line 1, in <module numpy.random._pickle>
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "_bit_generator.pxd", line 14, in init numpy.random.mtrand
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "_bit_generator.pyx", line 1, in init numpy.random._bit_generator
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "_bit_generator.pxd", line 14, in init numpy.random._common
> AttributeError: module 'numpy.random._bit_generator' has no attribute 'BitGenerator'
>
