### ISSUE TITLE
binary_directory in getBinaryDirectoryHostEncoded() lacks an implementation for OpenBSD

### ISSUE THREAD

**Issue by juanfra684** [Nuitka/Nuitka#662]
Hi, I'm working on an OpenBSD package for Nuitka. It builds fine but the standalone binaries generated abort in `getBinaryDirectoryWideChars`. Looks like ` binary_directory` in `getBinaryDirectoryHostEncoded()` (`build/static_src/CompiledCodeHelpers.c`) lacks an implementation for OpenBSD.

```plain
$ python3.7 -m nuitka --version
0.6.7
Python: 3.7.7 (default, Mar 30 2020, 15:25:59) 
Executable: /usr/local/bin/python3.7
OS: OpenBSD
Arch: amd64
```

**Comment by kayhayen** [comment]
Hello,

can you check if the factory branch works better for you. I do not have access to an openBSD machine, but this should be better and I willing to work on it.

https://nuitka.net/doc/factory.html

Yours,
Kay

**Comment by juanfra684** [comment]
Thanks for the quick reply. I checked your recent changes in `CompiledCodeHelpers.c`, unfortunately that's not going to work on OpenBSD. It doesn't have `KERN_PROC_PATHNAME`.

**Comment by juanfra684** [comment]
I asked in our internal chat and Robert Nagy gave me this code. http://ix.io/2gZF

**Comment by kayhayen** [comment]
Excuse me for arguing with the demo program. 

I am not convinced that `argv[0] is the path to the binary in all cases, it depends on how it's forked and could be an arbitrary value. Therefore the Chromium patch is very much based on that kind of luck to work. My guess that `KERN_PROC_PATHNAME` is apparently untrue.

Also tokens need not be an array, only a `char *` is return by `strtok` and only element 0 is used. The split to `:` is confusing to me, maybe uses an implementation detail. Makes me wonder of course, what happens with paths that contain that character.

Also the scan for open files, seems to only do that the split to `:` value is returned only if a main program file is found. I guess, it's missing a match there. It would make sense to check if it's the same file I guess, but that part is not done. A program not having the program text open is probably unlikely, so this doesn't contribute to reliability, does it, and requiring it is not a help I think, if it's not used to check. So I would leave that out, or see it enhanced to make a check that compares the name or content derived from `argv[0]` and that file, and error out if they mismatch.

I don't think there is a way to get the filename names from a file handle, is there?

Also I guess, I need to setup a VM. Due to my switch to WSL I don't have the KVM to run OpenBSD easily now. But I got a machine with Hyper-V where I can do it maybe, but that will take time.

I will try and incorporate the code given without checks, it's probably the best thing possible, but allow some time for that. I still want to see if there is an easy way to test for me.

**Comment by juanfra684** [comment]
Unfortunately, I can't help you with the C code. That's why I asked for alternatives to FreeBSD KERN_PROC_PATHNAME, so you can adapt the code to your needs. From time to time appears a package which requires something equivalent but OpenBSD doesn't implement KERN_PROC_PATHNAME because it makes assumptions which are not always true (not my words).

If you need machines with different OS and architectures, ask for an account in the [GCC Compile Farm](https://cfarm.tetaneutral.net/users/new/). They accept users from non GNU projects.

**Comment by kayhayen** [comment]
The code that was on factory, turned out to be useless. I will attempt a solution, once I got VMs back under control. Compile farm is all nice, but I prefer more control.

**Comment by kayhayen** [comment]
I do have the VM setup now, and I am going to install OpenBSD just to do a quick check, but it's not going to be fast. The code may still not work, let me know if you have any new knowledge here.

**Comment by kayhayen** [comment]
I am installing a VM with OpenBSD just now, lets see how it goes.

**Comment by kayhayen** [comment]
My VM installation is not forthcoming, if nobody is going to step up, I am going to close the issue at 2.3 release time, this should be tested by somebody with OpenBSD.

**Comment by SuperDisk** [comment]
I'm still getting an error regarding KERN_PROC_PATHNAME:

```
(cool-venv2) nickfaro$ python -m nuitka --follow-imports pygmentize_launcher.py
Nuitka-Options: Used command line options: --follow-imports pygmentize_launcher.py
Nuitka-Options: Detected static libpython to exist, consider '--static-libpython=yes' for better performance,
Nuitka-Options: but errors may happen.
Nuitka: Starting Python compilation with Nuitka '2.2.3' on Python '3.10' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: clang (clang 16.0.6).
In file included from static_src/CompiledFunctionType.c:3108:
In file included from /home/npfaro/pygment-stuff/cool-venv2/lib/python3.10/site-packages/nuitka/build/static_src/CompiledCodeHelpers.c:56:
/home/npfaro/pygment-stuff/cool-venv2/lib/python3.10/site-packages/nuitka/build/static_src/HelpersFilesystemPaths.c:59:14: error: use of undeclared identifier 'KERN_PROC_PATHNAME'
    mib[2] = KERN_PROC_PATHNAME;               
             ^                                 
/home/npfaro/pygment-stuff/cool-venv2/lib/python3.10/site-packages/nuitka/build/static_src/HelpersFilesystemPaths.c:197:10: fatal error: 'sys/sendfile.h' file not found
#include <sys/sendfile.h>                      
         ^~~~~~~~~~~~~~~~                      
2 errors generated.                            
Nuitka-Scons: Backend linking program with 7 files (no progress information available for this stage).
scons: *** [static_src/CompiledFunctionType.o] Error 1
FATAL: Failed unexpectedly in Scons C backend compilation.
Nuitka:WARNING:     Complex topic! More information can be found at
Nuitka:WARNING: https://nuitka.net/info/scons-backend-failure.html
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'.
```

**Comment by SuperDisk** [comment]
Looks to me like OpenBSD doesn't have KERN_PROC_PATHNAME, but here the directive incorrectly says to use it:

https://github.com/Nuitka/Nuitka/blob/e6ea71eac84d0a866fad3aa3c26c03577f927018/nuitka/build/static_src/HelpersFilesystemPaths.c#L52

**Comment by SuperDisk** [comment]
I at least got things to compile with this patch, but the resulting binary just core dumps.

```diff
diff --git a/nuitka/build/static_src/HelpersFilesystemPaths.c b/nuitka/build/static_src/HelpersFilesystemPaths.c
index e69cbd749..89cd78ef8 100644
--- a/nuitka/build/static_src/HelpersFilesystemPaths.c
+++ b/nuitka/build/static_src/HelpersFilesystemPaths.c
@@ -49,7 +49,7 @@ filename_char_t *getBinaryPath(void) {
     if (res != 0) {
         abort();
     }
-#elif defined(__FreeBSD__) || defined(__OpenBSD__)
+#elif defined(__FreeBSD__)
     /* Not all of FreeBSD has /proc file system, so use the appropriate
      * "sysctl" instead.
      */
@@ -167,7 +167,7 @@ int64_t getFileSize(FILE_HANDLE file_handle) {
 #if defined(__APPLE__)
 #include <copyfile.h>
 #else
-#if defined(__MSYS__) || defined(__HAIKU__)
+#if defined(__MSYS__) || defined(__HAIKU__) || defined(__OpenBSD__)
 static bool sendfile(int output_file, int input_file, off_t *bytesCopied, size_t count) {
     char buffer[32768];
 
@@ -618,7 +618,7 @@ char const *getBinaryFilenameHostEncoded(bool resolve_symlinks) {
     // Resolve any symlinks we were invoked via
     resolveFileSymbolicLink(binary_filename_target, binary_filename_target, buffer_size, resolve_symlinks);
 
-#elif defined(__FreeBSD__) || defined(__OpenBSD__)
+#elif defined(__FreeBSD__)
     /* Not all of FreeBSD has /proc file system, so use the appropriate
      * "sysctl" instead.
      */
```

**Comment by SuperDisk** [comment]
I got things working using this patch, I grabbed some code off [StackOverflow](https://stackoverflow.com/questions/31494901/how-to-get-the-executable-path-on-openbsd) to implement the binary path thing but I don't really know if it's totally right.

```diff
diff --git a/nuitka/build/static_src/HelpersFilesystemPaths.c b/nuitka/build/static_src/HelpersFilesystemPaths.c
index e69cbd749..f0b258b14 100644
--- a/nuitka/build/static_src/HelpersFilesystemPaths.c
+++ b/nuitka/build/static_src/HelpersFilesystemPaths.c
@@ -34,6 +34,62 @@
 #include "nuitka/filesystem_paths.h"
 #include "nuitka/safe_string_ops.h"
 
+const char *getExecutablePathOBSD(char *epath) {
+  int mib[4];
+  char **argv;
+  size_t len;
+  const char *comm;
+  int ok = 0;
+
+  mib[0] = CTL_KERN;
+  mib[1] = KERN_PROC_ARGS;
+  mib[2] = getpid();
+  mib[3] = KERN_PROC_ARGV;
+
+  if (sysctl(mib, 4, NULL, &len, NULL, 0) < 0)
+    abort();
+
+  if (!(argv = malloc(len)))
+    abort();
+
+  if (sysctl(mib, 4, argv, &len, NULL, 0) < 0)
+    abort();
+
+  comm = argv[0];
+
+  if (*comm == '/' || *comm == '.') {
+    if (realpath(comm, epath))
+      ok = 1;
+  } else {
+    char *sp;
+    char *xpath = strdup(getenv("PATH"));
+    char *path = strtok_r(xpath, ":", &sp);
+    struct stat st;
+
+    if (!xpath)
+      abort();
+
+    while (path) {
+      snprintf(epath, PATH_MAX, "%s/%s", path, comm);
+
+      if (!stat(epath, &st) && (st.st_mode & S_IXUSR)) {
+        ok = 1;
+        break;
+      }
+
+      path = strtok_r(NULL, ":", &sp);
+    }
+
+    free(xpath);
+  }
+
+  if (ok)
+    *strrchr(epath, '/') = '\0';
+
+  free(argv);
+  return ok ? epath : NULL;
+}
+
 filename_char_t *getBinaryPath(void) {
     static filename_char_t binary_filename[MAXPATHLEN];
 
@@ -49,7 +105,9 @@ filename_char_t *getBinaryPath(void) {
     if (res != 0) {
         abort();
     }
-#elif defined(__FreeBSD__) || defined(__OpenBSD__)
+#elif defined(__OpenBSD__)
+    getExecutablePathOBSD(binary_filename);
+#elif defined(__FreeBSD__)
     /* Not all of FreeBSD has /proc file system, so use the appropriate
      * "sysctl" instead.
      */
@@ -167,7 +225,7 @@ int64_t getFileSize(FILE_HANDLE file_handle) {
 #if defined(__APPLE__)
 #include <copyfile.h>
 #else
-#if defined(__MSYS__) || defined(__HAIKU__)
+#if defined(__MSYS__) || defined(__HAIKU__) || defined(__OpenBSD__)
 static bool sendfile(int output_file, int input_file, off_t *bytesCopied, size_t count) {
     char buffer[32768];
 
@@ -617,8 +675,10 @@ char const *getBinaryFilenameHostEncoded(bool resolve_symlinks) {
 
     // Resolve any symlinks we were invoked via
     resolveFileSymbolicLink(binary_filename_target, binary_filename_target, buffer_size, resolve_symlinks);
-
-#elif defined(__FreeBSD__) || defined(__OpenBSD__)
+#elif defined(__OpenBSD__)
+    getExecutablePathOBSD(binary_filename_target);
+    resolveFileSymbolicLink(binary_filename_target, binary_filename_target, buffer_size, resolve_symlinks);
+#elif defined(__FreeBSD__)
     /* Not all of FreeBSD has /proc file system, so use the appropriate
      * "sysctl" instead.
      */
```

**Comment by kayhayen** [comment]
The bit where it does 

```
+  if (ok)
+    *strrchr(epath, '/') = '\0';
```

That seems to be there it strips the binary name away, which is not what is wanted. And in case of not OK, it should `abort` since it must be expected to be possible to resolve this. Can you make a PR @SuperDisk so I can integrate it, seems like a good idea.

**Comment by SuperDisk** [comment]
@kayhayen I created the PR, although I must say that I didn't really test it at all, I just quickly put it together to make something work. Please let me know if there's anything else I can do to help out, I can test on an OpenBSD machine once there's a proper fix so you don't have to set up a VM.

**Comment by kayhayen** [comment]
Correct, this is released now, very many thanks for the help!
