### ISSUE TITLE
Python from Windows App Store not supported

### ISSUE THREAD

**Issue by Ambro86** [Nuitka/Nuitka#663]
Hi, I followed the guide to install Nuitka, however I installed Python 3.8.2.
If I write python --version everything works correctly. Also gcc --version works. I also installed nuitka with pip install nuitka, but if I write nuitka it tells me
"" C: \ Users \ xxx \ AppData \ Local \ Packages \ PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0 \ LocalCache \ local-packages \ P
ython38 \ Scripts \ python "" is not recognized as an internal or external command,
 an executable program or batch file.

But writing python -m nuitka the help page appears.
However if I try to compile any .py file I get several errors:

Traceback (most recent call last):
File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-pack
ages\Python38\site-packages\nuitka\__main__.py", line 182, in <module>
main()
File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-pack
ages\Python38\site-packages\nuitka\__main__.py", line 173, in main
from nuitka import MainControl # isort:skip
File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-pack
ages\Python38\site-packages\nuitka\MainControl.py", line 33, in <module>
from nuitka.freezer.Standalone import copyDataFiles
File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-pack
ages\Python38\site-packages\nuitka\freezer\Standalone.py", line 45, in <module>
from nuitka.nodes.ModuleNodes import PythonShlibModule, makeUncompiledPythonModule
File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-pack
ages\Python38\site-packages\nuitka\nodes\ModuleNodes.py", line 31, in <module>
from nuitka.optimizations.TraceCollections import TraceCollectionModule
File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-pack
ages\Python38\site-packages\nuitka\optimizations\TraceCollections.py", line 33, in <module>
from nuitka.nodes.NodeMakingHelpers import getComputationResult
File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-pack
ages\Python38\site-packages\nuitka\nodes\NodeMakingHelpers.py", line 31, in <module>
from nuitka.Builtins import builtin_names
File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-pack
ages\Python38\site-packages\nuitka\Builtins.py", line 190, in <module>
builtin_anon_names, builtin_anon_codes = _getAnonBuiltins()
File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-pack
ages\Python38\site-packages\nuitka\Builtins.py", line 145, in _getAnonBuiltins
with open(sys.executable) as any_file:
OSError: [Errno 22] Invalid argument: ’C:\\Users\\xxx\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFounda
tion.Python.3.8_qbz5n2kfra8p0\\python.exe’

Thank you if you want to give me an indication.
Ambro

**Comment by kayhayen** [comment]
That's very strange, I am also confused as to the directory name, never seen those kind of names, but then again, I always choose where to install Python myself. I am upgrading to 3.8.2 just to see if there is anything that changed.

**Comment by Ambro86** [comment]
Hi, I noticed that the error occurs if you install Python from the Microsoft Store, as I had done. For this there were these strange folders. Installing Python normally from python.org works correctly, even with version 3.8.2.

**Comment by kayhayen** [comment]
Ok, that's unsupported I guess, but I will try have a look at the difference. Very strange looking one though.

**Comment by kayhayen** [comment]
Not being allowed to open `sys.executable` for reading is very probably a security thing for Windows apps, and limits our ability to work with this very severely. I will add a check for it, or an exception handler, that catches this, and explains it.

I also added something to user manual that you probably didn't read, as it already says what is only supported.

**Comment by Ambro86** [comment]
Thanks a lot. Congratulations on this beautiful project.

**Comment by kayhayen** [comment]
The check is now in the latest pre-release, and will soon be released.

**Comment by kayhayen** [comment]
The release 0.6.8 was just made and contains the correction.
