### ISSUE TITLE
TypeError in warning for pefile dependency walker

### ISSUE THREAD

**Issue by Slyfoxy** [Nuitka/Nuitka#664]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

	`python -m nuitka --version`
	```
	0.6.8rc5
	Python: 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
	Executable: F:\Projects\myproject\venv\Scripts\python.exe
	OS: Windows
	Arch: x86_64
	```
* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
what is a virtualenv ...), this is very important usually.

	

* Many times when you get an error from Nuitka, your setup may be so special
that even a "hello world" program will not work, please try that and report
it instead.

	* Hello world does not work

* If possible please supply a Short, Self Contained, Correct, Example
that demonstrates the issue i.e a small piece of code which reproduces
the issue and can be run with out any other (or as few as possible)
external dependencies.
		
	Python code:
	```python3
	print("hello, world")
	```
	Command:
	`python -m nuitka --standalone --windows-dependency-tool=pefile --experimental=use_pefile_recurse --experimental=use_pefile_fullrecurse --follow-imports  --mingw64 --show-progress  --python-arch=x86_64 test.py`

	Output:
	```
	  File "f:\projects\myproject\venv\src\nuitka\nuitka\utils\SharedLibraries.py", line 275, in getPEFileInformation
	    % ("64" if python_is_64bit else "32" "32" if python_is_64bit else "64")
	TypeError: not enough arguments for format string
	```

	Problem line:
	https://github.com/Nuitka/Nuitka/blob/ba6d5681c31535a3834c35794c1f053799a36c48/nuitka/utils/SharedLibraries.py#L275

**Comment by kayhayen** [comment]
This is on the factory branch and will be part of the next pre-release, due soon.

https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
This is now in the latest pre-release, and will soon be released.

**Comment by kayhayen** [comment]
The release 0.6.8 was just made and contains the correction.
