### ISSUE TITLE
Script using pytorch and torch.cat on gpu tensors crash

### ISSUE THREAD

**Issue by rsirefelt** [Nuitka/Nuitka#666]
Just a small issue I found when trying to nuitka compile a simple script using pytorch with GPU which might be of interest. The script works if the below tensors x1 and x2 are put on the cpu instead or if the script is run through python directly. 

Computer:
Ubuntu 18.04
Gpu gtx1080

Environment install:
virtualenv -p python3.6 env
pip install nuitka
pip install numpy
pip install torch

pip freeze:
Nuitka==0.6.7
numpy==1.18.2
pkg-resources==0.0.0
torch==1.4.0

Code to reproduce error

repro_script.py
```python
import torch

x1 = torch.rand(1, 50, 20).to(torch.device("cuda"))
x2 = torch.rand(1, 5, 20).to(torch.device("cuda"))
x = [x1, x2]
y = torch.cat(x, 1)
```

Build:
python -m nuitka --standalone --follow-imports --plugin-enable=numpy --plugin-enable=torch repro_script.py

Works when running python repro_script.py

Error when running executable in dist:
File "/home/xxx/repro_script.dist/repro_script.py", line 6, in <module>
RuntimeError: Error in dlopen or dlsym: libcaffe2_nvrtc.so: cannot open shared object file: No such file or directory

**Comment by abhibha1807** [comment]
I am also facing the same issue, were you able to find a workaround? @rsirefelt

**Comment by rsirefelt** [comment]
No I don't think so unfortunatly. In the end I just implemented my stuff in
c++ from scratch.

**Comment by abhibha1807** [comment]
I tried replicating your error, but it seems to work fine. Probably the crash is due to torch.cat(). In my case, 
````
import torch
x=torch.rand(1)
y=torch.rand(1)
torch.cat(x,y[0])  #code crashes
torch.cat(x,y)  #works fine
#right way
y=torch.unsqueeze(y,1)
torch.cat(x,y[0])  #now works fine
````
Turns out I needed to 'unsqueeze' tensor y, so that I could reference elements from tensor y.
