### ISSUE TITLE
scons: *** [module.__main__.o] Error 1

### ISSUE THREAD

**Issue by BlackRouter** [Nuitka/Nuitka#669]
```
0.6.7
Python: 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 18 2019, 23:46:00) [MSC v.1916 32 bit (Intel)]
Executable: D:\Project\Moeinsoft\Launcher\venv\Scripts\python.exe
OS: Windows
Arch: x86
Modules usage: 
certifi==2019.11.28
chardet==3.0.4
coverage==5.0.4
idna==2.9
ippanel==1.1.0
Nuitka==0.6.7
PyQt5==5.14.1
PyQt5-sip==12.7.1
PyQt5-stubs==5.14.2.0
pywin32==227
requests==2.23.0
soupsieve==2.0
swinlnk==0.1.4
urllib3==1.25.8
zc.lockfile==2.0

```
i compile with mingw pyqt5 project and my project is 7700 line code and 445kb size but i want compile via this command error i give:

`nuitka main.py --show-progress --recurse-all --standalone --enable-plugin=qt-plugins=sensible,styles --windows-disable-console`

i get error:

> cc1.exe: out of memory allocating 54044 bytes
> scons: *** [module.__main__.o] Error 1

**Comment by kayhayen** [comment]
Can you indentify, which C files is getting the out of memory error, there will be a scalability problem at hand.

**Comment by BlackRouter** [comment]
> Can you indentify, which C files is getting the out of memory error, there will be a scalability problem at hand.

i think module.__main__.c

screenshot: https://i.imgur.com/VhLzgww.jpg

**Comment by kayhayen** [comment]
Then please provide `main.py` if you can.

**Comment by BlackRouter** [comment]
> Then please provide `main.py` if you can.

can i send to your email , this is private project?

**Comment by kayhayen** [comment]
Yes, that's OK.

**Comment by BlackRouter** [comment]
> Yes, that's OK.

i send to email kay.hayen@gmail.com

**Comment by BlackRouter** [comment]
@kayhayen hi bro are you check my source?

**Comment by kayhayen** [comment]
I received it, but I didn't have the time yet to check itout. If you want to me to do it sooner, get in touch with me for commercial support.

**Comment by BlackRouter** [comment]
@kayhayen price your  commercial support

**Comment by kayhayen** [comment]
Closing this, as I am not going to look at it for free.
