### ISSUE TITLE
Code Signature Invalid for Python

### ISSUE THREAD

**Issue by daviss92** [Nuitka/Nuitka#672]
I couldn't find another question, this could be an issue from my systems end but I don't really know how to address it.

**Nuitka version, full Python version and Platform (Windows, OSX, Linux ...**)
0.6.7
Python: 3.7.7 (v3.7.7:d7c567b08f, Mar 10 2020, 02:56:16) 
Executable: ~/Desktop/TestFolder/venv/bin/python
OS: Darwin
Arch: x86_64

**How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.**
pip

I'm not going to go into my actual program and just jump into a hello world example.

```
import os
print("HELLO WORLD")
```

Running nuitka with the below compiles successfully
`python -m nuitka --standalone test.py`

When I go to the test.dist folder, double-click or drag the executable into terminal, I receive this:

```
(venv) Seans-iMac:TestFolder seandavis$ /Users/seandavis/Desktop/TestFolder/test.dist/test 
dyld: Library not loaded: @executable_path/Python
  Referenced from: /Users/seandavis/Desktop/TestFolder/test.dist/test
  Reason: no suitable image found.  Did find:
	/Users/seandavis/Desktop/TestFolder/test.dist/Python: code signature invalid for '/Users/seandavis/Desktop/TestFolder/test.dist/Python'

	/Users/seandavis/Desktop/TestFolder/test.dist/Python: stat() failed with errno=1
	/Users/seandavis/Desktop/TestFolder/test.dist/Python: code signature invalid for '/Users/seandavis/Desktop/TestFolder/test.dist/Python'

	/Users/seandavis/Desktop/TestFolder/test.dist/Python: stat() failed with errno=1
Abort trap: 6
```

So, I thought, let me run the certificate.command that comes with python 3.7 from the venv and try again... But it made no difference. Note this below is a re-run.

```
(venv) Seans-iMac:TestFolder seandavis$ /Applications/Python\ 3.7/Install\ Certificates.command 
 -- pip install --upgrade certifi
Requirement already up-to-date: certifi in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (2020.4.5.1)
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
 -- removing any existing file or link
 -- creating symlink to certifi certificate bundle
 -- setting permissions
 -- update complete
```

**Comment by kayhayen** [comment]
I couldn't immediately recognize what kind of Python this is. It seems it's the standard one from macOS, right? The `@executable_path/Python` is not supposed to be a binary, but a shared library, but maybe there is none such anymore?

Can you provide the output of `otool -L ~/Desktop/TestFolder/venv/bin/python` then, that's probably going to reveal information needed.

**Comment by daviss92** [comment]
**MacOS Mojave 10.14.6**

```
(venv) Seans-iMac:TestFolder seandavis$ otool -L ~/Desktop/TestFolder/venv/bin/python
/Users/seandavis/Desktop/TestFolder/venv/bin/python:
	/Library/Frameworks/Python.framework/Versions/3.7/Python (compatibility version 3.7.0, current version 3.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
```

**Comment by daviss92** [comment]
**Update**

This is an Installation Issue, nothing with nuitka itself.

For those that ever encounter the same...

This seems to be a common issue with MacOS, not just with Python but other tools like Homebrew. It seems, after significant macOS Updates and Patches, Apple modifies/replaces lib files... among other components and tools.

Things are further muddied because I have the base 2.7 Python Install, 3.6 and 3.7.7.

I attempted using `virtualenv` instead of python3's built in `python -m venv` tool.

This used the Python 3.6 instance, nuitka compiled with no problems and launching the executable threw no errors.
