### ISSUE TITLE
ModuleNotFoundError: No module named 'psutil' issue

### ISSUE THREAD

**Issue by gauthierbuttez** [Nuitka/Nuitka#673]
I have an issue when I compile a python file with:
0.6.7
Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
OS: Windows
Arch: x86_64

I get this error:
```
Traceback (most recent call last):
File "E:\DropboxBACKUP14112018\Cff\Python\PhoneBot\phonebot.py", line 7, in <module>
import psutil
ModuleNotFoundError: No module named 'psutil'
```

So I search on google, doc and here. It seems it is because I forgot the arg "--standalone" ?
It takes almost 1 hour to compile the code. Before compiling again, I would prefer the recommendation of an expert.
This was my command:
`py -m nuitka --show-progress --show-scons --windows-disable-console --follow-imports --windows-icon=E:\DropboxBACKUP14112018\Cff\Python\PhoneBot\favicon_phonebot.ico phonebot.py`
I am using pycharm and psutil is installed.
Should I run the nuitka command line inside pycharm to be sure it will compile and include all my modules and libraries?

Thanks.

**Comment by kayhayen** [comment]
Standalone is supposed to make it run independent of the Python installation. Use it if that's what you want it to do. Using the correct Python environment is essential. So if `py phonebot.py` is not working, where you compile, no need to start with Nuitka. I am closing assuming that's your mistake.
