### ISSUE TITLE
Suggestion regarding `nuitka/tools/release/Documentation.py`

### ISSUE THREAD

**Issue by oz123** [Nuitka/Nuitka#674]
Hi, 
While working on packaging nuitka for gentoo, I noticed that the [Documentation.py](https://github.com/Nuitka/Nuitka/blob/8b97b891385b5d07c466ce7d0f0c8d71987f6202/nuitka/tools/release/Documentation.py) script contains
many of the following  `assert` ...`os.system` blocks:

```
assert (
            os.system(
                "convert -resize 32x32 doc/Logo/Nuitka-Logo-Symbol.svg ../nikola-site/files/favicon.ico"
            )
            == 0
        )
```

Those can be replaced with `subprocess.check_call` which raises an exception if the process exists with a code other than 0.

This change can reduce many lines of code.
Before I rush to create a patch, I was wondering if you are interested in merging such a change.

Thank you for your work on Nuitka.

**Comment by kayhayen** [comment]
Hello, this is very welcome proposal. In the tooling, I have been lazy, and not adopted subprocess, but remained with this very low skill code.

Not to mention, that asserts, since they can be disabled, must never execute any actual stuff....
