### ISSUE TITLE
"ImportError" of numpy after compilation with Nuitka 

### ISSUE THREAD

**Issue by gauthierbuttez** [Nuitka/Nuitka#677]
Hi,

I am trying to compile my python program with Nuitka.
I have Python 3.7 on Windows 10.
The compilation goes fine but when I execute the .exe of my program freshly complicated, I get this error:
http://prntscr.com/s0z64w

So I follow the recommendation displayed on the screen:
I uninstall and reinstall bumpy 1.18.2.
I uninstall, reinstall and double-check my python 3.7.
I compile again my python script with nuitka and again I get the same issue.

I also publish the issue on Numpy github page:
https://github.com/numpy/numpy/issues/16002

They recommend me to ask here as they don't know so much about Nuitka.

Do you have any idea how can I fix that please?

**Comment by gauthierbuttez** [comment]
I made a test:
1. I create a simple python script which involved 'numpy' (numpy_test.py):

```
import numpy as np
a = np.arange(15).reshape(3, 5)
a
np.array([[0, 1, 2, 3, 4],
          [ 5,  6,  7,  8,  9],
          [10, 11, 12, 13, 14]])
print(a.shape)
```
2. I compile it with nuitka:

`python -m nuitka --standalone --show-progress --show-scons --follow-imports numpy_test.py`

3. Guess what! I get exact same error:

> E:\DropboxBACKUP14112018\Cff\Python\numpy_test>cd numpy_test.dist
> 
> E:\DropboxBACKUP14112018\Cff\Python\numpy_test\numpy_test.dist>numpy_test.exe
> Traceback (most recent call last):
>   File "E:\DropboxBACKUP14112018\Cff\Python\numpy_test\numpy_test.dist\numpy\core\__init__.py", line 24, in <module numpy.core>
>   File "E:\DropboxBACKUP14112018\Cff\Python\numpy_test\numpy_test.dist\numpy\core\multiarray.py", line 14, in <module numpy.core.multiarray>
>   File "E:\DropboxBACKUP14112018\Cff\Python\numpy_test\numpy_test.dist\numpy\core\overrides.py", line 7, in <module numpy.core.overrides>
> ImportError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "E:\DropboxBACKUP14112018\Cff\Python\numpy_test\numpy_test.dist\numpy_test.py", line 1, in <module>
>   File "E:\DropboxBACKUP14112018\Cff\Python\numpy_test\numpy_test.dist\numpy\__init__.py", line 142, in <module numpy>
>   File "E:\DropboxBACKUP14112018\Cff\Python\numpy_test\numpy_test.dist\numpy\core\__init__.py", line 54, in <module numpy.core>
> ImportError:
> 
> IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
> 
> Importing the numpy c-extensions failed.
> - Try uninstalling and reinstalling numpy.
> - If you have already done that, then:
>   1. Check that you expected to use Python3.7 from "C:\Users\Nino\AppData\Local\Programs\Python\Python37\python.exe",
>      and that you have no directories in your PATH or PYTHONPATH that can
>      interfere with the Python and numpy version "1.18.2" you're trying to use.
>   2. If (1) looks fine, you can open a new issue at
>      https://github.com/numpy/numpy/issues.  Please include details on:
>      - how you installed Python
>      - how you installed numpy
>      - your operating system
>      - whether or not you have multiple versions of Python installed
>      - if you built from source, your compiler versions and ideally a build log
> 
> - If you're working with a numpy git repository, try `git clean -xdf`
>   (removes all files not under version control) and rebuild numpy.
> 
> Note: this error has many possible causes, so please don't comment on
> an existing issue about this - open a new one instead.
> 
> Original error was:

So I make a conclusion than Nuitka can't compile Numpy. What do you think about?

**Comment by kayhayen** [comment]
I guess you ought to use the numpy plugin of Nuitka, which I believe Nuitka also told you to do.

**Comment by gauthierbuttez** [comment]
Hi Kay, maybe I could exclude 'numpy' from compilation and leave it as open source. I will have to include it to the dust folder as my exe will call it. Do you think it is possible?
