### ISSUE TITLE
Can general DLLs be compiled instead of PYD?

### ISSUE THREAD

**Issue by qq1113162232** [Nuitka/Nuitka#682]
I have a program that only supports DLL extension. I want to use Python to develop the extension. I use Cython to implement a DLL and export the required functions and use them, but I can't find a way to generate a single DLL for the whole project. I found nuitka, but I couldn't find a way to export the function at nuitka.

**Comment by kayhayen** [comment]
Nuitka right now doesn't have this ability, but it could be added. Contact me privately if you are a commercial user willing to put funding into this feature, this could be added, but would have to be paid for.

**Comment by kayhayen** [comment]
BTW: Contacting me privately means via Email, not Twitter. I think might not allow that in my profile or so, if it doesn't work for you. I am definitely not checking it very often too.
