### ISSUE TITLE
Is Nuitka not supported by some packages?

### ISSUE THREAD

**Issue by qq1113162232** [Nuitka/Nuitka#684]
I compiled my program with Nuitka, and I packaged it as a stand-alone program. 
The third-party package I use: pyside2, Peewee,PIL . 
The environment I use is: 
Windows 10 X64. 
Python 3.7.5 X86. 
Pycharm venv

> nuitka --follow-imports --plugin-enable=qt-plugins main.py

`Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\Administrator\Desktop\robot\venv\lib\site-packages\PIL\Image.py:38
1' may require use of '--include-plugin-directory' or '--include-plugin-files'.`

Then I used --include-plugin-directory and the program still wouldn't open

#682  How much does this feature cost? I couldn't reach you on twitter.

**Comment by kayhayen** [comment]
As a question, it's defintely true that not all packages support Nuitka. In fact, very few do, it's normally the other way around.

In the case of PySide2, we would need them to support Nuitka by accepting our patches, which they did not, so dont use both, Nuitka and PySide2.

**Comment by math-artist** [comment]
Hi @kayhayen , is there any way to make them change their mind on accepting the patches?

I first had to make a switch from PySide2 to PyQt only because of that restriction, but now I see projects dropping PyQt in favor of PySide2, essentially because of the too restrictive GPL license.

**Comment by kayhayen** [comment]
I think the usual best technique for changing minds is convincing arguments @math-artist 

Somebody willing to do the work in PySide2 would clearly be an advantage in any case. I have once created those patches myself, but I am not going to repeat it now, for lack of man power on my side to do these things. Eventually my hope is, with increasing importance of Nuitka, it may become more convincing. So I work on that.

**Comment by alexdelorenzo** [comment]
@kayhayen I'd like to use PySide2 with Nuitka, so if you can link to those patches, I'll see what I can do even if that's just showing interest.

**Comment by kayhayen** [comment]
@alexdelorenzo these were my best ones, notice somebody also added something, and then there were reports of it working. It's not rocket science really. But I think PySide2 might not match them, but the general idea should be the same.
