### ISSUE TITLE
No system module 'pythoncom' (pythoncom37.dll)

### ISSUE THREAD

**Issue by Winand** [Nuitka/Nuitka#688]
- nuitka 0.6.7
- Python: 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
- Executable: D:\andray\Software\Python\Anaconda3\python.exe
- OS: Windows
- Arch: x86_64
- Anaconda x64
- VS Code
- Related to #296 (?)

Here's my test script:
```python
import pythoncom
print("Hello world", pythoncom.VT_I4)
```

Compile script:
```python
import sys

compiler = "nuitka"
main_module = "test.py"
icon = "Pocket-watch-open.ico"

if compiler=="nuitka":
    # Run in activated Anaconda environment, otherwise Qt plugins not found
    # Run w/o debugging:
    # - nuitka.__main__.main cannot restart itself with added --module arg
    # - scons gives "unknown option -port" error
    import subprocess, pathlib
    args = [
        "python", "-m", "nuitka",
        "--show-progress",
        "--standalone",
        "--python-flag=no_site",
        "--nofollow-import-to=environment_settings",
        # "--plugin-enable=qt-plugins",
        "--windows-icon=" + str(pathlib.Path(icon).absolute()),
        # "--windows-disable-console",
        # "--show-scons",
        "--experimental=use_pefile",
        main_module,
    ]
    if not subprocess.run(args).returncode:
        print("all done")
```

It gives import error
```
D:\andray\Software\Python\projects\nuitka_qt_test\test.dist>test
Traceback (most recent call last):
  File "D:\andray\Software\Python\projects\nuitka_qt_test\test.dist\test.py", li
ne 8, in <module>
  File "D:\andray\Software\Python\projects\nuitka_qt_test\test.dist\pythoncom.py
", line 3, in <module pythoncom>
  File "D:\andray\Software\Python\projects\nuitka_qt_test\test.dist\pywintypes.p
y", line 110, in __import_pywin32_system_module__
ImportError: No system module 'pythoncom' (pythoncom37.dll)
```

But nuitka puts `pythoncom.pyd` file into .dist folder and **if I simply rename it to `pythoncom37.dll` the program starts correctly.**

**Comment by kayhayen** [comment]
Can you retry with 0.6.8.1 hotfix, this seems very similar to a recently fixed bug.

**Comment by Winand** [comment]
Ok, now it puts both `pythoncom.pyd` and `pythoncom37.dll` (which are actually the same file?) to the output directory and the test script works fine. Also it depends on `pythoncom.pyd` now. If I delete the dll file the script still works.

**Comment by kayhayen** [comment]
You probably mean deleting the later @Winand . Can I ask you to create a new issue, because re-opening this one seems invalid. I honestly didn't get what is the issue from your last comment, but going on here, makes no sense to me. Please file a new issue.
