### ISSUE TITLE
win32com import error

### ISSUE THREAD

**Issue by MKdays** [Nuitka/Nuitka#696]
Hi,
I've just joined GitHub to ask a question to you. 😇

# Env
   Nuitka : 0.6.7
   Python: 3.8.2 32bit
   OS : Windows 10 64bit

# Python Script
import win32com.client
print("Test")

# Nuitka Script
python -m nuitka
--standalone
--remove-output
--follow-imports
nuitka_report.py

# Error Message
-# After Nuitka script is finished,
C:\Users\MK\Desktop\PyProject>python -m nuitka --standalone --remove-output --follow-imports nuitka_report.py
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Python\lib\site-packages\win32com\client\gencache.py:236' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Python\lib\site-packages\win32com\client\gencache.py:627' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Python\lib\site-packages\win32com\client\makepy.py:320' may require use of '--include-plugin-directory' or '--include-plugin-files'.

-# When I run exe file,
C:\Users\MK>C:\Users\MK\Desktop\PyProject\nuitka_report.dist\nuitka_report.exe
Traceback (most recent call last):
  File "C:\Users\MK\Desktop\PyProject\nuitka_report.dist\nuitka_report.py", line 2, in <module>
  File "C:\Users\MK\Desktop\PyProject\nuitka_report.dist\win32com\__init__.py", line 5, in <module win32com>
ImportError

# How to Handle The Error in my case
Below two files are missing in dist folder.

C:\Python\Lib\site-packages\pywin32_system32\
pythoncom38.dll
pywintypes38.dll

So I copy them manually to dist folder and It's OK.
(Pyinstaller is always OK with my Script.)

Thank you.

**Comment by kayhayen** [comment]
This is released as part of 0.6.8.1 hotfix.
