### ISSUE TITLE
Error when compiling: unbalanced parenthesis in operand 2.

### ISSUE THREAD

**Issue by CharlesWong1** [Nuitka/Nuitka#702]
Hello! I met the following issue when compiling:

> {standard input}: Assembler messages:
> {standard input}:270623: Warning: end of file not at end of a line; newline inserted
> {standard input}:270726: Error: unbalanced parenthesis in operand 2.
> {standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
> gcc: fatal error: Killed signal terminated program cc1
> compilation terminated.
> scons: *** [module.__main__.o] Error 1

The code was working well, but this issue happened when compiling.
It seems the C code nuitka generated has this error: unbalanced parenthesis in operand 2.

Environment:
Python 3.8
Ubuntu 18.02

**Comment by kayhayen** [comment]
This is low memory to the gcc compiler, not a Nuitka bug per se.

**Comment by CharlesWong1** [comment]
Got that. I compiled the code on a computer with larger memory and THAT error does not exist.

But I met a new error:
> raceback (most recent call last):
>   File "/home/charles/.local/lib/python3.8/site-packages/nuitka/__main__.py", line 182, in <module>
>     main()
>   File "/home/charles/.local/lib/python3.8/site-packages/nuitka/__main__.py", line 175, in main
>     MainControl.main()
>   File "/home/charles/.local/lib/python3.8/site-packages/nuitka/MainControl.py", line 782, in main
>     copyDataFiles(dist_dir=dist_dir, data_files=data_files)
>   File "/home/charles/.local/lib/python3.8/site-packages/nuitka/freezer/Standalone.py", line 1555, in copyDataFiles
>     for source_desc, target_filename in data_files:
> ValueError: not enough values to unpack (expected 2, got 0)
This happened after gcc compiled finish.

**Comment by CharlesWong1** [comment]
Got that. I compiled the code on a computer with larger memory and THAT error does not exist.
But I met a new error:

> Traceback (most recent call last):
> File "/home/charles/.local/lib/python3.8/site-packages/nuitka/main.py", line 182, in 
> main()
> File "/home/charles/.local/lib/python3.8/site-packages/nuitka/main.py", line 175, in main
> MainControl.main()
> File "/home/charles/.local/lib/python3.8/site-packages/nuitka/MainControl.py", line 782, in main
> copyDataFiles(dist_dir=dist_dir, data_files=data_files)
> File "/home/charles/.local/lib/python3.8/site-packages/nuitka/freezer/Standalone.py", line 1555, in copyDataFiles
> for source_desc, target_filename in data_files:
> ValueError: not enough values to unpack (expected 2, got 0)

This happened after gcc compiled finish. It seems this is a bug of nuitka.
BTW, I got a folder xxx.dist and xxx.build. There is a xxx (executable file) in xxx.dist. But it can't run standalone. And I didn't get a xxx outside those two folders.
