### ISSUE TITLE
Cannot locate suitable C compiler VS2019

### ISSUE THREAD

**Issue by lowlyocean** [Nuitka/Nuitka#703]
Hello, this is regarding nuitka version 0.6.7 obtained via pip on Windows Server 2019.

The precise error can be found [in this pipeline output](https://github.com/Fuzzwah/race-info/runs/661636648?check_suite_focus=true#step:4:9):
```
scons: warning: MSVC_USE_SCRIPT set to False, assuming environment set correctly.
File "C:\HOSTED~1\windows\Python\3794D4~1.7\x64\lib\SITE-P~1\nuitka\build\SINGLE~1.SCO", line 521, in createEnvironment
Error, cannot locate suitable C compiler. You have the following options:

a) If a suitable Visual Studio version is installed, it will not be located
   automatically, unless you install pywin32 for the Python installation
   below "C:\hostedtoolcache\windows\Python\3.7.7\x64".

b) To make it find Visual Studio without registry execute from Start Menu
   the 'Visual Studio Command Prompt' or "vcvarsall.bat". That will add
   Visual Studio to the "PATH". And it then will be detected.

c) Install MinGW64 to "C:\MinGW64" or "\MinGW", where then it is automatically
   detected or add it to PATH before executing Nuitka. But be sure to pick the
   proper variant (32/64 bits, your Python arch is 'x86_64'), or else cryptic errors
   will be shown.
```

The build machine has [Visual Studio 2019 Enterprise](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md#visual-studio-2019-enterprise) installed, and as part of suggestion b) provided by the error, I run this command [beforehand](https://github.com/Fuzzwah/race-info/runs/661636648?check_suite_focus=true#step:3:37) (but still encounter this error):
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat`

Also tried `pip install pywin32` beforehand to address suggestion a), but this also leads to same error.

**Comment by lxbrass** [comment]
This worked for me, one month ago (mid April 2020) using nuitka 0.6.7:

1) Install Microsoft - Visual Studio Build Tools 2019, default options
should be enough. I changed the install location.
[image: image.png]

2) Find vcvarsall.bat in your installation, I found it in F:\Microsoft
Visual Studio\2019\Community\VC\Auxiliary\Build

3) Choose your build target (x86 or x64) to match the Python
version/platform of your project.

4) Open a command environment there and execute vcvarsall.bat, with the
proper arguments for your target, to set the environment variables.

5) In the same command window *navigate* to the location of your Python
project.

6) Compile with Nuitka.

7) If that works, add the call to vcvarsall.bat to your build scripts... or
the build system complexity layer of your choice ;-)

Cheers.

**Comment by lowlyocean** [comment]
Hi, thank you for the reply. I'm not sure how this differs from the environment in the CI/CD runner as it seems to be quite similar. I added the x64 argument to vcvarsall.bat but this didn't quite resolve the problem.

**Comment by lxbrass** [comment]
Hi Daniel,

The purpose of doing it manually is to remove the complexity of the CI/CD
runner for the test, once checked you can move up into the chain.

Can you add a task to the job in that CI/CD runner to print out the
environment variables, before calling nuitka?

If you are sure you are in 64 bit Windows generating code for 64 bit
windows you may try using vcvars64.bat instead.

**Comment by lowlyocean** [comment]
Thanks, seems indeed to have been an issue of how I was invoking vcvarsall.bat from the CI/CD shell. I'm now using 32-bit VS and python and have some progress. I am getting a different [error](https://github.com/Fuzzwah/race-info/runs/662209054?check_suite_focus=true#step:4:361) now though, [here](https://github.com/Nuitka/Nuitka/blob/develop/nuitka/utils/SharedLibraries.py#L282) ,
```
  File "C:\hostedtoolcache\windows\Python\3.8.2\x86\lib\site-packages\nuitka\utils\SharedLibraries.py", line 274, in getPEFileInformation
    "Python %s bits with %s bits dependencies in '%s'"
TypeError: not enough arguments for format string
```

**Comment by lxbrass** [comment]
Hi Daniel,

It seems that there is a mix of 32 bit and 64 bit somewhere on the tools or
targets, check them carefully. Compilers can generate code for different
bitnesses (is this a word?) as self.

It also seems that you found a bug in Nuitka because it was trying to build
a message about some bitness mismatch and got a TypeError!

Personal opinion: These days you want everything 64 bit unless you are
developing for Raspberry Pi, Arduino or other embedded systems.

**Comment by kayhayen** [comment]
That's a bug fixed in 0.6.8 btw.

Unfortunately Microsoft has rejected a previous request to get their tools. So it's working out of the box with what I got, which is the community edition. For the other, you need to know what you are doing, so this is a user error.

**Comment by lowlyocean** [comment]
Thanks Kay, I was trying to use 0.6.8 from github instead, but it runs into "Server refused our key":
`pip install git+https://github.com/Nuitka/Nuitka.git@0.6.8#egg=Nuitka --upgrade`

Believe it may be related to submodules using SSH rather than HTTPS

**Comment by kayhayen** [comment]
That's something I need to check out. Obviously auth via HTTP for writing is something different than ssh to set it up. By default, I thought git wasn't doing submodules though, does it?

**Comment by lowlyocean** [comment]
Found a workaround [here](https://github.com/pypa/pip/issues/6623#issuecomment-541378375), but as mentioned [slightly earlier](https://github.com/pypa/pip/issues/6623#issuecomment-503242527) cloning with HTTPS URLs is recommended so perhaps it can be changed in Nuitka's .gitmodules

**Comment by kayhayen** [comment]
@lowlyocean I am switching to https, just did so for factory branch. I hated it for writing if I recall correctly, because it needs more than a simply ssh key, but I will sort that out I guess
