### ISSUE TITLE
Issue when using standalone mode

### ISSUE THREAD

**Issue by CharlesWong1** [Nuitka/Nuitka#706]
I met this issue when using standalone mode to compile:

> Traceback (most recent call last):
> File "/home/charles/.local/lib/python3.8/site-packages/nuitka/main.py", line 182, in
> main()
> File "/home/charles/.local/lib/python3.8/site-packages/nuitka/main.py", line 175, in main
> MainControl.main()
> File "/home/charles/.local/lib/python3.8/site-packages/nuitka/MainControl.py", line 782, in main
> copyDataFiles(dist_dir=dist_dir, data_files=data_files)
> File "/home/charles/.local/lib/python3.8/site-packages/nuitka/freezer/Standalone.py", line 1555, in copyDataFiles
> for source_desc, target_filename in data_files:
> ValueError: not enough values to unpack (expected 2, got 0)

This happened after gcc compiled finish. It seems this is a bug of nuitka.
BTW, I got a folder main.dist and main.build. There is a main (executable file) in main.dist. But it can't run standalone. It needs to run with the other files in the folder. And I didn't get a main outside those two folders.

**Comment by kayhayen** [comment]
When Nuitka fails, it doesn't cleanup and leaves it around for debugging purposes.

You didn't fill out the issue template, which is unacceptable.

**Comment by CharlesWong1** [comment]
Python: 3.8.2
OS: Linux
Nuitka 0.6.8

This issue only happened when I'm using Python 3.8
I downgraded to Python 3.7 and there is no issues

**Comment by kayhayen** [comment]
Minimal reproducer?

**Comment by CharlesWong1** [comment]
Minimal reproducer? Yes

BTW, although nuitka didn't threw an error on Python 3.7, it didn't generate the standalone file but only main.build and main.dist

**Comment by kayhayen** [comment]
Closing for lack of feedback.
