### ISSUE TITLE
qwindowsvistastyle.dll import error

### ISSUE THREAD

**Issue by MKdays** [Nuitka/Nuitka#708]
Hi. Nuitka 0.6.8 Version seem like not support PyQy5 `"qwindowsvistastyle.dll"`
As a result, the Windows style seems like old.

![1](https://user-images.githubusercontent.com/64838226/82082801-9785cf80-9723-11ea-83f6-7af8a7b6ee73.JPG)

So I copy the file manually to dist folder then It becomes OK.

> From : C:\Python\Lib\site-packages\PyQt5\Qt\plugins\styles\qwindowsvistastyle.dll
> To : .dist\PyQt5\qt-plugins\styles\qwindowsvistastyle.dll

Thank you.

**Comment by kayhayen** [comment]
I would really prefer the issue template over screenshots.

**Comment by MKdays** [comment]
Problem solved.

nuitka version0.6.8.1
Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)]
Executable: C:\Python\python.exe
OS: Windows
Arch: x86

# Case1 : enable-plugin=qt-plugins=sensible,styles
python -m nuitka
--enable-plugin=qt-plugins=sensible,styles
--standalone
--remove-output
--follow-imports
--windows-icon="C:\Users\MK\Desktop\Py\Material\py_app_icon.ico"
"ExcelTool.py"

### then error message
C:\Users\MK\Desktop\Py>python -m nuitka --enable-plugin=qt-plugins=sensible,styles --standalone --remove-output --follow-imports --windows-icon="C:\Users\MK\Desktop\Py\Material\py_app_icon.ico" "ExcelTool.py"
Error, unknown plug-in 'qt-plugins=sensible,styles' referenced.

# Case2 : --plugin-enable=qt-plugins
python -m nuitka
--plugin-enable=qt-plugins
--standalone
--remove-output
--follow-imports
--windows-icon="C:\Users\MK\Desktop\Py\Material\py_app_icon.ico"
"ExcelTool.py"

### then no error, but .dist\PyQt5\qt-plugins\styles\qwindowsvistastyle.dll is missing.
### As a result, the Windows style seems like old.

# Case3 : --include-qt-plugins=sensible,styles
python -m nuitka
--plugin-enable=qt-plugins
--include-qt-plugins=sensible,styles
--standalone ^
--remove-output ^
--follow-imports ^
--windows-icon="C:\Users\MK\Desktop\Py\Material\py_app_icon.ico" ^
"ExcelTool.py"

### then it worked properly.

**Comment by kayhayen** [comment]
Not a bug, styles are not included on purpose.
