### ISSUE TITLE
Exception in buildAnnotationNode when using future's annotations

### ISSUE THREAD

**Issue by paravoid** [Nuitka/Nuitka#709]
Nuitka --version is:
```
0.6.8.1
Python: 3.8.3 (default, May 14 2020, 11:03:12) 
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
```

This is the version from https://nuitka.net/pages/download.html. Originally I had tried with 0.6.8 as found in Debian unstable, with the same result.

Same issue applies to the 0.6.9rc1 snapshot as well.

This does not work:
```python3
from __future__ import annotations

from typing import Sequence

def colonjoin(seq: Sequence[str]) -> str:
    return ":".join(seq)

print(colonjoin(["foo", "bar"]))
```
Removing the `from __future__ import annotations` makes the example work.

The backtrace I get is:
```
Nuitka:WARNING:Problem at '<SourceCodeReference to ../ircstream/koko.py:5>' with FunctionDef(name='colonjoin', args=arguments(posonlyargs=[], args=[arg(arg='seq', annotation=Subscript(value=Name(id='Sequence', ctx=Load()), slice=Index(value=Name(id='str', ctx=Load())), ctx=Load()), type_comment=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=[Return(value=Call(func=Attribute(value=Constant(value=':', kind=None), attr='join', ctx=Load()), args=[Name(id='seq', ctx=Load())], keywords=[]))], decorator_list=[], returns=Name(id='str', ctx=Load()), type_comment=None).
Traceback (most recent call last):
  File "./nuitka/__main__.py", line 195, in <module>
    main()
  File "./nuitka/__main__.py", line 188, in main
    MainControl.main()
  File "./nuitka/MainControl.py", line 739, in main
    main_module = createNodeTree(filename=filename)
  File "./nuitka/MainControl.py", line 77, in createNodeTree
    main_module = Building.buildModuleTree(
  File "./nuitka/tree/Building.py", line 1054, in buildModuleTree
    createModuleTree(
  File "./nuitka/tree/Building.py", line 995, in createModuleTree
    module_body = buildParseTree(
  File "./nuitka/tree/Building.py", line 712, in buildParseTree
    result = buildStatementsNode(provider=provider, nodes=body, source_ref=source_ref)
  File "./nuitka/tree/TreeHelpers.py", line 430, in buildStatementsNode
    statements = buildNodeList(provider, nodes, source_ref, allow_none=True)
  File "./nuitka/tree/TreeHelpers.py", line 350, in buildNodeList
    entry = buildNode(provider, node, node_source_ref, allow_none)
  File "./nuitka/tree/TreeHelpers.py", line 311, in buildNode
    result = build_nodes_args3[kind](
  File "./nuitka/tree/ReformulationFunctionStatements.py", line 230, in buildFunctionNode
    annotations = buildParameterAnnotations(provider, node, source_ref)
  File "./nuitka/tree/ReformulationFunctionStatements.py", line 491, in buildParameterAnnotations
    extractArgAnnotation(arg)
  File "./nuitka/tree/ReformulationFunctionStatements.py", line 478, in extractArgAnnotation
    value=buildAnnotationNode(provider, arg.annotation, source_ref),
  File "./nuitka/tree/TreeHelpers.py", line 384, in buildAnnotationNode
    exec(r, m)
  File "<annotations>", line 5, in <module>
NameError: name 'Sequence' is not defined
```

**Comment by kayhayen** [comment]
Thanks for your report, this should hopefully be easy. Unfortunately some `exec` is needed for this, until Python adds the method to do it. I need to check, if that's not the case yet.

**Comment by kayhayen** [comment]
Ah, it's in Python 3.9 only, so I guess, I am adding something to the code, to remind me of that, once it's released.

**Comment by kayhayen** [comment]
I am going to make a star import from `typing` for the exec, but it's not too general. However, what's string, is that I didn't reproduce the issue now.

**Comment by kayhayen** [comment]
I am simply getting this:

> python3.8 bin/nuitka-run Mini.py 
> {'seq': 'Sequence[str]', 'return': 'str'}

for this program:

```
from __future__ import annotations

from typing import Sequence

def colonjoin(seq: Sequence[str]) -> str:
    return ":".join(seq)

print(colonjoin.__annotations__)
```

**Comment by kayhayen** [comment]
I wonder, if this could really be about the minor 3.8 version, other than that I am confused. In my WSL Debian Buster, I have this self compiled 3.8.0 and you got Debian's 3.8.3, for which there is extra option of Debian backports. I will try 3.8.3 once I can.

**Comment by kayhayen** [comment]
Oh shoot, I just read the changelog, and this is what truly happens:

https://bugs.python.org/issue39562

The renumbered the future flags, and I was lazy in this branch, and just used the numerical value, that heaven knows, I got it from:

```
        r = compile(_host_node, "<annotations>", "exec", 1048576, dont_inherit=True)
```

A comment deemed it unlikely for this to happen, therefore they didn't follow the safe route. No idea, where I took the number from, and why, obviously it would have been better to just add up to flags. My git repo makes this surface all at once. But I can re-construct the actual flags of course.

**Comment by kayhayen** [comment]
Ah, this is the value of `__future__.CO_FUTURE_ANNOTATIONS` only.

**Comment by kayhayen** [comment]
A fix should be coming soon, this is simple them. I guess, I wanted to avoid the import of the module at the time, thinking they don't change, as C code is allows to use them, but probably that's too optimistic with the CPython community. For experimental features, they rightfully are ruthless.

**Comment by kayhayen** [comment]
This should be fixed on factory https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
This is part of 0.6.8.2 release that was just done.
