### ISSUE TITLE
keyring module compatibility, pt 2

### ISSUE THREAD

**Issue by lowlyocean** [Nuitka/Nuitka#711]
Raising this one as a separate issue from #710, because applying a hacky workaround by forking importlib_metadata and patching it as described in option 3 described [here](https://gitlab.com/python-devs/importlib_metadata/-/issues/71#note_185285054) allows the program to run but still results in a subsequent error:

![image](https://user-images.githubusercontent.com/13685818/82130067-fd12a400-9795-11ea-9cee-d74107f5c861.png)

So then as suggested by https://github.com/jaraco/keyring/issues/324 when I make the commented modifications to the repro in #710 emphasized below, I get another error:
```python
#!python3
# -*- coding: utf-8 -*-

import keyring
from keyring.backends import Windows  # this line is new
import traceback

from tkinter import Tk
from tkinter.messagebox import showerror, showinfo
from tkinter.simpledialog import askstring


def main():

    root = Tk()
    root.withdraw()

    keyring.set_keyring(Windows.WinVaultKeyring())   # this line is new
    user = askstring('repro', 'Username')
    pw = askstring('repro', 'Password')
    keyring.set_password('repro', user, pw)
    pw_fetched = keyring.get_password('repro', user)
    showinfo('repro', pw_fetched)


if __name__ == "__main__":
    try:
        main()
    except:
        showerror('repro', traceback.format_exc())
```
![image](https://user-images.githubusercontent.com/13685818/82130164-da34bf80-9796-11ea-874e-efa95fd9ff3d.png)

**Comment by kayhayen** [comment]
I don't care really about workarounds. Obviously the packages should be defined. I think what you have here, might be things, that you can add to nuitka ImplicitImports plugin. 

A pull request adding them would be welcome, even if not immediately useful.

**Comment by lowlyocean** [comment]
After struggling a bit, sharing my results with future visitors to this issue:

- keyring module prefers pywin32-cytpes and fallsback to pywin32
- If you pip install pywin32 from Python 3.7, and then pass flag to Nuitka: `--include-module="win32timezone"` it seems to work
- However Python 3.8 will fail with last screenshot above, even if passing the include-module flag

**Comment by kayhayen** [comment]
I am closing this as invalid, as it's unclear what the issue really is, without the other one fixed first.
