### ISSUE TITLE
Some system locals can cause UnicodeDecodeError with unicode path on Python3

### ISSUE THREAD

**Issue by MKdays** [Nuitka/Nuitka#712]
Hi!
I googled, but I couldn't find the answer, can you help me?

> nuitka 0.6.8.1
> Python 3.8.2
> Windows 10 x86

## Python Script
`print("Hello World")
`
## Nuitka Script
`python -m nuitka --standalone "nui_report.py"
`
## Result
```
C:\Users\MK\Desktop\Py\nui_report\nui_report.dist\nui_report.exe
Hello World
```

An error occurs when I change the "path name" with the executable file to Korean.
(no change any script)
(while Pyinstaller works well any condition)
```
C:\Users\MK\Desktop\Py\nui_report\한글\nui_report.exe
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 41: invalid continuation byte
```
While Pyinstaller works well any condition.

**Comment by kayhayen** [comment]
This is supposed to have been solved a while ago, with Nuitka using short path names for everything. I wonder why it's complaining about UTF8, that's not what Korean uses, right?

**Comment by kayhayen** [comment]
So, I just tested it again. In fact, I recall making corrections for looking up dependencies inside such a folder, compiling with scons inside of such a folder, and for running inside such a folder.

Also I had no trouble here. I wonder if you are doing anything different. I pasted your folder name, and it's fine for me. I believe, it might be due to this function:

>    int res2 = WideCharToMultiByte(CP_UTF8, 0, path2, -1, path, MAXPATHLEN + 1, NULL, NULL);

Can you execute Nuitka compilation with `--debug` and repeat, it should reveal if this is the function that failed, or any other for that matter.

**Comment by kayhayen** [comment]
And if you find this in Nuitka source, change it to use `CP_ACP` instead of `CP_UTF8`. It may be the case, that on your system, the `ACP` is not what it is on my machine. Technically it shouldn't really talk about UTF8 decoding, unless it's Python itself, which it looks like it is though.

**Comment by kayhayen** [comment]
Ok, this is the code I suspect now:

```
// On Python3, this must be a unicode object, it cannot be on Python2,
// there e.g. code objects expect Python2 strings.
#if PYTHON_VERSION >= 300
    binary_directory = PyUnicode_DecodeFSDefault(getBinaryDirectoryHostEncoded());
#else
    binary_directory = PyString_FromString(getBinaryDirectoryHostEncoded());
#endif

    if (unlikely(binary_directory == NULL)) {
        PyErr_Print();
        abort();
    }
```

Find it in `CompiledCodeHelpers.c` and put an `assert(false)` right before the abort. That should trigger. I believe `PyUnicode_DecodeFSDefault` might be something different on your system, and potentially be very wrong. I remember I got that idea from Python source code, but probably it's wrong.

Also, I think, on Windows, we get `getBinaryDirectoryWideChars` in that function, and could use it, to create a perfect unicode value from there, without ever going to any other encoding. That is (on Windows) just unoptimal, where on the Linuxes and alikes, it's still needed. 

Please provide feedback on the test requested, but I guess, I am going to do these cleanups, so Win32 doesn't use this function.

**Comment by kayhayen** [comment]
@deajan notice this one, seems Korean works only on some systems after all

**Comment by kayhayen** [comment]
Check out https://nuitka.net/doc/factory.html where we don't use the `char *` for binary directory on Windows at all anymore. That should avoid errors in the conversion back and forth entirely. While it's still unclear what causes your issue, it couldn't be that anymore.

**Comment by MKdays** [comment]
I added "assert(false)" right before the "abort" and tested it in several languages.

```
// On Python3, this must be a unicode object, it cannot be on Python2,
// there e.g. code objects expect Python2 strings.
#if PYTHON_VERSION >= 300
    binary_directory = PyUnicode_DecodeFSDefault(getBinaryDirectoryHostEncoded());
#else
    binary_directory = PyString_FromString(getBinaryDirectoryHostEncoded());
#endif

    if (unlikely(binary_directory == NULL)) {
        PyErr_Print();
	assert(false);
        abort();
    }

```
### test1
C:\Users\MK>C:\Users\MK\Desktop\Py\nui_report\nui_report.dist\nui_report.exe
Hello World

### test2 : failed
C:\Users\MK>C:\Users\MK\Desktop\Py\nui_report\한글\nui_report.exe
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 32: invalid continuation byte
Assertion failed!

Program: C:\Users\MK\Desktop\Py\nui_report\\nui_report.exe
File: static_src\CompiledCodeHelpers.c, Line 1875

Expression: false

### test3
C:\Users\MK>C:\Users\MK\Desktop\Py\nui_report\kärlek\nui_report.exe
Hello World

### test4
C:\Users\MK>C:\Users\MK\Desktop\Py\nui_report\प्रेम\nui_report.exe
Hello World

### test5  : failed
C:\Users\MK>C:\Users\MK\Desktop\Py\nui_report\あい\nui_report.exe
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaa in position 32: invalid start byte
Assertion failed!

Program: C:\Users\MK\Desktop\Py\nui_report\\nui_report.exe
File: static_src\CompiledCodeHelpers.c, Line 1875

Expression: false

😂

**Comment by MKdays** [comment]
I rolled back to the Nuitka version 0.6.7 and the related error disappeared.

```
C:\Users\MK\Desktop\Nuitka-0.6.7>nuitka --version
0.6.7
Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)]
Executable: C:\Python\python.exe
OS: Windows
Arch: x86

C:\Users\MK\Desktop\Nuitka-0.6.7>C:\Users\MK\Desktop\Py\nui_report\nui_report.dist\nui_report.exe
Hello World

C:\Users\MK\Desktop\Nuitka-0.6.7>C:\Users\MK\Desktop\Py\nui_report\한글\nui_report.exe
Hello World
```

**Comment by kayhayen** [comment]
Many of the improvements for unicode paths first surface in 0.6.8 and should be very good step forward, but apparently not in your case as you demonstrate, not in all cases. Can you try out the factory version, I believe it ought to be working in all cases. 

I removed the need to go through UTF8 for that function, so this ought to work for all. If you were so kind, trying all the languages would be so nice!

**Comment by kayhayen** [comment]
For the record, I had forgotten to push factory, so please use the one from now. Sorry for any confusion.

**Comment by MKdays** [comment]
```
Installed c:\python\lib\site-packages\nuitka-0.6.9rc2-py3.8.egg
Processing dependencies for Nuitka==0.6.9rc2
Finished processing dependencies for Nuitka==0.6.9rc2

C:\Users\MK\Desktop\Nuitka-factory>nuitka --version
0.6.9rc2
Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)]
Executable: C:\Python\python.exe
OS: Windows
Arch: x86

C:\Users\MK\Desktop\Nuitka-factory>C:\Users\MK\Desktop\Py\nui_report\nui_report.dist\nui_report.exe
Hello World

C:\Users\MK\Desktop\Nuitka-factory>C:\Users\MK\Desktop\Py\nui_report\한글\nui_report.exe
Hello World

C:\Users\MK\Desktop\Nuitka-factory>C:\Users\MK\Desktop\Py\nui_report\kärlek\nui_report.exe
Hello World

C:\Users\MK\Desktop\Nuitka-factory>C:\Users\MK\Desktop\Py\nui_report\प्रेम\nui_report.exe
Hello World

C:\Users\MK\Desktop\Nuitka-factory>C:\Users\MK\Desktop\Py\nui_report\あい\nui_report.exe
Hello World

C:\Users\MK\Desktop\Nuitka-factory>C:\Users\MK\Desktop\Py\nui_report\◇♠♬\nui_report.exe
Hello World

C:\Users\MK\Desktop\Nuitka-factory>C:\Users\MK\Desktop\Py\nui_report\今日\nui_report.exe
Hello World
```
Today's factory version is OK!

**Comment by kayhayen** [comment]
Thanks for your feedback, this will soon be in a pre-release or hotfix, depending on how daring I am, since you said it's a regression, that might be justified.

**Comment by ffeenn** [comment]
Hi!
I also encountered this problem in my use.

》》》》》》》》》》》》》
D:\cond.bak\cond\pyqt\szydir\综合工具\taobao\load>python hello.py
Talk Hello World

D:\cond.bak\cond\pyqt\szydir\综合工具\taobao\load>python -m nuitka --standalone
--mingw64 hello.py

D:\cond.bak\cond\pyqt\szydir\综合工具\taobao\load>D:\cond.bak\cond\pyqt\szydir\
综合工具\taobao\load\hello.dist\hello.exe
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd7 in position 29: invalid
 continuation byte

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

D:\cond.bak\cond\pyqt\szydir\综合工具\taobao\load>python -m nuitka --version
0.6.9rc2                                e
Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit
 (AMD64)]
Executable: D:\Python\Python37\python.exe
OS: Windows
Arch: x86_64
》》》》》》》》》》》》》》》》》》》》
The Windows operating system is in Chinese #

**Comment by kayhayen** [comment]
@ffeenn are you saying this is with develop or factory? Unfortunately I can't tell from the version string, the later ought to be good.

**Comment by ffeenn** [comment]
> @ffeenn are you saying this is with develop or factory? Unfortunately I can't tell from the version string, the later ought to be good.

The development branch is used, the error is the same as above, there is no problem to use version 0.6.7, the above classmate's error has been fixed, you have not submitted it?

**Comment by kayhayen** [comment]
I tend to put things on factory through testing, so that I e.g. discover that it didn't work for Python2 on Windows anymore, and only make a pre-release once I feel it should be good.

**Comment by kayhayen** [comment]
This is part of 0.6.8.2 release that was just done.
