### ISSUE TITLE
how to import py files capsule to exe file 

### ISSUE THREAD

**Issue by BlackRouter** [Nuitka/Nuitka#714]
0.6.8.1
Python: 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 09:44:33) [MSC v.1900 32 bit (Intel)]
Executable: C:\Users\Moein\AppData\Local\Programs\Python\Python37-32\python.exe
OS: Windows
Arch: x86

i create project capsule and import 2 py file to project!
How to use switch add import files to standalone exe file?

`nuitka sync.py --show-progress --recurse-all --standalone`

please see screenshot!

![2020-05-20_152922](https://user-images.githubusercontent.com/15177510/82438830-e7abbb80-9aae-11ea-9c23-ded0c46d36fe.jpg)

**Comment by kayhayen** [comment]
Is the `sync.py` available at compile time, is it imported by the original files?

**Comment by BlackRouter** [comment]
> Is the `sync.py` available at compile time, is it imported by the original files?

`sync.py `is main file and` bucket.py , mega_thing.py` is modules for import .
how to compile this modules with main?

**Comment by kayhayen** [comment]
There is no issue described here, please refer to the user manual and `--help` output, or describe the symptons and provide an example.
