### ISSUE TITLE
error missing 1 required positional argument: 'qt_plugins'

### ISSUE THREAD

**Issue by BlackRouter** [Nuitka/Nuitka#715]
```
0.6.8.1
Python: 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 09:44:33) [MSC v.1900 32 bit (Intel)]
Executable: C:\Users\Moein\AppData\Local\Programs\Python\Python37-32\python.exe
OS: Windows
Arch: x86
```

i want compile source with included pyqt5 , i get error on compile:

`nuitka main.py --show-progress --recurse-all --standalone --enable-plugin=qt-plugins=sensible,styles --windows-disable-console`

> Traceback (most recent call last):
>   File "C:\Users\Moein\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nuitka\__main__.py", line 195, in <module>
>     main()
>   File "C:\Users\Moein\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nuitka\__main__.py", line 160, in main
>     activatePlugins()
>   File "C:\Users\Moein\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nuitka\plugins\Plugins.py", line 543, in activatePlugins
>     _addActivePlugin(plugin_class, args=True)
>   File "C:\Users\Moein\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nuitka\plugins\Plugins.py", line 70, in _addActivePlugin
>     plugin_instance = plugin_class(**plugin_args)
> TypeError: __init__() missing 1 required positional argument: 'qt_plugins'

**Comment by byehack** [comment]
دیوث اخر اون 200دلارو ندادی

**Comment by byehack** [comment]
> i want compile source with included pyqt5 , i get error on compile:

با پای اینستالر بزن. هوک هاش میتونن. این هوک نداره برای این

**Comment by kayhayen** [comment]
Arguments passing to plugins has changed in 0.6.8, and is no longer done in that option argument, but with separate options, that you will discover if you do `python -m nuitka --plugin-enable=qt-plugins --help`

**Comment by BlackRouter** [comment]
> Arguments passing to plugins has changed in 0.6.8, and is no longer done in that option argument, but with separate options, that you will discover if you do `python -m nuitka --plugin-enable=qt-plugins --help`

i have problem with new switch qt plugins:

```
  Plugin qt-plugins:
    --include-qt-plugins=QT_PLUGINS
                        Which Qt plugins to include. These can be big with
                        dependencies, so by default only the sensible ones are
                        included, but you can also put "all" or list them
                        individually. If you specify something that does not
                        exist, a list of all available will be given.
```

`--include-qt-plugins=all` not work!

please help for qt plugins with all dependencies
