### ISSUE TITLE
Question: It seems that application packaged all python source code. Is it correct?

### ISSUE THREAD

**Issue by marsprobe** [Nuitka/Nuitka#718]
Nuitka: 0.6.8.1
Python: 3.6.8
OS: Windows
Arch: x86_64

I create an application using the below command:
`python -m nuitka --follow-imports --python-arch=x86_64   --plugin-enable=qt-plugins --plugin-enable=numpy --show-progress --show-modules  entry.py`

entry.exe in entry.dist is created and run. But it is about 30M. When I open entry.exe using a text editor, I see my python module code, and even numpy code in entry.exe. Is it correct? And how to remove the code?

Should I use package mode if I want to protect my python code?

Thanks a lot.

**Comment by byehack** [comment]
you can use `pipenv` to prevent include other unusable modules.

**Comment by marsprobe** [comment]
@byehack Thank you for your reply. 

Do you mean that my python code will be packed into exe file if using --standalone mode?

Do I need to compile packages to dynamic shared libraries If I want to protect my python code?

**Comment by kayhayen** [comment]
Function names, variable names,  etc. are all going to be there, to raise compatible exceptions, have compatible dictionaries in modules, classes, etc. but no code. The former will be improved with Nuitka-commercial only, where I expect to add obfuscation for data and incompatibility for names. The later is already "good".

For standard library, in standalone mode, bytecode objects are included. They are not too secret.
