### ISSUE TITLE
Make Nuitka the best.

### ISSUE THREAD

**Issue by byehack** [Nuitka/Nuitka#721]
my ideas for having the best convertor:
(these are discussed before, but it's been a long time)
(i think all of them possible to do with hardwork!)

1. add option to choose what modules and scripts should convert to C.
2. add option to OneFile. not just like pyinstaller, winrarSFX, 7zSFX, or any SFX. you should load ".pyd"and ".dll" files from memory. as i know this is possible. like `pymemimporter`, `pymemorymodule` and [MemoryModule](https://github.com/fancycode/MemoryModule)
3. make the apps with decrease the size. use popular zipping methods. like `lzma`

after do these i'm sure `Nutika` will be used instead of `pyinstaller`, `py2exe` or any other converters.

**Comment by kayhayen** [comment]
For 1 there is an issue, for 2 there is an issue too. And 3 is solved in the Nuitka-utils repo, or so.

Issues referencing multiple things at once are not helpful. Code changes that actually perform the things are better.

I appreciate the enthusiasm. It's not that we don't know what you want us to do. It's that it takes somebody to do it.

**Comment by byehack** [comment]
what is the issue about 2?
now there are some projects in github in both of python and C for load pyd, dll and exe.

**Comment by kayhayen** [comment]
Then you want to contribute to #230 apparently.
