### ISSUE TITLE
Numpy plugin: "TypeError: __init__() missing 2 required positional arguments: 'matplotlib' and 'scipy'"

### ISSUE THREAD

**Issue by OliverCWY** [Nuitka/Nuitka#722]
When I was testing Nuitka with numpy, I encountered the following error:
```
Traceback (most recent call last):
  File "C:\Users\OliverCWY\.conda\envs\test\lib\site-packages\nuitka\__main__.py", line 195, in <module>
    main()
  File "C:\Users\OliverCWY\.conda\envs\test\lib\site-packages\nuitka\__main__.py", line 160, in main
    activatePlugins()
  File "C:\Users\OliverCWY\.conda\envs\test\lib\site-packages\nuitka\plugins\Plugins.py", line 564, in activatePlugins
    _addActivePlugin(plugin_class, args=True)
  File "C:\Users\OliverCWY\.conda\envs\test\lib\site-packages\nuitka\plugins\Plugins.py", line 70, in _addActivePlugin
    plugin_instance = plugin_class(**plugin_args)
TypeError: __init__() missing 2 required positional arguments: 'matplotlib' and 'scipy'
```
Environment: ```conda python3.6```(Windows) and ```python3.6```(Linux)
Command: ```nuitka a.py --standalone --mingw64 --remove-output --verbose --enable-plugin=numpy```

**Comment by kayhayen** [comment]
Oh, everything after the first non argument is not treated as nuitka options, which is probably something that should only be done for `nuitka-run`, and probably once was that way.

However, the detection of plugins to enable, done before command line parsing, treats this different, and does enable the plugin, but later, it's not completed, causing this exception.

When you put the filename last it works.

**Comment by kayhayen** [comment]
This is a regression of the last release and will be fixed in 0.6.8.3 soon.

**Comment by OliverCWY** [comment]
Thank you for your reply. It indeed worked.

**Comment by kayhayen** [comment]
Keeping issues open until code changes are released.

**Comment by kayhayen** [comment]
The fix is on factory, and currently undergoing CI testing.

**Comment by kayhayen** [comment]
This was release as part of 0.6.8.3 hotfix.
