### ISSUE TITLE
Detect 32 bit MSVC compiler on 64 bit Python

### ISSUE THREAD

**Issue by taurusai** [Nuitka/Nuitka#731]
With nuitka 0.6.8.3 I can not compile with correct msvc arch:

> C:\kungfu\core>pipenv run python -m nuitka  --standalone --follow-imports python/kungfu/__main__.py
> scons: warning: MSVC_USE_SCRIPT set to False, assuming environment set correctly.
> File "C:\Users\dkr\VIRTUA~1\CORE-F~1\lib\SITE-P~1\nuitka\build\SINGLE~1.SCO", line 532, in createEnvironment
> Error, mismatch between Python binary ('C:\Users\dkr\.virtualenvs\core-feNv3oGK\Scripts\python.exe' -> 'pei-x86-64') and C compiler ('C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\bin\HostX86\x86\cl.exe' -> 'pei-i386') arches.

My environment is:

> C:\kungfu\core>pipenv run python -m nuitka --version
> 0.6.8.3
> Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
> Executable: C:\Users\dkr\.virtualenvs\core-feNv3oGK\Scripts\python.exe
> OS: Windows
> Arch: x86_64

From the comments of [Issue #225](https://github.com/Nuitka/Nuitka/issues/225) I see this seems to be fixed, but still not working.

**Comment by kayhayen** [comment]
For what definition of correctness are you talking? Your Python version says it's 64 bits, and your compile binary path says 32 bits. That is exactly what this is supposed to find. Simply don't use a MSVC environment, then Nuitka will pick up the correct one, or alternatively know what you are supposed to do and use the correct one. 

The checks caught you, which is good news to me, demonstrating their usefulness. But what made you convinced it's otherwise?

**Comment by taurusai** [comment]
Unfortunately I have to use the MSVC environment in my project which relates to many other stuff like cmake, Node.js, etc. It would be great if Nuitka can provide an argument like --mingw64 to force MSVC to use 64bit arch.

**Comment by taurusai** [comment]
My work has addons (written in C++) to both Python and Node.js, so I use cmake-js to build C++ sources and then pybind11 to make Python bindings. With cmake-js it can automatically pick the right arch with Visual Studio 2019 MSVC environment. I am fine to use some arguments to specify the MSVC arch if exist, right now it is just no way to me to get it going.
