### ISSUE TITLE
Question: Why is the .dist folder very large

### ISSUE THREAD

**Issue by italorecife** [Nuitka/Nuitka#739]
compiled with: python -m nuitka --plugin-enable=numpy --plugin-enable=qt-plugins --mingw64 --standalone --follow-imports --recurse-all teste.py --show-progress --show-scons

folder very large: 754 MB

print: https://prnt.sc/stnvgn

code py:
```
from PIL import Image
from python_imagesearch.imagesearch import imagesearch
import pyautogui
import os
import numpy
print(numpy.__version__)

pos = imagesearch('./p1.png')
if pos[0] != -1:
    print("position : ", pos[0], pos[1])
    pyautogui.moveTo(pos[0]+Image.open('./p1.png').size[0]/2,pos[1]+Image.open('./p1.png').size[1]/2)
else:
    print("image not found")
os.system('pause')
```

**Comment by kayhayen** [comment]
That's a lot of code behind the imports. Not sure if pyautogui also includes multiple UIs. You can try removing qt plugins though, by trying to use only the ones you need.

Also the numpy plugin, if you don't need it, adds a lot of stuff.

That's all there is to say really.

**Comment by italorecife** [comment]
I removed the plugins qt, but still with the same size, I hope you launch the optimized utils updated soon
