### ISSUE TITLE
Nuitka and win32api with standalone (pywin32)

### ISSUE THREAD

**Issue by katant** [Nuitka/Nuitka#740]
Nuitka: 0.6.9rc4 (tested on factory and develop branches)
Python: 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]
Executable: C:\Program Files\Python38\python.exe
OS: Windows
Arch: x86_64
pywin32: 227

If you use _import win32api_ with --standalone, app will throw error:
```
Traceback (most recent call last):
  File "C:\Users\Katant\Desktop\TEST~1.DIS\test.py", line 1, in <module>
ImportError
```
And without --standalone, it works fine.

Minimal code to reproduce:
```
import win32api
```

**Comment by kayhayen** [comment]
You didn't share your exact command lines, I am suspecting you are using a Python with Nuitka that doesn't have it installed.

**Comment by katant** [comment]
Yes, it works even if you compile it without --standalone

**Comment by kayhayen** [comment]
Ok, reason I am asking is because I recall that I recently fixed a detail for one of those, but that was `win32com` it seems, and I might be confusing two different things here.

**Comment by katant** [comment]
win32com works fine with --standalone, but win32api don't

**Comment by kayhayen** [comment]
I am going to hide my stupid questions, I managed to reproduce it. Quite surprising to learn this is not working though.

**Comment by kayhayen** [comment]
This might be a regression. The `win32api.pyd` is there, and Nuitka when trying to load it, claims that `LoadLibraryExW` failed.

**Comment by kayhayen** [comment]
So, this just needs the same DLLs as does `pythoncom`, probably even more top level imports trigger that, but hard to tell. Going to cover this one though.

Definitely not a regression, apparently this has never worked in that form, but if you e.g. had win32com imported somewhere, it would have worked. Maybe that is why it wasn't reported yet.

Anyway, the next hotfix is going to get this, very low impact.

**Comment by kayhayen** [comment]
This is part of the 0.6.8.4 release I just made.
