### ISSUE TITLE
Question: Why is python path missing packages when binary moved onto another system

### ISSUE THREAD

**Issue by andy-brainome** [Nuitka/Nuitka#741]
Before submitting an Issue, please review the [Issue Guidelines](https://github.com/kayhayen/Nuitka/blob/master/CONTRIBUTING.md#submitting-an-issue).

* Please check whether the bug was already reported or fixed.

* Please check out if the develop version of Nuitka works better for you.

  Download source, packages [from here](http://nuitka.net/pages/download.html)
  where you will also find instructions how to do it via PyPI.

If you want to post a problem/bug, to help us understand and resolve your issue
please check that you have provided at least the information below, and discard
up to here:

* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

  python -m nuitka --version
    **0.6.8.2**

* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.
**python3 -m pip install -r requirement.txt**

* Many times when you get an error from Nuitka, your setup may be so special
  that even a "hello world" program will not work, please try that and report
  it instead.
**The python sys.path is incomplete when running the binary on a machine other than the one it was built on.
The error manifests as missing modules or other missing code.**
e.g. 
~/bin$ ./adduser
Traceback (most recent call last):
  File "/home/runner/work/mlmeter/mlmeter/srv/src/adduser.py", line 23, in <module>
ModuleNotFoundError: No module named 'passlib'
~/bin$
---
The error occurs when a bin is copied from the build machine to a deployment machine.
Build Machine Native Build
Python 3.6.10
['/home/runner/work/pythonenv/pythonenv', '/opt/hostedtoolcache/Python/3.6.10/x64/lib/python36.zip', '/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6', '/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/lib-dynload', '/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages']

Build Machine using Nuitka binary 
['/home/runner/work/pythonenv/pythonenv', '/opt/hostedtoolcache/Python/3.6.10/x64/lib/python36.zip', '/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6', '/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/lib-dynload', '/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages']

On a docker container
0.6.8.2
Python: 3.6.10 (default, May 20 2020, 21:54:39)
Executable: /usr/local/bin/python3
OS: Linux
Arch: x86_64
native system path: ['/sys-path-docker', '/usr/local/lib/python36.zip', '/usr/local/lib/python3.6', '/usr/local/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/site-packages']
_nuitka system path: ['/sys-path-docker', '/usr/local/lib/python36.zip', '/usr/local/lib/python3.6', '/usr/local/lib/python3.6/lib-dynload']_

MISSING os.path '/usr/local/lib/python3.6/site-packages'
---
Workaround: Manually create the pythonpath to include the missing element.
export PYTHONPATH=/usr/local/lib/python3.6/site-packages

* If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
  that demonstrates the issue i.e a small piece of code which reproduces
  the issue and can be run with out any other (or as few as possible)
  external dependencies.

Fully contained reproduction within this repos 
**https://github.com/brainome/pythonenv**

* If this is a regression (used to work in an earlier version of Nuitka),
  please note what you know about that.
this is my first time with Nuitka

**Comment by kayhayen** [comment]
Moving to another machine is only supported for standalone mode. For acceleration, it's supposed to be an identical installation, or same machine. If you build inside that container and still experience the issue, you have a point. Otherwise, hell knows what the `site.py` of your system is doing in that container and calls itself clever.
