### ISSUE TITLE
Question: Can i compile project in linux and use on other Distribution Linux 

### ISSUE THREAD

**Issue by BlackRouter** [Nuitka/Nuitka#745]
```
0.6.8.3
Python: 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 09:44:33) [MSC v.1900 32 bit (Intel)]
Executable: C:\Users\Moein\AppData\Local\Programs\Python\Python37-32\python.exe
OS: Windows
Arch: x86
```

can i compile from my project in Ubuntu and use compiled on other Distribution Linux ( ex cent os )?

**Comment by kayhayen** [comment]
Yes, that is possible, however newer glibc often doesn't run on older kernels. Therefore, you need to build on the oldest Debian or Ubuntu that you want it to run on. Going forward is not a problem, but going backward is. 

That should be described in the user manual, but it currently is not: https://nuitka.net/doc/user-manual.html
