### ISSUE TITLE
AtrributeError: type object 'type' has no attribute '__signature__' in modeuls PySide2

### ISSUE THREAD

**Issue by dougwood** [Nuitka/Nuitka#746]
Hi All,
I am brand new to Nuitka so apologies if this is a FAQ but I would not find it mentioned.
I have a fairly complex app with many modules, one of which is PySide2.  Yet Nuitka, with the following command:

python -m nuitka --show-progress --follow-imports --standalone --plugin-enable=numpy app.py

I was able to run successfully and create a .dist folder (something I have not been able to get PyInstaller to do).  But when I try to run the .exe in the .dist folder in a command window (so I can see the output) I get the following:

Traceback (most recent call last):
  File ...path to .dist\app.py , line 2, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File ...path to app.dist>\PySide2\__init__.py", line 88, in <module PySide2>
  File ...path to app.dist>\PySide2\__init__.py", line 62, in _setupQtDirectories
AttributeError: type object 'type' has no attribute '__signature__'

I find, BTW, that running without --standalone that Nuitka will create a .exe that will launch and display the PySide2 GUI main window, but when I click on buttons to execute some Qt slots the app hangs - -that is why I was trying --standalone (I would also like a standalone binary if possible).

Any suggestions?  Did I miss something?  Is PySide2 5.15.0 supported?

**Comment by JorjMcKie** [comment]
Nuitka does not support PySide. There are several issues referring to this topic.

**Comment by kayhayen** [comment]
Somebody needs to get changes into PySide2 to support Nuitka.

**Comment by salembream** [comment]
@kayhayen 
Hi,
Is this the required patch?
https://code.qt.io/cgit/pyside/pyside-setup.git/commit/?h=5.15&id=2bd69b9877f7b240512f03b4df042adf9acea744

https://codereview.qt-project.org/c/pyside/pyside-setup/+/312657

**Comment by kayhayen** [comment]
Actually PySide2 has integrated the patch. I have not yet had the time to test it out myself, but they solved that with a workaround for now and integrated our original patch. Not entirely sure what the status is though, but it might be in their stable release?

**Comment by kayhayen** [comment]
So, removing the unsupported tag, I will need to check this out myself though, before publicly changing the stance there. But it might be the case that it's working better than PyQt5 eventually.

**Comment by kayhayen** [comment]
I checked it out, and it's somewhat working with current stable, but will be only really good after https://bugreports.qt.io/browse/PYSIDE-1523 gets merged.
