### ISSUE TITLE
chrpath existence should be checked  at the start of compilation

### ISSUE THREAD

**Issue by rudy-sicard-coservit** [Nuitka/Nuitka#747]
When doing a long compilation on a new VM, I can be frustated to have an error just at the end, because 'chrpath' is not installed.
Use case:
```
NUITKA v0.6.8.3 on Python 3.7.7 (linux) is compiling 'XXX/YYY.py' with these options:
 --standalone
 --recurse-none
 --hinted-json-file=XXX/YYY-37-linux-64.json
```
The error message is:
```
Error, needs 'chrpath' on your system, due to 'RPATH' settings in used shared
libraries that need to be removed.
```
Given that Nuitka has long compilation time, the presence of chrpath may be checked at start.

**Comment by kayhayen** [comment]
No, `chrpath` is not normally needed. Is is only used when libraries that are compiled with it are encountered, on most OSes, esp sane ones, that is not the case. So we won't force the installation of a tool that is likely unused.

**Comment by ABD-Z** [comment]
Sorry to write this after its closure, but i just have this error suddenly.
Nuitka was working just fine with me till now. I have exactly the same error, the difference is that  i'm not on VM and I use Python3.9 and the newest develop branch of nuitka.
So what is the solution to get rid of the error? I can't figure it out.
