### ISSUE TITLE
asyncio completed tasks stay in memory

### ISSUE THREAD

**Issue by levesquejf** [Nuitka/Nuitka#748]
I have an issue with some asyncio code when compiled with Nuitka that is not present with native python. In some cases, when a task is completed, it stays in `asyncio.Task.all_tasks()`. When running for a few hours/days (which is the case with a daemon), it can be hundreds of tasks.

I have a reproducer at https://github.com/levesquejf/nuitka-asyncio-done-tasks-not-removed.

I tested with Nuitka 0.6.8.3 and Python 3.8.3.

**Comment by Aanok** [comment]
I'm experiencing the same bug, the completed tasks and their resources don't get released from memory.

For the moment I'm sticking with 0.6.7, which doesn't exhibit the issue.

**Comment by levesquejf** [comment]
@Aanok You can give a try to 0.6.8.4 as it solves #593 which causes some more important memory leaks, at least for me. These memory leaks are back in 0.6.9.1 (see #851).

**Comment by Aanok** [comment]
@levesquejf Thank you: indeed no leaks on 0.6.8.4 but they're back with 0.6.9.1+.

**Comment by kayhayen** [comment]
Just a heads up here, this is on my radar indeed. And since it's a regression, I will aim at fixing it once I biseted it, but that may take some time, as my scalabity and optimization work and currently in flow.

**Comment by kayhayen** [comment]
This is considered solved for a few hotfixes already. I think there was a duplicating going on. Correct me if I am wrong.

**Comment by Aanok** [comment]
Yes! 0.6.10 works fine without any more memory leaks. Thank you for your work :+1:
