### ISSUE TITLE
Differences between No-Console and a Regular Compiled Exe on Windows?

### ISSUE THREAD

**Issue by daniel442li** [Nuitka/Nuitka#749]
Python Version: 3.7.1
OS: Windows

I've been trying to debug a program but it's been hard because whenever I use the --windows-disable-console command, I can't see any output.

For some reason, when I compile my program with the console, everything works but whenever I add the --windows-disable-console command, nothing happens when I double click. This program works fine with the --noconsole command in PyInstaller so I'm not entirely sure why it's not working.

Some possible thoughts I had were that one of my packages, gevent, is not properly loaded but the sizes are the exact same so not super plausible. I also thought that maybe the path directory is different but I've tried adding code to change it with no success.

**Comment by kayhayen** [comment]
So, I am not deep into this. This is basically only a linker option for Windows, and we don't do more, but there might be more to do.

Can you try and find out, e.g. by writing to a file, what sys.stdin, sys.stdout, and sys.stderr are with Nuitka, and PyInstaller in no console mode? Probably there are differences there that I don't know about, but would crash your program. Also trying to catch any exception and write the traceback to a file when running with Nuitka would be good input.

**Comment by byehack** [comment]
with `--windows-disable-console`:
```
Traceback (most recent call last):
  File "C:\x.py", line 3, in <module>
RuntimeError: input(): lost sys.stdin
```

**Comment by kayhayen** [comment]
Are you seriously expecting that `input` should work without a terminal?

Nuitka is compatible with CPython, which always has a console on Windows if I am not mistaken. I don't know or care about PyInstaller, but either your program is using a GUI, or it is not. Although I just made this test:

```
python3 </dev/null -c "input('a')"

a

Traceback (most recent call last):
  File "<string>", line 1, in <module>
EOFError: EOF when reading a line
```

Maybe it's not supposed to give `RuntimeError`, and code can detect that way if there is a console. So that would mean, that is actually a bug. With git bash I can do the same on Windows, and same behaviour. Will try with Nuitka now. It then would mean that we need to setup a stdin for a nul device, which the linker flag doesn't do, probably just no such file.

**Comment by kayhayen** [comment]
So, on Python2 this works as expected, seems it's only Python3 affected.

**Comment by kayhayen** [comment]
So, this was a bit tricky to debug naturally, seems fixing it up beforehands with `freopen("NUL:, "r", stdin)` does nothing or not enough, so instead, we just correct it after Python has initialized itself. But maybe, it was just not covering enough. But this works sufficiently good.

**Comment by kayhayen** [comment]
With not enough, I mean that I found out, that for input, `sys.stdout` and `sys.stderr` needed to be also present, maybe that confused me when trying `freopen`. But maybe it's also just the Python3 new init structures, that recognize the GUI mode and don't do it.

**Comment by kayhayen** [comment]
This might also be hotfix material.

**Comment by kayhayen** [comment]
This was indeed part of a hotfix and the 0.6.10 release too.
