### ISSUE TITLE
what's the correct way of using nuitka

### ISSUE THREAD

**Issue by andrewchenshx** [Nuitka/Nuitka#750]
* Nuitka version,
0.6.8.3
Python: 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
Executable: C:\Users\Andrew\Anaconda3\python.exe
OS: Windows
Arch: x86_64

* How did you install Nuitka and Python 
conda install nuitka

my gui program(my_program.py) imports PyQt5, openpyxl and xlrd. I wish i could compile/package it as a standalone executable so it runs on another computer without python installed.

case 1)
nuitka --standalone --mingw64 --show-memory --show-progress --plugin-enable=qt-plugins --recurse-all --output-dir=out my_program.py
this command does NOT finish in serveral hours.

case 2)
nuitka --nofollow-imports --standalone --mingw64 --show-memory --show-progress --plugin-enable=qt-plugins --recurse-all --output-dir=out my_program.py
this command finishes in less than 1 min, and generate my_program.exe.
however, on executed, there is a ModuleNotFoundError(No module named 'openpyxl') 

case 3)
nuitka --standalone --mingw64 --show-memory --show-progress --plugin-enable=qt-plugins --recurse-all --output-dir=out --include-package=openpyxl my_program.py
command finishes in minutes. 
runtime error: there is a ModuleNotFoundError (a module imported by openpyxl)

**Comment by kayhayen** [comment]
There are scalability problems with Nuitka, that explains case 1. I believe these will improve with future releases, as I am finishing the long awaited scalability work for constants. Case 3 looks very similar though.

The correct way clearly involves reading upon options used. When I see --nofollow-imports being used, in case 2, I am not surprised about modules not being there.

For case 3 I would appreciate a minimal reproducer. Also the --include-package ought to not normally be necessary. These might be hidden dependencies that we need to add to Nuitka, but it's not happening without a reproducer.

**Comment by Torxed** [comment]
I'll add to this post, as a "simple" application using any `GL` libraries gets pretty insane.
I used [this game/library](https://github.com/dark00shadow/Space-Game) as an example and ran `nuitka3 --standalone Game.py`, and it sort of almost compiles. But ends with this:

![2020-07-10-162847_956x120_scrot](https://user-images.githubusercontent.com/861439/87165814-2fcea980-c2ba-11ea-9a27-37c46159d0ec.png)

And this is the resources you need to even get this far, let alone wait for 4 hours or so.

![20200710_162227](https://user-images.githubusercontent.com/861439/87165933-5987d080-c2ba-11ea-8852-845699fb68d1.jpg)

I want to be extremely clear, I am not complaining.
This is probably a bit of a one-off thing to use nuitka for, and I find nuitka to be Amazing for so many things I do like distributing my installer scripts and what not.

But If this feedback helps, I want to give it as I'd love to be able to distribute games etc later on with it.

**Comment by kayhayen** [comment]
Good Linux distributions do not need `chrpath` installed, because `rpath` should not be used, but Nuitka then needs to clean  it and if it's needed becomes only clear later.

Then 100GB seem extreme. 

On factory, there is now code that tells us the times for slow compilations when they end, and informs about them when they become long running.

I guess, I would be interested to know what module causes this. Generated Python code probably.

Yours,
Kay

**Comment by Torxed** [comment]
> Good Linux distributions do not need `chrpath` installed, because `rpath` should not be used, but Nuitka then needs to clean it and if it's needed becomes only clear later.
> 
> Then 100GB seem extreme.
> 
> On factory, there is now code that tells us the times for slow compilations when they end, and informs about them when they become long running.
> 
> I guess, I would be interested to know what module causes this. Generated Python code probably.
> 
> Yours,
> Kay

I'll have to read up some more to know what `chrpath` and `rpath` is. The 100GB is a bit extreme, heh.

It appeared as if there were looping Python optimizations being done, meaning I saw (I think) the same module/code being found recursively and optimized over and over. It seams that the main issue might be PIL, but I can't confirm yet.

The huge RAM usage comes from `scons`, when that stage runs it eats RAM like crazy.

Thanks for a fast response,
//Anton

**Comment by kayhayen** [comment]
That is the C compilation, and one of the generated C files will be to blame, giving the gcc a hard time.

**Comment by Torxed** [comment]
Any way I can help to diagnose or identify it?

**Comment by kayhayen** [comment]
Running with factory will output the slow commands, but factory is getting the constants work that should better it, but will be very likely broken for some time.

**Comment by jafd** [comment]
@Torxed, you can see the generated files in the `program.build` directory. Usually if you sort those files by size, the problematic files will stand out like sore thumbs, the giveaway being their sheer size (had a similar problem, but then again, my program is not as big, and my machine has 64 GiB of RAM so it was bad but not _that_ bad. A `pyasn1` submodule compiled to whopping 12 megabytes of C).

Looking at the compilation with some process monitor like top or htop, or what have you, will point you straight at the difficult file.

The thing about Nuitka is that it generates plain C, there are no crazy or overly clever things in it, like recursive C++ template compilation or worse, so it's usually the code size that is killing the compiler.

(I've noticed that it also compiles with -O3 by default; maybe that is contributing, too.)

**Comment by kayhayen** [comment]
The scalability should be a bit better on develop now, but I think this issue has no clear topic.
