### ISSUE TITLE
"os.add_dll_directory(path)" doesn't work

### ISSUE THREAD

**Issue by MKdays** [Nuitka/Nuitka#751]
## Env
C:\Users\MK>  python -m nuitka --version
0.6.8.3
Python: 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:20:19) [MSC v.1925 32 bit (Intel)]
Executable: C:\Python\python.exe
OS: Windows
Arch: x86

## Python script
```
import os
app_path = os.path.dirname(os.path.abspath(__file__))
try:os.mkdir("%s/Include"%(app_path))
except: pass
os.add_dll_directory("%s/Include"%(app_path)) #this function will add dll_dir

import sys
from PyQt5.QtWidgets import *
class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setFixedSize(300,100)
        self.setWindowTitle("Success")
if __name__ == "__main__":
    app = QApplication(sys.argv)
    myApp = Ui_MainWindow()
    myApp.show()
    sys.exit(app.exec())
```
## Nuitka script
```
python -m nuitka --standalone
--plugin-enable=qt-plugins
--include-qt-plugins=sensible,styles
--remove-output
"test.py"
```
## Run Original Nuitka : OK
![1](https://user-images.githubusercontent.com/64838226/84897987-7aa53900-b0e1-11ea-97cc-b66078799338.JPG)
## Run Nuitka after moved "qt5*.dll" to "\Include" folder : Failed
```
Traceback (most recent call last):
  File "C:\pyscript\TEST~1.NUI\test.py", line 8, in <module>
ImportError
```
![2](https://user-images.githubusercontent.com/64838226/84898002-81cc4700-b0e1-11ea-9b40-1afd61cde78b.JPG)
## Run Pyinstaller after moved "*.dll" to "\Include" folder : OK
![3](https://user-images.githubusercontent.com/64838226/84898027-8a248200-b0e1-11ea-8fe5-2e80b026cb53.JPG)

## So..
"os.add_dll_directory(path)" doesn't work properly as shown in the screenshot.
In the case of Pyinstaller, it worked fine.
Is there a way to use that function with Nuitka?

**Comment by kayhayen** [comment]
The Nuitka loader messes with the DLL directories and sets the search order with `SetDllDirectory` at program start. Not sure how that would influence things.

I wonder, if the PyQt5 plugin is at fault though. 

> Nuitka-Plugins:INFO: qt-plugins: Injecting post-module load code for module 'PyQt5.QtCore':
> Nuitka-Plugins:INFO: qt-plugins:     Setting Qt library path to distribution folder. Need to avoid 
> loading target
> Nuitka-Plugins:INFO: qt-plugins:     system Qt plug-ins, which may be from another Qt version.

That may well reverse anything that PyQt5 would normally pick up, i.e. standard load paths, and that is of course intended. Can you check the plugin code and add your folder there, and report back, if it works then?

This here
```
QCoreApplication.setLibraryPaths(
    [
        os.path.join(
           os.path.dirname(__file__),
           "qt-plugins"
        )
    ]
)
```

hard codes the path of plugins for Qt. Moving them, will make them not found.

Also, can you explain what your intent is here? Do you want the qt plugins to live anywhere else, than Nuitka does, or is this about other DLLs your program is supposed to load? Because making the plugin path would clearly be an option. Not moving them seems reasonable, as they are in a well named folder already.  Not sure why you are doing this.

**Comment by MKdays** [comment]
### Test script
```
import os
import sys
from PyQt5 import QtCore
from PyQt5.QtWidgets import *

QtCore.QCoreApplication.setLibraryPaths(
    [
        os.path.join(
           os.path.dirname(__file__),
           "qt-plugins"
        )
    ]
)

class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setFixedSize(300,100)
        self.setWindowTitle("Success")

if __name__ == "__main__":
    app = QApplication(sys.argv)
    myApp = Ui_MainWindow()
    myApp.show()
    sys.exit(app.exec())
```
But this shows error message.
```
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

### This is the alternative I found.
```
import os
app_path = os.path.dirname(os.path.abspath(__file__))

import ctypes
dll = [file for file in os.listdir(app_path+"\\Include\\") if file.endswith(".dll")]
for i in dll:
    try:ctypes.WinDLL(app_path+"\\Include\\"+i)
    except:pass

import sys
from PyQt5.QtWidgets import *
class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setFixedSize(300,100)
        self.setWindowTitle("Success")

if __name__ == "__main__":
    app = QApplication(sys.argv)
    myApp = Ui_MainWindow()
    myApp.show()
    sys.exit(app.exec())
```
It works well even if I detach the dll file in the specified folder.
![3](https://user-images.githubusercontent.com/64838226/85138664-21264100-b27e-11ea-98a9-dc4cdd50de3a.JPG)

**Comment by MKdays** [comment]
That's why I do this.
When distributing programs, exe was hidden in many library files, making it difficult for people to find executable files. So I intended to separate library files into specific folders.
Now that I have found an alternative, I have solved my problem.

**Comment by MKdays** [comment]
Finally, I found the solution that exactly fits the purpose.
Need to make some changes to the `Mainprogram.c` code.

## Python Script : just a typical script.
```
import sys
from PyQt5.QtWidgets import *
class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setFixedSize(300,100)
        self.setWindowTitle("Success")
if __name__ == "__main__":
    app = QApplication(sys.argv)
    myApp = Ui_MainWindow()
    myApp.show()
    sys.exit(app.exec())
```
## Mainprogram.c
```
#if defined(_WIN32)
    // SetDllDirectoryW(getBinaryDirectoryWideChars()); //this is original.
    SetDllDirectoryW(L"./Include/"); //This has been added.
```
## Result : Success
![123](https://user-images.githubusercontent.com/64838226/85205063-a4659680-b353-11ea-94a0-9bd0f687cf5d.JPG)

**Comment by kayhayen** [comment]
Ok, so the Nuitka plugin has a firm idea of where it wants to tell Qt the plugins live. That could be a sub folder of some sorts indeed, but that would require an option to it, that nobody will really ever benefit from. Maybe we just do one single file implementation, that makes more sense to fiddle around will directory layouts.
