### ISSUE TITLE
Compiling successful for scapy but getting `ImportError: cannot import name 'SCTP'` 

### ISSUE THREAD

**Issue by arussu** [Nuitka/Nuitka#753]
- Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)
$ python3 -m nuitka --version
0.6.8.4
Python: 3.6.8 (default, Apr  2 2020, 13:34:55) 
Executable: /usr/bin/python3
OS: CentOS Linux
Arch: x86_64

-  How did you install Nuitka and Python?
   -- Python: `yum install python3`
   -- Nuitka: `pip install nuitka`

scapy (https://scapy.net/) compiles successfully but at the end can't find the SCTP module.

script:
```python
from scapy.all import SCTP

SCTP()
```

Hinted compilation:
```bash
$ python3 get-hints.py test.py 
Call cleaning has removed 428 items.
$ python3 nuitka-hints.py test.py 
NUITKA v0.6.8.4 on Python 3.6.8 (linux) is compiling 'test.py' with these options:
 --standalone
 --recurse-none
 --show-progress
 --show-scons
 --hinted-json-file=test-36-linux-64.json

Nuitka-Plugins:INFO: hinted-mods: 'hinted-mods' is adding the following options:
Nuitka-Plugins:INFO: hinted-mods: --recurse-to=zlib and 164 more modules
... # lots of lines here
scons: done building targets.
Nuitka-Plugins:INFO: hinted-mods: Compiled 'test.py' in 11 minutes.
```

Test:
```bash
$ ./test.dist/test 
Traceback (most recent call last):
  File "/tmp/mon2pcap/test.dist/test.py", line 1, in <module>
ImportError: cannot import name 'SCTP'
```

Thank you.

**Comment by arussu** [comment]
Hi Kay,

sure, here:
```bash
$ python3 -m nuitka --follow-imports --standalone --show-progress --show-scons test.py 
... # logs logs logs all successful.
scons: done building targets.
```
result:
```bash
$ ./test.dist/test 
Traceback (most recent call last):
  File "/tmp/mon2pcap/test.dist/test.py", line 1, in <module>
ImportError: cannot import name 'SCTP'
```
The same in py3:
```bash
python3 -c "from scapy.all import IP,SCTP; print((IP()/SCTP()).summary())"
127.0.0.1 > 127.0.0.1 sctp / SCTP
```
Thank you.

**Comment by kayhayen** [comment]
I tried this on Windows, and there it fell down with `ImportError: cannot import name 'NPCAP_PATH' from 'scapy.arch.pcapdnet' (unknown location)` it seems to have a need for a plugin package that will update installation paths and copy other software, e.g. npcap, and maybe `SCTP` in your case. The way they treat non-detection of tools seems to be not assigning variables, which then lead to ImportError at run time.

If you are a commercial user, please consider this: https://nuitka.net/pages/commercial.html as otherwise, you need to solve this yourself, but I think it requires my knowledge.

**Comment by Yaroher2442** [comment]
Hi! I have a similar problem `No module named 'scipy.optimize._highs`. Need help to. try: ` python -m nuitka --standalone --follow-imports --plugin-enable=numpy --plugin-enable=torch  cli.py `

**Comment by kayhayen** [comment]
Different issues posted in comments are unlikely to be resolved ever. Create a new issue instead @Yaroher2442
