### ISSUE TITLE
Missing annotation of possible exception for next with 2 arguments led to NuitkaOptimizationError 

### ISSUE THREAD

**Issue by bertbarabas** [Nuitka/Nuitka#755]
The attached exception is raised while running 

python -m nuitka --standalone --follow-imports --plugin-enable=pylint-warnings --mingw64 ../src/interface.py

[error.txt](https://github.com/Nuitka/Nuitka/files/4808215/error.txt)

* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

  python -m nuitka --version

    0.6.8.4
    Python: 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]
    Executable: C:\Projects\Nuitka\.venv\Scripts\python.exe
    OS: Windows
    Arch: x86_64

* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.
  python - from windows installer
  nuitka - from pip

* Many times when you get an error from Nuitka, your setup may be so special
  that even a "hello world" program will not work, please try that and report
  it instead.

   helloworld program compiles fine.

**Comment by kayhayen** [comment]
This is on the factory branch http://nuitka.net/doc/factory.html

**Comment by bertbarabas** [comment]
This exception no longer appears in my build and the compilation now completes without errors.

**Comment by kayhayen** [comment]
We close issues when they are released as stable.

**Comment by kayhayen** [comment]
Part of the latest pre-release.

**Comment by kayhayen** [comment]
This is the last release 0.6.9 already for a while.
