### ISSUE TITLE
Question for pyd library use in project for compile as module

### ISSUE THREAD

**Issue by BlackRouter** [Nuitka/Nuitka#757]
```
0.6.8.4
Python: 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:20:19) [MSC v.1925 32 bit (Intel)]
Executable: C:\Users\Ja7ad\AppData\Local\Programs\Python\Python38-32\python.exe
OS: Windows
Arch: x86
```
i use pyd library in my project and i want project compile to pyd modules.

```
import pyodbc
import os , sys , platform

conn = ...
```
pyodbc is a pyd library can i use in project and compile my project as module with `--module test.py` ?

my switch for compile:

`nuitka --follow-import-to=os,sys,platform --include-module=pyodbc --module test.py`

just know it's true way?

**Comment by kayhayen** [comment]
In acceleration mode, extension modules are used from the Python installation. This command as given has no effect in that mode, unless there are hidden dependencies known for that extension module, which can also happen if a `.pyi` file is present, and does import statements. These would then be asked about too.

In standalone mode, you would only need to do that, if the usage is itself hidden, e.g. doing `__import__` with strings, in which case it won't be included automatically.
