### ISSUE TITLE
The locals() function could be evaluated in the wrong context, e.g. in dict comprehension

### ISSUE THREAD

**Issue by arkanoid87** [Nuitka/Nuitka#758]
0.6.8.4 (pip version)
Python: 3.8.2 (default, Apr 27 2020, 15:53:34) 
Executable: /home/jack/oggreader/venv/bin/python
OS: Linux
Arch: x86_64

returning locals() from comprehension returns empty dict without warnings
```
from typing import Dict, Any
def foo() -> Dict[str,Any]:
    bar: str = "asd"
    return {x:y for x,y in locals().items()}
print(foo())
```
> prints {}

copying the locals() to var solves the problem
```
from typing import Dict, Any
def foo() -> Dict[str,Any]:
    bar: str = "asd"
    copy = locals()
    return {x:y for x,y in copy.items()}
print(foo())
```
> prints {'bar': 'asd'}

without comprehension everything works as expected
```
from typing import Dict, Any
def foo() -> Dict[str,Any]:
    bar: str = "asd"
    return locals()
print(foo())
```
> prints {'bar': 'asd'}

**Comment by kayhayen** [comment]
Without warning is too weak a statement for incorrect code execution (ICE), the worst kinds of bugs. Thanks for the report, this should be easy and I hope to make a hotfix out of it.

**Comment by kayhayen** [comment]
So, this looks like `locals()` is in the iterator, and probably Nuitka is falsely evaluation the iterated in the comprehension context, which is wrong. 

This example is more extreme:

```
>>> def f(): x=1; return {(tuple(locals()), y)  for y in locals().keys()}
... 
>>> f()
{(('.0', 'y'), 'x')}
```

**Comment by kayhayen** [comment]
The bug affects Python 2.7 and higher.

**Comment by kayhayen** [comment]
The dictionary of locals is compile time predicted to the wrong value, the empty dict with your code.

**Comment by kayhayen** [comment]
This one is going to be tricky. The variable reference by name of locals knows it's referring to `f` still, but then gets translated to a module variable reference, `locals`, and which point the link is lost, as that gets owned by the module. Then next up it's translated to a built-in reference as nothing writes to `locals`, again that is without a link preservation.

And then when seen called, as a built-in of that name, it's changed to a `locals` node and derives where it looks at from parent function. In this case, it's the outline function of the contraction. 

Doing the iterator lookup outside of the "outline" (inline function code is a new context) would do the trick, but we can't do that, as it's an expression, and the way we would do that, is an outline, which then though is having the same problem.

**Comment by kayhayen** [comment]
In terms of solution, there is a technical debt of `locals()` not referencing its provider directly, but going via parent relationships, which bears potential problems by itself.

And then there is a need to preserve that original provider for some variable names. I think that `dir`, `vars` and `locals` are affected. Global variables of these names would have to remember the context they refer to. This could problematic in case of constructs like this: `(locals if cond else globals)()` where `cond` will be known statically only later.

**Comment by kayhayen** [comment]
I hate what this means for inline ability of functions, but obviously if there are locals references to it, we can't do it, and we should be aware of that anyway.

**Comment by kayhayen** [comment]
Ok, so this has a complex solution. In Nuitka we already use locals scopes for some things. They represent the scope of a function, class, or module. They are mostly only used for the ones, where locals is a dictionary, like class or functions with exec, to get the proper locals() values for these.

Normal functions for Python2 at least, do not create their variables through them though. Actually that's the only kind of function that has no locals scope. There is of course a TODO, to make functions do that too. I think Python3 functions are in between, and do only use them, where it's not clear if it's a module variable immediately, so they are incomplete potentially.

So I made the change and preserve the builtin name owner and pass them along. But ultimately when locals() gets constructed, it was was through its parent still during optimization, while using the locals scope for code generation. Changing the trace collection to go through a locals scope (that it was also using), but only that, is a goal.

The locals scopes are intended to get rid of constraints for inlining. With proper use of locals scopes, the original containers can indeed be inlined, and that resolves my worries with the inlining entirely.

Mostly the resolution is about working off these technical debts. That's pretty invasive stuff. I don't see this as any possible hotfix at all. The variable closure will be affected, and functions need to hand of some responsibility for provision of variables to be done through scopes. On the other hand, these scopes probably need to be the ones that take closure variables too.

**Comment by kayhayen** [comment]
So, I changed the nodes to preserve the information if necessary, and the locals dict handling and its optimization to work through the locals scope, while also attaching standard local variables, not just locals dict ones, to the local scopes, and the example you gave works correctly in both Python2 and Python3.

But there is a bunch of breakage now potentially. Esp. the handling of `.0` was strange in places, but that's probably just a harmless bug that is gone.

**Comment by kayhayen** [comment]
Took me a while, but the fix is finished, and the code on factory.

Instead of using parent variable provider of a node, which esp. for contractions can be something else, we remember the context we were in, and attach it. Functions now store they provided variables in local scope objects, and these are the only ones really used.

In principle we ought to be able now, to inline all local functions no matter what. This is not done, but probably a nice optimization target to aim for with at least cheap functions called multiple times, or single use functions. So this is also progress in the whole picture, including for whole program optimization, if ever done, to be allowed to inline functions without any regards to `locals()` being present or not.

**Comment by kayhayen** [comment]
Check this out if you want https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
There is a small remaining issue for code that assigns `__class__` inside of a class body, so this remains on factory despite the pre-release I just made.

**Comment by kayhayen** [comment]
I made a pre-release with this contained. This has drawn more and more circles, esp. as the code turned out to now highlight weaknesses in the loop tracing, which had to be ironed out. However, all good now.

**Comment by arkanoid87** [comment]
I'm far from capable of understanding the complexity of underlying machinery, but I consider this an impressive work.
Thanks for addressing this.

**Comment by kayhayen** [comment]
This is the last release 0.6.9 already for a while.
