### ISSUE TITLE
problem after create module with nuitka

### ISSUE THREAD

**Issue by BlackRouter** [Nuitka/Nuitka#760]
```
0.6.8.4
Python: 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:20:19) [MSC v.1925 32 bit (Intel)]
Executable: C:\Users\Moein\PycharmProjects\license\venv\Scripts\python.exe
OS: Windows 10
Arch: x86
```

Imports :
```
os
uuid
json
ctypes
base64
datetime
rsa
```
i create module with switch `nuitka --follow-import-to=os,uuid,json,ctypes,base64,datetime --include-package=rsa,pyasn1 --module M4Lic.py `

after create module work on windows 10 but on windows 8.1 and 7 i get error:

```
Traceback (most recent call last):
  File "d:/Project/Moeinsoft/MoeinBackup/test/test.py", line 1, in <module>
    from M4Lic import *
ImportError: DLL load failed while importing M4Lic: The specified module could not be found.
```

on windows 7 and 8.1 i install `Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019 , python 3.8.3 (32bit)`

**Next issue :** 

i import module : `from M4Lic import *` don't show functions in M4Lic module , any way show function method pyd modules?

**Comment by kayhayen** [comment]
There is a section on how to do older Windows in the user manual, follow that.

Yours,
Kay
