### ISSUE TITLE
StopIteration when running my exe

### ISSUE THREAD

**Issue by gauthierbuttez** [Nuitka/Nuitka#761]
Hi,

This is my environment:
0.6.8.4
Python: 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
Executable: E:\DropboxBACKUP14112018\Cff\Python\PhoneBot\venv\Scripts\python.exe
OS: Windows
Arch: x86_64

I used this command line to make exe:
`python -m nuitka --standalone --plugin-enable=numpy --plugin-enable=multiprocessing --show-progress --show-scons --follow-imports --recurse-all --windows-icon=E:\DropboxBACKUP14112018\Cff\Python\PhoneBot\favicon_phonebot.ico PhoneBot.py`

When I run my exe from cmd, I get this error message:
```
Traceback (most recent call last):
  File "E:\DROPBO~1\Cff\Python\PHONEB~3\PHONEB~1.DIS\PhoneBot.py", line 1032, in <module>
StopIteration
```

Can someone help me to find the source of the issue?

I checked my code on line 1032. Is this number of line reliable? I mean, are we 100% sure the issue is coming from line 1032 as I don't see any  loop there.

Here is my code:
 ```
  import itertools, glob
   icons = itertools.cycle(glob.glob('*.ico'))
   hover_text = "PhoneBot.co"
   def show(sysTrayIcon):
       the_program_to_hide = ctypes.windll.kernel32.GetConsoleWindow()
       win32gui.ShowWindow(the_program_to_hide, win32con.SW_SHOW)
   def hide(sysTrayIcon):
       the_program_to_hide = ctypes.windll.kernel32.GetConsoleWindow()
       win32gui.ShowWindow(the_program_to_hide, win32con.SW_HIDE)

   def run_main(sysTrayIcon):
       try:
           main()
       except SystemExit as e:
           print(f'Error! {e}')
           rawinput = input('Press enter to exit (and fix the problem)')
   menu_options = (('Show', next(icons), show),  # <------ Line 1032
                   ('Hide', next(icons), hide),
                   ('Pause', next(icons), pause),
                   ('Resume', next(icons), play),
                   ('Quit', next(icons),Exit)
                   )
```
Could you help me please?
Kind regards

**Comment by gauthierbuttez** [comment]
After some tests, I think I identify the source of problem.
First of all, I forgot to tell you that the script is running fine with  python3 interpreter. It has an issue only with the exe.
Line 1032 which creates an issue is connected with my "systray" icon menu.
I have to create some kind of small GUI for the users of my program.

I use the code proposed in the solution of this https://stackoverflow.com/questions/61656051/how-to-show-hide-windows-console-in-systray

Obviously it looks it is the function "Show" of my menu "Show" which suppose to show the console log of my program.
When my users run the program, the GUI menu offers them the possibility to HIDE the console log; and then to SHOW it again.
This is the code of the function. You can see 2 lines commented as I tried other code in order to fix this Nuitka issue 761. Both are working fine when the script is executed but both are raising the error "StopIteration" with the exe.
 def show(sysTrayIcon):
       #the_program_to_hide = ctypes.windll.kernel32.GetConsoleWindow()
       #win32gui.ShowWindow(the_program_to_hide, win32con.SW_SHOW)
       user32 = ctypes.WinDLL('user32', use_last_error=True)
       SW_HIDE = 0
       SW_SHOW = 5

Also, what is maybe important to know is the fact that I am running 2 threads:
- One for the systray menu.
- One for the main program.

Here is the code of multi-thread:
   ```
def run_SysTrayIcon():
       SysTrayIcon(next(icons), hover_text, menu_options, default_menu_index=1)

   th1 = threading.Thread(target=run_SysTrayIcon)
   th2 = threading.Thread(target=main)
   th1.start()
   th2.start()
   th1.join()
   th2.join()
```


For better understanding, here are all the pieces of the code which I suspect to create the issue:

```
import itertools, glob
   icons = itertools.cycle(glob.glob('*.ico'))
   hover_text = "PhoneBot.co"
   def show(sysTrayIcon):
       #the_program_to_hide = ctypes.windll.kernel32.GetConsoleWindow()
       #win32gui.ShowWindow(the_program_to_hide, win32con.SW_SHOW)
       user32 = ctypes.WinDLL('user32', use_last_error=True)
       SW_HIDE = 0
       SW_SHOW = 5
   def hide(sysTrayIcon):
       #the_program_to_hide = ctypes.windll.kernel32.GetConsoleWindow()
       #win32gui.ShowWindow(the_program_to_hide, win32con.SW_HIDE)
       was_visible = user32.ShowWindow(hwnd, SW_HIDE)


   def play(sysTrayIcon):
       # === Initialisation of SQLITE DB ========================
       sqliteConnection = sqlite3.connect('db.db')
       sqlite_cursor = sqliteConnection.cursor()
       sqlite_cursor.execute("UPDATE settings set play_stop_pause=?",(0,))
       sqliteConnection.commit()
       logger.info("You click on 'Play' button. Please wait a bit. PhoneBot will start again the work.")
       sqlite_cursor.close()
       sqliteConnection.close()


   def pause(sysTrayIcon):
       # === Initialisation of SQLITE DB ========================
       sqliteConnection = sqlite3.connect('db.db')
       sqlite_cursor = sqliteConnection.cursor()
       sqlite_cursor.execute("UPDATE settings set play_stop_pause=?",(2, ))
       sqliteConnection.commit()
       logger.info("You click on 'Pause' button. Please wait a bit. PhoneBot will put in pause all the jobs.")
       sqlite_cursor.close()
       sqliteConnection.close()


   def Exit(sysTrayIcon):
       # === Initialisation of SQLITE DB ========================
       sqliteConnection = sqlite3.connect('db.db')
       sqlite_cursor = sqliteConnection.cursor()
       try:
           sqlite_cursor.execute("UPDATE settings set play_stop_pause=?",(1, ))
           sqliteConnection.commit()
           logger.info("You click on 'Quit' button. Please wait a bit. PhoneBot will stop everything.")
       #except ValueError:
       except Exception as ex:
           logger.critical(f"{ex} -> Error when UPDATE settings set play_stop_pause=?")

           sqlite_cursor.close()
           sqliteConnection.close()
           sys.exit()


       sqlite_cursor.close()
       sqliteConnection.close()



       while True:
           PROCNAME = "python.exe"
           for proc in psutil.process_iter():
               if proc.name() == PROCNAME:
                   #print(f"PhoneBot stop : {proc}")
                   print(f"PhoneBot stop. Thanks for using PhoneBot.")
                   try:
                       proc.kill()
                   except:
                       sys.exit()


   def run_main(sysTrayIcon):
       try:
           main()
       except SystemExit as e:
           print(f'Error! {e}')
           rawinput = input('Press enter to exit (and fix the problem)')
   menu_options = (('Show', next(icons), show),
                   ('Hide', next(icons), hide),
                   ('Pause', next(icons), pause),
                   ('Resume', next(icons), play),
                   ('Quit', next(icons),Exit)
                   )
   def run_SysTrayIcon():
       SysTrayIcon(next(icons), hover_text, menu_options, default_menu_index=1)

   th1 = threading.Thread(target=run_SysTrayIcon)
   th2 = threading.Thread(target=main)
   th1.start()
   th2.start()
   th1.join()
   th2.join()
```

I hope, it could help to find the solution.

**Comment by kayhayen** [comment]
The `next` builtin can give `StopIteration` of course. And when used on a finished or empty iterator, well, it raises. In your code, you `glob` for icon files, and probably there are none.

I wonder, why I was involved here. I surely can't debug other people code. Can you please consider as a primary option a bug in your code first?

Yours,
Kay

**Comment by gauthierbuttez** [comment]
I am so sorry to have bothered you. Let me explain why I contacted you.
I am a newbie in python.
When I run my python script, there is no issue at all. Everything runs fine.
When I compile my code with nuitka and I run the exe, I get this issue.

So you can understand now why a newbie like me came here to ask for help. I thought it was because of Nuitka.

But, I start to understand how it works.

Nuitka is  transforming my python script in some code more strict and serious.

Python 3.7 is kind and flexible by ignoring my issue, whereas Nuitka code is very strict and raise any little exception.

Again, please accept my apologies. I am just a newbie who is learning day after day.

Thanks for the help.

**Comment by kayhayen** [comment]
I didn't mean to stress you out, sorry if I did.

One correction though, Nuitka is not more strict at all. In fact it behaves exactly the same. When you do not include your icon files, your program behaves the same, it's not ignoring your issue. 

The misunderstanding there is that you do not realize that file system differences change how your program behaves. The glob will not give an iterator that gives a filename, and henace your `StopIteration`.

When you program gives you any error, it may be true, that's just something, that as a newbee you still can consider. :-)

**Comment by bvrulez** [comment]
This "issue" pointed me to the right direction. People might suspect that packaging all of the code to just one executable (and one .dist-folder) might include files used as resources. Maybe you could add a comment in the manual that this is not the case. Of course it probably just affects novices. Thanks for your awesome work!
