### ISSUE TITLE
Script using the WMI module doesn't work after compiling

### ISSUE THREAD

**Issue by HoshinoKoji** [Nuitka/Nuitka#765]
I am trying to compile a simple script depending on WMI. While compiling through `nuitka --standalone --mingw64 --recurse-all --output-dir=out test_create.py`, some warnings are shown as below:

> Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\Hoshino\AppData\Local\Programs\Python\Python38\lib\site-packages\win32com\client\gencache.py:236' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\Hoshino\AppData\Local\Programs\Python\Python38\lib\site-packages\win32com\client\gencache.py:627' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\Hoshino\AppData\Local\Programs\Python\Python38\lib\site-packages\win32com\client\makepy.py:320' may require use of '--include-plugin-directory' or '--include-plugin-files'. 

And when I try to execute the output file, there is an import error:

> Traceback (most recent call last):
  File "C:\Users\Hoshino\Documents\Projects\client_create.dist\client_create.py", line 2, in <module>
  File "C:\Users\Hoshino\Documents\Projects\client_create.dist\wmi.py", line 105, in <module wmi>
  File "C:\Users\Hoshino\Documents\Projects\client_create.dist\win32com\__init__.py", line 5, in <module win32com>
ImportError

I have tried manually to include "C:\Users\Hoshino\AppData\Local\Programs\Python\Python38\lib\site-packages\win32com\client\" with `--include-plugin-directory` option, which failed as well. It seems that this module is doing a dynamic import. I will appreciate it if someone could help me.

* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

  0.6.7
  Python: 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
  Executable: C:\Users\Hoshino\AppData\Local\Programs\Python\Python38\python.exe
  OS: Windows
  Arch: x86_64

* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.

  pip

**Comment by kayhayen** [comment]
That's a very old Nuitka release. We fixed stuff for 0.6.8 hotfixes in that area.
