### ISSUE TITLE
Python27.dll is  missing from your computer

### ISSUE THREAD

**Issue by LP-Codes** [Nuitka/Nuitka#776]
after generating the exe when distributed to other sytem which doesnt have python installed we get Python27.dll is  missing from your computer error can you kindly let us know the fix 

command used is python -m nuitka --standalone  --follow-imports --mingw64 --show-progress --show-scons --windows-dependency-tool=pefile  filename.py

**Comment by kayhayen** [comment]
Try again without pefile used please.

**Comment by LP-Codes** [comment]
Hello Kayhayen,
I Tried Without pefile , got Same error the exe works fine on my system which has python installed i wanted to get it working on system which doesn't have python installed  , kindly check 
![image](https://user-images.githubusercontent.com/66465441/86753864-0dd8eb00-c05e-11ea-9acf-b3c2ee14362a.png)

**Comment by kayhayen** [comment]
This lacks all the information from the issue template unfortunately. I don't think I want to work like that. I just wanted to know if pefile can make a difference, but I don't even know what Python this is.
