### ISSUE TITLE
No module named 'pyfiglet.fonts'

### ISSUE THREAD

**Issue by himadriganguly** [Nuitka/Nuitka#777]
After running
```
python -m nuitka --plugin-enable=pylint-warnings --follow-imports --standalone sample.py
```
it completes the build without any error but when I run the build **sample** file from **sample.dist** directory it gives

```
Traceback (most recent call last):
  File "[PATH TO PROJECT]/sample.dist/pkg_resources/__init__.py", line 359, in get_provider
KeyError: 'pyfiglet.fonts'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[PATH TO PROJECT]/sample.dist/yarasilly2.py", line 183, in <module>
  File "[PATH TO PROJECT]/sample.dist/pyfiglet/__init__.py", line 794, in __init__
  File "[PATH TO PROJECT]/sample.dist/pyfiglet/__init__.py", line 801, in setFont
  File "[PATH TO PROJECT]/sample.dist/pyfiglet/__init__.py", line 126, in __init__
  File "[PATH TO PROJECT]/sample.dist/pyfiglet/__init__.py", line 136, in preloadFont
  File "[PATH TO PROJECT]/sample.dist/pkg_resources/__init__.py", line 1134, in resource_exists
  File "[PATH TO PROJECT]/sample.dist/pkg_resources/__init__.py", line 361, in get_provider
ModuleNotFoundError: No module named 'pyfiglet.fonts'
```

* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

  python -m nuitka --version
```
0.6.8.4
Python: 3.8.3 (default, May 29 2020, 00:00:00) 
Executable: [PATH TO PROJECT]/venv/bin/python
OS: Linux
Arch: x86_64
```
* Nuitka Install
```
pip install nuitka
```
* Sample piece of code
```
from pyfiglet import Figlet
if __name__ == '__main__':
  f = Figlet(font='slant')
  print(f.renderText("Sample Text")
```

**Comment by kayhayen** [comment]
Something is missing from the example code. Indentation is off, and puts an unknown variable.

**Comment by kayhayen** [comment]
So, this is a hidden dependency on `pyfiglet.fonts` and its many data files. This one probably needs a plugin to select which TTF fonts to include. I just removed the last line, error occurs earlier. All fonts are 5,8M, probably not too bad.

**Comment by himadriganguly** [comment]
Thank you @kayhayen for accepting the issue. Take care.

**Comment by himadriganguly** [comment]
> Something is missing from the example code. Indentation is off, and puts an unknown variable.

Sorry for my mistake there is some error in the sample code. Updated the code. Thank you @kayhayen for pointing out.

**Comment by mahmoudgabal081** [comment]
@kayhayen please , How do I fix that error ?
PS C:\Users\Dell> pip install pyfiglet
Requirement already satisfied: pyfiglet in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (0.8.post1)
PS C:\Users\Dell> & C:/Users/Dell/AppData/Local/Programs/Python/Python37/python.exe d:/python/Python/secound.py
Traceback (most recent call last):
  File "d:/python/Python/secound.py", line 273, in <module>
    import pyfiglet
ModuleNotFoundError: No module named 'pyfiglet'

**Comment by alf1e** [comment]
Hey, anyone got a fix for this yet or a workaround. I'm a bit dumb so if you could point it out that would be helpful.

**Comment by garayevh** [comment]
> Hey, anyone got a fix for this yet or a workaround. I'm a bit dumb so if you could point it out that would be helpful.

try like this: pyinstaller --collect-all pyfiglet -F your_file.py

**Comment by kayhayen** [comment]
So, this old issue has several solutions now. On develop, Nuitka now registers the loader with `pkg_resources` and therefore it works to look `pyfiglet.fonts` up. So this now works:

`python3.9 -m nuitka --standalone --include-package-data=pyfiglet.fonts --include-package=pyfiglet.fonts MiniPyfliglet.py`

This of course leads to 429 files being included.

> Nuitka-Options:INFO: Included 429 data files due to package 'pyfiglet.fonts' is exact match of 'pyfiglet.fonts'.

So, but nowadays there is `--noinclude-data-files` that can be used to remove data files. Keeping only one, can then be hard I guess. Right now, there is not yet an easy way to include only part of the fonts, but there is `--include-data-files` where you could chose to put only the font files you care about in that space. I will take note, that the package-data file option, should really have a positive filename matching built into itself too. If you care to read up, shell patterns probably also allow to say matching everything that is not this, but that is very arcane I guess.

I am not sure if `pyfiglet.fonts` is an implicit dependency that should always be there. And I am not sure if to at this data directory to the new Yaml configuration we have. 

But anyway, now it's supported at least.

**Comment by kayhayen** [comment]
So `--include-package-data=pyfiglet.fonts:slant.flf` works on the factory brach now too.

**Comment by kayhayen** [comment]
On develop now, and the yaml config should make this work out of the box.

**Comment by kayhayen** [comment]
This is part of the stable release 1.1 that I just made.
