### ISSUE TITLE
Dropbox module error MemoryError after 7h compilation

### ISSUE THREAD

**Issue by PSFarsi** [Nuitka/Nuitka#778]
```
0.6.8.4
Python: 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:20:19) [MSC v.1925 32 bit (Intel)]
Executable: C:\Users\Ja7ad\Desktop\test\env\Scripts\python.exe
OS: Windows
Arch: x86
```
my code for test:

```
from dropbox import Dropbox

dbx = Dropbox('access token from dropbox developer')
print(dbx.files_list_folder('',recursive=True))
input()
```
nuitka command for compilation `nuitka --recurse-all --standalone --show-progress --verbose --mingw64 test.py`

Error recived:

```
Nuitka:INFO: Total memory usage before generating C code: 786.27 MB (824463360 bytes):
Traceback (most recent call last):
  File "C:\Users\Ja7ad\Desktop\test\env\lib\site-packages\nuitka\__main__.py", line 195, in <module>
    main()
  File "C:\Users\Ja7ad\Desktop\test\env\lib\site-packages\nuitka\__main__.py", line 188, in main
    MainControl.main()
  File "C:\Users\Ja7ad\Desktop\test\env\lib\site-packages\nuitka\MainControl.py", line 749, in main
    result, options = compileTree(main_module=main_module)
  File "C:\Users\Ja7ad\Desktop\test\env\lib\site-packages\nuitka\MainControl.py", line 648, in compileTree
    makeSourceDirectory(main_module=main_module)
  File "C:\Users\Ja7ad\Desktop\test\env\lib\site-packages\nuitka\MainControl.py", line 368, in makeSourceDirectory
    source_code = CodeGeneration.generateModuleCode(
  File "C:\Users\Ja7ad\Desktop\test\env\lib\site-packages\nuitka\codegen\CodeGeneration.py", line 481, in generateModuleCode
    return getModuleCode(module_context=module_context, template_values=template_values)
  File "C:\Users\Ja7ad\Desktop\test\env\lib\site-packages\nuitka\codegen\ModuleCodes.py", line 171, in getModuleCode
    result = header + template_module_body_template % template_values
MemoryError

```

Dropbox files before\after generate C code:

![out](https://user-images.githubusercontent.com/67512583/86694713-1d860e80-c021-11ea-89e8-adda0b299d65.jpg)

**Comment by kayhayen** [comment]
Seems dropbox runs into the 32 bit process memory limit here. This might be because it's more code, which I doubt, but also could be because some wrong optimization creates a constant at compile time that it ought not to.

Can you use `--show-memory` and attach full compilation report with only that. Then we would know the worst offender, either for load in first pass, or for later optimization, where one step would make it explode.

**Comment by PSFarsi** [comment]
> Seems dropbox runs into the 32 bit process memory limit here. This might be because it's more code, which I doubt, but also could be because some wrong optimization creates a constant at compile time that it ought not to.
> 
> Can you use `--show-memory` and attach full compilation report with only that. Then we would know the worst offender, either for load in first pass, or for later optimization, where one step would make it explode.



> Seems dropbox runs into the 32 bit process memory limit here. This might be because it's more code, which I doubt, but also could be because some wrong optimization creates a constant at compile time that it ought not to.
> 
> Can you use `--show-memory` and attach full compilation report with only that. Then we would know the worst offender, either for load in first pass, or for later optimization, where one step would make it explode.

ok i send full report with `--show-memory`

**Comment by PSFarsi** [comment]
**command:

**

`nuitka --recurse-all --standalone --show-memory --enable-plugin=pylint-warnings --mingw64 test.py`

**code:**

```
from dropbox import Dropbox

dbx = Dropbox('access token from dropbox developer')
print(dbx.files_list_folder('',recursive=True))
input()
```

**Error:**

```
Nuitka:INFO: Total memory usage before generating C code: 1.01 GB (1079967744 bytes):
Traceback (most recent call last):
  File "C:\Users\Ja7ad\Desktop\test\env\lib\site-packages\nuitka\__main__.py", line 195, in <module>
    main()
  File "C:\Users\Ja7ad\Desktop\test\env\lib\site-packages\nuitka\__main__.py", line 188, in main
    MainControl.main()
  File "C:\Users\Ja7ad\Desktop\test\env\lib\site-packages\nuitka\MainControl.py", line 749, in main
    result, options = compileTree(main_module=main_module)
  File "C:\Users\Ja7ad\Desktop\test\env\lib\site-packages\nuitka\MainControl.py", line 648, in compileTree
    makeSourceDirectory(main_module=main_module)
  File "C:\Users\Ja7ad\Desktop\test\env\lib\site-packages\nuitka\MainControl.py", line 368, in makeSourceDirectory
    source_code = CodeGeneration.generateModuleCode(
  File "C:\Users\Ja7ad\Desktop\test\env\lib\site-packages\nuitka\codegen\CodeGeneration.py", line 481, in 
generateModuleCode
    return getModuleCode(module_context=module_context, template_values=template_values)
  File "C:\Users\Ja7ad\Desktop\test\env\lib\site-packages\nuitka\codegen\ModuleCodes.py", line 171, in getModuleCode
    result = header + template_module_body_template % template_values
MemoryError
```

[report.txt](https://github.com/Nuitka/Nuitka/files/4889299/report.txt)

**Comment by kayhayen** [comment]
The code generation error will of course not necessarily trigger for the module that has the issue, but raises the question, of why there is an extra 1G spent, as I expect there to be that much remaining. I am not sure though, if Windows doesn't have a smaller limit there.

It may leak memory though. And in fact, what should be happening is that memory lowers during code generation. I believe I release stuff afterwards, before then calling scons. So this could be improved. After I finish the new constants branch, which will be shortly, code generation per module will be independent from another. Then surely we can release it sooner.

In your tracing, there are two modules that stand out:

>Nuitka:INFO:Memory usage changed loading module 'idna.uts46data': 14.55 MB (15253504 bytes)
>Nuitka:INFO:Memory usage changed loading module 'chardet.langcyrillicmodel': 1.79 MB (1871872 bytes)
>Nuitka:INFO:Memory usage changed loading module 'dropbox.files': 31.05 MB (32555008 bytes)
>Nuitka:INFO:Memory usage changed loading module 'dropbox.file_properties': 3.57 MB (3739648 bytes)
>Nuitka:INFO:Memory usage changed loading module 'dropbox.file_requests': 1.09 MB (1138688 bytes)
>Nuitka:INFO:Memory usage changed loading module 'dropbox.paper': 5.50 MB (5771264 bytes)
>Nuitka:INFO:Memory usage changed loading module 'dropbox.sharing': 24.49 MB (25681920 bytes)
>Nuitka:INFO:Memory usage changed loading module 'dropbox.team_log': 150.89 MB (158220288 bytes)

The later is really a bummer. I expected traces for changes during optimization, which could also be to blame, but notice that the later takes almost as much as the whole of mercurial compilation on 64 bits. Using 32 bits should only be less memory.

**Comment by kayhayen** [comment]
```
# Auto-generated by Stone, do not modify.
# @generated
# flake8: noqa
# pylint: skip-file
```

and then 104k lines of code. I believe, the constants for the module, are going to cause a lot of code, that my branch will address. I think, this might be a nice case to study differences in memory usage of that branch. Since Nuitka no longer generates per constant code, this might make a huge difference at that point. It could well be that the code of the file generated is being simply very large too, easily parts of a GB as well.

So I guess, over the weekend, I might surface with something useful there. The new constants code is internal testing and being fixed up. Should it finish, this is probably going to drop below the threshold of 2GB.

**Comment by kayhayen** [comment]
So, 64 bits Linux it's more like 227 MB to load, i.e. even more, due to larger pointers.

**Comment by PSFarsi** [comment]
@kayhayen thank you for explain about this , i hope improved for support 2GB
