### ISSUE TITLE
Networkx → infinite optimization loop

### ISSUE THREAD

**Issue by belonesox** [Nuitka/Nuitka#783]
Tested on Anaconda 32/64, 3.7 and 3.8 python.

Lets consider minimal environment
```
conda create --prefix .\envs networkx pip
conda activate .\envs
python -m pip install nuitka
```
↓↓↓
```
networkx==2.4
Nuitka==0.6.8.4
```

Minimal sample

```python
import networkx
print('11111')
```

And call nuitka as 
```
python.exe -m nuitka --show-progress --recurse-not-to=networkx.linalg --recurse-not-to=pandas --show-scons --recurse-not-to=networkx.testing --recurse-not-to=networkx.drawing --recurse-not-to=pytest --recurse-not-to=nose --recurse-not-to=networkx.readwrite --standalone wtf.py   
```

we got infinite optimization loop 

```
…
Nuitka:INFO:Optimizing module '_bz2', 0 more modules to go after that.
Nuitka:INFO:Next global optimization pass.
Nuitka:INFO:Optimizing module '__main__', 18 more modules to go after that.
Nuitka:INFO:Doing module local optimizations for '__main__'.
Nuitka:INFO:Optimizing module 'networkx', 19 more modules to go after that.
Nuitka:INFO:Doing module local optimizations for 'networkx'.
Nuitka:INFO:Optimizing module 'networkx.algorithms', 28 more modules to go after that.
…
∞∞∞∞∞∞
…
```

**Comment by belonesox** [comment]
May be connected with #780, but I am not sure.

**Comment by belonesox** [comment]
Tested on linux and fresh Nuitka 
   commit 7256d14d4a10af1fbf4166417670314daba1964b   
   Date:   Thu Jun 25 16:13:30 2020 +0300

same problem.

**Comment by kayhayen** [comment]
If you compile with `--verbose` and it repeatedly complains about same incomplete loop, but nothing else is output other than that, it would be the same isue. Can you check that?

**Comment by belonesox** [comment]
Checked 0.6.6 and 0.6.7 — OK.  0.6.8 — problem.
Part of infinite verbose log attached.
[nuitka-log.zip](https://github.com/Nuitka/Nuitka/files/4895822/nuitka-log.zip)

**Comment by belonesox** [comment]
Hello! Is the bug still «need_example»? 
Any news or estimates? How "scary" the bug is?

**Comment by kayhayen** [comment]
I was thinking about it, and it only got more scary since. I am trying to devise a strategy on how a multi-loop analysis needs to be done in order to guarantuee a result, or how to recognize if it cannot be done.

**Comment by kayhayen** [comment]
I have had the workaround on factory for a while, and now it's part of the latest pre-release of Nuitka.

I will need to still look into the root cause, but that may not happen for some time, so I am treating this as the solution.

**Comment by kayhayen** [comment]
I think the root cause has been address with the latest pre-release. The loop analysis was in fact in so many ways, it wasn't funny.

**Comment by kayhayen** [comment]
This is the last release 0.6.9 already for a while.
