### ISSUE TITLE
Does Nuitka hardcode the initial path at compile time into the resulting accelerated executable?

### ISSUE THREAD

**Issue by Coderx7** [Nuitka/Nuitka#785]
The issue is, nuitka hadcodes all the pathes in the initial invocation into the resulting executable. that is, if my python script is located at for example : `C:\Users\user\PythonProjects\myproc1` 
all pathes that are evaluated at compile time, are hardcoded into  the executable, and if for example wrote a simple code for reading an image which is in the current working directory,:
```python
current_dir = os.path.dirname( os.path.abspath(__file__)) 
icon = os.path.join(current_dir, 'imgs', 'icon.ico')
....
```
it wont work, if I move the executable to some other locations where the initial path does not exists! 

* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)
```
0.6.8.4
Python: 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
Executable: C:\Users\User\Anaconda3\python.exe
OS: Windows
Arch: x86_64
```
* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.
```
using pip
```
* Many times when you get an error from Nuitka, your setup may be so special
  that even a "hello world" program will not work, please try that and report
  it instead.

it doesnt matter! 

* If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
  that demonstrates the issue i.e a small piece of code which reproduces
  the issue and can be run with out any other (or as few as possible)
  external dependencies.

here is a short self contained correct example (`test.py`): 
```python
import os
current_dir = os.path.dirname( os.path.abspath(__file__)) 
print(f'current dir: {current_dir}')
print(f"current_python file: {os.path.join(current_dir, 'test.py')}")
input()
```
Just create the executable and move it to some other location, you'll see it will print the path of where the original .py file resided.
I used the following command to create the executable : 
```shell
python -m nuitka test.py
```

* If this is a regression (used to work in an earlier version of Nuitka),
  please note what you know about that.

I also tested this on the 0.6.4.0 version and the same issue exists there as well.

**Comment by kayhayen** [comment]
There is `--file-reference-mode ` that controls these. For acceleration if defaults to compile time paths.

For the main program, should be use original location, and find unmoved files, or should we follow new location, and not find them.

Your `current_dir` is more like a home directory, if you ask me. There is also an issue about symlinks, and what they do in normal Python differently about `__file__`. But in a way, Nuitka binary created in accelerated mode, works more like a symlink to a Python script. And for independence from installation, acceleration is to be used.

Proper packaging with wheels and data files is illustrated in `tests/distutils` examples. If this is about distribution to another machine, that's better. It uses module mode for main code, and entry points, and puts the data files automatically. That is the best supported mode of operation right now.

**Comment by kayhayen** [comment]
I am treating this as a question and close it, mostly because I don't want to make a file reference mode, that treats main differently from other modules, which would probably be needed. Nobody is going to use that anyway for lack of discoverabiltiy.
