### ISSUE TITLE
cc1.exe memory issue on SimpleITK/ideas to overcome

### ISSUE THREAD

**Issue by ryancinsight** [Nuitka/Nuitka#788]
Hello,

my script uses SimpleElastix which is basically ITK and Elastix codes using Swig for python usage. It seems that nuitka faults when it gets to this package with a memory allocation error only on when compiling as a standalone.  Here is the command line I'm using to start compiling, I was hoping pefile might reduce the size enough but so far it hasn't, I have 16 gbs of ram. I believe the issue is that this package is one large pyd already ~500mbs as just _SimpleITK.pyd so I believe it is trying to include the whole package. My memory seems to fill and then the computer shuts down, even when I only import SimpleITK and have no other code in script. When I run without standalone everything runs fine. I am using the development version of nuitka as available yesterday, July 12th.

python -m nuitka --mingw64 MRANALYSIS_Pictures.py --plugin-enable=multiprocessing --plugin-enable=tk-inter --plugin-enable=numpy --plugin-enable=qt-plugins --show-progress --show-scons --plugin-enable=pylint-warnings --standalone --windows-dependency-tool=pefile

Is there potentially a way to compile not through ram like a temp folder or an exclude folder that packages but doesn't recompile certain packages. Otherwise, is there a way to spend more time analyzing SimpleITK to only pull relevant code being used from the package or a way to create a standalone zip that extracts everything needed, including packages you asked to exclude in compile, to a folder on someone else's computer etc.

**Comment by kayhayen** [comment]
Not filling out the issue template makes this lack important information.
