### ISSUE TITLE
Option "--recompile-c-only" misleading.

### ISSUE THREAD

**Issue by belonesox** [Nuitka/Nuitka#792]
While reading from option description

 "--recompile-c-only" —  "… Takes existing files and simply compile them as C again. …" 

someone (as me) may thought that is The Option that opposite to "--generate-c-only" that skip VERY LONG 
```Optimization.optimize(main_module.getOutputFilename())``` and only call Scons with clcache to recompile already generated C files (for hacking, experiments with compiler/linker options, etc).

But unfortunately, it is not true, Nuika still takes hours to "Optimization.optimize"
and there is no other option "--please-just-make-scons-and-recompile-already-generated-files-and-nothing-more".

Please, let  "--recompile-c-only" will only recompile C code, or.... if I missed the goal of the option, just make another option for this purpose.

**Comment by kayhayen** [comment]
Unfortunately, for scons to work, Nuitka needs the information about the modules, and this would have to come from compilation or a cache. The later is the actual solution in my mind, but it doesn't exist, but for this I see this issue as a duplicate.

What this option does is to skip generating the C files, which is only useful for manual editing while debugging. Not a user facing option at all.

**Comment by belonesox** [comment]
So, can we discuss here or on another issue other possibility, like option `--stop-on-generating-scons-file-and-shell-script-for-compilation`?

This option would stop Nuitka, generate shell file with Scons command for compilation and leaves it for researcher (experiments with compilation flags, etc)?

**Comment by kayhayen** [comment]
Nuitka puts things in environment variables, on the command line when it calls things, in include files, etc. and is all dirty about this folder contents. This could get cleaned up, but it would also increase the maintenance burden for what exactly. I would much rather see time invested in proper caching, such that it would be close to that in effect.

**Comment by belonesox** [comment]
All these stuff (environment variables, etc) also can be freezed on some  `set-up-envs-and-build-generated-cpp-sources-using-scons.sh` file.

I like to experiment with cpp compile phase (different gcc/ld options, using SAST tools for CPP, etc), without regenerating sources fron Nuitka. May be I would write dirty-hacking-monkey-patching plugin for this, but official option of course would be much better.

**Comment by kayhayen** [comment]
Adding plugin interfaces of general usablity would be great.

Now that I think of it, the call to scons is probably having an "env" provided too, if you capture that, you probably got something repeatable already. I can even imagine that with some form of isExperimental("create-scons-call-scipt") you would write it out, and I would carry that from a PR. Just make it a Python script please, not e.g. a CMD, because then it's automatically cross platform usable.

**Comment by kayhayen** [comment]
Ah, there is also post processing. You definitely want to also do that, only then constants and stuff are going to work, when resources are set, etc. let alone speak of standalone and onefile, so maybe that script doesn't cut it at all. I will let you figure it out though.

**Comment by kayhayen** [comment]
I am closing this now that we merged the quick option. I will however mid term develop this into something that does post processing, and can be called from Nuitka itself, maybe.
