### ISSUE TITLE
AttributeError: module 'nuitka.Options' has no attribute 'getIntendedPythonVersion'

### ISSUE THREAD

**Issue by yash-ahir** [Nuitka/Nuitka#793]
Nuitka version:
`python -m nuitka --version`
```
0.6.8
Python: 3.8.3 (default, May 17 2020, 18:15:42) 
Executable: /usr/bin/python
OS: Linux
Arch: x86_64
```
Nuitka installation steps:
- Tried both `pacman -S nuitka` and `pip install Nuitka`, same result.

Problem:
After installation on a fresh Arch Linux instance it seems that it's trying to call a non existent method for fetching the current version. I didn't find anything about this so here I am.

![Screenshot_20200722_001503](https://user-images.githubusercontent.com/68500326/88094011-7670ad80-cbb0-11ea-9afd-50000b37ebe0.png)

**Comment by kayhayen** [comment]
It seems the package is obsolete and/or broken. Please contact the packager to update, current Nuitka no longer has this.
