### ISSUE TITLE
Issue when including cvxopt library on Linux

### ISSUE THREAD

**Issue by cvpython** [Nuitka/Nuitka#796]
I try to create an exe **on Linux** of a script which uses cvxopt module.

I create the exe with the hinted approach:
`python get-hints.py script.py`
`python nuitka-hints.py script.py`

The compilation successes.
Here are the scripts used for the compilation and some information about my configuration:
[nuitka-hint.zip](https://github.com/Nuitka/Nuitka/files/4959084/nuitka-hint.zip)

`python -m nuitka --version`

> 0.6.8.4
> Python: 3.7.6 (default, Jan  8 2020, 19:59:22) 
> Executable: /anaconda3/envs/Script_Env/bin/python
> OS: Linux
> Arch: x86_64

`conda list`
> _libgcc_mutex             0.1                        main  
> attrdict                  2.0.1                      py_0    conda-forge
> backcall                  0.2.0                      py_0  
> blas                      1.0                         mkl  
> ca-certificates           2020.6.24                     0  
> certifi                   2020.6.20                py37_0  
> cvxopt                    1.2.4           py37hf6e81e8_204    conda-forge
> decorator                 4.4.2                      py_0  
> dsdp                      5.8               h23d7751_1203    conda-forge
> fftw                      3.3.8           nompi_h7f3a6c3_1111    conda-forge
> glpk                      4.65                 h3ceedfd_2  
> gmp                       6.1.2                h6c8ec71_1  
> gsl                       2.6                  h294904e_0    conda-forge
> intel-openmp              2020.1                      217  
> ipython                   7.16.1           py37h5ca1d4c_0  
> ipython_genutils          0.2.0                    py37_0  
> jedi                      0.17.1                   py37_0  
> ld_impl_linux-64          2.33.1               h53a641e_7  
> libblas                   3.8.0                    16_mkl    conda-forge
> libcblas                  3.8.0                    16_mkl    conda-forge
> libedit                   3.1.20191231         h14c3975_1  
> libffi                    3.2.1                hd88cf55_4  
> libgcc-ng                 9.1.0                hdf63c60_0  
> libgfortran-ng            7.3.0                hdf63c60_0  
> liblapack                 3.8.0                    16_mkl    conda-forge
> libstdcxx-ng              9.1.0                hdf63c60_0  
> metis                     5.1.0                hf484d3e_4  
> mkl                       2020.1                      217  
> mkl-service               2.3.0            py37he904b0f_0  
> mkl_fft                   1.1.0            py37h23d657b_0  
> mkl_random                1.1.1            py37h0573a6f_0  
> ncurses                   6.2                  he6710b0_1  
> nuitka                    0.6.8.4            pyh9f0ad1d_0    conda-forge
> numpy                     1.18.5           py37ha1c710e_0  
> numpy-base                1.18.5           py37hde5b4d6_0  
> openssl                   1.1.1g               h7b6447c_0  
> parso                     0.7.0                      py_0  
> pexpect                   4.8.0                    py37_1  
> pickleshare               0.7.5                 py37_1001  
> pip                       20.1.1                   py37_1  
> prompt-toolkit            3.0.5                      py_0  
> ptyprocess                0.6.0                    py37_0  
> pygments                  2.6.1                      py_0  
> python                    3.7.6                h0371630_2  
> python_abi                3.7                     1_cp37m    conda-forge
> readline                  7.0                  h7b6447c_5  
> scipy                     1.4.1            py37h0b6359f_0  
> setuptools                49.2.0                   py37_0  
> six                       1.15.0                     py_0  
> sqlite                    3.32.3               h62c20be_0  
> suitesparse               5.6.0                h717dc36_0    conda-forge
> tbb                       2020.0               hfd86e86_0  
> tk                        8.6.10               hbc83047_0  
> traitlets                 4.3.3                    py37_0  
> wcwidth                   0.2.5                      py_0  
> wheel                     0.34.2                   py37_0  
> xz                        5.2.5                h7b6447c_0  
> zlib                      1.2.11               h7b6447c_3

However, at runtime it **sometimes** crashes:
`./script-dist/script`
> Traceback (most recent call last):
>   File "script.dist/cvxopt/coneprog.py", line 4485, in qp
>   File "script.dist/cvxopt/coneprog.py", line 1764, in coneqp
> ImportError: cannot import name 'misc' from 'cvxopt' (script.dist/cvxopt/__init__.py)

It is due to the fact that the script uses **sometimes** the function _solvers.qp_ (which calls the function _coneqp_ defined in the _coneprog.py_ file) of the cvxopt module.
**Within the definition** of the _coneqp_ function , there are some imports:
`from cvxopt import base, blas, misc`
`from cvxopt.base import matrix, spmatrix`

When, I used the command `python get-hints.py script.py`, the program did not call the _solvers.qp_ function.
So Nuitka did not detect the need of these imports.

I found 2 solutions to fix that problem (which should not be necessary normally):
Solution 1) Run the command `python get-hints.py script.py` and force the script to use the _solvers.qp_ function.
or
Solution 2) Put these imports in the header of the _coneprog.py_ file of the cvxopt module (before the definition of the first function).

Whatever the solution used, there still was a problem at runtime:
> ./script.dist/script: symbol lookup error: script.dist/libmkl_intel_thread.so: undefined symbol: omp_get_num_procs

To solve this problem, I had to copy the libiomp5.so file (located in my python environment) in the script.dist folder.
 
**Please note that these problems happen only on my ubuntu session.
There is no problem when compiling on windows (with the same version of nuitka and cvxopt).**

**Comment by kayhayen** [comment]
Hinted mode is no more supported, and there was never example code to reproduce anything here. I am going to delete this issue therefore, please try again with recent Nuitka.
