### ISSUE TITLE
issue with executable created by nuitka

### ISSUE THREAD

**Issue by bhanuponguru** [Nuitka/Nuitka#801]
so, thankyou nuitka developer for providing wonderfull module. i installed nuitka by pip.
so, for testing, i created helllo world program and i tryed using by deleting all the dpendecnys created by nuitka and runed the executable. so it worked in my pc. i gave it to my friend for testing. so it din't work for him. the problem with this is, if it works on my pc after i deleting dependencys it worked for me so i thought i can distrubute without dependencys. and it dint work in my friends computer. then how could i know this will work or not.
this is the issue

**Comment by kayhayen** [comment]
No thanks for not providing any of the information asked for in the issue template though. Please retry, this time filling out giving information that is not general statements.
