### ISSUE TITLE
problem with lz4 module

### ISSUE THREAD

**Issue by ydkhatri** [Nuitka/Nuitka#802]
Running on macOS 10.15.5, python 3.8
```
$ nuitka3 --version
0.6.9rc6
Python: 3.8.5 (v3.8.5:580fbb018f, Jul 20 2020, 12:11:27) 
Executable: /Users/yogesh/Desktop/mac_apt_test/mac_apt/env/bin/python
OS: Darwin
Arch: x86_64
```
Code to reproduce:
```python
import lz4.block
print(lz4.VERSION)
```
That should print something like `3.1.0` to the console.  
Compiled with
```
$ nuitka3 --follow-imports test_lz4.py
```
Compiles fine, on run errors are:
```
$ ./test_lz4.bin 
Traceback (most recent call last):
  File "/Users/yogesh/Desktop/testing/test_lz4.py", line 1, in <module>
    import lz4.block
  File "/Users/yogesh/Desktop/testing/env/lib/python3.8/site-packages/lz4/__init__.py", line 14, in <module lz4>
    from ._version import (  # noqa: F401
ModuleNotFoundError: No module named 'lz4._version'
```
This is the standard lz4 compression library installed via `pip install lz4`

**Comment by kayhayen** [comment]
This just worked for me on Windows, do we think its a macOS only issue?

**Comment by ydkhatri** [comment]
> This just worked for me on Windows, do we think its a macOS only issue?

Perhaps, I only need this for mac, so didn't test windows.

**Comment by kayhayen** [comment]
Can you try develop version please, this might be an importing issue long fixed.

**Comment by ydkhatri** [comment]
I believe I was running latest code when I posted this. Is 0.6.9rc6 not development version?

**Comment by kayhayen** [comment]
Closing for lack of feedback.
