### ISSUE TITLE
Problems with dlib

### ISSUE THREAD

**Issue by gfyts0123** [Nuitka/Nuitka#803]
Hello， when I run main.exe on a computer without python environment, it shows like this

https://i.stack.imgur.com/2UDk2.png

Line 14 is 
```
import dlib
```
Other imports are OK
Is there any ways to solve this problem please?

**Comment by kayhayen** [comment]
Not filling out the issue template is not OK, and of course I am not going to look at screenshots even if they contained the info, it would be inaccessible.
