### ISSUE TITLE
Question: Optimizing multiple times

### ISSUE THREAD

**Issue by cooperdk** [Nuitka/Nuitka#808]
Hey,

On Nuitka develop (current), is there any reason why it optimizes modules multiple times? I have counted as many as about ten times, and since I am compiling a Django app, this takes quite some time - about an hour or so every time.

I am running with these arguments (to ensure inclusion of necessary modules, else it won't work):

nuitka --show-progress --show-scons --show-modules --follow-imports --nofollow-import-to=nuitka --nofollow-import-to=setuptools --include-package=django --include-package=django_extensions --include-module=rest_framework --include-module=mptt --include-module=PIL --include-module=(part of program) --include-module=(part of program) --include-module=(part of program) --include-module=(part of program) --include-module=dal --include-module=dal_contenttypes --include-module=dal_genericm2m --include-module=dal_gm2m --include-module=dal_legacy_static --include-module=dal_queryset_sequence --include-module=dal_select2_tagging --include-module=dal_select2_taggit --include-module=dal_genericm2m_queryset_sequence --include-module=dal_gm2m_queryset_sequence --include-module=dal_queryset_sequence --include-module=dal_select2 --include-module=dal_select2_queryset_sequence --include-module=dj_static --include-module=mptt --include-module datetime --output-dir=dist\ --windows-icon=h:\yapo\videos\static\favicon.ico (part of program).py

**Comment by kayhayen** [comment]
Nuitka is optimizing in multiple passes, as every optimization may enable others, without a clear knowledge, which ones these might be. So it stops optimization of a module only once it finds nothing anymore to do.

**Comment by kayhayen** [comment]
As an aside, `--include-package=django` and `--include=django_extensions` are definitely a recipe to make it include many unused modules. 

And once caching of Nuitka module optimization results is implemented, you won't have to redo it after the first time, letting you get away with compiling all the world for no good reason.

**Comment by cooperdk** [comment]
I get that, but it doesn't work any other way, due to how Django imports it's stuff. It doesn't even work even though I import modules in the code.
Well, maybe it does work if I import the specific modules used, but then the list of imports is doubled and it would take forever using the trial-and-error method. I used the same imports as in PyInstaller (which I would prefer not using), but with Nuitka it only worked with includes and follow imports.
That aside, I haven't experienced the use of cache at all. It recompiles and rebuilds every time, even though the files are there, even if I don't change anything in the code.

Thanks for your response, by the way :-)
