### ISSUE TITLE
Seg fault on aarch64 using gcc

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#809]
Using Nuitka-0.6.8.4 on Python 3.8
```
[   85s] Running the basic tests with options '' with python3.8:
[   85s] Run '/usr/bin/python3 ./tests/basics/run_all.py search' in '/home/abuild/rpmbuild/BUILD/Nuitka-0.6.8.4'.
[   85s] Using concrete python 3.8.5 on aarch64
[   85s] Comparing output of 'Asserts.py' using '/usr/bin/python3' with flags silent, expect_success, remove_output, recurse_all, original_file, cpython_cache, plugin_enable:pylint-warnings ...
[  102s] --- /usr/bin/python3 (stdout)
[  102s] +++ nuitka (stdout)
[  102s] 
[  102s] @@ -1,9 +1 @@
[  102s] 
[  102s] -Function that will assert.
[  102s] -Raised <class 'AssertionError'> 
[  102s] -Function that will not assert.
[  102s] -No exception.
[  102s] -Function that will assert with argument.
[  102s] -Raised <class 'AssertionError'> argument
[  102s] -Assertion with tuple argument.(3,)
[  102s] -Assertion with plain argument.3
[  102s]  
[  102s] --- /usr/bin/python3 (stderr)
[  102s] +++ nuitka (stderr)
[  102s] 
[  102s] @@ -1 +1,4 @@
[  102s] 
[  102s] +collect2: fatal error: ld terminated with signal 11 [Segmentation fault]
[  102s] +compilation terminated.
[  102s] +scons: *** [/var/tmp/basics/python3.8-nodebug/Asserts.bin] Error 1
[  102s]  
[  102s] Exit codes 0 (CPython) != 1 (Nuitka)
[  102s] Error, outputs differed.
[  102s] Error exit! 1
```
https://build.opensuse.org/package/rdiff/home:jayvdb:py-bridge/python-Nuitka?linkrev=base&rev=44

It does not occur on armv7l

**Comment by Taiwanchaoh** [comment]
I ran into the same error code several days before. I am not sure why this problem happened. But, I can resolve this issue by using clang instead of gcc. If you are using `python -m nuitka` syntax, you can add `--clang` flag to change the compiler. But, for my case, I have to modify some of the default setting to force nuitka uses clang when I use `python setup.py bdist_nuitka`.

**Comment by jayvdb** [comment]
ha! thanks for reminding me of https://github.com/Nuitka/Nuitka/issues/489 ; I had forgotten my own solution for this ;-)

**Comment by jayvdb** [comment]
That will probably also solve https://github.com/Nuitka/Nuitka/issues/812 , and maybe also https://github.com/Nuitka/Nuitka/issues/813

**Comment by jayvdb** [comment]
Re-confirmed, this is fixed by using clang instead of gcc.

I think nuitka should default to clang for these arch.

I can force it with
`sed -i 's/return options.clang/return True/' nuitka/Options.py`

But we need a better way of doing that.

**Comment by jayvdb** [comment]
For running the test suite, `CC=clang` works.

**Comment by AetherPrior** [comment]
Is this still open?

**Comment by jayvdb** [comment]
yes, re-tested and failed on the 0.6.9.1 release, and nothing in recent commits indicates it has been fixed since then.

**Comment by jayvdb** [comment]
As https://github.com/Nuitka/Nuitka/issues/813 is now fixed, it is possible that this issue is also fixed.  I've got a build scheduled at https://github.com/Nuitka/Nuitka/issues/813 , but it is blocked by lots of other deps.

**Comment by jayvdb** [comment]
Using gcc 10.2.1, and Nuitka 0.6.11, this problem no longer occurs for me.
