### ISSUE TITLE
Cant compile pygame

### ISSUE THREAD

**Issue by Ben-Faessler** [Nuitka/Nuitka#814]
I try to compile pygame2.0.0dev10 with nuitka but this give me a error:
Nuitka-Plugins:INFO: implicit-imports: Implicit module 'pygame.event.Event' suggested by 'pygame.mixer' not found.
Can i fix this?

**Comment by kayhayen** [comment]
It's not an error, it's an info, and one that will not be given anymore starting with 0.6.9, because we just cannot tell what version of package may or may not have an implicit dependency. So now we try it, and when it's there, we use it.
