### ISSUE TITLE
If a resource is included along with the code, just copy it over during compilation

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [Nuitka/Nuitka#819]
DESCRIPTION:
It's an encumbrance to have to copy non-Python resources from my source directory tree to my output directory tree after using Nuitka. Resources that are found among the Python source files ought just be copied over as part of building the output.

ENVIRONMENT:
* My employer's flavor of gmacOS 10.15.6
* Python 3.6.8
* Nuitka 0.6.8.4

STEPS TO REPRODUCE:
* `python -m pip install --upgrade importlib_resources nuitka paramiko requests zeroconf`
* Unzip, untar, and `cd` into [this code](https://github.com/Nuitka/Nuitka/files/5110677/representative-0.0.20200813144015583612.tar.gz)
* `python -m nuitka --output=2020-08-21 --standalone --show-progress --show-scons --python-flag=no_site representative/__main__.py`
* `python -m nuitka --output=2020-08-21 --standalone --show-progress --show-scons --python-flag=no_site representative/__main__.py`
* `./2020-08-21/__main__.dist/__main__`

EXPECTED RESULT:
`./2020-08-21/__main__.dist/__main__` will show the same output as would have been shown by installing the `representative` sdist and then running `python -m representative`:
```
Embedded text is 47 long!
Instantiated an SSHClient: <something that looks like an object instance at a memory location>
```

OBSERVED RESULT:
`FileNotFoundError: 'resource.txt' resource not found in 'representative.util'` (plus other stack bits).

WORKAROUND:
After using Nuitka to build, `mkdir -p fct-2020-08-21/__main__.dist/representative/util && cp representative/util/resource.txt fct-2020-08-21/__main__.dist/representative/util`.

ADDITIONAL INFORMATION:
There's some related discussion in [this earlier issue](https://github.com/Nuitka/Nuitka/issues/649) but the offered solution seems heavyweight (learn the plugin system and author a plugin?); simply including the data resources found among the Python source files strikes me as likely good ergonomics.

**Comment by kayhayen** [comment]
I am unsure how to deal with this. While I have this on my mind, I cannot say that I am thrilled to implement data files inside of Nuitka. This is not very actionable without concrete ideas. Maybe a special comment could indicate data files needed to Nuitka or generally for freezing. Setting a standard like that would be a solution. Adding command line options to Nuitka feels wrong.

**Comment by lxbrass** [comment]
I like the idea of a special file in non python code or data directories, hinting what to do with the contents of that directory. I usually do this inside a build.sh script after nuitka executes, but I understand the benefits of letting nuitka care about it.  The convenience of a nuitka one liner is addictive, so is the solid deploy experience that --embedded provides. This would add to that.

_nuitka.command.freeze or _nuitka.directive.freeze inside directories or perhaps a (more complex) _nuitka.manifest with instructions on the source directory.

**Comment by ThatXliner** [comment]
[MANIFEST.ini](https://packaging.python.org/guides/using-manifest-in/) ?

**Comment by Ben-Faessler** [comment]
So something like this that scans the code for open statements and copies the used files to a subdirectory of the output? If so, I would like to help.

**Comment by kayhayen** [comment]
So, the latest release has an option `--include-package-data` that accepts patterns, e.g. `*` would include everything that is found, which might not be limited enough yet though. But it's considered the solution.

Changelog says

-  Onefile: Added command line options to include data files. These are
   ``--include-package-data`` which will copy all non-DLLs and
   non-Python files of package names matching the pattern given. And
   ``--include-data-file`` takes source and relative target file paths
   and copies them. For onefile this is the only way to include files,
   for standalone mode they are mostly a convenience function.

**Comment by kayhayen** [comment]
@ThatXliner the manifest file will be used if you create a wheel already. For binaries, it tends to be unused, but I would definitely welcome a PR, that attempts to copy files from there automatically.
