### ISSUE TITLE
Easy-mode sdist-to-output

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [Nuitka/Nuitka#820]
DESCRIPTION:
When an sdist contains a `fooo/__main__.py` file it enables after installation execution of `python -m fooo`. It would be nice if Nuitka given such an sdist produced the reasonably-expected output with no other configuration required.

EXAMPLE:
`python -m nuitka --output=2020-08-21 --standalone --show-progress --show-scons --python-flag=no_site representative-0.0.20200813144015583612.tar.gz` given [this sdist](https://github.com/Nuitka/Nuitka/files/5110677/representative-0.0.20200813144015583612.tar.gz) could produce `2020-08-21/__main__.dist/__main__` that when executed displayed the same behavior as would be displayed had the sdist been installed in a Python environment and executed:
```
Embedded text is 47 long!
Instantiated an SSHClient: <something that looks like an object instance at a memory location>
```
.

**Comment by kayhayen** [comment]
For packages, no standalone is available and makes no sense. Simply compile a runner that does the import of the main, and be good with it. I believe, this could also be a `__main__.py`, can it not be?

**Comment by nathanielmanistaatgoogle** [comment]
I'm not sure that I'm following - are you suggesting that given an sdist like [this one](https://github.com/Nuitka/Nuitka/files/5110677/representative-0.0.20200813144015583612.tar.gz) that there's something better to do with it than use Nuitka to produce a standalone directory? ... or are you saying that sdists like that one oughtn't exist, and that when one has a tool that one is distributing that way that one ought distribute it some other way?

**Comment by nathanielmanistaatgoogle** [comment]
(Regarding the `needs_example` label: [the sdist](https://github.com/Nuitka/Nuitka/files/5110677/representative-0.0.20200813144015583612.tar.gz) is called "representative" because it really is representative of some other code that I'm writing that unfortunately I am not able to share.)

**Comment by kayhayen** [comment]
Binaries and not modules. I do not think I want to spare the need to create a runner for a module to use it as a program.
