### ISSUE TITLE
Installation Error when I run the code --Need help

### ISSUE THREAD

**Issue by a740615405** [Nuitka/Nuitka#822]
hello:
When I run the below code, there is a message box for Installation Error, what's wrong with my program?
> python -m nuitka --standalone --mingw64 hello.py

![image](https://user-images.githubusercontent.com/50734178/91009492-41260800-e613-11ea-8d44-930c64a02d58.png)

**Comment by kayhayen** [comment]
Not filling out the issue template is not OK, and screenshots are not good enough, or even wanted.
