### ISSUE TITLE
Implicit dependencies of pyglet are missing

### ISSUE THREAD

**Issue by AmandaBeuno** [Nuitka/Nuitka#823]
python -m nuitka --version

0.6.8.4
Python: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
Executable: C:\Python37\python.exe
OS: Windows
Arch: x86_64

* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.

Nuitka is installed using pip install nuitka
Python is installed using the 64-bit installer

* If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
  that demonstrates the issue i.e a small piece of code which reproduces
  the issue and can be run with out any other (or as few as possible)
  external dependencies.

```
import pyglet

window = pyglet.window.Window()
label = pyglet.text.Label('Hello, world',
                      font_name='Times New Roman',
                      font_size=36,
                      x=window.width//2, y=window.height//2,
                      anchor_x='center', anchor_y='center')

@window.event
def on_draw():
    window.clear()
    label.draw()

pyglet.app.run()
```

When running nuitka with these parameters:

> python -m nuitka --standalone --follow-imports --show-progress --mingw64 PygletTest.py

the example compiles with no errors, but when run, it provides the following error:

> Traceback (most recent call last):
 

>  File "C:\PYGLET~1.DIS\pyglet\__init__.py", line 334, in __getattr__

> AttributeError: 'NoneType' object has no attribute 'Window'

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
> File "C:\PYGLET~1.DIS\PygletTest.py", line 3, in <module>
> File "C:\PYGLET~1.DIS\pyglet\__init__.py", line 340, in __getattr__
> ModuleNotFoundError: No module named 'pyglet.window'

On the other hand, when running nuitka with the following parameters:

> python -m nuitka --standalone --show-progress --show-modules --mingw64 --warn-implicit-exceptions --warn-unusual-code -->plugin-enable=tk-inter --plugin-enable=multiprocessing --disable-dll-dependency-cache --include-module=pyglet.window >--nofollow-import-to=pyglet.libs.x11 --jobs=3 PygletTest.py

It fails to compile with scons producing the following error:

> scons: *** [module.pyglet.gl.glext_arb.o] Error 1

Please let me know if there any pointers on how to make it work. 

Amanda

**Comment by kayhayen** [comment]
```
# Fool py2exe, py2app into including all top-level modules (doesn't understand
# lazy loading)
if False:
    from . import app
    from . import canvas
    from . import clock
    from . import com
    from . import event
    from . import font
    from . import gl
    from . import graphics
    from . import input
    from . import image
    from . import lib
    from . import media
    from . import model
    from . import resource
    from . import sprite
    from . import shapes
    from . import text
    from . import window

```

So Nuitka is not fooled by this, optimizing it away.

**Comment by kayhayen** [comment]
So, I guess, this can be done with implicit imports only. It's really sad, the lazy loading non-sense that they do makes barely sense and has generic implementations too, I think it's called `demandimport` on PyPI.

**Comment by kayhayen** [comment]
This is now on the factory branch.

**Comment by AmandaBeuno** [comment]
@kayhayen Thank you for the update! 

I downloaded the factory branch and installed it. I tried running both commands with the same results. 

Command #1
> python -m nuitka --standalone --follow-imports --show-progress --mingw64 PygletTest.py

Command #2

> python -m nuitka --standalone --show-progress --show-modules --mingw64 --warn-implicit-exceptions --warn-unusual-code -->plugin-enable=tk-inter --plugin-enable=multiprocessing --disable-dll-dependency-cache --nofollow-import-to=pyglet.libs.x11 --jobs=3 PygletTest.py

Is there anything I am missing ? 

Amanda

**Comment by kayhayen** [comment]
Should be, works for me now.

**Comment by DoAltPlusF4** [comment]
Pyglet contributor here.
I have tried installing the factory branch with the same results as Amanda, is there anything we can do on the Pyglet side of things to get this fixed?

**Comment by kayhayen** [comment]
That's strange @DoAltPlusF4 I was pretty sure it works for me, I even retried after Amanda disconfirmed. How sure are we you follow this one: http://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
This code should be there:

```

        elif full_name == "pyglet":
            yield "pyglet.app"
            yield "pyglet.canvas"
            yield "pyglet.clock"
            yield "pyglet.com"
            yield "pyglet.event"
            yield "pyglet.font"
            yield "pyglet.gl"
            yield "pyglet.graphics"
            yield "pyglet.input"
            yield "pyglet.image"
            yield "pyglet.lib"
            yield "pyglet.media"
            yield "pyglet.model"
            yield "pyglet.resource"
            yield "pyglet.sprite"
            yield "pyglet.shapes"
            yield "pyglet.text"
            yield "pyglet.window"
```

Make sure you find it in your copy of Nuitka, and let me know, if you execute it. That is basically the list from the code I mentioned above, and after that it just worked. Should it ever become more dynamic, we could extract it from the source code, but it ought to be what it takes?

**Comment by DoAltPlusF4** [comment]
I'm attempting compilation now after installing factory with 
`python -m pip install -U "https://github.com/Nuitka/Nuitka/archive/factory.zip"`.

I managed to find those changes here: (`nuitka/plugins/standard/ImplicitImports.py`)
![image](https://user-images.githubusercontent.com/57148878/92109456-f8bfd480-ede0-11ea-9c05-7ef0ae578dbf.png)

Now we wait :P

**Comment by DoAltPlusF4** [comment]
Ok, I have run the compilation with the following command:
`python -m nuitka --standalone --follow-imports --show-progress --verbose --mingw64 main.py`
(The python file is the same that Amanda used.)

This still does not seem to work, I have attached the output here: (Ends with `scons: *** [module.pyglet.gl.glext_arb.o] Error 1`)
[nuitka-output.txt](https://github.com/Nuitka/Nuitka/files/5168368/nuitka-output.txt)

If you need me to send anything else let me know :)

**Comment by kayhayen** [comment]
I see, it's working, what is not is your gcc though. Would trying out MSVC be an option? The lack of any compiler error output is very disappointing. But very likely it's hitting a scalability limit on your machine (not mine), due to the strange code in that module, I have a fix for that coming though, shouldn't take long.

**Comment by DoAltPlusF4** [comment]
I can try out VC, is there a specific cmd flag I need to pass to use it?

**Comment by DoAltPlusF4** [comment]
Just attempted compilation again (mingw64) with [the new commit](https://github.com/Nuitka/Nuitka/commit/309dccd83594318c47c1482b41fa9d1024d59a1b) and it seems to work fine!
Compilation is still a little slow but that is probably to be expected with such a large module.

**Comment by kayhayen** [comment]
The slowness should also be addressed, and it's released now.
