### ISSUE TITLE
Should sys.executable return an empty string, None or the program path when compiled (standalone),  instead of the interpreter path?

### ISSUE THREAD

**Issue by lxbrass** [Nuitka/Nuitka#825]
Python 3.6.9
Nuitka 0.6.8 
Linux - ubuntu 18.04.4 LTS

The function platform.libc_ver() fails (file not found exception) when called from within a nuitka compiled (--standalone)  program running on a machine without a Python interpreter installed. 

Internally, platform.libc_ver() uses sys.executable which is documented to be:

_"A string giving the absolute path of the executable binary for the Python interpreter, on systems where this makes sense. If Python is unable to retrieve the real path to its executable, sys.executable will be an empty string or None."_

ref: https://docs.python.org/3/library/sys.html#sys.executable

In the nuitka compiled (--standalone) program, sys.executable value is the interpreter path of the python interpreter used to compile the program, which may be not present in the machine where it is deployed to.

Sample code attached

[platform_libcver_case.zip](https://github.com/Nuitka/Nuitka/files/5141206/platform_libcver_case.zip)

**Comment by kayhayen** [comment]
I found this in a separate issue just the other day. The fix is on factory. Not sure, if not setting leaves it at `None` though. In that case, we would have to actively set the value.

**Comment by kayhayen** [comment]
Yup, after the latest change, the binary itself is used for `sys.executable` which is against the spec you are citing. Going to make it set to None.

**Comment by lxbrass** [comment]
It is more correct. However, for the particular purposes of platform.libc_ver(), which is a bit hackish because it wants to scan the binary to determine the glibc version it is liked to, the actual solution is perhaps better than None. Without knowing other uses of sys.executable within python itself, I am not sure which is best.

https://github.com/python/cpython/commit/7c43b801503c802ed6ea4b811f5bc73791249d94

**Comment by kayhayen** [comment]
People would use `sys.executable` in an attempt to launch a Python script. With that being the executable itself, this will spell disaster. Is anything important using `platform.libc_ver()` ?

**Comment by lxbrass** [comment]
No, it is not important, only for reporting. A binary compiled on a newer/fresher system would complain about glibc version on an older machine so we were just collecting info. Will do that using system programs.

Thanks!

**Comment by kayhayen** [comment]
This is part of the current release.

**Comment by sefgit** [comment]
How to detect if python script.py is run as script.exe or script.py after converted using nuitka ?
cf_Freeze set sys.executable = script.exe

**Comment by kayhayen** [comment]
Check out the User Manual of Nuitka, it has all the information about how to detect being compiled.
