### ISSUE TITLE
A possible typo in README.rst

### ISSUE THREAD

**Issue by zenyusy** [Nuitka/Nuitka#829]
Hello,

Found a kinda ambiguous sentence in the "Install Python (64 Bits)" section of README.rst :

https://github.com/Nuitka/Nuitka/blob/b4a167acbf7b4f68fa18711689b1f188659e04bd/README.rst#install-python-64-bits

> - Select one of Windows x86-64 web-based installer (64 bits Python, recommended) or x86-64 executable (32 bits Python) installer

IMHO, x86-64 refers to 64 bits rather than 32 bits.

Guess this sentence might be something like "Select one of Windows web-based installer or executable installer (x86-64 for 64 bits Python, recommended; or x86 for 32 bits Python)"

**Comment by kayhayen** [comment]
I agree, and fixed this, will appear on Website soon too. Closing now, as it cannot really get lost anymore.
