### ISSUE TITLE
I'd like to use the C file generated by the build folder to port to Android.

### ISSUE THREAD

**Issue by coolmian** [Nuitka/Nuitka#830]
I'd like to use the C file generated by the build folder to port to Android.
If I don't want the executables in the dist, just use the build folder and run it in a C environment, will that work? 
In order to accomplish this, do I need to be clear on the details from the build folder to the dist folder? If anyone can help, I'd appreciate it.

**Comment by kayhayen** [comment]
Cross-compilation is not support. Native compilation on Android would work though, at least I know that people have used ARM machines to compile with Nuitka, I don't know how though.
