### ISSUE TITLE
Error: 'compiled_method' object is not connected

### ISSUE THREAD

**Issue by CineEncoder** [Nuitka/Nuitka#833]
Hi!

I have a project developed in Python 3.8 on GitHub:
https://github.com/CineEncoder/cine-encoder

I compiled it using Nuitka, and the compiled program throws an error and crashes, 
despite the fact that when running in Python, the program works fine.
Here is a link to the compiled program:
https://github.com/CineEncoder/cine-encoder/releases/download/2.4/cine-encoder-2.4_other_linux_x86_64.zip

To compile, I used the command:

`python -m nuitka --standalone --plugin-enable=qt-plugins main.py`

Versions:

```
[helg@Houston ~]$   python -m nuitka --version
0.6.8
Python: 3.8.5 (default, Sep  5 2020, 10:50:12) 
Executable: /usr/bin/python
OS: Linux
Arch: x86_64
```

How did I install Nuitka and Python:
- pip (Manjaro Linux), 
- also tryed with Nuitka.deb from Ubuntu 20.04, the result is the same,
- all without virtualenv

The console output:

```
[helg@Houston ~]$ /run/media/helg/GOODRAM-SDB/MakePackage/BIN/Linux/cine-encoder-2.4_other_linux_x86_64/App/CineEncoder.run 
Fontconfig warning: "/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 684, resource id: 14689761, major code: 40 (TranslateCoords), minor code: 0
HEVC
Traceback (most recent call last):
  File "/run/media/helg/GOODRAM-SDB/MakePackage/BIN/Linux/cine-encoder-2.4_other_linux_x86_64/App/main.py", line 1104, in progress_1
TypeError: 'compiled_method' object is not connected
Aborted (core dumped)
[helg@Houston ~]$ 
```

I think this corresponds to the following lines of code in Python (in file main.py):

```
...
1135   if (percent >= 50) and (calling_pr_1 is True):
1136        self.procedure_1.finished.disconnect(self.error)
1137        self.procedure_1.finished.connect(self.add_metadata)
1138        calling_pr_1 = False
...
```

**Comment by kayhayen** [comment]
A more minimal reproducer will be needed. I can't compile everybody's program and try to reduce the test case myself.

**Comment by newdive** [comment]
i have also encountered this same issue.
but after some trial and error,  i managed to solve this using a instance variable to store the receiver function  and then pass that instance variable to `disconnect` function
here is a rough illustration of my solution:
```
def __init__(self):
    # declare a instance variable for later use
    self.receiverFuncVar = None

# someSignal.connect(self.actualReceiver)  is rewritten to 
self.receiverFuncVar = self.actualReceiver
someSignal.connect(self.receiverFuncVar )

# someSignal.disconnect(self.actualReceiver)  is rewritten to 
someSignal.disconnect(self.receiverFuncVar )
```
i am not sure why this solves the issue,  but i think this could give you some hint
(

> i have check that `self.receiverFuncVar==self.actualReceiver` is always `True` at runtime
> but `id(self.receiverFuncVar)`  is always different from `id(self.actualReceiver)`  
> then i check the generated c code ,  but i can only  guess that `LOOKUP_ATTRIBUTE` could have something to do with this
  due to my poor knowledge of nuitka and c .     -.-||   Forgive me if i am wrong

)
FYI
i am using `python3.6` , `nuitka 0.6.8.4` , `PyQt5`

**Comment by kayhayen** [comment]
Still needs a minimal reproducer, otherwise I can't analyse this.

**Comment by newdive** [comment]
OK   here is my reproducer.  

[task_manager.zip](https://github.com/Nuitka/Nuitka/files/5690285/task_manager.zip)

**Comment by Pro100rus32** [comment]
I have a similar problem.
![image](https://user-images.githubusercontent.com/64806740/105398373-59866700-5c33-11eb-8cba-7fd19cadf9ad.png)


`python -m nuitka --clang --windows-disable-console --standalone --windows-uac-admin --windows-icon-from-ico=E:\TEST\TEST\Media\Sp7EYBpX_hY.ico --output-dir=E:\TEST\TEST\Current_build --plugin-enable=multiprocessing --plugin-enable=numpy --plugin-enable=qt-plugins "E:\TEST\TEST\main.py"`

![image](https://user-images.githubusercontent.com/64806740/105398071-f1378580-5c32-11eb-94b7-7e28596ba560.png)

**Comment by Tspm1eca** [comment]
I having same problem too.

**Comment by kayhayen** [comment]
@newdive thanks for the reproducer, going to look at it later this week

**Comment by kayhayen** [comment]
I am having a suspect that this is a PyQt5 regression, can you people check with older versions of it, from say beginning 2020, I am pretty sure this worked before.

**Comment by kayhayen** [comment]
so, when trying to reproduce this @newdive I found it working with this:

```
PyQt5==5.15.1
PyQt5-sip==12.8.1
PyQtWebEngine==5.15.2
```

But with a PyPI update to 5.15.3, the `PyQt5.QtCore` fails to load during Nuitka compile time, which is something @Pro100rus32 may have reported before, which would indicate it's entirely broken. As an aside 5.15.2 was working for me now too.

**Comment by kayhayen** [comment]
And yup, 

```
$ /c/Python38/python task_manager.py
Traceback (most recent call last):
  File "task_manager.py", line 2, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: DLL load failed while importing QtCore: Das angegebene Modul wurde nicht gefunden.
```

it's not working with your code either with CPython, naturally not interested in this. I am attaching a tag factory, as I have only looked at it with that, and I did fix something related to PyQt5 recently. Since 0.6.13 is coming soon, no point in checking if it's a stable bug, but you are welcome to verify.

**Comment by kayhayen** [comment]
For lack of feedback and under the assumption it's either invalid or a duplicate, I will make it the later and close it now that the change is the current pre-release and soon in a release.

**Comment by maplelost** [comment]
> I have a similar problem. ![image](https://user-images.githubusercontent.com/64806740/105398373-59866700-5c33-11eb-8cba-7fd19cadf9ad.png)
> 
> ![image](https://user-images.githubusercontent.com/64806740/105398071-f1378580-5c32-11eb-94b7-7e28596ba560.png)
> 
> UPD: I fixed this problem by replacing the line.

@Pro100rus32 
Do you remember how did you fix this problem? The solution below doesn't work for me. Thx
> ```
> def __init__(self):
>     # declare a instance variable for later use
>     self.receiverFuncVar = None
> 
> ...
> # someSignal.connect(self.actualReceiver)  is rewritten to 
> self.receiverFuncVar = self.actualReceiver
> someSignal.connect(self.receiverFuncVar )
> ...
> # someSignal.disconnect(self.actualReceiver)  is rewritten to 
> someSignal.disconnect(self.receiverFuncVar )
> ```

**Comment by kayhayen** [comment]
Don't use PyQt5, use PySide2 or PySide6.
