### ISSUE TITLE
ModuleNotFoundError: No module named 'win32com'

### ISSUE THREAD

**Issue by AmandaBeuno** [Nuitka/Nuitka#835]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

  python -m nuitka --version

- 0.6.9rc8
Python: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
Executable: C:\Python37\python.exe
OS: Windows
Arch: x86_64

- 0.6.8.4
Python: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
Executable: C:\Users\N\AppData\Local\Programs\Python\Python37\python.exe
OS: Windows
Arch: x86_64

* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.

pip

* If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
  that demonstrates the issue i.e a small piece of code which reproduces
  the issue and can be run with out any other (or as few as possible)
  external dependencies.

`import win32com
import winerror
import pythoncom

print("Hello, World!")`

> python -m nuitka --standalone --show-progress --mingw64 main.py

The issue here is that the py file compiles fine. But when running I end up with the "ModuleNotFoundError" for:

- "win32com"
- if I comment out the win32com import, I end up with the same error for the "winerror" module. 
- Commenting out the import winerror module, i end up with the same result for the "pythoncom" module

In the case of the "pythoncom" error, I tried copying pythoncom37.dll and pywintypes37.dll to the main.dist folder but it doesn't work.

All the best, 
Amanda

**Comment by kayhayen** [comment]
This is solved in the current stable release, and was for some time on develop before that.

**Comment by AmandaBeuno** [comment]
> This is solved in the current stable release, and was for some time on develop before that.

Thank you for your help @kayhayen !

I got these results using the most recent stable release 0.6.8.4 and again using this factory version 0.6.9rc8. 

Would appreciate any pointers. 

Thanks,

**Comment by AmandaBeuno** [comment]
When I run this command 

> python -m nuitka --standalone --show-progress --verbose --python-flag=-v main.py

I notice the following line when the exe file run:

> import win32com # considering responsibility
> import win32com # denied responsibility
> Traceback (most recent call last):
>    File "D:\Projects\ic\pygletO.dist\pygletO.py", line 1, in <module>
>    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>    File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
>    ModuleNotFoundError: No module named 'win32com'

Thanks
