### ISSUE TITLE
Pandas ModuleNotFoundError: No module named 'pandas._libs.tslibs.base'

### ISSUE THREAD

**Issue by bekatd** [Nuitka/Nuitka#837]
Creating new issue, since its still definitely bug in the develop version too

- 0.6.9
- Python: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
- Executable: C:\Users\wol\AppData\Local\Programs\Python\Python37\python.exe
- OS: Windows
- Arch: x86_64

Minimum reproducible example:

`example.py`:
```
import pandas as pd

def main():
    inp = input('enter')

if __name__ == '__main__':
    main()

```
nuitka command:
`python -m nuitka --mingw64 --standalone --show-progress --show-scons --enable-plugin=numpy example.py`

result after running generated `.exe` file:
```
Traceback (most recent call last):
  File "C:\Users\wol\Desktop\example\193CB~1.DIS\pandas\__init__.py", line 30, in <module pandas>
  File "C:\Users\wol\Desktop\example\193CB~1.DIS\pandas\_libs\__init__.py", line 13, in <module pandas._libs>
  File "pandas\_libs\hashtable.pxd", line 8, in init pandas._libs.interval
  File "pandas\_libs\missing.pxd", line 11, in init pandas._libs.hashtable
  File "pandas\_libs\tslibs\nattype.pxd", line 9, in init pandas._libs.missing
  File "C:\Users\wol\Desktop\example\193CB~1.DIS\pandas\_libs\tslibs\__init__.py", line 30, in <module pandas._libs.tslibs>
  File "pandas\_libs\tslibs\base.pxd", line 4, in init pandas._libs.tslibs.conversion
ModuleNotFoundError: No module named 'pandas._libs.tslibs.base'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\wol\Desktop\example\193CB~1.DIS\example.py", line 1, in <module>
  File "C:\Users\wol\Desktop\example\193CB~1.DIS\pandas\__init__.py", line 38, in <module pandas>
ImportError: C extension: No module named 'pandas._libs.tslibs.base' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
```

**Comment by bekatd** [comment]
As a workaround explicitly importing missing libraries solves the issue

`import pandas._libs.tslibs.base`

**Comment by kayhayen** [comment]
To be honest, I can't compile Pandas myself, this has to be delayed until this is more practical for debuging.

**Comment by kayhayen** [comment]
After the recent scalability fix on develop, it seems Pandas has become managable again, my standalone tests reproduce the issue now:

> +Traceback (most recent call last):
> +  File "/home/nuitka-buildslave/slave/standalone-Py38/build/tests/standalone/PandasUsing.dist/pandas/__init__.py", line 30, in <module>
> +  File "/home/nuitka-buildslave/slave/standalone-Py38/build/tests/standalone/PandasUsing.dist/pandas/_libs/__init__.py", line 13, in <module>
> +  File "/home/nuitka-buildslave/slave/standalone-Py38/build/tests/standalone/pandas/_libs/hashtable.pxd", line 8, in init pandas._libs.interval
> +  File "/home/nuitka-buildslave/slave/standalone-Py38/build/tests/standalone/pandas/_libs/missing.pxd", line 11, in init pandas._libs.hashtable
> +  File "/home/nuitka-buildslave/slave/standalone-Py38/build/tests/standalone/pandas/_libs/tslibs/nattype.pxd", line 9, in init pandas._libs.missing
> +  File "/home/nuitka-buildslave/slave/standalone-Py38/build/tests/standalone/PandasUsing.dist/pandas/_libs/tslibs/__init__.py", line 30, in <module>
> +  File "/home/nuitka-buildslave/slave/standalone-Py38/build/tests/standalone/pandas/_libs/tslibs/base.pxd", line 4, in init pandas._libs.tslibs.conversion
> +ModuleNotFoundError: No module named 'pandas._libs.tslibs.base'

My traceback is exhibiting the same strangeness as yours. The Cython compiled stuff, i.e. the ones with the .pxd are not including the standalone directory in the `__file__` object. This might be a bug by itself, and one that can potentially cause it to not find its ways. I don't think this is the case here though. I need to investigate if this is affecting other extension modules too, wrong values here can lead to all sorts of errors. But I think it may just take the current directory and use it for `__file__`, and that would explain the difference between our stacks (mine is absolute, yours is relative).

What I find strange is that the last line of the stack is appearing to come from the very file that it is complaining about as to be missing, but that might be something that Cython just does, like a partial inlining.

**Comment by kayhayen** [comment]
I just checked, the wrong `__file__` values are Cython specific and probably due to some hardcoding that may not affect the `__file__` value at all, so that's harmless.

**Comment by kayhayen** [comment]
Seems I forgot about this, but my CI presented me with it again, going to include the missing pandas specific implicit import in the next release.

**Comment by kayhayen** [comment]
This specific implicit dependency should now be there, not sure if it's the last one, my CI times out after 2h of build, and the pandas tests are hitting this most of the time.

**Comment by EBenkler** [comment]
> 
> 
> This specific implicit dependency should now be there, not sure if it's the last one, my CI times out after 2h of build, and the pandas tests are hitting this most of the time.

I think I found another one, and hope it is ok to report here without opening a new issue:
`ModuleNotFoundError: No module named 'pandas._libs.window'`
which I can workaround by explicitly importing it.

My env:
0.6.13.3
Python: 3.8.6 | packaged by conda-forge | (default, Jan 25 2021, 22:54:47) [MSC v.1916 64 bit (AMD64)]
Executable: D:\Miniconda3\envs\develop\python.exe
OS: Windows
Arch: x86_64

**Comment by kayhayen** [comment]
Keep it it open until it's released, potentially also as part of a hotfix.

**Comment by kayhayen** [comment]
Part of 0.6.15 release.
