### ISSUE TITLE
Failure in caching compilation with MSVC 14.2 and clcache.exe

### ISSUE THREAD

**Issue by ToshiEAB** [Nuitka/Nuitka#841]
I am trying to use Nuitka for a simple python program that uses Kivy for a GUI application. But I get an error message, "Nuitka-Scons:INFO: Cached C files (using clcache) with result 'cache miss': 11" with the following command:

python -m nuitka --recurse-none main.py

Maybe the error arises from that I'm using a Visual Studio 2019 (MSVC 14.2) compiler. Can anybody help me figure out how to resolve the "cache miss"?
 
Here is my environment:
- Windows 10
- MSVC 14.2 (Visual Studio 2019)
- Anaconda3 (Python 3.6)
- nuitka 0.6.9.1  (Installed with conda install nuitka)
- clcache 4.1.0 (Installed with conda install -c conda-forge clcache)
- kivy 1.11.1 (Installed with conda install kivy -c conda-forge)

Thanks in advance!

**Comment by kayhayen** [comment]
What is the nature of the failure here?

**Comment by ToshiEAB** [comment]
@kayhayen 
Thanks for the reply. It seems like the error results from failing to import a DLL file for OpenCV. The error looks like:

File "C:\....", line 9, in <module>
   import cv2
ImportError: DLL load failed: The specified module could not be found. 

Maybe I need to use something different from the "--recurse-none" option?

Thanks.

**Comment by kayhayen** [comment]
Puh, the message in your initial report is not an error, and your last question implies that you didn't read anything. But yet, asking it to not look at the code, might cause to not be included.
