### ISSUE TITLE
Numpy missing libraries: @loader_path/libgfortran.3.dylib

### ISSUE THREAD

**Issue by noonchen** [Nuitka/Nuitka#843]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

```
python3 -m nuitka --version

0.6.9.1
Python: 3.8.5 (default, Jul 21 2020, 10:48:26) 
Executable: /usr/local/opt/python@3.8/bin/python3.8
OS: Darwin
Arch: x86_64
```

* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
```
pip3 install nuitka
```

* Many times when you get an error from Nuitka, your setup may be so special
  that even a "hello world" program will not work, please try that and report
  it instead.

```
/Users/nochenon/hello.dist/hello 

hello world
```
hello world works fine

---------
`nuitka3 --windows-disable-console --standalone --show-progress --plugin-enable=qt-plugins --plugin-enable=numpy --recurse-all /PATH_TO/uic_Viewer_main.py`

The following error occurred when I run the compiled executable:
```
/Users/nochenon/uic_Viewer_main.dist/uic_Viewer_main 

Traceback (most recent call last):
  File "/Users/nochenon/uic_Viewer_main.dist/numpy/core/__init__.py", line 22, in <module numpy.core>
  File "/Users/nochenon/uic_Viewer_main.dist/numpy/core/multiarray.py", line 12, in <module numpy.core.multiarray>
  File "/Users/nochenon/uic_Viewer_main.dist/numpy/core/overrides.py", line 7, in <module numpy.core.overrides>
ImportError: dlopen(/Users/nochenon/uic_Viewer_main.dist/numpy/core/_multiarray_umath.so, 2): Library not loaded: @loader_path/libgfortran.3.dylib
  Referenced from: /Users/nochenon/uic_Viewer_main.dist/libopenblas.0.dylib
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nochenon/uic_Viewer_main.dist/uic_Viewer_main.py", line 2, in <module>
  File "/Users/nochenon/uic_Viewer_main.dist/numpy/__init__.py", line 140, in <module numpy>
  File "/Users/nochenon/uic_Viewer_main.dist/numpy/core/__init__.py", line 48, in <module numpy.core>
ImportError: 
```

The complete compile log can be found [here](https://gist.githubusercontent.com/noonchen/e142e35ed035f41d917c83192eee1c43/raw/1c574ee20b7e75ee6e97c1f36c2f34122cd903d5/gistfile1.txt).

I found these libraries in brew-installed gcc 10.2.0, and manually copied the missing libraries (libgfortran.5.dylib, libquadmath.0.dylib) to the dist folder, run the executable again and the following error occrred:
```
zsh: segmentation fault  /Users/nochenon/uic_Viewer_main.dist/uic_Viewer_main
```

I stuck here and don't know what else I can do, any advice?

**Comment by noonchen** [comment]
Update:
I take the suggestions from other similar issues regarding missing NumPy libraries, which is forcing reinstall NumPy and Scipy, I also keep other modules up to date, upgrade Nuitka to version 0.6.9.4. However, the issue is still not solved.

As for these missing libraries, I also found them in the Numpy package and copied to the dist folder, luckily there is no segfault anymore, instead:
```
ImportError: dlopen(/Users/nochenon/uic_Viewer_main.dist/numpy/core/_multiarray_umath.so, 2): Symbol not found: ___addtf3
  Referenced from: /Users/nochenon/uic_Viewer_main.dist/libquadmath.0.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/nochenon/uic_Viewer_main.dist/libquadmath.0.dylib
```

Search the error in google, some [1](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1053), [2](https://github.com/matplotlib/matplotlib/issues/12578/) suggest it has something to do with gcc.
TBH, I know nothing about it, the only thing I can do is to use different options `--clang`, `--lto`, install and link gcc installed by brew, but the problem seems untouched.

gcc version on my machine:
```
gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.16)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
Any suggestions are welcomed.

**Comment by tiwatsuka** [comment]
Do `libgfortran.3.dylib` and `libquadmath.0.dylib` exist in `{numpy-installed-path}/numpy/.dylibs`?  If so, the problem might be solved by copying them to the `dist` directory. 

To my understand, numpy plugin in nuitka finds and copies libraries from `numpy/.libs` (https://github.com/Nuitka/Nuitka/blob/158713e34cba7942483d76c860d6c5c15a0f9cdd/nuitka/plugins/standard/NumpyPlugin.py#L51-L55) but not from `numpy/.dylibs`. I guess that this is the root cause.

**Comment by noonchen** [comment]
Hi tiwatsuka,

Thanks for your suggestion. I did find the missing libraries in `numpy/.dylibs`, and manually copied to the `dist` folder, as I mentioned in the second comment. Sadly, my app does not work either.

I also tried this option `--recurse-not-to=numpy` to force nuitka not to compile numpy, and copy the numpy package to the dist folder after the build, but my app quits with a segfault...😂

I have no clue since then, and I am rebuilding my app on every new release... still waiting for miracle.

**Comment by kayhayen** [comment]
Copying to the dist folder is not supported. I can add that `.dylibs` thing to the plugin, won't harm if it considers both.

**Comment by kayhayen** [comment]
Also, do I really have to point out that windows specific options shouldn't be used on non-Windows? :-)

**Comment by noonchen** [comment]
> Also, do I really have to point out that windows specific options shouldn't be used on non-Windows? :-)

haha... Thanks for pointing out, didn't realize `--windows-disable-console` is only working on windows😂



> Copying to the dist folder is not supported. I can add that `.dylibs` thing to the plugin, won't harm if it considers both.

Thanks, I would try to rebuild once the new release is out.

**Comment by noonchen** [comment]
Updates on nuitka 0.6.10, using the hinted-compilation method to compile.
## Windows
The executable compiled via nuitka 0.6.10 complains about not finding `_multiarray_umath.pyd` in a specified path. However, this file is already located in the correct path `dist\numpy\core\_multiarray_umath.pyd`.
```
C:\Users\Administrator>"C:\Users\Administrator\STDF Viewer.dist\STDF Viewer.exe"
Traceback (most recent call last):
  File "C:\Users\ADMINI~1\STDFVI~1.DIS\numpy\core\__init__.py", line 22, in <module numpy.core>
  File "C:\Users\ADMINI~1\STDFVI~1.DIS\numpy\core\multiarray.py", line 12, in <module numpy.core.multiarray>
  File "C:\Users\ADMINI~1\STDFVI~1.DIS\numpy\core\overrides.py", line 7, in <module numpy.core.overrides>
ImportError: LoadLibraryExW 'C:\Users\ADMINI~1\STDFVI~1.DIS\numpy\core\_multiarray_umath.pyd' failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ADMINI~1\STDFVI~1.DIS\STDF Viewer.py", line 28, in <module>
  File "C:\Users\ADMINI~1\STDFVI~1.DIS\numpy\__init__.py", line 140, in <module numpy>
  File "C:\Users\ADMINI~1\STDFVI~1.DIS\numpy\core\__init__.py", line 48, in <module numpy.core>
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "C:\Users\ADMINI~1\STDFVI~1.DIS\python.exe"
  * The NumPy version is: "1.19.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: LoadLibraryExW 'C:\Users\ADMINI~1\STDFVI~1.DIS\numpy\core\_multiarray_umath.pyd' failed: The specified module could not be found.
```
## macOS
same as the previous version, libgfortran.3.dylib is not copied to dist folder by nuitka
```
Traceback (most recent call last):
  File "/Users/nochenon/STDF Viewer.dist/numpy/core/__init__.py", line 22, in <module numpy.core>
  File "/Users/nochenon/STDF Viewer.dist/numpy/core/multiarray.py", line 12, in <module numpy.core.multiarray>
  File "/Users/nochenon/STDF Viewer.dist/numpy/core/overrides.py", line 7, in <module numpy.core.overrides>
ImportError: dlopen(/Users/nochenon/STDF Viewer.dist/numpy/core/_multiarray_umath.so, 2): Library not loaded: @loader_path/libgfortran.3.dylib
  Referenced from: /Users/nochenon/STDF Viewer.dist/libopenblas.0.dylib
  Reason: image not found
```

**Comment by kayhayen** [comment]
@noonchen the numpy fix of 0.6.10.4 might do lot for this, can you please test? The numpy plugin was totally broken for the libs due to adding support for macOS but getting the boolean wrong, effectively using the wrong path on the platforms.

**Comment by noonchen** [comment]
@kayhayen 0.6.10.4 fixed this issue, thanks!

**Comment by kayhayen** [comment]
So this was an undiscovered duplicate. Unfortunate that I don't have macOS testing infrastructure for this.
