### ISSUE TITLE
bdist_nuitka exclude specific files

### ISSUE THREAD

**Issue by mukulmantosh** [Nuitka/Nuitka#846]
I am trying to create a python .whl package by running the command given below: 

`python setup.py bdist_nuitka. `

I want to exclude `__init__.py` as it contains entry scripts which I don't want to compile.

**Comment by kayhayen** [comment]
You cannot excluse parts of modules, but only full ones, there is a way to specify options, documented in the user manual, and the ``--nofollow-import-to`` can be used.
