### ISSUE TITLE
Hinted compilation with nuitka 0.6.9

### ISSUE THREAD

**Issue by cvpython** [Nuitka/Nuitka#849]
I have installed nuitka 0.6.9.1 and use nuitka-utilities from the master branch.
When I try to compile with the hinted approach (`python get-hints.py script.py`) I have the following error:
```
Traceback (most recent call last):
  File "get-hints.py", line 43, in <module>
    from nuitka.utils.Utils import getSharedLibrarySuffix
ImportError: cannot import name 'getSharedLibrarySuffix' from 'nuitka.utils.Utils'
```

Are there nutika-utilities compatible with nuitka 0.6.9.1 ?

Here are some characteristics of my installation:
> 
> 0.6.9.1
> Python: 3.7.6 (default, Jan  8 2020, 19:59:22) 
> OS: Linux
> Arch: x86_64

**Comment by danielmorgan0x1** [comment]
I am also using the latest version of Nuitka and had the same issue. I found the Utils.py file from 0.6.8 and found the getSharedLibrarySuffix function. I then added this to my Utils.py in 0.6.9.1 as follows:

`def getSharedLibrarySuffix():
    if python_version < 300:
        import imp

        result = None

        for suffix, _mode, module_type in imp.get_suffixes():
            if module_type != imp.C_EXTENSION:
                continue

            if result is None or len(suffix) < len(result):
                result = suffix

        return result
    else:
        import importlib.machinery  # pylint: disable=I0021,import-error,no-name-in-module

        result = None

        for suffix in importlib.machinery.EXTENSION_SUFFIXES:
            if result is None or len(suffix) < len(result):
                result = suffix

        return result`

After saving this and running get-hints.py it is working correctly!

**Comment by kayhayen** [comment]
I have corrected the hinted compilation, should work again.
