### ISSUE TITLE
Not An Issue in This Project : This is a Great Project

### ISSUE THREAD

**Issue by atErik** [Nuitka/Nuitka#859]
Hi,  
i like this "Nuitka" transpiler ( Python to C++ ) project.  
its useful.  
i have Starred this project.  
it needs to be improved further.

i have mentioned it here in SO(StackOverflow) site, would you please upvote it [here](https://stackoverflow.com/questions/64180191/) (please upvote both of my Q+A) if you find it useful or if you think it will be helpful for other users related to this type of transpiler projects.  
( and please downvote user Caleb's answer, as that is incorrect answer . Correct-answer must answer my questions first , My question is about "Transpiler" tools & which "transpiler" tool can keep high-level algorithms/structures intact , Question/article is NOT about language learning, when to transpile & when-not, etc.  
In SO site, user Flimzy (and Caleb) doesn't give advice When "C/C++",etc to "Go" conversion related question is posted or when "C/C++" is criticized , But when "Go"-to-"C/C++",etc conversion Question is posted or when Google based products (like "Go"-language) are criticized , then those users, especially Flimzy "Close" the question & downvotes, & give many un-asked advices, etc, Because those users are Google PUSHERS & google based product (like "Go") pushers . Google Crimes<sup>[1](https://en.wikipedia.org/wiki/Criticism_of_Google), [2](https://en.wikipedia.org/wiki/Google_litigation), [3](https://www.bbc.com/news/business-52887340), [4](https://www.reuters.com/article/us-alphabet-google-privacy-lawsuit-idUSKBN23933H), [5](https://www.nytimes.com/2020/09/21/technology/google-antitrust-justice-department.html), [6](https://www.nationalreview.com/news/department-of-justice-state-attorneys-general-to-sue-google-for-antitrust-violations-report/)</sup>. Problems in "Go"<sup>[1](https://bravenewgeek.com/go-is-unapologetically-flawed-heres-why-we-use-it/)</sup>. )

Thanks.

EDIT : added few more lines, i Starred this project, etc.

**Comment by kayhayen** [comment]
I consider this to be spam.
