### ISSUE TITLE
_pswindows.py, line 35 in <modules psutil.__pswindows> ImportError

### ISSUE THREAD

**Issue by gauthierbuttez** [Nuitka/Nuitka#860]
Hi,

I am trying to distribute my software. So I compile with Nuitka and test the exe on 2 different Windows computers: 10 and 8.1.

I compiled from the windows 10. Source code and exe work fine.

I tested this same exe in Windows 8.1 and it didn't work.

I compiled my software with nuitka with this command:

`python -m nuitka --standalone --mingw64 --include-module=psutil --plugin-enable=pylint-warnings --enable-plugin=numpy --enable-plugin=psutil --enable-plugin=qt-plugins --show-progress --show-scons --follow-imports --recurse-all --windows-icon=favicon_phonebot.ico MyApp.py`

I compiled it on Windows 10 with Python 3.7 with nuitka 0.6.8.4.

Here is log output:
[https://github.com/gauthierbuttez/public/blob/master/nuitka_log16102020.txt](https://github.com/gauthierbuttez/public/blob/master/nuitka_log16102020.txt)

On Windows 8.1 :
When I run the python code it is fine.
When I run the exe (compiled on WIndows 10) , I get this error message:

```
FILE "C:\PROGRAM-2\MYAPP-1\mymodules.py, line 24 in <modules mymodules>
FILE "C:\PROGRAM-2\MYAPP-1\psutil\__init__.py, line 145 in <modules psutil>
FILE "C:\PROGRAM-2\MYAPP-1\psutil\_pswindows.py, line 35 in <modules psutil.__pswindows>
ImportError
```

So I checked the line 27 of mymodules.py and saw that this line:
`Import psutil`

Is creating the issue.

So I made a simple python script:
import mymodules
print("test")
And this ImportError for psutil didn't show up!

What did I do wrong? I added --standalone option. I don't understand!

I don’t understand why the source code run fine with python and why do I get errors with the exe?

Does anyone already faced this issue with psutil?

**Comment by kayhayen** [comment]
There is something in the user manual about using old Windows versions, which is said to work, otherwise it's unsupported. Also since you are using Pandas, effectively the compilation includes virtually everything, so I won't try to reproduce at this time.
