### ISSUE TITLE
Memory leak with PyTorch

### ISSUE THREAD

**Issue by LuisTbx** [Nuitka/Nuitka#861]
I have encounter a memory leak with the PyTorch library. Was able to compile the code on standalone mode, but when executed and code goes inside a loop, memory explodes either on CPU or GPU. I believe it is the memory management not working correctly and creating new variables on each loop instead of reusing the current variables. According to PyTorch library python should freed the memory once it gets out of the loop as suggested in: [Here](https://pytorch.org/docs/stable/notes/faq.html) 

Before submitting an Issue, please review the [Issue Guidelines](https://github.com/kayhayen/Nuitka/blob/master/CONTRIBUTING.md#submitting-an-issue).

* Please check whether the bug was already reported or fixed.

* Please check out if the develop version of Nuitka works better for you.

  Download source, packages [from here](https://nuitka.net/pages/download.html)
  where you will also find instructions how to do it via PyPI.

If you want to post a problem/bug, to help us understand and resolve your issue
please check that you have provided at least the information below, and discard
up to here:

* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...) 

  python -m nuitka --version

Python: 3.8.5 (default, Jul 28 2020, 12:59:40) 
Executable: ~/compile/bin/python
OS: Linux
Arch: x86_64

* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually. 

Inside a virtualenv via pip

* Many times when you get an error from Nuitka, your setup may be so special
  that even a "hello world" program will not work, please try that and report
  it instead.

Hello world works without any issue, other scripts are compiled without any issue.

* If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
  that demonstrates the issue i.e a small piece of code which reproduces
  the issue and can be run with out any other (or as few as possible)
  external dependencies.

[example.txt](https://github.com/Nuitka/Nuitka/files/5392257/example.txt)

* If this is a regression (used to work in an earlier version of Nuitka),
  please note what you know about that.

**Comment by melandur** [comment]
Encountered the same behaviour for the GPU memory. Not compiled uses the model about about 30% of the GPUs memory, where the compiled code creates an cuda overflow.

nuitka 0.6.9.2
Python 3.7.0
torch 1.6.0+cu101
OS: Windows 10
everthying installed with pip

My installed nuitka works for all other libraries as expected!
I tried your example from the txt and got the same findings.

Here a workaround (sexy would be different), which worked for me:
python -m nuitka --standalone --follow-imports --plugin-enable=numpy --nofollow-import-to=torch main.py'

then copy the whole torch and numpy folders from your environment/Lib/site-packages to to your dist-folder

Works for me
Hope this helps

**Comment by kayhayen** [comment]
There is a torch plugin to Nuitka, I wonder why you aren't using it. You ought to have gotten a warning about it, did you not?

**Comment by melandur** [comment]
Got point, should have mentioned the torch plugin flag. I had no success with the torch plugin.
The warning works as expected: Nuitka-Plugins:WARNING: Use '--plugin-enable=torch' for: torch support.

python -m nuitka --standalone --follow-imports --plugin-enable=numpy --plugin-enable=torch main.py'

The example.txt code with numpy and torch plugin enabled:
      Traceback (most recent call last):
     File "C:\Users\...\...\MAIN~1.DIS\main.py", line 2, in <module>
     File "C:\Users\...\...\MAIN~1.DIS\torch\__init__.py", line 189, in <module torch>
    ImportError: numpy.core.multiarray failed to import

The numpy.core.multiarray error is not new, I saw this at the beginning of the torch plugin, I guess.

**Comment by LuisTbx** [comment]
Can confirm the solution proposed by @melandur solved my issue.
