### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by jiri-otoupal** [Nuitka/Nuitka#862]
I had tried compiling programs in python 2.7 successfully with nuitka. Unfortunately program that I want to compile uses pathos and numpy and cycles at Optimization, so i disabled optimization in code and at compilation phase it ends with error 
`module.BaseHTTPServer.c: In function '_create_compiled_function':
module.BaseHTTPServer.c:11612:44: error: too few arguments to function 'Nuitka_Function_New'
     struct Nuitka_FunctionObject *result = Nuitka_Function_New(
                                            ^~~~~~~~~~~~~~~~~~~
In file included from C:\Python27\lib\SITE-P~1\nuitka\build\include/nuitka/prelude.h:398,
                 from module.BaseHTTPServer.c:19:
C:\Python27\lib\SITE-P~1\nuitka\build\include/nuitka/compiled_function.h:102:38: note: declared here
 extern struct Nuitka_FunctionObject *Nuitka_Function_New(function_impl_code c_code, PyObject *name,
                                      ^~~~~~~~~~~~~~~~~~~`

**Comment by kayhayen** [comment]
Disabling optimization is not supported.
