### ISSUE TITLE
Force the use of -O1 instead of -O3

### ISSUE THREAD

**Issue by Leseratte10** [Nuitka/Nuitka#866]
I'm trying to package a fairly complex Python code, and I'm running Nuitka on a Github Runner for each commit of the python code. These runners are limited to 2GB of RAM, and that seems to be too little for the default settings - when I try to compile my app for Windows x86, I get an error that cc1 is running out of memory. 

When I looked into the `SingleExe.scons` file and replaced every `-O3` with `-O1` so the compiler doesn't spend as much time / resources optimizing stuff, the compilation worked. 

Currently I'm just using a step in my build script where I manually patch that file (`C:\bin\sed.exe -i 's/"-O3"/"-O1"/g' C:\hostedtoolcache\windows\Python\3.8.6\x86\lib\site-packages\nuitka\build\SingleExe.scons`) but that's not really a practical or future-proof solution. 

Is there a parameter I can give to nuitka to make it use -O1? Looking through the scons code, it looks like -O2 is used in debug mode, but A) I didn't figure out how to trigger that with a nuitka parameter, and B) that would also include other debug symbols and stuff in the binary which I don't need, and C), that's O2 and not O1. 

Is there an easy way to make nuitka use -O1 instead of -O3? If not, can a parameter be added to do that?

* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

Nuitka 0.6.8.4

* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.

Python comes from the Github runner
```
      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8
          architecture: 'x86'
```
and Nuitka is installed with pip: 
```
      - name: Configure Python
        run: |
          python -m pip install --upgrade pip
          pip install nuitka
```

**Comment by kayhayen** [comment]
From what I recall, setting the CCFLAGS="-O1" may not be put at the end, therefore not allowing this, although it probably is the intended mechanism for that. You could make it check if there is another -O option before adding its own one to the Scons environment, then it would be clean. Adding user options only at the very end, would be another way, maybe, depends on how the compilers parse the command line.

**Comment by kamgha** [comment]
From my limited testing, setting the environment variable `CCFLAGS` should give you the desired effect. E. g. `set CCFLAGS="-march=native -mtune=native -Os"` (in case of GCC+MinGW64) in a batch file or command line before you run Nuitka would/should give you a tailored for the machine and optimized for small size binary.

**Comment by Leseratte10** [comment]
Okay, I didn't think it'd be that easy. Looking at the source code I saw all the code that sets a custom optimization level so I didn't even think to try that. 

Setting `CCFLAGS="-O1"` makes the build work again without running out of memory, thanks.
