### ISSUE TITLE
Relative import

### ISSUE THREAD

**Issue by 00sapo** [Nuitka/Nuitka#869]
I'm trying to use nuitka for compiling a package which contains runnable modules, but it doesn't work.

### Directory structure:
```txt
nuitka_test/
├── __init__.py
├── __main__.py
├── module1.py
├── module2.py
``` 
### File content
`nuitka_test/module1.py`:
```py
def func():
    print("I'm in module1.func")

print("I'm in module1")
```
`nuitka_test/module2.py`:
```py
from . import module1

print("I'm in module2")

if __name__ == "__main__":
    print("I'm in module2, if __main__ ")
    module1.func()
```
`nuitka_test/__main__.py`:
```py
from . import module2

print("I'm in nuitka_test __main__")
```
`nuitka_test/__init__.py`:
```py
# empty
```

### Nuitka commands
Here is what I tried, each with its output:

#### --standalone on `nuitka_test`

```
$ python -m nuitka --standalone nuitka_test
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Compiled 11 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit (direct)': 4
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit (preprocessed)': 6
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 1

$ ls
nuitka_test/  nuitka_test.build/  nuitka_test.dist/

$ nuitka_test.dist/nuitka_test
Traceback (most recent call last):
  File "/home/sapo/Develop/nuitka_test/nuitka_test.dist/__main__.py", line 1, in <module>
ImportError: attempted relative import with no known parent package
```

#### --standalone on `nuitka_test/module2.py`

```
$ python -m nuitka --standalone nuitka_test/module2.py
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Compiled 11 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 11

$ ls
module2.build/  module2.dist/  nuitka_test/

$ module2.dist/module2
Traceback (most recent call last):
  File "/home/sapo/Develop/nuitka_test/module2.dist/module2.py", line 1, in <module>
ImportError: attempted relative import with no known parent package
```

#### --module on `nuitka_test/module2.py`

```
$ python -m nuitka --module nuitka_test/module2.py
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Compiled 10 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit (direct)': 3
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit (preprocessed)': 6
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 1

$ python -m module2
/usr/bin/python: No code object available for module2
```

#### --module on `nuitka_test`

```
$ python -m nuitka --module nuitka_test
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Compiled 10 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 10

$ ls
module2.build/  nuitka_test/        nuitka_test.cpython-38-x86_64-linux-gnu.so
module2.dist/   nuitka_test.build/  nuitka_test.pyi

$ python -m nuitka_test
/usr/bin/python: No module named nuitka_test.__main__; 'nuitka_test' is a package and cannot be directly executed 

$ mv nuitka_test nuitka_test.back

$ ls
module2.build/  nuitka_test.back/   nuitka_test.cpython-38-x86_64-linux-gnu.so
module2.dist/   nuitka_test.build/  nuitka_test.pyi

$ python -m nuitka_test.module2
/usr/bin/python: No module named nuitka_test.module2

```

### Non-relative import
By using `import` instead of `from . import`, nuitka works when using the `--standalone` or no flags, but I still cannot use it as module with `--module`. To be compliant with CPython, nuitka should be able to execute a module in all the previous scenarios (compiled mackage, compiled module, standalone module, standalone package).

`import` is not portable because the module cannot be exported as package.

### System Version

```
$ python -m nuitka --version
0.6.9.4
Python: 3.8.5 (default, Sep  5 2020, 10:50:12)
Executable: /usr/bin/python
OS: Linux
Arch: x86_64
```

**Comment by kayhayen** [comment]
Your module mode examples do not include contained modules, which you can read on in the user manual, how to achieve that. I am not sure if CPython will find the `__main__` module if included, but it might. Can you try that out please?

**Comment by 00sapo** [comment]
CPython in this way:
-  if the package is run as main (`-m` option), the `__main__.py` is imported, and, consequently, executed
- if the package  is imported, the `__main__.py` is not imported
This is documented [here](https://docs.python.org/3/library/__main__.html). Indeed, the implementation of `-m mymodule` option in CPython is equivalent to `-c "import mymodule.__main__"`:

```text
$ python -m nuitka_test
I'm in module1
I'm in module2
I'm in nuitka_test __main__

$ python -c "import nuitka_test.__main__"
I'm in module1
I'm in module2
I'm in nuitka_test __main__
```

Attached is the source code for the examples in this issue: [nuitka_test.zip](https://github.com/Nuitka/Nuitka/files/5471534/nuitka_test.zip)

**Comment by 00sapo** [comment]
> Your module mode examples do not include contained modules, which you can read on in the user manual, how to achieve that.

Can you give me a link so that I can test and create an example?

**Comment by kayhayen** [comment]
Closing for lack of feedback.

**Comment by egerlach** [comment]
I'm pretty sure this is a duplicate of #493 (adding comment for anyone who comes across this later)
