### ISSUE TITLE
Compiled Nuitka uses Python2 syntax? Or something wrong with trivial samples…

### ISSUE THREAD

**Issue by belonesox** [Nuitka/Nuitka#874]
I got Nuitka
```
0.6.10rc5
Python: 3.8.5 (default, Aug 12 2020, 00:00:00)
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
```
and compile it with 
``…/Nuitka/tests/reflected/compile_itself.py``
(patched to exit after ``executePASS1()``)

Lets consider oneliner ``wtf.py``:
```python
print("Hello!", end='')
```

``python3 -m nuitka wtf.py`` — OK

Selfcompiled version failed:
```
…/projects/nuitkas/upstream/Nuitka/tests/reflected/nuitka.bin wtf.py
  File "wtf.py", line 1
    print("Hello!", end='')

SyntaxError: invalid syntax

Nuitka is very syntax compatible with standard Python. It is currently running
with Python version '2.7', you might want to specify more clearly with the use
of the precise Python interpreter binary and '-m nuitka', e.g. use this
'python3.8 -m nuitka' option, if that's not the one the program expects.

```

Looks like compiled nuitka use 2.7 python syntax, but at the same time 

oneliner ``wtf2.py`` (Also incorrect to python2 syntax):
```python
print("Hello!")
```

compiled successfully.

So whats wrong in these trivial samples?

**Comment by kayhayen** [comment]
Your last statement is wrong, that is valid code in Python2. You can put useless braces around things.

The reflected test is a test, and runs with the Python version used to execute it, likely Python 2.7, and I am not sure, you are using the most useful binary at all, although it appears so. I don't recommend using it in compiled form.

**Comment by belonesox** [comment]
So, complitely impossible to fix somehow python3 in compiled version of Nuitka?
I use ``python3`` to run ``compile_itself.py``, how it possible to locking versus Python2?

I just want to speedup Nuitka compilation, and I hoped that compiled version should be somewhat faster....

**Comment by kayhayen** [comment]
It's not impossible now, but you would have to read what I wrote before.
