### ISSUE TITLE
Left over typo? 

### ISSUE THREAD

**Issue by salembream** [Nuitka/Nuitka#875]
Hi,
I think there is small typo here, 
`item[0]` should be `item`, 

this is a consequence to: 
https://github.com/Nuitka/Nuitka/commit/441ede616b6dc3269d08121d15b98841ec08fbaf#diff-3f22fe6627d5c80b5c1405f1fe3fbe6573949f499b21e7ebe3ddd43a53abe807

https://github.com/Nuitka/Nuitka/blob/2f81cff227cfa935cbed9e82ddb22d6fc523cb30/nuitka/plugins/standard/ImplicitImports.py#L1217

**Comment by kayhayen** [comment]
I agree, thanks for pointing it out. What was the symptom this caused?

**Comment by kayhayen** [comment]
I pushed this to factory branch, will be part of the next hotfix release.

**Comment by salembream** [comment]
I didn't notice any wrong output actually, but was trying to debug another issue, and noticed  strange checks for a single character names, "the first character of the last checked import".

**Comment by kayhayen** [comment]
Thanks for the report though, this is intended I think for cases, where implicit imports have such themselves, and that will cause some breakage somewhere.

**Comment by kayhayen** [comment]
This is part of 0.6.9.6 hotfix release done.
