### ISSUE TITLE
Compile Scons error and possible to Compile Faster?

### ISSUE THREAD

**Issue by EmreDemircan** [Nuitka/Nuitka#882]
Hello,
When I try to build my python project to exe it works fine on my computer. But when I try to compile on another computer (in server pc) it can't compile(it compiles but exe size is 17mb, in my computer exe size is 32mb and 17mb exe can't run). Exactly has the same files and Visual studio 2019.

**Nuitka --version:**
0.6.9.6
Python: 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Users\User\AppData\Local\Programs\Python\Python37\python.exe
OS: Windows
Arch: x86_64

**Compile Code:**
cd C:\Users\User\Desktop\MyProjectPYCHARM\MyProjectTools

REM pyarmor obfuscate --restrict 0 --no-cross-protection --exact Main.py
RMDIR dist /s /q
mkdir dist
echo D|xcopy /d /e /y pytransform dist\pytransform
echo D|xcopy /d /e /y TokenDrive dist\TokenDrive
copy Main.py dist\Main.py /y

pyarmor obfuscate --no-runtime --restrict 0 --no-cross-protection --exact Apps_iso.py
pyarmor obfuscate --no-runtime --restrict 0 --no-cross-protection --exact auth.py
pyarmor obfuscate --no-runtime --restrict 0 --no-cross-protection --exact AYARLAR.py
pyarmor obfuscate --no-runtime --restrict 0 --no-cross-protection --exact bildirim.py
pyarmor obfuscate --no-runtime --restrict 0 --no-cross-protection --exact Bilgisayarlarim.py
pyarmor obfuscate --no-runtime --restrict 0 --no-cross-protection --exact client.py
pyarmor obfuscate --no-runtime --restrict 0 --no-cross-protection --exact detay.py
pyarmor obfuscate --no-runtime --restrict 0 --no-cross-protection --exact Free_oyunlar.py
pyarmor obfuscate --no-runtime --restrict 0 --no-cross-protection --exact gelenler.py
pyarmor obfuscate --no-runtime --restrict 0 --no-cross-protection --exact HizliGuncelleme.py
pyarmor obfuscate --no-runtime --restrict 0 --no-cross-protection --exact imaj.py
pyarmor obfuscate --no-runtime --restrict 0 --no-cross-protection --exact istek.py
pyarmor obfuscate --no-runtime --restrict 0 --no-cross-protection --exact login.py
pyarmor obfuscate --no-runtime --restrict 0 --no-cross-protection --exact MyProjectform.py
pyarmor obfuscate --no-runtime --restrict 0 --no-cross-protection --exact oyunmenusupanel.py
pyarmor obfuscate --no-runtime --restrict 0 --no-cross-protection --exact settings.py
pyarmor obfuscate --no-runtime --restrict 0 --no-cross-protection --exact Reklam.py
pyarmor obfuscate --no-runtime --restrict 0 --no-cross-protection --exact TemaDuzenleyici.py
copy source.py Dist\source.py /y
copy EmreImports.py dist\EmreImports.py /y
REM pyarmor obfuscate --no-runtime --restrict 0 --no-cross-protection --exact source.py
pyarmor obfuscate --no-runtime --restrict 0 --no-cross-protection --exact Steampanel.py
pyarmor obfuscate --no-runtime --restrict 0 --no-cross-protection --exact tumayarlar.py
pyarmor obfuscate --no-runtime --restrict 0 --no-cross-protection --exact video.py

cd C:\Users\User\Desktop\MyProjectPYCHARM\MyProject\dist

C:\\Users\\User\\Desktop\\MyProjectPYCHARM\\MyProject\\venv\\Scripts\\python.exe -m nuitka --show-scons --include-package EmreImports --include-package auth  --include-package HizliGuncelleme --include-package Apps_iso --include-package AYARLAR --include-package bildirim --include-package MyProjectform --include-package login --include-package client --include-package source --include-package Steampanel --include-package settings --include-package tumayarlar --include-package oyunmenusupanel --include-package istek --include-package imaj --include-package gelenler --include-package Free_oyunlar --include-package Bilgisayarlarim --include-package Reklam --include-package TemaDuzenleyici --include-package paramiko --include-package pytransform --plugin-enable=qt-plugins --plugin-enable=multiprocessing --standalone --recurse-all --remove-output --windows-disable-console --windows-icon=c:\users\User\desktop\MyProjectpycharm\MyProject\MyProject.ico --output-dir=C:\\Users\\User\\Desktop\\ --show-progress Main.py

xcopy c:\Users\User\Desktop\BUILDEKLE C:\Users\User\Desktop\Main.dist\ /h/i/c/k/e/r/y > NUL

ren C:\Users\User\Desktop\Main.dist\Main.exe iProCafe.exe

echo D|xcopy /d /e /y 
C:\\Users\\User\\Desktop\\MyProjectPYCHARM\\MyProjectTools\\pytransformPyArmor C:\\Users\\User\\Desktop\\Main.dist\\pytransform
D:\programlar\UPX\upx.exe "C:\Users\User\Desktop\Main.dist\iProCafe.exe"
copy "C:\Users\User\Desktop\Main.dist\iProCafe.exe" "C:\xampp\htdocs\Client2\" /y
copy "C:\Users\User\Desktop\Main.dist\iProCafe.exe" "C:\Users\User\Desktop\Filezilla\" /y
RMDIR "C:\Users\User\Desktop\MyProjectPYCHARM\MyProjectTools\dist" /s /q

How Can I fix this issue? 
Images attached.

**And another question**
 is there anyway to compile faster? Because in Ryzen 7 3700X it takes 21 minutes to compile. Not very familiar with C + + so can let me know arguments to compile faster it is possible?

Thank you very much
![Compile err 1](https://user-images.githubusercontent.com/74592858/99369650-bf6e0f80-28cd-11eb-992e-9599e2f66b37.png)
![Compile err 2](https://user-images.githubusercontent.com/74592858/99369653-c006a600-28cd-11eb-950a-a894a4ad2ad2.png)

!

**Comment by kayhayen** [comment]
I don't think this is very actionable, seems there is a Windows error about a temporary file, that indicates an issue with your system. I don't speak your language, and screenshots are very unpolular, because e.g. I cannot google it, so I won't care.

Using failed build results is not possible. Nuitka adds stuff to it after the build, but of course not when it failed.

Develop and what's going to be 0.6.10 have indeed a lot of scalability improvements. Might help your case, unknowable with the source code.

Yours,
Kay
