### ISSUE TITLE
question: can I use nvcc (cuda) compiler?

### ISSUE THREAD

**Issue by OfekShochat** [Nuitka/Nuitka#885]
I wondered if I can use the nvcc compiler with nuitka. I read that I have to use on of the ones listed on the website, but is that all the compilers I can use?

**Comment by kayhayen** [comment]
I don't know what it is, and why you would want to use it to compile the Python code. Does it automatically optimize C code into vector using stuff?

**Comment by OfekShochat** [comment]
nvcc is a compiler for the gpu

**Comment by kayhayen** [comment]
That much I know, I don't know what difference it will make if you use it. I am expecting that Nuitka needs to generate code specifically for it to be any different in the output, which it doesn't do (yet?). 

If it doesn't automatically put the GPU to use on code not written for that, it is not worth using it. I repeat my question, does it?

**Comment by OfekShochat** [comment]
just how can I get the c code and not the exe

**Comment by kayhayen** [comment]
I think you are seeking something that won't be useful. To me it seems that just by using that compiler wrapper, code generation for any program is going to use the GPU. That is not true according to my limited knowledge. 

> 

> just how can I get the c code and not the exe

Read the ``--help`` output to find that option.
