### ISSUE TITLE
No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by multiarray-umath** [Nuitka/Nuitka#888]
- Nuitka version:
```
$ bin/nuitka --version
0.6.9.7
Python: 3.8.6 (default, Sep 30 2020, 04:00:38) 
Executable: /usr/bin/python
OS: Linux
Arch: x86_64
```
- sample `main.py`:
```
import numpy as np
print("test")
```
- execution:
```
$ python3 main.py
test
```
- compilation:
`nuitka --recurse-all --plugin-enable=pylint-warnings main.py`
- result when executing `main.bin`:
```$ ./main.bin 
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/numpy/core/__init__.py", line 22, in <module numpy.core>
    from . import multiarray
  File "/usr/lib/python3.8/site-packages/numpy/core/multiarray.py", line 12, in <module numpy.core.multiarray>
    from . import overrides
  File "/usr/lib/python3.8/site-packages/numpy/core/overrides.py", line 7, in <module numpy.core.overrides>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/test/main.py", line 1, in <module>
    import numpy as np
  File "/usr/lib/python3.8/site-packages/numpy/__init__.py", line 140, in <module numpy>
    from . import core
  File "/usr/lib/python3.8/site-packages/numpy/core/__init__.py", line 48, in <module numpy.core>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "/usr/bin/python"
  * The NumPy version is: "1.19.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```

Any ideas how I can compile a executable using numpy (no standalone variant) and link with the mutiarray_umath extension library?
Thx for any feedback

**Comment by melandur** [comment]
The multiarray module is already part of the numpy library. 
You need to enable the numpy plugin explicit as  "--plugin-enable=numpy" for a proper compilation.
Try this:
nuitka --recurse-all --plugin-enable=numpy --plugin-enable=pylint-warnings main.py

**Comment by NeuralAIM** [comment]
> The multiarray module is already part of the numpy library.
> You need to enable the numpy plugin explicit as "--plugin-enable=numpy" for a proper compilation.
> Try this:
> nuitka --recurse-all --plugin-enable=numpy --plugin-enable=pylint-warnings main.py

I have exactly the same problem, I was building a 32 bit application - and it works, but 64 bit does not.

**Comment by Pro100rus32** [comment]
> The multiarray module is already part of the numpy library.
> You need to enable the numpy plugin explicit as "--plugin-enable=numpy" for a proper compilation.
> Try this:
> nuitka --recurse-all --plugin-enable=numpy --plugin-enable=pylint-warnings main.py

I have exactly the same problem, I was building a 32 bit application - and it works, but 64 bit does not.

**Comment by Pro100rus32** [comment]
I found out that this works on version 0.6.9.6, but not on factory or 0.6.9.7

**Comment by kayhayen** [comment]
I really need to change the policy to enable plugins by default. 

People never get that the missing plugin warning causes their issues, but this is a case of that.

Also, if you have another issue, please raise another issue, filling out the issue template. Putting your comments to something that seems similar is not helpful to me, because I don't want to interact on different things in one issue.

**Comment by Pro100rus32** [comment]
> I really need to change the policy to enable plugins by default.
> 
> People never get that the missing plugin warning causes their issues, but this is a case of that.
> 
> Also, if you have another issue, please raise another issue, filling out the issue template. Putting your comments to something that seems similar is not helpful to me, because I don't want to interact on different things in one issue.

this is a bug not related to plugin import, it just doesn't work with numpy in newer versions. this error is only in 64bit build on factory or version 6.9.7

**Comment by kayhayen** [comment]
In the issue text itself it doesn't say so @Pro100rus32 and if you have another issue like that, you need to raise a new issue, and it seems it would be good to specify the numpy version in that one. Like I said, I am not mixing issues, the one here was one of missing numpy plugin usage.
