### ISSUE TITLE
Infinite optimization loop with numpy/scipy/pandas

### ISSUE THREAD

**Issue by Taiwanchaoh** [Nuitka/Nuitka#890]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

  python -m nuitka --version

```bash
0.6.10rc9
Python: 3.8.2 (default, Mar 25 2020, 17:03:02) 
Executable: /home/username/miniconda3/envs/nuitka_t/bin/python
OS: Linux
Arch: x86_64
```

* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.

I used the miniconda and the default channel to install python. And, I used pip to install the Nuitka version 0.6.10rc9 from the git.

* If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
  that demonstrates the issue i.e a small piece of code which reproduces
  the issue and can be run without any other (or as few as possible)
  external dependencies.

I used the following bash command to execute Nuitka. I also manually prevent Nuitka from recursing into unused packages/modules, which is a legacy after my testing and may be unnecessary. 

```bash
python -m nuitka --show-progress --show-scons  --standalone --follow-imports --recurse-not-to=dask --recurse-not-to=ipywidgets --recurse-not-to=ipython_genutils --recurse-not-to=ipykernel --recurse-not-to=IPython --recurse-not-to=pexpect --recurse-not-to=nbformat --recurse-not-to=numpydoc --recurse-not-to=pytest --recurse-not-to=bokeh  --recurse-not-to=systemd --recurse-not-to=numba --recurse-not-to=matplotlib --plugin-enable=numpy --plugin-enable=pylint-warnings nuitka_test.py > build.log 2>&1
```

The content of the ```nuitka_test.py``` is as follows.

```python
import numpy as np
import pandas as pd
import pandas._libs.tslibs.base
import scipy

print(np.__version__)
print(pd.__version__)
print(scipy.__version__)
```

Since the screen output was stored in ```build.log```, I parsed the output and found that some packages were optimized more than 1000 times after I left the code running for a dozen hours. I tried to import only either one of the packages. The optimization loop can end. And, I tried to import "pandas" + "numpy", the optimization loop can end, and the compiled Nuitka binary works. 

I guess this issue might be related to #887. And, I think that it might be worth putting it under your radar if you want to test the new fix with other modules with potentially similar issues. 

Some other information about pandas, numpy, and scipy.

``` bash
# Name                    Version                   Build  Channel
mkl                       2020.2                      256  
mkl-service               2.3.0            py38he904b0f_0  
mkl_fft                   1.2.0            py38h23d657b_0  
mkl_random                1.1.1            py38h0573a6f_0  
numpy                     1.19.2           py38h54aff64_0  
numpy-base                1.19.2           py38hfa32c7d_0  
pandas                    1.1.3            py38he6710b0_0  
scipy                     1.5.2            py38h0b6359f_0  
```

Please let me know if you need more information. And, thank you for this awesome work.

**Comment by kayhayen** [comment]
Not really interested in proactively checking out myself various problematic situations. I think the negativ impact of loop optimization of #887 is covered now, and should dramatically reduce compile times for cases where Nuitka may still not be scalable without caching.

I think the "worst module causing the long time time for everything" effect, explains how different versions, different mixes of used packages, can cause the issue. And what's really mean, that worst module on its own, can be dramatically fast itself, but trigger slow modules to be re-examined. So the fix for that on develop branch will be probably even solving this for you.
