### ISSUE TITLE
Nonidempotent option "--plugin-enable=xxx" crashing for plugins that have options

### ISSUE THREAD

**Issue by belonesox** [Nuitka/Nuitka#891]
Nuitka, branch ``factory`` commit ``0a5244bca9f2a09282949e5f9bc507928b762e6f``

Consider any python file (let it be ``test-scipy.py``), if we call 
``
python3 -m nuitka --plugin-enable=numpy  --plugin-enable=numpy  test-scipy.py    
``
(nonconflicting options should be idempotent)
we got 
``
optparse.OptionConflictError: option --noinclude-scipy: conflicting option string(s): --noinclude-scipy
``

**Comment by kayhayen** [comment]
Good report. It may not make it into 0.6.10, but certainly into one of the first hotfixes if not.

**Comment by kayhayen** [comment]
This one may already be fixed.

**Comment by kayhayen** [comment]
It's on develop now.

**Comment by kayhayen** [comment]
Released as part of 0.6.10
