### ISSUE TITLE
Create one portable statically linked executable file using Nuitka

### ISSUE THREAD

**Issue by anki-code** [Nuitka/Nuitka#903]
Hi! Thank you for Nuitka!

For [xxh project](https://github.com/xxh/xxh) (console tool) I created one portable statically linked executable file using Nuitka:

https://github.com/xxh/xxh-portable/blob/e26e48985621a33cde32772d672f11c3b3843f16/xxh-portable-musl-alpine.Dockerfile#L16-L28

As you can see I build the Python library first (`libpython3.8.a` with appropriate modules) and then use it in `LDFLAGS` before running Nuitka. I did this in Alpine with musl and as result I get the one portable statically linked `./xxh` binary file that could be run on many Linux distributes.

Is there a way now or future feature to do this in Nuitka by one command and by using one option i.e. `--standalone-static`?

Thanks!

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by kayhayen** [comment]
Nuitka now has the `--onefile` option which works for Linux. It doesn't care if it's shared or not.

There is also support for static Python library. You would only need to  convince `shallUseStaticLibPython()` to return True. Currently I have only ever use this successfully with Anaconda on Linux and maybe MSYS2 gcc on Windows. 

It's a bit neglected because the issue was that you really want to get the LTO version of `libpython.a` but then you absolutely have to match the C compiler used to create it with the one you are using. Something that is frequently not the case, as we tend to pick up the system gcc and they will have incompatible file formats.

But basically it's all there now. And you don't even have to worry about static Python, although I know it can give much better performance.

**Comment by kayhayen** [comment]
What would be needed is a file format analysis that detects unusable LTO link library `libpython.a` and then warns about that. If we could tell if it's usable with the specified C compiler, we could use it by default, and avoid the hardcoding of things. As for Windows and MSYS2, I believe it's only a link library for the DLL, and not really a static one. Windows is not in the picture for these things it seems.

**Comment by diovudau** [comment]
--onefile says it wants an icon file. What is the command line syntax to provide that?

**Comment by kayhayen** [comment]
@diovudau there should be an option for Linux, but there isn't yet, not even in development version, but I think that --windows-icon-from-ico=path might be working for now there too.

Otherwise it defaults to 
```
    if not icon_paths:
        if os.path.exists("/usr/share/pixmaps/python.xpm"):
            icon_paths.append("/usr/share/pixmaps/python.xpm")
```

Which allowed me to forget about it, it seems every Linux I tried it on had that. I am not even sure where the icon is visible at all, feel free to share where it is. Maybe in the desktop switcher at run time?

**Comment by diovudau** [comment]
In Archlinux there is no python icon at all. 
The result for `find . | grep -i "python"` in both /usr/share/pixmaps and /usr/share/icons  (recursive) is empty.
This might be an actual Archlinux packaging problem.  However, I am not going to contact the arch-people for that. 

Thanks for the explanation, I can work with that.

**Comment by kayhayen** [comment]
There was an option added in the last release to specify the icon, check help out of 0.6.11 or higher.

**Comment by ericdraken** [comment]
> There was an option added in the last release to specify the icon, check help out of 0.6.11 or higher.

`--linux-onefile-icon` for future readers.

Thanks for the great work, @kayhayen

**Comment by emsi** [comment]
`--onefile` does not produce statically linked executable. When moved to another system it tries to use host's glibc. My guess it's AppImage?

```
$ file python_app.bin 
ludo.bin: ELF 64-bit LSB executable, x86-64, version 1, dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, stripped


$ ./python_app.bin 
./ludo.bin: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./ludo.bin)
./ludo.bin: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_ludo.bcgjdNl/libpython3.8.so.1.0)
./ludo.bin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_ludo.bcgjdNl/libpython3.8.so.1.0)
./ludo.bin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_ludo.bcgjdNl/libpython3.8.so.1.0)
./ludo.bin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.26' not found (required by /tmp/.mount_ludo.bcgjdNl/libpython3.8.so.1.0)
./ludo.bin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /tmp/.mount_ludo.bcgjdNl/libpython3.8.so.1.0)
./ludo.bin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_ludo.bcgjdNl/libexpat.so.1)
```

Having an option to build truly statically linked binary would be great for producing portable applications.

**Comment by kayhayen** [comment]
There is a hacky way to enable non-appimage, using `--onefile-tempdir`, which is undocumented, and enables the code used on macOS, FreeBSD, etc. and actually I didn't consider static linking of glibc for libc for those, as they won't have the issue. 

For commercial users, there is a Linux container with old glibc and new tools chain, that you build these in, and then they ought to be portable:

https://nuitka.net/pages/commercial.html

I think Nuitka creates binaries dynamically linked by default, and chances are that Python you are using does it as well. The only way to produce forward working binaries, is to do it on the oldest system you want to support. On Linux, things are not really geared well for backward porting of binaries.

**Comment by SarahBeecroft** [comment]
For future readers that are getting stuck on the `--linux-onefile-icon` thing, my struggle was that the HPC centre didn't have the .xpm files available for some reason. I found the file on another linux virtual machine I have, copied to HPC and supplied it to the --linux-onefile-icon argument, and problem was solved. Just posting for posterity.

**Comment by kayhayen** [comment]
Well, you are aware, that you can and probably should provide another icon that the Python default one, right?

**Comment by SarahBeecroft** [comment]
Yeah I had a quick try but I must not have supplied the right thing. With my setup, it was more convenient to just copy over the exact thing it wanted. Will be different for different users I'm sure. I'll admit supplying icon files isn't something I've come across in the past, so I thought it might trip up other users too, and having a workaround post somewhere might help someone in the future. Possibly me, haha!
