### ISSUE TITLE
Is the --onefile option available in Windows 7?

### ISSUE THREAD

**Issue by MKdays** [Nuitka/Nuitka#904]
Hello, I like the new option.
I am testing compatibility according to Windows version.
I used the --onefile option, but there was an error in Windows 7.

### Env
> 0.6.10
> Python: 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 16:33:24) [MSC v.1928 32 bit (Intel)]
> Executable: C:\Python\python.exe
> OS: Windows
> Arch: x86

```
NUITKA v(0, 6, 10) on Python 3.9.1 (win32) is compiling 'C:/Users/MK/Desktop/Py_Project/test.py' with these options:
 --standalone
 --recurse-none
 --hinted-json-file=C:/Users/MK/Desktop/Py_Project/test-39-win32-32.json
 --plugin-enable=qt-plugins
 --include-qt-plugins=sensible,styles
 --remove-output
 --windows-product-version=1.0.0.0
 --windows-company-name=MK
 --windows-file-description=MK
 --output-dir=../Nuitka
 --onefile
 --windows-icon-from-ico=exe.ico
```

test.py
```
import pathlib
print(pathlib.Path(__file__))
input()
```
### Result

> Windows 10 x32 : OK
> Windows 10 x64 : OK
> Windows 7 x32 : Error

### Windows 7 Error Code:
> Problem signature:
>   Problem Event Name:	APPCRASH
>   Application Name:	test.exe
>   Application Version:	1.0.0.0
>   Application Timestamp:	5fd76c7b
>   Fault Module Name:	KERNELBASE.dll
>   Fault Module Version:	6.1.7601.24168
>   Fault Module Timestamp:	5b1aa77b
>   Exception Code:	c0000005
>   Exception Offset:	0000c510
>   OS Version:	6.1.7601.2.1.0.256.1
>   Locale ID:	1033
>   Additional Information 1:	0a9e
>   Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
>   Additional Information 3:	0a9e
>   Additional Information 4:	0a9e372d3b4ad19135b953a78882e789
> 
> Read our privacy statement online:
>   http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409
> 
> If the online privacy statement is not available, please read our privacy statement offline:
>   C:\Windows\system32\en-US\erofflps.txt

![image](https://user-images.githubusercontent.com/64838226/102089988-41ffd580-3e60-11eb-97ef-707476695321.png)

**Comment by kayhayen** [comment]
There is documentation how to do Windows 7 in the User Manual. If that doesn'T work, find out why, then open a PR. Otherwise Windows 7 is unsupported.

**Comment by kayhayen** [comment]
That said, @deajan did you have any luck with onefile with your Windows 7?

**Comment by ArkadiuszMichalski** [comment]
@MKdays or anybody can confirm that this project still works with Windows 7? I mean, if it possible to compile under Windows 7, even a simple `priint ("hello")`?

My setup is:
```
nuitka --version
0.6.10.4
Python: 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
Executable: Ř,
OS: Windows
Arch: x86_64
```
I see above that `Executable` has strange value: ` Ř`, but i don't know if this is a problem. 
I also  have MinGW64 and add it's `bin` to system Path. This version:
https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/seh/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z

After run `nuitka --mingw64 test.py` I get error:
```
D:\WinPython\_test>nuitka --mingw64 test.py
Traceback (most recent call last):
  File "D:\WinPython\python-3.9.1.amd64\lib\runpy.py", line 197, in _run_module_
as_main
    return _run_code(code, main_globals, None,
  File "D:\WinPython\python-3.9.1.amd64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\WinPython\python-3.9.1.amd64\lib\site-packages\nuitka-0.6.10.4-py3.9.
egg\nuitka\__main__.py", line 196, in <module>
    main()
  File "D:\WinPython\python-3.9.1.amd64\lib\site-packages\nuitka-0.6.10.4-py3.9.
egg\nuitka\__main__.py", line 137, in main
    Execution.callExec(args)
  File "D:\WinPython\python-3.9.1.amd64\lib\site-packages\nuitka-0.6.10.4-py3.9.
egg\nuitka\utils\Execution.py", line 49, in callExec
    process = subprocess.Popen(args=args)
  File "D:\WinPython\python-3.9.1.amd64\lib\subprocess.py", line 947, in __init_
_
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\WinPython\python-3.9.1.amd64\lib\subprocess.py", line 1416, in _execu
te_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Nie można odnaleźć określonego pliku
```
This message `Nie można odnaleźć określonego pliku` in english mean `The specified file could not be found`, but I have this file in my Python folder {`D:\WinPython\python-3.9.1.amd64\lib`}.

@kayhayen 
>There is documentation how to do Windows 7 in the User Manual. If that doesn'T work, find out why, then open a PR. Otherwise Windows 7 is unsupported.

Can you point where exactly is some hint for windows 7?

**Comment by Pro100rus32** [comment]
> @MKdays or anybody can confirm that this project still works with Windows 7? I mean, if it possible to compile under Windows 7, even a simple `priint ("hello")`?
> 
> My setup is:
> 
> ```
> nuitka --version
> 0.6.10.4
> Python: 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
> Executable: Ř,
> OS: Windows
> Arch: x86_64
> ```
> 
> I see above that `Executable` has strange value: ` Ř`, but i don't know if this is a problem.
> I also have MinGW64 and add it's `bin` to system Path. This version:
> https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/seh/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z
> 
> After run `nuitka --mingw64 test.py` I get error:
> 
> ```
> D:\WinPython\_test>nuitka --mingw64 test.py
> Traceback (most recent call last):
>   File "D:\WinPython\python-3.9.1.amd64\lib\runpy.py", line 197, in _run_module_
> as_main
>     return _run_code(code, main_globals, None,
>   File "D:\WinPython\python-3.9.1.amd64\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "D:\WinPython\python-3.9.1.amd64\lib\site-packages\nuitka-0.6.10.4-py3.9.
> egg\nuitka\__main__.py", line 196, in <module>
>     main()
>   File "D:\WinPython\python-3.9.1.amd64\lib\site-packages\nuitka-0.6.10.4-py3.9.
> egg\nuitka\__main__.py", line 137, in main
>     Execution.callExec(args)
>   File "D:\WinPython\python-3.9.1.amd64\lib\site-packages\nuitka-0.6.10.4-py3.9.
> egg\nuitka\utils\Execution.py", line 49, in callExec
>     process = subprocess.Popen(args=args)
>   File "D:\WinPython\python-3.9.1.amd64\lib\subprocess.py", line 947, in __init_
> _
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "D:\WinPython\python-3.9.1.amd64\lib\subprocess.py", line 1416, in _execu
> te_child
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> FileNotFoundError: [WinError 2] Nie można odnaleźć określonego pliku
> ```
> 
> This message `Nie można odnaleźć określonego pliku` in english mean `The specified file could not be found`, but I have this file in my Python folder {`D:\WinPython\python-3.9.1.amd64\lib`}.
> 
> @kayhayen
> 
> > There is documentation how to do Windows 7 in the User Manual. If that doesn'T work, find out why, then open a PR. Otherwise Windows 7 is unsupported.
> 
> Can you point where exactly is some hint for windows 7?

This is the first version of Python to default to the 64-bit installer on Windows. The installer now also actively disallows installation on Windows 7. Python 3.9 is incompatible with this unsupported version of Windows.

**Comment by ArkadiuszMichalski** [comment]
@Pro100rus32  
I test also with:
```
D:\WinPython\_test>nuitka --version
0.6.10.4
Python: 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]
Executable: Ř1
OS: Windows
Arch: x86_64
```
Same problem. There are problems with paths, I don't know if Win7 is just too old or if I don't have something set correctly (some environment variable).

**Comment by kayhayen** [comment]
@Pro100rus32 love you for that, I will add it to the docs, I knew it in theory, but it's easy to not have it on your mind.

As for mingw, do not install it, let Nuitka download it for you. Just don't have it in PATH.

And from the Executable: output, that is just plain `sys.executable` and indicative of your Python not feeling at home on that OS, or not with the installation path it is finding itself in. You might have to go back further. Or at least, you might have to install to something that doesn't contain anything that is not ASCII.

Ah, and don't use WinPython, it might be gargage or more aggressive about Windows 7 support, or... I considered checking out, if Nuitka supports it, but right now it does not. Use CPython or Anaconda, those I know work.

**Comment by kayhayen** [comment]
I thought the user manual had something about Windows 7, but it doesn't. Well, I know people have done it, but I won't care too much. But it definitely requires using very old toolchains.

**Comment by ArkadiuszMichalski** [comment]
WinPython it's just wrapper for CPython + a few modules and batch files (which set environment variables) to make it poratable. I also try using official "Windows embeddable package" from python page but still get this problem. Maybe the standard installation will work, that's why I'm asking here if anyone else has this tool still working under Win7, If yes then please share what version python and nuitka you used.

Maybe my Windows 7 system is damaged in some way, so that why it's doesn't work. But I also tested a virtual machine and still get the same problem. On the other hand, everything works on Windows 10.

If anyone get problem on Windows 7 that missing some .dll when running python then please read this:
https://github.com/winpython/winpython/issues/906#issuecomment-749146260

**Comment by ArkadiuszMichalski** [comment]
@kayhayen 

I download  last "Windows embeddable package" from official python page to Python (folder) and:
- rename `python39._pth` to `_python39._pth` (because on Win7 this file breake python) << cry that encoding module cant be find
- create Lib (and site-packages) and Script folder inside Python folder
- on  site-packages I install last pip and setuptools
-  so in Script folder now I have pip and easy-install .exe
- also set PYTHON var to my python.exe and add Script to Path var.

Now I try install Nuitka:
- pip install nuitka
```
    ERROR: Error [WinError 2] Nie można odnaleźć określonego pliku while executing command python setup.py e
gg_info                                                                                                     
ERROR: Could not install packages due to an EnvironmentError: [WinError 2] Nie można odnaleźć określonego pl
iku                                                                                                         
```
- easy_install https://github.com/Nuitka/Nuitka/archive/0.6.10.5.tar.gz
 ```
WARNING: The easy_install command is deprecated and will be removed in a future version.                   
Downloading https://github.com/Nuitka/Nuitka/archive/0.6.10.5.tar.gz                                       
Processing 0.6.10.5.tar.gz                                                                                 
Writing D:\zSyf\Temp\easy_install-uras9bg6\Nuitka-0.6.10.5\setup.cfg                                       
Running Nuitka-0.6.10.5\setup.py -q bdist_egg --dist-dir D:\zSyf\Temp\easy_install-uras9bg6\Nuitka-0.6.10.5
egg-dist-tmp-95nxthel                                                                                      
warning: no files found matching 'README.pdf'                                                              
warning: no files found matching 'Changelog.pdf'                                                           
warning: no files found matching 'Developer_Manual.pdf'                                                    
warning: no files found matching 'doc\*.1'                                                                 
error: Setup script exited with error: command 'ŘG' failed: None                                           
```
- python setup.py install
```
running install                                              
running bdist_egg                                            
running egg_info                                             
writing Nuitka.egg-info\PKG-INFO                             
writing dependency_links to Nuitka.egg-info\dependency_links.
writing entry points to Nuitka.egg-info\entry_points.txt     
writing top-level names to Nuitka.egg-info\top_level.txt     
reading manifest file 'Nuitka.egg-info\SOURCES.txt'          
reading manifest template 'MANIFEST.in'                      
warning: no files found matching 'README.pdf'                
warning: no files found matching 'Changelog.pdf'             
warning: no files found matching 'Developer_Manual.pdf'      
warning: no files found matching 'doc\*.1'                   
writing manifest file 'Nuitka.egg-info\SOURCES.txt'          
installing library code to build\bdist.win-amd64\egg         
running install_lib                                          
running build_py                                             
writing byte-compilation script 'D:\zSyf\Temp\tmpp5skhznm.py'
Ř= D:\zSyf\Temp\tmpp5skhznm.py                               
error: command 'Ř=' failed: None                             
                                                             
```

Any advice why I get such error? Same story as in comment https://github.com/Nuitka/Nuitka/issues/904#issuecomment-756988571, command is not recognizde, even when I set PYTHON var to correct file.

**Comment by ArkadiuszMichalski** [comment]
Hmm I print `args` inside `def callExec(args)` from `Execution.py` file: and get:
```['Ř6', 'Ř6', '-S', 'C:\\Users\\Arek\\Desktop\\Python2\\lib\\site-packages\\nuitka-0.6.10.5-py3.9.egg\\nuitka\\__main__.py', '--mingw64', 'test.py']```

Why this two element inside args is wrong recognized? What fails here, can it be fixed somehow under Win7?

**Comment by ArkadiuszMichalski** [comment]
@kayhayen 
I installed python from the installer and pip/nuitka works fine. So looks like portable version of python in Windows 7 is not supported (like WinPython or "Windows embeddable package" from official python page).

I also copy instaled version to other folder, set some vars and try compile simple script. Same error as above.  It would be worth adding this information in the manual. A strange thing, because these portable versions work under Win10.

**Comment by kayhayen** [comment]
@ArkadiuszMichalski Your fantasy of what WinPython is, doesn't match reality. From an end user standpoint, you are right, but not when it comes to building extension modules against it or embedding the Python library in an executable.

Much like Anaconda, while it's using the source code, it is using a different configuration, where things regarding the exposure of shared link libraries are defined, and a different tool chain, maybe gcc, maybe clang, definitely not the same as CPython. These differences can be huge technically. Sometimes they result in more or less performance, more or less portability, and more or less compatibility.

It's a mess.

I never saw the embeddable package from CPython so far. I wonder if it's a new thing.

**Comment by kayhayen** [comment]
It's there since 3.5 already https://docs.python.org/3/using/windows.html#windows-embeddable

**Comment by kayhayen** [comment]
Seems WinPython is working for me, so I remove that annotation.

**Comment by deajan** [comment]
To me it looks like the issue with --onefile that were present before last boolean / int patch.
Had the same on Windows 10.

Does it work without --onefile ?

**Comment by kayhayen** [comment]
The embeddable Python is a joke and trap. It contains no Python header files, no pip and nothing really. Unfortunatly neither WinPython, nor CPython or Anaconda provide any way of recognizing them. I wish I could blacklist them as easily as the Windows store Python.

**Comment by kayhayen** [comment]
@deajan the crash was because of 3.9 on Windows 7, nothing supports that, after that it's just difficult to install a CPython it seems, the embeddable Python is listed before the usable one, and admittedly, it sounds great. But it really is not usable on its own, and clearly not for Nuitka.

**Comment by ArkadiuszMichalski** [comment]
@kayhayen 
>Your fantasy of what WinPython is, doesn't match reality. 

I started my adventure with Python a few days ago, so please be understanding. I don't know exactly how it is built. I just noticed that after installing Python I see the same directory structure as in WinPython (here they add more stuff later). Maybe they build this tool differently and hence the problems, but it's beyond my skills.

>Seems WinPython is working for me, so I remove that annotation.

But working on what system, Win7? So the simple script compilation is finished using WinPython, Nuitka and Win7? If yest can you give me exactly wich version you used?

From what I can see, it just works for me to install Python 3.8.7 on Win7. Any othere portable solution generate above problem. I even copied the install Python directory elsewhere (to the desktop), uninstal Python, cleare registry, and this copy folder from desktop still works. But when I copy them to othere machine (still with Win7) I get above problem.

I'm just looking for some way to compile a simple python script, but without having to install all the python backend, I need some portable version. Unfortunately, the whole thing is done on Win7 and hence these combinations. On Win10, all the portable solutions I mentioned just work.

Backing to "embeddable package", it's comes with 3.5 version:
https://docs.python.org/3/using/windows.html#the-embeddable-package
>Third-party packages should be installed by the application installer alongside the embedded distribution. Using pip to manage dependencies as for a regular Python installation is not supported with this distribution, though with some care it may be possible to include and use pip for automatic updates. In general, third-party packages should be treated as part of the application (“vendoring”) so that the developer can ensure compatibility with newer versions before providing updates to users.

So missing pip is expected. But even if I manually add the necessary modules https://github.com/Nuitka/Nuitka/issues/904#issuecomment-757566180, I get the same error as for WinPython.

**Comment by kayhayen** [comment]
I don't care about Windows 7 @ArkadiuszMichalski and so do WinPython developers, and CPython developers since 3.9, and the `embeddable` package is not usable for Nuitka, because it lacks the C header files describing the C API of Python for one, you cannot use that either. Using that would be the absolutely hardest way to use CPython with Nuitka for no reason as Nuitka can extract that all by itself. Now if there was a static link library in there, that would be a thing, but there is no such thing for any CPython based distribution on Windows.

Nuitka itself doesn't do stuff that's not going to work with Windows 7. From what I understand, using a old enough MSVC and CPython should allow you to do hello world level stuff. I don't know how far back you have to go, but I would checkout Python 2.7 first. That would have to work, but I would download something like 2.7.6 there and not the latest bugfix release. Not sure if 3.8 doesn't already need Windows XP at least.

Another thing to check would be Anaconda, which might have once supported Windows 7.

**Comment by ArkadiuszMichalski** [comment]
OK, after a few tests, the last working WinPython for Win7 is WinPython_3.6.3.0:
https://github.com/winpython/winpython/releases/tag/1.9.20171031
Both pip and nuitka work without any problems. Unfortunately, we have a slightly older version of python and we have to be careful with the commands we use, but if someone really cares about the portable version for Win7, they have a hint ready.

Thanks for the tips.

**Comment by lich4** [comment]
See this,  https://github.com/Nuitka/Nuitka/issues/1920

**Comment by lich4** [comment]
> There is documentation how to do Windows 7 in the User Manual. If that doesn'T work, find out why, then open a PR. Otherwise Windows 7 is unsupported.

https://github.com/Nuitka/Nuitka/issues/1920

**Comment by stonebig** [comment]
so for Windows 7, last version that may still work is WinPython-3.8.9.0 of April 21th, 2021.
the older the better

**Comment by deajan** [comment]
@stobebig source ?

**Comment by kayhayen** [comment]
Nuitka-Python for 3.9 has patches to make it work on Windows 7. For what I know, they mostly disabled it only in the installer parts, so I wouldn't be surprised if some 3.9 compilations made on say 3.10 were backportable. But 3.8 is the last one to officially support it from CPython. Obviously, either way you have to take care of your dependencies as well. Do not think of using modern PyPI packages, much software has dropped even support.for early Windows 10 build.

The recommended way remains to create something running on that target OS and to compile there. When that works, compiling on Windows 11 will often be backward portable with the right compiler. I have supported customers do to Windows XP with this approach, alas with 3.4 there. That is the real challenge btw. :)

**Comment by deajan** [comment]
So far, I always used Python 3.7 as maximal version for my Windows 7 builds, which worked for over 5k different computers.
I'd stay away from newer verisons too ;)
