### ISSUE TITLE
Pillow: PIL.UnidentifiedImageError

### ISSUE THREAD

**Issue by biqqles** [Nuitka/Nuitka#909]
Hi, and thanks for this exciting project which somehow passed me by until very recently.

It seems Pillow is not packaged completely correctly, on Windows at least (I haven't tested on Linux).

I've written a tiny program to demonstrate this:

```python
from PIL import Image

with open('any.tga', 'rb') as f:
    Image.open(f)
```

This file works fine when run with Python normally. It compiles fine  with `nuitka test.py --standalone`, with or without `--follow-imports`. However, when the executable is run:

```C:\Users\biqqles\...\test.dist> ./test.exe
Traceback (most recent call last):
  File "C:\Users\biqqles\...\TEST~1.DIS\test.py", line 4, in <module>
  File "C:\Users\biqqles\...\TEST~1.DIS\PIL\Image.py", line 2930, in open
PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='any.tga'>
```

I tested the executable with a PNG file instead and that worked fine, so I think this error only affects TGA and maybe some other of the more unusual formats supported by PIL.

* Tested with Nuitka `develop` and `0.6.10.1`

* I installed Nuitka with pip

```
> python -m nuitka --version
0.6.11rc4
Python: 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:37:30) [MSC v.1927 32 bit (Intel)]
Executable: C:\Users\biqqles\Documents\Python\Python38-32\python.exe
OS: Windows
Arch: x86
```

**Comment by biqqles** [comment]
I came back to this - somewhat obviously adding `from PIL import TgaImagePlugin` to the file is a fine workaround. Time permitting I might be able to contribute a Pillow plugin, if that's something you would be happy accepting. One problem would be that it would presumably have to include all image plugins since it's impossible to determine which ones will be used ahead of time.

**Comment by kayhayen** [comment]
Sorry, I forgot to state this, but I added the implicit import already. A bunch of formats were listed, this one is probably new.

**Comment by kayhayen** [comment]
Ah wait, I was confused, this is in our current implicit imports plugin code:

```
        # imageio imports -----------------------------------------------
        elif full_name == "imageio":
            yield "PIL.BlpImagePlugin"
            yield "PIL.BmpImagePlugin"
            yield "PIL.BufrStubImagePlugin"
            yield "PIL.CurImagePlugin"
            yield "PIL.DcxImagePlugin"
            yield "PIL.DdsImagePlugin"
            yield "PIL.EpsImagePlugin"
            yield "PIL.FitsStubImagePlugin"
            yield "PIL.FliImagePlugin"
            yield "PIL.FpxImagePlugin"
            yield "PIL.FtexImagePlugin"
            yield "PIL.GbrImagePlugin"
            yield "PIL.GifImagePlugin"
            yield "PIL.GribStubImagePlugin"
            yield "PIL.Hdf5StubImagePlugin"
            yield "PIL.IcnsImagePlugin"
            yield "PIL.IcoImagePlugin"
            yield "PIL.ImImagePlugin"
            yield "PIL.ImtImagePlugin"
            yield "PIL.IptcImagePlugin"
            yield "PIL.Jpeg2KImagePlugin"
            yield "PIL.JpegImagePlugin"
            yield "PIL.McIdasImagePlugin"
            yield "PIL.MicImagePlugin"
            yield "PIL.MpegImagePlugin"
            yield "PIL.MpoImagePlugin"
            yield "PIL.MspImagePlugin"
            yield "PIL.PalmImagePlugin"
            yield "PIL.PcdImagePlugin"
            yield "PIL.PcxImagePlugin"
            yield "PIL.PdfImagePlugin"
            yield "PIL.PixarImagePlugin"
            yield "PIL.PngImagePlugin"
            yield "PIL.PpmImagePlugin"
            yield "PIL.PsdImagePlugin"
            yield "PIL.SgiImagePlugin"
            yield "PIL.SpiderImagePlugin"
            yield "PIL.SunImagePlugin"
            yield "PIL.TgaImagePlugin"
            yield "PIL.TiffImagePlugin"
            yield "PIL.WebPImagePlugin"
            yield "PIL.WmfImagePlugin"
            yield "PIL.XbmImagePlugin"
            yield "PIL.XpmImagePlugin"
            yield "PIL.XVThumbImagePlugin"
```

I agree, a plugin would be nice, and one that detects all available image format plugins and tells people about itself if not used. I imagine these all in all might have hefty dependencies and therefore might make sense to only enable one for the standalone distribution case. Just doing it all doesn't quite cut it.

**Comment by biqqles** [comment]
If `TgaImagePlugin` was in the implicit import list, do you know why it was not implicitly included here? Also yes, a plugin with a switch similar to `--include-qt-plugins` that allowed the user to select which image plugins they wanted would be nice to have.
