### ISSUE TITLE
mingw is missing, instruction is misleading

### ISSUE THREAD

**Issue by danieltuzes** [Nuitka/Nuitka#912]
If I am not mistaken, this is a problem with mingw, but I report it here to be sure and to get updated about the progress and to find workarounds.

## version
Python and nuitka version info:

```
(base) PS C:\Users\UserName\source\repos\collection\sandbox> python -m nuitka --version
0.6.10.2
Python: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Users\UserName\miniconda3\python.exe
OS: Windows
Arch: x86_64
(base) PS C:\Users\UserName\source\repos\collection\sandbox>
```

## installation
I installed nuitka with `conda install nuitka`.

## what the problem is

```
(base) PS C:\Users\UserName\source\repos\collection\sandbox_py> python -m nuitka --mingw64 will_compile.py  
Nuitka:INFO: Starting Python compilation.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating C source code for backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka will use gcc from MinGW64 of winlibs to compile on Windows.

Is it OK to download and put it in "C:\Users\UserName\AppData\Local\Nuitka\Nuitka\gcc\x86_64\10.2.0-11.0.0-9.0.0-r3".

No installer needed, cached, one time question.

Proceed and download? [Yes]/No
y
Nuitka:INFO: Downloading 'https://github.com/brechtsanders/winlibs_mingw/releases/download/10.2.0-11.0.0-9.0.0-r3/winlibs-x86_64-posix-seh-gcc-10.2.0-mingw-w64-8.0.0-r3.zip'.
Failed to download 'https://github.com/brechtsanders/winlibs_mingw/releases/download/10.2.0-11.0.0-9.0.0-r3/winlibs-x86_64-posix-seh-gcc-10.2.0-mingw-w64-8.0.0-r3.zip'. Contents should manually be extracted to 'C:\Users\UserName\AppData\Local\Nuitka\Nuitka\gcc\x86_64\10.2.0-11.0.0-9.0.0-r3\winlibs-x86_64-posix-seh-gcc-10.2.0-mingw-w64-8.0.0-r3.zip'.
(base) PS C:\Users\UserName\source\repos\collection\sandbox_py>
```

## tried to solve it myself
You can get the [latest gcc from mingw](https://github.com/brechtsanders/winlibs_mingw/releases/download/10.2.0-11.0.0-8.0.0-r5/winlibs-x86_64-posix-seh-gcc-10.2.0-mingw-w64-8.0.0-r5.zip), but the error code above asks to extract it into a zip file. Don't do that, extract the content into `C:\Users\UserName\AppData\Local\Nuitka\Nuitka\gcc\x86_64\10.2.0-11.0.0-9.0.0-r3\mingw64` so that this folder contains the subfolders and the `version_info.txt` too.

**Comment by kayhayen** [comment]
The one for Nuitka is linked from http://winlibs.com/ and the link in Nuitka should not 404 anymore, at least when I tried it after reporting the fact that they go away. On develop it's good, but I guess stable needs a fixup for that then, as there is a r5 link that works.

**Comment by kayhayen** [comment]
You were not using the latest stable, at the time 0.6.10.3 was available, with the fix included.
