### ISSUE TITLE
Fatal Python error: initfsencoding: unable to load the file system codec

### ISSUE THREAD

**Issue by thinkoaa** [Nuitka/Nuitka#913]
An error occurred while running on another computer:

on win10:

Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'
Current thread 0x00001870 (most recent call first):

on winserver2008:

Fatal Python error: _Py_HashRandomization_Init: failed to get random numbers to initialize Python

**Comment by kayhayen** [comment]
Not filling out the issue template, this cannot be analysed.
