### ISSUE TITLE
Can't compile script with nltk

### ISSUE THREAD

**Issue by linuxTown** [Nuitka/Nuitka#914]
Hello, it seems that Nuitka is unable to compile scripts when `nltk` package is included.

This is a simple example of script that fails to compile as a standalone with `--recurse-all` parameter:

```
import nltk

print("hello world")
```

This file works fine when run with Python normally, but it fails when I try to compiled it as a standalone:

`python -m nuitka --standalone --recurse-all --show-progress example.py`

 This is the error that I receive when trying to execute above command:
```
...
module.nltk.sem.linearlogic.cpp(10362): error C2094: label 'function_exception_exit' was undefined
scons: *** [module.nltk.sem.linearlogic.obj] Error 2
scons: building terminated because of errors.
```

Also tried with gcc on WSL with Ubuntu, this is the error I received:

```
...
module.nltk.sem.linearlogic.c: In function 'impl_nltk$sem$linearlogic$$$function_32___hash__':
module.nltk.sem.linearlogic.c:10465:13: error: label 'function_exception_exit' used but not defined
10465 |             goto function_exception_exit;
      |             ^~~~
module.nltk.sem.linearlogic.c: In function 'impl_nltk$sem$linearlogic$$$function_38___hash__':
module.nltk.sem.linearlogic.c:13148:13: error: label 'function_exception_exit' used but not defined
13148 |             goto function_exception_exit;
      |             ^~~~
scons: *** [module.nltk.sem.linearlogic.o] Error 1
```

I installed Nuitka with pip

```
Nuitka version: 0.6.10.3
OS: Windows also tried with WSL on Ubuntu with gcc and received the same error
Python 3.8.6
```

**Comment by kayhayen** [comment]
Thanks for your report, this seems to be a problems with optimization of `hash` not considering that even if the argument is known to be hashable, it may still raise an exception to get there.

The (almost) minimal reproducer is this:

```
def __hash__(self):
        return hash("%s%s" % (u, hash(v)))
```

There will be a hotfix for this.

**Comment by kayhayen** [comment]
That hotfix is out for a very long time of course already.
