### ISSUE TITLE
Is there some kind of portable without `--standalone` that uses existing Python installation

### ISSUE THREAD

**Issue by retsyo** [Nuitka/Nuitka#915]
currently, if no `--standalone` is used, the created EXE file reads python libraries from the `lib` sub-directory where python.exe is located. 
In other word
1. if I rename `c:\python36` to `c:\python3`, then the EXE fails to run
2. if I installed python 3.6 on other PC but under `d:\python`, then the EXE fails to run
and also it seems that it is not necessary to copy `python36.dll` to the directory where the created EXE file lives since it should be the parent directory where the EXE try to find python libraries

is it possible to add an options `--find-pythondll` for nuitka, then 
`nuikta --find-pythondll=.. main.py`
creates `main.exe` which will try to load `python36.dll` from the parent directory, and find python libraries from `..\lib`. 
so I can put it under a sub-directory of `python.exe`

thanks

**Comment by retsyo** [comment]
Yes, I have found the following in the document
but my advice is for user not for coder

```
Dynamic sys.path

If your script modifies sys.path to e.g. insert directories with source code relative to it, Nuitka will currently not be able to see those. However, if you set the PYTHONPATH to the resulting value, you will be able to compile it.
```

**Comment by kayhayen** [comment]
Your best way of distribution to use in an existing Python installation is to make an extension module, which will be portable to that specific Python version used to compile, and then a batch file to do the scanning, and a minimal executable that loads the DLL from there.

In fact, I bet this could be done relatively easily, with the new Windows bootstrap even as a single file to the user. But I would do it only if paid for, as it's work and not needed really. I estimate this would be take 4 days to create. Until such time this will remain unimplemented.

Yours,
Kay
