### ISSUE TITLE
OSError: libcurand.so.10: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mantejemilence1** [Nuitka/Nuitka#916]
python -m nuitka --standalone --follow-imports --plugin-enable=numpy --plugin-enable=pylint-warnings --plugin-enable=qt-plugins --nofollow-import-to=torch newdesg.py 
i have used  the command above for creating  standalone package  and have copied torch from environment /sitepackage. im getting this error while running the created standalone package 
OSError: libcurand.so.10: cannot open shared object file: No such file or directory

(yolact-env) elad@elad-Alienware-m15-R3:~/Downloads/yolact/newdesg.dist$ ./newdesg 
Traceback (most recent call last):
  File "/home/elad/Downloads/yolact/newdesg.dist/newdesg.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/home/elad/Downloads/yolact/newdesg.dist/eval.py", line 1, in <module eval>
    from data import COCODetection, get_label_map, MEANS, COLORS
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/home/elad/Downloads/yolact/newdesg.dist/data/__init__.py", line 1, in <module data>
    from .config import *
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/home/elad/Downloads/yolact/newdesg.dist/data/config.py", line 1, in <module data.config>
    from backbone import ResNetBackbone, VGGBackbone, ResNetBackboneGN, DarkNetBackbone
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/home/elad/Downloads/yolact/newdesg.dist/backbone.py", line 1, in <module backbone>
    import torch
  File "/home/elad/Downloads/yolact/newdesg.dist/torch/__init__.py", line 189, in <module>
    _load_global_deps()
  File "/home/elad/Downloads/yolact/newdesg.dist/torch/__init__.py", line 142, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/elad/Downloads/yolact/newdesg.dist/ctypes/__init__.py", line 356, in __init__
    print("asjasksjadjkasdksadjj")
OSError: libcurand.so.10: cannot open shared object file: No such file or directory

python:3.7
ubuntu :20.04
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
bash                      4.4.18            h67949de_1000    conda-forge
blas                      1.0                         mkl  
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2020.12.8            h06a4308_0  
certifi                   2020.12.5        py37h06a4308_0  
chardet                   4.0.0                    pypi_0    pypi
cuda100                   1.0                           0    pytorch
cudatoolkit               11.0.3               h15472ef_6    conda-forge
cudnn                     8.0.5.39             ha5ca753_1    conda-forge
curl                      7.64.0               h646f8bb_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.21          py37hb892b2f_1    conda-forge
dbus                      1.13.6               hfdff14a_1    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.4               h7ca028e_0    conda-forge
gettext                   0.19.8.1          hf34092f_1004    conda-forge
git                       2.20.1          pl526hc122a05_1001    conda-forge
glib                      2.66.3               h58526e2_0    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.10                     pypi_0    pypi
jpeg                      9b                   h024ee3a_2  
kiwisolver                1.3.1            py37hc928c03_0    conda-forge
krb5                      1.16.3            hc83ff2d_1000    conda-forge
lcms2                     2.11                 h396b838_0  
libcurl                   7.64.0               h01ee5af_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libglib                   2.66.3               hbe7bbb4_0    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libssh2                   1.8.0             h1ad7b7a_1003    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
libtiff                   4.1.0                h2733197_1  
libuuid                   2.32.1            h7f98852_1000    conda-forge
libuv                     1.40.0               h7f98852_0    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_2    conda-forge
llvm-openmp               11.0.0               hfc4b9b4_1    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
matplotlib                3.3.3            py37h89c1867_0    conda-forge
matplotlib-base           3.3.3            py37h4f6019d_0    conda-forge
mkl                       2020.4             h726a3e6_304    conda-forge
mkl-service               2.3.0            py37h8f50634_2    conda-forge
mkl_fft                   1.2.0            py37h161383b_1    conda-forge
mkl_random                1.2.0            py37h9fdb41a_1    conda-forge
mouseinfo                 0.1.3                    pypi_0    pypi
ncurses                   6.2                  h58526e2_4    conda-forge
ninja                     1.10.2               h4bd325d_0    conda-forge
nuitka                    0.6.10.4                 pypi_0    pypi
numpy                     1.18.5                   pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencv-python             4.2.0.34                 pypi_0    pypi
openssl                   1.0.2u               h7b6447c_0  
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.26.2            h36c2ea0_1008    conda-forge
pillow                    6.2.2                    pypi_0    pypi
pip                       20.3.3             pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyautogui                 0.9.52                   pypi_0    pypi
pycocotools               2.0.2                    pypi_0    pypi
pygetwindow               0.0.9                    pypi_0    pypi
pymsgbox                  1.0.9                    pypi_0    pypi
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyperclip                 1.8.1                    pypi_0    pypi
pyqt                      5.6.0           py37h13b7fb3_1008    conda-forge
pyqt5                     5.15.2                   pypi_0    pypi
pyqt5-sip                 12.8.1                   pypi_0    pypi
pyrect                    0.1.4                    pypi_0    pypi
pyscreeze                 0.1.26                   pypi_0    pypi
python                    3.7.0             hd21baee_1006    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python3-xlib              0.15                     pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.7.1           py3.7_cuda11.0.221_cudnn8.0.5_0    pytorch
pytweening                1.0.3                    pypi_0    pypi
qt                        5.6.3                h8bf5577_3  
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.25.1                   pypi_0    pypi
setuptools                49.6.0           py37he5f6b98_2    conda-forge
sip                       4.18.1          py37hf484d3e_1000    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.28.0               h8b20d00_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
torchvision               0.8.2                py37_cu110    pytorch
tornado                   6.1              py37h4abf009_0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
unzip                     6.0                  h516909a_2    conda-forge
urllib3                   1.26.2                   pypi_0    pypi
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge

**Comment by kayhayen** [comment]
Manually copying anything to the dist folder is not supported.

**Comment by mantej1995** [comment]
So can u tell me the command ,my python script has pytorch and pyqt as dependency.
