### ISSUE TITLE
Runtime error when embedding matplotlib plot in qt UI

### ISSUE THREAD

**Issue by noonchen** [Nuitka/Nuitka#920]
Tried on Windows and macOS, build ok (but kind of slow...).

**CMD**
* Windows: hinted compilation
* macOS: `nuitka --standalone --plugin-enable=numpy --plugin-enable=qt-plugins  /path/to/script`

**Versions**
* python 3.8
* nuitka 0.6.10.4 installed via pip
* pyqt5 5.15.2
* matplotlib 3.3.2
* numpy 1.19.2

**Error on Windows 10:**
```
C:\Users\ADMINI~1\EXAMPL~1.DIS\Example Test.py:8: MatplotlibDeprecationWarning: Matplotlib installs where the data is not in the mpl-data subdirectory of the package are deprecated since 3.2 and support for them will be removed two minor releases later.
Traceback (most recent call last):
  File "C:\Users\ADMINI~1\EXAMPL~1.DIS\Example Test.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\ADMINI~1\EXAMPL~1.DIS\matplotlib\__init__.py", line 905, in <module matplotlib>
  File "C:\Users\ADMINI~1\EXAMPL~1.DIS\matplotlib\cbook\__init__.py", line 480, in _get_data_path
  File "C:\Users\ADMINI~1\EXAMPL~1.DIS\matplotlib\__init__.py", line 239, in wrapper
  File "C:\Users\ADMINI~1\EXAMPL~1.DIS\matplotlib\__init__.py", line 534, in get_data_path
  File "C:\Users\ADMINI~1\EXAMPL~1.DIS\matplotlib\__init__.py", line 239, in wrapper
  File "C:\Users\ADMINI~1\EXAMPL~1.DIS\matplotlib\__init__.py", line 566, in _get_data_path
RuntimeError: Could not find the matplotlib data files
```
Note: `mpl-data` folder can be found in the `dist` folder.

**Error on macOS 11.1:**
```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000008
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [84696]
```

**Example code:**
```
import os, sys

# pyqt5
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QApplication

import matplotlib
matplotlib.use('QT5Agg')
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvas
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar

# high dpi stretch
if hasattr(QtCore.Qt, 'AA_EnableHighDpiScaling'):
    QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)
if hasattr(QtCore.Qt, 'AA_UseHighDpiPixmaps'):
    QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True)
    
if __name__ == '__main__':
    os.environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "1"
    app = QApplication([])
    window = QtWidgets.QMainWindow()

    #plot
    fig = plt.Figure((3, 2))
    canvas = FigureCanvas(fig)
    ax = fig.add_subplot(111)
    ax.plot([0, 1], [1, 2], "-o")
    
    layout = QtWidgets.QVBoxLayout()
    layout.addWidget(canvas)
    layout.addWidget(NavigationToolbar(canvas, None))
    
    widget = QtWidgets.QWidget()
    widget.setLayout(layout)
    window.setCentralWidget(widget)

    window.show()
    sys.exit(app.exec_())
```

**Comment by linluc** [comment]
I had a somewhat similar problem but with a different application. Check the source of "get_data_path". In my case the binary made by Nuitka expected the data files to be placed where python installed modules are stored "/usr/local/lib/dist-packages" which is clearly wrong. So for the purpose of the Nuitka compilation I had to modify the source of my application (yes, inside /usr/local/lib/dist-packages,  function similar to "get_data_path") and made it point to the location of the executable. 

I think many python compiled programs will experience this issue, because by definition python module location after installation is rather fixed, but the binary simply does not know it.

**Comment by kayhayen** [comment]
I forget now, if this is a duplicate or not, but there was a hotfix that added support for matplotlib 3.3, which required moving the folder and the config file format also changed. It should be good in 0.6.11.3 which was released the other day.

**Comment by noonchen** [comment]
@kayhayen 
The latest version 0.6.11.2 fixed the issue on Windows, but the segfault on macOS (11.1) was still not unresolved yet. I'd like to help you debug this segfault but I don't know-how...😂

**Comment by kayhayen** [comment]
Use --debugger which may work on macOS, I forgot, if not, make it work.
