### ISSUE TITLE
Why am I getting Encoding error in Django manage.py file

### ISSUE THREAD

**Issue by AjayBile** [Nuitka/Nuitka#922]
I am using ubuntu 18.04, python 3.6.9 and Nuitka 0.6.10.4 version

I have complete Django Project where i am trying to convert complete project in SO files and manage.py as a bin file using Nuitka.

In Manage.py i for line execute_from_command_line(sys.argv) i am getting below error

SyntaxError: Non-UTF-8 code starting with '\xd1' in file ./manage.bin on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Please note i have added # -*- coding: utf-8 -*- in all python files still not able to solve this issue

Can anyone please help

**Comment by kayhayen** [comment]
This is typically done when you attemp to execute the compiled binary as a Python script, but of course that's a bad idea. Django probably needs a change to support this.
