### ISSUE TITLE
Please add a sponsor button/Funding.yml to this repo.

### ISSUE THREAD

**Issue by ytrezq** [Nuitka/Nuitka#923]
https://github.blog/2020-03-24-getting-started-with-github-sponsors/

It appears your project is most advanced working idea towards an almost Gil free implementation of Python3. I m currently using [Python projects](https://github.com/ConsenSys/mythril/issues/936) with [objects that don t serialize](https://github.com/Z3Prover/z3/issues/4935#issuecomment-755175243).

Through it appears performance enhancements only apply to single file programs and not accross multiple site-packages and especially if when (pretty much used in everything serious) Numpy, but it seems your re still doing better than Numba for detecting Object types.

So if you start by adding something able to detect and do a special case handling for Numpy objects and possibly rely on the existing work of a compiler or third party librarary for analysing type dependencies instead of starting huge work from scratch, then I m billing t9 sponsor the project for faster development.

**But not using my own money though**. As a GitHub bounty hunter, I m receiving a lifetime $8 monthly coupon spendable only on GitHub.

So if you add a sponsor button to this project, I would be able to provide that $8 per month for free.

**Comment by kayhayen** [comment]
I had added the file necessary, but it seems that is not enough. Thanks for your support. I am activating this for the repo.

**Comment by ytrezq** [comment]
@kayhayen are you sure you did follow https://github.blog/2020-03-24-getting-started-with-github-sponsors/ instruction.

Hope this will help getting numpy parallelized.

**Comment by kayhayen** [comment]
Unfortunately the Nuitka organisation has no bank account, and is not a fiscal entity, therefore I am not going through Github, but through Paypal. If that means, I am not elligble for your sponsorship, that's too bad, but right now the extra efforts seems not justified. At least, the link now shows up on Github too, which is something.

As for special handling of numpy types, that's definitely on the roadmap, but it's slow evolution. However, we might see ctypes direct C calls this year, elminating binding layers is then only more work to specify how and what.

**Comment by ytrezq** [comment]
@kayhayen but you have a bank account? Why not just direct payments to it? And in the case you use payfull GitHub services like unlimited private repositories, this can allow to fund the GitHub account directly.
