### ISSUE TITLE
Error, Visual Studio required for using ClangCL on Windows.

### ISSUE THREAD

**Issue by Pro100rus32** [Nuitka/Nuitka#927]
1#
```
nuitka --version
0.6.10.5
Python: 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]
Executable: C:\Users\andre\AppData\Local\Programs\Python\Python38\python.exe
OS: Windows
Arch: x86_64
```
Input:
`python -m nuitka --clang --standalone  --windows-uac-admin "E:\Download\test.py"`

Output:
```
Nuitka:INFO: Starting Python compilation.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating C source code for backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:WARNING: Visual Studio required for for Clang on Windows.
Nuitka-Scons:INFO: Backend C compiler: clang-cl (clang-cl).
Nuitka-Scons:WARNING: Didn't find clcache for C level caching, follow Nuitka user manual description.
In file included from __loader.c:4:
In file included from C:\Users\andre\AppData\Local\Programs\Python\Python38\include\Python.h:8:
C:\Users\andre\AppData\Local\Programs\Python\Python38\include/pyconfig.h(59,10): fatal error: 'io.h' file not found
#include <io.h>
         ^~~~~~
1 error generated.
scons: *** [__loader.o] Error 1
In file included from __constants.c:2:
In file included from C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\SITE-P~1\nuitka\build\include\nuitka/prelude.h:50:
In file included from C:\Users\andre\AppData\Local\Programs\Python\Python38\include\Python.h:8:
C:\Users\andre\AppData\Local\Programs\Python\Python38\include/pyconfig.h(59,10): fatal error: 'io.h' file not found
#include <io.h>
         ^~~~~~
1 error generated.
scons: *** [__constants.o] Error 1
In file included from __helpers.c:4:
In file included from C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\SITE-P~1\nuitka\build\include\nuitka/prelude.h:50:
In file included from C:\Users\andre\AppData\Local\Programs\Python\Python38\include\Python.h:8:
C:\Users\andre\AppData\Local\Programs\Python\Python38\include/pyconfig.h(59,10): fatal error: 'io.h' file not found
#include <io.h>
         ^~~~~~
1 error generated.
scons: *** [__helpers.o] Error 1
In file included from module.pywin32_bootstrap.c:19:
In file included from C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\SITE-P~1\nuitka\build\include\nuitka/prelude.h:50:
In file included from C:\Users\andre\AppData\Local\Programs\Python\Python38\include\Python.h:8:
C:\Users\andre\AppData\Local\Programs\Python\Python38\include/pyconfig.h(59,10): fatal error: 'io.h' file not found
#include <io.h>
         ^~~~~~
1 error generated.
scons: *** [module.pywin32_bootstrap.o] Error 1
In file included from module.__main__.c:19:
In file included from C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\SITE-P~1\nuitka\build\include\nuitka/prelude.h:50:
In file included from C:\Users\andre\AppData\Local\Programs\Python\Python38\include\Python.h:8:
C:\Users\andre\AppData\Local\Programs\Python\Python38\include/pyconfig.h(59,10): fatal error: 'io.h' file not found
#include <io.h>
         ^~~~~~
1 error generated.
scons: *** [module.__main__.o] Error 1
In file included from static_src\MainProgram.c:25:
In file included from C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\SITE-P~1\nuitka\build\include\nuitka/prelude.h:50:
In file included from C:\Users\andre\AppData\Local\Programs\Python\Python38\include\Python.h:8:
C:\Users\andre\AppData\Local\Programs\Python\Python38\include/pyconfig.h(59,10): fatal error: 'io.h' file not found
#include <io.h>
         ^~~~~~
1 error generated.
scons: *** [static_src\MainProgram.o] Error 1
In file included from static_src\CompiledCellType.c:19:
In file included from C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\SITE-P~1\nuitka\build\include\nuitka/prelude.h:50:
In file included from C:\Users\andre\AppData\Local\Programs\Python\Python38\include\Python.h:8:
C:\Users\andre\AppData\Local\Programs\Python\Python38\include/pyconfig.h(59,10): fatal error: 'io.h' file not found
#include <io.h>
         ^~~~~~
1 error generated.
scons: *** [static_src\CompiledCellType.o] Error 1
In file included from static_src\CompiledFunctionType.c:19:
In file included from C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\SITE-P~1\nuitka\build\include\nuitka/prelude.h:50:
In file included from C:\Users\andre\AppData\Local\Programs\Python\Python38\include\Python.h:8:
C:\Users\andre\AppData\Local\Programs\Python\Python38\include/pyconfig.h(59,10): fatal error: 'io.h' file not found
#include <io.h>
         ^~~~~~
1 error generated.
scons: *** [static_src\CompiledFunctionType.o] Error 1
```

2#
```
nuitka --version
0.6.11rc6
Python: 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]
Executable: C:\Users\andre\AppData\Local\Programs\Python\Python38\python.exe
OS: Windows
Arch: x86_64
```

Input:
`python -m nuitka --clang --standalone  --windows-uac-admin "E:\Download\test.py"`

Output:
```
Nuitka:INFO: Starting Python compilation.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Error, Visual Studio required for using ClangCL on Windows.
```

Visual Studio installed:
![image](https://user-images.githubusercontent.com/64806740/104124787-acbf0680-5363-11eb-95ef-23f18902c7bf.png)

**Comment by kayhayen** [comment]
Seems you don't have the Windows SDK installed, the build tools are not enough.

**Comment by kayhayen** [comment]
I wonder how in Scons we can check the Windows SDK version. In fact now that MSVC 2019 supports C11, using a newer WinSDK would enable C11 mode which can only be better than the C++03 workaround.

**Comment by kayhayen** [comment]
So I implemented retrieving the SDK version used, and I noticed that even with multiple ones installed, only one is used. For me, the latest one wasn't selected, maybe it got added later without me noticing, they of course work equally well. I will add a check for when it's missing to be raised, that should solve my doubt about your installation automatically.

Unfortunately the SDK needed for C11 is not yet released outside of Insider Preview program and therefore I won't install it yet, but it's good to know that the decision will be feasible in the future.

**Comment by Pro100rus32** [comment]
He keeps writing that I don't have Visual Studio. I haven't installed something yet?
![image](https://user-images.githubusercontent.com/64806740/104182674-db031b80-5421-11eb-8b06-627d6ed2fe52.png)

**Nuitka --Version**
```
0.6.11rc7
Python: 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]
Executable: C:\Users\andre\AppData\Local\Programs\Python\Python38\python.exe
OS: Windows
Arch: x86_64
```

Output:
```
Nuitka:INFO: Starting Python compilation.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Error, Visual Studio required for using ClangCL on Windows.
```


_I updated Factory just now._

**Comment by kayhayen** [comment]
Your screenshot looks perfect to me.

Ok, that's strange. It checks if `cl` (and therefore `cl.exe`) is found, and that should be the case if it's installed. The best help of course would be the output with `--show-scons` of current factory branch. I would like to get to the bottom of this.

**Comment by Pro100rus32** [comment]
> Мне твой скриншот кажется идеальным.
> 
> Ладно, странно. Он проверяет, найден ли `cl`(и, следовательно, `cl.exe`), и это должно быть так, если оно установлено. Лучшим подспорьем, конечно же, будет выход с `--show-scons`текущим заводским филиалом. Я хотел бы разобраться в этом.

```
Nuitka:INFO: Starting Python compilation.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Scons command: C:\Users\andre\AppData\Local\Programs\Python\Python38\python.exe -W ignore C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\SITE-P~1\nuitka\build\INLINE~1\bin\scons.py -f C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\SITE-P~1\nuitka\build\BACKEN~1.SCO --jobs 8 --warn=no-deprecated --no-site-dir --debug=explain,stacktrace result_name=C:\Users\andre\TEST~1.DIS\test source_dir=. debug_mode=false python_debug=false unstripped_mode=false module_mode=false full_compat=false experimental= trace_mode=false python_version=3.8 target_arch=x86_64 python_prefix=C:\Users\andre\AppData\Local\Programs\Python\Python38 nuitka_src=C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\SITE-P~1\nuitka\build module_count=456 result_exe=C:\Users\andre\TEST~1.DIS\test.exe cache_mode=true standalone_mode=true frozen_modules=165 show_scons=true noelf_mode=true clang_mode=true
scons: Reading SConscript files ...
Scons: Tools= ['default']
Nuitka-Scons:INFO: Initial CC: 'cl'
Nuitka-Scons:INFO: Initial CCVERSION: None
Error, Visual Studio required for using ClangCL on Windows.
```

**Comment by Pro100rus32** [comment]
![image](https://user-images.githubusercontent.com/64806740/104205814-e402e580-543f-11eb-90ca-711abcb927bd.png)
Maybe this is the problem? I just have very little space on the system SSD (С:) and I installed it on another drive

**Comment by kayhayen** [comment]
@Pro100rus32 I wouldn't believe so, the IDE shouldn't contain the cl.exe, the other path is the default. Can you search where the `cl.exe` resides on your system? There might be multiple locations. Scons executes batch files it finds, and it wouldn't claim that cl is used initially if it didn't find it. Does it work without the `--clang` anyway?

**Comment by Pro100rus32** [comment]
> @Pro100rus32 I wouldn't believe so, the IDE shouldn't contain the cl.exe, the other path is the default. Can you search where the `cl.exe` resides on your system? There might be multiple locations. Scons executes batch files it finds, and it wouldn't claim that cl is used initially if it didn't find it. Does it work without the `--clang` anyway?

![image](https://user-images.githubusercontent.com/64806740/104209289-9176f880-5442-11eb-904b-9076414afe88.png)

**Comment by kayhayen** [comment]
Is this the only one, @Pro100rus32 ?

I have all of these:

c:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe
c:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x86/cl.exe
c:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx86/x64/cl.exe
c:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx86/x86/cl.exe

I assume that is about you having the non-community version then. Which edition is that on your side?

**Comment by Pro100rus32** [comment]
> Is this the only one, @Pro100rus32 ?
> 
> I have all of these:
> 
> c:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe
> c:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x86/cl.exe
> c:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx86/x64/cl.exe
> c:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx86/x86/cl.exe
> 
> I assume that is about you having the non-community version then. Which edition is that on your side?

![image](https://user-images.githubusercontent.com/64806740/104309847-da32be00-54e3-11eb-9572-80933cc1fd15.png)

**Comment by kayhayen** [comment]
Ok, then we have something like a mismatch there, you are uptodate as I am anyway, and for me the checkboxes seemed right, but it involved also guess work from my side due to my weak russian reading skills.

But I noticed when searching for "clang" in single components tab, it finds two things, one of which is called `clang-compiler for Windows` (in German though) and one is called `Clang-cl for v142-Buildtools (x64/x86)` and I only got the first one. I wonder where the real C++ compiler is hiding. I have `MSVC v142 - VS 2019 C++ v14.28` ticked and that is it for `C++`, the only other thing is `C++ core features` and `C++ profiling`, do you have the first one as well?

**Comment by Pro100rus32** [comment]
**I seem to have installed something wrong.**
![image](https://user-images.githubusercontent.com/64806740/104347940-3c0a1c80-5512-11eb-913c-576860629773.png)

 **I installed it and now everything works for me!**
![image](https://user-images.githubusercontent.com/64806740/104348130-66f47080-5512-11eb-8620-e5f2524a4558.png)

_**Thank you)**_

**Comment by Pro100rus32** [comment]
I just messed up)
![image](https://user-images.githubusercontent.com/64806740/104350922-c56f1e00-5515-11eb-9c38-eb0a3ed80d44.png)
