### ISSUE TITLE
System CPU Usage increased 4x between 0.6.8.4 and 0.6.10.5

### ISSUE THREAD

**Issue by levesquejf** [Nuitka/Nuitka#938]
I tried to upgrade from Nuitka `0.6.8.4` to `0.6.10.5` but I have a weird issue with CPU Usage. 

With both versions, the process is using around 4% of CPU (reported by `psutil.Process.cpu_percent()`) and that's ok. However, the system CPU Usage (reported by `psutil.cpu_percent()`) increased from 15% to 60% with `0.6.10.5`.

Also, I noticed it takes about 5-6 seconds the start my app (i.e. to have the initial stdout messages) with `0.6.10.5` compared to 1 sec with `0.6.8.4`.

The compiled binary is 37MB when compiled with `0.6.10.5` compared to 44MB with `0.6.8.4`.

I ran both builds with `strace -c` and the result is similar with both versions. 

Does it ring a bell to anyone? Any clue on how to troubleshoot this?

**Comment by kayhayen** [comment]
The constants loading code of 0.6.9 is entirely new and had a issue with slow startup that got fixed on develop, too invasive change, and is about to be released as 0.6.11.

No idea about system CPU though. Has the system maybe started swapping? I wouldn't think that's possible as a change from Nuitka, but maybe increased memory usage could do that.

**Comment by levesquejf** [comment]
There is a lot of free memory. It also happened on many systems (Linux arm and amd64) when I deployed the new binaries and it went back to normal after the rollback. Once I have the process running, any idea how I can troubleshoot?

For the startup issue, does the factory image have the fix so I can give it a try?

**Comment by kayhayen** [comment]
Go with develop @levesquejf and analyse only that, it's not released due to embarassing #940 which I am currently attempting to fix on factory, but it's not yet healthy again.

**Comment by kayhayen** [comment]
@levesquejf if your problem persists with 0.6.11 that would need a reproducer of some sorts, then I could git bisect it. 

Looking at things with perf could do the trick, https://perf.wiki.kernel.org/index.php/Main_Page and it would be useful to try perf annotate. Right now I am wondering though, if #940 is not causing non-obvious behavior differences, and it's a 0.6.10 regression for which I will have the fix shortly (undergoing final tests now).

**Comment by kayhayen** [comment]
@levesquejf can you try with 0.6.11.3 and let me know if this persisted?

**Comment by levesquejf** [comment]
I will as soon as 0.6.11.3 is available on Pypi. Except if you have another way to test it?

**Comment by kayhayen** [comment]
Wow, seems my CI rollout is broken, this isn't the first time it didn't trigger for a hotfix. Sorry about that. I don't monitor the automated stuff...

**Comment by levesquejf** [comment]
I am no longer able to compile for ARM. I have the following error. Looks like it's related to clang version (https://releases.llvm.org/5.0.0/tools/clang/docs/ThinLTO.html#basic).

`/usr/bin/ld: /usr/lib/llvm-3.8/bin/../lib/LLVMgold.so: error loading plugin: /usr/lib/llvm-3.8/bin/../lib/LLVMgold.so: cannot open shared object file: No such file or directory`. 

I am cross-compiling to arm using docker balena images (ex: `balenalib/raspberrypi4-64-python:3.8.3-stretch-build`). I don't have the issue with x86_64 which is using a custom image based on `debian:stretch`.

`--recurse-all` is no longer supported so I replaced it with `--follow-imports`.

Before I look deeper into clang, probably compiling from source, any advices @kayhayen? Any options I can use to avoid this error?

**Comment by kayhayen** [comment]
@levesquejf seems entirly unrelated to Nuitka. And that option was the old name, which has still supported, but got replaced a couple of releases ago.

**Comment by levesquejf** [comment]
In the same container image (`balenalib/raspberrypi4-64-python:3.8.3-stretch-build`), all tested with `--follow-imports` without `--recurse-all`. 

- `0.6.8.4`: working
- `0.6.10.5`: working
- `0.6.11`: is having the LLVMgold error
- `0.6.11.3`: is having the LLVMgold error

@kayhayen Any idea what could have introduced that between `0.6.10.5` and `0.6.11`?

**Comment by kayhayen** [comment]
@levesquejf so `--recurse-all` and `--follow-imports` were aliases, but making my life harder as some users were on one form, and some on the other, making it confusing to read bug reports sometimes to me. That as an aside.

You can compare the `--show-scons` output for the executed command. The only thing that could vaguely be related is that Nuitka is no longer calling `ccache` for linking, if it explicitely injects `ccache` into the command. That's because `ccache` is only going to pass through the command, but maybe that's what kept your clang setup working. But if there is any difference to be caused, it would happen there on that level.

Also you could attempt do a git bisect from 0.6.10.5 to 0.6.11 and find the commit that breaks it first. That would most definitely allow me to explain it.

**Comment by levesquejf** [comment]
@kayhayen With 0.6.11, it fails with:
```
(...)
scons: building `/opt/app/main.dist/main' because it doesn't exist
clang -o /opt/app/main.dist/main -flto -O3 -z noexecstack -Wl,-R,'$ORIGIN' -Wl,--disable-new-dtags @"./@link_input.txt" -L/usr/local/lib -ldl -lm -lpython3.8 -ldl -lpthread -lutil -lrt -lm
/usr/bin/ld: /usr/lib/llvm-3.8/bin/../lib/LLVMgold.so: error loading plugin: /usr/lib/llvm-3.8/bin/../lib/LLVMgold.so: cannot open shared object file: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [/opt/app/main.dist/main] Error 1
scons: internal stack trace:
  File "/root/.local/share/virtualenvs/app-ueEJiAOq/lib/python3.8/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Job.py", line 258, in run
    task.execute()
  File "/root/.local/share/virtualenvs/app-ueEJiAOq/lib/python3.8/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Script/Main.py", line 206, in execute
    SCons.Taskmaster.OutOfDateTask.execute(self)
  File "/root/.local/share/virtualenvs/app-ueEJiAOq/lib/python3.8/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Taskmaster.py", line 255, in execute
    self.targets[0].build()
  File "/root/.local/share/virtualenvs/app-ueEJiAOq/lib/python3.8/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Node/__init__.py", line 766, in build
    self.get_executor()(self, **kw)
  File "/root/.local/share/virtualenvs/app-ueEJiAOq/lib/python3.8/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Executor.py", line 397, in __call__
    return _do_execute_map[self._do_execute](self, target, kw)
  File "/root/.local/share/virtualenvs/app-ueEJiAOq/lib/python3.8/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Executor.py", line 131, in execute_action_list
    raise status    # TODO pylint E0702: raising int not allowed
scons: building terminated because of errors.
```

With 0.6.10.5, the last clang command looks like: 
```
clang -o /opt/app/main.dist/main -z noexecstack -Wl,-R,'$ORIGIN' -Wl,--disable-new-dtags -Wl,-b -Wl,binary -Wl,./__constants.bin -Wl,-b -Wl,elf64-littleaarch64 -Wl,-defsym -Wl,constant_bin=_binary_____constants_bin_start @"./@link_input.txt" -L/usr/local/lib -ldl -lm -lpython3.8 -ldl -lpthread -lutil -lrt -lm
```

Does it matter or it's normal? Thanks!

**Comment by kayhayen** [comment]
I think with last release, I fixed that --lto had no effect for clang (only worked for gcc), but obviously that needs another linker with clang, and your cross compile setup doesn't have that. Just drop the option --lto to restore same behaviour or get your clang to support LTO.

**Comment by levesquejf** [comment]
I removed the `--lto` option and everything is working with `0.6.11.5`. No delay on startup and no CPU increase. Thanks for your help @kayhayen.
