### ISSUE TITLE
nuitka gdcmswig module optimizations, INFO show  not finished with the module due to following change kinds 

### ISSUE THREAD

**Issue by wuwuyiyirong5** [Nuitka/Nuitka#939]
When I use nuitka package pydicom, but an issue happed:
Nuitka-Progress:INFO: Not finished with the module 'gdcmswig'  due to following change kinds:
new_builtin, new_builtin_ref, new_constant, new_expression, new_staements.
And the progress is stayed in this line long long time without breaking.
Could you give some suggestions to solve this problem? Waiting for your response. Thanks a lot.

**Comment by kayhayen** [comment]
Lacking all information this is just noise.
