### ISSUE TITLE
Cannot get pycryptodome module with ChaCha20 Cipher to work

### ISSUE THREAD

**Issue by Sn1cket** [Nuitka/Nuitka#941]
Hello Kay,

I am having issues compiling a python program that uses the ChaCha20 Cipher from the pycryptodome module as standalone.
It seems like the ChaCha20 cipher *.pyd file is  missing. When I manually copy the _chacha20.cp37-win_amd64.pyd file in the dist folder and rename it to _chacha20.pyd it works.

* _Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)_
0.6.10.5
Python: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
Executable: C:\Users\<Username>\.virtualenvs\pycryptodome_test-LRM0c8au\Scripts\python.exe
OS: Windows
Arch: x86_64

* _How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually._
I installed the pip Nuitka package in a pipenv virtual environment.
The Python installation is Python for Windows.

* _If possible please supply a [Short, Self Contained, Correct, Example]_
```
from Crypto.Cipher import ChaCha20
from Crypto.Random import get_random_bytes
key = get_random_bytes(32)
```

Compiled with the following line and getting no errors
```
python -m nuitka --standalone .\pycryptodome_test.py
```

Best regards!

**Comment by kayhayen** [comment]
I made this into 0.6.11 as a kind of last minute addition.
