### ISSUE TITLE
Unable to run PyQt6 app because no Qt platform plugin

### ISSUE THREAD

**Issue by hashuser** [Nuitka/Nuitka#944]
I've tried compiling a PyQt6 app using Nuitka 0.6.10.5, but the resulting executable raises an exception due to being unable to find Qt platform plugin. **PyQt5 doesn't have such issue.**

Platform: Windows
Python: 3.8.7 (x64)
Nuitka: 0.6.10.5

**Compiler command:**
`
nuitka --mingw64  --windows-disable-console --standalone --show-progress --plugin-enable=qt-plugins --plugin-enable=multiprocessing --include-package=dns --output-dir=C:\Users\home\Desktop\1 C:\Users\home\PycharmProjects\QYashmak\venv\project\Yashmak.py
`

**CMD output when executing the resulting executable (windows console enabled):**
`
C:\Users\home\Desktop\1\Yashmak.dist>C:\Users\home\Desktop\1\Yashmak.dist\Yashmak.exe
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
`

![2021-01-23 105038](https://user-images.githubusercontent.com/60065064/105567286-082dc300-5d6c-11eb-9398-17913f91fee6.png)

**Comment by kayhayen** [comment]
Ok, PyQt6 is new to me, the qt plugin probably needs some help there.

**Comment by Noir-** [comment]
@kayhayen can you roughly tell what's going wrong here? At the moment it seems like there's no working stand-alone distribution method for Qt6 Python applications. I'd love to use Nuitka because it produces the smallest results :)

**Comment by kayhayen** [comment]
I am currently busy with priority tickets from https://nuitka.net/pages/commercial.html but I am sure I will eventually get there, unless of course somebody buys priority there and asks me to do it. Obviously it's going to happen eventually, just because Qt6 is way too important, isn't it.

**Comment by Noir-** [comment]
Unfortunately, paying (250€) for priority is not a real option for me because I'm developing an Open Source application but with a certain time constraint. I'll have a look into the Qt plugin...

**Comment by Noir-** [comment]
I tried this again after reading that there's a Pyside6 plugin now. After manually deleting some Qt3D related files to workaround #1013 I ended up with the same error.

Compile command:
```
PYTHONPATH=src python -m nuitka ./debug.py --follow-imports --onefile --plugin-enable=pyside6 --include-qt-plugins=qml --linux-onefile-icon=./src/oxionecompanion/resources/oxionecompanion.xpm
```
Error when running the AppImage
```
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

**Comment by kayhayen** [comment]
@Noir- I fixed a bunch of issues related to the Qt plugin on Linux on the factory branch, so I recommend using that. But if you do not include "platform" plugin, no surprise, it is not found. The typical value there is `sensible,qml`. One day Nuitka will hopefully detect usage of `QtQuick` and make this automatic, but I am still busy to repair other things.

**Comment by kayhayen** [comment]
As for `PyQt6`, the focus is currently on `PySide6`, I might look at it later, but for now this is invalid.

**Comment by boldrack** [comment]
Hi @kayhayen , Does this issue also affects Qt5 ?

**Comment by kayhayen** [comment]
On factory branch there is now an experimental PyQt6 plugin, and PyQt5 plugin has been repaired. However, the recommendation is to got with PySide2 or PySide6 if you can.

**Comment by kayhayen** [comment]
The plugin has no detector, make sure to do use `--enable-plugin=pyqt6` and check help output for its options.

**Comment by kayhayen** [comment]
This is on develop now and will be part of the next release, no feedback so far though.

**Comment by kayhayen** [comment]
This is part of the 0.6.18 release.
