### ISSUE TITLE
matplotlib import problems

### ISSUE THREAD

**Issue by brev-dev** [Nuitka/Nuitka#947]
I don't think this is a duplicate of #943, although similar things are affected, so I'm not sure.
With a standalone compilation which includes matplotlib, the mpl-data directory is being found by nuitka, but copied to [name].dist/, rather than [name].dist/matplotlib/. When I first run my output .exe it therefore complains:
`RuntimeError: Could not find the matplotlib data files`

If I move mpl-data into matplotlib, I receive a different stream of errors concerning the format of mpl-data/matplotlibrc, which appears to have been somehow altered or corrupted. For things to work correctly, I need to copy-over an original matplotlibrc file from my python installation.

Platform: Windows (pip)
Python: 3.7.8 (AMD64)
Nuitka==0.6.11
numpy==1.19.5
matplotlib==3.3.3

Example code:
```
import matplotlib
print('Hello world')
```

Compiler command:
`python -m nuitka --standalone --mingw64 --show-progress --show-scons --plugin-enable=numpy bug_test.py
`
Examples of the original and "corrupt" matplotlibrc files are below. Something's happened to the blank lines / linefeeds? The multiple errors are of the form:
`Missing colon in file WindowsPath('matplotlibrc'), line 245 (' new century schoolbook, bookman, times, palatino,')`
and
```
Bad key are supported through the usual rc parameter settings in file matplotlibrc, line 244 (' are supported through the usual rc parameter settings:')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.3/matplotlibrc.template
or from the matplotlib source distribution
```

[matplotlibrc_corrupt.txt](https://github.com/Nuitka/Nuitka/files/5862662/matplotlibrc_corrupt.txt)
[matplotlibrc_original.txt](https://github.com/Nuitka/Nuitka/files/5862663/matplotlibrc_original.txt)

**Comment by kayhayen** [comment]
This is actually part of the hotfix 0.6.11.1 that is coming very soon, and is a duplicate yes. The config file format was also changed again. Currently it's good on factory branch.
