### ISSUE TITLE
[Question] Accelerating the compile on a strong machine

### ISSUE THREAD

**Issue by chwba** [Nuitka/Nuitka#951]
Are there any args I can pass to accelerate the compile, to have it use more cores for instance on a 16 or 32 core machine with a lot of ram?

**Comment by kayhayen** [comment]
For the C backend compilation, all cores are used. Ironically for Python frontend compilation, it will only work after caching is implemented, so save and load works, and with that, we could split out the work on modules.

So while this is definitely on the agenda, the caching from and to XML will need a lot of work to be working and trusted, which is a shame, but there is only so much development power invested into Nuitka.

**Comment by kayhayen** [comment]
Closing, as questions are closed, obviously the prong of action to get to caching working will be followed and maybe one day this answer gets an update. BTW: The progress bar on develop version will at least keep you informed.
