### ISSUE TITLE
0.6.11 and above failed to compile some 3rd party modules

### ISSUE THREAD

**Issue by hashuser** [Nuitka/Nuitka#953]
Since PyQt6 couldn't be compiled by nuitka, I tried to switch back to PyQt5 and I met some serious problems after I upgraded the nuitka from 0.6.10.5 to 0.6.11 and 0.6.11.1, and when I again switched back to 0.6.10.5, it worked fine.

Platform: Windows
Python: 3.8.7 (x64)
Nuitka: 0.6.11 and 0.6.11.1
3rd Party Modules: PyQt5, dnspython3, pywin32

**Compiler command:**
`
nuitka --mingw64  --windows-disable-console --standalone --show-progress --plugin-enable=qt-plugins --plugin-enable=multiprocessing --include-package=dns --output-dir=C:\Users\home\Desktop\2 C:\Users\home\PycharmProjects\QYashmak\venv\project\local.py
`

**CMD output:**
`
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
ccache: error: execv of C:\Program failed: No error
ccache: error: execv of C:\Program failed: No error
ccache: error: execv of C:\Program failed: No error
ccache: error: execv of C:\Program failed: No error
ccache: error: execv of C:\Program failed: No error
ccache: error: execv of C:\Program failed: No error
ccache: error: execv of C:\Program failed: No error
ccache: error: execv of C:\Program failed: No error
ccache: error: execv of C:\Program failed: No error
ccache: error: execv of C:\Program failed: No error
ccache: error: execv of C:\Program failed: No error
ccache: error: execv of C:\Program failed: No error
ccache: error: execv of C:\Program failed: No error
ccache: error: execv of C:\Program failed: No error
scons: *** [__constants.o] Error 1
scons: *** [__helpers.o] Error 1
scons: *** [__loader.o] Error 1
scons: *** [module.PyQt5-preLoad.o] Error 1
scons: *** [module.PyQt5.QtCore-postLoad.o] Error 1
scons: *** [module.PyQt5.o] Error 1
scons: *** [module.__main__.o] Error 1
scons: *** [module.__parents_main__.o] Error 1
scons: *** [module.dns._compat.o] Error 1
scons: *** [module.dns.o] Error 1
scons: *** [module.dns.dnssec.o] Error 1
scons: *** [module.dns.e164.o] Error 1
scons: *** [module.dns.edns.o] Error 1
scons: *** [module.dns.entropy.o] Error 1
ccache: error: execv of C:\Program failed: No error
scons: *** [module.dns.exception.o] Error 1
ccache: error: execv of C:\Program failed: No error
scons: *** [module.dns.flags.o] Error 1
`

![2021-01-26 115508](https://user-images.githubusercontent.com/60065064/105798562-69080600-5fcd-11eb-8a8f-87df839bed72.png)

**Comment by kayhayen** [comment]
It seems spaces in the gcc path are not handled well when executing `ccache.exe`, but just don't have them. However as a bug, this seems real and needs fixing. Previously we provided the gcc to ccache by changing PATH, but that's not reliable, so we pass it on the command line now, but obviously it needs some sort of quoting then.

**Comment by kayhayen** [comment]
I directly fixed this into the latest pre-release. For PyQt6 I need more time to get that sorted out, esp. as I would like to also include PySide2 at the same time.

**Comment by kayhayen** [comment]
I included this in 0.6.11.3 hotfix as well.
