### ISSUE TITLE
__file__ returns a wrong file name

### ISSUE THREAD

**Issue by hashuser** [Nuitka/Nuitka#956]
In my code, I tried to get the file name of itself in two different approaches, and they both worked fine in PyCharm. After I compiled the code by using nuitka 0.6.10.5 (I didn't try the pre-release), and the result showed  `__file__`  method didn't work properly.

Platform: Windows
Python: 3.8.7 (x64)
Nuitka: 0.6.10.5

**My test code:**
```python
import sys

if __name__ == '__main__':
    print(__file__)
    print(sys.argv[0])
```

**Compiler command:**
`
nuitka --mingw64  --standalone --show-progress --output-dir=C:\Users\home\Desktop\1 C:\Users\home\PycharmProjects\QYashmak\venv\project\test7.py
`

**CMD output when executing the resulting executable (windows console enabled):**
![2021-01-27 154153](https://user-images.githubusercontent.com/60065064/105958989-4a316e80-60b6-11eb-9afb-efc74c1fef1e.png)
![2021-01-27 154221](https://user-images.githubusercontent.com/60065064/105958993-4bfb3200-60b6-11eb-80e5-ad57ec07b602.png)

**Comment by kayhayen** [comment]
You didn't try it yes, and you didn't even use the latest release. 

However, what makes you think these are wrong, they are correct. One is the short path of the file, one is the long path, these are identical presumably. They help with compatibility on Windows systems. I honestly forget why, but even Python3 doesn't properly deal with unicode paths, at least not on Windows. And I don't want to remember, there was too much suffering involved. :)

**Comment by kayhayen** [comment]
Or, well is the complaint, that `__file__` is fixed? It's not derived from `sys.argv[0]`, but from the Python filename, which is what the Python spec says. If you want to rename the final product, you do it on the Python level. If you want to know how you have been called, you use `sys.argv[0]` I guess.
