### ISSUE TITLE
Move odict and oset code to build/inline_copy/

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#967]
Currently there are quite a few unconditional uses of `nuitka.containers.odict`.

```py
Builtins.py:from nuitka.containers.odict import OrderedDict
build/inline_copy/lib/scons-2.3.2/SCons/Executor.py:        for odict in self.overridelist:
build/inline_copy/lib/scons-2.3.2/SCons/Executor.py:            overrides.update(odict)
build/inline_copy/lib/scons-3.1.2/SCons/Executor.py:        for odict in self.overridelist:
build/inline_copy/lib/scons-3.1.2/SCons/Executor.py:            overrides.update(odict)
codegen/Reports.py:from nuitka.containers.odict import OrderedDict
containers/odict.py:It is not in 2.6, for this version we are using the odict.py as mentioned in the
freezer/Standalone.py:from nuitka.containers.odict import OrderedDict
nodes/LocalsScopes.py:from nuitka.containers.odict import OrderedDict
plugins/Plugins.py:from nuitka.containers.odict import OrderedDict
```
oset.py is similar.

On Python 2.7+, the code in `nuitka.containers.odict` is ignored, except for imports from stdlib/builtins.

As this module is under the "Python-2.0" SPDX license, and rightly has no Apache-2.0 header, it is desirable to not include it in distro packages unless necessary.  Its inclusion means the Nuitka package should use "License: Apache-2.0 AND Python-2.0" which is likely unnecessarily complications and confusion to wary users.

It can still be in the source tree, ideally under `build/inline_copy`, so it is easier to remove it.

The oset code should also be moved into build/inline_copy/ .  It might be possible to inline https://pypi.org/project/oset/ , thereby making it easier to patch in the python package if present. That packages repo has disappeared - need to check its other metadata to see if it appropriately credits the original authors.  (its setup.py uses `maintainer=...` but not `author=..`.  http://code.activestate.com/recipes/576694/ is MIT.  Now we need "License: Apache-2.0 AND Python-2.0 AND MIT".  Ugh.

And I notice inside oset.py
```py
# Note: Kay Hayen did some changes for Nuitka keeping this license. These
# changes are not improvements, use the original source instead, not this
# file.
```

Another alternative is to use one of the many other better-maintained [ordered set libraries](https://pypi.org/search/?q=ordered+set).

I'm about to do a build with the following so that I dont need to change the `License:...`
```sh
echo 'from collections import OrderedDict' > nuitka/containers/odict.py
echo 'from ordered_set import OrderedSet' > nuitka/containers/oset.py
```
I expect this to break .. ;-)

A code search reveals to other licenses in use
```
build/include/nuitka/hedley.h: * SPDX-License-Identifier: CC0-1.0
build/include/nuitka/incbin.h:For more information, please refer to <http://unlicense.org/>
```

Those files also have the Apache-2.0 header, so are being dual-licensed as Apache-2.0, and that is legally sound and appropriate to do in this case, and means these two files are not problematic.

Are there any other bits of inlined code in the codebase?

**Comment by kayhayen** [comment]
Checkout debian/copyright, everything ought to be listed there.

As for inline copies, originally the idea was that these would be used if there, or from the system. In some instances, scons and clcache on Windows to give examples, that is not even possible. For Scons on Linux, we have patches in their to save performances by not loading D, Fortran, tools in scons, that take up time. But there are other instances, where they are entirely meant to be optional, e.g. appdirs and friends.

For Debian packaging, inline copies are all nuked, as they disallow including packaged stuff. For RPM, it's selectively preserving used scons inline copies. Therefore things required to be there are not there, as they technically are not inline copies, with me not being aware of any packaging for these components.

As for ordered sets, this is a mess. I am still waiting for CPython to include them I guess. I really don't want to deal with trying out the others. I felt Raymond made a good `O(1)` performing one for all but iteration, but I also avoid these ordered sets if I can.

BTW: My intention is not to put these under any other license than what their currently are in. So I don't think I am dual licensing really. All the licenses are compatible, from public domain to BSD, if I am not mistaken.

Interestingly the license text I used is no longer on the site where I got it from, making my copy of oset special in that it is not under PSF license. That said, it would be compatible too. If asked by the original copyright holder, I would also follow the license change, but it's not clear it was actually him doing it.

If you wanted single license packages, you could make oset its own RPM I guess, but I don't think it matters much. For as long as the licenses are compatible, I see no issue. Specifically right now there is no license that is granting less permissions then Apache 2.0 does, so stating the whole things is "Apache 2" licensed would only leave out rights, not overstate them.

**Comment by jayvdb** [comment]
> so stating the whole things is "Apache 2" licensed would only leave out rights, not overstate them.

yes.  Nuitka is not doing anything wrong here even by stating simplify it as "Apache 2".

But adding the Apache-2.0 header on those two .h files, that is dual licensing them, which has no practical implications unless someone wants to modify those files, and you want to merge and re-send the changes upstream.  They are quite irrelevant for this issue. I only mention them to exclude them, and ask if there are any others that I havent yet found.

For openSUSE, the .spec also nukes all of the `build/inline_copy`, and I will soon be nuking oset and odict.  They have a policy of not allowing vendored code, which I try to follow even though I know of many cases where it isnt being done.

For oset, I'll find a package containing an `OrderedSet` which passes all the tests, maybe even try a few and note the results here (and I'll check the O for them), and I'll submit a PR to use it if present, and fallback to the inline code.  You can decide then, when reviewing, whether it is worth accepting or not.
The build with `echo 'from ordered_set import OrderedSet' > nuitka/containers/oset.py` is chugging along quite nicely so far.

**Comment by kayhayen** [comment]
I didn't mean to add licenses to these files, maybe I did by accident. Specifically I don't want to even come close to claiming copyright for it, as they now do. I think for incbin and hedley being header files only, packaging will be interesting. :)

I would very much welcome such a PR of yours, definitely. I think in terms of API there is not a lot being asked of ordered sets, so things will likely be compatible more or less. I think I had to add a few missing methods though, but maybe real implementations more completely implent the supposed collection interface.

**Comment by kayhayen** [comment]
I removed the accidental dual licencse of hedley on factory branch. Thanks for making me aware, these things are not easily recognized as mistaken as they could also be my intention, but definitely not. I take licensing stuff very serious.

**Comment by jayvdb** [comment]
Dual-licensing the header files, while it could be seen as claiming copyright, is actually the reason why "Apache-2.0" is ok.  If you were to remove those headers, my IANAL gut feeling is we start getting into murky territory.  The authorship is clear in the source, so in reality there is no claiming of authorship happening.  Maybe a thank you note in the README might be warranted, and would alert more users, with better legal teams, and we may get better verdict on what needs to be done, if anything.

**Comment by kayhayen** [comment]
Well, I do claim it with `

```
//     Copyright 2021, Kay Hayen, mailto:kay.hayen@gmail.com
//
//     Part of "Nuitka", an optimizing Python compiler that is compatible and
//     integrates with CPython, but also works on its own.

```

That first line is the most wrong part in my mind. I do not claim any copyright on it at all.

And then attaching Apache 2 license is also wrong, because it means, people couldn't remove it, that's one of the things it disallows. Instead now they can take it as the public domain it is. Arguably Nuitka inline copies will always be the wrong place to take anything from, but I did e.g. add a feature to incbin that may or may not end up in a PR, and I do want to re-license code under the license I received it.

The Apache, BSD, etc. licenses normally need no legal team involvements, so I don't care. For me this is more about my intent of leaving foreign code untouched. It's not like I would upload anybody's work on PyPI and change the license just because I can. It would be my right. But then there is plenty of things that I have a right to do that are wrong. :)

Yours,
Kay

**Comment by jayvdb** [comment]
https://pypi.org/project/ordered-set/ passed all of the test suite.  I guess that is sufficient to use it.  If you are aware of the parts of Nuitka using oset which dont have test coverage, I should manually test them.

**Comment by kayhayen** [comment]
If you use  `https://pypi.org/project/orderedset/` that is actually the code that Nuitka uses, but seemingly maintained. I will compare it and let you know about it. They have the code under BSD license as I do btw, the other one with PSF just seems to be an off beat upload of somebody.

**Comment by kayhayen** [comment]
The first one, does the wrong trade of, citing their desc:

```
Hettiger's implementation kept its content in a doubly-linked list referenced by a dict. As a result, looking up an item by its index was an O(N) operation, while deletion was O(1).

This version makes different trade-offs for the sake of efficient lookups. Its content is a standard Python list instead of a doubly-linked list. This provides O(1) lookups by index at the expense of O(N) deletion, as well as slightly faster iteration.
```

Since I am doing deletions, I highly disapprove of that.

The second one is using Cython, which I approve of and is Python2 compatible as well, which is something I need. I would welcome a PR that makes optional use of it. It might make some things in Nuitka compile time faster.

**Comment by jayvdb** [comment]
Just noting that the second one is not packaged for many distros or OS https://repology.org/project/python:orderedset/versions , while https://repology.org/project/python:ordered-set/versions is broadly packaged.

Boltons also has very high existing packages: https://repology.org/project/python:boltons/versions . It looks to be a bit more efficient for removals compared to ordered-set, until it reaches a hard-coded threshold of [384](https://github.com/mahmoud/boltons/blob/master/boltons/setutils.py#L122) for compaction, or the adjustable `_COMPACTION_FACTOR`.

I remember `sortedcollections` being quite good; if so I suspect I can get `.update()` added.

**Comment by kayhayen** [comment]
I am fine with Boltons too, being packaged is indeed a good criterion, I could change my Debian package towards boltons too, where the first ones really only cover Fedoras and maybe Arch. It also seems to have a nice amount of other stuff that I could look into for my tooling side.

Having to add a method to a Python3 only code, nah, esp. as not having `update` is a real let down.

**Comment by kayhayen** [comment]
The license duplication was removed and is now on develop. Any progress on this for a PR?

**Comment by kayhayen** [comment]
I release the part of the license hickup by releasing it as part of 0.6.12, I guess the issue remains.

**Comment by kayhayen** [comment]
I am going to do `from orderedset import OrderedSet` in next Nuitka releases. I noticed some severe performance issues related to merging of many exception branches in Nuitka, and it part of is related to the use of pure Python set code that is optimized for deletion, yes, but in those cases, they are only built up. A five times speed up won't hurt in these cases.

I will strive to rather use `set` and sort later where possible now as well. In the problematic cases, where there is a lot of interaction with the set object, and only a single (iterative) use, where determism is more the goal than real order, this will be much more clever.

**Comment by jayvdb** [comment]
IIUC, you have a specific implementation in mind, so I've re-assigned it to you.

**Comment by kayhayen** [comment]
I will close this on release, as I don't care about the unused oset and odict files, if they both become unused. Right now, only on Python 2.6 it's necessary to have the oset code, but I don't want to make Nuitka depend on it, as packaging would become only harder in my mine.

**Comment by kayhayen** [comment]
Part of the 0.6.14 release.
