### ISSUE TITLE
 I have no idea with this problem，want anybody help. nuitka failed，even the  very simple python code.

### ISSUE THREAD

**Issue by jiuyuanlvbu** [Nuitka/Nuitka#968]
### I have no idea with this problem，want anybody help. nuitka failed，even the  very simple python code.

environment：
_C:\Users\admin>python
Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

C:\Users\admin>gcc.exe --version
gcc.exe (x86_64-win32-seh-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

C:\Users\admin>nuitka --version
0.6.11.3
Python: 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Users\admin\AppData\Local\Programs\Python\Python37\python.exe
OS: Windows
Arch: x86_64_

---
python code:
`def talk(message):
    return "Talk " + message

def main():
    print( talk("Hello World"))

if __name__ == "__main__":
    main()`

---
and then what happend:

C:\Users\admin\Desktop\work\newfortest>nuitka hello.py
Nuitka:INFO: Starting Python compilation.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
ccache: error: execv of C:\Program failed: No error
ccache: error: execv of C:\Program failed: No error
ccache: error: execv of C:\Program failed: No error
ccache: error: execv of C:\Program failed: No error
scons: *** [__constants.o] Error 1
scons: *** [__helpers.o] Error 1
scons: *** [__loader.o] Error 1
scons: *** [module.__main__.o] Error 1
ccache: error: execv of C:\Program failed: No error
scons: *** [static_src\MainProgram.o] Error 1
ccache: error: execv of C:\Program failed: No error
scons: *** [static_src\CompiledCellType.o] Error 1

---

help wanted,thx.

**Comment by kayhayen** [comment]
That is something that got fixed in a recent hotfix 0.6.11.4, a space in the gcc path.

**Comment by jiuyuanlvbu** [comment]
got it.
looking forward to that.&nbsp;

---Original---
