### ISSUE TITLE
i want pack my little tool,but never done it ,plZ HAVA A LOOK

### ISSUE THREAD

**Issue by goslion** [Nuitka/Nuitka#979]
args:
python -m nuitka --follow-imports --show-progress --show-scons --warn-unusual-code --windows-disable-console --plugin-enable=qt-plugins --windows-dependency-tool=pefile --experimental=use_pefile_recurse --experimental=use_pefile_fullrecurse --standalone --mingw64 pickiller.py > nuitka.log

There was no problem in the process, but I made a mistake at the end. I don't know what happened. Please have a look. I've never succeeded

The last useful information is this:
Nuitka-Scons:INFO: Compiled 623 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 620
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 3
FATAL: Failed to update resources, the result is unusable.

I don't know if it's my problem, but I can't find any other solution

**Comment by kayhayen** [comment]
You didn't fill the issue template.

**Comment by LeonardoRick** [comment]
This error happen with me but not all the time

**Comment by kayhayen** [comment]
@LeonardoRick the issue is closed, create a new one with better information.
