### ISSUE TITLE
[QUESTION] pass --onefile after folder manipulation?

### ISSUE THREAD

**Issue by LeonardoRick** [Nuitka/Nuitka#981]
I was having this error: `assertion failed: pem_root_certs != nullptr` and searching I found that a solution was to copy `root.pem` to the exactly structure needed shown on the error. So far, my script is like that:

```
python -m nuitka --standalone --plugin-enable=numpy --plugin-enable=pylint-warnings --include-package=urllib3 --include-package-data --mingw64 iqbotrealtime/main.py
mkdir -p main.dist/grpc/_cython/_credentials
cp ~/AppData/Roaming/Python/Python38/site-packages/grpc/_cython/_credentials/roots.pem  main.dist/grpc/_cython/_credentials/
mkdir -p main.dist/tlgdb/local
```

I also need to create a folder called tlgdb inside the generated dist.

So far, everything is working just fine. The problem is that I was wanting to generate one file to distribute the application  and I can't generate the file before manipulating the dist. Is there a way to do that?

```
0.6.12
Python: 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]
Executable: C:\Program Files\Python38\python.exe
OS: Windows
Arch: x86_64
```
installed nuitka via `python -m pip install nuitka` and not using `virtualenv`

**Comment by kayhayen** [comment]
There are option for including data files, these should work for this just fine. To create empty folders, currently a file needs to be placed there.

What I would like to see for these cases though, is an issue raised with these things, so I can make the data files plugin of Nuitka hard code things that are unavoidable, so that not every user of grpc and tlgdb has to do that. Given a minimal reproducer would be nice. The grpc thing seems obvious, what is `tlgdb`, also a package that wants to look at files?

**Comment by LeonardoRick** [comment]
Since apparently the error `assertion failed: pem_root_certs != nullptr` was not happening with anyone in this library I tried to google and I found some people receiving this error when using `Google Could API`. In my case I'm using ``firebase_admin` on my project so I'm almost 100% that its related and it goes something like this: 

```
import firebase_admin
from firebase_admin import firestore, db
from firebase_admin import credentials

cred =  'mysecret.json'
firebase_admin.initialize_app(cred, {
    'databaseURL': https://<my_simple_project_id_on_firebase>.firebaseio.com',
    'databaseAuthVariableOverride': {
        'uid': uid
    }
})
```

Let me know if you could not reproduce, I'll try to make a small project here too so I can share It.

The `tlgdb` is a folder I create my self on the root folder of my project and it looks like this:

root.
│ ── mypackage/
│               │── tlgdb/
│               │── main.py
│ setup.py

**Comment by kayhayen** [comment]
Going to look at that folder of `grpc` and definitely add the certificate as a known data file. Not large, but I think users will hardly want to figure it out. 

I think data file options want paths relative to the distribution folder, so the `main.dist` should not be there. I don't think the cheking of the option warns about that, but I guess it ought to.

**Comment by LeonardoRick** [comment]
Don't know why but this is not working:

`--include-data-file=$HOME/AppData/Roaming/Python/Python38/site-packages/grpc/_cython/_credentials/roots.pem=grpc/_cython/_credentials/`

And this is working perfectly:
`--include-data-file=$HOME/AppData/Roaming/Python/Python38/site-packages/iqbotrealtime/tlgdb/local/__init__.py=tlgdb/local/`

**Comment by LeonardoRick** [comment]
I tried to change `$HOME` to `~` and not working yet

**Comment by LeonardoRick** [comment]
I don't think this should be closed since the error persists.

**Comment by kayhayen** [comment]
This is a question that was answered. If you find issues with the options, please raise separate issues with reproducers.

**Comment by LeonardoRick** [comment]
Just for the record, I manage to make the command working just by changing the order of the parameters. This one worked perfectly:  

`python -m nuitka --standalone --plugin-enable=numpy --plugin-enable=pylint-warnings --include-package=urllib3 --include-package-data --mingw64 iqbotrealtime/main.py --include-data-file=$HOME/AppData/Roaming/Python/Python38/site-packages/grpc/_cython/_credentials/roots.pem=grpc/_cython/_credentials/ --include-data-file=$HOME/AppData/Roaming/Python/Python38/site-packages/iqbotrealtime/tlgdb/local/__init__.py=tlgdb/local/`

thanks a lot for helping!
