### ISSUE TITLE
Some parameters cause nuitka failed to analysis dependencies

### ISSUE THREAD

**Issue by hashuser** [Nuitka/Nuitka#984]
`--windows-file-version=`; `--windows-product-version=` ;`--windows-product-name=`;`--windows-company-name=`
I've found these four parameters cause nuitka failed to analysis dependencies, and by the way the new progress bar in 0.6.13rc2 seems not function properly.

Platform: Windows
CPU: Ryzen7 1700
RAM: DDR4-3200*2
Python: 3.8.7 (x64)
Nuitka: 0.6.13rc2

**Compiler command:**
`nuitka --mingw64  --windows-disable-console --standalone --show-progress --windows-file-version=0337 --plugin-enable=qt-plugins --plugin-enable=multiprocessing --include-package=dns --output-dir=C:\Users\home\Desktop\1 C:\Users\home\PycharmProjects\QYashmak\venv\project\Yashmak.py
`

![2021-02-13 212636](https://user-images.githubusercontent.com/60065064/107851082-31f57980-6e42-11eb-95d3-896b0ac9d13d.png)

![demo](https://user-images.githubusercontent.com/60065064/107851049-d4f9c380-6e41-11eb-9166-8a60e1463b2c.gif)

**Comment by kayhayen** [comment]
The `--show-progress` is supposed to disable the progress bar, and I think I might have fixed that recently, but it may only be on factory yet. It's the old style, which everybody uses, but it's actually only good for debugging now. I think even the stable release might be affected, which is why I have this on the hotfix too.

**Comment by kayhayen** [comment]
And your bug, is that you are providing empty strings for options, which is not really allowed. I am going to enhance the checks against this.

**Comment by kayhayen** [comment]
I pushed to factory enhanced checks on company name, product name and version. These should catch the kind of mistake I am claiming to have happened here. https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
Part of 0.6.12.2 hotfix release.
