### ISSUE TITLE
What does the pylint-warnings plugin do?

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#987]
The test logs show `plugin_enable:pylint-warnings` even if pylint is not installed.

Also, just an aside, I've found it a bit odd that I havent seen any difference in the logs when pylint is available.  That makes me wonder if it isnt working for some reason.

**Comment by kayhayen** [comment]
This plugin checks the source code for pylint formatted comments and makes use of them inside of Nuitka. It would e.g. cause Nuitka to not warn about code that pylint has been told to not warn about. It doesn't use pylint at all.
