### ISSUE TITLE
NameError: name 'quit' is not defined 

### ISSUE THREAD

**Issue by LeonardoRick** [Nuitka/Nuitka#988]
I really need to use `quit()` instead of `sys.exit()` because I'm finishing a thread. But even a trivial code with quit() command do not work.

This code
```
print('hello world')
quit()

```

Throws this error:
```
hello world
Traceback (most recent call last):
  File "C:\Users\leona\iq\TESTE~1.DIS\teste.py", line 2, in <module>
NameError: name 'quit' is not defined
```
this command:
`python -m nuitka --standalone --include-package=urllib3 --plugin-enable=pylint-warnings --include-package-data --mingw64 teste.py
`

python -m nuitka --version

```
0.6.12
Python: 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]
Executable: C:\Program Files\Python38\python.exe
OS: Windows
Arch: x86_64
```
installed nuitka via `python -m pip install nuitka` and not using `virtualenv`

**Comment by kayhayen** [comment]
You didn't provide the command line used.

**Comment by LeonardoRick** [comment]
I think I missunderstood some concepts. [This stack](https://stackoverflow.com/questions/19747371/python-exit-commands-why-so-many-and-when-should-each-be-used#:~:text=The%20functions*%20quit()%20%2C%20exit,the%20site%20module%20is%20imported.) quotes: 

> Nevertheless, quit should not be used in production code. This is because it only works if the site module is loaded. Instead, this function should only be used in the interpreter 

So maybe the `site`  module is never packed since it's just for development purpose.

I think `sys.exit()` should work just fine inside threads to finish them.

**Comment by kayhayen** [comment]
Well, I thought you might be using `--python-flag=no_site` in which case the behviour would be expected. Otherwise it's a compatibility bug.
