### ISSUE TITLE
fuse 3 support

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#989]
onefile tests fail when libfuse3 is available.  CI appears to test against libfuse2

The error suggests any version is acceptable:

> Error, the fuse library (libfuse.so.x) must be installed for onefile to work on Linux

**Comment by kayhayen** [comment]
I will improve it, however, `libfuse3.so.x` doesn't match that name, does it?

**Comment by kayhayen** [comment]
This reads now ```
        postprocessing_logger.sysexit(
            """\
Error, the fuse library (libfuse.so.x from fuse2, *not* fuse3) must be installed
for onefile creation to work on Linux."""
        )
```
