### ISSUE TITLE
Disable onefile tests if appimagetool not available and stdin is not a tty

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#990]
If appimagetool is not available, on OBS offline build workers I get
```py
[ 4668s] +Traceback (most recent call last):
[ 4668s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.12.1/nuitka/__main__.py", line 209, in <module>
[ 4668s] +    main()
[ 4668s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.12.1/nuitka/__main__.py", line 195, in main
[ 4668s] +    MainControl.main()
[ 4668s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.12.1/nuitka/MainControl.py", line 756, in main
[ 4668s] +    packDistFolderToOnefile(dist_dir, binary_filename)
[ 4668s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.12.1/nuitka/freezer/Onefile.py", line 56, in packDistFolderToOnefile
[ 4668s] +    packDistFolderToOnefileLinux(onefile_output_filename, dist_dir, binary_filename)
[ 4668s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.12.1/nuitka/freezer/Onefile.py", line 148, in packDistFolderToOnefileLinux
[ 4668s] +    getAppImageToolPath(),
[ 4668s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.12.1/nuitka/freezer/Onefile.py", line 79, in getAppImageToolPath
[ 4668s] +    return getCachedDownload(
[ 4668s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.12.1/nuitka/utils/Download.py", line 82, in getCachedDownload
[ 4668s] +    reply = raw_input()
[ 4668s] +EOFError: EOF when reading a line
```

**Comment by kayhayen** [comment]
I have added --skip-onefile-tests in my RPM spec file for this reason. Detecting the availability of the tool in the test runner would be an option too indeed. I am going to remove it and try to implement this more automatically.

Also I see an issue here, with `raw_input()` not simply treating stdin unavailability with a default reply "no", that's more accurate, in which case however, it would error exit right now, as a "no" is not acceptable.

**Comment by kayhayen** [comment]
Btw, I dislike checking on tty, as I like programs like `yes` being usable for answering questions.

**Comment by kayhayen** [comment]
Both the EOF handling and the detection in the test runner are on current factory branch https://nuitka.net/doc/factory.html and will be in the hotfix, if my OBS tests pass with that now. I also removed the skip from the Debian packaging, always a good sign if there is no need to replicate this in many places.

**Comment by kayhayen** [comment]
Part of 0.6.12.2 hotfix release.

**Comment by jayvdb** [comment]
I've pre-installed appimagetool, and it isnt being found.  This question is still coming up.

**Comment by kayhayen** [comment]
The preinstalled tool is not used of course, and this is what it does for me:

> [ 1377s] Nuitka will make use of AppImage (https://appimage.org/) tool
> [ 1377s] to combine Nuitka dist folder to onefile binary.
> [ 1377s] 
> [ 1377s] Is it OK to download and put it in "/home/abuild/.local/share/Nuitka/appimagetool-x86_64.AppImage/x86_64/12".
> [ 1377s] 
> [ 1377s] No installer needed, cached, one time question.
> [ 1377s] 
> [ 1377s] Proceed and download? [Yes]/No 
> [ 1377s] The onefile tests are not run due to missing requirements.
> 

From https://build.opensuse.org/package/live_build_log/home:kayhayen/Nuitka/openSUSE_Leap_15.3/x86_64

Do the question output is not an issue in my eyes, and without stdin, the reply "no" is defaulted now, so this is considered fixed in my eyes.
