### ISSUE TITLE
import error win32gui

### ISSUE THREAD

**Issue by Pro100rus32** [Nuitka/Nuitka#993]
```
0.6.13rc3
Python: 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
Executable: C:\Users\andre\AppData\Local\Programs\Python\Python39\python.exe
OS: Windows
Arch: x86_64
```

Code:
`import win32gui`

Nuitka:
`python -m nuitka --clang --standalone --windows-uac-admin --output-dir=E:\test\test\test "C:\Users\andre\Desktop\test.py"`

Output code:
```
Traceback (most recent call last):
  File "E:\test\test\test\test.dist\test.py", line 1, in <module>
ImportError
```

**Comment by kayhayen** [comment]
@Pro100rus32 not an issue anymore? Sorry, didn't find the time yet.

**Comment by Pro100rus32** [comment]
Everything works)

Thank!)

**Comment by kayhayen** [comment]
@Pro100rus32 next time you close an issue just say why too, helps me not be in doubt :)
